### DISCUSSION TITLE
[Support]: Frigate Suddenly Stopped Recording

### DISCUSSION THREAD

**Discussion by jamesphw** [blakeblackshear/frigate#10004] [General Support]
### Describe the problem you are having

Recording has been working fine for about 5 days since I set up Frigate, but has suddenly stopped working, seemingly due to an I/O error. The error in the logs doesn't say what volume is not working, it just says "X: No such file or directory".

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.19
  port: 1883
  topic_prefix: frigate
  user: frigatemqttuser
  password: XXX

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  rtsp:
    username: XXX
    password: XXX
  streams:
    front_doorbell:
    - ffmpeg:https://192.168.50.171/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=copy#audio=opus
    - rtsp://XXX:XXX@192.168.50.171:554/h264Preview_01_main
    front_doorbell_sub:
    - ffmpeg:https://192.168.50.171/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=XXX&password=XXX#audio=copy#audio=opus
    - rtsp://XXX:XXX@192.168.50.171:554/h264Preview_01_sub     # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
  webrtc:
    candidates:
    - 192.168.50.41:8555
    - stun:8555

cameras:
  front_doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
      - path: x   # <--- the name here must match the name of the camera in restream
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/front_doorbell_sub?video=copy&audio=aac   # <--- the name here must match the name of the camera_sub in restream
        input_args: preset-rtsp-restream
        roles:
        - detect
      hwaccel_args: preset-vaapi
    snapshots:
      enabled: true
      required_zones:
      - front_property
    record:
      enabled: true
      retain:
        days: 2
      events:
        required_zones:
        - front_property
        retain:
          default: 14
          mode: active_objects
    detect:
      enabled: true
    motion:
      mask:
      - 199,283,112,273,64,257,0,234,0,0,486,0,521,89,515,287,268,282
    objects:
      track:
      - person
      - cat
      - dog
      filters:
        cat:
          threshold: 0.4
        dog:
          threshold: 0.4
    zones:
      front_property:
        coordinates: 36,238,74,263,112,271,511,288,467,480,236,480,58,480,0,480,0,238
```

### Relevant log output

```shell
2024-02-23 21:08:11.922044799  [2024-02-23 21:08:09] frigate.app                    INFO    : Capture process started for front_doorbell: 341
2024-02-23 21:08:29.387584124  [2024-02-23 21:08:29] ffmpeg.front_doorbell.record   ERROR   : x: No such file or directory
2024-02-23 21:08:29.397053743  [2024-02-23 21:08:29] watchdog.front_doorbell        INFO    : Terminating the existing ffmpeg process...
2024-02-23 21:08:29.397379350  [2024-02-23 21:08:29] watchdog.front_doorbell        INFO    : Waiting for ffmpeg to exit gracefully...
2024-02-23 21:08:39.416417391  [2024-02-23 21:08:39] ffmpeg.front_doorbell.record   ERROR   : x: No such file or directory
2024-02-23 21:08:39.417197739  [2024-02-23 21:08:39] watchdog.front_doorbell        INFO    : Terminating the existing ffmpeg process...
2024-02-23 21:08:39.417575929  [2024-02-23 21:08:39] watchdog.front_doorbell        INFO    : Waiting for ffmpeg to exit gracefully...
2024-02-23 21:08:49.440122947  [2024-02-23 21:08:49] ffmpeg.front_doorbell.record   ERROR   : x: No such file or directory
```

### FFprobe output from your camera

```shell
Can't get it from the front-end (seems to hang).
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink Wifi Doorbell 

### Any other information that may be helpful

Recording was working fine for about 5 days and suddenly stopped. Restarting the docker container hasn't helped.

Live streams of the camera are fine, detection is working fine (including receiving the events in Home Assistant), and snapshots are all saved correctly in the events list. But live and 

My docker compose has the following as the mounted volumes, and I can confirm that the mount /mnt/NVR/Media is otherwise working fine on the server and has space.

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/NVR/Media:/media/frigate
```
