### DISCUSSION TITLE
[Support]: Frigate v0.13 consuming a lot more memory than v0.12

### DISCUSSION THREAD

**Discussion by heisenberg2980** [blakeblackshear/frigate#10005] [General Support]
### Describe the problem you are having

After updating Frigate to v0.13 it is using double amount of memory than v0.12, increasing from less than 5Gb to almost 10Gb using the same config file, and crashing when trying to see the timeline from Home Assistant.

This is the top command executed inside the container using v0.12.1, where process python3 is using 2.4% of memory:
![Screenshot 2024-02-23 204623](https://github.com/blakeblackshear/frigate/assets/58039006/55095bc0-c031-40a4-aa54-9878c37d911b)

And the same top command after the update to v0.13.2 shows process python3 using  9% of memory:

![image](https://github.com/blakeblackshear/frigate/assets/58039006/62ccbc2d-b3e5-4da3-a19f-6bee3665ec5e)

The issue might be related to the size of the database (3Gb at the moment) as it does not happen when starting Frigate v0.13 with an empty database as shown here (python3 using 1% of memory):
![image](https://github.com/blakeblackshear/frigate/assets/58039006/53368595-cc70-4e98-91c2-0dd29e40d4db)

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.x
  user: xxxxxxxxx
  password: xxxxxxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

objects:
  track:
    - person
    - cat
  filters:
    person:
      max_area: 125000
      threshold: 0.8
    cat:
      max_area: 30000
      threshold: 0.75

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  mode: continuous 
  width: 1920
  height: 1080


record:
  enabled: True
  retain:
    days: 30
  events:
    retain:
      default: 120

snapshots:
  retain:
    default: 10000

detect:
  enabled: True
  width: 1280 # <---- update for your camera's resolution
  height: 720 # <---- update for your camera's resolution
  fps: 5
  stationary:
    interval: 150

motion:
  contour_area: 20
  mask:
    - 1236,29,1236,60,880,61,880,27

go2rtc:
  streams:
    cam_1:
      - rtsp://xxx:xxx@192.168.x.31:554/cam/realmonitor?channel=1&subtype=0
    cam_1_sub:
      - rtsp://xxx:xxx@192.168.x.31:554/cam/realmonitor?channel=1&subtype=2
    cam_2:
      - rtsp://xxx:xxx@192.168.x.32:554/cam/realmonitor?channel=1&subtype=0
    cam_2_sub:
      - rtsp://xxx:xxx@192.168.x.32:554/cam/realmonitor?channel=1&subtype=2
    cam_3:
      - rtsp://xxx:xxx@192.168.x.33:554/cam/realmonitor?channel=1&subtype=0
    cam_3_sub:
      - rtsp://xxx:xxx@192.168.x.33:554/cam/realmonitor?channel=1&subtype=2
    cam_4:
      - rtsp://xxx:xxx@192.168.x.34:554/cam/realmonitor?channel=1&subtype=0
    cam_4_sub:
      - rtsp://xxx:xxx@192.168.x.34:554/cam/realmonitor?channel=1&subtype=2
    cam_5:
      - rtsp://xxx:xxx@192.168.x.35:554/cam/realmonitor?channel=1&subtype=0
    cam_5_sub:
      - rtsp://xxx:xxx@192.168.x.35:554/cam/realmonitor?channel=1&subtype=2
    cam_6:
      - rtsp://xxx:xxx@192.168.x.36:554/cam/realmonitor?channel=1&subtype=0
    cam_6_sub:
      - rtsp://xxx:xxx@192.168.x.36:554/cam/realmonitor?channel=1&subtype=2
    cam_7:
      - rtsp://xxx:xxx@192.168.x.37:554/cam/realmonitor?channel=1&subtype=0
    cam_7_sub:
      - rtsp://xxx:xxx@192.168.x.37:554/cam/realmonitor?channel=1&subtype=2
    cam_8:
      - rtsp://xxx:xxx@192.168.x.38:554/cam/realmonitor?channel=1&subtype=0
    cam_8_sub:
      - rtsp://xxx:xxx@192.168.x.38:554/cam/realmonitor?channel=1&subtype=2
    cam_9:
      - rtsp://xxx:xxx@192.168.x.39:554/live/main
    cam_9_sub:
      - rtsp://xxx:xxx@192.168.x.39:554/live/sub

cameras:
  cam_1: # Main Street 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_1 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          threshold: 0.74
          mask:
            - 1449,1512,2688,1512,1848,888,1676,836
        car:
          min_area: 10000
          mask:
            - 0,0,611,0,607,160,0,334
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        - 930,1512,1905,1512,2075,1182,1590,983
        - 2014,704,2073,704,2153,336,2077,321
    zones:
      outside_main_door:
        coordinates: 714,538,0,691,0,1512,1168,1512,2161,1002,2237,785

  cam_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_2 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam_2_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 1236,29,1236,60,880,61,880,27
        - 202,720,869,720,564,436,162,568
    objects:
      filters:
        person:
          min_score: 0.8

  cam_3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_3 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        - 2688,0,2688,281,2538,301,2103,160,2091,0
        - 2205,1520,1574,1143,951,1520
    objects:
      mask:
        - 142,241,663,109,1379,57,1392,0,91,0
      filters:
        person:
          max_area: 600000
        cat:
          max_area: 80000

  cam_4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_4 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
    objects:
      filters:
        person:
          threshold: 0.8

  cam_5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_5 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 2688,0,2688,932,1032,376,997,0
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          max_area: 600000
          threshold: 0.8
          mask:
            - 50,1450,200,1450,200,1200,50,1200

  cam_6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_6 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    zones:
      Worktop:
        coordinates: 1771,531,2688,865,2403,1520,1987,1520,1743,1520,2332,877,1654,599
      Island:
        coordinates: 954,726,1285,1022,1609,865,1207,654
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
    objects:
      filters:
        person:
          max_area: 600000
          threshold: 0.8
          mask:
            - 2201,797,2288,849,2192,971,2688,1195,2688,714,2267,546
        cat:
          max_area: 80000

  cam_7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_7 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam_7_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    objects:
      mask:
        - 0,0,0,409,43,498,220,374,184,0

  cam_8:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_8 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam_8_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    objects:
      filters:
        person:
          threshold: 0.81
        cat:
          max_area: 30000
          threshold: 0.8

  cam_9:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_9 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 426,29,426,60,80,61,80,27
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5655369f9140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/cam_1':
  Metadata:
    title           : go2rtc/1.6.0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 2688x1520, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua HDW5442TM
