### DISCUSSION TITLE
[Question]: What does a broken pipe error 32 mean?

### DISCUSSION THREAD

**Discussion by rocket59** [blakeblackshear/frigate#10003] [Ask A Question] [answered]
### What is your question:

When cycling through the camera live views I get this error pop up often:

`[2024-02-24 08:36:56] ws4py                          ERROR   : Error when terminating the connection: [Errno 32] Broken pipe`

Should I be concerned? Other than the error everything seems to be working.

I have 3 cameras connected for testing and they are identical Wyze Cam v3s. Configs are the identical for each other than the masks.  I'm on 0.13.1.

```
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  topic_prefix: frigate
  host: xxx
  port: 1883
  user: xxx
  password: xxx
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    back_yard:
      - ffmpeg:"ffmpeg:"rtsp://xx:xxx@192.168.xx:8554/1080p"
birdseye:
  enabled: True
  mode: continuous
cameras:
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    mqtt:
      enabled: True        
    snapshots:
      enabled: True
      retain:
        default: 5
    record:
      enabled: False
      events:
       retain:
        default: 5
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          mask: xxxxxx
    motion:
      mask:
        - xxxxx
      improve_contrast: False
```
