### DISCUSSION TITLE
[Support]: Frigate MQTT Events - Can't figure out UPDATE events

### DISCUSSION THREAD

**Discussion by lavinir** [blakeblackshear/frigate#10014] [General Support]
### Describe the problem you are having

Hey all, 
I'm trying to get proper Home Assistant notifications only for an actual event that was caught in the camera (as close to real time as possible). In theory I don't need to notify at all about UPDATE events except that this seems to be an issue for Cars as from what I could tell if a Car in the driveway is stationary and is tracked, once it starts moving again it will register as an UPDATE not a NEW event. 
I tried parsing the UPDATE event for some clue as to how I can ignore 'none new' updates, and am filtering on 
**Stationary: False**  and **Entered_Zones: [Relevant Zone]** but I can still get an update about an event that occurred an hour ago where the "Before" would show no zones and the "After" payload will show the Relevant Zone. 

What is the proper way to filter these out ?

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
    zones:
      car_entrance:
        coordinates: 494,348,0,351,0,320,475,306
        objects:
          - car
          - bicycle
          - motorcycle
      gate_zone:
        coordinates: 0,480,56,358,640,342,640,480
        objects:
          - person
    record:
        events:
          pre_capture: 5
          post_capture: 5
          required_zones:
            - gate_zone
            - car_entrance
    snapshots:
      required_zones:
        - gate_zone
        - car_entrance
```

### Relevant log output

```shell
Example MQTT Event for an UPDATE that occurs an hour after the event took place:

{
    "topic": "frigate/events",
    "payload": {
        "before": {
            "id": "1708769658.573276-b5fns4",
            "camera": "video_doorbell",
            "frame_time": 1708773809.192199,
            "snapshot": {
                "frame_time": 1708771860.353668,
                "box": [
                    222,
                    227,
                    493,
                    464
                ],
                "area": 64227,
                "region": [
                    0,
                    0,
                    788,
                    788
                ],
                "score": 0.83203125,
                "attributes": []
            },
            "label": "car",
            "sub_label": null,
            "top_score": 0.84375,
            "false_positive": false,
            "start_time": 1708769658.573276,
            "end_time": null,
            "score": 0.7265625,
            "box": [
                218,
                223,
                490,
                448
            ],
            "area": 61200,
            "ratio": 1.208888888888889,
            "region": [
                168,
                160,
                488,
                480
            ],
            "stationary": false,
            "motionless_count": 1,
            "position_changes": 7,
            "current_zones": [],
            "entered_zones": [],
            "has_clip": false,
            "has_snapshot": false,
            "attributes": {},
            "current_attributes": []
        },
        "after": {
            "id": "1708769658.573276-b5fns4",
            "camera": "video_doorbell",
            "frame_time": 1708773815.914088,
            "snapshot": {
                "frame_time": 1708771860.353668,
                "box": [
                    222,
                    227,
                    493,
                    464
                ],
                "area": 64227,
                "region": [
                    0,
                    0,
                    788,
                    788
                ],
                "score": 0.83203125,
                "attributes": []
            },
            "label": "car",
            "sub_label": null,
            "top_score": 0.84375,
            "false_positive": false,
            "start_time": 1708769658.573276,
            "end_time": null,
            "score": 0.6171875,
            "box": [
                233,
                230,
                487,
                319
            ],
            "area": 22606,
            "ratio": 2.853932584269663,
            "region": [
                231,
                0,
                551,
                320
            ],
            "stationary": false,
            "motionless_count": 1,
            "position_changes": 7,
            "current_zones": [
                "car_entrance"
            ],
            "entered_zones": [
                "car_entrance"
            ],
            "has_clip": true,
            "has_snapshot": true,
            "attributes": {},
            "current_attributes": []
        },
        "type": "update"
    },
    "qos": 0,
    "retain": false,
    "_msgid": "d8b4505e456d4455"
}
```

### FFprobe output from your camera

```shell
[Not Relevant]
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Reolink Video Doorbell
