### DISCUSSION TITLE
[Config Support]: Leave Detection/Snapshot/Recording Off on Frigate Restart

### DISCUSSION THREAD

**Discussion by databoy2k** [blakeblackshear/frigate#10017] [Config Support] [answered]
### Describe the problem you are having

When my cameras load, I do not want them to automatically start detecting/taking snapshots/recording. Is there a configuration entry to have that off until I manually turn it on?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: ip
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  wroom_cam_east:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://user:pass@ip/ch0_0.h264
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    motion:
        mask:
          - 335,0,336,43,0,43,0,0
  fext_cam_door:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://user:pass@ip/Streaming/Channels/102
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
  fext_cam_north:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://ip/ch0_0.h264
          roles:
            - detect
            - record

ffmpeg:
  global_args: -hide_banner -loglevel warning
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p

record:
  enabled: True
  events:
    retain:
      default: 10

objects:
  track:
    - person
    - car
  filters:
    car:
      mask:
        - 1280,255,1280,0,511,0
    person:
      mask:
        - 570,144,199,183,48,91,263,35
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
