### DISCUSSION TITLE
[Support]: Frigate cannot connect to local MQTT -> ERROR   : Unable to publish to stats: client is not connected

### DISCUSSION THREAD

**Discussion by ZeluisFS** [blakeblackshear/frigate#10022] [General Support]
### Describe the problem you are having

Hi there,

Im a big fan of Frigate, and I have been using alot integrated with Home Assistant to see the cameras.
I have Home Assistant, Mosquitto MQTT broker and Frigate running as docker containers.
Frigate is not able to connect to Mosquitto broker, but Home Assistant can, and even on my laptop I installed MQTT Explorer client and I can connect to Mosquitto too with it.
Only frigate having issues with MQTT.
Cameras streams are working fine...
I tried changing the host of MQTT (on Frigate config) using the dns local name, tried with docker container network and using its ip directy, and none of them are able to work.

Im using the most recent docker images for each container...

P.S. Mosquitto MQTT Broker logs dont show anything. It seems Frigate can't even connect to it

Can someone help me?

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
homeassistant:
        container_name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        restart: always
        privileged: true
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./homeassistant/config:/config
            - /run/dbus:/run/dbus:ro
        network_mode: host # running on port 8123
        # extra_hosts:
        #     nginx_static_ip: "172.10.23.3"

    frigate:
        container_name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        depends_on:
            - nginx
        restart: always
        devices:
            - /dev/dri:/dev/dri # Mount GPU device for AMD Ryzen 5
        privileged: true
        shm_size: "128mb" # update for your cameras based on calculation above
        environment:
            FRIGATE_RTSP_PASSWORD: passwordHidden
            LIBVA_DRIVER_NAME: radeonsi
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./frigate/:/config/
            - /home/zeluisfs/my_projects/docker_bind_volumes/frigate:/media/frigate
            - type: tmpfs # 1 GB of memory
              target: /tmp/cache
              tmpfs:
                size: 1000000000
        ports:
            - "5000:5000" # Port used by the Web UI -> Used so HA can access it via frigate integration since it cannot use the proxy
            - "8554:8554" # RTSP feeds
            - "8555:8555/tcp" # WebRTC over tcp
            - "8555:8555/udp" # WebRTC over udp
        networks:
            - nginx_network

    mosquitto: # (MQTT Broker) Used for integration fo frigate with HA for now
        container_name: mosquitto
        image: eclipse-mosquitto
        restart: always
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        ports: # Since HA is running on host network we need to export ports for it to access
            - "1883:1883"
            - "9001:9001"
```

### Relevant log output

```shell
2024-02-24 20:37:34.362585711  [INFO] Preparing Frigate...
2024-02-24 20:37:34.370902792  [INFO] Starting Frigate...
2024-02-24 20:37:35.476075614  [2024-02-24 20:37:35] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-02-24 20:37:35.501438605  [2024-02-24 20:37:35] peewee_migrate.logs            INFO    : Starting migrations
2024-02-24 20:37:35.504398154  [2024-02-24 20:37:35] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-24 20:37:35.507395631  [2024-02-24 20:37:35] frigate.app                    INFO    : Recording process started: 587
2024-02-24 20:37:35.509118682  [2024-02-24 20:37:35] frigate.app                    INFO    : go2rtc process pid: 89
2024-02-24 20:37:35.520958837  [2024-02-24 20:37:35] detector.cpu                   INFO    : Starting detection process: 597
2024-02-24 20:37:35.522157409  [2024-02-24 20:37:35] frigate.app                    INFO    : Output process started: 599
2024-02-24 20:37:35.523801673  [2024-02-24 20:37:35] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-02-24 20:37:35.529153477  [2024-02-24 20:37:35] frigate.app                    INFO    : Camera processor started for Tapo_Camera_45EA_entry_hall: 603
2024-02-24 20:37:35.532404079  [2024-02-24 20:37:35] frigate.app                    INFO    : Camera processor started for Tapo_Camera_55DA_Living_Room: 604
2024-02-24 20:37:35.535885524  [2024-02-24 20:37:35] frigate.app                    INFO    : Capture process started for Tapo_Camera_45EA_entry_hall: 605
2024-02-24 20:37:35.540424799  [2024-02-24 20:37:35] frigate.app                    INFO    : Capture process started for Tapo_Camera_55DA_Living_Room: 610
2024-02-24 20:37:40.833228966  [2024-02-24 20:37:40] frigate.comms.mqtt             ERROR   : Unable to publish to Tapo_Camera_45EA_entry_hall/all: client is not connected
2024-02-24 20:37:40.833338486  [2024-02-24 20:37:40] frigate.comms.mqtt             ERROR   : Unable to publish to Tapo_Camera_45EA_entry_hall/motion: client is not connected
2024-02-24 20:37:40.864098610  [2024-02-24 20:37:40] frigate.comms.mqtt             ERROR   : Unable to publish to Tapo_Camera_55DA_Living_Room/all: client is not connected
2024-02-24 20:38:12.524282681  [2024-02-24 20:38:12] frigate.comms.mqtt             ERROR   : Unable to publish to Tapo_Camera_45EA_entry_hall/motion: client is not connected
2024-02-24 20:38:50.899903989  [2024-02-24 20:38:50] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
2024-02-24 20:39:52.029982112  [2024-02-24 20:39:52] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
```

### FFprobe output from your camera

```shell
Cameras are working well, so I did not do this
```

### Frigate stats

```json
{"cameras":{"Tapo_Camera_45EA_entry_hall":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":605,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":612,"pid":603,"process_fps":5.1,"skipped_fps":0.0},"Tapo_Camera_55DA_Living_Room":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":610,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":615,"pid":604,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"2.2","cpu_average":"2","mem":"0.1"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"1.2","cpu_average":"1","mem":"1.7"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"177":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"210":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"255":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"290":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"322":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"339":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"360":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"585":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.7"},"587":{"cmdline":"frigate.recording_manager","cpu":"0.8","cpu_average":"0","mem":"0.9"},"596":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"597":{"cmdline":"frigate.detector.cpu ","cpu":"0.0","cpu_average":"0","mem":"0.9"},"599":{"cmdline":"frigate.output       ","cpu":"0.6","cpu_average":"0","mem":"0.9"},"603":{"cmdline":"frigate.process:Tapo_Camera_45EA_entry_hall","cpu":"0.8","cpu_average":"0","mem":"1.1"},"604":{"cmdline":"frigate.process:Tapo_Camera_55DA_Living_Room","cpu":"0.8","cpu_average":"0","mem":"0.9"},"605":{"cmdline":"frigate.capture:Tapo_Camera_45EA_entry_hall","cpu":"1.9","cpu_average":"2","mem":"0.9"},"610":{"cmdline":"frigate.capture:Tapo_Camera_55DA_Living_Room","cpu":"2.4","cpu_average":"2","mem":"0.9"},"612":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Tapo_Camera_45EA_entry_hall -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Tapo_Camera_45EA_entry_hall@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.7","cpu_average":"3","mem":"1.2"},"615":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Tapo_Camera_55DA_Living_Room -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Tapo_Camera_55DA_Living_Room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.6","cpu_average":"3","mem":"0.9"},"618":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"619":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"620":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"628":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/Tapo_Camera_55DA_Living_Room?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/c1998e754bb04cbf9a75b275cf5ef02d","cpu":"1.9","cpu_average":"1","mem":"0.1"},"629":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/Tapo_Camera_45EA_entry_hall?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/3d272054f887388e332fb47956c6caa9","cpu":"1.9","cpu_average":"1","mem":"0.1"},"9095":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":42.52,"pid":597}},"gpu_usages":{"amd-vaapi":{"gpu":"1.67%","mem":"8.68%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":585},"recording":{"pid":587}},"service":{"last_updated":1708809575,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":120.7,"mount_type":"tmpfs","total":128.0,"used":7.3},"/media/frigate/clips":{"free":195854.0,"mount_type":"ext4","total":477061.4,"used":260736.9},"/media/frigate/recordings":{"free":195854.0,"mount_type":"ext4","total":477061.4,"used":260736.9},"/tmp/cache":{"free":952.2,"mount_type":"tmpfs","total":953.7,"used":1.5}},"temperatures":{},"uptime":2520,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C200

**Comment by ZeluisFS** [comment]
Ill post here my Frigate config file too:

```
mqtt:

  enabled: true
  host: 192.168.50.173 # zeserver.local and 192.168.50.173 was not working
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hidden_user
  password: hidden_password

go2rtc:
  streams:
    Tapo_Camera_45EA_entry_hall:
      - rtsp://zeluisfs:Camelo.1989@192.168.50.145:554/stream1
      - "ffmpeg:Tapo_Camera_45EA_entry_hall#audio=aac"
    Tapo_Camera_55DA_Living_Room:
      - rtsp://zeluisfs:Camelo.1989@192.168.50.20:554/stream1
      - "ffmpeg:Tapo_Camera_55DA_Living_Room#audio=aac"
  webrtc:
    candidates:
      - 192.168.50.173:8555 # With cameras it has to be the actual IP address in this case of the host machine
      - stun:8555

cameras:
  Tapo_Camera_45EA_entry_hall:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Tapo_Camera_45EA_entry_hall
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      threshold: 150 # 1 (Max Sensivity) - 255 (Min Sensitivity)
      contour_area: 30 # 10 - high sensitivity 50 - low sensitivity
    mqtt:
      enabled: true
    record:
      enabled: true
      events:
        objects:
          - person
        retain:
          default: 28
          mode: active_objects
  Tapo_Camera_55DA_Living_Room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Tapo_Camera_55DA_Living_Room
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      threshold: 90 # 1 (Max Sensivity) - 255 (Min Sensitivity)
      contour_area: 20 # 10 - high sensitivity 50 - low sensitivity
    mqtt:
      enabled: true
    record:
      enabled: true
      events:
        objects:
          - person
        retain:
          default: 28
          mode: active_objects
```
