### DISCUSSION TITLE
[Support]: HTTP API help with creating a recording outside of detection - Home Assistant

### DISCUSSION THREAD

**Discussion by CykloneFij** [blakeblackshear/frigate#10024] [General Support]
### Describe the problem you are having

I have  a shell command in HA that will create a recording using the HTTP API:
`shell_command:
  backyard_force_record: 'curl -d "duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://xxx.xxx.xxx.xxx:5000/api/events/backyard/forced/create'`
It works, an event is created in Frigate on the camera.  However, it is only a snapshot.  There is no video.  The response from the above command is:
`stdout: >-
  {"event_id":"1708645049.409679-gi943a","message":"Successfully created
  event.","success":true}
stderr: "% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   129  100    95  100    34    472    169 --:--:-- --:--:-- --:--:--   645"
returncode: 0`

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  user: xxxxxxx
  password: xxxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
    # rtmp: -c copy -f flv -tag:v hvc1
    detect: -f rawvideo -pix_fmt yuv420p
record:
  enabled: True
  retain:
    days: 0
    mode: active_objects    # all, motion, active_objects
  events:
    retain:
      default: 14
      mode: active_objects  # all, motion, active_objects
    pre_capture: 3
    post_capture: 10
  export:
    timelapse_args: "-vf setpts=0.02*PTS -r 30"
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  retain:
    default: 14
go2rtc:
  streams:
    backyard_rtsp_gpu:
      - rtsp://192.168.1.31:554/live0
      - "ffmpeg:backyard_rtsp_gpu#video=h264#width=1920#height=1080#raw=-fpsmax 10#hardware=cuda#audio=aac"
cameras:
  backyard:
    enabled: True
    record:
      enabled: True
      retain:
        days: 0                 # 0 here with mode: active_objects
        mode: active_objects    # all, motion, active_objects
      events:
        retain:
          default: 14
          mode: active_objects  # all, motion, active_objects
        pre_capture: 3
        post_capture: 10
    ffmpeg:
      #hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_rtsp_gpu                                                 # original camera rtsp stream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      fps: 10
      width: 1920
      height: 1080
      # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 150
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.75
        cat:
          threshold: 0.70
        dog:
          threshold: 0.60
    live:
      stream_name: backyard_rtsp_gpu
```

### Relevant log output

```shell
2024-02-24 19:12:10.644124647  192.168.1.15 - - [24/Feb/2024:19:12:10 -0500] "POST /api/events/backyard/forced/create HTTP/1.1" 200 95 "-" "curl/8.5.0" "-"
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Eufy Outdoor Cam Pro
