### DISCUSSION TITLE
[Support]: Frigate stops working and throws error after *mv: '/media/frigate/frigate.db' and '/config/frigate.db' are the same file*

### DISCUSSION THREAD

**Discussion by davidDS96** [blakeblackshear/frigate#10026] [General]
I am running Frigate (0.13) in a docker container pulling the image from ```ghcr.io/blakeblackshear/frigate:stable```.
After some time (typically a couple of hours), Frigate crashes and stops working and throws the following error message:
```
mv: '/media/frigate/frigate.db' and '/config/frigate.db' are the same file
[INFO] Service Frigate exited with code 1 (by signal 0)
```
I think this issue is closely related to https://github.com/blakeblackshear/frigate/issues/9857. However, I end up constantly removing the db file and restarting the Frigate docker container.

Can anyone give an answer to this issue? 
Thanks in advance!

**Comment by blakeblackshear** [comment]
We will need to see your compose file

**Comment by davidDS96** [comment]
Hi!

I am running Frigate using TrueNAS and with the help of a Kubernetes container. The docker compose file is similar to this one below:

```
version: "3.9"
services:
  frigate:
    container_name: dockerfrigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    volumes:
      - /mnt/Storage/localtime:/etc/localtime
      - /mnt/Storage/frigate/config:/config
      - /mnt/Storage/frigat:/media/frigate
    ports:
      - "15000:5000"
      - "11935:1935"
```
