### DISCUSSION TITLE
What do these values even mean

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#10033] [General]
I was wondering if someone could help explain what these settings mean on the attached screenshot 
![Screenshot_20240225-115334](https://github.com/blakeblackshear/frigate/assets/19710296/48359861-9b7b-40ea-b09b-fef419ece36e)

So for my Front Door camera that is a 2K 20FPS camera it shows capture is only 5.1 FPS which odd. And CPU and Memory it's hard to tell what stress or load this is actually putting my my system. Can anyone explain this in a bit more layman's terms?

**Comment by NickM-27** [comment]
`capture` refers to the capturing of the detect stream for object detection. It has nothing to do with recordings. These CPU usage for ffmpeg looks a bit high, are you using hwaccel

**Comment by MrCaspan** [comment]
I am only doing 24x7 recording right now. is there a way to disable object detection.

Also I am using my GTX 1080 to do stream decoding if that is what you mean?

```
mqtt:
  enabled: false

# Enable recording of all cameras and retain it for 14 days
record:
  enabled: true
  retain:
    days: 14

# Use the GPU to help with decoding streams adn record audio!
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

#snapshots:
#  enabled: True
#  retain:
#    default: 10
#  bounding_box: True

# Enable birdseye option to see any cameras with motion on them 
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

detect:
  enabled: False
  width: 1920
  height: 1080
#  fps: 5

#detectors:
#  coral:
#    type: edgetpu
#    device: pci:0


motion:
  mask:
    - 1364,76,1894,68,1891,0,1361,0 # Mask off time on all cameras

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.210/live0
          roles:
            - record

  Deck:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.214/live0
          roles:
            - record

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.213/h264Preview_01_main
          roles:
            - record

  Front_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.212/live0
          roles:
            - record
    motion:
      mask:
        - 1364,76,1894,68,1891,0,1361,0 # Mask of time
        - 1920,1080,1806,1080,1800,1053,1805,992,1803,899,1838,797,1920,761 # Mask off Christmas lights

  Ripleys_Room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.211/live0
          roles:
            - record

  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.217/h264Preview_01_main
          roles:
            - record
```

**Reply by NickM-27** [reply]
you have already disabled object detection, there is no way to disable the decoding of the stream

**Comment by MrCaspan** [comment]
ahh okay so it will do the decoding no matter what. Do the rest of my
settings seems okay?

**Comment by MrCaspan** [comment]
okay so question since I can't disable it I have two streams available to me and the only stream that I'm pulling in right now is the high resolution one because I was doing recording only. So the capture is dealing with a 2k 20 frame per second stream, should I be using the second stream? that's a much lower quality and set it to 5 SPS on the camera?

**Reply by NickM-27** [reply]
using the second stream will lower cpu usage considerably

**Reply by MrCaspan** [reply]
Just so I make sure I have this right. On my Reolink Cameras, I set the sub stream resolution to 640x480 and 4FPS

then in my frigate config I added this to each camera

```
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.86.213/h264Preview_01_main
          roles:
            - record
        - path: rtsp://user:pass@192.168.86.213/h264Preview_01_sub
          roles:
            - detect
```

And I use the sub stream for detect.  Is that correct?

**Reply by NickM-27** [reply]
yes

**Reply by MrCaspan** [reply]
Problem I have is that I have crappy Eufy single stream cameras that I am replacing with Reolink cameras so it looks like I will have to add a lower detect setting to each of my Reolink cameras until I can set it globally once I have all Reolink cameras that support the sub stream

I currently have this at the top of my config

```
detect:
  enabled: False
  width: 1920
  height: 1080
#  fps: 5
```

I added this to all my cameras that are Reolink

```
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.86.213/h264Preview_01_main
          roles:
            - record
        - path: rtsp://user:pass@192.168.86.213/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: False
      width: 640
      height: 360
      fps: 4
```

Would this be correct way of doing this untill all my cameras have a sub stream and I can set it globaly at the top of my config?
