### DISCUSSION TITLE
[Detector Support]: Mini PC Beelink S12, Proxmox, Coral

### DISCUSSION THREAD

**Discussion by Bomas7889** [blakeblackshear/frigate#10035] [Detector Support]
### Describe the problem you are having

Hallo. Habe den "Beelink Mini S12 Mini PC, Intel 12. Prozessor N100" und darauf Proxmox. Habe HomeAssistant laufen und darin Frigate mit 4 Kameras. Habe den Google Coral installiert. Leider ist die CPU Auslastung des Beelink immer noch sehr hoch (50%).  Habt ihr tipps wie ich dies verbessern kann ??? Grüße 

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb
#mqtt:
#  host: 192.168.168.201
#  port: 1883
#  topic_prefix: frigate
#  client_id: frigate
#  user: mqttuser
#  password: xxx
#  stats_interval: 60
cameras:

  # Tür
  Tür:
    ffmpeg:
      inputs:
        #  High Resolution Stream
      - path: rtsp://admin:xxxxx@192.168.168.102:554/av0_0
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://admin:xxxxx4@192.168.168.102:554/av0_1
        roles:
        - detect
    rtmp:
      enabled: false

    detect:
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
      - person
      filters:
        person:
          threshold: 30

    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 5

    zones:
      Spion_zone:
        coordinates: 1920,1058,1920,239,0,234,0,1055

    motion:
      mask: 1920,1058,1920,239,0,234,0,1055
      threshold: 30

# Straße
  Strasse1:
    ffmpeg:
      inputs:
        #  High Resolution Stream
      - path: rtsp://admin:NKYUQB@192.168.168.105:554/live/ch0
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://admin:xxxxx@192.168.168.105:554/live/ch1
        roles:
        - detect
    rtmp:
      enabled: false

    detect:
      width: 1820
      height: 1080
      fps: 5

    objects:
      track:
      - person
      - car
      filters:
        person:
          threshold: 30

    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 2

    zones:
      Strasse1_zone:
        coordinates: 552,1014,1543,858,1920,461,1879,112,275,185

    motion:
      mask: 552,1014,1543,858,1920,461,1879,112,275,185
      threshold: 30

# Wohnzimmer
  Wohnzimmer:
    ffmpeg:
      inputs:
      #  High Resolution Stream
      - path: rtsp://admin:CBHCYG@192.168.168.104:554/live/ch0
        roles:
        - record
      # Low Resolution Stream
      - path: rtsp://admin:xxxxx@192.168.168.104:554/live/ch1
        roles:
        - detect
    rtmp:
      enabled: false

    detect:
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
      - person
      - cat
      filters:
        person:
          threshold: 30

    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 2

    zones:
      Wohnzimmer_zone:
        coordinates: 52,995,1558,1080,1558,49,1157,61,1101,278,986,285,951,76,588,93

    motion:
      mask: 52,995,1558,1080,1558,49,1157,61,1101,278,986,285,951,76,588,93
      threshold: 20

# Flur
  Flur:
    ffmpeg:
      inputs:
#  High Resolution Stream
      - path: rtsp://admin:xxxxx@192.168.168.101:554/live/ch0
        roles:
        - record
# Low Resolution Stream
      - path: rtsp://admin:VTQVDL@192.168.168.101:554/live/ch1
        roles:
        - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      
    objects:
      track:
      - person
      - cat
      filters:
        person:
          threshold: 30

    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 2

    zones:
      Flur_zone:
        coordinates: 345,673,768,720,951,720,1042,299,817,54,489,88,167,505

    motion:
      mask: 345,673,768,720,951,720,1042,299,817,54,489,88,167,505
      threshold: 30

```

### docker-compose file or Docker CLI command

```yaml
Proxmox VM
```

### Relevant log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
