### DISCUSSION TITLE
[Config Support]: Reolink Doorbell setup - value is not a valid list (type=type_error.list)

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#10067] [Config Support] [answered]
### Describe the problem you are having

Hoping to get another set of eyes on this to figure out what I'm doing wrong.  It looks right to me, trying to follow the 'Getting Started' guide

### Version

3.9

### Frigate config file

```yaml
mqtt: 
  enabled: false
  #host: core-mosquito
  #user: mqtt-client
  #password: password

detectors:
  #coral_usb:
  #  type: edgetpu
  #  device: usb
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    front_doorbell:
      - "ffmpeg:http://192.168.1.30/flv?port=554app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.1.30/Preview_01_sub
    front_doorbell_sub:
      - "ffmpeg:http://192.168.1.30/flv?port=554&app=bcs&stream=channel0_ext.bcs&user=admin&password=password"

cameras:
  front_doorbell: 
    ffmpeg: 
      inputs:
        - path: rtsp://192.168.1.30:554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            -record
        - path: rtsp://192.168.1.30:554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            -detect
      hwaccel_args: preset-vaapi
    #detect:
     # enabled: True # <---- turn on detection
```

### Relevant log output

```shell
frigate  | 2024-02-26 14:59:00.439956870  *************************************************************
frigate  | 2024-02-26 14:59:00.439957777  ***    Config Validation Errors                           ***
frigate  | 2024-02-26 14:59:00.439958689  *************************************************************
frigate  | 2024-02-26 14:59:00.440014474  2 validation errors for FrigateConfig
frigate  | 2024-02-26 14:59:00.440029037  cameras -> front_doorbell -> ffmpeg -> inputs -> 0 -> roles
frigate  | 2024-02-26 14:59:00.440030309    value is not a valid list (type=type_error.list)
frigate  | 2024-02-26 14:59:00.440031526  cameras -> front_doorbell -> ffmpeg -> inputs -> 1 -> roles
frigate  | 2024-02-26 14:59:00.440032697    value is not a valid list (type=type_error.list)
frigate  | 2024-02-26 14:59:00.440511687  Traceback (most recent call last):
frigate  | 2024-02-26 14:59:00.440513465    File "/opt/frigate/frigate/app.py", line 645, in start
frigate  | 2024-02-26 14:59:00.440514462      self.init_config()
frigate  | 2024-02-26 14:59:00.440515524    File "/opt/frigate/frigate/app.py", line 112, in init_config
frigate  | 2024-02-26 14:59:00.440516478      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2024-02-26 14:59:00.440517427    File "/opt/frigate/frigate/config.py", line 1346, in parse_file
frigate  | 2024-02-26 14:59:00.440518241      return cls.parse_obj(config)
frigate  | 2024-02-26 14:59:00.440519425    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
frigate  | 2024-02-26 14:59:00.440521134    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
frigate  | 2024-02-26 14:59:00.440522150  pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
frigate  | 2024-02-26 14:59:00.440523178  cameras -> front_doorbell -> ffmpeg -> inputs -> 0 -> roles
frigate  | 2024-02-26 14:59:00.440524083    value is not a valid list (type=type_error.list)
frigate  | 2024-02-26 14:59:00.440557349  cameras -> front_doorbell -> ffmpeg -> inputs -> 1 -> roles
frigate  | 2024-02-26 14:59:00.440558405    value is not a valid list (type=type_error.list)
frigate  | 2024-02-26 14:59:00.440568345  
frigate  | 2024-02-26 14:59:00.440569451  *************************************************************
frigate  | 2024-02-26 14:59:00.440570349  ***    End Config Validation Errors                       ***
frigate  | 2024-02-26 14:59:00.440571427  *************************************************************
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe
