### DISCUSSION TITLE
[Camera Support]: Reolink Doorbell 401 Unauthorized

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#10069] [Camera Support]
### Describe the problem you are having

I can't seem to get a stream from my Reolink Doorbell.  I'm getting a 401 Unauthorized error, but I know my username/password combo is right.  I've even tried creating a new user/password and copying/pasting it into my config.yaml with no luck.  Is there something else I'm missing here?  Thanks!

### Version

3.9

### Frigate config file

```yaml
mqtt: 
  enabled: false
  #host: core-mosquito
  #user: mqtt-client
  #password: password

detectors:
  #coral_usb:
  #  type: edgetpu
  #  device: usb
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    front_doorbell:
      - "ffmpeg:http://192.168.1.30/flv?port=554app=bcs&stream=channel0_main.bcs&user=frigate&password=qXPf3pAzGar8RWjC#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.1.30/Preview_01_sub
    front_doorbell_sub:
      - "ffmpeg:http://192.168.1.30/flv?port=554&app=bcs&stream=channel0_ext.bcs&user=frigate&password=qXPf3pAzGar8RWjC"

cameras:
  front_doorbell: 
    ffmpeg: 
      inputs:
        - path: rtsp://192.168.1.30:554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.30:554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.30:554/front_doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
      hwaccel_args: preset-vaapi
    #detect:
     # enabled: True # <---- turn on detection
```

### Relevant log output

```shell
frigate  | 2024-02-26 15:52:36.219891425  [rtsp @ 0x40818c0] method DESCRIBE failed: 401 Unauthorized
frigate  | 2024-02-26 15:52:36.221041291  [ERROR:0@0.500] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
frigate  | 2024-02-26 15:52:36.221047416  
frigate  | 2024-02-26 15:52:36.221058321  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://192.168.1.30:554/front_doorbell_sub in function 'icvExtractPattern'

...

frigate  | 2024-02-26 15:52:56.317789298  [2024-02-26 15:52:56] watchdog.front_doorbell        ERROR   : Ffmpeg process crashed unexpectedly for front_doorbell.
frigate  | 2024-02-26 15:52:56.318091929  [2024-02-26 15:52:56] watchdog.front_doorbell        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-02-26 15:52:56.318452660  [2024-02-26 15:52:56] ffmpeg.front_doorbell.detect   ERROR   : [rtsp @ 0x55acb97f9e40] method DESCRIBE failed: 401 Unauthorized
frigate  | 2024-02-26 15:52:56.318833704  [2024-02-26 15:52:56] ffmpeg.front_doorbell.detect   ERROR   : rtsp://192.168.1.30:554/front_doorbell_sub: Server returned 401 Unauthorized (authorization failed)
frigate  | 2024-02-26 15:52:56.368871657  [2024-02-26 15:52:56] frigate.video                  ERROR   : front_doorbell: Unable to read frames from ffmpeg process.
frigate  | 2024-02-26 15:52:56.368962930  [2024-02-26 15:52:56] frigate.video                  ERROR   : front_doorbell: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
[http @ 0x55cf15fe0600] HTTP error 500 Internal Server Error
http://192.168.1.30/flv?port=554app=bcs: Server returned 5XX Server Error reply
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

reolink doorbell

**Comment by NickM-27** [comment]
how long is the password and what special characters does it have?

**Reply by ReticentRobot** [reply]
16 characters, none special: qXPf3pAzGar8RWjC

(It's random and I can change it after, so I just left it in)

**Reply by NickM-27** [reply]
oh I see your problem, you are accessing the cameras ip address in the cameras section but it should be 127.0.0.1

**Reply by ReticentRobot** [reply]
Oh!  Thanks!!

I'm no longer getting 401 at least, but now I'm getting:

'frigate  | 2024-02-26 16:11:17.679146073  [tcp @ 0x22b8b80] Connection to tcp://127.0.0.1:554?timeout=0 failed: Connection refused'

**Reply by PatSloan** [reply]
maybe try port 1935?   that's working for my reolink doorbell. 

Here is my config:

```
streams:
    doorbell:
    - "ffmpeg:http://192.168.30.40/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PW#video=copy#audio=copy#audio=opus#timeout=5"
    doorbell_sub:
    - "ffmpeg:http://192.168.30.40/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=PW#timeout=5"
```

**Reply by ReticentRobot** [reply]
I'll give it a try, I don't currently have RTMP enabled so I'll need to do that first.

**Reply by PatSloan** [reply]
also i don't haVe the rtsp line.  try without it?

**Reply by NickM-27** [reply]
The port is 8554 not 554 like it shows in the restream docs

**Reply by PatSloan** [reply]
interesting that mine works as I don't have rtmp enabled on my camera.   let me try the 554 port.

**Reply by ReticentRobot** [reply]
> The port is 8554 not 554 like it shows in the restream docs

Should it be 8554 in both the streams and in the cameras section?

**Reply by NickM-27** [reply]
Just the cameras section, remember you are accessing the restream

**Reply by ReticentRobot** [reply]
With 554 (http://192.168.1.30/flv?port=554) in streams and 8554 in cameras (127.0.0.1:8554) I'm getting a 404:

frigate  | 2024-02-26 16:25:23.300787515  16:25:23.300 WRN [rtsp] error="streams: exec: exit status 1" stream=front_doorbell_sub
frigate  | 2024-02-26 16:25:23.301307314  [rtsp @ 0x2988680] method DESCRIBE failed: 404 Not Found

**Reply by PatSloan** [reply]
I just tried 8544, 544 and 1935.   only 1935 works for me and I do not have rtmp enabled on the camera!

**Reply by NickM-27** [reply]
@PatSloan please, you are not using the same config as OP and at this point just causing confusion. 8554 is what should be used when pulling a stream from go2rtc

**Reply by NickM-27** [reply]
@ReticentRobot you need to enable go2rtc trace logs and check them

```
go2rtc:
  log:
    exec: trace
  streams:
    ...
```

**Reply by ReticentRobot** [reply]
Not seeing much:

```
2024-02-26 16:36:14.674489495  [INFO] Preparing new go2rtc config...
2024-02-26 16:36:14.944049831  [INFO] Starting go2rtc...
2024-02-26 16:36:15.017775610  16:36:15.017 INF go2rtc version 1.8.4 linux/amd64
2024-02-26 16:36:15.018131258  16:36:15.018 INF [api] listen addr=:1984
2024-02-26 16:36:15.018133133  16:36:15.018 INF [rtsp] listen addr=:8554
2024-02-26 16:36:15.018285572  16:36:15.018 INF [webrtc] listen addr=:8555
2024-02-26 16:36:15.696597954  16:36:15.696 DBG [exec] run url="exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.168.1.30/flv?port=554&app=bcs&stream=channel0_ext.bcs&user=frigate&password=qXPf3pAz -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
2024-02-26 16:36:16.357168159  [http @ 0x5647f4496440] HTTP error 500 Internal Server Error
2024-02-26 16:36:16.357196295  http://192.168.1.30/flv?port=554&app=bcs&stream=channel0_ext.bcs&user=frigate&password=qXPf3pAz: Server returned 5XX Server Error reply
```

**Reply by NickM-27** [reply]
maybe try rebooting your doorbell, it is throwing an internal error

**Reply by ReticentRobot** [reply]
Damn, still the same internal error after a reboot

**Reply by ReticentRobot** [reply]
Strangely, it does seem to work with 1935 as the stream port instead of 554, with 8554 in the cameras part 🤔.  Since you said that is a different config, I'm guessing that won't work for 2-way audio or for some other reason?

**Reply by NickM-27** [reply]
oh, the http part is definitely supposed to be 1935

**Reply by ReticentRobot** [reply]
Double checked the camera details and I'm on latest firmware. Hardware version is DB_566128M5MP_W

**Reply by ReticentRobot** [reply]
Oh no, lol - okay I am sorry to everyone for all of the confusion... but thank you all for getting me sorted!!

**Comment by ReticentRobot** [comment]
> The port is 8554 not 554 like it shows in the restream docs

```
go2rtc:
  streams:
    front_doorbell:
      - "ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=qXPf3pAz#video=copy#audio=copy#audio=opus"
      #- rtsp://192.168.1.30/Preview_01_sub
    front_doorbell_sub:
      - "ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=qXPf3pAz"

cameras:
  front_doorbell: 
    ffmpeg: 
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
      hwaccel_args: preset-vaapi

```
