### DISCUSSION TITLE
decoding errors help

### DISCUSSION THREAD

**Discussion by dave-parsons** [blakeblackshear/frigate#10073] [Config Support]
### Describe the problem you are having

I have a Dell precision with Nvidia RTX A4000 on windows connected to an REOLink NVR with 12 cams storing to NAS.  (read as all modern and with some strength). All works but I'm getting a continuous stream of decoding errors when I enable ffmpeg audio per log below.   

I've tried both the commented and uncommented ffmpeg configurations below, and I've tried aac and opus for each.  Only removing entirely resolves the errors.

I've tried bunches of combinations with memory and have a lot allocated (see docker-compose).

I usually need to restart frigate every couple of days too...

I can't seem to resolve - thanks in advance!

### Version

0.13.2-6476F8A, go2rtc 1.8.4

### Frigate config file

```yaml
###config.yml
database:
  path: /db/frigate.db

mqtt:
  enabled: true
  host: 192.168.1.100
  port: 1883
  topic_prefix: genesys_frigate
  client_id: genesys_frigate
  user: video_user
  password: PW

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtmp-generic
  # output_args: # record audio
  # #   record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy # -an
  output_args:
    record: preset-record-generic-audio-copy
go2rtc:
  streams:
    front_door:
      - rtsp://UID:PW@192.168.5.10:554//h264Preview_01_main # <----- The stream you want to use for detection
      # - "ffmpeg:front_door#video=h264#hardware#audio=opus"
      - "ffmpeg:front_door#audio=opus"
    front_door_sub:
      - rtsp://UID:PW@192.168.5.10:554//h264Preview_01_sub # <----- The stream you want to use for detection
      # - "ffmpeg:front_door#video=h264#hardware#audio=opus"
      - "ffmpeg:front_door_sub#audio=opus"

....(11 more cams)

  webrtc:
    candidates:
      - 192.168.1.133:8555

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_sub?video=copy&audio=opus #sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=opus #sub
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640 #RLC-410K
      height: 360
    ui:
      order: 1

````
snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True
  retain:
    default: 60

objects:
  track:
    - person
    - car

record:
  enabled: True
  events:
    retain:
      default: 30
      mode: active_objects

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"

ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
```
```

### Relevant log output

```shell
2024-02-26 17:31:07 2024-02-26 17:31:07.097302163  [2024-02-26 17:31:07] frigate.app                    INFO    : Capture process started for office: 646
2024-02-26 17:31:14 2024-02-26 17:31:14.554836535  [INFO] Starting go2rtc healthcheck service...
2024-02-26 17:31:46 2024-02-26 17:31:46.527904689  [2024-02-26 17:31:46] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for office. Keeping the 6 most recent segments out of 8 and discarding the rest...
2024-02-26 17:32:42 2024-02-26 17:32:42.364504654  [h264 @ 0x7f57f801df40] error while decoding MB 121 118, bytestream -11
2024-02-26 17:33:12 2024-02-26 17:33:12.475463881  [h264 @ 0x7f57f8172a00] error while decoding MB 41 118, bytestream -19
```

### Frigate stats

```json
GPU usually in the 25-75% range and seems to be working.
CPU (10 in docker shared) in the 20-50% range
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

```

## docker-compose.yml

volumes:
  SurveillanceVideos:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.1.10,rw,noatime
      device: :/volume1/SurveillanceVideos/frigate

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # increased from 320mb to help stability

    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs - can't use together with device_ids
              capabilities: [gpu]

    volumes:
      - \\wsl$$\Ubuntu\etc\localtime:/etc/localtime:ro
      - .\config:/config
      - .\frigate:/db
      - SurveillanceVideos:/media/frigate

      - type: tmpfs # Optional: allocation of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    
    # mem_limit: 6g #added attempt to improve stability
    # memswap_limit: 6g #added attempt to improve stability
    # mem_swappiness: 0 #added attempt to improve stability

    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

```

**Comment by NickM-27** [comment]
a full set of logs is needed

**Reply by dave-parsons** [reply]
Thank you for looking at this.  I actually had all the ffmpeg turned off and looked at the logs and errors started again - so maybe not an audio problem...Here's my latest log attached.
[Parsons_Frigate_Log_2.27.24.log](https://github.com/blakeblackshear/frigate/files/14428601/Parsons_Frigate_Log_2.27.24.log)

**Reply by NickM-27** [reply]
the problem is most likely that you are using cpu for object detection instead of coral or your gpu, so the system can not run detection on frames fast enough to keep up with recordings

**Reply by dave-parsons** [reply]
Thank you @NickM-27.   Certainly not my intention.   How do I fix this?  I've deployed the GPU in docker in docker compose and I see it's being utilized with nvida-smi.   I don't see the CPU being used more than about 75% and usually closer to 30%   

Happy to try any change - just unclear what changes to make.

**Reply by dave-parsons** [reply]
Here's my config entry.
```
#config.yml
...
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtmp-generic

...
```
here's my docker-compose entry

```
    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs - can't use together with device_ids
              capabilities: [gpu]


```
What do I need to change?

**Reply by NickM-27** [reply]
depends what you want to run. https://docs.frigate.video/configuration/object_detectors#nvidia-tensorrt-detector enables the use of the nvidia GPU for object detection but not all nvidia GPUs are supported. 

If you have an intel iGPU then https://docs.frigate.video/configuration/object_detectors#openvino-detector could be used

**Reply by dave-parsons** [reply]
@NickM-27  - thank you so much for the pointers.   Two weeks worth of testing here.   I have it working without errors, but some stuff doesn't make sense to me.   I have 2 GPUs, and and am only able to use 1 except as a TRT_MODEL_PREP_DEVICE.   Here's what I don't understand:
1) device_ids: ['1'] or device_ids: ['0'] using docker compose has no effect.   GPU A4000 (GPU#1) is only one used.
2) flag --gpus device=GPU-c5fd0137-8838-ee8e-2d16-e75c8e0d5f20 with docker run has no effect.  GPU A4000 (GPU#1) is only one used where the uuid here is the GPU GP100 (GPU#0)
3) Set env var TRT_MODEL_PREP_DEVICE=1 and GPU GP100 (GPU#0) works to build models...
4) devices: 0  in config.yml - seems only 0 works.

Note that the config that works is with GPU "0" setup - but the actual GPU being used in GPU1.   Opposite is true for model prep, and the ONLY setting I can get to utilize GP100 is model prep.  Would love your insights on what I'm missing here.

My setup.

Nvidia-smi
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro GP100                 WDDM  |   00000000:65:00.0 Off |                    0 |
| 26%   39C    P0             26W /  235W |     181MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A4000             WDDM  |   00000000:B3:00.0 Off |                  Off |
| 41%   48C    P3             35W /  140W |    7228MiB /  16376MiB |     13%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```
nvidia uuid
```
PS D:\Docker\frigate> nvidia-smi --query-gpu=gpu_name,gpu_bus_id,uuid --format=csv
name, pci.bus_id, uuid
Quadro GP100, 00000000:65:00.0, GPU-c5fd0137-8838-ee8e-2d16-e75c8e0d5f20
NVIDIA RTX A4000, 00000000:B3:00.0, GPU-42337753-7901-83b3-3257-72abf66bc788
```
Docker compose
```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    # image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "512mb" # increased from 320mb to help stability

    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: all
              device_ids: ['1'] # device0=: GPU-c5fd0137-8838-ee8e-2d16-e75c8e0d5f20 # this
              capabilities: [gpu]

    volumes:
      # - \\wsl.localhost\Ubuntu\etc\localtime:/etc/localtime:ro
      - \\wsl.localhost\Debian\etc\localtime:/etc/localtime:ro
      - .\config:/config
      - .\frigate:/db
      # - SurveillanceVideos:/media/frigate
      - nas_frigate_media:/media/frigate

      # - type: tmpfs # Optional
      #   target: /tmp/cache
      #   tmpfs:
      #     size: 1000000000
    
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    env_file:
      - .env
```
frigate config.yml
```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #no value other than 0 seems to work here.

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

```
.env
```
TRT_MODEL_PREP_DEVICE=1
CUDA_MODULE_LOADING=LAZY
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all

YOLO_MODELS=yolov7-tiny-416,yolov7x-640,yolov7x-320
# YOLO_MODELS=yolov7x-320
```
