### DISCUSSION TITLE
[Question]: What's the difference between these settings (I checked the docs and couldn't find the answer)

### DISCUSSION THREAD

**Discussion by rocket59** [blakeblackshear/frigate#10076] [Ask A Question] [answered]
### What is your question:

So in the config go2rtc parameters I can input this:

```
go2rtc:
  streams:
    back_yard:
      - ffmpeg:"rtsp://xxxx:xxxx@192.168.xx.xx:8554/1080p"
```

or:

```
go2rtc:
  streams:
    back_yard:
      - rtsp://xxxx:xxxx@192.168.xx.xx:8554/1080p
```

The ffmpeg prefixed option seems to work better but my searches haven't revealed what the difference is.
