### DISCUSSION TITLE
[Support]: Ghosting in snapshots and clips since 13.2 upgrade

### DISCUSSION THREAD

**Discussion by StarMonkey1** [blakeblackshear/frigate#10106] [General Support]
### Describe the problem you are having

Ghosting within images, as below:
![snapshot](https://github.com/blakeblackshear/frigate/assets/104598361/fd33ba0e-8a29-49e5-a714-cf4b61132a79)

This wasn't a problem in 12.x.

Assuming this is GPU or CPU related and something in 13 is using extra GPU/CPU so my box can't handle the load. It's happening across multiple cameras which rules out a camera issue. I haven't managed to view the cameras live during a motion event to see if it happens in the live feed as well. Go2RTC appears to be the largest CPU hog according to the System page. Occasionally the ghost is detected as the object rather than the object itself so the ghost is present in the detect stream.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.2
  port: 1883
  user: mqtt
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: true

ui:
  live_mode: webrtc

cameras:
  Front_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          roles:
            - record
        - path: rtsp://user:password@192.168.1.108:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Front_Door
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1500
        car:
          mask:
            - 0,720,186,192,218,186,942,570,891,720
        motorcycle:
          mask:
            - 0,720,0,225,186,192,917,571,848,720            
    ui:
      order: 0

  Front_Garden:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Garden
          roles:
            - record
        - path: rtsp://user:password@192.168.1.107:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Front_Garden
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 1

  Utility_External:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Utility_External
          roles:
            - record
        - path: rtsp://user:password@192.168.1.105:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Utility_External
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 2000
          mask:
             - 903,577,961,268,1020,226,1023,152,1080,149,1080,375,1080,512,1080,720,1006,720
        car:
          min_area: 25000
          mask:
             - 1080,0,1080,720,812,720,819,0
             - 0,720,302,720,300,633,0,626
    ui:
      order: 2

  Office_External:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Office_External
          roles:
            - record
        - path: rtsp://user:password@192.168.1.106:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Office_External
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - horse
      filters:
        person:
          min_area: 2000
    ui:
      order: 3

  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
        - path: rtsp://user:password@192.168.1.102/av_stream/ch0
          roles:
            - detect
    live:
      stream_name: Garage
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 4

  Back_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Rotated
          roles:
            - record
            - detect
    live:
      stream_name: Back_Door_Rotated
    objects:
      track:
        - person
        - bicycle
      filters:
        person:
          min_area: 25000
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain: 
          default: 14
          mode: active_objects
        pre_capture: 15
        post_capture: 15
    detect:
      width: 720
      height: 1080
      fps: 5
    ui:
      order: 5

go2rtc:
  streams:
    Front_Door:
      - rtsp://user:password@192.168.1.108:554/Streaming/channels/101
    Front_Garden:
      - rtsp://user:password@192.168.1.107:554/Streaming/channels/101
    Utility_External:
      - rtsp://user:password@192.168.1.105:554/Streaming/channels/101
    Office_External:
      - rtsp://user:password@192.168.1.106:554/Streaming/channels/101
    Garage:
      - rtsp://user:password@192.168.1.102/av_stream/ch0
    Back_Door:
      - rtsp://user:password@192.168.1.103/av_stream/ch0
    Back_Door_Rotated:
      - "ffmpeg:Back_Door#video=h264#rotate=90"

  webrtc:
    candidates:
      - 192.168.1.4:8555
      - stun:8555
```

### Relevant log output

```shell
N/A - Logs are clear
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":1520,"width":2688}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":1520,"width":2688}]}}]
```

### Frigate stats

```json
{"cameras":{"Back_Door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":371,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":308664,"pid":345,"process_fps":0.0,"skipped_fps":0.0},"Front_Door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":347,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":288997,"pid":321,"process_fps":5.0,"skipped_fps":0.0},"Front_Garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":351,"detection_enabled":1,"detection_fps":8.1,"ffmpeg_pid":255871,"pid":323,"process_fps":5.1,"skipped_fps":0.0},"Garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":365,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":383,"pid":342,"process_fps":5.1,"skipped_fps":0.0},"Office_External":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":363,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":301763,"pid":341,"process_fps":5.0,"skipped_fps":0.0},"Utility_External":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":359,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":306250,"pid":332,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"28.0","cpu_average":"28","mem":"0.5"},"109":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"114":{"cmdline":"python3 -u -m frigate","cpu":"4.0","cpu_average":"4","mem":"4.8"},"121":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.5"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.5"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"294":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"296":{"cmdline":"frigate.recording_manager","cpu":"5.9","cpu_average":"14","mem":"1.8"},"304":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)","cpu":"0.5","cpu_average":"0","mem":"0.1"},"305":{"cmdline":"frigate.detector.coral","cpu":"7.0","cpu_average":"3","mem":"1.7"},"307":{"cmdline":"frigate.output       ","cpu":"1.7","cpu_average":"1","mem":"1.5"},"313":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"318":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 720x1080 -i pipe: -f mpegts -s 480x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"320":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.6"},"321":{"cmdline":"frigate.process:Front_Door","cpu":"1.4","cpu_average":"2","mem":"1.9"},"323":{"cmdline":"frigate.process:Front_Garden","cpu":"12.0","cpu_average":"4","mem":"1.9"},"332":{"cmdline":"frigate.process:Utility_External","cpu":"1.8","cpu_average":"2","mem":"1.8"},"341":{"cmdline":"frigate.process:Office_External","cpu":"2.1","cpu_average":"2","mem":"1.8"},"342":{"cmdline":"frigate.process:Garage","cpu":"1.5","cpu_average":"2","mem":"1.9"},"345":{"cmdline":"frigate.process:Back_Door","cpu":"0.0","cpu_average":"0","mem":"1.5"},"347":{"cmdline":"frigate.capture:Front_Door","cpu":"2.0","cpu_average":"2","mem":"1.5"},"351":{"cmdline":"frigate.capture:Front_Garden","cpu":"2.0","cpu_average":"2","mem":"1.5"},"359":{"cmdline":"frigate.capture:Utility_External","cpu":"2.1","cpu_average":"2","mem":"1.5"},"363":{"cmdline":"frigate.capture:Office_External","cpu":"2.4","cpu_average":"2","mem":"1.5"},"364":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Door@%Y%m%d%H%M%S%z.mp4","cpu":"2.4","cpu_average":"2","mem":"0.4"},"365":{"cmdline":"frigate.capture:Garage","cpu":"2.3","cpu_average":"2","mem":"1.5"},"371":{"cmdline":"frigate.capture:Back_Door","cpu":"0.2","cpu_average":"0","mem":"1.5"},"374":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Garden@%Y%m%d%H%M%S%z.mp4","cpu":"2.9","cpu_average":"2","mem":"0.4"},"383":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.40.102/av_stream/ch0 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.6"},"385":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Office_External -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Office_External@%Y%m%d%H%M%S%z.mp4","cpu":"3.0","cpu_average":"2","mem":"0.4"},"389":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Utility_External -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Utility_External@%Y%m%d%H%M%S%z.mp4","cpu":"2.7","cpu_average":"2","mem":"0.4"},"394":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garage@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.3"},"255871":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.40.107:554/Streaming/channels/101 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.9","cpu_average":"8","mem":"0.8"},"288997":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.40.108:554/Streaming/channels/101 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.2","cpu_average":"8","mem":"0.7"},"301763":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.40.106:554/Streaming/channels/101 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.7","cpu_average":"8","mem":"0.7"},"306250":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.40.105:554/Streaming/channels/101 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.1","cpu_average":"8","mem":"0.7"},"308644":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":8.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.62,"pid":305}},"gpu_usages":{"intel-vaapi":{"gpu":"21.47%","mem":"-%"}},"processes":{"go2rtc":{"pid":88},"logger":{"pid":294},"recording":{"pid":296}},"service":{"last_updated":1709067741,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":243.4,"mount_type":"tmpfs","total":256.0,"used":12.6},"/media/frigate/clips":{"free":45427.1,"mount_type":"ext4","total":100220.9,"used":49657.8},"/media/frigate/recordings":{"free":45427.1,"mount_type":"ext4","total":100220.9,"used":49657.8},"/tmp/cache":{"free":45427.1,"mount_type":"overlay","total":100220.9,"used":49657.8}},"temperatures":{},"uptime":86482,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision 4MP x 5

**Comment by NickM-27** [comment]
would be good to see a screenshot of the system page

**Reply by StarMonkey1** [reply]
![screenshot](https://github.com/blakeblackshear/frigate/assets/104598361/2321e800-3901-4af1-bb35-d71122150e71)

**Reply by NickM-27** [reply]
```
    Back_Door_Rotated:
      - "ffmpeg:Back_Door#video=h264#rotate=90"
```

you should really be setting `#hardware` on here so hwaccel is used, right now you are using pure CPU to do this decode and enocde

**Reply by StarMonkey1** [reply]
Done, doesn't seem to have made any difference to anything

**Reply by NickM-27** [reply]
CPU usage on the go2rtc process should be lower.

**Reply by StarMonkey1** [reply]
28.2%

**Reply by NickM-27** [reply]
please paste updated config

**Reply by StarMonkey1** [reply]
```
go2rtc:
  streams:
    Front_Door:
      - rtsp://user:password@192.168.1.108:554/Streaming/channels/101
    Front_Garden:
      - rtsp://user:password@192.168.1.107:554/Streaming/channels/101
    Utility_External:
      - rtsp://user:password@192.168.1.105:554/Streaming/channels/101
    Office_External:
      - rtsp://user:password@192.168.1.106:554/Streaming/channels/101
    Garage:
      - rtsp://user:password@192.168.1.102/av_stream/ch0
    Back_Door:
      - rtsp://user:password@192.168.1.103/av_stream/ch0
    Back_Door_Rotated:
      - "ffmpeg:Back_Door#video=h264#rotate=90#hardware=vaapi"
```
