### DISCUSSION TITLE
[Support]: left block unavailable

### DISCUSSION THREAD

**Discussion by turboc1208** [blakeblackshear/frigate#10112] [General Support]
### Describe the problem you are having

What does this error mean?  other than the left block isn't available?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.2.50
  port: 1883
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  #user: mqtt_user
  #password: password
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  #tls_insecure: false
  stats_interval: 60

detectors:
  # Required: name of the detector
  Coral:
    # Required: type of the detector
    # Frigate provided types include 'cpu', 'edgetpu', and 'openvino' (default: shown below)
    # Additional detector types can also be plugged in.
    # Detectors may require additional configuration.
    # Refer to the Detectors configuration page for more information.
    type: edgetpu

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

# Optional: logger verbosity settings
logger:
  default: info
  logs:
    frigate.event: debug
    frigate.object_detection: info

# Optional: set environment variables
environment_vars:
  EXAMPLE_VAR: value

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic
  output_args:
    # Optional: output args for detect streams (default: shown below)
#    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    #rtmp: preset-rtmp-generic


snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 175
  required_zones: []
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

# Optional: Restream configuration
go2rtc:
  streams:
    sunroom: rtsp://admin:plough@192.168.3.31:554/h264Preview_01_main
    sunroom2: rtsp://admin:plough@192.168.3.31:554/h264Preview_01_sub

    doorbell: rtsp://admin:plough@192.168.3.32:554/h264Preview_01_main
    doorbell2: rtsp://admin:plough@192.168.3.32:554/h264Preview_01_sub

    hvac: rtsp://admin:plough@192.168.3.34:554/h264Preview_01_main
    hvac2: rtsp://admin:plough@192.168.3.34:554/h264Preview_01_sub

    drivewaygate: rtsp://admin:plough@192.168.3.35:554/h264Preview_01_main
    drivewaygate2: rtsp://admin:plough@192.168.3.35:554/h264Preview_01_sub

    driveway: rtsp://admin:plough@192.168.3.37:554/h264Preview_01_main
    driveway2: rtsp://admin:plough@192.168.3.37:554/h264Preview_01_sub

    twocar: rtsp://admin:plough@192.168.3.41:554/h264Preview_01_main
    twocar2: rtsp://admin:plough@192.168.3.41:554/h264Preview_01_sub

    onecar: rtsp://admin:plough@192.168.3.42:554/h264Preview_01_main
    onecar2: rtsp://admin:plough@192.168.3.42:554/h264Preview_01_sub


    shed: rtsp://admin:plough@192.168.3.38:554/h264Preview_01_main
    shed2: rtsp://admin:plough@192.168.3.38:554/h264Preview_01_sub

    pond: rtsp://admin:plough@192.168.3.33:554/h264Preview_01_main
    pond2: rtsp://admin:plough@192.168.3.33:554/h264Preview_01_sub

  webrtc:
    candidates:
    - 192.168.2.50:8555
    - stun:8555

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person
  - dog
  - cat
  - bicycle
  - motorcycle
  - bus
  - boat
  filters:
    cat:
      min_score: 0.7
      threshold: 0.8
# Optional: jsmpeg stream configuration for WebUI
#live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
#  stream_name: main
#  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid

#rtmp:
#  enabled: false

detect:
  enabled: true
  width: 640
  height: 480
  fps: 5
  stationary:
    interval: 50
    threshold: 50

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    objects:
    - person
    - dog
    - cat
    - bicycle
    - motorcycle
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 7
        cat: 2
        bicycle: 2
        motorcycle: 2


# Required
cameras:
  # Required: name of the camera
  driveway:
    enabled: true
    ui:
      order: 0
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/driveway2
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 0,480,164,480,157,387,102,333,39,334,21,208,76,123,402,153,640,188,640,0,0,0
    live:
      stream_name: driveway
  drivewaygate:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/drivewaygate
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/drivewaygate2
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 82,72,87,118,310,75,314,44,395,46,640,41,640,0,0,0,0,52
    live:
      stream_name: drivewaygate
  sunroom:
    enabled: true
    ui:
      order: 8
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/sunroom
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/sunroom2
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
      - 0,51,363,21,640,103,640,0,0,0
    live:
      stream_name: sunrooom
  hvac:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/hvac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/hvac2
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 1536
      height: 576
      fps: 5
    motion:
      mask:
      - 452,52,864,0,1198,79,1514,296,1536,0,0,0,0,576,435,576,167,139
      - 1379,576,1536,576,1536,399
      - 1398,438,1503,412,1434,341,1335,381
    live:
      stream_name: hvac
    zones:
      zone_0:
        coordinates: 
          795,59,1060,91,1515,412,1536,373,1077,57,977,21,767,0,601,0,381,89,196,193,223,220,498,94
  doorbell:
    enabled: true
    ui:
      order: 5
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/doorbell2
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 0,131,91,151,197,120,203,341,270,347,271,100,379,87,368,360,454,357,499,480,640,480,640,0,0,0
      - 1280,181,1280,0,171,0,170,57
    live:
      stream_name: doorbell
  shed:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/shed
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/shed2
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 1536
      height: 576
      fps: 7
    motion:
      mask:
      - 1398,438,1503,412,1434,341,1335,381
      - 0,267,390,106,735,70,956,73,1087,96,1206,77,1417,116,1402,203,1501,244,1536,211,1536,0,424,0,0,0
    live:
      stream_name: shed

  pond:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/pond
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/pond2
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 0,206,111,157,260,142,640,152,640,0,0,0
    live:
      stream_name: pond
  twocar:
    enabled: true
    ui:
      order: 7
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/twocar
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/twocar2
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 0,103,235,85,640,98,640,0,0,0
    live:
      stream_name: twocar
  onecar:
    enabled: true
    ui:
      order: 6
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/onecar
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/onecar2
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 0,113,196,113,204,43,394,52,415,62,461,68,460,0,0,0
    live:
      stream_name: onecar
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  use_experimental: false
  timezone: America/Chicago
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: '%Y/%m/%d %H:%M'

birdseye:
  enabled: true
  mode: objects

# Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
```

### Relevant log output

```shell
2024-02-27 17:35:32.929824095  [h264 @ 0x7fed54207b80] left block unavailable for requested intra4x4 mode -1
2024-02-27 17:35:32.929828884  [h264 @ 0x7fed54207b80] error while decoding MB 0 19, bytestream 217905
```

### FFprobe output from your camera

```shell
Not sure which camera it is
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

not sure which camera is the issue

### Any other information that may be helpful

I'm not sure what other information would be relevant.
