### DISCUSSION TITLE
[Camera Support]: Not reconnecting

### DISCUSSION THREAD

**Discussion by austindetzel** [blakeblackshear/frigate#10113] [Camera Support]
### Describe the problem you are having

I have several reolink RLC-823A 16X cameras connected. go2rtc seems to be crashing and not reconnecting. Looking for suggestions to make go2rtc more reliable.

### Version

0.13.0-49814B3

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: False



record:
    enabled: True
    retain:
        days: 7
        mode: all

detect:
  enabled: False

birdseye:
  enabled: False

snapshots:
  enabled: False
  clean_copy: False
  

  

go2rtc:
  streams:
    redacted-001:
      - rtsp://admin:@10.8.0.13:554/h264Preview_01_main
      - "ffmpeg:redacted-001"
    redacted-002:
      - rtsp://admin:@10.8.0.8:554/h264Preview_01_main
      - "ffmpeg:redacted-002"
    redacted-001:
      - rtsp://admin:@10.8.0.3:8554/CH001.sdp
      - "ffmpeg:redacted-001"
    redacted-001:
       - rtsp://admin:@72.23.219.107:554/h264Preview_01_main
       - "ffmpeg:redacted-001"
    redacted-003:
      - rtsp://admin:@10.8.0.12:554/h264Preview_01_main
      - "ffmpeg:redacted-003"
    redacted-001:
      - rtsp://admin:@10.8.0.14:554/h264Preview_01_main
      - "ffmpeg:redacted-001"
    


ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

cameras:
    redacted-001:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/redacted-001
                  input_args: preset-rtsp-restream
                  roles:
                    - record
    redacted-002:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/redacted-002
                  input_args: preset-rtsp-restream
                  roles:
                    - record
    redacted-001:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/redacted-001
                  input_args: preset-rtsp-restream
                  roles:
                    - record
    redacted-003:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/redacted-003
                  input_args: preset-rtsp-restream
                  roles:
                    - record
    redacted-001:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/redacted-001
                  input_args: preset-rtsp-restream
                  roles:
                    - record
    redacted-001:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/redacted-001
                  input_args: preset-rtsp-restream
                  roles:
                    - record
```

### Relevant log output

```shell
https://nextcloud.814server.com/s/Fgr7qQmnoawcmGd
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"18/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{"cameras":{"redacted-001":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":791,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":100066,"pid":764,"process_fps":5.1,"skipped_fps":0.0},"redacted-003":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":781,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":474836,"pid":763,"process_fps":0.3,"skipped_fps":0.0},"redacted-001":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":767,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":339708,"pid":748,"process_fps":5.0,"skipped_fps":0.0},"redacted-002":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":771,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":433330,"pid":760,"process_fps":5.1,"skipped_fps":0.0},"redacted-001":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":810,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":474849,"pid":766,"process_fps":0.0,"skipped_fps":0.0},"redacted-001":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":775,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":450446,"pid":761,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"101":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"102":{"cmdline":"python3 -u -m frigate","cpu":"6.1","cpu_average":"0","mem":"0.6"},"121":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"152":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"173":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"200":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"231":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"256":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"275":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"298":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"324":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"356":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"582":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.2"},"733":{"cmdline":"frigate.recording_manager","cpu":"1.8","cpu_average":"1","mem":"0.2"},"740":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(58)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"741":{"cmdline":"frigate.detector.cpu ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"743":{"cmdline":"frigate.output       ","cpu":"1.3","cpu_average":"1","mem":"0.2"},"746":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"748":{"cmdline":"frigate.process:redacted-001","cpu":"1.0","cpu_average":"0","mem":"0.2"},"751":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"760":{"cmdline":"frigate.process:redacted-002","cpu":"0.9","cpu_average":"1","mem":"0.2"},"761":{"cmdline":"frigate.process:redacted-001","cpu":"1.0","cpu_average":"1","mem":"0.2"},"762":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"763":{"cmdline":"frigate.process:redacted-003","cpu":"0.0","cpu_average":"0","mem":"0.2"},"764":{"cmdline":"frigate.process:redacted-001","cpu":"0.7","cpu_average":"0","mem":"0.2"},"765":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"766":{"cmdline":"frigate.process:redacted-001","cpu":"0.0","cpu_average":"0","mem":"0.2"},"767":{"cmdline":"frigate.capture:redacted-001","cpu":"3.4","cpu_average":"3","mem":"0.2"},"768":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"771":{"cmdline":"frigate.capture:redacted-002","cpu":"2.3","cpu_average":"3","mem":"8.1"},"775":{"cmdline":"frigate.capture:redacted-001","cpu":"1.6","cpu_average":"1","mem":"0.2"},"776":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"781":{"cmdline":"frigate.capture:redacted-003","cpu":"0.1","cpu_average":"0","mem":"0.2"},"791":{"cmdline":"frigate.capture:redacted-001","cpu":"3.5","cpu_average":"3","mem":"0.2"},"810":{"cmdline":"frigate.capture:redacted-001","cpu":"0.1","cpu_average":"0","mem":"0.2"},"79783":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"134.3","cpu_average":"5","mem":"2.4"},"100066":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/redacted-001 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/redacted-001@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.7","cpu_average":"11","mem":"0.1"},"339708":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/redacted-001 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/redacted-001@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"22.4","cpu_average":"23","mem":"0.1"},"433330":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/redacted-002 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/redacted-002@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2304:1296 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.4","cpu_average":"12","mem":"0.1"},"450446":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/redacted-001 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/redacted-001@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.4","cpu_average":"7","mem":"0.1"},"474847":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"474848":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/redacted-001?video&audio -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/91da3897b3f090f4ffec8a9ac8b3ba4b","cpu":"0.0","cpu_average":"0","mem":"0.0"},"474849":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/redacted-001 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/redacted-001@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"474851":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/redacted-003?video&audio -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/52ffa3fc5b07773b90bb9a107b2809c8","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":741}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":582},"recording":{"pid":733}},"service":{"last_updated":1709077325,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":481.0,"mount_type":"tmpfs","total":512.0,"used":31.0},"/media/frigate/clips":{"free":17280374.7,"mount_type":"ext4","total":18996612.3,"used":762544.9},"/media/frigate/recordings":{"free":17280374.7,"mount_type":"ext4","total":18996612.3,"used":762544.9},"/tmp/cache":{"free":17280374.7,"mount_type":"overlay","total":18996612.3,"used":762544.9}},"temperatures":{},"uptime":76418,"version":"0.13.0-49814b3"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Reolink

### Any other information that may be helpful

These cameras are remote and connected through VPN, Frigate AI is not being used it is just being used for go2rtc and nvr
