### DISCUSSION TITLE
[Config Support]: Playback cannot continue.  No available working or supported playlists.

### DISCUSSION THREAD

**Discussion by imatech** [blakeblackshear/frigate#10143] [Config Support]
### Describe the problem you are having

I can bring up the snapshots, but that's the error I get when I try to play the clip

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: localhost
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: cam
  password: Camino123
  stats_interval: 300

record:
  expire_interval: 10

timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  EastFence:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.226/user=admin&password=&channel=1&stream=0.sdp?
          roles:
            - detect
        - path: rtsp://user:pass@10.0.0.226/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - eastfenceclose_in
        - eastfence_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      eastfence_in:
        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
      eastfence_whole_area:
        coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
        objects:
          - person
          - cat
          - dog
          - bicycle
    motion:
      mask:
        - 2,465,328,468,330,432,5,431
        - 72,43,154,0,0,0,0,129
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - eastfence_in
          - eastfence_whole_area
        pre_capture: 5
        post_capture: 15

  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.224/user=admin&password=&channel=1&stream=0.sdp?
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      mask:
        - 0,480,198,480,200,449,0,451
        - 640,0,640,36,640,111,608,135,485,96,504,0
        - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
        - 370,0,356,100,291,79,292,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
      required_zones:
        - front_porch_close_in
      retain:
        default: 5
    motion:
      mask:
        - 0,480,198,480,200,449,0,451
        - 640,0,640,36,640,111,608,135,485,96,504,0
        - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
        - 370,0,356,100,291,79,292,0
    zones:
      front_porch_close_in:
        coordinates: 45,480,362,480,640,480,640,213,554,145,525,328,466,343,408,272,348,70,253,64,181,118,67,178
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
        required_zones:
         - front_porch_close_in
        pre_capture: 5
        post_capture: 15
 
  deck:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.180/user=admin&password=&channel=1&stream=0.sdp?
          roles:
            - detect
        - path: rtsp://10.0.0.180/user=admin&password=&channel=1&stream=0.sdp?
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
        person:
          mask:
            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 374,480,640,480,640,442,372,442
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15


  garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@10.0.0.135/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pass@10.0.0.135/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    motion:
      mask:
        - 352,93,477,95,554,99,640,94,640,0,343,0
        - 457,480,640,480,640,445,453,444

detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects

live:
  height: 640
  quality: 1
```

### Relevant log output

```shell
none
```

### Frigate stats

```json
not sure how to get this
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
