### DISCUSSION TITLE
[Detector Support]: Frigate wont detect clapping/applause but speech

### DISCUSSION THREAD

**Discussion by marquitosvitalee** [blakeblackshear/frigate#10157] [Detector Support]
### Describe the problem you are having

Hello everyone, i updated my frigate to 0.13 but i cant get applause or clapping sound recognition to work
did anyone had sucess with this?

on the events page i receive instantly the alerts for speech but no one for clapping applause or even meow fires
dont have a cat so i meow by myself 

### Version

0.13

### Frigate config file

```yaml
mqtt:
  enabled: False
record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
   retain:
    default: 3
    mode: motion
ffmpeg:
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic-audio-aac
audio:
  enabled: True
  listen:
    - applause
    - clapping
    - speech
cameras:
  bahiauno:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:12publico34@192.168.0.133:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:12publico34@192.168.0.133:554/Streaming/Channels/102
          roles:
            - audio
            - detect
      hwaccel_args: preset-vaapi
    detect:
        enabled: True
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    #You should not need to map through other devices for hardware acceleration when the Coral TPU is used.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/replay/Desktop/frigate.yml:/config/config.yml:ro
      - /mnt/4tb:/media/frigate # modify to match your setup
      - /mnt/4tb:/db # modify to match your setup
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "12sgrossi34"
```

### Relevant log output

```shell
no relevant output
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
