### DISCUSSION TITLE
Show birdseye when objects detected but do not record events or anything else?

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#10163] [General]
What kind of configuration would have birdseye show a camera when objects are detected, but to not record any events, nor 24/7? It seems like some sort of sub-property for "detect" is needed:

```
  camera-name:
    ffmpeg:   
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-name
          roles:
            - detect
    record:
      enabled: false
    detect:
      enabled: true
      recordEvents: false <----------------------- non-existent sub-property
    birdseye:
      mode: objects
```

**Comment by NickM-27** [comment]
Enable object detection but don't enable snapshots or recording

**Reply by thinkloop** [reply]
do you mean simply like this:

```
  camera-name:
    ffmpeg:   
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-name
          roles:
            - detect
    record:
      enabled: false
    detect:
      enabled: true
    birdseye:
      mode: objects
```

Oh yeah.
