### DISCUSSION TITLE
birdseye - add camera name

### DISCUSSION THREAD

**Discussion by eravion** [blakeblackshear/frigate#10176] [Config Support]
### Describe the problem you are having

Hello,
First, thanks for the job, Frigate is so cool :)

Sorry if the question was asked, I cannot find on issue or documentation the answer.
How can I add the camera name on birdseye view please?

### Version

0.12.1-367d724

### Frigate config file

```yaml
birdseye:
  enabled: True
  restream: False
  mode: continuous
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
