### DISCUSSION TITLE
[Camera Support]: main stream on Anpviz IPC-D363WD-SA unreliable and no sound

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#10179] [Camera Support] [answered]
### Describe the problem you are having

I am experiencing difficulty configuring an Anpviz IPC-D363WD-SA camera in Frigate running on a docker container in Ubuntu 23.10 on bare metal.

The problem is that the main stream which goes through go2rtc isn't working properly. If I view this stream in the Frigate web gui, it takes a long time to load using webrtc and even then the video feed is about 10 seconds delayed. If I try mse, then I can get it to load one frame pretty quickly but after than nothing. There is also no sound.

In comparison, the substream works fine, but I don't stream it through go2rt. It gets pulled into Frigate directly.

Both the main stream and substream are H.264. But as you can see from the log below, there is an error saying ```Invalid data found when processing input``` and ```Could not find codec parameters for stream 0 (Video: h264, none): unspecified size```. I've included a screenshot of the camera's configuration gui.

I am at a loss about the cause of the problem. I searched the discussion board but to no avail. I am hoping someone can point out the mistake I am making in the config file. I assume I am overlooking something.

![anpviz-screenshot](https://github.com/blakeblackshear/frigate/assets/5651490/a4094518-3ef5-4531-b543-1e08b763fa60)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 7
      mode: motion

go2rtc:
  streams:
    cam101:
      - "ffmpeg:rtsp://username:password@192.168.15.101:554/stream0/"
      - "isapi://username:password@192.168.15.101:80/"

  webrtc:
    candidates:
      - 192.168.15.3:8555
      - stun:8555

cameras:

  cam101:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args: 
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam101
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://username:password@192.168.15.101/stream1/
          roles:
            - detect
    detect:
      enabled: True
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 14
```
```


### Relevant log output

```shell
2024-03-01 15:40:08.848299500  [INFO] Preparing Frigate...
2024-03-01 15:40:08.865767109  [INFO] Starting Frigate...
2024-03-01 15:40:09.998269329  [2024-03-01 15:40:09] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-01 15:40:10.025464362  [2024-03-01 15:40:10] peewee_migrate.logs            INFO    : Starting migrations
2024-03-01 15:40:10.029102383  [2024-03-01 15:40:10] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-01 15:40:10.032784963  [2024-03-01 15:40:10] frigate.app                    INFO    : Recording process started: 299
2024-03-01 15:40:10.034862242  [2024-03-01 15:40:10] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-01 15:40:10.048373791  [2024-03-01 15:40:10] detector.coral                 INFO    : Starting detection process: 308
2024-03-01 15:40:12.790580720  [2024-03-01 15:40:10] frigate.app                    INFO    : Output process started: 310
2024-03-01 15:40:12.791301017  [2024-03-01 15:40:10] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-01 15:40:12.792512009  [2024-03-01 15:40:10] frigate.app                    INFO    : Camera processor started for cam101: 318
2024-03-01 15:40:12.792962192  [2024-03-01 15:40:10] frigate.app                    INFO    : Capture process started for cam101: 319
2024-03-01 15:40:12.800101478  [2024-03-01 15:40:12] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-03-01 15:40:30.089670781  [2024-03-01 15:40:30] ffmpeg.cam101.record           ERROR   : rtsp://127.0.0.1:8554/cam101: Invalid data found when processing input
2024-03-01 15:40:30.096926635  [2024-03-01 15:40:30] watchdog.cam101                INFO    : Terminating the existing ffmpeg process...
2024-03-01 15:40:30.097152586  [2024-03-01 15:40:30] watchdog.cam101                INFO    : Waiting for ffmpeg to exit gracefully...
2024-03-01 15:40:45.070167414  [2024-03-01 15:40:45] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/cam101@20240301154037-0500.mp4
2024-03-01 15:40:45.070356495  [2024-03-01 15:40:45] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/cam101@20240301154037-0500.mp4
2024-03-01 15:40:50.114654714  [2024-03-01 15:40:50] ffmpeg.cam101.record           ERROR   : [rtsp @ 0x560cd6f68ec0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2024-03-01 15:40:50.114665055  [2024-03-01 15:40:50] ffmpeg.cam101.record           ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-03-01 15:40:50.114695197  [2024-03-01 15:40:50] ffmpeg.cam101.record           ERROR   : [mp4 @ 0x560cd6f85680] track 0: codec frame size is not set
2024-03-01 15:40:50.114801206  [2024-03-01 15:40:50] ffmpeg.cam101.record           ERROR   : rtsp://127.0.0.1:8554/cam101: Connection timed out
2024-03-01 15:40:50.115381362  [2024-03-01 15:40:50] watchdog.cam101                INFO    : Terminating the existing ffmpeg process...
2024-03-01 15:40:50.115596321  [2024-03-01 15:40:50] watchdog.cam101                INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 3072x2048
FPS: 20/1

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 704x576
FPS: 5/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Anpviz IPC-D363WD-SA

**Comment by Cold-Lemonade** [comment]
I get a similar error if I pull the main stream into Frigate directly to record:

```
2024-03-01 17:15:13.930844887  [2024-03-01 17:15:13] ffmpeg.cam101.record           ERROR   : rtps://*:*@192.168.15.101/stream0/: Protocol not found
2024-03-01 17:15:13.931258216  [2024-03-01 17:15:13] ffmpeg.cam101.record           ERROR   : Did you mean file:rtps://*:*@192.168.15.101/stream0/?
2024-03-01 17:15:13.931933116  [2024-03-01 17:15:13] watchdog.cam101                INFO    : Terminating the existing ffmpeg process...
2024-03-01 17:15:13.932903104  [2024-03-01 17:15:13] watchdog.cam101                INFO    : Waiting for ffmpeg to exit gracefully...
```

**Reply by NickM-27** [reply]
you made a typo, you put `rtps` when it should be `rtsp`

**Reply by Cold-Lemonade** [reply]
@NickM-27 You have an eagle's eye for detail. Thank you!

Any thoughts on the go2rtc issue? I don't think this typo effected that.

**Reply by NickM-27** [reply]
seems the camera is just sending incorrect h264 data. If it works directly with frigate then I would just use that since frigate's default args are more forgiving

**Reply by Cold-Lemonade** [reply]
Okay. But I am still not getting any audio recorded when pulling directly into Frigate.

Here's that section of my config file. The camera is set to AAC at 16000.

```
  cam101:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args: 
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtps://username:password@192.168.15.101:554/stream0/
          roles:
            - record
        - path: rtsp://username:password@192.168.15.101/stream1/
          roles:
            - detect
    detect:
      enabled: True
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 14
```

**Reply by NickM-27** [reply]
use `preset-record-generic-audio-aac`

**Reply by Cold-Lemonade** [reply]
I've tried that but it doesn't make a difference.

I think there's another error that is not getting flagged in the log. When I watch the terminal, I'm seeing this:

```
frigate  | 2024-03-01 17:48:35.434614573  [2024-03-01 17:48:35] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/cam101@20240301174831-0500.mp4
frigate  | 2024-03-01 17:48:35.434802538  [2024-03-01 17:48:35] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/cam101@20240301174831-0500.mp4
frigate  | 2024-03-01 17:48:41.130500700  [2024-03-01 17:48:41] watchdog.cam101                ERROR   : No new recording segments were created for cam101 in the last 120s. restarting the ffmpeg record process...
frigate  | 2024-03-01 17:48:41.130782520  [2024-03-01 17:48:41] watchdog.cam101                INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-03-01 17:48:41.131081765  [2024-03-01 17:48:41] watchdog.cam101                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-03-01 17:48:45.437158340  [2024-03-01 17:48:45] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/cam101@20240301174841-0500.mp4
frigate  | 2024-03-01 17:48:45.437647450  [2024-03-01 17:48:45] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/cam101@20240301174841-0500.mp4
frigate  | 2024-03-01 17:48:51.162748474  [2024-03-01 17:48:51] watchdog.cam101                ERROR   : No new recording segments were created for cam101 in the last 120s. restarting the ffmpeg record process...
frigate  | 2024-03-01 17:48:51.163005929  [2024-03-01 17:48:51] watchdog.cam101                INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-03-01 17:48:51.163662188  [2024-03-01 17:48:51] watchdog.cam101                INFO    : Waiting for ffmpeg to exit gracefully...
```

Is this just bad data coming off the camera? I am wondering if I should try H265.

**Reply by Cold-Lemonade** [reply]
The go2rtc github says that it works with ISAPI. That's what these cameras are using. So something isn't working. I've tried using three additional cameras of this same model and get the same weird behavior where Frigate recognizes that no new recordings have been made in 120 seconds and restarts ffmpeg.

**Reply by FS1961** [reply]
> I get a similar error if I pull the main stream into Frigate directly to record:
> 
> ```
> 2024-03-01 17:15:13.930844887  [2024-03-01 17:15:13] ffmpeg.cam101.record           ERROR   : rtps://*:*@192.168.15.101/stream0/: Protocol not found
> 2024-03-01 17:15:13.931258216  [2024-03-01 17:15:13] ffmpeg.cam101.record           ERROR   : Did you mean file:rtps://*:*@192.168.15.101/stream0/?
> 2024-03-01 17:15:13.931933116  [2024-03-01 17:15:13] watchdog.cam101                INFO    : Terminating the existing ffmpeg process...
> 2024-03-01 17:15:13.932903104  [2024-03-01 17:15:13] watchdog.cam101                INFO    : Waiting for ffmpeg to exit gracefully...
> ```

I noticed you had a typo in your config. RTPS vs RTSP in your cam101.

**Comment by Cold-Lemonade** [comment]
Frigate seems to be losing the connection with the camera. The recording drops intermittently and then Frigate restarts ffmpeg after detecting no new recordings for 120 seconds. Then it records for a bit and then stops. Frigate restarts ffmpeg again after 120 seconds of no new recordings.

And there is never any audio. This happens when I set the camera to encode in either H264 or H265.

What is going on?

**Reply by Cold-Lemonade** [reply, marked as answer]
Solved! @NickM-27 points out that his Hikvision camera only works with two-way audio if the audio encoding is G711ulaw (https://github.com/AlexxIT/go2rtc/issues/972). I believe my friends' Anpviz cameras are Hikvision clones. So I changed the encoding to G711 from AAC in the camera GUI. I made the change and now Frigate is recording all of these Anpviz cameras and I can view them using MSE.

**Reply by jeeftor** [reply]
I've had success with 1-way audio on AAC. but I'll see if this fixes the 2way issue

**Reply by Torquas** [reply]
I'm at a loss getting audio live and recorded with these Anpviz Cameras through Frigate.  I've tried multiple configs (as you can see commented out) and also changed  Anpviz audio in GUI to G711, G711a, and AAC with no luck.  

If anyone has these Anpviz camera's audio working with Frigate, I would appreciate if they could share their config with me.

Thank you

```


go2rtc:

  streams:
    Breezway:
      - rtsp://admin:123456@192.168.30.92:554/stream0
      - "ffmpeg:Breezway#audio=aac"
      - "isapi://admin:123456@@192.168.30.92:80/"
    Breezway_sub:
      - rtsp://admin:123456@192.168.30.92:554/stream1
#      - "ffmpeg:Breezway#audio=aac"
cameras:
  Breezway:
    ffmpeg:
#      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
#        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/Breezway?video=copy&audio=aac
        - path: rtsp://127.0.0.1:8554/Breezway
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
#        - path: rtsp://127.0.0.1:8554/Breezway_sub?video=copy&audio=aac
        - path: rtsp://127.0.0.1:8554/Breezway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

**Reply by Cold-Lemonade** [reply]
What model are you having trouble with? I just purchased a bunch of Anpviz IPC-D3240W-S for US$35 each on Amazon. Pretty good value for the price. These are not two way audio, they just have microphones. I didn't change the default audio settings in the cameras. And used the following in my ``config.yml`` file:

```
go2rtc:
  streams:
    cam101:
      - ffmpeg:rtsp://admin:123456@192.168.50.101:554/stream0/
      - ffmpeg:cam101#audio=aac
```

And 

```
cameras:

  cam101:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/cam101
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:123456@192.168.50.101/stream1
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    motion:
      mask: 0.698,0.9,0.702,0.948,0.954,0.951,0.954,0.904
    ui:
      order: 1
```

I think my "streams" section is configured differently than yours.

Good luck.

**Reply by jeeftor** [reply]
Some of the higher end cameras have 2-way audio ... I also have this cheap-o camera and it works great on 1-way audio. I have yet to get 2-way working on either Anpviz or Reolink - outside of using mobile apps for them.

**Reply by Torquas** [reply]
I appreciate your reply and sharing of config.   

The cameras are physically 3000 miles away, but from my Amazon past order search, the model is IPC-B8740W-S.
Yes, these were the $35 cameras with one-way audio.  I'll attempt to  adjust streams config like yours and see what happens. I'm using docker on bare-metal Debian with latest stable pull of frigate.  I'll post here if successful or not and share my config.

**Reply by jeeftor** [reply]
Can you get audio on the go2rtc streams? instead of going into frigate? Can you get audio DIRECLTY on the RTSP streams? - that should be a start.

In the go2rtc block I use this for my garage setup:

```yaml
    garage_main:
      # - rtsp://Operator:Password@192.168.1.195:554/stream0#audio=opus#hardware#video=copy
      - ffmpeg:rtsp://Operator:Password@192.168.1.195:554/stream0#video=copy#audio=aac#hardware  # FFMPEG - Hardware Decoding/Encoding - keep video - opus audio
      - http://192.168.1.195/cgi-bin/snapshot.cgi?username=Operator&password=Password
```

Not sure why I'm using an HTTP snapshot API :) 

In the cam config:

```yaml
 garage:
    genai:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        # record: preset-record-generic-audio-aac # Current audio I think is mulaw so we need this setting
        record: preset-record-generic-audio-copy # Already should be using AAC audio
      inputs:
        - path: rtsp://localhost:8554/garage_main # 2560, 1440
          # input_args: preset-rtsp-restream
          input_args: -avoid_negative_ts make_zero -fflags +genpts

          roles:
            - audio
            - record
            - detect
    audio:
      enabled: true
      listen: []
    live:
      streams:
        main: garage_main
        aac: garage_main_aac

    detect:
      width: 1900
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - face
        - dog
        - car
        - frisbee
        - bicycle
        - waste_bin


```

**Reply by jeeftor** [reply]
One thing I ran into was if I didn't specific `#hardware` on go2rtc my stream was VERY unreliable

**Reply by Torquas** [reply]
Jefftor,

In VLC Media Player, I can run my stream rtsp://admin:123456@192.168.30.92:554/stream0 and get video and audio. (H264 and AAC)

I attempted to adopt your config with mine. But the validation spews errors about extra inputs:

```
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/          ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
cameras.breezway.ffmpeg.audio: Extra inputs are not permitted
cameras.breezway.ffmpeg.live: Extra inputs are not permitted
cameras.breezway.ffmpeg.detect: Extra inputs are not permitted
cameras.breezway.ffmpeg.objects: Extra inputs are not permitted
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
``` 
```
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: false
#enviroment_vars:
#  LIBVA_DRIVER_NAME: i965
detectors:
  coral:
    type: edgetpu
    device: pci
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bott>
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (defaul>
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%m/%d/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow
model:
  # Required: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Required: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320
  # Required: Object detection model input colorspace
  # Valid values are rgb, bgr, or yuv. (default: shown below)
  input_pixel_format: rgb
  # Required: Object detection model input tensor format
  # Valid values are nhwc or nchw (default: shown below)
  input_tensor: nhwc
  # Required: Object detection model type, currently only used with the OpenVINO detector
  # Valid values are ssd, yolox, yolonas (default: shown below)
  model_type: ssd
  # Required: Label name modifications. These are merged into the standard labelmap.
  labelmap:
    2: vehicle
  # Optional: Map of object labels to their attribute labels (default: depends on model)
  attributes_map:
    person:
#      - amazon
      - face
    car:
#      - amazon
#      - fedex
      - license_plate
#      - ups
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 10
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  # Optional: Threshold for camera activity to stop showing camera (default: shown below)
  inactivity_threshold: 30
  # Optional: Configure the birdseye layout
  layout:
    # Optional: Scaling factor for the layout calculator, range 1.0-5.0 (default: shown below)
    scaling_factor: 2.0
    # Optional: Maximum number of cameras to show at one time, showing the most recent (default: show all came>
    max_cameras: 8
go2rtc:
  streams:
    breezway:
      - ffmpeg:rtsp://admin:123456@192.168.30.92:554/stream0#video=copy#audio=aac#hardware
      - http://192.168.30.92/cgi-bin/snapshot.cgi?username=admin&password=123456
cameras:
  breezway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/breezeway
          input_args: -avoid_negative_ts make_zero -fflags +genpts
          roles:
            - audio
            - record
            - detect
      audio:
        enabled: true
        listen: []
      live:
        streams:
          main: breezway
          aac: breezeway_aac
      detect:
        width: 1280
        height: 720
        fps: 15
      objects:
        track:
          - person
          - face
          - car
          - bicycle


version: 0.16-0

```

**Reply by Torquas** [reply]
Cold-Lemonade,

I tried to adapt your config with mine and I get video, but Live and Recordings have no audio. Tried in Edge and Firefox.  I have my url fully trusted for my web browser (http://192.168.30.44:5000).

```
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: false
#enviroment_vars:
#  LIBVA_DRIVER_NAME: i965
detectors:
  coral:
    type: edgetpu
    device: pci
timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
model:
  path: /edgetpu_model.tflite
  labelmap_path: /labelmap.txt
  width: 320
  height: 320
  input_pixel_format: rgb
  input_tensor: nhwc
  model_type: ssd
  labelmap:
    2: vehicle
  attributes_map:
    person:
      - face
    car:
      - license_plate
birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 10
  mode: objects
  inactivity_threshold: 30
  layout:
    scaling_factor: 2.0
    max_cameras: 8
go2rtc:
  streams:
    breezway:
      - ffmpeg:rtsp://admin:123456@192.168.30.92:554/stream0/
      - ffmpeg:breezway#audio=aac
cameras:
  breezway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac #Also tried preset-record-generic-audio-copy as go2rtc should pick up aac. No luck.
      inputs:
        - path: rtsp://127.0.0.1:8554/breezway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:123456@192.168.30.92/stream1
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 368
      fps: 8
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    motion:
      mask: 0.698,0.9,0.702,0.948,0.954,0.951,0.954,0.904
    ui:
      order: 1



```

**Reply by Cold-Lemonade** [reply]
Have you tried restarting the computer you use to view the Frigate GUI (i.e., the computer your web browser is running on)? I have noticed that if I have been changing my camera settings, I sometimes lose audio but that it isn't actually lost. Instead, something happens in my laptop and I'm just not able to hear it. Restarting my laptop (not mini pc running Frigate) fixes the issue.

**Reply by Torquas** [reply]
This is really frustrating. The video works perfectly, but still no audio.  I tried to force ffmpeg to encode to opus instead of aac and also use generic and aac preset-record-generic-audio-xxx for recording args.  I downloaded some recordings with different configs, but when I play in VLC Media, the codec is only video...no audio.
I may need to eliminate go2rtc from config (below) and configure cameras directly.

```
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: pci
go2rtc:
  streams:
    breezway:
      - ffmpeg:rtsp://admin:123456@192.168.30.92:554/stream0/
      - ffmpeg:rtsp://admin:123456@192.168.30.92:554/stream0#audio=aac
cameras:
  breezway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/breezway
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://admin:123456@192.168.30.92/stream1
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 368
      fps: 8
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.75
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    motion:
      mask: 0.698,0.9,0.702,0.948,0.954,0.951,0.954,0.904
    ui:
      order: 1



version: 0.16-4 # Beta 4
```

**Reply by NickM-27** [reply]
what does the camera info show when you press the `i` icon in camera metrics page?

**Reply by Torquas** [reply]
<img width="512" height="649" alt="info-frigate" src="https://github.com/user-attachments/assets/6f6377db-477f-4800-b41d-b2139bff3bbe" />

**Reply by NickM-27** [reply]
both streams have audio, so if there is no sound on recordings that is a camera issue

**Reply by Torquas** [reply]
The strange thing is if I run the same network stream in VLC Media, I have video and audio.

<img width="592" height="509" alt="vlc-settings" src="https://github.com/user-attachments/assets/11a4a139-a5d3-44f2-9aca-8b5c529c4872" />

**Reply by NickM-27** [reply]
the streams are receiving audio all the way into Frigate itself, not sure what to suggest as it is clear that Frigate recognizes and is saving the audio it receives to the video file

**Comment by Torquas** [comment]
I'm showing some config snapshots of my Anpviz  IPC-B8740W-S.  I've tried different input/output args and ffmpeg options to get audio to work, but still no go. I've also tried changing audio to G.711 and use "audio=opus" as ffmpeg option in config.  Again still no audio.

I'm sharing some snapshots of Web UI config setting on Anpviz Camera....

<img width="1019" height="450" alt="audio" src="https://github.com/user-attachments/assets/f3a62b30-cb52-4cee-9da7-b75e27c79890" />
<img width="1145" height="410" alt="version" src="https://github.com/user-attachments/assets/da899dc2-976a-42bc-985a-08b5fc54ffce" />
<img width="1307" height="611" alt="video" src="https://github.com/user-attachments/assets/6f02a64f-46a8-4e37-a65d-95a8fb6d9cd8" />

**Comment by Torquas** [comment]
Success!!!  I have Audio and Video!!

I changed the Anpviz audio setting to G.711A.  My docker config converts it AAC.  Live view, recordings, and export videos all have audio now. 

Thanks to all for their input in solving this puzzle...

This setup/config is working in Frigate 16-Beta4 (Docker). Camera Anpviz IPC-B8740W-S. 
Server is an old Gateway Intel 915 bare metal running Debian 12/Docker only.

<img width="1328" height="348" alt="g711" src="https://github.com/user-attachments/assets/1d73a5fe-d701-4069-aab9-a9f05579764e" />
<img width="512" height="649" alt="frigate-g711" src="https://github.com/user-attachments/assets/6787597f-8532-4714-8d38-f3b27ae4b7fb" />

```
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: pci
go2rtc:
  streams:
    breezway:
      - ffmpeg:rtsp://admin:123456@192.168.30.92:554/stream0/
      - ffmpeg:rtsp://admin:123456@192.168.30.92:554/stream0#audio=aac
cameras:
  breezway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/breezway
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://admin:123456@192.168.30.92/stream1
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 368
      fps: 8
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.75
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    motion:
      mask: 0.698,0.9,0.702,0.948,0.954,0.951,0.954,0.904
    ui:
      order: 1



version: 0.16-4 # Beta 4
```
