### DISCUSSION TITLE
Birdseye layout does not consume full area

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#10174] [General]
How would I make birdseye take up as much available space as possible:

![image](https://github.com/blakeblackshear/frigate/assets/118814/d51199e3-1dd9-4ac9-9a3b-6505070bacc6)

My birdseye config is:

```
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 2
  mode: objects
```

Thank you.
