### DISCUSSION TITLE
[Config Support]: Reduce false positives

### DISCUSSION THREAD

**Discussion by jiiins** [blakeblackshear/frigate#10185] [Config Support] [answered]
### Describe the problem you are having

I get many Person false positives, especially when it's raining. I'm looking for a way to reduce or eliminate them.

For example, this (For reference, the blue line is 2.5 meters tall):
![snapshot-1709356202 123348-al1qy1](https://github.com/blakeblackshear/frigate/assets/5290927/e54b74af-a755-49cd-9756-2b8326f1bb9f)

Another example:
![snapshot-1709321598 458435-8ja0vs](https://github.com/blakeblackshear/frigate/assets/5290927/c31ce759-27a0-4909-bf56-7aad813e80af)

Since it's raining, motion occurs continuously and I get tons of these detections.

Can you suggest how to solve this?

### Version

13.2

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: 192.168.21.224
  port: 1883
  user: mqtt_user
  password: *

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

#ffmpeg:
#  hwaccel_args: -hwaccel vaapi

cameras:      
  06_pergola:
    ffmpeg:
      inputs:
        - path: rtsp://*:*@192.168.31.105/axis-media/media.amp?streamprofile=hass_detect
          roles:
            - detect
        - path: rtsp://*:*@192.168.31.105/axis-media/media.amp?streamprofile=hass_view
          roles:
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
    motion:
      mask:
        - 0,0,1280,0,1280,151,666,59,484,71,279,169,44,303,0,262
        - 238,267,335,240,254,345,178,326

  08b_master:
    ffmpeg:
      inputs:
        - path: rtsp://*:*@192.168.31.107/axis-media/media.amp?streamprofile=hass_detect
          roles:
            - detect
        - path: rtsp://*:*@192.168.31.107/axis-media/media.amp?streamprofile=hass_view
          roles:
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
    motion:
      mask:
        - 1280,0,1280,370,1221,411,927,375,915,160,528,201,0,315,0,0
        - 0,557,183,468,313,331,0,55

snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 30
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    objects:
      - person
      - car
    retain:
      default: 14
      objects:
        person: 21
        car: 10
objects:
  track:
    - car
    - person
    - cat
    - dog
```

### Relevant log output

```shell
nothing
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by FrigateEnthusiast** [comment, marked as answer]
Quickest and simplest is probably to raise the min person detect threshold to something like 65% or higher. That would have excluded those two examples -  51% and 59%.

Read the docs on these settings.

objects:
    track:
        - person
        - car
    filters:
        person:
            min_score: 0.60
            threshold: 0.67

**Reply by jiiins** [reply]
In the events list, it seems that the percentage is higher than the snapshot:
![image](https://github.com/blakeblackshear/frigate/assets/5290927/e3017d23-d13c-4e66-9c82-94a392df12ef)

Is it because the snapshot shows the very first detection and the other shows the highest score in the detection timespan?

**Reply by NickM-27** [reply]
the score shown on the event list is the highest median score, the snapshot shows the score at that very moment

**Comment by NickM-27** [comment]
For the second detection I'd suggest a max_area filter, a person wouldn't ever have a bounding box that large from that camera angle

**Comment by jiiins** [comment]
Sorry, one more thing about this. The camera of the first example has these settings:
```
    objects:
      filters:
        person:
          min_score: 0.60
          threshold: 0.67
    zones:
      zone_x:
        coordinates: 927,112,285,205,424,450,966,422
        filters:
          person:
            min_score: 0.60
            threshold: 0.67
            max_area: 5000
```
However, a person detection still occurs, right in the middle of the `zone_x` zone:
![image](https://github.com/blakeblackshear/frigate/assets/5290927/ad57ec44-75e3-4ee4-b61f-0d693c4a5513)

![image](https://github.com/blakeblackshear/frigate/assets/5290927/c894ebc2-1b4a-438b-aec2-1df8b8989db8)

What do I do wrong?
