### DISCUSSION TITLE
[Detector Support]: coral + openvivo

### DISCUSSION THREAD

**Discussion by seblang** [blakeblackshear/frigate#10195] [Detector Support]
### Describe the problem you are having

I see that it is possible de have 2 Coral, but it's possible to activate a coral and openvivo in the same time?

### Version

Current version: 0.13.2 

### Frigate config file

```yaml
etectors:
  coral:
    type: edgetpu
    device: usb

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### docker-compose file or Docker CLI command

```yaml
no docker
```

### Relevant log output

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
