### DISCUSSION TITLE
[Config Support]: Anyone used kornyhiv's Installation script for common Linux Variants from Jan 4th?

### DISCUSSION THREAD

**Discussion by kd4e** [blakeblackshear/frigate#10197] [Config Support]
### Describe the problem you are having

kornyhiv shared an _Installation script for common Linux Variants #9208_ on January 4th.

I'm trying to use it on a Dell OptiPlex 7060 with an Intel 8500 cpu.

Has anyone tried it, successfully (on a similar pc), please?

Thanks!

### Version

Stable

### Frigate config file

```yaml
mqtt:
  enabled: false  # Set this to true if you want to use MQTT
  host: mqtt.server.com
  user: mqtt_user
  password: password

detectors:
  cpu1:
    type: cpu
    num_threads: 3

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person

cameras:
  Balcon:
    ui:
      order: 1
    ffmpeg:
      inputs:
      - path: rtsp://username:password@192.168.0.5:554/h264Preview_01_sub
        roles:
        - detect
      - path: rtsp://username:password@192.168.0.5:554/h264Preview_01_main
        roles:
        - record
    detect:
      width: 640
      height: 360
      fps: 7
```

### Relevant log output

```shell
None relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Note 1: I'm trying this in MX Linux 23.2 (a Debian derivative).
Note 2: I'm on a Dell OptiPlex 7060 CPU: Intel 8500, 64G ram, 256G ssd,  and a 2TB nvme
Note 3: I plan to host about 12 cameras, as well as some additional security-related devices.
Note 4: I also plan to install openHAB.
