### DISCUSSION TITLE
[Config Support]: Lower min_score for stationary objects?

### DISCUSSION THREAD

**Discussion by rsteckler** [blakeblackshear/frigate#10190] [Config Support]
### Describe the problem you are having

I often have a false positive pop up that gets detected for 10 seconds and becomes stationary.  
The problem is that this remains detected for a very long time because I think the detection every 50 frames for a stationary object is returning very low scores, under min_score, which are then being discarded.  That means they aren't contributing to the overall score for the object and the object remains above the threshold for hours.  It seems to unstick once the bounding box moves enough to be considered active again, or if there's incidental movement in the area, like an actual person walking past.

Here's an example:
<img width="1108" alt="image" src="https://github.com/blakeblackshear/frigate/assets/1714230/4ade1a90-864b-45fd-9645-6631f244069a">

That firepit was detected as a person for an hour and I suspect there was an hour-long string of scores under the min_score that probably should have contributed to understanding it's not actually a person.

Hope this makes sense?  it might be good to add a separate min_score specifically for continued detection of stationary objects, so we can lower that to zero so that false positives can be cleared more quickly.  I may also just be misunderstanding how this works.

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
mqtt:
  host: homestack-mosquitto-service

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/database.db

model:
  path: plus://73b30a3d84dec0b38affc6f39ca63475

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

record:
  enabled: True
  events:
    retain:
      mode: active_objects
      default: 10 


motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 35

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    camera_pool:
      - rtsp://admin:@192.168.3.25/cam/realmonitor?channel=1&subtype=2
    camera_rear_patio:
      - rtsp://admin:@192.168.3.23/cam/realmonitor?channel=1&subtype=2
    camera_driveway:
      - rtsp://admin:@192.168.3.24/cam/realmonitor?channel=1&subtype=2
    camera_front_gate_driveway:
      - rtsp://admin:@192.168.3.29/cam/realmonitor?channel=1&subtype=2
    camera_front_gate_walkway:
      - rtsp://admin:@192.168.3.29/cam/realmonitor?channel=1&subtype=2
    camera_garage:
      - rtsp://admin:@192.168.3.22/cam/realmonitor?channel=1&subtype=2
    camera_balcony:
      - rtsp://admin:@192.168.3.27/cam/realmonitor?channel=1&subtype=2
    camera_front_yard:
      - rtsp://admin:@192.168.3.26/cam/realmonitor?channel=1&subtype=2
    camera_casita:
      - rtsp://admin:@192.168.3.30/cam/realmonitor?channel=1&subtype=2
    camera_front_door:
      - rtsp://admin:@192.168.3.21/cam/realmonitor?channel=1&subtype=2
    camera_familyroom:
      - rtsp://admin:@192.168.3.31:554/cam/realmonitor?channel=1&subtype=0
    camera_familyroom_pool:
      - rtsp://admin:@192.168.3.31:554/cam/realmonitor?channel=1&subtype=0

cameras:
  #    debug_test:
  #  ffmpeg:
  #    inputs:
  #      - path: /media/frigate/dog2.mp4
  #        input_args: -re -stream_loop -1 -fflags +genpts
  #        roles:
  #          - detect
  #  detect:
  #    height: 2688
  #    width: 1520
  #    fps: 5
  #  rtmp:
  #    enabled: False
  #  snapshots:
  #    enabled: True
  #    timestamp: False
  #    bounding_box: True
  #    crop: False
  #    retain:
  #      default: 365
  camera_pool:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:@192.168.3.25/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 365
        objects:
          person: 50
objects:
  track:
  - person
  - dog
  - cat
  - car
  - face
  - package
  - amazon
  - fedex
  - ups
  - license_plate
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
      threshold: .7
    package:
      min_score: .65
      threshold: .75
    license_plate:
      min_score: .6
      threshold: .7
    amazon:
      min_score: .75
      threshold: .7
    ups:
      min_score: .75
      threshold: .7
    fedex:
      min_score: .75
      threshold: .7
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
```

### Relevant log output

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
