### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by clowncracker** [blakeblackshear/frigate#10198] [Config Support] [answered]
### Describe the problem you are having

I want to set my garage camera to detect car as an object, but I don't want it to trigger an event.  How can I update my config file to achieve this?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: xxxx
  user: xxxx
  password: xxxx

go2rtc:
  streams:
    front_door:
      - "ffmpeg:xxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"
    garage:
      - "ffmpeg:xxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front_door: 
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
      required_zones:
        - entryway
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 438,916,469,598,556,260,656,0,922,0,1051,286,1028,669,1021,976,1023,1077,997,1111,924,1108,823,1103,611,1091,439,1082
            - 1151,1070,1171,1115,1271,1115,1480,1110,1768,1106,2115,1081,2301,1054,2299,872,2277,689,2236,522,2134,528,1897,471,1516,423,1156,426
        car:
          mask:
            - 438,916,469,598,556,260,656,0,922,0,1051,286,1028,669,1021,976,1023,1077,997,1111,924,1108,823,1103,611,1091,439,1082
            - 1151,1070,1171,1115,1271,1115,1480,1110,1768,1106,2115,1081,2301,1054,2299,872,2277,689,2236,522,2134,528,1897,471,1516,423,1156,426
    snapshots:
      enabled: true
    zones:
      entryway:
        coordinates: 2560,1920,2560,1681,2173,1506,1928,1579,1593,1321,930,1404,475,1307,321,1319,0,1319,0,1920
  garage: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,0,2560,0,2560,353,963,383,486,431,0,529
            - 0,1920,906,1920,748,1471,0,1496
    snapshots:
      enabled: true
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB
