### DISCUSSION TITLE
[Config Support]: How to remove events for car parked in driveway with motion

### DISCUSSION THREAD

**Discussion by rayzorben** [blakeblackshear/frigate#10211] [Config Support]
### Describe the problem you are having

I have cars parked in the driveway, and when it is raining or snowing it keeps retriggering the event over and over. As you can see in the image below. 

I have it partitioned off so the street and the driveway are 2 different zones. Ideally i'd only want an event if a car moves from street to driveway. I've tried some of the suggestions in the documentation but didn't have any luck.

![image](https://github.com/blakeblackshear/frigate/assets/7737834/6b840463-2484-4b79-85e4-6cb817e73ec4)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
driveway:
    record:
      events:
        required_zones:
          - front_street
          - driveway_area

    snapshots:
      required_zones:
        - front_street
        - driveway_area

    motion:
      mask:
        - 0,0,704,0,704,166,0,184

    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

    zones:
      front_street:
        coordinates: 0,250,704,239,704,170,0,181
        objects:
          - person
          - car
          - dog
          
      driveway_area:
        coordinates: 704,480,0,480,0,236,704,233        
        objects:
          - person
          - car
          - dog
```

### Relevant log output

```shell
None
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
