### DISCUSSION TITLE
[Camera Support]: The actual fps of the camera does not follow the fps setting of the detector

### DISCUSSION THREAD

**Discussion by SeanChengN** [blakeblackshear/frigate#10225] [Camera Support] [answered]
### Describe the problem you are having

```typescript
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
``` 
![chrome_ZdI7S1UpSq](https://github.com/blakeblackshear/frigate/assets/20624068/4f633e64-1160-46d8-bc1e-e3c7c3d40518)
![chrome_8477nl5CMR](https://github.com/blakeblackshear/frigate/assets/20624068/54012337-a650-4426-bf97-9966cf6f3065)
As shown in the appeal, my fps is set to 5, but the camera's fps is 10, sometimes restarting frigate can make the fps go to 5, but sometimes it goes to 10.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.X.X
  port: 1883
  user: frigate
  password: password

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

audio:
  enabled: False

logger:
  default: info
  logs:
    frigate.event: error  

birdseye:
  enabled: False

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-copy

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  min_initialized: 1
  max_disappeared: 25
  stationary:
    interval: 1
    threshold: 25
    max_frames:
      objects:
        car: 9000

objects:
  track:
    - person
    - car
    - dog
    - cat
  filters:
    person:
      min_area: 4300

motion:
  threshold: 35
  lightning_threshold: 0.6
  contour_area: 30
  frame_alpha: 0.1
  frame_height: 50
  improve_contrast: False
  mqtt_off_delay: 30
 
record:
  enabled: True
  expire_interval: 60
  sync_recordings: False
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      - dog
      - cat
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Required: Default retention days (default: shown below)
    retain:
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 30

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: False
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  height: 800
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
    objects:
      person: 365

rtmp:
  enabled: False

go2rtc:
  streams:
    back:
      - rtsp://admin:password@192.168.31.44:554/Streaming/Channels/102
    back-hd:
      - rtsp://admin:password@192.168.31.44:554/Streaming/Channels/101
      - "ffmpeg:back-hd#audio=aac"
    front:
      - rtsp://admin:password@192.168.31.44:554/Streaming/Channels/202
    front-hd:
      - rtsp://admin:password@192.168.31.44:554/Streaming/Channels/201
      - "ffmpeg:front-hd#audio=aac"

# Optional: jsmpeg stream configuration for WebUI
live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
  stream_name: camera_name
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%Y/%m/%d %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid

cameras:
  front:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front-hd
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: front-hd
    motion:
      mask:
        - 261,720,157,551,0,642,0,720
        - 364,0,358,87,180,148,143,117,122,0
        - 0,648,59,606,21,524,144,439,260,378,146,333,95,351,0,171
        - 1087,0,1081,94,1109,110,1208,49,1280,91,1280,0
    zones:
      front_0:
        coordinates: 0,720,1280,720,1280,68,1078,0,823,0,0,316
        # Optional: Number of consecutive frames required for object to be considered present in the zone (default: shown below).
        inertia: 1
        objects:
          - person
          - dog
          - cat
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 800
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []

  back:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back-hd
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: back-hd
    motion:
      mask:
        - 716,0,701,381,662,373,432,332,438,179,361,168,241,265,0,230,0,0
        - 582,451,589,588,439,549,421,422
        - 817,407,781,586,695,570,704,453,794,252,849,272
    zones:
      back_0:
        coordinates: 0,720,1280,720,1280,349,1280,148,862,100,790,311,690,638,0,430
        # Optional: Number of consecutive frames required for object to be considered present in the zone (default: shown below).
        inertia: 1
        objects:
          - person
          - car
          - dog
          - cat
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 800
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: [] 

# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour

# Optional: Telemetry configuration
telemetry:
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: False
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: True
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: True
```

### Relevant log output

```shell
2024-03-04 14:06:43.774566432  [INFO] Preparing Frigate...
2024-03-04 14:06:43.796345437  [INFO] Starting Frigate...
2024-03-04 14:06:44.723051558  [2024-03-04 14:06:44] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-04 14:06:44.742665941  [2024-03-04 14:06:44] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-03-04 14:06:44.750604108  [2024-03-04 14:06:44] peewee_migrate.logs            INFO    : Starting migrations
2024-03-04 14:06:44.753961663  [2024-03-04 14:06:44] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-04 14:06:44.757638594  [2024-03-04 14:06:44] frigate.app                    INFO    : Recording process started: 224
2024-03-04 14:06:44.761137632  [2024-03-04 14:06:44] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-04 14:06:44.818435397  [2024-03-04 14:06:44] frigate.app                    INFO    : Output process started: 235
2024-03-04 14:06:44.838429212  [2024-03-04 14:06:44] detector.ov                    INFO    : Starting detection process: 234
2024-03-04 14:06:44.986736013  [2024-03-04 14:06:44] frigate.app                    INFO    : Camera processor started for front: 247
2024-03-04 14:06:44.993388143  [2024-03-04 14:06:44] frigate.app                    INFO    : Camera processor started for back: 248
2024-03-04 14:06:45.001450738  [2024-03-04 14:06:44] frigate.app                    INFO    : Capture process started for front: 249
2024-03-04 14:06:45.017632845  [2024-03-04 14:06:45] frigate.app                    INFO    : Capture process started for back: 251
2024-03-04 14:06:45.288482143  [2024-03-04 14:06:45] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,300,300,3]
2024-03-04 14:06:45.288484898  [2024-03-04 14:06:45] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,1,100,7]
2024-03-04 14:06:45.288488634  [2024-03-04 14:06:45] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:password.@192.168.31.44:554/Streaming/Channels/102':
  Metadata:
    title           : HIK Media Server V4.73.000
    comment         : HIK Media Server Session Description : standard
  Duration: N/A, start: 0.080000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 1280x720, 10 fps, 25 tbr, 90k tbn

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:password@192.168.31.44:554/Streaming/Channels/101':
  Metadata:
    title           : HIK Media Server V4.73.000
    comment         : HIK Media Server Session Description : standard
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 2560x1440, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
{"bandwidth_usages":{"89":{"bandwidth":835.5}},"cameras":{"back":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":9.9,"capture_pid":251,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":262,"pid":248,"process_fps":9.9,"skipped_fps":0.0},"front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":9.8,"capture_pid":249,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":259,"pid":247,"process_fps":9.7,"skipped_fps":0.1}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"75":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"7.3","cpu_average":"6","mem":"0.1"},"104":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"python3 -u -m frigate","cpu":"2.4","cpu_average":"2","mem":"1.8"},"122":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"131":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"132":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"133":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"222":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"224":{"cmdline":"frigate.recording_manager","cpu":"1.5","cpu_average":"1","mem":"0.6"},"233":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"234":{"cmdline":"frigate.detector.ov  ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"235":{"cmdline":"frigate.output       ","cpu":"1.3","cpu_average":"1","mem":"0.4"},"239":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"240":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"247":{"cmdline":"frigate.process:front","cpu":"1.7","cpu_average":"1","mem":"0.5"},"248":{"cmdline":"frigate.process:back ","cpu":"1.7","cpu_average":"1","mem":"0.5"},"249":{"cmdline":"frigate.capture:front","cpu":"3.6","cpu_average":"3","mem":"0.5"},"251":{"cmdline":"frigate.capture:back ","cpu":"3.5","cpu_average":"3","mem":"0.5"},"259":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.5","cpu_average":"4","mem":"0.2"},"262":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.2","cpu_average":"4","mem":"0.2"},"263":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front-hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"0","mem":"0.1"},"268":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back-hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/back@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.1"},"280":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/front-hd?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/e8d8582c4792451fcac06aa589dd64f5","cpu":"1.7","cpu_average":"1","mem":"0.1"},"290":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/back-hd?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/25685bb755d81a70ada16a0581fd110b","cpu":"2.0","cpu_average":"1","mem":"0.1"},"10130":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"10614":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"ov":{"detection_start":0.0,"inference_speed":16.33,"pid":234}},"gpu_usages":{"intel-qsv":{"gpu":"1.57%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":222},"recording":{"pid":224}},"service":{"last_updated":1709539287,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":59.8,"mount_type":"tmpfs","total":64.0,"used":4.2},"/media/frigate/clips":{"free":89930.8,"mount_type":"ext4","total":239280.6,"used":149333.7},"/media/frigate/recordings":{"free":89930.8,"mount_type":"ext4","total":239280.6,"used":149333.7},"/tmp/cache":{"free":180.7,"mount_type":"tmpfs","total":190.7,"used":10.0}},"temperatures":{},"uptime":6882,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision
