### DISCUSSION TITLE
[Support]: Hard time identifying DEV-TAG vs Latest release

### DISCUSSION THREAD

**Discussion by MrSiO** [blakeblackshear/frigate#10237] [General Support] [answered]
### Describe the problem you are having

Hi. 
I'm currently running DEV version on docker-compose with the following tag:  **dev-c5ccc0f**

Found out on main site that a new release is now available:  v0.13.2

But i'm having a hard time finding the right tag for my docker-compose file to upgrade to v0.13.2

Found many dev versions here but most are unstable and not for public use: https://github.com/blakeblackshear/frigate/pkgs/container/frigate/versions?filters%5Bversion_type%5D=tagged&page=14

Tried ":latest"     No Luck
Tried: ":dev-6476f8a"      No lluck
Tried opening the docker-compose file, but no image are specified.

Any help would be great!  Thx!

### Version

dev-c5ccc0f

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-c5ccc0f  # dev-c5ccc0f
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
