### DISCUSSION TITLE
[Detector Support]: Crying not detected

### DISCUSSION THREAD

**Discussion by pappasaj** [blakeblackshear/frigate#10241] [Detector Support]
### Describe the problem you are having

I'm attempting to use my IP camera as a baby monitor, but I can not for the life of me get it to trigger the crying event.  I've had the baby right in front of the camera crying really loudly..still nothing.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.86.XXX # <---- same mqtt broker that home assistant uses
  port: 1883
  user: XXX
  password: XXXX

detect:
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  restream: true
  mode: motion

objects:
  track:
    - person
    - dog

audio:
  enabled: true
  listen:
    - crying
    - bark
    - fire_alarm
    - scream
    - yell
    - groan
    - wheeze
    - sneeze
    - chatter
    - smoke_detector
    - breaking
    - smash
    - fart

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  events:
    retain:
      default: 3
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 15
    mode: motion

go2rtc:
  streams:
    Mason:
      - rtsp://admin:XXXXXX@XXXXXXX:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Mason#audio=aac"

cameras:
  Mason:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
#        - path: rtsp://admin:XXXXXXXXX:554/cam/realmonitor?channel=1&subtype=1
#          roles:
#            - audio
#            - detect
        - path: rtsp://127.0.0.1:8554/Mason
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    zones:
      Garage:
        coordinates: 0,931,0,0,148,52,1231,78,1920,125,1920,1031
    detect:
      height: 1080
      width: 1920
      fps: 5
    onvif:
      host: 192.168.86.XX
      port: 80
      user: onvif
      password: XXXXX
```

### docker-compose file or Docker CLI command

```yaml
Docker-compose
```

### Relevant log output

```shell
No logs
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Speach, and a whole list of other audio events are triggered correctly, so I don't think its a setting that I have incorrect, and because of that I haven't tried modifying any thresholds.
