### DISCUSSION TITLE
[Config Support]: person detected in mask

### DISCUSSION THREAD

**Discussion by rayzorben** [blakeblackshear/frigate#10240] [Config Support]
### Describe the problem you are having

I know this has been covered before but for the life of me this hasn't ever happened until today so I am not sure. I have an area masked off but I still got a person detected in this area

![image](https://github.com/blakeblackshear/frigate/assets/7737834/d4d20ba7-d381-41c7-a998-6c0b6a7afee0)

and the person

![image](https://github.com/blakeblackshear/frigate/assets/7737834/4373bdda-ee6b-4f46-a4ee-73d7f05704ab)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
back_north:
    motion:
      mask:
        - 626,173,630,156,629,134,543,110,449,97,316,69,171,67,78,63,0,79,0,0,704,0,704,203

    objects:
      filters:
        person:
          mask: 704,0,704,201,624,175,576,162,529,149,0,49,0,0

    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.23:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.23:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
```

### Relevant log output

```shell
None
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
