### DISCUSSION TITLE
[HW Accel Support]: frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/salon@20240305133719+0100.mp4

### DISCUSSION THREAD

**Discussion by seblang** [blakeblackshear/frigate#10258] [Hardware Acceleration Support]
### Describe the problem you are having

Error in log :

![error](https://github.com/blakeblackshear/frigate/assets/11487773/09d5bbf1-f052-40b5-9237-2e68963abe43)

I have 6 camera we the same configuration and I just have the issue on one of them !!!

### Version

Current version: 0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.xx
  topic_prefix: frigate
  client_id: frigate
  port: 1883
  user: MQTT
  password: xx
  stats_interval: xx
  
#detectors:
#  coral:
#    type: edgetpu
#    device: usb

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
    

ffmpeg:
  hwaccel_args: preset-vaapi


birdseye:
  enabled: false
rtmp:
  enabled: false

# Optional: Snapshot configuration  
snapshots:
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 3

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 3


cameras:
  devant:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/devant
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/devant2
          input_args: preset-rtsp-restream
          roles:
            - detect            
    detect:
      width: 640 #width of the frame for the input with the detect role
      height: 360 #height of the frame for the input with the detect role (default: shown below)
      fps: 5 #Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      enabled: True

    objects:
      track:
        - person
#        - dog
#        - cat
#        - bird
#        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8


  salon:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/salon
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/salon2
          roles:
            - detect            
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: True

    objects:
      track:
        - person
  #        - dog
  #        - cat
  #        - bird
  #        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8


  arriere:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/arriere
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/arriere2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: True

    objects:
      track:
        - person
  #        - dog
  #        - cat
  #        - bird
  #        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8


  robot:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/robot
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/robot2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: True

    objects:
      track:
        - person
  #        - dog
  #        - cat
  #        - bird
  #        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
          
  cote:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: True

    objects:
      track:
        - person
  #        - dog
  #        - cat
  #        - bird
  #        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
          
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cote
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cote2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: True

    objects:
      track:
        - person
  #        - dog
  #        - cat
  #        - bird
  #        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
          
go2rtc:
  streams:
    devant: rtsp://xx@192.168.1.xx:554/Streaming/channels/101
    devant2: rtsp://xx@192.168.1.xx:554/Streaming/channels/102
    salon:  rtsp://xx@192.168.1.xx:554/Streaming/channels/101
    salon2:  rtsp://xx@192.168.1.xx:554/Streaming/channels/102
    arriere: rtsp://xxx@192.168.1.xx:554/Streaming/channels/101
    arriere2: rtsp://xx@192.168.1.xx:554/Streaming/channels/102   
    robot: rtsp://xx@192.168.1.xx:554/Streaming/channels/101
    robot2: rtsp://xx@192.168.1.xx:554/Streaming/channels/102
    cote: rtsp://xx@192.168.1.xx:554/Streaming/channels/101
    cote2: rtsp://xx@192.168.1.xx:554/Streaming/channels/102
    garage: rtsp://xx@192.168.1.xx:554/Streaming/channels/101
    garage2: rtsp://xx@192.168.1.xx:554/Streaming/channels/101

  webrtc:
    listen: ":8555" # address of your local server and port (TCP/UDP)
    candidates:
      - 192.168.1.34:8555  # if you have static public IP-address (1.2.3.4 To replace by External Public IP)
      - stun:8555 # if you have dynamic public IP-address
  ice_servers:
    - urls: [turn:a.relay.metered.ca:443] #TURN Server on https://www.metered.ca/stun-turn
      username: 6b8a93f6dcf5f67b8f5b049b
      credential: PFK8TLdeLiBvHbP+
```

### docker-compose file or Docker CLI command

```yaml
no docker
```

### Relevant log output

```shell
ras
```

### FFprobe output from your camera

```shell
ss
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

HIKVISON DS-2CD2443G0-IW
