### DISCUSSION TITLE
[Camera Support]:  HIK DS-2CD2543G0-I -help

### DISCUSSION THREAD

**Discussion by anthopocket** [blakeblackshear/frigate#10254] [Camera Support]
### Describe the problem you are having

Hi,

_**CAMERA GARAGE**_

i have a problem to view the camera on frigate.
in vlc the image is Ok but no frigate.
it's the same config other caméra.

thanks you for you help.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: admin
  password: anthony
  host: 192.168.1.77
  port: 1883


logger:
  default: info
  logs:
    frigate.mqtt: info

birdseye:
  enabled: true
  mode: continuous
  width: 720
  height: 360
  quality: 4

record:
  enabled: true
  retain:
    days: 15
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects
#      mode : motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 15

detect:
  fps: 30
  width: 1280
  height: 720

go2rtc:
  streams:
    rtsp_OUEST:
    - rtsp://admin:ABCDE12345@192.168.1.65/Streaming/Channels/101
    - ffmpeg:rtsp_OUEST#audio=opus

    rtsp_INTERPHONE:
    - rtsp://admin:ABCDE12345@192.168.1.231/Streaming/Channels/101
    - ffmpeg:rtsp_INTERPHONE#audio=opus
    
    rtsp_GARAGE:
    - rtsp://jeedom:ABCDE12345@192.168.1.39/Streaming/Channels/101
    - ffmpeg:rtsp_GARAGE#audio=opus

    rtsp_SALON:
    - rtsp://admin:NIHVTP@192.168.1.80:554/ch1/main
    - ffmpeg:rtsp_SALON#audio=opus

cameras:
  OUEST:
    ffmpeg:
      inputs : 
      - path: rtsp://192.168.1.198:8554/rtsp_OUEST
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    zones:
      Entrée:
        coordinates: 0,720,1280,720,1280,538,1280,264,940,158,718,260,394,357,0,378
        objects:
          - person

  INTERPHONE:
    ffmpeg:
      inputs : 
      - path: rtsp://192.168.1.198:8554/rtsp_INTERPHONE
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect

  GARAGE:
    ffmpeg:
      inputs :
      - path: rtsp://192.168.1.198:8554/rtsp_GARAGE
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect

  SALON:
     ffmpeg:
      inputs : 
      - path: rtsp://192.168.1.198:8554/rtsp_SALON
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
```

### Relevant log output

```shell
2024-03-06 12:27:56.736769860  [2024-03-06 12:27:56] watchdog.GARAGE                ERROR   : Ffmpeg process crashed unexpectedly for GARAGE.
2024-03-06 12:27:56.736835060  [2024-03-06 12:27:56] watchdog.GARAGE                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-03-06 12:27:56.736891148  [2024-03-06 12:27:56] ffmpeg.GARAGE.detect           ERROR   : rtsp://192.168.1.198:8554/rtsp_GARAGE: Invalid data found when processing input
2024-03-06 12:28:01.627516088  [2024-03-06 12:28:01] frigate.video                  ERROR   : SALON: Unable to read frames from ffmpeg process.
2024-03-06 12:28:01.627860566  [2024-03-06 12:28:01] frigate.video                  ERROR   : SALON: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=Main
codec_type=video
codec_time_base=1/50
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=1920
height=1080
coded_width=1920
coded_height=1088
closed_captions=0
has_b_frames=0
sample_aspect_ratio=189:190
display_aspect_ratio=168:95
pix_fmt=yuvj420p
level=40
color_range=pc
color_space=bt709
color_transfer=bt709
color_primaries=bt709
chroma_location=left
field_order=progressive
timecode=N/A
refs=1
is_avc=false
nal_length_size=0
id=N/A
r_frame_rate=25/1
avg_frame_rate=25/1
time_base=1/90000
start_pts=21600
start_time=0.240000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
[/STREAM]
```

### Frigate stats

```json
?
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

HIK DS-2CD2543G0-I
