### DISCUSSION TITLE
I have a zone where I want to record on any movement - not just person - as the objects is not found (postie car/bike thing)

### DISCUSSION THREAD

**Discussion by vw-kombi** [blakeblackshear/frigate#10256] [Config Support]
### Describe the problem you are having

In front of the house I have a few zones.
I have person and motorbike objects - but only once has it picked up a motorbike.
The postman here drives a cross between a motorbike and a golf car - no idea what you call it - but it is not picked up.
So - I was to split my path zone that in includes that section where the post box is to have people (ie leave it as is), but create the postbox area and have it record on ANY movement - not just object selection - seeing as it cant pick up these strange car/'bike vehicles.

I dont have a coral device - or a GPU - as it is doing a perfect job on people (once got a dog when playing - but was a person on the ground).

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.30.249:5005/api/config/schema.json

database:
  path: /config/frigate.db

mqtt:
  host: 192.168.1.174
  topic_prefix: frigate
  user: connect
  password: connect

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  enabled: true
  required_zones:
  - front-left
  - front-path
  - driveway
  - doorway
  bounding_box: true
  timestamp: true
  retain:
    default: 14

cameras:
  Front-Cam:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://hikvision:xxx@10.10.10.18:554/Streaming/Channels/102   # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
        - rtmp
      - path: rtsp://hikvision:xxx@10.10.10.18:554/Streaming/Channels/101   # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
      - person
      - motorcycle
      filters:
        motorcycle:
          min_score: 40
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
        - front-left
        - front-path
        - driveway
        retain:
          default: 14
          mode: motion
    motion:
      mask:
      - 184,676,426,673,425,720,0,720,0,671
      - 1024,0,1024,31,711,28,711,0
      - 967,720,1024,720,1024,34,649,27,643,47,879,92,842,282
      - 327,375,683,462,670,222,548,190,418,182
      - 0,372,155,410,182,315,221,179,112,177
      - 0,204,128,108,129,0,0,0
    zones:
      driveway:
        coordinates: 0,365,0,664,407,663,418,692,673,694,690,210,247,171
      front-path:
        coordinates: 
          863,117,855,217,828,280,851,346,929,634,873,720,693,720,708,414,708,135,530,96,533,57
      front-left:
        coordinates: 196,105,338,89,343,49,192,68

  Side-Cam:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://foscam:xxx@10.10.10.16:88/videoSub   # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
        - rtmp
      - path: rtsp://foscam:xxx@10.10.10.16:88/videoMain   # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
      - person
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
        - doorway
        retain:
          default: 14
          mode: motion
    motion:
      mask:
      - 0,24,233,25,235,0,0,0
      - 538,400,583,388,619,288,640,242,640,480,492,480
#     threshold: 30
#     contour_area: 10
#     lightning_threshold: 0.8
    zones:
      doorway:
        coordinates: 0,480,492,480,640,357,640,237,640,134,606,136,608,40,178,48,0,52
```

### Relevant log output

```shell
Logs are not relevant to this config thing.
```

### Frigate stats

```json
{"cameras":{"Front-Cam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.0,"capture_pid":728,"detection_enabled":1,"detection_fps":4.4,"ffmpeg_pid":735,"pid":725,"process_fps":6.1,"skipped_fps":0.0},"Side-Cam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":732,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":737,"pid":726,"process_fps":10.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"86":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.3"},"96":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"1.3","cpu_average":"1","mem":"4.7"},"116":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"155":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"182":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"197":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"199":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"216":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"232":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"250":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"268":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"276":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"283":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"697":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.6"},"699":{"cmdline":"frigate.recording_manager","cpu":"1.1","cpu_average":"0","mem":"2.1"},"708":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.2","cpu_average":"0","mem":"0.2"},"709":{"cmdline":"frigate.detector.ov  ","cpu":"20.0","cpu_average":"33","mem":"4.5"},"710":{"cmdline":"frigate.output       ","cpu":"0.8","cpu_average":"0","mem":"1.9"},"714":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.9"},"715":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"716":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"725":{"cmdline":"frigate.process:Front-Cam","cpu":"3.0","cpu_average":"4","mem":"2.5"},"726":{"cmdline":"frigate.process:Side-Cam","cpu":"1.5","cpu_average":"2","mem":"2.1"},"728":{"cmdline":"frigate.capture:Front-Cam","cpu":"1.4","cpu_average":"1","mem":"1.9"},"732":{"cmdline":"frigate.capture:Side-Cam","cpu":"1.1","cpu_average":"1","mem":"1.9"},"735":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@10.10.10.18:554/Streaming/Channels/102 -r 6 -vf fps=6,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.0","cpu_average":"4","mem":"0.8"},"737":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@10.10.10.16:88/videoSub -r 10 -vf fps=10,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.7","cpu_average":"2","mem":"0.6"},"742":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@10.10.10.18:554/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Front-Cam@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.5"},"743":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@10.10.10.16:88/videoMain -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Side-Cam@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"1","mem":"0.5"},"17984":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":4.4,"detectors":{"ov":{"detection_start":0.0,"inference_speed":17.18,"pid":709}},"processes":{"go2rtc":{"pid":86},"logger":{"pid":697},"recording":{"pid":699}},"service":{"last_updated":1709639321,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":252.8,"mount_type":"tmpfs","total":256.0,"used":3.2},"/media/frigate/clips":{"free":1480447.5,"mount_type":"fuse.shfs","total":7649015.7,"used":6168568.2},"/media/frigate/recordings":{"free":1480447.5,"mount_type":"fuse.shfs","total":7649015.7,"used":6168568.2},"/tmp/cache":{"free":952.2,"mount_type":"tmpfs","total":953.7,"used":1.5}},"temperatures":{},"uptime":37796,"version":"0.13.2-6476f8a"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Summary - photo of object from google here -
![australian-postie-bike](https://github.com/blakeblackshear/frigate/assets/56822460/670fc142-996c-455e-bcf0-51adc9862bd0)
 - how can I config it to record and movement not defined as a person, in an area by my letterbox (which is behind a shrub, hence you get the front half of the 'vehicle', until it drives off fast)
