### DISCUSSION TITLE
[Support]: 'Error updating config' when Adding Mask or Zone

### DISCUSSION THREAD

**Discussion by dan246** [blakeblackshear/frigate#10275] [General Support] [answered]
### Describe the problem you are having

When I try to manually add a mask or zone using the Frigate web interface and press save, it displays "Error updating config". Here are the error messages:

At 2024-03-06 10:16:01.424227703, from the IP address {this is my ip}, a PUT request was made to /api/config/set?cameras.2.zones.zone_0.coordinates=970,618,924,1039,271,1007,373,569 but it returned a 500 error. The request was made from "http://{my_ip}:15000/cameras/2/editor" and the browser user-agent was "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36".

Additionally, an error log was generated at the same time stating: "[2024-03-06 10:16:01] root ERROR: Error updating config: list index out of range".

What could be the reason for this error?

### Version

0.13.2

### Frigate config file

```yaml
cameras:
  '2':
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp_url
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
      - NO-Hardhat
    motion:
      mask:
        - 1890,673,1877,1080,1872,1057,1851,1052,1190,1032,1268,607
    record:
      enabled: true
    snapshots:
      enabled: true
  '3':
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp_url
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
      - NO-Safety Vest
      - smoke
    motion:
      mask:
        - 1890,673,1877,1080,1872,1057,1851,1052,1190,1032,1268,607
    record:
      enabled: true
    snapshots:
      enabled: true
detectors:
  ov:
    device: AUTO
    model:
      path: /workspace/frigate/export_yolov8/firesmoke/best.pt
    type: fire_smoke
  ov1:
    device: AUTO
    model:
      path: /workspace/frigate/export_yolov8/Construction_Site_Safety_yolov8n_20240221_v1/best.pt
    type: Construction_Site
model:
  height: 640
  input_pixel_format: bgr
  input_tensor: nhwc
  labelmap_path: /workspace/frigate/export_yolov8/Construction_Site_Safety_yolov8n_20240221_v1/Construction_Site_Safety_yolov8n_20240221_v1.names
  model_type: yolov8
  width: 640
mqtt:
  host: mqtt
snapshots:
  enabled: true
  retain:
    default: 5```


### Relevant log output

```shell
2024-03-06 10:16:01.424227703  my_ip - - [06/Mar/2024:10:16:01 +0800] "PUT /api/config/set?cameras.2.zones.zone_0.coordinates=970,618,924,1039,271,1007,373,569 HTTP/1.1" 500 52 "http://my_ip /cameras/2/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "-"
2024-03-06 10:16:01.424269070  [2024-03-06 10:16:01] root                           ERROR   : Error updating config: list index out of range
```

### FFprobe output from your camera

```shell
None
```

### Frigate stats

```json
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

None
