### DISCUSSION TITLE
[Question]: Filter out mqtt events

### DISCUSSION THREAD

**Discussion by Lallassu** [blakeblackshear/frigate#10280] [Ask A Question] [answered]
### What is your question:

I have setup HASS to trigger Telegram alarms via mqtt from Frigate. Works like a charm, except that I get a lot of false positives. I trigger on `new` event, because I want to be alarmed as fast as possible. But this gives me alarms that triggers even on stationary objects and objects in zones that shouldn't be there (such as cars in my zone that only detects person).

What is the best approach to trigger mqtt alarms, as fast as possible but avoiding these false positives? I read on some issue that looking at `update` events could be bad as these seem to come for objects until they are seen as stationary? And waiting for `end` could take a long time?

I would love some good advice, thanks!

**Comment by NickM-27** [comment]
You shouldn't be using new, update, or end. You should be using the information inside the payload to decide. 

For example mine are set up to only notify the moment an object enters a zone by checking that before.entered_zones is empty and after.entered_zones has the zones I care about.

**Reply by Lallassu** [reply]
Would you mind share example of your HASS configuration for the condition?

I haven't had the chance to elaborate yet, but I was thinking of something like this as one condition (not 100% sure that this works in a hass template):
```
{{ trigger.payload_json['before']['camera'] == 'frontyard' }}
{{ trigger.payload_json['before']['entered_zones'] |length == 0}}      
{{ trigger.payload_json['after']['entered_zones']|length > 0 }} 
```

**Reply by NickM-27** [reply, marked as answer]
```
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'new' }}"
  - condition: template
    value_template: "{{ before_zones | length == 0 }}"
  - condition: template
     value_template: "{{ ["driveway", "side_yard", "front_yard"] | select("in", after_zones) | list | length > 0 }}"
```
