### DISCUSSION TITLE
Audio records are not deleted

### DISCUSSION THREAD

**Discussion by jokerigno** [blakeblackshear/frigate#10297] [General]
I set up audio detection for a camera as follows:

```
cameras:
  cameretta:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cameretta
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cameretta_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio            
    audio:
      enabled: True
      listen:
        - crying
        - cough
        - scream
      min_volume: 200 
      filters:
        crying:
          threshold: 0.5
        cough:  
          threshold: 0.5
        scream:
          threshold: 0.5
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 1
          mode: active_objects
    snapshots: # <----- Enable snapshots
      enabled: True 

```

But today I noticed that i still have stored events from last week . 

![immagine](https://github.com/blakeblackshear/frigate/assets/23552762/65b554c3-e2b2-4af1-8be1-c6460a0d642a)

Looking at the docs my config seems ok

"Volume is considered motion for recordings, this means when the record -> retain -> mode is set to motion any time audio volume is > min_volume that recording segment for that camera will be kept"

I mean setting retain days 1 to motion events should delete also those audio events, right?

Maybe is a bug due to the new feature?
