### DISCUSSION TITLE
[Config Support]: 2 different detect stream resolutions possible?

### DISCUSSION THREAD

**Discussion by Goeste** [blakeblackshear/frigate#10303] [Config Support] [answered]
### Describe the problem you are having

Hey all,
I have 5 C800 connected to Frigate, so far no issues. However, when I rotate the stream of one cam so the resolution is not `3840x2160` but `2160x3840` my detect section in the config messes up the UI and detect screenshots are squished for this one stream. Shall i simply create a second stream, that is not rotated and use this one for detecion? or is there another workaround to get a rotated stream fit into the detect config?

Best,
goeste

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate_host:5000/api/config/schema.json
mqtt:
  enabled: false
logger:
  default: info
  logs:
    frigate.event: debug
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
  cpu5:
    typu: cpu
  #coral:
    #type: edgetpu
    #device: usb
ffmpeg:
  hwaccel_args: preset-nvidia-h265
detect:
  enabled: True
  #width: 640
  #height: 380
  width: 3840
  height: 2160
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 5
    threshold: 100
objects:
  track:
    - person
    - dog
record:
  enabled: True
  events:
    objects:
      - person
    retain:
      default: 7
      mode: motion
snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True
  retain:
    default: 7
go2rtc:
  streams:
    garten:
      - "ffmpeg:rtsp://xxx:xxx@192.168.2.40:554/Streaming/Channels/101#video=h264#hardware=cuda"
    eingang:
      - "ffmpeg:rtsp://xxx:xxx@192.168.2.41:554/Streaming/Channels/101#video=h264#hardware=cuda#rotate=90"
    terrasse:
      - "ffmpeg:rtsp://xxx:xxx@192.168.2.42:554/Streaming/Channels/101#video=h264#hardware=cuda#rotate=90"
    huette:
      - "ffmpeg:rtsp://xxx:xxx@192.168.2.43:554/Streaming/Channels/101#video=h264#hardware=cuda"
    parkplatz:
      - "ffmpeg:rtsp://xxx:xxx@192.168.2.44:554/Streaming/Channels/101#video=h264#hardware=cuda"
  webrtc:
    candidates:
      - 192.168.2.67:8555
      - stun:8555
birdseye:
  enabled: False
  mode: continuous
  restream: True
  width: 1920
  height: 1080
  quality: 1
live:
  height: 360
#Cameras      
cameras:
#Eingang
  eingang:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/eingang
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/eingang
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: eingang
    ui:
      order: 3
#Terrasse
  terrasse:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/terrasse
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/terrasse
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: terrasse
    ui:
      order: 5
#Hütte
  huette:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/huette
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/huette
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: huette
    ui:
      order: 2
#Garten
  garten:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: garten
    ui:
      order: 4
#Parkplatz
  parkplatz:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/parkplatz
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/parkplatz
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: parkplatz
    ui:
      order: 1
```

### Relevant log output

```shell
no log needed?!
```

### Frigate stats

```json
{"cameras":{"eingang":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":482,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":898,"pid":466,"process_fps":0.0,"skipped_fps":0.0},"garten":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":502,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":910,"pid":471,"process_fps":0.0,"skipped_fps":0.0},"huette":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":495,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":900,"pid":469,"process_fps":0.0,"skipped_fps":0.0},"parkplatz":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":511,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":911,"pid":473,"process_fps":0.0,"skipped_fps":0.0},"terrasse":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":490,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":901,"pid":467,"process_fps":0.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.5","cpu_average":"0","mem":"0.3"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"1.4","cpu_average":"14","mem":"2.8"},"113":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"157":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"175":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"203":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"227":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"262":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"289":{"cmdline":"nginx: cache loader process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"439":{"cmdline":"frigate.logger       ","cpu":"0.4","cpu_average":"0","mem":"1.3"},"441":{"cmdline":"frigate.recording_manager","cpu":"0.5","cpu_average":"0","mem":"1.8"},"449":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"450":{"cmdline":"frigate.detector.cpu1","cpu":"0.0","cpu_average":"0","mem":"1.9"},"452":{"cmdline":"frigate.detector.cpu2","cpu":"0.0","cpu_average":"0","mem":"1.9"},"454":{"cmdline":"frigate.detector.cpu3","cpu":"0.0","cpu_average":"0","mem":"1.9"},"455":{"cmdline":"frigate.detector.cpu4","cpu":"0.1","cpu_average":"0","mem":"1.9"},"458":{"cmdline":"frigate.detector.cpu5","cpu":"0.0","cpu_average":"0","mem":"1.9"},"460":{"cmdline":"frigate.output       ","cpu":"0.2","cpu_average":"0","mem":"2.0"},"463":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"465":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"466":{"cmdline":"frigate.process:eingang","cpu":"0.0","cpu_average":"0","mem":"1.9"},"467":{"cmdline":"frigate.process:terrasse","cpu":"0.0","cpu_average":"0","mem":"1.9"},"468":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"469":{"cmdline":"frigate.process:huette","cpu":"0.0","cpu_average":"0","mem":"1.9"},"470":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"471":{"cmdline":"frigate.process:garten","cpu":"0.1","cpu_average":"0","mem":"1.9"},"472":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"473":{"cmdline":"frigate.process:parkplatz","cpu":"0.1","cpu_average":"0","mem":"1.9"},"482":{"cmdline":"frigate.capture:eingang","cpu":"0.6","cpu_average":"0","mem":"1.8"},"490":{"cmdline":"frigate.capture:terrasse","cpu":"0.5","cpu_average":"0","mem":"1.8"},"495":{"cmdline":"frigate.capture:huette","cpu":"0.5","cpu_average":"0","mem":"1.8"},"502":{"cmdline":"frigate.capture:garten","cpu":"0.3","cpu_average":"0","mem":"1.8"},"511":{"cmdline":"frigate.capture:parkplatz","cpu":"0.4","cpu_average":"0","mem":"1.8"},"659":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"898":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"900":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/huette -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"901":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/terrasse -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"902":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac /tmp/cache/eingang@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.2"},"905":{"cmdline":"ffmpeg -hide_banner -v error -hwaccel cuda -hwaccel_output_format nv12 -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.2.41:554/Streaming/Channels/101 -c:v h264_nvenc -g 50 -bf 0 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -vf transpose=1,hwupload -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/d0bbbbf0bf42d3883ccee1392375c2f0","cpu":"0.0","cpu_average":"0","mem":"0.3"},"906":{"cmdline":"ffmpeg -hide_banner -v error -hwaccel cuda -hwaccel_output_format cuda -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.2.43:554/Streaming/Channels/101 -c:v h264_nvenc -g 50 -bf 0 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/bb13f374e3301d932bc4e48490d5f419","cpu":"0.0","cpu_average":"0","mem":"0.3"},"907":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/terrasse -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac /tmp/cache/terrasse@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.3"},"908":{"cmdline":"ffmpeg -hide_banner -v error -hwaccel cuda -hwaccel_output_format nv12 -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.2.42:554/Streaming/Channels/101 -c:v h264_nvenc -g 50 -bf 0 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -vf transpose=1,hwupload -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/65247ab16fd618a2166f42db8a95df64","cpu":"0.0","cpu_average":"0","mem":"0.3"},"909":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/huette -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac /tmp/cache/huette@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.3"},"910":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garten -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"911":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/parkplatz -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"913":{"cmdline":"ffmpeg -hide_banner -v error -hwaccel cuda -hwaccel_output_format cuda -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.2.40:554/Streaming/Channels/101 -c:v h264_nvenc -g 50 -bf 0 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/f8a3928a3b6fc10091afc965e936ca2a","cpu":"0.0","cpu_average":"0","mem":"0.3"},"914":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garten -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac /tmp/cache/garten@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.2"},"916":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/parkplatz -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac /tmp/cache/parkplatz@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.3"},"917":{"cmdline":"ffmpeg -hide_banner -v error -hwaccel cuda -hwaccel_output_format cuda -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.2.44:554/Streaming/Channels/101 -c:v h264_nvenc -g 50 -bf 0 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/eb4b62c80776ad3800947be21b8df9b8","cpu":"0.0","cpu_average":"0","mem":"0.3"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":10.0,"pid":450},"cpu2":{"detection_start":0.0,"inference_speed":10.0,"pid":452},"cpu3":{"detection_start":0.0,"inference_speed":10.0,"pid":454},"cpu4":{"detection_start":0.0,"inference_speed":10.0,"pid":455},"cpu5":{"detection_start":0.0,"inference_speed":10.0,"pid":458}},"gpu_usages":{"GRID P40-8Q":{"dec":"0.0%","enc":"0.0%","gpu":"0.0%","mem":"13.23%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":439},"recording":{"pid":441}},"service":{"last_updated":1709803230,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":1022.4,"mount_type":"tmpfs","total":1024.0,"used":1.6},"/media/frigate/clips":{"free":17102.6,"mount_type":"ext4","total":31114.8,"used":12406.7},"/media/frigate/recordings":{"free":17102.6,"mount_type":"ext4","total":31114.8,"used":12406.7},"/tmp/cache":{"free":17102.6,"mount_type":"overlay","total":31114.8,"used":12406.7}},"temperatures":{},"uptime":31,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

squished image that is rotated by 90 degrees clockwise
![image](https://github.com/blakeblackshear/frigate/assets/320889/86cda720-0893-48e9-9870-c9ae65e19e27)
