### DISCUSSION TITLE
[HW Accel Support]: what preset when using restreaming via go2rtc

### DISCUSSION THREAD

**Discussion by Goeste** [blakeblackshear/frigate#10308] [Hardware Acceleration Support]
### Describe the problem you are having

Hi all,

i got a Nvidia P40 that can handle hvec inputs very well, so knowing this and using only Annke C800's here i would go for the following preset:
```
ffmpeg:
  hwaccel_args: preset-nvidia-h265
```

However, since I use go2rtc incl transcoding like this:
```
go2rtc:
  streams:
    garten:
      - "ffmpeg:rtsp://xxx:xxx@192.168.2.40:554/Streaming/Channels/101#video=h264#hardware=cuda"
```
shall i still use the h265 preset for ffmpeg or is it actually obsolet since go2rtc takes care of the transcoding with hardware?

My camera is setup as the following:
```
#Garten
  garten:
    ffmpeg:
      #output_args:
        #record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - record
```

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
not needed
```

### docker-compose file or Docker CLI command

```yaml
not needed
```

### Relevant log output

```shell
not needed
```

### FFprobe output from your camera

```shell
not needed
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Annke C800
