### DISCUSSION TITLE
[Support]: go2rtc streams info is broken?

### DISCUSSION THREAD

**Discussion by djtremolo** [blakeblackshear/frigate#10316] [General Support] [answered]
### Describe the problem you are having

I'm running Frigate 0.13.2-6476F8A and have used go2rtc for restreaming.
On earlier Frigate versions, the go2rtc streams info page (found at System page) has been really helpful. Now it shows only the json of the existing stream connections. I'm looking for the status page that shows all possible output stream types with their URLs.

This is how it looks like:
![image](https://github.com/blakeblackshear/frigate/assets/23290782/d15f8d79-63c9-47d0-b293-f109bb4cd3fe)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
I believe the config is not relevant here. Here's the go2rtc part anyway:

go2rtc:
  streams:
    c30_main: ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c30_sub: ffmpeg:c30_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=cuda
    c31_main: ffmpeg:http://192.168.1.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c31_sub: ffmpeg:c31_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c32_main: ffmpeg:http://192.168.1.32/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c32_sub: ffmpeg:c32_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c33_main: ffmpeg:http://192.168.1.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c33_sub: ffmpeg:c33_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c34_main: ffmpeg:http://192.168.1.34/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c34_sub: ffmpeg:c34_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c35_main: ffmpeg:http://192.168.1.35/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c35_sub: ffmpeg:c35_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c36_main: ffmpeg:http://192.168.1.36/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c36_sub: ffmpeg:c36_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=cuda
    c37_main: ffmpeg:http://192.168.1.37/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c37_sub: ffmpeg:c37_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c38_main: ffmpeg:http://192.168.1.38/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c38_sub: ffmpeg:c38_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=cuda
    c39_main: ffmpeg:http://192.168.1.39/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c39_sub: ffmpeg:c39_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=cuda
    c40_main: ffmpeg:http://192.168.1.40/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c40_sub: ffmpeg:c40_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c41_main: ffmpeg:http://192.168.1.41/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c41_sub: ffmpeg:c41_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
    c42_main: ffmpeg:http://192.168.1.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myUser&password=myPwd#video=copy#audio=copy
    c42_sub: ffmpeg:c42_main#video=h264#width=2048#height=1536#raw=-r 5 -g 5#hardware=vaapi
```

### Relevant log output

```shell
No relevant log output. See screenshot in Description field.
```

### FFprobe output from your camera

```shell
not relevant. The cameras and restreaming work fine, it's just the go2rtc status/info page that does not.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

My cameras work perfectly - I just don't want to mention reolink rlc520 here to avoid comments on their bad quality :)
