### DISCUSSION TITLE
[Config Support]: Object masks for each camera

### DISCUSSION THREAD

**Discussion by a1ekseev** [blakeblackshear/frigate#10327] [Config Support] [answered]
### Describe the problem you are having

I searched for information about this feature in the full configuration, but did not find it.

Ours has a similar setting for motion https://github.com/blakeblackshear/frigate/discussions/3285, but it didn't work, which seems logical.

I would like to be able to have any camera, for certain types of objects to make a mask against false positives of object detection. Perhaps such a possibility already exists, I would be grateful for an example of configuration.

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 30

ui:
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: medium

telemetry:
  version_check: False

logger:
  default: info

database:
  path: /media/frigate/frigate.db

timestamp_style:
  position: "br"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

birdseye:
  enabled: False

rtmp:
  enabled: False

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  hwaccel_args: preset-vaapi

live:
  stream_name: cameras
  height: 1080
  quality: 8

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - dog
    - cat

detect:
  enabled: True
  width: 1920
  height: 1080
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50

record:
  enabled: True
  retain:
    days: 7
    mode: active_objects
  events:
    objects:
      - person
      - dog
    required_zones: 
      - camera_1_zone
      - camera_2_zone
      - camera_3_zone
      - camera_4_zone
    retain:
      default: 7
      mode: active_objects
      objects:
        person: 7
        car: 5
        dog: 5
        cat: 5

snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: 
        - camera_1_zone
        - camera_2_zone
        - camera_3_zone
        - camera_4_zone
  retain:
    default: 7
    objects:
      person: 7
      car: 5
      dog: 5
      cat: 5


go2rtc:
  streams:
    camera_1_record: 
      - rtsp://admin:password@10.10.10.51:554/ISAPI/Streaming/Channels/101
    camera_2_record:
      - rtsp://admin:password@10.10.10.52:554/ISAPI/Streaming/Channels/101
    camera_3_record:
      - rtsp://admin:password@10.10.10.53:554/ISAPI/Streaming/Channels/101
    camera_4_record:
      - rtsp://admin:password@10.10.10.54:554/ISAPI/Streaming/Channels/101



cameras:
  camera_1: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1_record
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    best_image_timeout: 60
    zones:
      camera_1_zone:
        coordinates: 1501,151,1531,1080,787,1080,0,1080,0,641,639,676,872,323,952,146
        objects:
          - person
          - dog
          - cat
    motion:
      mask:
        - 935,389,977,334,897,253,866,309
        - 1155,266,1176,357,1078,360,1074,264
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 1080
      quality: 70
      required_zones:
        - camera_1_zone


  camera_2: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2_record
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    best_image_timeout: 60
    zones:
      camera_2_zone:
        coordinates: 525,1080,1721,1080,1776,0,1333,0,716,249,0,557,0,1080
        objects:
          - person
          - dog
          - cat
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 1080
      quality: 70
      required_zones:
        - camera_2_zone


  camera_3: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3_record
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    best_image_timeout: 60
    zones:
      camera_3_zone:
        coordinates: 525,1080,1721,1080,1513,679,1346,590,1360,147,1228,51,498,89,170,284,215,556,0,925,0,1080
        objects:
          - person
          - dog
          - cat
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 1080
      quality: 70
      required_zones: 
        - camera_3_zone


  camera_4: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_4_record
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    best_image_timeout: 60
    zones:
      camera_4_zone:
        coordinates: 525,1080,1920,1080,1920,740,1225,498,1088,0,640,59,201,171,0,348,0,1080
        objects:
          - person
          - dog
          - cat
    motion:
      mask:
        - 171,699,215,877,44,888,55,703
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 1080
      quality: 70
      required_zones: 
        - camera_4_zone
```

### Relevant log output

```shell
without logs
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB
