### DISCUSSION TITLE
Intermittent issues with clips (clip.mp4) from HomeAssistant

### DISCUSSION THREAD

**Discussion by ronbruins** [blakeblackshear/frigate#10343] [Config Support] [answered]
### Describe the problem you are having

I have intermittent issues in retrieving the clips through HA API endpoints and see errors in the log.
the url used:  http://HAURL8123/api/frigate/notifications/{id}/{camera}/clip.mp4
Some do work and some give me an error 404

However the snapshot does work
http://HAURL:8123/api/frigate/notifications/1709987679.972472-tjn2ba/snapshot.jpg

I am running Home Assistant as a docker container on Ubuntu and Frigate as well, on another machine.

see examples below:

<img width="795" alt="Screenshot 2024-03-09 at 15 50 55" src="https://github.com/blakeblackshear/frigate/assets/43776917/00d25582-6183-458a-8aeb-12980c795260">
<img width="958" alt="Screenshot 2024-03-09 at 15 52 56" src="https://github.com/blakeblackshear/frigate/assets/43776917/7776c6c4-e551-4523-9851-49bfb3482480">
<img width="755" alt="Screenshot 2024-03-09 at 15 52 10" src="https://github.com/blakeblackshear/frigate/assets/43776917/7f45f4fd-cd83-4eff-a5fd-491af819a349">

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 1.1.1.35
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb
model:
  path: plus://longhexnr

birdseye:
  enabled: true
  mode: continuous

# motion:
#   threshold: 50

snapshots:
  enabled: true
  retain:
    default: 1

detect:
  enabled: true # <---- turn on detection
  width: 1280
  height: 720

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 1
      mode: motion

objects:
  track:
  - person
  - face
  - license_plate
  - dog
  - cat
    #- car
  - amazon
  - fedex
  - ups
  - package
  filters:
    cat:
      min_area: 1000
    #   max_area: 5000
    #   min_ratio: 0.5
    #   max_ratio: 2.0
    #   min_score: 0.5
    #   threshold: 0.5
    person:
      min_area: 5000
    #   min_ratio: 0.5
    #   max_ratio: 2
    #   min_score: 0.6
    #   threshold: 0.7

cameras:
  # debug:
  #   ffmpeg:
  #     inputs:
  #     - path: /media/frigate/recordings/2024-03-08/07/voordeur/11.28.mp4
  #       input_args: -re -stream_loop -1 -fflags +genpts

  #       roles:
  #       - detect
  #   record:
  #     enabled: False

### Camera VOORDEUR Config ###
  voordeur:
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@1.1.1.37:554/h265Preview_01_main
        roles:
        - record
        - detect
      hwaccel_args: preset-vaapi
    onvif:
      host: 1.1.1.37
      port: 8000
      user: admin
      password: password
    zones:
      vd_pad:
        coordinates: 212,574,216,720,670,720,718,558,297,450
      vd_trottoir:
        coordinates: 648,0,564,0,256,244,0,554,186,584
      vd_stoep:
        coordinates: 682,720,994,720,1014,545,739,495
      vd_weg:
        coordinates: 0,0,397,0,0,378
    objects:
      filters:
        person:
          mask:
            - 642,301,514,285,491,496,611,519
    motion:
      threshold: 50
      mask:
      - 1280,0,1280,39,1205,34,1204,0
      - 0,0,397,0,0,378


  # voordeur_2:
  #   ffmpeg:
  #     inputs:
  #     - path: rtsp://admin:password@1.1.1.37:554/h265Preview_02_main
  #       roles:
  #       - record
  #       - detect
  #     hwaccel_args: preset-vaapi
  #   motion:
  #    mask:
  #    - 1280,0,1280,39,1165,42,1171,0
  #    - 0,0,397,0,0,378
  #   zones:
  #     vd2_pad:
  #       coordinates: 212,574,216,720,670,720,718,558,297,450
  #     vd2_trottoir:
  #       coordinates: 648,0,564,0,256,244,0,554,186,584
  #     vd2_stoep:
  #       coordinates: 682,720,994,720,1014,545,739,495
  #     vd2_weg:
  #       coordinates: 0,0,397,0,0,378
  #   objects:
  #     filters:
  #       person:
  #         mask:
  #         - 615,477,704,476,651,171,599,176

### Camera ACHTER Config ###
  achter:
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@1.1.1.181:554/h264Preview_01_main
        roles:
        - record
        - detect
      hwaccel_args: preset-vaapi
    onvif:
      host: 1.1.1.181
      port: 8000
      user: admin
      password: password
    motion:
      threshold: 50
      mask:
      - 864,0,860,95,606,91,606,0
      - 65,351,0,61,0,720,219,720
    objects:
      filters:
        person:
          mask:
            - 1280,720,661,720,1280,445
    zones:
      hek:
        coordinates: 169,118,451,99,507,60,864,55,838,398,506,270,204,336
      terras:
        coordinates:
          745,720,1280,720,1280,697,507,342,226,394,220,431,294,417,414,556,222,606,289,720
      deur:
        coordinates: 160,450,287,437,383,545,217,596

### Camera BALKON Config ###
  balkon:
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@1.1.1.123:554/h264Preview_01_main
        roles:
        - record
        - detect
      hwaccel_args: preset-vaapi
    onvif:
      host: 1.1.1.123
      port: 8000
      user: admin
      password: password
    motion:
      threshold: 50
      mask:
        - 0,189,0,0,173,0
    objects:
      filters:
        person:
          mask:
            - 547,99,545,151,455,167,445,117
```

### Relevant log output

```shell
homeassistant  | 2024-03-09 11:09:11.462 WARNING (MainThread) [homeassistant.components.automation.dev_catnotify] DEV_CatNotify_Kat voor of achter zones disabled: Maximum number of runs exceeded
homeassistant  | 2024-03-09 11:09:11.626 WARNING (SyncWorker_17) [homeassistant.components.telegram_bot] Status code 404 (retry #1) loading http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4
homeassistant  | 2024-03-09 11:09:11.646 WARNING (SyncWorker_52) [homeassistant.components.telegram_bot] Status code 404 (retry #1) loading http://192.168.1.43:8123/api/frigate/notifications/1709982428.673064-nyuzdc/snapshot.jpg
homeassistant  | 2024-03-09 11:09:11.684 WARNING (SyncWorker_17) [homeassistant.components.telegram_bot] Status code 404 (retry #2) loading http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4
homeassistant  | 2024-03-09 11:09:11.691 WARNING (SyncWorker_52) [homeassistant.components.telegram_bot] Status code 404 (retry #2) loading http://192.168.1.43:8123/api/frigate/notifications/1709982428.673064-nyuzdc/snapshot.jpg
homeassistant  | 2024-03-09 11:09:11.720 WARNING (SyncWorker_17) [homeassistant.components.telegram_bot] Status code 404 (retry #3) loading http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4
homeassistant  | 2024-03-09 11:09:11.740 WARNING (SyncWorker_52) [homeassistant.components.telegram_bot] Status code 404 (retry #3) loading http://192.168.1.43:8123/api/frigate/notifications/1709982428.673064-nyuzdc/snapshot.jpg
homeassistant  | 2024-03-09 11:09:11.755 WARNING (SyncWorker_17) [homeassistant.components.telegram_bot] Status code 404 (retry #4) loading http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4
homeassistant  | 2024-03-09 11:09:11.780 WARNING (SyncWorker_52) [homeassistant.components.telegram_bot] Status code 404 (retry #4) loading http://192.168.1.43:8123/api/frigate/notifications/1709982428.673064-nyuzdc/snapshot.jpg
homeassistant  | 2024-03-09 11:09:11.816 WARNING (SyncWorker_17) [homeassistant.components.telegram_bot] Status code 404 (retry #5) loading http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4
homeassistant  | 2024-03-09 11:09:11.816 WARNING (SyncWorker_17) [homeassistant.components.telegram_bot] Can't load data in http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4 after 5 retries
homeassistant  | 2024-03-09 11:09:11.818 ERROR (SyncWorker_17) [homeassistant.components.telegram_bot] Can't send file with kwargs: {'message': 'A video is shown after cat was detected.', 'url': 'http://192.168.1.43:8123/api/frigate/notifications/1709982420.914392-cyxb3d/voordeur/clip.mp4', 'caption': "*end* END CATNOTIFY VIDEO event id 1709982420.914392-cyxb3d.\ncat detected by camera voordeur\nfrom ['vd_pad'] to ['vd_pad']"}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
