### DISCUSSION TITLE
Error Calling Deepstack API

### DISCUSSION THREAD

**Discussion by 1Kris** [blakeblackshear/frigate#10340] [Config Support]
### Describe the problem you are having

I am attempting to run Deepstack as a detector, but I have been unable to connect.  The Deepstack page is visible at http://192.168.0.8:5001, but I am unable to connect.  I have tried varying ports, IPs, etc.  

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  #hwaccel_args: preset-intel-qsv-h264
  hwaccel_args: preset-vaapi
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  deepstack:
    api_url: 192.168.0.8:5001/v1/vision/detection
    type: deepstack
    api_timeout: 0.1 # seconds
#Global Object Settings
objects:
  track:
  - person
  - car
  - cat
  - dog
  - bicycle
  - motorcycle
  - amazon
  - fedex
  - ups
  - USPS
  filters:
    person:
      min_area: 250
      max_area: 100000
      threshold: 0.60
    car:
      min_area: 600
      max_area: 100000
      threshold: 0.58
record:
  enabled: true
  retain:
    days: 30
    mode: active_objects
  events:
    retain:
      default: 30
      mode: active_objects
    pre_capture: 3
    post_capture: 3
    objects:
    - person
    - car
    - cat
    - dog
    - bicycle
    - motorcycle
    - amazon
    - fedex
    - ups
    - USPS
cameras:
  Front_Cam:
    webui_url: https://192.168.2.10/doc/page/config.asp
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://192.168.2.10:554
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://192.168.2.10:554/Streaming/Channels/102
        roles:
        - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bicycle
        - motorcycle
        - amazon
        - fedex
        - ups
        - USPS
    motion:
      mask:
      - 1280,164,1280,0,0,0,0,112
      - 310,378,328,535,496,565,728,584,826,720,0,720,0,326
      - 831,249,821,313,810,313,813,245
  Driveway_Cam:
    webui_url: https://192.168.2.11/doc/page/config.asp
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://192.168.2.11:554
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://192.168.2.11:554/Streaming/Channels/102
        roles:
        - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - amazon
        - fedex
        - ups
    motion:
      mask:
      - 1035,626,1167,576,1280,683,1280,720,886,720
      - 169,0,154,142,87,142,87,0
  Livingroom_Cam:
    webui_url: https://192.168.2.12/doc/page/config.asp
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://192.168.2.12:554
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://192.168.2.12:554 # rtsp://192.168.2.12:554/Streaming/Channels/102
        roles:
        - detect
    detect:
      width: 3840
      height: 2160
      fps: 5
    objects:
      track:
        - person
telemetry:
  # Optional: Enabled network interfaces for bandwidth stats monitoring (default: empty list, let nethogs search all)
  network_interfaces:
  - eth
  - enp
  - eno
  - ens
  - wl
  - lo
  # Optional: Configure system stats
  stats:
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: true
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
```

### Relevant log output

```shell
2024-03-08 22:22:45.698846071  [2024-03-08 22:22:45] frigate.detectors.plugins.deepstack ERROR   : Error calling deepstack API
```

### Frigate stats

```json
{
    "bandwidth_usages": {
        "1004": {
            "bandwidth": 32.8
        },
        "1008": {
            "bandwidth": 51
        },
        "1014": {
            "bandwidth": 142.3
        },
        "1017": {
            "bandwidth": 1472.3
        },
        "1018": {
            "bandwidth": 1352.4
        },
        "1021": {
            "bandwidth": 142.2
        }
    },
    "cameras": {
        "Driveway_Cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 1002,
            "detection_enabled": 1,
            "detection_fps": 0.7,
            "ffmpeg_pid": 1008,
            "pid": 995,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "Front_Cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 999,
            "detection_enabled": 1,
            "detection_fps": 0,
            "ffmpeg_pid": 1004,
            "pid": 994,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "Livingroom_Cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 1006,
            "detection_enabled": 1,
            "detection_fps": 3.1,
            "ffmpeg_pid": 1014,
            "pid": 997,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "79": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "80": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "96": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "100": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "1.3",
            "cpu_average": "4",
            "mem": "0.6"
        },
        "119": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "147": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "148": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "149": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "171": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "203": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "246": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "269": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "298": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "333": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "374": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "415": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "450": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "491": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "557": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "599": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "631": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "661": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "686": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "702": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "871": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "873": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "880": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(46)",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "886": {
            "cmdline": "frigate.detector.coral1",
            "cpu": "0.4",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "897": {
            "cmdline": "frigate.detector.deepstack",
            "cpu": "0.4",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "907": {
            "cmdline": "frigate.output       ",
            "cpu": "1.3",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "970": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "971": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "972": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "973": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "994": {
            "cmdline": "frigate.process:Front_Cam",
            "cpu": "1.3",
            "cpu_average": "13",
            "mem": "0.5"
        },
        "995": {
            "cmdline": "frigate.process:Driveway_Cam",
            "cpu": "2.2",
            "cpu_average": "16",
            "mem": "0.5"
        },
        "997": {
            "cmdline": "frigate.process:Livingroom_Cam",
            "cpu": "4.3",
            "cpu_average": "83",
            "mem": "0.6"
        },
        "999": {
            "cmdline": "frigate.capture:Front_Cam",
            "cpu": "1.4",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "1002": {
            "cmdline": "frigate.capture:Driveway_Cam",
            "cpu": "1.5",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "1004": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.10:554/Streaming/Channels/102 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.9",
            "cpu_average": "2",
            "mem": "0.2"
        },
        "1006": {
            "cmdline": "frigate.capture:Livingroom_Cam",
            "cpu": "5.0",
            "cpu_average": "3",
            "mem": "0.5"
        },
        "1008": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.11:554/Streaming/Channels/102 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.9",
            "cpu_average": "2",
            "mem": "0.2"
        },
        "1014": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.12:554 -r 5 -vf fps=5,scale_vaapi=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "20.6",
            "cpu_average": "19",
            "mem": "0.4"
        },
        "1017": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.10:554 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "3.3",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "1018": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.11:554 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Driveway_Cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "3.6",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "1021": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.12:554 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Livingroom_Cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "1642": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 3.8,
    "detectors": {
        "coral1": {
            "detection_start": 1709958246.678712,
            "inference_speed": 6.86,
            "pid": 886
        },
        "deepstack": {
            "detection_start": 0,
            "inference_speed": 1.51,
            "pid": 897
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "2.29%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 89
        },
        "logger": {
            "pid": 871
        },
        "recording": {
            "pid": 873
        }
    },
    "service": {
        "last_updated": 1709958251,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 367.3,
                "mount_type": "tmpfs",
                "total": 384,
                "used": 16.7
            },
            "/media/frigate/clips": {
                "free": 4415.6,
                "mount_type": "overlay",
                "total": 15035,
                "used": 9948.1
            },
            "/media/frigate/recordings": {
                "free": 4415.6,
                "mount_type": "overlay",
                "total": 15035,
                "used": 9948.1
            },
            "/tmp/cache": {
                "free": 4415.6,
                "mount_type": "overlay",
                "total": 15035,
                "used": 9948.1
            }
        },
        "temperatures": {
            "apex_0": 60.55
        },
        "uptime": 110,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/23587989/7f5ddce6-e45c-46ff-8aa6-51ff594b2379)

![image](https://github.com/blakeblackshear/frigate/assets/23587989/7e436b2c-6061-4b4f-837b-9c95ce883ec0)
