### DISCUSSION TITLE
[Detector Support]: Audio how to debug why not catch the event

### DISCUSSION THREAD

**Discussion by MG-Sky** [blakeblackshear/frigate#10344] [Detector Support]
### Describe the problem you are having

I want to use a reolink cam to detect audio ('ringtone' type) when my intercom rings, I see in MQQT explorer the values are changing when it calls ~70-200RMS, but no event in frigate, I have tested all 500 samples and only twice get 'ringtone' (Ringtone: 59%). 
I have added the few seconds of the event that were recorded by frigate - only once (whole ringing  took about 40-50 secs.).

Is there any way how i can measure why ?
[output-audio.zip](https://github.com/blakeblackshear/frigate/files/14546374/output-audio.zip)

### Version

13.2

### Frigate config file

```yaml
mqtt:
  host: IP
  stats_interval: 30

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  logs:
    frigate.event: debug 
    
cameras:
  garaz:
    webui_url: "https://kamera-garaz.IP"
    birdseye:
      mode: motion
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://{PASS}@IP:554/h264Preview_01_sub 
          roles:
            - audio
            - detect
            - rtmp
        - path: rtsp://{PASS}@IP:554/h264Preview_01_main # <-- 101 mainstream
          roles:
            - record  
    onvif:
      host: IP
      port: 8000
      user: XXX
      password: XXX
    detect:
      enabled: True 
      width: 640 
      height: 480 
      fps: 7  
      stationary:
        interval: 25
        threshold: 50
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
       person:
         min_score: 0.4
         threshold: 0.64
         min_area: 210
       dog:
         min_score: 0.4
         threshold: 0.57
       cat:
         min_score: 0.4
         threshold: 0.57
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
       # pre_capture: 10
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 7
            cat: 7
            car: 30
            person: 30
 
  kuchnia:
    live:
      stream_name: kuchnia_sub
    webui_url: "https://kamera-kuchnia.IP"
    birdseye:
      mode: objects
    ffmpeg:
  #    hwaccel_args: preset-vaapi 
      inputs:
        - path: rtsp://127.0.0.1:8554/kuchnia_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - rtmp
        - path: rtsp://127.0.0.1:8554/kuchnia_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true 
      width: 640
      height: 480 
      fps: 4
      stationary:
        interval: 40
        threshold: 50
    objects:
      track:
        - person
        - cat
        - dog
        - car
      filters:
       car:
         mask: 
           - 401,209,405,289,525,289,528,205
    #   person:
    #     min_score: 0.5
    #     threshold: 0.7
       dog:
         min_score: 0.3
         threshold: 0.5
       cat:
         min_score: 0.5
         threshold: 0.7
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        pre_capture: 3
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 7
            cat: 7
            car: 30
            person: 30
    motion:
      mask:
      #  - 401,209,405,289,525,289,528,205
        - 428,480,0,480,0,0,282,0,333,30,348,89,349,277,352,333,381,366,388,386,402,430,436,452
        - 550,108,588,251,556,352,575,415,557,480,640,480,640,0,249,0,309,67
    onvif:
      host: IP
      port: 8000
      user: USER
      password: PASS

  salon:
    live:
      stream_name: salon_sub
    webui_url: "https://kamera-salon.IP"
    birdseye:
      mode: motion
    ffmpeg:
  #    hwaccel_args: preset-vaapi 
      inputs:
        - path: rtsp://127.0.0.1:8554/salon_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - rtmp
        - path: rtsp://127.0.0.1:8554/salon_main
          input_args: preset-rtsp-restream
          roles:
            - record
			
################MY SETUP IS HERE ##############
    audio:
      enabled: true
      max_not_heard: 7
      min_volume: 60
      listen:
        - ringtone
      filters:
        ringtone:
          threshold: 0.5
###################################
    detect:
      enabled: true 
      width: 640
      height: 480 
      fps: 7
      stationary:
        interval: 40
        threshold: 50
    objects:
      track:
        - person
    #   person:
    #     min_score: 0.5
    #     threshold: 0.7
    motion:
      threshold: 30
      mask:
        - 191,0,188,22,0,21,0,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        pre_capture: 4
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 7
            cat: 7
            car: 30
            person: 30
    onvif:
      host: IP
      port: 8000
      user: USER
      password: PASS
      autotracking:
        enabled: false
        calibrate_on_startup: false
        zooming: absolute
        zoom_factor: 0.4
        track:
          - person
        required_zones:
          - drzwi
          - balkon
        return_preset: home
        timeout: 15
        # movement_weights: []
motion:
  improve_contrast: true
  
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  
go2rtc:
  rtsp:
    #username: "frigate"
    #password: "frigate12345678"
  streams:
    garaz:
      - rtsp://{PASS}@IP:554/h264Preview_01_sub
    kuchnia_sub:
      -  ffmpeg:rtsp://{PASS}@IP:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
    kuchnia_main:
      - ffmpeg:rtsp://{PASS}@IP:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
    salon_sub:
      - ffmpeg:rtsp://{PASS}@IP:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
    salon_main:
      - ffmpeg:rtsp://{PASS}@IP:554/h264Preview_01_main#video=copy#audio=copy#audio=opus

  webrtc:
    candidates:
      - IP:8555
      - frigate.IP
      - stun:8555
      - 100.0.0.0/8
```

### docker-compose file or Docker CLI command

```yaml
not related.
```

### Relevant log output

```shell
no output
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
