### DISCUSSION TITLE
[Support]: Frigate (standalone) was hacked! Found this in my config file

### DISCUSSION THREAD

**Discussion by FS1961** [blakeblackshear/frigate#10348] [General Support]
### Describe the problem you are having

Checked my Frigate via proxy and most of my cameras weren't working.  Checked the config file and found this instead. I'm running via Portainer/Docker on a separate Ubuntu host. I've changed all the userids/passwords on the cameras, the Portainer login, the Ubuntu host.  Not sure where they would have gotten in.

Everything is shutdown at the moment. Trying to get an idea if they came from the HA into the Proxy Add-On, directly into the server somehow, through Portainer, etc.

1) Is this a common problem?

2) Anyone else have this happen?

3) Since I'm using the proxy add-on, do I even need these ports open? I use Frigate cards in my Lovelace and also have the UI in the sidebar. Don't really go directly to the Frigate server at all.

Appreciate any support, links to locking down the system, etc.

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.82
  user: mqtt
  password: password

# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!

# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!

# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!
# HACKED WE CANN SEE YOU!

# HACKED WE CANN SEE YOU!

ffmpeg:
  hwaccel_args: preset-vaapi
    
go2rtc:
  streams:
    Office:
      - "rtsp://frigate:passwd@192.168.178.xx:554/stream1"
      - "ffmpeg:Office#audio=aac"

cameras:
  Dining: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:passwd@192.168.178.xx:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: True
      events:
        retain:
          mode: motion
          default: 10


            

detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects

telemetry:
  stats:
    intel_gpu_stats: True

  version_check: True

ui:
  timezone: Europe/Berlin
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/a

### Any other information that may be helpful

Here is my Portainer stack:

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frank/frigate/:/config
      - /mnt/sdb/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"  #modify to whatever if using rtsp
      TZ: "Europe/Berlin"
