### DISCUSSION TITLE
[Config Support]: Motion mask enabled and still, events are created

### DISCUSSION THREAD

**Discussion by TheSleepySlee** [blakeblackshear/frigate#10361] [Config Support] [answered]
### Describe the problem you are having

Hello,
I have create a motion mask, but events are still being created

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
portailcam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.50:554/cam/realmonitor?channel=1&subtype=1&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.0.50:554/cam/realmonitor?channel=1&subtype=1&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0,1080,572,1080,798,771,671,456,0,212
    best_image_timeout: 20
    zones:
      portailout:
        coordinates: 684,1078,894,648,780,595,779,531,1157,517,1910,402,1913,999,996,988
        filters:
          person:
            min_score: 0.4
            threshold: 0.5
          car:
            min_score: 0.4
            threshold: 0.5
    detect:
      enabled: True
      max_disappeared: 10
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 21
          mode: all  # default = motion
        pre_capture: 15
        post_capture: 60
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True
      height: 500
```

### Relevant log output

```shell
NTR
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Although motion masks are set correctly as can be seen on attached pictures, some events are created (between 5 and 6 stored).
<img width="535" alt="2024-03-10 à 16 46 23" src="https://github.com/blakeblackshear/frigate/assets/13090430/5d9e88fc-00a5-403b-b869-715a350ee2bb">
<img width="519" alt="2024-03-10 à 16 46 03" src="https://github.com/blakeblackshear/frigate/assets/13090430/89246729-d36d-47ca-b4ec-3fd5da850c56">
<img width="519" alt="2024-03-10 à 16 45 44" src="https://github.com/blakeblackshear/frigate/assets/13090430/64a684f9-e8cf-4229-81e1-f6adfb13c532">
<img width="551" alt="2024-03-10 à 16 41 44" src="https://github.com/blakeblackshear/frigate/assets/13090430/b4957b26-ba25-4821-9620-e9ecb57e6bb7">

Anything wrong I'm doing on the configuration? Sorry, I think there is something I don't understand in motion masks.
thanks for your help

**Comment by TheSleepySlee** [comment]
Is this due to this?

```
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 21
          mode: all  # default = motion
``` 


If yes, if I move events to 'motion', will I still be able to export recordings (over the pasrt 3 days) since recording retain set to 'all' ?

thanks

**Comment by nwish** [comment, marked as answer]
Motion masks don’t stop object detection, they only cause motion to be ignored in that area.  So in your case, a Frigate restart or even motion outside the mask could still trigger object detection.

Based on the section of your camera view that you shared, I would look into using a max_area for cars, because it looks like that guy would be way bigger than any car in your view.  What this would do is tell Frigate that anything with a total area (w x h) larger than the number of pixels you specify for car, cannot be a car.

**Reply by TheSleepySlee** [reply]
Thanks. Can this be set out of zones? I can only make it work for zones.
I set it for all cams in general config and works fine.

**Reply by NickM-27** [reply]
```
cameras:
  a_camera:
    objects:
      filters:
        car:
          max_area: 1234
```
