### DISCUSSION TITLE
[Support]: Frigate stuck in boot loop (fresh install)

### DISCUSSION THREAD

**Discussion by 8BK8** [blakeblackshear/frigate#10369] [General Support]
### Describe the problem you are having

- I've run Frigate before, but it's been nearly 2 years since. I'm revisiting Frigate today on a fresh install via Docker.
- Frigate stuck in bootloop.
- Frigate installed using docker_compose today.
- Frigate using the dummy config.
- Docker logs show nothing obviously wrong with config, just some exit codes and service stopping and starting.
- Visiting the UI on port :5000 returns a blank page with a loading circle in the middle.
- Installed Coral PCIe and drivers per https://coral.ai/docs/m2/get-started/#troubleshooting-on-linux
  ```
  # ls /dev/apex_0 
  /dev/apex_0
  ```

Docker compose file:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: “64mb” # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-uuid-8f381fec-b65a-42bc-ba14-20a8d8a37a64/cctv/config:/config
      - /srv/dev-disk-by-uuid-8f381fec-b65a-42bc-ba14-20a8d8a37a64/cctv/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: “password”
```

### Version

UI Blank/unreachable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  front:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.0.199:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

detectors:
  coral_pci:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-03-10 22:54:50.048909268  [INFO] Preparing new go2rtc config...
2024-03-10 22:54:50.057759115  [INFO] Preparing Frigate...
2024-03-10 22:54:50.072506121  [INFO] Starting NGINX...
2024-03-10 22:54:50.165284819  [INFO] Starting Frigate...
2024-03-10 22:54:51.101874423  [INFO] Starting go2rtc...
2024-03-10 22:54:51.404678202  22:54:51.404 INF go2rtc version 1.8.4 linux/amd64
2024-03-10 22:54:51.406255500  22:54:51.406 INF [rtsp] listen addr=:8554
2024-03-10 22:54:51.407026329  22:54:51.406 INF [webrtc] listen addr=:8555
2024-03-10 22:54:51.410245195  22:54:51.410 INF [api] listen addr=:1984
2024-03-10 22:54:54.620573333  2024/03/10 22:54:54 [error] 146#146: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
2024-03-10 22:54:54.871535094  [INFO] Service Frigate exited with code 256 (by signal 4)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-03-10 22:54:54.922128698  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-03-10 22:54:54.968944439  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-03-10 22:54:55.025178023  exit with signal: terminated
s6-rc: info: service nginx-log successfully stopped
2024-03-10 22:54:55.069122095  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
2024-03-10 22:55:04.577382387  [INFO] Preparing new go2rtc config...
2024-03-10 22:55:04.585157652  [INFO] Preparing Frigate...
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2024-03-10 22:55:04.613171802  [INFO] Starting NGINX...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-03-10 22:55:04.649736095  [INFO] Starting Frigate...
s6-rc: info: service legacy-services successfully started
2024-03-10 22:55:05.885668976  [INFO] Starting go2rtc...
2024-03-10 22:55:06.135576659  22:55:06.135 INF go2rtc version 1.8.4 linux/amd64
2024-03-10 22:55:06.136695104  22:55:06.136 INF [rtsp] listen addr=:8554
2024-03-10 22:55:06.137109177  22:55:06.137 INF [webrtc] listen addr=:8555
2024-03-10 22:55:06.140163153  22:55:06.139 INF [api] listen addr=:1984
2024-03-10 22:55:08.741585073  [INFO] Service Frigate exited with code 256 (by signal 4)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-03-10 22:55:08.830996806  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-03-10 22:55:08.865160355  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-03-10 22:55:08.891263242  exit with signal: terminated
s6-rc: info: service nginx-log successfully stopped
2024-03-10 22:55:08.932365799  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
ffprobe "rtsp://user:pass@192.168.0.199:554/cam/realmonitor?channel=1&subtype=1"
ffprobe version 4.3.6-0+deb11u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://user:pass@192.168.0.199:554/cam/realmonitor?channel=1&subtype=1':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt470bg/bt470bg/smpte170m), 704x576, 20 fps, 20 tbr, 90k tbn, 20 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua
