### DISCUSSION TITLE
[Support]: Error Saving Zones in Frigate Using Mask & Zone Creator Feature

### DISCUSSION THREAD

**Discussion by dan246** [blakeblackshear/frigate#10371] [General Support]
### Describe the problem you are having

I'm experiencing an issue with the Frigate application, specifically with the Mask & Zone Creator feature. When I attempt to save a zone, an error occurs, despite the config file containing data. However, upon restarting, the zones appear correctly.

### Version

0.13.2

### Frigate config file

```yaml
cameras:
  camera111:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp url
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
      - Pane For IV Injection
      - Sodium Bicarbonate
      - Relecox
      - Senokot
      - Dexilant
      - Ursolic
    record:
      enabled: true
    snapshots:
      enabled: true
  camera129:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp url
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
      - smoke
      - fire
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 608,599,767,601,702,227,545,238
      - 1188,884,1576,912,1548,619,1206,632
      - 1416,941,1616,927,1627,747,1422,749
    zones:
      zone_0:
        coordinates: 1251,1009,1517,1004,1540,844,1285,846
      zone_1:
        coordinates: 506,993,871,991,876,831,488,795
      zone_2:
        coordinates: 1339,581,1297,926,788,875,803,536
detectors:
  ov:
    device: AUTO
    model:
      path: /workspace/frigate/export_yolov8/firesmoke/best.pt
    type: fire_smoke
  ov1:
    device: AUTO
    model:
      path: 
        /workspace/frigate/export_yolov8/Construction_Site_Safety_yolov8n_20240308/best.pt
    type: Construction_Site
  ov2:
    device: AUTO
    model:
      path: /workspace/frigate/export_yolov8/drug_20240116/best.pt
    type: drug_detection
model:
  height: 640
  input_pixel_format: bgr
  input_tensor: nhwc
  labelmap_path: 
  /workspace/frigate/export_yolov8/Construction_Site_Safety_yolov8n_20240308/Construction_Site_Safety_yolov8n_20240308.names
  model_type: yolov8
  width: 640
mqtt:
  host: mqtt
snapshots:
  enabled: true
  retain:
    default: 5
```

### Relevant log output

```shell
JSMpegPlayer-3ca557cc.js:9 WebSocket connection to 'ws://192.168.50.15:15000/live/jsmpeg/camera129' failed: Received a broken close frame containing a reserved status code.
a.start @ JSMpegPlayer-3ca557cc.js:9

JSMpegPlayer-3ca557cc.js:9 WebSocket connection to 'ws://192.168.50.15:15000/live/jsmpeg/camera129' failed: Received a broken close frame containing a reserved status code.
a.start @ JSMpegPlayer-3ca557cc.js:9

index-2f8c73aa.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'is')
    at fa (index-2f8c73aa.js:1:8262)
    at er (index-2f8c73aa.js:1:7647)
    at To (index-2f8c73aa.js:1:2601)
    at fa (index-2f8c73aa.js:1:8848)
    at er (index-2f8c73aa.js:1:7647)
    at To (index-2f8c73aa.js:1:2601)
    at fa (index-2f8c73aa.js:1:8848)
    at er (index-2f8c73aa.js:1:7647)
    at To (index-2f8c73aa.js:1:2601)
    at er (index-2f8c73aa.js:1:7312)
```

### FFprobe output from your camera

```shell
none
```

### Frigate stats

```json
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

none

### Any other information that may be helpful

After clicking "save," the interface becomes unresponsive.
