### DISCUSSION TITLE
[HW Accel Support]: Rockchip ffmpeg / GPU

### DISCUSSION THREAD

**Discussion by csvke** [blakeblackshear/frigate#10383] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Is there any way to verify if hardware acceleration is properly setup and running?  **Hardware acceleration has not been setup, see the docs to setup hardware acceleration.**

ffmpeg shows CPU usages is consistently over 50%

Also, I'm aware that there's this pull request [](https://github.com/blakeblackshear/frigate/pull/10034), can I incorporate that without rebuilding?

### Version

0.13.2

### Frigate config file

```yaml
# yaml-language-server: $schema=http://rock3c.local:5000/api/config/schema.json
# VSCode supports JSON schemas for automatically validating configuration files, see: https://docs.frigate.video/configuration/#vscode-configuration-schema

##### For Rerference config, see: https://docs.frigate.video/configuration/reference #####

logger:
  default: debug
  logs:
    ffmpeg.luckfox-pico-max: debug
    go2rtc: info

mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-rk-h264
    

detectors: # required
  rknn: # required
    type: rknn # required
    # core mask for npu
    core_mask: 0b111

model: # required
  # name of yolov8 model or path to your own .rknn model file
  # possible values are:
  # - default-yolov8n
  # - default-yolov8s
  # - default-yolov8m
  # - default-yolov8l
  # - default-yolov8x
  # - /config/model_cache/rknn/your_custom_model.rknn
  path: default-yolov8n
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

record: # todo: record all
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  restream: true


go2rtc:
  streams:
    luckfox-pico-max:
      - rtsp://192.168.1.23/live/1
      - "ffmpeg:luckfox-pico-max#video=h264/rk#audio=copy#audio=opus" # See: https://deploy-preview-9487--frigate-docs.netlify.app/configuration/hardware_acceleration/#go2rtc-presets-for-hardware-accelerated-transcoding
    # rpizero-uvc-x003:
    #   - "rtsp://192.168.1.96:8554/live/stream"
    testing:
      - rtsp://192.168.1.23/live/1
      - "ffmpeg:testing#video=h264/rk#audio=copy#audio=opus" # See: https://deploy-preview-9487--frigate-docs.netlify.app/configuration/hardware_acceleration/#go2rtc-presets-for-hardware-accelerated-transcoding

cameras:
  luckfox-pico-max:
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/luckfox-pico-max
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
  testing:
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/testing
          input_args:  preset-rtsp-restream
          roles:
            - record
            - detect

##### This camera has been disabled but the prove of concept is that RPi Zero can host HD Camera with RTSP #####
  # rpizero-uvc-x003:
  #   ffmpeg:
  #     hwaccel_args: preset-rpi-64-h264
  #     inputs:
  #       - path: rtsp://192.168.1.96:8554/live/stream
  #         input_args: preset-rtsp-restream-low-latency
  #         roles:
  #           - record
  #   record:
  #     enabled: True
  #     retain:
  #       days: 7
  #       mode: all
  #   detect:
  #     enabled: False
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 1s
    group_add:
      - "106" # render
      - "44"  # video
      - "46"  # plugdev
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    # image: ghcr.io/blakeblackshear/frigate:0.13.0-rk
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # https://github.com/blakeblackshear/frigate/pull/8355#issue-1965373589
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/rga:/dev/rga
      - /dev/video-dec0:/dev/video-dec0
      - /dev/video-enc0:/dev/video-enc0
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - /dev/mpp_service:/dev/mpp_service
      - /dev/dma_heap:/dev/dma_heap

      # - /dev/shm:/dev/shm

    volumes:
      - ~:/root
      - /etc/localtime:/etc/localtime:ro
      - /media/nvme/frigate/config/:/config/
      - /media/nvme/frigate/media/:/media/frigate/
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - /usr/lib/aarch64-linux-gnu/librockchip_mpp.so:/usr/lib/aarch64-linux-gnu/librockchip_mpp.so
      - /usr/lib/aarch64-linux-gnu/librockchip_mpp.so.0:/usr/lib/aarch64-linux-gnu/librockchip_mpp.so.0
      - /usr/lib/aarch64-linux-gnu/librockchip_mpp.so.1:/usr/lib/aarch64-linux-gnu/librockchip_mpp.so.1
      - /usr/lib/aarch64-linux-gnu/librockchip_vpu.so:/usr/lib/aarch64-linux-gnu/librockchip_vpu.so
      - /usr/lib/aarch64-linux-gnu/librockchip_vpu.so.0:/usr/lib/aarch64-linux-gnu/librockchip_vpu.so.0
      - /usr/lib/aarch64-linux-gnu/librockchip_vpu.so.1:/usr/lib/aarch64-linux-gnu/librockchip_vpu.so.1
      # - /root/host/FFmpeg/libyuv.so:/usr/lib/aarch64-linux-gnu/libyuv.so
      # - /root/host/FFmpeg/libyuv.so.0:/usr/lib/aarch64-linux-gnu/libyuv.so.0
      # - /root/host/FFmpeg/libyuv.so.0.0.1873:/usr/lib/aarch64-linux-gnu/libyuv.so.0.0.1873
      - /usr/lib/aarch64-linux-gnu/pkgconfig/rockchip_vpu.pc:/usr/lib/aarch64-linux-gnu/pkgconfig/rockchip_vpu.pc
      - /usr/lib/aarch64-linux-gnu/pkgconfig/rockchip_mpp.pc:/usr/local/lib/aarch64-linux-gnu/pkgconfig/rockchip_mpp.pc
      # - /root/host/FFmpeg/rockchip:/usr/local/include/rockchip
      # - /root/frigate/frigate/detectors/plugins/armnn_tfl.py:/opt/frigate/frigate/detectors/plugins/armnn_tfl.py
      # - /usr/lib/aarch64-linux-gnu/libarmnn.so.32:/usr/lib/aarch64-linux-gnu/libarmnn.so.32
      # - /usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so:/usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so
      # - /usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.24.6:/usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.24.6
      # - /usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.24:/usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.24
      # - /usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.22:/usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.22
      # - /usr/lib/aarch64-linux-gnu/include/armnnTfLiteParser:/usr/lib/aarch64-linux-gnu/include/armnnTfLiteParser
      # - /usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.22.0:/usr/lib/aarch64-linux-gnu/libarmnnTfLiteParser.so.22.0
      - /usr/lib/aarch64-linux-gnu/libOpenCL.so:/usr/lib/aarch64-linux-gnu/libOpenCL.so
      - /usr/lib/aarch64-linux-gnu/libmali-x11:/usr/lib/aarch64-linux-gnu/libmali-x11
      - /usr/lib/aarch64-linux-gnu/pkgconfig/OpenCL.pc:/usr/lib/aarch64-linux-gnu/pkgconfig/OpenCL.pc
      - /etc/OpenCL/vendors/mali-arm64.icd:/etc/OpenCL/vendors/mali-arm64.icd
      # - /usr/lib/aarch64-linux-gnu/armnn22:/usr/lib/aarch64-linux-gnu/armnn22
      # - /usr/lib/aarch64-linux-gnu/armnn32:/usr/lib/aarch64-linux-gnu/armnn32
      # - /usr/lib/python3/dist-packages/pyarmnn:/usr/lib/python3/dist-packages/pyarmnn
      # - /usr/lib/ArmNN-linux-aarch64:/usr/lib/ArmNN-linux-aarch64
      # - /usr/lib/aarch64-linux-gnu/libarm_compute.so.31:/usr/lib/aarch64-linux-gnu/libarm_compute.so.31
      # - /usr/lib/aarch64-linux-gnu/libarm_compute_core.so.31:/usr/lib/aarch64-linux-gnu/libarm_compute_core.so.31
      # - /usr/lib/aarch64-linux-gnu/libarm_compute_graph.so.31:/usr/lib/aarch64-linux-gnu/libarm_compute_graph.so.31 
      # - /usr/lib/aarch64-linux-gnu/libarmnnAclCommon.so.32:/usr/lib/aarch64-linux-gnu/libarmnnAclCommon.so.32
      # - /usr/lib/aarch64-linux-gnu/libarmnnDeserializer.so.32:/usr/lib/aarch64-linux-gnu/libarmnnDeserializer.so.32
      # - /usr/lib/aarch64-linux-gnu/libarmnnSerializer.so.32:/usr/lib/aarch64-linux-gnu/libarmnnSerializer.so.32
      # - /srv/docker/frigate/armnn-23.05:/build/armnn-ZUc8OU/armnn-23.05
      # - /usr/lib/aarch64-linux-gnu/libmali-x11/libmali-valhall-g610-g13p0-x11-wayland-gbm.so:/usr/lib/aarch64-linux-gnu/libmali.so      

    # ports:
    #   - "5000:5000"
    #   - "8554:8554" # RTSP feeds
    #   - "8555:8555/tcp" # WebRTC over tcp
    #   - "8555:8555/udp" # WebRTC over udp
    network_mode: host

    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 1

Error:
```

### FFprobe output from your camera

```shell
ffprobe version e243e8d001-20231113 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-nonfree --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --enable-libdrm --enable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --disable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --disable-libvpx --enable-libwebp --enable-lv2 --enable-rkmpp --disable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --disable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lstdc++ -lgomp' --extra-version=20231113
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://192.168.1.23/live/1':
  Metadata:
    title           : rtsp_demo
  Duration: N/A, start: -0.050000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, stereo, s16, 128 kb/s
mpp[4864]: mpi: mpp_create enter ctx 0xaaaaf9440660 mpi 0xaaaaf9440668
mpp[4864]: mpp_info: mpp version: 1844ec5 author: MarcA711       2023-11-12 add -lstdc++ to Libs.private
mpp[4864]: mpi: mpp_create leave ret 0 ctx 0xaaaaf91e5340 mpi 0xaaaaeee8e948
mpp[4864]: mpi: mpi_control enter ctx 0xaaaaf91e5340 cmd 310006 parm 0xffffebd58d34
mpp[4864]: mpi: mpi_control leave ctx 0xaaaaf91e5340 ret 0
[h264_rkmpp_decoder @ 0xaaaaf93e9300] Picture format is yuv420p.
mpp[4864]: mpi: mpp_init enter ctx 0xaaaaf91e5340 type 0 coding 7
mpp[4864]: mpi: mpp_init leave ctx 0xaaaaf91e5340 ret 0
mpp[4864]: mpi: mpi_control enter ctx 0xaaaaf91e5340 cmd 310002 parm 0xaaaaf9338ba8
mpp[4864]: mpi: mpi_control leave ctx 0xaaaaf91e5340 ret 0
mpp[4864]: mpi: mpi_control enter ctx 0xaaaaf91e5340 cmd 31000b parm (nil)
mpp[4864]: mpi: mpi_control leave ctx 0xaaaaf91e5340 ret 0
mpp[4864]: mpi: mpi_reset enter ctx 0xaaaaf91e5340
mpp[4864]: mpi: mpi_reset leave ctx 0xaaaaf91e5340 ret 0
mpp[4864]: mpi: mpp_destroy enter ctx 0xaaaaf91e5340
mpp[4864]: mpi: mpp_destroy leave ctx 0xaaaaf91e5340 ret 0
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Rockchip rv1106
