### DISCUSSION TITLE
[Config Support]: Testing with mp4 files freezes Frigate

### DISCUSSION THREAD

**Discussion by jiiins** [blakeblackshear/frigate#10399] [Config Support]
### Describe the problem you are having

I'm trying to test masks and filters using [these instructions](https://docs.frigate.video/development/contributing/#2-modify-your-local-config-file-for-testing) on a live HA add-on, but it seems like the CPU gets overloaded and the entire Frigate starts to hiccup. Is there a way around it? I don't have a separate machine to do this. 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
#logger:
#  logs:
#    frigate.record.maintainer: debug

database:
  path: /config/frigate.db

mqtt:
  host: 192.168.21.224
  port: 1883
  user: mqtt_user
  password: mqtt33

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

#ffmpeg:
#  hwaccel_args: -hwaccel vaapi

cameras:
  00_test:
    enabled: false
    ffmpeg:
      inputs:
        - path: /media/frigate/fr1.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 1280,0,1280,370,1221,411,927,375,915,160,528,201,0,315,0,0
      - 0,557,183,468,313,331,0,55
    objects:
      filters:
        person:
          min_score: 0.60
          threshold: 0.67
    zones:
      sotto_passerella:
        coordinates: 927,112,285,205,424,450,966,422
        filters:
          person:
            min_score: 0.60
            threshold: 0.67
            max_area: 5000

  01_citofono:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.21.51/media?vcodec=h264&vres=640x480&fps=5&vbr=2048&zipstream=medium
        roles:
        - detect
            # - record
      - path: 
          rtsp://*:*@192.168.21.51/media?audio=1&vcodec=h264&vres=640x480&fps=15&vbr=2048&zipstream=low
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 960
    motion:
      mask:
      - 0,0,400,0,1280,0,1280,79,880,239,438,259,435,437,320,431,193,468,0,516

  01a_strada:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.116/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.116/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  01b_cancellone:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.112/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.112/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      parking:
        coordinates: 1141,349,1171,203,1112,174,1004,160,838,221
        objects:
        - person
        - cat
        - dog

  01c_borella:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.113/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.113/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 720
      height: 1280

  01d_piazzale:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.111/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.111/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 967,114,737,52,383,0,1280,0,1280,514,1197,500,1107,484,939,312
      - 31,400,159,294,143,0,0,0,0,394,0,720,141,720
    objects:
      filters:
        person:
          max_area: 50000
          mask:
            - 746,105,561,68,548,190,722,246
        car:
          mask:
            - 169,238,472,141,916,299,1057,452,1004,720,482,720

  02_entrata:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.110/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.110/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 184,236,0,288,0,0,187,0,210,174,311,669

  031_sinistra:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.109/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.109/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 720
      height: 1280

  04_lavanderia:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.114/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.114/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720

  05_zen:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.103/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.103/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 0,720,0,0,148,0,254,284,246,292,320,492,452,656,510,720
      - 937,527,922,419,784,337,414,204,247,272,112,0,1280,0,1280,542

  06_pergola:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.105/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.105/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 0,0,1280,0,1280,151,666,59,484,71,279,169,44,303,0,262
      - 238,267,335,240,254,345,178,326
    objects:
      filters:
        person:
          mask:
          - 0,720,312,720,816,720,412,593,240,497,248,475,0,273
          - 120,177,190,123,258,203,416,137,456,97,534,67,844,71,888,143,1280,159,1280,0,0,0,0,303
          min_score: 0.60
          threshold: 0.67
          max_area: 8000

  06b_palo:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.115/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.115/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720

  07_piscina:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.106/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.106/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 90,306,150,186,198,160,244,138,194,186,230,250,560,134,814,106,956,214,1114,260,1280,382,1280,362,1280,0,814,0,314,0,0,0,0,494

  08_sauna:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.104/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.104/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 961,178,765,176,545,212,548,301,0,520,0,0,1280,0,1280,368
    objects:
      filters:
        dog:
          max_area: 10000
        cat:
          max_area: 5000


  08b_master:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.107/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.107/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 1280,0,1280,370,1221,411,927,375,915,160,528,201,0,315,0,0
      - 0,557,183,468,313,331,0,55
    objects:
      filters:
        person:
          min_score: 0.60
          threshold: 0.67
    zones:
      sotto_passerella:
        coordinates: 927,112,285,205,424,450,966,422
        filters:
          person:
            min_score: 0.60
            threshold: 0.67
            max_area: 5000

  08c_angolo:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.108/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.108/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  09_bamboo:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.102/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.102/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 1280,720,1280,0,1166,0,916,0,906,354,960,428,898,720
      - 916,0,920,130,576,156,0,720,0,0
  10_termopompa:
    ffmpeg:
      inputs:
      - path: 
          rtsp://*:*@192.168.31.101/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
      - path: rtsp://*:*@192.168.31.101/axis-media/media.amp?streamprofile=hass_view
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
      - 1280,720,1280,0,934,0,918,333,998,720
      - 258,275,542,175,964,0,404,0,0,0,0,419

timestamp_style:
  format: '%d.%m.%Y %H:%M:%S'

snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 180
record:
  enabled: true
  retain:
    days: 14
    mode: motion
  events:
    objects:
    - person
    - car
    retain:
      default: 14
      objects:
        person: 21
        car: 10
objects:
  track:
  - car
  - person
  - cat
  - dog
```

### Relevant log output

```shell
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
is there a reason you're not using hwaccel? that is probably the problem, that your machine can't keep up with decoding via software

**Reply by jiiins** [reply]
I tried a few times but I can't find a way to make it work. It's an Intel NUC8i5BEH, with HAOS running on Proxmox.

**Comment by mitchell-pioneer** [comment]
I see your using axis cameras, so am I.  Did you ever get to the bottom of this?

**Reply by jiiins** [reply]
Yes, I finally enabled hwaccel and it sorts of work (still not very smooth but usable). But I don’t think it has anything to do with Axis, it’s a host issue.

**Comment by mitchell-pioneer** [comment]
Do you mind sharing the urls you used?

Mitchell Balsam
646-552-2097
________________________________

**Comment by jiiins** [comment]
This is the config for the mp4 camera:
```

  99_test:
    enabled: false
    ffmpeg:
      inputs:
        - path: /media/frigate/fr1.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
```

And this is the axis cam:
```
  02_park:
    ffmpeg:
      inputs:
      - path: 
          rtsp://user:pass@192.168.XX.XXX/axis-media/media.amp?streamprofile=hass_detect
        roles:
        - detect
```
