### DISCUSSION TITLE
Frigate Lovelace card - cannot figure out how to implement custom action

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#10391] [General]
I would like to make my Frigate card act like a button itself so that when it it is tapped, the "fullscreen" action is initiated without having a menu on the card. 

I've read the Frigate Lovelace github but I can't figure this out. I think it might use "image.actions" or "view.actions" but I can't figure out how to get this functionality to work. Can someone please point out the error in my yaml code for the card?

Here is the code:

```
square: false
type: grid
cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.street
        live_provider: image
        dependencies:
          cameras:
            - street_sub
      - camera_entity: camera.street
        live_provider: go2rtc
        id: street_sub
        hide: true
        go2rtc:
          modes:
            - mse
    image:
      actions:
        tap:
          action: custom:frigate-card-action
          frigate_card_action: fullscreen
    menu:
      style: none
    automations:
      - conditions:
          fullscreen: true
        actions:
          - action: custom:frigate-card-action
            frigate_card_action: live_substream_on
        actions_not:
          - action: custom:frigate-card-action
            frigate_card_action: live_substream_off
columns: 3
```
