### DISCUSSION TITLE
[Support]: problem high utilization CPU (VM on QNAP NAS using Coral USB TPU)

### DISCUSSION THREAD

**Discussion by pilot1981** [blakeblackshear/frigate#10393] [General Support]
### Describe the problem you are having

Hi,
I have VM on QNAP with Coral USB TPU; it has high utilization Intel CPU (90%) ...already tried to apply suggestion in documentation.

NAS QNAP TS-453D-8G:
- Processore Intel® Celeron® J4125 4-core/4-thread, fino a 2,7 GHz
- Intel® HD Graphics 600

### Version

0.13.2

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.6.31
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: danielevelardi
  password: xxxxxxx
  stats_interval: 60
cameras:
  cancello:
    detect:
      width: 2560
      height: 1440
      fps: 5
    ffmpeg:
      global_args: -hide_banner -loglevel fatal
      inputs:
      - path: rtsp://192.168.4.11:554/user=admin&password=xxxxx&channel=1
        roles:
        - detect
        - rtmp
    snapshots:
      enabled: true
      retain:
        default: 30
    objects:
      track:
      - person
      - car
      - truck
      - bicycle
      - motorcycle
      - dog
      - cat
environment_vars:
  LIBVA_DRIVER_NAME: i965
```

### Relevant log output

```shell
2024-03-12 08:08:17.918187958  [2024-03-12 09:08:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-12 08:08:21.857012842  [2024-03-12 09:08:21] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-03-12 08:09:44.338630211  172.30.32.2 - - [12/Mar/2024:09:09:44 +0100] "GET / HTTP/1.1" 200 6636 "-" "HomeAssistantSupervisor/2024.02.1 aiohttp/3.9.3 Python/3.12" "-"
2024-03-12 08:11:44.361066428  172.30.32.2 - - [12/Mar/2024:09:11:44 +0100] "GET / HTTP/1.1" 200 6636 "-" "HomeAssistantSupervisor/2024.02.1 aiohttp/3.9.3 Python/3.12" "-"
2024-03-12 08:12:07.935850591  [2024-03-12 09:12:07] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2024-03-12 08:12:07.936148648  [2024-03-12 09:12:07] root                           INFO    : Waiting for detection process to exit gracefully...
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1440
FPS: 20/1

Audio:

Codec: PCM A-law / G.711 A-law



[telecamera cancello] Output #0, mp4, to 'pipe:3':
  Metadata:
    title           : RTSP Session
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 2560x1440, q=2-31, 20 fps, 20 tbr, 90k tbn, 90k tbc
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 64 kb/s
    Metadata:
      encoder         : Lavc58.134.100 aac
frame=    1 fps=0.0 q=-1.0 size=       1kB time=00:00:00.04 bitrate= 207.0kbits/s speed=1.78e+03x    
[aac @ 0x55f533cbb140] Queue input is backward in time


[telecamera cancello] video/audio detected, discarding further input

[telecamera cancello] Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:3':


[telecamera cancello]   Metadata:

[telecamera cancello]     major_brand     : 
[telecamera cancello] iso5
[telecamera cancello] 


[telecamera cancello]     minor_version   : 
[telecamera cancello] 512
[telecamera cancello] 

[telecamera cancello]     compatible_brands: 
[telecamera cancello] iso5iso6mp41

[telecamera cancello] 

[telecamera cancello]     title           : 
[telecamera cancello] RTSP Session
[telecamera cancello]
```

### Frigate stats

```json
How I can get it?


SYSTEM 0.13.2-6476F8A
go2rtc 1.8.4 streams info
Last refreshed: 1m ago

DETECTORS
coral
P-ID	Inference Speed	CPU %	Memory %
5120	58.69 ms	10.6%	4.1%
GPUS
VAINFO
Hardware acceleration has not been setup, see the docs to setup hardware acceleration.
CAMERAS
Cancello
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3231	5.1	35.3%	2.9%
Capture	263	4.9	9.8%	0.8%
Detect	259	5.2 (0.5 skipped)	9.0%	1.8%
OTHER PROCESSES
Logger
P-ID	CPU %	Avg CPU %	Memory %
239	0.0%	0%	0.3%
Recording
P-ID	CPU %	Avg CPU %	Memory %
241	0.1%	0%	0.4%
Go2rtc
P-ID	CPU %	Avg CPU %	Memory %
89	0.0%	0%	0.1%
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

KEVIEW KX400FB-P 4MP using H.264

### Any other information that may be helpful

{"return_code":3,"stderr":"error:XDG_RUNTIME_DIRisinvalidornotsetintheenvironment.nerror:can'tconnecttoXserver!nlibvainfo:VA-APIversion1.17.0nlibvainfo:Userenvironmentvariablerequesteddriver'i965'nlibvainfo:Tryingtoopen/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.sonlibvainfo:Foundinitfunction__vaDriverInit_1_8nDRM_IOCTL_I915_GEM_APERTUREfailed:InvalidargumentnAssuming131072kBavailableaperturesize.nMayleadtoreducedperformanceorincorrectrendering.ngetchipidfailed:-1[22]nparam:4,val:0nlibvaerror:/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.soinitfailednlibvainfo:va_openDriver()returns-1nvaInitializefailedwitherrorcode-1(unknownlibvaerror),exit","stdout":""}

I already tried to add hw accelaration, but I receive always config error...

#      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
#      hwaccel_args: preset-intel-qsv-h265

**Comment by NickM-27** [comment]
your iGPU is not passed in so the driver is not able to load

**Comment by pilot1981** [comment]
> * Intel® HD Graphics 600

so Firgate driver isn't able to use Intel® HD Graphics 600, what do you suggest to do?

how I can get lowest usage of CPU Intel?

Coral TPU isn't useful to it?

**Reply by NickM-27** [reply]
Your understanding is incorrect, frigate works fine with intel gpus. The problem is your VM configuration. 

The dual helps with object detection, not decoding of video.

**Comment by pilot1981** [comment]
so the problem could be Frigate don't see my Intel Graphic 600...

in QNAP hypervisor I found VGA video card configured.

I also can choose:
- VMVGA
- Cirrus
- QXL

in your opinion what I have to use?

**Comment by pilot1981** [comment]
I can try them, but how I can be sure which is the right setting?

**Reply by NickM-27** [reply]
I'm not sure, I don't have much experience with VMs for this very reason

**Comment by pilot1981** [comment]
QNAP support confirmed no solution for now...I created request new feature per QNAP developer...

**Reply by messerffm** [reply]
Hey there,

I have a similar configuration as you. VM with Home Assistant and Frigate Addon. CPU was burning at 70%-90%.

I tried everything the past week to fix this and gave up.

But today I found a workaround!!!

You have to install frigate in container station. You can found the installation description on the frigate site under QNAP. You have to do it by command line (ssh to the qnap).

Now the Intel Hardware Acceleration works like a charm together with coral. No more cpu burning!!

If you want you can connect the frigate container with Mqtt to Home Assistant which works in the VM.

**Reply by pilot1981** [reply]
So, in your opinion frigate in container use less CPU on QNAP than VM with HA ADDON? I can try!

you can share your frigate config?

you have problem of stuck of Coral USB stick on QNAP?

**Reply by messerffm** [reply]
Yes, frigate in a container instead of vm on qnap works like a charm. CPU is on normal range and other VMs are snappy again. 

My frigate config isn’t something special! You have to activate the coral and ffmpeg vaapi for intel hardware acceleration.

Coral works in container without installing a driver.

**Reply by pilot1981** [reply]
Do you used this option?

ffmpeg:
  hwaccel_args: preset-vaapi

do you added also this one?

LIBVA_DRIVER_NAME=i965

which QNAP do you use?

**Reply by messerffm** [reply]
Yes, I used this vaapi setting.

No, LIBVA setting is not necessary.

qnap ts-264

on the installation in command line there is a setting down below (something with gpu) which I set to true

**Reply by thesearge** [reply]
Hello messerffm, I also have problems with my frigate setup running HA OS on virtualization station on Qnap TS-364. Coral TPU is not stable and slows down very often. Running frigate on container station seems to be a good idea, but how can this be integrated in HA running on VM. Could you offer more information?

**Reply by NickM-27** [reply]
The HA integration works the same regardless of where frigate is installed

**Comment by pilot1981** [comment]
Hi,
I have QNAP TS-453D-8G and works fine with LIBVA

I confirm docker of Frigate for QNAP is able to find Intel HID GPU/VAAPI and CPU utilization is very low!!!!! This is a good solution for who have problem with Frigate ADDON on Home Assistant!!!!! I don't know if it's a bug! @blakeblackshear  what do you think about it?

thanks to @messerffm for this suggestion!

regards

**Reply by NickM-27** [reply]
What would the bug be?

**Reply by messerffm** [reply]
You are welcome! :-)

The problem with frigate in a VM is that the GPU passthrough doesn’t work.
I think it’s not a bug! Maybe the software developers from qnap will implement it in future but I think for any reason they don’t.

**Reply by thesearge** [reply]
Also Coral TPU USB works much better with this frigate docker solution. Moreover Coral TPU is also available for other Qnap NAS services. Docker Frigate can be integrated in HAOS VM via Integration and Frigate Proxy-AddOn to gain full control similar to direct integration via frigate Addon.

**Comment by pilot1981** [comment]
I'm waiting 3 months about news from QNAP developer to develop a solution on his virtualization station: they have great project for this feature...almost from the acquire of VMWARE from BROADCOM...

**Comment by messerffm** [comment]
Hey there, you just have to install the frigate integration on HA and set it up with the ip address of your frigate in the container station. Works like a charm since many month. Am 04.10.2024 um 15:52 schrieb thesearge ***@***.***>:﻿
Hello messerffm, I also have problems with my frigate setup running HA OS on virtualization station on Qnap TS-364. Coral TPU is not stable and slows down very often. Running frigate on container station seems to be a good idea, but how can this be integrated in HA running on VM. Could you offer more information?

**Reply by thesearge** [reply]
@messerffm I‘m trying to migrate frigate from HA OS-AddOn installation to docker container installation as described before, but unfortunately I didn’t get my config.yml working. For some reason config can’t use/reach rtsp stream and frigate refuses to work.
![IMG_0531](https://github.com/user-attachments/assets/1a005c6b-6a1b-4129-ac5b-e62745ebfe64). Docker installation is bridged to qnap virtual switch. Streams are running via http due to reolink cams. I think I need more help. This seems to be apart from this topic. I guess you are also german speaking. Can I contact you directly in order to compare configs and network setups?

**Comment by messerffm** [comment]
Hi,ja, ich spreche auch deutsch. ;-)Es ist schon einige Monate her, dass ich das eingerichtet habe.Aber ich bin nach dieser Anleitung vorgegangen.Installationdocs.frigate.videoGanz unten steht wie es beim qnap zu machen ist.Man muss sich per ssh einloggen und dann command line den Container installieren. Glaube in der Zeile mit GPU musst du noch „true“ eintragen statt „false“Musste mal bisschen rumprobieren…Am 06.10.2024 um 08:23 schrieb thesearge ***@***.***>:﻿
@messerffm I‘m trying to migrate frigate from HA OS-AddOn installation to docker container installation as described before, but unfortunately I didn’t get my config.yml working. For some reason config can’t use/reach rtsp stream and frigate refuses to work.
IMG_0531.jpeg (view on web). Docker installation is bridged to qnap virtual switch. I think I need more help. This seems to be apart from this topic. I guess you are also german speaking. Can I contact you directly in order to compare configs and network setups?

**Reply by thesearge** [reply]
Ich hänge leider noch an anderer Stelle. Ich glaube sofort, dass die HW-Beschleunigung im Docker-Setup funktioniert. (GPU —> true und auch Network-Mode —> Bridge). Und auch die Coral-TPU wird vermutlich als Detektor laufen. Ich erreiche aber meine Kameras nicht mehr, obwohl ich die gleiche Config verwende, die bei Frigate als AddOn in HA OS funktioniert. Ich fürchte, dass das etwas spezielle Setup für die Reolink-Cams hier Probleme bereitet und das verstehe ich nicht. Das HA OS in der VM hat die lokale IP 192.xxx.xxx.6. Die Docker-Instanz 192.xxx.xxx.7 und die Qnap TS-364 mit Virtual Switch läuft auf 192.xxx.xxx.5. DHCP läuft über die Fritzbox 192.xxx.xxx.1.
Der stream wird per http auf Port 1935 von den Cams eingesammelt. Port 1935 habe ich auch geöffnet. 
```
go2rtc:
  streams:
    your_reolink_camera:
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"
    your_reolink_camera_sub:
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"

cameras:
  your_reolink_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/your_reolink_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/your_reolink_camera_sub
          input_args: preset-rtsp-restream
          roles:
```
Warum funktioniert es in der VM und nicht im Docker?
