### DISCUSSION TITLE
[Config Support]: help with the "parked car" problem.

### DISCUSSION THREAD

**Discussion by ross-rosario** [blakeblackshear/frigate#10394] [Config Support] [answered]
### Describe the problem you are having

There are multiple config examples in the docs that aim to tackle the repetitive parked car recording, such as "parked cars guide" and "zones" pages. However, coming up with config that is at the intersection of all those examples is a bit confusing (at least to me).

Here's the desired result and I'd appreciate any help with writing config for it.
- Entrance zone: Record/snapshot all events by all objects.
- Parking zone:
  - If object _**is not**_ a car, record/snapshot **all** events.
  - Else If object _**is**_ a car
    - If this this is coming from the **entrance zone**, record/snapshot.
    - **Else**, ignore this event (because presumably that's a parked car).
- Objects (these are the only objects I'm interested in capturing by frigate, regardless of zone or camera):
  - car
  - person
  - dog 

Note that in the parking zone we're still interesting in capturing events raised by non-car objects.

### Version

0.13.2

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
sounds like you want an entrance zone with an object mask where the car parks in the driveway, then a separate zone for the other objects you care about

**Reply by ross-rosario** [reply]
If I understand correctly, "object masks" are used to avoid false positives, is that correct? I have no false positives to remove, it's a proper positive (parked car) but very repetitive and annoying.

Here's an extremely simplified explanation of the desired config:

- Street zone, capture everything
- Parking zone, still capture everything MINUS the car that's been stationary forever.

I don't believe any of the frigate examples tackle that, and honestly, with the so many overlapping config options, writing this is complicated.

I would appreciate a config snippet here.

**Reply by ross-rosario** [reply]
Actually I might be muddying the problem statement by mentioning zones. I'm not even sure I need zones.

All needed is: if a car is stationary, please frigate, stop showing me endless events about this parked car, or whatever stationary object that might be.

**Reply by NickM-27** [reply]
object masks are used to force frigate to ignore an object that is detected in that area. Typically this is recommended to only be used for false positives (and as a last resort) but this is the only way to ensure a car is not detected while it is in view of your camera.

as it says in the docs, we have plans to improve parked car handling in future versions so this is not necessary. 

```
cameras:
  driveway_cam:
    objects:
      filters:
        car:
          mask: 
            - 1452,0,1218,0,1230,147,1462,154 # <- mask on bottom center of parked car
    zones:
      street:
        coordinates: 2560,720,2560,531,2010,326,1296,313,1309,498,579,479,450,550,94,720
    record:
      events:
        required_zones:
          - street
    snapshots:
      required_zones:
        - street
```
