### DISCUSSION TITLE
[Config Support]: Cannot use my camera with frigate. What am I doing wrong?

### DISCUSSION THREAD

**Discussion by fuuman** [blakeblackshear/frigate#10400] [Config Support] [answered]
### Describe the problem you are having

I am not able to get a simple camera with Frigate to work. In the camera overview I just get an dark frame with the message "No frames have been received, check error logs". The logfiles tells me that there is a problem with ffmpeg (`Unable to read frames from ffmpeg process.` and `ffmpeg process is not running. exiting capture thread...`), but when I exec into the container, there is ffmpeg and I can use it. The RTSP-URL I am using in my frigate config is working in a VLC player without any issues,

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  mycam:
    ffmpeg:
      inputs:
        - path: rtsp://myuser:mypassword123@x.x.x.x:554/onvif1
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 7
          mode: motion
```

### Relevant log output

```shell
2024-03-12 14:54:34.102155714  [INFO] Preparing Frigate...
2024-03-12 14:54:34.138749812  [INFO] Starting Frigate...
2024-03-12 14:54:35.681682215  [2024-03-12 14:54:35] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-12 14:54:35.807712140  [rtsp @ 0x377a8c0] Nonmatching transport in server reply
2024-03-12 14:54:35.850510536  [2024-03-12 14:54:35] peewee_migrate.logs            INFO    : Starting migrations
2024-03-12 14:54:35.854880572  [2024-03-12 14:54:35] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-12 14:54:35.858867036  [2024-03-12 14:54:35] frigate.app                    INFO    : Recording process started: 298
2024-03-12 14:54:35.861405594  [2024-03-12 14:54:35] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-12 14:54:35.880338742  [2024-03-12 14:54:35] detector.cpu                   INFO    : Starting detection process: 307
2024-03-12 14:54:35.886502928  [2024-03-12 14:54:35] frigate.app                    INFO    : Output process started: 309
2024-03-12 14:54:35.886820112  [2024-03-12 14:54:35] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-03-12 14:54:35.894832373  [2024-03-12 14:54:35] frigate.app                    INFO    : Camera processor started for mycam: 313
2024-03-12 14:54:35.900188663  [2024-03-12 14:54:35] frigate.app                    INFO    : Capture process started for mycam: 314
2024-03-12 14:54:36.416756026  [2024-03-12 14:54:36] frigate.video                  ERROR   : mycam: Unable to read frames from ffmpeg process.
2024-03-12 14:54:36.417132841  [2024-03-12 14:54:36] frigate.video                  ERROR   : mycam: ffmpeg process is not running. exiting capture thread...
```

### Frigate stats

```json
// 20240312145602
// https://frigate.mydomain.com/api/stats

{
  "cameras": {
    "mycam": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 0.0,
      "capture_pid": 312,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 347,
      "pid": 310,
      "process_fps": 0.0,
      "skipped_fps": 0.0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "104": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "107": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.7",
      "cpu_average": "4",
      "mem": "1.1"
    },
    "116": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "144": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "145": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "148": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "157": {
      "cmdline": "nginx: cache loader process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "293": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "295": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "303": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(38)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "304": {
      "cmdline": "frigate.detector.cpu ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "306": {
      "cmdline": "frigate.output       ",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "310": {
      "cmdline": "frigate.process:mycam",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "311": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "312": {
      "cmdline": "frigate.capture:mycam",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "317": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "335": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0.0,
  "detectors": {
    "cpu": {
      "detection_start": 0.0,
      "inference_speed": 10.0,
      "pid": 304
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 293
    },
    "recording": {
      "pid": 295
    }
  },
  "service": {
    "last_updated": 1710251764,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 95.5,
        "mount_type": "tmpfs",
        "total": 96.0,
        "used": 0.5
      },
      "/media/frigate/clips": {
        "free": 139418.9,
        "mount_type": "ext4",
        "total": 221691.4,
        "used": 72179.8
      },
      "/media/frigate/recordings": {
        "free": 139418.9,
        "mount_type": "ext4",
        "total": 221691.4,
        "used": 72179.8
      },
      "/tmp/cache": {
        "free": 953.7,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 0.0
      }
    },
    "temperatures": {
      
    },
    "uptime": 22,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

My `compose.yaml`:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "96mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config.yml:/config/config.yml
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "mypassword123456"
```

My `ffprobe` output for that cam:
```
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x960
FPS: 15/1

Audio:

Codec: PCM A-law / G.711 A-law
```

The codec information for my camera I receive from VLC player:
```
Codec: H264 - MPEG-4 AVC (part 10) (h264)
Typ: Video
Videoauflösung: 1280x960
Pufferabmessungen: 1280x960
Bildwiederholrate: 15
```
