### DISCUSSION TITLE
[HW Accel Support]: CPU and GPU extremely high on 0.13.2

### DISCUSSION THREAD

**Discussion by kajer** [blakeblackshear/frigate#10412] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I attempted to update Frigate from .12.1 to .13.2 after updating nvidia drivers to 535-server from 525-server
GPU use on .13.2 sticks around 95% for 11 cameras and even when limited to 2 cameras, while .12.1 stayed about 30% detecting on all 11 cameras at full primary stream resolution.

I have flapped between .13.2 and .12.1 and can repeat the results.  .13.2 pegs my GPU and CPUs and causes the server to go 90+ PWM on fans to keep the Tesla P4 cool, while running .12.1 keeps the GPU cool and server PWM fans ~20%

Changing detectors to sub streams do not change GPU use, it's at 100% for 2 cameras or 11 cameras on 640x480 sub streams.  While this limits ram use from 4GB down to ~1.6GB, this causes 100% gpu load and high temperatures. 

Screenshot of a final roll-back to .12.1 showing gpu use ~average at 25%

![image](https://github.com/blakeblackshear/frigate/assets/6497680/5cd5d151-cb3a-4229-9c5c-a25038c3d39c)

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: $homeassistantIP
  user: $user
  password: $password

database:
  path: /db/frigate.db

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -use_wallclock_as_timestamps 1
  hwaccel_args: preset-nvidia-h264

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 16
  restream: true

go2rtc:
  streams:
    camera01: # <- for RTSP streams
      - rtsp://user:pass@IP:554/Streaming/Channels/1
...
    camera11: # <- for RTSP streams
      - "ffmpeg:rtsp://user:pass@IP:554/Streaming/Channels/1#video=h264#audio=aac"
  webrtc:
    listen: ":8555"
    candidates:
      - fqdn:8555

cameras:
  camera01:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/camera01
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True

... #(all cameras configured the same)

detect:
  fps: 5
record:
   enabled: True
   retain:
     days: 21
     mode: motion
   events:
     pre_capture: 5
     post_capture: 5
     retain:
       objects:
         person: 31
         car: 31

objects:
  track:
    - person
    - cat
    - car
    - dog
    - bird
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7


snapshots:
   enabled: True
   timestamp: False
   bounding_box: True
   crop: False
   retain:
     default: 21
     objects:
       person: 60

detectors:
  tensorrt:
    type: tensorrt

model:
#  path: /trt-models/yolov7-tiny-416.trt
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
#  width: 416
#  height: 416
  width: 320
  height: 320

rtmp:
  enabled: False
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    environment:
    - YOLO_MODELS=yolov4-608,yolov7x-640
    - USE_FP16=false
    container_name: frigate-rt
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
#    image: ghcr.io/blakeblackshear/frigate:0.12.1-tensorrt
    shm_size: 2gb
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/kajer/docker/frigate-rt/db:/db
      - /home/kajer/docker/frigate-rt/config/:/config/
      - /home/kajer/docker/frigate-rt/trt-models:/trt-models
      - /CamStore:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

trendnet/generic rtsp

**Comment by NickM-27** [comment]
this is most likely due to motion detection being more sensitive, I'd suggest tuning motion detection

**Reply by kajer** [reply]
I would agree with motion detection, but the 1 camera used for testing is an indoor static shot.  GPU use should not be at 100% for a single camera with no motion boxes showing in the debug pane.

**Reply by NickM-27** [reply]
Well, if motion detection is too sensitive it could be that. Without screenshots of the system page running 0.13 there's no way to know what's going on.

**Reply by kajer** [reply]
![image](https://github.com/blakeblackshear/frigate/assets/6497680/675e037c-388f-4f6c-9406-ed194af4c091)

I trimmed the camera config from 11 down to two to get under 90%  one is an indoor camera, mostly static, the other is outdoor, and 4K.

I will need to point the detector at the substream to get any lower GPU use.   These are the same streams as 12.1, but 12.1 could handle all 11 cams at 25% gpu use

**Reply by NickM-27** [reply]
This is definitely a motion detection issue. We can see camera02 is running 32 detections per second. 

https://docs.frigate.video/configuration/motion_detection

**Reply by kajer** [reply]
Okay, so the global detect variable is 5 as seen in the config, what happened between 12 and 13 that this is now a problem?
That being said...
When I last revamped the config to use substreams for detect, I manually set all 11 ip cameras to output either 5 or 6fps at "vga" resolution on h264.   When I had all 11 set to 5pfs output, and used substream detectors, GPU use was still over 95%

**Reply by NickM-27** [reply]
detect fps of 5 means 5 frames per second, but object detection occurs on regions (portions of the image) so multiple can happen for each frame. 

Like the release notes said, motion detection was made more sensitive and some users need to adjust the sensitivity which is exactly what the above link walks through

**Reply by kajer** [reply]
Added `motion` section with the following values:
```
motion:
  threshold: 50
  lightning_threshold: 0.8
  contour_area: 30
```

I'm up to 4/11 cameras added back to the 13.2 config with GPU ~20%

I will let this run for a bit and continue to add more over the day.

![image](https://github.com/blakeblackshear/frigate/assets/6497680/4df35868-1b86-47b9-8cb7-f90e5477b49a)

**Reply by kajer** [reply]
I am having trouble getting a balance between detection and GPU saturation.

![image](https://github.com/blakeblackshear/frigate/assets/6497680/8114d463-93f8-4c1b-8a47-5b3b50bb6cdf)

Motion events are being captured and seen, but detection is not happening.  I walk around on one camera, and I can hear server workload from the garage (40MM fans and GPU temps)

If I tune detection to be any more sensitive, the GPU saturates.   This was never the case when using 12.1 and detecting on the full resolution of the primary stream.   I have tried various model sets, and they all peg the GPU at full if I want usable object detection in 13.2

**Reply by NickM-27** [reply]
what GPU are you using?

**Reply by kajer** [reply]
Tesla P4, the same as the above comments and screenshots referenced.

**Reply by kajer** [reply]
Detection can't hold a steady object when I went outside and walked around.  It was detecting me as a person in a very specific pose, and very off/on.  Me standing still for a minute generated ~20 video clips as detection kept thinking I was a new object.  I was watching the debug as that was happening. 

Current detection settings:
```
motion:
  threshold: 35
  lightning_threshold: 0.8
  contour_area: 20
  
  model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

Any lower and I'll be back to defaults, which cause 100% gpu use 100% of the time.  As it is now, I get lower GPU use than the initial migration to 13.2, but the slightest bit of wind and it's all over.  Even just walking around on one camera is already too much for the GPU when using 13.2

I have a few Quadro RTX 5000 I can probably throw at this, but I really was trying to keep frigate quiet and low wattage, which 12.1 does wonderfully.


![image](https://github.com/blakeblackshear/frigate/assets/6497680/585d0e6f-f153-4e79-900c-36a1848493af)
