### DISCUSSION TITLE
[Config Support]: Yet another ongoing parked car.

### DISCUSSION THREAD

**Discussion by mcozzo** [blakeblackshear/frigate#10426] [Config Support] [answered]
### Describe the problem you are having

"Main Door" camera has zones for driveway and parking. I get an ongoing event for a car, even though I've limited the objects to dog, person in both of those zones. I'm sure it's something simple but I believe I have everything setup as the documentation recommends. 

Also, amazing software. I love where this is going. 

![Screenshot 2024-03-13 at 7 54 02 AM](https://github.com/blakeblackshear/frigate/assets/12915569/26606338-8db4-4c05-be44-7a1af29d7c77)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
#######################################################################################################
# Configure Go2RTC first.
# This makes the initial connection to the camera. Frigate then connects to the RTC stream to do work
#######################################################################################################
go2rtc:
  streams:
    Main_Door:
      - rtsp://10.21.7.100:554/Streaming/Channels/101
    Main_Door_sub:
      - rtsp://10.21.7.100:554/Streaming/Channels/102?video&audio
    Driveway:
      - rtsp://10.21.7.101:554/Streaming/Channels/101
    Driveway_sub:
      - rtsp://10.21.7.101:554/Streaming/Channels/102?video&audio
    Camera_1:
      - rtsp://10.21.7.102:554/Streaming/Channels/101
    Camera_1_sub:
      - rtsp://10.21.7.102:554/Streaming/Channels/102?video&audio
    Camera_2:
      - rtsp://10.21.7.103:554/Streaming/Channels/101
    Camera_2_sub:
      - rtsp://10.21.7.103:554/Streaming/Channels/102?video&audio
  webrtc:
    candidates:
      - docker05.camp.cozzo.net:8555
      - stun:8555

#######################################################################################################
# Individual camera settings
######################################################################################################
cameras:
######################################################################################################
  Main_Door:
    enabled: true
    audio:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      #events:
      #  required_zones:
      #  - Zone_Driveway
    ui:
      order: 1
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://10.21.2.15:8554/Main_Door
          roles:
            - record
            - audio
        - path: rtsp://10.21.2.15:8554/Main_Door_sub
          roles:
            - detect
    live:
      stream_name: Main_Door_sub
    zones:
      Zone_Parking_Garage:
        coordinates: 0,720,1280,720,1280,356,735,0,0,0
        objects:
          - person
          - dog
      Zone_Driveway:
        coordinates: 1280,347,1280,0,711,0
        objects:
          - person
          - dog
######################################################################################################
  Driveway:
    enabled: true
    audio:
      enabled: false
    detect:
      enabled: true
    record:
      enabled: true
      events:
        required_zones:
          - Zone_Driveway
    ui:
      order: 0
    birdseye:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://10.21.2.15:8554/Driveway
          roles:
            - record
        - path: rtsp://10.21.2.15:8554/Driveway_sub
          roles:
            - detect
    live:
      stream_name: Driveway_sub
    motion:
      mask:
        - 903,98,902,137,317,165,306,134 #Kent Black Diamond
    zones:
      Zone_Driveway:
        coordinates: 594,186,365,254,178,308,313,409,910,185,907,130,768,146
      Zone_Parking_Garage:
        coordinates: 0,720,0,259,161,261,285,417,869,191,1280,268,1280,720
      Zone_Parking_Tree:
        coordinates: 482,132,496,239,304,263,286,143
######################################################################################################
  Camera_1:
    enabled: true
    audio:
      enabled: false
    detect:
      enabled: false
    record:
      enabled: true
    ui:
      order: 2
    birdseye:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://10.21.2.15:8554/Camera_1
          roles:
          - record
          - audio
        - path: rtsp://10.21.2.15:8554/Camera_1_sub
          roles:
          - detect
    live:
      stream_name: Camera_1_sub
######################################################################################################
  Camera_2:
    enabled: true
    audio:
      enabled: false
    detect:
      enabled: false
    record:
      enabled: true
    ui:
      order: 3
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://10.21.2.15:8554/Camera_2
          roles:
          - record
        - path: rtsp://10.21.2.15:8554/Camera_2_sub
          roles:
          - detect
    live:
      stream_name: Camera_2_sub

#######################################################################################################
# Global recorder settings
######################################################################################################
record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    objects:
      - person
      - car
      - dog
    retain:
      default: 30
      mode: motion
      #mode: active_objects

#######################################################################################################
# Global Object tracking 
######################################################################################################
objects:
  track:
    - person
    - car
    - dog
    - bird
    - bicycle
    - motorcycle
    - skis
    - snowboard
  #mask: 0,0,1000,0,1000,200,0,200
  filters:
    person:
      min_score: 0.5
      #threshold: 0.7
    car:
      min_score: 0.5
      #threshold: 0.7

#######################################################################################################
# Global motion settings
######################################################################################################
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 35
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30

#######################################################################################################
# Web UI settings
######################################################################################################
ui:
  live_mode: mse
  timezone: America/Los_Angeles
  use_experimental: false
  time_format: 24hour
  date_style: long
  time_style: medium

birdseye:
  enabled: true
  mode: motion

#######################################################################################################
# MQTT, obviously
######################################################################################################
mqtt:
  enabled: true
  #host: mosquitomqtt.camp.cozzo.net
  host: 10.21.2.15
  port: 1883
  topic_prefix: camp-frigate
  client_id: camp-frigate-client
  user: frigate
  password: password

#######################################################################################################
# General settings
#######################################################################################################
audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detect:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264
```

### Relevant log output

```shell
2024-03-13 07:47:35.868316899  [INFO] Preparing Frigate...
2024-03-13 07:47:35.886510418  [INFO] Starting Frigate...
2024-03-13 07:47:36.652418341  [2024-03-13 07:47:36] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-13 07:47:53.335853839  [2024-03-13 07:47:53] peewee_migrate.logs            INFO    : Starting migrations
2024-03-13 07:47:53.377211099  [2024-03-13 07:47:53] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-13 07:47:53.384221878  [2024-03-13 07:47:53] frigate.app                    INFO    : Recording process started: 949
2024-03-13 07:47:53.385747685  [2024-03-13 07:47:53] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-13 07:47:53.398748897  [2024-03-13 07:47:53] detector.coral                 INFO    : Starting detection process: 959
2024-03-13 07:47:56.590429823  [2024-03-13 07:47:53] frigate.app                    INFO    : Output process started: 961
2024-03-13 07:47:56.600400710  [2024-03-13 07:47:53] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-13 07:47:56.601369822  [2024-03-13 07:47:53] frigate.app                    INFO    : Camera processor started for Main_Door: 984
2024-03-13 07:47:56.601454268  [2024-03-13 07:47:53] frigate.app                    INFO    : Camera processor started for Driveway: 985
2024-03-13 07:47:56.601776967  [2024-03-13 07:47:56] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-03-13 07:47:56.601901874  [2024-03-13 07:47:53] frigate.app                    INFO    : Camera processor started for Camera_1: 987
2024-03-13 07:47:56.601999820  [2024-03-13 07:47:53] frigate.app                    INFO    : Camera processor started for Camera_2: 989
2024-03-13 07:47:56.602081598  [2024-03-13 07:47:53] frigate.app                    INFO    : Capture process started for Main_Door: 991
2024-03-13 07:47:56.602149063  [2024-03-13 07:47:53] frigate.app                    INFO    : Capture process started for Driveway: 995
2024-03-13 07:47:56.602212660  [2024-03-13 07:47:53] frigate.app                    INFO    : Capture process started for Camera_1: 999
2024-03-13 07:47:56.602276741  [2024-03-13 07:47:53] frigate.app                    INFO    : Capture process started for Camera_2: 1002
2024-03-13 07:47:56.602337767  [2024-03-13 07:47:53] frigate.app                    INFO    : Audio process started: 1009
```

### Frigate stats

```json
{"cameras":{"Camera_1":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":999,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":1008,"pid":987,"process_fps":5.1,"skipped_fps":0.0},"Camera_2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":1002,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":1014,"pid":989,"process_fps":5.1,"skipped_fps":0.0},"Driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":995,"detection_enabled":1,"detection_fps":6.3,"ffmpeg_pid":1000,"pid":985,"process_fps":5.1,"skipped_fps":0.0},"Main_Door":{"audio_dBFS":-36.649,"audio_rms":481.9452,"camera_fps":5.1,"capture_pid":991,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":997,"pid":984,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"40":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"43":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"13.2","cpu_average":"11","mem":"0.1"},"97":{"cmdline":"python3 -u -m frigate","cpu":"4.7","cpu_average":"6","mem":"0.8"},"98":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"114":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"153":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"173":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"211":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"255":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"301":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"331":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"362":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"392":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"422":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"458":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"491":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"524":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"569":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"596":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"633":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"664":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"870":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"949":{"cmdline":"frigate.recording_manager","cpu":"3.5","cpu_average":"2","mem":"0.4"},"958":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(55)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"959":{"cmdline":"frigate.detector.coral","cpu":"10.8","cpu_average":"14","mem":"0.4"},"961":{"cmdline":"frigate.output       ","cpu":"1.4","cpu_average":"1","mem":"0.4"},"967":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"968":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"969":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"970":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"971":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"984":{"cmdline":"frigate.process:Main_Door","cpu":"2.7","cpu_average":"5","mem":"0.4"},"985":{"cmdline":"frigate.process:Driveway","cpu":"15.7","cpu_average":"17","mem":"0.5"},"987":{"cmdline":"frigate.process:Camera_1","cpu":"1.6","cpu_average":"1","mem":"0.4"},"989":{"cmdline":"frigate.process:Camera_2","cpu":"1.8","cpu_average":"1","mem":"0.4"},"991":{"cmdline":"frigate.capture:Main_Door","cpu":"1.8","cpu_average":"1","mem":"0.4"},"995":{"cmdline":"frigate.capture:Driveway","cpu":"1.8","cpu_average":"1","mem":"0.4"},"997":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Main_Door_sub -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.6","cpu_average":"1","mem":"0.2"},"999":{"cmdline":"frigate.capture:Camera_1","cpu":"1.7","cpu_average":"1","mem":"0.4"},"1000":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Driveway_sub -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.7","cpu_average":"2","mem":"0.2"},"1002":{"cmdline":"frigate.capture:Camera_2","cpu":"1.7","cpu_average":"1","mem":"0.4"},"1008":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Camera_1_sub -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.6","cpu_average":"1","mem":"0.2"},"1009":{"cmdline":"frigate.audio_manager","cpu":"1.3","cpu_average":"1","mem":"0.4"},"1010":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Main_Door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Main_Door@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.1"},"1014":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Camera_2_sub -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.4","cpu_average":"1","mem":"0.2"},"1016":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Driveway@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"0","mem":"0.1"},"1022":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Camera_1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Camera_1@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.1"},"1023":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Camera_2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Camera_2@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"0","mem":"0.1"},"1024":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.21.2.15:8554/Main_Door -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.7","cpu_average":"0","mem":"0.1"},"3149":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":6.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":27.63,"pid":959}},"gpu_usages":{"intel-qsv":{"gpu":"1.13%","mem":"-%"}},"processes":{"audioDetector":{"pid":1009},"go2rtc":{"pid":89},"logger":{"pid":870},"recording":{"pid":949}},"service":{"last_updated":1710341447,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":301.5,"mount_type":"tmpfs","total":310.0,"used":8.5},"/media/frigate/clips":{"free":411969.4,"mount_type":"nfs","total":983040.0,"used":571070.6},"/media/frigate/recordings":{"free":411969.4,"mount_type":"nfs","total":983040.0,"used":571070.6},"/tmp/cache":{"free":924.1,"mount_type":"tmpfs","total":953.7,"used":29.5}},"temperatures":{},"uptime":174,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
