### DISCUSSION TITLE
[Config Support]: Turn off person recording/events without turning off person detection in Home Assistant

### DISCUSSION THREAD

**Discussion by clowncracker** [blakeblackshear/frigate#10489] [Config Support] [answered]
### Describe the problem you are having

Is it possible to set up the config to turn off person recording/events but still allow person detection in Home Assistant?  I basically want my 'office' camera to record 24/7 and to record audio events.  I was trying to figure out a way to turn off person recordings/events in Frigate without it turning off person detection in Home Assistant.  When I set detect to false, person counts weren't being updated in Home Assistant.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: xxxxx
  user: xxxxx
  password: xxxxx

go2rtc:
  streams:
    front_door:
      - "ffmpeg:http://xxx.xxx.x.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy#audio=opus"
      - rtsp://http://xxx.xxx.x.xxx/Preview_01_sub
    garage:
      - "ffmpeg:http://xxx.xxx.x.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy#audio=opus"
    office:
      - "ffmpeg:http://192.168.1.251/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy#audio=opus"

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front_door: 
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
      required_zones:
        - entryway
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 438,916,469,598,556,260,656,0,922,0,1051,286,1028,669,1021,976,1023,1077,997,1111,924,1108,823,1103,611,1091,439,1082
            - 1151,1070,1171,1115,1271,1115,1480,1110,1768,1106,2115,1081,2301,1054,2299,872,2277,689,2236,522,2134,528,1897,471,1516,423,1156,426
        car:
          mask:
            - 438,916,469,598,556,260,656,0,922,0,1051,286,1028,669,1021,976,1023,1077,997,1111,924,1108,823,1103,611,1091,439,1082
            - 1151,1070,1171,1115,1271,1115,1480,1110,1768,1106,2115,1081,2301,1054,2299,872,2277,689,2236,522,2134,528,1897,471,1516,423,1156,426
    snapshots:
      enabled: true
    zones:
      entryway:
        coordinates: 2560,1920,2560,1681,2173,1506,1928,1579,1593,1321,930,1404,475,1307,321,1319,0,1319,0,1920
  garage: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,0,2560,0,2560,353,963,383,486,431,0,529
            - 216,1920,906,1920,627,978,268,1022,165,1617,160,1767
    snapshots:
      enabled: true
  office: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/office?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - record
    audio:
      enabled: true
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 465,237,173,300,292,945,549,908
    snapshots:
      enabled: true
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

**Comment by nwish** [comment]
I haven’t tried it, but maybe:

```
record:
  events:
    retain:
      objects:
        person: 0
```

**Reply by NickM-27** [reply, marked as answer]
you could actually do this so the event never gets created

```
record:
  events:
    objects: []
```

**Reply by nwish** [reply]
Ahhh, that’s good to know!!

**Reply by clowncracker** [reply]
That didn't end up working, it still created the event.  I updated the config to:

```
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        objects: []
```
