### DISCUSSION TITLE
[HW Accel Support]:

### DISCUSSION THREAD

**Discussion by gcardy** [blakeblackshear/frigate#10487] [Hardware Acceleration Support]
### Describe the problem you are having

I have configured hardware acceleration, but I am seeing  CPU utilization and next to no GPU utilization on my  system. I thought that hardware acceleration would offload the ffmpeg load onto the GPU. Am I misunderstanding something?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  user: mqttuser
  password: xxxxxxx

detectors:
  coral1:
    type: edgetpu
    device: pci:0

record:
  enabled: true
  retain:
    days: 7
  events:
    retain:
      default: 45

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

timestamp_style:
  format: '%Y-%m-%d %H:%M:%S'

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    driveway_high_res:
    - rtsp://xxx:xxx@192.168.5.54/cam/realmonitor?channel=1&subtype=0&authbasic=64

cameras:
  driveway:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/driveway_high_res
        roles:
        - record
        - detect
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate.geonkins.net:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    runtime: nvidia
    shm_size: "750mb"
    networks:
      net:
        ipv4_address: 192.168.0.195
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/vol01/frigate/storage:/media/frigate'
      - '/vol01/frigate/config:/config'
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
      FRIGATE_RTSP_PASSWORD: "xxxxxxxxxxxx"
networks:
  net:
    name: net
    external: true
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
version 5.1.4-0+deb12u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55ed7a150700] max delay reached. need to consume packet
[rtsp @ 0x55ed7a150700] RTP: missed 35 packets
Input #0, rtsp, from 'rtsp://x:x@192.168.5.54':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 30 fps, 100 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 64000 Hz, mono, fltp

```
```


### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2599EW 

### Any other information that may be helpful

I know that I have detection setup on a high-res stream, and that is resource intensive, but I would expect ffmpeg to use some GPU resources and not CPU exclusively. ```
