### DISCUSSION TITLE
[Support]: Amcrest 5MP Turret POE Camera IP5M-T1179EW Memory leak

### DISCUSSION THREAD

**Discussion by johnvpr** [blakeblackshear/frigate#10515] [General Support]
### Describe the problem you are having

I have 4 Amcrest T1179EW POE cameras I see the memory go up to the limit.

<img width="1540" alt="image" src="https://github.com/blakeblackshear/frigate/assets/5040419/c216f26e-4ef1-44d1-a942-f68914f3a539">

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: 192.168.20.6
  user: mqttuser
  password: XXXXXX

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous    

go2rtc:
  streams:
    Garage1:
        - rtsp://admin:XXXXX@192.168.20.203:554/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Backyard#avoid_negative_ts=make_zero"
    Garage1-sub:
        - rtsp://admin:XXXX@192.168.20.203:554/cam/realmonitor?channel=1&subtype=1
        - "ffmpeg:Backyard-sub#avoid_negative_ts=make_zero"

    Garage2:
        - rtsp://admin:XXXX@192.168.20.204:554/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Backyard#avoid_negative_ts=make_zero"
    Garage2-sub:
        - rtsp://admin:XXXX@192.168.20.204:554/cam/realmonitor?channel=1&subtype=1
        - "ffmpeg:Backyard-sub#avoid_negative_ts=make_zero"

    Garden1:
        - rtsp://admin:XXXXX@192.168.20.205:554/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Backyard#avoid_negative_ts=make_zero"
    Garden1-sub:
        - rtsp://admin:XXXX@192.168.20.205:554/cam/realmonitor?channel=1&subtype=1
        - "ffmpeg:Backyard-sub#avoid_negative_ts=make_zero"

    Garden2:
        - rtsp://admin:XXXX@192.168.20.206:554/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Backyard#avoid_negative_ts=make_zero"
    Garden2-sub:
        - rtsp://admin:XXXX@192.168.20.206:554/cam/realmonitor?channel=1&subtype=1
        - "ffmpeg:Backyard-sub#avoid_negative_ts=make_zero"        
     
cameras:
 

  Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/Garage1-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
    record:
      enabled: True
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 704
      height: 480
      fps: 10
        
    motion:
      mask:
          - 357,85,704,130,704,480,332,480,0,480,0,230
   
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      height: 480
      retain:
        default: 10
        objects:
          person: 10
            #audio:
            #enabled: true # <- enable audio events for the this camera
 

  Garage2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage2
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/Garage2-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
    record:
      enabled: True
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 704
      height: 480
      fps: 10

    
    motion:
      mask:
        - 704,480,704,281,191,206,0,184,0,480
 
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      height: 480
      retain:
        default: 10
        objects:
          person: 15
  


  Garden1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/Garden1-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
    record:
      enabled: True
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 704
      height: 480
      fps: 10


     motion:
      mask:
        - 287,132,704,201,704,0,377,0,279,0,0,0,0,163            
 
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      height: 480
      retain:
        default: 10
        objects:
          person: 10



  Garden2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden2
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/Garden2-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
    record:
      enabled: True
      events:
        retain:
          default: 14
          mode: active_objects
    detect:
      width: 704
      height: 480
      fps: 10


     motion:
        mask:
          - 477,106,621,116,610,270,704,297,704,0,0,0,0,151            
 
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      height: 480
      retain:
        default: 10
        objects:
          person: 15



 
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: False
  retain:
    default: 10

objects:
  track:
    - person
    - dog
    - cat
    - package
    - mouse
        



-------------------------------
Docker compose:
-------------------------------

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    mem_limit: "3g"   
    image: ghcr.io/blakeblackshear/frigate:stable

    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml 
      - /home/frigate/config:/config 
      - /media/frigate:/media/frigate
      - /home/media:/media/frigate
      
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
          
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Birdseye In v 0.12
      

    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sI", "/api/stats"]
      interval: 30s
      timeout: 1s
      retries: 10  
    environment:
      FRIGATE_RTSP_PASSWORD: XXXXX
```

### Relevant log output

```shell
2024-03-17 09:19:32.179162390  [INFO] Preparing Frigate...
2024-03-17 09:19:32.192442927  [INFO] Starting Frigate...
2024-03-17 09:19:33.555614245  [2024-03-17 09:19:33] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-17 09:19:33.637982992  [2024-03-17 09:19:33] peewee_migrate.logs            INFO    : Starting migrations
2024-03-17 09:19:33.642355586  [2024-03-17 09:19:33] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-17 09:19:33.647043615  [2024-03-17 09:19:33] frigate.app                    INFO    : Recording process started: 297
2024-03-17 09:19:33.649551004  [2024-03-17 09:19:33] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-17 09:19:33.670813976  [2024-03-17 09:19:33] frigate.app                    INFO    : Output process started: 309
2024-03-17 09:19:33.684368370  [2024-03-17 09:19:33] frigate.app                    INFO    : Camera processor started for Garage1: 317
2024-03-17 09:19:33.707095827  [2024-03-17 09:19:33] frigate.app                    INFO    : Camera processor started for Garage2: 318
2024-03-17 09:19:33.707100262  [2024-03-17 09:19:33] frigate.app                    INFO    : Camera processor started for Garden1: 322
2024-03-17 09:19:33.708565192  [2024-03-17 09:19:33] frigate.app                    INFO    : Camera processor started for Garden2: 325
2024-03-17 09:19:33.713399900  [2024-03-17 09:19:33] frigate.app                    INFO    : Capture process started for Garage1: 326
2024-03-17 09:19:33.729563611  [2024-03-17 09:19:33] frigate.app                    INFO    : Capture process started for Garage2: 328
2024-03-17 09:19:33.730346508  [2024-03-17 09:19:33] frigate.app                    INFO    : Capture process started for Garden1: 336
2024-03-17 09:19:33.744522647  [2024-03-17 09:19:33] frigate.app                    INFO    : Capture process started for Garden2: 339
2024-03-17 09:19:36.292394567  [2024-03-17 09:19:33] detector.coral                 INFO    : Starting detection process: 307
2024-03-17 09:19:36.302978983  [2024-03-17 09:19:33] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-17 09:19:36.303447229  [2024-03-17 09:19:36] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest T1179EW
