### DISCUSSION TITLE
active_objects function doesn't work

### DISCUSSION THREAD

**Discussion by PeteDenmark** [blakeblackshear/frigate#10519] [Config Support]
### Describe the problem you are having

Hello.

I get really long events with parked cars. I have made an object mask in my carport, so me and my wife's car doesn't trigger events, but every time we have visitors, that park on our property, Frigate just makes on looooooong event with an equally long recording, even with active_objects as the record mode
          
I have read through the "parked car" documentation, and i thought that the active_objects was supposed to stop the looooong event recording behaviour, but if i have guests for 5 hour, i get a 5 hour car event, and a 5 hour recording.

I know i can make zones, but that behaviour would limit other functionality, like triggering outside lights with a Frigate event, when i back out of my carport.

How can i get the behaviour, that i only get an event when the object is actually moving, and only get a recording when the object is actually moving. The event keeps going even when there is no motion in the frame, which i can se from the "motion" entity.

I only want clips recorded - i don't want hours of video :)

### Version

0.13.2

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.8.250
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: **********
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  terrasse1:
    enabled: true
    ffmpeg:
      inputs:
      - path:
          rtsp://192.168.8.201:554/12
        roles:
          - detect
      - path:
          rtsp://192.168.8.201:554/11
        roles:
          - record
          
    detect:
      enabled: true
      width: 640
      height: 352
      fps: 5

    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 5
          mode: active_objects

    snapshots:
      enabled: true
      retain:
        default: 14
        mode: active_objects
      

          
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.75


    motion:
      mask:
        - 0,338,157,336,155,318,0,318
        - 0,0,0,58,69,49,192,41,284,49,338,49,397,54,459,77,534,109,545,146,640,199,640,0


  dahuafrigate: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://192.168.8.231:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif       # <----- The stream you want to use for detection
        roles:
          - detect
          - record
    record:
      enabled: true
      retain:
        days: 0 # <---- Hvor mange dages continuerlig optagelse
        mode: active_objects
      events:
        retain:
          default: 5
          mode: active_objects

    snapshots:
      enabled: true
      retain:
        default: 14
        mode: active_objects

    detect:
      enabled: true
      width: 1920 # <----- 75% af original størrelse
      height: 1080 # <----- 75% af original størrelse
      fps: 5 # <--- denne manglede

    objects:
      track:
      - person
      - car

      filters:
        person:
          threshold: 0.73
          mask:
          - 548,1080,531,989,504,909,390,903,356,978,393,1080
        car:
          mask:
          - 1364,213,1830,230,1838,398,1373,499,1099,346,1065,160
    motion:
      mask:
        - 525,982,526,1033,24,1039,21,980 # <--- motion mask ur
        - 0,0,1920,0,1920,222,1368,230,1075,176,1071,225,712,264,481,290,431,236,278,245,165,258,61,262,233,475,247,744,219,857,0,934 # <--- motion mask buske
```

### Relevant log output

```shell
Nothing relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
