### DISCUSSION TITLE
[Config Support]: Birdseye views are pixelated

### DISCUSSION THREAD

**Discussion by DaveTSG** [blakeblackshear/frigate#10513] [Config Support] [answered]
### Describe the problem you are having

Main video streams are high-resolution, but the Birdseye view is pixelated

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.42
  enabled: True
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 
  stats_interval: 30
  
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    FrontDoor:
      - rtspx://192.168.1.1:7441/HZ6BuVp4F3iWXAwl
      - "ffmpeg:FrontDoor#audio=opus"
    PackageCam:
      - rtsps://192.168.1.1:7441/7EBFyiGKgiRhf0jU
      - "ffmpeg:PackageCam#audio=opus"
    GarageCam:
      - rtsps://192.168.1.1:7441/fLIVSyOaCypG4V7R
      - "ffmpeg:GarageCam#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.110:6955
      - stun:6955

cameras:
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/HZ6BuVp4F3iWXAwl?enableSrtp?video&audio
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/NhxjoXQg5OVd0KiN?enableSrtp?video&audio
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    detect:
      enabled: True
      width: 960
      height: 720
    motion:
      mask:
        - 244,268,276,274,311,277,309,318,315,358,302,378,295,413,289,439,283,452,278,439,253,389,208,369,188,298,204,277
        - 0,326,65,336,100,343,105,359,123,393,134,430,141,453,135,499,113,533,92,550,54,578,0,582
        - 235,526,257,521,289,528,297,538,301,559,305,592,300,623,283,635,256,644,246,634,229,619,209,596,208,572,230,549
        - 356,455,383,480,399,484,409,477,417,459,421,437,419,416,409,407,390,406,364,417,346,430
        - 485,457,511,466,529,433,518,409,492,403,466,433
        - 724,620,751,609,759,434,764,401,774,350,728,335,693,333,672,337,637,383,637,405,642,423,635,468,609,490,611,539
        - 0,0,960,0,960,165,750,241,682,263,616,295,524,292,381,314,310,321,195,319,141,321,0,307
  PackageCam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/7EBFyiGKgiRhf0jU?enableSrtp?video&audio
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True
      width: 1600
      height: 1200
    motion:
      mask:
        - 572,870,561,919,536,967,487,988,473,1028,492,1085,466,1170,457,1200,423,1200,380,1200,298,1200,218,1200,161,1200,114,1200,64,1200,0,1200,0,1124,0,802,51,802,114,800,185,807,222,812,235,811,270,805,310,755,332,737,384,714,427,705,445,701,434,629,447,563,475,520,516,480,510,423,546,402,582,395,613,417,617,466,621,499,686,507,710,521,693,547,611,580,576,597,538,584,510,608,504,643,504,675,541,724,571,769,581,816
        - 166,180,185,158,215,155,256,165,278,175,295,193,309,209,338,222,363,247,370,271,379,304,362,328,332,354,311,367,264,378,210,378,187,374,166,361,155,361,130,340,117,318,118,292,125,261,131,222,143,200
        - 1600,0,1600,169,1516,309,1506,331,1513,356,1480,387,1435,404,1399,370,1362,324,1296,270,1259,253,1218,218,1188,183,1180,145,1188,124,1208,87,1203,42,1223,24,1243,0
        - 1600,1200,1600,867,1600,718,1574,752,1506,785,1423,814,1260,883,1140,936,1063,956,998,990,862,999,321,1200
  GarageCam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/fLIVSyOaCypG4V7R?enableSrtp?video&audio
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/hR3g7Ce9h8UqzBLo?enableSrtp?video&audio
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True
      width: 1280
      height: 1280


birdseye:
  enabled: True
  mode: continuous

record:
    enabled: True
    expire_interval: 60
    retain:
        days: 0
    events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
          - car
          - dog
        retain:
            default: 90
            objects:
             person: 90
             dog: 15

snapshots:
    enabled: True
    clean_copy: True
    timestamp: True
    bounding_box: True
    retain:
        default: 90
```

### Relevant log output

```shell
(Nothing relevant in the log)
```

### Frigate stats

```json
Sorry, I have no idea what this means or how to get it.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Hello. The camera feeds on the "cameras" side-menu are high-resolution, but the camera feeds when shown in the birdseye view are somewhat pixelated.

I'm not sure what I need to change to make the birdseye view higher-resolution. Any advice please?

I asked a few days ago on Reddit and [someone suggested increasing the resolution of the "detect" streams](https://www.reddit.com/r/frigate_nvr/comments/1bf40j4/comment/kv17dfq/?utm_source=reddit&utm_medium=web2x&context=3). I tried this but saw no improvement in Birdseye resolution.

Thanks in advance for your help.
