### DISCUSSION TITLE
[Support]: Birdseye not working after a while

### DISCUSSION THREAD

**Discussion by pszafer** [blakeblackshear/frigate#10518] [General Support]
### Describe the problem you are having

Hi,
After several hours every day Birdseye is not working for me. It's just blank screen, stays on loading.
No much error logs in frigate, go2rtc.
Just after opening in rtsp I got after several minutes.
Restarting Frigate fixes issue for 3-4 hours.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: '{FRIGATE_MQTT_HOST}'
  port: 1883
  user: mqtt
  password: '{FRIGATE_MQTT_PASSWORD}'
logger:
  default: debug
  logs:
    ffmpeg.wiata: error
    frigate.record: warning
    peewee: warning
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy
  hwaccel_args:
  - -hwaccel
  - vaapi
  - -hwaccel_device
  - /dev/dri/renderD128
  - -hwaccel_output_format
  - yuv420p
birdseye:
  enabled: true
  width: 1920
  height: 1080
  quality: 6
  mode: continuous
  restream: true
objects:
  track:
  - person
  - car
  - dog
go2rtc:
  streams:
    go_bok_garaz:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.51.7:554/h264Preview_01_main
    go_gabinet:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.9:554/Streaming/Channels/1
    go_fix:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.10:554/Streaming/Channels/1
    go_taras_dol:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.11:554/cam/realmonitor?channel=1&subtype=0
    go_kuchnia:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.51.13:554/cam/realmonitor?channel=1&subtype=0
    go_garaz:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.12:554/cam/realmonitor?channel=1&subtype=0
    go_taras_gora:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.8:554/Streaming/Channels/1
    go_adas:
    - rtsp://192.168.51.45/ch0_0.h264
    adas_audio:
    - ffmpeg:rtsp://127.0.0.1:8554/go_adas?audio=aac
    tapo:
    - rtsp://admintapo:{FRIGATE_RTSP_PASSWORD}@192.168.51.27/stream1
    go_domofon:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.29/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.29/cam/realmonitor?channel=1&subtype=0#audio=opus

  webrtc:
    candidates:
    - 192.168.50.6:8555
    - stun:8555
cameras:
  domofon:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/go_domofon
          roles:
            - detect
    detect:
      width: 1280
      height: 720
  bokgaraz:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/go_bok_garaz
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.51.7:554/h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 360
    record:
      events:
        required_zones:
        - z_bok_dom_garaz
        - z_parking_skrzynka
    objects:
      track:
      - person
      - car
      - dog
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    zones:
      z_bok_dom_garaz_car:
        coordinates: 155,360,81,188,222,168,640,266,640,360
        objects:
        - car
      z_parking_skrzynka:
        coordinates: 312,70,325,149,141,167,134,104
        objects:
        - car
        - person
      z_bok_dom_garaz:
        coordinates: 155,360,81,188,222,168,640,266,640,360
        objects:
        - person
  gabinet:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/go_gabinet
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.9:554/Streaming/Channels/2
        roles:
        - detect
    record:
      enabled: true
      events:
        required_zones:
        - zone_gabinet_wejscie
        - zone_gabinet_ulica
        - z_brama_gab_ulica
    detect:
      width: 1280
      height: 720
    live:
      stream_name: go_gabinet
    zones:
      z_brama_gab_ulica:
        coordinates: 766,265,932,203,841,209,777,184,722,222
      z_wioslarska_dol:
        coordinates: 968,54,957,152,574,122,562,61
      zone_gabinet_ulica:
        coordinates: 502,173,0,328,38,526,665,232
      zone_gabinet_wejscie:
        coordinates: 1074,720,0,720,0,642,876,215,1120,276
        filters:
          person:
            min_area: 14000
            threshold: 0.7
  fix:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/go_fix
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.10:554/Streaming/Channels/3
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
      - person
      filters:
        person:
          min_area: 1000
    zones:
      zone_fix_ogrod:
        coordinates: 456,277,572,276,1258,230,1280,720,81,720,58,387
  tarasdol:
    zones:
      zone_taras_dol_w_garaz:
        coordinates: 358,543,922,592,1025,603,937,371,662,324,343,266
      zone_hst:
        coordinates: 0,585,0,720,236,720,147,409,0,419
    ffmpeg:
      #output_args:
      #  rtmp: -vf transpose=1 -c:v libx264 -preset ultrafast -tune zerolatency -an -f flv
      inputs:
      - path: rtsp://localhost:8554/go_taras_dol
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.11:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
      - person
      - dog
      filters:
        person:
          min_area: 1000
  kuchnia:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/go_kuchnia
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.51.13:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    zones:
      z_kuchnia_ogrod:
        coordinates: 1055,228,1185,306,985,720,258,720,57,475
      z_kuchnia_ulica:
        coordinates: 489,40,1017,125,1203,229,1182,282
    motion:
      mask:
      - 515,0,0,0,0,148,650,86
    detect:
      width: 1280
      height: 720
    objects:
      track:
      - person
  garaz:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/go_garaz
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.12:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    record:
      events:
        required_zones:
        - ulica
        - z_front
    zones:
      ulica:
        coordinates: 518,231,1058,382,824,485,400,279
      z_front:
        coordinates: 84,720,619,621,788,526,363,326,0,386
      z_garaz:
        coordinates: 0,720,109,720,28,413,0,351
      z_sasiad:
        coordinates: 1280,0,1280,363,621,218,124,144
    motion:
      mask:
      - 0,0,0,235,144,200,124,144,340,0,128,0
  tarasgora:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/go_taras_gora
        roles:
        - record
        input_args: preset-rtsp-restream
      - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.51.8:554/Streaming/Channels/2
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
      - 0,338,901,299,1280,253,1280,0,746,0,0,0
    objects:
      track:
      - person
    zones:
      z_taras_gora:
        coordinates: 1197,529,1280,597,1280,720,495,720,495,604
      z_ogrod_z_gory:
        coordinates: 874,381,1087,512,383,565,344,720,0,720,0,397
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: /config/models/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
model:
    width: 300
    height: 300
    input_tensor: nhwc
    input_pixel_format: bgr
    labelmap_path: /config/models/coco_labels.txt
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  required_zones: []
  retain:
    default: 5
record:
  enabled: true
  expire_interval: 120
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
    - person
    - car
    - bicycle
    required_zones: []
    retain:
      default: 30
      mode: motion
      objects:
        person: 20
        dog: 7
```

### Relevant log output

```shell
ERR [exec] timeout url="exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -r 10 -i /tmp/cache/birdseye -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -rtsp_transport tcp -f rtsp {output}"
```

### FFprobe output from your camera

```shell
Is there FFProbe for birdseye?
```

### Frigate stats

```json
Are there stats for birdseye?
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua, Hikvision
