### DISCUSSION TITLE
[Camera Support]: Bird cams juddery and corrupted

### DISCUSSION THREAD

**Discussion by bgprior** [blakeblackshear/frigate#10526] [Camera Support]
### Describe the problem you are having

I have so many problems with Frigate, it's hard to know where to start, but here's one. I have 6 RTSP streams. 3 are identical birdbox IP cams from Green Feathers (https://www.green-feathers.co.uk/collections/bird-box-cameras/products/bird-box-camera-hd-with-network-connection-3rd-gen-poe-version), and 3 are streams from a 4-way Axis video server. This is about the bird cams.

Green Feathers don't reveal the manufacturer. My Unifi network controller identifies them as Foscam G4s. They could be Foscams; definitely not G4s. Some of the details from their specs:

Main Stream Resolution: 1920x1080 @ 20fps
Sub Stream Resolution: 640x480 @ 20fps
Video Compression: H.264 
Their specs don't say, but ffprobe reveals the audio is pcm-alaw.

The streams look fine (e.g. direct connection with VLC, or on Green Feathers' app). I can't see the main stream at intended quality through Frigate's Live View because I haven't been able to get MSE (reliably) or WebRTC (at all) working, so I'm stuck with jsmpeg. [I think the former is because of the corruption problem, because it usually plays for a second before failing, and sometimes longer. The latter is probably because it's not configured correctly yet.] 

The recordings are juddery and corrupted. Most of the time, I can't view them through Frigate's interface (whether through Events or Recordings), because it complains the files are too corrupted within a few seconds of going to the Recordings page, or fails when clicking on the Event clip. But I can get the 10-second chunks directly from the store and play them with VLC or Quicktime. I have uploaded a representative one.

https://github.com/blakeblackshear/frigate/assets/54583802/8347c583-f429-4b20-88f9-cfd35d4ad22d

The cameras timestamp the video, and it's particularly easy to spot the problem in the timestamp. If you look carefully, you can see the video jump and freeze to match. I have occasionally even seen the timestamp jump backwards a second or two.

From googling how to diagnose video file corruption, I saw a suggestion to use something like:

ffmpeg -v error -i FILENAME_OR_STREAM_URL -f null - 2> errors.log

Besides varying numbers of errors like the ones dominating Frigate's log, e.g.

[h264 @ 0x7393c817d600] error while decoding MB 37 66, bytestream -6

There were also quite a lot of things like this:

[null @ 0x5f9a73767f40] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 6 >= 1

I think that's a different problem, but I mention it for completeness.

One of the cameras (barn_birdbox_r) has materially fewer errors than the other two, and consequently has a slightly higher chance of being able to view the recordings through Frigate's interface. But still in the minority, and the other two barely ever.

Unlike the Axis system (which is ancient), these are new cameras. Two are connected via one switch, and the third via a different switch to the network hub, where the NUC (10th gen, i7, 32G RAM) that Frigate is running on is connected. It's all wired, not wifi. According to my Unifi UDM Pro, latency between each of the cameras and the hub is 0.2-0.3 ms. I doubt it's network problems.

The base OS on the NUC is Ubuntu 22.04. Besides Frigate, the NUC is running Mosquitto, Plex Media Server, a KVM VM for Home Assistant, and occasionally another VM for Windows 11 (no correlation with this problem). Docker's default firewall rules conflicted on install with the VMs, resolved by allowing packets to be forwarded to/from the bridge created for the VMs. Other than that, it's a vanilla install. I ought to try network:host, given the intended use (mainly for integration with HASS), but haven't yet.

I have played with all sorts of config settings, and ffmpeg options (running it directly from the command line with output to null, to try to isolate the problem). I don't have a clear grasp of how to choose which options. There are probably configuration errors, but I couldn't find anything in the documentation or google that connected this problem with a particular config snafu. The simple config below gave me fewer problems than most (e.g. I had tried using the go2rtc localhost restreams instead of the original streams in the cameras section, but that produced more errors, and likewise for different presets). I have disabled most of the cameras to try to get just one working, but it didn't make any difference, and at least this way, I am getting something I can use while I try to make it work better.

Is it hardware issues (3 new units similarly failed?!), am I doing something wrong, or is ffmpeg flawed? Why do the streams work viewed directly or via the manufacturer's app, but not via frigate?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: 192.168.83.251
  user: mquser
  password: mqPa55w0rd

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 5
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

go2rtc:
  streams:
    summerhouse_bird_feeder: 
      - rtsp://192.168.83.190:8554/main
      - "ffmpeg:summerhouse_bird_feeder#audio=aac"
    barn_birdbox_r: 
      - rtsp://192.168.83.224:8554/main
      - "ffmpeg:barn_birdbox_r#audio=aac"
    barn_birdbox_l: 
      - rtsp://192.168.83.208:8554/main
      - "ffmpeg:barn_birdbox_l#audio=aac"
    summerhouse_birdbox_l:
      - rtsp://192.168.83.84/mpeg4/1/media.amp
    summerhouse_birdbox_r:
      - rtsp://192.168.83.84/mpeg4/3/media.amp
    summerhouse_external:
      - rtsp://192.168.83.84/mpeg4/2/media.amp

cameras:
  summerhouse_bird_feeder:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/summerhouse_bird_feeder
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.83.190:8554/sub
          roles:
            - detect
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - sheep
    motion:
      threshold: 20
      contour_area: 8
      mask:
        - 204,0,203,42,0,41,0,0
        - 0,360,215,360,204,124,0,125
    detect:
      width: 640
      height: 480
      fps: 5
  barn_birdbox_r:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/barn_birdbox_r
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.83.224:8554/sub
          roles:
            - detect
    objects:
      track:
        - bird
    detect:
      width: 640
      height: 480
      fps: 5
  barn_birdbox_l:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/barn_birdbox_l
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.83.208:8554/sub
          roles:
            - detect
    objects:
      track:
        - bird
    detect:
      width: 640
      height: 480
      fps: 5
  summerhouse_birdbox_l:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://192.168.83.84/mpeg4/1/media.amp
          input_args: preset-rtsp-restream
          roles:
            - record
  summerhouse_birdbox_r:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://192.168.83.84/mpeg4/3/media.amp
          input_args: preset-rtsp-restream
          roles:
            - record
  summerhouse_external:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://192.168.83.84/mpeg4/2/media.amp
          input_args: preset-rtsp-restream
          roles:
            - record
```

### Relevant log output

```shell
2024-03-18 13:59:00.023296355  [INFO] Preparing Frigate...
2024-03-18 13:59:00.030374067  [INFO] Starting Frigate...
2024-03-18 13:59:01.350414732  [2024-03-18 13:59:01] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-18 13:59:01.978205476  [h264 @ 0x43d2c00] co located POCs unavailable
2024-03-18 13:59:03.793422593  [2024-03-18 13:59:03] peewee_migrate.logs            INFO    : Starting migrations
2024-03-18 13:59:03.799661232  [2024-03-18 13:59:03] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-18 13:59:03.804545761  [2024-03-18 13:59:03] frigate.app                    INFO    : Recording process started: 633
2024-03-18 13:59:03.806646067  [2024-03-18 13:59:03] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-18 13:59:03.826744947  [2024-03-18 13:59:03] detector.coral                 INFO    : Starting detection process: 643
2024-03-18 13:59:03.829397420  [2024-03-18 13:59:03] frigate.app                    INFO    : Output process started: 645
2024-03-18 13:59:03.845796326  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor not started for disabled camera viomic
2024-03-18 13:59:03.846050958  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor started for summerhouse_bird_feeder: 654
2024-03-18 13:59:03.851700280  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor started for barn_birdbox_r: 657
2024-03-18 13:59:03.857113511  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor started for barn_birdbox_l: 659
2024-03-18 13:59:03.866921481  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor started for summerhouse_birdbox_l: 662
2024-03-18 13:59:03.867085388  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor started for summerhouse_birdbox_r: 665
2024-03-18 13:59:03.872381165  [2024-03-18 13:59:03] frigate.app                    INFO    : Camera processor started for summerhouse_external: 667
2024-03-18 13:59:03.872469557  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process not started for disabled camera viomic
2024-03-18 13:59:03.877796407  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process started for summerhouse_bird_feeder: 670
2024-03-18 13:59:03.883141710  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process started for barn_birdbox_r: 674
2024-03-18 13:59:03.887859337  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process started for barn_birdbox_l: 678
2024-03-18 13:59:03.895182094  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process started for summerhouse_birdbox_l: 685
2024-03-18 13:59:03.901488110  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process started for summerhouse_birdbox_r: 709
2024-03-18 13:59:03.908224893  [2024-03-18 13:59:03] frigate.app                    INFO    : Capture process started for summerhouse_external: 716
2024-03-18 13:59:06.474537990  [2024-03-18 13:59:03] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-18 13:59:06.477751415  [2024-03-18 13:59:06] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-03-18 14:00:14.080059578  [2024-03-18 14:00:14] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
2024-03-18 14:00:14.080062759  
2024-03-18 14:01:14.750458730  [2024-03-18 14:01:14] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
2024-03-18 14:01:14.750461431  
2024-03-18 14:04:18.915770894  [h264 @ 0x7393c8009b40] error while decoding MB 68 67, bytestream -6
2024-03-18 14:05:48.851629938  [h264 @ 0x7393c8024c00] error while decoding MB 119 67, bytestream -7
2024-03-18 14:12:28.935943968  [h264 @ 0x7393c81bec40] error while decoding MB 69 67, bytestream -8
2024-03-18 14:13:28.858052823  [h264 @ 0x7393c800af80] error while decoding MB 119 67, bytestream -5
2024-03-18 14:16:38.899009095  [h264 @ 0x7393c8010e00] error while decoding MB 14 66, bytestream -6
2024-03-18 14:22:28.952127948  [h264 @ 0x7393c8011cc0] error while decoding MB 105 67, bytestream -6
2024-03-18 14:23:48.951530107  [h264 @ 0x7393c80261c0] error while decoding MB 101 67, bytestream -12
2024-03-18 14:33:58.949786748  [h264 @ 0x7393c81181c0] error while decoding MB 119 67, bytestream -5
2024-03-18 14:34:28.950347407  [h264 @ 0x7393c801ac40] error while decoding MB 119 67, bytestream -5
2024-03-18 14:36:38.928949834  [h264 @ 0x7393c81d5ac0] error while decoding MB 119 67, bytestream -5
2024-03-18 14:39:19.015302164  [h264 @ 0x7393c81d5ac0] error while decoding MB 0 67, bytestream -5
2024-03-18 14:49:58.951749719  [h264 @ 0x7393c817d600] error while decoding MB 119 67, bytestream -5
2024-03-18 14:51:58.976982794  [h264 @ 0x7393c817d600] error while decoding MB 37 66, bytestream -6
... repeated a lot, roughly every 2 minutes on average
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1+esm3 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://192.168.83.190:8554/main':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{"cameras":{"barn_birdbox_l":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":678,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":693,"pid":659,"process_fps":5.1,"skipped_fps":0.0},"barn_birdbox_r":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":674,"detection_enabled":1,"detection_fps":1.6,"ffmpeg_pid":683,"pid":657,"process_fps":5.1,"skipped_fps":0.0},"summerhouse_bird_feeder":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":670,"detection_enabled":1,"detection_fps":19.3,"ffmpeg_pid":675,"pid":654,"process_fps":5.1,"skipped_fps":0.0},"summerhouse_birdbox_l":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":685,"detection_enabled":1,"detection_fps":10.3,"ffmpeg_pid":712,"pid":662,"process_fps":5.1,"skipped_fps":0.0},"summerhouse_birdbox_r":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":709,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":720,"pid":665,"process_fps":5.1,"skipped_fps":0.0},"summerhouse_external":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":716,"detection_enabled":1,"detection_fps":15.2,"ffmpeg_pid":728,"pid":667,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"4.0","cpu_average":"3","mem":"0.1"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"2.0","cpu_average":"2","mem":"1.0"},"113":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"164":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"196":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"232":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"261":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"290":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"331":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"378":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"423":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"453":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"583":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"633":{"cmdline":"frigate.recording_manager","cpu":"1.6","cpu_average":"1","mem":"0.4"},"642":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"643":{"cmdline":"frigate.detector.coral","cpu":"17.2","cpu_average":"14","mem":"0.4"},"645":{"cmdline":"frigate.output       ","cpu":"1.3","cpu_average":"1","mem":"0.4"},"651":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 426x240 -i pipe: -f mpegts -s 1278x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"653":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"654":{"cmdline":"frigate.process:summerhouse_bird_feeder","cpu":"22.9","cpu_average":"23","mem":"0.4"},"656":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"657":{"cmdline":"frigate.process:barn_birdbox_r","cpu":"2.0","cpu_average":"2","mem":"0.4"},"659":{"cmdline":"frigate.process:barn_birdbox_l","cpu":"2.6","cpu_average":"2","mem":"0.4"},"660":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"662":{"cmdline":"frigate.process:summerhouse_birdbox_l","cpu":"14.3","cpu_average":"13","mem":"0.4"},"664":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"665":{"cmdline":"frigate.process:summerhouse_birdbox_r","cpu":"3.2","cpu_average":"1","mem":"0.4"},"667":{"cmdline":"frigate.process:summerhouse_external","cpu":"17.3","cpu_average":"10","mem":"0.4"},"668":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"670":{"cmdline":"frigate.capture:summerhouse_bird_feeder","cpu":"0.7","cpu_average":"0","mem":"0.3"},"673":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"674":{"cmdline":"frigate.capture:barn_birdbox_r","cpu":"0.4","cpu_average":"0","mem":"0.3"},"675":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.83.190:8554/sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.1","cpu_average":"3","mem":"0.2"},"678":{"cmdline":"frigate.capture:barn_birdbox_l","cpu":"0.9","cpu_average":"0","mem":"0.3"},"681":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"683":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.83.224:8554/sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"2","mem":"0.2"},"685":{"cmdline":"frigate.capture:summerhouse_birdbox_l","cpu":"0.9","cpu_average":"0","mem":"0.3"},"686":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/summerhouse_bird_feeder -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/summerhouse_bird_feeder@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"693":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.83.208:8554/sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.4","cpu_average":"2","mem":"0.2"},"709":{"cmdline":"frigate.capture:summerhouse_birdbox_r","cpu":"0.7","cpu_average":"0","mem":"0.3"},"712":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.83.84/mpeg4/1/media.amp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/summerhouse_birdbox_l@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=704:576 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.0","cpu_average":"1","mem":"0.1"},"713":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/barn_birdbox_r -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/barn_birdbox_r@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.1"},"716":{"cmdline":"frigate.capture:summerhouse_external","cpu":"1.1","cpu_average":"0","mem":"0.3"},"719":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/summerhouse_bird_feeder?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/00cbb1135e7f4204922dc8a85c0bb58c","cpu":"2.4","cpu_average":"2","mem":"0.1"},"720":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.83.84/mpeg4/3/media.amp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/summerhouse_birdbox_r@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=704:576 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.1"},"724":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/barn_birdbox_r?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/234250d8bc9cf94084667929576f63d4","cpu":"2.5","cpu_average":"2","mem":"0.1"},"726":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/barn_birdbox_l -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/barn_birdbox_l@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.1"},"727":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/barn_birdbox_l?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/a388f7dc3057a515ddde134bd6babbed","cpu":"2.3","cpu_average":"2","mem":"0.1"},"728":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.83.84/mpeg4/2/media.amp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/summerhouse_external@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=704:576 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.0","cpu_average":"4","mem":"0.1"},"79972":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":46.9,"detectors":{"coral":{"detection_start":1710779087.279576,"inference_speed":8.34,"pid":643}},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":583},"recording":{"pid":633}},"service":{"last_updated":1710779087,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":120.6,"mount_type":"tmpfs","total":128.0,"used":7.4},"/media/frigate/clips":{"free":7112025.9,"mount_type":"fuseblk","total":11444190.0,"used":4332164.1},"/media/frigate/recordings":{"free":7112025.9,"mount_type":"fuseblk","total":11444190.0,"used":4332164.1},"/tmp/cache":{"free":944.0,"mount_type":"tmpfs","total":953.7,"used":9.7}},"temperatures":{},"uptime":8744,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Foscam?
