### DISCUSSION TITLE
[Support]: ANY audio detection?

### DISCUSSION THREAD

**Discussion by wouterverduin** [blakeblackshear/frigate#10521] [General Support]
### Describe the problem you are having

Been running frigate which is great!

However for my newborn i want audio detection. I noticed i can select up to 500 different sounds but i want it to just toggle on ANY sound if it is hard enough to pass the volume level. However, i cant seem to figure out how to set this up?

The main thing i am looking at is using the detection in home-assistant. Got the integration up and running like a charm. It can detect cries etc but i want it to alarm at just any sound. Anyone know how to set that up?

### Version

0.13.0-01E2D20

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.14
  user: frigate
  password: xxx

database:
  path: /config/frigate.db

logger:
  default: debug

go2rtc:
  rtsp:
    username: "xx"
    password: "xx"
  streams:
    babycam:
      - "ffmpeg:rtsp://xx:xx@192.168.1.14/av_stream/ch0#video=copy#audio=aac"
    puppy:
      - rtsp://192.168.1.19:8554/unicast
  webrtc:
    candidates:
      - 192.168.1.50:8555
      - stun:8555

objects:
  track:
    - person
    - dog

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 500

motion:
  threshold: 40
  improve_contrast: false
  mqtt_off_delay: 30

record:
  enabled: True
  retain:
    days: 3
  events:
    pre_capture: 3
    post_capture: 20
    retain:
      default: 3
      mode: motion

cameras:
  puppycam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.19:8554/unicast
          roles:
            - detect
            - record
    audio:
      enabled: False
    detect:
      width: 800
      height: 600
  babycam:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xx@192.168.1.14/av_stream/ch0
          roles:
            - detect
            - audio
    audio:
      enabled: True
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Sonoff
