### DISCUSSION TITLE
[HW Accel Support]: Coral TPU only for one Camera ?

### DISCUSSION THREAD

**Discussion by mikki8** [blakeblackshear/frigate#10525] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hi,
my system page looks like this:
![grafik](https://github.com/blakeblackshear/frigate/assets/76606753/f8fae595-e05f-491c-af0c-fa6d0212a1fb)

does this mean the coral tpu is used only for one camera ?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-intel-qsv-h264

cameras:
  test-1:
    ffmpeg:
      inputs:
        - path: rtsp://*:*@192.168.11.1/ch0_1.h264
          roles:
            - detect
        - path: rtsp://*:*@192.168.11.1/ch0_0.h264
          roles:
            - record
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,0,0,48,183,44,184,0
    record:
      enabled: True
      events:
        retain:
          default: 10
  test-2:
    ffmpeg:
      inputs:
        - path: rtsp://*:*@192.168.11.2/ch0_1.h264
          roles:
            - detect
        - path: rtsp://*:*@192.168.11.2/ch0_0.h264
          roles:
            - record
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
#    birdseye:
#      enabled: true
#      mode: continuous
```

### docker-compose file or Docker CLI command

```yaml
version: '3'
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./data/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

yi home
