### DISCUSSION TITLE
[Config Support]: how to choose which stream gets shown in Home Assistant

### DISCUSSION THREAD

**Discussion by spitfire** [blakeblackshear/frigate#10538] [Config Support]
### Describe the problem you are having

I have Frigate installed on a separate server and connected to HA. I have two cameras, both of which offer a main full-res h265 stream, and a cut down h264 sub. I've already set up detection on sub, and recording on main. I'd like to use the latter for HA so I can expose it to HomeKit Bridge. I've added the stream name to the live: stream_name: config item.
Would this (as a h264 stream) be best for HomeKit, and is does this config look ok?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
camras:
brama:
    enabled: true
    birdseye:
      enabled: true
    webui_url: "http://<camera-ip>/"
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/brama_sub
        roles:
        - detect
        hwaccel_args: preset-nvidia-h264
      - path: rtsp://localhost:8554/brama_main
        roles:
        - record
        hwaccel_args: preset-nvidia-h265
    live:
      stream_name: brama_sub
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    record:
      enabled: true

go2rtc:
  streams:
    brama_main:
      - rtsp://<username, password, and camera ip>/cam/realmonitor?channel=1&subtype=0
    brama_sub:
      - rtsp://<username, password, and camera ip>/cam/realmonitor?channel=1&subtype=1
```

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Using NVIDIA GPU trhough docker runtime.

**Comment by NickM-27** [comment]
The stream that is used is the one that matches the name of the camera. I don't believe HomeKit supports h265 so you'll need to rename the sub stream by removing the _sub at the end.

**Reply by spitfire** [reply]
Do you mean rename the go2rtc restream of _sub channel to match the cam name?

**Reply by NickM-27** [reply]
yes, like

```
camras:
  brama:
    ...

go2rtc:
  streams:
    brama_main:
      - rtsp://<username, password, and camera ip>/cam/realmonitor?channel=1&subtype=0
    brama:
      - rtsp://<username, password, and camera ip>/cam/realmonitor?channel=1&subtype=1
```
