### DISCUSSION TITLE
Restricting events to specific zones not working

### DISCUSSION THREAD

**Discussion by asemev** [blakeblackshear/frigate#10539] [Config Support] [answered]
### Describe the problem you are having

- I have a camera at my front door.
- At the end of the entrance, there is a pavement
- I configured a zone for only detecting persons entering my home entrance, walking towards my door. So anybody just walking past my home along the pavement should be ignored.
- I made sure the zone is very separated from the pavement and also added intertia=3.
- I also added required zone in the notification (0.12.0.2)
- Despite all my efforts for several hours, frigate still keeps sending me a notification whenever someone just walks on the pavement.
- Pls note that i dont want to mask the pavement area because then it half of the image of the person is blacked out when they start walking towards my door.
- I have read the instructions carefully and tried all the options
- I have also checked the github issues section in case someone else had the same issue but couldnt find anything.
- I posted a few screenshots so you can see my zone area and the people walking on the pavement
- i also get an error when i click on "View Clip or View Snapshot int he Android notification. Screenshot below.

![image](https://github.com/blakeblackshear/frigate/assets/30929896/b5c09f37-c3d4-4fd6-91ae-84ab0df6593b)
![image](https://github.com/blakeblackshear/frigate/assets/30929896/a51d6437-3241-46bb-9a5d-4b10b796c6a4)
![image](https://github.com/blakeblackshear/frigate/assets/30929896/59290ee9-6c8e-4960-9a2e-0da790b08f59)
![image](https://github.com/blakeblackshear/frigate/assets/30929896/2a3a41c0-3b5c-4d1f-a169-d179c5fa7c34)

Many thanks!

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb'
    num_threads: 4
mqtt:
  host: 192.168.178.125
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user:
  password: 
#ffmpeg:
#  hwaccel_args:
#    - '-c:v'
#    - h264_v4l2m2m

#ffmpeg:
#  hwaccel_args: preset-rpi-64-h264

cameras:
#  Garage:
#    ffmpeg:
#      inputs:
#        - path: 'rtsp://
#          global_args: '-hide_banner -loglevel error'
#          roles:
#            - detect
#            - record
#    detect:
#     width: 1920
#      height: 1080
#      fps: 5
#    motion:
#      mask: >-
#        -0,0,1920,0,1920,1080,1490,1080,1659,694,690,270,121,417,345,1080,0,1080
#    snapshots:
#      enabled: true
#      timestamp: true
#      bounding_box: true
#      crop: false
#      height: 175
#      retain:
#        default: 10
#        objects:
#          person: 10
#    mqtt:
#      enabled: true
#      timestamp: true
#      bounding_box: true
#      crop: true
#      height: 270
#    objects:
#      track:
#        - person
#
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          min_score: 0.5
#          threshold: 0.7
#          mask: >-
#            -2,1,1920,0,1920,1080,1490,1080,1678,653,547,227,533,73,354,86,370,292,116,340,285,1012,680,1014,678,1080,0,1080
#    zones:
#      car:
#        coordinates: 343,1058,1477,1080,1654,683,776,252,123,394
#    record:
#      enabled: true
#      retain: 
#        days: 3
#        mode: motion 
#      events:
#        retain:
#          default: 3
#          mode: active_objects

  Package:
    ffmpeg:
      inputs:
        - path: 
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,1080,1920,1080,1350,547,1408,891,1081,899,1105,544,1307,523,1920,1080,1920,0,0,0

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 10

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person

    zones:
      box:
        coordinates: 1128,888,1408,891,1356,564,1073,535
    record:
      enabled: true
      retain: 
        days: 3
        mode: motion 
      events:
        retain:
          default: 3
          mode: active_objects

  Door:
    ffmpeg:
      inputs:
        - path: 
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
    record:
      enabled: true
      retain: 
        days: 10
        mode: motion 
      events:
        required_zones:
          - entire_yard
        retain:
          default: 10
          mode: active_objects
    snapshots:
      required_zones:
        - zone_0
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
    zones:
      zone_0:
        coordinates: 235,1080,1920,1080,1734,387,502,324
        inertia: 3
        objects:
          - person
database:
  path: /media/frigate.db
logger:
  default: info
  logs:
    frigate.mqtt: error
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
