### DISCUSSION TITLE
[Config Support]: Reduce CPU usage on server without GPU

### DISCUSSION THREAD

**Discussion by Tropaion** [blakeblackshear/frigate#10545] [Config Support]
### Describe the problem you are having

Hello,
I'm new to Frigate and want to use it for my Reolink Doorbell so I can talk with the person at the door through home assistant.
I'm running HA on an old Dell PowerEdge T320 with Proxmox. HA is limited to 4 Cores and 8 GB RAM.
I got this setup running and works okay, could be better but it works.
Sadly the HA cpu load is always at 100%. Is there a way to reduce it?
As far as I understood, the reasons is the transcoding, but do I really need it for my case?
And if not, my server officially supports an nVidia Quadro 4000 or 8000, would this help in any way?
I could also buy the Coral but as far is I know/understood it only helps with AI interference and not decoding.
I don't need any special features and just want to use the two-way talk within HA.

I hope someone can guide me.
Thanks,
Tropaion

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: **************
  stats_interval: 60

### go2rtc settings ####

go2rtc:
  streams:
    reolink_doorbell:
      - "ffmpeg:http://192.168.88.108/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=2gGG2CNPEmg0cZ#video=copy#audio=copy#audio=opus"
      - rtsp://admin:2gGG2CNPEmg0cZ@192.168.88.108/Preview_01_sub
    #      - rtsp://admin:2gGG2CNPEmg0cZ@192.168.88.108:554/h264Preview_01_sub
    #      - ffmpeg:rtsp://admin:2gGG2CNPEmg0cZ@192.168.88.108:554/h264Preview_01_sub#audio=pcm#audio=volume
    reolink_doorbell_sub:
      - "ffmpeg:http://192.168.88.108/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=2gGG2CNPEmg0cZ"
  ## this prevents audio from coming out from the doorbell sounding muffled
#  ffmpeg:
#    bin: ffmpeg
#    volume: '-af "volume=30dB"'

### configure cameras ###
cameras:
  reolink_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:2gGG2CNPEmg0cZ@192.168.88.108/Preview_01_sub
#          roles:
#            - detect
#            - record
#      output_args:
#        record: preset-record-generic-audio-copy
#    zones:
#      reolink_zone:
#        coordinates: 0,480,800,480,543,323,362,329,0,61 # WATCH MY FRIGATE VIDEO SHOWING YOU WHAT THIS IS
#    motion:
#      mask:
#        - 613,309,800,361,800,0,275,0,297,339 # WATCH MY FRIGATE VIDEO SHOWING YOU WHAT THIS IS

### Global settings
#ffmpeg:
#  hwaccel_args: preset-vaapi
detect:
  width: 640
  height: 360
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
