### DISCUSSION TITLE
Spotter cam (MQTT+Home Assistant) Examples?

### DISCUSSION THREAD

**Discussion by NullReferenceError** [blakeblackshear/frigate#10547] [General]
Tried searching through repository and docs for spotter examples - but curious if anyone has any spotter camera examples for listening on frigate events per zone, to set PTZ to specific presets? I have MQTT events setup already, and presets configured on the PTZ.

**Comment by NickM-27** [comment]
@hawkeye217 do you know of anyone who has shared examples?

**Reply by hawkeye217** [reply]
Before I wrote autotracking for Frigate, I used to have a simple automation in Home Assistant to move my PTZ to different zones I had set up based on the presence of a `person` in those zones. For example, here is the automation that I used to move my PTZ camera to my front door preset when a person was detected by my doorbell camera:

```
alias: "CAMERA: PTZ to front door when person detected"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbellcam_person_occupancy
    to: "on"
    id: detected
  - platform: state
    entity_id:
      - binary_sensor.doorbellcam_person_occupancy
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: clear

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - detected
        sequence:
          - service: frigate.ptz
            metadata: {}
            data:
              action: preset
              argument: front_door
      - conditions:
          - condition: trigger
            id: clear
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id:
                  - binary_sensor.ptzcam_person_occupancy
                to: "off"
                for:
                  hours: 0
                  minutes: 0
                  seconds: 8
          - service: frigate.ptz
            metadata: {}
            data:
              action: preset
              argument: home
mode: restart
```

The camera would move to the `front_door` preset when a person was detected by the doorbell camera, and then when a person was no longer detected by the doorbell camera, it would wait until a person was no longer detected on the PTZ for 8 seconds before moving back to the `home` preset.
