### DISCUSSION TITLE
[Question]: Odd Behaviour in Storage

### DISCUSSION THREAD

**Discussion by tibmeister** [blakeblackshear/frigate#10551] [Ask A Question]
### What is your question:

I have two cameras, both with the same resolution (2560x1920) and bitrate (6423 KB/s), but very different storage requirements.  They are both Reolink cameras and both streams are h264.  I have record set as follows globally:

```
record:
  enabled: True
  sync_recordings: True
  retain:
    days: 5
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects
```

So, I would expect that the reported **Stream Bandwidth** under **Storage** for both to be reasonably the same, but what I'm seeing is one camera is being reported as 2.66 GiB/hr and the other at 182.57 GiB/hr, and I tend to eat through the entire 1TB of storage in a hour or two, resulting in missing clips from a couple hours ago presumably because the storage is being cleared because of it being filled up.

I'm assuming that the **Stream Bandwidth** under **Storage** is how much storage that camera is using in the given time period, which makes no sense if both streams are the same resolution and bandwidth, how can there be such a difference between the storage requirements?
