### DISCUSSION TITLE
[Config Support]: Frigate Hass Addon records events apart from zone ?

### DISCUSSION THREAD

**Discussion by AdmiralRaccoon** [blakeblackshear/frigate#10563] [Config Support]
### Describe the problem you are having

Hello all,
due to the fact that this problems looks like a config error of mine, rather than a bug, i post it in here:

Focus is on the "cam_haustuer". As you can see there is a slight public area on the top, so i made a zone for the entrance only "zone_eingang" (See first picture)
In the Frigate UI, I guess it works as excpected, as I don´t see any detected people on the street in the events.
However, in Home Assistant there are quite some snapshots / recordings of people walking on the street (see picture 2).

Is there an error in the config?
Thank you for your time,

Philipp
 

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.99
  user: xxx
  password: xxx

#birdseye:
#  enabled: True
#  mode: objects

go2rtc:
  streams:
    cam_haustuer:
    - rtsp://administrator:xxxx@192.168.1.97:554/stream1
    cam_wohnzimmer:
    - rtsp://administrator:xxxx@192.168.1.96:554/stream1
    cam_garten:
    - rtsp://administrator:xxxx@192.168.1.94:554/stream1
    cam_party:
    - path: rtsp://administrator:xxxx@192.168.1.95:554/stream1


cameras:
  cam_haustuer:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://administrator:xxxx@192.168.1.97:554/stream1
        roles:
        - detect
        - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
      - 1134,0,0,0,0,194,437,51,468,92
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
        - zone_eingang
        retain:
          default: 7
          mode: active_objects
          objects:
            dog: 5
            cat: 5
            person: 7
        pre_capture: 5
        post_capture: 15
    objects:
      track:
      - person
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
      - zone_eingang
      retain:
        default: 30
        objects:
          person: 30
          dog: 5
          cat: 5
    zones:
      zone_eingang:
        coordinates: 1920,1080,1920,0,847,46,0,206,0,1080

  cam_wohnzimmer:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://administrator:xxxx@192.168.1.96:554/stream1
        roles:
        - detect
        - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
          objects:
            person: 7
            dog: 3
            cat: 3
        pre_capture: 5
        post_capture: 15
    objects:
      track:
      - person
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          dog: 10
          cat: 10


  cam_party:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://administrator:xxxx@192.168.1.95:554/stream1
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
          objects:
            dog: 2
            cat: 2
            person: 7
        pre_capture: 5
        post_capture: 15
    objects:
      track:
      - person
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          dog: 5
          cat: 5

  cam_garten:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://administrator:xxxx@192.168.1.94:554/stream1
        roles:
        - detect
        - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
        - zone_garten        
        retain:
          default: 7
          mode: active_objects
          objects:
            dog: 5
            cat: 5
            person: 7
        pre_capture: 5
        post_capture: 15
    objects:
      track:
      - person
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
      - zone_garten
      retain:
        default: 30
        objects:
          person: 30
          dog: 5
          cat: 5
    motion:
      mask:
      - 388,451,399,185,278,187,264,457
      - 764,436,775,208,549,188,547,451,625,453
    zones:
      zone_garten:
        coordinates: 
          0,1080,284,1080,1920,1080,1920,44,849,51,818,458,534,456,552,116,424,157,407,451,278,473,283,168,0,179
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

![screen2](https://github.com/blakeblackshear/frigate/assets/41727850/621953ec-9486-4ea9-a7d4-c724232542e3)
![screen1](https://github.com/blakeblackshear/frigate/assets/41727850/959e4bee-dda9-42b4-ba69-9fa20a29312d)

**Comment by NickM-27** [comment]
what you are looking at is the mqtt snapshot. If you do not want these to happen outside of the zone then you need to set required_zones on mqtt for each camera

```
cameras:

  your_camera:
    ...
    mqtt:
      required_zones:
       - ...
```
