### DISCUSSION TITLE
how to use frigate in a container stack (portainer) on a VLAN (IOT)

### DISCUSSION THREAD

**Discussion by johnvpr** [blakeblackshear/frigate#10566] [General]
Just wanted to share how to run frigate in a container stack (portainer)  on a VLAN (IOT)

you need to run this commend in the terminal to create a VLAN docker network (that will also show in portainer):
`docker network create -d macvlan   --subnet=192.168.20.0/24   --gateway=192.168.20.1   --ip-range=192.168.20.0/24    -o parent=vbr20 ipvlan20`

and add this to your docker compose network part:
```
dns:
      - 192.168.20.1
    # the networking section defines the interface from the
    # top-level network section
    networks: 
      # matches below
      ipvlan20:
        # if the following line is omitted the container
        # will pull from the ip-range from the network
        ipv4_address: 192.168.20.4
networks:
  # interface refered to by the service container
  ipvlan20:
    # KEY to look outside the compose for the network
    external: true.
```

my nixos config as reference:
```
networking = {

hostName = "nixos2";

# domain = "[example.com](https://example.com/)";

dhcpcd.enable = false;


##### BRIDGES

# for libvirtd

bridges = {

vbr20 = {

interfaces = [ "vlan20" ]; # rtsp = true;

};

};


interfaces.vlan10.ipv4.addresses = [{

address = "[192.168.10.3](https://192.168.10.3/)";

prefixLength = 24;

}];


# for VM libvirtd

interfaces.vbr20.ipv4.addresses = [{

address = "[192.168.20.3](https://192.168.20.3/)";

prefixLength = 24;

}];


interfaces.vlan99.ipv4.addresses = [{

address = "[10.10.99.3](https://10.10.99.3/)";

prefixLength = 24;

}];


vlans = {

vlan10 = { id = 10; interface = "eno1"; };

vlan20 = { id = 20; interface = "eno1"; };

vlan99 = { id = 99; interface = "eno1"; };

};


defaultGateway = "[192.168.10.1](https://192.168.10.1/)";

nameservers = [ "[1.1.1.1](https://1.1.1.1/)" "[8.8.8.8](https://8.8.8.8/)" ];


enableIPv6 = false;

nat = {

#

enable = false;

internalInterfaces = [ "vlan10" "vlan20" "vlan99" "br+" "veth+" "docker0" ]; # vlan40

};
```
