### DISCUSSION TITLE
[Detector Support]: RK detector.

### DISCUSSION THREAD

**Discussion by TechsavvyCNC** [blakeblackshear/frigate#10575] [Detector Support]
### Describe the problem you are having

I'm using the orange pi 5b with armbian running docker HA.  For the life of me I can't figure out how to edit the docker-compose.yml or where it's even located.  Also not sure how to use the frigate-rk version with home assistant addons.

### Version

Frigate-beta-fa

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.136
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: amcrest
  password: password
  stats_interval: 60

database:
  path: /media/frigate.db
  
go2rtc:
  streams:
    backdoor:
      - rtsp://admin:password@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0
    backdoor_sub:
      - rtsp://admin:password@192.168.1.147:554/cam/realmonitor?channel=1&subtype=1

cameras:
  backdoor: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp:/admin:password@192.168.1.147:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 320
      fps: 5
    objects:
      track:
        - person

    rtmp:
      enabled: false
      
record:
  enabled: false
  retain:
    days: 10
    # hours:
    # minutes: 
    mode: active_objects
  events:
    retain:
      default: 10
      mode: active_objects
      objects:
        dog: 10
        person: 10
    pre_capture: 5
    post_capture: 60
      
#detectors:
 # rknn:
  #  type: rknn
   # core_mask: 0b111
    
#model:
 # path: default-yolov8s
```

### docker-compose file or Docker CLI command

```yaml
Don't know
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

CPU (no coral)
