### DISCUSSION TITLE
Help with Getting CPU load down

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#10592] [General Support] [answered]
### Describe the problem you are having

I am running the TensorRT version and using my GTX1080 card for detection and doing 24x7 recording , I feel like the CPU load is still higher then it should be but I have nothign to compare it to!

![2024 03 21-000181](https://github.com/blakeblackshear/frigate/assets/19710296/a7157f09-7af8-45fd-8758-af8c08bb16bc)
![2024 03 21-000182](https://github.com/blakeblackshear/frigate/assets/19710296/3084cdf5-2d0d-4915-95f0-e3f1a86cbbf1)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

# Enable recording of all cameras and retain it for 14 days
record:
  enabled: true
  retain:
    days: 14

# Use experimental UI
ui:
  use_experimental: true

# Use the GPU to help with decoding streams and record audio!
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

# Enable birdseye option to see any cameras with motion on them 
birdseye:
  enabled: false
  width: 1280
  height: 720
  quality: 8
  mode: motion

detect:
  enabled: False
  width: 1920
  height: 1080

detectors:
  NVIDIA GeForce GTX 1080:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320


motion:
  mask:
    - 1360,65,1920,65,1920,0,1360,0 # Mask off time on all cameras

cameras:

  Deck:
    ui:
      order: 1

    ffmpeg:
      inputs:
        - path: rtsp://SMAIN270b:catFROGS213@192.168.86.214/live0
          roles:
            - record
  Driveway:
    ui:
      order: 2

    detect:
      enabled: True
      width: 640
      height: 360
      fps: 4

    ffmpeg:
      inputs:
        - path: rtsp://wejBBALvt2MZFxXTyQVb:9LsQiDvmaExyR_h0a@192.168.86.213/h264Preview_01_main
          roles:
            - record
        - path: rtsp://wejBBALvt2MZFxXTyQVb:9LsQiDvmaExyR_h0a@192.168.86.213/h264Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 640,29,640,0,398,0,398,30 ## Mask off time 
  Garage:
    ui:
      order: 3

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 4

    onvif:
      host: 192.168.86.210
      port: 8000
      user: 9oWLCdbmLKvd7
      password: 0jNlFeIj1iXT!
    
    ffmpeg:
      inputs:
        - path: rtsp://9oWLCdbmLKvd7:0jNlFeIj1iXT!@192.168.86.210/h264Preview_01_main
          roles:
            - record
        - path: rtsp://9oWLCdbmLKvd7:0jNlFeIj1iXT!@192.168.86.210/h264Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 386,31,640,28,640,0,389,0,385,0 ## Mask of time


  Front_Door:
    
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 4

    ui:
      order: 4

    ffmpeg:
      inputs:
        - path: rtsp://R3QAEkYH3N:oqxCW,C4G*_a4X@192.168.86.217/h264Preview_01_main
          roles:
            - record
        - path: rtsp://R3QAEkYH3N:oqxCW,C4G*_a4X@192.168.86.217/h264Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 384,32,640,32,640,0,385,0 ## Mask of time


  Front_Yard:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://7KvGYY0AG3F1:6BIwcoItbGrE@192.168.86.212/live0
          roles:
            - record
    motion:
      mask:
        - 1364,76,1894,68,1891,0,1361,0 # Mask of time
        - 1920,1080,1806,1080,1800,1053,1805,992,1803,899,1838,797,1920,761 # Mask off Christmas lights
  Ripleys_Room:
    ui:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://2gT8WP3vdSmt:5kMItKXsG78L@192.168.86.211/live0
          roles:
            - record
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"Deck":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":508,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":32823,"pid":497,"process_fps":5.1,"skipped_fps":0.0},"Driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.0,"capture_pid":512,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":517,"pid":498,"process_fps":4.0,"skipped_fps":0.0},"Front_Door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.1,"capture_pid":521,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":533,"pid":502,"process_fps":4.1,"skipped_fps":0.0},"Front_Yard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":527,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":536,"pid":504,"process_fps":5.1,"skipped_fps":0.0},"Garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.0,"capture_pid":516,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":522,"pid":499,"process_fps":4.0,"skipped_fps":0.0},"Ripleys_Room":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":534,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":543,"pid":506,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"22":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"35":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"36":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"37":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"38":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"39":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"50":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"51":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"94":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"95":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"99":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"105":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.2"},"124":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"129":{"cmdline":"python3 -u -m frigate","cpu":"2.8","cpu_average":"2","mem":"5.5"},"136":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"166":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"174":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"183":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"192":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"201":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"458":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"2.0"},"460":{"cmdline":"frigate.recording_manager","cpu":"5.2","cpu_average":"5","mem":"2.7"},"468":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(58)","cpu":"0.6","cpu_average":"0","mem":"0.1"},"469":{"cmdline":"frigate.detector.NVIDIA GeForce GTX 1080","cpu":"0.5","cpu_average":"5","mem":"6.3"},"470":{"cmdline":"frigate.output       ","cpu":"3.0","cpu_average":"3","mem":"2.3"},"474":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"477":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"478":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"479":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"481":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"482":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"497":{"cmdline":"frigate.process:Deck ","cpu":"1.9","cpu_average":"2","mem":"2.3"},"498":{"cmdline":"frigate.process:Driveway","cpu":"1.7","cpu_average":"8","mem":"2.4"},"499":{"cmdline":"frigate.process:Garage","cpu":"1.7","cpu_average":"1","mem":"2.4"},"502":{"cmdline":"frigate.process:Front_Door","cpu":"1.6","cpu_average":"14","mem":"2.4"},"504":{"cmdline":"frigate.process:Front_Yard","cpu":"2.4","cpu_average":"2","mem":"2.3"},"506":{"cmdline":"frigate.process:Ripleys_Room","cpu":"2.2","cpu_average":"2","mem":"2.3"},"508":{"cmdline":"frigate.capture:Deck ","cpu":"4.8","cpu_average":"5","mem":"2.5"},"512":{"cmdline":"frigate.capture:Driveway","cpu":"0.8","cpu_average":"0","mem":"2.3"},"516":{"cmdline":"frigate.capture:Garage","cpu":"0.9","cpu_average":"0","mem":"2.3"},"517":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.213/h264Preview_01_sub -r 4 -vf fps=4,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.4","cpu_average":"1","mem":"2.0"},"521":{"cmdline":"frigate.capture:Front_Door","cpu":"1.0","cpu_average":"0","mem":"2.3"},"522":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.210/h264Preview_01_sub -r 4 -vf fps=4,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"1","mem":"2.0"},"527":{"cmdline":"frigate.capture:Front_Yard","cpu":"6.0","cpu_average":"5","mem":"2.4"},"528":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.213/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Driveway@%Y%m%d%H%M%S%z.mp4","cpu":"9.7","cpu_average":"9","mem":"0.3"},"533":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.217/h264Preview_01_sub -r 4 -vf fps=4,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"1","mem":"2.0"},"534":{"cmdline":"frigate.capture:Ripleys_Room","cpu":"5.7","cpu_average":"5","mem":"2.4"},"536":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.212/live0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Front_Yard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.3","cpu_average":"11","mem":"3.8"},"537":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.210/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Garage@%Y%m%d%H%M%S%z.mp4","cpu":"8.9","cpu_average":"9","mem":"0.3"},"542":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.217/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Front_Door@%Y%m%d%H%M%S%z.mp4","cpu":"9.2","cpu_average":"9","mem":"0.3"},"543":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.211/live0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Ripleys_Room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"10.7","cpu_average":"10","mem":"3.8"},"32823":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.86.214/live0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Deck@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"9.8","cpu_average":"9","mem":"2.7"},"139011":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"NVIDIA GeForce GTX 1080":{"detection_start":0.0,"inference_speed":9.83,"pid":469}},"gpu_usages":{"NVIDIA GeForce GTX 1080":{"dec":"7.0%","enc":"0.0%","gpu":"2.0%","mem":"18.88%"}},"processes":{"go2rtc":{"pid":105},"logger":{"pid":458},"recording":{"pid":460}},"service":{"last_updated":1711043799,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":242.0,"mount_type":"tmpfs","total":256.0,"used":14.0},"/media/frigate/clips":{"free":5351630.2,"mount_type":"zfs","total":6523052.9,"used":1171422.6},"/media/frigate/recordings":{"free":5351630.2,"mount_type":"zfs","total":6523052.9,"used":1171422.6},"/tmp/cache":{"free":1006.7,"mount_type":"tmpfs","total":1024.0,"used":17.3}},"temperatures":{},"uptime":22081,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

ReoLink & Eufy cameras

### Any other information that may be helpful

I am running on TrueNAS Scale
