### DISCUSSION TITLE
[HW Accel Support]: Installed Nvidia-based GPU, cannot get hw_accel to work

### DISCUSSION THREAD

**Discussion by Juggler00** [blakeblackshear/frigate#10594] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Running Ubuntu server v20.04.6 and Docker v26.0.0. and have Frigate working with my 5x Dahua cameras. I have just installed an Nvidia-based GPU (GeForce GT 1030 chipset) and would like to leverage hardware acceleration of the the card. I have verified that my Nvidia drivers are properly installed:
```
$ nvidia-smi
Thu Mar 21 15:19:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GT 1030         Off | 00000000:02:00.0 Off |                  N/A |
| 32%   37C    P0              N/A /  30W |      0MiB /  2048MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: IP_ADDRESS

detectors:
  coral:
    type: edgetpu
    device: usb
    
birdseye:
  mode: motion

ffmpeg:
  hwaccel_args: preset-nvidia-h264

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 14
    mode: all

snapshots:
  enabled: True
  timestamp: True
  # crop: False
  retain:
    default: 7

go2rtc:
  streams:
    driveway:
      - rtsp://USERNAME:PASSWORD@192.168.60.98:554
      - "ffmpeg:driveway#audio=opus"
    driveway_sub:
      - rtsp://USERNAME:PASSWORD@192.168.60.98:554/cam/realmonitor?channel=1&subtype=2
  webrtc:
    candidates:
      - 192.168.2.10:8555
      - TAILSCALE_IP:8555
      - stun:8555    

cameras:
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - bicycle
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.2
    restart: unless-stopped
    container_name: frigate
    shm_size: "128mb"
    networks:
      public:
    ports:
      - 5000:5000
      - 1935:1935
      - 1984:1984
      - 8554:8554
      - 8555:8555
    environment:
      - TZ=America/Toronto
    devices:
      - /dev/bus/usb:/dev/bus/usb 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config/:/config/
      - /hdd5tbsingle/frigate:/media/frigate
```

### Relevant log output

```shell
frigate  | 2024-03-21 15:12:24.428816668  [INFO] Preparing Frigate...
frigate  | 2024-03-21 15:12:24.430546816  [INFO] Starting NGINX...
frigate  | 2024-03-21 15:12:24.435114249  [INFO] Preparing new go2rtc config...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-03-21 15:12:24.446464954  [INFO] Starting Frigate...
frigate  | 2024-03-21 15:12:24.754238209  2024/03/21 15:12:24 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.10, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.2.10:5000"
frigate  | 2024-03-21 15:12:24.807988805  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
frigate  | 2024-03-21 15:12:24.856600450  [INFO] Starting go2rtc...
frigate  | 2024-03-21 15:12:24.984123168  15:12:24.984 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-03-21 15:12:24.984846797  15:12:24.984 INF [rtsp] listen addr=:8554
frigate  | 2024-03-21 15:12:24.984870244  15:12:24.984 INF [api] listen addr=:1984
frigate  | 2024-03-21 15:12:24.985563525  15:12:24.985 INF [webrtc] listen addr=:8555
frigate  | 2024-03-21 15:12:26.270162920  [2024-03-21 15:12:26] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-03-21 15:12:26.291973233  [rtsp @ 0x3e72f80] method DESCRIBE failed: 404 Not Found
frigate  | 2024-03-21 15:12:26.292481378  [ERROR:0@0.778] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
frigate  | 2024-03-21 15:12:26.292486528  
frigate  | 2024-03-21 15:12:26.292499902  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://127.0.0.1:8554/driveway_sub in function 'icvExtractPattern'
frigate  | 2024-03-21 15:12:26.292504575  
frigate  | 2024-03-21 15:12:26.292507525  
frigate  | 2024-03-21 15:12:26.319761750  [2024-03-21 15:12:26] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-03-21 15:12:26.325252209  [2024-03-21 15:12:26] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-03-21 15:12:26.331315857  [2024-03-21 15:12:26] frigate.app                    INFO    : Recording process started: 728
frigate  | 2024-03-21 15:12:26.334818483  [2024-03-21 15:12:26] frigate.app                    INFO    : go2rtc process pid: 89
frigate  | 2024-03-21 15:12:26.365850610  [2024-03-21 15:12:26] detector.coral                 INFO    : Starting detection process: 737
frigate  | 2024-03-21 15:12:26.366507146  [2024-03-21 15:12:26] frigate.app                    INFO    : Output process started: 738
frigate  | 2024-03-21 15:12:26.385082194  [2024-03-21 15:12:26] frigate.app                    INFO    : Camera processor started for driveway: 746
frigate  | 2024-03-21 15:12:26.393319137  [2024-03-21 15:12:26] frigate.app                    INFO    : Capture process started for driveway: 749
frigate  | 2024-03-21 15:12:26.415678552  [2024-03-21 15:12:26] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
frigate  | 2024-03-21 15:12:26.415939610  [2024-03-21 15:12:26] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-03-21 15:12:29.037188666  [2024-03-21 15:12:26] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate  | 2024-03-21 15:12:29.043404178  [2024-03-21 15:12:29] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate  | 2024-03-21 15:12:34.430071045  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-03-21 15:12:46.351050465  [2024-03-21 15:12:46] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for driveway. Keeping the 6 most recent segments out of 7 and discarding the rest...
frigate  | 2024-03-21 15:12:46.475259601  [2024-03-21 15:12:46] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
frigate  | 2024-03-21 15:12:46.475439969  [2024-03-21 15:12:46] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-03-21 15:12:46.475633074  [2024-03-21 15:12:46] ffmpeg.driveway.detect         ERROR   : [rtsp @ 0x56004db94d40] method DESCRIBE failed: 404 Not Found
frigate  | 2024-03-21 15:12:46.475814011  [2024-03-21 15:12:46] ffmpeg.driveway.detect         ERROR   : rtsp://127.0.0.1:8554/driveway_sub: Server returned 404 Not Found
frigate  | 2024-03-21 15:12:46.494896815  [2024-03-21 15:12:46] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
frigate  | 2024-03-21 15:12:46.495038638  [2024-03-21 15:12:46] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-03-21 15:12:56.350595967  [2024-03-21 15:12:56] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for driveway. Keeping the 6 most recent segments out of 7 and discarding the rest...
frigate  | 2024-03-21 15:12:56.491696441  [2024-03-21 15:12:56] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
frigate  | 2024-03-21 15:12:56.491950989  [2024-03-21 15:12:56] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

```shell
root@9bdb5dac0e93:/opt/frigate# ffprobe rtsp://USERNAME:PASSWORD@192.168.60.98:554
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:i2zunXGOuxR4u08@192.168.60.98:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.041000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 15 fps, 100 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua IPC-HDW5231R-Z

### Any other information that may be helpful

If I omit the "ffmpeg" section of the config, everything works except for hardware acceleration.

**Comment by NickM-27** [comment]
The logs being shown are an error from go2rtc, nothing to do with the GPU. I'd suggest checking go2rtc logs

**Reply by Juggler00** [reply]
I've looked in the go2rtc logs and there are no obvious problems. Can you see anything here to help direct me?
```
2024-03-21 20:13:51.295270597  [INFO] Preparing new go2rtc config...
2024-03-21 20:13:51.703042420  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-03-21 20:13:51.772797596  [INFO] Starting go2rtc...
2024-03-21 20:13:51.868310568  20:13:51.868 INF go2rtc version 1.8.4 linux/amd64
2024-03-21 20:13:51.869289167  20:13:51.869 INF [api] listen addr=:1984
2024-03-21 20:13:51.869344906  20:13:51.869 INF [rtsp] listen addr=:8554
2024-03-21 20:13:51.870318962  20:13:51.870 INF [webrtc] listen addr=:8555
2024-03-21 20:14:01.287631589  [INFO] Starting go2rtc healthcheck service...
```

**Reply by Lensters** [reply]
Looks to me like the audio stream is the culprit.  Try turning the audio off and seeing if that doesn't fix it.

**Reply by Juggler00** [reply]
I tried commenting out the two references to audio, one in the go2rtc section and the other in the cameras section. I'm still seeing the same errors. Below is my modified config and frigate logs. The go2rtc logs are not showing any errors.

```
ffmpeg:
  hwaccel_args: preset-nvidia-h264

...

go2rtc:
  streams:
    driveway:
      - rtsp://USERNAME:PASSWORD@192.168.60.98:554
#       - "ffmpeg:driveway#audio=opus"
    driveway_sub:
      - rtsp://USERNAME:PASSWORD@192.168.60.98:554/cam/realmonitor?channel=1&subtype=2

...

cameras:
  driveway:
    ffmpeg:
#       output_args:
#         record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - bicycle
```
```
frigate  | 2024-03-22 06:46:10.306048175  [INFO] Preparing Frigate...
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-03-22 06:46:10.308885728  [INFO] Starting NGINX...
frigate  | 2024-03-22 06:46:10.311624128  [INFO] Preparing new go2rtc config...
frigate  | 2024-03-22 06:46:10.319410732  [INFO] Starting Frigate...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-03-22 06:46:10.679872881  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
frigate  | 2024-03-22 06:46:10.723080712  [INFO] Starting go2rtc...
frigate  | 2024-03-22 06:46:10.770253991  2024/03/22 06:46:10 [error] 146#146: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.10, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.2.10:5000"
frigate  | 2024-03-22 06:46:10.859514615  06:46:10.859 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-03-22 06:46:10.860229293  06:46:10.860 INF [api] listen addr=:1984
frigate  | 2024-03-22 06:46:10.860260833  06:46:10.860 INF [rtsp] listen addr=:8554
frigate  | 2024-03-22 06:46:10.861218072  06:46:10.861 INF [webrtc] listen addr=:8555
frigate  | 2024-03-22 06:46:12.142308998  [2024-03-22 06:46:12] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-03-22 06:46:13.877522678  2024/03/22 06:46:13 [error] 145#145: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 100.102.184.87, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "docker.home.srask.ca:5000"
frigate  | 2024-03-22 06:46:13.877629421  100.102.184.87 - - [22/Mar/2024:06:46:13 -0400] "GET /ws HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "-"
frigate  | 2024-03-22 06:46:15.305739281  2024/03/22 06:46:15 [error] 148#148: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-22 06:46:15.746122987  2024/03/22 06:46:15 [error] 146#146: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.10, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.2.10:5000"
frigate  | 2024-03-22 06:46:18.250936543  [2024-03-22 06:46:18] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-03-22 06:46:18.257927818  [2024-03-22 06:46:18] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-03-22 06:46:18.265393099  [2024-03-22 06:46:18] frigate.app                    INFO    : Recording process started: 753
frigate  | 2024-03-22 06:46:18.269504830  [2024-03-22 06:46:18] frigate.app                    INFO    : go2rtc process pid: 89
frigate  | 2024-03-22 06:46:18.300087508  [2024-03-22 06:46:18] detector.coral                 INFO    : Starting detection process: 762
frigate  | 2024-03-22 06:46:20.307534216  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-03-22 06:46:20.971209173  [2024-03-22 06:46:18] frigate.app                    INFO    : Output process started: 764
frigate  | 2024-03-22 06:46:20.971446892  [2024-03-22 06:46:18] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate  | 2024-03-22 06:46:20.976550793  [2024-03-22 06:46:18] frigate.app                    INFO    : Camera processor started for driveway: 786
frigate  | 2024-03-22 06:46:20.976794332  [2024-03-22 06:46:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate  | 2024-03-22 06:46:20.976989108  [2024-03-22 06:46:18] frigate.app                    INFO    : Capture process started for driveway: 791
frigate  | 2024-03-22 06:46:24.656687095  [2024-03-22 06:46:24] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
frigate  | 2024-03-22 06:46:24.656994550  [2024-03-22 06:46:24] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
```
