### DISCUSSION TITLE
[Config Support]: Reolink doorbell 2 way audio. Mic not working

### DISCUSSION THREAD

**Discussion by AussiSG** [blakeblackshear/frigate#10595] [Config Support] [answered]
### Describe the problem you are having

I've setup a reolink doorbell over PoE.
Streams/detection/records seem to be working fine. 

But when wanting to have a 2-way communication to work. I can only hear the sounds coming from the doorbell.
When trying to use the mic function over my phone , no sound on the bell.

Trying this with a frigate lovelace card in HomeAssistant.
![image](https://github.com/blakeblackshear/frigate/assets/56043947/cd042b0f-619b-43fa-923b-d2487f3f8143)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  user: USER
  password: USER

ffmpeg:
  hwaccel_args: preset-vaapi

#  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
#  output_args:
#    # Optional: output args for detect streams (default: shown below)
#    detect: -f rawvideo -pix_fmt yuv420p
#    # Optional: output args for record streams (default: shown below)
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
#    # Optional: output args for rtmp streams (default: shown below)
#    rtmp: -c copy -f flv  

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    front1: # <- for RTSP streams
      - rtsp://192.168.0.15:554/ # <- stream which supports video & aac audio
    doorbell: 
      - "ffmpeg:http://192.168.0.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=USER&password=PASS#video=copy#audio=copy#audio=opus"
      - rtsp://USER:PASS@192.168.0.21:554/h264Preview_01_sub
    doorbell_sub:  
      - "ffmpeg:http://192.168.0.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=USER&password=PASS"
    doorbell_snapshot:
      - onvif://USER:PASS@192.168.0.21:8000?subtype=MediaProfile00000&snapshot

  webrtc:
    candidates:
      - 192.168.0.12:8555
  log:
    exec: trace
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""


cameras:
  front1:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/front1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg 
      output_args:
              rtmp: -c:v libx264 -an -f flv
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
    # Optional: Record configuration
    # NOTE: Can be overridden at the camera level
    record:
      # Optional: Enable recording (default: shown below)
      # WARNING: If recording is disabled in the config, turning it on via
      #          the UI or MQTT later will have no effect.
      # WARNING: Frigate does not currently support limiting recordings based
      #          on available disk space automatically. If using recordings,
      #          you must specify retention settings for a number of days that
      #          will fit within the available disk space of your drive or Frigate
      #          will crash.
      enabled: True
      # Optional: Number of minutes to wait between cleanup runs (default: shown below)
      # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
      expire_interval: 60
      # Optional: Retention settings for recording
      retain:
        # Optional: Number of days to retain recordings regardless of events (default: shown below)
        # NOTE: This should be set to 0 and retention should be defined in events section below
        #       if you only want to retain recordings of events.
        days: 0
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - car
          - person
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
          # Optional: Mode for retention. (default: shown below)
          #   all - save all recording segments for events regardless of activity
          #   motion - save all recordings segments for events with any detected motion
          #   active_objects - save all recording segments for event with active/moving objects
          #
          # NOTE: If the retain mode for the camera is more restrictive than the mode configured
          #       here, the segments will already be gone by the time this mode is applied.
          #       For example, if the camera retain mode is "motion", the segments without motion are
          #       never stored, so setting the mode to "all" here won't bring them back.
          mode: motion
          # Optional: Per object retention days
          objects:
            person: 15


################### Doorbell Camera
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect      
      output_args:
          record: preset-record-generic-audio-copy
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
    # Optional: Record configuration
    # NOTE: Can be overridden at the camera level
    record:
      # Optional: Enable recording (default: shown below)
      # WARNING: If recording is disabled in the config, turning it on via
      #          the UI or MQTT later will have no effect.
      # WARNING: Frigate does not currently support limiting recordings based
      #          on available disk space automatically. If using recordings,
      #          you must specify retention settings for a number of days that
      #          will fit within the available disk space of your drive or Frigate
      #          will crash.
      enabled: True
      # Optional: Number of minutes to wait between cleanup runs (default: shown below)
      # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
      expire_interval: 60
      # Optional: Retention settings for recording
      retain:
        # Optional: Number of days to retain recordings regardless of events (default: shown below)
        # NOTE: This should be set to 0 and retention should be defined in events section below
        #       if you only want to retain recordings of events.
        days: 0
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - car
          - person
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
          # Optional: Mode for retention. (default: shown below)
          #   all - save all recording segments for events regardless of activity
          #   motion - save all recordings segments for events with any detected motion
          #   active_objects - save all recording segments for event with active/moving objects
          #
          # NOTE: If the retain mode for the camera is more restrictive than the mode configured
          #       here, the segments will already be gone by the time this mode is applied.
          #       For example, if the camera retain mode is "motion", the segments without motion are
          #       never stored, so setting the mode to "all" here won't bring them back.
          mode: motion
          # Optional: Per object retention days
          objects:
            person: 15
```

### Relevant log output

```shell
Think this is related to another camera which has doge WiFi connection:
Frigate log:

2024-03-21 19:40:12.627237490  [2024-03-21 19:40:12] frigate.video                  ERROR   : front1: Unable to read frames from ffmpeg process.
2024-03-21 19:40:12.628474188  [2024-03-21 19:40:12] frigate.video                  ERROR   : front1: ffmpeg process is not running. exiting capture thread...
2024-03-21 19:40:16.095078053  [2024-03-21 19:40:16] watchdog.front1                ERROR   : Ffmpeg process crashed unexpectedly for front1.
2024-03-21 19:40:16.095081963  [2024-03-21 19:40:16] watchdog.front1                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-03-21 19:40:16.095083633  [2024-03-21 19:40:16] ffmpeg.front1.detect           ERROR   : [rtsp @ 0x555b37192100] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2024-03-21 19:40:16.095085178  [2024-03-21 19:40:16] ffmpeg.front1.detect           ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-03-21 19:40:16.095086519  [2024-03-21 19:40:16] ffmpeg.front1.detect           ERROR   : Output file #0 does not contain any stream

Alot of frameworks passing in the logs
Go2RTC:
frame=46191 fps= 15 q=-1.0 size=N/A time=00:52:14.52 bitrate=N/A speed=   1x    
frame=46199 fps= 15 q=-1.0 size=N/A time=00:52:15.04 bitrate=N/A speed=   1x 

This seems to be relevant to the doorbell, this seems to be the trying with my mobile phone
Nginx log:

2024-03-21 19:56:54.608727974  192.168.0.11 - - [21/Mar/2024:19:56:54 +0000] "GET /live/mse/api/ws?src=doorbell&authSig=xxxxx HTTP/1.1" 101 264292 "-" "Mozilla/5.0 (Linux; Android 14; CPH2399 Build/UKQ1.230924.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36 Home Assistant/2024.1.5-12102 (Android 14; CPH2399)" "192.168.0.2, 192.168.0.12"
2024-03-21 19:56:57.387591539  192.168.0.11 - - [21/Mar/2024:19:56:57 +0000] "GET /live/mse/api/ws?src=front1&authSig=xxxx HTTP/1.1" 101 118852 "-" "Mozilla/5.0 (Linux; Android 14; CPH2399 Build/UKQ1.230924.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36 Home Assistant/2024.1.5-12102 (Android 14; CPH2399)" "192.168.0.2, 192.168.0.12"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
should check stream info from system page top right while the mic is active

**Comment by AussiSG** [comment]
Okido. What should I notice there? There's quite alot of data on it :) Here I've activated the microphone:

I see something with audio send only and receive only ?

```
{
  "doorbell": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, ANY",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:43306",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
        "send": 120600789,
        "senders": [
          "96 H264, bytes=118369646, receivers=1",
          "97 MPEG4-GENERIC/16000, bytes=889719, receivers=1"
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac",
        "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
      },
      {
        "medias": [
          "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
          "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML",
          "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
        ],
        "receivers": [
          "0 PCMU/8000, bytes=417440, senders=1"
        ],
        "recv": 471720,
        "remote_addr": "udp4 host 192.168.0.94:64293",
        "send": 29047899,
        "senders": [
          "102 H264, bytes=28189669, receivers=1",
          "111 OPUS/48000/2, bytes=524813, receivers=1"
        ],
        "type": "WebRTC/WebSocket async passive consumer",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H.264 High 5.1",
          "audio, recvonly, MPEG4-GENERIC/16000",
          "audio, recvonly, OPUS/48000/2"
        ],
        "receivers": [
          "96 H264, bytes=118369646, senders=2",
          "97 MPEG4-GENERIC/16000, bytes=889719, senders=1",
          "98 OPUS/48000/2, bytes=2263840, senders=1"
        ],
        "recv": 122669025,
        "remote_addr": "127.0.0.1:43312",
        "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
        "type": "RTSP passive producer",
        "url": "rtsp://127.0.0.1:8554/fd347cf0fc0fb7f5c019cddd035598e0",
        "user_agent": "ffmpeg/go2rtc"
      },
      {
        "medias": [
          "video, recvonly, H.264 High 5.1",
          "audio, recvonly, MPEG4-GENERIC/16000",
          "audio, sendonly, PCMU/8000"
        ],
        "recv": 548,
        "remote_addr": "192.168.0.21:554",
        "sdp": "v=0\r\no=- 1710787391283499 1 IN IP4 192.168.0.21\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
        "send": 459184,
        "senders": [
          "0 PCMU/8000, bytes=417440, receivers=1"
        ],
        "type": "RTSP active producer",
        "url": "rtsp://192.168.0.21/Preview_01_sub/",
        "user_agent": "go2rtc/1.8.4"
      }
    ]
  },
  "doorbell_snapshot": {
    "consumers": null,
    "producers": [
      {
        "url": "onvif://*:*@192.168.0.21:8000?subtype=MediaProfile00000&snapshot"
      }
    ]
  },
  "doorbell_sub": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, ANY"
        ],
        "remote_addr": "127.0.0.1:43278",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\n",
        "send": 35871406,
        "senders": [
          "96 H264, bytes=35441486, receivers=1"
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/doorbell_sub?video=copy",
        "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H.264 High 5.1",
          "audio, recvonly, MPEG4-GENERIC/16000"
        ],
        "receivers": [
          "96 H264, bytes=35441486, senders=1",
          "97 MPEG4-GENERIC/16000, bytes=887988, senders=0"
        ],
        "recv": 36662918,
        "remote_addr": "127.0.0.1:43320",
        "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\n",
        "type": "RTSP passive producer",
        "url": "rtsp://127.0.0.1:8554/7581a66b6f29e8be86890d554ce55035",
        "user_agent": "ffmpeg/go2rtc"
      }
    ]
  },
  "front1": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264, H265",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:43292",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1\r\na=control:trackID=0\r\n",
        "send": 16475565,
        "senders": [
          "96 H264, bytes=16266765, receivers=1"
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/front1",
        "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
      },
      {
        "medias": [
          "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
          "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
        ],
        "remote_addr": "udp4 prflx 192.168.0.94:55648 related :0",
        "send": 4816066,
        "senders": [
          "102 H264, bytes=4761846, receivers=1"
        ],
        "type": "WebRTC/WebSocket async passive consumer",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H264"
        ],
        "receivers": [
          "96 H264, bytes=16266765, senders=2"
        ],
        "recv": 16423365,
        "remote_addr": "192.168.0.15:554",
        "sdp": "v=0\r\no=StreamingServer 3331435948 1116907222000 IN IP4 192.168.0.15\r\ns=h264.mp4\r\ni=TAS-Tech Live Cast\r\nc=IN IP4 192.168.0.15\r\nt=0 0\r\na=recvonly\r\na=range:npt=now-\r\nm=video 0 RTP/AVP 96\r\na=control:rtsp://192.168.0.15:554/0/video0\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1\r\na=framesize:96 1280-720\r\n\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://192.168.0.15:554/",
        "user_agent": "go2rtc/1.8.4"
      }
    ]
  }
}
```

**Reply by NickM-27** [reply]
seems like this might be a doorbell issue, we can see that data is indeed being sent to the doorbell 

```
      {
        "medias": [
          "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
          "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML",
          "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
        ],
        "receivers": [
          "0 PCMU/8000, bytes=417440, senders=1"
        ],
        "recv": 471720,
        "remote_addr": "udp4 host 192.168.0.94:64293",
        "send": 29047899,
        "senders": [
          "102 H264, bytes=28189669, receivers=1",
          "111 OPUS/48000/2, bytes=524813, receivers=1"
        ],
        "type": "WebRTC/WebSocket async passive consumer",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
      }
```

**Reply by AussiSG** [reply]
I see, thanks for pointing that out. 

That's strange then because I can communicate (2ways) through the reolink app.... 
but frigate doesnt put the sound through reolink doorbell it seems

**Reply by NickM-27** [reply]
the reolink app does not use the same mechanism that frigate / go2rtc must, so there could be any number of issues along the way

**Comment by AussiSG** [comment]
After adding the 

```
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-cop
    **live:
      stream_name: doorbell**   
```

it seems I'm getting some extra errors in the logs:
```
2024-03-22 15:24:36.503598949  [2024-03-22 15:24:36] watchdog.doorbell              ERROR   : No new recording segments were created for doorbell in the last 120s. restarting the ffmpeg record process...
2024-03-22 15:24:36.508015854  [2024-03-22 15:24:36] watchdog.doorbell              INFO    : Terminating the existing ffmpeg process...
2024-03-22 15:24:36.508019740  [2024-03-22 15:24:36] watchdog.doorbell              INFO    : Waiting for ffmpeg to exit gracefully...
```

**Reply by supermarkert** [reply]
I get those errors all the time, but it otherwise seems to work as intended (all audio works during live/recording, including 2-way audio). I assume they're temporary Wifi issues. I'm hoping to wire it in with Ethernet in the next 1-2 weeks to improve the situation.

**Reply by AussiSG** [reply]
Mine is powered over PoE , but I see I made a typo in the config file..... 
This resolved the errors but sadly enough didnt fixed the mic problem :(

```
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: **preset-record-generic-audio-cop*y* <---------- the y got deleted hehe
     live:
      stream_name: doorbell
```
