### DISCUSSION TITLE
[Config Support]: publish inside go2rtc is not detected

### DISCUSSION THREAD

**Discussion by morenod** [blakeblackshear/frigate#10596] [Config Support]
### Describe the problem you are having

I have a camera capture working with go2rtc and I can see it as frigate camera, but Im trying to publish it as a youtube stream, but I dont see any reference to it on the logs, and if I click on the system > streams info link, I dont see any reference neither

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
go2rtc:
  publish:
    camara_11:
      - rtmps://a.rtmps.youtube.com/live2/xxxxxxx
      - rtmps://b.rtmps.youtube.com/live2?backup=1/xxxxxx
  streams:
    camara_11: # BirdCAM
      - http://esp32-birdcam.local:8080
      - ffmpeg:camara_11#video=h264#hardware


cameras:
  birdcam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara_11
          roles:
            - detect
            - record
```

### Relevant log output

```shell
No logs references to that publish. Searching for youtube hostname do not output any result
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

**Comment by NickM-27** [comment]
can you explain what you mean by "publish" ?

**Reply by morenod** [reply]
Based on https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#publish-stream, you can send the camera stream to a URL using go2rtc.

I have configured in the same way that the example, but youtube do not receive any stream, and I dont see any reference to it on the log, so I think that the parameter is not being read

**Reply by NickM-27** [reply]
that would be a question for go2rtc then not frigate

**Reply by morenod** [reply]
Well, it could be an error on go2rtc if there was a failure on the execution of go2rtc, bit I think that go2rtc is not even launched, as there is no trace on the log related to it. The configuration file is the frigate configuration file, but it is ok, I will open a similar issue on the go2rtc project, but can we investigate on this one if the go2rtc process is launched when the entry publish is on the file?

**Reply by NickM-27** [reply]
> but can we investigate on this one if the go2rtc process is launched when the entry publish is on the file?

Go2rtc is always running no matter what, it doesn't matter what is in your config

**Comment by rwlove** [comment]
I can't seem to get this working either. I am trying to stream to youtube. I'm running `0.16.0-1fa7ce5` I'm not getting any relevant logs either.

```
go2rtc:
  webrtc:
    candidates:
      - 10.10.40.102:1984
      - stun:1984
  log:
    publish: debug
  publish:
    birdcam: rtmp://a.rtmp.youtube.com/live2/REDACTED
  streams:
    birdcam:
      - rtsp://birdcam/user=admin_password={FRIGATE_BIRDCAM_RTSP_PASSWORD}_channel=1_stream=0.sdp?real_stream
```
