### DISCUSSION TITLE
[Support]: Keeps detecting stationary cars

### DISCUSSION THREAD

**Discussion by TheLion** [blakeblackshear/frigate#10604] [General Support]
### Describe the problem you are having

Hi,

I have got a camera set up in my carport, which was a view on the street.

![image](https://github.com/blakeblackshear/frigate/assets/3755011/c8d71c54-e512-49af-b2e8-97cd0cf70715)

There are always parked cars on the left. Frigate keeps detecting and recording the stationary cars, resulting in a lot of false positives and lots of videofiles on disk.

I tried Motion Boxes, Motion Masks and Zones to prevent this, but Frigate keeps detecting and recording.

I'm probably doing something wrong here.

Any tips?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 192.168.xxx.xxx
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: '{FRIGATE_MQTT_USER}'
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

go2rtc:
  streams:
    rtsp_3D_Printers:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    #rtsp_3D_Printers_sub:
    #  - rtsp://admin:password@192.168.xxx.xxx:554/h264Preview_01_sub # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Achtertuin:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Achtertuin_sub:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_sub # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Carport:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Carport_sub:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_sub # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Woonkamer:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Woonkamer_sub:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_sub # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    rtsp_Zolder:
      - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    #rtsp_Zolder_sub:
    #  - rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_sub # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus

#detectors:
#  ov:
#    type: openvino
#    device: GPU
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml

detectors:
 coral:
  type: edgetpu
  device: usb

#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


cameras:
  3D_Printers:
    ffmpeg:
      inputs:
        #- path: rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main
      - path: rtsp://127.0.0.1:8554/rtsp_3D_Printers
        input_args: preset-rtsp-restream
    detect:
      enabled: false
    record:
      enabled: false
    snapshots:
      enabled: false
    live:
      stream_name: rtsp_3D_Printers
  Achtertuin:
    ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/rtsp_Achtertuin
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/rtsp_Achtertuin_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
    live:
      stream_name: rtsp_Achtertuin
  Carport:
    #record:
      #events:
        #required_zones:
          #- zone_0
    ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/rtsp_Carport
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/rtsp_Carport_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
    live:
      stream_name: rtsp_Carport
    #motion:
      #mask: 357,105,466,0,366,0,277,24,177,61,180,112
    zones:
      alles_behalve_parkeerplaatsen:
        coordinates: 142,37,0,38,0,352,432,352,439,317,640,315,640,0,478,0,426,51,406,66,391,79,369,123,183,128,186,0,142,0
        objects:
         - person
         - car
         - bicycle
         - motorcycle
         - bird
         - cat
         - dog
      parkeerplaatsen:
        coordinates: 372,117,179,119,181,40,182,0,355,0,475,0
        objects:
         - person
         - bicycle
         - motorcycle
         - bird
         - cat
         - dog
  Woonkamer:
    ffmpeg:
      inputs:
        #- path: rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/rtsp_Woonkamer
          input_args: preset-rtsp-restream
          roles:
            - record
        #- path: rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_sub
        - path: rtsp://127.0.0.1:8554/rtsp_Woonkamer_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: rtsp_Woonkamer
  Zolder:
    ffmpeg:
      inputs:
  #      #- path: rtsp://user:password@192.168.xxx.xxx:554/h264Preview_01_main
      - path: rtsp://127.0.0.1:8554/rtsp_Zolder
      input_args: preset-rtsp-restream
    detect:
      enabled: false
    record:
      enabled: false
    snapshots:
      enabled: false
    live:
      stream_name: rtsp_Zolder

detect:
  stationary:
    interval: 10
    threshold: 50
  enabled: true
  #width: 640
  #height: 480
snapshots:
  enabled: True
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bird
    - cat
    - dog
record:
  enabled: True
  retain: 
    days: 14
    mode: motion
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
          - person
          - car
          - bicycle
          - motorcycle
          - bird
          - cat
          - dog
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 30
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      #objects:
        #person: 15
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
# Optional: Telemetry configuration
telemetry:
  # Optional: Enabled network interfaces for bandwidth stats monitoring (default: empty list, let nethogs search all)
  #network_interfaces:
  #  - eth
  #  - enp
  #  - eno
  #  - ens
  #  - wl
  #  - lo
  # Optional: Configure system stats
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: True
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: True
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: True
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
No relevant log output
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2304x1296
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x352
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Frigate stats

```json
bandwidth_usages	
87	
bandwidth	2063.9
cameras	
3D_Printers	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	422
detection_enabled	0
detection_fps	0
ffmpeg_pid	428
pid	414
process_fps	5.1
skipped_fps	0
Achtertuin	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	426
detection_enabled	1
detection_fps	1.6
ffmpeg_pid	698
pid	415
process_fps	5.1
skipped_fps	0
Carport	
audio_dBFS	0
audio_rms	0
camera_fps	5.2
capture_pid	429
detection_enabled	1
detection_fps	6.9
ffmpeg_pid	446
pid	416
process_fps	5.2
skipped_fps	0
Woonkamer	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	432
detection_enabled	1
detection_fps	3.8
ffmpeg_pid	712
pid	418
process_fps	5.1
skipped_fps	0
Zolder	
audio_dBFS	0
audio_rms	0
camera_fps	5
capture_pid	436
detection_enabled	0
detection_fps	0
ffmpeg_pid	481
pid	421
process_fps	5
skipped_fps	0
cpu_usages	
1	
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
15	
cmdline	"s6-supervise s6-linux-init-shutdownd"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
16	
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
24	
cmdline	"s6-supervise nginx-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
25	
cmdline	"s6-supervise frigate-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
26	
cmdline	"s6-supervise nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
27	
cmdline	"s6-supervise go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
28	
cmdline	"s6-supervise go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
29	
cmdline	"s6-supervise frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
30	
cmdline	"s6-supervise s6rc-fdholder"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
31	
cmdline	"s6-supervise s6rc-oneshot-runner"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
32	
cmdline	"s6-supervise go2rtc-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
40	
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
42	
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
78	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
81	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
87	
cmdline	"/config/go2rtc -config=/dev/shm/go2rtc.yaml"
cpu	"7.6"
cpu_average	"6"
mem	"0.1"
89	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
108	
cmdline	"bash ./run.user go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
115	
cmdline	"python3 -u -m frigate"
cpu	"3.7"
cpu_average	"2"
mem	"1.6"
123	
cmdline	"nginx: master process nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
133	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
134	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
135	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
136	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
138	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
139	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
140	
cmdline	"nginx: cache manager process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
357	
cmdline	"frigate.logger       "
cpu	"0.0"
cpu_average	"0"
mem	"0.3"
376	
cmdline	"frigate.recording_manager"
cpu	"0.3"
cpu_average	"1"
mem	"0.4"
385	
cmdline	"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)"
cpu	"0.3"
cpu_average	"0"
mem	"0.0"
386	
cmdline	"frigate.detector.coral"
cpu	"4.2"
cpu_average	"4"
mem	"0.4"
387	
cmdline	"frigate.output       "
cpu	"1.3"
cpu_average	"0"
mem	"0.4"
392	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
395	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
396	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
397	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
398	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
399	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
414	
cmdline	"frigate.process:3D_Printers"
cpu	"0.3"
cpu_average	"0"
mem	"0.7"
415	
cmdline	"frigate.process:Achtertuin"
cpu	"1.1"
cpu_average	"0"
mem	"0.7"
416	
cmdline	"frigate.process:Carport"
cpu	"3.4"
cpu_average	"3"
mem	"0.7"
418	
cmdline	"frigate.process:Woonkamer"
cpu	"2.1"
cpu_average	"0"
mem	"0.7"
421	
cmdline	"frigate.process:Zolder"
cpu	"0.3"
cpu_average	"0"
mem	"0.7"
422	
cmdline	"frigate.capture:3D_Printers"
cpu	"4.2"
cpu_average	"3"
mem	"0.7"
426	
cmdline	"frigate.capture:Achtertuin"
cpu	"0.5"
cpu_average	"0"
mem	"0.7"
428	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_3D_Printers -r 5 -vf vpp_qsv=framerate=5:w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"5.0"
cpu_average	"4"
mem	"0.3"
429	
cmdline	"frigate.capture:Carport"
cpu	"0.3"
cpu_average	"0"
mem	"0.7"
432	
cmdline	"frigate.capture:Woonkamer"
cpu	"0.3"
cpu_average	"0"
mem	"0.7"
436	
cmdline	"frigate.capture:Zolder"
cpu	"3.4"
cpu_average	"2"
mem	"0.7"
446	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Carport_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=352:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"0.5"
cpu_average	"0"
mem	"0.1"
467	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Carport -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Carport@%Y%m%d%H%M%S%z.mp4"
cpu	"0.3"
cpu_average	"0"
mem	"0.1"
474	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Achtertuin -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Achtertuin@%Y%m%d%H%M%S%z.mp4"
cpu	"0.3"
cpu_average	"0"
mem	"0.1"
481	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Zolder -r 5 -vf vpp_qsv=framerate=5:w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"3.7"
cpu_average	"2"
mem	"0.2"
503	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Woonkamer -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Woonkamer@%Y%m%d%H%M%S%z.mp4"
cpu	"0.3"
cpu_average	"0"
mem	"0.1"
698	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Achtertuin_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=352:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"0.5"
cpu_average	"0"
mem	"0.1"
712	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rtsp_Woonkamer_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=352:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"0.5"
cpu_average	"0"
mem	"0.1"
1181	
cmdline	"sleep 30s"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
detection_fps	12.3
detectors	
coral	
detection_start	0
inference_speed	7.88
pid	386
gpu_usages	
intel-qsv	
gpu	"7.42%"
mem	"-%"
processes	
go2rtc	
pid	87
logger	
pid	357
recording	
pid	376
service	
last_updated	1711103053
latest_version	"0.13.2"
storage	
/dev/shm	
free	159
mount_type	"tmpfs"
total	175
used	16
/media/frigate/clips	
free	521818.6
mount_type	"ext4"
total	754850.4
used	194615.9
/media/frigate/recordings	
free	521818.6
mount_type	"ext4"
total	754850.4
used	194615.9
/tmp/cache	
free	521818.6
mount_type	"overlay"
total	754850.4
used	194615.9
temperatures	{}
uptime	207
version	"0.13.2-6476f8a"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-410W
