### DISCUSSION TITLE
[Config Support]: Home assistant web live view OK, companion app only latest.jpg per second

### DISCUSSION THREAD

**Discussion by ronbruins** [blakeblackshear/frigate#10601] [Config Support]
### Describe the problem you are having

I configured go2rtc for live view in Home Assistant and in Frigate MSE works fine. Adding the frigate-card in HA and using the live view, work fine and it shows the live MSE stream.

However in the companion app (iOS) it still only shows the 1fps latest.jpg image.
It looks like it tries, as the url for use show up (like via webbrowser, but then it falls back on fastest.jpg images

### Version

latest

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 123.123.123.35
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ron
  password: PASSWORD
  
go2rtc:
  log:
    format: text
    exec: trace
  streams:
    balkon:
      - rtsp://USER:PASSWORD@123.123.123.123:554/h264Preview_01_main
      - "ffmpeg:balkon#audio=opus"    
    voordeur:
      - rtsp://USER:PASSWORD@123.123.123.37:554/h265Preview_01_main
      - "ffmpeg:voordeur#audio=opus"   
    achter:
      - rtsp://USER:PASSWORD@123.123.123.181:554/h264Preview_01_main
      - "ffmpeg:achter#audio=opus"
  webrtc:
    candidates:
      - 123.123.123.171:8555 

detectors:
  coral:
    type: edgetpu
    device: usb
model:
  path: plus://modelpath

birdseye:
  enabled: true
  mode: continuous

snapshots:
  enabled: true
  retain:
    default: 1

detect:
  enabled: true # <---- turn on detection
  width: 1280
  height: 720

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 1
      mode: motion

objects:
  track:
  - person
  - face
  - license_plate
  - dog
  - cat
    #- car
  - amazon
  - fedex
  - ups
  - package
  filters:
    cat:
      min_area: 1000
    person:
      min_area: 5000

cameras:
### Camera VOORDEUR Config ###
  voordeur:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/voordeur?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
      hwaccel_args: preset-vaapi
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1
    live:
      stream_name: voordeur
    onvif:
      host: 123.123.123.37
      port: 8000
      user: USER
      password: PASSWORD      
    zones:
      vd_pad:
        coordinates: 212,574,216,720,681,720,723,558,293,458
      vd_trottoir:
        coordinates: 225,539,277,461,303,438,268,362,392,213,526,70,627,0,564,0,410,110,256,244,122,384,0,569,0,720,59,720,132,558,166,583,191,600
      vd_stoep:
        coordinates: 685,720,998,720,1014,545,743,495
      vd_weg:
        coordinates: 0,165,267,0,561,0,407,110,253,244,119,384,0,562
      vd_fietsen:
        coordinates: 655,0,769,0,743,352,729,497,717,540,338,462
    objects:
      filters:
        person:
          mask:
            - 536,324,566,183,744,246,715,566,544,530
    motion:
      threshold: 50
      mask:
      - 1280,0,1280,39,1205,34,1204,0
  
### Camera ACHTER Config ###
  achter:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/achter?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
      hwaccel_args: preset-vaapi
    live:
      stream_name: achter
    onvif:
      host: 123.123.123.181
      port: 8000
      user: USER
      password: PASSWORD
    detect:
      enabled: true # <---- turn on detection
      width: 1280
      height: 960
    motion:
      threshold: 50
      mask:
      - 864,0,860,95,606,91,606,0
      - 174,878,0,347,0,960,197,960
    objects:
      filters:
        dog:
          mask:
            - 284,720,1280,720,1280,682,506,341,146,406
        person:
          mask:
            - 1280,720,444,720,448,649,1280,629
    zones:
      deur:
        coordinates: 149,581,280,546,389,740,217,798
      hek:
        coordinates: 169,118,451,99,507,60,864,55,839,409,508,353,204,392
      terras:                                        # -  LB- ,-  RB -,-  RO -,-  LO -
        coordinates: 1280,960,1280,918,504,460,147,537,148,578,282,542,393,741,219,801,282,960

  balkon:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/balkon?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
      hwaccel_args: preset-vaapi
    live:
      stream_name: balkon
    onvif:
      host: 123.123.123.123
      port: 8000
      user: USER
      password: PASSWORD
    motion:
      threshold: 50
      mask:
        - 0,189,0,0,173,0
    objects:
      filters:
        person:
          mask:
            - 0,445,504,300,397,116,0,216
            - 1170,720,1174,688,924,688,883,720
```

### Relevant log output

```shell
#####GOOD - FROM HA WEBBROWSER:#######
frigate  | 2024-03-22 07:16:31.189615444  192.168.1.171 - - [22/Mar/2024:07:16:31 +0100] "GET /api/balkon/latest.jpg HTTP/1.1" 200 268804 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:31.195558152  192.168.1.171 - - [22/Mar/2024:07:16:31 +0100] "GET /api/achter/latest.jpg HTTP/1.1" 200 146398 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:32.235494595  192.168.1.171 - - [22/Mar/2024:07:16:32 +0100] "GET /api/balkon/latest.jpg HTTP/1.1" 200 270943 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:32.236138053  192.168.1.171 - - [22/Mar/2024:07:16:32 +0100] "GET /api/voordeur/latest.jpg HTTP/1.1" 200 224370 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:32.239473714  192.168.1.171 - - [22/Mar/2024:07:16:32 +0100] "GET /api/achter/latest.jpg HTTP/1.1" 200 146737 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:33.181472142  192.168.1.171 - - [22/Mar/2024:07:16:33 +0100] "GET /api/balkon/latest.jpg HTTP/1.1" 200 268985 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:33.190283180  192.168.1.171 - - [22/Mar/2024:07:16:33 +0100] "GET /api/voordeur/latest.jpg HTTP/1.1" 200 224456 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:33.197086280  192.168.1.171 - - [22/Mar/2024:07:16:33 +0100] "GET /api/achter/latest.jpg HTTP/1.1" 200 146537 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:16:33.612522399  192.168.1.171 - - [22/Mar/2024:07:16:33 +0100] "GET /live/mse/api/ws?src=voordeur&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3YTI2N2FiYjkzNzE0N2QwODNkMGVjOTQyM2YyZWY0MCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJ2b29yZGV1ciJdXSwiaWF0IjoxNzExMDg3NzcyLCJleHAiOjE3MTExNzQxNzJ9.DWtY_KwWIlTTne6aKvGvwEpxS_67CJxd0s3PRa--AM0 HTTP/1.1" 101 1869168 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "178.80.149.253, 192.168.1.35"
frigate  | 2024-03-22 07:16:33.623898378  192.168.1.171 - - [22/Mar/2024:07:16:33 +0100] "GET /live/mse/api/ws?src=balkon&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3YTI2N2FiYjkzNzE0N2QwODNkMGVjOTQyM2YyZWY0MCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJiYWxrb24iXV0sImlhdCI6MTcxMTA4Nzc3MiwiZXhwIjoxNzExMTc0MTcyfQ.A7Upah_9AcKFIOx5SzuIxC7EMD8-j6tN8R8YKGsP_tk HTTP/1.1" 101 3194931 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "178.80.149.253, 192.168.1.35"
frigate  | 2024-03-22 07:16:33.633706556  192.168.1.171 - - [22/Mar/2024:07:16:33 +0100] "GET /live/mse/api/ws?src=achter&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3YTI2N2FiYjkzNzE0N2QwODNkMGVjOTQyM2YyZWY0MCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJhY2h0ZXIiXV0sImlhdCI6MTcxMTA4Nzc3MiwiZXhwIjoxNzExMTc0MTcyfQ.N_lVhq1DXA37n4fE99XrqmNId6JiNtO5iKJX8VD-tUw HTTP/1.1" 101 4207259 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "178.80.149.253, 192.168.1.35"




#####BAD - FROM HA COMAPNION:#######
frigate  | 2024-03-22 07:18:10.595829869  192.168.1.171 - - [22/Mar/2024:07:18:10 +0100] "GET /api/voordeur/latest.jpg HTTP/1.1" 200 222135 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:10.596782659  192.168.1.171 - - [22/Mar/2024:07:18:10 +0100] "GET /api/balkon/latest.jpg HTTP/1.1" 200 269590 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:11.144826813  192.168.1.171 - - [22/Mar/2024:07:18:11 +0100] "GET /live/mse/api/ws?src=balkon&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwNzQ3ZDgwMjA2ZDM0MTdkOWQ2NDFmMGIxZWU2NTFjOCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJiYWxrb24iXV0sImlhdCI6MTcxMTA4ODI4NSwiZXhwIjoxNzExMTc0Njg1fQ.WI64wj8tO1-fuIrLjEEG2Cgh5V4whW74lmMwbJFd5Kk HTTP/1.1" 101 1241973 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.2 (io.robbie.HomeAssistant; build:2024.561; iOS 17.4.0) Mobile/HomeAssistant, like Safari" "178.80.149.253, 192.168.1.35"
frigate  | 2024-03-22 07:18:11.144959945  192.168.1.171 - - [22/Mar/2024:07:18:11 +0100] "GET /live/mse/api/ws?src=voordeur&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwNzQ3ZDgwMjA2ZDM0MTdkOWQ2NDFmMGIxZWU2NTFjOCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJ2b29yZGV1ciJdXSwiaWF0IjoxNzExMDg4Mjg1LCJleHAiOjE3MTExNzQ2ODV9.1VzrjfPX14pAabBsrUxuGMqGa7169EsQZrfMoCtVvDQ HTTP/1.1" 101 1570514 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.2 (io.robbie.HomeAssistant; build:2024.561; iOS 17.4.0) Mobile/HomeAssistant, like Safari" "178.80.149.253, 192.168.1.35"
frigate  | 2024-03-22 07:18:11.148205523  192.168.1.171 - - [22/Mar/2024:07:18:11 +0100] "GET /live/mse/api/ws?src=achter&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwNzQ3ZDgwMjA2ZDM0MTdkOWQ2NDFmMGIxZWU2NTFjOCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJhY2h0ZXIiXV0sImlhdCI6MTcxMTA4ODI4NSwiZXhwIjoxNzExMTc0Njg1fQ.SHfpWTb6B0AWEFDgrxKof6ShBJTgVb2ReaAzl0s32so HTTP/1.1" 101 1140142 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.2 (io.robbie.HomeAssistant; build:2024.561; iOS 17.4.0) Mobile/HomeAssistant, like Safari" "178.80.149.253, 192.168.1.35"
frigate  | 2024-03-22 07:18:11.595447215  192.168.1.171 - - [22/Mar/2024:07:18:11 +0100] "GET /api/balkon/latest.jpg HTTP/1.1" 200 271925 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:11.595812404  192.168.1.171 - - [22/Mar/2024:07:18:11 +0100] "GET /api/voordeur/latest.jpg HTTP/1.1" 200 222105 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:11.596290879  192.168.1.171 - - [22/Mar/2024:07:18:11 +0100] "GET /api/achter/latest.jpg HTTP/1.1" 200 146162 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:12.585522573  192.168.1.171 - - [22/Mar/2024:07:18:12 +0100] "GET /api/voordeur/latest.jpg HTTP/1.1" 200 222015 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:12.587673312  192.168.1.171 - - [22/Mar/2024:07:18:12 +0100] "GET /api/balkon/latest.jpg HTTP/1.1" 200 269928 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-03-22 07:18:12.591524584  192.168.1.171 - - [22/Mar/2024:07:18:12 +0100] "GET /api/achter/latest.jpg HTTP/1.1" 200 145894 "-" "HomeAssistant/2024.3.0 aiohttp/3.9.3 Python/3.12" "-"
```

### Frigate stats

```json
{"cameras":{"achter":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":483,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":490,"pid":463,"process_fps":5.0,"skipped_fps":0.0},"balkon":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":487,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":494,"pid":468,"process_fps":5.1,"skipped_fps":0.0},"voordeur":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":479,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":484,"pid":460,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"22.5","cpu_average":"22","mem":"0.3"},"108":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"python3 -u -m frigate","cpu":"2.9","cpu_average":"13","mem":"3.8"},"122":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"189":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"223":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"440":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"442":{"cmdline":"frigate.recording_manager","cpu":"1.4","cpu_average":"1","mem":"1.0"},"451":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)","cpu":"0.5","cpu_average":"0","mem":"0.1"},"452":{"cmdline":"frigate.detector.coral","cpu":"0.3","cpu_average":"0","mem":"0.9"},"454":{"cmdline":"frigate.output       ","cpu":"1.9","cpu_average":"1","mem":"0.9"},"457":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"458":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x960 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"460":{"cmdline":"frigate.process:voordeur","cpu":"2.6","cpu_average":"3","mem":"1.0"},"461":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"463":{"cmdline":"frigate.process:achter","cpu":"5.2","cpu_average":"2","mem":"1.0"},"467":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"468":{"cmdline":"frigate.process:balkon","cpu":"2.8","cpu_average":"4","mem":"1.0"},"479":{"cmdline":"frigate.capture:voordeur","cpu":"3.3","cpu_average":"2","mem":"0.8"},"483":{"cmdline":"frigate.capture:achter","cpu":"4.2","cpu_average":"3","mem":"0.8"},"484":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/voordeur?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1 /tmp/cache/voordeur@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.3","cpu_average":"5","mem":"0.7"},"487":{"cmdline":"frigate.capture:balkon","cpu":"3.1","cpu_average":"2","mem":"0.8"},"490":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/achter?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/achter@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=960:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.1","cpu_average":"7","mem":"0.8"},"494":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/balkon?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/balkon@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.5","cpu_average":"6","mem":"0.8"},"92985":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.48,"pid":452}},"gpu_usages":{"amd-vaapi":{"gpu":"1.67%","mem":"49.20%"}},"processes":{"go2rtc":{"pid":92},"logger":{"pid":440},"recording":{"pid":442}},"service":{"last_updated":1711088364,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":243.4,"mount_type":"tmpfs","total":256.0,"used":12.6},"/media/frigate/clips":{"free":564999.6,"mount_type":"xfs","total":915264.9,"used":350265.3},"/media/frigate/recordings":{"free":564999.6,"mount_type":"xfs","total":915264.9,"used":350265.3},"/tmp/cache":{"free":931.3,"mount_type":"tmpfs","total":953.7,"used":22.3}},"temperatures":{},"uptime":2663,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
