### DISCUSSION TITLE
[Camera Support]: Troubleshooting 2-way audio with Reolink Doorbell

### DISCUSSION THREAD

**Discussion by soonerfan237** [blakeblackshear/frigate#10619] [Camera Support] [answered]
### Describe the problem you are having

I haven't been able to get 2-way audio working with my Reolink Doorbell WiFi and at this point I'm unsure what else to try. It seems like I'm quite close. In my Frigate lovelace card, I get audio and video. And I see the microphone button. My browser and OS reports that it's using my microphone. When I click the button, it turns red as if its in use. However, when I speak into my microphone, no audio comes out of the doorbell speaker. This feature works via the official Reolink iOS app.
https://youtu.be/F2fxWTnrEYY

go2rtc version 1.8.4

Here are my server settings in the Reolink Doorbell:
<img width="711" alt="Screenshot 2024-03-22 at 4 46 29 PM" src="https://github.com/blakeblackshear/frigate/assets/11335516/9d14c50b-8f70-472b-a5a9-d85046baf155">

I am accessing through https using Nabu Casa. I have not done anything else regarding https.

I believe I have WebRTC set up correctly. I did the [WebRTC extra configuration](https://docs.frigate.video/configuration/live/#webrtc-extra-configuration) including forwarding port 8555 in my router for TCP and UDP.
<img width="454" alt="Screenshot 2024-03-21 at 11 00 52 PM" src="https://github.com/blakeblackshear/frigate/assets/11335516/8a2cd393-aa60-41a8-bc5c-672c9e15d032">
I haven't changed any other router settings. Here are some other settings I can see (not sure if any of these are relevant).
![IMG_3157](https://github.com/blakeblackshear/frigate/assets/11335516/09a04099-d844-4366-82b5-c4571ff4dd1f)

Here is my Frigate lovelace card config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell_camera
    engine: frigate
    live_provider: go2rtc
    icon: mdi:doorbell-video
    go2rtc:
      modes:
        - webrtc
live:
  auto_mute: never
  transition_effect: slide
  microphone:
    always_connected: true
  controls:
    builtin: true
    title:
      mode: none
  show_image_during_load: false
  preload: true
  draggable: false
  zoomable: false
  auto_unmute: all
view:
  default: live
  camera_select: live
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '4:3'
menu:
  style: overlay
  buttons:
    microphone:
      enabled: true
      type: toggle
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    timeline:
      enabled: false
    mute:
      enabled: false
timeline:
  show_recordings: false
```

### Version

2024.3.3

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user:
    xxxx
  password:
    xxxx

go2rtc:
  streams:
    doorbell_camera:
      - ffmpeg:http://xxx.xxx.xx.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus
      - rtsp://xxxx:xxxx@xxx.xxx.xx.xxx:554/h264Preview_01_sub
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  webrtc:
    candidates:
      - http://xxx.xxx.xx.xxx:8555
      - stun:8555

cameras:
  doorbell_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      front_porch_zone:
        coordinates: 0,87,0,264,0,720,1034,720,864,388,453,385,455,265
    motion:
      mask:
        - 949,411,450,401,455,244,389,168,987,82
        - 935,0,935,50,325,50,325,0
        - 735,424,733,545,538,542,545,446
    record:
      enabled: True
      events:
        retain:
          default: 7
          mode: all
    snapshots:
      enabled: True
      retain:
        default: 14
    audio:
      enabled:
        true
      listen:
        - bark
        - speech
    objects:
      track:
        - person
        - dog
        - car
      filters:
        person:
          min_score: 0.8
        dog:
          min_score: 0.75
        car:
          min_score: 0.7

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
2024-03-22 22:00:57.687202270  172.30.32.1 - - [22/Mar/2024:17:00:57 -0500] "GET /api/events?cameras=doorbell_camera&limit=50&include_thumbnails=0 HTTP/1.1" 200 25437 "-" "HomeAssistant/2024.3.3 aiohttp/3.9.3 Python/3.12" "-"
2024-03-22 22:00:59.452236781  172.30.32.1 - - [22/Mar/2024:17:00:59 -0500] "GET /live/mse/api/ws?src=doorbell_camera&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4NzA2YTdiNjFlOTA0YmIwYTMyMDlkMjE5NzczMDJiZSIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJkb29yYmVsbF9jYW1lcmEiXV0sImlhdCI6MTcxMTE0NDg1NywiZXhwIjoxNzExMjMxMjU3fQ.QbC5cHtz5nd_OHEpnf0WO1AjNKY642cLzx5TfHVHJ1Y HTTP/1.1" 101 3141 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "127.0.0.1"
2024-03-22 22:00:59.456189914  172.30.32.1 - - [22/Mar/2024:17:00:59 -0500] "GET /live/mse/api/ws?src=doorbell_camera&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4NzA2YTdiNjFlOTA0YmIwYTMyMDlkMjE5NzczMDJiZSIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjpbWyJzcmMiLCJkb29yYmVsbF9jYW1lcmEiXV0sImlhdCI6MTcxMTE0NDg1NywiZXhwIjoxNzExMjMxMjU3fQ.QbC5cHtz5nd_OHEpnf0WO1AjNKY642cLzx5TfHVHJ1Y HTTP/1.1" 101 3144 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "127.0.0.1"
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://xxxx:xxxx@xxx.xxx.xx.xxx:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000750, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 15 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink Doorbell WiFi

### Any other information that may be helpful

Stream info from go2rtc while microphone is active:

```
{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/4ac90777626806e7d200b282a5fcda8a",
      "remote_addr": "127.0.0.1:34836",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 H264, bytes=841850279, senders=6",
        "97 MPEG4-GENERIC/16000, bytes=21018850, senders=2",
        "98 OPUS/48000/2, bytes=52647915, senders=4"
      ],
      "recv": 926780480
    },
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.86.152/Preview_01_sub/",
      "remote_addr": "192.168.86.152:554",
      "user_agent": "go2rtc/1.8.4",
      "sdp": "v=0\r\no=- 1711139203173092 1 IN IP4 192.168.86.152\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "senders": [
        "0 PCMU/8000, bytes=92480, receivers=7"
      ],
      "recv": 1248,
      "send": 100848
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/doorbell_camera",
      "remote_addr": "127.0.0.1:34820",
      "user_agent": "FFmpeg Frigate/0.13.2-6476f8a",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=841850279, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=21018850, receivers=1"
      ],
      "send": 873487385
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/doorbell_camera",
      "remote_addr": "127.0.0.1:34844",
      "user_agent": "FFmpeg Frigate/0.13.2-6476f8a",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=841592285, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=21007538, receivers=1"
      ],
      "send": 873214991
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.86.1:60151 related :0",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=8510052, receivers=1",
        "111 OPUS/48000/2, bytes=546302, receivers=1"
      ],
      "send": 9178355
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.86.213:56918",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=2806530, receivers=1",
        "111 OPUS/48000/2, bytes=179456, receivers=1"
      ],
      "send": 3026982
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.86.213:50055",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML",
        "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
      ],
      "receivers": [
        "0 PCMU/8000, bytes=36800, senders=1"
      ],
      "senders": [
        "102 H264, bytes=1266593, receivers=1",
        "111 OPUS/48000/2, bytes=73469, receivers=1"
      ],
      "recv": 41400,
      "send": 1358992
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.86.213:59093",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML",
        "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
      ],
      "receivers": [
        "0 PCMU/8000, bytes=56320, senders=1"
      ],
      "senders": [
        "102 H264, bytes=1235695, receivers=1",
        "111 OPUS/48000/2, bytes=70358, receivers=1"
      ],
      "recv": 63570,
      "send": 1324445
    }
  ]
}
```

**Comment by NickM-27** [comment]
What firmware is your doorbell running

**Reply by soonerfan237** [reply]
v3.0.0.3215_2401262240

**Reply by NickM-27** [reply]
This firmware broke two way talk via rtsp

**Reply by soonerfan237** [reply]
Which firmware version do I need?

**Reply by NickM-27** [reply, marked as answer]
A user said the August version works

**Reply by soonerfan237** [reply]
It works now! Thank you!

I downgraded to v.3.0.0.2033 using this unofficial archive:
https://github.com/AT0myks/reolink-fw-archive/tree/main

**Reply by zollak** [reply]
Hi, thanks for this detailed troubleshooting and the highlighted solution! I had exactly the same issue, with Firmware Version: v3.0.0.3215_2401262241, and the downlgrade solve it (Firmware Version: v3.0.0.2033_23041302). 

Thanks again!

**Reply by wwalcher** [reply]
Hey soonerfan237, I am having a problem getting this to work.  What I am trying to do is get my Reolink POE Doorbell working as a Media Player in HA so that I can either send an audio file or do Text to Speech to it.  I have installed Go2RTC, setup a stream(s) there, created a Media player entry for the stream, but when I try to use it, I get an error message "Failed to call service media_player/play_media. 'webrtc'".

My setting for DoorbellRTSP in Go2TRC:
  "producers": [
    {
      "url": "rtsp://admin:a1111111@10.10.10.139:554/h264Preview_01_main"
    }
  ],
  "consumers": []
} 

My setup in configuration.yaml of the media player
media_player:
  - platform: webrtc
    name: Front Doorbell RTSP
    stream: DoorbellRTSP
    audio: '-af "volume=10dB,adelay=2s,apad=pad_dur=6" -c:a pcm_alaw -ar:a 8000 -ac:a 1'    

I have installed WebRTC from HACS but don't know what to do with it.  When I tried to create a customer card with the Go2RTC stream, it didn't work, so I am not sure what I am supposed to do with it.

Can you (or anyone else reading this) provide any direction in getting this to work?

**Reply by wwalcher** [reply]
I did downgrade to the April 2023 version of the firmware on the camera, btw.

**Reply by wwalcher** [reply]
I think I found my problem.  I had downloaded WebRTC, but not added it as an integration.  When I did that, the camera worked as a media player, but sending it audio files and Text to Speech.  Yay!

**Reply by IDmedia** [reply]
A heads up for other people with this issue.

I brought a Reolink Doorbell Wifi after hearing it integrates perfectly into Home Assistant and Frigate. Even though the hardware model is "DB_566128M5MP_W" it is according to Reolink NOT compatible with the listed firmwares. They say there are "online" and "offline" models, but there is really no way for the customer to know which is which before buying.

If you have brought a Reolink Doorbell that has "D340W" printed on the box or shows that model in Home Assistant you might be out of luck and can't update or downgrade the firmware. I've been in touch with Reolink and they are not willing to help. In earlier days you could mail support and get a newer/suited firmware in return, but that's not the case anymore according to Reolink and other Reddit users. If you are stuck with one of these "offline" versions I would highly recommend to RMA or return it as a "fake" or misleading product.

**Reply by matthewmcpartland** [reply]
> A heads up for other people with this issue.
> 
> I brought a Reolink Doorbell Wifi after hearing it integrates perfectly into Home Assistant and Frigate. Even though the hardware model is "DB_566128M5MP_W" it is according to Reolink NOT compatible with the listed firmwares. They say there are "online" and "offline" models, but there is really no way for the customer to know which is which before buying.
> 
> If you have brought a Reolink Doorbell that has "D340W" printed on the box or shows that model in Home Assistant you might be out of luck and can't update or downgrade the firmware. I've been in touch with Reolink and they are not willing to help. In earlier days you could mail support and get a newer/suited firmware in return, but that's not the case anymore according to Reolink and other Reddit users. If you are stuck with one of these "offline" versions I would highly recommend to RMA or return it as a "fake" or misleading product.

I bought a Reolink Wifi Doorbell maybe 1.5 years ago, just now setting it up in Frigate. 
Item No. D340W
Hardware No. DB_566128M5MP_W
Firmware Version v3.0.0.4110_2410111119

This is the latest firmware, the same D340W. However I've been able to get 2-way audio working within Frigate (restreamed by the internal go2rtc).
I haven't tried downgrading the firmware, however it may not be necessary.

Some of my findings, as I spent more hours than reasonable today:
- the go2rtc configuration in Frigate requires restarting the go2rtc component. You can confirm this easily by changing the frigate config, then navigate to the go2rtc webui (:1984/editor.html) and you'll see the changes aren't there.
- 2-way audio requires HTTPS, so you'll need to set that up. A reverse proxy works fine
- not sure if it's necessary but I've seen some people put webrtc info under the go2rtc header, I did the same on this.
- I think I've also seen it said online that an rtsp stream must be provided too. I'm not 100% but definitely make sure you have the right video streams setup for the camera

**Comment by toxic0berliner** [comment]
Maybe I'm mitaken and I didn't pick the proper version to downgrade, but it seems to me version 3215 does not work for 2way audio as mentionned here but when I downgraded to `DB_566128M5MP_W.2676_23090700.Reolink-Video-Doorbell-WiFi.OV05A10.5MP.WIFI8812.REOLINK` I lost the "play quick reply message" feature... It's more low-tech than 2 way audio but also more useful to me so for now I'll stick with the latest firmware and forego 2way audio...

If someone has the 2 features working (on wifi version preferably) please do correct me and share what firmware version you have, either the download link or at least the version number so I can ask for it to the reolink support tams ;)

Else I fear I can only wayt for the vendor to fix the bug and release a new firmware ;)

**Comment by PrplHaz4** [comment]
For anyone following the reolink doorbell firmware issues - I've found some issues with chime pairing after downgrading my v2 Doorbell to v3.0.0.2033.

There are multiple versions of the Reolink Chime
- v1 (unversioned on the label) - pairs via 433mhz, only compatible with v1 of the Doorbell
- v2 (shows on label) - pairs via 900mhz, only compatible with v2+ of the Doorbell

On my v2 Doorbell running v3.0.0.2033 with v2 Chime, I was not able to pair
After upgrading v2 Doorbell to v3.0.0.3215, the doorbell paired and is working fine.

**Reply by reg98643t** [reply]
> For anyone following the reolink doorbell firmware issues - I've found some issues with chime pairing after downgrading my v2 Doorbell to v3.0.0.2033.
> 
> There are multiple versions of the Reolink Chime
> 
>     * v1 (unversioned on the label) - pairs via 433mhz, only compatible with v1 of the Doorbell
> 
>     * v2 (shows on label) - pairs via 900mhz, only compatible with v2+ of the Doorbell
> 
> 
> On my v2 Doorbell running v3.0.0.2033 with v2 Chime, I was not able to pair After upgrading v2 Doorbell to v3.0.0.3215, the doorbell paired and is working fine.

I've bricked 2 V2 doorbells trying to downgrade them, has Reolink made another update to prevent it?

**Reply by KumarMudedla** [reply]
@reg98643t 
Are you able find any solution to downgrade? I bricked 2 sofar v2 door bell POE
Seems who ever had success, using v1 maybe ?

**Comment by HSB-collab** [comment]
I am experiencing exactly the same issue as described by @soonerfan237 above. However, I have downgraded the firmware on the Reolink Video Doorbell WiFi  to v3.0.0.2033 and I still cannot get 2-way audio working. I am receiving audio from the doorbell but I am not able to get sound back to the doorbell. My microphone is working in the Frigate Card (my Android phone is showing a green dot to indicate it is on) but there is no sound out. Also, firmware v3,0,0,2033 broke the connection to my Chime as discussed by @PrplHaz4. This problem is driving me crazy. I would appreciate any help.
Here is my setup:

- HA running in a Virtualbox VM under a Ubuntu 22.04 host;
- Frigate 0.13.2-6476F8A running in a Docker container on the same host: the` Docker compose file and Frigate config.yml files are attached. Go2rtc is version 1.8.4 .
- I have attached the Frigate and go2rtc logs 
- I am unable to supply 'streams info' because I get a 404 error when I click on the link (not sure why?)
- Reolink video doorbell WiFi.  I have tried 3 firmware versions v3.0.0.3215 (the latest), v3.0.0.2033 (suggested by @NickM-27 and which solved @soonerfan237 problem) and v3.0.0.2676 suggested by Reolink support (who are super helpful - it is a pleasure to deal with them). My microphone audio did not work with any of them.
 
[Frigate card configuration.txt](https://github.com/user-attachments/files/15527742/Frigate.card.configuration.txt)
[go2rtc logs.txt](https://github.com/user-attachments/files/15527743/go2rtc.logs.txt)
[Frigate logs.txt](https://github.com/user-attachments/files/15527744/Frigate.logs.txt)
[config.yml for Frigate.txt](https://github.com/user-attachments/files/15527745/config.yml.for.Frigate.txt)
[Docker compose file for Frigate.txt](https://github.com/user-attachments/files/15527746/Docker.compose.file.for.Frigate.txt)

I would really appreciate some help. Thanks in advance.

**Reply by superdong69** [reply]
You ever figure this out?

**Reply by HSB-collab** [reply]
No unfortunately not. I have given up and use the Reolink app for 2-way audio and Frigate to record video. The Reolink app is very good and I have found its reaction time is about the same as Home-Assistant so there did not seem much point in carrying on.

**Comment by reg98643t** [comment]
Unfortunately not. I think we are stuck waiting for a firmware update from Reolink.

Could try contacting support but I haven't had the time for that at the moment.

-------- Original Message --------

**Comment by ericlik** [comment]
I m having the same issue. I talk to my phone app and sound does not come out from the camera. when I talk to the camera, I can hear from my phone (Samsung Fold 5)

But when I use my Samsung Note 20 Ultra, the 2 way audio works. but the live feed may freeze when I talk to the camera. 
Both phone has the Reolink app version 4.47.0.5.20240708

So 1 phone works and 1 phone does not. 

Anyone find a fix ?

**Reply by grimmaldus** [reply]
Have you figure it out ? I'm having the same issue on SM-T733

**Comment by Thorsten1982** [comment]
How does the 2-way audio actually work? Is a microphone symbol displayed in the camera's live feed under Home Assistant and can I then press it to speak?
There was a new firmware recently, has anyone tested it with this?

**Comment by DRuggeri** [comment]
⚠️⚠️⚠️WARNING⚠️⚠️⚠️

I just installed the v3.0.0.2033_23041302 firmware on a PoE doorbell purchased in June and it has entered an unstoppable bootloop (alive for 15 to 20 seconds, then unavailable 15 to 20 seconds). Factory reset took (when it's alive for a few seconds, the windows app shows it is not initialized), but did not help.

I think this thing just became an expensive paperweight, unless anyone has a recovery mechanism they'd advise.

**Reply by tarekshaheen1996** [reply]
any solution for this issue ?

**Reply by DRuggeri** [reply]
Nope - best I was able to do was to have it RMAd by Reolink since it was still under warranty.

**Reply by Handrail9** [reply]
I just bought one today because I was under the impression that this would work. Is there another option that you're aware of for HA/Frigate users or are we SOL at the moment?

**Reply by NickM-27** [reply]
If you just bought one you shouldn't have any issues, mine has been working fine for 2 years

**Reply by Handrail9** [reply]
> If you just bought one you shouldn't have any issues, mine has been working fine for 2 years

I was Trying to get it set up for two way audio last night and could not even get one way audio working (can't hear the doorbell)

should I open a new discussion to try and troubleshoot my issue? I figured what this guy was talking about would've been the problem

**Reply by DRuggeri** [reply]
As can probably be gathered from others here, v3.0.0.4110_2410111120 *does not* cause the camera to enter into a bootloop. I'm still working to find a successful formula, but at least this firmware works with the RMA'd device Reolink sent.

**Comment by toxic0berliner** [comment]
I'm getting lost in this discussion, I think everyone should try to be more specific, so I'll attempt to start : 
I'm running 
```
    Model Reolink Video Doorbell WiFi
    Item No.D340W
    Build No.build 2401262240
    Config Versionv3.0.0.0
    Firmware Versionv3.0.0.3215_2401262240
```
With the latest home assistant.
I have working 
- camera feed through frigate (including sound of course)
- snapshots (picture of the moment that I use for the below feature)
- ring event triggers my automation (notification on my phone with the picture of the visitor at the door)
- drop-down in home assistant to select a prerecorded message of my choosing when someone rings 

I am not running the latest firmware as you can see, that is because upgrading caused one of the above feature to break, don't remember which one.

I would like to be able to speak to frigate and have my voice output by the camera speaker, either live or by playing a media from HA onto a "speaker" entity of the camera device in HA, but that's lower on my priority than the above features, so I have downgraded to the above "old" 2401262240 firmware to get back these features and I'm monitoring this thread hoping someone tells us the latest firmware is all good.
But between the messages claiming that upgrade bricks their device and the messages claiming all is fine, all that without version numbers it's hard to understand...

Did someone manage to get 2 way audio (your voice into frigate coming out of the camera, or recorded media from HA) without breaking one of the above like loosing sound or the ability to select the prerecorded message? And if yes with which firmware version?

Hope we can sort it out.

**Comment by pfak** [comment]
Two-way audio works in the firmware released on October 23 for PoE doorbell: v3.0.0.4110_2410111120

**Reply by voron69-bit** [reply]
FYI all, This is NOT the Wifi Reolink Video Doorbell which this topic is about. This issue is NOT fixed for these doorbells.

**Reply by NickM-27** [reply]
If you are on the correct firmware it works without any issues on the wifi doorbell.

**Reply by dsantos21** [reply]
The new firmware worked for me (the specific one for Wi-Fi version, also available at reolink website).

My Reolink Doorbell is the Wi-Fi version.

**Reply by voron69-bit** [reply]
I've installed this latest version on the wifi doorbell. There is no option for 2 way audio in frigate, or the frigate card in HA.

**Reply by NickM-27** [reply]
Are you connecting via https? You can check the probe output in network tab of browser tools to see what the camera is advertising.

**Reply by voron69-bit** [reply]
Hey Nick, yes, connecting https.

**Reply by dsantos21** [reply]
@voron69-bit not sure if that's the case, but have you selected go2rtc as source in the frigate card? This, the new firmware, and restarting frigate after, has solved for me.

**Reply by voron69-bit** [reply]
Both were still webrtc. Changed to go2rtc and the option popped up. You sir win the Internet for the day!

**Reply by DRuggeri** [reply]
> Both were still webrtc. Changed to go2rtc and the option popped up. You sir win the Internet for the day!

So, for y'all that everything is working for... what was the magic formula that got you there? Looking at my frigate config, I have a second go2rtc stream like so (from [the docs](https://docs.frigate.video/configuration/live/#audio-support)):
```
    doorbell-cam_high:
      - rtsp://{FRIGAET_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@doorbell-cam.home.bitnebula.com:554/h264Preview_01_main
      - ffmpeg:doorbell-cam_high#audio=opus
```

In various posts here, I see another example that looks like this, though:
```
      - "ffmpeg:http://10.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=USER&password=PASSWORD#video=copy#audio=copy#audio=opus"
      - rtsp://10.x.x.x/Preview_01_sub
```
I'm a little lost in the difference between the two, which user/password to pass, the hosts, etc... all the redacting in the post has made things super vague :-).
Is this how you guys have the frigate config set up? If so, what do these two lines mean compared to using rtsp:// in my config?

**Reply by pfak** [reply]
> > Both were still webrtc. Changed to go2rtc and the option popped up. You sir win the Internet for the day!
> 
> So, for y'all that everything is working for... what was the magic formula that got you there? Looking at my frigate config, I have a second go2rtc stream like so (from [the docs](https://docs.frigate.video/configuration/live/#audio-support)):


```
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - <FRIGATE_IP>:8555
      - stun:8555
  streams:
    doorbell:
      - rtsp://admin:<PASSWORD>@192.168.4.21:554/
      - ffmpeg:http://192.168.4.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<PASSWORD>#audio=opus#audio=volume
    doorbell_sub:
      - rtsp://admin:<PASSWORD>@192.168.4.21:554/h264Preview_01_sub
      - ffmpeg:http://192.168.4.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<PASSWORD>#audio=opus#audio=volume
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"

cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
    onvif:
      host: 192.168.4.21
      port: 80
      user: admin
      password: <PASSWORD>

```
