### DISCUSSION TITLE
[Config Support]: expire_interval is being ignored

### DISCUSSION THREAD

**Discussion by fayeinmay** [blakeblackshear/frigate#10611] [Config Support] [answered]
### Describe the problem you are having

I set the expire_interval for all my cameras to 4320 minutes, so 72 hours.
Frigate is ignoring this parameter though, as you can see below.
Am I missing something here?

![image](https://github.com/blakeblackshear/frigate/assets/11154004/f895b856-2fd8-4f88-9b17-1f5a33d34352)
![image](https://github.com/blakeblackshear/frigate/assets/11154004/d01a5c0f-fe5d-4825-be25-014f3887e841)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.0.231
  
go2rtc:
  streams:
    reolink_cam: 
      - "ffmpeg:https://192.168.0.147/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=viewer&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    reolink_cam_sub: 
      - "ffmpeg:https://192.168.0.147/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=viewer&password={FRIGATE_RTSP_PASSWORD}"
    reolink_doorbell:
      - "ffmpeg:https://192.168.0.215/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=viewer&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    reolink_doorbell_sub:
      - "ffmpeg:https://192.168.0.215/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=viewer&password={FRIGATE_RTSP_PASSWORD}"

detectors:
  coral:
    type: edgetpu
    device: pci:0

birdseye:
  enabled: False

cameras:
  doorbell:
    objects:
      track:
        - person
    live:
      stream_name: reolink_doorbell
    record:
      enabled: True
      expire_interval: 4320
      events:
        retain:
          default: 14
          mode: active_objects
    detect:
      enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
  carport:
    objects:
      track:
        - person
    live:
      stream_name: reolink_cam
    record:
      enabled: True
      expire_interval: 4320
      events:
        retain:
          default: 14
          mode: active_objects
    detect:
      enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_cam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant log output

```shell
2024-03-21 09:07:57.750912949  [INFO] Preparing Frigate...
2024-03-21 09:07:57.810285680  [INFO] Starting Frigate..
(...)
Deletion at 2024-03-22 13:09:17, not logged in frigate logs.
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe

**Comment by NickM-27** [comment]
it does not look like the parameter is being ignored, if it was then the default 60 minutes would be used. I also run unraid and using the disk activity plugin can see that my disks are spun down a majority of the time meaning the value does work as expected. 

if I had to guess, what is happening here is one of two things:
1. the storage area got close to running out of space so frigate did an emergency recording cleanup (which does not respect the expire interval for obvious reasons)
2. it's not clear from the screenshots what time is right now, so it's not clear when exactly this cleanup job was run relative to when frigate was started

**Reply by fayeinmay** [reply]
1. Not the case, 4 TB of 8 TB free still.
2. Frigate was started at 2024-03-21 09:07:57 and the files were deleted at 2024-03-22 13:09:17. The highlighting in the screenshots might not have been enough.

**Comment by artiomchi** [comment]
Did you ever get anywhere with this? I'm in the exact same boat, with Frigate regularly deleting clips - I've got a lot of space left on disk, and have configured the `expire_interval` value both in the top level config and on each of the cameras, yet it sometimes runs a cleanup on a 5 min interval.

**Reply by NickM-27** [reply]
snapshots will be deleted when the events expire which is checked every 5 minutes. I would suggest keeping snapshots on an SSD since they take up a small amount of space relative to recordings anyway

**Reply by artiomchi** [reply]
Problem is, I've got all my CCTV stored on the SSD, and then moved to the HDD on a daily basis. But 10 days later, when the clips are deleted, they end up being deleted from the HDD.

I'm assuming there's no `expire_interval` option on the snapshots then. Can this be added, so that they're only deleted once a day?

**Reply by NickM-27** [reply]
right, but you could only move the recordings to HDD and leave the snapshots on SSD. I have a similar setup on unraid and it works great. 

and yes currently there is no configuration for the event expire interval

**Reply by artiomchi** [reply]
Ahh, so I'm assuming you mapped the snapshots folder on your Frigate container to a path in the host on the Cache, right?

**Reply by NickM-27** [reply]
yes

![Screen Shot 2024-07-02 at 07 17 26 AM](https://github.com/blakeblackshear/frigate/assets/14866235/bcf16cd0-c2df-413d-95af-9c0ea89ca6cb)

**Reply by artiomchi** [reply]
Thank you, will test it out later tonight

**Reply by fayeinmay** [reply]
The difference for me is that I set the expire_interval on recordings, not snapshots, but it is still checked every 5 minutes thus causing a disk spin-up with the file age metadata read.

**Reply by NickM-27** [reply]
> The difference for me is that I set the expire_interval on recordings, not snapshots, but it is still checked every 5 minutes thus causing a disk spin-up with the file age metadata read.

please read the conversation above, the 5 minute checks are usually for events cleanup which will cause snapshots to be removed. The solution is described above. Perhaps a similar config for snapshots can be created as well

**Reply by fayeinmay** [reply]
I'm at a loss for what you're trying to tell me. I did read the conversation. As with my original post above, expire_interval is being ignored for recordings. But maybe I just don't understand the purpose of expire_interval.
In my config, I have:
```
record:
      enabled: True
      expire_interval: 4320 # This means the cleanup job will check every 72 hours if any recording is older than retain time (?)
      events:
        retain:
          default: 14 # retain time, the recordings will be kept for 14 days
          mode: active_objects # recordings will be started and saved only when active_object is being detected
```

Also, for the wording: Snapshots = Images https://docs.frigate.video/configuration/snapshots, Recordings = Clips? https://docs.frigate.video/configuration/record
