### DISCUSSION TITLE
[Config Support]: Examples With Using an SSD + Hard Drive for Storage?

### DISCUSSION THREAD

**Discussion by slopokdave** [blakeblackshear/frigate#10614] [Config Support] [answered]
### Describe the problem you are having

I want to try using a spare SSD I have for initial drive storage (1/2 days), then move anything older (say, up to 5 or 7 days) to a larger SATA hard drive for extended storage.

Does anyone have any examples of doing this? Is it setup via the config file? For reference, I am running:

- Frigate appdata runs on Unraid nvme cache drive
- The 1-2 day SSD will be an "unassigned devices" drive (this is not part of my unraid cache or unraid array)
- Anything after 1-2 days should be moved to a second "unassigned devices" drive (2tb hard drive).

Thanks in advance for anything to help me start this. 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.70
  port: 1883
  user: admin
  password: XXXXXXXXXXX

detectors:
  coral:
    type: edgetpu
    device: pci:0

model:
  path: plus://XXXXXXXXXXX

go2rtc:
  webrtc:
    candidates:
      - 192.168.4.70:8555
      - stun:8555
  streams:
    front_cam:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.200/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_cam_sub:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.200/cam/realmonitor?channel=1&subtype=1
    front_cam_sub2:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.200/cam/realmonitor?channel=1&subtype=2
    garage_cam:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.203/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_cam_sub:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.203/cam/realmonitor?channel=1&subtype=1
    garage_cam_sub2:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.203/cam/realmonitor?channel=1&subtype=2
    door_cam:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.201/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    door_cam_sub:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.201/cam/realmonitor?channel=1&subtype=1
    door_cam_sub2:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.201/cam/realmonitor?channel=1&subtype=2
    back_patio_cam:
       - rtsp://admin:XXXXXXXXXXX@192.168.7.235/h265Preview_01_main
    back_patio_cam_balanced:
       - https://192.168.7.235/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXXXXXXXXX
    back_patio_cam_sub:
       - rtsp://admin:XXXXXXXXXXX@192.168.7.235/h264Preview_01_sub
    back_yard_cam:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.204/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    back_yard_cam_sub:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.204/cam/realmonitor?channel=1&subtype=1
    back_yard_cam_sub2:
       - rtsp://admin:XXXXXXXXXXX@192.168.4.204/cam/realmonitor?channel=1&subtype=2
birdseye:
  enabled: True
  mode: continuous

cameras:
  front_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtsp-restream-low-latency
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_cam_sub2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      - face
      - dog
      - cat
      - deer
      - car
      - amazon
      - fedex
      - ups
      filters:
        car:
          min_score: .65
          threshold: 0.8
        person:
          min_score: .65
          threshold: 0.8
        face:
          min_score: .7
        dog:
          min_score: .7
          threshold: 0.8
        cat:
          min_score: .65
          threshold: 0.8
        amazon:
          min_score: 0.75
        ups:
          min_score: 0.75
        fedex:
          min_score: 0.75
      mask: 390,56,404,71,290,71,286,58
    live:
      stream_name: front_cam_sub
    zones:
      front_driveway_yard:
        coordinates: 0,412,0,720,823,720,1098,551,1168,491,1280,414,1280,346,1280,252,1034,233,874,222,772,229,765,347,653,360,469,342,431,211,280,216,126,223,21,231,0,353
        objects:
          - person
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
      street_left:
        coordinates: 234,111,234,146,0,164,0,128
        objects:
          - person
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
      street:
        coordinates: 280,140,641,139,623,106,282,111
        objects:
          - person
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
      street_right:
        coordinates: 1149,136,1150,168,868,150,849,114
        objects:
          - person
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - front_driveway_yard
        - street_left
        - street
        - street_right
      crop: true
      height: 500
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 7
          mode: active_objects
        required_zones:
        - front_driveway_yard
        - street_left
        - street
        - street_right
        pre_capture: 4
        post_capture: 10

  garage_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtsp-restream-low-latency
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_cam_sub2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      - face
      - dog
      - cat
      - deer
      - car
      - amazon
      - fedex
      - ups
      filters:
        car:
          min_score: .65
          threshold: 0.8
        person:
          min_score: .65
          threshold: 0.8
        face:
          min_score: .7
        dog:
          min_score: .7
          threshold: 0.8
        cat:
          min_score: .65
          threshold: 0.8
        amazon:
          min_score: 0.75
        ups:
          min_score: 0.75
        fedex:
          min_score: 0.75
    live:
      stream_name: garage_cam_sub
    zones:
      garage_driveway_entrance:
        coordinates: 783,256,959,321,968,226,908,210
        objects:
          - person
          - face
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
        filters:
          person:
            threshold: 0.6
          car:
            threshold: 0.35
          dog:
            threshold: 0.6
          cat:
            threshold: 0.6
      garage_driveway:
        coordinates: 519,386,855,495,878,395,583,347
        objects:
          - person
          - face
          - dog
          - cat
          - deer
      garage_door:
        coordinates: 1015,95,1212,131,1136,720,951,720
        objects:
          - person
          - face
          - dog
          - cat
          - deer
      garage_back:
        coordinates: 264,351,946,524,880,720,0,720,0,357
        objects:
          - person
          - face
          - dog
          - cat
          - deer
      garage_neighbor:
        coordinates: 0,334,360,271,445,261,457,215,430,144,141,167,0,209
        objects:
          - person
          - face
          - dog
          - cat
          - deer
      garage_neighbor_entrance:
        coordinates: 667,199,668,232,790,219,762,194
        objects:
          - person
          - face
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
      garage_neighbor_yard:
        coordinates: 498,255,488,172,583,180,654,235
        objects:
          - person
          - face
          - dog
          - cat
          - deer
      garage_street:
        coordinates: 644,177,650,146,949,174,953,207
        objects:
          - person
          - face
          - car
          - dog
          - cat
          - deer
          - amazon
          - fedex
          - ups
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - garage_driveway_entrance
        - garage_door
        - garage_back
        - garage_neighbor
        - garage_neighbor_entrance
        - garage_street
      crop: true
      height: 500
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 7
          mode: active_objects
        required_zones:
        - garage_driveway_entrance
        - garage_door
        - garage_back
        - garage_neighbor
        - garage_neighbor_entrance
        - garage_street
        pre_capture: 4
        post_capture: 10

  door_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtsp-restream-low-latency
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/door_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/door_cam_sub2
          roles:
            - detect
    motion:
      mask:
      - 448,337,612,297,619,128,587,0,388,21
      - 815,370,942,406,1016,138,887,122
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      - face
      - dog
      - cat
      - package
      - amazon
      - fedex
      - ups
      filters:
        person:
          min_score: .65
          threshold: 0.8
        face:
          min_score: .7
        dog:
          min_score: .7
          threshold: 0.8
        cat:
          min_score: .65
          threshold: 0.8
        package:
          min_score: 0.65
          threshold: 0.8
        amazon:
          min_score: 0.75
        ups:
          min_score: 0.75
        fedex:
          min_score: 0.75
    live:
      stream_name: door_cam_sub
    zones:
      door_sidewalk:
        coordinates: 55,473,192,720,995,720,844,454,758,419,865,145,976,0,660,0,613,367,541,379,470,435
        objects:
          - person
          - face
          - dog
          - cat
          - package
          - amazon
          - fedex
          - ups
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - door_sidewalk
      crop: true
      height: 500
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 7
          mode: active_objects
        required_zones:
        - door_sidewalk
        pre_capture: 4
        post_capture: 10
  
  back_patio_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      input_args: preset-rtsp-restream-low-latency
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/back_patio_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_patio_cam_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
      - person
      - face
      - dog
      - cat
      - deer
      filters:
        person:
          min_score: .8
          threshold: 0.9
        face:
          min_score: .7
        dog:
          min_score: .7
          threshold: 0.8
        cat:
          min_score: .65
          threshold: 0.8
      mask: 283,127,411,134,424,52,283,79
    live:
      stream_name: back_patio_cam_balanced
    zones:
      back_yard:
        coordinates: 24,267,49,310,205,231,253,331,159,360,71,360,403,360,445,307,480,236,410,170,393,146,291,133
        objects:
          - person
          - face
          - dog
          - cat
          - deer
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 4
        post_capture: 10

  back_yard_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtsp-restream-low-latency
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_yard_cam_sub2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      - face
      - dog
      - cat
      - deer
      filters:
        person:
          min_score: .8
          threshold: 0.9
        face:
          min_score: .7
        dog:
          min_score: .7
          threshold: 0.8
        cat:
          min_score: .65
          threshold: 0.8
    live:
      stream_name: back_yard_cam_sub
    zones:
      back_yard:
        coordinates: 38,288,31,338,142,639,257,610,337,594,596,720,1280,720,1280,173,670,128,440,149,333,173,181,231
        objects:
          - person
          - face
          - dog
          - cat
          - deer
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 4
        post_capture: 10
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe
