### DISCUSSION TITLE
[Support]: Wind causes false positives in connection with covering a garden furniture.

### DISCUSSION THREAD

**Discussion by marc107** [blakeblackshear/frigate#10634] [General Support] [answered]
### Describe the problem you are having

Hello everyone,

I have been using frigate for some time now and am generally very satisfied with the detection rates. Today, however, I noticed two false positives: the cover of a piece of garden furniture was recognized as a person (apparently due to the wind today).
Below are the screenshots of todays scenes:
![image](https://github.com/blakeblackshear/frigate/assets/63843545/bf42226b-9908-4a78-a8e9-e2bb34975479)
![image](https://github.com/blakeblackshear/frigate/assets/63843545/ae1eda93-3521-48d3-b128-8356824b820d)

![image](https://github.com/blakeblackshear/frigate/assets/63843545/9699d192-4f19-4d82-8cda-2005cedd3c9c)

I have had more problems with false positives in the past and was able to minimize them significantly by setting max_ratio = 0.8.
Due to the high detection rate of these false positives (74% & 73%), I'm not sure if setting a threshold is a good idea.

Does anyone have an approach on how I can eliminate these false positives?

Thanks in advance!

Marc

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
   enabled: True
   host: 192.168.x.x

ffmpeg:
  hwaccel_args: preset-vaapi

database:
  path: /db/frigate.db
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:123@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True # <---- turn on detection

    motion:
      improve_contrast: True

    record: # <----- Enable recording
      enabled: True
      events:
        retain:
          default: 14
        pre_capture: 5
        post_capture: 5

    snapshots: # <----- Enable snapshots
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True

    objects:
      filters:
        person:
          min_ratio: 0
          max_ratio: 0.8
		  
detectors:
  coral:
    type: edgetpu
    device: usb

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Frigate stats

```json
none
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua
