### DISCUSSION TITLE
Live view laggy or stutter on iphone using wireless, but works smoothly on 5G signal

### DISCUSSION THREAD

**Discussion by eon0613** [blakeblackshear/frigate#10639] [General]
hi,

i have a reolink cameras, frigate live view is working smoothly on PC, LAPTOP and IPAD using wireless at home,viewed thru HA,
 However when i view it on my Iphone and Wife's iphone  thru home assistant  (using wireless) it is very LAGGY , but it works if i switch off the WIRELESS and just use 5G.

I am using GO2RTC and Coral TPU and have a very fast internet plan (1GB)

Hopefully someone can give me feedback, as i am working on this for 3 days and cant figure out what's wrong.

**FRIGATE CONFIG:**
```
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 192.168.1.134
  user: mqtt-user
  password: Leianne@1994
  port: 1883
  stats_interval: 300

record:
  expire_interval: 10

detect:
  annotation_offset: -800

go2rtc:
  streams:
    front_yard:
    - rtsp://admin:Leianne@1994@192.168.1.99:554/h264Preview_02_sub
    front_doorbell:
    - rtsp://admin:Leianne@1994@192.168.1.99:554/h264Preview_05_sub
    garage:
    - rtsp://admin:Leianne@1994@192.168.1.99:554/h264Preview_01_sub

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  front_yard:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_yard
        input_args: preset-rtsp-restream
        roles:
        - detect  
    detect:
      width: 896
      height: 512
      fps: 10
    objects:
      track:
      - person
      - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
 #     required_zones:
  #      - front_yard
      crop: true
      height: 500
      retain:
        default: 3
#    zones:
 #       front_yard_zone:
  #      coordinates: 505,131,604,128,611,459,466,459,361,480,188,480,298,284,179,261,242,210,320,138
        #inertia: 1

    motion:
      mask:
      - 640,0,640,41,451,40,450,0

  garage:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/garage
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 896
      height: 512
      fps: 10
    objects:
      track:
      - person
      - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      required_zones:
      - garage
      retain:
        default: 3
    motion:
      mask:
      - 441,42,640,43,640,0,444,0
    zones:
      garage_zone:
        coordinates: 640,0,640,480,201,480,156,301,112,0

  front_doorbell:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_doorbell
        input_args: preset-rtsp-restream
        roles:
        - detect   
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
      - person
      - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 3
    motion:
      mask:
      - 720,0,720,28,430,22,428,0

detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 1
  mode: objects
```
----------------------

Install method
Docker Compose

Coral version
edgetpu
usb
