### DISCUSSION TITLE
No Zoom control for EmpireTech Bullet Zoom Camera

### DISCUSSION THREAD

**Discussion by Ayuus** [blakeblackshear/frigate#10647] [Camera Support] [answered]
### Describe the problem you are having

I have connected an EmpireTech camera (Modified Dahua), type IPC-B54IR-Z4E-S3 to Frigate. Works OK, except for zoom in/out. The camera supports zoom via Onvif (no pan, no tilt). This works using other Onvif clients (I tested with HappySoft). 

However, no zoom buttons are visible for this camera in Frigate. I have also connected an other PTZ camera to Frigate, all controls (p, t and z) are visible for that camera.

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  port: 1883
#  port: 8883
#  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: false
  user: homeassistant
  password: <password>

logger:
  default: info
  logs:
    frigate.ptz.onvif: debug

detectors:
  coral:
    type: edgetpu
    device: usb
    
birdseye:
  enabled: false

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - cough
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event
      threshold: 0.8
    yell:
      threshold: 0.5
    scream:
      threshold: 0.5
    cough:
      threshold: 0.5

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 3
      mode: motion

go2rtc:
  streams:
    buitencamera_achterzijde:
    - rtsp://username:password@192.168.1.104:554/stream=1
    buitencamera_zijgevel:
    - rtsp://username:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps
 
cameras:
  buitencamera_achterzijde: # <--- this will be changed to your actual camera later
    ffmpeg:
      inputs:
      - path: rtsp://username:passwordr@192.168.1.104:554/stream=0
        roles:
        - audio
        - detect
        - record
    onvif: # necessary for ptz handling via frigate
      host: 192.168.1.104
      port: 8899
      user: username
      password: password
#      autotracking:
#        enabled: true
#        zooming: relative
#    motion:
#      mask:
#      - 1738,1017,1213,364

  buitencamera_zijgevel:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://username:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=2 #720p/5fps
        roles:
        - audio
        - detect
      - path: rtsp://username:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0 #4MP25fps
        roles:
        - record
    onvif: # necessary for ptz handling via frigate
      host: 192.168.1.108
      port: 80
      user: admin
      password: password
```

### Relevant log output

```shell
2024-03-24 14:59:42.873546020  [INFO] Preparing Frigate...
2024-03-24 14:59:42.950068447  [INFO] Starting Frigate...
2024-03-24 14:59:44.938412097  [2024-03-24 14:59:44] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-24 14:59:51.373224889  [2024-03-24 14:59:51] peewee_migrate.logs            INFO    : Starting migrations
2024-03-24 14:59:51.379613604  [2024-03-24 14:59:51] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-24 14:59:51.916825560  [2024-03-24 14:59:51] frigate.app                    INFO    : Recording process started: 306
2024-03-24 14:59:51.920737873  [2024-03-24 14:59:51] frigate.app                    INFO    : go2rtc process pid: 93
2024-03-24 14:59:51.946796144  [2024-03-24 14:59:51] detector.coral                 INFO    : Starting detection process: 316
2024-03-24 14:59:51.953469457  [2024-03-24 14:59:51] frigate.app                    INFO    : Output process started: 318
2024-03-24 14:59:52.040146271  [2024-03-24 14:59:52] frigate.app                    INFO    : Camera processor started for buitencamera_achterzijde: 332
2024-03-24 14:59:52.045998181  [2024-03-24 14:59:52] frigate.app                    INFO    : Camera processor started for buitencamera_zijgevel: 333
2024-03-24 14:59:52.051796357  [2024-03-24 14:59:52] frigate.app                    INFO    : Capture process started for buitencamera_achterzijde: 334
2024-03-24 14:59:52.066244056  [2024-03-24 14:59:52] frigate.app                    INFO    : Capture process started for buitencamera_zijgevel: 338
2024-03-24 14:59:52.066254068  [2024-03-24 14:59:52] frigate.app                    INFO    : Audio process started: 340
2024-03-24 14:59:54.566916161  [2024-03-24 14:59:51] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-24 14:59:54.572333080  [2024-03-24 14:59:54] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-03-24 15:00:35.658580802  [2024-03-24 15:00:35] frigate.ptz.onvif              DEBUG   : Onvif media xaddr for buitencamera_zijgevel: http://192.168.1.108/onvif/media_service
2024-03-24 15:00:35.659480241  [2024-03-24 15:00:35] frigate.ptz.onvif              DEBUG   : Onvif capabilities for buitencamera_zijgevel: ('http://192.168.1.108/onvif/ptz_service', '/usr/local/lib/python3.9/site-packages/wsdl/ptz.wsdl', '{http://www.onvif.org/ver20/ptz/wsdl}PTZBinding')
2024-03-24 15:00:35.712248751  [2024-03-24 15:00:35] frigate.ptz.onvif              ERROR   : No appropriate Onvif profiles found for camera: buitencamera_zijgevel.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":720,"width":1280},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1520,"width":2688},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
    "cameras": {
        "buitencamera_achterzijde": {
            "audio_dBFS": -71.9943,
            "audio_rms": 8.2364,
            "camera_fps": 5,
            "capture_pid": 334,
            "detection_enabled": 1,
            "detection_fps": 0,
            "ffmpeg_pid": 344,
            "pid": 332,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "buitencamera_zijgevel": {
            "audio_dBFS": -68.5554,
            "audio_rms": 12.2372,
            "camera_fps": 5,
            "capture_pid": 337,
            "detection_enabled": 1,
            "detection_fps": 14.9,
            "ffmpeg_pid": 345,
            "pid": 333,
            "process_fps": 5,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "21": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "80": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.9"
        },
        "101": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "110": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "13.0"
        },
        "116": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.8"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "147": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "148": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "149": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "295": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "5.8"
        },
        "306": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "8.1"
        },
        "315": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(47)",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "316": {
            "cmdline": "frigate.detector.coral",
            "cpu": "8.4",
            "cpu_average": "10",
            "mem": "8.1"
        },
        "318": {
            "cmdline": "frigate.output       ",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "7.3"
        },
        "321": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.9"
        },
        "325": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.9"
        },
        "332": {
            "cmdline": "frigate.process:buitencamera_achterzijde",
            "cpu": "1.7",
            "cpu_average": "2",
            "mem": "8.5"
        },
        "333": {
            "cmdline": "frigate.process:buitencamera_zijgevel",
            "cpu": "7.2",
            "cpu_average": "8",
            "mem": "9.0"
        },
        "334": {
            "cmdline": "frigate.capture:buitencamera_achterzijde",
            "cpu": "3.2",
            "cpu_average": "3",
            "mem": "7.3"
        },
        "337": {
            "cmdline": "frigate.capture:buitencamera_zijgevel",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "7.1"
        },
        "339": {
            "cmdline": "frigate.audio_manager",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "7.9"
        },
        "344": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.104:554/stream=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/buitencamera_achterzijde@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "22.0",
            "cpu_average": "21",
            "mem": "3.1"
        },
        "345": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.108:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "6.6",
            "cpu_average": "6",
            "mem": "2.0"
        },
        "351": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/buitencamera_zijgevel@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "1.2"
        },
        "352": {
            "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.104:554/stream=0 -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "1.1"
        },
        "355": {
            "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.108:554/cam/realmonitor?channel=1&subtype=2 -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "1.2"
        },
        "1502": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        }
    },
    "detection_fps": 14.9,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 9.13,
            "pid": 316
        }
    },
    "processes": {
        "audioDetector": {
            "pid": 339
        },
        "go2rtc": {
            "pid": 88
        },
        "logger": {
            "pid": 295
        },
        "recording": {
            "pid": 306
        }
    },
    "service": {
        "last_updated": 1711290551,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 90.3,
                "mount_type": "tmpfs",
                "total": 96,
                "used": 5.7
            },
            "/media/frigate/clips": {
                "free": 3565201.4,
                "mount_type": "btrfs",
                "total": 3651993.6,
                "used": 86792.2
            },
            "/media/frigate/recordings": {
                "free": 3565201.4,
                "mount_type": "btrfs",
                "total": 3651993.6,
                "used": 86792.2
            },
            "/tmp/cache": {
                "free": 948.2,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 5.5
            }
        },
        "temperatures": {},
        "uptime": 593,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

EmpireTech IPC-B54IR-Z4E-S3 variable zoom bullet camera

### Any other information that may be helpful

Frigate runs on Synology NAS. Runs seamless, except for zoom control.

**Comment by NickM-27** [comment]
We have made changes to the way that onvif is read for the next version of frigate, this will most likely fix this issue. Maybe @hawkeye217 has some additional opinion / insight

**Reply by hawkeye217** [reply]
Changes made for the next version should indeed fix this issue.

**Reply by Ayuus** [reply]
When is the next version expected?

**Reply by NickM-27** [reply]
there are already multiple betas out

**Comment by Ayuus** [comment]
I installed 0.14 beta3. What a beautiful en accurate user interface, thanks!
Do you have a screenshot available of the ptz controls in 0.14?
Regarding Onvif, I still get messages that camera does not support ptz. Camera does support zoom, checked with happysoft onvif client.

**Reply by NickM-27** [reply]
at this point if the zoom is not detected by frigate I don't believe there is anything we can do at the time being, according to the config frigate receives zoom is not supported

**Reply by NickM-27** [reply]
maybe check with empiretech about a firmware update, my empiretech zoom cameras have no issue

**Reply by Ayuus** [reply]
Maybe the detection is the dirrerence between HappySoft Onvif Client and Frigate?
Happysoft shows pan/tilt tools, too, even while camera does not support that. Zoom however, works OK in Happysoft.

**Comment by Ayuus** [comment]
Refer to attached image. No onvif errors during startup (for other camera that does not support onvif, logs do show up), but when displaying live image, log says "No appropriate Onvif profiles found for camera: buitencamera_zijgevel."

![no zoom controls](https://github.com/user-attachments/assets/4c0aad02-d59c-4906-a25a-26869fe4b2ba)

**Reply by hawkeye217** [reply]
Can you paste the debug log output from this camera when you start frigate?

```
logger:
  default: info
  logs:
    frigate.ptz.onvif: debug
```
