### DISCUSSION TITLE
ffmpeg copy mode and CPU usage

### DISCUSSION THREAD

**Discussion by groyee** [blakeblackshear/frigate#10643] [Config Support] [answered]
### Describe the problem you are having

I have my RTSP stream configured with copy mode which I assumed behaves like a passthrough, meaning no real intensive CPU required. However, it takes tons of my CPU. Pretty much 100% on HA green with only 2 cameras

Any ideas what can be the reason for that?

I guess I didn't really understand the ffmpeg copy mode?

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: admin
  stats_interval: 60
      
go2rtc:
  streams:
    living_room:
      - rtsp://admin:admin@192.168.1.43/live0 
      - "ffmpeg:living_room#video=copy#audio=copy"
    office:
      - rtsp://admin:admin@192.168.1.90:554/h264Preview_01_main
      - "ffmpeg:office#video=copy#audio=copy"

cameras:
  office:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/office
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: office
    onvif:
      host: 192.168.1.90
      port: 8000
      user: admin
      password: password
    snapshots: # <----- Enable snapshots
      enabled: True
    record: # <----- Enable recording
      enabled: True
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - rtmp
    live:
      stream_name: living_room
    snapshots: # <----- Enable snapshots
      enabled: True
    record: # <----- Enable recording
      enabled: False
record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
