### DISCUSSION TITLE
[Config Support]: Do zone parameters have priority over camera ones?

### DISCUSSION THREAD

**Discussion by jiiins** [blakeblackshear/frigate#10648] [Config Support]
### Describe the problem you are having

For a camera I have these settings:
```
    objects:
      filters:
        person:
          min_score: 0.60
          threshold: 0.67
    zones:
      zone_1:
        coordinates: 927,112,285,205,424,450,966,422
        filters:
          person:
            min_score: 0.60
            threshold: 0.67
            max_area: 5000
```
I would expect persons with size above 5000 to be excluded from zone_1, but they get detected anyway. What is the right way to accomplish this?

### Version

13.2

### Frigate config file

```yaml
not relevant
```

### Relevant log output

```shell
not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
