### DISCUSSION TITLE
[Config Support]: Help Dealing with Stationary Vehicle in Zone

### DISCUSSION THREAD

**Discussion by PablaV** [blakeblackshear/frigate#10669] [Config Support]
### Describe the problem you are having

I have a zone set up called 'driveway' and whenever a vehicle is parked as shown Frigate seems to at random note that the car has "left" and then later it says it entered and keeps repeating even though the car hasn't moved at all. Part of the back of the car is not in the zone but to my knowledge if the bottom part of the bounding box is in the zone that its considered inside it. I think it has something to do with the column that blocks part of the view of the car so the bounding box changes in size, but even with that the bounding box is still shown in the zone. 
<img width="719" alt="image" src="https://github.com/blakeblackshear/frigate/assets/82848440/98ebe3c0-868b-4db8-b0e4-6e3bf2c08dcf">
<img width="1066" alt="image" src="https://github.com/blakeblackshear/frigate/assets/82848440/7cc606cb-8865-4106-90b7-64308361d1ed">
<img width="1082" alt="image" src="https://github.com/blakeblackshear/frigate/assets/82848440/89cb4a34-2416-46c5-b78e-fa649be36295">
<img width="1040" alt="image" src="https://github.com/blakeblackshear/frigate/assets/82848440/14bd349f-b724-4858-9a31-b49a25803e15">
<img width="1040" alt="image" src="https://github.com/blakeblackshear/frigate/assets/82848440/2fe18dc1-b4e2-4ac7-ace3-bd359489767d">
<img width="1039" alt="image" src="https://github.com/blakeblackshear/frigate/assets/82848440/f0c3bd64-7493-4e8d-a23c-025d0b759765">

### Version

 0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.8.85
  port: 1883
  user: ****
  password: ***
cameras:
  front_doorbell:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/front_doorbell_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      mask:
      - 896,0,896,38,448,43,449,0
      - 417,67,608,64,732,42,783,116,684,162,627,322,176,310,146,116
    zones:
      driveway:
        coordinates: 896,672,896,223,621,263,620,374,350,368,167,353,158,254,0,184,0,672
      driveway_entrance:
        coordinates: 516,359,603,356,529,333,156,317,160,356,344,364
    snapshots:
      required_zones:
      - driveway
    objects:
      track:
      - person
      - car
      - dog
      - cat
      filters:
        car:
          min_area: 6000
        person:
          min_area: 2600
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 30
        post_capture: 30
        retain:
          default: 7
          mode: active_objects
        required_zones:
        - driveway
    detect:
      max_disappeared: 200
go2rtc:
  streams:
    front_doorbell:
    - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****#video=copy#audio=copy#audio=opus#async
    - rtsp://XXXX@192.168.8.186:554/h264Preview_01_sub
    front_doorbell_sub:
    - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXX&password=XXX

  webrtc:
    candidates:
    - 192.168.8.85:8555
    - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac #this allows audio in recordings 
  hwaccel_args: preset-vaapi
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
