### DISCUSSION TITLE
[Config Support]: Frigate in Docker on Linux Mint 23.1 on a MSFT Surface 5 with i5

### DISCUSSION THREAD

**Discussion by MilesAheadToo** [blakeblackshear/frigate#10666] [Config Support]
### Describe the problem you are having

I am struggling to get docker configured correctly. It is the first time I have used Docker so newbie alert. I've read the Frigate documentation and several other guides on the internet.

### Version

Latest version though I'm not operational yet

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  user: mqtt-user
  password: mqtt-pwd

database:
  path: /db/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: usb

detect:
  enabled: True
  width: 1920
  height: 1080
  stationary:
    interval: 2
    threshold: 50

objects:
  track:
    - person
    # - dog
    # - bicycle
    # - car

snapshots:
  enabled: True
  clean_copy: True
  crop: False
  bounding_box: True
  retain:
    default: 5

go2rtc:
  streams:
    doorbell:
      - rtsp://homeassistant.local:8554/T8210XXXXXXXXXXX
    front_door:
      - rtsp://homeassistant.local:8554/T8131XXXXXXXXXXX
    kitchen:
      - rtsp://homeassistant.local:8554/T8131XXXXXXXXXXX
    sunroom:
      - rtsp://homeassistant.local:8554/T8131XXXXXXXXXXX

live:
  height: 720
  quality: 8

#-------------------------------------------------------------------------------------------------
cameras:
  doorbell:
    audio:
      enabled: True
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:      
      inputs:
        - path: rtsp://homeassistant.local:8554/T8210XXXXXXXXXXX
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 1
    objects:
      track:
        - person

  front_door:
    audio:
      enabled: True
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:      
      inputs:
        - path: rtsp://homeassistant.local:8554/T8131XXXXXXXXXXX
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 1
    objects:
      track:
        - person

  kitchen:
    audio:
      enabled: True
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:      
      inputs:
        - path: rtsp://homeassistant.local:8554/T8131XXXXXXXXXXX
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 1
    objects:
      track:
        - person

  sunroom:
    audio:
      enabled: True
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:      
      inputs:
        - path: rtsp://homeassistant.local:8554/T8131XXXXXXXXXXXX
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 1
    objects:
      track:
        - person
```

### Relevant log output

```shell
trevor@DBServer:/mnt/1TB_SSD/frigate$ docker compose up
[+] Running 1/1
 ✔ Container frigate  Created                                              0.2s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-03-25 12:15:22.756282738  [INFO] Starting NGINX...
frigate  | 2024-03-25 12:15:22.757558351  [INFO] Preparing new go2rtc config...
frigate  | 2024-03-25 12:15:22.769697002  [INFO] Preparing Frigate...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-03-25 12:15:22.794305592  [INFO] Starting Frigate...
frigate  | 2024-03-25 12:15:23.152255732  [INFO] Starting go2rtc...
frigate  | 2024-03-25 12:15:23.311366689  12:15:23.311 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-03-25 12:15:23.312262130  12:15:23.312 INF [api] listen addr=:1984
frigate  | 2024-03-25 12:15:23.312552995  12:15:23.312 INF [rtsp] listen addr=:8554
frigate  | 2024-03-25 12:15:23.313008469  12:15:23.312 INF [webrtc] listen addr=:8555
frigate  | 2024-03-25 12:15:24.676320703  [2024-03-25 12:15:24] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-03-25 12:15:24.676436106  [2024-03-25 12:15:24] frigate.app                    INFO    : Creating directory: /config/model_cache
frigate  | 2024-03-25 12:15:24.744468228  unable to open database file
frigate  | 2024-03-25 12:15:24.744627409  [2024-03-25 12:15:24] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-03-25 12:15:26.069358998  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2024-03-25 12:15:26.081084287  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-03-25 12:15:26.138461791  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2024-03-25 12:15:26.142251717  exit with signal: terminated
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2024-03-25 12:15:26.146875637  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

This is my Docker compose file, which is where I suspect I have the problem.
'''
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation
    devices:
      - /dev/bus/usb:/dev/bus/usb 
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/1TB_SSD/frigate/config/frigate.yml:/config/config.yml:ro
      - /mnt/1TB_SSD/frigate/media:/media/frigate 
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      # - "1935:1935" # RTMP feeds – comment out if not needed , it may conflict with other containers
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_MQTT_USER: "mqtt-user"
      FRIGATE_MQTT_PASSWORD: "mqtt-user"
      # FRIGATE_RTSP_PASSWORD: #"password" #modify to whatever if using rtsp
```

**Comment by NickM-27** [comment]
your config mount is incorrect, it should be `- /mnt/1TB_SSD/frigate/config/:/config/` as the docs say the entire config directory needs to be passed in. Also, the name of the config file should be config.yml or config.yaml not frigate.yml

**Reply by MilesAheadToo** [reply]
Thanks @NickM-27 , though I am confused. Below is the exact example config.yml from the website at [this link](https://docs.frigate.video/frigate/installation):

I've highlighted the config line. They do not show the end /.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      **- /path/to/your/config:/config**
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"```
```

**Reply by NickM-27** [reply]
I am not sure what you mean by "the end"

**Reply by MilesAheadToo** [reply]
Your reply regarding the mounts was that I needed to use 

/mnt/1TB_SSD/frigate /config/:/config/

whereas following the documentation it would be

/mnt/1TB_SSD/frigate /config:/config

I've tried both, and both failed. I'm going to give it a rest for a bit.

**Reply by NickM-27** [reply]
it would be good to see the logs, those are essentially the same though I'd expect the space in there is what is causing the problem

**Reply by MilesAheadToo** [reply]
The space was just a typo. This is the compose.yaml
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation
    devices:
      - /dev/bus/usb:/dev/bus/usb 
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/1TB_SSD/frigate/config/:/config/
      - /mnt/1TB_SSD/frigate/media:/media/frigate 
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
   ```

This is the log. The "Connection refused error is continuing.
```
trevor@DBServer:/mnt/1TB_SSD/frigate$ docker compose up
[+] Running 1/1
 ✔ Container frigate  Created                                                                                                                                                                                                                                                      0.1s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2024-03-25 18:18:10.252779152  [INFO] Preparing new go2rtc config...
frigate  | s6-rc: info: service nginx successfully started
frigate  | 2024-03-25 18:18:10.262704551  [INFO] Preparing Frigate...
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-03-25 18:18:10.265923433  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-03-25 18:18:10.297999217  [INFO] Starting Frigate...
frigate  | 2024-03-25 18:18:10.722199784  [INFO] Starting go2rtc...
frigate  | 2024-03-25 18:18:10.826758326  18:18:10.826 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-03-25 18:18:10.827385851  18:18:10.827 INF [api] listen addr=:1984
frigate  | 2024-03-25 18:18:10.827419334  18:18:10.827 INF [rtsp] listen addr=:8554
frigate  | 2024-03-25 18:18:10.827700041  18:18:10.827 INF [webrtc] listen addr=:8555
frigate  | 2024-03-25 18:18:12.129628820  [2024-03-25 18:18:12] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-03-25 18:18:12.196584375  unable to open database file
frigate  | 2024-03-25 18:18:15.174530513  2024/03/25 18:18:15 [error] 138#138: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-25 18:18:20.219014044  2024/03/25 18:18:20 [error] 163#163: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-25 18:18:20.277168854  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-03-25 18:18:25.309343454  2024/03/25 18:18:25 [error] 141#141: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-25 18:18:30.341119299  2024/03/25 18:18:30 [error] 153#153: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-25 18:18:35.374847985  2024/03/25 18:18:35 [error] 138#138: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-25 18:18:40.408482046  2024/03/25 18:18:40 [error] 138#138: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-03-25 18:18:45.446179499  2024/03/25 18:18:45 [error] 138#138: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
```
