### DISCUSSION TITLE
Viewed events are disappearing (days: 0 is set)

### DISCUSSION THREAD

**Discussion by davidrylance** [blakeblackshear/frigate#10662] [General]
Hi folks,

I don't want to open a bug since I assume I'm doing something wrong. I want to keep everything in Events indefinitely (at least for now to see how much data it is using).

I set all numbers to zero (please see below) but I noticed that the events I watched yesterday disappeared (I guess deleted).

Could you please look at my config and tell me what's wrong?

``` yaml
# Frigate 0.13.2

mqtt:
  enabled: true
  host: localhost
  port: 1883
  topic_prefix: frigate

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

objects:
  track:
    - person

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 0
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 0

ui:
  time_format: 24hour
  strftime_fmt: '%Y-%m-%d %H:%M:%S'

cameras:
  first:
    motion:
      mask:
        - 640,0,640,84,640,139,640,197,640,231,640,251,602,231,588,210,563,194,534,184,506,171,482,163,465,147,442,134,423,125,400,119,370,111,345,105,315,93,294,87,267,75,239,77,212,78,187,81,147,89,95,89,0,91,0,64,0,31,0,0
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track: [person, bicycle, motorcycle]
    ffmpeg:
      inputs:
        - input_args: preset-rtsp-generic
          path: rtsp://.....Preview_01_main
          roles: [record]
        - input_args: preset-rtsp-generic
          path: rtsp://.....Preview_01_sub
          roles: [detect]
  # another cam ...

**Comment by NickM-27** [comment]
0 days means you essentially don't want them to be kept at all. There is no indefinite setting, you can just set a large number

**Comment by davidrylance** [comment]
Thank you.

Like this?
``` yaml
record:
  enabled: true
  retain:
    days: 9999
    mode: motion
  events:
    retain:
      default: 9999
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 9999
```

**Comment by ben-tiky** [comment]
Looking at the configuration reference, this should be
``` yaml
record:
  enabled: true
  retain:
    days: 0 # NOTE: This should be set to 0 and retention should be defined in events section
    mode: motion
  events:
    retain:
      default: 9999
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 9999
```
Could you please confirm @NickM-27 ?
