### DISCUSSION TITLE
Frigate failed to record an event that included assault on my neighbor

### DISCUSSION THREAD

**Discussion by comfuzio** [blakeblackshear/frigate#10664] [General]
Hi!
I am running frigate in Home Assistant OS over proxmox 8.1.5 host, I am passing through the coral tpu and I have a Dahua camera.
my config is:
```
mqtt:
  host: some-host
  user: someuser
  password: :somepass

cameras:
  entrance_camera_recording:
    ffmpeg:
      inputs:
        - path: rtsp://admin::somepass@someip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 2960
      height: 1668
      fps: 20

  entrance_camera_detection:
    ffmpeg:
      inputs:
        - path: rtsp://admin:somepass@someip:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      zone_0:
        coordinates: 447,381,635,194,704,241,619,576,387,576,302,576,261,474,238,388,182,123,258,93
    detect:
      width: 704
      height: 576
      fps: 20

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0
    threshold: 0.8  # Set the confidence threshold

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorbike
    - laptop
    - keyboard
    - mouse
    - tv

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

record:
  enabled: true
  retain:
    days: 3
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
        dog: 1
        cat: 1
        car: 1
        bird: 1
        tv: 1

birdseye:
  enabled: true
  width: 2960
  height: 1668
  quality: 8
  mode: continuous
```

Frigate is recording in all its area events, my cat, random cats, people, random people, cars etc! It has lots of false positives, way too many (mistakes my scooter for person for example all the time with 85% certainty!)
So this morning my parents told me that "people threw oranges at our home", I said ok let's investigate!
I went to the events and start looking where it recorded "person", none of the recorded people did anything wrong, just passing by or feeding the stray cats.
I start looking at other events such as cars (maybe a driveby orange shooting? who knows!) but nothing!
So I went by timestamps and I was seeing the orange all night but not before 22:00. I managed to see 2 events at 22:02 and the next 22:10. At the first it recording NOTHING as person, literally there is nothing moving! and at 22:10 a car parked across the street and left a few seconds later. So at 22:02 there no orange but at 22:10 there is an orange before the car appeared!
I was like what is going on here? Maybe people threw them from top to bottom (from the floor above) or someone from the side which I am not recording (wall covering it).
But luckily I have an sd card in the camera! So I have logged in the camera, went to the time between 22:03 and 22:10 and I get this recording (I have already send it to the police) https://www.youtube.com/watch?v=9nfl5gm62RI the event happen at 22:05:05.
3 teenagers threw oranges (perhaps other items as well) to my landlord who is a 95 years old lady with severe health issues!
luckily she didn't got frightened but thing could have been worse!
We have asked around and we got reports from almost in our area that strangers are throwing at them at night oranges/lemons and other heavy items creating damages to windows and even injuring animals.
Here I am, I have their faces.
BUT WHY DIDN'T FRIGATE RECORDED THEM?
It literally records the NOTHING but didn't record such a severe incident?

Please, I ask for assistance on how to minimize false recordings and to get actual recordings of acts of violence!

**Comment by comfuzio** [comment]
Let me post some pictures from Frigate and from the camera:
![image](https://github.com/blakeblackshear/frigate/assets/30821243/0f1dae7c-04d2-4e97-87bd-7f77fb3c9f18)
Frigate doesn't detect an event/recording in the timeframe which the event happen
![image](https://github.com/blakeblackshear/frigate/assets/30821243/da19978e-b5bb-46af-a95e-6d42301f2b76)
Dahua camera does have a recording and more specifically the recording I have uploaded to youtube and send to police

**Comment by NickM-27** [comment]
I see some things in the config that may be contributing to issues, I would suggest making some changes

1. The detect fps is set to 20, this should be much lower like 5 or at most 10. This does not need to match the fps of the camera and running at such high fps means the system likely is falling behind on detection. 
2. the same camera is defined twice in the config, this does not make sense, it should only have the camera defined once with multiple streams [see example in docs](https://docs.frigate.video/guides/getting_started#record)
3. if the goal is to ensure nothing is missed then I would recommend motion based recording https://docs.frigate.video/configuration/record#reduced-storage-only-saving-video-when-motion-is-detected
4. `threshold: 0.8  # Set the confidence threshold` can be removed, that config does not exist on detectors

**Reply by comfuzio** [reply]
I have set the primary feed of the camera on high detail for recordings to be as clear as they can be and I have set the detect to the 2nd feed that the camera produces at lower values, that's why it is stated there 2 times.
Other events it records them without issues in real time. If this attack didn't happen last night and I didn't have to investigate to see what happen, I can't tell you that I saw any other issue. Also if it is behind in detection, logic dictates that I would have seen this recording somewhere down the line....it isn't anywhere to be seen and believe me, I have used lots of time today in this.
what would an ideal config be in a setup like this?

**Reply by NickM-27** [reply]
> I have set the primary feed of the camera on high detail for recordings to be as clear as they can be and I have set the detect to the 2nd feed that the camera produces at lower values, that's why it is stated there 2 times.

Yes but you created the camera twice so you are actually recording and running object detection two times. This is my point. You should only have one camera defined with separate streams for record and detection. 

> Also if it is behind in detection, logic dictates that I would have seen this recording somewhere down the line....it isn't anywhere to be seen and believe me, I have used lots of time today in this.

No, that is incorrect. Frigate prioritizes real time tracking so if it falls behind then it skips detection so that it can keep up.

**Reply by NickM-27** [reply]
I would recommend this as the config to simplify the issues I mentioned above

```yaml
mqtt:
  host: some-host
  user: someuser
  password: :somepass

cameras:
  entrance_camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin::somepass@someip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:somepass@someip:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      zone_0:
        coordinates: 447,381,635,194,704,241,619,576,387,576,302,576,261,474,238,388,182,123,258,93
    detect:
      width: 704
      height: 576
      fps: 5

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorbike
    - laptop
    - keyboard
    - mouse
    - tv

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
        dog: 1
        cat: 1
        car: 1
        bird: 1
        tv: 1

birdseye:
  enabled: true
  width: 2960
  height: 1668
  quality: 8
  mode: continuous
```

**Reply by comfuzio** [reply]
Thanks! Let me try that! I just hope won't need it for acts of violence ever again!
Quick question about the lagging behind, during the time of the event, there was no other event taking place at the same time. Frigate is completely empty in that timeframe of 22:00 to 22:15 and the event took place at 22:05, what could have caused a lagging there and it doesn't when it actually records events?
Full philosophical question, not an accusation of any sorts!

**Reply by comfuzio** [reply]
Also the birdseye view does this
![image](https://github.com/blakeblackshear/frigate/assets/30821243/08bde8be-3fd2-4c1b-9155-beb6fa6ccd69)
it did that if I recall correctly ever since frigate went to 0.13.x it starts as gray feed and the color seems to be coming from the bottom moving upwards and then becomes like that 
![image](https://github.com/blakeblackshear/frigate/assets/30821243/c949cbb5-f57f-403b-81e7-aa904d32fa0b)
never gets fixed

**Reply by NickM-27** [reply]
With a detect fps of 20 that means frigate must analyze 20 frames every second which means detecting motion and then running object detection. Even if no objects are detected, it still has to do that work which is a lot especially given that it was running detect at 2960x1668.

You can check all of this in the system page of the webUI

**Reply by NickM-27** [reply]
I'd recommend removing the width and height from the birdseye config, that should fix it

**Reply by comfuzio** [reply]
Yeap that did the trick, but how can I view in good quality now live video without having to go to the camera's UI?
Now birdseye and cameras show very low quality video, sure the recording seems to be perfect but the live feed is very low.
I think this is why I had the dimensions there so I can get good quality live feed

**Reply by NickM-27** [reply]
you configure go2rtc https://docs.frigate.video/guides/configuring_go2rtc

**Reply by NickM-27** [reply]
https://docs.frigate.video/configuration/live

**Reply by comfuzio** [reply]
so something like that in the config?

```
mqtt:
  host: some-host
  user: someuser
  password: somepass

cameras:
  entrance_camera:
    ffmpeg:
      inputs:
        - path: rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - go2rtc_back
        - path: rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      zone_0:
        coordinates: 447,381,635,194,704,241,619,576,387,576,302,576,261,474,238,388,182,123,258,93
    detect:
      width: 704
      height: 576
      fps: 5

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorbike
    - laptop
    - keyboard
    - mouse
    - tv

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
        dog: 1
        cat: 1
        car: 1
        bird: 1
        tv: 1

birdseye:
  enabled: true
  quality: 8
  mode: continuous

go2rtc:
  streams:
    back:
      - rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=0
```

**Reply by NickM-27** [reply]
no, that is not correct. there is no role `go2rtc_`, that is nowhere in the docs. You simply need to make the names of the cameras match. so 

```
go2rtc:
  streams:
    entrance_camera: rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=0
```

**Comment by comfuzio** [comment]
> no, that is not correct. there is no role `go2rtc_`, that is nowhere in the docs. You simply need to make the names of the cameras match. so
> 
> ```
> go2rtc:
>   streams:
>     entrance_camera: rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=0
> ```
so something like that:

```
mqtt:
  host: some-host
  user: someuser
  password: somepass

cameras:
  entrance_camera:
    ffmpeg:
      inputs:
        - path: rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      zone_0:
        coordinates: 447,381,635,194,704,241,619,576,387,576,302,576,261,474,238,388,182,123,258,93
    detect:
      width: 704
      height: 576
      fps: 5

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorbike
    - laptop
    - keyboard
    - mouse
    - tv

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
        dog: 1
        cat: 1
        car: 1
        bird: 1
        tv: 1

birdseye:
  enabled: true
  quality: 8
  mode: continuous

go2rtc:
  streams:
    entrance_camera:
      - rtsp://someuser:somepass@someip:554/cam/realmonitor?channel=1&subtype=0
  ```
