### DISCUSSION TITLE
[Support]: Single stationay car in driveway detected twice

### DISCUSSION THREAD

**Discussion by rssindian** [blakeblackshear/frigate#10674] [General Support] [answered]
### Describe the problem you are having

I have a single car parked in my driveway, frigate identifies one car as two car during night vision. Because of this, the entered zones are updated very often leading to car parking alert. 

![image](https://github.com/blakeblackshear/frigate/assets/68811565/0a8b7e47-0a08-4a3d-84e7-4816703f4487)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.*.*.*
  port: 1883
  user: ****************
  password: ************

ffmpeg:
  #hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

ui:
  live_mode: jsmpeg
  use_experimental: false

timestamp_style:
  format: ""

rtmp:
  enabled: false

birdseye:
  enabled: false

go2rtc:
  streams:
    FrontCamera_High:
      - rtsp://***:***@192.*.*.*:554/live/ch0
cameras:
  FrontCamera:
    ui:
      order: 0

    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/FrontCamera_High'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
            - record

    live:
      quality: 1

    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - yell
        - talk

    detect:
      enabled: true
      fps: 5

    motion:
      threshold: 40
      frame_height: 80
      contour_area: 30
      mask:
        - 829,1296,630,1078,699,492,1640,319,2304,843,2304,0,0,0,0,1296
    
    zones:
      Car_Zone_1:
        coordinates: 613,792,2018,527,1627,291,689,470
        objects:
          - car
      Car_Zone_2:
        coordinates: 573,1296,2304,971,1820,565,629,776
        inertia: 5
        objects:
          - car
      Person_Zone_1:
        coordinates: 731,498,1585,341,2015,644,705,901
        objects:
          - person
          - cat
          - dog
      Person_Zone_2:
        coordinates: 1992,636,2304,873,2304,1296,551,1296,697,896
        objects:
          - person
          - cat
          - dog

    objects:
      track:
        - person
        - car
        - cat
        - dog

      filters:
        car:
          mask:
            - 2304,943,495,1296,681,473,1612,286,2304,943,2304,0,0,0,0,1296,2304,1296
        person:
          mask:
            - 2304,0,0,0,0,1296,577,773,657,499,1559,331,2304,828
        cat:
          mask:
            - 768,0,0,0,0,432,194,432,291,207,515,146,768,317
        dog:
          mask:
            - 768,0,0,0,0,432,194,432,291,207,515,146,768,317

    record:
      sync_recordings: true
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        post_capture: 15
        objects:
          - car
          - person
          - cat
        required_zones:
          - Car_Zone_1
          - Person_Zone_1
          - Person_Zone_2
        retain:
          default: 7
          mode: active_objects

    snapshots:
      enabled: true
      bounding_box: true
      quality: 100
      retain:
        default: 7
        objects:
          person: 30
          car: 30
          cat: 30
      required_zones:
        - Car_Zone_1
        - Person_Zone_1
        - Person_Zone_2
```

### Relevant log output

```shell
2024-03-25 21:24:21.390754868  [INFO] Preparing Frigate...
2024-03-25 21:24:21.447597274  [INFO] Starting Frigate...
2024-03-25 21:24:24.155346643  [2024-03-25 21:24:24] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-25 21:24:24.155456669  [2024-03-25 21:24:24] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-03-25 21:24:30.569538193  [2024-03-25 21:24:30] peewee_migrate.logs            INFO    : Starting migrations
2024-03-25 21:24:30.576916940  [2024-03-25 21:24:30] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-25 21:24:30.592680349  [2024-03-25 21:24:30] frigate.app                    INFO    : Recording process started: 478
2024-03-25 21:24:30.596973085  [2024-03-25 21:24:30] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-25 21:24:30.626436051  [2024-03-25 21:24:30] detector.coral                 INFO    : Starting detection process: 488
2024-03-25 21:24:33.691975770  [2024-03-25 21:24:30] frigate.app                    INFO    : Output process started: 490
2024-03-25 21:24:33.692195322  [2024-03-25 21:24:30] frigate.app                    INFO    : Camera processor started for FrontCamera: 499
2024-03-25 21:24:33.697190205  [2024-03-25 21:24:30] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-03-25 21:24:33.697406007  [2024-03-25 21:24:30] frigate.app                    INFO    : Camera processor started for BackCamera: 501
2024-03-25 21:24:33.697515964  [2024-03-25 21:24:33] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-03-25 21:24:33.697689802  [2024-03-25 21:24:30] frigate.app                    INFO    : Camera processor started for HallCamera: 510
2024-03-25 21:24:33.697804817  [2024-03-25 21:24:30] frigate.app                    INFO    : Capture process started for FrontCamera: 511
2024-03-25 21:24:33.697960137  [2024-03-25 21:24:30] frigate.app                    INFO    : Capture process started for BackCamera: 516
2024-03-25 21:24:33.698092848  [2024-03-25 21:24:30] frigate.app                    INFO    : Capture process started for HallCamera: 520
2024-03-25 21:24:33.698221819  [2024-03-25 21:24:30] frigate.app                    INFO    : Audio process started: 525
2024-03-25 21:24:36.672991194  [2024-03-25 21:24:36] frigate.comms.dispatcher       ERROR   : Turning off motion is not allowed when detection is enabled.
2024-03-25 21:24:36.714946335  [2024-03-25 21:24:36] frigate.comms.dispatcher       INFO    : Turning off detection for HallCamera
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.6-0+deb11u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55eae6618a00] max delay reached. need to consume packet
[rtsp @ 0x55eae6618a00] RTP: missed 3 packets
Input #0, rtsp, from 'rtsp://*****:*****@192.*.*.*:554/live/ch0':
  Metadata:
    title           : hysxrtpsion
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 2304x1296, 15 fps, 15 tbr, 90k tbn, 15 tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{
    "bandwidth_usages": {
        "89": {
            "bandwidth": 141.4
        }
    },
    "cameras": {
        "BackCamera": {
            "audio_dBFS": -61.0831,
            "audio_rms": 28.9264,
            "camera_fps": 5.1,
            "capture_pid": 516,
            "detection_enabled": 1,
            "detection_fps": 0,
            "ffmpeg_pid": 521,
            "pid": 501,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "FrontCamera": {
            "audio_dBFS": -56.4281,
            "audio_rms": 49.4361,
            "camera_fps": 5.1,
            "capture_pid": 511,
            "detection_enabled": 1,
            "detection_fps": 1,
            "ffmpeg_pid": 517,
            "pid": 499,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "HallCamera": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 520,
            "detection_enabled": 0,
            "detection_fps": 0,
            "ffmpeg_pid": 526,
            "pid": 510,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "79": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "2.9",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "111": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "1.9",
            "cpu_average": "13",
            "mem": "2.6"
        },
        "117": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "118": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "152": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "162": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "178": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "196": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "223": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "239": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "448": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "478": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "487": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(51)",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "488": {
            "cmdline": "frigate.detector.coral",
            "cpu": "1.1",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "490": {
            "cmdline": "frigate.output       ",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "1.0"
        },
        "496": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "497": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "499": {
            "cmdline": "frigate.process:FrontCamera",
            "cpu": "4.5",
            "cpu_average": "3",
            "mem": "1.2"
        },
        "500": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "501": {
            "cmdline": "frigate.process:BackCamera",
            "cpu": "1.0",
            "cpu_average": "1",
            "mem": "1.1"
        },
        "510": {
            "cmdline": "frigate.process:HallCamera",
            "cpu": "1.1",
            "cpu_average": "0",
            "mem": "0.9"
        },
        "511": {
            "cmdline": "frigate.capture:FrontCamera",
            "cpu": "3.0",
            "cpu_average": "2",
            "mem": "0.9"
        },
        "516": {
            "cmdline": "frigate.capture:BackCamera",
            "cpu": "3.3",
            "cpu_average": "3",
            "mem": "0.9"
        },
        "517": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/FrontCamera_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/FrontCamera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2304:1296 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "24.1",
            "cpu_average": "20",
            "mem": "0.5"
        },
        "520": {
            "cmdline": "frigate.capture:HallCamera",
            "cpu": "3.8",
            "cpu_average": "3",
            "mem": "0.9"
        },
        "521": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/BackCamera_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/BackCamera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2304:1296 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "23.6",
            "cpu_average": "23",
            "mem": "0.6"
        },
        "525": {
            "cmdline": "frigate.audio_manager",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "526": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/HallCamera_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/HallCamera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "11.9",
            "cpu_average": "11",
            "mem": "0.3"
        },
        "532": {
            "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/FrontCamera_High -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "535": {
            "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/BackCamera_High -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "5290": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 1,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 8.44,
            "pid": 488
        }
    },
    "processes": {
        "audioDetector": {
            "pid": 525
        },
        "go2rtc": {
            "pid": 89
        },
        "logger": {
            "pid": 448
        },
        "recording": {
            "pid": 478
        }
    },
    "service": {
        "last_updated": 1711403003,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 7925,
                "mount_type": "tmpfs",
                "total": 7938.6,
                "used": 13.5
            },
            "/media/frigate/clips": {
                "free": 84300.4,
                "mount_type": "fuseblk",
                "total": 715404,
                "used": 631103.5
            },
            "/media/frigate/recordings": {
                "free": 84300.4,
                "mount_type": "fuseblk",
                "total": 715404,
                "used": 631103.5
            },
            "/tmp/cache": {
                "free": 7936.9,
                "mount_type": "tmpfs",
                "total": 7938.6,
                "used": 1.7
            }
        },
        "temperatures": {},
        "uptime": 1133,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

GALAYOU 2K Security Camera, Y4
