### DISCUSSION TITLE
[Config Support]: Unusual timestamp in Events page

### DISCUSSION THREAD

**Discussion by artlov** [blakeblackshear/frigate#10686] [Config Support]
### Describe the problem you are having

In event description during timeperiod 00:00 - 00:59 it shows as 24:00-24:59, which is unusual, at least in our region :)
![Screenshot 2024-03-26 151950](https://github.com/blakeblackshear/frigate/assets/6746304/db8b7742-7659-4d3f-a052-c3d0588eeb4f)

### Version

0.13.2

### Frigate config file

```yaml
timestamp_style:
  position: "tl"
  format: "%Y-%m-%d %H:%M:%S"

ui:
  use_experimental: false
  time_format: 24hour
  date_style: medium
  time_style: medium
```

### Relevant log output

```shell
nothing to paste
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB
