### DISCUSSION TITLE
[Config Support]: Recording & Detection OK but Frigate seems to not take into account MASK and BOX

### DISCUSSION THREAD

**Discussion by AURELB87** [blakeblackshear/frigate#10691] [Config Support]
### Describe the problem you are having

Hello,

My Frigate is working well (with camera REOLING 823A) but it doesn't take into account all my settings. For example, I am receiving on my telegram pictures or recordings but without "yellow box". (Pictures sent are not very good in terms of resolution: may I improve this point too ?)

I also set a mask but it doesn't seems to work because I still have car from the road which are detected.

My frigate is working on LXC container and it's linked with my Home assistant.

As I said, it's working fine but I think I am missing something in my configuration.

Please find below my configuration for comments.

Many thanks for your help.
Aurel

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

logger:
  # Optional: default log level (debug, info, warning, error,critical)
  default: info

cameras:
  NOMCAM:
    ffmpeg:
      inputs:
      - path: rtsp://USER:PASSWORD@IP:554/h264Preview_01_sub
        roles:
        - detect
      - path: rtsp://USER:PASSWORD@IP:554/h264Preview_01_main
        roles:
        - record
    objects:
      track:
      - person
      filters:
        person:
          mask:
          - 251,521,366,630,231,867,108,789
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        required_zones:
        - inter_droite
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      required_zones:
      - inter_droite
    motion:
      mask:
      - 0,0,1484,0,1920,0,1920,348,1834,324,1733,312,1737,168,1567,140,1516,134,1496,203,797,186,725,173,735,262,273,279,237,176,215,189,0,246
    zones:
      inter_droite:
        coordinates: 
          1920,1080,1920,326,1708,293,1531,268,1481,214,739,189,742,265,267,287,235,198,0,256,0,1080
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 15
      stationary:
        interval: 50
        threshold: 50
```

### Relevant log output

```shell
No error in logs
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
