### DISCUSSION TITLE
[HW Accel Support]:

### DISCUSSION THREAD

**Discussion by DougLorenz** [blakeblackshear/frigate#10694] [Hardware Acceleration Support]
### Describe the problem you are having

Running under TrueNAS, using the Truecharts app.  

In the VAINFO output, it lists a file "/usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so" as not found, but there is a file in that directory named "radeonsi_dri.so".

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.1.1.6:5000/api/config/schema.json

mqtt:
  enabled: true
  host: 10.1.1.9
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigatemqtt
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    garage:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.31:554/cam/realmonitor?channel=1&subtype=0
    garage_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.31:554/cam/realmonitor?channel=1&subtype=1
    front_porch:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.32:554/cam/realmonitor?channel=1&subtype=0
    front_porch_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.32:554/cam/realmonitor?channel=1&subtype=1
    east_side_yard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.33:554/cam/realmonitor?channel=1&subtype=0
    east_side_yard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.33:554/cam/realmonitor?channel=1&subtype=1
    driveway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.34:554/cam/realmonitor?channel=1&subtype=0
    driveway_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.34:554/cam/realmonitor?channel=1&subtype=1
    front_yard_ptz:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.35:554/cam1/h264major
    front_yard_ptz_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.35:554/cam1/h264minor
    front_gate_doorbell:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.50:554/cam/realmonitor?channel=1&subtype=0
    front_gate_doorbell_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.50:554/cam/realmonitor?channel=1&subtype=1
    front_doorbell:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.51:554/cam/realmonitor?channel=1&subtype=0
    front_doorbell_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.51:554/cam/realmonitor?channel=1&subtype=1
    den:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.52:554/cam/realmonitor?channel=1&subtype=0
    den_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.1.52:554/cam/realmonitor?channel=1&subtype=1

birdseye:
  enabled: true
  restream: true
  width: 3840
  height: 2160
  quality: 2
  mode: continuous

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
#  coral_usb:
#    type: edgetpu
#    device: usb
#  coral_pci1:
#    type: edgetpu
#    device: pci:0
#  coral_pci2:
#    type: edgetpu
#    device: pci:1

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - boat
    - bird
    - cat
    - dog
    - cell phone
    - tie
    - book

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  retain:
    default: 10
    objects:
      person: 15

cameras:

  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_porch
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

  east_side_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/east_side_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/east_side_yard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

  front_yard_ptz:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard_ptz_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_yard_ptz
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false
      width: 640
      height: 480

  front_gate_doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_gate_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_gate_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

  front_doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

  den:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/den_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/den
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 10
    mode: all

ui:
  live_mode: mse
  use_experimental: false
```

### docker-compose file or Docker CLI command

```yaml
Not using docker compose.  Using TrueNAS app.
```

### Relevant log output

```shell
VAINFO OUTPUT
Return Code: 3

Process Error:

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
pci id for fd 3: 1a03:2000, driver (null)
pci id for fd 4: 1a03:2000, driver (null)
kmsro: driver missing
libva error: /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
COPY
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Multiple amcrest
