### DISCUSSION TITLE
[Support]: Unraid, Frigate Container, and Multiple Networks (VLANs)

### DISCUSSION THREAD

**Discussion by VanGoghComplex** [blakeblackshear/frigate#10715] [General Support]
### Describe the problem you are having

I'm trying to migrate my NVR setup from Blue Iris (which requires a Windows VM) to Frigate. I've been able to set up a boilerplate config.yml and launch Frigate without error, visit the web UI, etc.

My problem is that I have a separate VLAN for my cameras, which are PoE IP cameras. My server, a Dell T430, has two NICs. One is connected to my home network (main VLAN) and the other is connected to my camera VLAN in my managed switch. This may be more a Docker question than a Frigate question, but how do I get Frigate to serve its web interface on my Home VLAN and pull camera feeds from the camera VLAN? In my Blue Iris Windows VM, I've just got two virtual NICs, one of which is being passed from the host's physical NIC that's attached to the camera network.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
cameras:
  Front_Door: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://10.1.2.10:554/rtsp
          roles:
            - detect
    detect:
      enabled: False # <--- disable detection until you have a working camera feed
```

### Relevant log output

```shell
2024-03-27 20:26:27.281818297  [2024-03-27 20:26:27] frigate.video                  ERROR   : Front_Door: Unable to read frames from ffmpeg process.
2024-03-27 20:26:27.281971169  [2024-03-27 20:26:27] frigate.video                  ERROR   : Front_Door: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
10.1.2.10: No such file or directory
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest PoE IP camera

### Any other information that may be helpful

I've got my camera network set up as a custom IPV4 network in Unraid's Docker config page, and am able to assign Frigate to that network type when starting. It doesn't seem to be able to see the cameras from there either based on the log, but aside from that, I can't reach the web UI that way either.
