### DISCUSSION TITLE
Can't get video over WebRTC from remote ip

### DISCUSSION THREAD

**Discussion by groyee** [blakeblackshear/frigate#10736] [Config Support] [answered]
### Describe the problem you are having

I kinda gave up on MSE as I just can't get audio to work with MSE.

Audio in WebRTC works fine. WebRTC works fine on LAN but the moment I try to access externally it doesn't work. 

In the documentation it says to forward port 8555 tcp/udp in the router. I did that. Still doesn't work

https://docs.frigate.video/configuration/live/#audio-support

Not sure where else to look

Maybe 127.0.0.1 in the config is wrong?

### Version

0.13.2

### Frigate config file

```yaml
go2rtc:
  streams:
    living_room:
      - rtsp://admin:admin@192.168.1.43/live0 
      - "ffmpeg:living_room#video=copy#audio=opus" 
  cameras:
    living_room:
      ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - rtmp
    live:
      stream_name: living_room
    snapshots: 
      enabled: True
    record: # 
      enabled: False
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You need to configure webrtc https://docs.frigate.video/configuration/live#webrtc-extra-configuration

**Comment by groyee** [comment]
Hm.... yeah, it's same URL I shared I think.

It just says for external access to configure port forwarding

_For external access, over the internet, setup your router to forward port 8555 to port 8555 on the Frigate device, for both TCP and UDP._

Still doesn't work

<img width="865" alt="Screenshot 2567-03-29 at 22 40 53" src="https://github.com/blakeblackshear/frigate/assets/194016/6b334eaf-b997-4289-9474-251c96804aba">

**Reply by NickM-27** [reply]
you need to set your webrtc candidates including setting `stun:8555` if that doesn't work then you may be on a symmetric nat while off the LAN

**Comment by groyee** [comment]
That' the go2rtc.yml that I see from frigate:

```
api:
  origin: '*'
ffmpeg:
  h264/rk: -c:v h264_rkmpp_encoder -g 50 -bf 0
  h265/rk: -c:v hevc_rkmpp_encoder -g 50 -bf 0
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
    -rtsp_transport tcp -i {input}
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  living_room:
  - rtsp://admin:admin@192.168.1.43/live0
  - ffmpeg:living_room#video=copy#audio=opus
webrtc:
  candidates:
  - 192.168.1.72:8555
  - stun:8555

```

No idea what is symmetric nat... will go read about it now :-)

**Comment by groyee** [comment]
The good news I am not behind symmetric nat. That bad news, I still don't have video

https://tomchen.github.io/symmetric-nat-test/

<img width="750" alt="Screenshot 2567-03-29 at 22 52 59" src="https://github.com/blakeblackshear/frigate/assets/194016/c5601aa6-73a7-4c79-9b6e-ded311f14981">

Which logs should I search? The HA one or Frigate? Maybe I will find something there...

**Reply by NickM-27** [reply]
I would start by trying to view webrtc and opening the `streams info` from the frigate system page then paste that here

**Comment by groyee** [comment]
Very interesting problem

First of all no errors at all:

2024-03-29 16:08:30.702437049  [INFO] Preparing Frigate...
2024-03-29 16:08:31.486410628  [INFO] Starting Frigate...
2024-03-29 16:08:42.594394923  [2024-03-29 23:08:42] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-29 16:08:42.595484012  [2024-03-29 23:08:42] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-03-29 16:08:45.184629946  [2024-03-29 23:08:45] peewee_migrate.logs            INFO    : Starting migrations
2024-03-29 16:08:45.209095078  [2024-03-29 23:08:45] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-29 16:08:49.359878270  [2024-03-29 23:08:49] frigate.app                    INFO    : Recording process started: 320
2024-03-29 16:08:49.380458964  [2024-03-29 23:08:49] frigate.app                    INFO    : go2rtc process pid: 89
2024-03-29 16:08:49.494063451  [2024-03-29 23:08:49] detector.cpu                   INFO    : Starting detection process: 330
2024-03-29 16:08:49.494991248  [2024-03-29 23:08:49] frigate.app                    INFO    : Output process started: 332
2024-03-29 16:08:49.541366790  [2024-03-29 23:08:49] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-03-29 16:08:49.606145431  [2024-03-29 23:08:49] frigate.app                    INFO    : Camera processor started for office: 337
2024-03-29 16:08:49.609585366  [2024-03-29 23:08:49] frigate.app                    INFO    : Capture process started for office: 338
2024-03-29 16:10:34.565104945  [2024-03-29 23:10:34] frigate.ptz.onvif              WARNING : Disabling autotracking zooming for office: Relative zoom not supported


What's interesting that if I try to watch Live view:

<img width="1214" alt="Screenshot 2567-03-29 at 23 22 23" src="https://github.com/blakeblackshear/frigate/assets/194016/90412ea7-5717-4877-b673-52f4f0c72180">


Then the stream is just trying to load forever, no errors. Looking at Chrome console, I see a Websocket connection in pending state
<img width="1723" alt="Screenshot 2567-03-29 at 23 19 15" src="https://github.com/blakeblackshear/frigate/assets/194016/1a6fbf6f-fd42-48b8-bc37-9247a036ae65">


But if I switch to Debug mode then all works but I don't believe debug mode is WebRTC, it looks like it is using some MJPEG or something

<img width="1217" alt="Screenshot 2567-03-29 at 23 24 11" src="https://github.com/blakeblackshear/frigate/assets/194016/9d335d3e-bf20-4e02-8601-e8e465a0bd24">

One more thing. When I clicked the link for symmetric nat I clicked on the link from my Desktop at home over LAN (Same as HA Green). I hope that what I was supposed to do. If I click this link from external network (4g) then I get symmetric nat.

**Reply by NickM-27** [reply]
the NAT type is to do with how you are connecting. So with a symmetric nat on 4g it will not be able to use webrtc. I can try to help you get audio going in mse

**Comment by groyee** [comment]
Thanks!!!

MSE it is... :-) 

That would be awesome but I don't know what data I can provide to you because it doesn't work on iPhone (iOS 17.4). On the desktop (4G external connection) MSE works fine with audio.

Is there anything I can send to you so you can see what is the problem?

**Reply by NickM-27** [reply]
are you saying mse doesn't work at all on your iphone or just not audio?

**Reply by groyee** [reply]
Just the audio. Video works fine

**Reply by NickM-27** [reply]
let's do what I said before, start an mse stream on the iPhone and then press stream info in the top right of the system page and paste that here

**Reply by groyee** [reply]
From the frigate it works :-) Good to know. No errors in the log and I get audio

But from the frigate card in HA doesn't work. It doesn't even have the volume icon.

Frigate card on Desktop (There is volume icon)
<img width="339" alt="Screenshot 2567-03-30 at 00 00 04" src="https://github.com/blakeblackshear/frigate/assets/194016/411a5f1d-5f78-4e39-bf7b-0da54a1a70b4">

Frigate card on iOS (No volume icon)
<img width="430" alt="Screenshot 2567-03-30 at 00 02 41" src="https://github.com/blakeblackshear/frigate/assets/194016/3c78c3ab-5afe-4d06-944d-80bdfe0ad968">

Here is my card yaml:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.office_2
    go2rtc:
      modes:
        - mse
    live_provider: go2rtc
view:
  update_force: true
menu:
  buttons:
    mute:
      enabled: true
live:
  preload: true
media_viewer:
  auto_mute: never
```
