### DISCUSSION TITLE
[Camera Support]: 960p Camera events button cropped only in Firefox

### DISCUSSION THREAD

**Discussion by Mhisani** [blakeblackshear/frigate#10740] [Camera Support]
### Describe the problem you are having

I have two cameras on Frigate. 1 x 1080p doorbell. 1x 960p window camera.
Watching the cameras on birdseye works fine. However events/recordings when played back in Firefox have the bottom cropped off. This occurs on Firefox desktop and mobile. in Edge it appears fine.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
go2rtc:
  webrtc:
    candidates:
      - 192.696.1.23:8555
      - stun:8555
  streams:
    frontwindow_cam:
      - rtsp://youhavebeenin:suspensionfor@999.999.999.9:999/apple
    frontdoor_cam:
      - rtsp://whatyouredoingthere:isjumping@192.420.69.621:554/minorcaseofseverebraindamage_live
    
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.23
  user: comeon
  password: really?
  
cameras:
  front_door: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/didyounoticethisdoesntmatch_camera
          input_args: preset-rtsp-restream
        
          roles:
            - detect
      input_args:

       - -avoid_negative_ts
       - make_zero
       - -fflags
       - +genpts+discardcorrupt
       - -rtsp_transport
       - tcp
       - -use_wallclock_as_timestamps
       - '1'   
  front_window: # <--- this will be changed to your actual camera later
    enabled: True

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontwindow_cam
          input_args: preset-rtsp-generic
          roles:
            - detect

      input_args:
            - -analyzeduration
            - 2000000  # Adjust as needed (microseconds)
            - -fpsprobesize
            - 2000000  # Adjust as needed (bytes)
            - -fflags
            - +genpts+discardcorrupt
            - -rtsp_transport
            -  udp
            - -buffer_size
            - 256k
            - -use_wallclock_as_timestamps
            - '1'   
            
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

  output_args:
    record: preset-record-generic-audio-aac


objects:
 track:
  - person
  - bird
  - cat
  - dog
  - horse
  - sheep
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":960,"width":1280}]}}]
```

### Frigate stats

```json
{"cameras":{"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":338,"detection_enabled":1,"detection_fps":3.2,"ffmpeg_pid":3526,"pid":335,"process_fps":5.0,"skipped_fps":0.0},"front_window":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":340,"detection_enabled":1,"detection_fps":5.2,"ffmpeg_pid":347,"pid":336,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"2.9","cpu_average":"2","mem":"0.1"},"99":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"101":{"cmdline":"python3 -u -m frigate","cpu":"1.7","cpu_average":"2","mem":"1.0"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"149":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"295":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"306":{"cmdline":"frigate.recording_manager","cpu":"0.3","cpu_average":"2","mem":"0.4"},"315":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"316":{"cmdline":"frigate.detector.coral","cpu":"8.2","cpu_average":"11","mem":"0.4"},"318":{"cmdline":"frigate.output       ","cpu":"1.3","cpu_average":"1","mem":"0.4"},"324":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"325":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x960 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"326":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"335":{"cmdline":"frigate.process:front_door","cpu":"11.1","cpu_average":"16","mem":"0.5"},"336":{"cmdline":"frigate.process:front_window","cpu":"8.6","cpu_average":"10","mem":"0.4"},"338":{"cmdline":"frigate.capture:front_door","cpu":"6.4","cpu_average":"10","mem":"0.4"},"340":{"cmdline":"frigate.capture:front_window","cpu":"3.6","cpu_average":"3","mem":"0.4"},"347":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/frontwindow_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_window@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1280:h=960:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.1","cpu_average":"4","mem":"0.2"},"3526":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"13.4","cpu_average":"12","mem":"0.2"},"4375":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":8.4,"detectors":{"coral":{"detection_start":1711730796.888377,"inference_speed":10.91,"pid":316}},"gpu_usages":{"intel-qsv":{"gpu":"2.14%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":295},"recording":{"pid":306}},"service":{"last_updated":1711730797,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":57.9,"mount_type":"tmpfs","total":64.0,"used":6.1},"/media/frigate/clips":{"free":190112.4,"mount_type":"btrfs","total":935870.0,"used":725383.4},"/media/frigate/recordings":{"free":190112.4,"mount_type":"btrfs","total":935870.0,"used":725383.4},"/tmp/cache":{"free":1903.9,"mount_type":"tmpfs","total":1907.4,"used":3.4}},"temperatures":{},"uptime":1243,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Digoo M1Q 960p

### Any other information that may be helpful

![mpc-hc64_3aebFagNdk](https://github.com/blakeblackshear/frigate/assets/44286571/62aee1f6-080f-499a-a3d9-96d19386e6a1)
