### DISCUSSION TITLE
[Question]: Home Assistant automation using MQTT events; no event id sometimes?

### DISCUSSION THREAD

**Discussion by esand** [blakeblackshear/frigate#10742] [Ask A Question]
### What is your question:

Is there a the possibility that Frigate would send an MQTT event without an "after" state and/or an event id?

My Home Assistant automation starts like this:

```
alias: Security - Person at front door
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: Front_doorbell/new
    value_template: "{{ value_json.after.camera }}/{{ value_json.type }}"
    variables:
      id: >-
        {{ trigger.payload_json.after.id if trigger is defined and
        trigger.payload_json is defined else '' }}
``` 

and everything seems to work rather well, but every once in a while, I get these errors in HA logs: `Template variable warning: 'id' is undefined when rendering '{{ id }}'`. To make it more difficult to debug, due to the error, HA doesn't log an event entry so I can't check the JSON payload to see what's going on, so I'm totally in the dark.

This is the first place I try to use `{{ id }}` in my automation - the beginning of my action sequence:

```
action:
  - alias: Wait for a Person on the Doorstep
    repeat:
      sequence:
        - alias: Wait for an uptate to the Frigate event
          wait_for_trigger:
            - platform: mqtt
              topic: frigate/events
              payload: "{{ id }}"
              value_template: "{{ value_json.after.id }}"
              alias: When an update to the Frigate event is received
          timeout:
            hours: 0
            minutes: 1
            seconds: 0
            milliseconds: 0
          continue_on_timeout: false

```

If it matters, the automation is set to parallel mode. Any ideas why I'd be getting those errors saying id is undefined?
