### DISCUSSION TITLE
Zone Exit Inertia and Entrance Inertia

### DISCUSSION THREAD

**Discussion by bpmich** [blakeblackshear/frigate#10745] [General Support]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set the amount of time an object must be absent from a zone for that zone to be considered unoccupied

**Describe the solution you'd like**
I would like to have a configuration item for zones, let's say "exit_inertia", which can be set to an integer. This configuration item would determine the number of frames which must pass before an object is assumed to have left the zone.

**Describe alternatives you've considered**
I have attempted expanding the zone to accommodate the slight motion in an objects bounding box. This works better, but does not account for scenarios where an object is temporarily obstructed and the zone immediately becomes unoccupied. max_disappeared setting does not seem to have this functionality either

**Additional context**
I live in New Jersey near NYC, and parking out here is TERRIBLE. I have been using Frigate in conjunction with Home Assistant to notify me when the parking space in front of my house is clear. Occasionally, someone will walk in front of one of the cars or park too close, causing the vision model to briefly lose confidence and the object to disappear. I need a way to maintain zone occupancy even if a zone appears unoccupied for a defined amount of time. Presently I get a lot of notifications even though the actual object has not left the zone.

**Comment by NickM-27** [comment]
I can understand waiting a few frames before saying an object is not inside of the zone while it is detected. 

However, I definitely do not agree with the case where a zone would show as occupied even if the object stops being detected. That is a problem that should be solved on the automation side, not something that frigate should lie about what it is detected to fit this specific use case.

**Comment by bpmich** [comment]
@NickM-27 In case it is of use to you or others, here is my current automation in Home Assistant:

```
alias: "Frigate: Parking Space Notifications"
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
  - platform: mqtt
    topic: frigate/events
    payload: end
condition:
  - alias: Frigate Events
    condition: or
    conditions:
      - alias: Vehicle Leaves Parking Space 1
        condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.payload_json['after']['label'] == 'car' }}"
          - condition: template
            value_template: >-
              {{ 'parking_1' in trigger.payload_json['before']['current_zones']
              }}
          - condition: template
            value_template: >-
              {{ not 'parking_1' in
              trigger.payload_json['after']['current_zones'] }}
      - alias: Vehicle Leaves Parking Space 2
        condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.payload_json['after']['label'] == 'car' }}"
          - condition: template
            value_template: >-
              {{ 'parking_2' in trigger.payload_json['before']['current_zones']
              }}
          - condition: template
            value_template: >-
              {{ not 'parking_2' in
              trigger.payload_json['after']['current_zones'] }}
      - alias: Vehicle Leaves Driveway
        condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.payload_json['after']['label'] == 'car' }}"
          - condition: template
            value_template: "{{ 'driveway'in trigger.payload_json['before']['current_zones'] }}"
          - condition: template
            value_template: >-
              {{ not 'driveway' in
              trigger.payload_json['after']['current_zones'] }}
        enabled: false
action:
  - if:
      - condition: zone
        entity_id: person.person1
        zone: zone.home
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
        after: input_datetime.household_awake_time
        before: input_datetime.household_bedtime
    then:
      - service: notify.mobile_app_iphone_7
        data:
          message: A parking spot has become available
          data:
            image: >-
              https://hass.domain.tld/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
            tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
            when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
            entity_id: >-
              camera.{{trigger.payload_json["after"]["camera"] |
              replace("-","_") | lower}}
        alias: Notify person1's iPhone
  - if:
      - condition: zone
        entity_id: person.person2
        zone: zone.home
      - condition: time
        after: input_datetime.person2_s_awake_time
        before: input_datetime.household_bedtime
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
    then:
      - service: notify.mobile_app_pixel_7_pro
        data:
          message: A parking spot has become available
          data:
            image: >-
              https://hass.domain.tld/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
            tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
            when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        alias: Notify person2's Pixel 7 Pro
mode: single
```

I understand that intentionally misreporting occupancy could be considered a lie, but a new configuration item would have to be explicitly defined by the user. In my opinion, adding a tool to address the common problem of a frequently obstructed object would make Frigate more versatile, not less accurate.
