### DISCUSSION TITLE
[Config Support]:  Go2rtc Stream Using MSE Not Working

### DISCUSSION THREAD

**Discussion by raspman** [blakeblackshear/frigate#10752] [Config Support]
### Describe the problem you are having

Raspberry Pi 4b running HA with the Frigate add-on.  The camera is a Reolink WiFi Doorbell cam:

I can get the JSMPEG live feed to work, but can't get the MSE live feed to work.  When I click on "System" on the top right it shows "go2rtc 1.8.4 streams info."  As an FYI, when I click on "streams info" it brings me to a new webpage with "404: Not Found."

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: xx
  password: xx

record:
  enabled: true
  retain:
    days: 15
    mode: all

birdseye:
  mode: continuous

detect:
  enabled:  true
  width: 640
  height: 480
  fps:  5

motion:
  mask:
    - 640,0,640,452,640,321,0,307,0,0

objects:
  track:
    - person

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    Front-Door: 
      - "ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&xx=password#video=copy#audio=copy#audio=opus" 
      
cameras:
  Front-Door:
    ffmpeg:
      inputs:
        # Record HD stream
        - path: http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx
          input_args: preset-http-reolink
          roles:
            - record
        # Use low quality and low FPS stream for object detection
        - path: http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xx&password=xx
          input_args: preset-http-reolink
          roles:
            - detect
      
      output_args:
        record: preset-record-generic-audio-copy
```

### Relevant log output

```shell
2024-03-30 16:23:03.092007343  [INFO] Preparing Frigate...
2024-03-30 16:23:03.399947726  [INFO] Starting Frigate...
2024-03-30 16:23:08.725700830  [2024-03-30 09:23:08] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-30 16:23:08.726554974  [2024-03-30 09:23:08] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-03-30 16:23:08.776508101  [2024-03-30 09:23:08] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-03-30 16:23:08.797499036  [2024-03-30 09:23:08] peewee_migrate.logs            INFO    : Starting migrations
2024-03-30 16:23:08.810729675  [2024-03-30 09:23:08] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-03-30 16:23:08.823727501  [2024-03-30 09:23:08] frigate.app                    INFO    : Recording process started: 311
2024-03-30 16:23:08.831910980  [2024-03-30 09:23:08] frigate.app                    INFO    : go2rtc process pid: 87
2024-03-30 16:23:08.907360706  [2024-03-30 09:23:08] detector.ov                    INFO    : Starting detection process: 321
2024-03-30 16:23:08.924373326  [2024-03-30 09:23:08] frigate.app                    INFO    : Output process started: 323
2024-03-30 16:23:08.995123186  [2024-03-30 09:23:08] frigate.app                    INFO    : Camera processor started for Front-Door: 328
2024-03-30 16:23:09.024005916  [2024-03-30 09:23:09] frigate.app                    INFO    : Capture process started for Front-Door: 329
2024-03-30 16:23:10.230001079  [2024-03-30 09:23:10] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,300,300,3]
2024-03-30 16:23:10.232114717  [2024-03-30 09:23:10] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,1,100,7]
2024-03-30 16:23:10.232126180  [2024-03-30 09:23:10] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
what happens when trying to view mse in the frigate ui?

**Reply by raspman** [reply]
The screen is flashing showing the live view for a second (quality appears to be better than JSMPEG) and then the spinning wheel - then repeating itself. BTW, the recording part in Frigate is perfectly clear and smooth on playback...I just can't get the live feed to work properly.

**Comment by raspman** [comment]
I looked the Home Assistant Core logs; I don't know if this sheds light on the issue:

This error originated from a custom integration.

Logger: custom_components.frigate
Source: helpers/update_coordinator.py:350
integration: Frigate (documentation, issues)
First occurred: 10:03:47 AM (6 occurrences)
Last logged: 11:34:09 AM

Error fetching frigate data:

 This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:259
integration: Frigate (documentation, issues)
First occurred: 10:03:47 AM (31 occurrences)
Last logged: 11:34:42 AM

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Server disconnected
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.4', 5000)]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')

Logger: homeassistant.components.stream.stream.camera.front_door
Source: components/stream/__init__.py:431
integration: Stream (documentation, issues)
First occurred: 9:57:47 AM (14 occurrences)
Last logged: 11:39:07 AM

Error from stream worker: Timestamp discontinuity detected: last dts = 4197240, dts = -93228
Error from stream worker: Timestamp discontinuity detected: last dts = 4242150, dts = -48318
Error from stream worker: Timestamp discontinuity detected: last dts = 0, dts = 4290705705
Error from stream worker: Timestamp discontinuity detected: last dts = 4206150, dts = -84318
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://ccab4aaf-frigate:8554/Front-Door

**Reply by NickM-27** [reply]
Are you viewing the stream in Frigate or home assistant

**Comment by raspman** [comment]
HA

**Reply by raspman** [reply]
![Screenshot 2024-03-30 at 11 50 05 AM](https://github.com/blakeblackshear/frigate/assets/16636630/48bfd99e-c064-4036-9485-0c1ed9849a71)

**Reply by NickM-27** [reply]
That's Frigate UI, I'd suggest checking go2rtc logs (logs -> go2rtc in top right)

**Comment by raspman** [comment]
I'm not really sure what is going on, as I didn't see any errors before and the MSE stream wasn't playing.  I just saw a bunch of errors and had to restart everything.  JSMPEG is playing live, albeit very low quality and choppy.  MSE = nothing playing.  I am confused as to why the recordings are high quality and perfectly smooth, yet live play is either very poor quality (JSMPEG) or can't play at all (MSE.)  Is some of my config messed up?  I get that it's set up to record high-quality, but I am not sure why live can't be. 

Frigate:

2024-03-30 19:27:34.397206594 [2024-03-30 12:27:34] watchdog.Front-Door INFO : Waiting for ffmpeg to exit gracefully... 2024-03-30 19:27:34.796451639 [2024-03-30 12:27:34] frigate.video ERROR : Front-Door: Unable to read frames from ffmpeg process. 2024-03-30 19:27:34.797184411 [2024-03-30 12:27:34] frigate.video ERROR : Front-Door: ffmpeg process is not running. exiting capture thread... 2024-03-30 19:27:44.422003487 [2024-03-30 12:27:44] watchdog.Front-Door ERROR : Ffmpeg process crashed unexpectedly for Front-Door. 2024-03-30 19:27:44.422016154 [2024-03-30 12:27:44] watchdog.Front-Door ERROR : The following ffmpeg logs include the last 100 lines prior to exit. 2024-03-30 19:27:44.422020005 [2024-03-30 12:27:44] ffmpeg.Front-Door.detect ERROR : http://192.168.86.xx.xx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* End of file 2024-03-30 19:27:44.448130327 [2024-03-30 12:27:44] watchdog.Front-Door ERROR : No new recording segments were created for Front-Door in the last 120s. restarting the ffmpeg record process... 2024-03-30 19:27:44.448143105 [2024-03-30 12:27:44] watchdog.Front-Door INFO : Terminating the existing ffmpeg process... 2024-03-30 19:27:44.448146086 [2024-03-30 12:27:44] watchdog.Front-Door INFO : Waiting for ffmpeg to exit gracefully...

Go2rtc:

2024-03-30 19:24:17.431286538  [INFO] Preparing new go2rtc config...
2024-03-30 19:24:17.566101209  [INFO] Got IP address from supervisor: 192.168.86.24
2024-03-30 19:24:17.726051063  [INFO] Got WebRTC port from supervisor: 8555
2024-03-30 19:24:18.750622301  [INFO] Starting go2rtc...
2024-03-30 19:24:18.937604118  12:24:18.937 INF go2rtc version 1.8.4 linux/arm64
2024-03-30 19:24:18.939381474  12:24:18.939 INF [rtsp] listen addr=:8554
2024-03-30 19:24:18.939437084  12:24:18.939 INF [api] listen addr=:1984
2024-03-30 19:24:18.940371188  12:24:18.940 INF [webrtc] listen addr=:8555
2024-03-30 19:24:27.150982452  [INFO] Starting go2rtc healthcheck service...
2024-03-30 19:25:24.639877880  12:25:24.639 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door

Home Assistant Core:

2024-03-30 12:27:01.192 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-30 12:27:01.196 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-30 12:27:12.674 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by raspman** [comment]
Newest update:

(I've tried multiple browsers and different computers with the same results using MSE)

go2rtc:

024-03-30 19:40:00.904688985  12:40:00.904 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door
2024-03-30 19:40:11.713035048  12:40:11.712 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door
2024-03-30 19:40:32.511939526  12:40:32.511 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door
2024-03-30 19:41:03.347393396  12:41:03.347 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door
2024-03-30 19:41:44.192130178  12:41:44.191 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door
2024-03-30 19:42:35.027795371  12:42:35.027 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door
2024-03-30 19:43:35.839918941  12:43:35.839 WRN [rtsp] error="streams: exec: exit status 1" stream=Front-Door

**Reply by NickM-27** [reply]
enable trace logs

```
go2rtc:
  log:
    exec: trace
  streams:
    ...
```
