### DISCUSSION TITLE
is there a way to create a mask to block the counters for persons and cars

### DISCUSSION THREAD

**Discussion by jl-p** [blakeblackshear/frigate#10757] [Ask A Question]
### What is your question:

I have motion masks zones and object masks. but stil it counts people and cars which are not in the area i wanna look.
i only want my driveway. but every slow driving car is shown as a car. 
or people walking by.
And i made automations based on people and cars on my driveway. i thought. but i get a lot of false positives. 
But when i check the debug view i only see my car with a square. and not the cars which are blocked by the cars

![image](https://github.com/blakeblackshear/frigate/assets/10694270/1591bbeb-2824-49fc-b106-2808ca1d5fd4)

**Comment by NickM-27** [comment]
You are using motion masks. That is not what motion masks are for. You should be using zones to do this

**Comment by jl-p** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/10694270/d63e03ca-f204-4a70-af84-9ce8a836e678)
i did right or need that to be also like the motion mask. so the part which i dont want.

**Comment by kevinsaucier** [comment]
Pretty sure this is what you're looking for.  You can see all of the colored outlines depicting different zones in my config.  I mask out the sky for motion but the zones are what I'm using to 'detect' stuff.

![image](https://github.com/blakeblackshear/frigate/assets/25715814/808c6090-d8d7-4a79-a7b7-055c21acdbee)


```
# *** Driveway 180 (Facing North) ***
  driveway_180:
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-nvidia-h264 # Use GPU
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_180
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/driveway_180_sub
        roles:
        - detect
    live:
      stream_name: driveway_180
    detect:
      width: 960
      height: 272
      fps: 6
    objects:
      track:
      - person
      - car
    #     - bus
    #     - motorcycle
    #     - bicycle
    #     - boat
    #     - sports ball
    #     - bird
    #     - dog
    #     - cat
    motion:
      mask:
      - 23,144,153,101,189,62,259,32,340,34,388,0,476,0,508,21,574,0,656,22,763,56,960,152,960,0,634,0,0,0,0,272,44,272   # Neighbor yards, street, and sky
    zones:
      fritz:
        coordinates: 629,69,774,94,704,43,584,0,536,21,536,60
        objects:
        - person    
      front_walkway:
        coordinates: 960,272,858,231,778,272
        objects:
        - person
      front_yard_e:
        coordinates: 758,272,856,226,960,272,960,206,744,111,524,94,473,106,402,272
        inertia: 3
        objects:
        - person
      front_yard_w:
        coordinates: 51,218,279,106,327,102,311,120,67,241
        inertia: 3
        objects:
        - person
      street:
        coordinates: 403,86,593,86,748,107,869,118,650,81,529,70,386,72,226,92,196,104
        objects:
        - person
        - car
      lower_driveway:
        coordinates: 340,106,355,96,469,96,459,128,443,172,251,156
        objects:
        - person
        - car
      upper_driveway:
        coordinates: 76,272,396,272,434,179,241,163,58,251
        objects:
        - person
        - car
      west_neighbor:
        coordinates: 26,155,149,115,191,112,266,105,37,196
        objects:
        - person
      yerk:
        coordinates: 960,207,960,147,904,137,786,122
        objects:
        - person
```
