### DISCUSSION TITLE
[Question]: Detect stationary cars ?

### DISCUSSION THREAD

**Discussion by Cliff-R-K** [blakeblackshear/frigate#10760] [General Support] [answered]
### Describe the problem you are having

I have set up a zone around my mailbox and would like to detect when the mailman arrives. There are some moderate traffic on the road outside my house but I would like to be able to detect if a car stops in a specific zone for a minimum of x seconds. Is this possible ?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.0.5
  user: frigate
  password: frigate
birdseye:
  enabled: true
motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
detect:
  max_disappeared: 20


go2rtc:
  streams:
    ytterdorr:
    - rtsp://user:pass@192.168.0.10:554/h264Preview_01_main
    - ffmpeg:ytterdorr#audio=opus
    ytterdorr_sub:
    - rtsp://user:pass@192.168.0.10:554/h264Preview_01_sub
    uppfart:
    - rtsp://user:pass@192.168.0.10:554/h264Preview_03_main
    - ffmpeg:uppfart#audio=opus
    uppfart_sub:
    - rtsp://user:pass@192.168.0.10:554/h264Preview_03_sub
    kok:
    - rtsp://user:pass@192.168.0.10:554/h264Preview_04_main
    - ffmpeg:kok#audio=opus
    kok_sub:
    - rtsp://admin:cliff666@192.168.0.10:554/h264Preview_04_sub

cameras:
  ytterdorr:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/ytterdorr?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    detect:
      width: 2560
      height: 1920
      fps: 7
      # max_disappeared: 15
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
    objects:
      track:
      - person
      - bird
      - cat
      - dog
      filters:
        person:
          min_score: 0.7
          min_area: 4000
          max_area: 100000
          threshold: 0.7
        bird:
          max_area: 2000
          threshold: 0.6
          min_score: 0.5
        cat:
          max_area: 5000
          threshold: 0.6
          min_score: 0.5
        dog:
          max_area: 6000
          threshold: 0.7
          min_score: 0.6
  uppfart:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/uppfart?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 7
      # max_disappeared: 15
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 10
        required_zones:
        - street
        - entrance_driveway
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
    objects:
      track:
      - person
      - bird
      - cat
      - dog
      - car
      filters:
        person:
          min_score: 0.6
          min_area: 5000
          max_area: 100000
          threshold: 0.7
        bird:
          max_area: 3500
          threshold: 0.6
          min_score: 0.5
        cat:
          max_area: 5000
          threshold: 0.6
          min_score: 0.5
        dog:
          max_area: 6000
          threshold: 0.7
          min_score: 0.6
    zones:
      street:
        coordinates: 2147,357,2142,223,1400,159,799,167,215,243,0,354
      mailbox:
        coordinates: 1510,171,1894,188,2104,221,2109,385,1538,357
      driveway:
        coordinates: 803,1920,1630,1920,2296,1920,1971,1039,1809,574,1752,439,1073,430
      entrance_driveway:
        coordinates: 1643,420,1610,364,1090,362,1087,411
  kok:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/kok?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 1000
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
      # max_disappeared: 15
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 10
    motion:
      mask: 0,73,0,0,704,0,704,71
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
    objects:
      track:
      - person
      - cat
      - dog
      filters:
        person:
          min_score: 0.8
          min_area: 5000
          max_area: 100000
          threshold: 0.7
        cat:
          max_area: 5000
          threshold: 0.6
          min_score: 0.5
        dog:
          max_area: 6000
          threshold: 0.7
          min_score: 0.6
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 520A
