### DISCUSSION TITLE
[Detector Support]: Creation of Openvino models with integrated intel GPU fails on latest Linux kernel 6.8.2

### DISCUSSION THREAD

**Discussion by marco-calautti** [blakeblackshear/frigate#10785] [Detector Support] [answered]
### Describe the problem you are having

After updating my system (Arch), the kernel got updated to 6.8.2, and frigate is not able anymore to compile the openvino detector model for my integrated intel gpu, failing with the message logs shown below.
After reverting the kernel to 6.7.8, everything works normally again. Note that ffmpeg hardware acceleration is not affected, but only the openvino detectors are.

My specs: CPU intel i3 6100T with integrated GPU HD Graphics 530.

This issue in intel compute-runtime might be related: https://github.com/intel/compute-runtime/issues/710

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mosquitto

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  
go2rtc:
  streams:
    cam_salotto: # this needs to be named exactly as the camera, if you want this stream to be the live stream in frigate integration
      - rtsp://frigate:xxx@192.168.1.22:554/stream1
      - "ffmpeg:cam_salotto#audio=aac"
    cam_salotto_sub: #used only to detect movement and audio
      - rtsp://frigate:xxx@192.168.1.22:554/stream2
      - "ffmpeg:cam_salotto_sub#audio=aac"

    cam_terrazzo: # this needs to be named exactly as the camera, if you want this stream to be the live stream in frigate integration
      - rtsp://frigate:xxx@192.168.1.25:554/stream1
      - "ffmpeg:cam_terrazzo#audio=aac"
    cam_terrazzo_sub: #used only to detect movement and audio
      - rtsp://frigate:xxxB@192.168.1.25:554/stream2
      - "ffmpeg:cam_terrazzo_sub#audio=aac"

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: True
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 30
      mode: motion

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous

cameras:
  cam_salotto:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_salotto_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/cam_salotto
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif: # this enables camera features control like object movement tracking
      host: 192.168.1.22
      port: 2020
      user: frigate
      password: xxx

    audio:
      enabled: True
      min_volume: 5
    record:
      enabled: True
    detect:
      enabled: True
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75    
    live:
        stream_name: cam_salotto
  
  cam_terrazzo:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_terrazzo_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/cam_terrazzo
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif: # this enables camera features control like object movement tracking
      host: 192.168.1.25
      port: 2020
      user: frigate
      password: xxx

    audio:
      enabled: True
      min_volume: 5
    record:
      enabled: True
    detect:
      enabled: True
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
          mask:
            - 0,69,348,0,0,0
            - 597,0,588,29,532,0
    live:
        stream_name: cam_terrazzo
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    cap_add:
      - PERFMON # to see gpu stats
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: ${FRIGATE_SHM_SIZE} # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - ${FRIGATE_DRI_CARD} # this is /dev/dri/card0
      - ${FRIGATE_DRI_RENDER} # this is /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_STORAGE_DIR}/${HASS_DATA_DIR}/${FRIGATE_DATA_DIR}/${FRIGATE_CONFIG_DIR}:/config
      - ${FRIGATE_STORAGE_DEVICE}:/media/frigate
      - type: tmpfs # Optional: reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: ${FRIGATE_TMPFS_SIZE}
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    networks:
      - homeassistant-net
```

### Relevant log output

```shell
frigate  | 2024-04-02 08:57:44.141725869  Process detector:ov:
frigate  | 2024-04-02 08:57:44.143750259  Traceback (most recent call last):
frigate  | 2024-04-02 08:57:44.143842791    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-04-02 08:57:44.143846325      self.run()
frigate  | 2024-04-02 08:57:44.143848743    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-04-02 08:57:44.143850429      self._target(*self._args, **self._kwargs)
frigate  | 2024-04-02 08:57:44.143856204    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2024-04-02 08:57:44.143886819      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-04-02 08:57:44.143889641    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2024-04-02 08:57:44.143908891      self.detect_api = create_detector(detector_config)
frigate  | 2024-04-02 08:57:44.143912045    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-04-02 08:57:44.143914599      return api(detector_config)
frigate  | 2024-04-02 08:57:44.143968297    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 32, in __init__
frigate  | 2024-04-02 08:57:44.143971237      self.interpreter = self.ov_core.compile_model(
frigate  | 2024-04-02 08:57:44.143974192    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 399, in compile_model
frigate  | 2024-04-02 08:57:44.143976497      super().compile_model(model, device_name, {} if config is None else config),
frigate  | 2024-04-02 08:57:44.144153790  RuntimeError: Failed to create plugin /usr/local/lib/python3.9/dist-packages/openvino/libs/libopenvino_intel_gpu_plugin.so for device GPU
frigate  | 2024-04-02 08:57:44.144156352  Please, check your environment
frigate  | 2024-04-02 08:57:44.144158442  Check 'error_code == 0' failed at src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp:194:
frigate  | 2024-04-02 08:57:44.144160354  [GPU] No supported OCL devices found or unexpected error happened during devices query.
frigate  | 2024-04-02 08:57:44.144162338  [GPU] Please check OpenVINO documentation for GPU drivers setup guide.
frigate  | 2024-04-02 08:57:44.144163985  [GPU] clGetPlatformIDs error code: -1001
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by marco-calautti** [comment]
Any reason why this has been ignored? Especially considering that kernel 6.7 has been declared EOL, I think it is important for frigate to work as expected on 6.8 and greater.

**Reply by NickM-27** [reply]
None of the maintainers use openvino and building your own model has even more variables to it. If the built in model doesn't work then that's very concerning, building your own model is a lot more specific and any number of things could be the reason that it doesn't work

You're asking a very specific and specialized question that few people can give an informed answer to

Edit: looks like the title wasn't correct and it is the default model being used.

**Reply by NickM-27** [reply]
It looks like this issue is outside of Frigate https://github.com/intel/compute-runtime/issues/710#issuecomment-2027565979

**Reply by esand** [reply]
@NickM-27 As mentioned below by @alexeynl, it seems that updating Intel compute package might be required as well. It seems Jellyfin also updated (https://github.com/jellyfin/jellyfin-packaging/pull/15) to address the issue. Not saying a kernel fix isn't also necessary, but if Intel compute is part of Frigate, I'd just like to +1 requesting it get updated.

**Comment by alexeynl** [comment, marked as answer]
I use image Docker images from documentation ghcr.io/blakeblackshear/frigate:stable. I have migrated Docker host to Ubuntu 24.04 with 6.8 kernel and faced with the same issue.  
To get rid from this error I have installed latest compute-runtime deb packages inside Docker container according installation steps from https://github.com/intel/compute-runtime/releases.
1. Download packages to temp directory of Docker host:
```
mkdir neo
cd neo
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.16510.2/intel-igc-core_1.0.16510.2_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.16510.2/intel-igc-opencl_1.0.16510.2_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/24.13.29138.7/intel-level-zero-gpu-dbgsym_1.3.29138.7_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/24.13.29138.7/intel-level-zero-gpu_1.3.29138.7_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/24.13.29138.7/intel-opencl-icd-dbgsym_24.13.29138.7_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/24.13.29138.7/intel-opencl-icd_24.13.29138.7_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/24.13.29138.7/libigdgmm12_22.3.18_amd64.deb
```
2. Next you need repack downloaded libigdgmm12_22.3.18_amd64.deb package as [states here](https://github.com/yktoo/indicator-sound-switcher/issues/113#issuecomment-997810115) otherwise you will get the error during installation inside docker container:
```
dpkg-deb: error: archive 'libigdgmm12_22.3.18_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
```
```
sudo apt install binutils
mkdir deb_repack
cp ./libigdgmm12_22.3.18_amd64.deb ./deb_repack/libigdgmm12_22.3.18_amd64.deb
cd deb_repack
ar x libigdgmm12_22.3.18_amd64.deb
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
ar -m -c -a sdsd libigdgmm12_22.3.18_amd64_repacked.deb debian-binary control.tar.xz data.tar.xz
cp libigdgmm12_22.3.18_amd64_repacked.deb ../libigdgmm12_22.3.18_amd64.deb
cd ..
rm -rf ./deb_repack/
```
3. Run Frigate docker container as following to prevent from constant restart due the error and crash:
```
sudo docker run -d ghcr.io/blakeblackshear/frigate:stable tail -f /dev/null
```
4. Copy deb files to Frigate docker container:
```
cd ..
sudo docker cp neo frigate:/
```
5. Install deb packages inside Frigate docker container:
```
sudo docker exec -it frigate sh -c 'dpkg -i /neo/*.deb'
```
6. Restart the container and check its status:
```
sudo docker restart frigate
sudo docker ps | grep frigate
```

This is just workaround. For permanent fix Docker image mainteiner must build and push image with latest intel compute-runtime.

**Reply by esand** [reply]
Confirmed working here in an LXC on Proxmox 8.2.4. I followed these steps except I grabbed the current releases. The only hiccup I had was when installing the .deb files using your command in step 5, it threw an error during install:
`
dpkg: error processing archive /neo/intel-level-zero-gpu_1.3.29735.20_amd64.deb (--install):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1', which is also in package intel-opencl-icd 22.43.24595.41-1
`
and then said there was an error installing one of the .deb files (lost that part of the output; sorry). However, I just re-ran the command figuring it may have just been an out of sequence issue, and the second time there were no errors.

Finally, I commented out my temp fix env variables (mentioned by @marco-calautti below) and re-created my container.

GPU works, and my inference is basically the same (as it was with the env variables). I'm not certain about CPU utilization, but right now it's sitting at 0.8% (on an i3-10100 with nothing really going on for the cameras). No idea if there's any other added benefit to updating the OV packages though - I'm not that knowledgeable about this stuff yet.

**Reply by mavacpjm** [reply]
getting error during deb install any help much appreciated:

dpkg: error processing archive /neo/intel-level-zero-gpu_1.3.29138.7_amd64.deb (--install):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1', which is also in package intel-opencl-icd 22.43.24595.41-1

Here is the full verbose: when i run the deb install on container frigate.

Selecting previously unselected package intel-igc-core.
(Reading database ... 13120 files and directories currently installed.)
Preparing to unpack .../intel-igc-core_1.0.16510.2_amd64.deb ...
Unpacking intel-igc-core (1.0.16510.2) ...
Selecting previously unselected package intel-igc-opencl.
Preparing to unpack .../intel-igc-opencl_1.0.16510.2_amd64.deb ...
Unpacking intel-igc-opencl (1.0.16510.2) ...
Selecting previously unselected package intel-level-zero-gpu.
Preparing to unpack .../intel-level-zero-gpu_1.3.29138.7_amd64.deb ...
Unpacking intel-level-zero-gpu (1.3.29138.7) ...
dpkg: error processing archive /neo/intel-level-zero-gpu_1.3.29138.7_amd64.deb (--install):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1', which is also in package intel-opencl-icd 22.43.24595.41-1
Preparing to unpack .../intel-opencl-icd_24.13.29138.7_amd64.deb ...
Unpacking intel-opencl-icd (24.13.29138.7) over (22.43.24595.41-1) ...
Preparing to unpack .../libigdgmm12_22.3.18_amd64.deb ...
Unpacking libigdgmm12:amd64 (22.3.18) over (22.3.3+ds1-1) ...
Setting up intel-igc-core (1.0.16510.2) ...
Setting up intel-igc-opencl (1.0.16510.2) ...
Setting up libigdgmm12:amd64 (22.3.18) ...
Setting up intel-opencl-icd (24.13.29138.7) ...
Processing triggers for libc-bin (2.36-9+deb12u7) ...
Errors were encountered while processing:
 /neo/intel-level-zero-gpu_1.3.29138.7_amd64.deb

**Reply by mavacpjm** [reply]
Ran the script a second time like esand stated above and it installed without issue, still havent check if its resolved yet. But wanted to update that the script completed for me after a second run.

**Reply by willgryan** [reply]
> Ran the script a second time like esand stated above and it installed without issue, still havent check if its resolved yet. But wanted to update that the script completed for me after a second run.

Yes, I ran the same lines again after experiencing the error the first time, and it now works.

**Reply by mavacpjm** [reply]
Restarted Docker container, still openvino is running off cpu, so this did not resolve for me on ubuntu 22.04 LTS .

CPU pegged over 72 % when a detection occurs. Forced GPU as well to see if AUTO was the issue, still defaults back to CPU.

**Reply by mavacpjm** [reply]
It worked!!!! I gave it a few minutes after restarting frigate and things normalized - Inference went from 70ms to sub 29ms and now CPU is sitting between 8.0 and 9.0 on detector. Thanks esand for this !!! Awesome!!! 

The Frigate container will need updating to resolve this long term, this only works for the interim as esand stated!

**Reply by aeozyalcin** [reply]
@NickM-27 any updates on when openvino runtime in the docker images will be fixed?

**Reply by NickM-27** [reply]
It's already been fixed in 0.15

**Reply by aeozyalcin** [reply]
@NickM-27 FYI - just tried 0.15 Beta and the issue unfortunately still exists for me on my J5005 system with kernel 6.8.0-48. If others ask, there is still this open issue over at Intel repo:
https://github.com/intel/compute-runtime/issues/679

**Reply by NickM-27** [reply]
I tested using the arc a750 and it works, we've also had other users confirm, it's possible your issue is unrelated

**Reply by NickM-27** [reply]
I don't think that supports openvino https://www.intel.com/content/www/us/en/products/sku/128984/intel-pentium-silver-j5005-processor-4m-cache-up-to-2-80-ghz/specifications.html

**Reply by aeozyalcin** [reply]
Yeah I think officially it is not on the supported HW list, but me and others have been using it just fine on older kernels. J4105 is also on a similar boat, but you'll find plenty of people here successfully getting J4105/4125 to work with OpenVINO GPU acceleration. 

Are there confirmed cases of the latest OpenVINO runtime/Frigate working on Gemini-lake chips (J41x5 - J5xx5)? I have been searching on here, but have not found confirmations.

**Reply by NickM-27** [reply]
Not sure, but we've updated to the latest stable Intel packages so I don't think there's anything more we can do to fix it

**Reply by aeozyalcin** [reply]
Yep I appreciate the reply! I agree, in case I wasn't clear earlier, I am saying that there is still an open issue over at the [Intel repo](https://github.com/intel/compute-runtime/issues/679). So this needs to be fixed either in the kernel or with an OpenVINO runtime update by Intel in the future.

**Reply by lineumaciel** [reply]
I'm experiencing a similar issue on all versions above frigate:1234003. The error is as follows. I've checked all kernels from 6 to 6.11, and there are no changes. Hardware: i5-8259U/Iris Plus Graphics 655



``` 2024-11-03 20:29:47.782998849  Check '!m_device_map.empty()' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:379:
2024-11-03 20:29:47.783023491  [GPU] Can't get OPTIMIZATION_CAPABILITIES property as no supported devices found or an error happened during devices query.
2024-11-03 20:29:47.783026921  [GPU] Please check OpenVINO documentation for GPU drivers setup guide.
2024-11-03 20:30:01.325721  2024-11-03 20:29:47.783029309
2024-11-03 20:30:01.325747  2024-11-03 20:29:47.783031677
2024-11-03 20:30:01.325755  2024-11-03 20:29:47.783033777
2024-11-03 20:29:47.793179578  [2024-11-03 20:29:47] frigate.app                    INFO    : Output process started: 391
2024-11-03 20:29:47.817058342  [2024-11-03 20:29:47] frigate.app                    INFO    : Camera processor started for reolink: 405
2024-11-03 20:29:47.835582040  [2024-11-03 20:29:47] frigate.app                    INFO    : Capture process started for reolink: 409
2024-11-03 20:29:47.907245655  [2024-11-03 20:29:47] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2024-11-03 20:29:48.123709367  [2024-11-03 20:29:48] frigate.api.fastapi_app        INFO    : FastAPI started
2024-11-03 20:29:49.132722719  Process embeddings_manager:
2024-11-03 20:29:49.132726870  Traceback (most recent call last):
2024-11-03 20:29:49.132729086    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-11-03 20:29:49.132730801      self.run()
2024-11-03 20:29:49.132732823    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
2024-11-03 20:29:49.132734494      return run(*args, **kwargs)
2024-11-03 20:29:49.132736278    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-11-03 20:29:49.132737940      self._target(*self._args, **self._kwargs)
2024-11-03 20:29:49.132739752    File "/opt/frigate/frigate/embeddings/__init__.py", line 59, in manage_embeddings
2024-11-03 20:29:49.132741368      maintainer = EmbeddingMaintainer(
2024-11-03 20:29:49.132743101    File "/opt/frigate/frigate/embeddings/maintainer.py", line 48, in __init__
2024-11-03 20:29:49.132744806      self.embeddings = Embeddings(config.semantic_search, db)
2024-11-03 20:29:49.132746588    File "/opt/frigate/frigate/embeddings/embeddings.py", line 114, in __init__
2024-11-03 20:29:49.132748211      self.vision_embedding = GenericONNXEmbedding(
2024-11-03 20:29:49.132750049    File "/opt/frigate/frigate/embeddings/functions/onnx.py", line 90, in __init__
2024-11-03 20:29:49.132751663      self._load_model_and_tokenizer()
2024-11-03 20:29:49.132753572    File "/opt/frigate/frigate/embeddings/functions/onnx.py", line 136, in _load_model_and_tokenizer
2024-11-03 20:29:49.132755149      self.runner = ONNXModelRunner(
2024-11-03 20:29:49.132756897    File "/opt/frigate/frigate/util/model.py", line 100, in __init__
2024-11-03 20:29:49.132758531      self.interpreter = self.ov.compile_model(
2024-11-03 20:29:49.132760380    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 543, in compile_model
2024-11-03 20:29:49.132762170      super().compile_model(model, device_name, {} if config is None else config),
2024-11-03 20:29:49.132763912  RuntimeError: Exception from src/inference/src/cpp/core.cpp:121:
2024-11-03 20:29:49.132765784  Check '!m_device_map.empty()' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:379:
2024-11-03 20:29:49.132767789  [GPU] Can't get OPTIMIZATION_CAPABILITIES property as no supported devices found or an error happened during devices query.
2024-11-03 20:29:49.132769546  [GPU] Please check OpenVINO documentation for GPU drivers setup guide.
2024-11-03 20:30:01.325792  2024-11-03 20:29:49.132813243
2024-11-03 20:30:01.325800  2024-11-03 20:29:49.132815145
2024-11-03 20:30:01.325806  2024-11-03 20:29:49.132816478

**Reply by s7p** [reply]
This is the only solution that worked for me. I have frigate running on J5005 Gemini Lake. However, picking the right release was VERY IMPORTANT. Only installing [release 24.35.30872.36](https://github.com/intel/compute-runtime/releases/tag/24.35.30872.36) worked for me as it supported legacy platform, which includes J5005

**Reply by aeozyalcin** [reply]
> This is the only solution that worked for me. I have frigate running on J5005 Gemini Lake. However, picking the right release was VERY IMPORTANT. Only installing [release 24.35.30872.36](https://github.com/intel/compute-runtime/releases/tag/24.35.30872.36) worked for me as it supported legacy platform, which includes J5005 

This is great news! Which kernel version are you running now with Openvino 24.35.30872.36?

**Comment by marco-calautti** [comment]
A simpler, temporary fix, as suggested in the intel-compute-runtime repo is to set the following env variables (in the case of frigate, I guess this should be enough in the docker configuration):
NEOReadDebugKeys=1
OverrideGpuAddressSpace=48

Anyway, since the frigate image contains the intel-compute-runtime, I also believe it is frigate's responsibility to update it, to properly fix the bug.

**Reply by alexeynl** [reply]
> this should be enough in the docker configuration):
> NEOReadDebugKeys=1
> OverrideGpuAddressSpace=48

I can confirm this workaround works. I have added to my docker compose file these variables:

```
frigate:
...
    environment:
      NEOReadDebugKeys: "1"
      OverrideGpuAddressSpace: "48"
```

Checked variables exist inside container after down and up docker compose:
`sudo docker exec -it frigate sh -c 'env'`

```
HOSTNAME=6dc8233bedd6
HOME=/root
OverrideGpuAddressSpace=48
FRIGATE_RTSP_PASSWORD=password
NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
TERM=xterm
PATH=/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NEOReadDebugKeys=1
S6_LOGGING_SCRIPT=T 1 n0 s10000000 T
PWD=/opt/frigate
NVIDIA_VISIBLE_DEVICES=all
```

Frigate is running now and no errors in logs.
