### DISCUSSION TITLE
[Support]: After a day or so, recordings will play back at high speed with broken audio

### DISCUSSION THREAD

**Discussion by af7567** [blakeblackshear/frigate#10796] [General Support] [answered]
### Describe the problem you are having

My issue seemed similar to recent comments in https://github.com/blakeblackshear/frigate/issues/9818 (and also an older closed issue) but I also have video recording problems too so opened a new issue.
After working fine for 1 or 2 days, recordings will suddenly be broken and playback at high speed / skipping with broken or no audio.
This seems to happen after a very long "event" has been detected but that could just be a coincidence rather than the cause. This is what todays breaking event looked like (the car was not moving, it was just mist blowing around):
![image](https://github.com/blakeblackshear/frigate/assets/12093847/bb41b628-3b13-493b-b2f5-ff72fd5f21b0)
The first 3/4 of the recording play back fine, but then it starts to playback at high speed and trying to skip back in the video causes playback to get stuck.
All other events after this one have broken recordings until Frigate is restarted.
No errors or warnings are shown from Frigate or go2rtc
go2rtc live playback still works fine with audio in sync
Object and audio detection still seems to work correctly, but the recorded clips have no audio and will playback at high speed. The snapshots still show a good image with a bounding box in the correct place.

The problem seems to be with the ffmpeg segment recording process, but no errors or warnings from that ffmpeg process seem to make it to any log files. I noticed when trying to fix another problem that if I run the ffmpeg segment command in the container manually it would show a warning but the Frigate logs didn't show it.

I was originally just restreaming through go2rtc without any transcoding. I added #audio=aac but that didn't fix it so I also added #video=h264 but that also made no difference.

The CPU use at the times when it went wrong was only about 35%

The problem occured when this camera was the only one on the system, before adding the second camera. Although the second camera never seems to develop the problem. Possibly because the second camera is remote and sometimes needs to reconnect which causes the ffmpeg segment process to restart.

I am not sure why the warnings/errors from ffmpeg aren't showing in the logs, but feel like that would help figure out what's going wrong

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
  enabled: false
  mode: continuous
  
#logger:
#  default: debug
  #logs:
  #  ffmpeg: frigate.event

detectors:
  #cpu1:
  #  type: cpu
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
      #path: /config/openvino/yolox-tiny.xml
      
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
#model:
#  width: 416
#  height: 416
#  input_tensor: nchw
#  input_pixel_format: bgr
#  model_type: yolox
#  labelmap_path: /config/openvino/coco_80cl.txt


database:
  path: /config/frigate.db

audio:
  enabled: true
  max_not_heard: 10
  min_volume: 400
  listen:
    - bark
    - scream
    - speech
    - crying
    - cough
    - footsteps
    - yell
    - laughter

objects:
  track:
    - person
    - car
    - bus
    - bicycle
    - motorcycle
    - cat
    - dog
    #- bird
    #- sports ball

record:
  enabled: true
  events:
    required_zones:
      - above
      - below
      - road
      - rydalfull
    objects:
      - person
      - car
      - bus
      - cat
      - dog
      - bicycle
      - motorcycle
      #- bird
      #- sports ball
    retain:
      default: 10
      objects:
        car: 6
      mode: motion

snapshots:
  enabled: true
  required_zones:
    - above
    - below
    - road
    - rydalfull
  retain:
    default: 10
    
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:XXXXXX@192.168.1.14/H.264
      - "ffmpeg:doorbell#video=h264#audio=aac"
    rydalptz:
      - rtsp://opti.example.net:9554/12
      - "ffmpeg:rydalptz#audio=aac"
      
cameras:
  doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        # - path: rtsp://admin:VGAILP@192.168.1.14/H.264
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
            - record
    zones:
      above:
        coordinates: 0,524,77,540,337,542,768,515,768,0,0,0
      below:
        coordinates: 78,577,248,577,416,573,768,562,768,1024,0,1024,0,580
      road:
        coordinates: 768,524,768,555,416,578,261,581,0,575,0,540
        inertia: 32
      #above:
      #  coordinates: 0,491,70,498,768,494,768,0,0,0
      #below:
      #  coordinates: 78,577,255,582,416,573,768,538,768,1024,0,1024,0,580
      #road:
      #  coordinates: 768,489,768,526,415,567,251,573,0,575,0,505
      #  inertia: 32
    detect:
      width: 768
      height: 1024
    motion:
      threshold: 25
      lightning_threshold: 0.9
      contour_area: 10
      improve_contrast: true
      mask:
        - 416,908,471,908,469,886,420,884

  rydalptz:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rydalptz
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
            - record
    zones:
      rydalfull:
        coordinates: 0,0,800,0,800,448,0,448
    detect:
      width: 800
      height: 448
    motion:
      threshold: 30
      contour_area: 10
      lightning_threshold: 0.8
      improve_contrast: true
      mask:
        - 800,16,770,16,770,0,800,0
    objects:
      filters:
        car:
          min_area: 1100
        bus:
          min_area: 2000
```

### Relevant log output

```shell
No messages at all in the logs at the time the recording corruption started.
```

### FFprobe output from your camera

```shell
[rtsp @ 0x6cd980] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://admin:XXXXXX@192.168.1.14/H.264':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1536x2048, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

ezviz db1

**Comment by NickM-27** [comment]
This is most likely an issue where the camera starts sending bad presentation timestamps. The segment process relies on these timestamps to know when to break the segment apart so if a camera is sending incorrect timestamps (ezviz is a brand known to do this) then the recordings can have issues like this

> I am not sure why the warnings/errors from ffmpeg aren't showing in the logs, but feel like that would help figure out what's going wrong

logs are only shown from ffmpeg process when that process crashes or is stopped due to recordings not being created. In this case the recordings are being created still.

> - "ffmpeg:doorbell#video=h264#audio=aac"

this won't do anything in terms of video because the original camera already provides h264 so the new h264 would be ignored

**Reply by af7567** [reply]
> this won't do anything in terms of video because the original camera already provides h264 so the new h264 would be ignored

Ah, thanks. I guess that means that #audio=aac is also doing nothing :) I thought that the re-encoding would be fixing any bad data coming from the camera. Is there a way to force go2rtc to re-encode, there doesn't seem to be a specific option for forcing.

I wondered why some segments were 8s and some 12s.

**Reply by NickM-27** [reply]
>  Is there a way to force go2rtc to re-encode, there doesn't seem to be a specific option for forcing.

yes, just don't have a separate entry for the stream

```
go2rtc:
  streams:
    doorbell:
      - "ffmpeg:rtsp://admin:XXXXXX@192.168.1.14/H.264#video=h264#audio=aac"
```

> I wondered why some segments were 8s and some 12s.

because a segment must end on a keyframe, so it depends on your cameras iframe interval

**Reply by af7567** [reply]
> yes, just don't have a separate entry for the stream

Oops, I thought the second line was just the Frigate way of setting the stream options that would be applied to the stream in the go2rtc config. Didn't realise it was a second stream output :)

Thanks again. It's definitely re-encoding now as I see the extra ffmpeg process, so will find out in a few days if it fixes the problem.

**Comment by af7567** [comment]
Unfortunately getting go2rtc to re-encode the stream didn't fix the problem.
It went wrong again when multiple short events overlap with a long event. This is what seemed to have been happening every time.

Today I have 1 event between 16:44:13 -> 16:53:20 which is for a car it thinks is moving in my drive way.
There is also another event at 16:52:33 -> 16:53:15 for a car which keeps entering the zone on the other side of the road.
The third event at 16:53:13 -> 16:53:27 is a person walking into the driveway, and a few seconds into this event is when videos get broken.

There are no warnings or errors in the logs at or near that time and the CPU usage was only about 45%.

**Reply by NickM-27** [reply, marked as answer]
maybe try configuring frigate to connect directly to the camera for recordings instead of using the restream

**Reply by af7567** [reply]
Good idea. I see that when the recording is done from a different input it also splits the ffmpeg command into 2 rather than using the same one for segments and piping somewhere else. This would test my idea that for some reason the pipe buffer was getting full somehow :)

**Reply by NickM-27** [reply]
the pipe is only used for detect, it doesn't affect recordings in this way

**Reply by af7567** [reply]
Yes, I thought it was piping to the detection processes. I just wondered if the pipe output buffer could get full if the detection process was running slow, and this blocked ffmpeg which messed up the recording too.

**Reply by af7567** [reply]
I have tested now for over a week using "different" inputs for recording and detection so that 2 ffmpeg processes are used. I didn't restart Frigate or anything for over a week and it is still working OK. Sometimes the doorbell audio will get 10s ahead of the video but the recordings continue to record the motion OK with no "high speed" playback.  
The live view will also have the a/v sync problem, so this is a go2rtc/camera problem.  
Eventually go2rtc will close the connection to the camera, which causes Frigate to restart the ffmpeg processes because "doorbell exceeded fps limit. Exiting ffmpeg...". So it looks like a task failed successfully kind of thing where things get restarted automatically instead of staying in a broken state forever. Things work correctly for longer when using 2 ffmpeg processes rather than 1 using the go2rtc stream.
I have been using 2 inputs, but both the same stream:
```
    inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
          #  - record
        # XXX: testing with 2 of the same input so it is the same as before
        # but using 2 ffmpeg processes instead of combining segment and detect pipe
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
```
I will test now using the direct camera stream for recording with go2rtc for detect for a couple of weeks.
