### DISCUSSION TITLE
[Detector Support]: rknn include in beta

### DISCUSSION THREAD

**Discussion by TechsavvyCNC** [blakeblackshear/frigate#10798] [Detector Support]
### Describe the problem you are having

Is the rknn Detector included in the beta version of frigate?  I'm running armbian with home assistant docker.

### Version

13.2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.136
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: amcrest
  password: 7428Hootie
  stats_interval: 60

database:
  path: /media/frigate.db

go2rtc:
  streams:
    backdoor:
    - rtsp://admin:7428Hootie@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0
    backdoor_sub:
    - rtsp://admin:7428Hootie@192.168.1.147:554/cam/realmonitor?channel=1&subtype=2

cameras:
  backdoor: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      #hwaccel_args: preset-rk-h264
      inputs:
      - path: 
          rtsp://admin:7428Hootie@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp:/admin:7428Hootie@192.168.1.147:554/cam/realmonitor?channel=1&subtype=2
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
      - person

    rtmp:
      enabled: false

record:
  enabled: true
  retain:
    days: 1
    # hours:
    # minutes: 
    mode: active_objects
  events:
    retain:
      default: 10
      mode: active_objects 
      objects:
        dog: 10
        person: 10
    pre_capture: 5
    post_capture: 10

snapshots:
  enabled: true
  retain:
    default: 30

environment_vars:
  PRIVILEGED: true

#detectors:
#  rknn:
#    type: rknn
#    core_mask: 0b000
#model:
#  path: default-yolov8n
#  width: 320
#  height: 320
#  input_pixel_format: bgr
#  input_tensor: nhwc
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

Other
