### DISCUSSION TITLE
Unifi Camera no Detections

### DISCUSSION THREAD

**Discussion by strawgate** [blakeblackshear/frigate#10803] [General]
Hi,

I have a relatively simple config:

```
mqtt:
  enabled: false

database:
  path: /config/frigate.db

objects:
  track:
    - person
      car

go2rtc:
  streams:
    unifi-street-railing:
      - rtspx://192.168.0.1:7441/xxxxxxxxxxxxxxxxx

cameras:
  unifi-street-railing:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/unifi-street-railing
          roles:
            - record
            - detect
      output_args:
        record: preset-record-ubiquiti
    detect:
      enabled: true
    motion:
      threshold: 60
    record:
      enabled: True
    snapshots:
      enabled: True
```

And I see motion boxes on objects of interest
![image](https://github.com/blakeblackshear/frigate/assets/6384545/466e022c-f518-44b8-ba47-ddc1d911e421)

But I cannot for the life of me get a single event to be created for a detected object

**Comment by strawgate** [comment]
```
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[frigate] | 2024-04-02 20:35:28.330621035  [INFO] Preparing Frigate...
[frigate] | 2024-04-02 20:35:28.334535400  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
[frigate] | 2024-04-02 20:35:28.346311744  [INFO] Starting Frigate...
[frigate] | 2024-04-02 20:35:28.360301494  [INFO] Preparing new go2rtc config...
[frigate] | 2024-04-02 20:35:28.557624455  2024/04/02 20:35:28 [error] 139#139: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.239, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "192.168.0.138:5000"
[frigate] | 2024-04-02 20:35:28.557692703  192.168.0.239 - - [02/Apr/2024:20:35:28 -0500] "GET /ws HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
[frigate] | 2024-04-02 20:35:28.651015061  2024/04/02 20:35:28 [error] 140#140: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.239, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "192.168.0.138:5000"
[frigate] | 2024-04-02 20:35:28.651029353  192.168.0.239 - - [02/Apr/2024:20:35:28 -0500] "GET /ws HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
[frigate] | 2024-04-02 20:35:28.790567525  [INFO] Starting go2rtc...
[frigate] | 2024-04-02 20:35:28.898022546  20:35:28.897 INF go2rtc version 1.8.4 linux/arm64
[frigate] | 2024-04-02 20:35:28.898806819  20:35:28.898 INF [rtsp] listen addr=:8554
[frigate] | 2024-04-02 20:35:28.898837152  20:35:28.898 INF [api] listen addr=:1984
[frigate] | 2024-04-02 20:35:28.899361847  20:35:28.899 INF [webrtc] listen addr=:8555
[frigate] | 2024-04-02 20:35:29.885656716  [2024-04-02 20:35:29] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
[frigate] | 2024-04-02 20:35:31.240262998  [2024-04-02 20:35:31] peewee_migrate.logs            INFO    : Starting migrations
[frigate] | 2024-04-02 20:35:31.244740558  [2024-04-02 20:35:31] peewee_migrate.logs            INFO    : There is nothing to migrate
[frigate] | 2024-04-02 20:35:31.251647935  [2024-04-02 20:35:31] frigate.app                    INFO    : Recording process started: 457
[frigate] | 2024-04-02 20:35:31.254261789  [2024-04-02 20:35:31] frigate.app                    INFO    : go2rtc process pid: 85
[frigate] | 2024-04-02 20:35:31.275874942  [2024-04-02 20:35:31] detector.cpu                   INFO    : Starting detection process: 466
[frigate] | 2024-04-02 20:35:31.282636197  [2024-04-02 20:35:31] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[frigate] | 2024-04-02 20:35:31.284214368  [2024-04-02 20:35:31] frigate.app                    INFO    : Output process started: 468
[frigate] | 2024-04-02 20:35:31.295388727  [2024-04-02 20:35:31] frigate.app                    INFO    : Camera processor started for unifi-street-railing: 472
[frigate] | 2024-04-02 20:35:31.302520974  [2024-04-02 20:35:31] frigate.app                    INFO    : Capture process started for unifi-street-railing: 475
[frigate] | 2024-04-02 20:35:38.334784061  [INFO] Starting go2rtc healthcheck service...
```

![image](https://github.com/blakeblackshear/frigate/assets/6384545/0eabdfd7-b84b-4f53-9dd5-466c44919faa)

**Comment by NickM-27** [comment]
The default model is trained on the COCO dataset which does not look like camera images. It is known to not work well from high vantage points like this or looking down at people, so most likely it is just not detecting them well.

**Reply by strawgate** [reply]
Here's another example with bird detection enabled:
<img width="696" alt="image" src="https://github.com/blakeblackshear/frigate/assets/6384545/068ba812-e12c-4f4e-9a20-68d6d2503bef">

There is a bird every couple minutes at the feeder and I get zero detections with the below config 
![image](https://github.com/blakeblackshear/frigate/assets/6384545/3fb9fc77-ffce-4f46-bab8-059c4a2e4a7e)

```
mqtt:
  enabled: false

database:
  path: /config/frigate.db

objects:
  track:
    - person
      car
      bird

cameras:
  unifi-street-railing:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.0.1:7441/toh4FBjjjWrPkYIf
        #- path: rtsp://localhost:8554/unifi-street-railing
          roles:
            - record
            - detect
      output_args:
        record: preset-record-ubiquiti

    detect:
      enabled: true
    motion:
      threshold: 60
    objects:
      track:
        - car
          person
          bird
    record:
      enabled: True
    snapshots:
      enabled: True

```
