### DISCUSSION TITLE
[Config Support]: Detecting Cars when configured not to!

### DISCUSSION THREAD

**Discussion by slashgob** [blakeblackshear/frigate#10808] [Config Support] [answered]
### Describe the problem you are having

I have a zone configured for just detecting people, but i'm getting events created in this zone for cars. What am i doing wrong?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
cameras:
  Garden: # <--- Reolink
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://viewer:*******@10.0.0.83:554/h264Preview_01_sub   # <-- Low-res
        roles:
        - detect
      - path: rtsp://viewer:*******@10.0.0.83:554/h264Preview_01_main   # <-- Hi-res
        roles:
        - record
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        required_zones:
        - zone_0
        retain:
          default: 30
          mode: active_objects
    zones:
      zone_0:
        coordinates: 0,480,400,480,578,156,411,80,0,148
        inertia: 3
        objects:
        - person
    motion:
      mask:
      - 0,154,410,75,533,124,186,408,282,480,640,480,640,0,0,0

objects:
  track:
  - car
  - person
```

### Relevant log output

```shell
none
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB
