### DISCUSSION TITLE
[Support]: Any guides on how to use notifications without using homeassistant?

### DISCUSSION THREAD

**Discussion by Cantello** [blakeblackshear/frigate#10818] [General Support]
### Describe the problem you are having

See above, I have frigate installed as an alternative to BlueIris (which I had been using a long time but I'd like to consolidate all services on a single machine and BI doies not run in a container). Cameras and detection work well (a lot to be configured still, but the basics are already there thanks to the detailed documentation) but I struggle to enable notifications without having home assistant installed. Almost every guide I encounter uses HA as the basis.

So, should I simply use HA even though I do not use anything else from it or is there another ay to do it? I can see frigate uses MQTT to push out notifications, but how could I go from there? I cannot find anything on a relay from MQTT to e.g. pushover ( serivce I use for most of my other notifications), but any notification endpoint would be okay - ntfy, apprise, etc.

Any starting points for me?

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.12
  port: 1883
  user: user
  password: pass

objects:
  track:
    - person
    - car
    - dog
    - cat

detect:
  stationary:
    interval: 50
    threshold: 50

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  retain:
    default: 10

cameras:
  Eingang:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.60:554
          roles:
            - detect
      #hwaccel_args: preset-intel-qsv-h264

    detect:
      enabled: true

    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion

    snapshots:
      enabled: true
    
    motion:
      mask:
        - 1920,1080,1920,623,1857,624,1658,1080
        - 1920,534,1920,231,1920,0,1031,0,1094,49,1235,101,1475,208
      threshold: 30
      contour_area: 10
      lightning_threshold: 0.7
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

IMOU Bullet
