### DISCUSSION TITLE
[Support]:

### DISCUSSION THREAD

**Discussion by b24home** [blakeblackshear/frigate#10829] [General Support]
### Describe the problem you are having

Was working fine until the upgrade. Nothing has changed except that upgrade. I have restarted and rebooted.

### Version

2024.4

### Frigate config file

```yaml
# MQTT
mqtt:
  host: core-mosquitto
  user: mqtt
  password: redacted
  

# Recording Settings
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      
# Video Settings
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

# Detection Settings
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  min_initialized: 5
  max_disappeared: 25
  stationary:
    interval: 100
    threshold: 50
    max_frames:
      default: 3000
  annotation_offset: 0

objects:
  track:
  - person
  - dog
  - cat
  - car
  - bike


# ORIGINAL STREAMS
go2rtc:
  streams:
    Patio_Camera_1_main: # <- for RTSP streams
      - rtsp://redacted/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - "ffmpeg:patio_camera_1_main#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Patio_Camera_1_sub: # <- for RTSP sub-streams
      - rtsp://redacted/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:patio_camera_1_sub#audio=opus" 
    Patio_Camera_2_main: # <- for RTSP streams
      - rtsp://redacted/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - "ffmpeg:patio_camera_2_main#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Patio_Camera_2_sub: # <- for RTSP sub-streams
      - rtsp://redacted/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:patio_camera_2_sub#audio=opus" 
    Driveway_Camera_main: # <- for RTSP streams
      - rtsp://redacted/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - "ffmpeg:Driveway_Camera_main#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Driveway_Camera_sub: # <- for RTSP sub-streams
      - rtsp://redacted/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:Driveway_Camera_sub#audio=opus" 
    Front_Door_Camera:
      - rtsp://redacted_live?video&audio
      - "ffmpeg:Front_Door_Camera#audio=opus"

# CAMERAS 
cameras:
  Front_Door_Camera:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://127.0.0.1:8554/Front_Door_Camera
        roles:
        - record
        - detect
    mqtt:
      enabled: true
    record:
      enabled: true
    snapshots:
      quality: 90
    detect:
      enabled: true
  Driveway_Camera:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://127.0.0.1:8554/Driveway_Camera_main
        roles:
        - record
      - path: 
          rtsp://127.0.0.1:8554/Driveway_Camera_sub
        roles:
        - audio
        - detect
    mqtt:
      enabled: true
    record:
      enabled: true
    snapshots:
      quality: 90
    detect:
      enabled: true
  Patio_Camera_1_main:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://127.0.0.1:8554/Patio_Camera_1_main
        roles:
        - record
      - path: 
          rtsp://127.0.0.1:8554/Patio_Camera_1_sub
        roles:
        - audio
        - detect
    mqtt:
      enabled: true
    record:
      enabled: true
    snapshots:
      quality: 90
    detect:
      enabled: true
  Patio_Camera_2_main:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://127.0.0.1:8554/Patio_Camera_2_main
        roles:
        - record
      - path: 
          rtsp://127.0.0.1:8554/Patio_Camera_2_sub
        roles:
        - audio
        - detect
    mqtt:
      enabled: true
    record:
      enabled: true
    snapshots:
      quality: 90
    detect:
      enabled: true
```

### Relevant log output

```shell
Frigate logs:  https://pastebin.com/naZehzA0

---

Extra logs from Core:

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:259
integration: Frigate (documentation, issues)
First occurred: 12:00:26 PM (53 occurrences)
Last logged: 12:12:20 PM

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name has no usable address]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.3', 5000)]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:244
integration: Frigate (documentation, issues)
First occurred: 12:08:22 PM (3 occurrences)
Last logged: 12:08:52 PM

Timeout error fetching information from http://ccab4aaf-frigate:5000/api/stats:

This error originated from a custom integration.

Logger: custom_components.frigate
Source: helpers/update_coordinator.py:347
integration: Frigate (documentation, issues)
First occurred: 12:01:07 PM (11 occurrences)
Last logged: 12:08:02 PM

Error fetching frigate data:
```

### FFprobe output from your camera

```shell
Not sure how to do this.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest Bullet Cams

**Comment by NickM-27** [comment]
This config is incorrect, the model config is missing https://docs.frigate.video/configuration/object_detectors#openvino-detector

**Reply by b24home** [reply]
Is this not the model?

```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
```

Also, everything was working just fine until I upgrade HA.

Only other info I have is that all of a sudden my Frigate YAML is no longer "colored" with the XCode theme like all my other files are. No idea why.

Edit:

Oh, I see; this part, you mean?

```
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```
  
  Nonetheless, again, things WERE working just fine.
