### DISCUSSION TITLE
Setting Up Remote Storage For Frigate

### DISCUSSION THREAD

**Discussion by miketarg** [blakeblackshear/frigate#10849] [General Support]
### Describe the problem you are having

Hello, 

I am attempting to follow this guide 

[https://docs.frigate.video/guides/ha_network_storage/#if-you-dont-want-to-keep-the-current-data](url)

On sub heading Move Current data it says to either move or delete the current data located at /media/frigate

However I cant see these folders anywhere?

Where exactly are they as they are still accessible via the frigate add on and in the virtual folders in my media. 

Also the NAS isnt having anything written to it after doing the above.

### Version

Core 2024.4.0 Supervisor 2024.03.1 Operating System 12.1 Frontend 20240403.1

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: c4m343

detectors:
  cpu:
    type: cpu
    num-threads: 2

cameras:
  driveway:
    ffmpeg:
      inputs:
      - path: rtsp://admin:passwordhere@192.168.0.166/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
        - record
        - rtmp
    rtmp:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      - car
      - cat
      - bird
    motion:
      mask:
      - 640,330,353,152,348,218,288,153,288,192,185,195,191,0,640,0
    zones:
      drive_zone:
        coordinates: 167,480,467,480,278,182,186,186
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

imou
