### DISCUSSION TITLE
[Support]: "SEND TO FRIGATE+" button says "SETUP A FRIGATE+ ACCOUNT"

### DISCUSSION THREAD

**Discussion by krcm0209** [blakeblackshear/frigate#10852] [General Support] [answered]
### Describe the problem you are having

I am running Frigate on Proxmox in an LXC. I updated the LXC config to include
```
lxc.environment: PLUS_API_KEY=***
```
`***` replaced with my actual key.

When I am in the "Events" section, I can see the "SEND TO FRIGATE+" button, but if I click it, I get this popup:
![image](https://github.com/blakeblackshear/frigate/assets/17315774/75ffa31a-63e6-4ebc-a539-6020b882f833)

I assume the environment variable is there, because the button is rendering, but why does it think I need to setup an account? I already created an account in order to generate the API key.

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.0.4
  port: 1883
  user: frigate
  password: ***

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  quality: 100

go2rtc:
  streams:
    amcrest_north:
      - rtsp://admin:***@192.168.0.20:554/cam/realmonitor?channel=1&subtype=0
    amcrest_south:
      - rtsp://admin:***@192.168.0.21:554/cam/realmonitor?channel=1&subtype=0
    amcrest_east:
      - rtsp://admin:***@192.168.0.22:554/cam/realmonitor?channel=1&subtype=0
    amcrest_west:
      - rtsp://admin:***@192.168.0.23:554/cam/realmonitor?channel=1&subtype=0
    amcrest_door:
      - "rtsp://admin:***@192.168.0.24:554/cam/realmonitor?channel=1&subtype=0#backchannel=0"

cameras:
  amcrest_north:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@192.168.0.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:***@192.168.0.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
  amcrest_south:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@192.168.0.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:***@192.168.0.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
  amcrest_east:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@192.168.0.22:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:***@192.168.0.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
  amcrest_west:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@192.168.0.23:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:***@192.168.0.23:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
  amcrest_door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@192.168.0.24:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:***@192.168.0.24:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"amcrest_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":1476,"detection_enabled":1,"detection_fps":8.1,"ffmpeg_pid":1491,"pid":1443,"process_fps":1.9,"skipped_fps":3.2},"amcrest_east":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":1460,"detection_enabled":1,"detection_fps":8.1,"ffmpeg_pid":1481,"pid":1438,"process_fps":1.6,"skipped_fps":3.4},"amcrest_north":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":1446,"detection_enabled":1,"detection_fps":8.1,"ffmpeg_pid":1457,"pid":1434,"process_fps":1.7,"skipped_fps":3.3},"amcrest_south":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":1455,"detection_enabled":1,"detection_fps":8.1,"ffmpeg_pid":1475,"pid":1435,"process_fps":1.3,"skipped_fps":3.8},"amcrest_west":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":1474,"detection_enabled":1,"detection_fps":8.1,"ffmpeg_pid":1485,"pid":1439,"process_fps":1.2,"skipped_fps":3.9}},"cpu_usages":{"1":{"cmdline":"/sbin/init","cpu":"0.0","cpu_average":"0","mem":"0.1"},"51":{"cmdline":"/lib/systemd/systemd-journald","cpu":"0.0","cpu_average":"0","mem":"0.1"},"65":{"cmdline":"/lib/systemd/systemd-networkd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"/sbin/dhclient -4 -v -i -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92":{"cmdline":"/lib/systemd/systemd-resolved","cpu":"0.0","cpu_average":"0","mem":"0.1"},"95":{"cmdline":"/usr/sbin/cron -f","cpu":"0.0","cpu_average":"0","mem":"0.0"},"96":{"cmdline":"/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only","cpu":"0.0","cpu_average":"0","mem":"0.0"},"103":{"cmdline":"/usr/sbin/rsyslogd -n -iNONE","cpu":"0.0","cpu_average":"0","mem":"0.0"},"105":{"cmdline":"/lib/systemd/systemd-logind","cpu":"0.0","cpu_average":"0","mem":"0.0"},"143":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: master process /usr/local/nginx/sbin/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"155":{"cmdline":"/sbin/agetty -o -p -- \\u --noclear --keep-baud console 115200,38400,9600 linux","cpu":"0.0","cpu_average":"0","mem":"0.0"},"156":{"cmdline":"/bin/login -f     ","cpu":"0.0","cpu_average":"0","mem":"0.0"},"157":{"cmdline":"/sbin/agetty -o -p -- \\u --noclear --keep-baud tty2 115200,38400,9600 linux","cpu":"0.0","cpu_average":"0","mem":"0.0"},"162":{"cmdline":"nginx: worker process      ","cpu":"0.0","cpu_average":"0","mem":"0.0"},"163":{"cmdline":"nginx: worker process      ","cpu":"0.0","cpu_average":"0","mem":"0.0"},"175":{"cmdline":"nginx: worker process      ","cpu":"0.0","cpu_average":"0","mem":"0.1"},"197":{"cmdline":"nginx: worker process      ","cpu":"0.0","cpu_average":"0","mem":"0.0"},"198":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"457":{"cmdline":"/usr/lib/postfix/sbin/master -w","cpu":"0.0","cpu_average":"0","mem":"0.0"},"458":{"cmdline":"pickup -l -t unix -u -c","cpu":"0.0","cpu_average":"0","mem":"0.0"},"459":{"cmdline":"qmgr -l -t unix -u","cpu":"0.0","cpu_average":"0","mem":"0.0"},"464":{"cmdline":"-bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1376":{"cmdline":"python3 -u -m frigate","cpu":"2.0","cpu_average":"-1","mem":"1.1"},"1391":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.7"},"1413":{"cmdline":"frigate.recording_manager","cpu":"4.5","cpu_average":"-3","mem":"0.8"},"1421":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)","cpu":"0.2","cpu_average":"-1","mem":"0.1"},"1422":{"cmdline":"frigate.detector.coral","cpu":"31.1","cpu_average":"-15","mem":"0.8"},"1424":{"cmdline":"frigate.output       ","cpu":"0.3","cpu_average":"-1","mem":"0.8"},"1428":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1431":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"1433":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1434":{"cmdline":"frigate.process:amcrest_north","cpu":"2.5","cpu_average":"-2","mem":"0.8"},"1435":{"cmdline":"frigate.process:amcrest_south","cpu":"3.3","cpu_average":"-2","mem":"0.8"},"1436":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1438":{"cmdline":"frigate.process:amcrest_east","cpu":"2.7","cpu_average":"-2","mem":"0.8"},"1439":{"cmdline":"frigate.process:amcrest_west","cpu":"2.7","cpu_average":"-2","mem":"0.8"},"1441":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1443":{"cmdline":"frigate.process:amcrest_door","cpu":"2.8","cpu_average":"-2","mem":"0.8"},"1444":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"1446":{"cmdline":"frigate.capture:amcrest_north","cpu":"0.5","cpu_average":"-1","mem":"0.7"},"1455":{"cmdline":"frigate.capture:amcrest_south","cpu":"0.5","cpu_average":"-1","mem":"0.7"},"1457":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.20:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"-1","mem":"0.3"},"1460":{"cmdline":"frigate.capture:amcrest_east","cpu":"0.5","cpu_average":"-1","mem":"0.7"},"1474":{"cmdline":"frigate.capture:amcrest_west","cpu":"0.5","cpu_average":"-1","mem":"0.7"},"1475":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.21:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"-1","mem":"0.3"},"1476":{"cmdline":"frigate.capture:amcrest_door","cpu":"0.7","cpu_average":"-1","mem":"0.7"},"1481":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.22:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"-1","mem":"0.3"},"1485":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.23:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"-1","mem":"0.3"},"1486":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.20:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/amcrest_north@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"-1","mem":"0.2"},"1491":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.24:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=720:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.5","cpu_average":"-1","mem":"0.3"},"1494":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.23:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/amcrest_west@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"-1","mem":"0.2"},"1495":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.21:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/amcrest_south@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"-1","mem":"0.2"},"1497":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.22:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/amcrest_east@%Y%m%d%H%M%S%z.mp4","cpu":"1.2","cpu_average":"-1","mem":"0.2"},"1499":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2- -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.24:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/amcrest_door@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"-1","mem":"0.2"}},"detection_fps":40.5,"detectors":{"coral":{"detection_start":1712339162.002178,"inference_speed":24.46,"pid":1422}},"gpu_usages":{"intel-vaapi":{"gpu":"0.52%","mem":"-%"}},"processes":{"go2rtc":{"pid":143},"logger":{"pid":1391},"recording":{"pid":1413}},"service":{"last_updated":1712339162,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":7851.8,"mount_type":"tmpfs","total":7863.5,"used":11.7},"/media/frigate/clips":{"free":6655625.1,"mount_type":"zfs","total":6656000.0,"used":374.9},"/media/frigate/recordings":{"free":6655625.1,"mount_type":"zfs","total":6656000.0,"used":374.9},"/tmp/cache":{"free":11741.4,"mount_type":"ext4","total":19986.6,"used":7205.2}},"temperatures":{},"uptime":1130,"version":"0.13.2-"}}
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW-28MM
