### DISCUSSION TITLE
[Question]: recordings starting one minute after snapshots

### DISCUSSION THREAD

**Discussion by turnma** [blakeblackshear/frigate#10856] [Ask A Question]
### What is your question:

I’m seeing situations where a snapshot is taken of a car being detected, but the associated recording starts about a minute later. This means that I see things like a car arriving in the snapshot, but when I watch the associated recording it’s only capturing once the car has turned around and is driving off again. This doesn’t always happen, but I have at least a couple of occurrences just today. Any idea why?  Thanks

**Comment by NickM-27** [comment]
This is usually because the detect stream is falling behind real time so recordings that are saved don't match. Usually due to cheaper cameras or a presentation timestamp issue. You can provide your config as a first step.

**Comment by turnma** [comment]
Thanks, that's interesting.  I did spot an issue over the weekend where one of my masks had altered, which was causing a lot more detections, so I can't rule out something related to that.  I also can't rule out cheap cameras!  Just in case it's related, I also get cases where the event shows the snapshot but the recording says that "The media could not be loaded, either because the server or network failed or because the format is not supported".

```
mqtt:
  host: 192.168.1.5
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    http_drive:
    - http://192.168.1.197/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx
    - ffmpeg:http_drive
    rtsp_drive_sub:
    - rtsp://admin:xxxxx@192.168.1.197:554/h264Preview_01_sub
    - ffmpeg:rtsp_drive_sub
    rtsp_garage:
    - rtsp://admin:xxxxx@192.168.1.198:554/h264Preview_01_main
    - ffmpeg:rtsp_garage#audio=opus     # <- copy of the stream which transcodes audio to opus
    rtsp_garage_sub:
    - rtsp://admin:xxxxx@192.168.1.198:554/h264Preview_01_sub
    - ffmpeg:rtsp_garage_sub#audio=opus

cameras:
  drive:
    birdseye:
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy

      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - +genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - '5000000'
      inputs:
      - path: rtsp://127.0.0.1:8554/http_drive
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/rtsp_drive_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    record:
      events:
        required_zones:
        - off_drive
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: true
      required_zones:
      - off_drive
      retain:
        default: 21

    objects:
      track:
      - person
      - car
      - cat
      filters:
        car:
          mask:
          - 51,229,640,232,640,480,340,480,57,372
          - 559,0,562,27,640,49,640,0,561,0
    motion:
      mask:
      - 181,460,461,460,465,440,184,445
      - 0,0,95,0,0,130
    zones:
      off_drive:
        coordinates: 348,163,640,199,640,0,521,0,419,0,365,0,330,0,322,33,312,0
  garage1:
    birdseye:
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy

      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - +genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - '5000000'
      inputs:
      - path: rtsp://127.0.0.1:8554/rtsp_garage
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/rtsp_garage_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: true
    objects:
      track:
      - person
      filters:
        person:
          mask:
          - 99,298,96,136,208,105,200,266
    motion:
      mask:
      - 215,464,418,468,413,439,219,441
record:
  enabled: true
  retain:
    days: 14
    mode: motion
  events:
    retain:
      default: 28
      mode: active_objects
birdseye:
  enabled: true
  mode: continuous

objects:
  track:
  - person
  - car
```
