### DISCUSSION TITLE
[Camera Support]: Green Backyard wired POE camera not working

### DISCUSSION THREAD

**Discussion by SchoolGuy** [blakeblackshear/frigate#10867] [Camera Support] [answered]
### Describe the problem you are having

While VLC is playing the stream just fine, frigate keeps insisting that FFmpeg is crashing. ffprobe works just fine when using the arg `-rtsp_transport tcp`, without it the command never finishes.

Edit: The camera that has problems is `garten_vogel`

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: mosquitto.mqtt.svc.cluster.local
record:
  enabled: True
  retain:
    days: 90
    mode: motion
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 90
      mode: all
birdseye:
  restream: True
cameras:
  garten_dolly:
    birdseye:
      enabled: False
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://gartenhaus.home.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=viewer&password=<pass>
          roles:
            - record
            - rtmp
        - path: http://gartenhaus.home.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=viewer&password=<pass>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    record:
      events:
        objects:
          - person
          - cat
    motion:
      mask:
        - 920,0,919,47,357,46,357,0
  garten_igel:
    birdseye:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://igel-kamera.home.lan:554/user=admin&password=<pass>&channel=1&stream=0.sdp?real_stream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    detect:
      width: 1280
      height: 720
  garten_vogel:
    birdseye:
      enabled: False
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args:
        - -rtsp_transport tcp
      inputs:
        # - path: rtsp://vogel-kamera.home.lan:554/user=admin&password=<pass>&channel=1&stream=0.sdp?real_stream
        - path: rtsp://192.168.178.39:554/user=admin&password=<pass>&channel=1&stream=0.sdp?real_stream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    record:
      retain:
        mode: motion
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 231,24,233,58,9,58,11,23
  modelleisenbahn_1:
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://raspberrypi-camera.home.lan:8554/cam
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    record:
      enabled: False
    detect:
      enabled: False
  modelleisenbahn_2:
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://raspberrypi-camera-2.home.lan:8554/cam
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    record:
      enabled: False
    detect:
      enabled: False
  modelleisenbahn_3:
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://raspberrypi-camera-3.home.lan:8554/cam
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    record:
      enabled: False
    detect:
      enabled: False
  schlafzimmer_papa:
    birdseye:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://viewer:<pass>@e1.home.lan:554/h265Preview_01_main
          roles:
            - record
            - rtmp
        - path: rtsp://viewer:<pass>@e1.home.lan:554/h265Preview_01_main
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
    record:
      events:
        objects:
          - person
```

### Relevant log output

```shell
2024-04-06 17:19:00.331613383  [2024-04-06 19:18:58] frigate.video                  ERROR   : garten_vogel: Unable to read frames from ffmpeg process.
2024-04-06 17:19:00.331784724  [2024-04-06 19:18:58] frigate.video                  ERROR   : garten_vogel: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://192.168.178.39:554/user=admin&password=<pass>&channel=1&stream=0.sdp?real_stream':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 2880x1616, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{"cameras":{"garten_dolly":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":481,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":486,"pid":463,"process_fps":5.1,"skipped_fps":0.0},"garten_igel":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":485,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1500,"pid":465,"process_fps":0.0,"skipped_fps":0.0},"garten_vogel":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":490,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1506,"pid":468,"process_fps":0.0,"skipped_fps":0.0},"modelleisenbahn_1":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":496,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":1504,"pid":470,"process_fps":0.0,"skipped_fps":0.0},"modelleisenbahn_2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":503,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":1502,"pid":473,"process_fps":0.0,"skipped_fps":0.0},"modelleisenbahn_3":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":525,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":1505,"pid":476,"process_fps":0.0,"skipped_fps":0.0},"schlafzimmer_papa":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":529,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1510,"pid":478,"process_fps":0.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"0.9","cpu_average":"2","mem":"2.4"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"154":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"165":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"180":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"198":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"220":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"441":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.7"},"443":{"cmdline":"frigate.recording_manager","cpu":"1.5","cpu_average":"1","mem":"0.9"},"452":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(64)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"453":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"0.8"},"456":{"cmdline":"frigate.output       ","cpu":"0.6","cpu_average":"0","mem":"0.8"},"461":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"463":{"cmdline":"frigate.process:garten_dolly","cpu":"2.4","cpu_average":"3","mem":"0.9"},"464":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"465":{"cmdline":"frigate.process:garten_igel","cpu":"0.0","cpu_average":"0","mem":"0.7"},"467":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"468":{"cmdline":"frigate.process:garten_vogel","cpu":"0.0","cpu_average":"0","mem":"0.7"},"470":{"cmdline":"frigate.process:modelleisenbahn_1","cpu":"0.0","cpu_average":"0","mem":"0.7"},"472":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"473":{"cmdline":"frigate.process:modelleisenbahn_2","cpu":"0.0","cpu_average":"0","mem":"0.7"},"476":{"cmdline":"frigate.process:modelleisenbahn_3","cpu":"0.0","cpu_average":"0","mem":"0.7"},"477":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"478":{"cmdline":"frigate.process:schlafzimmer_papa","cpu":"0.0","cpu_average":"0","mem":"0.7"},"480":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"481":{"cmdline":"frigate.capture:garten_dolly","cpu":"2.3","cpu_average":"2","mem":"0.7"},"485":{"cmdline":"frigate.capture:garten_igel","cpu":"0.2","cpu_average":"0","mem":"0.7"},"486":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://gartenhaus.home.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"12.9","cpu_average":"14","mem":"0.3"},"487":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"490":{"cmdline":"frigate.capture:garten_vogel","cpu":"0.2","cpu_average":"0","mem":"0.7"},"496":{"cmdline":"frigate.capture:modelleisenbahn_1","cpu":"0.2","cpu_average":"0","mem":"0.7"},"498":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://gartenhaus.home.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garten_dolly@%Y%m%d%H%M%S%z.mp4","cpu":"2.0","cpu_average":"1","mem":"0.2"},"499":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"503":{"cmdline":"frigate.capture:modelleisenbahn_2","cpu":"0.2","cpu_average":"0","mem":"0.7"},"525":{"cmdline":"frigate.capture:modelleisenbahn_3","cpu":"0.2","cpu_average":"0","mem":"0.7"},"529":{"cmdline":"frigate.capture:schlafzimmer_papa","cpu":"0.4","cpu_average":"0","mem":"0.7"},"1285":{"cmdline":"/bin/bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1478":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":28.97,"pid":453}},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":441},"recording":{"pid":443}},"service":{"last_updated":1712424353,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":1020.1,"mount_type":"tmpfs","total":1024.0,"used":3.9},"/media/frigate/clips":{"free":5878999.9,"mount_type":"btrfs","total":11445597.0,"used":5565941.8},"/media/frigate/recordings":{"free":5878999.9,"mount_type":"btrfs","total":11445597.0,"used":5565941.8},"/tmp/cache":{"free":246596.2,"mount_type":"overlay","total":455947.0,"used":209343.1}},"temperatures":{},"uptime":416,"version":"0.13.1-34fb1c2"}}
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Green Backyard "Vogelhaus Kamera HD Bündel Netzwerkkabel Verbindung"

### Any other information that may be helpful

The install method is the Helm chart and not the HassOS Addon.

The camera itself has no clear marking on it what model and make they are. As I suspect that the company making them doesn't build the cameras themselves.

VLC reports this for the stream:

![VLC video stats](https://github.com/blakeblackshear/frigate/assets/15035141/92a1b10d-6059-49d7-8ba4-4c5bff8ebc3e)
