### DISCUSSION TITLE
[Support]: Object Detections not working

### DISCUSSION THREAD

**Discussion by strawgate** [blakeblackshear/frigate#10865] [General Support]
### Describe the problem you are having

I have an Amcrest camera that is sending video data into Frigate. The camera sees ~50-100 birds per hour but has zero bird detections.

Example Screenshot with Motion Boxes:
<img width="338" alt="image" src="https://github.com/blakeblackshear/frigate/assets/6384545/bbc8900b-521f-4f4d-ae21-60280aaf5aad">

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  rknn:
    type: rknn
    core_mask: 0b011

database:
  path: /config/frigate.db

model:
  input_pixel_format: bgr

audio:
  enabled: true
  listen:
  - bark
  - fire_alarm
  - scream
  - speech
  - sing
  - television
  - yell
  - crow
  - christian_music
  - christmas_music
  - angry_music
  - scary_music
  - sizzle
  - smoke_detector
  - fire_alarm

objects:
  track:
  - person
  - car
  - truck
  - bus
  - bird
  - crow
  - motorcycle
  - airplane
  - dog
  - bicycle
  - bottle
  - plate
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - potted plant
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - blender
  - book
  - vase
  - scissors
  - toothbrush
  - hair brush

record:
  enabled: true
  retain:
    days: 365


snapshots:
  enabled: true

go2rtc:

  webrtc:
    candidates:
    - 192.168.0.138:8555
    - 10.89.0.211:8555
    - stun:8555

  streams:
    amcrest-IP8M-T2599EW-bird-feeder:
    - rtsp://rtspuser:xxxxxxxxxx@192.168.10.200:554/cam/realmonitor?channel=1&subtype=0
    amcrest-IP8M-T2599EW-bird-feeder_low_quality:
    - rtsp://rtspuser:xxxxxxxxxx@192.168.10.200:554/cam/realmonitor?channel=1&subtype=1

ffmpeg:
  input_args: preset-rtsp-restream
  hwaccel_args: preset-rk-h264
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  bird-feeder:
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/amcrest-IP8M-T2599EW-bird-feeder
        roles:
        - record
        - audio
      - path: rtsp://localhost:8554/amcrest-IP8M-T2599EW-bird-feeder_low_quality
        roles:
        - detect
    detect:
      enabled: true
    objects:
      track:
      - bird
      - crow
      filters:
        bird:
          # Optional: minimum score for the object to initiate tracking
          min_score: 0.1
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.2
        crow:
          # Optional: minimum score for the object to initiate tracking
          min_score: 0.2
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.3
    motion:
      threshold: 40
      mask:
      - 444,21,448,54,231,56,240,0
    live:
      stream_name: amcrest-IP8M-T2599EW-bird-feeder
```

### Relevant log output

```shell
2024-04-06 07:57:28.085693519  [INFO] Preparing Frigate...
2024-04-06 07:57:28.123231701  [INFO] Starting Frigate...
2024-04-06 07:57:29.984829639  [2024-04-06 07:57:29] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-04-06 07:57:36.126308171  [2024-04-06 07:57:36] peewee_migrate.logs            INFO    : Starting migrations
2024-04-06 07:57:36.131237857  [2024-04-06 07:57:36] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-04-06 07:57:36.139440585  [2024-04-06 07:57:36] frigate.app                    INFO    : Recording process started: 458
2024-04-06 07:57:36.142415254  [2024-04-06 07:57:36] frigate.app                    INFO    : go2rtc process pid: 84
2024-04-06 07:57:36.165946909  [2024-04-06 07:57:36] detector.rknn                  INFO    : Starting detection process: 467
2024-04-06 07:57:36.172096329  [2024-04-06 07:57:36] frigate.app                    INFO    : Output process started: 469
2024-04-06 07:57:36.194454623  [2024-04-06 07:57:36] frigate.app                    INFO    : Camera processor started for bird-feeder: 475
2024-04-06 07:57:36.202032025  [2024-04-06 07:57:36] frigate.app                    INFO    : Capture process started for bird-feeder: 476
2024-04-06 07:57:36.218002319  [2024-04-06 07:57:36] frigate.app                    INFO    : Audio process started: 480
2024-04-06 07:57:36.407820032  I RKNN: [07:57:36.407] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
2024-04-06 07:57:36.407846573  I RKNN: [07:57:36.407] RKNN Driver Information: version: 0.9.2
2024-04-06 07:57:36.408194819  I RKNN: [07:57:36.408] RKNN Model Information: version: 6, toolkit version: 1.5.2+b642f30c(compiler version: 1.5.2 (c6b7b351a@2023-08-23T07:39:01)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
```

### FFprobe output from your camera

```shell
[
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "20/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 2592,
          "width": 1944
        },
        {
          "avg_frame_rate": "0/0",
          "codec_long_name": "AAC(AdvancedAudioCoding)"
        }
      ]
    }
  },
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "5/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 640,
          "width": 480
        },
        {
          "avg_frame_rate": "0/0",
          "codec_long_name": "AAC(AdvancedAudioCoding)"
        }
      ]
    }
  }
]
```

### Frigate stats

```json
{
  "cameras": {
    "bird-feeder": {
      "audio_dBFS": -40.9772,
      "audio_rms": 292.813,
      "camera_fps": 5.1,
      "capture_pid": 475,
      "detection_enabled": 1,
      "detection_fps": 7.7,
      "ffmpeg_pid": 484,
      "pid": 474,
      "process_fps": 5.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "10": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "11": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "19": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "20": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "21": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "22": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "23": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "35": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "40": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "75": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "76": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "77": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "84": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "5.7",
      "cpu_average": "5",
      "mem": "0.1"
    },
    "100": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "101": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "4.7",
      "cpu_average": "7",
      "mem": "0.6"
    },
    "110": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "139": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "140": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "141": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "142": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "143": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "144": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "153": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "165": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "180": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "448": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "458": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "465": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(40)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "467": {
      "cmdline": "frigate.detector.rknn",
      "cpu": "8.4",
      "cpu_average": "9",
      "mem": "0.6"
    },
    "469": {
      "cmdline": "frigate.output       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "473": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 480x640 -i pipe: -f mpegts -s 540x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "474": {
      "cmdline": "frigate.process:bird-feeder",
      "cpu": "15.2",
      "cpu_average": "9",
      "mem": "0.4"
    },
    "475": {
      "cmdline": "frigate.capture:bird-feeder",
      "cpu": "1.6",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "476": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "480": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "484": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_rkmpp_decoder -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/amcrest-IP8M-T2599EW-bird-feeder_low_quality -r 5 -vf fps=5,scale=480:640 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "16.3",
      "cpu_average": "13",
      "mem": "0.1"
    },
    "490": {
      "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/amcrest-IP8M-T2599EW-bird-feeder -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "1.6",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "496": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_rkmpp_decoder -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/amcrest-IP8M-T2599EW-bird-feeder -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/bird-feeder@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.1",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "985": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 7.7,
  "detectors": {
    "rknn": {
      "detection_start": 0,
      "inference_speed": 21.71,
      "pid": 467
    }
  },
  "processes": {
    "audioDetector": {
      "pid": 480
    },
    "go2rtc": {
      "pid": 84
    },
    "logger": {
      "pid": 448
    },
    "recording": {
      "pid": 458
    }
  },
  "service": {
    "last_updated": 1712408873,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 181.7,
        "mount_type": "tmpfs",
        "total": 183.1,
        "used": 1.4
      },
      "/media/frigate/clips": {
        "free": 5750336,
        "mount_type": "nfs",
        "total": 7314800.8,
        "used": 1564464.8
      },
      "/media/frigate/recordings": {
        "free": 5750336,
        "mount_type": "nfs",
        "total": 7314800.8,
        "used": 1564464.8
      },
      "/tmp/cache": {
        "free": 942.1,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 11.5
      }
    },
    "temperatures": {},
    "uptime": 132,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Amcrest IP8M T2599EW
