### DISCUSSION TITLE
[HW Accel Support]: error: XDG_RUNTIME_DIR is invalid or not set in the environment.

### DISCUSSION THREAD

**Discussion by KickingAss2024** [blakeblackshear/frigate#10874] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Try to setup HW accel on friget and can work out why I can get it to work any help on this will be helpful.

```
VAINFO OUTPUT
Return Code: 3

Process Error:

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: mosquitto.ix-mosquitto.svc.cluster.local
  user: ###
  password: ####
detectors:
  coral1:
    type: edgetpu
    device: pci:0
record:
  enabled: true
  retain:
    days: 1
  events:
    objects:
      - person
    retain:
      default: 1
snapshots:
  enabled: true
  retain:
    default: 1
go2rtc:
  streams:
    frontyard: 
      - rtsp://admin:#####@192.168.0.163:554/Preview_01_main
      - "ffmpeg:frontyard#video=h264"
    frontyard_sub: rtsp://admin:#######@192.168.0.163:554/Preview_01_sub
    kennel: 
      - rtsp://admin:######@192.168.0.73:554/Preview_01_main
      - "ffmpeg:kennel#video=h264"
    kennel_sub: rtsp://admin:#####@192.168.0.73:554/Preview_01_sub
    backyard: 
      - rtsp://admin:####$$##$@192.168.0.13:554/Preview_01_main
      - "ffmpeg:backyard#video=h264"
    backyard_sub: rtsp://admin:######@192.168.0.13:554/Preview_01_sub
cameras:
  frontyard:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record          
        - path: rtsp://127.0.0.1:8554/frontyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect  
    detect:
      enabled: True
      width: 1536
      height: 576
      fps: 4
    motion:
      mask:
        - 0,305,232,230,376,185,482,120,528,89,613,54,722,44,845,54,994,68,1130,95,1295,169,1376,151,1466,63,1488,0,0,0
  kennel:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/kennel
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kennel_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 1536
      height: 576
      fps: 4
  backyard:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 1536
      height: 576
      fps: 4
```
```


### docker-compose file or Docker CLI command

```yaml
I use trueNAS witch do not have a docker file
```

### Relevant log output

```shell
2024-04-07 04:35:03.326384734  [2024-04-07 14:35:03] frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
2024-04-07 04:35:03.326470372  [2024-04-07 14:35:03] frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
2024-04-07 04:35:04.202144961  [2024-04-07 14:35:04] watchdog.backyard              ERROR   : Ffmpeg process crashed unexpectedly for backyard.
2024-04-07 04:35:04.202334582  [2024-04-07 14:35:04] watchdog.backyard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-04-07 04:35:04.202537029  [2024-04-07 14:35:04] ffmpeg.backyard.detect         ERROR   : rtsp://127.0.0.1:8554/backyard_sub: Connection timed out
2024-04-07 04:35:04.202698174  [2024-04-07 14:35:04] ffmpeg.backyard.detect         ERROR   :     Last message repeated 1 times
2024-04-07 04:35:04.213838945  [2024-04-07 14:35:04] ffmpeg.backyard.record         ERROR   : [segment @ 0x557556efff00] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```
```


### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1728,"width":4608},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"4/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":1536},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```
```
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1728,"width":4608},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"4/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":1536},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```
```
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1728,"width":4608},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":0,"width":0},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```
```


### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Duo 2

### Any other information that may be helpful

 I useing TrueNas Scale
