### DISCUSSION TITLE
[Config Support]: EXIF data not in clips or snapshots

### DISCUSSION THREAD

**Discussion by aburow** [blakeblackshear/frigate#10876] [Config Support]
### Describe the problem you are having

I am not able to figure out how to put basic exif data into snapshots and recordings in order to preserve simple information, such as "time/date acquired" field. It would be nice to be able to fill out as much data as possible but I can't find a way to do this.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
logger:
  default: warning
  logs:
    frigate.mqtt: error

ui:
  timezone: Australia/Brisbane
  strftime_fmt: "%H:%M %d/%m/%Y"
  live_mode: mse

mqtt:
  enabled: true
  user: ""
  password: ""
  host: 192.168.100.10
  stats_interval: 60

detectors:
 coral:
   type: edgetpu
   device: usb

detect:
  stationary:
    interval: 10
    threshold: 50

audio:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
  global_args:
    -hide_banner
    -loglevel info

birdseye:
  enabled: True
  restream: false
  mode: objects

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 10
    post_capture: 30
    retain:
      default: 5
      mode: active_objects

snapshots:
  enabled:  True
  timestamp: True
  bounding_box: True
  retain:
    default: 5

go2rtc:
  streams:
    floorright:
      # Dahua
      - "rtsp://100.66.67.101:554#backchannel=0"
    garage:
      # XM510
      - "rtsp://100.66.67.103/channel=1_stream=0.sdp"
    bicam:
      # Hik
      - "rtsp://100.66.67.105:554/stream0#backchannel=0"
    ballcam:
      # Hik
      - "rtsp://100.66.67.106:554/stream0#backchannel=0"

cameras:
  floorright:
    ui:
      order: 1
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/floorright"
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: True
      fps: 10
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - bear
      filters:
        person:
          threshold: 0.8
        bird:
          min_score: 0.7
          min_area: 1000
        cat:
          threshold: 0.4
        dog:
          threshold: 0.4

  garage:
    ui:
      order: 2
    enabled: true
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/garage"
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
            - detect
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 500
      listen:
        - bark
      filters:
        bark:
          threshold: 0.5
    detect:
      enabled: True
      fps: 10
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - elephant
        - bear
      filters:
        person:
          threshold: 0.8
        cat:
          threshold: 0.4
        dog:
          threshold: 0.4

  bicam: #Name for your comment
    ui:
      order: 3
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/bicam"
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: True
      fps: 20
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - elephant
        - bear
      filters:
        person:
          threshold: 0.8
        bird:
          min_score: 0.7
          min_area: 4000
        cat:
          threshold: 0.4
        dog:
          threshold: 0.4

  ballcam: #Name for your comment
    ui:
      order: 4
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/ballcam"
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: True
      fps: 15
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - elephant
        - bear
      filters:
        person:
          threshold: 0.8
        cat:
          threshold: 0.4
        dog:
          threshold: 0.4

#EOF
```

### Relevant log output

```shell
n/a
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

USB
