### DISCUSSION TITLE
[Config Support]: Birdseye layout options not working/not allowed in config editor

### DISCUSSION THREAD

**Discussion by futuredj** [blakeblackshear/frigate#10878] [Config Support]
### Describe the problem you are having

Im trying to use the new layout options added in v13 but the config editor underlines layout in yellow if I add it to the birdseye section of the config. I tried adding it to each camera config which the config editor accepts but doesnt change anything to birdseye.

![frigate](https://github.com/blakeblackshear/frigate/assets/9522017/b922e91c-3dfc-44d9-8429-3076bee53d3f)

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
birdseye:
  enabled: True
  restream: True
  width: 1080
  height: 1920
  mode: objects
  layout:                     ## this wrong according to editor
    max_cameras: 1

cameras:
  Lilly:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/lilly
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    birdseye:
      mode: continuous
      order: 2
      layout:                          ## this is correct
        max_cameras: 1
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: lilly
```

### Relevant log output

```shell
n
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other
