### DISCUSSION TITLE
[Support]: Scream and/or Yell detection, can't get it to work.  Speech, Bark and Fire Alarm work fine

### DISCUSSION THREAD

**Discussion by tfer6** [blakeblackshear/frigate#10870] [General Support]
### Describe the problem you are having

As the subject says, I'm trying to get scream and/or yell detection to work.  I've tried manipulating the "min_volume" and the "threshold" variables to no avail.  Anything else I'm missing or can try?   I just have audio detection enabled on 1 camera "frigate_aa"  It's a unifi G3 instant.  I can seem the rms and dbfs spike on MQTT when either I or my daughter has been helping me test it, but it seems to trigger a detection.  Speech works perfectly, as does barking and fire alarm detection.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.200


ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti 


record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    objects:
    - person
    - dog
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: true

cameras:
  frigate_front:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.1:7447/j1LivrUhAek8MdKL
        roles:
        - detect
        - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
      - 1920,432,1920,0,0,0,0,622,252,584,624,306
    zones:
      frigate_front_grass:
        coordinates: 423,1080,1103,1080,1851,1080,1789,780,1073,705,793,670
      frigate_front_walkway:
        coordinates: 193,824,423,582,780,653,522,952
      frigate_front_steps:
        coordinates: 466,953,0,1013,0,853,189,818
      frigate_front_close:
        coordinates: 42,1080,1103,1080,1800,1080,1804,980,584,903,510,986
        objects:
        - person
        filters:
          person:
            threshold: 0.8
    objects:
      track:
      - person
      - dog




  frigate_backyard:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.1:7447/FSeoVvav6yrlexmF
        roles:
        - detect
        - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
      - 839,0,845,182,603,282,567,0
    objects:
      track:
      - person
      - dog
      filters:
        person:
          min_score: 0.7
          min_area: 3000
          mask:
          - 1743,1080,1733,918,1628,898,1534,1080




  frigate_doorbell:
    record:
      events:
        required_zones:
          - frigate_front_close
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.1:7447/hJKTAVobkbp6jX0i
        roles:
        - detect
        - record
    detect:
      width: 1600
      height: 1200
      fps: 5
    motion:
      mask:
      - 0,1200,0,349,0,0,140,0,289,0,1600,0,1600,1200,895,1200,909,922,793,900,754,962,700,970,550,985,271,1200
    objects:
      track:
      - person
      - dog
      filters:
        person:
          min_score: 0.7
          threshold: 0.72
    zones:
      frigate_front_close:
        coordinates: 
          0,1200,0,349,0,0,140,0,289,0,1600,0,1600,1200,895,1200,909,922,793,900,754,962,700,970,550,985,271,1200
        objects:
        - person



  frigate_aa:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.1:7447/kaPDTSs8I4otYW60
        roles:
        - record
        - detect
        - audio
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - yell
        - speech
      max_not_heard: 15
      min_volume: 50
      filters:
        scream:
          threshold: 0.5
        yell:
          threshold: 0.5
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          default: 1500
    motion:
      mask:
      - 1920,1080,1357,1080,1429,853,1479,628,1513,307,1516,0,1920,0
    zones:
      frigate_aa_door:
        coordinates: 391,35,594,570,330,716,34,84
    objects:
      track:
      - person
      - dog
      filters:
        person:
          min_score: 0.7
          threshold: 0.80



  frigate_den:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.202:8554/basement
        roles:
        - record
        - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
      - 1920,0,1920,1080,1376,1080,1428,588,1027,538,1041,0
    objects:
      track:
      - person
      - dog

  frigate_garage:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.202:8554/garage
        roles:
        - record
        - detect 
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
      - 1920,1080,1920,678,1920,588,1920,207,1814,223,1735,524,1514,492,1363,714,934,1080
    objects:
      track:
      - person
      filters:
        person:
          min_score: 0.75
          threshold: 0.77
          min_area: 28000



detectors:
  coral:
    type: edgetpu
    device: usb


objects:
  track:
  - person
  - dog
  - car
```

### Relevant log output

```shell
n/a, I think?
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1+esm3 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://192.168.1.1:7447/kaPDTSs8I4otYW60':
  Metadata:
    title           : E063DA01925B_0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
  Stream #0:2: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 29.92 tbr, 90k tbn, 60 tbc
```

### Frigate stats

```json
{"cameras": {"frigate_front": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 2.4, "detection_enabled": 1, "pid": 348, "capture_pid": 359, "ffmpeg_pid": 364, "audio_rms": 0.0, "audio_dBFS": 0.0}, "frigate_backyard": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.9, "detection_enabled": 1, "pid": 349, "capture_pid": 363, "ffmpeg_pid": 370, "audio_rms": 0.0, "audio_dBFS": 0.0}, "frigate_doorbell": {"camera_fps": 5.0, "process_fps": 5.0, "skipped_fps": 0.0, "detection_fps": 0.0, "detection_enabled": 1, "pid": 351, "capture_pid": 367, "ffmpeg_pid": 373, "audio_rms": 0.0, "audio_dBFS": 0.0}, "frigate_aa": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.9, "detection_enabled": 1, "pid": 353, "capture_pid": 372, "ffmpeg_pid": 379, "audio_rms": 2.3485, "audio_dBFS": -82.8932}, "frigate_den": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "detection_enabled": 1, "pid": 355, "capture_pid": 377, "ffmpeg_pid": 383, "audio_rms": 0.0, "audio_dBFS": 0.0}, "frigate_garage": {"camera_fps": 5.0, "process_fps": 5.0, "skipped_fps": 0.0, "detection_fps": 0.0, "detection_enabled": 1, "pid": 357, "capture_pid": 382, "ffmpeg_pid": 392, "audio_rms": 0.0, "audio_dBFS": 0.0}}, "detectors": {"coral": {"inference_speed": 9.41, "detection_start": 0.0, "pid": 317}}, "detection_fps": 4.2, "gpu_usages": {"intel-vaapi": {"gpu": "4.64%", "mem": "-%"}}, "cpu_usages": {"1": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"}, "15": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise s6-linux-init-shutdownd"}, "16": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"}, "24": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise s6rc-oneshot-runner"}, "25": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise go2rtc-healthcheck"}, "26": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise go2rtc-log"}, "27": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise go2rtc"}, "28": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise frigate-log"}, "29": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise nginx"}, "30": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise nginx-log"}, "31": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise frigate"}, "32": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-supervise s6rc-fdholder"}, "41": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"}, "42": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"}, "79": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"}, "80": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"}, "82": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"}, "89": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"}, "97": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "bash ./run.user go2rtc-healthcheck"}, "111": {"cpu": "3.5", "cpu_average": "3", "mem": "3.9", "cmdline": "python3 -u -m frigate"}, "119": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "nginx: master process nginx"}, "148": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "nginx: worker process"}, "149": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "nginx: worker process"}, "150": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "nginx: worker process"}, "151": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "nginx: worker process"}, "161": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "nginx: cache manager process"}, "305": {"cpu": "0.0", "cpu_average": "0", "mem": "0.7", "cmdline": "frigate.logger       "}, "307": {"cpu": "3.2", "cpu_average": "3", "mem": "1.1", "cmdline": "frigate.recording_manager"}, "316": {"cpu": "0.5", "cpu_average": "0", "mem": "0.1", "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)"}, "317": {"cpu": "2.7", "cpu_average": "3", "mem": "0.9", "cmdline": "frigate.detector.coral"}, "319": {"cpu": "2.5", "cpu_average": "2", "mem": "0.8", "cmdline": "frigate.output       "}, "325": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "326": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "327": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1600x1200 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "328": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "329": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "330": {"cpu": "0.0", "cpu_average": "0", "mem": "0.1", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "331": {"cpu": "0.0", "cpu_average": "0", "mem": "0.3", "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"}, "348": {"cpu": "3.4", "cpu_average": "2", "mem": "1.2", "cmdline": "frigate.process:frigate_front"}, "349": {"cpu": "2.0", "cpu_average": "2", "mem": "1.0", "cmdline": "frigate.process:frigate_backyard"}, "351": {"cpu": "1.4", "cpu_average": "1", "mem": "1.0", "cmdline": "frigate.process:frigate_doorbell"}, "353": {"cpu": "1.7", "cpu_average": "2", "mem": "1.2", "cmdline": "frigate.process:frigate_aa"}, "355": {"cpu": "1.5", "cpu_average": "3", "mem": "1.1", "cmdline": "frigate.process:frigate_den"}, "357": {"cpu": "2.2", "cpu_average": "1", "mem": "0.9", "cmdline": "frigate.process:frigate_garage"}, "359": {"cpu": "3.3", "cpu_average": "3", "mem": "0.9", "cmdline": "frigate.capture:frigate_front"}, "363": {"cpu": "3.4", "cpu_average": "3", "mem": "0.9", "cmdline": "frigate.capture:frigate_backyard"}, "364": {"cpu": "18.7", "cpu_average": "17", "mem": "0.5", "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.1:7447/j1LivrUhAek8MdKL -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/frigate_front@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"}, "367": {"cpu": "2.7", "cpu_average": "2", "mem": "0.9", "cmdline": "frigate.capture:frigate_doorbell"}, "370": {"cpu": "18.3", "cpu_average": "17", "mem": "0.5", "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.1:7447/FSeoVvav6yrlexmF -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/frigate_backyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"}, "372": {"cpu": "2.4", "cpu_average": "2", "mem": "0.9", "cmdline": "frigate.capture:frigate_aa"}, "373": {"cpu": "17.3", "cpu_average": "16", "mem": "0.5", "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.1:7447/hJKTAVobkbp6jX0i -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/frigate_doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1600:h=1200:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"}, "377": {"cpu": "3.0", "cpu_average": "2", "mem": "0.9", "cmdline": "frigate.capture:frigate_den"}, "379": {"cpu": "15.3", "cpu_average": "14", "mem": "0.4", "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.1:7447/kaPDTSs8I4otYW60 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/frigate_aa@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"}, "382": {"cpu": "3.6", "cpu_average": "2", "mem": "0.9", "cmdline": "frigate.capture:frigate_garage"}, "383": {"cpu": "3.6", "cpu_average": "3", "mem": "0.4", "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.202:8554/basement -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/frigate_den@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"}, "385": {"cpu": "0.2", "cpu_average": "0", "mem": "0.9", "cmdline": "frigate.audio_manager"}, "392": {"cpu": "4.4", "cpu_average": "3", "mem": "0.4", "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.202:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/frigate_garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"}, "393": {"cpu": "1.6", "cpu_average": "1", "mem": "0.1", "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.1:7447/kaPDTSs8I4otYW60 -f s16le -ar 16000 -ac 1 -y pipe:"}, "14788": {"cpu": "0.0", "cpu_average": "0", "mem": "0.0", "cmdline": "sleep 30s"}}, "service": {"uptime": 4128, "version": "0.13.2-6476f8a", "latest_version": "0.13.2", "storage": {"/media/frigate/recordings": {"total": 119462.3, "used": 86371.0, "free": 28209.0, "mount_type": "ext4"}, "/media/frigate/clips": {"total": 119462.3, "used": 86371.0, "free": 28209.0, "mount_type": "ext4"}, "/tmp/cache": {"total": 7945.3, "used": 10.3, "free": 7934.9, "mount_type": "tmpfs"}, "/dev/shm": {"total": 7945.3, "used": 24.2, "free": 7921.0, "mount_type": "tmpfs"}}, "temperatures": {}, "last_updated": 1712429989}, "processes": {"logger": {"pid": 305}, "recording": {"pid": 307}, "go2rtc": {"pid": 89}, "audioDetector": {"pid": 385}}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unfi G3 Instant
