### DISCUSSION TITLE
ffmpeg errors

### DISCUSSION THREAD

**Discussion by Baethovan** [blakeblackshear/frigate#10883] [Config Support]
### Describe the problem you are having

So I get the follow 3 errors ever 10 seconds non stop

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.0.5
  port: 1883
  user: user
  password: pass

###################
go2rtc:
  streams:
    computer_camera:
      - rtsp://user:pass:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam#audio=opus"
    computer_camera_sub:
      - rtsp://user:pass:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    front_door_camera:
      - rtsp://rtsp://user:pass:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    front_door_camera_sub:
      - rtsp://user:pass:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"

##################
cameras:
  computer_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/computer_camera
          input_args: preset-rtsp-restream
          roles:
             - record
        - path: rtsp://127.0.0.1:8554/computer_camera_sub
          input_args: preset_rtsp_restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.7 # min score for object to initiate tracking (default: 0.5
          threshold: 0.8 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
    detect:
      enabled: True
      width: 640
      height: 480
    snapshots:
      enabled: True
      retain:
        default: 3
      timestamp: True
      bounding_box: True
      crop: True
      height: 500
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects

####################
  front_door_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_camera
          input_args: preset-rtsp-restream
          roles:
             - detect
        - path: rtsp://127.0.0.1:8554/front_door_camera_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.7 # min score for object to initiate tracking (default: 0.5)
          threshold: 0.8 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
    detect:
      enabled: True
      width: 640
      height: 480
    snapshots:
      enabled: True
      retain:
        default: 3
      timestamp: True
      bounding_box: True
      crop: True
      height: 500
    record:
      enabled: True
      retain:
        days: 2
	mode: active_objects
####################
detectors:
    cpu1:
      type: cpu
```

### Relevant log output

```shell
2024-04-08 08:50:24.951686541  [2024-04-08 08:50:24] watchdog.computer_camera       ERROR   : No new recording segments were created for computer_camera in the last 120s. restarting the ffmpeg record process...
2024-04-08 08:50:24.951763039  [2024-04-08 08:50:24] watchdog.computer_camera       INFO    : Terminating the existing ffmpeg process...
2024-04-08 08:50:24.951784916  [2024-04-08 08:50:24] watchdog.computer_camera       INFO    : Waiting for ffmpeg to exit gracefully...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
I'd suggest using preset-vaapi instead of qsv

**Reply by Baethovan** [reply]
So `preset-vaapi-h264`?

**Reply by NickM-27** [reply]
no, just `preset-vaapi`

**Reply by Baethovan** [reply]
Okay, I'll try that. Why would you recommend that?

**Reply by NickM-27** [reply]
because this is a pretty common problem with qsv, and in general I recommend vaapi over qsv

**Reply by Baethovan** [reply]
So I just made the change, still getting the same errors

**Reply by NickM-27** [reply]
I see another issue in the config. Your go2rtc has `rtsp_cam` but it should match the name of the stream

**Reply by Baethovan** [reply]
So I got rid of that entirely as it was just for audio (which I found out that camera does not support), still same errors.

**Reply by NickM-27** [reply]
Would be good to see a fresh copy of looks after frigate has been running for a bit

**Reply by Baethovan** [reply]
So I restarted Frigate and now I don't get a camera feed. This is in the docker compose logs.
```
frigate  | 2024-03-17 16:59:01.063102285  ***    Your config file is not valid!                     ***
frigate  | 2024-03-17 16:59:01.063103647  ***    Please check the docs at                           ***
frigate  | 2024-03-17 16:59:01.063104506  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2024-03-17 16:59:01.063122994  *************************************************************
frigate  | 2024-03-17 16:59:01.063123814  *************************************************************
frigate  | 2024-03-17 16:59:01.063124911  ***    Config Validation Errors                           ***
frigate  | 2024-03-17 16:59:01.063125722  *************************************************************
frigate  | 2024-03-17 16:59:01.063126478  Config input retain is defined multiple times for the same field, this is not allowed.
frigate  | 2024-03-17 16:59:01.063832433  Traceback (most recent call last):
frigate  | 2024-03-17 16:59:01.063834895    File "/opt/frigate/frigate/app.py", line 645, in start
frigate  | 2024-03-17 16:59:01.063835826      self.init_config()
frigate  | 2024-03-17 16:59:01.063836757    File "/opt/frigate/frigate/app.py", line 112, in init_config
frigate  | 2024-03-17 16:59:01.063837659      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2024-03-17 16:59:01.063838573    File "/opt/frigate/frigate/config.py", line 1329, in parse_file
frigate  | 2024-03-17 16:59:01.063839438      config = load_config_with_no_duplicates(raw_config)
frigate  | 2024-03-17 16:59:01.063840432    File "/opt/frigate/frigate/util/builtin.py", line 114, in load_config_with_no_duplicates
frigate  | 2024-03-17 16:59:01.063841299      return yaml.load(raw_config, PreserveDuplicatesLoader)
frigate  | 2024-03-17 16:59:01.063842190    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate  | 2024-03-17 16:59:01.063843007      return loader.get_single_data()
frigate  | 2024-03-17 16:59:01.063844019    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
frigate  | 2024-03-17 16:59:01.063845171      return self.construct_document(node)
frigate  | 2024-03-17 16:59:01.063846155    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 55, in construct_document
frigate  | 2024-03-17 16:59:01.063868755      data = self.construct_object(node)
frigate  | 2024-03-17 16:59:01.063869952    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
frigate  | 2024-03-17 16:59:01.063870940      data = constructor(self, node)
frigate  | 2024-03-17 16:59:01.063871824    File "/opt/frigate/frigate/util/builtin.py", line 99, in map_constructor
frigate  | 2024-03-17 16:59:01.063872911      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
frigate  | 2024-03-17 16:59:01.063874233    File "/opt/frigate/frigate/util/builtin.py", line 99, in <listcomp>
frigate  | 2024-03-17 16:59:01.063875258      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
frigate  | 2024-03-17 16:59:01.063876275    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
```

**Reply by NickM-27** [reply]
you have duplicated the same config entry

**Reply by Baethovan** [reply]
I see that line, just not sure what entry it's referring to.

**Reply by NickM-27** [reply]
Most likely duplicated `retain` under record

**Reply by Baethovan** [reply]
Sorry, but I don't see a duplicate retain.

**Reply by NickM-27** [reply]
You should paste your config

**Reply by Baethovan** [reply]
```
mqtt:
  enabled: True
  host: 192.168.0.5
  port: 1883
  user: user  
  password: ps

###################
go2rtc:
  streams:
     computer_camera:
      - rtsp://user:pass@192.168.0.229:554/cam/realmonitor?channel=1&subtype=0
    computer_camera_sub:
      - rtsp://user:pass!@192.168.0.229:554/cam/realmonitor?channel=1&subtype=1
    front_door_camera:
      - rtsp://user:pass@192.168.0.205:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    front_door_camera_sub:
      - rtsp://user:pass@192.168.0.205:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"

##################
cameras:
  computer_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/computer_camera
          input_args: preset-rtsp-restream
          roles:
             - record
        - path: rtsp://127.0.0.1:8554/computer_camera_sub
          input_args: preset_rtsp_restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.7 # min score for object to initiate tracking (default: 0.5)
          threshold: 0.8 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
    detect:
      enabled: True
      width: 640
      height: 480
   snapshots:
      enabled: True
      retain:
        default: 3
      timestamp: True
      bounding_box: True
      crop: True
      height: 500
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects

####################
  front_door_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_camera
          input_args: preset-rtsp-restream
          roles:
             - detect
        - path: rtsp://127.0.0.1:8554/front_door_camera_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.7 # min score for object to initiate tracking (default: 0.5)
          threshold: 0.8 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
    detect:
      enabled: True
      width: 640
      height: 480
    snapshots:
      enabled: True
      retain:
        default: 3
      timestamp: True
      bounding_box: True
      crop: True
      height: 500
   record:
      enabled: True
      retain:
        days: 2
        mode: active_objects

####################
detectors:
    cpu1:
      type: cpu
```

**Reply by Baethovan** [reply]
I figured out the problem. I had duplicate inputs.

**Reply by Baethovan** [reply]
So with your suggested change `preset-vaapi` I get the following errors in the logs

```
2024-04-11 12:08:22.683146918  [2024-04-11 12:08:22] ffmpeg.computer_camera.record  ERROR   : Error parsing options for output file preset_rtsp_restream.
2024-04-11 12:08:22.683208375  [2024-04-11 12:08:22] ffmpeg.computer_camera.record  ERROR   : Error opening output files: Invalid argument
2024-04-11 12:08:22.683258866  [2024-04-11 12:08:22] watchdog.computer_camera       INFO    : Terminating the existing ffmpeg process...
2024-04-11 12:08:22.683315493  [2024-04-11 12:08:22] watchdog.computer_camera       INFO    : Waiting for ffmpeg to exit gracefully...
2024-04-11 12:08:32.689788897  [2024-04-11 12:08:32] ffmpeg.computer_camera.record  ERROR   : [rtsp @ 0x559b3d43dd00] method SETUP failed: 461 Unsupported transport
2024-04-11 12:08:32.696033525  [2024-04-11 12:08:32] ffmpeg.computer_camera.record  ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url preset_rtsp_restream -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
```

**Reply by NickM-27** [reply]
`[rtsp @ 0x559b3d43dd00] method SETUP failed: 461 Unsupported transport`

looks like the wrong input args are being used or this is being used directly with a camera that is udp only

**Reply by Baethovan** [reply]
If I use `hwaccel_args: preset-intel-qsv-h264` I don't have that error

**Reply by NickM-27** [reply]
do you have any errors?

**Reply by Baethovan** [reply]
Yea, 
```
2024-04-11 13:07:56.614856320  [2024-04-11 13:07:56] watchdog.computer_camera       INFO    : Terminating the existing ffmpeg process...
2024-04-11 13:07:56.614941136  [2024-04-11 13:07:56] watchdog.computer_camera       INFO    : Waiting for ffmpeg to exit gracefully...
2024-04-11 13:08:06.622289187  [2024-04-11 13:08:06] watchdog.computer_camera       ERROR   : No new recording segments were created for computer_camera in the last 120s. restarting the ffmpeg record process...
```

**Reply by Baethovan** [reply]
Question about this. I have all of my camera functions turned off (detection, motion, snapshots and recording). Does that have anything to do with this error?

**Reply by NickM-27** [reply]
right, then those errors might just be masking the error from above. What is your current config?

**Reply by NickM-27** [reply]
no, camera functions turning off will not cause this issue

**Reply by Baethovan** [reply]
```
mqtt:
  enabled: True
  host: 192.168.0.5
  port: 1883
  user: user
  password: pass

###################
go2rtc:
  streams:
    computer_camera:
      - rtsp://user:pass@192.168.0.229:554/cam/realmonitor?channel=1&subtype=0
    computer_camera_sub:
      - rtsp://user:pas@192.168.0.229:554/cam/realmonitor?channel=1&subtype=1
    front_door_camera:
      - rtsp://user:pas@192.168.0.205:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    front_door_camera_sub:
      - rtsp://user:pas@192.168.0.205:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam_sub#audio=opus"

##################
cameras:
  computer_camera:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/computer_camera
          input_args: preset-rtsp-restream
          roles:
             - detect
        - path: rtsp://127.0.0.1:8554/computer_camera_sub
          input_args: preset_rtsp_restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.7 # min score for object to initiate tracking (default: 0.5)
          threshold: 0.8 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
    detect:
        enabled: True
        width: 640
        height: 480
   snapshots:
        enabled: True
        retain:
          default: 3
        timestamp: True
        bounding_box: True
        crop: True
        height: 500
    record:
       enabled: True
       retain:
         days: 2
         mode: active_objects
####################
  front_door_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_camera
          input_args: preset-rtsp-restream
          roles:
             - detect
        - path: rtsp://127.0.0.1:8554/front_door_camera_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.7 # min score for object to initiate tracking (default: 0.5)
          threshold: 0.8 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
    detect:
      enabled: True
      width: 640
      height: 480
    snapshots:
      enabled: True
      retain:
        default: 3
      timestamp: True
      bounding_box: True
      crop: True
      height: 500
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects

####################
detectors:
    cpu1:
      type: cpu
```
