### DISCUSSION TITLE
[Config Support]: Advice on improving performance

### DISCUSSION THREAD

**Discussion by plsfixrito** [blakeblackshear/frigate#10889] [Config Support]
### Describe the problem you are having

Been using frigate for few days and loving the experience so far.

I'm trying to understand some parts of the config and improve them for performance on CPU. I'm running Frigate under home assistant on RPI 4B 8Gb. I'm looking to get google coral later this year, but planning on using this setup for now since it seems working with 3 Camera with rare moments of 90% CPU Utilization. CPU usually runs at 50~80% and under 70C. go2rtc is used for frigate card.

My questions are:

1. I tried using go2rtc streams for recording/detection but noticed that they're using CPU so I reverted to using rtsp stream, is it better to use go2rtc or just the raw stream? I don't mind extra connections to camera.

2. For detection, if I downgrade the image quality, for example to 640x360, 512kbs at 1 FPS does this reduce or increase CPU consumption? And does high quality/FPS stream use more or less resources for detection?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
database:
  path: /config/frigate.db
  
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    camera2:
      - rtsp://192.168.8.161:554/Streaming/Channels/101/
      - "ffmpeg:camera2#audio=aac"
    canera1:
      - rtsp://192.168.8.160:554/Streaming/Channels/101/
    camera3:
      - rtsp://192.168.8.162:554/Streaming/Channels/101/
      - "ffmpeg:camera3#audio=aac"

birdseye:
  enabled: True
  mode: continuous

detectors:
  cpu1:
    type: cpu

cameras:
  cam_1:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://192.168.8.160:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://192.168.8.160:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 1
    motion:
      mask:
        - 12,30,201,30,203,17,15,18
        - 80,198,57,0,32,0,0,0,0,360,141,360
  cam_2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://192.168.8.161:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://192.168.8.161:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 1
    motion:
      mask:
        - 12,30,201,30,203,17,15,18
        - 543,0,580,0,640,0,640,82,640,228,640,360,481,360,503,302,554,118,533,110,542,35
  cam_3:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://192.168.8.162:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://192.168.8.162:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 1

objects:
  track:
    - person
    - car
    
snapshots:
  enabled: True
  timestamp: false
  bounding_box: true
  retain:
    default: 10
    
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects
    objects:
      - person
      - car
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
