### DISCUSSION TITLE
[Config Support]: Detector and jsmpeg streams show green static but recording and webrtc works

### DISCUSSION THREAD

**Discussion by brandons209** [blakeblackshear/frigate#10891] [Config Support]
### Describe the problem you are having

My setup has been working fine until the latest update to 0.13. I have to use custom ffmpeg flags to get hardware acceleration and my camera streams to work since they are cheap WiFi cameras (which screw into a light socket) and have some issues keeping up a steady RTSP stream. Hardware acceleration is done using a NVIDIA Quadro P600 card. Detection uses the card with a Tensorrt model. When I updated to 0.13 my detector and jsmpeg streams stopped working, while recording and webrtc live views worked. I'm guessing some update to ffmpeg or another caused this issue but not sure what.

I've tried every possible combination of flags using presets, custom flags, with and without hardware acceleration and transcoding at different stages. The cameras only output h265 video so I transcode it to h264 for both detecting and recording. go2rtc also had issues transcoding to h264 as well, the streams never worked when I was transcoding this way. 

When trying to fix the issue I ran into a number of different errors depending on what I had configured, the configs posted here are the settings that I have used since 0.11 and work the best.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.169
  port: 1883
  user: ***
  password: ***

detectors:
  tensorrt:
    type: tensorrt
    device: 0
  #cpu1:
  #  type: cpu
  #  num_threads: 8

model:
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416


go2rtc:
  rtsp:
    username: ***
    password: ***
  streams:
    patio_cam:
      - rtsp://lapis:****@192.168.0.10:1024/live/ch0
      #- ffmpeg:patio_cam#video=h264/rk#audio=acc
    patio_cam_sd:
      - rtsp://***:***@192.168.0.10:1024/live/ch1
      #- ffmpeg:patio_cam_sd#video=h264/rk#audio=acc
    front_door_cam:
      - rtsp://***:***1@192.168.0.9:1024/live/ch0
      #- ffmpeg:front_door_cam#video=h264/rk#audio=acc
    front_door_cam_sd:
      - rtsp://***:***@192.168.0.9:1024/live/ch1
      #- ffmpeg:front_door_cam_sd#video=h264/rk#audio=acc
  webrtc:
    candidates:
      - 192.168.0.199:8555
      - stun:8555
        
birdseye:
  enabled: True
  quality: 1
  mode: continuous
  width: 1920
  height: 1080
  restream: true

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  input_args: -c:v hevc_cuvid -avoid_negative_ts make_zero -fflags +nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -rtsp_transport tcp -timeout 20000000 -use_wallclock_as_timestamps 1
  #input_args: preset-rtsp-restream
  hwaccel_args: [] #preset-nvidia-h264 #-hwaccel cuda -hwaccel_output_format cuda # -c:v hevc_cuvid 
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p -vf mpdecimate 
    #record: preset-record-generic-audio-copy
    record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -c:v h264_nvenc -b:v 4M -r 30

objects:
  track:
    - person
    - cat
    - dog

live:
  quality: 1

snapshots:
  enabled: True
  timestamp: False
  retain:
    default: 14

cameras:
  Patio:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_cam
          roles:
            - detect
            - record
    live:
      stream_name: patio_cam_sd

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects 
    
    detect:
      width: 2560
      height: 1440
      fps: 5

  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_cam
          roles:
            - detect
            - record
    live:
      stream_name: front_door_cam_sd

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects 
    objects:
      filters:
        person:
          mask:
            - 304,0,496,0,620,0,956,0,1337,0,2560,0,2560,506,1012,243,318,172,0,315,0,0
            - 2503,622,2404,612,2292,604,2294,956,2503,939
            - 1883,757,2018,742,1984,515,1912,491 
    motion:
      mask:
        - 304,0,496,0,620,0,956,0,1337,0,2560,0,2560,506,1012,243,318,172,0,315,0,0

    detect:
      width: 2560
      height: 1440
      fps: 5
```

### Relevant log output

```shell
2024-04-08 19:43:27.886502216  [INFO] Preparing Frigate...
2024-04-08 19:43:27.926194244  [INFO] Starting Frigate...
2024-04-08 19:43:30.762545360  [2024-04-08 19:43:30] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-04-08 19:43:30.930086947  [2024-04-08 19:43:30] peewee_migrate.logs            INFO    : Starting migrations
2024-04-08 19:43:30.950779417  [2024-04-08 19:43:30] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-04-08 19:43:30.955360987  [2024-04-08 19:43:30] frigate.app                    INFO    : Recording process started: 597
2024-04-08 19:43:30.969601777  [2024-04-08 19:43:30] frigate.app                    INFO    : go2rtc process pid: 100
2024-04-08 19:43:31.083639216  [2024-04-08 19:43:31] detector.tensorrt              INFO    : Starting detection process: 607
2024-04-08 19:43:31.084018533  [2024-04-08 19:43:31] frigate.app                    INFO    : Output process started: 609
2024-04-08 19:43:31.161465662  [2024-04-08 19:43:31] frigate.app                    INFO    : Camera processor started for Patio: 613
2024-04-08 19:43:31.217661489  [2024-04-08 19:43:31] frigate.app                    INFO    : Camera processor started for Front_Door: 616
2024-04-08 19:43:31.218459727  [2024-04-08 19:43:31] frigate.app                    INFO    : Capture process started for Patio: 619
2024-04-08 19:43:31.218469434  [2024-04-08 19:43:31] frigate.app                    INFO    : Capture process started for Front_Door: 623
2024-04-08 19:43:32.569211780  [2024-04-08 19:43:32] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 34 MiB
2024-04-08 19:43:33.181888308  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +194, GPU +74, now: CPU 548, GPU 218 (MiB)
2024-04-08 19:43:33.414981200  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +110, GPU +44, now: CPU 658, GPU 262 (MiB)
2024-04-08 19:43:33.439719609  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +34, now: CPU 0, GPU 34 (MiB)
2024-04-08 19:43:33.443422375  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 623, GPU 254 (MiB)
2024-04-08 19:43:33.443864440  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 623, GPU 262 (MiB)
2024-04-08 19:43:33.443878160  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +13, now: CPU 0, GPU 47 (MiB)
2024-04-08 19:43:33.443895321  [2024-04-08 19:43:33] frigate.detectors.plugins.tensorrt WARNING : CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars

2024-04-08 19:43:27.897283964  [INFO] Preparing new go2rtc config...
2024-04-08 19:43:28.540028567  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-04-08 19:43:28.572733253  [INFO] Starting go2rtc...
2024-04-08 19:43:28.658665986  19:43:28.658 INF go2rtc version 1.8.4 linux/amd64
2024-04-08 19:43:28.659810136  19:43:28.659 INF [rtsp] listen addr=:8554
2024-04-08 19:43:28.659816873  19:43:28.659 INF [api] listen addr=:1984
2024-04-08 19:43:28.674223260  19:43:28.674 INF [webrtc] listen addr=:8555
2024-04-08 19:43:37.887187602  [INFO] Starting go2rtc healthcheck service...
2024-04-08 19:49:42.817243894  19:49:42.816 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.0.199:52022->192.168.0.9:1024: i/o timeout" url=rtsp://***:***@192.168.0.9:1024/live/ch0
```

### Frigate stats

```json
// 20240408200248
// http://192.168.0.199:5000/api/stats

{
  "cameras": {
    "Front_Door": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 4.1,
      "capture_pid": 623,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 630,
      "pid": 616,
      "process_fps": 4.1,
      "skipped_fps": 0.0
    },
    "Patio": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 3.9,
      "capture_pid": 619,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 625,
      "pid": 613,
      "process_fps": 3.9,
      "skipped_fps": 0.0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "43": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "44": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "91": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "92": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "93": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "100": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "3.4",
      "cpu_average": "4",
      "mem": "0.0"
    },
    "109": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "110": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "5.3",
      "cpu_average": "3",
      "mem": "0.6"
    },
    "128": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "156": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "157": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "158": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "163": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "169": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "177": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "194": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "215": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "237": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "255": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "279": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "303": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "595": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "597": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.0",
      "cpu_average": "5",
      "mem": "0.3"
    },
    "606": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "607": {
      "cmdline": "frigate.detector.tensorrt",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.8"
    },
    "609": {
      "cmdline": "frigate.output       ",
      "cpu": "48.4",
      "cpu_average": "48",
      "mem": "0.3"
    },
    "613": {
      "cmdline": "frigate.process:Patio",
      "cpu": "2.4",
      "cpu_average": "3",
      "mem": "0.3"
    },
    "614": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "616": {
      "cmdline": "frigate.process:Front_Door",
      "cpu": "2.4",
      "cpu_average": "3",
      "mem": "0.3"
    },
    "618": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "619": {
      "cmdline": "frigate.capture:Patio",
      "cpu": "14.7",
      "cpu_average": "19",
      "mem": "0.3"
    },
    "623": {
      "cmdline": "frigate.capture:Front_Door",
      "cpu": "14.7",
      "cpu_average": "18",
      "mem": "0.3"
    },
    "625": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v hevc_cuvid -avoid_negative_ts make_zero -fflags +nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -rtsp_transport tcp -timeout 20000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/patio_cam -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -c:v h264_nvenc -b:v 4M -r 30 /tmp/cache/Patio@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p -vf mpdecimate pipe:",
      "cpu": "21.1",
      "cpu_average": "23",
      "mem": "0.8"
    },
    "627": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1920x1080 -codec:v mpeg1video -q 1 -bf 0 pipe:",
      "cpu": "43.2",
      "cpu_average": "40",
      "mem": "0.1"
    },
    "630": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v hevc_cuvid -avoid_negative_ts make_zero -fflags +nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -rtsp_transport tcp -timeout 20000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/front_door_cam -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -c:v h264_nvenc -b:v 4M -r 30 /tmp/cache/Front_Door@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p -vf mpdecimate pipe:",
      "cpu": "20.6",
      "cpu_average": "23",
      "mem": "0.8"
    },
    "4755": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0.0,
  "detectors": {
    "tensorrt": {
      "detection_start": 0.0,
      "inference_speed": 10.0,
      "pid": 607
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 100
    },
    "logger": {
      "pid": 595
    },
    "recording": {
      "pid": 597
    }
  },
  "service": {
    "last_updated": 1712620965,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 113.7,
        "mount_type": "tmpfs",
        "total": 128.0,
        "used": 14.3
      },
      "/media/frigate/clips": {
        "free": 8700059.0,
        "mount_type": "nfs4",
        "total": 41447113.0,
        "used": 32747054.0
      },
      "/media/frigate/recordings": {
        "free": 8700059.0,
        "mount_type": "nfs4",
        "total": 41447113.0,
        "used": 32747054.0
      },
      "/tmp/cache": {
        "free": 945.4,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 8.3
      }
    },
    "temperatures": {
      
    },
    "uptime": 1154,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Here is the go2rtc stream diagnostics via the api.

```json
// 20240408200406
// http://192.168.0.199:5000/api/go2rtc/streams

{
  "birdseye": {
    "consumers": null,
    "producers": [
      {
        "url": "exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -r 10 -i /tmp/cache/birdseye -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -rtsp_transport tcp -f rtsp {output}"
      }
    ]
  },
  "front_door_cam": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264, H265",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:51314",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//IUAAAAMAkAAAAwAAAwCWJQJA; sprop-sps=QgEBIUAAAAMAkAAAAwAAAwCWoAEgIAURZ67kShc1AQEBBAAAAwAEAAADAFAg; sprop-pps=RAHA98Dm2Q==\r\na=control:trackID=0\r\n",
        "send": 148394423,
        "senders": [
          "96 H265, bytes=146638935, receivers=1"
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/front_door_cam",
        "user_agent": "Lavf59.27.100"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265"
        ],
        "receivers": [
          "100 H265, bytes=101457876, senders=1"
        ],
        "recv": 102369936,
        "remote_addr": "192.168.0.9:1024",
        "sdp": "v=0\r\no=- 1712620185 2764 IN IP4 0.0.0.0\r\ns=gvminirtsp\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=range:npt=now-\r\na=recvonly\r\na=control:*\r\nm=video 0 RTP/AVP 100\na=rtpmap:100 H265/90000\na=fmtp:100 sprop-vps=QAEMAf//IUAAAAMAkAAAAwAAAwCWJQJA; sprop-sps=QgEBIUAAAAMAkAAAAwAAAwCWoAEgIAURZ67kShc1AQEBBAAAAwAEAAADAFAg; sprop-pps=RAHA98Dm2Q==\na=control:track0\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://192.168.0.9:1024/live/ch0",
        "user_agent": "go2rtc/1.8.4"
      }
    ]
  },
  "front_door_cam_sd": {
    "consumers": [
      
    ],
    "producers": [
      {
        "url": "rtsp://*:*@192.168.0.9:1024/live/ch1"
      }
    ]
  },
  "patio_cam": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264, H265",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:51300",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//IUAAAAMAkAAAAwAAAwCWJQJA; sprop-sps=QgEBIUAAAAMAkAAAAwAAAwCWoAEgIAURZ67kShc1AQEBBAAAAwAEAAADAFAg; sprop-pps=RAHA98Dm2Q==\r\na=control:trackID=0\r\n",
        "send": 104133203,
        "senders": [
          "96 H265, bytes=102853667, receivers=1"
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/patio_cam",
        "user_agent": "Lavf59.27.100"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265"
        ],
        "receivers": [
          "100 H265, bytes=102853667, senders=1"
        ],
        "recv": 103813319,
        "remote_addr": "192.168.0.10:1024",
        "sdp": "v=0\r\no=- 1712619812 236310 IN IP4 0.0.0.0\r\ns=gvminirtsp\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=range:npt=now-\r\na=recvonly\r\na=control:*\r\nm=video 0 RTP/AVP 100\na=rtpmap:100 H265/90000\na=fmtp:100 sprop-vps=QAEMAf//IUAAAAMAkAAAAwAAAwCWJQJA; sprop-sps=QgEBIUAAAAMAkAAAAwAAAwCWoAEgIAURZ67kShc1AQEBBAAAAwAEAAADAFAg; sprop-pps=RAHA98Dm2Q==\na=control:track0\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://192.168.0.10:1024/live/ch0",
        "user_agent": "go2rtc/1.8.4"
      }
    ]
  },
  "patio_cam_sd": {
    "consumers": null,
    "producers": [
      {
        "url": "rtsp://*:*@192.168.0.10:1024/live/ch1"
      }
    ]
  }
}
