### DISCUSSION TITLE
[Support]: i7-8550u proof of concept

### DISCUSSION THREAD

**Discussion by maxdd** [blakeblackshear/frigate#10892] [General]
Hello,
I would like to setup a poc to see how frigate performs in my environment.
I have an i7-8550u with debian and docker as my main device and 1-2 Tapo C320.
Here, some hw info

```
ls /dev/dri/
by-path  card0  card1  renderD128  renderD129
```

```
drm_info -j | jq 'with_entries(.value |= .driver.desc)'
{
  "/dev/dri/card1": "Intel Graphics",
  "/dev/dri/card0": "nVidia Riva/TNT/GeForce/Quadro/Tesla/Tegra K1+"
}
```

```
*-display                 
       description: VGA compatible controller
       product: UHD Graphics 620 [8086:5917]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 mode=1920x1080 resolution=1920,1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:1f0-1ef iomemory:1f0-1ef irq:142 memory:1ff0000000-1ff0ffffff memory:1fe0000000-1fefffffff ioport:5000(size=64) memory:c0000-dffff
  *-display
       description: 3D controller
       product: GM108M [GeForce 930MX] [10DE:134E]
       vendor: NVIDIA Corporation [10DE]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:141 memory:b2000000-b2ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:4000(size=128)
```

I've seen i have to point to the proper renderDxyz in the docker and i was wondering whether i should use D128 or D129 or cardX.
With openVino i have 15ms inference speed but i'm wondering whether going for the GPU would be better

**Comment by NickM-27** [comment]
in the vast majority of cases it is D128.

**Reply by maxdd** [reply]
But isn't one the UHD of Intel and the other the GeForce 930MX? in terms of performance am i wrong in thinking that the  GeForce would give me better inference time and hence configure for that?

**Reply by NickM-27** [reply]
Using detection on nvidia is entirely different and can't be done that way. 

The main concern with the render devices is hwaccel. Openvino figures out what to use on its own.

**Reply by maxdd** [reply]
I see, i think i got your point. Does that mean that openvino can offload HW rendering to CPU and GPU on its own? I thought it was only supposed to use the internal graphics card

**Reply by NickM-27** [reply]
OpenVINO is for object detection, it has nothing to do with video

hwaccel, (vaapi) is what is used for decoding of video. That is done on GPU when you setup hwaccel args

**Reply by maxdd** [reply]
Thank you for the clarification!
One more thing, I've tried both direct access jstream and go2rtc and ive seen a good increase in CPU usage (~18% vs 30%) when using the second (i've declared two cameras instead of 2 inputs, one for record and the other for detect). Is this within reasonable margin? I do expect to have some added load but I was wondering whether it is a reasonable value. I don't need multiple access but I do hate to have that low resolution in the frigate live.

**Reply by NickM-27** [reply]
restreaming can be decent CPU usage depending on the resolution of the stream. Without your config there is no way to tell if something is misconfigured

**Reply by maxdd** [reply]
vanilla version (jsmpeg)

```
mqtt:
  enabled: false

cameras:
  tapo_garden:
    enabled: true
    birdseye:
      mode: objects # <----- Objects mode prevents birdseye from being triggered by bushes in the wind.
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://user:pw@192.168.1.42/stream2
          roles:
          - detect
        - path: rtsp://user:pw@192.168.1.42/stream1
          roles:
          - record
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
      - person
      - face
      - bird
      - cat
      - dog
    detect:
      #width: 640
      #height: 360
      fps: 4
    snapshots:
      enabled: true
    record:
      enabled: true
    zones:
      zone_0:
        coordinates: 446,360,462,142,462,98,391,92,389,136,142,360

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

```

go2rtc version

```
mqtt:
  enabled: false

go2rtc:
  streams:
    tapo_c320_hd:
      - rtsp://user:pw@192.168.1.42/stream1
    tapo_c320_sd:
      - rtsp://user:pw@192.168.1.42/stream2

cameras:
  Tapo_C320_HD:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.52:8554/tapo_c320_hd
          roles:
            - record
    detect:
      enabled: False

  Tapo_C320_SD:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.52:8554/tapo_c320_sd # <----- The stream you want to use for detection
          roles:
            - detect
    objects:
      track:
      - person
      - face
    detect:
      width: 640
      height: 360
      fps: 4
    snapshots:
      enabled: true # <----- Enable snapshots
    zones:
      zone_0:
        coordinates: 446,360,462,142,462,98,391,92,389,136,142,360

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

```

**Reply by NickM-27** [reply]
so your problem is that you are created two cameras, one for the HD and one for the SD. That is incorrect. You should have one camera with multiple streams defined 

https://docs.frigate.video/guides/getting_started#step-6-enable-recording-andor-snapshots

**Reply by maxdd** [reply]
I've changed to this

```
mqtt:
  enabled: false

go2rtc:
  streams:
    tapo_c320_hd:
      - rtsp://itsmaxdd:C@lcio90@192.168.1.42/stream1
    tapo_c320_sd:
      - rtsp://itsmaxdd:C@lcio90@192.168.1.42/stream2

cameras:
  Tapo_C320:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.52:8554/tapo_c320_sd # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://192.168.1.52:8554/tapo_c320_hd # <----- The stream you want to use for detection
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
      - person
      - face
      - bird
      - cat
      - dog
    detect:
      #width: 640
      #height: 360
      fps: 4
    snapshots:
      enabled: true
    record:
      enabled: true
    zones:
      zone_0:
        coordinates: 446,360,462,142,462,98,391,92,389,136,142,360

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

```

although i only see jsmpeg in the live (with terrible quality). I've tried this as well

```
go2rtc:
  streams:
    tapo_c320_hd:
      - rtsp://itsmaxdd:C@lcio90@192.168.1.42/stream1
      - "ffmpeg:tapo_c320_hd#video=h264"
```
This is ffmpeg probe

```
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: 15/1

Audio:

Codec: PCM A-law / G.711 A-law

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1440
FPS: 15/1

Audio:

Codec: PCM A-law / G.711 A-law
```

Below a basic ps aux with and without go2rtc enabled

```
%CPU %MEM ARGS Sat Apr 13 05:01:51 PM CEST 2024
 3.6  0.4 ffmpeg
 5.1  0.2 ffmpeg
 6.7  3.2 frigate.detector.ov
15.8  0.7 frigate.process:tapo_garden
%CPU %MEM ARGS Sat Apr 13 05:07:36 PM CEST 2024
 1.1  0.7 frigate.recording_manager
 1.8  0.1 /usr/local/go2rtc/bin/go2rtc
 2.3  0.3 ffmpeg
 3.3  0.3 ffmpeg
17.5  2.8 frigate.detector.ov
23.2  0.7 frigate.process:Tapo_C320
```

rougly a 10% increase in usage

**Reply by NickM-27** [reply]
> although i only see jsmpeg in the live (with terrible quality). I've tried this as well

this is because the naming is incorrect. You called the camera `Tapo_C320_HD` but you called the stream `tapo_C320_hd`

**Reply by maxdd** [reply]
The camera is called Tapo_C320 in the new config, i thought the path was what it matters.
What it's not clear though is if i have two streams 

```
tapo_c320_hd 
tapo_c320_sd
```

how can i have 1 camera with two inputs if the camera must have the same name of the stream?

**Reply by NickM-27** [reply]
the stream that is used for the live view is the one that matches the name of the camera. so really, you would want it to look like this

```

go2rtc:
  streams:
    tapo_c320:
      - rtsp://itsmaxdd:C@lcio90@192.168.1.42/stream1
    tapo_c320_sd:
      - rtsp://itsmaxdd:C@lcio90@192.168.1.42/stream2

cameras:
  tapo_c320:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.52:8554/tapo_c320_sd
          roles:
            - detect
        - path: rtsp://192.168.1.52:8554/tapo_c320
          roles:
            - record
```

**Reply by maxdd** [reply]
That indeed solved the issue, now i see both webrtc and mse.
Btw at startup i also receive

https://github.com/blakeblackshear/frigate/blob/6476f8ade78a337be2244ead486d68e6d6365807/frigate/config.py#L1306

which feels related to

```
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```
is that normal? feels like labelmap is {}
