### DISCUSSION TITLE
[Detector Support]: OpenVINO / yolov8 / yolov9 / Opset error

### DISCUSSION THREAD

**Discussion by jsapede** [blakeblackshear/frigate#10893] [Detector Support]
### Describe the problem you are having

been playing around with openvino and detector models, especially yolov8 and now yolov9, and for newer models i got opset errors in frigate execution.

Building yolov8 model from this : 

https://colab.research.google.com/drive/1G05mESOhDdM1HpinKMJZWpI_jxNq_qIO?usp=sharing#scrollTo=ts7CSx7uTNff

works, flawlessly.

however, trying to implement : 

https://github.com/harakas/models/releases

or build from here : 

https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/yolov8-optimization

got the following error : 

Cannot create Interpolate layer /model.10/Resize id:607 from unsupported opset: opset11

Tried this morning to switch to new yolov9 suing this : 

https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/yolov9-optimization

and another time got this opset11 error, as well as yolov9 is not an option for "model_type:"

Yolov9 model is NCHW and BGR and 640x640

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /config/models/yolov9/yolov9.xml
model: 
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /config/models/yolov8s-320/coco_80cl.txt
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
#    image: ghcr.io/blakeblackshear/frigate:0.13-beta6
    shm_size: "256mb" # update for your cameras based on calculation above
    group_add:
      - "44"
      - "106"
      - "29"
      - "103"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/config:/config
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
Cannot create Interpolate layer /model.10/Resize id:607 from unsupported opset: opset11
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)
