### DISCUSSION TITLE
[Camera Support]: Does this error means the camera is going offline?

### DISCUSSION THREAD

**Discussion by lee-costa** [blakeblackshear/frigate#10890] [Camera Support] [answered]
### Describe the problem you are having

I often see this error pop up once in a while in the logs:

    Message: frigate[953]: 2024-04-07 22:58:12.285809296  22:58:12.283 WRN [github.com/AlexxIT/go2rtc/internal/streams/producer.go:171](http://github.com/AlexxIT/go2rtc/internal/streams/producer.go:171) > error="read tcp 172.18.0.2:44538->192.168.141.16:554: i/o timeout" url=rtsp://ha:PASSWORD$@192.168.141.16:554/cam/realmonitor?channel=1&subtype=0

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
#########################################################
## Global
#########################################################

mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED

birdseye:
  enabled: True
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 10

go2rtc:
  streams:
    driveway_cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
    backyard_cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0
    living_room_cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.16:554/cam/realmonitor?channel=1&subtype=0

live:
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 2160
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5

##########################################################
## Driveway
##########################################################

cameras:
  driveway_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    # detect:
    #   width: 3840
    #   height: 2160
    #   fps: 10
    #   enabled: True

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True

    zones:
      driveway:
        coordinates: 0,1080,255,826,1070,658,1920,904,1920,1080
        objects:
          - person
          - dog
          - cat
          - bicycle
      street:
        coordinates: 1246,699,1829,863,1840,769,1365,648
        objects:
          - person
          - dog
          - cat
          - car
          - bicycle

    objects:
      track:
        - person
        - dog
        - car
        - cat
        - bicycle
      filters:
        person:
          min_area: 8000
          max_area: 100000
          mask:
            - 1215,608,0,854,0,0,1920,0,1920,780
        dog:
          max_area: 12000
          mask:
            - 1215,608,0,854,0,0,1920,0,1920,780
        car:
          max_area: 200000
          mask:
            - 1215,608,0,854,0,0,1920,0,1920,780
        cat:
          mask:
            - 1215,608,0,854,0,0,1920,0,1920,780
        bicycle:
          mask:
            - 1215,608,0,854,0,0,1920,0,1920,780

    motion:
      mask:
       - 1215,608,0,854,0,0,1920,0,1920,780

    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
         # mode: motion #
        required_zones:
          - driveway
          - street

    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - driveway
        - street
      retain:
        default: 10

##########################################################
## Backyard
##########################################################

  backyard_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

# Detect
    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True

    # detect:
    #   width: 3840
    #   height: 2160
    #   fps: 10
    #   enabled: True

    motion:
      threshold: 25
      mask:
       - 1562,296,1624,211,1920,255,1920,0,0,0,21,534,1146,327
       - 1899,656,1696,588,1612,764,1815,873

    objects:
      track:
        - person
        - dog
        - bird
      filters:
        dog:
          mask:
            - 1562,296,1624,211,1920,255,1920,0,0,0,21,534,1146,327
        person:
          mask:
            - 1562,296,1624,211,1920,255,1920,0,0,0,21,534,1146,327
        bird:
          mask:
            - 1562,296,1624,211,1920,255,1920,0,0,0,21,534,1146,327

    record:
      enabled: True
      retain:
        days: 10
        # mode: active_objects
        mode: motion
      events:
        retain:
          default: 10
          # mode: active_objects
          mode: motion

##########################################################
## Living Room
##########################################################

  living_room_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    motion:
      mask:
        - 1641,207,1661,615,1239,586,1250,267
        - 1862,0,1434,0,1440,99,1860,105

    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 1509,269,1540,541,1160,563,1156,323
            - 1862,0,1434,0,1440,99,1860,105

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True

    record:
      enabled: True
      retain:
        days: 10
        # mode: active_objects
        mode: motion
      events:
        retain:
          default: 10
          # mode: active_objects
          mode: motion
```

### Relevant log output

```shell
Message: frigate[953]: 2024-04-07 22:58:12.285809296  22:58:12.283 WRN [github.com/AlexxIT/go2rtc/internal/streams/producer.go:171](http://github.com/AlexxIT/go2rtc/internal/streams/producer.go:171) > error="read tcp 172.18.0.2:44538->192.168.141.16:554: i/o timeout" url=rtsp://ha:PASSWORD$@192.168.141.16:554/cam/realmonitor?channel=1&subtype=0
```

### FFprobe output from your camera

```shell
Not sure how to run this.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

IP2M-841W

### Any other information that may be helpful

This camera is Wi-Fi FIY.
