### DISCUSSION TITLE
edgetpu detector not loading frigate plus custom models

### DISCUSSION THREAD

**Discussion by ht2k05** [blakeblackshear/frigate#10916] [Detector Support] [answered]
### Describe the problem you are having

just trying to get the custom models working in frigate as an addon. in the frigate yaml do i use the model ID for edgeTPU or CPU

i have a coral TPU that works fine..but when i put in the plus path as the edgetpu model ID frigate crashes

### Version

0.13.2

### Frigate config file

```yaml
#  host: edited
#  user: edited
#  password: edited!

mqtt:
  host: edited
  port: edited
  user: edited
  password: edtited
  topic_prefix: edited
  stats_interval: 60

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb
    
model:
  path: plus://tpumodelidhere
  
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
```

### docker-compose file or Docker CLI command

```yaml
na
```

### Relevant log output

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
