### DISCUSSION TITLE
[Config Support]: simple motion detection

### DISCUSSION THREAD

**Discussion by sulliwane** [blakeblackshear/frigate#10922] [Config Support]
### Describe the problem you are having

Hi there!
Thanks for that awesome Firgate. So:

- I have HA running on a very lightweight raspberry pie type of hardware
- I have don't have a Coral. 
- I just want to use Frigate for local retention of motion recordings. 
- I just want to record on motion.
- I don't want to run complex tensorflow image recognition, heavy on CPU.
- I have [this camera](https://support.eufy.com/s/article/Introducing-eufy-Indoor-Cam-2K-Pan-Tilt) which native resolution is 2304 x 1296

I got everything working, but I see the CPU usage is very high. Also I see "Person: 77%" which most probably implies some image recognition algo is being run.

![image](https://github.com/blakeblackshear/frigate/assets/1733686/820e9793-2428-4d00-b8b9-066dc51eddfe)

Which config would you recommend to be as low CPU as possible, and just get very basic recording on motion? Or is my current config enough?

Any help would be much appreciated 🙏

Bonus question: would getting a Coral reduce the CPU load for my specific use case ?
Bonus question 2: how to push HA notification on motion with snapshot only when a specific HA state is being checked and true (away from home)?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: core-mosquitto
  port: 1883
  user: "<redacted>"
  password: "<redacted>"

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 10

cameras:
  porte: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@192.168.1.12/live0
          roles:
            - detect
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by sulliwane** [comment]
Note: I updated the config a bit and it seems CPU usage decreased. Still, happy to get your feedback on how to improve even more!

Note: my [camera](https://support.eufy.com/s/article/Introducing-eufy-Indoor-Cam-2K-Pan-Tilt) native/full resolution is 2304 x 1296.

Note 2: currently my recordings seem to be in HD only, as you can see:
![image](https://github.com/blakeblackshear/frigate/assets/1733686/d41c7021-cf7a-43ad-8ce0-f1a060edfbad)
but it should be 2304 x 1296 no? Maybe RTSP is only available in 1920 x 1080...

Newest config:
```
mqtt:
  enabled: True
  host: core-mosquitto
  port: 1883
  user: "<redacted>"
  password: "<redacted>"

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 10

cameras:
  porte: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@192.168.1.12/live0
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1152
      height: 648
      fps: 5
    record:
      enabled: true
```

Thanks a lot in advance!

**Reply by NickM-27** [reply]
recordings are copied so the 1920x1080 is what the camera is sending

you can use openvino in CPU mode and likely reduce object detection cpu load or you can just disable detect altogether in which case motion recordings only will be kept

**Reply by sulliwane** [reply]
thanks a lot for the prompt reply! I get it now, so I removed "detect" keyword.

also, is there any way to record only when some conditions are met, based on Home Assistant states? (like, away from home).

Trying to be storage savy :)

**Reply by NickM-27** [reply]
> thanks a lot for the prompt reply! I get it now, so I removed "detect" keyword.

that does not disable detect. You need to explicitly set detect to enabled: false

> also, is there any way to record only when some conditions are met, based on Home Assistant states? (like, away from home).

you can use the integration toggles in HA to disable recordings. But storage is cheap and bad stuff can happen when home too so in general I wouldn't recommend that

**Reply by sulliwane** [reply]
Also, I don't really understand what is the difference between "retain" and "events > retain"...

```
record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
```

**Reply by NickM-27** [reply]
> Also, I don't really understand what is the difference between "retain" and "events > retain"...

`retain` is for general recordings while `events -> retain` is for objects that are detected

**Reply by sulliwane** [reply]
Thanks, so I set detect to false:
```
cameras:
  porte:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://<redacted>:<redacted>@192.168.1.12/live0
          roles:
            - record
    detect:
      enabled: false
```
So with `detect > enabled: false`, i assume that `events > retain` isn't useful anymore in the config?

**Reply by NickM-27** [reply]
> So with detect > enabled: false, i assume that events > retain isn't useful anymore in the config?

correct

**Reply by sulliwane** [reply]
thanks a lot @NickM-27 for the help. puting `detect: false` seems to have disable motion detection...

I don't see any new events now. Strange

**Reply by NickM-27** [reply]
that is expected, `events` are only for object detections. In the next version of frigate which has an entirely new UI, there will be a tab in the review page to review motion

**Reply by hawkeye217** [reply]
Events are generated from objects that were detected. If you disable detection, events will never be saved.

But with motion recording enabled, Frigate will retain recording segments with motion. You can review those from the "Recordings" button for your camera.

**Reply by sulliwane** [reply]
Got it. I re-enabled detection then 😄 

And checked the cpu of my board, I see "Rockchip" being mentioned:
```bash
# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     1296.0000
CPU min MHz:                     408.0000
BogoMIPS:                        48.00
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
# uname -a
Linux homeassistant 5.15.35-rockchip64 #trunk SMP PREEMPT Sat Apr 23 12:10:09 UTC 2022 aarch64 GNU/Linux
# cat /proc/device-tree/compatible
rockchip,rk3318-boxrockchip,rk3328-boxrockchip,rk3328
#docker ps
ghcr.io/blakeblackshear/frigate:0.13.2
```
Looking at the Frigate Hardware Acceleration page, it seems I should use a -rk docker image, together with `--privileged` mode:
![image](https://github.com/blakeblackshear/frigate/assets/1733686/9ecca87a-c848-4a4a-b74d-ae15abe8cf70)

Any pointer on where the Dockerfile I need to edit is located? Also, do I need to run the "non protected" version of Frigate or not?

Finally, which docker image name is the correct/latest one? I saw a reference to this one `ghcr.io/blakeblackshear/frigate:0.13.0-beta6-rk`

Thanks a LOT for your time. Much appreciated 🙏

**Reply by NickM-27** [reply]
if you didn't setup a docker file then there is none

you can use stable-rk

**Comment by sulliwane** [comment]
sorry to look stupid, but where am I supposed to "use stable-rk"? I have SSH access to the board. 

```
root@homeassistant:/usr/share/hassio# ls addons
core  data  git  local
root@homeassistant:/usr/share/hassio# ls addons/core/
assist_microphone  deconz	duckdns		  letsencrypt  matter_server  openthread_border_router	README.md     silabs_flasher	    tellstick  zwave_js
cec_scan	   dhcp_server	git_pull	  LICENSE      mosquitto      openwakeword		rpc_shutdown  silabs-multiprotocol  vlc
configurator	   dnsmasq	google_assistant  mariadb      nginx_proxy    piper			samba	      ssh		    whisper
```

**Reply by NickM-27** [reply]
there is no rockchip addon, it is only usable when running docker directly

**Reply by sulliwane** [reply]
Got it. So no way in my current setup to benefit from the rockchip optimized docker image. Unless a rockchip addon is being published (which seems overkill?). I assume that the performance gain isn't that huge.

**Reply by NickM-27** [reply]
the reason there is no rockchip addon is because the HA addon system does not provide necessary access to the underlying devices and device info to work correctly

**Reply by sulliwane** [reply]
Hey @NickM-27 , I'm trying to run a standalone Frigate docker container on my rockchip rk3328 board. My goal is to leverage hardware acceleration to decrease CPU usage due to ffmpeg.

Here is my `docker-compose.yml` file:
```yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/hassio/homeassistant:/config
      - /usr/share/hassio/homeassistant/frigate-media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      MQTT_HOST: "core-mosquitto"
      MQTT_PORT: 1883
      MQTT_USER: "mqtt"
      MQTT_PASSWORD: "password"
      MQTT_TOPIC_PREFIX: "frigate"
```
After running `docker compose up -d` I see this line in the logs:
```bash
[2024-09-03 20:30:02] frigate.detectors  WARNING : CPU detectors are  not recommended and should only be used for testing or for trial purposes.
```
Does it mean that I won't be able to use hwaccel? (in that case, I'll revert back to installing Frigate as a HA addon).

Thanks for your help 🙏

dunno if useful:
```bash
root@homeassistant:~/services/frigate# ls /dev/dri
by-path  card0  card1  renderD128
```
