### DISCUSSION TITLE
[Config Support]:  go2rtc i/o timeout when using docker bridge network.

### DISCUSSION THREAD

**Discussion by skooj** [blakeblackshear/frigate#10925] [Config Support]
### Describe the problem you are having

When using go2rtc to restream my cameras, I get some i/o timeout errors on both of my cameras repeatedly.

These only appear when I am using a docker bridge network. If I change the network mode to 'host', it works without throwing these errors.

It looks like there was a similar issue here: #5954 but that solution resulted in different errors, and my issue appears to be network related.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: <host>
  user: frigate
  password: <pass>
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
go2rtc:
  streams:
    doorbell: #amcrest ad410
       - "rtsp://<camerausername>:<camerapassword>@<camera1ip>/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0"
    doorbell-sub:
       - "rtsp://<camerausername>:<camerapassword>@<camera1ip>/cam/realmonitor?channel=1&subtype=1&authbasic=64#backchannel=0"
    kitchen: #tapo c220
       - "rtsp://<camerausername>:<camerapassword>@<camera2ip>/stream1"
       - "ffmpeg:kitchen#audio=aac"
    kitchen-sub:
       - "rtsp://<camerausername>:<camerapassword>@<camera2ip>/stream2"
       - "ffmpeg:kitchen-sub#audio=aac"
cameras:
  kitchen:
    onvif:
      host: <camera2ip> # <------ Name the camera
      port: 2020
      user: <camerausername>
      password: <camerapassword>
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: "rtsp://127.0.0.1:8554/kitchen"
          input_args: preset-rtsp-restream
          roles:
            #- rtmp
            - record
        - path: "rtsp://127.0.0.1:8554/kitchen-sub"
          roles:
            - detect
    #rtmp:
    #  enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #2560 # <---- update for your camera's resolution
      height: 360 #1920 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 10
          mode: motion
    snapshots:
      enabled: True
    motion:
      mask:
        - 234,0,232,27,0,21,0,0
    objects:
      filters:
        animal:
          mask:
        person:
          mask:  
          threshold: 0.7 
  
  doorbell: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: "rtsp://127.0.0.1:8554/doorbell"
          input_args: preset-rtsp-restream
          roles:
            #- rtmp
            - record
        - path: "rtsp://127.0.0.1:8554/doorbell-sub"
          roles:
            - detect
    #rtmp:
    #  enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 #2560 # <---- update for your camera's resolution
      height: 576 #1920 # <---- update for your camera's resolution
    record:
      enabled: True
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
    motion:
      mask:
        - 496,0,497,24,720,24,720,0,495,0,495,0
        - 0,325,217,268,232,81,0,38
        - 625,105,654,111,684,127,720,179,720,213,720,277,673,287,632,291,556,299,519,286,494,236,506,193,538,165,576,134,600,108
        - 278,23,284,40,292,81,297,140,295,168,264,194,228,230,179,258,136,256,127,214,77,101,89,80,114,71
    objects:
      filters:
        animal:
          mask:
            - 0,325,217,268,232,81,0,38
            - 579,27,591,59,600,95,611,140,616,186,624,236,629,267,625,316,611,406,597,499,583,538,566,576
        person:
          mask:
            - 56,554,69,576,110,576,132,554,142,534,138,509,126,493,112,466,93,447,67,454,42,462,38,487,42,514 
            - 0,325,217,268,232,81,0,38
        train:
          mask:
            - 282,312,516,324,496,271,288,269
        car:
          mask:
            - 282,312,516,324,496,271,288,269
        Car:
          mask:
            - 282,312,516,324,496,271,288,269
        truck:
          mask:
            - 282,312,516,324,496,271,288,269
        bus:
          mask:
            - 282,312,516,324,496,271,288,269
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: /config/spaghettinet_edgetpu_l_compiled.tflite
model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal
objects:
  track:
    - person
    - animal
#    - car
#    - bus
#    - train
#    - truck
  filters:
    person:
      threshold: 0.81
```

### Relevant log output

```shell
2024-04-10 11:44:22.652161573  11:44:22.651 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.7:33020-><camera1ip>:554: i/o timeout" url=rtsp://<camera1>:<camera1pass>@<camera1ip>/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0
2024-04-10 11:44:22.664798819  11:44:22.664 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.7:43382-><camera2ip>:554: i/o timeout" url=rtsp://<camera2>:<camera2pass>@<camera2ip>/stream1
```

### Frigate stats

```json
{
  "cameras": {
    "doorbell": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 479,
      "detection_enabled": 1,
      "detection_fps": 12.9,
      "ffmpeg_pid": 484,
      "pid": 465,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "kitchen": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4.15,
      "capture_pid": 468,
      "detection_enabled": 1,
      "detection_fps": 2.88,
      "ffmpeg_pid": 658,
      "pid": 464,
      "process_fps": 2.9,
      "skipped_fps": 0.61
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "47": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "1.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "96": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "2.5",
      "cpu_average": "4",
      "mem": "0.7"
    },
    "107": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "119": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "140": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "141": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "177": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "178": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "179": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "187": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "195": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "208": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "221": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "231": {
      "cmdline": "nginx: cache loader process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "441": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "443": {
      "cmdline": "frigate.recording_manager",
      "cpu": "1.2",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "452": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "453": {
      "cmdline": "frigate.detector.coral",
      "cpu": "5.4",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "456": {
      "cmdline": "frigate.output       ",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "461": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "463": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "464": {
      "cmdline": "frigate.process:kitchen",
      "cpu": "1.9",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "465": {
      "cmdline": "frigate.process:doorbell",
      "cpu": "11.9",
      "cpu_average": "5",
      "mem": "0.4"
    },
    "467": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "468": {
      "cmdline": "frigate.capture:kitchen",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "479": {
      "cmdline": "frigate.capture:doorbell",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "484": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/doorbell-sub -r 5 -vf fps=5,scale_cuda=w=720:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.9",
      "cpu_average": "15",
      "mem": "0.9"
    },
    "490": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "628": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/kitchen -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/kitchen@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.6",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "629": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/kitchen?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1bb3ec5496b1a75a98741b2c405ba3d4",
      "cpu": "1.6",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "658": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/kitchen-sub -r 5 -vf fps=5,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "660": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/kitchen-sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b968f84035f321a06a890e428665e1ee",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "730": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 15.78,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 10.78,
      "pid": 453
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 1650": {
      "dec": "1.0%",
      "enc": "0.0%",
      "gpu": "99.0%",
      "mem": "11.56%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 441
    },
    "recording": {
      "pid": 443
    }
  },
  "service": {
    "last_updated": 1712775981,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 61.7,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 2.3
      },
      "/media/frigate/clips": {
        "free": 18249827.8,
        "mount_type": "fuse.mergerfs",
        "total": 37844369.3,
        "used": 17687089.1
      },
      "/media/frigate/recordings": {
        "free": 18249827.8,
        "mount_type": "fuse.mergerfs",
        "total": 37844369.3,
        "used": 17687089.1
      },
      "/tmp/cache": {
        "free": 949.1,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 4.6
      }
    },
    "temperatures": {

    },
    "uptime": 39,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

My docker compose:
```yaml
#version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #image: blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:stable
    network_mode: bridge
    #network_mode: host
    cap_add:
      - CAP_PERFMON
    #runtime: nvidia
    shm_size: 64mb # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /apps/docker/frigate/spaghettinet_edgetpu_l_compiled.tflite:/config/spaghettinet_edgetpu_l_compiled.tflite:ro
      - /apps/docker/frigate/config.yml:/config/config.yml
      - /apps/docker/frigate/config/:/config
      - /mnt/storage/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935 # RTMP feeds
      - 8554:8554 #go2rtc stream
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: 6675636b00
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
```
edit: another interesting side effect of running it on the host network mode is that loading the streams in home assistant is instant now. Previously, it would take 5-10 seconds to start. This may ultimately be a non-issue and better for me in the host network configuration, but it seems like this is not how it should behave in bridge mode.
