### DISCUSSION TITLE
Telegram integration

### DISCUSSION THREAD

**Discussion by maxdd** [blakeblackshear/frigate#10932] [Ideas]
Hello,
I was looking for the possibility to integrate frigate events and streaming links with telegram.
I honestly would like to avoid Home Automation simply because i'm not using it extensively to justitfy its deployment.
I was wondering whether, given it is just a chat_id and a bot_token, the integration can be directly implemented here.
If not, i was planning to setup an http api to telegram sender, in that case would it make sense to send out an event api request every 1/2m to check whether there was a new event and reconstruct the url to snapshots/record?

**Comment by NickM-27** [comment]
Personally, I'd imagine frigate will just implement notifications directly. Supporting each service is a lot to provide to users and will bring even more requests of "use this service too"

There are many options besides home assistant like node red or even a simple local script to handle this via MQTT.

**Reply by maxdd** [reply]
> "will just implement notifications directly" 

is MQTT the go to "direct notification"?

**Reply by NickM-27** [reply]
By notifications directly I mean frigate sending notifications itself, that is not currently implemented

**Reply by maxdd** [reply]
I will play around to see whether i can implement a telegram service and maybe make a pull request
Am i wrong in thinking that the class Dispatcher is the one entitled to provide to the different services the payload to be sent?

**Reply by NickM-27** [reply]
> I will play around to see whether i can implement a telegram service and maybe make a pull request

like I said, I don't know that we will want this to be supported directly. Users will request more notification services be built in and I don't know that we want to maintain the integrations and support users setting things like telegram up. I would rather implement browser notifications directly

**Reply by maxdd** [reply]
I integrated a decent implementation (not async though, but it can be done if needed) of telegram which sends the snapshots and a caption with the url of the video, the implementation expects a configuration as such

```
telegram:
  enabled: True
  bot_token: redacted
  bot_chatID: redacted
  host: 'http://192.168.1.52:5000' # to get direct link of event/clip in the caption of the photo
  topics:
  - events # send notification when events payload is dispatched
  zones:
  - zone_0 # send notification when zone is zone_0
  time_range: '21:00,06:30' # (start,end) send notification only in this window e.g. now >= start or now <= end
```

If  you feel like it could make sense to have a look let me know
