### DISCUSSION TITLE
[Config Support]: Snapshot every X Seconds.

### DISCUSSION THREAD

**Discussion by CodingEmil** [blakeblackshear/frigate#10948] [Config Support]
### Describe the problem you are having

Hello Guys,
is there any way to create a Picture/Snapshot every few seconds? I want to create a timelaps, but I don't what to record the whole time and then cut it down...
I couldn't find anything about intervals for Snapshots.
Greetings. 

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: false
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
cameras:
  growbox:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://10.0.50.152:8554/Cam?mp4
          roles:
            - detect
            - record
            - rtmp # <- deprecated, recommend using restream instead
    snapshots:
      enabled: True
```

### Relevant log output

```shell
None
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)
