### DISCUSSION TITLE
[Detector Support]: Frigate Fails to Start, TensorRT w-Tesla P4

### DISCUSSION THREAD

**Discussion by DayRunner131** [blakeblackshear/frigate#10941] [Detector Support]
### Describe the problem you are having

During container start, Frigate fails to start after WebRTC port load. Error logs not enough to diagnose source of issues.

### Version

frigate:stable-tensorrt

### Frigate config file

```yaml
#mqtt:
#  host: 192.168.1.6
#  user: MQTT
#  password: XXXXX
detectors:
  tensorrt:
    type: tensorrt
model:
  path: /config/model_cache/tensorrt/yolov7-tiny-288.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 288
  height: 288
go2rtc:
  streams:
    driveway:
      - "ffmpeg:https://192.168.1.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXX&password=XXXX#video=copy#audio=copy#audio=opus"
    backyard_north:
      - "ffmpeg:https://192.168.1.202/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXX&password=XXXX#video=copy#audio=copy#audio=opus"
    front_door:
      - "ffmpeg:https://192.168.1.204/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXX&password=XXXX#video=copy#audio=copy#audio=opus"
cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs: 
        path: rtsp://127.0.0.1:8554/driveway
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect
    detect:
      ##Original##
#      width: 896
#      height: 672
      ##Scaled Down##
#      width: 1280
#      height: 984
      ##High Res##
      width: 2560
      height: 1920
      fps: 6
    objects:
      track:
        - person
        - car
        - bus
        - bicycle
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - driveway_entrance
          - property
        pre_capture: 10
        post_capture: 15
    zones:
      driveway_parking:
        ##Original##
#        coordinates: 478,672,649,672,896,395,386,145,134,233
        ##Scaled Down##
#        coordinates: 685,984,935,984,1259,584,643,262,227,392
        ##High Res##
        coordinates: 1121,420,2507,1137,1950,1920,1339,1920,315,638
      driveway_entrance:
        ##Original##
#        coordinates: 75,151,289,93,362,133,124,213
        ##Scaled Down##
#        coordinates: 112,239,429,152,586,222,207,358
        ##High Res##
        coordinates: 848,297,1110,404,291,622,171,454
        objects:
          - car
          - motorcycle
          - bicycle
      property:
        ##Original##
#        coordinates: 0,672,734,672,896,427,896,302,406,70,0,171
        ##Scaled Down##
#        coordinates: 1280,456,1280,623,1049,984,0,984,0,296,646,126
        ##High Res##
        coordinates: 0,1920,2058,1920,2560,1223,2560,874,1208,221,0,517
        objects:
          - person
          - dog
    snapshots:
      enabled: True
  backyard_north: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs: 
        path: rtsp://127.0.0.1:8554/backyard_north
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect
    detect:
      ##Original##
#      width: 896
#      height: 672
      ##Scaled Down##
#      width: 1280
#      height: 984
      ##High Res##
      width: 2560
      height: 1920
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask: 436,158,315,222,290,79,356,60
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - deck
          - backyard_northeast
        pre_capture: 10
        post_capture: 15
    zones:
      deck:
        coordinates: 318,984,717,984,861,984,924,851,929,547,933,480,816,344,452,294,235,392,0,671
        objects:
          - person
      backyard_northeast:
        coordinates: 0,671,305,984,1280,984,1280,0,445,0,0,462
        objects:
          - person
          - dog
          - cat
    snapshots:
      enabled: True
  front_door:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs: 
        path: rtsp://127.0.0.1:8554/front_door
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect
    detect:
      ##Original##
#      width: 640
#      height: 480
      ##High Res##
      width: 1920 
      height: 1080 
      fps: 6
    objects:
      track:
        - person
        - car
        - bus
        - bicycle
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - front_yard
          - walkway
        pre_capture: 10
        post_capture: 15
    zones:
      front_yard:
        ##Original##
#        coordinates: 640,480,640,307,526,313,444,315,352,316,198,310,85,299,0,321,0,480
        ##High Res##
        coordinates: 0,1080,0,744,267,645,1086,658,1920,872,1920,1080
        objects:
          - person
          - dog
          - cat
      walkway:
        ##Original##
#        coordinates: 454,480,281,480,338,318,376,317
        ##High Res##
        coordinates: 1595,1080,844,650,760,650,613,1080
        objects:
          - person
#      property:
#        coordinates: 0,672,734,672,896,427,896,302,406,70,0,171
#        objects:
#          - person
#          - dog
    snapshots:
      enabled: True
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    runtime: nvidia
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidiacaps:/dev/nvidiacaps
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    environment:    
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - YOLO_MODELS=yolov7-tiny-288
      - USE_FP16=false
 #     - FRIGATE_RTSP_PASSWORD=FrigateOne
    command: nvidia-smi
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/frigate/storage:/media/frigate
      - /home/frigate/config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
No models to convert.
s6-rc: info: service trt-model-prepare successfully started
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-04-11 15:23:10.582036942  [INFO] Preparing Frigate...
2024-04-11 15:23:10.583935887  [INFO] Preparing new go2rtc config...
2024-04-11 15:23:10.584094057  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2024-04-11 15:23:10.596171948  [INFO] Starting Frigate...
Thu Apr 11 15:23:10 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P4                       Off |   00000000:01:00.0 Off |                  Off |
| N/A   31C    P0             22W /   75W |       0MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
2024-04-11 15:23:10.836903316  [INFO] Starting go2rtc...
2024-04-11 15:23:10.911931320  15:23:10.911 INF go2rtc version 1.8.4 linux/amd64
2024-04-11 15:23:10.912356800  15:23:10.912 INF [rtsp] listen addr=:8554
2024-04-11 15:23:10.913049582  15:23:10.912 INF [webrtc] listen addr=:8555
2024-04-11 15:23:10.913090253  15:23:10.913 INF [api] listen addr=:1984
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-04-11 15:23:11.094134404  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-04-11 15:23:11.163143040  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2024-04-11 15:23:11.173297201  [INFO] Service Frigate exited with code 256 (by signal 15)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service trt-model-prepare: stopping
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-04-11 15:23:11.175561123  exit with signal: terminated
s6-rc: info: service trt-model-prepare successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-04-11 15:23:11.180610744  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Running in Proxmox Ubuntu v22.04 LXC with GPU passthrough.
