### DISCUSSION TITLE
I want to record (and be alerted) only when someone walks up to the door, not walks away from the door ?

### DISCUSSION THREAD

**Discussion by vw-kombi** [blakeblackshear/frigate#10950] [Config Support] [answered]
### Describe the problem you are having

I have a sort of a door bell system where with home assistant, the google homes in the lounge say "somebody at the door' and the google display shows the front door cam (and also an alert on my phone in case I am out).  This is all working but I read that I may be able to make it more 'smart' by knowing when someone is coming up the path to the door, vs someone leaving the front door and walking down the path.

I currently have it all as one zone which is not required I guess.  But If I had a zone for the front door area, and a zone for the pathway, can I then get home assistant to do its stuff based on the movement from the path to the door, rather than anywhere ?
 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.30.249:5005/api/config/schema.json

database:
  path: /config/frigate.db

mqtt:
  host: core-mosquitto
  topic_prefix: frigate
  user: MQTT
  password: connect

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  Side-Cam:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://foscam:nope@10.10.10.16:88/videoSub   # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
        - rtmp
      - path: rtsp://foscam:nope@10.10.10.16:88/videoMain   # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
        - doorway
        retain:
          default: 7
          mode: motion
    snapshots:
      enabled: true
      required_zones:
      - doorway
      bounding_box: true
      timestamp: true
      retain:
        default: 7
    motion:
      mask:
      - 0,39,173,38,333,33,333,0,0,0
      - 1210,520,1185,390,1188,344,1108,338,1103,203,942,218,572,134,515,113,0,115,0,60,343,66,343,0,1229,0,1280,0,1280,720,1194,720
#     threshold: 30
#     contour_area: 10
#     lightning_threshold: 0.8
    zones:
      doorway:
        coordinates: 
          0,720,1189,720,1198,515,1207,437,1168,399,1168,354,1113,353,1110,202,691,135,187,69,0,75
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
