### DISCUSSION TITLE
[Config Support]: config.yml

### DISCUSSION THREAD

**Discussion by thesebastianf** [blakeblackshear/frigate#10959] [Config Support] [answered]
### Describe the problem you are having

Hey I just upgraded from a pretty old version to latest.
I read that now I had to change the the compose file to mount the full config dir.
I did this .. however I cant get it to run but see:
```
2024-04-12 17:21:32.849533544  [INFO] Preparing Frigate...
2024-04-12 17:21:32.849585420  [ERROR] Frigate config file not found

```

compose excerpt:
```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config

```

the directory config does exist and contains the config.yml

I just cant find my error :-/

### Version

latest

### Frigate config file

```yaml
x
```

### Relevant log output

```shell
2024-04-12 17:21:32.849533544  [INFO] Preparing Frigate...
2024-04-12 17:21:32.849585420  [ERROR] Frigate config file not found
```

### Operating system

Ubuntu

### Install method

Ubuntu / Docker

### Coral version

USB

**Comment by NickM-27** [comment]
typically it is best to avoid relative paths and use absolute paths in the docker compose file

**Reply by thesebastianf** [reply]
I also tried the absolute path. Same result.

**Reply by NickM-27** [reply]
Then you should show that updated config as well as the path to the docker compose and where you are running the command

**Reply by thesebastianf** [reply]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/acc1/DATA/DOCKER/compose/frigate/config/:/config
      - /home/acc1/DATA/FRIGATEMEDIA_SDB250GB:/media/frigate


      - type: tmpfs # Optional: 2GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"        
```
