### DISCUSSION TITLE
[Config Support]: Adding Timestamp to Camera Feed with go2rtc

### DISCUSSION THREAD

**Discussion by MeeperBeeper** [blakeblackshear/frigate#10951] [Config Support] [answered]
### Describe the problem you are having

I'm trying to add a timestamp to the video feed from a camera that can't support it.  Well, to be honest it's a RPi Zero 2W with MotionEye that struggles to keep up unless you use the Fast Network Camera option that unfortunately disables all ability to add a timestamp to the video.

Anyway, I'm aware about the CPU hit I'm going to take on the Frigate system but I'm still looking to add the timestamp to the video feed.  My problem is that I can't get the config to actually work.  I'm not familiar enough with Frigate and go2rtc to take the snippets of config and convert it to the actual config that I enter.

Everything else in the config works, including routing the video feed through go2rtc.  According to [Configuring go2rtc | Frigate](https://docs.frigate.video/guides/configuring_go2rtc) I should be able to add parameters as necessary to the Frigate config and according to the [go2rtc Readme](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg) I should just be able to add the line but I can't quite figure out the pieces.  So far all attempts to make it work have failed with either no action and no timestamp added, or where go2rtc fails to start and Frigate doesn't receive any frames.

The config I've included in full is the latest attempt, this resulted in the feed working without the timestamp.  I've also attempted sections like the following without success:

```
go2rtc:
  ffmpeg:
    drawtext: x=2:y=2:fontsize=12:fontcolor=white:box=1:boxcolor=black
```

and

```
go2rtc:
  streams:
    front_door:
      - rtsp://user:mypass@meye-cam.local:554/h264#drawtext=x=2:y=2:fontsize=12:fontcolor=white:box=1:boxcolor=black
```

There was even one that somehow added a -vf but I didn't understand it either.

While I thought go2rtc would be the place to put it, it's really needed in what's recorded for motion detection because as it stands right now, it seems to record small snippets within the hour and when you play it back it rams all the bits together into a single video.  While this is fine, there's no way to piece together which snipped happened when during that hour.  So either a go2rtc solution or an on-record solution would work.

As I'm filling out this post, I saw in the api/stats what looks like a command line look at what's being entered and it even has the timestamp being added somewhere but I'm certainly not seeing it anywhere in any of the places I can see it. 

So anybody know how to fit these pieces together to get a timestamp to show up on the feed?  Other discussion questions I've come across didn't seem to provide the final answer as to what it's supposed to look like so I'm kinda stuck.

Thanks,
Meep.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: False

go2rtc:
  rtsp:
    username: "viewer"
    password: "mypass"
  streams:
    front_door:
      - rtsp://user:mypass@meye-cam.local:554/h264
      - "ffmpeg:front_door#drawtext=x=2:y=2:fontsize=12:fontcolor=white:box=1:boxcolor=black"

birdseye:
  enabled: true
  mode: continuous

record:
  enabled: true
  retain:
     days: 7
     mode: motion

cameras:
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
```

### Relevant log output

```shell
Nothing useful that I can see.
```

### Frigate stats

```json
{
  "cameras": {
    "front_door": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 0,
      "capture_pid": 253,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 1551,
      "pid": 252,
      "process_fps": 0,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "79": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "1.7",
      "cpu_average": "1",
      "mem": "1.2"
    },
    "100": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "4.7"
    },
    "116": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "117": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "137": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "138": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "139": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "221": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "2.6"
    },
    "235": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "2.8"
    },
    "243": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(38)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "244": {
      "cmdline": "frigate.detector.cpu ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "3.0"
    },
    "245": {
      "cmdline": "frigate.output       ",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "2.9"
    },
    "250": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "251": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "252": {
      "cmdline": "frigate.process:front_door",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "3.0"
    },
    "253": {
      "cmdline": "frigate.capture:front_door",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "2.9"
    },
    "1534": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "1562": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/front_door?video&audio -c copy -vf drawtext=x=2:y=2:fontsize=12:fontcolor=white:box=1:boxcolor=black:text='%{localtime\\:%Y-%m-%d %X}' -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/d374aa409502368b1095176e01c940ff",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "cpu": {
      "detection_start": 0,
      "inference_speed": 10,
      "pid": 244
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 90
    },
    "logger": {
      "pid": 221
    },
    "recording": {
      "pid": 235
    }
  },
  "service": {
    "last_updated": 1712892322,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 63.3,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 0.7
      },
      "/media/frigate/clips": {
        "free": 71211.4,
        "mount_type": "ext4",
        "total": 99257,
        "used": 22958.5
      },
      "/media/frigate/recordings": {
        "free": 71211.4,
        "mount_type": "ext4",
        "total": 99257,
        "used": 22958.5
      },
      "/tmp/cache": {
        "free": 953.7,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 0
      }
    },
    "temperatures": {},
    "uptime": 1262,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I doubt it'll be useful but this is a trial but Frigate is currently running in Docker running in Virtualbox.  There is no GPU or Coral support.  There is also no HA or MQTT integration (or any integration) currently setup nor desired at this time.  I'm just trying to get it to work with a single camera as a proof of concept first before I go hog wild.

**Comment by NickM-27** [comment, marked as answer]
you can't just set `#drawtext` you need to set `#video=h264` so it is clear that you want the video to be re encoded

**Reply by MeeperBeeper** [reply]
Alright, I've updated that config section to what is below.  Still no dice.

```
go2rtc:
  rtsp:
    username: "viewer"
    password: "mypass"
  streams:
    front_door:
      - rtsp://user:mypass@meye-cam.local:554/h264
      - "ffmpeg:front_door#video=h264#drawtext=x=2:y=2:fontsize=12:fontcolor=white:box=1:boxcolor=black"
```

**Reply by NickM-27** [reply]
You can't include the default stream in the same list, that first stream satisfies the requirements so ffmpeg is never run

**Reply by MeeperBeeper** [reply]
And I finally have a timestamp!

For the next person, the final config was this:
```
go2rtc:
  rtsp:
    username: "viewer"
    password: "mypass"
  streams:
    front_door:
      - "ffmpeg:rtsp://user:mypass@meye-cam.local:554/h264#video=h264#drawtext=x=2:y=2:fontsize=12:fontcolor=white:box=1:boxcolor=black"
```

That said, it looks like the documentation might need a few tweaks.  It clearly had the ffmpeg:camName#params setup and rtsp URL on a separate line when talking about adding #video and #audio params here:
https://docs.frigate.video/guides/configuring_go2rtc

Thanks for the help Nick!
