### DISCUSSION TITLE
[Config Support]:  Help with scaling frigate.yaml file structure

### DISCUSSION THREAD

**Discussion by jerryac** [blakeblackshear/frigate#10960] [Config Support]
### Describe the problem you are having

I finally have Frigate running with Home Assistant as and add on with TPU and hardware accel working. 
Currently only have a single camera added and now want to add in my other 5 cams and start building out detection and notifications. 

Looking for some guidance as how to best approach adding and properly structuring the frigate.yaml file as to not break it but also make it logical for scaling out in the future.   Any guidance or examples would be appreciated. 

### Version

.13.2

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg: 
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy


go2rtc:
  streams:
    rear_sw_main:
      - ffmpeg:rtsp://frigate:password@192.168.129.6:554/h264Preview_01_main#video=h265#audio=copy#audio=opus
      - ffmpeg:rear_sw_main#audio=opus
    rear_sw_sub:
      - ffmpeg:rtsp://frigate:password@192.168.129.6:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
      - ffmpeg:rear_sw_sub#audio=opus

cameras:
  rear_sw:
    ui:
      order: 1
    birdseye:
      order: 1
    detect:
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_sw_main?video=copy&audio=copy
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear_sw_sub?video=copy&audio=copy
          roles:
            - detect
    live:
      stream_name: rear_sw_main
snapshots:
  enabled: true
  bounding_box: true
  clean_copy: true
  retain:
    default: 15
record:
  enabled: false
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 15
birdseye:
  enabled: true
  mode: continuous
```

### Relevant log output

```shell
ffprobe does not run.. just spins forever when i try to grab any output from it.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Any other information that may be helpful

Still see slow load times and buffering on my single camera added and high cpu spikes at times.   Curious if there is some optimization opportunities in my config I'm over looking
