### DISCUSSION TITLE
[Config Support]: Adding Object Masks I don't see the options for Car just people and Object_0

### DISCUSSION THREAD

**Discussion by bcodermicro** [blakeblackshear/frigate#10973] [Config Support]
### Describe the problem you are having

So when I go to the UI and add an object mask I only get object_0   person is there by default. I can't seem to add one for cars and such.

https://imgur.com/SOCozwf

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: XXX
  password: 'XXX'

database:
  path: /config/frigate.db

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    tvroom:
    - rtsp://XXX:XXX@XXX.xxxXXX:554/h264Preview_01_main
    tvroomsub:
    - rtsp://XXX:XXX@XXX.xxxXXX/h264Preview_01_sub
    housefront:
    - rtsp://XXX:XXX@XXX.xxxXXX/h264Preview_01_main
    housefrontsub:
    - rtsp://XXX:XXX@XXX.xxxXXX/h264Preview_01_sub




cameras:
  tvroom:
    enabled: true
    ffmpeg:
      hwaccel_args: -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/tvroomsub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tvroom
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: tvroom

    snapshots: # <----- Enable snapshots
      enabled: true
    detect:
      enabled: false
      width: 1280 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution

    motion:
      mask:
      - 0,667,0,720,446,720,454,660

  housefront:
    enabled: true
    ffmpeg:
      hwaccel_args: -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/housefrontsub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/housefront
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: tvroom

    snapshots: # <----- Enable snapshots
      enabled: true
    detect:
      enabled: false
      width: 1280 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution

    motion:
      mask:
      - 0,667,0,720,311,720,539,720,842,720,838,661
      - 544,0,257,80,0,199,0,0
      - 1280,89,1280,0,1007,0
    objects:
      filters:
        object_0:
          mask:
          - 0,466,0,227,74,197,214,369
          - 857,720,301,720,239,542,415,461
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 2
        car: 7
        person: 7
```

### Relevant log output

```shell
Everything appears to be running fine...request for specific logs I can post....
```

### Frigate stats

```json
{"cameras":{"housefront":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":320,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":15802,"pid":315,"process_fps":5.0,"skipped_fps":0.0},"tvroom":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":318,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":15803,"pid":314,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"3.1","cpu_average":"3","mem":"0.2"},"98":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"108":{"cmdline":"python3 -u -m frigate","cpu":"0.7","cpu_average":"0","mem":"1.3"},"120":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"158":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"168":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"296":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"298":{"cmdline":"frigate.recording_manager","cpu":"1.1","cpu_average":"1","mem":"0.8"},"307":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"308":{"cmdline":"frigate.detector.ov  ","cpu":"0.1","cpu_average":"0","mem":"2.8"},"310":{"cmdline":"frigate.output       ","cpu":"0.4","cpu_average":"0","mem":"0.8"},"314":{"cmdline":"frigate.process:tvroom","cpu":"0.2","cpu_average":"0","mem":"0.7"},"315":{"cmdline":"frigate.process:housefront","cpu":"0.2","cpu_average":"0","mem":"0.7"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"318":{"cmdline":"frigate.capture:tvroom","cpu":"0.9","cpu_average":"0","mem":"0.7"},"320":{"cmdline":"frigate.capture:housefront","cpu":"1.0","cpu_average":"0","mem":"0.7"},"323":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"327":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"15802":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/housefrontsub -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.0","cpu_average":"2","mem":"0.3"},"15803":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/tvroomsub -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.6","cpu_average":"1","mem":"0.3"},"15806":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/housefront -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/housefront@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.2"},"15807":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/tvroom -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/tvroom@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.1"},"27860":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"ov":{"detection_start":0.0,"inference_speed":10.0,"pid":308}},"gpu_usages":{"intel-vaapi":{"gpu":"0.15%","mem":"-%"}},"processes":{"go2rtc":{"pid":88},"logger":{"pid":296},"recording":{"pid":298}},"service":{"last_updated":1713113144,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":124.5,"mount_type":"tmpfs","total":128.0,"used":3.5},"/media/frigate/clips":{"free":429774.5,"mount_type":"ext4","total":468359.8,"used":14722.4},"/media/frigate/recordings":{"free":429774.5,"mount_type":"ext4","total":468359.8,"used":14722.4},"/tmp/cache":{"free":947.7,"mount_type":"tmpfs","total":953.7,"used":6.0}},"temperatures":{},"uptime":15818,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

https://imgur.com/SOCozwf
