### DISCUSSION TITLE
[Support]: Allowing a multi lense camera to detect from all lenses at once

### DISCUSSION THREAD

**Discussion by Dvalin21** [blakeblackshear/frigate#10970] [General Support]
### Describe the problem you are having

So I have the [LS Vision LS-WL342-20X](https://www.aliexpress.us/item/3256806130228028.html?spm=a2g0o.order_list.order_list_main.16.57461802yAYV76&gatewayAdapt=glo2usa). The camera has three lenses with one that is ptz. Right now I have only been able to get them to show up if I add each lens if I add them as separate cameras. Which Frigate freaks out . You can see the stream, but frigate shows the in its entirety as being disconnected. I think this comes from the fact its on the same ip address, but different urls. 

example  rtsp://username:password@20.0.0.25:544/live0_0.sdp   #live0_0.sdp is the ptz, 1_0.sdp is first stationary, and 2_0.sdp is the second stationary. 

What I would like to be able to do  is which ever one that receives a detection, then that url would record. Only one would truly have audio as the mic is on the ptz part. The camera is onvif, but not truly sure if the onvif would work with this model. if autotracking worked, it would be awesome to have any of the stationary lens to detect and have the ptz turn to autotrack. However this might be wishful thinking. Anyway, any help would be appreciated. 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ui:
  timezone: America/Chicago

telemetry:
  version_check: True
  network_interfaces: []
  stats:
    network_bandwidth: True

#####Detector#########
detectors:
  coral:
    type: edgetpu
    device: pci:0
#######Birdseye View###
birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  quality: 1
  mode: continuous
#######################

#######MQTT Event######
mqtt:
  enabled: True
  host: 10.0.0.5
  topic_prefix: frigate
  client_id: frigate

#######################

database:
  path: /config/frigate.db

logger:
  default: info
  logs:
    frigate.event: debug

#######Global Camera Settings#######
live:
  height: 1440
  quality: 1

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  retain:
    default: 10
    objects:
      person: 8

record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  events:
    pre_capture: 20
    post_capture: 20
    retain:
      default: 7
      mode: active_objects

audio: # <- enable audio events for all camera
  enabled: True
  listen:
    - scream
    - speech
    - yell
    - gunshot
    - machine_gun

###########
go2rtc:
  log:
    format: text
    exec: trace
  streams:
    backyard:
      - rtsp://username:password@10.0.0.239:554/554/live0_0.sdp #onvif/device_service 
      - "ffmpeg:backyard#audio=aac"
    backyard_sub:
      - rtsp://username:password@10.0.0.239:554/live1_0.sdp
      - "ffmpeg:backyard#audio=aac"
#    backyard_sub2:
#      - rtsp://username:password@10.0.0.239:554/live2_0.sdp
#      - "ffmpeg:backyard#audio=aac"
    storage_room:
      - rtsp://username:password@10.0.0.235:554/user=admin_password=1bpcecDK_channel=0_stream=0&onvif=0.sdp?real_stream
      - "ffmpeg:storage_room#video=h264#hardware#audio=aac"
#    storage_room_sub:
#      - rtsp://username:password@10.0.0.235:554/user=admin_password=1bpcecDK_channel=0_stream=1&onvif=0.sdp?real_stream
#      - "ffmpeg:storage_room#video=h264#audio=aac"
    front_door:
      - rtsp://username:password@10.0.0.237:554/user=admin_password=1bpcecDK_channel=0_stream=0&onvif=0.sdp?real_stream
      - "ffmpeg:front_door#video=h264#hardware#audio=aac"
#    front_door_sub:
#      - rtsp://username:password7@10.0.0.237:554/user=admin_password=1bpcecDK_channel=0_stream=1&onvif=0.sdp?real_stream
#      - "ffmpeg:front_door#video=h264#audio=aac"
    bedroom:
      - rtsps://username:password@10.0.0.238:554/user=admin_password=1bpcecDK_channel=0_stream=0&onvif=0.sdp?real_stream
      - "ffmpeg:bedroom#video=h264#hardware#audio=aac"
#    bedroom_sub:
#      - rtsp://username:password@10.0.0.238:554/user=admin_password=1bpcecDK_channel=0_stream=1&onvif=0.sdp?real_stream
#      - "ffmpeg:bedroom#video=h264#audio=aac"
    back_room:
      - rtsps://username:password@10.0.0.234:88/videoMain
      - "ffmpeg:storage_room#audio=aac"
  webrtc:
    candidates:
      - 10.0.0.29:8555
      - stun:8555

############ Cameras!!!##############
######Storage Room Camera!!##########
cameras:
  storage_room:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/storage_room
          input_args: preset-rtsp-generic #preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
            - audio
#        - path: rtsp://127.0.0.1:8554/storage_room_sub
#          input_args: preset-rtsp-generic #preset-rtsp-restream-low-latency
#          roles:

    detect:
      width: 2560
      height: 1440
      fps: 12
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.77
          threshold: 0.75
#          mask:
#            - 1920,187,1920,0,0,0,0,192,1920,191
    birdseye:
      enabled: True
    onvif:
      host: 10.0.0.235
      port: 8899
      user: admin
      password: Leah0527
    ui:
      order: 1
#######Front Door Camera#####
  front_door:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
            - audio
#        - path: rtsp://127.0.0.1:8554/front_door_sub
#          input_args: preset-rtsp-generic
#          roles:
#            - audio
    detect:
      width: 2560
      height: 1440
      fps: 12
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.77
          threshold: 0.75
#          mask:
#            - 1920,253,1920,166,1920,89,1920,0,0,0,0,303
    birdseye:
      enabled: True
    onvif:
      host: 10.0.0.237
      port: 8899
      user: admin
      password: Leah0527
    ui:
      order: 2
#######Back Yard Camera#####
  backyard:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-generic
          roles:
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 15
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.77
          threshold: 0.75
    onvif:
      host: 10.0.0.239
      port: 8080
      user: admin
      password: Leah0527
    birdseye:
      enabled: True
    ui:
      order: 3

#####Bedroom Camaera#######
  bedroom:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
            - audio
#        - path: rtsp://127.0.0.1:8554/bedroom_sub
#          input_args: preset-rtsp-generic
#          roles:

    detect:
      width: 3632
      height: 1080
      fps: 12
    objects:
      track:
        - person
        - airplane
      filters:
        person:
          min_score: 0.77
          threshold: 0.75
#          mask:
#            - 1019,274,857,441,804,240
        airplane:
          min_score: 0.80
          threshold: 0.75
#          mask:
#            - 1019,274,857,441,804,240
    birdseye:
      enabled: True
    ui:
      order: 6
#######Back Room######
  back_room:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/back_room
          input_args: preset-rtsp-generic
          roles:
            - detect
            - audio
            - record
    detect:
      width: 2560
      height: 1440
      fps: 10
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.77
          threshold: 0.75
    birdseye:
      enabled: True
    onvif:
      host: 10.0.0.234
      port: 888
      user: keith
      password: Leah0527
    ui:
      order: 7
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{"back_room":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:59088","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 MPEG4-GENERIC/8000\r\na=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=0\r\n","send":1467179,"senders":["96 MPEG4-GENERIC/8000, bytes=1443851, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/back_room","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"}],"producers":[{"url":"rtsps://*:*@10.0.0.234:88/videoMain"},{"medias":["audio, recvonly, MPEG4-GENERIC/8000"],"receivers":["96 MPEG4-GENERIC/8000, bytes=1443851, senders=1"],"recv":1463391,"remote_addr":"127.0.0.1:59098","sdp":"v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.8.5\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=audio 0 RTP/AVP 96\r\nb=AS:48\r\na=rtpmap:96 MPEG4-GENERIC/8000/1\r\na=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:streamid=0\r\n","type":"RTSP passive producer","url":"rtsp://127.0.0.1:8554/2210b6946753474adbf2a51bfb6f3cfe","user_agent":"ffmpeg/go2rtc"}]},"backyard":{"consumers":[{"medias":["audio, sendonly, ANY"],"remote_addr":"127.0.0.1:46312","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 PCMA/8000\r\na=control:trackID=0\r\n","send":4457520,"senders":["96 PCMA/8000, bytes=4348800, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/backyard?audio","user_agent":"go2rtc/ffmpeg"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:46242","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=J2QAKK0AzoB4AiflmoCAgPgAAAMACAAAAwDxqABTQAA+cG//4FA=,KO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n","send":21886322,"senders":["96 H264, bytes=19801232, receivers=1","97 MPEG4-GENERIC/8000, bytes=1782060, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/backyard","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:46288","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=J2QAKK0AzoB4AiflmoCAgPgAAAMACAAAAwDxqABTQAA+cG//4FA=,KO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n","send":21886322,"senders":["96 H264, bytes=19801232, receivers=1","97 MPEG4-GENERIC/8000, bytes=1782060, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/backyard","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"}],"producers":[{"medias":["video, recvonly, H.264 High 4.0","audio, recvonly, PCMA/8000"],"receivers":["96 H264, bytes=19801232, senders=2","8 PCMA/8000, bytes=4348800, senders=1"],"recv":24491576,"remote_addr":"10.0.0.239:554","sdp":"v=0\r\no=- 1713067114 1713067114 IN IP4 10.0.0.239\r\nt=0 0\r\nc=IN IP4 10.0.0.239\r\na=packetization-supported:Puwell\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=rtpmap:96 H264/90000\r\na=framerate:15\r\na=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=J2QAKK0AzoB4AiflmoCAgPgAAAMACAAAAwDxqABTQAA+cG//4FA=,KO48sA==\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=1\r\na=rtpmap:8 PCMA/8000\r\n","type":"RTSP active producer","url":"rtsp://10.0.0.239:554/live0_0.sdp","user_agent":"go2rtc/1.8.5"},{"medias":["audio, recvonly, MPEG4-GENERIC/8000"],"receivers":["96 MPEG4-GENERIC/8000, bytes=1782060, senders=2"],"recv":1802900,"remote_addr":"127.0.0.1:46324","sdp":"v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.8.5\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=audio 0 RTP/AVP 96\r\nb=AS:48\r\na=rtpmap:96 MPEG4-GENERIC/8000/1\r\na=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:streamid=0\r\n","type":"RTSP passive producer","url":"rtsp://127.0.0.1:8554/42809a5c9d52428904fc9784fe546d21","user_agent":"ffmpeg/go2rtc"}]},"backyard_sub":{"consumers":[],"producers":[{"url":"rtsp://*:*@10.0.0.239:554/live1_0.sdp"},{"url":"ffmpeg:backyard#audio=aac"}]},"bedroom":{"consumers":null,"producers":[{"url":"rtsps://*:*@10.0.0.238:554/user=admin_password=1bpcecDK_channel=0_stream=0&onvif=0.sdp?real_stream"},{"url":"ffmpeg:bedroom#video=h264#hardware#audio=aac"}]},"birdseye":{"consumers":null,"producers":[{"url":"exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -r 10 -i /tmp/cache/birdseye -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -rtsp_transport tcp -f rtsp {output}"}]},"front_door":{"consumers":[{"medias":["video, sendonly, ANY","audio, sendonly, ANY"],"remote_addr":"127.0.0.1:40528","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 PCMA/8000\r\na=control:trackID=1\r\n","send":51489317,"senders":["96 H265, bytes=46313413, receivers=1","97 PCMA/8000, bytes=4369280, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/front_door?video&audio","user_agent":"go2rtc/ffmpeg"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:46230","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n","send":48849385,"senders":["96 H265, bytes=46137067, receivers=1","97 MPEG4-GENERIC/8000, bytes=2115143, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/front_door","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:46274","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n","send":48849385,"senders":["96 H265, bytes=46135671, receivers=1","97 MPEG4-GENERIC/8000, bytes=2115143, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/front_door","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"}],"producers":[{"medias":["video, recvonly, H265","audio, recvonly, PCMA/8000"],"receivers":["98 H265, bytes=46313413, senders=3","8 PCMA/8000, bytes=4369280, senders=1"],"recv":51298125,"remote_addr":"10.0.0.237:554","sdp":"v=0\r\no=- 38990265062388 38990265062388 IN IP4 10.0.0.237\r\ns=RTSP Session\r\nt=0 0\r\na=control:*\r\na=range:npt=0-\r\nm=video 0 RTP/AVP 98\r\nc=IN IP4 10.0.0.237\r\na=rtpmap:98 H265/90000 \r\na=fmtp:98 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=framerate:25\r\na=control:trackID=3\r\nm=audio 0 RTP/AVP 8\r\nc=IN IP4 10.0.0.237\r\na=rtpmap:8 PCMA/8000\r\na=control:trackID=4\r\n","type":"RTSP active producer","url":"rtsp://10.0.0.237:554/user=admin_password=1bpcecDK_channel=0_stream=0&onvif=0.sdp/","user_agent":"go2rtc/1.8.5"},{"medias":["video, recvonly, H.264 High 4.1","audio, recvonly, MPEG4-GENERIC/8000"],"receivers":["96 H264, bytes=491417177, senders=0","97 MPEG4-GENERIC/8000, bytes=2115143, senders=2"],"recv":498049268,"remote_addr":"127.0.0.1:46322","sdp":"v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.8.5\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAKay0AUAFrQgAAAMACAAAAwDEeMGV,aO8Pyw==; profile-level-id=640029\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\nb=AS:48\r\na=rtpmap:97 MPEG4-GENERIC/8000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:streamid=1\r\n","type":"RTSP passive producer","url":"rtsp://127.0.0.1:8554/da1596c9a5e7a58a9c1b126b5e6dda5f","user_agent":"ffmpeg/go2rtc"}]},"storage_room":{"consumers":[{"medias":["audio, sendonly, ANY"],"remote_addr":"127.0.0.1:59080","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 PCMA/8000\r\na=control:trackID=0\r\n","send":3138912,"senders":["96 PCMA/8000, bytes=2989440, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/storage_room?audio","user_agent":"go2rtc/ffmpeg"},{"medias":["video, sendonly, ANY","audio, sendonly, ANY"],"remote_addr":"127.0.0.1:59108","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 PCMA/8000\r\na=control:trackID=1\r\n","send":38686466,"senders":["96 H265, bytes=35122642, receivers=1","97 PCMA/8000, bytes=2972800, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/storage_room?video&audio","user_agent":"go2rtc/ffmpeg"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:59122","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n","send":36610051,"senders":["96 H265, bytes=34773601, receivers=1","97 MPEG4-GENERIC/8000, bytes=1377766, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/storage_room","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:47972","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n","send":32444348,"senders":["96 H265, bytes=30738076, receivers=1","97 MPEG4-GENERIC/8000, bytes=1296080, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/storage_room","user_agent":"FFmpeg Frigate/0.13.2-6476f8a"}],"producers":[{"medias":["video, recvonly, H265","audio, recvonly, PCMA/8000"],"receivers":["8 PCMA/8000, bytes=2989440, senders=2","98 H265, bytes=35122642, senders=3"],"recv":38562310,"remote_addr":"10.0.0.235:554","sdp":"v=0\r\no=- 38990265062388 38990265062388 IN IP4 10.0.0.235\r\ns=RTSP Session\r\nt=0 0\r\na=control:*\r\na=range:npt=0-\r\nm=video 0 RTP/AVP 98\r\nc=IN IP4 10.0.0.235\r\na=rtpmap:98 H265/90000 \r\na=fmtp:98 profile-id=010101;sprop-pps=RAHAcvAbJA==;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABQCAFof4qtO6JLuVlhCLAgBEqiADN/mAE;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;\r\na=framerate:25\r\na=control:trackID=3\r\nm=audio 0 RTP/AVP 8\r\nc=IN IP4 10.0.0.235\r\na=rtpmap:8 PCMA/8000\r\na=control:trackID=4\r\n","type":"RTSP active producer","url":"rtsp://10.0.0.235:554/user=admin_password=1bpcecDK_channel=0_stream=0&onvif=0.sdp/","user_agent":"go2rtc/1.8.5"},{"medias":["video, recvonly, H.264 High 4.1","audio, recvonly, MPEG4-GENERIC/8000"],"receivers":["96 H264, bytes=315336675, senders=0","97 MPEG4-GENERIC/8000, bytes=1383770, senders=3"],"recv":319620037,"remote_addr":"127.0.0.1:59118","sdp":"v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.8.5\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAKay0AUAFrQgAAAMACAAAAwDEeMGV,aO8Pyw==; profile-level-id=640029\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\nb=AS:48\r\na=rtpmap:97 MPEG4-GENERIC/8000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:streamid=1\r\n","type":"RTSP passive producer","url":"rtsp://127.0.0.1:8554/0bc398fa9a2cd9ff0b0ad018f6635a90","user_agent":"ffmpeg/go2rtc"}]}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wireless

### Camera make and model

LS Vision LS-WL342-20X
