### DISCUSSION TITLE
[Support]: Trying to add Object Mask for parked cars... only get object_0

### DISCUSSION THREAD

**Discussion by bcodermicro** [blakeblackshear/frigate#10971] [General Support]
### Describe the problem you are having

I'm sure I'm doing this wrong but when I use the UI to add object masks the only thing I get is object_0. I want to be able to add a car object mask so that my parked cars are ignored..

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
objects:
  filters:
    person:
      mask:
ADD TO PERSON
    object_0:
      mask:
       -
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reoline CX410
