### DISCUSSION TITLE
[Config Support]: Help with motion/PTZ using lightning threshold

### DISCUSSION THREAD

**Discussion by tamueller** [blakeblackshear/frigate#10983] [Config Support]
### Describe the problem you are having

Hi,
I'm having trouble with PTZ and motion detection. I tried to reduce the lightning threshold to 30 but still get a lot of motion, as shown in this video:
https://github.com/blakeblackshear/frigate/assets/1902960/8b4daaa7-e1a1-4c37-9a03-9871034e1bd9

Is this expected, or is there something wrong with my config?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 50
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.3
```

### Relevant log output

```shell
See video
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
