### DISCUSSION TITLE
[Config Support]: MQTT Events for one object in one camera in one zone

### DISCUSSION THREAD

**Discussion by mbronstein1** [blakeblackshear/frigate#10985] [Config Support]
### Describe the problem you are having

I am trying to detect cars inside of a single zone inside one camera. I don't need to pass car in the global objects to be tracked since I only want to detect cars in this camera. In my config's current state, I am not detecting cars at all inside the zone (or in the camera which is expected). When I set `objects->track->car` inside the specific camera (in the zone or not), an event is not created in Frigate BUT for some reason an mqtt `/event` topic is being published. I've also tried setting `mqtt -> required_zones` inside the camera config but an event is still being sent any time car is detected on the camera.

The requested camera is called `Dock_External`.

### Version

0.13.2

### Frigate config file

```yaml
go2rtc:
  webrtc:
    candidates:
    - localhost:8555
    - stun:8555
  streams:
    Dock_External_record:
    - ****
    Dock_External_detect:
    - ****
    Rear_Door_record:
    - ****
    Rear_Door_detect:
    - ****


mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true

objects:
  track:
  - person

motion:
  threshold: 80
  contour_area: 30

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 1

logger:
  default: info

cameras:
  Dock_External:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Dock_External_detect
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/Dock_External_record
        roles:
        - record
    record:
      events:
        objects:
        - car
        required_zones:
        - driveway
    snapshots:
      required_zones:
      - driveway
    zones:
      driveway:
        coordinates: 1017,557,997,720,131,720,596,417,1026,452
    live:
      stream_name: Dock_External_record
    motion:
      mask:
      - 0,0,537,0,546,286,0,457
  Rear_Door:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Rear_Door_detect
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/Rear_Door_record
        roles:
        - record
    live:
      stream_name: Rear_Door_record
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Zone in debug
<img width="973" alt="Screenshot 2024-04-15 at 10 38 07 AM" src="https://github.com/blakeblackshear/frigate/assets/77715521/9a04e858-fe34-464e-83dc-763e4b27e70b">

Proof of car mqtt event outside of zone through an mqtt subscriber app when `objects->track->car` is set within the camera.
![Screenshot 2024-04-15 at 10 38 43 AM](https://github.com/blakeblackshear/frigate/assets/77715521/a5d301bd-e7b9-4eaa-a987-dbe497801c39)
