### DISCUSSION TITLE
[HW Accel Support]: Intel N100 cannot configure properly, high CPU load

### DISCUSSION THREAD

**Discussion by SofaSurfer76** [blakeblackshear/frigate#11009] [Hardware Acceleration Support]
### Describe the problem you are having

I'm having issue running Frigate with 2 cameras, very high CPU load, I cannot see GPU stats, 

### Version

0.13.2

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.mqtt: error

mqtt:
  host: 20.20.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password: xxxxxx
  stats_interval: 300

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128

environment_vars:
  LIBVA_DRIVER_NAME: iHD

database:
  path: /db/frigate.db

record:
  expire_interval: 10

go2rtc:
  streams:
    vialetto_live:
      - rtsp://admin:xxxxxx@20.20.1.162/Preview_01_sub
    giardino_live:
      - rtsp://admin:xxxxx@20.20.1.161/h264_stream 

cameras:
  vialetto:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@20.20.1.162/Preview_01_main #rtsp://admin:xxxxxxxx@20.20.1.162:554/h265Preview_01_main  
          roles:
          - record
        - path: rtsp://admin:xxxxxxxxxxx@20.20.1.162/Preview_01_sub #rtsp://adminxxxxxxxxxxx@20.20.1.162:554/h265Preview_01_sub
          roles:
          - detect
    detect:
      width: 640
      height: 480
      fps: 20
      stationary:
        interval: 80
        threshold: 80
        max_frames:
          objects:
            person: 100
            car: 100
    objects:
      filters:
        car:
          mask:
            - 507,0,494,149,219,177,200,0
        cat:
          mask:
        dog:
          mask:
        person:
          mask:
            - 505,0,494,146,219,186,191,0
        umbrella:
          mask:
            - 493,147,505,0,189,0,215,178
    motion:
      mask:
        - 180,0,0,0,0,480,248,480
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 15
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 15
          mode: motion
        pre_capture: 5
        post_capture: 15
    zones:
      strada:
        coordinates: 193,0,513,0,490,153,207,182
    live: 
      stream_name: vialetto_live
  giardino:
    ffmpeg:
      inputs:
      - path: rtsp://admin:xxxxxxxxxxx@20.20.1.161/h264_stream   #H.264
        roles:
        - record
        - detect
    detect:
      width: 640
      height: 480
      fps: 15
      stationary:
        interval: 80
        threshold: 80
        max_frames:
          objects:
            person: 100
            car: 100
    objects:
      filters:
        car:
          mask:
            - 182,185,149,75,60,106,94,222,95,209
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 15
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 15
          mode: motion
        pre_capture: 5
        post_capture: 15
    live: 
      stream_name: giardino_live
rtmp:
  enabled: false

live:
  height: 640
  quality: 1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped #always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"  
    cap_add:
      - CAP_PERFMON
      - SYS_ADMIN 
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/frigate:/db
      - /root/frigate:/config:rw
      - /mnt/pve/omv/frigate/clips:/media/frigate/clips:rw
      - /mnt/pve/omv/frigate/recordings:/media/frigate/recordings:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxxxxxx"
```

### Relevant log output

```shell
2024-04-17 20:19:54.610147972  [INFO] Preparing Frigate...
2024-04-17 20:19:54.710820841  [INFO] Starting Frigate...
2024-04-17 20:19:55.928124344  [2024-04-17 20:19:55] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-04-17 20:19:55.967659781  [2024-04-17 20:19:55] peewee_migrate.logs            INFO    : Starting migrations
2024-04-17 20:19:55.971527004  [2024-04-17 20:19:55] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-04-17 20:19:55.975681217  [2024-04-17 20:19:55] frigate.app                    INFO    : Recording process started: 292
2024-04-17 20:19:55.977503473  [2024-04-17 20:19:55] frigate.app                    INFO    : go2rtc process pid: 91
2024-04-17 20:19:56.003758233  [2024-04-17 20:19:56] frigate.app                    INFO    : Output process started: 303
2024-04-17 20:19:56.011045498  [2024-04-17 20:19:56] detector.cpu                   INFO    : Starting detection process: 302
2024-04-17 20:19:56.011190963  [2024-04-17 20:19:56] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-04-17 20:19:56.035347665  [2024-04-17 20:19:56] frigate.app                    INFO    : Camera processor started for vialetto: 309
2024-04-17 20:19:56.042158259  [2024-04-17 20:19:56] frigate.app                    INFO    : Camera processor started for giardino: 310
2024-04-17 20:19:56.043610850  [2024-04-17 20:19:56] frigate.app                    INFO    : Capture process started for vialetto: 312
2024-04-17 20:19:56.049068889  [2024-04-17 20:19:56] frigate.app                    INFO    : Capture process started for giardino: 313
2024-04-17 20:19:58.885794322  [2024-04-17 20:19:58] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied)
2024-04-17 20:19:58.885797769
```

### FFprobe output from your camera

```shell
VIALETTO
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

GIARDINO
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolink and ezviz

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/65458026/1e834a97-5411-4a04-aa3f-a418d811f093)

**Comment by NickM-27** [comment]
You should be using `preset-vaapi` for hwaccel_args, not manual args

You also should not be running CPU detectors, you should be using openvino https://docs.frigate.video/configuration/object_detectors#openvino-detector

**Reply by SofaSurfer76** [reply]
thanks for the fast reply.
sorry but I am not experienced, where is cpu detectors enabled? I see the message in the log but I have nothing in the config. Do you mean I have to disable all object detect?

**Reply by NickM-27** [reply]
cpu detectors are enabled by default for object detection. This is not recommended because they are very slow and use a lot of system resources. Your iGPU can be used instead by setting up openvino detection like it explains in the docs I linked

**Reply by bobloadmire** [reply]
It appears when I enable GPU detection using openvino it then disables VAAPI, I have to disable detection all together to get vaapi to work. Is this a limitation, or is something in my config messed up? The only way I can get my cpu usage down is to have detect: enabled: false on all my cameras with GPU detection on my N100.  Setting openvino to GPU and having 
`detect:
      height: 1080
      width: 1920
      fps: 20`

for my wyze cams via wyze bridge disables VAAPI and hammers my CPU, and in the system page GPUS intel-vaapi shows 0% and my 4 CPU cores at 100%

**Reply by NickM-27** [reply]
no, there is no such limitation. You also should not be running detect at 20 fps. This does not need to match your camera fps and in most cases should not exceed 10, 5 is the default

**Reply by bobloadmire** [reply]
oh good to know, i thought it needed to match the native FPS of the rtsp stream.

**Reply by bobloadmire** [reply]
Does the camera detect width/height need to match the model width/height?

**Reply by NickM-27** [reply]
no, it would be bad if it did. See https://docs.frigate.video/frigate/camera_setup#choosing-a-detect-resolution for guidance on detect resolution as well as https://docs.frigate.video/troubleshooting/faqs#what-do-i-do-if-my-cameras-sub-stream-is-not-good-enough

**Reply by bobloadmire** [reply]
ok thanks. I'm guessing that the n100+VAAPI is still not strong enough for 3 streams. I lowered FPS to 5, but even with openvino set to GPU and hwaccel set to VAAPI, my CPUs are getting destroyed, all 4 cores pinned.

would it be helpful to lower fps below 5? what would the downsides be?

**Reply by NickM-27** [reply]
We have users running an n100 on 16 streams. It sounds like something is very wrong with your setup.

**Reply by bobloadmire** [reply]
I feel really dumb now. Do you have a sample config that is working for the N100 with that sort of setup? below is my own:

`

> mqtt:
>   enabled: false
> ffmpeg:
>   hwaccel_args: preset-vaapi
> detectors:
>   ov:
>     type: openvino
>     device: GPU
>     model:
>       path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
> model:
>   width: 300
>   height: 300
>   input_tensor: nhwc
>   input_pixel_format: bgr
>   labelmap_path: /openvino-model/coco_91cl_bkgr.txt
> cameras:
>   Kitchen:
>     ffmpeg:
>       hwaccel_args: preset-vaapi
>       inputs:
>         - path: rtsp://192.168.0.4:8554/kitchen
>           roles:
>             - detect
>     detect:
>       height: 1080
>       width: 1920
>       fps: 5
>   Driveway:
>     ffmpeg:
>       hwaccel_args: preset-vaapi
>       inputs:
>         - path: rtsp://192.168.0.4:8554/driveway
>           roles:
>             - detect
>     detect:
>       height: 1080
>       width: 1920
>       fps: 5
>   LyrasRoom:
>     ffmpeg:
>       hwaccel_args: preset-vaapi
>       inputs:
>         - path: rtsp://192.168.0.4:8554/lyras-room
>           roles:
>             - detect
>     detect:
>       height: 1080
>       width: 1920
>       fps: 5

`

Since OPENVINO is enabled in this config, Inference SPeed is 98.6ms with 60% CPU time. If I disable VAAPI, then inference drops to 10ms and no cpu time, but then cameras eat all the CPU. It seems like I can only have one or the other?

**Reply by NickM-27** [reply]
> Inference SPeed is 98.6ms with 60% CPU time.

That's really slow. I don't think this is a frigate config issue this seems to be a host OS or lxc config issue

**Reply by bobloadmire** [reply]
are you familar with https://tteck.github.io/Proxmox/ ? I'm using his script to install the Docker LXC on my N100 system. Maybe that script is leaving something out that the n100 needs?

**Reply by NickM-27** [reply]
I am not familiar with that at all and only familiar by proxy with proxmox in general from helping people

**Reply by bobloadmire** [reply]
gotcha and nothing looks wrong with my config either?

**Reply by bobloadmire** [reply]
FWIW , this is the script https://github.com/tteck/Proxmox/blob/main/install/frigate-install.sh

**Reply by NickM-27** [reply]
no, like I said this will be an issue outside of frigate config itself. 

I notice the script installs `va-driver-all` which is just intel-media-driver meanwhile the actual frigate container installs intel-media-driver-non-free so that might be part of the issue. Could be other things missing too

**Comment by SofaSurfer76** [comment]
I will check the cpu load without object detect and then try to use openvino, please wait to mark the answer

**Comment by SofaSurfer76** [comment]
I have disabled the detect part, still 160% cpu:

`logger:
  default: info
  logs:
    frigate.mqtt: error

mqtt:
  host: 20.20.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password: xxxxxx
  stats_interval: 300

ffmpeg:
  hwaccel_args: -hwaccel vaapi
environment_vars:
  LIBVA_DRIVER_NAME: iHD

database:
  path: /db/frigate.db

record:
  expire_interval: 10



go2rtc:
  streams:
    vialetto_live:
      - rtsp://admin:xxxxxxxxxxx@20.20.1.162/Preview_01_sub
    giardino_live:
      - rtsp://admin:xxxxxxxxxxx@20.20.1.161/h264_stream 

cameras:
  vialetto:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxx@20.20.1.162/Preview_01_main #rtsp://admin:xxxxxxxxxxx@20.20.1.162:554/h265Preview_01_main  
          roles:
          - record
    motion:
      mask:
        - 180,0,0,0,0,480,248,480
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 15
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 15
          mode: motion
        pre_capture: 5
        post_capture: 15
    zones:
      strada:
        coordinates: 193,0,513,0,490,153,207,182
    live: 
      stream_name: vialetto_live
  giardino:
    ffmpeg:
      inputs:
      - path: rtsp://admin:xxxxxxxxxxx@20.20.1.161/h264_stream   #H.264
        roles:
        - record
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 15
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 15
          mode: motion
        pre_capture: 5
        post_capture: 15
    live: 
      stream_name: giardino_live


rtmp:
  enabled: false`

**Reply by NickM-27** [reply]
Your hwaccel args are still wrong. You should have `hwaccel_args: preset-vaapi`

**Comment by SofaSurfer76** [comment]
nothing changed

```
logger:
  default: info
  logs:
    frigate.mqtt: error

mqtt:
  host: 20.20.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password: xxxxxxxxxxx
  stats_interval: 300

ffmpeg:
  hwaccel_args: preset-vaapi 
environment_vars:
  LIBVA_DRIVER_NAME: iHD

database:
  path: /db/frigate.db

record:
  expire_interval: 10



go2rtc:
  streams:
    vialetto_live:
      - rtsp://admin:xxxxxxxxxxx@20.20.1.162/Preview_01_sub
    giardino_live:
      - rtsp://admin:xxxxxxxxxxx@20.20.1.161/h264_stream 

cameras:
  vialetto:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxx@20.20.1.162/Preview_01_main #rtsp://admin:xxxxxxxxxxx@20.20.1.162:554/h265Preview_01_main  
          roles:
          - record
    motion:
      mask:
        - 180,0,0,0,0,480,248,480
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 15
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 15
          mode: motion
        pre_capture: 5
        post_capture: 15
    zones:
      strada:
        coordinates: 193,0,513,0,490,153,207,182
    live: 
      stream_name: vialetto_live
  giardino:
    ffmpeg:
      inputs:
      - path: rtsp://admin:xxxxxxxxxxx@20.20.1.161/h264_stream   #H.264
        roles:
        - record
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 15
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 15
          mode: motion
        pre_capture: 5
        post_capture: 15
    live: 
      stream_name: giardino_live


rtmp:
  enabled: false
```
load is better bur still high, and GPU error
![image](https://github.com/blakeblackshear/frigate/assets/65458026/28bd91a6-fa8e-4450-aa8d-2370a4522b93)
and still detector error in the log:
2024-04-17 21:41:22.324241935  [2024-04-17 21:41:22] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
