### DISCUSSION TITLE
[Question]: Is there a way to have email alerts when a camera stops working (no frames received?)

### DISCUSSION THREAD

**Discussion by paultanger** [blakeblackshear/frigate#11021] [Ask A Question] [answered]
### What is your question:

Is there a way to have email alerts when a camera stops working? For example no frames received?

**Comment by NickM-27** [comment, marked as answer]
yes, you can use mqtt `camera_fps == 0` as the condition. The email part itself you will have to configure

**Reply by paultanger** [reply]
awesome, thanks!

**Reply by paultanger** [reply]
Is the notification part something that could be configured with home assistant blueprints? Just starting to look at this but not sure if there is examples (I see event triggered examples) but I didn't see this as an option listed here: https://docs.frigate.video/integrations/mqtt/. Thanks!

**Reply by paultanger** [reply]
@NickM-27 Hi Nick, do you have an example of how to structure a HA notification from one of these stats values? I've been looking for examples but having a hard time.  Here is what I have so far but how can I specify which camera to set the condition on?:
``` yaml
alias: frigate cam down
description: ""
trigger:
  platform: mqtt
  topic: frigate/stats
action:
  - service: notify.mobile_app_pt12
    data:
      message: camera down!
      title: frigate
mode: single
condition:
  - "{{'camera_fps' == 0}}"
```

**Reply by NickM-27** [reply]
This is what I do

```
description: ""
mode: single
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.front_cam_camera_fps
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: 1
condition: []
action:
  - service: notify.notify
    metadata: {}
    data: {}

```

**Reply by paultanger** [reply]
Thanks! I had to enable the sensor, and it works if I trigger it manually, but it doesn't seem to work on its own, it just doesn't seem to get triggered even though I see the sensor fps is zero. Sorry if this is getting off topic, but think this might be helpful for others! If there is a better place to ask, let me know. Thanks for all your help on this project!  Here is what I have:

``` yaml
alias: frigate back cam down
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.back_camera_fps
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: 1
condition: []
action:
  - service: notify.paul_phone_and_email
    data:
      title: back camera down!
      message: back camera fps detected under 1 fps for more than a minute.
mode: single
```

![image](https://github.com/blakeblackshear/frigate/assets/5291285/2727d33a-50ed-49da-a489-9e73ac694fe4)
