### DISCUSSION TITLE
[Support]: HASS integration and zone occupancy events

### DISCUSSION THREAD

**Discussion by esand** [blakeblackshear/frigate#11046] [General Support] [answered]
### Describe the problem you are having

I have an automation set up in Home Assistant to detect when people are detected in certain zones, and there's one camera and zone that seems to get a lot of hits, yet checking the recorded events shows that the person was never really in the zone, but perhaps just really close.

I have read up on how the motion and object tracking works, and I'm wondering if it's by design, or if perhaps there's some advanced tweaks I can do to this particular camera (outside of shrinking the zone boundaries) to reduce the chances of this happening.

In most cases, the people are walking dogs, and the dogs usually do enter the zone (which I don't care about). Would this possibly trigger Frigate to assume the person is in the zone too because Frigate detected motion in the zone (the dog), and detected a person in frame (but not in the zone)?

If that's not the issue, would Frigate consider an object in a zone even if the bounding box is just 😗 kissing it on the edge? Is there a way to control how much of the object needs to be inside a zone before it's considered occupying it?

Or, is it just the HASS integration and how it works? Should I switch to using MQTT events instead?

### Version

0.13.2

### Frigate config file

```yaml
record:
      enabled: true
    detect:
      width: 1280
      height: 720
      stationary:
        max_frames:
          objects:
            person: 600
            car: 600
    snapshots:
      enabled: true
    objects:
      track:
      - person
      - car
      - dog
      - cat
      filters:
        person:
          mask:
          - 0,0,1280,0,1280,0,1280,256,1234,231,1168,201,1060,160,930,134,761,115,604,109,431,113,257,130,94,163,0,189
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

My automation is using the "occupied" trigger type which is simply "Zone person occupancy became occupied" and I can't tweak it outside of that.
