### DISCUSSION TITLE
[Config Support]: 'Mask & Zone creator' crashes

### DISCUSSION THREAD

**Discussion by jaymunro** [blakeblackshear/frigate#11047] [Config Support] [answered]
### Describe the problem you are having

The UI in 'Mask & Zone creator' crashes when clicking the 'Save' button of 'ZONES' and 'OBJECT MASKS'. All subsequent clicks on anything in the whole UI does nothing. The page must be reloaded for it to become usable again. Often the changes made in the config are not saved and have to be redone.

Pressing 'Save' in 'MOTION MASKS' saves the config correctly and gives the message `Config successfully updated, restart to apply`.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.x.x
  user: xxxxxxxxxxx
  password: xxxxxxxx

go2rtc:
  streams:
    gatecam_3k:
    - rtsp://admin:xxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    gatecam_vga:
    - rtsp://admin:xxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    courtyardcam_3k:
    - rtsp://admin:xxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    courtyardcam_vga:
    - rtsp://admin:xxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    garagecam_hd:
    - rtsp://admin:xxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garagecam_vga:
    - rtsp://admin:xxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif

cameras:
  gatecam:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/gatecam_vga
        input_args: preset-rtsp-generic
        roles:
        - detect
        - audio
              # - record
      - path: rtsp://127.0.0.1:8554/gatecam_3k
        input_args: preset-rtsp-generic
        roles:
        - record
    live:
      stream_name: gatecam_3k
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
      - 616,28,616,46,444,46,444,28
      - 405,40,404,0,640,0,640,480,401,480,318,411,299,321,312,212,339,175,367,150,414,136,462,130,512,148,546,162,578,142,579,91
      - 0,221,46,158,64,61,118,47,156,45,228,53,284,47,349,33,474,21,480,0,0,0
      - 0,332,35,364,71,480,0,480
    zones:
      gate_inside:
        coordinates: 524,231,380,150,455,99,581,146
      gate_outside:
        coordinates: 583,138,617,100,510,64,459,92
      gate_trigger:
        coordinates: 361,435,516,231,377,148,192,267
        objects:
        - car
        - person
      porch_steps:
        coordinates: 181,267,402,480,0,480,0,401
    objects:
      filters:
        person:
          mask:
          - 499,258,194,0,0,0,0,146

  garagecam:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/garagecam_vga
        input_args: preset-rtsp-generic
        roles:
        - detect
        - audio
            # - record
      - path: rtsp://127.0.0.1:8554/garagecam_hd
        input_args: preset-rtsp-generic
        roles:
        - record
    live:
      stream_name: garagecam_hd
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
      - 616,28,616,46,444,46,444,28
    zones:
      garage_car1:
        coordinates: 375,323,373,178,34,185,41,314
        objects:
        - car
      garage_car2:
        coordinates: 45,480,473,480,438,342,38,340
        objects:
        - car
      garage_door:
        coordinates: 640,392,354,442,287,162,414,165,434,99,640,196
        objects:
        - car
        - person
        - dog
        - cat
        - number_plate

  courtyardcam:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/courtyardcam_vga
        input_args: preset-rtsp-generic
        roles:
        - detect
        - audio
            # - record
      - path: rtsp://127.0.0.1:8554/courtyardcam_3k
        input_args: preset-rtsp-generic
        roles:
        - record
    live:
      stream_name: courtyardcam_3k
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
      - 616,28,616,46,444,46,444,28
      - 229,80,585,101,568,145,400,122,242,114
      - 640,435,591,366,550,302,539,212,546,122,595,97,640,115
      - 640,0,640,115,357,118,280,139,134,172,132,90,103,60,91,126,0,157,0,0
      frame_alpha: 0.02
    zones:
      driveway:
        coordinates: 0,480,640,480,619,366,548,272,577,150,523,142,449,213,0,398
        objects:
        - car
        - person
        - dog
      grass:
        coordinates: 0,403,454,211,531,140,411,123,326,119,176,170,73,170,29,188,12,226
        objects:
        - person
        - dog
      viewing_platform:
        coordinates: 124,66,86,89,83,171,156,167
        objects:
        - person
        - dog
    objects:
      filters:
        person:
          mask:
          - 59,126,81,121,91,173,67,174
          - 223,98,248,91,259,135,234,141
snapshots:
  enabled: true
  retain:
    default: 30

motion:
  threshold: 30

objects:
  track:
  - person
  - car
  - number_plate
  - dog
  - cat
  - package
  filters:
    person:
      threshold: 0.65
    dog:
      threshold: 0.6
    cat:
      threshold: 0.6
    package:
      threshold: 0.6


record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
```

### Relevant log output

```shell
2024-04-20 15:15:33.135671751  [INFO] Preparing Frigate...
2024-04-20 15:15:33.155776543  [INFO] Starting Frigate...
2024-04-20 15:15:34.325473544  [2024-04-20 15:15:34] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-04-20 15:15:34.379958627  [2024-04-20 15:15:34] peewee_migrate.logs            INFO    : Starting migrations
2024-04-20 15:15:34.388393044  [2024-04-20 15:15:34] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-04-20 15:15:34.395517502  [2024-04-20 15:15:34] frigate.app                    INFO    : Recording process started: 440
2024-04-20 15:15:34.398441294  [2024-04-20 15:15:34] frigate.app                    INFO    : go2rtc process pid: 89
2024-04-20 15:15:34.427561085  [2024-04-20 15:15:34] frigate.app                    INFO    : Output process started: 451
2024-04-20 15:15:34.428730335  [2024-04-20 15:15:34] detector.cpu                   INFO    : Starting detection process: 450
2024-04-20 15:15:34.434066002  [2024-04-20 15:15:34] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-04-20 15:15:34.588542419  [2024-04-20 15:15:34] frigate.app                    INFO    : Camera processor started for gatecam: 469
2024-04-20 15:15:34.598720044  [2024-04-20 15:15:34] frigate.app                    INFO    : Camera processor started for garagecam: 470
2024-04-20 15:15:34.598914335  [2024-04-20 15:15:34] frigate.app                    INFO    : Camera processor started for courtyardcam: 471
2024-04-20 15:15:34.598978669  [2024-04-20 15:15:34] frigate.app                    INFO    : Capture process started for gatecam: 473
2024-04-20 15:15:34.602206335  [2024-04-20 15:15:34] frigate.app                    INFO    : Capture process started for garagecam: 477
2024-04-20 15:15:34.613434377  [2024-04-20 15:15:34] frigate.app                    INFO    : Capture process started for courtyardcam: 481
```

### Frigate stats

```json
{"cameras":{"courtyardcam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":481,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":491,"pid":471,"process_fps":5.1,"skipped_fps":0.0},"garagecam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":477,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":484,"pid":470,"process_fps":5.0,"skipped_fps":0.0},"gatecam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":473,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":480,"pid":469,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"7.1","cpu_average":"6","mem":"0.4"},"100":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"103":{"cmdline":"python3 -u -m frigate","cpu":"2.7","cpu_average":"3","mem":"3.3"},"118":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"151":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"152":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"438":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.4"},"440":{"cmdline":"frigate.recording_manager","cpu":"0.5","cpu_average":"0","mem":"1.6"},"449":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)","cpu":"0.3","cpu_average":"0","mem":"0.1"},"450":{"cmdline":"frigate.detector.cpu ","cpu":"1.6","cpu_average":"3","mem":"1.6"},"451":{"cmdline":"frigate.output       ","cpu":"1.0","cpu_average":"0","mem":"1.5"},"455":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"456":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"457":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"458":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"469":{"cmdline":"frigate.process:gatecam","cpu":"2.0","cpu_average":"1","mem":"1.6"},"470":{"cmdline":"frigate.process:garagecam","cpu":"2.3","cpu_average":"2","mem":"1.6"},"471":{"cmdline":"frigate.process:courtyardcam","cpu":"1.6","cpu_average":"1","mem":"1.7"},"473":{"cmdline":"frigate.capture:gatecam","cpu":"1.0","cpu_average":"0","mem":"1.5"},"477":{"cmdline":"frigate.capture:garagecam","cpu":"0.9","cpu_average":"0","mem":"1.5"},"480":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/gatecam_vga -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.1","cpu_average":"2","mem":"0.4"},"481":{"cmdline":"frigate.capture:courtyardcam","cpu":"0.9","cpu_average":"0","mem":"1.5"},"484":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/garagecam_vga -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.1","cpu_average":"4","mem":"0.4"},"491":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/courtyardcam_vga -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.6","cpu_average":"2","mem":"0.4"},"492":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/gatecam_3k -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/gatecam@%Y%m%d%H%M%S%z.mp4","cpu":"4.0","cpu_average":"4","mem":"0.4"},"493":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/garagecam_hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garagecam@%Y%m%d%H%M%S%z.mp4","cpu":"7.4","cpu_average":"6","mem":"0.4"},"496":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/courtyardcam_3k -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/courtyardcam@%Y%m%d%H%M%S%z.mp4","cpu":"4.0","cpu_average":"4","mem":"0.3"},"5105":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.2,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":30.54,"pid":450}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":438},"recording":{"pid":440}},"service":{"last_updated":1713584082,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":150.4,"mount_type":"tmpfs","total":154.0,"used":3.6},"/media/frigate/clips":{"free":159049.0,"mount_type":"fakeowner","total":948584.2,"used":789535.1},"/media/frigate/recordings":{"free":159049.0,"mount_type":"fakeowner","total":948584.2,"used":789535.1},"/tmp/cache":{"free":951.4,"mount_type":"tmpfs","total":953.7,"used":2.3}},"temperatures":{},"uptime":1148,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Docker is running on a Mac M1 CPU
