### DISCUSSION TITLE
[Config Support]: how do i configure events for a zone only when the object went through another zone first?

### DISCUSSION THREAD

**Discussion by ghost** [blakeblackshear/frigate#11057] [Config Support]
### Describe the problem you are having

i'd like to do something similar to what the parked car page has outlined, but i'm not sure how to lay out the config:

I have a 'driveway' zone. i'd like to trigger an event only when a car comes through a 'street' zone and then enters the 'driveway' zone. i don't want a car that's leaving and starts in 'driveway' and ends in 'street' to trigger an event.

Is this possible through the frigate config?

### Version

0.13.2

### Frigate config file

```yaml
cameras:
  driveway:
    zones:
      driveway:
        coordinates: 
       584,281,425,286,255,382,277,406,154,493,178,529,112,720,1184,720,1040,385,974,336,828,261,751,265,654,258
        objects:
        - car
      street:
        coordinates: 438,216,914,210,932,228,432,235
        objects:
        - car
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
