### DISCUSSION TITLE
[Camera Support]: Mobotix T24

### DISCUSSION THREAD

**Discussion by kobelka** [blakeblackshear/frigate#11065] [Camera Support] [answered]
### Describe the problem you are having

Hi,
I've been trying to get my Mobotix T24 and Q24 to work with Frigate for a while now. The picture works, but I can't get the sound to work and the recording doesn't work either. With this config I get the stream, but no sound and no recordings. Any config I tested does not work:

```
go2rtc:
  streams:
   # haustuercam:
   #   - rtsp://admin:pass@haustuercam/stream0/mobotix.mjpeg
   #   - "ffmpeg:haustuercam#audio=opus" 
   # haustuercam_sub:
   #   - rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg
   #   - "ffmpeg: rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg#video=h264#hardware"
   #   - rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg 
```

Regards
Jörg

### Version

0.13.2-6476F8A go2rtc 1.8.4

### Frigate config file

```yaml
# Frigate Configuration file
# Defaults: https://docs.frigate.video/configuration/#full-configuration-reference

# MQTT needed for Smart Home Applications 
mqtt:
  host: 10.11.1.236 # <---- same mqtt broker that home assistant uses
  user: mqttuser
  password: mqttpass
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
database:
  path: /config/frigate.db

# Overview of all cameras https://frigate.video/images/birdseye-2-optimized.jpg
birdseye:
  enabled: true


# Hardware acceleration of video conversion

# Snapshots of events
snapshots:
  # Enable writing jpg snapshot to /media/frigate/clips
  enabled: True
  # print a timestamp on the snapshots
  timestamp: True

# List of objects to capture https://docs.frigate.video/configuration/objects/
objects:
  track:
    - person
    - cat
    - dog
    - bicycle
    - car
    - eye glasses
    - backpack
    - handbag
go2rtc:
  streams:
   # haustuercam:
   #   - rtsp://admin:pass@haustuercam/stream0/mobotix.mjpeg
   #   - "ffmpeg:haustuercam#audio=opus" 
   # haustuercam_sub:
   #   - rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg
   #   - "ffmpeg: rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg#video=h264#hardware"
   #   - rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg 
  

# List of cameras
cameras:
  haustuercam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy  
      inputs:
        - path: rtsp://admin:pass@haustuercam/stream0/mobotix.mjpeg
          input_args: preset-rtsp-restream        
          roles:
            - record
        - path: rtsp://admin:pass@haustuercam/stream1/mobotix.mjpeg 
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference

# Record settings https://docs.frigate.video/configuration/record
record:
  enabled: True
  retain:
    # record everything
    mode: all
    # and store it for 14 days
    days: 14
```

### Relevant log output

```shell
2024-04-22 11:56:57.839443751  [2024-04-22 13:56:57] ffmpeg.haustuercam.record      ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
2024-04-22 11:56:57.839526279  [2024-04-22 13:56:57] ffmpeg.haustuercam.record      ERROR   : [mp4 @ 0x55929621e4c0] Could not find tag for codec pcm_mulaw in stream #1, codec not currently supported in container
2024-04-22 11:56:57.839597826  [2024-04-22 13:56:57] ffmpeg.haustuercam.record      ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
2024-04-22 11:56:57.839666227  [2024-04-22 13:56:57] ffmpeg.haustuercam.record      ERROR   : Error initializing output stream 0:1 -- 
2024-04-22 11:56:57.839745338  [2024-04-22 13:56:57] ffmpeg.haustuercam.record      ERROR   : 
2024-04-22 11:56:57.839821374  [2024-04-22 13:56:57] watchdog.haustuercam           INFO    : Terminating the existing ffmpeg process...
2024-04-22 11:56:57.839891097  [2024-04-22 13:56:57] watchdog.haustuercam           INFO    : Waiting for ffmpeg to exit gracefully...
2024-04-22 11:56:58.075297648  [2024-04-22 13:56:58] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/haustuercam@20240422135653+0200.mp4
2024-04-22 11:56:58.075377141  [2024-04-22 13:56:58] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/haustuercam@20240422135653+0200.mp4
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"MotionJPEG","display_aspect_ratio":"16:9","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"MotionJPEG","display_aspect_ratio":"16:9","height":720,"width":1280},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]
```

### Operating system

Unraid

### Install method

Docker

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Mobotix T24

**Comment by NickM-27** [comment]
You can't record mjpeg you have to transcode it to h264

**Comment by kobelka** [comment]
When I change my config to 

```
go2rtc:
  streams:
    haustuercam:
      - "ffmpeg:rtsp://admin:pass@haustuercam.kobelka.de/stream0/mobotix.mjpeg#video=h264#hardware"
```

```  haustuercam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy    
      inputs:
        - path: rtsp://127.0.0.1:8554/haustuercam
        #- path: rtsp://admin:yWZ%jMSI5g0d@haustuercam.kobelka.de/stream0/mobotix.mjpeg # <--- the name here must match the name of the camera in restream
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```



I get these errors:

```2024-04-22 12:47:23.738435913  [2024-04-22 14:47:23] frigate.video                  ERROR   : haustuercam: Unable to read frames from ffmpeg process.
2024-04-22 12:47:23.738528867  [2024-04-22 14:47:23] frigate.video                  ERROR   : haustuercam: ffmpeg process is not running. exiting capture thread...
2024-04-22 12:47:28.474377728  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3ea0026980] moov atom not found
2024-04-22 12:47:28.474936695  [ERROR:0@10.547] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-04-22 12:47:28.474938098  
2024-04-22 12:47:28.474939140  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-04-22 12:47:28.474941695  
2024-04-22 12:47:28.474942056  
2024-04-22 12:47:28.508058217  [2024-04-22 14:47:28] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/gartencam@20240422144724+0200.mp4
2024-04-22 12:47:28.508126444  [2024-04-22 14:47:28] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/gartencam@20240422144724+0200.mp4
2024-04-22 12:47:38.638106116  [2024-04-22 14:47:38] watchdog.haustuercam           ERROR   : Ffmpeg process crashed unexpectedly for haustuercam.
2024-04-22 12:47:38.638165517  [2024-04-22 14:47:38] watchdog.haustuercam           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-04-22 12:47:38.638212255  [2024-04-22 14:47:38] ffmpeg.haustuercam.detect      ERROR   : rtsp://127.0.0.1:8554/haustuercam: Invalid data found when processing input
```

And no video stream

**Reply by NickM-27** [reply]
need to see the go2rtc logs

**Comment by kobelka** [comment]
``Ok, I don´t know how much I changed...
Here is my actual config:

``` # Frigate Configuration file
# Defaults: https://docs.frigate.video/configuration/#full-configuration-reference

# MQTT needed for Smart Home Applications 
mqtt:
  host: 10.11.1.236 # <---- same mqtt broker that home assistant uses
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
database:
  path: /config/frigate.db

# Overview of all cameras https://frigate.video/images/birdseye-2-optimized.jpg
birdseye:
  enabled: true

# Hardware acceleration of video conversion
ffmpeg:
  hwaccel_args: preset-vaapi
  
# Snapshots of events
snapshots:
  # Enable writing jpg snapshot to /media/frigate/clips
  enabled: True
  # print a timestamp on the snapshots
  timestamp: True

# List of objects to capture https://docs.frigate.video/configuration/objects/
objects:
  track:
    - person
    - cat
    - dog
    - bicycle
    - car
    - eye glasses
    - backpack
    - handbag
go2rtc:
  streams:
    carportcam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@carportcam.kobelka.de:88/videoMain 
      - "ffmpeg:carportcam#audio=aac"
    carportcam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@carportcam.kobelka.de:88/videoSub # <- stream which supports video & aac audio.
      - "ffmpeg:carportcam_sub#audio=aac" # <- copy of the stream which transcodes audio to opus for webrtc 
    hausseitecam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@hausseitecam.kobelka.de:88/videoMain 
      - "ffmpeg:hausseitecam#audio=aac"
    hausseitecam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@hausseitecam.kobelka.de:88/videoSub # <- stream which supports video & aac audio.
      - "ffmpeg:hausseitecam_sub#audio=aac" # <- copy of the stream which transcodes audio to opus for webrtc            
    werkstattcam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@werkstattcam.kobelka.de/stream1
      - "ffmpeg:werkstattcam#audio=aac"
    werkstattcam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@werkstattcam.kobelka.de/stream1 # <- stream which supports video & aac audio.
      - "ffmpeg:werkstattcam_sub#audio=aac" # <- copy of the stream which transcodes audio to opus for webrtc        
    terrassecam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@terrassencam.kobelka.de:88/videoMain
      - "ffmpeg:terrassencam#audio=aac"
    terrassecam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@terrassencam.kobelka.de:88/videoSub # <- stream which supports video & aac audio.
      - "ffmpeg:terrassencam_sub#audio=aac" # <- copy of the stream which transcodes audio to opus for webrtc     
    babycam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@babycam.kobelka.de/live0
      - "ffmpeg:babycam#audio=opus"
    babycam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@babycam.kobelka.de/live0 # <- stream which supports video & aac audio.
      - "ffmpeg:babycam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus for webrtc              
    haustuercam:
      - "ffmpeg: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@haustuercam.kobelka.de/stream0/mobotix.mjpeg#video=h264#hardware"
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@haustuercam.kobelka.de/stream0/mobotix.mjpeg
      - "ffmpeg: haustuercam#audio=aac"
    haustuercam_sub:
      - "ffmpeg: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@haustuercam.kobelka.de/stream0/mobotix.mjpeg#video=h264#hardware"
   #   - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@haustuercam.kobelka.de/stream0/mobotix.mjpeg
      #- "ffmpeg:haustuercam_sub#audio=aac"      
      ##- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@haustuercam.kobelka.de/stream0/mobotix.mjpeg
      - "ffmpeg:haustuercam#audio=aac" 
    gartencam:
      - "ffmpeg: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@gartencam.kobelka.de/stream0/mobotix.mjpeg#video=h264#hardware#audio=aac"
      #- "ffmpeg:gartencam#audio=aac"
    gartencam_sub:
      - "ffmpeg: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@gartencam.kobelka.de/stream1/mobotix.mjpeg#video=h264#hardware#audio=aac"
      #- "ffmpeg:gartencam_sub#audio=aac" # <- copy of the stream which transcodes audio to opus for webrtc 
    webrtc:
    candidates:
      - 10.11.1.12:8555
      - stun:8555
# List of cameras
cameras:
  carportcam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.12:8554/carportcam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.12:8554/carportcam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
         #   - audio
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: carportcam_sub
    motion:
      mask:
        - 0,1080,1920,1080,1920,352,1574,133,227,38
    webui_url: http://carportcam.kobelka.de:88/        
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference

  hausseitecam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hausseitecam
          input_args: preset-rtsp-restream        
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hausseitecam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    webui_url: http://hausseitecam.kobelka.de:88
    live:
      stream_name: hausseitecam_sub
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference 
      
  werkstattcam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/werkstattcam
          input_args: preset-rtsp-restream        
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/werkstattcam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      filters:
        car:
          mask:
          - 112,980,1464,983,1337,0,500,0
    live:
      stream_name: werkstattcam_sub
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference 
      
  haustuercam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/haustuercam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/haustuercam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    webui_url: http://haustuercam.kobelka.de
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference

  gartencam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gartencam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gartencam_sub            
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    webui_url: http://gartencam.kobelka.de
    live:
      stream_name: gartencam_sub

    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference

  terrassecam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrassecam
          input_args: preset-rtsp-restream        
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terrassecam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    webui_url: http://terrassencam.kobelka.de:88/             
    live:
      stream_name: terrassecam_sub
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference 
      
  babycam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/babycam
          input_args: preset-rtsp-restream        
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/babycam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac 
    live:
      stream_name: babycam_sub
    detect:
      enabled: True
      width: 1920
      height: 1080
      # Object detection uses 5 fps by default: https://docs.frigate.video/configuration/#full-configuration-reference 
# Record settings https://docs.frigate.video/configuration/record
record:
  enabled: True
  retain:
    # record everything
    mode: all
    # and store it for 14 days
    days: 14

```

These are the Errors from haustuercam mobotix t24 and gartencam mobotix q24:

``` 2024-04-23 12:40:36.627129936  [2024-04-23 12:40:36] frigate.video                  ERROR   : haustuercam: Unable to read frames from ffmpeg process.
2024-04-23 12:40:36.627193947  [2024-04-23 12:40:36] frigate.video                  ERROR   : haustuercam: ffmpeg process is not running. exiting capture thread...
2024-04-23 12:40:36.639462395  [2024-04-23 12:40:36] frigate.video                  ERROR   : gartencam: Unable to read frames from ffmpeg process.
2024-04-23 12:40:36.639571501  [2024-04-23 12:40:36] frigate.video                  ERROR   : gartencam: ffmpeg process is not running. exiting capture thread...
2024-04-23 12:40:51.553212960  [2024-04-23 12:40:51] watchdog.haustuercam           ERROR   : Ffmpeg process crashed unexpectedly for haustuercam.
2024-04-23 12:40:51.553269507  [2024-04-23 12:40:51] watchdog.haustuercam           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-04-23 12:40:51.553324881  [2024-04-23 12:40:51] ffmpeg.haustuercam.detect      ERROR   : rtsp://127.0.0.1:8554/haustuercam_sub: Invalid data found when processing input
2024-04-23 12:40:51.558792600  [2024-04-23 12:40:51] watchdog.gartencam             ERROR   : Ffmpeg process crashed unexpectedly for gartencam.
2024-04-23 12:40:51.558908579  [2024-04-23 12:40:51] watchdog.gartencam             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-04-23 12:40:51.559006554  [2024-04-23 12:40:51] ffmpeg.gartencam.detect        ERROR   : rtsp://127.0.0.1:8554/gartencam_sub: Invalid data found when processing input
2024-04-23 12:40:51.569361604  [2024-04-23 12:40:51] ffmpeg.haustuercam.record      ERROR   : rtsp://127.0.0.1:8554/haustuercam: Invalid data found when processing input
2024-04-23 12:40:51.577609829  [2024-04-23 12:40:51] watchdog.haustuercam           INFO    : Terminating the existing ffmpeg process...
2024-04-23 12:40:51.577612264  [2024-04-23 12:40:51] watchdog.haustuercam           INFO    : Waiting for ffmpeg to exit gracefully..
```

gp2rtc log:
``` 
2024-04-23 12:40:42.862774198  12:40:42.862 WRN [rtsp] error="streams: exec: exit status 1" stream=haustuercam
2024-04-23 12:40:52.928221103  12:40:52.928 WRN [rtsp] error="streams: exec: exit status 1" stream=haustuercam_sub
```

vainfo
``` 
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:MesaGalliumdriver22.3.6forAMDRadeonGraphics(renoir,LLVM15.0.6,DRM3.49,6.1.79-Unraid)nvainfo:SupportedprofileandentrypointsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLDnVAProfileNone:tVAEntrypointVideoProc"}
```

**Reply by NickM-27** [reply]
exit status 1 so there is an error. Need to enable trace logs

```
go2rtc:
  log:
    exec: trace
  streams: ...
```
