### DISCUSSION TITLE
[Detector Support]:Parked car not detected

### DISCUSSION THREAD

**Discussion by lorenzo-deluca** [blakeblackshear/frigate#11070] [Detector Support]
### Describe the problem you are having

Hello everyone, first of all, congratulations on an great project!

I'm a novice, but I'm having a "stupid" issue with the detection of my car parked in the garage, while I have no problem with the scooter that is detected perfectly even when stationary.
Here is a screenshot in debug mode.
![download](https://github.com/blakeblackshear/frigate/assets/32000123/a57cc332-9c09-4011-9917-7852d5826885)

I know the framing isn't the best but the garage is short and the camera doesn't have a very good grain, in any case the strange thing is that with "doods" the car is always recognised, while with Frigate I can't get it to be detected.
I've also tried creating a zone around it but nothing.

Here a screenshot of the same frame recognised by doods (without any specific configuration)
![doods_detection](https://github.com/blakeblackshear/frigate/assets/32000123/c50d5c21-235f-4f89-a69f-0af705663258)

I would tell you more, all I need to do is to find out if there's anything in the area I've created around the car or not, 
because the garage is so small that the car can only fit in that area 😄 

Thank you all very much and I apologise if the question is obvious! 🥇 

### Version

0.13.2

### Frigate config file

```yaml
detect:
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.9
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 15
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  # Optional: motion mask

  improve_contrast: true
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: Time in seconds to wait before ffmpeg retries connecting to the camera. (default: shown below)
  # If set too low, frigate will retry a connection to the camera's stream too frequently, using up the limited streams some cameras can allow at once
  # If set too high, then if a ffmpeg crash or camera stream timeout occurs, you could potentially lose up to a maximum of retry_interval second(s) of footage
  # NOTE: this can be a useful setting for Wireless / Battery cameras to reduce how much footage is potentially lost during a connection timeout.
  retry_interval: 10

  garage:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: true

    detect:
      stationary:
        max_frames:
          objects:
            car: 100

    objects:
      track:
      - person
      - car
      - motorcycle

    zones:
      parcheggio_auto:
        coordinates: 905,720,562,0,93,172,0,720 
        inertia: 1
        objects:
          - car
        
        filters:
          car:
            min_area: 5000
            max_area: 100000
            min_score: 0.4
            threshold: 0.5
            mask: 905,720,562,0,93,172,0,720 

    # Required: ffmpeg settings for the camera
    ffmpeg:
        #
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables or docker secrets, which must begin with 'FRIGATE_' and be referenced in {}
      - path: rtsp://user:pass!@ip:88/videoMain
          # Required: list of roles for this stream. valid values are: audio,detect,record,rtmp
          # NOTICE: In addition to assigning the audio, record, and rtmp roles,
          # they must also be enabled in the camera config.
        roles:
        - audio
        - detect
        - record
        - rtmp
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/config
      - /volume1/surveillance/_Frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "9150:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
2024-04-22 19:09:59.166251654  [INFO] Preparing Frigate...
2024-04-22 19:09:59.186075542  [INFO] Starting Frigate...
2024-04-22 19:10:00.564392206  [2024-04-22 19:10:00] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-04-22 19:10:00.664357123  [2024-04-22 19:10:00] peewee_migrate.logs            INFO    : Starting migrations
2024-04-22 19:10:00.670603733  [2024-04-22 19:10:00] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-04-22 19:10:00.674601139  [2024-04-22 19:10:00] frigate.app                    INFO    : Recording process started: 295
2024-04-22 19:10:00.677005764  [2024-04-22 19:10:00] frigate.app                    INFO    : go2rtc process pid: 88
2024-04-22 19:10:00.700499006  [2024-04-22 19:10:00] frigate.app                    INFO    : Output process started: 306
2024-04-22 19:10:00.701301881  [2024-04-22 19:10:00] detector.coral                 INFO    : Starting detection process: 305
2024-04-22 19:10:00.724481721  [2024-04-22 19:10:00] frigate.app                    INFO    : Camera processor started for living: 315
2024-04-22 19:10:00.729867026  [2024-04-22 19:10:00] frigate.app                    INFO    : Camera processor started for garage: 317
2024-04-22 19:10:00.734717098  [2024-04-22 19:10:00] frigate.app                    INFO    : Camera processor started for BalconePiano: 318
2024-04-22 19:10:00.741258150  [2024-04-22 19:10:00] frigate.app                    INFO    : Camera processor started for BalconeMansarda: 320
2024-04-22 19:10:00.747817602  [2024-04-22 19:10:00] frigate.app                    INFO    : Capture process started for living: 321
2024-04-22 19:10:00.754794777  [2024-04-22 19:10:00] frigate.app                    INFO    : Capture process started for garage: 322
2024-04-22 19:10:00.761036208  [2024-04-22 19:10:00] frigate.app                    INFO    : Capture process started for BalconePiano: 323
2024-04-22 19:10:00.768870468  [2024-04-22 19:10:00] frigate.app                    INFO    : Capture process started for BalconeMansarda: 324
2024-04-22 19:10:03.315305647  [2024-04-22 19:10:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-04-22 19:10:03.318670989  [2024-04-22 19:10:03] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB
