### DISCUSSION TITLE
list of objects detected by zone?

### DISCUSSION THREAD

**Discussion by fanrouge** [blakeblackshear/frigate#1107] [Ask A Question]
Good morning

Is it possible to define a list of objects detected by zone?

I have a camera and two zones for this view.
I need to detect people and cars in zone A.
And only dogs, cats or birds into zone B.

If not, could this be a new feature?

Thank you

**Comment by blakeblackshear** [comment]
Objects are going to be detected and tracked per camera. You should be able to configure snapshots, clips, and notifications to only store or alert on specific objects in each zone.

**Reply by fanrouge** [reply]
If I understand correctly I have to define two cameras with the same URL?
I can not do otherwise?

Currently I am using this:

```
camera:

  1_cour:
    width: 1920
    height: 1080

    ffmpeg:
      inputs:
        - path: rtsp://camera_cour:554/stream=0
          roles:
            - clips
            - detect

    zones:
      A:
        coordinates: 1920,0,1920,280,0,280,0,0

    objects:
      track:
        - person
        - car

    clips:
      enabled: True
      required_zones:
      - A

    snapshots:
      enabled: True
      required_zones:
      - A

  2_cour:
    width: 1920
    height: 1080

    ffmpeg:
      inputs:
        - path: rtsp://camera_cour:554/stream=0
          roles:
            - clips
            - detect

    zones:
      B:
        coordinates: 0,1080,1920,1080,1920,280,0,280

    objects:
      track:
        - dog
        - cat
        - bird

    clips:
      enabled: True
      required_zones:
      - B

    snapshots:
      enabled: True
      required_zones:
      - B
```

It works fine but uses a lot of network and CPU resources :-(

--------------------------------------------------------------------

Could this work in a future version of Frigate?

```
  cour:
    width: 1920
    height: 1080

    ffmpeg:
      inputs:
        - path: rtsp://camera_cour:554/stream=0
          roles:
            - clips
            - detect

    zones:
      A:
        coordinates: 1920,0,1920,280,0,280,0,0
        objects:
          track:
            - person
            - car
      B:
        coordinates: 0,1080,1920,1080,1920,280,0,280
        objects:
          track:
            - dog
            - cat
            - bird

    clips:
      enabled: True
      required_zones:
      - A
      - B

    snapshots:
      enabled: True
      required_zones:
      - A
      - B

```
