### DISCUSSION TITLE
[Support]: stream has stopped working (almost all the time but intermittently

### DISCUSSION THREAD

**Discussion by blacknell** [blakeblackshear/frigate#11085] [General Support]
### Describe the problem you are having

Recently, without changes to config I've been getting the no frames received error on frigate home dashboard. Unfortunately this was happening while I was on holiday so almost impossible to investigate.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.23
  topic_prefix: frigate
  client_id: frigatepi.local-d83add180f65
  user: mqtt
  password: REDACTED

logger:
  default: info
  logs:
    frigate.record: info
    frigate.events: info
    frigate.mqtt: info
    frigate.record.cleanup: debug
ui:
  use_experimental: true

telemetry:
  network_interfaces: [ ]
  stats:
    network_bandwidth: True

database:
  path: /media/frigate/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous
  restream: true

record:
  enabled: true
  retain:
    mode: motion
    days: 2
  events:
    retain:
      mode: active_objects
      default: 3
      objects:
        person: 7
        cat: 2
        dog: 2
    pre_capture: 5
    post_capture: 5

snapshots:
  enabled: True
  bounding_box: True
  quality: 100
  retain:
    default: 14
    objects:
      person: 14

live:
  height: 1080

objects:
  track:
    - car
    - license_plate
    - person
    - face
    - package
    - cat
    - dog

model:
  path: plus://REDACTED

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"

cameras:
  front_door:
    ui:
      order: 0
    mqtt:
      height: 720
      quality: 100
    detect:
      enabled: True
      width: 1280
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.51:8554/front_door_720
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://192.168.1.51:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      hwaccel_args: preset-rpi-64-h264
    motion:
      mask:
        - 1238,72,1243,22,1017,21,1014,73
    webui_url: "rtsp://192.168.1.51:8554/front_door"
    zones:
      street:
        coordinates: 718,0,726,149,563,132,567,0
        objects:
          - car
          - person
          - face
          - package
          - dog
      driveway:
        coordinates: 976,237,1193,311,1168,398,998,720,754,720,349,477,384,439,334,131,524,92,547,144,748,174,859,196
        objects:
          - car
          - license_plate
          - person
          - face
          - package
          - dog
          - cat
        filters:
          car:
            min_area: 50000
      porch:
        coordinates: 451,720,802,720,375,463,317,0,245,0,0,0,0,720
        objects:
          - person
          - face
          - package
  back_garden:
    ui:
      order: 1
    mqtt:
      height: 720
      quality: 100
    detect:
      enabled: True
      width: 1280
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.51:8554/back_garden_720
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://192.168.1.51:8554/back_garden
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      hwaccel_args: preset-rpi-64-h264
    motion:
      mask:
        - 1104,0,1280,0,1280,220,1068,130,1016,117,1000,88,963,82,926,0
    webui_url: "rtsp://192.168.1.51:8554/back_garden"
    zones:
      patio:
        coordinates: 329,330,359,294,575,277,577,322,709,354,163,473,139,347
        objects:
          - person
          - face
          - cat
      lawn:
        coordinates: 216,534,379,720,889,720,1280,720,1280,411,885,352,211,479
        objects:
          - person
          - face
          - cat
      gate:
        coordinates: 0,354,111,332,130,241,110,194,0,195
        objects:
          - person
          - face
      logstore:
        coordinates: 873,348,932,346,937,252,874,248
        objects:
          - person
          - face
  front_door_gate:
    ui:
      order: 2
    mqtt:
      height: 720
      quality: 100
    detect:
      enabled: True
      width: 1280
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.51:8554/front_door_crop
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://192.168.1.51:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      hwaccel_args: preset-rpi-64-h264
    webui_url: "rtsp://192.168.1.51:8554/front_door"
    motion:
      mask:
        - 1280,0,1280,254,964,255,961,0
    zones:
      street:
        coordinates: 398,0,914,0,896,428,401,369
        objects:
          - car
      driveway:
        coordinates: 0,720,0,519,368,401,976,473,1164,720,369,720
        objects:
          - car
```

### Relevant log output

```shell
Many 100s of lines


2024-04-23 21:15:34.766087341  [2024-04-23 21:15:34] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:15:44.777441189  [2024-04-23 21:15:44] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:15:54.764534939  [2024-04-23 21:15:54] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:16:04.764607890  [2024-04-23 21:16:04] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:16:14.763001379  [2024-04-23 21:16:14] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:16:24.772853048  [2024-04-23 21:16:24] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:16:34.773246964  [2024-04-23 21:16:34] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:16:44.771521738  [2024-04-23 21:16:44] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:16:54.771078223  [2024-04-23 21:16:54] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-04-23 21:17:04.776395113  [2024-04-23 21:17:04] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### FFprobe output from your camera

```shell
ffprobe rtsp://192.168.1.51:8554/front_door_crop
ffprobe version 4.3.6-0+deb11u1+rpt5 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt5 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55b1d9e840] method SETUP failed: 461 Unsupported transport
[rtsp @ 0x55b1d9e840] decoding for stream 0 failed
Input #0, rtsp, from 'rtsp://192.168.1.51:8554/front_door_crop':
  Metadata:
    title           : go2rtc/1.8.5
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720, 5 fps, 5 tbr, 90k tbn, 10 tbc
```

### Frigate stats

```json
{"bandwidth_usages":{"2723267":{"bandwidth":146.4},"2723269":{"bandwidth":831.1},"2723270":{"bandwidth":165.1},"2723272":{"bandwidth":857.4},"2723273":{"bandwidth":281.8},"2723275":{"bandwidth":863.4}},"cameras":{"back_garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.8,"capture_pid":341,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":2723267,"pid":331,"process_fps":0.1,"skipped_fps":5.8},"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.6,"capture_pid":335,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":2723273,"pid":330,"process_fps":0.2,"skipped_fps":5.4},"front_door_gate":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":346,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":2723270,"pid":333,"process_fps":0.2,"skipped_fps":4.8}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"94":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"108":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"python3 -u -m frigate","cpu":"3.2","cpu_average":"13","mem":"31.1"},"121":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"134":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"135":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"136":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"138":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.4"},"139":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"294":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.6"},"296":{"cmdline":"frigate.recording_manager","cpu":"9.0","cpu_average":"9","mem":"2.3"},"305":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)","cpu":"0.2","cpu_average":"0","mem":"0.1"},"308":{"cmdline":"frigate.output       ","cpu":"0.8","cpu_average":"7","mem":"1.0"},"312":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1920x1080 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"1.1"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1920x1080 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1920x1080 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.9","cpu_average":"12","mem":"0.6"},"330":{"cmdline":"frigate.process:front_door","cpu":"0.7","cpu_average":"7","mem":"2.9"},"331":{"cmdline":"frigate.process:back_garden","cpu":"0.2","cpu_average":"5","mem":"1.9"},"333":{"cmdline":"frigate.process:front_door_gate","cpu":"0.8","cpu_average":"11","mem":"3.1"},"335":{"cmdline":"frigate.capture:front_door","cpu":"4.6","cpu_average":"4","mem":"1.1"},"341":{"cmdline":"frigate.capture:back_garden","cpu":"4.8","cpu_average":"4","mem":"1.1"},"346":{"cmdline":"frigate.capture:front_door_gate","cpu":"4.6","cpu_average":"4","mem":"1.1"},"1749406":{"cmdline":"python3 -u -m frigate","cpu":"0.0","cpu_average":"0","mem":"29.4"},"2723267":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://192.168.1.51:8554/back_garden_720 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"16.3","cpu_average":"21","mem":"0.7"},"2723269":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://192.168.1.51:8554/back_garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_garden@%Y%m%d%H%M%S%z.mp4","cpu":"3.4","cpu_average":"3","mem":"0.6"},"2723270":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://192.168.1.51:8554/front_door_crop -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.0","cpu_average":"13","mem":"0.7"},"2723272":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://192.168.1.51:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door_gate@%Y%m%d%H%M%S%z.mp4","cpu":"3.6","cpu_average":"3","mem":"0.6"},"2723273":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://192.168.1.51:8554/front_door_720 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"20.6","cpu_average":"23","mem":"0.7"},"2723275":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://192.168.1.51:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"3.5","cpu_average":"3","mem":"0.6"},"2896427":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.27,"pid":1749406}},"gpu_usages":{"rpi-v4l2m2m":{"gpu":-1,"mem":-1}},"processes":{"go2rtc":{"pid":94},"logger":{"pid":294},"recording":{"pid":296}},"service":{"last_updated":1713903388,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":91.6,"mount_type":"tmpfs","total":128.0,"used":36.4},"/media/frigate/clips":{"free":53564.9,"mount_type":"ext4","total":450439.5,"used":378542.7},"/media/frigate/recordings":{"free":53564.9,"mount_type":"ext4","total":450439.5,"used":378542.7},"/tmp/cache":{"free":835.1,"mount_type":"tmpfs","total":953.7,"used":118.6}},"temperatures":{},"uptime":1258823,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua
