### DISCUSSION TITLE
[Support]: Exported video seems to slow down then speed up stuttering

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#11082] [General Support]
### Describe the problem you are having

So when I export a clip from frigate it seems the video frame rate is all over the palce. Its runs slow then it runs fast. It does this over and over again 

Here is an example of a clip that I have exported that shows it ([Link to Google Photos](https://photos.app.goo.gl/3RT9rSp1Aks1C5qw6))

I am running frigate on TrueNAS Scale and my CPU is only ever at 10-15% 

Is there anything that I can do to help smooth out these video recordings. I just had an issue where my cameras caught a fatle crash rom my backyard camera and I coul dnot use the footage from frigate becuase it kept doing this and made the footage unusable because it made the timing hard to figureout! The recording from the cameras SD card were smotth so I used them instead to help the police. But it pointed out an issue with the sustem that I never knew I had and Id like to see if I can fix it!

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

# Enable recording of all cameras
record:
  enabled: true
  retain:
    days: 10
    mode: all

ui:
  use_experimental: true ## Use experimental UI


ffmpeg:
  hwaccel_args: preset-nvidia-h264 ## Use the GPU to help with decoding streams 
  output_args:
    record: preset-record-generic-audio-aac ## Record audio!

birdseye:
  enabled: False
  width: 1280
  height: 720
  mode: continuous

detectors:
  NVIDIA GeForce GTX 1080:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320


cameras:

  ###############################################################
  ## Back Yard - Reolink 8MP/4K, E1 Outdoor Pro, H.265
  ###############################################################  
  Back_Yard:
    ui:
      order: 1

    detect:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@192.168.86.218/Preview_01_main
          roles:
            - record
        - path: rtsp://{user}:{pass}@192.168.86.218/Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 0,0,640,0,640,360,0,360 ## Everything

  ###############################################################
  ## Driveway - Reolink 8MP/4K, E1 Outdoor Pro, H.265
  ###############################################################          
  Driveway:
    ui:
      order: 2

    detect:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@192.168.86.213/Preview_01_main
          roles:
            - record
        - path: rtsp://{user}:{pass}@192.168.86.213/Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 0,0,640,0,640,360,0,360 ## Everything

  ###############################################################
  ## Garage - Reolink, E1 Zoom, 5MP/2K+, H.265
  ###############################################################
  Garage:
    ui:
      order: 3

    detect:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@192.168.86.210/Preview_01_main
          roles:
            - record
        - path: rtsp://{user}:{pass}@192.168.86.210/Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 0,0,640,0,640,360,0,360 ## Everything

  ###############################################################
  ## Front Door - Reolink, Wifi Doorbell, 5MP/2K+ H.264
  ###############################################################
  Front_Door:
    ui:
      order: 4

    detect:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@192.168.86.217/Preview_01_main
          roles:
            - record
        - path: rtsp://{user}:{pass}@192.168.86.217/Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 0,0,640,0,640,360,0,360 ## Everything

  ###############################################################
  ## Front Yard
  ## Reolink 8MP/4K, E1 Outdoor Pro, H.265
  ## Record Stream - 3840*2160  25FPS  Bitrate 8192 Kbps
  ## Detect Stream - 640*360    4FPS   Bitrate 512 Kbps
  ###############################################################
  Front_Yard:
    ui:
      order: 5

    detect:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@192.168.86.212/Preview_01_main
          roles:
            - record
        - path: rtsp://{user}:{pass}@192.168.86.212/Preview_01_sub
          roles:
            - detect

    motion:
      mask:
        - 0,0,640,0,640,360,0,360 ## Everything

  ###############################################################
  ## Ripley's Room - Reolink, E1 Pro, 4MP/2K, H.264
  ###############################################################
  Ripleys_Room:
    ui:
      order: 6

    detect:
      enabled: False
      
    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@192.168.86.211/h264Preview_01_main
          roles:
            - record
        - path: rtsp://{user}:{pass}@192.168.86.211/h264Preview_01_sub
          roles:
            - detect
    motion:
      mask:
        - 0,0,640,0,640,360,0,360 ## Everything
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 3840x2160
FPS: 25/1

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: 4/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Reolink E1 Outdoor Pro

### Any other information that may be helpful

Here are my stream settings for the recording stream:

3840x2160
FPS: 25/1
8194 Bit Rate
