### DISCUSSION TITLE
[Support]: Recorded videoclip sometimes have duration of hours with stuck frames for a lot of minutes

### DISCUSSION THREAD

**Discussion by StefanoGiu** [blakeblackshear/frigate#11099] [General Support]
### Describe the problem you are having

Recorded videoclip sometimes have duration of hours even if the real event is few minutes. There are stuck frames for a lot of minutes (I see the timer on the camera image blocked) and then the video continues to play. The entire video lenght is even 2 or 3 hours... How can I fix it?

I tested both the streams via VLC:
- http://XXXXX:5000/vod/event/YYYYYY/index-v1-a1.m3u8
- http://XXXXX:5000/api/frigate/notifications/YYYYYY/clip.mp4
The first one is playable with no interruption/stuck and the duration is correct. The second one is broken, with blocked images and the duration is hours...

Can you help here? Maybe something wrong the way Frigate transforms the M3U8 into MP4 via FFMPEG?

Thanks

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
go2rtc:
 streams:
    Cancello:
      - rtsp://XXXX:XXXX@192.XX.XX.XX:XXX/tcp/av0_0
      - "ffmpeg:Cancello#audio=aac" 


cameras:
   Cancello:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cancello
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0,0,670,0,666,22,0,265
        - 1075,292,943,314,908,284,791,191,713,145,624,194,613,244,633,276,805,409,772,498,996,689,1206,576
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
Frigate doesn't convert from m3u8 to MP4, all of the segments are directly combined as MP4 in the current UI. 

The new UI will features a different way of doing things so I think this won't be an issue at that point. 

This is usually due to cameras sending bad timestamps in the stream

**Comment by StefanoGiu** [comment]
How can I download a proper MP4 file then ? I would like to have a file that plays properly just like on the Frigate UI... ignoring the camera bad timestamps... is there a way?

**Reply by NickM-27** [reply]
Use the export feature instead of download button

**Comment by StefanoGiu** [comment]
I need a way from Home Assistant to send the mp4 event to telegram so I can see the video... 

I'm currently using http://XXXX:5000/api/frigate/notifications/YYYY/clip.mp4 which comes broken... how shall I do it?

**Reply by NickM-27** [reply]
currently that is the only way to do that for that use case. You could try using ffmpeg in go2rtc and see if that works better

```
go2rtc:
 streams:
    Cancello:
      - "ffmpeg:rtsp://XXXX:XXXX@192.XX.XX.XX:XXX/tcp/av0_0#video=copy#audio=copy#audio=aac"
```
