### DISCUSSION TITLE
[Config Support]: Proxmox LXC locks and freezes

### DISCUSSION THREAD

**Discussion by Strux-DK** [blakeblackshear/frigate#11101] [Config Support]
### Describe the problem you are having

A couple of weeks ago i had a problem with my frigate instance running in a Proxmox LXC. At the moment i didn't have time to fix it so i just turned off the LXC, but to my surprise it wouldn't turn off. It was locked into some kind of state and after trying to unlock, kill and remove the LXC i tried with a reboot of the proxmox host, which unlocked it. However, it didn't tell me what went wrong.

Now i have time, but i have no idea what could be wrong or where to start. I can't turn on the LXC. I tried restoring a backup to a new LXC which worked fine (well, something was wrong, because i couldn't get a stream from the cameras, but the frigate app was running) right until i wanted to reboot the LXC, resulting in another lockup.

I'm not expecting this to be Frigate's fault, there's a high chance that i did something i just can't remember, but i'm hoping that with these symptomes, you can help me find out where to start. I can (well, i guess i have to) start up a new LXC with the backup, but not before i know exactly what to do and what commands to run, so i can get a step closer to what is wrong and how to fix it.

I've read in the proxmox forums that this (a LXC that is locked and cannot be stopped without a host reboot) can be caused by faults NFS mounts or something like that. I checked these in the docker compose file on the LXC and confirmed on my NAS and i don't see any problem.

Any help would be highly appreciated

### Version

can't tell

### Frigate config file

```yaml
This is a copy of a config file that should be stable, but for some reason it did not work:

mqtt:
  enabled: False

birdseye:
  enabled: True
  restream: True
  quality: 8
  mode: continuous  

ffmpeg:
  hwaccel_args: preset-vaapi
#  hwaccel_args: preset-intel-qsv-h264
  output_args:
    # Makes sure video AND audio is recorded
    record: preset-record-generic-audio-copy

go2rtc:
  log:
    exec: trace
  streams:
    entrance:
#      - rtsp://HAFrigate:etagirFAH@192.168.1.30:554/h264Preview_01_main
      - "ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=HAFrigate&password=etagirFAH#video=copy#audio=copy#audio=opus"
    entrance_sub:
#       - rtsp://HAFrigate:etagirFAH@192.168.1.30:554/h264Preview_01_sub
      - "ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=HAFrigate&password=etagirFAH"
    garden:
#      - rtsp://HAFrigate:etagirFAH@192.168.1.31:554/h264Preview_01_main
      - "ffmpeg:http://192.168.1.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=HAFrigate&password=etagirFAH#video=copy#audio=copy#audio=opus"
    garden_sub:
#       - rtsp://HAFrigate:etagirFAH@192.168.1.31:554/h264Preview_01_sub
      - "ffmpeg:http://192.168.1.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=HAFrigate&password=etagirFAH"

  webrtc:
    candidates:
      - 192.168.1.53:6555

cameras:
# ENTRANCE
  entrance:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrance_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      entrance_pathway:
        # Covers the pathway/parking space
        coordinates: 0,330,0,219,176,134,387,78,391,127

      entrance_road:
        # Covers the road
        coordinates: 222,131,388,87,382,42,208,65,0,130,0,228

      entrance_entryway:
        # Covers the entrance pathway and the grass
        coordinates: 603,217,619,130,541,108,513,127,391,97,332,135
    motion:
      mask:
        # The windows of the house, where the camera can see movement inside the house
        - 896,672,896,253,856,365,765,672
        # Timestamp
        - 0,34,0,0,269,0,267,34
    objects:
      track:
        - car
        - person
        - cat
      filters:
        person:
          # minimum width*height of the bounding box for the detected object
          min_area: 10000
          # minimum score for the object to initiate tracking
          min_score: 0.4
          # minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.7
        cat:
          min_score: 0.3
          threshold: 0.5
        car:
          min_score: 0.5

  # GARDEN
  garden:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:  
      garden_fence:
        # Covers the fence towards neighbor, the fence door and the birdfeeder
        coordinates: 154,133,171,177,255,165,249,39,0,68,0,148
    motion:
      mask:
        # Covers bedroom window
        - 0,257,0,423,47,479,25,336
        # Timestamp
        - 271,0,270,35,0,35,0,0
    objects:
      track:
        - bird
        - person
        - cat
      filters:
        bird:
          min_score: 0.5
        person:
          # minimum width*height of the bounding box for the detected object
          min_area: 10000
          # minimum score for the object to initiate tracking
          min_score: 0.4
          # minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.7
        cat:
          min_score: 0.3
          threshold: 0.5
    
detect:
  enabled: true
  width: 640
  height: 480
  fps: 7

motion:
  # Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
    contour_area: 40
      
record:
  enabled: True
  expire_interval: 720
  # Retention settings for recordings in general
  retain:
    # Number of days to save recordings
    days: 2
    # Save only recordings with detectable motion, regardless of whether any objects were detected or not
    mode: motion
  # Events are when something, frigate is configured to register, is happening.
  events:
  # Seconds of recording before movement is registered, to also be saved
    pre_capture: 2
    # Seconds of recording after movement is disappeared, to also be saved
    post_capture: 5
    objects:
      - person
      - cat
      - car
    required_zones:
      - entrance_pathway
      - entrance_entryway
      - entrance_road
    retain:
      # Number of days to retain/save recordings
      default: 30
      # This mode saves all recording segments with active/moving objects
      mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  required_zones:
  - entrance_pathway
  - entrance_entryway
  - entrance_road
  retain:
    default: 90

rtmp:
  enabled: False
  
# Yes, the legacy software is capable of showing the timestamp, but i like all the configurations to be the same place
timestamp_style:
  position: "tl"
  format: "%d/%m/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

# Web interface settings
ui:
  # Set the default live mode for cameras in the UI
  live_mode: mse
  # Play around with this
  timezone: Europe/Copenhagen
  # Date and time style for the events overview
  strftime_fmt: "%d/%m/%Y %H:%M:%S"
```

### Relevant log output

```shell
Don't have any
```

### Frigate stats

```json
go fish
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by koomanan** [comment]
I'm having the same issue, I'm switching from lxc to a vm on proxmox because it just can't work well with frigate.

**Comment by filipefumaux** [comment]
Same thing is happening to me. Running 15 RC1 version and around 3 days it get stuck. No terminal connection o n PVE or SSH

**Comment by filipefumaux** [comment]
Same thing here. Out of nowhere it consumes a lot of resources and locks the whole PVE

**Reply by petertoth-dev** [reply]
same here... testing it for weeks... tried everything... huge headroom for CPU, RAM, GPU, TPU, I/O. Everything is max 50% still Frigate literally kills the whole PVE host, only a hard reboot in the server room helps.

**Comment by hawkeye217** [comment]
While some users have found success, installing in a Proxmox LXC is an unsupported installation method. See the official docs: https://docs.frigate.video/frigate/installation#proxmox

Also, see this discussion: https://github.com/blakeblackshear/frigate/discussions/10921

**Reply by petertoth-dev** [reply]
it doesn't say it's unsupported
also, it should be supported
This is a huge bug and should be fixed or you'll start losing users and reputation.

**Reply by hawkeye217** [reply]
Myself nor any of the other maintainers use Proxmox, so we cannot support it.

See the official documentation: https://docs.frigate.video/frigate/installation/#proxmox

**Reply by petertoth-dev** [reply]
I understand. I'll share if I have any findings.

**Comment by BlueMax** [comment]
I have hard freezes every 2-3 weeks. 3 times in a row for now. I'm using LXC/native on Buildroot/Linux 6.12.55 (no docker, no proxmox). Resources are not exhausted. It just stops and freezes. The system is headless (no gfx output). I've installed 'pstore' (persistent storage) to catch dmesg but as there is no warm restart after kernel panic (if there is one at all) everything is lost after hard reset.
I would rather blame iGPU than LXC but its just a wild shot. 

Maybe we should share some hardware infos to find some common components.

CPU: Intel i3-8100 (LIBVA_DRIVER_NAME=i965)
RAM: 8GB
2 Cams, 5 Streams (720p, 1080p)

```
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency

detectors:
  ov:
    type: openvino
    device: GPU
```
