### DISCUSSION TITLE
Frigate+ Base Model 2024.1 Update

### DISCUSSION THREAD

**Discussion by blakeblackshear** [blakeblackshear/frigate#11106] [General]
**NOTE:** The base model was updated 24 hours ago. If you recently requested a new model, check the base model version before requesting a new one.

The base model in Frigate+ has now been updated to 2024.1. All model requests going forward will use this version. In order to get a new model, you will need to submit a model request.

In addition to incorporating new images from Frigate+ users, this base model update was focused on reducing known false positives. To date, nearly 250,000 false positive examples have been submitted by users. The previous base model reproduces 26% of these false positives and the new base model reduces that to 11%.

I also updated the fine tuning process to increase the effect that your verified images have on your model. My fine tuned model now reproduces only 1.5% of my reported false positives.

Here are some stats showing the false positive reduction for my model.

|Model|Results|
|:-----|:----|
| 2024.0 Base Model  | Reproduces 18.6% of my reported false positives  |
| My Tuned 2024.0 Model  | Reproduces 16.7% of my reported false positives  |
| 2024.1 Base Model | Reproduces 9% of my reported false positives |
| My Tuned 2024.1 Model | Reproduces 1.5% of my reported false positives |

According to every objective measure I have looked at, this should be a significant improvement in false positive rates, but I expect results to vary by user. I would appreciate some user feedback (both good and bad) after upgrading.

**Comment by Whomever6378** [comment]
Very excited to try the new model, there has been one plant in particular out the front of my home that supposedly looks exceptionally human 😅
I had actually just submitted a new model request maybe 5 hours ago?
Will this happen to be on the new 2024.1 or should I expect to submit another request for the new base model?

**Reply by blakeblackshear** [reply]
Any model requests submitted in the past 24 hours will be using the new model.

**Reply by YBonline** [reply]
Although ideally the AI should figure it out, if its one plant in particular, you can mask that object on that area. I have multiple tables with umbrellas, and I've had to mask those spots because Frigate is very insistent the umbrellas are people with extremely high confidence even after training tons of photos..

**Comment by Benoulimou** [comment]
Hello , 
Thank you for all your work on Frigate. I use it all the time as a complement to other things while I refine it and I really hope to succeed in using it exclusively! 
However, is it possible to add an option for multiple deletion of images sent to Frigate+ in order to redo models more in line with recent settings (change of cam position for example). It would make things a lot easier. 
Oh yes, and is it possible to delete models? 

Sorry for the questions, thank you very much for all your work! I can't wait to try it out!

**Reply by NickM-27** [reply]
If you move a camera you shouldn't be deleting old images, I've done this multiple times without any issues

**Reply by Benoulimou** [reply]
There are really a lot of them in the old position, won't that "disrupt" the model?

**Reply by NickM-27** [reply]
No it shouldn't. I've moved my garage camera twice and even took down a camera that had a few hundred images and it hasn't caused any issues at all. Blake has also answered that it shouldn't cause any issues in most cases.

**Reply by Benoulimou** [reply]
thank you for your reply

**Comment by RWMoo** [comment]
Very excited to try this, really appreciate the hard work you put into this. I'll provide feedback over the next week :)

**Comment by bbrodriguez** [comment]
I’ve been eagerly awaiting this, 2024.0 was great and set a high bar.

Just got my 2024.1 completed and configured in and super keen to see how it fares.

edit: I’d love to see a write up / summary of what changes you made to training sample selection this time.

**Reply by blakeblackshear** [reply]
Very similar to the last round, but I weighted the sampling to focus primarily on false positive examples.

**Reply by bbrodriguez** [reply]
My initial impression is that it is an improvement. I dropped my thresholds a little based on the stated reduction in false +ve’s - to try to increase detections through the night.

Of the images below, I might have expected at least one cat detection to have been labelled a dog under 2024.0.

Admittedly it was a clear night so not challenging images to process.
![IMG_1074](https://github.com/blakeblackshear/frigate/assets/3668755/8285c107-9067-427a-ad1e-0f703fcd3c48)
![IMG_1073](https://github.com/blakeblackshear/frigate/assets/3668755/e57b1f17-3537-4350-a54e-9dfcba8bafb9)

It still seems strong for people at night also which is important to me.

![image](https://github.com/blakeblackshear/frigate/assets/3668755/73673fde-a5f8-49cf-92b3-0ef48784deca)

**Reply by bbrodriguez** [reply]
So a few false +ve detections creeping in, but I can bump my thresholds back up a little (dialled them back to 0.75) which would eliminate many.

What I do think would help is improved motion detection (which I understand is in the works) - specifically tracking an object through its motion. I seem to suffer occasional bouts of a table being detected as a dog while a dog is in the frame somewhere - maybe after it passes by.

**Reply by NickM-27** [reply]
> specifically tracking an object through its motion

frigate already does this, a false positive dog and the real dog are most likely unrelated unless you see them as the same event when using the recordings timeline viewer

**Comment by blacknell** [comment]
I'm wondering how we could get false positive statistics for our own data - like you summarised in your intro.

**Reply by blakeblackshear** [reply]
It will be easier for me to do something like that after users have a model based on 2024.1. I would be interested in seeing those results across all users, so I may write a script to generate those stats and email them.

**Reply by blacknell** [reply]
Excellent

**Reply by blacknell** [reply]
If it's relatively straightforward would be good to get a view of how many false/true positives/negatives there are by label/camera so I can focus on adding those to frigate+ ready for next model request. with 400+ images it's getting difficult/becoming guesswork as to where to focus

**Reply by NickM-27** [reply]
I don't know that the goal should be even label distribution. I think the goal should be focusing on where defections are missing or boxes are inaccurate

**Reply by blacknell** [reply]
Fair point but it would show gaps by label

**Reply by pyrodex** [reply]
I wrote a simple Python script that does this for my needs, it allows me to submit true/false by label, camera, zone, or a combination of all three. It also allows me to purge events based off those factors if I ever decide to do so.

```
~$ frigate-events.py -h
usage: frigate-events.py [-h] [--silent] [-y] [-p] [-s] [-n] [-f] [-t] [-l LABEL] [-c CAMERA] [-z ZONE]

Utility script to help process Frigate events in large amounts

options:
  -h, --help            show this help message and exit
  --silent              Disable verbose output
  -y, --yes             Enable automatic YES instead of being prompted
  -p, --purge           Purge events
  -s, --submitted       Process submitted events only
  -n, --not-submitted   Process not submitted events only
  -f, --false-positive  Submit the events as False Positive to Frigate+
  -t, --true-positive   Submit the events as False Positive to Frigate+
  -l LABEL, --label LABEL
                        Specify Frigate Label, these are always lower case (e.g. person)
  -c CAMERA, --camera CAMERA
                        Specify Frigate Camera, these are the same CASE as displayed in your Frigate configuration
  -z ZONE, --zone ZONE  Specify Frigate Zone, these are the same CASE as displayed in your Frigate configuration

```

**Comment by mintjberry** [comment]
Honestly I was very underwhelmed by my first model using 2024.0, even after tuning it wasn't a lot better.
Am excited and hopeful for 2024.1, have requested my first model using it, thanks.

**Comment by rough316** [comment]
Tried my first + model, its not working. I get this in the logs:

2024-04-26 03:19:54.587111853  Process detector:ov:
2024-04-26 03:19:54.587125103  Traceback (most recent call last):
2024-04-26 03:19:54.587134163    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-04-26 03:19:54.587142563      self.run()
2024-04-26 03:19:54.587150983    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-04-26 03:19:54.587159223      self._target(*self._args, **self._kwargs)
2024-04-26 03:19:54.587171553    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2024-04-26 03:19:54.587179833      detections = object_detector.detect_raw(input_frame)
2024-04-26 03:19:54.587196023    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2024-04-26 03:19:54.587204733      return self.detect_api.detect_raw(tensor_input=tensor_input)
2024-04-26 03:19:54.587212953    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 84, in detect_raw
2024-04-26 03:19:54.587233863      infer_request.infer([tensor_input])
2024-04-26 03:19:54.587242323    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 152, in infer
2024-04-26 03:19:54.587251023      return super().infer(normalize_inputs(self, dict(enumerate(inputs))))
2024-04-26 03:19:54.587259413  RuntimeError: The input blob size is not equal to the network input size: got 307200 expecting 270000

**Reply by NickM-27** [reply]
> Process detector:ov:

You're trying to use openvino which isn't currently supported

**Reply by rough316** [reply]
Was thinking thats the case, trying to get it working with CPU, then will go find my USB Coral.

**Reply by rough316** [reply]
Up and running on the Coral USB. You guys are doing a fantastic job on Frigate!

**Comment by Sch0field9** [comment]
I have statues of lions on my gate pillars, which are often mistaken for either a person or a dog. (Interestingly, they are almost never mistaken for a cat.) From the camera's perspective, people almost always walk behind the statues.

You mentioned that to reduce false positives, we should submit true positives in that area along with the false positives. Now, if a person walks behind one of these statues and I submit it as a true positive with the statue overlapping the person, would that confuse the model?

**Reply by Sch0field9** [reply]
Regarding that topic: the camera in question is a PTZ camera, making it impossible to mask out the statues. Is there a solution to this issue, or is something planned for zones/masks on PTZ cameras?

**Reply by blakeblackshear** [reply]
As long as the person is actually visible too, it should be fine.

**Comment by blacknell** [comment]
So in this circumstance where the Frigate+ identified box is too big should we mark this not a package and draw a tighter bounding box?

<img width="251" alt="image" src="https://github.com/blakeblackshear/frigate/assets/8863732/89d04211-d346-4863-bd95-ab9bffa0ec9f">

**Reply by YBonline** [reply]
I believe you say it is a package, and then adjust the size of the box before verifying

**Reply by bbrodriguez** [reply]
I’ve noticed the face boxes are extremely large in 2024.1.

**Reply by NickM-27** [reply]
Yes, this would be `this is a package` and fix the box. 

Face boxes look accurate just like always in my usage so far

**Comment by YBonline** [comment]
So my initial results are that false positives are indeed way down, but false negatives are up as well (which is obviously a bit of a bigger deal). This might be because I hiked up my min score on the previous model, so I'm gonna try to reduce that and see how it goes.

The camera with the most notable negative impact in my sole newer (to me) fisheye camera.... its detecting near nothing now. I don't have a whole lot of training on it either, so I'll have to see if I can drop the minimums pretty low and start training it. I do have it using the raw stream, with no de-warping, so I don't know if that is a proper goal or if there should be a different model for this unusual camera format?

I just didn't want to create multiple additional streams as I have so many cameras already, and I'm near the limit of what my hardware can support without more RAM.

**Comment by nshp** [comment]
Looking pretty good so far with the new model. Still some false positives and misidentifications here and there, but the false positives have been noticeably reduced, making it much easier to scroll back through events. The only identification that doesn't seem to have been reduced is deer, but most of those are relatively low confidence, I'll just set the minimum higher. The stationary object tracking seems to be working much better for me with parked cars. It was losing the car-ness of parked cars many times a day previously, now it's pretty solid. I frequently have two cars that overlap from the camera's perspective, I could watch the detection going nuts hopping back and forth between which one of them was a car and which wasn't.

I did notice one particular type of new false positive showing up. One of my cameras can see the street through some (sparse) tree branches. I've been submitting plenty of true positives of cars driving by seen through the branches, Frigate has been doing a fine job of catching those. Now it seems I've trained this new model that cars, and branches blowing in the wind, are cars. I'm submitting those false positives now, hopefully it'll go back to normal with the next model I train.

I think my biggest remaining problem model-wise is that squirrels and foxes are always running by firing off a confident stream of "cat - dog - cat - dog - cat - dog" events.

**Reply by NickM-27** [reply]
Some of these sound like things that the new UI will greatly improve the experience of. 

Stationary tracking has also been improved for the next version.

**Comment by krustophenia** [comment]
Thanks for your excellent work!! One question, I've submitted some images with dog labels from different cameras, day/night etc but my frigate is not detecting any since I started using this custom models. Should I keep uploading and labeling dog images? I've lowered the score for dogs to 40-50% and even like this no detections. Thanks.

**Reply by NickM-27** [reply]
You should include your config, seems like a config issue

**Reply by krustophenia** [reply]
```
model:
  path: plus://XXXXXXX
mqtt:
  host: XXXXXXX
  user: XXXXX
  password: XXXXX
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  Cam_Piscina:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX:XXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://XXXXX:XXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    motion:
      improve_contrast: true
  Cam_Passadis:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://XXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    motion:
      improve_contrast: true
      mask: 
        - 389,203,402,0,1280,0,1280,576
  Cam_Parking:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://XXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    motion:
      improve_contrast: true
  Cam_Frontal:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://XXXXXX@XXXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    motion:
      improve_contrast: true
  Cam_Menjador:
    detect:
      width: 1920
      height: 1088
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXX/live0
          roles:
            - detect
            - record
    motion:
      improve_contrast: true
  Cam_Carrer:
    detect:
      width: 640
      height: 480
    rtmp:
      enabled: False 
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXXX@XXXXXX:554/h264Preview_01_sub
          roles:
            - detect
            - record
    motion:
      improve_contrast: true
    objects:
      filters:
        dog:
          min_score: .6
          threshold: .7
        person:
          min_score: .70
          threshold: .75

detect:
  width: 1280
  height: 960
  fps: 3
  enabled: True
  max_disappeared: 25

record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 10

snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  retain:
    default: 10

timestamp_style:
  position: "br"
  format: "%d/%m/%Y %H:%M:%S"
  color:
    red: 0
    green: 0
    blue: 0
  thickness: 1
  effect: "solid"

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: motion

objects:
  filters:
    dog:
      min_score: .4
      threshold: .5
    person:
      min_score: .80
      threshold: .82  
```
