### DISCUSSION TITLE
[Question]: Where to specify the go2rtc server path?

### DISCUSSION THREAD

**Discussion by alve89** [blakeblackshear/frigate#11100] [Ask A Question]
Actually I'm quite confused as the thread starter in #8293.

I think I start with my current setup:
1. I have Frigate running standalone as docker compose service:
```
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://co>
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your har>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/bin/frigate/config:/config
      - /mnt/ssd/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: "myRTSPUSER"
      FRIGATE_RTSP_PASSWORD: "myRTSPPassword"
      FRIGATE_MQTT_USER: "myMQTTUser"
      FRIGATE_MQTT_PASSWORD: "myMQTTPassword"
```

In Frigate config I have a working detection and MQTT configuration. This is my `cameras` section with one of my cameras:

```
cameras:
  camera1:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://myRTSPUser:myRTSPPassword@camera1.lan.k41/Preview_01_sub
        roles:
        - detect
      - path: rtsp:///myRTSPUser:myRTSPPassword@camera1.lan.k41/Preview_01_main
        roles:
        - record
    detect:
      enabled: true
```

Up to this point everything is working as expected (detection, recording, MQTT, ...).

Since I want some cameras with a "undelayed" view in Home Assistant, I installed the [WebRTC card](https://github.com/AlexxIT/WebRTC). This (by default) provides automatically a [go2rtc](https://github.com/AlexxIT/go2rtc) service. Since Frigate is also providing this service I see an unnecessarily duplicated service, so I thought of running `go2rtc` in an dedicated docker container:
```
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc
#    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    ports:
      - 1984:1984
#      - 8554:8554
#      - 8555:8555
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Europe/Berlin  # timezone in logs
    volumes:
      - /usr/local/bin/go2rtc:/config
```

I then put all my cameras into the `/usr/local/bin/go2rtc/go2rtc.yaml` config:
```
streams:
  camera1: rtsp://myRTSPUser:myRTSPPassword@camera1.lan.k41

api:
  listen: ":1984"
  base_path: ""
  static_dir: ""
  origin: ""

ffmpeg:
  bin: "ffmpeg"
  global: "-hide_banner"
  file: "-re -stream_loop -1 -i {input}"
  http: "-fflags nobuffer -flags low_delay -i {input}"
  rtsp: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i {input}"
  output: "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"

rtsp:
  listen: ":8554"
  username: ""
  password: ""

```

Now I'm at the starting point of my question:
### What is your question:

I just don't understand this [documentation](https://docs.frigate.video/guides/configuring_go2rtc). So my questions are:

1. What does this mean?
> If you set the stream name under go2rtc to match the name of your camera, it will automatically be mapped and you will get additional live view options for the camera.
and
```
go2rtc:
  streams:
    back:
```

2. If I only want to have one `go2rtc` instance running, how can I specify to disable the bundled instance and instead using a external one by specifying the URL?

3. To maintain the cameras only in one place, should I simply put the stream links from my go2rtc instance into the Frigate config? If so, how could I then switch between Main and Sub stream?

Sorry for asking possibly stupid basic questions but I'm really overwhelmed of all these options...

My target is just to don't waste CPU and memory resources, having a live stream with the Main stream in Home Assistant, a detection stream with the Sub stream within Frigate and also a recording stream with the Main stream in Frigate.

I don't explicitly need to run `go2rtc` as an additional docker container if I can use the bundled instance for Home Assistant, too.

**Comment by NickM-27** [comment]
1. when you configure go2rtc in frigate correctly it automatically adds the stream to the frigate integration in home assistant
2. you don't. You use the bundled instance and you setup the webrtc card integration to point to the bundled instance. 
3. you should do it all in the frigate config

**Comment by alve89** [comment]
> 2\. You use the bundled instance and you setup the webrtc card integration to point to the bundled instance.

I updated the `docker-compose.yml` file by adding `port 1984`:
```
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/bin/frigate/config:/config
      - /mnt/ssd/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"

  homeassistant.k41:
    container_name: homeassistant.k41
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /usr/local/bin/nginx/html/k41:/mnt/share
      - /usr/local/bin/hass/k41/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
```

I just added the new go2rtc URL (bundled in Frigate container) to the HA WebRTC integration:
![Bildschirmfoto 2024-04-24 um 21 15 29](https://github.com/blakeblackshear/frigate/assets/11487054/8152c8e4-e74f-4e0a-bb4a-f222d36b4ee9)

This seems to be successful:
![Bildschirmfoto 2024-04-24 um 21 16 07](https://github.com/blakeblackshear/frigate/assets/11487054/e17fb4c6-84ba-4636-90fb-2208ff4f7137)

Further I added a test camera in Frigate (I deliberately chose two different streams to check which is used where):
```
go2rtc:
  streams:
    cameraTest_main:
      - rtsp://user:pass@camera6.lan.k41/Preview_01_main
    cameraTest_sub:
      - rtsp://user:pass@camera7.lan.k41/Preview_01_sub

cameras:
  cameraTest:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/cameraTest_main
        roles:
        - record
      - path: rtsp://localhost:8554/cameraTest_sub
        roles:
        - detect
```

After saving the Frigate config the go2rtc service looked like this:

![Bildschirmfoto 2024-04-24 um 21 42 05](https://github.com/blakeblackshear/frigate/assets/11487054/1fce319c-8a09-4767-be8e-ac99a172988f)


After saving and restarting Frigate and afterwards restarting Home Assistant I got the cameras in HA:

![Bildschirmfoto 2024-04-24 um 21 43 22](https://github.com/blakeblackshear/frigate/assets/11487054/7ee06f05-536a-4dda-9e8d-9316fafe6045)



The only thing that is not working is the WebRTC card with the new camera:
![Bildschirmfoto 2024-04-24 um 21 44 07](https://github.com/blakeblackshear/frigate/assets/11487054/61a92b86-1f16-40d3-ab8b-0da0eecdecd1)


So: What did I miss?

**Reply by NickM-27** [reply]
your config is wrong, you need one of the streams (the one that is to be used for live in home assistant) to have a name that matches the camera name. Adding _main  confuses things

**Comment by alve89** [comment]
Thank you, I it is working now, but the cameras are duplicated (including `camera.`) in go2rtc - is this an expected behaviour?

![Bildschirmfoto 2024-04-26 um 12 58 24](https://github.com/blakeblackshear/frigate/assets/11487054/b23eda47-16b8-4d22-a666-d3020d112e1f)

```
go2rtc:
  streams:
    doorbell4:
      - rtsp://user:pass@doorbell.lan.k4
    doorbell41:
      - rtsp://user:pass@doorbell.lan.k41    

cameras:
  doorbell4:
    enabled: true
    detect:
      enabled: false
    record:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://localhost:8554/doorbell4
        roles:
        - record
  doorbell41:
    enabled: true
    detect:
      enabled: false
    record:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/doorbell41
          roles:
            - record
```
