### DISCUSSION TITLE
[Support]: Memory usage increases after "Detection appears to be stuck. Restarting detection process..."

### DISCUSSION THREAD

**Discussion by heisenberg2980** [blakeblackshear/frigate#11124] [General Support]
### Describe the problem you are having

I am running the latest version of Frigate (0.13.2-6476f8a) and every time the detection process is automatically restarted, the memory usage increases substantially, going from 6GB in my case to almost 8GB, and never returns to the normal value unless I manually restart it.

This is an example today at 8:33am:

2024-04-26 08:33:24.895755111  [2024-04-26 08:33:24] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2024-04-26 08:33:24.896393627  [2024-04-26 08:33:24] root                           INFO    : Waiting for detection process to exit gracefully...
2024-04-26 08:33:54.925579690  [2024-04-26 08:33:54] root                           INFO    : Detection process didnt exit. Force killing...
2024-04-26 08:33:54.935264185  [2024-04-26 08:33:54] root                           INFO    : Detection process has exited...
2024-04-26 08:33:56.113915319  [2024-04-26 08:33:56] detector.coral                 INFO    : Starting detection process: 316621
2024-04-26 08:33:56.166307226  [2024-04-26 08:33:56] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-04-26 08:33:59.394135217  [2024-04-26 08:33:59] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
image

P.S.: I am not sure why the detection gets stuck in the first place, as all my cameras are wired and my server is pretty stable, but that´s a different question

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: xxxxxxxxx
  user: xxxxxxxxx
  password: xxxxxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

objects:
  track:
    - person
    - cat
  filters:
    person:
      max_area: 125000
      threshold: 0.8
    cat:
      max_area: 30000
      threshold: 0.75

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  mode: continuous 
  width: 1920
  height: 1080


record:
  enabled: True
  retain:
    days: 30
  events:
    retain:
      default: 120

snapshots:
  retain:
    default: 120

detect:
  enabled: True
  width: 1280 
  height: 720 
  fps: 5
  stationary:
    interval: 150

motion:
  contour_area: 20
  mask:
    - 1236,29,1236,60,880,61,880,27

go2rtc:
  streams:
    dahua_1:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx1:554/cam/realmonitor?channel=1&subtype=0
    dahua_1_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx1:554/cam/realmonitor?channel=1&subtype=2
    dahua_2:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx2:554/cam/realmonitor?channel=1&subtype=0
    dahua_2_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx2:554/cam/realmonitor?channel=1&subtype=2
    dahua_3:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx3:554/cam/realmonitor?channel=1&subtype=0
    dahua_3_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx3:554/cam/realmonitor?channel=1&subtype=2
    dahua_4:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx4:554/cam/realmonitor?channel=1&subtype=0
    dahua_4_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx4:554/cam/realmonitor?channel=1&subtype=2
    dahua_5:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx5:554/cam/realmonitor?channel=1&subtype=0
    dahua_5_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx5:554/cam/realmonitor?channel=1&subtype=2
    dahua_6:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx6:554/cam/realmonitor?channel=1&subtype=0
    dahua_6_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx6:554/cam/realmonitor?channel=1&subtype=2
    dahua_7:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx7:554/cam/realmonitor?channel=1&subtype=0
    dahua_7_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx7:554/cam/realmonitor?channel=1&subtype=2
    dahua_8:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx8:554/cam/realmonitor?channel=1&subtype=0
    dahua_8_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx8:554/cam/realmonitor?channel=1&subtype=2
    dahua_9:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx9:554/live/main
    dahua_9_sub:
      - rtsp://view:xxxxxxxxxxxx@192.168.x.xx9:554/live/sub

cameras:

  dahua_1: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_1 
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 
      height: 1520 
      fps: 5
      stationary:
        interval: 150
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          threshold: 0.74
          mask:
            - 1449,1512,2688,1512,1848,888,1676,836
        car:
          min_area: 10000
          mask:
            - 0,0,611,0,607,160,0,334
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        - 930,1512,1905,1512,2075,1182,1590,983
        - 2014,704,2073,704,2153,336,2077,321
    zones:
      outside_main_door:
        coordinates: 714,538,0,691,0,1512,1168,1512,2161,1002,2237,785

  dahua_2: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_2 
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_2_sub 
          roles:
            - detect
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    motion:
      mask:
        - 1236,29,1236,60,880,61,880,27
        - 202,720,869,720,564,436,162,568
    objects:
      filters:
        person:
          min_score: 0.8

  dahua_3: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_3 
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 
      height: 1520 
      fps: 5
      stationary:
        interval: 150
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        - 2688,0,2688,281,2538,301,2103,160,2091,0
        - 2205,1520,1574,1143,951,1520
    objects:
      mask:
        - 142,241,663,109,1379,57,1392,0,91,0
      filters:
        person:
          max_area: 600000
        cat:
          max_area: 80000

  dahua_4: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_4 
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 
      height: 1520 
      fps: 5
      stationary:
        interval: 150
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
    objects:
      filters:
        person:
          threshold: 0.8

  dahua_5: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_5 
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 
      height: 1520 
      fps: 5
      stationary:
        interval: 150
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    motion:
      mask:
        - 2688,0,2688,932,1032,376,997,0
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          max_area: 600000
          threshold: 0.8
          mask:
            - 50,1450,200,1450,200,1200,50,1200

  dahua_6: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_6 
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 
      height: 1520 
      fps: 5
      stationary:
        interval: 150
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    zones:
      Worktop:
        coordinates: 1771,531,2688,865,2403,1520,1987,1520,1743,1520,2332,877,1654,599
      Island:
        coordinates: 954,726,1285,1022,1609,865,1207,654
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
    objects:
      filters:
        person:
          max_area: 600000
          threshold: 0.8
          mask:
            - 2201,797,2288,849,2192,971,2688,1195,2688,714,2267,546
        cat:
          max_area: 80000

  dahua_7: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_7 
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_7_sub 
          roles:
            - detect
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    objects:
      mask:
        - 0,0,0,409,43,498,220,374,184,0

  dahua_8: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_8 
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_8_sub 
          roles:
            - detect
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    objects:
      filters:
        person:
          threshold: 0.81
        cat:
          max_area: 30000
          threshold: 0.8

  dahua_9: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_9 
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 2688 
      height: 1520 
      fps: 5
      stationary:
        interval: 150
    record: 
      enabled: True
    snapshots: 
      enabled: True
    mqtt: 
      enabled: False
    motion:
      mask:
        - 426,29,426,60,80,61,80,27
```

### Relevant log output

```shell
2024-04-26 08:33:24.895755111  [2024-04-26 08:33:24] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2024-04-26 08:33:24.896393627  [2024-04-26 08:33:24] root                           INFO    : Waiting for detection process to exit gracefully...
2024-04-26 08:33:54.925579690  [2024-04-26 08:33:54] root                           INFO    : Detection process didnt exit. Force killing...
2024-04-26 08:33:54.935264185  [2024-04-26 08:33:54] root                           INFO    : Detection process has exited...
2024-04-26 08:33:56.113915319  [2024-04-26 08:33:56] detector.coral                 INFO    : Starting detection process: 316621
2024-04-26 08:33:56.166307226  [2024-04-26 08:33:56] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-04-26 08:33:59.394135217  [2024-04-26 08:33:59] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
image
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua HDW5442TM
