### DISCUSSION TITLE
[Config Support]: Stopping Letterbox detected as person

### DISCUSSION THREAD

**Discussion by cloudbr34k84** [blakeblackshear/frigate#11128] [Config Support] [answered]
### Describe the problem you are having

Im trying to stop my one of my cameras thinking my letterbox is a person
![image](https://github.com/blakeblackshear/frigate/assets/58960644/a57552fa-35e3-44bb-a71b-b8fa88fb35de)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
frigate_front_top_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://viewer:xxxxxxx@xxxxxxx:554/h264Preview_01_main
        input_args: preset-rtsp-restream
        roles:
        - record
        - rtmp
        - detect
      # - path: rtsp://viewer:xxxxxxxxxxxxx@xxxxxxxxxxxxxxx:554/h264Preview_01_sub
      #   input_args: preset-rtsp-restream
      #   roles:

    record:
      events:
        required_zones:
        - frigate_zone_front_top_front_patio_frontyard
        - frigate_zone_front_top_driveway_entrance

    snapshots:
      required_zones:
      - frigate_zone_front_top_front_patio_frontyard
      - frigate_zone_front_top_driveway_entrance

    zones:
      frigate_zone_front_top_front_patio_frontyard:
        coordinates: 491,720,798,296,450,255,237,246,241,288,347,395,232,505,133,618,245,720
        objects:
        - person
        - dog
        - cat
        - car
      frigate_zone_front_top_driveway_entrance:
        coordinates: 1189,385,1183,341,811,288,787,325
        objects:
        - person
        - dog
        - cat
        - car
      frigate_zone_front_top_driveway_parking_only:
        coordinates: 1207,720,492,720,764,347,1192,409
        objects:
        - person
        - dog
        - cat
        - car
    objects:
      filters:
        car:
          mask:
          - 0,223,89,212,143,213,211,194,302,319,332,393,0,720
        cat:
          mask:
        dog:
          mask:
        person:
          mask:
            - 557,451,567,335,553,329,502,346,526,450
```

### Relevant log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
This is a good candidate for an object mask

**Reply by cloudbr34k84** [reply]
is that what I have, or do need to actually create mask around the letterbox?

**Reply by cloudbr34k84** [reply]
Do i need the Object Filter code?
Also why is this even identifying as a person??

```
    objects:
      filters:
        car:
          mask:
          - 0,223,89,212,143,213,211,194,302,319,332,393,0,720
        cat:
          mask:
        dog:
          mask:
        person:
          mask:
          - 557,451,567,335,553,329,502,346,526,450
    motion:
        mask:
          - 528,452,568,451,567,325,500,339
  ```
