### DISCUSSION TITLE
[Config Support]: Stretched video feed

### DISCUSSION THREAD

**Discussion by wildchai** [blakeblackshear/frigate#11131] [Config Support] [answered]
### Describe the problem you are having

Hi,
I have a few cameras that is wall mounted and needed to rotate the lens physically 90degrees for a corridor format and using in camera settings to rotate the feed.

In frigate, the live view is stretched horizontally. What can I do to rectify this?

Thanks.

**Direct camera feed**
![Screenshot 2024-04-28 002026](https://github.com/blakeblackshear/frigate/assets/140302945/ce4aa9f2-fcbf-4509-8c20-32acfcd793e0)

**Frigate stretched**
![Screenshot 2024-04-28 001902](https://github.com/blakeblackshear/frigate/assets/140302945/3097df64-b2dd-4aeb-a0b4-cbb96baca397)

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: True
  # Required: host name
  host: 192.168.3.205
  # Optional: port (default: shown below)
  port: 1883
  user: **
  password: **
  
cameras:
  Right_Garden:
    ffmpeg:
      inputs:
        - path: rtsp://user@pass@192.168.3.62/axis-media/media.amp?videocodec=h264
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - dog
        - cat
    detect:
      height: 1080
      width: 1920
      fps: 5
```

### Relevant log output

```shell
none
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Camera setting to rotate the video 90degrees

![Screenshot 2024-04-28 003842](https://github.com/blakeblackshear/frigate/assets/140302945/beb0bfc1-0c3a-430e-be45-b701a7dda17c)
