### DISCUSSION TITLE
[HW Accel Support]: No HW Accel Support under windows->wsl2

### DISCUSSION THREAD

**Discussion by exmatador** [blakeblackshear/frigate#11133] [Hardware Acceleration Support]
### Describe the problem you are having

I'm using windows 11 with wsl2 (Ubuntu-22.04)
graphics card is Intel Iris(R) Xe Graphics.
Therefor the d3d12 driver:
LIBVA_DRIVER_NAME: d3d12
LIBVA_DRIVERS_PATH: /usr/lib/x86_64-linux-gnu/dri

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt: 
  enabled: True
  host: 192.168.178.43
  port: 1885              # Standard mqtt-Port ist 1883, darauf hört bei den ESPxx auch mosquitto, der es dann an den ioBroker.mqtt-client weitergibt (auch 1883)
                          # ioBroker.frigate hat einen eigenen mqtt-client, der nur auf 1885 hört
  topic_prefix: frigate

# ffmpeg:
#  global_args: -display drm
#  hwaccel_args: preset-vaapi   #preset-intel-qsv-h264 
ffmpeg:
  hwaccel_args: preset-vaapi 

environment_vars:
  LIBVA_DRIVER_NAME: d3d12
  LIBVA_DRIVERS_PATH: /usr/lib/x86_64-linux-gnu/dri

logger:
  # Optional: default log level (default: shown below)
  default: info
  logs:
    frigate.comms.mqtt: debug

birdseye:
  enabled: True
  width: 1280
  height: 720
  mode: continuous
  # layout:
  #  scaling_factor: 2.0

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc: 
  #log:
  #  exec: trace

  streams: 
    #----- Output ist MJPEG, Video.Transkodierung in H.264, Audio.Transkodierung in OPUS oder AAC
    InnenCAM_EG: 
    # - rtsp://admin:L2793226@192.168.178.84:554/cam/realmonitor?channel=1&subtype=0#video=h264#audio=opus
    - rtsp://admin:L2793226@192.168.178.84:554/cam/realmonitor?channel=1&subtype=1#audio=aac
    #  "ffmpeg:InnenCAM#video=h264#audio=aac"
  
    InnenCAM_OG: 
    - rtsp://admin:m13m27h03t09@192.168.178.90:554/cam/realmonitor?channel=1&subtype=1&proto=Onvif

    #----- Output ist JPEG, Video.Transkodierung in H.264, kein Audio vorhanden
    3D-Printer:
    - ffmpeg:http://192.168.178.74:81/stream#video=h264
  
    #----- Output ist JPEG, Video.Transkodierung in H.264, kein Audio vorhanden
    Gaestezimmer:
    - ffmpeg:http://192.168.178.69:81/stream#video=h264
  
    #----- Alle 4 LE232 Konfiguration: Video: H.264  Audio: AAC  (keine Transkodierung erforderlich)
    #      Alle 4 können den neuen Video-Standard H.265, das kann go2RTC aber nicht
    #      WebRTC kann AAC | OPUS | PCM   
    #      MSE    kann       OPUS | PCM 
    #      MJPEG  kann AAC        | PCM
    Eingang:
    - rtsp://admin:m13m27h03t09@192.168.178.38:554/Port/cam/realmonitor?channel=1&subtype=1
    # ffmpeg:https://admin:m13m27h03t09@192.168.178.38/cgi-bin/mjpg/video.cgi?channel=1&subtype=1#video=h264#audio=opus
    Terrasse:
    - rtsp://admin:m13m27h03t09@192.168.178.39:554/Port/cam/realmonitor?channel=1&subtype=1
    Garten:
    - rtsp://admin:m13m27h03t09@192.168.178.40:554/Port/cam/realmonitor?channel=1&subtype=1
    Garage:
    - rtsp://admin:m13m27h03t09@192.168.178.41:554/Port/cam/realmonitor?channel=1&subtype=1
  
  #----- Transkodierung hat 2 Varianten
  # - ffmpeg:https://admin:m13m27h03t09@192.168.178.38/cgi-bin/mjpg/video.cgi?channel=1&subtype=1
  # - "ffmpeg:Eingang#video=h264"
  webrtc:
    candidates:
      - 192.168.178.43:8555
      - stun:8555

cameras:
  Eingang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5           

  Terrasse:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Terrasse
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5

  Garten:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5

  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5

  InnenCAM_EG:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/InnenCAM_EG
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      enabled: False

  InnenCAM_OG:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/InnenCAM_OG
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      enabled: False

  #3D-Printer:
  #  ffmpeg:
      #inputs:
      #  - path: rtsp://192.168.178.43:8554/3D-Printer   #http://192.168.178.74:81/stream
      #    roles:
      #      - detect
      #      - record
      #input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      #output_args:
      #  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
      #  rtmp: -c:v libx264 -an -f flv
    #rtmp:
    #  enabled: True

  3D-Printer:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/3D-Printer
          input_args: preset-rtsp-generic
          roles:
            - detect  
    detect:
      enabled: False            

  Gaestezimmer:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Gaestezimmer
          input_args: preset-rtsp-generic
          roles:
            - detect  
    detect:
      enabled: False  

objects:
  track:
    - person
    # - car

record:
  enabled: True
  retain:
    days: 0                  # Keine Standard-Aufzeichnung, nur im Falle von events
  events:
    retain:
      default: 10            # 10 Tage aufbewahren
      mode: active_objects   # motion: bei jeder Bewegung   # active_objects: nur bei Bewegung eines der Objekttypen (person, car)

# detect:                    # nur an der Kamera selbst angeben, nicht global für alle
#  enabled: false
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    
    # deploy:    # <------------- Add this section
    #  resources:
    #    reservations: 
    #      devices:
    #        - driver: dxgkrnl
    #          device_ids: ['3'] # this is only needed when using multiple GPUs
              #count: all # number of GPUs
              #capabilities: [gpu]
    
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video
    volumes:
      - \\wsl$$\Ubuntu-22.04\etc\localtime:/etc/localtime:ro
      - \\wsl$$\Ubuntu-22.04\home\michael\frigate\config.yml:/config/config.yml
      - \\wsl$$\Ubuntu-22.04\home\michael\frigate\clips:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554/tcp" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      # LIBVA_DRIVER_NAME: libd3d12.so
      # LIBVA_DRIVERS_PATH: /usr/lib/wsl/lib
      
      LIBVA_DRIVER_NAME: d3d12
      LIBVA_DRIVERS_PATH: /usr/lib/x86_64-linux-gnu/dri
      display: ':0'
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
2024-04-27 21:15:32 2024-04-27 21:15:32.765690875  [2024-04-27 21:15:32] watchdog.Eingang               ERROR   : Ffmpeg process crashed unexpectedly for Eingang.
2024-04-27 21:15:32 2024-04-27 21:15:32.765797367  [2024-04-27 21:15:32] watchdog.Eingang               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-04-27 21:15:32 2024-04-27 21:15:32.765877090  [2024-04-27 21:15:32] ffmpeg.Eingang.detect          ERROR   : [AVHWDeviceContext @ 0x55675a79f240] libva: /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so init failed
2024-04-27 21:15:32 2024-04-27 21:15:32.765965737  [2024-04-27 21:15:32] ffmpeg.Eingang.detect          ERROR   : [AVHWDeviceContext @ 0x55675a79f240] Failed to initialise VAAPI connection: 2 (resource allocation failed).
2024-04-27 21:15:32 2024-04-27 21:15:32.766138572  [2024-04-27 21:15:32] ffmpeg.Eingang.detect          ERROR   : Device creation failed: -5.
2024-04-27 21:15:32 2024-04-27 21:15:32.766140775  [2024-04-27 21:15:32] ffmpeg.Eingang.detect          ERROR   : [h264 @ 0x55675a79a040] No device available for decoder: device type vaapi needed for codec h264.
2024-04-27 21:15:32 2024-04-27 21:15:32.766142498  [2024-04-27 21:15:32] ffmpeg.Eingang.detect          ERROR   : Device setup failed for decoder on input stream #0:0 : Input/output error
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x563df9c18a80] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/Eingang':
  Metadata:
    title           : go2rtc/1.8.4
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 704x576, 25 fps, 25 tbr, 90k tbn, 50 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Windows

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW3449T1P-AS-PV-S2 

### Any other information that may be helpful

VAINFO within Frigate WebUI

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'd3d12'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva error: /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
