### DISCUSSION TITLE
RPI4 Google Coral USB Performance

### DISCUSSION THREAD

**Discussion by cigas4** [blakeblackshear/frigate#1113] [General]
Hello,

I am running Frigate container on RPI4 together with 3 IP cameras. To improve performance I have ordered and installed Google Coral USB accelerator, but for some reason I do not see any inprovement or a dropdown of cpu load on my rpi4..
Coral seems to be recognized by the frigate but I dont see any efect when it is there, compared to bare rpi4.
Do I need to make some configurations or drivers setup on rpi to use coral?

My docker compose config:

```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    devices:
      - /dev/bus/usb:/dev/bus/usb  
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/Downloads/frigate/frigate.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935'
    environment:
      FRIGATE_RTSP_PASSWORD: 'pass'
```

See CPU uage graphs for both using cpu and coral detectors, cpu usage looks almost identical.

Coral USB detector
<img width="964" alt="Screenshot 2021-05-16 at 16 44 51" src="https://user-images.githubusercontent.com/54658863/118465835-f604d580-b70a-11eb-9784-59c337fde269.png">
<img width="964" alt="Screenshot 2021-05-16 at 16 48 48" src="https://user-images.githubusercontent.com/54658863/118465861-fef5a700-b70a-11eb-8f5c-d06fb4bbf7d0.png">
<img width="2298" alt="Screenshot 2021-05-16 at 16 49 42" src="https://user-images.githubusercontent.com/54658863/118465903-061cb500-b70b-11eb-9dcd-000313ae67e3.png">

RPI4 CPU1&CPU2 detector
<img width="921" alt="Screenshot 2021-05-17 at 08 31 50" src="https://user-images.githubusercontent.com/54658863/118466326-6ca1d300-b70b-11eb-8f56-377bcb1344b0.png">
<img width="989" alt="Screenshot 2021-05-16 at 16 53 09" src="https://user-images.githubusercontent.com/54658863/118466327-6ca1d300-b70b-11eb-9a38-77811fa9250e.png">
<img width="2237" alt="Screenshot 2021-05-16 at 16 54 28" src="https://user-images.githubusercontent.com/54658863/118466344-70cdf080-b70b-11eb-890a-680666a5ab7e.png">
