### DISCUSSION TITLE
POST /api/events/  recording outside of detection - Home Assistant How To

### DISCUSSION THREAD

**Discussion by zaPure** [blakeblackshear/frigate#11139] [General]
I wanted to share how to trigger a recording using an external event from home assistant.
I have a set of outside alarm beams, that if triggered at night, I would like Frigate to record and create an event.

This uses the post-event API.
https://docs.frigate.video/integrations/api#post-apieventscamera_namelabelcreate.

The easiest way to make this work is in your home assistant is to use the RESTful Command 
https://www.home-assistant.io/integrations/rest_command

In your home assistant configuration file add the following lines
```css
rest_command:
  frigate_force_shed:
    url: "http://192.168.12.20:5000/api/events/Shed/forced/create"
    method: post
    content_type: "application/json"
  frigate_force_courtyard:
    url: "http://192.168.12.20:5000/api/events/Courtyard/forced/create"
    method: post
    content_type: "application/json"
``` 

Then in Home Assistant, you can create an automation that calls a service - selecting which camera you want to force record.
e.g.

![image](https://github.com/blakeblackshear/frigate/assets/92331689/cabae0a1-577e-477f-ace6-c304e918923a)

Hope this helps anybody else who has been struggling

**Comment by tubalainen** [comment]
Ive got another take om the same automation.

Here is my example:
```
## configuration.yaml
shell_command:
  alert_bi: "curl -d {{ url }}"
 
## automation
- id: motion_framsidan_send_to_frigate
  alias: "Motion framsidan send to frigate"
  initial_state: 'on'
  trigger:
    - entity_id: binary_sensor.shelly_19_switch
      platform: state
      to: 'on'
      id: "pir_uppfarten"
    - entity_id: binary_sensor.shelly_12_switch
      platform: state
      to: 'on'
      id: "pir_framsidan"
    - entity_id: binary_sensor.motion_sensor_ytterdorr_groventren_occupancy
      platform: state
      to: 'on'
      id: "pir_groventren"
    - entity_id: binary_sensor.postinkast
      platform: state
      to: 'on'
      id: "mailbox_delivery"
    - entity_id: binary_sensor.posttomning
      platform: state
      to: 'on'
      id: "mailbox_empty"
  condition: []
  action:
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam9_uppfart/{{ trigger.id }}/create'
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam1_framsidan/{{ trigger.id }}/create'
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam3_framsidan/{{ trigger.id }}/create'
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam6_lekstugan/{{ trigger.id }}/create'
 
- id: motion_baksidan_send_to_frigate
  alias: "Motion baksidan send to frigate"
  initial_state: 'on'
  trigger:
    - entity_id: binary_sensor.shellymotionsensor_60a42397547c_motion
      platform: state
      to: 'on'
      id: "pir_redskapsboden"
    - entity_id: binary_sensor.shellymotionsensor_60a42397547c_vibration
      platform: state
      to: 'on'
      id: "vibration_redskapsboden"
    - entity_id: binary_sensor.shellymotion02_motion
      platform: state
      to: 'on'
      id: "pir_vedboden"
    - entity_id: binary_sensor.shellymotion02_vibration
      platform: state
      to: 'on'
      id: "vibration_vedboden"
  condition: []
  action:
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam12_baksidan/{{ trigger.id }}/create'
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam2_baksidan/{{ trigger.id }}/create'
    - service: shell_command.alert_bi
      data_template:
        url: '"sub_label=external&duration=30&include_recording=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:5000/api/events/cam10_baksidan/{{ trigger.id }}/create'
```

**Comment by tubalainen** [comment]
Here is a new version of a HA package file to align with the removal of "application/x-www-form-urlencoded" in the API with version 0.15.0 beta1.

Thanks to to my Friend Robin for helping with the rest syntax.

## packages/frigate_external_events.yaml

```
automation:
  - id: motion_framsidan_send_to_frigate
    alias: "Motion framsidan send to frigate"
    initial_state: on
    trigger:
      - entity_id: binary_sensor.shelly_19_switch
        trigger: state
        to: 'on'
        id: "pir_uppfarten"
      - entity_id: binary_sensor.postinkast
        trigger: state
        to: 'on'
        id: "mailbox_delivery"
      - entity_id: binary_sensor.posttomning
        trigger: state
        to: 'on'
        id: "mailbox_empty"
    condition: []
    action:
      - action: rest_command.frigate_create_event
        data:
          camera_name: "cam3_framsidan"
          label: "{{ trigger.id }}"
          score: 9
          duration: 30
          include_recording: false
      - action: rest_command.frigate_create_event
        data:
          camera_name: "cam6_lekstugan"
          label: "{{ trigger.id }}"
          score: 9
          duration: 30
          include_recording: false
      - action: rest_command.frigate_create_event
        data:
          camera_name: "cam9_uppfart"
          label: "{{ trigger.id }}"
          score: 9
          duration: 30
          include_recording: false

rest_command:
  # data variables:
  #   camera_name
  #   label
  #   source_type
  #   sub_label
  #   score
  #   duration
  #   include_recording
  frigate_create_event:
    url: http://ip_and_port/api/events/{{ camera_name }}/{{ label }}/create
    method: POST
    content_type: "application/json"
    timeout: 5
    payload: >-
      {
        "score": "{{ int(score, 0) }}",
        "duration": "{{ int(duration, 30) }}",
        "include_recording": "{{ 'true' if bool(include_recording, True) else 'false' }}",
        "draw": {}
      }
```

**Reply by alexhk90** [reply]
Thanks for this! 

I'm not sure if it's because I'm on Frigate 0.14.1-f4f3cfa (not 0.15.0), but I had to change the "duration" element to not have quotes around it: 
`        "duration": {{ int(duration, 30) }},`
Otherwise for me it would returns: 
```
content:
  message: An unknown error occurred
  success: false
status: 500
```
With the following in the Frigate logs: 
- Tag: `frigate.api.event`
- Message: `unsupported operand type(s) for +: 'float' and 'str'`

As noted below, for 0.14.1 I also needed to remove "source_type" (or set it explicitly to the default of "api") to have the event create a corresponding review.
