### DISCUSSION TITLE
[Config Support]: Help needed to configure detection inside a zone

### DISCUSSION THREAD

**Discussion by Jebarson** [blakeblackshear/frigate#11164] [General Support]
### Describe the problem you are having

Hey  folks,

I am try to set up the configuration for the below.

1. Record everything.
2. Track only person in all the visible area in the camera.
3. Track the objects of interest in the zones that i have specified. 

I tried by keeping only person in the objects->track. However I am encountering error stating that the object I have mentioned in the zone is not mentioned in track. I believe, I am approaching this wrong. Can someone help me on I get the above accomplished?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant.local
  port: 1883
  user: mqtt
  password: mqttPr0gr@mm3r

detect:
  enabled: true
  fps: 5
  max_disappeared: 75 # 15 seconds considering 5 fps
record:
  enabled: true
  retain:
    days: 8

cameras:
  Camera_1:
    enabled: true
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
      - -c:v
      - h264_cuvid
      inputs:
      - path: rtsp://admin:BadPr0gramm3r@20.0.0.12:554/Preview_01_main
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://admin:BadPr0gramm3r@20.0.0.12:554/Preview_01_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    objects:
      track:
        - person
        - hat
        - cat
        - dog
        - bear
        - sheep
        - horse
        - bird
    zones:
      Front:
        coordinates: 89,0,145,58,210,107,414,227,443,181,548,229,640,301,640,360,0,360,0,0
        objects:
          - person
          - hat
          - cat
          - dog
          - bear
          - sheep
          - horse
          - bird
go2rtc:
  streams:
    Camera_1:
    - rtsp://admin:BadPr0gramm3r@20.0.0.12:554/Preview_01_sub
    - ffmpeg:Camera_1#video=h264#audio=aac
    Camera_2:
    - rtsp://admin:BadPr0gramm3r@20.0.0.13:554/Preview_01_sub
    - ffmpeg:Camera_2#video=h264#audio=aac
```

### Relevant log output

```shell
Zone is configured to track hat but that object type is not added to objects ->
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink
