### DISCUSSION TITLE
Recordings disappearing after frigate restart

### DISCUSSION THREAD

**Discussion by jsapede** [blakeblackshear/frigate#11178] [General Support] [answered]
### Describe the problem you are having

I use frigate with two configs : 1 config with an external hikvision doorbell cam and 1 config with the dorbell cam + 3 interior TAPO C210 cams

To stop permanent flow decoding i made a switch inside homeassistant witch : 
1/ with ssh turns down frigate docker compose
2/ inside HA using the TAPO integration, blinds cameras in privacy mode
3/ with ssh copy one or the other configs to config.yaml
3/ with ssh restart frigate docker compose

si i can, in seconds, switch to a low config with 1 cam to a full config with 4 cams.

Everythings seems to work well but ... when i switch from the 4 cams config, to the 1 cam config, all recordings from the 3 interior tapo cams are deleted.

Detections are still visible in the events timeline : 

![image](https://github.com/blakeblackshear/frigate/assets/66303110/822b4716-d0be-4aec-a752-5b0931c00c0d)

snapshots are available : 

![image](https://github.com/blakeblackshear/frigate/assets/66303110/60cc7879-3dbf-40b9-ba23-a117a93d8301)

but no recordings : 

![image](https://github.com/blakeblackshear/frigate/assets/66303110/f08c80e1-c946-480c-87e6-2e6749867500)

all the media are stored on a synology NAS with NFS mount inside the docker compose. 

when lookin inside the NAS folders, one can see that the recordings for the 3 interior cameras are not stored. Only remains the recordings of the external camera. 

When i run with the 4 cameras configs, recordings are available in the timeline, but as soon as i switch to the single cam config, they all become unavailable except the external camera witch is still there ! 

Cant find where's the problem

More strange is that files are effectively recorded on the nas when the 4 cam config is used : 

![image](https://github.com/blakeblackshear/frigate/assets/66303110/694da479-052b-4247-a11f-f1bb32a9a364)

but are deleted when i switch back to the 1cam config

 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# FULL

###################
# Définition MQTT #
###################
mqtt:
  host: 192.168.0.32
  port: 1883
  user: mqtt_login
  password: mqtt_pass

#####################
# Reglages Birdseye #
#####################
birdseye:
# déasactivé par défaut #
  enabled: false
  mode: objects
  width: 1280
  height: 720
  quality: 24

environment_vars:
  LIBVA_DRIVER_NAME: iHD

###################
# Défition GO2RTC #
###################
go2rtc:
  streams:
    Salon:
      - tapo://xxxxxx@192.168.0.123
      - ffmpeg:Salon#audio=aac

    Cuisine:
      - tapo://xxxxxx@192.168.0.122
      - ffmpeg:Cuisine#audio=aac

    Mezzanine:
      - tapo://xxxxxx@192.168.0.130
      - ffmpeg:Mezzanine#audio=aac

    Portail:
      - rtsp://xxxx:xxxxx@192.168.0.186:554/Streaming/Channels/101
      - ffmpeg:Portail#audio=aac
      - isapi://xxxx:xxxx@192.168.0.186:80/


# Serveur WEBRTC #
  webrtc:
    listen: ":8555"
    candidates:
      - xx.xX.XX.XX:8555


##################
# Presets FFMPEG #
##################
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy
    detect: -threads 4 -f rawvideo -pix_fmt yuv420p

##############
# Détecteurs #
##############
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /config/models/yolov8s-320/yolov8s.xml
model:  
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /config/models/yolov8s-320/coco_80cl.txt

####################
# options SNAPSHOT #
####################
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  quality: 95
  retain:
    default: 7

##################
# Options record #
##################
record:
  enabled: true
  expire_interval: 10
  sync_recordings: True
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 7
      mode: active_objects
    objects:
      - person
      - meow
      - cat
      - speech
##################
# Options Detect #
##################

detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5
  stationary:
    interval: 50
    threshold: 50

##################
# options motion #
##################

motion:
  threshold: 50
  lightning_threshold: 0.6
  contour_area: 30
  improve_contrast: false


# options audio #

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 200
  listen:
    - speech
    - bark
    - meow
    - scream
    - yell
    - fire_alarm
    - dog
    - cat
  filters:
    speech:
      threshold: 0.8



######################
# Definition cameras #
######################

cameras:
  Cuisine:
    enabled: true
    onvif:
      host: 192.168.0.122
      port: 2020
      user: xxxx
      password: xxx
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Cuisine
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.9
          min_area: 40000
        cat:
          threshold: 0.8
          min_area: 2000
          max_area: 20000
        dog:
          threshold: 0.8
          min_area: 2000
          max_area: 20000
    motion:
      mask:
        - 157,332,185,328,186,299,152,302
  Salon:
    enabled: true
    onvif:
      host: 192.168.0.123
      port: 2020
      user: xxxx
      password: xxxxx
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Salon
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.9
          min_area: 40000
        cat:
          threshold: 0.8
          min_area: 2000
          max_area: 20000
        dog:
          threshold: 0.8
          min_area: 2000
          max_area: 20000


  Mezzanine:
    enabled: true
    onvif:
      host: 192.168.0.130
      port: 2020
      user: xxxx
      password: xxxxx
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args: preset-rtsp-restream-low-latency
      inputs:
        - path: rtsp://127.0.0.1:8554/Mezzanine
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.9
          min_area: 40000
        cat:
          threshold: 0.8
          min_area: 5000
          max_area: 30000
        dog:
          threshold: 0.8
          min_area: 5000
          max_area: 30000


  Portail:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args: preset-rtsp-restream-low-latency
      inputs:
        - path: rtsp://127.0.0.1:8554/Portail
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - car
      filters:
        person:
          threshold: 0.9
          min_area: 150000
        car:
          threshold: 0.9
          min_area: 50000
          #max_area: 170000
```

### Relevant log output

```shell
2024-04-30 17:44:26.848988780  [INFO] Preparing Frigate...
2024-04-30 17:44:26.872598239  [INFO] Starting Frigate...
2024-04-30 17:44:28.387557351  [2024-04-30 17:44:28] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-04-30 17:44:28.418426571  [2024-04-30 17:44:28] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-04-30 17:44:28.426956307  [2024-04-30 17:44:28] peewee_migrate.logs            INFO    : Starting migrations
2024-04-30 17:44:28.431689290  [2024-04-30 17:44:28] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-04-30 17:44:28.437220728  [2024-04-30 17:44:28] frigate.app                    INFO    : Recording process started: 297
2024-04-30 17:44:28.440159987  [2024-04-30 17:44:28] frigate.app                    INFO    : go2rtc process pid: 89
2024-04-30 17:44:28.475879818  [2024-04-30 17:44:28] detector.ov                    INFO    : Starting detection process: 307
2024-04-30 17:44:28.479994757  [2024-04-30 17:44:28] frigate.app                    INFO    : Output process started: 309
2024-04-30 17:44:28.514306749  [2024-04-30 17:44:28] frigate.app                    INFO    : Camera processor started for Portail: 317
2024-04-30 17:44:28.522567889  [2024-04-30 17:44:28] frigate.app                    INFO    : Capture process started for Portail: 318
2024-04-30 17:44:28.530539352  [2024-04-30 17:44:28] frigate.app                    INFO    : Audio process started: 322
2024-04-30 17:44:28.942734986  [2024-04-30 17:44:28] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,3,320,320]
2024-04-30 17:44:28.943253479  [2024-04-30 17:44:28] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,84,2100]
2024-04-30 17:44:28.943581399  [2024-04-30 17:44:28] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2024-04-30 17:46:29.050119229  [2024-04-30 17:46:29] frigate.http                   ERROR   : No recordings found for the requested time range
2024-04-30 17:46:29.413157594  [2024-04-30 17:46:29] frigate.http                   ERROR   : No recordings found for the requested time range
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
  "cameras": {
    "Portail": {
      "audio_dBFS": -72.2533,
      "audio_rms": 7.9944,
      "camera_fps": 5,
      "capture_pid": 318,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 324,
      "pid": 317,
      "process_fps": 5,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "18": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "44": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "83": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "102": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "112": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.8",
      "cpu_average": "1",
      "mem": "0.5"
    },
    "119": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "137": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "138": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "139": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "141": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "142": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "295": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "297": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "306": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(43)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "307": {
      "cmdline": "frigate.detector.ov  ",
      "cpu": "0.0",
      "cpu_average": "8",
      "mem": "1.5"
    },
    "309": {
      "cmdline": "frigate.output       ",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "312": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "317": {
      "cmdline": "frigate.process:Portail",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "318": {
      "cmdline": "frigate.capture:Portail",
      "cpu": "1.2",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "322": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "324": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 4 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/Portail -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Portail@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 4 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.5",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "332": {
      "cmdline": "ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/Portail -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "353": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/Portail?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/03cc0095d32c7d42daf6b679f3580bdf",
      "cpu": "1.5",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "820": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "ov": {
      "detection_start": 0,
      "inference_speed": 97.72,
      "pid": 307
    }
  },
  "gpu_usages": {
    "intel-qsv": {
      "gpu": "1.58%",
      "mem": "-%"
    }
  },
  "processes": {
    "audioDetector": {
      "pid": 322
    },
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 295
    },
    "recording": {
      "pid": 297
    }
  },
  "service": {
    "last_updated": 1714492150,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 253.8,
        "mount_type": "tmpfs",
        "total": 256,
        "used": 2.2
      },
      "/media/frigate/clips": {
        "free": 1134929.8,
        "mount_type": "nfs4",
        "total": 1873147.1,
        "used": 738117.4
      },
      "/media/frigate/recordings": {
        "free": 1134929.8,
        "mount_type": "nfs4",
        "total": 1873147.1,
        "used": 738117.4
      },
      "/tmp/cache": {
        "free": 1021.4,
        "mount_type": "tmpfs",
        "total": 1024,
        "used": 2.6
      }
    },
    "temperatures": {

    },
    "uptime": 282,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

hikvision DVE 8113 / TAPO C210

### Any other information that may be helpful

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "256mb" # update for your cameras based on calculation above
    group_add:
      - "44"
      - "106"
      - "29"
      - "103"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1G
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

**Comment by jsapede** [comment]
for the 1 camera config 1 simply remove the 3 tapo cams from go2rtc and from camera definitions

**Comment by NickM-27** [comment]
you are removing the cameras so hence frigate is removing the recordings because the camera does not exist anymore. Switching between configs like this is not really supported. You would be better off including all cameras in a single config but only enabling some of the cameras

**Reply by jsapede** [reply]
as far as i remember i've read somewhere here that it wasnt possible to completely turn off cameras from go2rtc and frigate once it's running. 
Did i missed a feature ? 
and what is the point of removing recordings if the cameras are no more here ? if one of the cams becomes wrecked, all recordigns will be deleted ?

**Reply by NickM-27** [reply, marked as answer]
you can't do it dynamically, you can do it using the config

```
cameras:
  on_cam:
    enabled: true
  off_cam:
    enabled: false
```

> and what is the point of removing recordings if the cameras are no more here ? if one of the cams becomes wrecked, all recordigns will be deleted ?

the camera was removed from the config, it has no retention period configured anymore so keeping it around would just be dead space for a camera that can not be accessed from the webUI. A camera becoming "wrecked" is irrelevant because it would still be in the config. This only happens when a user changes their config to not include a camera anymore which means that camera does not exist
