### DISCUSSION TITLE
[Config Support]: FFMPEG is crashing my intel NUC due to high memory issues

### DISCUSSION THREAD

**Discussion by emile-bodin** [blakeblackshear/frigate#11189] [Config Support]
### Describe the problem you are having

i'm running home assistant supervised 2024.04.4 with the frigate addon 0.13.2 (full access) with protection mode off
It is running on:

- Intel NUC 
- 4 cores Intel(R) Core(TM) i5-4250U
- 8gb ram
- nvme SSD

I have setup a nest camera with the google nest integration and passing the stream trough the internal go2rtc
Now some minutes after starting frigate this is causing the intel nuc to go to 100% memory usage, and grinding the system to a halt.

![image](https://github.com/blakeblackshear/frigate/assets/2363359/0d5e1959-94c4-41b5-879a-aa0bc11dee7c)

I initially thought it might be the detection mode, but after disabling it via the frigate mqtt integration, it also went again to 100% memory usage
![image](https://github.com/blakeblackshear/frigate/assets/2363359/3d226590-f561-4b2a-aefa-5bdce46a2486)

I really could use some insights here

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.86.104
  user: frigate
  password: nestcam

# recordings
record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: motion

# global ffmpeg
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-vaapi

go2rtc:
  hass:
    config: "/config"
  streams:
    hass-achtertuin:
      - hass://supervisor?entity_id=camera.achtertuin

# cameras
cameras:
  hass-achtertuin: # <--- this will be changed to your actual camera later
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hass-achtertuin?mp4
          input_args: preset-rtsp-restream
          roles:
            - record
    # objects:
    #   track:
    #     - person
    #     - dog
    # motion:
    #   mask:
    #   - 116,192,668,78,678,25,109,85
```

### Relevant log output

```shell
2024-05-01 11:45:47.040782776  [INFO] Preparing new go2rtc config...
2024-05-01 11:45:47.107233402  [INFO] Got IP address from supervisor: 192.168.86.104
2024-05-01 11:45:47.164995984  [INFO] Got WebRTC port from supervisor: 8555
2024-05-01 11:45:47.828836411  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2024-05-01 11:45:47.828844682  [INFO] Starting go2rtc...
2024-05-01 11:45:47.933630642  13:45:47.933 INF go2rtc version 1.8.5 linux/amd64
2024-05-01 11:45:47.934529168  13:45:47.934 INF [api] listen addr=:1984
2024-05-01 11:45:47.934556813  13:45:47.934 INF [rtsp] listen addr=:8554
2024-05-01 11:45:47.934827403  13:45:47.934 INF [webrtc] listen addr=:8555
2024-05-01 11:45:56.952289021  [INFO] Starting go2rtc healthcheck service...

2024-05-01 11:45:46.950530894  [INFO] Preparing Frigate...
2024-05-01 11:45:47.041276553  [INFO] Starting Frigate...
2024-05-01 11:45:50.236242838  [2024-05-01 13:45:50] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-05-01 11:45:50.236424460  [2024-05-01 13:45:50] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-05-01 11:45:53.548208913  [2024-05-01 13:45:53] peewee_migrate.logs            INFO    : Starting migrations
2024-05-01 11:45:53.570332978  [2024-05-01 13:45:53] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-01 11:45:53.615846784  [2024-05-01 13:45:53] frigate.app                    INFO    : Recording process started: 319
2024-05-01 11:45:53.619917331  [2024-05-01 13:45:53] frigate.app                    INFO    : go2rtc process pid: 87
2024-05-01 11:45:53.646061683  [2024-05-01 13:45:53] detector.cpu                   INFO    : Starting detection process: 329
2024-05-01 11:45:53.662438743  [2024-05-01 13:45:53] frigate.app                    INFO    : Output process started: 331
2024-05-01 11:45:53.662921873  [2024-05-01 13:45:53] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-05-01 11:45:53.701077474  [2024-05-01 13:45:53] frigate.app                    INFO    : Camera processor not started for disabled camera hass-achtertuin
2024-05-01 11:45:53.701388612  [2024-05-01 13:45:53] frigate.app                    INFO    : Capture process not started for disabled camera hass-achtertuin
2024-05-01 11:46:25.170393058  [2024-05-01 13:46:25] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied)
2024-05-01 11:46:25.170398810  
2024-05-01 11:47:03.853786238  [2024-05-01 13:47:03] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied)
2024-05-01 11:47:03.853792841
```

### Frigate stats

```json
{
  "cameras": {
    "hass-achtertuin": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 0,
      "capture_pid": null,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 0,
      "pid": null,
      "process_fps": 0,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "79": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "87": {
      "cmdline": "/config/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "108": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "110": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.9",
      "cpu_average": "3",
      "mem": "2.3"
    },
    "122": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "149": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "150": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "151": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "305": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.3"
    },
    "319": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "1.4"
    },
    "328": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "329": {
      "cmdline": "frigate.detector.cpu ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "1.5"
    },
    "331": {
      "cmdline": "frigate.output       ",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "1.5"
    },
    "334": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "335": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "441": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "cpu": {
      "detection_start": 0,
      "inference_speed": 10,
      "pid": 329
    }
  },
  "gpu_usages": {
    "error-gpu": {
      "gpu": -1,
      "mem": -1
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 87
    },
    "logger": {
      "pid": 305
    },
    "recording": {
      "pid": 319
    }
  },
  "service": {
    "last_updated": 1714564074,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 3936.3,
        "mount_type": "tmpfs",
        "total": 3936.8,
        "used": 0.5
      },
      "/media/frigate/clips": {
        "free": 65293.8,
        "mount_type": "ext4",
        "total": 111142.2,
        "used": 40157.6
      },
      "/media/frigate/recordings": {
        "free": 65293.8,
        "mount_type": "ext4",
        "total": 111142.2,
        "used": 40157.6
      },
      "/tmp/cache": {
        "free": 3936.8,
        "mount_type": "tmpfs",
        "total": 3936.8,
        "used": 0
      }
    },
    "temperatures": {

    },
    "uptime": 121,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
might be good to try updating to go2rtc 1.9.0 as it has some fixes for the nest camera https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by emile-bodin** [comment]
hmm that might be a good catch, ill give it a try.

**Comment by emile-bodin** [comment]
I started using the custom version from go2rtc

```
2024-05-01 12:41:46.583383635  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2024-05-01 12:41:46.583413140  [INFO] Starting go2rtc...
2024-05-01 12:41:46.685852782  14:41:46.685 INF go2rtc version 1.9.0 linux/amd64
2024-05-01 12:41:46.687226023  14:41:46.687 INF [rtsp] listen addr=:8554
2024-05-01 12:41:46.687231915  14:41:46.687 INF [api] listen addr=:1984
2024-05-01 12:41:46.687448622  14:41:46.687 INF [webrtc] listen addr=:8555
2024-05-01 12:41:55.989911265  [INFO] Starting go2rtc healthcheck service...
```
ram usage is now around 2.1GB in total (out of 8GB) and running smooth.

It ran for about 50 minutes and all of a sudden the FFMPEG ram usage spiked again.

go2rtc logs are clean, and nothing specifically logged in the frigate logs on the time of the ram usage increase.

Is it in any way related to the frigate config?

**Comment by emile-bodin** [comment]
I was looking at https://github.com/blakeblackshear/frigate/issues/8470#issuecomment-1925948604 and ended up disabling `hwaccel_args: preset-vaapi` and system is running _stable_ now, as in no memory spikes and hanging system for the past 4 hours. 

```
# mqtt
mqtt:
  host: 192.168.86.104
  user: frigate
  password: nestcam

# recordings
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

# openvino
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# global ffmpeg
ffmpeg:
 output_args:
   record: preset-record-generic-audio-aac
# hwaccel_args: preset-vaapi

go2rtc:
  hass:
    config: "/config"
  streams:
    hass-achtertuin:
      - hass://supervisor?entity_id=camera.achtertuin

# cameras
cameras:
  hass-achtertuin: # <--- this will be changed to your actual camera later
    enabled: true
    detect:
      width: 1280
      height: 720
      fps: 5    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hass-achtertuin?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```

**Comment by marcusb** [comment]
Seeing ffmpeg maxing out the memory repeatedly, on 0.14.0-rc1. Intel Nuc Gen5, 16 GB RAM, Coral M.2, va-api.

I am using go2rtc with 4 cameras. There is one ffmpeg process that keeps blowing up memory, the one for cam3 (this one uses a different type of camera than the rest). The process grows to ~11 GB virtual, 9 GB resident. This happens within a few hours of starting the service.

ffmpeg command line:
```
ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-7c39b17 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam3 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
```
One of the threads is in D state when this happens.

<details>
<summary>config.yml:</summary>

```
mqtt:
  enabled: true
  host: mqtt.example.org
  user: frigate
  password: ***

detectors:
  coral:
    type: edgetpu

objects:
  track:
    - person
    - car
    - bicycle
    - cat

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

ffmpeg:
  retry_interval: 15

go2rtc:
  streams:
    cam1:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam1.example.org/ISAPI/Streaming/Channels/101
      - ffmpeg:cam1#audio=opus
    cam1_sub:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam1.example.org/ISAPI/Streaming/Channels/102
      - ffmpeg:cam1_sub#audio=opus
    cam2:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam2.example.org:554/cam/realmonitor?channel=1&subtype=0
    cam2_sub:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam2.example.org.se:554/cam/realmonitor?channel=1&subtype=1
    cam3:
      - rtsp://pi4.example.org:8554/cam3_main
    cam3_sub:
      - rtsp://pi4.example.org:8554/cam3_sub
    cam4:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam4.example.org:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:cam4#audio=opus
    cam4_sub:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam4.example.org:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:cam4#audio=opus
  webrtc:
    candidates:
      - 172.16.1.25:8555
      - stun:8555

cameras:
  cam1:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam1_sub
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.037,0.103,0.339,0.114,0.336,0.069,0.039,0.069
        - 0.593,0.19,0.584,0.405,0.861,0.626,0.902,0.305
    review:
      alerts:
        labels: []
      detections:
        labels: []

  cam2:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam2
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam2_sub
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    zones:
      patio:
        coordinates: 0.001,0.998,0.001,0.801,0.069,0.623,0.822,0.658,0.884,0.998
        objects: person
    motion:
      threshold: 49
      contour_area: 25
      improve_contrast: 'true'

  cam3:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam3
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam3
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      threshold: 40
      contour_area: 50
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 0,0.705,0.195,0.498,0.423,0.454,0.731,0.415,1,0.439,1,1,0,1
        inertia: 3
    review:
      detections:
        required_zones:
          - driveway
      alerts:
        required_zones:
          - driveway
  cam4:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam4
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam4_sub
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask: 
        0.52,0.069,0.501,0.004,0.999,0.003,0.995,0.371,0.823,0.363,0.727,0.233,0.649,0.26
      threshold: 40
      contour_area: 30
      improve_contrast: 'true'
    zones:
      front_steps:
        coordinates: 0.706,1,0.64,0.991,0.478,0.72,0.356,0.596,0.515,0.544,0.651,0.631,0.783,0.871
      walkway:
        coordinates: 
          0.53,0.132,0.496,0.124,0.462,0.306,0.192,0.314,0.271,0.614,0.509,0.535,0.577,0.332
    review:
      detections:
        required_zones:
          - front_steps
          - walkway
      alerts:
        required_zones:
          - front_steps
          - walkway
version: 0.14
```
</details>
