### DISCUSSION TITLE
[Config Support]: no output audio, errors in logs related to output_args

### DISCUSSION THREAD

**Discussion by davison** [blakeblackshear/frigate#11188] [Config Support] [answered]
### Describe the problem you are having

I'm hearing no audio in live (sub stream) or recorded (main stream) clips/recordings from my camera. There are speech events being detected, and the playback windows show a volume level which is maxed.

This camera has been used with other NVR/DVR systems that capture and playback audio on both streams without any problem and with the same camera configuration, so I think it's something I'm missing or have wrong on frigate config.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant
  port: 1883
  user: x
  password: x

cameras:
  office:
    enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/office_main
        input_args: preset-rtsp-restream
        roles:
        - record

  front_porch:
    enabled: true
    live:
      stream_name: front_porch_sub
    audio: 
      enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_porch_main
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/front_porch_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      output_args:
        record:
        - preset-record-generic-audio-copy
    zones:
      driveway:
        coordinates: 608,576,527,377,467,217,248,51,189,229,61,240,0,389,0,576
        objects:
        - person
        - dog
        - cat
      main_gate:
        coordinates: 476,227,405,167,464,362,539,371
        objects:
        - car
    record:
      events:
        required_zones:
        - driveway
        - main_gate
    motion:
      mask:
      - 704,576,704,0,308,0,395,68,502,145,471,205,620,576
      - 99,19,185,19,185,34,99,34

go2rtc:
  streams:
    office_main:
    - 'ffmpeg:device?video=0&video_size=1280x720#video=h264'
    front_porch_sub:
    - rtsp://viewer:x@cctv-dome1:554/live/sub
    front_porch_main:
    - rtsp://viewer:x@cctv-dome1:554/live/main

detectors:
  deepstack:
    api_url: http://imager:32168/v1/vision/detection
    type: deepstack
    api_timeout: 1.0

objects:
  track:
  - person
  - dog
  - car
  - cat

record:
  enabled: true
  #retain:
  #  days: 1
  #  mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 180

snapshots:
  enabled: true
  bounding_box: true
  height: 320
  required_zones:
  - driveway
  - main_gate
  retain:
    default: 3
```

### Relevant log output

```shell
frigate  | 2024-05-01 12:25:28.478898876  [2024-05-01 12:25:28] ffmpeg.front_porch.record      ERROR   : [NULL @ 0xaaab0a7720c0] Unable to find a suitable output format for 'preset-record-generic-audio-copy'
frigate  | 2024-05-01 12:25:28.479043912  [2024-05-01 12:25:28] ffmpeg.front_porch.record      ERROR   : preset-record-generic-audio-copy: Invalid argument
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other
