### DISCUSSION TITLE
[Config Support]:  No bbox and detection

### DISCUSSION THREAD

**Discussion by dbasbabasi** [blakeblackshear/frigate#11194] [Config Support]
### Describe the problem you are having

Hello, 

I tried to run the Frigate. Everything looks fine on the logs but I were not able to get any bbox on UI. I am not sure it works correctly. I have RTX3070 on Ubuntu computer. I don't want to use HA. I am trying to run it via tensorrt docker. Maybe it happen because oy docker yml or config yml. I have no experience with Frigate. I added my compose yml and config yml. Thank you!

![Screenshot from 2024-05-01 20-59-20](https://github.com/blakeblackshear/frigate/assets/13520065/37eba38e-8265-4eb3-88a9-869ee65ae315)

version: '3.9'
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    network_mode: "host"
    container_name: frigate
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    privileged: true
    restart: unless-stopped
    shm_size: '64mb'
    volumes:
      - ./trt-models:/trt-models/
      - /etc/localtime:/etc/localtime:ro
      - ./storage:/media/frigate
      - ./config:/config
    tmpfs:
      - /tmp/cache:size=1000000000
    #ports:
    #  - '5000:5000'
    #  - '8554:8554'
    #  - '8555:8555/tcp'
    #  - '8555:8555/udp'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - YOLO_MODELS=yolov7x-320
      - USE_FP16=false

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: False 
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt

cameras:
  test:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: /media/frigate/AVG-TownCentre.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
          #  - rtmp
    detect:
      height: 720
      width: 1280
      fps: 5
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 500
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.1
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      mask: 0,0,1000,0,1000,200,0,200
```

### Relevant log output

```shell
2024-05-01 20:47:50.949986574  [INFO] Preparing Frigate...
2024-05-01 20:47:50.955239288  [INFO] Starting Frigate...
2024-05-01 20:47:51.755271271  [2024-05-01 20:47:51] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-05-01 20:47:51.859726909  [2024-05-01 20:47:51] peewee_migrate.logs            INFO    : Starting migrations
2024-05-01 20:47:51.862238999  [2024-05-01 20:47:51] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-01 20:47:51.866357636  [2024-05-01 20:47:51] frigate.app                    INFO    : Recording process started: 882
2024-05-01 20:47:51.867853298  [2024-05-01 20:47:51] frigate.app                    INFO    : go2rtc process pid: 98
2024-05-01 20:47:51.882050880  [2024-05-01 20:47:51] frigate.app                    INFO    : Output process started: 893
2024-05-01 20:47:51.889764207  [2024-05-01 20:47:51] detector.tensorrt              INFO    : Starting detection process: 891
2024-05-01 20:47:51.970380533  [2024-05-01 20:47:51] frigate.app                    INFO    : Camera processor started for test: 898
2024-05-01 20:47:51.970472745  [2024-05-01 20:47:51] frigate.app                    INFO    : Capture process started for test: 902
2024-05-01 20:47:52.001798328  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 72 MiB
2024-05-01 20:47:52.088418533  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 210, GPU 1644 (MiB)
2024-05-01 20:47:52.091379921  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 212, GPU 1654 (MiB)
2024-05-01 20:47:52.098776771  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +70, now: CPU 0, GPU 70 (MiB)
2024-05-01 20:47:52.098853406  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 140, GPU 1646 (MiB)
2024-05-01 20:47:52.098855221  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 140, GPU 1654 (MiB)
2024-05-01 20:47:52.098873712  [2024-05-01 20:47:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +15, now: CPU 0, GPU 85 (MiB)
```

### Frigate stats

```json
{"cameras":{"test":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":902,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":907,"pid":898,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"43":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"44":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"91":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"115":{"cmdline":"python3 -u -m frigate","cpu":"0.3","cpu_average":"3","mem":"1.1"},"117":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"126":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"154":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"155":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"156":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"157":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"169":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"190":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"216":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"248":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"299":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"351":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"399":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"437":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"478":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"511":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"536":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"575":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"614":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"647":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"693":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"731":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"758":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"880":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.5"},"882":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"0","mem":"0.6"},"890":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(38)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"891":{"cmdline":"frigate.detector.tensorrt","cpu":"0.1","cpu_average":"0","mem":"1.3"},"893":{"cmdline":"frigate.output       ","cpu":"0.3","cpu_average":"0","mem":"0.6"},"897":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"898":{"cmdline":"frigate.process:test ","cpu":"0.5","cpu_average":"0","mem":"0.6"},"902":{"cmdline":"frigate.capture:test ","cpu":"0.6","cpu_average":"0","mem":"0.6"},"906":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"907":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -re -stream_loop -1 -fflags +genpts -i /media/frigate/AVG-TownCentre.mp4 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"0","mem":"0.5"},"1226":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"tensorrt":{"detection_start":0.0,"inference_speed":10.0,"pid":891}},"gpu_usages":{"NVIDIA GeForce RTX 3070":{"dec":"2.0%","enc":"0.0%","gpu":"9.0%","mem":"29.38%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":880},"recording":{"pid":882}},"service":{"last_updated":1714585871,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":62.1,"mount_type":"tmpfs","total":64.0,"used":1.9},"/media/frigate/clips":{"free":8898.9,"mount_type":"ext4","total":280523.5,"used":257303.5},"/media/frigate/recordings":{"free":8898.9,"mount_type":"ext4","total":280523.5,"used":257303.5},"/tmp/cache":{"free":953.7,"mount_type":"tmpfs","total":953.7,"used":0.0}},"temperatures":{},"uptime":200,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

I want to run it on Nvidia GPU RTX3070. I don't have any coral device.
