### DISCUSSION TITLE
Error in log and Frigate halted

### DISCUSSION THREAD

**Discussion by B0ndo2** [blakeblackshear/frigate#11206] [General Support]
### Describe the problem you are having

I was receiving the error below in the log and no detection or recording

2024-05-02 14:09:49.893866905  [2024-05-02 10:09:49] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-02 14:09:59.905620991  [2024-05-02 10:09:59] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-02 14:10:19.897135353  [2024-05-02 10:10:19] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-02 14:10:29.896890925  [2024-05-02 10:10:29] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
# frigate.yml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: xxxx
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxx
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
rtmp:
  enabled: false

#motion:
#  contour_area: 100
#  delta_alpha: 0.2
#  frame_alpha: 0.2
#  frame_height: 80
#  threshold: 25
  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  
cameras:
  driveway:
    timestamp_style:
      position: "tr"
      color:
        red: 255
        green: 0
        blue: 0     
    zones:
      sidewalk:
        coordinates: 409,52,368,17,241,18,227,50
        #coordinates: 114,64,232,57,302,62,409,68,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
        objects:
          - car
      drive_way:
        coordinates: 274,47,441,62,508,76,562,189,550,260,562,286,429,352,0,352,30,207,108,66
        objects:
          - person

    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 114,64,231,43,292,43,364,47,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
          threshold: 0.58
          min_area: 3200
#          max_area: 30320
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.6.xx/2
          roles:
            - detect
        - path: rtsp://xx:xx@192.168.6.xx/1
          roles:
            - record
            - audio
    audio: 
      enabled: true
      listen:
        - scream
        - speech
        - yell
    detect:    
      width: 640
      height: 352
      fps: 5  
   #   stationary:
    #    interval: 0
    #    threshold: 50
    motion:
      mask:
        - 0,0,181,0,100,81,0,304
        - 640,0,473,0,489,65,571,100,640,191    
        - 234,14,399,18,504,45,464,0,161,1,151,27
    record:
      enabled: true
      retain:
        days: 0
      events:
        required_zones:
          - drive_way
          - sidewalk
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - drive_way
        - sidewalk
      timestamp: True
      retain:
        default: 7


################################################ 
  front_porch_camera:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    ffmpeg:
      inputs:
        - path: rtsp:/xx:xx@192.168.6.xx/2
          roles:
            - detect
        - path: rtsp://xx:xx@192.168.6.xx/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 5  
    motion:
      mask:
        - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True      
      retain:
        default: 7
```

### Relevant log output

```shell
2024-05-02 14:09:49.893866905  [2024-05-02 10:09:49] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-02 14:09:59.905620991  [2024-05-02 10:09:59] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-02 14:10:19.897135353  [2024-05-02 10:10:19] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-02 14:10:29.896890925  [2024-05-02 10:10:29] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_porch_camera. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x352
FPS: 20/1

Audio:

Codec: PCM A-law / G.711 A-law

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 20/1
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Chortau
