### DISCUSSION TITLE
[General Support]: Camera snapshot suddenly not refreshing and much lower resolution

### DISCUSSION THREAD

**Discussion by heyfordy** [blakeblackshear/frigate#11215] [General Support]
### Describe the problem you are having

Previously, the snapshot image of my camera feed on the "cameras" page would update frequently, and it was a fairly high resolution. (It looked like the debug view.)

Now, without changing configs, docker-compose or apparently anything else, the image is much smaller / lower quality and does not refresh. I can still view the webRTC stream just fine, and I can view the debug stream fine too. Weirdly, Home Assistant's non live view stream is behaving just like Frigate's used to.

I'm not seeing any browser or Frigate errors, so not really sure where to start debugging this.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: i965

mqtt:
  enabled: True
  host: mqtt.home.lan
  port: 1883

go2rtc:
  streams:
    front_doorbell:
     - rtsp://USER:PASS@192.168.3.119:554/h264Preview_01_main
     - ffmpeg:front_doorbell#audio=opus
    front_doorbell_sub:
      - rtsp://USER:PASS@192.168.3.119:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.11.201:8555

birdseye:
  enabled: True
  mode: continuous

cameras:
  front_doorbell:
    mqtt:
      timestamp: False
      bounding_box: False
    detect:
      enabled: True
    birdseye:
      order: 1
    audio:
      enabled: True
      min_volume: 200
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
        - owl
        - emergency_vehicle
    motion:
      improve_contrast: True
      threshold: 20
      contour_area: 30
      lightning_threshold: 0.9
      mask:
        - 429,0,429,29,198,28,198,0
    zones:
      driveway:
        coordinates: 423,277,456,342,498,391,640,480,640,276,432,244
        objects:
          - cat
          - dog
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
            min_score: 0.6
      porch:
        coordinates: 246,0,405,295,481,380,640,480,640,480,467,480,225,480,0,480,0,0
        objects:
          - cat
          - dog
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
            min_score: 0.6
      street:
        coordinates: 640,188,542,162,415,202,294,241,640,276
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.75
          min_area: 5000
          max_area: 100000
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      export:
        timelapse_args: "-vf setpts=PTS/60 -r 25"
      events:
        required_zones:
          - driveway
          - porch
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - driveway
        - porch
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
detectors:
  coral:
    type: edgetpu
    device: usb

ui:
  live_mode: webrtc
```

### Relevant log output

```shell
There really isn't anything
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://USER:PASS@192.168.3.119:554':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000813, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 20 fps, 40 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell WiFi
