### DISCUSSION TITLE
Live view issues

### DISCUSSION THREAD

**Discussion by shanekuz** [blakeblackshear/frigate#11230] [Config Support] [answered]
### Describe the problem you are having

Im having an issue with the live view, i have configured a substream as recommended for each of my cameras for detection but when i do this even though i set the live stream name to the major stream it always shows the substream when viewing the camera.  It does record at full resolution but the live part just seems to not work for me.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
go2rtc:
  streams:
    rtc_front_cam:
    - rtsp://192.168.31.177:554/user=admin_password=******_channel=1_stream=0&amp;onvif=0.sdp?real_st
    rtc_front_cam_sub:
    - rtsp://192.168.31.177:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp?real_st

cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.31.175:8554/rtc_front_cam
        input_args: preset-rtsp-restream
        hwaccel_args: preset-vaapi
        roles:
        - record
        - rtmp
        - detect
      - path: rtsp://192.168.31.175:8554/rtc_front_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      fps: 5
      width: 640
      height: 480
      stationary:
        interval: 50
        threshold: 50
    live:
      stream_name: rtc_front_cam
    onvif:
      host: 192.168.31.177
      port: 8899
      user: admin
      password: ****
    zones:
      Drive:
        coordinates: 
          0,802,0,2160,2549,2160,2187,1684,2682,1190,2467,1094,2128,975,1811,918,1645,910,1506,842,1348,848,1000,715
    motion:
      mask:
      - 1988,933,3840,1484,3840,262,2871,0,956,0,979,541
```

### Relevant log output

```shell
there are no errors, everything seems to work fine but the camera view is the sub stream not the main stream
```

### Frigate stats

```json
not sure what is needed here.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by hawkeye217** [comment]
In Frigate 0.13, the birdseye view displays whatever you've set as the `detect` role for your cameras. If you click on Cameras and then on the image of an individual cam, you should see the higher resolution live view.

**Reply by shanekuz** [reply]
Its not in the birdseye view its in the main view and also if you have a camera feed into home assistant it shows the subview not the main stream.

**Reply by shanekuz** [reply]
if i enable the substream and have the live setting i get this compressed image in home assistant
![image](https://github.com/blakeblackshear/frigate/assets/12933566/c0bddf5f-8f97-4b6b-ad00-d3101c972982)

where if is disable the substream and use only the main stream for detect and record i get the correct feel into HA
![image](https://github.com/blakeblackshear/frigate/assets/12933566/4cbd70f4-386f-41ef-8088-4fa7fdb1f82d)

**Reply by NickM-27** [reply]
The stream that is used is the one with the name that matches the camera name

**Reply by shanekuz** [reply]
Thanks Nick but this doesn't seem to work as expected, i have live stream_name as the full res stream not the sub stream but its still passing homeassistant the sub stream to the frigate card.  I would have thought if the live stream_name was the main stream then this is what would be passed.   I know i can use a different card and give it the path to the go2rtc url but just thought this was meant to work like im using.

**Reply by NickM-27** [reply]
No, live stream name only affects frigate UI. You need to make the name of the stream and the name of the camera match in the frigate config.

**Reply by shanekuz** [reply]
So in my config you mean instead of rtc_front_cam it should be front ?

**Reply by shanekuz** [reply]
For me even with the live stream entry in the config everything in the UI only shows the substream, it does record the full stream when something is detected but the UI even when you click for live always shows the substream

**Comment by shanekuz** [comment]
@hawkeye217  I'm thinking this might actually be a bug. In my config as soon as i put the substream as a detect role everything uses substream it does not matter what i put as the live: stream_name.   My thoughts on how this should work is live: stream_name should be what stream is passed to the UI and home assistant as the live view in the frigate card.  This should be an over ride for always sending the detect stream to everything?  If not what is the live: stream_name used for?

**Reply by NickM-27** [reply]
This is not a bug.

you are but providing examples of your updated config so we're not able to point out what is incorrect. Live -> stream name is only used for the Frigate UI as was said before

**Reply by shanekuz** [reply]
Hi Nick, im not updating or changing anything here, if I have the config i originally posted is used in home assistant shows the sub stream at is feed using the frigate card.  It does not matter which live stream_name is set in the config.  Is this how its expected to work?
Also in the Frigate GUI it always shows the sub stream not the one that is selected in the live stream_name.  Im happy to provide logs or what ever is needed to help here, i can work around it by not using the frigate card and just sending the go2rtc stream to home assistant but i thought this forum was for helping or bug finding.

**Reply by NickM-27** [reply, marked as answer]
Okay, you should change your config to have the names of streams match the names of the cameras. 

```

go2rtc:
  streams:
    test_cam:
      - rtsp://192.168.1.5:554/live0 # <- stream which supports video & aac audio.
      - "ffmpeg:test_cam#audio=opus" # <- copy of the stream which transcodes audio to opus for webrtc
    test_cam_sub:
      - rtsp://192.168.1.5:554/substream # <- stream which supports video & aac audio.
      - "ffmpeg:test_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus for webrtc

cameras:
  test_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/test_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/test_cam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect

```
