### DISCUSSION TITLE
[Bug]: HA cameras switch OFF motion + recordings constantly with 2024.5.0 HA upgrade

### DISCUSSION THREAD

**Discussion by richardfoley** [blakeblackshear/frigate#11233] [General Support] [answered]
### Describe the problem you are having

Am using Frigate with HA to manage a couple of home security systems. They both have almost identical setups and work really well together. With the last update of HA to 2024.5.0 (from 2024.4.4) both systems cameras refuse to leave "motion" and "recordings" switched ON. If I switch them on via the frontend, while the camera remains on, the motion and recordings switches immediately flick back to OFF.
This is constant. I've tried removing the retained flag from the MQTT broker/explorer, as suggested in an older/similar thread. I've restarted Frigate, HA, the box itself. Nada. I've opened an [HA bug](https://github.com/home-assistant/core/issues/116676) but thinking it's relevant to cross-post here.

Anecdotally, I noticed from the "Settings->Devices->Frigate->Device" window, that when manually switching the options in the Configuration panel, a new entry appeared, or not, in the Logbook panel. eg;

`May 3, 2024 Camera-Name Recordings turned on triggered by service Switch: Turn on 9:03:29 AM - 2 seconds ago`  
In the working version 2024.4.4 the LogBook showed a new switch service item as above.
In the faulty version 2024.5.0 the LogBook did not show any new switch service item.

It seemed this might be a Frigate issue, until it dawned on me that the only thing I'd changed recently was the regular HA upgrade. I finally restored HA-only from a backup to the previous version on both systems, and all cameras are working exactly as expected, and as they used to. With HA-2024.4.4 I do see the switch entry in the LogBook and the switches control the cameras correctly again, on both systems.

Working version:
HA Core 2024.4.4
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240404.2
Frigate 0.13.2
MQTT broker 6.4.0

Fault version:
HA Core 2024.5.0

Faulty version is upgrade to Core 2024.5.0 only, although I think this upgraded the Frontend to 20240501 too (am not sure of the Frontend version but it's tied to, and came with, Core 2024.5.0). As the bug seems to manifest itself via the frontend switches apparently not sending the command to the backend, perhaps it's the frontend?

I hope this information helps someone to fix this usually excellent piece of software.

What version of Home Assistant Core has the issue?
2024.5.0

What was the last working version of Home Assistant Core?
2024.4.4

What type of installation are you running?
Home Assistant OS

Integration causing the issue
HomeAssistant/MQTT/Frigate

### Version

0.13.2

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.103:5000/api/config/schema.json
mqtt:
  enabled: True
  host: 192.168.0.145
  user: user
  password: pass

birdseye:
  enabled: False

detectors:
  nocoral:
    type: cpu

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

objects:
  track:
  - person
  - dog
  - umbrella

detect:
  enabled: True  # <---- disable detection until you have a working camera feed
  width: 1280    # <---- update for your camera's resolution
  height: 720    # <---- update for your camera's resolution
  fps: 5

record:
  enabled: True 
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

cameras:
  entrance-hall:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:xxx@192.168.0.111/cam/realmonitor?channel=1&subtype=1&authbasic=[AUTH]       # entrance-hall low-res
        roles:
        - detect
      - path: 
          rtsp://admin:xxx@192.168.0.111/cam/realmonitor?channel=1&subtype=0&authbasic=[AUTH]       # entrance-hall high-res
        roles:
        - record
    motion:
      mask:
        - 718,0,715,54,1280,190,1280,0
        - 1280,720,1162,720,1166,600,1280,288
        - 0,0,489,0,494,191,0,420
```

### Relevant log output

```shell
No log output
```

### FFprobe output from your camera

```shell
No camera output
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Imou

ps. tried to create this as a issue/bug here, although it may be any of HA/MQTT/Frigate problem, but is unclear how to get the `bug` label here. Thanks for any assistance/ideas/fixes.

_No response_
