### DISCUSSION TITLE
[Config Support]: Add timestamp to recorded video

### DISCUSSION THREAD

**Discussion by Spectre5** [blakeblackshear/frigate#11239] [Config Support] [answered]
### Describe the problem you are having

I have the timestamp disabled on my cameras themselves.  I disabled it since the changing times would trigger motion detection.  I know I could mask the time, but I might as well get a little extra coverage from the video feed anyway.  Plus, I'd rather frigate record the time instead of a potentially different time that the camera thinks it it.  I've add the timestamp to the screenshots, but is there an easy way to add the time to the video footage too?  Ideally I would still see the time on the video itself when reviewing playback.  Does this require an expensive re-encoding?  If so, I assume it is not recommended and my next question would be, what is recommended?  Just use the timestamp on the feed and mask the area?

### Version

0.13.2-6476f8a

### Frigate config file

partial:

```yaml
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false

record:
  enabled: true
  retain:
    days: 0.25
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 15
```

### Relevant log output

N/A

### Frigate stats

N/A

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
