### DISCUSSION TITLE
[Detector Support]: Is it possible to run CoralTPU and Nvidia TensorRT at same time? If so, how? Example configs crash when combined

### DISCUSSION THREAD

**Discussion by douginoz** [blakeblackshear/frigate#11244] [Detector Support]
### Describe the problem you are having

I have 2 pci-e Coral TPUs that are configured and work fine in Frigate.  I now want to try adding TensorRT detection in addition to the existing 2 Corals.  Doing this kills frigate.  If I remove the CoralTPUs from the config, the TensorRT stuff works as expected.  If I remove TensorRT stuff, the Corals work as expected.  But trying to have them all configured crashes things.

Frigate 0.13.2-6476F8A
go2rtc 1.8.4
ubuntu 22.04
GPU NVidia GeForce GTX 1660 Super
Nvidia driver 0.13.2-6476F8A
CUDA Version 12.2

This works:
```
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

```
And This works:
```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

But this doesn't:
```
detectors:
  tensorrt:
    type: tensorrt
    device: 0
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

I have also tried that last one with the entire 'model:" section removed but makes no difference.  

Attached are 3 logs:
A - With dual coralTPUs configured  (using first config snippet shown above)
B - With TensorRT configured only (using second config snippet shown above)
C - With dual CoralTPUs and TensorRT configured (using thirt config snippet shown above)

I'm guessing that it's related to the 'model:" section, which appears to be required for tensorRT, but by including it in the config it confuses frigate's attempt to initialize the CoralTPU detection.  So this leads to the question:

Is it possible to have tensorRT detection AND CoralTPU detection at the same time, and if so, what's the config trick to make them both work?

[A - Dual Corals Only.log](https://github.com/blakeblackshear/frigate/files/15212532/A.-.Dual.Corals.Only.log)
[B - TensorRT Only - with model.log](https://github.com/blakeblackshear/frigate/files/15212533/B.-.TensorRT.Only.-.with.model.log)
[C - Dual Corals and TensorRT.log](https://github.com/blakeblackshear/frigate/files/15212534/C.-.Dual.Corals.and.TensorRT.log)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.8
  port: 1883
  user: "homeassistant"
  password: "dei2oozain6aite0kainoom0eeVuejutheNgei1vai9aepaexaeGateif5zoojoh"
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 20

ffmpeg:
  global_args: -hide_banner -loglevel error -threads 6
  hwaccel_args: preset-nvidia-h265

detectors:
  tensorrt:
    type: tensorrt
    device: 0
#  coral1:
#    type: edgetpu
#    device: pci:0
#  coral2:
#    type: edgetpu
#    device: pci:1

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 4
  mode: continuous

audio:
  enabled: false
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - scream
    - speech
    - yell
    - fire_alarm

go2rtc:
  streams:
    driveway_record:
      - rtsp://nirodha:nirodha@192.168.1.154:554/stream1 # <- high quality stream
      - "ffmpeg:driveway_record#audio=opus" # <- copy of the stream which transcodes audio to opus
    driveway_detect:
      - rtsp://nirodha:nirodha@192.168.1.154:554/stream2 # <- low quality stream
      - "ffmpeg:driveway_detect#audio=opus" # <- copy of the stream which transcodes audio to opus
    garden_record:
      - rtsp://nirodha:nirodha@192.168.1.214:554/stream1 # <- high quality stream
      - "ffmpeg:driveway_record#audio=opus" # <- copy of the stream which transcodes audio to opus
    garden_detect:
      - rtsp://nirodha:nirodha@192.168.1.214:554/stream2 # <- low quality stream
      - "ffmpeg:driveway_detect#audio=opus" # <- copy of the stream which transcodes audio to opus
    entrance:
      - rtsp://Yo8v2qBRZQCU:Ny467V0hVbg8@192.168.1.197:554/live0 # <- eufy cam only has one stream
      - "ffmpeg:driveway_record#audio=opus" # <- copy of the stream which transcodes audio to opus
    kitchen:
      - rtsp://Ea887xOHDYx5:Lk1u2G3ZHEIO@192.168.1.195:554/live0 # <- eufy cam only has one stream
      - "ffmpeg:driveway_record#audio=opus" # <- copy of the stream which transcodes audio to opus
    livingroom:
      - rtsp://Pn0sJNqinJBo:Ru1KKDNrhekh@192.168.1.196:554/live0 # <- eufy cam only has one stream
      - "ffmpeg:driveway_record#audio=opus" # <- copy of the stream which transcodes audio to opus

cameras:
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.20:8554/driveway_detect
          roles:
            - detect
        - path: rtsp://192.168.1.20:8554/driveway_record
          roles:
            - record
            - audio
    objects:
      track:
        - person
        - dog
        - car
        - truck
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 15
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 14
        objects:
          - person
          - dog
          - car
          - truck
        required_zones:
          - guest_car
          - driveway
    snapshots:
      enabled: true
    zones:
      guest_car:
        coordinates: 183,84,123,77,128,42,209,47
        objects:
          - car
      driveway:
        coordinates: 95,480,448,480,370,330,183,194,192,52,154,45,80,31,76,79,54,133,118,147
        objects:
           - person
           - dog
           - car
    motion:
      mask:
        - 442,480,355,282,169,187,189,68,233,23,0,26,0,0,640,0,640,480
        - 0,132,120,138,115,480,0,480
  Garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.20:8554:554/garden_detect
          roles:
            - detect
        - path: rtsp://192.168.1.20:8554:554/garden_record
          roles:
            - record
            - audio
    objects:
      track:
        - person
        - dog
    detect:
      enabled: true
      width: 640
      height: 320
      fps: 15
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 14
        objects:
          - person
          - dog
    snapshots:
      enabled: true
    motion:
      mask:
        - 0,320,0,256,0,0,140,0,421,0,480,104,372,150,241,203,293,320
        - 640,212,533,136,400,0,640,0
    zones:
      suite:
        coordinates: 254,234,596,199,640,320,295,320
        objects:
          - person
          - dog
  Entrance:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.20:8554:554/entrance
          roles:
            - detect
            - record
            - audio
    objects:
      track:
        - cat
        - mouse
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 15
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 40
        objects:
          - person
          - cat
          - dog
    snapshots:
      enabled: true
  Kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.20:8554:554/kitchen
          roles:
            - detect
            - record
            - audio
    objects:
      track:
        - person
        - cat
        - dog
        - mouse
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 15
    record:
      enabled: true
      retain:
        days: 40
        mode: motion
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 40
        objects:
          - person
          - cat
          - dog
    snapshots:
      enabled: true
  LivingRoom:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.20:8554:554/livingroom
          roles:
            - detect
            - record
            - audio
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 40
        mode: motion
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 40
        objects:
          - person
          - cat
          - dog
    snapshots:
      enabled: true
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    runtime: nvidia
    shm_size: "512mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#    environment:
#      YOLO_MODELS: yolov7-320
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_0:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/configurations/frigate:/config
      - /mnt/frigate:/media/frigate
      - /media/configurations/frigate:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

# Relocated mqtt to a stand-alone container so this section not needed
#  mqtt:
#    container_name: mqtt
#    image: eclipse-mosquitto:1.6
#    ports:
#      - "1883:1883"
```

### Relevant log output

```shell
Attached as 3 separate files
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

I've only tried adding in TensorRT tonight.  In doing so I changed the docker-compose to use 
`    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt`
instead of
`    image: ghcr.io/blakeblackshear/frigate:stable`

It spent a few minutes generating the new files needed.  I have checked within the docker instance that the tensorRT model is available at  /config/model_cache/tensorrt/yolov7-320.trt
