### DISCUSSION TITLE
[Support]: trying to run Frigate using docker (docker-compose) on macOS M1 and getting error

### DISCUSSION THREAD

**Discussion by tomerkulla** [blakeblackshear/frigate#11248] [General Support]
### Describe the problem you are having

I'm getting this error while trying to run the project locally on my mac using `docker-compose up`
```
716.9       copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.linux-aarch64-cpython-39/h5py/tests/data_files
716.9       running build_ext
716.9       Building h5py requires pkg-config unless the HDF5 path is explicitly specified using the environment variable HDF5_DIR. For more information and details, see https://docs.h5py.org/en/stable/build.html#custom-installation
716.9       error: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
716.9       [end of output]
716.9   
716.9   note: This error originates from a subprocess, and is likely not a problem with pip.
716.9   ERROR: Failed building wheel for h5py
716.9 Successfully built jstyleson
716.9 Failed to build h5py
716.9 ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
------
failed to solve: executor failed running [/bin/sh -c apt-get -qq update     && apt-get -qq install -y wget python3 python3-distutils     && wget -q https://bootstrap.pypa.io/get-pip.py -O get-pip.py     && python3 get-pip.py "pip"     && pip install -r /requirements-ov.txt]: exit code: 1
```

anyone encounter this issue?

thx!

### Version

not sure

### Frigate config file

```yaml
mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /debug/1917.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

-
