### DISCUSSION TITLE
[Camera Support]: Generic POE camera via webrtc no audio

### DISCUSSION THREAD

**Discussion by thomdall** [blakeblackshear/frigate#11268] [Camera Support] [answered]
### Describe the problem you are having

I have a generic POE camera in frigate. I tested with straight ffmpeg and it has audio, but when I setup as WEBRTC, the live view does have audio, but the clip doesn't. Also used the webrtc url in VLC it has no audio in codec section. 
![image](https://github.com/blakeblackshear/frigate/assets/73900168/746ee1eb-a035-4ec8-93db-1286dd7d29f7)
straight rtsp in vlc
![image](https://github.com/blakeblackshear/frigate/assets/73900168/836f2622-8b75-445c-a0e1-a98945e52728)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: '10.0.0.42'
  user: 'mqtt-user'
  password: 'mypassword'
detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
    garage:
      - "ffmpeg:rtsp://username:mypassword@10.0.0.39/h264/ch1/main#video=copy#audio=copy"
    garage_sub:
      - "ffmpeg:rtsp://username:mypassword@10.0.0.39/h264/ch1/sub"
    test_birdhouse:
      - "ffmpeg:rtsp://10.0.0.82:554/user=username&password=mypassword&channel=1&stream=0.sdp?video&audio#video=copy#audio=copy"
    test_birdhouse_sub:
      - "ffmpeg:rtsp://10.0.0.82:554/user=username&password=mypassword&channel=1&stream=1.sdp?"
  webrtc:
    candidates:
      - 10.0.0.42:8555
      - stun:8555
cameras:
  birdhouse:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.82:554/user=username&password=mypassword&channel=1&stream=0.sdp?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.0.0.82:554/user=username&password=mypassword&channel=1&stream=1.sdp?
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args: 
        record: preset-record-generic-audio-aac
    detect:
      width: 704
      height: 576
      fps: 10
    record:
      enabled: true
      events: 
        pre_capture: 30
        post_capture: 30
        retain: 
          default: 30
    snapshots:
      enabled: true
      retain: 
        default: 3
        objects:
          bird: 30
    objects: 
      track: 
        - bird
      filters: 
        bird:
          min_score: 0.72
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args: 
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 360
      fps: 10
    record:
      enabled: true
      events: 
        pre_capture: 5
        post_capture: 5
        retain: 
          default: 5
    snapshots:
      enabled: true
      retain: 
        default: 3
        objects:
          person: 30
    objects: 
      track: 
        - person
      filters: 
        person:
          min_score: 0.72
  test_birdhouse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/test_birdhouse
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/test_birdhouse_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args: 
        record: preset-record-generic-audio-aac
    detect:
      width: 704
      height: 576
      fps: 10
    record:
      enabled: true
      events: 
        pre_capture: 30
        post_capture: 30
        retain: 
          default: 30
    snapshots:
      enabled: true
      retain: 
        default: 3
        objects:
          bird: 30
    objects: 
      track: 
        - bird
      filters: 
        bird:
          min_score: 0.72
    motion:
      mask:
        - 339,53,338,78,78,105,75,75
        - 485,0,640,0,640,21,484,21
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
webrtc:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":704}]}}]
straight ffmpeg:
keep spinning and no output
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Generic POE
