### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by gluca** [blakeblackshear/frigate#11260] [Config Support]
### Describe the problem you are having

Since some days, frigate doesnt't connect to any cam. If I try to stop and start congtainer i receive this message:
 driver failed programming external connectivity on endpoint frigate (containerID: Bind for 0.0.0.0:8555 failed: port is already allocated

### Version

0,3,12

### Frigate config file

```yaml
--------------- docker compose file ---------------------------
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 256mb
    devices:
      - /dev/apex_0:/dev/apex_0 #PCIe coral board
      - /dev/dri/renderD128:/dev/dri/renderD128 # Intel HW Acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hassio/ha-home/docker/frigate/config/:/config/
      - /media/frigate:/media/frigate
      - /home/hassio/ha-home/docker/frigate/db:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" #RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "855:855/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD="<MYPASSWORD>"
      - PLUS_API_KEY=<MYAPIKEY>

--------------- Frigate config file ----------------------
database:
  path: /db/frigate.db

ffmpeg:
  hwaccel_args: preset-vaapi

mqtt:
  enabled: true
  host: 192.168.1.221
  port: 1883
  topic_prefix: frigate
  client_id: frigate_casa
  user: usr
  password: pwd

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: pci

detect:
  enabled: true
  width: 960
  height: 540

live:
  height: 960
  quality: 16

cameras:
  SalottoCam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.43:554/unicast
          roles:
            - detect
            - record
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 498,253,513,0,628,0,602,254
      - 960,108,960,265,848,456,753,421,875,108
  MagiaPatioFCam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://usr:pwd@192.168.1.192:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp:/usr:pwd@192.168.1.192:554/h264Preview_01_main
          roles:
            - record
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 0,0,1108,0,1110,33,0,31
  CapannoCam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.41:554/unicast
          roles:
            - detect
            - record
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 753,94,747,519,486,457,504,93
      - 174,426,175,206,380,117,371,495,242,540
  GarageCam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://usr:pwd@192.168.10.133:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://usr:pwd@192.168.10.133:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true
```

### Relevant log output

```shell
no log... container doesn't start
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

uname -a:
Linux gandalf 6.5.0-28-generic #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 28 23:46:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
installed ladt updates from repos
