### DISCUSSION TITLE
How to avoid stationary object in PTZ camera?

### DISCUSSION THREAD

**Discussion by cleverpal-ai** [blakeblackshear/frigate#11271] [Config Support]
### Describe the problem you are having

I'm having a stationary car within my PTZ camera Home position. It keeps on firing as a Car event. In case of fixed camera I can configure a Zone and avoid unnecessary stationary car, but not in case of PTZ. If I do the "fix" for PTZ, I am going to risk not detecting cars in this particular zone when camera moves and tracks objects.
When my PTZ cam constantly detects Car in it's view in Home position I experience my extensive CPU/GPU load due to permanent ongoing TensorRT event processing.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
cameras:
  ptz:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ptz
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        person:
          min_area: 5000
        car:
          min_area: 5000
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
    record:
      enabled: true
      events:
        post_capture: 14
      retain:
        days: 10
        mode: motion
    motion:
      lightning_threshold: 1.0
```

### Relevant log output

```shell
not relevant to my problem
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

TensorRT detector
