### DISCUSSION TITLE
[Config Support]: Casting to Google Nest Hub

### DISCUSSION THREAD

**Discussion by Samywamy10** [blakeblackshear/frigate#11286] [Config Support] [answered]
### Describe the problem you are having

When casting my Reolink E1 Pro camera to a Google Nest Hub I was getting a black screen

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: 192.0.0.1
  user: <redacted>
  password: <redacted>

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      mode: active_objects
      objects:
        person: 7
        car: 7
    pre_capture: 5
    post_capture: 5

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    cam_hd:
    - "rtsp://<username>:<password>@<ip_address>:<port>/h264Preview_01_main"
    cam: 
    - "ffmpeg:rtsp://<username>:<password>@<ip_address>:<port>/h264Preview_01_main#video=h264#audio=opus#width=1920#height=1080"
  webrtc:
    candidates:
    - 192.168.86.18:8554
    - 192.168.86.18:8555
    - stun:8555

cameras:
  cam:
    enabled: true
    snapshots:
      enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://<local_frigate_ip>:8554/cam
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://<local_frigate_ip>:8554/cam_hd
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: cam_hd
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
      - person
      - cat
    onvif:
      host: <ip_address>
      port: 8000
      user: <username>
      password: <password>
    motion:
      mask:
      - 2560,0,2560,85,1666,76,1664,0
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          mode: active_objects
          objects:
            person: 0
            cat: 7
        pre_capture: 1
        post_capture: 1
```

### Relevant log output

```shell
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by Samywamy10** [comment, marked as answer]
Sorry, only posted this to share a solution in case this helps anyone else.

I was having an issue casting to my Nest Hub, either casting via:
- [DashCast](https://stestagg.github.io/dashcast/)
- Home Assistant dashboard casting (`cast.show_lovelace_view`)
- [`media_player.play_media`](https://www.home-assistant.io/integrations/media_player/#services)

These all gave me various black screens or errors.

The solution is reduce the camera resolution to less than 1920x1080. It was originally 2560x1440. The way I did this was to create another gortc stream which is downscaled to 1920x1080. I also needed to set `video=h264` for it to work. See the code here:
```yml
gortc:
  streams:
    cam_hd:
    - "rtsp://<username>:<password>@<ip_address>:<port>/h264Preview_01_main"
    cam: 
    - "ffmpeg:rtsp://<username>:<password>@<ip_address>:<port>/h264Preview_01_main#video=h264#audio=opus#width=1920#height=1080"
 ```

This then exposes URLs at `rtsp://<local_frigate_ip>:8554/cam_hd` and `rtsp://<local_frigate_ip>:8554/cam` which you can use for roles or live view. The important thing is the name of the camera in the `cameras` section is the same name of the stream will be exposed to Home Assistant via the Frigate integration. So you need your downscaled stream to be called the same as your camera.

Hope this was helpful!
