### DISCUSSION TITLE
[Camera Support]: Lenovo EasyCamera (USB)

### DISCUSSION THREAD

**Discussion by Doomsdayrs** [blakeblackshear/frigate#11283] [Camera Support] [answered]
### Describe the problem you are having

I am struggling to get a proper configuration down from my `Lenovo EasyCamera`.

I tried using `/dev/video0` directly, but that makes other components break.
and if I did use it directly, the output was flickery and not accurate to what the camera should be capable of.

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: False

logger:
  default: debug

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: False
  retain:
    days: 7
    mode: motion

snapshots:
  enabled: False

go2rtc:
  streams:
    # I tried mapping the old config (below) to a go2rtc format
    internal: "ffmpeg:device?video=0&video_size=640x480&framerate=30&f=v4l2#-vf=transpose=1,transpose=2#f=rawvideo"

cameras:
  internal:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/internal

# Disabled, since I need go2rtc to consume /dev/video0 into a multi-consumable stream.
#      inputs:
#        - path: /dev/video0
#          input_args: -f v4l2
#          roles:
#            - detect
#            - record
#     output_args:
        # These are the only args that give some form of stream. but it is very broken. 
#       detect: -vf transpose=1,transpose=2 -f rawvideo
```

### Relevant log output

```shell
// Frigate

2024-05-07 21:07:13.726223847  [2024-05-07 21:07:13] frigate.video                  ERROR   : internal: Unable to read frames from ffmpeg process.
2024-05-07 21:07:13.726392015  [2024-05-07 21:07:13] frigate.video                  ERROR   : internal: ffmpeg process is not running. exiting capture thread

// Go2rtc
2024-05-07 21:10:50.206379330  21:10:50.206 WRN [rtsp] error="streams: exec: exit status 1" stream=internal
```

### FFprobe output from your camera

```shell
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 12525.773981, bitrate: 147456 kb/s
  Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s, 30 fps, 30 tbr, 1000k tbn
```

### Frigate stats

```json
{"cameras":{"internal":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":318,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":328,"pid":316,"process_fps":0.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"10":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"12":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"19":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"20":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"21":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"22":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"36":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"37":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"75":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"76":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"77":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"84":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"92":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"94":{"cmdline":"python3 -u -m frigate","cpu":"5.5","cpu_average":"26","mem":"1.6"},"113":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"140":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"165":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"220":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"221":{"cmdline":"nginx: cache loader process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"292":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.0"},"299":{"cmdline":"frigate.recording_manager","cpu":"2.4","cpu_average":"0","mem":"1.0"},"308":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(38)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"309":{"cmdline":"frigate.detector.cpu ","cpu":"0.0","cpu_average":"0","mem":"1.0"},"311":{"cmdline":"frigate.output       ","cpu":"0.0","cpu_average":"0","mem":"1.0"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"316":{"cmdline":"frigate.process:internal","cpu":"0.0","cpu_average":"0","mem":"1.0"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"318":{"cmdline":"frigate.capture:internal","cpu":"0.0","cpu_average":"0","mem":"1.0"},"345":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":309}},"gpu_usages":{"amd-vaapi":{"gpu":"0.00%","mem":"1.48%"}},"processes":{"go2rtc":{"pid":84},"logger":{"pid":292},"recording":{"pid":299}},"service":{"last_updated":1715130926,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":99.5,"mount_type":"tmpfs","total":100.0,"used":0.5},"/media/frigate/clips":{"free":229548.7,"mount_type":"btrfs","total":242661.0,"used":11314.7},"/media/frigate/recordings":{"free":229548.7,"mount_type":"btrfs","total":242661.0,"used":11314.7},"/tmp/cache":{"free":1024.0,"mount_type":"tmpfs","total":1024.0,"used":0.0}},"temperatures":{},"uptime":11,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Lenovo EasyCamera
