### DISCUSSION TITLE
[Support]: Frigate is sending snapshot to MQTT for filtered out events.

### DISCUSSION THREAD

**Discussion by felipemarinho97** [blakeblackshear/frigate#11297] [General Support] [answered]
### Describe the problem you are having

It keeps detecting a person in a area tha is only a empty wall. I've created a motion mask in this zone, a filter, and also restricted person detection only to my zones.
But, frigate keeps sending the snapshots of the filtered out area to mqtt.
![2024-05-08-15-38-ha darklyn online](https://github.com/blakeblackshear/frigate/assets/20695061/17be6829-5247-40b3-8a35-3bfed12c2df3)

My 3 zone setup + mask:
![image](https://github.com/blakeblackshear/frigate/assets/20695061/a19ff343-d51e-49a7-8d7c-e891d02ac989)

### Version

0.13.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.x.x
  port: 1883
  topic_prefix: frigate
  client_id: frigate

cameras:
  garagem: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/garagem
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/garagem_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
    onvif:
      host: 192.168.x.x
      port: 8899
      user: xxxxxx
      password: xxxxxx
    record:
      events:
        required_zones:
        - garden
        - street
        - tilt_zone
    snapshots:
      required_zones:
      - garden
      - street
      - tilt_zone
    zones:
      garden:
        coordinates: 0,357,0,0,269,0,222,357
        objects:
        - person
        - bicycle
        - dog
        - cat
      street:
        coordinates: 640,0,640,365,508,357,309,0
        objects:
        - person
        - car
        - motorcycle
        - bicycle
        - dog
        - cat
      tilt_zone:
        coordinates: 640,720,0,720,0,360,640,358
        objects:
        - person
        - car
        - motorcycle
        - bicycle
        - dog
        - cat
    motion:
      mask:
      - 514,369,221,372,267,0,309,0
    objects:
      filters:
        person:
          mask:
          - 508,357,222,357
go2rtc:
  streams:
    garagem:
    - rtsp://:@192.168.x.x:554/user=xxxxx_password=xxxxxx=0_stream=0&onvif=0.sdp?real_stream   # <- stream which supports video & aac audio
    - ffmpeg:garagem#audio=aac   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    garagem_sub:
    - rtsp://:@192.168.x.x:554/user=xxxxxx_password=xxxxxxx_channel=0_stream=1&onvif=0.sdp?real_stream   # <- stream which supports video & aac audio
    - ffmpeg:garagem_sub#audio=aac   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)

audio: # <- enable audio events for all camera
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

model:
  labelmap_path: /config/model_cache/yolov8/labels.txt
  model_type: yolov8

detectors:
  rocm:
    type: rocm
    model:
      path: /config/model_cache/yolov8/yolov8s_320x320.onnx


objects:
  track:
  - person
  - motorcycle
  - car
  - bicycle
  - dog
  - cat

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 365
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Besder

**Comment by NickM-27** [comment, marked as answer]
you have to set required_zones for mqtt

**Reply by felipemarinho97** [reply]
Do you have any example?

**Reply by NickM-27** [reply]
```yaml
cameras:
  garagem: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/garagem
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/garagem_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
    onvif:
      host: 192.168.x.x
      port: 8899
      user: xxxxxx
      password: xxxxxx
    record:
      events:
        required_zones:
        - garden
        - street
        - tilt_zone
    snapshots:
      required_zones:
      - garden
      - street
      - tilt_zone
    mqtt:
      required_zones:
      - garden
      - street
      - tilt_zone
```
