### DISCUSSION TITLE
[Support]:  Frigate+ model, still lots of false positives

### DISCUSSION THREAD

**Discussion by derekcentrico** [blakeblackshear/frigate#11296] [General Support] [answered]
### Describe the problem you are having

I am using the Frigate+ model.  The latest one, made today, contains 783 images.  At least 200 of those images have to do with random identifications of people, cats, cars, dogs, and packages on my patio - all of which are nonexistent.  

However, the swing set, patio umbrella pole, and chairs are still throwing these false positives.  

I'm submitting bounding boxes based on the tutorial.  I'm curious what I may be doing wrong?

Several examples are here:

![image](https://github.com/blakeblackshear/frigate/assets/1930094/73b8f423-670b-41df-abac-ca04c81c77f7)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/d0a8824d-7f09-4780-b4ef-f327a72dc643)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/7f3f9ee3-3e29-410e-acfe-21c55ee272b7)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/ab7dd206-6152-48ad-986d-d6f51847efaa)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/867009ae-facd-4dfb-895a-2e5dd1475862)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/8b67c39a-2362-44f2-b8ca-cf1b624a8c31)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/630b4b6b-96d2-4d6c-bde1-97d1737bba56)

![image](https://github.com/blakeblackshear/frigate/assets/1930094/6c1298f5-2e81-4961-89ea-cc35a49b7f8d)

I'll be curious to see what false positives come through at night with the newly minted model as well.  Lots of ghostly people, dogs, cars, packages, and such all over my patio and yard at night.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.49
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate
  stats_interval: 60

model:
# 2024.1 Base - 783 images  
  path: plus://XXXXXX
#  path: plus://XXXXX  # CPU variant not used

detectors:
  coral_pci:
    type: edgetpu
    device: pci

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 500
  listen:
  - fire_alarm
  - scream
  - speech
  - yell
  filters:
    speech:
      threshold: 0.8

detect:
  enabled: true
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

objects:
  track:
  - person
  - face
  - license_plate
  - dog
  - cat
  - car
  - amazon
  - fedex
  - ups
  - package
#    - bird
#    - backpack
#    - handbag
#    - suitcase
#    - eye glasses
  - fox

record:
  enabled: true
  expire_interval: 60
  sync_recordings: true
  retain:
    days: 21
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
    - person
    retain:
      default: 30
      mode: motion
      objects:
        person: 60

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 720
  retain:
    default: 14
    objects:
      person: 60
  quality: 85

birdseye:
  enabled: true
  mode: continuous

go2rtc:
  streams:
    garage:
    - rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:garage#video=h265#audio=aac
    garage_sub:
    - rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=2
    - ffmpeg:garage_sub#video=h264#audio=aac
    driveway:
    - rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:driveway#video=h265#audio=aac
    driveway_sub:
    - rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2
    - ffmpeg:driveway_sub#video=h264#audio=aac
    backyard:
    - rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:backyard#video=h265#audio=aac
    backyard_sub:
    - rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2
    - ffmpeg:backyard_sub#video=h264#audio=aac
    patio:
    - rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:patio#video=h265#audio=aac
    patio_sub:
    - rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2
    - ffmpeg:patio_sub#video=h264#audio=aac

cameras:
  garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: 
          rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: 
          rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=2
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      height: 720
      width: 1280
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 885,57,1280,58,1280,0,891,0
    zones:
      inside:
        coordinates: 0,720,0,0,57,0,107,233,226,224,619,205,864,193,876,0,1280,0,1280,720
      outside:
        coordinates: 124,239,119,212,64,0,599,0,869,0,865,64,868,121,866,191
    objects:
      filters:
        car:
          mask:
          - 54,61,225,36,408,0,40,0
          - 1280,0,922,0,910,202,968,315,1043,412,1202,547,1280,583
        person:
          mask:
          - 48,53,62,96,425,0,171,0,36,0
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: 
          rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=0
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: 
          rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      height: 720
      width: 1280
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 848,78,574,53,474,0,675,0,854,0,1280,0,1280,115
      - 0,0,541,0,582,38,0,264
    zones:
      pavement:
        coordinates: 0,720,0,341,255,190,638,33,846,64,781,282,816,720
      sidewalk:
        coordinates: 818,488,1229,482,1280,398,807,379
    objects:
      filters:
        car:
          mask:
          - 581,0,0,0
          - 1233,24,1160,0,1280,0,1280,26
        person:
          mask:
          - 582,38,849,62
  backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: 
          rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=0
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: 
          rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      height: 720
      width: 1280
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 1152,135,1056,143,981,128,921,88,889,30,886,0,1280,0,1280,310
    objects:
      filters:
        person:
          mask:
          - 1076,0,1280,0
        license_plate:
          mask:
          - 0,720,0,0,1280,0,1280,720
        car:
          mask:
          - 0,720,0,0,1280,0,1280,720
  patio:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: 
          rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=0
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: 
          rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      height: 832
      width: 1920
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 21,315,49,256,65,90,85,0,132,0,217,0,284,24,327,126,228,198,162,275,55,396
      - 357,44,1205,0,1535,100,1750,220,1920,305,1920,0,335,0
      - 1920,196,1729,242,1841,247,1808,284,1782,321,1833,429,1920,650
    zones:
      deck:
        coordinates: 1216,605,1019,576,1027,230,685,226,561,308,327,283,138,549,320,832,1359,832
      swingset:
        coordinates: 417,0,1593,305,1698,488,1770,545,1814,535,1821,457,1781,374
    objects:
      filters:
        dog:
          mask:
          - 253,0,0,309,1920,452,1851,352
        person:
          mask:
          - 319,116,511,0,1920,247,1787,235,1363,0,1650,0,328,0,417,0
        license_plate:
          mask:
          - 0,832,0,0,1920,0,1920,832
        car:
          mask:
          - 0,832,0,0,1920,0,1920,832

telemetry:
  network_interfaces:
  - eno
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
```

### Relevant log output

```shell
Nothing relevant.

2024-05-08 09:22:20.251565561  [INFO] Preparing Frigate...
2024-05-08 09:22:20.277403538  [INFO] Starting Frigate...
2024-05-08 09:22:21.438621947  [2024-05-08 09:22:21] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-05-08 09:22:22.593534941  [2024-05-08 09:22:22] peewee_migrate.logs            INFO    : Starting migrations
2024-05-08 09:22:22.596814543  [2024-05-08 09:22:22] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-08 09:22:22.600956408  [2024-05-08 09:22:22] frigate.app                    INFO    : Recording process started: 733
2024-05-08 09:22:22.602595593  [2024-05-08 09:22:22] frigate.app                    INFO    : go2rtc process pid: 89
2024-05-08 09:22:22.619126872  [2024-05-08 09:22:22] detector.coral_pci             INFO    : Starting detection process: 743
2024-05-08 09:22:22.621457649  [2024-05-08 09:22:22] frigate.app                    INFO    : Output process started: 745
2024-05-08 09:22:22.626940178  [2024-05-08 09:22:22] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-05-08 09:22:22.631984587  [2024-05-08 09:22:22] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-05-08 09:22:22.689267129  [2024-05-08 09:22:22] frigate.app                    INFO    : Camera processor started for garage: 778
2024-05-08 09:22:22.689351796  [2024-05-08 09:22:22] frigate.app                    INFO    : Camera processor started for driveway: 779
2024-05-08 09:22:22.711061190  [2024-05-08 09:22:22] frigate.app                    INFO    : Camera processor started for backyard: 781
2024-05-08 09:22:22.720925513  [2024-05-08 09:22:22] frigate.app                    INFO    : Camera processor started for patio: 783
2024-05-08 09:22:22.721750643  [2024-05-08 09:22:22] frigate.app                    INFO    : Capture process started for garage: 785
2024-05-08 09:22:22.721832239  [2024-05-08 09:22:22] frigate.app                    INFO    : Capture process started for driveway: 789
2024-05-08 09:22:22.721879743  [2024-05-08 09:22:22] frigate.app                    INFO    : Capture process started for backyard: 793
2024-05-08 09:22:22.721916922  [2024-05-08 09:22:22] frigate.app                    INFO    : Capture process started for patio: 799
2024-05-08 09:22:22.721957892  [2024-05-08 09:22:22] frigate.app                    INFO    : Audio process started: 806
2024-05-08 11:27:51.442045866  [2024-05-08 11:27:51] frigate.output                 WARNING : Unable to copy frame backyard1715174570.171313 to birdseye.
2024-05-08 11:27:51.442164769  [2024-05-08 11:27:51] frigate.output                 WARNING : Unable to copy frame driveway1715174570.382596 to birdseye.
2024-05-08 11:27:51.442167270  [2024-05-08 11:27:51] frigate.output                 WARNING : Unable to copy frame garage1715174570.343619 to birdseye.
```

### FFprobe output from your camera

```shell
ffprobe appears not to work on my cameras.  RTSP issue maybe?

$ ffprobe version 4.4.2-0ubuntu0.22.04.1+esm3 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x5997ce656ec0] method DESCRIBE failed: 404 Not Found
```

### Frigate stats

```json
{"bandwidth_usages":{"790":{"bandwidth":97.0},"794":{"bandwidth":64.6},"800":{"bandwidth":267.7},"801":{"bandwidth":61.3},"807":{"bandwidth":260.1},"809":{"bandwidth":58.5},"814":{"bandwidth":296.7},"817":{"bandwidth":97.4},"820":{"bandwidth":472.9},"821":{"bandwidth":65.5},"825":{"bandwidth":62.4},"827":{"bandwidth":58.4},"89":{"bandwidth":577.6}},"cameras":{"backyard":{"audio_dBFS":-67.9786,"audio_rms":13.0773,"camera_fps":5.1,"capture_pid":793,"detection_enabled":1,"detection_fps":13.7,"ffmpeg_pid":801,"pid":781,"process_fps":5.1,"skipped_fps":0.0},"driveway":{"audio_dBFS":-71.3915,"audio_rms":8.8282,"camera_fps":5.0,"capture_pid":789,"detection_enabled":1,"detection_fps":1.8,"ffmpeg_pid":794,"pid":779,"process_fps":5.0,"skipped_fps":0.0},"garage":{"audio_dBFS":-73.3858,"audio_rms":7.0172,"camera_fps":5.1,"capture_pid":785,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":790,"pid":778,"process_fps":5.1,"skipped_fps":0.0},"patio":{"audio_dBFS":-58.2652,"audio_rms":40.0118,"camera_fps":5.0,"capture_pid":799,"detection_enabled":1,"detection_fps":2.6,"ffmpeg_pid":809,"pid":783,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.8","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.2","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"2.0","cpu_average":"2","mem":"0.9"},"105":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"152":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"175":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"207":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"246":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"275":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"310":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"345":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"397":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"431":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"456":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"482":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"522":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"567":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"595":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"731":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"733":{"cmdline":"frigate.recording_manager","cpu":"1.0","cpu_average":"0","mem":"0.2"},"742":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(55)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"743":{"cmdline":"frigate.detector.coral_pci","cpu":"0.7","cpu_average":"0","mem":"0.2"},"745":{"cmdline":"frigate.output       ","cpu":"0.7","cpu_average":"0","mem":"0.2"},"755":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"762":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"763":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"764":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x832 -i pipe: -f mpegts -s 1661x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"765":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"778":{"cmdline":"frigate.process:garage","cpu":"1.1","cpu_average":"1","mem":"0.3"},"779":{"cmdline":"frigate.process:driveway","cpu":"1.0","cpu_average":"3","mem":"0.3"},"781":{"cmdline":"frigate.process:backyard","cpu":"12.8","cpu_average":"6","mem":"0.3"},"783":{"cmdline":"frigate.process:patio","cpu":"1.1","cpu_average":"2","mem":"0.3"},"785":{"cmdline":"frigate.capture:garage","cpu":"0.7","cpu_average":"0","mem":"0.2"},"789":{"cmdline":"frigate.capture:driveway","cpu":"0.8","cpu_average":"0","mem":"0.2"},"790":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.240:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.1","cpu_average":"1","mem":"0.1"},"793":{"cmdline":"frigate.capture:backyard","cpu":"0.7","cpu_average":"0","mem":"0.2"},"794":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.3","cpu_average":"1","mem":"0.1"},"799":{"cmdline":"frigate.capture:patio","cpu":"0.8","cpu_average":"0","mem":"0.2"},"800":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.0"},"801":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"1","mem":"0.1"},"806":{"cmdline":"frigate.audio_manager","cpu":"0.3","cpu_average":"0","mem":"0.3"},"807":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.241:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.0"},"809":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1920:h=832:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.8","cpu_average":"1","mem":"0.1"},"814":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.242:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.0"},"817":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.240:554/cam/realmonitor?channel=1&subtype=2 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.2","cpu_average":"0","mem":"0.0"},"820":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.243:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/patio@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.0"},"821":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.2","cpu_average":"0","mem":"0.0"},"825":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"827":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":18.3,"detectors":{"coral_pci":{"detection_start":0.0,"inference_speed":4.69,"pid":743}},"gpu_usages":{"intel-vaapi":{"gpu":"0.67%","mem":"-%"}},"processes":{"audioDetector":{"pid":806},"go2rtc":{"pid":89},"logger":{"pid":731},"recording":{"pid":733}},"service":{"last_updated":1715188447,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":876.9,"mount_type":"tmpfs","total":886.4,"used":9.5},"/media/frigate/clips":{"free":5927556.7,"mount_type":"ext4","total":7569685.2,"used":1260568.2},"/media/frigate/recordings":{"free":5927556.7,"mount_type":"ext4","total":7569685.2,"used":1260568.2},"/tmp/cache":{"free":2843.4,"mount_type":"tmpfs","total":2861.0,"used":17.6}},"temperatures":{"apex_0":47.3},"uptime":13905,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

1x IPC-T54IR-AS 6mm, 2x IPC-T54IR-AS 3.6mm, 1x IPC-Color4K-T180

### Any other information that may be helpful

Just keep adding more and more photos to try and sort out the matter, but not having much luck.  Building all of my 12 allotted models in short succession just to add in a few more images isn't ideal so want to do what I can to make the most of this.
