### DISCUSSION TITLE
[Config Support]: How to only enable Recording function and low cpu loading?

### DISCUSSION THREAD

**Discussion by BobDLA** [blakeblackshear/frigate#11307] [Config Support]
### Describe the problem you are having

I want to only use the recording function to record lots of cameras. 
But, when I disabled  most of the funciton and make the config file like
```
mqtt:
  enabled: False

detect:
  enabled: False
  fps: 1
birdseye:
  enabled: False

record:
  enabled: True
  retain:
    days: 1
rtmp:
  enabled: False

cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://172.17.0.1:554/xxxxx # <----- The stream you want to use for detection
          roles:
            - record # <------ Add this role to enable recording
go2rtc:
  streams:
    camera_1: 
      - rtsp://172.17.0.1:554/xxxxx
```

But, the ffmpeg still use over 20% cpu loading.

I find the  ffmpeg like
`ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://172.17.0.1:554/xxxx  -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/camera_1@%Y%m%d%H%M%S%z.mp4 -r 1 -vf fps=1,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
`

I have no idea what still need to be disabled to save the cpu loading.  
It should much lower cpu loaing if only recording without  processing.

Could you suggest?

Thanks

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: False

detect:
  enabled: False
  fps: 1
birdseye:
  enabled: False

record:
  enabled: True
  retain:
    days: 1
rtmp:
  enabled: False

cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://172.17.0.1:554/xxxxx # <----- The stream you want to use for detection
          roles:
            - record # <------ Add this role to enable recording
go2rtc:
  streams:
    camera_1: 
      - rtsp://172.17.0.1:554/xxxxx
```

### Relevant log output

```shell
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-05-09 17:42:09.454453341  [INFO] Preparing Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-05-09 17:42:09.458288243  [INFO] Preparing new go2rtc config...
frigate  | 2024-05-09 17:42:09.459284589  [INFO] Starting NGINX...
frigate  | 2024-05-09 17:42:09.464126979  [INFO] Starting Frigate...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-05-09 17:42:09.771347859  [INFO] Starting go2rtc...
frigate  | 2024-05-09 17:42:09.841321853  17:42:09.841 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-05-09 17:42:09.841737663  17:42:09.841 INF [api] listen addr=:1984
frigate  | 2024-05-09 17:42:09.843095757  17:42:09.843 INF [rtsp] listen addr=:8554
frigate  | 2024-05-09 17:42:09.843290629  17:42:09.843 INF [webrtc] listen addr=:8555
frigate  | 2024-05-09 17:42:10.669820517  [2024-05-09 17:42:10] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-05-09 17:42:18.051832776  192.168.176.1 - - [09/May/2024:17:42:18 +0800] "GET /recording/camera_1 HTTP/1.1" 200 6636 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
frigate  | 2024-05-09 17:42:18.227506938  2024/05/09 17:42:18 [error] 139#139: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "127.0.0.1:5000", referrer: "http://127.0.0.1:5000/recording/camera_1"
frigate  | 2024-05-09 17:42:18.227544678  192.168.176.1 - - [09/May/2024:17:42:18 +0800] "GET /api/config HTTP/1.1" 502 559 "http://127.0.0.1:5000/recording/camera_1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
frigate  | 2024-05-09 17:42:19.455820895  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-05-09 17:42:19.758691635  [2024-05-09 17:42:19] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-05-09 17:42:19.762029829  [2024-05-09 17:42:19] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-05-09 17:42:19.829219523  [2024-05-09 17:42:19] frigate.app                    INFO    : Recording process started: 419
frigate  | 2024-05-09 17:42:19.831226551  [2024-05-09 17:42:19] frigate.app                    INFO    : go2rtc process pid: 85
frigate  | 2024-05-09 17:42:19.846197822  [2024-05-09 17:42:19] frigate.app                    INFO    : Output process started: 428
frigate  | 2024-05-09 17:42:19.848721332  [2024-05-09 17:42:19] detector.cpu                   INFO    : Starting detection process: 427
frigate  | 2024-05-09 17:42:19.851629656  [2024-05-09 17:42:19] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-05-09 17:42:19.864179034  [2024-05-09 17:42:19] frigate.app                    INFO    : Camera processor started for camera_1: 434
frigate  | 2024-05-09 17:42:19.909832040  [2024-05-09 17:42:19] frigate.app                    INFO    : Capture process started for camera_1: 448
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
