### DISCUSSION TITLE
Camera  error No new recording segments were created for garage in the last 120s. restarting the ffmpeg record process...

### DISCUSSION THREAD

**Discussion by mikey6283** [blakeblackshear/frigate#11316] [Camera Support]
### Describe the problem you are having

 I  have 4 reolink cameras running on an Unraid server     I can see all camera on  192.168.0.XXX:5000 . However i have  error on  garage camera . i am not sure what is going on.  Home Assistant  will not allow me to install Frigate [Addon saying that there is no Frigate Config  ?? See logs in  Any other information that may be helpful below.
Hope that you will be able to help or advise.

### Version

 0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.120:5000/api/config/schema

mqtt:
  host: 192.168.0.XXX
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db
record:
  expire_interval: 20


go2rtc:
  streams:
    koipond:
      - "ffmpeg:http://192.168.0.235/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Koipond1#video=copy#audio=copy#audio=opus"
    koipond_sub:
      - "ffmpeg:http://192.168.0.235/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Koipond1"
    backgarden:
      - "ffmpeg:http://192.168.0.219/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=BackGarden1#video=copy#audio=copy#audio=opus"
    backgarden_sub:
      - "ffmpeg:http://192.168.0.219/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=BackGarden1"
    garage:
      - "ffmpeg:http://1192.168.0.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Garage1#video=copy#audio=copy#audio=opus"
    garage_sub:
      - "ffmpeg:http://192.168.0.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Garage1"
    front:
      - "ffmpeg:http://192.168.0.115/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Front1#video=copy#audio=copy#audio=opus"
    front_sub:
      - "ffmpeg:http://192.168.0.115/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Front1"
cameras:
  koipond:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/koipond?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/koipond_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7  
    motion:
      mask:
        - 192,35,448,31,445,0,194,0
        - 359,156,394,214,423,288,248,314,0,333,32,198
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
  backgarden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backgarden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backgarden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
         - 188,31,446,32,441,0,191,0
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
              - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
         - 188,37,461,30,460,0,186,0   
    zones:
       garage_driveway:
        coordinates: 195,124,240,105,232,197,550,256,588,349,605,480,463,480,336,480,246,480,169,480,100,480,53,480,36,451,29,411,31,349,40,291,65,245,92,207,149,159 
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7  
    motion:
      mask:
        - 186,37,450,35,449,0,185,0
        - 247,295,285,305,360,302,451,283,551,250,547,229,496,95,416,76,352,75,304,99,278,166,238,239 
    zones:
      driveway:
        coordinates: 640,480,571,311,546,279,526,252,498,221,478,187,466,162,430,139,398,112,353,113,305,110,254,110,139,306,92,383,54,480    
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
```

### Relevant log output

```shell
2024-05-09 20:36:46.834894458  [2024-05-09 20:36:46] watchdog.garage                ERROR   : No new recording segments were created for garage in the last 120s. restarting the ffmpeg record process...
2024-05-09 20:36:46.834989527  [2024-05-09 20:36:46] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2024-05-09 20:36:46.835068144  [2024-05-09 20:36:46] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
2024-05-09 20:36:56.844890422  [2024-05-09 20:36:56] watchdog.garage                ERROR   : No new recording segments were created for garage in the last 120s. restarting the ffmpeg record process...
2024-05-09 20:36:56.849271155  [2024-05-09 20:36:56] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2024-05-09 20:36:56.849345013  [2024-05-09 20:36:56] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
Garage
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	652	5	5.5%	0.1%
Capture	645	5	0.4%	0.4%
Detect	621	0 (0 skipped)	0.6%	0.4%
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

It is  strange that  I am unable install The frigate NVR addon in HA Lgs shows error :
`s6-rc: info: service go2rtc-healthcheck successfully started
2024-05-09 19:28:54.191357385  [INFO] Preparing Frigate...
2024-05-09 19:28:54.191406708  [ERROR] Frigate config file not found
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-05-09 19:28:54.194973455  [INFO] Starting NGINX...
2024-05-09 19:28:54.197245962  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-05-09 19:28:54.209991243  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-05-09 19:28:54.210297227  [INFO] Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped.

However, Logs on Unraid  does not mention this  problem as i can see all 4 cameras
