### DISCUSSION TITLE
Config is ignored

### DISCUSSION THREAD

**Discussion by ostracizado** [blakeblackshear/frigate#11313] [General Support]
### Describe the problem you are having

```
...      
zone_1:
        coordinates: 1920,498,1088,463,987,426,1106,149,1486,132,1475,219,1575,248,1587,136,1920,183,1920,486
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 4000 
          person:
            mask: 
              - 1622,0,1530,282,1488,270,1530,22
            min_score: 0.4
            max_area: 6000
...
```

![screenprint](https://github.com/blakeblackshear/frigate/assets/78053830/548334c6-b838-4007-874f-d17d5b894627)

max_area is ignored.

### Version

Current version: 0.13.2

### Frigate config file

```yaml
zone_1:
        coordinates: 1920,498,1088,463,987,426,1106,149,1486,132,1475,219,1575,248,1587,136,1920,183,1920,486
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 4000 
          person:
            mask: 
              - 1622,0,1530,282,1488,270,1530,22
            min_score: 0.4
            max_area: 6000
```

### Relevant log output

```shell
...
```

### FFprobe output from your camera

```shell
...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

TP-Link C310

**Comment by NickM-27** [comment]
You are setting max area on the zone. Most likely the object was detected in the zone in a different frame. You can check that on the clip tab.

**Reply by ostracizado** [reply]
I thought so, at first, but there's no detection in other zones. Could be the shadows.....?
```
    zones:
      zone_0:
        coordinates: 0,784,795,784,1064,487,1920,505,1920,1080,0,1080
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 18000
            #min_score: 0.4
            #threshold: 0.5
          person:
            min_area: 10000 
      zone_1:
        coordinates: 1920,498,1088,463,987,426,1106,149,1486,132,1475,219,1575,248,1587,136,1920,183,1920,486
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 4000 
          person:
            mask: 
              - 1622,0,1530,282,1488,270,1530,22
            min_score: 0.4
            max_area: 6000
      zone_2:
        coordinates: 1366,0,1108,0,999,131,1333,138
        objects:
          - person
          #- dog
          #- cat
          - car
          - motorcycle
        filters:
          person:
            min_score: 0.5
            min_area: 2000
            max_area: 18000
...
```
![screenprint3](https://github.com/blakeblackshear/frigate/assets/78053830/66b279bd-63ab-4481-b15b-5161d91cd39d)

Other false detections, without 'trackings' before:

![screenprint2](https://github.com/blakeblackshear/frigate/assets/78053830/25a39d99-d726-4d82-b6f2-aa70771dfbd1)
