### DISCUSSION TITLE
[Config Support]: CodeProject.AI multiple modules

### DISCUSSION THREAD

**Discussion by aaronbanbury** [blakeblackshear/frigate#11320] [Config Support]
### Describe the problem you are having

I've got codeproject set up with frigate to detect objects as shown below.  

```
  deepstack:
    api_url: http://192.168.0.228:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.1
```

I also want to be able to use the face recognition in codeproject also. How can I add multiple modules to my config?
/v1/vision/face

Can i add multiple api urls? 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
#  coral1:
#    type: edgetpu
#    device: pci:0
  deepstack:
    api_url: http://192.168.0.228:32168/v1/vision/detection
   #   - http://192.168.0.228:32168/v1/vision/face
    type: deepstack
    api_timeout: 0.1


go2rtc:
  streams:
    doorbell:
    - rtsp://admin:******@192.168.0.157:554/h264Preview_01_main
    - ffmpeg:test_cam#audio=opus
    doorbell_sub:
    - rtsp://admin:*******@192.168.0.157:554/h264Preview_01_sub
    - ffmpeg:test_cam#audio=opus
    driveway:
    - rtsp://admin:********@192.168.0.167:554/h264Preview_01_main
    - ffmpeg:test_cam#audio=opus
    driveway_sub:
    - rtsp://admin:*******@192.168.0.167:554/h264Preview_01_sub
    - ffmpeg:test_cam#audio=opus
    hudson:
    - rtsp://admin:*******@192.168.0.167:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:test_cam#audio=opus
birdseye:
  enabled: true
  mode: continuous



cameras:
  Doorbell:
    ffmpeg: 
      hwaccel_args: preset-nvidia-h264      
      inputs:
        # High Res Stream
      - path: rtsp://127.0.0.1:8554/doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
        # Low res Stream
      - path: rtsp://127.0.0.1:8554/doorbell_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      filters:
        person:
          min_score: 0.5
          threshold: 0.75
          min_area: 4000
        car:
          min_score: 0.5
          threshold: 0.75
          min_area: 6000
      track:
      - person
      - dog
      - car
      - truck
      - bicycle
      - motorcycle
      - bus

    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
      - zone_0

    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 2
          mode: motion
        pre_capture: 5
        post_capture: 10
        required_zones:
        - zone_0

    live:
      stream_name: doorbell

    zones:
      zone_0:
        coordinates: 640,480,640,278,597,272,491,306,244,348,84,338,23,348,0,480
     
    motion:
      mask:
      - 0,281,640,232,640,0,0,0
  Driveway:
    ffmpeg:  
      hwaccel_args: preset-nvidia-h264      
      inputs:
        # High Res Stream
      - path: rtsp://127.0.0.1:8554/driveway
        roles:
        - record
        # Low res Stream
      - path: rtsp://127.0.0.1:8554/driveway_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
      filters:
        person:
          min_score: 0.5
          threshold: 0.75
          min_area: 4000
        car:
          min_score: 0.5
          threshold: 0.75
          min_area: 6000          
      track:
      - person
      - dog
      - car
      - bicycle
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
      - zone_0
    record:
      enabled: true
      retain:
        days: 1
      events:
        retain:
          default: 2
          mode: motion
        pre_capture: 05
        post_capture: 10
        required_zones:
        - zone_0
    live:
      stream_name: driveway


    zones:
      zone_0:
        coordinates: 640,360,640,227,587,136,441,111,328,147,212,191,0,255,0,360
    motion:
      mask:
      - 437,55,640,78,640,0,0,0,0,132,257,72
  Hudson:
    ffmpeg:
      inputs:
        # High Res Stream
      - path: rtsp://127.0.0.1:8554/hudson
        input_args: preset-rtsp-restream

        roles:
        - record

        # Low res Stream
    snapshots:
      enabled: false

    record:
      enabled: false
    birdseye:
      enabled: false
```

### Relevant log output

```shell
NA
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

Other
