### DISCUSSION TITLE
[Config Support]: Stationary object disappear

### DISCUSSION THREAD

**Discussion by esvaf** [blakeblackshear/frigate#11337] [Config Support]
### Describe the problem you are having

I've encountered an issue where a parked vehicle within the detection zone for this type of object is constantly being lost and recognized again, resulting in hundreds of events per hour. I am attaching a video in debug mode.
[https://youtu.be/mXKvnGZ6tLA](https://youtu.be/mXKvnGZ6tLA)
![IMG_1576](https://github.com/blakeblackshear/frigate/assets/17836561/235e6cb6-8a7d-40a8-bd23-ab7b6552467b)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
objects:
  track:
    - car
  filters:
    car:
      min_area: 20000
      min_score: 0.7
      threshold: 0.8
detect:
  width: 640
  height: 360
  fps: 10
  enabled: True
  max_disappeared: 100
  stationary:
    interval: 200
    threshold: 100
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:111@192.168.1.2:554/ISAPI/Streaming/Channels/101
          roles:
            - detect
            - record
    objects:
      track:
        - car
        - person
        - bicycle
        - motorcycle
        - bear
    record:
      enabled: true
      retain:
        days: 0
      events:
        required_zones:
          - front_nearby
        retain:
          default: 10
          mode: active_objects
    motion:
      mask:
        - 922,0,0,0,0,453
    zones:
      front_nearby:
        coordinates: 596,471,515,384,791,268,1355,402,1606,246,1920,304,1920,1080,0,1080,0,751
        inertia: 3
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 512
      quality: 80
      required_zones:
        - front_nearby
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 10
```

### Relevant log output

```shell
no relevant log
```

### Frigate stats

```json
{"cameras":{"door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":344,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":354,"pid":332,"process_fps":10.0,"skipped_fps":0.0},"field":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":347,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":356,"pid":333,"process_fps":10.0,"skipped_fps":0.0},"front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.2,"capture_pid":340,"detection_enabled":1,"detection_fps":4.8,"ffmpeg_pid":346,"pid":331,"process_fps":10.2,"skipped_fps":0.0},"street":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":336,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":342,"pid":330,"process_fps":10.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"45":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"83":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.2"},"99":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"101":{"cmdline":"python3 -u -m frigate","cpu":"12.2","cpu_average":"14","mem":"5.4"},"110":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"149":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"293":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"295":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"0","mem":"1.9"},"304":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"305":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"2","mem":"1.8"},"307":{"cmdline":"frigate.output       ","cpu":"0.0","cpu_average":"2","mem":"1.8"},"310":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2460x1440 -i pipe: -f mpegts -s 1230x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"312":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.8"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1920x1080 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"330":{"cmdline":"frigate.process:street","cpu":"0.0","cpu_average":"3","mem":"2.4"},"331":{"cmdline":"frigate.process:front","cpu":"6.2","cpu_average":"4","mem":"1.8"},"332":{"cmdline":"frigate.process:door ","cpu":"0.0","cpu_average":"4","mem":"2.0"},"333":{"cmdline":"frigate.process:field","cpu":"0.0","cpu_average":"2","mem":"2.0"},"336":{"cmdline":"frigate.capture:street","cpu":"6.2","cpu_average":"6","mem":"1.8"},"340":{"cmdline":"frigate.capture:front","cpu":"6.2","cpu_average":"3","mem":"1.7"},"342":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.81.6:554/ISAPI/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/street@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale=2460:1440 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"30.8","cpu_average":"38","mem":"1.3"},"344":{"cmdline":"frigate.capture:door ","cpu":"6.2","cpu_average":"3","mem":"1.7"},"346":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.81.7:554/ISAPI/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"30.8","cpu_average":"30","mem":"0.9"},"347":{"cmdline":"frigate.capture:field","cpu":"0.0","cpu_average":"3","mem":"1.7"},"354":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.81.8:554/ISAPI/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/door@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"37.0","cpu_average":"31","mem":"0.8"},"356":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.81.9:554/ISAPI/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/field@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"30.8","cpu_average":"31","mem":"0.9"},"9724":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":5.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.98,"pid":305}},"processes":{"go2rtc":{"pid":92},"logger":{"pid":293},"recording":{"pid":295}},"service":{"last_updated":1715420874,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":494.0,"mount_type":"tmpfs","total":512.0,"used":18.0},"/media/frigate/clips":{"free":415159.9,"mount_type":"ext4","total":468355.7,"used":29332.9},"/media/frigate/recordings":{"free":415159.9,"mount_type":"ext4","total":468355.7,"used":29332.9},"/tmp/cache":{"free":934.7,"mount_type":"tmpfs","total":953.7,"used":19.0}},"temperatures":{},"uptime":2171,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
