### DISCUSSION TITLE
[Config Support]: Config file hierarchy for zones, object restriction and recording

### DISCUSSION THREAD

**Discussion by ChienDeLaCasse** [blakeblackshear/frigate#11335] [Config Support] [answered]
### Describe the problem you are having

Greetings,
I am trying to implement specific zones for object detection (or is it rather tracking ?). I did my best at reading Frigate documentation for zones, full reference config template, and similar discussions.

But unfortunately, my config file seems incorrect and Frigate keeps loading. 
Could you kindly correct the following assumptions ? 

1. Zones for restricting object detection are defined inside the "[name_your-camera]" level. Not anywhere else. (ERGO : no possibility to define a common zone for all cameras (inside "cameras" level or global above). 
2. Any such object restriction is defined inside a [name_your_zone].  Not anywhere else.
3. To make use of the zones, they are listed under "record->events->required zones/snapshots" section. Not anywhere else.
4. The above settings (if correct) override the "objects->track" at the "[name_your_camera]" level, and thus at the "cameras" or global leveL  

May I kindly ask what is wrong in my config file ?
Many thanks !

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

#Global Object Settings
#objects:
#  track:
#  - person
#  - car
#  - cat
#  - dog
#  - bike

#  filters:
#    person:
#      min_area: 5000
#      max_area: 100000

cameras:
  Annke:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://login:pass@192.168.1.79:554/H265/ch1/main/av_stream
        roles:
        - record
        - detect
    detect:
      width: 3632
      height: 1632
      fps: 10

#    motion:
#      mask:
#        - 1254,800,1508,883,1145,888,893,903,610,865,424,842,777,726,1004,704,1251,623,2035,590,2605,631,3148,663,3334,668,3415,638,3632,878,3632,0,0,0 

    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
        required_zones: 
          - Zall
          - ZCar1
          - ZCar2

    motion:
      mask:
        - 1314,0,3632,0,3632,311,3632,670,3632,931,3377,630,1699,644,1132,683,815,797,673,778,517,667,380,596,264,823,327,950,232,1034,0,987,0,0

    zones:
      Zall:
        coordinates: 0,1632,3632,1632,3632,517,0,504
        objects:
          - person
          - bike
          - dog
          - cat
      ZCar1:
        coordinates: 2883,915,2775,715,3632,615,3632,789
        objects: 
          - car
      ZCar2:
        coordinates: 45,1029,1155,1161,1380,873,749,736,0,754
        objects:
          - car
```

### Relevant log output

```shell
Frigate keeps loading, cannot find the log.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
