### DISCUSSION TITLE
[Camera Support]: Using local mpeg file reduce false positives

### DISCUSSION THREAD

**Discussion by jiiins** [blakeblackshear/frigate#11336] [Camera Support]
### Describe the problem you are having

I've exported a recording containing a few detections, with the objective of fine tuning the config to reduce false positives. I created a new camera with the exact same config as the original one and the file plays fine. The bounding boxes seem to be correct showing the yellow person detections, however, no event is recorded. I also tried to leave the config to a minimum (see below) but nothing is recorded either. At the same time, all other cameras' events are recorded as usual.

Is this by design? If yes, what is the best way to use this feature to reduce false positives?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
99_test:
    enabled: true
    ffmpeg:
      inputs:
      - path: /media/frigate/fr1.mp4
        input_args: -re -stream_loop -1 -fflags +genpts
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
```

### Relevant log output

```shell
no errors
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

mpeg file

**Comment by NickM-27** [comment]
Doesn't look like you have recordings or snapshots enabled for this camera

**Comment by jiiins** [comment]
This is common to all cameras:
```
snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 180
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 3
    post_capture: 3
    objects:
    - person
    - car
    retain:
      mode: active_objects
      default: 14
      objects:
        person: 21
        car: 10
objects:
  track:
  - car
  - person
  - cat
  - dog
```
