### DISCUSSION TITLE
Backup 'active_objects' files

### DISCUSSION THREAD

**Discussion by rajil** [blakeblackshear/frigate#11338] [General]
I want to backup recordings which have 'active_objects'. My config is as follows:

```
record:
  enabled: true
  sync_recordings: false
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
```

I dont see separate 'active_objects' files in the filesystem. 

```
$ ls -1
clips
exports
recordings
```

How do i find out recordings with active_objects?  I wanted to rsync these files to another system.
