### DISCUSSION TITLE
[Support]: Object Persistence

### DISCUSSION THREAD

**Discussion by bbrodriguez** [blakeblackshear/frigate#11341] [General Support]
### Describe the problem you are having

Why would I be getting multiple events for a moving or in-motion object (example below, courtesy of lazy dog)?
![IMG_1085](https://github.com/blakeblackshear/frigate/assets/3668755/d846ba89-bea9-4519-bfc8-b0547b98b737)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: XX
  port: 1883
  topic_prefix: frigate


go2rtc:
  streams:
    backgarden_main:
      - "ffmpeg:http://XX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=XX#video=copy#audio=copy#audio=opus"
ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
        
cameras:
  Backgarden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backgarden_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    zones:
      gardenzone1:
        coordinates: 715,1440,1754,1440,2560,1440,2560,457,2458,344,2320,182,2205,84,2204,176,1606,133,1057,137,986,48,605,93,418,225,546,942
    objects:
      filters:
          person:
            min_score: 0.66
            threshold: 0.76
          car:
            min_score: 0.66
            threshold: 0.95
          cat:
            min_score: 0.66
            threshold: 0.85
          dog:
            min_score: 0.66
            threshold: 0.8

    motion:
      threshold: 19
      contour_area: 5
      mask:
      - 0,0,769,0,769,76,0,76 # TIMESTAMP
    detect:
      width: 2560
      height: 1440
      fps: 10
      enabled: True
      annotation_offset: 0



  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:XX@XX:554/h265Preview_01_main
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
            - audio
    zones:
      drivezone1:
        coordinates: 1687,226,2560,364,2560,1920,0,1920,0,1599,152,1347,98,989,0,783,112,756,633,525,624,463,971,342,1000,388,1327,302
    objects:
      filters:
        person:
          min_score: 0.66
          threshold: 0.75
        car:
          min_score: 0.66
          threshold: 0.75
        cat:
          min_score: 0.66
          threshold: 0.85
        dog:
          min_score: 0.66
          threshold: 0.75

    motion:
      threshold: 13
      lightning_threshold: 0.4
      contour_area: 5
      mask:
      - 0,0,769,0,769,76,0,76 # TIMESTAMP
    detect:
      width: 2560
      height: 1920
      fps: 10
      enabled: True
      annotation_offset: 0
    
audio: 
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://XX

objects:
  track:
    - person
    - car
    - cat
    - dog
    - face
    - license_plate



record:
  enabled: True
  expire_interval: 720
  retain:
    days: XX
    mode: all
  events:
    required_zones:
      - gardenzone1
      - drivezone1
    retain:
      default: XX
      mode: active_objects

snapshots:
  required_zones:
      - gardenzone1
      - drivezone1
  enabled: True
  crop: True
  retain:
    default: XX

birdseye:
  enabled: True
  mode: objects
  width: 720
  height: 1280
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink
