### DISCUSSION TITLE
[Config Support]: Clip ans snapshots - Frigate behavior changed and I cannot trace the reason

### DISCUSSION THREAD

**Discussion by ChienDeLaCasse** [blakeblackshear/frigate#11359] [Config Support] [answered]
### Describe the problem you are having

Greetings to you,
I bother you again in my endeavors to better understand this amazing application.
I have set up Frigate config with mask motion and zones to trigger event based recording. 
I have not added any specific config line regarding snapshots. But I have activated the icon (blue) in the GUI, at the "Cameras" menu.

Everything was working as planned until yesterday where events would trigger both a clip and snapshot recording.
Since yesterday, some specific events only trigger snapshot, and clip recording is not available anymore (greyed out when picking any such event in the "Events" submenu).

What bugs me is that : 

- I have defined three specific zones for object filtering and event recording, with additional object size and ratio filtering.
- One of the zones ("Zall") overarches the frame, yet those "clipless" snapshots above make no mention of any zone.
- Until yesterday, any event was necessarily linked to one of the 3 defined zones. 

I definitely believe this is related to my config.YML setting, I have certainly tinkered something without knowing, but I still have not been able to understand why and I am afraid my tinkerings worsen the situation.

Could you help me debug ?

Many thanks!

ATTACHED (5 pictures) : 
1) Exemple of the "clipless" snapshot with corresponding absence of Zone linkage. They seem only to affect "car" objects.
2) Zones and masks overview : 1st : motion mask ; 2nd and 3rd : Zones "ZCar1" and "ZCar2" for triggering car event ; 4th : "Zall" over-arching  zone for allowing all other objects except cars. 

![Capture d’écran_13-5-2024_1415_192 168 1 20](https://github.com/blakeblackshear/frigate/assets/161958114/d579343f-f152-4b72-95d0-48dad532b036)

![Capture d’écran_13-5-2024_14615_192 168 1 20](https://github.com/blakeblackshear/frigate/assets/161958114/e3ebca67-4fbf-427d-bc37-82e0809fc311)

![Capture d’écran_13-5-2024_1476_192 168 1 20](https://github.com/blakeblackshear/frigate/assets/161958114/58d62475-32fb-4dd0-8603-d141b2d40db2)

![Capture d’écran_13-5-2024_14735_192 168 1 20](https://github.com/blakeblackshear/frigate/assets/161958114/e9f8ec13-f803-4f3f-95fa-e609287fb148)

![Capture d’écran_13-5-2024_14749_192 168 1 20](https://github.com/blakeblackshear/frigate/assets/161958114/74764476-3663-4840-8b9c-4a1021aff066)

### Version

0.13.2-

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
  - person
  - car
  - cat
  - dog
  - bike

#  filters:
#    person:
#      min_area: 5000
#      max_area: 100000

cameras:
  Annke:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://XXXX@192.168.1.79:554/H265/ch1/main/av_stream
          roles:
            - record
            - detect
        
    detect:
      width: 3632
      height: 1632
      fps: 10

#    motion:
#      mask:
#        - 1254,800,1508,883,1145,888,893,903,610,865,424,842,777,726,1004,704,1251,623,2035,590,2605,631,3148,663,3334,668,3415,638,3632,878,3632,0,0,0 

    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
        required_zones:
          - Zall
          - ZCar1
          - ZCar2

    motion:
      mask:
        - 1314,0,3632,0,3632,311,3632,670,3632,931,3377,630,1699,644,1132,683,815,797,673,778,517,667,380,596,264,823,327,950,232,1034,0,987,0,0

    zones:
      Zall:
        coordinates: 0,1632,3632,1632,3632,517,0,504
        objects:
          - person
          - bike
          - dog
          - cat
        filters:
          dog:
            min_ratio: 1
      ZCar1:
        coordinates: 3094,818,2298,905,2237,644,3632,615,3632,773,3632,989,3313,923
        objects:
          - car
        filters:
          car:
            min_area: 50000
            min_ratio: 1.2
      ZCar2:
        coordinates: 45,1029,1155,1161,1380,873,749,736,0,754
        objects:
          - car
        filters:
          car:
            min_area: 50000
            min_ratio: 1.2
```

### Relevant log output

```shell
[INFO] Preparing Frigate...
[INFO] Starting Frigate...
[2024-05-13 02:28:33] frigate.app                    INFO    : Starting Frigate (0.13.2-)
[2024-05-13 02:28:33] peewee_migrate.logs            INFO    : Starting migrations
[2024-05-13 02:28:33] peewee_migrate.logs            INFO    : There is nothing to migrate
[2024-05-13 02:28:33] frigate.app                    INFO    : Recording process started: 450
[2024-05-13 02:28:33] frigate.app                    INFO    : go2rtc process pid: 124
[2024-05-13 02:28:33] detector.coral                 INFO    : Starting detection process: 459
[2024-05-13 02:28:33] frigate.app                    INFO    : Output process started: 461
[2024-05-13 02:28:33] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
[2024-05-13 02:28:33] frigate.app                    INFO    : Camera processor started for Annke: 475
[2024-05-13 02:28:33] frigate.app                    INFO    : Capture process started for Annke: 476
[2024-05-13 02:28:35] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
[2024-05-13 02:45:28] frigate.comms.dispatcher       INFO    : Turning on snapshots for Annke
[2024-05-13 02:51:33] frigate.comms.dispatcher       INFO    : Turning off snapshots for Annke
[2024-05-13 10:44:49] frigate.comms.dispatcher       INFO    : Turning on snapshots for Annke
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
