### DISCUSSION TITLE
deepstack detector doesn't work with labelmap aggregation

### DISCUSSION THREAD

**Discussion by fancygaphtrn** [blakeblackshear/frigate#11352] [Detector Support]
### Describe the problem you are having

When using deepstack object detection,  frigate will not received aggreated labels.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ui:
  use_experimental: false
  
logger:
  default: info
  logs:
    frigate.detectors.plugins.deepstack: debug
mqtt:
  host: 192.168.5.200
detectors:
  deepstack:
    api_url: http://192.168.5.200:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.1 # secondsrecord:

record:
  enabled: True
  retain:
    days: 7
    mode: all
#    mode: motion
  events:
    retain:
      default: 10
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  retain:
    default: 10

cameras:
  # Front porch
  nvr_cam_1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_1_main?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nvr_cam_1?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,0,0,131,94,133,104,23,216,21,227,0,499,102,487,233,524,293,597,322,563,480,640,480,640,0,0,0
    objects:
      track:
        - person
        - animal
        - vehicle
      mask:
        - 0,0,0,131,94,133,104,23,216,21,227,0,499,102,487,233,524,293,597,322,563,480,640,480,640,0,0,0
      filters:
        vehicle:
          mask:
            - 501,106,510,0,210,0,208,68
        person:
          mask:
            - 271,366,267,480,184,480,182,370
        animal:
          min_area: 200
          mask:
            - 271,366,267,480,184,480,182,370
  # Deck
  nvr_cam_2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_2_main?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nvr_cam_2?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,264,0,0,640,0,640,173,640,208,587,214,597,163,640,154,640,113,544,137,462,147,379,177,376,265,342,265,340,186,270,212,197,201
    objects:
      track:
        - vehicle
        - person
        - animal
      mask:
        - 0,264,0,0,640,0,640,173,640,208,587,214,597,163,640,154,640,113,544,137,462,147,379,177,376,265,342,265,340,186,270,212,197,201
      filters:
        animal:
          min_area: 475
        person:
          min_area: 475
          mask:
            - 510,230,542,222,541,180,505,183
  # Back porch
  nvr_cam_3:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_3_main?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nvr_cam_3?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,0,0,27,217,29,287,61,333,83,397,97,441,113,481,144,554,144,591,125,640,115,640,0,0,0
        - 0,329,0,480,312,480,317,367,280,328,151,330,82,304
    objects:
      track:
        - person
        - animal
        - vehicle
      filters:
        animal:
          mask:
            - 0,329,0,480,312,480,317,367,280,328,151,330,82,304
        person:
          mask:
            - 0,329,0,480,312,480,317,367,280,328,151,330,82,304
        vehicle:
          mask:
            - 0,101,146,108,164,0,0,0
  # Shop
  nvr_cam_4:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_4?video=h264
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,235,352,250,640,161,640,0,0,0
    objects:
      track:
        - person
        - animal
      filters:
        person:
          mask:
            - 562,290,606,280,599,213,562,220
  # Spare
  nvr_cam_5:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_5_main?video=h264
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nvr_cam_5?video=h264
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,480,640,480,21,389,24,288,255,321,257,243,640,315,640,0,0,0
    objects:
      track:
        - person
        - animal
        - vehicle
      mask:
        - 0,480,640,480,21,389,24,288,255,321,257,243,640,315,640,0,0,0
      filters:
        animal:
          min_area: 300
          max_area: 20000
          threshold: 0.7
          mask:
            - 545,282,477,283,465,368,546,381
        person:
          min_area: 350
          max_area: 20000
          threshold: 0.65
        vehicle:
          min_area: 300
          max_area: 20000
          mask:
            - 0,102,154,93,164,0,0,0
          threshold: 0.6
  # Amcrest 1
  nvr_cam_6:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_6?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 640,0,640,49,438,47,439,0
    objects:
      track:
        - person
        - animal
        - vehicle
  # Amcrest 1
  nvr_cam_7:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_7?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 640,0,640,49,438,47,439,0
    objects:
      track:
        - person
        - animal
        - vehicle
  nvr_cam_8:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_8_main?video=h264
          input_args: preset-rtsp-restream
          roles:
            - record
    snapshots:
      enabled: false
    record:
      enabled: false
    detect:
      enabled: false
  nvr_cam_8_top_left:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_8_top_left?video=h264
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 640,0,640,175,442,187,289,188,270,202,0,219,0,0
    objects:
      mask:
        - 640,0,640,175,442,187,289,188,270,202,0,219,0,0
      track:
        - person
        - animal
        - vehicle
  nvr_cam_8_top_right:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/nvr_cam_8_top_right?video=h264
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 640,0,640,228,321,186,253,128,204,124,221,161,0,182,0,0
    objects:
      mask:
        - 640,0,640,228,321,186,253,128,204,124,221,161,0,182,0,0
      track:
        - person
        - animal
        - vehicle
  
ffmpeg:
  hwaccel_args:  preset-vaapi

birdseye:
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 640
  # Optional: Height of the output resolution (default: shown below)
  height: 480
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
motion:
  threshold: 25
  contour_area: 30
  improve_contrast: True
live:
  height: 400
model:
  height: 320
  width: 320
  #path: /models/spaghettinet_edgetpu_l_compiled.tflite
  #path: /models/efficientdet_lite0_320_ptq_edgetpu.tflite
  path: /models/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
  #height: 300
  #width: 300
  #path: /models/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    22: animal
go2rtc:
  log:
    level: debug
  ffmpeg:
    h264: "-c:v libx264 -g 20 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -pix_fmt:v yuvj420p"
    h264/vaapi: "-c:v h264_vaapi -g 20 -bf 0 -profile:v high -level:v 4.1 -sei:v 0"
    myinput: "-avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -use_wallclock_as_timestamps 1 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i {input}"
    reolinkinput: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -use_wallclock_as_timestamps 1 -i {input}"
    hwdeviceinput: "-vaapi_device /dev/dri/renderD128 -i {input}"
  streams:
    nvr_cam_1_main:
      - "ffmpeg:rtmp://192.168.5.46:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=******&password=******#input=reolinkinput#video=copy#audio=copy#audio=opus"
    nvr_cam_1:
      - "ffmpeg:nvr_cam_1_main#hardware=vaapi#video=h264#height=480#width=640#audio=copy#audio=opus"
    nvr_cam_2_main:
      - "ffmpeg:rtmp://192.168.5.43:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=******&password=******#input=reolinkinput#video=copy#audio=copy#audio=opus"
#      - "ffmpeg:rtsp://******:******@192.168.5.43:554/h264Preview_01_main"
#      - "ffmpeg:rtsp://******:******@192.168.5.43:554/h264Preview_01_main#video=h264#audio=opus#audio=aac"
#      - "ffmpeg:http://192.168.5.43/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=******&password=******#audio=opus#audio=aac"
#      - "ffmpeg:rtsp://******:******@192.168.5.43:554/h264Preview_01_main#hardware#video=h264#height=720#audio=opus#audio=aac"
#      - "ffmpeg:rtsp://******:******@192.168.5.43:554/h264Preview_01_main#hardware=vaapi#video=h264#audio=opus#audio=aac"
    nvr_cam_2:
      - "ffmpeg:nvr_cam_2_main#hardware=vaapi#video=h264#height=480#width=640#audio=copy#audio=opus"
#      - "ffmpeg:rtmp://192.168.5.43:1935/bcs/channel0_sub.bcs?channel=0&stream=0&user=******&password=******#hardware=vaapi#video=h264#height=480#width=640#audio=copy#audio=opus"
#      - "ffmpeg:rtsp://******:******@192.168.5.43:554/h264Preview_01_sub#hardware=vaapi#video=h264#width=640#height=480#audio=opus#audio=aac"
#      - "ffmpeg:http://192.168.5.43/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=******&password=******#audio=opus#audio=aac"
#      - "ffmpeg:nvr_cam_2_main#width=640#height=480#audio=opus#audio=aac"
    nvr_cam_3_main:
      - "ffmpeg:rtmp://192.168.5.47:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=******&password=******#input=reolinkinput#video=copy#audio=copy#audio=opus"
    nvr_cam_3:
      - "ffmpeg:nvr_cam_3_main#hardware=vaapi#video=h264#height=480#width=640#audio=copy#audio=opus"
    nvr_cam_4:
      - "ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.41:554/ch0_1.264#input=myinput"
    nvr_cam_5_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.42:554/11#input=myinput#hardware=vaapi#video=h264#height=1080#width=1920#audio=aac#audio=opus"
    nvr_cam_5:
      - "ffmpeg:nvr_cam_5_main#hardware=vaapi#video=h264#height=480#width=640#audio=aac#audio=opus"
#      - "ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.42:554/12#hardware=vaapi#video=h264#width=640#height=480#audio=aac#audio=opus"
    nvr_cam_6:
      - "ffmpeg:rtsp://admin:******@192.168.5.22:554/cam/realmonitor?channel=1&subtype=1"
    nvr_cam_7:
      - "ffmpeg:rtsp://admin:******@192.168.5.23:554/cam/realmonitor?channel=1&subtype=1"
    nvr_cam_8_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.40:554/ch0_0.264#input=myinput#hardware=vaapi#video=h264#audio=copy"
#    nvr_cam_8:
#      - "ffmpeg:nvr_cam_8_main#hardware=vaapi#video=h264#height=480#width=640#audio=copy"
#      - "ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.40:554/ch0_1.264"
#      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.40:554/ch0_1.264
    nvr_cam_8_top_left:
      - "ffmpeg:nvr_cam_8_main#input=hwdeviceinput#video=h264/vaapi#raw=-vf \"format=nv12,crop=640:480:0:100,hwupload\""
    nvr_cam_8_top_right:
      - "ffmpeg:nvr_cam_8_main#input=hwdeviceinput#video=h264/vaapi#raw=-vf \"format=nv12,crop=640:480:639:100,hwupload\""
#      - "ffmpeg:nvr_cam_8_main#video=h264#audio=copy#raw=-vf \"crop=640:480:639:100\""
    nvr_cam_9_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.5.44:554/ch0_1.264#input=myinput#hardware=vaapi#video=h264#audio=copy"
#    nvr_cam_9:
#      - "ffmpeg:nvr_cam_9_main#hardware=vaapi#video=h264#height=480#width=640#audio=copy"

  webrtc:
    listen: ":8555"
    candidates:
      - stun:8555
#  webrtc:
#    candidates:
#      - 192.168.5.200:8555
      #- stun:8555
```

### docker-compose file or Docker CLI command

```yaml
name: frigate
services:
    frigate:
        container_name: frigate
        restart: unless-stopped
        network_mode: host
        volumes:
            - type: tmpfs
              target: /tmp/cache
              tmpfs:
                size: 1000000000
            - /home/docker/frigate/models:/models
            - /mnt/goflex/frigate/storage:/media/frigate
            - /home/docker/frigate/config:/config
            - /etc/localtime:/etc/localtime:ro
        devices:
            - /dev/bus/usb:/dev/bus/usb
            - /dev/dri/renderD128
        shm_size: 64m
        privileged: true
        environment:
            - FRIGATE_RTSP_PASSWORD=********
            - LIBVA_DRIVER_NAME=iHD
        image: ghcr.io/blakeblackshear/frigate:0.13.2
```

### Relevant log output

```shell
Break due to unknown label
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Codeproject.AI will detect an object such as Dog and send to frigate.   But when the labelmap is configured to aggregate the Dog to animal.
log will show Break due to unknown label.

If the labelmap is removed, it behaves as expected.
