### DISCUSSION TITLE
[Support]: Upgrade from 0.12.1-367D724

### DISCUSSION THREAD

**Discussion by GWW88** [blakeblackshear/frigate#11369] [General Support]
### Describe the problem you are having

Hi guys, (apologies for a simple question)

Could someone point me in the right direction.
I have a really good set up of 0.12.1-367D724. I love it and it is was working great.

I am having some real trouble updating it to v0.13.

I have tried doing, 
docker compose pull
docker compose up -d
(along with a complete rebuild that I couldn't get working)

When it reloads I just get the spinning/loading wheel. I have tried for hours but just can't solve it.

### Version

0.12.1-367D724

### Frigate config file

```yaml
version: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:rw
      - /CCTV:/media/frigate/clips:rw
      - /CCTV:/media/frigate/recordings:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXX"



mqtt:
  enabled: True
  host: 192.168.1.200
  port: 1883
  topic_prefix: frigate
  user: 'gw'
  password: 'XXXXXX'
  stats_interval: 30

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
#  hwaccel_args: preset-vaapi
#  hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

#Global Object Settings
objects:
  track:
    - person
    - dog
    - car
    - bicycle
    - motorcycle
  filters:
    car:
      min_area: 750
      max_area: 100000
    person:
      min_area: 550
    dog:
      min_area: 300

go2rtc:  # <------ Check stream in VLC player if it works there all good.
  streams:
    driveway:
      - rtsp://admin:XXXXXX@192.168.1.226:554/Streaming/Channels/101
    driveway_sub:
      - rtsp://admin:XXXXXX@192.168.1.226:554/Streaming/Channels/103
    front_garden:
      - rtsp://admin:XXXXXX@192.168.1.229:554/Streaming/Channels/101
    front_garden_sub:
      - rtsp://admin:XXXXXX@192.168.1.229:554/Streaming/Channels/102
    back:
      - rtsp://admin:XXXXXX@192.168.1.227:554/Streaming/Channels/101
    back_sub:
      - rtsp://admin:XXXXXX@192.168.1.227:554/Streaming/Channels/102
    lounge:
      - rtsp://admin:XXXXXX@192.168.1.228:554/Streaming/Channels/101
    lounge_sub:
      - rtsp://admin:XXXXXX@192.168.1.228:554/Streaming/Channels/102
    porch:
      - rtsp://admin:XXXXXX@192.168.1.230:554/Streaming/Channels/101
      - "ffmpeg:porch#audio=opus" # <- copy of the stream which transcodes audio to opus
    porch_sub:
      - rtsp://admin:XXXXXX@192.168.1.230:554/Streaming/Channels/102
      - "ffmpeg:porch_sub#audio=opus" # <- copy of the stream which transcodes audio to opus

cameras:
  Driveway:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/driveway?video
#          input_args: preset-rtsp-restream
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://127.0.0.1:8554/driveway_sub?video #&audio=aac
#          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      stationary:
        interval: 0
        threshold: 25     # number of frames an object needs to remain relatively still before it is considered stationary.
      width: 1280
      height: 720
      fps: 15
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        pre_capture: 2
        post_capture: 2
        retain:
          default: 5
          mode: motion
          objects: 
            person: 7
            car: 7
            dog: 2
    zones:
      zone_driveway_road:
        coordinates: 0,288,1280,389,1280,0,0,0,0,130,135,197
        objects:
        - person
        - dog
        - car
        filters:
          person:
            min_score: 0.40
            threshold: 0.50
          car:
            threshold: 0.55
          dog:
            threshold: 0.55
      zone_driveway_entry:
        coordinates: 1280,499,1280,392,95,301,0,387
        objects:
        - person
        - dog
        - car
        filters:
          person:
            min_score: 0.40
            threshold: 0.50
          car:
            threshold: 0.55
          dog:
            threshold: 0.55
      zone_driveway_main:
        coordinates: 0,380,0,720,1280,720,1280,507
        objects:
        - person
        - dog
        - car
        filters:
          person:
            min_score: 0.4
            threshold: 0.50
          car:
            threshold: 0.55
          dog:
            threshold: 0.55
    motion:
        mask:
          - 0,104,0,364,69,353,108,279,128,234,136,195,93,129,54,135
```

### Relevant log output

```shell
Nil
```

### FFprobe output from your camera

```shell
Nil
```

### Frigate stats

```json
Nil
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision
