### DISCUSSION TITLE
[Config Support]: Person detection vicious cycle

### DISCUSSION THREAD

**Discussion by DrSpaldo** [blakeblackshear/frigate#11377] [Config Support] [answered]
### Describe the problem you are having

I've got external lights triggering when a person is detected (via HA) and I have noticed that when the camera is going between B&W & colour mode that there is a vicious cycle of detecting persons when there is no person. In fact the person size would be massive if it were really one. I was hoping for some help with the best way to reduce the false positives with the current setup. 

https://github.com/blakeblackshear/frigate/assets/8526509/02fb7b55-3066-4fd6-aa7f-ff01af3cb4aa

The 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
street1:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/street1
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/street1_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        pre_capture: 10
        post_capture: 15
        objects:
        - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 14
    detect:
      enabled: true
      max_disappeared: 100
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      quality: 100
      crop: false
      retain:
        default: 7
        objects:
          person: 60
    ui:
      order: 3
    birdseye:
      order: 5
      mode: objects
    objects:
      track:
      - person
    motion:
      mask:
      - 704,23,704,0,569,0,571,21
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
"street1": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 10,
            "capture_pid": 718,
            "detection_enabled": 1,
            "detection_fps": 10.1,
            "ffmpeg_pid": 737,
            "pid": 669,
            "process_fps": 10.1,
            "skipped_fps": 0
        },
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

The motion mask is just to block the time from the camera that was triggering motions.

**Comment by blakeblackshear** [comment, marked as answer]
Max area filter probably works here: https://docs.frigate.video/configuration/object_filters#object-area

**Reply by DrSpaldo** [reply]
> Max area filter probably works here: https://docs.frigate.video/configuration/object_filters#object-area

Thanks for the reply @blakeblackshear 

I knew it would be something like that but finding out the values I wasn't sure how to get them. Glad I could work it out with your help and the docs :)

For my own reference, this is what I ended up with:

```
objects:
  filters:
    person:
      min_area: 350
      max_area: 16000
```
