### DISCUSSION TITLE
Frigate doesn't open after installing in Proxmox LXC

### DISCUSSION THREAD

**Discussion by tomhusband** [blakeblackshear/frigate#11378] [Config Support]
### Describe the problem you are having

I had Frigate running great in Proxmox but I had to reinstall Proxmox and now can't get it to open after, I think, an identical installation. I used this [tutorial ](https://www.homeautomationguy.io/blog/running-frigate-on-proxmox) which uses the tteck scripts to install but this time nothing opens. I used the same config.yaml as before. If I go to the Frigate IP nothing loads except sometimes if I keep reloading (many times) I can get a blank page with the Frigate logo in the top left.

I can access the camera via the IP address.

Any pointers greatly appreciated.

### Version

I only see a blank page

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx.xxxxxx@192.168.68.60:554/cam/realmonitor?channel=1&su>
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10

    objects:
      track:
        - car
            mask
              - 1164,611,610,720,493,211,838,71
        - person
        - dog
        - cat
        - bicycle
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
        dog:
          min_score: 0.6
          threshold: 0.75
    record:
      enabled: True
      retain:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects

    motion:
      improve_contrast: True
```

### Relevant log output

```shell
No log output
```

### FFprobe output from your camera

```shell
When I try ff probe 192.168.68.60/ I get Invalid data found when processing input
```

### Frigate stats

```json
Can't open
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP8M-2496EW
