### DISCUSSION TITLE
[Config Support]: High CPU load advice

### DISCUSSION THREAD

**Discussion by james-barrett** [blakeblackshear/frigate#11387] [Config Support]
### Describe the problem you are having

My 4 camera setup works, uses Coral TPU and Intel iGPU passthrough but the CPU load is 40% showing in the Frigate UI and 25% over 4 Cores in Proxmox, is this expected? seems a little higher than i was expecting.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: jsmpeg

record:
  expire_interval: 10

mqtt:
  enabled: false

#ffmpeg:
  #hwaccel_args: preset-intel-qsv-h265

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

birdseye:
  enabled: true
  mode: continuous

live:
  height: 1080
  quality: 5

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"

go2rtc:
  streams:
    camera1:
      - rtsp://admin:xxx@192.168.0.181:554/h265Preview_01_main
    camera1_sub:
      - rtsp://admin:xxx@192.168.0.181:554/h264Preview_01_sub
    camera2:
      - rtsp://admin:xxx@192.168.0.40:554/h265Preview_01_main
    camera2_sub:
      - rtsp://admin:xxx@192.168.0.40:554/h264Preview_01_sub
    camera3:
      - rtsp://admin:xxx@192.168.0.20:554/h265Preview_01_main
    camera3_sub:
      - rtsp://admin:xxx@192.168.0.20:554/h264Preview_01_sub
    camera4:
      - rtsp://admin:xxx@192.168.0.186:554/h265Preview_01_main
    camera4_sub:
      - rtsp://admin:xxx@192.168.0.186:554/h264Preview_01_sub
  log:
    exec: trace

detect:
  width: 640
  height: 360
  fps: 5

cameras:
  camera1:
    ffmpeg:
      inputs:
         - path: rtsp://127.0.0.1:8554/camera1?video=copy&audio=aac
           input_args: preset-rtsp-restream
           roles:
            - record
         - path: rtsp://127.0.0.1:8554/camera1_sub?video=copy
           input_args: preset-rtsp-restream
           roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 7
          mode: motion
        pre_capture: 15
        post_capture: 15
    onvif:
      host: 192.168.0.181
      port: 8000
      user: admin
      password: xxx
      autotracking:
        enabled: False
        calibrate_on_startup: False
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - zone_name
        return_preset: home
        timeout: 10
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera2_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
           - detect
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 7
          mode: motion
        pre_capture: 15
        post_capture: 15
    onvif:
      host: 192.168.0.40
      port: 8000
      user: admin
      password: xxx
      autotracking:
        enabled: False
        calibrate_on_startup: False
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - zone_name
        return_preset: home
        timeout: 10
  camera3:
    ffmpeg:
      inputs:
         - path: rtsp://127.0.0.1:8554/camera3?video=copy&audio=aac
           input_args: preset-rtsp-restream
           roles:
            - record
         - path: rtsp://127.0.0.1:8554/camera3_sub?video=copy
           input_args: preset-rtsp-restream
           roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 7
          mode: motion
        pre_capture: 15
        post_capture: 15
    onvif:
      host: 192.168.0.20
      port: 8000
      user: admin
      password: xxx
      autotracking:
        enabled: False
        calibrate_on_startup: False
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - zone_name
        return_preset: home
        timeout: 10
  camera4:
    ffmpeg:
      inputs:
         - path: rtsp://127.0.0.1:8554/camera4?video=copy&audio=aac
           input_args: preset-rtsp-restream
           roles:
            - record
         - path: rtsp://127.0.0.1:8554/camera4_sub?video=copy
           input_args: preset-rtsp-restream
           roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 7
          mode: motion
        pre_capture: 15
        post_capture: 15
    onvif:
      host: 192.168.0.186
      port: 8000
      user: admin
      password: xxx
      autotracking:
        enabled: False
        calibrate_on_startup: False
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - zone_name
        return_preset: home
        timeout: 10
```

### Relevant log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
you are restreaming both the main and sub stream, presumably based on the reolink rtsp URls you are using high res reolink cameras which restreaming is expensive. Best way to know for sure is to attach a screenshot of the system page from the UI which shows what is using CPU

**Reply by james-barrett** [reply]
Thanks for your reply

Screenshot attached

![IMG_0011](https://github.com/blakeblackshear/frigate/assets/11320710/a704a954-cd4c-4523-a90e-de74e177eef1)

**Reply by NickM-27** [reply]
Can you scroll down and screenshot the rest

**Reply by james-barrett** [reply]
yes sorry, also the htop incase it helps

![IMG_0013](https://github.com/blakeblackshear/frigate/assets/11320710/56417e78-3f43-447c-862a-1fff7cb153aa)
![IMG_0012](https://github.com/blakeblackshear/frigate/assets/11320710/8402e623-01d2-45d3-b9c4-de898132ab4a)

**Reply by NickM-27** [reply]
Right, so go2rtc is using the most cpu. Would likely see a considerable drop if you used the sub streams for live view and didn't restream the high res

**Reply by james-barrett** [reply]
trying not to sound dim but, how to use substreams for live view :)

**Reply by NickM-27** [reply]
your config would change ot something like this

```
go2rtc:
  streams:
    camera1: # <- updated
      - rtsp://admin:xxx@192.168.0.181:554/h264Preview_01_sub
  log:
    exec: trace

detect:
  width: 640
  height: 360
  fps: 5

cameras:
  camera1:
    ffmpeg:
      inputs:
         - path: rtsp://admin:xxx@192.168.0.181:554/h265Preview_01_main # <- uses stream directly
           input_args: preset-rtsp-restream
           roles:
            - record
         - path: rtsp://127.0.0.1:8554/camera1?video=copy # <- updated
           input_args: preset-rtsp-restream
           roles:
            - detect

```
