### DISCUSSION TITLE
[Config Support]: Getting 400 when trying to access POST /config/save from another app in same docker compose

### DISCUSSION THREAD

**Discussion by mbronstein1** [blakeblackshear/frigate#11389] [Config Support]
### Describe the problem you are having

I am having trouble updating and saving new fields in a different app that is spun up in the same docker compose as the Frigate image (similar to Double Take). Accessing frigate works great, but I am trying to create a cleaner interface to be able to update the Frigate config through the /config/save route, and I continue to run into 400 errors. I have a proxy route that can access the Frigate image w/out CORS issues, and the advanced Frigate docs say that JSON can be sent via a POST route to /config/save to update the frigate config. I have tried sending both JSON and yml-formatted string (w/ content-type set to text/plain). I receive 400s in every instance.

Out of curiosity, I exec'd into the Docker frigate shell and used the cat command to read the http.py file. It looked like /config/save wasn't even there, which is even more confusing, considering the Frigate UI can successfully save config changes.

I'm wondering if there is something I am missing? The format is correct, both when sending in JSON and yaml string, as I first GET the raw config file, convert to JSON, and then spread changes into that object, which I then am sending back to /config/save.

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: mqtt
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

# model and detectors for built-in frigate openvino
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true

objects:
  track:
    - person


motion:
  threshold: 80
  contour_area: 30

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  bounding_box: false
  retain:
    default: 1

cameras:
  Dock_External:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: **redacted**
          roles:
            - record
        - path: **redacted**
          roles:
            - detect
    objects:
      track:
        - car
    record:
      events:
        objects:
          - car
        required_zones:
          - left_door_arrival
          - left_door_departure
          - right_door_arrival
          - right_door_departure
    snapshots:
      required_zones:
        - left_door_arrival
        - left_door_departure
        - right_door_arrival
        - right_door_departure
    zones:
      left_door_arrival:
        coordinates: 442,662,580,720,866,438,742,418
        objects:
          - car
      left_door_departure:
        coordinates: 730,424,634,504,768,529,962,354,846,347
        objects:
          - car
      right_door_arrival:
        coordinates: 596,720,1110,720,1148,457,873,444
        objects:
          - car
      right_door_departure:
        coordinates: 1136,570,1159,376,954,363,867,445,782,533
        objects:
          - car
```

### Relevant log output

```shell
Error message:
Request failed with status code 400
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
