### DISCUSSION TITLE
[Config Support]:  Frigate Crashes when adding a stream rtsp url with a dash (-) in it.

### DISCUSSION THREAD

**Discussion by bobloadmire** [blakeblackshear/frigate#11386] [Config Support] [answered]
### Describe the problem you are having

All RTSP streams work perfectly, unless the url has a dash, i.e. rtsp://192.168.0.4:8554/side-yard. This will cause frigate to stop loading correctly, requiring me to restore from backup since the web ui no longer loads. Adding streams without a dash work perfectly.

### Version

13.2

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml

record:
  enabled: False
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: False
  retain:
    default: 30

cameras:
  Kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.4:8554/kitchen
          roles:
            - detect
    detect:
      height: 1080
      width: 1920
      fps: 5
  Lyras Room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.4:8554/lyras-room
          roles:
            - detect
    detect:
      height: 1080
      width: 1920
      fps: 5
  Lincs Room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.4:8554/lincs-room
          roles:
            - detect
    detect:
      height: 1080
      width: 1920
      fps: 5      
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant log output

```shell
N/A unreachable
```

### Operating system

Proxmox

### Install method

LXC

### Coral version

CPU (no coral)
