### DISCUSSION TITLE
[Camera Support]: SD59225U-HNI

### DISCUSSION THREAD

**Discussion by hmjgriffon1** [blakeblackshear/frigate#11404] [Camera Support]
### Describe the problem you are having

I added my Dahua PTZ SD59225U-HNI using the same rtsp URL as my dahua turret cameras from the same period and I get an error, maybe the URL is wrong? The URL I am using is rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif 

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

database:
  path: /config/frigate.db

mqtt:
  enabled: true
  host: 10.0.0.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous
  restream: false

record:
  enabled: True
  retain:
    days: 0
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 14

go2rtc:
  streams:
    living_room_cam:
      - ffmpeg:rtsp://admin:password@10.0.0.7:554/Streaming/Channels/101
      - "ffmpeg:living_room_cam#audio=aac"
    living_room_cam_sub:
      - ffmpeg:rtsp://admin:password@10.0.0.7:554/Streaming/Channels/102
      - "ffmpeg:living_room_cam_sub#audio=aac"
    office_cam:
      - rtsp://admin:password@10.0.0.12:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:office_cam#audio=opus"
    office_cam_sub:
      - rtsp://admin:password@10.0.0.12:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:office_cam_sub#audio=opus"
    ptz_cam:
      - rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:office_cam#audio=opus"
    ptz_cam_sub:
      - rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:office_cam_sub#audio=opus"
#  log:
#    exec: trace
  webrtc:
    candidates:
      - 10.0.0.2:8555
      - stun:8555

cameras:
  living_room_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:password@10.0.0.7:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://admin:password@10.0.0.7:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 6
    objects:
      track:
        - person

  office_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://10.0.0.2:8554/office_cam
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://10.0.0.2:8554/office_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person

  ptz_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://10.0.0.4:8554/ptz_cam
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://10.0.0.4:8554/ptz_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
```

### Relevant log output

```shell
2024-05-16 20:54:24.911967950  [2024-05-16 20:54:24] watchdog.ptz_cam               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-05-16 20:54:24.912342279  [2024-05-16 20:54:24] ffmpeg.ptz_cam.detect          ERROR   : [tcp @ 0x5b7dc9c57f80] Connection to tcp://10.0.0.4:8554?timeout=5000000 failed: Connection refused
2024-05-16 20:54:24.912541614  [2024-05-16 20:54:24] ffmpeg.ptz_cam.detect          ERROR   : rtsp://10.0.0.4:8554/ptz_cam_sub: Connection refused
2024-05-16 20:54:24.942105790  [2024-05-16 20:54:24] ffmpeg.ptz_cam.record          ERROR   : [tcp @ 0x5a2e89b53100] Connection to tcp://10.0.0.4:8554?timeout=5000000 failed: Connection refused
2024-05-16 20:54:24.942407081  [2024-05-16 20:54:24] ffmpeg.ptz_cam.record          ERROR   : rtsp://10.0.0.4:8554/ptz_cam: Connection refused
2024-05-16 20:54:24.942682842  [2024-05-16 20:54:24] watchdog.ptz_cam               INFO    : Terminating the existing ffmpeg process...
2024-05-16 20:54:24.942936857  [2024-05-16 20:54:24] watchdog.ptz_cam               INFO    : Waiting for ffmpeg to exit gracefully...
2024-05-16 20:54:24.968668453  [2024-05-16 20:54:24] frigate.video                  ERROR   : ptz_cam: Unable to read frames from ffmpeg process.
2024-05-16 20:54:24.968818151  [2024-05-16 20:54:24] frigate.video                  ERROR   : ptz_cam: ffmpeg process is not running. exiting capture thread...
2024-05-16 20:54:34.962427536  [2024-05-16 20:54:34] watchdog.ptz_cam               ERROR   : Ffmpeg process crashed unexpectedly for ptz_cam.
2024-05-16 20:54:34.962670646  [2024-05-16 20:54:34] watchdog.ptz_cam               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-05-16 20:54:34.963117163  [2024-05-16 20:54:34] ffmpeg.ptz_cam.detect          ERROR   : [tcp @ 0x635d41f3af80] Connection to tcp://10.0.0.4:8554?timeout=5000000 failed: Connection refused
2024-05-16 20:54:34.963312381  [2024-05-16 20:54:34] ffmpeg.ptz_cam.detect          ERROR   : rtsp://10.0.0.4:8554/ptz_cam_sub: Connection refused
2024-05-16 20:54:34.988045003  [2024-05-16 20:54:34] ffmpeg.ptz_cam.record          ERROR   : [tcp @ 0x5e0f27130100] Connection to tcp://10.0.0.4:8554?timeout=5000000 failed: Connection refused
2024-05-16 20:54:34.988118287  [2024-05-16 20:54:34] ffmpeg.ptz_cam.record          ERROR   : rtsp://10.0.0.4:8554/ptz_cam: Connection refused
```

### FFprobe output from your camera

```shell
FFPROBE just spins and never gives any output.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua SD59225U-HNI

**Comment by hawkeye217** [comment]
Your URL may not be correct, but you should fix the lines in your go2rtc config for `ptz_cam` that still point to `office_cam`:
```
    ptz_cam:
      - rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:office_cam#audio=opus"
    ptz_cam_sub:
      - rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:office_cam_sub#audio=opus"
```
      
change it to:
```
    ptz_cam:
      - rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:ptz_cam#audio=opus"
    ptz_cam_sub:
      - rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:ptz_cam_sub#audio=opus"
```

I have several Dahua cams and the URL looks similar, though I don't have the `&unicast=true&proto=Onvif` at the end.

**Reply by hmjgriffon1** [reply]
Good catch, fixed and yeah still get an error, I did also try without the unicast part and it didn't work, it does on my turret cameras though, the erorr says 10.0.0.4:8554 though I'm not sure why it looks like it's trying to hit 8554 when I specified 554 and that is the port the camera says in it's settings.

**Reply by hawkeye217** [reply]
It would be good to see the go2rtc logs.

One thing you could also try would be to use `preset_vaapi` for your hwaccel args.

**Reply by hmjgriffon1** [reply]
2024-05-17 08:58:07.002596851  [INFO] Preparing new go2rtc config...
2024-05-17 08:58:07.213073050  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-05-17 08:58:07.256332120  [INFO] Starting go2rtc...
2024-05-17 08:58:07.344457179  08:58:07.344 INF go2rtc version 1.8.4 linux/amd64
2024-05-17 08:58:07.344910008  08:58:07.344 INF [api] listen addr=:1984
2024-05-17 08:58:07.344937692  08:58:07.344 INF [rtsp] listen addr=:8554
2024-05-17 08:58:07.345330152  08:58:07.345 INF [webrtc] listen addr=:8555
2024-05-17 08:58:16.997948446  [INFO] Starting go2rtc healthcheck service...

I will try preset_vaapi

**Comment by hmjgriffon1** [comment]
I keep getting.

024-05-17 09:51:33.419927899  [2024-05-17 09:51:33] ffmpeg.ptz_cam.detect          ERROR   : [tcp @ 0x5d49a5b76e40] Connection to tcp://10.0.0.4:8554?timeout=5000000 failed: Connection refused
2024-05-17 09:51:33.420181540  [2024-05-17 09:51:33] ffmpeg.ptz_cam.detect          ERROR   : rtsp://10.0.0.4:8554/ptz_cam_sub: Connection refused

Camera settings:
![image](https://github.com/blakeblackshear/frigate/assets/121559144/7a59dbb2-8080-4f3b-9cad-fc3d6040c92d)

not sure what the W in front of everything is about.

**Reply by NickM-27** [reply]
you should be using 127.0.0.1:8554/... not the ip address

**Reply by hawkeye217** [reply]
This 👆🏻

**Reply by hmjgriffon1** [reply]
I did just catch that, one sec, I think I see another issue I can fix, standby.

**Reply by hawkeye217** [reply]
```
  office_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/office_cam
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://127.0.0.1:8554/office_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
...
```            

If you're using go2rtc (which you are), you need to point the record and detect streams at the go2rtc provided streams, which is why you want to use 127.0.0.1 and port 8554.

**Comment by hmjgriffon1** [comment]
Okay so now everything is good but its saying

2024-05-17 10:27:18.216319276  10:27:18.216 WRN [rtsp] error="streams: wrong user/pass, exec: exit status 1" stream=ptz_cam
2024-05-17 10:27:23.306008678  10:27:23.305 WRN [rtsp] error="streams: wrong user/pass, exec: exit status 1" stream=ptz_cam_sub

I even changed the camera password to 12345678

so I dunno what the deal is with that, it won't let me have a blank password and I can log into the cameras web interface.

**Reply by NickM-27** [reply]
Enable trace logs to see what the error is 

```
go2rtc:
  log:
    exec: trace
  streams: ...
```
