### DISCUSSION TITLE
[Support]: 2 way audio over Cloudflare argo tunnel

### DISCUSSION THREAD

**Discussion by xflapx** [blakeblackshear/frigate#11416] [General Support]
### Describe the problem you are having

Hi all!

I've set up WebRTC on the latest stable build of Frigate. It works well inside my network with the mic (still messing with the audio but less concerned here I'm sure I'll figure it out). Over the argo tunnel (Cloudflared), however, the 2 way audio options on the frigate card disappear, which is what I'm mostly interested in right now. Just wanted to know if anyone has experience with argo tunnels and what might cause the options to disappear entirely. For additional color- I borrowed from someone's Reolink config for the WebRTC configuration, so maybe there is something that doesn't quite align with the AD410, but I've not found anyone talking about their AD410 2 way audio in a way that is helpful to my config.

As an aside, I used to have hass and frigate split and it was an old setup. To make some of the elements work, I had an amcrest docker container that pulled from the api and sent mqtt messages to my broker. With the Dahua HACS integration I don't think I even need MQTT anymore here. Just wanted to get any general thoughts as my goal is to consolidate. I have a kubernetes server and a docker server (don't ask), and I'm nearly done getting rid of the old docker server with this Amcrest container being an outlier. Feel free to pick apart my config file if I'm doing anything wrong or dated as well. Coral and quicksync working great, so the hardware side is clean.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: [redacted]
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [redacted]
  password: [redacted]
  stats_interval: 60

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

##########################################################################

go2rtc:
  streams:

    back_deck:
      - rtsp://[redacted]/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:rtsp://[redacted]/h264Preview_01_sub#audio=pcm#audio=volume      
    front_door:
      - rtsp://[redacted]/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:rtsp://[redacted]/h264Preview_01_sub#audio=pcm#audio=volume      
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 14
      mode: motion
      objects:
        person: 30

##########################################################################

cameras:

  back_deck:
    ffmpeg:
      inputs:

        - path: rtsp://[redacted]/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      filters:
        person:
          mask: 2498,2029,2403,1567
    detect:
      width: 3840
      height: 2160
    snapshots:
      enabled: True
  front_door:
    ffmpeg:
      inputs:

        - path: rtsp://[redacted]/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 2560
      height: 1920
    snapshots:
      enabled: True
```

### Relevant log output

```shell
Nothing shows in the frigate logs nor is there anything apparent in HassOS. I know this isn't necessarily a frigate issue so just looking for anyone who may have experience. Will share any logs needed to help troubleshoot.
```

### FFprobe output from your camera

```shell
Don't believe this is relevant but let me know if I need to figure this part out.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wireless

### Camera make and model

Amcrest AD410

### Any other information that may be helpful

To clarify: the doorbell cam is wireless, the HassOS system is a micro PC that is hardwired in my dmarc.
