### DISCUSSION TITLE
[HW Accel Support]:

### DISCUSSION THREAD

**Discussion by phlnil** [blakeblackshear/frigate#11412] [Hardware Acceleration Support]
### Describe the problem you are having

Hi, 
proxmox 8.2.2 and docker and Frigate and problems :)
just one cam on portainer I see starting frigate but suddenly it stops No way to enter on IP:5000 
What I need to look at ? 
Thank you!

### Version

ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128                                                                       
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

detectors:
  cpu1:
    type: cpu
    num_threads: 3
#    model:
#      path: "/custom_model.tflite"
  cpu2:
    type: cpu
    num_threads: 3


#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  FrontCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:this@192.168.1.164:554
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://admin:this@192.168.1.164:554
          roles:
            - detect
    detect:
      width: 480
      height: 360
      fps: 24
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:rw
      - /cctv_clips:/clips
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "this"
```

### Relevant log output

```shell
2024-05-18 09:53:42.212485961  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
ffprobe: command not found
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision
