### DISCUSSION TITLE
[Config Support]: Home and away behavior

### DISCUSSION THREAD

**Discussion by Subseedshiva** [blakeblackshear/frigate#11413] [Config Support]
### Describe the problem you are having

Hi

Is there a way to set up home vs away behavior for detection and recording? I have Tapo c310 cameras and in the app i have set up this behavior, but since i use frigate to record this seems to have no relevance on what gets recorded. Basically i would like to set it up so nothing gets recorded when home (besides some hours of the night), and that all events get recorded when away.

Appreciate any help. 

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: 
  user: 
  password: 

cameras:
  Kamera1:
    ffmpeg:
      inputs:
        - path: rtsp://Kamera1:xxx@192.xxx.xxx:554/stream1  
          roles:
            - record
            - detect
  Kamera2:
    ffmpeg:
      inputs:
        - path: rtsp://Kamera2:xxx@192.xxx.xxx.xx:554/stream1  
          roles:
            - record
            - detect
record:
  enabled: True
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 0
        cat: 0
        car: 7
        person: 14
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
