### DISCUSSION TITLE
[Config Support]: threshold not being honored

### DISCUSSION THREAD

**Discussion by danodemano** [blakeblackshear/frigate#11438] [Config Support] [answered]
### Describe the problem you are having

Hello all,

I'll admit I'm brand new to this NVR software. I'm working on configuring object (person) detection. I have my threshold set to 0.75 but I'm still getting events with person: 71%. Maybe I'm missing something silly (entirely possible) but I'm trying to understand why my camera setting is being ignored. See full config below. Here is a screenshot showing the 71% detection:

![image](https://github.com/blakeblackshear/frigate/assets/1128744/d6c5b098-4b53-4ddf-bf79-398697a9d000)

Thanks,
Dan

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.9.205
  port: 1883
  topic_prefix: frigate
  client_id: frigate

rtmp:
  enabled: False

go2rtc:
  streams:
    driveway:
      - rtsp://admin:[pass]@192.168.53.110:554/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46amFja2hhbW1lcjg2
    driveway_sub:
      - rtsp://admin:[pass]@192.168.53.110:554/cam/realmonitor?channel=1&subtype=02&authbasic=YWRtaW46amFja2hhbW1lcjg2
    front_walk:
      - rtsp://admin:[pass]@192.168.53.111:554/s0
    front_walk_sub:
      - rtsp://admin:[pass]@192.168.53.111:554/s2
    patio_1:
      - rtsp://admin:[pass]@192.168.53.112:554/s0
    patio_1_sub:
      - rtsp://admin:[pass]@192.168.53.112:554/s2
    patio_2:
      - rtsp://admin:[pass]@192.168.53.118:554/s0
    patio_2_sub:
      - rtsp://admin:[pass]@192.168.53.118:554/s2
    backyard:
      - rtsp://admin:[pass]@192.168.53.113:554/s0
    backyard_sub:
      - rtsp://admin:[pass]@192.168.53.113:554/s2
    house_east:
      - rtsp://admin:[pass]@192.168.53.120:554/s0
    house_east_sub:
      - rtsp://admin:[pass]@192.168.53.120:554/s2
    living_room:
      - rtsp://admin:[pass]@192.168.53.115:554/s0
    living_room_sub:
      - rtsp://admin:[pass]@192.168.53.115:554/s2
    den:
      - rtsp://admin:[pass]@192.168.53.119:554/s0
    den_sub:
      - rtsp://admin:[pass]@192.168.53.119:554/s2
    craft_room:
      - rtsp://admin:[pass]@192.168.53.116:554/s0
    craft_room_sub:
      - rtsp://admin:[pass]@192.168.53.116:554/s2
    garage:
      - rtsp://admin:[pass]@192.168.53.117:554/s0
    garage_sub:
      - rtsp://admin:[pass]@192.168.53.117:554/s2
    basement:
      - rtsp://admin:[pass]@192.168.53.114:554/s0
    basement_sub:
      - rtsp://admin:[pass]@192.168.53.114:554/s2
    litter_boxes:
      - rtsp://admin:[pass]@192.168.53.131:554/h264Preview_01_main
    litter_boxes_sub:
      - rtsp://admin:[pass]@192.168.53.131:554/h264Preview_01_sub

cameras:
  driveway:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    motion:
        mask:
          - 883,60,1236,61,1230,29,878,29
    zones:
      driveway_zone:
        coordinates: 1280,720,1280,213,1099,162,983,136,890,117,673,109,508,108,324,133,170,160,0,213,0,720
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 0
      dashboard: True
    birdseye:
      order: 0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  front_walk:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_walk
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/front_walk_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      front_yard_and_steps:
        coordinates: 1024,60,1024,576,463,576,0,576,0,162,179,107,290,167,303,74,510,0,897,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 1
      dashboard: True
    birdseye:
      order: 1
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  patio_1:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_1
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/patio_1_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    motion:
        mask:
          - 600,243,611,242,613,225,601,223
          - 550,226,562,229,563,209,551,206
    zones:
      patio_1_zone:
        coordinates: 0,576,1024,576,1024,0,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 2
      dashboard: True
    birdseye:
      order: 2
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  patio_2:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_2
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/patio_2_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      patio_2_zone:
        coordinates: 0,576,1024,576,1024,0,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 3
      dashboard: True
    birdseye:
      order: 3
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  backyard:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    motion:
      lightning_threshold: 0.7
    zones:
      backyard_zone:
        coordinates: 0,576,1024,576,1024,0,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 4
      dashboard: True
    birdseye:
      order: 4
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  house_east:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/house_east
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/house_east_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      side_yard:
        coordinates: 865,576,873,69,765,65,628,88,497,134,286,246,0,413,0,576,441,576
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 5
      dashboard: True
    birdseye:
      order: 5
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  living_room:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/living_room_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      window:
        coordinates: 113,314,400,296,400,45,93,88
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
      door:
        coordinates: 529,372,770,383,807,48,560,24
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 6
      dashboard: True
    birdseye:
      order: 6
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  den:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/den
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/den_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      den_zone:
        coordinates: 0,576,1024,576,1024,0,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 7
      dashboard: True
    birdseye:
      order: 7
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  craft_room:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/craft_room
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/craft_room_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      craft_room_zone:
        coordinates: 0,576,1024,576,1024,0,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 8
      dashboard: True
    birdseye:
      order: 8
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  garage:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      garage_door:
        coordinates: 181,425,640,429,647,39,171,42
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 9
      dashboard: True
    birdseye:
      order: 9
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  basement:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/basement
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/basement_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    zones:
      basement_zone:
        coordinates: 0,576,1024,576,1024,0,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
    best_image_timeout: 60
    ui:
      order: 10
      dashboard: True
    birdseye:
      order: 10
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
  litter_boxes:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/litter_boxes
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/litter_boxes_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
          - audio
    best_image_timeout: 60
    ui:
      order: 11
      dashboard: True
    birdseye:
      order: 11
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False

ffmpeg:
  hwaccel_args: preset-vaapi
#  hwaccel_args: preset-intel-qsv-h264

detectors:
#  detector_cpu:
#    type: cpu
#    num_threads: 6
#  ov:
#    type: openvino
#    device: AUTO
  coral:
    type: edgetpu
    device: usb

audio:
  enabled: True
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: True
  retain:
    default: 30

birdseye:
  enabled: True
  mode: continuous

motion:
  threshold: 25
  lightning_threshold: 0.8

ui:
  time_format: 24hour
```

### Relevant log output

```shell
N/A
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

Running on Docker in Ubuntu 24.04 LTS.

**Comment by NickM-27** [comment]
You set the filter on the zone not the camera, and you didn't make the zone required

**Reply by danodemano** [reply]
lol I'm going to display my noobness here, but I cannot apply a filter to each zone? I likely will want to tweak it individually.

Also, I don't know what you mean by making the zone required. :/

**Reply by NickM-27** [reply, marked as answer]
https://docs.frigate.video/configuration/zones#restricting-events-to-specific-zones

**Reply by danodemano** [reply]
OK Now I'm confused. I was looking at the full config here https://docs.frigate.video/configuration/reference

Which shows that filters go with zones (about 3/4 of the way down). So do I have something all wrong? I don't even have the record events specified per camera but it is recording on events (and as mentioned not honoring the threshold).

**Reply by NickM-27** [reply]
You can set filters on a camera or on a zone. If you don't make the zones required for events then the event will still be created even when the object is not considered in the zone.

So you should either apply the filter to the camera or make your zones required for events.

**Reply by danodemano** [reply]
Cool ok, I think I get it now. So to circle back to that camera in question I just need to drop this bit into the camera config, correct?

```
    record:
      events:
        required_zones:
          - patio_1_zone
```
