### DISCUSSION TITLE
[Config Support]: No audio in recordings (using preset-record-generic-audio-copy)

### DISCUSSION THREAD

**Discussion by FeatherKing** [blakeblackshear/frigate#11431] [Config Support] [answered]
### Describe the problem you are having

I am able to hear audio for the `hagdrivewaycam` camera in MSE, but none of the recordings have audio. I am using `preset-record-generic-audio-copy`. When i export, VLC doesnt even show an audio track (but again web ui sounds fine). I am trying to enable audio recordings for three cameras and this is my first attempt.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
logger:
  default: info
  logs:
    detector.ov: debug
    ffmpeg: debug
mqtt:
  enabled: true
  host: mqtt
go2rtc:
  streams:
    hagdrivewaycam:
      - rtsp://wyze.home.xyz:8554/hag-driveway
      - "ffmpeg:hagdrivewaycam#video=h264#hardware#audio=opus"
cameras:
  front_doorbell:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://user:pass@10.0.1.103:554/h264Preview_01_main
        roles:
        - record
        - detect
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
      events:
        retain:
          default: 2
        objects:
        - person
    motion:
      threshold: 25
      mask:
      - 0,74,0,0,778,0,778,67
      - 1685,956,1116,974,1122,744,1138,337,1651,335
    detect:
      width: 2560
      height: 1920
  hagdrivewaycam:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/hagdrivewaycam
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/hagdrivewaycam
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      threshold: 30
      mask:
      - 1677,1059,1870,1057,1869,1015,1670,1019
    detect:
      width: 1920
      height: 1080
      fps: 10
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
      events:
        required_zones:
        - driveway_hag
        - neighbor
        - south_frame
        retain:
          default: 2
    zones:
      driveway_hag:
        coordinates: 373,1080,1429,1080,1545,883,940,577,477,336,124,446,224,766
      south_frame:
        coordinates: 219,779,378,1080,720,1080,1920,1080,1920,159,1484,0,415,0,227,50,66,108,93,367
        objects:
        - person
      neighbor:
        coordinates: 1794,321,1846,201,1534,117,1443,203
      street:
        coordinates: 336,78,1007,161,1430,261,1920,444,1920,817,1202,496,658,289,170,124
    objects:
      filters:
        car:
          mask:
          - 104,340,85,193,223,150,392,234
          - 317,585,481,473,674,435,806,609,819,924,357,919,253,911,250,668
        cat:
          mask:
          - 317,585,481,473,674,435,837,612,639,856,415,872,308,860,219,667
        person:
          mask:
          - 96,482,181,473,173,323,88,323
  driveway-cam:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: 
          rtsp://user:pass@192.168.0.172:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://user:pass@192.168.0.172:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    motion:
      threshold: 30
      mask:
      - 967,277,1018,266,1029,217,976,224
      - 883,275,929,267,940,220,895,221
      - 820,242,814,201,849,193,845,242
      - 884,238,884,193,914,194,924,235
      - 1761,469,1685,379,1638,381,1600,315,1577,252,1647,266,1697,327,1735,371,1764,374,1744,243,1827,251,1881,314,1827,436,1892,348,1920,362,1920,443,1846,483,1813,535,1784,529
      - 757,96,942,108,955,161,1003,161,1017,126,1084,131,1636,217,1920,304,1920,128,1920,0,1362,0,1079,0,0,0,0,208,210,138,383,117
    zones:
      driveway_house:
        coordinates: 
          1920,1080,1920,720,1578,564,1338,477,867,536,409,598,429,721,188,745,0,825,0,1080
      neighbor1:
        coordinates: 1635,301,1504,248,1379,239,1298,232,1460,289
      neighbor2:
        coordinates: 1766,373,1920,442,1920,362
      neighbor3:
        coordinates: 236,262,394,248,388,200,271,217
      street_west:
        coordinates: 
          641,297,925,286,1241,296,1460,289,1716,311,1920,327,1920,383,1830,385,1426,393,986,435,663,456,346,489,109,552,0,587,0,482,0,306,212,193,284,188,89,325,100,362
      west_frame:
        coordinates: 0,1080,1920,1080,1920,90,1626,111,1072,51,261,116,0,234,0,347
        objects:
        - person
    objects:
      filters:
        car:
          mask:
          - 266,217,390,196
        person:
          mask:
          - 340,459,354,535,293,539,292,455
          - 340,459,354,535,1568,429,1566,459,1601,570,1632,568,1357,473,1527,541
          - 1601,570,1632,568,1632,523,1607,518
          - 1357,473,1527,541,1511,477,1457,457
    detect:
      width: 1920
      height: 1080
      fps: 8
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
      events:
        retain:
          default: 2
        required_zones:
        - driveway_house
        - neighbor1
        - neighbor2
        - neighbor3
        - west_frame
  cat-cam:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://wyze.home.xyz:8554/cat-cam
        roles:
        - record
        - detect
    motion:
      threshold: 50
      mask:
      - 1920,775,1841,928,1744,860,1920,442
      - 1674,1059,1867,1056,1866,1014,1670,1017
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 2
    objects:
      filters:
        person:
          mask:
          - 871,803,1077,705,1033,567,807,626,803,730
      track:
      - person
      - dog
      - cat
  deck:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://wyze.home.xyz:8554/deck
        roles:
        - record
        - detect
    motion:
      threshold: 50
      mask:
      - 1567,0,1560,219,1289,193,1289,0
      - 742,0,955,65,964,301,804,319,509,339,304,275,442,163,427,59,526,0
      - 327,708,211,722,169,497,281,458
      - 0,380,0,0,356,0,302,169,236,333
      - 1669,1057,1870,1055,1866,1011,1666,1017
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 2
    objects:
      filters:
        person:
          mask:
          - 533,395,543,485,487,495,483,408
          - 791,436,841,432,841,365,793,363
          - 166,483,172,549,209,537,203,476
          - 1332,312,1334,371,1292,371,1294,316
          - 1460,310,1460,351,1429,353,1429,308
          - 130,503,140,566,103,566,95,501
      track:
      - person
      - dog
      - cat
      - car
  driveway-south-floodcam:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://wyze.home.xyz:8554/driveway-south-floodcam
        roles:
        - record
        - detect
    motion:
      threshold: 30
      mask:
      - 1670,1057,1870,1057,1867,1017,1672,1018
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 2
    objects:
      track:
      - person
      - dog
      - cat
      - car
  hag-cam:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://wyze.home.xyz:8554/hag-cam
        roles:
        - record
        - detect
    motion:
      mask:
      - 1059,564,1114,568,1115,0,1072,0
      - 1663,1059,1866,1059,1866,1015,1658,1014
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 2
detectors:
  coral:
    type: edgetpu
objects:
  track:
  - person
  - car
  - bicycle
  - bus
  - dog
  - cat
  - motorcycle
```

### Relevant log output

```shell
no errors in logs
```

### Frigate stats

```json
// 20240519145725
// https://frigate.home.xyz/api/stats

{
  "cameras": {
    "cat-cam": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 513,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 525,
      "pid": 492,
      "process_fps": 5.1,
      "skipped_fps": 0.0
    },
    "deck": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 519,
      "detection_enabled": 1,
      "detection_fps": 1.8,
      "ffmpeg_pid": 566,
      "pid": 494,
      "process_fps": 5.1,
      "skipped_fps": 0.0
    },
    "driveway-cam": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 8.0,
      "capture_pid": 508,
      "detection_enabled": 1,
      "detection_fps": 33.0,
      "ffmpeg_pid": 514,
      "pid": 489,
      "process_fps": 8.0,
      "skipped_fps": 0.0
    },
    "driveway-south-floodcam": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 527,
      "detection_enabled": 1,
      "detection_fps": 21.8,
      "ffmpeg_pid": 602,
      "pid": 496,
      "process_fps": 5.0,
      "skipped_fps": 0.0
    },
    "front_doorbell": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.0,
      "capture_pid": 500,
      "detection_enabled": 1,
      "detection_fps": 21.1,
      "ffmpeg_pid": 1168,
      "pid": 487,
      "process_fps": 5.1,
      "skipped_fps": 0.0
    },
    "hag-cam": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.0,
      "capture_pid": 556,
      "detection_enabled": 1,
      "detection_fps": 0.3,
      "ffmpeg_pid": 603,
      "pid": 498,
      "process_fps": 5.0,
      "skipped_fps": 0.0
    },
    "hagdrivewaycam": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 10.0,
      "capture_pid": 504,
      "detection_enabled": 1,
      "detection_fps": 14.0,
      "ffmpeg_pid": 509,
      "pid": 488,
      "process_fps": 10.1,
      "skipped_fps": 0.0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "18": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "97": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "16.9",
      "cpu_average": "15",
      "mem": "5.9"
    },
    "98": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "118": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "145": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "153": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "172": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "201": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "239": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "270": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "439": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "441": {
      "cmdline": "frigate.recording_manager",
      "cpu": "5.2",
      "cpu_average": "5",
      "mem": "0.9"
    },
    "450": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "451": {
      "cmdline": "frigate.detector.coral",
      "cpu": "31.4",
      "cpu_average": "27",
      "mem": "0.5"
    },
    "453": {
      "cmdline": "frigate.output       ",
      "cpu": "2.8",
      "cpu_average": "2",
      "mem": "0.5"
    },
    "459": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "460": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "461": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "462": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "463": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "464": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "465": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "466": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "487": {
      "cmdline": "frigate.process:front_doorbell",
      "cpu": "26.1",
      "cpu_average": "15",
      "mem": "1.0"
    },
    "488": {
      "cmdline": "frigate.process:hagdrivewaycam",
      "cpu": "13.8",
      "cpu_average": "19",
      "mem": "1.0"
    },
    "489": {
      "cmdline": "frigate.process:driveway-cam",
      "cpu": "36.8",
      "cpu_average": "36",
      "mem": "1.1"
    },
    "492": {
      "cmdline": "frigate.process:cat-cam",
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "494": {
      "cmdline": "frigate.process:deck ",
      "cpu": "2.5",
      "cpu_average": "5",
      "mem": "0.9"
    },
    "496": {
      "cmdline": "frigate.process:driveway-south-floodcam",
      "cpu": "42.5",
      "cpu_average": "28",
      "mem": "1.0"
    },
    "498": {
      "cmdline": "frigate.process:hag-cam",
      "cpu": "2.6",
      "cpu_average": "3",
      "mem": "0.8"
    },
    "500": {
      "cmdline": "frigate.capture:front_doorbell",
      "cpu": "4.4",
      "cpu_average": "4",
      "mem": "0.9"
    },
    "504": {
      "cmdline": "frigate.capture:hagdrivewaycam",
      "cpu": "4.4",
      "cpu_average": "3",
      "mem": "0.8"
    },
    "508": {
      "cmdline": "frigate.capture:driveway-cam",
      "cpu": "3.4",
      "cpu_average": "2",
      "mem": "0.8"
    },
    "509": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hagdrivewaycam -r 10 -vf fps=10,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "9.6",
      "cpu_average": "9",
      "mem": "0.2"
    },
    "513": {
      "cmdline": "frigate.capture:cat-cam",
      "cpu": "2.0",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "514": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.172:554/cam/realmonitor?channel=1&subtype=2 -r 8 -vf vpp_qsv=framerate=8:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "4.8",
      "cpu_average": "4",
      "mem": "0.2"
    },
    "519": {
      "cmdline": "frigate.capture:deck ",
      "cpu": "2.0",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "525": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wyze.home.xyz:8554/cat-cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/cat-cam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.5",
      "cpu_average": "3",
      "mem": "0.3"
    },
    "527": {
      "cmdline": "frigate.capture:driveway-south-floodcam",
      "cpu": "2.1",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "546": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hagdrivewaycam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/hagdrivewaycam@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "556": {
      "cmdline": "frigate.capture:hag-cam",
      "cpu": "2.1",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "566": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wyze.home.xyz:8554/deck -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/deck@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.4",
      "cpu_average": "3",
      "mem": "0.3"
    },
    "567": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.172:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway-cam@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "602": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wyze.home.xyz:8554/driveway-south-floodcam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway-south-floodcam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.8",
      "cpu_average": "3",
      "mem": "0.3"
    },
    "603": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wyze.home.xyz:8554/hag-cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/hag-cam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.5",
      "cpu_average": "3",
      "mem": "0.3"
    },
    "1168": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.1.103:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "7.6",
      "cpu_average": "6",
      "mem": "0.4"
    },
    "6264": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 92.0,
  "detectors": {
    "coral": {
      "detection_start": 1716152245.183066,
      "inference_speed": 8.43,
      "pid": 451
    }
  },
  "gpu_usages": {
    "intel-qsv": {
      "gpu": "9.46%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 439
    },
    "recording": {
      "pid": 441
    }
  },
  "service": {
    "last_updated": 1716152245,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 223.9,
        "mount_type": "tmpfs",
        "total": 256.0,
        "used": 32.1
      },
      "/media/frigate/clips": {
        "free": 59984.2,
        "mount_type": "zfs",
        "total": 9344015.1,
        "used": 9284030.9
      },
      "/media/frigate/recordings": {
        "free": 59984.2,
        "mount_type": "zfs",
        "total": 9344015.1,
        "used": 9284030.9
      },
      "/tmp/cache": {
        "free": 929.2,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 24.5
      }
    },
    "temperatures": {
      
    },
    "uptime": 713,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
