### DISCUSSION TITLE
[Camera Support]: FFPROBE showing FPS: Unknown for main stream but showing correct FPS for sub stream.

### DISCUSSION THREAD

**Discussion by hmjgriffon1** [blakeblackshear/frigate#11433] [Camera Support]
### Describe the problem you are having

My camera is showing unknown for the FPS in the FFPROBE for the main stream only but shows the correct FPS for the sub stream, is this an issue?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

database:
  path: /config/frigate.db

mqtt:
  enabled: true
  host: 10.0.0.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous
  restream: false

record:
  enabled: true
  retain:
    days: 0
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 14

go2rtc:
  streams:
    living_room_cam:
    - ffmpeg:rtsp://admin:!password@10.0.0.7:554/Streaming/Channels/101
    - ffmpeg:living_room_cam#audio=aac
    living_room_cam_sub:
    - ffmpeg:rtsp://admin:!password@10.0.0.7:554/Streaming/Channels/102
    - ffmpeg:living_room_cam_sub#audio=aac
    office_cam:
    - rtsp://admin:!password@10.0.0.12:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - ffmpeg:office_cam#audio=opus
    office_cam_sub:
    - rtsp://admin:!password@10.0.0.12:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    - ffmpeg:office_cam_sub#audio=opus
    ptz_cam:
    - rtsp://admin:!password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46ZEwxOExyUjg=
    - ffmpeg:ptz_cam#audio=opus
    ptz_cam_sub:
    - rtsp://admin:!password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=01&authbasic=YWRtaW46ZEwxOExyUjg=
    - ffmpeg:ptz_cam_sub#audio=opus
#  log:
#    exec: trace
  webrtc:
    candidates:
    - 10.0.0.2:8555
    - stun:8555

cameras:
  living_room_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://admin:!password@10.0.0.7:554/Streaming/Channels/101
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://admin:!password@10.0.0.7:554/Streaming/Channels/102
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 6
    objects:
      track:
      - person

  office_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/office_cam
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/office_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    objects:
      track:
      - person

  ptz_cam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/ptz_cam
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/ptz_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    objects:
      track:
      - person
    onvif:
      host: 10.0.0.4
      port: 80
      user: admin
      password: !password
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zooming: absolute
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - zone_0
        return_preset: home
        timeout: 10
        movement_weights: 
    zones:
      zone_0:
        coordinates: 704,0,704,545,0,541,0,0
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":704},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua SD59225U-HNI

### Any other information that may be helpful

Sorry to bug the few guys who watch for new issues and helped me on some others but the help has been greatly appreciated.
