### DISCUSSION TITLE
[Support]: Frigate 0.14 support for 30 minute offset timezones (e.g. UTC + 5.30)

### DISCUSSION THREAD

**Discussion by rajil** [blakeblackshear/frigate#11445] [General Support] [answered]
### Describe the problem you are having

Hello,

There are a bunch of time zones which have an offset from UTC (listed [here](https://www.timeanddate.com/time/time-zones-interesting.html)) . Unfortunately frigate review/recording is not showing up for an offset time zone.

My setup is as follows:

Docker host on the server is set to UTC,
```
$ sudo timedatectl status
               Local time: Mon 2024-05-20 12:35:27 UTC
           Universal time: Mon 2024-05-20 12:35:27 UTC
                 RTC time: n/a
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
```

Frigate browser on my desktop is set to IST,
```
$ timedatectl status
               Local time: Mon 2024-05-20 18:06:21 IST
           Universal time: Mon 2024-05-20 12:36:21 UTC
                 RTC time: Mon 2024-05-20 12:36:21
                Time zone: Asia/Kolkata (IST, +0530)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

### Problem

When  i goto to review my alerts, it **plays** the preview of the camera event taken at 4:50 PM. Here is a partial screenshot of the preview/thumbnail

![image](https://github.com/blakeblackshear/frigate/assets/379266/822fd1e7-4203-4b13-b7bb-52f6aa17ea4f)

 When i click on the thumbnail, it opens the recording and shows an error message, "No recordings found for this time". A partial screenshot is shown below:
![image](https://github.com/blakeblackshear/frigate/assets/379266/76e90aa7-7fd9-4056-a4f6-0d80f926ec76)

### Temporary Workaround

If i change my desktop/browser to UTC, the recording plays fine.
```
[desktop] # timedatectl set-timezone UTC
[desktop] # timedatectl status
               Local time: Mon 2024-05-20 12:42:18 UTC
           Universal time: Mon 2024-05-20 12:42:18 UTC
                 RTC time: Mon 2024-05-20 12:42:18
                Time zone: UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
The preview/thumbnail is at UTC time now,

![image](https://github.com/blakeblackshear/frigate/assets/379266/8d970af4-5073-460c-92e6-18c10e28f403)

Clicking on the thumbnail, recording opens up and plays successfully. Here is a screenshot from the recording showing the camera time.
![image](https://github.com/blakeblackshear/frigate/assets/379266/023139f3-d9bd-4e90-9c4a-277a885b1f89)

### Version

0.14 dev-82d4bf8

### Frigate config file

```yaml
record:
  enabled: true
  sync_recordings: false
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects

objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  crop: true
  retain:
    default: 20
    objects:
      person: 30

ffmpeg:
# global_args: -hide_banner -loglevel warning -threads 2 -extra_hw_frames 8
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac


cameras:
  maingate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/maingate_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/maingate_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1,0.168,1,0,0.649,0
        - 0.002,0.055,0.41,0.058,0.414,0,0,0
    objects:
      track:
        - person
  sidealley:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sidealley_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sidealley_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0.883,0.279,0.112,0.285,0.055,0.289,0.031,0.274,0,0.002,0
        - 0.553,0.002,0.551,0.058,0.955,0.059,0.955,0
    objects:
      track:
        - person
  frontdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1,0.735,0.95,0.715,0.885,0.492,0.959,0.268,0.999,0.313
        - 0.551,0.001,0.551,0.061,0.96,0.065,0.958,0.002
    objects:
      track:
        - person
  bedroomback:
    enabled: true
    ffmpeg:
      global_args: -hide_banner -loglevel warning -threads 2 -extra_hw_frames 8
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroomback_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroomback_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360

  groundlobby:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/groundlobby_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/groundlobby_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  terracefront:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terracefront_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terracefront_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.531,0,0.5,0.303,1,0.504,1,0
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8

  terraceback:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraceback_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terraceback_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.016,0.001,0.015,0.034,0.264,0.036,0.266,0
  computerroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/computerroom_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/computerroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
  bedroomfront:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroomfront_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroomfront_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5
          min_area: 42000

  drawingroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drawingroom_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drawingroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.553,0.009,0.551,0.066,0.958,0.067,0.957,0.009
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
  diningroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/diningroom_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/diningroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.653,0.049,0.654,0.101,0.966,0.104,0.964,0.05
  kitchen:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          roles:
            - detect
            - record
#  road:
#    enabled: false
#    ffmpeg:
#      inputs:
#      - path: rtsp://127.0.0.1:8554/road_main
#        input_args: preset-rtsp-restream
#        roles:
#        - record
#      - path: rtsp://127.0.0.1:8554/road_sub
#        input_args: preset-rtsp-restream
#        roles:
#        - detect

#  computerroom2:
#    enabled: true
#    rtmp:
#      enabled: false
#    ffmpeg:
#      inputs:
#        - path: /dev/webcam0
#          roles:
#            - detect
#            - record
#            - rtmp
#      input_args: -f v4l2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        rtmp: -c copy -f rawvideo
#    detect:
#      width: 640
#      height: 480


go2rtc:
#  log:
#    rtsp: trace
  streams:
    maingate_main:
      - rtsp://192.168.1.12:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:maingate_main#audio=aac
    maingate_sub:
      - rtsp://192.168.1.12:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:maingate_sub#audio=aac
    sidealley_main:
      - rtsp://192.168.1.14:554/cam/realmonitor?channel=1&subtype=0
    sidealley_sub:
      - rtsp://192.168.1.14:554/cam/realmonitor?channel=1&subtype=1
    frontdoor_main:
      - rtsp://192.168.1.13:554/cam/realmonitor?channel=1&subtype=0
    frontdoor_sub:
      - rtsp://192.168.1.13:554/cam/realmonitor?channel=1&subtype=1
    road_main:
      - rtsp://192.168.1.25:554/cam/realmonitor?channel=1&subtype=1
    road_sub:
      - rtsp://192.168.1.25:554/cam/realmonitor?channel=1&subtype=0
    bedroomback_sub:
      - rtsp://192.168.1.18:80/videoSub
      - ffmpeg:bedroomback_sub#audio=aac
    bedroomback_main:
      # - ffmpeg:http://192.168.1.18/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=76754243dd
      - rtsp://192.168.1.18:80/videoMain
      - ffmpeg:bedroomback_main#audio=aac
    groundlobby_sub:
      - rtsp://192.168.1.17:80/videoSub
      - ffmpeg:groundlobby_sub#audio=aac
    groundlobby_main:
      - rtsp://192.168.1.17:80/videoMain
      - ffmpeg:groundlobby_main#audio=aac
    terraceback_sub:
      - rtsp://192.168.1.23:554/ch1/sub/av_stream
    terraceback_main:
      - rtsp://192.168.1.23:554/ch1/main/av_stream
    computerroom_sub:
      - rtsp://192.168.1.21:554/12
    computerroom_main:
      - rtsp://192.168.1.21:554/11
    bedroomfront_sub:
      - rtsp://192.168.1.19:80/videoSub
      - ffmpeg:bedroomfront_sub#audio=aac
    bedroomfront_main:
      - rtsp://192.168.1.19:80/videoMain
      - ffmpeg:bedroomfront_main#audio=aac
    drawingroom_sub:
      - rtsp://192.168.1.26:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:drawingroom_sub#audio=aac
    drawingroom_main:
      - rtsp://192.168.1.26:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:drawingroom_main#audio=aac
    diningroom_sub:
      - rtsp://192.168.1.33:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:diningroom_sub#audio=aac
    diningroom_main:
      - rtsp://192.168.1.33:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:diningroom_main#audio=aac
    terracefront_sub:
      - rtsp://192.168.1.24:554/cam/realmonitor?channel=1&subtype=1
    terracefront_main:
      - rtsp://192.168.1.24:554/cam/realmonitor?channel=1&subtype=0
    kitchen:
      - ffmpeg:http://192.168.1.31:8080?action=stream#video=h264#hardware

  webrtc:
    candidates:
      - 192.168.1.127:8555
#     - stun:8555
detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
#    num_threads: 3

birdseye:
  enabled: true
  quality: 1
  mode: continuous
  restream: true

camera_groups:
  Outdoor:
    order: 1
    icon: LuCar
    cameras:
      - frontdoor
      - maingate
      - sidealley
  Terrace:
    order: 2
    icon: LuCloud
    cameras:
      - terracefront
      - terraceback
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA
