### DISCUSSION TITLE
[Config Support]: Sorry, again - Parking cars

### DISCUSSION THREAD

**Discussion by frank2604** [blakeblackshear/frigate#11450] [Config Support] [answered]
### Describe the problem you are having

I tried to read and understand everything about the parking cars issues and tips & tricks but obviously I sill doing something wrong.

My goal is, that a car are is only detected and recorded when it enters the ramp (Carport_Zone_Auffahrt), not in the parking space (Carport_Zone_Parkplatz). The recording should stop when the car leaves the ramp, either to the road or to the parking space.

<img width="1292" alt="2024-05-20_16-15-06" src="https://github.com/blakeblackshear/frigate/assets/51050855/340f8950-e12b-43a3-85a9-81f52b07560e">

But what happend very often is this:

The car is coming from the road and enters the ramp. So far so good.

<img width="1512" alt="2024-05-20_16-20-38" src="https://github.com/blakeblackshear/frigate/assets/51050855/670c4059-bfc9-4f5a-9190-c6bf68ecabda">

But when it has left the ramp and stands on the parking space it becomes the still status for - in this example - 4 hours until the next car is coming.

<img width="1366" alt="2024-05-20_16-23-05" src="https://github.com/blakeblackshear/frigate/assets/51050855/62e2ef19-cbe8-4e32-ac7b-25dcc236f851">

I thought I managed this with my config below, but ... not.

Any recommendations?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.2.30
  port: 1883
  user: mqtt
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
  - person
  - car
  - cat
  - dog
  filters:
    person:
      threshold: 0.7
    car:
      threshold: 0.7
    cat:
      threshold: 0.7
    dog:
      threshold: 0.8

cameras:
  Carport_Kamera:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:xxx@192.168.2.xx:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://admin:xxx@192.168.2.xx:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
        - rtmp
    motion:
      mask:
      - 1278,3,1280,371,1026,373,963,325,989,224,756,146,726,151,762,184,639,209,514,160,653,132,650,1
    zones:
      Carport_Zone_Parkplatz:
        coordinates: 429,146,35,331,109,506,248,720,950,720,1024,365,968,326,984,281,708,193,608,177
        objects:
        - person
        - cat
        - dog
      Carport_Zone_Auffahrt:
        coordinates: 704,188,984,281,992,250,982,233,728,155,750,180
        objects:
        - person
        - car
        - cat
        - dog
    objects:
      filters:
        car:
          mask:
          - 1280,0,1280,299
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
        required_zones:
        - Carport_Zone_Parkplatz
        - Carport_Zone_Auffahrt
    snapshots:
      enabled: true
      retain:
        default: 30
      required_zones:
      - Carport_Zone_Parkplatz
      - Carport_Zone_Auffahrt
```

### Relevant log output

```shell
-
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB
