### DISCUSSION TITLE
[Config Support]: HTTP-FLV vs RTSP for newer Reolink cameras

### DISCUSSION THREAD

**Discussion by dlarkinsPonderosa** [blakeblackshear/frigate#11454] [Config Support] [answered]
### Describe the problem you are having

Is the HTTP-FLV recommendation for Reolink cameras still applicable for newer cameras?

I have an RLC-1212a that seems to crash go2rtc after about 12 hours (stream still works in the Reolink app, and audio still coming through on the streams in Frigate). I do have some errors that I can share, but I didn't want to waste time if the solution is to not use RTSP at all.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.104
  port: 1883
  user: xx
  password: yy
birdseye:

    # Optional: Enable birdseye view (default: shown below)
  enabled: true
        # Optional: Width of the output resolution (default: shown below)
  height: 1080
  width: 1920
                # Optional: Encoding quality of the mpeg1 feed (default: shown below)
                  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
                      # Optional: Mode of the view. Available options are: objects, motion, and continuous
                        #   objects - cameras are included if they have had a tracked object within the last 30 seconds
                          #   motion - cameras are included if motion was detected in the last 30 seconds
                            #   continuous - all cameras are included always
  mode: motion


detectors:
  coral:
    type: edgetpu
    device: usb


ffmpeg:
  output_args: # record audio
    record: preset-record-generic-audio-aac
model:
  path: plus://4aec12efe72d22ab1c5ab99a0867ae29

go2rtc:
  streams:
    garden_cam:
    - rtsp://admin:pw@192.168.1.a:554/h265Preview_01_main
    garden_cam_sub:
    - ffmpeg:garden_cam#video=h264#width=1920#height=1080#audio=aac#raw=-fpsmax 10#hardware=vaapi
    valley_cam:
    - rtsp://admin:pw@192.168.1.b:554/h264Preview_01_main
    valley_cam_sub:
    - ffmpeg:valley_cam#video=h264#width=1920#height=1080#audio=aac#raw=-fpsmax 10#hardware=vaapi
  webrtc:
    candidates:
    - 192.168.1.104:8555

cameras:
  #RECORD ONLY CAMERAS
  garden_record_only:
    record:
      enabled: true
      retain:
        days: 14
      export:
        timelapse_args: -vf setpts=0.00005*PTS -r 30
    ffmpeg:
      inputs:
      - path: /dev/zero
        input_args: -re -s 640x480 -f rawvideo -pix_fmt rgb24 -r 1
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/garden_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - record
        hwaccel_args: preset-vaapi
    detect:
      enabled: false
      height: 480
      width: 640
      fps: 1

  valley_record_only:
    record:
      enabled: true
      retain:
        days: 14
      export:
        timelapse_args: -vf setpts=0.00005*PTS -r 30
    ffmpeg:
      inputs:
      - path: /dev/zero
        input_args: -re -s 640x480 -f rawvideo -pix_fmt rgb24 -r 1
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/valley_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - record
        hwaccel_args: preset-vaapi
    detect:
      enabled: false
      height: 480
      width: 640
      fps: 1


# MAIN CAMERAS
  garden_cam:
    zones:
      garden:
        coordinates: 
          654,605,1020,377,1111,303,1268,169,1548,148,1718,187,1750,223,1920,287,1920,719,1920,1080,305,1080,215,908
      road:
        coordinates: 1920,0,1920,295,1765,228,1697,184,1576,80,1549,0
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 2
        post_capture: 2
        retain:
          default: 5
          mode: active_objects
          objects:
            person: 3
        objects:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
        - deer

      export:
        timelapse_args: -vf setpts=0.00005*PTS -r 30
    snapshots:
      enabled: true
      quality: 100

    mqtt:
      # Optional: height to resize the snapshot to (default: shown below)
      height: 640
      # Optional: jpeg encode quality (default: shown below)
      quality: 100

    objects:
      track:
      - person
      - face
      - license_plate
      - dog
      - cat
      - car
      - amazon
      - fedex
      - ups
      - package
      - deer
      filters:
        person:
          min_score: 0.8
          threshold: 0.93
          min_area: 700
        car:
          min_score: 0.8
          threshold: 0.92
          min_area: 800
          max_area: 60000
        cat:
          min_score: 0.65
          threshold: 0.85
        dog:
          min_score: 0.65
          threshold: 0.85
        deer:
          min_score: 0.65
          threshold: 0.85

    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/garden_cam
        input_args: preset-rtsp-restream
        roles:
        - record
        hwaccel_args: preset-vaapi
      - path: rtsp://127.0.0.1:8554/garden_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        hwaccel_args: preset-vaapi
    live:
      stream_name: garden_cam_sub

  valley_cam:
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 2
        post_capture: 2
        retain:
          default: 5
          mode: motion
          objects:
            person: 3
        objects:
        - person
        - face
        - dog
        - cat
        - deer

      export:
        timelapse_args: -vf setpts=0.00005*PTS -r 30
    snapshots:
      enabled: true
      quality: 100
    motion:
      contour_area: 4
      threshold: 23
      mask:
        - 976,727,1042,674,1077,570,1012,415,932,362,828,353,674,392,614,519,653,605,727,706,867,712
        - 0,0,493,0,1597,0,1783,0,1920,0,1920,404,1801,389,1694,368,1638,347,1519,341,1427,332,1246,344,1104,323,976,329,813,344,730,368,659,362,466,368,472,490,356,487,261,493,163,516,0,632
        - 1920,451,1742,522,1629,573,1635,742,1920,718
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.1.201
      # Optional: ONVIF port for device (default: shown below).
      port: 8000
      user: admin
      # Optional: password for login.
      password: acd
    mqtt:
      # Optional: height to resize the snapshot to (default: shown below)
      height: 640
      # Optional: jpeg encode quality (default: shown below)
      quality: 100

    objects:
      track:
      - person
      - face
      - dog
      - cat
      - deer
      filters:
        person:
          min_score: 0.8
          threshold: 0.93
          min_area: 700
        cat:
          min_score: 0.65
          threshold: 0.85
        dog:
          min_score: 0.65
          threshold: 0.85
        deer:
          min_score: 0.65
          threshold: 0.85

    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/valley_cam
        input_args: preset-rtsp-restream
        roles:
        - record
        hwaccel_args: preset-vaapi
      - path: rtsp://127.0.0.1:8554/valley_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        hwaccel_args: preset-vaapi
    live:
      stream_name: valley_cam_sub
```

### Relevant log output

```shell
2024-05-20 10:01:30.278734673  [2024-05-20 10:01:30] frigate.video                  ERROR   : garden_cam: Unable to read frames from ffmpeg process.
2024-05-20 10:01:30.278788247  [2024-05-20 10:01:30] frigate.video                  ERROR   : garden_cam: ffmpeg process is not running. exiting capture thread...
2024-05-20 10:01:35.075847504  [2024-05-20 10:01:35] watchdog.garden_cam            ERROR   : Ffmpeg process crashed unexpectedly for garden_cam.
2024-05-20 10:01:35.075860814  [2024-05-20 10:01:35] watchdog.garden_cam            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-05-20 10:01:35.075977023  [2024-05-20 10:01:35] ffmpeg.garden_cam.detect       ERROR   : [rtsp @ 0x641b62ffee40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2024-05-20 10:01:35.075979151  [2024-05-20 10:01:35] ffmpeg.garden_cam.detect       ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-05-20 10:01:35.075980290  [2024-05-20 10:01:35] ffmpeg.garden_cam.detect       ERROR   : Output file #0 does not contain any stream
2024-05-20 10:01:39.781659063  [2024-05-20 10:01:39] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for garden_cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-20 10:01:39.788164466  [ERROR:0@3256.514] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-05-20 10:01:39.788167044  
2024-05-20 10:01:39.788168237  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
