### DISCUSSION TITLE
Audio lags behind video 2 seconds in recordings

### DISCUSSION THREAD

**Discussion by iamandyogden** [blakeblackshear/frigate#11470] [Camera Support]
### Describe the problem you are having

I'm using a Reolink E1 Zoom, connected to Frigate.  Frigate is running in docker, which in turn is running on an 8Gb raspberry pi 5 with a USB coral.

When I view webRTC the sound is in sync.  However, when I watch back the recordings there is roughly a 2 second lag on the audio.

As you'll see from the config I have two cameras running.  hallway_cam is a Eufy 2k which only has a single stream.  This camera has no audio issues when watching recordings.

Georges_cam it the Reolink E1 Zoom and despite using the recommend config from Frigate for this brand, always has a 2 second delay on the audio.  I recently added #async after reading this post, which had no effect https://github.com/blakeblackshear/frigate/issues/7019

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  # Required: host name
  host: 192.168.145.160
  # Optional: topic prefix
  topic_prefix: frigate
  user: username
  password: password
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    hallway_cam:
      - rtsp://username:password@192.168.145.206/live0
      - "ffmpeg:hallway#audio=opus"
    georges_cam:
      - "ffmpeg:http://192.168.145.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=aac#async"
    georges_cam_sub:
      - "ffmpeg:http://192.168.145.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password"
   

      
cameras:
  hallway_cam: #
    enabled: true
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://username:password@192.168.145.206/live0
        input_args: preset-rtsp-generic
        roles:
        - record
        - detect
        
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    detect:
      enabled: true # Detection is enabled
      width: 1920 # The Cameras resolution
      height: 1080 # The Cameras resolution
    objects:
      track:
        - person
        - cat
        - package
        - face
    snapshots:
      enabled: true
      timestamp: false
    zones:
      Front_Door:
        coordinates: 164,1080,0,1080,0,799,0,531,83,359
      Kitchen:
        coordinates: 1817,612,1268,391,1277,197,1486,222,1896,332
      Stairs:
        coordinates: 1814,1080,1025,1080,857,935,967,474,1375,660,1899,715
      Living_Room:
        coordinates: 896,103,1006,127,1776,197,932,56
      Letterbox:
        coordinates: 79,523,123,760,97,880,33,657
      Office:
        coordinates: 708,828,948,1080,532,1080,429,881
  
  georges_cam: #
    ffmpeg:
      
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/georges_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/georges_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    detect:
      enabled: true # Detection is enabled
    objects:
      track:
        - person
        - cat
        - package
        - face
    snapshots:
      enabled: true
      timestamp: false
```

### Relevant log output

```shell
2024-05-21 14:25:16.841639374  [INFO] Preparing Frigate...
2024-05-21 14:25:17.005537808  [INFO] Starting Frigate...
2024-05-21 14:25:17.825616050  Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/_pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned
2024-05-21 14:25:18.248661421  [2024-05-21 14:25:18] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-05-21 14:25:26.327542102  [2024-05-21 14:25:26] peewee_migrate.logs            INFO    : Starting migrations
2024-05-21 14:25:26.331409397  [2024-05-21 14:25:26] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-21 14:25:26.340311389  [2024-05-21 14:25:26] frigate.app                    INFO    : Recording process started: 303
2024-05-21 14:25:26.345048125  [2024-05-21 14:25:26] frigate.app                    INFO    : go2rtc process pid: 100
2024-05-21 14:25:26.403870551  [2024-05-21 14:25:26] detector.coral                 INFO    : Starting detection process: 312
2024-05-21 14:25:26.403881588  [2024-05-21 14:25:26] frigate.app                    INFO    : Output process started: 314
2024-05-21 14:25:26.406252335  [2024-05-21 14:25:26] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-05-21 14:25:26.536881919  [2024-05-21 14:25:26] frigate.app                    INFO    : Camera processor started for hallway_cam: 339
2024-05-21 14:25:26.570387306  [2024-05-21 14:25:26] frigate.app                    INFO    : Camera processor started for georges_cam: 340
2024-05-21 14:25:26.571066562  [2024-05-21 14:25:26] frigate.app                    INFO    : Capture process started for hallway_cam: 341
2024-05-21 14:25:26.593781633  [2024-05-21 14:25:26] frigate.app                    INFO    : Capture process started for georges_cam: 350
2024-05-21 14:25:29.082553912  [2024-05-21 14:25:29] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-05-21 14:27:12.697767114  [2024-05-21 14:27:12] frigate.video                  ERROR   : hallway_cam: Unable to read frames from ffmpeg process.
2024-05-21 14:27:12.697926298  [2024-05-21 14:27:12] frigate.video                  ERROR   : hallway_cam: ffmpeg process is not running. exiting capture thread...
2024-05-21 14:27:16.633058656  [2024-05-21 14:27:16] watchdog.hallway_cam           ERROR   : Ffmpeg process crashed unexpectedly for hallway_cam.
2024-05-21 14:27:16.633348914  [2024-05-21 14:27:16] watchdog.hallway_cam           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-05-21 14:27:16.633552950  [2024-05-21 14:27:16] ffmpeg.hallway_cam.detect      ERROR   : [aac @ 0x5555a4484200] Queue input is backward in time
2024-05-21 14:27:16.633696746  [2024-05-21 14:27:16] ffmpeg.hallway_cam.detect      ERROR   :     Last message repeated 1 times
2024-05-21 14:27:16.633924133  [2024-05-21 14:27:16] ffmpeg.hallway_cam.detect      ERROR   : [segment @ 0x5555a4423b80] Non-monotonous DTS in output stream 0:0; previous: 2690, current: 2690; changing to 2691. This may result in incorrect timestamps in the output file.
2024-05-21 14:27:16.634100059  [2024-05-21 14:27:16] ffmpeg.hallway_cam.detect      ERROR   : [segment @ 0x5555a4423b80] Non-monotonous DTS in output stream 0:0; previous: 2691, current: 2691; changing to 2692. This may result in incorrect timestamps in the output file.
2024-05-21 14:27:16.634242873  [2024-05-21 14:27:16] ffmpeg.hallway_cam.detect      ERROR   : [segment @ 0x5555a4423b80] Non-monotonous DTS in output stream 0:0; previous: 2692, current: 2691; changing to 2693. This may result in incorrect timestamps in the output file.
2024-05-21 14:28:06.646820811  [2024-05-21 14:28:06] watchdog.hallway_cam           INFO    : No frames received from hallway_cam in 20 seconds. Exiting ffmpeg...
2024-05-21 14:28:06.646825645  [2024-05-21 14:28:06] watchdog.hallway_cam           INFO    : Waiting for ffmpeg to exit gracefully...
2024-05-21 14:28:06.677741806  [2024-05-21 14:28:06] frigate.video                  ERROR   : hallway_cam: Unable to read frames from ffmpeg process.
2024-05-21 14:28:06.677746806  [2024-05-21 14:28:06] frigate.video                  ERROR   : hallway_cam: ffmpeg process is not running. exiting capture thread...
2024-05-21 14:28:16.681929148  [2024-05-21 14:28:16] watchdog.hallway_cam           ERROR   : Ffmpeg process crashed unexpectedly for hallway_cam.
2024-05-21 14:28:16.681935185  [2024-05-21 14:28:16] watchdog.hallway_cam           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-05-21 14:28:16.681937889  [2024-05-21 14:28:16] ffmpeg.hallway_cam.detect      ERROR   : [segment @ 0x55559a017b80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```

### FFprobe output from your camera

```shell
[{"return_code":1,"stderr":"","stdout":""},{"return_code":1,"stderr":"","stdout":""}]
```

### Frigate stats

```json
{
    "cameras": {
        "georges_cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 350,
            "detection_enabled": 1,
            "detection_fps": 2.1,
            "ffmpeg_pid": 357,
            "pid": 340,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "hallway_cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 341,
            "detection_enabled": 1,
            "detection_fps": 6.1,
            "ffmpeg_pid": 749,
            "pid": 339,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "80": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "84": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "100": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "1.3",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "109": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "111": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "2.0",
            "cpu_average": "1",
            "mem": "3.7"
        },
        "127": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "143": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "163": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "296": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "1.2"
        },
        "303": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.0",
            "cpu_average": "2",
            "mem": "1.6"
        },
        "311": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "312": {
            "cmdline": "frigate.detector.coral",
            "cpu": "4.7",
            "cpu_average": "4",
            "mem": "1.6"
        },
        "314": {
            "cmdline": "frigate.output       ",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "1.4"
        },
        "328": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "329": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "330": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "339": {
            "cmdline": "frigate.process:hallway_cam",
            "cpu": "5.4",
            "cpu_average": "3",
            "mem": "1.7"
        },
        "340": {
            "cmdline": "frigate.process:georges_cam",
            "cpu": "1.3",
            "cpu_average": "2",
            "mem": "1.7"
        },
        "341": {
            "cmdline": "frigate.capture:hallway_cam",
            "cpu": "4.0",
            "cpu_average": "3",
            "mem": "1.5"
        },
        "350": {
            "cmdline": "frigate.capture:georges_cam",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "1.5"
        },
        "357": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -i rtsp://127.0.0.1:8554/georges_cam_sub -r 5 -vf fps=5,scale=896:672 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "4.0",
            "cpu_average": "5",
            "mem": "0.6"
        },
        "360": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -stimeout 5000000 -i rtsp://127.0.0.1:8554/georges_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/georges_cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "361": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.145.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/102a770a2226d6d8fb4d6d73d0e640a7",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "369": {
            "cmdline": "ffmpeg -hide_banner -v error -use_wallclock_as_timestamps 1 -async 1 -fflags nobuffer -flags low_delay -i http://192.168.145.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6d069c2eda429a321cd739aed1d7ea64",
            "cpu": "1.3",
            "cpu_average": "1",
            "mem": "0.6"
        },
        "749": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.145.206/live0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/hallway_cam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "12.1",
            "cpu_average": "11",
            "mem": "0.9"
        },
        "2071": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 8.2,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 9.04,
            "pid": 312
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 100
        },
        "logger": {
            "pid": 296
        },
        "recording": {
            "pid": 303
        }
    },
    "service": {
        "last_updated": 1716298755,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 248.5,
                "mount_type": "tmpfs",
                "total": 256,
                "used": 7.5
            },
            "/media/frigate/clips": {
                "free": 64182.4,
                "mount_type": "ext4",
                "total": 119406.9,
                "used": 49137.2
            },
            "/media/frigate/recordings": {
                "free": 64182.4,
                "mount_type": "ext4",
                "total": 119406.9,
                "used": 49137.2
            },
            "/tmp/cache": {
                "free": 64182.4,
                "mount_type": "overlay",
                "total": 119406.9,
                "used": 49137.2
            }
        },
        "temperatures": {},
        "uptime": 829,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink E1 Zoom

### Any other information that may be helpful

Please bear in mind that I'm a beginner who has got this far by following step-by-step instructions.  I can change the config and edit the docker compose, but more than that and I'd ask that you please provide an explanation of how to do what you're suggesting.
