### DISCUSSION TITLE
[Support]: Unable to open go2rtc api page

### DISCUSSION THREAD

**Discussion by hapklaar** [blakeblackshear/frigate#11481] [General Support] [answered]
### Describe the problem you are having

Frigate works fine with go2rtc restream. Only issue is the api page at http://192.168.1.3:5000/api/go2rtc/streams won't open. I'm greeted with an '500 Internal Server Error'.

Log for frigate shows an error at that time (see below). Go2rtc log is clean.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.2
  user: mqtt
  password: mqtt

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

snapshots:
  enabled: True
  bounding_box: True
  timestamp: False

birdseye:
  enabled: true
  mode: continuous

go2rtc:
  streams:
    Voor:
    - rtsp://admin:pass@192.168.1.7:554/h264Preview_01_main
    - ffmpeg:Voor#audio=opus
    Voor_sub:
    - rtsp://admin:pass@192.168.1.7:554/h264Preview_01_sub
    webrtc:
      candidates:
        - 192.168.1.3:8555
        - 192.168.1.2:8555
        - stun:8555

cameras:
  Voor:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/Voor
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Voor_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_area: 150
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 3
          mode: motion
    zones:
      zone_0:
        coordinates: 0,1920,2560,1920,2560,905,0,961
    mqtt:
      timestamp: false
      bounding_box: true
      crop: false
      quality: 100
      height: 1920
      
logger:
  logs:
    ffmpeg.Voor.*: debug
```

### Relevant log output

```shell
2024-05-22 15:15:37.025155879  [2024-05-22 15:15:37] frigate.http                   ERROR   : Exception on /go2rtc/streams [GET]
2024-05-22 15:15:37.025160188  Traceback (most recent call last):
2024-05-22 15:15:37.025162044    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2024-05-22 15:15:37.025163560      response = self.full_dispatch_request()
2024-05-22 15:15:37.025165189    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2024-05-22 15:15:37.025166602      rv = self.handle_user_exception(e)
2024-05-22 15:15:37.025168192    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2024-05-22 15:15:37.025169466      rv = self.dispatch_request()
2024-05-22 15:15:37.025170990    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2024-05-22 15:15:37.025172451      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-05-22 15:15:37.025173859    File "/opt/frigate/frigate/http.py", line 1374, in go2rtc_streams
2024-05-22 15:15:37.025175153      for producer in data.get("producers", []):
2024-05-22 15:15:37.025176491  TypeError: 'NoneType' object is not iterable
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
    "cameras": {
        "Voor": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 10,
            "capture_pid": 343,
            "detection_enabled": 1,
            "detection_fps": 36,
            "ffmpeg_pid": 348,
            "pid": 342,
            "process_fps": 10,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "79": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "85": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "/config/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "4.0",
            "cpu_average": "3",
            "mem": "0.2"
        },
        "112": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "113": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "3.6",
            "cpu_average": "2",
            "mem": "4.7"
        },
        "118": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "147": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "148": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "149": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "293": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "295": {
            "cmdline": "frigate.recording_manager",
            "cpu": "1.2",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "304": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "305": {
            "cmdline": "frigate.detector.coral1",
            "cpu": "2.7",
            "cpu_average": "1",
            "mem": "0.8"
        },
        "308": {
            "cmdline": "frigate.detector.coral2",
            "cpu": "2.7",
            "cpu_average": "1",
            "mem": "0.8"
        },
        "309": {
            "cmdline": "frigate.output       ",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "314": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "325": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "342": {
            "cmdline": "frigate.process:Voor ",
            "cpu": "24.1",
            "cpu_average": "12",
            "mem": "1.5"
        },
        "343": {
            "cmdline": "frigate.capture:Voor ",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "1.4"
        },
        "348": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Voor_sub -r 10 -vf fps=10,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.6",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "352": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Voor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Voor@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.7",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "1118": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 36,
    "detectors": {
        "coral1": {
            "detection_start": 0,
            "inference_speed": 6.6,
            "pid": 305
        },
        "coral2": {
            "detection_start": 0,
            "inference_speed": 6.61,
            "pid": 308
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "0.27%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 88
        },
        "logger": {
            "pid": 293
        },
        "recording": {
            "pid": 295
        }
    },
    "service": {
        "last_updated": 1716383984,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 154.3,
                "mount_type": "tmpfs",
                "total": 156,
                "used": 1.7
            },
            "/media/frigate/clips": {
                "free": 23554.8,
                "mount_type": "ext4",
                "total": 200502,
                "used": 166691.1
            },
            "/media/frigate/recordings": {
                "free": 23554.8,
                "mount_type": "ext4",
                "total": 200502,
                "used": 166691.1
            },
            "/tmp/cache": {
                "free": 949.9,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 3.8
            }
        },
        "temperatures": {
            "apex_0": 82.05,
            "apex_1": 79.8
        },
        "uptime": 548,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

Tried a couple of different go2rtc versions besides the built-in one, but all behave the same regarding this issue
