### DISCUSSION TITLE
[Support]: Raspberry Pi 5 - Preview Errors

### DISCUSSION THREAD

**Discussion by stuartb55** [blakeblackshear/frigate#11486] [General Support] [answered]
### Describe the problem you are having

Running Frigate on a Raspberry Pi 5 I get an error message for each camera in the log on the hour, every hour.

I also get 404's in the console:
![image](https://github.com/blakeblackshear/frigate/assets/1265100/736bc3fd-7825-4cbc-9a1c-41696df70217)

Also the status bar at the bottom reports the GPU incorrectly:
![image](https://github.com/blakeblackshear/frigate/assets/1265100/a2415e94-81fe-4089-8b11-6de0427ae18c)

### Version

dev-01e387e-rpi

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.76
  user: frigate
  password: *

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://c5e89d47a846556300a52e11eb47acbe

telemetry:
  version_check: false

ui:
  timezone: Europe/London

detect:
  width: 640
  height: 480
  fps: 7
  max_disappeared: 100

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 45
    post_capture: 45
    objects:
      - person
      - face
      - car
      - package
      - amazon
    retain:
      mode: active_objects
      objects:
        person: 10

objects:
  track:
    - person
    - face
    - car
    - package
    - amazon
    - license_plate
    - fedex
    - cat
    - dog
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

motion:
  threshold: 40

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 7
    objects:
      person: 10

birdseye:
  enabled: true
  mode: objects

audio:
  enabled: false
  filters:
    speech:
      threshold: 0.85

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    front:
      - rtsp://admin:*@192.168.20.25:554/h265Preview_01_main
      - ffmpeg:front#audio=opus
    front_sub: rtsp://admin:*@192.168.20.25:554/h264Preview_01_sub
    garage:
      - rtsp://admin:*@192.168.20.13:554/h264Preview_01_main
      - ffmpeg:garage#audio=opus
    garage_sub: rtsp://admin:*@192.168.20.13:554/h264Preview_01_sub
    rear:
      - rtsp://admin:*@192.168.20.14:554/h264Preview_01_main
      - ffmpeg:rear#audio=opus
    rear_sub: rtsp://admin:*@192.168.20.14:554/h264Preview_01_sub
    garden:
      - rtsp://admin:*@192.168.20.16:554/h264Preview_01_main
      - ffmpeg:garden#audio=opus
    garden_sub: rtsp://admin:*@192.168.20.16:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.1.165:8555

cameras:
  front:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_sub
          hwaccel_args: preset-rpi-64-h264
          roles:
            - detect
    detect:
      width: 640
      height: 360
    zones:
      drive:
        coordinates: 
          0.131,1,0.313,0.491,0.456,0.173,0.588,0.184,0.716,0.224,0.87,0.226,0.997,0.097,1,1
        inertia: 3
    motion:
      mask: 0.301,0.061,0.014,0.064,0.012,0.03,0.301,0.03
    objects:
      filters:
        car: {}
      mask: 0.456,0.167,0.292,0.519,0.106,1,0.001,1,0.001,0,0.871,0,0.87,0.209
    review:
      alerts:
        required_zones: drive

  garage:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/garage_sub
          roles:
            - detect
    objects:
      mask: 0,0,1,0,1,0.387,0.811,0.216,0.488,0.157,0,0.177
    motion:
      mask: 0.025,0.036,0.313,0.032,0.313,0.062,0.025,0.064

  rear:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rear
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/rear_sub
          roles:
            - detect
    motion:
      mask: 0.026,0.064,0.314,0.063,0.315,0.033,0.026,0.033

  garden:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/garden_sub
          roles:
            - detect
    motion:
      mask: 0.025,0.035,0.315,0.038,0.313,0.062,0.024,0.059

camera_groups:
  Front:
    order: 1
    icon: LuParkingSquare
    cameras:
      - front
      - garage
  Back:
    order: 2
    icon: LuMountainSnow
    cameras:
      - garden
      - rear
```

### Relevant log output

```shell
2024-05-22 17:27:55.346190875  [INFO] Preparing Frigate...
2024-05-22 17:27:55.482232139  [INFO] Starting Frigate...
2024-05-22 17:27:56.690032090  Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/_pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned
2024-05-22 17:27:57.715925589  [2024-05-22 17:27:57] frigate.app                    INFO    : Starting Frigate (0.14.0-01e387e)
2024-05-22 17:27:57.715931311  [2024-05-22 17:27:57] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-05-22 17:27:57.717990321  [2024-05-22 17:27:57] frigate.util.config            INFO    : frigate config does not need migration...
2024-05-22 17:27:58.138203095  [2024-05-22 17:27:58] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2024-05-22 17:28:02.204130359  [2024-05-22 17:28:02] peewee_migrate.logs            INFO    : Starting migrations
2024-05-22 17:28:02.205226771  [2024-05-22 17:28:02] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-22 17:28:02.873016652  [2024-05-22 17:28:02] frigate.app                    INFO    : Recording process started: 330
2024-05-22 17:28:02.894669157  [2024-05-22 17:28:02] frigate.app                    INFO    : Recording process started: 332
2024-05-22 17:28:02.896457943  [2024-05-22 17:28:02] frigate.app                    INFO    : go2rtc process pid: 99
2024-05-22 17:28:02.943282045  [2024-05-22 17:28:02] detector.coral                 INFO    : Starting detection process: 359
2024-05-22 17:28:02.947396248  [2024-05-22 17:28:02] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-05-22 17:28:05.620141635  [2024-05-22 17:28:02] frigate.app                    INFO    : Output process started: 361
2024-05-22 17:28:05.620547785  [2024-05-22 17:28:03] frigate.app                    INFO    : Camera processor started for front: 379
2024-05-22 17:28:05.620819249  [2024-05-22 17:28:03] frigate.app                    INFO    : Camera processor started for garage: 380
2024-05-22 17:28:05.620931324  [2024-05-22 17:28:03] frigate.app                    INFO    : Camera processor started for rear: 383
2024-05-22 17:28:05.621067825  [2024-05-22 17:28:03] frigate.app                    INFO    : Camera processor started for garden: 386
2024-05-22 17:28:05.621195973  [2024-05-22 17:28:03] frigate.app                    INFO    : Capture process started for front: 391
2024-05-22 17:28:05.621354770  [2024-05-22 17:28:03] frigate.app                    INFO    : Capture process started for garage: 406
2024-05-22 17:28:05.621459586  [2024-05-22 17:28:03] frigate.app                    INFO    : Capture process started for rear: 416
2024-05-22 17:28:05.621742050  [2024-05-22 17:28:03] frigate.app                    INFO    : Capture process started for garden: 421
2024-05-22 17:28:05.625832550  [2024-05-22 17:28:05] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-05-22 18:00:00.366913009  [2024-05-22 18:00:00] frigate.output.preview         ERROR   : Error saving preview for rear :: Input #0, concat, from '/dev/stdin':
2024-05-22 18:00:00.366925602    Duration: N/A, start: 0.000000, bitrate: N/A
2024-05-22 18:00:00.366927176      Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 240x180, 25 tbr, 25 tbn, 25 tbc
2024-05-22 18:00:00.366932917  [NULL @ 0x5555b8e1d200] Unable to find a suitable output format for ''
2024-05-22 18:00:00.366935102  : Invalid argument
2024-05-22 18:00:00.366935750
2024-05-22 18:00:00.473985700  [2024-05-22 18:00:00] frigate.output.preview         ERROR   : Error saving preview for garage :: Input #0, concat, from '/dev/stdin':
2024-05-22 18:00:00.473990107    Duration: N/A, start: 0.000000, bitrate: N/A
2024-05-22 18:00:00.473991644      Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 240x180, 25 tbr, 25 tbn, 25 tbc
2024-05-22 18:00:00.473992830  [NULL @ 0x5555ab73ab20] Unable to find a suitable output format for ''
2024-05-22 18:00:00.473993607  : Invalid argument
2024-05-22 18:00:00.473994274
2024-05-22 18:00:00.513937131  [2024-05-22 18:00:00] frigate.output.preview         ERROR   : Error saving preview for garden :: Input #0, concat, from '/dev/stdin':
2024-05-22 18:00:00.513942298    Duration: N/A, start: 0.000000, bitrate: N/A
2024-05-22 18:00:00.513943780      Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 240x180, 25 tbr, 25 tbn, 25 tbc
2024-05-22 18:00:00.513944909  [NULL @ 0x555641c126d0] Unable to find a suitable output format for ''
2024-05-22 18:00:00.513945650  : Invalid argument
2024-05-22 18:00:00.513946335
2024-05-22 18:00:00.554905846  [2024-05-22 18:00:00] frigate.output.preview         ERROR   : Error saving preview for front :: Input #0, concat, from '/dev/stdin':
2024-05-22 18:00:00.554911124    Duration: N/A, start: 0.000000, bitrate: N/A
2024-05-22 18:00:00.554912735      Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 320x180, 25 tbr, 25 tbn, 25 tbc
2024-05-22 18:00:00.554913957  [NULL @ 0x5555cb0bb5b0] Unable to find a suitable output format for ''
2024-05-22 18:00:00.554914716  : Invalid argument
2024-05-22 18:00:00.554915346
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.6-0+deb11u1+rpt5 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt5 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:*@192.168.20.25:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000250, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"cameras":{"front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":391,"detection_enabled":true,"detection_fps":5.1,"ffmpeg_pid":418,"pid":379,"process_fps":7.1,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":406,"detection_enabled":true,"detection_fps":9.0,"ffmpeg_pid":423,"pid":380,"process_fps":7.1,"skipped_fps":0.0},"garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":421,"detection_enabled":true,"detection_fps":20.6,"ffmpeg_pid":436,"pid":386,"process_fps":7.1,"skipped_fps":0.0},"rear":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.9,"capture_pid":416,"detection_enabled":true,"detection_fps":9.2,"ffmpeg_pid":426,"pid":383,"process_fps":6.9,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"113":{"cmdline":"python3 -u -m frigate","cpu":"3.3","cpu_average":"3","mem":"4.9"},"114":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"124":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"159":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15959":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"299":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"1.7"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"330":{"cmdline":"frigate.recording_manager","cpu":"4.9","cpu_average":"5","mem":"2.2"},"332":{"cmdline":"frigate.review_segment_manager","cpu":"0.9","cpu_average":"0","mem":"1.9"},"358":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(62)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"359":{"cmdline":"frigate.detector.coral","cpu":"9.7","cpu_average":"6","mem":"2.0"},"361":{"cmdline":"frigate.output       ","cpu":"5.9","cpu_average":"4","mem":"2.0"},"379":{"cmdline":"frigate.process:front","cpu":"3.7","cpu_average":"4","mem":"2.0"},"380":{"cmdline":"frigate.process:garage","cpu":"4.6","cpu_average":"3","mem":"2.1"},"383":{"cmdline":"frigate.process:rear ","cpu":"3.9","cpu_average":"2","mem":"2.0"},"386":{"cmdline":"frigate.process:garden","cpu":"8.9","cpu_average":"7","mem":"2.0"},"391":{"cmdline":"frigate.capture:front","cpu":"0.8","cpu_average":"0","mem":"1.9"},"406":{"cmdline":"frigate.capture:garage","cpu":"1.0","cpu_average":"0","mem":"1.9"},"416":{"cmdline":"frigate.capture:rear ","cpu":"1.1","cpu_average":"0","mem":"1.9"},"418":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/front_sub -r 7 -vf fps=7,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.0","cpu_average":"1","mem":"0.6"},"421":{"cmdline":"frigate.capture:garden","cpu":"1.0","cpu_average":"0","mem":"1.9"},"423":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/garage_sub -r 7 -vf fps=7,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"1","mem":"0.6"},"426":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear_sub -r 7 -vf fps=7,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"2","mem":"0.6"},"43":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"436":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/garden_sub -r 7 -vf fps=7,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"2","mem":"0.6"},"44":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"441":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"1","mem":"0.6"},"444":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/rear@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.6"},"445":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"0","mem":"0.6"},"447":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.14.0-01e387e -rtsp_transport tcp -stimeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"0","mem":"0.6"},"457":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"462":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"467":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"472":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"478":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"83":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"9063":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(51)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"94":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"99":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"12.9","cpu_average":"12","mem":"0.5"},"frigate.full_system":{"cpu":"22.9","mem":"18.9"}},"detection_fps":43.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.27,"pid":359}},"gpu_usages":{"rpi-v4l2m2m":{"gpu":"","mem":""}},"processes":{"go2rtc":{"pid":99},"logger":{"pid":299},"recording":{"pid":330},"review_segment":{"pid":332}},"service":{"last_updated":1716400188,"latest_version":"disabled","storage":{"/dev/shm":{"free":503.7,"mount_type":"tmpfs","total":512.0,"used":8.3},"/media/frigate/clips":{"free":114559.6,"mount_type":"ext4","total":1876684.3,"used":1762108.6},"/media/frigate/recordings":{"free":114559.6,"mount_type":"ext4","total":1876684.3,"used":1762108.6},"/tmp/cache":{"free":1765.8,"mount_type":"tmpfs","total":1907.4,"used":141.5}},"temperatures":{},"uptime":4905,"version":"0.14.0-01e387e"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink
