### DISCUSSION TITLE
[Support]: Cannot get started

### DISCUSSION THREAD

**Discussion by joshuisken** [blakeblackshear/frigate#11490] [General Support]
### Describe the problem you are having

Using docker stable and 0.12.1 release cannot get started with minimal config. No frames have been received.

I tried the attached docker-compose.yml, with some commented options as well. BTW, I also tried directly from the github repo today.

ffmpeg crashes whereas ffprobe responds normally. Both on /dev/video0 and on rstp:... streams.
I added a logging command in the container code to print the failing ffmpeg commands. 
Not being an expert on ffmpeg, so I have no clue how to solve this.

Attached is part of the docker log, grepped on `ffmpeg`

The attached probe is obtained with:
`docker exec -ti frigate  "ffprobe rtsp://192.168.1.11:554/user=admin_password=_channel=1_stream=0.sdp"`

I hope someone can help me. Both cameras work fine using a short python script with opencv2 and also with ffplay on the host system. Host is ubuntu 22.04 with ffmpeg version 4.4.2 and opencv2 version 4.5.4.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: false

logger:
  # Optional: default log level (default: shown below)
  default: debug
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error

cameras:
  # Locally connect Foscam
  znova_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: /dev/video0
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
  # Hiseeu Model HB612-3.6, HSY-HB612-1901, 2MP
  voordeur:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://191.168.1.11:554/user=admin_password=_channel=1_stream=0.sdp
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
```

### Relevant log output

```shell
frigate  | 2024-05-22 19:37:50.223871663  [2024-05-22 19:37:50] watchdog.voordeur              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-05-22 19:37:50.224024426  [2024-05-22 19:37:50] ffmpeg.voordeur.detect         ERROR   : [tcp @ 0x64ea6e83d140] Connection to tcp://191.168.1.11:554?timeout=5000000 failed: Connection timed out
frigate  | 2024-05-22 19:37:50.224031779  [2024-05-22 19:37:50] ffmpeg.voordeur.detect         ERROR   : rtsp://191.168.1.11:554/user=admin_password=_channel=1_stream=0.sdp: Connection timed out
frigate  | 2024-05-22 19:37:50.233121012  [2024-05-22 19:37:50] watchdog.znova_cam             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-05-22 19:37:50.233272063  [2024-05-22 19:37:50] ffmpeg.znova_cam.detect        ERROR   : Option user_agent not found.
frigate  | 2024-05-22 19:37:50.429912240  [2024-05-22 19:37:50] watchdog.voordeur              INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-05-22 19:37:50.429923425  [2024-05-22 19:37:50] watchdog.znova_cam             INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-05-22 19:37:50.430016604  [2024-05-22 19:37:50] watchdog.znova_cam             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-05-22 19:37:50.430019320  [2024-05-22 19:37:50] watchdog.voordeur              INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-05-22 19:37:57.963239603  [2024-05-22 19:37:57] frigate.config                 ERROR   : ffmpeg command: 'ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i /dev/video0 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:'
frigate  | 2024-05-22 19:38:28.013097918  [2024-05-22 19:38:28] frigate.config                 ERROR   : ffmpeg command: 'ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://191.168.1.11:554/user=admin_password=_channel=1_stream=0.sdp -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:'
frigate  | 2024-05-22 19:38:28.358713499  [2024-05-22 19:38:28] frigate.video                  ERROR   : znova_cam: Unable to read frames from ffmpeg process.
frigate  | 2024-05-22 19:38:28.358871675  [2024-05-22 19:38:28] frigate.video                  ERROR   : znova_cam: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-05-22 19:38:33.071634016  [2024-05-22 19:38:33] frigate.video                  ERROR   : voordeur: Unable to read frames from ffmpeg process.
frigate  | 2024-05-22 19:38:33.071788327  [2024-05-22 19:38:33] frigate.video                  ERROR   : voordeur: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://192.168.1.11:554/user=admin_password=_channel=1_stream=0.sdp':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

My docker-compose.yml:

```
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    # image: ghcr.io/blakeblackshear/frigate:0.12.1
    # network_mode: host
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      # - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #   target: /tmp/cache
      #   tmpfs:
      #     size: 1000000000
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
```
