### DISCUSSION TITLE
[Question]: latest snapshot for home assistant

### DISCUSSION THREAD

**Discussion by bozzio83** [blakeblackshear/frigate#11492] [Ask A Question] [answered]
### What is your question:

I'm trying to find a way to have frigate label the latest snapshot from frontdoor camera something like frontdoor_latest.jpg and have it update every time there is a new person at the frontdoor so i can attach an image to my home assistant notification.  Is this something that's possible?

frigate and doubletake are running on unraid. home assistant on vm from unraid box.

**Comment by NickM-27** [comment]
typically for notifications the event snapshot is used

**Reply by bozzio83** [reply]
I'm not sure what you mean. I'm trying to implement my doubletake setup.. i have it set when it sees my face to take a snapshot
```
service: camera.snapshot
metadata: {}
data:
  filename: www/latest_frontdoor.jpg
target:
  entity_id: camera.frontdoor_2
```
And then have it do this:
```
service: notify.mobile_app_troy_phone
data:
  message: troy spotted {{states('sensor.double_take_troy')}}
  title: front door
  data:
    image: mwww/latest_frontdoor.jpg
```
But it doesnt seem to do anything.  I tried other directory with the  
```
  allowlist_external_dirs:
  - /media
```
but i get a no permission error when i set to that directory.
