### DISCUSSION TITLE
[Camera Support]: No sound on REOLINK E1 Pro

### DISCUSSION THREAD

**Discussion by J0han3s** [blakeblackshear/frigate#11514] [Camera Support] [answered]
### Describe the problem you are having

When i play the live video stream in VLC all is well.
However, when i play the stream Home Assistant or Frigate, I do not get audio in the live view (web gui) or recordings.

Logs do not indicate an issue. tried to play it using Go2RTC plugin in home assistant, this is the below probe i get.

### Version

0.13.2-6476F8A go2rtc 1.8.4 streams info

### Frigate config file

```yaml
logger:
  logs:
    frigate.record.maintainer: debug


mqtt:
  host: 192.168.50.26
  user: username

detectors:
  coral1:
    type: edgetpu
    device: pci:0


go2rtc:
  streams:
    mjpeg_cam: "ffmpeg:rtsp://user:password@192.168.x.x:554/h264Preview_01_main#video=h264#hardware" 

cameras:

  mjpeg_cam:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.x.x:554/h264Preview_01_main
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac 

record:

  enabled: true
```

### Relevant log output

```shell
2024-05-24 22:38:24.219381095  [INFO] Preparing Frigate...
2024-05-24 22:38:24.219396063  [INFO] Starting Frigate...
2024-05-24 22:38:25.367318223  [2024-05-24 22:38:25] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-05-24 22:38:28.954279611  [2024-05-24 22:38:28] peewee_migrate.logs            INFO    : Starting migrations
2024-05-24 22:38:28.957512613  [2024-05-24 22:38:28] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-24 22:38:28.962736083  [2024-05-24 22:38:28] frigate.app                    INFO    : Recording process started: 461
2024-05-24 22:38:28.970010312  [2024-05-24 22:38:28] frigate.app                    INFO    : go2rtc process pid: 89
2024-05-24 22:38:28.993237724  [2024-05-24 22:38:28] frigate.app                    INFO    : Output process started: 472
2024-05-24 22:38:29.003232854  [2024-05-24 22:38:28] detector.coral1                INFO    : Starting detection process: 470
2024-05-24 22:38:29.003237309  [2024-05-24 22:38:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-05-24 22:38:29.010101071  [2024-05-24 22:38:29] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
` {
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.x.x/Preview_01_main/",
      "remote_addr": "192.168.x.x:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1562112078653562 1 IN IP4 192.168.x.x\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoALWQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=0, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=0, senders=1"
      ],
      "senders": [
        "0 PCMU/8000, bytes=0, receivers=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "probe",
      "remote_addr": "192.168.20.14, 172.30.32.1, 172.30.32.2:56778",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        "0 ANY, bytes=0, senders=1"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=0, receivers=1"
      ]
    }
  ]
}`
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink E1 Pro, Camera details build: 2401092478 Hardware version: IPC_566SD54MP firmware: v3.1.0.3149_2401092478

### Any other information that may be helpful

I see from ffprobe, that it is mpeg4/h264, not sure if that means i should change my config to mpeg4

**Comment by hawkeye217** [comment, marked as answer]
Your go2rtc line isn't copying or transcoding audio. Depending on what kind of audio your camera is sending, you may need something like:

`#audio=copy#audio=aac`

Check the docs [here](https://docs.frigate.video/guides/configuring_go2rtc).

**Comment by J0han3s** [comment]
perfect - thank you - got it working now

**Reply by celodnb** [reply]
> perfect - thank you - got it working now

Hi, would you mind posting the full config, showing how you got the audio to work? I cannot seem to get it working :-)

**Reply by Steini0809** [reply]
i am interested too

**Comment by 7aklhz** [comment]
I have this in my config but still no sound. However, I have sound on replay but not on live video. 

Here is a snippet of my config
```
go2rtc:
  streams:
    cam1_main:
      - rtsp://xxx:yyy@ccc
      - ffmpeg:cam4#audio=copy#audio=aac#stimeout=30000000
    cam1_sub:
      - rtsp://xxx:yyy@ccc
      - ffmpeg:cam4#audio=copy#audio=aac#stimeout=30000000
````
Any suggestions ?

**Reply by hawkeye217** [reply]
Try using the ffmpeg module to copy the video and provide AAC audio only:

```
go2rtc:
  streams:
    cam1_main:
      - ffmpeg:rtsp://xxx:yyy@ccc#video=copy#audio=aac
    cam1_sub:
      - ffmpeg:rtsp://xxx:yyy@ccc#video=copy#audio=aac
```

**Reply by 7aklhz** [reply]
Thank you for your response. I tried (with multiple variations audio=aac, audio=opus, audio=copy, etc.) but when using the ffmpeg module I cannot see / the video does not go trough / no video. Any other ideas ? 

I reverted back and this is my full config


```
mqtt:
  enabled: false
birdseye:
  enabled: true
  mode: continuous
  quality: 1
go2rtc:
  streams:
    cam1_main:
      - rtsp://abc:123@333101:554/h264Preview_01_main
      - ffmpeg:cam1#audio=copy#audio=aac#stimeout=30000000
    cam1_sub:
      - rtsp://abc:123@333101:554/h264Preview_01_sub
      - ffmpeg:cam1#audio=copy#audio=aac#stimeout=30000000
    cam2_main:
      - rtsp://abc:123@333102:554/h264Preview_01_main
      - ffmpeg:cam2#audio=copy#audio=aac#stimeout=30000000
    cam2_sub:
      - rtsp://abc:123@333102:554/h264Preview_01_sub
      - ffmpeg:cam2#audio=copy#audio=aac#stimeout=30000000
    cam3_main:
      - rtsp://abc:123@333103:554/h264Preview_01_main
      - ffmpeg:cam3#audio=copy#audio=aac#stimeout=30000000
    cam3_sub:
      - rtsp://abc:123@333103:554/h264Preview_01_sub
      - ffmpeg:cam3#audio=copy#audio=aac#stimeout=30000000
    cam4_main:
      - rtsp://abc:123@333104:554/h264Preview_01_main
      - ffmpeg:cam4#audio=copy#audio=aac#stimeout=30000000
    cam4_sub:
      - rtsp://abc:123@333104:554/h264Preview_01_sub
      - ffmpeg:cam4#audio=copy#audio=aac#stimeout=30000000
cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam1_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam1_main
    record:
      enabled: true
    detect:
      enabled: false
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam2_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam2_main
    record:
      enabled: true
    detect:
      enabled: false
  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam3_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam3_main
    record:
      enabled: true
    detect:
      enabled: false
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam4_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam4_main
    record:
      enabled: true
    detect:
      enabled: false
record:
  enabled: true
  retain:
    days: 4
    mode: all
version: 0.14
camera_groups:
  MyLayout:
    order: 1
    icon: LuShapes
    cameras:
      - cam1
      - cam2
      - cam3
      - cam4
      
   ```
