### DISCUSSION TITLE
[Support]: Bug with 0.14.0 and Motion masks

### DISCUSSION THREAD

**Discussion by rourke750** [blakeblackshear/frigate#11524] [General Support] [answered]
### Describe the problem you are having

Currently when trying to save motion masks I get an unable to save config.

### Version

0.14.0 beta

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.130
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx

model:
  path: plus://54e7a1de40b8e42627f1c4008b67e4be

birdseye:
  restream: true
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  layout:
    scaling_factor: 2.0

ffmpeg:
  hwaccel_args: preset-vaapi
#  hwaccel_args: preset-rpi-64-h264

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3

#ffmpeg:
#  hwaccel_args: -c:v h264_v4l2m2m
go2rtc:
  streams:
    basement_camera:
      #- rtsp://192.168.1.148:8554/basement
      - rtsp://xxx:xxx!!@192.168.50.107:554/cam/realmonitor?channel=1&subtype=0
    front_door:
      - rtsp://xxx:xxx!@192.168.50.100:554/cam/realmonitor?channel=1&subtype=0 #rtsp://192.168.1.148:8554/front
#      - rtsp://xxx:xxx!@192.168.50.100:554/cam/realmonitor?channel=1&subtype=0
#      - "ffmpeg:front_door#video=h264"
    garage:
      - rtsp://xxx:xxx@192.168.50.102:554/cam/realmonitor?channel=1&subtype=0
    backyard:
      - rtsp://x:x@192.168.50.104:554/cam/realmonitor?channel=1&subtype=0
    living_room_camera:
      - rtsp://x:x!!@192.168.50.99:554/cam/realmonitor?channel=1&subtype=0

cameras:
  # Required: name of the camera
  basement_camera:
    enabled: true
    onvif:
      host: 192.168.50.107
      port: 80
      user: xxx
      password: xxx!!
#      autotracking:
#        enabled: False
#        calibrate_on_startup: True
#        zooming: disabled
#        track:
#          - person
#        return_preset: home
#        required_zones: []
    # Required: ffmpeg settings for the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      # Required: A list of input streams for the camera. See documentation for more information.
#      input_args:
#        - -avoid_negative_ts
#        - make_zero
#        - -fflags
#        - nobuffer
#        - -flags
#        - low_delay
#        - -strict
#        - experimental
#        - -fflags
#        - +genpts+discardcorrupt
#        - -use_wallclock_as_timestamps
#        - "1"
      inputs:
          # Required: the path to the stream
          # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        #- path: rtsp://127.0.0.1:8554/basement_camera
        - path: rtsp://xxx:xxx!!@192.168.50.107:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-generic
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/basement_camera
          roles:
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 640
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60

    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: true
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
          - cat
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
          mode: active_objects
          # Optional: Per object retention days

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
    motion:
  front_door:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://xxx:xxx!@192.168.50.100:554/cam/realmonitor?channel=1&subtype=1       #rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record

    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      #width: 1920
      width: 640
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      #height: 1080
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60

    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: true
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
          - car
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
          # Optional: Per object retention days

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7

    motion:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.50.102:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 704
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60
    record:
      # Optional: Enable recording (default: global setting)
      enabled: true
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
          - car
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        #tional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
    objects:
      track:
        - person
        - car
        - cat

    motion:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.50.104:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 704
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60
    record:
      # Optional: Enable recording (default: global setting)
      enabled: true
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
    objects:
      track:
        - person
        - cat

    motion:

  living_room_camera:
    enabled: true
    onvif:
      host: 192.168.50.99
      port: 80
      user: xxx
      password: xxx!!
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      # Required: A list of input streams for the camera. See documentation for more information.
#      input_args:
#        - -avoid_negative_ts
#        - make_zero
#        - -fflags
#        - nobuffer
#        - -flags
#        - low_delay
#        - -strict
#        - experimental
#        - -fflags
#        - +genpts+discardcorrupt
#        - -use_wallclock_as_timestamps
#        - "1"
      inputs:
          # Required: the path to the stream
          # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        #- path: rtsp://basementcamera:fdsbdgkhjfdbgkhj54879564!@192.168.20.40:8554/unicast
        #- path: rtsp://127.0.0.1:8554/basement_camera
        - path: rtsp://xxx:xxx!!@192.168.50.99:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-generic
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/living_room_camera
          roles:
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 640
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60

    # Optional: 24/7 recording configuration
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        retain:
          default: 10
          mode: active_objects

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
    motion:

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

### Relevant log output

```shell
Error updating config: argument of type 'NoneType' is not iterable
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

I am browsing on port 5000 as an anonymous user.  It might be related to authentication?
