### DISCUSSION TITLE
[Config Support]: New UI Review - Alerts vs Detections

### DISCUSSION THREAD

**Discussion by DrSpaldo** [blakeblackshear/frigate#11523] [Config Support]
### Describe the problem you are having

I have a busy street and I only want 'alerts' if a person walks by my front path. If they walk past the road, then it should only be a detection. In my case, these are cameras street1 & street2. 

I have created zones for these named street1_road, street1_path, street2_road & street2_path. So I want alerts for street1_path & street2_path and detections for street1_road &  street2_road. 

Currently, it looks like some are still sneaking in as 'alerts' even on the road. Any ideas if I have done something incorrectly with my config?

### Version

0.14.0-b97e274

### Frigate config file

```yaml
street1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/street1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        pre_capture: 10
        post_capture: 15
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 14
    detect:
      enabled: true
      max_disappeared: 100
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      quality: 100
      crop: false
      retain:
        default: 7
        objects:
          person: 60
    ui:
      order: 3
    birdseye:
      order: 5
      mode: objects
    objects:
      track:
        - person
      filters:
        person:
          min_area: 350
          max_area: 16000
    motion:
      mask:
        - 704,23,704,0,569,0,571,21
    zones:
      street1_road:
        coordinates: 0.002,0.279,0.006,0.864,0.865,0.097,0.601,0.011,0.424,0.02
        objects: person
      street1_path:
        coordinates: 0.009,0.871,0.869,0.11,0.995,0.175,0.962,0.595,0.851,0.989,0.008,0.988
        objects: person
    review:
      detections:
        required_zones: street1_road
      alerts:
        required_zones: street1_path
  street2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street2
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/street2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        pre_capture: 10
        post_capture: 15
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 14
    detect:
      enabled: true
      max_disappeared: 100
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      quality: 100
      crop: false
      retain:
        default: 7
        objects:
          person: 60
    ui:
      order: 4
    objects:
      track:
        - person
      filters:
        person:
          min_area: 350
          max_area: 16000
    motion:
      mask:
        - 203,0,204,26,103,26,100,0
    zones:
      street2_road:
        coordinates: 0.172,0.087,0.99,0.74,0.991,0.145,0.702,0.005,0.317,0.008
        objects: person
      street2_path:
        coordinates: 0.006,0.188,0.165,0.095,0.988,0.776,0.993,0.988,0.183,0.993,0.057,0.601
        objects: person
    review:
      detections:
        required_zones: street2_road
      alerts:
        required_zones: street2_path
```

### Relevant log output

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

**Comment by hawkeye217** [comment]
The bottom center of the bounding box is what determines if the object is in a zone or not. If your object entered the zone at any time that it was tracked, it will be marked as having been in that zone. See the docs: https://deploy-preview-11419--frigate-docs.netlify.app/configuration/zones

Also, `person` and `car` are alerts by default, so you should list what objects you do want as alerts for your zone. See the docs: https://deploy-preview-11419--frigate-docs.netlify.app/configuration/review

**Reply by DrSpaldo** [reply]
They never entered the incorrect zone. Where is the option to exclude?

**Reply by DrSpaldo** [reply]
I have this for review / zone:

```
    review:
      detections:
        required_zones: street2_road
      alerts:
        required_zones: street2_path
```

Shouldn't that restrict detections to road & alerts to path?

**Reply by hawkeye217** [reply]
Your config looks fine. You'll want to watch the debug view to see what happens with the objects that "sneak in" as alerts.

**Reply by DrSpaldo** [reply]
How do I totally turn off person alerts for one camera and only get detections for persons on that camera. I have added this to the config but it isn't working, the people keep going into alerts and not detections:

```  street3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street3
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        pre_capture: 10
        post_capture: 15
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 14
    detect:
      enabled: true
      max_disappeared: 100
      width: 2560
      height: 1440
      fps: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      quality: 100
      crop: false
      retain:
        default: 7
    objects:
      track:
        - person
        - car
    ui:
      order: 12
    birdseye:
      enabled: false
    audio:
      enabled: false
    review:
      detections:
        labels:
          - person
          - car
```

    **review:
      detections:
        labels:
          - person
          - car**

**Reply by hawkeye217** [reply]
To turn off `person` from any alerts, just exclude it from the list in review:

```
review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - speech
```
