### DISCUSSION TITLE
[Support]: Onvif PTZ works than stops working

### DISCUSSION THREAD

**Discussion by rourke750** [blakeblackshear/frigate#11538] [General Support] [answered]
### Describe the problem you are having

Currently with a few of my Amcrest cameras that support ptz they always work as soon as I restart frigate.  Than after a little bit of time the ptz function stops working.

### Version

0.13.0+

### Frigate config file

```yaml
basement_camera:
    enabled: true
    onvif:
      host: 192.168.50.107
      port: 80
      user: ccc
      password: xxx
```

### Relevant log output

```shell
Onvif is not setup for basement_camera
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

amcrest IP4M-1041W

### Any other information that may be helpful

I think the issue is related to time drift.  If time drifts on the camera or there are lag spikes I think the onvif connection fails.  If what ever start up logic Frigate uses for initially connecting, just reinitialize that part on failure I think that would fix my problems.
