### DISCUSSION TITLE
Getting 404 Page not Found [Support]:

### DISCUSSION THREAD

**Discussion by Elder-HVAC-Man** [blakeblackshear/frigate#11535] [General Support] [answered]
### Describe the problem you are having

Clicking on the Frigate icon on the sidebar of HA, it takes me to a page that says 404 page not found.
![Figate 404](https://github.com/blakeblackshear/frigate/assets/65379405/c4f954fd-6f6a-4def-8442-389874ceb5e7)

### Version

System 0.14.0-b97e274

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.170
  user: secret
  password: secret

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: false
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 15

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
      car: 8

go2rtc:
  streams:
    garage:
      - rtsp://admin:secret@192.168.1.199:554/cam/realmonitor?channel=1&subtype=0
    front:
      - rtsp://admin:secret@192.168.1.35:554/cam/realmonitor?channel=1&subtype=0
    entry:
      - rtsp://admin:secret@192.168.1.76:554/cam/realmonitor?channel=1&subtype=0
    yard:
      - rtsp://admin:secret@192.168.1.9:554/cam/realmonitor?channel=1&subtype=0
    front_door:
      - rtsp://admin:secret@192.168.1.69:554/cam/realmonitor?channel=1&subtype=0
    patio:
      - rtsp://admin:secret@192.168.1.93:554/cam/realmonitor?channel=1&subtype=0
    backyard:
      - rtsp://admin:secret@192.168.1.134:554/cam/realmonitor?channel=1&subtype=0
    gate:
      - rtsp://192.168.1.170:8554/gate

cameras:
  front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:secret@192.168.1.35:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:secret@192.168.1.35:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - car
        - dog
        - cat
        - bird
        - person
      filters:
        dog:
          threshold: 0.6
        cat:
          threshold: 0.6
        bird:
          threshold: 0.6
        person:
          threshold: 0.7
    motion:
      mask:
        - 548,41,667,46,675,23,547,21
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - car_zone
        - people_zone
    zones:
      car_zone:
        coordinates: 467,58,402,114,343,152,198,161,230,111,290,91,364,58
        objects:
          - car
      people_zone:
        coordinates: 
          0,284,0,480,328,480,352,350,379,206,392,157,527,161,639,168,679,160,662,77,487,50,336,49,200,59
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 2
####################################################################################
  entry: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:secret@192.168.1.76:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:secret@192.168.1.76:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bird
      filters:
        dog:
          threshold: 0.6
        cat:
          threshold: 0.6
        person:
          threshold: 0.7
        bird:
          mask: 
            0,447,42,459,86,459,116,424,140,378,144,340,152,288,151,238,134,184,100,186,59,176,0,173
    motion:
      mask:
        - 581,41,682,48,682,0,580,0
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - people_zone2
    zones:
      people_zone2:
        coordinates: 
          229,164,150,206,172,278,166,336,160,398,24,480,205,480,364,480,375,420,451,354,507,370,553,296,595,154,618,33,538,0,464,0,398,0,312,0,230,54
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 3
######################################################################################
  yard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:secret@192.168.1.9:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:secret@192.168.1.9:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bird
      filters:
        person:
          threshold: 0.75
        cat:
          threshold: 0.6
        dog:
          threshold: 0.6
    motion:
      mask:
        - 551,41,668,40,671,21,546,21
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - people_zone1
    zones:
      people_zone1:
        coordinates: 374,448,679,444,679,281,514,262,418,74,170,82,133,304,202,335,302,341
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 1
##################################################################################
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:secret@192.168.1.93:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:secret@192.168.1.93:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        dog:
          threshold: 0.6
        cat:
          threshold: 0.6
    motion:
      contour_area: 10
      threshold: 30
      mask:
        - 235,356,300,364,289,301,224,275
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - patio_zone
    zones:
      patio_zone:
        coordinates: 252,480,456,480,704,438,704,319,629,215,470,142,327,95,169,139,46,187
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 5
#####################################################################################
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:secret@192.168.1.134:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:secret@192.168.1.134:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          threshold: 0.80
        dog:
          min_score: 0.4
          threshold: 0.6
        cat:
          min_score: 0.4
          threshold: 0.6
        bird:
          min_score: 0.4
          threshold: 0.6
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - backyard_zone
    zones:
      backyard_zone:
        coordinates: 
          58,185,0,198,0,291,51,358,28,390,126,480,293,480,704,459,704,321,704,165,546,129,338,94,158,89
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 8
########################################################################################
  front_door:
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:secret@192.168.1.69:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: 
            rtsp://admin:secret@192.168.1.69:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    detect:
      enabled: true
      width: 720 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        dog:
          threshold: 0.6
          mask:
            - 214,326,256,346,300,359,352,362,400,362,430,330,420,286,381,266,340,250,289,242,242,242,211,281
        cat:
          threshold: 0.6
          mask:
            - 214,326,256,346,300,359,352,362,400,362,430,330,420,286,381,266,340,250,289,242,242,242,211,281
        bird:
          threshold: 0.6
          mask:
            - 214,326,256,346,300,359,352,362,400,362,430,330,420,286,381,266,340,250,289,242,242,242,211,281
        person:
          threshold: 0.80
          mask:
            - 263,477,311,479,341,461,328,373,262,390
    motion:
      mask:
        - 263,477,311,479,341,461,328,373,262,390
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - door_zone
    zones:
      door_zone:
        coordinates: 93,576,354,576,441,462,446,397,455,331,406,299,342,335,210,348,37,382,58,460
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 6
####################################################################################
  gate:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.170:8554/gate
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1296 # <---- update for your camera's resolution
      height: 1728 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          threshold: 0.80
        bird: {}
    motion:
      mask:
        - 0,737,501,769,924,775,903,218,683,187,304,196,0,245
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - gate_zone
    zones:
      gate_zone:
        coordinates: 
          580,1728,598,1502,627,1210,538,1212,541,1035,696,1031,703,1212,871,1203,886,827,0,809,0,1728
        objects:
          - person
          - dog
          - cat
          - bird
    ui:
      order: 6
###########################################################################
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:secret@192.168.1.199:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.80
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 0
        mode: motion
    snapshots:
      required_zones:
        - garage_zone
    zones:
      garage_zone:
        coordinates: 
          56,699,52,1026,306,1055,981,1034,1289,1032,1870,1034,1889,468,1841,151,1245,120,540,137,62,205
        objects:
          - person
    ui:
      order: 9
```

### Relevant log output

```shell
2024-05-26 12:58:59.425509948  [INFO] Preparing Frigate...
2024-05-26 12:58:59.661492284  [INFO] Starting Frigate...
2024-05-26 12:59:10.011251845  [2024-05-26 07:59:10] frigate.app                    INFO    : Starting Frigate (0.14.0-b97e274)
2024-05-26 12:59:10.011730342  [2024-05-26 07:59:10] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-05-26 12:59:10.018988228  [2024-05-26 07:59:10] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-05-26 12:59:10.019809694  [2024-05-26 07:59:10] frigate.util.config            INFO    : frigate config does not need migration...
2024-05-26 12:59:10.260908960  [2024-05-26 07:59:10] peewee_migrate.logs            INFO    : Starting migrations
2024-05-26 12:59:10.262384788  [2024-05-26 07:59:10] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-26 12:59:10.280116060  [2024-05-26 07:59:10] frigate.app                    INFO    : Recording process started: 323
2024-05-26 12:59:10.283320627  [2024-05-26 07:59:10] frigate.app                    INFO    : Recording process started: 324
2024-05-26 12:59:10.289120195  [2024-05-26 07:59:10] frigate.app                    INFO    : go2rtc process pid: 94
2024-05-26 12:59:10.356534026  [2024-05-26 07:59:10] frigate.app                    INFO    : Output process started: 353
2024-05-26 12:59:10.367797094  [2024-05-26 07:59:10] detector.coral                 INFO    : Starting detection process: 352
2024-05-26 12:59:10.395246215  [2024-05-26 07:59:10] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-05-26 12:59:13.239121558  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for front: 420
2024-05-26 12:59:13.239127488  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for entry: 421
2024-05-26 12:59:13.239134520  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for yard: 428
2024-05-26 12:59:13.239138559  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for patio: 437
2024-05-26 12:59:13.239159769  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for backyard: 445
2024-05-26 12:59:13.239163829  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for front_door: 455
2024-05-26 12:59:13.239766458  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for gate: 461
2024-05-26 12:59:13.240267209  [2024-05-26 07:59:11] frigate.app                    INFO    : Camera processor started for garage: 469
2024-05-26 12:59:13.240583762  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for front: 470
2024-05-26 12:59:13.240964730  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for entry: 480
2024-05-26 12:59:13.241384704  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for yard: 483
2024-05-26 12:59:13.241771791  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for patio: 497
2024-05-26 12:59:13.242127171  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for backyard: 499
2024-05-26 12:59:13.242544800  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for front_door: 507
2024-05-26 12:59:13.242937961  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for gate: 508
2024-05-26 12:59:13.243285350  [2024-05-26 07:59:11] frigate.app                    INFO    : Capture process started for garage: 513
2024-05-26 12:59:13.256648476  [2024-05-26 07:59:13] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
Not applicable
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest

### Any other information that may be helpful

Clicking on the icons brings me to the appropriate pages.  Just seems odd to get the 404 error initially.  I have uninstalled and reinstalled both Frigate and the add on.  Same outcome after reinstall.
