### DISCUSSION TITLE
[Support]: Frigate crashing/broken after upgrade to 0.14.0-beta1

### DISCUSSION THREAD

**Discussion by a9e78rauijasdf** [blakeblackshear/frigate#11533] [General Support]
### Describe the problem you are having

After upgrading Frigate addon in HA to 0.14.0-beta1 from 0.13.2, Frigate crashes and will not restart. I am running on a Pi4 with a coral tpu via usb. it has been running for long time with no stability issues.
I am seeing quite a few errors suddenly, but i have tried to clean up erverything and delete everything frigate-related to start all over and build a new config.

### Version

0.14.0-beta1

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect
```

### Relevant log output

```shell
N/A for now
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
cannot access
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relevant

### Any other information that may be helpful

Frigate configuration editor claims that it is unable to save the configuration. I have not touched any files manually. I have looked at them and they dont appear weird to me.
As I have reverted to 0.13.2 now, I am unable to provide further details. I badly needed cameras to be online and working with frigate, so I am creating this issue for others to report into, if they are also experiencing issues when upgrading to the beta. I tried all sorts of troubleshooting - rebooting host, reinstalling frigate, cleaning config (as per docs), I could not identify any possible ways to debug this :(
