### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by bozzio83** [blakeblackshear/frigate#11547] [Config Support] [answered]
### Describe the problem you are having

I have an option for ups, amazon, fedex on my frigate+ setup.. But if I try and add amazon to objects to track on my config frigate does not boot.

Then frigate does not boot. Any help would be greatly appreciated.

Thank you

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.29
  user: mqtt-user
  password: *****************
  client_id: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous

model:
  path: plus://***************************

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  height: 1440
  retain:
    default: 5

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    frontdoor:
    - rtsp://***@******@192.168.x.x:xxxx/**********
    driveway:
    - rtsp://***@******@192.168.x.x:xxxx/**********
    garage:
    - rtsp://***@******@192.168.x.x:xxxx/**********
    package:
    - rtsp://***@******@192.168.x.x:xxxx/**********

cameras:
  frontdoor:
    ffmpeg:
      inputs:
        # High res
      - path: rtsp://127.0.0.1:8554/frontdoor
        roles:
        - record
        - detect
        - rtmp
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    detect:
      width: 1600
      height: 1200
      fps: 7
    objects:
      track:
      - person
      - dog
      - package
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
    motion:
      mask:
      - 607,644,847,636,1054,671,1146,690,1186,480,1069,478,796,478,562,492,556,620

  garage:
    ffmpeg:
      inputs:
        # High res
      - path: rtsp://127.0.0.1:8554/garage
        roles:
        - record
        - detect
        - rtmp
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    detect:
      width: 2688
      height: 1512
      fps: 7
    objects:
      track:
      - person
      - dog
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
    birdseye:
      enabled: true
      width: 2688
      height: 1512

  driveway:
    ffmpeg:
      inputs:
        # High res
      - path: rtsp://127.0.0.1:8554/driveway
        roles:
        - record
        - detect
        - rtmp
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    detect:
      width: 2688
      height: 1512
      fps: 7
    objects:
      track:
      - person
      - dog
      - package
      - amazon
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    record:
      enabled: true
      retain:
        days: 7
      events:
        required_zones:
        - yard
        retain:
          default: 14
          mode: active_objects
    birdseye:
      enabled: true
      width: 2688
      height: 1512
    snapshots:
      required_zones:
      - yard
    zones:
      road:
        coordinates: 1231,0,2405,0,2688,0,2688,480,2018,220,1322,251,710,273,0,404,0,0
      yard:
        coordinates: 0,603,0,1512,2688,1512,2688,551,2442,463,2197,415,1910,415,1424,458
        objects:
        - person
        - dog
  package:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/package
        roles:
        - rtmp
        - record
        - detect
    detect:
      width: 1600
      height: 1200
      fps: 5
    objects:
      track:
      - package
      - motion
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 7
          mode: active_objects
    birdseye:
      enabled: false
```

Config as posted works.. but i try and add under driveway camera..
```zones:
      road:
        coordinates: 1231,0,2405,0,2688,0,2688,480,2018,220,1322,251,710,273,0,404,0,0
        objects:
        - amazon
        - package
```
     

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB
