### DISCUSSION TITLE
[Support]: Frigate crashing!! No EdgeTPU was detected

### DISCUSSION THREAD

**Discussion by aronmgv** [blakeblackshear/frigate#11544] [General Support] [answered]
### Describe the problem you are having

Suddenly my docker frigate instance started crashing on: No EdgeTPU was detected

I configured it months ago to utilize Dual Edge TPU. All was working flawlessly until recently

```
root@edoras:[/docker/frigate]: lspci -nn | grep 089a
03:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
04:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
root@edoras:[/docker/frigate]: lsmod | grep apex
apex                   28672  5
gasket                126976  6 apex
root@edoras:[/docker/frigate]: ls /dev/apex*
/dev/apex_0  /dev/apex_1
root@edoras:[/docker/frigate]:
```

Docker-Compose:
```yml
version: "3.9"

services:
  frigate:
    container_name: home.frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: always
    privileged: true
    shm_size: "512mb"
    ports:
      - 5000:5000     # Port used by the Web UI
      - 8554:8554     # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - $PWD/frigate/config.yml:/config/config.yml
      - /lvm/hdd/data/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"

  mosquitto:
    container_name: home.mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - $PWD/mosquitto/config:/mosquitto/config
      - $PWD/mosquitto/data:/mosquitto/data
      - $PWD/mosquitto/log:/mosquitto/log

networks:
  default:
    name: home.frigate
```

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
logger:
   default: info
   logs:
     frigate.comms.mqtt: debug

mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  user: mqtt
  password: xxx

detect:
  enabled: true

objects:
  track:
    - person
    - car
    - bird
    - bicycle
    - motorcycle
    - bus
    - cat
    - dog
    - train

#detectors:
#    cpu:
#      type: cpu
#      num_threads: 1

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  #hwaccel_args:
  #  - -hwaccel
  #  - vaapi
  #  - -hwaccel_device
  #  - /dev/dri/renderD128

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

go2rtc:
  streams:
    balkon:
      - rtsp://admin:xxx@192.168.255.91:554/live/main
      - "ffmpeg:balkon#video=h264#audio=aac"
    #chodba:
    #  - rtsp://192.168.255.92:554/user=admin_password=xxx_channel=1_stream=0.sdp
    #  - "ffmpeg:chodba#video=h265#audio=aac"
    byt:
      - rtsp://admin:xxx@192.168.255.93:554/h265Preview_01_main
      - "ffmpeg:byt#video=h265#audio=aac"

cameras:
  balkon:
    birdseye:
      order: 1
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/balkon?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 10
          mode: motion
          objects:
            person: 21
  #chodba:
  #  birdseye:
  #    order: 2
  #  detect:
  #    enabled: true
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/chodba?video&audio
  #        input_args: preset-rtsp-restream
  #        roles:
  #          - record
  #          - detect
  #  record:
  #    enabled: true
  #    retain:
  #      days: 3
  #      mode: all
  byt:
    birdseye:
      order: 3
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/byt?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
```

### Relevant log output

```shell
home.frigate    | s6-rc: info: service s6rc-fdholder: starting
home.frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
home.frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
home.frigate    | s6-rc: info: service fix-attrs: starting
home.frigate    | s6-rc: info: service s6rc-fdholder successfully started
home.frigate    | s6-rc: info: service fix-attrs successfully started
home.frigate    | s6-rc: info: service legacy-cont-init: starting
home.frigate    | s6-rc: info: service legacy-cont-init successfully started
home.frigate    | s6-rc: info: service log-prepare: starting
home.frigate    | s6-rc: info: service log-prepare successfully started
home.frigate    | s6-rc: info: service nginx-log: starting
home.frigate    | s6-rc: info: service go2rtc-log: starting
home.frigate    | s6-rc: info: service frigate-log: starting
home.frigate    | s6-rc: info: service nginx-log successfully started
home.frigate    | s6-rc: info: service frigate-log successfully started
home.frigate    | s6-rc: info: service go2rtc-log successfully started
home.frigate    | s6-rc: info: service go2rtc: starting
home.frigate    | s6-rc: info: service go2rtc successfully started
home.frigate    | s6-rc: info: service go2rtc-healthcheck: starting
home.frigate    | s6-rc: info: service frigate: starting
home.frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
home.frigate    | s6-rc: info: service frigate successfully started
home.frigate    | s6-rc: info: service nginx: starting
home.frigate    | s6-rc: info: service nginx successfully started
home.frigate    | s6-rc: info: service legacy-services: starting
home.frigate    | 2024-05-27 01:26:59.296595618  [INFO] Preparing Frigate...
home.frigate    | 2024-05-27 01:26:59.297270640  [INFO] Starting NGINX...
home.frigate    | 2024-05-27 01:26:59.299416181  [INFO] Preparing new go2rtc config...
home.frigate    | s6-rc: info: service legacy-services successfully started
home.frigate    | 2024-05-27 01:26:59.304519772  [INFO] Starting Frigate...
home.frigate    | 2024-05-27 01:26:59.482762285  [INFO] Starting go2rtc...
home.frigate    | 2024-05-27 01:26:59.555392857  01:26:59.555 INF go2rtc version 1.8.4 linux/amd64
home.frigate    | 2024-05-27 01:26:59.555675866  01:26:59.555 INF [rtsp] listen addr=:8554
home.frigate    | 2024-05-27 01:26:59.555810688  01:26:59.555 INF [webrtc] listen addr=:8555
home.frigate    | 2024-05-27 01:26:59.556057730  01:26:59.555 INF [api] listen addr=:1984
home.frigate    | 2024-05-27 01:27:00.081540129  [2024-05-27 01:27:00] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
home.frigate    | 2024-05-27 01:27:02.174582033  2024/05/27 01:27:02 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.255.12, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.255.12:5000"
home.frigate    | 2024-05-27 01:27:04.295578408  2024/05/27 01:27:04 [error] 147#147: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
home.frigate    | 2024-05-27 01:27:04.782332564  [2024-05-27 01:27:04] peewee_migrate.logs            INFO    : Starting migrations
home.frigate    | 2024-05-27 01:27:04.789978990  [2024-05-27 01:27:04] peewee_migrate.logs            INFO    : There is nothing to migrate
home.frigate    | 2024-05-27 01:27:04.790053149  [2024-05-27 01:27:04] frigate.app                    INFO    : Recording process started: 775
home.frigate    | 2024-05-27 01:27:04.791567470  [2024-05-27 01:27:04] frigate.app                    INFO    : go2rtc process pid: 89
home.frigate    | 2024-05-27 01:27:04.797551318  [2024-05-27 01:27:04] frigate.comms.mqtt             DEBUG   : MQTT connected
home.frigate    | 2024-05-27 01:27:04.809561805  [2024-05-27 01:27:04] detector.coral1                INFO    : Starting detection process: 785
home.frigate    | 2024-05-27 01:27:07.173244128  2024/05/27 01:27:07 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.255.12, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.255.12:5000"
home.frigate    | 2024-05-27 01:27:09.297040583  [INFO] Starting go2rtc healthcheck service...
home.frigate    | 2024-05-27 01:27:09.344212962  2024/05/27 01:27:09 [error] 148#148: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
home.frigate    | 2024-05-27 01:27:12.173122717  2024/05/27 01:27:12 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.255.12, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.255.12:5000"
home.frigate    | 2024-05-27 01:27:14.444659113  2024/05/27 01:27:14 [error] 146#146: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
home.frigate    | 2024-05-27 01:27:17.181757929  2024/05/27 01:27:17 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.255.12, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.255.12:5000"
home.frigate    | 2024-05-27 01:27:17.704395610  [2024-05-27 01:27:04] detector.coral2                INFO    : Starting detection process: 788
home.frigate    | 2024-05-27 01:27:17.704511988  [2024-05-27 01:27:04] frigate.app                    INFO    : Output process started: 795
home.frigate    | 2024-05-27 01:27:17.704628966  [2024-05-27 01:27:04] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
home.frigate    | 2024-05-27 01:27:17.704694108  [2024-05-27 01:27:04] frigate.app                    INFO    : Camera processor started for balkon: 803
home.frigate    | 2024-05-27 01:27:17.704711861  Process detector:coral2:
home.frigate    | 2024-05-27 01:27:17.704796159  [2024-05-27 01:27:04] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
home.frigate    | 2024-05-27 01:27:17.704873283  [2024-05-27 01:27:04] frigate.app                    INFO    : Camera processor started for byt: 804
home.frigate    | 2024-05-27 01:27:17.704954335  [2024-05-27 01:27:17] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
home.frigate    | 2024-05-27 01:27:17.705022813  [2024-05-27 01:27:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
home.frigate    | 2024-05-27 01:27:17.705101009  [2024-05-27 01:27:04] frigate.app                    INFO    : Capture process started for balkon: 805
home.frigate    | 2024-05-27 01:27:17.705170399  [2024-05-27 01:27:04] frigate.app                    INFO    : Capture process started for byt: 809
home.frigate    | 2024-05-27 01:27:17.705613568  Traceback (most recent call last):
home.frigate    | 2024-05-27 01:27:17.705626292    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
home.frigate    | 2024-05-27 01:27:17.705626853      delegate = Delegate(library, options)
home.frigate    | 2024-05-27 01:27:17.705627404    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
home.frigate    | 2024-05-27 01:27:17.705628476      raise ValueError(capture.message)
home.frigate    | 2024-05-27 01:27:17.705633295  ValueError
home.frigate    | 2024-05-27 01:27:17.705642402
home.frigate    | 2024-05-27 01:27:17.705643013  During handling of the above exception, another exception occurred:
home.frigate    | 2024-05-27 01:27:17.705643384
home.frigate    | 2024-05-27 01:27:17.705643814  Traceback (most recent call last):
home.frigate    | 2024-05-27 01:27:17.705660936    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
home.frigate    | 2024-05-27 01:27:17.705661447      self.run()
home.frigate    | 2024-05-27 01:27:17.705661948    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
home.frigate    | 2024-05-27 01:27:17.705662409      self._target(*self._args, **self._kwargs)
home.frigate    | 2024-05-27 01:27:17.705667008    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
home.frigate    | 2024-05-27 01:27:17.705667519      object_detector = LocalObjectDetector(detector_config=detector_config)
home.frigate    | 2024-05-27 01:27:17.705668020    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
home.frigate    | 2024-05-27 01:27:17.705668480      self.detect_api = create_detector(detector_config)
home.frigate    | 2024-05-27 01:27:17.705668991    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
home.frigate    | 2024-05-27 01:27:17.705669923      return api(detector_config)
home.frigate    | 2024-05-27 01:27:17.705674462    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 41, in __init__
home.frigate    | 2024-05-27 01:27:17.705674953      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
home.frigate    | 2024-05-27 01:27:17.705675484    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
home.frigate    | 2024-05-27 01:27:17.705675964      raise ValueError('Failed to load delegate from {}\n{}'.format(
home.frigate    | 2024-05-27 01:27:17.705685112  ValueError: Failed to load delegate from libedgetpu.so.1.0
home.frigate    | 2024-05-27 01:27:17.705685492
home.frigate    | 2024-05-27 01:27:19.520806689  2024/05/27 01:27:19 [error] 172#172: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
home.frigate    | 2024-05-27 01:27:40.880981513  [2024-05-27 01:27:40] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
home.frigate    | s6-rc: info: service legacy-services: stopping
home.frigate    | s6-rc: info: service legacy-services successfully stopped
home.frigate    | s6-rc: info: service nginx: stopping
home.frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
home.frigate    | 2024-05-27 01:27:40.893236401  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
home.frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
home.frigate    | 2024-05-27 01:27:40.979124383  [INFO] Service NGINX exited with code 0 (by signal 0)
home.frigate    | s6-rc: info: service nginx successfully stopped
home.frigate    | s6-rc: info: service nginx-log: stopping
home.frigate    | s6-rc: info: service frigate: stopping
home.frigate    | 2024-05-27 01:27:40.981449794  [2024-05-27 01:27:40] frigate.app                    INFO    : Stopping...
home.frigate    | s6-rc: info: service nginx-log successfully stopped
home.frigate    | 2024-05-27 01:27:40.981982100  [2024-05-27 01:27:40] detector.coral1                INFO    : Signal to exit detection process...
home.frigate    | 2024-05-27 01:27:40.981983923  [2024-05-27 01:27:40] root                           INFO    : Waiting for detection process to exit gracefully...
home.frigate    | 2024-05-27 01:27:40.982003089  [2024-05-27 01:27:40] frigate.ptz.autotrack          INFO    : Exiting autotracker...
home.frigate    | 2024-05-27 01:27:40.982121210  [2024-05-27 01:27:40] frigate.storage                INFO    : Exiting storage maintainer...
home.frigate    | 2024-05-27 01:27:40.982164240  [2024-05-27 01:27:40] frigate.events.cleanup         INFO    : Exiting event cleanup...
home.frigate    | 2024-05-27 01:27:40.982255782  [2024-05-27 01:27:40] frigate.watchdog               INFO    : Exiting watchdog...
home.frigate    | 2024-05-27 01:27:40.982292661  [2024-05-27 01:27:40] frigate.stats                  INFO    : Exiting stats emitter...
home.frigate    | 2024-05-27 01:27:40.982386496  [2024-05-27 01:27:40] frigate.record.cleanup         INFO    : Exiting recording cleanup...
home.frigate    | 2024-05-27 01:27:40.989144480  [2024-05-27 01:27:40] frigate.events.maintainer      INFO    : Exiting event processor...
home.frigate    | 2024-05-27 01:27:40.992630813  [2024-05-27 01:27:40] detector.coral1                INFO    : Exited detection process...
home.frigate    | 2024-05-27 01:27:40.995358296  [2024-05-27 01:27:40] frigate.object_processing      INFO    : Exiting object processor...
home.frigate    | 2024-05-27 01:27:41.001895106  [2024-05-27 01:27:41] root                           INFO    : Detection process has exited...
home.frigate    | 2024-05-27 01:27:41.336695557  [2024-05-27 01:27:41] frigate.comms.ws               INFO    : Exiting websocket client...
home.frigate    | 2024-05-27 01:27:42.077507627  [2024-05-27 01:27:42] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
home.frigate    | 2024-05-27 01:27:42.080309419  [2024-05-27 01:27:42] watchdog.balkon                INFO    : Terminating the existing ffmpeg process...
home.frigate    | 2024-05-27 01:27:42.080384570  [2024-05-27 01:27:42] watchdog.byt                   INFO    : Terminating the existing ffmpeg process...
home.frigate    | 2024-05-27 01:27:42.080581288  [2024-05-27 01:27:42] watchdog.balkon                INFO    : Waiting for ffmpeg to exit gracefully...
home.frigate    | 2024-05-27 01:27:42.080640829  [2024-05-27 01:27:42] watchdog.byt                   INFO    : Waiting for ffmpeg to exit gracefully...
home.frigate    | 2024-05-27 01:27:46.347451892  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 10 leaked shared_memory objects to clean up at shutdown
home.frigate    | 2024-05-27 01:27:46.347454437    warnings.warn('resource_tracker: There appear to be %d '
home.frigate    | 2024-05-27 01:27:46.350854700  [INFO] Service Frigate exited with code 0 (by signal 0)
home.frigate    | s6-rc: info: service frigate successfully stopped
home.frigate    | s6-rc: info: service go2rtc: stopping
home.frigate    | s6-rc: info: service frigate-log: stopping
home.frigate    | 2024-05-27 01:27:46.352426882  exit with signal: terminated
home.frigate    | s6-rc: info: service frigate-log successfully stopped
home.frigate    | 2024-05-27 01:27:46.356374848  [INFO] The go2rtc service exited with code 0 (by signal 0)
home.frigate    | s6-rc: info: service go2rtc successfully stopped
home.frigate    | s6-rc: info: service go2rtc-log: stopping
home.frigate    | s6-rc: info: service go2rtc-log successfully stopped
home.frigate    | s6-rc: info: service log-prepare: stopping
home.frigate    | s6-rc: info: service s6rc-fdholder: stopping
home.frigate    | s6-rc: info: service log-prepare successfully stopped
home.frigate    | s6-rc: info: service legacy-cont-init: stopping
home.frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
home.frigate    | s6-rc: info: service legacy-cont-init successfully stopped
home.frigate    | s6-rc: info: service fix-attrs: stopping
home.frigate    | s6-rc: info: service fix-attrs successfully stopped
home.frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
home.frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
home.frigate exited with code 0
```

### FFprobe output from your camera

```shell
why??? so I did this command to first camera:

ffprobe rtsp://admin:xxx@192.168.255.91:554/live/main
ffprobe version 5.1.4-0+deb12u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5595bcf83700] max delay reached. need to consume packet
[rtsp @ 0x5595bcf83700] RTP: missed 26 packets
[h264 @ 0x5595bcf88200] error while decoding MB 232 107, bytestream -7
[h264 @ 0x5595bcf88200] concealing 6777 DC, 6777 AC, 6777 MV errors in I frame
Input #0, rtsp, from 'rtsp://admin:xxx@192.168.255.91:554/live/main':
  Metadata:
    title           : IPCAM
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 14.99 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, stereo, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Hview, Reolink

**Comment by NickM-27** [comment]
have you tried a full host hardware restart?

**Reply by bubba925** [reply]
I moved my server to new hardware recently. I use proxmox with the Coral passed through to an LXC. Was having a similar issue to you where the TPU would not be connected or would crash constantly. After a lot of software troubleshooting it turns out the coral wasn't fully seated in the riser I was using. Might be worth a look.

**Reply by aronmgv** [reply]
Yes, I performed update and server restart.. still crashing on the same error..

**Reply by aronmgv** [reply]
> I moved my server to new hardware recently. I use proxmox with the Coral passed through to an LXC. Was having a similar issue to you where the TPU would not be connected or would crash constantly. After a lot of software troubleshooting it turns out the coral wasn't fully seated in the riser I was using. Might be worth a look.

I doubted that but I did check and reseated it again and still same error.. `frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.` Thanks!

**Comment by psilantropy** [comment]
Try use each coral in a coral testing container to verify it functions. [Something like this](https://www.jeffgeerling.com/blog/2023/testing-coral-tpu-accelerator-m2-or-pcie-docker), but there are others.

I sometimes had a failure on my usb corals unless I specified model. This was a long time ago, but I've left my config like this anyway. Give it a whirl?

```
detectors:
  coral1:
    type: edgetpu
    device: usb:0
    model:
  coral2:
    type: edgetpu
    device: usb:1
    model:
```
