### DISCUSSION TITLE
[Support]: 0.14B1 Alerted event is messed up but partially working?

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#11546] [General Support] [answered]
### Describe the problem you are having

So I had a triggered event at 5:51PM and under the events section it was labeled as an Alert and the SNAPSHOT picture shows the truck (car) but when I hover over the video it starts to playback video around the 5:00:00 PM time and when I then click on the Alert event the UI redraws but the video playback starts shortly at 4:59PM

<img width="1344" alt="Screenshot 2024-05-26 at 7 20 46 PM" src="https://github.com/blakeblackshear/frigate/assets/108703/8aceab62-8dc7-4f37-8d1c-92ecd86d3f1a">

You can clearly see from the screenshot above the timecode for the event according to Frigate was around 5:51:30PM but the video isn't there. When I try to scrub closer to the event time wise on the right side the video disappears and then a spinning circle shows up in the section the video plays. 

I even tried to export the event as a test but just got nothing back and errors from the logs, provided below. I also tried to export 5:45PM to 6:00PM via the export function and never did anything. Logs indicate it TRIED but nothing.

I WAS able to submit the three "events" triggered via the Frigate+ section and they did upload just fine. 

If you need another logs let me know, I bumped up debugging now but didn't have it fully on before.

 

### Version

0.14.0-b97e274

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate.iot:5000/api/config/schema.json
mqtt:
  enabled: true
  host: mqtt.ha
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
timestamp_style:
  position: br
  format: '%m/%d/%Y %I:%M:%S %p'
model:
  path: plus://redacted
telemetry:
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
# Default, also tuned at a camera level depending on need.
# Heff if you are reading this remove this section as I am a Frigate+ user.
objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65 # .75 -> .65 20240508 after 2024.1 model
      threshold: .90 # .90 -> .85 20240508 after 2024.1 model
    car:
      min_score: .65
      threshold: .85

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 90
    mode: motion
  events:
    retain:
      default: 90
      mode: active_objects
      objects:
        dog: 7
        cat: 3
        car: 3
        package: 7

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  quality: 100
  retain:
    default: 90
    objects:
      dog: 7
      cat: 3
      car: 3
      package: 7

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2
  coral4:
    type: edgetpu
    device: pci:3

logger:
  default: debug
  logs:
    frigate.event: debug
    frigate.storage: debug
    frigate.object_detection: debug
    frigate.record.cleanup: debug

birdseye:
  enabled: true
  restream: true
  width: 3840
  height: 2160
  quality: 8
  mode: continuous



ui:
  #live_mode: webrtc
  time_format: 12hour
  #use_experimental: True # Breaks audio in live view

go2rtc:
  webrtc:
    candidates:
      - frigate.ip:8555
      - stun:8555
  rtsp:
    username: '{FRIGATE_RTSP_USER}'
    password: '{FRIGATE_RTSP_PASSWORD}'
  streams:
    # Driveway
    driveway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:driveway#audio=opus   # to hear sound with AAC camera audio for WebRTC needs to be PCM or opus, MSE does AAC native.
    driveway_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:driveway_sub#audio=opus
    # BBQ Deck
    bbq_deck:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@bbqdeck.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:bbq_deck#audio=opus
    bbq_deck_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@bbqdeck.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:bbq_deck_sub#audio=opus
    # Basement with AC units
    basement_side:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@basementside.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:basement_side#audio=opus
    basement_side_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@basementside.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:basement_side_sub#audio=opus
    # Front walkway
    frontwalkway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontwalkway.camera:554/Streaming/Channels/101
    frontwalkway_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontwalkway.camera:554/Streaming/Channels/102
    # Mudroom
    mudroom:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@mudroom.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:mudroom#audio=opus
    mudroom_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@mudroom.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:mudroom_sub#audio=opus
    # Kiddo's room
    charlotte:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@charlotte.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:charlotte#audio=opus
    charlotte_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@charlotte.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:charlotte_sub#audio=opus
    # Double Fence
    double_fence:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@double-fence.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:double_fence#audio=opus
    double_fence_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@double-fence.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:double_fence_sub#audio=opus
    # Patio
    patio:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@patio.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:patio#audio=opus
    patio_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@patio.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:patio_sub#audio=opus
    # Backyard
    backyard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@backyard.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:backyard#audio=opus
    backyard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@backyard.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:backyard_sub#audio=opus
    # Playroom
    playroom:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom.camera:554/Streaming/Channels/101
      - ffmpeg:playroom#audio=opus
    playroom_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom.camera:554/Streaming/Channels/102
      - ffmpeg:playroom#audio=opus

cameras:
  Driveway: # Driveway
    live:
      stream_name: driveway
    snapshots:
      required_zones:
        - Front_Yard
    ui:
      order: 1
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    objects:
      track:
        - person
        - car
        - face
        - package
        - amazon
        - fedex
        - ups
        - license_plate
        - dog
    motion:
      mask:
        - 0.703,0.095,0.704,0.022,0.969,0.03,0.97,0.09
        - 0.741,0,1,0,1,0.276,0.739,0.146,0.503,0.115,0.186,0.134,0,0.254,0,0.171,0,0
    zones:
      Front_Yard:
        coordinates:
          1,1,0.942,0.338,0.862,0.214,0.649,0.143,0.393,0.128,0.309,0.142,0.23,0.139,0,0.352,0,1
        objects:
          - person
          - car
          - face
          - package
          - amazon
          - fedex
          - ups
          - license_plate
          - dog
        inertia: 3
      Street:
        coordinates:
          0.181,0.132,0.358,0.105,0.596,0.099,0.753,0.13,0.904,0.206,1,0.28,1,0,0.276,0,0,0,0,0.283,0.095,0.21
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: Front_Yard
      detections:
        required_zones: Street
  Patio: # Patio
    live:
      stream_name: patio
    ui:
      order: 3
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patio_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask:
        - 0.665,0,1,0.614,1,0,0.839,0
        - 0.422,0,0.258,0,0.332,0.108,0.355,0.356,0.641,0.356,0.645,0.083,0.724,0
    objects:
      track:
        - person
        - face
  Basement_Side: # Basement Side with AC
    live:
      stream_name: basement_side
    snapshots:
      required_zones:
        - Basement_Side_Yard
    ui:
      order: 4
    birdseye:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/basement_side
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/basement_side_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    objects:
      track:
        - person
        - face
        - dog
      #filters:
      #  person:
      #    min_area: 4000 # 20240508 after 2024.1 model
    motion:
      mask:
        - 0.291,0.137,0.392,0.185,0.501,0.196,0.497,0.343,1,0.665,1,0,0.292,0
        - 0.323,0.527,0.464,0.489,0.426,0.393,0.305,0.409
        - 0.26,0.332,0.352,0.314,0.327,0.276,0.255,0.291
        - 0.806,0.962,1,0.965,1,0.898,0.804,0.901
    zones:
      Basement_Side_Yard:
        coordinates:
          0.313,0.204,0.402,0.173,0.492,0.201,0.487,0.339,0.657,0.451,1,0.689,1,1,0.287,1,0.237,0.601,0.231,0.218
        objects:
          - person
          - face
          - dog
        inertia: 3
    review:
      alerts:
        required_zones: Basement_Side_Yard
  BBQ_Deck: # BBQ Deck
    live:
      stream_name: bbq_deck
    snapshots:
      required_zones:
        - BBQ_Deck_Yard
        - BBQ_Deck_Door
    ui:
      order: 5
    birdseye:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bbq_deck
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bbq_deck_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    objects:
      track:
        - person
        - dog
        - face
    motion:
      mask:
        - 0.976,0.025,0.977,0.092,0.701,0.09,0.699,0.022
        - 0,0.627,0,0,0.294,0
    zones:
      BBQ_Deck_Door:
        coordinates: 0.898,1,0.762,0.641,0.459,0.714,0.468,1
        objects: dog
        inertia: 3
      BBQ_Deck_Yard:
        coordinates:
          0.435,0.173,0.424,1,0,1,0.021,0.859,0.285,0.143,0.436,0,0.599,0,0.73,0.294,0.583,0.313,0.551,0.237,0.513,0.203
        objects:
          - person
          - face
        inertia: 3
    review:
      alerts:
        required_zones:
          - BBQ_Deck_Yard
          - BBQ_Deck_Door
  Front_Walkway: # Front Walkway
    live:
      stream_name: frontwalkway
    ui:
      order: 2
    birdseye:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontwalkway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontwalkway_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      enabled: true
      fps: 10
    motion:
      mask:
        - 0.557,0,0.898,0,0.9,0.048,0.56,0.036
        - 0.133,0.499,0.387,0.074,0.318,0,0,0,0,1,0.399,1
        - 0.585,1,1,1,1,0.892,1,0.818,0.879,0.661,0.758,0.562,0.65,0.566,0.574,0.761,0.649,0.869
        - 0.311,0.221,0.393,0.051,0.506,0.116,0.576,0.247,0.487,0.46,0.392,0.489
    objects:
      track:
        - person
        - package
        - face
        - dog
  Mudroom:
    live:
      stream_name: mudroom
    ui:
      order: 6
    birdseye:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mudroom
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mudroom_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask: 0.704,0.086,0.701,0.019,0.979,0.026,0.975,0.083
    objects:
      track:
        - person
        - face
        - dog
      #filters: # Disabled after 2024-04-29 on new 2024.1 model to test
        #person:
          #mask:
            #- 1651,184,1635,593,1439,588,1459,190 # Storage rack getting classified as person, training it out
  Backyard: # Backyard
    live:
      stream_name: backyard
    ui:
      order: 7
    birdseye:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask: 0.252,0.229,0.386,0.11,0.649,0.14,0.768,0.251,1,0.477,1,0,0.393,0,0,0,0,0.392
    objects:
      track:
        - person
        - face
        - dog
  Charlotte: # Kiddo's room
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    live:
      stream_name: charlotte
    ui:
      order: 9
    birdseye:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/charlotte
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/charlotte_sub
          roles:
            - audio
            - detect
    objects:
      filters:
        person: {}
    detect:
      enabled: true
    audio:
      enabled: true
      listen:
        - scream
        - crying
        - yell
        - beep
    motion: {}
  Double_Fence: # Double Fence
    live:
      stream_name: double_fence
    ui:
      order: 8
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/double_fence
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/double_fence_sub
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - face
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask:
        - 1,0,1,0.535,0.889,0.34,0.742,0.126,0.532,0,0.692,0
        - 0.178,0,0.186,0.09,0.386,0
  Playroom: # Kiddo's room
    record:
      enabled: true
      retain:
        days: 5
        mode: all
    live:
      stream_name: playroom_sub
    ui:
      order: 10
    birdseye:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/playroom
          roles:
            - record
    detect:
      enabled: false
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras:
      - birdseye
  Front:
    order: 2
    icon: LuCar
    cameras:
      - Driveway
      - Front_Walkway
  Patio:
    order: 3
    icon: LuRockingChair
    cameras:
      - BBQ_Deck
      - Patio
```

### Relevant log output

```shell
2024-05-26 19:13:29.519207715  ::ffff:172.19.0.1 - - [26/May/2024:19:13:29 -0400] "GET /clips/previews/Driveway/1716760813.222011-1716764400.060903.mp4 HTTP/1.1" 206 2 "https://frigate.domain.com/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "xxx.xxx.xxx.xxx"
2024-05-26 19:13:29.537193021  ::ffff:172.19.0.1 - - [26/May/2024:19:13:29 -0400] "GET /clips/previews/Driveway/1716760813.222011-1716764400.060903.mp4 HTTP/1.1" 206 4062533 "https://frigate.domain.com/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "xxx.xxx.xxx.xxx"
2024-05-26 19:13:33.297431178  [2024-05-26 19:13:33] asyncio                        DEBUG   : Using selector: EpollSelector
2024-05-26 19:13:34.801001380  [2024-05-26 19:13:34] peewee                         DEBUG   : ('SELECT COUNT(1) FROM (SELECT 1 FROM "recordings" AS "t1" WHERE (((("t1"."start_time" BETWEEN ? AND ?) OR ("t1"."end_time" BETWEEN ? AND ?)) OR (("t1"."start_time" < ?) AND ("t1"."end_time" > ?))) AND ("t1"."camera" = ?))) AS "_wrapped"', [1716760292.418303, 1716760338.445531, 1716760292.418303, 1716760338.445531, 1716760292.418303, 1716760338.445531, 'Driveway'])
2024-05-26 19:13:34.807257984  ::ffff:172.19.0.1 - - [26/May/2024:19:13:34 -0400] "GET /api/config HTTP/1.1" 200 58140 "https://frigate.domain.com/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "xxx.xxx.xxx.xxx"
2024-05-26 19:13:34.820868938  [2024-05-26 19:13:34] frigate.record.export          DEBUG   : Beginning export for Driveway from 1716760292 to 1716760338
2024-05-26 19:13:34.820980134  [2024-05-26 19:13:34] peewee                         DEBUG   : ('SELECT "t1"."camera", "t1"."path", "t1"."duration", "t1"."start_time", "t1"."end_time" FROM "previews" AS "t1" WHERE (((("t1"."start_time" BETWEEN ? AND ?) OR ("t1"."end_time" BETWEEN ? AND ?)) OR (("t1"."start_time" < ?) AND ("t1"."end_time" > ?))) AND ("t1"."camera" = ?)) LIMIT ? OFFSET ?', [1716760292, 1716760338, 1716760292, 1716760338, 1716760292, 1716760338, 'Driveway', 1, 0])
2024-05-26 19:13:34.821367900  ::ffff:172.19.0.1 - - [26/May/2024:19:13:34 -0400] "POST /api/export/Driveway/start/1716760292.418303/end/1716760338.445531 HTTP/1.1" 200 59 "https://frigate.domain.com/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "xxx.xxx.xxx.xxx"
2024-05-26 19:13:34.821764146  Exception in thread Thread-320:
2024-05-26 19:13:34.821772702  Traceback (most recent call last):
2024-05-26 19:13:34.821779347    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 7270, in get
2024-05-26 19:13:34.822881231      return clone.execute(database)[0]
2024-05-26 19:13:34.822886929    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 4570, in __getitem__
2024-05-26 19:13:34.823379947      return self.row_cache[item]
2024-05-26 19:13:34.823415631  IndexError: list index out of range
2024-05-26 19:13:34.823417243
2024-05-26 19:13:34.823419029  During handling of the above exception, another exception occurred:
2024-05-26 19:13:34.823420161
2024-05-26 19:13:34.823421424  Traceback (most recent call last):
2024-05-26 19:13:34.823422925    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2024-05-26 19:13:34.823588970      self.run()
2024-05-26 19:13:34.823610784    File "/opt/frigate/frigate/record/export.py", line 168, in run
2024-05-26 19:13:34.823806832      thumb_path = self.save_thumbnail(export_id)
2024-05-26 19:13:34.823809699    File "/opt/frigate/frigate/record/export.py", line 78, in save_thumbnail
2024-05-26 19:13:34.823858850      Previews.select(
2024-05-26 19:13:34.823862523    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 7273, in get
2024-05-26 19:13:34.824955665      raise self.model.DoesNotExist('%s instance matching query does '
2024-05-26 19:13:34.824965943  frigate.models.PreviewsDoesNotExist: <Model: Previews> instance matching query does not exist:
2024-05-26 19:13:34.824968600  SQL: SELECT "t1"."camera", "t1"."path", "t1"."duration", "t1"."start_time", "t1"."end_time" FROM "previews" AS "t1" WHERE (((("t1"."start_time" BETWEEN ? AND ?) OR ("t1"."end_time" BETWEEN ? AND ?)) OR (("t1"."start_time" < ?) AND ("t1"."end_time" > ?))) AND ("t1"."camera" = ?)) LIMIT ? OFFSET ?
2024-05-26 19:13:34.824974675  Params: [1716760292, 1716760338, 1716760292, 1716760338, 1716760292, 1716760338, 'Driveway', 1, 0]
2024-05-26 19:13:38.303193859  [2024-05-26 19:13:38] asyncio                        DEBUG   : Using selector: EpollSelector
2024-05-26 19:13:38.561441178  ::ffff:172.19.0.1 - - [26/May/2024:19:13:38 -0400] "GET /clips/previews/Driveway/1716760813.222011-1716764400.060903.mp4 HTTP/1.1" 206 2 "https://frigate.domain.com/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "xxx.xxx.xxx.xxx"
2024-05-26 19:13:38.570893369  ::ffff:172.19.0.1 - - [26/May/2024:19:13:38 -0400] "GET /clips/previews/Driveway/1716760813.222011-1716764400.060903.mp4 HTTP/1.1" 206 4062533 "https://frigate.domain.com/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "xxx.xxx.xxx.xxx"
```

### FFprobe output from your camera

```shell
$ docker exec -it frigate ffprobe "rtsp://camera/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5581aac42140] max delay reached. need to consume packet
[rtsp @ 0x5581aac42140] RTP: missed 152 packets
[h264 @ 0x5581aac474c0] error while decoding MB 223 80, bytestream -5
[h264 @ 0x5581aac474c0] concealing 13026 DC, 13026 AC, 13026 MV errors in P frame
Input #0, rtsp, from 'rtsp://camera/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 30 fps, 100 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
  Stream #0:2: Data: none
Unsupported codec with id 0 for input stream 2
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Amcrest IP8M-2696E-AI
