### DISCUSSION TITLE
Object masks seems not to be applied

### DISCUSSION THREAD

**Discussion by maxdd** [blakeblackshear/frigate#11553] [General]
Hello,
i'm on docker 0.13.2 of frigate with the following config

```
    objects:
      track:
      - person
      - face
      - bird
      - cat
      - dog
      filters:
        person:
          mask:
          - 199,92,192,34,216,28,209,89

```

![image](https://github.com/blakeblackshear/frigate/assets/6155973/55a01901-7c6c-42bf-a0f2-f2d43699e36f)

but i pretty much always get false detection there.
The "live" debug view is always showing the following

![image](https://github.com/blakeblackshear/frigate/assets/6155973/b6dd574b-3a28-4935-aa1c-fe161522a49e)

I'm using two streams, one in 2K and the other is 720p.
Could it be an issue with the coordinates?
The zone definition seems to be fine
