### DISCUSSION TITLE
[Support]: Is it possible to exclude a camera from alerts?

### DISCUSSION THREAD

**Discussion by Mincka** [blakeblackshear/frigate#11558] [General Support] [answered]
### Describe the problem you are having

I would like to exclude a camera from alerts.
I did not find a way to exclude it from alerts in the configuration.

Is it valid to provide an empty label list in the configuration at the camera level?

```
review:
  alerts:
    labels:
```

### Version

0.14 beta 1

### Frigate config file

```yaml
review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - person
      - car

Nothing in `review:` for the camera I want to exlude from alerts.
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment, marked as answer]
yes, it is valid to provide an empty list for alert labels

**Reply by Mincka** [reply]
Ok, thank you.

For anyone interested, the exact required syntax is the following:

```yaml
cameras:
  Backyard:
    review:
      alerts:
        labels: []
```
