### DISCUSSION TITLE
Guide: Frigate 0.14 review notifications in HomeAssistant

### DISCUSSION THREAD

**Discussion by NickM-27** [blakeblackshear/frigate#11554] [Tips]
As part of the [new Frigate UI](https://github.com/blakeblackshear/frigate/discussions/11136) events are now intelligently organized into different categories and combined by times of activity. This means that a person delivering a package is one review item instead of having separate events for the person and the package. This behavior is often also desirable for notifications. In Frigate 0.14 there is a new `/reviews` MQTT topic that can be used for notifications as well. 

## Automation YAML

```yaml
alias: Frigate Notifications
description: ""
# The trigger is mqtt and will fire when any camera has an alert
trigger:
  - alias: "topic published to /reviews"
    platform: mqtt
    topic: frigate/reviews
    id: frigate-event
    payload: alert  # this ensures notifications are only received for alerts
    value_template: "{{ value_json['after']['severity'] }}"
    variables:
      zones: "{{ trigger.payload_json['after']['data']['zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      before_objects: "{{ trigger.payload_json['before']['data']['objects'] }}"
      objects: "{{ trigger.payload_json['after']['data']['objects'] }}"
      sub_labels: "{{ trigger.payload_json['after']['data']['sub_labels'] }}"
      events: "{{ trigger.payload_json['after']['data']['detections'] }}"
      type: "{{ trigger.payload_json['type'] }}"
condition:
  - alias: Update has no new objects
    condition: template
    value_template: "{{ type != \"update\" or before_zones | length < after_zones | length }}"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: frigate-event
        sequence:
          # this is a custom notification script, see an example of using the built in notification service below
          - service: script.send_dynamic_notification_to_all_devices
            data:
              id: "{{ id }}"
              title: >-
                {% set data = namespace(labels=[]) %} {% for obj in objects %}
                    {% if "-verified" in obj %}
                    {% else %}
                        {% set data.labels = data.labels + [obj] %}
                    {% endif %}
                {% endfor %} {% set data.labels = data.labels + sub_labels %} {{
                data.labels | unique | list | sort | join(", ") | title }}{{ '
                was' if type == "end" else '' }} detected in {{ zones | join(',
                ') | replace("_", " ") | title }}
              message: Detected on {{ camera | replace("_", " ") | title }}
              notifTag: "{{ id }}"
              notifIcon: >-
                {% if objects[0] == "cat" -%} mdi:cat {%- elif objects[0] ==
                "dog" -%} mdi:dog-service {%- elif objects[0] == "person" and
                type == "end" -%} mdi:account-outline {%- elif objects[0] ==
                "person" -%} mdi:account-clock-outline {%- elif objects[0] ==
                "person-verified" -%} mdi:account-check-outline {%- elif
                objects[0] == "package" -%} mdi:package-variant-closed-check {%-
                elif objects[0] == "amazon" -%} mdi:truck-delivery-outline {%-
                elif objects[0] == "fedex" -%} mdi:truck-delivery-outline {%-
                elif objects[0] == "ups" -%} mdi:truck-delivery-outline {%- elif
                objects[0] == "car" -%} mdi:car-outline {%- elif objects[0] ==
                "car-verified" -%} mdi:car-outline {%- else -%} mdi:cctv {%-
                endif %}
              group: frigate-notification-{{ camera }}
              channel: Frigate
              importance: "{{ \"max\" if type != \"end\" else \"default\" }}"
              label: "{{objects | join(', ')}}"
              camera: "{{camera}}"
              live: |-
                {% if type == "end" -%}
                  https://HA_BASE_URL/review?id={{id}}
                {%- else -%}
                  https://FRIGATE_BASE_URL/#{{camera}}
                {%- endif %}
              image: |-
                {% if type == "end" -%}
                  {{undefined}}
                {%- else -%}
                  https://HA_BASE_URL/api/frigate/notifications/{{events[0]}}/snapshot.jpg?bbox=1
                {%- endif %}
              video: |-
                {% if type == "end" -%}
                  https://HA_BASE_URL/api/frigate/notifications/{{id}}/review_preview.gif?format=ts
                {%- else -%}
                  {{undefined}}
                {%- endif %}
    default: []
mode: parallel
trace:
  stored_traces: 100
max: 10
```

### Example Payload

Here is an example payload

```yaml
  payload_json:
    type: end  #  new, update, or end
    before:
      id: 1716750796.680641-ao0d9x
      camera: front_doorbell_cam
      start_time: 1716750796.680641
      end_time: 1716750832.273281
      severity: alert  # detection or alert
      thumb_path: >-
        /media/frigate/clips/review/thumb-front_doorbell_cam-1716750796.680641-ao0d9x.webp
      data:
        detections:  # list of event IDs (can be used for getting a snapshot or clip of that object specifically)
          - 1716750795.092463-autt0m
        objects:  # list of object labels
          - person
        sub_labels: []  # list of sub labels
        zones:  # zones that have been entered
          - front_porch
        audio: []  # list of audio labels
    after:
      id: 1716750796.680641-ao0d9x
      camera: front_doorbell_cam
      start_time: 1716750796.680641
      end_time: 1716750832.273281
      severity: alert
      thumb_path: >-
        /media/frigate/clips/review/thumb-front_doorbell_cam-1716750796.680641-ao0d9x.webp
      data:
        detections:
          - 1716750795.092463-autt0m
        objects:
          - person
        sub_labels: []
        zones:
          - front_porch
        audio: []
```
 
## Simple Notification Service

Reference the [HomeAssistant notification docs](https://www.home-assistant.io/integrations/notify/)for how to customize these.

```yaml
- service: notify.PHONE_SERVICE
  data:
    title: >-
      {{label | title}} was detected on {{
      trigger.payload_json["after"]["camera"] | replace("_", "
      ") | title }}
    message: >-
      {{label | title}} detected in the {{
      after_zones[0] }}
    data:
      url: >-
      HASS_URL_BASE/api/{{ id }}/{{camera}}/clip.mp4
      tag: '{{ id }}'
      group: frigate-notification-{{camera}}
      clickAction: >-
        HASS_URL_BASE/api/{{id}}/{{camera}}/clip.mp4
      image: >-
        /api/frigate/notifications/{{id}}/snapshot.jpg
      attachment:
        url: >-
          /api/frigate/notifications/{{id}}/snapshot.jpg
```

**Comment by superdong69** [comment]
Does this replace the need for SGTBattens blueprint in 0.14? I added the automation portion of your code to my automations.yaml, and created a script using the script portion, but I can't get it to do anything.

**Reply by NickM-27** [reply]
yes, this is doing the same thing

**Comment by fisch55** [comment]
@superdong69 
does not work for me..... maybe you could show a full example...

**Reply by superdong69** [reply]
Also doesn't work for me. LOL But I'm having major issues with the update.

**Comment by Elder-HVAC-Man** [comment]
I need a set up guide for dummies 101.

**Reply by NickM-27** [reply]
this automation isn't meant to solve that need, for that most likely best to just wait for a blueprint to be offered

**Reply by Elder-HVAC-Man** [reply]
Thanks for the reply.  Will wait on SGTBattens blueprint to be updated.  His blueprint works for notifications, just no video stream on my watch.

**Comment by SgtBatten** [comment]
What's the -verified part doing Nik?

**Reply by NickM-27** [reply]
So `-verified` basically points to any object that has a sub label that is not in the labelmap. For example a person that has been tagged by doubletake. The issue in general is that we show this in the UI but there is no way to know just based off of a sub label if it is a person, car, etc. So instead the backend notates these as `{label}-verified` so we know to show a check mark next to the icon to designate it is a known object. 

The logic in this automation is basically trying to filter those out and include the sub labels. It would be redundant for the notification to say `person, person-verified, Nick detected in the front yard` for example

**Comment by ofcedwards** [comment]
>       id: "{{ trigger.payload_json['after']['id'] }}"

From what I can tell, this is no longer the proper way to reference an event id for the purpose of pulling a thumbnail, snapshot, or clip in a Home Assistant notification. I might be misunderstanding the new system with reviews, but this id seems to refer to the overall review item (which can include multiple objects) and not a singular detection like in 0.13.

To get a thumbnail in a notification like I would with the regular frigate/events topic, I need to set the variable to ````id: "{{ trigger.payload_json['after']['data']['detections'][0] }}"```` which you have under the "events" variable.

It would appear that what I'm familiar with as event id's are listed out under "detections" now as an array. This difference is likely why other users are unsuccessful in getting the template to produce a notification. I imagine (like myself), they used your template for the mqtt trigger and paired it with the provided "simple notification service" (which also uses a variable "label" instead of "objects").

These few tweaks seem to have my notifications working like before, but with customization of what causes a notification done through Frigate's alerts vs. detections instead of a bunch of conditions in Home Assistant. Really liking 0.14 so far and I hope this helps someone passing by!

**Comment by SgtBatten** [comment]
Hi Nick, 

I cant seem to get the preview gif to load, even just as a url outside the notification.

**Reply by NickM-27** [reply]
What response are you getting and what url are you using

**Reply by SgtBatten** [reply]
{{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif?format=ts

https://ha.mydomain.com/api/frigate/notifications/{{review_id}}/review_preview.gif?format=ts

![image](https://github.com/blakeblackshear/frigate/assets/24822223/e1453a2d-911b-43a2-a28b-21b410da4e99)

might be having issues, or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Reply by NickM-27** [reply]
this endpoint doesn't exist in the latest version of the integration (only in the dev branch) so you might need to edit the file in the custom_component to enable it

**Reply by SgtBatten** [reply]
ahh okay thanks. bit beyond me at this time of day. will look at it on the weekend. thank you

**Reply by NickM-27** [reply]
I will look at doing a beta update for that

**Reply by Mincka** [reply]
Since https://github.com/blakeblackshear/frigate-hass-integration/pull/687 was merged two weeks ago, can we expect the release 5.3.0 of the integration in the coming days? It would be great to have the support of the GIF previews.

**Reply by NickM-27** [reply]
yes, should be soon

**Reply by substeeze** [reply]
Thanks to this guide, I've managed to get a simple notification automation working (tested with Apple devices) for the animated gif preview. It uses the unauthenticated port 5000 api, which is far from ideal, but as my instance is only accessed via a VPN I'm not too fussed for now.

I've set conditions to limit to a specific camera and ensure at least one zone has been triggered.

There is also a condition to limit processing to the 'end' message. The frigate/review mqtt topic issues 'new' 'update' and 'end' messages for a each review event. I want to wait for the 'end' message so I get the full preview gif - however, this does mean the notification is issued after the event, so bear that in mind.

I have also added 'persistent: true' to the notification, so that you have to actively swipe to dismiss each event notification. I found that without this, I'd often accidentally clear all my frigate notifications before I'd had a chance to review them!

Just ensure your frigate instance port 5000 is accessible from your device, replace your_camera_name and your_frigate_ip with the relevant name/ip for your instance.

```yaml
alias: Preview GIF Notification
description: Send the preview gif at the end of an event
triggers:
  - alias: Trigger on frigate/reviews topic
    topic: frigate/reviews
    variables:
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      type: "{{ trigger.payload_json['type'] }}"
      events: "{{ trigger.payload_json['after']['data']['detections'] }}"
      zones: "{{ trigger.payload_json['after']['data']['zones'] }}"
    trigger: mqtt
conditions:
  - alias: Limit to a specific camera
    condition: template
    value_template: "{{ camera == \"your_camera_name\" }}"
  - alias: Is this trigger the end of the event?
    condition: template
    value_template: "{{ type == \"end\" }}"
  - alias: Ensure a zone has been triggered
    condition: template
    value_template: "{{ zones != [] }}"
actions:
  - action: notify.notify
    data:
      message: New Event
      title: Frigate
      data:
        persistent: true
        attachment:
          url: http://your_frigate_ip:5000/api/events/{{ events[0] }}/preview.gif
mode: parallel
trace:
  stored_traces: 100
max: 10
```

**Reply by substeeze** [reply]
Whilst that last automation works for a preview. I've realised it only gives you the last 20 seconds of the event. To get the full gif preview, as you would see in the Frigate web UI, the /api/review call is required. Unfortunately, this doesn't have a .gif postfix file extension, so my iPhone couldn't determine the file type from the url. Explicitly specifying 'content-type: gif' in the attachment call fixes this. The iPhone will play the looping gif when the notification is long-press expanded. The iMac and Apple Watch just show the first still image.

Sorry for spamming this thread - it's probably not the right place for this! As you can probably tell, I'm quite new to github/frigate/homeassistant/yaml etc!!

```yaml
alias: Send the preview gif at the end of a review event
description: Replace your_camera_name and your_frigate_ip with details of your instance
triggers:
  - alias: Trigger on frigate/reviews topic
    topic: frigate/reviews
    variables:
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      type: "{{ trigger.payload_json['type'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      zones: "{{ trigger.payload_json['after']['data']['zones'] }}"
    trigger: mqtt
conditions:
  - alias: Limit to a specific camera
    condition: template
    value_template: "{{ camera == \"your_camera_name\" }}"
  - alias: Is this trigger the end of the event?
    condition: template
    value_template: "{{ type == \"end\" }}"
  - alias: Ensure a zone has been triggered
    condition: template
    value_template: "{{ zones != [] }}"
actions:
  - action: notify.notify
    data:
      message: New Event
      title: Frigate
      data:
        persistent: true
        attachment:
          content-type: gif
          url: http://your_frigate_ip:5000/api/review/{{ id }}/preview?gif
mode: parallel
trace:
  stored_traces: 100
max: 10
```

**Reply by Hasnaat-k** [reply]
Surely there's a better way to viewing gif preview than exposing port 5000?

**Reply by NickM-27** [reply]
You can use the authenticated port with the integration as well

**Comment by Morphy99** [comment]
Is this info still valid? I get an error when trying to call the `notify` service:
`Error: Error rendering data template: UndefinedError: 'after_zones' is undefined`

```
- id: Camera Alert
  alias: Camera Alert
  mode: restart
  trace:
    stored_traces: 20
  trigger:
    platform: mqtt
    topic: frigate/reviews
    payload: alert
    id: frigate-event
    value_template: "{{ value_json['after']['severity'] }}"
    variables:
      zones: "{{ trigger.payload_json['after']['data']['zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      before_objects: "{{ trigger.payload_json['before']['data']['objects'] }}"
      objects: "{{ trigger.payload_json['after']['data']['objects'] }}"
      sub_labels: "{{ trigger.payload_json['after']['data']['sub_labels'] }}"
      events: "{{ trigger.payload_json['after']['data']['detections'] }}"
      type: "{{ trigger.payload_json['type'] }}"
  condition:
    - alias: Update has no new objects
      condition: template
      value_template: "{{ type != \"update\" or before_zones | length < after_zones | length }}"
    - condition: template
      value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.camera_alert', 'last_triggered') | default(0), 0) | int > 30)}}"
  action:
    - service: notify.mobile_app
      data:
        message: >-
          {{label | title}} detected in the {{
          after_zones[0] }}
        title: >-
          {{label | title}} was detected on {{
          trigger.payload_json["after"]["camera"] | replace("_", "
          ") | title }}
        data:
          channel: "Cameras Max"
          ttl: 0
          priority: high
          media_stream: alarm_stream_max
          image: >-
            /api/frigate/notifications/{{id}}/snapshot.jpg
          tag: '{{ id }}'
          url: >-
            https://url/api/{{ id }}/{{camera}}/clip.mp4
          actions:
            - action: URI
              title: Video
              uri: >-
                https://url/api/{{id}}/{{camera}}/clip.mp4
            - action: URI
              title: View Snapshot
              uri: >-
                https://url/api/{{id}}/{{camera}}/snapshot.jpg
            - action: "MUTE_FRONT"
              title: Mute
          clickAction: "/lovelace/cameras-live"
```

**Reply by NickM-27** [reply]
You have after_zones but there is no variable called after_zones, it is just called zones

**Reply by Morphy99** [reply]
I just copied your example:
> ## Simple Notification Service
> Reference the [HomeAssistant notification docs](https://www.home-assistant.io/integrations/notify/)for how to customize these.
> 
> ```yaml
> - service: notify.PHONE_SERVICE
>   data:
>     title: >-
>       {{label | title}} was detected on {{
>       trigger.payload_json["after"]["camera"] | replace("_", "
>       ") | title }}
>     message: >-
>       {{label | title}} detected in the {{
>       after_zones[0] }}
>     data:
>       url: >-
>       HASS_URL_BASE/api/{{ id }}/{{camera}}/clip.mp4
>       tag: '{{ id }}'
>       group: frigate-notification-{{camera}}
>       clickAction: >-
>         HASS_URL_BASE/api/{{id}}/{{camera}}/clip.mp4
>       image: >-
>         /api/frigate/notifications/{{id}}/snapshot.jpg
>       attachment:
>         url: >-
>           /api/frigate/notifications/{{id}}/snapshot.jpg
> ```

I've tried removing the after which now makes the notification trigger but the message just says "was detected on front". The object name is missing.

**Reply by Morphy99** [reply]
Also no snapshot and the link says no event. Is it `{{ id }}` or `{{  id  }}` in the URL?

**Reply by ofcedwards** [reply]
Here's the yaml for my automation that's been thoroughly tested and working for months. I have it set how I prefer things, so you may need to make some tweaks. But it's a good starting point.

````
alias: "Frigate: Recent Review"
description: ''
trigger:
  - platform: mqtt
    topic: frigate/reviews
    payload: "on"
    value_template: >-
      {{ 'on' if (value_json['type'] == 'new' and value_json['after']['severity'] == 'alert') or
      (value_json['before']['severity'] != value_json['after']['severity']) or
      (value_json['type'] == 'update' and value_json['after']['severity'] == 'alert'
      and (now() | as_timestamp - this.attributes.last_triggered | as_timestamp > 20)) else 'off' }}
condition: []
action:
  - alias: Notify Devices
    service: notify.devices
    data:
      title: "{{ objects }} Detected"
      message: New alert on {{ camera }} camera
      data:
        url: http://REPLACE_WITH_YOUR_FRIGATE_URL:5000/#{{ after['camera'] }}
        attachment:
          url: /api/frigate/notifications/{{ trigger_event }}/thumbnail.jpg
        actions:
          - action: URI
            title: View Clip
            uri: http://REPLACE_WITH_YOUR_FRIGATE_URL:5000/review?id={{ id }}
          - action: URI
            title: View Snapshot
            uri: /api/frigate/notifications/{{ trigger_event }}/snapshot.jpg
        tag: "{{ id }}"
        push:
          interruption-level: "{{ interruption_level }}"
mode: queued
variables:
  before: "{{ trigger.payload_json['before'] }}"
  after: "{{ trigger.payload_json['after'] }}"
  objects: >-
    {% set ns = namespace(list=[]) %}
    {% for item in after['data']['objects'] %}
      {% if item not in before['data']['objects'] %}
        {% set ns.list = ns.list + [item] %}
      {% endif %}
    {% endfor %}
    {{ (ns.list | join(', ') if ns.list | length > 0 else after['data']['objects'] | join(', ')) | title }}
  id: "{{ after['id'] }}"
  camera: "{{ after['camera'].replace('_',' ') }}"
  trigger_event: >-
    {% set ns = namespace(list=[]) %}
    {% for item in after['data']['detections'] %}
      {% if item not in before['data']['detections'] %}
        {% set ns.list = ns.list + [item] %}
      {% endif %}
    {% endfor %}
    {{ ns.list | max if ns.list | length > 0 else after['data']['detections'] | max }}
  interruption_level: >-
    {{ 'passive' if before['severity'] == after['severity'] and trigger.payload_json['type'] != 'new' else 'active' }}
max: 10
trace:
  stored_traces: 100
````

**Reply by Morphy99** [reply]
Thanks, I'll take a look and see how it works. Does it have the event animation thumbnail? Templates baffle me a lot of the time though and yours looks even more complicated!

One thing I do need is a way to incorporate a notification input_boolean helper per camera. I like to be able to still record events but turn off notifications on a per camera basis. I did have separate automations per camera but it would be nice if I could achieve this in one automation now.

**Reply by ofcedwards** [reply]
> Does it have the event animation thumbnail?

I'm not exactly sure what you're asking here. Do you mean the preview gif?

> Templates baffle me a lot of the time

Keep in mind that this is not exactly a template. This is what I've come up with to meet my own needs, but it has all the necessary foundations to build upon.

> One thing I do need is a way to incorporate a notification input_boolean helper per camera. I like to be able to still record events but turn off notifications on a per camera basis. I did have separate automations per camera but it would be nice if I could achieve this in one automation now.

Personally, I would achieve this with a template condition. The easiest way to do it would be have each input boolean match the name of the camera in frigate (so if frigate config has `front_door` as camera name, you create a bool called `input_boolean.front_door`). You'll place that in the `condition` section that I have as an empty list in my automation. That would look something like this:

````
condition:
  - condition: template
    value_template: "{{ false if states('input_boolean.' + after['camera']) == 'off' else true }}"
````

This will dynamically change the name of the input boolean to `input_boolean.CAMERA_NAME` to match which frigate camera the alert is coming from. The condition fails if the input boolean is switched off and will not fire the automation. In all other cases (boolean is on or there is no matching boolean), the condition passes and the automation fires.

**Reply by Morphy99** [reply]
> I'm not exactly sure what you're asking here. Do you mean the preview gif?

Yes. I've tested yours and it works great but no preview gif. 

Thanks for the info, I will give what you've explained a try!

**Reply by ofcedwards** [reply]
> Yes. I've tested yours and it works great but no preview gif.

I don't use the preview gifs because they don't play on Apple Watch (appears to be a Home Assistant issue). If you want to use them, change the `attachment` block (found under service -> data -> message -> data) in the action yaml to this:

````
        attachment:
          url: /api/frigate/notifications/{{ id }}/review_preview.gif
````

This is changing the notification attachment from the static thumbnail to the gif.

If you haven't already, you'll need to update the frigate integration in HACS to 5.3.0 to access the gifs.

**Reply by Morphy99** [reply]
The preview GIF doesn't animate for me, I'm guessing that's my phone's limitation. 

I'm using Android not iOS so I don't need  ```
          url: >-
            https://url/api/{{ id }}/{{camera}}/clip.mp4
``` or `interruption_level: >-`

I'm also struggling with the URL's for videos and snapshots. I get a 404: not found error. 

I'm confused why the URL's have changed and they seem to be different in your example to Nicks, are you only viewing clips on your LAN and not outside?

```
        actions:
          - action: URI
            title: View Clip
            uri: http://REPLACE_WITH_YOUR_FRIGATE_URL:5000/review?id={{ id }}
          - action: URI
            title: View Snapshot
            uri: /api/frigate/notifications/{{ trigger_event }}/snapshot.jpg
```
I use Nabu Casa so doesn't this url need to be before `/api`?

**Reply by ofcedwards** [reply]
> The preview GIF doesn't animate for me, I'm guessing that's my phone's limitation.

Precisely why I don't use it, though I'm not sure if there's something different you need to do on Android to have it work.

> I'm using Android not iOS so I don't need `url: >- https://url/api/{{ id }}/{{camera}}/clip.mp4`

This line isn't anywhere in my yaml, so I can't speak to whether you need it or not, but the clip has nothing to do with Android vs iOS.

> I'm also struggling with the URL's for videos and snapshots. I get a 404: not found error.

The urls for snapshots haven't changed at all from 0.13 to 0.14, so you may have some other networking error going on there. It's also possible you're blending Nick's yaml and mine, which use different variable names.

> I'm confused why the URL's have changed and they seem to be different in your example to Nicks, are you only viewing clips on your LAN and not outside?

I use a vpn for remote access, so it works for me. Again, I can't stress enough how what I've provided is **not** a template or blueprint. It's simply what I've come up with that works for my use case and may need to be altered for yours. You may need to spend some time going through the frigate docs and home assistant companion docs to get everything working correctly.

> I use Nabu Casa so doesn't this url need to be before `/api`?

I don't believe videos for the new review items are available through the frigate integration, which is why I'm referencing my frigate instance in the url for the video. This navigates me to frigate to watch the video matching the alert. If you don't care about viewing videos using the new review system and simply want it attached to your notification, then you can change that back to how it was for 0.13 and it will work fine (`/api/frigate/notifications/{{ trigger_event }}/clip.mp4`).

I would argue, however, that this defeats some of the improvements that were made to frigate. Specifically, frigate is now designed to provide one comprehensive video for all objects detected during the same timeframe. Using the api to access the clip for an event does not guarantee you will see everything of interest or relevance.

I'm not sure how you have everything setup, but Nabu Casa is only remote access for home assistant. I have frigate in docker outside of home assistant, so remote access with Nabu Casa would not allow me to access frigate outside of my LAN (aside from what's available via the frigate integration). If you don't have any way of externally accessing frigate (which you should absolutely be using frigate's own ui in 0.14), I would recommend working on that in addition to ironing out notifications. Being notified is great, but it doesn't give you any opportunity to review any additional activity before/after, save the video for later review or for law enforcement, or even the ability to review the video a second time.

**Reply by NickM-27** [reply]
Depends what android you have, Samsung for example hasn't implemented the feature for some reason.

**Reply by Morphy99** [reply]
> This line isn't anywhere in my yaml, so I can't speak to whether you need it or not, but the clip has nothing to do with Android vs iOS.

The `url: ` is an iOS specific option

> The urls for snapshots haven't changed at all from 0.13 to 0.14, so you may have some other networking error going on there. It's also possible you're blending Nick's yaml and mine, which use different variable names.

I've used your variables, but I was using `{{ id }}` instead of '{{ trigger_event }}'. Working now with:
`https://nabu-url.ui.nabu.casa/api/frigate/notifications/{{ trigger_event }}/clip.mp4`

> I don't believe videos for the new review items are available through the frigate integration, which is why I'm referencing my frigate instance in the url for the video. This navigates me to frigate to watch the video matching the alert. If you don't care about viewing videos using the new review system and simply want it attached to your notification, then you can change that back to how it was for 0.13 and it will work fine (`/api/frigate/notifications/{{ trigger_event }}/clip.mp4`).
> 
> I would argue, however, that this defeats some of the improvements that were made to frigate. Specifically, frigate is now designed to provide one comprehensive video for all objects detected during the same timeframe. Using the api to access the clip for an event does not guarantee you will see everything of interest or relevance.

That's a good point. I can't use the internal URL as I'm not connected via a VPN though. I've tried ` uri: /ccab4aaf_frigate-fa/ingress/review?id={{ id }}` however it doesn't take me to the actual review event, just the main Frigate page. Does yours take you to the actual review?

> I'm not sure how you have everything setup, but Nabu Casa is only remote access for home assistant. I have frigate in docker outside of home assistant, so remote access with Nabu Casa would not allow me to access frigate outside of my LAN (aside from what's available via the frigate integration). If you don't have any way of externally accessing frigate (which you should absolutely be using frigate's own ui in 0.14), I would recommend working on that in addition to ironing out notifications. Being notified is great, but it doesn't give you any opportunity to review any additional activity before/after, save the video for later review or for law enforcement, or even the ability to review the video a second time.

That's incorrect. With HA OS and ingress, the full Frigate interface is available outside the LAN.

**Reply by Morphy99** [reply]
> Depends what android you have, Samsung for example hasn't implemented the feature for some reason.

According to the companion docs Android 14+ is required, mines on 13 so won't work. 

In the Frigate docs, the code example for Android HA notifications isn't the recommended frigate/reviews topic, should this be updated?

**Reply by ofcedwards** [reply]
> That's a good point. I can't use the internal URL as I'm not connected via a VPN though. I've tried ` uri: /ccab4aaf_frigate-fa/ingress/review?id={{ id }}` however it doesn't take me to the actual review event, just the main Frigate page. Does yours take you to the actual review?

I have frigate in docker outside of home assistant, so I'm not sure how to make the url work for home assistant add on. I am directed to the actual review item as if I'd clicked on it in frigate.

> That's incorrect. With HA OS and ingress, the full Frigate interface is available outside the LAN. 

You're right - I wasn't thinking about using frigate as a home assistant add on, since I do not. I run frigate in docker completely separate from home assistant.

**Reply by Morphy99** [reply]
> Personally, I would achieve this with a template condition. The easiest way to do it would be have each input boolean match the name of the camera in frigate (so if frigate config has `front_door` as camera name, you create a bool called `input_boolean.front_door`). You'll place that in the `condition` section that I have as an empty list in my automation. That would look something like this:
> 
> ```
> condition:
>   - condition: template
>     value_template: "{{ false if states('input_boolean.' + after['camera']) == 'off' else true }}"
> ```
> 
> This will dynamically change the name of the input boolean to `input_boolean.CAMERA_NAME` to match which frigate camera the alert is coming from. The condition fails if the input boolean is switched off and will not fire the automation. In all other cases (boolean is on or there is no matching boolean), the condition passes and the automation fires.

Thanks for this. Although this will work with stopping it from running, I had an action to mute from the notification itself, this example being the front camera:
```
            - action: "MUTE_FRONT"
              title: Mute
```
Then at the end of the automation:
```
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "MUTE_FRONT"
      timeout: "00:05:00"
      continue_on_timeout: false
```
