### DISCUSSION TITLE
[Question]: Review screen

### DISCUSSION THREAD

**Discussion by xavan83** [blakeblackshear/frigate#11579] [Ask A Question]
### What is your question:

First of all, great thank you for your work (starting with the 0.13 version and now testing the 0.14 beta).
I look at the beta documentation of the new review screen and I don't find a way to understand why some people crossing the street in front of the camera are not detected. 
I only record on event however I can see people in low resolution when the timeline is displaying at fast speed (8x). I imagine you keep some snapshots in memory to display that.
I imagine it is a good idea to switch the recording to continuous to debug that?
After that can I replay the footage with the motion/detection boxes to understand why the people are not detected? May be cross the footage with skipped frames statistics to know if the server was not under to much load at that point?

**Comment by NickM-27** [comment]
You need to include your config otherwise there's no way to help.

**Comment by xavan83** [comment]
```yaml
motion:
  mqtt_off_delay: 30 
birdseye:
  enabled: true
  mode: continuous
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
database:
  path: /db/frigate.db
mqtt:
  enabled: true
  host: 192.168.0.16
  port: 1884
  topic_prefix: frigate
  client_id: frigate
logger:
  default: info
  logs:
    frigate.comms.dispatcher: error
    #frigate.object_detection: debug
    #frigate.record.maintainer: debug
detectors:
  coral1:
    type: edgetpu
    device: pci:1
  coral2:
    type: edgetpu
    device: pci:0
model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

snapshots:
  enabled: true
  clean_copy: true
  bounding_box: false
  crop: false
  retain:
    default: 10
    objects:
      person: 30
go2rtc:
  streams:
    sonnette:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.70:554/Streaming/Channels/101#timeout=20
      - ffmpeg:sonnette#audio=aac#timeout=20#input=-avoid_negative_ts make_zero -fflags
        +genpts+discardcorrupt -stimeout "5000000" -use_wallclock_as_timestamps "1"
cameras:
  sonnette:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/sonnette?video=copy&audio=aac
          roles:
            - detect,record
    detect:
      fps: 5
      enabled: true
      width: 1280
      height: 720
    motion:
      mask: 0.491,0.658,0.993,0.589,1,0,0,0,0,0.629
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      quality: 100
      required_zones: []
    zones:
      streetpeople:
        objects:
          - person
        inertia: 90
        coordinates: 0,720,1280,720,1280,434,0,451
      streetcar:
        objects:
          - car
        inertia: 60
        coordinates: 0,720,1280,720,1280,434,0,451
      boiteauxlettres:
        objects:
          - person
          - face
        coordinates: 1280,712,1280,720,0,720,0,712
    objects:
      filters:
        person:
          min_area: 25000
          max_ratio: 1.0
          mask:
            - 638,463,1280,422,1280,0,0,0,0,458
        car:
          min_score: 0.5
          #min_area: 100000
          mask:
            - 638,463,1280,422,1280,0,0,0,0,458
        cat:
          mask:
            - 638,463,1280,422,1280,0,0,0,0,458
        dog:
          mask:
            - 638,463,1280,422,1280,0,0,0,0,458
      track:
        - face
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
        - horse
objects:
  filters:
    person:
      min_score: 0.70
    car:
      min_score: 0.70
    dog:
      min_area: 10000
    cat:
      min_area: 10000
  track:
    - person
    - licence_plate
record:
  enabled: true
  events:
    pre_capture: 15
    post_capture: 15
    objects:
      - person
      - bicycle
      - car
      - motorcycle
      - bus
      - train
      - cat
      - dog
      - horse
    retain:
      default: 30
      mode: motion
```
