### DISCUSSION TITLE
[Config Support]: go2rtc re-stream config with backchanel support is missing audio

### DISCUSSION THREAD

**Discussion by a2nt** [blakeblackshear/frigate#11574] [Config Support] [answered]
### Describe the problem you are having

It isn't clear how to setup go2rtc re-stream with audio and back-channel

To re-produce the issue I'm running `docker exec -it *container_id* bash`
And then inside the container I'm running `ffprobe rtsp://127.0.0.1:8554/camera_0`

Following config will work ok, the audio/video and back-channel are present:
```
  streams:
    camera_0:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      - "ffmpeg:camera_0#video=h264/rk"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      - "ffmpeg:camera_0#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567/audioback?backchannel=1
```

Audio is missing:
```
go2rtc:
  streams:
    camera_0:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      - "ffmpeg:camera_0#video=h264/rk#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567/audioback?backchannel=1
```

Audio is missing:
```
go2rtc:
  streams:
    camera_0:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:553
      - "ffmpeg:camera_0#video=h264/rk#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567/audioback?backchannel=1
```

### Version

0.14.0-dev

### Frigate config file

```yaml
auth:
  mode: native
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.17.0.0/16
    - 172.18.0.0/16 # <---- this is the subnet for the internal docker compose networ
    - 172.19.0.0/16
#detectors:
#  armnn:
#    type: rknn
#    core_mask: 0b111 # 0b111 3 cores

#model:
  # name of yolov8 model or path to your own .rknn model file
  # possible values are:
  # - default-yolov8n
  # - default-yolov8s
  # - default-yolov8m
  # - default-yolov8l
  # - default-yolov8x
  # - /config/model_cache/rknn/your_custom_model.rknn
  #path: /models/rknn/default-yolov8m-rk3588.rknn
  #path: /config/model_cache/rknn/yolov8m-320x320-rk3588.rknn # default-yolov8m
#  width: 320
#  height: 320
#  input_pixel_format: bgr
#  input_tensor: nhwc

detectors: # required
  rknn: # required
    type: rknn # required
    # number of NPU cores to use
    # 0 means choose automatically
    # increase for better performance if you have a multicore NPU e.g. set to 3 on rk3588
    num_cores: 3

model: # required
  # name of model (will be automatically downloaded) or path to your own .rknn model file
  # possible values are:
  # - deci-fp16-yolonas_s
  # - deci-fp16-yolonas_m
  # - deci-fp16-yolonas_l
  # - /config/model_cache/your_custom_model.rknn
  path: deci-fp16-yolonas_s
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolo models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

ffmpeg:
  hwaccel_args: preset-rk-h264 # or preset-rk-h265
  output_args:
    record: preset-record-generic-audio-aac # preset-record-generic-audio-copy 
     #detect: -f rawvideo
     #rtmp: -c copy -f flv -flvflags no_duration_filesize

ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
  timezone: Etc/GMT-2
  time_format: 24hour
  date_style: full
  time_style: medium
  strftime_fmt: '%a, %H:%M (%d.%m.%Y)'

# Re-stream
#- ffmpeg:camera_0
##video=h264/rk
##audio=aac 
# rtsp:// :554
# dvrip:// :34567
go2rtc:
  streams:
    camera_0:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      - "ffmpeg:camera_0#video=h264/rk"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      - "ffmpeg:camera_0#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567/audioback?backchannel=1
    camera_1:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.11:34567
      - "ffmpeg:camera_1#video=h264/rk"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.11:34567
      - "ffmpeg:camera_1#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.11:34567/audioback?backchannel=1
    camera_2:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.12:34567
      - "ffmpeg:camera_2#video=h264/rk"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.12:34567
      - "ffmpeg:camera_2#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.12:34567/audioback?backchannel=1
    camera_3:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.13:34567
      - "ffmpeg:camera_3#video=h264/rk"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.13:34567
      - "ffmpeg:camera_3#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.13:34567/audioback?backchannel=1
    camera_4:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.14:34567
      - "ffmpeg:camera_4#video=h264/rk"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.14:34567
      - "ffmpeg:camera_4#audio=aac"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.14:34567/audioback?backchannel=1
    webrtc:
      candidates:
        - stun:8555
mqtt:
  host: 192.168.88.2 # Docker Host
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

birdseye:
  enabled: true
  mode: continuous
  quality: 1
  width: 2880
  height: 1616

#audio:
#  enabled: true
#  listen:
#    - scream
#    - speech
#    - yell

database:
  path: /media/frigate/frigate.db

objects:
  track:
    - person
    - car

motion:
  threshold: 30
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mqtt_off_delay: 30

record:
  enabled: true
  retain:
    days: 2
    mode: motion

  events:
    #max_seconds: 300
    pre_capture: 10 # sec
    post_capture: 60 # sec
    objects:
      - person
      - car

    retain:
      default: 7
      mode: active_objects
      objects:
        person: 10
        car: 3

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 1080
  retain:
    default: 15
    objects:
      person: 15
      car: 3
#rtmp:
#  enabled: false

live:
  height: 1080
  quality: 1

timestamp_style:
  position: br
  format: '%d.%m.%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid

detect:
  enabled: true
  fps: 10
  max_disappeared: 250
  stationary:
    interval: 5000
    threshold: 500
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    #max_frames:
    #  default: 3000 # 3000 frames / 5 fps = 10 mins

logger:
  default: info
  logs:
    frigate.mqtt: error
#    frigate.record.maintainer: debug

cameras:
  camera_0:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_0
          roles:
            - record
            - detect
            - audio
    detect:
      width: 2880
      height: 1616
    zones:
      inner_entrance-0:
        coordinates: 0,1616,2880,1616,2880,1301,2369,755,0,1044
      outside_entrance_road-0:
        coordinates: 
          0.905,0.51,1,0.603,1,0.4,0.96,0.356,0.936,0.357,0.829,0.39,0.808,0.412,0.829,0.433,0.851,0.467
        inertia: 3
      outside_entrance_house1-0:
        coordinates: 
          695,685,1611,501,1620,568,2028,517,2114,561,2132,556,2213,598,2245,612,2273,609,2328,623,2479,695,1559,824,713,925
      outside_entrance_house2-0:
        coordinates: 2658,653,2522,589,2319,494,2333,429,2880,408,2880,646
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

    review:
      detections:
        required_zones: outside_entrance_road-0
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1
          roles:
            - record
            - detect
            - audio
    detect:
      width: 2880
      height: 1616
    zones:
      inner_garden-1:
        coordinates: 2880,813,1807,275,1696,242,0,260,0,1616,2880,1616
      uyutni_pereulok_all-1:
        coordinates: 65,0,67,209,1177,185,1781,218,2880,697,2880,0
      uyutni_pereulok_road-1:
        coordinates: 129,256,1823,224,1849,196,1246,49,983,0,874,0,1136,104,125,192
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

  camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      width: 2880
      height: 1616
    zones:
      gate_inner-2:
        coordinates: 413,693,460,0,0,0,0,1616,455,1616
      gate_outer_near-2:
        coordinates: 
          0.446,1,0.636,1,0.578,0.82,0.525,0.639,0.386,0.252,0.342,0.119,0.141,0,0.14,0.313,0.149,1
        inertia: 3
      gate_outer_road-2:
        coordinates: 2880,1616,2880,743,2146,0,517,0,515,86,907,256,1821,1616
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

    review:
      alerts:
        required_zones: gate_outer_near-2
      detections:
        required_zones: gate_outer_near-2
  camera_3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3
          roles:
            - record
            - detect
            - audio
    detect:
      width: 2880
      height: 1616
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100
    zones:
      spokoinaya_road-3:
        coordinates: 
          0,0.111,0.41,0.09,0.812,0.23,0.762,0.142,0.767,0.119,0.822,0.197,0.884,0.269,0.953,0.4,0.943,0.436,0.151,0.721,0,0.721
        inertia: 3
      inner-3:
        coordinates: 2880,895,2880,1616,2245,1616,2687,1157
      outside_garden-3:
        coordinates: 0,1,0.781,1,0.924,0.745,1,0.548,0.927,0.448,0.635,0.573,0,0.743
        inertia: 3
    motion: {}
    review:
      detections:
        required_zones:
          - spokoinaya_road-3
          - outside_garden-3
      alerts:
        required_zones: outside_garden-3
  camera_4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_4
          roles:
            - record
            - detect
            - audio
    detect:
      width: 2880
      height: 1616
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

camera_groups:
  Outside:
    order: 0
    icon: LuCar
    cameras:
      - camera_2
      - camera_3
  Inner:
    order: 1
    icon: LuPalmtree
    cameras:
      - camera_0
      - camera_1
version: 0.14
```

### Relevant log output

```shell
No relevant logs
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Dev Board
