### DISCUSSION TITLE
[Config Support]: Reolink 1224A livestream issue.

### DISCUSSION THREAD

**Discussion by fraschm1998** [blakeblackshear/frigate#11576] [Config Support] [answered]
### Describe the problem you are having

Live stream is set up for Rio Link 1224A cameras, but I'm still unable to see the live stream in the web UI interface. I also tried to downgrade to version 0.13 whether or not it was an issue with the beta, and it still doesn't work. 

I'm using a Coral AI, mPCIE TPU, as well as an NVIDIA GT710 gpu.

I could see the live stream if I connect using VLC. 

Frigate screenshot of interface:

![Screenshot_2024-05-28-00-07-45_5129](https://github.com/blakeblackshear/frigate/assets/54919428/24817a2b-67c0-4e4b-93c5-2bd96b409151)

Reolink Camera setting:
![image](https://github.com/blakeblackshear/frigate/assets/54919428/d7c4a388-e43a-4b1f-831a-bc39f124d230)

![image](https://github.com/blakeblackshear/frigate/assets/54919428/05b24438-87e6-40b2-ae5c-108cff8925d4)

### Version

0.14 beta

### Frigate config file

```yaml
mqtt:
  host: 192.168.30.39
  port: 1883
  topic_prefix: frigate
  user: mqtt
  password: sdasdsdasd

detectors:
  #cpu1:
  #  type: cpu
  #  num_threads: 1
  #cpu2:
  #  type: cpu
  #  num_threads: 1
  coral0:
    type: edgetpu
    device: pci

# Optional: ffmpeg configuration
ffmpeg:
  global_args: -hide_banner -loglevel warning
    #hwaccel_args: preset-nvidia-h264
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 10000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy -an
    #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

birdseye:
  enabled: true
  restream: true
  width: 1920
  height: 1080
  quality: 5
  #ffmpeg:
  #  input_args: preset-rtsp-udp
  mode: objects

go2rtc:
  streams:
    ### REOLINK CAMERAS ###
    backyard_cam:
      #- rtsp://admin:password@192.168.70.5:554/h264Preview_01_main
      - rtsp://admin:password@192.168.70.5/Preview_01_main
      - "ffmpeg:backyard_cam#audio=opus"
    backyard_cam_sub:
      - rtsp://admin:password@192.168.70.5/Preview_01_sub
        #- rtsp://admin:password@192.168.70.5:554/h264Preview_01_sub
    garage_cam:
      - rtsp://admin:password@192.168.70.6:554/h264Preview_01_main
      #- rtsp://admin:password@192.168.70.6:554/Preview_01_main
      - "ffmpeg:garage_cam#audio=opus"
    garage_cam_sub:
      #- rtsp://admin:password@192.168.70.6:554/Preview_01_sub
      - rtsp://admin:password@192.168.70.6:554/h264Preview_01_sub

cameras:
  backyard_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_cam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
    detect:
      width: 2560
      height: 1440
    record:
      enabled: true
    snapshots:
      enabled: true

  garage_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_cam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
    detect:
      width: 2560
      height: 1440
    record:
      enabled: true
    snapshots:
      enabled: true
```

### Relevant log output

```shell
No error logs.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe
