### DISCUSSION TITLE
[Camera Support]: PTZ wrong direction

### DISCUSSION THREAD

**Discussion by gypais** [blakeblackshear/frigate#11578] [Camera Support]
### Describe the problem you are having

When I click on the bottom arrow, it goes down, but when I click on the right arrow, it goes left! I don't have any settings on the camera to change that... Is there a setting in frigate to change the direction in one direction? Not found in the docs.
THANKS.

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.5
  user: "jpp"
  password: "XX"

cameras:
  JPP_camera: 
    detect:
    # width: 1280
    # height: 720
      fps: 5
    enabled: true
    onvif:
      host: 192.168.1.196
      port: 8899
      user: admin
      password: admin
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.1.196/channel=1_stream=1.sdp
          roles:
            - detect
objects:
  track:
    - person
    - airplane
    - bird
    - cat
    - dog
  filters:
    person:
      threshold: 0.8
record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 10
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

pg x6 weq 2

**Comment by NickM-27** [comment]
Sounds like a bug in the cameras onvif implementation

**Reply by redelacruz** [reply]
It would be cool if there was a way to set this with something like a:
```
    onvif:
      host: 192.168.1.196
      port: 8899
      user: admin
      password: admin
      ptz:
         inverted_y_axis: true    # default: false
         inverted_x_axis: true    # default: false
         x_is_y_axis: true        # to realign the axes in perpendicular installations; default: false
```
