### DISCUSSION TITLE
[Support]: Upgraded to 0.14 from mature Frigate installation. No alerts, slow video, video not loading etc.

### DISCUSSION THREAD

**Discussion by superdong69** [blakeblackshear/frigate#11585] [General Support]
### Describe the problem you are having

Got a Frigate installation that I've been using for a few years now, frigate+, the complete setup. Everything was working perfectly, no issues. Upgraded to 0.14. Immediately, I stopped getting detection and there for alerts from Home Assistant.  Besides that, when I go to the frigate UI page, under Live, the cameras take forever to load, which is new. Going to home assistant, on the frigate card, they also take forever to load, whether in the app or web. I have a stationary car in the driveway, and in Live, it is outlined in red, with a picture of a car in the top left, but when I click the feed image I get "No preview found" and a spinning circle. All in all, I LOVE the changes, and I can see where you're all going with this, but it doesn't seem to be working. I'm not sure if its because its not a clean install, but there should be delays in the system, I'm running this on a heavy metal machine, CPU is constantly at 5%. I'm seeing  "No frames have been received, check error logs." where I never used to see this. I see it when I change tabs and go back to Frigate, I see it when I go to debug instead of live feeds, I see it in frigate card of home assistant, I see it everywhere, where I never saw it on latest 0.13. 
The only thing showing up in the logs is this which is a warning, but no idea what it means.

```
2024-05-28 08:33:31.405028726  [2024-05-28 08:33:31] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for garage_rear. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.410489039  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_back1. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.411018443  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_side. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.411604418  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_front. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.412239764  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for driveway. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.412934504  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for garage_rear. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:51.419160914  [2024-05-28 08:33:51] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_back1. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Version

0.14-beta1

### Frigate config file

```yaml
ui:
  live_mode: mse
model:
  path: plus://fd5a1f95e78984e07b66c51d339f566b
mqtt:
  host: 192.168.1.80
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigateuser
  password: password
  stats_interval: 300
record:
  expire_interval: 10
go2rtc:
  streams:
    driveway:
      - rtsp://user:pass@192.168.1.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    driveway_sub:
      - rtsp://user:pass@192.168.1.95:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    garage_rear:
      - rtsp://user:pass@192.168.1.94:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_rear_sub:
      - rtsp://user:pass@192.168.1.94:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    house_front:
      - rtsp://user:pass@192.168.1.93:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    house_front_sub:
      - rtsp://user:pass@192.168.1.93:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    house_side:
      - rtsp://user:pass@192.168.1.90:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    house_side_sub:
      - rtsp://user:pass@192.168.1.90:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    house_back1:
      - rtsp://user:pass@192.168.1.91:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    house_back1_sub:
      - rtsp://user:pass@192.168.1.91:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    garage_side:
      - rtsp://user:pass@192.168.1.92:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_side_sub:
      - rtsp://user:pass@192.168.1.92:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    doggo:
      - rtsp://user:pass@192.168.1.141:554/stream1
    front_doorbell:
      - rtsp://user:pass@192.168.1.50:554/h264Preview_01_main
    back_doorbell:
      - rtsp://user:pass@192.168.1.51:554/h264Preview_01_main
  webrtc:
    candidates:
      - 192.168.1.79:8555
      - stun:8555
timestamp_style:
  position: tr
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
objects:
  track:
    - face
    - person
    - dog
    - car
    - ups
    - fedex
    - amazon
    - package
  filters:
    face:
      min_score: 0.7
      threshold: 0.9
    dog:
      min_score: 0.7
      threshold: 0.9
    person:
      min_score: 0.7
      threshold: 0.9
    car:
      min_score: 0.6
      threshold: 0.85
    ups:
      min_score: 0.7
      threshold: 0.9
    fedex:
      min_score: 0.7
      threshold: 0.9
    amazon:
      min_score: 0.7
      threshold: 0.9
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_driveway
        - monitor_car_detect
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_driveway:
        coordinates: 
          0,504,101,428,239,357,333,310,442,259,536,201,571,162,644,99,693,88,747,75,800,69,930,53,1046,59,1160,59,1305,61,1381,68,1409,68,1431,96,1513,99,1582,109,1649,119,1700,128,1760,138,1833,164,1920,200,1920,1080,0,1080
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_car_detect:
        coordinates: 1088,172,748,201,810,138,829,99,957,89
        objects:
          - car
          - fedex
          - ups
          - amazon
    motion:
      mask:
        - 0,0,424,0,710,0,719,21,470,122,0,396
        - 1920,0,1920,163,1412,84,1414,0
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_driveway
          - monitor_car_detect
  house_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_front
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_house_front
        - monitor_car_detect
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_house_front:
        coordinates: 
          0,210,45,201,105,182,193,147,320,112,410,95,574,69,738,45,928,21,1038,21,1147,21,1239,65,1402,119,1582,187,1769,271,1920,354,1920,1080,0,1080
        objects:
          - face
          - car
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_car_detect:
        coordinates: 1229,70,649,117,465,156,376,94,546,71,695,45,885,21,1013,21
        objects:
          - face
          - car
          - fedex
          - ups
          - amazon
          - person
          - dog
    motion:
      mask:
        - 1853,40,1858,86,1440,87,1442,39
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_house_front
          - monitor_car_detect
  garage_rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage_rear
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - face
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_garage_rear
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_garage_rear:
        coordinates: 
          0,1080,1691,1080,1756,908,1920,826,1920,403,1899,367,1872,334,1788,264,1680,228,1642,224,1198,159,1140,108,1101,57,1082,26,1019,21,843,0,565,0,405,25,214,83,0,175
        objects:
          - face
          - person
          - dog
    motion:
      mask:
        - 0.894,0.855,1,0.725,1,1,0.843,1
        - 0.748,0.074,0.961,0.077,0.961,0.031,0.749,0.035
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_garage_rear
  house_side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_side
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_house_side
        - monitor_house_side_dog
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_house_side:
        coordinates: 
          269,886,377,808,317,671,222,550,165,470,96,504,64,415,29,297,40,258,124,210,175,190,246,162,404,117,473,97,569,75,642,61,706,49,787,38,873,31,945,25,1019,23,1087,24,1154,26,1216,29,1279,38,1347,49,1408,64,1485,90,1566,115,1631,138,1730,171,1920,226,1920,424,1920,1080,398,1080
        objects:
          - face
          - person
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_house_side_dog:
        coordinates: 
          21,279,57,266,86,251,113,238,156,216,199,195,241,177,360,147,424,124,478,107,539,87,561,76,587,77,622,65,650,65,709,55,772,49,832,42,882,38,939,32,1046,23,1127,24,1219,25,1310,33,1379,74,1195,99,1015,145,725,235,404,332,196,402,75,461
        objects:
          - dog
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
        - 0,0,761,0,1046,23,0,321
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_house_side_dog
          - monitor_house_side
  house_back1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_back1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_back1
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_house_back1
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_house_back1:
        coordinates: 
          1613,1080,1920,725,1920,509,1830,454,1881,319,1817,279,1726,231,1637,200,1549,165,1455,128,1332,88,1263,65,1142,40,1055,27,963,21,890,21,807,21,715,21,637,25,539,36,467,33,355,64,196,80,0,127,0,1080
        objects:
          - face
          - person
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
        - 0,0,453,0,470,122,0,396
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_house_back1
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 2560
      height: 1920
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_front_doorbell
        - monitor_doorstep
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_front_doorbell:
        coordinates: 
          203,1785,661,1501,756,1488,1167,1609,1550,1661,1591,1159,1365,1135,671,1048,499,1124,0,1252,0,1416
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_doorstep:
        coordinates: 
          312,1920,1509,1920,1553,1664,775,1517,672,1517,563,1566,431,1650,330,1707,273,1753,214,1788
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
          - package
    motion:
      mask:
        - 2560,89,2560,0,1796,0,1798,89
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_doorstep
          - monitor_front_doorbell
  back_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 2560
      height: 1920
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_back_doorbell
        - monitor_backdoorstep
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_back_doorbell:
        coordinates: 
          0,1920,788,1920,802,1623,1108,1603,1355,1566,1828,1474,1905,829,1782,845,1406,823,999,846,685,824,0,823,0,1416
        objects:
          - face
          - person
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_backdoorstep:
        coordinates: 
          2272,1920,2428,1750,1977,1488,1918,1488,1837,1482,1737,1488,1062,1599,1073,1723,1113,1920
        objects:
          - face
          - person
    motion:
      mask:
        - 2560,89,2560,0,1668,0,1669,84
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_backdoorstep
          - monitor_back_doorbell
  garage_side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage_side
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_garage_side
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_garage_side:
        coordinates: 
          1920,1080,1920,177,1733,97,1493,21,1028,0,705,23,501,32,361,95,87,151,0,195,0,1080
        objects:
          - face
          - person
          - dog
          - car
        stationary:
          duration: 60
          filter:
            car: {}
    motion:
      mask:
        - 1844,43,1843,94,1450,87,1446,45
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_garage_side
  dog:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dog
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
    record:
      enabled: true  # Enable recording
      retain:
        days: 2  # Retain recordings for 2 days

detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: continuous
live:
  height: 640
  quality: 1
```

### Relevant log output

```shell
2024-05-28 08:33:31.405028726  [2024-05-28 08:33:31] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for garage_rear. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.410489039  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_back1. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.411018443  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_side. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.411604418  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_front. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.412239764  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for driveway. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:41.412934504  [2024-05-28 08:33:41] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for garage_rear. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-05-28 08:33:51.419160914  [2024-05-28 08:33:51] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for house_back1. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### FFprobe output from your camera

```shell
ffprobe -rtsp_transport tcp rtsp://127.0.0.1:8554/driveway
ffprobe version 5.1.1-1ubuntu2.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.2.0-3ubuntu1)
  configuration: --prefix=/usr --extra-version=1ubuntu2.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/driveway':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 5 fps, 30 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2669EW-AI, and Reolink Wireless Doorbell

**Comment by NickM-27** [comment]
we will need to see a full copy of the logs

**Reply by superdong69** [reply]
Sure thing. How do I get you those in 0.14?

**Reply by NickM-27** [reply]
open the log page, scroll to the top, click copy logs, paste them here

**Reply by superdong69** [reply]
Ok, So in the log page, I've just got this.
![image](https://github.com/blakeblackshear/frigate/assets/119988539/a41a33b6-6bba-4971-8d62-0e34ddf32634)
The copy log I pasted was the frigate log, there is nothing in the go2rtc tab.

**Reply by NickM-27** [reply]
okay, easiest way to get all of the logs is to use `docker logs frigate` or whatever you called the container. Besides that maybe try restarting frigate and see if it continues

**Reply by superdong69** [reply]
Gotcha! Here it is!

[frigate_logs.txt](https://github.com/blakeblackshear/frigate/files/15470802/frigate_logs.txt)

I've restarted frigate a bunch of times now.

**Reply by NickM-27** [reply]
> Fatal Python error: Bus error

you need to increase the SHM size in the docker compose

**Reply by superdong69** [reply]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    environment:
      PLUS_API_KEY: "redacted"
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta1
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker-compose/frigate:/config
      - unraid_frigate_nfs:/media/frigate
      - /mnt/data/efficientdet_lite3_512_ptq_edgetpu.tflite:/models/efficientdet_lite3_512_ptq_edgetpu.tflite
      - /mnt/data/coco_labels.txt:/models/coco_labels.txt
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
```

What would be the appropriate value do you think?

**Reply by NickM-27** [reply]
try `1024mb`

**Reply by superdong69** [reply]
![image](https://github.com/blakeblackshear/frigate/assets/119988539/a79b0378-8702-4006-97fa-3a9411d3e611)

So after making that change and bringing docker back up, None of my video feeds are live. I click on a camera, and it just loads a black screen with the UI, camera feed never shows up, and in HA the frigate card doesn't show live video either. The streams are live in VLC obviously, but frigate is making a mess of the whole thing.

**Reply by NickM-27** [reply]
what browser are you using and on what OS?

also I would suggest not using your manual qsv args but instead using `preset-vaapi` for hwaccel_args as this will reduce CPU usage

**Reply by superdong69** [reply]
I was JUST removing that from a couple cameras to test.  And should I be using this setting with the google coral?

So it should read as:

```cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - preset-vaapi

**Reply by NickM-27** [reply]
no it should not have the `-` before it, and you could remove it from all of the cameras and just set it once at the top

```
model:
  path: plus://fd5a1f95e78984e07b66c51d339f566b
ffmpeg:
  hwaccel_args: preset-vaapi
```

**Reply by superdong69** [reply]
oh great. Should I be using though, with using the google coral?
It's a stand alone server running an i5 16GB of DDR5

**Reply by NickM-27** [reply]
yes, the coral and this are entirely unrelated. This is used for decoding the videos that come from the cameras

**Reply by superdong69** [reply]
Well the system is responding better, that's for sure. Any idea why the detection isn't working?

**Reply by NickM-27** [reply]
I think more information will be needed. So you see no alerts or detections? What happens if you go to the settings of page, debug tab and enable object boxes. Are objects detected there?

**Comment by superdong69** [comment]
This is all I get on settings >debug.

![image](https://github.com/blakeblackshear/frigate/assets/119988539/cc3af232-a8d2-4ec0-be6c-01fd02dba006)


I never get a camera feed on any camera.

**Reply by NickM-27** [reply]
okay, will need another logs dump then

**Reply by superdong69** [reply]
[frigate.log.txt](https://github.com/blakeblackshear/frigate/files/15471720/frigate.log.txt)

**Reply by NickM-27** [reply]
very weird, looks like it is still just running out of SHM. Let's try bumping it up to `2048mb` and see if that finally solves the issue

**Reply by superdong69** [reply]
That was it. So I've got 8 cameras. Does this routinely fill up? 
I've just checked it, and after upping to 2GB and restarting I have:
````root@68cac3abb00d:/opt/frigate# df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
shm             2.0G   53M  2.0G   3% /dev/shm
root@68cac3abb00d:/opt/frigate#

**Reply by superdong69** [reply]
Well. I THOUGHT it was. Now when I click a camera from the Live page, I just get a blank screen. On the live screen, some cameras are live, others aren't. It DID detect me and created an event though. So that's good.

**Reply by NickM-27** [reply]
what browser are you using?

**Reply by superdong69** [reply]
Brave.

**Reply by NickM-27** [reply]
okay, if any of your cameras are h265 that could be part of the issue.

**Reply by superdong69** [reply]
Pretty sure they all are these days.

**Reply by superdong69** [reply]
I take that back. The amcrest are all configured for H264. And the reolinks as well.

**Reply by NickM-27** [reply]
okay, then you will want to update your config to have 

```
cameras:
  driveway:
    ... # (all of the existing config)
    live:
      stream_name: driveway_sub
```

that way the sub stream is used for the live views in the UI. This should make things work better
