### DISCUSSION TITLE
[Support]: 0.14.0 Beta 1 - Live View using snapshot wrong format

### DISCUSSION THREAD

**Discussion by jtut1731** [blakeblackshear/frigate#11594] [General Support]
### Describe the problem you are having

Two cameras (happen to be Amcrest AD410...with wide angle correction enabled) display strange behavior when camera view switches from live to snapshot. Top picture is live view. Bottom is snapshot. Aspect ratio of snapshot is also incorrect. Stream is 2560x1920.

![Screenshot 2024-05-28 at 1 35 59 PM](https://github.com/blakeblackshear/frigate/assets/10236530/46cc351a-7e90-4c52-9ecb-0dce259cbdb2)

![Screenshot 2024-05-28 at 1 37 02 PM](https://github.com/blakeblackshear/frigate/assets/10236530/c25c41a1-9e73-4002-ad08-21115453d630)

### Version

0.14.0-b97e274

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-rk-h264

go2rtc:
  streams:
    front_doorbell:
      - rtsp://xxx:xxx@xx.xx.xx.xx/cam/realmonitor?channel=1&subtype=0   # h264 2560x1920 / 15 fps
    front_doorbell_detect:
      - rtsp://xxx:xxx@xx.xx.xx.xx/cam/realmonitor?channel=1&subtype=1   # h264 720x576 / 5 fps

cameras:
  front_doorbell: # <------ Name the camera
    detect:
      height: 576
      width: 720
    motion:
      mask:
        - 720,0,720,29,488,25,488,0
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell_detect 
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
```

### Relevant log output

```shell
No relevant logs
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/front_doorbell':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp

Input #0, rtsp, from 'rtsp://127.0.0.1:8554/front_doorbell_detect':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.200000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 720x576, 5 fps, 5 tbr, 90k tbn
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux: Joshua-Riek/ubuntu-rockchip

### Install method

Docker Compose

### Coral version

Other: Rockchip rk3588

### Network connection

Wired

### Camera make and model

Amcrest AD410
