### DISCUSSION TITLE
Frigate behing Nginx Proxy Manager - no live video

### DISCUSSION THREAD

**Discussion by obermotz** [blakeblackshear/frigate#11595] [Config Support] [answered]
### Describe the problem you are having

Put Frigate behind NGP + Authelia - can't get live / realtime video from the cameras this way. Tested with and without Authelia, it does not seem to affect the problem. Accessing Frigate locally (such as http://192.168.2.xx:5000) works perfectly, no issues with the live camera feeds.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: mqtt
  user: yyy
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db
record:
  enabled: true
  retain:
    days: 5
birdseye:
  enabled: True
  mode: continuous
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-vaapi
environment_vars:
  LIBVA_DRIVER_NAME: i965

objects:
  track:
    - person
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.6

cameras:
  Garazs2Utca:
    enabled: True
    ffmpeg:
      inputs:
        - path: http://192.168.2.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx
          input_args: preset-http-reolink
          roles:
            - record
        - path: http://192.168.2.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx
          input_args: preset-http-reolink
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 4
    snapshots:
      enabled: true
    mqtt:
      enabled: true
    motion:
      mask:
        - 357,41,640,40,640,0,350,0
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7

  Garazs2Hatsokert:
    enabled: True
    ffmpeg:
      inputs:
        - path: http://192.168.2.53/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx
          input_args: preset-http-reolink
          roles:
            - record
        - path: http://192.168.2.53/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx
          input_args: preset-http-reolink
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 4
    snapshots:
      enabled: true
    mqtt:
      enabled: true
    motion:
      mask:
        - 357,41,640,40,640,0,350,0
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7

  Utca:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.2.55:554/stream1
          roles:
            - record
        - path: rtsp://admin:xxx@192.168.2.55:554/stream0
          roles:
            - detect
    detect:
      enabled: true
      width: 800
      height: 448
      fps: 5
    snapshots:
      enabled: true
      required_zones:
        - Utca_kapu_elott
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 10
        pre_capture: 5
        post_capture: 8
        required_zones:
          - Utca_kapu_elott
    mqtt:
      enabled: true
      required_zones:
        - Utca_kapu_elott
    zones:
      Utca_kapu_elott:
        coordinates: 233,87,351,75,411,137,459,245,456,349,398,444,150,448,138,208
        objects:
          - person
          - dog
          - cat
    motion:
      mask:
       - 800,28,800,0,620,0,624,30
    objects:
      filters:
        dog:
          mask:
            - 0,0,4,77,0,205,0,448,98,448,126,151,181,0,86,4
        person:
          mask:
            - 77,227,110,408,178,414,177,239,200,167,101,165
```

### Relevant log output

```shell
2024-05-28 19:41:30.078411048  192.168.2.30 - - [28/May/2024:19:41:30 +0200] "GET /api/config HTTP/1.1" 200 19028 "http://192.168.2.233:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0" "-"
2024-05-28 19:41:31.066116799  Traceback (most recent call last):
2024-05-28 19:41:31.066120618    File "/usr/lib/python3.9/wsgiref/handlers.py", line 137, in run
2024-05-28 19:41:31.066122204      self.result = application(self.environ, self.start_response)
2024-05-28 19:41:31.066123762    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgiutils.py", line 101, in __call__
2024-05-28 19:41:31.066125119      raise HandshakeError('Header %s is not defined' % key)
2024-05-28 19:41:31.066162896  ws4py.exc.HandshakeError: Header HTTP_UPGRADE is not defined
2024-05-28 19:41:31.066563874  172.19.0.1 - - [28/May/2024:19:41:31 +0200] "GET /live/jsmpeg/birdseye HTTP/1.1" 500 70 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0" "192.168.2.30"
```

### Frigate stats

```json
{
   "cameras":{
      "Garazs2Hatsokert":{
         "audio_dBFS":0.0,
         "audio_rms":0.0,
         "camera_fps":4.0,
         "capture_pid":338,
         "detection_enabled":1,
         "detection_fps":0.0,
         "ffmpeg_pid":348,
         "pid":321,
         "process_fps":4.0,
         "skipped_fps":0.0
      },
      "Garazs2Utca":{
         "audio_dBFS":0.0,
         "audio_rms":0.0,
         "camera_fps":4.0,
         "capture_pid":334,
         "detection_enabled":1,
         "detection_fps":0.0,
         "ffmpeg_pid":339,
         "pid":319,
         "process_fps":4.0,
         "skipped_fps":0.0
      },
      "Utca":{
         "audio_dBFS":0.0,
         "audio_rms":0.0,
         "camera_fps":5.0,
         "capture_pid":342,
         "detection_enabled":1,
         "detection_fps":5.4,
         "ffmpeg_pid":351,
         "pid":323,
         "process_fps":5.1,
         "skipped_fps":0.0
      }
   },
   "cpu_usages":{
      "1":{
         "cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "15":{
         "cmdline":"s6-supervise s6-linux-init-shutdownd",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "16":{
         "cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "24":{
         "cmdline":"s6-supervise go2rtc-healthcheck",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "25":{
         "cmdline":"s6-supervise go2rtc",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "26":{
         "cmdline":"s6-supervise s6rc-fdholder",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "27":{
         "cmdline":"s6-supervise nginx-log",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "28":{
         "cmdline":"s6-supervise frigate",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "29":{
         "cmdline":"s6-supervise nginx",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "30":{
         "cmdline":"s6-supervise go2rtc-log",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "31":{
         "cmdline":"s6-supervise s6rc-oneshot-runner",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "32":{
         "cmdline":"s6-supervise frigate-log",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "41":{
         "cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "42":{
         "cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "79":{
         "cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "81":{
         "cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "82":{
         "cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "89":{
         "cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "107":{
         "cmdline":"bash ./run.user go2rtc-healthcheck",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "110":{
         "cmdline":"python3 -u -m frigate",
         "cpu":"1.3",
         "cpu_average":"1",
         "mem":"2.7"
      },
      "119":{
         "cmdline":"nginx: master process nginx",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "145":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "146":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "147":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "148":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "149":{
         "cmdline":"nginx: cache manager process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "295":{
         "cmdline":"frigate.logger       ",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"1.0"
      },
      "297":{
         "cmdline":"frigate.recording_manager",
         "cpu":"2.6",
         "cpu_average":"2",
         "mem":"1.2"
      },
      "306":{
         "cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)",
         "cpu":"0.2",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "309":{
         "cmdline":"frigate.output       ",
         "cpu":"0.6",
         "cpu_average":"0",
         "mem":"1.2"
      },
      "312":{
         "cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "313":{
         "cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "318":{
         "cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x448 -i pipe: -f mpegts -s 1285x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "319":{
         "cmdline":"frigate.process:Garazs2Utca",
         "cpu":"0.8",
         "cpu_average":"1",
         "mem":"1.3"
      },
      "320":{
         "cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "321":{
         "cmdline":"frigate.process:Garazs2Hatsokert",
         "cpu":"0.8",
         "cpu_average":"1",
         "mem":"1.3"
      },
      "323":{
         "cmdline":"frigate.process:Utca ",
         "cpu":"3.3",
         "cpu_average":"4",
         "mem":"1.3"
      },
      "334":{
         "cmdline":"frigate.capture:Garazs2Utca",
         "cpu":"0.5",
         "cpu_average":"0",
         "mem":"1.2"
      },
      "338":{
         "cmdline":"frigate.capture:Garazs2Hatsokert",
         "cpu":"0.5",
         "cpu_average":"0",
         "mem":"1.2"
      },
      "339":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.2.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 4 -vf fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
         "cpu":"1.4",
         "cpu_average":"1",
         "mem":"0.5"
      },
      "342":{
         "cmdline":"frigate.capture:Utca ",
         "cpu":"0.6",
         "cpu_average":"0",
         "mem":"1.2"
      },
      "348":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.2.53/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 4 -vf fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
         "cpu":"1.4",
         "cpu_average":"1",
         "mem":"0.5"
      },
      "349":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.2.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garazs2Utca@%Y%m%d%H%M%S%z.mp4",
         "cpu":"0.4",
         "cpu_average":"0",
         "mem":"0.4"
      },
      "351":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.55:554/stream0 -r 5 -vf fps=5,scale_vaapi=w=800:h=448:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
         "cpu":"1.1",
         "cpu_average":"1",
         "mem":"0.5"
      },
      "353":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.2.53/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garazs2Hatsokert@%Y%m%d%H%M%S%z.mp4",
         "cpu":"0.5",
         "cpu_average":"0",
         "mem":"0.4"
      },
      "356":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.55:554/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Utca@%Y%m%d%H%M%S%z.mp4",
         "cpu":"0.9",
         "cpu_average":"0",
         "mem":"0.3"
      },
      "6979":{
         "cmdline":"frigate.detector.coral",
         "cpu":"13.0",
         "cpu_average":"7",
         "mem":"2.3"
      },
      "8151":{
         "cmdline":"sleep 30s",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      }
   },
   "detection_fps":5.4,
   "detectors":{
      "coral":{
         "detection_start":0.0,
         "inference_speed":22.58,
         "pid":6979
      }
   },
   "gpu_usages":{
      "intel-vaapi":{
         "gpu":"2.5%",
         "mem":"-%"
      }
   },
   "processes":{
      "go2rtc":{
         "pid":89
      },
      "logger":{
         "pid":295
      },
      "recording":{
         "pid":297
      }
   },
   "service":{
      "last_updated":1716918204,
      "latest_version":"0.13.2",
      "storage":{
         "/dev/shm":{
            "free":445.3,
            "mount_type":"tmpfs",
            "total":450.0,
            "used":4.7
         },
         "/media/frigate/clips":{
            "free":1791387.4,
            "mount_type":"cifs",
            "total":3754443.8,
            "used":1963056.4
         },
         "/media/frigate/recordings":{
            "free":1791387.4,
            "mount_type":"cifs",
            "total":3754443.8,
            "used":1963056.4
         },
         "/tmp/cache":{
            "free":949.4,
            "mount_type":"tmpfs",
            "total":953.7,
            "used":4.3
         }
      },
      "temperatures":{
         
      },
      "uptime":3210,
      "version":"0.13.2-6476f8a"
   }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Frigate is running in a Docker container in a Debain 12 VM running on Proxmox 8.2.2. NPM settings for the Frigate host look like this:

![image](https://github.com/blakeblackshear/frigate/assets/22054677/17f41a47-1246-4342-bca4-5915c4db8d1c)

![image](https://github.com/blakeblackshear/frigate/assets/22054677/eb9e742a-5846-4d2c-ab07-3750d8e621ef)
