### DISCUSSION TITLE
[Config Support]: Error on update to 14 beta1

### DISCUSSION THREAD

**Discussion by h2rSys** [blakeblackshear/frigate#11603] [Config Support]
### Describe the problem you are having

Hi, when starting after update it crash with error on cookie_name option, but it is using default....
Error in log is this:
auth.cookie_name: String should match pattern '^[a-z]_*$'
Config option is this:
cookie_name: frigate_token

### Version

14 beta1

### Frigate config file

```yaml
auth:
  # Optional: Authentication mode (default: shown below)
  # Valid values are: native, proxy
  mode: native
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: False
  # Optional: Cookie to store the JWT token for native auth (default: shown below)
  cookie_name: frigate_token
  # Optional: Set secure flag on cookie. (default: shown below)
  # NOTE: This should be set to True if you are using TLS
  cookie_secure: False
  # Optional: Session length in seconds (default: shown below)
  session_length: 86400 # 24 hours
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Mapping for headers from upstream proxies. Only used in proxy auth mode.
  # NOTE: Many authentication proxies pass a header downstream with the authenticated
  #       user name. Not all values are supported. It must be a whitelisted header.
  #       See the docs for more info.
  header_map:
    user: x-forwarded-user
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  failed_login_rate_limit: None
  # Optional: Trusted proxies for determining IP address to rate limit
  # NOTE: This is only used for rate limiting login attempts and does not bypass
  # authentication in any way
  trusted_proxies: []
  # Optional: Url for logging out a user. This only needs to be set if you are using
  # proxy mode.
  logout_url: /api/logout
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000
```

### Relevant log output

```shell
*************************************************************
frigate-lnx | 2024-05-28 16:13:48.858234961  *************************************************************
frigate-lnx | 2024-05-28 16:13:48.858244036  ***    Your config file is not valid!                     ***
frigate-lnx | 2024-05-28 16:13:48.858249892  ***    Please check the docs at                           ***
frigate-lnx | 2024-05-28 16:13:48.858253837  ***    https://docs.frigate.video/configuration/index     ***
frigate-lnx | 2024-05-28 16:13:48.858278342  *************************************************************
frigate-lnx | 2024-05-28 16:13:48.858282096  *************************************************************
frigate-lnx | 2024-05-28 16:13:48.858286889  ***    Config Validation Errors                           ***
frigate-lnx | 2024-05-28 16:13:48.858290677  *************************************************************
frigate-lnx | 2024-05-28 16:13:48.858320065  auth.cookie_name: String should match pattern '^[a-z]_*$'
frigate-lnx | 2024-05-28 16:13:48.858323502  *************************************************************
frigate-lnx | 2024-05-28 16:13:48.858326823  ***    End Config Validation Errors                       ***
frigate-lnx | 2024-05-28 16:13:48.858330117  *************************************************************
frigate-lnx | 2024-05-28 16:13:50.134919780  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate-lnx | s6-rc: info: service legacy-services: stopping
frigate-lnx | s6-rc: info: service legacy-services successfully stopped
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
