### DISCUSSION TITLE
[Config Support]: ENV Variables Not Being Read Correctly

### DISCUSSION THREAD

**Discussion by benblustey** [blakeblackshear/frigate#11626] [Config Support] [answered]
### Describe the problem you are having

I recently decided to start moving all of my secrets out of the main config file and into an .env file on unRaid. This file is located in the same directory as my config file. The .env file is mapped within the unRaid GUI extra parameters via `--env-file /mnt/cache/appdata/frigate/.env`. A generic user is set as `FRIGATE_USER`, which is set on all 7 cameras and 14 feeds without any compilation issues. The first camera, has no issues with both username and password being passed as a env variable. Once another camera is set with the password as a variable, I receive the following log issue for the next camera with usr/pw set as variables in the configuration file. This obviously keeps the go2rtc from starting up, blocking all cameras. I just went through and resolved the main/sub issues with my Reolink cameras, hence why my filters min/max are commented out. 

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: x.x.y.y
  port: 1883
  # user: mqtt
  # password: mqtt

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream 
  output_args:
    record: preset-record-generic-audio-copy

birdseye:
  enabled: true
  mode: continuous
  restream: True
  quality: 8

snapshots:
  enabled: true
  retain:
    default: 30
    objects:
      person: 15
      cat: 15
      dog: 15
  bounding_box: true
  crop: false

database:
  path: /media/frigate/frigate.db

record:
  enabled: true
  retain:
    days: 14
    mode: all

detect:
  width: 640
  height: 360

environment_vars:
  PLUS_API_KEY: xxxxxx

go2rtc:
  streams:
    doorbell_main:
      - rtsp://{FRIGATE_USER}:{FRIGATE_DOORBELL_PW}@x.x.x.x:554/h264Preview_01_main
      - "ffmpeg:doorbell_main#audio=opus"
    doorbell_sub:
      - rtsp://{FRIGATE_USER}:{FRIGATE_DOORBELL_PW}@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:doorbell_sub#audio=opus"

    front_yard_main:
      - rtsp://{FRIGATE_USER}:{FRIGATE_FRONT_YARD_PW}@x.x.x.x:554/h264Preview_01_main
      - "ffmpeg:front_yard_main#audio=opus"
    front_yard_sub:
      - rtsp://{FRIGATE_USER}:{FRIGATE_FRONT_YARD_PW}@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:front_yard_sub#audio=opus"

    front_porch_main:
      - rtsp://{FRIGATE_USER}:Swm0pAOoVARVuGlo@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:front_yard_sub#audio=opus"
    front_porch_sub:
      - rtsp://{FRIGATE_USER}:Swm0pAOoVARVuGlo@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:front_yard_sub#audio=opus"

    front_driveway_sub:
      - rtsp://{FRIGATE_USER}:GsJ3LG97Z9OuW8Ol@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:front_driveway_sub#audio=opus"
    front_driveway_main:
      - rtsp://{FRIGATE_USER}:GsJ3LG97Z9OuW8Ol@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:front_driveway_main#audio=opus"

    side_driveway_sub:
      - rtsp://{FRIGATE_USER}:v0SYvXgevuk7kP1I@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:side_driveway_sub#audio=opus"
    side_driveway_main:
      - rtsp://{FRIGATE_USER}:v0SYvXgevuk7kP1I@x.x.x.x:554/h264Preview_01_main
      - "ffmpeg:side_driveway_main#audio=opus"

    backyard_sub:
      - rtsp://{FRIGATE_USER}:iF95i7Y2zIOmSB2B@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:backyard_sub#audio=opus"
    backyard_main:
      - rtsp://{FRIGATE_USER}:iF95i7Y2zIOmSB2B@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:backyard_main#audio=opus"

    office_main:
      - rtsp://{FRIGATE_USER}:X5MSkXzAQcKwkpX@x.x.x.x:554/h264Preview_01_main
      - "ffmpeg:office_main#audio=opus"
    office_sub:
      - rtsp://{FRIGATE_USER}:X5MSkXzAQcKwkpX@x.x.x.x:554/h264Preview_01_sub
      - "ffmpeg:office_sub#audio=opus"

cameras:
  doorbell:
    ui:
      order: 1
    objects:
      track:
      - person
      filters:
        person:
          # min_area: 80000
          # max_area: 500000
          min_score: 0.6
          threshold: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/doorbell_main
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    zones:
      porch_walkway:
        coordinates: 0,1440,2560,1440,2560,1069,2286,1015,1762,1233,1262,1318,1249,1030,1194,927,789,940
    motion:
      mask:
        - 1127,257,1725,290,2290,383,2560,295,2560,581,2265,608,2265,738,740,664,679,310
        - 787,0,787,106,0,106,0,0

  front_porch:
    ui:
      order: 3
    objects:
      track:
      - person
      - cat
      - dog
      filters:
        person:
          # min_area: 350000
          # max_area: 800000
          min_score: 0.6
          threshold: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/front_porch_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/front_porch_main
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    zones:
      porch_zone:
        coordinates: 0,0,0,1440,1685,1440,1696,0
    motion:
      mask:
        - 1012,814,1570,1440,2560,1440,2560,0,1494,0,1449,194,1131,351
        - 787,0,787,106,0,106,0,0

  front_driveway:
    ui:
      order: 4
    objects:
      track:
      - person
      - cat
      - dog
      - car
      filters:
        person:
          # min_area: 90000
          # max_area: 310000
          min_score: 0.6
          threshold: 0.8
        cat:
          # min_area: 5800
          # max_area: 45000
          min_score: 0.6
          threshold: 0.8
        dog:
          # min_area: 1500
          # max_area: 30000
          min_score: 0.6
          threshold: 0.82
        car:
          # min_area: 200000
          # max_area: 500000
          min_score: 0.6
          threshold: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/front_driveway_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/front_driveway_main
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 787,0,787,106,0,106,0,0
    zones:
      driveway_zone:
        coordinates: 0,945,0,1158,218,1440,1934,1440,2157,328,1347,173
      sidewalk_zone:
        coordinates: 2164,187,2173,320,1352,148,1348,38

  office:
    ui:
      order: 5
    objects:
      track:
      - cat
      - dog
      - person
      filters:
        person:
          # min_area: 100000
          # max_area: 200000
          min_score: 0.6
          threshold: 0.8
        cat:
          # min_area: 10000
          # max_area: 30000
          min_score: 0.7
          threshold: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/office_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/office_main
          hwaccel_args: preset-intel-qsv-h265
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 787,0,787,106,0,106,0,0

  side_driveway:
    ui:
      order: 6
    objects:
      track:
      - person
      - cat
      - dog
      filters:
        cat:
          # min_area: 4600
          # max_area: 15000
          min_score: 0.6
          threshold: 0.6
        person:
          # min_area: 130000
          # max_area: 300000
          min_score: 0.7
          threshold: 0.7
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/side_driveway_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/side_driveway_main
          hwaccel_args: preset-intel-qsv-h265
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 787,0,787,106,0,106,0,0
    zones:
      steps:
        coordinates: 1197,509,1453,495,1404,365,1210,365

  backyard:
    ui:
      order: 7
    objects:
      track:
      - person
      - cat
      - dog
      filters:
        person:
          # min_area: 150000
          # max_area: 400000
          min_score: 0.75
          threshold: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/backyard_main
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 787,0,787,106,0,106,0,0

  front_yard:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://x.x.y.y:8554/front_yard_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
        - path: rtsp://x.x.y.y:8554/front_yard_main
          hwaccel_args: preset-intel-qsv-h265
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 30
      contour_area: 30
      mask:
        - 176,0,0,0,0,0,0,91,88,81,119,29,173,28
        - 640,0,640,130,560,148,484,104,394,82,324,62,319,0
    zones:
      main_yard:
        coordinates: 640,360,640,303,513,168,380,159,318,155,136,162,0,258,0,360
    objects:
      track:
        - person
        - backpack
        - car
        - cat
        - dog
        - bicycle
      filters:
        cat:
          # min_area: 4600
          # max_area: 15000
          min_score: 0.6
          threshold: 0.6
        dog:
          # min_area: 7500
          # max_area: 50000
          min_score: 0.6
          threshold: 0.6
        person:
          # min_area: 600
          # max_area: 10000
          min_score: 0.75
          threshold: 0.75
        car:
          # min_area: 700
          # max_area: 7800
          min_score: 0.6
          threshold: 0.72
```

### Relevant log output

```shell
[ERROR] Invalid substitution found, see https://docs.frigate.video/configuration/restream#advanced-restream-configurations for more info.
'FRIGATE_FRONT_YARD_PW'
The go2rtc service exited with code 1 (by signal 0)
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":722,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5278,"pid":643,"process_fps":0.0,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":647,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5148,"pid":633,"process_fps":0.0,"skipped_fps":0.0},"front_driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":654,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5213,"pid":637,"process_fps":0.0,"skipped_fps":0.0},"front_porch":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":650,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5210,"pid":635,"process_fps":0.0,"skipped_fps":0.0},"front_yard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":774,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5340,"pid":645,"process_fps":0.0,"skipped_fps":0.0},"office":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":660,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5211,"pid":639,"process_fps":0.0,"skipped_fps":0.0},"side_driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":691,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5341,"pid":641,"process_fps":0.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.1","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"1.5","cpu_average":"4","mem":"1.8"},"118":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"153":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"173":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"196":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"232":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"263":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"298":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"339":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"382":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"423":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"459":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"577":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.3"},"579":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"0","mem":"0.3"},"588":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"589":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"0.4"},"591":{"cmdline":"frigate.output       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"607":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"608":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"609":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"610":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"611":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"612":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"613":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"614":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"633":{"cmdline":"frigate.process:doorbell","cpu":"0.0","cpu_average":"0","mem":"0.5"},"635":{"cmdline":"frigate.process:front_porch","cpu":"0.0","cpu_average":"0","mem":"0.5"},"637":{"cmdline":"frigate.process:front_driveway","cpu":"0.0","cpu_average":"0","mem":"0.5"},"639":{"cmdline":"frigate.process:office","cpu":"0.0","cpu_average":"0","mem":"0.5"},"641":{"cmdline":"frigate.process:side_driveway","cpu":"0.0","cpu_average":"0","mem":"0.5"},"643":{"cmdline":"frigate.process:backyard","cpu":"0.0","cpu_average":"0","mem":"0.5"},"645":{"cmdline":"frigate.process:front_yard","cpu":"0.0","cpu_average":"0","mem":"0.5"},"647":{"cmdline":"frigate.capture:doorbell","cpu":"0.1","cpu_average":"0","mem":"0.5"},"650":{"cmdline":"frigate.capture:front_porch","cpu":"0.1","cpu_average":"0","mem":"0.5"},"654":{"cmdline":"frigate.capture:front_driveway","cpu":"0.3","cpu_average":"0","mem":"0.5"},"660":{"cmdline":"frigate.capture:office","cpu":"0.2","cpu_average":"0","mem":"0.5"},"691":{"cmdline":"frigate.capture:side_driveway","cpu":"0.3","cpu_average":"0","mem":"0.5"},"722":{"cmdline":"frigate.capture:backyard","cpu":"0.2","cpu_average":"0","mem":"0.5"},"774":{"cmdline":"frigate.capture:front_yard","cpu":"0.1","cpu_average":"0","mem":"0.5"},"5107":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":589}},"gpu_usages":{"intel-qsv":{"gpu":"0.0%","mem":"-%"}},"processes":{"logger":{"pid":577},"recording":{"pid":579}},"service":{"last_updated":1717011087,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":497.9,"mount_type":"tmpfs","total":500.0,"used":2.1},"/media/frigate/clips":{"free":2645451.1,"mount_type":"xfs","total":3813584.8,"used":1168133.7},"/media/frigate/recordings":{"free":2645451.1,"mount_type":"xfs","total":3813584.8,"used":1168133.7},"/tmp/cache":{"free":953.7,"mount_type":"tmpfs","total":953.7,"used":0.0}},"temperatures":{"apex_0":42.55},"uptime":92,"version":"0.13.2-6476f8a"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

My .env file is formatted as follows, with passwords including only alpha numeric, no special characters.

```
FRIGATE_USER=frigate
FRIGATE_OFFICE_PW=ozA9El9dgjdX4JKj
FRIGATE_FRONT_YARD_PW=pgCF1Axx1KLt6wAJ
```

Hopefully it something small I just missed, but I really do appreciate the second set of eyes on my config. Thank you!
