### DISCUSSION TITLE
[Support]: Recommended approach to enable / disable Alerts on demand in v0.14

### DISCUSSION THREAD

**Discussion by Mincka** [blakeblackshear/frigate#11620] [General Support]
### Describe the problem you are having

I would like to disable either the alerts / detections or all the review system based on conditions.

Clearly, the main issue here is that I don't want to see / review alerts when someone is at home during the day.

I already turn off the Detection on certain cameras using the MQTT switches for that.

Should I use that approach or would it be possible to have MQTT topics to globally control the review system?

### Version

Latest 0.14 dev

### Frigate config file

```yaml
review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - person
      - car
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Not relevant
