### DISCUSSION TITLE
[Support]: Frigate mqtt events for objects that aren't tagged.

### DISCUSSION THREAD

**Discussion by jonofmac** [blakeblackshear/frigate#11623] [General Support]
### Describe the problem you are having

I use a home assistant blueprint to parse the mqtt events and send an alert/snapshot to my phone.

I noticed with 0.13 that i started getting "false alerts" where when I clicked on the link it gave to load the clip from frigate, it would always hit me with {"message" : "Event not found", "success" : false}

In 0.14 I've noticed this is ramping up. Using home assistant to look at the mqtt topics that were published, it appears that frigate is pushing topics for objects it's not sure enough are real to snapshot? It's difficult for me to reproduce this because it's quite random, but I managed to get a copy of the mqtt topics for one of the instances.

I don't understand why frigate publishes an MQTT event for this, and even though it meets the probability thresholds and is in the correct zone to be saved as an event/take a snapshot, it does not (randomly).
For what it's worth, there was no actual cat on my patio when I review the footage. I took the video frame, scaled it down to 1080p, then drew the bounding box it suggested. Looks like it got dirt (just had a large storm in DFW and it blew crap everywhere)
![videoframe_13749](https://github.com/blakeblackshear/frigate/assets/11986470/ef45229b-525c-404e-b5f6-2f1d11bedc0e)

It seems like the solution for the blueprint should be to check for the "has_clip" or "has_snapshot" fields, but again, I'm not sure why Frigate is publishing these events when it doesn't save them in its own system.

```
 after:
        id: 1717001150.444927-h2i2zy
        camera: front_door
        frame_time: 1717001150.444927
        snapshot:
          frame_time: 1717001150.632209
          box:
            - 398
            - 1762
            - 785
            - 1916
          area: 59598
          region:
            - 4
            - 844
            - 1080
            - 1920
          score: 0.87109375
          attributes: []
        label: cat
        sub_label: null
        top_score: 0.859375
        false_positive: false
        start_time: 1717001150.444927
        end_time: null
        score: 0.87109375
        box:
          - 398
          - 1762
          - 785
          - 1916
        area: 59598
        ratio: 2.512987012987013
        region:
          - 4
          - 844
          - 1080
          - 1920
        stationary: false
        motionless_count: 0
        position_changes: 0
        current_zones:
          - front_porch
        entered_zones:
          - front_porch
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      type: update
```

I posted the full output below, but what is most interesting, is even though there are a few updates to this event (not just a 1 off frame), 
it never gets logged as an alert/detection
```
Iteration 1
Executed: May 29, 2024 at 11:45:50 AM
Result:
wait:
  remaining: 119.62014875200111
  trigger:
    id: '0'
    idx: '0'
    alias: null
    platform: mqtt
    topic: frigate/events
    payload: >-
      {"before": {"id": "1717001150.444927-h2i2zy", "camera": "front_door",
      "frame_time": 1717001150.444927, "snapshot": {"frame_time":
      1717001150.632209, "box": [398, 1762, 785, 1916], "area": 59598, "region":
      [4, 844, 1080, 1920], "score": 0.87109375, "attributes": []}, "label":
      "cat", "sub_label": null, "top_score": 0.859375, "false_positive": false,
      "start_time": 1717001150.444927, "end_time": null, "score": 0.87109375,
      "box": [398, 1762, 785, 1916], "area": 59598, "ratio": 2.512987012987013,
      "region": [4, 844, 1080, 1920], "stationary": false, "motionless_count":
      0, "position_changes": 0, "current_zones": [], "entered_zones": [],
      "has_clip": false, "has_snapshot": false, "attributes": {},
      "current_attributes": []}, "after": {"id": "1717001150.444927-h2i2zy",
      "camera": "front_door", "frame_time": 1717001150.444927, "snapshot":
      {"frame_time": 1717001150.632209, "box": [398, 1762, 785, 1916], "area":
      59598, "region": [4, 844, 1080, 1920], "score": 0.87109375, "attributes":
      []}, "label": "cat", "sub_label": null, "top_score": 0.859375,
      "false_positive": false, "start_time": 1717001150.444927, "end_time":
      null, "score": 0.87109375, "box": [398, 1762, 785, 1916], "area": 59598,
      "ratio": 2.512987012987013, "region": [4, 844, 1080, 1920], "stationary":
      false, "motionless_count": 0, "position_changes": 0, "current_zones":
      ["front_porch"], "entered_zones": ["front_porch"], "has_clip": false,
      "has_snapshot": false, "attributes": {}, "current_attributes": []},
      "type": "update"}
    qos: 0
    description: mqtt topic frigate/events
    payload_json:
      before:
        id: 1717001150.444927-h2i2zy
        camera: front_door
        frame_time: 1717001150.444927
        snapshot:
          frame_time: 1717001150.632209
          box:
            - 398
            - 1762
            - 785
            - 1916
          area: 59598
          region:
            - 4
            - 844
            - 1080
            - 1920
          score: 0.87109375
          attributes: []
        label: cat
        sub_label: null
        top_score: 0.859375
        false_positive: false
        start_time: 1717001150.444927
        end_time: null
        score: 0.87109375
        box:
          - 398
          - 1762
          - 785
          - 1916
        area: 59598
        ratio: 2.512987012987013
        region:
          - 4
          - 844
          - 1080
          - 1920
        stationary: false
        motionless_count: 0
        position_changes: 0
        current_zones: []
        entered_zones: []
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      after:
        id: 1717001150.444927-h2i2zy
        camera: front_door
        frame_time: 1717001150.444927
        snapshot:
          frame_time: 1717001150.632209
          box:
            - 398
            - 1762
            - 785
            - 1916
          area: 59598
          region:
            - 4
            - 844
            - 1080
            - 1920
          score: 0.87109375
          attributes: []
        label: cat
        sub_label: null
        top_score: 0.859375
        false_positive: false
        start_time: 1717001150.444927
        end_time: null
        score: 0.87109375
        box:
          - 398
          - 1762
          - 785
          - 1916
        area: 59598
        ratio: 2.512987012987013
        region:
          - 4
          - 844
          - 1080
          - 1920
        stationary: false
        motionless_count: 0
        position_changes: 0
        current_zones:
          - front_porch
        entered_zones:
          - front_porch
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      type: update
Iteration 2
Executed: May 29, 2024 at 11:45:51 AM
Result:
wait:
  remaining: 119.81435095201596
  trigger:
    id: '0'
    idx: '0'
    alias: null
    platform: mqtt
    topic: frigate/events
    payload: >-
      {"before": {"id": "1717001150.444927-h2i2zy", "camera": "front_door",
      "frame_time": 1717001150.444927, "snapshot": {"frame_time":
      1717001150.632209, "box": [398, 1762, 785, 1916], "area": 59598, "region":
      [4, 844, 1080, 1920], "score": 0.87109375, "attributes": []}, "label":
      "cat", "sub_label": null, "top_score": 0.859375, "false_positive": false,
      "start_time": 1717001150.444927, "end_time": null, "score": 0.87109375,
      "box": [398, 1762, 785, 1916], "area": 59598, "ratio": 2.512987012987013,
      "region": [4, 844, 1080, 1920], "stationary": false, "motionless_count":
      0, "position_changes": 0, "current_zones": ["front_porch"],
      "entered_zones": ["front_porch"], "has_clip": false, "has_snapshot":
      false, "attributes": {}, "current_attributes": []}, "after": {"id":
      "1717001150.444927-h2i2zy", "camera": "front_door", "frame_time":
      1717001150.444927, "snapshot": {"frame_time": 1717001150.632209, "box":
      [398, 1762, 785, 1916], "area": 59598, "region": [4, 844, 1080, 1920],
      "score": 0.87109375, "attributes": []}, "label": "cat", "sub_label": null,
      "top_score": 0.859375, "false_positive": false, "start_time":
      1717001150.444927, "end_time": 1717001151.231325, "score": 0.87109375,
      "box": [398, 1762, 785, 1916], "area": 59598, "ratio": 2.512987012987013,
      "region": [4, 844, 1080, 1920], "stationary": false, "motionless_count":
      0, "position_changes": 0, "current_zones": ["front_porch"],
      "entered_zones": ["front_porch"], "has_clip": false, "has_snapshot":
      false, "attributes": {}, "current_attributes": []}, "type": "end"}
    qos: 0
    description: mqtt topic frigate/events
    payload_json:
      before:
        id: 1717001150.444927-h2i2zy
        camera: front_door
        frame_time: 1717001150.444927
        snapshot:
          frame_time: 1717001150.632209
          box:
            - 398
            - 1762
            - 785
            - 1916
          area: 59598
          region:
            - 4
            - 844
            - 1080
            - 1920
          score: 0.87109375
          attributes: []
        label: cat
        sub_label: null
        top_score: 0.859375
        false_positive: false
        start_time: 1717001150.444927
        end_time: null
        score: 0.87109375
        box:
          - 398
          - 1762
          - 785
          - 1916
        area: 59598
        ratio: 2.512987012987013
        region:
          - 4
          - 844
          - 1080
          - 1920
        stationary: false
        motionless_count: 0
        position_changes: 0
        current_zones:
          - front_porch
        entered_zones:
          - front_porch
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      after:
        id: 1717001150.444927-h2i2zy
        camera: front_door
        frame_time: 1717001150.444927
        snapshot:
          frame_time: 1717001150.632209
          box:
            - 398
            - 1762
            - 785
            - 1916
          area: 59598
          region:
            - 4
            - 844
            - 1080
            - 1920
          score: 0.87109375
          attributes: []
        label: cat
        sub_label: null
        top_score: 0.859375
        false_positive: false
        start_time: 1717001150.444927
        end_time: 1717001151.231325
        score: 0.87109375
        box:
          - 398
          - 1762
          - 785
          - 1916
        area: 59598
        ratio: 2.512987012987013
        region:
          - 4
          - 844
          - 1080
          - 1920
        stationary: false
        motionless_count: 0
        position_changes: 0
        current_zones:
          - front_porch
        entered_zones:
          - front_porch
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      type: end 
```

### Version

 0.14.0-b97e274

### Frigate config file

```yaml
database:
  path: /db/frigate.db

model:
  path: plus://<redact>

mqtt:
  host: <redact>
  port: 1883
  user: <redact>
  password: <redact>


logger:
  default: info

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  stationary:
    interval: 5
    threshold: 50

objects:
  track:
    - person
    - face
    - car
    - amazon
    - ups
    - fedex
    - package
    - cat
    - dog
  filters:
    person:
      min_score: 0.85
    cat:
      min_score: 0.83
    dog:
      min_score: 0.83
    car:
      min_score: 0.8
    package:
      min_score: 0.84

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_height: 50
  improve_contrast: true

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: true
  retain:
    default: 20

record:
  enabled: true
  expire_interval: 1
  retain:
    days: 20
    mode: all
  events:
    pre_capture: 5
    post_capture: 2

live:
  height: 1080
  quality: 8


# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
   # Optional: Mode of the view. Available options are: objects, motion, and continuous
   #   objects - cameras are included if they have had a tracked object within the last 30 seconds
   #   motion - cameras are included if motion was detected in the last 30 seconds
   #   continuous - all cameras are included always
  mode: continuous

go2rtc:
  webrtc:
    candidates:
      - 10.1.1.10:8555
  streams:
    rtsp_back_porch:
      - rtsp://<redact:redact>@hikvision3:554/Streaming/Channels/101/

    rtsp_front_yard:
      - rtsp://<redact:redact>@hikvision6:554/Streaming/Channels/101/

    rtsp_driveway_side:
      - rtsp://<redact:redact>@hikvision5:554/Streaming/Channels/101/

    rtsp_front_door:
      - rtsp://<redact:redact>@hikvision1:554/Streaming/Channels/101/

    rtsp_garage:
      - rtsp://<redact:redact>@hikvision2:554/Streaming/Channels/101/


cameras:
####### Back Porch Camera ######
  back_porch:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: rtsp_back_porch
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      patio:
        coordinates: 0.957,0.608,0.333,0.083,0.234,0,0.115,0,0,0.102,0,1,0.982,1
        objects:
          - person
          - cat
          - dog
        inertia: 3
      parking_zone:
        coordinates: 0.281,0,0.969,0,0.904,0.459,0.369,0.18,0.258,0.149
        objects:
          - person
          - cat
          - dog
        inertia: 3
    snapshots:
      required_zones:
        - patio
        - parking_zone
    objects:
      track:
        - person
        - face
        - cat
        - dog
      filters:
        cat:
          min_area: 200
        dog:
          min_area: 200
    review:
      alerts:
        required_zones:
          - patio
          - parking_zone
      detections:
        required_zones: patio
    motion:
      mask: 0.063,0.932,0.34,0.924,0.342,0.968,0.06,0.97
  front_yard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: rtsp_front_yard
    detect:
      fps: 4
    motion:
      mask:
        - 0.415,0.061,0.345,0.09,0.335,0,1,0,1,0.162,0.896,0.104,0.699,0.054
        - 0,0,0.273,0,0.28,0.058,0.23,0.1,0.151,0.147,0,0.243
        - 0.018,0.913,0.26,0.915,0.261,0.946,0.016,0.948
      threshold: 25
      contour_area: 30
      improve_contrast: false
    zones:
      yard:
        coordinates: 
          0.064,0.306,0,0.383,0,1,1,1,1,0.422,0.887,0.233,0.65,0.191,0.374,0.203,0.263,0.224,0.119,0.268
        objects:
          - person
          - face
          - amazon
          - ups
          - fedex
          - cat
          - dog
        min_area: 3000
        inertia: 3
      driveway:
        coordinates: 1,0.425,1,0.284,0.893,0.246
        objects:
          - person
          - fedex
          - amazon
          - ups
          - car
          - cat
          - dog
        inertia: 3
      street:
        coordinates: 
          0,0.26,0.165,0.162,0.229,0.113,0.308,0.066,0.344,0.065,0.292,0.113,0.457,0.076,0.613,0.064,0.824,0.091,1,0.152,1,0.242,0.693,0.163,0.335,0.186,0.124,0.265,0,0.333
        objects:
          - car
          - person
          - face
          - amazon
          - ups
          - fedex
          - cat
          - dog
        inertia: 3
    objects:
      filters:
        car:
          min_area: 3000
        person:
          min_area: 3000
    snapshots:
      required_zones:
        - street
        - driveway
        - yard

# Driveway camera
    review:
      alerts:
        required_zones:
          - driveway
          - yard
      detections:
        required_zones:
          - yard
          - driveway
          - street
  driveway_side:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_driveway_side
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: rtsp_driveway_side
    detect:
      width: 1920
      height: 1080
      fps: 4
    motion:
      mask:
        - 0.585,0.078,0.405,0.122,0.545,0.162,0.76,0.263,0.772,0.002
        - 0.336,0,0.035,0,0.044,0.188,0.193,0.131,0.347,0.064
        - 0.018,0.913,0.26,0.908,0.261,0.948,0.016,0.949
    objects:
      filters:
        car:
          min_area: 15000
        person:
          min_area: 70000
        cat:
          min_score: 0.5
          min_area: 10000
        dog:
          min_score: 0.5
          min_area: 10000
    zones:
      driveway_entrance:
        coordinates: 0.393,0.148,0.51,0.255,0,0.5,0,0.323
        objects:
          - person
          - face
          - car
          - cat
          - dog
        inertia: 3
      driveway:
        coordinates: 
          0.536,0.253,0.761,0.348,0.775,0.035,0.935,0.078,1,0.092,1,1,0,1,0,0.518,0.205,0.48,0.447,0.353
        objects:
          - person
          - car
          - cat
          - dog
        inertia: 3
      street:
        coordinates: 0.234,0.184,0.039,0.249,0.035,0.09,0.21,0.029,0.427,0.019,0.435,0.114
        objects:
          - car
          - person
          - cat
          - dog
        inertia: 3
    snapshots:
      required_zones:
        - driveway_entrance
        - driveway
    review:
      alerts:
        required_zones:
          - driveway_entrance
          - driveway
      detections:
        required_zones:
          - driveway
          - driveway_entrance
          - street

###### Front Door Camera ######
  front_door:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: rtsp_front_door
    detect:
      height: 1920
      width: 1080
      fps: 5
    motion:
      mask: 1,0,0,0,0,0.388,1,0.432
    zones:
      front_porch:
        coordinates: 884,824,1086,939,1086,1920,0,1920,0,767,86,806,348,841
        objects:
          - person
          - face
          - cat
          - dog
          - amazon
          - ups
          - fedex
          - package
    objects:
      filters:
        dog:
          mask:
            - 644,1628,839,1920,1080,1920,1080,1369,999,1353,728,1441
        cat:
          mask:
            - 644,1628,839,1920
        package:
          mask:
            - 0,1920,222,1920,97,1498,0,1463
            - 1080,1920,1080,1403,528,1424,442,1809,156,1841,116,1920
    snapshots:
      required_zones:
        - front_porch

    review:
      alerts:
        required_zones:
          - front_porch

###### Garage Camera ######
  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: rtsp_garage
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      garage_inside:
        coordinates: 0.003,0.125,0.539,0.003,0.999,0.18,0.995,0.994,0.003,0.997
        objects:
          - person
          - cat
          - dog
        inertia: 3
    snapshots:
      required_zones:
        - garage_inside

    review:
      detections:
        required_zones: garage_inside
      alerts:
        required_zones: garage_inside
    motion:
      mask: 0.369,0.952,0.342,0.901,0.077,0.909,0.064,1
```

### Relevant log output

```shell
Nothing in logs
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://<redact:redact>@hikvision6:554/Streaming/Channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.100000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 10 fps, 10 tbr, 90k tbn
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Hikivisions
