### DISCUSSION TITLE
[Config Support]: Excluding expected objects from detections

### DISCUSSION THREAD

**Discussion by jamie-tm** [blakeblackshear/frigate#11640] [Config Support] [answered]
### Describe the problem you are having

Hi again!

What I'm trying to accomplish, what I _think_ the docs say _should_ happen, and what's actually happening are three different things. So, I'll touch on them individually.

#### What I'm trying to do
The goal I'm trying to accomplish is to track the counts of objects in certain locations (in Home Assistant), _without_ generating detections in the Reviews tab of the new UI. I understand that this may not be possible, but I wanted to test it thoroughly before I opened a feature request.

My use case is that we routinely let the dogs into the fenced-in back yard. I want to have routines in HA that operate on the dog count/occupancy ("Hey, you forgot to let the dogs back in!"), but I _don't_ want to have a whole pile of detections to review when I log into Frigate.

So, to test if I could do this, I tried disabling detections on my porch camera following [the review instructions](https://deploy-preview-11419--frigate-docs.netlify.app/configuration/review#excluding-a-camera-from-alerts-or-detections):
```yaml
  porch_cam:
    # ... Other properties removed for brevity, see full config below for details
    objects:
      track:
        - person
        - dog
        - cat
        - deer
        - face
    review:
      alerts:
        labels: []
      detections:
        labels: []
    # ... 
```

After setting this config and restarting, I verified that there were no alerts or detections in Frigate and that all sensors were clear in Home Assistant. Then I walked out onto my porch and stood in view of the camera.

## What I expect to happen
I expected that this would prevent any alerts or detections from this camera from appearing in the Review tab in Frigate. The doc seemed pretty straight-forward about that.

What I didn't know was if it would still track me as an object and report me to HA via MQTT. I _hoped_ it would, but thought it might not.

#### What actually happened
My presence showed up _both_ as a Detection for review in Frigate _and_ in Home Assistant. The latter is good, but the former confused me. I though my config should have disabled that. 😕 

#### What now?
So, two questions:
1. How do I _actually_ configure it to disable detections on that camera? (At least for people and dogs. I still would like cats and deer, if I can.)
2. Once I do that, is it still possible to track occupancy/counts of people and dogs in HA?

Thanks so much for any help, and for the absolutely incredible piece of software you've built!

### Version

0.14.0-b97e274

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate.local/api/config/schema.json

mqtt:
  host: REDACTED
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  coral:
    type: edgetpu
    device: pci:0

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

detect:
  width: 1920
  height: 1080
  fps: 5

model:
  path: plus://REDACTED # Model trained 5/29/2024

objects:
  track:
    # Supported objects:
    - person
    - car
    - dog
    - cat
    - deer
    - package
    # Special labels:
    - face
    - license_plate
    - amazon
    - ups
    - fedex
  filters:
    person:
      min_score: 0.6
      threshold: 0.75

review:
  alerts:
    labels:
      - person
      - car
      - dog

record:
  enabled: true
  events:
    retain:
      mode: active_objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false

ui:
  live_mode: webrtc

camera_groups:
  Back:
    order: 1
    icon: LuDog
    cameras:
      - backyard_cam
      - garden_cam
      - porch_cam
  Front:
    order: 2
    icon: LuDoorClosed
    cameras:
      - front_cam
      - driveway_cam
      - garden_cam

go2rtc:
  streams:
    # Redacted for brevity, and to hide IPs.

cameras:
  driveway_cam:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_cam_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_cam
          input_args: preset-rtsp-restream
          roles:
            - record
    snapshots:
      required_zones:
        - driveway
        - frontyard
    review:
      alerts:
        required_zones:
          - driveway
          - frontyard
      detections:
        required_zones:
          - parking
          - street
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.625,0.037,0.958,0.038,0.959,0.09,0.625,0.09
    zones:
      driveway:
        coordinates: 
          0.174,1,0.521,1,0.513,0.497,0.782,0.509,0.715,0.283,0.513,0.211,0.396,0.219,0.289,0.506,0.201,0.753
        inertia: 3
      parking:
        coordinates: 0.523,1,0.514,0.587,1,0.595,1,1
        inertia: 3
      frontyard:
        coordinates: 0.201,0.745,0.395,0.219,0.036,0.236,0.088,0.75
        inertia: 3
      street:
        coordinates: 0.295,0.176,0.742,0.188,0.741,0.133,0.295,0.114
        loitering_time: 5
        inertia: 3
        objects:
          - car
          - person

  front_cam:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_cam_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_cam
          roles:
            - record
    review:
      alerts:
        required_zones:
          - frontyard
          - driveway
      detections:
        required_zones: street
    motion:
      mask: 0.625,0.037,0.96,0.035,0.961,0.09,0.625,0.089
    zones:
      driveway:
        coordinates: 1,0.387,1,1,0.635,0.446,0.489,0.317,0.74,0.322
        inertia: 3
      frontyard:
        coordinates: 1,1,0,1,0,0.398,0.095,0.352,0.314,0.319,0.48,0.311,0.633,0.445
        inertia: 3
      street:
        coordinates: 
          0.214,0.258,0.204,0.321,0.318,0.301,0.44,0.299,0.671,0.299,0.874,0.333,0.873,0.273,0.626,0.24,0.444,0.236
        loitering_time: 5
        objects:
          - car
          - person
        inertia: 3

  porch_cam:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch_cam_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/porch_cam
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - deer
        - face
      mask: 0.6,0.581,0.685,0.57,0.678,0.495,0.643,0.502,0.596,0.521
    review:
      alerts:
        labels: []
      detections:
        labels: [] # TODO Refine/remove this
        # required_zones:
        #   - porch
        #   - backyard
    motion:
      mask: 
        0.663,0.231,0.411,0.135,0.274,0.119,0.165,0.157,0.124,0.08,0,0.166,0,0,1,0,1,0.464,0.85,0.339
    zones:
      porch:
        coordinates: 
          0.069,0.703,0.238,0.543,0.431,0.969,0.532,0.803,0.354,0.433,0.353,0.375,0.226,0.286,0.141,0.23,0.006,0.312
        inertia: 3
      backyard:
        coordinates: 
          0.428,0.973,0.538,0.803,0.376,0.468,0.365,0.307,0.468,0.238,0.651,0.317,0.826,0.437,1,0.574,0.998,0.998,0.43,0.998,0.155,0.998,0.076,0.741,0.165,0.653,0.206,0.745,0.245,0.714
        inertia: 3

  backyard_cam:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cam_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_cam
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - deer
        - face
    review:
      alerts:
        labels: []
      detections:
        labels: [] # TODO Refine/remove this
        # required_zones: backyard
    motion:
      mask: 
        0,0,0,0.401,0.159,0.235,0.312,0.12,0.417,0.061,0.526,0.032,0.745,0.086,0.9,0.168,1,0.253,1,0
    zones:
      backyard:
        coordinates: 
          0,0.535,0.129,0.382,0.267,0.25,0.408,0.15,0.528,0.099,0.646,0.138,0.769,0.187,0.898,0.272,1,0.358,1,1,0,1
        inertia: 3

  garden_cam:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_cam_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garden_cam
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - deer
        - face
    review:
      alerts:
        labels: []
      detections:
        labels: [] # TODO Refine/remove this
        # required_zones: backyard
    motion:
      mask:
        - 0.187,0,1,0,1,0.431,0.769,0.147,0.466,0.019,0.277,0.019,0.186,0.045,0.103,0.075,0,0.133,0,0
        - 0,0.275,0,1,0.296,1,0.24,0.714,0.164,0.44,0.079,0.482,0.078,0.571,0.055,0.574,0.05,0.527,0.017,0.434
        - 0.771,0.265,0.712,0.483,0.668,0.549,0.691,0.805,0.724,0.937,0.905,0.987,0.942,0.919,1,0.816,1,0.241,0.819,0.218
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      backyard:
        coordinates: 0.46,0.088,0.597,0.292,0.908,0.863,0.908,1,0,0.996,0,0.2,0.104,0.144,0.281,0.097
        inertia: 3
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
N/A (probably)
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2
