### DISCUSSION TITLE
[Support]: No detections for one camera

### DISCUSSION THREAD

**Discussion by marcfager** [blakeblackshear/frigate#11647] [General Support] [answered]
### Describe the problem you are having

Hi,

I have setup frigate with five cameras. First four, and now later one additional. The cameras are all Ubiquiti (2 pcs G4 Pro, 1 pcs G4 doorbell and 2 pcs G3 Flex) and the streams come from a Cloud Key Gen2+. With the first four everything works very well and as intended. I added a fifth camera (a G3 Flex) and practically copy-pasted the config both for the stream (go2rtc) and the detection/recording part from the other G3 Flex that already was setup and worked well. I of course adjusted camera names, stream urls etc.

The issue is that the last camera doesn't detect anything. I have tried to set the detection limit min_score to as low as 10 without any success. The stream itself works well. Any suggestions what to try next?

In the config below, Patio is the working G3 Flex and Bastuentre the one where detections are not working. I assume detections are not working since no events are created in Frigate. I (person) have tried to approach the camera from all different angles but still no detection. The placement is perhaps not ideal, but I think it is better than some of the other ones that work very well.

![frigate_bastuentre](https://github.com/blakeblackshear/frigate/assets/59563338/88601925-bccb-4561-b93d-34ec46c77ff8)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
    host: 1.2.3.4
    user: frigate
    password: password

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - boat
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - baseball bat
    - knife



go2rtc:
  streams:
    Patio:
      - rtspx://10.100.3.2:7441/123
      - "ffmpeg:rtsp_cam#audio=opus"
    Patio_sub: 
      - rtspx://10.100.3.2:7441/456
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    Dorrklocka:
      - rtspx://10.100.3.2:7441/789
      - "ffmpeg:rtsp_cam#audio=opus"
    Dorrklocka_sub: 
      - rtspx://10.100.3.2:7441/101
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    Uppfart:
      - rtspx://10.100.3.2:7441/102
      - "ffmpeg:rtsp_cam#audio=opus"
    Uppfart_sub: 
      - rtspx://10.100.3.2:7441/103
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    Husentre:
      - rtspx://10.100.3.2:7441/104
      - "ffmpeg:rtsp_cam#audio=opus"
    Husentre_sub: 
      - rtspx://10.100.3.2:7441/105
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    Bastuentre:
      - rtspx://10.100.3.2:7441/106
      - "ffmpeg:rtsp_cam#audio=opus"
    Bastuentre_sub: 
      - rtspx://10.100.3.2:7441/107
      - "ffmpeg:rtsp_cam_sub#audio=opus"

birdseye:
  enabled: true
  mode: objects
  inactivity_threshold: 120
  restream: true

cameras:
  Patio:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/Patio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Patio
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,0,0,14,120,12,126,0
        - 164,198,165,247,200,246,209,200,187,188
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - elephant
        - bear
        - zebra
        - giraffe
      filters:
        person:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        bird:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        cat:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        dog:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        horse:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        sheep:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        cow:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        elephant:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        bear:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        zebra:
          mask:
            - 164,198,165,247,200,246,209,200,187,188
        giraffe:
          mask:
            - 164,198,165,247,200,246,209,200,187,188

  Dorrklocka:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/Dorrklocka_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dorrklocka
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,0,0,14,164,14,164,0
    objects:
      filters:
        person:
          min_area: 1600
  Uppfart:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/Uppfart_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Uppfart
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,0,0,14,120,12,126,0
        - 302,59,307,90,266,102,238,105,233,78
    objects:
      filters:
        person:
          mask:
            - 452,57,449,98,407,94,243,91,238,47,322,38
        car:
          mask:
            - 305,360,306,223,0,105,0,360
            - 0,181,0,102,161,249,210,360,0,360
        boat:
          mask:
            - 172,127,158,0,466,0,473,118
  Husentre:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/Husentre_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Husentre
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,0,0,14,120,12,126,0
  Bastuentre:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/Bastuentre_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Bastuentre
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - elephant
        - bear
        - zebra
        - giraffe
      filters:
        person:
          min_score: 10
    motion:
      mask:
        - 124,0,115,21,0,21,0,0
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting

s6-rc: info: service s6rc-oneshot-runner: starting

s6-rc: info: service s6rc-oneshot-runner successfully started

s6-rc: info: service fix-attrs: starting

s6-rc: info: service fix-attrs successfully started

s6-rc: info: service legacy-cont-init: starting

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service log-prepare: starting

s6-rc: info: service s6rc-fdholder successfully started

s6-rc: info: service log-prepare successfully started

s6-rc: info: service nginx-log: starting

s6-rc: info: service go2rtc-log: starting

s6-rc: info: service frigate-log: starting

s6-rc: info: service nginx-log successfully started

s6-rc: info: service go2rtc-log successfully started

s6-rc: info: service go2rtc: starting

s6-rc: info: service frigate-log successfully started

s6-rc: info: service go2rtc successfully started

s6-rc: info: service go2rtc-healthcheck: starting

s6-rc: info: service frigate: starting

s6-rc: info: service go2rtc-healthcheck successfully started

s6-rc: info: service frigate successfully started

s6-rc: info: service nginx: starting

2024-05-30 12:26:25.555848242  [INFO] Preparing Frigate...

2024-05-30 12:26:25.557592948  [INFO] Starting NGINX...

s6-rc: info: service nginx successfully started

s6-rc: info: service legacy-services: starting

s6-rc: info: service legacy-services successfully started

2024-05-30 12:26:25.965987172  [INFO] Preparing new go2rtc config...

2024-05-30 12:26:26.448598205  [INFO] Starting Frigate...

2024-05-30 12:26:27.590696504  [INFO] Starting go2rtc...

2024-05-30 12:26:27.594690800  2024/05/30 12:26:27 [error] 142#142: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.100.10.17, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "10.100.41.47:5000"

2024-05-30 12:26:27.594775351  10.100.10.17 - - [30/May/2024:12:26:27 +0000] "GET /ws HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:27.937122415  12:26:27.936 INF go2rtc version 1.8.4 linux/amd64

2024-05-30 12:26:27.937590290  12:26:27.937 INF [rtsp] listen addr=:8554

2024-05-30 12:26:27.937727521  12:26:27.937 INF [api] listen addr=:1984

2024-05-30 12:26:27.937962297  12:26:27.937 INF [webrtc] listen addr=:8555

2024-05-30 12:26:29.302508280  [2024-05-30 12:26:29] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)

2024-05-30 12:26:29.372214340  [2024-05-30 12:26:29] peewee_migrate.logs            INFO    : Starting migrations

2024-05-30 12:26:29.376379506  [2024-05-30 12:26:29] peewee_migrate.logs            INFO    : There is nothing to migrate

2024-05-30 12:26:29.380741489  [2024-05-30 12:26:29] frigate.app                    INFO    : Recording process started: 290

2024-05-30 12:26:29.383287475  [2024-05-30 12:26:29] frigate.app                    INFO    : go2rtc process pid: 98

2024-05-30 12:26:29.411477797  [2024-05-30 12:26:29] frigate.app                    INFO    : Output process started: 300

2024-05-30 12:26:29.465500728  [2024-05-30 12:26:29] frigate.app                    INFO    : Camera processor started for Patio: 310

2024-05-30 12:26:29.473243321  [2024-05-30 12:26:29] frigate.app                    INFO    : Camera processor started for Dorrklocka: 311

2024-05-30 12:26:29.489133585  [2024-05-30 12:26:29] frigate.app                    INFO    : Camera processor started for Uppfart: 314

2024-05-30 12:26:29.505693308  [2024-05-30 12:26:29] frigate.app                    INFO    : Camera processor started for Husentre: 317

2024-05-30 12:26:29.510729500  [2024-05-30 12:26:29] frigate.app                    INFO    : Camera processor started for Bastuentre: 321

2024-05-30 12:26:29.515332866  [2024-05-30 12:26:29] frigate.app                    INFO    : Capture process started for Patio: 322

2024-05-30 12:26:29.530411775  [2024-05-30 12:26:29] frigate.app                    INFO    : Capture process started for Dorrklocka: 323

2024-05-30 12:26:29.554104293  [2024-05-30 12:26:29] frigate.app                    INFO    : Capture process started for Uppfart: 325

2024-05-30 12:26:29.572508886  [2024-05-30 12:26:29] frigate.app                    INFO    : Capture process started for Husentre: 331

2024-05-30 12:26:29.586151476  [2024-05-30 12:26:29] frigate.app                    INFO    : Capture process started for Bastuentre: 337

2024-05-30 12:26:32.089920251  [2024-05-30 12:26:29] detector.coral                 INFO    : Starting detection process: 299

2024-05-30 12:26:32.089923816  [2024-05-30 12:26:29] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb

2024-05-30 12:26:32.095354578  [2024-05-30 12:26:32] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

2024-05-30 12:26:35.554568075  [INFO] Starting go2rtc healthcheck service...

2024-05-30 12:26:52.035563799  10.100.10.17 - - [30/May/2024:12:26:52 +0000] "GET /api/go2rtc/api HTTP/1.1" 200 142 "http://10.100.41.47:5000/system" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:52.045110259  10.100.10.17 - - [30/May/2024:12:26:52 +0000] "GET /api/config HTTP/1.1" 200 33210 "http://10.100.41.47:5000/system" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:53.145955724  10.100.10.17 - - [30/May/2024:12:26:53 +0000] "GET /api/Dorrklocka/latest.jpg?h=286 HTTP/1.1" 200 25176 "http://10.100.41.47:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:53.148730157  10.100.10.17 - - [30/May/2024:12:26:53 +0000] "GET /api/Bastuentre/latest.jpg?h=286 HTTP/1.1" 200 35406 "http://10.100.41.47:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:53.159776750  10.100.10.17 - - [30/May/2024:12:26:53 +0000] "GET /api/Husentre/latest.jpg?h=286 HTTP/1.1" 200 25022 "http://10.100.41.47:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:53.163764979  10.100.10.17 - - [30/May/2024:12:26:53 +0000] "GET /api/Patio/latest.jpg?h=286 HTTP/1.1" 200 37264 "http://10.100.41.47:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"

2024-05-30 12:26:53.164472735  10.100.10.17 - - [30/May/2024:12:26:53 +0000] "GET /api/Uppfart/latest.jpg?h=286 HTTP/1.1" 200 22732 "http://10.100.41.47:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
rtspx://10.100.3.2:7441/cameraUrl: Protocol not found
```

### Frigate stats

```json
cameras	
Bastuentre	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	337
detection_enabled	1
detection_fps	5.5
ffmpeg_pid	361
pid	321
process_fps	5.1
skipped_fps	0
Dorrklocka	
audio_dBFS	0
audio_rms	0
camera_fps	5
capture_pid	323
detection_enabled	1
detection_fps	3
ffmpeg_pid	340
pid	311
process_fps	5
skipped_fps	0
Husentre	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	331
detection_enabled	1
detection_fps	0
ffmpeg_pid	347
pid	317
process_fps	5
skipped_fps	0
Patio	
audio_dBFS	0
audio_rms	0
camera_fps	5
capture_pid	322
detection_enabled	1
detection_fps	5.1
ffmpeg_pid	341
pid	310
process_fps	5.1
skipped_fps	0
Uppfart	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	325
detection_enabled	1
detection_fps	7.5
ffmpeg_pid	345
pid	314
process_fps	5.1
skipped_fps	0
cpu_usages	
1	
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
15	
cmdline	"s6-supervise s6-linux-init-shutdownd"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
18	
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
24	
cmdline	"s6-supervise nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
25	
cmdline	"s6-supervise s6rc-oneshot-runner"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
26	
cmdline	"s6-supervise frigate-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
27	
cmdline	"s6-supervise go2rtc-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
28	
cmdline	"s6-supervise go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
29	
cmdline	"s6-supervise s6rc-fdholder"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
30	
cmdline	"s6-supervise frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
31	
cmdline	"s6-supervise go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
32	
cmdline	"s6-supervise nginx-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
41	
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
44	
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
79	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
80	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
84	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
98	
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
cpu	"5.9"
cpu_average	"5"
mem	"0.3"
111	
cmdline	"bash ./run.user go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
113	
cmdline	"python3 -u -m frigate"
cpu	"2.7"
cpu_average	"2"
mem	"2.7"
120	
cmdline	"nginx: master process nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
142	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
143	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
144	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
145	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
146	
cmdline	"nginx: cache manager process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
288	
cmdline	"frigate.logger       "
cpu	"0.0"
cpu_average	"0"
mem	"1.3"
290	
cmdline	"frigate.recording_manager"
cpu	"5.2"
cpu_average	"2"
mem	"1.7"
298	
cmdline	"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)"
cpu	"0.3"
cpu_average	"0"
mem	"0.1"
299	
cmdline	"frigate.detector.coral"
cpu	"9.1"
cpu_average	"8"
mem	"1.7"
300	
cmdline	"frigate.output       "
cpu	"3.2"
cpu_average	"2"
mem	"1.5"
304	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
309	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
310	
cmdline	"frigate.process:Patio"
cpu	"1.9"
cpu_average	"0"
mem	"1.6"
311	
cmdline	"frigate.process:Dorrklocka"
cpu	"2.5"
cpu_average	"0"
mem	"1.7"
314	
cmdline	"frigate.process:Uppfart"
cpu	"2.7"
cpu_average	"0"
mem	"1.7"
315	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
317	
cmdline	"frigate.process:Husentre"
cpu	"0.8"
cpu_average	"0"
mem	"1.7"
319	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
321	
cmdline	"frigate.process:Bastuentre"
cpu	"2.2"
cpu_average	"0"
mem	"1.6"
322	
cmdline	"frigate.capture:Patio"
cpu	"0.3"
cpu_average	"0"
mem	"1.5"
323	
cmdline	"frigate.capture:Dorrklocka"
cpu	"0.5"
cpu_average	"0"
mem	"1.5"
324	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
325	
cmdline	"frigate.capture:Uppfart"
cpu	"0.3"
cpu_average	"0"
mem	"1.5"
328	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"2.7"
cpu_average	"1"
mem	"0.6"
331	
cmdline	"frigate.capture:Husentre"
cpu	"0.5"
cpu_average	"0"
mem	"1.5"
337	
cmdline	"frigate.capture:Bastuentre"
cpu	"0.5"
cpu_average	"0"
mem	"1.5"
340	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Dorrklocka_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"1.0"
cpu_average	"0"
mem	"0.7"
341	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Patio_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"1.0"
cpu_average	"0"
mem	"0.7"
345	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Uppfart_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"1.5"
cpu_average	"0"
mem	"0.7"
347	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Husentre_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"1.4"
cpu_average	"0"
mem	"0.7"
356	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Patio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/Patio@%Y%m%d%H%M%S%z.mp4"
cpu	"1.5"
cpu_average	"0"
mem	"0.3"
361	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Bastuentre_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"1.2"
cpu_average	"0"
mem	"0.7"
365	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Dorrklocka -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/Dorrklocka@%Y%m%d%H%M%S%z.mp4"
cpu	"1.4"
cpu_average	"0"
mem	"0.3"
366	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Husentre -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/Husentre@%Y%m%d%H%M%S%z.mp4"
cpu	"1.4"
cpu_average	"0"
mem	"0.3"
368	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Uppfart -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/Uppfart@%Y%m%d%H%M%S%z.mp4"
cpu	"1.5"
cpu_average	"0"
mem	"0.3"
372	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Bastuentre -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/Bastuentre@%Y%m%d%H%M%S%z.mp4"
cpu	"1.5"
cpu_average	"0"
mem	"0.3"
679	
cmdline	"sleep 30s"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
detection_fps	21.1
detectors	
coral	
detection_start	0
inference_speed	9.54
pid	299
gpu_usages	
intel-vaapi	
gpu	"2.41%"
mem	"-%"
processes	
go2rtc	
pid	98
logger	
pid	288
recording	
pid	290
service	
last_updated	1717072096
latest_version	"0.13.2"
storage	
/dev/shm	
free	121.7
mount_type	"tmpfs"
total	128
used	6.3
/media/frigate/clips	
free	705713.1
mount_type	"ext4"
total	805246.9
used	58557.8
/media/frigate/recordings	
free	705713.1
mount_type	"ext4"
total	805246.9
used	58557.8
/tmp/cache	
free	705713.1
mount_type	"overlay"
total	805246.9
used	58557.8
temperatures	{}
uptime	107
version	"0.13.2-6476f8a"
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G3 Flex (affected), Unifi G4 Pro, Unifi G4 Doorbell
