### DISCUSSION TITLE
Error fetching frigate data.     &        Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:

### DISCUSSION THREAD

**Discussion by greydeee** [blakeblackshear/frigate#11641] [General Support]
### Describe the problem you are having

Hi All,

After sorting out my config in a previous post, I'm getting these errors in the HA logs and I'm not sure where to begin. I thought it may have been something to do with my MQTT broker upgrade but after a rollback I'm still having issues. I'm not sure where to start with API issues to be honest. I'm also not sure how long these issues have been happening either. 

I have remote access setup through a domain name and SSL. This works correctly i believe and I have it set up correctly I think in HA.

<img width="602" alt="Screen Shot 2024-05-30 at 11 50 50" src="https://github.com/blakeblackshear/frigate/assets/141195780/801f8802-f4c2-4544-a7cc-cbcf325f4e55">

<img width="608" alt="Screen Shot 2024-05-30 at 11 53 56" src="https://github.com/blakeblackshear/frigate/assets/141195780/d7373ef3-5f83-4813-8f04-dc8c4b13c62c">

<img width="389" alt="Screen Shot 2024-05-30 at 12 31 01" src="https://github.com/blakeblackshear/frigate/assets/141195780/de82e518-f3c0-4c3f-adaf-86228b3da425">

Thanks for you help. 

### Version

0.13.2

### Frigate config file

```yaml
#mqtt:
#  enabled: False

mqtt:
  host: core-mosquitto
  topic_prefix: frigate
  client_id: frigate
  ##  stats_interval: 60        #60 seconds is default value
  user: xxxxxx
  password: xxxxxxxx

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

go2rtc:
  streams:
    Front-Right:
      - rtsp://xxxxxx:xxxxx@192.168.6.40:554/h264Preview_01_main
    Front-Right_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.40:554/h264Preview_01_sub
    Front-Left:
      - rtsp://xxxxxx:xxxxx@192.168.6.42:554/h264Preview_01_main
    Front-Left_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.42:554/h264Preview_01_sub
    Doorbell:
      - rtsp://xxxxxx:xxxxx@192.168.6.41:554/h264Preview_01_main
    Doorbell_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.41:554/h264Preview_01_sub
    Left-Side:
      - rtsp://xxxxxx:xxxxx@192.168.6.43:554/h264Preview_01_main
    Left-Side_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.43:554/h264Preview_01_sub
    Backyard:
      - rtsp://xxxxxx:xxxxx@192.168.6.44:554/h264Preview_01_main
    Backyard_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.44:554/h264Preview_01_sub
    Patio:
      - rtsp://xxxxxx:xxxxx@192.168.6.45:554/h264Preview_01_main
    Patio_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.45:554/h264Preview_01_sub
    Right-Side:
      - rtsp://xxxxxx:xxxxx@192.168.6.46:554/h264Preview_01_main
    Right-Side_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.46:554/h264Preview_01_sub
    Garage:
      - rtsp://xxxxxx:xxxxx@192.168.6.47:554/h264Preview_01_main
    Garage_sub:
      - rtsp://xxxxxx:xxxxx@192.168.6.47:554/h264Preview_01_sub

#___________________________________________________________________________________________________
cameras:
  #___________________________________________________________________________________________________

  C_Front-Right:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Right
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front-Right_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 896
      height: 512
      fps: 4
      stationary: 
        interval: 50
        threshold: 50 

    objects: #objects must be here to be listed down below in zones
      track:
        - person
        - car
        - dog
        - motorcycle

      filters:
        person:
          mask:
            - 406,114,422,115,424,76,403,73

        car:
          mask:
            - 197,121,0,201,0,512,512,512,645,512,896,512,896,0,491,0,191,0,198,57,448,93,451,131
          threshold: 0.75
          min_area: 6000

    zones:
      Z_Front-Right_Driveway:
        coordinates: 412,110,428,136,300,149,135,160,58,152,70,0,139,0,193,25,198,84,244,85,286,90
        objects:
          - person
          - car
          - dog

      Z_Front-Right_Frontgrass:
        coordinates: 341,122,213,117,174,130,70,139,72,22,0,37,0,326,78,512,896,512,896,268,875,118,687,81,494,88,446,117
        objects:
          - person
          - dog

      Z_Front-Right_Mailbox:
        coordinates: 376,117,440,118,447,48,368,43,347,100
        objects:
          - motorcycle

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1
      required_zones:
        - Z_Front-Right_Frontgrass
        - Z_Front-Right_Driveway
        - Z_Front-Right_Mailbox

    record:
      enabled: True
      retain:
        days: 1
        mode: all 
      events:
        retain:
          default: 1
        required_zones:
          - Z_Front-Right_Driveway
          - Z_Front-Right_Frontgrass
          - Z_Front-Right_Mailbox

    motion:
      mask:
        #Clock at bottom
        - 313,469,309,512,189,512,187,465
        # bushes around top
        - 896,0,856,0,739,0,648,0,581,0,538,0,510,0,454,0,458,51,542,54,741,50,832,73,853,120,896,159

  #___________________________________________________________________________________________________

  C_Doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7
          min_area: 1000

    # setting for quality snapshot to double-take
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1

    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 1

  #_________________________________________________________________________

  C_Front-Left:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Left
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front-Left_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    mqtt: # for facerec in deep stack and double take
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    detect:
      width: 1536
      height: 576
      fps: 4
      stationary: 
        interval: 50 
        threshold: 50 

    objects:
      track: #must be defined here to be able to put into zones down below
        - person
        - car
        - motorcycle
        - dog

      filters:
        dog:
          threshold: 0.8
          min_area: 500
          max_area: 15000
        person:
          threshold: 0.7
          min_area: 1000
        car:
          mask:
            - 817,144,762,367,836,576,1536,576,1536,188,1536,0,1097,0,839,0,546,0,496,0,380,0,173,0,0,0,0,206,112,161,194,162,340,122,456,151
          threshold: 0.6
          min_area: 6000

    zones:
      Z_Front-Left_Driveway:
        coordinates: 248,203,127,136,0,211,0,576,375,576,601,576,779,576,781,469,729,315,794,214,690,204,625,196,486,196
        objects:
          - person
          - car
          - motorcycle
          - dog

      Z_Front-Left_Grass:
        coordinates: 988,209,1291,255,1536,407,1536,576,816,576,744,479,705,315,789,199,948,218
        objects:
          - dog
          - person

      Z_Mailbox:
        coordinates: 734,128,874,133,869,247,721,215
        objects:
          - motorcycle

    motion:
      mask:
        #Clock at bottom
        - 317,523,330,576,236,576,231,537
        #bushes at top
        - 134,153,222,141,411,86,597,53,748,56,929,133,1337,189,1478,270,1536,0,1382,0,264,0,116,0,53,0,38,0,0,0,0,186

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 2

    record:
      enabled: True
      retain: #24/7 recordings
        days: 1
        mode: all
      events:
        retain: #objects detect
          default: 1
          mode: active_objects
        required_zones: #but only in these zones
          - Z_Front-Left_Driveway
          - Z_Front-Left_Grass
          - Z_Mailbox

  #_________________________________________________________________________

  C_Left-Side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Left-Side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Left-Side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 896
      height: 512
      fps: 4

    objects: #objects must be here to be listed down below in zones
      track:
        - person
      filters:
        person:
          #          min_area: 5000
          threshold: 0.70

    # setting for quality snapshot to double-take
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    motion:
      mask:
        - 304,110,471,32,504,0,507,0,0,0,0,311

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1

    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 1
  #_________________________________________________________________________

  C_Backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1536
      height: 576
      fps: 4

    objects:
      track:
        - person #must be defined here to be able to put into zones down below
        - dog
        - cat
        - bird
      filters:
        person:
          #          min_area: 5000
          threshold: 0.80

    # setting for quality snapshot to double-take
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    zones:
      Z_Backyard_Pool:
        coordinates: 1536,576,1536,425,1161,224,861,161,645,169,425,325,317,429,214,576
        objects:
          - person

      Z_Trampoline:
        coordinates: 307,214,338,285,405,271,474,246,489,191,482,132,454,85,370,102,291,134
        objects:
          - person

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1
      required_zones:
        - Z_Backyard_Pool
        - Z_Trampoline

    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 1
          mode: active_objects
        required_zones:
          - Z_Backyard_Pool
          - Z_Trampoline

    motion:
      mask:
        #clock
        - 278,576,312,576,313,536,276,536
        #bushes at top
        - 0,0,1536,0,1536,236,1362,181,1179,101,899,52,484,60,0,194
  #___________________________________________________________________________________________________

  C_Patio:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Patio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Patio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 896
      height: 512
      fps: 4

    objects: #objects must be here to be listed down below in zones
      track:
        - person
      filters:
        person:
          mask:
            - 0,355,111,286,58,143,0,139
          min_area: 5000
          threshold: 0.70

    motion:
      mask:
        - 316,512,321,470,178,468,180,512

    # setting for quality snapshot to double-take
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1

    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 1
  #___________________________________________________________________________________________________

  C_Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 640
      height: 360
      fps: 4

    objects: #objects must be here to be listed down below in zones
      track:
        - car

    # setting for quality snapshot to double-take
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1

    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 1
  #___________________________________________________________________________________________________

  C_Right-Side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Right-Side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Right-Side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 896
      height: 512
      fps: 4

    objects: #objects must be here to be listed down below in zones
      track:
        - person
      filters:
        person:
          #          min_area: 5000
          threshold: 0.80

    # setting for quality snapshot to double-take
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

    snapshots: # If this is not defined then you'll just get a 'thumbnail' with your recordings
      enabled: True
      bounding_box: true
      timestamp: false #getting from camera
      crop: false
      retain:
        default: 1

    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 1
#___________________________________________________________________________________________________
```

### Relevant log output

```shell
From HA Logs:

2024-05-30 13:33:28.026 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:33:36.720 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:34:07.479 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:34:47.793 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:36:08.046 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:37:28.424 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:38:48.542 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.2', 5000)]
2024-05-30 13:40:18.733 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:41:49.075 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:43:19.235 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:44:49.441 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:46:30.958 ERROR (MainThread) [aiohttp.server] Error handling request
2024-05-30 13:46:34.782 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:46:34.782 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:46:54.781 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:46:54.781 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:47:54.782 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:47:54.782 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:49:13.782 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:49:13.782 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:52:19.345 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/version:
2024-05-30 13:52:43.340 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/config:
2024-05-30 13:53:13.719 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:54:15.684 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:54:15.684 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:55:15.686 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:55:15.686 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:55:50.685 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:55:50.685 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:56:30.684 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:56:30.685 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
2024-05-30 13:57:30.685 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
2024-05-30 13:57:30.686 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
```

### FFprobe output from your camera

```shell
unable
```

### Frigate stats

```json
Not sure where to find this? Also looking at the errors I think this maybe where the problem is or at lease a symptom.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-1224A, Duo 2 Floodlight POE, RLC-820A, Doorbell POE

### Any other information that may be helpful

I'm running a bare metal HAOS install on an x86 NUC.
