### DISCUSSION TITLE
[Support]: Exports stuck In Progress

### DISCUSSION THREAD

**Discussion by rwlove** [blakeblackshear/frigate#11651] [General Support] [answered]
### Describe the problem you are having

1. Select a 5m time segment to export - storage backend is NFS
2. Observe that the in_progress file is created
3. "in_progress." prefix is never removed and UI shows never-ending 'spinning' icon

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
---
mqtt:
  host: emqx.home.svc.cluster.local
  topic_prefix: frigate
  user: "${FRIGATE_MQTT_USERNAME}"
  password: "${FRIGATE_MQTT_PASSWORD}"

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "info"]
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: info

database:
  path: /data/frigate.db

objects:
  track:
    - person
    - dog
    - car

record:
  enabled: true
  retain:
    days: 182
    mode: all
  events:
    retain:
      default: 365
      mode: active_objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false

go2rtc:
  streams:
    #backyard:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-backyard:554/cam/realmonitor?channel=1?subtype=1
    #backyard_substream:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-backyard:554/cam/realmonitor?channel=1?subtype=0
    pool:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-pool:554/cam/realmonitor?channel=1?subtype=1
    pool_substream:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-pool:554/cam/realmonitor?channel=1?subtype=0
    frontyard:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-frontyard:554/cam/realmonitor?channel=1?subtype=1
    frontyard_substream:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-frontyard:554/cam/realmonitor?channel=1?subtype=0
    office:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-office:554/cam/realmonitor?channel=1?subtype=1
    office_substream:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-office:554/cam/realmonitor?channel=1?subtype=0
    turret:
      - rtsp://admin:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-turret:554/cam/realmonitor?channel=1?subtype=1
    turret_substream:
      - rtsp://admin:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-turret:554/cam/realmonitor?channel=1?subtype=0
    bookshelf:
      - rtsp://wyze:{FRIGATE_WYZECAM_RTSP_PASSWORD}@wyzecam-2/live
    familyroom:
      - rtsp://wyze:{FRIGATE_WYZECAM_RTSP_PASSWORD}@wyzecam-1/live
    kitchen:
      - rtsp://wyze:{FRIGATE_WYZECAM_RTSP_PASSWORD}@wyzecam-3/live
    #backyard2:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@loryta-backyard:554/cam/realmonitor?channel=1?subtype=1
    #backyard2_substream:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@loryta-backyard:554/cam/realmonitor?channel=1?subtype=0
    frontdoor:
      - rtsp://user:p@reolink-frontdoor:554/h264Preview_01_main
    frontdoor_substream:
      - rtsp://user:p@reolink-frontdoor:554/h264Preview_01_sub
    bush:
      - rtsp://user:p@reolink-bush:554/h264Preview_01_main
    bush_substream:
      - rtsp://user:p@reolink-bush:554/h264Preview_01_sub
    backyard:
      - rtsp://user:p@reolink-backyard:554/h264Preview_01_main
    backyard_substream:
      - rtsp://user:p@reolink-backyard:554/h264Preview_01_sub

cameras:
  reolink-backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      width: 1536
      height: 576
  reolink-frontdoor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      width: 640
      height: 480
  reolink-bush:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bush
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bush_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      width: 640
      height: 480
  amcrest-frontyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      width: 640
      height: 480
    motion:
      mask:
        - 510,480,640,480,640,329,640,221,609,222,577,256,572,284,581,321,564,334,530,344,502,326,470,324,416,331,382,348,365,394,370,480,422,480
    zones:
      front-walkway:
        coordinates: 577,366,640,346,640,251,590,265,540,282,460,304,378,326,296,340,259,350,218,351,159,352,108,357,59,334,0,312,0,377,162,417,304,411,326,480,372,480,360,404,510,372
        objects:
          - person
      front-driveway:
        coordinates: 49,174,93,140,136,115,101,123,64,147,21,181,0,197,0,216
        objects:
          - person
          - car
      street:
        coordinates: 301,56,392,59,469,63,568,78,640,95,640,142,547,123,478,117,415,114,340,114,242,113,151,124,0,168,0,110,57,96,128,79,170,73,227,68
        objects:
          - person
          - car
    record:
      events:
        required_zones:
          - front-walkway
          - front-driveway
    snapshots:
      required_zones:
        - front-walkway
        - front-driveway

  amcrest-pool:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      width: 640
      height: 480
    objects:
      filters:
        person:
          mask:        
            - 186,207,201,203,204,186,188,185
            - 580,240,563,233,570,209,585,218
    zones:
      pool:
        coordinates: 539,480,640,480,640,188,556,176,479,172,388,168,321,157,257,152,133,147,74,147,0,135,0,245,0,480,124,480,198,480,266,480,357,480,430,480
        objects:
          - person
          - dog
      greenway:
        coordinates: 150,198,306,198,640,240,640,162,447,141,234,131,67,137,68,215
        objects:
          - person
          - car
    record:
      events:
        required_zones:
          - pool
    snapshots:
      required_zones:
        - pool
```

### Relevant log output

```shell
I'd be happy to share log output, but I didn't see anything relevant.

kubectl -n home logs frigate-0 | grep -i export | grep -vi GET
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink, but I think N/A

### Any other information that may be helpful

1. Running in K8S cluster
2. Exporting previously worked with no known changes to NFS or mounts
3. Everything else works fine
