### DISCUSSION TITLE
[Config Support]: Black video but audio after potential disconnects

### DISCUSSION THREAD

**Discussion by Lallassu** [blakeblackshear/frigate#11662] [Config Support]
### Describe the problem you are having

The recorded video + clips sometimes get black and has only sound for my Unifi G3 cameras. I got 4x TP-Link (Vigi) cameras that works fine and have 4 Unifi G3 cameras that has issues. The unifi cameras has worked for several years before in Frigate. But I haven't used them for a while, that's why I haven't seen this issue until now.

I've seen this https://github.com/blakeblackshear/frigate/issues/7995 and https://github.com/blakeblackshear/frigate/issues/8888 (commented). 

I'm running the latest version of go2rtc.

However, I start to suspect that it might be triggered by random disconnects. Due to physical limitation of the location, I have all 4 unifi cameras connected via a switch to a WiFi extender. And looking at the unifi controller for my AP, I see some random disconnects between the AP and the extender. Not quite sure if that fully correlates. However, during some of these disconnects the video seems fine without any loss (when the video actually works). So that makes me question if the disconnects are the issue, but that is the only difference between the unifi and vigi cameras.

It seems that it sometimes becomes periods of black recording and then starts to work again (without any manual interference). And sometimes it's on the hour (e.g. 11:00), so I wonder if that is related to a new period of a recording so something restarts?

If the disconnects causes these black recordings, any tips for workaround or perhaps a different configuration setting?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args:
  - -hwaccel
  - vaapi
  - -hwaccel_device
  - /dev/dri/renderD128
  global_args:
  - -loglevel
  - error
  output_args:
     detect: -f rawvideo -pix_fmt yuv420p
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
go2rtc:
  streams:
    # TP-Link camera that works good (no connections issues or black video)
    backyard:
    - rtsp://usr:pass@192.168.1.178:554/stream1
    - ffmpeg:backyard#audio=aac
    backyard_sub:
    - rtsp://usr:pass@192.168.1.178:554/stream2
    # One of the unifi cameras that get random black recordings
    storage:
    - rtsp://usr:pass@192.168.1.240:554/s0
    - ffmpeg:storage#audio=aac
    storage_sub:
    - rtsp://usr:pass@192.168.1.240:554/s1


 # One of the working cameras (however down right now, which might be reflected in stats)
 backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/backyard
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/backyard_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    live:
      stream_name: backyard
    objects:
      track:
      - person
      filters:
        person:
          min_area: 600
          min_score: 0.55
          threshold: 0.75
          mask:
          - 614,250,604,360,552,360,577,252
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true

# The one that sometimes records black video with audio.
 storage:
    ffmpeg:
      output_args:
        # record: preset-record-ubiquiti # <-- tested w/o any difference
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/storage
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/storage_sub 
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      fps: 5
    live:
      stream_name: storage
    motion:
      mask:
         - 112,0,122,22,0,21,0,0,0,0
    objects:
      track:
      - person
      filters:
        person:
          min_area: 600
          min_score: 0.55
          threshold: 0.75
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
```

### Relevant log output

```shell
No warning/error or anything related to these events.
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":437,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":451,"pid":404,"process_fps":5.1,"skipped_fps":0.0},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":420,"detection_enabled":1,"detection_fps":3.0,"ffmpeg_pid":10926,"pid":397,"process_fps":5.1,"skipped_fps":0.0},"field":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":413,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":11695,"pid":392,"process_fps":0.0,"skipped_fps":0.0},"frontdoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":408,"detection_enabled":1,"detection_fps":1.0,"ffmpeg_pid":444,"pid":390,"process_fps":5.0,"skipped_fps":0.0},"frontdoor2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":417,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":10771,"pid":393,"process_fps":5.1,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":429,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":10657,"pid":402,"process_fps":5.1,"skipped_fps":0.0},"storage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":424,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":10773,"pid":399,"process_fps":5.1,"skipped_fps":0.0},"street":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":441,"detection_enabled":1,"detection_fps":3.1,"ffmpeg_pid":454,"pid":406,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"91":{"cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"14.2","cpu_average":"17","mem":"0.2"},"99":{"cmdline":"python3 -u -m frigate","cpu":"5.6","cpu_average":"3","mem":"2.7"},"112":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"116":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"366":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.7"},"368":{"cmdline":"frigate.recording_manager","cpu":"3.8","cpu_average":"3","mem":"0.8"},"376":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(69)","cpu":"0.5","cpu_average":"0","mem":"0.1"},"378":{"cmdline":"frigate.detector.coral","cpu":"3.0","cpu_average":"1","mem":"0.8"},"380":{"cmdline":"frigate.output       ","cpu":"1.6","cpu_average":"1","mem":"0.8"},"386":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"387":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"389":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"390":{"cmdline":"frigate.process:frontdoor","cpu":"1.9","cpu_average":"2","mem":"0.8"},"392":{"cmdline":"frigate.process:field","cpu":"0.1","cpu_average":"0","mem":"0.8"},"393":{"cmdline":"frigate.process:frontdoor2","cpu":"1.4","cpu_average":"1","mem":"0.8"},"394":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"397":{"cmdline":"frigate.process:driveway","cpu":"3.0","cpu_average":"1","mem":"0.8"},"399":{"cmdline":"frigate.process:storage","cpu":"1.4","cpu_average":"1","mem":"0.8"},"400":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"402":{"cmdline":"frigate.process:garage","cpu":"1.6","cpu_average":"1","mem":"0.8"},"403":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"404":{"cmdline":"frigate.process:backyard","cpu":"1.3","cpu_average":"1","mem":"0.8"},"406":{"cmdline":"frigate.process:street","cpu":"3.2","cpu_average":"2","mem":"0.8"},"408":{"cmdline":"frigate.capture:frontdoor","cpu":"0.7","cpu_average":"0","mem":"0.7"},"409":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"413":{"cmdline":"frigate.capture:field","cpu":"0.2","cpu_average":"0","mem":"0.8"},"414":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 2275x1280 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"417":{"cmdline":"frigate.capture:frontdoor2","cpu":"0.6","cpu_average":"0","mem":"0.8"},"420":{"cmdline":"frigate.capture:driveway","cpu":"0.5","cpu_average":"0","mem":"0.8"},"424":{"cmdline":"frigate.capture:storage","cpu":"0.6","cpu_average":"0","mem":"0.8"},"429":{"cmdline":"frigate.capture:garage","cpu":"0.7","cpu_average":"0","mem":"0.8"},"437":{"cmdline":"frigate.capture:backyard","cpu":"0.7","cpu_average":"0","mem":"0.7"},"441":{"cmdline":"frigate.capture:street","cpu":"0.6","cpu_average":"0","mem":"0.7"},"444":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.2","cpu_average":"1","mem":"0.6"},"451":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"1","mem":"0.6"},"452":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"454":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/street_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"2","mem":"0.6"},"468":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/frontdoor@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.2"},"476":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.2"},"489":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/street -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/street@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.2"},"490":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/frontdoor?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/79eeb61a9fe8311c183dec44afc694bd","cpu":"2.3","cpu_average":"2","mem":"0.1"},"493":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/backyard?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/2de6b4e353033e294b8a2be8f02702d4","cpu":"1.9","cpu_average":"2","mem":"0.1"},"494":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/street?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/f661b437092f7908e069f5fa9b5a74a5","cpu":"2.0","cpu_average":"2","mem":"0.1"},"10556":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/frontdoor2@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.1"},"10557":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"0.0","cpu_average":"0","mem":"0.1"},"10558":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/storage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/storage@%Y%m%d%H%M%S%z.mp4","cpu":"0.1","cpu_average":"0","mem":"0.1"},"10560":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/frontdoor2?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/574fdbc8229093d703506d2c2feb942f","cpu":"2.4","cpu_average":"2","mem":"0.1"},"10561":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/driveway?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5f402a2ba0414b1503dd4a4436f299bc","cpu":"2.6","cpu_average":"2","mem":"0.1"},"10562":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/storage?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/4c4d5907f9e39838f0a2dee4fc9aa911","cpu":"2.6","cpu_average":"2","mem":"0.1"},"10610":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.1"},"10657":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"3","mem":"0.6"},"10771":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor2_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.1","cpu_average":"3","mem":"0.6"},"10773":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/storage_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"3","mem":"0.6"},"10926":{"cmdline":"ffmpeg -loglevel error -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_sub -r 5 -vf fps=5,scale=640:360 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.1","cpu_average":"3","mem":"0.6"},"11735":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"11745":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/field?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/448409f5821e21aee84ed099d260f770","cpu":"0.0","cpu_average":"0","mem":"0.1"}},"detection_fps":7.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.96,"pid":378}},"gpu_usages":{"amd-vaapi":{"gpu":"100.00%","mem":"41.75%"}},"processes":{"go2rtc":{"pid":91},"logger":{"pid":366},"recording":{"pid":368}},"service":{"last_updated":1717137958,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":56.5,"mount_type":"tmpfs","total":64.0,"used":7.5},"/media/frigate/clips":{"free":214195.0,"mount_type":"ext4","total":2343813.7,"used":2029563.6},"/media/frigate/recordings":{"free":214195.0,"mount_type":"ext4","total":2343813.7,"used":2029563.6},"/tmp/cache":{"free":4750.3,"mount_type":"tmpfs","total":4768.4,"used":18.0}},"temperatures":{},"uptime":1692,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
