### DISCUSSION TITLE
[Support]: Cannot open historical recordings

### DISCUSSION THREAD

**Discussion by rowra44** [blakeblackshear/frigate#11661] [General Support]
### Describe the problem you are having

Opening historical recordings is extremely buggy for me, more like only works very rarely. Please see screenshot attached, how there are "dots", thus recordings/events from the May 26 very clearly. Yet if I try clicking any of them, nothing happens. I have to keep clicking numerous times and then and only then sometimes it'll load. Some days work with "less click spamming", some require straight away like 20+, some will never load.

_(Please note I'm aware I shouldn't try older recordings done before 0.14beta as per #11589 , this ticket is exclusively about recordings recorded with 0.14beta already. I've made the switch to the beta on the 26th, so anything from the 27th is 100% exclusively 0.14beta recordings, yet the same thing is happening.)_

![image](https://github.com/blakeblackshear/frigate/assets/34800035/2ef4e9c6-b9eb-4620-9d8b-0c0a258aa56f)

### Version

0.14.0-b97e274

### Frigate config file

```yaml
# logging settings
#logger:
#  logs:
#    frigate.record.maintainer: debug

# go2rtc streams - all input streams defined here
go2rtc:
  streams:
    driveway:
      - rtsp://admin:xxxxx@10.31.17.101:554/Streaming/Channels/101
    driveway_sub:
      - rtsp://admin:xxxxx@10.31.17.101:554/Streaming/Channels/102
    Szabadka_str_side:
      - rtsp://admin:xxxxx@10.31.17.102:554/Streaming/Channels/101
    Szabadka_str_side_sub:
      - rtsp://admin:xxxxx@10.31.17.102:554/Streaming/Channels/102
    Drava_str_side:
      - rtsp://admin:xxxxx@10.31.17.103:554/Streaming/Channels/101
    Drava_str_side_sub:
      - rtsp://admin:xxxxx@10.31.17.103:554/Streaming/Channels/102
    porch:
      - rtsp://admin:xxxxx@10.31.17.104:554/Streaming/Channels/101
    porch_sub:
      - rtsp://admin:xxxxx@10.31.17.104:554/Streaming/Channels/102
  webrtc:
    candidates:
      - 10.31.17.100:8555
      - stun:8555

# cameras' definitions - inputs are used from go2rtc
cameras:
  driveway:
    enabled: true
    birdseye:
      order: 1
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles: [record]
        - path: rtsp://127.0.0.1:8554/driveway
          roles: [detect]
    motion:
      mask:
        - 0,147,0,0,772,0,765,151

  porch:
    enabled: true
    birdseye:
      order: 2
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch
          roles: [record]
        - path: rtsp://127.0.0.1:8554/porch
          roles: [detect]
    motion:
      mask:
        - 0,137,0,0,735,0,746,140

  Szabadka_str_side:
    enabled: true
    birdseye:
      order: 3
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Szabadka_str_side
          roles: [record]
        - path: rtsp://127.0.0.1:8554/Szabadka_str_side
          roles: [detect]
    motion:
      mask:
        - 0,1440,940,1440,736,707,688,316,688,160,748,134,735,0,0,0
        - 0,72,366,72,369,0,0,0

  Drava_str_side:
    enabled: true
    birdseye:
      order: 4
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Drava_str_side
          roles: [record]
        - path: rtsp://127.0.0.1:8554/Drava_str_side
          roles: [detect]
    motion:
      mask:
        - 1664,545,1516,1440,2560,1440,2560,0,1708,0
        - 0,140,751,141,739,0,0,0

##########################################################################################################################

# AMD iGPU acceleration
ffmpeg:
  hwaccel_args: preset-vaapi

# AI Detection type
# Google Coral
detectors:
  coral:
    type: edgetpu
    device: usb

# Frigate+ model
model:
  path: plus://xxxxx

# detection settings
detect:
  enabled: true
  width: 2560
  height: 1440
  fps: 5
  min_initialized: 5
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 50
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 100
     # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 100

objects:
  track:
    - person
    - cat
    - dog
  # Frigate+ recommended settings as per https://docs.frigate.video/plus/first_model/#step-4-adjust-your-object-filters-for-higher-scores
  filters:
    dog:
      min_score: .70
      threshold: .9
    cat:
      min_score: .70
      threshold: .9
    person:
      min_score: .75
      threshold: .90

review:
  #alerts:
  #  labels:
  #    - person
  #    - dog
  #    - cat
  detections:
    labels:
      - person
      - dog
      - cat

# MQTT (for HomeAssistant)
mqtt:
  enabled: true
  host: 192.168.0.67
  user: frigate
  password: xxxxx

# Birdseye, live and UI settings
birdseye:
  enabled: true
  mode: continuous
  quality: 1
  height: 720
  restream: true

live:
  height: 1440
  quality: 1

ui:
  live_mode: mse

# recording settings
record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: true
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 7
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Recording Export Settings
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.0007*PTS -r 30
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    #objects:
    #  - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 30
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: all
      # Optional: Per object retention days
      #objects:
      #  person: 15
  preview:
    quality: very_high
  

# snapshots config
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
    #objects:
      #person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

# telemetry settings
telemetry:
  stats:
    amd_gpu_stats: true
    network_bandwidth: true
```

### Relevant log output

```shell
Nothing relevant, no errors.
```

### FFprobe output from your camera

```shell
Irrelevant, this ticket is about past recordings.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-
