### DISCUSSION TITLE
[Support]: FFMPEG memory leak with restreaming

### DISCUSSION THREAD

**Discussion by Samywamy10** [blakeblackshear/frigate#11676] [General Support] [answered]
### Describe the problem you are having

Every ~12 hours memory usage starts to dramatically climb which leads to my Frigate container running out of memory, which leads to CPU usage being pinned to 100% and Frigate dies.

The strange part is, despite errors in the logs, that object detection, recording and even HomeKit viewing all work fine.

Diving further into this issue, I can see that the FFMPEG process for my Reolink E1 Pro camera is what’s taking up all the memory.

I have restreaming set up for this camera for two reasons:
1) I didn’t want to make several connections to the camera
2) I need to re-encode the video at a smaller resolution (~1920x1080) as higher resolutions can’t be casted to Google Homes

I also want to know if there is a better way to achieve (2) as I’m still making two connections to the camera. It doesn’t look like I can use one go2rtc stream as an input to another.

(Before anyone asks, the camera is in the bathroom to watch our cats, and the camera is very obvious. Home Assistant uses the PTZ to point it at the wall when it detects people in the bathroom)

Very high memory usage for FFMPEG:
![IMG_0071](https://github.com/blakeblackshear/frigate/assets/1314053/c397759a-cf03-4894-9d83-84f2fd972c50)

Proxmox screenshot:
![IMG_0072](https://github.com/blakeblackshear/frigate/assets/1314053/a45b14f8-1df6-4086-bd89-ce79513586f4)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.86.58
  user: username
  password: password
  port: 1883

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      mode: active_objects
      objects:
        person: 7
        car: 7
    pre_capture: 5
    post_capture: 5

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    bathroom_hd:
    - "rtsp://reolinkusername:reolinkpassword@192.168.86.36:554/h264Preview_01_main"
    bathroom: 
    - "ffmpeg:rtsp://reolinkusername: reolinkpassword@192.168.86.36:554/h264Preview_01_main#video=h264#width=1920#height=1080"
  webrtc:
    candidates:
    - 192.168.86.18:8554
    - 192.168.86.18:8555
    - stun:8555
  homekit:
    bathroom:
      name: Bathroom
      pairings:
      - client_id=XX
      - client_id=XX
cameras:
  bathroom:
    enabled: true
    snapshots:
      enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.86.18:8554/bathroom
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.86.18:8554/bathroom_hd
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: bathroom_hd
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
      - person
      - cat
    onvif:
      host: 192.168.86.36
      port: 8000
      user: reolinkusername
      password: reolinkpassword
    motion:
      mask:
      - 1280,0,1280,41,834,43,838,0 #clock
      - 44,0,297,0,355,311,77,191 #door
      - 613,378,632,378,630,403,605,399 #water fountain
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          mode: active_objects
          objects:
            person: 0
            cat: 7
        pre_capture: 1
        post_capture: 1
```

### Relevant log output

```shell
2024-06-01 12:18:25.458151756  [2024-06-01 12:18:25] ffmpeg.bathroom.record         ERROR   : rtsp://192.168.86.18:8554/bathroom_hd: Invalid data found when processing input
2024-06-01 12:18:25.459896513  [2024-06-01 12:18:25] watchdog.bathroom              INFO    : Terminating the existing ffmpeg process...
2024-06-01 12:18:25.461327515  [2024-06-01 12:18:25] watchdog.bathroom              INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-01 12:18:55.653827518  [2024-06-01 12:18:55] ffmpeg.bathroom.record         ERROR   : [segment @ 0x5b549f1d30c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2024-06-01 12:18:55.653831877  [2024-06-01 12:18:55] ffmpeg.bathroom.record         ERROR   : rtsp://192.168.86.18:8554/bathroom_hd: Connection timed out
2024-06-01 12:18:55.653833362  [2024-06-01 12:18:55] watchdog.bathroom              INFO    : Terminating the existing ffmpeg process...
2024-06-01 12:18:55.653834593  [2024-06-01 12:18:55] watchdog.bathroom              INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-01 12:19:25.261791111  [2024-06-01 12:19:25] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/bathroom@20240601121908+1000.mp4
2024-06-01 12:19:35.268155249  [2024-06-01 12:19:35] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/bathroom@20240601121921+1000.mp4
2024-06-01 12:19:35.760478651  [2024-06-01 12:19:35] ffmpeg.bathroom.record         ERROR   : [segment @ 0x5e63ca9fb0c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2024-06-01 12:19:35.868246017  [2024-06-01 12:19:35] ffmpeg.bathroom.record         ERROR   : [rtsp @ 0x5e63ca9d9f00] RTP: PT=60: bad cseq 5e75 expected=3d87
2024-06-01 12:19:35.868704670  [2024-06-01 12:19:35] ffmpeg.bathroom.record         ERROR   : [rtsp @ 0x5e63ca9d9f00] RTP: PT=61: bad cseq e254 expected=4867
2024-06-01 12:19:35.869076720  [2024-06-01 12:19:35] ffmpeg.bathroom.record         ERROR   : [rtsp @ 0x5e63ca9d9f00] RTP: PT=61: bad cseq 7755 expected=e25f
2024-06-01 12:19:35.869601140  [2024-06-01 12:19:35] ffmpeg.bathroom.record         ERROR   : rtsp://192.168.86.18:8554/bathroom_hd: Connection timed out
2024-06-01 12:19:35.870217321  [2024-06-01 12:19:35] watchdog.bathroom              INFO    : Terminating the existing ffmpeg process...
2024-06-01 12:19:35.871823009  [2024-06-01 12:19:35] watchdog.bathroom              INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-01 12:19:45.968715516  [2024-06-01 12:19:45] ffmpeg.bathroom.record         ERROR   : rtsp://192.168.86.18:8554/bathroom_hd: Invalid data found when processing input
2024-06-01 12:19:45.968719676  [2024-06-01 12:19:45] watchdog.bathroom              INFO    : Terminating the existing ffmpeg process...
2024-06-01 12:19:45.968721148  [2024-06-01 12:19:45] watchdog.bathroom              INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-01 12:20:51.261414053  [2024-06-01 12:20:51] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for letterboxes. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-01 12:20:59.465155375  [2024-06-01 12:20:59] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for letterboxes. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-01 12:21:09.466465563  [2024-06-01 12:21:09] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for letterboxes. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-01 12:21:14.968187120  [h264 @ 0x726f10ce0840] cabac decode of qscale diff failed at 85 49
2024-06-01 12:21:14.968513367  [h264 @ 0x726f10ce0840] error while decoding MB 85 49, bytestream 156319
2024-06-01 12:21:19.567340554  [2024-06-01 12:21:19] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for letterboxes. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
   "cameras":{
      "bathroom":{
         "audio_dBFS":0.0,
         "audio_rms":0.0,
         "camera_fps":1.9,
         "capture_pid":381,
         "detection_enabled":1,
         "detection_fps":0.0,
         "ffmpeg_pid":659,
         "pid":366,
         "process_fps":1.9,
         "skipped_fps":0.0
      },
   },
   "cpu_usages":{
      "1":{
         "cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "15":{
         "cmdline":"s6-supervise s6-linux-init-shutdownd",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "17":{
         "cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "24":{
         "cmdline":"s6-supervise frigate",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "25":{
         "cmdline":"s6-supervise s6rc-oneshot-runner",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "26":{
         "cmdline":"s6-supervise nginx-log",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "27":{
         "cmdline":"s6-supervise go2rtc",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "28":{
         "cmdline":"s6-supervise go2rtc-log",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "29":{
         "cmdline":"s6-supervise frigate-log",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "30":{
         "cmdline":"s6-supervise go2rtc-healthcheck",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "31":{
         "cmdline":"s6-supervise s6rc-fdholder",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "32":{
         "cmdline":"s6-supervise nginx",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "41":{
         "cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "42":{
         "cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "80":{
         "cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "81":{
         "cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "82":{
         "cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "92":{
         "cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
         "cpu":"1.4",
         "cpu_average":"0",
         "mem":"0.2"
      },
      "109":{
         "cmdline":"python3 -u -m frigate",
         "cpu":"1.8",
         "cpu_average":"1",
         "mem":"1.5"
      },
      "110":{
         "cmdline":"bash ./run.user go2rtc-healthcheck",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "117":{
         "cmdline":"nginx: master process nginx",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "144":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "145":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "146":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "147":{
         "cmdline":"nginx: worker process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "148":{
         "cmdline":"nginx: cache manager process",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      },
      "295":{
         "cmdline":"frigate.logger       ",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.6"
      },
      "297":{
         "cmdline":"frigate.recording_manager",
         "cpu":"2.2",
         "cpu_average":"5",
         "mem":"1.0"
      },
      "305":{
         "cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)",
         "cpu":"0.3",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "306":{
         "cmdline":"frigate.detector.ov  ",
         "cpu":"29.8",
         "cpu_average":"29",
         "mem":"1.7"
      },
      "308":{
         "cmdline":"frigate.output       ",
         "cpu":"0.6",
         "cpu_average":"0",
         "mem":"0.8"
      },
      "321":{
         "cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "366":{
         "cmdline":"frigate.process:bathroom",
         "cpu":"0.6",
         "cpu_average":"0",
         "mem":"0.9"
      },
      "381":{
         "cmdline":"frigate.capture:bathroom",
         "cpu":"0.5",
         "cpu_average":"0",
         "mem":"0.9"
      },
      "659":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.86.18:8554/bathroom -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
         "cpu":"1.2",
         "cpu_average":"1",
         "mem":"0.4"
      },
      "665":{
         "cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.86.36:554/h264Preview_01_main -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -pix_fmt:v yuv420p -an -vf scale=1920:1080 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/397c353cb2a44ff7eac784760432915e",
         "cpu":"14.9",
         "cpu_average":"15",
         "mem":"0.7"
      },
      "1531":{
         "cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.86.18:8554/bathroom_hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/bathroom@%Y%m%d%H%M%S%z.mp4",
         "cpu":"0.8",
         "cpu_average":"0",
         "mem":"0.1"
      },
      "2081":{
         "cmdline":"sleep 30s",
         "cpu":"0.0",
         "cpu_average":"0",
         "mem":"0.0"
      }
   },
   "detection_fps":4.0,
   "detectors":{
      "ov":{
         "detection_start":1717208578.857912,
         "inference_speed":247.34,
         "pid":306
      }
   },
   "gpu_usages":{
      "intel-vaapi":{
         "gpu":"13.32%",
         "mem":"-%"
      }
   },
   "processes":{
      "go2rtc":{
         "pid":92
      },
      "logger":{
         "pid":295
      },
      "recording":{
         "pid":297
      }
   },
   "service":{
      "last_updated":1717208580,
      "latest_version":"0.13.2",
      "storage":{
         "/dev/shm":{
            "free":228.8,
            "mount_type":"tmpfs",
            "total":256.0,
            "used":27.2
         },
         "/media/frigate/clips":{
            "free":2116628.1,
            "mount_type":"cifs",
            "total":7416765.1,
            "used":5300137.0
         },
         "/media/frigate/recordings":{
            "free":2116628.1,
            "mount_type":"cifs",
            "total":7416765.1,
            "used":5300137.0
         },
         "/tmp/cache":{
            "free":239191.9,
            "mount_type":"overlay",
            "total":256946.1,
            "used":4631.0
         }
      },
      "temperatures":{
         
      },
      "uptime":487,
      "version":"0.13.2-6476f8a"
   }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink E1 Pro
