### DISCUSSION TITLE
[Support]: Error: duplicate column name: score

### DISCUSSION THREAD

**Discussion by belfour** [blakeblackshear/frigate#11681] [General Support]
### Describe the problem you are having

Existing setup working yesterday appears to have failed overnight.  

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2

rtmp:
  enabled: False

snapshots:
  enabled: True
  retain:
    default: 21
    objects:
      person: 21
      car: 0
      bear: 21
      dog: 21
      cat: 21

objects:
  track:
    - person
    - car
    - bear
    - dog
    - cat

go2rtc:
  streams:
    doorbell:
      - 'rtsp://<ip>/cam/realmonitor?channel=1&subtype=0#backchannel=0'
      - 'ffmpeg:doorbell#audio=opus'

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: 'rtsp://<ip address>/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            - record
      hwaccel_args:
        - -c:v
        - h264_cuvid
    detect:
      enabled: True
      width: 1920
      height: 1080
    record:
      enabled: True
      retain:
        days: 16
        mode: all
      events:
        required_zones:
          - doorbell_street
        retain:
          default: 16
          mode: active_objects
        pre_capture: 1
        post_capture: 2
    zones:
      doorbell_street:
        coordinates: 1920,0,1920,644,1719,678,894,681,0,618,0,0
        objects:
          - person
          - dog
          - cat
          - car
```

### Relevant log output

```shell
[+] Running 1/0
 \u2714 Container frigate  Created                                                                                                              frigate  | 2024-06-01 10:39:44.510423571  [2024-06-01 10:39:44] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-06-01 10:39:44.676697732  [2024-06-01 10:39:44] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-06-01 10:39:44.704943003  [2024-06-01 10:39:44] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
frigate  | 2024-06-01 10:39:44.705117489  [2024-06-01 10:39:44] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
frigate  | 2024-06-01 10:39:44.707660792  duplicate column name: score
frigate  | 2024-06-01 10:39:44.708004634  [2024-06-01 10:39:44] peewee_migrate.logs            ERROR   : Migration failed: 014_event_updates_for_fp
```

### FFprobe output from your camera

```shell
App is crashing before it gets to the camera
```

### Frigate stats

```json
App is crashing, can't get to this?
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

amcrest
