### DISCUSSION TITLE
Beta 2 does not start without ipv6

### DISCUSSION THREAD

**Discussion by Lukino2000** [blakeblackshear/frigate#11684] [General Support]
as per title in my host i disabled ipv6. after upgrade to beta 2 docker logs loops on this:

```
2024-06-01 21:43:16.798162323  [INFO] Starting NGINX...
2024-06-01 21:43:16.825700420  2024/06/01 23:43:16 [emerg] 4457#4457: socket() [::]:80 failed (97: Address family not supported by protocol)
2024-06-01 21:43:16.825705488  nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2024-06-01 21:43:16.831632549  [INFO] Service NGINX exited with code 1 (by signal 0)
```

is there any env variable to disable ipv6 use on frigate docker image?

**Comment by blakeblackshear** [comment]
Everything I can find about this issue is that it's only an issue if you disable ipv6 on the host which isn't very common. You can simply not use ipv6 instead of disabling it. We had ipv6 support in beta 1 as well. Does beta 1 work?

**Reply by Lukino2000** [reply]
I did not tried beta 1. I revert back to 0.13 and i'm using it with ipv6 disabled on host.

i prefer not enabling ipv6 if possible. 

Furthermore as I can understand from [here](https://docs.docker.com/config/daemon/ipv6/) ipv6 is still not supported on windows.

I remember seeing several docker image with an environment variable to disable ipv6 use on docker container... but cannot find one at the moment, but still searching...

do you think is possible implementing an environment variable to disable ipv6 on frigate image?

**Reply by blakeblackshear** [reply]
You can always use a bind mount to overwrite the nginx config. We will see how many other users report this issue, since we had several users request ipv6 support. There are many other self hosted apps with open issues like this, so you are going to have to implement work arounds for many apps.

**Reply by cchance27** [reply]
ya sorta figured it isn't a common case but does come up, if it stays this way might want to add a note to the docs that IPv6 is required by default and you need to replace all the [::] with 0.0.0.0 in the nginx.conf and tls.conf if you really want it to work on a disabled host.

even if technically not a "bug" it's definitely a breaking change for a subset of users, so should be noted if left this way. 

That said it almost feels like a build step could avoid this issue... check if ipv6 is supported on host if not just to a sed to replace [::] with 0.0.0.0 in those 2 files would likely fix it for the few with the issue.

**Reply by ondrejmo** [reply]
I am gonna leave here a snippet with the `[::]` replacement for Frigate deployed in Kubernetes:

```yaml
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate

spec:
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        core.coral: "true"
      initContainers:
        - name: frigate-init
          image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2
          command: [ /bin/bash, -c ]
          args:
            - >
              cp -r /usr/local/nginx/conf/* /override/;
              sed 's/\[::\]:443\ ipv6only=off/0.0.0.0:443/g' /usr/local/nginx/conf/tls.conf | tee /override/tls.conf;
              sed 's/\[::\]:80\ ipv6only=off/0.0.0.0:80/g' /usr/local/nginx/conf/nginx.conf | sed 's/\[::\]:8080\ ipv6only=off/0.0.0.0:8080/g' | sed 's/\[::\]:5000\ ipv6only=off/0.0.0.0:5000/g' | tee /override/nginx.conf;
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
          volumeMounts:
            - name: override
              mountPath: /override
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2
          resources:
            limits:
              gpu.intel.com/i915: "1"
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            privileged: true
          ports:
            - name: rtmp
              containerPort: 1935
            - name: http
              containerPort: 5000
            - name: rtsp
              containerPort: 8554
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          envFrom:
            - secretRef:
                name: frigate-config
          volumeMounts:
            - name: override
              mountPath: /usr/local/nginx/conf
            - name: configmap
              mountPath: /config/config.yml
              subPath: config.yml
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: coral
              mountPath: /dev/bus/usb
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: configmap
          configMap:
            name: frigate-config
        - name: config
          persistentVolumeClaim:
            claimName: frigate-config
        - name: media
          persistentVolumeClaim:
            claimName: frigate-data
        - name: coral
          hostPath:
            path: /dev/bus/usb
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: override
          emptyDir: {}
```
