### DISCUSSION TITLE
[Config Support]:  Zone where i do not want an event.

### DISCUSSION THREAD

**Discussion by anthopocket** [blakeblackshear/frigate#11698] [Config Support]
### Describe the problem you are having

hi,

i have a problem with a zone don't want event beacause it's the street.

![image](https://github.com/blakeblackshear/frigate/assets/62506538/04c6b49d-cf5b-4951-a0fe-28ea832b1eea)

in yellow, this is the zone where I do not want an event

"entrée" ( config) is the zone where i have event. it's ok.

thanks you for you help

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: admin
  password: anthony
  host: 192.168.1.59
  port: 1883

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person

logger:
  default: info
  logs:
    frigate.mqtt: info

birdseye:
  enabled: false
  mode: continuous
  width: 720
  height: 360
  quality: 4

record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects
#      mode : motion

 
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 15

detect:
  fps: 30
  width: 1280
  height: 720

go2rtc:
  streams:
    rtsp_OUEST:
    - rtsp://admin:ABCDE12345@192.168.1.65/Streaming/Channels/101
    - ffmpeg:rtsp_OUEST#audio=opus

    rtsp_INTERPHONE:
    - rtsp://admin:ABCDE12345@192.168.1.231/Streaming/Channels/101
    - ffmpeg:rtsp_INTERPHONE#audio=opus
    
    rtsp_EST:
    - rtsp://admin:ABCDE12345@192.168.1.94/Streaming/Channels/101
    - ffmpeg:rtsp_EST#audio=opus

    rtsp_SALON:
    - rtsp://admin:NIHVTP@192.168.1.80/Streaming/Channels/101
    - ffmpeg:rtsp_SALON#audio=opus

cameras:
  OUEST:
    ffmpeg:
      inputs : 
      - path: rtsp://192.168.1.20:8554/rtsp_OUEST
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
        - audio
    record:
     events:
      required_zones:
        - entree
    snapshots:
     required_zones:
      - entree
    zones:
     entree:
      coordinates: 0,720,1280,720,1280,538,1280,286,918,169,761,304,391,465,0,495,0,506,0,590
```

### Relevant log output

```shell
no it's only config
```

### Frigate stats

```json
cpu
P-ID	Inference Speed	CPU %	Memory %
450	40.08 ms	0.0%	0.2%
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
it's not clear what the problem is, are you getting events when you don't want to? if so then we need to see the zone as created in the frigate UI and we need to see an example of a detection

**Reply by anthopocket** [reply]
hi

for exemple my son is in the zone no Event

![snapshot](https://github.com/blakeblackshear/frigate/assets/62506538/bee7e48b-fe89-4864-b1ee-d424bf593139)

an over event in the street
![image](https://github.com/blakeblackshear/frigate/assets/62506538/89efbad2-9f1b-4d57-bef9-7487734cca94)


this is a street, i have a lot of event.

i want a event only on the red zone

![image](https://github.com/blakeblackshear/frigate/assets/62506538/c47558d7-ee5e-4048-966d-a6dbad22e5e6)

**Reply by NickM-27** [reply]
the snapshot that is chosen is not necessarily the moment that the object entered the zone.

**Reply by anthopocket** [reply]
moment entered on the zone

![image](https://github.com/blakeblackshear/frigate/assets/62506538/4901320f-d648-4439-8d78-6936bcd2d48e)

**Reply by NickM-27** [reply]
that is not the moment it entered the zone, if it was there would be a yellow box in the bottom of the object. 

![image](https://github.com/blakeblackshear/frigate/assets/14866235/8ae0888b-fa96-4907-a408-94af3fc1e5f5)

**Reply by anthopocket** [reply]
it's a probléme 

the event is in never zone

**Reply by anthopocket** [reply]
in my event zone it's ok
for exemple

![image](https://github.com/blakeblackshear/frigate/assets/62506538/772732c1-80e4-4373-b48c-b971321d5186)

**Reply by NickM-27** [reply]
then it seems the config put above is not correct, required_zones needs to be set

**Reply by anthopocket** [reply]
sorry i don't undernet.

Required_zone have set to "entree"
```
cameras:
  OUEST:
    ffmpeg:
      inputs : 
      - path: rtsp://192.168.1.20:8554/rtsp_OUEST
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
        - audio
    record:
     events:
      required_zones:
        - entree
    snapshots:
     required_zones:
      - entree
    zones:
     entree:
      coordinates: 0,720,1280,720,1280,538,1280,286,918,169,761,304,391,465,0,495,0,506,0,590
```

do you have an example?


sorry for my english...
