### DISCUSSION TITLE
[Support]: HASS go2rtc addon - Audio within Frigate card.

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#11693] [General Support]
### Describe the problem you are having

Hey,

I've moved my setup from go2rtc within Frigate to the go2rtc addon, primarily to ensure I'm regularly on the latest version of go2rtc. I've got all my cameras working fine but I'm having trouble with audio. Within my Frigate config I'm using the link "[rtsp] for MP4 recording (Hass or Frigate) / codecs: H264, H265, AAC" (e.g. rtsp://192.168.1.1:8554/driveway?mp4) as the cameras path. But when I view the cameras frigate card I can't seem to get the video player audio controls to appear like I used to. I can confirm that within go2rtc streams I do get these controls. Any idea what I might be missing?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
driveway:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.1:8554/driveway?mp4
        roles:
        - record
        - detect
    motion:
      mask: 0,73,632,73,637,0,0,0
    objects:
      track:
      - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        retain:
          default: 7
```

### Relevant log output

```shell
No log issues in "info".
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo
