### DISCUSSION TITLE
[Support]: 0.14.0 beta 2 "no frames received" + "unable to keep with with recording segments"

### DISCUSSION THREAD

**Discussion by huperaisan** [blakeblackshear/frigate#11705] [General Support]
### Describe the problem you are having

Since trying out the second beta, my Frigate stops displaying any camera feeds after a few hours with the message "no frames received". The logs have a string of errors from frigate.record.maintainer saying "unable to keep with with recording segments".

I'm running off an SSD on RP4 with Coral (4 cameras), which I know isn't the most powerful config, but it has worked well on 0.13.2. I'm wondering if it might have something to do with the fact that it now automatically records all object detections, whereas previously I would only see object detections in specifically defined zones. Could that be causing extra load and leading to the observed error? There are a lot more object detections under the "review" section of the UI than what I used to have under "events". Is there a way to go back to the previous behaviour, where it only records objects detected within defined zones? Failing that, is there a way to stay on version 0.13.2? I assume this is in docker-compose.yml, where I currently have it set to "ghcr.io/blakeblackshear/frigate:stable".

Note: the config file is from 0.13.2. I no longer have access to the logs because I've rolled back from the beta.

### Version

0.14.0 beta 2

### Frigate config file

```yaml
mqtt:
  host: 
  port: 
  user: 
  password: 

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  retain:
    default: 2

ffmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration

birdseye:
  enabled: True
  mode: continuous

cameras:
  hallway:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
    objects:
        track: 
        #  - car
        #  - person
          - cat
        filters:
          cat:
            threshold: 0.70

    detect:
      enabled: True
      width: 640
      height: 360
      fps: 10
      max_disappeared: 30
      stationary:
        interval: 10
        threshold: 50
    
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects
      events:
        retain:
          default: 2
          mode: active_objects

    motion:
      mask:
        - 640,0,550,0,405,137,529,360,640,360
        - 128,0,232,0,232,22,128,22
      improve_contrast: True
    
    zones:
      zbottom:
       coordinates: 144,360,158,186,418,218,471,360
      ztop:
        coordinates: 197,0,164,182,410,212,377,0

  frontdoor:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
          
    objects:
        track: 
          - car
          - person
          - suitcase
        filters:
          car:
            threshold: 0.70
            min_area: 750
          person:
            threshold: 0.70

    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    
    record:
      enabled: true
      retain:
        days: 2
        mode: active_objects
      events:
        required_zones:
          - zdriveway
        retain:
          default: 2
          mode: active_objects

    snapshots:
      required_zones:
        - zdriveway
    
    motion:
      mask:
        - 539,360,613,360,613,333,538,335
        - 640,0,640,132,0,134,0,0

    zones:
      zdriveway:
        coordinates: 513,287,499,303,0,306,0,360,640,360,640,282

  backyard:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
    objects:
        track: 
          - person

    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    
    record:
      enabled: true
      retain:
        days: 2
        mode: active_objects
      events:
        required_zones:
          - zyard
        retain:
          default: 2
          mode: active_objects

    snapshots:
      required_zones:
        - zyard

    motion:
      mask:
        - 640,0,297,0,290,176,640,179
        - 555,360,620,360,620,336,557,336
    
    zones:
      zyard:
       coordinates: 0,360,0,274,640,252,640,360

  garage:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
    objects:
        track: 
          - car
          - person
    
    motion:
      mask:
        - 128,0,232,0,232,22,128,22

    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects
      events:
        required_zones:
          - zentry
        retain:
          default: 2
          mode: active_objects
    
    zones:
      zentry:
       coordinates: 318,336,318,360,0,360,0,238,640,229,640,334
```

### Relevant log output

```shell
frigate.record.maintainer Message Unable to keep up with recording segments in cache
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.3-1+rpt4 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=1+rpt4 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --disable-mmal --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sand --enable-sdl2 --disable-sndio --enable-libjxl --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

tp-link tapo c100
