### DISCUSSION TITLE
Sonoff Camera GK-200MP2-B

### DISCUSSION THREAD

**Discussion by huuub** [blakeblackshear/frigate#1170] [Ask A Question]
Does anybody had this camera working in Frigate?
And what config are you using?

**Comment by osos** [comment]
I use the Sonoff-Hack: https://github.com/roleoroleo/sonoff-hack

This is my current camera settings:

```
cameras:
  skur:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pwd>@192.168.1.5/av_stream/ch1
          roles:
            - detect
        - path: rtsp://<user>:<pwd>@192.168.1.5/av_stream/ch0
          roles:
#            - detect
            - rtmp
            - clips
            - record
      hwaccel_args: []
#        - -hwaccel
#        - vaapi
#        - -hwaccel_device
#        - /dev/dri/renderD128
#        - -hwaccel_output_format
#        - yuv420p
    width: 640
    height: 360
    fps: 5
```
