### DISCUSSION TITLE
[Support]: recording zoomed/cropped when changing resolution on camera from 2k to 4k

### DISCUSSION THREAD

**Discussion by andrewpwade** [blakeblackshear/frigate#11713] [General Support] [answered]
### Describe the problem you are having

Hi,

If I change my CCTV from 2560x1440 to 3840x2160 (same aspect ratio), the recordings in Frigate are "zoomed", with the right and bottom cropped out.

Thanks!

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi

logger:
  default: info
  logs:
    frigate.record.maintainer: debug
mqtt:
  enabled: true
  host: localhost
  client_id: frigate

detect:
  enabled: true

objects:
  track:
  - person
  - dog
  - bird
  - motorcycle
  - bicycle
  - cat

go2rtc:
  streams:
    Rear:
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.135:554/Streaming/Channels/101

cameras:
  Rear:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.135:554/Streaming/Channels/101
        hwaccel_args: preset-vaapi
        roles:
        - record
      - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.135:554/Streaming/Channels/102
        hwaccel_args: preset-vaapi
        roles:
        - detect

    motion:
      #contour_area: 30
      mask:
      - 826,664,832,720,1227,720,1210,659
      - 1280,0,1280,125,1123,0
record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 10
    post_capture: 60
    retain:
      mode: all
      default: 30
  export:
    timelapse_args: -qp 38 -vf setpts=0.04*PTS -r 30

snapshots:
  timestamp: true
  enabled: true


birdseye:
  enabled: true
  mode: continuous

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

#model:
#  path: /models/tf2_ssd_mobilenet_v2_coco17_ptq_edgetpu.tflite
#  width: 300
#  height: 300
```

### Relevant log output

```shell
No logging happens when I change the res
```

### FFprobe output from your camera

```shell
with 4k res:

ffprobe version 5.1.4-0+deb12u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x57347d9f2700] max delay reached. need to consume packet
[rtsp @ 0x57347d9f2700] RTP: missed 266 packets
[h264 @ 0x57347d9f7400] left block unavailable for requested intra mode
[h264 @ 0x57347d9f7400] error while decoding MB 0 16, bytestream 448190
[h264 @ 0x57347d9f7400] concealing 28609 DC, 28609 AC, 28609 MV errors in I frame
[rtsp @ 0x57347d9f2700] max delay reached. need to consume packet
[rtsp @ 0x57347d9f2700] RTP: missed 515 packets
[rtsp @ 0x57347d9f2700] max delay reached. need to consume packet
[rtsp @ 0x57347d9f2700] RTP: missed 16 packets
[rtsp @ 0x57347d9f2700] max delay reached. need to consume packet
[rtsp @ 0x57347d9f2700] RTP: missed 42 packets
[h264 @ 0x57347d9f7400] concealing 29231 DC, 29231 AC, 29231 MV errors in P frame
[rtsp @ 0x57347d9f2700] max delay reached. need to consume packet
[rtsp @ 0x57347d9f2700] RTP: missed 277 packets
Input #0, rtsp, from 'rtsp://...':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.050000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 15 fps, 20 tbr, 90k tbn
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision DS-2CD2385G1-I
