### DISCUSSION TITLE
[Bug]: Cannot review motion in 0.14.0-beta2

### DISCUSSION THREAD

**Discussion by luke3butler** [blakeblackshear/frigate#11729] [Report a Bug]
### Describe the problem you are having

When I go to the review screen and click on "Motion", I get an infinite spinner.   
Everything else appears to work so far, including reviewing events.

### Steps to reproduce

Upgraded from latest stable 0.13.2 to 0.14.0-beta2 and did a reboot.

The following error occurs in the logs whenever I navigate to "Motion".

```
2024-06-03 20:34:52.631901330  /usr/local/lib/python3.9/dist-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
2024-06-03 20:34:52.631904343    return arr.astype(dtype, copy=True)
```

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  host: redacted
  port: 1883
  user: frigate
  password: redacted

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    wc_maple:
      - ffmpeg:rtsp://redacted:8554/1080p?video&audio=aac#video=copy#audio=copy
      - ffmpeg:wc_maple#video=copy#audio=opus

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - mouse
      - dog
      - cat
      - bird
    retain:
      default: 3
      mode: motion
      objects:
        person: 15
        mouse: 15
        dog: 15

snapshots:
  enabled: true

cameras:
  wc_maple:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/wc_maple
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080

    motion:
      mask:
        - 1390,1015,1873,1015,1871,1058,1388,1059

version: 0.14
```

### Relevant log output

```shell
2024-06-03 20:34:52.631901330  /usr/local/lib/python3.9/dist-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
2024-06-03 20:34:52.631904343    return arr.astype(dtype, copy=True)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Generic

### Any other information that may be helpful

Things I've tried.  
- Restart several times
- Delete ALL footage, set record->sync_recordings to `true`, restart, trigger events and motion (and verify that they were recorded to disk)

Appears like it might be similar to #11593

Willing to provide any additional information needed.

**EDIT:** I also just noticed this in the logs on each startup, so maybe it's not successfully deleting the old recordings? I think I'm giving it enough time (latest uptime was around 15 minutes).

```
2024-06-03 20:57:36.807371046  [2024-06-03 20:57:36] frigate.record.util            INFO    : Deleting 157 recording DB entries with missing files
```
