### DISCUSSION TITLE
[Bug]: Blinking/Dropping Feeds in Live View

### DISCUSSION THREAD

**Discussion by jasonmh37** [blakeblackshear/frigate#11732] [Report a Bug] [answered]
### Describe the problem you are having

I am having difficulty watching live view. Every 15 secs or so, the camera feeds will blink black and then restart. Also there are frequent times the camera feed won't start or will freeze.

### Steps to reproduce

Open Live view.

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream

go2rtc:
  streams:
    Outdoor_Front:
      - rtsp://ZZZ:???@192.168.100.10:11002/Streaming/Channels/101/
    Outdoor_Zoom:
      - rtsp://ZZZ:???@192.168.100.2:554/Streaming/Channels/101/
    Outdoor_Bullet:
      - rtsp://ZZZ:???@192.168.125.1:554/Streaming/Channels/101/
    Living_room:
      - rtsp://ZZZ:???@192.168.100.1:8554/video1_unicast

detect:
  fps: 6
  stationary:
    interval: 50
    threshold: 50

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - cat

motion:
  threshold: 25

record:
  enabled: true
  retain:
    days: 10
    mode: motion
  events:
    pre_capture: 4
    post_capture: 3
    objects:
      - person
      - car
      - bicycle
      - motorcycle
      - dog
      - cat
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      mode: motion

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 10


cameras:
  Outdoor_Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ZZZ:???@192.168.100.10:11002/Streaming/Channels/102/ # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://ZZZ:???@192.168.100.10:11002/Streaming/Channels/101/ # <----- Update for your camera
          roles:
            - record

  Outdoor_Zoom: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ZZZ:???@192.168.100.2:554/Streaming/Channels/102/ # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://ZZZ:???@192.168.100.2:554/Streaming/Channels/101/ # <----- Update for your camera
          roles:
            - record

  Outdoor_Bullet: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ZZZ:???@192.168.125.1:554/Streaming/Channels/102/ # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://ZZZ:???@192.168.125.1:554/Streaming/Channels/101/ # <----- Update for your camera
          roles:
            - record

  Living_room: # <------ Name the camera
    detect:
      fps: 4
    ffmpeg:
      inputs:
        - path: rtsp://ZZZ:???@192.168.100.1:8554/video2_unicast # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://ZZZ:???@192.168.100.1:8554/video1_unicast # <----- Update for your camera
          roles:
            - record


version: 0.14
```

### Relevant log output

```shell
No identified relevant log
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision
