### DISCUSSION TITLE
[Support]: New Frigate+ model installed and now more false positives?

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#11746] [General Support]
Starting off I've been sending TONS of my images to Frigate+ since nearly October last year and have trained a few models, 3 remaining, and try to train once a month if I had a bad month of false positives. I was running a model I trained on 4/25/2024 with 2024.1 and had really good success in both 0.13 and 0.14 with very little false positives if none. Since that model I had submitted nearly 1400+ new images and verified them accordingly but when the new model was generated on 5/31/2024 and configured to use in Frigate I started seeing odd false positives I didn't have before. 

Over time after I trained a new model I would "walk back" the filters and stuff in place to see if it remediated via training but this time I didn't have anything to walk back from the 4/2024 to 5/2024 model so I am wondering why I am seeing these now. 

I know I can filter them out but it is interesting in the regression of false positives...

Here are the models from the F+ UI showing the difference in counts:

![image](https://github.com/blakeblackshear/frigate/assets/108703/239078c1-2a96-4dc9-a6d6-e49c8c36dca2)

Here are a few examples I did NOT see before in the 4/2024 model:

![Mudroom-1717513271 034979-ffj3m7](https://github.com/blakeblackshear/frigate/assets/108703/1389121d-a91a-4cf5-b328-82c90340e249)

![Patio-1717462995 63531-hhs7r9](https://github.com/blakeblackshear/frigate/assets/108703/1a74facf-c7e9-4439-ab10-6ac4af9365ea)

![Basement_Side-1717443599 892422-zos0sq](https://github.com/blakeblackshear/frigate/assets/108703/0e54b904-6670-4eaa-8742-41c03ab6074b)

### Version

0.14.0-e6d1ad0

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate.iot:5000/api/config/schema.json
mqtt:
  enabled: true
  host: mqtt.ha
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
timestamp_style:
  position: br
  format: '%m/%d/%Y %I:%M:%S %p'
model:
  path: plus://<frigate_model>
telemetry:
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
# Default, also tuned at a camera level depending on need.
# Heff if you are reading this remove this section as I am a Frigate+ user.
objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

auth:
  mode: proxy
  failed_login_rate_limit: 1/second;5/minute;20/hour
  header_map:
    user: Remote-User
  trusted_proxies:
    - 172.18.0.0/16 # <---- this is the subnet for the internal docker compose network
    - 192.168.220.11

record:
  enabled: true
  retain:
    days: 90
    mode: all
  events:
    retain:
      default: 90
      mode: active_objects
      objects:
        dog: 7
        cat: 3
        car: 3
        package: 14

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  quality: 100
  retain:
    default: 90
    objects:
      dog: 7
      cat: 3
      car: 3
      package: 14

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2
  coral4:
    type: edgetpu
    device: pci:3

logger:
  default: info
  logs:
    frigate.event: debug
    frigate.app: debug
    frigate.storage: debug
    frigate.object_detection: debug
    frigate.record.cleanup: debug

birdseye:
  enabled: true
  restream: true
  width: 3840
  height: 2160
  quality: 8
  mode: continuous



ui:
  #live_mode: webrtc
  time_format: 12hour
  #use_experimental: True # Breaks audio in live view

go2rtc:
  webrtc:
    candidates:
      - frigate.ip:8555
      - stun:8555
  rtsp:
    username: '{FRIGATE_RTSP_USER}'
    password: '{FRIGATE_RTSP_PASSWORD}'
  streams:
    # Driveway
    driveway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:driveway#audio=opus   # to hear sound with AAC camera audio for WebRTC needs to be PCM or opus, MSE does AAC native.
    driveway_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:driveway_sub#audio=opus
    # BBQ Deck
    bbq_deck:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@bbqdeck.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:bbq_deck#audio=opus
    bbq_deck_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@bbqdeck.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:bbq_deck_sub#audio=opus
    # Basement with AC units
    basement_side:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@basementside.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:basement_side#audio=opus
    basement_side_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@basementside.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:basement_side_sub#audio=opus
    # Front walkway
    frontwalkway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontwalkway.camera:554/Streaming/Channels/101
    frontwalkway_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontwalkway.camera:554/Streaming/Channels/102
    # Mudroom
    mudroom:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@mudroom.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:mudroom#audio=opus
    mudroom_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@mudroom.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:mudroom_sub#audio=opus
    # Kiddo's room
    charlotte:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@charlotte.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:charlotte#audio=opus
    charlotte_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@charlotte.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:charlotte_sub#audio=opus
    # Double Fence
    double_fence:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@double-fence.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:double_fence#audio=opus
    double_fence_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@double-fence.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:double_fence_sub#audio=opus
    # Patio
    patio:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@patio.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:patio#audio=opus
    patio_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@patio.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:patio_sub#audio=opus
    # Backyard
    backyard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@backyard.camera:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:backyard#audio=opus
    backyard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@backyard.camera:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:backyard_sub#audio=opus
    # Playroom
    playroom:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom.camera:554/Streaming/Channels/101
      - ffmpeg:playroom#audio=opus
    playroom_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom.camera:554/Streaming/Channels/102
      - ffmpeg:playroom#audio=opus

cameras:
  Driveway: # Driveway
    live:
      stream_name: driveway_sub
    snapshots:
      required_zones:
        - Front_Yard
    ui:
      order: 1
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    objects:
      track:
        - person
        - car
        - face
        - package
        - amazon
        - fedex
        - ups
        - license_plate
        - dog
    motion:
      mask:
        - 0.703,0.095,0.704,0.022,0.969,0.03,0.97,0.09
        - 0.741,0,1,0,1,0.276,0.739,0.146,0.503,0.115,0.186,0.134,0,0.254,0,0.171,0,0
        - 0.409,0.889,0.54,0.833,0.674,0.765,0.753,0.748,0.783,0.808,0.796,0.905,0.802,1,0.407,0.996
    zones:
      Front_Yard:
        coordinates: 
          1,1,0.942,0.338,0.862,0.214,0.649,0.143,0.393,0.128,0.309,0.142,0.23,0.139,0,0.352,0,1
        objects:
          - person
          - car
          - face
          - package
          - amazon
          - fedex
          - ups
          - license_plate
          - dog
        inertia: 3
      Street:
        coordinates: 
          0.181,0.132,0.358,0.105,0.596,0.099,0.753,0.13,0.904,0.206,1,0.28,1,0,0.276,0,0,0,0,0.283,0.095,0.21
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: Front_Yard
      detections:
        required_zones: Street
  Patio: # Patio
    live:
      stream_name: patio_sub
    ui:
      order: 3
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patio_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask:
        - 0.665,0,1,0.614,1,0,0.839,0
        - 0.422,0,0.258,0,0.332,0.108,0.355,0.356,0.641,0.356,0.645,0.083,0.724,0
    objects:
      track:
        - person
        - face
  Basement_Side: # Basement Side with AC
    live:
      stream_name: basement_side_sub
    snapshots:
      required_zones:
        - Basement_Side_Yard
    ui:
      order: 4
    birdseye:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/basement_side
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/basement_side_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    objects:
      track:
        - person
        - face
        - dog
      #filters: 
      #  person: 
      #    min_area: 4000 # 20240508 after 2024.1 model
    motion:
      mask:
        - 0.291,0.137,0.392,0.185,0.501,0.196,0.497,0.343,1,0.665,1,0,0.292,0
        - 0.323,0.527,0.464,0.489,0.426,0.393,0.305,0.409
        - 0.26,0.332,0.352,0.314,0.327,0.276,0.255,0.291
        - 0.806,0.962,1,0.965,1,0.898,0.804,0.901
    zones:
      Basement_Side_Yard:
        coordinates: 
          0.313,0.204,0.402,0.173,0.492,0.201,0.487,0.339,0.657,0.451,1,0.689,1,1,0.287,1,0.237,0.601,0.231,0.218
        objects:
          - person
          - face
          - dog
        inertia: 3
    review:
      alerts:
        required_zones: Basement_Side_Yard
  BBQ_Deck: # BBQ Deck
    live:
      stream_name: bbq_deck_sub
    snapshots:
      required_zones:
        - BBQ_Deck_Yard
        - BBQ_Deck_Door
    ui:
      order: 5
    birdseye:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bbq_deck
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bbq_deck_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    objects:
      track:
        - person
        - dog
        - face
    motion:
      mask:
        - 0.976,0.025,0.977,0.092,0.701,0.09,0.699,0.022
        - 0,0.627,0,0,0.294,0
    zones:
      BBQ_Deck_Door:
        coordinates: 0.898,1,0.762,0.641,0.459,0.714,0.468,1
        objects: dog
        inertia: 3
      BBQ_Deck_Yard:
        coordinates: 
          0.435,0.173,0.424,1,0,1,0.021,0.859,0.285,0.143,0.436,0,0.599,0,0.73,0.294,0.583,0.313,0.551,0.237,0.513,0.203
        objects:
          - person
          - face
        inertia: 3
    review:
      alerts:
        required_zones:
          - BBQ_Deck_Yard
          - BBQ_Deck_Door
  Front_Walkway: # Front Walkway
    live:
      stream_name: frontwalkway
    ui:
      order: 2
    birdseye:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontwalkway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontwalkway_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      enabled: true
      fps: 10
    motion:
      mask:
        - 0.557,0,0.898,0,0.9,0.048,0.56,0.036
        - 0.133,0.499,0.387,0.074,0.318,0,0,0,0,1,0.399,1
        - 0.585,1,1,1,1,0.892,1,0.818,0.879,0.661,0.758,0.562,0.65,0.566,0.574,0.761,0.649,0.869
        - 0.311,0.221,0.393,0.051,0.506,0.116,0.576,0.247,0.487,0.46,0.392,0.489
    objects:
      track:
        - person
        - package
        - face
        - dog
  Mudroom:
    live:
      stream_name: mudroom_sub
    ui:
      order: 6
    birdseye:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mudroom
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mudroom_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask: 0.704,0.086,0.701,0.019,0.979,0.026,0.975,0.083
    objects:
      track:
        - person
        - face
        - dog
      #filters: # Disabled after 2024-04-29 on new 2024.1 model to test
        #person:
          #mask: 
            #- 1651,184,1635,593,1439,588,1459,190 # Storage rack getting classified as person, training it out
  Backyard: # Backyard
    live:
      stream_name: backyard_sub
    ui:
      order: 7
    birdseye:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask: 0.252,0.229,0.386,0.11,0.649,0.14,0.768,0.251,1,0.477,1,0,0.393,0,0,0,0,0.392
    objects:
      track:
        - person
        - face
        - dog
  Charlotte:
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    live:
      stream_name: charlotte_sub
    ui:
      order: 9
    birdseye:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/charlotte
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/charlotte_sub
          roles:
            - audio
            - detect
    objects:
      filters:
        person:
          mask: 0,0,0,1,1,1,1,0
    detect:
      enabled: true
    audio:
      enabled: true
      listen:
        - scream
        - crying
        - yell
        - beep
    motion:
      mask:
        - 0.709,0.028,0.709,0.084,0.973,0.082,0.973,0.032
        - 0.022,0.914,0.125,0.916,0.127,0.968,0.022,0.969
  Double_Fence:
    live:
      stream_name: double_fence_sub
    ui:
      order: 8
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/double_fence
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/double_fence_sub
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - face
    detect:
      width: 1920
      height: 1080
      enabled: true
      fps: 10
    motion:
      mask:
        - 1,0,1,0.535,0.889,0.34,0.742,0.126,0.532,0,0.692,0
        - 0.178,0,0.186,0.09,0.386,0
  Playroom:
    record:
      enabled: true
      retain:
        days: 3
        mode: all
    live:
      stream_name: playroom_sub
    ui:
      order: 10
    birdseye:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/playroom
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/playroom_sub
          roles:
            - detect
    detect:
      enabled: false
    motion:
      mask:
        - 0.929,0.019,0.93,0.074,0.779,0.085,0.778,0.011
        - 0.008,0.865,0.075,0.865,0.077,0.95,0.011,0.95
camera_groups:
  Front:
    order: 2
    icon: LuCar
    cameras:
      - Driveway
      - Front_Walkway
  Patio:
    order: 3
    icon: LuRockingChair
    cameras:
      - BBQ_Deck
      - Patio
  Birdseye:
    order: 3
    icon: LuBird
    cameras: birdseye
version: 0.14
```

### Relevant log output

```shell
None to report yet
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Mostly Amcrest
