### DISCUSSION TITLE
[Bug]: 0.14.0-beta2 - frigate/events "has_snapshot" always false

### DISCUSSION THREAD

**Discussion by sodre90** [blakeblackshear/frigate#11758] [Report a Bug] [answered]
### Describe the problem you are having

I have an HA automation with a condition to send notifications for frigate events only if "has_snapshot" is true. I am experiencing that "has_snapshot" is always false under "after" and "before" section, even if the event has a snapshot.

By the way, the new user interface is fantastic, thank you for your hard work! 😊

### Steps to reproduce

Trigger any event and check frigate/events on MQTT.

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
go2rtc:
  streams:
    garage:
      - ffmpeg:rtsp://***:***@192.168.3.100/h265Preview_01_main#video=copy#audio=copy#audio=opus
    terrace:
      - ffmpeg:http://192.168.3.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    bedroom:
      - ffmpeg:http://192.168.3.102/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    bedroom_backyard:
      - ffmpeg:http://192.168.3.103/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    backyard:
      - ffmpeg:http://192.168.3.104/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    upper_gate_upper_street:
      - ffmpeg:http://192.168.3.111/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    upper_gate_upper_garden:
      - ffmpeg:http://192.168.3.111/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    upper_gate_bottom_garden:
      - ffmpeg:http://192.168.3.110/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    upper_gate_bottom_street:
      - ffmpeg:http://192.168.3.110/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    garage_gate:
      - ffmpeg:http://192.168.3.109/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    small_gate:
      - ffmpeg:http://192.168.3.109/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    garage_indoor:
      - rtsp://***:***@192.168.3.106:554/Streaming/Channels/101/
    videophone:
      - rtsp://***:***@192.168.3.105:554/Streaming/Channels/101/
    babycamera:
      - ffmpeg:rtsp://***:***@192.168.3.120/h264Preview_01_main#video=copy#audio=copy#audio=opus
mqtt:
  host: 192.168.1.165
  user: homeassistant
  password: ***
logger:
  logs:
    frigate.record: debug
# Optional: Review configuration
# NOTE: Can be overridden at the camera level
review:
  detections:
    labels:
      - face
      - person
      - car
      - bicycle
      - motorcycle
      - dog
      - cat
objects:
  filters:
    person:
      min_score: 0.7
      threshold: 0.83
    car:
      min_score: 0.65
      threshold: 0.7
    motorcycle:
      min_score: 0.7
      threshold: 0.8
    dog:
      min_score: 0.7
      threshold: 0.82
    cat:
      min_score: 0.7
      threshold: 0.82
live:
  height: 1080
  quality: 3
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-vaapi
#  output_args:
#    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
cameras:
  garage:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          #input_args: preset-rtsp-restream
          #input_args: preset-http-reolink
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    motion:
      mask:
        - 2441,0,2437,72,1655,69,1655,0
    objects:
      track:
        - face
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
  terrace:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrace?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2048
      height: 1536
      fps: 5
    motion:
      mask: 0.683,0,0.681,0.048,0.301,0.049,0.299,0
    objects:
      track:
        - face
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.81
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
  bedroom:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2048
      height: 1536
      fps: 5
    motion:
      mask: 0.687,0,0.685,0.048,0.305,0.049,0.303,0
    objects:
      track:
        - face
        - person
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
  bedroom_backyard:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2048
      height: 1536
      fps: 5
    motion:
      mask: 0.69,0,0.688,0.048,0.308,0.049,0.306,0
    objects:
      track:
        - face
        - person
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
  backyard:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2048
      height: 1536
      fps: 5
    motion:
      mask: 0.69,0,0.688,0.048,0.308,0.049,0.306,0
    objects:
      track:
        - face
        - person
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
#      height: 1440
      quality: 90
  upper_gate_upper_street:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upper_gate_upper_street?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - face
        - license_plate
        - car
        - person
        - bicycle
        - motorcycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
#      height: 1440
      quality: 90
    motion:
      mask: 0.333,0.007,0.332,0.066,0.669,0.069,0.669,0
  upper_gate_upper_garden:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upper_gate_upper_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
    motion:
      mask:
        - 1537,0,1539,82,768,84,768,0
    objects:
      track:
        - face
        - person
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
#      height: 1440
      quality: 90
  upper_gate_bottom_garden:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upper_gate_bottom_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - face
        - person
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    motion:
      mask:
        - 1523,0,1524,84,770,78,774,0
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
#      height: 1440
      quality: 90
  upper_gate_bottom_street:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upper_gate_bottom_street?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - face
        - license_plate
        - car
        - person
        - bicycle
        - motorcycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
#      height: 1440
      quality: 90
    motion:
      mask: 0.332,0.004,0.333,0.064,0.664,0.061,0.664,0.006
  garage_gate:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_gate?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - face
        - license_plate
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
    motion:
      mask: 0.344,0,0.344,0.059,0.65,0.058,0.65,0
  small_gate:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/small_gate?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - face
        - license_plate
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
    motion:
      mask: 0.348,0.003,0.347,0.05,0.651,0.057,0.651,0.005
  garage_indoor:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_indoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 834,48,832,123,51,126,45,47
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 7
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 20
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 90
  videophone:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/videophone?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 1753,817,1753,888,1373,892,1364,822
    objects:
      track:
        - face
        - license_plate
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat
      filters:
        bicycle:
          threshold: 0.82
        person:
          min_area: 2500
          min_score: 0.7
          threshold: 0.84
    record:
      enabled: true
      retain:
        days: 14
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
    snapshots:
      enabled: true
      bounding_box: false
      retain:
        default: 60
    mqtt:
      timestamp: false
      bounding_box: false
#      height: 1440
      quality: 90
  babycamera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/babycamera?video=copy&audio=aac
          input_args: preset-rtsp-restream
    detect:
      enabled: false
    record:
      enabled: false
    motion:
      mask: 0.349,0.001,0.35,0.054,0.651,0.056,0.65,0.002
record:
  expire_interval: 1440
database:
  path: /db/frigate.db
detectors:
  coral1:
    type: edgetpu
    device: pci:0
birdseye:
  restream: true
  enabled: true
  width: 1920
  height: 1080
  quality: 8
  mode: objects

version: 0.14
camera_groups:
  Street:
    order: 1
    icon: LuPersonStanding
    cameras:
      - garage_gate
      - small_gate
      - videophone
      - upper_gate_bottom_street
      - upper_gate_upper_street
telemetry:
  # Optional: Configure system stats
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: True
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: True
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_***, cap_net_raw capabilities enabled.
    network_bandwidth: True
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Duo, RLC-410
