### DISCUSSION TITLE
Help me optimize my CPU consumption

### DISCUSSION THREAD

**Discussion by mabed-fr** [blakeblackshear/frigate#11751] [Ask A Question]
### What is your question:

Hello,

Today for the first time I had to use my frigate videos for an intrusion into my home.

To my great surprise the videos during detection were unreadable.(grey and slow...) :(

----
Here is my configuration

```
09:49:36 root ~ → neofetch 
       _,met$$$$$gg.          root
    ,g$$$$$$$$$$$$$$$P.       ------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: NUC11ATKC2 M53060-202 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-21-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 28 days, 17 hours, 52 mins 
 $$P      d$'     ,    $$P    Packages: 1561 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0 
 Y$$.    `.`"Y$$$$P"'         CPU: Intel Celeron N4505 (2) @ 2.900GHz 
 `$$b      "-.__              GPU: Intel JasperLake [UHD Graphics] 
  `Y$$                        Memory: 4657MiB / 15738MiB 
   `Y$$.
     `$$b.                                            
       `Y$$b.                                         
          `"Y$b._
              `"""
```

----
2 x reolink 811a (POE)(h265)
1 x reolink trackmix (POE)(h265)

here is my frigate config

```
mqtt:
  host: 192.168.1.254

model:
  path: plus://**********************************

#logger:
#  logs:
#    frigate.record.maintainer: debug

birdseye:
  enabled: false
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog
    - license_plate
  filters:
    dog:
      min_score: .65
      threshold: .85
    cat:
      min_score: .65
      threshold: .89
    license_plate:
      min_score: .7
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .90

review:
  alerts:
    labels:
      - person

go2rtc:
  streams:
    TELECOM:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main
    CLIM:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.175:554/h265Preview_01_main
    ENTRE:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.177:554/h265Preview_01_main
    #ENTRE2:
    #  - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.177:554/h265Preview_02_main

cameras:
  TELECOM:
    ffmpeg:
      inputs:
        #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main
        - path: rtsp://127.0.0.1:8554/TELECOM
         # input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.1.146
      port: 8000
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
  CLIM:
    ffmpeg:
      inputs:
        #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.175:554/h265Preview_01_main
        - path: rtsp://127.0.0.1:8554/CLIM
         # input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.1.175
      port: 8000
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
  ENTRE:
    ffmpeg:
      inputs:
        #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.175:554/h265Preview_01_main
        - path: rtsp://127.0.0.1:8554/ENTRE
         # input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.1.177
      port: 8000
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
  #ENTRE2:
  #  ffmpeg:
  #    inputs:
  #      #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.175:554/h265Preview_01_main
  #      - path: rtsp://127.0.0.1:8554/ENTRE2
  #       # input_args: preset-rtsp-generic
  #        roles:
  #          - record
  #          - detect
  #    output_args:
  #      record: preset-record-generic-audio-aac
  #  onvif:
  #    host: 192.168.1.177
  #    port: 8000
  #    user: '{FRIGATE_RTSP_USER}'
  #    password: '{FRIGATE_RTSP_PASSWORD}'

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 10

record:
  expire_interval: 60
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 1

snapshots:
  enabled: true
version: 0.14
```

I notice that my CPU load was 8-10 before deactivation of bird eyes and now i have 4-6
I also deactivated the second objective of the trackmix for the moment

Do I really need to change hardware or do you see any areas for CPU optimization?
-----

![image](https://github.com/blakeblackshear/frigate/assets/25350431/712dea62-514d-45d0-8ef6-1cbdb53ff29e)
![image](https://github.com/blakeblackshear/frigate/assets/25350431/1b869ecb-e853-491b-ae83-d797efe8b45b)
![image](https://github.com/blakeblackshear/frigate/assets/25350431/16ebdc97-c53a-46ce-ba08-b923be90ce55)
![image](https://github.com/blakeblackshear/frigate/assets/25350431/54368479-2720-47ec-9b15-9450aec7b917)
