### DISCUSSION TITLE
improve_contrast Option

### DISCUSSION THREAD

**Discussion by NeoDuder** [blakeblackshear/frigate#11759] [Config Support] [answered]
### Describe the problem you are having

I automate the 'improve_contrast' option using NodeRed. Unfortunately, when the Frigate container restarts for whatever reason, it always goes back to the default. Is there a way to set this to manual?

### Version

0.14.0-b97e274

### Frigate config file

```yaml
mqtt:
  host: 172.16.50.6
  user: mqtt
  password: *****

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://e00b7fec53ce1287eb452ba0a6698cb8

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    drive:
      - rtsp://admin:*****@172.16.50.101:554/h264Preview_01_main
    drive_sub:
      - rtsp://admin:*****@172.16.50.101:554/h264Preview_01_sub
    door:
      - rtsp://admin:*****@172.16.50.100:554/h264Preview_01_main
    door_sub:
      - rtsp://admin:*****@172.16.50.100:554/h264Preview_01_sub
    path:
      - rtsp://admin:*****@172.16.50.102:554/h264Preview_01_main
    path_sub:
      - rtsp://admin:*****@172.16.50.102:554/h264Preview_01_sub
    front:
      - rtsp://admin:*****@172.16.50.103:554/h264Preview_01_main
    front_sub:
      - rtsp://admin:*****@172.16.50.103:554/h264Preview_01_sub
    #360cam:
    #  - rtsp://admin:*****@172.16.50.110:554/h264Preview_01_main
    #360cam_sub:
    #  - rtsp://admin:*****@172.16.50.110:554/h264Preview_01_sub

birdseye:
  enabled: true
  mode: objects

cameras:
  drive:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drive
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drive_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 
        1,0,0,0,0,0.315,0.087,0.282,0.316,0.306,0.334,0.35,0.539,0.43,0.708,0.45,0.74,0.475,0.908,0.353,1,0.183
    zones:
      frontgarden:
        coordinates: 
          1,0.447,0.874,0.379,0.74,0.475,0.708,0.452,0.556,0.433,0.356,0.358,0,0.508,0,1,1,1
        objects:
          - person
          - cat
          - dog
          - bicycle
          - bird
        inertia: 3
      drivepath:
        coordinates: 640,208,640,294,517,258,479,209,508,178,538,193,599,194
        objects:
          - person
      driveway:
        coordinates: 112,360,80,202,323,146,456,158,516,185,508,212,541,235,589,260,640,272,640,360
      entry:
        coordinates: 0.166,0.472,0.411,0.375,0.505,0.406,0.125,0.559
        objects: car
        inertia: 3
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bicycle
        - bird
    detect:
      width: 640
      height: 360
      fps: 4
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 30
        retain:
          default: 28
          mode: active_objects
    snapshots:
      enabled: true
      required_zones:
        - entry
        - frontgarden
      retain:
        default: 28
    review:
      alerts:
        required_zones:
          - entry
          - frontgarden
  door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 432,29,640,29,640,0,434,0
    zones:
      doorway:
        coordinates: 
          0.746,0.915,0.644,0.888,0.587,0.837,0.476,0.771,0.188,0.912,0.224,0.999,0.713,0.998
        objects: 
          - person
          - face
        inertia: 3
      doorpath:
        coordinates: 
          0.208,1,0.138,0.705,0.259,0.678,0.254,0.596,0.33,0.586,0.322,0.608,0.333,0.624,0.369,0.644,0.403,0.673,0.442,0.736,0.526,0.805
        objects: person
        inertia: 3
      centrepath:
        coordinates: 
          0.402,0.671,0.368,0.643,0.336,0.626,0.321,0.608,0.33,0.586,0.356,0.578,0.253,0.568,0.259,0.679,0.139,0.707,0.187,0.911,0.476,0.772,0.444,0.738
        objects: person
        inertia: 3
      frontgarden:
        coordinates: 
          0.745,0.915,0.643,0.889,0.659,0.777,0.682,0.69,0.734,0.602,0.457,0.562,0.457,0.532,0.443,0.522,0.43,0.512,0.25,0.512,0.259,0.679,0.123,0.71,0.189,1,0.711,1
        inertia: 3
    objects:
      track:
        - person
        - face
        - cat
        - dog
        - bicycle
        - bird
    detect:
      width: 640
      height: 480
      fps: 4
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 30
        retain:
          default: 28
          mode: active_objects
    snapshots:
      enabled: true
      required_zones:
        - frontgarden
      retain:
        default: 28
    review:
      alerts:
        required_zones: frontgarden
  path:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/path
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/path_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 640,0,640,24,439,26,438,0
        - 169,0,0,0,0,145
    zones:
      frontgarden:
        coordinates: 
          0.888,1,0.827,0.717,0.619,0.733,0.586,0.169,0.586,0.061,0.228,0.086,0.127,0.239,0,0.458,0,1
        inertia: 3
      drivepath:
        coordinates: 
          0,1,0.887,1,0.828,0.715,0.616,0.731,0.587,0.197,0.453,0.203,0.436,0.227,0.408,0.342,0.362,0.445,0.281,0.548,0.143,0.656,0.068,0.687,0,0.583
        objects: person
        inertia: 3
      centrepath:
        coordinates: 
          0.5,0.153,0.585,0.149,0.616,0.729,0.829,0.714,0.889,1,0.178,1,0.07,0.687,0.144,0.656,0.282,0.547,0.362,0.448,0.409,0.345,0.435,0.235,0.467,0.18
        objects: person
        inertia: 3
      doorpath:
        coordinates: 
          0.591,0.258,0.587,0.103,0.528,0.104,0.501,0.152,0.473,0.175,0.436,0.228,0.408,0.342,0.362,0.445,0.28,0.549,0.145,0.655,0.615,0.702
        objects: person
        inertia: 3
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
        - bird
    detect:
      width: 640
      height: 360
      fps: 4
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 30
        retain:
          default: 28
          mode: active_objects
    snapshots:
      enabled: true
      retain:
        default: 28
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1,0,1,0.067,0.686,0.072,0.684,0
        - 0.561,0.16,0.565,0.391,0.457,0.517,0.441,0.254
    zones:
      doorway:
        coordinates: 131,360,59,285,106,273,200,339
        objects:
          - person
      doorpath:
        coordinates: 
          0.109,0.825,0.302,0.611,0.406,0.71,0.598,0.456,0.822,0.569,0.741,0.571,0.693,0.596,0.665,0.622,0.634,0.661,0.599,0.725,0.531,0.814,0.491,0.849,0.444,0.871,0.347,0.934,0.279,1,0.198,1
        objects: person
        inertia: 3
      drivepath:
        coordinates: 
          0.528,0.816,0.59,0.734,0.636,0.652,0.686,0.602,0.744,0.571,0.794,0.565,0.842,0.575,0.9,0.592,0.961,0.636,0.944,0.404,0.759,0.264,0.715,0.348,0.599,0.303,0.601,0.446,0.407,0.712,0.477,0.775
        objects: person
        inertia: 3
      centrepath:
        coordinates: 
          0.717,0.347,0.86,0.422,0.898,0.59,0.853,0.571,0.808,0.563,0.755,0.564,0.72,0.578,0.684,0.603,0.634,0.661,0.587,0.739,0.509,0.836,0.401,0.899,0.324,0.956,0.182,0.775,0.311,0.622,0.406,0.711,0.601,0.446,0.598,0.302
        objects: person
        inertia: 3
      driveway:
        coordinates: 
          0.728,0.317,0.841,0.125,1,0.183,1,0.664,0.903,0.594,0.918,0.536,0.92,0.478,0.907,0.439,0.886,0.408,0.849,0.378,0.809,0.356
        inertia: 3
      frontgarden:
        coordinates: 
          0.6,0.446,0.597,0.301,0.709,0.347,0.828,0.144,1,0.203,1,0.661,1,1,0.205,1,0.11,0.824,0.301,0.612,0.407,0.71
        inertia: 3
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
        - bird
    detect:
      width: 640
      height: 360
      fps: 4
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 30
        retain:
          default: 28
          mode: active_objects
    snapshots:
      enabled: true
      retain:
        default: 28
      required_zones:
        - frontgarden
  #360cam:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/360cam
  #        input_args: preset-rtsp-restream
  #        roles:
  #          - record
  #      - path: rtsp://127.0.0.1:8554/360cam_sub
  #        input_args: preset-rtsp-restream
  #        roles:
  #          - detect
    review:
      alerts:
        required_zones: frontgarden
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB
