### DISCUSSION TITLE
[Support]: Cant resize ultra wide cameras to remove black bars.

### DISCUSSION THREAD

**Discussion by mattbruman** [blakeblackshear/frigate#11767] [Camera Support] [answered]
### Describe the problem you are having

When using ultra-wide cameras like Reolink Duo 2 and resizing the camera in Beta 14.2 the camera will keep the black bars in the views. But in Birdseye view the black bars are not shown.

![image](https://github.com/blakeblackshear/frigate/assets/43623584/54e350a7-c1a3-4720-b7f4-fff5915d3a00)
 
![image](https://github.com/blakeblackshear/frigate/assets/43623584/dda5f924-fb63-4034-a3b0-48fd4454298e)

Also doorbell cameras from Reolink looks like they will allow the resizing of the cameras to allow for the removal of the black bars but after resizing the black bars snap back on.

![image](https://github.com/blakeblackshear/frigate/assets/43623584/4eb3b057-d263-46c0-803b-f73f9234912e)

![image](https://github.com/blakeblackshear/frigate/assets/43623584/a0047d88-ceca-4369-bb31-ce39ae18bb0f)

![image](https://github.com/blakeblackshear/frigate/assets/43623584/2f4bd919-9fe2-449e-b328-316b381837b9)

### Steps to reproduce

Create a new camera view and add wide or doorbell cameras and then resize.

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: mqttuser
  password: '****'
  host: 192.168.1.10
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

# Optional: birdseye configuration
birdseye:
# Optional: Enable birdseye view (default: shown below)
  enabled: true
# Optional: Width of the output resolution (default: shown below)
  width: 1920
# Optional: Height of the output resolution (default: shown below)
  height: 1080
# Optional: Encoding quality of the mpeg1 feed (default: shown below)
# 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
# Optional: Mode of the view. Available options are: objects, motion, and continuous
#   objects - cameras are included if they have had a tracked object within the last 30 seconds
#   motion - cameras are included if motion was detected in the last 30 seconds
#   continuous - all cameras are included always
  mode: motion

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  events:
    retain:
      default: 1
      mode: active_objects
      objects:
        dog: 1
        car: 2

go2rtc:
  streams:
    front_right:
      - rtsp://admin:****@192.168.1.113:554/h264Preview_01_main
      - ffmpeg:front_right#video=h264
    front_right_sub:
      - rtsp://admin:****@192.168.1.113:554/h264Preview_01_sub
      - ffmpeg:front_right_sub#video=h264
    back:
      - rtsp://admin:****@192.168.1.247:554/h264Preview_01_main
      - ffmpeg:back#video=h264
    back_sub:
      - rtsp://admin:****@192.168.1.247:554/h264Preview_01_sub
      - ffmpeg:back_sub#video=h264
    front:
      - rtsp://admin:****@192.168.1.48:554/h264Preview_01_main
      - ffmpeg:front#video=h264
    front_sub:
      - rtsp://admin:****@192.168.1.48:554/h264Preview_01_sub      
     #- ffmpeg:front_sub#video=h264
    front_doorbell:
      - rtsp://admin:****@192.168.1.98:554/h264Preview_01_main
      #- ffmpeg:front_doorbell#video=h264
    front_doorbell_sub:
      - rtsp://admin:****@192.168.1.98:554/h264Preview_01_sub
      #- ffmpeg:front_doorbell#video=h264
    side_doorbell:
      - rtsp://admin:****@192.168.1.172:554/h264Preview_01_main
      #- ffmpeg:side_doorbell#video=h264
    side_doorbell_sub:
      - rtsp://admin:****@192.168.1.172:554/h264Preview_01_sub
      #- ffmpeg:side_doorbell#video=h264
    garage-door:
      - rtsp://admin:****@192.168.1.185:554/h264Preview_01_main
      #- ffmpeg:garage-door#video=h264
    garage-door_sub:
      - rtsp://admin:****@192.168.1.185:554/h264Preview_01_sub
      #- ffmpeg:garage-door#video=h264
    side:
      - rtsp://admin:****@192.168.1.50:554/h264Preview_01_main
      #- ffmpeg:side#video=h264
    side_sub:
      - rtsp://admin:****@192.168.1.50:554/h264Preview_01_sub
      #- ffmpeg:side#video=h264



ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  front_right:
    birdseye:
      mode: continuous
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_right
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_right_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask: 
        0.263,0.294,0.093,0.205,0,0.133,0.041,0.001,1,0.004,0.997,0.61,0.95,0.738,0.908,0.769,0.656,0.109,0.637,0.069,0.447,0.124,0.366,0.203
      #mask:
        #- 577,99,725,61,914,36,1032,44,1182,153,1436,379,1536,279,1536,0,0,0,0,303
    zones:
      walkway:
        coordinates: 
          390,392,524,283,728,193,921,160,894,79,656,82,543,129,470,155,432,170,335,215,288,245
        objects:
          - person
      driveway_entrance:
        coordinates: 893,128,1077,140,997,57,860,44
        objects:
          - car
      driveway:
        coordinates: 1481,576,1062,576,900,114,1072,133
        objects:
          - person
          - car
    objects:
      track:
        - person
        - car
      #filters:
        #car:
          #mask:
            #- 0,0,1536,0,1536,576,1482,576,1007,51,867,50,1015,576,0,576
        #person:
          #threshold: 0.81
          #mask:
            #- 1059,80,691,73,321,204,0,348,0,0,1111,0,1536,0,1536,459
            #- 819,343,787,87,509,124,550,384
      filters:
        car:
          mask: 
            0.28,0.27,0.208,0.133,0.353,0,0.664,0,0.848,0,0.929,0.126,1,0.217,1,0.369,1,0.523,0.911,0.823,0.69,0.131,0.652,0.089,0.56,0.102,0.443,0.141
        person:
          mask: 
            0.273,0.29,0.189,0.158,0.332,0.004,0.94,0,1,0.23,1,0.58,0.94,0.713,0.896,0.755,0.673,0.144,0.656,0.114,0.561,0.101,0.434,0.141
  front:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask: 0.44,0.29,0.001,0.653,0.003,0.002,1,0,1,0.203,0.638,0.23,0.478,0.263
      #mask: 0,0,0.745,0,1,0,1,0.21,0.687,0.258,0.439,0.302,0,0.674
    zones:
      driveway:
        coordinates: 0.927,0.306,0.988,0.292,0.982,0.216,0.503,0.292,0.439,0.356,0.54,0.342
        objects:
          - car
          - person
        inertia: 3
      driveway_entrance:
        coordinates: 0.483,0.35,0.494,0.295,0.356,0.318,0.262,0.394
        objects: car
        inertia: 3
      porch:
        coordinates: 1920,329,1920,799,1259,789,1094,636,1183,483,1323,392,1540,306
        objects:
          - person
      walkway:
        coordinates: 995,549,1232,735,1341,581,1282,353,1038,355
        objects:
          - person
    objects:
      track:
        - person
        - car
      #filters:
        #car:
          #mask:
            #- 0,1080,1920,1080,1920,302,1453,351,1107,366,683,402,574,427,0,0
            #- 0,0,1920,0,1920,197,1920,227,1797,250,704,335,0,717
        #person:
          #threshold: 0.80
          #mask: 0,0,0,0.672,0.436,0.299,0.972,0.226,0.963,0.145,0.947,0.049,1,0
      filters:
        car:
          mask: 
            0.001,0.648,0,0.002,0.997,0.002,0.998,0.201,0.478,0.269,0.351,0.312,0.281,0.368,0.32,0.394
        person:
          mask: 0.002,0.652,0.001,0,0.998,0,0.998,0.198,0.476,0.261,0.421,0.314,0.319,0.399
  garage-door:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-door
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage-door_sub
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      stationary:
        interval: 30
        threshold: 20
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask: 0.118,0.543,0,0.713,0.001,0.001,0.587,0.003,0.6,0.069,0.392,0.225
      #mask: 0,0,0.502,0,0.625,0,0.624,0.046,0.528,0.122,0.131,0.478,0,0.851
    objects:
      track:
        - person
        - car
      filters:
        car:
          threshold: 0.85
        person:
          threshold: 0.80
          #mask: 0.602,0.066,0.591,0,0,0,0,0.849,0.139,0.538,0.129,0.475
          mask: 0,0.803,0,0.001,0.595,0.003,0.61,0.066,0.396,0.244
  side:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/side
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_sub
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask:
      #mask:
        #- 0,497,0,0,2560,0,2560,363,2328,50,1726,0,1472,0,1455,274,1376,370,670,387
        - 0.818,0,1,0.235,1,0
        - 0.453,0,0,0,0.226,0.572,0.314,0.735,0.464,0.418
    zones:
      driveway_entrance:
        coordinates: 2159,0,2332,255,1882,222,1906,0
        objects:
          - car
      side_door:
        coordinates: 1512,0,2180,44,2271,167,1911,187,1747,817,1399,777
        objects:
          - person
    objects:
      track:
        - person
        - car
      filters:
        car:
          threshold: 0.80
          mask: 0.823,0.016,1,0.276,0.999,0.003,0.734,0.003
            #- 0,0,2560,0,2560,336,2307,45,1901,0,1027,1440,0,1440,25,615
        person:
          threshold: 0.80
          #mask: 0.856,0,0.893,0.036,0.954,0.158,1,0.283,1,0
          mask: 0.738,0.03,0.875,0.073,0.924,0.216,0.997,0.347,0.998,0.006,0.737,0.003
  back:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution 
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      #mask: 
        #0,0,0.298,0,1,0,0.877,0.462,0.645,0.168,0.508,0.064,0.434,0.075,0.307,0.151,0.3,0.297,0.064,0.568,0.075,0.712,0,0.898
      threshold: 30
      contour_area: 26
      improve_contrast: 'true'
      mask:
        - 0.001,0.878,0.084,0.688,0.398,0,0.001,0.001
        - 0.787,0.337,0.473,0.006,0.857,0.001
    zones:
      backyard:
        coordinates: 696,576,1074,576,1228,254,1122,153,909,68,723,33,652,58,572,66,477,145,545,417
      gate:
        coordinates: 603,576,542,423,453,240,316,263,89,576
    objects:
      track:
        - person
        - dog
      #filters:
        #dog:
          #mask:
            #- 867,59,1232,212,1330,0,1113,0,759,0
        #person:
          #threshold: 0.80
          #mask: 
            #0.061,0.575,0.303,0.307,0.306,0.108,0.528,0.064,0.809,0.314,0.863,0,0,0,0,0.878,0.071,0.731
      filters:
        dog:
          mask:
            - 0.551,0.69,0.614,0.54,0.754,0.615,0.679,0.963
            - 0.786,0.332,0.858,0,0.472,0.004
        person:
          mask:
            - 0,0.884,0.003,0.009,0.407,0
            - 0.786,0.329,0.857,0.001,0.47,0.009
  front_doorbell:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask: 0,0.548,0.658,0.624,1,0.615,0.998,0.332,0.001,0.359
      #mask: 0,0.354,0,0,1,0,1,0.371,1,0.611,0.412,0.606,0.368,0.617,0.196,0.671,0,0.719
    objects:
      track:
        - person
        - car
      filters:
        car:
          threshold: 0.80
          #mask: 0.188,0.568,0.456,0.588,1,0.613,1,0.412,0.177,0.457
          mask: 0.001,0.359,0.996,0.331,0.996,0.624,0.002,0.547
        person:
          threshold: 0.80
          #mask: 0.169,0.482,1,0.479,1,0.622,0.615,0.628,0.171,0.6
          mask: 0.003,0.546,0.552,0.627,0.99,0.622,0.998,0.335,0.005,0.361
  side_doorbell:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/side_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask: 
        0.095,0.546,0.329,0.593,0.532,0.633,0.6,0.368,0.443,0.195,0.233,0.147,0.16,0.166,0.127,0.24
      #mask:
        #- 0,680,0,0,1829,0,2054,224,2002,732,1395,404,865,732,873,1009,699,1029,369,1051,0,1025
    objects:
      track:
        - person
        - car
      filters:
        car:
          threshold: 0.80
          #mask:
            #- 0,1089,352,1049,879,1132,1317,0,0,0
          mask: 0.096,0.542,0.53,0.63,0.454,0.389,0.3,0.368,0.103,0.348
        person:
          threshold: 0.80
          min_area: 150000
          #mask:
            #- 261,743,870,598,2018,693,1795,1397,900,1264,292,1079



          mask: 0.087,0.54,0.509,0.6,0.601,0.601,0.599,0.431,0.566,0.297,0.301,0.194,0.114,0.233
version: 0.14
camera_groups:
  Birds_Eye:
    order: 1
    icon: LuActivity
    cameras:
      - birdseye
      - front_right
  All:
    order: 2
    icon: LuGalleryVerticalEnd
    cameras:
      - back
      - front
      - front_doorbell
      - front_right
      - garage-door
      - side
      - side_doorbell
```

### Relevant log output

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink Duo2, Reolink Doorbell POE
