### DISCUSSION TITLE
Having trouble getting MSE stream to display in WebUI. Stuck on [INFO] Starting go2rtc healthcheck service...

### DISCUSSION THREAD

**Discussion by EvanEsh52** [blakeblackshear/frigate#11772] [Config Support]
### Describe the problem you are having

Title pretty much sums it up.

My jsmpeg stream works correctly, but when loading the MSE stream i get the following:

![image](https://github.com/blakeblackshear/frigate/assets/144980616/3c22dcb8-ad40-4a1e-8fb3-2e0284560bc7)

With a black spinning wheel. 

I would like to get the MSE feed working but have tried everything I can find.

Unfortunately, I am definitely not an expert on any of this stuff so I have been learning as I go. 

I will also be integrating into home assistant soon, so my presumption is that this will be needed to be fixed as I move forward given that it may be a Go2rtc issue. Regardless, I would like to see the stream working correctly.

Any help is greatly appreciated! If there is a way I can pay it forward, please let me know. 

### Version

0.13.2-6476F8A   go2rtc 1.8.4

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

record:
    enabled: true
    retain:
      days: 7
      mode: motion
    events:
      retain:
        default: 30
        mode: motion

snapshots:
  enabled: true
  retain:
    default: 30
    
cameras:
  TestCam: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://[username]:[password]@192.168.0.221:554/cam/realmonitor?channel=1&subtype=0&u>
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
            - rtmp
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: True
      fps: 5
go2rtc:
  streams:
    TestCam:
      - rtsp://[username]:[password]@192.168.0.221:554/cam/realmonitor?channel=1&subtype=0&u>
```

### Relevant log output

```shell
2024-06-06 05:31:51.496339192  [INFO] Preparing new go2rtc config...
2024-06-06 05:31:51.837572303  [INFO] Starting go2rtc...
2024-06-06 05:31:51.915284590  05:31:51.914 INF go2rtc version 1.8.4 linux/amd64
2024-06-06 05:31:51.915288085  05:31:51.914 INF [rtsp] listen addr=:8554
2024-06-06 05:31:51.915292069  05:31:51.914 INF [webrtc] listen addr=:8555
2024-06-06 05:31:51.915531874  05:31:51.915 INF [api] listen addr=:1984
2024-06-06 05:32:01.495701781  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
