### DISCUSSION TITLE
[Bug]: Frigate container fails to restart on beta 0.14.2

### DISCUSSION THREAD

**Discussion by derekcentrico** [blakeblackshear/frigate#11784] [Report a Bug] [answered]
### Describe the problem you are having

Any time I update the cameras using the new UI and go to reboot the system it just hangs.  I have to manually stop the docker container and re-start it for frigate to come back online.

### Steps to reproduce

Edit cameras.  Reboot frigate.  Frigate doesn't come back online.

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.49
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqttuser
  password: mqttuser
  stats_interval: 60

model:
# 2024.1 Base - 1064 images  
  path: plus://XXXX

detectors:
  coral_pci:
    type: edgetpu
    device: pci

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 500
  listen:
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.90

detect:
  enabled: true
  stationary:
    interval: 10
    threshold: 100
    max_frames:
      default: 2000
      objects:
        person: 1000
        car: 2000

objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package
    - bird
    - suitcase
    - fox
    - raccoon
    - squirrel
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
      threshold: .85
    package:
      min_score: .65
      threshold: .85
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .86
    car:
      min_score: .65
      threshold: .85

record:
  enabled: true
  expire_interval: 60
  sync_recordings: true
  retain:
    days: 21
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 30
      mode: motion
      objects:
        person: 60

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 1080
  retain:
    default: 14
    objects:
      person: 60
  quality: 100

birdseye:
  enabled: true
  mode: continuous

go2rtc:
  streams:
    garage:
      - rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:garage#video=h265#audio=aac
    garage_sub:
      - rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:garage_sub#video=h264#audio=aac
    driveway:
      - rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway#video=h265#audio=aac
    driveway_sub:
      - rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:driveway_sub#video=h264#audio=aac
    backyard:
      - rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:backyard#video=h265#audio=aac
    backyard_sub:
      - rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:backyard_sub#video=h264#audio=aac
    patio:
      - rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:patio#video=h265#audio=aac
    patio_sub:
      - rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:patio_sub#video=h264#audio=aac
    doorbell:
      - rtsp://admin:admin@192.168.1.244:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:doorbell#video=h265#audio=aac
    doorbell_sub:
      - rtsp://admin:admin@192.168.1.244:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
      - ffmpeg:doorbell_sub#video=h264#audio=aac

cameras:
  garage:
    mqtt:
      bounding_box: false
      timestamp: false
      crop: true
      height: 2160 #1620 #1080
      quality: 100
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://admin:admin@192.168.1.240:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-vaapi
    live:
      stream_name: garage_sub
    detect:
      enabled: true
      height: 1080
      width: 1920
      fps: 10
      stationary:
        interval: 50  # Check every 50 frames to confirm if the car is stationary
        threshold: 100  # Require 100 frames of no movement to consider stationary (10 seconds at 10 fps)
        max_frames:
          default: 100  # Track for 10 seconds and then ignore
          objects:
            car: 100  # Specifically for the car
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      threshold: 50  # Increase to reduce sensitivity to minor changes
      mask:
        - 1354,72,1920,71,1920,0,1354,0
    zones:
      inside:
        coordinates: 0,1080,0,0,70,0,167,360,301,357,781,325,1323,286,1331,0,1920,0,1920,1080
      outside:
        coordinates: 154,352,119,212,64,0,599,0,1317,0,1309,139,1296,267,887,296
    objects:
      track:
        - person
        - face
        - suitcase
#      - car
      filters:
        car:
          min_score: 0.85
          threshold: 0.90
          mask:
            - 72,0,685,0,1920,0,1348,0,1283,359,124,413
            - 1920,0,1348,0,1426,329,1492,457,1616,681,1920,908
            - 1300,1045,1428,683,1283,359,1112,325,960,326,707,325,504,353,261,386,136,402,0,748,0,990,33,1058
        person:
          mask:
            - 120,155,305,96,674,0,425,0,171,0,76,0
            - 120,155,305,96
  driveway:
    mqtt:
      bounding_box: false
      timestamp: false
      crop: true
      height: 2160 #1620 #1080
      quality: 100
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://admin:admin@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-vaapi
    live:
      stream_name: driveway_sub
    detect:
      enabled: true
      height: 1080
      width: 1920
      fps: 10
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 848,78,574,53,474,0,675,0,854,0,1280,0,1280,115
        - 0,0,541,0,582,38,0,264
        - 1114,54,1139,0,1769,0,1920,0,1920,127
    zones:
      pavement:
        coordinates: 0,1080,0,516,315,306,740,127,995,46,1259,81,1221,216,1150,510,1202,602,1221,1080
      sidewalk:
        coordinates: 1235,739,1858,736,1920,602,1496,586,1221,582
      frontyard:
        coordinates: 0.614,0.401,0.609,0.469,0.621,0.509,1,0.533,1,0.202,0.649,0.136
        inertia: 3
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
        - fox
        - raccoon
      filters:
        car:
          mask:
            - 0,369,399,202,898,35,901,0,0,0
            - 1783,112,1289,74,1318,0,1920,0,1920,118
        person:
          mask: 
            0,0.308,0,0,1,0,1,0.108,0.865,0.106,0.661,0.069,0.512,0.042,0.455,0.03,0.395,0.052
  backyard:
    mqtt:
      bounding_box: false
      timestamp: false
      crop: true
      height: 1620 #1080
      quality: 100
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://admin:admin@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-vaapi
    live:
      stream_name: backyard_sub
    detect:
      enabled: true
      height: 1080
      width: 1920
      fps: 10
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 1831,306,1736,175,1712,137,1680,84,1666,263,1450,221,1322,0,1920,0,1920,490
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - bird
        - fox
        - raccoon
        - squirrel
      filters:
        person:
          mask:
            - 1920,0,1920,463,1672,130,1627,0,1920,0
        license_plate:
          mask:
            - 0,1080,0,0,1920,0,1920,1080
        car:
          mask:
            - 0,1080,0,0,1920,0,1920,1080
  patio:
    mqtt:
      bounding_box: false
      timestamp: false
      crop: true
      height: 2496 #1664 #832
      quality: 100
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
#            - detect
#            - audio
        - path: 
            rtsp://admin:admin@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-vaapi
    live:
      stream_name: patio_sub
    detect:
      enabled: true
      height: 1644 #832
      width: 3840 #1920
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 21,315,49,256,37,80,57,0,560,0,381,76,228,198,162,275,55,396
        - 1450,0,1460,66,1750,220,1920,305,1920,0
        - 1920,93,1563,80,1783,225,1808,284,1782,321,1833,429,1920,650
    zones:
      deck:
        coordinates: 1216,605,1019,576,1041,267,654,229,531,309,327,283,138,549,320,832,1359,832
      swingset:
        coordinates: 1593,305,1698,488,1770,545,1814,535,1814,430,1718,272
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - bird
        - fox
        - raccoon
        - squirrel
      filters:
        dog:
          mask:
            - 0,0,0,422,78,442,719,38,1153,49,1590,218,1726,315,1821,478,1920,685,1920,0
        person:
          min_score: 0.65  # Adjusted to improve person detection
          threshold: 0.85  # Adjusted to improve person detection
          mask:
            - 0,435,338,109,490,21,1346,21,1681,188,1920,572,1920,384,1920,0,328,0,0,0
        face:
          min_score: 0.70  # Adjusted to improve face detection
          threshold: 0.80  # Adjusted to improve face detection
        license_plate:
          mask:
            - 0,832,0,0,1920,0,1920,832
        car:
          mask:
            - 0,832,0,0,1920,0,1920,832
  doorbell:
    mqtt:
      bounding_box: false
      timestamp: false
      crop: true
      height: 1440
      quality: 100
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#      - path: 
#          rtsp://admin:admin@192.168.1.244:554/cam/realmonitor?channel=1&subtype=1
#        roles:
        - path: 
            rtsp://admin:admin@192.168.1.244:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      hwaccel_args: preset-vaapi
#    live:
#      stream_name: doorbell
    detect:
      enabled: true
      height: 1080
      width: 1920
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
        - fox
        - raccoon

      mask: 
        0,0,0,0.537,0.353,0.536,0.436,0.566,0.583,0.573,0.725,0.569,0.803,0.542,0.807,0.33,0.796,0.081,0.793,0,0.482,0,0.132,0
    zones:
      porch:
        coordinates: 0.003,0.903,0.182,0.827,0.77,0.908,0.768,0.994,0,0.998
        objects:
          - package
          - person
      sidewalk:
        coordinates: 
          0.054,0.622,0.286,0.758,0.584,0.794,0.551,0.958,0.376,0.916,0.397,0.872,0.168,0.794,0.04,0.697,0.002,0.634
        objects:
          - package
          - person
      frontyard:
        coordinates: 
          0.108,0.614,0.452,0.57,0.802,0.545,0.791,0.708,0.782,0.802,0.772,0.894,0.656,0.748,0.512,0.703,0.368,0.698
        objects:
          - car
          - person
          - package
        inertia: 3
      pavement:
        coordinates: 0.002,0.552,0.002,0.63,0.19,0.595,0.431,0.57,0.387,0.553,0.189,0.556
        objects:
          - car
          - package
          - person
    review:
      alerts:
        required_zones:
          - porch
          - sidewalk
      detections:
        required_zones:
          - porch
          - sidewalk
          - frontyard
          - pavement
    motion:
      mask:
        - 0.435,0.569,0.533,0.57,0.709,0.567,0.808,0.544,0.813,0.484,0.811,0.245,0.802,0,0.002,0.005,0,0.205,0,0.242,0,0.547,0.301,0.553
        - 0.07,0.933,0.278,0.93,0.28,0.975,0.069,0.977
telemetry:
  network_interfaces:
    - eno
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
```

### Relevant log output

```shell
ndle.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
2024-06-06 14:47:32.545198596  ::ffff:192.168.1.140 - - [06/Jun/2024:14:47:32 -0400] "POST /api/config/save?save_option=restart HTTP/1.1" 200 103 "http://192.168.1.49:5000/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service certsync: stopping
2024-06-06 14:47:32.551581271  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-06-06 14:47:32.552337698  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
s6-rc: info: service certsync successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service certsync-log: stopping
s6-rc: info: service certsync-log successfully stopped
2024-06-06 14:47:32.666546581  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2024-06-06 14:47:32.668955744  [2024-06-06 14:47:32] frigate.app                    INFO    : Stopping...
2024-06-06 14:47:32.669683138  [2024-06-06 14:47:32] frigate.storage                INFO    : Exiting storage maintainer...
2024-06-06 14:47:32.669740711  [2024-06-06 14:47:32] frigate.record.cleanup         INFO    : Exiting recording cleanup...
2024-06-06 14:47:32.669904186  [2024-06-06 14:47:32] frigate.watchdog               INFO    : Exiting watchdog...
2024-06-06 14:47:32.669918891  [2024-06-06 14:47:32] frigate.events.cleanup         INFO    : Exiting event cleanup...
2024-06-06 14:47:32.703714539  [2024-06-06 14:47:32] frigate.ptz.autotrack          INFO    : Exiting autotracker...
2024-06-06 14:47:32.704786252  [2024-06-06 14:47:32] frigate.object_processing      INFO    : Exiting object processor...
2024-06-06 14:47:32.771588937  [2024-06-06 14:47:32] frigate.events.maintainer      INFO    : Exiting event processor...
2024-06-06 14:47:36.123249790  [2024-06-06 14:47:36] frigate.stats.emitter          INFO    : Exiting stats emitter...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

dahuas all
