### DISCUSSION TITLE
[Bug]: "No Preview Found" when clicking on some (usually older) events in review section (0.14-beta2-rk)

### DISCUSSION THREAD

**Discussion by jonadis** [blakeblackshear/frigate#11783] [Report a Bug] [answered]
### Describe the problem you are having

If I go to the review section, and I click on one of the events, sometimes it will go to a screen where it says "No Preview Found" in the main pane along with several "No Preview Found" along the right edge.  If I go to that particular camera's history and then scroll back on the timeline to the point of the event, then I can watch it.

### Steps to reproduce

Click on an event in the review section.  It seems like the older the event is the more likely this is to happen.  1 hour seems to be about the threshold between working and non-working.

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.0.71.64:5000/api/config/schema
mqtt:
  host: 10.0.71.10
  user: DVES_USER
  password: _redacted_

detectors: # required
  rknn: # required
    type: rknn # required
    # number of NPU cores to use
    # 0 means choose automatically
    # increase for better performance if you have a multicore NPU e.g. set to 3 on rk3588
    num_cores: 3

model: # required
  # name of model (will be automatically downloaded) or path to your own .rknn model file
  # possible values are:
  # - deci-fp16-yolonas_s
  # - deci-fp16-yolonas_m
  # - deci-fp16-yolonas_l
  # - /config/model_cache/your_custom_model.rknn
  path: deci-fp16-yolonas_s
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolo models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

auth:
  reset_admin_password: false

birdseye:
  mode: motion

ffmpeg:
  hwaccel_args: preset-rk-h264
  output_args:
    record: preset-record-generic-audio-aac

detect:
  fps: 5
  enabled: true

objects:
  track:
    - car
    - cat
    - dog
    - person
  filters:
    car:
      min_area: 5000
      min_score: 0.6
      threshold: 0.80
    cat:
      min_area: 1000
      min_score: 0.6
      threshold: 0.80
    dog:
      min_area: 1000
      min_score: 0.6
      threshold: 0.80
    person:
      min_area: 5000
      min_score: 0.6
      threshold: 0.80

motion:
  contour_area: 20
  threshold: 40

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 14
      mode: motion

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

go2rtc:
  streams:
    chicken: rtsp://admin:admin@10.0.71.224:18554/chicken
      #esp32_cam: http://10.4.10.68:8080
    front_door: 
      rtsp://admin:_redacted_@10.0.71.131/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_door_sub: 
      rtsp://admin:_redacted_@10.0.71.131/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    front_driveway: rtsp://admin:_redacted_@10.0.71.155:554/Streaming/Channels/101
    front_driveway_sub: rtsp://admin:_redacted_@10.0.71.155:554/Streaming/Channels/102
    front_porch: 
      rtsp://admin:_redacted_@10.0.71.11/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_porch_sub: 
      rtsp://admin:_redacted_@10.0.71.11/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    garage: rtsp://admin:_redacted_@10.0.71.81:554/Streaming/Channels/101
    garage_sub: rtsp://admin:_redacted_@10.0.71.81:554/Streaming/Channels/102
    garage_se:
      - ffmpeg:http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=_redacted_#video=copy#audio=copy#audio=opus
    garage_se_sub:
      - ffmpeg:http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=_redacted_
    garage_sw:
      - ffmpeg:http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=_redacted_#video=copy#audio=copy#audio=opus
    garage_sw_sub:
      - ffmpeg:http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=_redacted_
    # garage_se: rtsp://admin:_redacted_@10.0.71.199:554/h264Preview_01_main
    # garage_se_sub: rtsp://admin:_redacted_@10.0.71.199:554/h264Preview_01_sub
    # garage_sw: rtsp://admin:_redacted_@10.0.71.161:554/h264Preview_01_main
    # garage_sw_sub: rtsp://admin:_redacted_@10.0.71.161:554/h264Preview_01_sub
    mud_room: rtsp://admin:_redacted_@10.0.70.176:554/Streaming/Channels/101
    mud_room_sub: rtsp://admin:_redacted_@10.0.70.176:554/Streaming/Channels/102
    pole_barn: rtsp://admin:_redacted_@10.0.71.219:554/Streaming/Channels/101
    pole_barn_sub: rtsp://admin:_redacted_@10.0.71.219:554/Streaming/Channels/102
    pole_barn_porch: rtsp://admin:_redacted_@10.0.71.100/Streaming/Channels/101
    pole_barn_porch_sub: rtsp://admin:_redacted_@10.0.71.100/Streaming/Channels/102
    pole_barn_south: rtsp://admin:_redacted_@10.0.70.234:554/Streaming/Channels/101
    pole_barn_south_sub: rtsp://admin:_redacted_@10.0.70.234:554/Streaming/Channels/102
    # road: rtsp://admin:_redacted_@10.0.71.155:554/Streaming/Channels/103

timestamp_style:
  effect: solid

cameras:
  chicken:
    birdseye:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/chicken
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
#  esp32_cam:
#    ffmpeg:
#      inputs:
#        - path: http://10.4.10.68:8080
#          input_args: preset-http-mjpeg-generic
#          roles:
#            - record
#            - detect
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    motion:
      mask:
        - 640,0,640,45,0,45,0,0
    zones:
      front_step:
        coordinates: 640,480,640,361,0,120,0,480
  front_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_driveway_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 1,0,1,0.451,0.547,0.171,0.536,0
        - 0,0.439,0.249,0.419,0.353,0.254,0.371,0,0,0
    objects:
      filters:
        car:
          mask:
            - 1920,635,1920,0,467,0
        cat:
          mask:
            - 1920,635,1920,0,467,0
          max_area: 50000
        dog:
          mask:
            - 1920,635,1920,0,467,0
          max_area: 50000
        person:
          mask:
            - 1920,635,1920,0,467,0
          min_area: 10000
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    zones:
      front_step:
        coordinates: 640,480,640,299,499,250,462,161,159,480
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  garage_se:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_se
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_se_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  garage_sw:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_sw
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sw_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  mud_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mud_room
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mud_room_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  pole_barn:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pole_barn
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pole_barn_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
  pole_barn_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pole_barn_porch
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pole_barn_porch_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask: 0.000,0.500,1,0.500,1,0,0,0
    objects:
      filters:
        car:
          mask:
            - 720,720,0,720,0,0,720,0
  pole_barn_south:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pole_barn_south
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pole_barn_south_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 0,120,640,120,640,0,0,0
  # road:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/road
  #         input_args: preset-rtsp-restream-low-latency
  #         roles:
  #           - detect
  #           - record
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10
  #   objects:
  #     filters:
  #       car:
  #         min_score: 0.4
  #         threshold: 0.6
  #   record:
  #     enabled: false
  #   snapshots:
  #     required_zones:
  #       - optimal
  #   zones:
  #     optimal:
  #       coordinates: 450,375,950,375,950,150,450,150
version: 0.14
```

### Relevant log output

```shell
*** These are the most relevant log files that I can find, though the timestamps do not line up with me trying to access the previews in the web interface ***

{"log":"2024-06-06 14:00:01.446809213  [2024-06-06 14:00:01] frigate.output.preview         ERROR   : Error saving preview for front_porch :: Input #0, concat, from '/dev/stdin':\
n","stream":"stdout","time":"2024-06-06T18:00:01.447088125Z"}
{"log":"2024-06-06 14:00:01.446820588    Duration: N/A, start: 0.000000, bitrate: N/A\n","stream":"stdout","time":"2024-06-06T18:00:01.447196332Z"}
{"log":"2024-06-06 14:00:01.446824379    Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 240x180, 25 fps, 25 tbr, 25 tbn\n","stream":"stdout","time":"2024-06-06T18
:00:01.447217915Z"}
{"log":"2024-06-06 14:00:01.446828754  [vost#0:0/libx264 @ 0xaaaad7e111e0] One of -r/-fpsmax was specified together a non-CFR -vsync/-fps_mode. This is contradictory.\n","stream":
"stdout","time":"2024-06-06T18:00:01.447237456Z"}
{"log":"2024-06-06 14:00:01.446832546  Error opening output file /media/frigate/clips/previews/front_porch/1717693200.184647-1717696800.160307.mp4.\n","stream":"stdout","time":"20
24-06-06T18:00:01.447256706Z"}
{"log":"2024-06-06 14:00:01.446835171  Error opening output files: Invalid argument\n","stream":"stdout","time":"2024-06-06T18:00:01.447275372Z"}
{"log":"2024-06-06 14:00:01.446837213  \n","stream":"stdout","time":"2024-06-06T18:00:01.447293164Z"}
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

This is the Rockchip build on an OrangePi5B with 16GB of RAM.
