### DISCUSSION TITLE
[Camera Support]: Reolink POE Doorbell - No audio on recordings

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#11792] [Camera Support] [answered]
### Describe the problem you are having

Hi,

I have audio on my my live views but cannot get sound on recordings after numerious iterations of the config file.  I believe I have correctly enabled audio in my config file and the audio is aac according to ffprobe. 

There are no errors in the log.  The toggling of recording in the log is before my testing of recordings.

### Version

0.3.12

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.52         # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user               # YOUR MQTT USERNAME
  password: ****                # YOUR MQTT PASSWORD
  stats_interval: 60

##########################################################################

go2rtc:
  streams:
                    ## CHANGE RTSP USERNAME AND PASSWORD
    reolink:
      - rtsp://admin:****@192.168.1.218:554/h264Preview_01_main
      - ffmpeg:rtsp://admin:****@192.168.1.218:554/h264Preview_01_main


## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

##########################################################################

record:
  enabled: True

cameras:
  reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://admin:****@192.168.1.218:554/h264Preview_01_main
          roles:
            - detect
            - record
```

### Relevant log output

```shell
2024-06-06 20:47:04.408164008  [2024-06-06 21:47:04] frigate.comms.dispatcher       INFO    : Turning off recordings for reolink
2024-06-06 20:47:05.904711051  [2024-06-06 21:47:05] frigate.comms.dispatcher       INFO    : Turning on recordings for reolink
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:****@192.168.1.218:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000313, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink POE Doorbell

### Any other information that may be helpful

MediaInfo for the audio from a file recorded via FTP:

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 47 s 936 ms
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Nominal bit rate                         : 127 kb/s
Channel(s)                               : 1 channel
Channel layout                           : M
Sampling rate                            : 16.0 kHz
Frame rate                               : 15.625 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 374 KiB (2%)
Language                                 : English

**Comment by hawkeye217** [comment]
You should use the recommended Reolink config. Search [the docs](https://docs.frigate.video) for "reolink cameras" and "reolink doorbell".

Make sure you are using the go2rtc url as your `inputs:` for the camera, eg: 
```
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
```

**Reply by ForTheRush** [reply]
The suggested config didn't work for me. After a ton of trial and error I finally got it working using 


```
cameras:
  front_door_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_door_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - 
```

**Reply by jakeycrx** [reply]
Thanks @ForTheRush Audio is now recording! Do you get audio on the live view? There's no audio on the live view for me

**Comment by jakeycrx** [comment]
I've changed the config but it seems there is no connection to the go2rtc URL

```go2rtc:
  streams:
                    ## CHANGE RTSP USERNAME AND PASSWORD
    reolink:
      - "ffmpeg:http://192.168.1.218/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.1.218/Preview_01_sub

record:
  enabled: True

cameras:
  reolink:
    ffmpeg:    
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
```

2024-06-06 22:12:41.652745676  [2024-06-06 23:12:41] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x559a45b45f40] method DESCRIBE failed: 404 Not Found
2024-06-06 22:12:41.652746698  [2024-06-06 23:12:41] ffmpeg.reolink.detect          ERROR   : rtsp://127.0.0.1:8554/reolink: Server returned 404 Not Found
2024-06-06 22:12:42.923464831  [2024-06-06 23:12:42] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2024-06-06 22:12:42.923645125  [2024-06-06 23:12:42] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
2024-06-06 22:12:51.664372974  [2024-06-06 23:12:51] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
2024-06-06 22:12:51.664544813  [2024-06-06 23:12:51] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-06-06 22:12:51.664905894  [2024-06-06 23:12:51] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x55bfa23c2f40] method DESCRIBE failed: 404 Not Found
2024-06-06 22:12:51.664975709  [2024-06-06 23:12:51] ffmpeg.reolink.detect          ERROR   : rtsp://127.0.0.1:8554/reolink: Server returned 404 Not Found
2024-06-06 22:12:52.862458995  [2024-06-06 23:12:52] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2024-06-06 22:12:52.862830169  [2024-06-06 23:12:52] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
2024-06-06 22:13:01.668484229  [2024-06-06 23:13:01] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
2024-06-06 22:13:01.668759320  [2024-06-06 23:13:01] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-06-06 22:13:01.668902971  [2024-06-06 23:13:01] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x5627a1020f40] method DESCRIBE failed: 404 Not Found
2024-06-06 22:13:01.669523003  [2024-06-06 23:13:01] ffmpeg.reolink.detect          ERROR   : rtsp://127.0.0.1:8554/reolink: Server returned 404 Not Found
2024-06-06 22:13:02.868267901  [2024-06-06 23:13:02] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2024-06-06 22:13:02.868637316  [2024-06-06 23:13:02] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
2024-06-06 22:13:11.676604411  [2024-06-06 23:13:11] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
2024-06-06 22:13:11.677963941  [2024-06-06 23:13:11] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-06-06 22:13:11.677965722  [2024-06-06 23:13:11] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x55e206711f40] method DESCRIBE failed: 404 Not Found
2024-06-06 22:13:11.677966901  [2024-06-06 23:13:11] ffmpeg.reolink.detect          ERROR   : rtsp://127.0.0.1:8554/reolink: Server returned 404 Not Found
2024-06-06 22:13:12.854750695  [2024-06-06 23:13:12] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2024-06-06 22:13:12.854965394  [2024-06-06 23:13:12] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
2024-06-06 22:13:21.686975348  [2024-06-06 23:13:21] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
2024-06-06 22:13:21.686977840  [2024-06-06 23:13:21] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-06-06 22:13:21.686978927  [2024-06-06 23:13:21] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x556644c25f40] method DESCRIBE failed: 404 Not Found
2024-06-06 22:13:21.686979929  [2024-06-06 23:13:21] ffmpeg.reolink.detect          ERROR   : rtsp://127.0.0.1:8554/reolink: Server returned 404 Not Found
2024-06-06 22:13:23.165083054  [2024-06-06 23:13:23] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2024-06-06 22:13:23.165266728  [2024-06-06 23:13:23] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...

**Reply by hawkeye217** [reply]
What do your go2rtc logs say?

**Reply by jakeycrx** [reply]
I must have made a typo somewhere. I started again from scratch and it's working now.  I used the config ForTheRush suggested and it records audio now but no audio on the live view.  Is this normal behaviour? Or should there be audio on the live view?

**Reply by jakeycrx** [reply]
The errors are back now.  This is the go2rtc log:

2024-06-07 11:46:32.498284288  [INFO] Preparing new go2rtc config...
2024-06-07 11:46:32.567810284  [INFO] Got IP address from supervisor: 192.168.1.52
2024-06-07 11:46:32.622882965  [INFO] Got WebRTC port from supervisor: 8555
2024-06-07 11:46:33.001747435  [INFO] Starting go2rtc...
2024-06-07 11:46:33.110769418  12:46:33.110 INF go2rtc version 1.8.4 linux/amd64
2024-06-07 11:46:33.111838362  12:46:33.111 INF [rtsp] listen addr=:8554
2024-06-07 11:46:33.111839974  12:46:33.111 INF [webrtc] listen addr=:8555
2024-06-07 11:46:33.113149783  12:46:33.113 INF [api] listen addr=:1984
2024-06-07 11:46:41.010817218  12:46:41.010 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout" stream=reolink
2024-06-07 11:46:42.481657485  [INFO] Starting go2rtc healthcheck service...
2024-06-07 11:46:42.518393829  12:46:42.518 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip on 127.0.0.11:53: no such host" stream=reolink
2024-06-07 11:47:05.936021997  12:47:05.935 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout, dial tcp: lookup reolink_ip on 127.0.0.11:53: no such host" stream=reolink
2024-06-07 11:47:18.511566929  12:47:18.511 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout" stream=reolink
2024-06-07 11:47:28.521879755  12:47:28.521 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout" stream=reolink
2024-06-07 11:47:35.719869496  12:47:35.719 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout, dial tcp: lookup reolink_ip on 127.0.0.11:53: no such host" stream=reolink
2024-06-07 11:47:45.936081463  12:47:45.935 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout, dial tcp: lookup reolink_ip on 127.0.0.11:53: no such host" stream=reolink
2024-06-07 11:47:55.936439448  12:47:55.936 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout, dial tcp: lookup reolink_ip on 127.0.0.11:53: no such host" stream=reolink
2024-06-07 11:48:08.582176271  12:48:08.582 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout" stream=reolink
2024-06-07 11:48:15.936135062  12:48:15.935 WRN [rtsp] error="streams: exec: exit status 1, dial tcp: lookup reolink_ip: i/o timeout, dial tcp: lookup reolink_ip on 127.0.0.11:53: no such host" stream=reolink

**Comment by jakeycrx** [comment, marked as answer]
It needs the login details in the go2rtc rtsp section.  It intially worked without it which is strange!  The docs show to enter just the IP.  

![image](https://github.com/blakeblackshear/frigate/assets/47118674/227373bc-5c43-466c-ba49-080c04c0c3a9)

I added in the ffmpeg transcode to Opus command which is now giving me audio on the live view.

```
go2rtc:
  streams:
    reolink:
      - "ffmpeg:http://192.168.1.218/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****#video=copy#audio=copy#audio=opus"
      - rtsp://admin:****@192.168.1.218:554/h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"      
record:
  enabled: True

cameras:
  reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
```
