### DISCUSSION TITLE
[Camera Support]: Reolink POE doorbell

### DISCUSSION THREAD

**Discussion by rossdargan** [blakeblackshear/frigate#11798] [Camera Support] [answered]
### Describe the problem you are having

I'm wondering what I need to do to enable two way audio within frigate for version 0.14? It works fine in home assistant for me so I think it's setup correctly for webrtc. 

### Version

0.14 beta 2

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.86.51:5000/api/config/schema
mqtt:
  host: 192.168.86.**
  topic_prefix: frigate
  client_id: frigate
  user: **
  password: **
birdseye:
  enabled: true
 # mode: continuous
go2rtc:
  streams:
    garden:
      - rtsp://admin:**@192.168.60.2:554/h264Preview_01_main
    garden_sub:
      - rtsp://admin:**@192.168.60.2:554/h264Preview_01_sub
    doorbell_sub:
      - rtsp://admin:**@192.168.60.4:554/h264Preview_01_sub
      - ffmpeg:doorbell#audio=opus#audio=volume
    doorbell:
      - rtsp://admin:**@192.168.60.4:554/
      - ffmpeg:doorbell#audio=opus#audio=volume
    indoor_sub:
      - rtsp://admin:**@192.168.60.5:554/h264Preview_01_sub
      - ffmpeg:doorbell#audio=opus#audio=volume
    indoor:
      - rtsp://admin:**@192.168.60.5:554/
      - ffmpeg:doorbell#audio=opus#audio=volume
  webrtc:
    listen: :8555
    candidates:
      - 192.168.86.60:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: true
  quality: 100
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

record:
  enabled: true
  retain:
    days: 5
    mode: all #motion 

cameras:
  doorbell:
    record:
      enabled: true
      retain:
        days: 5
        mode: all #motion 
      events:
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 2
            cat: 2
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.8
          mask:
            - 1830,1472,2474,1808,2503,686,1919,733
    audio: # <- enable audio events for camera
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000
    motion:
      threshold: 30
      contour_area: 10
      mask:
        - 351,80,767,68,765,0,0,0,0,91
    snapshots: # <----- Enable snapshots
      enabled: true
    best_image_timeout: 240
    zones:
      drive:
        inertia: 3
        coordinates: 2322,1920,1622,1525,1665,1220,1487,1158,1101,1161,1094,1019,0,984,0,1920
    ui:
      order: 0
  garden:
    record:
      enabled: true
      retain:
        days: 14
        mode: motion #motion 
      events:
        retain:
          default: 30
          mode: active_objects
          objects:
            dog: 2
            cat: 2
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.8
    audio: # <- enable audio events for camera
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 1536
      height: 576
    motion:
        # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
      threshold: 30
        # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
      contour_area: 10
      mask:
        - 0,302,457,128,471,101,769,54,1049,96,1054,123,1330,205,1341,248,1536,317,1536,0,0,0
        - 848,71,845,164,850,179,851,208,815,206,825,174
        - 572,104,580,165,560,162,555,104
    snapshots: # <----- Enable snapshots
      enabled: true
    best_image_timeout: 240
    zones:
      shed:
        coordinates: 1201,278,1230,185,1176,175,1146,233
      patio:
        coordinates: 
          1452,576,1536,467,1238,324,1037,368,793,383,531,408,344,433,209,425,136,402,65,409,143,576
    ui:
      order: 2 
  indoor:
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.60.5
      # Optional: ONVIF port for device (default: shown below).
      port: 8000
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: **
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: True
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: relative
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.75
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - cat
          - dog
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - Pet_Food
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: full room
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10

    record:
      enabled: true
      retain:
        days: 5
        mode: all #motion 
      events:
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 2
            cat: 2
    objects:
      track:
        - person
        - dog
        - cat
    audio: # <- enable audio events for camera
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    snapshots: # <----- Enable snapshots
      enabled: true
    best_image_timeout: 240
    ui:
      order: 3
    zones:
      Pet_Food:
        coordinates: 0.684,0.549,0.908,0.53,0.915,0.687,0.681,0.692
        objects:
          - cat
          - dog
    review:
      detections:
        required_zones: Pet_Food
version: 0.14
```

### Relevant log output

```shell
2024-06-07 09:50:02.720714173  [INFO] Preparing new go2rtc config...
2024-06-07 09:50:03.075004303  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-06-07 09:50:03.115721547  [INFO] Starting go2rtc...
2024-06-07 09:50:03.238742245  09:50:03.238 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-06-07 09:50:03.238745766  09:50:03.238 INF config path=/dev/shm/go2rtc.yaml
2024-06-07 09:50:03.239578924  09:50:03.239 INF [api] listen addr=:1984
2024-06-07 09:50:03.240020080  09:50:03.239 INF [rtsp] listen addr=:8554
2024-06-07 09:50:03.240744843  09:50:03.240 INF [webrtc] listen addr=:8555
2024-06-07 09:50:12.723453284  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
{
    "producers": [
        {
            "type": "RTSP active producer",
            "url": "rtsp://192.168.60.4//",
            "remote_addr": "192.168.60.4:554",
            "user_agent": "go2rtc/1.9.2",
            "sdp": "v=0\r\no=- 1717293647335244 1 IN IP4 192.168.60.4\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 8\r\na=control:track3\r\na=rtpmap:8 PCMA/8000\r\na=sendonly",
            "medias": [
                "video, recvonly, H.264 High 5.1",
                "audio, recvonly, MPEG4-GENERIC/16000",
                "audio, sendonly, PCMA/8000"
            ],
            "receivers": [
                "96 H264, bytes=1459772115, senders=3",
                "97 MPEG4-GENERIC/16000, bytes=22409364, senders=5"
            ],
            "senders": [
                "8 PCMA/8000, bytes=221120, receivers=1"
            ],
            "recv": 1495329267,
            "send": 243232
        },
        {
            "type": "RTSP passive producer",
            "url": "rtsp://127.0.0.1:8554/1225b166a9ecdd0647abf19a065e921b",
            "remote_addr": "127.0.0.1:40004",
            "user_agent": "ffmpeg/go2rtc",
            "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.9.2\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=audio 0 RTP/AVP 96\r\nb=AS:64\r\na=rtpmap:96 opus/48000/2\r\na=control:streamid=0\r\n",
            "medias": [
                "audio, recvonly, OPUS/48000/2"
            ],
            "receivers": [
                "96 OPUS/48000/2, bytes=0, senders=1"
            ]
        }
    ],
    "consumers": [
        {
            "type": "RTSP passive consumer",
            "url": "rtsp://127.0.0.1:8554/doorbell?video=copy&audio=copy",
            "remote_addr": "127.0.0.1:57346",
            "user_agent": "FFmpeg Frigate/0.14.0-bccffe6",
            "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=control:trackID=1\r\n",
            "medias": [
                "video, sendonly, ANY",
                "audio, sendonly, ANY"
            ],
            "senders": [
                "96 H264, bytes=1459772115, receivers=1",
                "97 MPEG4-GENERIC/16000, bytes=22409364, receivers=1"
            ],
            "send": 1499631895
        },
        {
            "type": "RTSP passive consumer",
            "url": "rtsp://127.0.0.1:8554/doorbell?video=copy&audio=copy",
            "remote_addr": "127.0.0.1:39932",
            "user_agent": "FFmpeg Frigate/0.14.0-bccffe6",
            "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=control:trackID=1\r\n",
            "medias": [
                "video, sendonly, ANY",
                "audio, sendonly, ANY"
            ],
            "senders": [
                "96 H264, bytes=576492801, receivers=1",
                "97 MPEG4-GENERIC/16000, bytes=8852496, receivers=1"
            ],
            "send": 592238593
        },
        {
            "type": "RTSP passive consumer",
            "url": "rtsp://127.0.0.1:8554/doorbell?audio",
            "remote_addr": "127.0.0.1:49690",
            "user_agent": "go2rtc/ffmpeg",
            "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 MPEG4-GENERIC/16000\r\na=fmtp:96 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=control:trackID=0\r\n",
            "medias": [
                "audio, sendonly, ANY"
            ],
            "senders": [
                "96 MPEG4-GENERIC/16000, bytes=3012924, receivers=1"
            ],
            "send": 3106348
        },
        {
            "type": "RTSP passive consumer",
            "url": "rtsp://127.0.0.1:8554/doorbell?audio",
            "remote_addr": "127.0.0.1:39996",
            "user_agent": "go2rtc/ffmpeg",
            "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 MPEG4-GENERIC/16000\r\na=fmtp:96 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=control:trackID=0\r\n",
            "medias": [
                "audio, sendonly, ANY"
            ],
            "senders": [
                "96 MPEG4-GENERIC/16000, bytes=1032, receivers=1"
            ],
            "send": 1064
        },
        {
            "type": "probe",
            "remote_addr": "192.168.86.203:61902",
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
            "medias": [
                "video, sendonly, ALL",
                "audio, sendonly, ALL",
                "audio, recvonly, ANY"
            ],
            "receivers": [
                "0 ANY, bytes=0, senders=1"
            ],
            "senders": [
                "96 H264, bytes=0, receivers=1",
                "97 MPEG4-GENERIC/16000, bytes=0, receivers=1",
                "96 OPUS/48000/2, bytes=0, receivers=1"
            ]
        }
    ]
}
```

### Frigate stats

```json
{
    "cameras": {
        "doorbell": {
            "audio_dBFS": -71.4435,
            "audio_rms": 8.7756,
            "camera_fps": 5.1,
            "capture_pid": 398,
            "detection_enabled": true,
            "detection_fps": 7.3,
            "ffmpeg_pid": 6922,
            "pid": 389,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "garden": {
            "audio_dBFS": -43.8734,
            "audio_rms": 209.7871,
            "camera_fps": 5.1,
            "capture_pid": 409,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 421,
            "pid": 390,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "indoor": {
            "audio_dBFS": -33.6631,
            "audio_rms": 679.6645,
            "camera_fps": 5.1,
            "capture_pid": 415,
            "detection_enabled": true,
            "detection_fps": 0.5,
            "ffmpeg_pid": 444,
            "pid": 393,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "44": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "49": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "84": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "87": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "91": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "99": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "7.9",
            "cpu_average": "8",
            "mem": "0.2"
        },
        "125": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "126": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "20.8",
            "cpu_average": "6",
            "mem": "3.3"
        },
        "134": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "149": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "150": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "151": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "152": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "153": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "297": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "321": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "335": {
            "cmdline": "frigate.recording_manager",
            "cpu": "1.9",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "339": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "363": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "364": {
            "cmdline": "frigate.detector.ov  ",
            "cpu": "24.3",
            "cpu_average": "42",
            "mem": "0.7"
        },
        "366": {
            "cmdline": "frigate.output       ",
            "cpu": "5.1",
            "cpu_average": "5",
            "mem": "0.6"
        },
        "389": {
            "cmdline": "frigate.process:doorbell",
            "cpu": "2.1",
            "cpu_average": "3",
            "mem": "0.7"
        },
        "390": {
            "cmdline": "frigate.process:garden",
            "cpu": "1.0",
            "cpu_average": "1",
            "mem": "0.7"
        },
        "393": {
            "cmdline": "frigate.process:indoor",
            "cpu": "1.0",
            "cpu_average": "2",
            "mem": "0.7"
        },
        "398": {
            "cmdline": "frigate.capture:doorbell",
            "cpu": "3.4",
            "cpu_average": "3",
            "mem": "0.6"
        },
        "409": {
            "cmdline": "frigate.capture:garden",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "415": {
            "cmdline": "frigate.capture:indoor",
            "cpu": "3.3",
            "cpu_average": "3",
            "mem": "0.6"
        },
        "421": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub?video=copy&audio=copy -r 5 -vf fps=5,scale_vaapi=w=1536:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.4",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "423": {
            "cmdline": "frigate.audio_manager",
            "cpu": "2.6",
            "cpu_average": "3",
            "mem": "0.7"
        },
        "441": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "442": {
            "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video=copy&audio=copy -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "444": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/indoor?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/indoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "5.6",
            "cpu_average": "5",
            "mem": "0.3"
        },
        "453": {
            "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub?video=copy&audio=copy -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "462": {
            "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/indoor?video=copy&audio=copy -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "476": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "481": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1536x576 -i pipe: -threads 1 -f mpegts -s 1920x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "486": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "3.5",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "491": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "692": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "6922": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-bccffe6 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "5.6",
            "cpu_average": "5",
            "mem": "0.4"
        },
        "9202": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/doorbell?audio -map 0:a:0? -c:a:0 libopus -application:a:0 lowdelay -min_comp 0 -af volume=30dB -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1225b166a9ecdd0647abf19a065e921b",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "10225": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "10253": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "48.7",
            "mem": "66.7"
        }
    },
    "detection_fps": 7.8,
    "detectors": {
        "ov": {
            "detection_start": 0,
            "inference_speed": 18.8,
            "pid": 364
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "8.01%",
            "mem": "-%"
        }
    },
    "processes": {
        "audio_detector": {
            "pid": 423
        },
        "go2rtc": {
            "pid": 99
        },
        "logger": {
            "pid": 321
        },
        "recording": {
            "pid": 335
        },
        "review_segment": {
            "pid": 339
        }
    },
    "service": {
        "last_updated": 1717752996,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 95.5,
                "mount_type": "tmpfs",
                "total": 120,
                "used": 24.5
            },
            "/media/frigate/clips": {
                "free": 35892988,
                "mount_type": "nfs4",
                "total": 66044875,
                "used": 30151359
            },
            "/media/frigate/recordings": {
                "free": 35892988,
                "mount_type": "nfs4",
                "total": 66044875,
                "used": 30151359
            },
            "/tmp/cache": {
                "free": 893.4,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 60.3
            }
        },
        "temperatures": {},
        "uptime": 2786,
        "version": "0.14.0-bccffe6"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

 Reolink Video Doorbell PoE ( DB_566128M5MP_P)
