### DISCUSSION TITLE
[Bug]: Error 'Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid'

### DISCUSSION THREAD

**Discussion by townsmcp** [blakeblackshear/frigate#11797] [Report a Bug] [answered]
### Describe the problem you are having

I have upgraded to beta v0.14.0-beta2 however I keep getting the following  error constantly in the logs:

```
Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nlibva info: VA-API version 1.17.0\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so\nlibva info: va_openDriver() returns -1\nvaInitialize failed with error code -1 (unknown libva error),exit\n"
```

<img width="378" alt="image" src="https://github.com/blakeblackshear/frigate/assets/14061617/03cbfe53-c18d-42ee-bbb3-325d2d6d696d">

I am running the following:

- Proxmox 8.2.2
- Frigate is running on Docker inside an LXC
- Kernel version - Linux 6.8.4-3-pve
- GPUs - Intel UHD Graphics for 10th Gen Intel Processors, also a NVIDIA Quadro T2000, both passed through to LXC container
- Intel GPU - /dev/dri/renderD129
- NVIDIA GPU - /dev/dri/renderD128
- CPU -  Intel i7-10850H
- Coral pcie installed

Output from Hardware Info:
```
Vainfo Output
Return Code: 3

Process Error:

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

Docker Compose:
```
version: "3.9"
services:
  frigate:
    container_name: frigate_beta14
    privileged: true
    cap_add:
        - CAP_PERFMON
        - SYS_ADMIN 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2
    runtime: nvidia
    shm_size: "192mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri:/dev/dri # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/frigate/config:/config
      - /mnt/Media/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      TZ: Europe/London
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

networks:
  proxy:
    driver: bridge
    external: true
```
I have tried also removing the NVIDIA info from docker compose but still get the same error message

I have also noticed that no events are being retained. My intention is to use Frigate for motion snapshot capture, not for full NVR.
I only want to use the Intel GPU due to the NVIDIA being in use with CompreFace which eats all the 4gb memory.
I have tried setting compose line `- /dev/dri/renderD129:/dev/dri/renderD129` but this has not worked to resolve the problem.
This same config works fine with Frigate v13, even though I was getting similar message when checking hardware info

### Steps to reproduce

Update to beta v14. Also performed a clean install of the new beta and observe the same error

### Version

0.14.0-beta2

### Frigate config file

```yaml
birdseye:
  enabled: false
mqtt:
  host: 192.168.1.198
  user: mqtt-user
  password: XXXX
ffmpeg:
  hwaccel_args: preset-vaapi
cameras:
  doorbell:
    zones:
      garden_doorbell:
        coordinates: 0,204,0,320,0,360,480,360,480,279,480,251,374,257,241,244,167,234,90,191
        objects:
          - person
          - cat
          - dog
    motion:
      mask:
        - 0,0,480,0,480,136,480,213,480,243,365,246,263,231,169,219,89,189,0,186
    objects:
      track:
        - person
        - cat
        - dog
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.198:45497/XXXXXXXXXXXXXXXXX
          roles:
            - detect
    detect:
      width: 480
      height: 360
      fps: 5
      stationary:
        interval: 1
        threshold: 50
    snapshots:
      required_zones:
        - garden_doorbell
      enabled: true
      bounding_box: true
      retain:
        default: 1
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 360
      quality: 100
detectors:
  coral1:
    type: edgetpu
    device: pci:0
objects:
  track:
    - person
    - cat
    - dog
version: 0.14
```

### Relevant log output

```shell
Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nlibva info: VA-API version 1.17.0\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so\nlibva info: va_openDriver() returns -1\nvaInitialize failed with error code -1 (unknown libva error),exit\n"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Unifi G4 Doorbell

**Comment by NickM-27** [comment]
I would suggest removing nvidia from the container and not making the container privileged

**Reply by townsmcp** [reply]
I have tried both with and without privilege.
For the nvidia gpu, do you mean from this LXC or just from the compose settings?

**Reply by NickM-27** [reply]
I mean from the compose settings, which is important to also not be privileged.

**Reply by townsmcp** [reply]
Done. Changed compose to:
```
version: "3.9"
services:
  frigate:
    container_name: frigate_beta14
    # privileged: true # this may not be necessary for all setups
    cap_add:
        - CAP_PERFMON
        - SYS_ADMIN 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2
    # runtime: nvidia
    shm_size: "192mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri:/dev/dri # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/frigate/config:/config
      - /mnt/Media/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
#      FRIGATE_RTSP_PASSWORD: "password"
      TZ: Europe/London
      # LIBVA_DRIVER_NAME: i965
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         capabilities: [gpu]

networks:
  proxy:
    driver: bridge
    external: true
```

Still getting the same error message though. Also, when I look at env variables, I see the following NVIDIA references. If I delete the 2 lines and republish, the new container has the lines back again:
<img width="1116" alt="image" src="https://github.com/blakeblackshear/frigate/assets/14061617/02d0658e-e044-4d7f-8711-845314587532">

**Reply by NickM-27** [reply]
I would maybe try overriding them with different values. Use none for the visible devices

**Reply by townsmcp** [reply]
Thank you. Sadly that hasnt worked. I added the following to the compose and republished:
```
    environment:
      TZ: Europe/London
      NVIDIA_VISIBLE_DEVICES: none
      NVIDIA_DRIVER_CAPABILITIES: compute
```

Still getting the same error:
```
Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nlibva info: VA-API version 1.17.0\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so\nlibva info: va_openDriver() returns -1\nvaInitialize failed with error code -1 (unknown libva error),exit\n"
```
