### DISCUSSION TITLE
[Bug]: [beta] Object mask editor hits delete error when pre-existing commented entry exists under object->filter in config.yml

### DISCUSSION THREAD

**Discussion by chadcrum** [blakeblackshear/frigate#11807] [Report a Bug] [answered]
### Describe the problem you are having

Hitting error when using the new Object mask editor in the UI and trying to delete an object mask where the config.yml has a pre-existing commented out value under the object to delete.

### Steps to reproduce

- Create a camera section in config.yml that contains a filter object , such as 
```
    objects:
      track:
        - person
        - dog
        - bicycle
      filters:
        dog: {}
        person:
          #min_score: 0.70
          mask: 0.675,0.29,0.83,0.458,0.895,0.342,0.764,0.188
```
- Ensure it has a commented out key/value like the above `#min_score: 0.70`
- Try to delete the object mask from the Mask and Zone Editor web UI
![image](https://github.com/blakeblackshear/frigate/assets/1462069/1f1a49f5-6a46-4016-8c7a-26194267f097)
- It will fail to delete  
![image](https://github.com/blakeblackshear/frigate/assets/1462069/9c148259-aec9-4a89-84e7-54501dc91e5f)

### Version

frigate:0.14.0-beta2

### Frigate config file

```yaml
backyard_gate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_gate
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_gate_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      backyard_z:
        coordinates: 0.009,0.004,0.657,0.009,0.673,0.076,0.999,0.323,0.993,0.996,0.011,0.988
        objects:
          - dog
          - person
    objects:
      track:
        - person
        - dog
        - bicycle
      filters:
        #dog: {}
        person:
          #min_score: 0.70
          mask: 0.675,0.29,0.83,0.458,0.895,0.342,0.764,0.188
    review:
      detections:
        required_zones: backyard_z
```

### Relevant log output

```shell
frigate    | 2024-06-07 10:32:11.790539435  [2024-06-07 10:32:11] frigate.api.app                ERROR   :
frigate    | 2024-06-07 10:32:11.790544073  Config Error:
frigate    | 2024-06-07 10:32:11.790545470
frigate    | 2024-06-07 10:32:11.790546902  Traceback (most recent call last):
frigate    | 2024-06-07 10:32:11.790548303    File "/opt/frigate/frigate/api/app.py", line 332, in config_set
frigate    | 2024-06-07 10:32:11.790549662      config_obj = FrigateConfig.parse_raw(new_raw_config)
frigate    | 2024-06-07 10:32:11.790551005    File "/opt/frigate/frigate/config.py", line 1640, in parse_raw
frigate    | 2024-06-07 10:32:11.790552231      config = load_config_with_no_duplicates(raw_config)
frigate    | 2024-06-07 10:32:11.790553831    File "/opt/frigate/frigate/util/builtin.py", line 114, in load_config_with_no_duplicates
frigate    | 2024-06-07 10:32:11.790555302      return yaml.load(raw_config, PreserveDuplicatesLoader)
frigate    | 2024-06-07 10:32:11.790557017    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate    | 2024-06-07 10:32:11.790558414      return loader.get_single_data()
frigate    | 2024-06-07 10:32:11.790559989    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
frigate    | 2024-06-07 10:32:11.790561111      node = self.get_single_node()
frigate    | 2024-06-07 10:32:11.790562878    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
frigate    | 2024-06-07 10:32:11.790564405      document = self.compose_document()
frigate    | 2024-06-07 10:32:11.790566123    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
frigate    | 2024-06-07 10:32:11.790567442      node = self.compose_node(None, None)
frigate    | 2024-06-07 10:32:11.790569164    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate    | 2024-06-07 10:32:11.790571045      node = self.compose_mapping_node(anchor)
frigate    | 2024-06-07 10:32:11.790573567    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
frigate    | 2024-06-07 10:32:11.790575612      while not self.check_event(MappingEndEvent):
frigate    | 2024-06-07 10:32:11.790577663    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
frigate    | 2024-06-07 10:32:11.790579119      self.current_event = self.state()
frigate    | 2024-06-07 10:32:11.790581324    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
frigate    | 2024-06-07 10:32:11.790583142      if self.check_token(KeyToken):
frigate    | 2024-06-07 10:32:11.790585527    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
frigate    | 2024-06-07 10:32:11.790587374      self.fetch_more_tokens()
frigate    | 2024-06-07 10:32:11.790589353    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 162, in fetch_more_tokens
frigate    | 2024-06-07 10:32:11.790591706      self.stale_possible_simple_keys()
frigate    | 2024-06-07 10:32:11.790594364    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
frigate    | 2024-06-07 10:32:11.790596440      raise ScannerError("while scanning a simple key", key.mark,
frigate    | 2024-06-07 10:32:11.790598323  yaml.scanner.ScannerError: while scanning a simple key
frigate    | 2024-06-07 10:32:11.790600538    in "<unicode string>", line 329, column 1:
frigate    | 2024-06-07 10:32:11.790602311      {}
frigate    | 2024-06-07 10:32:11.790604007      ^
frigate    | 2024-06-07 10:32:11.790605964  could not find expected ':'
frigate    | 2024-06-07 10:32:11.790607770    in "<unicode string>", line 330, column 5:
frigate    | 2024-06-07 10:32:11.790609359          review:
frigate    | 2024-06-07 10:32:11.790611045          ^
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

If I remove or un-comment
```
          #min_score: 0.70
```
it will delete successfully\.
