### DISCUSSION TITLE
[Config Support]: Multiple events for one event

### DISCUSSION THREAD

**Discussion by bearded-papa** [blakeblackshear/frigate#11817] [Config Support]
### Describe the problem you are having

I am currently getting 2 or 3 events for just one person walking past. Is there a way that I can get the software to see this as one event?
I have tried several variables in the config file but so far no luck but it is likely jsu me not being to familiar with what each one does and the values to set.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.155:5000/api/config/schema.json

mqtt:
  enabled: False

# ffmpeg:
  # : preset-rpi-64-h264 # Enable Hardware Acceleration

go2rtc:
  streams:
    Front_Garden_Sub:
      - rtsp://192.168.1.22:1024/12 # The Stream you want to detect
    # Back_Garden_Sub:
    #   - rtsp://<USER>:<PASSWORD>@192.168.1.73:554/stream2 # The Stream you want to detect

cameras:
  Front_Garden: #Name for your comment
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://192.168.1.155:8554/Front_Garden_Sub # The Stream you want to detect from go2rtc
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.22:1024/11 # The Stream you want to record
          roles:
            - record
            - audio
    audio: # <- enable audio events for all camera
      enabled: True
    onvif:
      host: 192.168.1.22
      port: 8080
      user: <USER>
      password: <PASSWORD>
    detect:
      enabled: true
      max_disappeared: 25
    record: # https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean
      enabled: true
      sync_recordings: true
      retain:
        days: 7
        mode: all
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 14
          mode: motion
          objects:
            person: 14
            car: 7

  Back_Garden: #Name for your comment
    ffmpeg:
      inputs:
        # - path: rtsp://192.168.1.155:8554/Back_Garden_Sub #The Stream you want to detect from go2rtc
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
        - path: rtsp://<USER>:<PASSWORD>@192.168.1.73:554/stream1 #The Stream you want to monitor
          roles:
            - record
    detect:
      enabled: false
    record: # https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
          objects:
            person: 14
            car: 7
```

### Relevant log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
