### DISCUSSION TITLE
[Bug]: [beta] Refreshing the UI Settings page causes no camera to be selected and black screen with spinner

### DISCUSSION THREAD

**Discussion by chadcrum** [blakeblackshear/frigate#11810] [Report a Bug] [answered]
### Describe the problem you are having

Refreshing the "Settings" page (ie http://<frigate_ip>:5000/settings) un-selects all cameras, so the user is then presented with a black screen for "Mask Zones", "Motion Tuner", and "Debug" until they select a camera. 

### Steps to reproduce

- Browse to settings page - http://<frigate_ip>:5000/settings
- Select Mask/Zones, Motion Tuner, or Debug links
- By default the first camera in alphabetical order is automatically selected
- Refresh the browser
- User is brought back to the "General" tab
- Now user again selects Mask/Zones, Motion Tuner, or Debug links
- User is presented with a black screen and spinning circle as all cameras have been un-selected

https://github.com/blakeblackshear/frigate/assets/1462069/f8c736c5-f0f7-4a44-b14d-fc90bee15166

### Version

frigate:0.14.0-beta2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.50
  enabled: true
  # user: mqtt
  # password: mqtt
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  timestamp: true
  bounding_box: true



logger:
  default: info

detectors:
  coral1:
    type: edgetpu
    device: usb:0
live:
  quality: 3

detect:
  enabled: true

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 2
    post_capture: 2
    # retain:
    #   default: 7
    #   mode: motion

birdseye:
  enabled: true
  mode: continuous
  quality: 7
  restream: true

objects:
  track:
    - person
    - car
    - bicycle
    - dog
    - bus
    - motorcycle

# motion:
#   contour_area: 25
#   threshold: 15
#   improve_contrast: false




go2rtc:
  webrtc:
    candidates:
      - 192.168.1.65:8555
  streams:
    upstairs_hallway:
      - rtsp://<redacted>.23:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    upstairs_hallway_sub:
      - rtsp://<redacted>.23:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    bonus_room:
      - rtsp://<redacted>.16:8554/Streaming/Channels/101#backchannel=0
    bonus_room_sub:
      - rtsp://<redacted>.16:8554/Streaming/Channels/102#backchannel=0
    living_room:
    #- rtsp://<redacted>.15:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - rtsp://<redacted>.15:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    living_room_sub:
      - rtsp://<redacted>.15:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    kitchen:
      - rtsp://<redacted>.14:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    kitchen_sub:
      - rtsp://<redacted>.14:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    entrance_way:
      - rtsp://<redacted>.10:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    entrance_way_sub:
      - rtsp://<redacted>.10:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    garage:
      - rtsp://<redacted>.19:8554/Streaming/Channels/101
    garage_sub:
      - rtsp://<redacted>.19:8554/Streaming/Channels/102
    rando_cam:
      - rtsp://<redacted>.22:8554/Streaming/Channels/101
    rando_cam_sub:
      - rtsp://<redacted>.22:8554/Streaming/Channels/102
    back_porch:
      - rtsp://<redacted>.11:554/cam/realmonitor?channel=1&subtype=0
    back_porch_sub:
      - rtsp://<redacted>.11:554/cam/realmonitor?channel=1&subtype=1
    backyard:
      - rtsp://<redacted>.12:554/cam/realmonitor?channel=1&subtype=0
    backyard_sub:
      - rtsp://<redacted>.12:554/cam/realmonitor?channel=1&subtype=1
    backyard_gate:
      - rtsp://<redacted>.13:554/cam/realmonitor?channel=1&subtype=0
    backyard_gate_sub:
      - rtsp://<redacted>.13:554/cam/realmonitor?channel=1&subtype=1
    backyard_left:
      - rtsp://<redacted>.21:554/cam/realmonitor?channel=1&subtype=0
    backyard_left_sub:
      - rtsp://<redacted>.21:554/cam/realmonitor?channel=1&subtype=1
    drive_way:
      - rtsp://<redacted>.18:554/cam/realmonitor?channel=1&subtype=0
    drive_way_sub:
      - rtsp://<redacted>.18:554/cam/realmonitor?channel=1&subtype=1
    front_yard:
      - rtsp://<redacted>.17:554/cam/realmonitor?channel=1&subtype=0
    front_yard_sub: rtsp://<redacted>.17:554/cam/realmonitor?channel=1&subtype=1


timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
cameras:
  upstairs_hallway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/upstairs_hallway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/upstairs_hallway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true

    motion:
      threshold: 65
      contour_area: 10
      improve_contrast: 'true'
  bonus_room:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/bonus_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bonus_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true

  living_room:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true

  kitchen:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true

  entrance_way:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_way
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrance_way_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true

  rando_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/rando_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rando_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true

  ####################################################################################################
  #
  # GERRRRAGE
  #
  ####################################################################################################

  garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 60
    objects:
      track:
        - person
        - car
      filters:
        person:
          #min_score: 0.75
          min_area: 500
          max_area: 2800
        car:
          min_area: 10000
          min_score: 0.75

  ####################################################################################################
  #
  # Back Yard Cameras
  #
  ####################################################################################################
  back_porch:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      backyard_z:
        coordinates: 0,480,640,480,640,0,0,0
    objects:
      track:
        - person
        - dog
      #the ratio is the width in pixels of the bounding box divided by the height. So a ratio of 1 would be a square, 0.5 would be a tall skinny box and 2 would be a wide flat box.
      filters:
        person:
          max_ratio: 0.5

    motion:
      threshold: 51
      contour_area: 10
      improve_contrast: 'true'
  backyard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      backyard_z:
        coordinates: 0,480,640,480,640,0,0,0

    motion:
      threshold: 42
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.81,0.058,0.957,0.055,0.959,0.112,0.802,0.117
  backyard_gate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_gate
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_gate_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      backyard_z:
        coordinates: 0.009,0.004,0.657,0.009,0.673,0.076,0.999,0.323,0.993,0.996,0.011,0.988
        objects:
          - dog
          - person
    objects:
      track:
        - person
        - dog
        - bicycle
      filters:
        #dog: {}
        person:
          min_score: 0.70
    review:
      detections:
        required_zones: backyard_z
  backyard_left:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_left
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_left_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      backyard_z:
        coordinates: 704,480,704,90,503,0,295,0,0,0,0,480

  ####################################################################################################
  #
  # Front Yard Cameras
  #
  ####################################################################################################
  # test:
  #   ffmpeg:
  #     inputs:
  #       #- path: /media/frigate/recordings/test/05.38.mp4
  #       #- path: /media/frigate/recordings/test/front_yard_card_high_res.mp4
  #       - path: /media/frigate/recordings/test/driveway_high_def_car.mp4
  #         input_args: -re -stream_loop -1 -fflags +genpts
  #         roles:
  #           - detect
  #   detect:
  #     height: 1080
  #     width: 1920
  #     fps: 5
  ########################################################################
  ## Drive Way Start
  ########################################################################   
  drive_way:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/drive_way
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drive_way_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      front_yard_z:
        coordinates: 704,480,0,480,0,244,233,106,285,87,374,96,540,124,704,187
        objects:
          - person
          - dog
          - bicycle
      sidewalk_street_z:
        coordinates: 164,53,375,55,508,82,648,112,704,137,704,85,487,27,270,21,148,29,114,47
        objects:
          - person
          - dog
          - bicycle

      # Car must hit this or other steet zone + drivway_z to be counted as entering/leaving driveway
      street_left_z:
        coordinates: 387,90,435,40,364,33,323,82
        objects:
          - car
      street_right_z:
        coordinates: 664,77,704,88,704,184,659,158
        objects:
          - car
      driveway_z:
        coordinates: 0,480,450,480,528,342,226,233,0,382
        objects:
          - car

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - front_yard_z
        - sidewalk_street_z
        - street_left_z
        - street_right_z
        - driveway_z
    objects:
      track:
        - person
        - dog
        - bicycle
        - car

    review:
      alerts:
        required_zones:
          - front_yard_z
          - sidewalk_street_z
          - street_left_z
          - street_right_z
          - driveway_z
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'

      
  ######################################################################################3
  ## Front Yard
  ######################################################################################
  front_yard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    #the ratio is the width in pixels of the bounding box divided by the height. So a ratio of 1 would be a square, 0.5 would be a tall skinny box and 2 would be a wide flat box.
    objects:
      track:
        - person
        - dog
        - bicycle
      filters:
        person:
          #min_area: 100          
          mask:
            # fire hydrant and green box
            - 499,82,536,99,569,132,522,156,474,107
        dog:
          #min_area: 100
          mask:
            # fire hydrant and green box
            - 499,82,536,99,569,132,522,156,474,107
    zones:
      front_yard_z:
        coordinates: 0,480,704,480,704,349,470,95,265,135,0,204
        objects:
          - person
          - dog
          - bicycle
      sidewalk_street_z:
        coordinates: 
          0,136,112,88,241,51,337,33,445,24,530,23,592,23,657,32,704,39,704,69,638,61,414,78,282,100,163,132,0,197
        objects:
          - person
          - dog
          - bicycle
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - front_yard_z
        - sidewalk_street_z
    # motion:
    #   contour_area: 40
    #   threshold: 35
    #   improve_contrast: false


  ########################################################################
  ## Front YARD End
  ########################################################################   



# Optional
    review:
      alerts:
        required_zones:
          - front_yard_z
          - sidewalk_street_z


    motion:
      threshold: 33
      contour_area: 10
      improve_contrast: 'true'
version: 0.14
camera_groups:
  Front_Yard:
    order: 1
    icon: LuStepForward
    cameras:
      - front_yard
      - drive_way
      - garage
  Upstairs:
    order: 2
    icon: LuArrowBigUp
    cameras:
      - upstairs_hallway
      - rando_cam
      - bonus_room
  Downstairs:
    order: 3
    icon: LuArrowBigDown
    cameras:
      - kitchen
      - living_room
      - garage
      - entrance_way
  Backyard:
    order: 4
    icon: LuSkipBack
    cameras:
      - back_porch
      - backyard
      - backyard_gate
      - backyard_left
```

### Relevant log output

```shell
no relevant log output in docker container or dev console
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

na
