### DISCUSSION TITLE
[Camera Support]: Foscam R5 reporting 401s

### DISCUSSION THREAD

**Discussion by Chaoscontrol** [blakeblackshear/frigate#11814] [Camera Support] [answered]
### Describe the problem you are having

I've been using this camera (named backgarden) for months. Have 2 of the same model, firmware, password... everything (livingroom is the other one). After updating to HA 2024.6 I suddenly noticed that when trying to access this camera (backgarden) recordings to review, it showed me a Frigate login page (I had never seen this before). 

It doesn't happen with the other same model camera, or any other cameras. 

After asking in Discord, I was told to check browser logs and found several 401 errors for this camera, both in Review and in Live View too (it doesn't load the thumbnail preview shows the login page. 

Blake suggested to change the camera password to a simpler one, as mine had some symbol. I did, used `12345a` but it made no difference. And again, the other camera of the same model also had same password with no issues. 

I checked the camera via app and it connects fine. No drops. And user access logs show no login errors. 
Go2rtc also shows 3 or 4 connections fine (prob mobile app, desktop app, Frigate, and ONVIF maybe)

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: frigate
  password: redacted

# logger:
#   logs:
#     frigate.record.util: debug

go2rtc:
  log:
    #level: trace
    #api: trace
    #exec: trace
    #ngrok: trace
    #rtsp: trace
    #streams: trace
    #webrtc: trace

  # AAC Audio required for recordings, Opus required for webRTC Live View
  streams:
    doorbell: # Reolink Doorbell WiFi
      - rtsp://admin:redacted@192.168.1.232:554/h264Preview_01_main
      - ffmpeg:doorbell#audio=aac#audio=volume
      - ffmpeg:doorbell#audio=opus#audio=volume
    reolink: # Reolink E1 Pro broken night vision
      - rtsp://admin:redacted@192.168.1.138:554/h264Preview_01_main
      - ffmpeg:reolink#audio=aac#audio=volume
      - ffmpeg:reolink#audio=opus#audio=volume
    bedroom: # Reolink E1 Pro
      - rtsp://admin:redacted@192.168.1.216:554/h264Preview_01_main
      - ffmpeg:bedroom#audio=aac#audio=volume
      - ffmpeg:bedroom#audio=opus#audio=volume
    backgarden: # Foscam R5
      - ffmpeg:rtsp://foscamadmin:12345a@192.168.1.177:88/videoMain
      - ffmpeg:backgarden#audio=aac#audio=volume
      - ffmpeg:backgarden#audio=opus#audio=volume
    livingroom: # Foscam R5
      - ffmpeg:rtsp://foscamadmin:redacted@192.168.1.239:88/videoMain
      - ffmpeg:livingroom#audio=aac#audio=volume
      - ffmpeg:livingroom#audio=opus#audio=volume

  ## Frigate docs recommend HTTP+FLV connection for Reolink Doorbell, but only RTSP allows for 2-way audio
  ## #video=copy is needed for a single line ffmpeg config when using audio tags, or else video stream is dropped


## THIS INCREASES VOL AND PREVENTS THE AUDIO COMING OUT FROM THE CAMERA SOUNDING MUFFLED
## Source https://www.youtube.com/watch?v=upXyBVMR4RM

  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

cameras:
  doorbell:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
            - detect
            - audio
    audio:
      enabled: true
    #birdseye:
    #  order: 1
    zones:
      Front_garden:
        coordinates: 
          0.143,0.527,0.143,0.561,0.373,0.563,0.613,0.56,0.609,0.523,0.885,0.557,0.874,0.704,0.993,0.751,0.995,0.999,0.002,0.999,0,0.557
      Driveway/Neighbours:
        coordinates: 
          0.851,0.516,0.898,0.502,1,0.502,1,0.588,0.973,0.732,0.876,0.703,0.887,0.555,0.834,0.545
    review:
      detections:
        required_zones:
          - Front_garden
          - Driveway/Neighbours
    motion:
      mask: 
        0,0.429,0.122,0.421,0.198,0.33,0.56,0.331,0.589,0.434,0.871,0.412,0.896,0.389,0.975,0.436,0.999,0.436,0.999,0.003,0.002,0
  bedroom:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom
          roles:
            - record
            - detect
            - audio
    audio:
      enabled: true
    #birdseye:
    #  order: 2
    onvif:
      host: 192.168.1.216
      port: 8000
      user: admin
      password: redacted
  reolink:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          roles:
            - record
            - detect
            - audio
    #birdseye:
    #  order: 2
    onvif:
      host: 192.168.1.138
      port: 8000
      user: admin
      password: redacted
  backgarden:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backgarden
          roles:
            - record
            - detect
            - audio
    #birdseye:
    #  order: 3
    # onvif:
    #   host: 192.168.1.177
    #   port: 888
    #   user: foscamadmin
    #   password: 8LqM7qBX2AX^
    motion:
      mask:
        - 0,0,0,0.471,0.247,0.445,0.275,0.492,0.39,0.492,0.441,0.492,0.56,0.459,0.677,0.439,0.786,0.309,0.768,0.113,0.761,0.003
        - 0.64,0.373,0.578,0.579,0.688,0.708,0.768,0.719,0.803,0.697,0.792,0.292
  livingroom:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/livingroom
          roles:
            - record
            - detect
            - audio
    #birdseye:
    #  order: 4
    onvif:
      host: 192.168.1.239
      port: 888
      user: foscamadmin
      password: redacted

## Intel N5095, SSD 256GB, 8GB RAM

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  ov:
    type: openvino
    device: AUTO

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  path: /openvino-model/ssdlite_mobilenet_v2.xml

record:
  enabled: true
  # sync_recordings: true
  retain:
    days: 1 #default=0
    mode: motion #default
  events:
    retain:
      default: 5
      mode: motion
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case. 
    # x4=0.25, x8=0.125, x16=0.0625
    timelapse_args: -vf setpts=0.125*PTS

motion:
  threshold: 50 # 0-255 default=30 Less is more sensitive (was using 150 for months)
  improve_contrast: true

snapshots:
 enabled: True
 retain:
   default: 10 #days

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - cat
  filters:
    person:
      threshold: 0.8
      min_score: 0.65
    # cat:
    #   threshold: 0.8

review:
  alerts:
    labels:
     - bark

audio:
  enabled: true
  listen:
    - scream
    - yell
    - laughter

#birdseye:
#  enabled: True
#  mode: continuous

#ui:
  #live_mode: webrtc
camera_groups:
  Outdoors:
    order: 2
    icon: LuTrees
    cameras:
      - backgarden
      - doorbell
  Indoors:
    order: 1
    icon: LuHome
    cameras:
      - bedroom
      - livingroom
      - reolink
version: 0.14
```

### Relevant log output

```shell
Nothing relevant in logs. 
Browser logs when preview and live view (when it loads): https://xfiles.s-ul.eu/cVV1DI2w
```

### FFprobe output from your camera

```shell
{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/f83cf02ecb61dfc6ed4b2bb8abb76701",
      "remote_addr": "127.0.0.1:32996",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=IP Camera Video\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z0IAMukAUAHjQgAAB9IAAdU4CA==,aMqPIAA=; profile-level-id=420032\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 0\r\nb=AS:64\r\na=control:streamid=1\r\n",
      "medias": [
        "video, recvonly, H.264 Baseline 5.0",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=2800724811, senders=3",
        "0 PCMU/8000, bytes=28466880, senders=3"
      ],
      "recv": 2853586047
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/cf65ddbae0bc4dce778970af4d36f683",
      "remote_addr": "127.0.0.1:33032",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.9.2\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=audio 0 RTP/AVP 96\r\nb=AS:48\r\na=rtpmap:96 MPEG4-GENERIC/8000/1\r\na=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:streamid=0\r\n",
      "medias": [
        "audio, recvonly, MPEG4-GENERIC/8000"
      ],
      "receivers": [
        "96 MPEG4-GENERIC/8000, bytes=16016470, senders=3"
      ],
      "recv": 16203922
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/80bf85183cd21b426a58291d8e32528e",
      "remote_addr": "127.0.0.1:37714",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.9.2\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=audio 0 RTP/AVP 96\r\nb=AS:64\r\na=rtpmap:96 opus/48000/2\r\na=control:streamid=0\r\n",
      "medias": [
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 OPUS/48000/2, bytes=0, senders=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/backgarden?audio",
      "remote_addr": "127.0.0.1:33006",
      "user_agent": "go2rtc/ffmpeg",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 PCMU/8000\r\na=control:trackID=0\r\n",
      "medias": [
        "audio, sendonly, ANY"
      ],
      "senders": [
        "96 PCMU/8000, bytes=28466880, receivers=1"
      ],
      "send": 29415776
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/backgarden",
      "remote_addr": "127.0.0.1:32962",
      "user_agent": "FFmpeg Frigate/0.14.0-bccffe6",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z0IAMukAUAHjQgAAB9IAAdU4CA==,aMqPIAA=; profile-level-id=420032\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=2800724811, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=16016470, receivers=1"
      ],
      "send": 2848175280
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/backgarden",
      "remote_addr": "127.0.0.1:32986",
      "user_agent": "FFmpeg Frigate/0.14.0-bccffe6",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z0IAMukAUAHjQgAAB9IAAdU4CA==,aMqPIAA=; profile-level-id=420032\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=2800724811, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=16016470, receivers=1"
      ],
      "send": 2848136904
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/backgarden?audio",
      "remote_addr": "127.0.0.1:37710",
      "user_agent": "go2rtc/ffmpeg",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 PCMU/8000\r\na=control:trackID=0\r\n",
      "medias": [
        "audio, sendonly, ANY"
      ],
      "senders": [
        "96 PCMU/8000, bytes=1440, receivers=1"
      ],
      "send": 1488
    },
    {
      "type": "probe",
      "remote_addr": "174.216.246.233, 172.30.32.1:51866",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "0 PCMU/8000, bytes=0, receivers=1",
        "96 MPEG4-GENERIC/8000, bytes=0, receivers=1",
        "96 OPUS/48000/2, bytes=0, receivers=1"
      ]
    }
  ]
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Foscam R5

### Any other information that may be helpful

Preview (shows 401 in browser console): 
![image](https://github.com/blakeblackshear/frigate/assets/6642238/a19de1a7-1420-4a0d-b2a3-d06f37d6b7e0)
![image](https://github.com/blakeblackshear/frigate/assets/6642238/0602d621-72b6-4010-b15e-7e8cdfae1b72)
![image](https://github.com/blakeblackshear/frigate/assets/6642238/2daa5a82-0d3b-4eeb-bc24-6991b1222eb2)

Live view showed login page at the beginning. After tests and changing password now it seems to load, still showing 401 errors in browser console. 

Review still shows login page consistently. 401 in browser console: 
![image](https://github.com/blakeblackshear/frigate/assets/6642238/5a588a2a-03cb-4821-b030-49accd7f7e04)

Frigate seems to be able to connected, since frames seem to being processed:
![image](https://github.com/blakeblackshear/frigate/assets/6642238/75287258-7d7e-487a-8eb1-98d36a1cdb39)
