### DISCUSSION TITLE
[0.14.0 beta2] extra fields not permitted (type=value_error.extra)

### DISCUSSION THREAD

**Discussion by pathia** [blakeblackshear/frigate#11813] [Config Support] [answered]
### Describe the problem you are having

My properly working config for 0.13.2-6476f8a
has a problem in 0.14.0beta:
frigate  | 2024-06-07 22:59:15.218389802  cameras.cam1.ffmpeg.inputs.1.roles.1: Input should be 'audio', 'record' or 'detect'
frigate  | 2024-06-07 22:59:15.218512669  cameras.cam2.ffmpeg.inputs.1.roles.1: Input should be 'audio', 'record' or 'detect'
frigate  | 2024-06-07 22:59:15.218519492  cameras.cam3.ffmpeg.inputs.1.roles.1: Input should be 'audio', 'record' or 'detect'
any ideas what could cause this ?

### Version

0.14.0.beta2

### Frigate config file

```yaml
cameras:
  deurbel:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
      inputs:
        - path: 
            rtmp://myip/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
            - detect
        - path: 
            rtmp://myip/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
            - record
            - rtmp
```

### Relevant log output

```shell
frigate  | 2024-06-07 23:37:49.880100644  *************************************************************
frigate  | 2024-06-07 23:37:49.880150124  *************************************************************
frigate  | 2024-06-07 23:37:49.880154603  ***    Your config file is not valid!                     ***
frigate  | 2024-06-07 23:37:49.880164551  ***    Please check the docs at                           ***
frigate  | 2024-06-07 23:37:49.880169447  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2024-06-07 23:37:49.880172833  *************************************************************
frigate  | 2024-06-07 23:37:49.880205073  *************************************************************
frigate  | 2024-06-07 23:37:49.880209448  ***    Config Validation Errors                           ***
frigate  | 2024-06-07 23:37:49.880251792  *************************************************************
frigate  | 2024-06-07 23:37:49.880349086  cameras.cam1.ffmpeg.inputs.1.roles.1: Input should be 'audio', 'record' or 'detect'
frigate  | 2024-06-07 23:37:49.880376430  cameras.cam2.ffmpeg.inputs.1.roles.1: Input should be 'audio', 'record' or 'detect'
frigate  | 2024-06-07 23:37:49.880397941  cameras.cam3.ffmpeg.inputs.1.roles.1: Input should be 'audio', 'record' or 'detect'
frigate  | 2024-06-07 23:37:49.880401431  *************************************************************
frigate  | 2024-06-07 23:37:49.880421275  ***    End Config Validation Errors                       ***
frigate  | 2024-06-07 23:37:49.880424713  *************************************************************
```

### Frigate stats

```json
{"message":"Camera not found","success":false}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
