### DISCUSSION TITLE
error message at startup

### DISCUSSION THREAD

**Discussion by sys1aeg** [blakeblackshear/frigate#11823] [Config Support]
### Describe the problem you are having

hi just started 0.14.0-beta2 getting a hard error at startup 
" ValueError: Camera front_house has a required zone for detections zone_1 that is not defined." .  I have defined the zone in both review and snapshot. also the strange thing that the zone_1 is for the backyard camera not the front house 

### Version

0.14.0-beta2 

### Frigate config file

```yaml
mqtt:
  enabled: true
  # Required: host name
  host: x.x.x.x
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user:x 
  # Optional: 
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxxxxxx

detectors:
  detector_name:
    type: edgetpu

database:
  # The path to store the SQLite DB 
  path: /home/frigate/frigate.db

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

# Optional: Review configuration
# NOTE: Can be overridden at the camera level
review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - car
      - person
    # Optional: required zones for an object to be marked as an alert (default: none)
    required_zones:
      - zone_0
      - zone_1
      - zone_2
      - zone_3
      - zone_4
      - zone_5
      - zone_6
  # Optional: detections configuration
  detections:
    # Optional: labels that qualify as a detection (default: all labels that are tracked / listened to)
    labels:
      - car
      - person
    # Optional: required zones for an object to be marked as a detection (default: none)
    required_zones:
      - nydriveway
      - zone_1
      - zone_2
      - zone_3
      - zone_4
      - zone_5
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car 

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: False
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 1

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones:
    - nydriveway
    - zone_1
    - zone_2
    - zone_3
    - zone_4
    - zone_5
    
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 5
      car: 5

go2rtc:
  streams:
    back_yard:
      - rtsp://x:x@x:554//h264Preview_01_sub
  #
    ny_doorbell:
      - rtsp://x:x@x:554//h264Preview_01_sub
  #  
  # 
#### ended here 
cameras:
#
# 
#
#


  front_house:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://x:x@x:554//h264Preview_01_sub
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    zones:
      nydriveway:
        coordinates: 512,79,439,328,272,360,60,280,236,111
        objects:
          - person
          - car
        filters:
          persons:
            threshold: 0.8 #0.75
            min_area: 5000
    motion:
      mask:
        - 432,0,373,104,180,67,184,0
  back_yard:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://x:x@x:554//h264Preview_01_sub
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    zones:
      zone_1:
        coordinates: 551,109,602,451,22,458,23,101
  #


version: 0.14
```

### Relevant log output

```shell
024-06-08 20:37:51.458947300  ***    Config Validation Errors                                                                        ***
2024-06-08 20:37:51.458949874  *************************************************                                             ************
2024-06-08 20:37:51.459066744  Camera front_house has a required zone for detect                                             ions zone_1 that is not defined.
2024-06-08 20:37:51.461708654  Traceback (most recent call last):
2024-06-08 20:37:51.461724043    File "/opt/frigate/frigate/app.py", line 644, i                                             n start
2024-06-08 20:37:51.461726006      self.init_config()
2024-06-08 20:37:51.461728691    File "/opt/frigate/frigate/app.py", line 140, i                                             n init_config
2024-06-08 20:37:51.461731191      self.config = user_config.runtime_config(self                                             .plus_api)
2024-06-08 20:37:51.461733913    File "/opt/frigate/frigate/config.py", line 156                                             0, in runtime_config
2024-06-08 20:37:51.461736247      verify_required_zones_exist(camera_config)
2024-06-08 20:37:51.461739247    File "/opt/frigate/frigate/config.py", line 127                                             1, in verify_required_zones_exist
2024-06-08 20:37:51.461741117      raise ValueError(
2024-06-08 20:37:51.461744302  ValueError: Camera front_house has a required zon                                             e for detections zone_1 that is not defined.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by hawkeye217** [comment]
You've placed your `review` configuration at the global level, which requires you to have all of the zones you've defined globally to exist in every one of your cameras. The reason why you're gettting an error is because you haven't defined `zone_1` for the `front_house` camera.

You should be specifying the `review` configuration *at the camera level*, and defining which zones in each camera you want to appear in alerts and detections.

For example:

```
cameras:
  front_house:
    ffmpeg:
     ...
    zones:
      nydriveway:
        coordinates: 512,79,439,328,272,360,60,280,236,111
        objects:
          - person
          - car
        filters:
          persons:
            threshold: 0.8 #0.75
            min_area: 5000
    motion:
      mask:
        - 432,0,373,104,180,67,184,0
     review:
       alerts:
         required_zones:
           - nydriveway
  back_yard:
    ffmpeg:
    ...
    zones:
      zone_1:
        coordinates: 551,109,602,451,22,458,23,101
    review:
      detections:
        required_zones:
          - zone_1
```

Search [the beta docs](https://deploy-preview-11419--frigate-docs.netlify.app) for "zones": https://deploy-preview-11419--frigate-docs.netlify.app/configuration/zones#restricting-alerts-and-detections-to-specific-zones
