### DISCUSSION TITLE
[Config Support]: Cannot seem to get Birdseye restream to work

### DISCUSSION THREAD

**Discussion by sydneyjd** [blakeblackshear/frigate#11824] [Config Support]
### Describe the problem you are having

Hello, 
This may be a simple fix, however I have been trying to wrap my head around what is going on, and am not making sense of it. Running Debian 12 with Frigate installed via Docker compose. I have been trying to enable the RTSP restream feed from Birdseye so I can pipe it into VLC on my main NVR viewing computer, however, I have not been having much sucess, and haven't figured out what is wrong. Go2rtc doesn't appear to be showing any errors, and i'm not quite sure how to dig further.
Can you help me figure out what i'm missing here? Thank you for your time.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
logger:
  default: debug
  
go2rtc:
  log:
    exec: trace

mqtt:
  enabled: false

detectors:
  coral1:
    type: edgetpu
    device: pci:0

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  restream: true
  mode: continuous


objects:
  track:
  - person
  - car
  - truck
  - hat
  - shoe
  - chair
  - cat



cameras:
  Radar:

    ffmpeg:
      inputs:
        - path: /radarimage/image.jpeg

      input_args:
      - -framerate
      - 2
      - -re
      - -thread_queue_size
      - 512
      - -f
      - image2
      - -loop 
      - 1
      - -an
      output_args:
        detect:
          -filter:v fps=2
          -f rawvideo
          -pix_fmt yuv420p
          -an
    detect:
      enabled: false

  MaternityPen1:
    ffmpeg:
      inputs:
      - path: rtsp://root:password@192.168.1.12/axis-media/media.amp
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion
    onvif:
      host: 192.168.1.12
      port: 80
      user: root
      password: password

  MaternityPen2:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.13/user=admin&password=hehehoho&channel=1&stream=1.sdp?
        roles:
        - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion

  CalfBarn1:
    ffmpeg:
      inputs:
      - path: rtsp://root:password@192.168.1.10/axis-media/media.amp
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion
    onvif:
      host: 192.168.1.10
      port: 80
      user: root
      password: password

  CalfBarn2:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.11/user=admin&password=hehehoho&channel=1&stream=1.sdp?
        roles:
        - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion

    motion:
      mask:
      - 1280,0,1052,0,1086,108,1280,85
    objects:
      filters:
        car:
          mask:
            - 1280,0,1280,720,0,720,0,0
  Parlor:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:admin@192.168.1.14:554/user=admin_password=6QNMIQGe_channel=1_stream=0.sdp
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion
    motion:
      mask:
      - 0,0,174,540,494,159,462,0
      - 1008,480,1280,510,1280,0,748,0,748,117


  NorthBarnCam:
    ffmpeg:
      inputs:
      - path: 
          rtmp://192.168.1.15/bcs/channel0_main.bcs?channel=0&stream=1&user=admin&password=password
        input_args: preset-rtmp-generic
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion


    objects:
      filters:
        car:
          mask:
          - 1280,197,0,378,0,720,1280,720
  WestBarnCam:
    ffmpeg:
      inputs:
      - path: 
          rtmp://192.168.1.16/bcs/channel0_main.bcs?channel=0&stream=1&user=admin&password=password
        input_args: preset-rtmp-generic
        roles:
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion

    objects:
      filters:
        car:
          mask:
          - 0,37,0,334,1280,321,1280,85
  WorkshopSouth:
    ffmpeg:
      inputs:
      - path: rtsp://root:password@192.168.1.17/axis-media/media.amp
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 90
          mode: motion
    motion:
      mask:
      - 716,80,724,23,692,24,654,21,632,82
    onvif:
      host: 192.168.1.17
      port: 80
      user: root
      password: password

#        - path: rtsp://admin:password@192.168.1.16/Preview_01_main
```

### Relevant log output

```shell
2024-06-08 22:41:38.233642008  [INFO] Preparing new go2rtc config...
2024-06-08 22:41:38.506627567  [INFO] Starting go2rtc...
2024-06-08 22:41:38.582038926  22:41:38.581 INF go2rtc version 1.8.4 linux/amd64
2024-06-08 22:41:38.582505492  22:41:38.582 INF [rtsp] listen addr=:8554
2024-06-08 22:41:38.582544817  22:41:38.582 INF [api] listen addr=:1984
2024-06-08 22:41:38.583120387  22:41:38.583 INF [webrtc] listen addr=:8555
2024-06-08 22:41:48.231877290  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"CalfBarn1":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":372,"detection_enabled":1,"detection_fps":12.1,"ffmpeg_pid":397,"pid":348,"process_fps":5.1,"skipped_fps":0.0},"CalfBarn2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":379,"detection_enabled":1,"detection_fps":4.4,"ffmpeg_pid":419,"pid":349,"process_fps":5.1,"skipped_fps":0.0},"MaternityPen1":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":367,"detection_enabled":1,"detection_fps":20.2,"ffmpeg_pid":387,"pid":343,"process_fps":5.1,"skipped_fps":0.0},"MaternityPen2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":370,"detection_enabled":1,"detection_fps":9.7,"ffmpeg_pid":376,"pid":345,"process_fps":5.1,"skipped_fps":0.0},"NorthBarnCam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":385,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":418,"pid":355,"process_fps":5.1,"skipped_fps":0.0},"Parlor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":382,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":395,"pid":353,"process_fps":5.1,"skipped_fps":0.0},"Radar":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":366,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":386,"pid":338,"process_fps":5.0,"skipped_fps":0.0},"WestBarnCam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":408,"detection_enabled":1,"detection_fps":2.8,"ffmpeg_pid":453,"pid":357,"process_fps":5.1,"skipped_fps":0.0},"WorkshopSouth":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":412,"detection_enabled":1,"detection_fps":19.0,"ffmpeg_pid":461,"pid":359,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.2"},"105":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"8.0","cpu_average":"8","mem":"3.9"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.5","cpu_average":"0","mem":"0.1"},"156":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"295":{"cmdline":"frigate.logger       ","cpu":"0.2","cpu_average":"0","mem":"1.3"},"297":{"cmdline":"frigate.recording_manager","cpu":"0.5","cpu_average":"1","mem":"2.0"},"305":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(70)","cpu":"0.7","cpu_average":"0","mem":"0.1"},"306":{"cmdline":"frigate.detector.coral1","cpu":"14.7","cpu_average":"21","mem":"2.0"},"308":{"cmdline":"frigate.output       ","cpu":"19.3","cpu_average":"15","mem":"2.0"},"326":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"331":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"337":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"338":{"cmdline":"frigate.process:Radar","cpu":"1.4","cpu_average":"0","mem":"1.8"},"343":{"cmdline":"frigate.process:MaternityPen1","cpu":"9.7","cpu_average":"6","mem":"2.0"},"344":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"345":{"cmdline":"frigate.process:MaternityPen2","cpu":"6.0","cpu_average":"6","mem":"2.0"},"347":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"348":{"cmdline":"frigate.process:CalfBarn1","cpu":"6.8","cpu_average":"9","mem":"2.2"},"349":{"cmdline":"frigate.process:CalfBarn2","cpu":"4.1","cpu_average":"1","mem":"1.9"},"353":{"cmdline":"frigate.process:Parlor","cpu":"1.4","cpu_average":"1","mem":"1.9"},"355":{"cmdline":"frigate.process:NorthBarnCam","cpu":"1.4","cpu_average":"4","mem":"2.0"},"357":{"cmdline":"frigate.process:WestBarnCam","cpu":"1.4","cpu_average":"6","mem":"2.2"},"359":{"cmdline":"frigate.process:WorkshopSouth","cpu":"7.0","cpu_average":"9","mem":"2.2"},"360":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"366":{"cmdline":"frigate.capture:Radar","cpu":"1.2","cpu_average":"0","mem":"1.8"},"367":{"cmdline":"frigate.capture:MaternityPen1","cpu":"1.5","cpu_average":"0","mem":"1.8"},"368":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"370":{"cmdline":"frigate.capture:MaternityPen2","cpu":"1.7","cpu_average":"0","mem":"1.8"},"372":{"cmdline":"frigate.capture:CalfBarn1","cpu":"1.5","cpu_average":"0","mem":"1.8"},"375":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"376":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.13/user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/MaternityPen2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"0","mem":"0.5"},"379":{"cmdline":"frigate.capture:CalfBarn2","cpu":"1.5","cpu_average":"0","mem":"1.8"},"381":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"382":{"cmdline":"frigate.capture:Parlor","cpu":"1.7","cpu_average":"0","mem":"1.8"},"385":{"cmdline":"frigate.capture:NorthBarnCam","cpu":"1.2","cpu_average":"0","mem":"1.8"},"386":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -framerate 2 -re -thread_queue_size 512 -f image2 -loop 1 -an -i /radarimage/image.jpeg -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -filter:v fps=2 -f rawvideo -pix_fmt yuv420p -an pipe:","cpu":"4.4","cpu_average":"3","mem":"3.9"},"387":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.12/axis-media/media.amp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/MaternityPen1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.9","cpu_average":"1","mem":"0.6"},"395":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.14:554/user=admin_password=6QNMIQGe_channel=1_stream=0.sdp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Parlor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"0","mem":"0.7"},"397":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.10/axis-media/media.amp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/CalfBarn1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.9","cpu_average":"1","mem":"0.6"},"408":{"cmdline":"frigate.capture:WestBarnCam","cpu":"1.5","cpu_average":"0","mem":"1.8"},"409":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"4.8","cpu_average":"3","mem":"0.6"},"412":{"cmdline":"frigate.capture:WorkshopSouth","cpu":"1.2","cpu_average":"0","mem":"1.8"},"418":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv -i rtmp://192.168.1.15/bcs/channel0_main.bcs?channel=0&stream=1&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/NorthBarnCam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"0","mem":"0.6"},"419":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.11/user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/CalfBarn2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.4","cpu_average":"0","mem":"0.5"},"453":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv -i rtmp://192.168.1.16/bcs/channel0_main.bcs?channel=0&stream=1&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/WestBarnCam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"0","mem":"0.7"},"461":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.17/axis-media/media.amp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/WorkshopSouth@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.1","cpu_average":"1","mem":"0.5"},"859":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":68.4,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":8.28,"pid":306}},"gpu_usages":{"intel-vaapi":{"gpu":"2.26%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":295},"recording":{"pid":297}},"service":{"last_updated":1717900965,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":236.5,"mount_type":"tmpfs","total":256.0,"used":19.5},"/media/frigate/clips":{"free":3563593.9,"mount_type":"ext4","total":3754443.0,"used":60.8},"/media/frigate/recordings":{"free":3563593.9,"mount_type":"ext4","total":3754443.0,"used":60.8},"/tmp/cache":{"free":82715.7,"mount_type":"overlay","total":93296.4,"used":5796.3}},"temperatures":{"apex_0":44.3},"uptime":64,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

docker-compose file.
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/sydney/frigatenvr/:/config/
      - /home/sydney/frigatenvr/storage/:/media/frigate
      - /home/sydney/radarimage:/radarimage
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "mypassword"
      LIBVA_DRIVER_NAME: i965

`http://192.168.1.231:5000/api/go2rtc/streams:
{"birdseye":{"consumers":null,"producers":[{"url":"exec:ffmpeg -hide_banner -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf format=vaapi|nv12,hwupload -rtsp_transport tcp -f rtsp {output}"}]}}`
