### DISCUSSION TITLE
[Config Support]: High CPU usage despite adding a Coral TPU

### DISCUSSION THREAD

**Discussion by DrissiReda** [blakeblackshear/frigate#11830] [Config Support]
### Describe the problem you are having

I have been using frigate with a ryzen 5800X as a container. and it had high cpu usage. I'm only using a single camera for testing purposes for now. 

I installed a Coral TPU as PCI device and it is detected, however my cpu usage didn't change, only had inference speed go up.

<details>

<summary>
here is my config file:
</summary>

```yaml
mqtt:
  host: rabbitmq.surveillance
  port: 1883
  user: rabbit
  password: ENC[AES256_GCM,data:m6W63ud71eIAxa3s44e+ZZCDaBgtKtjM9q0sR2641g==,iv:4H1HtCsyipXI91Xx6UoVB9hThhSgC53m69y+fWJZqFo=,tag:v5sSH2sxXsp+RMT3Asmnbg==,type:str]
# go2rtc:
#   streams:
#     reolinkMain:
#       - ffmpeg:http://{FRIGATE_REO1_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REO1_USER}&password={FRIGATE_REO1_PASS}#video=copy#audio=copy#audio=opus
detectors:
  coral:
    type: edgetpu
    device: pci
go2rtc:
  streams:
    backyard:
      - ffmpeg:rtsp://{FRIGATE_REO1_USER}:{FRIGATE_REO1_PASS}@{FRIGATE_REO1_IP}:554/h264Preview_01_main#video=copy#audio=copy#audio=aac
cameras:
  # Define at least one camera
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_REO1_USER}:{FRIGATE_REO1_PASS}@{FRIGATE_REO1_IP}:554/h265Preview_01_main
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -timeout 5000000 -an
          roles:
            - detect
    detect:
      height: 1920
      width: 2560
      fps: 23
    objects:
      track:
        - person
        - dog
        - cat
        - car
record:
  enabled: true
  events:
    retain:
      default: 14
      mode: motion
snapshots:
  enabled: true
```

</details>

<details>
<summary>
Here is system page screenshot:
</summary>

![image](https://github.com/blakeblackshear/frigate/assets/16291156/45b24b96-5a77-4646-bba4-7291bedf0e21)

</details>

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: rabbitmq.surveillance
  port: 1883
  user: rabbit
  password: ENC[AES256_GCM,data:m6W63ud71eIAxa3s44e+ZZCDaBgtKtjM9q0sR2641g==,iv:4H1HtCsyipXI91Xx6UoVB9hThhSgC53m69y+fWJZqFo=,tag:v5sSH2sxXsp+RMT3Asmnbg==,type:str]
# go2rtc:
#   streams:
#     reolinkMain:
#       - ffmpeg:http://{FRIGATE_REO1_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REO1_USER}&password={FRIGATE_REO1_PASS}#video=copy#audio=copy#audio=opus
detectors:
  coral:
    type: edgetpu
    device: pci
go2rtc:
  streams:
    backyard:
      - ffmpeg:rtsp://{FRIGATE_REO1_USER}:{FRIGATE_REO1_PASS}@{FRIGATE_REO1_IP}:554/h264Preview_01_main#video=copy#audio=copy#audio=aac
cameras:
  # Define at least one camera
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_REO1_USER}:{FRIGATE_REO1_PASS}@{FRIGATE_REO1_IP}:554/h265Preview_01_main
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -timeout 5000000 -an
          roles:
            - detect
    detect:
      height: 1920
      width: 2560
      fps: 23
    objects:
      track:
        - person
        - dog
        - cat
        - car
record:
  enabled: true
  events:
    retain:
      default: 14
      mode: motion
snapshots:
  enabled: true
```

### Relevant log output

```shell
No logs
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

PCIe
