### DISCUSSION TITLE
[Config Support]: Need help with cat and dog detection

### DISCUSSION THREAD

**Discussion by lilp69** [blakeblackshear/frigate#11846] [Config Support] [answered]
### Describe the problem you are having

Hi,
New to frigate.
I've installed it on HA.
Here is my conf:
Frigate Current version: 0.13.2
Home Assistant Core 2024.6.1
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240605.0

I've a lot of false positive with person, I upload them to Frigate+ to edit them.
But camera, never detect dog or car.

Thanks;

### Version

0.13.2

### Frigate config file

```yaml
## Connection à MQTT ##
mqtt:
  host: XxX
  port: XxX
  client_id: frigate
  topic_prefix: frigate
  user: XX
  password: XxX


## Choix des caméras ##
go2rtc:
  streams:
    r4252_smart_outdoor_camera:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh
      camera.r4252_smart_outdoor_camera

## Liste des caméras avec leurs adresses de connection ##
cameras:
  r4252_smart_outdoor_camera:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/r4252_smart_outdoor_camera?video
        input_args: preset-rtsp-restream-low-latency
        roles:
        - detect

#    motion: ## Création des zones à ignorer ##
#      mask:
#        - 0,461,3,0,1919,0,1919,843,1699,492,1344,458,1346,336,973,317,869,375,866,432
    motion:
      mask:
      - 262,0,259,36,32,38,31,0

## Choix des options de détection et d'enregistrement ##
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
# Seconds d'enregistrement avant et après l'èvenement
    pre_capture: 60
    post_capture: 60
    retain:
#Durée de rétention en J
      default: 15
#      mode: motion ## Conserve les vidéos avec mouvements seulement ## ## active_objects ## Conserve les vidéos avec objets seulement ##
      mode: all ## Conserve les vidéos avec détection d'objets ##
      objects:
        dog: 2 ## Durée de conservation par objets ##
        cat: 2
        person: 7

#Objets à suivre
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person
  - dog
  - cat
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
#      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
#      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
    dog:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
#      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
#      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.4
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.5
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
#      mask: 0,0,1000,0,1000,200,0,200
    cat:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
#      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
#      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.4
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.5

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30


snapshots:
  enabled: true
```

### Relevant log output

```shell
Cat and dog not detect.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
