### DISCUSSION TITLE
[Support]: Phantom detection "events"

### DISCUSSION THREAD

**Discussion by adamburgoyne** [blakeblackshear/frigate#11847] [General Support] [answered]
### Describe the problem you are having

I've been facing this issue for a little while now, on both the latest stable version and the latest beta version of Frigate. I'm using the HomeAssistant notification blueprint (by sgtbatten) and will very occasionally get a person detected notification when there's no actual person but the main concern is there's no attached screenshot or Frigate event present either. 

The "Garden side person detection" entity from the Frigate integration shows a "detected" state at this point so I believe the notification automation is working as expected but I can't seem to find out why that state is being triggered as there's no corresponding event in Frigate. 

This is the same every time I get a notification without a screenshot, there's never a corresponding event in Frigate so I'm a bit lost on where to look at what triggered it and the notifications don't seem to have any regularity which doesn't help troubleshooting. 

Any idea what might cause Frigate to send these phantom person detected states? 

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
database:
  path: /config/frigate.db

model:
  path: xxxxxxxx

birdseye:
  enabled: true
  mode: continuous
  restream: true

go2rtc:
  streams:
    doorbell:
      - ffmpeg:http://192.168.5.195/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx#video=copy#audio=copy#audio=opus
    doorbell_sub:
      - ffmpeg:http://192.168.5.195/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx
    duo_two:
      - rtsp://admin:xxxxx@192.168.5.234:554/h264Preview_01_main
    duo_two_sub:
      - rtsp://admin:xxxxx@192.168.5.234:554/h264Preview_01_sub

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 10
      events:
        retain:
          default: 14
    snapshots:
      enabled: true
      required_zones:
        - driveway
    zones:
      driveway:
        coordinates: 485,489,788,479,881,482,1155,544,1280,438,1280,720,0,720,0,462
        objects:
          - person
          - face
          - dog
    motion:
      mask:
        - 1280,0,1280,45,1095,46,1173,178,1206,308,1147,290,1089,249,1062,252,891,235,877,262,693,262,574,310,504,309,447,222,198,464,0,440,0,0
    review:
      alerts:
        required_zones:
          - driveway
  duo_two:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/duo_two
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/duo_two_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1536
      height: 576
      fps: 5
    objects:
      track:
        - dog
        - person
        - face
        - sports_ball
      filters:
        person:
          min_area: 6000
          max_area: 60000
          min_score: .80
          threshold: .85
        dog:
          max_area: 40000
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 7
    snapshots:
      enabled: true
      required_zones:
        - garden_side
    motion:
      mask:
        - 0,0.562,0,0,0.372,0,0.351,0.041,0.275,0.098,0.208,0.163,0.058,0.58
        - 0.928,0.406,0.831,0.205,0.648,0,0.893,0,1,0,1,0.554
        - 0.945,0.927,0.949,1,0.824,1,0.823,0.929
    zones:
      garden_side:
        coordinates: 
          0,1,0.632,1,1,1,1,0.585,0.943,0.45,0.855,0.276,0.765,0.132,0.609,0,0.484,0,0.388,0.046,0.277,0.12,0.212,0.185,0.067,0.594,0,0.717
        inertia: 3
    review:
      alerts:
        required_zones: garden_side
objects:
  track:
    - person
    - face
    - dog
  filters:
    person:
      min_score: .65
      threshold: .85
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7

# Enable sound and HW accelleration
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Duo 2
