### DISCUSSION TITLE
[Bug]: Live view gets stuck as JSMPEG when returning from other tabs

### DISCUSSION THREAD

**Discussion by bakedhorse** [blakeblackshear/frigate#11843] [Report a Bug] [answered]
### Describe the problem you are having

Ever since pre-beta 1, the automatic switching from MSE, or WebRTC, to JSMPEG does not switch back when switching to another tab for a minute and then switching back to frigate.
I have tried two browsers, Brave and Firefox. I have also tried this on my phone and it has done the same thing.
Refreshing or going back does fix it until you put it in the background again.

Apologies if this is a dupe, but I cannot find anything talking about an issue like this.

### Steps to reproduce

1. Go to live view of a camera, wait for it to load.
2. Switch to another tab and leave it for a minute.
3. Switch back to frigate's tab.
4. Presto, live view stuck as jsmpeg.

### Version

0.14.0-30b8627

### Frigate config file

```yaml
# MQTT connection
mqtt:
  enabled: false

# Default Detection
detect: # video detection
  enabled: false
  fps: 5
  width: 640
  height: 480
  max_disappeared: 25
  annotation_offset: -50
  stationary:
    interval: 10
    threshold: 50
    max_frames:
      default: 10000
      objects:
        person: 50000
audio: # audio detection
  enabled: false
  listen:
    - bark
    - scream
    - speech
    - yell
  min_volume: 1000
  max_not_heard: 30
  filters:
    speech:
      threshold: 0.8

# Default Record/DVR
record:
  enabled: false
  expire_interval: 30
  sync_recordings: true

# Default Snapshots
snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  timestamp: false
  retain:
    default: 10
    objects:
      person: 15

# Birdseye
birdseye:
  enabled: false

# FFMPEG default Video Processing
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  global_args: -hide_banner -loglevel warning
  input_args: preset-rtsp-generic

# AI Detection & Models
detectors:
  cpu1:
    type: cpu
    num_threads: 3

go2rtc:
  webrtc:
    candidates:
      - xxxx:8555
      - stun:8555
  rtsp:
    default_query: mp4
  streams:
    # Front Door #
    front_door:
      - rtsp://admin:{xxxx}@xxxx:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:front_door#audio=opus
    front_door_sub:
      - rtsp://admin:{xxxx}@xxxx:554/cam/realmonitor?channel=1&subtype=1

# Cameras
cameras:
  # Front Door
  front_door:
    ffmpeg:
      inputs:
        # Recording stream, highest quality and framerate
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    # ONVIF
    onvif:
      host: xxxx
      port: xxxx
      user: xxxx
      password: '{xxxx}'
    # Detection
    detect:
      enabled: false
    # Objects
    objects:
      track:
        - cat
    # Motion Tracking (this is used for general recording)    
    motion:
      threshold: 40
      contour_area: 40 
      mask: 0,0
    # Recording/DVR
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        post_capture: 5
        pre_capture: 5
        retain:
          default: 10
          mode: motion
version: 0.14
```

### Relevant log output

```shell
None.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Amcrest IP2M-841B-V3 (this does happen with all my cameras with different models)

### Any other information that may be helpful

May I make suggestion as well? Could you guys add a way to switch between MSE, WebRTC and Jsmpeg like from 0.13? There's no indication nor easy way to test if things are working. A small little button that lists the 3 and maybe even an "Auto" would work.
Even if not that, just some kind of indication of what type of stream it is using?
*Or maybe I'm just blind and missed it.*
Thank you.
