### DISCUSSION TITLE
[Camera Support]: Imou Cruiser Dual (IPC-S7X-6MOWED)

### DISCUSSION THREAD

**Discussion by buzh** [blakeblackshear/frigate#11848] [Camera Support]
### Describe the problem you are having

Thought I'd share my config for this model, which is apparently quite new. Just to be clear, my setup now works - just sharing to help others along and get any suggestions for improvement.

There's still very little information online about this model, even from the manufacturer website. It's currently not listed on the main website, but it can be found (along with some downloads) on regional sites. It's a dual camera system with one fixed camera and one motorized pan/tilt dome.

Since this is based on the same platform as Dahua I was hoping it would be perfect for Frigate, and while it does work the substreams are limited to a max of 640x480. There is very little in the way of tools and documentation available for this specific model, and the recommended "Imou Life" app doesn't let you configure much of the encoding options, just the built-in detection/alerting features (which I won't be using).

After some digging I found that:
- You can use the same "SmartPSS" software that's used on other Dahua/Amcrest branded cams to manage the configuration.
- The "ConfigTool" referenced at dahuawiki works, but is missing some options
- There's an "Imou ConfigTool" which seems like an updated version of the above with some extra options, but not everything included in the previous two tools.

Using a combination (!) of those three tools AND the Imou Life app, I was able to:
- Turn off the built-in detection, tracking, alerting
- Change from h265 to h264 for the PT main stream
- Turn off the "Imou" watermark in the bottom right corner
- Remove the date/time display from the feed
- Manually set the Iframe rate
- Tune the color/white balance/etc settings

Since the sub streams are limited to a low resolution, I configured them this way:

Fixed camera: 720P 5fps main stream
PT camera: 2304x1296 15fps main stream, Onvif support

Then for the PT I'm using ffmpeg in the Frigate config to downscale to 720p and use that for the detect feed.

Would appreciate any feedback or suggestions, both on the Frigate configuration and on the camera..

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: true
objects:
  track:
    - person
    - cat
    - dog
    - deer
    - car
    - bicycle
    - bird

detect:
  enabled: true

record:
  enabled: true

go2rtc:
  streams:
    cruiser_pt:
    - rtsp://admin:redacted@10.0.40.222/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    cruiser_pt_sub:
    - "ffmpeg:cruiser_pt#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi"

cameras:
  imou_cruiser_ptz:
    onvif:
      host: 10.0.40.222
      port: 80
      user: admin
      password: redacted
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cruiser_pt
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cruiser_pt_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  imou_cruiser_fixed:
    ffmpeg:
      inputs:
      - path: rtsp://admin:redacted@10.0.40.222/cam/realmonitor?channel=2&subtype=0
        roles:
        - detect
        - record
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280}]}}]

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Imou Cruiser Dual (IPC-S7X-6MOWED) 2.800.0000000.19.R Build 2024-03-04

### Any other information that may be helpful

Running on a ~10 year old NUC with a mPCIe Coral TPU.
