### DISCUSSION TITLE
Frigate will not load

### DISCUSSION THREAD

**Discussion by mikey6283** [blakeblackshear/frigate#11859] [Config Support]
### Describe the problem you are having

 I removed 2 of  Reolink cameras from the config now i am unable  to start frigate to see the logs to understand  the problem . The logs is from portainer.
 Is there a basic  config that i setup to at least get int Frigate. The camera image is showing up on Overview in HA .

### Version

 0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.120:5000/api/config/schema



logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.comms.mqtt: debug
    frigate.record.maintainer: debug

mqtt:
  enabled: true
  host: 192.168.0.120
  port: 1883
  topic_prefix: frigate  
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db
record:  expire_interval: 20
go2rtc:
  log:
    exec: trace
  streams:
    backgarden:
      - "ffmpeg:http://192.168.0.219/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=BackGarden1#video=copy#audi>
    backgarden_sub:
      - "ffmpeg:http://192.168.0.219/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=BackGarden1"
cameras
  backgarden:
    ffmpeg:
     inputs:
        - path: rtsp://127.0.0.1:8554/backgarden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backgarden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
         - 188,31,446,32,441,0,191,0
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
```

### Relevant log output

```shell
File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 28, column 25:
    record:  expire_interval: 20
                            ^
2024-06-10 19:35:28.240366989  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-06-10 19:36:37.458493475  [INFO] Preparing new go2rtc config...
2024-06-10 19:36:37.459138282  [INFO] Preparing Frigate...
2024-06-10 19:36:37.460947310  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
Error: bad file '/config/config.yml': yaml: line 24: mapping values are not allowed in this context
2024-06-10 19:36:37.498100752  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-06-10 19:36:37.524689872  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-06-10 19:36:37.578973222  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2024-06-10 19:36:37.614106922  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

PCIe
