### DISCUSSION TITLE
[Config Support]: Audio on tablet Lenovo XiaoXin Pad 2022

### DISCUSSION THREAD

**Discussion by Trax0u62** [blakeblackshear/frigate#11868] [Config Support]
### Describe the problem you are having

Hello,

I have started using Frigate and would like to manage my Reolink Doorbell POE with Home Assistant and Frigate on my wall-mounted tablet. Home Assistant and Frigate are both running on Proxmox.

However, I have a sound issue on my tablet when using the main stream of the doorbell. Here is my Frigate configuration:

```yaml
mqtt:
  enabled: false

##########################################################################

go2rtc:
  streams:
    reolink:
      - rtsp://user:password@192.168.1.19:554/h264Preview_01_main
      - "ffmpeg:rtsp://user:password@192.168.1.19:554/h264Preview_01_main#audio=pcm#audio=volume"
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

##########################################################################

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink 
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
```

On my computer, the sound and microphone (2-way audio) work fine. But on my tablet, there is no sound, and the sound and microphone icons on the Frigate card are not showed.

If I change the configuration to:

```yaml
go2rtc:
  streams:
    reolink:
      - rtsp://user:password@192.168.1.19:554/h264Preview_01_sub
      - "ffmpeg:rtsp://user:password@192.168.1.19:554/h264Preview_01_sub#audio=pcm#audio=volume"
```

It works on both the computer and the tablet, with sound and microphone (2-way audio).

I am using Fully Kiosk on my tablet, but I have the same issue with Google Chrome. It looks like there is a codec issue on the tablet. 

Is there a way to use the main stream and change the audio codec?

Thank you for your help.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false

##########################################################################

go2rtc:
  streams:
    reolink:
      - rtsp://user:password@192.168.1.19:554/h264Preview_01_main
      - "ffmpeg:rtsp://user:password@192.168.1.19:554/h264Preview_01_main#audio=pcm#audio=volume"
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

##########################################################################

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink 
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
```

### Relevant log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)
