### DISCUSSION TITLE
Toggling Detection via MQTT not working - but works via UI

### DISCUSSION THREAD

**Discussion by ianflipp** [blakeblackshear/frigate#11878] [General Support] [answered]
### Describe the problem you are having

Hi,
my first post since switching to frigate.  I have everything working as I want so decided to try and automate altering the config via MQTT, I don't use HA just a Frigate container and MQTT via MQTTExplorer or command line (linux).

I can publish to the various cameras and read the various events sent out acknowledging the change.  What I want to do is turn off detections based on various conditions, eg  If I'm home don't detect my dogs in the back garden.

If I use the buttons in the UI all works OK and the button is greyed out and the state change is reflected in MQTT Explorer.

If I use MQTT to change the detect state to OFF then the button isn't greyed out in the UI but the state is toggled when viewed via MQTT.  However detections continue to occur.

Any pointers greatly appreciated.

### Version

14 beta 2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: host ip
  user: me
  password: password
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  mode: objects
model:
  labelmap:
    7: truck


cameras:

  DriveCamera:
    enabled: true
    ffmpeg:

      inputs:
        - path: rtsp://admin:redacted@cam ip:554/stream1
          roles:
            - detect
        - path: rtsp://admin:redacted@cam ip:554/stream0
          roles:
            - record

#detection res same as low res stream
    detect:
      enabled: true
      width: 720
      height: 480
#What we are looking for
    objects:
      track:
        - person
        - dog
        - cat

#Overide the default confidence value per object anything below this confidence is ignored
      filters:
        person:
          threshold: 0.60
        dog:
          threshold: 0.50

    zones:
      dr_zone_1:
        coordinates: 0.073,0.993,0.562,1,0.591,0.496,0.384,0.482
        objects:
          - person
          - dog
          - cat
        inertia: 3
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects

#Only record wanted objects in the defined area and keep for 7 days
      events:
        pre_capture: 1
        post_capture: 5
        retain:
          default: 3
          mode: active_objects
    motion:
      mask:
        - 0.565,1,1,1,1,0.45,0.608,0.39
        - 0.137,0.251,0.648,0.253,0.589,0.49,0.384,0.476,0.065,1,0,1,0,0.244

    review:
      detections:
        labels: []

      alerts:
        labels:
          - dog
          - person
          - cat
        required_zones: dr_zone_1

repeat for other cameras ...
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink 5MP
