### DISCUSSION TITLE
[Bug]: 14 beta 2 startup failure due to trying to backup database

### DISCUSSION THREAD

**Discussion by evilbulgarian** [blakeblackshear/frigate#11889] [Report a Bug] [answered]
### Describe the problem you are having

I update to beta2 version 14 of frigate and I get below error, I even wipe the database and volume where frigate stores its data with same result:
`2024-06-05 19:41:27.398504619  '/database/church.db' and '/database/church.db' are the same file
2024-06-05 19:41:27.398827086  [2024-06-05 19:41:27] frigate.app                    INFO    : Making backup of DB before migrations...
2024-06-05 19:41:28.672173311  [INFO] Service Frigate exited with code 1 (by signal 0)`

### Steps to reproduce

update image to beta 2, start frigate container, fails to start

### Version

14-beta2

### Frigate config file

```yaml
database:
  path: /database/church.db

mqtt:
  host: nixbg
  user: homeassistant2
  password: '{FRIGATE_MQTT_PASS}'

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: false

go2rtc:
  streams:
    church1:
      - rtsp://admin:{FRIGATE_RTSP_PASS}@192.168.120.3:554/cam/realmonitor?channel=1&subtype=0
    church2:
      - rtsp://admin:{FRIGATE_RTSP_PASS}@192.168.120.4:554/cam/realmonitor?channel=1&subtype=0
    # church3:
    #   - rtsp://admin:{FRIGATE_RTSP_PASS}@192.168.120.5:554/cam/realmonitor?channel=1&subtype=0
    church3:
      - rtsp://admin:{FRIGATE_RTSP_PASS}@192.168.120.6:554/

record:
  enabled: false
detect:
  enabled: false

cameras:
  church1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/church1
  church2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/church2
  church3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/church3
version: 0.14
```

### Relevant log output

```shell
`2024-06-05 19:41:27.398504619  '/database/church.db' and '/database/church.db' are the same file
2024-06-05 19:41:27.398827086  [2024-06-05 19:41:27] frigate.app                    INFO    : Making backup of DB before migrations...
2024-06-05 19:41:28.672173311  [INFO] Service Frigate exited with code 1 (by signal 0)`
```

### Operating system

Other

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

dahua
