### DISCUSSION TITLE
[Support]: No video in live video whereas it works from Settings > Debug

### DISCUSSION THREAD

**Discussion by dmartinpro** [blakeblackshear/frigate#11884] [General Support] [answered]
### Describe the problem you are having

Previously, with 0.13.2 and before, I was able to display the live video of my Reolink camera. live_mode was defined in my configuration as jsmpeg.
After migrating to 0.14.0-beta2, I've removed it from my conf file (as it's no longer supported).
But, I just can't see the live stream of my camera, just a greyish rectangle.

My frigate instance is running in a Docker container, on a AMD64 server. All ports are exposed. I'm still using port 5000 as the main HTTP port as my auth is managed differently (Vouch based SSO).

I can see the live stream properly displayed from Settings > Debug, which is quite surprising, but also promising :)

### Version

0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.10
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *****
  password: *****

database:
  path: /media/frigate/db/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

objects:
  track:
    - person
    - car
  filters:
    person:
      min_score: 0.65
    car:
      min_score: 0.5

motion:
#  improve_contrast: True
  lightning_threshold: 0.7

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous

detect:
  fps: 5
  max_disappeared: 25
  width: 1280
  height: 720
  stationary:
    interval: 10
    threshold: 50

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

#ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
#  live_mode: jsmpeg # not compatible anymore with v0.14+

logger:
  default: info
  logs:
    frigate.events: debug

go2rtc:
  log:
    level: error
    streams: error
    rtsp: error
  streams:
    entrance_clean:
      - rtsp://***user***:***pwd***@192.168.0.xx/h264Preview_01_main#video=h264#width=1280#height=720#audio=copy#audio=opus

record:
  events:
    retain:
      mode: all

cameras:
  entrance:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_clean?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: entrance_sub
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - entrance_2
    motion:
      mask:
        - 0,0,0,720,116,720,595,230,729,230,736,720,1280,720,1280,0
    objects:
      mask:
        - 0,0,0,720,116,720,595,230,729,230,736,720,1280,720,1280,0
    zones:
      entrance_1:
        inertia: 5
        coordinates: 720,264,577,265,460,392,725,390
        objects:
          - person
          - car
      entrance_2:
        inertia: 5
        coordinates: 733,391,733,720,114,720,460,394
        objects:
          - person
    review:
      alerts:
        required_zones:
          - entrance_1

version: 0.14
```

### Relevant log output

```shell
Unable to see anything relevant
```

### FFprobe output from your camera

```shell
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 2560,
            "height": 1440,
            "coded_width": 2560,
            "coded_height": 1440,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 0,
            "pix_fmt": "yuv420p",
            "level": 51,
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "false",
            "nal_length_size": "0",
            "r_frame_rate": "30000/1001",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 9000,
            "start_time": "0.100000",
            "bits_per_raw_sample": "8",
            "extradata_size": 22,
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "16000",
            "channels": 1,
            "channel_layout": "mono",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/16000",
            "start_pts": 0,
            "start_time": "0.000000",
            "extradata_size": 2,
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            }
        }
    ],
    "chapters": [

    ],
    "format": {
        "filename": "rtsp://****:*****@192.168.0.**/h264Preview_01_main",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "rtsp",
        "format_long_name": "RTSP input",
        "start_time": "0.000000",
        "probe_score": 100,
        "tags": {
            "title": "Session streamed by \"preview\"",
            "comment": "h264Preview_01_main"
        }
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Mixed

### Camera make and model

REOLINK RLC-410W
