### DISCUSSION TITLE
[Bug]: Two events created at different timestamps (40 mins separate) for one event?

### DISCUSSION THREAD

**Discussion by ptruman** [blakeblackshear/frigate#11904] [Report a Bug] [answered]
### Describe the problem you are having

Per title, I have had some instances of an apparent event (with CCTV embedded timestamps) being given two very different times.

An example view frigate event view (see top/bottom thumbnails):

![image](https://github.com/blakeblackshear/frigate/assets/1991779/49966914-8e4b-4621-8e0a-34384b1ef05c)

Bottom thumbnail takes me to this:

![image](https://github.com/blakeblackshear/frigate/assets/1991779/0893fb33-98af-452a-8431-93eab1bac2a2)

Top thumbnail takes me to this:

![image](https://github.com/blakeblackshear/frigate/assets/1991779/b8d30106-d9bd-4afc-a04c-c71a702f4f88)

I have checked the know the truck in the picture was not there until circa 09:18, but it's been given an 08:37 timestamp and you can see the CCTV embedded image has 09:18 in.

Logs do show a "missing UTC" error but I'd have thought that would make a +/-1 hr different (BST/GMT) - the above is more like 40 mins?

The actual event was 09:18, and I could envisage Frigate "maintaining" an event so that it showed up "later", but this appears to have gone backward? :)

### Steps to reproduce

Unsure - I've only seen this once before and didn't pay attention - caught it this morning.
This looks like it could be similar to : https://github.com/blakeblackshear/frigate/issues/2838 ?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 10.74.90.131

detectors:
  coral1:
    type: edgetpu
#    device: usb:0

cameras:
  Driveway:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://REDACTED:REDACTED@127.0.0.1:8554/driveway_cam?video&audio
          hwaccel_args: preset-nvidia-h264
          roles:
            - record
            - detect
#        - path: rtsp://REDACTED:REDACTED@127.0.0.1:8554/driveway_cam_sub?video&audio
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
    onvif:
      host: REDACTED
      port: 80
      user: REDACTED
      #user: REDACTED
      #password: REDACTED
      password: REDACTED
    detect:
      width: 2592
      height: 1944 
#      width: 704
#      height: 576 
      fps: 15
    motion:
      mask:
        - 2070,645,2592,1368,2592,535,2592,0,1465,0,1653,187
        - 0,0,1194,0,1145,109,1002,225,541,784,114,1591,0,1523
#      mask:
#        - 704,405,704,153,704,0,404,0,568,192
#        - 0,0,310,0,163,216,30,472,0,454
    zones:
      Drive:
#        coordinates: 276,105,195,244,79,492,284,576,649,576,683,531,543,245,443,108
        coordinates: 1029,363,740,709,333,1682,1020,1944,2376,1944,2516,1775,2010,891,1636,355
        objects:
            - person
        filters:
          person:
            min_score: 0.8
      Approach:
        coordinates: 1182,0,1416,0,1627,339,1045,345
#        coordinates: 328,9,384,8,435,98,288,95
        objects:
            - car

go2rtc:
  rtsp:
    username: "REDACTED"
    password: "REDACTED"
  streams:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    driveway_cam:
      - rtsp://viewer:REDACTED@REDACTED:554/stream0
        "ffmpeg:rtsp_cam#audio=aac"
    driveway_cam_sub:
      - rtsp://viewer:REDACTED@REDACTED:554/stream1
        "ffmpeg:rtsp_cam#audio=aac"

live:
#     width: 2592
      height: 1944
      quality: 8
      stream_name: driveway_cam

#timestamp_style:
#      position: "tl"
#      format: "%d/%m/%Y %H:%M:%S"
#      thickness: 1
#      effect: solid

ffmpeg:
#  input_args:
#    - h264_cuvid
  hwaccel_args: preset-nvidia-h264
     #- -c:v
#     - h264_v4l2m2m
#     - preset-nvidia-h264

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
        - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones:
      - Drive
      - Approach
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 7
        car : 7

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 1944
    # 576
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones:
    - Drive
    - Approach
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 7
```

### Relevant log output

```shell
2024-06-12 03:00:02.083136232  [2024-06-12 03:00:02] frigate.util.builtin           WARNING : Using utc for maintenance due to missing or incorrect timezone set
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Jennov 5MP PTZ

### Any other information that may be helpful

Noticed this via HASS UI but frigate native UI shows it also (hence screenshots)
