### DISCUSSION TITLE
Sync existing recordings after restart

### DISCUSSION THREAD

**Discussion by schoen2** [blakeblackshear/frigate#11903] [Config Support] [answered]
### Describe the problem you are having

Hi all,

i have Frigate.video running as a Helm-Chart Deployment in a Kubernetes-Cluster. After updating to the latest version, the Pod restarts as expected and comes up running again. But after that, I noticed, that I don't see any existing recording in the Web-UI. 

On my machines Disk, the Recordings from the last days alive. So I can see the mp4-Files on the Disk, but not in Frigate Web-UI. The Helm-Chart uses a values.yaml with configured persistence. The Pod has bound the PVC/PV correctly (no new PVC after the Update).

Is this expected, that the records list will be left empty after an update?

thanks for clarification :)

Kind regards
Hannes

### Version

7.5.1

### Frigate config file

```yaml
config: |
  mqtt:
    host: "mqtt.example.com"
    port: 1883
    user: admin
    password: "<your_mqtt_password>"
  cameras:
    # Define at least one camera
    Cam1:
      enabled: True
      ffmpeg:
        inputs:
          - path: rtsp://ip
            roles:
              - detect
              - record
      detect:
        width: 1920
        height: 1080
      record:
        enabled: True
    Cam2:
      enabled: True
      ffmpeg:
        inputs:
          - path: rtsp://ip
            roles:
              - detect
              - record
      detect:
        width: 1920
        height: 1080
      record:
        enabled: True
  record:
    enabled: True
    sync_recordings: True
    retain:
      days: 14
      mode: all
```

### Relevant log output

```shell
--
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Values.yaml

```
config: |
  mqtt:
    host: "mqtt.example.com"
    port: 1883
    user: admin
    password: "<your_mqtt_password>"
  cameras:
    # Define at least one camera
    Haustuer:
      enabled: True
      ffmpeg:
        inputs:
          - path: rtsp://ip
            roles:
              - detect
              - record
      detect:
        width: 1920
        height: 1080
      record:
        enabled: True
    Hof:
      enabled: True
      ffmpeg:
        inputs:
          - path: rtsp://ip
            roles:
              - detect
              - record
      detect:
        width: 1920
        height: 1080
      record:
        enabled: True
  record:
    enabled: True
    sync_recordings: True
    retain:
      days: 14
      mode: all

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: IP
  type: LoadBalancer
  port: 80

persistence:
  data:
    enabled: true
    storageClass: ssd-hostpath
    accessMode: ReadWriteOnce
    size: 500Gi
    skipuninstall: true
extraVolumeMounts:
  - name: data
    mountPath: /media
    subPath: frigate
```
