### DISCUSSION TITLE
[Config Support]: No config/ folder

### DISCUSSION THREAD

**Discussion by RobertW62** [blakeblackshear/frigate#11916] [Config Support]
### Describe the problem you are having

Installed Home Assistant OS on x86 pc. When I open file editor to create the frigate.yml config file the editor shows homeassistant/ as the root folder. cannot find config/ folder. I did create a frigate config file. When I try to start frigate it wont start. Checked the log file and it says it cant find the config file. Any Ideas?

### Version

Current version: 0.13.2

### Frigate config file

```yaml
mttq:
  host: a0d7b954-emqx
  user: frigate
  password: 

  
detectors:
  coral:
  type: edgetpu
  device: usb

cameras:
  frontyard:
   ffmpeg:
    inputs:
     path: rtsp://admin:Camera01@192.168.2.101:554/cam/realmonitor?channel=1&subtype=0
     roles:
      - detect
      - rtmp
      path: rtsp://admin:Camera01@192.168.2.101:554/cam/realmonitor?channel=0&subtype=0
      roles:
       - record
    rtmp:
     enabled: True
    record:
     enable: True
    snapshots:
     enabled: True
    detect:
     enable: True
     width: 1280
     height: 720
     fps: 5
     objects:
       track:
         - person
         - car
         - bicycle
         - cat
         - dog
```

### Relevant log output

```shell
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-06-12 19:03:16.206864063  [INFO] Preparing Frigate...
2024-06-12 19:03:16.207586512  [INFO] Starting NGINX...
Error: bad file '/config/frigate.yml': yaml: line 16: did not find expected '-' indicator
s6-rc: info: service legacy-services successfully started
2024-06-12 19:03:16.212263435  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-06-12 19:03:16.217099475  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-06-12 19:03:16.217606365  [INFO] Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-06-12 19:03:16.220819461  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-06-12 19:12:47.944287684  [INFO] Preparing Frigate...
2024-06-12 19:12:47.946056657  [INFO] Starting NGINX...
Error: bad file '/config/frigate.yml': yaml: line 16: did not find expected '-' indicator
s6-rc: info: service legacy-services successfully started
2024-06-12 19:12:47.957152916  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-06-12 19:12:47.964990190  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-06-12 19:12:47.965873131  [INFO] Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-06-12 19:12:47.970323520  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
