### DISCUSSION TITLE
Best Practice for Doorbird d20x Camera

### DISCUSSION THREAD

**Discussion by fabian-born** [blakeblackshear/frigate#1191] [Ask A Question] [answered]
Hi All, 
I have a doorbird D20x and I want to connect them to frigate. The connectivity works fine but don't get  a right picture. 
[picture 1](https://1drv.ms/u/s!Ai_TuK-7U58wxyuzBRhBSFVL-5Nb?e=j4aFk1)
[picture 2](https://1drv.ms/u/s!Ai_TuK-7U58wxyzydUCpKDsIp_a4?e=zEaGzs)

I use following configuration:

```yaml
cameras:
  #   # Name of your camera
    front_door:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.100.43:554/mpeg/media.amp
            roles:
              - detect
              - rtmp
      width: 640
      height: 480
      fps: 3
      objects:
        track:
          - person
   ```

Has anyone a working configuration?
Thanks in advance
Fabian
