### DISCUSSION TITLE
[HW Accel Support]: Make sure transcoding is correctly configured

### DISCUSSION THREAD

**Discussion by BurningTheSky** [blakeblackshear/frigate#11910] [Hardware Acceleration Support]
### Describe the problem you are having

I am running Frigate as a container under Unraid with a GPU and coral passed through. I have had an issue where when backups of my container configs are run, my server memory fills and services are hard stopped. Posting in the Unraid forums they say that it looks like the caching of the stream transcodes was filling my RAM. I'm not sure if this is expect behaviour or if it can be moved to the GPU somehow to free up the system RAM?

Should the tmpfs size (--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000) be reduced? I'm not sure why I set it to that. My server has 32GB of RAM

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.x.x.45
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci
#  cuda:
#    type: tensorrt

go2rtc:
  log:
    exec: trace
  streams:
    Front:
     # - "ffmpeg:rtsp://user:pass@192.x.x.54:554//Streaming/Channels/101/#video=copy#audio=aac#audio=opus"
     # - "ffmpeg:rtsp://user:pass@192.x.x.54:554//Streaming/Channels/101/#video=copy#audio=aac"
      - "rtsp://user:pass@192.x.x.54:554//Streaming/Channels/101/"
      - "ffmpeg:Front#audio=aac"
    Front247:
      - "rtsp://user:pass@192.x.x.54:554//Streaming/Channels/102/"
    Driveway:
      - "ffmpeg:http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#video=copy#audio=copy#audio=opus#hardware"
    Driveway247:
      - "ffmpeg:http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass#hardware"
    Garage:
      - "ffmpeg:http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#video=copy#audio=copy#audio=opus#hardware"
    Garage247:
      - "ffmpeg:http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass#hardware"
    Garden:
      - "ffmpeg:http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#video=copy#audio=copy#audio=opus#hardware"
    Garden247:
      - "ffmpeg:http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass#hardware"
    Downstairs:
      - "rtsp://192.x.x.57/live0"
      - "ffmpeg:Downstairs#video=copy#audio=aac#audio=opus#hardware"

cameras:
  # <------- Event record ------->

  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy # was preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects
    motion:
      mask:    
        - 595,0,640,0,640,87,619,72,588,46,549,23,497,0
    

  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garden247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - cat
        - dog
        - person
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Downstairs: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Downstairs?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  # <------- 24/7 record ------->

  Front_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all

  Driveway_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all

  Garage_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all

#model:
#  path: /trt-models/yolov7-tiny-416.trt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 416
#  height: 416
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='br0'
  --ip='192.x.x.48'
  --privileged=true
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid"
  -e HOST_CONTAINERNAME="frigate"
  -e 'TCP_PORT_5000'='5000'
  -e 'TCP_PORT_8554'='8554'
  -e 'FRIGATE_RTSP_PASSWORD'='pass'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-6b240216-4ebc-194d-099d-5d86624395a0'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'TCP_PORT_8555'='8555'
  -e 'UDP_PORT_8555'='8555'
  -e 'TCP_PORT_1984'='1984'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -v '/mnt/cache/appdata/frigate':'/config':'rw'
  -v '/mnt/user/Media/frigate':'/media/frigate':'rw'
  -v '/mnt/cache/frigate/':'/db':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/apex_0'
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped
  --runtime=nvidia 'ghcr.io/blakeblackshear/frigate:stable'
```

### Relevant log output

```shell
root      8162  0.0  0.0    212    16 ?        S    Jun01   0:00      \_ s6-supervise frigate
root      8234  5.2  4.9 5792448 1634420 ?     Ssl  Jun01 575:26      |   \_ python3 -u -m frigate
root     11025 14.3  0.9 2374752 313456 ?      Sl   Jun01 1564:18      |       \_ frigate.process:Garden
root     11022 14.1  0.8 2340448 279156 ?      Sl   Jun01 1543:22      |       \_ frigate.process:Driveway
root     11039 11.8  0.7 2302740 241340 ?      Sl   Jun01 1291:50      |       \_ frigate.process:Driveway_247
root     11041 10.4  0.7 2300852 240964 ?      Sl   Jun01 1135:54      |       \_ frigate.process:Garage_247
root     11020  9.9  0.8 2346084 284816 ?      Sl   Jun01 1081:18      |       \_ frigate.process:Front
root     11030  9.5  0.7 2317900 255596 ?      Sl   Jun01 1042:14      |       \_ frigate.process:Garage
root     10973  9.0  0.3 1598768 120000 ?      Sl   Jun01 991:03      |       \_ frigate.detector.coral
root     11032  5.6  0.7 2319756 258096 ?      Sl   Jun01 620:15      |       \_ frigate.process:Downstairs
root     11034  5.6  0.7 2300200 238128 ?      Sl   Jun01 620:16      |       \_ frigate.process:Front_247
root     10963  4.9  0.8 1923012 279340 ?      Sl   Jun01 543:30      |       \_ frigate.recording_manager
root     10975  2.1  0.3 2507320 111812 ?      Sl   Jun01 238:49      |       \_ frigate.output
root     10991  0.0  0.0 126820  9052 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10992  0.0  0.0 126820  7012 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10993  0.0  0.0 126820  7012 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10994  0.0  0.0 126820  4992 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10995  0.0  0.0 126820  7056 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10996  0.0  0.0 126820  7008 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10997  0.0  0.0 126820  7012 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10998  0.0  0.0 126820  5000 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     10999  0.0  0.0 126820  7048 ?        Ss   Jun01   0:00      |       |   \_ ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
root     11046  0.8  0.6 1823140 219336 ?      Sl   Jun01  87:52      |       \_ frigate.capture:Front
root     11072  3.0  0.0 134592 18456 ?        Ss   Jun01 328:08      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Front?video&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Front@%Y%m%d%H%M%S%z.mp4
root      6319  2.2  0.4 9621624 158492 ?      Ssl  Jun03 184:24      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Front247?video -r 7 -vf fps=7,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     11051  0.8  0.6 1823140 220292 ?      Sl   Jun01  88:24      |       \_ frigate.capture:Driveway
root     21478  4.6  0.0 158708 25792 ?        Ssl  02:00  25:47      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Driveway?video&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Driveway@%Y%m%d%H%M%S%z.mp4
root     20881  2.1  0.5 9623460 165712 ?      Ssl  02:00  12:12      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Driveway247?video -r 7 -vf fps=7,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     11061  0.8  0.6 1823140 219976 ?      Sl   Jun01  89:57      |       \_ frigate.capture:Garage
root     20877  4.9  0.0 157216 24432 ?        Ssl  02:00  27:22      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garage?video&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Garage@%Y%m%d%H%M%S%z.mp4
root     20873  2.2  0.5 9623476 168448 ?      Ssl  02:00  12:16      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garage247?video -r 7 -vf fps=7,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     11089  0.8  0.6 1823472 220396 ?      Sl   Jun01  94:40      |       \_ frigate.capture:Driveway_247
root     20646  2.2  0.5 9624264 171476 ?      Ssl  02:00  12:47      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Driveway247?video -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Driveway_247@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     11096  0.8  0.6 1823472 222132 ?      Sl   Jun01  96:38      |       \_ frigate.capture:Garage_247
root     20659  2.2  0.5 9624128 167296 ?      Ssl  02:00  12:46      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garage247?video -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garage_247@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     11057  0.7  0.6 1823140 219936 ?      Sl   Jun01  87:08      |       \_ frigate.capture:Garden
root     19522  4.5  0.0 158428 25272 ?        Ssl  02:00  25:22      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garden?video&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Garden@%Y%m%d%H%M%S%z.mp4
root     19515  2.1  0.5 9623412 167576 ?      Ssl  02:00  11:47      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garden247?video -r 7 -vf fps=7,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     10971  0.5  0.0  14256  5280 ?        S    Jun01  59:34      |       \_ /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(69)
root     11071  0.5  0.6 1823140 219052 ?      Sl   Jun01  63:56      |       \_ frigate.capture:Downstairs
root      6646  5.2  0.5 9696468 183964 ?      Ssl  Jun03 428:16      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Downstairs?video&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Downstairs@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     11080  0.5  0.6 1826516 217568 ?      Sl   Jun01  63:00      |       \_ frigate.capture:Front_247
root     11090  1.9  0.4 9622596 163428 ?      Ssl  Jun01 211:57      |       |   \_ ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Front247?video -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_247@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root      9015  0.0  0.2 1174664 97496 ?       S    Jun01   1:15      |       \_ frigate.logger
root      8163  0.0  0.0    212    24 ?        S    Jun01   0:00      \_ s6-supervise frigate-log
65534     8218  0.0  0.0    276    12 ?        Ss   Jun01   0:00      |   \_ s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate
root      8164  0.0  0.0    212    24 ?        S    Jun01   0:00      \_ s6-supervise go2rtc
root      8225 16.3  0.1 1243212 51600 ?       Ssl  Jun01 1789:31      |   \_ /usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml
root     19525  3.0  0.0 157944 26496 ?        Sl   02:00  16:54      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/839205513c401a659f62fafb66cfed60
root     20883  3.0  0.0 157980 25564 ?        Sl   02:00  16:45      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/158bc1b215dbaf99d475490f6c80dd54
root     21479  3.0  0.0 158096 26052 ?        Sl   02:00  17:08      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5efea959eaa941771256e9b769e56ca5
root     23581  2.9  0.0 158668 17236 ?        Sl   Jun02 312:30      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/839205513c401a659f62fafb66cfed60
root     24056  2.9  0.0 158628 17256 ?        Sl   Jun02 317:09      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5efea959eaa941771256e9b769e56ca5
root     24539  2.8  0.0 157784 17248 ?        Sl   Jun02 305:23      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/158bc1b215dbaf99d475490f6c80dd54
root     19517  0.7  0.0 131664 24204 ?        S    02:00   4:04      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/a9ffc7f972a86a39f24ae7bf75595e43
root     20648  0.7  0.0 131660 27920 ?        S    02:00   3:59      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/de319af3336ee28a73d8c2521ed9d586
root     20661  0.7  0.0 131356 23956 ?        S    02:00   4:07      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6dc596b3d9f28d982965e3473b1b0f40
root      6297  0.6  0.0 131964 17980 ?        S    Jun03  54:41      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/a9ffc7f972a86a39f24ae7bf75595e43
root      6343  0.6  0.0 131352 20228 ?        S    Jun03  56:22      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6dc596b3d9f28d982965e3473b1b0f40
root      6368  0.6  0.0 131360 17860 ?        S    Jun03  54:55      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/de319af3336ee28a73d8c2521ed9d586
root     11070  0.0  0.0 131356 16716 ?        S    Jun01   3:31      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/de319af3336ee28a73d8c2521ed9d586
root     11079  0.0  0.0 131352 10864 ?        S    Jun01   3:33      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/a9ffc7f972a86a39f24ae7bf75595e43
root     11087  0.0  0.0 131352 14688 ?        S    Jun01   3:29      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6dc596b3d9f28d982965e3473b1b0f40
root     11088  0.0  0.0 157376 15376 ?        Sl   Jun01  10:09      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5efea959eaa941771256e9b769e56ca5
root     11095  0.0  0.0 156552 13072 ?        Sl   Jun01   9:51      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/839205513c401a659f62fafb66cfed60
root     11102  0.0  0.0 156948 14040 ?        Sl   Jun01   8:30      |       \_ ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.x.x.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/158bc1b215dbaf99d475490f6c80dd54
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Mix of Hikvision and Reolink
