### DISCUSSION TITLE
[Bug]: pano camera in cam views larger than it should (oversized black bar right and left)

### DISCUSSION THREAD

**Discussion by iamhermes** [blakeblackshear/frigate#11918] [Report a Bug]
### Describe the problem you are having

two wide angle camera streams are shown with black bars right and left.
browser size doesnt matter  (Chrome 125.0.6422.142)

moved from 0.13 to 0.14.0-e3c8901

<img width="368" alt="image" src="https://github.com/blakeblackshear/frigate/assets/4535068/8794e801-8763-4ee5-b2b6-6aaab65fecf4">
<img width="1276" alt="image" src="https://github.com/blakeblackshear/frigate/assets/4535068/909791ce-235e-4e0a-93e4-6f03e9fe82ea">

### Steps to reproduce

reload site

### Version

0.14.0-e3c8901

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

model:
  path: plus://11xxxxxxxxxxx613   

go2rtc:
  streams:
    sub_vorn:
      - rtsp://admin:notknownpw@192.168.220.51:554/Streaming/channels/102#timeout=30#backchannel=0
    sub_hinten:
      - rtsp://admin:notknownpw@192.168.220.52:554/Streaming/channels/102#timeout=30#backchannel=0
    sub_eingang:
      - rtsp://admin:notknownpw@192.168.220.53:554/Streaming/channels/102#timeout=30#backchannel=0

cameras:
  vorn:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:notknownpw@192.168.220.51:554/Streaming/channels/101 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        #- detect
        - path: rtsp://127.0.0.1:8554/sub_vorn # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
      filters:
        cat:
          max_area: 5000
    detect:
      fps: 6
    zones:
      vorderer_Bereich:
        coordinates: 934,161,647,144,587,86,313,129,94,343,268,536,947,536,1149,304
        objects:
          - person
          - cat
    snapshots:
      enabled: true
      retain:
        default: 30
    live:
      stream_name: sub_vorn
    webui_url: http://192.168.220.51/doc/page/config.asp
    ui:
      order: 2
      dashboard: true
  hinten:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:notknownpw@192.168.220.52:554/Streaming/channels/101
          roles:
            - record
        #- detect
        - path: rtsp://127.0.0.1:8554/sub_hinten # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
      filters:
        cat:
          max_area: 5000
    detect:
      fps: 6
    zones:
      hinterer_Bereich:
        coordinates: 614,253,641,88,827,84,1200,298,969,536,234,536,87,389,209,286
        objects:
          - person
          - cat
    snapshots:
      enabled: true
      retain:
        default: 30
    live:
      stream_name: sub_hinten
    webui_url: http://192.168.220.52/doc/page/config.asp
    ui:
      order: 3
      dashboard: true
      
  eingang:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:notknownpw@192.168.220.53:554/Streaming/channels/101
          roles:
            - record
        #- detect
        - path: rtsp://127.0.0.1:8554/sub_eingang # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
    detect:
      fps: 6
    snapshots:
      enabled: true
      retain:
        default: 30
      required_zones:
        - Weg
        - Treppe
    zones:
      Weg:
        coordinates: 662,519,659,392,1065,214,1258,329,1254,720,403,720,85,634,59,488,426,636
      Treppe:
        coordinates: 
          0.248,0.432,0.233,0.089,0.142,0.15,0.167,0.634,0.33,0.881,0.523,0.718,0.512,0.593,0.276,0.418
        inertia: 3
    live:
      stream_name: sub_eingang
    webui_url: http://192.168.220.53/doc/page/config.asp
    ui:
      order: 1
      dashboard: true

#  ov:
#    type: openvino
#    device: AUTO
#    model:
#      path: plus://af879a7f9dd371e1bd277048d9f75fdc
    review:
      alerts:
        required_zones:
          - Weg
          - Treppe

ui:
  timezone: Europe/Berlin
  time_format: 24hour
  date_style: short
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: '%Y/%m/%d %H:%M'

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

birdseye:
  enabled: false
  mode: continuous
version: 0.14
```

### Relevant log output

```shell
{
  "sub_eingang": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264, H265",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:35642",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.3\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAmawJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAmaACgIAtH+KrTuiS7/8AAQABbAgCJVEADN/mAEA=; sprop-pps=RAHAcvAbJH0=\r\na=control:trackID=0\r\n",
        "send": 148868324,
        "senders": [
          {
            "bytes": 147111348,
            "codec": {
              "codec_name": "h265",
              "codec_type": "video"
            },
            "packets": 109811
          }
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/sub_eingang",
        "user_agent": "FFmpeg Frigate/0.14.0-e3c8901"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265",
          "audio, recvonly, PCMU/8000"
        ],
        "receivers": [
          {
            "bytes": 147111348,
            "codec": {
              "codec_name": "h265",
              "codec_type": "video"
            },
            "packets": 109811
          },
          {
            "bytes": 10723520,
            "codec": {
              "codec_name": "pcm_mulaw",
              "codec_type": "audio",
              "sample_rate": 8000
            },
            "packets": 33511
          }
        ],
        "recv": 159568424,
        "remote_addr": "192.168.220.53:554",
        "sdp": "v=0\r\no=- 1718227405337306 1718227405337306 IN IP4 192.168.220.53\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5100\r\nt=0 0\r\na=control:rtsp://192.168.220.53:554/Streaming/channels/102/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:1280,720\r\na=control:rtsp://192.168.220.53:554/Streaming/channels/102/trackID=1\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAmawJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAmaACgIAtH+KrTuiS7/8AAQABbAgCJVEADN/mAEA=; sprop-pps=RAHAcvAbJH0=\r\nm=audio 0 RTP/AVP 0\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://192.168.220.53:554/Streaming/channels/102/trackID=2\r\na=rtpmap:0 PCMU/8000\r\na=Media_header:MEDIAINFO=494D4B48010300000400050010710110401F000000FA000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://192.168.220.53:554/Streaming/channels/102/",
        "user_agent": "go2rtc/1.9.3"
      }
    ]
  },
  "sub_hinten": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264, H265",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:35638",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.3\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAmawJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAmaACWIAiHy4qtO6JLv/wABAAFsCAIlUQAM3+YAQ=; sprop-pps=RAHAcvAbJOU=\r\na=control:trackID=0\r\n",
        "send": 108610632,
        "senders": [
          {
            "bytes": 107318952,
            "codec": {
              "codec_name": "h265",
              "codec_type": "video"
            },
            "packets": 80730
          }
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/sub_hinten",
        "user_agent": "FFmpeg Frigate/0.14.0-e3c8901"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265",
          "audio, recvonly, PCMU/8000"
        ],
        "receivers": [
          {
            "bytes": 107318952,
            "codec": {
              "codec_name": "h265",
              "codec_type": "video"
            },
            "packets": 80730
          },
          {
            "bytes": 10713280,
            "codec": {
              "codec_name": "pcm_mulaw",
              "codec_type": "audio",
              "sample_rate": 8000
            },
            "packets": 33479
          }
        ],
        "recv": 119410704,
        "remote_addr": "192.168.220.52:554",
        "sdp": "v=0\r\no=- 1718227406654184 1718227406654184 IN IP4 192.168.220.52\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5100\r\nt=0 0\r\na=control:rtsp://192.168.220.52:554/Streaming/channels/102/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:1200,536\r\na=control:rtsp://192.168.220.52:554/Streaming/channels/102/trackID=1\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAmawJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAmaACWIAiHy4qtO6JLv/wABAAFsCAIlUQAM3+YAQ=; sprop-pps=RAHAcvAbJOU=\r\nm=audio 0 RTP/AVP 0\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://192.168.220.52:554/Streaming/channels/102/trackID=2\r\na=rtpmap:0 PCMU/8000\r\na=Media_header:MEDIAINFO=494D4B48010300000400050010710110401F000000FA000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://192.168.220.52:554/Streaming/channels/102/",
        "user_agent": "go2rtc/1.9.3"
      }
    ]
  },
  "sub_vorn": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264, H265",
          "audio, sendonly, MPEG4-GENERIC"
        ],
        "remote_addr": "127.0.0.1:35634",
        "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.3\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAmawJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAmaACWIAiHy4qtO6JLv/wABAAFsCAIlUQAM3+YAQ=; sprop-pps=RAHAcvAbJAE=\r\na=control:trackID=0\r\n",
        "send": 120849520,
        "senders": [
          {
            "bytes": 119430656,
            "codec": {
              "codec_name": "h265",
              "codec_type": "video"
            },
            "packets": 88679
          }
        ],
        "type": "RTSP passive consumer",
        "url": "rtsp://127.0.0.1:8554/sub_vorn",
        "user_agent": "FFmpeg Frigate/0.14.0-e3c8901"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265",
          "audio, recvonly, PCMU/8000"
        ],
        "receivers": [
          {
            "bytes": 119430656,
            "codec": {
              "codec_name": "h265",
              "codec_type": "video"
            },
            "packets": 88679
          },
          {
            "bytes": 10712960,
            "codec": {
              "codec_name": "pcm_mulaw",
              "codec_type": "audio",
              "sample_rate": 8000
            },
            "packets": 33478
          }
        ],
        "recv": 131616932,
        "remote_addr": "192.168.220.51:554",
        "sdp": "v=0\r\no=- 1718227406636531 1718227406636531 IN IP4 192.168.220.51\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5100\r\nt=0 0\r\na=control:rtsp://192.168.220.51:554/Streaming/channels/102/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:1200,536\r\na=control:rtsp://192.168.220.51:554/Streaming/channels/102/trackID=1\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAmawJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAmaACWIAiHy4qtO6JLv/wABAAFsCAIlUQAM3+YAQ=; sprop-pps=RAHAcvAbJAE=\r\nm=audio 0 RTP/AVP 0\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://192.168.220.51:554/Streaming/channels/102/trackID=2\r\na=rtpmap:0 PCMU/8000\r\na=Media_header:MEDIAINFO=494D4B48010300000400050010710110401F000000FA000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://192.168.220.51:554/Streaming/channels/102/",
        "user_agent": "go2rtc/1.9.3"
      }
    ]
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

annke i91dw

### Any other information that may be helpful

sub stream 1200x536px
sub stream 1280x720px no problem
