### DISCUSSION TITLE
[Bug]: Strange Chrome preview playback bug

### DISCUSSION THREAD

**Discussion by jasonmadigan** [blakeblackshear/frigate#11912] [Report a Bug]
### Describe the problem you are having

On Chrome (126.0.6478.56) for arm64 on macOS, review clips from one particular camera (a Hikvision DS-2CD2383G0-IU - the "gate" camera in the config) never load. I'm fairly sure I saw clips load and play fine on Beta 1 at some point, but not with Beta 2 (or dev:latest).

![Screenshot 2024-06-12 at 15 13 44](https://github.com/blakeblackshear/frigate/assets/4467/8788f4c8-ea4e-4ea4-b8c9-3a30d0354c2e)

Clips from this camera do play correctly on Safari.

I don't see any failed requests in the Chrome request tab. I can send a HAR of a hanging request flow privately if helpful.
I've also skimmed the Frigate + goRTC logs, but these also do not show any errors when viewing clips from this camera.

The camera in question isn't particularly odd. It supports H264, and both the substream and main stream are H264. The main stream has an MP3 audio sub-stream.

### Steps to reproduce

In my case, the reproduce I:

- Navigate to Reviews
- Click a clip associated with this specific camera
- Watch the spinner spin indefinitely

### Version

0.14-beta2

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
go2rtc:
  webrtc:
    candidates:
      - 192.168.1.230:8555
      - stun:8555
  rtsp:
    username: ****
    password: ***
  streams:
    gate_substream:
      - rtsp://****:****@192.168.1.151:554/Streaming/Channels/2/
      - "ffmpeg:gate#audio=aac"
    frontdoor_substream:
      - rtsp://****:****@192.168.1.159:554/h264Preview_01_sub
      - "ffmpeg:frontdoor#audio=aac"
    pumphouse_substream:
      - rtsp://****:****@192.168.1.150/Preview_01_sub
      - "ffmpeg:pumphouse#audio=aac"
    rear_substream:
      - rtsp://****:****@192.168.1.156:554/Streaming/Channels/102/
      - "ffmpeg:rear#audio=aac"
    garage_substream:
      - rtsp://****:****@192.168.1.152:554/Streaming/Channels/3/
      - "ffmpeg:garage#audio=aac"
    patio_substream:
      - rtsp://****:****@192.168.3.4:554/Streaming/Channels/3/
      - "ffmpeg:patio#audio=aac"
    frontlawn_substream:
      - rtsp://****:****@192.168.3.2:554/Streaming/Channels/3/
      - "ffmpeg:frontlawn#audio=aac"
    garageinterior_substream:
      - rtsp://****:****@192.168.3.3:554/Streaming/Channels/2/
      - "ffmpeg:garageinterior#audio=aac"
    sidegarden_substream:
      - rtsp://****:****@192.168.3.5:554/Streaming/Channels/3/
      - "ffmpeg:sidegarden#audio=aac"
    pumphouseinside_substream:
      - rtsp://****:****@192.168.1.157:554/Streaming/Channels/2/
      - "ffmpeg:pumphouseinside#audio=aac"
    gate:
      - rtsp://****:****@192.168.1.151:554/Streaming/Channels/1/
      - ffmpeg:gate#audio=aac
    rear:
      - rtsp://****:****@192.168.1.156:554/Streaming/Channels/101/
      - ffmpeg:rear#audio=aac
    pumphouse:
      - rtsp://****:****@192.168.1.150:554/Preview_01_autotrack
      - ffmpeg:pumphouse#audio=aac
    pumphouseinside:
      - rtsp://****:****@192.168.1.157:554/Streaming/Channels/1/
    garage:
      - rtsp://****:****@192.168.1.152:554/Streaming/Channels/1/
      - ffmpeg:garage#audio=aac
    patio:
      - rtsp://****:****@192.168.3.4:554/Streaming/Channels/1/
      - ffmpeg:patio#audio=aac
    frontlawn:
      - rtsp://****:****@192.168.3.2:554/Streaming/Channels/1/
      - ffmpeg:frontlawn#audio=aac
    garageinterior:
      - rtsp://****:****@192.168.3.3:554/Streaming/Channels/1/
      - ffmpeg:garageinterior#audio=aac
    sidegarden:
      - rtsp://****:****@192.168.3.5:554/Streaming/Channels/1/
      - ffmpeg:sidegarden#audio=aac
    frontdoor:
      - rtsp://****:****@192.168.1.159:554/h264Preview_01_main
      - ffmpeg:sidegarden#audio=aac

mqtt:
  host: 192.168.1.230
  user: ***
  password:  ***

ffmpeg:
  hwaccel_args: preset-vaapi

motion:
  improve_contrast: true

objects:
  track:
    - person
    - car
    - truck
    - dog
    - cat
    - cow
    - horse
    - motorcycle
    - bus
    - bird
  filters:
    bird:
      min_score: 0.6
      threshold: 0.7
    car:
      min_score: 0.6
      threshold: 0.7
    truck:
      min_score: 0.55
      threshold: 0.6
    person:
      min_score: 0.65
      threshold: 0.75
    cow:
      min_score: 0.65
      threshold: 0.75

cameras:
  # test:
  #   ffmpeg:
  #     inputs:
  #       - path: /media/frigate/car.mp4
  #         input_args: -re -stream_loop -1 -fflags +genpts
  #         roles:
  #           - detect
  #   detect:
  #     height: 2160
  #     width: 3840
  #     fps: 15
  #   objects:
  #     filters:
  #       car:
  #         min_score: 0.45
  #         threshold: 0.55
  frontdoor:
    live:
      stream_name: frontdoor_substream
    motion:
      mask:
        - 0,0,640,0,640,156,341,146,0,133
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      filters:
        car:
          mask:
            - 298,179,488,170,640,168,640,423,276,395 # Car
  gate:
    live:
      stream_name: gate_substream
    motion:
      mask:
        - 0,0,640,0,640,42,250,67,0,82
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gate_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/gate?video&audio
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      filters:
        car:
          min_score: 0.55
          threshold: 0.65
          mask:
            - 0,172,32,164,26,119,0,125 # main road
        horse:
          mask:
            - 84,96,355,96,343,161,216,164,108,168
        cow:
          mask: 0.131,0.2,0.555,0.2,0.536,0.335,0.338,0.342,0.169,0.35
    zones:
      road:
        coordinates: 0,216,212,226,315,229,442,227,552,206,562,155,640,153,640,0,377,0,0,0
        filters:
          car:
            min_score: 0.55
            threshold: 0.65
      entrance:
        coordinates: 491,273,567,269,575,172,640,182,640,480,485,480,308,480,0,480,0,359,0,274
        filters:
          car:
            min_score: 0.55
            threshold: 0.65
  pumphouse:
    live:
      stream_name: pumphouse_substream
    onvif:
      host: 192.168.1.150
      port: 8000
      user: ****
      password: ****
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pumphouse
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/pumphouse
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      filters:
        person:
          threshold: 0.74
        car: {}
        cat: {}
        dog: {}
  pumphouseinside:
    live:
      stream_name: pumphouseinside_substream
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pumphouseinside_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/pumphouseinside
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
  rear:
    live:
      stream_name: rear_substream
    motion:
      threshold: 100
      contour_area: 35
      mask:
        - 0,217,325,97,595,0,0,0
        - 1920,0,1500,0,1612,85,1920,232
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/rear
          roles:
            - record
    detect:
      width: 1920
      height: 536
      fps: 6
  garage:
    live:
      stream_name: garage_substream
    motion:
      mask:
        - 0,0,1920,0,1920,148,926,94,386,181,250,310,0,696
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      filters:
        car:
          min_area: 800
          mask:
            - 0,0,1294,0,1566,272,789,474,291,585,0,654
        motorcycle:
          mask:
            - 722,488,427,518,433,330,677,322
        person:
          mask:
            - 722,488,427,518,433,330,677,322
            - 431,171,439,227,390,229,381,184
          min_score: 0.75
          threshold: 0.8
        cow:
          mask:
            - 0,263,348,195,0,585
        dog:
          mask:
            - 1107,69,1235,53,1283,212,1081,230
  patio:
    live:
      stream_name: patio_substream
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/patio
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      filters:
        car:
          min_area: 500
          mask:
            - 0,183,0,1080,1920,1080,1920,337,403,279
        cow:
          mask:
            - 1789,0,1804,284,1382,244,974,224,587,238,82,291,166,131,412,0,603,0
        person:
          mask: 0.359,0.103,0.377,0.58,0.211,0.569,0.214,0.129
  frontlawn:
    live:
      stream_name: frontlawn_substream
    motion:
      mask:
        - 1266,31,744,25,271,192,0,304,0,0,499,0,1920,0
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontlawn_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontlawn
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      filters:
        car:
          mask: 0,0.324,0.256,0.248,0.252,0.701,0,0.727
        person: {}
  garageinterior:
    live:
      stream_name: garageinterior_substream
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garageinterior_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garageinterior
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - bird
      filters:
        cat:
          min_area: 900
        dog:
          min_area: 900
        bird:
          min_area: 900
  sidegarden:
    live:
      stream_name: sidegarden_substream
    motion:
      mask:
        - 1920,0,1920,97,1105,74,0,327,0,0
    snapshots:
      height: 700
      enabled: true
      timestamp: true
      bounding_box: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/sidegarden_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/sidegarden
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      filters:
        cow:
          min_score: 0.6
          threshold: 0.69
        bird: {}
record:
  sync_recordings: True
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion
camera_groups:
  Gate:
    order: 1
    icon: LuCar
    cameras:
      - gate
      - frontdoor
```

### Relevant log output

```shell
frigate  | 2024-06-12 15:06:00.787642590  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:00 +0100] "GET /api/profile HTTP/1.1" 200 18 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:00.793290083  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:00 +0100] "GET /review HTTP/1.1" 200 2650 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:00.810112979  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:00 +0100] "GET /api/config HTTP/1.1" 200 0 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:00.810704573  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:00 +0100] "GET /api/review/summary?timezone=Europe%2FDublin HTTP/1.1" 200 0 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:00.813389041  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:00 +0100] "GET /api/preview/all/start/1718114400/end/1718204400 HTTP/1.1" 200 0 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:00.813659403  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:00 +0100] "GET /ws HTTP/1.1" 101 132607 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.141053801  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/review/activity/motion?before=1718200908.159&after=1718114508.159&scale=15&cameras=gate HTTP/1.1" 200 0 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.156523474  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/profile HTTP/1.1" 200 18 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.160151364  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/config HTTP/1.1" 200 64417 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.162013238  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/review/summary HTTP/1.1" 200 746 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.165949733  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/preview/all/start/1718114400/end/1718204400 HTTP/1.1" 200 40288 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.170601676  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/review?reviewed=1&before=1718201160.798&after=1718114760.798 HTTP/1.1" 200 88010 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.186768132  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/review/summary?timezone=Europe%2FDublin HTTP/1.1" 200 746 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.217107948  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /vod/gate/start/1718182800/end/1718186400/master.m3u8 HTTP/1.1" 200 174 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.221767291  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/gate/recordings?before=1718186400&after=1718182800 HTTP/1.1" 200 55089 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:01.489883951  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:01 +0100] "GET /api/review/activity/motion?before=1718201160.798&after=1718114760.798&scale=15&cameras=gate HTTP/1.1" 200 222464 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-06-12 15:06:03.050802574  ::ffff:192.168.1.69 - - [12/Jun/2024:15:06:03 +0100] "GET /api/review/summary?timezone=Europe%2FDublin HTTP/1.1" 200 746 "http://192.168.1.230:5001/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "-"
frigate  | 2024-06-12 15:06:05.511899609  ::ffff:192.168.1.149 - - [12/Jun/2024:15:06:05 +0100] "GET /api/frontdoor/latest.jpg?cache=1718201165373 HTTP/1.1" 200 52686 "http://192.168.1.230:5001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.6 Safari/605.1.15" "-"
frigate  | 2024-06-12 15:06:05.739017368  ::ffff:192.168.1.149 - - [12/Jun/2024:15:06:05 +0100] "GET /api/gate/latest.jpg?cache=1718201165596 HTTP/1.1" 200 48002 "http://192.168.1.230:5001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.6 Safari/605.1.15" "-"
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision
