### DISCUSSION TITLE
[Support]: Frigate 0.14b2 get stuck at restart from UI (ZMQ error)

### DISCUSSION THREAD

**Discussion by jsapede** [blakeblackshear/frigate#11927] [General Support] [answered]
### Describe the problem you are having

after editing config and restarting from config edition or restarting directly from UI, restart process is stuck

Docker restart is necessary to recover, and everything start to work again

### Version

0.14b2

### Frigate config file

```yaml
# LOW

#tls:
#  enabled: false

###################
# Definition MQTT #
###################
mqtt:
  host: 192.168.0.187
  port: 1883
  user: mqtt_login
  password: mqtt_pass

#####################
# Reglages Birdseye #
#####################
birdseye:
# deasactive par defaut #
  enabled: false
  mode: objects
  width: 1280
  height: 720
  quality: 24

##########
# Review #
##########

review:
  alerts:
    labels:
      - cat
      - dog
      - person
      - speech
      - bark
      - meow
      - scream
      - yell
      - fire_alarm

environment_vars:
  LIBVA_DRIVER_NAME: iHD

###################
# Defition GO2RTC #
###################
go2rtc:
  streams:
    Salon:
      - tapo://XXX@192.168.0.123
      - "ffmpeg:Salon#audio=aac"

    Cuisine:
      - tapo://xxxx@192.168.0.122
      - "ffmpeg:Cuisine#audio=aac"

    Mezzanine:
      - tapo://xxxx@192.168.0.130
      - "ffmpeg:Mezzanine#audio=aac"

    Portail:
      - rtsp://xxxx:xxx@192.168.0.186:554/Streaming/Channels/101
      - "ffmpeg:Portail#audio=aac#timeout=10"
      - isapi://xxxx:xxxx@192.168.0.186:80/


# Serveur WEBRTC #
  webrtc:
    listen: :8555
    candidates:
      - 192.168.0.112:8555
      - 90.66.180.210:8555
    ice_servers:
      - urls: [stun:stun.relay.metered.ca:80]
      - urls: [turn:global.relay.metered.ca:443]
        username: xxxx
        credential: xxx

##################
# Presets FFMPEG #
##################
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy


##############
# Detecteurs #
##############


detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


####################
# options SNAPSHOT #
####################
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  quality: 95
  retain:
    default: 7

##################
# Options record #
##################
record:
  enabled: true
  expire_interval: 10
  sync_recordings: false
  retain:
    days: 1
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 7
      mode: active_objects
    objects:
      - person
      - meow
      - cat
      - speech
##################
# Options Detect #
##################

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5
  stationary:
    interval: 50
    threshold: 50

##################
# options motion #
##################

motion:
  threshold: 50
  lightning_threshold: 0.6
  contour_area: 30
  improve_contrast: false


# options audio #

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 200
  listen:
    - speech
    - bark
    - meow
    - scream
    - yell
    - fire_alarm
    - dog
    - cat
  filters:
    speech:
      threshold: 0.8



######################
# Definition cameras #
######################

cameras:
  Cuisine:
    enabled: false
    ui:
      dashboard: false
    onvif:
      host: 192.168.0.122
      port: 2020
      user: xxx
      password: xxx
#      autotracking:
#        enabled: true
#        track:
#        - person
#        return_preset: home
#        required_zones:
#        - zone_0
    ffmpeg:
      #hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Cuisine
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.9
          min_area: 40000
        cat:
          threshold: 0.8
          min_area: 2000
          max_area: 20000
        dog:
          threshold: 0.8
          min_area: 2000
          max_area: 20000
    motion:
      mask:
        - 157,332,185,328,186,299,152,302

  Salon:
    enabled: false
    ui:
      dashboard: false
    onvif:
      host: 192.168.0.123
      port: 2020
      user: xxx
      password: xxxx
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Salon
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.9
          min_area: 40000
        cat:
          threshold: 0.8
          min_area: 2000
          max_area: 20000
        dog:
          threshold: 0.8
          min_area: 2000
          max_area: 20000


  Mezzanine:
    enabled: false
    ui:
      dashboard: false
    onvif:
      host: 192.168.0.130
      port: 2020
      user: xxx
      password: xxx
    ffmpeg:
      #hwaccel_args: preset-intel-qsv-h264
      #input_args: preset-rtsp-restream-low-latency
      inputs:
        - path: rtsp://127.0.0.1:8554/Mezzanine
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.9
          min_area: 40000
        cat:
          threshold: 0.8
          min_area: 5000
          max_area: 30000
        dog:
          threshold: 0.8
          min_area: 5000
          max_area: 30000


  Portail:
    enabled: true
    ffmpeg:
      #hwaccel_args: preset-intel-qsv-h264
      #input_args: preset-rtsp-restream-low-latency
      inputs:
        - path: rtsp://127.0.0.1:8554/Portail
          roles:
            - detect
            - audio
            - record
    objects:
      track:
        - person
        - car
      filters:
        person:
          threshold: 0.9
          min_area: 150000
        car:
          threshold: 0.9
          min_area: 50000
          #max_area: 170000
    motion:
      mask: 0.002,0.126,0.213,0.091,0.232,0,0.002,0
    zones:
      parking_commun:
        coordinates: 0.617,0.439,0.962,0.468,0.954,0.702,0.722,0.631,0.629,0.63
        objects: car
      interphone:
        coordinates: 0.12,0.996,0.122,0,0.481,0,0.48,1
        objects: person
    review:
      detections:
        required_zones:
          - parking_commun
      alerts:
        required_zones: interphone
version: 0.14
```

### Relevant log output

```shell
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2024-06-13 08:03:15.363309622  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | 2024-06-13 08:03:15.364655510  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | s6-rc: info: service certsync successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service certsync-log: stopping
frigate  | s6-rc: info: service certsync-log successfully stopped
frigate  | 2024-06-13 08:03:15.395869094  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | 2024-06-13 08:03:15.399546249  [2024-06-13 08:03:15] frigate.app                    INFO    : Stopping...
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2024-06-13 08:03:15.402106604  [2024-06-13 08:03:15] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate  | 2024-06-13 08:03:15.403135924  [2024-06-13 08:03:15] frigate.watchdog               INFO    : Exiting watchdog...
frigate  | 2024-06-13 08:03:15.403576760  [2024-06-13 08:03:15] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate  | 2024-06-13 08:03:15.404399747  [2024-06-13 08:03:15] frigate.stats.emitter          INFO    : Exiting stats emitter...
frigate  | 2024-06-13 08:03:15.405003599  [2024-06-13 08:03:15] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate  | 2024-06-13 08:03:15.405544691  [2024-06-13 08:03:15] frigate.storage                INFO    : Exiting storage maintainer...
frigate  | 2024-06-13 08:03:15.475569792  [2024-06-13 08:03:15] frigate.object_processing      INFO    : Exiting object processor...
frigate  | 2024-06-13 08:03:15.857739669  [2024-06-13 08:03:15] frigate.events.maintainer      INFO    : Exiting event processor...
frigate  | 2024-06-13 08:03:16.670163388  Exception in thread detection_proxy:
frigate  | 2024-06-13 08:03:16.670168335  Traceback (most recent call last):
frigate  | 2024-06-13 08:03:16.670189202    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
frigate  | 2024-06-13 08:03:16.670687224      self.run()
frigate  | 2024-06-13 08:03:16.670691768    File "/opt/frigate/frigate/comms/detections_updater.py", line 37, in run
frigate  | 2024-06-13 08:03:16.671235854      zmq.proxy_steerable(
frigate  | 2024-06-13 08:03:16.671240674    File "_zmq.py", line 1685, in zmq.backend.cython._zmq.proxy_steerable
frigate  | 2024-06-13 08:03:16.671243047    File "_zmq.py", line 160, in zmq.backend.cython._zmq._check_rc
frigate  | 2024-06-13 08:03:16.671248180  zmq.error.ZMQError: Operation not supported
frigate  | 2024-06-13 08:03:16.673100428  [2024-06-13 08:03:16] detector.ov                    INFO    : Signal to exit detection process...
frigate  | 2024-06-13 08:03:16.673216776  [2024-06-13 08:03:16] root                           INFO    : Waiting for detection process to exit gracefully...
frigate  | 2024-06-13 08:03:16.719591218  [2024-06-13 08:03:16] detector.ov                    INFO    : Exited detection process...
frigate  | 2024-06-13 08:03:16.743815084  [2024-06-13 08:03:16] root                           INFO    : Detection process has exited...
frigate  | 2024-06-13 08:03:17.063351906  [2024-06-13 08:03:17] frigate.comms.ws               INFO    : Exiting websocket client...
frigate  | 2024-06-13 08:03:17.063835293  [2024-06-13 08:03:17] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate  | 2024-06-13 08:03:17.067301617  [2024-06-13 08:03:17] watchdog.Portail               INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-06-13 08:03:17.068321738  [2024-06-13 08:03:17] watchdog.Portail               INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-06-13 08:03:17.206610933  [2024-06-13 08:03:17] frigate.video                  INFO    : Portail: exiting subprocess
frigate  | 2024-06-13 08:03:18.197650835  [2024-06-13 08:03:18] frigate.output.output          INFO    : exiting output process...
```

### FFprobe output from your camera

```shell
cant find on 0.14b2
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Hikvision KVE8113
