### DISCUSSION TITLE
[Bug]: Service frigate exited with code 1 (by signal 0)

### DISCUSSION THREAD

**Discussion by Newspaperman57** [blakeblackshear/frigate#11929] [Report a Bug]
### Describe the problem you are having

Attempting to try out 0.14.0-beta2, but i'm having trouble getting working. The log doesn't seem to produce any meaningful output, and the service is simply stopping... 

### Steps to reproduce

Paste config, clear database and attempt to start

### Version

0.14.0-beta2

### Frigate config file

```yaml
mqtt:
  host: homeassistant_local.cnf.dk
  user: user
  password: passwd
birdseye:
  enabled: true
  mode: continuous

database:
  path: /opt/database/database.db

logger:
  default: info

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    chicks_outdoor:
      - rtsp://surveillance:{FRIGATE_RTSP_PASS}@10.12.0.5:554/Streaming/Channels/101/

cameras:
  chicks_outdoor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/chicks_outdoor
          roles:
            - record
        - path: rtsp://surveillance:{FRIGATE_RTSP_PASS}@10.12.0.5:554/Streaming/Channels/102/
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
        - horse
        - cat
        - dog
        - mouse
    record:
      enabled: true
      retain:
        days: 7
    snapshots:
      enabled: false
version: 0.14
```


### Relevant log output

```shell
✔ Container frigate  Created                                                                                                                                                                                                                                                                                                                                                                                                                                    0.0s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-06-13 10:23:23.219602455  [INFO] Preparing Frigate...
frigate  | 2024-06-13 10:23:23.219892827  [INFO] Preparing new go2rtc config...
frigate  | 2024-06-13 10:23:23.226070649  [INFO] Starting NGINX...
frigate  | 2024-06-13 10:23:23.259263565  [INFO] Starting Frigate...
frigate  | 2024-06-13 10:23:23.683359831  [INFO] Starting go2rtc...
frigate  | 2024-06-13 10:23:23.853224935  10:23:23.852 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-06-13 10:23:23.853230705  10:23:23.852 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-06-13 10:23:23.853233490  10:23:23.852 INF [rtsp] listen addr=:8554
frigate  | 2024-06-13 10:23:23.853236194  10:23:23.852 INF [api] listen addr=:1984
frigate  | 2024-06-13 10:23:23.853238727  10:23:23.852 INF [webrtc] listen addr=:8555/tcp
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-06-13 10:23:24.261640453  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-06-13 10:23:24.287258229  ::ffff:127.0.0.1 - - [13/Jun/2024:10:23:24 +0200] "" 400 0 "-" "-" "-"
frigate  | 2024-06-13 10:23:25.601321920  [2024-06-13 10:23:25] frigate.app                    INFO    : Starting Frigate (0.14.0-bccffe6)
frigate  | 2024-06-13 10:23:25.604257235  [2024-06-13 10:23:25] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-06-13 10:23:25.628827118  [2024-06-13 10:23:25] frigate.util.config            INFO    : copying config as backup...
frigate  | 2024-06-13 10:23:25.658717535  [2024-06-13 10:23:25] frigate.util.config            INFO    : Migrating frigate config from 0.13 to 0.14...
frigate  | 2024-06-13 10:23:25.678469352  [2024-06-13 10:23:25] frigate.util.config            INFO    : Migrating export file names...
frigate  | 2024-06-13 10:23:25.707665389  [2024-06-13 10:23:25] frigate.util.config            INFO    : Finished frigate config migration...
frigate  | 2024-06-13 10:23:26.008125118  [2024-06-13 10:23:26] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
frigate  | 2024-06-13 10:23:27.238637835  2024/06/13 10:23:27 [error] 153#153: *2 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:10.20.1.120, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "10.10.1.125:5000"
frigate  | 2024-06-13 10:23:27.238644175  2024/06/13 10:23:27 [error] 153#153: *2 auth request unexpected status: 502 while sending to client, client: ::ffff:10.20.1.120, server: , request: "GET /api/stats HTTP/1.1", host: "10.10.1.125:5000"
frigate  | 2024-06-13 10:23:32.239151496  2024/06/13 10:23:32 [error] 155#155: *4 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:10.20.1.120, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "10.10.1.125:5000"
frigate  | 2024-06-13 10:23:32.239173920  2024/06/13 10:23:32 [error] 155#155: *4 auth request unexpected status: 502 while sending to client, client: ::ffff:10.20.1.120, server: , request: "GET /api/stats HTTP/1.1", host: "10.10.1.125:5000"
frigate  | 2024-06-13 10:23:32.867332496  [2024-06-13 10:23:32] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
frigate  | 2024-06-13 10:23:32.881892686  '/opt/database/database.db' and '/opt/database/database.db' are the same file
frigate  | 2024-06-13 10:23:32.882736869  [2024-06-13 10:23:32] frigate.app                    INFO    : Making backup of DB before migrations...
frigate  | 2024-06-13 10:23:33.226221399  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-06-13 10:23:34.262700072  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2024-06-13 10:23:34.276504271  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-06-13 10:23:34.281578617  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | s6-rc: info: service certsync successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service certsync-log: stopping
frigate  | s6-rc: info: service certsync-log successfully stopped
frigate  | 2024-06-13 10:23:34.364525112  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | 2024-06-13 10:23:34.368944241  exit with signal: terminated
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2024-06-13 10:23:34.374411290  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```


### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision via RTSP

### Any other information that may be helpful

docker-compose.yml
```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /opt/database:/opt/database/
      - /etc/localtime:/etc/localtime:ro
      - /mnt/surveillance/frigate/config:/config/
      - /mnt/surveillance/frigate:/media/frigate
      - type: tmpfs # Optional: 100MB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 100000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
