### DISCUSSION TITLE
[Bug]: Frigate+ shows unavailable snapshots

### DISCUSSION THREAD

**Discussion by bakedhorse** [blakeblackshear/frigate#11939] [Report a Bug] [answered]
### Describe the problem you are having

This has been a problem, even before 0.14. For some reason, some snapshots just aren't available. With the new frigate+ page, it now displays these unavailable snapshots. This occurs for every object.

(Note, I have only ran 0.14 for like 2 days and already saw 3 of these)

### Steps to reproduce

1. Setup frigate+ and snapshots
2. Let cameras capture for awhile (and I mean awhile)
3. Presto, you might've got some unavailable snapshots showing on Frigate+ page.

### Version

0.14.0-e56ce99

### Frigate config file

```yaml
##################

snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  timestamp: false
  retain:
    default: 10
    objects:
      person: 15

###########
```

### Relevant log output

```shell
None.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Not relevant.

### Any other information that may be helpful

![Screenshot_20240613_105327](https://github.com/blakeblackshear/frigate/assets/101318210/0b505bab-05ed-409b-a580-3724133a566c)
![Screenshot_20240613_105400](https://github.com/blakeblackshear/frigate/assets/101318210/2578e71d-618d-4b39-9668-66c45ad043ad)
![Screenshot_20240613_105417](https://github.com/blakeblackshear/frigate/assets/101318210/675c109d-a384-4c86-9bfe-b50d9a3f2f4c)
![Screenshot_20240613_110346](https://github.com/blakeblackshear/frigate/assets/101318210/43cb8a14-cb2d-48e8-b799-b3dd5d68a14d)
