### DISCUSSION TITLE
[Config Support]: Configuring CodeProjectAI with Double Take and Frigate

### DISCUSSION THREAD

**Discussion by jupytertemi** [blakeblackshear/frigate#11932] [Config Support]
### Describe the problem you are having

I cant seem to find any up-to-date documentation on integrating Codeproject AI with frigate and Double Take for Object Detection and Face Recognition.
I will appreciate if anyone could share a link to the latest deployment guide.
Thank you.

### Version

3.9

### Frigate config file

```yaml
------------------------------------------
CONFIGURATION.YML (CODEPROJECTAI SETTINGS)
------------------------------------------
image_processing:
  - platform: codeprojet_ai_object
    ip_address: localhost
    port: 32168
    # confidence: 80
    save_file_folder: /config/snapshots/
    save_file_format: png
    save_timestamped_file: True
    always_save_latest_file: True
    scale: 0.75
    # roi_x_min: 0.35
    roi_x_max: 0.8
    #roi_y_min: 0.4
    roi_y_max: 0.8
    crop_to_roi: True
    targets:
      - target: person
      - target: vehicle
        confidence: 60
      - target: car
        confidence: 40
    source:
      - entity_id: camera.gaagecamera


---------------
FRIGATE CONFIG
---------------
# yaml-language-server: schema=http://ccab4aaf-frigate-fa:5000/api/config/schema.json

mqtt:
  host: 192.168.0.63
  user: admin  # Replace with your MQTT username
  password: 1BeachHouse@2023  # Replace with your MQTT password

audio: # <- enable audio events for all camera
  enabled: True

cameras:
  GarageCamera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:mypassword@192.168.0.117:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record 
            - audio         
          input_args: -analyzeduration 1000M -probesize 1000M
        - path: rtsp://admin:mypassword@192.168.0.117:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
          input_args: -analyzeduration 1000M -probesize 1000M
    detect:
      width: 640
      height: 360
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 10
    objects:
      track:
        - person
        - car
        - dog


-------------------
DOUBLE TAKE CONFIG
-------------------
mqtt:
  host: 192.168.0.63
  username: admin
  password: mypassword
  
frigate:
  url: http://ccab4aaf-frigate-fa:5000

detectors:
  deepstack:
    url: http://192.168.0.63:90
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB
