### DISCUSSION TITLE
[Config Support]: ffmpeg exec for mosaic

### DISCUSSION THREAD

**Discussion by protocol6v** [blakeblackshear/frigate#11934] [Config Support]
### Describe the problem you are having

I am trying to use frigate's existing go2rtc to create a restream of a few cameras in a mosaic as birdseye does not format correctly for some of my use cases. Cannot seem to get any options to work. Someone else on here had a small config that allegedly worked for them, but does not seem to be working at all for me when trying to connect to the stream with vlc. 

In my config, I am working with the "mosaic" stream. If i replace the mosaic stream config with just a regular camera connection, vlc will pull up the stream, but nothing else more advanced seems to work.

I have never had good luck getting any advanced ffmpeg options working in the frigate config, so I'm sure it is something I am doing wrong, but im struggling to identify what it is i'm missing. Appreciate any help!

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate_host/api/config/schema.json
mqtt:
  enabled: True
  host: mqtt
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  retain:
    days: 14
  events:
    pre_capture: 10
    post_capture: 10
    objects:
      - person
rtmp:
  enabled: False
birdseye:
  enabled: True
  restream: true
  width: 1920
  height: 1440
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  #quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
detect:
  width: 1280
  height: 960
ffmpeg:
  hwaccel_args: preset-nvidia-h264
go2rtc:
  streams:
    1_Front_Door_Record:
      - rtsp://frigate:camerapassword@192.168.0.29:554/cam/realmonitor?channel=1&subtype=0
    1_Front_Door_Detect:
      - rtsp://frigate:camerapassword@192.168.0.29:554/cam/realmonitor?channel=1&subtype=1
    2_Reception_Record:
      - rtsp://frigate:camerapassword@192.168.0.25:554/cam/realmonitor?channel=1&subtype=0
    2_Reception_Detect: ffmpeg:rtsp://frigate:camerapassword@192.168.0.25:554/cam/realmonitor?channel=1&subtype=1#video=h264#raw=-vf "scale=704:480,setdar=16/9"
    3_Hallway_1_Record:
      - rtsp://frigate:camerapassword@192.168.0.24:554/cam/realmonitor?channel=1&subtype=0
    3_Hallway_1_Detect: ffmpeg:rtsp://frigate:camerapassword@192.168.0.24:554/cam/realmonitor?channel=1&subtype=1#video=h264#raw=-vf "scale=704:480,setdar=16/9"
    4_Hallway_2_Record:
      - rtsp://frigate:camerapassword@192.168.0.23:554/cam/realmonitor?channel=1&subtype=0
    4_Hallway_2_Detect: ffmpeg:rtsp://frigate:camerapassword@192.168.0.23:554/cam/realmonitor?channel=1&subtype=1#video=h264#raw=-vf "scale=640:480,setdar=16/9"
    5_Man_Trap_Record:
      - rtsp://frigate:camerapassword@192.168.0.22:554/cam/realmonitor?channel=1&subtype=0
    5_Man_Trap_Detect: ffmpeg:rtsp://frigate:camerapassword@192.168.0.22:554/cam/realmonitor?channel=1&subtype=1#video=h264#raw=-vf "scale=640:480,setdar=16/9"
    6_DC_Record:
      - rtsp://frigate:camerapassword@192.168.0.21:554/cam/realmonitor?channel=1&subtype=0
    6_DC_Detect:
      - rtsp://frigate:camerapassword@192.168.0.21:554/cam/realmonitor?channel=1&subtype=1
    7_Roof_Gen_Record:
      - rtsp://frigate:camerapassword@192.168.0.26:554/cam/realmonitor?channel=1&subtype=0
    7_Roof_Gen_Detect:
      - rtsp://frigate:camerapassword@192.168.0.26:554/cam/realmonitor?channel=1&subtype=1
    8_Side_Door_Record:
      - rtsp://frigate:camerapassword@192.168.0.27:554/cam/realmonitor?channel=1&subtype=0
    8_Side_Door_Detect: ffmpeg:rtsp://frigate:camerapassword@192.168.0.27:554/cam/realmonitor?channel=1&subtype=1#video=h264#raw=-vf "scale=640:480,setdar=16/9"
    9_Front_Closet_Record:
      - rtsp://frigate:camerapassword@192.168.0.28:554/cam/realmonitor?channel=1&subtype=0
    9_Front_Closet_Detect: ffmpeg:rtsp://frigate:camerapassword@192.168.0.28:554/cam/realmonitor?channel=1&subtype=1#video=h264#raw=-vf "scale=640:480,setdar=16/9"
    mosaic:
      - exec:ffmpeg -hide_banner -re
        -i rtsp://127.0.0.1:8554/2_Reception_Detect
        -i rtsp://127.0.0.1:8554/3_Hallway_1_Detect
        -i rtsp://127.0.0.1:8554/4_Hallway_2_Detect
        -filter_complex xstack=inputs=3
        -c copy -rtsp_transport tcp -f rtsp {{output}}
  log:
    exec: trace
    streams: trace
    rtsp: trace
  webrtc:
    candidates:
      - 192.168.0.20:8555
      - stun:8555
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100


cameras:
  1_Front_Door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/1_Front_Door_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/1_Front_Door_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    live:
      stream_name: 1_Front_Door_Detect
    objects:
      filters:
        person:
          mask:
            - 1251,622,971,680,974,48,1232,47
    zones:
      openfrontdoor:
        coordinates: 0,480,397,480,245,273,77,54,0,65
  2_Reception:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/2_Reception_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/2_Reception_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
            - 992,671,1117,747,1210,517,1259,336,1080,289
  3_Hallway_1:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/3_Hallway_1_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/3_Hallway_1_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
  4_Hallway_2:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/4_Hallway_2_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/4_Hallway_2_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
  5_Man_Trap:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/5_Man_Trap_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/5_Man_Trap_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
  6_Data_Center:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/6_DC_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/6_DC_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
  7_Roof_Gen:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/7_Roof_Gen_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/7_Roof_Gen_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
  8_Side_Door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/8_Side_Door_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/8_Side_Door_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
  9_Front_Closet:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/9_Front_Closet_Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/9_Front_Closet_Detect
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    objects:
      filters:
        person:
          mask:
```

### Relevant log output

```shell
nothing related to "mosaic" is posted in logs
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
