### DISCUSSION TITLE
[Config Support]: After 0.13.2 upgrade, Zones not working

### DISCUSSION THREAD

**Discussion by BoostN** [blakeblackshear/frigate#11943] [Config Support] [answered]
### Describe the problem you are having

I have a NodeRed flow that will let me send a mobile app notifications.. To help reduce false alerts, I have a zone named "driveway_entry" and I filter on that. After upgrading all alerts are working but my filtered zone alerts.

Any ideas? Did some detect, config options change that I missed?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: XXXXXXXXX
  user: mqtt
  password: XXXXXXXXXXX
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  global_args: -hide_banner -loglevel debug
  input_args: -an
cameras:
  Outside_Driveway:
    ffmpeg:
      inputs:
        - path: rtsps://XXXXXXX:7441/6dXXXXXXXXXXPBy
          roles:
            - detect
            - rtmp
    motion:
      mask:
        - 1002,45,290,23,323,0,604,0,790,0,923,0
        - 0,244,258,122,340,84,422,66,482,48,549,0,143,0,0,60,0,204
    zones:
      driveway_end:
        coordinates: 372,373,239,309,402,234,449,207,580,148,755,186,1011,231,980,338
      driveway_entry:
        coordinates: 447,132,889,224,889,50,761,30
    detect:
      width: 1280
      height: 720
      fps: 7
    snapshots:
      required_zones:
        - driveway_entry
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        car:
          min_area: 18000
          min_score: 0.2
          threshold: 0.5
          mask: 125,212,169,284,263,315,563,154,407,69,262,97
        person:
          min_area: 5000
          threshold: 0.7
          mask: 933,171,891,338,966,397,1025,193
  Int_Garage:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXX:7447/utQOXXXXXXXXXpv
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 3
  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXX:7447/XXXXXXXXXXXX
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 3
  Front_Doorbell:
    ffmpeg:
      inputs:
        - path: rtsps://XXXXXXXXXX:7441/XXXXXXX
          roles:
            - detect
            - rtmp
    motion:
      mask:
        - 0,0,0,223,0,360,146,360,151,0
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
    detect:
      width: 480
      height: 360
      fps: 3
  Back_Porch:
    ffmpeg:
      inputs:
        - path: rtsps://XXXXXXXXX:7441/XXXXXXXXXXXXUzc
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
    detect:
      width: 1280
      height: 720
      fps: 3
```

### Relevant log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
