### DISCUSSION TITLE
Confidence Mismatch on Events

### DISCUSSION THREAD

**Discussion by f1d094** [blakeblackshear/frigate#11962] [Report a Bug] [answered]
### The problem:

The match confidence percentage that causes an event to trigger often (approx 70% of events) does not match the confidence level of the snapshot. Most are a only a few percent off. Some a little higher, some are a little lower. But some are off by 20% or more. This is problematic for objects that have a high min_level set because they trigger alarms/alerts. For example, the following event confidence level is reported at 75% and therefore triggered an alert via HASS...but when the snapshot is viewed it is displayed as 53%:

![75pct_but_really_53pct](https://github.com/blakeblackshear/frigate/assets/852886/db552a0b-7d0a-4c05-8978-b6f62fcce66b)

For this camera/view cars typically register around 97-98% confidence.

### Steps to reproduce

Select any event under the events tab and view the snapshot or "Send to Frigate+". Percentage confidence on event will not match percentage confidence on snapshot.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
-------snip------
  filters:
    person:
      min_score: 0.75
    package:
      min_score: 0.75
    car:
      min_score: 0.75
-------snip------
```

### Relevant log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

n/a
