### DISCUSSION TITLE
[Bug]: Sending to Frigate+ results in missing image.

### DISCUSSION THREAD

**Discussion by Amadou91** [blakeblackshear/frigate#11975] [Report a Bug] [answered]
### Describe the problem you are having

I have been using Frigate+ for months without issue, however now it seems when an image to Frigate+ the link seems to be broken and the thumbnail missing.

### Steps to reproduce

Send an image to Frigate+.
I tried to do this from the Frigate+ review section, as well as from the history playback section while viewing a recording, to no avail.

### Version

 0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxxxx
  user: xxxxx
  password: xxxxx
  port: 1883
  stats_interval: 5

detectors:
  coral:
    type: edgetpu
    device: usb

review:
  alerts:
    labels:
      - car
      - person
      - cat
      - dog

model:
  path: plus://xxxxxxxxx

audio:
  enabled: true

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 7
  quality: 100

objects:
  track: [person, face, license_plate, dog, cat, car, amazon, fedex, ups, package]

go2rtc:
  streams:
    front:
      - rtsp://user:pass@front:554/h265Preview_01_main
    frontSub:
      - rtsp://user:pass@front:554/h264Preview_01_sub
      - ffmpeg:frontSub#audio=opus
    coveralls:
      - rtsp://user:pass@coveralls:554/h265Preview_01_main
    coverallsSub:
      - rtsp://user:pass@coveralls:554/h264Preview_01_sub
      - ffmpeg:coverallsSub#audio=opus
    deck:
      - rtsp://user:pass@deck:554/h265Preview_01_main
    deckSub:
      - rtsp://user:pass@deck:554/h264Preview_01_sub
      - ffmpeg:deckSub#audio=opus
  webrtc:
    candidates:
      - xxx.xxx.x.xx:8555
      - stun:8555

cameras:
  front:
    detect:
      fps: 7
      min_initialized: 3
      max_disappeared: 50
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -c:a copy
      inputs:
        - path: rtsp://frigate:8554/front
          input_args: preset-rtsp-restream
          roles: [record, detect, audio]

    live:
      stream_name: frontSub

    mqtt:
      height: 540
      quality: 100
    objects:
      track: [person, face, license_plate, dog, cat, car, amazon, fedex, ups, package]
    motion:
      mask:
        - 0.068,0.326,0.458,0.209,0.554,0.209,0.621,0.203,0.641,0.216,0.697,0.23,1,0.305,1,0,0,0,0,0.443,0.071,0.408
        - 0.109,0.647,0.133,0.638,0.124,0.437,0.03,0.475,0.082,0.651
      improve_contrast: false
      lightning_threshold: 0.8

  coveralls:
    detect:
      fps: 7
      min_initialized: 3
      max_disappeared: 50
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -c:a copy
      inputs:
        - path: rtsp://frigate:8554/coveralls
          input_args: preset-rtsp-restream
          roles: [record, detect, audio]

    live:
      stream_name: CoverallsSub

    mqtt:
      height: 540
      quality: 100
    objects:
      track: [person, face, license_plate, dog, cat, car]
    motion:
      mask:
        - 0.749,0.477,0.855,0.606,0.862,0.494,0.786,0.4
        - 0.018,0.747,0.046,0.721,0.057,0.768,0.094,0.739,0.136,0.75,0.176,1,0.084,0.991
        - 0.001,0.522,0.073,0.456,0.126,0.434,0.174,0.401,0.175,0.354,0.196,0.351,0.202,0.384,0.234,0.365,0.148,0.525,0.254,0.566,0.289,0.561,0.263,0.34,0.277,0.337,0.304,0.517,0.34,0.492,0.323,0.326,0.363,0.304,0.353,0.262,0.409,0.232,0.425,0.157,0.448,0.157,0.456,0.185,0.472,0.21,0.426,0.235,0.426,0.254,0.484,0.235,0.499,0.182,0.513,0.191,0.515,0.232,0.569,0.243,0.593,0.249,0.616,0.26,0.621,0.334,0.644,0.337,0.643,0.273,0.72,0.315,0.729,0.395,0.766,0.423,0.786,0.384,0.946,0.583,1,0.607,1,0,0,0
        - 1,0.751,0.976,0.715,1,0.649
      improve_contrast: false
      lightning_threshold: 0.8
      
  deck:
    detect:
      fps: 7
      min_initialized: 3
      max_disappeared: 50
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -c:a copy
      inputs:
        - path: rtsp://frigate:8554/deck
          input_args: preset-rtsp-restream
          roles: [record, detect, audio]

    live:
      stream_name: deckSub

    mqtt:
      height: 540
      quality: 100

    objects:
      track: [person, face, dog, cat]
    motion:
      mask:
        - 0.123,1,0.208,0.786,0.306,0.665,0.318,0.403,0.336,0.405,0.341,0.657,0.324,1
        - 0.091,0.499,0,0.507,0,0.002,1,0,1,0.442,0.605,0.442,0.615,0.378,0.333,0.195,0.333,0.177,0.46,0.18,0.687,0.324,0.788,0.188,0.858,0.19,0.863,0.094,0.659,0.061,0.329,0.103,0.314,0.144,0.285,0.145,0.278,0.077,0.204,0.088,0.202,0.162,0.178,0.164,0.164,0.079,0.122,0.094,0.117,0.176,0.088,0.182
        - 0.866,0.19,0.863,0.107,0.904,0.113,0.843,0,1,0,1,0.186
        - 0.394,0,0.616,0,0.601,0.04,0.402,0.045
        - 0.561,1,0.56,0.907,0.618,0.845,0.655,0.799,0.689,0.817,0.721,0.897,0.743,1
      lightning_threshold: 0.8
      improve_contrast: false
version: 0.14
```

### Relevant log output

```shell
Type
Info
Timestamp
2024-06-15 13:02:22
Tag
POST
Message
::ffff:xxx.xxx.x.xx - - [15/Jun/2024:13:02:22 -0400] "POST /api/front/plus/1718469284.035437 HTTP/1.1" 200 59 "http://frigate:5000/review" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0" "-"
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

REOLINK RLC-811A

### Any other information that may be helpful

I first noticed this yesterday after I started deleting all images (over 1000) from my Frigate+ account (I wanted to repurpose some of the camera names and a fresh start). I noticed that a bunch of the images I recently sent over from 0.14 Beta 2 are not appearing in Frigate+ correctly. Please see attached images.
![image](https://github.com/blakeblackshear/frigate/assets/46040590/a150b2c0-39c4-4dbc-bf2d-6fff6c92dc37)
![image](https://github.com/blakeblackshear/frigate/assets/46040590/d7740b9e-094c-4ea9-8fe1-0ff4ab2ffcde)

Also, as a sanity check I generated a new API key from my Frigate+ account and restarted my Docker Compose instance. No change.
