### DISCUSSION TITLE
[Config Support]:  the usual tree as a person. Is it a Coral 'problem'?

### DISCUSSION THREAD

**Discussion by ostracizado** [blakeblackshear/frigate#11976] [Config Support]
### Describe the problem you are having

It's a recurrent problem I keep having with a specific tree...
A static object, _aka_ tree, is, at certain periods of the day, identified as a person. 
There no previous movement, or identifications.

The event is not created, but the "person count", "person occupancy" and entity: image.camera_person, are affected.
As automations/notifications/TTS, in Home Assistant, regarding the Frigate's Integration, are affected by those what I want to know is if there's anything I can do to avoid it.

Ex:
![tree](https://github.com/blakeblackshear/frigate/assets/78053830/4af538e8-974d-4a0f-aaae-d7bac51a65f0)

![tree2](https://github.com/blakeblackshear/frigate/assets/78053830/7141133e-70c9-4af8-a874-1b033c58200b)

I did the object mask, at the bottom center of the bounding box. I tried a small and large object mask, I tried various forms (triangle, rectangle, etc.), and so on... But it seems that it does not affect the "person count", "person occupancy" and entity: image.camera_person.

Is there any solution I'm not aware? Or nothing in the config file will affect those?

### Version

0.13.2

### Frigate config file

```yaml
...  
outside_gate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_gate #hd 1920x1080 - stream1 2k 2304x1296
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
    #  stationary:
    #    interval: 10
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      required_zones:
        - cabin_2
        - path
        - gate
      #crop: True
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 2 
      events:
        retain:
          default: 4
          mode: active_objects 
        required_zones:
         - cabin_2
         - path
         - gate
        pre_capture: 3
        post_capture: 10 
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - motorcycle
      filters:
        person:
          mask:
            #- 1563,364,1418,333,1540,136
            - 1605,246,1483,394,1459,209
            - 1670,258,1565,258,1618,396
        dog:
          mask:
            - 1454,299,1585,292,1621,0,1515,0
    motion:
      improve_contrast: true 
      mask:
        - 0,69,616,63,612,0,0,0
        - 201,408,369,252,99,74,0,57
        - 361,109,92,391,54,678,304,772,843,723,937,55
    zones:
      cabin_2:
        coordinates: 0,784,795,784,1064,487,1920,505,1920,1080,0,1080
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 18000
            #min_score: 0.4
            #threshold: 0.5
          person:
            min_area: 10000 
      path:
        coordinates: 1920,498,1088,463,987,426,1106,149,1523,102,1609,114,1920,183,1920,486
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 4000 
          person:
            min_score: 0.4
            max_area: 6000
      gate:
        coordinates: 1366,0,1108,0,999,131,1333,138
        objects:
          - person
          #- dog
          #- cat
          - car
          - motorcycle
        filters:
          person:
            min_score: 0.5
            min_area: 2000
            max_area: 18000
          car:
            min_score: 0.75
```

### Relevant log output

```shell
---
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
