### DISCUSSION TITLE
auth.mode: Extra inputs are not permitted

### DISCUSSION THREAD

**Discussion by rajil** [blakeblackshear/frigate#11991] [General]
I updated from 0.14 beta2 to beta3 and my config no longer works.

I have a separate nginx proxy running which is not on the docker internal network.

Here is my config

```
auth:
  mode: native
  failed_login_rate_limit: "1/second;5/minute;20/hour"
  trusted_proxies:
    - 192.168.1.4/32 # <---- this is upstream proxy
    - 10.10.0.0/16  # <---- this is docker internal network
```

If i remove the auth section then frigate is able to start.
