### DISCUSSION TITLE
[Bug][0.14b3]: Camera video broken on Android Phone

### DISCUSSION THREAD

**Discussion by mderasse** [blakeblackshear/frigate#11997] [Report a Bug]
### Describe the problem you are having

Hello,

I'm giving a try to the 0.14 beta 3 and i'm having an issue that doesn't exist in the 0.13.
The global camera view is working correctly but when i'm opening a specific camera (and only that one, Xiaomi Xiaofang) the video stream is broken and not readable.

That issue is only happening on one of my camera (Xiaomi Xiaofang) and on Google Chrome (Android but i haven't check on iPhone)

![Screenshot_2024-06-16-21-07-53-40_c3a231c25ed346e59462e84656a70e50](https://github.com/blakeblackshear/frigate/assets/374357/c0cef08b-3b31-4194-b5e6-ec1e1a80a4f7)

 

### Steps to reproduce

Open a camera stream from the global view on Google Chrome Android

### Version

0.14b3

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: core-mosquitto
  port: 1883
  user: XXXXXXXXXXXx
  password: XXXXXXXXXXXXXXX

detectors:
  cpu:
    type: cpu

birdseye:
  enabled: false

motion:
  threshold: 40
  lightning_threshold: 0.4
  contour_area: 20

detect:
  stationary:
    interval: 5
    threshold: 10

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    bedroom:
      - rtsp://XXXX:XXXX@192.168.XXX.XXX/unicast
    livingroom:
      - rtsp://XXXX:XXXX@192.168.XXX.XXX:554/stream1
    camera03:
      - rtsp://XXXX:XXXX@192.168.XXX.XXX:554/stream1

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10
    mode: motion

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

cameras:
  bedroom:
    objects:
      track:
        - person
    detect:
      enabled: false
    motion:
      threshold: 40
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.XXX.XXX/unicast
          roles:
            - record
  livingroom:
    enabled: true
    objects:
      track:
        - person
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
    motion:
      threshold: 60
      mask:
        - 304,360,187,360,114,212,328,151,469,299
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.XXX.XXX:554/stream2
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@192.168.XXX.XXX:554/stream1
          roles:
            - record
    onvif:
      host: 192.168.XXX.XXX
      port: XXX
      user: XXXXX
      password: XXXXX
  camera03:
    enabled: true
    objects:
      track:
        - person
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    motion:
      threshold: 60
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.XXX.XXX:554/stream2
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@192.168.XXX.XXX:554/stream1
          roles:
            - record
    onvif:
      host: 192.168.XX.XXX
      port: XXX
      user: XXXXX
      password: XXXX

version: 0.14
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Mixed

### Camera make and model

Xiaomi XiaoFang (hacked)
