### DISCUSSION TITLE
Different resolution streams

### DISCUSSION THREAD

**Discussion by provaprova1** [blakeblackshear/frigate#1200] [Ask A Question]
In the docs I read the following:

>This allows you to use a lower resolution stream for object detection, but create clips from a higher resolution stream, or vice versa. 

So I tried to use 2 different streams for different roles (unfortunately I cannot choose a lower resolution for the higher one)

```
  camera7:
    ffmpeg:
      inputs:
####lower resolution stream 800x600#####
        - path: rtsp://user:pass@192.168.1.207:554/12
          roles:
            - clips
####higher resolution stream 2560x1920#####
        - path: rtsp://user:pass@192.168.1.207:554/11
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
```
But this is the result
![image](https://user-images.githubusercontent.com/31503604/121484371-6f70aa80-c9cf-11eb-9dae-fd1ea85a9222.png)

So I'm assuming that width and height values must correspond to the ones of the Detect stream. Am I right?
