### DISCUSSION TITLE
[Support]: webrtc not working

### DISCUSSION THREAD

**Discussion by alexanderek** [blakeblackshear/frigate#12007] [General Support] [answered]
### Describe the problem you are having

WebRTC not working, MSE functioning correctly

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  restream: True
  mode: continuous

go2rtc:
  streams:
    room:
      - rtsp://admin:pass@IP:554/Streaming/channels/101
      - "ffmpeg:room#audio=aac"
    room_sub:
      - rtsp://admin:pass@IP:554/Streaming/channels/102
    webrtc:
      candidates:
        - IP:8555
        - stun:8555

cameras:
  # Camera ========================== Room =============================================
  room:
    enabled: True
    ffmpeg:
      output_args:
        #record: preset-record-generic-audio-aac
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/room # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/room_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: room

    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 14
          mode: motion
      
    snapshots:
      enabled: True
      retain:
        default: 30

ui:
  live_mode: mse
  strftime_fmt: "%d.%m.%YY %H:%M"
```

### Relevant log output

```shell
go2rtc

2024-06-17 09:27:05.145565977  [INFO] Preparing new go2rtc config...
2024-06-17 09:27:05.669618500  [INFO] Starting go2rtc...
2024-06-17 09:27:05.792781458  09:27:05.792 INF go2rtc version 1.8.4 linux/amd64
2024-06-17 09:27:05.793311301  09:27:05.793 INF [rtsp] listen addr=:8554
2024-06-17 09:27:05.793518716  09:27:05.793 INF [webrtc] listen addr=:8555
2024-06-17 09:27:05.794400698  09:27:05.794 INF [api] listen addr=:1984
2024-06-17 09:27:15.147226851  [INFO] Starting go2rtc healthcheck service...

Frigate

2024-06-17 09:27:05.147128145  [INFO] Preparing Frigate...
2024-06-17 09:27:05.168637300  [INFO] Starting Frigate...
2024-06-17 09:27:06.753040758  [2024-06-17 09:27:06] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-06-17 09:27:09.994681553  [2024-06-17 09:27:09] peewee_migrate.logs            INFO    : Starting migrations
2024-06-17 09:27:09.999319686  [2024-06-17 09:27:09] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-06-17 09:27:10.005492148  [2024-06-17 09:27:10] frigate.app                    INFO    : Recording process started: 227
2024-06-17 09:27:10.008522432  [2024-06-17 09:27:10] frigate.app                    INFO    : go2rtc process pid: 98
2024-06-17 09:27:10.036466214  [2024-06-17 09:27:10] frigate.app                    INFO    : Output process started: 237
2024-06-17 09:27:10.057771814  [2024-06-17 09:27:10] detector.coral                 INFO    : Starting detection process: 236
2024-06-17 09:27:10.058778479  [2024-06-17 09:27:10] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-06-17 09:27:10.095310941  [2024-06-17 09:27:10] frigate.app                    INFO    : Camera processor started for room: 252
2024-06-17 09:27:10.113098566  [2024-06-17 09:27:10] frigate.app                    INFO    : Capture process started for room: 256
2024-06-17 09:27:12.856876247  [2024-06-17 09:27:12] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:Pass!@IP_CAM:554/Streaming/channels/101
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:Pass!@IP_CAM:554/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

HikVision DS-2CV2Q21FD-IW

### Any other information that may be helpful

docker compose:

```
 frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - /mnt/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
    shm_size: "256mb"
    privileged: true
    restart: unless-stopped
```

**Comment by stalakerob** [comment, marked as answer]
The indentation of the webrtc configuration block seems to be wrong. It should align vertically with the the first letter of "streams:"

**Comment by bakedhorse** [comment]
You need to configure go2rtc's webrtc in frigate's config, along with exposing port 8555 in docker compose. If you are doing this over the internet, you also need to port forward port 8555. (I'd highly recommend using a reverse proxy with auth, home assistant, or wait until the next version for exposing frigate to the internet)
[https://docs.frigate.video/configuration/live#webrtc-extra-configuration](https://docs.frigate.video/configuration/live#webrtc-extra-configuration)

**Reply by bakedhorse** [reply]
~~Otherwise, so far your setup looks pretty correct. So I'm unsure what the problem would be.~~
Tired sleepy me forsake me, your indentation of the go2rtc config seems incorrect. Here's a fixed version
```
go2rtc:
  streams:
    room:
      - rtsp://admin:pass@IP:554/Streaming/channels/101
      - "ffmpeg:room#audio=aac"
    room_sub:
      - rtsp://admin:pass@IP:554/Streaming/channels/102
  webrtc:
    candidates:
      - IP:8555
      - stun:8555
```
