### DISCUSSION TITLE
[Bug]: /dev/shm grows rapidly

### DISCUSSION THREAD

**Discussion by wes1993** [blakeblackshear/frigate#12010] [Report a Bug] [answered]
### Describe the problem you are having

Hello, 
I have found a BUG that cause the /dev/shm to grows rapidly and use all the space allocated (12 GB).
![image](https://github.com/blakeblackshear/frigate/assets/52070589/c0fa56f1-7ea2-486f-b993-8c9ca3ef43e3)

![image](https://github.com/blakeblackshear/frigate/assets/52070589/3023304f-a49e-4659-b221-422442a34bf3)

### Steps to reproduce

Restart the container with command 
docker compose -f /home/stefano/Containers/Frigate/docker-compose.yml restart

### Version

Frigate (0.14.0-4e5a6eb)

### Frigate config file

```yaml
mqtt:
  enabled: true #Needed For HomeAssistant Control
  host: 192.168.0.22
  user: mqtt
  password: HiddenByME
database:
  path: /config/Database/frigate.db
#logger:
# Optional: default log level (default: shown below)
#  default: debug
ffmpeg:
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  #hwaccel_args: []
  #  hwaccel_args:
  #    - -hwaccel
  #    - vaapi
  #    - -hwaccel_device
  #    - /dev/dri/renderD128
  #    - -hwaccel_output_format
  #    - yuv420p
  #hwaccel_args: -c:v h264_cuvid
  #hwaccel_args: -c:v hevc_cuvid
  hwaccel_args: preset-nvidia-h265
  output_args:
    #    record: -an
    record: preset-record-generic-audio-aac
#    record: preset-record-generic-audio-copy
#  output_args:
# Optional: output args for record streams (default: shown below)
#    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
# use Nvidia GPU for h264 decoding
#  input_args:
#    - -c:v
#    - h264_cuvid
# try to prevent smearing of the video from packetloss
#    - -rtsp_transport
#    - tcp

# Optional: Audio Events Configuration
# NOTE: Can be overridden at the camera level
audio:
  # Optional: Enable audio events (default: shown below)
  enabled: true
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  #max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  #min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    # Optional: Filters to configure detection.
#  filters:
# Label that matches label in listen config.
#    speech:
# Minimum score that triggers an audio event (default: shown below)
#      threshold: 0.8

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - motorcycle
    - dog
    - cat
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      threshold: 0.88
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
detect:
  enabled: true
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  #path: /config/model_cache/tensorrt/yolov7-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  #  width: 416
  width: 320
  #  height: 416
  height: 320
  # Optional: Label name modifications. These are merged into the standard labelmap.
  labelmap:
    16: dog
# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: motion
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
#record:
# Optional: Enable recording (default: shown below)
# WARNING: If recording is disabled in the config, turning it on via
#          the UI or MQTT later will have no effect.
# WARNING: Frigate does not currently support limiting recordings based
#          on available disk space automatically. If using recordings,
#          you must specify retention settings for a number of days that
#          will fit within the available disk space of your drive or Frigate
#          will crash.
#enabled: false
# Optional: Number of minutes to wait between cleanup runs (default: shown below)
# This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
#  expire_interval: 60
# Optional: Retention settings for recording
#  retain:
# Optional: Number of days to retain recordings regardless of events (default: shown below)
# NOTE: This should be set to 0 and retention should be defined in events section below
#       if you only want to retain recordings of events.
#    days: 2
# Optional: Mode for retention. Available options are: all, motion, and active_objects
#   all - save all recording segments regardless of activity
#   motion - save all recordings segments with any detected motion
#   active_objects - save all recording segments with active/moving objects
# NOTE: this mode only applies when the days setting above is greater than 0
#    mode: all

#record:
#  enabled: False
#  retain:
# Optional: Number of days to retain recordings regardless of events (default: shown below)
# NOTE: This should be set to 0 and retention should be defined in events section below
#       if you only want to retain recordings of events.
#    days: 3
# Optional: Mode for retention. Available options are: all, motion, and active_objects
#   all - save all recording segments regardless of activity
#   motion - save all recordings segments with any detected motion
#   active_objects - save all recording segments with active/moving objects
# NOTE: this mode only applies when the days setting above is greater than 0
#    mode: all
# Optional: Number of minutes to wait between cleanup runs (default: shown below)
# This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
#  expire_interval: 60
#  events:
#    retain:
#      default: 10
#      mode: active_objects
record:
  enabled: true
  retain:
    days: 7
    mode: all
    #mode: active_objects
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 15
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 15
    # Optional: Objects to save recordings for. (default: all tracked objects)
    retain:
      default: 14
      mode: active_objects
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  #clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  #timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  #bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  #crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  #retain:
  # Required: Default retention days (default: shown below)
  #default: 10
  # Optional: Per object retention days
  #objects:
  #person: 15
# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%d.%m.%Y %H:%M:%S'
  # Optional: Color of font
  #color:
  # All Required when color is specified (default: shown below)
  #red: 255
  #green: 255
  #blue: 255
  # Optional: Line thickness of font (default: shown below)
  #thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  #effect: None
go2rtc:
  streams:
    Parcheggio: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=0&stream=0
      #      - ffmpeg:Parcheggio#audio=aac
    Parcheggio_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=0&stream=1
    BagnoStudio: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=1&stream=0
    BagnoStudio_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=1&stream=1
    CameraOspiti: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=2&stream=0
    CameraOspiti_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=2&stream=1
    GiardinoPosteriore: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=3&stream=0
    GiardinoPosteriore_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=3&stream=1
    Ripostiglio: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=4&stream=0
    Ripostiglio_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=4&stream=1
    ParcheggioMoto: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=5&stream=0
    ParcheggioMoto_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=5&stream=1
    Laghetto: # Risoluzione video: 2304x1296
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=6&stream=0
    Laghetto_SD: # Risoluzione video: 640x360
      - bubble://admin:pass@192.168.0.20:80/bubble/live?ch=6&stream=1
    Capanno: # Risoluzione video: 1920x1080
      - rtsp://192.168.0.57:554/realmonitor?channel=0&stream=0.sdp
    Capanno_SD: # Risoluzione video: 640x360
      - rtsp://192.168.0.57:554/realmonitor?channel=0&stream=1.sdp
    Veranda: # Risoluzione video: 1920x1080
      - rtsp://192.168.0.59:554/realmonitor?channel=0&stream=0.sdp
    Veranda_SD: # Risoluzione video: 640x360
      - rtsp://192.168.0.59:554/realmonitor?channel=0&stream=1.sdp
    Studio: # Risoluzione video: 1920x1080
      - rtsp://192.168.0.60:554/realmonitor?channel=0&stream=0.sdp
    Studio_SD: # Risoluzione video: 640x360
      - rtsp://192.168.0.60:554/realmonitor?channel=0&stream=1.sdp
    Cucina: # Risoluzione video: 1280X720
      - rtsp://admin:pass@192.168.0.65:554/Streaming/Channels/101
    Cucina_SD: # Risoluzione video: 768x432
      - rtsp://admin:pass@192.168.0.65:554/Streaming/Channels/102
cameras:
  Parcheggio:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Parcheggio?video=all&audio=all # <--- the name here must match the name of the camera in restream
          #- path: http://127.0.0.1:1984/api/stream.mp4?src=Parcheggio&mp4=all
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Parcheggio_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
    motion:
      mask:
        - 0,0.09,0.164,0.097,0.165,0.045,0.305,0.045,0.307,0,0,0
        - 0.331,0.347,0.638,0.351,0.635,0.905,0.431,0.908,0.431,0.773,0.336,0.755
      threshold: 80
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Vialetto2:
        coordinates: 0.326,0.988,0.363,0.659,0.337,0.252,0.347,0.232,0.347,0.229,0.624,0.238,0.71,0.293,0.836,0.342,0.863,0.09,0.932,0.11,1,0.144,1,0.322,0.969,0.529,0.931,0.713,0.979,0.826,1,1
        inertia: 3
      Vialetto1:
        coordinates: 0.332,0.222,0.332,0,0.52,0,0.57,0,0.746,0,0.839,0.171,0.58,0.145,0.63,0.237
    review:
      alerts:
        required_zones: Vialetto2
      detections:
        required_zones: Vialetto2
    objects:
      filters:
        car:
          mask:
            - 0.344,0.519,0.367,0.036,0.558,0.051,0.626,0.517
            - 0.663,0,0.663,0.147,0.851,0.183,0.876,0
  BagnoStudio:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BagnoStudio?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BagnoStudio_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 1
    motion:
      mask:
        - 0,0.09,0.18,0.089,0.18,0.048,0.305,0.045,0.307,0,0,0
        - 0.708,1,0.671,0.813,0.543,0.673,0.562,0.195,0.536,0.199,0.201,0.197,0.202,0,1,0,1,1
      threshold: 60
      contour_area: 20
      improve_contrast: 'true'
    objects:
      filters:
        person:
          mask: 559,261,533,109
  CameraOspiti:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CameraOspiti?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CameraOspiti_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 2
    motion:
      mask:
        - 0,0.09,0.196,0.085,0.196,0.05,0.305,0.045,0.307,0,0,0
        - 0,0.482,0.232,0.492,0.217,0.127,0.273,0.207,0.423,0.205,0.469,0.102,0.469,0,0,0
      threshold: 70
      contour_area: 10
      improve_contrast: 'true'
  GiardinoPosteriore:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/GiardinoPosteriore?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/GiardinoPosteriore_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 3
    motion:
      mask:
        - 0,0.09,0.29,0.087,0.291,0.045,0.305,0.045,0.307,0,0,0
        - 0,0.742,0.255,0.745,0.322,0.728,0.353,0.683,0.367,0.651,0.43,0.589,0.466,0.519,0.479,0.441,0.421,0.306,0.428,0.217,0.433,0.175,0.42,0.098,0.395,0,0.181,0,0,0,0,0.104,0,0.482,0.143,0.44,0.181,0.317,0.113,0.532,0,0.634
        - 0.652,0.76,0.642,0.606,0.647,0.509,0.666,0.441,0.746,0.416,0.816,0.474,0.837,0.516,0.852,0.574,0.856,0.663,0.83,0.736,0.752,0.793,0.684,0.801
        - 0.454,0.277,0.491,0.277,0.5,0.22,0.465,0.174,0.438,0.192,0.432,0.265
        - 0.648,0.287,0.623,0.275,0.621,0.22,0.629,0.162,0.647,0.132,0.67,0.104,0.698,0.092,0.853,0.115,0.869,0.022,0.957,0,1,0.035,1,0.454,0.788,0.376,0.669,0.302
        - 0.435,0.045,0.694,0.088,0.623,0.187,0.438,0.164
        - 0.016,0.856,0.027,0.705,0.1,0.684,0.1,1,0,1
      threshold: 50
      contour_area: 20
      improve_contrast: 'true'
    objects:
      filters:
        motorcycle:
          mask: 0.43,1,0.956,0.703,0.911,0.638,0.9,0.583,1,0.509,1,1
        car:
          mask: 0.423,1,0.948,0.698,0.91,0.629,0.903,0.581,1,0.513,1,1
  Ripostiglio:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Ripostiglio?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Ripostiglio_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 4
    motion:
      mask:
        - 0,0.09,0.184,0.085,0.183,0.043,0.305,0.045,0.307,0,0,0
        - 0.388,1,0.412,0.832,0.438,0.636,0.438,0.526,0.412,0.342,0.4,0.232,0.353,0.227,0.377,0.115,0.388,0.085,0.409,0,0.359,0,0,0,0,1
        - 0.559,0,0.735,0,0.721,0.2,0.555,0.195
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
  ParcheggioMoto:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ParcheggioMoto?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/ParcheggioMoto_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 5
    motion:
      mask:
        - 0,0.09,0.164,0.097,0.165,0.045,0.305,0.045,0.307,0,0,0
        - 0.468,1,0.468,0.344,0.551,0.073,0.75,0.003,1,0,1,1
      threshold: 80
      contour_area: 20
      improve_contrast: 'true'
    objects:
      filters:
        motorcycle:
          mask: 0.25,1,0.252,0.234,0.467,0.226,0.468,1
        car:
          mask: 0.459,0.05,0.608,0.083,0.611,0.215,0.446,0.209
  Laghetto:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Laghetto?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Laghetto_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 6
    motion:
      mask:
        - 0,0.09,0.136,0.089,0.134,0.047,0.305,0.045,0.307,0,0,0
        - 0.249,0.229,0.353,0.285,0.403,0.245,0.416,0.205,0.444,0.212,0.52,0.232,0.562,0.105,0.55,0.052,0.463,0,0.218,0
        - 0.688,0.344,0.707,0.165,0.771,0.187,0.825,0.063,0.852,0.01,0.98,0,0.992,0.047,1,0.145,0.998,0.394,0.861,0.342
      threshold: 40
      contour_area: 25
      improve_contrast: 'true'
    zones:
      Prato:
        coordinates: 0.255,0.261,0.263,0.247,0.408,0.245,0.418,0.215,0.547,0.159,0.562,0.12,0.623,0.13,0.701,0.182,0.678,0.339,0.847,0.369,1,0.461,1,0.578,0.892,0.629,0.638,0.287
        inertia: 3
      Vialetto:
        coordinates: 0.004,0.098,0.139,0.097,0.14,0.057,0.219,0.053,0.265,0.234,0.088,0.656,0.061,0.472,0.004,0.466
        objects:
          - car
      Piazzale:
        coordinates: 0.089,0.679,0.251,0.263,0.636,0.292,0.92,0.673,0.121,0.718,0.086,0.735
        inertia: 3
    review:
      alerts:
        required_zones: Prato
      detections:
        required_zones: Prato
    objects:
      mask:
        - 0,0.888,0.128,0.88,0.15,0.765,0.085,0.74,0.075,0.594,0.057,0.482,0.007,0.486
        - 0.26,1,0.267,0.684,0.813,0.694,0.823,1
  Capanno:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Capanno?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Capanno_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-nvidia-h264
    snapshots: # <----- Enable snapshots
      timestamp: true
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 7
  Veranda:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Veranda?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Veranda_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-nvidia-h264
      #    detect:
      #      enabled: False # <---- disable detection until you have a working camera feed
    snapshots: # <----- Enable snapshots
      timestamp: true
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 8
  Studio:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Studio?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Studio_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-nvidia-h264
      #    detect:
      #      enabled: False # <---- disable detection until you have a working camera feed
    snapshots: # <----- Enable snapshots
      timestamp: true
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 9
    objects:
      filters:
        car:
          mask: 0.509,0.203,0.514,0.015,0.66,0.038,0.652,0.242
  Cucina:
    enabled: true # <------ True by default
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cucina?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Cucina_SD?video=all&audio=all # <--- the name here must match the name of the camera in restream
          roles:
            - detect
            - audio
      hwaccel_args: preset-nvidia-h264
      #    detect:
      #      enabled: False # <---- disable detection until you have a working camera feed
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 10
camera_groups:
  Interne:
    order: 1
    icon: LuWebcam
    cameras:
      - Veranda
      - Studio
      - Cucina
version: 0.14
```

### Relevant log output

```shell
2024-06-17 10:24:21.844145441  [INFO] Preparing Frigate...
2024-06-17 10:24:21.869627860  [INFO] Starting Frigate...
2024-06-17 10:24:23.978553624  [2024-06-17 10:24:23] frigate.app                    INFO    : Starting Frigate (0.14.0-4e5a6eb)
2024-06-17 10:24:23.979157879  [2024-06-17 10:24:23] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-06-17 10:24:24.094822717  [2024-06-17 10:24:24] frigate.util.config            INFO    : frigate config does not need migration...
2024-06-17 10:24:42.985207905  [2024-06-17 10:24:42] peewee_migrate.logs            INFO    : Starting migrations
2024-06-17 10:24:42.985279181  [2024-06-17 10:24:42] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-06-17 10:24:43.017669123  [2024-06-17 10:24:43] frigate.app                    INFO    : Recording process started: 462
2024-06-17 10:24:43.037000838  [2024-06-17 10:24:43] frigate.app                    INFO    : Recording process started: 466
2024-06-17 10:24:43.044144148  [2024-06-17 10:24:43] frigate.app                    INFO    : go2rtc process pid: 107
2024-06-17 10:24:43.110379790  [2024-06-17 10:24:43] frigate.app                    INFO    : Output process started: 517
2024-06-17 10:24:43.141578901  Process output_processor:
2024-06-17 10:24:43.149103513  Traceback (most recent call last):
2024-06-17 10:24:43.149133371    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-06-17 10:24:43.149134939      self.run()
2024-06-17 10:24:43.149139486    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-06-17 10:24:43.149141752      self._target(*self._args, **self._kwargs)
2024-06-17 10:24:43.149149612    File "/opt/frigate/frigate/output/output.py", line 68, in output_frames
2024-06-17 10:24:43.149150929      move_preview_frames("cache")
2024-06-17 10:24:43.149152190    File "/opt/frigate/frigate/output/output.py", line 183, in move_preview_frames
2024-06-17 10:24:43.149153233      shutil.move(preview_holdover, preview_cache)
2024-06-17 10:24:43.149154307    File "/usr/lib/python3.9/shutil.py", line 804, in move
2024-06-17 10:24:43.149172726      raise Error("Destination path '%s' already exists" % real_dst)
2024-06-17 10:24:43.149181828  shutil.Error: Destination path '/tmp/cache/preview_frames/preview_restart_cache' already exists
2024-06-17 10:24:43.161671522  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Parcheggio: 564
2024-06-17 10:24:43.179649771  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for BagnoStudio: 573
2024-06-17 10:24:43.185640468  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for CameraOspiti: 580
2024-06-17 10:24:43.200110576  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for GiardinoPosteriore: 602
2024-06-17 10:24:43.214535974  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Ripostiglio: 611
2024-06-17 10:24:43.230343750  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for ParcheggioMoto: 635
2024-06-17 10:24:43.244787264  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Laghetto: 649
2024-06-17 10:24:43.258607164  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Capanno: 659
2024-06-17 10:24:43.270289761  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Veranda: 680
2024-06-17 10:24:43.283618182  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Studio: 696
2024-06-17 10:24:43.287074035  [2024-06-17 10:24:43] detector.tensorrt              INFO    : Starting detection process: 507
2024-06-17 10:24:43.300018309  [2024-06-17 10:24:43] frigate.app                    INFO    : Camera processor started for Cucina: 709
2024-06-17 10:24:43.316374873  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Parcheggio: 717
2024-06-17 10:24:43.331947659  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for BagnoStudio: 722
2024-06-17 10:24:43.343042550  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for CameraOspiti: 726
2024-06-17 10:24:43.368749998  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for GiardinoPosteriore: 733
2024-06-17 10:24:43.401780099  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Ripostiglio: 739
2024-06-17 10:24:43.404773893  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for ParcheggioMoto: 745
2024-06-17 10:24:43.417245373  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Laghetto: 750
2024-06-17 10:24:43.462824593  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Capanno: 759
2024-06-17 10:24:43.462830808  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Veranda: 763
2024-06-17 10:24:43.518818779  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Studio: 773
2024-06-17 10:24:43.518825354  [2024-06-17 10:24:43] frigate.app                    INFO    : Capture process started for Cucina: 779
2024-06-17 10:24:43.519387936  [2024-06-17 10:24:43] frigate.app                    INFO    : Audio process started: 788
2024-06-17 10:24:43.604250930  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 73 MiB
2024-06-17 10:24:43.785173953  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt WARNING : Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
2024-06-17 10:24:43.900039171  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 229, GPU 208 (MiB)
2024-06-17 10:24:43.948557513  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +16, now: CPU 231, GPU 228 (MiB)
2024-06-17 10:24:43.967172965  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +72, now: CPU 0, GPU 72 (MiB)
2024-06-17 10:24:43.981601654  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 158, GPU 220 (MiB)
2024-06-17 10:24:43.987311150  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 158, GPU 228 (MiB)
2024-06-17 10:24:43.996415650  [2024-06-17 10:24:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +16, now: CPU 0, GPU 88 (MiB)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Misecu

### Any other information that may be helpful

Seems that restart command won't clear the directory /tmp/cache/preview_frames/preview_restart_cache, but i'm not sure if /tmp/cache/preview_frames/preview_restart_cache is related with /dev/shm
