### DISCUSSION TITLE
[Bug]: Snapshot endpoint and encoded camera snapshots no longer return `*.jpg`, but instead `*.webp`

### DISCUSSION THREAD

**Discussion by aav7fl** [blakeblackshear/frigate#12027] [Report a Bug] [answered]
### Describe the problem you are having

Starting with the 0.14.0 Beta releases, I've noticed that `webp` has replaced any `jpg` images in the app.

I use the [Home Assistant Camera Proxy](https://www.home-assistant.io/integrations/proxy/) from cameras re-streamed from Frigate to crop and resize thumbnails for my phone notifications. 

With the latest Frigate beta releases, I can no longer crop the snapshots/cameras. Home Assistant gives me the following warning: `Image is of unsupported type: WEBP`.

The Camera Proxy in HA only supports JPEG and PNG.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/proxy/camera.py#L88

I can understand that the `camera.<CAMERA_NAME>` inside of Home Assistant might not have a jpg image, but the Frigate snapshot API endpoint is also returning a `.webp` file at the `.jpg` url endpoint.

Ref: https://deploy-preview-11419--frigate-docs.netlify.app/integrations/api/#get-apieventsidsnapshotjpg

http://FRIGATE_IP:5000/api/CAMERA_NAME/latest.jpg

When you try to save the image above, it's downloaded as `latest.webp`

1. The snapshot API no longer returns a `*.jpg` formatted image. 
2. When I run `camera.snapshot` in Home Assistant, Frigate's camera returns a `*.webp` encoded file. This is incompatible with Home Assistant's Camera Proxy.

Is there a good way around this issue? Like can I add an additional re-stream in Frigate to make it compatible with Home Assistant's Camera Proxy?

## Camera API JPG bug

1. Visit any snapshot endpoint that should be returning a `.jpg` image.
2. http://FRIGATE_IP:5000/api/CAMERA_NAME/latest.jpg
3. Try to save the image file. I expect it to be a jpg.
4. It will be a webp.

## Camera Proxy Bug

1. In home assistant, set up the frigate integration.,
2. Set up a camera proxy that crops the frigate camera.
3. Try to view or take a snapshot of the proxy camera. There should be a warning message in the Home Assistant logs saying that WEBP is not supported.

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  host: mqtt
  port: 8883
  topic_prefix: frigate
  user: USERNAME
  password: SECRET_PASSWORD

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: REMOVED

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

review:
  alerts:
    labels:
      - cat
      - person

snapshots:
  enabled: true

go2rtc:
  streams:
    driveway:
      - rtsp://USERNAME:SECRET_PASSWORD@192.168.95.53:554/cam/realmonitor?channel=1&subtype=02
      - ffmpeg:driveway#audio=aac

timestamp_style:
  position: bl
  effect: shadow

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .85
      threshold: .80
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .85
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    deer:
      min_score: .80
      threshold: .80

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      #fps: 2
    motion:
      mask:
        - 0.107,0.279,0.284,0.178,0.391,0.142,0.657,0.101,0.705,0.098,0.768,0.103,0.836,0.115,0.882,0,0,0,0,0.54,0.13,0.455
        - 0.129,0.943,0.132,1,0.223,1,0.226,0.942
        - 0.641,0.373,0.917,0.625,0.947,0.481,0.977,0.289,0.855,0.184,0.823,0.241,0.787,0.274
        - 0,1,0.284,1,0.243,0.826,0.187,0.657,0.15,0.648,0,0.673
    mqtt:
      quality: 100
    objects:
      track:
        - person
        - cat
        - deer
      filters:
        person:
          min_area: 5000
          max_area: 3686400
        cat:
          min_area: 5000
          max_area: 3686400
        car: {}
        deer: {}
        license_plate: {}
        fedex: {}
      mask:
        - 0.002,0.549,0.137,0.459,0.111,0.285,0.281,0.187,0.393,0.147,0.704,0.104,0.834,0.124,0.878,0.128,0.891,0.003,0,0
        - 0.666,0.375,0.836,0.25,0.855,0.204,0.971,0.299,0.928,0.597


ffmpeg:
  hwaccel_args: preset-vaapi
version: 0.14
```

### Relevant log output

```shell
Logger: homeassistant.components.proxy.camera
Source: components/proxy/camera.py:89
integration: proxy (documentation, issues)
First occurred: 1:36:17 PM (4 occurrences)
Last logged: 1:46:50 PM

Image is of unsupported type: WEBP
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2669EW-AI

### Any other information that may be helpful

My config may have other bugs or things that can be cleaned up. I've been running the same config file and updating it since [`0.1.2`](https://github.com/blakeblackshear/frigate/releases/tag/0.1.2) back in mid-2019. I'm open to any suggestions! 

Other related discussion on how webp is taking over in the new UI rewrite: https://github.com/blakeblackshear/frigate/issues/6303
