### DISCUSSION TITLE
[HW Accel Support]: Settings for Ivy Bridge Intel HD 2500 VAAPI

### DISCUSSION THREAD

**Discussion by danieldietsch** [blakeblackshear/frigate#12023] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I am trying to use the very old hardware acceleration of my Intel i5-3550. It has a Gen7 GPU that does not support H265, hence ``preset-vaapi`` fails for cameras that provide a H265 stream. But it is so old that ``preset-intel-qsv-h264`` is not yet supported. Is there a way I can use it anyways?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: ... # preset-intel-qsv-h264, preset-vaapi do not work

mqtt:
  ...

go2rtc:
  streams:
    01:
      - rtsp://XXX/live/ch0



birdseye:
  enabled: true
  mode: continuous

cameras:
  01:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/01 
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    motion:
      mask:
        - 562,1514,1525,1551,1537,719,608,687
    audio:
      enabled: True
audio:
  enabled: True
  listen:
    - ...
detect:
  enabled: false
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 365
      mode: all
snapshots:
  enabled: true
  retain:
    default: 365
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ...
    ports:
      - "5000:5000" # webinterface
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - LIBVA_DRIVER_NAME=i965
    cap_add:
      - CAP_PERFMON
```

### Relevant log output

```shell
# vainfo 
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:Inteli965driverforIntel(R)IvybridgeDesktop-2.4.1nvainfo:SupportedprofileandentrypointsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264StereoHigh:tVAEntrypointVLDnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileNone:tVAEntrypointVideoProcnVAProfileJPEGBaseline:tVAEntrypointVLD"}

# log
Ffmpeg process crashed unexpectedly for 01.
frigate  | 2024-06-17 15:14:53.530592035  [2024-06-17 15:14:53] watchdog.01             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-06-17 15:14:53.530760356  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : [segment @ 0x558a74fbd1c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | 2024-06-17 15:14:53.531033080  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : [hevc @ 0x558a74fec9c0] No support for codec hevc profile 1.
frigate  | 2024-06-17 15:14:53.531053602  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : [hevc @ 0x558a74fec9c0] Failed setup for format vaapi: hwaccel initialisation returned error.
frigate  | 2024-06-17 15:14:53.531404767  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
frigate  | 2024-06-17 15:14:53.531410492  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : Error reinitializing filters!
frigate  | 2024-06-17 15:14:53.531485476  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : Failed to inject frame into filter network: Function not implemented
frigate  | 2024-06-17 15:14:53.531585251  [2024-06-17 15:14:53] ffmpeg.01.detect        ERROR   : Error while processing the decoded data for stream #0:0
frigate  | 2024-06-17 15:14:55.093864393  [2024-06-17 15:14:55] frigate.video           ERROR   : 01: Unable to read frames from ffmpeg process.
frigate  | 2024-06-17 15:14:55.093939885  [2024-06-17 15:14:55] frigate.video           ERROR   : 01: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1620,"width":2880},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Cinnado 5MP
