### DISCUSSION TITLE
[0.14.0 Beta 3] Can’t install Frigate0.14

### DISCUSSION THREAD

**Discussion by ccie11827** [blakeblackshear/frigate#12021] [Report a Bug] [answered]
### Describe the problem you are having

I tried to install Frigate 0.14 in my LXC/Ubuntu/Docker/Portainer environment with the same configuration of a previously well running 0.13.2 version.
The Container doesn’t start anymore due to a repeating error (See log)
It seems to be related to IPv6 which I do not use and not plan to use in my network. 

### Steps to reproduce

updated docker compose with new release "ghcr.io/blakeblackshear/frigate:0.14.0-beta3"
no other changes

### Version

0.14 beta 3

### Frigate config file

```yaml
[Docker compose]

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    # image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3
    shm_size: "256mb"
    devices:
       - /dev/dri/renderD128
       - /dev/bus/usb:/dev/bus/usb
    cap_add:
      - CAP_PERFMON
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/:/config/
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - TZ="Europe/Vienna"
      - FRIGATE_RTSP_PASSWORD="xxxxx"
      - FRIGATE_RTSP_USERNAME="xxxxx"
```

### Relevant log output

```shell
2024-06-17 14:07:06.313097434 [INFO] Starting NGINX...
2024-06-17 14:07:06.352386040 2024/06/17 12:07:06 [emerg] 1224184#1224184: socket() [::]:5000 failed (97: Address family not supported by protocol)
2024-06-17 14:07:06.352389573 nginx: [emerg] socket() [::]:5000 failed (97: Address family not supported by protocol)
2024-06-17 14:07:06.355822651 [INFO] Service NGINX exited with code 1 (by signal 0)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

not relevant for this issue
