### DISCUSSION TITLE
Notification ok for Telegram - KO for mobile app

### DISCUSSION THREAD

**Discussion by provaprova1** [blakeblackshear/frigate#1202] [Ask A Question]
Hi I'm having troubles in enabling event notifications on mobile app.
The telegram notification works well, while the mobile app only shows the message without any picture

This is the automation
```
alias: Notify of events
trigger:
  platform: mqtt
  topic: frigate/events
action:
  - service: notify.mobile_app_realme_6_pro
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: 'https://ccab4aaf-frigate:5000/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
        tag: '{{trigger.payload_json["after"]["id"]}}'
```

and this is my configuration file

```
detectors:
  cpu1:
    type: cpu
mqtt:
  host: core-mosquitto
  port: 1883
  user: user
  password: password
  stats_interval: 60
    
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.201:554/12
          roles:
            - clips
            - detect
    width: 800
    height: 600
    fps: 5
    motion:
      mask: 267,0,270,89,456,98,486,0
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
```
