### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by brunopiras** [blakeblackshear/frigate#12035] [Config Support]
### Describe the problem you are having

Upgrade from stable to 0.14beta 3, nginx it's configured only to ipv6 listen.

### Version

0.14beta 3

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.2:5000/api/config/schema.json
mqtt:
  host: 192.168.1.2
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

tls:
  # Optional: Enable TLS for port 8080 (default: shown below)
  enabled: false
# Optional: Authentication configuration
auth:
  # Optional: Enable authentication
  enabled: false
timestamp_style:
  effect: shadow
detectors:
  coral:
    type: edgetpu
    device: usb
#  deepstack:
#    api_url: http://192.168.1.2:8002/v1/vision/detection
#    type: deepstack
#    api_timeout: 0.1 # seconds
objects:
  track:
    - person
    - dog
    - car
    - umbrella
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
  #  yuv420p
  #hwaccel_args: preset-vaapi
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -an
go2rtc:
  streams:
#    tablet:
#      - http://192.168.1.174:2323/?cmd=getCamshot&password=1234
#      - "ffmpeg:http://127.0.0.1:1984/api/stream.mjpeg?src=tablet#video=h264"

    carducci:
      - rtsp://admin:xxxxxxx@192.168.1.26:554/stream1
    carducci_sub:
      - rtsp://admin:xxxxx@192.168.1.26:554/stream2
    citofono:
      - rtsp://192.168.1.5/user=admin&password=xxxxxxx&channel=1&stream=0.sdp?real_stream
    citofono_sub:
      - rtsp://192.168.1.5/user=admin&password=xxxxxxx&channel=1&stream=1.sdp?real_stream
    cortile:
      - rtsp://admin:xxxx@192.168.1.20:554/stream1
    cortile_sub:
      - rtsp://admin:xxxx@192.168.1.20:554/stream2
    garage:
      - rtsp://admin:xxxx@192.168.1.22:554/stream1
    garage_sub:
      - rtsp://admin:xxxxx@192.168.1.22:554/stream2
    scale:
      - rtsp://admin:xxxx@192.168.1.25:554/stream1
    scale_sub:
      - rtsp://admin:xxxxx@192.168.1.25:554/stream2
    cucina:
      - rtsp://admin:xxxxx@192.168.1.24:554/stream1
    cucina_sub:
      - rtsp://admin:xxxxxx@192.168.1.24:554/stream2
    soggiorno:
      - rtsp://admin:xxxxx@192.168.1.21:554/stream1
    soggiorno_sub:
      - rtsp://admin:xxxxxx@192.168.1.21:554/stream2
  webrtc:
    candidates:
      - 192.168.1.2:8555
      - stun:8555
cameras:
####################

###CITOFONO###
  citofono:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/citofono?video=h264
          input_args: preset-rtsp-restream
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/citofono_sub?mp4
          input_args: preset-rtsp-restream
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi
          roles:
            - detect
      input_args:
        - -rtsp_transport
        - tcp
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      enabled: true
      width: 720
      height: 480
      fps: 10
      stationary:
        interval: 40
        threshold: 80
        max_frames:
          default: 4000
          objects:
            person: 800
    objects:
      track:
        - person
      filters:
        person:
          min_area: 60000
          min_ratio: 0.4
          max_ratio: 0.95
          min_score: 0.65
          threshold: 0.70
          mask:
            - 244,121,1031,118,1044,720,1280,720,1280,0,0,0,0,720,238,720
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 3
        post_capture: 2
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 600
      retain:
        default: 30
      required_zones:
        - faces
    motion:
      # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
      #           needs to recalibrate. (default: shown below)
      # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
      # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
      # a doorbell camera.
      lightning_threshold: 0.6
      threshold: 73
      contour_area: 35
      mask: 0.005,0.083,0.315,0.079,0.314,0.031,0.006,0.032
      mqtt_off_delay: 30
      improve_contrast: true
      frame_height: 600
    mqtt:
      required_zones:
        - faces
      timestamp: false
      bounding_box: false
      crop: true
      height: 600
    zones:
      faces:
        inertia: 3
        coordinates: 0.146,1,0.789,1,0.778,0.169,0.145,0.165
        objects: person
        filters:
          person:
            threshold: 0.70
            min_area: 60000
            min_score: 0.65
    # live:
    #   stream_name: citofono_sub
    # webui_url: http://192.168.1.5
    ui:
      order: 1
    review:
      alerts:
        required_zones: faces
      detections:
        required_zones: faces

############################

  cortile:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cortile?video=h264
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            yuv420p
        - path: rtsp://127.0.0.1:8554/cortile_sub?mp4
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            yuv420p
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
      stationary:
        interval: 3
        threshold: 40
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.6
          min_area: 20000
          #max_area: 50000
          min_score: 0.55
        dog:
          threshold: 0.78
          min_area: 3000
          #max_area: 18000
          min_score: 0.45
    record:
      sync_recordings: true
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 2
        post_capture: 3
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 500
      retain:
        default: 30
    motion:
      threshold: 25
      contour_area: 30

      mqtt_off_delay: 30
      improve_contrast: false
      frame_height: 100
    # live:
    #   stream_name: cortile_sub
    # webui_url: http://192.168.1.20
      mask: 
        0.003,0.567,0.16,0.526,0.28,0.444,0.308,0.464,0.293,0.525,0.308,0.588,0.384,0.596,0.3,0.66,0.274,0.753,0.275,0.83,0.314,0.837,0.362,0.782,0.375,0.804,0.376,0.879,0.38,0.933,0.423,0.944,0.432,0.893,0.466,0.898,0.492,0.872,0.492,0.821,0.512,0.821,0.524,0.846,0.541,0.879,0.565,0.9,0.595,0.868,0.593,0.834,0.574,0.777,0.551,0.728,0.559,0.712,0.585,0.722,0.607,0.762,0.634,0.782,0.668,0.753,0.676,0.71,0.704,0.689,0.723,0.668,0.718,0.626,0.707,0.582,0.718,0.557,0.74,0.512,0.732,0.473,0.683,0.447,0.641,0.441,0.66,0.408,0.707,0.392,0.703,0.342,0.676,0.332,0.638,0.339,0.655,0.272,0.509,0.197,0.411,0.207,0.445,0.17,0.463,0.117,0.481,0.076,0.491,0.035,0.497,0,0.499,0,0.499,-0.001,0.006,0.002
    ui:
      order: 7
####################
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=h265
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi #yuv420p
        - path: rtsp://127.0.0.1:8554/garage_sub?mp4
          input_args: preset-rtsp-restream
          roles:
            - record
          #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
          #  vaapi
      input_args:
        - -rtsp_transport
        - tcp
        #- -c:v
        #- hevc_cuvid
        #
        # copied from genral options
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 3
        threshold: 40
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.78
          min_area: 20000
          #max_area: 50000
          min_score: 0.55
        dog:
          threshold: 0.78
          min_area: 2500
          #max_area: 10000
          min_score: 0.45
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 2
        post_capture: 3
        retain:
          default: 30
          mode: active_objects
        #required_zones:
        #  - Cucina_Ingresso
        #  - Cucina_Interno
    motion:
      mask:
        - 0,674,317,671,323,636,0,636
      lightning_threshold: 0.6
      threshold: 73
      contour_area: 35
      mqtt_off_delay: 30
      improve_contrast: false
      frame_height: 600
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 500
      #required_zones:
      #  - Cucina_Ingresso
      #  - Cucina_Interno
      retain:
        default: 30
    #mqtt:
    #  required_zones:
    #    - Cucina_Ingresso
    #    - Cucina_Interno
    #zones:
    #  Cucina_Ingresso:
    #    coordinates: 363,786,797,474,716,128,538,23,143,189
    #    objects:
    #      - person
    #      - dog
    #    filters:
    #        dog:
    #          threshold: 0.8   
    #        person:
    #          min_area: 5000
    #          max_area: 100000
    #          threshold: 0.8
    # live:
    #   stream_name: garage_sub
    webui_url: http://192.168.1.22
    ui:
      order: 5
#####################
  cucina:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cucina?video=h265
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi #yuv420p
        - path: rtsp://127.0.0.1:8554/cucina_sub?mp4
          input_args: preset-rtsp-restream
          roles:
            - record
          #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
          #  vaapi
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 3
        threshold: 40
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.78
          min_area: 20000
          #max_area: 60000
          min_score: 0.55
        dog:
          threshold: 0.78
          min_area: 4000
          #max_area: 15000
          min_score: 0.45
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 500
      required_zones:
        - Cucina_Ingresso
        - Cucina_Interno
      retain:
        default: 30
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    zones:
      Cucina_Ingresso:
        inertia: 3
        coordinates: 241,511,530,317,379,0,94,129
        objects:
          - person
          - dog
        filters:
          person:
            threshold: 0.6
            min_area: 26000
            #max_area: 60000
            min_score: 0.55
          dog:
            threshold: 0.78
            min_area: 3000
            #max_area: 15000
            min_score: 0.45
      Cucina_Interno:
        inertia: 3
        coordinates: 1204,720,1280,0,557,41,604,312,222,576,441,720
        objects:
          - person
          - dog
        filters:
          person:
            threshold: 0.78
            min_area: 26000
            #max_area: 60000
            min_score: 0.55
          dog:
            threshold: 0.78
            min_area: 3000
            #max_area: 15000
            min_score: 0.45
    motion:
      mask:
        - 0,673,322,671,319,630,0,630
    # live:
    #   stream_name: cucina_sub
    webui_url: http://192.168.1.24
    ui:
      order: 2
    review:
      alerts:
        required_zones:
          - Cucina_Ingresso
          - Cucina_Interno
 ################
  scale:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/scale?video=h265
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi
        - path: rtsp://127.0.0.1:8554/scale_sub?mp4
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.78
          min_area: 15000
          #max_area: 60000
          min_score: 0.55
        dog:
          threshold: 0.68
          min_area: 3000
          #max_area: 15000
          min_score: 0.45
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 600
      required_zones:
        - salita
    motion:
      # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
      #           needs to recalibrate. (default: shown below)
      # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
      # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
      # a doorbell camera.
      lightning_threshold: 0.6
      threshold: 73
      contour_area: 35
      mqtt_off_delay: 15
      improve_contrast: true
      frame_height: 600
      #mask:
      #  - 0,671,326,670,330,642,0,640
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 600
      required_zones:
        - salita
    zones:
      salita:
        inertia: 3
        coordinates: 
          669,108,631,245,414,161,354,323,171,112,0,162,0,338,219,720,472,567,548,720,1019,720,1280,287
    # live:
    #   stream_name: scale_sub
    webui_url: http://192.168.1.25
    ui:
      order: 4
#################
    review:
      alerts:
        required_zones:
          - salita
  soggiorno:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/soggiorno?video=h265
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi #yuv420p
        - path: rtsp://127.0.0.1:8554/soggiorno_sub?mp4
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.78
          min_area: 20000
          #max_area: 70000
          min_score: 0.50
        dog:
          threshold: 0.78
          min_area: 4000
          #max_area: 30000
          min_score: 0.45
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 500
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    # live:
    #   stream_name: soggiorno_sub
    webui_url: http://192.168.1.21
    ui:
      order: 8
###############
  carducci:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carducci?video=h265
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi #yuv420p
        - path: rtsp://127.0.0.1:8554/carducci_sub?mp4
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
            vaapi
      input_args:
        - -rtsp_transport
        - tcp
        #- -c:v
        #- hevc_cuvid
        #
        # copied from genral options
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    # live:
    #   stream_name: carducci_sub
    ui:
      order: 3
    webui_url: http://192.168.1.26
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      #- umbrella
        - dog
      #- bicycle
      filters:
        person:
          threshold: 0.78
          min_area: 15000
          #max_area: 50000
          min_score: 0.55
        dog:
          threshold: 0.78
          min_area: 4000
          #max_area: 18000
          min_score: 0.45
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 500
      required_zones:
        - Interno_Carducci
        - Esterno_Carducci
    mqtt:
      required_zones:
        - Interno_Carducci
        - Esterno_Carducci
    zones:
      Interno_Carducci:
        inertia: 3
        coordinates: 
          948,444,650,505,579,151,146,243,0,494,0,720,1280,720,1280,501,1280,247,1280,144,1208,98,709,133,869,228
        objects:
          - person
        #- umbrella
          - dog
        filters:
          person:
            threshold: 0.78
            min_area: 15000
            #max_area: 50000
            min_score: 0.55
          dog:
            threshold: 0.78
            min_area: 4000
            #max_area: 18000
            min_score: 0.45
      Esterno_Carducci:
        inertia: 3
        coordinates: 0,306,1171,52,1280,156,1280,0,0,0
        objects:
          - person
        #- umbrella
        #- bicycle
        filters:
          person:
            threshold: 0.78
            min_area: 15000
            #max_area: 50000
            min_score: 0.55
          dog:
            threshold: 0.78
            min_area: 4000
            #max_area: 18000
            min_score: 0.45
    motion:
      lightning_threshold: 0.6
      threshold: 25
      contour_area: 30
      mask:
        - 0,483,145,252,1153,58,1280,156,1280,0,0,0
        - 731,153,885,240,902,461,725,490,664,465,584,348,585,276
        - 0,669,332,668,335,641,0,637
      mqtt_off_delay: 30
      improve_contrast: false
      frame_height: 500
    best_image_timeout: 60
    review:
      alerts:
        required_zones:
          - Interno_Carducci
          - Esterno_Carducci
birdseye:
  enabled: true
  restream: false
  mode: continuous
  width: 2560
  height: 1440
  quality: 1
  layout:
    scaling_factor: 4.0
live:
  height: 1080
# ui:
#   live_mode: mse
#   timezone: Europe/Rome
#   use_experimental: true
#   time_format: browser
#   date_style: short
#   time_style: medium
#   #strftime_fmt: '%d/%m/%Y %H:%M'
telemetry:
  version_check: true
  network_interfaces:
    - enp1s0
    - enp2s0
    - enp3s0
  stats:
    network_bandwidth: true

version: 0.14
camera_groups:
  Esterno:
    order: 1
    icon: LuZap
    cameras:
      - carducci
      - citofono
      - cortile
      - scale
  Interno:
    order: 2
    icon: LuActivity
    cameras:
      - birdseye
      - cucina
      - garage
      - soggiorno
```

### Relevant log output

```shell
///===///
```

### Frigate stats

```json
///===///
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

How setup frigate to set nginx listen only IPV4 ?

Due to the problem/issue I've mounted nginx.conf in a separate volume and modified myself.

Thanks
