### DISCUSSION TITLE
[Config Support]: troubling accessing UI, when I can it is slow and in a restart loop

### DISCUSSION THREAD

**Discussion by Applegrcoug** [blakeblackshear/frigate#12046] [Config Support]
### Describe the problem you are having

Some changes in my config.yml make it so my docker instance can't connect....I get a "can't connect to 127.0.0.1 port 5000"

For example, if I use preset-record-generic I can connect, but if I change to preset-record-generic-audio-copy I can't.  Heck, in the process of writing this, the frigate container stopped working to even pull the api/stats.  

When I do have a yml that I can connect, frigate seems slow and sometimes the cameras don't load or there is a lot of latency.  Sometimes the camera loads and then drops out and then loads again.  I've tried re-writing my yml several times to see if it helps...it doesn't.  I attached my latest one which I robbed from someone else at adjusted things.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 10.10.10.231
  user: mqtt
  password: ttqm
detectors:
  coral:
    type: edgetpu
    device: pci
model:
  width: 320
  height: 320
  path: /edgetpu_model.tflite
  labelmap_path: /labelmap.txt
logger:
  default: info
  logs:
    logs: debug
birdseye:
  enabled: True
  width: 640
  height: 320
  quality: 2
  mode: continuous
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic
    rtmp: preset-rtmp-generic
detect:
  enabled: True
  width: 640
  height: 320
  fps: 6
  max_disappeared: 25
  stationary: 
    interval: 50
    threshold: 50
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 160000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.7
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 1
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 15
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 10
    objects:
      person: 15
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.10.10.23/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pw@10.10.10.23/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    best_image_timeout: 60
    zones:
      driveway_zone1:
        coordinates: 52,236,40,320,640,320,640,186,614,164,472,63,284,0,203,45
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
    ui:
      order: 1
      dashboard: True
  sidedriveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.10.10.21/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pw@10.10.10.21/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    best_image_timeout: 60
    zones:
      sidedriveway_zone1:
        coordinates: 386,0,129,37,0,64,0,320,640,320,640,257,470,0
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
    ui:
      order: 2
      dashboard: True
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.10.10.22/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pw@10.10.10.22/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    best_image_timeout: 60
    zones:
      frontyard_zone1:
        coordinates: 0,172,0,320,640,320,640,104,557,51,469,23,401,21,278,36,130,94
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
    ui:
      order: 0
      dashboard: True
  pool:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.10.10.20/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pw@10.10.10.20/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    best_image_timeout: 60
    zones:
      pool_zone1:
        coordinates: 262,178,542,96,265,17,112,42
        objects:
          - person
      pool_zone2:
        coordinates: 259,173,118,42,265,10,530,92,626,65,390,0,101,0,46,0,0,320,640,320,640,62
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
    ui:
      order: 3
      dashboard: True
```

### Relevant log output

```shell
2024-06-18 17:38:35.732426423  [INFO] Preparing Frigate...
2024-06-18 17:38:35.746192026  [INFO] Starting Frigate...
2024-06-18 17:38:36.839685102  [2024-06-18 17:38:36] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-06-18 17:38:36.901769979  [2024-06-18 17:38:36] peewee_migrate.logs            INFO    : Starting migrations
2024-06-18 17:38:36.906364603  [2024-06-18 17:38:36] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-06-18 17:38:36.913469778  [2024-06-18 17:38:36] frigate.app                    INFO    : Recording process started: 375
2024-06-18 17:38:36.916122300  [2024-06-18 17:38:36] frigate.app                    INFO    : go2rtc process pid: 89
2024-06-18 17:38:36.946735225  [2024-06-18 17:38:36] detector.coral                 INFO    : Starting detection process: 385
2024-06-18 17:38:36.979112623  [2024-06-18 17:38:36] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-06-18 17:38:36.984215426  [2024-06-18 17:38:36] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-06-18 17:38:36.994529041  [2024-06-18 17:38:36] frigate.app                    INFO    : Output process started: 388
2024-06-18 17:38:36.994533201  [2024-06-18 17:38:36] frigate.app                    INFO    : Camera processor started for driveway: 395
2024-06-18 17:38:37.001906405  [2024-06-18 17:38:36] frigate.app                    INFO    : Camera processor started for sidedriveway: 398
2024-06-18 17:38:37.001910505  [2024-06-18 17:38:36] frigate.app                    INFO    : Camera processor started for frontyard: 410
2024-06-18 17:38:37.001911775  [2024-06-18 17:38:36] frigate.app                    INFO    : Camera processor started for pool: 413
2024-06-18 17:38:37.002739653  [2024-06-18 17:38:37] frigate.app                    INFO    : Capture process started for driveway: 416
2024-06-18 17:38:37.018300109  [2024-06-18 17:38:37] frigate.app                    INFO    : Capture process started for sidedriveway: 419
2024-06-18 17:38:37.018303139  [2024-06-18 17:38:37] frigate.app                    INFO    : Capture process started for frontyard: 424
2024-06-18 17:38:37.030593476  [2024-06-18 17:38:37] frigate.app                    INFO    : Capture process started for pool: 442
```

### Frigate stats

```json
{
  "cameras": {
    "driveway": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4.84,
      "capture_pid": 415,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 420,
      "pid": 395,
      "process_fps": 4.79,
      "skipped_fps": 0
    },
    "frontyard": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.3,
      "capture_pid": 424,
      "detection_enabled": 1,
      "detection_fps": 1.02,
      "ffmpeg_pid": 444,
      "pid": 409,
      "process_fps": 4.98,
      "skipped_fps": 0
    },
    "pool": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.28,
      "capture_pid": 429,
      "detection_enabled": 1,
      "detection_fps": 0.56,
      "ffmpeg_pid": 449,
      "pid": 413,
      "process_fps": 4.94,
      "skipped_fps": 0
    },
    "sidedriveway": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.16,
      "capture_pid": 419,
      "detection_enabled": 1,
      "detection_fps": 0.53,
      "ffmpeg_pid": 427,
      "pid": 398,
      "process_fps": 5.08,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "14": {
      "cmdline": "/bin/sh -e /run/s6/basedir/scripts/rc.init top sh -c sleep 10",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "97": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.0",
      "cpu_average": "20",
      "mem": "1.5"
    },
    "119": {
      "cmdline": "sleep 10s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "126": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "149": {
      "cmdline": "sh -c sleep 10",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "150": {
      "cmdline": "sleep 10",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "151": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "152": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "153": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "156": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "167": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "300": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "312": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "318": {
      "cmdline": "nginx: cache loader process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "373": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "375": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "384": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "385": {
      "cmdline": "frigate.detector.coral",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.1"
    },
    "388": {
      "cmdline": "frigate.output       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "393": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x320 -i pipe: -f mpegts -s 1440x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "395": {
      "cmdline": "frigate.process:driveway",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.0"
    },
    "397": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x320 -i pipe: -f mpegts -s 1440x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "398": {
      "cmdline": "frigate.process:sidedriveway",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.0"
    },
    "409": {
      "cmdline": "frigate.process:frontyard",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.0"
    },
    "412": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x320 -i pipe: -f mpegts -s 1440x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "413": {
      "cmdline": "frigate.process:pool ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.0"
    },
    "415": {
      "cmdline": "frigate.capture:driveway",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "418": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x320 -i pipe: -f mpegts -s 1440x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "419": {
      "cmdline": "frigate.capture:sidedriveway",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "420": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.23/cam/realmonitor?channel=1&subtype=1 -r 6 -vf fps=6,scale_cuda=w=640:h=320:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.3"
    },
    "423": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x320 -i pipe: -f mpegts -s 640x320 -codec:v mpeg1video -q 2 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "424": {
      "cmdline": "frigate.capture:frontyard",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "427": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.21/cam/realmonitor?channel=1&subtype=1 -r 6 -vf fps=6,scale_cuda=w=640:h=320:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.3"
    },
    "428": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.23/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "429": {
      "cmdline": "frigate.capture:pool ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "444": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.22/cam/realmonitor?channel=1&subtype=1 -r 6 -vf fps=6,scale_cuda=w=640:h=320:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.3"
    },
    "449": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.20/cam/realmonitor?channel=1&subtype=1 -r 6 -vf fps=6,scale_cuda=w=640:h=320:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.3"
    },
    "452": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.21/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/sidedriveway@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "455": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.22/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontyard@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "456": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.10.20/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/pool@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    }
  },
  "detection_fps": 2.11,
  "detectors": {
    "coral": {
      "detection_start": 1718732779.99497,
      "inference_speed": 9.84,
      "pid": 385
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 1080": {
      "dec": "2.0%",
      "enc": "0.0%",
      "gpu": "0.0%",
      "mem": "7.07%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 373
    },
    "recording": {
      "pid": 375
    }
  },
  "service": {
    "last_updated": 1718732780,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 508.7,
        "mount_type": "tmpfs",
        "total": 512,
        "used": 3.3
      },
      "/media/frigate/clips": {
        "free": 3901320,
        "mount_type": "ext4",
        "total": 4127354.9,
        "used": 16303.8
      },
      "/media/frigate/recordings": {
        "free": 3901320,
        "mount_type": "ext4",
        "total": 4127354.9,
        "used": 16303.8
      },
      "/tmp/cache": {
        "free": 942.4,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 11.3
      }
    },
    "temperatures": {
      "apex_0": 51.55
    },
    "uptime": 5,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

My install is proxmox with a ryzen 1600x, 32gb ram, a gtx 1080 gpu and coral.  The gpu and coral and 12gb of ram are passed through to an ubuntu server running frigate. In docker, for the smh, I have given 512mb of ram.

**Comment by Applegrcoug** [comment]
ETA more info.  I have reinstalled the entire system without proxmox.  Swapped out the RAM, the GPU and it still is not behaving like it should.  In fact, last night I had it running for 40min before it died.

**Comment by NickM-27** [comment]
What is the docker compose? What storage is the system running on? Screenshot of the system page?

**Comment by Applegrcoug** [comment]
storage is on an iscsi share on a nas.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    command: sh -c "sleep 30"
    shm_size: "512mb"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerapps/frigate/config:/config
      - /mnt/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "notagoodpassword"
```

![2024-06-20](https://github.com/blakeblackshear/frigate/assets/92070315/13121dcb-2a73-4a57-ae93-52f97787d758)
