### DISCUSSION TITLE
[Config Support]: New error from NPM "The plain HTTP request was sent to HTTPS port"

### DISCUSSION THREAD

**Discussion by downtownsj1973** [blakeblackshear/frigate#12043] [Config Support] [answered]
### Describe the problem you are having

After recently moving to dev-5b60785 I am now getting an error when access the auth port 8080 via Nginx Proxy Manager (NPM).  If I take this same config and direct to port 5000, I do not get this error.

custom NPM config is applied to root path at /

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;

### Version

dev-5b60785

### Frigate config file

```yaml
##########################################################################
##                             Telemetry                                ##
##########################################################################


telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    network_bandwidth: true
  version_check: true

##########################################################################
##                             Database                                 ##
##########################################################################
# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db


##########################################################################
##                              MQTT                                    ##
##########################################################################
mqtt:
  host: 10.250.11.88
  port: 1883
  topic_prefix: frigate
    #stats (default: shown below)
    #stats_interval: 60



##########################################################################
##                      Global Detection                                ##
##########################################################################
detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  fps: 5

model:
  ##v1
  ##path: plus://a0fbfe35872d0f25ee107ad5c813bda6
  ##v2
  path: plus://1168ea7c6a61ca1256f5557f8cc1fc07
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320

##########################################################################
##                       Global Camera Config                           ##
##########################################################################

birdseye:
  enabled: true
  mode: motion
  quality: 1




##########################################################################
##                             Cameras                                  ##
##########################################################################
cameras:

###---

  Hallway2-Dome:
    enabled: true
    ui:
      order: 10
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.139/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://username:password@10.250.11.139/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    webui_url: http://10.250.11.139
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    onvif:
      host: 10.250.11.139
      port: 80
      user: username
      password: Password
      autotracking:
        enabled: true
        calibrate_on_startup: false
        zooming: absolute
        zoom_factor: 0.3
        required_zones:
          - zone_1
        return_preset: Home

        movement_weights: 0.25, 1.0, 5.686736583709717, 5.641918780726772, 0.5237098432356317
    objects:
      track:
        - person
        - cat
        - face
        - package


    record:
      enabled: true
      retain:
        days: 3
        mode: all

###---

  Attic-West-Dome:
    enabled: true
    ui:
      order: 12
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.129/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://username:password@10.250.11.129/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    webui_url: http://10.250.11.129
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    onvif:
      host: 10.250.11.129
      port: 80
      user: username
      password: Password
      autotracking:
        enabled: true
        calibrate_on_startup: false
        zooming: absolute
        zoom_factor: 0.3
        required_zones:
          - zone_1
        return_preset: Home

        movement_weights: 0.25, 1.0, 6.60681939125061, 6.802366996067828, 0.2713363485951592
    objects:
      track:
        - person
        - cat
        - face
        - package


    record:
      enabled: true
      retain:
        days: 3
        mode: all

###---
###---

  Attic-East-Dome:
    enabled: true
    ui:
      order: 11
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.22/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://username:password@10.250.11.22/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    webui_url: http://10.250.11.22
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    onvif:
      host: 10.250.11.22
      port: 80
      user: username
      password: Password
      autotracking:
        enabled: true
        calibrate_on_startup: false
        zooming: absolute
        zoom_factor: 0.3
        required_zones:
          - zone_1
        return_preset: Home

        movement_weights: 0.25, 1.0, 8.895801782608032, 6.665948632968369, 0.598642099288203
    objects:
      track:
        - person
        - cat
        - face
        - package

    record:
      enabled: true
      retain:
        days: 3
        mode: all

###---

  Kitchen-Turret:
    enabled: true
    ui:
      order: 9
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.10.111/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://username:password@10.250.10.111/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio

      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.10.111

    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package



    record:
      enabled: true
      retain:
        days: 3
        mode: all
#---

###---

  LivingRoom-Turret:
    enabled: true
    ui:
      order: 8
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.239/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://username:password@10.250.11.239/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio

      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.11.239

    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package



    record:
      enabled: true
      retain:
        days: 3
        mode: all
#---

###---

  DiningRoom-Turret:
    enabled: true
    ui:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.242/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://username:password@10.250.11.242/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio

      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.11.242

    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package



    record:
      enabled: true
      retain:
        days: 3
        mode: all
#---

###---

  Garage-Turret:
    enabled: true
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.10.115/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.10.115
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package
        - dog
        - license_plate
        - car
        - amazon
        - fedex
        - ups



    record:
      enabled: true
      retain:
        days: 3
        mode: all
#---

###---

  Backyard-Turret:
    enabled: true
    ui:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.10.134/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://username:password@10.250.10.134/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.10.134

    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package
        - dog



    record:
      enabled: true
      retain:
        days: 3
        mode: all
#---

###---

  Front-Turret:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.10.167/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://username:password@10.250.10.167/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.10.167
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package
        - dog
        - license_plate
        - car
        - amazon
        - fedex
        - ups

    record:
      enabled: true
      retain:
        days: 3
        mode: all

#---

###---

  Driveway-Turret:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.10.137/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://username:password@10.250.10.137/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: http://10.250.10.137
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package
        - dog
        - license_plate
        - car
        - amazon
        - fedex
        - ups



    record:
      enabled: true
      retain:
        days: 3
        mode: all

#---

  Garage-Doorbell:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.75:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://username:password@10.250.11.75:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: https://10.250.11.75
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package



    record:
      enabled: true
      retain:
        days: 3
        mode: all
#---

  Front-Doorbell:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.250.11.5:8555/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://username:password@10.250.11.5:8555/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true
      listen:
        - fire_alarm
        - scream
        - speech
        - yell
        - bark

    webui_url: https://10.250.11.5:8444
    zones:
      zone_1:
        coordinates: 2560,1440,2560,0,0,0,0,1440

    objects:
      track:
        - person
        - cat
        - face
        - package


    record:
      enabled: true
      retain:
        days: 3
        mode: all

go2rtc:
  streams:
    Front-Doorbell:
      - ffmpeg:http://10.250.11.5/flv?port=1936&app=bcs&stream=channel0_main.bcs&user=username&password=Password#video=copy#audio=copy#audio=opus
      - rtsp://username:password@10.250.11.5:8555/h264Preview_01_sub
    Front-Doorbell_sub:
      - ffmpeg:http://10.250.11.5/flv?port=1936&app=bcs&stream=channel0_ext.bcs&user=username&password=Password
    Garage-Doorbell:
      - ffmpeg:http://10.250.11.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=Password#video=copy#audio=copy#audio=opus
      - rtsp://username:password@10.250.11.75:554/h264Preview_01_sub
    Garage-Doorbell_sub:
      - ffmpeg:http://10.250.11.75/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Password


##########################################################################
##                             Snapsots                                 ##
##########################################################################
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 175
  required_zones: []
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
    objects:
      person: 60
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

##########################################################################
##                              Objects                                 ##
##########################################################################

objects:
  filters:
    person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.80
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.82
    #cat:
    #face:
    #package:
    #dog:
    #license_plate:
    #car:
    #amazon:
    #fedex:
    #ups:

##########################################################################
##                         Frigate Managed                              ##
##########################################################################

camera_groups:
  Doorbells:
    order: 1
    icon: LuDoorClosed
    cameras:
      - Front-Doorbell
      - Garage-Doorbell
  Front_Door:
    order: 2
    icon: LuMailbox
    cameras:
      - Front-Doorbell
      - Front-Turret
      - Driveway-Turret
  Back_Door:
    order: 3
    icon: LuDoorClosed
    cameras:
      - Garage-Doorbell
      - Garage-Turret
  Attic:
    order: 4
    icon: LuHome
    cameras:
      - Attic-East-Dome
      - Attic-West-Dome
      - Hallway2-Dome
  Outside:
    order: 5
    icon: LuSun
    cameras:
      - Backyard-Turret
      - Driveway-Turret
      - Front-Doorbell
      - Front-Turret
      - Garage-Doorbell
      - Garage-Turret
  Inside:
    order: 6
    icon: LuHome
    cameras:
      - Attic-East-Dome
      - Attic-West-Dome
      - DiningRoom-Turret
      - Hallway2-Dome
      - Kitchen-Turret
      - LivingRoom-Turret
version: 0.14
```

### Relevant log output

```shell
NGINX logs on Frigate show the following:


Type
Info
Timestamp
2024-06-18 09:24:26
Tag
GET
Message
::ffff:10.250.11.88 - - [18/Jun/2024:09:24:26 -0400] "GET /favicon.ico HTTP/1.1" 400 657 "https://redacted.duckdns.org/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0" "192.168.2.1"

and


Type
Info
Timestamp
2024-06-18 09:24:26
Tag
GET
Message
::ffff:10.250.11.88 - - [18/Jun/2024:09:24:26 -0400] "GET / HTTP/1.1" 400 657 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0" "192.168.2.1"
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

Tried newer release to see if this still happened and it did.
