### DISCUSSION TITLE
[Bug]: upgraded to v0.14Beta now Camera Live View Not Working

### DISCUSSION THREAD

**Discussion by jeremy-betts** [blakeblackshear/frigate#12047] [Report a Bug] [answered]
### Describe the problem you are having

After upgrading from v0.13.2 to v0.14.Beta2 the live view for cameras does not work. All other camera views work.

In the chrome console I get the following error:
WebSocket connection to 'ws:￼//192.168.100.29:5000/live/mse/api/ws?src=backyard' failed: WebSocket is closed before the connection is established.
(anonymous)	@	￼BirdseyeLivePlayer-C2UwuJJ6.js:12

### Steps to reproduce

From the main Frigate screen click a camera preview. The video fails to load for the individual camera.

### Version

v0.14.Beta2

### Frigate config file

```yaml
logger:
  # Optional: default log level (default: shown below)
  default: debug
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: debug
mqtt:
  enabled: true
  host: 192.168.100.29 # <---- same mqtt broker that home assistant uses
  user: ha
  password: b00bi3s
  port: 1883
  topic_prefix: frigate

go2rtc:
  streams:
    back_hill:
      - rtsp://admin:@192.168.100.203:80/ch0_0.264
    back_hill_sub:
      - rtsp://admin:@192.168.100.203:80/ch0_1.264
    backyard:
      - rtsp://admin:@192.168.100.201:80/ch0_0.264
    backyard_sub:
      - rtsp://admin:@192.168.100.201:80/ch0_1.264
    chicken_run:
      - rtsp://admin:admn@192.168.100.202:554/11
    chicken_run_sub:
      - rtsp://admin:admn@192.168.100.202:554/12
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 3
    post_capture: 5
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true

cameras:
  backyard: # <--- this will be changed to your actual camera later
    enabled: true
    motion:
      threshold: 30
      mask: 
        0.349,0.31,0.246,0.407,0.183,0.293,0.179,0.11,0.204,0.001,0.996,0.003,0.993,0.216,0.904,0.198,0.82,0.341,0.717,0.25,0.554,0.289
    record:
      enabled: true
      events:
        retain:
          default: 10
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    zones:
      zone_0:
        coordinates: 241,177,239,124,336,119,351,169
    detect:
      stationary:
        interval: 100
        threshold: 25
    objects:
      filters:
        car: {}
        bear: {}
  back_hill: # <--- this will be changed to your actual camera later
    enabled: true
    motion:
      threshold: 20
    record:
      enabled: true
      events:
        retain:
          default: 10
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/back_hill
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_hill_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      stationary:
        interval: 100
        threshold: 25
    objects:
      filters:
        car:
          mask:
            - 414,127,461,186

  chicken_run: # <--- this will be changed to your actual camera later
    enabled: true
    motion:
      threshold: 30
    record:
      enabled: true
      events:
        retain:
          default: 10
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/chicken_run
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/chicken_run_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      stationary:
        interval: 100
        threshold: 25
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
detect:
  fps: 2
  enabled: true
  max_disappeared: 25
objects:
  track:
    - person
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - bear
    - zebra

model:
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

birdseye:
  enabled: true
  mode: continuous

version: 0.14
camera_groups: {}
```

### Relevant log output

```shell
No relevant logs on the server
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Various

**Comment by NickM-27** [comment, marked as answer]
this has already been fixed in the latest commits

**Reply by Redsandro** [reply]
> this has already been fixed in the latest commits

@NickM-27 Are those commits part of the next beta `v0.14.Beta3`? Because I'm having the same problem in Beta3.

Interestingly, in Firefox, with a broken live view, if you navigate to a random page like about:config, and then press back, the live view starts working.

**Reply by hawkeye217** [reply]
No, beta 3 does not have these fixes. Beta 4 will.

**Reply by Redsandro** [reply]
@hawkeye217 great, thank you! You replied so fast I fell off my chair from the sonic boom.

**Reply by hawkeye217** [reply]
@NickM-27 is usually faster than me 😂

**Comment by jeremy-betts** [comment]
Any idea when beta4 will be ready?

**Reply by hawkeye217** [reply]
When it's ready :)

You can always run dev builds in the meantime if you're feeling more adventurous.

**Comment by jeremy-betts** [comment]
I'm running on a docker container on a jetson nano. Is there a way to run
dev?

**Reply by NickM-27** [reply]
just change the image to a dev image

**Comment by jeremy-betts** [comment]
Setting my docker image to
ghcr.io/blakeblackshear/frigate:dev-tensorrt-jp4
doesn't work

**Reply by hawkeye217** [reply]
That's not a valid tag. You can find the latest dev builds here: https://github.com/blakeblackshear/frigate/pkgs/container/frigate

**Comment by jeremy-betts** [comment]
OK I was able to run the dev image but still had the same issue with Live
View. When I click on a specific camera it just goes to the loading
spinner. Nothing in the chrome console or in the frigate logs.

Tried with dev-012aa63-tensorrt-jp4 and dev-fe9a3c9-tensorrt-jp4

**Reply by hawkeye217** [reply]
`012aa63` was not a good build, but `fe9a3c9` should be. 

The most recent frigate live view code uses MSE first, then falls back to jsmpeg if MSE can't connect.  Since you're running via docker compose, could you try mapping port 1984 and trying to stream the cameras from the go2rtc UI?

**Reply by hawkeye217** [reply]
Also, it would be good to see the browser's developer tools network tab

**Comment by jeremy-betts** [comment]
I tried mapping port 1984 but I get connection refused when trying to open
go2rtc UI

Here is chrome network log
[image: image.png]

**Reply by hawkeye217** [reply]
You'll have to post the image to the discussion on the web - Github doesn't know how to deal with email attachments.

**Comment by jeremy-betts** [comment]
![Screenshot from 2024-07-02 13-30-49](https://github.com/blakeblackshear/frigate/assets/26467709/85cc4e6f-7425-4554-8fbd-513a4e66514e)

**Reply by hawkeye217** [reply]
Thanks. The 2nd to the last item on the list there, `ws?src=backyard` is a websocket connection back to Frigate for your live stream of the `backyard` camera. It hasn't transferred any data (as indicated by `0 B` in the far right column), which is why the loading spinner never disappears.

Do you have any Chrome extensions installed and running? Could you try loading the Frigate UI in incognito mode? Could you try another browser besides Chrome?

**Comment by jeremy-betts** [comment]
No changes using incognito mode or firefox

**Reply by hawkeye217** [reply]
Do you have any unique network conditions or are you using a VPN to access Frigate?

**Reply by hawkeye217** [reply]
When you click on `ws` or `ws?src=backyard` from the devtools network pane, do you see any data being transferred?

**Reply by hawkeye217** [reply]
Also, what's your docker compose?

**Comment by jeremy-betts** [comment]
I use tailscale to remotely access the Home Assistant UI but I am currently
on the same local network.

**Comment by jeremy-betts** [comment]
Yes it appears data is being transferred
![Screenshot from 2024-07-02 14-49-54](https://github.com/blakeblackshear/frigate/assets/26467709/ccaaa4bf-b02d-4c5c-81db-964b206dfd04)

Docker compose:
version: "3.9"
services:
  frigate:
    container_name: frigate
    #network_mode: host
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-fe9a3c9-tensorrt-jp4
    runtime: nvidia   # Add this
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
        - YOLO_MODELS=yolov7x-320
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8080:8080"
      - "8554:8554" # RTSP feeds

**Reply by hawkeye217** [reply]
Thanks.

What's the resolution of your main streams on either the backyard or back_hill cameras?

**Comment by jeremy-betts** [comment]
I have three cameras two are 1280x960 one is 1920x1080

They all show the same issue

**Reply by hawkeye217** [reply]
I've put up this PR to see if it helps with your issue: https://github.com/blakeblackshear/frigate/pull/12271

Once it's merged, pull the dev build and test it for me.

**Comment by jeremy-betts** [comment]
From my iphone/firefox the live view loads if I pinch to zoom.

I tried double clicking from my desktop chrome and the loading spinner
zooms but the camera view does not load.

**Comment by Redsandro** [comment]
I can confirm `dev-be9e606` is working correctly on my env.

**Comment by jeremy-betts** [comment]
Just loaded docker image

Now I get a picture from the camera but there is no video stream just the static picture

![Screenshot from 2024-07-03 08-04-36](https://github.com/blakeblackshear/frigate/assets/26467709/48cffec3-3712-4eaa-9aff-1f363d6c7eff)

**Reply by hawkeye217** [reply]
If you right-click on the camera in single cam live view, does your menu pop up with video-related items? For example, do you see "Show All Controls" or "Save Video Frame As..."?

**Comment by jeremy-betts** [comment]
Sorry I loaded docker image dev-784b701-tensorrt-jp4

**Comment by jeremy-betts** [comment]
Yes

**Reply by hawkeye217** [reply]
But the video is not playing?

**Comment by jeremy-betts** [comment]
Right, the video is not playing.

**Reply by hawkeye217** [reply]
Okay. From what I can see, there's nothing in Frigate's code that is preventing the video from playing at this point. If the websocket data is flowing (as seen in the dev tools network pane), my best guess is that the issue is likely the actual video data that being sent from your camera. I've only ever seen this before on Mac Safari with a cheap doorbell camera - where the camera's video codec is not playable in the browser player. However in that case, the player actually fires a decode error, which Frigate is able to catch and switch the player type. 

There are a few possible options for your case:

1) Don't use go2rtc for restreaming. Frigate will default to its internal live view type, which uses less bandwidth and is more compatible.

2) Continue to use go2rtc, but change the stream names to *not* match your camera names, and just specify the correct URLs in the `path` directive for your cameras. For example, if you change the go2rtc stream `backyard` to `backyard_restream`, change your path to: `- path: rtsp://127.0.0.1:8554/backyard_restream`

**Reply by hawkeye217** [reply]
Something else you could try: continue to use go2rtc, but set the sources to use ffmpeg. For example:

```
go2rtc:
  streams:
    back_hill:
      - ffmpeg:rtsp://admin:@192.168.100.203:80/ch0_0.264
    back_hill_sub:
      - rtsp://admin:@192.168.100.203:80/ch0_1.264
    backyard:
      - ffmpeg:rtsp://admin:@192.168.100.201:80/ch0_0.264
    backyard_sub:
      - rtsp://admin:@192.168.100.201:80/ch0_1.264
    chicken_run:
      - ffmpeg:rtsp://admin:admn@192.168.100.202:554/11
    chicken_run_sub:
      - rtsp://admin:admn@192.168.100.202:554/12
```

**Reply by hawkeye217** [reply]
There's something else that would be helpful to see before you make any changes. In the browser dev tools network tab, when you click on the `ws?src=<camera name>`, can you scroll to the very top of the messages tab and send a screenshot of the lines there? For example:

![Browser tools network tab MSE data](https://github.com/blakeblackshear/frigate/assets/32435876/c81f5562-b206-456a-a320-f0e854273fd4)

**Comment by jeremy-betts** [comment]
![Screenshot from 2024-07-03 10-33-52](https://github.com/blakeblackshear/frigate/assets/26467709/5e091731-f24d-4499-a635-bd01999f2dd4)

**Reply by hawkeye217** [reply]
Thanks. Can you try changing the audio output on your camera to AAC and testing live view again?

**Comment by jeremy-betts** [comment]
I don't think these cameras do audio. I can't find any audio parameters on
the camera UI

**Reply by hawkeye217** [reply]
That may explain it. The camera is telling frigate that FLAC audio is being sent and should be decoded in the stream.

**Comment by jeremy-betts** [comment]
These are cheap cameras but have always been pretty reliable for video.
Anyway to disable the audio on the frigate side?

**Reply by hawkeye217** [reply]
Try what I specified earlier for your go2rtc section in your config:

```
go2rtc:
  streams:
    back_hill:
      - ffmpeg:rtsp://admin:@192.168.100.203:80/ch0_0.264#video=copy
    back_hill_sub:
      - rtsp://admin:@192.168.100.203:80/ch0_1.264
    backyard:
      - ffmpeg:rtsp://admin:@192.168.100.201:80/ch0_0.264#video=copy
    backyard_sub:
      - rtsp://admin:@192.168.100.201:80/ch0_1.264
    chicken_run:
      - ffmpeg:rtsp://admin:admn@192.168.100.202:554/11#video=copy
    chicken_run_sub:
      - rtsp://admin:admn@192.168.100.202:554/12
```
