### DISCUSSION TITLE
[Bug]: v0.14.0-beta3 - Live view feeds go black when switch to live

### DISCUSSION THREAD

**Discussion by calederer** [blakeblackshear/frigate#12050] [Report a Bug]
### Describe the problem you are having

In the new release of beta on the live view page when the camera switches to live video the the feed goes black as shown in the screenshot below
<img width="1634" alt="Screenshot 2024-06-17 at 9 13 05 PM" src="https://github.com/blakeblackshear/frigate/assets/8452372/25bdefb0-3f69-499a-a462-dd6c2a9cf528">

### Steps to reproduce

Watch live view page to switch to live feed for the camera

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p

record:
  enabled: true
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 20
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 20

model:
  path: ##

objects:
  track:
    - person
    - bicycle
    - motorcycle
    - cat
    - dog
    - car
  filters:
    person:
      threshold: 0.85
      min_score: 0.70
    cat:
      threshold: 0.85
      min_score: 0.70
    dog:
      threshold: 0.85
      min_score: 0.70
    car:
      threshold: 0.85
      min_score: 0.70

cameras:
  Driveway:
    ffmpeg:

      inputs:
        - path: rtsp://##@192.168.0.20/axis-media/media.amp?camera=5
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

    motion:
      threshold: 50

    zones:
      parking_area:
        coordinates: 1920,250,1920,1080,0,1080,0,325

    snapshots:
      required_zones:
        - parking_area

    review:
      alerts:
        required_zones:
          - parking_area

  MainGarageDoor:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.20/axis-media/media.amp?camera=6
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

    motion:
      threshold: 50

    zones:
      garage_driveway:
        coordinates: 1036,0,1021,224,1493,263,1920,402,1920,1080,0,1080,0,0

    snapshots:
      required_zones:
        - garage_driveway

    review:
      alerts:
        required_zones:
          - garage_driveway
  GarageWalkway:
    ffmpeg:
      inputs:
        - path: rtsp://##/axis-media/media.amp?camera=7
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

    motion:
      threshold: 50

  GarageBackDoor:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.23/axis-media/media.amp?camera=6
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  GarageSide:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.23/axis-media/media.amp?camera=7
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.23/axis-media/media.amp?camera=5
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.21/axis-media/media.amp?camera=5
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

    zones:
      Front_Door:
        coordinates: 
          1920,1080,1920,54,938,74,965,342,766,410,666,81,425,72,572,490,367,562,0,51,0,1080
    snapshots:
      required_zones:
        - Front_Door

    review:
      alerts:
        required_zones:
          - Front_Door

  LeftFrontWindows:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.21/axis-media/media.amp?camera=6
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  ShitHoleYard:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.21/axis-media/media.amp?camera=7
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  FrontLeftYard:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.22/axis-media/media.amp?camera=5
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  FrontRightYard:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.22/axis-media/media.amp?camera=6
          roles:
            - detect
    detect:
      width: 1920
      height: 1080

  Lake:
    ffmpeg:
      inputs:
        - path: rtsp://##@192.168.0.22/axis-media/media.amp?camera=7
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      threshold: 50


version: 0.14
```

### Relevant log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Axis

**Comment by NickM-27** [comment]
this has already been fixed

**Reply by UmiDevSec** [reply]
I just updated to 0.14-beta3 about 30 minutes ago and I'm experiencing this same issue.
Is there going to be a 0.14-beta4 released soon that includes that fix?

This bug makes it really hard to use Frigate.

**Reply by Sireone** [reply]
Seeing a similar issue, but in my case since I'm using go2rtc with multiple streams, my live view randomly switches to the substream and back.

**Reply by hawkeye217** [reply]
> I just updated to 0.14-beta3 about 30 minutes ago and I'm experiencing this same issue.
> 
> Is there going to be a 0.14-beta4 released soon that includes that fix?
> 
> 
> 
> This bug makes it really hard to use Frigate.

The fix is already available in the dev builds. Frigate 0.14 is still beta software, so use at your own risk :)

**Reply by hawkeye217** [reply]
> Seeing a similar issue, but in my case since I'm using go2rtc with multiple streams, my live view randomly switches to the substream and back.

This is expected and normal behavior. On the live dashboard with all your cameras, Frigate will intelligently switch between still images, streamed images, and a live player when motion is detected.

**Reply by rccoleman** [reply]
What is the logic that determines which is shown?  I have my hi-res streams being used for recording and low-res substreams being used for detection and it seems like the snapshots in the birdseye view are regularly low-res stills when there's no motion.  It's particularly noticeable because my recording stream is 1080P and my detect stream is 640x480, so even the aspect ratio is different.

**Reply by NickM-27** [reply]
Birdseye always uses the stream set for detect as the stream must be decoded. For the UI it is whichever stream you set for live, or the stream that matches the name of the camera

**Reply by rccoleman** [reply]
I guess I'm talking about the "live" view via the button in the upper-left and not the birdseye view.  As you can see in the lower image, it's the 640x480 "detect" stream and is currently a static image with no motion detected:

<img width="669" alt="image" src="https://github.com/blakeblackshear/frigate/assets/860888/e1013412-a93c-4341-8ab2-c97329fbfa00">

Sometimes, seemingly randomly, it flips to the 1920x1080 "recording" stream, and then eventually flips back.  Is that expected?  My cameras are named for the go2rtc recording stream and I've even separately specified that stream for the live stream:

```
cameras:
  upstairshallway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://rcoleman-linux:8554/upstairshallway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://rcoleman-linux:8554/upstairshallway_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: upstairshallway

....

go2rtc:
  streams:
    upstairshallway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.137:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:upstairshallway#audio=opus
```

When I click on the camera from the "live" view, I do get the hi-res recording stream.

I also see a lot of these in the browser console that keep popping up that I haven't been able to track down, and I don't know if they're related:

<img width="567" alt="image" src="https://github.com/blakeblackshear/frigate/assets/860888/3f58b7a5-855e-4ed7-a90d-fbbca3b657a9">

**Reply by NickM-27** [reply]
Right, the still snapshot will be from the detect stream. It switches to live when motion or active objects are detected

**Reply by rccoleman** [reply]
I understand that the snapshot is from the detect stream (as it's used for detection), but it's not very attractive to have a smaller, low-res image there.  I chose the substream for the parts of the pipeline that the user doesn't see, not for use in the UI.

**Reply by rccoleman** [reply]
BTW, are the 401/unauthorized errors that I'm seeing in the browser console unexpected and worthy of an issue?

**Reply by NickM-27** [reply]
how do you have frigate installed?

**Reply by rccoleman** [reply]
As a container, and I'm running the latest dev as of a few hours ago: `image: ghcr.io/blakeblackshear/frigate:dev-abc1ecf-amd64`

**Reply by NickM-27** [reply]
can you check the nginx logs and see if you see a 401 there?

**Reply by rccoleman** [reply]
Yes, I see them there too:

```
2024-06-23 11:49:45.450769401  ::ffff:192.168.1.61 - - [23/Jun/2024:11:49:45 -0700] "GET /api/backdoor/latest.webp?h=347&cache=1719168585337 HTTP/1.1" 200 41786 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:01.538070751  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:01 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168601401 HTTP/1.1" 200 42130 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:10.688863006  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:10 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168610505 HTTP/1.1" 401 50 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:11.832534924  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:11 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168611545 HTTP/1.1" 401 50 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:11.985558486  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:11 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168611800 HTTP/1.1" 401 50 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:12.300674013  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:12 -0700] "GET /api/backdoor/latest.webp?h=347&cache=1719168612177 HTTP/1.1" 200 41514 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:13.549227767  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:13 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168613373 HTTP/1.1" 401 50 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:13.768937646  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:13 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168613633 HTTP/1.1" 401 50 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
2024-06-23 11:50:14.816683602  ::ffff:192.168.1.61 - - [23/Jun/2024:11:50:14 -0700] "GET /api/frontdoor/latest.webp?h=347&cache=1719168614687 HTTP/1.1" 401 50 "http://192.168.1.159:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
```

This is also when I'm accessing Frigate directly by IP (i.e., http://192.168.1.159:5000) with no auth.

**Reply by blakeblackshear** [reply]
What does your compose file look like?

**Reply by rccoleman** [reply]
Here's the service definition:

```
  frigate-14:
    container_name: frigate-14
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #network_mode: host
    cap_add:
      - CAP_PERFMON
    #image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3
    image: ghcr.io/blakeblackshear/frigate:dev-abc1ecf-amd64
    shm_size: "256mb" # update for your cameras based on calculation above
    mem_swappiness: 0
    memswap_limit: 15GB
    deploy:
      resources:
        limits:
          memory: 15GB
    devices:
      - /dev/bus/usb/002:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate-14:/config
      - /nfs/NVR:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8084:8080"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_MQTT_USER: "xxx"
      FRIGATE_MQTT_PASSWORD: "xxx"
      FRIGATE_RTSP_USER: "xxx"
      FRIGATE_RTSP_PASSWORD: "xxx"
      PLUS_API_KEY: "xxx"
```

The `mem_swappiness` and related parameters were an attempt to address these issues described [here](https://deploy-preview-11419--frigate-docs.netlify.app/troubleshooting/recordings), but I think they were due to my WyzeCams, which I've removed from Frigate.

My entire Frigate config is [here](https://dpaste.org/qdgi0).
