### DISCUSSION TITLE
[Support]: High detect CPU usage

### DISCUSSION THREAD

**Discussion by ehn** [blakeblackshear/frigate#12054] [General Support]
### Describe the problem you are having

I'm constantly getting an alert in the Frigate web UI footer for one of my cameras, complaining about high CPU usage (45%). I have two cameras of this type. They're configured identically. I only get this complaint for one of them.

Possibly the high CPU usage could be caused by a specific scene with lots of motion, say leaves moving in the wind. However, they're PTZ cameras, and I've tried pointing them at various things. It makes no difference. I keep getting this notification for one of them and so far never for the other.

The system view is also showing high detect CPU usage for this camera:

<img width="1512" alt="screenshot" src="https://github.com/blakeblackshear/frigate/assets/179446/a9f1c656-039b-4768-ac4f-edf4c8b15843">

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.1
  user: homeassistant
  password: redacted

detectors:
  coral0:
    type: edgetpu
    device: pci:0
  coral1:
    type: edgetpu
    device: pci:1
  coral2:
    type: edgetpu
    device: pci:2
  coral3:
    type: edgetpu
    device: pci:3
  coral4:
    type: edgetpu
    device: pci:4
  coral5:
    type: edgetpu
    device: pci:5
  coral6:
    type: edgetpu
    device: pci:6
  coral7:
    type: edgetpu
    device: pci:7

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-nvidia-h264

model:
  path: plus://redacted

objects:
  track:
    - person
    - face
    - car
    - license_plate
    - dog
    - cat
    - deer
    - ups
    - fedex
    - amazon
    - package
  filters:
    deer:
      min_score: .7
      threshold: .9
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

record:
  enabled: true
    retain:
    days: 14
    mode: all
  events:
    retain:
      default: 60
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 60

go2rtc:
  streams:
    garage_pole:
      - rtsp://redacted:{FRIGATE_RTSP_PASSWORD}@192.168.6.12:554/profile4/media.smp
    garage_pole_sub:
      - rtsp://redacted:{FRIGATE_RTSP_PASSWORD}@192.168.6.12:554/profile5/media.smp
    southeast_pole:
      - rtsp://redacted:{FRIGATE_RTSP_PASSWORD}@192.168.6.14:554/profile4/media.smp
    southeast_pole_sub:
      - rtsp://redacted:{FRIGATE_RTSP_PASSWORD}@192.168.6.14:554/profile5/media.smp

  webrtc:
    candidates:
      - 192.168.1.1:8555
      - stun:8555

cameras:
  garage_pole:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_pole
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_pole_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.6.12
      port: 80
      user: redacted
      password: redacted
    detect:
      width: 1280
      height: 720
  southeast_pole:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/southeast_pole
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/southeast_pole_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.6.14
      port: 80
      user: redacted
      password: redacted
    detect:
      width: 1280
      height: 720

ui:
  timezone: Europe/Stockholm
  strftime_fmt: '%Y-%m-%d %H:%M:%S'

telemetry:
  version_check: true

version: 0.14
```

### Relevant log output

```shell
2024-06-18 10:43:22.615909019  [2024-06-18 10:43:22] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for southeast_pole. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-18 10:45:07.397521436  [2024-06-18 10:45:07] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for southeast_pole. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-06-18 10:45:22.391626532  [2024-06-18 10:45:22] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for southeast_pole. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://redacted:redacted@192.168.6.14:554/profile5/media.smp':
  Metadata:
    title           : Media Presentation
    comment         : samsung
  Duration: N/A, start: -0.623000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, progressive), 1280x720, 5 tbr, 90k tbn
  Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hanwha XNP-6550RH
