### DISCUSSION TITLE
[Config Support]: Support Frigate+ detection

### DISCUSSION THREAD

**Discussion by sebastian-tischer** [blakeblackshear/frigate#12068] [Config Support]
### Describe the problem you are having

Hi Frigate Team,

As a huge fan, I now just switched to Frigate+ - both to support you and to train my own model. As of now it works great and I only have a question I can't solve right now.

The following image shows the camera positioning and behind the fence 2-3 cars get parked.
<img width="1025" alt="1" src="https://github.com/blakeblackshear/frigate/assets/63227608/5097ed9b-ae1a-4848-9e23-239dc7d0b2f9">

To solve constant recognition I used the object mask as below which helps getting no notifications on parked objects.
<img width="1133" alt="2" src="https://github.com/blakeblackshear/frigate/assets/63227608/34fe45bf-08af-4b37-b6af-376b9d0cb040">

BUT: Unfortunately it doesn't recognizes moving cars that get into the red area - both left or right.

I am thinking of moving from global objects>filters to camera specific and then adjust the scores.

Do you have other recommendations or ideas maybe?

Thank you again and warm regards
Sebastian

### Version

13.2

### Frigate config file

```yaml
model:
  path: plus://0a861bbb1c1d837ca5bcac6427c46a64

mqtt:
  enabled: true
  host: 192.168.2.163
  port: 1883
  user: hass-mqtt
  password: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h265

motion:
  threshold: 15
  improve_contrast: True
  contour_area: 10

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - cat
    - dog
    - car
  filters:
    person:
      min_score: 0.60
      threshold: 0.75
      min_area: 5000
      min_ratio: 0
      max_ratio: 0.8
    car:
      min_score: 0.60
      threshold: 0.75
#      min_area: 5000
#      min_ratio: 1.25
#      max_ratio: 1.8
    cat:
      min_score: 0.60
      threshold: 0.75
#      min_area: 5000
#      min_ratio: 1.25
#      max_ratio: 1.9
    dog:
      min_score: 0.60
      threshold: 0.75
#      min_area: 5000
#      min_ratio: 1.25
#      max_ratio: 1.9

birdseye:
  enabled: True
  mode: continuous

record:
  enabled: True
  retain:
    mode: motion
  events:
    pre_capture: 30
    post_capture: 30
    objects:
      - person
      - cat
      - dog
      - car
    retain:
      default: 30
      mode: motion
      objects:
        person: 30
        cat: 30
        dog: 30
        car: 30

snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True
  crop: False
  retain:
    default: 30
    objects:
      person: 30
      car: 30
      cat: 30
      dog: 30

cameras:
  Einfahrt:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Einfahrt
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Einfahrt-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 325,405,1003,383,1077,457,1280,691,1280,720,0,720,0,434
            - 0,372,0,221,545,144,558,333
  Eingang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang
          input_args: preset-rtsp-restream

          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Eingang-Detect
          input_args: preset-rtsp-restream

          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 1035,319,1173,104,1000,52,888,27,699,0,437,0,420,78
            - 393,720,1280,720,1280,439,761,207,169,334
  Garten:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten
          input_args: preset-rtsp-restream

          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten-Detect
          input_args: preset-rtsp-restream

          roles:
            - detect
  Haus:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Haus
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Haus-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 1280,0,1280,720,257,720,250,0
  Klingel:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Klingel
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Klingel-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 611,451,920,453,904,382,908,331,611,334
            - 339,481,358,438,327,381,0,339,0,434
go2rtc:
  streams:
    Einfahrt:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.141/livestream/11#video=copy#audio=copy#audio=opus"
    Einfahrt-Detect:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.141/livestream/12"
    Eingang:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.127/livestream/11#video=copy#audio=copy#audio=opus"
    Eingang-Detect:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.127/livestream/12"
    Garten:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.128/livestream/11#video=copy#audio=copy#audio=opus"
    Garten-Detect:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.128/livestream/12"
    Haus:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.194/livestream/11#video=copy#audio=copy#audio=opus"
    Haus-Detect:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.194/livestream/12"
    Garage:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.188/livestream/11#video=copy#audio=copy#audio=opus"
    Garage-Detect:
      - "ffmpeg:rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.188/livestream/12"
    Klingel:
      - "ffmpeg:rtsp://ghusmf0002:NKDasD3YaCnzhC2DzVXDkCmnbTPfryjg@192.168.2.190/mpeg/media.amp"
    Klingel-Detect:
      - "ffmpeg:rtsp://ghusmf0002:NKDasD3YaCnzhC2DzVXDkCmnbTPfryjg@192.168.2.190/mpeg/media.amp"
```

### Relevant log output

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Object Detector

Coral
