### DISCUSSION TITLE
[Question]:  is go2rtc useful for wyze-bridge "fed" cameras?

### DISCUSSION THREAD

**Discussion by g13092** [blakeblackshear/frigate#12072] [Ask A Question] [answered]
### What is your question:

For the time being, all my cams are Wyze.  I've set up Frigate to take in the rtsp address stream for each cam from the bridge: 

```
  SouthCam:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.248:8554/new-south-cam
        roles:
        - record
        - detect
```
The address 192.168.248 is the home of both the wyze-bridge and frigate dockers.  

To me, the bridge seems to be like go2rtc, rebroadcasting what it gets from the cam.  Maybe I'm totally off base.  But what I'm wondering, is there any benefit to inserting go2rtc in the chain?  

Why?  I'm thinking about how go2rtc might reduce load on this machine by using substreams to feed detection.  It's working and stable, but frequently higher than 4 (quad core) load.  hdw accel is working, coral is detecting nicely, and I'm only recording at 5fps.  I've got 10 cams, 6 being bridged, shm set to 256mb.  That's all the runs on this machine, with a basic Deb12 OS, no desktop.
