### DISCUSSION TITLE
[Support]: Frigate suddenly stops recording video

### DISCUSSION THREAD

**Discussion by n07r1x** [blakeblackshear/frigate#12075] [General Support] [answered]
### Describe the problem you are having

I had this issue already some months ago. So it doesn't occur very often but it's very bad though, because it simply stops recording from that sudden point on and I can only fix this by manually restarting the frigate container.
It looks like frigate is only recording audio and no video anymore. The recorded files are just some kb and there is only audio recorded. Live view is still working though.
At the time when it stops recording video there is no output in the logs. It only happens to a single camera, in this case a Hikvision. I also have some Reolink in use. Sadly I cannot remember if it also affected the Hikvision or a Reolink camera the last time this happened.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
#database:
#  path: /media/frigate/db/frigate.db

mqtt:
  host: 10.10.0.22
  user: mqtt
  password: mqtt

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    stellplatz_main:
    - rtsp://admin:xxx@10.10.0.201:554/h265Preview_01_main
    hinterhof_main:
    - rtsp://admin:xxx@10.10.0.202:554/h265Preview_01_main
    eingang_main:
    - rtsp://admin:xxx@10.10.0.203:554/Streaming/Channels/101
    eingang_sub:
    - rtsp://admin:xxx@10.10.0.203:554/Streaming/Channels/103

cameras:
  Stellplatz:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: 
          http://10.10.0.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx
        roles:
        - detect
        input_args: preset-http-reolink

      - path: rtsp://127.0.0.1:8554/stellplatz_main
        roles:
        - record
        input_args: preset-rtsp-restream
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps  1
          -strftime 1 -c:v copy -c:a aac

    detect:
      width: 896
      height: 512
      fps: 15

    record:
      enabled: true
      retain:
        days: 14
      events:
        retain:
          default: 14

    objects:
      track:
      - person
      - cat
      - car
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

    motion:
      mask:
      - 792,512,829,512,827,468,794,470

  Hinterhof:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: 
          http://10.10.0.202/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx
        roles:
        - detect
        input_args: preset-http-reolink

      - path: rtsp://127.0.0.1:8554/hinterhof_main
        roles:
        - record

        input_args: preset-rtsp-restream
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps  1
          -strftime 1 -c:v copy -c:a aac

    detect:
      width: 896
      height: 512
      fps: 15

    record:
      enabled: true
      retain:
        days: 14
      events:
        retain:
          default: 14

    objects:
      track:
      - person
      - cat
      - car
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

    motion:
      mask:
      - 792,512,829,512,827,468,794,470
  Eingang:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/eingang_sub
        roles:
        - detect
        input_args: preset-rtsp-restream

      - path: rtsp://127.0.0.1:8554/eingang_main
        roles:
        - record

        input_args: preset-rtsp-restream
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps  1
          -strftime 1 -c:v copy -c:a copy

    detect:
      width: 1920
      height: 1080
      fps: 10

    record:
      enabled: true
      retain:
        days: 14
      events:
        required_zones:
        - zone_auffahrt
        - zone_alles
        retain:
          default: 14

    objects:
      track:
      - person
      - cat
      - car
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14
      required_zones:
      - zone_auffahrt
      - zone_alles
    motion:
      mask:
      - 1920,980,1920,1025,1863,1028,1862,983
    zones:
      zone_auffahrt:
        coordinates: 1232,99,943,303,1920,1080,1920,348
        objects:
        - car
      zone_alles:
        coordinates: 0,1080,1920,1080,1920,0,0,0
        objects:
        - person
        - cat
```

### Relevant log output

```shell
No related log output
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:xxx@10.10.0.203:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc), 3840x2160 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{
  "cameras": {
    "Eingang": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 10.1,
      "capture_pid": 472,
      "detection_enabled": 1,
      "detection_fps": 10.1,
      "ffmpeg_pid": 481,
      "pid": 463,
      "process_fps": 10.1,
      "skipped_fps": 0
    },
    "Hinterhof": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 15.1,
      "capture_pid": 468,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 473,
      "pid": 461,
      "process_fps": 15.1,
      "skipped_fps": 0
    },
    "Stellplatz": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 15,
      "capture_pid": 464,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 469,
      "pid": 459,
      "process_fps": 15,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "79": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "8.0",
      "cpu_average": "7",
      "mem": "0.1"
    },
    "108": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "109": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "3.0",
      "cpu_average": "3",
      "mem": "1.5"
    },
    "119": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "141": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "142": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "143": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "144": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "157": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "170": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "180": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "196": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "425": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "427": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "436": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "437": {
      "cmdline": "frigate.detector.coral",
      "cpu": "3.1",
      "cpu_average": "4",
      "mem": "0.5"
    },
    "439": {
      "cmdline": "frigate.output       ",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.5"
    },
    "442": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "443": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "447": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "448": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "459": {
      "cmdline": "frigate.process:Stellplatz",
      "cpu": "2.5",
      "cpu_average": "2",
      "mem": "0.6"
    },
    "461": {
      "cmdline": "frigate.process:Hinterhof",
      "cpu": "2.5",
      "cpu_average": "3",
      "mem": "0.6"
    },
    "463": {
      "cmdline": "frigate.process:Eingang",
      "cpu": "4.3",
      "cpu_average": "4",
      "mem": "0.6"
    },
    "464": {
      "cmdline": "frigate.capture:Stellplatz",
      "cpu": "1.5",
      "cpu_average": "1",
      "mem": "0.5"
    },
    "468": {
      "cmdline": "frigate.capture:Hinterhof",
      "cpu": "1.5",
      "cpu_average": "1",
      "mem": "0.5"
    },
    "469": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://10.10.0.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 15 -vf fps=15,scale_vaapi=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "472": {
      "cmdline": "frigate.capture:Eingang",
      "cpu": "4.2",
      "cpu_average": "4",
      "mem": "0.5"
    },
    "473": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://10.10.0.202/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 15 -vf fps=15,scale_vaapi=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "479": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/stellplatz_main -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Stellplatz@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.3",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "481": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang_sub -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "9.1",
      "cpu_average": "9",
      "mem": "0.2"
    },
    "483": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hinterhof_main -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Hinterhof@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.5",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "486": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang_main -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Eingang@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "2360": {
      "cmdline": "sh",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "2620": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 10.1,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 7.94,
      "pid": 437
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "2.12%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 425
    },
    "recording": {
      "pid": 427
    }
  },
  "service": {
    "last_updated": 1718865624,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 93.8,
        "mount_type": "tmpfs",
        "total": 100,
        "used": 6.2
      },
      "/media/frigate/clips": {
        "free": 863807.4,
        "mount_type": "ext4",
        "total": 3754443,
        "used": 2699847.2
      },
      "/media/frigate/recordings": {
        "free": 863807.4,
        "mount_type": "ext4",
        "total": 3754443,
        "used": 2699847.2
      },
      "/tmp/cache": {
        "free": 884.4,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 69.3
      }
    },
    "temperatures": {},
    "uptime": 1592,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2086G2-IU
