### DISCUSSION TITLE
[Bug]: Beta 3 Docker Container Won't Start

### DISCUSSION THREAD

**Discussion by liamstears** [blakeblackshear/frigate#12077] [Report a Bug]
### Describe the problem you are having

Docker container won't start with new 0.14.0 Beta 3, 0.14.0 Beta 2 worked fine.

### Steps to reproduce

Upgrade to 0.14.0 Beta 3

### Version

0.14.0 Beta 3

### Frigate config file

```yaml
mqtt:
  host: *ip*
  user: *username*
  password: *password*
detectors:
  coral_pci:
    type: edgetpu
    device: pci
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    *1*:
      - rtsp://*userpassip*/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:*1*#audio=pcma
      - ffmpeg:*1*#audio=aac
    *2*:
      - rtsp://*userpassip*/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:*2*#audio=pcma
      - ffmpeg:*2*#audio=aac
    *3*:
      - rtsp://*userpassip*/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:*3*#audio=pcma
  webrtc:
    candidates:
      - *ip*:8555
cameras:
  *1*:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/*1*
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1920
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: motion
  *2*:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/*2*
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1440
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: motion
  *3*:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/*3*
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1440
    snapshots:
      enabled: false
    record:
      enabled: false
version: 0.14
```

### Relevant log output

```shell
2024-06-20 10:19:39.811970094  [INFO] Starting NGINX...
./run.user: line 84: tempio: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
2024-06-20 10:19:39.848845777  [INFO] Service NGINX exited with code 127 (by signal 0)
2024-06-20 10:19:40.853179002  [INFO] Starting NGINX...
./run.user: line 84: tempio: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

### Operating system

Proxmox

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Lorex - Various
