### DISCUSSION TITLE
.13 to .14 beta upgrade - How to do it and should I?

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#12095] [General]
Hello all,

I've been looking at the features of the .14 beta and _really_ like what I'm seeing, particularly the time scrubbing for reviewing recordings.  

I've looked around a bit on how one would go about upgrading from .13 to .14 beta 3, but I'm not really finding any instructions on how to do that (do I just start over?) - I am running .13 on its own server in docker.

That said, should I?  If I just wait it out on .13 will it eventually auto update itself to .14 when it is ready for release?

Thanks!!

**Comment by NickM-27** [comment]
to update you just change the `image` in the docker compose / docker cli command to the beta image. If you waited until 0.14 was fully released you would need to run `docker compose pull` followed by `docker compose up -d` for it to restart the container with the updated image

**Reply by ReticentRobot** [reply]
Thank you!

**Reply by ReticentRobot** [reply]
If I switch to the beta now, would I use the same `docker compose pull` followed by `docker compose up -d` commands to update to new betas (and then eventually the final release)?  I've only ever used docker for frigate so I know next to nothing about how it works.

**Reply by ReticentRobot** [reply]
Alright I'm looking at the available images, and now I'm confused about which one I should be using:

- ghcr.io/blakeblackshear/frigate:0.14.0-beta3
- _ghcr.io/blakeblackshear/frigate:0.14.0-beta3-standard-arm64_
- ghcr.io/blakeblackshear/frigate:0.14.0-beta3-tensorrt
- ghcr.io/blakeblackshear/frigate:0.14.0-beta3-tensorrt-jp4
- ghcr.io/blakeblackshear/frigate:0.14.0-beta3-tensorrt-jp5
- ghcr.io/blakeblackshear/frigate:0.14.0-beta3-rk

I'm running the server on Ubuntu, and I have a usb coral and a pci m.2 coral.  I at least know I don't want the arm64 version - but what are the -tensorrt and -rk versions for?

**Reply by NickM-27** [reply]
if you don't know what image you should be running then you should just run the default image without any `-suffix`

**Reply by ReticentRobot** [reply]
Hmm... I changed the image to beta 3, but after restarting I'm still getting 0.13.2-6476F8A when I use Frigate.  Is there some other step I am missing?  This is my docker-compose.yml now:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3
    privileged: true
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/Recordings:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

**Reply by NickM-27** [reply]
what command did you run to restart?

**Reply by ReticentRobot** [reply]
I used the little docker whale icon that shows up at the top of Ubuntu desktop and selected Restart to restart docker.  I also had an update for the OS that needed a system restart, so I restarted the system as well.

**Reply by NickM-27** [reply]
right, you have to run `docker compose up -d` so that it rebuilds with the new image

**Reply by ReticentRobot** [reply]
Ah! Okay, sorry about that - I misunderstood your instructions, thought that was only if I was going to wait for 14 to release 😳. Thanks so much for the help on this, sorry about being such a pain.

**Reply by ReticentRobot** [reply]
I'm getting an error trying to do that, that isn't specifically Frigate - Error response from daemon: Mounts denied: 
The path /mnt/Recordings is not shared from the host and is not known to Docker.

Should I open a ticket\issue here for that problem - or do I need to go find a Docker support forum type place to get help with that?  Sorry again for the bother!

**Reply by NickM-27** [reply]
that doesn't seem right, maybe try `docker-compose` instead. Or, perhaps there is an "update container" button in the UI similar ot what you described earlier

**Reply by ReticentRobot** [reply]
Not sure how I ended up trying this, but it seems that having Docker Desktop running at all was causing the problem? After shutting it down and running `docker-compose up -d` everything seems good!

**Comment by cloudbr34k84** [comment]
@NickM-27 looking to try out the beta, using image: `ghcr.io/blakeblackshear/frigate:0.14.0-beta3` but when i rebuild it says
Error response from daemon: No such container: 00f8d98a1be21fbbc304850006ea442a2139676a4901cee24ed7c4aa131977e7

**Reply by NickM-27** [reply]
What command are you running? and what does the docker config look like?

**Reply by cloudbr34k84** [reply]
@NickM-27 
docker-compose down && docker-compose up -d
It pulled the the image, downloaded and everything
```
version: "3.9"
networks:
  traefik:
    external: true
services:  
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config/config.yml:/config/config.yml
      - /volume1/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs: #hkljljljlkjl
          size: 1000000000
    ports:
      - "5698:5000"
      - "8554:8554" # RTSP feeds
      - "5697:8555/tcp" # WebRTC over tcp
      - "5696:8555/udp" # WebRTC over udp
    environment:
      TZ: Australia/Brisbane
      FRIGATE_RTSP_PASSWORD: "xxxxxxxx"
      PLUS_API_KEY: "xxxxxx"
    labels:
      - "homepage.description=Is used as our homes security camera system. Its Integrated into Home Assistant for automations"    
      - "homepage.group=Docker Containers"
      # - "traefik.http.routers.${SVCName}.middlewares=auth@file"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.${SVCName}.loadbalancer.server.port=5000"
    extends:
          file: ../common-services-app.yml
          service: app
```
