### DISCUSSION TITLE
[Config Support]: config file not found after upgrading from 0.13 to 0.14

### DISCUSSION THREAD

**Discussion by njsmith983** [blakeblackshear/frigate#12106] [Config Support] [answered]
### Describe the problem you are having

I am running a linux system using docker compose. I wanted to try the new version of frigate so i stopped my current container and run these command to update the version.

docker compose pull
docker compose up -d

noticed i was getting a docker error and eventually the container doesnt start. I didnt make any changes to my config file location or the docker-compose.yml file, but for some reason the new version can't find the config file. 

frigate    | 2024-06-22T01:58:48.329018878Z 2024-06-21 20:58:48.328742853  [INFO] Preparing Frigate...
frigate    | 2024-06-22T01:58:48.329148205Z 2024-06-21 20:58:48.328895038  [ERROR] Frigate config file not found
frigate    | 2024-06-22T01:58:48.329162661Z 2024-06-21 20:58:48.328863570  [INFO] Starting NGINX...
frigate    | 2024-06-22T01:58:48.332390493Z 2024-06-21 20:58:48.332176219  [INFO] Preparing new go2rtc config...

Here is my docker compose file contents
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate_user/frigate_docker/config.yml:/config/
      - /mnt/frigate_mnt/storage:/media/frigate
      - /home/frigate_user/frigate_docker/frigateVol:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD:

Here is my location of my config file

/home/frigate_user/frigate_docker/config.yml

Am i missing something obvious? I am not sure why it wont find the config file. I even tried moving the config file into different folders to test and it never finds the config file. Thoughts?

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.85
  user: homeassistant
  password: 
database:
  path: /db/frigate.db
detectors:
  cpu1:
    type: cpu
    num_threads: 4
  cpu2:
    type: cpu
    num_threads: 4
#detectors:
#  coral:
#    type: edgetpu
#    device: usb
birdseye:
  enabled: true
  mode: continuous
cameras:
  CAMBARN1:
    ffmpeg:
      inputs:
      - path:
          rtsp://admin:@192.168.0.20:554/cam/realmonitor?channel=1?subtype=0
        roles:
        - record
      - path:
          rtsp://admin:@192.168.0.20:554/cam/realmonitor?channel=1?subtype=1
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      - dog
      - cat
      - car
      filters:
        person:
          threshold: 0.6
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 5
    motion:
      threshold: 30
```

### Relevant log output

```shell
frigate    | 2024-06-22T01:58:48.329018878Z 2024-06-21 20:58:48.328742853  [INFO] Preparing Frigate...
frigate    | 2024-06-22T01:58:48.329148205Z 2024-06-21 20:58:48.328895038  [ERROR] Frigate config file not found
frigate    | 2024-06-22T01:58:48.329162661Z 2024-06-21 20:58:48.328863570  [INFO] Starting NGINX...
frigate    | 2024-06-22T01:58:48.332390493Z 2024-06-21 20:58:48.332176219  [INFO] Preparing new go2rtc config...
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)
