### DISCUSSION TITLE
Getting lots of hits on code project

### DISCUSSION THREAD

**Discussion by rykr** [blakeblackshear/frigate#12100] [Detector Support]
### Describe the problem you are having

Getting lots of hits on code project on a camear where there is zero movement.  I've used debug view and motion boxes and I see zero evidence of anything moving but I get tons of these  in the code project log

13:48:46:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...a61a52) ['Found potted plant, chair, boat']  took 35ms
13:48:46:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...dbbe05) ['Found potted plant, boat, chair']  took 36ms
13:48:46:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...22203b) ['Found boat, potted plant, chair']  took 35ms
13:48:46:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...00c1f8) ['Found potted plant, potted plant, boat...']  took 36ms
13:48:46:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...1629f9) ['Found boat, potted plant, chair']  took 36ms

There is a potted plant, chair, and boat on the camera but they are not moving.  you see those 5 events above all happened in the same second.  It's like frigate is not checking for changed pixels first before sending for detection.

### Version

0.14.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.200
record:
  enabled: true
snapshots:
  enabled: true
motion:
  threshold: 30
  improve_contrast: false
detectors:
  deepstack:
    api_url: http://192.168.1.200:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.5 # seconds

go2rtc:
  streams:
    house_rear:
      - ffmpeg:rtsp://admin:18Gr33nacr3s@192.168.1.34:554/h264Preview_01_main#backchannel=0
    house_rear_sub:
      - ffmpeg:rtsp://admin:18Gr33nacr3s@192.168.1.34:554/h264Preview_01_sub#backchannel=0
    pool:
      - rtsp://admin:111111@192.168.1.164:554/h264Preview_01_main#backchannel=0
    pool_sub:
      - rtsp://admin:111111@192.168.1.164:554/h264Preview_01_sub#backchannel=0
    pool_rear:
      - ffmpeg:http://192.168.1.127/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=111111#video=copy#audio=copy#audio=opus
    pool_rear_sub:
      - ffmpeg:http://192.168.1.127/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=111111
  webrtc:
    candidates:
      - 192.168.1.200:8555
      - stun:8555

cameras:
  # ##### camera on back of house
  house_rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_rear
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/house_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 720
      height: 480
      fps: 10
    motion:
      mask:
        - 720,445,720,480,625,480,621,446
    objects:
      track:
        - person
        - dog

  ##### camera on back of pool house
  pool_rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool_rear
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 297,30,363,30,359,0,299,0
    objects:
      track:
        - person
        - car
        - truck
        - dog
        - motorcycle

  #### camera over pool
  pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 322,21,363,23,363,0,322,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 247,95,239,118,203,117,202,77
    detect:
      width: 640
      height: 480
      fps: 10

  ### camera in kitchen
#  kitchen:
#    ffmpeg:
#      hwaccel_args: preset-nvidia-h264
##      inputs:
 #     - path: rtsp://192.168.1.41/live0
 #       input_args: preset-rtsp-restream
 #       roles:
 #       - record
 #   motion:
 #     mask:
 #       - 1809,0,1814,63,1649,70,1649,0
 #   objects:
 #     track:
 #       - person
 #       - dog

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
None to speak of
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

Other
