### DISCUSSION TITLE
[Bug]: Automatic live view UI jitter

### DISCUSSION THREAD

**Discussion by terryma** [blakeblackshear/frigate#12110] [Report a Bug] [answered]
### Describe the problem you are having

With Automatic live view on, the view switching from live view to/from still image is jittery. The still image is slightly wider and has rounded corners, where the live view has sharp corners and slightly narrower. When you have lots of cameras on the same screen, the constant switching is jarring. Any way we can configure the exact dimension of both the live view and the static image so this stops happening? See the short clip I attached that demonstrates the issue around the 3 second mark.

Other than this, 0.14 has been simply amazing!

### Steps to reproduce

This appears to be the default behavior in the new UI.

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  host: 192.168.7.3
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
ffmpeg:
  hwaccel_args: preset-nvidia-h264
birdseye:
  enabled: false
objects:
  track:
    - person
    - vehicle
    - animal
model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    16: animal
    17: animal
    18: animal
snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 15
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
    objects:
      - person
      - vehicle
      - animal
go2rtc:
  streams:
    01_west_hall:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.101:554/cam/realmonitor?channel=1&subtype=0
    02_east_hall:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.102:554/cam/realmonitor?channel=1&subtype=0
    03_back_door:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.103:554/cam/realmonitor?channel=1&subtype=0
    04_front_door:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.104:554/cam/realmonitor?channel=1&subtype=0
    05_west_garage:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.105:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:05_west_garage#audio=opus
    06_rose_garden:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.106:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:06_rose_garden#audio=opus
    07_east_patio:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.107:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:07_east_patio#audio=opus
    08_east_parking_lot:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.108:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:08_east_parking_lot#audio=opus
    09_backyard_east:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.109:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:09_backyard_east#audio=opus
    10_west_patio:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.110:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:10_west_patio#audio=opus
    11_front_driveway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.111:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:11_front_driveway#audio=opus
    12_backyard_west:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.112:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:12_backyard_west#audio=opus
    13_perennial_garden:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.113:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:13_perennial_garden#audio=opus
    14_east_garage:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.114:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:14_east_garage#audio=opus
    15_pottery_room:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.115:554/h264Preview_01_main
      - ffmpeg:15_pottery_room#audio=opus
    16_front_gate:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.116:554/cam/realmonitor?channel=1&subtype=0
    18_laundry_room:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.118:554/h264Preview_01_main
      - ffmpeg:18_laundry_room#audio=opus
  webrtc:
    candidates:
      - 192.168.7.3:8555
      - stun:8555
cameras:
  01_west_hall:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/01_west_hall
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
    live:
      stream_name: 01_west_hall
    motion:
      mask: 0.664,0.028,0.665,0.093,0.967,0.09,0.967,0.031
  02_east_hall:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/02_east_hall
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.102:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          mask: 0.743,0.723,0.725,1,0.868,1,0.895,0.726
    live:
      stream_name: 02_east_hall
    motion:
      mask: 0.667,0.028,0.668,0.089,0.967,0.09,0.966,0.028
  03_back_door:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/03_back_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.103:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          mask: 0.617,0.541,0.695,0.472,0.659,0.629,0.639,0.826,0.587,0.817
    live:
      stream_name: 03_back_door
    motion:
      mask: 0.663,0.027,0.664,0.093,0.966,0.092,0.965,0.031
  04_front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/04_front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_OLD}@192.168.6.104:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
    live:
      stream_name: 04_front_door
    motion:
      mask:
        - 0.665,0.029,0.665,0.089,0.967,0.088,0.967,0.031
        - 0.107,0.071,0.101,0.265,0.168,0.265,0.174,0.075
  05_west_garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/05_west_garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.105:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
      filters:
        vehicle:
          mask:
            - 0,77,306,78,567,480,0,480
    live:
      stream_name: 05_west_garage
    zones:
      driveway:
        coordinates: 
          0.931,0.797,0.669,1,0.308,0.09,0.178,0.076,0.186,0.025,0.368,0.058,0.544,0.183,0.704,0.419
        inertia: 3
      parked_cars:
        coordinates: 0,480,0,185,42,104,100,39,248,44,532,480

    review:
      alerts:
        required_zones: driveway
    motion:
      mask: 0.724,0.032,0.724,0.089,0.976,0.086,0.976,0.031
  06_rose_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/06_rose_garden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.106:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 06_rose_garden
    motion:
      mask:
        - 0.723,0.031,0.725,0.088,0.978,0.087,0.979,0.032
        - 0.391,0.878,0.565,0.708,0.684,0.825,0.545,1,0.472,1
  07_east_patio:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/07_east_patio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.107:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 07_east_patio
    motion:
      mask: 0.727,0.031,0.728,0.087,0.975,0.084,0.975,0.031
  08_east_parking_lot:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/08_east_parking_lot
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.108:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
      filters:
        person:
          mask: 0.066,0.451,0.068,0.604,0.104,0.604,0.101,0.449
    live:
      stream_name: 08_east_parking_lot
    motion:
      mask:
        - 0.721,0.031,0.723,0.084,0.974,0.084,0.976,0.034
        - 0.809,0.115,0.801,0.494,1,0.562,1,0.115
        - 0,0,0,0.503,0.219,0.412,0.215,0
    zones:
      parked_cars:
        coordinates: 0.298,0.299,0.219,0.514,0.791,0.519,0.717,0.303
      driveway:
        coordinates: 0,0.513,0.807,0.522,1,0.601,1,0.869,0,0.807
    review:
      alerts:
        required_zones: driveway
  09_backyard_east:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/09_backyard_east
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.109:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 09_backyard_east
    motion:
      mask:
        - 0.725,0.032,0.725,0.084,0.975,0.084,0.975,0.036
        - 0.633,0,0.567,0.126,0.625,0.211,0.652,0.306,0.853,0.37,0.954,0.624,0.998,0.623,1,0
        - 0.766,0.91,0.879,0.844,1,0.89,1,1,0.761,1
  10_west_patio:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/10_west_patio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.110:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 10_west_patio
    motion:
      mask: 0.725,0.031,0.725,0.086,0.975,0.087,0.975,0.032
  11_front_driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/11_front_driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.111:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    live:
      stream_name: 11_front_driveway
    motion:
      mask:
        - 0.721,0.029,0.719,0.089,0.98,0.087,0.978,0.029
        - 0.271,0,0.172,0.196,0.16,0.354,0.21,0.492,0.323,0.545,0.413,0.541,0.52,0.483,0.55,0.331,0.545,0.197,0.488,0.088,0.435,0
  12_backyard_west:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/12_backyard_west
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.112:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 12_backyard_west
    motion:
      mask:
        - 0.729,0.039,0.728,0.087,0.976,0.083,0.976,0.037
        - 0,0.241,0.343,0.312,0.416,0.23,0.362,0,0,0
  13_perennial_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/13_perennial_garden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.113:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 13_perennial_garden
    motion:
      mask: 0.722,0.029,0.721,0.089,0.977,0.088,0.977,0.031
  14_east_garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/14_east_garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.114:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    live:
      stream_name: 14_east_garage
    motion:
      mask:
        - 0.725,0.029,0.727,0.086,0.972,0.084,0.973,0.029
        - 0,0.185,0.433,0.159,0.568,0.098,0.541,0,0,0
        - 0.908,0.082,0.802,0.23,0.96,0.339,1,0.198
    zones:
      parked_cars:
        coordinates: 0.583,0.357,0.759,0.319,1,0.638,1,0.773,0.929,0.892
      driveway:
        coordinates: 
          0.655,0.112,0.748,0.159,0.782,0.219,1,0.374,1,0.633,0.757,0.315,0.577,0.355,0.87,0.803,0.548,1,0,1,0,0.197
    review:
      alerts:
        required_zones: driveway
  15_pottery_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/15_pottery_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.115:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 15_pottery_room
    motion:
      mask: 0.629,0.031,0.63,0.108,0.985,0.109,0.982,0.033
  16_front_gate:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/16_front_gate
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.116:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    live:
      stream_name: 16_front_gate
    motion:
      mask:
        - 0.717,0.031,0.718,0.089,0.983,0.084,0.98,0.026
        - 0.38,0.205,0.398,0.503,1,0.344,1,0.097
        - 0.168,0,0.158,0.278,0.27,0.476,0.331,0.551,0.258,0.763,0,0.716,0,0
  18_laundry_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/18_laundry_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.6.118:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - animal
    live:
      stream_name: 18_laundry_room
    motion:
      mask: 0.625,0.032,0.627,0.105,0.983,0.104,0.983,0.036
  # This apparently drained the battery in a day
  # front_door:
  #   # Front door Nest Doorbell
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/front_door
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
  #   objects:
  #     track:
  #       - person
  #       - animal
version: 0.14
camera_groups:
  Indoor:
    order: 1
    icon: LuBedSingle
    cameras:
      - 01_west_hall
      - 02_east_hall
      - 03_back_door
      - 04_front_door
      - 18_laundry_room
  West:
    order: 2
    icon: LuArrowLeft
    cameras:
      - 05_west_garage
      - 06_rose_garden
      - 15_pottery_room
      - 13_perennial_garden
  East:
    order: 3
    icon: LuArrowRight
    cameras:
      - 08_east_parking_lot
      - 14_east_garage
  Front:
    order: 4
    icon: LuArrowDown
    cameras:
      - 11_front_driveway
      - 16_front_gate
  Back_(North):
    order: 5
    icon: LuArrowUp
    cameras:
      - 09_backyard_east
      - 10_west_patio
      - 12_backyard_west
      - 07_east_patio
  Main:
    order: 6
    icon: LuShieldAlert
    cameras:
      - 01_west_hall
      - 02_east_hall
      - 03_back_door
      - 05_west_garage
      - 04_front_door
      - 06_rose_garden
      - 07_east_patio
      - 08_east_parking_lot
      - 09_backyard_east
      - 10_west_patio
      - 11_front_driveway
      - 12_backyard_west
      - 13_perennial_garden
      - 14_east_garage
      - 16_front_gate
      - 15_pottery_room
```

### Relevant log output

```shell
No errors in logs
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

amcrest and reolink

### Any other information that may be helpful

https://github.com/blakeblackshear/frigate/assets/567259/2f88c567-0745-4d81-9d47-04b8d27882d5
