### DISCUSSION TITLE
V14 MQTT frigate/reviews. No change message on new zones and objects. Is this expected behaviour?

### DISCUSSION THREAD

**Discussion by ediguidedog** [blakeblackshear/frigate#12113] [General]
I'm seeing a number of review messages where objects just appear in the payload without any change message appearing. Below is an example 

I go form

```
payload_json:
    type: new
    before:
      id: 1719065610.161006-ursz8g
      camera: drive
      start_time: 1719065610.161006
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-drive-1719065610.161006-ursz8g.webp
      data:
        detections:
          - 1719065608.965215-pv82wa
        objects:
          - person
        sub_labels: []
        zones:
          - my_driveway
        audio: []
    after:
      id: 1719065610.161006-ursz8g
      camera: drive
      start_time: 1719065610.161006
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-drive-1719065610.161006-ursz8g.webp
      data:
        detections:
          - 1719065608.965215-pv82wa
        objects:
          - person
        sub_labels: []
        zones:
          - my_driveway
        audio: []
```

To 

```
payload_json:
    type: end
    before:
      id: 1719065610.161006-ursz8g
      camera: drive
      start_time: 1719065610.161006
      end_time: 1719065664.350035
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-drive-1719065610.161006-ursz8g.webp
      data:
        detections:
          - 1719065642.816897-4av83y
          - 1719065608.965215-pv82wa
          - 1719065621.171832-yf2rb3
        objects:
          - person
          - car
        sub_labels: []
        zones:
          - my_driveway
          - my_driveway_threshold
        audio: []
    after:
      id: 1719065610.161006-ursz8g
      camera: drive
      start_time: 1719065610.161006
      end_time: 1719065664.350035
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-drive-1719065610.161006-ursz8g.webp
      data:
        detections:
          - 1719065642.816897-4av83y
          - 1719065608.965215-pv82wa
          - 1719065621.171832-yf2rb3
        objects:
          - person
          - car
        sub_labels: []
        zones:
          - my_driveway
          - my_driveway_threshold
        audio: []
```

The car and additional zone just appeared in the end message and there was no change message received. I would have expected a change message to sent both when the car appeared and it entered into the driveway threshold

Do the new review messages work differently?

**Comment by NickM-27** [comment]
This is a bug that has been fixed since beta3

**Reply by ediguidedog** [reply]
Smashing thanks.  Is the intention that they work the same way as before? So a new message with nothing (object wise) 
 in the before section and then updates each time something changes (zone or object wise) and then an end when all done and dusted?

**Reply by ofcedwards** [reply]
`new` and `end` messages show the same data for before/after, but `update` messages will show the before/after differences

**Reply by ediguidedog** [reply]
When you say this has been fixed. Is the fix in build 9bbb88c as I'm still seeing oddities 
Take the following sequence

```
payload_json:
    type: new
    before:
      id: 1719129515.302688-xxlz6k
      camera: front
      start_time: 1719129515.302688
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-front-1719129515.302688-xxlz6k.webp
      data:
        detections:
          - 1719129514.696977-mwcxfk
        objects:
          - person
        sub_labels: []
        zones:
          - front_path
        audio: []
    after:
      id: 1719129515.302688-xxlz6k
      camera: front
      start_time: 1719129515.302688
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-front-1719129515.302688-xxlz6k.webp
      data:
        detections:
          - 1719129514.696977-mwcxfk
        objects:
          - person
        sub_labels: []
        zones:
          - front_path
        audio: []
```

This is a new message and I would have expected the before section to be devoid of zones yet they are there and this I believe from the reply above is intended behaviour (can anyone explain why we want it this way?) 
Four seconds later I get the next message 

```
  payload_json:
    type: update
    before:
      id: 1719129515.302688-xxlz6k
      camera: front
      start_time: 1719129515.302688
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-front-1719129515.302688-xxlz6k.webp
      data:
        detections:
          - 1719129514.696977-mwcxfk
        objects:
          - person
        sub_labels: []
        zones:
          - doorstep
          - front_path
        audio: []
    after:
      id: 1719129515.302688-xxlz6k
      camera: front
      start_time: 1719129515.302688
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-front-1719129515.302688-xxlz6k.webp
      data:
        detections:
          - 1719129514.696977-mwcxfk
          - 1719129518.318033-dg17zf
        objects:
          - person
        sub_labels: []
        zones:
          - doorstep
          - front_path
        audio: []
```

this time the before also has the doorstep zone in it whereas I would have expected the before section to mirror the after section from the previous message.  Again is this intended as if it is I can't get my head around it?

The final message is the end message 

```
payload_json:
    type: end
    before:
      id: 1719129515.302688-xxlz6k
      camera: front
      start_time: 1719129515.302688
      end_time: 1719129552.309915
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-front-1719129515.302688-xxlz6k.webp
      data:
        detections:
          - 1719129526.527381-oa1uz8
          - 1719129549.143716-x948ap
          - 1719129514.696977-mwcxfk
          - 1719129518.318033-dg17zf
          - 1719129540.299362-jicp33
          - 1719129530.507751-1q5iju
        objects:
          - person
        sub_labels: []
        zones:
          - side_path
          - doorstep
          - front_path
        audio: []
    after:
      id: 1719129515.302688-xxlz6k
      camera: front
      start_time: 1719129515.302688
      end_time: 1719129552.309915
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-front-1719129515.302688-xxlz6k.webp
      data:
        detections:
          - 1719129526.527381-oa1uz8
          - 1719129549.143716-x948ap
          - 1719129514.696977-mwcxfk
          - 1719129518.318033-dg17zf
          - 1719129540.299362-jicp33
          - 1719129530.507751-1q5iju
        objects:
          - person
        sub_labels: []
        zones:
          - side_path
          - doorstep
          - front_path
        audio: []
```

Now the side path has appeared (the actual order is correct. I walked up the path, past the door and up the side path) and again it's in the before section so I would have expected an earlier update message to add that but it just appears in the before section as part of the end message. 

My biggest problem with is is with the old events topics I don't really care whether it's a new or update message I simply check if the before zone list is empty and the after contains a zone and trigger on that and that way I get a single message event for each frigate event that involves someone on my land. This way is so much more complicated so what am I missing?
