### DISCUSSION TITLE
how to diagnose - unknown error in log

### DISCUSSION THREAD

**Discussion by sys1aeg** [blakeblackshear/frigate#12111] [Report a Bug]
### Describe the problem you are having

getting:
Tag
unknown
Message
[h264 @ 0xffff54029cb0] error while decoding MB 19 27, bytestream -36

### Steps to reproduce

view log

### Version

014-beta3

### Frigate config file

```yaml
mqtt:
  enabled: true
  # Required: host name
  host: 192.168.1.4
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: sys1aeg
  # Optional: 
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: 
auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 10.1.0.0/16 # <---- this is the subnet for the internal docker compose network

detectors:
  detector_name:
    type: edgetpu
tls:
  enabled: False
database:
  # The path to store the SQLite DB 
  path: /config/frigate.db

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: error
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

# Optional: Review configuration
# NOTE: Can be overridden at the camera level
review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - car
      - person
    # Optional: required zones for an object to be marked as an alert (default: none)


  # Optional: detections configuration
  detections:
    # Optional: labels that qualify as a detection (default: all labels that are tracked / listened to)
    labels:
      - car
      - person
    # Optional: required zones for an object to be marked as a detection (default: none)

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: false
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 1

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 5
      car: 5
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

go2rtc:
  streams:
    back_yard:
      - rtsp://admin:7@10.1.1.63:554//h264Preview_01_sub
  #
    ny_doorbell:
      - rtsp://admin2:7@10.1.1.13:554//h264Preview_01_sub
  #  
    front_house:
      - rtsp://admin:x@10.1.1.9:554//h264Preview_01_sub

  # 
#### ended here 
cameras:
#
#
  NY_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ny_doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    zones:
      nydoor:
        coordinates: 0.035,0.935,0.527,0.957,0.499,0.539,0.213,0.52
        objects:
          - car
          - person
    review:
      alerts:
        required_zones: nydoor
      detections:
        required_zones: nydoor
#######
    motion:
      mask: 0.174,0.578,0.15,0.858,0.501,0.865,0.355,0.589
  front_house:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_house
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    zones:
      nydriveway:
        coordinates: 0.303,0.201,0.116,0.63,0.564,0.982,0.79,0.958,0.855,0.303
        objects:
          - car
          - person
    review:
      alerts:
        required_zones: nydriveway
      detections:
        required_zones: nydriveway
#
    motion:
      mask: 0.499,0.362,0.342,0.744,0.737,0.976,0.841,0.415,0.472,0.329
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    zones:
      nybackyard:
        coordinates: 0.013,0.135,0.005,0.372,0.771,0.398,0.769,0.185
        objects:
          - car
          - person
    review:
      alerts:
        required_zones: nybackyard
      detections:
        required_zones: nybackyard
#  myrtle_beach_kitchen:
#    ffmpeg:
#      inputs:
#       - path: rtsp://127.0.0.1:8554/myrtle_beach_kitchen
#         input_args: preset-rtsp-restream  
#         roles:
#           - detect
#           - record
#    zones:
#      sckitchen:
#        coordinates: 0.012,0.272,0.023,0.796,0.983,0.82,0.991,0.528,0.974,0.302
#        objects:
#          - car
#          - person
#    review:
#      alerts:
#        required_zones: sckitchen
#      detections:
#        required_zones: sckitchen
######################################
#  myrtle_beach_garage:
#    ffmpeg:
#      inputs:
#        - path: rtsp://127.0.0.1:8554/myrtle_beach_garage
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#            - record
#    zones:
#      scgarage:
#        coordinates: 0.071,0.236,0.071,0.913,0.721,0.917,0.728,0.177
#        objects:
#          - car
#          - person
#    review:
#      alerts:
#        required_zones: scgarage
#      detections:
#        required_zones: scgarage
#
    motion:
      mask: 0.052,0.156,0.065,0.337,0.743,0.34,0.754,0.156
  myrtle_beach_front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/myrtle_beach_front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    zones:
      scfrontdoor:
        coordinates: 0.332,0.048,0.324,0.983,0.785,0.976,0.727,0.235
        objects:
          - car
          - person
    review:
      alerts:
        required_zones: scfrontdoor
      detections:
        required_zones: scfrontdoor
#
#  myrtle_beach_bedroom:
#    ffmpeg:
#      inputs:
#        - path: rtsp://127.0.0.1:8554/myrtle_beach_bedroom
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#            - record
#    zones:
#      scmasterbed:
#        coordinates: 0.05,0.149,0.044,0.866,0.82,0.828,0.801,0.116
#        objects:
#          - car
#          - person
#    review:
#      alerts:
#        required_zones: scmasterbed
#      detections:
#        required_zones: scmasterbed
    motion:
      mask: 0.09,0.276,0.138,0.89,0.796,0.89,0.753,0.262
version: 0.14
###
```

### Relevant log output

```shell
Tag
unknown
Message
[h264 @ 0xffff54029cb0] error while decoding MB 19 27, bytestream -36
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

amcrest, reolink

### Any other information that may be helpful

don't know how to diagnose problem
