### DISCUSSION TITLE
[Bug]: Live view of individual camera isn't working

### DISCUSSION THREAD

**Discussion by artinbastani** [blakeblackshear/frigate#12114] [Report a Bug] [answered]
### Describe the problem you are having

I have 0.14 beta3 set up via the home assistant add on and its recording and my home view works fine but I cannot view individual cameras from the homepage.

### Steps to reproduce

I click on frigate from the home assistant sidebar. Live view loads fine and I can see all my cameras and if there's motion it plays the video with a higher frame rate. But if I click on a camera to view it, that screen is stuck loading.

### Version

0.14 beta 3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.8
  user: mqttclient
  password: XXXXXXXXXXXXXXXX

logger:
  # Optional: default log level (default: shown below)
  default: info

#ui:
# use_experimental: true

birdseye:
  enabled: true
  restream: true
  mode: motion

detectors:
#  coral:
#    type: edgetpu
#    device: usb
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  width: 1280
  height: 720
  fps: 5

objects:
  track:
    - person
    - car
    - dog

live:
  quality: 1

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as m>
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection m>
  # The value should be between 1 and 255.
  threshold: 30
  improve_contrast: false

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi

cameras:
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/livingroom?mp4
          roles:
            - detect
    motion:
      mask:
        - 1252,0,1252,35,912,35,909,0
    detect:
      enabled: true
    objects:
      track:
        - person

  breakfastnook:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/breakfastnook?mp4
          roles:
            - detect
    motion:
      mask:
        - 1250,0,1256,37,919,42,918,0
    detect:
      enabled: true
    objects:
      track:
        - person

  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/kitchen?mp4
          roles:
            - detect
    motion:
      mask:
        - 1255,0,1252,41,908,43,908,0
    zones:
      kitchenonly:
        coordinates: 74,296,733,244,1122,498,1000,720,154,720
    detect:
      enabled: true
    objects:
      track:
        - person

  playroom:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/playroom?mp4
          roles:
            - detect
    motion:
      mask:
        - 1249,0,1249,38,912,41,912,0
    detect:
      enabled: true
    objects:
      track:
        - person

  wyze:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/wyze?mp4
          roles:
            - detect
    motion:
      mask:
        - 1256,670,1256,720,911,720,911,671
    detect:
      enabled: true
    objects:
      track:
        - person

  circle:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/circle?mp4
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/driveway?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/driveway?mp4
          roles:
            - record
    motion:
      mask:
        - 0,0,0,201,760,88,1224,205,1280,0
    zones:
      drivewayonly:
        coordinates: 135,594,307,720,1093,720,1244,235,1196,198,849,114,709,86,0,249
    detect:
      enabled: true
    snapshots:
      enabled: true
      retain:
        default: 7
      required_zones:
        - drivewayonly
    record:
      enabled: true
      events:
        retain:
          default: 1
          mode: active_objects
        pre_capture: 2
        post_capture: 2
        objects:
          - person
          - car

    review:
      alerts:
        required_zones:
          - drivewayonly
  front:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/front?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/front?mp4
          roles:
            - record
    motion:
      mask:
        - 1237,26,1234,57,820,59,818,29
    zones:
      frontmyyard:
        coordinates: 347,720,1280,720,1280,226,954,131,547,70,178,136,0,96,86,323
    detect:
      enabled: true
    snapshots:
      enabled: true
      retain:
        default: 7
      required_zones:
        - frontmyyard

  ethan:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/ethan?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/ethan?mp4
          roles:
            - record
    motion:
      mask:
        - 911,67,1240,65,1238,21,912,25
    detect:
      enabled: true
    objects:
      track:
        - person
    snapshots:
      enabled: true
      retain:
        default: 1
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 3
          mode: active_objects
        pre_capture: 2
        post_capture: 2

  eva:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/eva?mp4
          roles:
            - detect
            - audio
        - path: rtsp://192.168.1.8:8554/eva?mp4
          roles:
            - record
    motion:
      mask:
        - 1238,25,1232,59,913,59,920,24
    zones:
      evacrib:
        coordinates: 356,720,974,692,941,484,389,478
    detect:
      enabled: true
    objects:
      track:
        - person
    snapshots:
      enabled: true
      retain:
        default: 1
      required_zones:
        - evacrib
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 3
          mode: active_objects
        pre_capture: 2
        post_capture: 2
    audio:
      enabled: false
      listen:
        - crying
        - scream
        - speech
        - yell
    review:
      alerts:
        required_zones:
          - evacrib
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/doorbell?mp4
          roles:
            - detect
    motion:
      mask:
        - 21,424,401,435,609,433,913,416,1123,393,1280,364,1280,0,0,0
    zones:
      doorbell_lawn:
        coordinates: 0,720,1280,720,1280,414,1073,397,496,443,97,427
    detect:
      enabled: true
    birdseye:
      mode: motion

  basementdoor:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/basementdoor_sub?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/basementdoor?mp4
          roles:
            - record
    motion:
      mask:
        - 1242,21,1233,59,886,57,891,26
    detect:
      enabled: true
    objects:
      track:
        - person
    birdseye:
      mode: motion

  basementmain:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/basementmain_sub?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/basementmain?mp4
          roles:
            - record
    motion:
      mask:
        - 1239,25,1235,63,904,62,905,30
    detect:
      enabled: true
    objects:
      track:
        - person
    birdseye:
      mode: motion

  garageleft:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/garageleft_sub?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/garageleft?mp4
          roles:
            - record
    motion:
      mask:
        - 911,56,1237,65,1243,31,904,31
    detect:
      enabled: true
    snapshots:
      enabled: true
      retain:
        default: 1
    birdseye:
      mode: motion

  garageright:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/garageright_sub?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/garageright?mp4
          roles:
            - record
    motion:
      mask:
        - 897,55,1237,64,1241,28,900,25
    detect:
      enabled: true
    birdseye:
      mode: motion

  patio:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/patio_sub?mp4
          roles:
            - detect
        - path: rtsp://192.168.1.8:8554/patio?mp4
          roles:
            - record
    motion:
      mask:
        - 900,63,1244,61,1240,22,897,31
    detect:
      enabled: true
version: 0.14
camera_groups:
  Outside:
    order: 1
    icon: LuCar
    cameras:
      - garageright
      - garageleft
      - front
      - driveway
      - doorbell
```

### Relevant log output

```shell
even with debug logging on i'm not seeing anything
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

mostly amcrests
