### DISCUSSION TITLE
[Config Support]: Frigate is causing my network latency to spike when enabled.

### DISCUSSION THREAD

**Discussion by asteriqz** [blakeblackshear/frigate#12121] [Config Support]
### Describe the problem you are having

Hoping to get some help with my config - when frigate is running, I get high latency throughout my network - I believe I need to use sub streams for detection? although unsure where in the config to include this. Could someone please help me out on this please.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: a0d7b954-emqx
  user: frigate
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -tag:v hvc1

database:
  path: /config/frigate.db
  
go2rtc:
  streams:
    username: "admin"
    password: "xxx"
    driveway: 
      - rtsp://admin:xxx@192.168.0.211:554/h265Preview_01_main
      - "ffmpeg:driveway#video=h264#hardware"
    backyard:
      - rtsp://admin:xxx@192.168.0.210:554/h265Preview_01_main
      - "ffmpeg:backyard#video=h264#hardware"
    # sideyard:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.104:554/h265Preview_01_main
    #  - "ffmpeg:sideyard#video=h264#hardware"
    #doorbell:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.108:554/h264Preview_01_main
    #viewcam:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.105:554/h265Preview_01_main
    #  - "ffmpeg:viewcam#video=h264#hardware"

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
           min_score: 0.78   
        car:
           min_score: 0.78
    zones:
     driveway_area:
      coordinates: 4096,1536,4096,615,2860,530,2056,482,1597,681,130,1536

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
           min_score: 0.78 # min score for object to initiate tracking (default: 0.5
    zones:
     backyard_area:
      coordinates: 0,1536,4096,1536,4096,0,0,0
    motion:
       mask:
        - 2024,55,1884,245,1812,408,1578,526,1300,570,898,501,892,391,675,388,667,223,881,182

record:
 enabled: True
 retain:
  days: 7
  mode: motion
 events:
  required_zones:
    - driveway_area
    - backyard_area
  retain:
   default: 14
   mode: active_objects
snapshots:
  enabled: True

rtmp:
  enabled: false

birdseye:
  enabled: False
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 4
```

### Relevant log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)
