### DISCUSSION TITLE
[Question]: Stream Handling Architecture from Camera through to HA

### DISCUSSION THREAD

**Discussion by jamesonuk** [blakeblackshear/frigate#12123] [Ask A Question] [answered]
### What is your question:

My head is spinning a bit trying to piece together what is actually going in in Frigate.   The documentation is pretty decent but like most OSS it has largely been written by people who understand the background mechanics and lacks a little of the background and reasoning behind things.   Quite happy to try and get involved but I am struggling to get my head round the moving parts.   I spent a good few years working on HTPC software and have a good understanding of streams, transcoding, ffmpeg etc. but my head is doing somersaults trying to apply this here.

When I first setup Frigate I added two cameras that both had two RTSP streams (high and low res) and I didn't configure go2rtc or anything and I understood that.   Frigate connected to the stream I set to detect and recording but as I have extended my setup for audio and to integrate with HA I have lost of bit of what gets processed where.

AIUI I have done the right thing and setup go2rtc streams pointing at my camera streams and then pointed the cameras at the go2rtc streams.   Without any additional config this just means that the go2rtc is connecting to the camera and passing through the streams as is (so should be pretty low on resources) and HA and and Frigate are both reading the go2rtc streams.

I had some fun getting audio to work on one of the cameras (original camera source is PCM) but I managed to get this working by adding 
```
      - "ffmpeg:<stream_name>#audio=aac#audio=opus"
```
to the stream definition and then realising that I also needed to add
```
      output_args:
        record: preset-record-generic-audio-aac 
```
to the camera definition for audio to be included in recordings (which works whether or not go2rtc has the transcoding option set as I think go2rtc converts PCM to AAC automatically???).
With both audio options set I can get both tracks in VLC from go2rtc adding `?video=h264&audio=aac&audio=opus` but without any options I either see no audio at all or just the AAC track.

I am right in thinking by defining the audio transcoding in the go2rtc stream this will be passed downstream but you still need to tell Frigate to output audio in recordings because by default it simply ignores any audio tracks?

Then when I add HA into the mix I get an integration which adds a camera but I am not sure which stream is mapped to the camera and no matter what I do I cannot get audio in HA.   The HA integration seems very black box and entities appear but they don't directly to what is configured in Frigate so it is difficult to track things back.

So ultimately I was looking for details of how streams are handled (and if that is different depending on whether go2rtc is configured or not).    This will probably help me figure out how to get audio in HA but I am currently adding random ffmpeg presets and options  My goal is to have audio in recordings and live stream from one camera (a Tapo C200 with H.264 video and PCM audio) but I want to understand it from end to end rather than just adding `x` or `y` to the config.

Not sure if I missed some high levels documentation or whether anything similar exists but any help to clarify what is going on would be appreciated.

I am really looking for a high level understanding that what I need to change in my config but for info the relevant bits are https://pastebin.com/fsEynByU (plus the two bits above for transcoding and recording  AAC)

**Comment by NickM-27** [comment]
1. by default go2rtc always passes the audio through transparently as it receives it. However, frigate itself only gets audio if AAC audio is enabled. Because your camera outputs PCM by default, the most efficient setup would actually be `- "ffmpeg:<stream_name>#audio=copy#audio=aac"` as this will create an aac track and keep the PCM track (which is usable for MSE and WebRTC streams)
2. If you are not using go2rtc then there is no stream in HA, just a snapshot that updates once per second. The HA integration only uses an actual stream when go2rtc is setup, and it looks for a `stream` which has a matching `camera` name. This is how it knows automatically that they are related. In your case the camera is named `test` and you have `test_high` and `test_low` so there are no matching streams, HA will not get any stream. If you want the high res stream to be used in HA for example then you would do

```
go2rtc:
  streams:
    test:
      - rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@test-tapo-camera/stream1
    test_low:
      - rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@test-tapo-camera/stream2
 
ffmpeg:
  hwaccel_args: preset-vaapi
 
cameras:
  test:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/test_low
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/test
          input_args: preset-rtsp-restream
          roles:
            - record
```
