### DISCUSSION TITLE
error="streams: wrong user/pass" on Go2RTC

### DISCUSSION THREAD

**Discussion by ldm95450** [blakeblackshear/frigate#12133] [Config Support]
### Describe the problem you are having

Hi,
I received an new TapoC210 and I obtained the error : error="streams: wrong user/pass" using go2rtc streams ( "go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4") or directly using a rtsp stream without go2rtc. The credential are correct. I've installed frigate on my Synology NAS using docker.
I installed go2rtc (go2rtc platform=linux/arm64 revision=a4885c2 version=1.9.4) in my homeAssistant environment on raspberry 3B  and I hadn't issue, C210 is operational.
I see that the paltform is different (amd64/arm64). Could it be the reason ?
Can you help me ?

Regards.. 

### Steps to reproduce

just configure my C210 in frigate with the configuration editor and restart.

### Version

0.14.0 Beta 3

### Frigate config file

```yaml
go2rtc:
  log:
    level: debug
  streams:
    camsalon:
      - onvif://name:pwd@192.168.1.93:2020?subtype=profile_2
    camsalon_sub:
      - onvif://name:pwd@192.168.1.93:2020?subtype=profile_1
cameras:
  camsalon:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/camsalon_sub
          roles:
            - detect
```

### Relevant log output

```shell
go2rtc log :
2024-06-24 09:55:38 onvif new uri=rtsp://name:pwb@192.168.1.93:554/stream1
Warning 2024-06-24 09:55:38 rtsp error="streams: wrong user/pass" stream=camsalon_sub

Frigate log

2024-06-24 09:57:28 watchdog.camsalon The following ffmpeg logs include the last 100 lines prior to exit.
Error 2024-06-24 09:57:28 ffmpeg.camsalon.detect [rtsp @ 0x55ebd04f6100] method DESCRIBE failed: 404 Not Found
Error 2024-06-24 09:57:28 ffmpeg.camsalon.detect rtsp://localhost:8554/camsalon_sub: Server returned 404 Not Found
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

TAPO C210

### Any other information that may be helpful

I already own 2 TapoC210 but I discovered that the manufacturers are differents but use same FW version. These C210 work without any problem.
I had same result with 0.13.2
