### DISCUSSION TITLE
[Detector Support]: Object detection comically bad with OpenVino?

### DISCUSSION THREAD

**Discussion by DReffects** [blakeblackshear/frigate#12134] [Detector Support] [answered]
### Describe the problem you are having

Hello there!

first of all: this project is awesome! I've discovered it a few days ago and am blown away by its possibilities.
Unfortunately I am struggeling with the openvino Object Detection. It is comically bad. 

I've set up frigate according to the recommendations from the docs:

- frigate 0.13.2 in home assistant
- detection streams 1280x720 @5fps 

I've attached relevant config excerpts below. 

Within the last 24 hours I've got:

- 24x robotic lawnmower as person
![image](https://github.com/blakeblackshear/frigate/assets/48361672/73e7a939-015a-4521-80b8-97bd9a8bbfe5)
![image](https://github.com/blakeblackshear/frigate/assets/48361672/8557e621-e3cf-4314-841a-2a294b99b628)

- 4x trampoline as dog
![image](https://github.com/blakeblackshear/frigate/assets/48361672/d2218112-5a21-49fb-a88f-e7b05b6cc76c)

- 2x parts of a stroller as person
![image](https://github.com/blakeblackshear/frigate/assets/48361672/a9878b98-2943-4364-8604-24840cd219ad)

Is this to be expected? Is there a better detection model? Am I missing crucial settings?

Thanks! :-)

### Version

0.13.2

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac  

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


objects:
  track:
    - person
    - cat
    - dog
```

### docker-compose file or Docker CLI command

```yaml
installed via home assistant
```

### Relevant log output

```shell
nothing in the logs
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

OpenVino

**Comment by NickM-27** [comment]
This has to do with the model, all openvino or coral does is run the model. The default model is not trained on camera images as it is a demo model trained on the coco dataset (examples of images in the coco dataset https://imgur.com/a/CNImofJ)

Frigate offers many filters that you can use to filter out false positives like this. https://docs.frigate.video/configuration/object_filters

There is also Frigate+ which are paid models, purpose built and fine tuned on your cameras to be more accurate https://docs.frigate.video/plus/

**Reply by blakeblackshear** [reply]
Though it's worth pointing out that Frigate+ doesn't yet support OpenVino.

**Reply by jackez** [reply]
Using this opportunity to ask if there's any timeline for Frigate+ OpenVino support? Lack of OpenVino support is probably the only reason why I'm still not subscribed for Frigate+.

**Reply by NickM-27** [reply]
It is currently being worked on https://github.com/orgs/frigate-nvr/projects/2/views/1

**Reply by DReffects** [reply]
Thanks for the clarification
I am fixed to OpenVino at the moment. Is there a list of available models i can run locally with openvino?

**Reply by NickM-27** [reply]
There are multiple listed in the docs, but some have to be built by the user https://docs.frigate.video/configuration/object_detectors#openvino-detector

**Reply by DReffects** [reply]
Thanks. I meant like a comparison list or feature table. All those model names mean nothing to me ;-) 

Is "OpenVino" an "execution engine" for OpenVino-compatible models?
If so, are Coral-Models compatible with OpenVino? (someone linked a huge list below)

Looking at https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public - is there some kind of explanation for all those models? (like a freature comparison between h264, h265, av1)

How do I know if a model is compatibel with Frigate? (Docs state 'Other YOLO variants are not officially supported/tested.')
What makes a model frigate-compatible?
Yolox-Tiny 

And how does the matching of the objects like doc, cat, brocoli work in regards to the models? is there an unwritten consent on how the objects are called or do I need to match the objects to the model somehow?

Sorry for the probably dumb questions. I am way removed from all the ai stuff and most of the terminology is all chinese to me.

**Comment by Xtian85** [comment]
You could try as a model Yolonas-s, I have noticed a fair improvement over the basic model

**Reply by DReffects** [reply]
Thank you for the suggestion! Can you provide a very short overview on how to install this? 
Is there a "model database" somewhere with different models altogether? I am rather new to this and was under the impression, that the "detection engine" itself was part of frigate, not something external. :)

**Reply by NickM-27** [reply]
You can find quite a few different models over at https://github.com/google-coral/test_data/ for example, and many other architectures in different repos as well

**Reply by NickM-27** [reply]
Frigate still runs the model locally, but it can accept many different formats of model depending on what detector you are using

**Reply by DReffects** [reply]
@NickM-27 ooof thats an extensive list. Do I need a coral accellerator for those models or are these models compatible with openvino?

I think I am missing the basic concept behind this and how all comes together in frigate :-D

**Reply by Xtian85** [reply]
> Thank you for the suggestion! Can you provide a very short overview on how to install this? Is there a "model database" somewhere with different models altogether? I am rather new to this and was under the impression, that the "detection engine" itself was part of frigate, not something external. :)

Actually I simply followed the guide at this point.
[https://deploy-preview-11419--frigate-docs.netlify.app/configuration/object_detectors#yolo-nas](https://deploy-preview-11419--frigate-docs.netlify.app/configuration/object_detectors#yolo-nas)
Basically you have to run Collab's notebook and download the model that is processed. Then you put it in your config folder and insert the part of the code that's in the guide.
I assumed though that you are using version 0.14 which is in beta, I don't think it works on version 0.13...

**Reply by DReffects** [reply]
Thanks! Unfortunately the link goes to a 404 error page. 

Is an upgrade to 0.14 beta recommended? I have no fallback recording method just now.

**Reply by Xtian85** [reply]
> Thanks! Unfortunately the link goes to a 404 error page.
> 
> Is an upgrade to 0.14 beta recommended? I have no fallback recording method just now.

Link corrected now

**Reply by DReffects** [reply]
Thanks!!
How to yolo-nas and yolox_tiny compare?

**Reply by DReffects** [reply]
> Actually I simply followed the guide at this point. https://deploy-preview-11419--frigate-docs.netlify.app/configuration/object_detectors#yolo-nas Basically you have to run Collab's notebook and download the model that is processed. Then you put it in your config folder and insert the part of the code that's in the guide. I assumed though that you are using version 0.14 which is in beta, I don't think it works on version 0.13...


@Xtian85 unfortunately the script fails with:

![image](https://github.com/blakeblackshear/frigate/assets/48361672/66bec580-ba12-4608-98a0-1e6679b18b67)

I am unsure what to do about it. Can you help out? :-)

Ok, seems like adding "--use-deprecated=legacy-resolver" to the first pip install command solves the dependencies error.

**Reply by NickM-27** [reply]
numpy is out of date

**Reply by DReffects** [reply]
I've managed to download the model from colab - where do i put it? I've placed it via SSH at /homeassistant where the firgate.yaml file is located but i am getting an 

File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 26, in __init__
2024-06-30 13:06:56.651146349      self.ov_model = self.ov_core.read_model(detector_config.model.path)
2024-06-30 13:06:56.651193655  RuntimeError: Model file None cannot be opened!

Error and frigate quits. 

The /config directory seems to be somewhere else. can you point me in the right direction? :)

**Reply by NickM-27** [reply]
There should be a model_cache folder next to frigate.yaml

**Reply by DReffects** [reply]
I've repasted the yaml, it now seems to work.

Unfortunately now:
2024-06-30 13:15:17.013110863    value is not a valid enumeration member; permitted: 'ssd', 'yolox', 'yolov5', 'yolov8' 

This seems to be an limitation of verison 0.13, yes?

**Reply by NickM-27** [reply]
yes, yolo nas is only available in 0.14

**Reply by DReffects** [reply]
Thanks for the Heklp! I've upgraded to 0.14 and sucessfully enabled yolo

Is it to be expected, that the Hardware Statistics do not work atm? I am getting GPU load 0% (Intel N100 System)
All other metrics also produce no data. Power consumtion is noticeably higher then before.

**Reply by ubawurinna** [reply]
Does statistics work with the MobileNetv2-SSD model on your Frigate 0.14?
Which version of Frigate 0.14 did you use ? You can try ghcr.io/blakeblackshear/frigate:dev-f9e1ad2
Your yolo_nas_s.onnx file should have a size of about 46MB

**Reply by DReffects** [reply]
@ubawurinna 
How do I get and intall the MobileNetv2-SSD model?

I am using the "latest Version" that the beta channel installer for Home Assistant just provided: (0.14.0-4e5a6eb)

yolo_nas_s.onnx is 46.5 MB in Size :-)

**Reply by ubawurinna** [reply]
The MobileNetv2-SSD model is integrated into Frigate.
In the Frigate configuration, comment out or replace your model with this one:
```
model:
  model_type: ssd
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

**Reply by DReffects** [reply]
@ubawurinna oh sorry, i wasn't aware of the name of the "default" model. 
No stats with this model either. :-(

**Reply by ubawurinna** [reply]
So the problem is not with the model

You can check your configuration against this functional setup:
```
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

go2rtc:
  streams:
    camera1:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    camera1_sub:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1_sub
          roles:
            - detect
    live:
      stream_name: camera1
```
