### DISCUSSION TITLE
[Question]: How do you configure separate detect and record go2rtc streams for a single camera, with auto-naming?

### DISCUSSION THREAD

**Discussion by victorhooi** [blakeblackshear/frigate#12136] [Ask A Question]
### What is your question:

The [Frigate documentation page for go2rtc](https://docs.frigate.video/guides/configuring_go2rtc) mentions this:
> If you set the stream name under go2rtc to match the name of your camera, it will automatically be mapped and you will get additional live view options for the camera. Avoid changing any other parts of your config at this step.

However, how does this work if you have multiple streams (e.g. detect vs record) for a given camera?

For example:

```
  bedroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://user:password@192.168.1.5:554/axis-media/media.amp?streamprofile=hdwitnessSecondary&event=on
          roles:
            - detect
        - path: 
            rtsp://user:password@192.168.1.5:554/axis-media/media.amp?streamprofile=hdwitnessPrimary&event=on
          roles:
            - record
    # detect:
    #   width: 640 # <- optional, by default Frigate tries to automatically detect resolution
    #   height: 360 # <- optional, by default Frigate tries to automatically detect resolution
```
I could have a single go2rtc stream like this:
```
go2rtc:
  streams:
    bedroom:
      - rtsp://user:password@192.168.1.5:554/axis-media/media.amp?streamprofile=hdwitnessSecondary&event=on
```

However, should I put in the detect or the record stream? And will Frigate automatically pick it up if the streams are named the same? ("bedroom" in this case).
