### DISCUSSION TITLE
[Support]: HA Notification for a single Tag

### DISCUSSION THREAD

**Discussion by H1ghSyst3m** [blakeblackshear/frigate#12145] [General Support] [answered]
### Describe the problem you are having

Hi guys, I have a question about Notifications.

I want to enable notification for Frigate events, but I only want it to send Notification when as example only "cat" event occurred.
I already read the docs, but could only see an option for all events and not for a single one.

Can someone please help me?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.188.200
  user: mqtt-user
  password: ++++++++++
  topic_prefix: frigate

ui:
  live_mode: mse

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

objects:
  track:
  - person
  - cat
  filters:
    person:
      min_score: .85
      threshold: .5
      min_area: 5000
      max_area: 100000
    cat:
      min_score: .85
      threshold: .3

birdseye:
  enabled: true
  mode: continuous

record:
  sync_recordings: true

go2rtc:
  streams:
    Flur_main:
    - rtsp://tcamflur:+++++++++++++@192.168.188.44:554/stream1
    - ffmpeg:Flur_main#audio=aac
    Flur_sub:
    - rtsp://tcamflur:+++++++++++++++@192.168.188.44:554/stream2
    - ffmpeg:Flur_sub#audio=aac
    Eingang_main:
    - rtsp://admin:+++++++++@192.168.188.201:554/Streaming/Channels/101
    - ffmpeg:Eingang_main#audio=aac
    Eingang_sub:
    - rtsp://admin:+++++++++@192.168.188.201:554/Streaming/Channels/102
    - ffmpeg:Eingang_sub#audio=aac

cameras:
  Flur_Kamera:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Flur_main?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Flur_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 8
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 3
    live:
      stream_name: Flur_sub

    motion:
      mask:
      - 415,0,0,0,0,28,413,32

  Eingang_Kamera:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Eingang_main?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Eingang_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 8
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 3
    live:
      stream_name: Eingang_sub

    motion:
      mask:
      - 399,36,23,37,23,69,400,68
      - 927,669,1039,673,1039,641,924,639
model:
  path: plus://+++++++++
```

### Relevant log output

```shell
No log available
```

### FFprobe output from your camera

```shell
I think its not needed
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision

**Comment by NickM-27** [comment]
assuming you are using home assistant, you would just add a condition that the label is `cat`

**Reply by H1ghSyst3m** [reply]
Hi thanks for your fast reply. 

I tried it with condition. But I can't make it work with a specific camera. 
When I only make the label, then it works, but then it sends notification for cat detections from all cameras.
I only want to send notification, when it cat is on the camera eingang_kamera

I tried this:

```
alias: Notify of cat detection
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'cat' }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['camera'] == 'eingang_kamera' }}"
action:
  - service: notify.mobile_app_mi12pro
    data:
      message: A cat was detected at the entrance.
      data:
        image: >-
          https://mypublicurl.eu/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
```
