### DISCUSSION TITLE
[Support]: Frigate detecting 2 separate events which start and end and then stitches them up to 1 event.

### DISCUSSION THREAD

**Discussion by teymur1988** [blakeblackshear/frigate#12144] [General Support] [answered]
### Describe the problem you are having

I'm pretty happy with my frigate installation but here is a little thing that keeps bothering me. I live in an apartment bulding and I have a front door camera pointing at elevators. Here is the thing I'm getting:

I have an automation setup in homeassistant which is triggered when a frigate event ends and grabs the event id and sends me a notification with full link to the video or snapshot. Sometimes what happens is I get a notification with a link to a short video like 8-10 seconds and it ends with elevator doors opening and person just about to come out. Then I get a second notification with a link to a short video about same length where person is exiting the elevator and going to their door that's where the video ends. Finally I'm getting the 3rd notification with a link to the full video which is from the beginning to the end. Interestingly enough, after I get the last notification with a full video the first 2 links that I got with short videos no longer work, as that event is gone from the system. My question is that how do I configure it so that it sends me the full event and not its parts. Here is the automation. Any help is appreciated. Thank you. If any other information is needed I'll be happy to provide.

Here is my automation:

```
alias: 1.4 Doorbell Frigate Motion Detect  --- > Snap and Video Telegram and mobile
description: Frigate Detections will be sent to telegram and Mobile App
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: "{{ value_json.type }}"
    id: started
  - platform: mqtt
    topic: frigate/events
    payload: end
    value_template: "{{ value_json.type }}"
    id: finished
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['before']['camera'] == 'frigate_doorbell' }}"
        enabled: true
      - condition: template
        value_template: "{{ trigger.payload_json['before']['camera'] == 'frigate_xatai' }}"
        enabled: true
    enabled: true
action:
  - variables:
      camnamesmall: "{{trigger.payload_json.before.camera.split('_')[1]}} camera"
      camnamecapital: "{{camnamesmall.capitalize()}}"
      label: "{{trigger.payload_json.after.label}}"
      eventid: "{{trigger.payload_json.after.id}}"
      starttimeunix: "{{trigger.payload_json.before.start_time|int}}"
      endtimeunix: "{{trigger.payload_json.after.end_time|int}}"
      videolength: "{{ (endtimeunix - starttimeunix)|timestamp_custom('%Mm %Ss') }}"
      startdate: "{{starttimeunix|timestamp_custom('%d-%B-%Y')}}"
      starttime: "{{starttimeunix|timestamp_custom('%H:%M:%S')}}"
      startweekday: "{{starttimeunix|timestamp_custom('%A')}}"
      link: https://mydomain.com/api/frigate/notifications/{{eventid}}
      imagelink: "{{link}}/snapshot.jpg"
      videolink: "{{link}}/clip.mp4"
      snapmessage: >-
        Snapshot of a {{label}} detected by {{camnamesmall}} on {{startweekday}}
        {{startdate}} at {{starttime}}.
      videomessage: >-
        Video ({{videolength}}) of a {{label}} detected by {{camnamesmall}} on
        {{startweekday}} {{startdate}} at {{starttime}}.
  - alias: Send Snapshot/Video when event starts/ends
    if:
      - condition: trigger
        id:
          - started
    then:
      - parallel:
          - service: notify.notify
            data:
              message: "{{snapmessage}}"
              data:
                image: "{{imagelink}}"
                actions:
                  - action: URI
                    title: View Live
                    icon: sfsymbols:play-circle-outline
                    uri: /dashboard-camcast/{{camnamesmall}}
            alias: >-
              Send notification to my iPhone with picture attached and action to
              view Live feed.
          - service: telegram_bot.send_photo
            metadata: {}
            data:
              caption: "{{snapmessage}}"
              url: "{{imagelink}}"
    enabled: true
    else:
      - parallel:
          - service: notify.notify
            data:
              message: "{{videomessage}}"
              data:
                video: "{{videolink}}"
                actions:
                  - action: URI
                    title: Open Frigate
                    icon: sfsymbols:open-in-app
                    uri: /ccab4aaf_frigate-proxy
            alias: >-
              Send notification to my iPhone with video attached and option to
              open Frigate.
          - service: telegram_bot.send_video
            metadata: {}
            data:
              caption: "{{videomessage}}"
              url: "{{videolink}}"
          - service: persistent_notification.create
            metadata: {}
            data:
              title: "{{camnamecapital}}:"
              message: >-
                Check <a href="/api/frigate/notifications/{{eventid}}/clip.mp4"
                target="_blank">Video</a> ({{videolength}}) or <a
                href="/api/frigate/notifications/{{eventid}}/snapshot.jpg"
                target="_blank">Snapshot</a> of a {{label}} detected by
                {{camnamesmall}} on {{startweekday}} {{startdate}} at
                {{starttime}}.
mode: parallel
max: 10
trace:
  stored_traces: 10

```

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
go2rtc:
  streams:
    doorbell:
    - rtsp://user:pass@doorbellcamera.asus/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:doorbell#audio=opus
    doorbell_sub:
    - rtsp://user:pass@doorbellcamera.asus/cam/realmonitor?channel=1&subtype=1
    - ffmpeg:doorbell_sub#audio=opus

  webrtc:
    listen: :8555   # address of your local server (TCP)
    candidates:
    - x.x.x.x:8555   # if you have dynamic public IP-address
  ffmpeg:
    output: -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}
    hwaccel_args: preset-vaapi
  api:
    origin: '*'
  rtsp:
    listen: :8554
  log:
    level: info # default level
    api: trace
    exec: debug
    rtsp: warn
    streams: trace
    webrtc: fatal

####FRIGATE CONFIG BELOW####
ffmpeg: 
  hwaccel_args: preset-vaapi

mqtt:
  host: ha
  user: user
  password: pass
#
database:
  path: /media/frigate/frigate.db
#
#
detectors:
  coral:
    type: edgetpu
    device: usb
#
snapshots:
  enabled: true
  quality: 100
  height: 360
#
record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects
#
birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 1
  mode: continuous #objects #motion
#
cameras:
  frigate_doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://localhost:8554/doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://localhost:8554/doorbell_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 360
    motion:
      mask:
      - 400,31,612,32,613,0,404,0
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

amcrest
