### DISCUSSION TITLE
[Support]: Streams / ffmpeg crashes

### DISCUSSION THREAD

**Discussion by kankadev** [blakeblackshear/frigate#12157] [General Support]
### Describe the problem you are having

Since several days Frigate became unusable for me because after a few hours of frigate running 1-2 streams or like now all 6 streams crash and there are a lot errors in the log. If I use the "native" apps of Reolink and Tapo I can see all cameras work.

I have to restart frigate everyday and it works again for a few hours.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: 192.168.123.59
  user: frigate
  password: secret
  port: 1883
  topic_prefix: frigate
  client_id: frigate

birdseye:
  enabled: true
  mode: objects
  width: 2560
  height: 1440
  inactivity_threshold: 10

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
  - person
  - car
  - cat
  - dog
  - bicycle
  - motorcycle
  filters:
    person:
      min_area: 400 #5000
      max_area: 100000

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 20
      mode: active_objects

cameras:
  # Tapo C320WS - outdoor ueber Eingangstuer
  outside_door:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://camera:secret@192.168.123.150/stream1
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://camera:secret@192.168.123.150/stream2
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 15
    motion:
      mask:
      - 232,21,0,26,0,0,228,0

  # Tapo C310 - outdoor corner
  outside_corner:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://camera:secret@192.168.123.151/stream1
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://camera:secret@192.168.123.151/stream2
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 15


  # Tapo C310 - outdoor Klima
    motion:
      mask:
      - 0,0,640,0,640,195,391,57,294,62,0,54
  outside_klima:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://camera:secret@192.168.123.152/stream1
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://camera:secret@192.168.123.152/stream2
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 15
    motion:
      mask:
      - 640,0,640,82,0,31,0,0

  # Reolink E1 Pro - inside watching door
  inside_door:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://admin:secret@192.168.123.160:554/h264Preview_01_main
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://admin:secret@192.168.123.160:554/h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 7
    motion:
      mask:
      - 226,26,413,31,410,0,410,0,218,0

  # Reolink E1 Pro - above kitchen door
  inside_room_overview:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://admin:secret@192.168.123.161:554/h264Preview_01_main
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://admin:secret@192.168.123.161:554/h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 7
    motion:
      mask:
      - 412,0,411,23,218,24,222,0

  # Reolink E1 Pro - inside watching door
  inside_kitchen:
    ffmpeg:
      inputs:
        # High Resolution Stream
      - path: rtsp://admin:secret@192.168.123.162:554/h264Preview_01_main
        roles:
        - record
        # Low Resolution Stream
      - path: rtsp://admin:secret@192.168.123.162:554/h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 7
    motion:
      mask:
      - 223,0,222,28,415,27,410,0
```

### Relevant log output

```shell
please see attachment. Log is too long.
```

### FFprobe output from your camera

```shell
outside door:
C:\Windows\System32>ffprobe rtsp://camera:secret@192.168.123.150/stream2
ffprobe version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[rtsp @ 0000025aedd75200] max delay reached. need to consume packet
[rtsp @ 0000025aedd75200] RTP: missed 6 packets
Input #0, rtsp, from 'rtsp://camera:secret@192.168.123.150/stream2':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 640x360, 15 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

outside corner:
C:\Windows\System32>ffprobe rtsp://camera:secret@192.168.123.151/stream2
ffprobe version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[rtsp @ 000001763c975200] method DESCRIBE failed: 406 Not Acceptable
rtsp://camera:secret@192.168.123.151/stream2: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

I think this error occurs because Tapo cameras only allows 2 connections to it (frigate and Tapo Cloud).

outside klima:
same error like before

inside door:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"7/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]


inside room overview:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"7/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]


inside kitchen:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"7/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{"cameras":{"inside_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.2,"capture_pid":358,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":372,"pid":341,"process_fps":7.2,"skipped_fps":0.0},"inside_kitchen":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":373,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":385,"pid":345,"process_fps":7.1,"skipped_fps":0.0},"inside_room_overview":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.0,"capture_pid":363,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":374,"pid":344,"process_fps":7.0,"skipped_fps":0.0},"outside_corner":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":14.9,"capture_pid":351,"detection_enabled":1,"detection_fps":20.0,"ffmpeg_pid":356,"pid":337,"process_fps":15.0,"skipped_fps":0.0},"outside_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.1,"capture_pid":347,"detection_enabled":1,"detection_fps":3.3,"ffmpeg_pid":353,"pid":336,"process_fps":15.1,"skipped_fps":0.0},"outside_klima":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.0,"capture_pid":355,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":370,"pid":339,"process_fps":15.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"100":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"104":{"cmdline":"python3 -u -m frigate","cpu":"3.8","cpu_average":"5","mem":"3.1"},"122":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"143":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"154":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"293":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"295":{"cmdline":"frigate.recording_manager","cpu":"3.7","cpu_average":"4","mem":"0.8"},"304":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)","cpu":"0.7","cpu_average":"0","mem":"0.1"},"305":{"cmdline":"frigate.detector.coral","cpu":"8.3","cpu_average":"11","mem":"0.8"},"307":{"cmdline":"frigate.output       ","cpu":"10.8","cpu_average":"10","mem":"0.9"},"313":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"318":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"319":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 2560x1440 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"11.7","cpu_average":"11","mem":"0.7"},"336":{"cmdline":"frigate.process:outside_door","cpu":"3.6","cpu_average":"4","mem":"1.0"},"337":{"cmdline":"frigate.process:outside_corner","cpu":"18.0","cpu_average":"18","mem":"1.0"},"339":{"cmdline":"frigate.process:outside_klima","cpu":"4.5","cpu_average":"6","mem":"1.0"},"341":{"cmdline":"frigate.process:inside_door","cpu":"1.3","cpu_average":"1","mem":"1.0"},"344":{"cmdline":"frigate.process:inside_room_overview","cpu":"1.2","cpu_average":"1","mem":"1.0"},"345":{"cmdline":"frigate.process:inside_kitchen","cpu":"1.3","cpu_average":"1","mem":"1.0"},"347":{"cmdline":"frigate.capture:outside_door","cpu":"1.1","cpu_average":"1","mem":"0.9"},"351":{"cmdline":"frigate.capture:outside_corner","cpu":"1.0","cpu_average":"1","mem":"0.9"},"353":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.150/stream2 -r 15 -vf fps=15,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.0","cpu_average":"2","mem":"0.3"},"355":{"cmdline":"frigate.capture:outside_klima","cpu":"1.1","cpu_average":"1","mem":"0.9"},"356":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.151/stream2 -r 15 -vf fps=15,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"1","mem":"0.3"},"358":{"cmdline":"frigate.capture:inside_door","cpu":"0.6","cpu_average":"0","mem":"0.9"},"363":{"cmdline":"frigate.capture:inside_room_overview","cpu":"0.6","cpu_average":"0","mem":"0.9"},"365":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.150/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/outside_door@%Y%m%d%H%M%S%z.mp4","cpu":"1.3","cpu_average":"1","mem":"0.1"},"369":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.151/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/outside_corner@%Y%m%d%H%M%S%z.mp4","cpu":"1.4","cpu_average":"1","mem":"0.1"},"370":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.152/stream2 -r 15 -vf fps=15,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.3"},"372":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.160:554/h264Preview_01_sub -r 7 -vf fps=7,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.1","cpu_average":"0","mem":"0.3"},"373":{"cmdline":"frigate.capture:inside_kitchen","cpu":"0.4","cpu_average":"0","mem":"0.9"},"374":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.161:554/h264Preview_01_sub -r 7 -vf fps=7,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"0","mem":"0.3"},"384":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.152/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/outside_klima@%Y%m%d%H%M%S%z.mp4","cpu":"1.3","cpu_average":"1","mem":"0.1"},"385":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.162:554/h264Preview_01_sub -r 7 -vf fps=7,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"0","mem":"0.3"},"386":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.161:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/inside_room_overview@%Y%m%d%H%M%S%z.mp4","cpu":"1.8","cpu_average":"1","mem":"0.2"},"387":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.160:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/inside_door@%Y%m%d%H%M%S%z.mp4","cpu":"1.8","cpu_average":"1","mem":"0.2"},"390":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.123.162:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/inside_kitchen@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"1","mem":"0.2"},"9846":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":23.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.1,"pid":305}},"gpu_usages":{"intel-vaapi":{"gpu":"0.6%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":293},"recording":{"pid":295}},"service":{"last_updated":1719320134,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":122.1,"mount_type":"tmpfs","total":128.0,"used":5.9},"/media/frigate/clips":{"free":874653.0,"mount_type":"ext4","total":1006832.8,"used":86063.8},"/media/frigate/recordings":{"free":874653.0,"mount_type":"ext4","total":1006832.8,"used":86063.8},"/tmp/cache":{"free":851.6,"mount_type":"tmpfs","total":953.7,"used":102.0}},"temperatures":{},"uptime":2043,"version":"0.13.2-6476f8a"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

see comments in config file

### Any other information that may be helpful

docker-compose.yml:

```
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "secret"
```

Proxmox:
![grafik](https://github.com/blakeblackshear/frigate/assets/84390410/686e724f-e8ed-4fd3-bfcc-3f48ca71df35)

Log:
[log.txt](https://github.com/user-attachments/files/15971852/log.txt)
