### DISCUSSION TITLE
Upgrade from 0.12 can't find config.yml

### DISCUSSION THREAD

**Discussion by Drizzt321** [blakeblackshear/frigate#12159] [Config Support] [answered]
### Describe the problem you are having

So I'm finally getting around to upgrading from the old 0.12.1. I run it in a separate VM from HA and use the HA Frigate Proxy add-on, using docker compose. I did the following:

```
docker compose pull
docker compose up -d
```

After that, wouldn't start up, log showed issues with finding config.yml, and after some searching realized there needed to be a migration for the config dir. So I updated the `docker-compose.yml` file with that change, and now I'm stuck at 
```
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 35, in <module>
frigate  |     with open(config_file) as f:
frigate  | FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
```

### Version

N/A

### Frigate config file

```yaml
docker-compose.yml:

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable 
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/frigate/conf:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /media/frigate/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "<REDACTED>"
      PLUS_API_KEY: <REDACTED>


frigate.yml:
mqtt:
  host: homeassistant
  user:  frigate
  password: <REDACTED>

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 120 
      mode: active_objects
      
cameras:
  alley_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.230/stream0 # 640x480 25fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.230/stream1 # 1920x1080 10fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10


  alley_2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.212:554/cam/realmonitor?channel=1&subtype=1 # 704x576 20fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.212:554/cam/realmonitor?channel=1&subtype=0 # 2592x1944 20fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 10

  alley_3: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.249:554/cam/realmonitor?channel=1&subtype=1 # 704x576 20fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.249:554/cam/realmonitor?channel=1&subtype=0 # 2592x1944 20fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 10


birdseye:
  enabled: True
  mode: continuous

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - skateboard
    - cat
    - umbrella
    - handbag
      #    - suitcase


snapshots:
  enabled: True
  timestamp: True
```


### Relevant log output

```shell
From `docker compose up`


frigate@darkfrigate:~/frigate/conf$ docker compose up
WARN[0000] /home/frigate/frigate/conf/docker-compose.yml: `version` is obsolete 
[+] Running 2/2
 ✔ Network conf_default  Created                                                                                                                                                                                                                                  0.2s 
 ✔ Container frigate     Created                                                                                                                                                                                                                                  0.2s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | 2024-06-25 11:30:50.561493015  [INFO] Preparing Frigate...
frigate  | 2024-06-25 11:30:50.561518168  [ERROR] Frigate config file not found
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-06-25 11:30:50.564370427  [INFO] Starting NGINX...
frigate  | 2024-06-25 11:30:50.566344729  [INFO] Preparing new go2rtc config...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-06-25 11:30:50.570502242  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2024-06-25 11:30:50.588009120  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-06-25 11:30:50.654525934  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2024-06-25 11:30:50.676506759  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 35, in <module>
frigate  |     with open(config_file) as f:
frigate  | FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```
```


### Frigate stats

```json
N/A
```


### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

_No response_
