### DISCUSSION TITLE
Trying to figure out notifications with HA

### DISCUSSION THREAD

**Discussion by rykr** [blakeblackshear/frigate#12169] [General Support]
### Describe the problem you are having

Not getting thumbnail on IOS notification.  My automation sends the notify like this:

  - alias: Notify phones
    service: notify.parents_mobile_devices
    data:
      message: >
        {% if camera == 'pool' %} A {{objects[0]}} has been seen by the pool {%
        elif camera == 'house_rear' %} A {{objects[0]}} has been seen behind the
        house {% else %} A {{objects[0]}} has been seen behind the pool house {%
        endif %}
      data:
        image: >-
          https://192.168.1.200:8123/api/frigate/notifications/{{id}}/thumbnail.jpg
        tag: "{{id}}"
        group: frigate-notification-{{camera}}
        when: "{{start_time}}"
        entity_id: camera.{{camera}}

Also, when I long press on the notification to look at it it takes 2-4 seconds to come up.  it's all black but within 2-4 seconds it comes up.  Being on my home wifi I would expect this to be near instant.  

Also, when I look at the HA trace and get the actual url used for the image, and then paste it into a browse, I get event not found.  What am I not understanding here?

### Version

0.14 beta 3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.200
record:
  enabled: true
snapshots:
  enabled: true
motion:
  threshold: 30
  improve_contrast: false
detectors:
  deepstack:
    api_url: http://192.168.1.200:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.5 # seconds

go2rtc:
  streams:
    house_rear:
      - ffmpeg:rtsp://admin:18Gr33nacr3s@192.168.1.34:554/h264Preview_01_main#backchannel=0
    house_rear_sub:
      - ffmpeg:rtsp://admin:18Gr33nacr3s@192.168.1.34:554/h264Preview_01_sub#backchannel=0
    pool:
      - rtsp://admin:111111@192.168.1.164:554/h264Preview_01_main#backchannel=0
    pool_sub:
      - rtsp://admin:111111@192.168.1.164:554/h264Preview_01_sub#backchannel=0
    pool_rear:
      - rtsp://admin:111111@192.168.1.127:554/h264Preview_01_main#backchannel=0
      #- ffmpeg:http://192.168.1.127/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=111111#video=copy#audio=copy#audio=opus
    pool_rear_sub:
      - rtsp://admin:111111@192.168.1.127:554/h264Preview_01_sub#backchannel=0
#      - ffmpeg:http://192.168.1.127/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=111111
  webrtc:
    candidates:
      - 192.168.1.200:8555
      - stun:8555

cameras:
  # ##### camera on back of house
  house_rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_rear
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/house_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 720
      height: 480
      fps: 10
    motion:
      mask:
        - 720,445,720,480,625,480,621,446
      threshold: 30
      contour_area: 20
      improve_contrast: 'false'
    objects:
      track:
        - person
        - dog

  ##### camera on back of pool house
  pool_rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool_rear
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 297,30,363,30,359,0,299,0
      threshold: 30
      contour_area: 20
      improve_contrast: 'false'
    objects:
      track:
        - person
        - car
        - truck
        - dog
        - motorcycle

  #### camera over pool
  pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.471,0.046,0.567,0.048,0.567,0,0.464,0
      threshold: 30
      contour_area: 20
      improve_contrast: 'false'
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 247,95,239,118,203,117,202,77
    detect:
      width: 640
      height: 480
      fps: 10

  ### camera in kitchen
#  kitchen:
#    ffmpeg:
#      hwaccel_args: preset-nvidia-h264
##      inputs:
 #     - path: rtsp://192.168.1.41/live0
 #       input_args: preset-rtsp-restream
 #       roles:
 #       - record
 #   motion:
 #     mask:
 #       - 1809,0,1814,63,1649,70,1649,0
 #   objects:
 #     track:
 #       - person
 #       - dog

version: 0.14
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

Other

### Network connection

Wired

### Camera make and model

N/A
