### DISCUSSION TITLE
[Config Support]: Ignore recordings outside the zone

### DISCUSSION THREAD

**Discussion by SirSheik** [blakeblackshear/frigate#12163] [Config Support]
### Describe the problem you are having

Hello.
I am currently testing the latest beta version 0.14 and I detected a small problem but I don't know if it is a bug or a mistake in my configuration.
I have configured my video door phone to only record alerts and detections and snapshots in a specific zone and it seems to work fine.
The problem I have detected is that the recordings are still stored when it detects people outside the zone, even when these people have not entered the zone, which is not legal in Spain.

Checking the documentation in previous versions there was the following option, but I see that this is no longer valid in version 0.14
`  record:
    events:
      required_zones:
        - entire_yard`

Would there be a way to avoid recording any events outside the area?
The only thing I can think of is to increase the motion mask so as not to detect anything on the pavement, but in that case I think that in my particular case it would not make sense to define a zone.
![Image 671](https://github.com/blakeblackshear/frigate/assets/31892065/daa91e7f-f370-4f59-8650-d77a05155d65)

Any ideas or suggestions are welcome.
Thank you very much for this wonderful project.

### Version

0.14.0 Beta 3

### Frigate config file

```yaml
videoportero:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy #Use this to enable audio in recordings
      inputs:
        - path: rtsp://127.0.0.1:8554/videoportero
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/videoportero_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    # double-take optimization    
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
      required_zones:
        - zona_videoportero_entrada
    motion:
      mask:
        - 0.007,0.978,0.347,0.98,0.347,0.935,0.007,0.933
        - 0.701,1,1,1,1,0,0.31,0,0.494,0.47,0.493,0.516,0.511,0.515
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        mode: active_objects
    snapshots:
      enabled: true
      required_zones:
        - zona_videoportero_entrada
    objects:
      track:
        - person
        - cat
    zones:
      zona_videoportero_entrada:
        coordinates: 0,0,0.303,0,0.478,0,0.484,0.748,0.513,0.751,0.527,1,0,1
        inertia: 3
    review:
      alerts:
        required_zones: zona_videoportero_entrada
      detections:
        required_zones: zona_videoportero_entrada
```

### Relevant log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral
