### DISCUSSION TITLE
[Question]: Excessive CPU usage + frigate record 24 hours without object detection

### DISCUSSION THREAD

**Discussion by AnonymousWebHacker** [blakeblackshear/frigate#12175] [Ask A Question]
### What is your question:

The title already says it all, anyway I will leave my information.

Server only for Test.

- OS: Ubuntu
- CPU: i5-3360M CPU @ 2.80GHz
- RAM: 8 Gb  
- Frigate instalation: docker
- Frigate Version: 0.14.0-beta3
- TPU Coral: No installed

### FFPROBE

```
Input #0, rtsp, from 'rtsp://10.28.143.242/onvif1':
  Metadata:
    title           : H.264 Video, RtspServer_0.0.0.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1280x720, 15 fps, 14.92 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
  ```
  
  ### Saving video, The CPU just doesn't even know what I'm doing.
  
  ```
ffmpeg -i rtsp://10.28.143.242/onvif1 -c:v copy -an /tmp/video.mp4
  ```
## **Using the Frigate.**
Since it is a modest hardware, I decided to do some tests with frigate that is not aggressive with the hardware.
Frigate + Record 24/7 for 3 days without motion detection or object detection.

## **config.yaml**
```
#======================================
#   MQTT Config integrate HA events
#======================================
mqtt:
  host: 10.28.143.249
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  #user: frigate
  #password: frigate
  enabled: true

#======================================
#          go2rtc Config
#======================================
go2rtc:
  streams:
    Albert:
      - rtsp://10.28.143.242/onvif1


#=====================================================================
cameras:                #CAMERAS CONFIGURATION
#=====================================================================


#===================================================================== 
  Albert: # <------ Name the camera
#=====================================================================
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Albert # <----- Update for your camera URL
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy

    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 15

    record:
      enabled: true
      retain:
        days: 3
        mode: all
              #   all - save all recording segments regardless of activity
              #   motion - save all recordings segments with any detected motion
              #   active_objects - save all recording segments with active/moving objects
      events:
        retain:
          default: 5 #Days
          mode: all
              #   all - save all recording segments for events regardless of activity
              #   motion - save all recordings segments for events with any detected motion
              #   active_objects - save all recording segments for event with active/moving objects

version: 0.14
```
### Frigate UI

1 - Videos recorded in timelapse, without audio.

2- Creation of mini events like it is detecting something.
![image](https://github.com/blakeblackshear/frigate/assets/43164089/5c6de142-ad05-40d6-83c0-09768bb2fdde)

3 - CPU is high and GPU is low
![image](https://github.com/blakeblackshear/frigate/assets/43164089/207fd992-3671-42cb-8186-c55aec2fca35)
![image](https://github.com/blakeblackshear/frigate/assets/43164089/efd66494-6996-43bf-9b23-7b0b72954129)

4 - Detector Use (Detectors? with frigate only recording?)
![image](https://github.com/blakeblackshear/frigate/assets/43164089/1570e704-82ae-4086-a5ba-94ebec7ad348)

![image](https://github.com/blakeblackshear/frigate/assets/43164089/b5367c46-00a9-4c43-ab55-5eae573b63bc)

5 - I had to manually disable person detection in the GUI (when I don't have that option in the frigate configuration file.)
![image](https://github.com/blakeblackshear/frigate/assets/43164089/03dd5d97-21cb-4372-a8be-1074978ae6ea)

6 - When I go to the frigate page at the address //review, to see the camera, the site is extremely slow
![image](https://github.com/blakeblackshear/frigate/assets/43164089/42a4d750-9321-405e-aaa9-4b84f2d8656f)
![image](https://github.com/blakeblackshear/frigate/assets/43164089/76581ed2-c326-46a0-b548-ce065b3d4e06)

If I'm just saving the videos.
Why this excessive CPU usage?

## Improvements: 
Frigate should have 3 options in its configuration
```
Mode Use GUI:      Record24/7
                            #Motion Detect
                             Object Detect
```
According to the options you comment or decomment, the GUI is modified.
Firgate is configured to easily access the captured events, etc., but however, if you only set record, the GUI does not match the mode of use.

What am I missing in my configuration, or what error do I have that causes Frigate to use so many resources?

**Comment by NickM-27** [comment]
1. not sure what you mean, you are probably referring to the previews which are separate from recordings
2. you say you don't have object or motion detection enabled, but you have enabled object and motion detection (which are enabled by default as well)

```yaml
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 15
```

3. you have detect fps set to 15, this is quite high and also this fps does not need to match the camera fps. 5 is the recommended default especially if you don't intend to do motion or object detection
4. again, you configured it incorrectly
5. you do have the option in the configuration file, you set it to true

**Reply by NickM-27** [reply]
you should instead set your config as 

```yaml
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false
```

**Comment by AnonymousWebHacker** [comment]
Thank you for your quick response and taking the trouble to read my problem. 

I was absolutely right, bad configuration and a misunderstanding with the documentation, I will try to push the repo doc  with something more detailed for the clueless like me

I still have a problem, the recorded videos do not have audio.

### **Config Fixed.yml**
```
#======================================
#   MQTT Config integrate HA events
#======================================
mqtt:
  host: 10.28.143.249
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  #user: frigate
  #password: frigate
  enabled: true

#======================================
#          go2rtc Config
#======================================
go2rtc:
  streams:
    Albert:
      - rtsp://10.28.143.242/onvif1


#=====================================================================
cameras:                #CAMERAS CONFIGURATION
#=====================================================================


#===================================================================== 
  Albert: # <------ Name the camera
#=====================================================================
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Albert # <----- Update for your camera URL
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 3
        mode: all
              #   all - save all recording segments regardless of activity
              #   motion - save all recordings segments with any detected motion
              #   active_objects - save all recording segments with active/moving objects
      events:
        retain:
          default: 5 #Days
          mode: all
              #   all - save all recording segments for events regardless of activity
              #   motion - save all recordings segments for events with any detected motion
              #   active_objects - save all recording segments for event with active/moving objects
```

Here the post https://github.com/blakeblackshear/frigate/discussions/12180

**Reply by NickM-27** [reply]
If you change `rtsp://127.0.0.1:8554/Albert` to `rtsp://127.0.0.1:8554/Albert?video&audio` it should work

**Reply by AnonymousWebHacker** [reply]
No work . 
![image](https://github.com/blakeblackshear/frigate/assets/43164089/91c833d1-4657-4f03-9d18-88740a4705bb)
![image](https://github.com/blakeblackshear/frigate/assets/43164089/92a9d54c-548d-4792-bf91-9f9aa57bf2ce)
**Observation,** 
both with the original configuration and the "video&audio" configuration, in live mode, I can hear the audio, but not when it is saved

**Reply by NickM-27** [reply]
Ah right, need to use `preset-record-generic-audio-aac`

**Reply by AnonymousWebHacker** [reply]
Noup.

```
ffprobe rtsp://10.28.143.242/onvif1
Input #0, rtsp, from 'rtsp://10.28.143.242/onvif1':
  Metadata:
    title           : H.264 Video, RtspServer_0.0.0.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1280x720, 15 fps, 14.92 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```
Audio --> Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

**Config Frigate** 
```
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Albert # <----- Update for your camera URL
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
```
The resulting video has no audio.

```
ffprobe /opt/frigate/storage/recordings/2024-06-28/02/Albert/26.44.mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/opt/frigate/storage/recordings/2024-06-28/02/Albert/26.44.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : go2rtc/1.9.2
    encoder         : Lavf59.27.100
  Duration: 00:00:08.02, start: 0.000000, bitrate: 368 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 1280x720, 366 kb/s, 14.96 fps, 15 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
 ```
      
Live I can hear the audio, but not the resulting recording.

**Reply by NickM-27** [reply]
You need to still have the url I put above.

**Reply by AnonymousWebHacker** [reply]
Done man, done 
`ffprobe 40.28.mp4`

```
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 1280x720, 345 kb/s, 14.68 fps, 15 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 30 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```
Last Config 100% Work
```
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1?video&audio 
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
```

`?video&audio` In the documentation, I had not seen this option.

Thanks for your help, and quick responses.
