### DISCUSSION TITLE
[Support]: Video clips wont play in Frigate UI

### DISCUSSION THREAD

**Discussion by sentur66413** [blakeblackshear/frigate#12176] [General Support]
### Describe the problem you are having

Older video clips recorded in Frigate won't play at all. I get the error `The media could not be loaded, either because the server or network failed or because the format is not supported.` and a black screen for the video clip. But the files play fine when accessed on a mac/win SMB share so I know the videos are working correctly and not corrupt.

I recently restored my Frigate from a backup and the video files recorded pre-restore are the ones that are affected. A small thumbnail of the trigger frame shows, but it's at a small resolution. 

All clips that have been recorded since the restore play fine, last couple of days. Snapshots / highlighted motion also previews a static image correctly and at full size. 

I'm running Frigate in an LXC on Proxmox using the [PVE Helper Scripts ](https://tteck.github.io/Proxmox/#frigate-lxc). The clips are recorded to a local SMB share. I've mapped the SMB share in `/etc/fstab` at the host level. And then in the LXC container config, it's setup as `mp0: /mnt/nas/frigate,mp=/cctv_clips`. 

I've been into the SMB share on my NAS and reapplied the permissions so that all files are set to the correct frigate:frigate user:group in the ACLs. I'm able to create new files/video clips on the SMB share. I've also checked that the old clip videos are still playable through FileBrowser on TrueNAS. So I don't think this is a permissions issue. 

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mqtt.server.arpa
  port: 1883
  topic_prefix: frigate
  user: mqttFrigate
  password: <REDACTED_PASSWORD>
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  retain:
    days: 21
    mode: motion
  events:
    pre_capture: 30
    post_capture: 20
    retain:
      default: 30
      mode: active_objects
      objects:
        cat: 14
        people: 180
audio:
  enabled: True
go2rtc:
  streams:
    living_room:
      - rtsp://<REDACTED_IP>/live0
    master_bedroom:
      - rtsp://<REDACTED_IP>/live0
    second_bedroom:
      - rtsp://<REDACTED_IP>/live0
    kitchen:
      - rtsp://<REDACTED_IP>/live0
objects:
  track:
    - person
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  living_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    record:
      enabled: True
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: true
      crop: False
    motion:
      mask:
        - 0,158,693,243,792,250,1280,150,1280,0,0,0
  kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    record: 
      enabled: True
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: true
      crop: False
  master_bedroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/master_bedroom
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    record:
      enabled: True
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: true
      crop: False
  second_bedroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/second_bedroom
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    record:
      enabled: True
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: true
      crop: False
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
{
  "cameras": {
    "kitchen": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 0,
      "capture_pid": 600,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 154362,
      "pid": 588,
      "process_fps": 0,
      "skipped_fps": 0
    },
    "living_room": {
      "audio_dBFS": -44.6882,
      "audio_rms": 191.0034,
      "camera_fps": 0,
      "capture_pid": 596,
      "detection_enabled": 1,
      "detection_fps": 0.7,
      "ffmpeg_pid": 154368,
      "pid": 587,
      "process_fps": 5,
      "skipped_fps": 0
    },
    "master_bedroom": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 0,
      "capture_pid": 605,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 154378,
      "pid": 591,
      "process_fps": 0,
      "skipped_fps": 0
    },
    "second_bedroom": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 0,
      "capture_pid": 621,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 154361,
      "pid": 593,
      "process_fps": 0,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "79": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "100": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "105": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "118": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "145": {
      "cmdline": "nginx: worker process",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "155": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "310": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "311": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "312": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "315": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "324": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "336": {
      "cmdline": "nginx: worker process",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "350": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "363": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "564": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "566": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "575": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(55)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "576": {
      "cmdline": "frigate.detector.coral",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "578": {
      "cmdline": "frigate.output       ",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "584": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "586": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "587": {
      "cmdline": "frigate.process:living_room",
      "cpu": "0.0",
      "cpu_average": "1",
      "mem": "0.4"
    },
    "588": {
      "cmdline": "frigate.process:kitchen",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "589": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "591": {
      "cmdline": "frigate.process:master_bedroom",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "593": {
      "cmdline": "frigate.process:second_bedroom",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "594": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "596": {
      "cmdline": "frigate.capture:living_room",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "600": {
      "cmdline": "frigate.capture:kitchen",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "601": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "605": {
      "cmdline": "frigate.capture:master_bedroom",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "621": {
      "cmdline": "frigate.capture:second_bedroom",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "625": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "154335": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "154378": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/master_bedroom -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/master_bedroom@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0.7,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 8.31,
      "pid": 576
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.0%",
      "mem": "-%"
    }
  },
  "processes": {
    "audioDetector": {
      "pid": 625
    },
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 564
    },
    "recording": {
      "pid": 566
    }
  },
  "service": {
    "last_updated": 1719507030,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 112.8,
        "mount_type": "tmpfs",
        "total": 128,
        "used": 15.2
      },
      "/media/frigate/clips": {
        "free": 401961.1,
        "mount_type": "cifs",
        "total": 406313.8,
        "used": 4352.6
      },
      "/media/frigate/recordings": {
        "free": 401961.1,
        "mount_type": "cifs",
        "total": 406313.8,
        "used": 4352.6
      },
      "/tmp/cache": {
        "free": 12090.6,
        "mount_type": "overlay",
        "total": 16384,
        "used": 4293.4
      }
    },
    "temperatures": {

    },
    "uptime": 68700,
    "version": "0.13.1-34fb1c2"
  }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

I think it's using docker-compose as there's a `/opt/docker-compose.yaml` file. Portainter is also installed as part of the PVE Helper Script I used in the original setup.
