### DISCUSSION TITLE
Frigate and Records 24/7

### DISCUSSION THREAD

**Discussion by AnonymousWebHacker** [blakeblackshear/frigate#12180] [Ideas]
### Intro
Frigate in itself is to be used with all its options:

- motion detection
- object detection
- all time recordings, etc.

But what happens when you use frigate only for 24-hour recordings without detection of movements and objects ?

### Proyect
I currently have a local frigate instance with the goal of recording 24 hours without object or movement detection, and with as little hardware use as possible.

In my first attempt at reading the documentation, at least for me, it was not entirely clear, I made a [discussion](https://github.com/blakeblackshear/frigate/discussions/12175) in which they corrected some configurations.

### Sample Config 24 hours 100% working.
```
#======================================
#   MQTT Config integrate HA events
#======================================
mqtt:
  host: 10.28.143.249
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  #user: frigate
  #password: frigate
  enabled: true

#======================================
#          go2rtc Config
#======================================
go2rtc:
  streams:
    Camera1:
      - rtsp://10.28.143.242/onvif1


#=====================================================================
cameras:                #CAMERAS CONFIGURATION
#=====================================================================


#===================================================================== 
  Camera1: # <------ Name the camera
#=====================================================================
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi # <---- #(Be careful, depending on your hardware it may change)
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1 # <----- Update for your camera URL
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 3
        mode: all
              #   all - save all recording segments regardless of activity
              #   motion - save all recordings segments with any detected motion
              #   active_objects - save all recording segments with active/moving objects
      events:
        retain:
          default: 5 #Days
          mode: all
              #   all - save all recording segments for events regardless of activity
              #   motion - save all recordings segments for events with any detected motion
              #   active_objects - save all recording segments for event with active/moving objects
```
#### Result? 
Incredibly non-existent CPU and RAM usage.

I have my frigate instance working fine, with 24-hour recordings, and without detection of movements or objects. (except that videos saved on disk do not have audio)

#### 1 - Live cameras or **List Cameras** button:
It is certainly functional to see the list of cameras. 

#### 2 - **Review button:**
![image](https://github.com/blakeblackshear/frigate/assets/43164089/ac2a95a1-af80-42ad-a9d1-28e1d6643e37)
It can work perfect for **_history_** or **_timelapse recording_**,  **events**, **alerts**, **detections**, or **motion**. (I don't have any of those options in my configuration file record 24/7).
Let's add to this, the **filter**, **Show Reviewed**, even the **timelapse by dates** also has no function.

#### 3- Live Video Mode
Back to the Live Camera or Camera List button, and I click on one of them, it opens its Live mode. It is perfect!!! 
..Wait, what does the people detection button do in a 24 hour setting?
![image](https://github.com/blakeblackshear/frigate/assets/43164089/354216ed-fe4d-458f-befb-49be0fb8c831)

Anyway I say, okay, let's move on to the recordings saved on disk
![image](https://github.com/blakeblackshear/frigate/assets/43164089/4f378a00-1bd9-445e-9aae-4fa2ff2c51f2)

#### 4- Video Records
Firstly, it is something...hidden or unintuitive, I think. In any case it is understandable, History with Recordings 
At first impression, the guide took its time loading the recordings at a somewhat "desperate" level, the wait, but in the end it loaded.
**Export Mode:** Is great! 
![image](https://github.com/blakeblackshear/frigate/assets/43164089/39e67a99-71cb-4738-91a7-ea2b68dbee31)

**Timelap Data:** 
I more or less understand the intention of having that option, it just doesn't fulfill its objective, if you don't mark the days on which there are recordings and which ones don't.
![image](https://github.com/blakeblackshear/frigate/assets/43164089/074f7f39-1408-4a0c-8b4f-4604af2bb755)

**Filter:**  and **Events** 
It also doesn't make sense to be
![image](https://github.com/blakeblackshear/frigate/assets/43164089/2b1baf43-bd5f-4b13-bd79-d4aedd8cc831)

**Timelap:**
It really works well as expected
At least draw me a graph like the motion detection one, so I know where there are recordings or not.
Meanwhile, I'm just blindly scrolling through a timelapse.
![image](https://github.com/blakeblackshear/frigate/assets/43164089/902c7946-49ca-4a1e-a63e-03d0aacba811)

### Possible solution:
Frigate should incorporate in its configuration, the options for the use that will be given and according to this, then its options visible in the GUI or not.
```
Mode Use GUI:      Record24/7
                            #Motion Detect
                             Object Detect
```
If I choose the option to only record 24 hours, the GUI should not show me things like detection options etc.
