### DISCUSSION TITLE
Whats the acceptable Inference Speed for yolo-nas on OpenVino?

### DISCUSSION THREAD

**Discussion by klingon888** [blakeblackshear/frigate#12188] [Detector Support]
### Describe the problem you are having

My system is a Beelink S12 with Intel N100 CPU. I have 3x 2K cams with detect set at 640x360 and 1x 2K cam detect at 1280x720. Motion detection threshold is set at 50. I've built yolo-nas at 256x256 using the Collab provided at https://colab.research.google.com/github/blakeblackshear/frigate/blob/dev/notebooks/YOLO_NAS_Pretrained_Export.ipynb. 

My inference when idle is around 30ms and when motion is detected goes up to 150ms. I constantly get the OV is slow/very slow msg on the bottom right even when minimal 1-2 red boxes of motion detected shown on the Debug screen. Searching other posts show yolonas inference of 50-60ms at 320x320 but not sure if this is at idle or average. At 320, my inference go up to around 220ms when motion is detected. Is this speed considered acceptable with my setup? Would a Coral TPU provide better inference? 

![image](https://github.com/blakeblackshear/frigate/assets/30375535/1400c6fa-7f67-4fd1-a0da-be82ae2b5461)

### Version

0.14.0-bfbacee

### Frigate config file

```yaml
Same across all 4 cams:
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 256
  height: 256
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas/yolo_nas_s_256.onnx
  labelmap_path: /labelmap/coco-80.txt

go2rtc:
  streams:
    front_cam:
      - rtsp://@192.168.10.146:554/stream1
    front_cam_sub:
      - rtsp://@192.168.10.146:554/stream2

cameras:
  front_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_cam_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    motion:
      threshold: 50
      improve_contrast: 'true'
      contour_area: 10
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 14
    mqtt:
      enabled: false
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-bfbacee
    cap_add:
      - CAP_PERFMON
    shm_size: "80mb" 
    devices:
      - /dev/bus/usb:/dev/bus/usb 
      - /dev/dri/renderD128 
    volumes:
      - /opt/frigate/media:/media/frigate
      - /opt/frigate:/db
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/config:/config
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000 
    ports:
      - "5000:5000"
      - "8554:8554" 
      - "8555:8555/tcp"
      - "8555:8555/udp"
```

### Relevant log output

```shell
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

OpenVino
