### DISCUSSION TITLE
[Config Support]: Recordings not being retained correctly

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#12182] [Config Support] [answered]
### Describe the problem you are having

Hi,

I have a defaut retention of 5 days, but want to keep recordings of cats and dogs for 90 days.  The recordings of cats/dogs stay in the UI list, but the recordings are being deleted from the media folder after 5 days.

### Version

0.13.2

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 5
    post_capture: 20
    required_zones:
    - car_detection
    - overall_detection        
    retain:
      default: 5
      mode: all
      objects:
        cat: 90
        dog: 90
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

OpenVino
