### DISCUSSION TITLE
[Support]: Error from HA integration connecting to Frigate (I think)

### DISCUSSION THREAD

**Discussion by Chaoscontrol** [blakeblackshear/frigate#12199] [General Support] [answered]
### Describe the problem you are having

See logs below. These errors appearing repeatedly on HA. 

Frigate is running fine, all cameras fine, Frigate integration and card showing cameras fine. 

I searched a bit before posting and found this is an error related to Frigate not being available during startup, and fixing itself by restarting. But here it's not the case. I've restarted Frigate, HA, several times, in different orders. It actually doesn't happen on restart, it happens afterwards during normal running. 

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: frigate
  password: redacted

# logger:
#   logs:
#     frigate.record.util: debug

go2rtc:
  log:
    #level: trace
    #api: trace
    #exec: trace
    #ngrok: trace
    #rtsp: trace
    #streams: trace
    #webrtc: trace

  # AAC Audio required for recordings and detection, Opus required only for webRTC Live View (2-way audio)
  streams:
    doorbell: # Reolink Doorbell WiFi
      - rtsp://admin:redacted@192.168.1.232:554/h264Preview_01_main
      - ffmpeg:doorbell#audio=aac#audio=volume
      - ffmpeg:doorbell#audio=opus#audio=volume # Opus required for 2-way audio
    doorbell_sub: # 640x480, 7fps, 64K br 1x ifi
      - rtsp://admin:redacted@192.168.1.232:554/h264Preview_01_sub 
      - ffmpeg:doorbell_sub#audio=aac#audio=volume
    reolink: # Reolink E1 Pro broken night vision
      - rtsp://admin:redacted@192.168.1.138:554/h264Preview_01_main
      - ffmpeg:reolink#audio=aac#audio=volume
    reolink_sub: # 640x360, 7fps, 64K br
      - rtsp://admin:redacted@192.168.1.138:554/h264Preview_01_sub
      - ffmpeg:reolink_sub#audio=aac#audio=volume
    bedroom: # Reolink E1 Pro
      - rtsp://admin:redacted@192.168.1.216:554/h264Preview_01_main
      - ffmpeg:bedroom#audio=aac#audio=volume
    bedroom_sub: # 640x360, 7fps, 64K br
      - rtsp://admin:redacted@192.168.1.216:554/h264Preview_01_sub
      - ffmpeg:bedroom_sub#audio=aac#audio=volume
    backgarden: # Foscam R5
      - ffmpeg:rtsp://foscamadmin:redacted@192.168.1.177:88/videoMain
      - ffmpeg:backgarden#audio=aac#audio=volume
    backgarden_sub: # 640x480, 5fps, 50K br, 10 ifi
      - ffmpeg:rtsp://foscamadmin:redacted@192.168.1.177:88/videoSub
      - ffmpeg:backgarden_sub#audio=aac#audio=volume
    livingroom: # Foscam R5
      - ffmpeg:rtsp://foscamadmin:redacted@192.168.1.239:88/videoMain
      - ffmpeg:livingroom#audio=aac#audio=volume
    livingroom_sub: # 640x480, 5fps, 50K br, 10 ifi
      - ffmpeg:rtsp://foscamadmin:redacted@192.168.1.239:88/videoSub
      - ffmpeg:livingroom_sub#audio=aac#audio=volume

  ## Frigate docs recommend HTTP+FLV connection for Reolink Doorbell, but only RTSP allows for 2-way audio
  ## #video=copy is needed for a single line ffmpeg config when using audio tags, or else video stream is dropped


## THIS INCREASES VOL AND PREVENTS THE AUDIO COMING OUT FROM THE CAMERA SOUNDING MUFFLED
## Source https://www.youtube.com/watch?v=upXyBVMR4RM

  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

cameras:
  doorbell:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          roles:
            - detect
            - audio
    live:
      stream_name: doorbell
    detect:
      width: 640
      height: 480
      fps: 7
    #birdseye:
    #  order: 1
    zones:
      Front_garden:
        coordinates: 
          0.143,0.527,0.143,0.561,0.373,0.563,0.613,0.56,0.609,0.523,0.885,0.557,0.874,0.704,0.993,0.751,0.995,0.999,0.002,0.999,0,0.557
      Driveway/Neighbours:
        coordinates: 
          0.851,0.516,0.898,0.502,1,0.502,1,0.588,0.973,0.732,0.876,0.703,0.887,0.555,0.834,0.545
    review:
      detections:
        required_zones:
          - Front_garden
          - Driveway/Neighbours
    motion:
      mask: 
        0,0.429,0.122,0.421,0.198,0.33,0.56,0.331,0.589,0.434,0.871,0.412,0.896,0.389,0.975,0.436,0.999,0.436,0.999,0.003,0.002,0
  bedroom:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroom_sub
          roles:
            - detect
            - audio
    live:
      stream_name: bedroom
    detect:
      width: 640
      height: 360
      fps: 7
    #birdseye:
    #  order: 2
    onvif:
      host: 192.168.1.216
      port: 8000
      user: admin
      password: redacted
    objects:
      filters:
        person:
          min_area: 1500
  reolink:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_sub
          roles:
            - detect
            - audio
    live:
      stream_name: reolink
    detect:
      width: 640
      height: 360
      fps: 7
    #birdseye:
    #  order: 2
    onvif:
      host: 192.168.1.138
      port: 8000
      user: admin
      password: redacted
  backgarden:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backgarden
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backgarden_sub
          roles:
            - detect
            - audio
    live:
      stream_name: backgarden
    detect:
      width: 640
      height: 480
      fps: 5
    #birdseye:
    #  order: 3
    onvif:
      host: 192.168.1.177
      port: 888
      user: foscamadmin
      password: redacted
    motion:
      mask:
        - 0,0,0,0.471,0.247,0.445,0.275,0.492,0.39,0.492,0.441,0.492,0.56,0.459,0.677,0.439,0.786,0.309,0.768,0.113,0.761,0.003
        - 0.64,0.373,0.578,0.579,0.688,0.708,0.768,0.719,0.803,0.697,0.792,0.292
  livingroom:
    # enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/livingroom
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/livingroom_sub
          roles:
            - detect
            - audio
    live:
      stream_name: livingroom
    detect:
      width: 640
      height: 480
      fps: 5
    #birdseye:
    #  order: 4
    onvif:
      host: 192.168.1.239
      port: 888
      user: foscamadmin
      password: redacted

## Intel N5095, SSD 256GB, 8GB RAM

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  ov:
    type: openvino
    device: AUTO

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  path: /openvino-model/ssdlite_mobilenet_v2.xml

record:
  enabled: true
  # sync_recordings: true
  retain:
    days: 1 #default=0
    mode: motion #default
  events:
    retain:
      default: 5
      mode: motion
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case. 
    # x4=0.25, x8=0.125, x16=0.0625
    timelapse_args: -vf setpts=0.125*PTS

motion:
  threshold: 50 # 0-255 default=30 Less is more sensitive (was using 150 for months)
  improve_contrast: true

snapshots:
  enabled: true
  retain:
    default: 10 #days

detect:
  enabled: true

objects:
  track:
    - person
    - cat
  filters:
    person:
      threshold: 0.8
      min_score: 0.65
    # cat:
    #   threshold: 0.8

review:
  alerts:
    labels:
      - bark

audio:
  enabled: true
  listen:
    - scream
    - yell
    - laughter

#birdseye:
#  enabled: True
#  mode: continuous

#ui:
  #live_mode: webrtc
camera_groups:
  Outdoors:
    order: 2
    icon: LuTrees
    cameras:
      - backgarden
      - doorbell
  Indoors:
    order: 1
    icon: LuHome
    cameras:
      - bedroom
      - livingroom
      - reolink
version: 0.14
```

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:259
integration: Frigate (documentation, issues)
First occurred: 28 June 2024 at 14:41:03 (159 occurrences)
Last logged: 09:06:06

Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [Connect call failed ('172.30.33.5', 5000)]
Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: 500, message='Internal Server Error', url=URL('http://ccab4aaf-frigate-fa-beta:5000/api/stats')
Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [None]

This error originated from a custom integration.

Logger: custom_components.frigate
Source: helpers/update_coordinator.py:344
integration: Frigate (documentation, issues)
First occurred: 28 June 2024 at 14:41:03 (22 occurrences)
Last logged: 09:05:31

Error fetching frigate data:
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

OpenVino

### Network connection

Wireless

### Camera make and model

Foscam R5, Reolink E1 Pro, Reolink Doorbell WiFi
