### DISCUSSION TITLE
[Support]: playback not working in 0.14.0-beta3

### DISCUSSION THREAD

**Discussion by GoldieLocks89** [blakeblackshear/frigate#12191] [General Support]
### Describe the problem you are having

Playback of events does not work for some cameras but works for others. 
All I get is a black spinner which spins and waits forever, the playback doesn't start.
The MP4 files are being saved correctly to the correct folder and I can play them back manually in VLC.

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: <REDACTED>
  password: <REDACTED>
  host: server

go2rtc:
  streams:
    driveway_front: 
      rtsp://<REDACTED>/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    driveway_front_sub: 
      rtsp://<REDACTED>/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    driveway_back: 
      rtsp://<REDACTED>/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    driveway_back_sub: 
      rtsp://<REDACTED>/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    front_left: 
      rtsp://<REDACTED>/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front_left_sub: 
      rtsp://<REDACTED>/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    front_right: 
      rtsp://<REDACTED>/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front_right_sub: 
      rtsp://<REDACTED>/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    back_garden: 
      rtsp://<REDACTED>/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    back_garden_sub: 
      rtsp://<REDACTED>/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    doorbell: 
      rtsp://<REDACTED>/cam/realmonitor?channel=1&subtype=0&authbasic=auth64
    doorbell_sub: 
      rtsp://<REDACTED>/cam/realmonitor?channel=1&subtype=1&authbasic=auth64

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - car
    - dog
    - cat
    - bird

ffmpeg:
  input_args: preset-rtsp-restream
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 5
    post_capture: 20
    retain:
      default: 7
      mode: active_objects

cameras:
  driveway_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_front
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_front_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 360
      height: 640
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    zones:
      driveway:
        coordinates: 360,0,241,0,151,0,49,85,83,148,21,208,100,307,360,640
    #live:
    #  stream_name: driveway_front_sub
  driveway_back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_back?video&audio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_back_sub?video&audio
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    zones:
      driveway:
        coordinates: 640,360,640,72,565,69,558,144,468,157,367,173,200,176,31,187,21,76,0,92,0,360
    #live:
    #  stream_name: driveway_back_sub
    motion:
      threshold: 40
      contour_area: 30
      improve_contrast: true
  front_left:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_left
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_left_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 6
    zones:
      front_garden:
        coordinates: 640,480,640,384,640,296,590,303,505,294,422,281,318,267,200,258,69,282,0,480
    #live:
    #  stream_name: front_left_sub
  front_right:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_right
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_right_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 480
      height: 640
      fps: 6
    zones:
      front_garden:
        coordinates: 116,640,224,477,312,353,361,263,393,162,371,103,247,48,87,0,39,233,0,640
    #live:
    #  stream_name: front_right_sub
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    motion:
      mask: 0.044,0.059,0.282,0.058,0.282,0.09,0.046,0.092
    #live:
    #  stream_name: back_garden_sub
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video&audio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video&audio
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 720
      height: 576
      fps: 10
    zones:
      front_garden:
        coordinates: 
          0.001,0.734,0.12,0.672,0.194,0.694,0.282,0.718,0.395,0.755,0.493,0.766,0.553,0.773,0.684,0.787,0.802,0.787,0.86,0.784,0.932,0.8,0.994,0.818,0.998,0.999,0.002,0.999
        inertia: 3
      front_garden_entrance:
        coordinates: 
          0,0.649,0.114,0.6,0.264,0.618,0.415,0.664,0.532,0.683,0.689,0.693,0.869,0.687,0.957,0.679,0.995,0.69,0.997,0.81,0.866,0.779,0.684,0.784,0.515,0.763,0.402,0.752,0.29,0.72,0.19,0.69,0.122,0.664,0.001,0.728
        inertia: 3
    motion:
      contour_area: 60
    #live:
    #  stream_name: doorbell_sub

tls:
  enabled: False

auth:
  enabled: False

version: 0.14
```

### Relevant log output

```shell
2024-06-28 19:18:09.771946499  [INFO] Preparing Frigate...
2024-06-28 19:18:09.791225133  [INFO] Starting Frigate...
2024-06-28 19:18:11.478168245  [2024-06-28 19:18:11] frigate.app                    INFO    : Starting Frigate (0.14.0-4e5a6eb)
2024-06-28 19:18:11.478201659  [2024-06-28 19:18:11] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-06-28 19:18:11.499071735  [2024-06-28 19:18:11] frigate.util.config            INFO    : frigate config does not need migration...
2024-06-28 19:18:13.301597101  [2024-06-28 19:18:13] peewee_migrate.logs            INFO    : Starting migrations
2024-06-28 19:18:13.302081288  [2024-06-28 19:18:13] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-06-28 19:18:13.318041717  [2024-06-28 19:18:13] frigate.app                    INFO    : Recording process started: 382
2024-06-28 19:18:13.321580156  [2024-06-28 19:18:13] frigate.app                    INFO    : Recording process started: 388
2024-06-28 19:18:13.322654552  [2024-06-28 19:18:13] frigate.app                    INFO    : go2rtc process pid: 98
2024-06-28 19:18:13.337314666  [2024-06-28 19:18:13] detector.ov                    INFO    : Starting detection process: 411
2024-06-28 19:18:13.339118776  [2024-06-28 19:18:13] frigate.app                    INFO    : Output process started: 413
2024-06-28 19:18:13.876780550  [2024-06-28 19:18:13] frigate.app                    INFO    : Camera processor started for driveway_front: 489
2024-06-28 19:18:13.882917145  [2024-06-28 19:18:13] frigate.app                    INFO    : Camera processor started for driveway_back: 490
2024-06-28 19:18:13.890160540  [2024-06-28 19:18:13] frigate.app                    INFO    : Camera processor started for front_left: 496
2024-06-28 19:18:13.898774599  [2024-06-28 19:18:13] frigate.app                    INFO    : Camera processor started for front_right: 513
2024-06-28 19:18:13.906349460  [2024-06-28 19:18:13] frigate.app                    INFO    : Camera processor started for back_garden: 521
2024-06-28 19:18:13.913171080  [2024-06-28 19:18:13] frigate.app                    INFO    : Camera processor started for doorbell: 529
2024-06-28 19:18:13.920484086  [2024-06-28 19:18:13] frigate.app                    INFO    : Capture process started for driveway_front: 537
2024-06-28 19:18:13.927595737  [2024-06-28 19:18:13] frigate.app                    INFO    : Capture process started for driveway_back: 540
2024-06-28 19:18:13.936250173  [2024-06-28 19:18:13] frigate.app                    INFO    : Capture process started for front_left: 546
2024-06-28 19:18:13.944693771  [2024-06-28 19:18:13] frigate.app                    INFO    : Capture process started for front_right: 551
2024-06-28 19:18:13.952961171  [2024-06-28 19:18:13] frigate.app                    INFO    : Capture process started for back_garden: 558
2024-06-28 19:18:13.964347393  [2024-06-28 19:18:13] frigate.app                    INFO    : Capture process started for doorbell: 565
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"cameras":{"back_garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":558,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":566,"pid":521,"process_fps":10.1,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":565,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":576,"pid":529,"process_fps":10.0,"skipped_fps":0.0},"driveway_back":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.0,"capture_pid":540,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":547,"pid":490,"process_fps":6.0,"skipped_fps":0.0},"driveway_front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":537,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":541,"pid":489,"process_fps":10.1,"skipped_fps":0.0},"front_left":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":546,"detection_enabled":true,"detection_fps":2.4,"ffmpeg_pid":554,"pid":496,"process_fps":6.0,"skipped_fps":0.0},"front_right":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":551,"detection_enabled":true,"detection_fps":3.4,"ffmpeg_pid":561,"pid":513,"process_fps":6.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"python3 -u -m frigate","cpu":"2.2","cpu_average":"6","mem":"1.7"},"129":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"163":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"164":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2179":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(56)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"342":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"360":{"cmdline":"sleep 9999","cpu":"0.0","cpu_average":"0","mem":"0.0"},"380":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"382":{"cmdline":"frigate.recording_manager","cpu":"1.9","cpu_average":"1","mem":"0.6"},"388":{"cmdline":"frigate.review_segment_manager","cpu":"0.6","cpu_average":"0","mem":"0.5"},"410":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(67)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"411":{"cmdline":"frigate.detector.ov  ","cpu":"7.2","cpu_average":"21","mem":"1.2"},"413":{"cmdline":"frigate.output       ","cpu":"1.5","cpu_average":"1","mem":"0.5"},"444":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 360x640 -i pipe: -threads 1 -f mpegts -s 405x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"449":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"45":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"454":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"459":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 480x640 -i pipe: -threads 1 -f mpegts -s 540x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"46":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"4603":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"464":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"469":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -threads 1 -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"474":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"489":{"cmdline":"frigate.process:driveway_front","cpu":"1.0","cpu_average":"1","mem":"0.7"},"490":{"cmdline":"frigate.process:driveway_back","cpu":"0.7","cpu_average":"1","mem":"0.7"},"496":{"cmdline":"frigate.process:front_left","cpu":"1.9","cpu_average":"1","mem":"0.7"},"513":{"cmdline":"frigate.process:front_right","cpu":"2.6","cpu_average":"2","mem":"0.7"},"521":{"cmdline":"frigate.process:back_garden","cpu":"1.2","cpu_average":"4","mem":"0.7"},"529":{"cmdline":"frigate.process:doorbell","cpu":"1.0","cpu_average":"1","mem":"0.7"},"537":{"cmdline":"frigate.capture:driveway_front","cpu":"0.5","cpu_average":"0","mem":"0.7"},"540":{"cmdline":"frigate.capture:driveway_back","cpu":"0.3","cpu_average":"0","mem":"0.7"},"541":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_front_sub -r 10 -vf fps=10,scale_vaapi=w=360:h=640:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.1","cpu_average":"0","mem":"0.2"},"546":{"cmdline":"frigate.capture:front_left","cpu":"0.3","cpu_average":"0","mem":"0.7"},"547":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_back_sub?video&audio -r 6 -vf fps=6,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.7","cpu_average":"0","mem":"0.2"},"548":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_front@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"551":{"cmdline":"frigate.capture:front_right","cpu":"0.4","cpu_average":"0","mem":"0.7"},"554":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_left_sub -r 6 -vf fps=6,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.2"},"557":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_back?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/driveway_back@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"1","mem":"0.1"},"558":{"cmdline":"frigate.capture:back_garden","cpu":"0.5","cpu_average":"0","mem":"0.7"},"561":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_right_sub -r 6 -vf fps=6,scale_vaapi=w=480:h=640:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.2"},"564":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_left -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_left@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.1"},"565":{"cmdline":"frigate.capture:doorbell","cpu":"0.7","cpu_average":"0","mem":"0.7"},"566":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_garden_sub -r 10 -vf fps=10,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.1","cpu_average":"0","mem":"0.2"},"576":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_sub?video&audio -r 10 -vf fps=10,scale_vaapi=w=720:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.4","cpu_average":"1","mem":"0.2"},"577":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_right -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_right@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"587":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_garden@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"588":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"0","mem":"0.1"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"13.3","cpu_average":"12","mem":"0.2"},"frigate.full_system":{"cpu":"11.0","mem":"44.4"}},"detection_fps":5.8,"detectors":{"ov":{"detection_start":0.0,"inference_speed":12.82,"pid":411}},"gpu_usages":{"intel-vaapi":{"gpu":"47.62%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":380},"recording":{"pid":382},"review_segment":{"pid":388}},"service":{"last_updated":1719598890,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":505.1,"mount_type":"tmpfs","total":512.0,"used":6.9},"/media/frigate/clips":{"free":890826.0,"mount_type":"fuse.shfs","total":5723166.5,"used":4829671.4},"/media/frigate/recordings":{"free":890826.0,"mount_type":"fuse.shfs","total":5723166.5,"used":4829671.4},"/tmp/cache":{"free":899.6,"mount_type":"tmpfs","total":953.7,"used":54.1}},"temperatures":{},"uptime":197,"version":"0.14.0-4e5a6eb"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

It used to work fine.. I've recently implemented go2rtc to get live view working reliably since updating to 0.14 and have been tweaking settings there, but can't figure out why playbacks don't work.

front left - doesn't work
back garden - does work
driveway back - doesn't work
doorbell - doesn't work

driveway front - does work
front right - does work
