### DISCUSSION TITLE
[Support]: Migration failed on startup

### DISCUSSION THREAD

**Discussion by Drizzt321** [blakeblackshear/frigate#12195] [General Support]
### Describe the problem you are having

So apparently the VM didn't mount the 2nd partition when I was migrating from 0.12.x to latest, so after https://github.com/blakeblackshear/frigate/discussions/12159 it started up fine, but quickly filled up the root partition.

The partition mounting is now fixed, but now frigate crashes during startup when it appears to be migrating old recordings/metadata to a new format. 

I'm running Debian 12.5 stable

```
frigate@darkfrigate:~/frigate/conf$ uname -a
Linux darkfrigate 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
frigate@darkfrigate:~/frigate/conf$ cat /etc/debian_version 
12.5
```

### Version

Latest

### Frigate config file

```yaml
mqtt:
  host: homeassistant
  user:  frigate
  password: <REDACTED>

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 120 
      mode: active_objects
      
cameras:
  alley_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.230/stream0 # 640x480 25fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.230/stream1 # 1920x1080 10fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10


  alley_2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.212:554/cam/realmonitor?channel=1&subtype=1 # 704x576 20fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.212:554/cam/realmonitor?channel=1&subtype=0 # 2592x1944 20fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 10

  alley_3: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.249:554/cam/realmonitor?channel=1&subtype=1 # 704x576 20fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.249:554/cam/realmonitor?channel=1&subtype=0 # 2592x1944 20fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 10


birdseye:
  enabled: True
  mode: continuous

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - skateboard
    - cat
    - umbrella
    - handbag
      #    - suitcase


snapshots:
  enabled: True
  timestamp: True
```


### Relevant log output

```shell
frigate@darkfrigate:~/frigate/conf$ docker compose up
WARN[0000] /home/frigate/frigate/conf/docker-compose.yml: `version` is obsolete 
[+] Running 2/2
 ✔ Network conf_default  Created                                                                                                                                                                                                                                  0.2s 
 ✔ Container frigate     Created                                                                                                                                                                                                                                  0.3s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2024-06-28 15:55:45.678388543  [INFO] Preparing Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | 2024-06-28 15:55:45.681171139  [INFO] Starting NGINX...
frigate  | 2024-06-28 15:55:45.683361726  [INFO] Preparing new go2rtc config...
frigate  | 2024-06-28 15:55:45.688153884  [INFO] Starting Frigate...
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-06-28 15:55:45.873969073  [INFO] Starting go2rtc...
frigate  | 2024-06-28 15:55:45.933321515  15:55:45.933 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-06-28 15:55:45.933776251  15:55:45.933 INF [rtsp] listen addr=:8554
frigate  | 2024-06-28 15:55:45.934244636  15:55:45.934 INF [webrtc] listen addr=:8555
frigate  | 2024-06-28 15:55:45.934704498  15:55:45.933 INF [api] listen addr=:1984
frigate  | 2024-06-28 15:55:46.641982321  [2024-06-28 15:55:46] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-06-28 15:55:46.642023032  [2024-06-28 15:55:46] frigate.app                    INFO    : Creating directory: /tmp/cache
frigate  | 2024-06-28 15:55:46.684357026  [2024-06-28 15:55:46] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-06-28 15:55:46.696251503  [2024-06-28 15:55:46] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
frigate  | 2024-06-28 15:55:46.696496246  [2024-06-28 15:55:46] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
frigate  | 2024-06-28 15:55:46.697787734  duplicate column name: score
frigate  | 2024-06-28 15:55:46.697905814  [2024-06-28 15:55:46] peewee_migrate.logs            ERROR   : Migration failed: 014_event_updates_for_fp
frigate  | 2024-06-28 15:55:46.697913920  Traceback (most recent call last):
frigate  | 2024-06-28 15:55:46.697939134    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3291, in execute_sql
frigate  | 2024-06-28 15:55:46.697945750      cursor.execute(sql, params or ())
frigate  | 2024-06-28 15:55:46.697951472  sqlite3.OperationalError: duplicate column name: score
frigate  | 2024-06-28 15:55:46.697957969  
frigate  | 2024-06-28 15:55:46.697964526  During handling of the above exception, another exception occurred:
frigate  | 2024-06-28 15:55:46.698001959  
frigate  | 2024-06-28 15:55:46.698007681  Traceback (most recent call last):
frigate  | 2024-06-28 15:55:46.698013284    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 200, in run_one
frigate  | 2024-06-28 15:55:46.698020675      migrator()
frigate  | 2024-06-28 15:55:46.698026278    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 76, in __call__
frigate  | 2024-06-28 15:55:46.698052684      op.run()
frigate  | 2024-06-28 15:55:46.698058346    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
frigate  | 2024-06-28 15:55:46.698063592      self._handle_result(method(*self.args, **kwargs))
frigate  | 2024-06-28 15:55:46.698072771    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 156, in _handle_result
frigate  | 2024-06-28 15:55:46.698090057      self._handle_result(item)
frigate  | 2024-06-28 15:55:46.698095898    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 153, in _handle_result
frigate  | 2024-06-28 15:55:46.698101442      result.run()
frigate  | 2024-06-28 15:55:46.698107164    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
frigate  | 2024-06-28 15:55:46.698112707      self._handle_result(method(*self.args, **kwargs))
frigate  | 2024-06-28 15:55:46.698131781    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 151, in _handle_result
frigate  | 2024-06-28 15:55:46.698137742      self.execute(result)
frigate  | 2024-06-28 15:55:46.698143404    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 147, in execute
frigate  | 2024-06-28 15:55:46.698149007      self.migrator.database.execute(node)
frigate  | 2024-06-28 15:55:46.698155922    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3299, in execute
frigate  | 2024-06-28 15:55:46.698162419      return self.execute_sql(sql, params)
frigate  | 2024-06-28 15:55:46.698167902    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3291, in execute_sql
frigate  | 2024-06-28 15:55:46.698188169      cursor.execute(sql, params or ())
frigate  | 2024-06-28 15:55:46.698193652    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3059, in __exit__
frigate  | 2024-06-28 15:55:46.698198957      reraise(new_type, new_type(exc_value, *exc_args), traceback)
frigate  | 2024-06-28 15:55:46.698204322    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
frigate  | 2024-06-28 15:55:46.698209686      raise value.with_traceback(tb)
frigate  | 2024-06-28 15:55:46.698215051    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3291, in execute_sql
frigate  | 2024-06-28 15:55:46.698220594      cursor.execute(sql, params or ())
frigate  | 2024-06-28 15:55:46.698226197  peewee.OperationalError: duplicate column name: score
frigate  | 2024-06-28 15:55:46.836146844  192.168.10.6 - - [28/Jun/2024:15:55:46 -0700] "GET / HTTP/1.1" 200 10672 "-" "HomeAssistantSupervisor/2024.06.2 aiohttp/3.9.5 Python/3.12" "-"
frigate  | 2024-06-28 15:55:47.859779178  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2024-06-28 15:55:47.870934363  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-06-28 15:55:47.943847791  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | 2024-06-28 15:55:47.948216509  exit with signal: terminated
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2024-06-28 15:55:47.952188250  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```


### FFprobe output from your camera

```shell
N/A
```


### Frigate stats

```json
N/A
```


### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

_No response_
