### DISCUSSION TITLE
[Bug]: Detection & live streams fail when using network storage

### DISCUSSION THREAD

**Discussion by BaQs** [blakeblackshear/frigate#12209] [Report a Bug]
### Describe the problem you are having

Hello,
When using HA network storage, my live streams are much longer to load ("no frames have been received, check error logs..." for 10s) and it seems no detection is possible.

### Steps to reproduce

use attached config with local storage (confirm all is working fine).
Now, mount /media/frigate using Home Assistant network storage (I'm using smb - it works ok when reading/creating file by  using HA terminal)
detection (records when a person or a car is detected) does not seem to work & live streams are very slow to load

### Version

0.14-beta3

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate.local.hass.io:5000/api/config/schema.json

mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  user: homeassistant
  password: xxxxxxxx

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  # logs:
  #  frigate.mqtt: debug

database:
  path: /config/frigate.db

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  restream: true


detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog

record:
  enabled: true
  # bounding_box: True # not possible here :/
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  log:
    exec: trace
  streams:

    camera_m_main:
      - rtsp://admin:xxx554/ch1/main
    camera_m_sub:
      - rtsp://admin:xxx:554/ch1/sub

    camera_v_main:
      - rtsp://admin:x:554/ch1/mainxx
    camera_v_sub:
      - rtsp://admin:xxx:554/ch1/sub

    couloir_main:
      - rtsp://admin:xxx:554/ch1/main
    couloir_sub:
      - rtsp://admin:xxx:554/ch1/sub

    rue_main:
      - rtsp://admin:xxx:554/ch1/main
    rue_sub:
      - rtsp://admin:xxx:554/ch1/sub


    jardin_main:
      - rtsp://admin:xxx:554/ch1/main
    jardin_sub:
      - rtsp://admin:xxx:554/ch1/sub

    sdj_main:
      - rtsp://admin:xxx:554/ch1/main
    sdj_sub:
      - rtsp://admin:xxx:554/ch1/sub




cameras:


  camera_m:
    live:
      stream_name: camera_m_sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_m_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_m_sub
          input_args: preset-rtsp-restream
          roles:
            - detect


  camera_v:
    live:
      stream_name: camera_v_sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_v_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_v_sub
          input_args: preset-rtsp-restream
          roles:
            - detect


  Couloir:
    live:
      stream_name: couloir_sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/couloir_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/couloir_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

  Jardin:
    live:
      stream_name: jardin_sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/jardin_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/jardin_sub
          input_args: preset-rtsp-restream
          roles:
            - detect


  SDJ:
    live:
      stream_name: sdj_sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/sdj_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sdj_sub
          input_args: preset-rtsp-restream
          roles:
            - detect



  Devant:
    live:
      stream_name: rue_sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/rue_main
          input_args: preset-rtsp-restream
          roles:
        #    - detect
            - record
        - path: rtsp://127.0.0.1:8554/rue_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.634,1,0.671,0.826,0.651,0.725,0.689,0.669,0.6,0.44,0.557,0.275,0.754,0,1,0,1,1
    zones:
      Parking:
        coordinates: 0.385,0.668,0.628,0.631,0.652,0.756,0.395,0.812
        loitering_time: 5
        objects: car
        inertia: 3
      Parking2:
        coordinates: 0.177,0.588,0.329,0.587,0.334,0.533,0.204,0.535
        objects: car
    review:
      alerts:
        required_zones: Parking
      detections:
        required_zones:
          - Parking
          - Parking2
telemetry:
  network_interfaces:
    - eth0
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
version: 0.14
```

### Relevant log output

```shell
2024-06-29 20:43:53.720114184  [2024-06-29 22:43:53] watchdog.Couloir               INFO    : Terminating the existing ffmpeg process...
2024-06-29 20:43:53.720119473  [2024-06-29 22:43:53] watchdog.Couloir               INFO    : Waiting for ffmpeg to exit gracefully...
2024-06-29 20:43:54.132217935  [2024-06-29 22:43:54] ffmpeg.Madeleine.record        ERROR   : [rtsp @ 0x5615dcaa5d80] Missing PPS in sprop-parameter-sets, ignoring
2024-06-29 20:43:54.132234635  [2024-06-29 22:43:54] ffmpeg.Madeleine.record        ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device
2024-06-29 20:43:54.147998718  [2024-06-29 22:43:54] ffmpeg.Madeleine.record        ERROR   : Error initializing output stream 0:1 -- 
2024-06-29 20:43:54.149477555  [2024-06-29 22:43:54] watchdog.Madeleine             INFO    : Terminating the existing ffmpeg process...
2024-06-29 20:43:54.149481406  [2024-06-29 22:43:54] watchdog.Madeleine             INFO    : Waiting for ffmpeg to exit gracefully...




[core-ssh ~]$ df -h /media/frigate/
Filesystem                Size      Used Available Use% Mounted on
//black4/cameras          3.5T      3.1T    404.8G  89% /media/frigate
[core-ssh ~]$


[core-ssh ~]$ touch /media/frigate/test
[core-ssh ~]$ ls -l /media/frigate/test
-rwxr-xr-x    1 root     root             0 Jun 29 22:46 /media/frigate/test
[core-ssh ~]$ rm /media/frigate/test
[core-ssh ~]$
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wireless

### Camera make and model

ezviz c6n & lc3
