### DISCUSSION TITLE
Frigate unresponsive, causing system halt [SOLVED]

### DISCUSSION THREAD

**Discussion by Welsyntoffie** [blakeblackshear/frigate#12217] [General]
Been having issues since version 14. The ram would increase to 100% at random times, ha integration would report unavailable, then available few seconds later, but  the complete system is unusable. The recording disc was having a smart warning about command timeouts that increasing. So I replaced the drive. Still the same issue.
This morning I decided to RESTART from scratch and install Debian 12.6 on a new drive.
1 Hour after starting frigate it crashed the system. Memory full. Unable to keep up with recording segments. FFMPEG process crashed.
I have no logs as I formatted everything. Did not even want to bother further getting logs as I am tired of trying everything. Im running and gunning now.

Now I restarted version 13.2 to see if the crashes persist even though I know its still the same frigate. Just shooting in the dark.

**Comment by hawkeye217** [comment]
Frigate 0.14 is working well for most users, so the only way we'll be able to help is with your config and full logs.

**Reply by Welsyntoffie** [reply]
I do understand, thank you.
It might even be hardware related. Which is why I want to run an older version to check.

**Comment by Welsyntoffie** [comment]
Should probably start somewhere. This is my config contents.
Reinstalled EVERYTHING and started from scratch.
Frigate 14 Beta 3. Waiting for logs...

```
mqtt:
enabled: true
host: 172.22.2.111
port: 1884
user: mqttuser
password: mqttuser
client_id: frigate_mint
topic_prefix: frigate_mint
stats_interval: 300

tls:
  enabled: false

telemetry:
  version_check: false
  stats:
    amd_gpu_stats: true
    intel_gpu_stats: true  
    network_bandwidth: true

timestamp_style:
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 1

ui:
  time_format: browser
  date_style: medium
  time_style: medium

logger:
  default: info
  logs:
    frigate.mqtt: error

birdseye:
  enabled: true
  mode: objects

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    Back_Yard:
      - rtsp://admin:password@172.22.2.170:8554/live0.264
    Back_Yard_sub:
      - rtsp://admin:password@172.22.2.170:8554/live1.264
    Driveway:
      - rtsp://admin:password@172.22.2.172:8554/live0.264
    Driveway_sub:
      - rtsp://admin:password@172.22.2.172:8554/live1.264
    SideWindows:
      - onvif://admin:password@172.22.2.171:80?subtype=MainStreamToken
    SideWindows_sub:
      - onvif://admin:password@172.22.2.171:80?subtype=SubStreamToken
    Stoep:
      - rtsp://admin:password@172.22.2.173:8554/live0.264
    Stoep_sub:
      - rtsp://admin:password@172.22.2.173:8554/live1.264
    pcroom:
      - rtsp://admin:password@172.22.2.175:554/cam/realmonitor?channel=1&subtype=0
    pcroom_sub:
      - rtsp://admin:password@172.22.2.175:554/cam/realmonitor?channel=1&subtype=1
    front_windows:
      - rtsp://admin:password@172.22.2.174:554/ISAPI/Streaming/Channels/101
    front_windows_sub:
      - rtsp://admin:password@172.22.2.174:554/ISAPI/Streaming/Channels/102
    Front_Yard:
      - onvif://admin:password@172.22.2.176:80?subtype=MainStreamToken
    Front_Yard_sub:
      - onvif://admin:password@172.22.2.176:80?subtype=SubStreamToken
  webrtc:
    candidates:
      - 172.22.2.111:8555
      - stun:8555

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  Back_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/Back_Yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://172.22.2.111:8554/Back_Yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Back_Yard
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
      max_disappeared: 50
      stationary:
        threshold: 100
        max_frames:
          objects:
            person: 3000
    objects:
      track:
        - person
      filters:
        car:
          mask: 0,0.212,0.331,0.092,0.58,0.058,0.692,0.128,1,0.286,1,0,0,0
        person:
          min_area: 1500
          max_area: 100000
          mask: 0,0.203,0.331,0.092,0.58,0.058,0.692,0.128,1,0.286,1,0,0,0
    zones:
      Back_Yard_close:
        inertia: 3
        coordinates: 0,0.923,1,0.919,1,1,0,1
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75 
      Back_Yard_far:
        inertia: 3
        coordinates: 0.967,0.886,0.575,0.183,0,0.324,0,0.903
        objects: person
        filters:
          person:
            min_area: 1000
            max_area: 100000
            threshold: 0.75
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - Back_Yard_close
        - Back_Yard_far
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - car
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 10
            car: 10
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - Back_Yard_close
        - Back_Yard_far
      retain:
        default: 7
        objects:
          car: 7
          person: 7
    motion:
      improve_contrast: false
      mqtt_off_delay: 20
      mask: 0,0.211,0.331,0.092,0.58,0.058,0.692,0.128,1,0.286,1,0,0,0
    review:
      detections:
        required_zones:
          - Back_Yard_close
          - Back_Yard_far
    ui:
      order: 5
      dashboard: true

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://172.22.2.111:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
      max_disappeared: 50
      stationary:
        threshold: 100
        max_frames:
          objects:
            person: 3000
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask: 0.366,0,0.213,0.082,0,0.186,0,0
          min_area: 1000
          max_area: 100000
        car:
          min_area: 2000
          max_area: 100000
          threshold: 0.75

    zones:
      Driveway_windows:
        inertia: 10 
        coordinates: 0.793,0.285,0.753,1,0.644,1,0.734,0.311
        objects: person
        filters:
          person:
            min_area: 1000
            max_area: 100000
            threshold: 0.75
      Driveway_close:
        inertia: 3
        coordinates: 0.394,0.532,0.695,0.567,0.622,1,0.145,1
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
      Driveway_far:
        inertia: 3
        coordinates: 
          0.545,0.236,0.527,0,0.698,0,0.7,0.2,0.792,0.197,0.784,0.264,0.73,0.292,0.693,0.551,0.402,0.524
        objects:
          - person
          - car
        filters:
          person:
            min_area: 500
            max_area: 100000
            threshold: 0.75
          car:
            min_area: 2000
            max_area: 100000
      Driveway_lawn:
        inertia: 3
        coordinates: 0.548,0.225,0.206,0.853,0,0.907,0,0.436,0.461,0.072,0.506,0.142
        objects: person
        filters:
          person:
            min_area: 500
            max_area: 100000
            threshold: 0.75
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - Driveway_close
        - Driveway_far
        - Driveway_windows
        - Driveway_lawn

    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - Driveway_close
        - Driveway_far
        - Driveway_windows
        - Driveway_lawn
      retain:
        default: 7
        objects:
          person: 7

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 10
          mode: active_objects

    motion:
      improve_contrast: false
      mqtt_off_delay: 20
      mask:
        - 0.71,0.095,0.709,0.148,0.808,0.153,0.811,0.094,1,0.094,1,0,0,0,0,0.372,0.477,0.086
        - 0.739,0.631,0.777,0.633,0.777,0.569,0.744,0.572
    review:
      detections:
        required_zones:
          - Driveway_close
          - Driveway_far
          - Driveway_lawn
          - Driveway_windows
    ui:
      order: 4
      dashboard: true

  SideWindows:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/SideWindows
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://172.22.2.111:8554/SideWindows_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
      max_disappeared: 50
      stationary:
        threshold: 100
        max_frames:
          objects:
            person: 3000
      annotation_offset: 0
    objects:
      track:
        - person
      filters:
        person:
          min_area: 1000
          max_area: 100000
          mask: 0.386,0.1,0.405,0.499,0.042,0.847,0.005,0.691,0,0.144
    zones:
      SideWindows_Close:
        inertia: 10
        coordinates: 0.592,0.347,0,0.925,0,1,0.436,1,0.643,0.491,0.6,0.475
        objects: person
        filters:
          person:
            min_area: 4000
            max_area: 100000
            threshold: 0.75
      SideWindows_Far:
        inertia: 3
        coordinates: 0.645,0.519,0.655,0.428,0.895,0.456,1,0.561,1,1,0.46,1
        objects: person
        filters:
          person:
            min_area: 2500
            max_area: 100000
            threshold: 0.75
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - SideWindows_Close
        - SideWindows_Far

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 10

    motion:
      improve_contrast: false
      mqtt_off_delay: 20
      mask:
        - 0.595,0.369,0.847,0.411,0.893,0.377,1,0.469,1,0,0.608,0
        - 0.287,0,0.288,0.079,0,0.1,0,0
        - 0.284,0.106,0.408,0.108,0.408,0.509,0.047,0.878,0,0.742,0,0.169
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - SideWindows_Close
        - SideWindows_Far
      retain:
        default: 7
        objects:
          person: 7

    review:
      detections:
        required_zones:
          - SideWindows_Close
          - SideWindows_Far
    ui:
      order: 6
      dashboard: true

  Stoep:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/Stoep
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://172.22.2.111:8554/Stoep_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
      max_disappeared: 50
      stationary:
        threshold: 100
        max_frames:
          objects:
            person: 3000
    objects:
      track:
        - person
      filters:
        person:
          min_area: 2000
          max_area: 100000
          mask: 0.13,0.745,0.134,1,0,1,0,0.756
    zones:
      Stoep_Close:
        inertia: 3
        coordinates: 0.565,0.484,0.616,1,0.235,1,0.368,0.475
        objects: person
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.75
      Stoep_Far:
        inertia: 3
        coordinates: 
          0.36,0.148,0.623,0.153,0.617,0.379,0.369,0.403,0.215,1,0,0.991,0.005,0.66,0.097,0.361,0.198,0.182
        objects: person
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.75
      Stoep_Windows:
        inertia: 10
        coordinates: 
          0.65,0.484,0.687,0,0.872,0.185,0.838,0.518,0.995,0.782,1,0.991,0.628,0.99,0.572,0.484
        objects: person
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.75
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - Stoep_Close
        - Stoep_Far
        - Stoep_Windows

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 10

    motion:
      improve_contrast: false
      mqtt_off_delay: 20
      mask: 0,0.42,0.222,0.137,0.398,0.119,0.653,0.102,0.657,0,0,0
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - Stoep_Close
        - Stoep_Far
        - Stoep_Windows
      retain:
        default: 7
        objects:
          person: 7

    review:
      detections:
        required_zones:
          - Stoep_Close
          - Stoep_Far
          - Stoep_Windows
    ui:
      order: 0
      dashboard: true

  pcroom:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/pcroom
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      max_disappeared: 50
      stationary:

        threshold: 100
        max_frames:
          objects:
            person: 3000
    objects:
      track:
        - person
      filters:
        person:
          min_area: 2000
          max_area: 100000

    zones:
      garage_close:
        inertia: 3
        coordinates: 0.691,0.637,0.407,0.526,0.106,1,0.623,1
        objects: person
        filters:
          person:
            min_area: 2500
            max_area: 100000
            threshold: 0.75
      garage_far:
        inertia: 3
        coordinates: 0.421,0.513,0.69,0.626,0.745,0.245,0.628,0.197
        objects: person
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.75
      garage_lawn_close:
        inertia: 3
        coordinates: 0.914,0.442,1,0.706,1,1,0.644,1,0.726,0.446
        objects: person
        filters:
          person:
            min_area: 2500
            max_area: 100000
            threshold: 0.75
      garage_lawn_far:
        inertia: 3
        coordinates: 0.806,0.187,0.912,0.429,0.729,0.431,0.758,0.185
        objects: person
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.75
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - garage_close
        - garage_far
        - garage_lawn_close
        - garage_lawn_far

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 10

    motion:

      threshold: 65
      contour_area: 40
      improve_contrast: false
      mqtt_off_delay: 20
      mask: 0,0.055,0.848,0.081,1,0.237,1,0.058,1,0,0,0
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - garage_close
        - garage_far
        - garage_lawn_close
        - garage_lawn_far
      retain:
        default: 4
        objects:
          person: 4

    review:
      detections:
        required_zones:
          - garage_close
          - garage_far
          - garage_lawn_close
          - garage_lawn_far
    ui:
      order: 7
      dashboard: true

  front_windows:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/front_windows
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 150000

    zones:
      front_windows_stoep:
        inertia: 3
        coordinates: 
          0.918,0.252,1,0.369,0.939,0.659,0.906,0.765,0.84,0.678,0.547,1,0.425,0.672,0.421,0.266,0.793,0.265
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 150000
            threshold: 0.75
      front_windows_yard:
        inertia: 3
        coordinates: 0.114,0.445,0.133,0.804,0.249,0.767,0.314,1,0,1,0,0.433
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 150000
            threshold: 0.75
      front_windows_windows:
        inertia: 3
        coordinates: 0.128,0.28,0.149,0.772,0.246,0.743,0.19,0.254
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 150000
            threshold: 0.75
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - front_windows_stoep
        - front_windows_yard
        - front_windows_windows

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 10

    motion:
      threshold: 65
      contour_area: 40
      improve_contrast: false
      mqtt_off_delay: 20
      mask: 0,0.206,0.181,0.094,0.235,0.241,0.915,0.231,0.943,0,0,0
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - front_windows_stoep
        - front_windows_yard
        - front_windows_windows
      retain:
        default: 4
        objects:
          person: 4

    review:
      detections:
        required_zones:
          - front_windows_stoep
          - front_windows_windows
          - front_windows_yard
    ui:
      order: 1
      dashboard: true

  Front_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://172.22.2.111:8554/Front_Yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://172.22.2.111:8554/Front_Yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Front_Yard
    detect:
      enabled: true
      width: 768
      height: 432

      fps: 5
      max_disappeared: 50
      stationary:
        threshold: 100
        max_frames:
          objects:
            person: 3000
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask: 0,0.164,0.286,0.127,0.577,0.131,0.719,0.093,1,0.227,1,0,0,0
        person:
          min_area: 1500
          max_area: 100000
          mask: 0,0.164,0.286,0.127,0.573,0.134,0.72,0.097,1,0.227,1,0,0,0
    zones:
      Front_Yard_close:
        inertia: 3
        coordinates: 0.409,0.527,0.836,0.505,1,0.706,1,1,0.477,1
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.75
      Front_Yard_far:
        inertia: 3
        coordinates: 0.842,0.482,0.646,0.243,0.387,0.257,0.418,0.509
        objects:
          - person
          - car
        filters:
          person:
            min_area: 1000
            max_area: 100000
            threshold: 0.75
      Front_Yard_lawn_close:
        inertia: 3
        coordinates: 0.456,1,0.389,0.496,0,0.469,0,1
        objects: person
        filters:
          person:
            min_area: 1000
            max_area: 100000
            threshold: 0.75
      Front_Yard_lawn_far:
        inertia: 3
        coordinates: 0.377,0.477,0.327,0.199,0,0.22,0,0.451
        objects: person
        filters:
          person:
            min_area: 1000
            max_area: 100000
            threshold: 0.75 
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 99
      height: 370
      required_zones:
        - Front_Yard_close
        - Front_Yard_far
        - Front_Yard_lawn_close
        - Front_Yard_lawn_far

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - car
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 10
            car: 10

    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
      quality: 99
      required_zones:
        - Front_Yard_close
        - Front_Yard_far
        - Front_Yard_lawn_close
        - Front_Yard_lawn_far
      retain:
        default: 7
        objects:
          car: 7
          person: 7

    motion:
      improve_contrast: false
      mqtt_off_delay: 20
      mask: 0,0.164,0.286,0.127,0.573,0.134,0.723,0.096,1,0.227,1,0,0,0
    review:
      detections:
        required_zones:
          - Front_Yard_close
          - Front_Yard_far
          - Front_Yard_lawn_close
    ui:
      order: 2
      dashboard: true

version: 0.14
camera_groups:
  Main:
    order: 1
    icon: LuActivity
    cameras:
      - birdseye
      - Back_Yard
      - Driveway
      - Front_Yard
      - SideWindows
      - Stoep
      - front_windows
      - pcroom

```
