### DISCUSSION TITLE
[Bug]: Firefox only - Picture in Picture

### DISCUSSION THREAD

**Discussion by ubawurinna** [blakeblackshear/frigate#12215] [Report a Bug] [answered]
### Describe the problem you are having

On Firefox (this works on Chrome-based browsers) the Picture in Picture function does not work as expected.

### Steps to reproduce

When you click on the Picture in Picture button, the whole page turns white (not only the live view but also the Frigate interface disappears).
Instead of clicking on button, if you click on the hover button, it works.

Now, if you close the floating view, the live view is no longer displayed.
Unless you switch the floating view to full screen before closing it, in which case the live view is redisplayed.

### Version

last dev (2024-06-30)

### Frigate config file

```yaml
go2rtc:
  streams:
    stream_main:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    stream_sub:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  tapo_c510w:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stream_sub
          roles:
            - detect
    live:
      stream_name: stream_main
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Tapo

**Comment by hawkeye217** [comment]
Thanks for the report. This is fixed in https://github.com/blakeblackshear/frigate/pull/12216

As you noted, Firefox doesn't support the picture-in-picture method that Chrome-based browsers use. So the PR just disables the top bar button for Firefox. PiP can still be achieved via the hover button.

**Comment by ubawurinna** [comment]
There is still a problem when the floating view is displayed and then closed.  

I've included 2 configuration examples below
With the first configuration, when you close the floating view, the live view is **no longer displayed**.
With the second configuration, when you close the floating view, the live view reappears, but **switches to the low-resolution stream**.  

In the second configuration, the high stream has the same name as the camera.
In both case, if you switch the floating view to full screen before closing, all works as expected

``` config 1
go2rtc:
  streams:
    highres:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    lowres:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lowres
          roles:
            - detect
    live:
      stream_name: highres
```

```
go2rtc:
  streams:
    camera1:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    lowres:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lowres
          roles:
            - detect
    live:
      stream_name: camera1
```
