### DISCUSSION TITLE
[Support]: How to acces web UI after installation?

### DISCUSSION THREAD

**Discussion by Mo7mud** [blakeblackshear/frigate#12214] [General Support] [answered]
### Describe the problem you are having

I installed Frigate on Linux with docker but I don't know how to access web UI and I can't find it in the docs
I tried `127.0.0.1` but didn't work

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/car-stopping.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5
```

### Relevant log output

```shell
WARN[0000] /home/mohammad/Downloads/frigate/docker-compose.yml: `version` is obsolete 
[+] Running 2/0
 ✔ Container frigate-devcontainer  Created                                                                           0.0s 
 ✔ Container mqtt                  Created                                                                           0.0s 
Attaching to frigate-devcontainer, mqtt
mqtt                  | 1719705489: mosquitto version 1.6.15 starting
mqtt                  | 1719705489: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt                  | 1719705489: Opening ipv4 listen socket on port 1883.
mqtt                  | 1719705489: Opening ipv6 listen socket on port 1883.
mqtt                  | 1719705489: mosquitto version 1.6.15 running
frigate-devcontainer  | s6-rc: info: service s6rc-fdholder: starting
frigate-devcontainer  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-devcontainer  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-devcontainer  | s6-rc: info: service fix-attrs: starting
frigate-devcontainer  | s6-rc: info: service s6rc-fdholder successfully started
frigate-devcontainer  | s6-rc: info: service fix-attrs successfully started
frigate-devcontainer  | s6-rc: info: service legacy-cont-init: starting
frigate-devcontainer  | s6-rc: info: service legacy-cont-init successfully started
frigate-devcontainer  | s6-rc: info: service log-prepare: starting
frigate-devcontainer  | s6-rc: info: service log-prepare successfully started
frigate-devcontainer  | s6-rc: info: service nginx-log: starting
frigate-devcontainer  | s6-rc: info: service go2rtc-log: starting
frigate-devcontainer  | s6-rc: info: service frigate-log: starting
frigate-devcontainer  | s6-rc: info: service certsync-log: starting
frigate-devcontainer  | s6-rc: info: service nginx-log successfully started
frigate-devcontainer  | s6-rc: info: service frigate-log successfully started
frigate-devcontainer  | s6-rc: info: service certsync-log successfully started
frigate-devcontainer  | s6-rc: info: service go2rtc-log successfully started
frigate-devcontainer  | s6-rc: info: service go2rtc: starting
frigate-devcontainer  | s6-rc: info: service go2rtc successfully started
frigate-devcontainer  | s6-rc: info: service go2rtc-healthcheck: starting
frigate-devcontainer  | s6-rc: info: service frigate: starting
frigate-devcontainer  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-devcontainer  | s6-rc: info: service frigate successfully started
frigate-devcontainer  | s6-rc: info: service nginx: starting
frigate-devcontainer  | 2024-06-30 02:58:09.748233292  [INFO] The fake Frigate service is running...
frigate-devcontainer  | 2024-06-30 02:58:09.780182533  [INFO] Starting NGINX...
frigate-devcontainer  | 2024-06-30 02:58:09.795052034  [INFO] Preparing new go2rtc config...
frigate-devcontainer  | s6-rc: info: service nginx successfully started
frigate-devcontainer  | s6-rc: info: service certsync: starting
frigate-devcontainer  | s6-rc: info: service certsync successfully started
frigate-devcontainer  | 2024-06-30 02:58:10.029095850  [INFO] Starting certsync...
frigate-devcontainer  | s6-rc: info: service legacy-services: starting
frigate-devcontainer  | 2024-06-30 02:58:10.136246255  127.0.0.1 - - [30/Jun/2024:02:58:10 +0300] "" 400 0 "-" "-" "-"
frigate-devcontainer  | s6-rc: info: service legacy-services successfully started
frigate-devcontainer  | 2024-06-30 02:58:10.194095780  [INFO] Starting go2rtc...
frigate-devcontainer  | 2024-06-30 02:58:10.304567668  02:58:10.304 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate-devcontainer  | 2024-06-30 02:58:10.304759838  02:58:10.304 INF config path=/dev/shm/go2rtc.yaml
frigate-devcontainer  | 2024-06-30 02:58:10.305208533  02:58:10.305 INF [api] listen addr=:1984
frigate-devcontainer  | 2024-06-30 02:58:10.305346485  02:58:10.305 INF [rtsp] listen addr=:8554
frigate-devcontainer  | 2024-06-30 02:58:10.305597179  02:58:10.305 INF [webrtc] listen addr=:8555/tcp
```

### FFprobe output from your camera

```shell
No web UI yet
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

None

**Comment by hawkeye217** [comment]
The frigate UI runs on port 5000 of your host.

**Reply by Mo7mud** [reply]
> The frigate UI runs on port 5000 of your host.

403 Forbidden

**Reply by hawkeye217** [reply]
What is your docker compose?

**Reply by Mo7mud** [reply]
> What is your docker compose?

```
version: "3.9"
services:
  devcontainer:
    container_name: frigate-devcontainer
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: yolov7-320
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
```
