### DISCUSSION TITLE
[Support]: How do I get the OpenVINO models in the proper format?

### DISCUSSION THREAD

**Discussion by Redsandro** [blakeblackshear/frigate#12226] [General Support] [answered]
### Describe the problem you are having

I've been using the Coral with much joy and happiness. Now I want to try OpenVINO so I can use the Intel Arc Alchemist iGPU in my NUC 14.

But how do I get the model? [Instructions unclear](https://docs.frigate.video/configuration/object_detectors/#openvino-detector). According to the instructions, I need a .txt and a .xml file. But all `omz_downloader --name yolox*` is giving me is a file called `yolox_tiny.pth`.

### Version

0.12

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /path/to/yolox_tiny.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolox
  labelmap_path: /path/to/coco_80cl.txt
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
The main config can be used as is, the model is included

**Reply by ubawurinna** [reply, marked as answer]
You can build YOLOX Tiny with Google Colab:
```
# Frigate 0.13.2 use 2022.3.0
# Frigate 0.14.0 beta 3 use 2024.1.0 <= (Not working)
openvino_release='2022.3.0'

!pip install openvino-dev=={openvino_release}
!pip install onnx

# clone open_model_zoo
!git clone https://github.com/openvinotoolkit/open_model_zoo.git
%cd /content/open_model_zoo
!git -c advice.detachedHead=false checkout tags/{openvino_release}

%cd /content/open_model_zoo/tools/model_tools
!pip install --upgrade pip
!pip install .

!omz_downloader --name yolox-tiny
!omz_converter --name yolox-tiny
%cp /content/open_model_zoo/data/dataset_classes/coco_80cl.txt /content/open_model_zoo/tools/model_tools/public/yolox-tiny/FP16/
%cd /content/open_model_zoo/tools/model_tools/public/yolox-tiny/FP16/
!zip -r yolox-tiny ./

from google.colab import files
files.download('/content/open_model_zoo/tools/model_tools/public/yolox-tiny/FP16/yolox-tiny.zip')
```

Place generated .bin, .mapping, .xml and .txt files side by side in /config/yolox for example

In your configuration:
```
model:
  model_type: yolox
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolox/yolox_tiny.xml
  labelmap_path: /config/yolox/coco_80cl.txt
```
