### DISCUSSION TITLE
[Support]: 0.14b3 RockChip installation went kaput.

### DISCUSSION THREAD

**Discussion by jonadis** [blakeblackshear/frigate#12228] [General Support]
### Describe the problem you are having

I've been really enjoying the latest beta of 0.14 on my Orange Pi 5B (16GB) but sometime today most of the cameras stopped working and I tried restarting everything but no matter how much I restart it will only load a camera or two at a time.  I have gone as far as completely deleting the container (but leaving the DB, recording, etc files in place) and re-creating the container, even updating to the latest commit but I'm still in the same place.

### Version

0.14.0-f050c7b

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.0.71.64:5000/api/config/schema
mqtt:
  host: 10.0.71.10
  user: DVES_USER
  password: DVES_PASS

detectors: # required
  rknn: # required
    type: rknn # required
    # number of NPU cores to use
    # 0 means choose automatically
    # increase for better performance if you have a multicore NPU e.g. set to 3 on rk3588
    num_cores: 3

model: # required
  # name of model (will be automatically downloaded) or path to your own .rknn model file
  # possible values are:
  # - deci-fp16-yolonas_s
  # - deci-fp16-yolonas_m
  # - deci-fp16-yolonas_l
  # - /config/model_cache/your_custom_model.rknn
  path: deci-fp16-yolonas_s
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolo models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

auth:
  reset_admin_password: false

birdseye:
  mode: motion

ffmpeg:
  hwaccel_args: preset-rk-h264
  output_args:
    record: preset-record-generic-audio-aac

detect:
  fps: 5
  enabled: true

objects:
  track:
    - car
    - cat
    - dog
    - person
  filters:
    car:
      min_area: 5000
      min_score: 0.6
      threshold: 0.80
    cat:
      min_area: 1000
      min_score: 0.6
      threshold: 0.80
    dog:
      min_area: 1000
      min_score: 0.6
      threshold: 0.80
    person:
      min_area: 5000
      min_score: 0.6
      threshold: 0.80

motion:
  contour_area: 20
  threshold: 40

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 14
      mode: motion

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

go2rtc:
  streams:
    chicken: rtsp://admin:admin@10.0.71.224:18554/chicken
      #esp32_cam: http://10.4.10.68:8080
    front_door: 
      rtsp://admin:redacted@10.0.71.131/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_door_sub: 
      rtsp://admin:redacted@10.0.71.131/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    front_driveway: rtsp://admin:redacted@10.0.71.155:554/Streaming/Channels/101
    front_driveway_sub: rtsp://admin:redacted@10.0.71.155:554/Streaming/Channels/102
    front_porch: 
      rtsp://admin:redacted@10.0.71.11/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_porch_sub: 
      rtsp://admin:redacted@10.0.71.11/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    garage: rtsp://admin:redacted@10.0.71.81:554/Streaming/Channels/101
    garage_sub: rtsp://admin:redacted@10.0.71.81:554/Streaming/Channels/102
    # garage_se:
    #   - ffmpeg:http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted#video=copy#audio=copy#audio=opus
    # garage_se_sub:
    #   - ffmpeg:http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
    # garage_sw:
    #   - ffmpeg:http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted#video=copy#audio=copy#audio=opus
    # garage_sw_sub:
    #   - ffmpeg:http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
    mud_room: rtsp://admin:redacted@10.0.70.176:554/Streaming/Channels/101
    mud_room_sub: rtsp://admin:redacted@10.0.70.176:554/Streaming/Channels/102
    pole_barn: rtsp://admin:redacted@10.0.71.219:554/Streaming/Channels/101
    pole_barn_sub: rtsp://admin:redacted@10.0.71.219:554/Streaming/Channels/102
    pole_barn_porch: rtsp://admin:redacted@10.0.71.100/Streaming/Channels/101
    pole_barn_porch_sub: rtsp://admin:redacted@10.0.71.100/Streaming/Channels/102
    pole_barn_south: rtsp://admin:redacted@10.0.70.234:554/Streaming/Channels/101
    pole_barn_south_sub: rtsp://admin:redacted@10.0.70.234:554/Streaming/Channels/102
    # road: rtsp://admin:redacted@10.0.71.155:554/Streaming/Channels/103

timestamp_style:
  effect: solid

cameras:
  chicken:
    birdseye:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/chicken
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
#  esp32_cam:
#    ffmpeg:
#      inputs:
#        - path: http://10.4.10.68:8080
#          input_args: preset-http-mjpeg-generic
#          roles:
#            - record
#            - detect
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    motion:
      mask:
        - 640,0,640,45,0,45,0,0
    zones:
      front_step:
        coordinates: 640,480,640,361,0,120,0,480
  front_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_driveway_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 1,0,1,0.451,0.547,0.171,0.536,0
        - 0,0.439,0.249,0.419,0.353,0.254,0.371,0,0,0
    objects:
      filters:
        car:
          mask:
            - 1920,635,1920,0,467,0
        cat:
          mask:
            - 1920,635,1920,0,467,0
          max_area: 50000
        dog:
          mask:
            - 1920,635,1920,0,467,0
          max_area: 50000
        person:
          mask:
            - 1920,635,1920,0,467,0
          min_area: 10000
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    zones:
      front_step:
        coordinates: 640,480,640,299,499,250,462,161,159,480
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  # garage_se:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/garage_se
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #       - path: rtsp://127.0.0.1:8554/garage_se_sub
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - detect
  #   detect:
  #     width: 640
  #     height: 480
  #     fps: 5
  # garage_sw:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/garage_sw
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #       - path: rtsp://127.0.0.1:8554/garage_sw_sub
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - detect
  #   detect:
  #     width: 640
  #     height: 480
  #     fps: 5
  mud_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mud_room
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mud_room_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  pole_barn:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pole_barn
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pole_barn_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
  pole_barn_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pole_barn_porch
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pole_barn_porch_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask: 0.000,0.500,1,0.500,1,0,0,0
    objects:
      filters:
        car:
          mask:
            - 720,720,0,720,0,0,720,0
  pole_barn_south:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pole_barn_south
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pole_barn_south_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 0,120,640,120,640,0,0,0
  # road:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/road
  #         input_args: preset-rtsp-restream-low-latency
  #         roles:
  #           - detect
  #           - record
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10
  #   objects:
  #     filters:
  #       car:
  #         min_score: 0.4
  #         threshold: 0.6
  #   record:
  #     enabled: false
  #   snapshots:
  #     required_zones:
  #       - optimal
  #   zones:
  #     optimal:
  #       coordinates: 450,375,950,375,950,150,450,150
version: 0.14
```

### Relevant log output

```shell
[ERROR:0@75.042] global cap_ffmpeg_impl.hpp:1309 open Could not open codec h264, error: -11
[ERROR:0@75.042] global cap_ffmpeg_impl.hpp:1317 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ERROR:0@75.042] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception: OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:redacted@10.0.71.155:554/Streaming/Channels/101
ffprobe version 9efe5bc Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, rtsp, from 'rtsp://admin:redacted@10.0.71.155:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 10 fps, 24 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

RKNN

### Network connection

Wired

### Camera make and model

Hikvision HS-VST08G2-IU

### Any other information that may be helpful

I tried commenting out
  hwaccel_args: preset-rk-h264
since the error logs mention not being able to load the h.264 codec but that didn't seem to make any difference.
