### DISCUSSION TITLE
[Support]: Version 0.14 issues after upgrading: No Audio, Detections/Alerts, old files clean-up, no HA Camera available, no stats?

### DISCUSSION THREAD

**Discussion by DReffects** [blakeblackshear/frigate#12222] [General Support]
### Describe the problem you are having

I've just made the switch to the 0.14 beta channel by removing the home assistant addon and then reinstalling via the beta channel. 
The new UI is great but I am missing a bunch of features.

 Playback / live View:

- I seem unable to pause, rewind or fast forward the recordings 
- I do not find any option to enable or disable audio in the recordings
     (Visualized waveform is available in the history section though but nothing can be heard)
- Recording junks in the media folder do have working audio in it
- An audio toggle during live view can be found and audio is working there

Detections/Alerts:

- I have object tracking enabled and have lots of "alerts" to review but zero "Detections". What's the difference here?

Old files Cleanup:

- Looks like the new version has "forgotten" about the previously recorded files from version 0.13.
- Whats the best way to clean-up here?

Cameras are not available within HA

- While i do get the frigate devices integration to show all kinds of data, the camera stream itself is always unavailable. 
- What can be done here?

No stats
- I do not get any CPU/GPU stats on a n100 Mini system no matter if i use the ssdlite mobilenet or yolonas model

Thanks!!

### Version

 0.14.0-4e5a6eb

### Frigate config file

```yaml
database:
  path: /config/frigate.db


mqtt:
  enabled: true
  host: 192.168.0.14
  user: homeassistant
  password: 134513452435
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 10


ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt



birdseye:
  enabled: false
  mode: continuous
  width: 1920
  height: 1080
  restream: true


objects:
  track:
    - person
    - cat
    - dog


go2rtc:
  streams:
    Carport:
      - rtsp://sadfasdasdf@192.168.0.24:554/cam/realmonitor?channel=1&subtype=0

    Carport_Sub:
      - rtsp://sadfasdasdf@192.168.0.24:554/cam/realmonitor?channel=1&subtype=2

    Strasse:
      - rtsp://sadfasdasdf@192.168.0.26:554/cam/realmonitor?channel=1&subtype=0
    Strasse_Sub:
      - rtsp://sadfasdasdf@192.168.0.26:554/cam/realmonitor?channel=1&subtype=2

    Seite:
      - rtsp://sadfasdasdf@192.168.0.27:554/cam/realmonitor?channel=1&subtype=0
    Seite_Sub:
      - rtsp://sadfasdasdf@192.168.0.27:554/cam/realmonitor?channel=1&subtype=2

    Hinten:
      - rtsp://sadfasdasdf@192.168.0.25:554/cam/realmonitor?channel=1&subtype=0
    Hinten_Sub:
      - rtsp://sadfasdasdf@192.168.0.25:554/cam/realmonitor?channel=1&subtype=2

cameras:
  Carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Carport?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Carport_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 90
          mode: motion
    #live:
      #stream_name: Carport_Main          
    motion:
      mask: 0.205,0.069,0.287,0.614,0.337,0.706,0.35,0.999,0,0.997,0,0,0.203,-0.001
  Strasse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Strasse?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Strasse_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 90
          mode: motion


    motion:
      mask:
        - 0.005,0.938,0.003,0.991,0.344,0.992,0.344,0.935
        - 1,0.093,0.863,0.127,0.691,0.159,0,0.606,0,0,0.492,0.002,1,0
  Seite:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Seite?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Seite_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 90
          mode: motion


    motion:
      mask:
        - 0.689,0.068,0,0.614,0,0,0.672,0
        - 0.022,0.935,0.023,0.987,0.359,0.989,0.36,0.932
  Hinten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Hinten?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Hinten_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 90
          mode: motion


    motion:
      mask: 0,0.558,0.358,0.218,0.48,0.09,0.687,0,0,0
version: 0.14
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Dahua
