### DISCUSSION TITLE
[Support]: Live view crashes browser

### DISCUSSION THREAD

**Discussion by peterjonesk** [blakeblackshear/frigate#12225] [General Support] [answered]
### Describe the problem you are having

When viewing the Live page showing all 8 cameras, all the streams initially show up, but after a few seconds, the browser crashes (just completely disappears with no error message). This is in Chrome on an android tablet (both a Lenovo P11 Gen 2, and an older Samsung SM-T510). If I turn OFF "Automatic Live View" in Settings, it does not crash. 

Works fine in Chrome on Windows desktop, and on Samsung Galaxy S23 phone.

Can anyone provide any tips on what to look at to try to debug this?
Is it expected that 8 cameras would be too much for a 4gb tablet to handle?

I'm guessing this may not really be a frigate problem , but would seem this is a standard setup. Hoping there is some knowledge I can draw from...

Thanks for any pointers!

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.35
  user: ha_mqtt
  password: XXX

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.50:8555
      - stun:8555
  streams:
    side:
      - rtsp://user1:XXX@192.168.1.182:554/Streaming/channels/101#media=video
    frontdoor:
      - rtsp://user1:XXX@192.168.1.183:554/Streaming/Channels/101#media=video+audio
    kitchen:
      - rtsp://user1:XXX@192.168.1.184:554/Streaming/channels/101#media=video+audio
    deck:
      - rtsp://user1:XXX@192.168.1.185:554/Streaming/channels/101
    garagelawn:
      - rtsp://user1:XXX@192.168.1.186:554/Streaming/channels/101
    driveway:
      - rtsp://user1:XXX@192.168.1.187:554/Streaming/channels/101
    side_sub:
      - rtsp://user1:XXX@192.168.1.182:554/Streaming/channels/102#media=video
    frontdoor_sub:
      - rtsp://user1:XXX@192.168.1.183:554/Streaming/Channels/102#media=video
    kitchen_sub:
      - rtsp://user1:XXX@192.168.1.184:554/Streaming/channels/102#media=video
    deck_sub:
      - rtsp://user1:XXX@192.168.1.185:554/Streaming/channels/102
    garagelawn_sub:
      - rtsp://user1:XXX@192.168.1.186:554/Streaming/channels/102
    driveway_sub:
      - rtsp://user1:XXX@192.168.1.187:554/Streaming/channels/102
    frontdoorbell:
      - rtsp://user1:XXX@192.168.1.180:554/h264Preview_01_main
    frontdoorbell_sub:
      - rtsp://user1:XXX@192.168.1.180:554/h264Preview_01_sub#media=video
    rearlawn:
      - rtsp://user1:XXX@192.168.1.188:554/cam/realmonitor?channel=1&subtype=0
    rearlawn_sub:
      - rtsp://user1:XXX@192.168.1.188:554/cam/realmonitor?channel=1&subtype=1

detect:
  enabled: true
  width: 640 # <---- update for your camera's resolution
  height: 480 # <---- update for your camera's resolution
  fps: 5

objects:
  track:
    - person
    - cat
    - dog
    - horse

record:
  enabled: true
  retain:
    days: 5
    mode: motion

cameras:
  side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_sub
          roles:
            - detect
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          roles:
            - detect
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_sub
          roles:
            - detect
    #live:
    #  stream_name: kitchen_sub
  deck:    # main stream: 2688x1520
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.50:8554/deck
          roles:
            - record
        - path: rtsp://192.168.1.50:8554/deck_sub
          roles:
            - detect
    record:
      retain:
        days: 3
        mode: all
  garagelawn:    # main stream: 2688x1520
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagelawn
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garagelawn_sub
          roles:
            - detect
  driveway:    # main stream: 2688x1520
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          roles:
            - detect
  frontdoorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoorbell
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoorbell_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
  rearlawn:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.50:8554/rearlawn
          roles:
            - record
            - detect
    record:
      retain:
        days: 3
        mode: all
version: 0.14
```

### Relevant log output

```shell
no errors
```

### FFprobe output from your camera

```shell
?
```

### Frigate stats

```json
{"cameras":{"deck":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":527,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":545,"pid":473,"process_fps":5.1,"skipped_fps":0.0},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":535,"detection_enabled":true,"detection_fps":3.7,"ffmpeg_pid":544,"pid":489,"process_fps":5.1,"skipped_fps":0.0},"frontdoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":516,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":521,"pid":452,"process_fps":5.0,"skipped_fps":0.0},"frontdoorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":546,"detection_enabled":true,"detection_fps":4.1,"ffmpeg_pid":567,"pid":497,"process_fps":5.0,"skipped_fps":0.0},"garagelawn":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":531,"detection_enabled":true,"detection_fps":5.7,"ffmpeg_pid":543,"pid":481,"process_fps":5.1,"skipped_fps":0.0},"kitchen":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":520,"detection_enabled":true,"detection_fps":7.5,"ffmpeg_pid":526,"pid":465,"process_fps":5.0,"skipped_fps":0.0},"rearlawn":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":553,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":566,"pid":505,"process_fps":5.0,"skipped_fps":0.0},"side":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":511,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":517,"pid":449,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"122":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"126":{"cmdline":"python3 -u -m frigate","cpu":"6.1","cpu_average":"7","mem":"6.3"},"130":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"14114":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"14179":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"176":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"177":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"178":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"179":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"18":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"184":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"316":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"342":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.8"},"344":{"cmdline":"frigate.recording_manager","cpu":"3.1","cpu_average":"4","mem":"1.9"},"346":{"cmdline":"frigate.review_segment_manager","cpu":"0.4","cpu_average":"0","mem":"0.9"},"372":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(71)","cpu":"0.2","cpu_average":"0","mem":"0.1"},"373":{"cmdline":"frigate.detector.coral","cpu":"2.1","cpu_average":"0","mem":"0.9"},"375":{"cmdline":"frigate.output       ","cpu":"2.6","cpu_average":"1","mem":"1.0"},"393":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"398":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"403":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"408":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"413":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"418":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"423":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"428":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"433":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"449":{"cmdline":"frigate.process:side ","cpu":"0.5","cpu_average":"0","mem":"1.0"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"452":{"cmdline":"frigate.process:frontdoor","cpu":"0.6","cpu_average":"0","mem":"1.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"465":{"cmdline":"frigate.process:kitchen","cpu":"2.2","cpu_average":"1","mem":"1.3"},"473":{"cmdline":"frigate.process:deck ","cpu":"0.6","cpu_average":"0","mem":"1.1"},"481":{"cmdline":"frigate.process:garagelawn","cpu":"1.8","cpu_average":"0","mem":"1.2"},"489":{"cmdline":"frigate.process:driveway","cpu":"0.8","cpu_average":"0","mem":"1.1"},"497":{"cmdline":"frigate.process:frontdoorbell","cpu":"1.4","cpu_average":"0","mem":"1.1"},"505":{"cmdline":"frigate.process:rearlawn","cpu":"0.6","cpu_average":"0","mem":"1.2"},"511":{"cmdline":"frigate.capture:side ","cpu":"0.3","cpu_average":"0","mem":"1.0"},"516":{"cmdline":"frigate.capture:frontdoor","cpu":"0.3","cpu_average":"0","mem":"1.0"},"517":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/side_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"520":{"cmdline":"frigate.capture:kitchen","cpu":"0.3","cpu_average":"0","mem":"1.0"},"521":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"526":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/kitchen_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"527":{"cmdline":"frigate.capture:deck ","cpu":"0.3","cpu_average":"0","mem":"1.0"},"529":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side@%Y%m%d%H%M%S%z.mp4","cpu":"0.1","cpu_average":"0","mem":"0.2"},"531":{"cmdline":"frigate.capture:garagelawn","cpu":"0.3","cpu_average":"0","mem":"1.0"},"533":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontdoor@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.2"},"535":{"cmdline":"frigate.capture:driveway","cpu":"0.3","cpu_average":"0","mem":"1.0"},"536":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/kitchen -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/kitchen@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.2"},"543":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garagelawn_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"544":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"545":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.50:8554/deck_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"546":{"cmdline":"frigate.capture:frontdoorbell","cpu":"0.3","cpu_average":"0","mem":"1.0"},"553":{"cmdline":"frigate.capture:rearlawn","cpu":"0.4","cpu_average":"0","mem":"0.9"},"554":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.50:8554/deck -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/deck@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.2"},"557":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garagelawn -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garagelawn@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.2"},"563":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.2"},"566":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.50:8554/rearlawn -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/rearlawn@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.3","cpu_average":"1","mem":"0.7"},"567":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoorbell_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.5"},"571":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontdoorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"740":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"83":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.1","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"8.7","cpu_average":"8","mem":"0.5"},"frigate.full_system":{"cpu":"4.7","mem":"91.9"}},"detection_fps":21.0,"detectors":{"coral":{"detection_start":1719782508.161129,"inference_speed":6.16,"pid":373}},"gpu_usages":{"intel-vaapi":{"gpu":"3.21%","mem":"-%"}},"processes":{"go2rtc":{"pid":97},"logger":{"pid":342},"recording":{"pid":344},"review_segment":{"pid":346}},"service":{"last_updated":1719782508,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":119.3,"mount_type":"tmpfs","total":128.0,"used":8.7},"/media/frigate/clips":{"free":2279678.6,"mount_type":"zfs","total":3682657.9,"used":1402979.2},"/media/frigate/recordings":{"free":2279678.6,"mount_type":"zfs","total":3682657.9,"used":1402979.2},"/tmp/cache":{"free":19868.4,"mount_type":"overlay","total":30065.9,"used":8645.5}},"temperatures":{"apex_0":50.3},"uptime":1333,"version":"0.14.0-4e5a6eb"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision, reolink doorbell
