### DISCUSSION TITLE
[Bug]: Firefox only - Masks/Zones

### DISCUSSION THREAD

**Discussion by ubawurinna** [blakeblackshear/frigate#12230] [Report a Bug] [answered]
### Describe the problem you are having

On Firefox (this works on Chrome-based browsers) the mask/motion view remains frozen after an initial display.

### Steps to reproduce

Click on a camera to get the live view
Now go to settings Masks/Zones, a low res picture of the live view is displayed
Click on the camera again to obtain a live view, move the camera or place an object in the camera field.
Now return to settings Masks/Zones, the low-resolution image is the **same as the first time.**

### Version

last dev (commit f050c7b)

### Frigate config file

```yaml
go2rtc:
  streams:
    camera1:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    lowres:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lowres
          roles:
            - detect
    live:
      stream_name: camera1
```
```


### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Tapo
