### DISCUSSION TITLE
[Bug]: System Stats not working/broken - Exiting stats emitter

### DISCUSSION THREAD

**Discussion by DReffects** [blakeblackshear/frigate#12231] [Report a Bug] [answered]
### Describe the problem you are having

The entire system Stats section does not seem to be working/being broken. There are no auto-updates ("Last update 16h ago") and no stats at all besides Detector memory Usage which seems to be rather fixed.
Detector Inference Speed is always 10ms

Time for the stats is always the last reboot time of frigate. The stats emitter seems to die (see log)

Intel GPU in the status bar always reports 0 or 1% usage, CPU Usage is always zero:
![image](https://github.com/blakeblackshear/frigate/assets/48361672/9609c717-d40d-4865-b095-d3a6f14c88dd)

![image](https://github.com/blakeblackshear/frigate/assets/48361672/b43363a3-e1d9-4956-894c-590f26495cce)

![image](https://github.com/blakeblackshear/frigate/assets/48361672/8682a6fc-2a02-4fc7-965d-9b58f826dd39)

System: Intel N100 Mini-PC

Happens with both yolonas and ssdlite_mobilenet_v2 mdoel

Also happens when switching to CPU device for detections

Without any object detection same thing. 
Does still not refresh or update though. Time shown always stays at the time of the last reboot of frigate.
In this case 1:58pm (it's currently 2:06pm)

![image](https://github.com/blakeblackshear/frigate/assets/48361672/44d56659-5b26-4392-82d2-9d871f563604)

### Steps to reproduce

Open the System Stats page

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac


detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt


objects:
  track:
    - person
    - cat
    - dog


go2rtc:
  streams:
    Carport:
      - rtsp://192.168.0.24:554/cam/realmonitor?channel=1&subtype=0

    Carport_Sub:
      - rtsp://192.168.0.24:554/cam/realmonitor?channel=1&subtype=2



cameras:
  Carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Carport?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Carport_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant log output

```shell
2024-07-01 13:59:03
frigate.stats.emitter
Exiting stats emitter...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Dahua
