### DISCUSSION TITLE
[HW Accel Support]: ffmpeg crashes with frigate:dev-93e0868

### DISCUSSION THREAD

**Discussion by gofaster** [blakeblackshear/frigate#12248] [Hardware Acceleration Support]
### Describe the problem you are having

`dev-f0159bf` worked fine. 
`dev-93e0868` crashes  upon start, with ffmpeg errors.

Should I switch to VAAPI?

I'm using Intel hw accel.
```
vainfo:
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

```
root@wnnn:/opt/frigate# ffmpeg -codecs  | grep -i qsv
ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
 DEV.L. av1                  Alliance for Open Media AV1 (decoders: libdav1d libaom-av1 av1 av1_cuvid av1_qsv ) (encoders: libaom-av1 librav1e libsvtav1 )
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv libopenh264 h264_cuvid ) (encoders: libx264 libx264rgb libopenh264 h264_amf h264_nvenc h264_qsv h264_v4l2m2m h264_vaapi )
 DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_cuvid ) (encoders: libx265 hevc_amf hevc_nvenc hevc_qsv hevc_vaapi )
 DEVIL. mjpeg                Motion JPEG (decoders: mjpeg mjpeg_cuvid mjpeg_qsv ) (encoders: mjpeg mjpeg_qsv mjpeg_vaapi )
 DEV.L. mpeg2video           MPEG-2 video (decoders: mpeg2video mpegvideo mpeg2_v4l2m2m mpeg2_qsv mpeg2_cuvid ) (encoders: mpeg2video mpeg2_qsv mpeg2_vaapi )
 D.V.L. vc1                  SMPTE VC-1 (decoders: vc1 vc1_qsv vc1_v4l2m2m vc1_cuvid )
 DEV.L. vp8                  On2 VP8 (decoders: vp8 vp8_v4l2m2m libvpx vp8_cuvid vp8_qsv ) (encoders: libvpx vp8_v4l2m2m vp8_vaapi )
 DEV.L. vp9                  Google VP9 (decoders: vp9 libvpx-vp9 vp9_cuvid vp9_qsv ) (encoders: libvpx-vp9 vp9_vaapi vp9_qsv )
```

### Version

dev-93e0868

### Frigate config file

```yaml
version: 0.14

tls:
  enabled: true

mqtt:
  enabled: true
  host: mqtt.example.com
  port: 8883
  user: user
  password: pass
  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
  tls_insecure: false

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://deadbeeff00d

go2rtc:
  rtsp: # restream auth
    username: user
    password: pass
  webrtc:
    candidates:
      - xxx.xxx.xxx.xxx:8555
      - stun:8555
  streams:
    dining_main:
      - rtsp://user:pass@xxx.xxx.xxx.xxx:554/Preview_01_main
      - ffmpeg:dining_main#audio=opus
    dining_sub:
      - rtsp://user:pass@xxx.xxx.xxx.xxx:554/Preview_01_sub
      - ffmpeg:dining_sub#audio=opus
    foyer_main:
      - rtsp://user:pass@xxx.xxx.xxx.xxx:554/Preview_01_main
      - ffmpeg:foyer_main#audio=opus
    foyer_sub:
      - rtsp://user:pass@xxx.xxx.xxx.xxx:554/Preview_01_sub
      - ffmpeg:foyer_sub#audio=opus

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 8
  mode: objects
  inactivity_threshold: 30

cameras:
  dining:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/dining_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/dining_main
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 500 # 200=hi,500-med,100=low
      listen:  # https://github.com/blakeblackshear/frigate/blob/dev/audio-labelmap.txt
        - gunshot
        - scream
        - yell
        - fire_alarm
        - siren
        - smoke_detector
    detect:
      enabled: false
      fps: 5
    objects:
      track:
        - person
        - face
        - cat
        - dog
    record:
      enabled: true
      sync_recordings: false ###
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 21
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      retain:
        default: 3
    review:
      alerts:
        labels:
          - person
          - cat
          - dog
          - gunshot
          - scream
          - yell
    birdseye:
      enabled: true
      restream: true
      mode: motion
    live:
      stream_name: dining_main
    motion:
      mask:
        - 0,0,0,0.226,0.972,0.186,1,0.182,1,0
        - 0,0.384,0.099,0.385,0.103,0.537,0.072,0.573,0.001,0.549

  foyer:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/foyer_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/foyer_main
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 500 # 200=hi,500-med,100=low
      listen:  # https://github.com/blakeblackshear/frigate/blob/dev/audio-labelmap.txt
        - gunshot
        - scream
        - yell
        - fire_alarm
        - smoke_detector
        - siren
    detect:
      enabled: false
      fps: 5
    objects:
      track:
        - person
        - face
        - cat
        - dog
    record:
      enabled: true
      sync_recordings: false ###
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 21
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: true
      retain:
        default: 3
    review:
      alerts:
        labels:
          - person
          - cat
          - dog
          - gunshot
          - scream
          - yell
    birdseye:
      enabled: true
      restream: true
      mode: motion
    live:
      stream_name: foyer_main
    motion:
      mask: 1,0.105,0.284,0.019,0.291,0.176,0.222,0.174,0.205,0,1,0

telemetry:
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
#  logs:
#    frigate.event: debug
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
#    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3
#    image: ghcr.io/blakeblackshear/frigate:dev-9bbb88c
#    image: ghcr.io/blakeblackshear/frigate:dev-bfbacee
#    image: ghcr.io/blakeblackshear/frigate:dev-18b8e19
    image: ghcr.io/blakeblackshear/frigate:dev-f0159bf
#    image: ghcr.io/blakeblackshear/frigate:dev-93e0868  ## 2023-07-01 ffmpeg crashes, qsv_device
    privileged: true # this may not be necessary for all setups
    restart: always
#    restart: unless-stopped
#   mem_limit: 6gb
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /BLAH/certs:/etc/letsencrypt/live/frigate
      - /BLAH/frigate:/media/frigate
      - type: tmpfs # Optional: 500MB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "5000:5000" # Internal unauthenticated UI and API access.
      - "8971:8971" # Authenticated UI and API access without TLS.
      - "1984:1984" # go2rtc UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - PLUS_API_KEY=mykey
    labels:
      - "docker.group=frigate"    # for telegraf/grafana
```

### Relevant log output

```shell
frigate  | 2024-07-01 13:41:34.452112591  [2024-07-01 13:41:34] watchdog.dining                ERROR   : Ffmpeg process crashed unexpectedly for dining.
frigate  | 2024-07-01 13:41:34.466525481  [2024-07-01 13:41:34] watchdog.dining                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-07-01 13:41:34.466532984  [2024-07-01 13:41:34] ffmpeg.dining.detect           ERROR   : Unrecognized option 'qsv_device'.
frigate  | 2024-07-01 13:41:34.467202350  [2024-07-01 13:41:34] ffmpeg.dining.detect           ERROR   : Error splitting the argument list: Option not found
frigate  | 2024-07-01 13:41:34.473137258  [2024-07-01 13:41:34] watchdog.foyer                 ERROR   : Ffmpeg process crashed unexpectedly for foyer.
frigate  | 2024-07-01 13:41:34.473144527  [2024-07-01 13:41:34] watchdog.foyer                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-07-01 13:41:34.473552492  [2024-07-01 13:41:34] ffmpeg.foyer.detect            ERROR   : Unrecognized option 'qsv_device'.
frigate  | 2024-07-01 13:41:34.473557722  [2024-07-01 13:41:34] ffmpeg.foyer.detect            ERROR   : Error splitting the argument list: Option not found
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://user:pass@xxx.xxx.xxx.xxx':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000125, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink 520a
