### DISCUSSION TITLE
[Bug]: All browsers - Exiting full-screen live view

### DISCUSSION THREAD

**Discussion by ubawurinna** [blakeblackshear/frigate#12246] [Report a Bug] [answered]
### Describe the problem you are having

When you exit the live view in full-screen mode using the "back" button, the view becomes smaller, but you remain in full-screen mode.

### Steps to reproduce

When live view is displayed, click on Full Screen button
Then click the Back button

### Version

las dev (commit 93e0868)

### Frigate config file

```yaml
go2rtc:
  streams:
    camera1:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    lowres:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lowres
          roles:
            - detect
    live:
      stream_name: camera1
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Tapo

### Any other information that may be helpful

The reduce and return button seems redundant and does not produce the same result.
