### DISCUSSION TITLE
[Config Support]: Motion detection only not working

### DISCUSSION THREAD

**Discussion by lordraiden** [blakeblackshear/frigate#12244] [Config Support]
### Describe the problem you are having

I have configured frigate to work only on motion detection, but still tries to do some sort of object detection
![imagen](https://github.com/blakeblackshear/frigate/assets/17175395/a2b30330-b49d-41d7-9836-d0f98b0f02dc)

Why do I get detections (recoded clips) if nothing is going on on the screen?
The "puerta" camera works fine but the "entrada" camera gets a lot of boxes trying to detects things, while I don't want that, just motion detection.
Why events are not created when detections are done?
Should I use the configuration specified here for my reolink doorbell "puerta" or it doesn't matter? https://docs.frigate.video/configuration/camera_specific#reolink-doorbell

Do I need to configure #model if I will use CPU?
Do I need to configure "rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_sub" as a go2rtc stream? or the config is fine If I only want to use it for detect?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: asd.asd

logger:
  default: info
  logs:
    watchdog.puerta: critical

detectors:
  cpu:
    type: cpu
    num_threads: 6

#ffmpeg:
#  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    entrada:
      - rtsp://tpc210:asd.asd@10.10.10.133:554/stream1
      - "ffmpeg:entrada#audio=aac"
    puerta: 
      - rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_main
      - "ffmpeg:puerta#audio=aac#audio=volume"
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

#model:
#  path: /cpu_model.tflite
#  width: 320
#  height: 320
#  input_tensor: "nhwc"
#  input_pixel_format: "rgb"

# Configuracion de deteccion de movimiento

detect:
  enabled: True
  #width: 1280
  #height: 720
  fps: 7
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 4
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 35
  # Optional: Configuration for stationary object tracking

motion:
  threshold: 30
  contour_area: 15
  lightning_threshold: 0.8


record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30
  quality: 100

cameras:
  
  entrada:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrada
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 0,51,715,51,715,0,0,0

  puerta:
    ffmpeg:
      inputs:
        - path: rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_main
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 215,30,415,30,415,0,215,0 # timestamp reolink
        - 155,305,170,305,170,324,155,324 # numeros ascensor
    live:
      stream_name: puerta


##
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
You have detection enabled:

```
detect:
  enabled: True
```

If you don't want detections or events, you should disable it.

**Reply by lordraiden** [reply]
> You have detection enabled:
> 
> ```
> detect:
>   enabled: True
> ```
> 
> If you don't want detections or events, you should disable it.

I want "events" and "detections" but only based on motion. Should I disable it then?

**Comment by lordraiden** [comment]
I have disable de detect section and roles and restarted the app and still is doing all this
![imagen](https://github.com/blakeblackshear/frigate/assets/17175395/17990f4d-69bc-448c-b751-de5f4a5bc422)

**Reply by hawkeye217** [reply]
Your motion detection settings are too sensitive, then. The red boxes indicate areas that Frigate is saying motion has occurred. The green boxes are "regions" of interest, that if detection was enabled, would be sent off to the detector. But if you've disabled detection, that won't happen.

**Reply by hawkeye217** [reply]
For a graphical understanding of what Frigate is doing, check out the docs: https://docs.frigate.video/frigate/video_pipeline

**Reply by NickM-27** [reply]
To be clear detection is enabled by default. Removing it from the config does not disable it. It needs to be set to disabled.

**Reply by lordraiden** [reply]
Ok, now it works, after setting detection to false and tune up a little bit more the motions limits. The only thing that bothers me is that now I don't have the events. Are the events only available when detection is used?
According to the docs the motion "events" exists.


![imagen](https://github.com/blakeblackshear/frigate/assets/17175395/fe3cac0e-8164-474c-87f3-6d65672e1f9c)

**Reply by hawkeye217** [reply]
Events are generated when objects are detected. If you want objects to be detected, you need to enable object detection.

Motion "events" don't exist, but motion recordings do. You want recordings to be retained based on motion, you can set that in your config.

**Reply by NickM-27** [reply]
Worth noting that in frigate 0.14 motion is more easily reviewed as well in the motion tab of the review page

**Reply by lordraiden** [reply]
> Events are generated when objects are detected. If you want objects to be detected, you need to enable object detection.
> 
> Motion "events" don't exist, but motion recordings do. You want recordings to be retained based on motion, you can set that in your config.

I have the events enabled for motion, I get the records when there is something in motion, the files are saved in my disk but the Events section in frigate remains empty. Is this how it is suppose to work?
I don't see anything wrong in my config


record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: motion


```
mqtt:
  enabled: True
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: contrasena.fuerte2021

logger:
  default: info
# logs:
  # watchdog.puerta: critical

go2rtc:
  streams:
    entrada:
      - rtsp://tpc210:asd.asd@10.10.10.133:554/stream1
      - "ffmpeg:entrada#audio=aac"
    # - "tapo://asd.asd@10.10.10.133"
    puerta:   #https://docs.frigate.video/configuration/camera_specific#reolink-doorbell
      - rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_main 
      - "ffmpeg:puerta#video=copy#audio=copy#audio=aac#audio=volume"
    # - rtsp://homeassistant:asd.asd@10.10.10.134:554/h264Preview_01_sub
    # - "http://10.10.10.134/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=asd.asd"
    # - "ffmpeg:puerta#video=copy#audio=copy#audio=aac"
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""


detect:
  enabled: False

record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30
  quality: 100

cameras:
  
  entrada:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrada
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
        - 0,51,715,51,715,0,0,0 # timestamp tapo
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 100
      # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 10 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      contour_area: 30
      # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
      #           needs to recalibrate. (default: shown below)
      # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
      # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
      # a doorbell camera.
      lightning_threshold: 0.8

  puerta:
    ffmpeg:
      inputs:
       #- path: rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_sub
       #- path: http://10.10.10.134/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=asd.asd
       #- path: rtsp://admin:asd.asd@10.10.10.134:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/puerta
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 903,65,1664,65,1664,0,903,0 # timestamp reolink
        - 681,1234,681,1276,629,1276,629,1234 # numeros ascensor
      threshold: 50
      contour_area: 30
      lightning_threshold: 0.8
    live:
      stream_name: puerta


##  END
```
