### DISCUSSION TITLE
[Config Support]: Increasing record video duration and export

### DISCUSSION THREAD

**Discussion by jwill2385** [blakeblackshear/frigate#12257] [Config Support] [answered]
### Describe the problem you are having

Hello I would like to increase video duration with frigate to 2 minutes. However I keep reaching an error when I try to go pass 1 minute clips. Additionally by setting the clips to be one minute in the output_arg oftentimes the video quality will freeze and miss frames making the videos unusable.

I am using a jetson orin running ubuntu 22.04 and Cuda 11.2 and jetpack 6.0
I would like to save 2 minute video clips and then be able to compile and export 1 hour long videos. How can I do this effectively wih the output_args setting and the export feature in frigate?

### Version

Frigate stable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  camera1: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_nvmpi
      inputs:
        - path: rtsp://user:pass@10.0.0.111/live #TODO update to camera path
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        # mode: all
      
  ip_cam: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://user:pass@10.0.0.122/live #TODO update to camera path
          roles:
            - detect
            - record
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        mode: all
```

### Relevant log output

```shell
version: "2.4"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp4 #Jetson nano image jetpack 4.6
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/visionsense2/Docker/frigate/config:/config
      - /home/visionsense2/Docker/frigate/media:/media/frigate #TODO switch this to external HD for media storage
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Any other information that may be helpful

I have hardware accleration enabled on the docker compose file however it only accesses the CPU for some reason.
