### DISCUSSION TITLE
[Support]: Stable docker compose image tag not there

### DISCUSSION THREAD

**Discussion by Drizzt321** [blakeblackshear/frigate#12258] [Report a Bug] [answered]
### Describe the problem you are having

The docker compose stable image tag seems to have disappeared/not been updated/created. I try and do `docker compose pull` and it says `stable` isn't a valid tag.

### Steps to reproduce

Try and use `ghcr.io/blakeblackshear/frigate:stable` in the `docker-compose.yml`

### Version

v0.12.1

### Frigate config file

```yaml
mqtt:
  host: homeassistant
  user:  frigate
  password: <REDACTED>

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 10
      mode: active_objects
      
cameras:
  alley_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.230/stream0 # 640x480 25fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.230/stream1 # 1920x1080 10fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10


  alley_2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.212:554/cam/realmonitor?channel=1&subtype=1 # 704x576 20fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.212/cam/realmonitor?channel=1&subtype=0 # 2592x1944 20fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 10

  alley_3: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<REDACTED>@10.30.255.249:554/cam/realmonitor?channel=1&subtype=1 # 704x576 20fps
          roles:
            - detect
        - path: rtsp://admin:<REDACTED>@10.30.255.249:554/cam/realmonitor?channel=1&subtype=0 # 2592x1944 20fps
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 10


birdseye:
  enabled: True
  mode: continuous

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - skateboard
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A
