### DISCUSSION TITLE
[Config Support]: Motion detection for light changes and IR

### DISCUSSION THREAD

**Discussion by lordraiden** [blakeblackshear/frigate#12267] [Config Support]
### Describe the problem you are having

As seen in the video the process is the light is on, goes off, IR camera gets activated, the process will continue with light on, camera IR disable. etc

I have tried everything but still frigate detects this as motion, Is there a way to fix it? any advice?

I'm using this parameters:

### Version

System 0.13.2-6476f8a

### Frigate config file

```yaml
motion:
      mask:
        - 903,65,1664,65,1664,0,903,0 # timestamp reolink
        - 681,1234,681,1276,629,1276,629,1234 # elevator numbers
      threshold: 200
      contour_area: 30
      lightning_threshold: 0.3
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

CPU (no coral)
