### DISCUSSION TITLE
[Bug]: Sudden Issue with one camera, not sure what to make of the error

### DISCUSSION THREAD

**Discussion by grainsoflight** [blakeblackshear/frigate#12270] [Report a Bug] [answered]
### Describe the problem you are having

I am suddenly having an issue with the stream from a reolink doorbell. The stream works, but with visual artifacts. This is new and was not happening in the past, that specific camera has been operating fine for months.  See log below for error.

### Steps to reproduce

Open camera stream

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: "pass"
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  doorbell:
    ffmpeg:
      inputs:
      - path: rtsp://user:pass@192.168.5.3:554/h264Preview_01_sub
        roles:
        - detect
      - path: rtsp://0.0.0.0:8554/doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 640
      height: 480
      fps: 7
    record:
      enabled: true
      retain:
        days: 14
    motion:
      mask:
      - 422,0,421,26,208,29,207,0
      - 222,112,293,45,436,51,453,123,442,279,218,302
    objects:
      filters:
        person:
          mask:
          - 301,0,0,0,0,480,230,480,229,100,265,99
          - 438,40,640,0,640,480,501,480,438,437
          - 234,102,305,21,440,52,445,187,228,185
    snapshots:
      enabled: true
  backyard:
    ffmpeg:
      inputs:
      - path: rtsp://user:pass@192.168.5.2:554/h264Preview_01_sub
        roles:
        - detect
      - path: rtsp://0.0.0.0:8554/backyard
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 896
      height: 512
      fps: 8
    motion:
      mask:
      - 231,36,649,40,650,0,267,0,236,0
      - 456,0,460,217,374,258,347,0
      - 126,0,203,273,309,222,263,0
      - 587,0,578,138,508,167,509,0
      - 896,0,896,114,800,49,811,0
      - 114,41,174,49,174,84,38,80,39,43
    record:
      enabled: true
      retain:
        days: 14
    snapshots:
      enabled: true
    onvif:
      host: 192.168.5.2
      user: admin
      password: BW5ynKNVLDhQyS
    zones:
      zone_0:
        coordinates: 801,77,896,124,896,512,0,512,0,0
  backzoom:
    ffmpeg:
      inputs:
      - path: rtsp://0.0.0.0:8554/backzoom
        input_args: preset-rtsp-restream
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 14
          mode: motion
        required_zones: 
          - zone_0
    snapshots:
      enabled: false
    motion:
      mask:
      - 1259,0,1263,56,617,56,620,0
      - 356,78,361,166,54,159,59,68
    zones:
      zone_0:
        coordinates: 1920,0,1920,1080,0,1080,0,0
  # garage:
    # ffmpeg:
      #inputs:
      #- path: rtsp://0.0.0.0:8554/garage
       # input_args: preset-rtsp-restream
        #roles:
        #- record
        #- detect
    #detect:
     # width: 1920
      #height: 1080
      #fps: 5
   # record:
      #enabled: true
      #retain:
       # days: 7
        #mode: motion
      #events:
       # retain:
        #  default: 7
         # mode: active_objects
          #objects:
           # person: 14

go2rtc:
  streams:
    doorbell:
    - rtsp://user:pass@192.168.5.3:554/h264Preview_01_main
    - "ffmpeg:doorbell#audio=opus"
    backyard:
    - rtsp://user:pass@192.168.5.2:554/h264Preview_01_main
    # "#raw=-vf hwdownload,format=nv12" resolves issue where hevc would not transcode properly
    # by converting the GPU pixels to a format the CPU can read
    - "ffmpeg:backyard#audio=opus#video=h264#hardware#raw=-vf hwdownload,format=nv12"
    backzoom:
    - rtsp://user:pass@192.168.5.2:554/h264Preview_02_main
    - "ffmpeg:backzoom#video=h264#hardware#raw=-vf hwdownload,format=nv12"
    # garage:
    # - rtsp://user:pass@192.168.5.4/live
  webrtc:
    candidates:
    - 192.168.0.11:8555
    - stun:8555

birdseye:
  enabled: true
  restream: true
  mode: continuous
```

### Relevant log output

```shell
2024-07-02 14:50:20.045934076  [h264 @ 0x14874c0dc0c0] left block unavailable for requested intra mode
2024-07-02 14:50:20.045937530  [h264 @ 0x14874c0dc0c0] error while decoding MB 0 97, bytestream 46563
2024-07-02 14:50:25.045731596  [h264 @ 0x14874c0dbf00] left block unavailable for requested intra4x4 mode -1
2024-07-02 14:50:25.045734803  [h264 @ 0x14874c0dbf00] error while decoding MB 0 90, bytestream 68216
2024-07-02 14:50:55.034546341  [h264 @ 0x14874c101b40] left block unavailable for requested intra mode
2024-07-02 14:50:55.034549659  [h264 @ 0x14874c101b40] error while decoding MB 0 49, bytestream 214327
2024-07-02 14:51:35.042676602  [h264 @ 0x14874c1bae80] left block unavailable for requested intra mode
2024-07-02 14:51:35.042679812  [h264 @ 0x14874c1bae80] error while decoding MB 0 64, bytestream 144449
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Reolink Doorbell

### Any other information that may be helpful

go2RTC version 1.9.4
