### DISCUSSION TITLE
[Support]: Review page hover

### DISCUSSION THREAD

**Discussion by lukicsl** [blakeblackshear/frigate#12275] [General Support]
### Describe the problem you are having

The review page shows all the events in the past.
When hovering over the snapshot of the events the fast forward of the event is shown (great stuff).
Unfurtunally the hover works just some time in the past (e.g. 1h of possible also just 5 event in the past?).
In this case the snapshot turn to black and stays so.

### Steps to reproduce

Open Review page and hover over events in the past.

### Version

image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3

### Frigate config file

```yaml
mqtt:
  client_id: frigate-pro
  topic_prefix: frigate-pro
  host: 192.168.3.140
  user: xxx
  password: xxx

go2rtc:
  streams:
    housedoor:
      - ffmpeg:rtsp://ghtwga0002:xxx@192.168.3.160/mpeg/1080p/media.amp
      - ffmpeg:front_garden#audio=opus
    housedoor_sub:
      - ffmpeg:rtsp://ghtwga0002:AefHv5TnWx@192.168.3.160/mpeg/media.amp
      - ffmpeg:front_garden#audio=opus
    front_garden:
      - ffmpeg:rtsp://admin:xx*xx@192.168.3.161:554//h265Preview_01_main
      - ffmpeg:front_garden#audio=opus
    front_garden_sub:
      - ffmpeg:rtsp://admin:xx*xx@192.168.3.161:554//h264Preview_01_sub
      - ffmpeg:front_garden_sub#audio=opus
    garage:
      - ffmpeg:rtsp://admin:xx*xx@192.168.3.162:554//h265Preview_01_main
      - ffmpeg:garage#audio=opus
    garage_sub:
      - ffmpeg:rtsp://admin:xx*xx@192.168.3.162:554//h264Preview_01_sub
      - ffmpeg:garage_sub#audio=opus
    garden:
      - ffmpeg:rtsp://admin:h9Bqh8j9G*aAn6p7@192.168.3.163:554//h265Preview_01_main
      - ffmpeg:garden#audio=opus
    garden_sub:
      - ffmpeg:rtsp://admin:xx*xx@192.168.3.163:554//h264Preview_01_sub
      - ffmpeg:garden_sub#audio=opus
detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  stationary:
    interval: 10
    threshold: 50

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 10
    post_capture: 30
    retain:
      default: 14
      mode: active_objects


cameras:
  housedoor:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    motion:
      mask:
        - 0,365,310,373,378,0,0,0
    zones:
      eingang:
        coordinates: 0,506,0,720,937,720,731,486,665,486,664,435,418,441,411,380,268,364,0,363
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/housedoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/housedoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
  front-garden:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    zones:
      eingang:
        coordinates: 178,43,223,360,119,360,70,185,69,58
      sitzplatz:
        coordinates: 345,182,481,305,380,360,223,360,154,219
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_garden
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
  garage:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    zones:
      autos:
        coordinates: 281,84,317,94,378,126,496,360,195,360,200,85
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
  garden:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    zones:
      weg:
        coordinates: 0,157,64,154,70,263,26,265
      wiese:
        coordinates: 357,229,640,298,640,360,0,360,0,273
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
version: 0.14
```

### Relevant log output

```shell
no relevant log found
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolink
