### DISCUSSION TITLE
[Bug]:  Android mobile browsers - Layout problem after full-screen display

### DISCUSSION THREAD

**Discussion by ubawurinna** [blakeblackshear/frigate#12279] [Report a Bug]
### Describe the problem you are having

After displaying a video to full screen, the interface is shifted upwards.

### Steps to reproduce

The problem is easy to reproduce on Firefox. I also had it on Chrome but I don't remember how I did it.

In Firefox in **portrait mode** with the **address bar at the top**:
In the live view, click on the full-screen icon, **move your finger around the screen** (move the video or enlarge it), then click on the exit full-screen icon.
The interface shifts upwards, and the top button bar is no longer accessible.

### Version

0.14 commit 784b701

### Frigate config file

```yaml
go2rtc:
  streams:
    camera1:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream1
    lowres:
      - rtsp://{FRIGATE_CAMERA1_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:{FRIGATE_CAMERA1_PORT_RTSP}/stream2

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lowres
          roles:
            - detect
    live:
      stream_name: camera1
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Tapo
