### DISCUSSION TITLE
[Config Support]: Storing event/motion clips in a separate folder; or uploading them to a cloud provider

### DISCUSSION THREAD

**Discussion by aeronautjohn** [blakeblackshear/frigate#12274] [Config Support]
### Describe the problem you are having

Howdy folks!

So I have Frigate running as a Home Assistant add-on in my RV. It runs just a single camera, pretty simple setup. I store my RV off-site so I like being able to check on it remotely and have the motion detection.

The RV has a cellular internet connection that is unlimited; but de-prioritizes me after 50GB. That can be pretty quickly eaten up by nightly backups of the /media folder. But I don't want to rely on _only_ local copies of files. If the RV were stolen and the 12v power disconnected or the modem damaged or something like that; or the RPi itself nabbed from out of it; I wouldn't have any way to access anything.

So _ideally_, what I want to happen is to **not** backup any of the clips on my nightly Google Drive backups; but to _immediately_ upload any events/motion detection clips to a cloud provider. 

Is there a way to accomplish this?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: core-mosquitto
  user: [REDACTED]
  password: [REDACTED]

ffmpeg:
  hwaccel_args: preset-rpi-64-h264


record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  [REDACTED]:
    ffmpeg:
      inputs:
      - path: rtsp://[REDACTED]
        roles:
        - detect
    motion:
      mask:
        - 1694,136,2304,157,2304,0,1680,0
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)
