### DISCUSSION TITLE
[Bug]: Mask Creation Screen Old Snapshot of Camera

### DISCUSSION THREAD

**Discussion by spikked27** [blakeblackshear/frigate#12289] [Report a Bug] [answered]
![Screenshot_20240703_183024_Chrome Beta](https://github.com/blakeblackshear/frigate/assets/26699225/90201206-c162-4b44-95f3-9e5d50f66e3e)
### Describe the problem you are having

I rotated the orientation of my camera today and the preview on the motion mask creation screen won't update, should this happen automatically or will I need to force it to update latest.jpeg somehow?

### Steps to reproduce

Go to the motion mask creation tool after moving your camera, displayed image will be old making it useless for masking out regions

### Version

14 beta 3

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  hwaccel_args: preset-nvidia-h265

go2rtc:
  streams:
    front_door:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=h265#audio=copy
      - rtsp://XXX:XXX@192.168.0.112:554/h264Preview_01_sub
    front_door_sub:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX
      - rtsp://XXX:XXX@192.168.0.112:554/h264Preview_01_sub

    webrtc:
    candidates:
      - 192.168.0.101:8555
      - stun:8555

cameras:
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_door

detect:
  width: 640
  height: 480
  fps: 4

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 365
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
```

### Relevant log output

```shell
Not relevant
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Reolink video doorbell

![Uploading Screenshot_20240703_183110_Chrome Beta.jpg…]()
