### DISCUSSION TITLE
[Support]:frigate refuses to start( pls help

### DISCUSSION THREAD

**Discussion by Nick-500** [blakeblackshear/frigate#12287] [General Support]
### Describe the problem you are having

After the last update Frigate doesnt start. I didnt modufy anything in the frigate config. i tryed Frigates simple config: mqtt:
  enabled: False

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect
But no mater what i do it doesnt help.
Deleted and instaled again: go2rtc, frigat, Mqtt.... no luck(((

### Version

Core
2024.7.0b9
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240702.0

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci

mqtt:
  host: homeassistant.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: Irrational17 #your mqtt user
  password: 17lanoitarrl #your mqtt password
  stats_interval: 60
  
# Go2rtc cams:
go2rtc:
  streams:
    my_camera:
      - echo: bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.kam_skld_5_1
    my_camera1:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.kotelnaia
    kam_vorota_2:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.kam_vorota_2
cameras:
  kam_skld_5_1:
    ffmpeg:
      inputs:
        - path: "rtsp://192.168.88.139:8554/my_camera?video"
          input_args: "preset-rtsp-restream-low-latency"
          roles:
            - detect 
  kamera_nad_shchitovoi_none:
    ffmpeg:
      inputs:
        - path: "rtsp://192.168.88.139:8554/my_camera1?video"
          input_args: "preset-rtsp-restream-low-latency"
          roles:
            - detect       
  kam_vorota_2:
    ffmpeg:
      inputs:
        - path: "rtsp://192.168.88.139:8554/kam_vorota_2?video"
          input_args: "preset-rtsp-restream-low-latency"
          roles:
            - detect 

#IP cams:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.88.23:554
          roles:
            - record
            - detect 
    detect: 
      height: 720
      fps: 5

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

ffmpeg:  
  hwaccel_args: preset-rpi-64-h264

objects: 
  track:
    - person
    - dog
    - cat  
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 0
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
```

### Relevant log output

```shell
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
2024-07-03 19:27:14.844041350  [INFO] Preparing Frigate...
s6-rc: info: service legacy-services: starting
2024-07-03 19:27:14.845932241  [INFO] Starting NGINX...
Error: bad file '/config/frigate.yaml': yaml: line 8: did not find expected '-' indicator
2024-07-03 19:27:14.849098035  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-07-03 19:27:14.854581552  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-07-03 19:27:14.865829046  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-07-03 19:27:14.883050523  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2024-07-03 19:27:14.886326781  [INFO] Got IP address from supervisor: 192.168.88.139
s6-rc: info: service frigate-log successfully stopped
2024-07-03 19:27:14.889276940  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-07-03 19:27:22.728826371  [INFO] Preparing Frigate...
2024-07-03 19:27:22.730241668  [INFO] Starting NGINX...
2024-07-03 19:27:22.730385580  [INFO] Preparing new go2rtc config...
Error: bad file '/config/frigate.yaml': yaml: line 8: did not find expected '-' indicator
2024-07-03 19:27:22.737385110  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-07-03 19:27:22.749179384  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-07-03 19:27:22.765215254  [INFO] Got IP address from supervisor: 192.168.88.139
2024-07-03 19:27:22.771207492  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-07-03 19:27:22.779008094  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
0
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua, hikvision
