### DISCUSSION TITLE
[Detector Support]: MQTT frigate/<camera_name>/lightning_threshold/set

### DISCUSSION THREAD

**Discussion by philippecrowdsec** [blakeblackshear/frigate#12284] [Detector Support] [answered]
### Describe the problem you are having

Hi everyone,

I'm trying to tune different values for day/night detection.
During night, I like to adjust motion threshold and lightning_threshold using an MQTT publication.

In the documentation, I've only found a motion threshold but no lightning_threshold, would this be useful to others too?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
camera1:
    enabled: true
    best_image_timeout: 60
    ffmpeg:
      retry_interval: 20
      hwaccel_args: preset-vaapi
      inputs:
      - path: 
          rtsp://[redacted]@[redacted]/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
        roles:
        - detect
        - record
      - path: 
          rtsp://[redacted]@[redacted]/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
        roles:
        - rtmp
      output_args:
        rtmp: -aspect 720:480 -c copy -f flv
    motion:
      mask:
        - 491,720,0,720,0,490,0,185,0,0,560,0,573,153,330,164,331,250,483,265,576,563
        - 1280,397,1004,369,764,324,670,283,649,139,558,144,556,0,1280,0
        - 1280,720,1280,610,1211,527,766,527,581,720
      contour_area: 35
      frame_alpha: 0.01
      frame_height: 90
      mqtt_off_delay: 30
      improve_contrast: true    # false during day, true by night
      threshold: 50             # 30 by night, 50 by day
      lightning_threshold: 0.8  # 0.7 by day, 0.85 by night
[...]
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    network_mode: "host"   
    container_name: frigate
    privileged: true               
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: "160mb"                                     
    devices:
      - /dev/bus/usb:/dev/bus/usb  
      - /dev/dri/renderD128        
    volumes:
      - /usr/local/docker:/config
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/docker/frigate_config.yml:/config/config.yml
      - /mnt/storage:/media/frigate
      - type: tmpfs                
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: [redacted]
```

### Relevant log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
