### DISCUSSION TITLE
[General Support]: would go2rtc be a good idea for me, a new user?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#12282] [General Support] [answered]
### Describe the problem you are having

Hello all

I use four out of a total of eight cameras, part of a cheap Chinese WiFi NVR from eBay, using the H265 rtsp streams from the NVR set top box. The NVR is made by "Floureon" and it is similar to Sannce, Anran, Maisi, Zosi and a dozen other names who rebrand equipment full of Xiong Mai (XM) firmware and maybe OEM from Hikvision? Don't know).

I can't render H265 in my browser but I *do* understand why. However, is it worth me moving over to go2RTC instead?  I have tried to understand the advantages but I haven't grasped the pros and cons of go2RTC vs my current RTSP-streamed H265 (which I think ends up as jsmpeg).

My "go2rtc goal" would be to realise the video (and there is audio available per camera with which I have done nothing so far) in the full 1920 x 1080 resolution available and stream it live in Frigate's  browser UI window. There may be other advantages - please let me know.

I'm very much a beginner, so much so that I fear I may have chosen the wrong category for this question so please advise if so and I can delete/repost.

EB

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false


### don't add this accelerator: it all stops working ###
###ffmpeg:
  ###hwaccel_args: preset-vaapi
  ###hwaccel_args: preset-intel-qsv-h265
### don't add this accelerator: it all stops working ###

detectors:
  coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

birdseye:
  enabled: true
  mode: continuous #continuous | objects | motion

# record: # <----- Enable recording # was working
#  enabled: true # was working

# added from https://fixtse.com/blog/coral-ia-frigate start#
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
# added from https://fixtse.com/blog/coral-ia-frigate #

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 768
  #height: 800
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 7
      cat: 7
      dog: 7
      bird: 7
      fox: 7
      badger: 7
      car: 7
      licence_plate: 7

  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

##########################################################
##########################################################
##########################################################
##########################################################
##########################################################

cameras:
  upper_patio:
    enabled: true
    ffmpeg:
      inputs:

      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
      #- path: http://truenas.local:8082/media=0/channel=1&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
      #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
        roles:
        - detect

      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
      

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 1

    motion:
      mask:
      - 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0
    

  blue_gate:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placehlder
      - badger # placeholder
      - car
      - licence_plate

    birdseye:
      mode: continuous   #continuous | objects | motion
      # masks are black: they block out areas where you aren't interested in detecting things
      order: 2
      
      motion:
      mask:
      #  - 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0
      - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
      - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360
         
   

    zones:
      gravel:
        coordinates: 
          411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233

  drive:
    enabled: true

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
      - car
      - licence_plate

    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; changing track0 to track1 didn't work)
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;(changing track0 to track1 didn't work)
        roles:
        - record

    birdseye:
      mode: continuous #continuous | objects | motion
      #restream: True
      order: 4

    motion:
      # masks are black: they block out areas where you aren't interested in detecting things
      mask:
      - 98,129,170,113,189,0,0,0,0,0,0,142
      - 273,0,170,0,178,67,258,117,256,191,414,181,640,307,640,0

    # zones are red: they select areas where monitoring of activity is wanted
    zones:
      zone_0:
        coordinates: 
          78,360,248,360,381,360,640,360,640,276,449,177,303,183,298,129,200,64,144,113,0,127,0,360


  lower_patio:
      enabled: true
      ffmpeg:
        inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
          roles:
          - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
          - record

      objects:
        track:
        - person
        - cat
        - dog
        - bird
        - deer
        - fox #placeholder
        - badger #placeholder

      birdseye:
        mode: continuous #continuous | objects | motion
        order: 3

      # masks are black: they block out areas where you aren't interested in detecting things
      motion:
        mask:
        - 0,148,92,104,184,55,253,0,269,154,272,305,318,125,354,107,345,56,406,60,417,131,504,240,570,360,640,360,640,0,0,0
        #- 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

        


#-----------------------END-----------------------#
```

### Relevant log output

```shell
2024-07-03 12:10:28.682949855  [INFO] Preparing Frigate...
2024-07-03 12:10:28.716166878  [INFO] Starting Frigate...
2024-07-03 12:10:31.434089510  [2024-07-03 12:10:31] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-03 12:10:34.466259168  [2024-07-03 12:10:34] peewee_migrate.logs            INFO    : Starting migrations
2024-07-03 12:10:34.472249755  [2024-07-03 12:10:34] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-07-03 12:10:34.478305004  [2024-07-03 12:10:34] frigate.app                    INFO    : Recording process started: 476
2024-07-03 12:10:34.481665656  [2024-07-03 12:10:34] frigate.app                    INFO    : go2rtc process pid: 89
2024-07-03 12:10:34.515535921  [2024-07-03 12:10:34] detector.coral                 INFO    : Starting detection process: 485
2024-07-03 12:10:34.522836150  [2024-07-03 12:10:34] frigate.app                    INFO    : Output process started: 487
2024-07-03 12:10:37.200273715  [2024-07-03 12:10:34] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-07-03 12:10:37.200280766  [2024-07-03 12:10:34] frigate.app                    INFO    : Camera processor started for upper_patio: 499
2024-07-03 12:10:37.200288491  [2024-07-03 12:10:34] frigate.app                    INFO    : Camera processor started for blue_gate: 508
2024-07-03 12:10:37.200292026  [2024-07-03 12:10:34] frigate.app                    INFO    : Camera processor started for drive: 513
2024-07-03 12:10:37.200321117  [2024-07-03 12:10:34] frigate.app                    INFO    : Camera processor started for lower_patio: 515
2024-07-03 12:10:37.200324811  [2024-07-03 12:10:34] frigate.app                    INFO    : Capture process started for upper_patio: 517
2024-07-03 12:10:37.200349647  [2024-07-03 12:10:34] frigate.app                    INFO    : Capture process started for blue_gate: 519
2024-07-03 12:10:37.200962588  [2024-07-03 12:10:34] frigate.app                    INFO    : Capture process started for drive: 524
2024-07-03 12:10:37.200966067  [2024-07-03 12:10:34] frigate.app                    INFO    : Capture process started for lower_patio: 529
2024-07-03 12:10:37.206457446  [2024-07-03 12:10:37] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
SD stream, detect:
ffprobe rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0
[1] 1660202
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x5602f00d6680] method DESCRIBE failed: 404 Not Found
rtsp://192.168.1.123:554/media=0/channel=1: Server returned 404 Not Found

and

HD stream, record:
ffprobe rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0
[2] 1660344
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x560da16a7680] method DESCRIBE failed: 404 Not Found
rtsp://192.168.1.123:554/media=0/channel=1: Server returned 404 Not Found
```

### Frigate stats

```json
{"cameras":{"blue_gate":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":519,"detection_enabled":1,"detection_fps":5.6,"ffmpeg_pid":526,"pid":508,"process_fps":4.6,"skipped_fps":0.5},"drive":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":524,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":532,"pid":513,"process_fps":5.0,"skipped_fps":0.1},"lower_patio":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":529,"detection_enabled":1,"detection_fps":0.7,"ffmpeg_pid":539,"pid":515,"process_fps":4.8,"skipped_fps":0.3},"upper_patio":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":517,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":525,"pid":499,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"97":{"cmdline":"python3 -u -m frigate","cpu":"2.5","cpu_average":"1","mem":"1.0"},"98":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"151":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"171":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"180":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"190":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"207":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"442":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"476":{"cmdline":"frigate.recording_manager","cpu":"0.8","cpu_average":"0","mem":"0.7"},"484":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"485":{"cmdline":"frigate.detector.coral","cpu":"3.1","cpu_average":"3","mem":"0.7"},"487":{"cmdline":"frigate.output       ","cpu":"0.8","cpu_average":"0","mem":"0.7"},"493":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"494":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"495":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"496":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"498":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"499":{"cmdline":"frigate.process:upper_patio","cpu":"1.5","cpu_average":"1","mem":"0.7"},"508":{"cmdline":"frigate.process:blue_gate","cpu":"6.5","cpu_average":"6","mem":"0.7"},"513":{"cmdline":"frigate.process:drive","cpu":"1.5","cpu_average":"1","mem":"0.7"},"515":{"cmdline":"frigate.process:lower_patio","cpu":"2.0","cpu_average":"1","mem":"0.7"},"517":{"cmdline":"frigate.capture:upper_patio","cpu":"0.6","cpu_average":"0","mem":"0.6"},"519":{"cmdline":"frigate.capture:blue_gate","cpu":"0.5","cpu_average":"0","mem":"0.6"},"524":{"cmdline":"frigate.capture:drive","cpu":"0.6","cpu_average":"0","mem":"0.6"},"525":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.5","cpu_average":"2","mem":"0.1"},"526":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.1"},"529":{"cmdline":"frigate.capture:lower_patio","cpu":"0.6","cpu_average":"0","mem":"0.6"},"532":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.1"},"538":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/blue_gate@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.0"},"539":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.1"},"542":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/upper_patio@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.0"},"543":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/drive@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.0"},"546":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/lower_patio@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.0"},"758":{"cmdline":"/bin/sh","cpu":"0.0","cpu_average":"0","mem":"0.0"},"9789":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":6.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.39,"pid":485}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":442},"recording":{"pid":476}},"service":{"last_updated":1720011094,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":86.0,"mount_type":"tmpfs","total":90.0,"used":4.0},"/media/frigate/clips":{"free":810781.1,"mount_type":"zfs","total":846275.2,"used":35494.1},"/media/frigate/recordings":{"free":810781.1,"mount_type":"zfs","total":846275.2,"used":35494.1},"/tmp/cache":{"free":1022.7,"mount_type":"tmpfs","total":1024.0,"used":1.3}},"temperatures":{},"uptime":2460,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Floureon NVR with unknown WiFi CCTV camera model number

### Any other information that may be helpful

This is using the TrueNAS Frigate app installed on TrueNAS scale 24 (Dragonfish) - not pure Docker but I don't understand enough to describe the methods used.
