### DISCUSSION TITLE
[Support]: Export page is blank?

### DISCUSSION THREAD

**Discussion by rovingclimber** [blakeblackshear/frigate#12286] [General Support] [answered]
### Describe the problem you are having

Hi! I'm testing 0.14.0-4e5a6eb (beta 3) but on my Export page there is nothing but a search bar at the top. From the docs it seems I should be be able to select time ranges to export but I don't have any UI visible to do that. Everything else seems to be working. Probably I'm being an idiot, but I can't see how?

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: 192.168.1.123
  user: homeassistant
  password: *******
  topic_prefix: frigate

model:
  path: plus://##mymodel###

detectors:
  coral0:
    type: edgetpu
    device: pci:0
  coral1:
    type: edgetpu
    device: pci:1
ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

snapshots:
  enabled: true
  retain:
    default: 14
    objects:
      person: 31
      cat: 14
go2rtc:
  ffmpeg:
    frigatedefaults: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
      tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  streams:
    catcam1:
      - rtsp://catcam:*****=@catcam.mydomain.com:554/stream1
      - ffmpeg:catcam1#video=copy#audio=aac
    catcam1-low:
      - rtsp://catcam:*****=@catcam.mydomain.com:554/stream2
      - ffmpeg:catcam1#video=copy
    catcam2:
      - rtsp://catcam2:*****@catcam2.mydomain.com:554/stream1
      - ffmpeg:catcam2#video=copy#audio=aac
    catcam2-low:
      - rtsp://catcam2:*****@catcam2.mydomain.com:554/stream2
      - ffmpeg:catcam2#video=copy
    catcam5:
      - rtsp://catcam5:*****@catcam5.mydomain.com:554/stream1
      - ffmpeg:catcam5#video=copy#audio=aac
    catcam5-low:
      - rtsp://catcam5:*****@catcam5.mydomain.com:554/stream2
      - ffmpeg:catcam5#video=copy
    catcam7:
      - rtsp://catcam7:*****@catcam7.mydomain.com:554/stream1
      - ffmpeg:catcam7#video=copy#audio=aac
    catcam7-low:
      - rtsp://catcam7:*****@catcam7.mydomain.com:554/stream2
      - ffmpeg:catcam7#video=copy      
    catcam9:
      - rtsp://catcam9:*****@catcam9.mydomain.com:554/stream1
      - ffmpeg:catcam9#video=copy
    catcam9-low:
      - rtsp://catcam9:*****@catcam9.mydomain.com:554/stream2
      - ffmpeg:catcam9#video=copy
  webrtc:
    candidates:
      - frigate.mydomain.com:8555
      - stun:8555

cameras:
  catcam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/catcam1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/catcam1-low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
    birdseye:
      mode: continuous
  catcam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/catcam2-low
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/catcam2
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
  catcam5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/catcam5-low
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/catcam5
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    birdseye:
      mode: continuous
  catcam7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/catcam7-low
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/catcam7
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - cat
        - person
      filters:
        person:
          threshold: 0.9
          mask: 1062,414,821,293,871,0,1137,0
    detect:
      width: 1280
      height: 720
  catcam9:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/catcam9-low
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/catcam9
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - cat
        - person
      filters:
        person:
          threshold: 0.9
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 0,31,413,29,411,0,0,0
        - 206,0,219,115,166,190,133,62

      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
objects:
  track:
    - cat
  filters:
    cat:
      threshold: 0.88
      min_area: 1000


detect:
  stationary:
    threshold: 200

birdseye:
  restream: true

record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 14
      mode: active_objects

version: 0.14
camera_groups: {}
```

### Relevant log output

```shell
No log, it's just missing UI for me
```

### FFprobe output from your camera

```shell
Cameras all working AOK
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Various
