### DISCUSSION TITLE
[Support]: Lost DB upon upgrade / adding FRIGATE+

### DISCUSSION THREAD

**Discussion by Mister-A** [blakeblackshear/frigate#12283] [General Support] [answered]
### Describe the problem you are having

I just stopped, removed and recreated my Frigate docker container to get the latest version (I was already on 0.13.something) and to add my new Frigate+ API key.

When restarted it seems to have lost all events and recordings from the UI - it did a new DB migration and all events and recordings have vanished, though the files are still in the storage folder.

Is there a way to get them back? There's a 433MB DB file in the folder - that feels too big for "virgin" so is it still there?

How do I avoid this in future? (It's never happened before and I've re-run with the latest stable docker image a few times before this one)

Docker run
`docker run -d --name frigate --restart=always --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/dri --device /dev/bus/usb:/dev/bus/usb --shm-size=256m -v /storage/media:/media/frigate -v /storage/config/config.yml:/config/config.yml -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='****' -e PLUS_API_KEY='****' -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp ghcr.io/blakeblackshear/frigate:stable`

(Note when I try the newest advice of not directly mounting the config.yml file, just the folder, the Docker never finishes starting - I can only get it to run if I provide the path to the config.yml itself)

Thanks
Andrew

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.10
  user: ****
  password: ****
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      mode: active_objects
      default: 28
snapshots:
  enabled: true
  retain:
    default: 45
birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720
objects:
  track:
  - person
  - car
  - motorcycle
  - bus
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
go2rtc:
  streams:
    front_wide:
    - rtsp://****:****@10.0.0.71:554/1/1#hardware
    - ffmpeg:front_wide#audio=aac
    front_door:
    - rtsp://****:****@192.168.1.61:554/stream1#hardware
    - ffmpeg:front_door#audio=aac
    front_door2:
    - rtsp://****:****@10.0.0.67:554/1/1#hardware
    - ffmpeg:front_door2#audio=aac
    garden_wide:
    - rtsp://****:****@10.0.0.70:554/Preview_01_main#hardware
    - ffmpeg:garden#audio=aac
    garden:
    - rtsp://****:****@192.168.1.60:10554/tcp/av0_1#hardware
    - ffmpeg:garden#audio=aac
cameras:
  front_wide:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://****:****@10.0.0.71:554/1/1
        roles:
        - record
      - path: rtsp://****:****@10.0.0.71:554/1/1
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
      - 1280,0,1280,465,1110,385,893,426,820,422,930,309,1033,236,1006,132,865,107,746,110,688,130,618,235,555,252,422,229,360,221,323,208,35,183,0,169,0,60,0,0
      - 39,720,669,720,721,677,758,640,796,594,823,565,854,534,848,496,834,479,815,418,791,407,750,409,725,394,701,378,683,324,578,276,74,203,160,358,53,401,0,481,0,596,0,661
    zones:
      driveway:
        coordinates: 995,285,911,256,832,243,766,241,638,251,577,288,688,414,821,421
    objects:
      filters:
        car:
          mask:
          - 270,201,489,236,620,185,667,139,751,120,938,169,1280,230,1280,0,924,0,0,0,0,156
  front_door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://****:****@192.168.1.61:554/stream1
        roles:
        - record
        - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
      - 1220,0,0,0,0,38,564,69,696,615,769,680,879,684,1170,510
  front_door2:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://****:****@10.0.0.67:554/1/1
        roles:
        - record
      - path: rtsp://****:****@10.0.0.67:554/1/1
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
      - 640,0,0,0,0,21,161,21,365,21,439,100,464,294,640,360
  garden_wide:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://****:****@10.0.0.70:554/Preview_01_main
        roles:
        - record
      - path: rtsp://****:****@10.0.0.70:554/Preview_01_main
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
      - 0,0,1280,0,1280,720,1061,720,966,439,941,334,892,309,862,497,744,504,583,464,584,398,600,220,515,233,521,350,433,442,0,665
    objects:
      filters:
        person:
          mask:
          - 0,0,1280,0,1280,720,1061,720,966,439,941,334,892,309,862,497,744,504,583,464,584,398,600,220,527,220,548,316,464,439,0,665
  garden:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://****:****@192.168.1.60:10554/tcp/av0_1
        roles:
        - record
        - detect
    detect:
      width: 1152
      height: 648
    motion:
      mask:
      - 0,0,177,0,845,0,1152,0,1152,339,266,329,0,257
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"cameras":{"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":327,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":335,"pid":313,"process_fps":5.1,"skipped_fps":0.0},"front_door2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":330,"detection_enabled":1,"detection_fps":0.9,"ffmpeg_pid":341,"pid":315,"process_fps":5.1,"skipped_fps":0.0},"front_wide":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":321,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":331,"pid":311,"process_fps":5.1,"skipped_fps":0.0},"garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":349,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":363,"pid":319,"process_fps":5.0,"skipped_fps":0.0},"garden_wide":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":337,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":359,"pid":318,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"94":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.2"},"105":{"cmdline":"python3 -u -m frigate","cpu":"2.5","cpu_average":"2","mem":"3.6"},"112":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"287":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"289":{"cmdline":"frigate.recording_manager","cpu":"4.0","cpu_average":"3","mem":"1.7"},"298":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"299":{"cmdline":"frigate.detector.coral","cpu":"0.7","cpu_average":"2","mem":"1.7"},"301":{"cmdline":"frigate.output       ","cpu":"1.3","cpu_average":"1","mem":"1.5"},"307":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"308":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"310":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.6"},"311":{"cmdline":"frigate.process:front_wide","cpu":"1.5","cpu_average":"1","mem":"1.5"},"313":{"cmdline":"frigate.process:front_door","cpu":"1.7","cpu_average":"1","mem":"1.6"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"315":{"cmdline":"frigate.process:front_door2","cpu":"1.4","cpu_average":"1","mem":"1.6"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1152x648 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"318":{"cmdline":"frigate.process:garden_wide","cpu":"1.3","cpu_average":"1","mem":"1.5"},"319":{"cmdline":"frigate.process:garden","cpu":"1.1","cpu_average":"1","mem":"1.8"},"321":{"cmdline":"frigate.capture:front_wide","cpu":"1.1","cpu_average":"1","mem":"1.4"},"325":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"327":{"cmdline":"frigate.capture:front_door","cpu":"1.2","cpu_average":"1","mem":"1.4"},"330":{"cmdline":"frigate.capture:front_door2","cpu":"1.2","cpu_average":"1","mem":"1.4"},"331":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.71:554/1/1 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.5","cpu_average":"2","mem":"0.7"},"335":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.61:554/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.8","cpu_average":"3","mem":"0.7"},"337":{"cmdline":"frigate.capture:garden_wide","cpu":"1.2","cpu_average":"1","mem":"1.4"},"341":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.67:554/1/1 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.0","cpu_average":"2","mem":"0.7"},"349":{"cmdline":"frigate.capture:garden","cpu":"0.9","cpu_average":"0","mem":"1.4"},"355":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.71:554/1/1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_wide@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.3"},"359":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.70:554/Preview_01_main -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"5","mem":"0.8"},"363":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.60:10554/tcp/av0_1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1152:h=648:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.3","cpu_average":"3","mem":"0.6"},"364":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.67:554/1/1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_door2@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"1","mem":"0.3"},"367":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.70:554/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garden_wide@%Y%m%d%H%M%S%z.mp4","cpu":"3.2","cpu_average":"3","mem":"0.3"},"1885":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":1.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.83,"pid":299}},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"processes":{"go2rtc":{"pid":94},"logger":{"pid":287},"recording":{"pid":289}},"service":{"last_updated":1720015934,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":246.5,"mount_type":"tmpfs","total":256.0,"used":9.5},"/media/frigate/clips":{"free":43095.2,"mount_type":"ext4","total":906041.8,"used":823998.8},"/media/frigate/recordings":{"free":43095.2,"mount_type":"ext4","total":906041.8,"used":823998.8},"/tmp/cache":{"free":930.3,"mount_type":"tmpfs","total":953.7,"used":23.4}},"temperatures":{},"uptime":785,"version":"0.13.2-6476f8a"}}
```

### Operating system

Proxmox

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Various
