### DISCUSSION TITLE
Zones and masks sometimes change upon restart.

### DISCUSSION THREAD

**Discussion by Bug23451** [blakeblackshear/frigate#12293] [Report a Bug]
### Describe the problem you are having

I configure zones and masks either by gui or cli and upon reboot of container (or whole system) the points of the zones will shift and/or scale. 
As in the shape of the zone/ mask will renain but will move around and/or become bigger or smaller.

Note that this is not a visual bug as home assistant starts to misbehave and the config changes.

### Steps to reproduce

Create zone/masks by preferred method.
Restart docker/host.
Inspect zones/masks.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
cameras:
  Cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Cam
        roles:
        - detect
        - record
        - audio
    zones:
      zone0:
        coordinates: 665,517,1074,566,1280,720,0,720,0,28
      zone1:
        coordinates: 637,65,1188,100,1019,424,704,401
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Tapo C210

### Any other information that may be helpful

Happens on 2 cameras, same model.
