### DISCUSSION TITLE
[Support]: Home Assistant integration doesn't show correct status

### DISCUSSION THREAD

**Discussion by McPaHa** [blakeblackshear/frigate#12307] [General Support] [answered]
### Describe the problem you are having

Integration is working - I see cameras, clips etc but for example HA shows camera "detect" entity always on and it doesn't change even if I change camera setting in Frigate web-page.

That's why my camera automations doesn't work also.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.60
  client_id: frigate
  user: mqtt
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
   restream: true
   enabled: True
   width: 1280
   height: 720
   quality: 8
   mode: motion

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

record:
  enabled: true
  retain: 
    days: 14
  events:
    retain:
      default: 14

snapshots:
  enabled: True
  bounding_box: True
  crop: false
  retain:
    default: 14

environment_vars:
  PLUS_API_KEY: xxxx

ui:
  use_experimental: false

rtmp:
  enabled: false

go2rtc:
  log:
    exec: trace
  streams:
    Etupiha:  
      - rtsp://xxx:xxxx@192.168.1.67:554/Streaming/Channels/1
    Takapiha2:
      - ffmpeg:rtsp://xxx:xxxx@192.168.1.66:554/cam/realmonitor?channel=1&subtype=0
    Takapiha:
      - ffmpeg:rtsp://xxx:xxxx192.168.1.65:554/cam/realmonitor?channel=1&subtype=0
    Mokkitienpuoli:
      - ffmpeg:rtsp://xxx:xxxx@xxx.xxxx:1111/cam/realmonitor?channel=1&subtype=0
    Mokkijarvenpuoli:
      - ffmpeg:rtsp://xxx:xxxx@xxx.xxxx:554/cam/realmonitor?channel=1&subtype=0
    Mokkisisa:
      - ffmpeg:rtsp://xxx:xxxx@xxx.xx:8554/unicast    
    Eteinen:
      - ffmpeg:rtsp://xxx:xxxx&@192.168.1.50:554/stream1

cameras:

#  Keittio:
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.1.119:8080/h264_pcm.sdp
#          roles:
#            - rtmp
#            - record
#    rtmp:
#      enabled: True
#    detect:
#      enabled: False
#    snapshots:
#      enabled: False


  Etupiha:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Etupiha
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      etupiha_ovella:
        coordinates: 1289,833,873,734,1066,285,1349,307
        objects:
          - person
      etupiha_muualue:
        coordinates: 869,568,826,352,445,355,403,493
        objects:
          - person
          - dog
          - cat
          - motorcycle
      etupihaan_sisääntulo:
        coordinates: 373,380,577,403,789,162,605,159
        objects:
          - person
          - dog
          - cat
          - car
          - motorcycle
    record:
      events:
        required_zones:
          - etupiha_ovella
          - etupiha_muualue
          - etupihan_sisääntulo
    snapshots:
      required_zones:
        - etupiha_ovella
        - etupiha_muualue
        - etupihan_sisääntulo

    motion:
      mask:
        - 313,402,0,0,659,0,675,120
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - motorcycle
      filters:
        person:
          min_area: 10000
          max_area: 100000



  Takapiha2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Takapiha2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          max_area: 300000


    motion:
      mask:
        - 1824,0,1809,180,1699,167,1684,0

  Mokkitienpuoli:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Mokkitienpuoli
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      mökki_sisääntulo_ajo:
        coordinates: 934,313,1186,323,1140,253,918,252
        objects:
          - person
          - dog
          - car
          - cat

      mökkivaja_sisääntulo_ajo:
        coordinates: 53,292,258,273,222,206,55,200
        objects:
          - person
          - dog
          - car
          - cat

      mökin_edusta:
        coordinates: 1250,605,1430,661,1626,750,1706,760,1809,938,1850,862,1920,691,1920,479,1865,321,1494,113,1270,77,1215,323,1200,316,918,316
        objects:
          - person
          - dog
          - cat
          - bird
      mökin_muu_alue:
        coordinates: 876,132,970,394,1262,594,1686,744,1834,889,1672,1080,487,1080,0,1080,0,306,117,266,285,260,289,136
        objects:
          - person
          - dog
          - cat
          - bird
      mökin_tontin_ulkopuoli:
        coordinates: 285,0,1428,0,1174,128,1250,168,1237,257,1128,240,913,209,906,116,468,122,302,116,285,196,236,193,70,196,269,146
        objects:
          - person
          - car
    record:
      events:
        required_zones:
          - mökin_edusta
          - mökin_muu_alue
          - mökin_tontin_ulkopuoli
          - mökki_sisääntulo_ajo
          - mökkivaja_sisääntulo_ajo
    snapshots:
      required_zones:
          - mökin_edusta
          - mökin_muu_alue
          - mökin_tontin_ulkopuoli
          - mökki_sisääntulo_ajo
          - mökkivaja_sisääntulo_ajo

    motion:
      mask:
        - 0,0,0,208,277,141,288,0
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bird
      filters:
        person:
          mask:
            - 1518,906,1549,881,1611,804,1675,745,1694,726,1699,704,1712,661,1677,621,1643,572,1611,544,1584,503,1523,509,1472,544,1416,666,1315,794,1512,931,1479,934

  Takapiha:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Takapiha
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 65000

  Mokkijarvenpuoli:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Mokkijarvenpuoli
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 2000
    motion:
      mask:
        - 743,204,732,348,651,348,644,213


  Mokkisisa:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Mokkisisa
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person

  Eteinen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Eteinen
          input_args: preset-rtsp-restream
```

### Relevant log output

```shell
Not camera problem
```

### FFprobe output from your camera

```shell
Not camera problem
```

### Frigate stats

```json
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful
Home Assistant
Core 2024.7.0
Supervisor 2024.06.2
Operating System Frontend 20240703.0
