### DISCUSSION TITLE
[Bug]: 0.14.0 Beta 3 does not respect camera specific mqtt settings

### DISCUSSION THREAD

**Discussion by QBANIN** [blakeblackshear/frigate#12310] [Report a Bug] [answered]
### Describe the problem you are having

No matter what I set mqtt snapshot is not cropped. I can see this in my double-take instance where all incoming snapshot are full-size and have bounding box visible. As a result it takes forever (over 1 minute) for double-take to process every snapshot.

### Steps to reproduce

Enable crop in camera specific mqtt settings. Check snapshot output.

### Version

0.14.0 Beta 3

### Frigate config file

```yaml
cameras:
  front:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
```

### Relevant log output

```shell
No errors in log.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink 2 Duo
