### DISCUSSION TITLE
[Question]: Zone, Objects and Config

### DISCUSSION THREAD

**Discussion by jamesonuk** [blakeblackshear/frigate#12321] [Ask A Question]
### What is your question:

I would like to track different objects in different zones but as you can define things in multiple places I am not sure I have the right config

I want to track cars in zone 1 and people / dogs in zone2
```
cameras:
  testcam:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://<stream url>
          roles:
            - detect
        - path: rtsp://<stream url>
           input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - <coordinates>
    zones:
      zone1:
        coordinates: <coordinates>
        inertia: 1
        objects:
          - car
      zone2:
        coordinates: <coordinates>
        objects:
          - person
          - dog
    objects:
      track:
        - person
        - dog
        - car
 ```

Is the objects / track needed?

Does this essentially track the whole frame for motion excluding the motion mask and then checks if cars are detected in zone 1 or people/dogs in zone2 as I want?
