### DISCUSSION TITLE
[HW Accel Support]: Container Not Starting Up With GPU

### DISCUSSION THREAD

**Discussion by ccigas** [blakeblackshear/frigate#12329] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hello, I am tring to deploy frigate in Portainer using the below yaml. I am getting an error that pertains to the GPU and not sure if its something with the drivers or something with my config. I am using Proxmox LXC, blacklisted the nouveau drivers, installed the latest drivers I could get for my P2000, NVIDIA-Linux-x86_64-550.90.07, this is installed in both my Proxmox host and my LXC. 

The error: `Network frigate_default Creating Network frigate_default Created Container frigate Creating Container frigate Created Container frigate Starting Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]] `

Nvidia drivers:
`root@frigate01:~# ls -l /dev/nv*
crw-rw-rw- 1 root root 195, 254 Jul  7 19:08 /dev/nvidia-modeset
crw-rw-rw- 1 root root 511,   0 Jul  7 19:08 /dev/nvidia-uvm
crw-rw-rw- 1 root root 511,   1 Jul  7 19:08 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Jul  7 19:08 /dev/nvidia0
crw-rw-rw- 1 root root 195, 255 Jul  7 19:08 /dev/nvidiactl

/dev/nvidia-caps:
total 0
cr-------- 1 root root 238, 1 Jul  7 19:16 nvidia-cap1
cr--r--r-- 1 root root 238, 2 Jul  7 19:16 nvidia-cap2`

My LXC config: 
`arch: amd64
cores: 4
features: nesting=1
hostname: frigate01
memory: 4096
mp0: /mnt/container_storage/,mp=/mnt/container_storage
mp1: /mnt/file_storage/,mp=/mnt/file_storage
mp2: /mnt/nvr/,mp=/mnt/nvr
net0: name=eth0,bridge=vmbr1,hwaddr=BC:24:11:CB:50:25,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: data:vm-100-disk-1,size=64G
swap: 512
tags: proxmox-helper-scripts
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyUSB1       dev/ttyUSB1       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
lxc.mount.entry: /dev/bus/usb/ dev/bus/usb/ none bind,optional,create=dir 0,0
lxc.cgroup.devices.allow: c 195:* rwm
lxc.cgroup.devices.allow: c 511:* rwm
lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file`

Not sure if I need to add anything else so please ask. 

### Version

Stable

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  enabled: True
  host: ha.home.cigas
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: !

#ffmpeg:
#  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    backyard:
      - rtsp://*:!@172.16.3.53:554/cam/realmonitor?channel=1&subtype=0
    backyard_sub:
      - rtsp://*:!@172.16.3.53:554/cam/realmonitor?channel=1&subtype=1
    front_porch:
      - rtsp://*:!@172.16.3.50:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    front_porch_sub:
      - rtsp://*:!@172.16.3.50:554/cam/realmonitor?channel=1&subtype=1#backchannel=0


timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  Front_Porch:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_porch
          input_args: preset-rtsp-restream
          roles:
            - record
      #hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 2
          mode: active_objects
        pre_capture: 5
        post_capture: 30
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person

  Backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
      #hwaccel_args: preset-nvidia-h265
    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 2
          mode: active_objects
        pre_capture: 5
        post_capture: 10
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person

rtmp:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 1
  mode: objects
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1047MB"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              count: 1
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml
      - /mnt/nvr/frigate/recordings:/media/frigate/recordings
      - /mnt/nvr/frigate/clips:/media/frigate/clips
      - /opt/frigate/db/frigate.db:/db/frigate.db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Web GUI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "***"
```

### Relevant log output

```shell
Network frigate_default Creating Network frigate_default Created Container frigate Creating Container frigate Created Container frigate Starting Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Amcrest
