### DISCUSSION TITLE
[Camera Support]: Reolink Duo 3 POE

### DISCUSSION THREAD

**Discussion by jjavin** [blakeblackshear/frigate#12323] [Camera Support]
### Describe the problem you are having

Good morning, 

Since a few days ago (I think it was after the Reolink firmware update) I get the following error in the log:

`2024-07-07 12:56:09.799871482  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:56:14.940990753  [h264 @ 0x7771e8014f40] Overread VUI by 8 bits
2024-07-07 12:56:29.775875166  [h264 @ 0x7771e8014f40] Overread VUI by 8 bits
2024-07-07 12:56:34.922033703  [h264 @ 0x7771e8014f40] Overread VUI by 8 bits
2024-07-07 12:56:49.785380254  [h264 @ 0x7771e8008740] Overread VUI by 8 bits
2024-07-07 12:56:54.901578996  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:09.747273370  [h264 @ 0x7771e8200980] Overread VUI by 8 bits
2024-07-07 12:57:14.984732713  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:29.744880792  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:34.898475247  [h264 @ 0x7771e8f07dc0] Overread VUI by 8 bits
2024-07-07 12:57:49.740121250  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:54.900477847  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:58:09.748172377  [h264 @ 0x7771e862d680] Overread VUI by 8 bits
2024-07-07 12:58:14.897918238  [h264 @ 0x7771e8f53880] Overread VUI by 8 bits
2024-07-07 12:58:29.745055675  [h264 @ 0x7771e8623f00] Overread VUI by 8 bits
2024-07-07 12:58:34.906478308  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:58:49.755872378  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:58:54.915503766  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:59:09.748668280  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:59:14.920492845  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:59:29.749827334  [h264 @ 0x7771e8f55440] Overread VUI by 8 bits
2024-07-07 12:59:34.901880197  [h264 @ 0x7771e8f3dd00] Overread VUI by 8 bits`

Thanks ;)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
Puerta_H:
    - rtsp://admin:XXXX@192.168.X.XXX:554/h264Preview_01_main
    - "ffmpeg:Puerta_H#audio=aac"
 
    Puerta_L:
    - rtsp://admin:XXXX@192.168.X.XXX:554/h264Preview_01_sub
    - "ffmpeg:Puerta_L#audio=aac"
 
  Puerta:
    birdseye:
      order: 2
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Puerta_L?video=copy&audio=aac
#        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Puerta_L?video=copy
#        input_args: preset-rtsp-restream
        roles:
        - detect
      output_args:
       record: preset-record-generic-audio-copy
    live:
      stream_name: Puerta_H
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1536
      height: 432
      fps: 5
    motion:
      threshold: 30
      contour_area: 10
    record:
      enabled: true
      retain:
        days: 10
        mode: all
      events:
        required_zones:
          - todas
          - entrada_casa
    snapshots:
      required_zones:
      - todas
      - entrada_casa
    zones:
      todas:
        coordinates: 753,432,0,432,0,0,1536,0,1536,432
        objects:
          - dog
          - cat
          - face
          - package
          - license_plate
          - amazon
          - ups
          - fedex
          - person
      entrada_casa:
        coordinates: 68,432,331,248,719,250,870,432
        objects:
          - car                     
    objects:
      track:
       - person
       - face
       - license_plate
       - dog
       - cat
       - car
       - amazon
       - fedex
       - ups
       - package
      filters:
        dog:
          min_score: .7
          threshold: .9
        cat:
          min_score: .7
          threshold: .9
        face:
          min_score: .7
        package:
          min_score: .65
          threshold: .9
        license_plate:
          min_score: .6
        amazon:
          min_score: .75
        ups:
          min_score: .75
        fedex:
          min_score: .75
        person:
          min_score: .7
          threshold: .75
          max_area: 60000
          max_ratio: 0.7         
#        person:
#          min_score: 0.60
##        threshold: 0.8
#          min_area: 1000
##        max_area: 1000000
#        cat:
#          min_score: 0.60
##        threshold: 0.8
#          min_area: 3000
###        max_area: 100000
        car:
          min_score: 0.70
#        threshold: 0.8
          min_area: 4000
#        max_area: 100000   
          mask:
          - 469,59,348,242,998,187,989,34
          - 681,0,0,0,0,432
```

### Relevant log output

```shell
2024-07-07 12:56:09.799871482  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:56:14.940990753  [h264 @ 0x7771e8014f40] Overread VUI by 8 bits
2024-07-07 12:56:29.775875166  [h264 @ 0x7771e8014f40] Overread VUI by 8 bits
2024-07-07 12:56:34.922033703  [h264 @ 0x7771e8014f40] Overread VUI by 8 bits
2024-07-07 12:56:49.785380254  [h264 @ 0x7771e8008740] Overread VUI by 8 bits
2024-07-07 12:56:54.901578996  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:09.747273370  [h264 @ 0x7771e8200980] Overread VUI by 8 bits
2024-07-07 12:57:14.984732713  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:29.744880792  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:34.898475247  [h264 @ 0x7771e8f07dc0] Overread VUI by 8 bits
2024-07-07 12:57:49.740121250  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:57:54.900477847  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:58:09.748172377  [h264 @ 0x7771e862d680] Overread VUI by 8 bits
2024-07-07 12:58:14.897918238  [h264 @ 0x7771e8f53880] Overread VUI by 8 bits
2024-07-07 12:58:29.745055675  [h264 @ 0x7771e8623f00] Overread VUI by 8 bits
2024-07-07 12:58:34.906478308  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:58:49.755872378  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:58:54.915503766  [h264 @ 0x7771e8136680] Overread VUI by 8 bits
2024-07-07 12:59:09.748668280  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:59:14.920492845  [h264 @ 0x7771e813d140] Overread VUI by 8 bits
2024-07-07 12:59:29.749827334  [h264 @ 0x7771e8f55440] Overread VUI by 8 bits
2024-07-07 12:59:34.901880197  [h264 @ 0x7771e8f3dd00] Overread VUI by 8 bits
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":432,"width":1536},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":432,"width":1536}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Duo 3 POE

### Any other information that may be helpful

Firmware version: v3.0.0.3632_2406192112
