### DISCUSSION TITLE
[Camera Support]: Reolink PoE doorbell through NVR, 2-way audio not working

### DISCUSSION THREAD

**Discussion by Timonator** [blakeblackshear/frigate#12335] [Camera Support]
### Describe the problem you are having

Hi all,

Since I am using a samsung phone, 2 -way audio through the Reolink app is useless. Eventhough I’ve been waiting for a very long time from reolink for a fix.

To make the doorbell useful, I need a working 2-way audio and a custom ring sound notification on my phone. Which both could be resolved with the help of home assistant. Currently I have a working stream in the frigate card with video and audio. When enabling the microphone, there just seems to be no output from the doorbell.

So I am running the PoE doorbell through a Reolink NVR model H3MB18 (16port nvr) with firmware version v3.4.0.293_24010833

I had my doorbell on the latest firmware, but I found there are breaking changes in the newer firmwares, therefore I downgraded to version v3.0.0.2033_23041302, which seems to work for other people.

I've heard about https issues as well, but I am running with nabu casa, which should have ssl taken care of.

So I am running:
Home Assistant Blue
Core 2024.7.0
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240703.0
Frigate Add-on 0.13.2-6476f8a
Go2rtc 1.8.4 linux/arm64
Frigate Lovelace Card v5.2.0

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 10.10.1.10         # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ****               # YOUR MQTT USERNAME
  password: ****        # YOUT MQTT PASSWORD
  stats_interval: 60

##########################################################################

go2rtc:
  streams:
                    ## CHANGE RTSP USERNAME AND PASSWORD
    reolink:
      - rtsp://****:****@10.10.1.80:554/h264Preview_01_sub
      - ffmpeg:rtsp://****:****@10.10.1.80/h264Preview_01_sub#audio=pcm#audio=volume


## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  
##########################################################################

cameras:

  reolink:
    ffmpeg:
      inputs:

        - path: rtsp://****:****@10.10.1.80/h264Preview_01_sub
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy

ui:
  live_mode: webrtc
```

### Relevant log output

```shell
{
  "reolink": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
          "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, PCML",
          "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
        ],
        "remote_addr": "udp4 host 10.10.1.138:46713",
        "send": 179284,
        "senders": [
          "102 H264, bytes=117687, receivers=1",
          "8 PCMA/8000, bytes=118752, receivers=1"
        ],
        "type": "WebRTC/WebSocket async passive consumer",
        "user_agent": "Mozilla/5.0 (Linux; Android 13; SM-A536B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Home Assistant/2024.6.1-12936 (Android 13; SM-A536B)"
      },
      {
        "medias": [
          "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
          "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, PCML"
        ],
        "remote_addr": "udp4 host 10.10.1.138:36689",
        "send": 179284,
        "senders": [
          "102 H264, bytes=117687, receivers=1",
          "8 PCMA/8000, bytes=118752, receivers=1"
        ],
        "type": "WebRTC/WebSocket async passive consumer",
        "user_agent": "Mozilla/5.0 (Linux; Android 13; SM-A536B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Home Assistant/2024.6.1-12936 (Android 13; SM-A536B)"
      },
      {
        "medias": [
          "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
          "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, PCML",
          "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
        ],
        "receivers": [
          "111 OPUS/48000/2, bytes=14560, senders=0"
        ],
        "recv": 19520,
        "remote_addr": "udp4 host 10.10.1.138:38717",
        "send": 159896,
        "senders": [
          "102 H264, bytes=117687, receivers=1",
          "8 PCMA/8000, bytes=79872, receivers=1"
        ],
        "type": "WebRTC/WebSocket async passive consumer",
        "user_agent": "Mozilla/5.0 (Linux; Android 13; SM-A536B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Home Assistant/2024.6.1-12936 (Android 13; SM-A536B)"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H.264 High 5.1",
          "audio, recvonly, MPEG4-GENERIC/16000"
        ],
        "receivers": [
          "96 H264, bytes=117687, senders=3"
        ],
        "recv": 118951,
        "remote_addr": "10.10.1.80:554",
        "sdp": "v=0\r\no=- 1720310441071020 1 IN IP4 192.168.10.2\r\ns=Session streamed by \"preview\"\r\ni=Preview_01_sub\r\nt=0 0\r\na=tool:BC Streaming Media v2022.02.07\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:Preview_01_sub\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:500\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=framerate:25.000\r\na=control:trackID=1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:256\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=15;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408; profile=1;\r\na=framerate:25.000\r\na=control:trackID=2\r\n",
        "type": "RTSP active producer",
        "url": "rtsp://10.10.1.80/Preview_01_sub/",
        "user_agent": "go2rtc/1.8.4"
      },
      {
        "medias": [
          "audio, recvonly, L16/8000"
        ],
        "receivers": [
          "96 L16/8000, bytes=118752, senders=3"
        ],
        "recv": 120200,
        "remote_addr": "127.0.0.1:53888",
        "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=Session streamed by \"preview\"\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat 58.45.100\r\nm=audio 0 RTP/AVP 96\r\nb=AS:128\r\na=rtpmap:96 L16/8000/1\r\na=control:streamid=0\r\n",
        "type": "RTSP passive producer",
        "url": "rtsp://127.0.0.1:8554/1f05d5554402ca185b505e49e2ce6af4",
        "user_agent": "ffmpeg/go2rtc"
      }
    ]
  }
}
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 1

Error:
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink PoE video doorbell
