### DISCUSSION TITLE
[Support]: How to debug crashing ffmpeg

### DISCUSSION THREAD

**Discussion by marekk1717** [blakeblackshear/frigate#12334] [General Support]
### Describe the problem you are having

I'm trying to add rtsp streams from 2 types of cameras but according to log ffmpeg is crashing for both.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: False

go2rtc:
  streams:
    back:
      - rtsp://admin:*****@10.205.0.87:554/live/profile.0/video

logger:
  # Optional: default log level (default: shown below)
  default: debug

cameras:
  klatka:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://admin:*******@10.205.0.87:554/live/profile.0/video
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed

detectors: # required
  rknn: # required
    type: rknn # required
    # core mask for npu
    core_mask: 0

model: # required
  # name of yolov8 model or path to your own .rknn model file
  # possible values are:
  # - default-yolov8n
  # - default-yolov8s
  # - default-yolov8m
  # - default-yolov8l
  # - default-yolov8x
  # - /config/model_cache/rknn/your_custom_model.rknn
  path: default-yolov8n
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc
```

### Relevant log output

```shell
2024-07-08 10:11:07.807617190  [2024-07-08 10:11:07] frigate.video                  ERROR   : klatka: Unable to read frames from ffmpeg process.
2024-07-08 10:11:07.807779352  [2024-07-08 10:11:07] frigate.video                  ERROR   : klatka: ffmpeg process is not running. exiting capture thread...
2024-07-08 10:11:15.287386100  [2024-07-08 10:11:15] watchdog.klatka                ERROR   : Ffmpeg process crashed unexpectedly for klatka.
```

### FFprobe output from your camera

```shell
ffprobe version 7.0.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, rtsp, from 'rtsp://admin:$$$$$@10.205.0.87:554/live/profile.0/video':
  Metadata:
    title           : Session streamed by D-Link
    comment         : live/profile.0/video
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

RKNN

### Network connection

Wired

### Camera make and model

DLINK 6500
