### DISCUSSION TITLE
[Config Support]: Snapshots ignoring expire_interval setting?

### DISCUSSION THREAD

**Discussion by seansheep** [blakeblackshear/frigate#12330] [Config Support] [answered]
### Describe the problem you are having

I've got expire_interval set to 300 in config, however snapshot png and jpg files seem to be ignoring this setting, purging more frequently, and so spinning up otherwise idle disks.

### Version

0.14.0-beta3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.9

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  bounding_box: true
  crop: true
  height: 1000
  quality: 100




record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: motion
  expire_interval: 300



objects:
  filters:
    person:
      min_score: 0.7
      threshold: 0.75




##################################################################################   
# go2rtc streams
##################################################################################   

go2rtc:
  streams:
#****************************************************   
    doorbell:
      - rtsp://XXXXX@192.168.1.101/h264Preview_01_main
      - ffmpeg:doorbell#audio=opus#audio=copy#video=copy
    #doorbell_sub:
    #- rtsp://XXXXX@192.168.1.101/h264Preview_01_sub
    #- ffmpeg:doorbell_sub
#****************************************************   
    rear_porch:
      - rtsp://XXXXX@192.168.1.103/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:rear_porch#video=h264
    rear_porch_sub:
      - rtsp://XXXXX192.168.1.103/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:rear_porch_sub#video=h264
#****************************************************     
    rear_yard:
      - rtsp://XXXXX@192.168.1.105/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:rear_porch#video=h264
    rear_yard_sub:
      - rtsp://XXXXX@192.168.1.105/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:rear_porch_sub#video=h264
#****************************************************     
    front_yard:
      - rtsp://XXXXX@192.168.1.104/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:rear_porch#video=h264
    front_yard_sub:
      - rtsp://XXXXX@192.168.1.104/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:rear_porch_sub#video=h264
#****************************************************   




##################################################################################   
cameras:
##################################################################################
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      #- path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
      #  input_args: preset-rtsp-restream
      #  roles:
      #  - detect
    live:
      stream_name: doorbell
    motion:
      mask:
        - 2560,0,2560,92,1789,82,1785,0
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    zones:
      front_garden:
        coordinates: 0,1920,988,1920,1002,1696,1806,1542,1825,1255,782,1296,183,1231,0,1259
      front_door:
        coordinates: 1115,1351,1390,1341,2560,1920,949,1920
    objects:
      track:
        - person
        - motorcycle
        - cat
        - dog
    mqtt:
      crop: true
      bounding_box: false
      quality: 100
      height: 1000

##################################################################################

  rear_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_porch?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear_porch_sub?video=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    live:
      stream_name: rear_porch
    motion:
      mask:
        - 382,0,376,65,672,57,676,0
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask:
            - 704,246,704,315,623,315,627,248

    mqtt:
      crop: true
      bounding_box: false
      quality: 100
      height: 1000
##################################################################################
  rear_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_yard?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear_yard_sub?video=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    live:
      stream_name: rear_yard
    motion:
      mask: 0.541,0.03,0.535,0.093,0.979,0.095,0.979,0.034
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_area: 2000
        car:
          min_area: 6000
    mqtt:
      crop: true
      bounding_box: false
      quality: 100
      height: 1000
##################################################################################
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_sub?video=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    live:
      stream_name: front_yard
    motion:
      mask: 0.545,0,0.541,0.094,0.957,0.094,0.96,0
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
      filters:
        car:
          min_area: 3000
          mask: 0,0,0,0.297,0.994,0.17,0.996,0
        person:
          mask:
            - 704,0,704,98,0,170,0,0
    zones:
      top_driveway:
        coordinates: 0,0.773,0.339,0.749,0.312,0.533,0,0.601
        inertia: 3
    mqtt:
      crop: true
      bounding_box: false
      quality: 100
      height: 1000
##################################################################################



version: 0.14
camera_groups:
  Front_Cameras:
    order: 1
    icon: LuArrowBigUp
    cameras:
      - doorbell
      - front_yard
  Back_Cameras:
    order: 2
    icon: LuArrowBigDown
    cameras:
      - rear_porch
      - rear_yard
```

### Relevant log output

```shell
Unraid Logs:

** /mnt/user/cctv **
Jul 08 09:37:45 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531243.882051-de19lq.jpg
Jul 08 09:37:45 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531243.882051-de19lq-clean.png
Jul 08 09:37:45 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531300.888823-5pik9z.jpg
Jul 08 09:37:45 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531300.888823-5pik9z-clean.png
Jul 08 09:44:10 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531598.483538-9qmp7z.jpg
Jul 08 09:44:10 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531598.483538-9qmp7z-clean.png
Jul 08 09:44:10 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531653.514423-ovl47k.jpg
Jul 08 09:44:10 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531653.514423-ovl47k-clean.png
Jul 08 09:45:14 DELETE => /mnt/disk1/cctv/frigate/clips/front_yard-1719531848.918494-yhqxdp.jpg
Jul 08 09:45:14 DELETE => /mnt/disk1/cctv/frigate/clips/front_yard-1719531848.918494-yhqxdp-clean.png
Jul 08 09:50:36 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531836.073326-49quv1.jpg
Jul 08 09:50:36 DELETE => /mnt/disk1/cctv/frigate/clips/doorbell-1719531836.073326-49quv1-clean.png
```

### Frigate stats

```json
{"cameras":{"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":473,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":489,"pid":458,"process_fps":5.1,"skipped_fps":0.0},"front_yard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":500,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":514,"pid":466,"process_fps":5.0,"skipped_fps":0.0},"rear_porch":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":487,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":495,"pid":459,"process_fps":5.0,"skipped_fps":0.0},"rear_yard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":496,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":513,"pid":464,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"120":{"cmdline":"python3 -u -m frigate","cpu":"2.2","cpu_average":"2","mem":"2.3"},"127":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"132":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"165":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"166":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"167":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"168":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"170":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"302":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"343":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.8"},"410":{"cmdline":"frigate.recording_manager","cpu":"2.9","cpu_average":"2","mem":"1.1"},"412":{"cmdline":"frigate.review_segment_manager","cpu":"0.4","cpu_average":"0","mem":"0.8"},"438":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.3","cpu_average":"0","mem":"0.1"},"439":{"cmdline":"frigate.detector.coral","cpu":"0.2","cpu_average":"0","mem":"0.9"},"441":{"cmdline":"frigate.output       ","cpu":"1.5","cpu_average":"1","mem":"0.9"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"458":{"cmdline":"frigate.process:doorbell","cpu":"1.3","cpu_average":"1","mem":"1.0"},"459":{"cmdline":"frigate.process:rear_porch","cpu":"1.5","cpu_average":"1","mem":"1.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"464":{"cmdline":"frigate.process:rear_yard","cpu":"1.0","cpu_average":"1","mem":"1.0"},"466":{"cmdline":"frigate.process:front_yard","cpu":"1.4","cpu_average":"1","mem":"1.0"},"473":{"cmdline":"frigate.capture:doorbell","cpu":"4.8","cpu_average":"4","mem":"1.0"},"487":{"cmdline":"frigate.capture:rear_porch","cpu":"0.6","cpu_average":"0","mem":"0.9"},"489":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.9","cpu_average":"6","mem":"0.7"},"495":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear_porch_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=704:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.3"},"496":{"cmdline":"frigate.capture:rear_yard","cpu":"0.7","cpu_average":"0","mem":"0.9"},"500":{"cmdline":"frigate.capture:front_yard","cpu":"0.6","cpu_average":"0","mem":"0.9"},"508":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear_porch?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/rear_porch@%Y%m%d%H%M%S%z.mp4","cpu":"0.8","cpu_average":"0","mem":"0.2"},"513":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear_yard_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=704:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.3"},"514":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/front_yard_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=704:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.3"},"520":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear_yard?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/rear_yard@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.1"},"521":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/front_yard?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_yard@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.1"},"5266":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"5383":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"541":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"546":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"551":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"556":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"561":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"13.4","cpu_average":"13","mem":"0.2"},"frigate.full_system":{"cpu":"13.5","mem":"36.3"}},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.19,"pid":439}},"gpu_usages":{"intel-vaapi":{"gpu":"12.18%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":343},"recording":{"pid":410},"review_segment":{"pid":412}},"service":{"last_updated":1720396364,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":118.9,"mount_type":"tmpfs","total":130.0,"used":11.1},"/media/frigate/clips":{"free":6067344.2,"mount_type":"cifs","total":10011652.3,"used":3944308.1},"/media/frigate/recordings":{"free":6067344.2,"mount_type":"cifs","total":10011652.3,"used":3944308.1},"/tmp/cache":{"free":1224.0,"mount_type":"tmpfs","total":1239.8,"used":15.8}},"temperatures":{},"uptime":1606,"version":"0.14.0-4e5a6eb"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
