### DISCUSSION TITLE
Authentik Headers No Longer Function in Beta 3

### DISCUSSION THREAD

**Discussion by owenfiscus** [blakeblackshear/frigate#12349] [General Support]
### Describe the problem you are having

Frigate 0.14-beta3 appears to break authentication via Authentik headers. The following config does not use the username passed via the proxy to Frigate and defaults to the _Anonymous_ user.

``` yaml
auth:
  enabled: False
  trusted_proxies:
    - 10.10.2.1

proxy:
  header_map:
    user: X-authentik-username
```

I believe this bug may have been introduced by [this pull request](https://github.com/blakeblackshear/frigate/issues/11985).

### Steps to reproduce

Configure Frigate to disable auth and use a proxy with Authentik headers.

### Version

0.14-beta3

### Frigate config file

```yaml
See above.
```

### Relevant log output

```shell
None.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A
