### DISCUSSION TITLE
[Camera Support]: m3u8 camera stream issues

### DISCUSSION THREAD

**Discussion by garethiowc** [blakeblackshear/frigate#12347] [Camera Support] [answered]
### Describe the problem you are having

I'm trying to add a view-only camera from a m3u8 file, although the camera is on a public address i would rather keep it hidden so i've removed the IP from this post.  

http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8

When testing from VLC it streams fine so i'm sure it's just my config

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  host: 10.10.50.8
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: pass
go2rtc:
  streams:
    Driveway:
      - rtsp://admin:PASS@10.10.60.4:554/Streaming/Channels/101
      - ffmpeg:Driveway#audio=aac
    Front_Camera:
      - rtsp://admin:PASS@10.10.60.3:554/Streaming/Channels/101
      - ffmpeg:Front_Camera#audio=aac
    Needles_cam_1:
      - http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8
cameras:
  Needles_cam_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Needles_cam_1
          input_args: preset-rtsp-restream
    detect:
      enabled: false
    record:
      enabled: false      
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car
        - cat
      filters:
        car:
          mask:
            - 0.754,0.988,0.78,0.235,0.743,0.186,0.624,0.16,0.17,1
            - 0.802,0.195,0.72,0.11,0.74,0.08,0.797,0.059,0.841,0.075,0.875,0.077,0.9,0.08,0.89,0.131
    zones:
      My_Boundry:
        coordinates: 
          0.002,0.998,0.002,0,0.502,0.002,0.502,0.141,0.587,0.138,0.659,0.16,0.756,0.204,0.813,0.259,0.894,0.334,0.999,0.528,0.999,0.998
        inertia: 3
      Street:
        coordinates: 
          0.507,0,0.513,0.125,0.58,0.12,0.609,0.127,0.664,0.153,0.742,0.179,0.813,0.242,0.817,0.098,0.884,0.103,0.892,0
        objects:
          - car
          - person
    motion:
      mask:
        - 0.876,0.679,0.851,0.423,0.82,0.28,0.819,0.101,0.889,0.115,0.897,0,1,0,1,0.169,0.917,0.12,1,0.23,0.998,0.51,0.911,0.352
        - 0.002,0.225,0.001,0,0.506,0,0.5,0.04
        - 0.241,1,0.54,0.319,0.591,0.324,0.615,0.26,0.737,0.268,0.752,0.343,0.751,0.587,0.742,0.765,0.734,1
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    review:
      alerts:
        required_zones: My_Boundry
      detections:
        required_zones: Street
  Front_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car

      filters:
        car:
          mask:
            - 0.541,0.301,0.51,0.234,0.511,0.151,0.59,0,0.675,0,0.808,0,0.927,0,0.964,0,0.969,0.131,0.966,0.173,0.971,0.205,0.967,0.277,0.96,0.259,0.99,0.309,1,0.35,1,0.465,1,0.59,1,0.72,0.758,0.506,0.584,0.332
            - 0.361,0.03,0.396,0.028,0.425,0,0.526,0.054,0.561,0.109,0.512,0.193,0.399,0.201,0.331,0.202,0.27,0.165,0.291,0.032
            - 0,0.132,0.001,0.626,0.049,0.404,0.098,0.334,0.159,0.263,0.2,0.234,0.099,0.234,0.056,0.128
        person:
          mask:
            - 0.007,0.179,0.091,0.173,0.088,0.245,0.013,0.253
            - 0.592,0.076,0.635,0.078,0.641,0.142,0.589,0.138
    zones:
      Street:
        coordinates: 
          0.001,0.004,0.002,0.612,0.05,0.431,0.088,0.349,0.108,0.31,0.137,0.291,0.179,0.26,0.211,0.228,0.229,0.218,0.239,0.209,0.267,0.21,0.311,0.205,0.331,0.209,0.358,0.209,0.506,0.232,0.745,0.297,0.759,0.158,0.776,0.149,0.988,0.271,0.955,0.076,0.926,0.001
        inertia: 3
      My_Boundry:
        coordinates: 
          0.004,0.993,0.003,0.695,0.039,0.506,0.07,0.414,0.1,0.348,0.132,0.317,0.172,0.276,0.243,0.224,0.335,0.22,0.45,0.232,0.643,0.277,0.745,0.312,0.755,0.303,0.767,0.17,0.89,0.231,0.998,0.308,0.997,0.997
        inertia: 3
    motion:
      mask:
        - 0.416,0.979,0.511,0.69,0.57,0.604,0.685,0.501,0.71,0.436,0.768,0.445,0.777,0.396,0.821,0.402,0.84,0.422,0.863,0.406,0.905,0.429,0.913,0.513,0.916,0.571,0.889,0.64,0.845,0.737,0.765,0.891,0.713,0.977,0.692,1,0.452,1
        - 0.335,0.249,0.367,0.228,0.381,0.221,0.404,0.223,0.419,0.273,0.419,0.315,0.397,0.328,0.36,0.333,0.331,0.318
        - 0.997,0.001,0,0,0,0.097,0.037,0.095,0.095,0.097,0.178,0.095,0.256,0.094,0.303,0.094,0.339,0.073,0.412,0.074,0.395,0.096,0.392,0.136,0.436,0.141,0.45,0.119,0.492,0.127,0.503,0.15,0.535,0.156,0.571,0.114,0.711,0.146,0.746,0.162,0.749,0.229,0.797,0.3,0.855,0.332,0.97,0.347,0.997,0.353
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        required_zones: Street
      alerts:
        required_zones: My_Boundry
snapshots:
  enabled: true
  bounding_box: true
record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects
detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.14
camera_groups:
  Home:
    order: 1
    icon: LuHome
    cameras:
      - birdseye
      - Driveway
      - Front_Camera
```

### Relevant log output

```shell
Go2rtc 

Message
error="streams: mpegts: wrong sync byte" stream=Needles_cam_1

Frigate 

Error
2024-07-08 22:39:12
watchdog.Needles_cam_1
Ffmpeg process crashed unexpectedly for Needles_cam_1.
Error
2024-07-08 22:39:12
watchdog.Needles_cam_1
The following ffmpeg logs include the last 100 lines prior to exit.
Error
2024-07-08 22:39:12
ffmpeg.Needles_cam_1.detect
[rtsp @ 0x55aa49e19c40] method DESCRIBE failed: 404 Not Found
Error
2024-07-08 22:39:12
ffmpeg.Needles_cam_1.detect
rtsp://127.0.0.1:8554/Needles_cam_1: Server returned 404 Not Found
Error
2024-07-08 22:39:12
frigate.video
Needles_cam_1: Unable to read frames from ffmpeg process.
Error
2024-07-08 22:39:12
frigate.video
Needles_cam_1: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
# ffprobe http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[hls @ 0x55c960af5140] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55c960af5140] Opening 'http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07_var0.m3u8?session=niq8FxhsWCmgvnSEjYLJJ8' for reading
[hls @ 0x55c960af5140] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55c960af5140] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-07-08T21:28:16.199+0000')
[hls @ 0x55c960af5140] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-07-08T21:28:18.715+0000')
[hls @ 0x55c960af5140] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-07-08T21:28:21.191+0000')
[hls @ 0x55c960af5140] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-07-08T21:28:23.706+0000')
[hls @ 0x55c960af5140] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-07-08T21:28:26.182+0000')
[hls @ 0x55c960af5140] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-07-08T21:28:28.698+0000')
[hls @ 0x55c960af5140] Opening 'http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07_16303_var0.ts?session=niq8FxhsWCmgvnSEjYLJJ8' for reading
[hls @ 0x55c960af5140] Opening 'http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07_16304_var0.ts?session=niq8FxhsWCmgvnSEjYLJJ8' for reading
Input #0, hls, from 'http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8':
  Duration: N/A, start: 40690.870222, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 70400
  Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709), 1920x1080, 20 fps, 25 tbr, 90k tbn
    Metadata:
      variant_bitrate : 70400
  Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 70400
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision

**Comment by hawkeye217** [comment]
Would be good to see go2rtc trace logs, but first, try your go2rtc url with `ffmpeg`:

`- ffmpeg:http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8`

**Reply by garethiowc** [reply]
Thanks for the suggestion but it didn't work. 

```
    Needles_cam_1:
      - ffmpeg:http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8
cameras:
  Needles_cam_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Needles_cam_1
          input_args: preset-rtsp-restream
```


I'm hoping the following additional options give us the logs required
```
go2rtc:
  log:
    format: text
    level: "debug"

```

go2rtc log output 

```
Info
2024-07-09 07:31:03
rtsp
new consumer stream=Needles_cam_1
Info
2024-07-09 07:31:03
exec
run cmd="ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9e2b0769e83ccb751db2e28cd15fca40" url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://IP.AA.DD.RR:8080/memfs/25dc2a71-1baf-4a6b-bf35-3c279d9faa07.m3u8 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9e2b0769e83ccb751db2e28cd15fca40"
Info
2024-07-09 07:31:04
startup
AAC with no global headers is currently not supported.
Info
2024-07-09 07:31:04
startup
2024-07-09 07:31:04.098713198 Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Info
2024-07-09 07:31:04
startup
2024-07-09 07:31:04.098715553 Error initializing output stream 0:1 --
Info
2024-07-09 07:31:04
startup
2024-07-09 07:31:04.098717508
Warning
2024-07-09 07:31:04
rtsp
error="streams: exec: [rtsp @ 0x7fff0d23be70] AAC with no global headers is currently not supported.\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input\nError initializing output stream 0:1 -- \n\n" stream=Needles_cam_1
```
