### DISCUSSION TITLE
[Config Support]: Zone object: car error

### DISCUSSION THREAD

**Discussion by dkduck** [blakeblackshear/frigate#12355] [Config Support] [answered]
### Describe the problem you are having

When adding a zone to a camera with the object **_car_**, Frigate fails
If using object **_person_** everything works like a charm

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx.xxx.xxx.xxx
  port: 1883
  user: xxxx
  password: xxxx
  topic_prefix: frigate

database:
  path: /config/frigate.db

rtmp:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-udp

detectors:
  coral:
    type: edgetpu
    device: usb

#----------------------------------------------------------------------------------------
cameras:
  01-Driveway:
    detect:
      width: 1280
      height: 720
      fps: 5

    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 2

    zones:
      zone_cars_on_street:
        coordinates: 879,0,887,157,352,163,352,0
        objects:
          - car



    ffmpeg:
      inputs:
      - path: rtsp://xxxx:xxxx@xxx.xxx.xxx.xxx/h265Preview_01_main
        roles:
        - detect
        - record

#----------------------------------------------------------------------------------------
detect:
  stationary:
    interval: 50
    threshold: 50
```

### Relevant log output

```shell
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/http.py&#34;, line 1235, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1351, in parse_raw
    return cls.parse_obj(config)
  File &#34;pydantic/main.py&#34;, line 526, in pydantic.main.BaseModel.parse_obj
  File &#34;pydantic/main.py&#34;, line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -&gt; 01-Driveway
  &#39;list&#39; object is not a mapping (type=type_error)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral
