### DISCUSSION TITLE
Unable to upgrade to 0.13.2

### DISCUSSION THREAD

**Discussion by ronrath** [blakeblackshear/frigate#12351] [General Support]
### Describe the problem you are having

When I click on "update" in Home Assistant I get the following message:

Can't install ghcr.io/blakeblackshear/frigate:0.13.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/blakeblackshear/frigate:0.13.2/json: Not Found ("No such image: ghcr.io/blakeblackshear/frigate:0.13.2")

The system is also failing to start and when I click on the log I get:

Failed to get add-on logs, No systemd-journal-gatewayd Unix socket available

### Steps to reproduce

Go to Settings->Add Ons->Update

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.112
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user:
  password: 
  stats_interval: 60

database:
  path: /media/frigate/clips/frigate.db
  
detectors:
  coral:
    type: edgetpu
    device: usb
      
cameras:
  garage:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://uname:pwd@IP/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://uname:pwd@IP/live
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.6
    motion:
      mask:
        - 700,0,700,46,515,46,515,0
        - 704,480,704,457,446,313,269,480
        - 704,192,641,140,512,123,500,202,704,354
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 5
        
  basement:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac      
      inputs:
        - path: rtsp://uname:pwd@IP/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://uname:pwd@IP/live
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.6
    motion:
      mask:
        - 700,0,700,46,515,46,515,0
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 5
        
  backyard:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://uname:pwd@IP/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://uname:pwd@IP/live
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.6
    motion:
      mask:
        - 700,0,700,46,515,46,515,0
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 5

  front:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://uname:pwd@IP/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://uname:pwd@IP/live
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.6
    motion:
      mask:
        - 700,0,700,46,515,46,515,0
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 5
        
  front-door:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://uname:pwd@IP/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://uname:pwd@IP/live
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.6
    motion:
      mask:
        - 700,0,700,46,515,46,515,0
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 5
                
birdseye:
  enabled: True
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 3
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
```

### Relevant log output

```shell
The system is also failing to start and when I click on the log I get:

Failed to get add-on logs, No systemd-journal-gatewayd Unix socket available
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

amcrest

### Any other information that may be helpful

Running on a Pi4. Everything was working and had been for over a year until a couple of days ago. I believe an update to Home Assistant Core broke the Frigate functionality but not sure.
