### DISCUSSION TITLE
[Support]: Recording Disabled but still showing low resolution frames for all the time

### DISCUSSION THREAD

**Discussion by greedily8276** [blakeblackshear/frigate#12366] [General Support] [answered]
### Describe the problem you are having

Hi, i enable recording from home assistant when arming alarm and disable recording when disarming alarm. everything works fine for this, but with recording disabled I can scrub the timeline, it say "no recording found for this time"  but I can still see a low res images dragging the cursor of the timeline. Each frames are approximatively distant 3/4 seconds.

The same in beta1, beta2 and beta3

### Version

0.14 beta3

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.4
  user: xxxxx
  password: xxxxx

detectors:
  ov:
    type: openvino
    device: CPU

model:
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    frsalotto:
      - ffmpeg:http://192.168.5.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxxx!#video=copy#audio=copy#audio=opus

    frsalotto_sub:
      - ffmpeg:http://192.168.5.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxxx
  webrtc:
    candidates:
      - 192.168.5.5:8555
      - stun:8555
record:
  events:
    pre_capture: 20
    post_capture: 20

cameras:
  frsalotto:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frsalotto
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frsalotto_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.5.10
      port: 8000
      user: xxxxx
      password: xxxxx
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - cat
    motion:
      mask: 0.722,0,0.712,0.068,0.281,0.07,0.281,0.019
      threshold: 15
      contour_area: 10
      improve_contrast: 'true'
    zones:
      zone_blindata:
        coordinates: 0.71,0.073,0.669,0.439,0.504,0.443,0.508,0.058
        inertia: 3
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
    review: {}
version: 0.14
```

### Relevant log output

```shell
no relevant log
```

### FFprobe output from your camera

```shell
no ffprobe output relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink E1 Zoom
