### DISCUSSION TITLE
[Config Support]: ffprobe says H.265 but setting ffmpeg codec doesn't work - beginner

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#12376] [Config Support]
### Describe the problem you are having

Hello all

My graphics card can h/w decode H.265 which is what my cameras are sending, but it doesn't work when I set what I think is the right codec argument. Can anyone help explain things to me using crayons and children's toys so I might grasp some of it please? I am very much out of my depth.

detail:
I am running frigate in a TrueNAS app (some form of docker container) and I have added four cameras which I know to be H.265 output. All four are working with jsmpeg and I am detecting and classifying with a degree of success. However, I want to use go2rtc and MSE so that I can variously improve video quality, or play the video clips directly in my browser rather than downloading them to play in mplayer or ffplay etc. 

(I'm using a linux desktop OS, using Chromium amongst other browsers, none of which support the right type of video and the window says, for reasons I have read about,  "the media playback was aborted due to a corruption problem or because the media used features your browser did not support").

If I do "ffprobe" from Frigate's UI for any of these four cameras I am told 
FPROBE OUTPUT
Stream 0:
Return Code: 0
Video: Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 640x360
FPS: Unknown
Audio: Codec: PCM mu-law / G.711 mu-law

Stream 1: Return Code: 0
Video: Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 1920x1080
FPS: Unknown
Audio:Codec: PCM mu-law / G.711 mu-law

I am using an Nvidia GT 1030 GPU and nvidia-smi tells me it sees four ffmpegs running which seems sensible. 

I can also see that "ffmpeg -decoders | grep cuvid" tells me (snipped for pertinence and clarity):

V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)

So I thought I could add *one* of these arguments to my Frigate config:
https://docs.frigate.video/configuration/hardware_acceleration/

ffmpeg:
  hwaccel_args: preset-nvidia-h264
yes - this works and all cameras see streams and detect on them, but I can't render in the Frigate video clip window

ffmpeg:
  hwaccel_args: preset-nvidia-hevc 
NO this gives black screens on cameras ... no video stream

Perhaps my  nomenclature is wrong, because the worked example only shows preset-nvidia-h264, so let's try another approach (because it isn't clear to me how to translate the above into a config line):

ffmpeg:
  #hwaccel_args: preset-nvidia-cuvid 
NO - this also gives black screens on cameras

I am now struggling to write a config which can use my graphics card to transcode H265 into H264 so that I can play it in my browser, or give better quality streaming to other items.   My goal is to connect Frigate to my cameras and then restream to Motioneye for onwards consumption to various tablets/machines on my network, thus establishing just one rtsp connection to the cameras.

Can anyone help please explain where I am going wrong?  This might be a tall order because as you can see I am not very familiar with video streaming (yet)!

Thanks

EB

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  enabled: false

#go2rtc:
#  streams:
#    greenhouse:
#    - rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0 
#    upper_patio:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0
#    ponds:
#    - rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0
#    blue_gate:
#    - rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0
#    lower_steps:
#    - rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0
#    lower_patio:
#    - rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0
#    shed:
#    - rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0
#    kitchen_steps:
#    - rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0
   
#    webrtc:
#    candidates:
#    - 192.168.1.194:8555
#    - stun:8555

ffmpeg:
  #####you can only have one line here#####
  hwaccel_args: preset-nvidia-h264
  #hwaccel_args: preset-nvidia-hevc #gives black screens on cameras
  #hwaccel_args: preset-nvidia-cuvid #gives black screens on cameras
  
detectors:
  coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

birdseye:
  enabled: true
  mode: continuous #continuous | objects | motion

# record: # <----- Enable recording # was working
#  enabled: true # was working

# added from https://fixtse.com/blog/coral-ia-frigate start#
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
# added from https://fixtse.com/blog/coral-ia-frigate #

  
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 768
  #height: 800
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 7
      cat: 7
      dog: 7
      bird: 7
      fox: 7
      badger: 7
      car: 7
      licence_plate: 7

  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

##########################################################
##########################################################
# go2rtc: # this worked from https://docs.frigate.video/configuration/live/#setting-stream-for-live-ui
#  streams:
#    upper_patio:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 # <- stream which supports video & aac audio.
#    - "ffmpeg:upper_patio#audio=opus" # <- copy of the stream which transcodes audio to opus for webrtc
#    restream: true        
#    upper_patio_sub:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 # <- stream which supports video & aac audio.
#    - "ffmpeg:upper_patio_sub#audio=opus"
##########################################################
##########################################################

motion:
  improve_contrast: True




##########################################################
##########################################################
##########################################################
##########################################################
##########################################################


cameras: #########UPPER_PATIO#############################
  upper_patio:
    enabled: true
    ffmpeg:
      inputs:

      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
      #- path: http://truenas.local:8082/media=0/channel=1&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
      #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #input_args: preset-rtsp-restream

        roles:
        - detect

      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 1

    motion:
      mask: 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      upper patio:
        coordinates: 640,360,640,337,610,312,603,297,594,279,564,256,524,255,510,242,487,220,451,203,435,201,421,187,409,166,392,152,334,146,274,138,215,142,122,145,78,162,23,202,0,360


  blue_gate: #########BLUE_GATE#############################
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #  input_args: preset-rtsp-restream

        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placehlder
      - badger # placeholder
      - car
      - licence_plate

    birdseye:
      mode: continuous   #continuous | objects | motion
      # masks are black: they block out areas where you aren't interested in detecting things
      order: 2

    motion:
      mask:
      - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
      - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360

    zones:
      gravel:
        coordinates: 411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233

  drive: #########DRIVE#############################
    enabled: true

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
      - car
      - licence_plate

    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; changing track0 to track1 didn't work)
      #input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;(changing track0 to track1 didn't work)
        roles:
        - record

    birdseye:
      mode: continuous #continuous | objects | motion
      #restream: True
      order: 4

    motion:
      # masks are black: they block out areas where you aren't interested in detecting things
      mask:
      - 98,129,170,113,189,0,0,0,0,0,0,142
      - 273,0,170,0,178,67,258,117,256,191,414,181,640,307,640,0

    # zones are red: they select areas where monitoring of activity is wanted
    zones:
      driveway:
        coordinates: 78,360,248,360,381,360,640,360,640,276,449,177,303,183,298,129,200,64,144,113,0,127,0,360


  lower_patio: #########LOWER_PATIO#############################
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox   #placeholder
      - badger   #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 3

      # masks are black: they block out areas where you aren't interested in detecting things
    motion:
      mask:
      - 0,148,92,104,184,55,253,0,269,154,272,305,318,125,354,107,345,56,406,60,417,131,504,240,570,360,640,360,640,0,0,0
        #- 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      lower patio:
        coordinates: 284,360,303,183,333,157,344,139,357,118,352,99,359,74,382,73,384,110,403,128,499,246,580,360

#-----------------------END-----------------------#
```

### Relevant log output

```shell
024-07-10 11:33:17.314305018  [INFO] Starting go2rtc healthcheck service...
2024-07-10 11:43:11.084347673  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-07-10 11:43:14.433545794  exit with signal: terminated
2024-07-10 11:43:14.439080612  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024-07-10 11:43:25.656324999  [INFO] Removing stale config from last run...
2024-07-10 11:43:25.657357158  [INFO] Preparing new go2rtc config...
2024-07-10 11:43:26.165535134  [INFO] Starting go2rtc...
2024-07-10 11:43:26.259466866  11:43:26.259 INF go2rtc version 1.8.4 linux/amd64
2024-07-10 11:43:26.259952761  11:43:26.259 INF [api] listen addr=:1984
2024-07-10 11:43:26.260164276  11:43:26.260 INF [rtsp] listen addr=:8554
2024-07-10 11:43:26.260396998  11:43:26.260 INF [webrtc] listen addr=:8555
2024-07-10 11:43:35.655133367  [INFO] Starting go2rtc healthcheck service...
2024-07-10 11:45:53.745004257  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-07-10 11:45:57.571329655  exit with signal: terminated
2024-07-10 11:45:57.576137108  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024-07-10 11:46:14.259611200  [INFO] Removing stale config from last run...
2024-07-10 11:46:14.262024006  [INFO] Preparing new go2rtc config...
2024-07-10 11:46:14.771700953  [INFO] Starting go2rtc...
2024-07-10 11:46:14.910330573  11:46:14.909 INF go2rtc version 1.8.4 linux/amd64
2024-07-10 11:46:14.911102897  11:46:14.911 INF [api] listen addr=:1984
2024-07-10 11:46:14.911131728  11:46:14.911 INF [rtsp] listen addr=:8554
2024-07-10 11:46:14.911430262  11:46:14.911 INF [webrtc] listen addr=:8555
2024-07-10 11:46:24.264110073  [INFO] Starting go2rtc healthcheck service...
2024-07-10 13:02:20.907060909  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-07-10 13:02:24.349067811  exit with signal: terminated
2024-07-10 13:02:24.355440424  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024-07-10 13:02:37.001278229  [INFO] Removing stale config from last run...
2024-07-10 13:02:37.002726782  [INFO] Preparing new go2rtc config...
2024-07-10 13:02:37.578367556  [INFO] Starting go2rtc...
2024-07-10 13:02:37.665316797  13:02:37.665 INF go2rtc version 1.8.4 linux/amd64
2024-07-10 13:02:37.665916145  13:02:37.665 INF [api] listen addr=:1984
2024-07-10 13:02:37.665941342  13:02:37.665 INF [rtsp] listen addr=:8554
2024-07-10 13:02:37.666175714  13:02:37.666 INF [webrtc] listen addr=:8555
2024-07-10 13:02:46.997582992  [INFO] Starting go2rtc healthcheck service...
2024-07-10 13:05:17.211335662  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-07-10 13:05:21.610478241  exit with signal: terminated
2024-07-10 13:05:21.616039124  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024-07-10 13:05:49.329997847  [INFO] Removing stale config from last run...
2024-07-10 13:05:49.331693544  [INFO] Preparing new go2rtc config...
2024-07-10 13:05:49.871908370  [INFO] Starting go2rtc...
2024-07-10 13:05:49.970415474  13:05:49.970 INF go2rtc version 1.8.4 linux/amd64
2024-07-10 13:05:49.970996242  13:05:49.970 INF [api] listen addr=:1984
2024-07-10 13:05:49.971188668  13:05:49.971 INF [rtsp] listen addr=:8554
2024-07-10 13:05:49.971434293  13:05:49.971 INF [webrtc] listen addr=:8555
2024-07-10 13:05:59.324080275  [INFO] Starting go2rtc healthcheck service...
2024-07-10 13:07:39.872906971  13:07:39.872 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.16.0.16:54948->192.168.1.123:554: i/o timeout" url=rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0
2024-07-10 13:12:31.913995773  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-07-10 13:12:38.566330816  exit with signal: terminated
2024-07-10 13:12:38.573746573  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024-07-10 13:13:08.153256030  [INFO] Removing stale config from last run...
2024-07-10 13:13:08.155034932  [INFO] Preparing new go2rtc config...
2024-07-10 13:13:08.713822867  [INFO] Starting go2rtc...
2024-07-10 13:13:08.802515639  13:13:08.802 INF go2rtc version 1.8.4 linux/amd64
2024-07-10 13:13:08.803093842  13:13:08.803 INF [rtsp] listen addr=:8554
2024-07-10 13:13:08.803097791  13:13:08.803 INF [api] listen addr=:1984
2024-07-10 13:13:08.803331317  13:13:08.803 INF [webrtc] listen addr=:8555
2024-07-10 13:13:18.146931931  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

TrueNAS Dragonfish-24.04.2 running TrueNAS'  (not Truecharts) Frigate app. I don't have the ability to upgrade to 0.14 until the app gets upgraded
