### DISCUSSION TITLE
[Support]:

### DISCUSSION THREAD

**Discussion by ryosoftware** [blakeblackshear/frigate#12378] [General Support]
### Describe the problem you are having

I have a automation script at my HA install that sends the clip via Telegram when a detection finishes.
It's working fine from months, but recently it fails sometimes due to the event HA receives do not includes a clip (has_clip = false)
Why this occurs? 

### Version

0.14.0 beta 3

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: true
  host: localhost
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects

motion:
  improve_contrast: true

detect:
  enabled: false
  width: 1920
  height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://XXXXXXXXXXXXXXXXXXXXXXXXXX

objects:
  track:
    - person
    - dog
    - cat
  filters:
    person:
#      min_area: 25000
      min_score: .8
      threshold: .85

go2rtc:
  streams:
    terraza_trasera:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.231/stream1
    dormitorio_principal:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.235/stream1
    recibidor:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.233/stream1
    comedor:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.234/stream1
    terraza_delantera:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.232/stream1
cameras:
  terraza_trasera:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_trasera
          roles:
            - record
            - detect

  dormitorio_principal:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dormitorio_principal
          roles:
            - record
            - detect

  recibidor:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/recibidor
          roles:
            - record
            - detect

  comedor:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/comedor
          roles:
            - record
            - detect

  terraza_delantera:
    enabled: true
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_delantera
          roles:
            - record
            - detect
    objects:
      filters:
        person:
          mask:
            - 1920,0,1920,252,1654,250,1653,0     # Foco
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Tapo C100, Tapo C320W

### Any other information that may be helpful

HA Automation

alias: Notificar con vídeo al acabar de detectar una persona en una cámara
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    alias: Is a end event?
    value_template: "{{ event_type == 'end' }}"
  - condition: template
    alias: Is a person related event?
    value_template: "{{ object_type == 'person' }}"
  - condition: template
    alias: Is a camera event?
    value_template: "{{ camera is defined }}"
action:
  - delay:
      seconds: 7
  - service: notify.telegram_alarma
    data:
      message: Vídeo {{ camera_name }}
      data:
        parse_mode: html
        video:
          - url: "{{ base_location }}/{{ id }}/clip.mp4"
            caption: Vídeo {{ camera_name }}
variables:
  base_location: https://127.0.0.1:5000/api/events
  id: "{{ trigger.payload_json['after']['id'] }}"
  event_type: "{{ trigger.payload_json['type'] }}"
  object_type: "{{ trigger.payload_json['after']['label'] }}"
  camera: "{{ trigger.payload_json['after']['camera'] }}"
  camera_name: "{{ camera | replace('_', ' ') }}"
  start_time: "{{ trigger.payload_json['after']['start_time'] }}"
mode: single
