### DISCUSSION TITLE
[Config Support]: Connection refused... database is locked

### DISCUSSION THREAD

**Discussion by DaveTSG** [blakeblackshear/frigate#12371] [Config Support] [answered]
### Describe the problem you are having

I'm trying to load Frigate for the first time on a new Debian system (running on an old Apple Mac Mini (8,1) from 2018). I previously had it running on a different machine, so I've already got a lot of the config set up. I made some adjustments to suit the different computer (enabling hardware acceleration and a password).

Frigate fails to start up. The log file mentions 127.0.0.1:5001, which is interesting, because I don't have port 5001 specified in the docker-compose.yml file. It also says that a database is locked, but I have no idea what that's referring to.

Thank you in advance.

### Version

Don't know, but I specified the stable container. Update, after I got it working: it was v0.13.2-6476F8A.

### Frigate config file

```yaml
mqtt:
  host: 192.168.3.22
  enabled: True
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: MQTT4HA
  password: redacted
  stats_interval: 30
  
# Uncomment the following when Google Coral USB TPU has been plugged into the system...:
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  
go2rtc:
  streams:
    FrontDoor:
      - rtspx://192.168.1.1:7441/HZ6BuVp4F3iWXAwl
      - "ffmpeg:FrontDoor#audio=opus"
    PackageCam:
      - rtsps://192.168.1.1:7441/7EBFyiGKgiRhf0jU
      - "ffmpeg:PackageCam#audio=opus"
    GarageCam:
      - rtsps://192.168.1.1:7441/fLIVSyOaCypG4V7R
      - "ffmpeg:GarageCam#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.110:6955
      - stun:6955

cameras:
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/HZ6BuVp4F3iWXAwl?enableSrtp?video&audio
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/NhxjoXQg5OVd0KiN?enableSrtp?video&audio
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
        # record: preset-record-generic-audio-aac
    detect:
      enabled: True #Change this to true when Coral USB TPU is plugged in.
      width: 960
      height: 720
    motion:
      mask:
        - 244,268,276,274,311,277,309,318,315,358,302,378,295,413,289,439,283,452,278,439,253,389,208,369,188,298,204,277
        - 0,326,65,336,100,343,105,359,123,393,134,430,141,453,135,499,113,533,92,550,54,578,0,582
        - 235,526,257,521,289,528,297,538,301,559,305,592,300,623,283,635,256,644,246,634,229,619,209,596,208,572,230,549
        - 356,455,383,480,399,484,409,477,417,459,421,437,419,416,409,407,390,406,364,417,346,430
        - 485,457,511,466,529,433,518,409,492,403,466,433
        - 724,620,751,609,759,434,764,401,774,350,728,335,693,333,672,337,637,383,637,405,642,423,635,468,609,490,611,539
        - 0,0,960,0,960,165,750,241,682,263,616,295,524,292,381,314,310,321,195,319,141,321,0,307
  PackageCam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/7EBFyiGKgiRhf0jU?enableSrtp?video&audio
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True #Change this to true when Coral USB TPU is plugged in.
      width: 1600
      height: 1200
    motion:
      mask:
        - 572,870,561,919,536,967,487,988,473,1028,492,1085,466,1170,457,1200,423,1200,380,1200,298,1200,218,1200,161,1200,114,1200,64,1200,0,1200,0,1124,0,802,51,802,114,800,185,807,222,812,235,811,270,805,310,755,332,737,384,714,427,705,445,701,434,629,447,563,475,520,516,480,510,423,546,402,582,395,613,417,617,466,621,499,686,507,710,521,693,547,611,580,576,597,538,584,510,608,504,643,504,675,541,724,571,769,581,816
        - 166,180,185,158,215,155,256,165,278,175,295,193,309,209,338,222,363,247,370,271,379,304,362,328,332,354,311,367,264,378,210,378,187,374,166,361,155,361,130,340,117,318,118,292,125,261,131,222,143,200
        - 1600,0,1600,169,1516,309,1506,331,1513,356,1480,387,1435,404,1399,370,1362,324,1296,270,1259,253,1218,218,1188,183,1180,145,1188,124,1208,87,1203,42,1223,24,1243,0
        - 1600,1200,1600,867,1600,718,1574,752,1506,785,1423,814,1260,883,1140,936,1063,956,998,990,862,999,321,1200
  GarageCam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/fLIVSyOaCypG4V7R?enableSrtp?video&audio
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/hR3g7Ce9h8UqzBLo?enableSrtp?video&audio
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True #Change this to true when Coral USB TPU is plugged in.
      width: 1280
      height: 1280


birdseye:
  enabled: True
  # width: 1280
  # height: 720
  mode: continuous
  # layout:
  #   scaling_factor: 4

record:
    enabled: True
    # expire_interval: 60
    # retain:
    #     days: 0
    events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 60
          mode: active_objects
        objects:
          - person
          - car
          - dog
          - cat
          - bird
        # retain:
        #     default: 90
        #     objects:
        #      person: 90
        #      dog: 15

snapshots:
    enabled: True
    clean_copy: True
    timestamp: True
    bounding_box: True
    retain:
        default: 90

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
```

### Relevant log output

```shell
2024-07-10T05:39:54.229103317Z 2024-07-10 15:39:54.229036098  [INFO] Starting Frigate...
2024-07-10T05:39:54.394509441Z 2024-07-10 15:39:54.394402371  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-07-10T05:39:54.417213712Z 2024-07-10 15:39:54.417148332  [INFO] Starting go2rtc...
2024-07-10T05:39:54.505089155Z 2024-07-10 15:39:54.505010182  15:39:54.504 INF go2rtc version 1.8.4 linux/amd64
2024-07-10T05:39:54.505393863Z 2024-07-10 15:39:54.505366678  15:39:54.505 INF [rtsp] listen addr=:8554
2024-07-10T05:39:54.505637429Z 2024-07-10 15:39:54.505607243  15:39:54.505 INF [webrtc] listen addr=:8555
2024-07-10T05:39:54.505962041Z 2024-07-10 15:39:54.505930466  15:39:54.505 INF [api] listen addr=:1984
2024-07-10T05:39:55.153298894Z 2024-07-10 15:39:55.153156426  [2024-07-10 15:39:55] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-10T05:39:55.199220394Z 2024-07-10 15:39:55.199007625  [2024-07-10 15:39:55] peewee_migrate.logs            INFO    : Starting migrations
**2024-07-10T05:39:59.059373388Z 2024-07-10 15:39:59.059329609  2024/07/10 15:39:59 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
2024-07-10T05:40:00.210497178Z 2024-07-10 15:40:00.210305992  database is locked**
2024-07-10T05:40:01.354329049Z 2024-07-10 15:40:01.354195735  [INFO] Service Frigate exited with code 1 (by signal 0)
2024-07-10T05:40:01.356143662Z s6-rc: info: service legacy-services: stopping
2024-07-10T05:40:01.357895397Z s6-rc: info: service legacy-services successfully stopped
2024-07-10T05:40:01.358088688Z s6-rc: info: service nginx: stopping
...(Many other lines showing Frigate continuing to stop)
```

### Frigate stats

```json
(I don't know how to access this)
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

Contents of Docker compose file:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Enables Google Coral EdgeAI USB TPU
      - /dev/dri/renderD128:/dev/dri/renderD128 # Intel-based iGPU hardware acceleration.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "redacted"
```

**Comment by DaveTSG** [comment, marked as answer]
I have figured out the problem and the solution.

I wanted to have all of my Docker files in an SMB network folder (from my NAS) so that everything was backed-up. However, as per [this documentation](https://docs.frigate.video/configuration/advanced/#database), doing so results in the "database is locked" error.

I added a line in the volumes section of docker-compose.yml to specify the config directory of Frigate should be saved into a separate part of the actual computer, i.e. 

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/dockerfilesNotOnNAS/frigate-config:/config
      - ./storage:/media/frigate
```

That solved the problem.
