### DISCUSSION TITLE
Url for direct access to specific date time in recording in 0.14

### DISCUSSION THREAD

**Discussion by gonzalezcalleja** [blakeblackshear/frigate#12383] [General]
Hi,

I have been using in 0.13 version a custom action in home assistant notification with a URL for view specific recording, like this:

```yaml
  - service: notify.redacted
    data:
      title: "Persona en Planta Primera"
      data:
        actions:
          - action: "URI"
            title: "Ver grabación"
            uri: "{{ 'http://192.168.1.1:5000/recording/plantaprimera/' + as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%Y-%m-%d/%H/%M/00') }}"
```

Can I use a similar url in 0.14 for direct access to specific date time recording? 
Thanks!
