### DISCUSSION TITLE
[Support]: Person being in constant detection where there isn't one

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#12396] [General Support] [answered]
### Describe the problem you are having

On one of my cameras it is showing that a person is constantly detected, but I can't seem to tell from Debug where it thinks it is seeing a person, and don't know what to do about it.

### Version

0.14.0-4e5a6eb

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.102
  user: mqtt-client
  password: PaSSw0rD

detectors:
  coral_usb:
    type: edgetpu
    device: usb
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    frontyard_a:
      - rtsp://admin:PaSSw0rD@192.168.1.67:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_b#audio=opus
    frontyard_a_sub:
      - rtsp://admin:PaSSw0rD@192.168.1.67:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_b:
      - rtsp://admin:PaSSw0rD@192.168.1.64:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_b#audio=opus
    backyard_b_sub:
      - rtsp://admin:PaSSw0rD@192.168.1.64:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_c:
      - rtsp://admin:PaSSw0rD@192.168.1.65:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_c#audio=opus
    backyard_c_sub:
      - rtsp://admin:PaSSw0rD@192.168.1.65:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_d:
      - rtsp://admin:PaSSw0rD@192.168.1.68:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_c#audio=opus
    backyard_d_sub:
      - rtsp://admin:PaSSw0rD@192.168.1.68:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    front_doorbell:
      - ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=qXPf3pAz#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.30/Preview_01_sub
    front_doorbell_sub:
      - ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=qXPf3pAz

cameras:
  frontyard_a:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard_a
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_a_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontyard_a?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.336,0.004,0.213,0.057,0.249,0.33,0.167,0.381,0.209,0.476,0.481,0.483,0.538,0.413,0.587,0.164,0.519,0
        - 0.624,0.094,0.572,0.222,0.746,0.285,1,0.38,1,0.144
        - 0.806,0.475,0.894,0.466,0.991,0.525,1,1,0.962,1,0.933,0.865,0.952,0.812,0.747,0.557,0.71,0.499
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Zone_1:
        coordinates: 0.983,0.502,0.248,0.233,0.017,0.345,0.323,0.98,0.979,0.99
    review:
      alerts:
        required_zones: Zone_1
      detections:
        required_zones: Zone_1
  backyard_b:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_b
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_b_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_b?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.002,0.44,0.301,0.293,0.295,0.468,0.349,0.588,0.381,0.54,0.649,0.54,0.702,0.702,0.756,0.709,0.845,0.567,0.828,0.263,0.772,0.26,0.742,0.328,0.643,0.3,0.47,0.316,0.398,0.34,0.355,0.149,0.411,0,0.002,0
        - 0.793,0.118,0.37,0.146,0.389,0.339,0.792,0.308
    zones:
      Frisbee_Golf:
        coordinates: 0.055,0,0.044,0.297,0.309,0.228,0.768,0.172,0.821,0
      Backyard:
        coordinates: 1,0.16,0,0.416,0.016,1,1,1,1,0.696
  backyard_c:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_c
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_c_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_c?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
  backyard_d:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_d
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_d_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_d?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    motion:
      mask: 0.303,0.649,0.464,0.625,0.509,0.719,0.425,0.765,0.34,0.767
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.705,0.137,0.544,0.378,0.542,0.548,0.885,0.722,1,0.58,1,0.311,0.916,0
        - 0.539,0.458,0.544,0.496,0.368,0.49,0.374,0.455
        - 0.517,0.629,0.426,0.708,0.459,0.989,0.598,0.993
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      zone_0:
        coordinates: 43,672,338,388,337,224,457,254,464,395,535,672
version: 0.14

detect:
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - bird
    - car
    - cat
    - dog
    - package
    - person
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

### Frigate stats

```json
{
    "cameras": {
        "backyard_b": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 0,
            "capture_pid": 657,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 14121,
            "pid": 622,
            "process_fps": 0,
            "skipped_fps": 0
        },
        "backyard_c": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 661,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 668,
            "pid": 626,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "backyard_d": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 669,
            "detection_enabled": true,
            "detection_fps": 3.7,
            "ffmpeg_pid": 685,
            "pid": 636,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "front_doorbell": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 684,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 700,
            "pid": 646,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "frontyard_a": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 652,
            "detection_enabled": true,
            "detection_fps": 5,
            "ffmpeg_pid": 658,
            "pid": 620,
            "process_fps": 5,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "46": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "86": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "98": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "10.3",
            "cpu_average": "9",
            "mem": "0.1"
        },
        "106": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "107": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "4.6",
            "cpu_average": "7",
            "mem": "0.8"
        },
        "119": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "158": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "159": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "160": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "161": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "173": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "296": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "365": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "557": {
            "cmdline": "frigate.recording_manager",
            "cpu": "2.2",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "566": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "585": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "586": {
            "cmdline": "frigate.detector.coral_usb",
            "cpu": "4.5",
            "cpu_average": "5",
            "mem": "0.3"
        },
        "589": {
            "cmdline": "frigate.detector.coral_pci",
            "cpu": "1.9",
            "cpu_average": "2",
            "mem": "0.3"
        },
        "594": {
            "cmdline": "frigate.output       ",
            "cpu": "4.2",
            "cpu_average": "4",
            "mem": "0.3"
        },
        "620": {
            "cmdline": "frigate.process:frontyard_a",
            "cpu": "36.1",
            "cpu_average": "36",
            "mem": "0.3"
        },
        "622": {
            "cmdline": "frigate.process:backyard_b",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "626": {
            "cmdline": "frigate.process:backyard_c",
            "cpu": "2.2",
            "cpu_average": "3",
            "mem": "0.3"
        },
        "636": {
            "cmdline": "frigate.process:backyard_d",
            "cpu": "18.2",
            "cpu_average": "22",
            "mem": "0.3"
        },
        "646": {
            "cmdline": "frigate.process:front_doorbell",
            "cpu": "2.5",
            "cpu_average": "5",
            "mem": "0.3"
        },
        "652": {
            "cmdline": "frigate.capture:frontyard_a",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "657": {
            "cmdline": "frigate.capture:backyard_b",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "658": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontyard_a_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.2",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "661": {
            "cmdline": "frigate.capture:backyard_c",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "667": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontyard_a -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontyard_a@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "668": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_c_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.1",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "669": {
            "cmdline": "frigate.capture:backyard_d",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "682": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "684": {
            "cmdline": "frigate.capture:front_doorbell",
            "cpu": "2.1",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "685": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_d_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.2",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "693": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_c -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard_c@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "700": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_doorbell_sub -r 5 -vf fps=5,scale_vaapi=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "5.1",
            "cpu_average": "4",
            "mem": "0.1"
        },
        "701": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_d -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard_d@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "702": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "706": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/e787cdef0323157e2dcfe63276dae664",
            "cpu": "1.3",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "708": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_doorbell@%Y%m%d%H%M%S%z.mp4",
            "cpu": "2.2",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "712": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "713": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/7ade2a6aea34b9fb9d6a2750f2399619",
            "cpu": "4.9",
            "cpu_average": "4",
            "mem": "0.1"
        },
        "718": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "723": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "728": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "13978": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "14047": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "14054": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/backyard_b?audio -c:a libopus -application:a lowdelay -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/68c5cdb5db00500549637c469da71694",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "14121": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_b_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "14123": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-4e5a6eb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_b -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard_b@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "11.2",
            "mem": "7.4"
        }
    },
    "detection_fps": 8.7,
    "detectors": {
        "coral_pci": {
            "detection_start": 0,
            "inference_speed": 9.57,
            "pid": 589
        },
        "coral_usb": {
            "detection_start": 0,
            "inference_speed": 12.45,
            "pid": 586
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "1.68%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 98
        },
        "logger": {
            "pid": 365
        },
        "recording": {
            "pid": 557
        },
        "review_segment": {
            "pid": 566
        }
    },
    "service": {
        "last_updated": 1720715904,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 506.7,
                "mount_type": "tmpfs",
                "total": 512,
                "used": 5.3
            },
            "/media/frigate/clips": {
                "free": 13749362.8,
                "mount_type": "ext4",
                "total": 15138274.5,
                "used": 625913.5
            },
            "/media/frigate/recordings": {
                "free": 13749362.8,
                "mount_type": "ext4",
                "total": 15138274.5,
                "used": 625913.5
            },
            "/tmp/cache": {
                "free": 908.8,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 44.9
            }
        },
        "temperatures": {
            "apex_0": 41.3
        },
        "uptime": 1679,
        "version": "0.14.0-4e5a6eb"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Amcrest ASH43-W

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/2847330/2d085e30-d8ff-46be-8ba6-abe4fa665990)

**Comment by ReticentRobot** [comment]
I found the option I was missing (Bounding Boxes), seems that it thinks trashcans in the distance are people.  
![image](https://github.com/blakeblackshear/frigate/assets/2847330/e79e4c17-2ec0-4ad7-8511-52473bfcf3d3)

Should I mask those areas out or what would someone typically do in this situation?

**Reply by ReticentRobot** [reply]
Checking my zones, these objects are already outside of it.  Am I missing something that would tell it to not do detections outside of my Zone?

![image](https://github.com/blakeblackshear/frigate/assets/2847330/f94fa4d6-9829-4c1b-8526-cc9a33ecace5)

**Reply by ReticentRobot** [reply]
Relevant Config for the Front Yard A cam - what am I doing wrong?:

```
    zones:
      Zone_1:
        coordinates: 0.983,0.502,0.248,0.233,0.017,0.345,0.323,0.98,0.979,0.99
    review:
      alerts:
        required_zones: Zone_1
      detections:
        required_zones: Zone_1
```
