### DISCUSSION TITLE
Question about detections - What is supported, how to use in notifications, Frigate+ requirements?

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#12391] [General]
Hello,

I have everything set up and working nicely now, so I'm looking to increase complexity to get more useful notifications at this point.  I'd like to set up notifications for different types of animals and packages.  With the free version, am I right in thinking that the only type of detection supported is Person?  I would need Frigate+ to be able to detect dogs, cats, packages, etc. and get a corresponding notification in Home Assistant, correct?  I also saw on the Frigate+ page that there seems to be a slew of options that aren't in the object type drop-down on the frigate notification blueprint - face, license plate, amazon, ups, fedex, and deer.  How would those be used in a notification?

Thanks so much!!

**Comment by NickM-27** [comment]
> With the free version, am I right in thinking that the only type of detection supported is Person?

no, that is incorrect. Frigate supports many labels, see the documentation https://docs.frigate.video/configuration/objects

**Reply by ReticentRobot** [reply]
Ah okay, interesting - so Frigate+ is not a requirement, thank you - I will look into getting this set up!  I do plan on getting Frigate+ but just replaced all of my Nest cameras with Amcrest and Reolinks, so am waiting a few months for my budget to catch back up :)

**Reply by ReticentRobot** [reply]
Alright, I've read through the documentation and examples for this.  Could you tell me if I'm understanding right that this is all I should need in my config to get started with this?:

```
objects:
  track:
    - person
    - dog
    - cat
    - package
```

I don't actually see package on the list in the documentation, but it is in the drop-down in the blueprint - so I assume it is actually supported?

**Reply by NickM-27** [reply]
Yes, except `package` does not exist in the default model

**Reply by ReticentRobot** [reply]
Alright, so I'm trying to get Frigate+ set up (free for now, not sure if that gives access to 'package' or if I need Frigate+ paid though) - but I'm not really understanding the documentation. The Home Assistant Add-On seems easy enough for getting the API key set up, but I'm running Frigate in Docker. 

> In Frigate, you can use an environment variable or a docker secret named PLUS_API_KEY to enable the SEND TO FRIGATE+ buttons on the events page. CAUTION You cannot use the environment_vars section of your configuration file to set this environment variable.

Is there any more documentation somewhere I'm missing that explains where you would put an environment variable or how you would go about doing that? I also looked at docker secrets documentation and my eyes quickly glazed over, is there maybe a step-by-step example of how that would be set up somewhere if that is the way to go over using an environment variable?

**Reply by NickM-27** [reply]
Just set the environment variable, it is just an extra -e VAR=value if using docker CLI or an extra line under `environment` if using docker compose

**Reply by ReticentRobot** [reply]
I don't seem to have an environment section in my docker compose, and I'm not seeing any examples in the documentation that I can find.  Sorry to be such a pain, my docker experience begins and ends with getting Frigate up and running.  Would it just be something like this (adding environment: at the end?):

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3
    privileged: true
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/Recordings:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
     environment:
      PLUS_API_KEY: myapikey
```

**Reply by NickM-27** [reply]
yes, the frigate installation docs show the environment section https://docs.frigate.video/frigate/installation#docker

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    ...
    ...
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
