### DISCUSSION TITLE
Synology D224+ hwaccell detected, but initializing fails

### DISCUSSION THREAD

**Discussion by Ayuus** [blakeblackshear/frigate#12408] [Hardware Acceleration Support]
### Describe the problem you are having

Running Frigate on a Synology 224+ (Intel Celeron J4125), Frigate log says hwaccel detected, and later GPU could not be initialized.

### Steps to reproduce

Start Frigete from Docker container on a Synology 224+

### Version

0.14.0-beta3

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  port: 1883
#  port: 8883
#  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: false
  user: user
  password: password
  
tls:
  enabled: False

#logger:
#  default: info
#  logs:
#    frigate.mqtt: info
#    frigate.ptz.onvif: debug

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      threshold: 0.75
    cat:
      threshold: 0.75
    dog:
      threshold: 0.75

detect:
  max_disappeared: 5

motion:
   lightning_threshold: 0.9

birdseye:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

audio:
  # geen audio events, person events zijn wel inclusief audio
  enabled: false
  min_volume: 500
  listen:
    - speech
    - yell
    - scream
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event
      threshold: 0.8
    yell:
      threshold: 0.8
    scream:
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

go2rtc:
  streams:
    buitencamera_zijgevel:
      - rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps
    buitencamera_achterzijde:
      - rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=2 #720p/25fps
    buitencamera_voordeur:
      - rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps

cameras:
  buitencamera_voordeur:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=2   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record
    onvif: # necessary for ptz handling via frigate, werkt niet
      host: 192.168.4.42
      port: 80
      user: user
      password: password

  buitencamera_zijgevel:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=2     #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=0     #4MP25fps
          roles:
            - record
    motion:
      mask:
        - 843,261,1100,720,1280,720,1280,0,868,0,484,0,493,267
    zones:
      grind:
        coordinates: 505,266,912,250,1148,720,509,720
    snapshots:
      required_zones:
        - grind
    onvif: # necessary for ptz handling via frigate, werkt niet
      host: 192.168.4.40
      port: 80
      user: user
      password: password

    review:
      alerts:
        required_zones:
          - grind
  buitencamera_achterzijde:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=1   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record
#    onvif: # necessary for ptz handling via frigate, werkt niet
#      host: 192.168.4.41
#      port: 80
#      user: user
#      password: password

version: 0.14
```

### Relevant log output

```shell
During startup:

Automatically detected vaapi hwaccel for video decoding

and later:

Unable to poll intel GPU stats: Failed to initialize PMU! (Invalid argument)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

EmpireTech/Dahua

### Any other information that may be helpful

Tried changing Docker yaml to include:

```
devices:
  - /dev/dri/renderD128:/dev/dri/renderD128

``` 
Apart from restarting migration, PMU initialization message remains, as well as high CPU usage.
