### DISCUSSION TITLE
When changing container parameters, migration is started, and history is gone

### DISCUSSION THREAD

**Discussion by Ayuus** [blakeblackshear/frigate#12407] [Report a Bug] [answered]
### Describe the problem you are having

When staarting Frigate after changing parameters of the Docker container Yaml, the migration process starts, even though the log says that migration is not needed. Result is that all Alerts are gone.

### Steps to reproduce

Refer to Docker configurtation yaml snippet below: uncomment last line (- /dev/dri/renderD128:...), recreate image and start. Observe in log that migration is not necessary, and observe in log and in reviews that migration is actually executed.

```
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware

```

### Version

0.14.0-beta3

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  port: 1883
#  port: 8883
#  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: false
  user: user
  password: password
  
tls:
  enabled: False

#logger:
#  default: info
#  logs:
#    frigate.mqtt: info
#    frigate.ptz.onvif: debug

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      threshold: 0.75
    cat:
      threshold: 0.75
    dog:
      threshold: 0.75

detect:
  max_disappeared: 5

motion:
   lightning_threshold: 0.9

birdseye:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

audio:
  # geen audio events, person events zijn wel inclusief audio
  enabled: false
  min_volume: 500
  listen:
    - speech
    - yell
    - scream
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event
      threshold: 0.8
    yell:
      threshold: 0.8
    scream:
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

go2rtc:
  streams:
    buitencamera_zijgevel:
      - rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps
    buitencamera_achterzijde:
      - rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=2 #720p/25fps
    buitencamera_voordeur:
      - rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps

cameras:
  buitencamera_voordeur:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=2   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record
    onvif: # necessary for ptz handling via frigate, werkt niet
      host: 192.168.4.42
      port: 80
      user: user
      password: password

  buitencamera_zijgevel:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=2     #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=0     #4MP25fps
          roles:
            - record
    motion:
      mask:
        - 843,261,1100,720,1280,720,1280,0,868,0,484,0,493,267
    zones:
      grind:
        coordinates: 505,266,912,250,1148,720,509,720
    snapshots:
      required_zones:
        - grind
    onvif: # necessary for ptz handling via frigate, werkt niet
      host: 192.168.4.40
      port: 80
      user: user
      password: password

    review:
      alerts:
        required_zones:
          - grind
  buitencamera_achterzijde:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=1   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record
#    onvif: # necessary for ptz handling via frigate, werkt niet
#      host: 192.168.4.41
#      port: 80
#      user: user
#      password: password

version: 0.14
```

### Relevant log output

```shell
frigate config does not need migration...
followed by logs of SQL messaged indicating migration.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

EmpireTech/Dahua

**Comment by NickM-27** [comment]
What is your docker compose? This is usually due to an incorrect config volume mount

**Comment by Ayuus** [comment]
My Docker compose:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta3
    shm_size: "96mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config.yml:/config/config.yml:rw
      - /volume1/media/frigate:/media/frigate:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8000:5000"
      - "8080:8080"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
#    environment:
#      - FRIGATE_RTSP_PASSWORD: "yTFO7Z1BBcStomuretRl"
```
Uncommenting the line "- /dev/dri/renderD128:/dev/dri/renderD128" results in new migration being started.
