### DISCUSSION TITLE
Coral usb disconnected

### DISCUSSION THREAD

**Discussion by phlnil** [blakeblackshear/frigate#12405] [Detector Support] [answered]
### Describe the problem you are having

Hi, 
got this error : frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found 
it seems that coral is not so stable after several hours...
of course cpu <10% and frigate work quite well.
I would ask if this kind of _disconnections_ are something to deal with or not.
Thank you. 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb


  filters:
    person:
      min_area: 5000
      max_area: 100000

cameras:


  RearCam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:xxx@192.168.1.164:*XXXX*
          roles:
            - record
            - detect
    detect:
      width: 704
      height: 576
      fps: 5
      enabled: True
    motion:
      mask:
        - 0,55,704,50,704,0,0,0      
    objects:
      track:
        - person
        - dog
        - cat
        - car

record:
  enabled: True
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 1
      mode: active_objects


motion:
```

### docker-compose file or Docker CLI command

```yaml
frigate already running quite well.
```

### Relevant log output

```shell
none
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral
