### DISCUSSION TITLE
[Config Support]: How to secure access to Frigate event clips via Home Assistant custom component?

### DISCUSSION THREAD

**Discussion by stalakerob** [blakeblackshear/frigate#12414] [Config Support] [answered]
### Describe the problem you are having

Im using Frigate 0.14b2, Home Assistant and the HA custom component. From an HA automation I'm sending a telegram notification that includes an URL to a Frigate clip, i.e. https://ha_domain:8123/api/frigate/notifications/{{event_id}}/clip.mp4
All of this works but it there is no authentication for accessing the clips. Can this be added so that no user/password is needed every time a clip is watched?

PS: Frigate runs as a docker container on a separate host from HA. The HA config includes an nginx add-on that provides https access to HA from the internet. 

### Version

0.14b2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.200
  port: 1883
  user: xxxxxxx
  password: xxxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car

snapshots:
  enabled: true
  retain:
    default: 7
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 7
      mode: motion

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  mode: continuous

go2rtc:
  streams:
    Garten_Cam:
      - "ffmpeg:http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=xxxxxx205"
    Garten_Cam_sub:
      - "ffmpeg:http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=user&password=xxxxxx205"
    Garten_Cam_ext:
      - "ffmpeg:http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=xxxxxx205"

    Carport_Cam:
      - rtsp://admin:xxxxxx204@192.168.1.204:554/h264Preview_01_main
    Carport_Cam_sub:
      - rtsp://admin:xxxxxx204@192.168.1.204:554/h264Preview_01_sub
    Carport_Cam_ext:
      - http://192.168.1.204/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=xxxxxx204
    WZ_Cam:
      - rtsp://admin:xxxxxx206@192.168.1.206:554/h264Preview_01_main
    WZ_Cam_sub:
      - rtsp://admin:xxxxxx206@192.168.1.206:554/h264Preview_01_sub
    Garten_Cam2:
      - rtsp://admin:xxxxxx208@192.168.1.208:554/h264Preview_01_main
    Garten_Cam2_sub:
      - rtsp://admin:xxxxxx208@192.168.1.208:554/h264Preview_01_sub
    Garten_Cam2_ext:
      - http://192.168.1.208/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=xxxxxx208


  webrtc:
    candidates:
      - 192.168.1.244:8555
      - stun:8555

cameras:
  Garten_Cam: # <------ Name the camera
    enabled: true
    motion:
      threshold: 15
      contour_area: 8
      improve_contrast: 'true'
      mask:
        - 0.708,0.941,1,0.835,1,1,0.709,1
        - 0.841,0.139,0.835,0.618,1,0.686,1,0.15
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten_Cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten_Cam # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    detect:
      enabled: true # <---- disable detection until you have a working camera feed

    live:
      stream_name: Garten_Cam_ext

  Garten_Cam2: # <------ Name the camera
    enabled: true
    motion:
      mask: 0.695,0.948,0.699,0.981,1,0.984,0.995,0.945
      threshold: 15
      contour_area: 10
      improve_contrast: 'true'
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten_Cam2 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten_Cam2_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    live:
      stream_name: Garten_Cam2_ext

  Carport_Cam: # <------ Name the camera
    enabled: true
    motion:
      mask:
        - 640,455,640,480,444,480,445,452
      threshold: 20
      contour_area: 10
      improve_contrast: 'true'
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Carport_Cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Carport_Cam_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - car
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    live:
      stream_name: Carport_Cam_ext

  WZ_Cam: # <------ Name the camera
    enabled: true
    motion:
      mask:
        - 640,322,438,319,441,352,640,352,640,352
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/WZ_Cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/WZ_Cam # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    live:
      stream_name: WZ_Cam_sub

camera_groups:
  Garten:
    order: 1
    icon: LuVideo
    cameras:
      - Garten_Cam
      - Garten_Cam2
version: 0.14
```

### Relevant log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
