### DISCUSSION TITLE
[Detector Support]: Low quality & laggy stream when viewed using Frigate, elsewhere is ok

### DISCUSSION THREAD

**Discussion by tomerh2001** [blakeblackshear/frigate#12416] [Detector Support] [answered]
### Describe the problem you are having

When I view any of my two Amcrest cameras in Frigate, I get a low-quality stream that is very laggy (1 frame every 2/3 seconds).
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/9632e177-d404-4ee6-b782-4544e9dd40cd">
<img width="472" alt="image" src="https://github.com/user-attachments/assets/5dd01073-1f6d-4f54-a799-dd7db608b53f">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8641e99c-523e-44d5-b721-6ab1fb9e1312">

But I get a crisp-looking smooth video when I view the camera from an amcrest view.
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/e1926306-8847-41a7-b155-a9bbbdfd3b7c">

I can't show the lagginess here, but the quality difference is visible in the screenshots.

This is the camera used: https://www.amazon.com/dp/B077Y52782?ref=ppx_yo2ov_dt_b_product_details&th=1

### Version

SYSTEM 0.13.2-6476F8A

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: password

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

cameras: 
  living-room:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.0.201:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
            - audio
        - path: rtsp://admin:password@10.0.0.201:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
  office:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.0.230:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
            - audio
        - path: rtsp://admin:password@10.0.0.230:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

rtmp:
  enabled: true

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

detect:
  enabled: true
  width: 704
  height: 480
  fps: 5

birdseye:
  enabled: True
  mode: continuous

objects:
  track:
    - person
    - cat
    - cell phone
```

### docker-compose file or Docker CLI command

```yaml
HA Addon
```

### Relevant log output

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral
