### DISCUSSION TITLE
[Config Support]: iGPU on Lenovo m710q is not used

### DISCUSSION THREAD

**Discussion by WildEchoWanderer** [blakeblackshear/frigate#12428] [Config Support] [answered]
### Describe the problem you are having

My system runs a i5-7400T GPU with Intel® HD Graphics 630

I have 3 Tapo C-210 Cameras detecting for human and cats with a FullHD 1080p Stream for recording and a 640x320 Sub-Stream for detection (Set like this on the cameras, i guess they are both 25 fps)

I see the GPU in Frigate\System but it is not really utilised
![image](https://github.com/user-attachments/assets/89ae1cf4-d435-46ba-8c11-8ba4ace4b044)

I brought the CPU-Load i bit down with only detecting in 5FPS

CPU is a bit toasty:
![image](https://github.com/user-attachments/assets/8e253b4b-1f9c-433f-93b3-1613de897456)

### Version

0.13.2-6476F8A     go2rtc 1.8.4

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.10
  user: mqtt-user
  password: asdfasdg

cameras:
  kamera_1:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://tapocamRTSP:kasdfasdfa@192.168.178.240/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:klasdfasdfae@192.168.178.240/stream2
          roles:
            - detect
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1
  kamera_2:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://tapocamRTSP:kluasdfasdfasdge@192.168.178.241/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:kludadsfasdfasdage@192.168.178.241/stream2
          roles:
            - detect
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1
  kamera_3:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://tapocamRTSP:klasdfasdfe@192.168.178.242/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:kludasdfasdfage@192.168.178.242/stream2
          roles:
            - detect
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1

ffmpeg:
  hwaccel_args: preset-vaapi

# Optional: database configuration for event storage
database:
  path: /media/frigate/clips/frigate.db
```

### Relevant log output

```shell
2024-07-13 12:15:41.789664865  [INFO] Preparing Frigate...
2024-07-13 12:15:41.803304583  [INFO] Starting Frigate...
2024-07-13 12:15:43.209424998  [2024-07-13 14:15:43] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-13 12:15:43.209559745  [2024-07-13 14:15:43] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-07-13 12:15:43.250594022  [2024-07-13 14:15:43] peewee_migrate.logs            INFO    : Starting migrations
2024-07-13 12:15:43.254373008  [2024-07-13 14:15:43] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-07-13 12:15:43.258803506  [2024-07-13 14:15:43] frigate.app                    INFO    : Recording process started: 450
2024-07-13 12:15:43.261234186  [2024-07-13 14:15:43] frigate.app                    INFO    : go2rtc process pid: 89
2024-07-13 12:15:43.282256115  [2024-07-13 14:15:43] detector.cpu                   INFO    : Starting detection process: 460
2024-07-13 12:15:43.287494056  [2024-07-13 14:15:43] frigate.app                    INFO    : Output process started: 462
2024-07-13 12:15:43.287633202  [2024-07-13 14:15:43] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-07-13 12:15:43.313762281  [2024-07-13 14:15:43] frigate.app                    INFO    : Camera processor started for kamera_1: 468
2024-07-13 12:15:43.315662355  [2024-07-13 14:15:43] frigate.app                    INFO    : Camera processor started for kamera_2: 470
2024-07-13 12:15:43.322352527  [2024-07-13 14:15:43] frigate.app                    INFO    : Camera processor started for kamera_3: 474
2024-07-13 12:15:43.328506738  [2024-07-13 14:15:43] frigate.app                    INFO    : Capture process started for kamera_1: 485
2024-07-13 12:15:43.332755589  [2024-07-13 14:15:43] frigate.app                    INFO    : Capture process started for kamera_2: 488
2024-07-13 12:15:43.338415801  [2024-07-13 14:15:43] frigate.app                    INFO    : Capture process started for kamera_3: 492
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

### Any other information that may be helpful

(I searched for similar problems and even used chatgpt. i did not find anything helpfull)

**Comment by NickM-27** [comment]
you have not configured frigate to use your iGPU for object detection

you should also be using `preset-vaapi` instead of manual ffmpeg args for hwaccel_args

**Reply by WildEchoWanderer** [reply]
thanks for the fast reply

how would i config frigate to use the gpu? i am absolutely new to frigate

**Reply by NickM-27** [reply, marked as answer]
https://docs.frigate.video/configuration/object_detectors#openvino-detector

**Reply by WildEchoWanderer** [reply]
Wow thank you!
Seems linke it works now because Interference is down, CPU% is down and GPU% is up
![image](https://github.com/user-attachments/assets/44fd8d6b-d969-4252-b879-0e0796a3e71f)


What does this?
```
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```
and should i set it to 640x320?

also i am wondering if i should delete/change something in my config now:
```
mqtt:
  host: 192.168.178.10
  user: mqtt-user
  password: loliasdfdfme

cameras:
  kamera_1:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://tapocamRTSP:kasdfdsfase@192.168.178.240/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:kluasdfasdfasage@192.168.178.240/stream2
          roles:
            - detect
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1
  kamera_2:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://tapocamRTSP:klasdfasde@192.168.178.241/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:kluasdfasdfge@192.168.178.241/stream2
          roles:
            - detect
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1
  kamera_3:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://tapocamRTSP:kludasdfasdfge@192.168.178.242/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:klasdffdsae@192.168.178.242/stream2
          roles:
            - detect
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# Optional: database configuration for event storage
database:
  path: /media/frigate/clips/frigate.db
```

**Reply by NickM-27** [reply]
It's the size of the model, no you should not change it (the docs would tell you to if you should)

You should however replace the manual ffmpeg args with preset-vaapi

**Reply by WildEchoWanderer** [reply]
EDIT: Seems i had just to jus remove all the 
```
          hwaccel_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
```
to get it right :)

Thanks a lot for the infos & help 🥇 

(before edit:)
_I changed the code to this and now it does not work anymore
![image](https://github.com/user-attachments/assets/28565f90-7a99-4d05-8e77-0dab4411b4ca)_


```
mqtt:
  host: 192.168.178.10
  user: mqtt-user
  password: lolihgfdome

cameras:
  kamera_1:
    ffmpeg:
      hwaccel_args:
        - preset-vaapi
      inputs:
        - path: rtsp://tapocamRTSP:kludifud1mAgedage@192.168.178.240/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:asdfasdfae@192.168.178.240/stream2
          roles:
            - detect
          hwaccel_args:
            - preset-vaapi
    detect:
      width: 640
      height: 360
      fps: 25
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1
  kamera_2:
    ffmpeg:
      hwaccel_args:
        - preset-vaapi
      inputs:
        - path: rtsp://tapocamRTSP:kluasdfasfdaage@192.168.178.241/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:kludasdfadsfage@192.168.178.241/stream2
          roles:
            - detect
          hwaccel_args:
            - preset-vaapi
    detect:
      width: 640
      height: 360
      fps: 25
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1
  kamera_3:
    ffmpeg:
      hwaccel_args:
        - preset-vaapi
      inputs:
        - path: rtsp://tapocamRTSP:kluasfdfasage@192.168.178.242/stream1
          roles:
            - record
        - path: rtsp://tapocamRTSP:kluasdfadage@192.168.178.242/stream2
          roles:
            - detect
          hwaccel_args:
            - preset-vaapi
    detect:
      width: 640
      height: 360
      fps: 25
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 1

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# Optional: database configuration for event storage
database:
  path: /media/frigate/clips/frigate.db
```

this is the log:
```
2024-07-13 14:31:50.466920872  [2024-07-13 16:31:50] frigate.video                  ERROR   : kamera_1: Unable to read frames from ffmpeg process.
2024-07-13 14:31:50.467093043  [2024-07-13 16:31:50] frigate.video                  ERROR   : kamera_1: ffmpeg process is not running. exiting capture thread...
2024-07-13 14:31:51.776634196  [2024-07-13 16:31:51] frigate.video                  ERROR   : kamera_2: Unable to read frames from ffmpeg process.
2024-07-13 14:31:51.776872473  [2024-07-13 16:31:51] frigate.video                  ERROR   : kamera_2: ffmpeg process is not running. exiting capture thread...
2024-07-13 14:31:52.996591483  [2024-07-13 16:31:52] frigate.video                  ERROR   : kamera_3: Unable to read frames from ffmpeg process.
2024-07-13 14:31:52.997669974  [2024-07-13 16:31:52] frigate.video                  ERROR   : kamera_3: ffmpeg process is not running. exiting capture thread...
2024-07-13 14:32:07.963860068  [2024-07-13 16:32:07] watchdog.kamera_1              ERROR   : Ffmpeg process crashed unexpectedly for kamera_1.
2024-07-13 14:32:07.964113720  [2024-07-13 16:32:07] watchdog.kamera_1              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-07-13 14:32:07.964352593  [2024-07-13 16:32:07] ffmpeg.kamera_1.detect         ERROR   : [NULL @ 0x56383dd1ac80] Unable to find a suitable output format for 'preset-vaapi'
2024-07-13 14:32:07.964648056  [2024-07-13 16:32:07] ffmpeg.kamera_1.detect         ERROR   : preset-vaapi: Invalid argument
2024-07-13 14:32:07.972221183  [2024-07-13 16:32:07] watchdog.kamera_2              ERROR   : Ffmpeg process crashed unexpectedly for kamera_2.
2024-07-13 14:32:07.972468334  [2024-07-13 16:32:07] watchdog.kamera_2              ERROR   : The following ffmpeg logs include the last 100 
```_
