### DISCUSSION TITLE
[Support]: when using go2rtc on different machine, live view needs initial refresh in UI

### DISCUSSION THREAD

**Discussion by ronbruins** [blakeblackshear/frigate#12427] [General Support]
### Describe the problem you are having

To split the load I installed go2rtc on a different machine and pinned frigate to use these streams. However when selecting the live view, by clicking on a camera the screen stays black, when I refresh the browser it does show me the stream. I have 4 camera's and all behave the same. 

### Version

0.14b3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.35
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ***
  password: ***

# logger:
#   # Optional: default log level (default: shown below)
#   default: debug


detectors:
  coral:
    type: edgetpu
    device: usb
model:
  path: plus://5****9764033593f46
  labelmap:
    16: Kat

birdseye:
  enabled: true
  mode: continuous

audio: # <- enable audio events for all camera
  enabled: false
# motion:
#   threshold: 50

snapshots:
  enabled: true
  retain:
    default: 1

# detect:
#   enabled: true # <---- turn on detection
#   width: 1280
#   height: 720

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 7
      mode: motion

objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
  #- Kat
    - car
    - amazon
    - fedex
    - ups
    - package
  filters:
    cat:
      min_area: 3000
      threshold: 0.83
    dog:
      min_area: 3000
      threshold: 0.8
    person:
      min_area: 5500
      threshold: 0.8

cameras:
  deurbel:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:8554/deurbel?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac -tag:v hvc1
    detect:
      enabled: true # <---- turn on detection
      width: 1280
      height: 960
    live:
      stream_name: deurbel
    motion:
      threshold: 75
    objects:
      filters:
        car:
          mask: 0.738,0.689,0.72,0.788,0.141,0.818,0.116,0.736,0.508,0.715
        cat:
          mask: 0.004,0.005,0.002,0.204,0.234,0.221,0.283,0.008
### Camera VOORDEUR Config ###
  voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:8554/voordeur?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac -tag:v hvc1
    detect:
      enabled: true # <---- turn on detection
      width: 1280
      height: 720
    live:
      stream_name: voordeur
    zones:
      pad:
        coordinates: 0.224,0.63,0.159,0.824,0.277,0.925,0.391,1,0.535,1,0.568,0.775
        inertia: 3
      trottoir:
        coordinates: 
          225,539,277,461,303,438,268,362,392,213,526,70,627,0,564,0,410,110,256,244,122,384,0,569,0,720,59,720,132,558,166,583,191,600
      weg:
        coordinates: 0,165,267,0,561,0,407,110,253,244,119,384,0,562
      fietsen:
        coordinates: 0.512,0,0.601,0,0.58,0.489,0.57,0.69,0.567,0.76,0.257,0.639
        inertia: 3
      stoepje_voordeur:
        coordinates: 0.535,1,0.78,1,0.791,0.753,0.579,0.691
        inertia: 3
    objects:
      filters:
        # person:
        #   mask:
        #     - 536,324,566,183,744,246,715,566,544,530
        car:
          mask:
            - 466,128,142,677,0,473,342,81

    motion:
      threshold: 75
      mask:
        - 1280,0,1280,39,1205,34,1204,0
      #- 0,0,397,0,0,378

### Camera ACHTER Config ###
  achter:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:8554/achter?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac -tag:v hvc1
    live:
      stream_name: achter
    onvif:
      host: 192.168.1.181
      port: 8000
      user: ***
      password: ***
    detect:
      enabled: true # <---- turn on detection
      width: 1280
      height: 960
    motion:
      threshold: 70
      mask:
        - 864,0,860,95,606,91,606,0
    objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - face
        - cat
      filters:
        dog:
          mask:
            - 0,960,1280,960,1280,0,0,0
        cat:
          mask:
            - 174,878,0,347,0,960,197,960
        person:
          mask:
            - 1280,925,1280,960,358,960,354,932
          threshold: 0.9
    zones:
      terrasdeur:
        coordinates: 149,581,280,546,389,740,217,798
      hek:
        coordinates: 169,118,451,99,507,60,864,55,839,409,508,353,204,392
      terras:                                        # -  LB- ,-  RB -,-  RO -,-  LO -
        coordinates: 1280,960,1280,918,504,460,147,537,148,578,282,542,393,741,219,801,282,960
      tuinset:
        coordinates: 1280,960,1280,399,852,356,836,530,530,594,415,960

  balkon:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:8554/balkon?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
    live:
      stream_name: balkon
    detect:
      enabled: true # <---- turn on detection
      width: 1280
      height: 720

    motion:
      threshold: 75
      mask:
        - 0,395,0,0,429,0
        - 721,0,721,23,630,23,630,0
      contour_area: 10
      improve_contrast: true
    objects:
      filters:
        # person:
        #   mask:
        #     #- 547,99,545,151,455,167,445,117
        #     - 0,445,504,300,397,116,0,216
        #     - 1170,720,1174,688,924,688,883,720
        #     - 1236,290,1280,284,1280,331,1233,335
        car:
          mask:
            - 1,0.56,0.71,0.759,0.251,0.876,0,0.895,0,1,0.359,1,1,0.783
            - 1,0.209,0.304,0.366,0,0.492,0,0.584,1,0.295
version: 0.14
camera_groups:
  Large:
    order: 1
    icon: LuAlignCenter
    cameras:
      - balkon
      - voordeur
      - deurbel
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

reolink
