### DISCUSSION TITLE
[HW Accel Support]: Orange Pi5 Pro and GPU

### DISCUSSION THREAD

**Discussion by GMagician** [blakeblackshear/frigate#12433] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

How can I know if GPU is used? on stat page I just see CPU.

Note: All NPU cores are working (note I read somewhere that num_cores: 0 means use all cores but it uses just 1 core)

### Version

0.14 beta 4

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: false

birdseye:
  enabled: true
  mode: continuous

detectors:
  rknn:
    type: rknn
    num_cores: 3

model:
  path: deci-fp16-yolonas_s
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nhwc

ffmpeg:
  hwaccel_args: preset-rk-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    Balcone_main:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.112:554/0#video=copy#audio=copy
    Balcone_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.112:554/1#video=copy#audio=copy
    - ffmpeg:Balcone_sub##audio=opus
    Retro_main:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/0#video=copy#audio=copy
    Retro_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/1#video=copy#audio=copy
    - ffmpeg:Retro_sub#audio=opus

cameras:
  Balcone:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Balcone_main
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Balcone_sub
        roles:
        - detect
    birdseye:
      order: 1
    live:
      stream_name: Balcone_sub
    motion:
      threshold: 20
    detect:
      fps: 10
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5
  Retro:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Retro_main
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Retro_sub
        roles:
        - detect
    birdseye:
      order: 2
    live:
      stream_name: Retro_sub
    motion:
      threshold: 12
    detect:
      fps: 10
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5

timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

record:
  enabled: true
  retain:
    days: 0
  events:
    objects:
    - person
    pre_capture: 5
    post_capture: 10
    retain:
      default: 5
      mode: active_objects
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4-rk
    shm_size: "256mb"
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    devices:
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    ports:
      - "5000:5000"
    environment:
      FRIGATE_RTSP_USER: xxxxx
      FRIGATE_RTSP_PASSWORD: xxxxx
```

### Relevant log output

```shell
None all ok
```

### FFprobe output from your camera

```shell
none all ok
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

DSE

### Any other information that may be helpful

My problem is no a problem but more a question. How can I know if GPU is used? on stat page I just see CPU.
All NPU cores are working (note I read somewhere that num_cores: 0 is use all cores but it uses just 1 core)
