### DISCUSSION TITLE
[Config Support]: Reolink Camera 2 Way Audio not working

### DISCUSSION THREAD

**Discussion by sam7567** [blakeblackshear/frigate#12447] [Config Support]
### Describe the problem you are having

No matter what I try, can't make 2-way audio working with Riolink Cameras. My setup is as below:

HW: Beelink EQ13 (No Coral as of now. Order placed not yet received but seems this is not because of that.
Setup: Proxmox + Firgate Docker LXC via Helper Script

Following another thread, have upgraded `go2rtc` to version=`1.9.4`

```
# cat docker-compose.yaml 
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:rw
      - /opt/frigate/config/go2rtc:/config/go2rtc
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

![Screenshot 2024-07-14 213944](https://github.com/user-attachments/assets/482fd5f3-6f4a-4866-9794-9ea3f30c56c4)

Camera Card Config in Home Assistant:
```
    type: custom:frigate-card
    cameras:
      - camera_entity: camera.family_room
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc

    live:
      microphone:
        always_connected: true
        disconnect_seconds: 0

    menu:
      buttons:
        microphone:
          enabled: true
```

No MIC or Speaker icon in the menu

![Screenshot 2024-07-14 215226](https://github.com/user-attachments/assets/14b911a1-564e-4c29-8393-6332fe6690d5)

### Version

Frigate (0.13.2-6476f8a)

### Frigate config file

```yaml
mqtt:
  host: mqtt-server-ip
  port: 1883
  user: redacted
  password: redacted
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy

# detectors:
#   cpu1:
#     type: cpu

database:
  path: /config/frigate.db

birdseye:
  enabled: False

rtmp:
  enabled: False

record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  retain:
    days: 0
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True
  clean_copy: True
  retain:
    default: 5

go2rtc:
  webrtc:
    candidates:
      - 192.168.7.245:8555
      - stun:8555
  streams:
    ### Riolink E1 Outdoor -- All 3 works fine with same one way audio only. Home-Assistant has HTTPS enabled and I can see "mic" state is in-use but I can listen audio from camera but cant send voice to camera.
    frigate_backyard:
      - "ffmpeg:http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    frigate_backyard_sub:
      - "ffmpeg:http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}"

    # frigate_backyard:
    #   - http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD} # <- stream which supports video & aac audio
    #   - "ffmpeg:frigate_backyard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    # frigate_backyard_sub:
    #   - http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}
    #   - "ffmpeg:frigate_backyard_sub#audio=opus"

    # frigate_backyard:
    #   - rtsp://{FRIGATE_RTSP_UID}:{FRIGATE_RTSP_PASSWORD}@192.168.4.88:554/h264Preview_01_main
    #   - "ffmpeg:frigate_backyard#audio=opus"
    # frigate_backyard_sub:
    #   - rtsp://{FRIGATE_RTSP_UID}:{FRIGATE_RTSP_PASSWORD}@192.168.4.88:554/h264Preview_01_sub
    
    ### Riolink E1 Zoom -- All 3 works fine with same one way audio only. Home-Assistant has HTTPS enabled and I can see "mic" state is in-use but I can listen audio from camera but cant send voice to camera.
    frigate_family_room:
      - "ffmpeg:http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    frigate_family_room_sub:
      - "ffmpeg:http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}"

    # frigate_family_room:
    #   - http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD} # <- stream which supports video & aac audio
    #   - "ffmpeg:frigate_family_room#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    # frigate_family_room_sub:
    #   - http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}
    #   - "ffmpeg:frigate_family_room_sub#audio=opus"

    # frigate_family_room: 
    #   - rtsp://{FRIGATE_RTSP_UID}:{FRIGATE_RTSP_PASSWORD}@192.168.4.89:554/h264Preview_01_main 
    #   - "ffmpeg:frigate_family_room#audio=opus" 
    # frigate_family_room_sub:
    #   - rtsp://{FRIGATE_RTSP_UID}:{FRIGATE_RTSP_PASSWORD}@192.168.4.89:554/h264Preview_01_sub

cameras:
  ## Camera config for Bakyard
  ############################
  backyard:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        # Stream High Resolution
        - path: rtsp://127.0.0.1:8554/frigate_backyard
          input_args: preset-rtsp-restream
          roles:
            - record

        # Stream Standard Resolution
        - path: rtsp://127.0.0.1:8554/frigate_backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect

    live:
      stream_name: frigate_backyard
    
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10

  ## Camera config for Family Room
  ################################
  family_room:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        # Stream High Resolution
        - path: rtsp://127.0.0.1:8554/frigate_family_room
          input_args: preset-rtsp-restream
          roles:
            - record

        # Stream Standard Resolution
        - path: rtsp://127.0.0.1:8554/frigate_family_room_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect      

    live:
      stream_name: frigate_family_room

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 7
```

### Relevant log output

```shell
2024-07-14 21:28:36.200594055  [2024-07-14 21:28:36] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-14 21:28:36.242350966  [2024-07-14 21:28:36] peewee_migrate.logs            INFO    : Starting migrations
2024-07-14 21:28:36.246130570  [2024-07-14 21:28:36] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-07-14 21:28:37.157842459  [2024-07-14 21:28:37] frigate.app                    INFO    : Recording process started: 289
2024-07-14 21:28:37.157846298  [2024-07-14 21:28:37] frigate.app                    INFO    : go2rtc process pid: 92
2024-07-14 21:28:37.183722767  [2024-07-14 21:28:37] detector.cpu                   INFO    : Starting detection process: 299
2024-07-14 21:28:37.194208055  [2024-07-14 21:28:37] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-07-14 21:28:37.194212075  [2024-07-14 21:28:37] frigate.app                    INFO    : Output process started: 301
2024-07-14 21:28:40.014110292  [2024-07-14 21:28:40] frigate.app                    INFO    : Camera processor started for backyard: 319
2024-07-14 21:28:40.026482649  [2024-07-14 21:28:40] frigate.app                    INFO    : Camera processor started for family_room: 320
2024-07-14 21:28:40.035247023  [2024-07-14 21:28:40] frigate.app                    INFO    : Capture process started for backyard: 323
2024-07-14 21:28:40.035250974  [2024-07-14 21:28:40] frigate.app                    INFO    : Capture process started for family_room: 326
```

### Frigate stats

```json
{
    "frigate_backyard": {
        "consumers": [
            {
                "bytes_send": 66764103,
                "format_name": "rtsp",
                "id": 3,
                "medias": [
                    "video, sendonly, ANY",
                    "audio, sendonly, MPEG4-GENERIC"
                ],
                "protocol": "rtsp+tcp",
                "remote_addr": "127.0.0.1:54230",
                "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
                "senders": [
                    {
                        "bytes": 65006511,
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 13,
                        "packets": 45782,
                        "parent": 10
                    },
                    {
                        "bytes": 1010430,
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 14,
                        "packets": 981,
                        "parent": 11
                    }
                ],
                "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
            }
        ],
        "producers": [
            {
                "bytes_recv": 67749076,
                "format_name": "rtsp",
                "id": 9,
                "medias": [
                    "video, recvonly, H264",
                    "audio, recvonly, MPEG4-GENERIC/16000",
                    "audio, recvonly, OPUS/48000/2"
                ],
                "protocol": "rtsp+tcp",
                "receivers": [
                    {
                        "bytes": 65006511,
                        "childs": [
                            13
                        ],
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 10,
                        "packets": 45782
                    },
                    {
                        "bytes": 1010430,
                        "childs": [
                            14
                        ],
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 11,
                        "packets": 981
                    },
                    {
                        "bytes": 1093495,
                        "codec": {
                            "channels": 2,
                            "codec_name": "opus",
                            "codec_type": "audio",
                            "sample_rate": 48000
                        },
                        "id": 12,
                        "packets": 6282
                    }
                ],
                "remote_addr": "127.0.0.1:54762 forwarded 192.168.4.88",
                "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
                "source": "exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Welc0me1234 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/302d35708d9b17c9a759672fe943f5be",
                "url": "http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*",
                "user_agent": "ffmpeg/go2rtc"
            }
        ]
    },
    "frigate_backyard_sub": {
        "consumers": [
            {
                "bytes_send": 19723346,
                "format_name": "rtsp",
                "id": 1,
                "medias": [
                    "video, sendonly, ANY"
                ],
                "protocol": "rtsp+tcp",
                "remote_addr": "127.0.0.1:54208",
                "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\n",
                "senders": [
                    {
                        "bytes": 19484962,
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 8,
                        "packets": 14899,
                        "parent": 6
                    }
                ],
                "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
            }
        ],
        "producers": [
            {
                "bytes_recv": 20687352,
                "format_name": "rtsp",
                "id": 5,
                "medias": [
                    "video, recvonly, H264",
                    "audio, recvonly, MPEG4-GENERIC/16000"
                ],
                "protocol": "rtsp+tcp",
                "receivers": [
                    {
                        "bytes": 19484962,
                        "childs": [
                            8
                        ],
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 6,
                        "packets": 14899
                    },
                    {
                        "bytes": 1010430,
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 7,
                        "packets": 981
                    }
                ],
                "remote_addr": "127.0.0.1:54758 forwarded 192.168.4.88",
                "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\n",
                "source": "exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Welc0me1234 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/76c4a09ec7dc40260d1f873331e78d8c",
                "url": "http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=*",
                "user_agent": "ffmpeg/go2rtc"
            }
        ]
    },
    "frigate_family_room": {
        "consumers": [
            {
                "bytes_send": 66566321,
                "format_name": "rtsp",
                "id": 4,
                "medias": [
                    "video, sendonly, H264, H265",
                    "audio, sendonly, MPEG4-GENERIC"
                ],
                "protocol": "rtsp+tcp",
                "remote_addr": "127.0.0.1:54232",
                "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
                "senders": [
                    {
                        "bytes": 64813387,
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 19,
                        "packets": 45687,
                        "parent": 16
                    },
                    {
                        "bytes": 1006310,
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 20,
                        "packets": 977,
                        "parent": 17
                    }
                ],
                "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
            }
        ],
        "producers": [
            {
                "bytes_recv": 67500529,
                "format_name": "rtsp",
                "id": 15,
                "medias": [
                    "video, recvonly, H264",
                    "audio, recvonly, MPEG4-GENERIC/16000",
                    "audio, recvonly, OPUS/48000/2"
                ],
                "protocol": "rtsp+tcp",
                "receivers": [
                    {
                        "bytes": 64813387,
                        "childs": [
                            19
                        ],
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 16,
                        "packets": 45687
                    },
                    {
                        "bytes": 1006310,
                        "childs": [
                            20
                        ],
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 17,
                        "packets": 977
                    },
                    {
                        "bytes": 1043656,
                        "codec": {
                            "channels": 2,
                            "codec_name": "opus",
                            "codec_type": "audio",
                            "sample_rate": 48000
                        },
                        "id": 18,
                        "packets": 6259
                    }
                ],
                "remote_addr": "127.0.0.1:54766 forwarded 192.168.4.89",
                "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
                "source": "exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Welc0me1234 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/928768d3fc1d4d47ad2a11249ddcb0ce",
                "url": "http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*",
                "user_agent": "ffmpeg/go2rtc"
            }
        ]
    },
    "frigate_family_room_sub": {
        "consumers": [
            {
                "bytes_send": 20666219,
                "format_name": "rtsp",
                "id": 2,
                "medias": [
                    "video, sendonly, H264, H265",
                    "audio, sendonly, MPEG4-GENERIC"
                ],
                "protocol": "rtsp+tcp",
                "remote_addr": "127.0.0.1:54222",
                "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
                "senders": [
                    {
                        "bytes": 19420201,
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 24,
                        "packets": 14397,
                        "parent": 22
                    },
                    {
                        "bytes": 1001160,
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 25,
                        "packets": 972,
                        "parent": 23
                    }
                ],
                "user_agent": "FFmpeg Frigate/0.13.2-6476f8a"
            }
        ],
        "producers": [
            {
                "bytes_recv": 20607189,
                "format_name": "rtsp",
                "id": 21,
                "medias": [
                    "video, recvonly, H264",
                    "audio, recvonly, MPEG4-GENERIC/16000"
                ],
                "protocol": "rtsp+tcp",
                "receivers": [
                    {
                        "bytes": 19420201,
                        "childs": [
                            24
                        ],
                        "codec": {
                            "codec_name": "h264",
                            "codec_type": "video",
                            "level": 51,
                            "profile": "High"
                        },
                        "id": 22,
                        "packets": 14397
                    },
                    {
                        "bytes": 1001160,
                        "childs": [
                            25
                        ],
                        "codec": {
                            "codec_name": "aac",
                            "codec_type": "audio",
                            "sample_rate": 16000
                        },
                        "id": 23,
                        "packets": 972
                    }
                ],
                "remote_addr": "127.0.0.1:54770 forwarded 192.168.4.89",
                "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKDgFWQ=,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\n",
                "source": "exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Welc0me1234 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/2c26e05827617bedb6f552f17fbef1f7",
                "url": "http://192.168.4.89/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=*",
                "user_agent": "ffmpeg/go2rtc"
            }
        ]
    }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Any other information that may be helpful

Frigate on Docker LXC is on HTTP only. Hope that is not causing issue. I understand Mic won't work with HTTP hence tried through Frigate Proxy on HA as well. No issue with video or incoming audio. Only problem with outgoing audio from Browser.

I have been searching and learning Frigate related topics on this issue for more than 2 weeks now. Unable to resolve by any way.

Please advise if there is something wrong in my understanding.

**Comment by NickM-27** [comment]
You're using the frigate card, so that is the repo where this issue should be reported

**Reply by sam7567** [reply]
How can i see frigate card log? in homeassistant log? Please ignore frigate card and advise a native alternate way to troubleshoot. 

I have Frigate Proxy configured as well which is serving with HTTPS inside HA. Its same there. Camera is not getting my voice.

**Reply by NickM-27** [reply]
https://github.com/dermotduffy/frigate-hass-card is the repo, I don't know how the frigate card works. Frigate 0.14 supports two way talk in the UI so I'd be able to help with that

**Reply by sam7567** [reply]
ok then please check my frigate version. is this ok? I used `image: ghcr.io/blakeblackshear/frigate:stable` this one

Frigate (0.13.2-6476f8a)

**Reply by NickM-27** [reply]
Right, 0.14 is in beta currently

**Reply by sam7567** [reply]
Just upgraded to `ghcr.io/blakeblackshear/frigate:0.14.0-beta4`. The UI looks nice :) but can't see the mic button still

![image](https://github.com/user-attachments/assets/40b0d673-adf3-44dd-96c2-1d38ee927280)

**Reply by sam7567** [reply]
May be a dumb question, but can you see if I made any mistake in frigate config already? I have been with frigate for 3 weeks now and learning everyday. Thanks in advance

**Reply by NickM-27** [reply]
ah yes, you're missing a line in the go2rtc config https://docs.frigate.video/configuration/camera_specific#reolink-doorbell

**Reply by sam7567** [reply]
Mine is not doorbell. One is Riolink E1 Zoom indoor camera and another one is E1 Outdoor. Both are Wifi Camera only. I can certainly try the doorbell config anyway. Let me see.

**Reply by sam7567** [reply]
The new Config: Not working. Tried `Preview_01_sub` as well as `h264Preview_01_sub` My voice is echoing in laptop itself but not reaching the camera

```
  streams:
    ### Riolink E1 Outdoor -- All 3 works fine with same one way audio
    frigate_backyard:
      - ffmpeg:http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
      - rtsp://192.168.4.88/Preview_01_sub
    frigate_backyard_sub:
      - ffmpeg:http://192.168.4.88/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_UID}&password={FRIGATE_RTSP_PASSWORD}
```
