### DISCUSSION TITLE
Input / Output-Options for recordings

### DISCUSSION THREAD

**Discussion by Bodengriller** [blakeblackshear/frigate#12442] [General Support] [answered]
### Describe the problem you are having

I have problems that my recordings from one camera become faulty and show green images, but the live stream works without any problems.
More details [here.](https://github.com/blakeblackshear/frigate/discussions/11229)
Unfortunately, I still haven't found a solution.

Where do the ffmpeg input settings intervene and where the output settings?
I don't know where else I can tweak or what else I can test.
It would be too easy to buy a new camera, where's the fun in that? :-)

If the live stream is displayed without errors, I assume that the input settings must be OK so far.
I assume that the output settings determine how the live stream becomes a record or how it is converted.
I am also almost certain that it is somehow related to the hwaccl.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci

#activate hardware acceleration
ffmpeg:
  hwaccel_args: preset-vaapi
  #hwaccel_args: preset-intel-qsv-h264
  #hwaccel_args: "-loglevel warning"

mqtt:
  enabled: True
  host: 192.168.178.123
  port: 1883
  user: "user"
  password: "secret"

rtmp:
  enabled: False
  
##########----------General ui----------##########
birdseye:
  # Optional: Enable birdseye view (default: True)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: False)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: 1280)
  width: 640
  # Optional: Height of the output resolution (default: 720)
  height: 360
  # Optional: Encoding quality of the mpeg1 feed (default: 8)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

live:
  height: 360

timestamp_style:
    position: "br"
    format: "%d.%m.%Y %H:%M:%S"
    effect: solid

##########----------General-Config----------##########
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
  filters:
    person:
      # Optional: minimum score for the object to initiate tracking (default: 0.5)
      min_score: 0.4
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      threshold: 0.7
    car:
      # Optional: minimum score for the object to initiate tracking (default: 0.5)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      threshold: 0.7

snapshots:
  enabled: True
  clean_copy: False
  timestamp: True
  bounding_box: True
  retain:
    default: 10
    objects:
      person: 30

# only keeps Motion-Clips for 10 days (default)
record:     
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 10
    post_capture: 20
    retain:
      default: 14
      mode: active_objects

##########----------Camera-Config----------##########
cameras:
  #####-----Kamera Parkplatz----#####
  Parkplatz:
    #enabled: False
    ui:
      order: 2
    ffmpeg:
      retry_interval: 15
      input_args: -rtsp_transport tcp
      #input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://192.168.178.40/ch0_1.h264
          roles:
            - detect
          #hwaccel_args: preset-vaapi
          #hwaccel_args: preset-intel-qsv-h264
          #hwaccel_args: "-loglevel warning"
        - path: rtsp://192.168.178.40/ch0_1.h264
          roles:
            - record
          #hwaccel_args: preset-vaapi
          #hwaccel_args: preset-intel-qsv-h264
          #hwaccel_args: "-loglevel warning"
    detect:
      #enabled: False
      enabled: True
      width: 640
      height: 360
      fps: 5
    record:
      events:
        required_zones:
          - driving_zone
    snapshots:
      required_zones:
        - driving_zone
    motion:
      mask:
      - 640,187,377,360,640,360
      - 640,0,640,360,604,360,427,0
      - 640,175,511,154,345,124,349,96,216,78,0,104,0,33,0,0,640,0
      - 588,0,0,0,0,124
      - 101,360,0,360,0,0,80,0
      - 0,360,346,360,267,291,0,291
    zones:
      driving_zone:
        coordinates: 198,360,556,163,364,130,129,187,132,360
  #####-------------------------#####
  
  #####------Kamera Carport-----#####
    # no problems with this cam
  #####-------------------------#####

  #####----Kamera Stellplatz----#####
    # no problems with this cam
  #####-------------------------#####
```

### Relevant log output

```shell
nothing special
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640}]}}]
```

### Frigate stats

```json
{"cameras":{"Carport":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":361,"detection_enabled":1,"detection_fps":5.0,"ffmpeg_pid":2749717,"pid":357,"process_fps":5.0,"skipped_fps":0.0},"Parkplatz":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":360,"detection_enabled":1,"detection_fps":4.9,"ffmpeg_pid":2749763,"pid":356,"process_fps":5.0,"skipped_fps":0.0},"Stellplatz":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":366,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":2749739,"pid":359,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"86":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"93":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"103":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"python3 -u -m frigate","cpu":"2.8","cpu_average":"2","mem":"2.8"},"117":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"152":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"298":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"300":{"cmdline":"frigate.recording_manager","cpu":"1.9","cpu_average":"1","mem":"1.1"},"308":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"309":{"cmdline":"frigate.detector.coral","cpu":"2.9","cpu_average":"2","mem":"0.3"},"310":{"cmdline":"frigate.output       ","cpu":"1.0","cpu_average":"0","mem":"0.3"},"313":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"321":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 640x360 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"356":{"cmdline":"frigate.process:Parkplatz","cpu":"8.4","cpu_average":"4","mem":"1.3"},"357":{"cmdline":"frigate.process:Carport","cpu":"6.8","cpu_average":"5","mem":"0.7"},"359":{"cmdline":"frigate.process:Stellplatz","cpu":"1.7","cpu_average":"2","mem":"0.4"},"360":{"cmdline":"frigate.capture:Parkplatz","cpu":"0.7","cpu_average":"0","mem":"0.4"},"361":{"cmdline":"frigate.capture:Carport","cpu":"0.9","cpu_average":"0","mem":"0.4"},"366":{"cmdline":"frigate.capture:Stellplatz","cpu":"0.7","cpu_average":"0","mem":"0.4"},"381":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -i rtsp://192.168.178.40/ch0_1.h264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Parkplatz@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"2731720":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -i rtsp://192.168.178.42/ch0_1.h264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Stellplatz@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"2731730":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -i rtsp://192.168.178.41/ch0_1.h264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Carport@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"2749717":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -i rtsp://192.168.178.41/ch0_1.h264 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.2"},"2749739":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -i rtsp://192.168.178.42/ch0_1.h264 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"2","mem":"0.2"},"2749763":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -i rtsp://192.168.178.40/ch0_1.h264 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.2"},"2820193":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":9.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.39,"pid":309}},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"processes":{"go2rtc":{"pid":86},"logger":{"pid":298},"recording":{"pid":300}},"service":{"last_updated":1720979263,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":120.4,"mount_type":"tmpfs","total":128.0,"used":7.6},"/media/frigate/clips":{"free":152034.4,"mount_type":"ext4","total":205639.1,"used":43087.8},"/media/frigate/recordings":{"free":152034.4,"mount_type":"ext4","total":205639.1,"used":43087.8},"/tmp/cache":{"free":697.0,"mount_type":"overlay","total":15954.9,"used":14422.6}},"temperatures":{"apex_0":45.05},"uptime":1130674,"version":"0.13.2-6476f8a"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

yi home y211ga (yi-hack 0.3.2)

**Comment by Bodengriller** [comment]
Here is an examle recording-clip.

https://github.com/user-attachments/assets/ea3b0b24-8c55-4323-baca-9c546702e529

No visible problems with VLC-Player or Firefox, but with WindowsMediaPlayer, Chrome, Edge etc. only green images.
Also with the Android Chrome and Firefox

**Comment by NickM-27** [comment]
Live stream and recordings are entirely unrelated, so one working does not confirm any part of the other is working. 

I'd definitely suggest not using minimal input args like that and instead using one of the input presets

**Reply by Bodengriller** [reply]
I'm still trying to understand what exactly is meant by input_args and output_args or what attacks where and if there is a way to troubleshoot to find out what is going wrong.

in my opinion, i have tested the presets in all combinations of input/output_args - without success

**Reply by NickM-27** [reply]
Ffmpeg very specifically has input and output (demuxer and muxer). By default frigate only copies from recording so I'm not sure any output args short of re-encoding (increased cpu and GPU usage) will help

**Reply by Bodengriller** [reply]
hmm... so it's definitely a problem related to ffmpeg?
Then I'll probably ask the ffmpeg specialists if they have any ideas as to where I could attack here

Thank you in any case for your great support

**Reply by NickM-27** [reply]
No, it's almost certainly a camera problem, and the only way to fix it is by re encoding

**Reply by Bodengriller** [reply]
I expressed myself unfavorably.
Of course I don't mean that ffmpeg itself has a problem.
I meant that this problem can only be solved with the right ffmpeg settings

Or am I misunderstanding you completely?

**Reply by NickM-27** [reply, marked as answer]
ah, yes that is correct. If you did want to go down the transcoding route that would be done inside of go2rtc fairly simply 

```
go2rtc:
  streams:
    camera:
      - "ffmpeg:rtsp://...#video=h264#audio=copy#hardware
```

**Reply by Bodengriller** [reply]
That was an extremely useful tip, thank you!

no problems with go2rtc with this setting:

```
##########------------go2rtc------------##########
go2rtc:
  streams:
    Parkplatz:
      - "ffmpeg:rtsp://192.168.178.40/ch0_1.h264#video=h264#hardware"
```
webrtc:
![image](https://github.com/user-attachments/assets/d10726f7-c115-49fe-b631-386ec09c49a9)
mse:
![image](https://github.com/user-attachments/assets/834c6419-cada-4730-a231-28862c78ab05)


but:
green fragments again with this settings:
```
go2rtc:
  streams:
    Parkplatz:
      - "ffmpeg:rtsp://192.168.178.40/ch0_1.h264"
```

![image](https://github.com/user-attachments/assets/18c41af3-701d-44a4-99e2-b3d7b7fcaed6)


Next try:
```
go2rtc:
  streams:
    Parkplatz:
      - "ffmpeg:rtsp://192.168.178.40/ch0_1.h264#hardware"
```
![image](https://github.com/user-attachments/assets/0e37fd60-7a68-4caf-aecc-de9232c966df)

Last try:
```
go2rtc:
  streams:
    Parkplatz:
      - "ffmpeg:rtsp://192.168.178.40/ch0_1.h264#video=h264"
```
![image](https://github.com/user-attachments/assets/aba980ff-ed60-4c1a-9f15-8e762b417a0a)


So it seems to make no difference if I use #video=h264 or "#video=h264#hardware"
Go2rtc logs don't show anything special (also when stream is green):

```
2024-07-14 21:00:09.417572088  [INFO] Preparing new go2rtc config...
2024-07-14 21:00:10.064523133  [INFO] Starting go2rtc...
2024-07-14 21:00:10.205569143  21:00:10.205 INF go2rtc version 1.8.4 linux/amd64
2024-07-14 21:00:10.206464571  21:00:10.206 INF [api] listen addr=:1984
2024-07-14 21:00:10.206775126  21:00:10.206 INF [rtsp] listen addr=:8554
2024-07-14 21:00:10.207177457  21:00:10.207 INF [webrtc] listen addr=:8555
2024-07-14 21:00:19.409347300  [INFO] Starting go2rtc healthcheck service...
```

Now I just have to find out what exactly that means :D
If I understand it correctly, go2rtc now re-encodes the stream and I could use the re-encoded stream for my records of this camera?
I'll have to read the frigate-documentation on go2rtc thoroughly again.

Of course, reencoding costs resources - I understood that. I'll have to see if my hardware can handle it, but it looks good at the moment.

Is it better to use #video=h264 or "#video=h264#hardware" if both work?
