### DISCUSSION TITLE
Deleting review items also deletes recording within retention period

### DISCUSSION THREAD

**Discussion by lin-xianming** [blakeblackshear/frigate#12449] [Report a Bug] [answered]
### Describe the problem you are having

Deleting a review item also deletes the recording for that time period, even if the recording is otherwise within the retention period.

### Steps to reproduce

1. Delete a review item
2. Find time period covered by review item is no longer available when viewing timeline

### Version

0.14.0-a4eb435

### Frigate config file

```yaml
version: 0.14
go2rtc:
  streams:
    camera1:
      - rtsp://user:pass@camera1/stream1
    camera2:
      - rtsp://user:pass@camera2/stream1
    camera3:
      - rtsp://user:pass@camera3/stream1
    camera4:
      - rtsp://user:pass@camera4/stream1
    camera5:
      - rtsp://user:pass@camera5/stream1
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camera1url/stream1
          roles:
            - record
        - path: rtsp://user:pass@camera1url/stream2
          roles:
            - detect
    onvif:
      host: camera1url
      port: 2020
      user: user
      password: pass
    motion:
      mask:
        - 0.36,0,0.36,0.07,0,0.07,0,0
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camera2url/stream1
          roles:
            - record
        - path: rtsp://user:pass@camera2url/stream2
          roles:
            - detect
    onvif:
      host: camera2url
      port: 2020
      user: user
      password: pass
    motion:
      mask:
        - 0.36,0,0.36,0.07,0,0.07,0,0
    zones:
      camera2-stuff:
        coordinates: 0.362,0.517,0.471,0.672,0.753,0.528,0.884,0.598,0.984,0.497,0.983,0.106,0.753,0.092,0.359,0.114
    review:
      alerts:
        required_zones: camera2-stuff
  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camera3url/stream1
          roles:
            - record
        - path: rtsp://user:pass@camera3url/stream2
          roles:
            - detect
    onvif:
      host: camera3url
      port: 2020
      user: user
      password: pass
    motion:
      mask:
        - 0.36,0,0.36,0.05,0,0.05,0,0
    detect:
      enabled: False
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camera4/stream1
          roles:
            - record
        - path: rtsp://user:pass@camera4/stream2
          roles:
            - detect
    onvif:
      host: camera4
      port: 2020
      user: user
      password: pass
    motion:
      mask:
        - 0.36,0,0.36,0.05,0,0.05,0,0
    detect:
      enabled: False
  camera5:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camera5/stream1
          roles:
            - record
        - path: rtsp://user:pass@camera5/stream2
          roles:
            - detect
    onvif:
      host: camera5
      port: 2020
      user: user
      password: pass
    motion:
      mask:
        - 0.36,0,0.36,0.05,0,0.05,0,0
    detect:
      enabled: False
record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: True
  quality: 90
  retain:
    default: 14
detectors:
  openvino:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
ffmpeg:
  hwaccel_args: preset-vaapi
mqtt:
  enabled: False
```

### Relevant log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

.
