### DISCUSSION TITLE
nvidia p400

### DISCUSSION THREAD

**Discussion by nathanmuntz** [blakeblackshear/frigate#12468] [Hardware Acceleration Support]
### Describe the problem you are having

i dont know what is wrong but my camera isnt working with it

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
detectors:
  coral:
    type: edgetpu
    device: usb
#Global Object Settings
objects:
  track:
    - person
go2rtc:
  streams:
    Frontdoor:
      - rtsp://192.168.0.141:554/11
cameras:
  Frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - /dev/bus/usb:/dev/bus/usb
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/frigate/config:/config
    #  - /cctv_clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "myPassword"
      NVIDIA_VISIBLE_DEVICES: all # add this variable as well (or adjust it as needed when you have multiple GPUs)
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video # probably not needed
```

### Relevant log output

```shell
2024-07-16 01:45:22.251869679  [INFO] Preparing Frigate...
2024-07-16 01:45:22.268181233  [INFO] Starting Frigate...
2024-07-16 01:45:23.781722452  [2024-07-16 01:45:23] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-16 01:45:26.992268749  [2024-07-16 01:45:26] peewee_migrate.logs            INFO    : Starting migrations
2024-07-16 01:45:26.997791005  [2024-07-16 01:45:26] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-07-16 01:45:27.003381502  [2024-07-16 01:45:27] frigate.app                    INFO    : Recording process started: 1753
2024-07-16 01:45:27.007850285  [2024-07-16 01:45:27] frigate.app                    INFO    : go2rtc process pid: 89
2024-07-16 01:45:27.035056816  [2024-07-16 01:45:27] detector.coral                 INFO    : Starting detection process: 1762
2024-07-16 01:45:27.035433631  [2024-07-16 01:45:27] frigate.app                    INFO    : Output process started: 1763
2024-07-16 01:45:27.051544220  [2024-07-16 01:45:27] frigate.app                    INFO    : Camera processor started for Frontdoor: 1773
2024-07-16 01:45:27.057337334  [2024-07-16 01:45:27] frigate.app                    INFO    : Capture process started for Frontdoor: 1775
2024-07-16 01:45:30.059157880  [2024-07-16 01:45:27] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-07-16 01:45:30.064655475  [2024-07-16 01:45:30] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-07-16 01:45:31.201883376  [2024-07-16 01:45:31] frigate.video                  ERROR   : Frontdoor: Unable to read frames from ffmpeg process.
2024-07-16 01:45:31.202342397  [2024-07-16 01:45:31] frigate.video                  ERROR   : Frontdoor: Unable to read frames from ffmpeg process.
2024-07-16 01:45:31.203078752  [2024-07-16 01:45:31] frigate.video                  ERROR   : Frontdoor: Unable to read frames from ffmpeg process.
24-07-16 01:45:31.443553379  [2024-07-16 01:45:31] frigate.video                  ERROR   : Frontdoor: ffmpeg process is not running. exiting capture thread...
2024-07-16 01:45:47.077989008  [2024-07-16 01:45:47] watchdog.Frontdoor             ERROR   : Ffmpeg process crashed unexpectedly for Frontdoor.
2024-07-16 01:45:47.078081572  [2024-07-16 01:45:47] watchdog.Frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-07-16 01:45:47.078184378  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : [h264 @ 0x651798e908c0] Cannot load libnvcuvid.so.1
2024-07-16 01:45:47.078271558  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : [h264 @ 0x651798e908c0] Failed loading nvcuvid.
2024-07-16 01:45:47.078771016  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : [h264 @ 0x651798e908c0] Failed setup for format cuda: hwaccel initialisation returned error.
2024-07-16 01:45:47.078775031  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
2024-07-16 01:45:47.078777033  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : Error reinitializing filters!
2024-07-16 01:45:47.078779005  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : Failed to inject frame into filter network: Function not implemented
2024-07-16 01:45:47.078780798  [2024-07-16 01:45:47] ffmpeg.Frontdoor.detect        ERROR   : Error while processing the decoded data for stream #0:0
```

### FFprobe output from your camera

```shell
[1] 53399
[2] 53400
root@docker-frigate:~# ffprobe rtsp://192.168.0.141:554/11                                                                   
ffprobe version 5.1.5-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://192.168.0.141:554/11':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

C6F0SgZ3N0PlL2

### Any other information that may be helpful
[
![1](https://github.com/user-attachments/assets/392bede6-c110-4574-9d54-285e6cc28030)
](url)

**Comment by NickM-27** [comment]
> [h264 @ 0x651798e908c0] Cannot load libnvcuvid.so.1

See https://github.com/blakeblackshear/frigate/issues/5166 and related issues

**Comment by nathanmuntz** [comment]
ok i got that fixed now my coral isnt working here is the logs for it 
   

2024-07-16 11:28:01.617266974  [INFO] Preparing Frigate...
2024-07-16 11:28:01.629441550  [INFO] Starting Frigate...
2024-07-16 11:28:03.173610971  [2024-07-16 11:28:03] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-16 11:28:10.923850362  [2024-07-16 11:28:10] peewee_migrate.logs            INFO    : Starting migrations
2024-07-16 11:28:10.929599612  [2024-07-16 11:28:10] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-07-16 11:28:10.937876295  [2024-07-16 11:28:10] frigate.app                    INFO    : Recording process started: 1769
2024-07-16 11:28:10.941792425  [2024-07-16 11:28:10] frigate.app                    INFO    : go2rtc process pid: 91
2024-07-16 11:28:10.969491816  [2024-07-16 11:28:10] frigate.app                    INFO    : Output process started: 1779
2024-07-16 11:28:10.986118007  [2024-07-16 11:28:10] frigate.app                    INFO    : Camera processor started for Frontdoor: 1785
2024-07-16 11:28:10.987224693  [2024-07-16 11:28:10] frigate.app                    INFO    : Camera processor started for OurBackYard: 1786
2024-07-16 11:28:11.007296115  [2024-07-16 11:28:10] frigate.app                    INFO    : Camera processor started for InsideFrontPorch: 1787
2024-07-16 11:28:11.007300895  [2024-07-16 11:28:11] frigate.app                    INFO    : Capture process started for Frontdoor: 1792
2024-07-16 11:28:11.019007665  [2024-07-16 11:28:11] frigate.app                    INFO    : Capture process started for OurBackYard: 1797
2024-07-16 11:28:11.019011697  [2024-07-16 11:28:11] frigate.app                    INFO    : Capture process started for InsideFrontPorch: 1799
2024-07-16 11:28:36.349211163  [2024-07-16 11:28:10] detector.coral                 INFO    : Starting detection process: 1778
2024-07-16 11:28:36.349468776  Process detector:coral:
2024-07-16 11:28:36.350098816  [2024-07-16 11:28:10] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-07-16 11:28:36.350198027  [2024-07-16 11:28:36] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2024-07-16 11:28:36.350907591  Traceback (most recent call last):
2024-07-16 11:28:36.350922616    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2024-07-16 11:28:36.350924450      delegate = Delegate(library, options)
2024-07-16 11:28:36.350926157    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2024-07-16 11:28:36.350927874      raise ValueError(capture.message)
2024-07-16 11:28:36.350954971  ValueError
2024-07-16 11:28:36.350956567  
2024-07-16 11:28:36.350957965  During handling of the above exception, another exception occurred:
2024-07-16 11:28:36.350959076  
2024-07-16 11:28:36.350960344  Traceback (most recent call last):
2024-07-16 11:28:36.350989637    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-07-16 11:28:36.350991335      self.run()
2024-07-16 11:28:36.350992772    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-07-16 11:28:36.350994076      self._target(*self._args, **self._kwargs)
2024-07-16 11:28:36.350995511    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-07-16 11:28:36.350996945      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-07-16 11:28:36.351048014    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-07-16 11:28:36.351049920      self.detect_api = create_detector(detector_config)
2024-07-16 11:28:36.351051374    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-07-16 11:28:36.351052570      return api(detector_config)
2024-07-16 11:28:36.351054018    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 41, in __init__
2024-07-16 11:28:36.351055491      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2024-07-16 11:28:36.351056993    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2024-07-16 11:28:36.351059583      raise ValueError('Failed to load delegate from {}\n{}'.format(
2024-07-16 11:28:36.351061169  ValueError: Failed to load delegate from libedgetpu.so.1.0
2024-07-16 11:28:36.351062281

**Reply by NickM-27** [reply]
what is the docker compose now and what kind of coral is it

**Comment by nathanmuntz** [comment]
its a usb 

```
ersion: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    runtime: nvidia
    shm_size: "512mb" # update for your cameras based on calculation above
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - /dev/bus/usb:/dev/bus/usb
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/frigate/config:/config
    #  - /cctv_clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "Wolfie12271985"
      NVIDIA_VISIBLE_DEVICES: all # add this variable as well (or adjust it as needed when you have multiple GPUs)
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video # probably not needed
```
