### DISCUSSION TITLE
Annoying problem when unable to configure Intel CPU hardware acceleration via docker

### DISCUSSION THREAD

**Discussion by Pureaznangel** [blakeblackshear/frigate#12466] [General]
I tried for a few days but could not turn on hardware acceleration. Following is my configuration:

I need to  use QuickSync, preset-vaapi or preset-intel-qsv-h265 but seem failed, the Frigate will restart continously if I set it different to "auto". Please help

![image](https://github.com/user-attachments/assets/0101994b-dbc6-47a8-96bf-f7b84e30d94a)

![image](https://github.com/user-attachments/assets/adfcbee5-dccd-4b82-a5d2-ff8cb652317e)

![image](https://github.com/user-attachments/assets/67726672-4829-4036-8871-51f2e8b1868a)

![image](https://github.com/user-attachments/assets/a6da100f-e480-4aa1-b7e8-8b079517b091)

**Comment by NickM-27** [comment]
If auto isn't working then the hardware isn't available. What is your docker compose

**Reply by Pureaznangel** [reply]
This is my docker editor. I don't think a gaming laptop with a dedicated GPU and 11th Gen Intel CPU wouldn't support these hardware acceleration technologies.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - E:\docker\frigate:/config
      - E:\docker\frigate\storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

and I've tried this, too.

![image](https://github.com/user-attachments/assets/ac3f94de-b4c9-48a8-982b-852c34586df9)
