### DISCUSSION TITLE
After a few hours running: Unable to keep up with recording segments in cache

### DISCUSSION THREAD

**Discussion by Ayuus** [blakeblackshear/frigate#12465] [General Support]
### Describe the problem you are having

Since Frigate 0.14, detection stops working after a few hours (less than 24 in my case). After starting, everything is running OK, but after a day of continous recording with 3 camera's (2x4MP, 1x8MP) on my Synology D224+, the log is full of messages about "Unable to keep up with recording segments in cache", Coral inference speed is 96ms, Detection fps  is 0.
I have not noticed this with 0.13.2.

### Steps to reproduce

Start Frigate 0.14 with config as stated below and wait 24 hours.

### Version

0.14.0-beta3 and beta4

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.10 #homeassistant.local
  port: 1883
#  port: 8883
#  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: false
  user: user
  password: password
  
ui:
  time_format: 24hour

#logger:
#  default: info
#  logs:
#    frigate.mqtt: info
#    frigate.ptz.onvif: debug

ffmpeg:
  hwaccel_args: preset-vaapi
  
detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog
#  filters:
#    person:
#      threshold: 0.75
#    cat:
#      threshold: 0.75
#    dog:
#      threshold: 0.75

detect:
  max_disappeared: 5

#motion:
#   lightning_threshold: 0.9

birdseye:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

audio:
  # geen audio events, events zijn wel inclusief audio
  enabled: false
  min_volume: 500
  listen:
    - speech
    - yell
    - scream
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event
      threshold: 0.8
    yell:
      threshold: 0.8
    scream:
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

go2rtc:
  streams:
    buitencamera_zijgevel:
      - rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps
    buitencamera_achterzijde:
      - rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=2 #720p/25fps
    buitencamera_voordeur:
      - rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps

cameras:
  buitencamera_voordeur:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=2   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.42:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record
#    onvif: # necessary for ptz handling via frigate, werkt niet
#      host: 192.168.4.42
#      port: 80
#      user: user
#      password: password

  buitencamera_zijgevel:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=2     #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.40:554/cam/realmonitor?channel=1&subtype=0     #4MP25fps
          roles:
            - record
    motion:
      mask:
        - 843,261,1100,720,1280,720,1280,0,868,0,484,0,493,267
    zones:
      grind:
        coordinates: 505,266,912,250,1148,720,509,720
    snapshots:
      required_zones:
        - grind
    review:
      alerts:
        required_zones:
          - grind
#    onvif: # necessary for ptz handling via frigate, werkt niet
#      host: 192.168.4.40
#      port: 80
#      user: user
#      password: password

          
  buitencamera_achterzijde:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=1   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://user:password@192.168.4.41:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record
#    onvif: # necessary for ptz handling via frigate, werkt niet
#      host: 192.168.4.41
#      port: 80
#      user: user
#      password: password

#  ptz_achterzijde: # oude ptz camera
#    ffmpeg:
#      inputs:
#      - path: rtsp://mpfc:wr6etr@192.168.1.104:554/stream=0
#        roles:
#        - audio
#        - detect
#        - record
#    onvif: # necessary for ptz handling via frigate
#      host: 192.168.1.104
#      port: 8899
#      user: mpfc
#      password: password
#      autotracking:
#        enabled: true
#        zooming: relative
#    motion:
#      mask:
#      - 1738,1017,1213,364   
version: 0.14
```

### Relevant log output

```shell
Log is spammed with messages:

Unable to keep up with recording segments in cache for buitencamera_achterzijde. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

EmpireTech/Dahua

### Any other information that may be helpful

Continuous recording was no problem with Frigate 0.13.2. Live images still work real-time, Synology CPU is higher than normal (45% vs 28%)
