### DISCUSSION TITLE
[Support]: 15 seconds of video missing from recordings

### DISCUSSION THREAD

**Discussion by tslytsly** [blakeblackshear/frigate#12467] [General Support] [answered]
### Describe the problem you are having

I'm noticing that every now and then, 14-15 seconds of video will just be missing from a recording.
For example, watching the timestamp on the camera feed I see the time jump from 10:38:16 to 10:38:30.
I have got a packet capture of one of these events and the stream from the camera continues with no errors, no TCP resets or latency.
I understand that it may be an error in my config or my hardware, but there are no errors in the logs at all and the captures look clean to me.

Any help is appreciated, thank you in advance.

### Steps to reproduce

Configure go2rtc stream for camera (FoH in my case).
Use that stream as an input for your camera.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
# logger:
#   default: info
#   logs:
#     frigate.record: debug
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  host: <removed>
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

record:
  enabled: True
  expire_interval: 30
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 10
      mode: motion
      objects:
        dog: 1
        cat: 1
        bird: 1

detectors:
  coral:
     type: edgetpu
     device: usb

birdseye:
  enabled: False
  mode: objects

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream # check if udp can be used with cameras, may improve performance.
  output_args:
    # record: preset-record-generic-audio-copy
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    FoH: "ffmpeg:rtsp://zman:{FRIGATE_RTSP_PASSWORD}@<removed>:554#hardware=cuda"
    FoH_sub: "ffmpeg:FoH#video=h264/cuda#audio=copy#audio=opus#width=1280#hardware=cuda"
    Back_Garden: "ffmpeg:rtsp://zman:{FRIGATE_RTSP_PASSWORD}@<removed>:554#hardware=cuda"
    Back_Garden_sub: "ffmpeg:Back_Garden#video=h264/cuda#audio=copy#audio=opus#width=1280#hardware=cuda"
    #Doorbell: "ffmpeg:http://<removed>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    Doorbell: "ffmpeg:rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<removed>:554#video=copy#audio=copy#audio=opus#hardware=cuda"
  

  webrtc:
    candidates:
    - <removed>:8555
    - stun:8555

cameras:
  Doorbell:
    enabled: True
    webui_url: https://<removed>/
    ui:
      order: 1
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Doorbell
        roles:
        - record
        - audio
        - detect
    record: # <----- Enable recording
      enabled: True
    audio:
      enabled: True
    detect:
      enabled: True
      fps: 5
      width: 960
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: True
    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - bicycle
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
      # - car
      # - motorcycle
      # - suitcase
      # - skateboard
        cat:
          mask:
          - 0,720,341,720
    motion:
      # # FOR 720-RES Stream!!!
      mask:
      - 456,374,648,407,563,288,595,223,702,160,809,180,840,347,760,390,838,444,895,388,920,450,798,528,606,533,450,443
      - 0,720,0,390,339,430,335,720
      - 0,0,960,0,960,314,852,329,726,279,567,336,484,362,0,341
    zones:
      front_path:
        coordinates: 791,539,960,645,960,720,478,720,408,477,449,460
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - cat
        - dog
      kitchen_window:
        coordinates: 960,594,960,429,801,573
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - dog
      road:
        coordinates: 49,398,532,383,515,364,0,378
      next_door:
        coordinates: 0,720,302,720,332,434,0,398
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - dog
      drive:
        coordinates: 629,434,960,451,928,377,761,381,674,408
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - dog

  Front_of_House: # <------ Name the camera
    enabled: True
    webui_url: https://<removed>/
    ui:
      order: 2
    live:
      stream_name: FoH_sub
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/FoH
        roles:
        - record
        - audio
        - detect
      hwaccel_args: preset-nvidia-h265
    record: # <----- Enable recording
      enabled: True
    audio:
      enabled: True
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: True
    objects:
      track:
      - person
      - dog
      - bicycle
      # - motorcycle
      # - suitcase
      # - skateboard
      
      # FOR 720-RES STREAM!!!
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
        cat:
          max_area: 25000
          mask: 1168,720,1100,545,1199,377,1057,247,631,315,562,109,226,104,0,720
        #car:
         # mask:
         # - 0,720,1280,720,1280,263,972,58,205,27,244,72,92,126
          #- 114,0,205,27,239,86,0,79,0,24
    motion:
      threshold: 30
      contour_area: 15
      mask:
      - 0,70,112,54,242,71,135,593,0,620
      - 628,291,819,273,937,273,1047,236,1191,384,1219,309,940,63,839,35,733,35,536,65
      - 1280,258,1280,0,1001,0,1045,68
    zones:
      drive:
        coordinates: 173,514,565,523,599,304,627,277,519,132,246,141
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - dog
      leighs_path:
        coordinates: 940,112,1223,343,1196,381,1104,533,1171,720,1280,720,1245,639,1280,277,972,55
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
      bins:
        coordinates: 
          662,495,620,644,820,657,857,720,1173,720,1104,558,1121,471,1185,375,1042,238,622,305
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
      drive_steps:
        coordinates: 621,720,562,520,163,523,0,720
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - dog
      road:
        coordinates: 0,81,546,55,585,31,958,45,991,0,937,0,0,0
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
        - person
        - dog

  Back_Garden: # <------ Name the camera
    enabled: True
    webui_url: https://<removed>/
    ui:
      order: 3
    live:
      stream_name: Back_Garden_sub
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Back_Garden
        roles:
        - record
        - audio
        - detect
      hwaccel_args: preset-nvidia-h265
    record: # <----- Enable recording
      enabled: True
    audio:
      enabled: True
      listen:
      - bark
      - fire_alarm
      - scream
      - yell
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: True
    objects:
      track:
      - person
      - cat
      - dog
    zones:
      lower_patio:
        coordinates: 51,255,426,205,577,299,242,485,239,521,134,566
      living_room_window:
        coordinates: 437,720,0,720,0,139,135,551,253,500
      flower_bed:
        coordinates: 421,720,1147,720,1237,355,785,221,257,486
      shed:
        coordinates: 745,159,739,0,531,52,451,144,530,190
      top_patio:
        coordinates: 1191,355,1215,315,1222,116,750,25,739,152,563,179
      nans_fence:
        coordinates: 1280,720,1170,720,1234,261,1235,122,1280,122
      leighs_fence:
        coordinates: 35,163,554,40,566,0,35,0
    motion:
      mask:
      - 517,98,609,62,711,38,748,0,0,0,0,112,142,83,252,112
      - 887,84,983,260,916,426,859,720,1196,720,1259,265,1235,120,1280,125,1280,0,743,0,755,65
```

### Relevant log output

```shell
NONE (there are no logs in frigate or go2rtc logs at all for this day)
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Reolink RLC-1224A

### Any other information that may be helpful

I know the issues that some have with Reolink cameras, but I have put a lot of work into tweaking the settings to make them stable. I don't have any other issues with recordings and live streaming them through Frigate or HA works flawlessly.
They are all on the latest firmware: v3.1.0.2174_23050816
