### DISCUSSION TITLE
Cannot connect to camera in subnet

### DISCUSSION THREAD

**Discussion by ReneXB12X** [blakeblackshear/frigate#12478] [Config Support]
### Describe the problem you are having

Camera on ethernet(eth0) of Raspberry pi 3B+ (wlan0) 
camera= 10.42.0.241  wlan0=192.168.2.28
routed bridge to share wifi to ethernet (works ok)
can ping to the camera from RPI and can view RTPS stream with VLC on a PC in the same subnet 
Frigate installed on the RPI cannot connect to the RTPS stream in the subnet.
If the camera is on the same rang as the RPI it works perfect.
any suggestions?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration

cameras:
  Camera_1: #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://admin@10.42.0.241:554/ch01.264 #The Stream you want to monitor
          roles:
            - detect
            
    detect:
      enabled: true # Detection is disabled
      width: 1280 # The Cameras resolution
      height: 720 # The Cameras resolution
    snapshots:
      enabled: true
    record:
      enabled: true
```

### Relevant log output

```shell
no connection
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)
