### DISCUSSION TITLE
[Config Support]: Audio from other Camera

### DISCUSSION THREAD

**Discussion by gomble** [blakeblackshear/frigate#12475] [Config Support]
### Describe the problem you are having

I want to record the audio from another camera for a camera without audio support.
I added:

        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.12:554/ISAPI/Streaming/channels/102/
          roles:
            - audio

But that did not work.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: XXX.XXX.XXX.XXX
  topic_prefix: frigate
  client_id: frigate
  user: XXX
  password: XXXX
  stats_interval: 60

objects:
  track:
    - person
    - cat
    - dog


ffmpeg:
  hwaccel_args: -c:v h264_qsv

record:
  enabled: True
  events:
    pre_capture: 4
    post_capture: 4
    objects:
      - person
      - cat
    retain:
      default: 9

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 9


cameras:
  eingangptz:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.17:554/live/0/SUB
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.17:554/live/0/MAIN
          roles:
            - record
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.12:554/ISAPI/Streaming/channels/102/
          roles:
            - audio
    detect:
      width: 800
      height: 448
      fps: 5
    objects:
      filters:
        person:
            min_score: 0.72
            threshold: 0.65
  gartenptz:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.16:554/live/0/SUB
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.16:554/live/0/MAIN
          roles:
            - record
    detect:
      width: 800
      height: 448
      fps: 5
    motion:
      mask:
        - 146,39,274,0,0,0,0,84
        - 800,0,800,35,497,39,496,0
    objects:
      filters:
        cat:
          min_score: 0.3
          threshold: 0.45
        dog:
          min_score: 0.3
          threshold: 0.45
        person:
          min_score: 0.6
          threshold: 0.7
  parkplatzptz:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.15:554/live/0/SUB
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.15:554/live/0/MAIN
          roles:
            - record
    detect:
      width: 800
      height: 448
      fps: 5
      stationary:
          interval: 10

    record:
      events:
        required_zones:
          - park
          - strasse
    snapshots:
      required_zones:
        - park
        - strasse
    zones:
      park:
        coordinates: 252,448,800,448,800,154,543,130,612,406,287,409,315,142,267,144,247,229,50,164,0,149,0,210,151,294
      strasse:
        coordinates: 0,0,641,0,776,110,573,102,193,103,0,105
      park-nachts:
        coordinates: 311,448,800,448,800,126,522,122,596,325,446,416,283,367,330,116,285,115,247,363,0,322,140,124,0,133,0,382,171,376,209,416,306,417
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
            min_score: 0.4
            threshold: 0.62
        cat:
            min_score: 0.4
            threshold: 0.6
        dog:
            min_score: 0.4
            threshold: 0.6
    motion:
        mask:
          - 671,78,594,322,660,328,750,108,800,160,800,0,621,0,623,44
          - 0,448,307,448,303,419,226,408,134,285,201,241,199,221,0,219
  garagehinten:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX.XXX.XXX.13:554/12
          roles:
            - detect
        - path: rtsp://XXXX.XXX.XXX.13:554/11
          roles:
            - record
    detect:
      width: 640
      height: 352
      fps: 5
    motion:
      mask:
        - 0,0,0,352,120,352,218,317,216,189,186,149,201,61,164,43,159,0
        - 491,0,493,21,640,22,640,0
        - 640,352,640,107,479,121,462,191,576,352
    objects:
      filters:
        cat:
          min_score: 0.3
          threshold: 0.45
        person:
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
  klingel:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.12:554/ISAPI/Streaming/channels/102/
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.12:554/ISAPI/Streaming/channels/101/
          roles:
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    record:
      events:
        required_zones:
          - vor_der_tuer
    snapshots:
      required_zones:
        - vor_der_tuer
    zones:
        vor_der_tuer:
          coordinates: 0,576,0,278,22,342,64,291,304,304,313,376,399,387,453,358,490,326,495,138,704,0,704,576
    motion:
      mask:
        - 0,0,704,0,704,140,518,118,418,115,355,129,362,491,324,493,318,202,182,172,0,256
        - 0,576,349,576,342,527,216,534,204,459,0,401
        - 704,546,704,576,586,576,583,542
    objects:
      filters:
        person:
          min_score: 0.67
          threshold: 0.45
  garteneingang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://XXX:XXX!@XXXX.XXX.XXX.14:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
          input_args: preset-rtsp-blue-iris
          roles:
            - detect
        - path: rtsp://XXX:XXX!@XXXX.XXX.XXX.14:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
          input_args: preset-rtsp-blue-iris
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    record:
      events:
        required_zones:
          - terasse
    snapshots:
      required_zones:
        - terasse
    zones:
      terasse:
        coordinates: 441,360,234,360,449,74,545,104
    motion:
        mask:
          - 0,0,116,0,175,170,96,210,57,360,0,360
          - 640,360,463,360,488,269,422,244,446,178,502,189,543,28,467,0,640,0
    objects:
      filters:
        cat:
          min_score: 0.3
          threshold: 0.45
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
birdseye:
  enabled: False


detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
cameras:
  eingangptz:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.17:554/live/0/SUB
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.17:554/live/0/MAIN
          roles:
            - record
        - path: rtsp://XXXX:XXXX@XXXX.XXX.XXX.12:554/ISAPI/Streaming/channels/102/
          roles:
            - audio
    detect:
      width: 800
      height: 448
      fps: 5
    objects:
      filters:
        person:
            min_score: 0.72
            threshold: 0.65
```

### Frigate stats

```json
{
    "cameras": {
        "eingangptz": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 724,
            "detection_enabled": 1,
            "detection_fps": 2.6,
            "ffmpeg_pid": 736,
            "pid": 712,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "garagehinten": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 754,
            "detection_enabled": 1,
            "detection_fps": 15.1,
            "ffmpeg_pid": 765,
            "pid": 717,
            "process_fps": 4.9,
            "skipped_fps": 0
        },
        "garteneingang": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 764,
            "detection_enabled": 1,
            "detection_fps": 14.5,
            "ffmpeg_pid": 774,
            "pid": 723,
            "process_fps": 4.9,
            "skipped_fps": 0
        },
        "gartenptz": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 730,
            "detection_enabled": 1,
            "detection_fps": 19.3,
            "ffmpeg_pid": 743,
            "pid": 713,
            "process_fps": 4.9,
            "skipped_fps": 0
        },
        "klingel": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 758,
            "detection_enabled": 1,
            "detection_fps": 11.1,
            "ffmpeg_pid": 770,
            "pid": 721,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "parkplatzptz": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 744,
            "detection_enabled": 1,
            "detection_fps": 15.5,
            "ffmpeg_pid": 752,
            "pid": 714,
            "process_fps": 4.7,
            "skipped_fps": 0.1
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "79": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "/config/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "102": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "104": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "4.5",
            "cpu_average": "4",
            "mem": "1.1"
        },
        "121": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "147": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "152": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "160": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "167": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "305": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "313": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "314": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "318": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "331": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "344": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "350": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "351": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "352": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "353": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "687": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "689": {
            "cmdline": "frigate.recording_manager",
            "cpu": "8.4",
            "cpu_average": "5",
            "mem": "0.5"
        },
        "698": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "699": {
            "cmdline": "frigate.detector.coral",
            "cpu": "50.3",
            "cpu_average": "19",
            "mem": "0.4"
        },
        "701": {
            "cmdline": "frigate.output       ",
            "cpu": "1.6",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "707": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x448 -i pipe: -f mpegts -s 1285x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "3.1",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "708": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x448 -i pipe: -f mpegts -s 1285x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "709": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x448 -i pipe: -f mpegts -s 1285x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "711": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "712": {
            "cmdline": "frigate.process:eingangptz",
            "cpu": "2.3",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "713": {
            "cmdline": "frigate.process:gartenptz",
            "cpu": "9.6",
            "cpu_average": "3",
            "mem": "0.5"
        },
        "714": {
            "cmdline": "frigate.process:parkplatzptz",
            "cpu": "8.1",
            "cpu_average": "4",
            "mem": "0.4"
        },
        "716": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "717": {
            "cmdline": "frigate.process:garagehinten",
            "cpu": "7.7",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "721": {
            "cmdline": "frigate.process:klingel",
            "cpu": "5.6",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "722": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "723": {
            "cmdline": "frigate.process:garteneingang",
            "cpu": "6.7",
            "cpu_average": "3",
            "mem": "0.4"
        },
        "724": {
            "cmdline": "frigate.capture:eingangptz",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "730": {
            "cmdline": "frigate.capture:gartenptz",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "736": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.38:81/EingangPTZ?decode=-1 -r 5 -vf fps=5,scale=800:448 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.4",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "743": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.16:554/live/0/SUB -r 5 -vf fps=5,scale=800:448 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.4",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "744": {
            "cmdline": "frigate.capture:parkplatzptz",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "752": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.15:554/live/0/SUB -r 5 -vf fps=5,scale=800:448 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.5",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "754": {
            "cmdline": "frigate.capture:garagehinten",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "755": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.38:81/EingangPTZ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/eingangptz@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "758": {
            "cmdline": "frigate.capture:klingel",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "760": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.16:554/live/0/MAIN -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/gartenptz@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "764": {
            "cmdline": "frigate.capture:garteneingang",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "765": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.59.13:554/12 -r 5 -vf fps=5,scale=640:352 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.2",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "769": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.15:554/live/0/MAIN -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/parkplatzptz@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.4",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "770": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.12:554/ISAPI/Streaming/channels/102/ -r 5 -vf fps=5,scale=704:576 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.9",
            "cpu_average": "3",
            "mem": "0.1"
        },
        "774": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.14:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.1",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "775": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.59.13:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garagehinten@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "780": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.14:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garteneingang@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.9",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "781": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.59.12:554/ISAPI/Streaming/channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/klingel@%Y%m%d%H%M%S%z.mp4",
            "cpu": "3.8",
            "cpu_average": "3",
            "mem": "0.1"
        },
        "3653": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 78.1,
    "detectors": {
        "coral": {
            "detection_start": 1721134121.726136,
            "inference_speed": 12.15,
            "pid": 699
        }
    },
    "gpu_usages": {
        "intel-qsv": {
            "gpu": "0.56%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 89
        },
        "logger": {
            "pid": 687
        },
        "recording": {
            "pid": 689
        }
    },
    "service": {
        "last_updated": 1721134122,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 52.3,
                "mount_type": "tmpfs",
                "total": 64,
                "used": 11.7
            },
            "/media/frigate/clips": {
                "free": 8929.8,
                "mount_type": "ext4",
                "total": 50088.5,
                "used": 38582.7
            },
            "/media/frigate/recordings": {
                "free": 8929.8,
                "mount_type": "ext4",
                "total": 50088.5,
                "used": 38582.7
            },
            "/tmp/cache": {
                "free": 934.7,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 19
            }
        },
        "temperatures": {},
        "uptime": 626,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Proxmox

### Install method

Docker CLI

### Object Detector

Coral
