### DISCUSSION TITLE
Dahua RESTful commands

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#12483] [General]
Hi,

My Dahua camera always returns a 401 when trying to run a RESTful command, including the RESTful command for day and night modes in the Dahua integration.  Has anybody come across this issue before?

**Comment by NickM-27** [comment]
you should provide more information about what you are using to run this

**Reply by jakeycrx** [reply]
In HASS, there is a Dahua integration with RESTful commands to change day and night modes.  They just return a 401:

![image](https://github.com/user-attachments/assets/84823bca-78ef-4a1a-89dc-b9f923ecd2cc)

I also tried my own RESTful command to try and pull some PTZ data with the same result
```
rest_command:
  dahua_ptz:
    url: http://192.168.1.108/cgi-bin/ptz.cgi?action=getStatus
    method: GET
    verify_ssl: false
    username: ****
    password: ****
    payload: ""
```
