### DISCUSSION TITLE
[Detector Support]: Labelmap index issue on TensorRT

### DISCUSSION THREAD

**Discussion by WarrenSchultz** [blakeblackshear/frigate#12495] [Detector Support]
### Describe the problem you are having

I saw this mentioned a few places in the repo without a solid answer what was going on, so I apologize if I missed somewhere that this was already discovered. 

I'm running 1.4 Beta 4 on WSL2/Ubuntu 22.04/Docker-CE/NVIDIA Container Toolkit (latest), with 2x RTX 3060 GPUs.

I'd been beating my head up against the wall why detections were out of whack (dog detected as cat, but person detected fine, for example) for TensorRT, but seemed to be working correctly with the same model using CPU detection.

Turns out, there's something wrong with how the labelmap is being handled in the TRT implementation.

I enabled all detections, pulled up a browser with google image search, and went down the list. 
Everything seems fine until you get to street sign, and then it loses its mind, and can't lock on to anything. Subsequent labels are all off by one. Stop signs are IDed as street signs, cats as birds, dogs, as cats, etc.

### Version

0.14.0-a4eb435

### Frigate config file

```yaml
# yaml-language-server: $schema=http://127.0.0.1:5000/api/config/schema.json

mqtt:
  enabled: true
  host: homeassistant.gfgnet.home
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: wyzemqtt
  password: fdklh38vh!b
  stats_interval: 15

detectors:
  tensorrt0:
    type: tensorrt
    device: 1
  tensorrt1:
    type: tensorrt
    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

cameras:
  V3TestCamBlack:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://wyze-bridge:8554/v3testnew
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.721,0.986,0.984,0.988,0.985,0.933,0.721,0.931
  BackDeckCam:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://wyze-bridge:8554/back-deck-cam
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.717,0.98,0.979,0.982,0.984,0.937,0.716,0.931
objects:
  track:
    # - person
    # - car
    # - bicycle
    # - bird
    # - dog
    # - cat
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - car
    - boat
    - traffic light
    - fire hydrant
    - street sign
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - hat
    - backpack
    - umbrella
    - shoe
    - eye glasses
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - plate
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - mirror
    - dining table
    - window
    - desk
    - toilet
    - door
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - blender
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
    - hair brush
  # filters:
  #   person:
  #     # min_area: 50
  #     # max_area: 10000000
  #     min_score: 0.80
  #     threshold: 0.80 # <---- percentage
  #   car:
  #     # min_area: 5000
  #     # max_area: 100000
  #     min_score: 0.80
  #     threshold: 0.90 # <---- percentage
  #   bicycle:
  #     # min_area: 500
  #     # max_area: 100000
  #     min_score: 0.80
  #     threshold: 0.90 # <---- percentage
  #   bird:
  #     # min_area: 500
  #     # max_area: 100000
  #     min_score: 0.80
  #     threshold: 0.90 # <---- percentage
  #   dog:
  #     # min_area: 1000       
  #     # max_area: 500000
  #     min_score: 0.85
  #     threshold: 0.95 # <---- percentage
  #   # cat:
  #   #   min_area: 100
  #   #   max_area: 20000
  #   #   min_score: 0.85
  #   #   threshold: 0.96 # <---- percentage

record:
  enabled: false
  retain:
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - bicycle
      - bird
      - cat
      - dog

# Include all cameras by default in Birdseye view
birdseye:
  enabled: false
  mode: continuous
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    hostname: frigate
    networks:
      - securitynet
    privileged: true # this may not be necessary for all setups
    cap_add:
      - PERFMON
    restart: unless-stopped
    # image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4-tensorrt
    # image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev:/dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/warren/Docker/frigate/config:/config
      - /s/frigate_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - YOLO_MODELS=yolov7-320 # yolo7-nms-640 yolov7x-640,yolov7-w6-nms-1280,yolov7-nms-fp16-640,yolov4-p5-896,ssdlite_mobilenet_v2
    deploy:
      resources:
          reservations:
              devices:
              - driver: nvidia
                device_ids: ["all"]
                capabilities:
                  - gpu
networks:
  securitynet:
    name: securitynet
    external: True
```

### Relevant log output

```shell
Nothing relevant here.
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

TensorRT

### Any other information that may be helpful

I think I got everything up there, but feel free to ping me for additional debugging that would be useful.

I played around with trying different built-in and custom models, but I couldn't get that to work either.

Thanks!
