### DISCUSSION TITLE
[Config Support]: Config changes randomly drops quotes

### DISCUSSION THREAD

**Discussion by sketchy989** [blakeblackshear/frigate#12493] [Config Support] [answered]
### Describe the problem you are having

I cant pinpoint when it happens but the most recent change I made was creating a motion mask and once I did that it dropped the quotes around my ffmpeg config as shown below
```
    front-yard:
    - rtsp://username:somepass@192.168.68.203:554//h264Preview_01_main
    - ffmpeg:front-yard#audio=acc
```
when it should look like
```
    front-yard:
    - rtsp://username:somepass@192.168.68.203:554//h264Preview_01_main
    - "ffmpeg:front-yard#audio=acc"
```
is this a common thing? has anyone else experienced it? Am I doing something wrong?

When this happens, the recordings saved from the above camera stop working due to an invalid format below is what I get when I attempt to run an event, and Frigate wont keep any recordings from that camera while the config is incorrect.
> The media could not be loaded, either because the server or network failed or because the format is not supported.

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.168.68.99
  user: hauser
  password: ha-pass
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    driveway:
    - "ffmpeg:http://192.168.68.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=somepass#video=copy#audio=copy#audio=aac"
    driveway_sub:
    - "ffmpeg:http://192.168.68.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=somepass"
    porch:
    - rtsp://username:somepass@192.168.68.202:554//h264Preview_01_main
    porch_sub:
    - rtsp://username:somepass@192.168.68.202:554//h264Preview_01_sub
        front-yard:
    - rtsp://username:somepass@192.168.68.203:554//h264Preview_01_main
    - "ffmpeg:front-yard#audio=acc"
    front-yard_sub:
    - rtsp://username:somepass@192.168.68.203:554//h264Preview_01_sub

cameras:
  driveway:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/driveway_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      threshold: 20
      lightning_threshold: 0.8
      improve_contrast: true
    objects:
      filters:
        person:
          mask:
          - 896,346,854,213,235,672,0,672
          - 235,672,0,672,0,482,0,377,32,258,201,69,290,91,255,233,226,369
  porch:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/porch
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/porch_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      threshold: 20
      lightning_threshold: 0.8
      improve_contrast: true
  front-yard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/front-yard
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/front-yard_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    motion:
      threshold: 20
motion detection
      lightning_threshold: 0.8
      improve_contrast: true
objects:
  track:
  - car
  - person
  - dog
  - bicycle
  - motorcycle
  - bird
  - cat
record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 15
    post_capture: 10
    objects:
    - person
    - car
    - dog
    - bicycle
    - motorcycle
    - bird
    - cat
    retain:
      default: 2
      objects:
        person: 7
        car: 5
        bicycle: 5
        motorbike: 5
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  retain:
    default: 1
    objects:
      person: 7
      car: 5
      bicycle: 5
      motorbike: 5
  quality: 100
```

### Relevant log output

```shell
2024-07-17 23:36:11.412088334  [INFO] Preparing Frigate...
2024-07-17 23:36:11.543224429  [INFO] Starting Frigate...
2024-07-17 23:36:18.939833013  [2024-07-18 09:36:18] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-07-17 23:36:38.828569486  [2024-07-18 09:36:38] peewee_migrate.logs            INFO    : Starting migrations
2024-07-17 23:36:38.832225518  [2024-07-18 09:36:38] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-07-17 23:36:38.832372523  [2024-07-18 09:36:38] frigate.app                    INFO    : Running database vacuum
2024-07-17 23:36:41.198106141  [2024-07-18 09:36:41] frigate.app                    INFO    : Recording process started: 645
2024-07-17 23:36:41.199827917  [2024-07-18 09:36:41] frigate.app                    INFO    : go2rtc process pid: 103
2024-07-17 23:36:41.222566997  [2024-07-18 09:36:41] detector.tensorrt              INFO    : Starting detection process: 654
2024-07-17 23:36:41.297345766  [2024-07-18 09:36:41] frigate.app                    INFO    : Output process started: 656
2024-07-17 23:36:41.505350185  [2024-07-18 09:36:41] frigate.app                    INFO    : Camera processor started for driveway: 713
2024-07-17 23:36:41.511836629  [2024-07-18 09:36:41] frigate.app                    INFO    : Camera processor started for porch: 715
2024-07-17 23:36:41.518541362  [2024-07-18 09:36:41] frigate.app                    INFO    : Camera processor started for front-yard: 717
2024-07-17 23:36:41.525059547  [2024-07-18 09:36:41] frigate.app                    INFO    : Capture process started for driveway: 719
2024-07-17 23:36:41.531849091  [2024-07-18 09:36:41] frigate.app                    INFO    : Capture process started for porch: 722
2024-07-17 23:36:41.539004489  [2024-07-18 09:36:41] frigate.app                    INFO    : Capture process started for front-yard: 726
2024-07-17 23:36:41.622130479  [2024-07-18 09:36:41] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 171 MiB
2024-07-17 23:36:43.209960896  [2024-07-18 09:36:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 294, GPU 253 (MiB)
2024-07-17 23:36:43.256427471  [2024-07-18 09:36:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 296, GPU 263 (MiB)
2024-07-17 23:36:43.282978895  [2024-07-18 09:36:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +171, now: CPU 0, GPU 171 (MiB)
2024-07-17 23:36:43.283331786  [2024-07-18 09:36:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 124, GPU 256 (MiB)
2024-07-17 23:36:43.283377021  [2024-07-18 09:36:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 124, GPU 264 (MiB)
2024-07-17 23:36:43.283428117  [2024-07-18 09:36:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +29, now: CPU 0, GPU 200 (MiB)
2024-07-17 23:44:51.188704174  [2024-07-18 09:44:51] frigate.http                   ERROR   : No recordings found for the requested time range
2024-07-17 23:44:51.234267096  [2024-07-18 09:44:51] frigate.http                   ERROR   : No recordings found for the requested time range
2024-07-17 23:54:48.662483213  [2024-07-18 09:54:48] frigate.http                   ERROR   : No recordings found for the requested time range
2024-07-17 23:54:48.702431713  [2024-07-18 09:54:48] frigate.http                   ERROR   : No recordings found for the requested time range
```

### Frigate stats

```json
{"cameras":{"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":719,"detection_enabled":1,"detection_fps":3.3,"ffmpeg_pid":724,"pid":713,"process_fps":5.0,"skipped_fps":0.0},"front-yard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":726,"detection_enabled":1,"detection_fps":5.4,"ffmpeg_pid":735,"pid":717,"process_fps":5.1,"skipped_fps":0.0},"porch":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.3,"capture_pid":722,"detection_enabled":1,"detection_fps":0.6,"ffmpeg_pid":729,"pid":715,"process_fps":5.3,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"21":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"22":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"35":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"36":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"37":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"38":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"49":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"50":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"94":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"95":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"96":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"103":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"6.0","cpu_average":"5","mem":"0.4"},"108":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"130":{"cmdline":"python3 -u -m frigate","cpu":"1.2","cpu_average":"1","mem":"4.6"},"134":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"169":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"195":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"234":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"275":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"309":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.4"},"345":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"393":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"429":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"462":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"492":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"601":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.9"},"645":{"cmdline":"frigate.recording_manager","cpu":"2.4","cpu_average":"2","mem":"2.2"},"653":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"654":{"cmdline":"frigate.detector.tensorrt","cpu":"10.3","cpu_average":"14","mem":"3.8"},"656":{"cmdline":"frigate.output       ","cpu":"0.6","cpu_average":"0","mem":"2.0"},"660":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"661":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"662":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"663":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"713":{"cmdline":"frigate.process:driveway","cpu":"4.9","cpu_average":"7","mem":"2.3"},"715":{"cmdline":"frigate.process:porch","cpu":"1.5","cpu_average":"2","mem":"2.2"},"717":{"cmdline":"frigate.process:front-yard","cpu":"9.1","cpu_average":"11","mem":"2.3"},"719":{"cmdline":"frigate.capture:driveway","cpu":"1.0","cpu_average":"0","mem":"2.2"},"722":{"cmdline":"frigate.capture:porch","cpu":"0.6","cpu_average":"0","mem":"2.2"},"724":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_sub -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.3","cpu_average":"1","mem":"2.5"},"726":{"cmdline":"frigate.capture:front-yard","cpu":"0.8","cpu_average":"0","mem":"2.2"},"729":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/porch_sub -r 5 -vf fps=5,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"2.4"},"733":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.68.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/022e5930ffaa6db7ba192137f3032d63","cpu":"0.4","cpu_average":"0","mem":"0.2"},"734":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.2"},"735":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front-yard_sub -r 5 -vf fps=5,scale_cuda=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"1","mem":"2.5"},"738":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/porch -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/porch@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.1"},"741":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.68.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/69c49cad939110f8e5aa0b0bf8ab8005","cpu":"2.5","cpu_average":"2","mem":"0.2"},"742":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front-yard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front-yard@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"0","mem":"0.2"},"6037":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":9.3,"detectors":{"tensorrt":{"detection_start":0.0,"inference_speed":10.86,"pid":654}},"gpu_usages":{"NVIDIA GeForce GTX 980":{"dec":"2.0%","enc":"0.0%","gpu":"6.0%","mem":"16.93%"}},"processes":{"go2rtc":{"pid":103},"logger":{"pid":601},"recording":{"pid":645}},"service":{"last_updated":1721260577,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":8176.0,"mount_type":"tmpfs","total":8192.0,"used":16.0},"/media/frigate/clips":{"free":6753333.1,"mount_type":"zfs","total":7348836.6,"used":595503.5},"/media/frigate/recordings":{"free":6753333.1,"mount_type":"zfs","total":7348836.6,"used":595503.5},"/tmp/cache":{"free":8176.7,"mount_type":"tmpfs","total":8192.0,"used":15.3}},"temperatures":{},"uptime":1176,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

TensorRT

### Any other information that may be helpful

This has been built on a TrueNAS Scale setup using the TrueCharts.org deployment
