### DISCUSSION TITLE
[Question]: GPU Usage/Memory metrics permissions?

### DISCUSSION THREAD

**Discussion by WarrenSchultz** [blakeblackshear/frigate#12503] [Ask A Question]
### What is your question:

I'm running under WSL2/Ubuntu 22.04/Docker-CE on the 0.14 beta 4 build, but only recently started testing out Frigate, so I only know a bit about how it worked previously. As I understand it, it may be a permissions issue, but I'm trying to narrow down what I'm specifically missing from my configuration to be able to see GPU-level stats on the system metrics screen.

Thanks!

![image](https://github.com/user-attachments/assets/c38fbe88-00b0-49dc-8a99-77f4426cc6a4)

**Comment by NickM-27** [comment]
there's no way to answer this question without seeing your config, knowing your hardware, etc.

**Comment by WarrenSchultz** [comment]
Sorry, it seemed like a fairly generic question.

WIndows 11 Pro 23H2
Ubu 22.04, Docker-CE, NVIDIA Container all fully updated
i9-7900X CPU
2x RTX 3060 (12GB) GPU

```
services:
  frigate:
    container_name: frigate
    hostname: frigate
    networks:
      - securitynet
    privileged: true # this may not be necessary for all setups
    cap_add:
      - PERFMON
    restart: unless-stopped
    # image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4-tensorrt
    # image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev:/dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/warren/Docker/frigate/config:/config
      - /s/frigate_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - YOLO_MODELS=yolov7-320,yolov7x-640 # yolo7-nms-640 yolov7x-640,yolov7-w6-nms-1280,yolov7-nms-fp16-640,yolov4-p5-896,ssdlite_mobilenet_v2
    deploy:
      resources:
          reservations:
              devices:
              - driver: nvidia
                device_ids: ["all"]
                capabilities:
                  - gpu
networks:
  securitynet:
    name: securitynet
    external: True
```

```
detectors:
  tensorrt0:
    type: tensorrt
    device: 1
  # tensorrt1:
  #   type: tensorrt
  #   device: 0
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  labelmap_path: /config/labelmap.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

cameras:
  V3TestCamBlack:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://wyze-bridge:8554/v3testnew
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.721,0.986,0.984,0.988,0.985,0.933,0.721,0.931
  BackDeckCam:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://wyze-bridge:8554/back-deck-cam
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.717,0.98,0.979,0.982,0.984,0.937,0.716,0.931
  GarageEntry:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://wyze-bridge:8554/garage-entry
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.717,0.98,0.979,0.982,0.984,0.937,0.716,0.931
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
```
