### DISCUSSION TITLE
Audio detection: Detect all audio?

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#12504] [General]
Hi,

I'm planning to use a camera as a sleep monitor with motion and audio detection.  Is there any way to set the audio detector to detect all sounds with no filtering?

**Comment by NickM-27** [comment]
it is not clear what you mean, there are no audio events for sound but you could create a notification via home assistant or nodered that triggers when the sound volume goes above a certain level

**Reply by jakeycrx** [reply]
From what I can see in the docs, you have to select audio events to detect (speech, snoring etc) With my usage as a sleep monitor, it would be better to detect all noise, then filter on the RMS level.

**Reply by NickM-27** [reply]
to be clear you don't have to, you could set it to an empty list and just use the RMS or dbfs level. 

```
audio:
  listen: []
```

the only way to listen for everything is to simply enable all of the labels

**Reply by jakeycrx** [reply]
I've set the audio listen with square brackets, but it doesn't record when the RMS is over the threshold.  Recording was working when I had events set to detect.

![image](https://github.com/user-attachments/assets/715807a0-fbf5-436b-ae3e-5a9da1a3b004)
```
  e1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      input_args: preset-http-reolink
      inputs:
        - path: 
            http://192.168.1.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****
          roles:
            - record
        - path: 
            http://192.168.1.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=****&password=****
          roles:
            - detect
            - audio
    audio:
      enabled: true
      # Optional: Configure the amount of seconds without detected audio to end the event (default: shown 30)
      max_not_heard: 30
      # Optional: Configure the min rms volume required to run audio detection (default: 500)
      # As a rule of thumb:
      #  - 200 - high sensitivity
      #  - 500 - medium sensitivity
      #  - 1000 - low sensitivity
      min_volume: 200
      # Optional: Types of audio to listen for (default: shown below)
      listen: []              
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 10
        post_capture: 30
        retain:
          default: 5
          mode: motion
```
