### DISCUSSION TITLE
[Config Support]:  [ERROR] Frigate config file not found

### DISCUSSION THREAD

**Discussion by wgsullivan** [blakeblackshear/frigate#12519] [Config Support] [answered]
### Describe the problem you are having

I have been running frigate in a vm for some time and am in the process of moving to new dedicated hardware. I have freshly installed Ubuntu 24.04 and docker compose. I have created the following directory structure for frigate, which mirrors my existing setup
/docker
   /frigate
      /config
      /storage
Here is my docker-compose.yml, located in /docker/frigate/:

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "192mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions

    volumes:
      - /etc/localtime:/etc/localtime:ro
        #      - /docker/frigate/config.yml:/config/config.yml
      - /docker/frigate/config:/config
      - /docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "???"
      FRIGATE_RTSP_GV_PASSWORD: "???"
      FRIGATE_RTSP_USER: "user"
```

my config.yml file is located at /docker/frigate/config/config.yml:
bill@cg-frigate:/docker/frigate$ ls -l config/
total 5404
-rw-r--r-- 1 root root    5860 Jul 19 17:38 config.yml
-rwxr-xr-x 1 root root 5521476 Jul 19 17:38 go2rtc

When I try to bring up frigate with 
"docker compose up -d" 
(from the /docker/frigate directory), frigate constantly restarts and the logs show that frigate can't find the config file

  [ERROR] Frigate config file not found

I have gone over the configs and reinstalled the OS. I've tried Ubuntu 23.10 as well as Ubuntu 24.04. I'm not sure what could be wrong. This is a working configuration on my vm.

Thanks for any insight you can offer

### Version

frigate:stable

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.133
  #  port: 1833
  user: frigate
  password: ???
  topic_prefix: frigate
  client_id: frigate
detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
    cg_driveway:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.101:554/cam/realmonitor?channel=1&subtype=0
    cg_driveway_sub:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.101:554/cam/realmonitor?channel=1&subtype=1
    cg_front_door:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.102:554/cam/realmonitor?channel=1&subtype=0
    cg_front_door_sub:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.102:554/cam/realmonitor?channel=1&subtype=1
    cg_chicken_run:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.104:554/cam/realmonitor?channel=1&subtype=0
    cg_chicken_run_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.104:554/cam/realmonitor?channel=1&subtype=1
    cg_chicken_coop:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.105:554/cam/realmonitor?channel=1&subtype=0
    cg_chicken_coop_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.4.105:554/cam/realmonitor?channel=1&subtype=1
    gv_driveway:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_GV_PASSWORD}@192.168.81.101:554/cam/realmonitor?channel=1&subtype=0
    gv_driveway_sub:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_GV_PASSWORD}@192.168.81.101:554/cam/realmonitor?channel=1&subtype=1
    gv_deck:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_GV_PASSWORD}@192.168.81.102:554/cam/realmonitor?channel=1&subtype=0
    gv_deck_sub:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_GV_PASSWORD}@192.168.81.102:554/cam/realmonitor?channel=1&subtype=1
    gv_rear:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_GV_PASSWORD}@192.168.81.103:554/cam/realmonitor?channel=1&subtype=0
    gv_rear_sub:
    - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_GV_PASSWORD}@192.168.81.103:554/cam/realmonitor?channel=1&subtype=1

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 45
      mode: motion

cameras:
  cg_driveway:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cg_driveway
        roles:
        - record
        - rtmp
      - path: rtsp://127.0.0.1:8554/cg_driveway_sub
        roles:
        - detect
    rtmp:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - dog
      - car
      - bird
    live:
      stream_name: cg_driveway
  cg_front_door:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cg_front_door
        roles:
        - record
        - rtmp
      - path: rtsp://127.0.0.1:8554/cg_front_door_sub
        roles:
        - detect

    rtmp:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - dog
      - car
      - bird
    zones:
      zone_0:
        coordinates: 499,74,463,74,610,174,640,154
      zone_1:
        coordinates: 579,173,461,68,401,63,370,261
  cg_chicken_run:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cg_chicken_run
        roles:
        - record
        - rtmp
      - path: rtsp://127.0.0.1:8554/cg_chicken_run_sub
        roles:
        - detect
    rtmp:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - dog
      - bird
  cg_chicken_coop:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cg_chicken_coop
        roles:
        - record
        - rtmp
      - path: rtsp://127.0.0.1:8554/cg/chicken_coop_sub
        roles:
        - detect
    rtmp:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - bird
  gv_driveway:
    ffmpeg:
      inputs:
              #         - path: rtsp://127.0.0.1:8554/gv_driveway
              #           roles:
                   #            - clips
      - path: rtsp://127.0.0.1:8554/gv_driveway_sub
        roles:
        - detect
        - record
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - dog
      - car
      - bear
      - cat
  gv_rear:
    ffmpeg:
      inputs:
              #         - path: rtsp://127.0.0.1:8554/gv_driveway
              #           roles:
                   #            - clips
      - path: rtsp://127.0.0.1:8554/gv_rear_sub
        roles:
        - detect
        - record
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - dog
      - car
      - bear
      - cat
  gv_deck:
    ffmpeg:
      inputs:
              #         - path: rtsp://127.0.0.1:8554/gv_driveway
              #           roles:
                   #            - clips
      - path: rtsp://127.0.0.1:8554/gv_deck_sub
        roles:
        - detect
        - record
    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - dog
      - car
      - bear
      - cat
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-07-19 17:57:39.597743776  [INFO] Preparing Frigate...
2024-07-19 17:57:39.597798075  [ERROR] Frigate config file not found
2024-07-19 17:57:39.600021323  [INFO] Starting NGINX...
2024-07-19 17:57:39.600944522  [INFO] Preparing new go2rtc config...
2024-07-19 17:57:39.603207218  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-07-19 17:57:39.613545270  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-07-19 17:57:39.614550837  [INFO] Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-07-19 17:57:39.620801824  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral
