### DISCUSSION TITLE
[Config Support]: Applying ffmpeg crop to rtsp input

### DISCUSSION THREAD

**Discussion by madjetey** [blakeblackshear/frigate#12518] [Config Support]
### Describe the problem you are having

Trying to crop a camera stream to show a gate that is part of another feed but none of my ffmpeg arguments are working.  I'm only getting the full view without any crop.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
go2rtc:
  streams:
    Gate-Focus:
#      - rtsp://admin:scL5WX8YLmCkaH3@192.168.1.46:554/cam/realmonitor?channel=1&subtype=1
#      - "ffmpeg:#video=h264#raw=-vf crop=185:161:149:105#hardware"
      - 'ffmpeg:rtsp://xxxx:xxx@192.168.1.46:554/cam/realmonitor?channel=1&subtype=1#hardware#video=h264#raw=-vf "crop=185:161:149:105"'

cameras:
  Gate_Focus:
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
    ffmpeg:
      inputs:
      #High Resolution Stream
      - path: rtsp://127.0.0.1:8554/Gate-Focus
      #  input_args: preset-rtsp-restream
        roles:
        - detect
```

### Relevant log output

```shell
- [19/Jul/2024:17:56:08 +0000] "GET /api/Gate_Focus/latest.jpg?h=469 HTTP/1.1" 200 50601 "http://100.67.126.116:8123/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0" "127.0.0.1, 172.30.32.1"
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)
