### DISCUSSION TITLE
[HW Accel Support]:

### DISCUSSION THREAD

**Discussion by smorar** [blakeblackshear/frigate#12515] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I get the following errors in the docker logs:
frigate  | ERROR: file (yolov7-320.trt.cfg) not found!
frigate  | s6-rc: warning: unable to start service trt-model-prepare: command exited 1

My docker image returns running in an unhealthy state, and I can no-longer access the user interface.

### Version

Not sure, UI isn't loading up

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.0.22
  user: homeassistant
  password: <removed>

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

go2rtc:
  streams:
<removed for privacy>

ffmpeg:
  hwaccel_args: preset-nvidia-h264

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

detect:
  enabled: True
  width: 640
  height: 480

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

birdseye:
  enabled: True
  mode: continuous

cameras:
  garage_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cam
          roles:
            - detect
            - record

  front_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_cam
          roles:
            - detect
            - record
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    environment:
      - YOLO_MODELS=yolov7-320.trt
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt #image: ghcr.io/blakeblackshear/frigate:0.12.1-tensorrt
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/smorar/docker/frigate:/config
        #      - /home/smorar/docker/frigate/go2rtc:/config/go2rtc
      - /storage/Frigate:/media/frigate #- /home/smorar/docker/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | Generating the following TRT Models: yolov7-320.trt
frigate  | Downloading yolo weights
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-07-20 01:05:04.501343585  [INFO] Preparing new go2rtc config...
frigate  | 2024-07-20 01:05:04.720755293  [INFO] Starting go2rtc...
frigate  | 2024-07-20 01:05:04.908519590  01:05:04.908 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-07-20 01:05:04.909135381  01:05:04.909 INF [api] listen addr=:1984
frigate  | 2024-07-20 01:05:04.909185840  01:05:04.909 INF [rtsp] listen addr=:8554
frigate  | 2024-07-20 01:05:04.909482173  01:05:04.909 INF [webrtc] listen addr=:8555
frigate  | 2024-07-20 01:05:14.501178371  [INFO] Starting go2rtc healthcheck service...
frigate  | 
frigate  | Creating yolov7-320.cfg and yolov7-320.weights
frigate  | 
frigate  | Done.
frigate  | ERROR: file (yolov7-320.trt.cfg) not found!
frigate  | s6-rc: warning: unable to start service trt-model-prepare: command exited 1
```

### FFprobe output from your camera

```shell
I'm using go2rtc to read from nest cameras.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Google nest

### Any other information that may be helpful

My configuration was working fine with 0.13.1
