### DISCUSSION TITLE
[Support]: high cpu usage where to look to fix

### DISCUSSION THREAD

**Discussion by GMagician** [blakeblackshear/frigate#12534] [General Support]
### Describe the problem you are having

I have high cpu usage in one of the cameras, up to 50%. Cpu is high in detection. There should be no conversion for video (h264 camera).

### Version

0.14.0-a4eb435 (beta4)

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: false

birdseye:
  enabled: true
  mode: continuous

detectors:
  rknn:
    type: rknn
    num_cores: 3

model:
  path: deci-fp16-yolonas_s
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nhwc

ffmpeg:
  hwaccel_args: preset-rk-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    Balcone_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.112:554/0#video=copy#audio=copy
    Balcone_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.112:554/1#video=copy#audio=copy
      - ffmpeg:Balcone_sub##audio=opus
    Retro_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/0#video=copy#audio=copy
    Retro_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/1#video=copy#audio=copy
      - ffmpeg:Retro_sub#audio=opus

cameras:
  Balcone:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Balcone_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Balcone_sub
          roles:
            - detect
    birdseye:
      order: 1
    live:
      stream_name: Balcone_sub
    motion:
      threshold: 20
      mask:
        - 1,1,0.61,0.999,0.48,0.395,0.702,0.288,0.832,0.311,1,0.436
        - 0.002,0.994,0.002,0.007,0.267,0.003,0.26,0.612,0.185,0.45,0.102,0.71,0.087,1
    detect:
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5
  Retro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Retro_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Retro_sub
          roles:
            - detect
    birdseye:
      order: 2
    live:
      stream_name: Retro_sub
    motion:
      threshold: 12
      mask: 1,1,1,0,0.697,0,0.697,0.093,0.722,0.286,0.775,0.459,0.845,1
    detect:
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5

timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

record:
  enabled: true
  retain:
    days: 0
  events:
    objects:
      - person
    pre_capture: 5
    post_capture: 10
    retain:
      default: 5
      mode: active_objects
```

### Relevant log output

```shell
No relevant output
```

### FFprobe output from your camera

```shell
MAIN STREAM
[rtsp @ 0xaaaafe2aabf0] Missing PPS in sprop-parameter-sets, ignoring
[rtsp @ 0xaaaafe2aabf0] max delay reached. need to consume packet
[rtsp @ 0xaaaafe2aabf0] RTP: missed 1 packets
[h264 @ 0xaaaafe2acd00] concealing 4653 DC, 4653 AC, 4653 MV errors in I frame
[rtsp @ 0xaaaafe2aabf0] max delay reached. need to consume packet
[rtsp @ 0xaaaafe2aabf0] RTP: missed 1 packets
Input #0, rtsp, from 'rtsp://USER:PSWD@192.168.0.114/0':
  Metadata:
    title           : h264.mp4
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, progressive), 1944x2592, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp

SUBSTREAM:
[rtsp @ 0xaaab0be2abf0] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://USER:PSWD@192.168.0.114/1':
  Metadata:
    title           : h264.mp4
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, progressive), 720x1280, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

RKNN

### Network connection

Wired

### Camera make and model

DSE

### Any other information that may be helpful

![immagine](https://github.com/user-attachments/assets/368a7c30-39fa-4f89-ac7a-b8f54b1e9fc2)
