### DISCUSSION TITLE
[Detector Support]: Increase in false positives due since switching to TensorRT

### DISCUSSION THREAD

**Discussion by nosar77** [blakeblackshear/frigate#12531] [Detector Support]
### Describe the problem you are having

Previously using CPU detectors resulted in maybe 1 or 2 false positives due to shadows or windy trees, mostly during the day. Since enabling tensor RT, I got a significate increase in false positives like someone's 1 or 2 and hour. In addition frigate detects something but the recording isn't save, it seems either the GPU is really fast at detecting and doesn't save or something I'm not sure, 

### Version

0.14.0-a4eb435

### Frigate config file

```yaml
mqtt:
  host: SECRET         # YOUR MQTT IP
  port: SECRET
  topic_prefix: SECRET
  user: SECRET               # YOUR MQTT USERNAME
  password: 'SECRET'        # YOUT MQTT PASSWORD

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    front_door_bell:
      - rtsp://SECRET:SECRET@SECRET:SECRET/h264Preview_01_main
      - ffmpeg:rtsp://SECRET:SECRET@SECRET:SECRET/h264Preview_01_main#audio=pcm#audio=volume
    front_door_bell_sub:
      - rtsp://SECRET:SECRET@SECRET/h264Preview_01_sub
      - ffmpeg:rtsp://SECRET:SECRET@SECRET/h264Preview_01_sub#audio=pcm#audio=volume

    backyard_cam:
      - rtsp://SECRET:SECRET@SECRET/videoMain
    backyard_cam_sub:
      - rtsp://SECRET:SECRET@SECRET/videoSub

    garage_floodlight:
      - rtsp://SECRET:SECRET@SECRET:SECRET/Preview_01_main
      - ffmpeg:rtsp://SECRET:SECRET@SECRET:SECRET/Preview_01_main#video=h264#audio=opus

    garage_floodlight_sub:
      - rtsp://admin:SECRET@SECRET:SECRET/Preview_01_sub
      - rtsp://SECRET:SECRET@SECRET:SECRET/Preview_01_sub#audio=pcm#audio=volume
  webrtc:
    candidates:
      - SECRET:SECRET
      - stun:SECRET

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

# Camera configuration
cameras:
  front_door_bell:
    ffmpeg:
      inputs:
        # Main stream for recording
        - path: rtsp://127.0.0.1:8554/front_door_bell
          input_args: preset-rtsp-restream
          roles:
            - record
        # Sub-stream for detection
        - path: rtsp://127.0.0.1:8554/front_door_bell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
  backyard_cam:
    ffmpeg:
      inputs:
        # Main stream for recording
        - path: rtsp://127.0.0.1:8554/backyard_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        # Sub-stream for detection
        - path: rtsp://127.0.0.1:8554/backyard_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
  garage_floodlight:
    ffmpeg:
      inputs:
        # Main stream for recording
        - path: rtsp://127.0.0.1:8554/garage_floodlight
          input_args: preset-rtsp-restream
          roles:
            - record
        # Sub-stream for detection
        - path: rtsp://127.0.0.1:8554/garage_floodlight_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy

#Global camera Config

detect:
  enabled: true
  width: 1080
  height: 720
  fps: 5

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 14

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

  sync_recordings: false
  
tls:
  enabled: False

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate_beta:
    container_name: "frigate_beta"
    image: "ghcr.io/blakeblackshear/frigate:0.14.0-beta4-tensorrt"
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    entrypoint:
      - "/init"
    environment:
      - "FRIGATE_RTSP_PASSWORD=password"
      - "PATH=/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/tempio/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "S6_LOGGING_SCRIPT=T 1 n0 s10000000 T"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "YOLO_MODELS=yolov7-320"
      - "TRT_VER=8.5.3"
      - "USE_FP16=false"
    hostname: "72cc68871428"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "c055e02c43856d838b0b36430f47c4bb9772f5467811d99a96cab05d5cb3084f"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:72456521b2d27df26796647f057e552646c3fa3ad066aae6af01f848b8631e71"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "frigate_beta"
      com.docker.compose.project.config_files: "/frigate_beta/docker-compose.yml"
      com.docker.compose.project.working_dir: "/frigate_beta"
      com.docker.compose.service: "frigate"
      com.docker.compose.version: "2.28.1"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "frigate_beta_default"
    ports:
      - "5000:5000/tcp"
      - "8554:8554/tcp"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "8971:8971/tcp"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "label=disable"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/frigate_beta/config:/config"
      - "/mnt/EternalStorage/Frigate/Recordings:/media/frigate/recordings"
      - "/mnt/EternalStorage/Frigate/Snapshots:/media/frigate/clips"
      - "frigatetmpfs:/tmp/cache"
    working_dir: "/opt/frigate"
```

### Relevant log output

```shell
None
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

TensorRT
