### DISCUSSION TITLE
Help understanding ffmpeg errors

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#12541] [General]
I've posted previously about issues with audio sync with my Dahua camera.  The video ends up around 10 seconds behind the audio after a day or so.  I don't have any ffmpeg errors in the Frigate logs though.  I decided to play the stream using ffplay to see what would happen.  It threw up quite a few errors:

Does anybody have any ideas on what could be causing these errors and how I would go about resolving them?
```
Input #0, rtsp, from 'rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.022000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2592x1520 [SAR 28:27 DAR 168:95], 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp
[swscaler @ 000002a3a2045780] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000002a3a2045780] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000002a3a21ab680] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000002a3a2546240] deprecated pixel format used, make sure you did set range correctly
[rtsp @ 000002a392b91d00] max delay reached. need to consume packet
[rtsp @ 000002a392b91d00] RTP: missed 48 packets
[h264 @ 000002a398e18500] error while decoding MB 45 64, bytestream -7B
[h264 @ 000002a398e18500] concealing 5026 DC, 5026 AC, 5026 MV errors in P frame
   4.84 A-V: -0.028 fd=   1 aq=   17KB vq= 1176KB sq=    0B
```

The http stream from my Reolink POE doorbell doesn't give any errors at all:
```
Input #0, flv, from 'http://192.168.1.218/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****':
  Metadata:
    displayWidth    : 2560
    displayHeight   : 1920
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 19 fps, 20 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
  16.90 A-V: -0.008 fd=   3 aq=   13KB vq= 1141KB sq=    0B
```

**Comment by NickM-27** [comment]
what are your video and audio encoding settings in the camera ui

**Reply by jakeycrx** [reply]
![image](https://github.com/user-attachments/assets/303ad448-a4e8-4e62-bb85-86ab203cda5b)

I recently changed the sampling to 48K out of desperation

![image](https://github.com/user-attachments/assets/50fc6b1a-bb36-41c4-937d-6f52336e9238)

I have noticed the pings to the camera aren't great, no packet loss though. This is pinging from the machine running HAOS.  I do want to try changing the ethernet cable, but that involves getting up on the roof again.

![image](https://github.com/user-attachments/assets/2ea21ea7-690b-4ee4-b300-e88ff83acb3c)

**Reply by NickM-27** [reply]
I would suggest 8000 for AAC audio personally. Other than that seems fine, although I run mine at 20 fps and a lower bit rate

**Reply by jakeycrx** [reply]
I'll try lowering the fps and bitrate.

One other thing I noticed is that the video is Level 5 High.  I found the ffmpeg command to convert to 5.1, but can't figure out how to enter it as an argument for ffmpeg.  How would I dial this in?

-bsf:v h264_metadata=level=51

![image](https://github.com/user-attachments/assets/37409408-2cb1-47ed-a506-02f57110c61c)

**Reply by jakeycrx** [reply]
I just used ffmpeg to record the rtsp stream and got some different errors. I ran:
```
ffmpeg -i "rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0" -acodec copy -vcodec copy c:/ffmpeg/rtsp2.mp4
```
```
  Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 2592x1520 [SAR 28:27 DAR 168:95], q=2-31, 20 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp
Press [q] to stop, [?] for help
[mp4 @ 0000023801458cc0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[vost#0:0/copy @ 0000023801e45500] Non-monotonic DTS; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
```

**Reply by jakeycrx** [reply]
There are a few errors in the log for the Dahua today.  At this rate I will be making my way up onto the roof with a big hammer.
```
2024-07-21 17:19:23.931053635  [2024-07-21 18:19:23] watchdog.dahua                 ERROR   : No new recording segments were created for dahua in the last 120s. restarting the ffmpeg record process...
2024-07-21 17:19:23.931180905  [2024-07-21 18:19:23] watchdog.dahua                 INFO    : Terminating the existing ffmpeg process...
2024-07-21 17:19:23.931353101  [2024-07-21 18:19:23] watchdog.dahua                 INFO    : Waiting for ffmpeg to exit gracefully...
2024-07-21 17:54:51.182707300  [2024-07-21 18:54:51] frigate.ptz.onvif              WARNING : dahua is already performing an action, not moving...
2024-07-21 20:03:54.908757158  [2024-07-21 21:03:54] watchdog.dahua                 ERROR   : No new recording segments were created for dahua in the last 120s. restarting the ffmpeg record process...
2024-07-21 20:03:54.909015404  [2024-07-21 21:03:54] watchdog.dahua                 INFO    : Terminating the existing ffmpeg process...
2024-07-21 20:03:54.909196310  [2024-07-21 21:03:54] watchdog.dahua                 INFO    : Waiting for ffmpeg to exit gracefully...
```

**Reply by saket424** [reply]
@jakeycrx 
Try h264 baseline profile instead of high profile to see if that improves things

**Comment by jakeycrx** [comment]
I see an error about missed packets a lot of the time when manually recording using ffmpeg.  After some Googling it was suggested to increase the buffer size

[rtsp @ 00000183f4156580] max delay reached. need to consume packet
[rtsp @ 00000183f4156580] RTP: missed 16 packets

Is this the correct way to enter the ffmpeg argument? I've entered this and it's accepted it without any errors:
```
go2rtc:
  streams:
    dahua:
      - rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:dahua#buffer_size=10000K
```

**Reply by NickM-27** [reply]
That doesn't work with go2rtc, it is not a valid go2rtc parameter. 

The log you are referring to is not an error, it won't cause the stream to crash. The cause will be at the end of the log. Usually connection timed out or something.

**Reply by jakeycrx** [reply]
How can I enter the buffer size as an ffmpeg argument? I think it's worth a try

**Reply by NickM-27** [reply]
You would have to use manual input args

**Reply by jakeycrx** [reply]
Could you help me out with that please? I've read though the docs, but I can't find any examples of manual arguments

**Reply by NickM-27** [reply]
Right, because in general manual ffmpeg args are only meant to be used by users familiar with ffmpeg. Ffmpeg is complex software.

You're using go2rtc to restream, so there are multiple parts that will fail if the stream has problems so it isn't a simple config to paste. In general, adding a buffer will just increase latency. That log line isn't the actual error that caused the stream to fail.

**Reply by jakeycrx** [reply]
I just want to add one simple argument just to try it

What is causing the stream to fail and how do I fix it?

**Reply by NickM-27** [reply]
> I just want to add one simple argument just to try it

Right, like I said there is no simple argument given that you're using go2rtc for restream. 

> What is causing the stream to fail and how do I fix it?

I don't know, you haven't provided logs or the original config that is being used.

**Reply by jakeycrx** [reply]
I'm happy to change my config to suit.

I provided all the info on the other post and we tried some tweaks to the config, but unfortunately it didn't resolve it.

[This post](https://github.com/blakeblackshear/frigate/discussions/12345)

**Reply by jakeycrx** [reply]
Is there enough info on the previous post? Or would it be helpful to provide some more info?

**Reply by NickM-27** [reply]
The current config and a full copy of the logs

**Comment by jakeycrx** [comment]
I'm making some progress.  I used Wayback Machine and found the example config before presets were introduced so I now know how to enter ffmpeg arguments.  
```
# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
``` 

I added -buffer_size 10000K and decided to try it with UDP.  
```
  dahua:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -timeout 5000000 -use_wallclock_as_timestamps 1 -buffer_size 10000K
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

The sound stays in sync, but the video is very jumpy and not smooth at all.  

[Example](https://drive.google.com/file/d/1fGyWGiSSTuDxDkfH22FIeRhjmUqUFb2G/view?usp=sharing)

I then experimented by manually recording with ffmpeg and removing arguments.  It seems using -fflags +genpts+discardcorrupt and -use_wallclock_as_timestamps 1 with -buffer_size 10000K makes the video jumpy.

I then ran the below for a day. I decided to reinstate TCP. The video was absolutely fine, but the sound did go very slightly out of sync, only by a second or so. It's a huge improvement on the 10+ seconds I was seeing before.
```
  dahua:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
          input_args: -avoid_negative_ts make_zero -rtsp_transport tcp -timeout 5000000 -buffer_size 10000K
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```
I've decided to try UDP again. All seems good at the minute, but it will probably go out of sync again.
```
  dahua:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
          input_args: -avoid_negative_ts make_zero -timeout 5000000 -buffer_size 10000K
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

Do you have any suggestions for any other arguments to try?

**Reply by jakeycrx** [reply]
It seems to be working OK for now with that last set of arguments.  

I use the following counting video from YouTube to check the sync:

[YouTube Link](https://youtu.be/U03lLvhBzOw?si=rGWTxFsDpVpfdB2n)

This is the problematic camera after running for 24 hours:

[Video](https://drive.google.com/file/d/1FKYw-0l-EMiwh6Lk-AR8hb7IPADsdj-j/view?usp=sharing)

**Reply by jakeycrx** [reply]
I just checked my Reolink POE Doorbell and it's a couple of seconds out of sync.  Am I just really unlucky? Or is there a wider problem here?

[Reolink POE Doorbell OOS](https://drive.google.com/file/d/1W1unVwaEfQplzghLJi-6wqPe2qzeoqWc/view?usp=sharing)

**Reply by NickM-27** [reply]
are you using the recommended reolink config? is the firmware up to date? My reolink doorbell, nor any other cameras have any audio sync issues.

**Reply by jakeycrx** [reply]
I'm just very unlucky then! 

Can you just confirm this is correct? I have the recommended http stream and the rtsp stream for go2rtc.  The rtsp stream is needed for 2 way talk isn't it?
```
go2rtc:
  streams:
    reolink:
      - ffmpeg:http://192.168.1.218/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****#video=copy#audio=copy#audio=opus
      - rtsp://admin:Harriet2015@192.168.1.218:554/h264Preview_01_main 
```
```
cameras:
  reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect 
```
I use the full res stream for detection as the fluent stream doesn't pick up cats at a distance very well.  I run v3.0.0.2033_23041302 firmware as apparently the latest firmware broke 2 way talk via rtsp?  To be fair I use the Reolink app for 2 way talk now, so I could update the firmware and delete the rtsp stream from go2rtc.
