### DISCUSSION TITLE
[Support]: "Kernel does not support swap limit capabilities..." warning message when composing docker in unRaid

### DISCUSSION THREAD

**Discussion by capnjip** [blakeblackshear/frigate#12544] [General Support]
### Describe the problem you are having

I have, what seems to be, a relatively common "out of memory" issue with my unRaid server. The memory issue does trace back to frigate. I noticed when trying different "compositions" of this docker that there was an Warning message, and it doesn't make any sense to me. Can anyone tell me if this is something I should look to fix or safely ignore? 
"WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. "

### Version

0.13.2

### Frigate config file

```yaml
## v1.0 used on unRAID server. 05Mar2023
## First install, 13Jan2022. Following https://docs.frigate.video/guides/getting_started "creating a config file"
## Upgrade to Frigate 0.12 27May2023

mqtt:
  host: 192.168.X.X
  port: 1883
  user: mqtt
  password: [Redacted]

detectors:
  coral:
    type: edgetpu
    device: pci:0

birdseye:
  enabled: true

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-nvidia-h264

objects:
  track:
  - person
  - dog
  - cat
#    - car

#added as attempt to reduce false positives ID'ing Cars as People
  filters:
    person:
      threshold: 0.58
      min_area: 8000
#      min_ratio: 0.2
      max_ratio: 0.88
    cat:
      threshold: 0.60
    dog:
      threshold: 0.6

motion:
#scale: 1-255, higher = less sensitive
  threshold: 40
#Rule of thumb: 15 high, 30 med, 50 low sensitivity
  contour_area: 35
#alpha values: high values mean single frame makes for motion, too low won't show motion at all
  delta_alpha: 0.18
  frame_alpha: 0.18

record:
  enabled: true
  retain:
    days: 20
    mode: all
  events:
    retain:
      default: 20

      mode: all

snapshots:
  enabled: true
  retain:
    default: 20

go2rtc:
  streams:
    sidedoor:
    - rtsp://[redacted]:[redacted]@192.168.X.X:554/cam/realmonitor?channel=1&subtype=0
    driveway:
    - rtsp://[redacted]:[redacted]@192.168.X.X:554/cam/realmonitor?channel=1&subtype=0
    acunit:
    - rtsp://[redacted]:[redacted]@192.168.X.X/h265Preview_01_main
    frontyard:
    - rtsp://[redacted]:[redacted]@192.168.X.X:554/cam/realmonitor?channel=1&subtype=0
    backdoor:
    - rtsp://[redacted]:[redacted]@192.168.X.X/h265Preview_01_main
    frontdoor:
    - rtsp://[redacted]:[redacted]@192.168.X.X/h265Preview_01_main
    garagedoor:
    - rtsp://[redacted]:[redacted]@192.168.X.X/h265Preview_01_main
  webrtc:
    candidate:
    - 192.168.X.X:8555

cameras:
  frontdoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/frontdoor
        roles:
        - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
      - 1310,0,2560,0,2560,318,1302,21,0,252,0,0
    objects:
      filters:
        dog:
          mask:
          - 583,168,426,328,591,561,897,365,877,103

  sidedoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/sidedoor
        roles:
        - detect
    detect:
      enabled: true
      width: 2688
      height: 1520
    motion:
      mask:
      - 0,672,752,584,2641,578,2581,369,1912,276,1711,293,942,340,0,383
    objects:
      filters:
        car:
          mask:
          - 0,672,752,584,2641,578,2581,369,1912,276,1711,293,942,340,0,383

  driveway:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway
        roles:
        - detect
    detect:
      enabled: true
      width: 2688
      height: 1520
    motion:
      mask:
      - 2688,0,2688,732,2222,491,1857,358,1160,271,409,251,338,0
    objects:
      filters:
        car:
          mask:
          - 2688,0,2688,732
        person:
          mask:
          - 2214,486,1784,338,1497,290,1486,0,2688,0,2688,718 #McGaskill Driveway and Road
          - 2214,486,1784,338,97,1015,481,1028 #tree and Fence gap false pos
          - 97,1015,481,1028,491,817,89,802 #sideview mirror close car
  backdoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/backdoor
        roles:
        - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
      - 2560,0,2560,926,1810,675,1850,433,1546,319,1003,227,0,212,0,0
      - 0,1440,1072,1440,732,1002,0,1078
    objects:
      filters:
        car:
          mask:
          - 0,1440,2560,1440,2560,0,0,0

  acunit:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/acunit
        roles:
        - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
      - 2535,630,2560,0,0,0,0,967,626,692,923,89,2017,69,2098,597
    objects:
      filters:
        car:
          mask:
          - 2560,0,2560,1440,0,1440,0,0

  garagedoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/garagedoor
        roles:
        - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
      - 2335,0,2340,422,2125,428,2129,166,1482,222,1121,373,487,537,0,709,0,0
    objects:
      filters:
        car:
          mask:
          - 0,0,1166,0,1555,0,1555,235,938,346,661,412,0,578
        person:
          mask:
          - 2231,488,2369,486,2365,323,2226,322

  frontyard:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/frontyard
        roles:
        - detect
    detect:
      enabled: true
      width: 2688
      height: 1520
    motion:
      mask:
      - 0,666,634,379,1415,180,1929,178,1849,0,0,0
    objects:
      filters:
        car:
          mask:
          - 0,666,634,379,1415,180,1929,178,1849,0,0,0
```

### Relevant log output

```shell
--runtime=nvidia 'ghcr.io/blackbearshear/frigate"stable'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. 4ce32eb13f5db5fc72221818075ae91cbedd3218b4f54fad28b2f380433ac440
```

### FFprobe output from your camera

```shell
unrelated, software runs normal, minus growing memory issue
```

### Frigate stats

```json
{"cameras":{"acunit":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":524,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":535,"pid":499,"process_fps":5.0,"skipped_fps":0.0},"backdoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":519,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":527,"pid":497,"process_fps":5.1,"skipped_fps":0.0},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":514,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":520,"pid":496,"process_fps":5.0,"skipped_fps":0.0},"frontdoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":506,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":511,"pid":493,"process_fps":5.0,"skipped_fps":0.0},"frontyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":532,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":538,"pid":503,"process_fps":5.0,"skipped_fps":0.0},"garagedoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":528,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":539,"pid":502,"process_fps":5.0,"skipped_fps":0.0},"sidedoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":510,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":515,"pid":494,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"14.8","cpu_average":"14","mem":"0.9"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.1"},"98":{"cmdline":"python3 -u -m frigate","cpu":"2.6","cpu_average":"2","mem":"18.2"},"114":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.4"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"172":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"192":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"220":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"435":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"2.5"},"437":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"8","mem":"4.5"},"446":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)","cpu":"0.4","cpu_average":"0","mem":"0.3"},"447":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"4.5"},"448":{"cmdline":"frigate.output       ","cpu":"5.3","cpu_average":"5","mem":"4.2"},"453":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"457":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2688x1520 -i pipe: -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"469":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2688x1520 -i pipe: -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"470":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"471":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"472":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"473":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2688x1520 -i pipe: -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"474":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"493":{"cmdline":"frigate.process:frontdoor","cpu":"1.1","cpu_average":"1","mem":"4.6"},"494":{"cmdline":"frigate.process:sidedoor","cpu":"1.9","cpu_average":"1","mem":"4.5"},"496":{"cmdline":"frigate.process:driveway","cpu":"1.5","cpu_average":"1","mem":"4.5"},"497":{"cmdline":"frigate.process:backdoor","cpu":"1.1","cpu_average":"1","mem":"4.5"},"499":{"cmdline":"frigate.process:acunit","cpu":"1.5","cpu_average":"1","mem":"5.5"},"502":{"cmdline":"frigate.process:garagedoor","cpu":"1.5","cpu_average":"1","mem":"4.8"},"503":{"cmdline":"frigate.process:frontyard","cpu":"1.5","cpu_average":"1","mem":"4.5"},"506":{"cmdline":"frigate.capture:frontdoor","cpu":"4.9","cpu_average":"4","mem":"4.5"},"510":{"cmdline":"frigate.capture:sidedoor","cpu":"5.3","cpu_average":"4","mem":"4.5"},"511":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontdoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.2","cpu_average":"4","mem":"8.4"},"514":{"cmdline":"frigate.capture:driveway","cpu":"4.9","cpu_average":"4","mem":"4.5"},"515":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/sidedoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/sidedoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2688:h=1520:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.0","cpu_average":"8","mem":"8.5"},"519":{"cmdline":"frigate.capture:backdoor","cpu":"4.2","cpu_average":"4","mem":"4.5"},"520":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2688:h=1520:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.7","cpu_average":"8","mem":"8.9"},"524":{"cmdline":"frigate.capture:acunit","cpu":"3.8","cpu_average":"4","mem":"4.5"},"527":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backdoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backdoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.6","cpu_average":"4","mem":"8.6"},"528":{"cmdline":"frigate.capture:garagedoor","cpu":"4.2","cpu_average":"4","mem":"4.5"},"532":{"cmdline":"frigate.capture:frontyard","cpu":"4.6","cpu_average":"4","mem":"4.5"},"535":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/acunit -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/acunit@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.4","cpu_average":"4","mem":"8.7"},"538":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2688:h=1520:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.0","cpu_average":"8","mem":"8.4"},"539":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garagedoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garagedoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.8","cpu_average":"4","mem":"8.6"},"7528":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.78,"pid":447}},"gpu_usages":{"NVIDIA GeForce GTX 1060 6GB":{"dec":"26.0%","enc":"0.0%","gpu":"3.0%","mem":"34.51%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":435},"recording":{"pid":437}},"service":{"last_updated":1721608685,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":469.3,"mount_type":"tmpfs","total":512.0,"used":42.7},"/media/frigate/clips":{"free":566457.6,"mount_type":"xfs","total":5721128.5,"used":5154670.9},"/media/frigate/recordings":{"free":566457.6,"mount_type":"xfs","total":5721128.5,"used":5154670.9},"/tmp/cache":{"free":2011.5,"mount_type":"tmpfs","total":2048.0,"used":36.5}},"temperatures":{"apex_0":44.8},"uptime":1093,"version":"0.13.2-6476f8a"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

amcrest and reolinks

### Any other information that may be helpful

Not even sure this is a problem, just asking for clarification.
