### DISCUSSION TITLE
[Camera Support]:  Live view resize problem in Safari with Foscam C5M

### DISCUSSION THREAD

**Discussion by gonzalezcalleja** [blakeblackshear/frigate#12552] [Camera Support] [answered]
### Describe the problem you are having

In live view with Safari (Version 17.5 (19618.2.12.11.6)) and Foscam C5M camera he resize doesn't work, is always 1/4 of the size (dashboard view has the same problem):

### Steps to reproduce

Dashboard view and live view problem.

### Version

0.14.0-29345c4

### Frigate config file

```yaml
go2rtc config:

    plantabaja:
      #Planta Baja: HEVC y PCM
      - rtsp://admin:redacted@192.168.6.240:88/videoMain
      - ffmpeg:plantabaja#audio=aac

    plantabaja_sub:
      #Planta Baja: HEVC y PCM
      - rtsp://admin:redacted@192.168.6.240:88/videoSub
      - ffmpeg:plantabaja_sub#video=h264#hardware=vaapi#audio=opus#audio=aac
```

camera config:
```
  plantabaja:
    ui:
      order: 6
      dashboard: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:redacted@127.0.0.1:8554/plantabaja_sub?video=copy&audio=copy
          roles:
            - detect
            - audio

        - path: rtsp://admin:redacted@127.0.0.1:8554/plantabaja?video=h265&audio=aac
          roles:
            - record
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.7
          min_area: 15000
    live:
      stream_name: plantabaja_sub
    audio:
      enabled: true
    motion:
      mask: 0.262,0.016,0.265,0.059,0,0.057,0,0.015
    detect:
      width: 1280
      height: 720
```
```


### Relevant log output

```shell
No relevant log output for this camera.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Foscam C5M

### Any other information that may be helpful

I only have this problem with Foscam c5m cameras, I have other cameras and this is the first time with this issue.

```
$ ffprobe -i rtsp://admin:redacted@192.168.1.103:8554/plantabaja_sub
ffprobe version 7.0.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[rtsp @ 0x147604980] method SETUP failed: 461 Unsupported transport
[hevc @ 0x149104540] PPS id out of range: 0
    Last message repeated 1 times
[hevc @ 0x149104540] Error parsing NAL unit #0.
[hevc @ 0x149104540] PPS id out of range: 0
    Last message repeated 1 times
[hevc @ 0x149104540] Error parsing NAL unit #0.
Input #0, rtsp, from 'rtsp://admin:redacted@192.168.1.103:8554/plantabaja_sub':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 1280x720, 5 fps, 5 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```
