### DISCUSSION TITLE
[Support]: Onvif camera

### DISCUSSION THREAD

**Discussion by GMagician** [blakeblackshear/frigate#12557] [General Support]
### Describe the problem you are having

Are secrets supported on onvif user and password? I have a "zoom only" camera and I get errors when I type direclty in config user and passwor but if I use "secret variables" I get error about "Connection refused" so values are not properly used

### Version

0.14 beta 4

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: true
  host: nvr
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

birdseye:
  enabled: true
  mode: continuous

detectors:
  rknn:
    type: rknn
    num_cores: 3

model:
  path: deci-fp16-yolonas_s
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nhwc

ffmpeg:
  hwaccel_args: preset-rk-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    Balcone_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.112:554/0#video=copy#audio=copy
    Balcone_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.112:554/1#video=copy#audio=copy
      - ffmpeg:Balcone_sub##audio=opus
    Retro_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/0#video=copy#audio=copy
    Retro_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/1#video=copy#audio=copy
      - ffmpeg:Retro_sub#audio=opus

cameras:
  Balcone:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Balcone_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Balcone_sub
          roles:
            - detect
    birdseye:
      order: 1
    live:
      stream_name: Balcone_sub
    motion:
      threshold: 20
      mask:
        - 1,1,0.61,0.999,0.48,0.395,0.653,0.28,0.874,0.332,1,0.436
        - 0.002,0.994,0.002,0.007,0.267,0.003,0.268,0.393,0.185,0.45,0.102,0.71,0.087,1
    detect:
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5
  Retro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Retro_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Retro_sub
          roles:
            - detect
    birdseye:
      order: 2
    onvif:
      host: 192.168.0.114
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
    live:
      stream_name: Retro_sub
    motion:
      threshold: 12
      mask: 1,1,1,0,0.697,0,0.697,0.093,0.722,0.286,0.775,0.459,0.845,1
    detect:
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.5

timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

record:
  enabled: true
  retain:
    days: 0
  events:
    objects:
      - person
    pre_capture: 5
    post_capture: 10
    retain:
      default: 5
      mode: active_objects
```

### Relevant log output

```shell
None more than onvif error
```

### FFprobe output from your camera

```shell
don't care
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

RKNN

### Network connection

Wired

### Camera make and model

DSE
