### DISCUSSION TITLE
[Support]: Birdseye Greyed Out and Missing Sub Labels on Events

### DISCUSSION THREAD

**Discussion by chrisborell** [blakeblackshear/frigate#12562] [General Support]
### Describe the problem you are having

I am experiencing two issues with Frigate:

- The Birdseye view appears greyed out.
- Sub labels are not being attached to events.

I am using Double Take with update_sub_labels: true and a license plate detection script by NickM. These components are **working correctly**, but no sub_label appears in Frigate. (Frigate + Supporter 👍 )

### Steps to reproduce

(Refer To Screenshots)

### Version

0.14.0 Beta 4

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.147
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [REDACTED]
  password: [REDACTED]


record:
  enabled: true
  retain:
    days: 60
    mode: all
  events:
    pre_capture: 10
    post_capture: 30
    retain:
      default: 60
      mode: motion


snapshots:
  enabled: true
  bounding_box: false
  crop: true
  quality: 100

detectors:
  coral1:
    type: edgetpu
    device: pci:0

model:
  path: plus://[REDACTED]

birdseye:
  restream: true
  enabled: true
  quality: 5
  mode: objects

review:
  detections:
    labels:
      - person
      - dog
      - car
      - license_plate
  alerts:
    labels:
      - person
      - dog
      - car
      - license_plate


ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

database:
  path: /config/frigate.db

go2rtc:
  streams:
    front_door:
      - rtsp://admin:[REDACTED]@192.168.2.11:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:front_door#audio=aac
    front_door_sub:
      - rtsp://admin:[REDACTED]@192.168.2.11:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - ffmpeg:front_door_sub#audio=aac
    dante_lane:
      - rtsp://admin:[REDACTED]@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:dante_lane#audio=aac
    dante_lane_sub:
      - rtsp://admin:[REDACTED]@192.168.2.12:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - ffmpeg:dante_lane#audio=aac
    garage_entry:
      - rtsp://admin:[REDACTED]@192.168.2.13:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:garage_entry#audio=aac
    garage_entry_sub:
      - rtsp://admin:[REDACTED]@192.168.2.13:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - ffmpeg:garage_entry#audio=aac
    side_laneway:
      - rtsp://admin:[REDACTED]@192.168.2.14:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:side_laneway#audio=aac
    side_laneway_sub:
      - rtsp://admin:[REDACTED]@192.168.2.14:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - ffmpeg:side_laneway#audio=aac
    elliot_laneway:
      - rtsp://admin:[REDACTED]@192.168.2.16:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:elliot_laneway#audio=aac
    elliot_laneway_sub:
      - rtsp://admin:[REDACTED]@192.168.2.16:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - ffmpeg:elliot_laneway#audio=aac
    garden_area:
      - rtsp://admin:[REDACTED]@192.168.2.17:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:garden_area#audio=aac
    garden_area_sub:
      - rtsp://admin:[REDACTED]@192.168.2.17:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - ffmpeg:garden_area#audio=aac
    garage_area:
      - rtsp://admin:[REDACTED]@192.168.2.15:554/user=admin_password=[REDACTED]_channel=1_stream=0.sdp?real_stream
    garage_area_sub:
      - rtsp://admin:[REDACTED]@192.168.2.15:554/user=admin_password=[REDACTED]_channel=1_stream=1.sdp?real_stream
    downstairs_area:
      - rtsp://admin:[REDACTED]@192.168.2.18:554/user=admin_password=[REDACTED]_channel=1_stream=0.sdp?real_stream
    downstairs_area_sub:
      - rtsp://admin:[REDACTED]@192.168.2.18:554/user=admin_password=[REDACTED]_channel=1_stream=1.sdp?real_stream
    upstairs_area:
      - rtsp://admin:[REDACTED]@192.168.2.19:554/user=admin_password=[REDACTED]_channel=1_stream=0.sdp?real_stream
    upstairs_area_sub:
      - rtsp://admin:[REDACTED]@192.168.2.19:554/user=admin_password=[REDACTED]_channel=1_stream=1.sdp?real_stream
    elliot_food:
      - rtsp://admin:[REDACTED]@192.168.2.20:554/cam/realmonitor?channel=1&subtype=0unicast=true&proto=Onvif
    elliot_food_sub:
      - rtsp://admin:[REDACTED]@192.168.2.20:554/cam/realmonitor?channel=1&subtype=1unicast=true&proto=Onvif
    roaming_camera:
      - rtsp://admin:[REDACTED]@192.168.2.21:554/cam/realmonitor?channel=1&subtype=0unicast=true&proto=Onvif
    roaming_camera_sub:
      - rtsp://admin:[REDACTED]@192.168.2.21:554/cam/realmonitor?channel=1&subtype=1unicast=true&proto=Onvif
    front_gate:
      - ffmpeg:rtsp://admin:[REDACTED]@192.168.2.10:554/Streaming/Channels/101#video=h264#hardware
    front_gate_sub:
      - ffmpeg:rtsp://admin:[REDACTED]@192.168.2.10:554/Streaming/Channels/102#video=h264#hardware

cameras:

  front_gate:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_gate
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_gate_sub
          roles:
            - detect
    ui:
      order: 1

    objects:
      filters:
        car:
          mask:
            - 0.647,0.513,0.645,0.616,0.743,0.617,0.747,0.513
            - 0.486,0.495,0.485,0.554,0.572,0.557,0.57,0.497
    zones:
      Dante_Lane:
        coordinates: 0.489,0.676,0.829,0.657,0.999,0.728,0.999,0.998,0.473,0.997
        inertia: 5
      gate:
        coordinates: 0.482,0.752,0.61,0.743,0.738,1,0.455,0.993
        inertia: 4
        objects:
          - person
          - dog
          - package
    review:
      alerts:
        required_zones:
          - Dante_Lane
          - gate
      detections:
        required_zones:
          - Dante_Lane
          - gate
    snapshots:
      required_zones:
        - Dante_Lane
        - gate

    motion:
      mask: 0.483,0.494,0.485,0.617,0.741,0.619,0.742,0.492

      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          roles:
            - detect
            - audio
    ui:
      order: 2
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.577,0.041,0.576,0.087,0.978,0.085,0.979,0.038
    zones:
      path:
        coordinates: 
          0.794,0.066,0.608,0.119,0.002,0.605,0.002,0.995,0.767,0.997,0.82,0.275,0.816,0.069
        inertia: 4
    review:
      alerts:
        required_zones: path
      detections:
        required_zones: path
    snapshots:
      required_zones:
        - path
    objects:
      filters:
        car:
          mask: 0.745,0.232,0.766,0.236,0.761,0.289,0.741,0.288
    audio:
      enabled: true  # Enable audio events globally
      listen:
        - smash
        - breaking
        - crack
        - glass
        - explosion
        - gunshot
        - machine_gun
        - fusillade
        - artillery_fire
        - cap_gun
        - fireworks
        - firecracker
        - burst
        - eruption
        - siren
        - civil_defense_siren
        - buzzer
        - smoke_detector
        - fire_alarm
        - alarm
        - knock
        - doorbell
        - ding-dong
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - skidding
        - honk
        - toot
        - car_alarm
        - fire
        - crackle
        - thunderstorm
        - thunder
        - bell
        - cat
        - purr
        - meow
        - hiss
        - dog
        - bark
        - yell

  dante_lane:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dante_lane
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dante_lane_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    motion:
      mask:
        - 0.218,0.121,0.313,0.095,0.312,0,0.214,0
        - 0.534,0.014,0.536,0.149,0.977,0.16,0.975,0.011
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
    ui:
      order: 3
    objects:
      filters:
        car:
          mask:
            - 0.355,0.227,0.352,0.027,0.749,0.114,1,0.248,1,0.677,0.502,0.465
            - 0.225,0.054,0.226,0.095,0.291,0.08,0.287,0.043
    audio:
      enabled: true  # Enable audio events globally
      listen:
        - smash
        - breaking
        - crack
        - glass
        - explosion
        - gunshot
        - machine_gun
        - fusillade
        - artillery_fire
        - cap_gun
        - fireworks
        - firecracker
        - burst
        - eruption
        - siren
        - civil_defense_siren
        - buzzer
        - smoke_detector
        - fire_alarm
        - alarm
        - knock
        - doorbell
        - ding-dong
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - skidding
        - honk
        - toot
        - car_alarm
        - fire
        - crackle
        - thunderstorm
        - thunder
        - bell
        - cat
        - purr
        - meow
        - hiss
        - dog
        - bark
        - yell

  garage_entry:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_entry
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_entry_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    ui:
      order: 4
    objects:
      filters:
        car:
          mask:
            - 0,0.287,0,0.382,0,0.495,0.63,0.198,0.48,0.11
            - 0.667,0.137,0.661,0.235,0.778,0.275,0.858,0.18
    audio:
      enabled: true  # Enable audio events globally
      listen:
        - smash
        - breaking
        - crack
        - glass
        - explosion
        - gunshot
        - machine_gun
        - fusillade
        - artillery_fire
        - cap_gun
        - fireworks
        - firecracker
        - burst
        - eruption
        - siren
        - civil_defense_siren
        - buzzer
        - smoke_detector
        - fire_alarm
        - alarm
        - knock
        - doorbell
        - ding-dong
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - skidding
        - honk
        - toot
        - car_alarm
        - fire
        - crackle
        - thunderstorm
        - thunder
        - bell
        - cat
        - purr
        - meow
        - hiss
        - dog
        - bark
        - yell

    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.507,0.038,0.514,0.092,0.974,0.09,0.977,0.031
  side_laneway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_laneway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_laneway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    ui:
      order: 5
    motion:
      mask:
        - 0,1,0.202,1,0.578,0.091,0.534,0,0.003,0
        - 0.531,0.026,0.527,0.099,0.979,0.1,0.979,0.028
    audio:
      enabled: true  # Enable audio events globally
      listen:
        - smash
        - breaking
        - crack
        - glass
        - explosion
        - gunshot
        - machine_gun
        - fusillade
        - artillery_fire
        - cap_gun
        - fireworks
        - firecracker
        - burst
        - eruption
        - siren
        - civil_defense_siren
        - buzzer
        - smoke_detector
        - fire_alarm
        - alarm
        - knock
        - doorbell
        - ding-dong
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - skidding
        - honk
        - toot
        - car_alarm
        - fire
        - crackle
        - thunderstorm
        - thunder
        - bell
        - cat
        - purr
        - meow
        - hiss
        - dog
        - bark
        - yell

  elliot_laneway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/elliot_laneway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/elliot_laneway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio

    ui:
      order: 6
    audio:
      enabled: true  # Enable audio events globally
      listen:
        - smash
        - breaking
        - crack
        - glass
        - explosion
        - gunshot
        - machine_gun
        - fusillade
        - artillery_fire
        - cap_gun
        - fireworks
        - firecracker
        - burst
        - eruption
        - siren
        - civil_defense_siren
        - buzzer
        - smoke_detector
        - fire_alarm
        - alarm
        - knock
        - doorbell
        - ding-dong
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - skidding
        - honk
        - toot
        - car_alarm
        - fire
        - crackle
        - thunderstorm
        - thunder
        - bell
        - cat
        - purr
        - meow
        - hiss
        - dog
        - bark
        - yell


    motion:
      mask: 0.511,0.033,0.511,0.083,0.977,0.088,0.978,0.033
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
  garden_area:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_area
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_area_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio

    ui:
      order: 7
    motion:
      mask: 0.532,0,0.526,0.258,0.711,1,0.997,0.997,0.999,0.001
    audio:
      enabled: true  # Enable audio events globally
      listen:
        - smash
        - breaking
        - crack
        - glass
        - explosion
        - gunshot
        - machine_gun
        - fusillade
        - artillery_fire
        - cap_gun
        - fireworks
        - firecracker
        - burst
        - eruption
        - siren
        - civil_defense_siren
        - buzzer
        - smoke_detector
        - fire_alarm
        - alarm
        - knock
        - doorbell
        - ding-dong
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - skidding
        - honk
        - toot
        - car_alarm
        - fire
        - crackle
        - thunderstorm
        - thunder
        - bell
        - cat
        - purr
        - meow
        - hiss
        - dog
        - bark
        - yell

  garage_area:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_area
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_area_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ui:
      order: 8

    motion:
      mask: 0.647,0.046,0.645,0.091,0.986,0.09,0.986,0.043
    objects:
      filters:
        car:
          mask: 0,1,1,1,1,0.843,1,0,0.444,0,0,0
  downstairs_area:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/downstairs_area
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/downstairs_area_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ui:
      order: 9
    motion:
      mask:
        - 0.586,0.905,0.922,0.9,0.923,0.959,0.58,0.962
        - 0.645,0.046,0.644,0.091,0.99,0.088,0.99,0.043
    review:
      alerts:
        labels: []

  upstairs_area:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upstairs_area
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/upstairs_area_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ui:
      order: 10
    review:
      alerts:
        labels: []
    motion:
      mask: 0.66,0.038,0.649,0.102,0.983,0.109,0.98,0.022

  elliot_food:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/elliot_food
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/elliot_food_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ui:
      order: 11
    review:
      alerts:
        labels: []
    motion:
      mask: 0.604,0.05,0.608,0.13,0.976,0.138,0.976,0.037

  roaming_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/roaming_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/roaming_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ui:
      order: 12
    review:
      alerts:
        labels: []
    motion:
      mask: 0.618,0.053,0.618,0.119,0.962,0.116,0.962,0.041


objects:
  track:
    - person
    - car
    - bicycle
    - dog
    - face
    - license_plate
    - package


  filters:
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85




camera_groups:
  Birdseye:
    order: 1
    icon: LuAlertTriangle
    cameras: birdseye
version: 0.14
```

### Relevant log output

```shell
(No relevant logs to attach at this time)
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Mix of Dahua & Dikvision

### Any other information that may be helpful

![Screenshot 2024-07-23 at 8 32 07 am](https://github.com/user-attachments/assets/eba52eab-f35b-4cc6-9dbf-d15ddce91f27)

Positive result with no sub-label ^

![Screenshot 2024-07-23 at 8 30 51 am](https://github.com/user-attachments/assets/152bdd60-1dfa-496a-ac0f-bd933ad9a4d2)
