### DISCUSSION TITLE
[Support]: Initial install

### DISCUSSION THREAD

**Discussion by montef** [blakeblackshear/frigate#12578] [General Support]
### Describe the problem you are having

I want to run frigate. I have an Intel Dell micro desktop machine that I have installed a fresh install of Debian Linux to.
I've spent multiple days now, looking at various web pages about how to install frigate. I'm very confused.

I'm not new to Linux, but I am new to frigate and to Docker.

Running frigate inside a Docker container seems to be the most popular method.

The extra layers of abstraction with Docker are confusing to my newbie brain.

It's 7/23/2024 as I type this. Could someone *PLEASE* give me a link to a known, working, newbie friendly; document or website that tells me how to get Docker running, and an instance of frigate for Docker that is known to work.

PLEASE, PLEASE, don't just reply with "RTFM".   I have read everything I can find. If it had worked for me, I wouldn't be posting this message.

I don't care about MQTT integration, or Home Assistant Integration. I just want to run frigate, connect to several PoE RTSP cameras, and record the cameras.
I just need the basics.

I'm absolutely begging for help here.  If there is someone who lives very close to the Tucker, GA area who has a working setup; and would be willing to help; I'll pay you to come to my house and get this up and running for me. I'm beyond frustrated with this.

### Version

I can't get this far yet. I have no idea.

### Frigate config file

```yaml
mqtt:
  enabled: False
Again, I don't have one yet. I can't get far enough to know where to put this frigate config file, what it should be named, how it should be formatted.  I don't have enough information.

Since I have to put something here, this is copied and pasted from:
https://docs.frigate.video/configuration/

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect
```

### Relevant log output

```shell
I don't have any log files yet. I can't get that far. :(
```

### FFprobe output from your camera

```shell
I don't know where to run this command. On the Debian host? Inside a Docker container? I don't know how to get this information.
```

### Frigate stats

```json
Same here. Where do I get this information.  This question seems to presume that you have a working system, which I do not yet have.  I need help getting to that point.
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

These are generic AliExpress RTSP PoE cameras.  I 100% know the cameras work. I'm using 28 of them on three different BlueIris NVR setups. 

### Any other information that may be helpful

I'm very new to Docker and to frigate. I just need help getting an instance up and running to the point that I can try to add cameras to it. I don't yet know what I don't know. I need a starting place that doesn't make the assumption that I know how to get a Docker container running, because I don't.
