### DISCUSSION TITLE
[HW Accel Support]: RK3328 (rock64) with '-rk' images

### DISCUSSION THREAD

**Discussion by fenouil-r** [blakeblackshear/frigate#12577] [Hardware Acceleration Support]
### Describe the problem you are having

Hi,

My apologies if this topic seems recurring, but after reading 10's of page on various forums, I still don't have a clear idea on how it is supposed to work.

My current setup is a Rock64 running on Ayufan's OMV 5 distribution. Since then I updated kernel up to '6.0.0-1164-ayufan-ga2fd0c498'.

Now I discover Frigate and the amazing world of transcoding, detectors... and potential hardware acceleration :)

With 4 cameras (1920x1080) streams (via go2rtc), I am close to a constant 100% cpu just for ffmpeg... So I'm wondering if I could get the hw acceleration working on this board, with my limited knowledge (Spoiler: No).

For now I just tried to:
 - pull "frigate:0.14.0-beta4-rk"
 - set `privileged: true` in Portainer stack
 - Add in Frigate config:
```
ffmpeg: 
    hwaccel_args: preset-rk-h264
``` 

Here are some of the logs (same error for all cameras):
```
2024-07-23 22:07:08.843508700  [2024-07-23 22:07:08] watchdog.C01                   ERROR   : Ffmpeg process crashed unexpectedly for C01.
2024-07-23 22:07:08.843528242  [2024-07-23 22:07:08] watchdog.C01                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-07-23 22:07:08.843535533  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : [h264_rkmpp @ 0xaaaace5e3120] Failed to init MPP context: -1
2024-07-23 22:07:08.843543991  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : [vist#0:0/h264 @ 0xaaaace49dd10] Error while opening decoder: Generic error in an external library
2024-07-23 22:07:08.843551283  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : [vost#0:0/rawvideo @ 0xaaaace587460] Error initializing a simple filtergraph
2024-07-23 22:07:08.843557116  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : Error opening output file pipe:.
2024-07-23 22:07:08.843564116  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : Error opening output files: Generic error in an external library
```

After getting a bash in the container and [testing ffmpeg](https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Encoder#test-encoders) directly with:
```
docker exec -it frigate bash
> ffmpeg -f lavfi -i testsrc2=s=1920x1080,format=nv12 -c:v hevc_rkmpp -qp_init 26 -profile:v main -level 4.1 -g:v 100 -vframes 5000 -y /tmp/tmp.mp4
```
I get:
```
# ffmpeg -f lavfi -i testsrc2=s=1920x1080,format=nv12 -c:v hevc_rkmpp -qp_init 26 -profile:v main -level 4.1 -g:v 100 -vframes 5000 -y /tmp/tmp.mp4     
ffmpeg version 9efe5bcff0-20240613 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.26.0.65_ecc5e41)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --disable-libvpx --enable-libwebp --enable-lv2 --disable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-rkmpp --enable-rkrga --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm
--disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lstdc++ -lstdc++ -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=aarch64-ffbuild-linux-gnu-gcc --cxx=aarch64-ffbuild-linux-gnu-g++ --ar=aarch64-ffbuild-linux-gnu-gcc-ar --ranlib=aarch64-ffbuild-linux-gnu-gcc-ranlib --nm=aarch64-ffbuild-linux-gnu-gcc-nm --extra-version=20240613
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, lavfi, from 'testsrc2=s=1920x1080,format=nv12':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, nv12, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn                                                                                     
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_rkmpp))
Press [q] to stop, [?] for help
[hevc_rkmpp @ 0xaaaafa0775d0] Failed to init MPP context: -1
[vost#0:0/hevc_rkmpp @ 0xaaaafa077270] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.                                              
Error while filtering: Generic error in an external library
[out#0/mp4 @ 0xaaaafa075f00] Nothing was written into output file, because at least one of its streams received no packets.                                                           
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A
Conversion failed!
```

This is where I started to read about hw acceleration on rockchip boards and realized I don't understand much about how this works :)

Here are my questions:

1. When using the docker image, should the host kernel provide some entries to the hw acceleration, or is this all handled from the container (hence privileged mode required) ?
 
2. What are the candidate kernels/distribution with such capability ?
I saw a lot of references to 5.10 and 6.1, but neither appear on my apt list...

3. From what I (poorly) understand, board vendors usually create kernels (bsp) exposing hw capabilities that end-up either integrated into mainline, or adapted to limited linux distributions (depending on community). Correct ?
Is it what Ayufan was providing for armbian on rockchip ? 

I can't figure a timeline of what solutions were made available to access hw acceleration on this board (kernels, patches, scripts, ...), and what would be the optimal solution today... 
Would it be possible to get a 'proper kernel' running with my current setup ?
If not, is there a debian distribution (I need OMV running) available for this board with the 'proper kernel' ?

That's already a lot, sorry... :)
Thank you for your help.

### Version

0.14.0-a4eb435

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx
  port: xxx
  user: xxx
  password: xxx

go2rtc:
  streams:
    C01:
      - rtsp://log:pass@xxx.xxx.xxx.xxx/unicast

ffmpeg:
  hwaccel_args: preset-rk-h264 # or preset-rk-h265


cameras:
  C01:
    enabled: true
    ffmpeg:
      #hwaccel_args: preset-rk-h264    
      inputs:
        - path: rtsp://127.0.0.1:8554/C01
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed



version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    # 'privileged' for accessing rockchip acceleration only (rk)
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4-rk
    shm_size: "512mb" # update for your cameras based on calculation above
    #devices:
      #- /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11  # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - xxx:/config
      - xxx:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1935:1935"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "pass"
```

### Relevant log output

```shell
2024-07-23 22:07:08.843508700  [2024-07-23 22:07:08] watchdog.C01                   ERROR   : Ffmpeg process crashed unexpectedly for C01.
2024-07-23 22:07:08.843528242  [2024-07-23 22:07:08] watchdog.C01                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-07-23 22:07:08.843535533  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : [h264_rkmpp @ 0xaaaace5e3120] Failed to init MPP context: -1
2024-07-23 22:07:08.843543991  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : [vist#0:0/h264 @ 0xaaaace49dd10] Error while opening decoder: Generic error in an external library
2024-07-23 22:07:08.843551283  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : [vost#0:0/rawvideo @ 0xaaaace587460] Error initializing a simple filtergraph
2024-07-23 22:07:08.843557116  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : Error opening output file pipe:.
2024-07-23 22:07:08.843564116  [2024-07-23 22:07:08] ffmpeg.C01.detect              ERROR   : Error opening output files: Generic error in an external library
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://log:pass@xxx.xxx.xxx.xxx/unicast
ffprobe version 9efe5bcff0-20240613 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.26.0.65_ecc5e41)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --disable-libvpx --enable-libwebp --enable-lv2 --disable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-rkmpp --enable-rkrga --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lstdc++ -lstdc++ -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=aarch64-ffbuild-linux-gnu-gcc --cxx=aarch64-ffbuild-linux-gnu-g++ --ar=aarch64-ffbuild-linux-gnu-gcc-ar --ranlib=aarch64-ffbuild-linux-gnu-gcc-ranlib --nm=aarch64-ffbuild-linux-gnu-gcc-nm --extra-version=20240613
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, rtsp, from 'rtsp://log:pass@xxx.xxx.xxx.xxx/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 0.067556, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 15.17 tbr, 90k tbn
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dafang (wize)
