### DISCUSSION TITLE
[Support]: how do I enable bounding boxes on events|snapshots?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#12570] [General Support] [answered]
### Describe the problem you are having

hello all

When I go to events|snapshots, this is a typical image:
![Screenshot at 2024-07-23 12-45-58](https://github.com/user-attachments/assets/c98eae04-e54d-48ea-bcd9-2cc98fe30536)

What I want it to look like is this (my hand-drawn simulation showing a bounding box - the image is supposed to be the same size as the one above):
![Screenshot at 2024-07-23 12-45-58_marked](https://github.com/user-attachments/assets/58b6b9b7-41dc-4cba-a022-221a27106cef)

That's so that, when I then decide whether to submit it to Frigate+, it is easy to see what Frigate thinks it has seen.  At the moment, Frigate might spot a cat and a dog and a person and detect "dog" but, without actually submitting it, I won't find out whether the dog is ID'd as a dog, or if a cat has been mistaken for a dog.

Perhaps there is something missing in my config (attached) - I have searched and I've looked at the config docs but it has eluded me (probably because I am still learning, rather slowly!).

Please can you share any advice?

Thanks

EB

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  enabled: false


go2rtc:
  streams:
    
    #reference format from NickM-27 @ https://github.com/blakeblackshear/frigate/discussions/12376 
    #   "ffmpeg:rtsp://...                                               #video=h264#audio=copy#hardware" note the quotes and hashes
    greenhouse:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:greenhouse#audio=opus"
    upper_patio:   
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:upper_patio#audio=opus"
    ponds:         
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:ponds#audio=opus"
    blue_gate:     
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:blue_gate#audio=opus"
    lower_steps:   
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:lower_steps#audio=opus"
    lower_patio:   
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:lower_patio#audio=opus"
    shed:          
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:shed#audio=opus"
    drive:         
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0#video=h264#audio=copy#hardware"
      - "ffmpeg:drive#audio=opus"
    

####rtsp is 30060 and webRTC is 30061 (TN Frigate app interrnals)
  webrtc:
    candidates:
    - 192.168.1.194:30061
    - stun:30061


ffmpeg:
  #####you can only have one line here#####
  hwaccel_args: preset-nvidia-h264
  #hwaccel_args: preset-nvidia-hevc #gives black screens on cameras
  #hwaccel_args: preset-nvidia-cuvid #gives black screens on cameras
  
detectors:
  coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

birdseye:
  enabled: true
  mode: continuous #continuous | objects | motion

# record: # <----- Enable recording # was working
#  enabled: true # was working

# added from https://fixtse.com/blog/coral-ia-frigate start#
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
# added from https://fixtse.com/blog/coral-ia-frigate #

  
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true #false  #true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 768
  #height: 800
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 7
      cat: 7
      dog: 7
      bird: 7
      fox: 7
      badger: 7
      car: 7
      licence_plate: 7

  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

##########################################################
##########################################################
# go2rtc: # this worked from https://docs.frigate.video/configuration/live/#setting-stream-for-live-ui
#  streams:
#    upper_patio:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 # <- stream which supports video & aac audio.
#    - "ffmpeg:upper_patio#audio=opus" # <- copy of the stream which transcodes audio to opus for webrtc
#    restream: true        
#    upper_patio_sub:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 # <- stream which supports video & aac audio.
#    - "ffmpeg:upper_patio_sub#audio=opus"
##########################################################
##########################################################

motion:
  improve_contrast: True




##########################################################
##########################################################
##########################################################
##########################################################
##########################################################


cameras: #########UPPER_PATIO#############################
  upper_patio:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
      #- path: http://truenas.local:8082/media=0/channel=1&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
      #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #input_args: preset-rtsp-restream

        roles:
        - detect

      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 1

    motion:
      mask: 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      upper patio:
        coordinates: 640,360,640,337,610,312,603,297,594,279,564,256,524,255,510,242,487,220,451,203,435,201,421,187,409,166,392,152,334,146,274,138,215,142,122,145,78,162,23,202,0,360


  blue_gate: #########BLUE_GATE#############################
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
      #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
      #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
        input_args: preset-rtsp-restream

        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placehlder
      - badger # placeholder
      - car
      - licence_plate

    birdseye:
      mode: continuous   #continuous | objects | motion
      # masks are black: they block out areas where you aren't interested in detecting things
      order: 2

    motion:
      mask:
      - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
      - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360

    zones:
      gravel:
        coordinates: 411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233

  drive: #########DRIVE#############################
    enabled: true

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
      - car
      - licence_plate

    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; changing track0 to track1 didn't work)
      #input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;(changing track0 to track1 didn't work)
        roles:
        - record

    birdseye:
      mode: continuous #continuous | objects | motion
      #restream: True
      order: 4

    motion:
      # masks are black: they block out areas where you aren't interested in detecting things
      mask:
      - 98,129,170,113,189,0,0,0,0,0,0,142
      - 273,0,170,0,178,67,258,117,256,191,414,181,640,307,640,0

    # zones are red: they select areas where monitoring of activity is wanted
    zones:
      driveway:
        coordinates: 78,360,248,360,381,360,640,360,640,276,449,177,303,183,298,129,200,64,144,113,0,127,0,360


  lower_patio: #########LOWER_PATIO#############################
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox   #placeholder
      - badger   #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 3

      # masks are black: they block out areas where you aren't interested in detecting things
    motion:
      mask:
      - 0,148,92,104,184,55,253,0,269,154,272,305,318,125,354,107,345,56,406,60,417,131,504,240,570,360,640,360,640,0,0,0
        #- 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      lower patio:
        coordinates: 284,360,303,183,333,157,344,139,357,118,352,99,359,74,382,73,384,110,403,128,499,246,580,360

#-----------------------END-----------------------#
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not relevant
```

### Operating system

Other Linux

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

various Hikvision copies

### Any other information that may be helpful

iX systems frigate app (Docker/K3S/helm/other) installed in TrueNAS Scale Dragonfish (Debian based with ZFS additions)
