### DISCUSSION TITLE
[Config Support]: set filter on camera level

### DISCUSSION THREAD

**Discussion by maxx-ukoo** [blakeblackshear/frigate#12584] [Config Support] [answered]
### Describe the problem you are having

I want to set min_area for people for specific camera. All examples show camera->zones->zone->filter. But I doesn't have zones. Is it possible to set person filter on camera level without zones? It is PTZ camera, zone not related to this camera.

filters:
  person:
    min_area: 500
How I can add this to specific camera?

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: *****************

database:
  path: /opt/db/frigate.db

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: True
  retain:
    days: 15
    mode: all
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog
    - bird
detectors:
  coral:
    type: edgetpu
    device: ""

cameras:
  R-PTZ-CAM04:
    ffmpeg:
      inputs:
        - path: rtsp://*****************:*****************@1*****************/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://*****************:*****************@*****************:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: False
    motion:
      improve_contrast: True
    onvif:
      host: *****************
      port: 8000
      user: view
      password: *************
```

### Relevant log output

```shell
no related logs
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

Coral

**Comment by NickM-27** [comment, marked as answer]
You set it on the camera level

```yaml
cameras:
  R-PTZ-CAM04:
    ffmpeg:
      inputs:
        - path: rtsp://*****************:*****************@1*****************/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://*****************:*****************@*****************:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: False
    objects:
      filters:
        person:
          min_area: 500
```

**Reply by maxx-ukoo** [reply]
@NickM-27 with min_area 300 I got person alert with detected area 216 and ratio 0.67. Is it expected behavior?

**Reply by NickM-27** [reply]
did you set filter on a zone or the camera itself?

**Reply by maxx-ukoo** [reply]
on camera:
```
  R-PTZ-CAM04:
    ffmpeg:
      inputs:
        - path: rtsp://v:v@10.0.10.19:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://v:v@10.0.10.19:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: False
    objects:
      filters:
        person:
          min_area: 300
    motion:
      improve_contrast: True
    onvif:
      host: 10.23.10.19
      port: 8000
      user: v
      password: 
```
Is 300 px related to detect or record stream?
Detect stream: 896x512
Record stream: 3840x2160
I see box with this info (it is not full image):
![image](https://github.com/user-attachments/assets/56a89b1c-884a-43aa-846a-640cc1a8551c)
