### DISCUSSION TITLE
[Detector Support]: USB Coral - "detector stuck- force killing"

### DISCUSSION THREAD

**Discussion by kwsabq** [blakeblackshear/frigate#12595] [Detector Support]
### Describe the problem you are having

Have had Frigate up and running for a while now, all smooth sailing and working wonderfully. However 4 days ago I started to see the watchdog errors come up for my detector. Log is found in the relevant section. 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 192.XXX.X.XXX
  user: XXXX
  password: XXXXX

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://dfe4ce8e577250XXXXXXXXXX

go2rtc:
  log:
    exec: trace
  streams:
    Front_Camera:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_main
    Front_Camera_Sub:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_sub
    Doorbell_Camera:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_main
    Doorbell_Camera_Sub:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_sub
    Back_Camera:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_main
    Back_Camera_Sub:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_sub
    Side_Camera:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_main
    Side_Camera_Sub:
    - rtsp://XXXX:XXXX@192.XXX.XX.XXXX:554/Preview_01_sub

birdseye:
  enabled: true
  mode: objects

cameras:
  # reolink duo 2 w/flood #
  Front_Camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://localhost:8554/Front_Camera_Sub
        roles:
        - detect
      - path: rtsp://localhost:8554/Front_Camera
        roles:
        - record
      hwaccel_args: preset-vaapi
    detect:
      width: 1280
      height: 720
      enabled: true
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
      - person
      - face
      - car
      - amazon
      - fedex
      - ups
      - dog
      - package
      filters:
        car:
          mask:
          - 279,293,362,292,371,230,299,237
          - 322,315,578,324,585,244,341,250
          - 734,720,1210,720,1226,638,908,417,310,363,77,720
          - 881,312,969,323,965,272,883,263
          - 0,432,164,370,120,315,0,333
          - 1032,331,1097,345,1083,305,1031,294
          min_score: .75
          threshold: .9
        dog:
          min_score: .65
          threshold: .85
        person:
          min_score: .65
          threshold: .85
        package:
          mask:
            - 38,670,103,638,78,556,0,578
          min_score: .7
          threshold: .8
    motion:
      mask:
      - 0,293,594,290,1280,342,1280,0,0,0
    zones:
      Front_street:
        coordinates: 
          182,371,336,384,554,407,728,410,959,410,1097,394,1034,351,744,318,440,304,281,312
        objects:
        - person
        - car
        - amazon
        - fedex
        - ups
      Front_yard:
        coordinates: 0,720,1217,720,1224,638,859,403,668,404,184,370,75,390,0,423
        objects:
        - person
        - face
        - dog
        - package
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        required_zones:
        - Front_street
        - Front_yard
        pre_capture: 10
        post_capture: 10
        retain:
          default: 7
          objects:
            dog: 1
            car: 1
    snapshots:
      enabled: true
      retain:
        default: 7
        objects:
          car: 1

# side yard camera #
  Side_Camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/Side_Camera_Sub
          roles:
            - detect
        - path: rtsp://localhost:8554/Side_Camera
          roles:
            - record
      hwaccel_args: preset-vaapi
    detect:
      width: 1280
      height: 720
      enabled: true
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
        - person
        - face
        - cat
        - dog
      filters:
        person:
          min_score: .75
          threshold: .85
        dog:
          min_score: .75
          threshold: .8
        cat:
          min_score: .75
          threshold: .8
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        retain:
          default: 7
          objects:
            cat: 1
            dog: 1
    snapshots:
      enabled: true
      retain:
        default: 7


# Doorbell camera#
  Doorbell_Camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://localhost:8554/Doorbell_Camera_Sub
        roles:
        - detect
      - path: rtsp://localhost:8554/Doorbell_Camera
        roles:
        - record
      hwaccel_args: preset-vaapi
    detect:
      width: 1280
      height: 720
      enabled: true
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
      - person
      - face
      - package
      - dog
      - cat
      filters:
        person:
          min_score: .75
          threshold: .85
        dog:
          min_score: .75
          threshold: .8
        cat:
          min_score: .75
          threshold: .8
        package:
          min_score: .7
          threshold: .8
    motion:
      mask:
      - 375,180,729,203,748,344,455,342,187,328,0,319,0,209
    zones:
      Walk_Way:
        coordinates: 407,720,408,573,738,221,1280,129,1280,720
        objects:
        - person
        - face
        - dog
        - cat
        - package
    record:
      enabled: true
      retain:
        days: 0
      events:
        required_zones:
        - Walk_Way
        pre_capture: 10
        post_capture: 10
        objects:
        - person
        - face
        - package
        - cat
        retain:
          default: 7
          objects:
            cat: 1
    snapshots:
      enabled: true
      retain:
        default: 7

#Backyard Camera#
  Back_Camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://localhost:8554/Back_Camera_Sub
        roles:
        - detect
      - path: rtsp://localhost:8554/Back_Camera
        roles:
        - record
      hwaccel_args: preset-vaapi
    detect:
      width: 1280
      height: 720
      enabled: true
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
      - person
      - face
      - dog
      - cat
      filters:
        person:
          min_score: .75
          threshold: .85
        dog:
          min_score: .75
          threshold: .85
        cat:
          min_score: .75
          threshold: .85
    zones:
      Back_Door:
        coordinates: 1280,0,1280,720,881,720,1077,0
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        objects:
        - person
        - dog
        - cat
        retain:
          default: 7
          objects:
            dog: 1
            cat: 1
    snapshots:
      enabled: true
      retain:
        default: 7
        objects:
          dog: 1
          cat: 1
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant log output

```shell
2024-07-23 15:12:04.975164928  [2024-07-23 09:12:02] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-07-23 15:12:04.977755008  [2024-07-23 09:12:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-07-24 02:33:33.092506576  [2024-07-23 20:33:33] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2024-07-24 02:33:33.092631378  [2024-07-23 20:33:33] root                           INFO    : Waiting for detection process to exit gracefully...
2024-07-24 02:34:03.110589196  [2024-07-23 20:34:03] root                           INFO    : Detection process didnt exit. Force killing...
2024-07-24 02:34:03.135410787  [2024-07-23 20:34:03] root                           INFO    : Detection process has exited...
2024-07-24 02:34:03.152760648  [2024-07-23 20:34:03] detector.coral                 INFO    : Starting detection process: 784773
2024-07-24 02:34:05.768652772  [2024-07-23 20:34:03] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-07-24 02:34:05.772999899  [2024-07-23 20:34:05] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-07-24 07:30:13.479469900  [2024-07-24 01:30:13] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2024-07-24 07:30:13.479612709  [2024-07-24 01:30:13] root                           INFO    : Waiting for detection process to exit gracefully...
2024-07-24 07:30:43.509007464  [2024-07-24 01:30:43] root                           INFO    : Detection process didnt exit. Force killing...
2024-07-24 07:30:43.524817180  [2024-07-24 01:30:43] root                           INFO    : Detection process has exited...
2024-07-24 07:30:43.540042668  [2024-07-24 01:30:43] detector.coral                 INFO    : Starting detection process: 918408
2024-07-24 07:30:43.547144730  [2024-07-24 01:30:43] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-07-24 07:30:46.167118358  [2024-07-24 01:30:46] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Any other information that may be helpful

It seems to start back up fine and work perfectly for a long while, but it is happening everyday now and I do not want the problem to get worse.

We did have a major power outage 5 days ago, right before this started to happen. But I do not see how that would have any effect on the Coral.
