### DISCUSSION TITLE
[Detector Support]: Coral USB: Worse detection than CPU detector

### DISCUSSION THREAD

**Discussion by tuxedo0801** [blakeblackshear/frigate#12598] [Detector Support]
### Describe the problem you are having

Started using Coral USB... changed config according to documentation (had CPU detector before... but switched to Coral to reduce cpu load).
Works in principle. But detection is now very bad.
Example: Detects cars where there are no cars, even if cars are on the image...

![image](https://github.com/user-attachments/assets/e560149b-7e3b-4d6c-b0e4-e5e9a0a08c03)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: blackbox.lan
  port: 1883
  topic_prefix: frigate
  user: user
  password: pass

#detectors:
#  ov:
#    type: openvino
#    device: AUTO
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


detectors:
  coral:
    type: edgetpu
    device: usb      


record:
  enabled: True
#  sync_recordings: True
  retain:
    days: 7
#    mode: motion
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: 5)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: 5)
    post_capture: 5
    retain:
      default: 30
      mode: motion
      
objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package     
      
snapshots:
  enabled: True
  retain:
    default: 30 
    # Optional: Per object retention days
    objects:
      person: 15     
      
birdseye:
  enabled: true   
  mode: continuous
  width: 1920
  height: 1080
  inactivity_threshold: 15     
  restream: true
  
# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%Y-%m-%d %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  #effect: "solid"

detect:
  stationary:
    interval: 50
    threshold: 50

cameras:

  # rtsp://admin:@192.168.200.11:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream --> H264 1920x1080
  # rtsp://admin:@192.168.200.11:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream --> H264 704x576

  Einfahrt:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:@192.168.200.12:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
        roles:
        - record
      - path: 
          rtsp://admin:@192.168.200.12:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream
        roles:
        - detect
    zones:
      haustuer:
        coordinates: 1291,0,1292,375,1146,431,1046,361,1070,0
      einfahrt:
        coordinates: 967,347,1138,481,1318,423,1238,1080,203,1080,68,690,414,422
      strasse:
        coordinates: 0,721,0,579,537,183,576,303
    motion:
      mask:
      - 1085,317,1073,0,512,26,531,401
    birdseye: 
      enabled: true
  Garten:
    enabled: false
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:@192.168.200.11:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
        roles:
        - record
      - path: 
          rtsp://admin:@192.168.200.11:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream
        roles:
        - detect
    zones:
      nachbar:
        coordinates: 266,103,725,46,722,0,284,0
      terasse:
        coordinates: 577,144,1688,1080,97,1080,55,152
    birdseye: 
      enabled: true       
  Reserve:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:@192.168.200.10:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
        roles:
        - record
      - path: 
          rtsp://admin:@192.168.200.10:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream
        roles:
        - detect
```

### docker-compose file or Docker CLI command

```yaml
# see: https://docs.frigate.video/frigate/installation
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/mirror/docker/frigate/config:/config
      - /media/mirror/docker/frigate/storage:/media/frigate
#      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
#        target: /tmp/cache
#        tmpfs:
#          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "xxxxxxxxxxxxxxxxxxxxx"
```

### Relevant log output

```shell
no relevant log output so far...?!
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

Either it's causes by the Coral USB, or a model updated did come with a update of my frigate docker container... No idea. Fact is: Detection is almost useless.
