### DISCUSSION TITLE
Review time offset of recorded clip

### DISCUSSION THREAD

**Discussion by lukicsl** [blakeblackshear/frigate#12592] [Report a Bug] [answered]
### Describe the problem you are having

On the review page the snapshots shows the moment the event (object detection) hapenend , e.g:15:00:00. When hoovering over the snapshot a fast-forward shows a video sequence starting with event - pre_capture (in my case 10s), e.g: 14:59:50 .
When clicking on the snapshot the recorded clip start late, e.g: 15:00:30.
Expected: the clip should start event - pre_capture (in my case 10s), e.g: 14:59:50

### Steps to reproduce

go to review page
hover over the snapshot
click on the snapshot
compare the times to be as expected

### Version

0.14.0 beta 4

### Frigate config file

```yaml
mqtt:
  client_id: frigate-pro
  topic_prefix: frigate-pro
  host: 192.168.3.140
  user: openhab
  password: .*.

go2rtc:
  streams:
    #housedooraudio: exec:ffmpeg -f mulaw -ar 8000 -i http://ghtwga0002:AefHv5TnWx@192.168.3.160/bha-api/audio-receive.cgi -f rtsp {output}
    housedoor:
      - rtsp://ghtwga0002:*@192.168.3.160/mpeg/1080p/media.amp
      - ffmpeg:front_garden#audio=opus
    housedoor_sub:
      - rtsp://ghtwga0002:*@192.168.3.160/mpeg/media.amp
      - ffmpeg:front_garden#audio=opus
    front_garden:
      - rtsp://admin:***@192.168.3.161:554//h265Preview_01_main
      - ffmpeg:front_garden#audio=opus
    front_garden_sub:
      - rtsp://admin:***@192.168.3.161:554//h264Preview_01_sub
      - ffmpeg:front_garden_sub#audio=opus
    garage:
      - rtsp://admin:***@192.168.3.162:554//h265Preview_01_main
      - ffmpeg:garage#audio=opus
    garage_sub:
      - rtsp://admin:***@192.168.3.162:554//h264Preview_01_sub
      - ffmpeg:garage_sub#audio=opus
    garden:
      - rtsp://admin:***@192.168.3.163:554//h265Preview_01_main
      - ffmpeg:garden#audio=opus
    garden_sub:
      - rtsp://admin:***@192.168.3.163:554//h264Preview_01_sub
      - ffmpeg:garden_sub#audio=opus
detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  stationary:
    interval: 10
    threshold: 50

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 10
    post_capture: 30
    retain:
      default: 28
      mode: active_objects


cameras:
  housedoor:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    motion:
      mask: 
        0,0.48,0.246,0.508,0.247,0.601,0.463,0.598,0.463,0.484,0.323,0.472,0.323,0.413,0.252,0.372,0.266,0.19,0.298,0,0,0
    zones:
      eingang:
        coordinates: 0,506,0,720,937,720,731,486,665,486,664,435,418,441,411,380,268,364,0,363
      duncovci:
        coordinates: 0.581,0.609,0.468,0.593,0.465,0.491,0.581,0.483
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/housedoor?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/housedoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    review:
      alerts:
        required_zones: eingang
      detections:
        required_zones: duncovci
  front-garden:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    zones:
      eingang:
        coordinates: 0.274,0.122,0.278,0.594,0.235,0.608,0.35,1,0.184,1,0.118,0.56,0.108,0.151
        inertia: 3
      sitzplatz:
        coordinates: 0.742,0.807,0.737,0.878,0.586,1,0.352,1,0.239,0.61,0.555,0.515
        inertia: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_garden
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    review:
      alerts:
        required_zones:
          - eingang
          - sitzplatz
      detections: {}
    motion:
      mask:
        - 0.557,0.513,0.508,0.491,0.51,0.441,0.507,0.379,0.555,0.364,0.575,0.06,0.994,0.343,0.999,0.997,0.607,0.995,0.738,0.888,0.742,0.808
        - 0.292,0.58,0.213,0.598,0.184,0.445,0.211,0.413,0.25,0.397,0.287,0.402
        - 0.35,0.937,0.349,0.972,0.64,0.971,0.641,0.935
  garage:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    zones:
      autos:
        coordinates: 0.479,0.106,0.507,0.259,0.609,0.31,0.73,0.607,0.856,1,0.305,1,0.326,0.1
        inertia: 3
      strasse:
        coordinates: 
          0.372,0.006,0.504,0.268,0.607,0.542,0.788,0.992,0.993,0.99,0.996,0.572,0.911,0.445,0.796,0.288,0.686,0.176,0.597,0.086,0.557,0.046,0.511,0.005
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    review:
      alerts:
        required_zones: autos
      detections:
        required_zones: strasse
    motion:
      mask:
        - 0,0,0,1,0.302,1,0.316,0.532,0.318,0.073,0.324,0.007
        - 0.348,0.94,0.641,0.938,0.642,0.976,0.348,0.98
  garden:
    snapshots:
      enabled: true
      timestamp: false # Whether to include timestamp on snapshots
      bounding_box: true # Whether to include bounding box on snapshots
      crop: false # Whether to crop the snapshot to the detected object
      height: 700 # Height for snapshots (optional, if you want to resize)
    zones:
      weg:
        coordinates: 0.11,0.46,0.128,0.455,0.155,0.736,0.099,0.747
        inertia: 3
      wiese:
        coordinates: 0.636,0.619,0.953,0.768,0.996,0.787,0.946,0.822,0.936,1,0.249,0.994,0.158,0.742
        inertia: 3
      terasse:
        coordinates: 0.688,0.596,0.999,0.692,1,0.29,0.684,0.308
        inertia: 3
      stockwerk:
        coordinates: 0.593,0.19,0.595,0.006,0.993,0,0.996,0.078
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    review:
      alerts:
        required_zones:
          - weg
          - wiese
          - terasse
          - stockwerk
    motion:
      mask:
        - 0.003,0.344,0.106,0.315,0.109,0.46,0.097,0.744,0.175,0.997,0.002,0.994
        - 0.109,0.315,0.114,0.454,0.13,0.452,0.162,0.739,0.631,0.604,0.635,0.291,0.594,0.277,0.59,0.068,0.591,0,0.006,0.01,0.006,0.333
        - 0.349,0.934,0.349,0.975,0.641,0.971,0.64,0.938
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
version: 0.14
```

### Relevant log output

```shell
no relevant log entries for the time of execution
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolink
