### DISCUSSION TITLE
[Config Support]: Nested options for review labels and zones for detections and alerts

### DISCUSSION THREAD

**Discussion by seansheep** [blakeblackshear/frigate#12601] [Config Support] [answered]
### Describe the problem you are having

Is the following plain-english description of my alert/detection "review" preferences possible with the current (0.14.0-beta4) configuration schema?

- Camera "front_yard" with a single zone called "driveway" (only covering part of the camera's area)
- "Alert" only for cars in driveway zone
- "Detection" for cars anywhere else
- "Alert" for person anywhere on the camera (not limited to the driveway zone)

I can currently limit "alerts" to by zone or by label, but I can't see if it's possible to combine the two on a more granular level.

### Version

0.14.0-beta4

### Frigate config file

```yaml
front_yard:
  [...]  
  review:
      alerts:
        required_zones: driveway
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

**Comment by NickM-27** [comment]
yes, this is possible. You basically have it figured out, you just need 1 more zone that covers the entire camera and only considers `person` and add that to alerts too

**Comment by seansheep** [comment, marked as answer]
Ahh ok thanks - So I think the missing piece was making the zone that was limited to the particular object.

So what I've done is (i've changed the names of the zones a bit to make it clearer):

```
 front_yard:
    [stuff...]
    zones:
      top_driveway_car_alert_zone:
        coordinates: 0.004,0.517,0.325,0.476,0.422,0.792,0.003,0.828
        objects: car
      front_person_alert_zone:
        coordinates: 0,0,1,0,1,1,0,1
        objects: person
    review:
      alerts:
        required_zones:
          - top_driveway_car_alert_zone
          - front_person_alert_zone
```

Is this the approach you were thinking?
