### DISCUSSION TITLE
[Config Support]: HAProxy on Pfsense to frigate:5000

### DISCUSSION THREAD

**Discussion by phipac** [blakeblackshear/frigate#12615] [Config Support]
### Describe the problem you are having

I am wanting to incorporate my Frigate instance in my HAProxy setup on pfsense. I have multiple other sites and services working through HAProxy, so I know my basic setup works. However, I am unable to bring up a backend that is set to frigateip:5000. I get the following error on Chrome browser:

ERR_EMPTY_RESPONSE

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: 172.x.x.x
  user: homeassistant
  password: private

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    Back_Door:
      - rtsp://zm:private@172.19.5.30:554/cam/realmonitor?channel=1&subtype=0
    Front_Door:
      - rtsp://admin:private@172.19.5.20:554/live0.264

birdseye:
  enabled: True
  mode: continuous

cameras:
  Back_Door:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Back_Door
        input_args: preset-rtsp-restream
        roles:
          - detect
          - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    objects:
      track:
      - person
      - dog
      - cat
#      - car
#      - motorcycle
#      - bicycle

  Front_Door:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Front_Door
        input_args: preset-rtsp-restream
        roles:
          - detect
          - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    objects:
      track:
      - person
      - dog
      - cat
#      - car
#      - motorcycle
#      - bicycle

ffmpeg:
#  hwaccel_args: preset-intel-qsv-h264
  hwaccel_args: preset-vaapi
database:
  path: /db/frigate.db
```

### Relevant log output

```shell
Nothing pertaining to the proxy problem.
```

### Frigate stats

```json
{"cameras":{"Back_Door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":251,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":433838,"pid":246,"process_fps":5.1,"skipped_fps":0.0},"Front_Door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":254,"detection_enabled":1,"detection_fps":14.0,"ffmpeg_pid":436882,"pid":248,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"44":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"101":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"3.8","cpu_average":"3","mem":"0.6"},"109":{"cmdline":"python3 -u -m frigate","cpu":"0.9","cpu_average":"0","mem":"9.7"},"115":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.1"},"120":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"223":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"225":{"cmdline":"frigate.recording_manager","cpu":"0.3","cpu_average":"0","mem":"2.3"},"234":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.2","cpu_average":"0","mem":"0.2"},"236":{"cmdline":"frigate.output       ","cpu":"0.4","cpu_average":"0","mem":"1.9"},"243":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"244":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"246":{"cmdline":"frigate.process:Back_Door","cpu":"0.9","cpu_average":"1","mem":"2.5"},"247":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"1.3"},"248":{"cmdline":"frigate.process:Front_Door","cpu":"3.0","cpu_average":"1","mem":"2.7"},"251":{"cmdline":"frigate.capture:Back_Door","cpu":"0.7","cpu_average":"0","mem":"1.8"},"254":{"cmdline":"frigate.capture:Front_Door","cpu":"0.7","cpu_average":"0","mem":"1.8"},"147615":{"cmdline":"frigate.detector.coral","cpu":"20.3","cpu_average":"9","mem":"6.7"},"433838":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Back_Door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Back_Door@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.2","cpu_average":"3","mem":"2.1"},"436882":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Front_Door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Door@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"1.8"},"443572":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":14.5,"detectors":{"coral":{"detection_start":1721934227.076126,"inference_speed":14.87,"pid":147615}},"gpu_usages":{"intel-vaapi":{"gpu":"7.84%","mem":"-%"}},"processes":{"go2rtc":{"pid":101},"logger":{"pid":223},"recording":{"pid":225}},"service":{"last_updated":1721934227,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":248.6,"mount_type":"tmpfs","total":256.0,"used":7.4},"/media/frigate/clips":{"free":3094923.7,"mount_type":"cifs","total":3940930.1,"used":846006.4},"/media/frigate/recordings":{"free":3094923.7,"mount_type":"cifs","total":3940930.1,"used":846006.4},"/tmp/cache":{"free":941.8,"mount_type":"tmpfs","total":953.7,"used":11.9}},"temperatures":{},"uptime":257098,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

I've read some posts about websockets, but I've not found anything specific to HAProxy on pFsense.
