### DISCUSSION TITLE
[Detector Support]: OpenVINO won't run yolox-tiny model (0.14.0 beta 4)

### DISCUSSION THREAD

**Discussion by alphapuggle** [blakeblackshear/frigate#12613] [Detector Support] [answered]
### Describe the problem you are having

When using yolox-tiny (converted with `omz_converter --name yolox-tiny`) OpenVino fails with error `[GPU] Mismatch tensor and port type: f32 vs u8`

### Version

0.14.0 beta 4 on Fedora Server 40 

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.2
  user: frigate
  password: xxxxxxxxxxxxx

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU
    model:
        #path: /openvino-model/ssdlite_mobilenet_v2.xml
      path: /config/models/yolox-tiny/FP32/yolox-tiny.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolox
  labelmap_path: /config/models/yolox-tiny/FP32/coco_80cl.txt

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:xxxxxxxx@192.168.1.10:554/Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: true
  back_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:xxxxxxxx@192.168.1.11:554/Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: true

go2rtc:
  streams:
    front_porch:
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxxx"
```

### Relevant log output

```shell
frigate  | 2024-07-25 12:41:32.700006682  Process detector:ov:
frigate  | 2024-07-25 12:41:32.700649883  Traceback (most recent call last):
frigate  | 2024-07-25 12:41:32.700697614    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-07-25 12:41:32.700699345      self.run()
frigate  | 2024-07-25 12:41:32.700700911    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-07-25 12:41:32.700702452      self._target(*self._args, **self._kwargs)
frigate  | 2024-07-25 12:41:32.700704062    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
frigate  | 2024-07-25 12:41:32.700705506      detections = object_detector.detect_raw(input_frame)
frigate  | 2024-07-25 12:41:32.700706843    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
frigate  | 2024-07-25 12:41:32.700708114      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate  | 2024-07-25 12:41:32.700709796    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 160, in detect_raw
frigate  | 2024-07-25 12:41:32.700711200      infer_request.infer(input_tensor)
frigate  | 2024-07-25 12:41:32.700723337    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 132, in infer
frigate  | 2024-07-25 12:41:32.700724282      return OVDict(super().infer(_data_dispatch(
frigate  | 2024-07-25 12:41:32.700725319  RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:116:
frigate  | 2024-07-25 12:41:32.700726316  Exception from src/inference/src/cpp/infer_request.cpp:66:
frigate  | 2024-07-25 12:41:32.700727565  Check 'port.get_element_type() == tensor->get_element_type()' failed at src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp:144:
frigate  | 2024-07-25 12:41:32.700728460  [GPU] Mismatch tensor and port type: f32 vs u8
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

OpenVino

### Any other information that may be helpful

The detector was functioning using openvino on ssdlite_mobilenet_v2, it would just continuously classify my neighbor's mailbox as a person
![image](https://github.com/user-attachments/assets/8a423b42-1c3a-42e6-b994-2432d661632d)
