### DISCUSSION TITLE
[Config Support]: Thumbnail/snapshot not showing in iOS notification

### DISCUSSION THREAD

**Discussion by chienb** [blakeblackshear/frigate#12619] [Config Support] [answered]
### Describe the problem you are having

Thumbnail/snapshot are not showing up in iOS notification. However, when using the notification Blueprint tapping the action button to view snapshot works. the url is: `[local ip address]:8123/api/frigate/notifications/1721808659.304718-j1yodc/snapshot.jpg?external_auth=1`

![image](https://github.com/user-attachments/assets/b1c2878a-0eb0-41a1-a252-3af9aa4c7104)

Accessing the snapshot from Frigate integration also works. 

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: ***

go2rtc:
  streams:
    front_door:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh
      camera.front_door
    side_yard:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh
      camera.side_yard

cameras:
  front_door:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_door?video
        input_args: preset-rtsp-restream-low-latency
        roles:
        - detect
        - audio
        - record
        - restream
    zones:
      zone_0:
        coordinates: 410,1097,1095,1104,900,786,615,778
  side_yard:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/side_yard?video
        input_args: preset-rtsp-restream-low-latency
        roles:
        - detect
        - audio
        - record
        - restream

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30
```

### Relevant log output

```shell
Frigate Notification DEBUG (in loop): Send Notification: False Info: sublabel: None, image: "/api/frigate/notifications/1721808659.304718-j1yodc/snapshot.jpg" Title: message: A Person was detected on the Front Door camera. iOS sound: enabled, Android Sound: enabled, iOS url: /api/frigate/notifications/1721808659.304718-j1yodc/front_door/clip.mp4 video: "/api/frigate/notifications/1721808659.304718-j1yodc/front_door/clip.mp4" critical: False, Triggers: New Snapshot: False - Disabled Presence Changed: False, Stationary Moved: False, Entered Zones Changed: False - Disabled, sublabel changed: False, Conditions: Loitering: 0 or Filters: Zones: Zone Filter Enabled: False, Multi Zone Enabled: False, Required Zones: [], Last Zones: [], Entered zones: 0 - [], TEST: PASS, Object Filter: Input: , TEST: PASS, Presence entity (not home): Entity: , TEST: PASS, Time Filter: Disabled times: [], TEST: PASS State Filter: state filter toggle on: False, state filter entity: , required states: [], TEST: PASS, Custom Filter: PASS, triggered by automation Front Door - Frigate Notifications (0.12.0.4a) mqtt topic frigate/events
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

### Any other information that may be helpful

here is the config for the notification blueprint

`alias: Front Door - Frigate Notifications (0.12.0.4a)
description: Front Door
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_device: 871a42775eeb44ae6c5cc5ec505578fe
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    ios_live_view: camera.front_door
    debug: true
    attachment: snapshot.jpg`
