### DISCUSSION TITLE
[Support]: green image in H.264 stream via go2rtc

### DISCUSSION THREAD

**Discussion by marcusb** [blakeblackshear/frigate#12622] [General Support]
### Describe the problem you are having

I have a H.264 stream that works correctly when I add it directly to the camera config, however if I add it via go2rtc config (which I want to do for restreaming functionality), then the image gets corrupted.

The corrupted image is mostly green with some flickering. Occasionally when reloading the page, it shows the camera image for a fraction of a second, then turns green. Sometimes the image starts working after some minutes, then reverts back to green if I click into the live view, for example.

The Frigate server is an Intel NUC Gen 5. I am using vaapi acceleration, which works for the other cameras, but also tried disabling it using `hwaccel_args: ' '`, which makes no difference - still the green screen.

The only added wrinkle is that the source H.264 stream is not taken directly from the camera, it is produced by a Raspberry Pi 4 which is transcoding a H.265 camera stream to H.264 using a standalone go2rtc. This is to avoid software H.265 decoding on my Frigate server. So maybe something in this stream isn't playing well with the go2rtc in Frigate. However, the same stream works just fine when it's configured directly on the camera config.

I have 3 other H.264 cameras configured, and they work just fine (without the Raspberry Pi involved).

![image](https://github.com/user-attachments/assets/f14401c5-6cc7-4325-858b-67a38c4993cd)

So the non-working stream setup is:
```
   Camera ----(RTSP H.265)-----> Raspberry Pi 4 / go2rtc transcoder ----(RTSP H.264)----> go2rtc / Frigate
```

The working setup is:
```
   Camera ----(RTSP H.265)-----> Raspberry Pi 4 / go2rtc transcoder ----(RTSP H.264)----> Frigate
```

### Steps to reproduce

Configure camera stream with go2rtc as per the attached config. Start Frigate. The overview screen shows a corrupted green image.

### Version

0.14.0-a4eb435

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt.example.org
  user: frigate
  password: xxxxx

detectors:
  coral:
    type: edgetpu

objects:
  track:
    - person
    - car
    - bicycle
    - cat
   
go2rtc:
  streams:
    cam1:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam1.example.org/ISAPI/Streaming/Channels/101
      - ffmpeg:cam1#audio=opus
    cam1_sub:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam1.example.org/ISAPI/Streaming/Channels/102
      - ffmpeg:cam1_sub#audio=opus
    cam2:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam2.example.org:554/cam/realmonitor?channel=1&subtype=0
    cam2_sub:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam2.example.org:554/cam/realmonitor?channel=1&subtype=1
    cam3:
      # *****************************************
      # This is the stream that ends up corrupted
      # *****************************************
      - rtsp://pi4.example.org:8554/cam3_main
    cam4:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam4.example.org:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:cam4#audio=opus
    cam4_sub:
      - rtsp://motion:{FRIGATE_RTSP_PASSWORD}@cam4.example.org:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:cam4#audio=opus

cameras:
  cam1:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam1_sub
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
  cam2:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam2
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam2_sub
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
  cam3:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      hwaccel_args: ' '
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
  cam4:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam4
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam4_sub
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

go2rtc-transcoded stream from "ASECAM 8MP H.265" turret camera

### Any other information that may be helpful

ffmpeg cmd line (this one with hwaccel):

```
ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-a4eb435 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam3 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/cam3@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
```
