### DISCUSSION TITLE
[Question]: Stationary car keeps alerting...

### DISCUSSION THREAD

**Discussion by Answer-1** [blakeblackshear/frigate#12635] [Ask A Question]
### What is your question:

Using 0.14, a car is parked in the driveway and that driveway (yellow zone) is setup as a zone to alerts on car and persons. The thing is, I constantly get alerts of that car when somebody walks in the street or another car passes by. 

![Screenshot 2024-07-26 102743](https://github.com/user-attachments/assets/c46affd8-2abc-461c-bbf4-ca6f30d8f67d)

So, I said hey, let's add an object mask there to prevent that detection

![Screenshot 2024-07-26 102539](https://github.com/user-attachments/assets/34f7b3c1-749a-4939-b2e2-b6d1c6ae9aeb)

but upon doing that, only small parts of the car are now being detected and I'm still getting false alerts...

![Screenshot 2024-07-26 102436](https://github.com/user-attachments/assets/06760bb6-37aa-45e9-af4d-affe53cad02b)
![Screenshot 2024-07-26 102415](https://github.com/user-attachments/assets/d11e8507-3089-4546-bc04-c0fca42a467d)

I can't really split the zone more than that to prevent false alerts.. Anything that could be done here? Wondering why only parts of the car are now getting detected after the object mask is added..

Thx!!

**Comment by NickM-27** [comment]
We need to see your config. the white box means the car is considered stationary so I don't think that car is being made part of the alert if things are setup correctly

**Comment by Answer-1** [comment]
Here's the config for that cam (Wyze v4):
(That config is me trying to split the initial object mask in two different zones)

```
  front:
    enabled: true
    mqtt:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      terrain:
        coordinates: 
          1,1,1,0.392,0.607,0.382,0.317,0.404,0.182,0.421,0.111,0.448,0.05,0.489,0,0.529,0,1
        objects:
          - person
          - car
        inertia: 3
      rue:
        coordinates: 
          0.276,0.265,0.422,0.226,0.708,0.173,1,0.184,1,0.331,0.643,0.324,0.346,0.35,0.132,0.398
        objects:
          - person
          - car
        inertia: 3
    motion:
      mask:
        - 1,0.931,1,1,0.711,1,0.711,0.931
        - 0,0.357,0.221,0.208,0.381,0.156,0.56,0.151,0.628,0.121,0.678,0.165,0.936,0.162,1,0.216,1,0.126,1,0,0,0
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0.597,0.143,0.545,0.065,0.443,0.074,0.401,0.201
            - 0,0.406,0.001,0.298,0.079,0.271,0.09,0.335
            - 0.429,0.416,0.206,0.437,0.179,0.573,0.404,0.501
            - 0.144,0.642,0.326,0.615,0.351,0.745,0.136,0.751
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    snapshots:
      retain:
        default: 10
      required_zones:
        - terrain
        - rue
      enabled: true
      bounding_box: true
    review:
      alerts:
        required_zones: terrain  # Yellow zone in smapshots
      detections:
        required_zones: rue  # Blue zone in snapshots
```

Yeah, the car is actually marked as stationary so I thought it should be good, but it gets detected again when something goes by in the street and creates a false alert.

Here's another exemple when a truck was backing up in the street:

![Screenshot 2024-07-26 105604](https://github.com/user-attachments/assets/2231ca71-b52d-492e-85e8-0948416d958f)

Only like parts of the stationary car are getting detected (after adding the object masks):

![Screenshot 2024-07-26 105451](https://github.com/user-attachments/assets/d1344e62-2997-4138-9885-48287c9badb5)
