### DISCUSSION TITLE
[Question]: How to config a camera to record crying audio event only?

### DISCUSSION THREAD

**Discussion by longhtran91** [blakeblackshear/frigate#12649] [Ask A Question] [answered]
### What is your question:

Hi,

I have a camera pointing at the baby bassinet. While I want all other cameras to take default audio events below.
```
audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
```

I want this specific baby camera to record only for crying events (no motion or other kind of objects detection). Here is what I have so far:
```
camera:
  baby_bedroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/baby_bedroom
        input_args: preset-rtsp-restream
        roles:
        - record
        - audio
        - detect
    motion:
      mask:
      - 1243,9,1244,37,918,40,921,7
    objects:
      track: []
    audio:
      listen:
      - crying
```
