### DISCUSSION TITLE
[Detector Support]:

### DISCUSSION THREAD

**Discussion by odehalaa** [blakeblackshear/frigate#12648] [Detector Support]
### Describe the problem you are having

I have subscription frigate+ and need to know can detect cat or dog must use fright+ or not ?

codeproject.ai I used but only detect car and person on fright version why ?

### Version

14 rc

### Frigate config file

```yaml
mqtt:
  enabled: false
 
cameras:
  Discovery_ID_HD:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.85:4751/Discover_ID_HD
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - cat
        - deer
        - face
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
 
  Animal_Planet_HD:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.85:4751/rtsp
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - cat
        - deer
        - face
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
 
#detectors:
 
  #cpu1:
  #  type: cpu
  #  num_threads: 10
 
#version: 0.14
 
    zones:
      TV:
        coordinates: 1,0.066,0.396,0.036,0.281,0,0.199,0.049,0.193,0.616,0.969,0.687
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: TV
detectors:
  deepstack:
    api_url: http://192.168.1.85:32168/v1/vision/detection
    type: deepstack
    api_timeout: 1 # seconds
 
camera_groups:
  IDX:
    order: 1
    icon: LuHome
    cameras:
      - birdseye
      - Discovery_ID_HD
      - Animal_Planet_HD
version: 0.14
 
environment_vars:
  PLUS_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### docker-compose file or Docker CLI command

```yaml
mqtt:
  enabled: false
 
cameras:
  Discovery_ID_HD:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.85:4751/Discover_ID_HD
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - cat
        - deer
        - face
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
 
  Animal_Planet_HD:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.85:4751/rtsp
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - cat
        - deer
        - face
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
 
#detectors:
 
  #cpu1:
  #  type: cpu
  #  num_threads: 10
 
#version: 0.14
 
    zones:
      TV:
        coordinates: 1,0.066,0.396,0.036,0.281,0,0.199,0.049,0.193,0.616,0.969,0.687
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: TV
detectors:
  deepstack:
    api_url: http://192.168.1.85:32168/v1/vision/detection
    type: deepstack
    api_timeout: 1 # seconds
 
camera_groups:
  IDX:
    order: 1
    icon: LuHome
    cameras:
      - birdseye
      - Discovery_ID_HD
      - Animal_Planet_HD
version: 0.14
 
environment_vars:
  PLUS_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxx
```

### Relevant log output

```shell
mqtt:
  enabled: false
 
cameras:
  Discovery_ID_HD:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.85:4751/Discover_ID_HD
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - cat
        - deer
        - face
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
 
  Animal_Planet_HD:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.85:4751/rtsp
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - cat
        - deer
        - face
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
 
#detectors:
 
  #cpu1:
  #  type: cpu
  #  num_threads: 10
 
#version: 0.14
 
    zones:
      TV:
        coordinates: 1,0.066,0.396,0.036,0.281,0,0.199,0.049,0.193,0.616,0.969,0.687
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: TV
detectors:
  deepstack:
    api_url: http://192.168.1.85:32168/v1/vision/detection
    type: deepstack
    api_timeout: 1 # seconds
 
camera_groups:
  IDX:
    order: 1
    icon: LuHome
    cameras:
      - birdseye
      - Discovery_ID_HD
      - Animal_Planet_HD
version: 0.14
 
environment_vars:
  PLUS_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Other
