### DISCUSSION TITLE
[Support]: Got Error when want play history

### DISCUSSION THREAD

**Discussion by antonbek89** [blakeblackshear/frigate#12652] [General Support]
### Describe the problem you are having

When I tried to play history I got
**Failed to play recordings (error 3): PIPELINE_ERROR_DECODE: Error Domain=NSOSStatusErrorDomain Code=-12909 "(null)" (-12909): VTDecompressionOutputCallback**

### Version

0.14.0-rc1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.187
  user: mqttuser
  password: '****'

birdseye:
  enabled: true
  width: 1920
  height: 1080
  quality: 15
  mode: objects #motion


detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

go2rtc:
  streams:
    Hall:
      - rtsp://admin:user@192.168.1.106:8554/Streaming/Channels/101
      - ffmpeg:Hall#audio=opus
    Hall_sub:
      - rtsp://admin:user@192.168.1.106:8554/Streaming/Channels/102

cameras:
#####################################################Hall######################################
  Hall:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Hall_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Hall?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.70

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 900
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 45
      events:
        pre_capture: 10
        post_capture: 15
        objects:
          - person
        retain:
          default: 45
#####################################################Hall######################################
```

### Relevant log output

```shell
Failed to play recordings (error 3): PIPELINE_ERROR_DECODE: Error Domain=NSOSStatusErrorDomain Code=-12909 "(null)" (-12909): VTDecompressionOutputCallback*
```

### FFprobe output from your camera

```shell
non
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Arenti c51 5.2.6.20211229

**Comment by hawkeye217** [comment]
What browser and OS are you using?

**Reply by antonbek89** [reply]
I’m try in Chrome last version

**Reply by hawkeye217** [reply]
What device/operating system? Are you on an Apple Silicon Mac?

**Reply by antonbek89** [reply]
Mac M3
But I try again via Home Assistant application and didn’t get error now only circle on the device - loading 
But actually I don’t see any recorder 

But when I go forward for example I can see image only via the timelines but not recorder history

**Reply by hawkeye217** [reply]
Can you try Safari?

**Reply by antonbek89** [reply]
I check it . 
When I go to timeline and go for example 1 hour ago
I can see the image , the circle in the middle of the screen loading but the recorder didn’t start 

I have in total 12 cameras 
Amcrest + Reolink working great !
The problem I describe it’s only with 6 cameras of Arenti

**Reply by hawkeye217** [reply]
> I have in total 12 cameras Amcrest + Reolink working great ! The problem I describe it’s only with 6 cameras of Arenti

If this is only happening with the Arenti cameras, you could try h264 reencoding with go2rtc.

For the affected cameras, try:

```
go2rtc:
  streams:
    Hall:
      - ffmpeg:rtsp://admin:user@192.168.1.106:8554/Streaming/Channels/101#video=h264
```
