### DISCUSSION TITLE
[Bug]: Javascript errors in Camera Live View

### DISCUSSION THREAD

**Discussion by illuzn** [blakeblackshear/frigate#12657] [Report a Bug]
### Describe the problem you are having

The home page overview which shows all cameras works fine. However, when I click on any individual camera, the video doesn't load and I receive the following javascript errors in MS Edge 127.0.2651.74 (Official build) (64-bit).

```plaintext
CameraControlPanel-9e3528c6.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'catch')
    at E.play (CameraControlPanel-9e3528c6.js:1:2800)
    at E.onmse (CameraControlPanel-9e3528c6.js:1:6221)
    at E.onopen (CameraControlPanel-9e3528c6.js:1:5130)
    at E.onopen (CameraControlPanel-9e3528c6.js:1:9527)
    at WebSocket.<anonymous> (CameraControlPanel-9e3528c6.js:1:4540)
play @ CameraControlPanel-9e3528c6.js:1
onmse @ CameraControlPanel-9e3528c6.js:1
onopen @ CameraControlPanel-9e3528c6.js:1
onopen @ CameraControlPanel-9e3528c6.js:1
(anonymous) @ CameraControlPanel-9e3528c6.js:1
CameraControlPanel-9e3528c6.js:1  Uncaught TypeError: this.ondata is not a function
    at WebSocket.<anonymous> (CameraControlPanel-9e3528c6.js:1:4955)
(anonymous) @ CameraControlPanel-9e3528c6.js:1

CameraControlPanel-9e3528c6.js:1  Uncaught TypeError: this.ondata is not a function
    at WebSocket.<anonymous> (CameraControlPanel-9e3528c6.js:1:4955)
(anonymous) @ CameraControlPanel-9e3528c6.js:1
```

### Steps to reproduce

Click on camera from frigate home page

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant.local
  user: REDACTED
  password: REDACTED

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 30
    post_capture: 60
    retain:
      default: 21
      mode: all

detect:
  annotation_offset: -500

snapshots:
  enabled: true
  quality: 100
  retain:
    default: 30

ui:
  live_mode: webrtc

go2rtc:
  streams:
    Garage:
    - REDACTED
    Garage_sub:
    - REDACTED
    Front_Door:
    - REDACTED
    Front_Door_sub:
    - REDACTED
    Front_Yard_Left:
    - REDACTED
    Front_Yard_Left_sub:
    - REDACTED
    Front_Yard_Right:
    - REDACTED
    Front_Yard_Right_sub:
    - REDACTED
    Courtyard:
    - REDACTED
    Courtyard_sub:
    - REDACTED
    Backyard_Left:
    - REDACTED
    Backyard_Left_sub:
    - REDACTED
    Side:
    - REDACTED
    Side_sub:
    - REDACTED
    Backyard_Right:
    - REDACTED
    Backyard_Right_sub:
    - REDACTED

  webrtc:
    candidates:
    - REDACTED
    - REDACTED
    - stun:8555

objects:
  track:
  - person
  - car
  - bicycle
  - motorcycle
  - bus
  filters:
    person:
      min_score: 0.8
      threshold: 0.93
    car:
      min_score: 0.8
      threshold: 0.9
    bicycle:
      min_score: 0.8
      threshold: 0.9
    motorcycle:
      min_score: 0.8
      threshold: 0.9
    bus:
      min_score: 0.8
      threshold: 0.9

cameras:
  Garage:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Garage
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Garage_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 286,320,411,320,409,299,289,299
    objects:
      filters:
        car:
          mask:
          - 61,320,331,320
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
  Front_Door:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Front_Door
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Front_Door_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 432,320,432,296,288,298,290,320
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
  Front_Yard_Left:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Front_Yard_Left
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Front_Yard_Left_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 432,320,432,298,292,297,292,320
      - 0,102,21,23,31,84,168,64,336,68,343,35,432,101,432,0,0,0
    objects:
      filters:
        car:
          mask:
          - 0,102,199,66,208,0,0,0
          - 0,320,432,320,432,178,384,129,0,180
        person:
          mask:
          - 143,183,189,185,187,148,144,150
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
  Front_Yard_Right:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Front_Yard_Right
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Front_Yard_Right_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 288,320,432,320,432,295,292,296
      - 60,33,104,17,107,53,202,49,334,63,336,20,417,320,432,320,432,320,432,0,57,0
    objects:
      filters:
        car:
          mask:
          - 110,66,252,71,254,0,101,0
          - 0,320,330,320,333,128,60,69
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
  Courtyard:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Courtyard
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Courtyard_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: false
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 291,320,432,320,432,296,289,298
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
    objects:
      filters:
        person:
          threshold: 0.8
        car:
          threshold: 0.8
        bicycle:
          threshold: 0.8
        motorcycle:
          threshold: 0.8
        bus:
          threshold: 0.8
  Backyard_Left:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Backyard_Left
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Backyard_Left_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: false
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 432,0,432,39,336,5,103,26,0,320,0,0
      - 432,299,432,320,293,320,293,301
      - 1520,23,1242,0,1920,0,1920,137
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
    objects:
      filters:
        person:
          threshold: 0.8
        car:
          threshold: 0.8
        bicycle:
          threshold: 0.8
        motorcycle:
          threshold: 0.8
        bus:
          threshold: 0.8
  Side:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Side
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Side_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: false
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 300,320,432,320,432,299,301,299
      - 276,94,376,320,432,320,432,0,225,0
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
    objects:
      filters:
        person:
          threshold: 0.8
        car:
          threshold: 0.8
        bicycle:
          threshold: 0.8
        motorcycle:
          threshold: 0.8
        bus:
          threshold: 0.8
  Backyard_Right:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/Backyard_Right
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/Backyard_Right_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: false
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
      - 432,320,432,299,290,299,291,320
      - 364,27,405,254,432,247,432,0,201,0
      - 71,22,134,0,0,0,0,50
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
    objects:
      filters:
        person:
          threshold: 0.8
        car:
          threshold: 0.8
        bicycle:
          threshold: 0.8
        motorcycle:
          threshold: 0.8
        bus:
          threshold: 0.8
```

### Relevant log output

```shell
None Applicable
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision
