### DISCUSSION TITLE
[Support]: Home Assistant Cameras Unavailable

### DISCUSSION THREAD

**Discussion by kceleslie** [blakeblackshear/frigate#12651] [General Support]
### Describe the problem you are having

I've got frigate and home assistant installed on separate servers. I've gone through the steps [here](https://docs.frigate.video/integrations/home-assistant/) to install and configure HA integration. Everything seems to work except for the cameras. They all (except for birdseye) show up unavailable. When i click on them i should get the RTSP stream but i dont, except for birdseye. 

![image](https://github.com/user-attachments/assets/d09a9bb1-a99c-4632-ab29-f86618340b32)

I'm able to use VLC to browse to the RTSP steam, rtsp://frigate:8554/ftdoor manually. I've configured the URL in HA for rtsp to be `rtsp://frigate:8554/{{ name|lower }}`. 

I'm not seeing anything in the HA or frigate logs to help debug this issue.  What am I missing? 

### Version

0.13.0

### Frigate config file

```yaml
mqtt:
  host: mqtt.xxxxx.us
birdseye:
  enabled: true
  mode: continuous
  restream: true
go2rtc:
  streams:
    ftdoor:
      - rtsp://xxxxxxxxxxx/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    garage:
      - rtsp://xxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    backyard:
      - rtsp://xxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif  
cameras:
  ftdoor:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://xxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      retain:
        days: 10
        mode: all 
    live:
      stream_name: ftdoor       
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://xxxxxxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
    zones:
      garageStreet:
        coordinates: 218,132,264,113,326,96,381,86,403,77,427,70,501,57,503,41,498,31,473,27,461,26,440,29,422,30,398,33,379,36,355,38,327,39,311,44,282,49,221,62,172,75,120,91,63,109,0,138,0,180,0,143,0,229
      garageNeighborsAcross:
        coordinates: 0,140,90,102,150,80,220,58,320,41,407,32,520,22,525,0,394,0,250,0,0,0
      garageNeighbors:
        coordinates: 562,121,575,41,537,38,437,75
    live:
      stream_name: garage
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://xxxxxxxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
    live:
      stream_name: backyard
objects:
  filters:
    person:
      mask:
        - 242,120,242,84,254,82,257,119
        - 1081,194,1096,148,1119,152,1100,203
        - 222,34,233,32,234,53,222,54
  track:
    - person
    - car
    - dog
    - bicycle
    - bus
    - horse
detectors:
  tensorrt:
    type: tensorrt
    model:
      path: /config/model_cache/tensorrt/yolov7-320.trt
record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 15
      mode: motion
ffmpeg:
  hwaccel_args: preset-jetson-h264
model:
  input_tensor: nchw                              # yolo models are nchw
  width: 320                                      # must match model size
  height: 320                                     # must match model size
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
Not sure how to do this
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

Amcrest
