### DISCUSSION TITLE
MobileNet SSD v2 Coco EdgeTPU vs ssdlite_mobiledet_coco_qat_postprocess model

### DISCUSSION THREAD

**Discussion by bence-b** [blakeblackshear/frigate#12669] [General]
Hi,

I'm using Frigate since v0.3.0. Me and my whole family loves it  :) It's rock solid, it sends relevant notifications through MQTT and HA 24/7 for 5 years. Thank you!

Version 0.3.0 uses the older model (MobileNet SSD v2 Coco), which processes 300x300 images. I haven't upgrade Frigate because it worked fine for my use-case: almost perfect detections, no false alarms, all in real-time.

But things have changed in the neighbourhood, and now it's time to upgrade to have access to more advanced zone, mask and stationery object features. 

The only problem is, that for some reason the night detections didn't work as good as they did in the past. I thought that it might be due to the new model, so I simply wanted to set it up like this in the config.yml

```
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/models/MobileNet SSD v2 Coco EdgeTPU.tflite"
      height: 300
      width: 300
```

But if I do it like this, I get an error:
` File "/opt/frigate/frigate/object_detection.py", line 195, in __init__ 
self.np_shm = np.ndarray(
TypeError: buffer is too small for requested array` 

Do you have any suggestions how to use that older model? I'm planning to buy Frigate+ anyway - do I understand it right that I'll get access to a model which was trained on IR images as well, which would mean that reverting to an older model is useless?

Does it help if I post compare images?

Thank you
