### DISCUSSION TITLE
[Support]: Is V14 RC1 missing the SEND_TO_FRIGATE+ Button?

### DISCUSSION THREAD

**Discussion by marc4s** [blakeblackshear/frigate#12672] [General Support] [answered]
### Describe the problem you are having

I have enabled the frigate+ api and missing the button. is it hidden somehow?

### Steps to reproduce

install v14rc1
enable api key via docker env

### Version

v14

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: true
  # Required: host name
  host: 1x
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: x
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: x
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  #stats_interval: 60
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    hauseingang_reo:
      - ffmpeg:https://xxx
cameras:
  # terasse deaktiviert. unnötig. hohe CPU Last
  #terasse:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/terasse
  #        input_args: preset-rtsp-restream
  #        roles:
  #          - detect
  #          - record
  #  detect:
  #    width: 1280
  #    height: 720
  #    fps: 7
  #  motion:
  #    mask:    
  #      - 424,0,458,720,0,720,0,0
  #  zones:
  #    zone_0:
  #      coordinates: 1172,0,446,0,424,720,1050,720
  garagetor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagetor
          roles:
            - detect
            - record
    motion:
      mask:
        - 563,0,0,0,0,128
    zones:
      UnterDemCarport:
        coordinates: 0.731,0.662,0.921,0.712,0.963,0.448,0.759,0.377
        inertia: 3
        objects: person
      AmHoftor:
        coordinates: 0.257,0.266,0.422,0.288,0.437,0.551,0.126,0.467
        objects: person
      VorDerGarage:
        coordinates: 0.007,0.987,0.128,0.473,0.974,0.732,0.991,0.989
        objects: person
      AmBaumhaus:
        coordinates: 0.581,0.604,0.618,0.227,0.737,0.265,0.727,0.648
        objects: person
  carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/x
          roles:
            - detect
            - record
  untermcarport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xx
          roles:
            - detect
            - record
#  haus:
#    ffmpeg:
#      inputs:
#        - path: rtsp://127.0.0.1:8554/xxx
#          roles:
#            - detect
#            - record
  hausflur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xxxx
          roles:
            - detect
            - record
  hauseingang:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.355,0,0.354,0.094,0.251,0.086,0.192,0
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xxx?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/xxx?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask: 0.145,0.143,0.184,0.009,0.946,0.016,0.953,0.148,0.131,0.174
    zones:
      AmHoftor:
        coordinates: 0.986,0.155,0.819,0.156,0.856,0.447,0.982,0.332
        objects: person
      VorDerGarage:
        coordinates: 0.008,0.259,0.007,0.654,0.871,0.552,0.812,0.154,0.143,0.178
        objects: person
      AufDemHof:
        coordinates: 
          0.254,0.63,0.387,0.993,0.998,0.999,0.998,0.539,0.996,0.528,0.997,0.325,0.861,0.449,0.878,0.552
        objects: person
detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  max_disappeared: 500


objects:
  track:
    - person
    - cat
    - dog

record:
  enabled: true
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 100
      #mode: motion
      mode: active_objects
      objects:
        dog: 14
        car: 30
        person: 365

# Include all cameras by default in Birdseye view
# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous



# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
#  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Europe/Berlin
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
#  use_experimental: false
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: full
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: '%Y/%m/%d %H:%M'

# Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
version: 0.14
```

### Relevant log output

```shell
nothing frigate+ related
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolink
