### DISCUSSION TITLE
[HW Accel Support]: Intel NUC8i7HVK AMD GPU

### DISCUSSION THREAD

**Discussion by cigas4** [blakeblackshear/frigate#12673] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hello, would appreciate some help getting AMD GPU hardware acceleration working on Frigate (docker container).

Actually I have managed to get hardware acceleration running, but for some reason it is using 'intel HD' graphics insted of AMD GPU.

 I am running Proxmox 8.2.4, inside I have LXC container running Debian 12. Inside Debian LXC I am running Frigate docker container.

Proxmox shall:
`root@proxmox:~# lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 22 XT [Radeon RX Vega M GH] (rev c0)`

Proxmox LXC config:
`arch: amd64
cores: 6
features: nesting=1
hostname: Frigate
memory: 14336
mp0: /mnt/pve/Synology_Frigate,mp=/mnt/pve/Synology_Frigate
nameserver: 192.168.1.13 8.8.8.8
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,hwaddr=22:AA:3E:DC:53:0C,ip=192.168.31.13/24,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-104-disk-0,size=100G
searchdomain: 192.168.1.1
swap: 2048
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: a
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
lxc.mount.entry: /dev/bus/usb/002 dev/bus/usb/002 none bind,optional,create=dir 0, 0
lxc.cap.drop:
lxc.mount.auto: cgroup:rw`

Inside Debin LXC container:
`root@Frigate:~# vainfo
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD`

Inside Debin LXC container:
`root@Frigate:~# ls -al /dev/dri/renderD128
crw-rw---- 1 root input 226, 128 Jul 28 20:37 /dev/dri/renderD128`

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  client_id: Frigate
  user: Frigate
  password: pass
  stats_interval: 60

birdseye:
  enabled: false
  quality: 10
  mode: continuous

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    parking: 
      - rtsp://user:pass@192.168.1.114:554/Streaming/Channels/101
      - "ffmpeg:rtsp://user:pass@192.168.1.114:554/Streaming/Channels/101#video=copy#audio=aac"
  webrtc:
    candidates:
      - 192.168.1.13:8555
      - stun:8555

cameras:
  parking:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/parking?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 2688
      height: 1520
      fps: 8
      max_disappeared: 35
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          mask:
            - 283,862,542,146,950,182,1744,399,2081,545,2217,992,2248,1280,1955,1321,1966,1459,1623,1520,2688,1520,2688,0,0,0,0,701,0,1520,672,1520,170,1441
          min_area: 41000
          min_score: 0.5
          threshold: 0.8
        car:
          mask:
            - 283,862,542,146,950,182,1744,399,2081,545,2217,992,2248,1280,1955,1321,1966,1459,1623,1520,2688,1520,2688,0,0,0,0,701,0,1520,672,1520,170,1441
          max_area: 1000000
          min_score: 0.5
          threshold: 0.75
        dog:
          mask:
            - 283,862,542,146,950,182,1744,399,2081,545,2217,992,2248,1280,1955,1321,1966,1459,1623,1520,2688,1520,2688,0,0,0,0,701,0,1520,672,1520,170,1441
          max_area: 40000
          min_score: 0.5
          threshold: 0.75
    snapshots:
      enabled: True
      crop: True
      quality: 100
      height: 500
      timestamp: False
      bounding_box: True
      retain:
        default: 100
    record:
      enabled: True
      retain:
        days: 13
        mode: all
      events:
        pre_capture: 10
        post_capture: 15
        retain:
          default: 69
    rtmp:
      enabled: False
    live:
      stream_name: parking
    motion:
      threshold: 60
      mask:
        - 283,862,542,146,950,182,1744,399,2081,545,2217,992,2248,1280,1955,1321,1966,1459,1623,1520,2688,1520,2688,0,0,0,0,701,0,1520,672,1520,170,1441
    zones:
      gate:
        coordinates: 1733,1327,1873,1320,1885,1486,1605,1520
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    shm_size: '1024mb'
    image: ghcr.io/blakeblackshear/frigate:0.13.2
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/frigate.yml:/config/config.yml
      - /mnt/HDD_8TB/Frigate/media:/media/frigate
      - /mnt/HDD_8TB/Frigate/config:/config
      - /mnt/HDD_8TB/Frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935'
      - '8555:8555/tcp'
      - '8555:8555/udp'
    environment:
      FRIGATE_RTSP_PASSWORD: 'pass'
      LIBVA_DRIVER_NAME: radeonsi
```

### Relevant log output

```shell
Vainfo Output
Return Code: 0

Process Output:

vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2688x1520
FPS: 25/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

I have another exactly same hardware machine (Intel NUC8i7HVK) running in different premises. It is setup in exactly same way - running Proxmox and has Debian 12 LXC running Frigate docker container.
On this machine somehow I have managed to make it working, but do not know how I did it and can't repeat same steps for this machine.

On the other NUC:

Proxmox shall:
`root@proxmoxve:~# lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 22 XL [Radeon RX Vega M GL] (rev c0)`

Inside Debin LXC container:
`root@Debian:~# vainfo
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 22.3.6 for AMD Radeon RX Vega M GL Graphics (vegam, LLVM 15.0.6, DRM 3.57, 6.8.8-4-pve)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc`

Inside Frigate UI under System HW ACCEL:
`Vainfo Output
Return Code: 0
Process Output:
vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Mesa Gallium driver 22.3.6 for AMD Radeon RX Vega M GL Graphics (vegam, LLVM 15.0.6, DRM 3.57, 6.8.8-4-pve)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc`
