### DISCUSSION TITLE
[Support]: Birdeye not available in HA Integration

### DISCUSSION THREAD

**Discussion by chrasim** [blakeblackshear/frigate#12670] [General Support]
### Describe the problem you are having

Since 0.13 I have the problem that Birdseye in the integration is always not available. 

It seems to come up and transfer an image (I see the latest image in the overview) but immediately goes back to "not available" and cannot be used in the Frigate card or viewed as a live stream. 

It worked fine in 0.12, now I'm on 0.14-rc1. Go2Rtc restream is enabled and the Birdseye stream works fine in the Go2rtc dashboard (ha-ip port 1984). Frigate is installed as HASS OS add-in. 

Does anyone have an idea how to fix this?

![453331273_10233169475002758_8746781418379675197_n](https://github.com/user-attachments/assets/bd59c17c-e7b0-4c8d-adc9-c06c700d7f2d)

### Version

0.14-rc1

### Frigate config file

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: i965

database:
  path: /config/frigate.db

mqtt:
  host: 192.168.12.250
  user: mqtt
  password: xxx

motion:
  improve_contrast: true

detectors:
  coral:
    type: edgetpu
    device: pci

birdseye:
  restream: true
  enabled: true
  width: 1280
  height: 720
  quality: 1

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  rtsp:
    username: admin
    password: xxx
  streams:
    garten_sub:
      - rtsp://xxx:xxx@192.168.12.230:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      # - "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    garten:
      - rtsp://xxx:xxx@192.168.12.230:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      # - "ffmpeg:rtsp_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    hinten_sub:
      - rtsp://admin:xxx@192.168.12.234:554/H264/ch1/sub/av_stream
    hinten:
      - rtsp://admin:xxx@192.168.12.234:554/H264/ch1/main/av_stream
    kinderzimmer_sub:
      - rtsp://admin:xxx@192.168.12.232:554/H264/ch1/sub/av_stream
    kinderzimmer:
      - rtsp://admin:xxx@192.168.12.232:554/H264/ch1/sub/av_stream
    vorne_sub:
      - rtsp://admin:xxx@192.168.12.233:554/H264/ch1/sub/av_stream
    vorne:
      - rtsp://admin:xxx@192.168.12.233:554/H264/ch1/main/av_stream

cameras:
  Garten:  # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    live:
      stream_name: garten
  Hinten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hinten_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/hinten # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
#      output_args:
#        detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
#        rtmp: '-aspect 854:480 -c copy -f flv'
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    live:
      stream_name: hinten
  Kinderzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kinderzimmer_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/kinderzimmer # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
     # output_args:
     #   detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    detect:
      width: 854 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    live:
      stream_name: kinderzimmer
  Vorne:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorne_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/vorne # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
     # output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    detect:
      width: 854 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    live:
      stream_name: vorne

record:
  enabled: true
  retain:
    days: 0
  events:
    retain:
      default: 5

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 5

version: 0.14
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Several Dahua/Annke
