### DISCUSSION TITLE
[HW Accel Support]: Jetson Orin not working

### DISCUSSION THREAD

**Discussion by jwill2385** [blakeblackshear/frigate#12686] [Hardware Acceleration Support]
### Describe the problem you are having

Hello I have a jetson orin device running Ubuntu 22.04 and jetpack 6.0.
Every time I try to run frigate with hardware acceleration it fails and runs into an error. I've tried a variety of different presets including the nvidia and the jetson preset. along with directly setting the hardware arg to be h264_cuvid.

Has anyone figured out how to get frigate to work using GPU on a jetson orin device? I am attaching my log file below

### Version

frigatestable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  camera1: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      # hwaccel_args:
      #   -preset-nvidia-h264
        # - -c:v
        # - h264_cuvid
      inputs:
        - path: rtsp://admin:admin@192.168.0.1/live #TODO update to camera path
          roles:
            - detect
            - record
      # output_args:
      #   record: -f segment -segment_time 10 -segment_format mp4 -crf 28 -reset_timestamps 1 -strftime 1
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        # mode: all
      
  ip_cam: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://admin:admin@10.0.0.238/live #TODO update to camera path
          roles:
            - detect
            - record
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        mode: all
```

### docker-compose file or Docker CLI command

```yaml
version: "2.4"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable #Jetson nano image jetpack 4.6
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/visionsense/Docker/frigate/config:/config
      - /home/visionsense/Docker/frigate/media:/media/frigate #TODO switch this to external HD for media storage
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
ate  | 2024-07-30 19:58:32.069028350  19:58:32.068 INF go2rtc version 1.8.4 linux/arm64
frigate  | 2024-07-30 19:58:32.069923030  19:58:32.069 INF [api] listen addr=:1984
frigate  | 2024-07-30 19:58:32.070093626  19:58:32.069 INF [rtsp] listen addr=:8554
frigate  | 2024-07-30 19:58:32.070425091  19:58:32.070 INF [webrtc] listen addr=:8555
frigate  | 2024-07-30 19:58:33.830865575  [2024-07-30 19:58:33] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-07-30 19:58:33.901051831  [2024-07-30 19:58:33] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-07-30 19:58:33.909759748  [2024-07-30 19:58:33] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-07-30 19:58:33.920862769  [2024-07-30 19:58:33] frigate.app                    INFO    : Recording process started: 380
frigate  | 2024-07-30 19:58:33.926068958  [2024-07-30 19:58:33] frigate.app                    INFO    : go2rtc process pid: 100
frigate  | 2024-07-30 19:58:33.964673142  [2024-07-30 19:58:33] detector.cpu                   INFO    : Starting detection process: 389
frigate  | 2024-07-30 19:58:33.971310602  [2024-07-30 19:58:33] frigate.app                    INFO    : Output process started: 391
frigate  | 2024-07-30 19:58:33.971326827  [2024-07-30 19:58:33] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-07-30 19:58:33.994714917  [2024-07-30 19:58:33] frigate.app                    INFO    : Camera processor started for camera1: 396
frigate  | 2024-07-30 19:58:34.003268237  [2024-07-30 19:58:33] frigate.app                    INFO    : Camera processor not started for disabled camera ip_cam
frigate  | 2024-07-30 19:58:34.005944086  [2024-07-30 19:58:34] frigate.app                    INFO    : Capture process started for camera1: 398
frigate  | 2024-07-30 19:58:34.005953750  [2024-07-30 19:58:34] frigate.app                    INFO    : Capture process not started for disabled camera ip_cam
frigate  | 2024-07-30 19:58:34.197634344  [2024-07-30 19:58:34] frigate.video                  ERROR   : camera1: Unable to read frames from ffmpeg process.
frigate  | 2024-07-30 19:58:34.197643560  [2024-07-30 19:58:34] frigate.video                  ERROR   : camera1: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-07-30 19:58:41.257466076  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-07-30 19:58:54.076699014  [2024-07-30 19:58:54] watchdog.camera1               ERROR   : Ffmpeg process crashed unexpectedly for camera1.
frigate  | 2024-07-30 19:58:54.077121137  [2024-07-30 19:58:54] watchdog.camera1               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-07-30 19:58:54.077396793  [2024-07-30 19:58:54] ffmpeg.camera1.detect          ERROR   : Unrecognized option 'preset-nvidia-h264'.
frigate  | 2024-07-30 19:58:54.077652512  [2024-07-30 19:58:54] ffmpeg.camera1.detect          ERROR   : Error splitting the argument list: Option not found
frigate  | 2024-07-30 19:58:54.254631672  [2024-07-30 19:58:54] frigate.video                  ERROR   : camera1: Unable to read frames from ffmpeg process.
frigate  | 2024-07-30 19:58:54.255196167  [2024-07-30 19:58:54] frigate.video                  ERROR   : camera1: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
Unsure how to run this
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

wyze camv3

### Any other information that may be helpful

Jetson orin has aarch64 architecture and is running jetpack 6.0 with ubuntu 22.04
