### DISCUSSION TITLE
[Support]: live preview has artifacts

### DISCUSSION THREAD

**Discussion by krishne35** [blakeblackshear/frigate#12700] [General Support] [answered]
### Describe the problem you are having

The rtsp stream of camera is fine but when I try to live preview the camera it shows weired atrifacts on it
Frigate Live view
![IMG_20240801_130113](https://github.com/user-attachments/assets/09ff0425-7421-429a-a070-74752cb4a4f1)

Rtsp stream from vlc
![Screenshot_2024-08-01-12-52-08-86_4aed3257f278fcf7bfa3abd644e23333](https://github.com/user-attachments/assets/bb186fb5-2ddf-4f6d-93f9-c66bea8a2a3a) 

### Steps to reproduce

Go to live view of the camera

### Version

RC-1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx
  port: 1883
  user: xxx
  password: xxx
detectors:
  ov:
    type: openvino
    device: GPU
#model:
#  model_type: yolonas
#  width: 320 # <--- should match whatever was set in notebook
#  height: 320 # <--- should match whatever was set in notebook
#  input_tensor: nchw
#  input_pixel_format: bgr
#  path: /config/yolo_nas_s.onnx
#  labelmap_path: /labelmap/coco-80.txt
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
#model:
#  width: 416
#  height: 416
#  input_tensor: nchw
#  input_pixel_format: bgr
#  model_type: yolox
#  path: /model/yolox/yolox-tiny.xml
#  labelmap_path: /model/yolox/coco_80cl.txt
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 8
  mode: continuous
objects:
  track:
    - person
    - car
    - motorcycle
    - dog
    - cat
    - knife
snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    retain:
      default: 10
      mode: active_objects
cameras:
  TP_cam: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://xxx:xxx@10.0.2.1:554/stream2
          roles:
            - detect
        - path: rtsp://xxx:xxx@10.0.2.1:554/stream1
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 640,384,640,420,505,420,505,393
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 420 # <---- update for your camera's resolution
      fps: 5
    zones:
      car_zone:
        coordinates:
          0.189,1,0.8,1,1,1,1,0.683,0.942,0.55,0.85,0.529,0.832,0.265,0.577,0.212,0.497,0.243,0.226,0.556,0.417,0.634
        objects:
          - car
          - motorcycle
        inertia: 3
  Kitchen_Cam_IMOU: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://xxx:xxx@10.0.2.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
        - path:
            rtsp://xxx:xxx@10.0.2.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 420 # <---- update for your camera's resolution
      fps: 5
    onvif:
      host: 10.0.2.2
      port: 80
      user: admin
      password: Applez35
    motion:
      mask:
        - 477,40,619,44,618,21,479,21
version: 0.14
camera_groups:
  Birds_eye:
    order: 1
    icon: LuAperture
    cameras:
      - birdseye
      - Kitchen_Cam_IMOU
      - TP_cam
```

### Relevant log output

```shell
log.txt
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tp link vigi
