### DISCUSSION TITLE
[Support]: Label icons not working when labelmap is used.

### DISCUSSION THREAD

**Discussion by mx-vatte** [blakeblackshear/frigate#12702] [General Support] [answered]
### Describe the problem you are having

I use labelmap in the configuration to translate labels into German. It seems that this causes a problem with showing the correct label icons.

![image](https://github.com/user-attachments/assets/85f9d38a-cbcc-4903-b01f-395739a80494)

### Steps to reproduce

Use e.g. the following labelmap config.
`model:
  labelmap:
    0: Person
    1: Fahrrad
    2: Auto
    3: Motorrad
    7: Auto
    15: Vogel
    16: Katze
    17: Hund`

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
mqtt:
  host: 123.456.789.001
  user: xxx
  password: yyy
  port: 1883

detectors:
#  cpu1:
#    type: cpu
#    num_threads: 2
  coral:
    type: edgetpu
    device: usb

model:
  labelmap:
    0: Person
    1: Fahrrad
    2: Auto
    3: Motorrad
    7: Auto
    15: Vogel
    16: Katze
    17: Hund

go2rtc:
  streams:
    eingang_vorne:
      - rtsp://xxx:yyy@192.168.178.39:554/Streaming/channels/101
    eingang_vorne_sub:
      - rtsp://xxx:yyy@192.168.178.39:554/Streaming/channels/102

    schuppen:
      - rtsp://xxx:yyy@192.168.178.191:554/Streaming/channels/101
    schuppen_sub:
      - rtsp://xxx:yyy@192.168.178.191:554/Streaming/channels/102

    klingel:
      - ffmpeg:http://192.168.178.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=yyy#video=copy#audio=copy#audio=opus
      - rtsp://192.168.178.21/Preview_01_sub
      - onvif://xxx:yyy@192.168.178.21:8000?subtype=000&snapshot
    klingel_sub:
      - ffmpeg:http://192.168.178.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=yyy

birdseye:
  enabled: true
  mode: continuous

cameras:
#   test:
#     ffmpeg:
#       inputs:
#         - path: /media/frigate/05.43.mp4
#           roles:
#             - detect
#       input_args: -tag:v hvc1
#     detect:
#       fps: 5
#       width: 1080
#       height: 720
#     zones: 
#       Vorgarten:
#         coordinates: 0,720,0,0,83,0,159,0,167,140,602,109,1080,321,1080,720

# #    motion:
# #      mask:
#         #Vogelscheuche- 479,0,580,0,591,199,477,194
# #        - 371,110,175,210,217,425,302,406,415,410,540,473,759,280,834,203,767,164,552,295,476,256
# #        - 875,546,1050,650,1012,720,967,720,693,575,919,237,975,267
# #        - 244,0,240,24,0,25,0,0

#     objects:
#       track:
#         - Person
#         - Auto
#         - Katze
#         - Hund
#         - Fahrrad
#         - Motorrad
#       filters:
#       #bicycle:
#       #  mask:
#       #car:
#       #  mask:
#       #    - 0,2160,0,115,2705,465,3840,610,3840,2160,1955,2160
#       #cat:
#       #  mask:
#       #dog:
#       #  mask:
#         Auto:
#           mask:
#             - 1017,720,0,720,0,344,219,223
#         Motorrad:
#           mask:
#             - 1017,720,0,720,0,344,219,223
#         Person:
#           #mask:
#             #Vogelscheuche- 479,0,580,0,591,199,477,194
#            # - 371,110,175,210,217,425,302,406,415,410,540,473,759,280,834,203,767,164,552,295,476,256
#             #- 875,546,1050,650,1012,720,967,720,693,575,919,237,975,267
#             #- 111,572,221,507,422,641,345,720,192,720 # Halloween Kürbis + Hut
#           min_score: 0.7
#           threshold: 0.725  
  eingang_vorne: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.131:8554/eingang_vorne # <----- Update for your camera
          roles:
            - record

        - path: rtsp://192.168.178.131:8554/eingang_vorne_sub # <----- Update for your camera
          roles:
            - detect

      input_args: -tag:v hvc1
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      fps: 10
      width: 640
      height: 480

    zones:
      vorgarten:
        coordinates: 
          - 0,1,0,0,0.064,0,0.148,0,0.159,0.265,0.47,0.152,1,0.527,1,1


        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0.245,0.235,0.161,0.283,0.195,0.556,0.256,0.498,0.294,0.465,0.481,0.644,0.552,0.556,0.553,0.515,0.745,0.294,0.742,0.256,0.711,0.235,0.558,0.385,0.531,0.41,0.448,0.402
        - 0.783,0.769,0.983,0.89,0.933,1,0.855,0.971,0.753,0.894,0.689,0.856,0.662,0.794,0.655,0.715,0.714,0.637,0.75,0.625,0.841,0.392,0.863,0.335,0.887,0.373
        - 0,0,0,0.033,0.331,0.033,0.331,0
    objects:
      track:
        - Person
        - Auto
        - Katze
        - Hund
        - Fahrrad
        - Motorrad
      filters:
        Katze:
          mask:
          min_score: 0.7
          threshold: 0.725
        Hund:
          mask:
          min_score: 0.7
          threshold: 0.725
        Auto:
          mask: 
            - 0.972,0.925,0.939,1,0,1,0,0.477,0.237,0.292
        Motorrad:
          mask: 
            - 0.972,0.925,0.939,1,0,1,0,0.477,0.237,0.292
        Person:
          mask:

          min_score: 0.7
          threshold: 0.725
          min_area: 800


    review:
      alerts:
        required_zones: vorgarten
  schuppen: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.131:8554/schuppen # <----- Update for your camera
          roles:
            - record

        - path: rtsp://192.168.178.131:8554/schuppen_sub # <----- Update for your camera
          roles:
            - detect

      input_args: -tag:v hvc1

      output_args:
        record: preset-record-generic-audio-copy
    detect:
      #fps: 5
      #width: 1280
      #height: 720
      fps: 10
      width: 640
      height: 480
      stationary:
        threshold: 500

    zones:
      einfahrt:
        coordinates: 
          - 0.73,0.335,0.983,0.419,0.947,0.373,0.742,0.304
        inertia: 3
        loitering_time: 0
    motion:
      mask: 
        - 0,0,0,0.033,0.331,0.033,0.331,0
    objects:
      track:
        - Person
        - Auto
#        - Katze
#        - Hund
        - Fahrrad
        - Motorrad
    review:
      alerts:
        required_zones: einfahrt
  klingel: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.131:8554/klingel # <----- Update for your camera
          roles:
            - record

        - path: rtsp://192.168.178.131:8554/klingel_sub # <----- Update for your camera
          roles:
            - detect

      input_args: -tag:v hvc1

      output_args:
        record: preset-record-generic-audio-copy
    detect:
      fps: 10
      width: 640
      height: 480
      stationary:
        threshold: 500

    zones:
      einfahrt_vorne:
        coordinates: 
          - 0,1,1,1,1,0.615,0.713,0.592,0.53,0.596,0.327,0.596,0.3,0.775,0.192,0.79,0,0.648
        inertia: 3
        loitering_time: 0
    motion:
      mask: 
        - 0,0,0,0.448,0.78,0.458,0.778,0.527,1,0.558,1,0.442,1,0
    objects:
      track:
        - Person
        - Auto
        - Katze
        - Hund
        - Fahrrad
        - Motorrad
      filters:
        Auto:
          mask: 
            - 1,0.352,1,0.779,0.733,0.781,0.73,0.379
    review:
      alerts:
        required_zones: einfahrt_vorne
record:
  enabled: true
  retain:
    days: 15
    mode: all
    #mode: motion
  events:
    pre_capture: 15
    post_capture: 30
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  clean_copy: false
  crop: false
  height: 1080
version: 0.14
```

### Relevant log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Annke VC800 + Reolink Doorbell POE

### Any other information that may be helpful

Maybe that's why I don't get alerts?
