### DISCUSSION TITLE
[Support]: with the last RC1 version the cam using webrtc is not visible in live view

### DISCUSSION THREAD

**Discussion by alexchini** [blakeblackshear/frigate#12703] [General Support] [answered]
### Describe the problem you are having

With the last release RC1 the live view of the cam using webrtc (192.1638.0.111) is not visible instead was working fine with beta4.
Weird thing in homeassistant the live view is working fine using frigate app.

### Steps to reproduce

Just using the live view of the cam

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt



# default threshold value
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 50

  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30

  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8

# Include all cameras by default in Birdseye view
# birdseye:
#   enabled: true
#   width: 1280
#   # Optional: Height of the output resolution (default: shown below)
#   height: 720
#   # Optional: Encoding quality of the mpeg1 feed (default: shown below)
#   # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#   quality: 12
#   # Optional: Mode of the view. Available options are: objects, motion, and continuous
#   #   objects - cameras are included if they have had a tracked object within the last 30 seconds
#   #   motion - cameras are included if motion was detected in the last 30 seconds
#   #   continuous - all cameras are included always
#   mode: motion
#   # Optional: Threshold for camera activity to stop showing camera (default: shown below)
#   inactivity_threshold: 30
#   # Optional: Configure the birdseye layout
#   layout:
#     # Optional: Scaling factor for the layout calculator (default: shown below)
#     scaling_factor: 2.0
#     # Optional: Maximum number of cameras to show at one time, showing the most recent (default: show all cameras)
#     max_cameras: 4

go2rtc:
  streams:
    ipcam1:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.111:554/11
    ipcam2:
      - rtsp://admin:@192.168.0.112:554/videoMain
    ipcam3:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.113:554/videoMain
    ipcam4:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/videoMain
    ipcam5:
      - rtsp://admin:@192.168.0.115:554/videoMain
    ipcam6:
      - rtsp://admin:@192.168.0.116:554/videoMain
  webrtc:
    candidates:
      #- 192.168.0.110:8555
      - stun:8555

ffmpeg:
  hwaccel_args: preset-vaapi

mqtt:
  host: 192.168.0.188
  topic_prefix: frigate
  client_id: frigate
  user: alemqtt
  password: 

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true

timestamp_style:
  position: bl
  effect: shadow
  thickness: 2
  format: '%d/%m/%Y %H:%M:%S'

cameras:
  ipcam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.111:554/12 # 1280*720
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.111:554/11 #4k
          roles:
            - record

    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
        - person
        - car
        - cat
      # filters:
      #   person:
      #     # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #     min_area: 0
      #     # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #     max_area: 24000000
      #    ## # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #    ## min_ratio: 0.5
      #    ## # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #    ## max_ratio: 2.0
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.5
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.7
      #     # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      #     # Checks based on the bottom center of the bounding box of the object
      #     # mask: 0,0,1000,0,1000,200,0,200
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
    onvif:
      host: 192.168.0.111
      port: 8080
      user: admin
      password: {FRIGATE_RTSP_PASSWORD}
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: false
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
    #motion:
     # mask:
     #   - 859,454,914,467,896,239,828,230
  ipcam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.112:554/videoMain
          roles:
            - record
        - path: rtsp://admin:@192.168.0.112:554/videoMain
          roles:
            - detect

    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects

  ipcam3:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.113:554/videoMain
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.113:554/videoMain
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
  ipcam4:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/videoMain
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.114:554/videoMain
          roles:
            - detect

    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
    #motion:
    #  mask:
    #    - 455,0,720,0,720,148

  ipcam5:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.115:554/videoMain
          roles:
            - detect
        - path: rtsp://admin:@192.168.0.115:554/videoMain
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
    motion:
      mask:
        - 150,2,41,360,0,360,0,0

  ipcam6:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.116:554/videoMain
          roles:
            - detect
        - path: rtsp://admin:@192.168.0.116:554/videoMain
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 14
          mode: active_objects
version: 0.14
camera_groups: {}
```

### Relevant log output

```shell
no errors in logs
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

ctronics

### Any other information that may be helpful

it was working fine the the previous versions
