### DISCUSSION TITLE
[Hwaccel Support]: can't show GPU info at SR-IOV env

### DISCUSSION THREAD

**Discussion by lyj0309** [blakeblackshear/frigate#12718] [Hardware Acceleration Support]
### Describe the problem you are having

can't show gpu info, the error return
```
intel_gpu_top    
Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)
Segmentation fault (core dumped)
```

### Steps to reproduce

```
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-rc1
    shm_size: 256mb # update for your cameras based on calculation above
    cap_add:
      - CAP_PERFMON
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 
  ```

### Version

0.14.0-rc1

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

```
```


### Relevant log output

```shell
intel_gpu_top    
Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)
Segmentation fault (core dumped)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

tp-link

### Any other information that may be helpful

However, i see source code use intel_gpu_top    to get GPU status , but it's not working when sr-iov enable, see https://github.com/strongtz/i915-sriov-dkms/issues/95 
for me, it works when using ` intel_gpu_top -d drm:/dev/dri/renderD128` or ` intel_gpu_top -d sriov`
