### DISCUSSION TITLE
[Support]:  Audio in Live View on iOS Chome Doesn't Work  - Recordings Work Fine - Chrome Browser

### DISCUSSION THREAD

**Discussion by moogoos** [blakeblackshear/frigate#12716] [Camera Support] [answered]
### Describe the problem you are having

Ive been able to enable audio for recording playback and live view. In chrome on OS X it works fine. Toggle the mute button audio comes on or off.

On iOS for recordings enabling or disabling audio also works fine on iOS Chrome, iPhone 15 Pro in this case. For live view howeever, even with the button being toggled, audio does not come through for live view. Works fine for recording play back, meaning it can be toggled on and off and audio comes on and off

### Steps to reproduce

Connect to a live stream on, presumably, an iOS device that has a camera live feed that has audio capabilty. Toggle the mute icon, the icon will turn blue stating it's on, but no audio comes on. Recordings are fine. This was on an iPhone 15 Pro

### Version

.14 RC1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: emqx
  port: 1883

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  coral:
    type: edgetpu
    device: pci:0

snapshots:
  enabled: true
  retain:
    default: 90

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 90
      mode: all

go2rtc:
  rtsp:
  streams:
    street_main:
      - rtsp://xxx:yyy@ip/Streaming/channels/101
      - ffmpeg:street_main#audio=opus
    street_sub:
      - rtsp://xxx:yyy@ip/Streaming/channels/102
      - ffmpeg:street_sub#audio=opus
   

cameras:

  street:
    live:
      stream_name: street_main
    ui:
      order: 2
    birdseye:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/street_main?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/street_sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
        - mouse
      mask:
        0.021,0.718,0.169,0.857,0.268,0.898,0.566,0.959,0.805,0.887,0.838,0.988,0.005,0.986
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 10
```

### Relevant log output

```shell
NA
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Hikvision 8MP PoE - DS-2CD2387G2H-LIU
