### DISCUSSION TITLE
[Bug]: Full screen exports display is not correct on chrome

### DISCUSSION THREAD

**Discussion by gypais** [blakeblackshear/frigate#12717] [Report a Bug] [answered]
### Describe the problem you are having

the exports visualization is not correct, as soon as I click on the arrow to read, it goes to full screen. The display is not sized to the browser, nor to the screen. I have to reduce the zoom to 50% of the browser to see the commands once I have gone to full screen.
There is no problem with safari
I am on mac and with an up-to-date OS

### Steps to reproduce

the problem is every time

### Version

System 0.14.0-7c39b17

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.44
  #host: 172.29.8.2
  port: 1883
  user: jpp
  password: freehp
  topic_prefix: frigate
  client_id: frigate

#logger:
#  default: debug
 # logs:
  #  frigate.ptz.onvif: debug

go2rtc:
  streams:
    JPP_camera-in:
      - rtsp://192.168.0.204:554/rtsp
    JPP_camera-out:
      - rtsp://rphn:yh4mty@192.168.0.243/channel=1_stream=1.sdp

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

cameras:
  JPP_camera-in:
    detect:
      fps: 5
      enabled: false
    enabled: true
    onvif:
      host: 192.168.0.204
      port: 80
      user: admin
      password: admin1
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.204:554/rtsp
        #rtsp://192.168.0.204:554/h264_stream
          roles:
            - detect
    zones: {}
    motion:
      mask:
        - 0.006,0.015,0.258,0.009,0.258,0.066,0.006,0.066
        - 0.686,0.188,0.682,0.404,0.95,0.452,0.958,0.195
  JPP_camera-out:
    detect:
    # width: 1280
    # height: 720
      fps: 5
      enabled: true
    enabled: true
    onvif:
      host: 192.168.0.243
      port: 8899
      user: admin
      password: admin
    ffmpeg:
      inputs:
        #- path: rtsp://admin:admin@192.168.0.243/channel=1_stream=1.sdp
        - path: rtsp://rphn:yh4mty@192.168.0.243/channel=1_stream=1.sdp
        #- path: rtsp://admin:admin@192.168.0.243/stream=1.sdp
          roles:
            - detect
    motion:
      mask:
        - 0.62,0.023,0.985,0.025,0.985,0.057,0.621,0.058
        - 0.899,0.187,0.858,0.184,0.87,0.225,0.802,0.261,0.927,0.33,0.995,0.278,0.983,0.192
        - 0.351,0.09,0.358,0.148,0.659,0.158,0.589,0.073
objects:
  track:
    - person
    - bird
    - cat
    - dog
  filters:
    bird:
      min_score: 0.7
    person:
      min_score: 0.75
record:
  enabled: true
  retain:
    days: 10
    mode: motion
  events:
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 20

version: 0.14
```

### Relevant log output

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

pg x6 weq 2 + cloudcam
