### DISCUSSION TITLE
[Support Frigate+]: License plate not comming through

### DISCUSSION THREAD

**Discussion by heisenberg2980** [blakeblackshear/frigate#12719] [General Support] [answered]
### Describe the problem you are having

I am a Frigate+ user, and after enabling the licence_plate object into my Frigate config file I cannot see any license plate being recognised by Frigate (I validated it using the debug window). I have the feeling that the reason for this might be that I didn´t annotate any license plate in the images with cars that I annotated to create my model, could this be the case? and if so, is there an easy way to re-annotate those images to add the license plate? I tried to do it but every time I re-annotate one image and save it, the Frigate+ screen jumps back to the list of images instead of opening the next image (which I guest it´s normal as all the images are already annotated).

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: xxxxxxxxxxxxx
  user: xxxxxxxxxxxxx
  password: xxxxxxxxxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://xxxxxxxxxxxxx

database:
  path: /db/frigate.db

objects:
  track:
    - person
    - cat
  filters:
    person:
      threshold: 0.9
    cat:
      threshold: 0.9

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

audio: # <- enable audio events for all camera
  enabled: True
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - cat
    - music
    - ice_cream_truck
    - police_car
birdseye:
  mode: continuous 
  width: 1920
  height: 1080

record:
  enabled: True
  retain:
    days: 30
  events:
    retain:
      default: 120

snapshots:
  retain:
    default: 120

detect:
  enabled: True
  width: 1280 # <---- update for your camera's resolution
  height: 720 # <---- update for your camera's resolution
  fps: 5
  stationary:
    interval: 150

motion:
  contour_area: 20
  mask:
    - 1236,29,1236,60,880,61,880,27

go2rtc:
  streams:
    dahua_1:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_1_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_2:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_2_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_3:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_3_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_4:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_4_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_5:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_5_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_6:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_6_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_7:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_7_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_8:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
    dahua_8_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=2
    dahua_9:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/live/main
    dahua_9_sub:
      - rtsp://xxxxxxxxxxxxx:xxxxxxxxxxxxx@xxxxxxxxxxxxx:554/live/sub

cameras:
  dahua_1: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_1 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    objects:
      track:
        - person
        - cat
        - car
        - license_plate
      filters:
        person:
          threshold: 0.9
        cat:
          threshold: 0.9
        car:
          threshold: 0.9
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        - 930,1512,1905,1512,2075,1182,1590,983
        - 2014,704,2073,704,2153,336,2077,321
    zones:
      outside_main_door:
        coordinates: 714,538,0,691,0,1512,1168,1512,2161,1002,2237,785

  dahua_2: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_2 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_2_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
            - audio
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 1236,29,1236,60,880,61,880,27
        - 202,720,869,720,564,436,162,568

  dahua_3: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_3 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        - 2688,0,2688,281,2538,301,2103,160,2091,0
        - 2205,1520,1574,1143,951,1520

  dahua_4: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_4 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60
        #- 1784,748,2241,932,2423,237,1832,85

  dahua_5: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_5 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 2688,0,2688,932,1032,376,997,0
    objects:
      track:
        - person
        - cat
        - car
        - license_plate
      mask:
        - 160,1436,233,1379,119,1197,44,1262
      filters:
        person:
          threshold: 0.9
        cat:
          threshold: 0.9
        car:
          threshold: 0.9

  dahua_6: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_6 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    zones:
      Worktop:
        coordinates: 1771,531,2688,865,2403,1520,1987,1520,1743,1520,2332,877,1654,599
      Island:
        coordinates: 954,726,1285,1022,1609,865,1207,654
    motion:
      mask:
        - 2600,60,2600,125,2000,125,2000,60

  dahua_7: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_7 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_7_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
            - audio
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    zones:
      inside_office:
        coordinates: 586,288,1280,374,1280,720,0,720,0,585,309,416

  dahua_8: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_8 # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_8_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
            - audio
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False

  dahua_9:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_9 # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: True
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 150
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    mqtt: # only apply to snapshots
      enabled: False
    motion:
      mask:
        - 426,29,426,60,80,61,80,27
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua HDW5442TM

**Comment by blakeblackshear** [comment]
It should still identify license plates on the cameras where you have it listed under `track:` unless your cameras perspective is very unusual. They do not show up as separate objects, but rather an additional bounding box on car objects.

There is not a better workflow to go back and re-annotate in Frigate+ yet. It is something I am working on because it will be very necessary for adding new labels.

**Reply by heisenberg2980** [reply]
I could only think about my annotations on my model missing the licence plates, because this is one example of the camera dahua_5, which contains the licence_plate under `track:` in my config, but it´s not picking up the licence plate even though it is clearly visible and the car is recognised with a 98% accuracy:

![image](https://github.com/user-attachments/assets/c3d37532-bef3-4c68-a6a6-68fed9db080a)

I tried reducing the threshold to 0.6 for licence_plate, but it´s still not picking it up.

**Reply by heisenberg2980** [reply]
Frigate finally reported the licence_plate attribute 30 minutes after the car was stationary, with a maximum score of 0.77, which I think it´s low considering the clarity of the picture. It is still not reporting other licence plates of a different camera (dahua_1) where the cars are a bit smaller in the picture but the licence plates are still readable.
I guess the low score could be due to my lack of licence plate annotations in my model (it would be good to know if I could increase this by re-annotating all my images containing cars), but is there a reason for Frigate to take so long (30 minutes) to report the licence plate?

**Reply by NickM-27** [reply]
Most likely just due to the low score, I haven't checked over the config yet but you could try lowering the threshold for license plate. I have no issues like that personally ![image](https://github.com/user-attachments/assets/022741fd-2e5a-4631-94d7-b4da79b1632a)

**Reply by heisenberg2980** [reply]
I have lowered the threshold for licence plate to 0.5 with a similar result, the licence plate is still not appearing in the debug window or reported in mqtt.

I am in the UK, could the different format of the EU licence plates be causing trouble for Frigate to recognize it if the baseline model has been trained mainly with US licence plates? https://www.myparkingsign.com/european-and-american-license-plate-differences

**Reply by NickM-27** [reply]
it is certainly possible, Blake would be the best person to answer that as I don't know how many EU plates are in the dataset

**Reply by NickM-27** [reply]
If that is the case, that would mean you annotating and submitting the plates correctly would improve the results

**Reply by heisenberg2980** [reply]
> There is not a better workflow to go back and re-annotate in Frigate+ yet. It is something I am working on because it will be very necessary for adding new labels.

@blakeblackshear do you have an estimated timeline for this? It would be good to know if it´s worth waiting, as I would expect a massive difference in effort when trying to re-annotate images

**Reply by blakeblackshear** [reply, marked as answer]
I don't have a specific timeline for that feature, but it won't be this month.

I have a lot of EU license plates in the training data, so I don't think that's the issue.

I haven't run a side by side comparison, but it could be that you have convinced your model the license plates aren't there.

You may just want to wait until I implement AI suggested labels. Then you will have a bunch of suggestions for license plates to review. I'm hoping to have that ready in the next couple months.

**Comment by ElectronicBattle** [comment]
@blakeblackshear  @NickM-27   I have also failed to detect any cat number plates since I started in the middle of July.

"licence_plate" is listed as an object to detect for two out of for of my cameras but as far as I can recall I also haven't seen any detections for licence plates on either of them. 

So far I have submitted  770 images to F+, about half of which are for the cameras which want to detect licence_plates. I have diligently been transferring the images to F+ and matching them up to show "car" (which it detects very successfully) and also "licence_plate" when relevant to do so (along with dog/cat/person etc.).  

I imagine I have sent at least 100 images containing cars and number plates and I reckon I have marked at least 80-90 of them, failing to do so in the early days of my use. 

I have included my work-in-progress full config at https://pastebin.com/ZT0jTWyg and perhaps I originally made a mistake in the detection part (which I havent changed since starting six weeks ago).

The "blue gate" camera  sees cars like this (which is probably a bit demanding):
![image](https://github.com/user-attachments/assets/1f18f985-b4fc-4ab2-89dd-789105a4db96)

The "drive" camera detects cars like this (which looks easier - note I have intentionally blurred the number plate in this image):
![image](https://github.com/user-attachments/assets/ff28d3c8-7b87-46b7-995e-138b9ae3416e)

(Number plates here are in the form "AB23 CDE")

> They do not show up as separate objects, but rather an additional bounding box on car objects.

I have never seen this. Actually, I only ever see one bounding box per image even if the image also contains people/cats/dogs etc.

[_edit 13/9/24: now that I have corrected my spelling from `licence_plate` to the required `license_plate` I have immediately seen a car  number plate and a car_] 

I am happy to provide full logs etc. here but I didn't want to get in the way should this not be interesting or if I have made a mistake.

**Reply by heisenberg2980** [reply]
~~@ElectronicBattle I am not sure if you are aware of this, but when Blake mentioned "an additional bounding box on car objects" I believe he meant in the debug window, as that is the only place where you will see the extra box around the licence plate. The snapshot of an event will always contain only one box (even if the picture includes more than one, because that will create multiple snapshots). If you want to check if your Frigate is detecting the license plate, go to the debug window and check if the licence_place box is displayed there.~~

Another option is to read the mqtt messages from the topic "frigate/events" and check if the field "after.current_attributes" contains the licence_plate flag (in my case this only happened once as I mentioned above, and I was able to capture it by using an automation in node-red that notified me if that field was populated in any of the messages)

**Reply by ElectronicBattle** [reply]
@heisenberg2980 that's excellent info and advice - thanks! I didn't know.  I had better start using the debug window immediately to check on "licence plate" detections.

I don't have MQTT configured in F yet but I do use it elsewhere so it would be easy for me to implement.

**Reply by NickM-27** [reply]
If a license plate was detected above threshold it'll be included in the snapshot, like I showed earlier

**Reply by heisenberg2980** [reply]
I thought your screenshot was the debug window and not a snapshot, sorry for creating confusion. 
@ElectronicBattle it seems both of us are having the same issue with our Frigate not recognising licence plates, and as the format you mentioned ("AB23 CDE") is the same here in the UK, I think the issue might be related with the licenses plate used to train the model being mainly from US

**Reply by ElectronicBattle** [reply]
No problem - I am very easily confused!  Yes, I'm also in England; I have many things to sort out with my Frigate implementation (it's only a hobby, mainly for spotting wildlife eventually) and when I saw your post I realised that I should add this "number plate blindness" as an additional problem on my list.

**Reply by NickM-27** [reply]
To be clear a "person" snapshot will not have a license plate labeled. It has to be a car snapshot. (Person might include a face if a face was detected)

**Reply by ElectronicBattle** [reply]
@NickM-27 OK, understood. 
What I have been doing is submitting images which are incorrectly classified ("this is a dog" when in fact it is a car) and making sure that I box in the car and I box in the licence_plate in F+.  
Additionally, when things are correctly classified ("this is a car" or even "this is a dog but there is a car in the same shot) I've been submitting one out of very few and also annotating to show the licence_plate as well.  

Perhaps I too should lower the default threshold now (from memory, 0.7 I think) because none of the images I have seen have had a licence_plate identified in them.  

(I have built up a good "library" of images submitted to F+ so I might ask for a trained model soon, but I want to get every thing else sort out beforehand).

**Reply by heisenberg2980** [reply]
@ElectronicBattle I want to double-check something as your last comment gives me some doubts, when you say you have submitted and annotated over 100 images with licence_plate, have you generated a model after submitting those images and are you using that model now? I´m just asking because if you have uploaded all those images to Frigate+ and annotated them, but you haven´t generated a new model after that, then those images and annotations are not being used by your model and you will not know if they fix your issue with the licence plate recognition until you generate a new model and use it in your Frigate

**Reply by ElectronicBattle** [reply]
No - I have *not* generated any models yet.

My understanding is that when I *do* decide to generate a model, all of the images I have submitted will be used  and - importantly - all of the images from me also help other "Frigateers".

(I have now started to check using the debug view specifically for future lic plate detection signs and I will see what happens).

**Reply by heisenberg2980** [reply]
Ah ok, in that case we are in a similar boat, because I have generated some models but I didn´t annotate licence plates in any of the images I uploaded, so it is still unknown the effect of annotating licence plates and generating a new model (hopefully the updated model will recognise the UK number plates and the issue will be partially solved, with the final solution being the addition of EU licence plate to the baseline model so the model recognise them without the need to annotate them).

By the way, if you have already uploaded and annotated over 700 images to Frigate+, I would advise you to generate a model now to test it, you will be impressed with the difference in the accuracy of your new model compared to the default model. When I generated my first model I was so impressed by the result that I immediately increased the threshold in my config file from 0.75-0.8 that I had before for different objects (person, car, etc.) to 0.9 for every single object, and I could even go to 0.95 if I wanted to as most of the time the detection value is 97-98% (before it never went over 84%), the difference in quality is massive!

**Reply by ElectronicBattle** [reply]
That sounds ace! I am keen to get some custom models tuned for me but I am struggling so much with the rest of the config that I can't risk taking on even more stuff to configure at the moment.  Running before I can walk etc.  but luckily people like you and Nick and Haweye217 and others are very helpful.

**Reply by ElectronicBattle** [reply]
A brief update mainly for @heisenberg2980 : I now have Frigate 0.14 running in Docker (as well as my original 0.13 on a separate box. Looking in the debug view I have seen many boxes pop up today (car, person) but none for licence_plate.  
Your theory seems sound - the UK pattern is sufficiently different from US/EU to not show up.

**Comment by ElectronicBattle** [comment]
a reference image with  annotation hidden
![image](https://github.com/user-attachments/assets/76609467-0cd7-48d5-9724-7f4ea50385e6)

image as annotated by Frigate
![image](https://github.com/user-attachments/assets/1b50a42f-e4a4-4507-843f-7cdfc4a23b2c)

my addition of "licence_plate", prior to submitting to F+
![image](https://github.com/user-attachments/assets/51d5b7e4-6640-4850-bcc4-d89a9c377b63)

Would other Frigate users expect the licence_plate to be detected in these conditions? Night time, slight rain and a very vivid IR reflection from the number plate.  Daytime shots are similar, i.e. the car's detected but the clearly visible plate isn't, as per @heisenberg2980 's earlier images and observations.

**Reply by BradFD** [reply]
> a reference image with annotation hidden ![image](https://private-user-images.githubusercontent.com/10836275/355468402-76609467-0cd7-48d5-9724-7f4ea50385e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Nzc5OTgsIm5iZiI6MTcyMjk3NzY5OCwicGF0aCI6Ii8xMDgzNjI3NS8zNTU0Njg0MDItNzY2MDk0NjctMGNkNy00OGQ1LTk3MjQtN2Y0ZWE1MDM4NWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDIwNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTBlZTBkZmViMmQwMDk1ODUwZmUxNDg2ZWQxZmY1NjRiZTcxNDc0NTVhNGNiNDg1MDE3YWYxNDRjZDllMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oOneSvlCe3Y8yk9iLJxFV_pgqTpEtEOMO3yfmwDWKQ)
> 
> image as annotated by Frigate ![image](https://private-user-images.githubusercontent.com/10836275/355468752-1b50a42f-e4a4-4507-843f-7cdfc4a23b2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Nzc5OTgsIm5iZiI6MTcyMjk3NzY5OCwicGF0aCI6Ii8xMDgzNjI3NS8zNTU0Njg3NTItMWI1MGE0MmYtZTRhNC00NTA3LTg0M2YtN2NkZmM0YTIzYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDIwNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZDU4ZDA5MDIzYThhYTQ1NTRmNDcyMGE3MjUwZGZlOWM5ZDAzM2E0NmRiZGJkYTUxY2FiMjQxOTIzMGM3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BRCsq6-TM_s5NQ0-_WbeLHeBp7p1GPfWSVxR9F-Ko64)
> 
> my addition of "licence_plate", prior to submitting to F+ ![image](https://private-user-images.githubusercontent.com/10836275/355468914-51d5b7e4-6640-4850-bcc4-d89a9c377b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Nzc5OTgsIm5iZiI6MTcyMjk3NzY5OCwicGF0aCI6Ii8xMDgzNjI3NS8zNTU0Njg5MTQtNTFkNWI3ZTQtNjY0MC00ODUwLWJjYzQtZDg5YTljMzc3YjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDIwNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMmVkNmQ1M2U4YmVlNjdiMWExMTFjYzJjYjk0YmNjMTc5NzdjNTI0YzlmYWRhM2MwYzRmM2Q1YTdlZWNiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgSRsP5aFeavO9oGdkEHZph7ZJYXAD3u82gnidW8ajI)
> 
> Would other Frigate users expect the licence_plate to be detected in these conditions? Night time, slight rain and a very vivid IR reflection from the number plate. Daytime shots are similar, i.e. the car's detected but the clearly visible plate isn't, as per @heisenberg2980 's earlier images and observations.

Mine does very poorly at night with cars and plates under the conditions needed for good clear plates which is a near total dark scene to quelch the head/tail lights and have the IR reflection of the plate not be washed out. Ideally almost everything will be very very dark at night except for the plate to get the clearest plate image but then frigate fails to detect the car or plate because it is soooooo dark Thus, I have to be content with just the motion capture that has the plate to review if it is needed.

**Reply by NickM-27** [reply]
I have a color night vision camera but it works fine for mine

![Screen Shot 2024-08-06 at 15 04 21 PM](https://github.com/user-attachments/assets/ea65f771-5a8e-4890-a4db-f8e646a0c96f)

**Reply by BradFD** [reply]
> I have a color night vision camera but it works fine for mine
> 

My best mounting spot is too far and not enough light for color so rely on zoom and IR which works decently well but only plate looks good. The rest of a car is like a shadow and Frigate doesn't see a car or plate then hardly ever.

**Reply by heisenberg2980** [reply]
@ElectronicBattle the rule of thumb is that Frigate can only recognize things that you could recognize by looking at that picture. According to the image you submitted the number plate is completely white due to the IR reflection, and in that case I doubt Frigate will be able to recognize it (and even if it does, it would be useless as you wouldn´t be able to extract the licence plate numbers, which is the reason to have licence plate recognition in the first place).

I think we should stick to the licence plates that are easily readable but Frigate don´t pick up, so we try to fix that issue first, and once that is solved we will see if more complex scenarios can be solved.

**Reply by ElectronicBattle** [reply]
I agree and I understand that rule of thumb. I was wondering, though, if Frigate does something additionally, like calculating the aspect ratio of the "number_plate" rectangle and then deciding if its area falls within the object detection area of "car".  

I think anyone would see my night-time IR image and say "that's clearly a number plate, although I can't read it" .  Reading a plate and recognising a plate are very different things from the point of view of a human rule-of-thumb which is where the guideline breaks down of course, hence my thoughts.  It *is* merely a guideline, I know. 

The reasoning for my posting is to talk about (what I think are) minor differences  in  the range of character layouts in the UK not being  radically different from those in the EU (Dutch plates for example, and I think Belgian ones). 

The fonts and character sizes are/were probably defined by EU law (or at least limited in the range of fonts and sizes) and hence likely to be a similar set, part of which is to make them easily readable by national ANPR systems and hence introduce a degree of commonality.

 I know some plates in the US appear radically different, but if there are 

> a lot of EU license plates in the training data

ready for analysis then I am interested to learn why  UK ones (or perhaps some other specific countries?) aren't identified.

I recognise that reading the characters off the plates is yet another level.

(@heisenberg2980 I still haven't submitted a model request Victor - too busy fiddling with settings to get things as good as I can before doing so!).

**Reply by ElectronicBattle** [reply]
@jakeycrx and referring to your thread at https://github.com/blakeblackshear/frigate/discussions/13023#discussioncomment-10633365   
I am following all of this with great interest for my own set of circumstances but do you ever get *any* `licence_plate` detections?  I get none at all, even though some shots are pristine and square on and (I imagine) ideal ...there seems to be a problem with the UK format even though the set of EU plates used in the model are detected properly (and our font and spacing format is the same as a lot of EU countries).  

(@heisenberg2980 I did eventually generate a model a couple of weeks ago, which has contributed some significant improvements, but more work needed).

**Reply by NickM-27** [reply]
Double checking that you've enabled the license plate label in the object -> track config?

**Reply by ElectronicBattle** [reply]
I *think* I have done it correctly:  my config shows these parts which I hope are correct. 

Firstly, general thresholds taken from the generic config (but altered recently for cats and dogs and people due to local model training):

```
objects:
  filters:
    dog:
      min_score: .8
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    license_plate:
      min_score: .6
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
```

and then secondly, specifically per camera and e.g. for the camera looking at our driveway for vehicular access:

```
drive: #########DRIVE#########DRIVE#########DRIVE#########DRIVE#########DRIVE#########DRIVE
    enabled: true

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
      - car
      - licence_plate
```

For my model stats I see this (spread across eight cameras, only two of which can see vehicles and number plates):
![image](https://github.com/user-attachments/assets/4162bd31-6844-4ee9-85fe-9aed2767bef6)

and so far I have submitted 300 images for the "drive" camera.  

(I am not  looking for faces/Amazon/FedEx etc anywhere but I am looking for cars and their number plates, people, animals).
