### DISCUSSION TITLE
[Support]: Review page slow to load

### DISCUSSION THREAD

**Discussion by mdv0** [blakeblackshear/frigate#12734] [General Support]
### Describe the problem you are having

It takes almost 15 sec to load events in reviews tab., its been the same from the start of frigate 14 beta 2 and still same on rc1. On frigate 13 events tab loaded up all the events/video almost instantly, but it takes forever to load reviews on 14 rc1. 1 am running 20 cam two of which are 4mp others 1080 pand even reduced the num of cam to 10 but still same issue. video attached as well 

### Steps to reproduce

when ever i refresh or go to reviews tab 

### Version

14rc-1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.150

#####################################################   Universal Config for all Cameras   #########################################################
detectors:
  coral:
    type: edgetpu
    device: pci:0

#detectors:
#  deepstack:
#    api_url: http://192.168.0.200:32168
#    type: deepstack
#    api_timeout: 0.1 # seconds

record:
  enabled: true
  retain:
    days: 4
    mode: all
  events:
    retain:
      default: 15
      mode: motion

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 15

objects:
  track:
    - person
    - dog
    - cat
    - car
    - motorcycle
    - bicycle

birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: objects

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128

go2rtc:
  streams:
    webrtc:
    candidates:
      - 192.168.1.10:8555
      - stun:8555
    Db:
      - rtsp://192.168.0.212:554/Streaming/Channels/101
    Db_sub:
      - rtsp://192.168.0.212:554/Streaming/Channels/102
    Cruiser:
      - rtsp://192.168.0.205/cam/realmonitor?channel=1&subtype=0
    Cruiser_sub:
      - rtsp://192.168.0.205/cam/realmonitor?channel=1&subtype=1
    Bullet:
      - rtsp://192.168.0.206/cam/realmonitor?channel=1&subtype=0
    Bullet_sub:
      - rtsp://192.168.0.206/cam/realmonitor?channel=1&subtype=1
    Hik:
      - rtsp://192.168.0.203/Streaming/Channels/101
    Hik_sub:
      - rtsp://192.168.0.203/Streaming/Channels/102
    Lounge:
      - rtsp://192.168.0.207/cam/realmonitor?channel=1&subtype=0
    Lounge_sub:
      - rtsp://192.168.0.207/cam/realmonitor?channel=1&subtype=1
    Loungedown:
      - rtsp://192.168.0.208/cam/realmonitor?channel=1&subtype=0
    Loungedown_sub:
      - rtsp://192.168.0.208/cam/realmonitor?channel=1&subtype=1
    Garden:
      - rtsp://192.168.0.211/cam/realmonitor?channel=1&subtype=0
    Garden_sub:
      - rtsp://192.168.0.211/cam/realmonitor?channel=1&subtype=1
    Car:
      - rtsp://192.168.0.209/Streaming/Channels/101
    Car_sub:
      - rtsp://192.168.0.209/Streaming/Channels/102
    Entrance:
      - rtsp://192.168.0.210/Streaming/Channels/101
    Entrance_sub:
      - rtsp://192.168.0.210/Streaming/Channels/102
    Mptz:
      - rtsp://192.168.0.204:554/live/ch00_0
    Mptz_sub:
      - rtsp://192.168.0.204:554/live/ch00_1
    Office:
      - rtsp://xyx/cam/realmonitor?channel=1&subtype=0
    Office_sub:
      - rtsp://xyz/cam/realmonitor?channel=1&subtype=1

##########################################################################################################################################

###################################################         Camera Config     ############################################################
cameras:
  Cruiser: #####################      Cruiser Cam Config    #####################
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Cruiser_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Cruiser
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 403,0,571,0,576,29,311,83,0,199,0,111,0,0
    zones:
      zone_0:
        coordinates: 411,327,490,268,556,188,640,131,640,480,591,480,406,480,202,480
    objects:
      mask: 0.786,0.009,0.751,0.094,0.892,0.142,0.918,0.039

  Bullet: #####################   Bullet Cam Config  ##################################
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Bullet_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Bullet
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 640,0,640,74,640,150,505,85,392,37,396,0
        - 258,99,316,62,305,0,146,0,150,70
    objects:
      filters:
        car:
          mask:
            - 147,27,165,77,88,87,84,23
    zones:
      zone_0:
        coordinates: 0,480,0,67,122,156,244,307,339,387,428,480

  Hik: #########################   HiLook Cam Config  #################################
    ui:
      order: 3
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Hik_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Hik
          roles:
            - record
    motion:
      mask:
        - 341,0,332,30,140,42,0,86,0,86,0,51,0,0
    objects:
      mask: 0.785,0.29,0.797,0.413,0.912,0.384,0.891,0.281

  Db:  ########################       DoorBell Cam config           ####################
    ui:
      order: 5
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.0.212:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Db
          roles:
            - record
    motion:
      mask:
        - 245,0,640,0,640,192,269,208,0,198,0,0
    zones:
      zone_0:
        coordinates: 640,403,640,480,191,480,0,480,0,413

  Car:  #######################  Car Cam Config  ############################################
    ui:
      order: 6
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Car_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Car
          roles:
            - record
    objects:
      track:
        - person
        - cat
    motion:
      mask:
        - 0,21,155,25,162,0,0,0,0,0

  Entrance:  ########################  Entrance Cam Config  ######################################
    ui:
      order: 7
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Entrance_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Entrance
          roles:
            - record
    objects:
      track:
        - person
        - cat
    motion:
      mask:
        - 162,24,163,0,0,0,
```

### Relevant log output

```shell
2024-08-03 04:38:37.036824298  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-08-03 04:38:49.658973  2024-08-03 04:38:37.036825714
2024-08-03 04:38:49.658976  2024-08-03 04:38:37.036827122
2024-08-03 04:38:37.316096046  [2024-08-03 04:38:37] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/Db@20240803043826+0500.mp4
2024-08-03 04:38:37.316230142  [2024-08-03 04:38:37] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/Db@20240803043826+0500.mp4
2024-08-03 04:38:47.019506969  [h264 @ 0x70c624165980] missing picture in access unit with size 119981
2024-08-03 04:38:47.019782730  [extract_extradata @ 0x70c624014580] No start code is found.
2024-08-03 04:38:47.019884293  [ WARN:0@220739.506] global cap_ffmpeg_impl.hpp:1167 open Unable to read codec parameters from stream (Invalid data found when processing input)
2024-08-03 04:38:47.020042352  [ERROR:0@220739.506] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-08-03 04:38:49.658980  2024-08-03 04:38:47.020045002
2024-08-03 04:38:47.020047781  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-08-03 04:38:49.658983  2024-08-03 04:38:47.020049382
2024-08-03 04:38:49.658986  2024-08-03 04:38:47.020050803
2024-08-03 04:38:47.262702228  [2024-08-03 04:38:47] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/Db@20240803043836+0500.mp4
2024-08-03 04:38:47.262861259  [2024-08-03 04:38:47] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/Db@20240803043836+0500.mp4
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision, imou ranger2, cruiser4mp
