### DISCUSSION TITLE
[HW Accel Support]:NVIDIA GeForce 920M

### DISCUSSION THREAD

**Discussion by tv4you2016** [blakeblackshear/frigate#12736] [Hardware Acceleration Support]
### Describe the problem you are having

![image](https://github.com/user-attachments/assets/def08b66-b1c4-4285-b8af-980da34ca311)

![image](https://github.com/user-attachments/assets/fffc333b-8402-435a-805e-2c230132f81d)

![image](https://github.com/user-attachments/assets/73900a4b-9707-47b9-a6d6-24127ac6d648)

**ERROR:** 
![image](https://github.com/user-attachments/assets/40b37225-7fbb-430b-87e7-d50d140f2124)

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb


ffmpeg:
  hwaccel_args: preset-nvidia-h264
    
cameras:
  jardim: # <------ Name the camera
    enabled: true
    ffmpeg:
      
      inputs:
        - path: rtsp://192.168.1.xxxxxxxxxx/user=admin&password=asdasdsdadada&channel=1&stream=1.sdp?real_stream--rtp-caching=100
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 5

  frente: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.cxxxx/user=admin&password=yyyyyyyyy&channel=1&stream=1.sdp?real_stream--rtp-caching=100
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 5
  garagem: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:yyyyyyyy@192.168.1.xxxxx:554/12
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 5
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='bridge'
  --cpuset-cpus='1,3'
  --privileged=true
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='enterpassword'
  -e 'PLUS_API_KEY'=''
  -e 'LIBVA_DRIVER_NAME'='iHD'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-2d2f9c74-36d9-4674-f7a5-1daa70182151'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='compute,utility,video'
  -e 'YOLO_MODELS'='yolov4-416,yolov4-tiny-416'
  -e 'USE_FP16'='false'
  -e 'TRT_MODEL_PREP_DEVICE'='0'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '5000:5000/tcp'
  -p '8554:8554/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -p '1984:1984/tcp'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/user/Media/frigate':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/bus/usb'
  --device='/dev/dri/renderD128'
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:0.14.0-rc1'
20188e92603aad2fad43b13fb011d8094c36884edd5f47385c220ffcffcfd33f
```

### Relevant log output

```shell

```

### FFprobe output from your camera

```shell
nd
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

others

### Any other information that may be helpful

the nvidia gpu is not detected
