### DISCUSSION TITLE
[Support]: Frigate+ Free account & button/UI with 0.14 RC1

### DISCUSSION THREAD

**Discussion by ikout** [blakeblackshear/frigate#12737] [General Support] [answered]
### Describe the problem you are having

I want to test the Frigate+ so I started a free account and got the API key that I added at the docker compose file in the "environment" section but I don't see the Frigate+ icon/buttons.

At the docs there is this note/warning:
"You cannot use the "environment_vars" section of your configuration file to set this environment variable."

But for which file are we talking about? The docker compose or the "config/config.yml" one?

If that's the "config.yml" that the message is about why I'm not seen the Frigate+ options?
Is that limited to paying accounts only?

### Version

0.14 RC1

### Frigate config file

```yaml
mqtt:
  enabled: false
#
# ====================================================================================================================
#
#
ffmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration
  output_args:
    record: preset-record-generic-audio-aac
# ====================================================================================================================
detectors:
  coral:
    type: edgetpu
    device: usb
# ====================================================================================================================
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
# ====================================================================================================================
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: False
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100
```

### Relevant log output

```shell
No logs about the Frigate+ that I can see
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

Tp-Link - Tapo

### Any other information that may be helpful

I don't use it with Home Assistant at the moment, it's a "standalone" install on a Raspberry Pi 5 with Coral USB
So I also have mqtt disabled.
