### DISCUSSION TITLE
[HW Accel Support]: Camera with multiple codecs

### DISCUSSION THREAD

**Discussion by stephenpapierski** [blakeblackshear/frigate#12733] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I have a Reolink RLC-820A which uses h264 for the substream and h265 for the main stream. I'm using an NVIDIA GTX 1060. How do I add multiple hw_accel_args for the different streams?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors: # <---- add detectors
  tensorrt:
    type: tensorrt
    device: 0 # This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

cameras:
  front_left: # camera name
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: 
          rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.93.1.103:554/h264Preview_01_sub # detect stream (h264)
        roles:
        - detect
      - path: 
          rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.93.1.103:554/ # record stream (hevc)
        roles:
        - record
    detect:
      enabled: true
    record:
      enabled: true
    motion:
      mask:
      - 1280,0,1280,266,1031,191,664,106,82,0   # Sidewalk/Street
      - 0,0,392,0,391,51,0,49                   # Timestamp
```

### docker-compose file or Docker CLI command

```yaml
Running on Unraid
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-820A
