### DISCUSSION TITLE
[Config Support]: tls_insecure: true - not working

### DISCUSSION THREAD

**Discussion by romanad** [blakeblackshear/frigate#12745] [Config Support]
### Describe the problem you are having

Hello,
it seems to me that option "tls_insecure: true" not working for mqtt
I'm using let's encrypt certs, and this is my config:
---
mqtt:
  enabled: true
  topic_prefix: frigate
  client_id: frigate
  host: 192.168.5.220
  port: 8883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 60
  tls_ca_certs: /certbot/isrgrootx1.crt
  tls_insecure: true
---
and I keep getting error "Certificate has expired"
I'm getting this error in MQTT Explorer if I don't disable "Validate certificate" toggle, and if I disable that toggle everything works fine in MQTT Explorer .

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
#false
#true

mqtt:
  enabled: true
  topic_prefix: frigate
  client_id: frigate
  host: 192.168.5.220
  port: 8883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 60
  tls_ca_certs: /certbot/isrgrootx1.crt
  tls_insecure: true


record:
  enabled: false
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30




cameras:
  Camera_1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.5.105:554/stream1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.5.105:554/stream2
          roles:
            - record
    onvif:
        host: 192.168.5.105
        port: 2020
        user: "{FRIGATE_RTSP_USER}"
        password: "{FRIGATE_RTSP_PASSWORD}"
```

### Relevant log output

```shell
Home assistant:

2024-08-04 05:24:48: OpenSSL Error[0]: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired
2024-08-04 05:24:48: Client <unknown> disconnected: Protocol error.

Frigate:
 frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
```

### Operating system

HassOS

### Install method

Docker CLI

### Object Detector

CPU (no coral)
