### DISCUSSION TITLE
[Config Support]: Occupancy reporting

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#12749] [Config Support]
### Describe the problem you are having

Hi,

I'm using the cat occupancy sensor within the Frigate HAOS integration to play various sounds to try and discourage cats from urinating and defecating everywhere. I'm getting false triggers though.  There is activity at the time of the false trigger and the camera is autotracking (people and cars), so I guess it must be detecting a false positive of a cat from something.  There is nothing stored anywhere to see what the false trigger was though.

There was a false trigger at 11:30.  The trigger at 7:07 was genuine.

![image](https://github.com/user-attachments/assets/e2372278-a444-49fd-a288-d7cd6d8d0952)

The last image stored for a cat is 7:07:

![image](https://github.com/user-attachments/assets/68a3af0c-c34c-45a0-afd7-670f6e2364da)

That is also the last image stored in the Frigate+ section on the UI, there is nothing stored for the 11:30 trigger:

![image](https://github.com/user-attachments/assets/4a56ebe7-cf11-4bbd-a949-eac5137889bc)

I have set the min score in my config for cats.  Is there any way of tying the occupancy sensor to the min score with the median scoring?  I guess it's seeing a false trigger of a cat for one frame from something therefore triggering the occupancy sensor?

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
dahua:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://****:****@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
          input_args: -avoid_negative_ts make_zero -timeout 5000000 -buffer_size 10000K
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          max_ratio: 0.8
          min_score: 0.65
          threshold: 0.8
        cat:
          min_score: 0.7
          threshold: 0.8
        dog:
          min_score: 0.7
          threshold: 0.8
    detect:
        # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 75
    zones:
      car_detection_dahua:
        coordinates: 
          0.279,0.192,0.034,0.238,0.024,0,0.480,0,0.611,0,0.615,0.192,0.509,0.158,0.405,0.154
        objects:
          - car
      overall_detection_dahua:
        coordinates: 0,1,1,1,1,0,0,0
        objects:
          - person
          - cat
          - dog
      light_detection_dahua:
        coordinates: 
          0.893,1,0.12,1,0.016,0.304,0.067,0.292,0.248,0.232,0.348,0.243,0.505,0.253,0.678,0.428,0.741,0.544,0.731,0.683
        objects:
          - person
    motion:
      mask: 0.736,1,0.969,1,0.969,0.9,0.888,0.894,0.887,0.943,0.778,0.946,0.736,0.944
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 5
        post_capture: 20
        retain:
          default: 5
          mode: all
          objects:
            cat: 90
            dog: 90
    snapshots:
      required_zones:
        - car_detection_dahua
        - overall_detection_dahua
      enabled: true
      clean_copy: true
      retain:
        default: 45
```

### Relevant log output

```shell
No log entry at 11:30
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral
