### DISCUSSION TITLE
[Support]: Can't get frigate plus in portainer

### DISCUSSION THREAD

**Discussion by mariusvr** [blakeblackshear/frigate#12764] [General Support] [answered]
### Describe the problem you are having

Can't get frigate plus activated. Got my PLUS key through the website, Using enviroment variables, the API_KEY doesn't seem to be recognized and I have no option to send to frigate plus. The same problem with the stable version, rather than the beta. I use portainer.

### Steps to reproduce

services:
  frigate:
    container_name: frigate_beta
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4
    shm_size: "256mb" # update for your cameras based on calculation
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions 
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/sda2/frigate2/config:/config  # modify to match your setup
      - /mnt/sda2/frigate2/db:/db  # modify to match your setup      
      - /mnt/sda2/frigate2/media:/media/frigate  # modify to match your setup      
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "SECRET" 
      PLUS_API_KEY: "SECRET"

### Version

beta

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.180
  port: 1883
  user: user1
  password: SECRET
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 120

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

audio:
  # Optional: Enable audio events (default: shown below)
  enabled: false
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  cave: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SECRET@192.168.1.108:554 # <----- The stream you want to use for detection
          roles:
            - audio
            - detect
            - record
            - rtmp
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 300
      quality: 70
  driveway: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SECRET@192.168.1.109:554 # <----- The stream you want to use for detection
          roles:
            - audio
            - detect
            - record
            - rtmp
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 300
      quality: 70      

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

objects:
  track:
    - person
    - cat
    - dog
record:
  enabled: true
  retain:
    days: 7
  events:
    retain:
      default: 7
      mode: motion
      objects:
        person: 180
        dog: 30
        cat: 30

version: 0.14
```

### Relevant log output

```shell
nil
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

dahua
