### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by Kedryn** [blakeblackshear/frigate#12771] [Config Support] [answered]
### Describe the problem you are having

Some of my cameras (i use different brands) have wrong aspect ratio between normal channel and sub channel
![image](https://github.com/user-attachments/assets/4eeeaf37-e3b1-40b4-996f-73bbb3a7f4d3)
This one when no movement is detected
![image](https://github.com/user-attachments/assets/163e3bc4-8558-43fa-9722-d302f2b32c8e)
This when movement is detect
To be honest, i'm not entirely sure that the "switching" happens when movement is detected.
the camera is H265 2688x1520 in main stream, and  H265 D1 (720x576) in sub stream

That happens with some other brands, but not all.
For some other (like Tapo c100) i dont even need to specify any resolution.

### Version

0.14b4

### Frigate config file

```yaml
go2rtc:
  streams:
    ingresso_rec:
      - rtsp://admin:Extreme@192.168.0.201:554/stream0
    ingresso_det:
      - rtsp://admin:Extreme@192.168.0.201:554/stream1
    campo_rec:

cameras:
  ingresso:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ingresso_rec
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/ingresso_det
          roles:
            - detect

    motion:
      mask: 0.197,0.281,0.289,0.332,1,0.48,1,0,0,0,0,0.239
    best_image_timeout: 60
    detect:
      enabled: true
      width: 720
      height: 576
    live: 
        stream_name: ingresso_rec
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []

    ui:
      order: 1
      dashboard: true
```

### Relevant log output

```shell
none
```

### Operating system

Debian

### Install method

Docker CLI

### Object Detector

OpenVino
