### DISCUSSION TITLE
[Bug]: 0.14.0 Release Candidate 2 UI Detect / Recording / Snapshot icons and preview recordings

### DISCUSSION THREAD

**Discussion by derhappy** [blakeblackshear/frigate#12779] [Report a Bug] [answered]
### Describe the problem you are having

I'm currently running [0.14.0 Release Candidate 2](https://github.com/blakeblackshear/frigate/releases/tag/v0.14.0-rc2) with four cameras. First of all: Wow, thank you so much for the huge leap forward in the UI!
I've been noticing two issues:
a) When recording, detection and snapshots are disabled for a camera through the HA integration the icons in the new frontend still show those options as active. When I disable them in the new frontend, close the browser tab and open it up again the icons are enabled again (detection / events are still disabled).
b) When recordings are disabled the low res preview stream is still recorded, so recording is not really disabled. Is this by design? It could be a privacy issue for some (and I guess my wife would also disapprove of the indoor cam recording the whole day, which is even worse than the legal issues).

### Steps to reproduce

Disable recording / detection / snapshots via the HA integration switches and go to the new frontend.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
(abbreviated)
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -use_wallclock_as_timestamps 1

go2rtc:
  streams:
    gartenseite:
      - rtsp://...@192.168.1.63:554/Streaming/Channels/101/
    gartenseite_sub:
      - rtsp://...@192.168.1.63:554/Streaming/Channels/102/
    gartenende:
      - ffmpeg:gartenseite#video=h264#raw=-vf crop=1280:720:2580:0
    eingang:
      - rtsp://...@192.168.1.65/axis-media/media.amp?streamprofile=full264&camera=2
    eingang_sub:
      - rtsp://...@192.168.1.65/axis-media/media.amp?streamprofile=detect&camera=2
    klingel_ipad:
      - rtsp://...@192.168.1.65/axis-media/media.amp?camera=3
    innen:
      - rtsp://...@192.168.1.36:88/videoMain
mqtt:
  host: 192.168.1.222
  user: ...
  password: ...

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@192.168.1.64:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
      fps: 5
      stationary:
      # Optional: Frequency for confirming stationary objects (default: shown below)
      # When set to 0, object detection will not confirm stationary objects until movement is detected.
      # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 10
        max_frames:
          objects:
            person: 300
    motion:
      mask:
        - 636,162,1833,278,2053,381,2131,0,0,0,0,535,350,291,451,272
    zones:
      rasen:
        coordinates: 2092,415,1866,273,819,182,563,314,1517,473,2059,529
      einfahrt:
        coordinates: 540,1296,1878,1296,2062,527,1515,471,613,291,89,657
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bear
      filters:
        bear:
          mask:
            - 2304,1296,2304,0,2071,0,2099,1296
            - 2137,0,0,0,0,172,2135,200
            - 0,448,0,1296,412,1296
            - 938,0,0,0,0,564
        car:
          mask:
            - 2304,1296,2304,0,2071,0,2099,1296
            - 0,1296,0,411,564,1296,316,1296
            - 1568,259,1898,601,1680,1296,742,1296,167,705,219,610,745,161
        cat:
          mask:
            - 2304,1296,2304,0,2071,0,2099,1296
            - 2137,0,0,0,0,172,2135,200
            - 0,448,0,1296,412,1296
            - 938,0,0,0,0,564
        dog:
          mask:
            - 2304,1296,2304,0,2071,0,2099,1296
            - 2137,0,0,0,0,172,2135,200
            - 0,448,0,1296,412,1296
            - 938,0,0,0,0,564
        person:
          min_area: 10000
          mask:
            - 526,296,587,79,764,0,0,0,0,581,74,581
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100

    review:
      alerts:
        required_zones:
          - einfahrt
          - rasen

    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 98

  innen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/innen
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      innen_all:
        coordinates: 0,0,1280,0,1280,720,0,720
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 90
    onvif:
      host: 192.168.1.36
      port: 888
      user: ...
      password: ...
    ui:
      order: 5

    motion:
      mask:
        - 0,0,233,0,235,32,0,30

  eingang:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/eingang
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/eingang_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        max_frames:
          objects:
            person: 300
    zones:
      treppe:
        coordinates: 1502,534,788,650,642,840,1461,925
      einfahrt:
        coordinates: 1462,129,1152,166,979,396,1461,310
      klingel:
        coordinates: 1117,373,1560,175,1467,953,889,883
        objects:
          - person
      eingang_ext:
        coordinates: 1556,1080,1535,46,1155,98,385,1080
      eingang_all:
        coordinates: 1514,1080,1456,0,1063,0,0,984,0,1080
        objects:
          - car
          - cat
          - bear
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bear
      mask:
        - 826,0,0,0,0,652
      filters:
        bear:
          mask:
            - 1920,1080,1920,0,1487,0,1511,446,1515,1080
        car:
          mask:
            - 1920,1080,1920,0,1462,0,1485,321,1018,402,495,1080
            - 1268,74,1458,0,1471,246,1279,251
        cat:
          mask:
            - 1920,1080,1920,0,1487,0,1511,446,1515,1080
            - 950,657,776,635,948,407,1051,392
        dog:
          mask:
            - 1920,1080,1920,0,1487,0,1511,446,1515,1080
            - 960,671,994,462,895,482,847,560,791,654
        person:
          mask:
            - 1053,169,1168,115,1182,0,0,0,0,1080,135,1080
    motion:
      mask:
        - 0,0,0.508,0,0.224,0.481,0,0.77
        - 0.316,0.809,0.293,0.856,0.311,0.887,0.341,0.904,0.364,0.895,0.383,0.83,0.372,0.806,0.342,0.776
        - 1,1,0.848,1,0.851,0,1,0
        - 0.236,1,0,0.837,0,1
        - 0.629,1,0.636,0.844,0.499,0.799,0.442,1
        - 0.51,0.55,0.521,0.368,0.578,0.263,0.684,0.237,0.713,0.377,0.69,0.55,0.597,0.556
        - 0.084,1,0.015,0.917,0,0.768,0.055,0.671,0.068,0.775,0.081,0.837,0.096,0.727,0.13,0.735,0.132,0.798,0.15,0.81,0.153,0.839,0.192,0.845,0.224,0.862,0.228,0.931,0.255,1
        - 0.378,1,0.355,0.931,0.28,0.94,0.269,1
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100

    review:
      alerts:
        required_zones:
          - einfahrt
          - treppe
          - klingel
detectors:
  coral:
    type: edgetpu
    device: usb


record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 8
      objects:
        person: 15
snapshots:
  enabled: true
  bounding_box: true
  crop: true
  clean_copy: true
  retain:
    default: 8


database:
  path: /db/frigate.db

# Optional: birdseye configuration
birdseye:
  enabled: false
  width: 800
  height: 600
  quality: 20
  mode: continuous

telemetry:
  version_check: false

version: 0.14
```

### Relevant log output

```shell
2024-08-06 04:40:15.241827867  [2024-08-06 04:40:15] frigate.comms.dispatcher       INFO    : Turning off detection for innen
2024-08-06 04:40:15.285824845  [2024-08-06 04:40:15] frigate.comms.dispatcher       INFO    : Turning off recordings for innen
2024-08-06 04:40:15.286045145  [2024-08-06 04:40:15] frigate.comms.dispatcher       INFO    : Turning off snapshots for innen
2024-08-06 06:42:09.500890444  [2024-08-06 06:42:09] frigate.api.media              ERROR   : No recordings found for innen during the requested time range
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

various

### Any other information that may be helpful

The log shows recording etc. have been disabled by the integration as expected.
The last log line was created when i scrubbed through the preview recording of the disabled camera
