### DISCUSSION TITLE
[Detector Support]:  Detecting Barking Dog Audio

### DISCUSSION THREAD

**Discussion by moogoos** [blakeblackshear/frigate#12775] [Detector Support]
### Describe the problem you are having

Not getting events for barking dog. I have 8 cameras all similar. I have a very annoying yapping dog with one of my neighbors. For some reason bark doesn't pick up the yapper or their other dog which is a more typical lower tone bark. My front camera picked up a couple dogs barking more traditionally. How can I figure out why it's missing these pickups? It feels like the dogs pitch perhaps and yaps isn't getting detected by "bark"?

I tried recently adding the min_volume and filters for bark and threshhold for the yapper yapped and it didn't get picked up by the events filter in history.

### Version

.14 RC2

### Frigate config file

```yaml
backyard-center:
    live:
      stream_name: backyard-center_main
    ui:
      order: 8
    birdseye:
      order: 8
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard-center_main?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard-center_sub?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 200
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
      filters:
        bark:
          threshold: 0.7
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 90
          mode: motion
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

**Comment by NickM-27** [comment]
dog bark seems to be fairly picky, my dog only gets detected by it sometimes while barking. You may get more information by enabling debug logs for `frigate.events.audio`

**Reply by moogoos** [reply]
Cool. will give this a go:
```
logger:
  default: info
  logs:
    frigate.events.audio: debug
```
