### DISCUSSION TITLE
[Support]: Prefer Live view to use high-res video

### DISCUSSION THREAD

**Discussion by bonifacio123** [blakeblackshear/frigate#12795] [General Support] [answered]
### Describe the problem you are having

Hello, I'm using beta 2 of the version 0.14 - is there a way to enable the Live view to show the "record" stream (high res video) instead of the low res? Thank you

### Version

0.14.0-da913d8

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  
cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0  # Amcrest 4K @ 3840 x 2160 h264
          roles:
            - record
        - path: rtsp://xxx:yyy@192.168.1.201:554/cam/realmonitor?channel=1&subtype=1  # Amcrest 4K @ 704 x 480 h264
          roles:
            - detect
    record:
      enabled: true
    detect:
      enabled: false
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - deer

  patio:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.1.202:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:yyy@192.168.1.202:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: true

  back:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.1.203:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:yyy@192.168.1.203:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: true

  side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.1.204:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:yyy@192.168.1.204:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: true

snapshots:
  enabled: true
  bounding_box: true
  clean_copy: true
  retain:
    default: 10
    objects:
      person: 10

record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    retain:
      default: 10
      mode: motion

detect:
  enabled: true
  width: 704
  height: 480

detectors:
  deepstack:
    api_url: http://192.168.1.3:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.5 # seconds
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"cameras":{"back":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":450,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":457,"pid":428,"process_fps":4.7,"skipped_fps":0.0},"front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":437,"detection_enabled":true,"detection_fps":10.2,"ffmpeg_pid":477,"pid":419,"process_fps":3.4,"skipped_fps":1.4},"patio":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.9,"capture_pid":444,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":453,"pid":424,"process_fps":4.6,"skipped_fps":0.1},"side":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.2,"capture_pid":456,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":474,"pid":431,"process_fps":5.1,"skipped_fps":0.1}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"0.8","cpu_average":"1","mem":"0.4"},"125":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"159":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"165":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"296":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"373":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"375":{"cmdline":"frigate.recording_manager","cpu":"1.0","cpu_average":"1","mem":"0.3"},"384":{"cmdline":"frigate.review_segment_manager","cpu":"0.2","cpu_average":"0","mem":"0.2"},"402":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"403":{"cmdline":"frigate.detector.deepstack","cpu":"1.4","cpu_average":"0","mem":"0.2"},"405":{"cmdline":"frigate.output       ","cpu":"2.1","cpu_average":"1","mem":"0.2"},"419":{"cmdline":"frigate.process:front","cpu":"5.7","cpu_average":"2","mem":"0.2"},"424":{"cmdline":"frigate.process:patio","cpu":"0.4","cpu_average":"0","mem":"0.2"},"428":{"cmdline":"frigate.process:back ","cpu":"0.5","cpu_average":"0","mem":"0.2"},"431":{"cmdline":"frigate.process:side ","cpu":"0.5","cpu_average":"0","mem":"0.2"},"437":{"cmdline":"frigate.capture:front","cpu":"0.3","cpu_average":"0","mem":"0.2"},"444":{"cmdline":"frigate.capture:patio","cpu":"0.2","cpu_average":"0","mem":"0.2"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"450":{"cmdline":"frigate.capture:back ","cpu":"0.2","cpu_average":"0","mem":"0.2"},"4501":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"453":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.202:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.4","cpu_average":"0","mem":"0.1"},"456":{"cmdline":"frigate.capture:side ","cpu":"0.2","cpu_average":"0","mem":"0.2"},"457":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.203:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.3","cpu_average":"0","mem":"0.1"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"473":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.202:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/patio@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.0"},"474":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.204:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.3","cpu_average":"0","mem":"0.1"},"476":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.203:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.0"},"477":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.201:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.5","cpu_average":"0","mem":"0.1"},"482":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.204:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.0"},"483":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"498":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"503":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"508":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"513":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"5172":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"518":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"5241":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"2.9","mem":"25.1"}},"detection_fps":10.2,"detectors":{"deepstack":{"detection_start":1722963690.314183,"inference_speed":40.9,"pid":403}},"gpu_usages":{"intel-vaapi":{"gpu":"6.58%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":373},"recording":{"pid":375},"review_segment":{"pid":384}},"service":{"last_updated":1722963690,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":773.6,"mount_type":"tmpfs","total":777.0,"used":3.4},"/media/frigate/clips":{"free":5022753.4,"mount_type":"ext4","total":7569069.4,"used":2164782.6},"/media/frigate/recordings":{"free":5022753.4,"mount_type":"ext4","total":7569069.4,"used":2164782.6},"/tmp/cache":{"free":940.3,"mount_type":"tmpfs","total":953.7,"used":13.4}},"temperatures":{},"uptime":553,"version":"0.14.0-da913d8"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Other

### Network connection

Wired

### Camera make and model

Amcrest 4K IP8M-2796EW-AI
