### DISCUSSION TITLE
[Support]: Timezone off in the container

### DISCUSSION THREAD

**Discussion by darmach** [blakeblackshear/frigate#12796] [Config Support] [answered]
### Describe the problem you are having

Debian Bookworkm, timedatectl:
```
darmach@frigate:~$ timedatectl
               Local time: Tue 2024-08-06 22:44:09 CEST
           Universal time: Tue 2024-08-06 20:44:09 UTC
                 RTC time: Tue 2024-08-06 20:44:09
                Time zone: Europe/Warsaw (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

Frigate:
1. Review page - thumbnail lower right corner and on timeline - proper time, but 12 hour format
2. Settings > Debug - enabled timestamp - wrong time (2 hours short, seem to show UTC), proper format (24h)
3. System Logs - same as above, nice 24h same as OS locale, but -2h to local TZ, seem to use UTC.
4. Exports - both on export gallery, and single export popu - same as bove, properly 24h, but not applying TZ/using UTC

It's a bit annoying, am I doing something wrong, or should it use OS locale/TZ out of the box?

### Steps to reproduce

1. deployed clean os, debian vm on proxmox
2. deployed clean frigate: https://github.com/darmach/frigate-ansible/tree/master/template (config changed as pulled 0.14 rc1)

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxxxx
  user: xxxxxx
  password: xxxxxx

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  enabled: true
  fps: 10

objects:
  track:
    - person
    # - cat
    # - bird
    # - dog
    # - car

record:
  enabled: true

birdseye:
  enabled: true
  mode: continuous
  width: 2560
  height: 1440
  quality: 1

snapshots:
  enabled: true
  bounding_box: true

go2rtc:
  streams:
    cam1:
      - rtsp://192.168.1.101:554/live0.264
    cam2:
      - rtsp://192.168.1.102:554/live0.264
    cam3:
      - rtsp://192.168.1.103:554/live0.264
    cam4:
      - rtsp://192.168.1.104:554/live0.264

# Optional: jsmpeg stream configuration for WebUI
live:
  height: 1080
  quality: 1

cameras:
  cam1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
  cam2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
      threshold: 30
      contour_area: 31
      improve_contrast: 'false'
    zones:
      Parcel:
        coordinates: 0,0.362,0.844,0.438,0.999,0.689,0.999,0.846,0.92,0.998,0,0.998
        loitering_time: 0
      Street:
        coordinates: 0,0.358,0.845,0.428,0.873,0.333,0.433,0.214,0,0.168
        loitering_time: 0
      Sidewalk:
        coordinates: 0,0,0.573,0,1,0.265,0.975,0.392,0.876,0.345,0.877,0.325,0.43,0.202,0.003,0.16
        loitering_time: 0
    review:
      alerts:
        required_zones: Parcel
  cam3:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 0.75,0,1,0,1,0.059,0.75,0.059
        - 0.619,0.078,0.615,0.096,0.63,0.096,0.631,0.077
    zones:
      Backyard:
        coordinates: 
          0.052,0.463,0.186,0.4,0.267,0.42,0.924,0.461,1,0.636,1,1,0.114,1,0.054,0.778,0.015,0.509
        loitering_time: 0
      Tomek:
        coordinates: 
          0.253,0.362,0.476,0.297,0.476,0.216,0.513,0.101,0.781,0.105,0.796,0.23,0.789,0.317,0.834,0.323,0.924,0.457,0.286,0.402
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Backyard
          - Tomek
  cam4:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
version: 0.14
```

### Relevant log output

```shell
info
2024-08-06 21:01:44
frigate.app
Camera processor started for cam4: 556
info
2024-08-06 21:01:44
frigate.app
Capture process started for cam1: 561
info
2024-08-06 21:01:44
frigate.app
Capture process started for cam2: 567
info
2024-08-06 21:01:44
frigate.app
Capture process started for cam3: 576
info
2024-08-06 21:01:44
frigate.app
Capture process started for cam4: 584

(it's 23:01 CEST, in OS:
darmach@frigate:~$ timedatectl
               Local time: Tue 2024-08-06 23:03:48 CEST
           Universal time: Tue 2024-08-06 21:03:48 UTC
                 RTC time: Tue 2024-08-06 21:03:48
                Time zone: Europe/Warsaw (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
darmach@frigate:~$ date
Tue  6 Aug 23:03:49 CEST 2024
)
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

not related

### Any other information that may be helpful

Tried in chrome and safari, macos and windows 11, all set to CEST.
