### DISCUSSION TITLE
[Config Support]: Black Output from Cameras

### DISCUSSION THREAD

**Discussion by DanGarion** [blakeblackshear/frigate#12800] [Config Support] [answered]
### Describe the problem you are having

Hello, I was starting to try and figure out how to add audio recording with one of my cameras (that was already fully functional with my config below). But now it appears my config is broken. I'm getting black screens for both of my cameras. I can access both of them outside of Frigate and they both appear functional.

The only parts of the config that I attempted to tweak were adding output_args to ffmpeg in reardoor as well as trying to add it to the ffmpeg down near the end (not at the same time) I've removed what I had added but now I'm stuck with both of my camera's not working.

I'm unsure what I broke that is now making the config not work at all. It passes the check and Frigate does not appear to be throwing up any errors.

### Version

0.14.0-rc1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: core-mosquitto
  user: mqtt
  password: XXXXX
cameras:
  frontdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.1.42:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@192.168.1.42:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
    mqtt:
      height: 480
      quality: 85
  reardoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.1.41:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@192.168.1.41:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
    mqtt:
      height: 480
      quality: 85
detectors:
  coral:
    type: edgetpu
    device: pci
objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
    - face
#    - amazon
#    - fedex
#    - ups
record:
  enabled: true
  retain:
    days: 10
    mode: motion
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    retain:
      default: 15
      mode: active_objects
      objects:
        person: 30
        car: 30
# Optional: set environment variables
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 480
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 30
      car: 30
# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # Optional: output args for rtmp streams (default: shown below)
database:
  path: /config/frigate.db

version: 0.14
```

### Relevant log output

```shell
2024-08-06 22:06:24.607754904  [2024-08-06 15:06:24] frigate.app                    INFO    : Starting Frigate (0.14.0-7c39b17)
2024-08-06 22:06:24.608113085  [2024-08-06 15:06:24] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-08-06 22:06:24.609629131  [2024-08-06 15:06:24] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-08-06 22:06:24.730610124  [2024-08-06 15:06:24] frigate.util.config            INFO    : frigate config does not need migration...
2024-08-06 22:06:24.914942131  [2024-08-06 15:06:24] peewee_migrate.logs            INFO    : Starting migrations
2024-08-06 22:06:24.918836520  [2024-08-06 15:06:24] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-06 22:06:24.944741414  [2024-08-06 15:06:24] frigate.app                    INFO    : Recording process started: 361
2024-08-06 22:06:24.961792026  [2024-08-06 15:06:24] frigate.app                    INFO    : Recording process started: 366
2024-08-06 22:06:24.974515050  [2024-08-06 15:06:24] frigate.app                    INFO    : go2rtc process pid: 97
2024-08-06 22:06:25.099465195  [2024-08-06 15:06:25] detector.coral                 INFO    : Starting detection process: 390
2024-08-06 22:06:25.191056129  [2024-08-06 15:06:25] frigate.app                    INFO    : Output process started: 392
2024-08-06 22:06:25.198627893  [2024-08-06 15:06:25] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-08-06 22:06:25.200807974  [2024-08-06 15:06:25] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-08-06 22:06:25.526942944  [2024-08-06 15:06:25] frigate.app                    INFO    : Camera processor started for frontdoor: 420
2024-08-06 22:06:25.548332345  [2024-08-06 15:06:25] frigate.app                    INFO    : Camera processor started for reardoor: 423
2024-08-06 22:06:25.571059367  [2024-08-06 15:06:25] frigate.app                    INFO    : Capture process started for frontdoor: 429
2024-08-06 22:06:25.612869548  [2024-08-06 15:06:25] frigate.app                    INFO    : Capture process started for reardoor: 434
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

**Comment by hawkeye217** [comment]
You shouldn't copy the reference config and you should be using ffmpeg presets, not manual arguments:

https://docs.frigate.video/configuration/ffmpeg_presets

**Reply by hawkeye217** [reply, marked as answer]
Replace the entire `ffmpeg:` section with:

```
ffmpeg:
  hwaccel_args: preset-vaapi
```

That should be all you need.

**Reply by DanGarion** [reply]
I will check your suggestions. Granted this has all been configured for 2 years. Added the new camera last week and after a week of no issues decided to tackle audio (since the new camera has a mic). It is strange why this would pop up suddenly. I will also completely reboot the HA server in case something stupid is going on there. 

Things are back up and working. I guess I will start from scratch again on the audio and see if I can get it to work for the camera that has it.

**Comment by DanGarion** [comment]
One more question as I try and tackle getting audio "detection" working. I am able to get audio working itself but are my detect settings correct?

```
mqtt:
  enabled: true
  host: core-mosquitto
  user: mqtt
  password: XX
cameras:
  frontdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@192.168.1.42:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://XX:XX@192.168.1.42:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
    mqtt:
      height: 480
      quality: 85
  reardoor:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://XX:XX@192.168.1.41:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - audio
        - path: rtsp://XX:XX@192.168.1.41:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    mqtt:
      height: 480
      quality: 85
detectors:
  coral:
    type: edgetpu
    device: pci
objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
    - face
#    - amazon
#    - fedex
#    - ups
record:
  enabled: true
  retain:
    days: 10
    mode: motion
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    retain:
      default: 15
      mode: active_objects
      objects:
        person: 30
        car: 30
# Optional: set environment variables
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 480
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 30
      car: 30
# Optional: ffmpeg configuration
ffmpeg:
  hwaccel_args: preset-vaapi
database:
  path: /config/frigate.db

version: 0.14
```
