### DISCUSSION TITLE
[Camera Support]: Reolink E1 Outdoor record ffmpeg options for h264 transcode

### DISCUSSION THREAD

**Discussion by stratus-ss** [blakeblackshear/frigate#12818] [Camera Support] [answered]
### Describe the problem you are having

I am using the docker compose on hardware 

In the below config I have 2 different camera models the Trackmix and the E1 Outdoor POE. The Trackmix take the ffmpeg output_args just fine as does a _single_ one of my E1 Outdoor POE cameras. It has a slightly different firmware version than the rest

problem camera firmware: **v3.1.0.3398_2404031842**
working camera firmware: **v3.1.0.2448_23071200**

When attempting to use any output arguments for ffmpeg on these problem cameras I get reams of errors. All these cameras have only an H265 stream which does not play back in the web browser. 

I can omit the output_args and this will use the GPU as expected. However I want to store these files in H264 for viewing in the web ui.

I have tried with and without using the `go2rtc` streams. If I am approaching this wrong I am happy to be corrected

### Version

System 0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.1
  user: mqtt-user
  password: password
record:
    sync_recordings: True
    enabled: True
    retain:
      days: 5
      mode: all
    events:
      retain:
        default: 30
        mode: motion
go2rtc:
  streams:
    garage:
      - rtsp://username:password@garage-reolink.example.com:554/h264Preview_01_main

database:
  path: /media/frigate/config/db/frigate.db
ffmpeg:
  hwaccel_args: preset-nvidia-h264
cameras:
  doorbell: # <--- this will be changed to your actual camera later
    enabled: True
    detect: 
        enabled: False
    ffmpeg:
        inputs:
            - path: rtsp://username:password@doorbell.example.com:554/h264Preview_01_main
              roles:
                - record

  chicken_outside: # <--- WORKING E1 Outdoor
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        output_args:
          record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5
        inputs:
            - path: rtsp://username:password@outside-coop.example.com:554/h264Preview_01_main
              roles:
                - record
  
  chicken_inside: # <--- not working E1 Outdoor
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        inputs:
            - path: rtsp://username:password@chicken.example.com:554/h264Preview_01_main
              roles:
                - record

  garage: # <--- not working E1 Outdoor
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        output_args:
          record:  -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5
        inputs:
            - path: rtsp://127.0.0.1:8554/garage
              roles:
                - record
              input_args: preset-rtsp-restream

  backyard: # 
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        output_args:
            record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5
        inputs:
            - path: rtsp://username:password@backyard-camera.example.com:554/h264Preview_01_main
              roles:
                - record

  driveway: # <--- this will be changed to your actual camera later
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        output_args:
            record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5
        inputs:
            - path: rtsp://username:password@driveway-reolink.example.com:554/h264Preview_01_main
              roles:
                - record
```

### Relevant log output

```shell
2024-08-07 17:13:01.455098399  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-08-07 17:13:01.455303402  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-08-07 17:13:01.455385074  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-08-07 17:13:01.455571792  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-08-07 17:13:01.455761816  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-08-07 17:13:01.455878444  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-08-07 17:13:01.456626028  [2024-08-07 17:13:01] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2024-08-07 17:13:02.710562439  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f2998185f80] moov atom not found
2024-08-07 17:13:02.710640805  [ERROR:0@442.935] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-08-07 17:13:02.710642297  
2024-08-07 17:13:02.710644091  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-08-07 17:13:02.710645083  
2024-08-07 17:13:02.710645954  
2024-08-07 17:13:02.730966292  [2024-08-07 17:13:02] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/garage@20240807171255-0500.mp4
2024-08-07 17:13:02.731031303  [2024-08-07 17:13:02] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/garage@20240807171255-0500.mp4
2024-08-07 17:13:03.375289095  [2024-08-07 17:13:03] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
2024-08-07 17:13:03.375400393  [2024-08-07 17:13:03] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-08-07 17:13:03.375472107  [2024-08-07 17:13:03] ffmpeg.garage.detect           ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'
2024-08-07 17:13:03.375535485  [2024-08-07 17:13:03] ffmpeg.garage.detect           ERROR   : Error reinitializing filters!
2024-08-07 17:13:03.375597160  [2024-08-07 17:13:03] ffmpeg.garage.detect           ERROR   : Failed to inject frame into filter network: Function not implemented
2024-08-07 17:13:03.375656981  [2024-08-07 17:13:03] ffmpeg.garage.detect           ERROR   : Error while processing the decoded data for stream #0:0
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 3840x2160
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":936,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":943,"pid":897,"process_fps":5.1,"skipped_fps":0.0},"chicken_inside":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":925,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":932,"pid":893,"process_fps":5.0,"skipped_fps":0.0},"chicken_outside":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":920,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":926,"pid":892,"process_fps":5.1,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":916,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":921,"pid":890,"process_fps":5.0,"skipped_fps":0.0},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":941,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":947,"pid":914,"process_fps":5.1,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":2.46,"capture_pid":931,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":9448,"pid":895,"process_fps":0.9,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"39":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"48":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"49":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"50":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"51":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"52":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"53":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"54":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"55":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"56":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"65":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"66":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"104":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"105":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"113":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"2.8","cpu_average":"1","mem":"0.0"},"121":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"122":{"cmdline":"python3 -u -m frigate","cpu":"47.6","cpu_average":"5","mem":"1.3"},"133":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"169":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"170":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"171":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"172":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"183":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"208":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"253":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"300":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"331":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"369":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"406":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"446":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"472":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"499":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"527":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"568":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"613":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"753":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"869":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"2","mem":"0.3"},"878":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(59)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"879":{"cmdline":"frigate.detector.cpu ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"881":{"cmdline":"frigate.output       ","cpu":"7.9","cpu_average":"7","mem":"0.2"},"884":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"885":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"886":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"887":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"888":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"890":{"cmdline":"frigate.process:doorbell","cpu":"1.4","cpu_average":"0","mem":"0.3"},"891":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"892":{"cmdline":"frigate.process:chicken_outside","cpu":"1.4","cpu_average":"1","mem":"0.3"},"893":{"cmdline":"frigate.process:chicken_inside","cpu":"1.9","cpu_average":"1","mem":"0.3"},"895":{"cmdline":"frigate.process:garage","cpu":"0.9","cpu_average":"0","mem":"0.3"},"896":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"897":{"cmdline":"frigate.process:backyard","cpu":"1.4","cpu_average":"1","mem":"0.3"},"914":{"cmdline":"frigate.process:driveway","cpu":"1.4","cpu_average":"1","mem":"0.3"},"916":{"cmdline":"frigate.capture:doorbell","cpu":"6.5","cpu_average":"6","mem":"0.3"},"920":{"cmdline":"frigate.capture:chicken_outside","cpu":"11.2","cpu_average":"10","mem":"0.3"},"921":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@doorbell.x86experts.com:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.0","cpu_average":"7","mem":"0.6"},"925":{"cmdline":"frigate.capture:chicken_inside","cpu":"11.7","cpu_average":"10","mem":"0.3"},"926":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@outside-coop.x86experts.com:554/h264Preview_01_main -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5 /tmp/cache/chicken_outside@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"12.6","cpu_average":"11","mem":"0.8"},"931":{"cmdline":"frigate.capture:garage","cpu":"8.4","cpu_average":"6","mem":"0.3"},"932":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@chicken.x86experts.com:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/chicken_inside@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"14.9","cpu_average":"16","mem":"0.7"},"936":{"cmdline":"frigate.capture:backyard","cpu":"10.7","cpu_average":"9","mem":"0.3"},"941":{"cmdline":"frigate.capture:driveway","cpu":"10.3","cpu_average":"10","mem":"0.3"},"943":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@backyard-camera.x86experts.com:554/h264Preview_01_main -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5 /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.2","cpu_average":"11","mem":"0.8"},"947":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@driveway-reolink.x86experts.com:554/h264Preview_01_main -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5 /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.2","cpu_average":"10","mem":"0.8"},"9447":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"9448":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5 /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"19.6","cpu_average":"0","mem":"0.6"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":879}},"gpu_usages":{"NVIDIA GeForce GTX 1060 3GB":{"dec":"62.0%","enc":"6.0%","gpu":"6.0%","mem":"84.91%"}},"processes":{"go2rtc":{"pid":113},"logger":{"pid":753},"recording":{"pid":869}},"service":{"last_updated":1723068896,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":955.2,"mount_type":"tmpfs","total":1024.0,"used":68.8},"/media/frigate/clips":{"free":7582519.0,"mount_type":"nfs4","total":13474970.0,"used":5892451.0},"/media/frigate/recordings":{"free":7582519.0,"mount_type":"nfs4","total":13474970.0,"used":5892451.0},"/tmp/cache":{"free":16305.0,"mount_type":"tmpfs","total":16384.0,"used":79.0}},"temperatures":{},"uptime":544,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink TrackMix, E1 Outdoor POE

**Comment by NickM-27** [comment]
I would definitely suggest using go2rtc for transcoding

**Reply by stratus-ss** [reply]
can you provide an example that I might follow please?

**Reply by NickM-27** [reply]
```
go2rtc:
  streams:
    camera:
      - "ffmpeg:rtsp://...#video=h264#audio=copy#hardware"
```

**Reply by stratus-ss** [reply]
I am attempting to use this method but I want to put a warning out there to other people. I paired my config down to a single camera and I started seeing this error

```
frigate1  | 2024-08-07 19:52:17.740676905  19:52:17.740 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:rtsp://<user>:<password>@garage-reolink.example.com:554/h264Preview_01_main#video=h264#audio=copy#hardware
```

Within less than a minute Frigate container had burned through all 64G of ram plust 24G of swap and crashed my box. This happened repeatedly. I had to have a second window open to kill the container

For the record I paired this down to

```
mqtt:
  enabled: True
  host: 192.168.1.1
  user: mqtt-user
  password: password
record:
    sync_recordings: True
    enabled: True
    retain:
      days: 5
      mode: all
    events:
      retain:
        default: 30
        mode: motion
go2rtc:
  streams:
    garage:
      - "ffmpeg:rtsp://<user>:<password>@garage-reolink.example.com:554/h264Preview_01_main#video=h264#audio=copy#hardware"


database:
  path: /media/frigate/config/db/frigate.db
ffmpeg:
  hwaccel_args: preset-nvidia-h264
cameras:
  garage: 
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        inputs:
            - path: rtsp://127.0.0.1:8554/garage
              roles:
                - record
              input_args: preset-rtsp-restream
```

I will try some variations in the go2rtc sections of the docs and report back

**Reply by stratus-ss** [reply]
When I change the go2rtc to look like this
```
go2rtc:
  streams:
    garage:
      - "rtsp://<user>:<password>@garage-reolink.example.com.com:554/h264Preview_01_main"
      - "ffmpeg:garage#video=h264#audio=copy#hardware"
```

The preview window in Frigate is blank and if I look at the files on disk they appear to be h265 still:

```
ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 2024-08-08/01/garage/00.24.mp4 
hevc
```

**Reply by stratus-ss** [reply]
I found that the problem with the system eating all the ram is directly related to adding `#hardware`. When I remove it, the transcoding works (albeit with cpu and not the gpu) and the system doesn't crash

**Reply by NickM-27** [reply]
you may want to specify `#hardware=cuda`

**Reply by stratus-ss** [reply]
so that prevented the crash/memory leak but the problem is no recording is happening
```
frigate1  | 2024-08-07 20:51:13.683749206  20:51:13.683 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:rtsp://<user>:<password>@garage-reolink.example.com:554/h264Preview_01_main#video=h264#hardware=cuda
frigate1  | 2024-08-07 20:51:14.560032966  [2024-08-07 20:51:14] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
frigate1  | 2024-08-07 20:51:14.560120680  [2024-08-07 20:51:14] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
frigate1  | 2024-08-07 20:51:25.708449744  [2024-08-07 20:51:25] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
frigate1  | 2024-08-07 20:51:25.708518062  [2024-08-07 20:51:25] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate1  | 2024-08-07 20:51:25.708597870  [2024-08-07 20:51:25] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x5652b94a8040] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate1  | 2024-08-07 20:51:25.708661980  [2024-08-07 20:51:25] ffmpeg.garage.detect           ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate1  | 2024-08-07 20:51:25.708717814  [2024-08-07 20:51:25] ffmpeg.garage.detect           ERROR   : Output file #0 does not contain any stream
```

**Reply by stratus-ss** [reply]
should i be using an exec here to specify the full ffmpeg command i wonder?

**Reply by NickM-27** [reply]
Should be fine with ffmpeg, no idea why the steam would fail to record. Are you able to watch the live view, what is your current config

**Reply by stratus-ss** [reply]
This is the full stripped down config (as in I removed everything else)

```
mqtt:
  enabled: True
  host: 192.168.1.1
  user: mqtt-user
  password: password
record:
    sync_recordings: True
    enabled: True
    retain:
      days: 5
      mode: all
    events:
      retain:
        default: 30
        mode: motion
go2rtc:
  streams:
    garage:
      - "ffmpeg:rtsp://<user>:<password>@garage-reolink.example.com:554/h264Preview_01_main#video=h264#hardware=cuda"

database:
  path: /media/frigate/config/db/frigate.db
ffmpeg:
  hwaccel_args: preset-nvidia-h264
cameras:
  garage: 
    enabled: True
    record:
      retain:
        days: 2
    detect: 
        enabled: False
    ffmpeg:
        inputs:
            - path: rtsp://127.0.0.1:8554/garage
              roles:
                - record
              input_args: preset-rtsp-restream
```

Just for an interesting reference when I use the above with docker compose this is what happens about 70s after I run the `docker compose up` command

![image](https://github.com/user-attachments/assets/c1aeedb9-e341-401b-b742-11082d1abe66)

Then I have to kill it before it murders the machine. For reference the box without this docker compose running looks like this before launching

```
               total        used        free      shared  buff/cache   available
Mem:           63698       12640       49106          17        2604       51057
Swap:          24419           5       24414
```


Here is the compose file if that makes a difference

```
version: "3.9"
services:
  frigate:
    container_name: frigate1
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    runtime: nvidia
    mem_limit: 16384m
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    shm_size: "1024mb" # update for your cameras based on calculation
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/frigate/config/frigate.yaml:/config/config.yml # modify to match your setup
      - /media/frigate:/media/frigate # modify to match your setup
      - /media/frigate/config/db:/db # modify to match your setup
      - /tmp:/tmp/cache
    ports:
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "password" 
```

**Reply by NickM-27** [reply]
Well, we just released a new version of Frigate which is a major update, but it also includes a newer version of go2rtc which might have this issue fixed

**Reply by stratus-ss** [reply, marked as answer]
so I updated the docker compose file to indicate the image 0.14.0 which seems to be the latest non-dev release.

I love the new interface!

However I'm still getting these problems with go23rtc

```
WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:rtsp://<user>:<password>@garage-reolink.example.com:554/h264Preview_01_main#video=h264#audio=copy#hardware=cuda
```

And it causes that memory problem.

If I remove the `#hardware=cuda` from the go2rtc line it works but uses the cpu. It seems odd that the other streams work and 2 don't.

I did make some progress with the new version.

If I change the stream from `h264Preview_01_Main` to `h264Preview_01_Sub` with the latest 0.14.0 release it seems to do what I want! I can see previews and I can scrub through them in the webui. I can get at the history and I don't have a massive memory leak. I had to remove `=cuda` however to get this to work. Full "working" config below

```
mqtt:
  enabled: true
  host: 192.168.1.1
  user: mqtt-user
  password: password
record:
  sync_recordings: true
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    retain:
      default: 30
      mode: motion
go2rtc:
  streams:
    garage:
      - ffmpeg:rtsp://<user>:<password>@garage-reolink.example.com:554/h264Preview_01_sub#video=h264#audio=copy#hardware

database:
  path: /media/frigate/config/db/frigate.db
ffmpeg:
  hwaccel_args: preset-nvidia-h264
cameras:

  garage: # <--- this will be changed to your actual camera later
    enabled: true
    record:
      retain:
        days: 2
    detect:
      enabled: false
    ffmpeg:
        # output_args:
        #   record:  -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -preset fast -b:v 4M -r 5
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - record
          input_args: preset-rtsp-restream
```
