### DISCUSSION TITLE
[Config Support]: Tweaks for accessing web UI over low bandwidth connection

### DISCUSSION THREAD

**Discussion by mike2307** [blakeblackshear/frigate#12816] [Config Support]
### Describe the problem you are having

Even if I like the look and feel of the new frigate version 0.14, it feels a bit more heavy in terms of bandwidth and loading times.
Of course when watching some recordings in solely depends on some configuration settings regarding the recordings themselves but I'm referring to the web UI, even when no recordings are being viewed (e.g. just checking the most recent events).

With version 0.13 the web UI was quite sleek and fast.

Are there some specific settings in the config and/or web UI to make the web UI more usable/fast when accessing it via a low bandwidth connection?
Are there any plans on continuing to support version 0.13?

Thanks a lot in advance.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: false

tls:
  enabled: false

birdseye:
  enabled: true
  restream: false
  mode: continuous
  width: 1280
  height: 720
  layout:
    scaling_factor: 1.0

camera_groups:
  Birdseye:
    order: 1
    icon: LuAirplay
    cameras: birdseye

ui:
  date_style: medium

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  openvino:
    type: openvino
    device: GPU

model:
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  width: 300
  height: 300
  input_pixel_format: bgr
  input_tensor: nhwc
  model_type: ssd

detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5

record:
  enabled: true
  retain:
    days: 42
    mode: all
  export:
    # fits 1 hour into 1 minute (1/60), 15 FPS
    timelapse_args: -vf setpts=PTS/60 -r 15 -qp 36
  events:
    retain:
      default: 365
      mode: active_objects
  sync_recordings: true

snapshots:
  enabled: true
  retain:
    default: 1000

go2rtc:
  streams:
    Cam_HQ:
      - rtsp://:#####@:#####@10.42.0.2:554/cam/realmonitor?channel=1&subtype=0
    Cam_LQ:
      - ffmpeg:Cam_HQ#video=h264#width=1280#audio=copy#hardware=vaapi#raw=-r 15 -qp
        36
      - ffmpeg:Cam_LQ#audio=opus # for WebRTC audio

cameras:
  Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam_HQ
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: Cam_LQ

objects:
  track:
    - person
```

### Relevant log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

OpenVino
