### DISCUSSION TITLE
[Config Support]: Frigate Docker Container keep restarting

### DISCUSSION THREAD

**Discussion by leonbrag** [blakeblackshear/frigate#12819] [Config Support] [answered]
### Describe the problem you are having

 I followed https://docs.frigate.video/frigate/installation/ to install Frigate in Docker container on Debian 12.

When I start using `sudo docker compose up` command container is just restarting

I have verified that Frigate configuration worked when Frigate runs as HASS add-on.

What is going wrong?
Is there a specific logs to review error ?

logs:



### Version

latest released

### Frigate config file

```yaml
Docker Compose:

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation, more here docs.frigate.video/frigate/installation/#docker
#    devices:
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/wd/frigate_config/config:/config/ # frigate NVR config
      - /media/toshiba:/media/frigate # recordings & snapshot storage
      - /media/wd/frigate_config/db:/db # frigate database folder
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_MQTT_USER: "xxx"
      FRIGATE_MQTT_PASSWORD: "xxx" # CHANGE to your MQTT password for the frigate user that you created in earlier steps.


Frigate:

logger:
  default: info
  frigate.mqtt: error

mqtt:
  enabled: true
  host: hpdebian
  user: xxx
  password: xxx
  topic_prefix: frigate
  port: 1883
  
ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  fps: 5

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  
#go2rtc:
#  rtsp:
#    username: viewer
#    password: restream_password # !!! PLEASE CHANGE, this will be used to access restreamed cameras in Home Assistant.
#  streams:
#    Driveway_(g2): # example camera without audio
#    - rtsp://xxx:pass@192.168.10.11/Streaming/Channels/101
#    Front_Door_(g2): # example camera with audio
#    - rtsp://xxx:pass@192.168.10.13/Streaming/Channels/101
#
#
birdseye:
  enabled: True
  mode: continuous
  width: 1280
  height: 720

  
#go2rtc:
#  streams:
#    Driveway_R:
#      - ffmpeg:rtsp://xxx:pass@192.168.10.11/Streaming/Channels/102

cameras:
  Driveway: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.11/Streaming/Channels/102
          roles:
            - detect



  Front_Door: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.13/Streaming/Channels/102
          roles:
            - detect

  Back_Yard: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.22/Streaming/Channels/102
          roles:
            - detect

  Basement: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.14/Streaming/Channels/102
          roles:
            - detect

  Side_Yard: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.23/Streaming/Channels/102
          roles:
            - detect

  Garage: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.17/Streaming/Channels/102
          roles:
            - detect

  Bedroom: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:pass@192.168.10.10/Streaming/Channels/102
          roles:
            - detect
```


### Relevant log output

```shell
leonbrag@hpdebian:/media/wd/frigate_config$ sudo docker compose up
[+] Running 1/0
 ✔ Container frigate  Created                                                                                                                                                                                                                                                                                        0.0s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-08-07 16:33:14.204934841  [INFO] Preparing Frigate...
frigate  | 2024-08-07 16:33:14.205029654  [ERROR] Frigate config file not found
frigate  | 2024-08-07 16:33:14.208531093  [INFO] Starting NGINX...
frigate  | 2024-08-07 16:33:14.210476840  [INFO] Preparing new go2rtc config...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-08-07 16:33:14.212494348  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2024-08-07 16:33:14.222148160  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-08-07 16:33:14.223488392  [INFO] Service NGINX exited with code 256 (by signal 15)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2024-08-07 16:33:14.229196516  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```

```
CONTAINER ID   IMAGE                                                      COMMAND               CREATED          STATUS                         PORTS
                        NAMES
aaf56134213f   ghcr.io/blakeblackshear/frigate:stable                     "/init"               51 minutes ago   Restarting (1) 2 seconds ago
                        frigate


```
```


### Frigate stats

_No response_

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

### Any other information that may be helpful

_No response_
