### DISCUSSION TITLE
[Config Support]: Camera has alert: required zone, and still alerts are generated for detections outside of the zone

### DISCUSSION THREAD

**Discussion by darmach** [blakeblackshear/frigate#12826] [Config Support] [answered]
### Describe the problem you are having

`cam2` camera has added alerting zone:
```
  cam2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
      threshold: 30
      contour_area: 31
    zones:
      Parcel:
        coordinates: 0,0.398,0.86,0.448,0.878,0.376,1,0.424,0.999,0.846,0.92,0.998,0,0.998
        loitering_time: 0
        inertia: 3
      Street:
        coordinates: 0,0.358,0.845,0.428,0.868,0.345,0.68,0.279,0.389,0.207,0,0.168
        loitering_time: 0
        inertia: 3
      Sidewalk:
        coordinates: 0,0,0.573,0,1,0.265,0.981,0.382,0.797,0.305,0.61,0.253,0.43,0.202,0.003,0.16
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Parcel
```
Objects are defined before cameras:
```
objects:
  track:
    - person
    - cat
    - bird
    - dog
    - car
```

Despite camera having `required_zones: Parcel` in `review: alerts` I still get alerts to review for car/person detected way outside the 'parcel' zone. Full config attached below. Can it be caused by some other settings in my config?

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: XXXXXXX
  user: XXXXXXX
  password: XXXXXX

ui:
  time_format: 24hour

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  enabled: true
  fps: 10

# model:
#   path: /config/mobilenet_v2/1.tflite
#   labelmap_path: /config/mobilenet_v2/imagenet_labels.txt
#   width: 224
#   height: 224

objects:
  track:
    - person
    - cat
    - bird
    - dog
    - car

record:
  enabled: true
  retain:
    days: 2
    mode: active_objects
  # events:
  #   retain:
  #     default: 10
  #     mode: motion

birdseye:
  enabled: true
  mode: continuous
  width: 2560
  height: 1440
  quality: 1

snapshots:
  enabled: true
  bounding_box: true

go2rtc:
  streams:
    cam1:
      - rtsp://192.168.1.101:554/live0.264
    cam2:
      - rtsp://192.168.1.102:554/live0.264
    cam3:
      - rtsp://192.168.1.103:554/live0.264
    cam4:
      - rtsp://192.168.1.104:554/live0.264

# Optional: jsmpeg stream configuration for WebUI
live:
  height: 1080
  quality: 1

cameras:
  cam1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
  cam2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
      threshold: 30
      contour_area: 31
    zones:
      Parcel:
        coordinates: 0,0.398,0.86,0.448,0.878,0.376,1,0.424,0.999,0.846,0.92,0.998,0,0.998
        loitering_time: 0
        inertia: 3
      Street:
        coordinates: 0,0.358,0.845,0.428,0.868,0.345,0.68,0.279,0.389,0.207,0,0.168
        loitering_time: 0
        inertia: 3
      Sidewalk:
        coordinates: 0,0,0.573,0,1,0.265,0.981,0.382,0.797,0.305,0.61,0.253,0.43,0.202,0.003,0.16
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Parcel
  cam3:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
        - dog
        - bird
    motion:
      mask:
        - 0.75,0,1,0,1,0.059,0.75,0.059
        - 0.619,0.078,0.615,0.096,0.63,0.096,0.631,0.077
    zones:
      Backyard:
        coordinates:
          0.052,0.463,0.186,0.4,0.267,0.42,0.924,0.461,1,0.636,1,1,0.114,1,0.054,0.778,0.015,0.509
        loitering_time: 0
      Tomek:
        coordinates:
          0.253,0.362,0.476,0.297,0.476,0.216,0.513,0.101,0.781,0.105,0.796,0.23,0.789,0.317,0.834,0.323,0.924,0.457,0.286,0.402
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Backyard
          - Tomek
  cam4:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 1440,0,1920,0,1920,64,1440,64
version: 0.14
```

### Relevant log output

```shell
NA
```

### Frigate stats

```json
{"cameras":{"cam1":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":497,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":517,"pid":481,"process_fps":10.0,"skipped_fps":0.0},"cam2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":505,"detection_enabled":true,"detection_fps":22.9,"ffmpeg_pid":514,"pid":482,"process_fps":10.1,"skipped_fps":0.0},"cam3":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.2,"capture_pid":513,"detection_enabled":true,"detection_fps":7.5,"ffmpeg_pid":535,"pid":486,"process_fps":10.1,"skipped_fps":0.0},"cam4":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":518,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":536,"pid":489,"process_fps":10.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"python3 -u -m frigate","cpu":"3.6","cpu_average":"4","mem":"4.2"},"110":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"134":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"159":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"167":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24708":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24740":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"299":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"338":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.7"},"34":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"423":{"cmdline":"frigate.recording_manager","cpu":"1.9","cpu_average":"1","mem":"1.1"},"431":{"cmdline":"frigate.review_segment_manager","cpu":"0.8","cpu_average":"0","mem":"0.9"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"451":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.3","cpu_average":"0","mem":"0.1"},"452":{"cmdline":"frigate.detector.coral","cpu":"3.0","cpu_average":"1","mem":"1.0"},"454":{"cmdline":"frigate.output       ","cpu":"4.2","cpu_average":"4","mem":"1.1"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"481":{"cmdline":"frigate.process:cam1 ","cpu":"1.6","cpu_average":"1","mem":"1.0"},"482":{"cmdline":"frigate.process:cam2 ","cpu":"10.5","cpu_average":"7","mem":"1.2"},"486":{"cmdline":"frigate.process:cam3 ","cpu":"3.5","cpu_average":"3","mem":"1.2"},"489":{"cmdline":"frigate.process:cam4 ","cpu":"1.5","cpu_average":"1","mem":"1.2"},"497":{"cmdline":"frigate.capture:cam1 ","cpu":"4.7","cpu_average":"4","mem":"0.9"},"505":{"cmdline":"frigate.capture:cam2 ","cpu":"4.5","cpu_average":"4","mem":"0.9"},"513":{"cmdline":"frigate.capture:cam3 ","cpu":"4.5","cpu_average":"4","mem":"0.9"},"514":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-7c39b17 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/cam2@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.0","cpu_average":"5","mem":"0.8"},"517":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-7c39b17 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/cam1@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"4","mem":"0.8"},"518":{"cmdline":"frigate.capture:cam4 ","cpu":"4.4","cpu_average":"4","mem":"0.9"},"535":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-7c39b17 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam3 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/cam3@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"5","mem":"0.8"},"536":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-7c39b17 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam4 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/cam4@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.8","cpu_average":"4","mem":"0.8"},"539":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1920x1080 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"544":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1920x1080 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"549":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1920x1080 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"554":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1920x1080 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"559":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 2560x1440 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"664":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"95":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"7.9","cpu_average":"7","mem":"0.2"},"frigate.full_system":{"cpu":"20.4","mem":"16.0"}},"detection_fps":30.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.2,"pid":452}},"gpu_usages":{"amd-vaapi":{"gpu":"5.83%","mem":"88.83%"}},"processes":{"go2rtc":{"pid":95},"logger":{"pid":338},"recording":{"pid":423},"review_segment":{"pid":431}},"service":{"last_updated":1723120413,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":239.0,"mount_type":"tmpfs","total":256.0,"used":17.0},"/media/frigate/clips":{"free":29928.1,"mount_type":"ext4","total":51536.2,"used":19277.8},"/media/frigate/recordings":{"free":29928.1,"mount_type":"ext4","total":51536.2,"used":19277.8},"/tmp/cache":{"free":904.5,"mount_type":"tmpfs","total":953.7,"used":49.2}},"temperatures":{"apex_0":45.05},"uptime":7951,"version":"0.14.0-7c39b17"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
