### DISCUSSION TITLE
[Config Support]: Double detection within a short time

### DISCUSSION THREAD

**Discussion by 1990marco1990** [blakeblackshear/frigate#12837] [Config Support]
### Describe the problem you are having

I always have detections that are detected twice within a short period of time. For example, if there is a car in the yard, it will be recognized every few minutes and a new video will be created. How can I prevent this?

### Version

frigate:0.14.0-rc2

### Frigate config file

```yaml
mqtt:
  host: 192.168.31.243
  user: mqtt
  password: ****
  port: 1883

database:
  path: /media/frigate/frigate.db

detect:
  stationary:
    interval: 50
    threshold: 50
motion:
  threshold: 30
  contour_area: 10

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true

record:
  enabled: true
  retain:
    days: 5
    mode: all

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
birdseye:
  enabled: false

cameras:
  tuerklingel:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 500M
        - -probesize
        - 500M
        - -rw_timeout
        - '5000000'
      inputs:
        - path: 
            http://192.168.31.242/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***#video=copy#audio=copy#audio=opus
          roles:
            - record
            - rtmp
            - detect
    motion:
      mask:
        - 383,424,1280,420,1280,0,0,0,0,216,0,442
      improve_contrast: true
    detect:
      width: 1280
      height: 720
      fps: 15
      max_disappeared: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 20
        retain:
          default: 10
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 1000
          max_area: 100000
          threshold: 0.68
        car: {}
    zones:
      Home:
        coordinates: 1,1,0.985,0.624,0.721,0.586,0.68,0.556,0.299,0.574,0,0.599,0,1
        objects:
          - car
          - person
        inertia: 3
        loitering_time: 0
  Kamera_HWR:
    ffmpeg:
      inputs:
        - path: 
            rtsp://192.168.31.230:554/stream0?username=admin&password=*****
          roles:
            - detect
            - clips
            - record
    detect:
      width: 1280
      height: 720
      fps: 20
      max_disappeared: 100
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 1500
          max_area: 100000
          threshold: 0.65
        car:
          min_area: 5000
          max_area: 200000
          threshold: 0.65
      mask: 0.834,0.233,0.848,0.474,0.962,0.483,0.933,0.246
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 20
    zones: {}
    onvif:
      host: 192.168.31.230
      port: 80
      user: admin
      password: '123456'
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zooming: disabled
        required_zones:
          - Home
        return_preset: PRESET_1
        track:
          - person
    motion:
      mask: 0.627,0.908,0.85,0.911,0.849,0.862,0.971,0.871,0.974,0.948,0.627,0.956
  Kamera_Schuppen:
    motion:
      mask:
        - 0,0,263,0,482,0,495,83,397,110,261,342,55,576,0,576
        - 1340,245,972,47,960,0,1536,0,1536,576
      improve_contrast: false
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - '5000000'
        - -vaapi_device
        - /dev/dri/renderD128
        - -hwaccel
        - vaapi
      inputs:
        - path: 
            http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=****
          roles:
            - record
  Kamera_hinten_links:
    ffmpeg:
      inputs:
        - path: rtsp://admin:*****@192.168.31.110:554/h264Preview_01_sub
          roles:
            - detect
            - record
            - rtmp
          input_args:
            - -rtsp_transport
            - tcp
    detect:
      width: 1280
      height: 720
      fps: 15
      max_disappeared: 50
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 20
        retain:
          default: 10
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_area: 1500
          max_area: 100000
          threshold: 0.65
        car:
          min_area: 5000
          max_area: 200000
          threshold: 0.65
        dog:
          min_area: 1000       # Mindestfläche für erkannte Hunde
          max_area: 50000      # Maximalfläche für erkannte Hunde
          threshold: 0.65
      mask: 0.001,0.35,0.234,0.331,0.285,0.986,0.001,0.991
    motion:
      improve_contrast: true
version: 0.14
```

### Relevant log output

```shell
Nothing
```

### Operating system

Proxmox

### Install method

Docker CLI

### Object Detector

Coral
