### DISCUSSION TITLE
[Config Support]: civil defense siren not detected

### DISCUSSION THREAD

**Discussion by izzygold** [blakeblackshear/frigate#12835] [Config Support]
### Describe the problem you are having

Hi,
I have multiple cameras, unfortunately my house is in a war zone, so I have multiple events a day including: gunshots, explosions etc.
the vast majority of events are captures, but for some reason the civil air defense is never triggering. I am using cpu to process the detection (I have coral but its a bit problematic to get to the house to install it, will it change the quality of detections? I don't see performance issues on my setup)

### Version

5.2.0

### Frigate config file

```yaml
mqtt:
   mqtt_login_details
go2rtc:
   streams:
       list_of_ips
audio:
  enabled: True
  listen:
    - explosion
    - gunshot
    - machine_gun
    - artillery_fire
    - cap_gun
    - fireworks
    - siren
    - civil_defense_siren

detectors:
  cpu:
    type: cpu
    num_threads: 2
cameras:
  front_yard: 
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://XXXXX
          roles:
            - record
            - detect
            - audio
    rtmp:
      enabled: False
    record:
      export:
        timelapse_args: "-vf setpts=PTS/60 -r 25"
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: True

        record: preset-record-generic-audio-aac
      inputs:
        - path: XXXXX
          roles:
            - record
            - detect
            - audio
    rtmp:
      enabled: False
    record:
      export:
        timelapse_args: "-vf setpts=PTS/60 -r 25"
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: True

  eastern_path: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: XXXXX
          roles:
            - record
            - detect
            - audio
    rtmp:
      enabled: False
    record:
      export:
        timelapse_args: "-vf setpts=PTS/60 -r 25"
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: True
```

### Relevant log output

```shell
no logs
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

**Comment by NickM-27** [comment]
You could try lowering the score threshold for that label

**Reply by izzygold** [reply]
How can I do this per label?

**Reply by NickM-27** [reply]
```
audio:
  filters:
    civil_defense_siren:
      threshold: 0.6
```
