### DISCUSSION TITLE
[Support]: Unable to type time when selecting start/stop dates for export

### DISCUSSION THREAD

**Discussion by noelhibbard** [blakeblackshear/frigate#12840] [General Support]
### Describe the problem you are having

When doing a custom range when exporting a video, you can select a date in the past, but then when start typing the time on the keyboard, the date picker switches back to today. You can select a custom date/time if you only use the mouse.

### Steps to reproduce

- Select a camera
- Click the history button
- Click the export button
- Select Custom
- With the mouse, click a date, for example 2024-08-06
- With the mouse, set focus to the time input
- Start typing a time with the keyboard

As soon as you start typing the time, the date switches back to today's date. The only way to select a time is with the mouse.

### Version

0.14.0

### Frigate config file

```yaml
# yaml-language-server: $schema=http://server1.example.com:5000/api/config/schema.json

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: auto

tls:
  enabled: false

auth:
  enabled: true
  reset_admin_password: false
  cookie_secure: false
  session_length: 86400 # 24 hours
  refresh_time: 43200 # 12 hours
  trusted_proxies: []
  hash_iterations: 600000

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - car
      - person

motion:
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 100
  mask: 0.000,0.469,1.000,0.469,1.000,1.000,0.000,1.000
  improve_contrast: true
  mqtt_off_delay: 30

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 0
    mode: all
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: false
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
  quality: 70

go2rtc:
  log:
    level: info # default level
    api: trace
    exec: debug
    ngrok: info
    rtsp: warn
    streams: error
    webrtc: fatal
  api:
    listen: :1984
    origin: '*'
  webrtc:
    candidates:
      - 10.18.1.1:8555
      # - stun:8555
    listen: :8555
  rtsp:
    listen: :9554
  srtp:
    listen: :9443
  streams:
    Front_Left:
      - ffmpeg:http://frontyard.example.com/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXXX&password=XXXXXX#video=copy#audio=copy#audio=opus
      - rtsp://XXXXXX:XXXXXXX@frontyard.example.com:554/h264Preview_01_sub
mqtt:
  host: server1.example.com
  topic_prefix: frigate
birdseye:
  enabled: true
  restream: false
  width: 1920
  height: 1080
  quality: 8
  mode: objects
cameras:
  Front_Left:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://frigate:9554/Front_Left
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    detect:
      stationary:
        interval: 50
        threshold: 50
        max_frames:
          default: 3000
          objects:
            person: 1000
      enabled: true
      max_disappeared: 100
      width: 2688
      height: 1520
      fps: 10
    objects:
      track:
        - person
        - car
        - bicycle
        - bus
      filters:
        car:
          threshold: 0.63
          mask:
            - 0.278,0.176,0.046,0.269,0.026,0.382,0.158,0.325,0.175,0.309,0.285,0.27
            - 0.804,0.149,0.908,0.184,0.891,0.208,0.801,0.182
            - 0.829,0.165,0.802,0.158,0.8,0.134,0.833,0.145
    motion:
      mask:
        - 1,1,1,0.452,0.798,0.556,0.554,0.642,0.5,0.769,0.363,1,0.656,1
        - 0.474,0,0.425,0,0.329,0,0.301,0.101,0.316,0.208,0.376,0.326,0.403,0.345,0.431,0.313,0.475,0.156
        - 0.261,0.16,0.291,0.148,0.324,0.077,0.318,0,0.193,0,0.18,0.062,0.191,0.132,0.222,0.159
        - 0.697,0.091,0.724,0.051,0.651,0,0.606,0,0.596,0.025
        - 0.801,0.158,0.881,0.185,0.898,0.173,0.898,0.134,0.885,0.046,0.836,0.014,0.811,0.043,0.791,0.107
        - 1,0.29,0.929,0.195,0.921,0,1,0
      threshold: 25
    zones:
      Driveway:
        coordinates: 368,860,243,1178,130,1520,0,1520,0,819,468,736
      Yard:
        coordinates: 2688,1520,2688,493,1808,529,463,744,328,960,122,1520
        filters:
          car:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      Road_West:
        coordinates: 0.007,0.385,0,0.53,0.124,0.491,0.121,0.345
        inertia: 3
      Road_East:
        coordinates: 0.92,0.241,0.936,0.322,0.832,0.334,0.799,0.228
        inertia: 3
    snapshots:
      enabled: true
      crop: true
      height: 500
    record:
      enabled: true
      retain:
        days: 4
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - bicycle
          - bus
        retain:
          mode: active_objects
          default: 10
          objects:
            person: 15
    review:
      alerts:
        required_zones:
          - Driveway
          - Yard
version: 0.14
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

I was able to reproduce this in Brave and Chrome.
