### DISCUSSION TITLE
[Config Support]: ImportError: no module named object_detection

### DISCUSSION THREAD

**Discussion by tarteAuxPommes** [blakeblackshear/frigate#12846] [Config Support] [answered]
### Describe the problem you are having

Hello, 

I'm trying to install Frigate on NAS Synology DSM 7.2.1. I created a container and add config.yml. 
I have an error when i run the container.
The error in log say : ImportError: no module named object_detection

![image](https://github.com/user-attachments/assets/23c42be8-def9-47ae-9300-0413a22578ec)
![image](https://github.com/user-attachments/assets/d19b8136-c373-4b91-9a5c-442070064a1b)

I probably missed something. Can you please help me ?

Best regards,

### Version

Last version

### Frigate config file

```yaml
mqtt:
  enabled: False  # MQTT désactivé

cameras:
  CAMJARDIN:  # Nom de la caméra
    ffmpeg:
      inputs:
        - path: rtsp://admin:MyPass@192.168.3.218:554/  # Chemin du flux RTSP
          roles:
            - detect
    detect:
      enabled: False  # Désactivation de la détection jusqu'à ce que le flux soit vérifié
```

### Relevant log output

```shell
ImportError: no module named object_detection
```

### Operating system

Other

### Install method

Docker CLI

### Object Detector

CPU (no coral)
