### DISCUSSION TITLE
[Bug]: frigate 0.14.0 fails to clean up events and eventually stops showing camera streams

### DISCUSSION THREAD

**Discussion by jho1670** [blakeblackshear/frigate#12845] [Report a Bug]
### Describe the problem you are having

Frigate runs then after about 10-20 minutes, most of the cameras show no output/no stream/no video until Frigate is restarted.

### Steps to reproduce

1. Upgrade to 0.14.0. I have around 30 cameras.
2. Let instance run for about 20 minutes.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
# yaml-language-server: $schema=https://frigate.dmbc.ca/api/config/schema

mqtt:
  host: 192.168.0.10
  topic_prefix: frigate
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy -c:a aac
####################
# Global object configuration. Applies to all cameras
# unless overridden at the camera levels.
# Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
# All labels from the model are reported over MQTT. These values are used to filter out false positives.
# min_area (optional): minimum width*height of the bounding box for the detected person
# max_area (optional): maximum width*height of the bounding box for the detected person
# threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
####################
detectors:
#  cpu1:
#    type: cpu
#    num_threads: 1
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: true

objects:
  track:
    - personES
    - car
    - truck
  filters:
    person:
      min_area: 1000
      min_score: 0.6
      threshold: 0.6
    car:
      min_area: 10000
      min_score: 0.6
      threshold: 0.6

record:
  enabled: true
  expire_interval: 2
  retain:
    days: 0
  events:
    retain:
      default: 45
      mode: active_objects

birdseye:
  enabled: true
  mode: objects

cameras:
  inside-room-blah-4R:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.47:554/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.47:554/?inst=1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    zones:
      blah-4R-zone-1:
        coordinates: 49,720,413,720,688,720,1280,699,1280,460,740,493,0,526
      blah-4R-zone-2:
        coordinates: 298,454,606,394,872,334,1280,298,1280,207,296,137
    review:
      alerts:
        required_zones:
          - blah-4R-zone-1
          - blah-4R-zone-2

  inside-alt-side-door-stairwell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.22:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.22:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person

  inside-balcony-room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.17:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.17:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,245,152,195,275,157,345,135,379,117,969,186,1024,0,0,0

  inside-basement-children-room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.21:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.21:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    zones:
      basement-room-zone:
        coordinates: 0,576,39,576,460,576,958,576,1024,429,1024,132,721,79,536,96,0,136
    review:
      alerts:
        required_zones:
          - basement-room-zone

  inside-basement-children-blah:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.15:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.15:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,95,49,94,93,97,241,91,335,88,494,87,1024,115,1024,0,0,0

  inside-basement-front-stairwell:
    ffmpeg:
      inputs:
        - path: rtsp://user1:<redacted>@192.168.80.39/profile2/media.smp
          roles:
            - record
        - path: rtsp://user1:<redacted>@192.168.80.39/profile2/media.smp
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0,1280,0,1280,110,467,61,0,97

  inside-basement-laundry-room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.46:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.46:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: motion

  inside-basement-room-hallway:
    ffmpeg:
      inputs:
        - path: rtsp://user1:<redacted>@192.168.80.40/profile2/media.smp
          roles:
            - record
        - path: rtsp://user1:<redacted>@192.168.80.40/profile2/media.smp
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    zones:
      room-hallway-zone:
        coordinates:
          393,720,509,720,699,720,836,720,1280,720,1280,602,947,327,745,172,574,180,401,235
    review:
      alerts:
        required_zones:
          - room-hallway-zone

  inside-front-lobby:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.34/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.34/?inst=1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 892,177,1280,269,1280,0,733,0

  inside-room:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.29:554/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.29:554/?inst=1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0,1280,0,1280,188,0,203

  inside-room-back-stairwell:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.45/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.45/?inst=1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    zones:
      back-stairwell-zone:
        coordinates: 35,720,95,698,244,720,341,698,895,699,1206,698,1280,308,1133,96,849,92,0,435
    review:
      alerts:
        required_zones:
          - back-stairwell-zone

  inside-room-side:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.36:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.36:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,95,49,94,93,97,241,91,335,88,494,87,1024,115,1024,0,0,0

  inside-hallway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.18:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.18:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    zones:
      inside-hallway-zone:
        coordinates: 165,576,896,576,957,342,718,281,0,435
    review:
      alerts:
        required_zones:
          - inside-hallway-zone

  inside-pantry:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.16:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.16:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,156,229,112,310,101,457,113,1024,127,1024,0,0,0
        - 1024,576,1024,195,907,218,763,352,707,576

  inside-pantry-sitting-area:
	
      inputs:
        - path: rtsp://192.168.80.23:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.23:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0,1024,0,1024,139,0,138

  inside-blah-area:
    ffmpeg:
      inputs:
        - path: rtsp://user1:<redacted>@192.168.80.49/profile2/media.smp
          roles:
            - record
        - path: rtsp://user1:<redacted>@192.168.80.49/profile2/media.smp
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,414,64,609,115,605,511,174,525,21,0,22

  inside-rear-elevator:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.14:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.14:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 1
    objects:
      track:
        - person
    zones:
      elevator-zone:
        coordinates: 743,576,825,441,850,277,262,173,79,281,103,576
    review:
      alerts:
        required_zones:
          - elevator-zone

  inside-blah-podium:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.13:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.13:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 1
    objects:
      track:
        - person
    zones:
      podium_0:
        coordinates:
          566,360,567,317,570,264,555,196,530,157,483,110,410,107,342,111,252,111,164,113,115,141,94,250,96,360

  inside-side-entrance-stairwell:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.38:554/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.38:554/?inst=1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person

  inside-side-room-balcony:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.10:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.10:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    zones:
      room-balcony-zone1:
        coordinates: 0,576,208,576,497,576,868,576,1024,256,629,37,126,41,0,171
    review:
      alerts:
        required_zones:
          - room-balcony-zone1

  inside-upstairs-kitchen-hallway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.30:554/s1
          roles:
            - record
        - path: rtsp://192.168.80.30:554/s1
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,365,201,118,192,0,0,0
        - 426,0,416,122,533,207,1024,188,1024,0

  inside-upstairs-office-blah-area:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.31:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.31:554/s1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    zones:
      blah-zone:
        coordinates: 1227,720,976,274,572,165,484,166,241,383,23,415,0,720
    review:
      alerts:
        required_zones:
          - blah-zone

  outside-front-driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.11:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.11:554/s1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 842,157,1920,190,1920,0,965,0,0,0,0,389

  outside-front-main-door:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.44/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.44/?inst=1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 903,219,1134,249,1063,249,1027,238,1920,410,1920,347,1920,204,1920,160,1920,124,1920,0,0,0,0,323

  outside-front-side-door-parking-lot:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.37:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.37:554/s1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 1920,0,1920,309,0,326,0,0
        - 1920,82,1920,661,415,333

  outside-rear-parking-lot-north:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.48:554/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.48:554/?inst=1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,138,1166,157,1920,196,1920,0,0,0
        - 1540,163,1920,323,1920,122,1450,103

  outside-rear-parking-lot-center:
    ffmpeg:
      inputs:
        - path: rtsp://user:<redacted>@192.168.80.33:554/?inst=1
          roles:
            - record
        - path: rtsp://user:<redacted>@192.168.80.33:554/?inst=1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,0,1920,0,1920,168,0,136

  outside-rear-parking-lot-south:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.80.20:554/s0
          roles:
            - record
        - path: rtsp://192.168.80.20:554/s1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,0,168,0,502,0,1003,0,1920,0,1920,276,0,252

        #  inside-cafe-25:
        #    ffmpeg:
        #      inputs:
        #        - path: rtsp://192.168.100.22:554/s0
        #          roles:
        #            - record
        #        - path: rtsp://192.168.100.22:554/s1
        #          roles:
        #            - detect
        #    detect:
        #      width: 640
        #      height: 360
        #      fps: 5
version: 0.14
```

### Relevant log output

```shell
Exception in thread event_cleanup:
unknown
2024-08-08 17:17:50
unknown
Traceback (most recent call last):
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3322, in execute_sql
unknown
2024-08-08 17:17:50
unknown
cursor.execute(sql, params or ())
unknown
2024-08-08 17:17:50
unknown
sqlite3.OperationalError: too many SQL variables
unknown
2024-08-08 17:19:03
unknown
24-08-08 17:17:50.764901263
unknown
2024-08-08 17:17:50
unknown
During handling of the above exception, another exception occurred:
unknown
2024-08-08 17:19:03
unknown
24-08-08 17:17:50.764914368
unknown
2024-08-08 17:17:50
unknown
Traceback (most recent call last):
unknown
2024-08-08 17:17:50
unknown
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
unknown
2024-08-08 17:17:50
unknown
self.run()
unknown
2024-08-08 17:17:50
unknown
File "/opt/frigate/frigate/events/cleanup.py", line 197, in run
unknown
2024-08-08 17:17:50
unknown
self.expire(EventCleanupType.snapshots)
unknown
2024-08-08 17:17:50
unknown
File "/opt/frigate/frigate/events/cleanup.py", line 184, in expire
unknown
2024-08-08 17:17:50
unknown
Event.update(update_params).where(Event.id << events_to_update).execute()
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2036, in inner
unknown
2024-08-08 17:17:50
unknown
return method(self, database, *args, **kwargs)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2107, in execute
unknown
2024-08-08 17:17:50
unknown
return self._execute(database)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2626, in _execute
unknown
2024-08-08 17:17:50
unknown
return self.handle_result(database, cursor)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2637, in handle_result
unknown
2024-08-08 17:17:50
unknown
return database.rows_affected(cursor)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3834, in rows_affected
unknown
2024-08-08 17:17:50
unknown
return cursor.rowcount
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 94, in rowcount
unknown
2024-08-08 17:17:50
unknown
self._wait()
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 63, in _wait
unknown
2024-08-08 17:17:50
unknown
raise self._exc
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 183, in execute
unknown
2024-08-08 17:17:50
unknown
cursor = self.database._execute(obj.sql, obj.params)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3322, in execute_sql
unknown
2024-08-08 17:17:50
unknown
cursor.execute(sql, params or ())
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3088, in __exit__
unknown
2024-08-08 17:17:50
unknown
reraise(new_type, new_type(exc_value, *exc_args), traceback)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 196, in reraise
unknown
2024-08-08 17:17:50
unknown
raise value.with_traceback(tb)
unknown
2024-08-08 17:17:50
unknown
File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3322, in execute_sql
unknown
2024-08-08 17:17:50
unknown
cursor.execute(sql, params or ())
unknown
2024-08-08 17:17:50
unknown
peewee.OperationalError: too many SQL variables
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Mix of Bosch, Ubiquiti, Hanwha, etc.
