### DISCUSSION TITLE
[Support]:  Random occurrence "Failed to play recordings (error 4)"

### DISCUSSION THREAD

**Discussion by ChienDeLaCasse** [blakeblackshear/frigate#12841] [General Support]
### Describe the problem you are having

Hello, 
first of all, thanks a lot for this massive work on 0.14. 
I have the following issue appearing randomly : I cannot access the live stream (indefinite "loop" icon) nor the events/recording of my camera. 

The funny thing is that I don't change anything in my configuration setting. 
It does not seem to show anything on system log.

However, when trying to look at a detection event, there is a red pop-up with the following : 
**Failed to play recordings (error 4): DECODER_ERROR_NOT_SUPPORTED: video decoder initialization failed with DecoderStatus::Codes:kUnsupportedConfig**

I never had any such issue on Frigate 0.13.
Camera is an Annke FCD600.
I am using Edge navigator for web GUI.

Would greatly appreciate your help for troubleshooting, thanks!

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - cat
    - dog
    - bike

#  filters:
#    person:
#      min_area: 5000
#      max_area: 100000


go2rtc:
  streams:
    Annke_main:
      - rtsp://login:password@192.168.1.79:554/H264/ch1/main/av_stream
#      - ffmpeg:Annke_main#audio=opus

    


cameras:
  Annke_main:
    ffmpeg:
#      output_args:
#        record: preset-record-generic-audio-copy
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/Annke_main
#          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    


    detect:
      width: 3632
      height: 1632
      fps: 8



    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 15
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 15
      required_zones:
        - Zall
        - ZCar1
        - ZCar2


    motion:
      mask:
        - 1314,0,3632,0,3632,311,3632,670,3632,931,3377,630,1699,644,1132,683,815,797,673,778,517,667,380,596,264,823,327,950,232,1034,0,987,0,0

    zones:
      Zall:
        coordinates: 0,1632,3632,1632,3632,517,0,504
        objects:
          - person
          - bike
          - dog
          - cat
        filters:
          dog:
            min_ratio: 1.1
          cat:
            max_area: 60000
      ZCar1:
        coordinates: 3094,818,2298,905,2237,644,3632,615,3632,773,3632,989,3313,923
        objects:
          - car
        filters:
          car:
#            min_area: 30000
            min_ratio: 1.3
      ZCar2:
        coordinates: 45,1029,1155,1161,1380,873,749,736,0,754
        objects:
          - car
        filters:
          car:
#            min_area: 30000
            min_ratio: 1.3

    review:
      alerts:
        required_zones:
          - Zall
          - ZCar1
          - ZCar2

version: 0.14
```

### Relevant log output

```shell
Don't see any error or anything abnormal in the system logs.
```

### FFprobe output from your camera

```shell
Apologies, I don't find the ffprobe command either at the Proxmox shell or at the Frigate container shell.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Annke FCD600 dual lens camera
