### DISCUSSION TITLE
[Support]: Frigate 0.14.0 Docker - NGINX error on startup

### DISCUSSION THREAD

**Discussion by simonepittis** [blakeblackshear/frigate#12853] [General Support]
### Describe the problem you are having

2024-08-09 07:46:10.203990559  [INFO] Starting NGINX...

./run.user: line 84: tempio: command not found

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>

BrokenPipeError: [Errno 32] Broken pipe

2024-08-09 07:46:10.261626868  [INFO] Service NGINX exited with code 127 (by signal 0)

### Steps to reproduce

after upgrade from 0.13.2

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx.xxx.xxx.9
  port: 1883
  topic_prefix: frigate
  client_id: frigate-server
  user: username
  password: password

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 15
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 15

birdseye:
  enabled: true
  restream: true
  mode: continuous

cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 15

  parking:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/parking
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 15

  garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 15
    objects:
      track:
        - person
        - cat
        - dog

  backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    record:
      enabled: true
      retain:
        days: 15
    objects:
      track:
        - person
        - cat
        - dog

  terrace:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/terrace
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2304
      height: 1296
    record:
      enabled: true
      retain:
        days: 15

  giulia:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/giulia
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: false
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 7

  stair:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/stair
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: false
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 7

  livingroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/livingroom
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: false
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 7

  bedroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.12:8554/bedroom
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: false
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
version: 0.14
```

### Relevant log output

```shell
2024-08-09 07:46:10.203990559  [INFO] Starting NGINX...

./run.user: line 84: tempio: command not found

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>

BrokenPipeError: [Errno 32] Broken pipe

2024-08-09 07:46:10.261626868  [INFO] Service NGINX exited with code 127 (by signal 0)
```

### Operating system

Other

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

TAPO

**Comment by jwarner3412** [comment]
I also have this exact issue. 

```
mqtt:
  host: x.x.x.100
  user: user
  password: ******
detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac
audio:
  enabled: true
detect:
  fps: 5
record:
  enabled: true
  events:
    objects:
      - person
      - cat
objects:
  track:
    - person
    - cat
snapshots:
  enabled: true
go2rtc:
  streams:
    foyer:
      - rtsp://user:********@x.x.x.107:554/stream1
      - ffmpeg:foyer#audio=aac
      - tapo://HAbc2r6aV8UgZ5aw@x.x.x.107
    foyer_sub:
      - rtsp://user:********@x.x.x.107:554/stream2
    kitchen:
      - rtsp://user:********@x.x.x.102:554/stream1
      - ffmpeg:kitchen#audio=aac
      - tapo://HAbc2r6aV8UgZ5aw@x.x.x.102
    kitchen_sub:
      - rtsp://user:********@x.x.x.102:554/stream2
    living_room:
      - rtsp://user:********@x.x.x.110:554/stream1
      - ffmpeg:living_room#audio=aac
      - tapo://HAbc2r6aV8UgZ5aw@x.x.x.110
    living_room_sub:
      - rtsp://user:********@x.x.x.110:554/stream2
    bedroom:
      - rtsp://user:********@x.x.x.111:554/stream1
      - ffmpeg:bedroom#audio=aac
      - tapo://HAbc2r6aV8UgZ5aw@x.x.x.111
    bedroom_sub:
      - rtsp://user:********@x.x.x.111:554/stream2
  webrtc:
    candidates:
      - x.x.x.100:8555
      - stun:8555
cameras:
  foyer:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/foyer
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/foyer_sub
          roles:
            - detect
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/kitchen
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/kitchen_sub
          roles:
            - detect
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/living_room
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/living_room_sub
          roles:
            - detect
  bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/bedroom
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/bedroom_sub
          roles:
            - detect
version: 0.14
```
