### DISCUSSION TITLE
Intel NCS2 broken since 0.14.0-beta2

### DISCUSSION THREAD

**Discussion by guestus** [blakeblackshear/frigate#12855] [Detector Support]
### Describe the problem you are having

After update to 0.14.0-beta2 or later freegate container don't wona start.

The changes  _image: ghcr.io/blakeblackshear/frigate:0.14.0-beta1_ to _image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2_ int compose file gains this error:
**Device with "MYRIAD" name is not registered in the OpenVINO Runtime**
```
frigate  | 2024-08-09 07:09:14.011581306  Process detector:ncs:
frigate  | 2024-08-09 07:09:14.018131606  Traceback (most recent call last):
frigate  | 2024-08-09 07:09:14.022644206    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-08-09 07:09:14.022652126      self.run()
frigate  | 2024-08-09 07:09:14.022655486    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-08-09 07:09:14.022658270      self._target(*self._args, **self._kwargs)
frigate  | 2024-08-09 07:09:14.022666202    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2024-08-09 07:09:14.022671050      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-08-09 07:09:14.022674614    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2024-08-09 07:09:14.022732298      self.detect_api = create_detector(detector_config)
frigate  | 2024-08-09 07:09:14.022736222    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-08-09 07:09:14.022739222      return api(detector_config)
frigate  | 2024-08-09 07:09:14.022742354    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 38, in __init__
frigate  | 2024-08-09 07:09:14.022807406      self.interpreter = self.ov_core.compile_model(
frigate  | 2024-08-09 07:09:14.022811714    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 521, in compile_model
frigate  | 2024-08-09 07:09:14.022858610      super().compile_model(model, device_name, {} if config is None else config),
frigate  | 2024-08-09 07:09:14.022862594  RuntimeError: Exception from src/inference/src/cpp/core.cpp:123:
frigate  | 2024-08-09 07:09:14.022865774  Exception from src/inference/src/dev/core_impl.cpp:566:
frigate  | 2024-08-09 07:09:14.022868774  Device with "MYRIAD" name is not registered in the OpenVINO Runtime

```

### Version

 0.14.0-bccffe6

### Frigate config file

```yaml
mqtt:
  host: 192.168.213.251
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user2
  password: user2
  stats_interval: 60

detectors:
  ncs:
    type: openvino
    device: MYRIAD
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: true
  max_disappeared: 25

database:
  path: /media/frigate/frigate.db

logger:
  default: debug
  logs:
    frigate.event: debug

objects:
  track:
    - person
    - cat
    - dog

cameras:
  room:
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://u1:p1@192.168.213.244:554/stream1
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 626,0,625,70,0,65,0,0
    best_image_timeout: 60

  dacha:
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://u2:p2@192.168.215.197:554/stream1
          roles:
            - audio
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 626,0,625,70,0,65,0,0
    best_image_timeout: 60

  home:
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://u3:p3@192.168.213.243:554/ISAPI/Streaming/channels/101/
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 626,0,625,70,0,65,0,0
    best_image_timeout: 60

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
    retain:
      default: 7
      mode: active_objects

motion:
  threshold: 50
  contour_area: 50
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mask:
    - 411,29,412,0,0,0,0,30
  improve_contrast: false
  mqtt_off_delay: 30

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  required_zones: []
  retain:
    default: 10

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
#version: 0.14
#version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0-beta2
    shm_size: "64mb"
    device_cgroup_rules:
      - "c 189:* rmw"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yaml:/config/config.yaml
      - /opt/shara/frigate/storage:/media/frigate
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    network_mode: "host"
    #ports:
    #  - "5000:5000" # Port used by the Web UI
    #  - "8554:8554" # RTSP feeds
    #  - "8555:8555/tcp" # WebRTC over tcp
    #  - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
frigate  | 2024-08-09 07:09:14.011581306  Process detector:ncs:
frigate  | 2024-08-09 07:09:14.018131606  Traceback (most recent call last):
frigate  | 2024-08-09 07:09:14.022644206    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-08-09 07:09:14.022652126      self.run()
frigate  | 2024-08-09 07:09:14.022655486    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-08-09 07:09:14.022658270      self._target(*self._args, **self._kwargs)
frigate  | 2024-08-09 07:09:14.022666202    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2024-08-09 07:09:14.022671050      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-08-09 07:09:14.022674614    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2024-08-09 07:09:14.022732298      self.detect_api = create_detector(detector_config)
frigate  | 2024-08-09 07:09:14.022736222    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-08-09 07:09:14.022739222      return api(detector_config)
frigate  | 2024-08-09 07:09:14.022742354    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 38, in __init__
frigate  | 2024-08-09 07:09:14.022807406      self.interpreter = self.ov_core.compile_model(
frigate  | 2024-08-09 07:09:14.022811714    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 521, in compile_model
frigate  | 2024-08-09 07:09:14.022858610      super().compile_model(model, device_name, {} if config is None else config),
frigate  | 2024-08-09 07:09:14.022862594  RuntimeError: Exception from src/inference/src/cpp/core.cpp:123:
frigate  | 2024-08-09 07:09:14.022865774  Exception from src/inference/src/dev/core_impl.cpp:566:
frigate  | 2024-08-09 07:09:14.022868774  Device with "MYRIAD" name is not registered in the OpenVINO Runtime
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino
