### DISCUSSION TITLE
[Question]: Trigger alerts for objects only when the object has loitered in a zone for some time?

### DISCUSSION THREAD

**Discussion by PHLAK** [blakeblackshear/frigate#12854] [Ask A Question] [answered]
I upgraded to v0.14 today and am absolutely loving it, the new UI is fantastic. Thanks to all involved in this release!

With the update and introduction of alerts and loiter times I'm wondering if it's possible combine these to set up a zone that will trigger alerts for objects only when the object has loitered in that zone for a certain amount of time but log all detections in that zone as soon as an object is detected.

For example, I have a camera pointed at my front yard that also sees the street. I have a zone that covers the street. I'd like all people and cars detected in the `street` to log a detection no matter how long they're in the zone (e.g. a car drives by) but only trigger an alert if they loiter there for 10+ seconds (e.g. a car parks in front of my house).

Is this possible?

Here's my current config (edited for brevity).

```yaml
cameras:
  front_yard:
    objects:
      track: [person, cat, dog, car, amazon, fedex, ups, package]
    review:
      alerts:
        labels: [person, cat, dog, car]
        required_zones: [street, yard]
      detections:
        required_zones: [street, yard]
    zones:
      street:
        coordinates: ...
        loitering_time: 10
        objects: [person, cat, dog, amazon, fedex, ups, package]
      yard:
        coordinates: ...
        objects: [person, cat, dog, package]
```

As it is now with `loitering_time` on the `street` zone a detection is  only logged if an object is in the zone for 10+ seconds. It would be nice if I could instead define the `loitering_time` only for alerts for the yard zone. Maybe something like this.

```
    review:
      alerts:
        required_zones:
          street:
            labels: [person, cat, dog, car]
            loitering_time: 10
          yard:
            labels: [person, cat, dog, car]
```

To take this one step further, it would be even better if we could configure loitering time per zone + object combination (e.g. alert for a person in the zone immediately but only alert for cars in the zone after loitering for 10+ seconds) but that might be wishful thinking.
