### DISCUSSION TITLE
[Config Support]: How to enable non-stop streaming in Camera Group?

### DISCUSSION THREAD

**Discussion by SailingSailing** [blakeblackshear/frigate#12858] [Config Support] [answered]
### Describe the problem you are having

It seems like my cameras only stream when motion is detected, but I need them to stream 24/7. I'm not sure where I'm going wrong in the configuration ? 

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  enabled: false

  # Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  width: 2560
  height: 1440
  restream: true

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

go2rtc:
  streams:
    bulwark_port:
      - rtsp://admin:pass@192.168.170.25:554/stream0
    bulwark_stb:
      - rtsp://admin:pass@192.168.170.13:554/stream0
    cockpit_port:
      - rtsp://admin:pass@192.168.170.20:554/stream0
    cockpit_stb:
      - rtsp://admin:zcpm3ETO@192.168.170.140:554/stream0
    main_engine_port:
      - rtsp://admin:pass@192.168.170.19:554/stream0
    main_engine_stb:
      - rtsp://admin:pass@192.168.170.12:554/stream0
    fwd_mast_port:
      - rtsp://admin:pass@192.168.170.29:554/stream0
    fwd_mast_stb:
      - rtsp://admin:pass@192.168.170.28:554/stream0
    er_upper_port_fwd:
      - rtsp://admin:pass@192.168.170.17:554/stream0
    er_upper_stbd_inboard:
      - rtsp://admin:pass@192.168.170.150:554/stream0
    er_lower_stb_aft:
      - rtsp://admin:pass@192.168.170.24:554/stream0
    mizzen_mast_port:
      - rtsp://admin:pass@192.168.170.26:554/stream0

cameras:
  bulwark_stb:
    enabled: true
    birdseye:
      order: 1
    ffmpeg:
     # hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/bulwark_stb
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  cockpit_stb:
    enabled: true
    birdseye:
      order: 2
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/cockpit_stb
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  er_upper_stbd_inboard:
    enabled: true
    birdseye:
      order: 3
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/er_upper_stbd_inboard
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  fwd_mast_stb:
    enabled: true

    birdseye:
      order: 4
    ffmpeg:
 #     hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/fwd_mast_stb
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  er_upper_port_fwd:
    enabled: true
    birdseye:
      order: 5
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/er_upper_port_fwd
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  main_engine_stb:
    enabled: true
    birdseye:
      order: 6
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/main_engine_stb
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  main_engine_port:
    enabled: true
    birdseye:
      order: 7
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/main_engine_port
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  cockpit_port:
    enabled: true
    birdseye:
      order: 8
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/cockpit_port
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  er_lower_stb_aft:
    enabled: true
    birdseye:
      order: 9
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/er_lower_stb_aft
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  bulwark_port:
    enabled: true
    birdseye:
      order: 10
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/bulwark_port
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  fwd_mast_port:
    enabled: true
    birdseye:
      order: 11
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/fwd_mast_port
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
  mizzen_mast_port:
    enabled: true
    birdseye:
      order: 12
    ffmpeg:
#      hwaccel_args: preset-vaapi
      retry_interval: 10
      inputs:
        - path: rtsp://localhost:8554/mizzen_mast_port
          roles:
            - detect
    detect:
      enabled: false
      fps: 5
version: 0.14
camera_groups:
  All_CAmera:
    order: 1
    icon: LuAlignCenterHorizontal
    cameras:
      - cam13
      - cam14
      - cam148
      - cam15
      - cam17
      - cam19
      - cam20
      - cam25
      - cam1
      - cam2
      - cockpit_stb
      - bulwark_stb
      - bulwark_port
      - cockpit_port
  TEst:
    order: 2
    icon: LuAlignEndHorizontal
    cameras:
      - cam13
      - cam14
      - cam148
      - cam19
      - fwd_mast_port
      - fwd_mast_stb
      - cockpit_port
      - cockpit_stb
  Column:
    order: 3
    icon: LuAlignVerticalJustifyEnd
    cameras:
      - bulwark_port
      - bulwark_stb
      - cockpit_port
      - cockpit_stb
  During_Passage:
    order: 4
    icon: LuSailboat
    cameras: mizzen_mast_port
```

### Relevant log output

```shell
Not required
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
