### DISCUSSION TITLE
Documentation error Effect of lettering

### DISCUSSION THREAD

**Discussion by brembygit** [blakeblackshear/frigate#12864] [Config Support]
### Describe the problem you are having

It seems that there is an error with the valid parameters, None is not valid, the correct way to use it is to leave the option 
blank

effect: 

if I configure it as described in the documentation

  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: None

 I get the following error

Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
timestamp_style.effect
  Input should be &#39;solid&#39; or &#39;shadow&#39; [type=enum, input_value=&#39;None&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum

### Version

0.14.0-da913d8

### Frigate config file

```yaml
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect:
```

### Relevant log output

```shell
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
timestamp_style.effect
  Input should be &#39;solid&#39; or &#39;shadow&#39; [type=enum, input_value=&#39;None&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
