### DISCUSSION TITLE
[Camera Support]: Frigate 1.4 and RTSP streams

### DISCUSSION THREAD

**Discussion by DanNeidle** [blakeblackshear/frigate#12874] [Camera Support] [answered]
### Describe the problem you are having

I have an old RTSP stream which worked for 0.13 but fail under 0.14

it's a raspberry pi streaming from a USB composite-video-to-USB device. I can view it fine using VLC at rtsp://192.168.1.15:80/live/stream, but Frigate fails

### Version

0.14

### Frigate config file

```yaml
entryphone:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.15:80/live/stream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    record:
      enabled: true
      events:
        retain:
          default: 100
          mode: motion
    detect:
      width: 640
      height: 480
      fps: 5
    ui:
      order: 2

    mqtt:
      enabled: false
    objects:
      track:
        - person
```

### Relevant log output

```shell
2024-08-09 13:02:33
frigate.record.maintainer
Failed to probe corrupt segment /tmp/cache/entryphone@20240809130233+0100.mp4
```

### FFprobe output from your camera

```shell
Stream #0:0: Video: h264 (High 4:2:2), yuv422p(progressive), 720x480, 30 fps, 30 tbr, 90k tbn, 60 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

stream
