### DISCUSSION TITLE
[Question]: When are preview_[CAMERA]_TIMESTAMP.mp4 removed from /tmp/cache?

### DISCUSSION THREAD

**Discussion by rubberbandboy** [blakeblackshear/frigate#12879] [Ask A Question]
### What is your question:

Hi,

I noticed my /tmp/cache was getting full, on checking I see other than the usual camera mp4's, we now have preview_camera mp4 files as well. As I suspect I have lots of events I think the cache is being filled causing errors processing new events, when are these preview files either stored away on the storage - or removed to be regenerated when required?

(I have cleared the review tab - therefore they remain despite not being visible on the "live" camera page at the top)

RRB

**Comment by NickM-27** [comment]
The temporary preview mp4s used for the live view are deleted every 5 minutes

**Reply by rubberbandboy** [reply]
Any way to check that? I have preview mp4's stored in /tmp/cache that are > 30 mins old.....

**Reply by NickM-27** [reply]
can you show an example?

**Reply by rubberbandboy** [reply]
I restarted the container to clear them (its a tmpfs) but this shows them 20ish mins old

![image](https://github.com/user-attachments/assets/cea6ee3e-4a8a-45c6-9533-89fcb325dddf)

**Reply by NickM-27** [reply]
hmm, that isn't right, those previews should not be inside of /tmp/cache. What is your docker config?

**Reply by rubberbandboy** [reply]
```
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.55
  port: 1883
  user: XXX
  password: XXX
  stats_interval: 30
ffmpeg:
  output_args:
    record: preset-record-ubiquiti
go2rtc:
  streams:
    aipro:
      - rtspx://192.168.1.4:7441/M5sIxh0Ou24P5izF
    aipro-low:
      - rtspx://192.168.1.4:7441/uD5b1dCvEyR6EEBM
    aipro-low-low:
      - rtspx://192.168.1.4:7441/AzoJQYc0uOgLaT9T
    garden:
      - rtspx://192.168.1.4:7441/agAbOQMUYNX2iCuP
    garden-low:
      - rtspx://192.168.1.4:7441/m6ptDe26bRZOpiLT
    shed:
      - rtspx://192.168.1.4:7441/p3tqaz0Xjxm1e3ar
    shed-low:
      - rtspx://192.168.1.4:7441/KIEFxJWxkbPUWWYY
    side:
      - rtspx://192.168.1.4:7441/8eEmzq0NihF9b6vM
    side-low:
      - rtspx://192.168.1.4:7441/uEQntXmKQLEP9qhi
    drive:
      - rtspx://192.168.1.4:7441/WpyYNt6JZkvN3O5n
    drive-low:
      - rtspx://192.168.1.4:7441/CStRW8rk2zrghZas
  webrtc:
    candidates:
      - stun:8555
      - 192.168.1.60:8555
cameras:
  aipro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/aipro-low
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/aipro
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 45
      events:
        pre_capture: 30
        post_capture: 30
        objects:
          - person
          - dog
        retain:
          default: 45
          objects:
            person: 70
            dog: 70
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 904,504,798,452,922,279,1002,318
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 70
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden-low
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garden
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 45
      events:
        pre_capture: 15
        post_capture: 15
        objects:
          - person
        retain:
          default: 45
          objects:
            person: 70
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 70
  shed:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shed-low
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/shed
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 45
      events:
        pre_capture: 30
        post_capture: 30
        objects:
          - person
        retain:
          default: 45
          objects:
            person: 70
    motion:
      mask:
        - 0,576,81,576,163,576,220,542,332,451,365,389,355,337,318,323,55,302,0,308
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 0,576,81,576,163,576,220,542,332,451,365,389,355,337,318,323,55,302,0,308
            - 930,193,932,136,814,128,811,177
        dog:
          mask:
            - 0,576,81,576,163,576,220,542,332,451,365,389,355,337,318,323,55,302,0,308
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 70
  side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side-low
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/side
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 45
      events:
        pre_capture: 30
        post_capture: 30
        objects:
          - person
          - dog
        retain:
          default: 45
          objects:
            person: 70
            dog: 70
    motion:
      mask:
        - 627,181,837,193,873,110,871,0,0,0,0,576,410,576,627,350
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 627,181,837,193,873,110,871,0,0,0,0,576,410,576,627,350
        dog:
          mask:
            - 627,181,837,193,873,110,871,0,0,0,0,576,410,576,627,350

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 70
  drive:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drive-low
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/drive
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 45
      events:
        pre_capture: 30
        post_capture: 30
        objects:
          - person
          - dog
        retain:
          default: 45
          objects:
            person: 70
            dog: 70
    motion:
      mask:
        - 368,0,444,0,426,29,408,32,403,63,320,62,318,0
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 368,0,444,0,426,29,408,32,403,63,320,62,318,0
        dog:
          mask:
            - 368,0,444,0,426,29,408,32,403,63,320,62,318,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 70
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuEye
    cameras: birdseye

```
