### DISCUSSION TITLE
[Support]: How to manually clean old snapshots, events, recordings, favorites?

### DISCUSSION THREAD

**Discussion by ovizii** [blakeblackshear/frigate#12870] [General Support] [answered]
### Describe the problem you are having

I have upgraded to Frigate 0.14 and would like to delete all old items. Frigate claims there's a lot of space used.

![image](https://github.com/user-attachments/assets/0b03788f-907e-420d-80f6-67b658f79766)

I sincerely don't need that stuff.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: core-mosquitto
  user: mosquitto
  password: secret

detectors:
  coralAI: # <---------- Name your detector (you can choose any name)
    type: edgetpu # <-- This specifies that you want to use the Coral USB Accelerator
    device: usb # <-- This tells Frigate to use the USB connected Coral device

ffmpeg:
  output_args:
    record: preset-record-generic # record without audio

go2rtc:
  streams:
    cam01:
      - rtsp://frigate:secret@192.168.95.2:554/Streaming/channels/101?transportmode=unicast&profile=Profile_1
    cam01_sub:
      - rtsp://frigate:secret@192.168.95.2:554/Streaming/channels/102?transportmode=unicast&profile=Profile_2
  webrtc:
    candidates:
      - 192.168.96.2:8555
      - 100.71.132.49:8555
      - stun:8555
# sample logging levels and their order ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
  log:
    level: info  # default level
    api: info
    exec: info
    ngrok: info
    rtsp: info
    streams: info
    webrtc: info

cameras:
  cam01: # <------ Name the camera
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/cam01
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam01_sub
          roles:
            - detect

    detect:
      enabled: true
      fps: 6
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    live:
      quality: 6

  # this configures the snapshots sent over mqtt
    mqtt:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      height: 480
      quality: 95

    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7
          min_area: 60000
    zones:
      door:
        coordinates: 933,592,1231,0,621,0,646,207,664,395
      window:
        coordinates: 118,67,235,0,380,0,460,241,293,379
      kitchen:
        coordinates: 1213,246,1055,720,859,720
      bedroom:
        coordinates: 328,720,496,720,107,288


snapshots:
  enabled: true
  bounding_box: true
  timestamp: false
  retain:
    default: 7
    objects:
      person: 10


record:
  enabled: true
# save recordings with all / motion / active_objects for XX days
  retain:
    days: 7
    mode: motion
# save recordings overlapping with events with all / motion / active_objects for xx days
  events:
    pre_capture: 10
    post_capture: 20
# this limits the types of objects recorded
    objects:
      - person
    retain:
      default: 7
      mode: active_objects
      objects:
        person: 14

motion:
  threshold: 25
  contour_area: 35

birdseye:
  enabled: true
  mode: motion
version: 0.14

# can be overridden at the camera level
review:
  alerts:
    labels:
      - person
```

### Relevant log output

```shell
no logs, no errros
```

### FFprobe output from your camera

```shell
not necessary for my question
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

not necessary for my question

**Comment by NickM-27** [comment]
You can just delete the files from the file system, but that won't change what frigate shows until it decides it needs to delete those due to the retention config.

**Reply by ovizii** [reply]
I understand but since I have no way to check the snapshots  and recordigns with the new UI and I kept some favorited I don't need anymore, I was going to delete them all. Also, not sure how favorited recordings are treated, I assume they are kept forever.

**Reply by NickM-27** [reply]
yes, any events that were favorited will stay forever because we don't want to remove something that a user may still need.

**Reply by ovizii** [reply]
Not sure waht you meant by "but that won't change what frigate shows" 
I assuem when I manually delete recordigns Frigate will revise the used storage it shows sicne the recordigns are now missing? 

Anyway, I don't want to mess with Frigate's internals, if I could make sure the favorited recordings are somehow also deleted due to my retention settings all would be well.

**Reply by ovizii** [reply]
Since I can't see the old recordings to unfavorite them, how do I get rid of them without confusing Frigate?

**Reply by NickM-27** [reply, marked as answer]
I mean that Frigate does not check automatically that the files in the file system are deleted because this is a very resource intensive task. What you can do is:

1. Delete all of the files
2. Restart Frigate with sync enabled https://docs.frigate.video/configuration/record#syncing-recordings-with-disk
3. Let it do its thing, and then disable sync.

**Reply by ovizii** [reply]
Awesome, exactly what I was looking for.

**Reply by balazsskorka** [reply]
I am pretty new to Frigate. Can you point me to some more step by step documentation for step 1 above? I am running Frigate as a HASS add-on and facing exactly the same challenge - want to delete any old recordings after having upgraded Frigate to 0.14. (I basically need to know where the files are located and how to access them) Thank you.

**Reply by ovizii** [reply]
In HA, in the menu on the left there is MEDIA and inside there is a folder FRIGATE. I wasn't sureh ow to delete from there so I connected via SSH to HA and manually deleted files inside /media/frigate - that is solely from memory, hope I didn't get any paths wrong.

**Reply by ovizii** [reply]
> I mean that Frigate does not check automatically that the files in the file system are deleted because this is a very resource intensive task. What you can do is:
> 
> 1. Delete all of the files
> 2. Restart Frigate with sync enabled https://docs.frigate.video/configuration/record#syncing-recordings-with-disk
> 3. Let it do its thing, and then disable sync.

I have a follow-up question:

After doing these steps I still see a discrepancy. Apparently I still have old files.

**Actual storage use:**
```
du -cksh /media/frigate/*
1020.2M /media/frigate/clips
0       /media/frigate/exports
6.1G    /media/frigate/recordings
7.1G    total

```
**frigate report:**
![image](https://github.com/user-attachments/assets/ecf8ba06-8b29-4ec1-aac3-8b603962bc1b)

I am simply double-checking as frigate's logs suggest that it does delete files without DB entries. So how come I still have more storage used than frigate reports?

![image](https://github.com/user-attachments/assets/d899b93d-e5a0-4c28-931b-f68b3d02367a)


**Anyway, if I am misreading the logs, I will simply manually delete snapshots/clips/recording manually.**

**Reply by NickM-27** [reply]
if you have more storage than frigate reports then you did not delete the files as step 1 recommended

**Reply by ovizii** [reply]
> if you have more storage than frigate reports then you did not delete the files as step 1 recommended

Yes, I get that, I was just wondering about the log line saying: deleting recording files with missing DB entries. That sounded like it would delete old stuff? Anyway, I might have just misread that line, will manually delete again.

**Reply by NickM-27** [reply]
6.1G is a lot more than 800 files so perhaps it deleted some

**Reply by ovizii** [reply]
Btw. I attempted another go at this: stopped frigate, manually emptied out the directory where it stores stuff, restarted frigate with sync enabled and was told this looks like an error and that frigate aborted. :-/

```
2024-10-18 16:08:38.022639541  [2024-10-18 19:08:38] frigate.record.util            INFO    : Deleting 286 recording DB entries with missing files
2024-10-18 16:08:38.024278208  [2024-10-18 19:08:38] frigate.record.util            WARNING : Deleting 1.000000% of recordings DB entries, could be due to configuration error. Aborting...
```
I tried again:

```
2024-10-18 16:12:45.740247347  [2024-10-18 19:12:45] frigate.record.util            INFO    : Deleting 286 recording DB entries with missing files
2024-10-18 16:12:45.741325775  [2024-10-18 19:12:45] frigate.record.util            WARNING : Deleting 0.993056% of recordings DB entries, could be due to configuration error. Aborting...
```

**Reply by NickM-27** [reply]
You've deleted 99% of your recording files you might as well just delete the whole DB file. Sync won't run because it is likely an error when that much of the DB would be deleted.

**Reply by manish-patel** [reply]
@NickM-27 

Can you confirm if i delete the Frigate.db

1. How to kepp Users that have already been settup
2. Ensure Face Detection trained images and data are kept
3. Same for LPR Data

**Reply by NickM-27** [reply]
1. You can't, you'd need to use SQL to remove specific parts of the database
2. This is based on image files, not stored in the DB
3. same as 2

**Reply by manish-patel** [reply]
Thanks @NickM-27 


![Screenshot 2026-01-09 at 18 00 27](https://github.com/user-attachments/assets/92a41166-538a-4add-8786-aaaae90867d6)

I have delete all my media except (faces, lpr, export) folders.

I have config 

```
# ============================================================================
# Recording Configuration
# ============================================================================
record:
  enabled: true
  sync_recordings: true
```
![Screenshot 2026-01-09 at 18 01 55](https://github.com/user-attachments/assets/1b9e4177-4f1c-49c6-b7fa-bbd5d1a92256)


When I restart the data is still the same. I have this issue in 16 and 17 beta


Happy to provide logs if needed.


Is there a script to epport users.

I can then 
1. docker compose down frigate
2. delete frigate db
3.docker copose up ( to create the db)
4. docker compose down 
5 re import the users 
6 docker compose up


Or is you let me know which tables to export i can do that in sql 


I have tried Sync
