### DISCUSSION TITLE
[Config Support]: 0.14 config validation error

### DISCUSSION THREAD

**Discussion by lovelyjubley** [blakeblackshear/frigate#12886] [Config Support] [answered]
### Describe the problem you are having

Just updated to 0.14 and I'm getting config validation errors. Previous to the update 0.13 was working perfectly. I've checked the breaking changes and unless I've completely missed something I can't find any obvious issue.

### Version

0.14

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.232
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxxx

go2rtc:
  rtsp:
    username: xxxx
    password: xxxx
  streams:
    lean_to:
    - rtsp://xxxx:xxxx@192.168.1.227/554/stream1
    - ffmpeg:back#audio=aac
    lean_to_sub:
    - rtsp://xxxx:xxxx@192.168.1.227/554/stream2
    - ffmpeg:back#audio=aac
    outside_cam:
    - ffmpeg:http://192.168.1.148/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx#video=copy#audio=copy#audio=opus
    outside_cam_sub:
    - ffmpeg:http://192.168.1.148/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
    lola_cot:
    - rtsp://xxxx:xxxx@192.168.1.247/av_stream/ch0
    - ffmpeg:back#audio=aac
    lola_cot_sub:
    - rtsp://xxxx:xxxx@192.168.1.247/av_stream/ch1
    - ffmpeg:back#audio=aac

  webrtc:
    candidates:
    - 192.168.1.252:8555
    - stun:8555

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# Optional: ffmpeg configuration
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity

record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    days: 5
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
    - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: all
      # Optional: Per object retention days
      objects:
        person: 7

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: false
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 7

# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: bl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%d/%m/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)

# Required
cameras:
  # Required: name of the camera
  lola_cot:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
      - path: rtsp://127.0.0.1:8554/lola_cot
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/lola_cot_sub
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true
      max_disappeared: 25
      # Optional: Configuration for stationary object tracking
      stationary:
        interval: 50
        threshold: 50
    record:
      enabled: true
      retain:
        days: 1
      events:
        retain:
          default: 1

    motion:
      mask:
      - 0,360,640,360,640,0,0,0
  lean_to:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/lean_to
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/lean_to_sub
        roles:
        - detect

    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true
      max_disappeared: 25
      # Optional: Configuration for stationary object tracking
      stationary:
        interval: 50
        threshold: 50
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 7
    motion:
      mask:
      - 0,0,0,21,114,21,225,21,227,0
      - 515,277,566,239,613,91,526,53,440,22,359,30,358,150

    objects:
      filters:
        person:
          mask:
          - 355,27,456,0
  outside_cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/outside_cam
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/outside_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 4
      enabled: true
      max_disappeared: 25
      stationary:
        interval: 50
        threshold: 50
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 7
    motion:
      mask:
      - 96,101,180,355,249,349,271,114,330,113,274,0,0,0,0,211
    # Optional: Configuration for the jpg snapshots published via MQTT
      - 454,403,542,78,640,157,640,0,398,0,383,197
      - 640,309,640,480,522,480
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true


    objects:
      filters:
        person:
          mask:
          - 396,111,397,58
logger:
  # Optional: default log level (default: shown below)
  default: info
```

### Relevant log output

```shell
2024-08-09 16:22:35.182651640  [INFO] Preparing Frigate...
2024-08-09 16:22:35.191783371  [INFO] Starting NGINX...
2024-08-09 16:22:35.201495400  [INFO] Starting Frigate...
2024-08-09 16:22:35.484150109  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-08-09 16:22:35.523540833  [INFO] Starting go2rtc...
2024-08-09 16:22:35.628801769  16:22:35.628 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-08-09 16:22:35.628805983  16:22:35.628 INF config path=/dev/shm/go2rtc.yaml
2024-08-09 16:22:35.629241790  16:22:35.629 INF [api] listen addr=:1984
2024-08-09 16:22:35.629498005  16:22:35.629 INF [rtsp] listen addr=:8554
2024-08-09 16:22:35.630038462  16:22:35.629 INF [webrtc] listen addr=:8555
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
2024-08-09 16:22:36.296564677  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
2024-08-09 16:22:36.393171470  127.0.0.1 - - [09/Aug/2024:16:22:36 +0100] "" 400 0 "-" "-" "-"
2024-08-09 16:22:36.517035793  [2024-08-09 16:22:36] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
2024-08-09 16:22:36.517170944  [2024-08-09 16:22:36] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-08-09 16:22:36.557813698  [2024-08-09 16:22:36] frigate.util.config            INFO    : frigate config does not need migration...
2024-08-09 16:22:36.576678433  *************************************************************
2024-08-09 16:22:36.576682022  *************************************************************
2024-08-09 16:22:36.576685983  ***    Your config file is not valid!                     ***
2024-08-09 16:22:36.576688485  ***    Please check the docs at                           ***
2024-08-09 16:22:36.576690116  ***    https://docs.frigate.video/configuration/index     ***
2024-08-09 16:22:36.576713811  *************************************************************
2024-08-09 16:22:36.576715471  *************************************************************
2024-08-09 16:22:36.576717362  ***    Config Validation Errors                           ***
2024-08-09 16:22:36.576718786  *************************************************************
2024-08-09 16:22:36.576732340  mqtt.password: Input should be a valid string
2024-08-09 16:22:36.576733891  record.events.required_zones: Extra inputs are not permitted
2024-08-09 16:22:36.576735290  *************************************************************
2024-08-09 16:22:36.576736672  ***    End Config Validation Errors                       ***
2024-08-09 16:22:36.576737999  *************************************************************
2024-08-09 16:22:37.738760086  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
```

### Operating system

HassOS

### Install method

Docker Compose

### Object Detector

OpenVino
