### DISCUSSION TITLE
OpenVINO not working on 0.14

### DISCUSSION THREAD

**Discussion by mitchplze** [blakeblackshear/frigate#12889] [Detector Support] [answered]
### Describe the problem you are having

Since upgrading to 0.14, the OpenVINO detector does not initialize, which causes the whole app to stop. This worked fine for months in the previous version. I reviewed the [doc page](https://docs.frigate.video/configuration/object_detectors/#openvino-detector) but could not find anything relevant.

### Version

0.14

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi

ui:
  # use_experimental: True
  time_format: 24hour

telemetry:
  stats:
    network_bandwidth: true

birdseye:
  enabled: true
  mode: continuous
  # width: 1512
  # height: 982
  # layout:
    # max_cameras: 6
    # scaling_factor: 1.0

detect:
  enabled: true
  width: 1280 # 1920
  height: 720 # 1080
  stationary:
    max_frames:
      default: 300

objects:
  track:
    - person
    - dog
    - face
  #  - tv
  # - door
  # - bed
  # - laptop

snapshots:
  enabled: true
  retain:
    default: 30

record:
  #sync_recordings: True
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  1-entry:
    enabled: true
    ffmpeg:
      inputs:
        - path: '{FRIGATE_CAM1}'
          roles:
            - detect
            - audio
            - record

  2-living-room:
    enabled: true
    ffmpeg:
      inputs:
        - path: '{FRIGATE_CAM2_HQ}'
          roles:
            - detect
            - audio
            - record

  3-kitchen:
    enabled: true
    ffmpeg:
      inputs:
        - path: '{FRIGATE_CAM3}'
          roles:
            - detect
            - audio
            - record

  4-library:
    enabled: true
    ffmpeg:
      # hwaccel_args: preset-vaapi
      # hwaccel_args: preset-vaapi
      inputs:
        - path: '{FRIGATE_CAM4_HQ}'
          roles:
            - detect
            - audio
            - record

  5-rack:
    enabled: true
    ffmpeg:
      inputs:
        - path: '{FRIGATE_CAM5}'
          roles:
            - detect
            - audio
            - record

  6-bedroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: '{FRIGATE_CAM6}'
          roles:
            - detect
            - audio
            - record


# timestamp_style: # This timestamp only applies to snapshots and the debug video stream.
#   position: "br"
#   # format: "%Y-%m-%d %H:%M"
#   effect: "shadow" # solid or shadow

# live:
#   height: 1080 # default, or 720, 1080

mqtt:
  enabled: false
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    # image: ghcr.io/blakeblackshear/frigate:0.14.0-rc2
    # image: ghcr.io/blakeblackshear/frigate:0.14.0-beta1
    shm_size: 256mb # update for your cameras based on calculation above
    env_file: .env
    cap_add:
      - CAP_PERFMON
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    #   - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11  # For Raspberry Pi 4B
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
networks: {}
```

### Relevant log output

```shell
root@rgnvr:/srv/frigate# docker compose up
[+] Running 2/2
 ✔ Network frigate_default  Created                                                                                                0.1s
 ✔ Container frigate        Created                                                                                                2.7s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2024-08-09 17:35:19.640469644  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-09 17:35:19.642807387  [INFO] Preparing Frigate...
frigate  | 2024-08-09 17:35:19.645185361  [INFO] Starting NGINX...
frigate  | 2024-08-09 17:35:19.655179667  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2024-08-09 17:35:19.657118114  [INFO] Starting Frigate...
frigate  | 2024-08-09 17:35:20.027099095  [INFO] Starting go2rtc...
frigate  | 2024-08-09 17:35:20.122798025  10:35:20.122 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-08-09 17:35:20.123346090  10:35:20.123 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-08-09 17:35:20.124226123  10:35:20.124 INF [api] listen addr=:1984
frigate  | 2024-08-09 17:35:20.125173764  10:35:20.125 INF [rtsp] listen addr=:8554
frigate  | 2024-08-09 17:35:20.126044577  10:35:20.125 INF [webrtc] listen addr=:8555/tcp
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-08-09 17:35:21.020175950  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-08-09 17:35:21.030673831  [2024-08-09 10:35:21] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
frigate  | 2024-08-09 17:35:21.031116641  [2024-08-09 10:35:21] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-08-09 17:35:21.051380229  [2024-08-09 10:35:21] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-08-09 17:35:21.080562457  127.0.0.1 - - [09/Aug/2024:10:35:21 -0700] "" 400 0 "-" "-" "-"
frigate  | 2024-08-09 17:35:21.096817427  [2024-08-09 10:35:21] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-08-09 17:35:21.097496658  [2024-08-09 10:35:21] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-08-09 17:35:21.111743757  [2024-08-09 10:35:21] frigate.app                    INFO    : Recording process started: 341
frigate  | 2024-08-09 17:35:21.111753884  [2024-08-09 10:35:21] frigate.app                    INFO    : Recording process started: 345
frigate  | 2024-08-09 17:35:21.114185358  [2024-08-09 10:35:21] frigate.app                    INFO    : go2rtc process pid: 97
frigate  | 2024-08-09 17:35:21.142531416  [2024-08-09 10:35:21] detector.ov                    INFO    : Starting detection process: 369
frigate  | 2024-08-09 17:35:21.143300956  [2024-08-09 10:35:21] frigate.app                    INFO    : Output process started: 371
frigate  | 2024-08-09 17:35:21.183816118  Process detector:ov:
frigate  | 2024-08-09 17:35:21.187049609  Traceback (most recent call last):
frigate  | 2024-08-09 17:35:21.187057362    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-08-09 17:35:21.187060644      self.run()
frigate  | 2024-08-09 17:35:21.187064416    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-08-09 17:35:21.187070981      self._target(*self._args, **self._kwargs)
frigate  | 2024-08-09 17:35:21.187074823    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2024-08-09 17:35:21.187099617      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-08-09 17:35:21.187103389    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2024-08-09 17:35:21.187106671      self.detect_api = create_detector(detector_config)
frigate  | 2024-08-09 17:35:21.187110024    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-08-09 17:35:21.187137961      return api(detector_config)
frigate  | 2024-08-09 17:35:21.187141244    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 43, in __init__
frigate  | 2024-08-09 17:35:21.187144527      self.interpreter = self.ov_core.compile_model(
frigate  | 2024-08-09 17:35:21.187147949    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 521, in compile_model
frigate  | 2024-08-09 17:35:21.187161359      super().compile_model(model, device_name, {} if config is None else config),
frigate  | 2024-08-09 17:35:21.187164712  RuntimeError: Exception from src/inference/src/cpp/core.cpp:123:
frigate  | 2024-08-09 17:35:21.187167505  Exception from src/inference/src/dev/plugin.cpp:59:
frigate  | 2024-08-09 17:35:21.187170858  Check 'contexts.count(device_id)' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:204:
frigate  | 2024-08-09 17:35:21.187174141  [GPU] Context was not initialized for 0 device
frigate  | 2024-08-09 17:35:21.187177493
frigate  | 2024-08-09 17:35:21.187180357
frigate  | 2024-08-09 17:35:21.187183290
frigate  | 2024-08-09 17:35:21.650317044  [2024-08-09 10:35:21] frigate.app                    INFO    : Camera processor started for 1-entry: 422
frigate  | 2024-08-09 17:35:21.650420483  [2024-08-09 10:35:21] frigate.app                    INFO    : Camera processor started for 2-living-room: 430
frigate  | 2024-08-09 17:35:21.670065044  [2024-08-09 10:35:21] frigate.app                    INFO    : Camera processor started for 3-kitchen: 438
frigate  | 2024-08-09 17:35:21.671107813  [2024-08-09 10:35:21] frigate.app                    INFO    : Camera processor started for 4-library: 446
frigate  | 2024-08-09 17:35:21.681514966  [2024-08-09 10:35:21] frigate.app                    INFO    : Camera processor started for 5-rack: 454
frigate  | 2024-08-09 17:35:21.691812535  [2024-08-09 10:35:21] frigate.app                    INFO    : Camera processor started for 6-bedroom: 462
frigate  | 2024-08-09 17:35:21.701884996  [2024-08-09 10:35:21] frigate.app                    INFO    : Capture process started for 1-entry: 470
frigate  | 2024-08-09 17:35:21.712555670  [2024-08-09 10:35:21] frigate.app                    INFO    : Capture process started for 2-living-room: 473
frigate  | 2024-08-09 17:35:21.736106529  [2024-08-09 10:35:21] frigate.app                    INFO    : Capture process started for 3-kitchen: 477
frigate  | 2024-08-09 17:35:21.744377019  [2024-08-09 10:35:21] frigate.app                    INFO    : Capture process started for 4-library: 482
frigate  | 2024-08-09 17:35:21.745301891  [2024-08-09 10:35:21] frigate.app                    INFO    : Capture process started for 5-rack: 487
frigate  | 2024-08-09 17:35:21.759373193  [2024-08-09 10:35:21] frigate.app                    INFO    : Capture process started for 6-bedroom: 492
frigate  | 2024-08-09 17:35:29.640536014  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-08-09 17:35:42.086286186  [2024-08-09 10:35:42] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2024-08-09 17:35:42.099660446  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-08-09 17:35:42.101366172  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | s6-rc: info: service certsync successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service certsync-log: stopping
frigate  | s6-rc: info: service certsync-log successfully stopped
frigate  | 2024-08-09 17:35:42.160215276  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | 2024-08-09 17:35:42.166364678  [2024-08-09 10:35:42] frigate.app                    INFO    : Flask has exited...
frigate  | 2024-08-09 17:35:42.166450726  [2024-08-09 10:35:42] frigate.app                    INFO    : Stopping...
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2024-08-09 17:35:42.169810914  [2024-08-09 10:35:42] frigate.stats.emitter          INFO    : Exiting stats emitter...
frigate  | 2024-08-09 17:35:42.169861760  [2024-08-09 10:35:42] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate  | 2024-08-09 17:35:42.170688572  [2024-08-09 10:35:42] frigate.watchdog               INFO    : Exiting watchdog...
frigate  | 2024-08-09 17:35:42.170695696  [2024-08-09 10:35:42] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate  | 2024-08-09 17:35:42.170698490  [2024-08-09 10:35:42] frigate.storage                INFO    : Exiting storage maintainer...
frigate  | 2024-08-09 17:35:42.170702750  [2024-08-09 10:35:42] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate  | 2024-08-09 17:35:42.191577052  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for capture process for 1-entry to stop
frigate  | 2024-08-09 17:35:42.192814546  [2024-08-09 10:35:42] watchdog.1-entry               INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-08-09 17:35:42.192848839  [2024-08-09 10:35:42] watchdog.1-entry               INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-08-09 17:35:42.261242175  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for capture process for 2-living-room to stop
frigate  | 2024-08-09 17:35:42.262732364  [2024-08-09 10:35:42] watchdog.2-living-room         INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-08-09 17:35:42.262881480  [2024-08-09 10:35:42] watchdog.2-living-room         INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-08-09 17:35:42.495709947  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for capture process for 3-kitchen to stop
frigate  | 2024-08-09 17:35:42.496878574  [2024-08-09 10:35:42] watchdog.3-kitchen             INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-08-09 17:35:42.497262925  [2024-08-09 10:35:42] watchdog.3-kitchen             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-08-09 17:35:42.539474036  [2024-08-09 10:35:42] frigate.events.maintainer      INFO    : Exiting event processor...
frigate  | 2024-08-09 17:35:42.546161794  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for capture process for 4-library to stop
frigate  | 2024-08-09 17:35:42.547220697  [2024-08-09 10:35:42] watchdog.4-library             INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-08-09 17:35:42.547720080  [2024-08-09 10:35:42] watchdog.4-library             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-08-09 17:35:42.610028271  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for capture process for 5-rack to stop
frigate  | 2024-08-09 17:35:42.610902157  [2024-08-09 10:35:42] watchdog.5-rack                INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-08-09 17:35:42.611060423  [2024-08-09 10:35:42] watchdog.5-rack                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-08-09 17:35:42.655111361  [2024-08-09 10:35:42] frigate.object_processing      INFO    : Exiting object processor...
frigate  | 2024-08-09 17:35:42.680419491  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for capture process for 6-bedroom to stop
frigate  | 2024-08-09 17:35:42.681335772  [2024-08-09 10:35:42] watchdog.6-bedroom             INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-08-09 17:35:42.681531335  [2024-08-09 10:35:42] watchdog.6-bedroom             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-08-09 17:35:42.740866831  [2024-08-09 10:35:42] frigate.app                    INFO    : Waiting for process for 1-entry to stop
frigate  | 2024-08-09 17:35:42.995188836  [2024-08-09 10:35:42] frigate.video                  INFO    : 1-entry: emptying frame queue
frigate  | 2024-08-09 17:35:42.995243594  [2024-08-09 10:35:42] frigate.video                  INFO    : 1-entry: exiting subprocess
frigate  | 2024-08-09 17:35:43.013671755  [2024-08-09 10:35:43] frigate.app                    INFO    : Closing frame queue for 1-entry
frigate  | 2024-08-09 17:35:43.514811949  [2024-08-09 10:35:43] frigate.app                    INFO    : Waiting for process for 2-living-room to stop
frigate  | 2024-08-09 17:35:44.325189088  [2024-08-09 10:35:44] frigate.video                  INFO    : 2-living-room: emptying frame queue
frigate  | 2024-08-09 17:35:44.325227083  [2024-08-09 10:35:44] frigate.video                  INFO    : 2-living-room: exiting subprocess
frigate  | 2024-08-09 17:35:44.345815584  [2024-08-09 10:35:44] frigate.app                    INFO    : Closing frame queue for 2-living-room
frigate  | 2024-08-09 17:35:44.847095397  [2024-08-09 10:35:44] frigate.app                    INFO    : Waiting for process for 3-kitchen to stop
frigate  | 2024-08-09 17:35:47.379598182  [2024-08-09 10:35:47] frigate.video                  INFO    : 3-kitchen: emptying frame queue
frigate  | 2024-08-09 17:35:47.379637364  [2024-08-09 10:35:47] frigate.video                  INFO    : 3-kitchen: exiting subprocess
frigate  | 2024-08-09 17:35:47.398890730  [2024-08-09 10:35:47] frigate.app                    INFO    : Closing frame queue for 3-kitchen
frigate  | 2024-08-09 17:35:47.900094623  [2024-08-09 10:35:47] frigate.app                    INFO    : Waiting for process for 4-library to stop
frigate  | 2024-08-09 17:35:49.329001524  [2024-08-09 10:35:49] frigate.video                  INFO    : 4-library: emptying frame queue
frigate  | 2024-08-09 17:35:49.329176972  [2024-08-09 10:35:49] frigate.video                  INFO    : 4-library: exiting subprocess
frigate  | 2024-08-09 17:35:49.348476295  [2024-08-09 10:35:49] frigate.app                    INFO    : Closing frame queue for 4-library
frigate  | 2024-08-09 17:35:49.849487489  [2024-08-09 10:35:49] frigate.app                    INFO    : Waiting for process for 5-rack to stop
frigate  | 2024-08-09 17:35:54.262627523  [2024-08-09 10:35:54] frigate.video                  INFO    : 5-rack: emptying frame queue
frigate  | 2024-08-09 17:35:54.263080809  [2024-08-09 10:35:54] frigate.video                  INFO    : 5-rack: exiting subprocess
frigate  | 2024-08-09 17:35:54.281315223  [2024-08-09 10:35:54] frigate.app                    INFO    : Closing frame queue for 5-rack
frigate  | 2024-08-09 17:35:54.782867637  [2024-08-09 10:35:54] frigate.app                    INFO    : Waiting for process for 6-bedroom to stop
frigate  | 2024-08-09 17:35:57.395879222  [2024-08-09 10:35:57] frigate.video                  INFO    : 6-bedroom: emptying frame queue
frigate  | 2024-08-09 17:35:57.395886905  [2024-08-09 10:35:57] frigate.video                  INFO    : 6-bedroom: exiting subprocess
frigate  | 2024-08-09 17:35:57.414830304  [2024-08-09 10:35:57] frigate.app                    INFO    : Closing frame queue for 6-bedroom
frigate  | 2024-08-09 17:35:58.417788799  [2024-08-09 10:35:58] frigate.app                    INFO    : Detection queue closed
frigate  | 2024-08-09 17:35:58.919962941  [2024-08-09 10:35:58] frigate.app                    INFO    : Detected frames queue closed
frigate  | 2024-08-09 17:35:59.420792309  [2024-08-09 10:35:59] frigate.app                    INFO    : Timeline queue closed
frigate  | 2024-08-09 17:36:00.835031520  [2024-08-09 10:36:00] frigate.output.output          INFO    : exiting output process...
frigate  | 2024-08-09 17:36:01.152168977  [2024-08-09 10:36:01] frigate.record.maintainer      INFO    : Exiting recording maintenance...
frigate  | 2024-08-09 17:36:01.297223688  [2024-08-09 10:36:01] frigate.review.maintainer      INFO    : Exiting review maintainer...
frigate  | 2024-08-09 17:36:01.670518046  [2024-08-09 10:36:01] frigate.comms.ws               INFO    : Exiting websocket client...
frigate  | 2024-08-09 17:36:02.167020098  [2024-08-09 10:36:02] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate  | 2024-08-09 17:36:03.224879805  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 24 leaked shared_memory objects to clean up at shutdown
frigate  | 2024-08-09 17:36:03.224888745    warnings.warn('resource_tracker: There appear to be %d '
frigate  | 2024-08-09 17:36:03.230341734  [INFO] Service Frigate exited with code 0 (by signal 0)
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | 2024-08-09 17:36:03.233807386  exit with signal: terminated
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2024-08-09 17:36:03.242282797  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino
