### DISCUSSION TITLE
[Support]:  Camera Group Icon not showing

### DISCUSSION THREAD

**Discussion by hagak** [blakeblackshear/frigate#12880] [General Support] [answered]
### Describe the problem you are having

I am creating my camera group via config not UI.  The icon shows as blank however the rest of the camera group functions properly.  I suspect my icon name is incorrect however using the one in the docs is also not working.

Is there a list of icons we can access, is it using MDI icons?

### Version

v0.14.0

### Frigate config file

```yaml
camera_groups:
  # Required: Name of camera group
  outside:
    # Required: list of cameras in the group
    cameras:
      - dooryardcam
      - backyardcam
      - backyardnorthcam
      - sideyardcam
      - rivercam
    # Required: icon used for group
    icon: car
    # Required: index of this group
    order: 0
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

N/A
