### DISCUSSION TITLE
[Camera Support]: Person detection active even if camera is switch to privacy mode

### DISCUSSION THREAD

**Discussion by runningman84** [blakeblackshear/frigate#12888] [Camera Support]
### Describe the problem you are having

![image](https://github.com/user-attachments/assets/dd0ae6a7-a0ea-4de6-89e8-aee916983554)

### Steps to reproduce

Use the privacy mode of a tapo camera

### Version

0.14.0

### Frigate config file

```yaml
# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
mqtt:
  host: mosquitto
  topic_prefix: frigate
  # user: ${SECRET_MQTT_USERNAME}
  # password: ${SECRET_MQTT_PASSWORD}
database:
  path: /config/frigate.db
detectors:
  coral:
    type: edgetpu
    device: pci:0
record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 7
      mode: motion
      objects:
        person: 30
# Global objects configuration
objects:
  track:
    - person
    - face
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7
# Global ffmpeg configuration
ffmpeg:
  hwaccel_args: preset-vaapi
# Birdseye
birdseye:
  enabled: false
# Specify camera's
cameras:
  living_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://go2rtc:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://go2rtc:8554/living_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: living_room_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0,0.062,0.312,0.062,0.312,0,0,0
        - 0,0.794,0.192,0.311,0.171,0.094,0,0.089
        - 0.658,0.429,0.676,0.282,0.812,0.37,0.772,0.554
        - 0.774,1,1,0.633,0.999,0.997
    snapshots:
      enabled: true # <----- Enable snapshots
    objects:
      mask:
        - 0.674,0.261,0.647,0.444,0.773,0.573,0.824,0.353
        - 0.002,0.81,0.197,0.325,0.167,0.08,0.002,0.072
  master_bedroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://go2rtc:8554/master_bedroom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://go2rtc:8554/master_bedroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: master_bedroom_sub
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 0,25,230,25,230,0,0,0
    snapshots:
      enabled: true # <----- Enable snapshots
  corridor_downstairs:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://go2rtc:8554/corridor_downstairs
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://go2rtc:8554/corridor_downstairs_sub1
          input_args: preset-rtsp-restream
          roles:
            - detect
        # - path: rtsp://go2rtc:8554/corridor_downstairs_sub2
        #   input_args: preset-rtsp-restream
    live:
      stream_name: corridor_downstairs_sub1
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 480,303,509,151,482,134,470,83,393,86,382,143,454,142,435,236
        - 100,186,124,144,161,121,190,128,205,228,173,312,131,314
        - 0,360,85,360,41,70,0,88
        - 0,25,120,25,120,0,0,0
    objects:
      filters:
        object_0:
          mask:
            - 480,303,509,151,482,134,470,83,393,86,382,143,454,142,435,236
        object_1:
          mask:
            - 100,186,124,144,161,121,190,128,205,228,173,312,131,314
        object_2:
          mask:
            - 0,360,85,360,41,70,0,88
version: 0.14
```

### Relevant log output

```shell
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

tapo cc125
