### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by clowncracker** [blakeblackshear/frigate#12892] [Config Support]
### Describe the problem you are having

I'm trying to get only speech to show up as alerts and to have no detections set up.  Right now speech and people are showing up as alerts.

### Version

0.14.0

### Frigate config file

```yaml
This is the config for the camera specifically:

  office:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/office?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - record
    audio:
      enabled: true
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        objects: []
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 465,237,173,300,292,945,549,908
    snapshots:
      enabled: false
    review:
      alerts:
        labels:
          - speech
      detections:
        labels: []
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

Coral
