### DISCUSSION TITLE
[Bug]: Regression with MJPG Camera - maybe user-agent

### DISCUSSION THREAD

**Discussion by grigio** [blakeblackshear/frigate#12899] [Report a Bug] [answered]
### Describe the problem you are having

I think it is related to #4597 

![image](https://github.com/user-attachments/assets/410b8fe7-e1dc-4dc0-8a50-2099066b924f)

I rolled back from `v0.1.4` to `v0.13.2`

This config stopped to work on latest stable `v0.14.x` but it is working on `v.0.13.x`, honestly i don't know if it was optimal but it worked fine for my old security camera

```
  portoncino:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://admin:secretpassword@192.168.1.239:81/videostream.cgi
          roles:
            - rtmp 
```

VLC can open it and it says that it is a stream MJPG

![image](https://github.com/user-attachments/assets/ff4fffbb-4aa7-4c94-9e40-b7d14913d77b)

### Steps to reproduce

.

### Version

v0.14

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

.

**Comment by NickM-27** [comment]
this config is not valid, rtmp is not a valid role anymore

**Reply by grigio** [reply]
I tried to change it but it doesn't seem related to that

```
error
2024-08-09 22:34:01
frigate.video
portoncino: ffmpeg process is not running. exiting capture thread...
error
2024-08-09 22:34:21
watchdog.portoncino
Ffmpeg process crashed unexpectedly for portoncino.
error
2024-08-09 22:34:21
watchdog.portoncino
The following ffmpeg logs include the last 100 lines prior to exit.
error
2024-08-09 22:34:21
ffmpeg.portoncino.detect
Option user_agent not found.
error
2024-08-09 22:34:21
frigate.video
portoncino: Unable to read frames from ffmpeg process.
error
2024-08-09 22:34:21
frigate.video
portoncino: ffmpeg process is not running. exiting capture thread...
```

**Reply by NickM-27** [reply]
you should show your full config.

**Reply by grigio** [reply]
```yaml
mqtt:
  enabled: false
#  host: mqtt

detectors:
  coral1:
    type: edgetpu
    device: pci:0

cameras:


  portoncino:
    ffmpeg:
      # hwaccel_args: preset-vaapi # amd
      input_args: preset-http-jpeg-generic
      # input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict
      #   experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      # output_args:
      #   record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
      #     1 -strftime 1 -c:v libx264 -an
      inputs:
        - path: http://admin:password@192.168.1.239:81/videostream.cgi
          # input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - record
            - detect
            # - rtmp



record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 1
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 2
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 2
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      # objects:
      #   person: 15

telemetry:
  version_check: false

```
