### DISCUSSION TITLE
`frigate_token` does not have a proper SameSite attribute value when using Firefox [Bug]:

### DISCUSSION THREAD

**Discussion by DerVerruckteFuchs** [blakeblackshear/frigate#12913] [Report a Bug]
### Describe the problem you are having

When using Firefox to access my frigate deployment, I get the following warning. Also, Firefox is not letting me log in.
`
Cookie “frigate_token” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

Chromium does not give me a warning, and I can log in fine. I assume this is from Firefox have more strict default settings for security reasons.

This occurs when I try to login with a URL when using an Nginx reverse proxy. When accessing my frigate deployment directly via IP address, there is no issue.

My Nginx reverse proxy config: [frigate-reverse-proxy.txt](https://github.com/user-attachments/files/16568507/frigate-reverse-proxy.txt)

### Steps to reproduce

- Open frigate URL in Firefox
- Attempt to log in

### Version

0.14.0

### Frigate config file

```yaml
database:
  path: /db/frigate.db
mqtt: # If you have a MQTT server then update this section, if not delete it.
  enabled: false
#  host: IP ADDRESS OF MQTT SERVER
#  user: MQTT USERNAME
#  password: MQTT PASSWORD
detectors:
#    coral:
#        type: edgetpu
#        device: usb
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# go2rtc has transcoding(?) issues
# maybe swannview/hikvision cameras don't put out a reliable enough stream
# i.e. something non-standard is happening with the video codec?
# or maybe old camera age?
#go2rtc:
#  streams:
#    camera_1_main:
#      - rtsp://[CAMERA_1_IP]:554/h264Preview_01_main
#    camera_1_sub:
#      - rtsp://[CAMERA_1_IP]:554/h264Preview_01_sub
#    camera_2_main:
#      - rtsp://[CAMERA_2_IP]:554/h264Preview_01_main
#    camera_2_sub:
#      - rtsp://[CAMERA_2_IP]:554/h264Preview_01_sub
#    camera_3_main:
#      - rtsp://[CAMERA_3_IP]:554/h264Preview_01_main
#    camera_3_sub:
#      - rtsp://[CAMERA_3_IP]:554/h264Preview_01_sub
#    camera_4_main:
#      - rtsp://[CAMERA_4_IP]:554/h264Preview_01_main
#    camera_4_sub:
#      - rtsp://[CAMERA_4_IP]:554/h264Preview_01_sub
#  webrtc:
#    candidates:
#      - 10.20.20.95:8555
#      - stun:8555

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy
  hwaccel_args: -c:v h264_qsv
       #- -hwaccel
       # - vaapi
       # - -hwaccel_device
       # - /dev/dri/renderD128
       # - -hwaccel_output_format
       # - yuv420p
objects: # Object to detect - https://docs.frigate.video/configuration/objects
  track:
    - person
    - bicycle
    - motorcycle
record: # how long to record before and after motion
  events:
    pre_capture: 7
    post_capture: 10
birdseye:
  enabled: true
  mode: continuous
cameras:
  #    CAMERA_NAME: # <------ Name the camera
  #        ffmpeg:
  #            inputs:
  #                - path: rtsp://USERNAME:PASSWORD@IPADDRESS:PORT/URL/FOR/STREAM/ # Update with your camera info (Normally the lower res stream, 1280*720 would be a good detection res)
  #                  roles:
  #                    - detect
  #                - path: rtsp://USERNAME:PASSWORD@IPADDRESS:PORT/URL/FOR/STREAM/ # Update with your camera info (Normally the higher res stream, used for actual recording)
  #                  roles:
  #                    - record
  #                   # - detect
  #        detect:
  #            width: 1280 # <---- update for your camera's resolution
  #            height: 720 # <---- update for your camera's resolution
  #            #width: 2688
  #            #height: 1520
  #        record: # what you want Frigate to record
  #            enabled: True
  #           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
  #           #     days: 1
  #           #     mode: all
  #            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
  #                retain:
  #                    mode: active_objects
  #                    default: 10
  #        snapshots:
  #            enabled: True
  #            retain:
  #                default: 10
  camera_1:
    birdseye:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      #hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://[CAMERA_1_IP]:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[CAMERA_1_IP]:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640       # <---- update for your camera's resolution
      height: 360       # <---- update for your camera's resolution
      fps: 4
    record:     # what you want Frigate to record
      enabled: true
      retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
        days: 365
        mode: active_objects
      events:       # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 30
    snapshots:
      enabled: true
      retain:
        default: 10
  camera_2:
    birdseye:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      #hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://[CAMERA_2_IP]:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[CAMERA_2_IP]:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640       # <---- update for your camera's resolution
      height: 360       # <---- update for your camera's resolution
      fps: 4
    record:     # what you want Frigate to record
      enabled: true
      retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
        days: 365
        mode: active_objects
      events:       # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 10
    snapshots:
      enabled: true
      retain:
        default: 10
  camera_3:
    birdseye:
      order: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      #hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://[CAMERA_3_IP]:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[CAMERA_3_IP]:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640       # <---- update for your camera's resolution
      height: 360       # <---- update for your camera's resolution
      fps: 4
    record:     # what you want Frigate to record
      enabled: true
      retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
        days: 365
        mode: active_objects
      events:       # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 10
    snapshots:
      enabled: true
      retain:
        default: 10
  camera_4:
    birdseye:
      order: 4
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      #hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://[CAMERA_4_IP]:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[CAMERA_4_IP]:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640       # <---- update for your camera's resolution
      height: 360       # <---- update for your camera's resolution
      fps: 4
    record:     # what you want Frigate to record
      enabled: true
      retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
        days: 365
        mode: active_objects
      events:       # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 10
    snapshots:
      enabled: true
      retain:
        default: 10
auth:
  failed_login_rate_limit: "1/second;5/minute;20/hour"
  trusted_proxies:
    - [IPV4_SUBNET]/24
    - [IPV6_SUBNET]::/64
tls:
  enabled: False # the nginx reverse proxy will handle tls
version: 0.14
```

### Relevant log output

```shell
2024-08-10 04:56:27.971607351  172.19.0.1 - - [10/Aug/2024:04:56:27 +0000] "POST /api/login HTTP/1.1" 200 3 "https://frigate.billhei.org/login" "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0" "[My IPv6 Address]"

2024-08-10 04:56:28.042251177  172.19.0.1 - - [10/Aug/2024:04:56:28 +0000] "GET /login HTTP/1.1" 200 2651 "https://frigate.billhei.org/login" "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0" "[My IPv6 Address]"

2024-08-10 04:56:28.318271329  172.19.0.1 - - [10/Aug/2024:04:56:28 +0000] "GET /images/apple-touch-icon.png HTTP/1.1" 200 4042 "https://frigate.billhei.org/login" "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0" "[My IPv6 Address]"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Swannview
