### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by jubjubrsx** [blakeblackshear/frigate#12910] [Config Support]
### Describe the problem you are having

having a problem with my config not sure whats going on.  by the output says extra inputs are not permitted? but not sure what are extra.

note: these are ankee C800 camera's used config from documentation.

### Version

14

### Frigate config file

```yaml
# ~/docker/frigate/config.yml
# yaml-language-server: $schema=http://192.168.150.3:5000/api/config/schema.json

ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 192.168.10.12
  port: 1883
  user: mqtt
  password: pooopypants!!!
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
  enabled: true

detectors:
  coral1:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  expire_interval: 10

logger:
  default: info

rtmp:
  enabled: false

live:
  height: 720
  quality: 1

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 1
  mode: continuous

#############################################################
go2rtc:
  streams:

    Front_Porch:
      - rtsp://admin:pooopypants!!@192.168.150.10:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Front_Porch_sub:
      - rtsp://admin:pooopypants!!@192.168.150.10:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Back_Porch:
      - rtsp://admin:pooopypants!!@192.168.150.13:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Back_Porch_sub:
      - rtsp://admin:pooopypants!!@192.168.150.13:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Air_Conditioner:
      - rtsp://admin:pooopypants!!@192.168.150.14:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Air_Conditioner_sub:
      - rtsp://admin:pooopypants!!@192.168.150.14:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Carport:
      - rtsp://admin:pooopypants!!@192.168.150.12:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Carport_sub:
      - rtsp://admin:pooopypants!!@192.168.150.12:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Driveway:
      - rtsp://admin:pooopypants!!@192.168.150.11:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Driveway_sub:
      - rtsp://admin:pooopypants!!@192.168.150.11:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Backyard:
      - rtsp://admin:pooopypants!!@192.168.150.15:554/Streaming/Channels/101
    Backyard_sub:
      - rtsp://admin:pooopypants!!@192.168.150.15:554/Streaming/Channels/102 

    webrtc:
      candidates:
        - 192.168.150.3:8555
        #- stun:8555
##############################################################

cameras:

 Driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        #H.264 re-encode -- record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
        - dog
      filters:
        car:
          mask:
            - 242,28,548,74,544,0,177,0,42,0,0,54
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30

 Back_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        #H.264 re-encode -- record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Back_Porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Back_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30


 Carport: # <------ Name the camera
    ffmpeg:
      output_args:
        #H.264 re-encode -- record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Carport
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Carport_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30

 Air_Conditioner: # <------ Name the camera
    ffmpeg:
      output_args:
        #H.264 re-encode -- record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Air_Conditioner
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Air_Conditioner_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
          mask:
           - 927,54,933,104,881,87,887,49
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30


 Front_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        #H.264 re-encode -- record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Front_Porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Front_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - bicycle
        - cat
        - dog
        - car
      filters:
        car:
          mask:
            - 605,0,514,0,511,60,640,101
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30

 Backyard: # <------ Name the camera
    ffmpeg:
      output_args:
        #H.264 re-encode -- record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.7
          threshold: 0.8
          min_area: 700
          mask:
           - 927,54,933,104,881,87,887,49
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30


 247Front_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 10 
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Front_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false


 247Driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 10 
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
    detect:
        enabled: false
    birdseye:
      enabled: false

 247Carport: # <------ Name the camera
    ffmpeg:
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 10
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Carport_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false

 247Back_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 10 
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Back_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false

 247Air_Conditioner: # <------ Name the camera
    ffmpeg:
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 10 
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Air_Conditioner_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false

 247Backyard: # <------ Name the camera
    ffmpeg:
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 10 
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 14
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false
```

### Relevant log output

```shell
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 33 validation errors for FrigateConfig
ui.use_experimental
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
ui.live_mode
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;mse&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Driveway.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Driveway.ffmpeg.inputs.0.roles.1
  Input should be &#39;audio&#39;, &#39;record&#39; or &#39;detect&#39; [type=enum, input_value=&#39;rtmp&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
cameras.Driveway.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Back_Porch.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Back_Porch.ffmpeg.inputs.0.roles.1
  Input should be &#39;audio&#39;, &#39;record&#39; or &#39;detect&#39; [type=enum, input_value=&#39;rtmp&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
cameras.Back_Porch.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Carport.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Carport.ffmpeg.inputs.0.roles.1
  Input should be &#39;audio&#39;, &#39;record&#39; or &#39;detect&#39; [type=enum, input_value=&#39;rtmp&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
cameras.Carport.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Air_Conditioner.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Air_Conditioner.ffmpeg.inputs.0.roles.1
  Input should be &#39;audio&#39;, &#39;record&#39; or &#39;detect&#39; [type=enum, input_value=&#39;rtmp&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
cameras.Air_Conditioner.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Front_Porch.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Front_Porch.ffmpeg.inputs.0.roles.1
  Input should be &#39;audio&#39;, &#39;record&#39; or &#39;detect&#39; [type=enum, input_value=&#39;rtmp&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
cameras.Front_Porch.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Backyard.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.Backyard.ffmpeg.inputs.0.roles.1
  Input should be &#39;audio&#39;, &#39;record&#39; or &#39;detect&#39; [type=enum, input_value=&#39;rtmp&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum
cameras.Backyard.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Front_Porch.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Front_Porch.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Driveway.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Driveway.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Carport.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Carport.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Back_Porch.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Back_Porch.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Air_Conditioner.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Air_Conditioner.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Backyard.ffmpeg.output_args.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value=&#39;-c:v copy -c:a aac -f flv&#39;, input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
cameras.247Backyard.rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
rtmp
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;enabled&#39;: False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
```

### Operating system

Proxmox

### Install method

Docker CLI

### Object Detector

Coral
