### DISCUSSION TITLE
[Config Support]: required_zones under record...

### DISCUSSION THREAD

**Discussion by lee-costa** [blakeblackshear/frigate#12928] [Config Support] [answered]
### Describe the problem you are having

So I just finished upgrading but my instance won't start which I believe is due to the required_zone: part.

            record:
                enabled: True
                retain:
                days: 10
                mode: motion
                events:
                retain:
                    default: 10
                    mode: active_objects
                    # mode: motion #
                required_zones:
                    - driveway
                    - street

Do I simply omit this section now?

My error:

    cameras.driveway_cam.record.events.required_zones: Extra inputs are not permitted

### Version

0.14

### Frigate config file

```yaml
record:
                enabled: True
                retain:
                days: 10
                mode: motion
                events:
                retain:
                    default: 10
                    mode: active_objects
                    # mode: motion #
                required_zones:
                    - driveway
                    - street
```

### Relevant log output

```shell
cameras.driveway_cam.record.events.required_zones: Extra inputs are not permitted
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
