### DISCUSSION TITLE
[Support]: History View very slow/doesn't load

### DISCUSSION THREAD

**Discussion by Sirfon** [blakeblackshear/frigate#12920] [General Support]
### Describe the problem you are having

I have four cameras set to record 24/7 with no detection. Live view is fine. They are not always running, I tend to put them on when I am away.  If I click on a camera for live view then History to view recordings, then within the current day I can click through the timeline and view recorded video no problem.  However if I change to a different day, the timeline loads but the main images just sit there saying no preview found with a spinner going.  I've waited up to 15 minutes before giving up.  Am I doing something wrong, is there potentially a problem with my install, or is it just very slow? Thanks!

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
go2rtc:
  streams:
    driveway_cam:
      - rtsp://redacted:redacted@192.168.254.152/Streaming/Channels/101
    driveway_cam_sub:
      - rtsp://redacted:redacted@192.168.254.152/Streaming/Channels/102
    garden_cam:
      - rtsp://redacted:redacted@192.168.254.151/Streaming/Channels/101
    garden_cam_sub:
      - rtsp://redacted:redacted@192.168.254.151/Streaming/Channels/102
    frontdoor_cam:
      - rtsp://redacted:redacted@192.168.254.153/Streaming/Channels/101
    frontdoor_cam_sub:
      - rtsp://redacted:redacted@192.168.254.153/Streaming/Channels/102
    sidepassage_cam:
      - rtsp://redacted:redacted@192.168.254.150/Streaming/Channels/101
    sidepassage_cam_sub:
      - rtsp://redacted:redacted@192.168.254.150/Streaming/Channels/102
cameras:
  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_cam_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_cam
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    live:
      stream_name: driveway_cam
    zones:
      Drive:
        coordinates: 
          0.213,0.248,0.347,0.287,0.509,0.208,0.632,0.2,0.747,0.269,0.761,0.21,0.979,0.375,0.998,0.395,0.995,0.992,0.001,0.99,0.003,0.328
        loitering_time: 0
  Garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_cam_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garden_cam
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: garden_cam
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_cam_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontdoor_cam
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: frontdoor_cam
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
  SidePassage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sidepassage_cam_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/sidepassage_cam
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: sidepassage_cam
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
record:
  enabled: true
  retain:
    days: 365
    mode: all
birdseye:
  enabled: false
version: 0.14
```

### Relevant log output

```shell
Nothing shown apart from errors as one camera currently disconnected.
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.5-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x620c1372c700] max delay reached. need to consume packet
[rtsp @ 0x620c1372c700] RTP: missed 91 packets
[h264 @ 0x620c13731400] left block unavailable for requested intra mode
[h264 @ 0x620c13731400] error while decoding MB 0 50, bytestream 455752
[h264 @ 0x620c13731400] concealing 15025 DC, 15025 AC, 15025 MV errors in I frame
Input #0, rtsp, from 'rtsp://redacted:redacted@192.168.254.152/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.050000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 3072x2048 [SAR 1:1 DAR 3:2], 20 fps, 20 tbr, 90k tbn
```

### Frigate stats

```json
{"cameras":{"Driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":401,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":425,"pid":384,"process_fps":5.1,"skipped_fps":0.0},"FrontDoor":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":414,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":428,"pid":388,"process_fps":5.0,"skipped_fps":0.0},"Garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":408,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":433,"pid":385,"process_fps":5.0,"skipped_fps":0.0},"SidePassage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":426,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":1275,"pid":393,"process_fps":0.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"104":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"11.3","cpu_average":"10","mem":"0.2"},"1204":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"122":{"cmdline":"python3 -u -m frigate","cpu":"2.8","cpu_average":"8","mem":"2.8"},"123":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1240":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1296":{"cmdline":"ffmpeg -hide_banner -y -i /tmp/cache/Garden@20240810104325+0100.mp4 -c copy -movflags +faststart /media/frigate/recordings/2024-08-10/09/Garden/43.25.mp4","cpu":"0.0","cpu_average":"0","mem":"0.2"},"131":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"159":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"225":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"226":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"227":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"296":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"337":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.7"},"339":{"cmdline":"frigate.recording_manager","cpu":"4.1","cpu_average":"2","mem":"0.9"},"34":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"341":{"cmdline":"frigate.review_segment_manager","cpu":"0.6","cpu_average":"0","mem":"0.8"},"366":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"367":{"cmdline":"frigate.detector.ov  ","cpu":"0.1","cpu_average":"7","mem":"2.4"},"369":{"cmdline":"frigate.output       ","cpu":"2.2","cpu_average":"2","mem":"0.8"},"384":{"cmdline":"frigate.process:Driveway","cpu":"2.3","cpu_average":"1","mem":"0.8"},"385":{"cmdline":"frigate.process:Garden","cpu":"2.1","cpu_average":"1","mem":"0.8"},"388":{"cmdline":"frigate.process:FrontDoor","cpu":"2.1","cpu_average":"1","mem":"0.8"},"393":{"cmdline":"frigate.process:SidePassage","cpu":"0.0","cpu_average":"0","mem":"0.8"},"401":{"cmdline":"frigate.capture:Driveway","cpu":"1.0","cpu_average":"0","mem":"0.8"},"408":{"cmdline":"frigate.capture:Garden","cpu":"1.1","cpu_average":"0","mem":"0.8"},"414":{"cmdline":"frigate.capture:FrontDoor","cpu":"1.0","cpu_average":"0","mem":"0.8"},"425":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_cam_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.3"},"426":{"cmdline":"frigate.capture:SidePassage","cpu":"0.5","cpu_average":"0","mem":"0.8"},"428":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_cam_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.3"},"433":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_cam_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"1","mem":"0.3"},"443":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Driveway@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.2"},"444":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/FrontDoor@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"0","mem":"0.2"},"446":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garden@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.2"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"464":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"469":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"474":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"486":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"19.6","mem":"56.5"}},"detection_fps":0.0,"detectors":{"ov":{"detection_start":0.0,"inference_speed":10.0,"pid":367}},"gpu_usages":{"error-gpu":{"gpu":"","mem":""}},"processes":{"go2rtc":{"pid":104},"logger":{"pid":337},"recording":{"pid":339},"review_segment":{"pid":341}},"service":{"last_updated":1723283019,"latest_version":"0.14.0","storage":{"/dev/shm":{"free":125.8,"mount_type":"tmpfs","total":128.0,"used":2.2},"/media/frigate/clips":{"free":9976.6,"mount_type":"ext4","total":1906028.4,"used":1876958.5},"/media/frigate/recordings":{"free":9976.6,"mount_type":"ext4","total":1906028.4,"used":1876958.5},"/tmp/cache":{"free":922.9,"mount_type":"tmpfs","total":953.7,"used":30.7}},"temperatures":{},"uptime":146,"version":"0.14.0-da913d8"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision

### Any other information that may be helpful

Running on Proxmox
