### DISCUSSION TITLE
[Support]: Frigate 0.14: after upgrading from 0.13 manually created events via HTTP API are mostly not displayed

### DISCUSSION THREAD

**Discussion by MaxRower** [blakeblackshear/frigate#12930] [Config Support] [answered]
### Describe the problem you are having

Alongside my cameras I have PIR sensors. When a sensor reports motion, I create an event for that camera via the HTTP API. When motion is no longer detected, the event is ended. That way, I don't have to enable motion detection or object detection on a slow NUC5CAYH without coral.
With frigate 0.13 this worked fine, all events showed up. But since the upgrade to 0.14, I have only three of them visible in alerts, from numerous other new events.

### Steps to reproduce

n/a

### Version

0.14.0-da913d8

### Frigate config file

```yaml
ui:
  strftime_fmt: "%Y-%m-%d %H:%M:%S"
  time_format: 24hour
mqtt:
  enabled: true
  host: ********
  user:
  password:
ffmpeg:
  hwaccel_args:
#  - preset-vaapi
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
#audio: # <- enable audio events for all camera
#  enabled: True
go2rtc:
  streams:
    stream_keller_high: # <- for RTSP streams
      - rtsp://********/live.sdp # <- stream which supports video & aac audio
      - ffmpeg:stream_keller_high#audio=aac   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    stream_keller_low: # <- for RTSP streams
      - rtsp://********/live3.sdp # <- stream which supports video & aac audio
      - ffmpeg:stream_keller_low#audio=aac   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    stream_vorzimmer_high: # <- for RTSP streams
      - rtsp://********/live.sdp # <- stream which supports video & aac audio
      - ffmpeg:stream_vorzimmer_high#audio=aac   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    stream_vorzimmer_low: # <- for RTSP streams
      - rtsp://********/live3.sdp # <- stream which supports video & aac audio
      - ffmpeg:stream_vorzimmer_low#audio=aac   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
cameras:
  Keller:
    live:
      stream_name: stream_keller_low
    audio:
      enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
#       - path: rtsp://********/live.sdp
        - path: rtsp://127.0.0.1:8554/stream_keller_high?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
#     - path: rtsp://********/live3.sdp
        - path: rtsp://127.0.0.1:8554/stream_keller_low?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
#      audio:
#        enabled: True
#      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - cat
        - bicycle
#        - car
#        - motorcycle
      filters:
        bicycle:
          mask:
            - 294,106,308,420
    detect:
      enabled: false
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
  Vorzimmer:
    live:
      stream_name: stream_vorzimmer_low
    audio:
      enabled: true
    ffmpeg:
      inputs:
#       - path: rtsp://********/live.sdp
        - path: rtsp://127.0.0.1:8554/stream_vorzimmer_high?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
#       - path: rtsp://********/live3.sdp
        - path: rtsp://127.0.0.1:8554/stream_vorzimmer_low?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
#      audio:
#        enabled: True
#      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
#       - cat
#       - bicycle
#       - car
#       - motorcycle
    detect:
      enabled: false
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
  Wohnzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://********/live.sdp
          roles:
            - record
        - path: rtsp://********/live3.sdp
          roles:
            - detect
      hwaccel_args: preset-vaapi
    objects:
      track:
        - person
#       - cat
#       - bicycle
#       - car
#       - motorcycle
    detect:
      enabled: false
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
  Kueche:
    ffmpeg:
      inputs:
        - path: rtsp://********/streaming/Channels/1
          roles:
            - record
        - path: rtsp://********/streaming/Channels/2
          roles:
            - detect
      hwaccel_args: preset-vaapi
#      output_args:
#        detect: -vf scale=1024:576
    objects:
      track:
        - person
#       - cat
#       - bicycle
#       - car
#       - motorcycle
    detect:
      enabled: false
      width: 704
      height: 576
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
detectors:
  cpu1:
    type: cpu
    num_threads: 3
#detectors:
#  ov:
#    type: openvino
#    device: GPU
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml
version: 0.14
```

### Relevant log output

```shell
{"log":"2024-08-10 17:40:55.876274459  172.18.0.1 - - [10/Aug/2024:17:40:55 +0200] \"POST /api/events/Vorzimmer/PIR/create HTTP/1.1\" 200 95 \"-\" \"curl/8.7
.1\" \"-\"\n","stream":"stdout","time":"2024-08-10T15:40:55.876926355Z"}
{"log":"2024-08-10 17:41:40.733913516  172.18.0.1 - - [10/Aug/2024:17:41:40 +0200] \"PUT /api/events/1723304455.695401-dhevkr/end HTTP/1.1\" 200 55 \"-\" \"c
url/8.7.1\" \"-\"\n","stream":"stdout","time":"2024-08-10T15:41:40.734238939Z"}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

VIVOTEK FD8167
