### DISCUSSION TITLE
[Bug]:

### DISCUSSION THREAD

**Discussion by nabeelmoeen** [blakeblackshear/frigate#12941] [Report a Bug] [answered]
### Describe the problem you are having

Upgraded the home assistant addon from version 0.13.2 to version 0.14.
after the upgrade frigate would not start, and log shows a single error message

error /init: exec format error

### Steps to reproduce

- stop Frigate addon in homeassistant
- click to upgrade
- restart home assistant
- click on start addon

### Version

0.14

### Frigate config file

```yaml
mqtt: 
  host: 192.168.1.100
  user: mqttuser
  password: mqtt
  
database:
  path: /config/frigate.db
  
detectors:
  cpu:
    type: cpu
    num_threads: 2

cameras:
  # rumpus:
  #   ffmpeg:
  #     hwaccel_args: preset-rpi-64-h264
  #     inputs:
  #       - path: rtsp://192.168.1.148:8554/cam
  #         roles: 
  #           - detect
  #           - record
  #   detect: 
  #     enabled: True
  #   record: 
  #     enabled: True
  #   snapshots: 
  #     enabled: True
  
  backyard:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://admin:reomrsnah79@192.168.1.51:554/h264Preview_02_main
          roles: 
            - record
        - path: rtsp://admin:reomrsnah79@192.168.1.51:554/h264Preview_02_sub
          roles:
            - detect
    detect:
      enabled: True
    record:
      enabled: true
    snapshots:
      enabled: true

  side_alley:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264      
      inputs:
        - path: rtsp://admin:reomrsnah79@192.168.1.51:554/h264Preview_01_main
          roles: 
            - record
        - path: rtsp://admin:reomrsnah79@192.168.1.51:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: True
    record:
      enabled: True
    snapshots:
      enabled: True
```

### Relevant log output

```shell
error /init: exec format error
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

using Reolink IP camera
