### DISCUSSION TITLE
Why does (improve_contrast:) in config file have apostrophes for true or false?

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#12940] [General]
When edited in "Motion Tuner" (improve_contrast:) in config file has apostrophes appended before and after 'true' or 'false'
None of the other true/false options in config file have it.
**The config editor flags the line.**

 ```
motion:
      threshold: 60
      contour_area: 20
      improve_contrast: 'true'
    record:
      enabled: true
```
