### DISCUSSION TITLE
[Config Support]: Needing optimization guidance

### DISCUSSION THREAD

**Discussion by SailingSailing** [blakeblackshear/frigate#12946] [Config Support]
### Describe the problem you are having

I am running Frigate on a EliteDesk  (specs below) with a USB Google Coral. Currently I am experiencing a 64-67% CPU load and 28+ms inference. Is there anything I could do in my configuration to optimize this? Sub streams are running at 720 x 480.

At the moment, one of the switches is down which links some of the cameras - so only 7 of the 13 cameras are currently up. If I bring that switch up now, I can imagine Frigate is really going to struggle.

EliteDesk specs:
800G3 Mini 
Intel Core i5-7400T 
RAM 16 GB 
SSD 240GB

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  enabled: true

  # Include all cameras by default in Birdseye view (currently disabled to save resources and bandwidth)
birdseye:
  enabled: false
  mode: continuous
  width: 2560
  height: 1440
  restream: true

detectors:
  coral:
    type: edgetpu
    device: usb

review:
  alerts:
    labels:
      - boat
      - dog
      - person
  detections:
    labels:
      - boat
      - dog
      - person
      
objects:
  track:
      - boat
      - dog
      - person

record:
  enabled: true
  expire_interval: 60
  sync_recordings: False
  retain:
    days: 7
    mode: active_objects
  preview:
    quality: medium
  events:
    pre_capture: 10
    post_capture: 10
    objects:
      - boat
      - dog
      - person
    retain:
      default: 7
      mode: active_objects
      # Optional: Per object retention days
      # objects:
      #   person: 15

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

go2rtc:
  streams:
    bulwark_port:
      - rtsp://admin:pass@192.168.170.25:554/stream0
    bulwark_port_sub:
      - rtsp://admin:pass@192.168.170.25:554/stream1
    bulwark_stb:
      - rtsp://admin:pass@192.168.170.13:554/stream0
    bulwark_stb_sub:
      - rtsp://admin:pass@192.168.170.13:554/stream1
    cockpit_port:
      - rtsp://admin:pass@192.168.170.20:554/stream0
    cockpit_port_sub:
      - rtsp://admin:pass@192.168.170.20:554/stream1
    cockpit_stb:
      - rtsp://admin:zcpm3ETO@192.168.170.140:554/stream0
    cockpit_stb_sub:
      - rtsp://admin:zcpm3ETO@192.168.170.140:554/stream1
    main_engine_port:
      - rtsp://admin:pass@192.168.170.19:554/stream0
    main_engine_port_sub:
      - rtsp://admin:pass@192.168.170.19:554/stream1
    main_engine_stb:
      - rtsp://admin:pass@192.168.170.12:554/stream0
    main_engine_stb_sub:
      - rtsp://admin:pass@192.168.170.12:554/stream1
    fwd_mast_port:
      - rtsp://admin:pass@192.168.170.29:554/stream0
    fwd_mast_port_sub:
      - rtsp://admin:pass@192.168.170.29:554/stream1
    fwd_mast_stb:
      - rtsp://admin:pass@192.168.170.28:554/stream0
    fwd_mast_stb_sub:
      - rtsp://admin:pass@192.168.170.28:554/stream1
    er_upper_port_fwd:
      - rtsp://admin:pass@192.168.170.17:554/stream0
    er_upper_port_fwd_sub:
      - rtsp://admin:pass@192.168.170.17:554/stream1
    er_upper_stbd_inboard:
      - rtsp://admin:pass@192.168.170.150:554/stream0
    er_upper_stbd_inboard_sub:
      - rtsp://admin:pass@192.168.170.150:554/stream1
    er_lower_stb_aft:
      - rtsp://admin:pass@192.168.170.24:554/stream0
    er_lower_stb_aft_sub:
      - rtsp://admin:pass@192.168.170.24:554/stream1
    mizzen_mast_port:
      - rtsp://admin:pass@192.168.170.26:554/stream0
    mizzen_mast_port_sub:
      - rtsp://admin:pass@192.168.170.26:554/stream1

cameras:
  bulwark_stb:
    enabled: true
    birdseye:
      order: 1
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/bulwark_stb_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/bulwark_stb
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  cockpit_stb:
    enabled: true
    birdseye:
      order: 2
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/cockpit_stb_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/cockpit_stb
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  er_upper_stbd_inboard:
    enabled: true
    birdseye:
      order: 3
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/er_upper_stbd_inboard_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/er_upper_stbd_inboard
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  fwd_mast_stb:
    enabled: true
    birdseye:
      order: 4
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/fwd_mast_stb_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/fwd_mast_stb
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  er_upper_port_fwd:
    enabled: true
    birdseye:
      order: 5
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/er_upper_port_fwd_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/er_upper_port_fwd
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  main_engine_stb:
    enabled: true
    birdseye:
      order: 6
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/main_engine_stb_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/main_engine_stb
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  main_engine_port:
    enabled: true
    birdseye:
      order: 7
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/main_engine_port_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/main_engine_port
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  cockpit_port:
    enabled: true
    birdseye:
      order: 8
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/cockpit_port_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/cockpit_port
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  er_lower_stb_aft:
    enabled: true
    birdseye:
      order: 9
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/er_lower_stb_aft_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/er_lower_stb_aft
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  bulwark_port:
    enabled: true
    birdseye:
      order: 10
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/bulwark_port_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/bulwark_port
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  fwd_mast_port:
    enabled: true
    birdseye:
      order: 11
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/fwd_mast_port_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/fwd_mast_port
          roles:
            - record
    detect:
      enabled: true
      fps: 5
  mizzen_mast_port:
    enabled: true
    birdseye:
      order: 12
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/mizzen_mast_port_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/mizzen_mast_port
          roles:
            - record
    detect:
      enabled: true
      fps: 5
version: 0.14
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
Hardware Info:

Return Code: 0

Process Output:

vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
VAProfileNone : VAEntrypointVideoProc
VAProfileNone : VAEntrypointStats
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Simple : VAEntrypointEncSlice
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointFEI
VAProfileH264Main : VAEntrypointEncSliceLP
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSlice
VAProfileH264High : VAEntrypointFEI
VAProfileH264High : VAEntrypointEncSliceLP
VAProfileVC1Simple : VAEntrypointVLD
VAProfileVC1Main : VAEntrypointVLD
VAProfileVC1Advanced : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointEncPicture
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264ConstrainedBaseline: VAEntrypointFEI
VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
VAProfileVP8Version0_3 : VAEntrypointVLD
VAProfileVP8Version0_3 : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointFEI
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileHEVCMain10 : VAEntrypointEncSlice
VAProfileVP9Profile0 : VAEntrypointVLD
VAProfileVP9Profile2 : VAEntrypointVLD
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

Running via Docker on clean Debian install.
