### DISCUSSION TITLE
[Config Support]: Retention error - *now* what have I done wrong?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#12954] [Config Support] [answered]
### Describe the problem you are having

Hello

Please can you help me work out why my retention is not deleting things after 7 days?

I have NFS mounted a quota-based share (quota based on the total data size  I expect to be written during the retention period) but the share has filled up and filled up, presumably because I must have made a config mistake.

Within Frigate, video and jpeg writing to the share occurs, reading back within the UI occurs, deleting doesn't occur. 

Here's the file structure on my NAS store which you can see dates back to mid-July:
![Screenshot at 2024-08-11 12-31-22](https://github.com/user-attachments/assets/1a7ea77a-09d6-41c8-8a53-e977dc82b5fb)

Here's the first relevant part of my config:

```
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
 
snapshots:
  enabled: true
  clean_copy: true #false  #true
  timestamp: false
  bounding_box: true
  crop: false
  height: 768
  required_zones: []
  retain:
    default: 5
    objects:
      person: 7
      cat: 7
      dog: 7
      bird: 7
      fox: 7
      badger: 7
      car: 7
      licence_plate: 7
  quality: 100
```

and per camera I have

```
cameras: 
  upper_patio:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0
        roles:
        - detect
 
      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
```

What is it that I have messed up?

### Version

0.13

### Frigate config file

```yaml
#config_310724_NO_RESTREAMING_FIXED taken from #config_and_audio_110724# # this works with the FrigateViewer tablet app - events playback OK
# improved detection (height & width added) # also added ffmpeg out args record audio and logger entries at EOF

ui:
  use_experimental: false
  live_mode: mse

mqtt:
  enabled: false


go2rtc:
  streams:
    
    #reference format from NickM-27 @ https://github.com/blakeblackshear/frigate/discussions/12376 
    #              "ffmpeg:rtsp://...                                               #video=h264#audio=copy#hardware" note the quotes and hashes
    greenhouse:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:greenhouse#audio=opus"
    upper_patio:   
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:upper_patio#audio=opus"
    ponds:         
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:ponds#audio=opus"
    blue_gate:     
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:blue_gate#audio=opus"
    lower_steps:   
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:lower_steps#audio=opus"
    lower_patio:   
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:lower_patio#audio=opus"
    shed:          
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:shed#audio=opus"
    drive:         
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:drive#audio=opus"
    

####rtsp is 30060 and webRTC is 30061 (TN Frigate app interrnals)
  webrtc:
    candidates:
    - 192.168.1.194:30061
    - stun:30061


ffmpeg:
  #####you can only have one line here#####
  #hwaccel_args: preset-nvidia-h264
  #hwaccel_args: preset-nvidia-hevc #gives black screens on cameras
  #hwaccel_args: preset-nvidia-cuvid #gives black screens on cameras
  output_args:
    record: preset-record-generic-audio-aac
  
detectors:
  coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

birdseye:
  enabled: true
  mode: continuous #continuous | objects | motion

# record: # <----- Enable recording # was working
#  enabled: true # was working

# added from https://fixtse.com/blog/coral-ia-frigate start#
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
# added from https://fixtse.com/blog/coral-ia-frigate #

 
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true #false  #true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 768
  #height: 800
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 7
      cat: 7
      dog: 7
      bird: 7
      fox: 7
      badger: 7
      car: 7
      licence_plate: 7

  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

##########################################################
##########################################################
# go2rtc: # this worked from https://docs.frigate.video/configuration/live/#setting-stream-for-live-ui
#  streams:
#    upper_patio:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 # <- stream which supports video & aac audio.
#    - "ffmpeg:upper_patio#audio=opus" # <- copy of the stream which transcodes audio to opus for webrtc
#    restream: true        
#    upper_patio_sub:
#    - rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 # <- stream which supports video & aac audio.
#    - "ffmpeg:upper_patio_sub#audio=opus"
##########################################################
##########################################################

motion:
  improve_contrast: True

detect:
  width: 640
  height: 360

#record:
#  width: 1920
#  height: 1080

####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################
####################################################################################################################


##################UPPER_PATIO###############################################UPPER_PATIO#############################
##################UPPER_PATIO###############################################UPPER_PATIO#############################
cameras: #########UPPER_PATIO###############################################UPPER_PATIO###########################
  upper_patio:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
      #- path: http://truenas.local:8082/media=0/channel=1&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
      #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #input_args: preset-rtsp-restream

        roles:
        - detect
          

      - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 1

    motion:
      mask: 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      upper patio:
        coordinates: 640,360,640,337,610,312,603,297,594,279,564,256,524,255,510,242,487,220,451,203,435,201,421,187,409,166,392,152,334,146,274,138,215,142,122,145,78,162,23,202,0,360


######################BLUE_GATE###################################################BLUE_GATE#############################
######################BLUE_GATE###################################################BLUE_GATE#############################
  blue_gate: #########BLUE_GATE###################################################BLUE_GATE#############################
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #  input_args: preset-rtsp-restream

        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placehlder
      - badger # placeholder
      - car
      - licence_plate

    birdseye:
      mode: continuous   #continuous | objects | motion
      # masks are black: they block out areas where you aren't interested in detecting things
      order: 2

    motion:
      mask:
      - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
      - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360

    zones:
      gravel:
        coordinates: 411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233

##################DRIVE###############################################DRIVE#############################
##################DRIVE###############################################DRIVE#############################
  drive: #########DRIVE###############################################DRIVE#############################
    enabled: true

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox #placeholder
      - badger #placeholder
      - car
      - licence_plate

    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; changing track0 to track1 didn't work)
      #input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;(changing track0 to track1 didn't work)
        roles:
        - record

    birdseye:
      mode: continuous #continuous | objects | motion
      #restream: True
      order: 4

    motion:
      # masks are black: they block out areas where you aren't interested in detecting things
      mask:
      - 98,129,170,113,189,0,0,0,0,0,0,142
      - 273,0,170,0,178,67,258,117,256,191,414,181,640,307,640,0

    # zones are red: they select areas where monitoring of activity is wanted
    zones:
      driveway:
        coordinates: 78,360,248,360,381,360,640,360,640,276,449,177,303,183,298,129,200,64,144,113,0,127,0,360

########################LOWER_PATIO#####################################################LOWER_PATIO#############################
########################LOWER_PATIO#####################################################LOWER_PATIO#############################
  lower_patio: #########LOWER_PATIO#####################################################LOWER_PATIO#############################
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0   #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0   #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
        roles:
        - record

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      - deer
      - fox   #placeholder
      - badger   #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 3

      # masks are black: they block out areas where you aren't interested in detecting things
    motion:
      mask:
      - 0,148,92,104,184,55,253,0,269,154,272,305,318,125,354,107,345,56,406,60,417,131,504,240,570,360,640,360,640,0,0,0
        #- 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      lower patio:
        coordinates: 284,360,303,183,333,157,344,139,357,118,352,99,359,74,382,73,384,110,403,128,499,246,580,360


logger:
    logs:
      #frigate.record.maintainer: debug
      frigate.object_detection: debug
      #watchdog.blue_gate: debug







#-----------------------END-----------------------##-----------------------END-----------------------##-----------------------END
```

### Relevant log output

```shell
n/a
```

### Frigate stats

```json
{
  "cameras": {
    "blue_gate": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 478,
      "detection_enabled": 1,
      "detection_fps": 4.8,
      "ffmpeg_pid": 405889,
      "pid": 465,
      "process_fps": 4.9,
      "skipped_fps": 0.1
    },
    "drive": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 493,
      "detection_enabled": 1,
      "detection_fps": 0.1,
      "ffmpeg_pid": 502,
      "pid": 468,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "lower_patio": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 498,
      "detection_enabled": 1,
      "detection_fps": 3.4,
      "ffmpeg_pid": 362628,
      "pid": 471,
      "process_fps": 5,
      "skipped_fps": 0
    },
    "upper_patio": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 473,
      "detection_enabled": 1,
      "detection_fps": 1.1,
      "ffmpeg_pid": 489,
      "pid": 464,
      "process_fps": 5.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "18": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "43": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "83": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "98": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "2.6",
      "cpu_average": "1",
      "mem": "1.8"
    },
    "99": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "122": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "152": {
      "cmdline": "nginx: worker process",
      "cpu": "2.2",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "233": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "246": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "248": {
      "cmdline": "nginx: worker process",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "249": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "258": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "442": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "444": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "452": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "453": {
      "cmdline": "frigate.detector.coral",
      "cpu": "6.8",
      "cpu_average": "2",
      "mem": "0.7"
    },
    "455": {
      "cmdline": "frigate.output       ",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "461": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "463": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "464": {
      "cmdline": "frigate.process:upper_patio",
      "cpu": "7.1",
      "cpu_average": "2",
      "mem": "0.7"
    },
    "465": {
      "cmdline": "frigate.process:blue_gate",
      "cpu": "10.3",
      "cpu_average": "3",
      "mem": "0.7"
    },
    "467": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "468": {
      "cmdline": "frigate.process:drive",
      "cpu": "2.7",
      "cpu_average": "3",
      "mem": "0.7"
    },
    "470": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "471": {
      "cmdline": "frigate.process:lower_patio",
      "cpu": "4.3",
      "cpu_average": "2",
      "mem": "0.7"
    },
    "473": {
      "cmdline": "frigate.capture:upper_patio",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "475": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "478": {
      "cmdline": "frigate.capture:blue_gate",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "489": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.3",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "493": {
      "cmdline": "frigate.capture:drive",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "498": {
      "cmdline": "frigate.capture:lower_patio",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "501": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/upper_patio@%Y%m%d%H%M%S%z.mp4",
      "cpu": "3.2",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "502": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.2",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "513": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/drive@%Y%m%d%H%M%S%z.mp4",
      "cpu": "3.1",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "514": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/lower_patio@%Y%m%d%H%M%S%z.mp4",
      "cpu": "3.0",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "222613": {
      "cmdline": "ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0 -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -pix_fmt:v yuv420p -c:a copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/533522f5b40329fb504a2f28f1ace041",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "362628": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.1",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "405854": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/blue_gate@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "405889": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "4.1",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "614199": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "614258": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/blue_gate?audio -c:a libopus -application:a lowdelay -frame_duration 20 -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/252ebb76a2cc11f2d824529eaf1d8898",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    }
  },
  "detection_fps": 9.4,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 10,
      "pid": 453
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 90
    },
    "logger": {
      "pid": 442
    },
    "recording": {
      "pid": 444
    }
  },
  "service": {
    "last_updated": 1723376367,
    "latest_version": "unknown",
    "storage": {
      "/dev/shm": {
        "free": 48.4,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 15.6
      },
      "/media/frigate/clips": {
        "free": 3724.4,
        "mount_type": "zfs",
        "total": 87040,
        "used": 83315.6
      },
      "/media/frigate/recordings": {
        "free": 3724.4,
        "mount_type": "zfs",
        "total": 87040,
        "used": 83315.6
      },
      "/tmp/cache": {
        "free": 1021.7,
        "mount_type": "tmpfs",
        "total": 1024,
        "used": 2.3
      }
    },
    "temperatures": {

    },
    "uptime": 156775,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

TrueNAS "app" , based on Docker
