### DISCUSSION TITLE
[Question]: My BBQ is detected as a person and how to see detected objects on a detection

### DISCUSSION THREAD

**Discussion by royduin** [blakeblackshear/frigate#12955] [Ask A Question] [answered]
### What is your question:

<img width="1545" alt="image" src="https://github.com/user-attachments/assets/4c37d75a-006d-43f5-bcc7-5378fcdc2c01">

It's funny.. but it fills up a lot of events previously in 0.13 and alerts now with 0.14. How fix this so my BBQ isn't detected as a person? My detector/model settings:

```
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```
And yes, I know CPU isn't the best choose here, but that's due: https://github.com/blakeblackshear/frigate/issues/8470

And my second question; previously in 0.13 I was able to see all detected outlines on an event. Since 0.14 I can't find it anywhere. From "settings -> debug" I'm able to see it realtime, but how can I see that on a alert/detection?
