### DISCUSSION TITLE
[Config Support]: No Alerts / detections created - occupancy sensors remain on "off" state

### DISCUSSION THREAD

**Discussion by promufa** [blakeblackshear/frigate#12952] [Config Support] [answered]
### Describe the problem you are having

Since update to 0.14, my light automation have stopped working.
I have been using Frigate to trigger automations based on object detection in different areas. After the upgrade and re-settinga lot of the areas, the binary_sensor.area_person_occupancy are not updating to "on" / "detected" any more. 

In the debug screen I can see that objects are detected correctly and the area is being highlighted but the sensor does not seem to trigger.

For the front camera it seem to work - at least I can see cars in the "objects" list in the debug section.
For the living room camera, the objects panel is empty, even though in the live stream there are detected objects.

I cannot figure out where the problem is ...

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.245
  port: 1883
  user: frigate
  password: redacted
database:
  path: /config/frigate.db
detectors:
  coral: # <---------- Name your detector (you can choose any name)
    type: edgetpu # <-- This specifies that you want to use the Coral USB Accelerator
    device: usb # <-- This tells Frigate to use the USB connected Coral device
go2rtc:
  streams:
    front:
      - rtsp://redacted:redacted@192.168.0.215:554/stream1
    living:
      - rtsp://redacted:redacted@192.168.0.121:554/stream1
  webrtc:
    candidates:
      - 192.168.0.245:8555
      - stun:8555
cameras:
  front:
    motion:
      threshold: 40
      contour_area: 35
      lightning_threshold: 0.4
      mask: 
        0.042,0.044,0.313,0.043,0.315,0.014,0.609,0.062,0.78,0.111,0.942,0.188,0.96,0.09,0.862,0.002,0,0,0,1,0.072,1,0.066,0.888,0.099,0.887,0.063,0.633,0.039,0.298
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@192.168.0.215/stream1
          roles:
            - record
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - motorcycle
        - bicycle
      filters:
        person:
          min_area: 35000 #700
          max_area: 400000 #20000
          min_score: 0.7
          threshold: 0.9
        car:
          min_area: 100000 #2000
          max_area: 1000000 #60000
          min_score: 0.7
          threshold: 0.8
        dog:
          max_area: 90000 #10000
          min_score: 0.7
          threshold: 0.8
        cat:
          max_area: 80000 #10000
          min_score: 0.8
          threshold: 0.9
    record:
      enabled: true
      expire_interval: 240 #minutes
      retain:
        days: 4 #days
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 30 #days
          mode: active_objects
    snapshots:
      required_zones:
        - parking
        - front_yard
        - neighbours
      enabled: true
      clean_copy: true
      bounding_box: true
      retain:
        default: 10
        objects:
          person: 60
      quality: 100

    zones:
      front_yard:
        coordinates: 
          0.726,0.429,0.551,0.188,0.333,0.173,0.036,0.182,0.046,0.366,0.07,0.692,0.1,1,0.998,0.997,0.997,0.814
        loitering_time: 5
      neighbours:
        coordinates: 0.604,0.203,0.717,0.208,0.801,0.226,0.92,0.247,0.999,0.353,0.998,0.743
        loitering_time: 5
      parking:
        coordinates: 0.059,0.98,0.245,0.944,0.51,0.851,0.832,0.697,0.555,0.271,0.02,0.316
        loitering_time: 0
        objects: car
    review:
      alerts:
        required_zones:
          - front_yard
          - neighbours
          - parking
  living_room:
    motion:
      threshold: 20
      contour_area: 15
      frame_alpha: 0.2
      delta_alpha: 0.05
      frame_height: 100
      improve_contrast: true
      lightning_threshold: 0.3
      mask:
        - 0.314,0,0.312,0.049,0,0.045,0,0,0,0,0,0
        - 0.536,0.034,0.531,0.115,0.444,0.107,0.449,0.023
        - 0.385,0.049,0.379,0.18,0.366,0.179,0.371,0.049
    zones:
      dinning:
        coordinates: 
          0.345,0.461,0.347,0.375,0.34,0.347,0.334,0.332,0.334,0.231,0.242,0.232,0.212,0.253,0.154,0.375,0.16,0.465
        inertia: 3
        objects: person
        loitering_time: 0
      entrance:
        coordinates: 0.418,0.334,0.408,0.188,0.34,0.186,0.337,0.329
        inertia: 3
        objects: person
        loitering_time: 0
      kitchen:
        coordinates: 0.432,0.3,0.539,0.303,0.547,0.193,0.435,0.182
        inertia: 3
        objects:
          - person
          - cat
        loitering_time: 0
      living:
        coordinates: 
          0,1,0.935,1,0.964,0.922,0.843,0.685,0.82,0.522,0.758,0.522,0.724,0.701,0.541,0.288,0.427,0.283,0.424,0.321,0.213,0.315,0.138,0.486,0.031,0.858
        inertia: 3
        objects: person
        loitering_time: 0
      sofa:
        coordinates: 0.113,0.68,0.383,0.679,0.38,0.512,0.144,0.51,0.089,0.662
        inertia: 3
        objects: person
        loitering_time: 0
      stairwell:
        coordinates: 
          0.767,0.416,0.679,0,0.78,0,0.875,0.417,0.848,0.601,0.922,0.758,0.9,0.881,0.863,0.917,0.773,0.847,0.712,0.701
        inertia: 3
        objects: person
        loitering_time: 0
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@192.168.0.121/stream1
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      stationary:
        interval: 10
        threshold: 500
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 22000
          max_area: 400000
          min_score: 0.65
          threshold: 0.87
          mask: 
            0.705,0.082,0.847,0.162,0.998,0.29,0.997,0.567,0.908,0.882,0.827,0.715,0.837,0.672,0.82,0.521,0.755,0.523,0.743,0.6,0.664,0.416
        cat:
          min_area: 4000
          max_area: 55000
          min_score: 0.75
          threshold: 0.9
    snapshots:
      enabled: true
      clean_copy: true
      bounding_box: true
      retain:
        default: 10
        objects:
          cat: 3
          person: 3
      quality: 100

    review:
      alerts: {}
live:
  height: 1440
  quality: 8
version: 0.14
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral
