### DISCUSSION TITLE
[Config Support]: Why does my Detections count on the UI doesn't show new detections?

### DISCUSSION THREAD

**Discussion by lee-costa** [blakeblackshear/frigate#12963] [Config Support] [answered]
### Describe the problem you are having

I expect whenever a label subject is detected on the camera for the Detections count on the IU to show new footage.

<img width="1092" alt="Screenshot 2024-08-11 at 11 49 19 AM" src="https://github.com/user-attachments/assets/36356bb2-049a-44e7-9295-eb0c137742b7">

### Version

0.14

### Frigate config file

```yaml
##########################################################
## Driveway
##########################################################

cameras:
driveway_cam:
  ffmpeg:
    output_args:
      record: preset-record-generic-audio-copy
    inputs:
      - path: rtsp://127.0.0.1:8554/driveway_cam # <--- the name here must match the name of the camera in restream
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect

  # detect:
  #   width: 3840
  #   height: 2160
  #   fps: 10
  #   enabled: True

  detect:
    width: 1920
    height: 1080
    fps: 10
    enabled: true

  zones:
    street:
      coordinates: 0.627,0.675,0.943,0.835,0.958,0.712,0.711,0.6
      objects:
        - person
        - dog
        - cat
        - car
        - bicycle
      inertia: 3
      loitering_time: 0
    driveway:
      coordinates: 
        0.596,0.708,0.444,0.633,0.134,0.717,0.131,0.767,0.004,0.807,0.002,0.895,0,1,0.325,0.997,0.996,0.999,1,0.875,0.623,0.681
      loitering_time: 0
      objects:
        - bicycle
        - cat
        - dog
        - person
      inertia: 3

  objects:
    track:
      - person
      - dog
      - car
      - cat
      - bicycle
    filters:
      person:
        min_area: 8000
        max_area: 100000
      dog:
        max_area: 12000
      car:
        max_area: 200000
      cat: {}
      bicycle: {}
  motion:
    threshold: 30
    contour_area: 10
    improve_contrast: 'true'
    mask: 
      0.128,0.706,0.113,0.744,0.005,0.781,0.001,0.001,0.998,0.001,0.998,0.429,1,0.721,0.709,0.588,0.643,0.652,0.593,0.699,0.435,0.622

  record:
    enabled: true
    retain:
      days: 10
      mode: motion
    events:
      retain:
        default: 10
        mode: active_objects

  snapshots:
    enabled: true
    bounding_box: true
    required_zones:
      - driveway
      - street
    retain:
      default: 10

  review:
    alerts:
      labels: []
    detections:
      labels:
        - car
        - people
        - dog
        - cat
        - bicycle
      required_zones:
        - driveway
        - street
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

I expected my review configuration to be able to show me new detection but no alerts. What am I doing wrong?

Thanks for all the support so far!
