### DISCUSSION TITLE
[Support]: Cannot view pre-upgrade recordings after upgrade to 0.14.0

### DISCUSSION THREAD

**Discussion by sshaikh** [blakeblackshear/frigate#12965] [Config Support]
### Describe the problem you are having

After upgrading to [0.14.0](https://github.com/blakeblackshear/frigate/releases/tag/v0.14.0), we cannot view footage in history made before the date of the upgrade.

We only see "No Preview Found" and a spinning circle.

### Steps to reproduce

- click a camera
- click history
- select a date from before the upgrade
- click a time in the timeline

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  host: mqtt
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: True
  retain:
    days: 7

snapshots:
  enabled: True

detect:
  enabled: True

objects:
  track:
    - person
    - bicycle
    - car
    - motocycle
    - bird
    - cat
    - dog
    - backpack
    - umbrella
    - suitcase

detectors:
  coral:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    cam1:
      - rtsp://user:{FRIGATE_RTSP_PASSWORD}@cam1:554/h264Preview_01_main
    cam1-sub:
      - rtsp://user:{FRIGATE_RTSP_PASSWORD}@cam1:554/h264Preview_01_sub

cameras:
  cam1:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam1-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 15
    motion:
      mask:
        - 0,30,200,30,200,0,0,0
    zones:
      test-zone:
        coordinates: 0,480,640,480,640,319,467,306,0,305
        filters:
          person:
            min_area: 3600
    record:
      events:
        required_zones:
          - test-zone
    snapshots:
      required_zones:
        - test-zone

```

### Relevant log output

```shell
None that seem relevant but these smell a bit and seem to occur at the same time:


Recording clip is missing or empty: /media/frigate/recordings/2024-08-11/16/camera/38.29.mp4
```
```


### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Various

### Any other information that may be helpful

Interestingly this seems to work when the browser window is made small, at which point I have a list of "no preview found" thumbnails along the right. The timeline still doesn't work (it runs from midnight of the selected day) but the footage is historical.

The expected historical recordings are present in the media directory (along with post upgrade footage).

**Comment by hawkeye217** [comment]
Did you change the name of the camera in your config file after you upgraded? The error message you're seeing in the log shows it's looking for `camera`, but in your config file it's named `cam1`.

**Reply by sshaikh** [reply]
Apologies, I was trying to obfuscate my camera names. They are consistent across my config and logs.

**Reply by hawkeye217** [reply]
A screenshot of your browser's dev tools network pane as you try to view past footage in the History view would be helpful to see.

**Reply by sshaikh** [reply]
![2024-08-11_18-05 - frigate network](https://github.com/user-attachments/assets/9a8fdf5b-ccb2-4367-b31a-7affff0e5fff)

FWIW I access frigate using HTTPS via nginx.

**Reply by hawkeye217** [reply]
Everything looks fine in the screenshot. The .ts files are the video segments and those are being fetched successfully.

**Reply by sshaikh** [reply]
Do the 404s mean anything?

I see the same behavior in firefox and chrome. I have tried via http and also incognito with similar results. The browser window size seems to be the workaround.

**Reply by hawkeye217** [reply]
History view should display footage from your selected camera and have a smaller set of previews from your other cameras either to the side or below it (depending on your browser window size and main camera aspect ratio). 

It's expected that the smaller previews will show *Preview Not Found* for pre-0.14 footage (see the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), upgrade question 3).

It might be helpful to have a screenshot or video screengrab of what you're seeing if you're expecting something different. I may be misunderstanding you.

**Reply by sshaikh** [reply]
I can reproduce this on mobile and have made some captures. For privacy reasons can I send these via email?

**Reply by hawkeye217** [reply]
Are you on Discord? You can reach me at my same username there.

**Reply by hawkeye217** [reply]
After reviewing your screengrabs, there are a few different issues I noted. Since you scrubbed/altered/redacted your config for this discussion, just want to make sure - did you happen to change your recording configuration after upgrading? Or did your config also have this exact configuration before :

```
record:
  enabled: True
  retain:
    days: 7
```

**Reply by sshaikh** [reply]
Hmm seems I copied an older config to this issue. The relevant part is:

```
record:
  enabled: True
  retain:
    days: 30
```

I can confirm that I haven't changed my config since before upgrading (although I have created a few camera groups via the GUI post upgrade).
