### DISCUSSION TITLE
[Camera Support]: No Audio in Reolink Wifi Doorbell

### DISCUSSION THREAD

**Discussion by NasKar2** [blakeblackshear/frigate#12961] [Camera Support] [answered]
### Describe the problem you are having

Camera video feed works but don't get any audio.  The ip of the camera web page does have audio

### Version

14

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.5.45         # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user               # YOUR MQTT USERNAME
  password: MQTTpassword    # YOUT MQTT PASSWORD
  stats_interval: 60

database:
  path: /config/frigate.db
#detect:
   #annotation_offset: -800
ffmpeg:
  hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p
detectors:
  coral:
    type: edgetpu
    device: usb
###############################################################################

go2rtc:
  streams:
    camerafrontdoor:
    camerafrontdoor_camera:
      - ffmpeg:http://192.168.30.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://192.168.30.20/Preview_01_sub
    camerafrontdoor_sub:
      - ffmpeg:http://192.168.30.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password


#################################################################################

cameras:
  Camerafrontdoor:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:password@192.168.30.20:554/h264Preview_01_main
          roles:
            - record

        # Low Resolution Stream 
        - path: rtsp://admin:password@192.168.30.20:554/h264Preview_01_sub
          roles:
            - detect

    detect:
      width: 640
      height: 480
      fps: 10
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50

    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 10
          mode: motion


    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10

    motion:
      mask:
        - 640,0,640,267,576,265,376,257,353,275,328,274,137,351,138,380,176,416,173,480,0,480,0,0
        - 355,299,367,300,367,278,381,265,325,263
    zones:
      walkway:
        coordinates: 137,480,140,340,204,325,349,265,376,271,640,371,640,480
version: 0.14
```

### Relevant log output

```shell
Info
2024-08-11 10:28:54
startup
Preparing Frigate...
Info
2024-08-11 10:28:54
startup
Starting Frigate...
Info
2024-08-11 10:28:55
frigate.app
Starting Frigate (0.14.0-da913d8)
Info
2024-08-11 10:28:55
frigate.util.config
Checking if frigate config needs migration...
Info
2024-08-11 10:28:55
frigate.util.config
frigate config does not need migration...
Info
2024-08-11 10:28:55
peewee_migrate.logs
Starting migrations
Info
2024-08-11 10:28:55
peewee_migrate.logs
There is nothing to migrate
Info
2024-08-11 10:28:55
frigate.app
Recording process started: 341
Info
2024-08-11 10:28:55
frigate.app
Recording process started: 345
Info
2024-08-11 10:28:55
frigate.app
go2rtc process pid: 107
Info
2024-08-11 10:28:55
detector.coral
Starting detection process: 370
Info
2024-08-11 10:28:55
frigate.app
Output process started: 372
Info
2024-08-11 10:28:55
frigate.detectors.plugins.edgetpu_tfl
Attempting to load TPU as usb
Info
2024-08-11 10:28:55
frigate.app
Camera processor started for Camerafrontdoor: 389
Info
2024-08-11 10:28:55
frigate.app
Capture process started for Camerafrontdoor: 395
Info
2024-08-11 10:28:57
frigate.detectors.plugins.edgetpu_tfl
TPU found
```

### FFprobe output from your camera

```shell
ffprobe version 7.0.2-essentials_build-www.gyan.dev Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Wifi Doorbell Camera

**Comment by hawkeye217** [comment]
The [docs](https://docs.frigate.video) have all the details.

For audio on live views, you need to use go2rtc for your `inputs:`: https://docs.frigate.video/configuration/live

For audio in recordings, you need to use an ffmpeg preset: https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Comment by NasKar2** [comment]
made these changes to the config. I now have audio in the recordings when I play back the mp4 files but not in frigate when I play the clip.

`ffmpeg:
  hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p
  output_args:
    record: preset-record-generic-audio-aac
detectors:
  coral:
    type: edgetpu
    device: usb
###############################################################################

go2rtc:
  streams:
    camerafrontdoor:
    camerafrontdoor_camera:
      - ffmpeg:http://192.168.30.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://192.168.30.20/Preview_01_sub
      - "ffmpeg:camerafrontdoor#audio=opus"
    camerafrontdoor_sub:
      - ffmpeg:http://192.168.30.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
      - "ffmpeg:camerafrontdoor#audio=opus"
`

**Reply by hawkeye217** [reply]
Try using `preset-record-generic-audio-copy` instead of `preset-record-generic-audio-aac`. You may not need transcoding.

**Comment by NasKar2** [comment]
Still no audio after using `preset-record-generic-audio-copy` in frigate but have audio in home assistant when viewing the clip

**Reply by hawkeye217** [reply]
Just to be clear, this change won't affect past recordings.

**Reply by NickM-27** [reply]
if you have audio in the recordings at all then the audio will be applied everywhere. It is impossible for the clips in HA to have audio but not have audio in the Frigate UI. Are you actually unmuting the video when trying to see if it has audio?

**Comment by NasKar2** [comment]
I'm testing with a new recording each time

**Comment by hawkeye217** [comment, marked as answer]
Did you update your `inputs:` to use go2rtc per the docs, specifically for the `record` role?

https://docs.frigate.video/configuration/live#setting-stream-for-live-ui

```
      inputs:
        - path: rtsp://127.0.0.1:8554/camerafrontdoor_camera 
          input_args: preset-rtsp-restream
          roles:
            - record
```
