### DISCUSSION TITLE
[Bug]: The Review tab does not show the correct clip of the event

### DISCUSSION THREAD

**Discussion by janusn** [blakeblackshear/frigate#12971] [General Support] [answered]
### Describe the problem you are having

On the review tab, the video shown is always about half an hour earlier than the event timestamp. The difference of time is very imprecise but the clip shown always starts at the 00 seconds of a minute.

Clicking on the timeline of another event has no effect. The only way to show another event is click on "back" widget and select another. The skip and playing speed widgets works though.

### Steps to reproduce

1) click on the review button on the side pane.
2) click on any of the events shown.
3) watch the clip playing much earlier than the event tagged.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate.home.arpa/api/config/schema.json

# database
# ========================================================================================
database:
  path: /config/frigate.db

# Optional: logger verbosity settings
# logger:
#   # Optional: Default log verbosity (default: info)
#   # Available log levels are: debug, info, warning, error, critical
#   default: debug
#   # Optional: Component specific logger overrides
#   logs:
#     frigate.event: error

# authentication
# ========================================================================================
auth:
  failed_login_rate_limit: 5/minutes;10/hour;100/day
  trusted_proxies:
    - 10.27.0.40/32

# mqtt
# ========================================================================================
mqtt:
  # Optional: Enable mqtt server (default: true)
  enabled: true
  # Required: host name
  host: 10.27.0.50
  # Optional: port (default: 1883)
  port: 1883
  # Optional: topic prefix (default: frigate)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: frigate)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: '{FRIGATE_MQTT_USER}'
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
 #  tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
#  tls_client_cert: /path/to/client.crt
#  tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
#  tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: 60)
  stats_interval: 60

# detectors
# ========================================================================================
detectors:
  # CPU Detector
#  cpu1:
#    type: cpu
#    num_threads: 3  # default 3
#    model:
#      path: "/cpu_model.tflite" #default ""/cpu_model.tflite"

  # Google Coral Detector
  coral:
    type: edgetpu
    device: usb

  # OpenVINO Detector available to Intel CPU 6th Generation CPU (Skylake) or later with a GPU
#  ov:
#    type: openvino
#    device: GPU
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml

# for OpenVino Detectors only
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
# for OpenVino Detectors only

# birdseye
# ========================================================================================
# Include all cameras by default in Birdseye view
birdseye:
  # Optional: Enable birdseye view (default: True)
#  enabled: true
  # Optional: Restream birdseye via RTSP (default: False)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
#  restream: false
  # Optional: Width of the output resolution (default: 1280)
#  width: 1280
  # Optional: Height of the output resolution (default: 720)
#  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: 8)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

# ffmpeg
# ========================================================================================
ffmpeg:
  # generic Intel hardware acceleration
  hwaccel_args: preset-vaapi
  # Intel quick sync for gen 10 GPU (Ice Lake/Jasper Lake) h.264
#  hwaccel_args: preset-intel-qsv-h264
  # Intel quick sync for gen 10 GPU (Ice Lake/Jasper Lake) h.265
#  hwaccel_args: preset-intel-qsv-h265
  # manually crafted quick sync argument
#  hwaccel_args: "-hwaccel_output_format qsv -c:v h264_qsv"
  output_args:
    record: preset-record-generic-audio-aac

# objects
# ========================================================================================
objects:
  # Optional: list of objects to track from labelmap.txt (default: person)
  track:
    - person
    - dog
#    - cat
#    - car

# record
# ========================================================================================
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: false)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: 60)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: False).
  sync_recordings: false
  # Optional: Retention settings for recording
  retain: # <----- continuous recordings
    # Optional: Number of days to retain recordings regardless of events (default: 0)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 7
    # Optional: Mode for retention. Available options are: all, motion, and active_objects (default: all)
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Recording Export Settings
  export:
    # Optional: Timelapse Output Args (default: "-vf setpts=0.04*PTS -r 30").
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.04*PTS -r 30
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: 5)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: 5)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: 10)
      default: 14
      # Optional: Mode for retention. (default: motion)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 60

# snapshots
# ========================================================================================
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: False)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: True)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: False)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: True)
  bounding_box: true
  # Optional: crop the snapshot (default: False)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: 10)
    default: 14
    # Optional: Per object retention days
    objects:
      person: 60

# go2rtc
# ========================================================================================
go2rtc:
  api:
    username: '{FRIGATE_GO2RTC_USER}'
    password: '{FRIGATE_GO2RTC_PASSWORD}'

  rtsp:
    username: '{FRIGATE_GO2RTC_USER}'
    password: '{FRIGATE_GO2RTC_PASSWORD}'

  # webrtc:
  #   listen: ":8555"
  #   candidates:
  #     - 10.27.0.50:8555
  #     - stun:8555

  # extra parameters required for adding a timestamp to a stream. Please refer to
  # https://github.com/AlexxIT/go2rtc/issues/402#issuecomment-1606026909
  ffmpeg:
    vaapi_input: -hwaccel vaapi -hwaccel_output_format nv12 -fflags nobuffer -flags
      low_delay -i {input}
      #  qsv_input: "-hwaccel h264_qsv -hwaccel_output_format nv12 -fflags nobuffer -flags low_delay -i {input}"
    vaapi_h264: -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0
      -codec:a copy
      #  qsv_h264: "-c:v h264_qsv -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0"
    timestamp: >-
      -vf "drawtext=text='%{localtime}':x=w/25:y=(h-th)-h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2,format=vaapi|nv12,hwupload"

  streams:

    # stream baby camera ====================================================================
#     baby:
#       - 'rtsp://{FRIGATE_CAM_BABY_USER}:{FRIGATE_CAM_BABY_PASSWORD}@10.27.0.221:554/stream1'
# #      - "ffmpeg:baby#audio=opus" # required by WebRTC
#     baby_sub:
#       - 'rtsp://{FRIGATE_CAM_BABY_USER}:{FRIGATE_CAM_BABY_PASSWORD}@10.27.0.221:554/stream2'
# #      - "ffmpeg:baby_sub#audio=opus" # required by WebRTC

    # stream backyard ====================================================================
    backyard:
      - rtsp://{FRIGATE_CAM_AMCREST_USER}:{FRIGATE_CAM_AMCREST_PASSWORD}@10.27.3.3:554/cam/realmonitor?channel=1&subtype=0
#      - "ffmpeg:backyard#audio=opus" # required by WebRTC
    backyard_sub:
      - rtsp://{FRIGATE_CAM_AMCREST_USER}:{FRIGATE_CAM_AMCREST_PASSWORD}@10.27.3.3:554/cam/realmonitor?channel=1&subtype=2
#      - "ffmpeg:backyard_sub#audio=opus" # required by WebRTC

    # stream frontyard ===================================================================
    frontyard:
      - rtsp://{FRIGATE_CAM_AMCREST_USER}:{FRIGATE_CAM_AMCREST_PASSWORD}@10.27.3.2:554/cam/realmonitor?channel=1&subtype=0
#      - "ffmpeg:frontyard#audio=opus" # required by WebRTC
    frontyard_sub:
      - rtsp://{FRIGATE_CAM_AMCREST_USER}:{FRIGATE_CAM_AMCREST_PASSWORD}@10.27.3.2:554/cam/realmonitor?channel=1&subtype=2
#      - "ffmpeg:frontyard_sub#audio=opus" # required by WebRTC

    # stream shed ========================================================================
    shed:
      - rtsp://{FRIGATE_CAM_AMCREST_USER}:{FRIGATE_CAM_AMCREST_PASSWORD}@10.27.3.6:554/cam/realmonitor?channel=1&subtype=0
#      - "ffmpeg:shed#audio=opus" # required by WebRTC
    shed_sub:
      - rtsp://{FRIGATE_CAM_AMCREST_USER}:{FRIGATE_CAM_AMCREST_PASSWORD}@10.27.3.6:554/cam/realmonitor?channel=1&subtype=2
#      - "ffmpeg:shed_sub#audio=opus" # required by WebRTC

    # stream video doorbell ==============================================================
    video_doorbell_raw:
      # restreamed from HASS integration hass-expose-camera-stream-source. Please refer to 
      # https://github.com/felipecrs/hass-expose-camera-stream-source
      - echo:/config/get_ha_stream.sh camera.hello_video_doorbell
    video_doorbell:
      # restream from doorbell_raw above with time stamp added. Please refer to
      # https://github.com/AlexxIT/go2rtc/issues/402#issuecomment-1606026909
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/video_doorbell_raw#input=vaapi_input#video=vaapi_h264#audio=copy#raw=timestamp
#      - "ffmpeg:doorbell#audio=opus" # required by WebRTC


# cameras
# ========================================================================================
cameras:

  # Camera ========================== Baby ===========================================
#   baby: # <------ Name the camera
#     ffmpeg:
#       inputs:
#         - path: 'rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/baby_sub'
#           input_args: preset-rtsp-restream-low-latency
#           roles:
#             - detect
#         - path: 'rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/baby'
#           input_args: preset-rtsp-restream-low-latency
#           roles:
#             - record
#     birdseye:
#       mode: continuous
#       order: 4
#     live:
# #      stream_name: baby_sub # prefer sub channel for live stream
#       stream_name: baby # default main channel for live stream
#     motion:
#       mask:
#         # cover the whole screen to skip motion detection
#         - 0,360,640,360,640,0,0,0
#     detect:
#       enabled: false
#     # Optional: Configuration for how camera is handled in the GUI.
#     ui:
#       # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
#       # By default the cameras are sorted alphabetically.
#       order: 4
#       # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
#       dashboard: True

  # Camera ========================== Backyard ===========================================
  backyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    birdseye:
      mode: continuous
      order: 3
    live:
#      stream_name: backyard_sub # prefer sub channel for live stream
      stream_name: backyard # default main channel for live stream
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:
        - 1,0,1,0.422,0.916,0.489,0.859,0.45,0.817,0.279,0.694,0.287,0.686,0.137,0.691,0
        - 0,0.312,0.041,0.114,0.082,0.093,0.091,0,0,0
        - 0.473,0.129,0.642,0.115,0.652,0,0.124,0,0.127,0.188
    objects:
      track:
        - person
        - dog
        - cat
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 3000
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: true
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 1
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

  # Camera ========================== Frontyard ==========================================
  frontyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/frontyard_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    birdseye:
      mode: continuous
      order: 1
    live:
#      stream_name: frontyard_sub # prefer sub channel for live stream
      stream_name: frontyard # default channel for live stream
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,0,0.318,0,0.323,0.189,0.227,0.21,0.066,0.272,0,0.396
        - 0.784,0,1,0,1,1,0.837,1,0.911,0.775,0.958,0.513,0.969,0.189,0.944,0.171,0.94,0.088,0.785,0.087
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          max_area: 120000
          mask:
            - 0,169,0,293,417,194,411,106
        cat:
          max_area: 22000
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: true
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

  # Camera ========================== Shed ===============================================
  shed: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/shed_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/shed
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    birdseye:
      mode: continuous
      order: 2
    live:
#      stream_name: shed_sub # prefer sub channel for live stream
      stream_name: shed # default main channel for live stream
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,1,0.312,1,0.348,0.465,0.428,0.283,0.391,0.161,0.551,0.107,0.535,0,0.393,0,0,0
        - 0.96,0.097,0.961,0.035,0.786,0.033,0.785,0.093
    objects:
      track:
        - person
        - dog
        - cat
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 10000
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: true
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 2
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

  # Camera ========================== Video Doorbell ================================
  video_doorbell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_GO2RTC_USER}:{FRIGATE_GO2RTC_PASSWORD}@127.0.0.1:8554/video_doorbell
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    birdseye:
      mode: continuous
      order: 0
    live:
      stream_name: video_doorbell # default channel for live stream
      # Optional: Set the height of the jsmpeg stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
      height: 1200
      # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8
      # Optional: in-feed timestamp style configuration
      # NOTE: Can be overridden at the camera level
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1600 # <---- update for your camera's resolution
      height: 1200 # <---- update for your camera's resolution
      fps: 5 # <---- update for your camera's fps
      stationary:
        interval: 50
        threshold: 150 # <---- video doorbell fps is 15 which is 3 times the default. Hence the default threshold should be 3 times as well.
    motion:
      mask:
        - 0,0,1600,0,1600,571,428,580,0,276
        - 60,1160,580,1160,580,1110,60,1110
    objects:
      track:
        - person
        - dog
        - cat
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          mask:
            - 0,0,1600,0,1600,582,706,599,0,780
          min_area: 40000
        dog:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          max_area: 50000
    # Optional: Configuration for the jpeg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: true
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 3
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
version: 0.14
camera_groups:
  Front:
    order: 1
    icon: LuDoorClosed
    cameras:
      - frontyard
      - video_doorbell
  back:
    order: 2
    icon: LuFlower2
    cameras:
      - backyard
      - shed
```

### Relevant log output

```shell
2024-08-11 22:50:50.061340072  10.27.0.40 - - [11/Aug/2024:22:50:50 +0100] "GET /api/preview/all/start/1723323600/end/1723413600 HTTP/1.1" 404 49 "https://frigate.home.arpa/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" "10.27.2.14"
2024-08-11 22:51:09.995134975  10.27.0.40 - - [11/Aug/2024:22:51:09 +0100] "GET /api/review/summary?timezone=Europe%2FLondon HTTP/1.1" 200 585 "https://frigate.home.arpa/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" "10.27.2.14"
2024-08-11 22:51:14.801256415  127.0.0.1 - - [11/Aug/2024:22:51:14 +0100] "" 400 0 "-" "-" "-"
2024-08-11 22:51:15.086698077  10.27.0.40 - - [11/Aug/2024:22:51:15 +0100] "GET /api/preview/all/start/1723323600/end/1723413600 HTTP/1.1" 404 49 "https://frigate.home.arpa/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" "10.27.2.14"
2024-08-11 22:51:18.519289417  127.0.0.1 - - [11/Aug/2024:22:51:18 +0100] "GET / HTTP/1.1" 200 6837 "-" "curl/7.74.0" "-"
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua, Nest Video Doorbell via HA integration "Expose Camera Stream Source"
