### DISCUSSION TITLE
[Config Support]: I want to stream an event on Google Nest Hub but video clip.mp4 seems to be incompatible

### DISCUSSION THREAD

**Discussion by StefanoGiu** [blakeblackshear/frigate#12978] [Config Support]
### Describe the problem you are having

I'm using the following service call to stream events on Google Nest Hub

service: media_player.play_media
data:
  media_content_id: https://HAURL/api/frigate/notifications/EVENTID/clip.mp4
  media_content_type: video
  entity_id: media_player.XXXX
  
This works perfectly with a set of cameras (12) which has max resolution of 1280x720. Instead I have 5 cameras with resolution 2304x1296 and when I run the above command, I can hear only the audio on Google Nest Hub, not the video.

I want to keep the resolution high for motion detect, streaming, object recognition etc... 

Any suggestion?

### Version

0.14

### Frigate config file

```yaml
go2rtc:
  streams:
    Viale:
      - rtsp://XX:XX@XX.XX.XX.XX:XX/Streaming/Channels/101
      - ffmpeg:Viale#audio=aac

cameras:
  Viale:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Viale 
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 
        1,0,1,0.328,0.941,0.283,0.884,0.244,0.883,0.126,0.727,0.09,0.502,0.031,0.389,0.044,0.366,0.137,0.27,0.153,0.27,0.242,0.275,0.344,0.219,0.314,0.164,0.263,0.108,0.208,0.034,0.225,0.079,0.747,0.127,1,0,1,0,0.275,0,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
```

### Relevant log output

```shell
No error
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral
