### DISCUSSION TITLE
[Support]: /tmp/cache UI storage size is different to container config from docs

### DISCUSSION THREAD

**Discussion by RutgerDiehard** [blakeblackshear/frigate#12979] [General Support] [answered]
### Describe the problem you are having

I have Frigate 0.14 running in a container on bare metal Linux using the configuration from the docs. After the upgrade to 0.14, the UI reports the /tmp/cache storage size as 100GiB whereas the storage defined in Docker Compose is 1GiB:

- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

![image](https://github.com/user-attachments/assets/9353421f-a737-448c-b515-303d822f4670)

I've restarted the container multiple times but the /tmp/cache storage never clears, it constantly increases. Is this normal?

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: IP
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: USER
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: PASSWORD
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3
record:
  # Optional: Enable recording (default: shown below)
  enabled: true
  # Optional: Number of days to retain recordings regardless of events (default: shown below)
  # NOTE: This should be set to 0 and retention should be defined in events section below
  #       if you only want to retain recordings of events.
  retain:
    days: 0
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    # max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    # required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Per object retention days
      objects:
        person: 15
go2rtc:
  streams:
    Drive:
      - ffmpeg:rtsp://USER:PASSWORD@IP:554/h265Preview_01_main#video=copy#audio=copy#audio=aac
    Drive_Sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=USER&password=PASSWORD
    Front_Door:
      - ffmpeg:rtsp://USER:PASSWORD@IP:554/h265Preview_01_main#video=copy#audio=copy#audio=aac
    Front_Door_Sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=USER&password=PASSWORD
    Garage_1:
      - ffmpeg:rtsp://USER:PASSWORD@IP:554/h264Preview_02_main
    Garage_1_Sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel1_ext.bcs&user=USER&password=PASSWORD
    Side:
      - ffmpeg:rtsp://USER:PASSWORD@IP:554/h264Preview_06_main
    Side_Sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel5_ext.bcs&user=USER&password=PASSWORD
cameras:
  Front_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac  
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Door_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#    live:
#      stream_name: Front_Door_Sub
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
      filters:
        dog:
          mask: 471,349,469,439,533,443,534,347
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
      required_zones:
        - drive_zone
        - drive_parking_zone
        - drive_path_zone
    zones:
      drive_zone:
        coordinates: 476,58,278,301,44,207,21,125,132,63,118,0,324,0,476,0
        objects:
          - person
          - car
          - dog
      drive_parking_zone:
        coordinates: 0.312,0.589,0.634,0.785,0.576,1,0.944,1,1,0.613,1,0,0.531,0,0.532,0.115
        objects:
          - person
          - dog
        inertia: 3
        loitering_time: 0
      drive_path_zone:
        coordinates: 0,1,0.519,1,0.589,0.765,0.04,0.399,0,0.112
        objects:
          - person
          - dog
        inertia: 3
        loitering_time: 0
      street_zone:
        coordinates: 0.002,0.002,0.097,0,0.132,0,0.146,0.118,0.016,0.245,0,0.114
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0.717,0.92,0.718,0.978,0.29,0.981,0.29,0.92
      threshold: 50
      contour_area: 20
      improve_contrast: 'true'
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    review:
      alerts:
        required_zones:
          - drive_zone
          - drive_parking_zone
          - drive_path_zone
  Drive:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Drive
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Drive_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
      required_zones:
        - drive_zone
        - drive_parking_zone
        - drive_path_zone
    zones:
      drive_parking_zone:
        coordinates: 0,512,534,512,684,384,504,262,316,132,315,62,0,173
        objects:
          - person
          - dog
      drive_path_zone:
        coordinates: 537,512,800,512,827,450,683,383
        objects:
          - person
          - dog
      drive_zone:
        coordinates: 
          1,0.296,1,0.564,0.921,0.873,0.764,0.749,0.352,0.252,0.355,0.122,0.362,0.106,0.731,0.189
        objects:
          - person
          - car
          - dog
        inertia: 3
        loitering_time: 0
      close_zone:
        coordinates: 0,0.339,0.173,0.227,0.353,0.118,0.336,0,0,0
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 1,0,1,0.301,0.735,0.188,0.366,0.104,0.339,0
        - 0.712,0.93,0.712,0.975,0.296,0.979,0.296,0.93
        - 0.181,0.229,0.362,0.137,0.35,0,0.183,0,0.157,0.061
        - 0.153,0.24,0.16,0.154,0.126,0.102,0.056,0.096,0.013,0.154,0.027,0.221
        - 0.002,0.146,0.039,0.121,0.064,0.068,0.037,0.021,0,0.043
        - 0.146,0.002,0.135,0.027,0.114,0.006
      threshold: 50
      contour_area: 30
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    review:
      alerts:
        required_zones:
          - drive_zone
          - drive_parking_zone
          - drive_path_zone
  Garage_1:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage_1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_1_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    motion:
      mask: 0.292,0.926,0.704,0.927,0.704,0.968,0.291,0.968
  Side:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Side_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
      filters:
        person: {}
      mask: 
        0.428,0.483,0.46,0.351,0.515,0.274,0.605,0.278,0.678,0.342,0.713,0.397,0.695,0.537,0.688,0.581,0.539,0.588,0.444,0.593
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    motion:
      mask:
        - 0.292,0.926,0.704,0.927,0.704,0.968,0.291,0.968
        - 0.001,0.708,0.272,0.446,0.396,0.288,0.691,0.001,0.001,0.001
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      side_garden_zone:
        coordinates: 
          0.3,0.607,0.69,0.584,0.717,0.375,0.735,0.314,0.731,0.224,0.815,0.221,0.823,0.437,0.818,0.68,0.804,1,0.372,1,0.316,0.909
        inertia: 3
        loitering_time: 0
        objects: person
      top_garden_zone:
        coordinates: 
          0.429,0.371,0.422,0.261,0.693,0,0.791,0,0.813,0.218,0.726,0.221,0.73,0.314,0.714,0.368
        inertia: 3
        loitering_time: 0
        objects: person
version: 0.14
camera_groups:
  Front:
    order: 1
    icon: LuBuilding2
    cameras:
      - Drive
      - Front_Door
```

### Relevant log output

```shell
Docker Compose:

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "100mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructi>
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your h>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/USER/frigate/config:/config
      - /home/USER/go2rtc:/config/go2rtc
      - /home/USER/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8123:8123"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD"
```

### FFprobe output from your camera

```shell
Not required
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink 5mp and 8mp

**Comment by NickM-27** [comment]
it looks like the tmpfs definition is not being applied, notice that the size of tmpfs and recordings is the same meaning it is likely using the same drive. What is your docker compose

**Reply by RutgerDiehard** [reply]
I've included in the log output section, but included here for convenience:

`Docker` Compose:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "100mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructi>
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your h>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/USER/frigate/config:/config
      - /home/USER/go2rtc:/config/go2rtc
      - /home/USER/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8123:8123"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD"``
```

**Reply by RutgerDiehard** [reply]
Thanks for the edit @NickM-27, you beat me to it!

**Reply by RutgerDiehard** [reply]
Might this be the answer:

https://github.com/docker/compose/issues/5907

**Reply by RutgerDiehard** [reply, marked as answer]
Yes, the tmpfs is being ignored as mentioned in link above.

I've changed to this:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "100mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructi>
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your h>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/USER/frigate/config:/config
#      - /home/USER/config.yml:/config/config.yml
      - /home/USER/go2rtc:/config/go2rtc
      - /home/USER/frigate:/media/frigate
#      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
#        target: /tmp/cache
#        tmpfs:
#          size: 1000000000
    tmpfs:
     - /tmp/cache:exec,size=1G
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8123:8123"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD"

```

And it is sized it correctly:

<img width="1678" alt="image" src="https://github.com/user-attachments/assets/bad2d081-537b-4773-bb44-d65e8301d0cd">
