### DISCUSSION TITLE
[Support]: Frigate crashing

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#12981] [General Support]
### Describe the problem you are having

Hi,

My setup is as follows:
- Intel NUC (i7-1165G7 + 32GB RAM).
- Proxmox running VM Home Assistant OS 12.4.
- Home Assistant running Frigate (Full Access) version 0.14.0-da913d8
- Coral.ai USB Accelerator

Since upgrading to 0.14.0-da913d8 I've discovered my instance of Frigate tends to crash after ~10 hours of use. Other than the upgrade I've made no significant changes though there is a chance it's not the upgrade causing the issue. It just so happens I noticed the issue now when paying closer attention and as a result have disabled "Watchdog" so I'm more aware of if/when it occurs.

The issue I'm getting is the add-on appears to crash.

### Steps to reproduce

Running Frigate NVR for a reasonable period of time and it will crash (in my instance).

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.14
  port: 1883
  user: mqtt-user
  password: password
  topic_prefix: frigate

logger:
  # Optional: default log level (default: shown below). Available log levels are: debug, info, warning, error, critical
  default: info

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    driveway_stream:
      - rtsp://username:password@192.168.1.65:554/stream1
      - ffmpeg:driveway_stream#audio=aac
    living_room_stream:
      - rtsp://username:password@192.168.1.43:554/stream1
      - ffmpeg:living_room_stream#audio=aac
    kitchen_worktop_stream:
      - rtsp://username:password@192.168.1.44:554/stream1
    kitchen_cat_stream:
      - rtsp://username:password@192.168.1.30:554/stream1
    bedroom_2_cat_stream:
      - rtsp://username:password@192.168.1.24:554/stream1
    bedroom_3_stream:
      - rtsp://username:password@192.168.1.56:554/stream1
      - ffmpeg:bedroom_3_stream#audio=aac
    front_stream:
      - rtsp://username:password@192.168.1.75:554/Preview_01_main

cameras:
  living_room_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_stream
          roles:
            - record
          input_args: preset-rtsp-generic
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    detect:
      enabled: false  # This disables detection for this camera
  kitchen_worktop_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_worktop_stream
          roles:
            - record
            - detect
          input_args: preset-rtsp-generic
    motion:
      mask: 0,73,632,73,637,0,0,0
    objects:
      track:
        - person
        - cat
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 7
          mode: all
    zones:
      worktop:
        coordinates: 345,538,521,470,979,470,1041,557,1440,561,1416,458,1223,383,1236,0,157,0,157,534
        objects:
          - cat
    review:
      alerts:
        required_zones:
          - worktop
  kitchen_cat_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_cat_stream
          roles:
            - detect
            - record
          input_args: preset-rtsp-generic
    motion:
      mask: 0,73,632,73,637,0,0,0
    objects:
      track:
        - cat
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 7
  bedroom_2_cat_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_2_cat_stream
          roles:
            - detect
            - record
          input_args: preset-rtsp-generic
    motion:
      mask: 0,0.076,0.324,0.078,0.325,0,0,0
    objects:
      track:
        - cat
    zones:
      zone_eating:
        coordinates: 0,1,1,1,0.912,0.336,0.502,0.298,0.485,0,0,0
        inertia: 3
        loitering_time: 0
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 7
    review:
      alerts:
        required_zones: zone_eating
  bedroom_3_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_3_stream
          roles:
            - detect
            - record
          input_args: preset-rtsp-generic
    detect:
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
    motion:
      mask:
        - 0,73,632,73,637,0,0,0
    objects:
      track:
        - cat
  driveway_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_stream
          roles:
            - record
            - detect
          input_args: preset-rtsp-generic
    motion:
      mask: 0,73,632,73,637,0,0,0
    objects:
      track:
        - person
        - cat
    detect:
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 7
          mode: all
  front_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_stream
          roles:
            - record
            - detect
          input_args: preset-rtsp-generic
    motion:
      mask: 0,73,778,72,787,0,0,0
    objects:
      track:
        - person
        - cat
    detect:
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 1
          mode: all
version: 0.14
camera_groups:
  Cats:
    order: 1
    icon: LuCat
    cameras:
      - bedroom_2_cat_stream
      - kitchen_cat_stream
```

### Relevant log output

```shell
2024-08-12 10:55:58.964676441  [INFO] Service Frigate exited with code 256 (by signal 9)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service certsync: stopping
2024-08-12 10:55:59.016244238  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service certsync successfully stopped
s6-rc: info: service nginx: stopping
2024-08-12 10:55:59.017546106  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
s6-rc: info: service certsync-log: stopping
s6-rc: info: service go2rtc-healthcheck successfully stopped
s6-rc: info: service certsync-log successfully stopped
2024-08-12 10:55:59.121624880  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-08-12 10:55:59.152792045  exit with signal: terminated
s6-rc: info: service frigate-log successfully stopped
2024-08-12 10:55:59.200163532  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink CX810, Tapo C110, Tapo C210
