### DISCUSSION TITLE
[Config Support]: Home Assistant intergration with newly authenticated UI on 0.14

### DISCUSSION THREAD

**Discussion by tzalistar** [blakeblackshear/frigate#12994] [Config Support]
### Describe the problem you are having

Hello,

I've recenty updated to version 0.14 with the main reason being the built-in authentication. While the setup works just fine, if i try to add my frigate instance to my Home Assistant via the intergration by using the autenticated endpoint on 8971. Adding an instance using 5000 works as exected. I tried putting the credentials in-line with URL with the usual way http://user:pass@frigate:8971 but no luck there either.

My  topology consist with a VM running HassOS and a another running the docker container of frigate and deepstack.

Is there something wrong with my setup or something i'm missing? Unless i must wait for the HACS intergration to support authenticated instances.

BR

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: ommitted
  port: 1883
  user: ommitted
  password: ommitted

cameras:
  garden_01:
    birdseye:
      mode: objects
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://"ommitted"/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://"ommitted"/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    best_image_timeout: 60
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.791,0.07,0.804,0.073,0.883,0.066,0.916,0.123,0.967,0.135,1,0,1
  garage_01:
    birdseye:
      mode: objects
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://"ommitted"/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://"ommitted"/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    best_image_timeout: 60
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 
        0.558,1,0.542,0.944,0.486,0.949,0.45,0.891,0.426,0.821,0.41,0.742,0.386,0.698,0.359,0.695,0.335,0.683,0.355,0.591,0.365,0.546,0.375,0.476,0.392,0.318,0.391,0.228,0.356,0.092,0.293,0,0,0,0,1
auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.18.0.0/16 # <---- this is the subnet for the internal docker compose network
    - x.x.x.2/23
    - x.x.x.254/23
    - x.x.x.253/23

detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects

detectors:
  deepstack:
    api_url: http://codeproject-ai-server-cuda:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.2


birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous


database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db

logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

tls:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264
version: 0.14
```

### Relevant log output

```shell
No log output
```

### Frigate stats

```json
{
    "cameras": {
        "garage_01": {
            "audio_dBFS": 0.0,
            "audio_rms": 0.0,
            "camera_fps": 0.0,
            "capture_pid": 343,
            "detection_enabled": true,
            "detection_fps": 0.0,
            "ffmpeg_pid": 812,
            "pid": 333,
            "process_fps": 0.0,
            "skipped_fps": 0.0
        },
        "garden_01": {
            "audio_dBFS": 0.0,
            "audio_rms": 0.0,
            "camera_fps": 0.0,
            "capture_pid": 340,
            "detection_enabled": true,
            "detection_fps": 0.0,
            "ffmpeg_pid": 809,
            "pid": 332,
            "process_fps": 0.0,
            "skipped_fps": 0.0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "114": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "123": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "1.3",
            "cpu_average": "4",
            "mem": "3.8"
        },
        "143": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "205": {
            "cmdline": "nginx: worker process",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "206": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "24": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "250": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "275": {
            "cmdline": "sleep 9999",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "283": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "285": {
            "cmdline": "frigate.recording_manager",
            "cpu": "4.3",
            "cpu_average": "2",
            "mem": "0.9"
        },
        "286": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "29": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "315": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "316": {
            "cmdline": "frigate.detector.deepstack",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "317": {
            "cmdline": "frigate.output       ",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.8"
        },
        "32": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "332": {
            "cmdline": "frigate.process:garden_01",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.8"
        },
        "333": {
            "cmdline": "frigate.process:garage_01",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.8"
        },
        "34": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "340": {
            "cmdline": "frigate.capture:garden_01",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "341": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "343": {
            "cmdline": "frigate.capture:garage_01",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "360": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "377": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@"ommitted"/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garden_01@%Y%m%d%H%M%S%z.mp4",
            "cpu": "3.0",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "379": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "380": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@"ommitted"/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage_01@%Y%m%d%H%M%S%z.mp4",
            "cpu": "2.5",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "45": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "46": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "789": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "84": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "85": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "97": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "frigate.full_system": {
            "cpu": "21.5",
            "mem": "50.1"
        }
    },
    "detection_fps": 0.0,
    "detectors": {
        "deepstack": {
            "detection_start": 0.0,
            "inference_speed": 10.0,
            "pid": 316
        }
    },
    "gpu_usages": {
        "error-gpu": {
            "gpu": "",
            "mem": ""
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 97
        },
        "logger": {
            "pid": 283
        },
        "recording": {
            "pid": 285
        },
        "review_segment": {
            "pid": 286
        }
    },
    "service": {
        "last_updated": 1723463944,
        "latest_version": "0.14.0",
        "storage": {
            "/dev/shm": {
                "free": 127.0,
                "mount_type": "tmpfs",
                "total": 128.0,
                "used": 1.0
            },
            "/media/frigate/clips": {
                "free": 1975783.6,
                "mount_type": "xfs",
                "total": 5721127.6,
                "used": 3745343.9
            },
            "/media/frigate/recordings": {
                "free": 1975783.6,
                "mount_type": "xfs",
                "total": 5721127.6,
                "used": 3745343.9
            },
            "/tmp/cache": {
                "free": 893.6,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 60.0
            }
        },
        "temperatures": {},
        "uptime": 270,
        "version": "0.14.0-da913d8"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Other
