### DISCUSSION TITLE
[Bug]: Audio Detect. Cant' enable if it's not enabled at startup

### DISCUSSION THREAD

**Discussion by JuanDYB** [blakeblackshear/frigate#12993] [Report a Bug] [answered]
### Describe the problem you are having

I'm not sure if it is a bug but I have noticed strange behaviour in how is enabled.
With record and snapshot I can set settings in `yaml` but I can setup as disabled on startup per camera like this.
```
record:
  enabled: true
  retain:
    days: 3
    mode: motion

snapshots:
  enabled: true
  retain:
    default: 10

cameras:
  cam1:
    record:
      enabled: false
    snapshots:
      enabled: false
```
With this configuration I'm able to enable record and snapshots whenever I want using HA integration.

But for audio, with same method configuration I can't enable after startup audio detection. In HA integration the switch is not available and also in Frigate UI, the icon to enable/disable audio detection is not available.
```
audio:
  enabled: true
  listen:
    - bark
cameras:
  cam1:
    audio:
      enabled: False
```
So, seems the only way to enable audio detection is to have it enabled in `config.yaml`. If it's disabled in `config.yaml` file it's not possible to enable it after.

### Steps to reproduce

Set audio detection as enabled and set audio in camera as disabled.
```
audio:
  enabled: true
  listen:
    - bark
cameras:
  cam1:
    audio:
      enabled: False
```

### Version

0.14.0

### Frigate config file

```yaml
audio:
  enabled: true
  listen:
    - bark
cameras:
  cam1:
    audio:
      enabled: False
```

### Relevant log output

```shell
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink E1 zoom
