### DISCUSSION TITLE
Error adding `review` section to config and parked car detection

### DISCUSSION THREAD

**Discussion by dparson55** [blakeblackshear/frigate#13008] [Config Support] [answered]
### Describe the problem you are having

Frigate fails to boot and logs an error when I copy and paste the example section from the docs. The config editor UI shows that `review` is not allowed so I used an external editor to try forcing it in to no avail.

https://docs.frigate.video/configuration/zones#restricting-alerts-and-detections-to-specific-zones
![image](https://github.com/user-attachments/assets/b3c26a16-fc24-4671-8f55-ff87470a42b2)

![image](https://github.com/user-attachments/assets/becd6c0c-37bc-4680-986e-0de143ff5f0f)

Ultimately I'm trying, and failing, to prevent car events outside my `front_road` zone. I'm probably not understanding this part of the configuration.
![image](https://github.com/user-attachments/assets/6429a7b4-ceae-4316-8cdd-f7f99a32a923)

I added the configuration described above and my events UI is still showing a car was detected outside of the `front_road` zone (`None` is in the zone dropdown), so I'm just having trouble understanding what is happening and the troubleshooting led me to try adding the `review` section that is not working.
![image](https://github.com/user-attachments/assets/4dc61dcc-42f6-4c7a-9821-2a4dec786c32)
![image](https://github.com/user-attachments/assets/7caad7a6-cf32-4f35-8f1f-b81d751ab1b9)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: rp1

birdseye:
  enabled: false
  
cameras:
  wuuk1:
    review:
      alerts:
        required_zones:
          - north_road
      detections:
        required_zones:
          - north_road
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://wuuk1.lan/ch0
        roles:
          - record
      - path: rtsp://wuuk1.lan/ch1
        roles:
          - detect
    detect:
      enabled: true
      width: 640
      height: 360
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - truck
    snapshots:
      enabled: true
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 5
    motion:
      threshold: 40
      mask:
        - 640,0,640,297,533,275,391,189,199,112,0,125,203,249,495,360,0,360,0,0
    zones:
      north_view:
        coordinates: 538,281,640,327,640,360,501,360,200,242,29,149,43,129,102,142,225,117,228,142,207,161,437,204
        objects:
          - person
          - cat
          - dog
      north_road:
        coordinates: 309,211,266,264,113,191,35,145,55,138,107,156,158,148,178,156,175,172
        objects:
          - car
          - truck
    onvif:
      host: wuuk1.lan
      port: 80
      user: thingino
      password: thingino
  wyze1:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://wyze1.lan/ch0
        roles:
          - record
          - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      retain:
        default: 5
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 5
    motion:
      threshold: 40
      mask:
      - 1920,0,1920,410,0,410,0,0
      - 1920,410,1920,1080,748,1080,748,410
    zones:
      front_porch:
        coordinates: 0,1080,0,439,301,441,315,976,428,979,418,830,479,836,479,683,591,680,592,455,717,450,724,1080
      front_sidewalk:
        coordinates: 564,425,577,672,457,669,463,812,413,814,418,913,339,907,328,431
```

### Relevant log output

```shell
2024-08-12 12:30:06.121470895  [INFO] Preparing Frigate...
2024-08-12 12:30:06.123720500  [INFO] Starting NGINX...
2024-08-12 12:30:06.127686553  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-08-12 12:30:06.178073748  [INFO] Starting Frigate...
2024-08-12 12:30:06.751727421  [INFO] Starting go2rtc...
2024-08-12 12:30:06.849157543  12:30:06.849 INF go2rtc version 1.8.4 linux/amd64
2024-08-12 12:30:06.850077696  12:30:06.849 INF [rtsp] listen addr=:8554
2024-08-12 12:30:06.850101346  12:30:06.849 INF [api] listen addr=:1984
2024-08-12 12:30:06.850380577  12:30:06.850 INF [webrtc] listen addr=:8555
2024-08-12 12:30:08.092537805  2024/08/12 12:30:08 [error] 143#143: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.249, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "server2:5000"
2024-08-12 12:30:08.092666918  192.168.2.249 - - [12/Aug/2024:12:30:08 -0700] "GET /ws HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" "-"
2024-08-12 12:30:08.322005803  [2024-08-12 12:30:08] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-08-12 12:30:08.343464648  *************************************************************
2024-08-12 12:30:08.343470790  *************************************************************
2024-08-12 12:30:08.343476365  ***    Your config file is not valid!                     ***
2024-08-12 12:30:08.343479296  ***    Please check the docs at                           ***
2024-08-12 12:30:08.343481530  ***    https://docs.frigate.video/configuration/index     ***
2024-08-12 12:30:08.343517653  *************************************************************
2024-08-12 12:30:08.343519906  *************************************************************
2024-08-12 12:30:08.343522358  ***    Config Validation Errors                           ***
2024-08-12 12:30:08.343524275  *************************************************************
2024-08-12 12:30:08.343598049  1 validation error for FrigateConfig
2024-08-12 12:30:08.343602487  cameras -> wuuk1 -> review
2024-08-12 12:30:08.343605057    extra fields not permitted (type=value_error.extra)
2024-08-12 12:30:08.345102730  Traceback (most recent call last):
2024-08-12 12:30:08.345106770    File "/opt/frigate/frigate/app.py", line 645, in start
2024-08-12 12:30:08.345108612      self.init_config()
2024-08-12 12:30:08.345110418    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024-08-12 12:30:08.345112097      user_config = FrigateConfig.parse_file(config_file)
2024-08-12 12:30:08.345113831    File "/opt/frigate/frigate/config.py", line 1346, in parse_file
2024-08-12 12:30:08.345115354      return cls.parse_obj(config)
2024-08-12 12:30:08.345117089    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2024-08-12 12:30:08.345118813    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2024-08-12 12:30:08.345120622  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2024-08-12 12:30:08.345124546  cameras -> wuuk1 -> review
2024-08-12 12:30:08.345127064    extra fields not permitted (type=value_error.extra)
2024-08-12 12:30:08.345182764  
2024-08-12 12:30:08.345185840  *************************************************************
2024-08-12 12:30:08.345188293  ***    End Config Validation Errors                       ***
2024-08-12 12:30:08.345219477  *************************************************************
```

### Frigate stats

```json
{
  "cameras": {
    "wuuk1": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 321,
      "detection_enabled": 1,
      "detection_fps": 2.9,
      "ffmpeg_pid": 66699,
      "pid": 314,
      "process_fps": 1.4,
      "skipped_fps": 3.8
    },
    "wyze1": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 318,
      "detection_enabled": 1,
      "detection_fps": 2.9,
      "ffmpeg_pid": 88806,
      "pid": 313,
      "process_fps": 2.4,
      "skipped_fps": 2.7
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "43": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "83": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "102": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "293.6",
      "cpu_average": "1",
      "mem": "10.3"
    },
    "103": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "122": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "151": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.2"
    },
    "162": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "295": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "2.4"
    },
    "297": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.0",
      "cpu_average": "2",
      "mem": "3.9"
    },
    "306": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(47)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "307": {
      "cmdline": "frigate.detector.cpu ",
      "cpu": "289.8",
      "cpu_average": "76",
      "mem": "3.4"
    },
    "309": {
      "cmdline": "frigate.output       ",
      "cpu": "0.4",
      "cpu_average": "1",
      "mem": "3.2"
    },
    "313": {
      "cmdline": "frigate.process:wyze1",
      "cpu": "2.8",
      "cpu_average": "3",
      "mem": "3.9"
    },
    "314": {
      "cmdline": "frigate.process:wuuk1",
      "cpu": "2.7",
      "cpu_average": "4",
      "mem": "3.5"
    },
    "316": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "318": {
      "cmdline": "frigate.capture:wyze1",
      "cpu": "3.0",
      "cpu_average": "6",
      "mem": "3.5"
    },
    "319": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.5"
    },
    "321": {
      "cmdline": "frigate.capture:wuuk1",
      "cpu": "0.5",
      "cpu_average": "1",
      "mem": "3.1"
    },
    "66699": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wuuk1.lan/ch1 -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.0",
      "cpu_average": "2",
      "mem": "0.9"
    },
    "88806": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wyze1.lan/ch0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/wyze1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "15.5",
      "cpu_average": "14",
      "mem": "2.0"
    },
    "88989": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://wuuk1.lan/ch0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/wuuk1@%Y%m%d%H%M%S%z.mp4",
      "cpu": "3.3",
      "cpu_average": "2",
      "mem": "0.6"
    },
    "89134": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 5.8,
  "detectors": {
    "cpu": {
      "detection_start": 1723490488.42472,
      "inference_speed": 178.18,
      "pid": 307
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 90
    },
    "logger": {
      "pid": 295
    },
    "recording": {
      "pid": 297
    }
  },
  "service": {
    "last_updated": 1723490488,
    "latest_version": "0.14.0",
    "storage": {
      "/dev/shm": {
        "free": 51.8,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 12.2
      },
      "/media/frigate/clips": {
        "free": 39756.1,
        "mount_type": "ext4",
        "total": 118651.7,
        "used": 72823.3
      },
      "/media/frigate/recordings": {
        "free": 39756.1,
        "mount_type": "ext4",
        "total": 118651.7,
        "used": 72823.3
      },
      "/tmp/cache": {
        "free": 940.9,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 12.8
      }
    },
    "temperatures": {

    },
    "uptime": 49559,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)
