### DISCUSSION TITLE
[Detector Support]: Cat detected as a person

### DISCUSSION THREAD

**Discussion by abratchik** [blakeblackshear/frigate#13013] [Detector Support]
### Describe the problem you are having

Cats are consistently detected as people thus generating false alarms. Example (posting one but I have many more):
![4b8ca7ce3a3c4e0d85524490ecd7e1f8](https://github.com/user-attachments/assets/5ed87655-f18f-4d1a-9a6a-597702a09b69)

https://github.com/user-attachments/assets/e98686ab-55ad-46ba-ad97-384472b531d2

### Version

0.14.0-da913d8

### Frigate config file

```yaml
version: 0.14
mqtt:
  enabled: true
  topic_prefix: frigate
  client_id: frigate
  host: mqtt
  user: '{FRIGATE_MQTT_USR}'
  password: '{FRIGATE_MQTT_PWD}'

logger:
  default: info

detectors:
  rknn:
    type: rknn
    num_cores: 3
model:
  path: deci-fp16-yolonas_m
  width: 320
  height: 320
  input_tensor: nhwc
  input_pixel_format: bgr

objects:
  track:
    - person

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 7

cameras:
  frontcam:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD}@192.168.0.5/media/video2
          roles:
            - detect
    motion:
      mask: 
        0,0.405,0.001,0.002,0.996,0,1,0.588,0.828,0.324,0.837,0.162,0.584,0.122,0.327,0.111,0.089,0.143,0.085,0.269
  cam1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.6:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
    motion:
      mask: 
        0.002,0.998,0,0.002,0.999,0.002,0.999,0.998,0.724,0.998,0.762,0.321,0.732,0.141,0.49,0.168,0.06,0.996
  cam2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.7:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
    motion:
      mask: 
        0.002,0.006,0.998,0.002,0.998,0.994,0.845,0.996,0.365,0.158,0.195,0.155,0.122,0.998,0,0.996
  cam3:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.8:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
    motion:
      mask: 
        0.002,0.998,0.001,0.002,1,0,0.999,0.998,0.889,1,0.747,0.084,0.633,0.084,0.26,0.998
  cam4:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.9:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
    motion:
      mask: 
        0.001,0.998,0.001,0.002,0.998,0.002,0.999,0.998,0.654,1,0.751,0.105,0.579,0.105,0.11,0.998
  cam5:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.10:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
    motion:
      mask: 
        0.002,0.998,0,0.002,0.998,0,0.999,0.998,0.489,0.16,0.32,0.158,0.293,0.315,0.315,0.996
  cam6:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h265
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.11:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
    motion:
      mask: 
        0,0.994,0,0,0.999,0.002,0.998,0.996,0.732,0.998,0.364,0.303,0.256,0.309,0.146,0.996
```

### docker-compose file or Docker CLI command

```yaml
services:
    mqtt:
      container_name: mqtt
      image: eclipse-mosquitto:2
      restart: unless-stopped
      volumes:
        - /home/ubuntu/config/mqtt:/mosquitto/config
      ports:
        - "1883:1883"
      networks:
        - br0
    frigate:
      container_name: frigate
      image: ghcr.io/blakeblackshear/frigate:0.14.0-rk
      privileged: true 
      restart: unless-stopped
      group_add:
        - "106" # render
        - "44"  # video
        - "46"  # plugdev
      shm_size: "128mb"
      security_opt:
        - apparmor=unconfined
      devices:
        - /dev/dri:/dev/dri
        - /dev/dma_heap:/dev/dma_heap
        - /dev/rga:/dev/rga
        - /dev/mpp_service:/dev/mpp_service
      volumes:
        - /dev/bus/usb:/dev/bus/usb
        - /etc/localtime:/etc/localtime:ro
        - /home/ubuntu/config/frigate/config.yml:/config/config.yml:rw
        - /home/ubuntu/config/frigate/storage:/media/frigate:rw        
        - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: 1000000000
      ports:
        - "5000:5000"
        - "1935:1935"
        - "8554:8554" # RTSP feeds
        - "8555:8555/tcp" # WebRTC over tcp
        - "8555:8555/udp" # WebRTC over udp
      networks:
        - br0
      device_cgroup_rules:
        - "c 189:* rmw"
      env_file:
        - ./.env.client

networks:
  br0:
    name: br0
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

RKNN

### Any other information that may be helpful

My setup is:
Linux ubuntu 6.1.0-1021-rockchip #21-Ubuntu SMP Mon Jul 29 03:52:32 UTC 2024 aarch64 aGNU/Linux
Orange PI5 Plus rk 3588
