### DISCUSSION TITLE
[Config Support]: Help: how to stop detecting and alerting on stationary bicycle in garage when light pixel changes.

### DISCUSSION THREAD

**Discussion by chrislawso** [blakeblackshear/frigate#13010] [Config Support]
### Describe the problem you are having

I've read the docs several times and have been testing configurations and can't find a correct solution.

The camera scene has bicycles standing in the garage which are in direct line of sight from camera to the garage door which is in background. When the garage door opens and closes the dark background changes around the bicycles from dark to light and causes frigate to continue repeatedly triggering detections for bicycle. 

Images of the bike scene, light and dark:
https://ibb.co/QnzSrL8
https://ibb.co/xHXDXmX

What is the correct method to configure frigate to not alert and not identify certain object detections (bicycle) for an area of the camera? How can I disable motion detection and/or object detection in a certain limited area of camera?

The camera in garage I would want to continue to detect people and bikes for the other parts of camera pixel scene when there is motion in some areas of the camera, but not stationary bikes which are triggering light change pixel motion because of moving garage door background.

Docs I read:
https://docs.frigate.video/configuration/object_filters
https://docs.frigate.video/configuration/masks
https://docs.frigate.video/configuration/zones
https://docs.frigate.video/configuration/stationary_objects/

### Version

v14

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
  
go2rtc:
  streams:
    garage:
      - rtsp://un:pw@ip



cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy  
objects:
  track:
    - person
    - bicycle
    - cat
    - dog
record:
  enabled: True
  retain:
    days: 15
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
detect: #default
  stationary:
    interval: 50
    threshold: 50
version: 0.14


```

### Relevant log output

```shell
not applicable
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)
