### DISCUSSION TITLE
[HW Accel Support]:  Cheap GPU which supports H265 video decoding?

### DISCUSSION THREAD

**Discussion by Johnyb62** [blakeblackshear/frigate#13029] [Hardware Acceleration Support]
### Describe the problem you are having

System:
Unraid server running several dockers  (Dell 3020 - Intel® Core™ i5-4570 CPU @ 3.20GHz / 8Gb RAM)
PCI Coral running for detector
Camera:  Annke C800 [(](https://uk.annke.com/products/c800?variant=43505394319572)

I'd like to add a GFX card with hardware decoding to take the burden from the CPU.  The CCTV cameras output H265 so needs to manage this.  Looking for a cheap 2nd hand card from ebay, recommendations welcomed.  Thanks.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  #enabled: false
  host: 192.168.0.63
  user: xxxxxx
  password: xxxxx
  
cameras:
  Front:  # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxx@192.168.0.114:554/Streaming/Channels/102/?transportmode=unicast.sdp # <----- The stream you want to use for detection
          roles:
            - detect
            
        - path: rtsp://xxxxx:xxxxxx@192.168.0.114:554/Streaming/Channels/101/?transportmode=unicast.sdp # <----- The stream you want to use for detection
          roles:
            - record
      #hwaccel_args: preset-vaapi
      
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
      
    objects:
        track:
        - person
        - dog
        - cat
 
    motion:
        mask:
        - 243,0,252,480,0,480,0,0
        - 640,0,522,147,372,99,240,157,212,0
        - 640,23,640,480,529,480,396,480,448,298,610,39
    
    zones:
        Driveway:
            coordinates: 262,480,388,480,432,294,527,167,402,87,188,175
    
    
    record:
        enabled: True
        events:
            retain:
                default: 45
                mode: active_objects
            required_zones:
              - Driveway
                
    snapshots: # <----- Enable snapshots
      enabled: True
      required_zones:
        - Driveway

  Back_1:  # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://xxxxx:xxxxx@192.168.0.114:554/Streaming/Channels/302/?transportmode=unicast.sdp # <----- The stream you want to use for detection
          roles:
            - detect
            - audio
            
        - path: rtsp://xxxxx:xxxxxx@192.168.0.114:554/Streaming/Channels/301/?transportmode=unicast.sdp # <----- The stream you want to use for detection
          roles:
            - record
      
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
      
    objects:
        track:
        - person
        - dog
        - cat

    motion:
        mask:      
        - 448,0,640,0,640,154,640,275,518,291,473,215,405,168,388,92,414,48
        - 0,0,0,231,104,28,189,27,187,0
    
    zones:
        Garden_1:
            coordinates: 545,480,640,361,640,255,582,173,545,285,382,135,450,25,431,0,182,0,0,480
    
    
    record:
        enabled: True
        events:
            retain:
                default: 45
                mode: active_objects
            required_zones:
              - Garden_1
                
    snapshots: # <----- Enable snapshots
      enabled: True
      required_zones:
        - Garden_1
    
    audio:
      enabled: True
      min_volume: 400
      max_not_heard: 30
      listen:
        - bark
      filters:
        bark:
          threshold: 0.5
          
detectors:
  coral_pci:
    type: edgetpu
    device: pci 
#ffmpeg:
#  hwaccel_args: preset-vaapi
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","display_aspect_ratio":"4:3","height":480,"width":640},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","display_aspect_ratio":"16:9","height":2160,"width":3840},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Annke C800
