### DISCUSSION TITLE
[Config Support]: Some camera streams load slow or not at all in Frigate 0.14 Live View

### DISCUSSION THREAD

**Discussion by stalakerob** [blakeblackshear/frigate#13035] [Config Support]
### Describe the problem you are having

I have 4 Reolink cams configured. 2 of them (Garten_Cam and WZ_Cam) load very slow or sometimes not at all in Live View. I also use Home Assistant with the HA custom component and in HA they always load and reasonably fast. I did not experience that with 0.14 Beta 2. It appeared with the release candidates and the final release.  I tried Chrome, Firefox and Edge and there is no difference.
 
Frigate runs on a dedicated system with Intel N100 CPU, 16 GB RAM and Coral TPU. 

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.200
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car

snapshots:
  enabled: true
  retain:
    default: 7

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 7
      mode: motion

birdseye:
  enabled: true
  mode: continuous

go2rtc:
  streams:
    Garten_Cam:
      - ffmpeg:http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxxxxxxxx05
    Garten_Cam_sub:
      - ffmpeg:http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxxxx&password=xxxxxxxxxxx05
    Garten_Cam_ext:
      - ffmpeg:http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxxxxxxxx05

    Carport_Cam:
      - rtsp://xxxxx:xxxxxxxxxxx04@192.168.1.204:554/h264Preview_01_main
    Carport_Cam_sub:
      - rtsp://xxxxx:xxxxxxxxxxx04@192.168.1.204:554/h264Preview_01_sub
    Carport_Cam_ext:
      - http://192.168.1.204/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxxxxxxxx04

    WZ_Cam:
      - rtsp://xxxxx:xxxxxxxxxxx06@192.168.1.206:554/h264Preview_01_main
    WZ_Cam_sub:
      - rtsp://xxxxx:xxxxxxxxxxx06@192.168.1.206:554/h264Preview_01_sub

    Garten_Cam2:
      - rtsp://xxxxx:xxxxxxxxxxx08@192.168.1.208:554/h264Preview_01_main
    Garten_Cam2_sub:
      - rtsp://xxxxx:xxxxxxxxxxx08@192.168.1.208:554/h264Preview_01_sub
    Garten_Cam2_ext:
      - http://192.168.1.208/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxxxxxxxx08


  webrtc:
    candidates:
      - 192.168.1.244:8555
      - stun:8555

cameras:
  Garten_Cam: # <------ Name the camera
    enabled: true
    motion:
      threshold: 25
      contour_area: 8
      improve_contrast: 'true'
      mask:
        - 0.708,0.941,1,0.835,1,1,0.709,1
        - 0.841,0.139,0.916,0.868,1,0.834,1,0.15
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten_Cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten_Cam # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - bird

      filters:
        person:
          min_area: 200000
          min_score: 0.6
          threshold: 0.7

    detect:
      enabled: true # <---- disable detection until you have a working camera feed

    live:
      stream_name: Garten_Cam_ext

  Garten_Cam2: # <------ Name the camera
    enabled: true
    motion:
      mask: 0.695,0.948,0.699,0.981,1,0.984,0.995,0.945
      threshold: 15
      contour_area: 10
      improve_contrast: 'true'
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten_Cam2 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten_Cam2_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    live:
      stream_name: Garten_Cam2_ext

  Carport_Cam: # <------ Name the camera
    enabled: true
    motion:
      mask:
        - 640,455,640,480,444,480,445,452
      threshold: 20
      contour_area: 10
      improve_contrast: 'true'
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Carport_Cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Carport_Cam_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - car
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    live:
      stream_name: Carport_Cam_ext

  WZ_Cam: # <------ Name the camera
    enabled: true
    motion:
      mask:
        - 640,322,438,319,441,352,640,352,640,352
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/WZ_Cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/WZ_Cam # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    live:
      stream_name: WZ_Cam_sub

camera_groups:
  Garten:
    order: 1
    icon: LuVideo
    cameras:
      - Garten_Cam
      - Garten_Cam2
version: 0.14
```

### Relevant log output

```shell
2024-08-13 19:21:46.804860942  [INFO] Preparing Frigate...
2024-08-13 19:21:46.824019895  [INFO] Starting Frigate...
2024-08-13 19:21:48.305026991  [2024-08-13 19:21:48] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
2024-08-13 19:21:48.305103731  [2024-08-13 19:21:48] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-08-13 19:21:48.344297307  [2024-08-13 19:21:48] frigate.util.config            INFO    : frigate config does not need migration...
2024-08-13 19:21:48.551731615  [2024-08-13 19:21:48] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-08-13 19:22:06.965552503  [2024-08-13 19:22:06] peewee_migrate.logs            INFO    : Starting migrations
2024-08-13 19:22:06.965710686  [2024-08-13 19:22:06] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-13 19:22:06.980036779  [2024-08-13 19:22:06] frigate.app                    INFO    : Recording process started: 426
2024-08-13 19:22:06.980041769  [2024-08-13 19:22:06] frigate.app                    INFO    : Recording process started: 432
2024-08-13 19:22:06.982253518  [2024-08-13 19:22:06] frigate.app                    INFO    : go2rtc process pid: 109
2024-08-13 19:22:07.005207843  [2024-08-13 19:22:07] detector.coral                 INFO    : Starting detection process: 455
2024-08-13 19:22:09.651646222  [2024-08-13 19:22:07] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-08-13 19:22:09.651650204  [2024-08-13 19:22:07] frigate.app                    INFO    : Output process started: 457
2024-08-13 19:22:09.651900023  [2024-08-13 19:22:07] frigate.app                    INFO    : Camera processor started for Garten_Cam: 481
2024-08-13 19:22:09.651972458  [2024-08-13 19:22:07] frigate.app                    INFO    : Camera processor started for Garten_Cam2: 482
2024-08-13 19:22:09.652043719  [2024-08-13 19:22:07] frigate.app                    INFO    : Camera processor started for Carport_Cam: 485
2024-08-13 19:22:09.652112181  [2024-08-13 19:22:07] frigate.app                    INFO    : Camera processor started for WZ_Cam: 491
2024-08-13 19:22:09.652182935  [2024-08-13 19:22:07] frigate.app                    INFO    : Capture process started for Garten_Cam: 493
2024-08-13 19:22:09.652251382  [2024-08-13 19:22:07] frigate.app                    INFO    : Capture process started for Garten_Cam2: 498
2024-08-13 19:22:09.652325176  [2024-08-13 19:22:07] frigate.app                    INFO    : Capture process started for Carport_Cam: 503
2024-08-13 19:22:09.652398786  [2024-08-13 19:22:07] frigate.app                    INFO    : Capture process started for WZ_Cam: 518
2024-08-13 19:22:09.660776483  [2024-08-13 19:22:09] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Frigate stats

```json
{
    "cameras": {
        "Carport_Cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 503,
            "detection_enabled": true,
            "detection_fps": 0.1,
            "ffmpeg_pid": 531,
            "pid": 485,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "Garten_Cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 493,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 524,
            "pid": 481,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "Garten_Cam2": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 498,
            "detection_enabled": true,
            "detection_fps": 4.8,
            "ffmpeg_pid": 510,
            "pid": 482,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "WZ_Cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 518,
            "detection_enabled": true,
            "detection_fps": 1.5,
            "ffmpeg_pid": 541,
            "pid": 491,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "46": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "87": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "109": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "14.7",
            "cpu_average": "13",
            "mem": "0.4"
        },
        "122": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "123": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "3.3",
            "cpu_average": "5",
            "mem": "6.4"
        },
        "129": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "162": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "163": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "164": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "165": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "166": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "317": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "343": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "426": {
            "cmdline": "frigate.recording_manager",
            "cpu": "3.0",
            "cpu_average": "3",
            "mem": "1.0"
        },
        "432": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "454": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "455": {
            "cmdline": "frigate.detector.coral",
            "cpu": "3.8",
            "cpu_average": "11",
            "mem": "1.0"
        },
        "457": {
            "cmdline": "frigate.output       ",
            "cpu": "3.1",
            "cpu_average": "4",
            "mem": "1.0"
        },
        "481": {
            "cmdline": "frigate.process:Garten_Cam",
            "cpu": "1.8",
            "cpu_average": "6",
            "mem": "1.3"
        },
        "482": {
            "cmdline": "frigate.process:Garten_Cam2",
            "cpu": "4.2",
            "cpu_average": "4",
            "mem": "1.1"
        },
        "485": {
            "cmdline": "frigate.process:Carport_Cam",
            "cpu": "2.7",
            "cpu_average": "2",
            "mem": "1.0"
        },
        "491": {
            "cmdline": "frigate.process:WZ_Cam",
            "cpu": "2.3",
            "cpu_average": "4",
            "mem": "1.2"
        },
        "493": {
            "cmdline": "frigate.capture:Garten_Cam",
            "cpu": "5.9",
            "cpu_average": "5",
            "mem": "1.0"
        },
        "498": {
            "cmdline": "frigate.capture:Garten_Cam2",
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "503": {
            "cmdline": "frigate.capture:Carport_Cam",
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "510": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garten_Cam2_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.9",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "518": {
            "cmdline": "frigate.capture:WZ_Cam",
            "cpu": "5.7",
            "cpu_average": "5",
            "mem": "1.0"
        },
        "524": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garten_Cam -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "11.0",
            "cpu_average": "10",
            "mem": "0.6"
        },
        "531": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Carport_Cam_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.9",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "532": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garten_Cam2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garten_Cam2@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "539": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.205/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ea462999ff41d7cb0fcd44baded67b51",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.2"
        },
        "541": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/WZ_Cam -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "11.4",
            "cpu_average": "11",
            "mem": "0.6"
        },
        "544": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Carport_Cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Carport_Cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "547": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/WZ_Cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/WZ_Cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "548": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garten_Cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garten_Cam@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "562": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "567": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "572": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "577": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "582": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "3709": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "11079": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "11108": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "23.9",
            "mem": "18.8"
        }
    },
    "detection_fps": 6.4,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 10.18,
            "pid": 455
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "5.01%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 109
        },
        "logger": {
            "pid": 343
        },
        "recording": {
            "pid": 426
        },
        "review_segment": {
            "pid": 432
        }
    },
    "service": {
        "last_updated": 1723571782,
        "latest_version": "0.14.0",
        "storage": {
            "/dev/shm": {
                "free": 306,
                "mount_type": "tmpfs",
                "total": 320,
                "used": 14
            },
            "/media/frigate/clips": {
                "free": 527799.9,
                "mount_type": "ext4",
                "total": 1920285,
                "used": 1294868
            },
            "/media/frigate/recordings": {
                "free": 527799.9,
                "mount_type": "ext4",
                "total": 1920285,
                "used": 1294868
            },
            "/tmp/cache": {
                "free": 1792.1,
                "mount_type": "tmpfs",
                "total": 1907.4,
                "used": 115.3
            }
        },
        "temperatures": {},
        "uptime": 2055,
        "version": "0.14.0-da913d8"
    }
}
```

### Operating system

HassOS

### Install method

Docker Compose

### Object Detector

Coral
