### DISCUSSION TITLE
[Bug]: v0.14 config validation errors on integer camera name

### DISCUSSION THREAD

**Discussion by mchangrh** [blakeblackshear/frigate#13032] [Report a Bug]
### Describe the problem you are having

Camera names with integers report a strange error with `cameras.name.[key]` since it's hardcoded to only accept strings instead of integers

### Steps to reproduce

Drop the following config file into an empty install

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  name:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp
          roles:
            - detect
  1234:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp
          roles:
            - detect
version: 0.14
```

### Relevant log output

```shell
frigate  | 2024-08-13 16:09:06.418949961  *************************************************************
frigate  | 2024-08-13 16:09:06.418955461  ***    Your config file is not valid!                     ***
frigate  | 2024-08-13 16:09:06.418958062  ***    Please check the docs at                           ***
frigate  | 2024-08-13 16:09:06.418959862  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2024-08-13 16:09:06.418985264  *************************************************************
frigate  | 2024-08-13 16:09:06.418987165  *************************************************************
frigate  | 2024-08-13 16:09:06.418989365  ***    Config Validation Errors                           ***
frigate  | 2024-08-13 16:09:06.418990965  *************************************************************
frigate  | 2024-08-13 16:09:06.419048971  cameras.1234.[key]: Input should be a valid string
frigate  | 2024-08-13 16:09:06.419051571  *************************************************************
frigate  | 2024-08-13 16:09:06.419053071  ***    End Config Validation Errors                       ***
frigate  | 2024-08-13 16:09:06.419054571  *************************************************************
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

single quoting the camera name does mitigate the problem, but integer camera names should still be valid
