### DISCUSSION TITLE
[Config Support]: it seems cameras record all the time

### DISCUSSION THREAD

**Discussion by leonbrag** [blakeblackshear/frigate#13049] [Config Support] [answered]
### Describe the problem you are having

Objective : not record all the time. Record only on motion. 

 
However when I go to camera history, when I use scrubbing on the time vertical timeline I can scrub through entire timeline of recording. There are no yellow (motion) or red (alert) markers. Yet is seems entire video is preserved 

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/380bb783-5720-4e07-a3ac-df148fefcbcd">

I verified in debug view - there is no motion in live feed

Why is all video shows on the timeline while scrubbing ? It should not be saved. 

When Motion only toggle is on, then timeline correctly only shows recorded segments. 

<img width="380" alt="image" src="https://github.com/user-attachments/assets/90b8e44c-21ff-47d3-ab09-5b1173ae8df4">

### Version

.14

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

Cameras:
  Basement: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.10.14/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:xxx@192.168.10.14/Streaming/Channels/101
          roles:
            - record
    motion:
      mask:


        - 0.042,0.061,0.639,0.061,0.641,0.122,0.04,0.119
```

### Relevant log output

```shell
Na
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino
