### DISCUSSION TITLE
[Support]:failing to start after upgrade.

### DISCUSSION THREAD

**Discussion by risk1994** [blakeblackshear/frigate#13045] [General Support]
### Describe the problem you are having

Trying to upgrade to latest version from 0.10.1-83481AF

after downloading ghcr.io/blakeblackshear/frigate   stable  
 sudo docker compose up -d 
it goes into an endless restarting loop.  

The log keeps saying this....

frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-08-13 21:13:18.643717650  [INFO] Preparing Frigate...
frigate  | 2024-08-13 21:13:18.648142630  [INFO] Starting NGINX...
frigate  | 2024-08-13 21:13:18.651173690  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-13 21:13:18.654780177  [ERROR] Trying to migrate the db path from '/media/frigate/frigate.db' to the '/config' dir, but '/config' is not a mountpoint, please mount the '/config' dir
frigate  | 2024-08-13 21:13:18.662750875  [INFO] Service Frigate exited with code 1 (by signal 0)

I created a new 5g mount point /config (kept permissions same as existing) same error.
I moved the mount point to /home/bobbo/config - same error

I should note "/media/frigate/frigate.db" is actually /home/bobbo/media/frigate.db.  I'm wondering if thats where some of the issue is coming from, but whether I create /home/bobbo/config or /config I get the same error every time.

Been banging my head against the wall on this one for awhile.  Any help would be appreciated.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yml:/config/config.yml
#     - ./media/:/media/frigate
      - /home/bobbo/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
#    environment:
#      FRIGATE_RTSP_PASSWORD: password
```

### Relevant log output

```shell
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-08-13 21:13:10.345960202  [INFO] Starting NGINX...
frigate  | 2024-08-13 21:13:10.348489767  [INFO] Preparing Frigate...
frigate  | 2024-08-13 21:13:10.352391731  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-13 21:13:10.360669184  [ERROR] Trying to migrate the db path from '/media/frigate/frigate.db' to the '/config' dir, but '/config' is not a mountpoint, please mount the '/config' dir
frigate  | 2024-08-13 21:13:10.367895857  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | 2024-08-13 21:13:10.441779434  2024/08/13 21:13:10 [error] 164#164: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.50.50.101, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "10.50.50.120:5000"
frigate  | 2024-08-13 21:13:10.441809402  2024/08/13 21:13:10 [error] 164#164: *1 auth request unexpected status: 502 while sending to client, client: 10.50.50.101, server: , request: "GET /api/stats HTTP/1.1", host: "10.50.50.120:5000"
frigate  | 2024-08-13 21:13:10.730435717  [INFO] Starting go2rtc...
frigate  | 2024-08-13 21:13:10.856680340  21:13:10.856 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-08-13 21:13:10.856700614  21:13:10.856 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-08-13 21:13:10.857154494  21:13:10.857 INF [rtsp] listen addr=:8554
frigate  | 2024-08-13 21:13:10.857226439  21:13:10.857 INF [api] listen addr=:1984
frigate  | 2024-08-13 21:13:10.857373327  21:13:10.857 INF [webrtc] listen addr=:8555/tcp
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-08-13 21:13:11.448090322  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

foscam
