### DISCUSSION TITLE
High CPU usage with Coral

### DISCUSSION THREAD

**Discussion by UKHarj** [blakeblackshear/frigate#13065] [Detector Support] [answered]
### Describe the problem you are having

Hi 

I have started using a Coral TPU and was expecting my CPU usage to reduce, however it hasn't had any impact. The Coral is being used to detection but I guess the decoding is impacting the CPU. Can someone check my config in case I have made an error somewhere?

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.192
  user: ****
  password: ****

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5
  stationary:
    interval: 50
    threshold: 50

snapshots:
  enabled: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

cameras:
  Front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****192.168.1.200/Streaming/Channels/101
          roles:
            - record
            - detect

    objects:
      track:
        - person

  Drive:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/201
          roles:
            - record
            - detect

    objects:
      track:
        - person

  Side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****192.168.1.200/Streaming/Channels/301
          roles:
            - record
            - detect

    objects:
      track:
        - person

  Garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****192.168.1.200/Streaming/Channels/401
          roles:
            - record
            - detect

    objects:
      track:
        - person
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Any other information that may be helpful

I'm running the add on a Dell Optiplex 3050 i3 3.4ghz 7100T with 8GB Ram. Despite the use of the Coral I have a warning message about High CPU usage. I can see in the system area that the Coral is being used for detection.
