### DISCUSSION TITLE
[Support]: openvino CPU vs GPU getting crashes with GPU and auto

### DISCUSSION THREAD

**Discussion by zaPure** [blakeblackshear/frigate#13066] [General Support] [answered]
### Describe the problem you are having

Hi 

Need some help understanding which openvino setting to use.

When I set it to GPU and Auto it crashes with a error "The go2rtc-healthcheck service exited with code 256"
When I set it to CPU it runs fine but the config is filled with the following errors.
```
2024-08-14 16:07:50.612674932  mbind failed: Operation not permitted
2024-08-14 16:07:50.612757090  mbind failed: Operation not permitted
2024-08-14 16:07:50.612845846  mbind failed: Operation not permitted
2024-08-14 16:07:50.618078931  mbind failed: Operation not permitted
```

I'm running frigate on unraid using a docker from the app store.
on a i7-7700 CPU with a 1050ti and I have set the shm to 1024, as I read somewhere it may be insufficient RAM.

config file - been using Frigate for at least 2 to 3 years and this config file has been modified over time as the versions have changed.

Any help would be appreciated.

### Version

0.14

### Frigate config file

```yaml
qtt:
  host: 192.168.12.20
  port: 1883
  user: ######
  password: ######

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


ffmpeg:
  hwaccel_args: preset-nvidia-h264
  
cameras:
#=============================================================
  Courtyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://viewer:######@192.168.12.50:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://viewer:######@192.168.12.50:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 1300
          mask:
            - 392,165,399,54,433,54,439,166
            - 595,141,674,58,458,48,449,107
    motion:
      mask:
        - 470,50,683,50,683,30,470,30
        - 704,0,704,98,434,97,186,92,64,0
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
#=============================================================
  Driveway:
    ffmpeg:
      inputs:
        - path: 
            rtsp://viewer:######@192.168.12.51:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://viewer:######@192.168.12.51:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 800
          mask:
    motion:
      mask:
        - 0,102,216,37,389,45,526,69,621,92,677,111,704,115,704,0,0,0
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
#=============================================================
  Frontdoor:
    ffmpeg:
      inputs:
        - path: 
            rtsp://viewer:######@192.168.12.48:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://viewer:######@192.168.12.48:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 154,100,178,0,220,0,234,107
    motion:
      mask:
        - 0,32,413,35,470,45,548,52,611,73,704,111,704,0,0,0
        - 47,576,234,576,160,223,41,240
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
#=============================================================
  Frontgate:
    ffmpeg:
      inputs:
        - path: 
            rtsp://viewer:######@192.168.12.49:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://viewer:######@192.168.12.49:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
    motion:
      mask:
        - 460,55,704,55,704,22,460,22
        - 627,576,630,368,377,352,280,576
        - 0,65,312,26,310,0,0,0
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
#=============================================================
  Shed:
    ffmpeg:
      inputs:
        - path: 
            rtsp://viewer:######@192.168.12.47:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://viewer:######@192.168.12.47:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
        - bird
    motion:
      mask:
        - 704,143,560,97,400,65,400,0,704,0
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
#=============================================================
version: 0.14
```

### Relevant log output

```shell
2024-08-14 16:07:50.612674932  mbind failed: Operation not permitted
2024-08-14 16:07:50.612757090  mbind failed: Operation not permitted
2024-08-14 16:07:50.612845846  mbind failed: Operation not permitted
2024-08-14 16:07:50.618078931  mbind failed: Operation not permitted
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Dahua
