### DISCUSSION TITLE
[Support]: Frigate videos record higher resolution than desired

### DISCUSSION THREAD

**Discussion by jwill2385** [blakeblackshear/frigate#13078] [General Support] [answered]
### Describe the problem you are having

Hello I am using a jetson orin nano running ubuntu 22.04, Jetpack 6.0. I am using a wyze camv3 for my camera. I would like to record and save frigate videos as 640 by 480p resolution. However for some reason they keep saving as 1920 by 1080p.

I set the width and height to be 640 by 480 in detect. Is there a way to set the width and height for the general recording as well? I tried to switch the RTSP stream endpoint from /live to /substream however this did not work either. 

### Version

frigate stable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  camera1: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      # hwaccel_args: preset-nvidia-h264
        # - -c:v
      inputs:
        - path: rtsp://admin:admin@10.0.0.212/live #TODO update to camera path
          roles:
            - detect
            - record
      # output_args:
      #   record: -f segment -segment_time 10 -segment_format mp4 -crf 28 -reset_timestamps 1 -strftime 1
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        # mode: all
      
  cam2: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://admin:admin@10.0.0.238/live #TODO update to camera path
          roles:
            - detect
            - record
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        mode: all
```

### Relevant log output

```shell
frigate  | 2024-08-14 20:16:28.841085361  [INFO] Preparing Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-08-14 20:16:28.847244934  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-08-14 20:16:28.965995239  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-14 20:16:29.000093954  [INFO] Starting Frigate...
frigate  | 2024-08-14 20:16:29.441992930  [INFO] Starting go2rtc...
frigate  | 2024-08-14 20:16:29.561192941  20:16:29.560 INF go2rtc version 1.8.4 linux/arm64
frigate  | 2024-08-14 20:16:29.561856189  20:16:29.561 INF [rtsp] listen addr=:8554
frigate  | 2024-08-14 20:16:29.561992769  20:16:29.561 INF [api] listen addr=:1984
frigate  | 2024-08-14 20:16:29.562198534  20:16:29.562 INF [webrtc] listen addr=:8555
frigate  | 2024-08-14 20:16:31.339875001  [2024-08-14 20:16:31] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-08-14 20:16:31.406570379  [2024-08-14 20:16:31] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-08-14 20:16:31.415835340  [2024-08-14 20:16:31] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-08-14 20:16:31.425523319  [2024-08-14 20:16:31] frigate.app                    INFO    : Recording process started: 383
frigate  | 2024-08-14 20:16:31.430582290  [2024-08-14 20:16:31] frigate.app                    INFO    : go2rtc process pid: 108
frigate  | 2024-08-14 20:16:31.470665086  [2024-08-14 20:16:31] detector.cpu                   INFO    : Starting detection process: 392
frigate  | 2024-08-14 20:16:31.477712937  [2024-08-14 20:16:31] frigate.app                    INFO    : Output process started: 394
frigate  | 2024-08-14 20:16:31.477731082  [2024-08-14 20:16:31] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-08-14 20:16:31.499876259  [2024-08-14 20:16:31] frigate.app                    INFO    : Camera processor started for camera1: 399
frigate  | 2024-08-14 20:16:31.499886339  [2024-08-14 20:16:31] frigate.app                    INFO    : Camera processor not started for disabled camera cam2
frigate  | 2024-08-14 20:16:31.511741059  [2024-08-14 20:16:31] frigate.app                    INFO    : Capture process started for camera1: 400
frigate  | 2024-08-14 20:16:31.511751203  [2024-08-14 20:16:31] frigate.app                    INFO    : Capture process not started for disabled camera cam2
frigate  | 2024-08-14 20:16:38.837840360  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-08-14 20:16:56.209724417  172.18.0.1 - - [14/Aug/2024:20:16:56 -0400] "GET / HTTP/1.1" 200 6636 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:16:56.344947186  172.18.0.1 - - [14/Aug/2024:20:16:56 -0400] "GET /api/config HTTP/1.1" 200 10648 "http://localhost:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:16:56.633114116  172.18.0.1 - - [14/Aug/2024:20:16:56 -0400] "GET /api/camera1/latest.jpg?h=100 HTTP/1.1" 200 2910 "http://localhost:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:16:56.719216429  172.18.0.1 - - [14/Aug/2024:20:16:56 -0400] "GET /api/camera1/latest.jpg?h=455 HTTP/1.1" 200 24703 "http://localhost:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:16:59.759403747  172.18.0.1 - - [14/Aug/2024:20:16:59 -0400] "GET /api/labels?camera=camera1 HTTP/1.1" 200 3 "http://localhost:5000/cameras/camera1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:16:59.759413155  172.18.0.1 - - [14/Aug/2024:20:16:59 -0400] "GET /api/config HTTP/1.1" 200 10648 "http://localhost:5000/cameras/camera1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:05.049356617  172.18.0.1 - - [14/Aug/2024:20:17:05 -0400] "GET /live/jsmpeg/camera1 HTTP/1.1" 101 259736 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:05.094889850  172.18.0.1 - - [14/Aug/2024:20:17:05 -0400] "GET /api/config HTTP/1.1" 200 10648 "http://localhost:5000/birdseye" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:14.632045250  172.18.0.1 - - [14/Aug/2024:20:17:14 -0400] "GET /live/jsmpeg/birdseye HTTP/1.1" 101 20532 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:14.819118975  172.18.0.1 - - [14/Aug/2024:20:17:14 -0400] "GET /api/events?in_progress=1&include_thumbnails=0 HTTP/1.1" 200 3 "http://localhost:5000/events" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:14.843688756  172.18.0.1 - - [14/Aug/2024:20:17:14 -0400] "GET /api/labels HTTP/1.1" 200 3 "http://localhost:5000/events" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:14.851502386  172.18.0.1 - - [14/Aug/2024:20:17:14 -0400] "GET /api/sub_labels?split_joined=1 HTTP/1.1" 200 3 "http://localhost:5000/events" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:14.857074937  172.18.0.1 - - [14/Aug/2024:20:17:14 -0400] "GET /api/events?cameras=all&labels=all&zones=all&sub_labels=all&time_range=00:00,24:00&timezone=America%2FNew_York&favorites=0&is_submitted=-1&in_progress=0&include_thumbnails=0&limit=25 HTTP/1.1" 200 3 "http://localhost:5000/events" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:14.857084985  172.18.0.1 - - [14/Aug/2024:20:17:14 -0400] "GET /api/config HTTP/1.1" 200 10648 "http://localhost:5000/events" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:15.667521650  172.18.0.1 - - [14/Aug/2024:20:17:15 -0400] "GET /exports/ HTTP/1.1" 200 14 "http://localhost:5000/exports" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:17.362276583  172.18.0.1 - - [14/Aug/2024:20:17:17 -0400] "GET /api/recordings/storage HTTP/1.1" 200 114 "http://localhost:5000/storage" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:23.516934095  172.18.0.1 - - [14/Aug/2024:20:17:23 -0400] "GET /api/go2rtc/api HTTP/1.1" 200 139 "http://localhost:5000/system" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:23.580641050  172.18.0.1 - - [14/Aug/2024:20:17:23 -0400] "GET /api/config HTTP/1.1" 200 10648 "http://localhost:5000/system" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:39.735749787  172.18.0.1 - - [14/Aug/2024:20:17:39 -0400] "GET /api/config HTTP/1.1" 200 10648 "http://localhost:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:39.768578456  172.18.0.1 - - [14/Aug/2024:20:17:39 -0400] "GET /api/camera1/latest.jpg?h=100 HTTP/1.1" 200 2917 "http://localhost:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
frigate  | 2024-08-14 20:17:39.812801898  172.18.0.1 - - [14/Aug/2024:20:17:39 -0400] "GET /api/camera1/latest.jpg?h=455 HTTP/1.1" 200 24402 "http://localhost:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
```

### FFprobe output from your camera

```shell
Unsure
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Wyze camera v3

### Any other information that may be helpful

Running frigate-stable
