### DISCUSSION TITLE
Mobile phone notifications

### DISCUSSION THREAD

**Discussion by UKHarj** [blakeblackshear/frigate#13073] [General Support] [answered]
### Describe the problem you are having

Hi I noticed that the mobile notification blue print is not working. Would someone be able to provide some automation code in order to get notifications to my Pixel 8 phone whenever I'm away from home. I'd like to see the snap shot and have the option to stream the event recording. 

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.192
  user: ****
  password: ****

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

environment_vars:
  LIBVA_DRIVER_NAME: i965

detect:
  enabled: true
  width: 640
  height: 480
  fps: 5
  stationary:
    interval: 50
    threshold: 50

snapshots:
  enabled: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

cameras:
  Front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****192.168.1.200/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/101
          roles:
            - record

    objects:
      track:
        - person

  Drive:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/202
          roles:
            - detect
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/201
          roles:
            - record

    objects:
      track:
        - person

  Side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/302
          roles:
            - detect
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/301
          roles:
            - record

    objects:
      track:
        - person

  Garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/402
          roles:
            - detect
        - path: rtsp://****:****@192.168.1.200/Streaming/Channels/401
          roles:
            - record
    

    objects:
      track:
        - person
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

Hikvision
