### DISCUSSION TITLE
[Support]: There are no events on the alert page.

### DISCUSSION THREAD

**Discussion by williamcanon1** [blakeblackshear/frigate#13079] [General Support]
### Describe the problem you are having

After the upgrade, I am not receiving any alerts about people and vehicles on the alert page. Do I need to change my configuration? This is my current configuration. The preview is normal, and people are being detected correctly, but they are not appearing on the alert page.

### Version

last

### Frigate config file

```yaml
detectors:
  coral:
    type: cpu
environment_vars:
  LIBVA_DRIVER_NAME: iHD
ffmpeg:
  hwaccel_args: preset-rpi-64-h265
mqtt:
  host: 
  user: 
  password: 
go2rtc:
  streams:
    back:
    camera1:
      - rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/101
    camera2:
      - rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/201
    camera3:
      - rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/301
    camera4:
      - rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/401
    camera5:
      - rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/501
    camera6:
      - rtsp://admin:XXX@192.168.1.100:554/mpeg4cif
    camera7:
      - rtsp://admin:XXX@192.168.1.101:554/mpeg4cif
    camera8:
      - rtsp://admin:XXX@192.168.1.102:554/mpeg4cif
    camera9:
      - rtsp://admin:XXX@192.168.1.103:554/mpeg4cif
    camera10:
      - rtsp://admin:XXX192.168.11.170:554/stream1
    camera11:
      - rtsp://admin:XXX@192.168.101.62:554/h264/ch1/main/av_stream
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/101
          roles:
            - detect
            - record 
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/201
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/301
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/401
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera5:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.101.29:554/ISAPI/Streaming/Channels/501
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera6:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.1.100:554/mpeg4
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera7:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.1.101:554/mpeg4
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 10
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera8:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.1.102:554/mpeg4
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera9:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.1.103:554/mpeg4
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera10:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.11.170:554/stream1
          roles:
            - detect
            - record 
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
  camera11:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.101.62:554/ISAPI/Streaming/Channels/101
          roles:
            - detect
            - record 
            - audio
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10
        objects:
          person: 15
objects:
  track:
    - person
    - car
    - motorcycle
  filters:
    person:
      min_score: 0.5
      threshold: 0.7
```

### Relevant log output

```shell
1
```

### FFprobe output from your camera

```shell
1
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wireless

### Camera make and model

hikvision and other
