### DISCUSSION TITLE
[HW Accel Support]: Jetson Orin Nano Not Working

### DISCUSSION THREAD

**Discussion by NicholasJohnson2020** [blakeblackshear/frigate#13081] [Hardware Acceleration Support]
### Describe the problem you are having

Hello - I am using Nvidia Jetson Orin with Ubuntu 22.04,  jetpack 6.0, and cuda 12.2. 
Currently Frigate works when running just cpu. However when I try any hardware acceleration flag it does not connect and gives following error as seen in logs. Has anyone got frigate with GPU to work on Jetson Orin Nano device? What else is needed?

### Version

frigatestable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  camera1: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
        # - -c:v
        # - h264_cuvid
      inputs:
        - path: rtsp://exp2:horse@10.0.0.212/live #TODO update to camera path
          roles:
            - detect
            - record
      # output_args:
      #   record: -f segment -segment_time 10 -segment_format mp4 -crf 28 -reset_timestamps 1 -strftime 1
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        # mode: all
      
  ip_cam: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://admin:admin@10.0.0.238/live #TODO update to camera path
          roles:
            - detect
            - record
    detect:
      width: 640 #update to camera resolution
      height: 480 # update to camera resolution
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        mode: all
```

### docker-compose file or Docker CLI command

```yaml
version: "2.4"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable #Jetson nano image jetpack 4.6
    # image: ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp5 #Jetson nano image jetpack 4.6
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/visionsense/Docker/frigate/config:/config
      - /home/visionsense/Docker/frigate/media:/media/frigate #TODO switch this to external HD for media storage
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-08-14 19:52:43.197164834  [INFO] Starting NGINX...
frigate  | 2024-08-14 19:52:43.197155042  [INFO] Preparing Frigate...
frigate  | 2024-08-14 19:52:43.482458961  [INFO] Starting Frigate...
frigate  | 2024-08-14 19:52:43.485846809  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-14 19:52:45.412364756  [INFO] Starting go2rtc...
frigate  | 2024-08-14 19:52:45.636730455  19:52:45.636 INF go2rtc version 1.8.4 linux/arm64
frigate  | 2024-08-14 19:52:45.638078579  19:52:45.637 INF [rtsp] listen addr=:8554
frigate  | 2024-08-14 19:52:45.638638815  19:52:45.638 INF [webrtc] listen addr=:8555
frigate  | 2024-08-14 19:52:45.638989767  19:52:45.638 INF [api] listen addr=:1984
frigate  | 2024-08-14 19:52:47.977971971  2024/08/14 19:52:47 [error] 158#158: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2024-08-14 19:52:50.802121118  [2024-08-14 19:52:50] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2024-08-14 19:52:50.911821470  [2024-08-14 19:52:50] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-08-14 19:52:50.928165306  [2024-08-14 19:52:50] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-08-14 19:52:50.929365844  [2024-08-14 19:52:50] frigate.app                    INFO    : Running database vacuum
frigate  | 2024-08-14 19:52:51.003036821  [2024-08-14 19:52:51] frigate.app                    INFO    : Recording process started: 395
frigate  | 2024-08-14 19:52:51.014887313  [2024-08-14 19:52:51] frigate.app                    INFO    : go2rtc process pid: 98
frigate  | 2024-08-14 19:52:51.059642955  [2024-08-14 19:52:51] detector.cpu                   INFO    : Starting detection process: 404
frigate  | 2024-08-14 19:52:51.070061033  [2024-08-14 19:52:51] frigate.app                    INFO    : Output process started: 406
frigate  | 2024-08-14 19:52:51.071033565  [2024-08-14 19:52:51] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-08-14 19:52:51.091165674  [2024-08-14 19:52:51] frigate.app                    INFO    : Camera processor started for camera1: 411
frigate  | 2024-08-14 19:52:51.091175274  [2024-08-14 19:52:51] frigate.app                    INFO    : Camera processor not started for disabled camera ip_cam
frigate  | 2024-08-14 19:52:51.106997883  [2024-08-14 19:52:51] frigate.app                    INFO    : Capture process started for camera1: 412
frigate  | 2024-08-14 19:52:51.107007228  [2024-08-14 19:52:51] frigate.app                    INFO    : Capture process not started for disabled camera ip_cam
frigate  | 2024-08-14 19:52:53.032310391  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-08-14 19:52:53.892735930  [2024-08-14 19:52:53] frigate.video                  ERROR   : camera1: Unable to read frames from ffmpeg process.
frigate  | 2024-08-14 19:52:53.894808870  [2024-08-14 19:52:53] frigate.video                  ERROR   : camera1: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-08-14 19:53:11.171823376  [2024-08-14 19:53:11] watchdog.camera1               ERROR   : Ffmpeg process crashed unexpectedly for camera1.
frigate  | 2024-08-14 19:53:11.173333905  [2024-08-14 19:53:11] watchdog.camera1               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-08-14 19:53:11.173949374  [2024-08-14 19:53:11] ffmpeg.camera1.detect          ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate  | 2024-08-14 19:53:11.174074496  [2024-08-14 19:53:11] ffmpeg.camera1.detect          ERROR   : Device creation failed: -12.
frigate  | 2024-08-14 19:53:11.174198883  [2024-08-14 19:53:11] ffmpeg.camera1.detect          ERROR   : [h264 @ 0xaaaac70bf5c0] No device available for decoder: device type cuda needed for codec h264.
frigate  | 2024-08-14 19:53:11.174317350  [2024-08-14 19:53:11] ffmpeg.camera1.detect          ERROR   : Device setup failed for decoder on input stream #0:0 : Cannot allocate memory
frigate  | 2024-08-14 19:53:13.831257357  [2024-08-14 19:53:13] frigate.video                  ERROR   : camera1: Unable to read frames from ffmpeg process.
frigate  | 2024-08-14 19:53:13.831497970  [2024-08-14 19:53:13] frigate.video                  ERROR   : camera1: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-08-14 19:53:21.207433557  [2024-08-14 19:53:21] watchdog.camera1               ERROR   : Ffmpeg process crashed unexpectedly for camera1.
frigate  | 2024-08-14 19:53:21.207724251  [2024-08-14 19:53:21] watchdog.camera1               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-08-14 19:53:21.207933536  [2024-08-14 19:53:21] ffmpeg.camera1.detect          ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate  | 2024-08-14 19:53:21.208073091  [2024-08-14 19:53:21] ffmpeg.camera1.detect          ERROR   : Device creation failed: -12.
frigate  | 2024-08-14 19:53:21.208160452  [2024-08-14 19:53:21] ffmpeg.camera1.detect          ERROR   : [h264 @ 0xaaaae7b8a4c0] No device available for decoder: device type cuda needed for codec h264.
frigate  | 2024-08-14 19:53:21.208448171  [2024-08-14 19:53:21] ffmpeg.camera1.detect          ERROR   : Device setup failed for decoder on input stream #0:0 : Cannot allocate memory
frigate  | 2024-08-14 19:53:23.825623159  [2024-08-14 19:53:23] frigate.video                  ERROR   : camera1: Unable to read frames from ffmpeg process.
frigate  | 2024-08-14 19:53:23.825974687  [2024-08-14 19:53:23] frigate.video                  ERROR   : camera1: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-08-14 19:53:31.246168135  [2024-08-14 19:53:31] watchdog.camera1               ERROR   : Ffmpeg process crashed unexpectedly for camera1.
frigate  | 2024-08-14 19:53:31.247092762  [2024-08-14 19:53:31] watchdog.camera1               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-08-14 19:53:31.247099451  [2024-08-14 19:53:31] ffmpeg.camera1.detect          ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate  | 2024-08-14 19:53:31.247101275  [2024-08-14 19:53:31] ffmpeg.camera1.detect          ERROR   : Device creation failed: -12.
frigate  | 2024-08-14 19:53:31.247114715  [2024-08-14 19:53:31] ffmpeg.camera1.detect          ERROR   : [h264 @ 0xaaaafb534190] No device available for decoder: device type cuda needed for codec h264.
frigate  | 2024-08-14 19:53:31.247149884  [2024-08-14 19:53:31] ffmpeg.camera1.detect          ERROR   : Device setup failed for decoder on input stream #0:0 : Cannot allocate memory
frigate  | 2024-08-14 19:53:33.825298966  [2024-08-14 19:53:33] frigate.video                  ERROR   : camera1: Unable to read frames from ffmpeg process.
frigate  | 2024-08-14 19:53:33.826950842  [2024-08-14 19:53:33] frigate.video                  ERROR   : camera1: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
Unsure how to run this
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

wyze camv3

### Any other information that may be helpful

Jetson Orin Nano has aarch64 architecture and is running jetpack 6.0 with ubuntu 22.04

**Comment by NickM-27** [comment]
what is your docker compose

**Reply by NicholasJohnson2020** [reply]
Hi Nick, I included my docker compose in my original post. Pasting it below for ease of reference:

```
version: "2.4"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable #Jetson nano image jetpack 4.6
    # image: ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp5 #Jetson nano image jetpack 4.6
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/visionsense/Docker/frigate/config:/config
      - /home/visionsense/Docker/frigate/media:/media/frigate #TODO switch this to external HD for media storage
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```
