### DISCUSSION TITLE
[Config Support]: Objects outside the Zone are getting detected and reported

### DISCUSSION THREAD

**Discussion by Jebarson** [blakeblackshear/frigate#13080] [Config Support] [answered]
### Describe the problem you are having

I have a camera configured so that only alerts are raised when there is a detection inside the zone. I believe that my setting is perhaps wrong.

### Version

 0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxxx
  port: 1883
  user: mqtt
  password: xxx

detect:
  enabled: true
  fps: 5
  max_disappeared: 75 # 15 seconds considering 5 fps

record:
  enabled: true
  retain:
    days: 8

cameras:
  Doorbell:
    enabled: true
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://xxx/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - bear
        - bicycle
        - bird
        - bus
        - car
        - cat
        - cow
        - dog
        - hat
        - horse
        - person
        - sheep
        - umbrella
    motion:
      mask: 0.345,0.015,0.644,0.012,0.647,0.05,0.344,0.052
  Camera_1:
    enabled: true
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://xxx/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - bear
        - bicycle
        - bird
        - bus
        - car
        - cat
        - cow
        - dog
        - hat
        - horse
        - person
        - sheep
        - umbrella
    zones:
      Front:
        coordinates: 
          0,0.25,0.1,0.322,0.225,0.392,0.578,0.517,0.692,0.503,0.916,0.55,1,0.836,1,1,0,1,0,0
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0.351,0.026,0.638,0.025,0.638,0.058,0.352,0.058
  Camera_2:
    enabled: true
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://xxx/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - bear
        - bicycle
        - bird
        - bus
        - car
        - cat
        - cow
        - dog
        - hat
        - horse
        - person
        - sheep
        - umbrella
    motion:
      mask: 0.349,0.025,0.642,0.019,0.643,0.064,0.348,0.069
version: 0.14
```

### Relevant log output

```shell
Dont see any log that might be relevant
```

### Operating system

WSL2

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Any other information that may be helpful

Here is the snapshot of how the mask is created.

![image](https://github.com/user-attachments/assets/2934f4e2-4f2c-4ba5-b0c6-7cb64c703dcc)
