### DISCUSSION TITLE
[Bug]: I believe the temperature should belong to coral3 and not coral1. Coral1 is usb, and Coral3 is pci.

### DISCUSSION THREAD

**Discussion by riemers** [blakeblackshear/frigate#13085] [Report a Bug] [answered]
### Describe the problem you are having

It shows temperature on the usb and not on the pci one, it also shows NaN on the usb2.

![image](https://github.com/user-attachments/assets/6dc6650f-7d39-45d2-b706-47c2137d2409)

### Steps to reproduce

Install 2 usb corals, then add another pci one. Yeah overkill, i was just testing to see whats the best resonse times. Weird that usb1 does 23ms, the other 8ms. But clearly the pci one with almost 6ms is the clearest winner :)

### Version

0.14

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
  coral3:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
No ouput as its UI
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Keep up the good work ;) since this is just cosmestic, low prio i would say. Assuming its a bug in the first place.
