### DISCUSSION TITLE
Setup go2rtc.yaml with onvif camera

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#13084] [Ask A Question]
### What is your question:

Hi!

I have cameras with onvif support!
![P05](https://github.com/user-attachments/assets/fbdb9af1-e72f-426b-a7ad-17da5f614bfb)
Through the YCC365 Plus APP, it shows me that the model is `P05-7-C` (https://www.alibaba.com/product-detail/YCC365-Plus-1MP-2MP-CC-TV_62125262949.html).
The camera meets all my needs and it's cheap!

I currently have the following configuration in go2rtc.yaml:
```yaml
streams:
 Dining room-HD: rtsp://admin:123456@192.168.1.30:554/0/av0
 Dining room: rtsp://admin:123456@192.168.1.30:554/0/av1
 Di-HD: rtsp://admin:123456@192.168.1.31:554/0/av0
 Di: rtsp://admin:123456@192.168.1.31:554/0/av1
 Nata-HD: rtsp://admin:123456@192.168.1.32:554/0/av0
 Nata: rtsp://admin:123456@192.168.1.32:554/0/av1
 Bedroom-HD: rtsp://admin:123456@192.168.1.33:554/0/av0
 Bedroom: rtsp://admin:123456@192.168.1.33:554/0/av1
```

As far as I understand it is a ffmpeg connection.
If you wanted to burn ONVIF to me through the `Ispy program` displays:
`http://192.168.1.30/onvif/device_service`
but I have to choose one more from:
```yaml
FFMPEG(H264)
1920x1080
rtsp://admin:123456@192.168.1.30:554/0/av0
640x352
rtsp://admin:123456@192.168.1.30:554/0/av1
```

Does anyone know how I should modify the go2rtc.yaml file to have the ONVIF connection/protocol selected?

Thanks for any help.

**Comment by Trzinka** [comment]
**Apparently I found a solution!?**
# Is this correct:

go2rtc.yaml:
```yaml
streams: 
# FFMPEG(H264) 1920x1080
  Jedilnica-HD: rtsp://admin:123456@192.168.1.30:554/0/av0
  Di-HD: rtsp://admin:123456@192.168.1.31:554/0/av0
  Nata-HD: rtsp://admin:123456@192.168.1.32:554/0/av0
  Spalnica-HD: rtsp://admin:123456@192.168.1.33:554/0/av0
# ONVIF
  Jedilnica-ONVIF: rtsp://admin:123456@192.168.1.30/onvif/device_service
  Di-ONVIF: rtsp://admin:123456@192.168.1.31/onvif/device_service
  Nata-ONVIF: rtsp://admin:123456@192.168.1.32/onvif/device_service  
  Spalnica-ONVIF: rtsp://admin:123456@192.168.1.33/onvif/device_service
```
