### DISCUSSION TITLE
Review of config file for optimal usage

### DISCUSSION THREAD

**Discussion by UKHarj** [blakeblackshear/frigate#13099] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

0.14 is working great as someone new to Frigate I'd appreciate someone just taking a place to see if I can tweek my config in any way?

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.192
  user: mqtt-user
  password: ***

detectors:
  coral:
    type: edgetpu
    device: usb
  
ffmpeg:
  hwaccel_args: preset-vaapi

environment_vars:
  LIBVA_DRIVER_NAME: i965

detect:
  enabled: true
  width: 640
  height: 480
  fps: 5
  stationary:
    interval: 50
    threshold: 50

snapshots:
  enabled: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

cameras:
  Front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.1.200/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://***:***@192.168.1.200/Streaming/Channels/101
          roles:
            - record

    objects:
      track:
        - person

  Drive:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***:***192.168.1.200/Streaming/Channels/202
          roles:
            - detect
        - path: rtsp://***:***192.168.1.200/Streaming/Channels/201
          roles:
            - record

    objects:
      track:
        - person

  Side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***:***!@192.168.1.200/Streaming/Channels/302
          roles:
            - detect
        - path: rtsp://***:***@192.168.1.200/Streaming/Channels/301
          roles:
            - record

    objects:
      track:
        - person

  Garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.1.200/Streaming/Channels/402
          roles:
            - detect
        - path: rtsp://****:****!@192.168.1.200/Streaming/Channels/401
          roles:
            - record

    objects:
      track:
        - person

version: 0.14
camera_groups:
  Home:
    order: 1
    icon: LuHome
    cameras:
      - Drive
      - Front
      - Garden
      - Side
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wireless

### Camera make and model

Hikvision

### Any other information that may be helpful

I'm running the sub stream and main steam at H.265+. I'm running the addon on a Dell Optiplex i3, 7100T 2.4ghz processor with no specialist GPU
![image](https://github.com/user-attachments/assets/8558de15-1277-4641-8973-344d1da25dd9)
![image](https://github.com/user-attachments/assets/5f6b09d2-5e36-4e90-8432-30cbe05644e8)
