### DISCUSSION TITLE
[Support]: how to make sure frigate clears /tmp/cache from container?

### DISCUSSION THREAD

**Discussion by ristoavila** [blakeblackshear/frigate#13095] [General Support] [answered]
### Describe the problem you are having

Frigate stops recording when /tmp/cache is full and for some reason its fullfilled and never cleared. 

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.13
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: zxczxcv
  password: zxcvzxcv
  stats_interval: 300

go2rtc:
  api:
    listen: 0.0.0.0:1984
  rtsp:
    listen: 0.0.0.0:8554
  webrtc:
    candidates:
      - 192.168.0.1:8555
      - stun:8555
    listen: 0.0.0.0:8555
  streams:
    #talli_etu: rtsp://192.168.0.36:554/0/h264major
    #talli_etu_sub: rtsp://192.168.0.36:554/0/h264minor
    #640x480 5fps i-frame 5

    #only main video stream works not sub
    talli_etu_sub:
      ffmpeg:rtsp://admin:123456@192.168.0.39:554/user=admin&password=123456&channel=1&stream=1.sdp?#backchannel=0
    talli_etu:
      - ffmpeg:rtsp://admin:123456@192.168.0.39:554/user=admin&password=123456&channel=1&stream=0.sdp?
      - isapi://admin:123456@192.168.0.39:80/

    #test: rtsp://192.168.0.37:554/stream1
    #test_sub: rtsp://192.168.0.37:554/stream2

    #test_sub: ffmpeg:rtsp://admin:123456@192.168.0.39:554/user=admin&password=123456&channel=1&stream=1.sdp?
    #test_sub: ffmpeg:rtsp://admin:123456@192.168.0.39/cam/realmonitor?channel=1&subtype=1
    #test_sub: ffmpeg:rtsp://192.168.0.39:554/stream1?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E

    #704x576 5fps i-frame 5
    talli_taka: rtsp://192.168.0.30/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp
    talli_taka_sub: rtsp://192.168.0.30/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp
    #704x576 5fps i-frame 5
    talli_sivu: rtsp://192.168.0.33/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp
    talli_sivu_sub: rtsp://192.168.0.33/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp
    #704x576 5fps i-frame 5
    takaovi: rtsp://admin:admin@192.168.0.32:554/cam/realmonitor?channel=1&subtype=0
    takaovi_sub: rtsp://admin:admin@192.168.0.32:554/cam/realmonitor?channel=1&subtype=1
    #704x576 5 fps i-frame 5
    #hamrolte_old_etuovi: rtsp://192.168.0.34:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
    #hamrolte_old_etuovi_sub: rtsp://192.168.0.34:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream
    etuovi: rtsp://192.168.0.37:554/stream1
    etuovi_sub: rtsp://192.168.0.37:554/stream2

    #704x576 5fps i-frame 5
    katos: rtsp://admin:1234567a@192.168.0.35:554/cam/realmonitor?channel=1&subtype=0
    katos_sub: rtsp://admin:1234567a@192.168.0.35:554/cam/realmonitor?channel=1&subtype=1
    #704x576 5fps i-frame 5
    katostie: rtsp://192.168.0.31/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp
    katostie_sub: rtsp://192.168.0.31/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp
    #704x576 5fps i-frame 5

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  expire_interval: 3
  sync_recordings: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 704
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 576
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  annotation_offset: -800
#  stationary:
#    interval: 10
#    threshold: 50
#    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
#      default: 3000
      # Optional: Object specific values
#      objects:
#        person: 1000
#        car: 1000
#        dog: 1000
#        cat: 1000

model:
  width: 320 #default 320
  height: 320 #default 320

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 3
    # Optional: Per object retention days
    objects:
      person: 5

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat
  restream: false
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - car
    - bus
  #filters:
  #  cat:
  #    min_score: 0.4
  #    threshold: 0.5
  #  dog:
  #    min_score: 0.4
  #    threshold: 0.5
  #  person:
  #    min_score: 0.5
  #    threshold: 0.6
  #  car:
  #    min_score: 0.3
  #    threshold: 0.5

cameras:
#  test:
#    ffmpeg:
#      inputs:
#        - path: /media/frigate/10.17.mp4
#          input_args: -re -stream_loop -1 -fflags +genpts
#          roles:
#            - detect
#    detect:
#      width: 704
#      height: 576
#      fps: 5


#Anpviz kamera
#  anpviz:
#    ffmpeg:
#      hwaccel_args: preset-vaapi
#      inputs:
#        - path: rtsp://admin:123456@192.168.0.39/stream1/
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#        - path: rtsp://admin:123456@192.168.0.39/stream0/
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#    live:
#       stream_name: test

#  test:
#    ffmpeg:
#      hwaccel_args: preset-vaapi
#      inputs:
#        - path: rtsp://127.0.0.1:8554/anpviz_sub?video=copy
#          #input_args: preset-rtsp-restream
#          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 10000000 -use_wallclock_as_timestamps 1
#          roles:
#            - detect
#        - path: rtsp://127.0.0.1:8554/anpviz
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#    live:
#       stream_name: anpviz_sub

  talli_etu:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/talli_etu_sub?video=copy
          #input_args: preset-rtsp-restream
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt
            -rtsp_transport tcp -timeout 10000000 -use_wallclock_as_timestamps 1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/talli_etu
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: talli_etu_sub
    motion:
      mask:
        - 0,34,180,34,181,0,0,0
    zones:
      metsa:
        coordinates: 167,93,165,0,704,0,704,213
      parkki:
        coordinates: 0,0,0.205,0,0.213,0.381,0.268,0.447,0,0.559
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - car
      piha:
        coordinates: 0.006,1,1,1,1,0.566,0.425,0.328,0.219,0.378,0.28,0.451,0,0.576,0,1
        inertia: 3
        loitering_time: 0
      tie:
        coordinates: 0.605,0.268,0.297,0.207,0.239,0.231,0.432,0.319,1,0.556,1,0.403
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - piha
        - tie

    review:
      alerts:
        required_zones: piha
      detections: {}
  talli_taka:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/talli_taka_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/talli_taka
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 0.271,0.099,0.334,0.048,0.37,0.023,0.413,0,0,0,0,0.135,0,0.382
        - 1,1,1,0,0.915,0,0.901,0.172,0.839,1
    objects:
      track:
        - person
        - dog
        - cat
    live:
      stream_name: talli_taka_sub

    zones:
      Taka:
        coordinates: 0,0.998,0.835,1,0.909,0,0.427,0,0.273,0.1,0,0.388
        loitering_time: 0
    review:
      alerts:
        required_zones: Taka
  talli_sivu:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/talli_sivu_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/talli_sivu
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 22,52,261,52,262,28,25,28
        - 339,318,403,333,408,0,352,0
        - 599,23,704,75,704,0,502,0
    zones:
      piha:
        coordinates: 0,576,704,576,704,78,596,30,501,0,131,122,55,109,0,137
    objects:
      track:
        - person
        - dog
        - cat
    live:
      stream_name: talli_sivu_sub

    review:
      alerts:
        required_zones:
          - piha
  takaovi:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/takaovi_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/takaovi
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 303,59,526,85,457,475,576,576,704,576,704,0,0,0,0,81
    objects:
      track:
        - person
        - dog
        - cat
    live:
      stream_name: takaovi_sub

    zones:
      Terassi:
        coordinates: 0.002,0.145,0.425,0.11,0.738,0.156,0.637,0.817,0.807,0.999,0.002,0.998
        loitering_time: 0
  etuovi:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/etuovi_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/etuovi
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
        - 0,25,163,24,165,0,0,0
    live:
      stream_name: etuovi_sub

  katos:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/katos_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/katos
          input_args: preset-rtsp-restream
          roles:
            - record
    zones:
      parkki:
        coordinates: 1,1,1,0.083,0.94,0.13,0.507,0.119,0.523,1
        inertia: 3
        loitering_time: 0
      piha:
        coordinates: 0,0,298,0,704,0,704,0,704,38,661,72,356,67,365,576,0,576
    objects:
      filters:
        car:
          mask: 0.555,0.076,1,0.083,1,1,0.522,1,0.51,0.162
    motion:
      mask:
        - 451,50,678,51,679,21,450,22
    snapshots:
      required_zones:
        - piha
    live:
      stream_name: katos_sub

    review:
      alerts:
        required_zones: piha
      detections: {}
  katostie:
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/katostie_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/katostie
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 24,53,267,51,268,28,28,28
    zones:
      metsa:
        coordinates: 1,0,0.581,0,0.578,0.157,1,0.411
        inertia: 3
        loitering_time: 0
      piha:
        coordinates:
          1,0.616,0.568,0.335,0.584,0,0.153,0,0.148,0.158,0,0.243,0,0.477,0.143,0.487,0.296,0.987,1,1,1,0.615
        inertia: 3
        loitering_time: 0
      talli:
        coordinates: 0,0.235,0.143,0.152,0.146,0,0,0
        inertia: 3
        loitering_time: 0
      tie:
        coordinates: 1,0.398,1,0.611,0.57,0.317,0.579,0.156
        inertia: 3
        loitering_time: 0
      parkki:
        coordinates: 0,1,0.272,1,0.135,0.495,0,0.493
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - tie
        - piha
        - metsa
    live:
      stream_name: katostie_sub

    review:
      alerts:
        required_zones: piha
      detections: {}
version: 0.14
camera_groups:
  Tie:
    order: 1
    icon: LuCar
    cameras:
      - talli_etu
      - katostie
  Ovet:
    order: 2
    icon: LuDoorClosed
    cameras:
      - etuovi
      - takaovi
      - katos
      - talli_sivu
```

### Relevant log output

```shell
ffmpeg states out of disk space even though the recording media has 800gb left.
see https://github.com/blakeblackshear/frigate/discussions/13050#discussioncomment-10337083 for screenshot
```

### FFprobe output from your camera

```shell
all streams report out of disk space
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

mixed models, 0.13 worked fine
