### DISCUSSION TITLE
[Config Support]: go2rpc problem with RCL-520A cameras

### DISCUSSION THREAD

**Discussion by tzezar** [blakeblackshear/frigate#13129] [Config Support] [answered]
### Describe the problem you are having

I'm trying to configure frigate and go2rpc to get lower latency on the preview however I can't do it. It doesn't show me select with option selection. Also when I try to use second path stream for detection then docker container keeps restarting. I believe I followed guide in docs 1:1. I can see stream in go2rpc web ui. Would be glad for some tips or maybe answer if this is problem with Reolink camera - with Hikvision ones it worked. 

Also adding `hwaccel_args: preset-vaapi` disables camera preview in frigate too (but it reduce cpu usage)

### Version

docker

### Frigate config file

```
ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    back:
      - rtsp://admin:pass@192.168.0.121:554/Preview_01_main
  webrtc:
    candidates:
      - 192.168.0.1:8555
      - stun:8555


mqtt:
  enabled: False

birdseye:
  enabled: True
  mode: continuous

cameras:
  back:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    snapshots:
      enabled: False
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    detect:
      enabled: False
      width: 640
      height: 480

version: 0.14

```

### Relevant log output

```shell
error
2024-08-17 01:50:58
frigate.video
back: Unable to read frames from ffmpeg process.
error
2024-08-17 01:50:58
frigate.video
back: ffmpeg process is not running. exiting capture thread...
error
2024-08-17 01:51:08
frigate.util.services
Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nerror: failed to initialize display\n"
error
2024-08-17 01:51:15
watchdog.back
Ffmpeg process crashed unexpectedly for back.
error
2024-08-17 01:51:15
watchdog.back
The following ffmpeg logs include the last 100 lines prior to exit.
error
2024-08-17 01:51:15
ffmpeg.back.detect
[AVHWDeviceContext @ 0x5d65d43f8340] No VA display found for device /dev/dri/renderD128.
error
2024-08-17 01:51:15
ffmpeg.back.detect
Device creation failed: -22.
error
2024-08-17 01:51:15
ffmpeg.back.detect
[h264 @ 0x5d65d43f4880] No device available for decoder: device type vaapi needed for codec h264.
error
2024-08-17 01:51:15
ffmpeg.back.detect
Device setup failed for decoder on input stream #0:0 : Invalid argument
```

### Operating system

```
System:
  Host: saturn Kernel: 6.8.0-40-generic arch: x86_64 bits: 64
  Console: pty pts/0 Distro: Ubuntu 24.04 LTS (Noble Numbat)
Machine:
  Type: Desktop Mobo: AWOW model: AK10 v: Prod serial: <superuser required> UEFI: American
    Megatrends LLC. v: 5.27 date: 05/23/2024
CPU:
  Info: quad core Intel N100 [MCP] speed (MHz): avg: 700 min/max: 700/3400
Graphics:
  Device-1: Intel Alder Lake-N [UHD Graphics] driver: i915 v: kernel
  Display: server: No display server data found. Headless machine? tty: 195x63
    resolution: 3840x2160
  API: N/A Message: No API data available in console. Headless machine?
Network:
  Device-1: Intel CNVi: Wi-Fi driver: iwlwifi
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet driver: r8169
  Device-3: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet driver: r8169
Drives:
  Local Storage: total: 4.1 TiB used: 12.29 GiB (0.3%)
Info:
  Memory: total: 12 GiB note: est. available: 11.39 GiB used: 1.3 GiB (11.4%)
  Processes: 222 Uptime: 4h 12m Init: systemd target: graphical (5) Shell: Bash inxi: 3.3.34
```

### Install method

Docker Compose

### Object Detector

CPU (no coral)

**Comment by tzezar** [comment]
Current config (below) results in no birdseye preview image and errors in console, any hint what could be wrong? Latency is lower due to go2rtc, but I believe it is not fully working (no select in camera preview).

```

mqtt:
  enabled: False

go2rtc:
  streams:
    back:
      - rtsp://admin:password@192.168.0.121:554/Preview_01_main
  webrtc:
    candidates:
      - 192.168.0.95:8555
      - stun:8555


record:
  enabled: True
  retain:
    days: 3
    mode: all

detect:
   enabled: False

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.0.121:554/Preview_01_main
          roles:
            - detect
            - record
            - audio
      hwaccel_args: preset-vaapi
environment_vars:
  LIBVA_DRIVER_NAME: i965


version: 0.14
```
```
error
2024-08-17 03:51:39
ffmpeg.back.detect
[AVHWDeviceContext @ 0x5b0d918402c0] No VA display found for device /dev/dri/renderD128.
error
2024-08-17 03:51:39
ffmpeg.back.detect
Device creation failed: -22.
error
2024-08-17 03:51:39
ffmpeg.back.detect
[h264 @ 0x5b0d91841640] No device available for decoder: device type vaapi needed for codec h264.
error
2024-08-17 03:51:39
ffmpeg.back.detect
Device setup failed for decoder on input stream #0:0 : Invalid argument
error
2024-08-17 03:51:40
frigate.video
back: Unable to read frames from ffmpeg process.
error
2024-08-17 03:51:40
frigate.video
back: ffmpeg process is not running. exiting capture thread...
error
2024-08-17 03:51:49
watchdog.back
Ffmpeg process crashed unexpectedly for back.
error
2024-08-17 03:51:49
watchdog.back
The following ffmpeg logs include the last 100 lines prior to exit.
error
2024-08-17 03:51:49
ffmpeg.back.detect
[AVHWDeviceContext @ 0x60506a215e80] No VA display found for device /dev/dri/renderD128.
error
2024-08-17 03:51:49
ffmpeg.back.detect
Device creation failed: -22.
error
2024-08-17 03:51:49
ffmpeg.back.detect
[h264 @ 0x60506a215640] No device available for decoder: device type vaapi needed for codec h264.
error
2024-08-17 03:51:49
ffmpeg.back.detect
Device setup failed for decoder on input stream #0:0 : Invalid argument
error
2024-08-17 03:51:50
frigate.video
back: Unable to read frames from ffmpeg process.
error
2024-08-17 03:51:50
frigate.video
back: ffmpeg process is not running. exiting capture thread...
```
is igpu discovered? I think it is
```
skelaw@saturn:~/docker-compose$ sudo docker exec frigate ls /dev/dri -l
total 4
crw-rw---- 1 root video 226, 1 Aug 17 03:55 card1
drwxr-xr-x 2 root root    4096 Aug 16 23:30 renderD128
```

**Reply by hawkeye217** [reply]
What is your docker compose?

**Reply by tzezar** [reply]
> What is your docker compose?
```
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/skelaw/smart-home/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "100mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/skelaw/smart-home/frigate/config:/config
      - /mnt/usbdrive/media/frigate
      - /dev/dri/renderD128
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: i965
    cap_add:
      - CAP_PERFMON
```

**Reply by NickM-27** [reply]
you need to pass /dev/dri as a device

**Reply by tzezar** [reply]
> you need to pass /dev/dri as a device

Could you please elaborate on what you mean? 
I understand that I should add it next to `/dev/dri/renderD128:/dev/dri/renderD128`, but what should it look like?

**Reply by hawkeye217** [reply]
> > you need to pass /dev/dri as a device
> 
> Could you please elaborate on what you mean? I understand that I should add it next to `/dev/dri/renderD128:/dev/dri/renderD128`, but what should it look like?

Remove it from `volumes:` and just keep the line you have in `devices:`

**Reply by tzezar** [reply]
In such configuration adding `hwaccel_args: preset-vaapi` resuts in no image from every camera.

(added this param just to one camera here)
```
2024-08-17 17:03:44
frigate.video
820A1: Unable to read frames from ffmpeg process.
error
2024-08-17 17:03:44
frigate.video
820A1: ffmpeg process is not running. exiting capture thread...
error
2024-08-17 17:03:57
watchdog.820A1
Ffmpeg process crashed unexpectedly for 820A1.
error
2024-08-17 17:03:57
watchdog.820A1
The following ffmpeg logs include the last 100 lines prior to exit.
error
2024-08-17 17:03:57
ffmpeg.820A1.detect
[AVHWDeviceContext @ 0x56fa9ca5fc40] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
error
2024-08-17 17:03:57
ffmpeg.820A1.detect
[AVHWDeviceContext @ 0x56fa9ca5fc40] Failed to initialise VAAPI connection: -1 (unknown libva error).
error
2024-08-17 17:03:57
ffmpeg.820A1.detect
Device creation failed: -5.
error
2024-08-17 17:03:57
ffmpeg.820A1.detect
[h264 @ 0x56fa9c927ec0] No device available for decoder: device type vaapi needed for codec h264.
error
2024-08-17 17:03:57
ffmpeg.820A1.detect
Device setup failed for decoder on input stream #0:0 : Input/output error
```

**Reply by NickM-27** [reply]
what CPU are you using

**Reply by tzezar** [reply]
> what CPU are you using

Intel N100
```
CPU:
  Info: quad core Intel N100 [MCP] speed (MHz): avg: 700 min/max: 700/3400
Graphics:
  Device-1: Intel Alder Lake-N [UHD Graphics] driver: i915 v: kernel
  Display: server: No display server data found. Headless machine? tty: 195x63
    resolution: 3840x2160
  API: N/A Message: No API data available in console. Headless machine?
```

**Reply by NickM-27** [reply, marked as answer]
you need to remove

```
environment_vars:
  LIBVA_DRIVER_NAME: i965
```

from your docker compose then re-apply with `docker compose up -d`

**Reply by tzezar** [reply]
It works! Thank you so much brother.


![image](https://github.com/user-attachments/assets/5728b5e0-d744-4116-996c-75272a228837)
8 cameras with detection on

**Comment by tzezar** [comment]
I paste the whole config in case anyone needs it

```
mqtt:
  enabled: false

go2rtc:
  streams:
    RLC-820A1:
      - rtsp://admin:password@192.168.0.121:554/Preview_01_main
    RLC-820A1_sub:
      - rtsp://admin:password@192.168.0.121:554/Preview_01_sub
    RLC-820A2:
      - rtsp://admin:password@192.168.0.122:554/Preview_01_main
    RLC-820A2_sub:
      - rtsp://admin:password@192.168.0.122:554/Preview_01_sub
    RLC-520A3:
      - rtsp://admin:password@192.168.0.123:554/Preview_01_main
    RLC-520A3_sub:
      - rtsp://admin:password@192.168.0.123:554/Preview_01_sub
    RLC-520A4:
      - rtsp://admin:password@192.168.0.124:554/Preview_01_main
    RLC-520A4_sub:
      - rtsp://admin:password@192.168.0.124:554/Preview_01_sub
    RLC-520A5:
      - rtsp://admin:password@192.168.0.125:554/Preview_01_main
    RLC-520A5_sub:
      - rtsp://admin:password@192.168.0.125:554/Preview_01_sub
    RLC-520A6:
      - rtsp://admin:password@192.168.0.126:554/Preview_01_main
    RLC-520A6_sub:
      - rtsp://admin:password@192.168.0.126:554/Preview_01_sub
    RLC-520A7:
      - rtsp://admin:password@192.168.0.127:554/Preview_01_main
    RLC-520A7_sub:
      - rtsp://admin:password@192.168.0.127:554/Preview_01_sub
    RLC-520A8:
      - rtsp://admin:password@192.168.0.128:554/Preview_01_main
    RLC-520A8_sub:
      - rtsp://admin:password@192.168.0.128:554/Preview_01_sub
  webrtc:
    candidates:
      - 192.168.0.95:8555
      - stun:8555


ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  enabled: True

birdseye:
  enabled: False
  restream: True

record:
  enabled: true
  retain:
    days: 3
    mode: all
  sync_recordings: True

cameras:
  RLC-820A1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-820A1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-820A1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 10
  RLC-820A2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-820A2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-820A2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 10
  RLC-520A3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-520A3
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-520A3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
  RLC-520A4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-520A4
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-520A4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
  RLC-520A5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-520A5
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-520A5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10

  RLC-520A6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-520A6
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-520A6_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
  RLC-520A7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-520A7
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-520A7_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
  RLC-520A8:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC-520A8
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC-520A8_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10

version: 0.14
```

```

services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/skelaw/smart-home/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "400mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/skelaw/smart-home/frigate/config:/config
      - /mnt/usbdrive/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    cap_add:
      - CAP_PERFMON
```
