### DISCUSSION TITLE
[Question]: go2rtc is still a mystery: use Frigate to feed MotionEye?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#13123] [Ask A Question]
### What is your question:

Hello all

In order to achieve only one set of IP connections to my eight camera  NVR source,  I would like to use Frigate (presumably employing its "internal" implementation of go2rtc) to generate a replica stream, feeding [Motioneye](https://github.com/motioneye-project/motioneye/wiki),  a video camera application.

I have Frigate in a Docker container and, on the same box, Motioneye in a Docker container.  Currrently they both connect to the NVR IP address and they both process the eight rtsp streams.  My NVR sometimes crashes if too many connections are made to its server.

In spite of reading about it, I still haven't understood the workings of go2rtc but this is (I hope a pertinent snippet of) the working config I have. I have marked four lines (here, not in the config!) with four queries ##Q1## etc.:

```
  go2rtc:
    streams:
      camera_one:
##Q1##      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0#video=h264#audio=copy#hardware
##Q2##      - ffmpeg:camera_one#audio=opus                                                                                                                   
```

and then later on in the config

```
    cameras:
      camera_one:
        enabled: true
        ffmpeg:
          inputs:
##Q3##        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #SD 640x360 level1
            roles:
              - detect
##Q4##        - path: rtsp://127.0.0.1:8554/camera_one                                                                                        
            roles:
              - record
```
**Q1** to **Q4**, line by line: what is it doing?

does **Q1** read an NVR rtsp stream - HD video - and appends some predefined options (in the form of `#statements` I think) ?

does **Q2** define this stream as "camera_one" and it then appends a standard audio profile `#opus` ?

Is **Q3** another connection to the NVR, but for the substream? There must be a pair of unavoidable connections if you want a main (HD) and a sub (SD) stream.

Would a "tidier" option be for me to use go2rtc above to also define the SD connection as camera_one_sub or something?

Is **Q4** the local server (Docker) rebroadcasting the camera_one ffmpeg "copy" defined in **Q2** ?

If this is about right, I would have 

`[NVR]`------>`[Frigate]`------>`[go2rtc internals]`------>`[MotionEye]`

I could then have 
`127.0.0.1/camera_one` 
and
`127.0.0.1/camera_one_sub`
feeding "out". **What form are they in - stil in rtsp form?**

If so, I can presumably tell Motioneye to expect to see some IP network cameras at `127.0.0.1` or `localhost` etc.

(I have tried already but it didn't work, so I then realised how unsure I am regarding these mechanisms).
