### DISCUSSION TITLE
[Support]: Live view sometimes fails to load for Unifi camera

### DISCUSSION THREAD

**Discussion by masonevans** [blakeblackshear/frigate#13126] [General Support] [answered]
### Describe the problem you are having

I recently added a Unifi G4 Instant to my system.  Sometimes when I click on the camera from Bird's eye view to view the full live view for the camera, I just get the spinner, which sits forever.  Sometimes it loads ok.  There doesn't seem to be anything I can do to make it work or not work.   All my other cameras work fine.

Some additional things I've noticed

* When I try to load the camera stream directly in go2rtc, it doesn't ever have problems (neither MSE nor WebRTC)
* The times where I have the stream open in Frigate and it's just spinning, if I go to the go2rtc info about the camera, I do not see an MSE or WebRTC consumer listed (just the Frigate RTSP consumer).  When the stream is working, the go2rtc info for the camera does show an MSE consumer.  So, it seems like Frigate isn't even trying to connect (or fails to connect & aborts).
* There are no errors in the js console
* There are no errors in the Frigate or go2rtc logs
* The times where the stream is working, I can see the open websocket connection in the dev tools network tab, and I see data streaming.  The times where it has failed, I can see that the websocket connection is closed, and there are alway just three messages that look like this:
    
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/0d5514f6-f81e-458b-a189-ad64f0398f25">

I've tried different input & output args in the config but nothing seems to have any effect

### Steps to reproduce

1. Go to my bird's eye view
2. Click on the camera
3. Sometimes it works, sometimes it doesn't

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  host: mqtt.local
ffmpeg:
  hwaccel_args: preset-vaapi
record:
  enabled: True
  retain:
    days: 14
    mode: all
snapshots:
  enabled: True
birdseye:
  mode: continuous
objects:
  track:
    - person
    - face
    - car
    - license_plate
    - cat
    - dog
    - deer
    - amazon
    - ups
    - fedex
    - package
  filters:
    person:
      threshold: .8
    car:
      threshold: .8
    dog:
      threshold: .8
    cat:
      threshold: .8
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
motion:
  improve_contrast: True
go2rtc:
  streams:
    garageInside:
      - rtspx://192.168.1.1:7441/8sNibnNaSPM2T9J0
    garageInside_sub:
      - rtspx://192.168.1.1:7441/7RmLDIEvUrWUdBpH
  webrtc:
    candidates:
      - 192.168.1.70:8555
      - stun:8555
cameras:
  garageInside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garageInside
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garageInside_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      enabled: False
      width: 1280
      height: 720
      fps: 5
```

### Relevant log output

```shell
Nothing in the logs
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Unifi G4 Instant

**Comment by hawkeye217** [comment]
Are you using Safari?

**Reply by masonevans** [reply]
The exact same thing happens on Safari & Chrome.  The screen shot of the websocket data was from Chrome dev tools but I see literally the same behavior on Safari too.

**Reply by hawkeye217** [reply]
Can you pull `ghcr.io/hawkeye217/frigate:dev-eb2d6b5` and paste the console logs you get when the live view fails to open?

**Reply by hawkeye217** [reply]
Also, can you post a screenshot of the same dev tools pane you posted above but for a working camera? I'll just need to see the first couple of lines of the buffer, before it starts sending "Binary Message".

**Reply by masonevans** [reply]
I was not able to reproduce the issue with your build.  The times when it seemed like it was going to fail, it looks like it successfully switched to WebRTC, which the 0.14.0 build did not seem to be doing (I never saw a Frigate WebRTC connection in the go2rtc camera info).  After being unable to repro using your build, I rolled my system back to the 0.14.0 release and was able to reproduce the issue again right away.

This is in Chrome with your build:

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/e827a2f3-ae27-4682-a055-48bc5b2fdd44">

WS data for a working MSE connection using your build:

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/8c6c3db9-111e-4c02-80ac-2c69b756c816">

WS data for a working MSE connection using 0.14.0:

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/92d0ea32-01c6-4910-af1a-9ec5b0b7ce62">

**Reply by hawkeye217** [reply]
Great. Thanks for testing.

Can you try this in your go2rtc config and see if it changes the behavior on 0.14?

```
go2rtc:
  streams:
    garageInside:
      - ffmpeg:rtspx://192.168.1.1:7441/8sNibnNaSPM2T9J0#video=copy#audio=aac
```

**Reply by masonevans** [reply]
Nope - that did not seem to change anything

**Reply by hawkeye217** [reply]
Alright. What if you did this temporarily:

```
go2rtc:
  streams:
    garageInside:
      - ffmpeg:rtspx://192.168.1.1:7441/8sNibnNaSPM2T9J0#video=h264#hardware
```

**Reply by masonevans** [reply]
No change, same behavior

**Reply by hawkeye217** [reply]
Alright, thanks. Revert those changes. What happens if you switch to the substream?

In your camera config, set:

```
cameras:
  garageInside:
    live:
      stream_name: garageInside_sub
    ffmpeg:
...
```

**Reply by masonevans** [reply]
Switching to substream did not help

**Reply by hawkeye217** [reply]
Alright, thanks. I really have no idea why this would happen with only one camera and not any of your others. Can you adjust the i-frame interval at all on the `garageInside` cam?

**Reply by masonevans** [reply]
It doesn't look like this camera has a way to set the iframe interval.

One thing I just noticed while I was trying some other ideas.  I previously had a different camera in go2rtc that was called `garageInside`.  Just in case something weird was happening with re-using the name, I updated it to `garageInside2` and updated the camera config (there wasn't ever a substream for the old camera so I didn't rename that).

After making that change, I see new behavior.  Now, live view doesn't even try to load the MSE stream (confirmed in the devtools network tab).  It just spins for a sec and shows the jsmpeg stream. But that loads 100% of the time consistently.  If I look at the history for the camera, I do see the recording in hi-res, so I know that stream is configured correctly.  And going directly to go2rtc works fine for both the main stream & substream for MSE & WebRTC.

And if I change it back to the old name (`garageInside`) then I see the old behavior again (intermittent failures of the hi-res stream)!

```
go2rtc:
  streams:
    garageInside2:
      - rtspx://192.168.1.1:7441/8sNibnNaSPM2T9J0
    garageInside_sub:
      - rtspx://192.168.1.1:7441/7RmLDIEvUrWUdBpH
...
cameras:
  garageInside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garageInside2
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garageInside_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      enabled: False
      width: 1280
      height: 720
      fps: 5
```
