### DISCUSSION TITLE
[Camera Support]: no preview found

### DISCUSSION THREAD

**Discussion by williamcanon1** [blakeblackshear/frigate#13132] [Camera Support]
### Describe the problem you are having

Why do some events show 'no preview found'? The same camera can replay some events but not others.
![Screenshot_20240817_151500_Chrome](https://github.com/user-attachments/assets/3e83152e-7c8c-447d-bc53-847fcc437e78)

### Version

latest

### Frigate config file

```yaml
1
```

### Relevant log output

```shell
1
```

### FFprobe output from your camera

```shell
1
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wireless

### Camera make and model

other

**Comment by hawkeye217** [comment]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Upgrade Issues question 3.

**Reply by rpendleton** [reply]
I don't know if it's the same for @williamcanon1, but for what it's worth, I'm seeing this inconsistently even for footage that was recorded with version 0.14.

I upgraded to version 0.14 around 5 pm today. I'm able to load previews between 6 pm and 10 pm, but 10 pm through 11 pm is completely missing. Previews start working again at 11 pm, and it's 11:18 right now. So somehow, I lost an hour of previews.

**Reply by williamcanon1** [reply]
Yes, I reinstalled the latest version, but on the same day, there are always a few alarm previews that are invalid.

**Reply by hawkeye217** [reply]
What is your frigate config file?

**Reply by williamcanon1** [reply]
```
detectors:
  coral:
    type: cpu
environment_vars:
  LIBVA_DRIVER_NAME: iHD
ffmpeg:
  hwaccel_args: preset-vaapi
mqtt:
  host: 192.168.11.2
  user: frigate
  password: password
go2rtc:
  streams:
    camera6:
      - ffmpeg:rtsp://admin:password@192.168.1.100:554/mpeg4#video=h265#hardware=vaapi
    camera7:
      - ffmpeg:rtsp://admin:password@192.168.1.101:554/mpeg4#video=h265#hardware=vaapi
    camera8:
      - ffmpeg:rtsp://admin:password@192.168.1.102:554/mpeg4#video=h265#hardware=vaapi
    camera9:
      - ffmpeg:rtsp://admin:password@192.168.1.103:554/mpeg4#video=h265#hardware=vaapi
    camera10:
      - ffmpeg:rtsp://admin:password@@192.168.11.170:554/stream1#video=h265#audio=aac#hardware=vaapi
cameras:
  camera6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera6?video&audio=aac
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain:
      expire_interval: 60
      sync_recordings: true
  camera7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera7?video&audio=aac
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain:
      expire_interval: 60
      sync_recordings: true
  camera8:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera8?video&audio=aac
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain:
      expire_interval: 60
      sync_recordings: true
  camera9:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera9?video&audio=aac
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain:
      expire_interval: 60
      sync_recordings: true
  camera10:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera10?video&audio=aac
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain:
      expire_interval: 60
      sync_recordings: true
objects:
  track:
    - person
    - car
    - motorcycle
  filters:
    person:
      min_score: 0.5
      threshold: 0.7
version: 0.14
camera_groups:
  ba:
    order: 1
    icon: LuAccessibility
    cameras:
      - camera10
      - camera6
      - camera7
      - camera8
      - camera9
tls:
  enabled: False
```
