### DISCUSSION TITLE
Memory leak with ffmpeg

### DISCUSSION THREAD

**Discussion by gonzalezcalleja** [blakeblackshear/frigate#13133] [General]
Hi! 

I have detected some memory leak withe some Foscam cameras (C5M), for example this ffmpeg process:

```
ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://redacted:redacted@127.0.0.1:8554/cocina?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/cocina@%Y%m%d%H%M%S%z.mp4
```

After many hours working well, this ffmpeg process started to consume a lot of ram (~6Gb  and growing) and then swap ...  any advice on where to continue in the search for the cause of the problem?*

I'm not using virtualization, is all baremetal: 
- AMD Ryzen 7 5700U
- Coral accelerator -PCIe in M2 adapter-
- Ubuntu 24.04
- kernel 6.8.0-40-generic

I'm using this camera through go2rtc: 

```
    cocina:
      - ffmpeg:rtsp://redacted:redacted@192.168.6.238:88/videoMain#video=copy#audio=copy#audio=aac
```

and this is the camera config:

```
  cocina:
    ui:
      order: 8
      dashboard: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://redacted:redacted@127.0.0.1:8554/cocina_sub?video=copy&audio=copy
          roles:
            - detect
            - audio
        - path: rtsp://redacted:redacted@127.0.0.1:8554/cocina?video=copy&audio=aac
          roles:
            - record
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.8
    live:
      stream_name: cocina_sub
    audio:
      enabled: true
      min_volume: 600
    motion:
      mask: 0.348,0,0.268,0.032,0,0.49,0,0
    detect:
      width: 1280
      height: 720
```

Thanks for your support!
