### DISCUSSION TITLE
[Support]: external drive as a storage problem

### DISCUSSION THREAD

**Discussion by tzezar** [blakeblackshear/frigate#13144] [General Support] [answered]
### Describe the problem you are having

I would like to save recordings to an external HDD drive connected via USB. The drive has been mounted. It is visible in the system. In `compose.config` I changed the media parameter to ` - /mnt/usbdrive:/media/frigate` however in the frigate UI I still see only 100gb (probably from the container) instead of 4TB. 

![image](https://github.com/user-attachments/assets/cdd30753-4671-40af-a04e-104e4deac8f6)

In logs there is warning:
```
Type
  warning
Timestamp
  2024-08-17 19:08:22
Tag
  frigate.record.util
Message
  Deleting 0.872791% of recordings DB entries, could be due to configuration error. Aborting...
```

Am I missing something?

### Version

0.14.0-da913d8

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink

**Comment by NickM-27** [comment]
What is the compose file

**Reply by tzezar** [reply]
```

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    environment:
      - EMQX_NAME=emqx
      - EMQX_NODE__COOKIE=emqxsecretcookie
    volumes:
      - emqx_data:/home/skelaw/smart-home/emqx/data
      - emqx_log:/home/skelaw/smart-home/emqx/log
    restart: unless-stopped

  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/skelaw/smart-home/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "400mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardw>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/skelaw/smart-home/frigate/config:/config
      - /mnt/usbdrive:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    cap_add:
      - CAP_PERFMON

volumes:
  emqx_data:
  emqx_log:
```

**Reply by NickM-27** [reply]
What did you do to mount the storage? In general I'd recommend letting docker manage the mounting of the storage

**Reply by tzezar** [reply]
> What did you do to mount the storage? In general I'd recommend letting docker manage the mounting of the storage

I run some linux commands like `sudo gdisk /dev/sda`, then I created partition, formatted it with `sudo mkfs.ntfs -f /dev/sda1` and mounted it via `sudo mount /dev/sda1 /mnt/usbdrive` and added automount on boot in `sudo nano /etc/fstab`. I can verify disk mount with `ls /mnt/usbdrive`. There are some dirs like `clips`, `exports`, `recordings` - seems like they were created by frigate, but in UI I can see as above (just 100gb)

```
skelaw@saturn:~$ lsblk
NAME                      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda                         8:0    0   3.6T  0 disk
└─sda1                      8:1    0   3.6T  0 part
nvme0n1                   259:0    0 476.9G  0 disk
├─nvme0n1p1               259:1    0     1G  0 part /boot/efi
├─nvme0n1p2               259:2    0     2G  0 part /boot
└─nvme0n1p3               259:3    0 473.9G  0 part
  └─ubuntu--vg-ubuntu--lv 252:0    0   100G  0 lvm  /
```

**Reply by tzezar** [reply]
Oh, I used some magic commands from web, restarded whole machine and seems like frigate is now using new disk! Not sure which one of the commands worked, but it worked! 

Anyway second question then because I dont remember seeing it in docs: 
How to allocate more space to each camera? Now in UI it shows ~43.48GB per camera, will it increase its size automatically when needed?

![obraz](https://github.com/user-attachments/assets/f236418f-b3fe-46c8-aae9-39d5b1cf721e)

**Comment by astyrrian1** [comment]
I have the exact same issue. I added an external USB SSD, changed my /media path in docker compose to point to the external volume, but Frigate still seems to calculate storage on it's original drive / where the config also is. Any ideas on how to get it to see the full storage available for the storage path?

**Reply by NickM-27** [reply]
What is your compose?

**Reply by astyrrian1** [reply]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /Volumes/SSD/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984" # go2rtc Web UI
      - "8971:8971"
      - "5001:5000" # Internal unauthenticated access. Expose carefully.
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
     PLUS_API_KEY: "..."
```

I also did run docker compose up -d --force-recreate in case it makes any different. Host is latest Mac OS on M1 Mini.
