### DISCUSSION TITLE
[Config Support]: Frigate Reolink auth request unexpected status: 502 while sending to client

### DISCUSSION THREAD

**Discussion by theyaw** [blakeblackshear/frigate#13148] [Config Support] [answered]
### Describe the problem you are having

Frigate won't connect to the camera when I run the docker container.

### Version

3.9

### Frigate config file

```yaml
mqtt:
  host: mqtt://192.168.1.104:1883
  user: mqtt
  password: pass1234

go2rtc:
  streams:
    dbell:
      - "ffmpeg:http://192.168.1.105/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=passwerd1#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.1.105/Preview_01_sub
    dbell_sub:
      - "ffmpeg:http://192.168.1.105/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=passwerd1"
     

cameras:
  dbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```


### Relevant log output

```shell
docker-compose up
time="2024-08-17T15:08:57-05:00" level=warning msg="C:\\Users\\User\\frigate\\compose.yml: `version` is obsolete"
[+] Running 8/8
 ✔ frigate Pulled                                                                                                                                                                                                                     38.6s
   ✔ 5de87e84afee Pull complete                                                                                                                                                                                                        5.2s
   ✔ b5dd446ad6ed Pull complete                                                                                                                                                                                                       24.8s
   ✔ d996c67e8747 Pull complete                                                                                                                                                                                                       36.5s
   ✔ c846b97ae33e Pull complete                                                                                                                                                                                                       37.1s
   ✔ 6b1c6be91a14 Pull complete                                                                                                                                                                                                       37.2s
   ✔ 79a14b2aac4d Pull complete                                                                                                                                                                                                       37.2s
   ✔ 92f5b4c367e8 Pull complete                                                                                                                                                                                                       37.5s
[+] Running 2/1
 ✔ Container frigate                                                  Created                                                                                                                                                         10.0s
 ! frigate Published ports are discarded when using host network mode                                                                                                                                                                  0.0s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2024-08-17 20:09:46.751324660  [INFO] Preparing Frigate...
frigate  | 2024-08-17 20:09:46.753404646  [INFO] Starting NGINX...
frigate  | 2024-08-17 20:09:46.753698559  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-17 20:09:46.760651048  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2024-08-17 20:09:46.765354543  [INFO] Starting Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-08-17 20:09:47.056184936  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-08-17 20:09:47.113905736  127.0.0.1 - - [17/Aug/2024:20:09:47 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-08-17 20:09:47.156760518  [INFO] Starting go2rtc...
frigate  | 2024-08-17 20:09:47.267285514  20:09:47.267 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-08-17 20:09:47.267347317  20:09:47.267 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-08-17 20:09:47.267781035  20:09:47.267 INF [rtsp] listen addr=:8554
frigate  | 2024-08-17 20:09:47.268356559  20:09:47.268 INF [api] listen addr=:1984
frigate  | 2024-08-17 20:09:47.268504065  20:09:47.268 INF [webrtc] listen addr=:8555/tcp
frigate  | 2024-08-17 20:09:48.418584386  [2024-08-17 20:09:48] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
frigate  | 2024-08-17 20:09:48.422542251  [2024-08-17 20:09:48] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-08-17 20:09:48.436227120  [2024-08-17 20:09:48] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-08-17 20:09:48.476014674  [2024-08-17 20:09:48] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
frigate  | 2024-08-17 20:09:51.657011543  2024/08/17 20:09:51 [error] 174#174: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate  | 2024-08-17 20:09:51.657015443  2024/08/17 20:09:51 [error] 174#174: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate  | 2024-08-17 20:09:55.339103444  [2024-08-17 20:09:55] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-08-17 20:09:55.340350396  [2024-08-17 20:09:55] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-08-17 20:09:55.357663607  [2024-08-17 20:09:55] frigate.app                    INFO    : Recording process started: 394
frigate  | 2024-08-17 20:09:55.363325739  [2024-08-17 20:09:55] frigate.app                    INFO    : Recording process started: 396
frigate  | 2024-08-17 20:09:55.370712843  [2024-08-17 20:09:55] frigate.app                    INFO    : go2rtc process pid: 104
frigate  | 2024-08-17 20:09:55.393519879  [2024-08-17 20:09:55] detector.cpu                   INFO    : Starting detection process: 423
frigate  | 2024-08-17 20:09:55.397349036  [2024-08-17 20:09:55] frigate.app                    INFO    : Output process started: 425
frigate  | 2024-08-17 20:09:55.397519843  [2024-08-17 20:09:55] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-08-17 20:09:55.413376094  [2024-08-17 20:09:55] frigate.app                    INFO    : Camera processor started for dbell: 439
frigate  | 2024-08-17 20:09:55.424185438  [2024-08-17 20:09:55] frigate.app                    INFO    : Capture process started for dbell: 440
frigate  | 2024-08-17 20:09:56.752408282  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-08-17 20:10:01.313803309  [2024-08-17 20:10:01] frigate.comms.mqtt             ERROR   : Unable to publish to dbell/all: client is not connected
frigate  | 2024-08-17 20:10:01.313912913  [2024-08-17 20:10:01] frigate.comms.mqtt             ERROR   : Unable to publish to dbell/motion: client is not connected
frigate  | 2024-08-17 20:10:20.659295602  [2024-08-17 20:10:20] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
frigate  | 2024-08-17 20:10:47.130826034  127.0.0.1 - - [17/Aug/2024:20:10:47 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-08-17 20:11:20.715589237  [2024-08-17 20:11:20] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
frigate  | 2024-08-17 20:11:47.145730652  127.0.0.1 - - [17/Aug/2024:20:11:47 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-08-17 20:12:20.771838029  [2024-08-17 20:12:20] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
frigate  | 2024-08-17 20:12:47.158563294  127.0.0.1 - - [17/Aug/2024:20:12:47 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-08-17 20:13:20.833166484  [2024-08-17 20:13:20] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
frigate  | 2024-08-17 20:13:47.167555319  127.0.0.1 - - [17/Aug/2024:20:13:47 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-08-17 20:14:20.883390930  [2024-08-17 20:14:20] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
```


### Frigate stats

_No response_

### Operating system

Windows

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Any other information that may be helpful

_No response_

**Comment by hawkeye217** [comment]
You need to specify the rtsp port for the rtsp stream in your go2rtc config:

`- rtsp://192.168.1.105:554/Preview_01_sub`

**Comment by hawkeye217** [comment, marked as answer]
Also, your `mqtt` host should just be:

`host: 192.168.1.104`

**Reply by theyaw** [reply]
still same error

frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-08-17 21:22:32.555551567  [INFO] Preparing Frigate...
frigate  | 2024-08-17 21:22:32.561448238  [INFO] Starting NGINX...
frigate  | 2024-08-17 21:22:32.696779368  [INFO] Starting Frigate...
frigate  | 2024-08-17 21:22:32.696808370  [INFO] Preparing new go2rtc config...
frigate  | 2024-08-17 21:22:33.764725230  [INFO] Starting go2rtc...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-08-17 21:22:33.859583397  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-08-17 21:22:33.931055987  21:22:33.930 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-08-17 21:22:33.931059187  21:22:33.931 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-08-17 21:22:33.932664261  21:22:33.932 INF [api] listen addr=:1984
frigate  | 2024-08-17 21:22:33.932745765  21:22:33.932 INF [rtsp] listen addr=:8554
frigate  | 2024-08-17 21:22:33.933824115  21:22:33.933 INF [webrtc] listen addr=:8555/tcp
frigate  | 2024-08-17 21:22:33.938973252  127.0.0.1 - - [17/Aug/2024:21:22:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-08-17 21:22:36.799892152  [2024-08-17 21:22:36] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
frigate  | 2024-08-17 21:22:36.802460370  [2024-08-17 21:22:36] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-08-17 21:22:36.832357446  [2024-08-17 21:22:36] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-08-17 21:22:36.947152631  [2024-08-17 21:22:36] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
frigate  | 2024-08-17 21:22:37.236669158  2024/08/17 21:22:37 [error] 163#163: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate  | 2024-08-17 21:22:37.236704460  2024/08/17 21:22:37 [error] 163#163: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate  | 2024-08-17 21:22:42.295842982  2024/08/17 21:22:42 [error] 164#164: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate  | 2024-08-17 21:22:42.295846283  2024/08/17 21:22:42 [error] 164#164: *4 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate  | 2024-08-17 21:22:42.558120373  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-08-17 21:22:43.899075038  [2024-08-17 21:22:43] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-08-17 21:22:43.900508411  [2024-08-17 21:22:43] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-08-17 21:22:43.930456840  [2024-08-17 21:22:43] frigate.app                    INFO    : Recording process started: 401
frigate  | 2024-08-17 21:22:43.941282093  [2024-08-17 21:22:43] frigate.app                    INFO    : Recording process started: 402
frigate  | 2024-08-17 21:22:43.948304051  [2024-08-17 21:22:43] frigate.app                    INFO    : go2rtc process pid: 101
frigate  | 2024-08-17 21:22:44.045781628  [2024-08-17 21:22:44] detector.cpu                   INFO    : Starting detection process: 430
frigate  | 2024-08-17 21:22:44.086274996  [2024-08-17 21:22:44] frigate.app                    INFO    : Output process started: 431
frigate  | 2024-08-17 21:22:44.090173595  [2024-08-17 21:22:44] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-08-17 21:22:44.123506197  [2024-08-17 21:22:44] frigate.app                    INFO    : Camera processor started for dbell: 447
frigate  | 2024-08-17 21:22:44.146784685  [2024-08-17 21:22:44] frigate.app                    INFO    : Capture process started for dbell: 448
frigate  | 2024-08-17 21:22:50.024516212  [2024-08-17 21:22:50] frigate.comms.mqtt             ERROR   : Unable to publish to dbell/all: client is not connected
frigate  | 2024-08-17 21:22:50.024649719  [2024-08-17 21:22:50] frigate.comms.mqtt             ERROR   : Unable to publish to dbell/motion: client is not connected
frigate  | 2024-08-17 21:23:09.448628947  [2024-08-17 21:23:09] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected

**Reply by hawkeye217** [reply]
The 502 error is expected while Frigate is starting up. It's just the UI in your browser trying to talk to the server, and it hasn't started up yet. As you can see, once the camera and capture processes are started, you don't see those errors anymore.

The last 3 lines of the log are the ones you want to pay attention to. If you plan to use MQTT (for the Home Assistant integration, for example), you'll want to make sure you have an MQTT broker running and that the username and password are correct.

**Reply by theyaw** [reply]
I have MQTT broker and it's running. The credentials are correct as well
![image](https://github.com/user-attachments/assets/ac284084-0be9-4710-b28f-906638e3166a)

**Reply by hawkeye217** [reply]
Did you see my earlier message? Did you change your mqtt section to:

```
mqtt:
  host: 192.168.1.104
  port: 1883
  user: mqtt
  password: pass1234
```

**Reply by theyaw** [reply]
My apologies sir. I am a complete idiot. i still had the mqtt protocol in front of the host address. Removed it and it connected. I see the frigate connection in mqtt now. but I can't access the web at the localhost:5000 address even tho I have network mode set to host. Any help with that?

**Reply by hawkeye217** [reply]
What's your docker compose file?

**Reply by theyaw** [reply]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - C:/Users/user1/frigate:/config
      - K:/Frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
 ```
