### DISCUSSION TITLE
[Support]: Very high FFMPEG CPU Usage on RPi5 from Reolink RTSP Camera

### DISCUSSION THREAD

**Discussion by mike6789** [blakeblackshear/frigate#13145] [General Support] [answered]
### Describe the problem you are having

I have a dedicated Raspberry Pi 5 running Frigate in Docker (with docker compose). I have two cameras connected, one is a low resolution MJPEG camera and another is a high resolution (4K) RTSP camera (the Reolink). I have tried to enable HEVC hardware accelerated decoding but it does not seem to be working at all as my CPU usage for FFMPEG on the Reolink camera is over 100%...

FFMPEG CPU usage for my other camera is only 6% or so.

Is any of this expected, or is something wrong? I want to get to the bottom of this so I can understand if there is some limitation with the hardware or not.

Thank you

### Version

0.14.0-da913d8

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args:
    - -c:v:1
    - hevc_v4l2m2m

go2rtc:
  streams:
    mycamera: ffmpeg:http://*****:*****@192.168.1.87/video.cgi#video=h264#hardware
    reolink: ffmpeg:rtsp://*****:*****@192.168.1.76:554/

mqtt:
  enabled: true
  host: 192.168.1.74
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *****
  password: *****
  stats_interval: 60

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

logger:
  default: info
  logs:
    frigate.comms.mqtt: debug
    frigate.mqtt: debug
    frigate.object_detection: debug
    detector.cpu: debug

cameras:
  mycamera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mycamera
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          roles:
            - record

version: 0.14
camera_groups:
  Bird's_Eye:
    order: 1
    icon: LuTwitter
    cameras: birdseye
```

### Relevant log output

```shell
No log errors per se... just high CPU usage
```

### FFprobe output from your camera

```shell
*****@frigate:~/frigate-nvr $ ffprobe rtsp://*****:*****@192.168.1.76/
ffprobe version 5.1.5-0+rpt1+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+rpt1+deb12u1 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --disable-mmal --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sand --enable-sdl2 --disable-sndio --enable-libjxl --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://*****:*****@192.168.1.76/':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000500, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink CX810
