### DISCUSSION TITLE
[Bug]: No possibility to watch motion recordings

### DISCUSSION THREAD

**Discussion by krojew** [blakeblackshear/frigate#13155] [Report a Bug]
### Describe the problem you are having

With the new UI, there doesn't seem to be any possibility of watching recordings based only on motion. In the old UI, one simply had to click Recordings -> Hour, but now when I go to Camera -> Reviews -> Motion -> Yellow timeline marker, I simply get a blank rectangle with "No Preview Found". There's no video when clicking on the timeline markers. There's no way to go to a fullscreen recording and skip the preview. There's no way to view a simple list of recordings. With Home Assistant integration, I can see there are, in fact, recordings.

### Steps to reproduce

1. Set up a camera to capture on motion only.
2. Wait for some motion events to register.
3. Try to watch recordings.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx
  user: xxx
  password: xxx
birdseye:
  enabled: false
record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      mode: motion
detect:
  enabled: true
motion:
  threshold: 20
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
ffmpeg:
  retry_interval: 60
cameras:
  xxx:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - detect
            - record
    webui_url: xxx
    detect:
      enabled: false
    record:
      retain:
        days: 2
        mode: motion
    motion:
      mask:
        - 0,68,754,61,758,0,0,0
version: 0.14
```

### Relevant log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

Please give the option to bring back the old UI.
