### DISCUSSION TITLE
[Config Support]: Black camera in live view

### DISCUSSION THREAD

**Discussion by 2d65** [blakeblackshear/frigate#13153] [Config Support] [answered]
### Describe the problem you are having

After upgrading to 0.14 , the second camera in my live view is black.  No errors are listed but the feed is black.  I can click on on the black feed which direct directs me to the the full screen view which works fine.   The go2rtc dashboard shows all streams and they all display valid video when clicked.   I did noticed that the feeds in Frigate would sometimes swap on restart.  Meaning Backyard_1 would be black and on the following restart, Backyard_2  would be black instead.   Seems to depend on startup or some order condition..  As a test I added a dummy camera to see if it would "skip" and sure enough I can see all cameras if I inject a dummy/duplicate camera in between.  The dummy camara is now black but the desired feeds are fine.

 I just now tested removing go2rtc by going directly to the rtsp stream in the camera section.. same problem.

Other tests: deleted db files and restarted.  Same problem.

A second pair of eyes would be appreciated.

### Version

0.14

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.10.2
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: xxx
  password: yyy
  stats_interval: 60

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)

go2rtc:
  # ffmpeg:
  #   preset-http-reolink: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i {input}"
  streams:
    Backyard_1_go:
    - rtsp://xxx:yyy@10.0.5.17:554/h264Preview_01_main
    Backyard_1_go_sub:
    - rtsp://xxx:yyy@10.0.5.17:554/h264Preview_01_sub
    Dummy_go_sub:
    - rtsp://xxx:yyy@10.0.5.17:554/h264Preview_01_sub
    Backyard_2_go:
    - rtsp://xxx:yyy@10.0.5.16:554/h264Preview_01_main
    Backyard_2_go_sub:
    - rtsp://xxx:yyy@10.0.5.16:554/h264Preview_01_sub

cameras:
  Backyard_1:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        - path: rtsp://127.0.0.1:8554/Backyard_1_go_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Backyard_1_go
          roles:
            - record
  Dummy_sub:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        - path: rtsp://127.0.0.1:8554/Dummy_go_sub
          roles:
            - detect
  Backyard_2:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        - path: rtsp://127.0.0.1:8554/Backyard_2_go_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Backyard_2_go

          roles:
            - record
              
version: 0.14
```

### Relevant log output

```shell
Frigate logs:

2024-08-17 22:40:44.011456317  [INFO] Preparing Frigate...
2024-08-17 22:40:44.027994887  [INFO] Starting Frigate...
2024-08-17 22:40:44.982220865  [2024-08-17 22:40:44] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
2024-08-17 22:40:44.982267815  [2024-08-17 22:40:44] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-08-17 22:40:44.995718139  [2024-08-17 22:40:44] frigate.util.config            INFO    : frigate config does not need migration...
2024-08-17 22:40:45.419017909  [2024-08-17 22:40:45] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-08-17 22:41:04.244866951  [2024-08-17 22:41:04] peewee_migrate.logs            INFO    : Starting migrations
2024-08-17 22:41:04.244938022  [2024-08-17 22:41:04] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-17 22:41:04.261457582  [2024-08-17 22:41:04] frigate.app                    INFO    : Recording process started: 698
2024-08-17 22:41:04.270711772  [2024-08-17 22:41:04] frigate.app                    INFO    : Recording process started: 706
2024-08-17 22:41:04.273056185  [2024-08-17 22:41:04] frigate.app                    INFO    : go2rtc process pid: 98
2024-08-17 22:41:04.311864067  [2024-08-17 22:41:04] detector.coral                 INFO    : Starting detection process: 727
2024-08-17 22:41:04.319485069  [2024-08-17 22:41:04] frigate.app                    INFO    : Output process started: 731
2024-08-17 22:41:04.326154735  [2024-08-17 22:41:04] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-08-17 22:41:04.326649568  [2024-08-17 22:41:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-08-17 22:41:04.342367644  [2024-08-17 22:41:04] frigate.app                    INFO    : Camera processor started for Backyard_1: 756
2024-08-17 22:41:04.352529589  [2024-08-17 22:41:04] frigate.app                    INFO    : Camera processor started for Dummy_sub: 762
2024-08-17 22:41:04.363419309  [2024-08-17 22:41:04] frigate.app                    INFO    : Camera processor started for Backyard_2: 767
2024-08-17 22:41:04.373109242  [2024-08-17 22:41:04] frigate.app                    INFO    : Capture process started for Backyard_1: 773
2024-08-17 22:41:04.385489419  [2024-08-17 22:41:04] frigate.app                    INFO    : Capture process started for Dummy_sub: 783
2024-08-17 22:41:04.401062334  [2024-08-17 22:41:04] frigate.app                    INFO    : Capture process started for Backyard_2: 787


go2rtc logs:

Info
2024-08-17 22:40:44
startup
Preparing new go2rtc config...
Info
2024-08-17 22:40:44
startup
Starting go2rtc...
Info
2024-08-17 22:40:44
startup
go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
Info
2024-08-17 22:40:44
startup
config path=/dev/shm/go2rtc.yaml
Info
2024-08-17 22:40:44
api
listen addr=:1984
Info
2024-08-17 22:40:44
rtsp
listen addr=:8554
Info
2024-08-17 22:40:44
webrtc
listen addr=:8555/tcp
Info
2024-08-17 22:40:54
startup
Starting go2rtc healthcheck service...


Browser logs:

No errors in console or network tab.
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

Coral

**Comment by hawkeye217** [comment]
Are these Reolink cameras? If so, you should use the recommended Reolink config: https://docs.frigate.video/configuration/camera_specific/#reolink-cameras

Also, you would benefit from using go2rtc for your live views: https://docs.frigate.video/configuration/live

From the docs:

> For the best experience, you should set the stream name under go2rtc to match the name of your camera so that Frigate will automatically map it and be able to use better live view options for the camera.

**Comment by 2d65** [comment]
These are indeed Reolink cameras.  I don't think this is related to the camera config per say since all the streams show up fine in the go2rtc dashboard (all main and sub feeds).  But hey.. maybe I'm missing something.

The issue seems to reside in Frigate and is limited to the preview in live view.  No matter what I do, one of the cameras will display black and not the feed.  Which one displays the feed seems to be determined at startup.  Clicking on the "black/no feed"  camera will work and bring up the main feed as expected in full view. 

Also tested using WebRTC with the same result.  I even tried to map the main feed to sub but again only one camera shows up in live view.  Not sure if this is a bug or something in my config..

**Reply by hawkeye217** [reply]
What is your current frigate config?

**Reply by 2d65** [reply]
Latest config below. I tried several things in an attempt to alter the behavior but the issue remains..


```yaml
mqtt:
  # Required: host name
  host: 192.168.10.2
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  # Optional: user
  user: [<redacted>](url)
  password: <redacted>
  stats_interval: 60

ffmpeg:  
  output_args:
    record: preset-record-generic-audio
#   global_args: -hide_banner -loglevel warning
#   hwaccel_args: preset-intel-vaapi

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug


go2rtc:
  log:
    exec: trace
  # ffmpeg:
  #   preset-http-reolink: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i {input}"
  streams:
    Backyard1:
    - rtsp://<redacted>:<redacted>@10.0.5.17:554/h264Preview_01_main
    - ffmpeg:Backyard_1#audio=aac#audio=opus
    #- ffmpeg:http://10.0.5.17/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<redacted>&password=<redacted>#video=copy#audio=copy#audio=opus" 
    Backyard1_sub:
    #- ffmpeg:Backyard_1#video=h264#width=1920#height=1080#audio=aac#raw=-fpsmax 7#hardware=vaapi
    - rtsp://<redacted>:<redacted>@10.0.5.17:554/h264Preview_01_sub
    #- ffmpeg:http://10.0.5.17/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<redacted>&password=<redacted>#video=copy#audio=copy" 
    
    Xyz:
    - rtsp://<redacted>:<redacted>@10.0.5.16:554/h264Preview_01_main
    - ffmpeg:Backyard_1#audio=aac#audio=opus
    #- ffmpeg:http://10.0.5.16/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<redacted>&password=<redacted>#video=copy#audio=copy" 
    Xyz_sub:
    #- ffmpeg:Backyard_2#video=h264#width=1920#height=1080#audio=aac#raw=-fpsmax 7#hardware=vaapi    
    - rtsp://<redacted>:<redacted>@10.0.5.16:554/h264Preview_01_sub
    #- ffmpeg:http://10.0.5.16/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<redacted>&password=<redacted>" 

  webrtc:
    candidates:
      - 192.168.10.2:8556
      - stun:8556
    listen: :8556

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci

cameras:
  Backyard1:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Backyard1_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
      - path: rtsp://127.0.0.1:8554/Backyard1
        input_args: preset-rtsp-restream
        roles:
          - record
      output_args:
        record:
        - preset-record-generic-audio-copy    
        
  Xyz:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Xyz_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
      - path: rtsp://127.0.0.1:8554/Xyz
        input_args: preset-rtsp-restream
        roles:
          - record
      output_args:
        record:
        - preset-record-generic-audio-copy   
                 
version: 0.14
```

**Reply by hawkeye217** [reply]
Try this go2rtc config:

```
go2rtc:
  streams:
    Backyard1:
    - "ffmpeg:http://10.0.5.17/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<redacted>&password=<redacted>#video=copy#audio=copy#audio=opus"
    Backyard1_sub:
    - "ffmpeg:http://10.0.5.17/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<redacted>&password=<redacted>"
    
    Xyz:
    - "ffmpeg:http://10.0.5.16/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<redacted>&password=<redacted>#video=copy#audio=copy#audio=opus" 
    Xyz_sub:
    - "ffmpeg:http://10.0.5.16/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<redacted>&password=<redacted>"
```

**Reply by 2d65** [reply]
Same behavior unfortunately.   The live view that's supposed to show all cameras only shows one feed.  The other feed remains black.
I can click on the black feed as before and the bigger view which will render correctly.  Which is feed is visible in the multi camera view seems to be random and it will stay the same until I restart the container.    It's not related to motion as I tested that as well.

Not sure if this helps but I also noticed the following as I'm digging a bit deeper in the code and docs:

1) Currently the Xyz feed is black in the main live view (which should list both cameras).  Using the API and browsing to `http://192.168.10.2:5000/api/Xyz` also shows a black screen as well.   Browsing to `http://192.168.10.2:5000/api/Backyard1` displays the correct feed as expected.  A restart of the container can/will change this order around.

All feeds show up properly in the go2rtc dashboard including `http://192.168.10.2:1984/stream.html?src=Xyz` and `http://192.168.10.2:1984/stream.html?src=Xyz_sub` whereas `http://192.168.10.2:5000/api/Xyz` in Frigate does not.

2) Probably a side effect but in the main live view with all cameras, the video tag in the source HTML is missing the `blob:http://192.168.10.2..`" attribute.  The working one has this tag.

**Reply by hawkeye217** [reply]
Are either of your Reolink cams 8MP cameras?

**Reply by 2d65** [reply]
Both these cameras are older RLC410 5MP versions with the latest FW.

**Reply by hawkeye217** [reply]
We've not had any other reports of anything like this. Can you send a screenshot of what you're seeing? Also, what is your OS and browser version?

**Reply by 2d65** [reply]
Yeah I haven't seen it either in reports etc.  and  I've been looking for 2-3 days.  This setup used to work previously before I updated to 0.14.  It's been rock solid for a few years.  I wish I wrote down the previous version.

OS: Unraid, running ghcr.io/blakeblackshear/frigate:stable
Browser: Tested with Chrome Version 127.0.6533.120 , Latest Opera and Edge and Android Chrome.  All exhibit the same problem.

Black feed  (Xyz) is highlighted in red. Backyard1 is the one that's visible. Clicking on the black/Xyz feed will render the feed accordingly in full resolution.  If I do a couple of container restarts, the order will change.
![image_2024-08-20_172651140](https://github.com/user-attachments/assets/7ec0db25-480e-483a-8f98-f3c28d42434b)
![image](https://github.com/user-attachments/assets/34b22ff2-55cd-408a-871c-3eabb634be47)

**Reply by hawkeye217** [reply]
Can you run ffprobe from inside the container on the streams:

`ffprobe rtsp://127.0.0.1:8554/Backyard1`
`ffprobe rtsp://127.0.0.1:8554/Xyz`

**Reply by hawkeye217** [reply]
Also, can you try changing the names of the cameras in your camera config temporarily (*not* in your go2rtc config, only your camera config)? In the config below, I added `TEST` to the two places that need to change.

```
cameras:
  TESTBackyard1:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Backyard1_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
      - path: rtsp://127.0.0.1:8554/Backyard1
        input_args: preset-rtsp-restream
        roles:
          - record
      output_args:
        record:
        - preset-record-generic-audio-copy    
        
  TESTXyz:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Xyz_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
      - path: rtsp://127.0.0.1:8554/Xyz
        input_args: preset-rtsp-restream
        roles:
          - record
      output_args:
        record:
        - preset-record-generic-audio-copy   
                 
version: 0.14
```
```
