### DISCUSSION TITLE
[Config Support]: Recording Required Zones

### DISCUSSION THREAD

**Discussion by AriaGen** [blakeblackshear/frigate#13169] [Config Support]
### Describe the problem you are having

Since updateing to 0.14. The option for setting what zones were allowed to record seems to have gone, The YAML entry was automatically removed when I updated it but it seems to have stuck with the original settings I had set. I would now, like to change it so I get the clips for everything again, which is what I would expect to happen if the option has been removed.
Adding it back into my config.yml throws a config error and I can't find it within the new UI.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://**@**/Streaming/Channels/102/
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - umbrella
        - bicycle
      #  - car
      filters:
        person:
          min_area: 100
          max_area: 300000
          threshold: 0.65
        umbrella:
          min_area: 5000
          max_area: 400000
          threshold: 0.65
        bicycle:
          min_area: 5000
          max_area: 400000
          threshold: 0.65
        car:
          min_area: 2000
          max_area: 500000
          threshold: 0.50
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
        objects:
          - person
          - umbrella
          - bicycle
  #        - car
  ##    ORIGINALLY HAD THIS NEXT SECTION HERE::: ###
        required_zones:
          - driveway_zone
          - caverswall_zone
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

Coral

### Any other information that may be helpful

Admittitly, I might just be missing where the option is now.

**Comment by NickM-27** [comment]
The required zones are taken from the review section now

**Reply by AriaGen** [reply]
I appreciate, that might be what is suppose to control it. However, this doesn't seem to be the case. I have my driveway zone as alerts. All my other zones are defections. These zones I originally defined to record are still recording. The other zones leave a snapshot but say no preview found when I try and load the clip.

**Reply by NickM-27** [reply]
We'd need to see your full config

**Reply by AriaGen** [reply]
```yaml
# yaml-language-server: $schema=http://192.168.1.250:5000/api/config/schema.json

detectors:
  coral:
    type: edgetpu
    device: pci

mqtt:
  enabled: true
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: ***
  stats_interval: 30

auth:
  enabled: True
  reset_admin_password: False

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 15
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 8
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 150
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 15
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 150

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 3
    # Optional: Per object retention days
    objects:
      person: 3
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:s**3@192.168.1.5:554/Streaming/Channels/102/
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - umbrella
        - bicycle
      #  - car
      filters:
        person:
          min_area: 100
          max_area: 300000
          threshold: 0.65
        umbrella:
          min_area: 5000
          max_area: 400000
          threshold: 0.65
        bicycle:
          min_area: 5000
          max_area: 400000
          threshold: 0.65
        car:
          min_area: 2000
          max_area: 500000
          threshold: 0.50
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
        objects:
          - person
          - umbrella
          - bicycle
  #        - car
    snapshots:
      required_zones:
        - driveway_zone
        - caverswall_zone
        - caverswall_ext_zone
        - edenhurst_zone
    zones:
      driveway_zone:
        coordinates: 
          0.186,1,0.98,1,0.884,0.853,0.747,0.783,0.781,0.466,0.571,0.434,0.566,0.535,0.119,0.739
         #coordinates: 238,720,1254,720,1179,442,1126,418,834,376,152,532
        objects: person
        inertia: 3
        loitering_time: 0
      door_zone:
        coordinates: 1210,341,1086,315,1023,582,1136,629
         #coordinates: 238,720,1254,720,1179,442,1126,418,834,376,152,532
        objects:
          - person
           #- car
      caverswall_zone:
        coordinates: 166,460,677,360,698,297,802,283,802,219,147,348
        objects:
          - person
          - bicycle
        #   - car
      caverswall_ext_zone:
        coordinates: 0.819,0.292,0.825,0.354,0.631,0.384,0.632,0.289
        objects:
          - person
          - bicycle
        inertia: 3
        loitering_time: 0
      edenhurst_zone:
        coordinates: 125,180,570,171,671,230,115,297
        objects:
          - person
          - bicycle
        #   - car
    motion:
      mask:
        - 0,0,0,72,1280,72,1280,0
        #- 751,385,865,441,936,364,829,331
    audio:
  # Optional: Enable audio events (default: shown below)
      enabled: true
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  #   max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #    - 200 - high sensitivity
  #    - 500 - medium sensitivity
  #    - 1000 - low sensitivity
  #   min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
      listen:
      #  - bark
      #  - fire_alarm
        - scream
        - speech
        - yell
        - car_alarm
        - alarm
        - siren
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 720
    birdseye:
      order: 1

    review:
      alerts:
        required_zones: driveway_zone
  carport:
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://user:s***@192.168.1.5:554/Streaming/Channels/201/
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 1000
          max_area: 500000
          threshold: 0.65
        cat:
          min_area: 100
          max_area: 25000
          threshold: 0.65
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
        objects:
          - person
          - cat
    snapshots:
      required_zones:
        - carport_zone
    zones:
      carport_zone:
        coordinates: 877,720,985,106,730,70,0,636,0,720
        objects:
          - person
          - cat
    motion:
      mask: 0,0.928,0,0.997,1,1,1,0.928
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 720
    birdseye:
      order: 3

    review:
      alerts:
        required_zones:
          - carport_zone
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://user:s***@192.168.1.5:554/Streaming/Channels/302/
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 300
          max_area: 50000
          threshold: 0.70
          mask:
            - 231,452,319,458,319,336,232,337
            - 582,331,628,379,589,536,356,484,405,374
            - 664,64,676,155,585,155,583,99,627,103,638,75
        cat:
          min_area: 100
          max_area: 500
          threshold: 0.65
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
        objects:
          - person
  #        - car
    snapshots:
      required_zones:
        - garden_zone
        - garden_right_zone
        - garden_left_zone
    zones:
      garden_zone:
        coordinates: 1280,720,654,112,514,95,441,108,490,720
        objects:
          - person
      garden_left_zone:
        coordinates: 399,121,223,139,51,457,0,568,43,648,45,720,254,720
        objects:
          - person
      garden_right_zone:
        coordinates: 1110,465,1246,445,1173,393,1196,310,1060,203,1042,260,924,243
        objects:
          - person
    motion:
      mask:
        - 0,0,0,76,427,72,413,0
    audio:
  # Optional: Enable audio events (default: shown below)
      enabled: true
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  #   max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #    - 200 - high sensitivity
  #    - 500 - medium sensitivity
  #    - 1000 - low sensitivity
  #   min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
      listen:
      #  - bark
      #  - fire_alarm
        - scream
      #  - speech
        - yell
      #  - car_alarm
        - alarm
      #  - siren
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 720
    birdseye:
      order: 4


    review:
      alerts:
        required_zones: garden_zone
birdseye:
  enabled: false
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: continuous
  layout:
    max_cameras: 4

telemetry:
  version_check: true
version: 0.14
```

**Reply by NickM-27** [reply]
You have only defined one zone as required. You'd need to make the other zones required for detections for them to be included in the events based recording

**Reply by AriaGen** [reply]
Sorry that hasn't pasted well. I'm on my phone and its difficult.

Please can you point out the exact part? Its obviously different to my original config before the update and I've clearly just missed where it is now. But it's late and I can't see it. Thanks.

**Reply by NickM-27** [reply]
For example 

```
    review:
      alerts:
        required_zones: 
          - garden_zone
      detections:
        required_zones:
          - garden_right_zone
          - garden_left_zone
```

**Reply by AriaGen** [reply]
Thank you, I just needed clarification as it wasn't clear. 
I had throught that this was just to define, wether they appear as alerts or detections. 
It's odd, that for example with my driveway camera I have 4 zones:
- driveway_zone - Views as alert, that records
- caverswall_zone - Views as Detectioin, that records
- caverswall_ext_zone - Views as Detection, that doesn't record, snapshot only
- edenhurst_zone - Views as Detection, that doesn't record, snapshot only
I will, change my config to this for my driveway and see if it performs any differently:

```
    review:
      alerts:
        required_zones: driveway_zone
      detections:
        required_zones:
          - caverswall_ext_zone
          - caverswall_zone
          - door_zone
          - edenhurst_zone
```
