### DISCUSSION TITLE
[Config Support]: what am I doing wrong here?

### DISCUSSION THREAD

**Discussion by Ayuus** [blakeblackshear/frigate#13165] [Config Support] [answered]
### Describe the problem you are having

Refer to attached image
![snapshot](https://github.com/user-attachments/assets/34921af1-5b95-40c0-8943-a23f63a50b3b), obviously a false positive, but why?
In my config, person threshold is 0.7, in image 0.61. Whatam I missing?

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.10 #homeassistant.local
  port: 1883
#  port: 8883
#  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: false
  user: homeassistant
  password: zz

ui:
  time_format: 24hour

logger:
  default: info
#  logs:
#    frigate.ptz.onvif: debug

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.6
      threshold: 0.7
    cat:
      min_score: 0.6
      threshold: 0.7
    dog:
      min_score: 0.6
      threshold: 0.7

detect:
  max_disappeared: 5

#motion:
#   lightning_threshold: 0.9

birdseye:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

audio:
  # geen audio events, events zijn wel inclusief audio
  enabled: false
  min_volume: 500
  listen:
    - speech
    - yell
    - scream
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event
      threshold: 0.8
    yell:
      threshold: 0.8
    scream:
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

go2rtc:
  streams:
    buitencamera_zijgevel:
      - rtsp://admin:zz@192.168.4.40:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps
    buitencamera_achterzijde:
      - rtsp://admin:zz@192.168.4.41:554/cam/realmonitor?channel=1&subtype=2 #720p/25fps
    buitencamera_voordeur:
      - rtsp://admin:zz@192.168.4.42:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps

cameras:
  buitencamera_voordeur:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:zz@192.168.4.42:554/cam/realmonitor?channel=1&subtype=2   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://admin:zz@192.168.4.42:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record

  buitencamera_zijgevel:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:z@192.168.4.40:554/cam/realmonitor?channel=1&subtype=2     #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://admin:zz@192.168.4.40:554/cam/realmonitor?channel=1&subtype=0     #4MP25fps
          roles:
            - record
    motion:
      mask: 0.643,0.358,0.843,1,1,1,1,0,0.678,0,0.378,0,0.385,0.371
    zones:
      grind:
        coordinates: 505,266,912,250,1148,720,509,720
    review:
      alerts:
        required_zones:
          - grind
    snapshots:
      required_zones:
        - grind
  buitencamera_achterzijde:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:zz@192.168.4.41:554/cam/realmonitor?channel=1&subtype=1   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://admin:zz@192.168.4.41:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record

version: 0.14
```

### Relevant log output

```shell
None
```

### Frigate stats

```json
{
    "cameras": {
        "buitencamera_achterzijde": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 433,
            "detection_enabled": true,
            "detection_fps": 5.4,
            "ffmpeg_pid": 442,
            "pid": 426,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "buitencamera_voordeur": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 427,
            "detection_enabled": true,
            "detection_fps": 3.4,
            "ffmpeg_pid": 440,
            "pid": 424,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "buitencamera_zijgevel": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 430,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 443,
            "pid": 425,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "18": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "46": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "85": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "86": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "87": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "93": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "99": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "124": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "126": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "2.2",
            "cpu_average": "2",
            "mem": "5.3"
        },
        "132": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "160": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "161": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "162": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "163": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "164": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "297": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "347": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "369": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "1.5"
        },
        "370": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "398": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "399": {
            "cmdline": "frigate.detector.coral",
            "cpu": "5.2",
            "cpu_average": "6",
            "mem": "0.7"
        },
        "401": {
            "cmdline": "frigate.output       ",
            "cpu": "4.0",
            "cpu_average": "4",
            "mem": "1.2"
        },
        "424": {
            "cmdline": "frigate.process:buitencamera_voordeur",
            "cpu": "2.3",
            "cpu_average": "2",
            "mem": "1.4"
        },
        "425": {
            "cmdline": "frigate.process:buitencamera_zijgevel",
            "cpu": "1.6",
            "cpu_average": "1",
            "mem": "1.3"
        },
        "426": {
            "cmdline": "frigate.process:buitencamera_achterzijde",
            "cpu": "4.1",
            "cpu_average": "4",
            "mem": "1.1"
        },
        "427": {
            "cmdline": "frigate.capture:buitencamera_voordeur",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.7"
        },
        "430": {
            "cmdline": "frigate.capture:buitencamera_zijgevel",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.7"
        },
        "433": {
            "cmdline": "frigate.capture:buitencamera_achterzijde",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "440": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.4.42:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.4",
            "cpu_average": "2",
            "mem": "0.8"
        },
        "442": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.4.41:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale_vaapi=w=1024:h=452:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.7",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "443": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.4.40:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "2.4",
            "cpu_average": "2",
            "mem": "0.7"
        },
        "450": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.4.41:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/buitencamera_achterzijde@%Y%m%d%H%M%S%z.mp4",
            "cpu": "2.1",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "451": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.4.40:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/buitencamera_zijgevel@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.7",
            "cpu_average": "1",
            "mem": "0.2"
        },
        "452": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.4.42:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/buitencamera_voordeur@%Y%m%d%H%M%S%z.mp4",
            "cpu": "1.3",
            "cpu_average": "1",
            "mem": "0.2"
        },
        "524": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "529": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "534": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1024x452 -i pipe: -threads 1 -f mpegts -s 1631x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "4584": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "18442": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "18536": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "frigate.full_system": {
            "cpu": "10.0",
            "mem": "57.8"
        }
    },
    "detection_fps": 8.8,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 9.04,
            "pid": 399
        }
    },
    "gpu_usages": {
        "error-gpu": {
            "gpu": "",
            "mem": ""
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 99
        },
        "logger": {
            "pid": 347
        },
        "recording": {
            "pid": 369
        },
        "review_segment": {
            "pid": 370
        }
    },
    "service": {
        "last_updated": 1724000754,
        "latest_version": "0.14.0",
        "storage": {
            "/dev/shm": {
                "free": 250.8,
                "mount_type": "tmpfs",
                "total": 256,
                "used": 5.2
            },
            "/media/frigate/clips": {
                "free": 896950,
                "mount_type": "btrfs",
                "total": 3651993.6,
                "used": 2755043.6
            },
            "/media/frigate/recordings": {
                "free": 896950,
                "mount_type": "btrfs",
                "total": 3651993.6,
                "used": 2755043.6
            },
            "/tmp/cache": {
                "free": 933.6,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 20.1
            }
        },
        "temperatures": {},
        "uptime": 62260,
        "version": "0.14.0-da913d8"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

I also tried without the min_score, same kind of false positives (cats seen as persons, with score < threshold).
