### DISCUSSION TITLE
[Detector Support]: Detection appears to be stuck. Restarting detection process

### DISCUSSION THREAD

**Discussion by will-riley** [blakeblackshear/frigate#13167] [Detector Support]
### Describe the problem you are having

Log Info: "Detection appears to be stuck. Restarting detection process"

USB 3 speeds appear to be working. Cables and ports have been swapped around. No change.
HassOS add-on, on proxmox 8.2.4.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
birdseye:
  enabled: true
  restream: true
  quality: 4
  height: 1080
  width: 1920
  mode: continuous

mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  user: ***
  password: ***
  topic_prefix: frigate
  client_id: frigate

database:
  path: /config/frigate.db

detectors:
  coral_1:
    type: edgetpu
    device: usb:0
  coral_2:
    type: edgetpu
    device: usb:1

go2rtc:
  streams:
    gate:
      - rtsp://***@192.168.2.5:554/cam/realmonitor?channel=1&subtype=1
    north:
      - rtsp://***@192.168.2.7:554/cam/realmonitor?channel=1&subtype=0
    south:
      - rtsp://***@192.168.2.6:554/cam/realmonitor?channel=1&subtype=1
    west:
      - rtsp://***@192.168.2.8:554/cam/realmonitor?channel=1&subtype=1
    garage:
      - rtsp://***@192.168.2.9:554/cam/realmonitor?channel=1&subtype=1
    aux1:
      - rtsp://***@192.168.2.12:554/cam/realmonitor?channel=1&subtype=1
    front:
      - rtsp://***@192.168.2.11:554/cam/realmonitor?channel=1&subtype=1

motion:
  threshold: 20
  contour_area: 30
  lightning_threshold: 0.8
  improve_contrast: true
  frame_alpha: 0.01
  frame_height: 100
  mqtt_off_delay: 10

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 4
    mode: motion
  events:
    pre_capture: 2
    retain:
      default: 6
      mode: motion

timestamp_style:
  position: tr
  effect: solid

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  crop: true
  retain:
    default: 20
    objects:
      person: 30

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-vaapi

detect:
  fps: 6
  width: 704
  height: 480

objects:
  track:
    - car
    - person
    - dog
    - cat
    - bird
    - motorcycle
    - fedex
    - ups
    - amazon
    - truck

audio:
  enabled: true
  min_volume: 200
  max_not_heard: 20
  listen:
    - bark
    - babbling
    - laughter
    - fire_alarm
    - scream
    - speech
    - yell
    - whoop
    - singing
    - footsteps
    - owl
    - music
    - rain
    - wind
    - car
    - honk
    - motorcycle
    - aircraft
    - slam
    - squeak
    - gunshot
    - explosion

cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 20
      contour_area: 33
      improve_contrast: false
      mask:
        - 1,0,1,0.235,0.294,0.279,0.264,0.366,0.197,0.37,0.164,0.292,0,0.296,0,0
        - 0.229,1,0.713,1,0.565,0.485,0.48,0.519
        - 0.659,0.753,0.798,0.766,0.814,0.953,0.785,0.996,0.657,0.995
    detect:
      width: 704
      height: 480
    record:
      enabled: true
    snapshots:
      required_zones:
        - street_left
        - street_right
        - wide_area
    webui_url: http://192.168.2.11/
    zones:
      street_left:
        coordinates: 168,223,179,151,25,159,22,228
        inertia: 3
        objects:
          - car
          - motorcycle
          - amazon
          - fedex
          - ups
          - person
      street_right:
        coordinates: 395,220,503,227,488,139,386,135
        inertia: 3
        objects:
          - car
          - motorcycle
          - truck
          - amazon
          - fedex
          - ups
          - person
      wide_area:
        coordinates: 0,403,704,480,704,138,0,157
        inertia: 3
        objects:
          - person
          - cat
          - dog

    review:
      alerts:
        required_zones:
          - street_left
          - street_right
          - wide_area
  gate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.5:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.5:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 14
      contour_area: 31
      mask:
        - 0,480,0,0,704,0,704,147,442,232,383,255,304,253,314,325,376,480
    detect:
      width: 704
      height: 480
    record:
      enabled: true
    webui_url: http://192.168.2.5/

  north:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.7:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.7:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 13
      contour_area: 10
      mask:
        - 0,203,0,314,0,480,113,480,282,132,315,57,325,0
        - 439,43,475,64,528,64,600,64,704,60,704,0,366,0
    detect:
      width: 704
      height: 480
    record:
      enabled: true
    webui_url: http://192.168.2.7/

  south:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.6:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.6:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 15
      contour_area: 30
      improve_contrast: false
      mask:
        - 522,480,704,480,704,449,522,454
        - 704,0,704,132,704,0,704,236,704,304,704,480,484,480,527,314,558,0
        - 290,125,527,36,558,0,0,0,0,209
    detect:
      width: 704
      height: 480
    record:
      enabled: true
    webui_url: http://192.168.2.6/

  west:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.8:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.8:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 13
      contour_area: 10
      mask:
        - 153,51,184,0,0,0,0,114
        - 704,0,704,128,418,0
    detect:
      width: 704
      height: 480
    record:
      enabled: true
    webui_url: http://192.168.2.8/

  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.9:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.9:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 13
      contour_area: 33
      improve_contrast: false
      mask:
        - 477,23,704,21,704,0,477,0
    detect:
      width: 704
      height: 480
    record:
      enabled: true
      events:
        objects:
          - person
          - dog
          - cat
    webui_url: http://192.168.2.9/

  aux1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://***@192.168.2.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - record
    motion:
      threshold: 13
      contour_area: 30
      improve_contrast: false
      mask:
        - 523,98,611,98,704,88,704,63,522,64
    detect:
      width: 704
      height: 480
    record:
      enabled: true
      events:
        objects:
          - person
          - dog
          - cat
    webui_url: http://192.168.2.12/

telemetry:
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: false
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: true
version: 0.14
camera_groups:
  Main:
    order: 1
    icon: LuBookmark
    cameras:
      - front
      - gate
      - north
      - west
      - south
      - aux1
  Bird:
    order: 2
    icon: LuBird
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
none used
```

### Relevant log output

```shell
info
2024-08-18 09:38:17
frigate.detectors.plugins.edgetpu_tfl
Attempting to load TPU as usb:1
info
2024-08-18 09:38:20
frigate.detectors.plugins.edgetpu_tfl
TPU found
info
2024-08-18 12:10:17
frigate.watchdog
Detection appears to be stuck. Restarting detection process...
info
2024-08-18 12:10:17
root
Waiting for detection process to exit gracefully...
info
2024-08-18 12:10:47
root
Detection process didn't exit. Force killing...
info
2024-08-18 12:10:47
root
Detection process has exited...
info
2024-08-18 12:10:47
detector.coral_2
Starting detection process: 2251533
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Object Detector

Coral

### Any other information that may be helpful

```
root@pmox1:~# lsusb
Bus 002 Device 005: ID 18d1:9302 Google Inc. 
Bus 002 Device 003: ID 0bda:0411 Realtek Semiconductor Corp. Hub
Bus 002 Device 002: ID 18d1:9302 Google Inc. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 001 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

```
root@pmox1:~# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/10p, 10000M
    |__ Port 3: Dev 2, If 0, Class=Vendor Specific Class, Driver=usbfs, 5000M
    |__ Port 7: Dev 3, If 0, Class=Hub, Driver=hub/4p, 5000M
        |__ Port 1: Dev 5, If 0, Class=Vendor Specific Class, Driver=usbfs, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/16p, 480M
    |__ Port 7: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
    |__ Port 9: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 12M

```
