### DISCUSSION TITLE
Trying to reduce CPU usage

### DISCUSSION THREAD

**Discussion by jobby889** [blakeblackshear/frigate#13166] [Config Support] [answered]
### Describe the problem you are having

Coral is being used, Nvidia video Hardware Acceleration is in use, three cameras are configured using low res stream for detection (two cameras are tplink Tapo C310 and are fixed at 15 fps, one camera is generic IPCam that is blocked from Web access and is 10 fps), I understand CPU is used for detecting motion and then offloading to Coral for actual Object detection, I have set quite large motion mask areas, where trees, plants etc trigger motion.  but CPU usage is still to great (peaking at around 150% per camera, with idle about 25% per camera), xeoma utilisation with same camera's and masks is a total of 25% for all camera's, I clearly think I have something wrong, or is this an expected CPU utilisation for frigate, is there something else I can tune, as I much prefer Frigate to xeoma!

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral_pci:
    type: edgetpu
    device: pci

record:
  enabled: true
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

birdseye:
  enabled: false
  mode: continuous

ffmpeg:
  hwaccel_args: preset-nvidia-h264
#ffmpeg:
#  hwaccel_args: preset-vaapi

objects:
  track:
  - person
  - face
  - dog
  - cat
  - package
  - bird
  - bicycle

cameras:
  Back_Door: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://<Retracted>:<Retracted>@192.168.1.232/stream2   #<----- Low res
        roles:
        - detect
      - path: rtsp://<Retracted>:<Retracted>@192.168.1.232/stream1   #<----- High Res
        roles:
        - record  
    detect:
      enabled: true 
      width: 640
      height: 360
      fps: 15
    motion:
      mask:
      - 340,61,325,101,260,129,236,96,228,51,284,0
      - 0,288,62,269,52,242,52,200,112,155,105,117,0,174
      - 0,155,107,113,114,43,0,69
      - 111,165,171,157,175,84,124,67,93,81
  Shed: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://<Retracted>:<Retracted>@192.168.1.231/stream2   #<----- Low Res
        roles:
        - detect    
      - path: rtsp://<Retracted>:<Retracted>@192.168.1.231/stream1   #<----- High Res
        roles:
        - record  
      #  - detect
    detect:
      enabled: true 
      width: 640
      height: 360
      fps: 15
    motion:
      mask:
        - 264,73,321,166,331,167,347,70,314,66
  Josie:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://<Retracted>:<Retracted>@192.168.1.35:554/12 
        roles:
          - detect          
      - path: rtsp://<Retracted>:<Retracted>@192.168.1.35:554/11 
        roles:
          - record 
    detect:
      enabled: true 
      width: 640
      height: 352
      fps: 10
    motion:
      mask:    
      - 465,123,640,266,640,172,496,55    
      - 277,167,243,154,284,58,313,70
      - 268,55,208,150,166,138,135,111,151,57
      - 432,145,459,99,521,129,477,180
      - 486,0,373,0,373,21,470,56              
environment_vars:
  PLUS_API_KEY: <Retracted>
```

### Relevant log output

```shell
2024-08-18 17:00:22.707292295  [INFO] Preparing Frigate...
2024-08-18 17:00:22.722162016  [INFO] Starting Frigate...
2024-08-18 17:00:23.681080551  [2024-08-18 17:00:23] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-08-18 17:00:23.716601070  [2024-08-18 17:00:23] peewee_migrate.logs            INFO    : Starting migrations
2024-08-18 17:00:23.723494044  [2024-08-18 17:00:23] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-18 17:00:23.723571017  [2024-08-18 17:00:23] frigate.app                    INFO    : Recording process started: 441
2024-08-18 17:00:23.725454025  [2024-08-18 17:00:23] frigate.app                    INFO    : go2rtc process pid: 89
2024-08-18 17:00:23.741386119  [2024-08-18 17:00:23] detector.coral_pci             INFO    : Starting detection process: 450
2024-08-18 17:00:23.765724556  [2024-08-18 17:00:23] frigate.app                    INFO    : Output process started: 452
2024-08-18 17:00:23.765821904  [2024-08-18 17:00:23] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-08-18 17:00:23.771210997  [2024-08-18 17:00:23] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-08-18 17:00:23.778349198  [2024-08-18 17:00:23] frigate.app                    INFO    : Camera processor started for Back_Door: 472
2024-08-18 17:00:23.782427865  [2024-08-18 17:00:23] frigate.app                    INFO    : Camera processor started for Shed: 480
2024-08-18 17:00:23.786572917  [2024-08-18 17:00:23] frigate.app                    INFO    : Camera processor started for Josie: 482
2024-08-18 17:00:23.790857747  [2024-08-18 17:00:23] frigate.app                    INFO    : Capture process started for Back_Door: 484
2024-08-18 17:00:23.795222880  [2024-08-18 17:00:23] frigate.app                    INFO    : Capture process started for Shed: 488
2024-08-18 17:00:23.799731577  [2024-08-18 17:00:23] frigate.app                    INFO    : Capture process started for Josie: 492
```

### Frigate stats

```json
cameras	
Back_Door	
audio_dBFS	0
audio_rms	0
camera_fps	15
capture_pid	484
detection_enabled	1
detection_fps	4.5
ffmpeg_pid	489
pid	472
process_fps	15.1
skipped_fps	0
Josie	
audio_dBFS	0
audio_rms	0
camera_fps	10.3
capture_pid	492
detection_enabled	1
detection_fps	6.2
ffmpeg_pid	499
pid	482
process_fps	4
skipped_fps	6.3
Shed	
audio_dBFS	0
audio_rms	0
camera_fps	15.1
capture_pid	488
detection_enabled	1
detection_fps	0
ffmpeg_pid	494
pid	480
process_fps	15.1
skipped_fps	0
cpu_usages	
1	
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
15	
cmdline	"s6-supervise s6-linux-init-shutdownd"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
17	
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
24	
cmdline	"s6-supervise frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
25	
cmdline	"s6-supervise nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
26	
cmdline	"s6-supervise frigate-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
27	
cmdline	"s6-supervise go2rtc-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
28	
cmdline	"s6-supervise s6rc-oneshot-runner"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
29	
cmdline	"s6-supervise s6rc-fdholder"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
30	
cmdline	"s6-supervise go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
31	
cmdline	"s6-supervise go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
32	
cmdline	"s6-supervise nginx-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
41	
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
42	
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
80	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
81	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
82	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
89	
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
97	
cmdline	"bash ./run.user go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
98	
cmdline	"python3 -u -m frigate"
cpu	"5.5"
cpu_average	"6"
mem	"0.5"
111	
cmdline	"nginx: master process nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
145	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
146	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
147	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
148	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
154	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
166	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
185	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
281	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
310	
cmdline	"nginx: cache manager process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
439	
cmdline	"frigate.logger       "
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
441	
cmdline	"frigate.recording_manager"
cpu	"2.3"
cpu_average	"1"
mem	"0.2"
449	
cmdline	"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(46)"
cpu	"1.0"
cpu_average	"0"
mem	"0.0"
450	
cmdline	"frigate.detector.coral_pci"
cpu	"4.5"
cpu_average	"9"
mem	"0.2"
452	
cmdline	"frigate.output       "
cpu	"2.9"
cpu_average	"3"
mem	"0.2"
456	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
469	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
470	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
472	
cmdline	"frigate.process:Back_Door"
cpu	"38.8"
cpu_average	"49"
mem	"0.2"
480	
cmdline	"frigate.process:Shed "
cpu	"7.8"
cpu_average	"10"
mem	"0.2"
482	
cmdline	"frigate.process:Josie"
cpu	"19.1"
cpu_average	"62"
mem	"0.2"
484	
cmdline	"frigate.capture:Back_Door"
cpu	"3.7"
cpu_average	"3"
mem	"0.2"
488	
cmdline	"frigate.capture:Shed "
cpu	"3.5"
cpu_average	"3"
mem	"0.2"
489	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.232/stream2 -r 15 -vf fps=15,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"7.0"
cpu_average	"7"
mem	"0.2"
492	
cmdline	"frigate.capture:Josie"
cpu	"2.7"
cpu_average	"2"
mem	"0.2"
494	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.231/stream2 -r 15 -vf fps=15,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"7.0"
cpu_average	"7"
mem	"0.2"
499	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.35:554/12 -r 10 -vf fps=10,scale_cuda=w=640:h=352:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"2.7"
cpu_average	"3"
mem	"0.2"
501	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.232/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Back_Door@%Y%m%d%H%M%S%z.mp4"
cpu	"1.2"
cpu_average	"0"
mem	"0.0"
504	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.231/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Shed@%Y%m%d%H%M%S%z.mp4"
cpu	"1.2"
cpu_average	"0"
mem	"0.0"
506	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.35:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Josie@%Y%m%d%H%M%S%z.mp4"
cpu	"0.2"
cpu_average	"0"
mem	"0.0"
1869	
cmdline	"sleep 30s"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
detection_fps	10.7
detectors	
coral_pci	
detection_start	0
inference_speed	9.01
pid	450
gpu_usages	
NVIDIA GeForce GT 1030	
dec	"2.0%"
enc	"-1.0%"
gpu	"1.0%"
mem	"13.96%"
processes	
go2rtc	
pid	89
logger	
pid	439
recording	
pid	441
service	
last_updated	1724000799
latest_version	"0.14.0"
storage	
/dev/shm	
free	147.1
mount_type	"tmpfs"
total	150
used	2.9
/media/frigate/clips	
free	1637135.7
mount_type	"ext4"
total	1876685.3
used	144147.1
/media/frigate/recordings	
free	1637135.7
mount_type	"ext4"
total	1876685.3
used	144147.1
/tmp/cache	
free	952.9
mount_type	"tmpfs"
total	953.7
used	0.8
temperatures	
apex_0	43.8
uptime	376
version	"0.13.2-6476
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

Xeoma and Frigate running, showing CPU utilisation...

Tasks: 308 total,   2 running, 306 sleeping,   0 stopped,   0 zombie
%Cpu(s): 19.4 us, 12.7 sy,  0.0 ni, 67.0 id,  0.4 wa,  0.0 hi,  0.4 si,  0.0 st 
MiB Mem :  64240.9 total,  13229.4 free,   7366.8 used,  47613.9 buff/cache     
MiB Swap:   8192.0 total,   8191.5 free,      0.5 used.  56874.1 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                       
 301979 root      20   0 1642564 144108  17492 S  73.6   0.2   0:27.20 frigate.process                                               
 301969 root      20   0 1646304 147816  17628 S  60.1   0.2   0:37.49 frigate.process                                               
   1208 root      20   0   14.1g   1.7g 350248 S  30.7   2.7     27,07 xeoma                                                         
 301947 root      20   0 1318388 127328  20516 S  11.9   0.2   0:05.73 frigate.detecto                                               
 301977 root      20   0 1645836 146480  17164 R  10.6   0.2   0:10.80 frigate.process                                               
 301991 root      20   0 9577752 162792 137580 S   7.6   0.2   0:04.76 ffmpeg                                                        
 301938 root      20   0 1262148 131368  18084 S   7.3   0.2   0:01.42 frigate.recordi                                               
 301986 root      20   0 9577772 162632 137316 S   7.3   0.2   0:04.83 ffmpeg                                                        
 301595 root      20   0 3322292 292584  71808 S   6.3   0.4   0:06.62 python3                                                       
 301949 root      20   0 1470544 113504  11428 S   4.0   0.2   0:02.22 frigate.output                                                
 301985 root      20   0 1421988 132128   7640 S   4.0   0.2   0:02.31 frigate.capture                                               
 301981 root      20   0 1421988 131872   7384 S   3.6   0.2   0:02.31 frigate.capture                                               
 301996 root      20   0 9577656 162576 137216 S   3.6   0.2   0:02.38 ffmpeg                                                        
   3030 libvirt+  20   0   10.1g   3.2g   3.1g S   3.0   5.1 177:49.92 qemu-system-x86                                               
 301989 root      20   0 1421908 132000   7512 S   2.6   0.2   0:01.54 frigate.capture                                               
 301946 root      20   0   14256  10624   5376 S   1.3   0.0   0:00.71 python3                                                       
 301998 root      20   0  129552  21884  16512 S   1.3   0.0   0:00.73 ffmpeg                                                        
 302001 root      20   0  129308  21724  16512 S   1.3   0.0   0:00.78 ffmpeg                                                        
 302003 root      20   0  129668  22356  16640 S   1.3   0.0   0:00.74 ffmpeg  

nvidia-smi showing gpu accel in use
john@hal:/xeoma/frigate/config$ nvidia-smi
Sun Aug 18 17:02:46 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GT 1030         Off | 00000000:01:00.0 Off |                  N/A |
| 35%   40C    P0              N/A /  30W |    235MiB /  2048MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1208      C   /home/john/bin/Xeoma/xeoma                   69MiB |
|    0   N/A  N/A    301986      C   ffmpeg                                       55MiB |
|    0   N/A  N/A    301991      C   ffmpeg                                       55MiB |
|    0   N/A  N/A    301996      C   ffmpeg                                       53MiB |
+---------------------------------------------------------------------------------------+
