### DISCUSSION TITLE
[Config Support]: Camera is live and playing video in UI but frigate says no frames recieved

### DISCUSSION THREAD

**Discussion by sheminasalam** [blakeblackshear/frigate#13174] [Config Support] [answered]
### Describe the problem you are having

One of my cameras which was working without any issues till the latest update is now having a strange issue with frigate. I get the error in log as well as on UI that "no frames has been received" but when I check frigate UI, the camera video is playing without any issues. Can anybody take a look?
![image](https://github.com/user-attachments/assets/c702ae03-e0ef-4502-81d4-132693c81ecb)

### Steps to reproduce

just an issue with one camera

### Version

Current version: 0.14.0

### Frigate config file

```yaml
detectors:
  coral:
    type: cpu
mqtt:
  host: 1d
  port: d
  user: d
  password: d@d
  topic_prefix: d
ffmpeg:
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  hwaccel_args:
    - -c:v
    - h264
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
go2rtc:
  streams:
    bell_cam: # <- for RTSP streams
      - rtsp://ddd/user=dd.sdp # <- stream which supports video & aac audio
cameras:
  bell_cam:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://127.0.0.1:8554/bell_cam # <--- the name here must match the name
            of the camera in restream
#            rtsp://username:password@192.168.2.41:554/user=username_password=password_channel=1_stream=1.sdp
#            rtsp://username:password@192.168.1.40:554/cam/realmonitor?channel=10&subtype=1&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
            - restream
    detect:
      fps: 5
      height: 360
      width: 640
    motion:
      mask: 499,0,0,0,0,121,307,75,333,69,640,66,640,0
    best_image_timeout: 30
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 352
      retain:
        default: 30
    mqtt:
      timestamp: false
      crop: false
      height: 360
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 499,0,0,0,0,121,307,75,333,69,640,66,640,0
    record:
      enabled: true
      events:
        retain:
          default: 5
          mode: active_objects
  gate_cam:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://username:password@192.168.1.40:554/cam/realmonitor?channel=9&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    detect:
      height: 352
      width: 640
      fps: 5
    motion:
      mask:
        - 0,266,0,1,640,0,640,352,640,352,640,194,508,128,547,63,462,51
    best_image_timeout: 30
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 352
      retain:
        default: 30
    mqtt:
      timestamp: false
      crop: false
      height: 352
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          min_score: 0.3
          threshold: 0.6
#          mask:
#            - '0,309,0,1,640,0,640,352,564,352,618,199,549,194,601,113,548,108'
        car:
          min_score: 0.3
          threshold: 0.6
#          mask:
#            - '0,309,0,1,640,0,640,352,564,352,618,199,549,194,601,113,548,108'           

version: 0.14
#            - 0,113,81,27,94,0,0,0
#            - 259,63,256,0,352,0,352,288,205,288
```

### Relevant log output

```shell
2024-08-19 04:34:53.675011042  [2024-08-19 10:04:53] frigate.video                  ERROR   : bell_cam: Unable to read frames from ffmpeg process.
2024-08-19 04:34:53.675022912  [2024-08-19 10:04:53] frigate.video                  ERROR   : bell_cam: ffmpeg process is not running. exiting capture thread...
2024-08-19 04:35:03.387030927  [2024-08-19 10:05:03] watchdog.bell_cam              ERROR   : Ffmpeg process crashed unexpectedly for bell_cam.
2024-08-19 04:35:03.388111057  [2024-08-19 10:05:03] watchdog.bell_cam              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-08-19 04:35:03.388724603  [2024-08-19 10:05:03] ffmpeg.bell_cam.detect         ERROR   : rtsp://127.0.0.1:8554/bell_cam # <--- the name here must match the name of the camera in restream: Server returned 400 Bad Request
```

### Operating system

Debian

### Install method

HassOS Addon

### Network connection

Wireless

### Camera make and model

onvif

**Comment by hawkeye217** [comment, marked as answer]
The YAML in your config file is what's causing your problem. You've got a `>-` after the `-path: ` directive for `bell_cam`. This directs YAML to read the entire next block of text as a quoted string. 

Normally that's not an issue, but you have a `#` on the same line as your camera url, so that is being interpreted as part of the camera url, not as a comment.

So ffmpeg is interpreting your camera url incorrectly.

Here's what you need to change:

```
cameras:
  bell_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bell_cam 
```

Just remove the `>-` and move the url up to the `-path: ` line.
