### DISCUSSION TITLE
[Support]: No frames received from Camera in 20 seconds. Exiting ffmpeg...

### DISCUSSION THREAD

**Discussion by TopBanana123** [blakeblackshear/frigate#13172] [General Support]
### Describe the problem you are having

No frames received from Camera in 20 seconds. Exiting ffmpeg...
Waiting for ffmpeg to exit gracefully...
Camera: Unable to read frames from ffmpeg process.
Camera: ffmpeg process is not running. exiting capture thread...
Ffmpeg process crashed unexpectedly for Camera.
The following ffmpeg logs include the last 100 lines prior to exit.

____________________________________________________

But, I don't see 100 lines of logs!

Does anyone have this issue since upgrading to 0.14? Its only intermittent and might go for hours without issue, and then all of a suddenly have problems

System load is very low, Inference Speed is ~9ms, only 1 of 10 cameras have this issue. zero packet loss to camera, camera is PoE powered and connected via ethernet. Camera is in Blue Iris as well (As all cameras are) and has zero dropped frames. Camera is a Dahua T54IR-ZE-S3

I can't seem to see any other logs to check. Anyone got any ideas on how I can troubleshoot this?

Config for this camera, plus another that has zero issue. "Generator" has issues, the other does not: https://pastebin.com/QP28PikY

Is there any way to tell which steam ffmpeg is having issues with?

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.0.0.32
  user: mqtt-user@domain.com
  password: ergergergergerferg

cameras:
  Meadowcam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.25:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.25:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      threshold: 90
      mask:
        - 345,117,396,139,440,138,472,44,704,140,704,0,0,0,0,83,78,84,177,95,267,111
        - 704,369,660,374,632,303,704,262
        - 0,450,135,445,132,222,0,233,0,336
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    objects:
      filters:
        person:
          min_area: 400
          min_score: 0.7
          threshold: 0.75
          mask:
            - 704,0,0,0,0,80,242,86,361,95,444,132,462,44,704,29
            - 704,480,704,310,665,325,624,382,630,480
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Back_Yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.32:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.32:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 0,127,165,72,254,55,375,46,496,56,546,65,605,88,704,126,704,0,0,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    objects:
      filters:
        person:
          min_area: 510
          min_score: 0.7
          threshold: 0.8
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Front_Left: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.34:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.34:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          input_args: preset-rtsp-blue-iris
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 583,197,746,188,1280,249,1280,0,0,0,0,383,75,364,187,317,255,292,383,261,523,230
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    objects:
      filters:
        car:
          mask:
            - 421,131,147,224,0,233,0,0,295,0,1280,0,1280,256,961,204,752,169
        person:
          min_area: 15000
          min_score: 0.7
          threshold: 0.75
          mask:
            - 581,168,525,147,417,108,147,224,0,233,0,0,295,0,1280,0,1280,256,953,213,746,188
        motorcycle:
          min_area: 30000
          min_score: 0.7
          threshold: 0.75
          mask:
            - 421,131,147,224,0,233,0,0,295,0,1280,0,1280,256,961,204,752,169
      track:
        - person
        - car
        - motorcycle
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Front_Right: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.35:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.35:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 677,171,849,219,1108,313,1158,132,1280,147,1280,72,1280,0,0,0,0,292,117,249,215,222,342,187,442,166,560,162,629,161
    objects:
      filters:
        person:
          min_score: 0.7
          threshold: 0.8
          mask:
            - 1280,0,1280,162,1156,120,1112,322,832,219,710,189,583,158,530,155,358,183,107,246,0,275,0,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Driveway: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.21:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.21:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 0,72,480,60,480,0,0,0
    objects:
      filters:
        person:
          min_area: 9000
          min_score: 0.72
          threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  AC: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.22:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.22:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 0,0.044,0.761,0.037,0.77,0,0.112,0,0,0
        - 0.317,0.548,0.671,0.482,0.519,0.344,0.185,0.401
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    objects:
      filters:
        person:
          mask:
            - 480,0,480,179,233,53,85,0
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Generator: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.37:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.37:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      threshold: 90
      mask:
        - 0.625,0.053,1,0.529,1,0.364,1,0,0.625,0
        - 0.665,0.102,0.608,0.485,0.759,0.598,0.793,0.27
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    objects:
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          mask:
            - 974,595,1059,384,967,352,906,535
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Front_Door: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.26:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.26:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 0,116,480,119,480,0,0,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Back_Door: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.24:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.24:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for recording
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      threshold: 90
      mask:
        - 704,0,704,32,304,32,227,47,216,0
    objects:
      filters:
        person:
          min_area: 2000
          min_score: 0.7
          threshold: 0.75
    detect:
      enabled: true
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion
  Front-Path: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin1:poopoo@10.0.60.36:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin1:poopoo@10.0.60.36:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 0,0,0,122,26,237,118,204,245,182,637,140,1280,258,1280,0
    objects:
      filters:
        person:
          min_area: 1000
          min_score: 0.75
          mask:
            - 40,218,190,202,475,153,587,140,665,146,1280,266,1280,0,0,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 5
          mode: motion

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb


ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
version: 0.14
```

### Relevant log output

```shell
No frames received from Camera in 20 seconds. Exiting ffmpeg...
Waiting for ffmpeg to exit gracefully...
Camera: Unable to read frames from ffmpeg process.
Camera: ffmpeg process is not running. exiting capture thread...
Ffmpeg process crashed unexpectedly for Camera.
The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

```shell
I'm unsure how to do this inside Docker?
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua T54IR-ZE-S3

**Comment by hawkeye217** [comment]
Are you sure you are looking at the correct config file? Did you change the logs in any way before pasting?

The ffmpeg error reports the name of the camera. For example:
```
2024-08-16 23:53:47.046212  [2024-08-16 23:53:47] watchdog.Hall                  ERROR   : Ffmpeg process crashed unexpectedly for Hall.
2024-08-16 23:53:47.046352  [2024-08-16 23:53:47] watchdog.Hall                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

There is no camera named `Camera` in your config file.

Nonetheless, I'd suggest changing the ffmpeg arguments at the bottom section of your config file to:
```
ffmpeg:
  hwaccel_args: preset-vaapi
```

**Comment by TopBanana123** [comment]
My apologies, I did switch it to "Camera" to make it easier to read when posting on reddit, the camera is called "Generator" 

I will switch to what you suggested, but since the other cameras have no issues I suspect it may not help. But I will report back!

**Reply by hawkeye217** [reply]
No worries. The change I suggested won't have any effect as you're already reassigning `hwaccel_args` at the camera level.

Does your camera have an auto-reboot/maintenance function enabled? This is definitely an option in Dahua firmware. If the camera is going offline regularly at the same time each day, it would show up this way in the frigate logs.

**Reply by TopBanana123** [reply]
No auto reboot, sadly, that would be a nice easy fix! It will be fine for 12 hours and then might do this 3 times in the span of an hour, I really can't seem to find a correlation to anything

**Reply by hawkeye217** [reply]
Interesting. I have the same camera and it's been rock-solid with Frigate using PoE.

Can you paste more of the logs when it goes down?

**Reply by TopBanana123** [reply]
May be a silly question, but where do I get more logs? The error in system logs indicates it will provide the last 100 lines, but I don't get anything

**Reply by ElectronicBattle** [reply]
you can add this sort of thing to your config:

```
logger:
    logs:
      frigate.record.maintainer: debug
      frigate.object_detection: debug
      watchdog.Generator: debug
```

and that'll populate more details in the Frigate log (and of course you've already got access to the other logs for go2rtc and nginx) but I don't know how you recover the previous 100 lines if they are "missing".
