### DISCUSSION TITLE
[Support]: why does "it" (perhaps go2rtc?) crash my NVR all the time?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#13182] [General Support]
### Describe the problem you are having

hello All

I am using Frigate 0.13, connected to a three year old 8 channel Chinese ("Floureon" branded) NVR whose cameras all present rtsp hvec LAN outputs (confimed via ffprobe built into frigate and also via my linux host shell commands).  

This NVR  is a low powered server and doesn't like lots of connections being made to it based on my previous experiments years ago, prior to Frigate,  with ffplay ffprobe etc. tests and scripts.

This first config (one of the eight cameras shown) works well even though it seems wrong because it says `h264` and it makes scant use of go2rtc. The cameras run for days at a time, or weeks if I were to stop fiddling(!) :

```
######## working config ######## 
go2rtc:
  streams:
    greenhouse:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:greenhouse#audio=opus"

cameras: 
  greenhouse:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0
        roles:
        - record
```

whereas this config appears to me to make proper and better use of go2rtc, thus minimising the connections to the NVR, but the NVR crashes within tens of seconds of Frigate starting:

```
######## crashing config ######## 
go2rtc:
  streams:
    greenhouse:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy" #HD 1920x1080
      - "ffmpeg:greenhouse#audio=opus"

    greenhouse_sub:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0#video=h264#audio=copy" #SD 640x360
      - "ffmpeg:greenhouse_sub#audio=opus"
      
cameras: 
  greenhouse:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/greenhouse_sub 
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/greenhouse
        roles:
        - record
  ```
I have tried setting the go2rtc preset directives (is that the right terminology?) to say `#video=h264` or `#video=h265` or `#video=hvec` but it has either given me a blank screen or it has crashed the NVR before getting that far.  

Later today I shall have a thorough look through the go2rtc repository discussions to see if I can glean any ideas but, in the mean time, if someone educated could speculate so that I have a sense of direction in which to head, it would be better than my own wild (likely wrong) guesses.

I realise this might be an imponderable question.

[edit - incidentally, when it has run for a few tens of seconds with the crashing config shown, the in-browser playback has worked perfectly @NickM-27 @hawkeye217 you may remember my previous seemingly endless struggle]

### Version

0.13

### Frigate config file

```yaml
please see text but repeated here for clarity:
#########working config #########working config #########working config #########working config 
go2rtc:
  streams:
    greenhouse:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy"
      - "ffmpeg:greenhouse#audio=opus"

cameras: 
  greenhouse:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0
        roles:
        - detect
      - path: rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0
        roles:
        - record

#########crashing config #########crashing config #########crashing config ######### 
go2rtc:
  streams:
    greenhouse:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy" #HD 1920x1080
      - "ffmpeg:greenhouse#audio=opus"

    greenhouse_sub:    
      - "ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0#video=h264#audio=copy" #SD 640x360
      - "ffmpeg:greenhouse_sub#audio=opus"
      
cameras: 
  greenhouse:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/greenhouse_sub 
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/greenhouse
        roles:
        - record
```

### Relevant log output

```shell
go2rtc from working config:
[INFO] The go2rtc service exited with code 0 (by signal 0)
[INFO] Removing stale config from last run...
[INFO] Preparing new go2rtc config...
[INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
[INFO] Starting go2rtc...
INF go2rtc version 1.8.4 linux/amd64
INF [api] listen addr=:1984
[rtsp] listen addr=:8554
INF [webrtc] listen addr=:8555
[INFO] Starting go2rtc healthcheck service...

Crashing config - various messages after various crashes, including
WRN [rtsp] error="streams: codecs not matched: H264, PCMU => H264, H265, AAC" stream=drive_sub
WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 127.0.0.1:8554->127.0.0.1:45408: i/o timeout" url=ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0#video=h265#audio=copy
plus many mre similar ones
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0
Video: Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 640x360 FPS: Unknown
Audio:Codec: PCM mu-law / G.711 mu-law

Stream 1:
Return Code: 0
Video: Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 1920x1080 FPS: Unknown
Audio: Codec: PCM mu-law / G.711 mu-law
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

Floureon (Hikvision or XM clone)
