### DISCUSSION TITLE
[Bug]: Events created with `POST /api/events/<camera_name>/<label>/create` do not show up anymore

### DISCUSSION THREAD

**Discussion by danieldietsch** [blakeblackshear/frigate#13184] [Report a Bug]
### Describe the problem you are having

I am using various API calls to create events and record them. They are not shown in the UI anymore (even new ones created after 0.14), and despite having `record: enabled: true`. 

### Steps to reproduce

1. Have Frigate 0.14 with at least one camera
2. Send `POST /api/events/<camera_name>/<label>/create`, note event id
3. Wait some time
4. Send `PUT /api/events/<event_id>/end`
5. Try to find the event. 

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  host: ***
  port: 8883
  user: frigate
  password: ***
  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
  tls_insecure: true

go2rtc:
  streams:
    keller_01: # <- for RTSP streams
      - rtsp://***:***@***:554/live/ch0 # <- stream which supports video & aac audio

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: true
  mode: continuous

cameras:
  keller_01:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/keller_01 # restream via go2rtc
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      hwaccel_args: []
    motion: {}
    audio:
      enabled: true
audio:
  enabled: true
  listen:
    - footsteps
    - speech
    - yell
    - scream
    - fire_alarm
    - door
    - slam
    - rattle
detect:
  enabled: false
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 365
      mode: all
snapshots:
  enabled: true
  retain:
    default: 365
version: 0.14
```

### Relevant log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A
