### DISCUSSION TITLE
[Config Support]: Can't get reviews working

### DISCUSSION THREAD

**Discussion by bence-b** [blakeblackshear/frigate#13192] [Config Support] [answered]
### Describe the problem you are having

I'm struggling to get reviews. On the UI it says there are no alerts / detections to review, and No motion data found.
There is no frigate/reviews MQTT topic published.

I checked the detection treshold values and on the debug screen I get 85-95% for persons standing in the required zones.

Am I missing something in the config.yml?

Thanks

### Version

0.14

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.112:5000/api/config/schema.json

mqtt:
  enabled: true
  host: 192.168.1.xxx
  topic_prefix: frigate
  user: xxx
  password: xxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  #path: "/models/0132_ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
  #height: 320
  #width: 320
  #path: "/models/030_ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite"
  #height: 300
  #width: 300
  path: plus://xxxxxxxxxxxx


birdseye:
  enabled: false

go2rtc:
  streams:
    kapu:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.6/profile3 #352x288
    bejarat:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.4/profile3  #704x576
    garazs:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.3/profile2 #704x576
    pince:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.5/profile2 #352x288
    kert:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.7/profile1 #2048x1536
    vetemenyes:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.8/cam/realmonitor?channel=1&subtype=0 #1920x1080

review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person


cameras:
  kapu:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kapu
          roles:
            - detect

    detect:
      enabled: true
      fps: 5


    snapshots:
      enabled: true
      #required_zones:
      #  - kapu_elott

    mqtt: 
      enabled: true
      #required_zones:
      #  - kapu_elott

    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 50 #30
      #Watching the motion boxes in the debug view, adjust the contour area until there are no motion boxes smaller than the smallest you'd expect frigate to detect something moving.
      contour_area: 30 #10
      mask: 0.704,0,-0.001,0.519,0.001,0.002

    zones:
      kapu_elott:
        coordinates: 0.241,1,1,1,1,0.237,0.733,0.215
        inertia: 1
        loitering_time: 0
      utca:
        coordinates: 0.176,1,0,1,0,0.528,0.675,0.032,0.808,0.033
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - cat
        - dog

      filters:
        person:
          threshold: 0.8
          min_score: 0.7
        car:
          threshold: 0.8
          min_score: 0.7
        cat:
          threshold: 0.2
        dog:
          threshold: 0.2


    review:
      alerts:
        required_zones: kapu_elott



  bejarat:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bejarat
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      stationary:
        interval: 50
        threshold: 50


    snapshots:
      enabled: true
      required_zones:
        - bejarat_elott_b
        - rampa_alja_b

    mqtt:
      enabled: true
      required_zones:
        - bejarat_elott_b
        - rampa_alja_b


    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 30 #30
      #Watching the motion boxes in the debug view, adjust the contour area until there are no motion boxes smaller than the smallest you'd expect frigate to detect something moving.
      contour_area: 10 #10


      mask:
        - 0.938,0.118,0.72,0.071,0.468,0.059,0.252,0.067,0.207,0.184,0.205,0.286,0.156,0.314,0.105,0.343,0.099,0.542,0.004,0.643,0.004,0.005,1,0.006,1,0.607,0.957,0.501
        - 0.666,0.884,0.662,0.952,0.895,0.952,0.897,0.884

    zones:
      bejarat_elott_b:
        coordinates: 
          0.321,0.552,0.327,0.485,0.466,0.478,0.464,0.566,0.953,0.572,1,0.654,1,1,0.478,1,0.462,0.699,0,0.678,0,0.646,0.087,0.542,0.137,0.557
        inertia: 3
        loitering_time: 0
      rampa_alja_b:
        coordinates: 0,1,0.473,1,0.458,0.704,0,0.684
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - cat
        - dog

      filters:
        person:
          threshold: 0.8
          min_score: 0.7
        car:
          threshold: 0.8
          min_score: 0.7

        cat:
          threshold: 0.8
          min_score: 0.7
        dog:
          threshold: 0.8
          min_score: 0.7

      mask: 0.316,0.546,0.314,0.504,0.151,0.502,0.144,0.536
    review:
      alerts:
        required_zones:
          - bejarat_elott_b
          - rampa_alja_b
  garazs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garazs
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      stationary:
        interval: 50
        threshold: 50

    snapshots:
      enabled: true
      required_zones:
        - bejarat_elott_g
        - garazs_elott_g
        - rampan_g

    mqtt:
      enabled: true
      required_zones:
        - bejarat_elott_g
        - garazs_elott_g
        - rampan_g

    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 30 #30
      #Watching the motion boxes in the debug view, adjust the contour area until there are no motion boxes smaller than the smallest you'd expect frigate to detect something moving.
      contour_area: 10 #10


      mask:
        - 0,0.437,0.002,0.001,0.998,0.002,0.996,0.614,0.823,0.214,0.822,0.096,0.434,0.107,0.136,0.162,0.133,0.222,0.032,0.272
        - 0.451,0.377,0.471,0.255,0.6,0.279,0.552,0.436,0.458,0.446
    zones:
      rampan_g:
        coordinates: 0.526,0.528,0.962,0.549,0.816,0.204,0.632,0.2
        inertia: 3
        loitering_time: 0
      garazs_elott_g:
        coordinates: 0.477,0.526,0.516,0.411,0.223,0.404,0.052,0.508
        inertia: 3
        loitering_time: 0
      bejarat_elott_g:
        coordinates: 0.046,0.515,0,0.525,0,1,1,1,1,0.633,0.968,0.558
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - cat
        - dog

      filters:
        person:
          threshold: 0.85
          min_score: 0.8
        car:
          threshold: 0.8
          min_score: 0.7
          mask: 0.129,0.375,0.583,0.364,0.607,0.109,0.133,0.114
        cat:
          threshold: 0.8
          min_score: 0.7
        dog:
          threshold: 0.8
          min_score: 0.7



    review:
      alerts:
        required_zones:
          - bejarat_elott_g
          - garazs_elott_g
          - rampan_g
  kert:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kert
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      stationary:
        interval: 50
        threshold: 50

    snapshots:
      enabled: true

    mqtt:
      enabled: true

    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 30 #30
      #Watching the motion boxes in the debug view, adjust the contour area until there are no motion boxes smaller than the smallest you'd expect frigate to detect something moving.
      contour_area: 10 #10

      mask:
        - 0.03,0.914,0.029,0.955,0.368,0.957,0.369,0.908
        - 0.038,0.327,0,0.33,0,0.001,1,0,1,0.506,0.453,0.365
    zones:
      kert_k:
        coordinates: 0.177,0.497,0.504,0.571,1,0.727,1,1,0,1,0,0.424

        inertia: 3
        loitering_time: 0
      kert_terasz_k:
        coordinates: 0.27,0.514,0.49,0.556,0.615,0.599,0.625,0.51,0.51,0.456,0.169,0.476
        loitering_time: 0
      kert_tavol_k:
        coordinates: 1,0.581,0.627,0.539,0.616,0.599,1,0.716
        loitering_time: 0

        inertia: 3
    objects:
      track:
        - person


      filters:
        person:
          threshold: 0.91
          min_score: 0.7


    review:
      alerts:
        required_zones:
          - kert_terasz_k
          - kert_k
          - kert_tavol_k

  pince:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pince
          roles:
            - detect
    detect:
      enabled: true
      fps: 5

    snapshots:
      enabled: true

    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 30 #30
      #Watching the motion boxes in the debug view, adjust the contour area until there are no motion boxes smaller than the smallest you'd expect frigate to detect something moving.
      contour_area: 10 #10


      mask:
        - 0.492,0.004,0.566,0.313,0.81,0.601,0.999,0.63,0.998,0
        - 0.389,0.191,0.403,0,0.094,0,0.096,0.103
    objects:
      track:
        - person
        - cat
        - dog

      filters:
        person:
          threshold: 0.8
          min_score: 0.7
          max_ratio: 1.0
        cat:
          threshold: 0.8
          min_score: 0.65
        dog:
          threshold: 0.8
          min_score: 0.65

    zones:
      pince_lepcso_p:
        coordinates: 0.108,0.604,0.278,0.573,0.538,1,0.13,1
        loitering_time: 0
        inertia: 3
      pince_rampa_p:
        coordinates: 0.404,0.038,0.455,0.04,0.529,0.304,0.795,0.598,0.67,0.629,0.388,0.252
        loitering_time: 0
        inertia: 3
      pince_rampa_alja_p:
        coordinates: 0.759,1,1,1,1,0.724,0.65,0.849
        loitering_time: 0


        inertia: 3
    review:
      alerts:
        required_zones:
          - pince_rampa_p
          - pince_rampa_alja_p
          - pince_lepcso_p
  vetemenyes:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vetemenyes
          roles:
            - detect
    detect:
      enabled: true
      fps: 5

    snapshots:
      enabled: true

    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 30 #30
      #Watching the motion boxes in the debug view, adjust the contour area until there are no motion boxes smaller than the smallest you'd expect frigate to detect something moving.
      contour_area: 10 #10

      mask: 
        0.158,0.917,0.077,0.898,0.097,0.564,0.171,0.46,0.366,0.39,0.63,0.359,0.641,0.203,0.726,0.147,0.853,0.153,0.858,0.605,0.898,0.995,1,1,1,0,0.002,0.005,-0.001,0.998,0.156,1
    objects:
      track:
        - person
        - cat
        - dog

      filters:
        person:
          threshold: 0.8
          min_score: 0.7
          max_ratio: 1.0
        cat:
          threshold: 0.8
          min_score: 0.7     
        dog:
          threshold: 0.8
          min_score: 0.7



    zones:
      pregola_alatt_v:
        coordinates: 0.636,0.291,0.886,0.312,0.893,0.361,0.632,0.344
        loitering_time: 0
      pergola_lepcso_v:
        coordinates: 0.777,0.369,0.751,0.605,0.848,0.626,0.831,0.374
        loitering_time: 0
      vetemenyes_v:
        coordinates: 
          0.845,0.641,0.829,1,0.16,1,0.165,0.792,0.216,0.694,0.38,0.601,0.747,0.539,0.746,0.62
        loitering_time: 0
        inertia: 3
      naspolya_v:
        coordinates: 0.326,0.577,0.454,0.567,0.453,0.473,0.366,0.48
        loitering_time: 0
      kert_v:
        coordinates: 0.083,0.745,0.196,0.722,0.383,0.411,0.147,0.503
        loitering_time: 0
        inertia: 3

    review:
      alerts:
        required_zones:
          - vetemenyes_v
          - pregola_alatt_v
          - pergola_lepcso_v
          - kert_v
          - naspolya_v
          
version: 0.14
```

### Relevant log output

```shell
Type
warning
Timestamp
2024-08-19 18:23:47
Tag
frigate.api.review
Message
No motion data found for the requested time range
```

### Frigate stats

```json
{
"cameras": {
"bejarat": {
"audio_dBFS": 0,
"audio_rms": 0,
"camera_fps": 5,
"capture_pid": 418,
"detection_enabled": true,
"detection_fps": 0,
"ffmpeg_pid": 434,
"pid": 377,
"process_fps": 5.1,
"skipped_fps": 0
},
"garazs": {
"audio_dBFS": 0,
"audio_rms": 0,
"camera_fps": 5.1,
"capture_pid": 427,
"detection_enabled": true,
"detection_fps": 0.1,
"ffmpeg_pid": 440,
"pid": 385,
"process_fps": 5.1,
"skipped_fps": 0
},
"kapu": {
"audio_dBFS": 0,
"audio_rms": 0,
"camera_fps": 5,
"capture_pid": 410,
"detection_enabled": true,
"detection_fps": 0,
"ffmpeg_pid": 426,
"pid": 376,
"process_fps": 5,
"skipped_fps": 0
},
"kert": {
"audio_dBFS": 0,
"audio_rms": 0,
"camera_fps": 5.1,
"capture_pid": 432,
"detection_enabled": true,
"detection_fps": 1.7,
"ffmpeg_pid": 446,
"pid": 392,
"process_fps": 5.1,
"skipped_fps": 0
},
"pince": {
"audio_dBFS": 0,
"audio_rms": 0,
"camera_fps": 5,
"capture_pid": 437,
"detection_enabled": true,
"detection_fps": 0,
"ffmpeg_pid": 452,
"pid": 401,
"process_fps": 5,
"skipped_fps": 0
},
"vetemenyes": {
"audio_dBFS": 0,
"audio_rms": 0,
"camera_fps": 5,
"capture_pid": 443,
"detection_enabled": true,
"detection_fps": 0,
"ffmpeg_pid": 457,
"pid": 402,
"process_fps": 5,
"skipped_fps": 0
}
},
"cpu_usages": {
"1": {
"cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"15": {
"cmdline": "s6-supervise s6-linux-init-shutdownd",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"17": {
"cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"24": {
"cmdline": "s6-supervise go2rtc-healthcheck",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"25": {
"cmdline": "s6-supervise s6rc-oneshot-runner",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"26": {
"cmdline": "s6-supervise frigate-log",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"27": {
"cmdline": "s6-supervise go2rtc-log",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"28": {
"cmdline": "s6-supervise nginx",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"29": {
"cmdline": "s6-supervise certsync-log",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"30": {
"cmdline": "s6-supervise go2rtc",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"31": {
"cmdline": "s6-supervise nginx-log",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"32": {
"cmdline": "s6-supervise certsync",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"33": {
"cmdline": "s6-supervise s6rc-fdholder",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"34": {
"cmdline": "s6-supervise frigate",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"45": {
"cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"46": {
"cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"84": {
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"87": {
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"92": {
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"94": {
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"99": {
"cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
"cpu": "7.2",
"cpu_average": "6",
"mem": "0.4"
},
"118": {
"cmdline": "bash ./run.user go2rtc-healthcheck",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"127": {
"cmdline": "python3 -u -m frigate",
"cpu": "8.7",
"cpu_average": "9",
"mem": "5.8"
},
"133": {
"cmdline": "nginx: master process nginx",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2"
},
"160": {
"cmdline": "nginx: worker process",
"cpu": "0.3",
"cpu_average": "0",
"mem": "0.1"
},
"161": {
"cmdline": "nginx: worker process",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1"
},
"162": {
"cmdline": "nginx: cache manager process",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1"
},
"238": {
"cmdline": "bash ./run.user certsync",
"cpu": "0.1",
"cpu_average": "0",
"mem": "0.0"
},
"265": {
"cmdline": "frigate.logger       ",
"cpu": "0.1",
"cpu_average": "0",
"mem": "1.5"
},
"326": {
"cmdline": "frigate.recording_manager",
"cpu": "1.0",
"cpu_average": "1",
"mem": "1.7"
},
"329": {
"cmdline": "frigate.review_segment_manager",
"cpu": "1.7",
"cpu_average": "1",
"mem": "1.7"
},
"356": {
"cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(68)",
"cpu": "1.2",
"cpu_average": "1",
"mem": "0.1"
},
"357": {
"cmdline": "frigate.detector.coral",
"cpu": "1.1",
"cpu_average": "4",
"mem": "1.9"
},
"358": {
"cmdline": "frigate.output       ",
"cpu": "7.3",
"cpu_average": "8",
"mem": "1.8"
},
"376": {
"cmdline": "frigate.process:kapu ",
"cpu": "3.7",
"cpu_average": "3",
"mem": "1.8"
},
"377": {
"cmdline": "frigate.process:bejarat",
"cpu": "3.3",
"cpu_average": "4",
"mem": "1.9"
},
"385": {
"cmdline": "frigate.process:garazs",
"cpu": "6.6",
"cpu_average": "6",
"mem": "1.9"
},
"392": {
"cmdline": "frigate.process:kert ",
"cpu": "7.0",
"cpu_average": "6",
"mem": "1.9"
},
"401": {
"cmdline": "frigate.process:pince",
"cpu": "3.9",
"cpu_average": "5",
"mem": "1.8"
},
"402": {
"cmdline": "frigate.process:vetemenyes",
"cpu": "3.6",
"cpu_average": "4",
"mem": "1.9"
},
"410": {
"cmdline": "frigate.capture:kapu ",
"cpu": "1.0",
"cpu_average": "1",
"mem": "1.7"
},
"418": {
"cmdline": "frigate.capture:bejarat",
"cpu": "2.3",
"cpu_average": "2",
"mem": "1.7"
},
"426": {
"cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/kapu -r 5 -vf fps=5,scale_vaapi=w=352:h=288:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
"cpu": "2.0",
"cpu_average": "2",
"mem": "0.4"
},
"427": {
"cmdline": "frigate.capture:garazs",
"cpu": "2.3",
"cpu_average": "2",
"mem": "1.7"
},
"432": {
"cmdline": "frigate.capture:kert ",
"cpu": "10.9",
"cpu_average": "10",
"mem": "1.8"
},
"434": {
"cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/bejarat -r 5 -vf fps=5,scale_vaapi=w=704:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
"cpu": "2.6",
"cpu_average": "2",
"mem": "0.5"
},
"437": {
"cmdline": "frigate.capture:pince",
"cpu": "1.1",
"cpu_average": "1",
"mem": "1.7"
},
"440": {
"cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/garazs -r 5 -vf fps=5,scale_vaapi=w=704:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
"cpu": "2.9",
"cpu_average": "2",
"mem": "0.5"
},
"443": {
"cmdline": "frigate.capture:vetemenyes",
"cpu": "7.4",
"cpu_average": "7",
"mem": "1.8"
},
"446": {
"cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/kert -r 5 -vf fps=5,scale_vaapi=w=2048:h=1536:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
"cpu": "9.9",
"cpu_average": "9",
"mem": "1.0"
},
"452": {
"cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/pince -r 5 -vf fps=5,scale_vaapi=w=352:h=288:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
"cpu": "2.6",
"cpu_average": "2",
"mem": "0.4"
},
"457": {
"cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/vetemenyes -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
"cpu": "17.1",
"cpu_average": "17",
"mem": "0.8"
},
"474": {
"cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 352x288 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2"
},
"479": {
"cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2"
},
"484": {
"cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2"
},
"489": {
"cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2048x1536 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2"
},
"494": {
"cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 352x288 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.3"
},
"499": {
"cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2"
},
"4934": {
"cmdline": "sleep 60",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"4946": {
"cmdline": "sleep 30s",
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0"
},
"frigate.full_system": {
"cpu": "65.6",
"mem": "22.5"
}
},
"detection_fps": 1.8,
"detectors": {
"coral": {
"detection_start": 0,
"inference_speed": 8.28,
"pid": 357
}
},
"gpu_usages": {
"intel-vaapi": {
"gpu": "6.24%",
"mem": "-%"
}
},
"processes": {
"go2rtc": {
"pid": 99
},
"logger": {
"pid": 265
},
"recording": {
"pid": 326
},
"review_segment": {
"pid": 329
}
},
"service": {
"last_updated": 1724084523,
"latest_version": "0.14.0",
"storage": {
"/dev/shm": {
"free": 243.6,
"mount_type": "tmpfs",
"total": 256,
"used": 12.4
},
"/media/frigate/clips": {
"free": 78292,
"mount_type": "ext4",
"total": 111604.2,
"used": 27597.9
},
"/media/frigate/recordings": {
"free": 78292,
"mount_type": "ext4",
"total": 111604.2,
"used": 27597.9
},
"/tmp/cache": {
"free": 940.9,
"mount_type": "tmpfs",
"total": 953.7,
"used": 12.7
}
},
"temperatures": {},
"uptime": 2800,
"version": "0.14.0-da913d8"
}
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral
