### DISCUSSION TITLE
[Config Support]: Event triggered, but not found in Home Assistant

### DISCUSSION THREAD

**Discussion by Ayuus** [blakeblackshear/frigate#13206] [Config Support]
### Describe the problem you are having

I have a notification set up to notify me in case of a person detected. Sometimes, in case of false positives, a mqtt message "new", "person" is recieved by Home Assistant, but without a snapshot, and whe I want to see snapshot/video of the event later, Frigate responds with "Event not Found".
Whay is this happening, an how can I avoid it? 
Can I use score and/or top_score in mqtt message to prevent this kind of false alarms?

### Version

0.14.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.10 #homeassistant.local
  port: 1883
#  port: 8883
#  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
#  tls_insecure: false
  user: homeassistant
  password: zz

ui:
  time_format: 24hour

logger:
  default: info
#  logs:
#    frigate.ptz.onvif: debug

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.6
      threshold: 0.7
    cat:
      min_score: 0.6
      threshold: 0.7
    dog:
      min_score: 0.6
      threshold: 0.7

detect:
  max_disappeared: 5

#motion:
#   lightning_threshold: 0.9

birdseye:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

audio:
  # geen audio events, events zijn wel inclusief audio
  enabled: false
  min_volume: 500
  listen:
    - speech
    - yell
    - scream
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event
      threshold: 0.8
    yell:
      threshold: 0.8
    scream:
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

go2rtc:
  streams:
    buitencamera_zijgevel:
      - rtsp://admin:zz@192.168.4.40:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps
    buitencamera_achterzijde:
      - rtsp://admin:zz@192.168.4.41:554/cam/realmonitor?channel=1&subtype=2 #720p/25fps
    buitencamera_voordeur:
      - rtsp://admin:zz@192.168.4.42:554/cam/realmonitor?channel=1&subtype=3 #720p/25fps

cameras:
  buitencamera_voordeur:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:zz@192.168.4.42:554/cam/realmonitor?channel=1&subtype=2   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://admin:zz@192.168.4.42:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record

  buitencamera_zijgevel:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:z@192.168.4.40:554/cam/realmonitor?channel=1&subtype=2     #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://admin:zz@192.168.4.40:554/cam/realmonitor?channel=1&subtype=0     #4MP25fps
          roles:
            - record
    motion:
      mask: 0.643,0.358,0.843,1,1,1,1,0,0.678,0,0.378,0,0.385,0.371
    zones:
      grind:
        coordinates: 505,266,912,250,1148,720,509,720
    review:
      alerts:
        required_zones:
          - grind
    snapshots:
      required_zones:
        - grind
  buitencamera_achterzijde:
    ffmpeg:
      output_args:
        #audio format must be AAC, so we set this as format in camera configuration
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:zz@192.168.4.41:554/cam/realmonitor?channel=1&subtype=1   #720p/5fps
          roles:
            - audio
            - detect
        - path: 
            rtsp://admin:zz@192.168.4.41:554/cam/realmonitor?channel=1&subtype=0   #4MP25fps
          roles:
            - record

version: 0.14
```

### Relevant log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

I did not see this behaviour in 0.13.2, with the same HA automation, which looks like this:
```
#------------------------------------------------------------------------------#
# Notificatie op telefoon van Person Detected bij de zijgevel, op het grind
# https://github.com/blakeblackshear/frigate/discussions/2898
#------------------------------------------------------------------------------#
- id: '202407071306'
  alias: Frigate Event - Person Detected Zijgevel
  trigger:
    - platform: mqtt
      topic: frigate/events
      payload: buitencamera_zijgevel
      value_template: "{{ value_json['after']['camera'] }}"
      variables:
#        before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
#        after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
        camera: "{{ trigger.payload_json['after']['camera'] }}"
        id: "{{ trigger.payload_json['after']['id'] }}"
        label: "{{ trigger.payload_json['after']['label'] }}"
#        score: "{{ trigger.payload_json['after']['score'] }}"
  condition:
    # Op het grind?
#    - condition: template
#      value_template: "{{ before_zones | length == 0 and after_zones | length != 0 }}"
#    - condition: template
#      value_template: "{{ ['grind'] | select('in', after_zones) | list | length > 0 }}"
    - condition: template
      value_template: "{{ trigger.payload_json['type'] == 'new' }}"
    # This filters out any objects other than persons
    - condition: template
      value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
#    - condition: template
#      value_template: "{{ trigger.payload_json['after']['score'] >= 0.7 }}"
  action:
    - variables:
        title: 'Achtung!'
        message: "Persoon gedetecteerd bij de zijgevel!"
    - service: script.camera_notification_to_ronald_boe
      data:
        camera: "{{ camera }}"
        id: "{{ id }}"
        title: "{{ title }}" 
        message: "{{ message }}" 
    # Wait until the end of the notification has occurred.
    - repeat:
        until:
          - condition: template
            value_template: "{{ wait.trigger.payload_json['type'] == 'end' }}"
        sequence:
          - wait_for_trigger:
              - platform: mqtt
                topic: frigate/events
                payload: "{{ trigger.payload_json['after']['id'] }}"
                value_template: "{{ value_json['after']['id'] }}"
            continue_on_timeout: false
            timeout: '00:02:00'
          - condition: template
            value_template: "{{ wait.trigger.payload_json['type'] == 'end' }}"
          - delay:
              seconds: 10
          - service: script.camera_notification_to_ronald_eoe
            data:
              camera: "{{ camera }}"
              id: "{{ id }}"
              title: "{{ title }}" 
              message: "{{ message }}" 
  mode: parallel
  max: 10
```
