### DISCUSSION TITLE
[Support]: Dog/Bike/etc no longer detected?

### DISCUSSION THREAD

**Discussion by cliffburdick** [blakeblackshear/frigate#13216] [General Support] [answered]
### Describe the problem you are having

I updated from 0.13 to 0.14 with a complete wipe of my db file. Dogs and bikes used to be detected without issues, but now even though several dogs have gone by, the filter only gives the option for people and cars.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat
    - face
    - package
    - license_plate
    - amazon
    - ups
    - fedex
    - car
    - motorcycle
    - bicycle
  filters:
    dog:
      min_score: .7
      threshold: .8
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .80
    car:
      min_score: .65
      threshold: .80

model:
  path: plus://baac81f8e71e6b32a1d16b10cecf1133

cameras:
  lwb: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:pass!@192.168.1.170:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass!@192.168.1.170:554 # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 10
          mode: active_objects
    motion:
      mask:
        - 1280,398,1121,212,852,0,383,0,292,94,191,145,140,200,0,251,26,458,199,720,1280,720
    zones:
      front_and_street:
        coordinates: 
          1428,161,922,150,739,411,651,480,490,560,517,632,478,707,342,821,373,881,234,1013,258,1080,1920,1080,1920,251

  uwb: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:pass@192.168.1.172:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.1.172:554 # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          mode: active_objects
          default: 10
    motion: {}
    zones:
      driveway_and_street:
        coordinates: 391,0,1868,0,1968,137,2358,127,2375,261,2238,527,2575,657,2688,1520,0,1520,0,277
  porch: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:pass@192.168.1.171:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.1.171:554 # <----- The stream you want to use for detection
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          mode: active_objects
          default: 10
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    motion:
      mask:
        - 1280,117,1161,95,1089,165,805,131,530,97,387,147,334,0,0,0,0,720,1280,720
    zones:
      porch_and_lawn:
        coordinates: 
          2688,0,2381,244,2315,347,1945,261,1618,244,1178,187,931,267,735,0,0,0,0,1520,2688,1520
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
version: 0.14
camera_groups:
  Cameras:
    order: 1
    icon: LuAccessibility
    cameras:
      - lwb
      - porch
      - uwb
      - birdseye
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua
