### DISCUSSION TITLE
[Support]: One Camera when night vision kicks in crashes ffmpeg at night. Works on h.265, but unstable during daytime.

### DISCUSSION THREAD

**Discussion by Chris87871** [blakeblackshear/frigate#13231] [General Support]
### Describe the problem you are having

One Camera when night vision kicks in crashes ffmpeg at night. Works on h.265, but unstable during daytime.

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  deepstack:
    type: deepstack
    api_url: http://192.168.2.4:32168/v1/vision/detection
    api_timeout: 3 # seconds
  cpu1:
    type: cpu
    num_threads: 4
    #cpu2:
      #type: cpu
      #num_threads: 4
#Global Object Settings
objects:
  track:
    - person
    - cat
  filters:
    person:
      min_area: 100
      max_area: 100000
      threshold: 0.7

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 3840
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

go2rtc:
  streams:
    BackYard:
      - ffmpeg:rtsp://192.168.2.100:554/stream0

    BackYard_Sub:
      - ffmpeg:rtsp://192.168.2.100:554/stream1

    Window:
      - ffmpeg:rtsp://192.168.2.102:554/live/main

    Window_Sub:
      - ffmpeg:rtsp://192.168.2.102:554/live/sub

    webrtc:
    candidates:
      - 192.168.2.4:8555
      - stun:8555

cameras:
  BackYard:
    birdseye:
      order: 1
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/BackYard?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/BackYard_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: BackYard
  
  Window:
    birdseye:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Window?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/Window_Sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
detect:
  width: 640
  height: 480
  fps: 5
  max_disappeared: 25

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 30


version: 0.14
```

### Relevant log output

```shell
error
2024-08-20 18:40:12
frigate.video
BackYard: Unable to read frames from ffmpeg process.
error
2024-08-20 18:40:12
frigate.video
BackYard: ffmpeg process is not running. exiting capture thread...
error
2024-08-20 18:40:17
watchdog.BackYard
Ffmpeg process crashed unexpectedly for BackYard.
error
2024-08-20 18:40:17
watchdog.BackYard
The following ffmpeg logs include the last 100 lines prior to exit.
error
2024-08-20 18:40:17
ffmpeg.BackYard.detect
rtsp://127.0.0.1:8554/BackYard_Sub?video&audio: Invalid data found when processing input
error
2024-08-20 18:40:17
ffmpeg.BackYard.audio_record
rtsp://127.0.0.1:8554/BackYard?video&audio: Invalid data found when processing input
info
2024-08-20 18:40:17
watchdog.BackYard
Terminating the existing ffmpeg process...
```

### FFprobe output from your camera

```shell
ffprobe version N-103134-gaccfd015e3-g65fdc0e589+2 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration:  --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-librtmp --enable-mbedtls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads
  libavutil      57.  3.100 / 57.  3.100
  libavcodec     59.  4.100 / 59.  4.100
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  1.103 /  8.  1.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, rtsp, from 'rtsp://192.168.2.100:554/stream0':
  Metadata:
    title           : RTSP/RTP stream from anjvision ipcamera
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2144, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 16000 Hz, 1 channels, s16, 128 kb/s



ffprobe version N-103134-gaccfd015e3-g65fdc0e589+2 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration:  --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-librtmp --enable-mbedtls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads
  libavutil      57.  3.100 / 57.  3.100
  libavcodec     59.  4.100 / 59.  4.100
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  1.103 /  8.  1.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[rtsp @ 000001e7c206ef00] Error parsing AU headers
    Last message repeated 52 times
Input #0, rtsp, from 'rtsp://192.168.2.100:554/stream0':
  Metadata:
    title           : RTSP/RTP stream from anjvision ipcamera
  Duration: N/A, start: 0.498000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2144, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

CTVision YM800N_WM230

### Any other information that may be helpful

It only crashes at night time after black and white night vision turns on.

**Comment by hawkeye217** [comment]
This is usually related to a power issue with the camera where the stream becomes unstable. There's nothing Frigate can do about that. If the camera is PoE, make sure your switch is providing enough power to the camera.

**Reply by Chris87871** [reply]
The camera is still viewable and works with other dvr/nvr software such as ISpy or milestone xprotect. Also any idea when I turn ACC on in camera error parsing AU headers

**Reply by hawkeye217** [reply]
What do your go2rtc logs show when the stream crashes in Frigate?

**Comment by Chris87871** [comment]
info
2024-08-20 18:53:19
startup
Preparing new go2rtc config...
info
2024-08-20 18:53:20
startup
Starting go2rtc...
info
2024-08-20 18:53:20
startup
go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info
2024-08-20 18:53:20
startup
config path=/dev/shm/go2rtc.yaml
info
2024-08-20 18:53:20
rtsp
listen addr=:8554
info
2024-08-20 18:53:20
api
listen addr=:1984
info
2024-08-20 18:53:20
webrtc
listen addr=:8555/tcp
info
2024-08-20 18:53:29
startup
Starting go2rtc healthcheck service...
warning
2024-08-20 18:53:38
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:rtsp://192.168.2.100:554/stream1
warning
2024-08-20 18:53:38
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:rtsp://192.168.2.100:554/stream0



I turned on night vision manually jsut now and seems ok atm this may only be a night time thing. I will try to grab the logs tonight when it happens

**Reply by hawkeye217** [reply]
The `EOF` error means go2rtc's ffmpeg is failing on the camera stream, most likely because ffmpeg loses the connection to it. You can try enabling more verbose go2rtc logging. https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-log

**Reply by Chris87871** [reply]
Does this go in my frigate config or where do I put it and location
log:
  level: info  # default level
  api: trace
  exec: debug
  ngrok: info
  rtsp: warn
  streams: error
  webrtc: fatal

**Reply by hawkeye217** [reply]
Add it to the go2rtc section of your frigate config (there will be a lot of logging if you use `trace`, feel free to use another less verbose option if you want):

```
go2rtc:
  log:
    level: trace
    api: trace
    exec: trace
    ngrok: trace
    rtsp: trace
    streams: trace
    webrtc: trace
  streams:
    BackYard:
    ...
```
