### DISCUSSION TITLE
[Question]: CPU % is high?

### DISCUSSION THREAD

**Discussion by FS1961** [blakeblackshear/frigate#13236] [Ask A Question] [answered]
### What is your question:

Running new 0.14 and it's beautiful!  Not sure I understand how the CPU % is calculated or when to be alarmed.  Please see screenshot.

[CPU 61%](http://192.168.178.97:5000/system#general)
[Intel GPU 16%](http://192.168.178.97:5000/system#general)

<img width="1774" alt="Screenshot 2024-08-21 at 8 54 03 AM" src="https://github.com/user-attachments/assets/67b513e8-f19e-4f96-85c5-1a0abf613f4e">

**Comment by NickM-27** [comment]
The CPU% shown in the bottom left is cumulative average for all cores, the % shown on each stat is % of a single core. The best page to see would be the camera metrics page

**Comment by FS1961** [comment]
Okay - so I'm not alarmed then?

By the way - you and your guys did a phenomenal job on this version! My Hat is off to you!

**Reply by NickM-27** [reply]
would be good to see the camera metrics page

and thank you!

**Comment by FS1961** [comment]
<img width="1640" alt="Screenshot 2024-08-21 at 3 08 29 PM" src="https://github.com/user-attachments/assets/8a60760b-6fb3-4334-85e1-6ab08c5732a4">
<img width="1624" alt="Screenshot 2024-08-21 at 3 08 39 PM" src="https://github.com/user-attachments/assets/8500defc-85b7-4d26-a253-d754b98578ce">

**Reply by NickM-27** [reply]
Some of the cameras cpu is a bit high but nothing too alarming

**Comment by FS1961** [comment]
Still feeling my way around the new system.  Any suggestions are appreciated.

**Comment by FS1961** [comment]
Any recommendations? On Aug 21, 2024, at 3:22 PM, Nicolas Mowen ***@***.***> wrote:﻿
Some of the cameras cpu is a bit high but nothing too alarming

**Reply by NickM-27** [reply]
would need to see the config

**Reply by FS1961** [reply]
Okay

```
mqtt:
  host: 192.x.178.82
  user: userid
  password: passwd

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    office:
      - rtsp://userid:passwd@192.x.178.125:554/stream1
    storage:
      - rtsp://userid:passwd@192.x.178.131:554/stream1
    granny_flat:
      - rtsp://userid:passwd@192.x.178.136:554/stream1
    garage:
      - rtsp://userid:passwd@192.x.178.130:554/stream1
    dining:
      - ffmpeg:rtsp://userid:passwd@192.x.178.59:554/play1.sdp
    front-door:
      - ffmpeg:rtsp://userid:passwd@192.x.178.28:554/play1.sdp
    gh_cam:
      - ffmpeg:rtsp://userid:passwd@192.x.178.57:554/play1.sdp
    driveway:
      - ffmpeg:rtsp://userid:passwd@192.x.178.55:554/h264
    patio:
      - ffmpeg:rtsp://userid:passwd@192.x.178.74:554/h264
    garden-main:
      - ffmpeg:rtsp://userid:passwd@192.x.178.52:554/h264Preview_01_main
    garden-sub:
      - ffmpeg:rtsp://userid:passwd@192.x.178.52:554/h264Preview_01_sub

cameras:
  Office:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/office
          input_args: preset-rtsp-restream
          roles:
            - detect

  Storage:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/storage
          input_args: preset-rtsp-restream
          roles:
            - detect

  Granny_flat:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/granny_flat
          input_args: preset-rtsp-restream
          roles:
            - detect

  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      threshold: 50
      contour_area: 20
      improve_contrast: 'true'
  Dining: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/dining
          input_args: preset-rtsp-restream

  Front-door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-door
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      entry_doors:
        coordinates: 737,1043,1119,961,1098,136,579,168
    motion:
      mask:
        - 620,1080,0,1080,0,472,91,430,378,363,466,761

  Garten-house: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gh_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 5
    motion:
      mask:
        - 818,697,1163,720,1193,334,839,345

  Garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden-main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    live:
      stream_name: garden_main

  Drive-way: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    zones:
      driveway_area:
        coordinates: 889,1079,908,1440,2560,1440,2560,797,2182,508,899,578
      front_entrance:
        coordinates: 904,582,1744,551,1773,0,883,0,849,74

  Patio: # <------ Name the camera.
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          input_args: preset-rtsp-restream
          roles:
            - detect

detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 3
      mode: active_objects

telemetry:
  stats:
    intel_gpu_stats: true

  version_check: true
ui:
  timezone: Europe/Berlin
```
