### DISCUSSION TITLE
[Config Support]: Live view of camera does not load

### DISCUSSION THREAD

**Discussion by slashgob** [blakeblackshear/frigate#13238] [Config Support] [answered]
### Describe the problem you are having

Using Firefox browser version 129.0 - From the All Camera screen, if I click the "Front" camera to get a live view, it connects no problem and I get a live view. However, if I click the "Side" or "Garden" camera for a live view I just get a spinning icon and it never loads. Birdseye, Recording and Review screens all work fine. These are all Reolink 520A cameras.

I also use the Home Assistant Frigate integration and Card and I can see all Live views from all Cameras with no delay or problems. Just not from the desktop browser.

I have tried the suggested http connection method for these cameras but that just point blank refuses to work, RTSP is working fine with audio.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
qtt:
  enabled: true
  host: 10.0.0.4
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxx
  password: xxxxx

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  # Optional: default log level (default: shown below)
  default: info

cameras:
  Side: # <--- Reolink
    enabled: true
    birdseye:
      order: 2
    ui:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://viewer:xxxxxxx@10.0.0.81:554/h264Preview_01_sub
          input_args: preset-rtsp-restream        
          roles:
            - detect
        - path: rtsp://viewer:xxxxxxx@10.0.0.81:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
    zones:
      Drive_Side:
        coordinates: 0.299,1,0.601,1,0.843,0.662,0.347,0.011,0.02,0.166
        objects: person
        filters:
          person:
            min_area: 4000
            max_area: 8000
            threshold: 0.7
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0,0,1,0,1,0.688,0.358,0,0,0.168
        - 0.111,0.457,0.195,0.397,0.315,0.654,0.206,0.742,0.293,1,0,1,0,0.159,0.012,0.15
    review:
      alerts:
        required_zones: Drive_Side
      detections:
        required_zones: Drive_Side
  Garden: # <--- Reolink
    enabled: true
    birdseye:
      order: 3
    ui:
      order: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://viewer:xxxxxx@10.0.0.83:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://viewer:xxxxxx@10.0.0.83:554/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
    zones:
      Garden_Zone:
        coordinates: 0,1,0.727,1,0.921,0.327,0.642,0.167,0,0.325
        objects: person
        filters:
          person:
            min_area: 4000
            max_area: 8000
            threshold: 0.7
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.321,0.641,0.156,0.931,0.322,0.854,0.648,0.742,1,1,1,1,0,0,0
    review:
      alerts:
        required_zones: Garden_Zone
      detections:
        required_zones: Garden_Zone
  Front: # <--- Reolink
    enabled: true
    birdseye:
      order: 1
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://viewer:xxxxxx@10.0.0.82:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://viewer:xxxxxxx@10.0.0.82:554/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
    zones:
      Drive_Front:
        coordinates: 0,1,0,1,0.714,1,0.899,0.343,0.677,0.218,0.641,0.261,0.461,0.463
        objects: person
        filters:
          person:
            min_area: 4000
            max_area: 8000
            threshold: 0.7
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0,0,640,0,640,480,461,480,580,164,433,100,0,480
    review:
      alerts:
        required_zones: Drive_Front
      detections:
        required_zones: Drive_Front
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 360
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  # Optional: Threshold for camera activity to stop showing camera (default: shown below)
  # inactivity_threshold: 30
  # Optional: Configure the birdseye layout
  layout:
    # Optional: Scaling factor for the layout calculator (default: shown below)
    scaling_factor: 1.75

objects:
  track:
    - person

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image
  clean_copy: true
  # Optional: print a timestamp on the snapshots
  timestamp: false
  # Optional: draw bounding box on the snapshots
  bounding_box: true
  # Optional: crop the snapshot
  crop: false
  required_zones:
    - Drive_Front
    - Drive_Side
    - Garden_Zone
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuEye
    cameras: birdseye
```

### Relevant log output

```shell
No errors in any log
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

All Reolink RLC-520A cameras
