### DISCUSSION TITLE
Frigate 0,14: display bug with rotated go2rtc streams

### DISCUSSION THREAD

**Discussion by earion68** [blakeblackshear/frigate#13247] [Camera Support] [answered]
### Describe the problem you are having

I'm using h264 rtsp streams, rotated with go2rtc.
GPU is Intel integrated (gen 12).

On the live view, I see a diagonal bar on all the rotated streams as shown below, but only when the stream is live:
![2024-08-21 16_27_13](https://github.com/user-attachments/assets/9448a541-3277-49e8-a83f-38bb605986b4)

This did not happen under Frigate 0.13.

What am I doing wrong?

### Version

0.14.0

### Frigate config file

```yaml
go2rtc:
  # log:
  #  exec: trace
  # temp fix from https://github.com/AlexxIT/go2rtc/issues/152
  # no hardware rotation with the ffmpeg shipped in go2rtc 1.2
  # is fixed in v 1.6, but not in current frigate image
  ffmpeg:
    #global: "-hide_banner -hwaccel cuda -hwaccel_output_format nv12 -extra_hw_frames 2"
    global: -hide_banner   # -extra_hw_frames 2"
  streams:
    original_exterieur_est: # <- for RTSP streams
      - rtsp://admin:<redacted>@192.168.1.115/ch1/main
    rotated_exterieur_est: # <- for RTSP streams
      - ffmpeg:original_exterieur_est#video=h264#rotate=90#width=1080#height=1920#hardware
    original_exterieur_ouest:
      - rtsp://admin:<redacted>@192.168.1.116/ch1/main
    rotated_exterieur_ouest:
      - ffmpeg:original_exterieur_ouest#video=h264#rotate=90#width=1080#height=1920#hardware

cameras:
  exterieur_ouest:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/rotated_exterieur_ouest
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1080 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - cat

  exterieur_est:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/rotated_exterieur_est
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1080 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
    objects:
      track:
        - person
      filters:
        person:
          min_area: 3000
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
## for the rotated camera
root@0e970550b543:/opt/frigate# ffprobe rtsp://127.0.0.1:8554/rotated_exterieur_est
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x602fef31f140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/rotated_exterieur_est':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709/unknown/unknown, progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
root@0e970550b543:/opt/frigate# 

## for the original stream
root@0e970550b543:/opt/frigate# ffprobe rtsp://admin:<redacted>@192.168.1.115/ch1/main
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5c1fb3a2a140] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://admin:DSSFFC@192.168.1.115/ch1/main':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
root@0e970550b543:/opt/frigate#
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wireless

### Camera make and model

EZVIZ C3X

**Comment by NickM-27** [comment, marked as answer]
Add

```
live:
  stream_name: rotated_exterieur_ouest
```

To your cameras config so it uses the stream from go2rtc

**Reply by earion68** [reply]
Thanks so much, you were right it fixed the issue!

I also had to change
` ffmpeg:original_exterieur_ouest#video=h264#rotate=90#width=1080#height=1920#hardware`
to
`ffmpeg:original_exterieur_ouest#video=h264#rotate=90#hardware`

**Comment by gemminiss** [comment]
Hello

I'm having the same issue as @earion68 . But the solution that worked for him  does not work for me.

After several tests, I found that for me the #rotate=90#hardware in Go2TRC configuration does not work, but if I  put  only #rotate=90 (without #hardware) it works.

I would like to use hardware acceleration to reduce CPU, because I have 4 more cameras that Video should be rotated.

Can anyone help me?

The following conf does not work,  but as I said, replacing "ffmpeg:ErikLow#video=h264#rotate=90#hardware" by "ffmpeg:ErikLow#video=h264#rotate=90" make it works, but CPU usage rises
`
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

go2rtc:
  global: -hide_banner
  streams:
    ErikLow:
      - rtsp://admin:password@192.168.1.60:554/live/ch1
      - "ffmpeg:ErikLow#video=h264#audio=aac#hardware"
    ErikLowRotated:
      - "ffmpeg:ErikLow#video=h264#rotate=90#hardware"

cameras:

  Erik:
    ffmpeg:
      hwaccel_args: preset-vaapi #-hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://127.0.0.1:8554/ErikLowRotated # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    #detect:
        #enabled: True
        #width: 360 # <---- update for your camera's resolution
        #height: 640 # <---- update for your camera's resolution
    live:
      stream_name: ErikLowRotated
`

my conf:
Frigate as Homeassitant addon
HP T540 with AMD Ryzen™ R1305G

**Reply by NickM-27** [reply]
We will need to see the error logs when you use hardware

**Reply by gemminiss** [reply]
Ok, 

Thanks Nick for quick reply.

So, With the following configuration I get black screen on the camera View, but if I remove "#hardware" from here  

ffmpeg:ErikLow#video=h264#rotate=90#hardware

Then the video shows-up.

I also would like to notice that I have to comment 

#-hwaccel_device /dev/dri/renderD128

Otherwise does not work neither.

```
mqtt:
  host: 192.168.1.70
  port: 1883
  user: Sergio
  password: Password
  topic_prefix: frigate

logger:
  default: debug

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      #min_ratio: 0.5
      #max_ratio: 2.0
      min_score: 0.7
      threshold: 0.5

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

go2rtc:
  streams:
    ErikLow:
      - rtsp://admin:Password@192.168.1.60:554/live/ch1
      - ffmpeg:ErikLow#video=h264#hardware

    ErikLowRotated:
      - ffmpeg:ErikLow#video=h264#rotate=90#hardware

cameras:
  Erik:
    ffmpeg:
      hwaccel_args: preset-vaapi #-hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://127.0.0.1:8554/ErikLowRotated # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 360 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
    live:
      stream_name: ErikLowRotated

motion:
  threshold: 30
  improve_contrast: true

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

record:
  enabled: true
  expire_interval: 60
  sync_recordings: true
  retain:
    days: 5
    mode: all
  export:
    timelapse_args: -vf setpts=0.2*PTS -r 30
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 20
      mode: active_objects
      objects:
        person: 20
version: 0.14
```

Hereby the logs from go2rtc

is this what you need?

```
2024-09-21 14:17:21.337562755  [INFO] Preparing new go2rtc config...
2024-09-21 14:17:21.406186746  [INFO] Got IP address from supervisor: 192.168.1.70
2024-09-21 14:17:21.479442151  [INFO] Got WebRTC port from supervisor: 8555
2024-09-21 14:17:22.155022239  [INFO] Starting go2rtc...
2024-09-21 14:17:22.523416999  16:17:22.523 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-21 14:17:22.523445971  16:17:22.523 INF config path=/dev/shm/go2rtc.yaml
2024-09-21 14:17:22.524150309  16:17:22.523 INF [rtsp] listen addr=:8554
2024-09-21 14:17:22.524154145  16:17:22.523 INF [api] listen addr=:1984
2024-09-21 14:17:22.524274060  16:17:22.524 INF [webrtc] listen addr=:8555/tcp
2024-09-21 14:17:29.478630077  16:17:29.478 WRN [rtsp] error="streams: exec: [Parsed_transpose_vaapi_2 @ 0x558e5d42af40] VAAPI driver doesn't support transpose\n[Parsed_transpose_vaapi_2 @ 0x558e5d42af40] Failed to configure output pad on Parsed_transpose_vaapi_2\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #0:0\n" stream=ErikLowRotated
2024-09-21 14:17:31.331726199  [INFO] Starting go2rtc healthcheck service...
2024-09-21 14:17:49.784489991  16:17:49.784 WRN [rtsp] error="streams: exec: [Parsed_transpose_vaapi_2 @ 0x5589e4aa6780] VAAPI driver doesn't support transpose\n[Parsed_transpose_vaapi_2 @ 0x5589e4aa6780] Failed to configure output pad on Parsed_transpose_vaapi_2\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #0:0\n" stream=ErikLowRotated


```

**Reply by NickM-27** [reply]
> 2024-09-21 14:17:49.784489991  16:17:49.784 WRN [rtsp] error="streams: exec: [Parsed_transpose_vaapi_2 @ 0x5589e4aa6780] VAAPI driver doesn't support transpose\n[Parsed_transpose_vaapi_2 @ 0x5589e4aa6780] Failed to configure output pad on Parsed_transpose_vaapi_2\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #0:0\n" stream=ErikLowRotated

your hardware doesn't support the feature

**Comment by gemminiss** [comment]
thanks.

but the thing is that if I do not use go2rtc,  that I use only ffmpeg  with transpose=1  and hardware acceleration it works.

it would be then that is something only inside go2rtc thats is not suported on my wardware?

the following configuration works, but I get the diagonal line.


```
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

cameras:
  Erik: 
    ffmpeg:
      output_args:
        detect: -vf transpose=1 -f rawvideo -pix_fmt yuv420p
      inputs:
        - path: rtsp://admin:Password@192.168.1.60:554/live/ch1 # <----- The stream you want to use for 
          roles:
            - detect
            - record

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 360 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
```

**Reply by NickM-27** [reply]
Your hardware doesn't support transpose, in your example the transpose is being done in software and only the decoding is being done in hardware

**Reply by gemminiss** [reply]
OK, I thougth that as per above level 'hwaccel_args: -hwaccel vaapi', all the ffmpeg instructions would be hardware accelerated.

Then, following on my case, if I do software transpose, I still get the diagonal line. It is not inmediatly when starting the addon, the line appears after some time and disapears.

And when it appears, if I click on refresh the webpage, it desapears after refreshing (not always, but very often)

my frigate.yml

```
mqtt:
  host: 192.168.1.70
  port: 1883
  user: Sergio
  password: Password
  topic_prefix: frigate

logger:
  default: debug

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      #min_ratio: 0.5
      #max_ratio: 2.0
      min_score: 0.7
      threshold: 0.5

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

go2rtc:
  streams:
    PuertaLow:
      - rtsp://192.168.1.25:554/user=admin_password=Password_channel=0_stream=1.sdp?real_stream
      - ffmpeg:PuertaLow#video=h264#width=640#height=360#hardware

    PuertaLowRotated:
      - ffmpeg:PuertaLow#video=h264#rotate=90

cameras:
  Puerta:
    ffmpeg:
      hwaccel_args: preset-vaapi #-hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://127.0.0.1:8554/PuertaLowRotated # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 360 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
    live:
      stream_name: PuertaLowRotated

motion:
  threshold: 30
  improve_contrast: true

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

record:
  enabled: true
  expire_interval: 60
  sync_recordings: true
  retain:
    days: 5
    mode: all
  export:
    timelapse_args: -vf setpts=0.2*PTS -r 30
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 20
      mode: active_objects
      objects:
        person: 20
version: 0.14
```

The ffprobe output for the camera

`http://192.168.1.70:5000/api/ffprobe?paths=rtsp://192.168.1.25:554/user=admin_password=Password_channel=1_stream=1.sdp?real_stream`

```
0	
return_code	0
stderr	""
stdout	
programs	[]
streams	
0	
avg_frame_rate	"12/1"
codec_long_name	"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"
height	360
width	640
```

And the logs:

No Errors into go2rtc section

```
2024-09-23 14:10:26.469045690  [INFO] Preparing new go2rtc config...
2024-09-23 14:10:26.523954400  [INFO] Got IP address from supervisor: 192.168.1.70
2024-09-23 14:10:26.599116501  [INFO] Got WebRTC port from supervisor: 8555
2024-09-23 14:10:27.446326144  [INFO] Starting go2rtc...
2024-09-23 14:10:27.821340696  16:10:27.821 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-23 14:10:27.821375182  16:10:27.821 INF config path=/dev/shm/go2rtc.yaml
2024-09-23 14:10:27.822526017  16:10:27.822 INF [rtsp] listen addr=:8554
2024-09-23 14:10:27.822531267  16:10:27.822 INF [api] listen addr=:1984
2024-09-23 14:10:27.822855005  16:10:27.822 INF [webrtc] listen addr=:8555/tcp
2024-09-23 14:10:36.470680979  [INFO] Starting go2rtc healthcheck service...
```

If also tested with other resolutions, like:
 640x366 (Buffer dimension of the codec) -> the diagonal is still there, but there is less distortion in the image than in 640x360
or 640x370 (just for testing) ->  diagonal disapears, but there is strange blurry band on the rigth of the image

**Reply by NickM-27** [reply]
your resolutions need to be divisible by 4 since they are using yuv420p pixel format, that would be a good place to start

**Reply by gemminiss** [reply]
Thanks Nick, but  detect : width: 360 & height: 640 are divisible by 4 and I still get the diagonal line on all rotated cameras.  

As per ffprobe outcome ;  video resolution is 640 x 360, so I'would be detecting with the good resolution.

 I do not understand what can go wrong. 

When I Forced to resolution  372,640 , I found something strange.

When camera detects motion and UI goes live (with red dot) ,  no diagonal line and video has squared corners

![image](https://github.com/user-attachments/assets/cd5bc06f-a1da-4537-93d6-6562cfc5dd13)

But, When no motion, the picture has rounded corners and à blurry band.

![image](https://github.com/user-attachments/assets/15c97442-d025-4b1e-9742-42a3a1c349b7)

Could it be that something goes wrong with UI when making round corners to rotated Videos?

```
mqtt:
  host: 192.168.1.70
  port: 1883
  user: User
  password: Password
  topic_prefix: frigate

logger:
  default: debug

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      #min_ratio: 0.5
      #max_ratio: 2.0
      min_score: 0.7
      threshold: 0.5

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

go2rtc:
  streams:
    PuertaLow:
      - rtsp://admin:Password@192.168.1.60:554/live/ch1
      - ffmpeg:PuertaLow#video=h264#width=640#height=372#hardware

    PuertaLowRotated:
      - ffmpeg:PuertaLow#video=h264#rotate=90

cameras:
  Puerta:
    ffmpeg:
      hwaccel_args: preset-vaapi #-hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://127.0.0.1:8554/PuertaLowRotated # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 372 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
    live:
      stream_name: PuertaLowRotated

motion:
  threshold: 30
  improve_contrast: true

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

record:
  enabled: true
  expire_interval: 60
  sync_recordings: true
  retain:
    days: 5
    mode: all
  export:
    timelapse_args: -vf setpts=0.2*PTS -r 30
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 20
      mode: active_objects
      objects:
        person: 20
version: 0.14
```

**Comment by gemminiss** [comment]
Hello Nick.

I'm thinking that forcing the video resolution to another format just to get rid of the diagonal line, cannot be the way to go.

So I've changed the configuration file back to origin resolutions (640,360) and I continued testing.

What I found is,  if I enable the integrated go2rtc API (port 1984), the video stream for the rotated camera camera has no diagonal line.  Then, if this video flow is the one used for the UI, and in the UI I see the diagonal line -> something has to happen in-between :)

I also found that, rigth after starting Figates addon, there is no diaginal line for the first 10 seconds. After that the diagonal shows-up.

I'm not expert and I do not know any programming language but i Would like to propose a test for Frifate's Dev Team:

For rotated video streams, do not round corners, and see if the diagonal is still there.

Perhaps this test worths nothing, is just un idea to try to debug the why of the diagonal line.

EDIT: 
I've done another test. 

I downloaded the addon AlexxIT/go2rtc (Go2rtc version 1.9.4) and I created one camera flow:

in go2rtc.yml

`  Puerta2Rotated: ffmpeg:rtsp://192.168.1.25:554/user=admin_password=Password_channel=0_stream=1.sdp?real_stream#video=h264#width=640#heigth=360#rotate=90`

Using that link for detection makes also the diagonal line

in frigate.yml
```
  Puerta: #
    ffmpeg:

      inputs:
        - path: rtsp://192.168.1.70:8554/Puerta2Rotated # <----- The stream you want to use for 
          roles:
            - detect
            - record

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 360 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution

```
kind regards.
