### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by Volker2828** [blakeblackshear/frigate#13250] [Config Support]
### Describe the problem you are having

False dedection
![Frigate01](https://github.com/user-attachments/assets/c7bc7f3a-d9bc-4be0-a047-cdd259c328dd)
![Frigate02](https://github.com/user-attachments/assets/1241f1c0-5c97-473e-a27f-9c40e2b923d9)
![Frigate03](https://github.com/user-attachments/assets/cb29256f-970d-44de-bd91-5d5ecafc7256)
I hope someone can tell me why the lamp was dedectet.

### Version

14

### Frigate config file

```yaml
mqtt:
  host: 111111111 # mqttserver ohne port
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: 1111111 # mqttuser
  password: 111111111 # mqttpassword

database:
  path: /config/frigate.db

detectors:
  # coral:
  #   type: edgetpu
  #   device: usb
  cpu1:
    type: cpu
    num_threads: 3

birdseye:
  enabled: true
  restream: true
  mode: objects

go2rtc:
  streams:
    camera_haustuer:
      - rtsp://11111:11111@11111111/h264/ch1/av_stream

cameras:
  Kamera_Haustuer: # Kameraname
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://111111111:8554/camera_haustuer?video=copy&audio=aac # RTSP Stream High Res
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.70
          min_area: 5000
          max_area: 100000
          mask: 
            0.727,0.581,0.74,0.564,0.755,0.526,0.77,0.514,0.775,0.543,0.781,0.585,0.787,0.623,0.775,0.661,0.77,0.7,0.759,0.726,0.749,0.738,0.732,0.727,0.73,0.704,0.729,0.667,0.731,0.64,0.735,0.627
        cat:
          min_score: 0.8
        dog:
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 20
    record:
      enabled: true
      events:
        retain:
          default: 14


    live:
      stream_name: camera_haustuer
    motion:
      mask: 
        0,0.467,0.108,0.473,0.135,0.457,0.177,0.457,0.206,0.456,0.241,0.456,0.313,0.454,0.357,0.47,0.373,0.496,0.375,0.389,0.467,0.381,0.468,0.462,0.723,0.468,0.746,0.371,0.817,0.363,0.862,0.332,0.9,0.338,0.923,0.336,1,0.335,0.999,0.003,0.001,0.005
version: 0.14
```

### Relevant log output

```shell
no output
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)
