### DISCUSSION TITLE
[Config Support]:  Two cameras but getting message "Drive has high FFMPEG CPU usage (22%)"

### DISCUSSION THREAD

**Discussion by gtramsey2000** [blakeblackshear/frigate#13259] [Config Support] [answered]
### Describe the problem you are having

I've looked through a lot of the recommended config settings to try and solve this but I appreciate I may have made an error.  

I only have two cameras: a 4k camera on the drive (RLC-820A) and one on my front lawn (RLC-520A)
I also have a working Coral pcie on my motherboard.  

However, I'm constantly at about 18 - 22% CPU usage.  I've read some of the guides and understand that due to detections etc CPU usage may be higher than expected even with Coral support but I've also read some updates from people with triple the number of cameras pulling the same figures, so I wondered if there was some simple mistake I've made.  
I therefore get the error in the bottom right of the web UI saying "Drive has high FFMPEG CPU usage (22%)"

I've matched the pixel height and width of the camera on the config, as well as putting them both on 5 fps.  
For what it's worth, I've got it all running on my Ubuntu server, which has got some other services on it - however - without Frigate running (which I do via Portainer), the CPU usage is between 2 and 4%.  

I've tried disabling object detection on the "front" camera to decrease demand (again, possibly a misconfiguration on my part).
The only other detection I have is on the "drive" camera for people and cats.

Any assistance gratefully received.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  Drive: # <---  name assigned
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi # < --- leave this on as there will always be CPU/GPU use by frigate

      inputs:
        # high res stream
        - path: rtsp://admin:K0T7dKz9iZMVG3gDdDdx@192.168.0.8/Preview_01_main
          roles:
            - record
            - audio # < --- this allows audio on exports/recordings
        # low res stream
        - path: rtsp://admin:K0T7dKz9iZMVG3gDdDdx@192.168.0.8/Preview_01_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy

  

    detect:
      width: 3840
      height: 2160
      fps: 5
    objects:
      track:
        - person
        - cat

      mask:
        - 0.068,0.579,0.163,0.511,0.221,0.457,0.291,0.393,0.262,0.347,0.2,0.306,0.148,0.308,0.09,0.352,0.036,0.41,0.024,0.498
        - 0.156,0.003,0.406,0.007,0.407,0.141,0.192,0.13,0.159,0.124
        - 0.452,0.006,0.495,0.008,0.488,0.231,0.445,0.231
        - 0.75,0.03,0.847,0.066,0.834,0.209,0.745,0.185
        - 0.589,0.004,0.587,0.134,0.51,0.121,0.513,0.002
        - 0.094,0.474,0.324,0.333,0.481,0.521,0.236,0.791,0.187,0.819
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    motion: {}


  Front: # <---  name assigned
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi # < --- leave this on as there will always be CPU/GPU use by frigate

      inputs:
        # high res stream
        - path: rtsp://admin:u2UuLJy5BAjneyUhFSp6@192.168.0.11/Preview_01_main
          roles:
            - record
            - audio # < --- this allows audio on exports/recordings
        # low res stream
        - path: rtsp://admin:u2UuLJy5BAjneyUhFSp6@192.168.0.11/Preview_01_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy

 

    detect:
      enabled: false
      width: 2560
      height: 1920
      fps: 5

    objects:
      track:
        - person
      filters:
        person:
          mask: 0.587,0.012,0.608,0.105,0.999,0.544,0.997,0.004
      mask: 0.186,0.061,0.255,0.446,0.062,0.739,0.002,0.587,0.001,0.201
    motion:
      mask: 0.608,0.105,0.997,0.549,0.997,0.001,0.589,0.004


    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: motion


version: 0.14
```

### Relevant log output

```shell
Type
Timestamp
Tag
Message
info
2024-08-22 08:21:51
startup
Preparing Frigate...
info
2024-08-22 08:21:51
startup
Starting Frigate...
info
2024-08-22 08:21:53
frigate.app
Starting Frigate (0.14.0-da913d8)
info
2024-08-22 08:21:53
frigate.util.config
Checking if frigate config needs migration...
info
2024-08-22 08:21:53
frigate.util.config
frigate config does not need migration...
info
2024-08-22 08:21:53
frigate.util.services
Automatically detected vaapi hwaccel for video decoding
info
2024-08-22 08:21:53
peewee_migrate.logs
Starting migrations
info
2024-08-22 08:21:53
peewee_migrate.logs
There is nothing to migrate
info
2024-08-22 08:21:53
frigate.app
Recording process started: 406
info
2024-08-22 08:21:53
frigate.app
Recording process started: 407
info
2024-08-22 08:21:53
frigate.app
go2rtc process pid: 98
info
2024-08-22 08:21:53
detector.coral
Starting detection process: 434
info
2024-08-22 08:21:53
frigate.app
Output process started: 436
info
2024-08-22 08:21:53
frigate.detectors.plugins.edgetpu_tfl
Attempting to load TPU as pci
info
2024-08-22 08:21:53
frigate.detectors.plugins.edgetpu_tfl
TPU found
info
2024-08-22 08:21:53
frigate.app
Camera processor started for Drive: 463
info
2024-08-22 08:21:53
frigate.app
Camera processor started for Front: 464
info
2024-08-22 08:21:53
frigate.app
Capture process started for Drive: 465
info
2024-08-22 08:21:53
frigate.app
Capture process started for Front: 468
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

**Comment by hawkeye217** [comment, marked as answer]
Your `detect` resolution is very high. It does not need to match the resolution of your camera. If you lower it you should see a significant drop in CPU usage. Start by trying half of what you have now.

**Reply by gtramsey2000** [reply]
> Your `detect` resolution is very high. It does not need to match the resolution of your camera. If you lower it you should see a significant drop in CPU usage. Start by trying half of what you have now.

Thanks. I dropped all resolutions by 50% and it's gone down to 17% CPU, which is something.  I appreciate you taking the time to reply.

**Reply by hawkeye217** [reply]
Happy to help!

**Reply by hawkeye217** [reply]
To improve your live views to be more fluent and clear, I'd recommend setting up go2rtc: https://docs.frigate.video/configuration/live/

**Reply by gtramsey2000** [reply]
> Your `detect` resolution is very high. It does not need to match the resolution of your camera. If you lower it you should see a significant drop in CPU usage. Start by trying half of what you have now

> To improve your live views to be more fluent and clear, I'd recommend setting up go2rtc: https://docs.frigate.video/configuration/live/

Thanks - I'm trying to add the titles to the yaml as per the instructions;
go2rtc:
  streams:

But I don't seem to be having any luck.  Do I need to remove other parts to make it work?  I'm afraid it's not entirely clear from the config example linked from the Frigate docs.

**Reply by hawkeye217** [reply]
Paste what you have in your config now here and I'll take a look.

**Reply by hawkeye217** [reply]
Based on your original config at the top of the post, you need to do this:

```
go2rtc:
  streams:
    Drive: rtsp://admin:K0T7dKz9iZMVG3gDdDdx@192.168.0.8/Preview_01_main
    Drive_sub: rtsp://admin:K0T7dKz9iZMVG3gDdDdx@192.168.0.8/Preview_01_sub

cameras:
  Drive: # <---  name assigned
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi # < --- leave this on as there will always be CPU/GPU use by frigate

      inputs:
        # high res stream
        - path: rtsp://127.0.0.1:8554/Drive
          input_args: preset-rtsp-restream
          roles:
            - record
        # low res stream
        - path: rtsp://127.0.0.1:8554/Drive_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
```

This is just for the `Drive` cam, but you should do the same for your other cameras.
