### DISCUSSION TITLE
[Config Support]: Help setting masks/zones

### DISCUSSION THREAD

**Discussion by musapinar** [blakeblackshear/frigate#13254] [Config Support] [answered]
### Describe the problem you are having

Hello,
Reading the docs about masks/zones, I figured I was doing it wrong but I still struggle doing it properly in order to remove irrelevant alerts and without exhausting the cpu/edgetpu unnecessarily.

Here is the raw camera output :
![g0](https://github.com/user-attachments/assets/f69096fb-d37f-48ad-ac15-ba7ecea68d98)

I do not care about what happens within this red area (public property with cars, pedestrians, etc) : 
![ignore](https://github.com/user-attachments/assets/1e2a81c2-92cc-4ed6-a400-df990bb8bc64)

I care about everything in this green area (private property) : 
![car_person](https://github.com/user-attachments/assets/e6bd19ad-c4aa-401c-97f2-2b0a77f7e78f)

Pink area is a mailbox. An alert is expected if someone is interacting with it. I guess I'd have to rely on "loitering" ( > ~ 5sec) : 
![mail](https://github.com/user-attachments/assets/4732ade4-e8a6-4bac-8d50-03673d6cd743)

Should my red area remain a mask ?
This is my current config (+see yaml below) : 
![cfg](https://github.com/user-attachments/assets/07e63113-d45a-4ca5-a1e8-564d14a24a74)

What about the green area ? Should it be an object_zone ?
What about the pink area ?
What would the yaml look like (indentations/blocks) ? May I request an example with dummy coords ?

Thank you for your help.

### Version

 0.14.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  #host: 192.168.1.52
  host: core-mosquitto
  user: redacted
  password: redacted
  port: 1883

ffmpeg:
  hwaccel_args: auto

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: true
  width: 640
  height: 480
  fps: 5
objects:
  track:
    #- backpack
    #- bicycle
    #- bird
    #- bus
    #- car
    - cat
    - dog
    #- handbag
    #- motorcycle
    - person
    #- shoe
  filters:
    person:
      min_score: 0.5 # Optional: minimum score for the object to initiate tracking (default: 0.5)
      threshold: 0.7 # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      min_area: 800 # Optional: minimum width*height of the bounding box for the detected object (default: 0)
snapshots:
  enabled: true
  quality: 90 # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  timestamp: false
  bounding_box: true
  crop: true
  clean_copy: true
  retain:
    default: 30
record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      #mode: motion
      mode: active_objects
    pre_capture: 5
    post_capture: 5

go2rtc:
  streams:
    Garage:
      - rtsp://redacted:redacted@192.168.1.28:554/Streaming/channels/401
      - ffmpeg:Garage#audio=opus
    Garage_sub:
      - rtsp://redacted:redacted@192.168.1.28:554/Streaming/channels/402
      - ffmpeg:Garage_sub#audio=opus
    # redacted : more cameras
  webtorrent:
    shares:
      garage_sub:
        pwd: redacted
        src: Garage_sub
      # redacted : more cameras

cameras:
  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0.942,0.29,0.942,0.29,0.971,0,0.971 # timestamp
        - 0.417,0,0.246,0.213,0.14,0.383,0,0.759,0,0
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - bicycle
        - car
        - cat
        - dog
        - motorcycle
        - person

# redacted : more cameras

version: 0.14
```

### Relevant log output

```shell
Relevant log output : irrelevant
```

### Frigate stats

```json
Frigate stats : irrelevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

**Comment by NickM-27** [comment]
the only mask you should have in this scenario is on the timestamp. The green should be a zone marked as required for alerts in the camera settings tab and then the pink could be a separate zone with loitering time also marked as required for alerts in the camera settings tab

**Comment by musapinar** [comment]
I tried what you said for about 12 hours and I'm afraid this is not correct. I have been bombed with notifications.

Here is the relevant part of the actual config : 
```

detect:
  enabled: true
  width: 640
  height: 480
  fps: 5
objects:
  track:
    #- backpack
    - bicycle
    #- bird
    - bus
    - car
    - cat
    - dog
    #- handbag
    - motorcycle
    - person
    #- shoe
  filters:
    person:
      min_score: 0.5 # Optional: minimum score for the object to initiate tracking (default: 0.5)
      threshold: 0.7 # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      #min_area: 800 # Optional: minimum width*height of the bounding box for the detected object (default: 0)
snapshots:
  enabled: true
  quality: 90 # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  timestamp: false
  bounding_box: true
  crop: true
  clean_copy: true
  retain:
    default: 30
record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      #mode: motion
      mode: active_objects
    pre_capture: 5
    post_capture: 5

go2rtc:
  streams:
    Garage:
      - rtsp://redacted:redacted@192.168.1.28:554/Streaming/channels/401
      - ffmpeg:Garage#audio=opus
    Garage_sub:
      - rtsp://redacted:redacted@192.168.1.28:554/Streaming/channels/402
      - ffmpeg:Garage_sub#audio=opus

cameras:
  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0.935,0.295,0.935,0.295,0.980,0,0.980 # timestamp
        - 0.801,0,0.838,0.267,0.857,0.483,0.854,1,1,1,1,0 # façade
    zones:
      bal: # boîte à lettres
        coordinates: 0.149,0.295,0.222,0.445,0.304,0.324,0.231,0.17
        loitering_time: 5
        objects:
          - bicycle
          - car
          - motorcycle
          - person
      parvis:
        coordinates: 0,0.772,0.157,0.45,0.325,0.172,0.435,0,0.796,0,0.834,0.273,0.852,0.482,0.848,1,0,1
        objects:
          - bicycle
          - car
          - cat
          - dog
          - motorcycle
          - person
      vp: # voie publique
        coordinates: 0.43,0,0.338,0.142,0.153,0.446,0,0.759,0,0
    review:
      alerts:
        required_zones:
          - bal
          - parvis
    snapshots:
      required_zones:
        - bal
        - parvis

version: 0.14
```

This is what it looks like on the Firgate GUI : 
![debug](https://github.com/user-attachments/assets/67fbe1db-f23a-405e-838c-23f15b8e0908)
![masks](https://github.com/user-attachments/assets/840107ed-990b-45a8-851c-de6f944f9465)

I received countless irrelevant notifications, such as : 
![wtf1](https://github.com/user-attachments/assets/6cb043bf-9dac-424f-99b3-7c1921591f11)
![wtf2](https://github.com/user-attachments/assets/6be38861-3287-449c-9608-8ad4a5dbe040)

What is wrong with my config ? The bottom center of the bounding boxes of these objects are not even inside my defined required_zones, why do they fire alerts ?
