### DISCUSSION TITLE
[HW Accel Support]: go2rtc CPU usage

### DISCUSSION THREAD

**Discussion by avvalex** [blakeblackshear/frigate#13252] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hi, i would like to know if is it normal to have 20% under go2rtc process CPU usage with 10x cameras (5x 4MP and 5x 1080p), with HD stream used for recording and sub stream used for detect.
I have a J5040 CPU.
Thanks!!

### Version

System 0.14.0-da913d8

### Frigate config file

```yaml
...
ffmpeg:
  hwaccel_args: preset-vaapi
...
go2rtc:
  rtsp:
    username: xxxx
    password: xxxx
  streams:
    1:
      - rtsp://xxxx:xxxx@192.168.0.193:554/cam/realmonitor?channel=1&subtype=0
    1_sub:
      - rtsp://xxxx:xxxx@192.168.0.193:554/cam/realmonitor?channel=1&subtype=1
...
  webrtc:
    candidates:
      - 192.168.0.100:8555
      - stun:8555
...
cameras:
  1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxxx:xxxx@127.0.0.1:8554/1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxxx:xxxx@127.0.0.1:8554/1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate --restart=always --mount type=tmpfs,target=/tmp/cache,tmpfs-size=4000000000 --device /dev/dri/renderD128:/dev/dri/renderD128 --device /dev/apex_0:/dev/apex_0 --shm-size=1024m --cap-add=CAP_PERFMON -v /home/deb/video/media/frigate:/media/frigate -v /home/deb/frigate/config/:/config/ -v /etc/localtime:/etc/localtime:ro -e LIBVA_DRIVER_NAME=i965 -e FRIGATE_RTSP_PASSWORD='xxxx' -p 1984:1984 -p 8971:8971 -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp ghcr.io/blakeblackshear/frigate:stable
```

### Relevant log output

```shell
no errors
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker CLI

### Network connection

Mixed

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
You are restreaming both main and sub streams so yes, this does seem reasonable

**Reply by avvalex** [reply]
Is it adviced to restream both, as i currently do, or is it better another config?
I use it mainly with HA Frigate card (and sometimes with Frigate directly)

**Reply by NickM-27** [reply]
If you are using both outside of frigate that is fine, but if one of them is only used inside of frigate then there's no benefit to restreaming it.

**Reply by avvalex** [reply]
When i am outside i mainly use HA, with all cams set to show low res with 1 second update, and if i want to watch something i switch to high res stream, so i think it's better to restream both.
Another thing i've noticed is that every cam uses some CPU for detect... Is there a way to completely disable detect for some cams? (If i don't need motion detection and object detection, but only 24/24 recording). Even if i mask entire frame, i've got about 1% CPU usage for each cam.... In HA i see a switch for disabling "motion", but i don't know what it does...

**Reply by NickM-27** [reply, marked as answer]
yes you can disable motion and object detection

```
cameras:
  the_camera:
    detect:
      enabled: false
    motion:
      enabled: false
```
