### DISCUSSION TITLE
Storage utilisation showing 35692%

### DISCUSSION THREAD

**Discussion by paulhollands** [blakeblackshear/frigate#13262] [General]
Hi.

I upgraded to a larger and faster storage, but it now seems like the % used calculation is broken and reporting 35692% utilised.

It seems to be causing continued maintenance processing and the logs full of 1 hr left messages

Anyone have any ideas how I can reset this? 
![Screenshot 2024-08-22 at 11 40 20](https://github.com/user-attachments/assets/caf86ce0-f7f5-4e5f-bca8-ed84def6b9ae)

**Comment by hawkeye217** [comment]
What is your docker compose?

**Reply by paulhollands** [reply]
Hi.

It looks like this;

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0
    shm_size: "99mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/usbfrigate/frigate/config:/config
      - /media/usbfrigate/frigate/media/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```
