### DISCUSSION TITLE
[Support]:

### DISCUSSION THREAD

**Discussion by rudak** [blakeblackshear/frigate#13274] [General Support] [answered]
### Describe the problem you are having

**Issue Description:**

I'm experiencing a problem where, as shown in the attached image, the colors in the preview are not aligned correctly with the image—they're skewed, forming a diagonal offset that corresponds to the triangle visible on the bottom right. Additionally, any detection rectangle is also skewed.

Fortunately, this issue does not occur in the recorded video but only during detection. When I revert back to Frigate v13, everything works fine.

I'm unsure what parameter might be causing this anomaly, but if you have any suggestions for a fix, it would be greatly appreciated. Thanks in advance!
![image](https://github.com/user-attachments/assets/baca4825-05c7-4654-ad0a-8476e9b815c9)

![image](https://github.com/user-attachments/assets/9255ef99-5029-43bf-8fe0-b0b43360c253)

i've seen [an issue](https://github.com/blakeblackshear/frigate/discussions/13092) that talks about a similar problem but it works very well on v13 so there must be a solution, that's why i'm posting this issue anyway.

### Version

System 0.14.0-da913d8

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral1:
    type: edgetpu
    device: usb:0

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  camera_devant_1:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxxxx@xxxxxxxxxx:554/stream1
          roles:
            - record
        - path: rtsp://xxxxxxxx:xxxxxx@xxxxxx:554/substream
          roles:
            - detect
    detect:
      enabled: true
      width: 800
      height: 448
      fps: 5
      stationary:
        interval: 1
        threshold: 50
    record:
      enabled: true
      retain:
        days: 4
        mode: motion
    motion:
      mask:
        - 0,0,0,0.375,0.111,0.219,0.229,0.083,0.371,0.053,0.535,0.044,0.603,0.05,0.808,0.072,0.82,0.142,0.967,0.18,0.97,0.094,1,0.128,1,0
        - 0,0.665,0,1,0.269,1
    zones:
      devant:
        coordinates: 
          0.274,1,1,1,1,0.132,0.972,0.106,0.967,0.188,0.819,0.149,0.81,0.079,0.637,0.047,0.371,0.057,0.233,0.078,0,0.364,0,0.449,0.044,0.507,0.026,0.69
        objects: person
        filters:
          person:
            min_area: 2000
          car:
            mask:
              - 0,130,46,185,207,237,282,194,386,57,341,21,158,33
        inertia: 3
        loitering_time: 2
    birdseye:
      mode: objects

    review:
      alerts:
        required_zones: devant

version: 0.14
```

### Relevant log output

```shell
error
2024-08-22 10:00:25
frigate.video
camera_devant_1: Unable to read frames from ffmpeg process.
error
2024-08-22 10:00:25
frigate.video
camera_devant_1: ffmpeg process is not running. exiting capture thread...
error
2024-08-22 10:00:30
watchdog.camera_devant_1
Ffmpeg process crashed unexpectedly for camera_devant_2.
error
2024-08-22 10:00:30
watchdog.camera_devant_1
The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

```shell
(it causes this problem on several different cameras)
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

several different cameras

**Comment by hawkeye217** [comment]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Usage question 15.

**Comment by hawkeye217** [comment]
My guess is that your resolution should be 800x450, not 800x448.

**Reply by rudak** [reply]
![image](https://github.com/user-attachments/assets/2edbe1b0-d62b-454d-8a69-9b14714f725a)

**Reply by hawkeye217** [reply]
What happens if you set the resolution in your frigate config to 800x450 though? We've found that some cameras actually misreport the resolution they send.

If setting your `detect` width and height to 800x450 doesn't work, you should set up go2rtc for your live views. The experience will be vastly better, even if 800x450 does work.

https://docs.frigate.video/configuration/live/

**Reply by rudak** [reply]
![image](https://github.com/user-attachments/assets/d3cc890e-b08b-495d-b28e-d012a451fba2)
no, unfortunately it's even worse

**Reply by NickM-27** [reply]
to be clear the issue here is that the camera is using a nonstandard aspect ratio, 800x448 is a 25:14 aspect ratio. That is why the suggestion was to use 800x450 which is 16:9 however this seems to be an issue still. The suggestion would be to use go2rtc like Josh mentioned above

**Reply by hawkeye217** [reply, marked as answer]
Alright. go2rtc is your best bet then.

**Reply by rudak** [reply]
![image](https://github.com/user-attachments/assets/6eeb4861-69ab-43af-a1ce-ca9a190af8c8)
vlc sends me this configuration, so it's the right size.

**Reply by hawkeye217** [reply]
```
go2rtc:
  streams:
    camera_devant_1: rtsp://xxxxx:xxxxxxx@xxxxxxxxxx:554/stream1
    camera_devant_1_sub: rtsp://xxxxxxxx:xxxxxx@xxxxxx:554/substream

cameras:
  camera_devant_1:
    ffmpeg:
      inputs:
        - path: http://127.0.0.1:8554/camera_devant_1
          roles:
            - record
        - path: http://127.0.0.1:8554/camera_devant_1_sub
          roles:
            - detect
```
