### DISCUSSION TITLE
[Config Support]: Onvif host env var substitution

### DISCUSSION THREAD

**Discussion by oddfrost** [blakeblackshear/frigate#13270] [Config Support] [answered]
### Describe the problem you are having

ONVIF host field does't support environment variables 

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt-broker
  user: ***
  password: ***

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error

ffmpeg:
  hwaccel_args: preset-rk-h265
  output_args:
    record: preset-record-generic-audio-aac

detectors: # required
  rknn: # required
    type: rknn # required
    core_mask: 0b111

model: # required
  # name of yolov8 model or path to your own .rknn model file
  # possible values are:
  # - default-yolov8n
  # - default-yolov8s
  # - default-yolov8m
  # - default-yolov8l
  # - default-yolov8x
  # - /config/model_cache/rknn/your_custom_model.rknn
  path: deci-fp16-yolonas_s
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc
  labelmap_path: /labelmap.txt

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog
    - bird

  filters:
    person:
      threshold: 0.65

    car:
      threshold: 0.6

    motorcycle:
      threshold: 0.6

    bicycle:
      threshold: 0.6


snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

go2rtc:
  streams:
    main:
      "rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_MAIN_CAMERA}/cam/realmonitor?channel=1&subtype=0&video=h265/rk"

record:
  enabled: true
  export:
    timelapse_args: -vf setpts=0.3*PTS -r 30
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 0
      mode: motion

cameras:
  main: # <--- this will be changed to your actual camera later
    enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 500
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
        - car
        - honk
        - car_alarm
        - car_passing_by
        - motor_vehicle
        - engine
      filters:
        speech:
          threshold: 0.8
        bark:
          threshold: 0.8
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_MAIN_CAMERA}/cam/realmonitor?channel=1&subtype=1"
          input_args: preset-rtsp-generic
          roles:
            - detect
            - audio
        - path: "rtsp://127.0.0.1:8554/main"
          input_args: preset-rtsp-generic
          roles:
            - record
    onvif:
      host: '{FRIGATE_MAIN_CAMERA}'
      port: 80
      user: '{FRIGATE_CAMERA_USER}'
      password: '{FRIGATE_CAMERA_PASSWORD}'
      autotracking:
        enabled: False
        calibrate_on_startup: True
        zooming: relative
        track:
          - motion
        return_preset: home

version: 0.14
```

### Relevant log output

```shell
2024-08-22 12:32:23.631611650  [tcp @ 0x2b822350] Failed to resolve hostname {FRIGATE_MAIN_CAMERA}: Name or service not known
2024-08-22 12:32:23.659058959  [2024-08-22 15:32:23] peewee_migrate.logs            INFO    : Starting migrations
2024-08-22 12:32:23.690145748  [2024-08-22 15:32:23] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-22 12:32:23.841256879  [2024-08-22 15:32:23] frigate.ptz.onvif              ERROR   : Onvif connection to main failed: Unknown error: HTTPConnectionPool(host='%7bfrigate_main_camera%7d', port=80): Max retries exceeded with url: /onvif/device_service (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8b0a1280>: Failed to resolve '%7bfrigate_main_camera%7d' ([Errno -2] Name or service not known)"))
```

### Frigate stats

```json
{"cameras":{"main":{"audio_dBFS":-54.0671,"audio_rms":64.8773,"camera_fps":5.0,"capture_pid":413,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":435,"pid":411,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"117":{"cmdline":"python3 -u -m frigate","cpu":"1.9","cpu_average":"2","mem":"2.8"},"119":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"126":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1671":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"168":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1690":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"18":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"185":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"331":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"364":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.5"},"366":{"cmdline":"frigate.recording_manager","cpu":"0.3","cpu_average":"0","mem":"1.8"},"368":{"cmdline":"frigate.review_segment_manager","cpu":"0.2","cpu_average":"0","mem":"1.6"},"394":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(56)","cpu":"0.2","cpu_average":"0","mem":"0.1"},"395":{"cmdline":"frigate.detector.rknn","cpu":"0.1","cpu_average":"0","mem":"2.9"},"397":{"cmdline":"frigate.output       ","cpu":"1.4","cpu_average":"0","mem":"1.8"},"411":{"cmdline":"frigate.process:main ","cpu":"3.1","cpu_average":"3","mem":"1.9"},"412":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"413":{"cmdline":"frigate.capture:main ","cpu":"3.1","cpu_average":"2","mem":"1.8"},"416":{"cmdline":"frigate.audio_manager","cpu":"0.3","cpu_average":"0","mem":"1.8"},"433":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"435":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel rkmpp -hwaccel_output_format drm_prime -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.10.58/cam/realmonitor?channel=1&subtype=1 -r 5 -vf scale_rkrga=w=1280:h=720:format=yuv420p:force_original_aspect_ratio=0,hwmap=mode=read,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.2","cpu_average":"3","mem":"0.7"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"451":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel rkmpp -hwaccel_output_format drm_prime -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/main@%Y%m%d%H%M%S%z.mp4","cpu":"4.5","cpu_average":"4","mem":"0.5"},"452":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.10.58/cam/realmonitor?channel=1&subtype=1 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.7","cpu_average":"0","mem":"0.4"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"2.4","cpu_average":"2","mem":"0.2"},"frigate.full_system":{"cpu":"7.7","mem":"30.8"}},"detection_fps":0.0,"detectors":{"rknn":{"detection_start":0.0,"inference_speed":31.91,"pid":395}},"processes":{"audio_detector":{"pid":416},"go2rtc":{"pid":98},"logger":{"pid":364},"recording":{"pid":366},"review_segment":{"pid":368}},"service":{"last_updated":1724330736,"latest_version":"0.14.0","storage":{"/dev/shm":{"free":509.8,"mount_type":"tmpfs","total":512.0,"used":2.2},"/media/frigate/clips":{"free":1781003.5,"mount_type":"ext4","total":1876685.3,"used":279.3},"/media/frigate/recordings":{"free":1781003.5,"mount_type":"ext4","total":1876685.3,"used":279.3},"/tmp/cache":{"free":949.9,"mount_type":"tmpfs","total":953.7,"used":3.8}},"temperatures":{},"uptime":626,"version":"0.14.0-da913d8"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

RKNN

### Any other information that may be helpful

Host ONVIF config part not supports templates (env variables)
This is not working:
```yml
cameras:
  my_camera_name:
    onvif:
      host: '{FRIGATE_MAIN_CAMERA}'
      port: 80
      user: '{FRIGATE_CAMERA_USER}'
      password: '{FRIGATE_CAMERA_PASSWORD}'
```

This is working:
```yml
cameras:
  my_camera_name:
    onvif:
      host: 192.168.1.111
      port: 80
      user: '{FRIGATE_CAMERA_USER}'
      password: '{FRIGATE_CAMERA_PASSWORD}'
```

You can see log output, looks like it wasn't resolved. Double quotes not working too.

P.S.
Thank you for your work!
