### DISCUSSION TITLE
[Config Support]: differences between two configurations

### DISCUSSION THREAD

**Discussion by NadeoGolf** [blakeblackshear/frigate#13281] [Ask A Question] [answered]
### What is your question:

Hello,

I can't understand the difference between these two configurations. To me, they do the same thing.

```
record:
  enabled: True
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 10
      mode: active_objects
```

```
record:
  enabled: True
  events:
    retain:
      default: 10
```
