### DISCUSSION TITLE
[Detector Support]: N100 and slow OpenVino

### DISCUSSION THREAD

**Discussion by maniel** [blakeblackshear/frigate#13284] [Detector Support]
### Describe the problem you are having

Hello
I'm getting low performance in OpenVino, the hardware is N100 based Aoostar R1. The inference takes about 60ms on GPU, weird thing is CPU is faster:
![image](https://github.com/user-attachments/assets/0ab7d3e4-7b32-4a6d-850d-7269433de927)
i tried it separate (device: CPU vs device: GPU), the results are the same, so it's not like both fight eachother for resources, the gpu usage is low too:
![image](https://github.com/user-attachments/assets/f36fe82e-fb5a-4d75-b596-d23ca8d12a5a)

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false

tls:
  enabled: false

detectors:
  openvino-cpu:
    type: openvino
    device: CPU
  openvino-gpu:
    type: openvino
    device: GPU

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - crying
    - gunshot

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  kamerka: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.214/0/av1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:@192.168.1.214/0/av0
          roles:
            - record
            - audio
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 640
      height: 352
    objects:
      track:
        - person
    motion:
      mask: 0.01,0.079,0.262,0.084,0.258,0.027,0.011,0.021

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/frigatecache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "redacted"
```

### Relevant log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

OpenVino

### Any other information that may be helpful

the platform is DSM 7.2 on xpenology, so the kernel version is 5.10.55 and i can't really do anything about it (except migrating to different platform), but the drivers are available, i successfully use vaapi in this container, qsv works in containereized jellyfin and immich, openvino works in immich container too
