### DISCUSSION TITLE
[HW Accel Support]: High GPU Memory usage

### DISCUSSION THREAD

**Discussion by kobelka** [blakeblackshear/frigate#13293] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Despite coral TPU, I have high GPU memory consumption. Is that normal?
![image](https://github.com/user-attachments/assets/8b7ad7fe-c8db-4db6-abe5-102ff4f1e816)

### Version

0.14.0

### Frigate config file

```yaml
# Frigate Configuration file
# Defaults: https://docs.frigate.video/configuration/#full-configuration-reference

# MQTT needed for Smart Home Applications 
mqtt:
  host: 10.11.1.236 # <---- same mqtt broker that home assistant uses
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
#ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
#  live_mode: webrtc
detectors:
  coral:
    type: edgetpu
    #device: pci
# Hardware acceleration of video conversion
ffmpeg:
  # global hwaccel args
  hwaccel_args: preset-vaapi
  #hwaccel_args: preset-intel-qsv-h265


database:
  path: /config/frigate.db

# Overview of all cameras https://frigate.video/images/birdseye-2-optimized.jpg
birdseye:
  enabled: true
  mode: objects
  restream: true

# Snapshots of events
snapshots:
  # Enable writing jpg snapshot to /media/frigate/clips
  enabled: true
  # print a timestamp on the snapshots
  timestamp: true

# List of objects to capture https://docs.frigate.video/configuration/objects/
objects:
  track:
    - car
    - person
    - cat
    - dog
    - bicycle
    - eye glasses
    - backpack
    - handbag

go2rtc:
  log:
    exec: trace
  ffmpeg:
    input_mulaw: -f mulaw -ar 8000 -i {input}
    noise_filter: -af highpass=200,lowpass=3000,afftdn
  streams:
    carportcam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.70:88/videoMain
      - ffmpeg:carportcam#audio=aac
    carportcam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.70:88/videoSub # <- stream which supports video & aac audio.
      - ffmpeg:carportcam_sub#audio=aac   # <- copy of the stream which transcodes audio to opus for webrtc 
    haustuercam:
      - rtsp://10.11.1.71/mpeg/media.amp#media=video
      - ffmpeg:http://10.11.1.71/bha-api/bha-api/audio-receive.cgi#media=audio#backchannel=0#input=input_mulaw#audio=opus#audio=noise_filter
    hausseitecam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.72:88/videoMain
      - ffmpeg:hausseitecam#audio=aac
    hausseitecam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.72:88/videoSub # <- stream which supports video & aac audio.
      - ffmpeg:hausseitecam_sub#audio=aac
    werkstattcam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.76/stream1
      - ffmpeg:werkstattcam#audio=aac
    werkstattcam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.76/stream1 # <- stream which supports video & aac audio.
      - ffmpeg:werkstattcam_sub#audio=aac   # <- copy of the stream which transcodes audio to opus for webrtc        
    terrassecam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.75:88/videoMain
      - ffmpeg:hausseitecam_sub#audio=aac
    terrassecam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.75:88/videoSub # <- stream which supports video & aac audio.
      - ffmpeg:hausseitecam_sub#audio=aac
    babycam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.77/live0
      - ffmpeg:babycam#audio=opus
    babycam_onvif:
      - onvif://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.77
    babycam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.77/live0 # <- stream which supports video & aac audio.
      - ffmpeg:babycam_sub#audio=opus   # <- copy of the stream which transcodes audio to opus for webrtc              
    gartencam:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.73:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:gartencam#video=h264#audio=aac
    gartencam_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.73:554/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:gartencam#video=h264#audio=aac
    webrtc:
    candidates:
      - 10.11.1.3:8555
      - stun:8555
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

# List of cameras
cameras:
  carportcam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/carportcam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/carportcam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: carportcam_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      required_zones:
        - pforte
        - auffahrt
        - komplett
    zones:
      auffahrt:
        coordinates: 479,195,874,720,1280,720,1280,142,1095,81,974,103,837,82,817,238,644,242
        objects:
          - car
      komplett:
        coordinates: 1280,0,1280,720,0,720,42,238,140,38,210,27,213,0
        objects:
          - person
          - cat
          - dog
          - bicycle
          - eye glasses
          - backpack
          - handbag
    motion:
      mask:
        - 1280,0,936,0,929,64,1089,104,1280,157
        - 308,280,21,672,0,350,269,165,254,0,532,0,543,82,382,99,398,192,557,184,552,267
        - 508,51,829,54,821,103,778,246,699,130,635,130,505,136
    objects:
      filters:
        person:
          mask: 487,143,521,138,519,63,486,68
    

#    review:
#      alerts:
#        required_zones:
#          - pforte
#          - auffahrt
#          - komplett
  haustuercam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://10.11.1.3:8554/haustuercam?video=all&audio=all
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      komplett:
        coordinates: 0,720,1280,720,1280,0,0,0
        objects:
          - person
          - cat
          - dog
          - bicycle
          - eye glasses
          - backpack
          - handbag
    snapshots:
      required_zones:
        - komplett
   
    live:
      stream_name: haustuercam
    detect:
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        required_zones:
          - komplett
  hausseitecam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/hausseitecam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/hausseitecam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
   
    live:
      stream_name: hausseitecam_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 988,720,1280,720,1280,586,1280,411,1136,271,1055,201,907,107,758,34,715,123
  werkstattcam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/werkstattcam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/werkstattcam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: werkstattcam_sub
    snapshots:
      required_zones:
        - autowerkstatt
        - komplett
    zones:
      autowerkstatt:
        coordinates: 609,94,612,0,909,0,928,80,911,289,0,202,91,96
        objects:
          - car
      komplett:
        coordinates: 1280,0,421,0,405,32,0,37,0,720,1280,720
        objects:
          - person
          - cat
          - dog
          - bicycle
          - eye glasses
          - backpack
          - handbag
    motion:
      mask:
        - 338,237,0,622,0,94,277,0
    review:
      alerts:
        required_zones:
          - autowerkstatt
          - komplett
  terrassecam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/terrassecam?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/terrassecam_sub?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
 
    motion:
      mask:
        - 338,237,0,622,0,94,277,0
    record:
      events:
        objects:
          - person
          - cat
          - dog
          - bicycle
          - eye glasses
          - backpack
          - handbag
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: terrassecam_sub
    objects:
      filters:
        handbag:
          threshold: 0.8
        person:
          threshold: 0.76
  gartencam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/gartencam?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/gartencam_sub?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask:
        - 144,284,152,531,57,720,0,720,0,94,0,0,319,0
    snapshots:
      required_zones:
        - komplett
    zones:
      komplett:
        coordinates: 0,720,1280,720,1280,0,0,0
        objects:
          - person
          - cat
          - dog
          - bicycle
          - eye glasses
          - backpack
          - handbag



    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: gartencam_sub
    objects:
      filters:
        handbag:
          threshold: 0.8
        person:
          threshold: 0.76

    review:
      alerts:
        required_zones:
          - komplett
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
Name:
frigate
Beschreibung:
A complete and local NVR designed for Home Assistant with AI object detection. Uses OpenCV and Tensorflow to perform realtime object detection locally for IP cameras.

You cas use a integrated or dedicated GPU (Intel/AMD/Nvidia) to perform the image decoding of the input streams of your cameras.

Optionally (but highly recommended), you can use multiple devices to perform the object detetion, such as a Google Coral Accelerator Nvidia GPU, OpenVINO (Intel GPU) and Intel NCS2 VPU

See the documentation for more details about your specific hardware and needs (https://docs.frigate.video/). This is a general templeate that aims to give a fast deoplyment for every user so check all the options carefully and remove all the configurations that you are not going to use.
Zusätzliche Anforderungen:
<br>- A valid config.yml file must exist in the config directory to startup the container.<br>- If you are using a Coral Detector, you must set the container to privileged mode under advanced view<br>- If you are using a PCI Coral instead of a USB one, you must install first the needed drivers going to the CA app and searching for Coral-Driver (thanks to @ich777)<br>- If you want to use a NVidia card to image decoding and/or detection, you must first install the drivers from CA app (thanks to @ich777), add &quot;--runtime=nvidia&quot; as extra parameter under advanced view and set the &quot;Nvidia Visible Devices&quot; variable with your &quot;GPU UUID&quot; as the value.<br>- If you want to use the NVidia TensorRT Detector, you have to select the correspondig NVIDIA branch.<br>- If you want to use a AMD GPU to image decoding you must change driver to &quot;radeonsi&quot;<br>- With some of the Intel processors, like the J4125, the default driver &quot;iHD&quot; doesn't seem to work correctly for hardware acceleration. You may need to change the driver to &quot;i965&quot;<br>- If you want to use a NCS2 as detector you have to add &quot;--device-cgroup-rule='c 189:\* rmw'&quot; as extra parameter under advanced view and install the &quot;udev rule&quot; in the unraid host.
Quelle:
ghcr.io/blakeblackshear/frigate:stable
Kategorien:
Heimautomation, Sicherheit
Kategorien
Sicherung
Cloud
Kryptowährung
Download-Tools
Treiber
Spiele-Server
Heimautomation
Produktivität
Sicherheit
Werkzeuge
Andere
Medien-App
Medien-App:Video
Medien-App:Musik
Medien-App:Bücher
Medien-App:Fotos
Medien-App:Andere
Medien-Server
Medien-Server:Video
Medien-Server:Musik
Medien-Server:Bücher
Medien-Server:Fotos
Medien-Server:Andere
Netzwerk
Netzwerk:Web
Netzwerk:DNS
Netzwerk:FTP
Netzwerk:Proxy
Netzwerk:VoIP
Netzwerk:Management
Netzwerk:Messenger
Netzwerk:VPN
Netzwerk:Privacy
Netzwerk:Andere
Development Status
Status:Stabil
Status:Beta
...schließen
Hilfe-Forenbeitrag:
https://forums.unraid.net/topic/98064-support-blakeblackshear-frigate/
Projektseite:
https://frigate.video/
Zuerst lesen:
Registry URL:
https://github.com/blakeblackshear/frigate/pkgs/container/frigate
Symbol-URL:
https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png
WebUI:
http://[IP]:[PORT:5000]
Extra Parameter:
--shm-size=512mb --mount type=tmpfs,target=/tmp/cache,tmpfs-size=10000000000 --restart unless-stopped
Post-Argumente:
CPU Zuweisung:
CPU:
HT:
Netzwerktyp:

Custom : br0
Statische IP-Adresse (Optional):
10.11.1.3
Subnet: 10.11.1.0/24
Konsole:

Shell
Privilegierte Rechte:
An
Config Path:
/mnt/user/appdata/frigate
BearbeitenEntfernen
Container Path: /config

Media path:
/mnt/user/Kameras/
BearbeitenEntfernen
Container Path: /media/frigate

HTTP port:
5000
BearbeitenEntfernen
Container Port: 5000

RTSP port:
8554
BearbeitenEntfernen
Container Port: 8554

Frigate RTSP Password:
7CYCi1MixmnO
BearbeitenEntfernen
Container Variable: FRIGATE_RTSP_PASSWORD

Frigate+ API key:
BearbeitenEntfernen
Container Variable: PLUS_API_KEY
Optional: Enter the frigate+ API key or remove this if you are not using it
go2rtc TCP port:
8555
BearbeitenEntfernen
Container Port: 8555
If you are not going to use MSE/WebRCT you can remove all the WebRTC entrys
go2rtc UDP port:
8555
BearbeitenEntfernen
Container Port: 8555
If you are not going to use MSE/WebRCT you can remove all the WebRTC entrys
go2rtc server port:
1984
BearbeitenEntfernen
Container Port: 1984
For Home Assistant WebRTC integration. Remove this if you are not using it.
Frigate RTSP User:
••••••••••••
BearbeitenEntfernen
Container Variable: FRIGATE_RTSP_USER

Frigate mqtt User:
mqttuser
BearbeitenEntfernen
Container Variable: FRIGATE_MQTT_USER

Frigate matt Password:
••••••••••••
BearbeitenEntfernen
Container Variable: FRIGATE_MQTT_PASSWORD

Coral TPU/NCS2 Mapping:
/dev/apex_0
BearbeitenEntfernen
Container Device:
Use /dev/bus/usb for USB devices and /dev/apex_0 for PCIe devices (you must install the drivers first for PCIe devices). Remove this if you are not using it.
Intel/AMD GPU mapping:
/dev/dri/renderD128
BearbeitenEntfernen
Container Device:
Intel/AMD GPU mapping for image decode (and detection with Intel OpenVINO). Remove this if you are not using it.
Driver for Intel/AMD GPUs:
radeonsi
BearbeitenEntfernen
Container Variable: LIBVA_DRIVER_NAME
(Intel = iHD or i965 and AMD = radeonsi). Remove this if you are not using it.
 
 Mehr Einstellungen ausblenden ...
Localtime:
/etc/localtime
```

### Relevant Frigate log output

```shell
siehe Screenshot
```

### Relevant go2rtc log output

```shell
...
```

### FFprobe output from your camera

```shell
...
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

six cameras

### Screenshots of the Frigate UI's System metrics pages and any other screenshots pertinent to your issue.

![image](https://github.com/user-attachments/assets/2364be66-2c55-4a09-8f53-c3d464bd1ebf)

### Any other information that may be helpful

Return Code: 0

Process Output:

vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Mesa Gallium driver 22.3.6 for AMD Radeon Graphics (renoir, LLVM 15.0.6, DRM 3.49, 6.1.99-Unraid)
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileVC1Simple : VAEntrypointVLD
VAProfileVC1Main : VAEntrypointVLD
VAProfileVC1Advanced : VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSlice
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileHEVCMain10 : VAEntrypointEncSlice
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileVP9Profile0 : VAEntrypointVLD
VAProfileVP9Profile2 : VAEntrypointVLD
VAProfileNone : VAEntrypointVideoProc
