### DISCUSSION TITLE
Not recording events

### DISCUSSION THREAD

**Discussion by Sprinarkus** [blakeblackshear/frigate#13307] [Config Support] [answered]
### Describe the problem you are having

Not sure if its my config. Cameras are up and running, motion is being detected fine, but nothing will record(nothing shows up as alerts or detections in Review panel)  TensorRT Version is 8. Debug says everything is fine. Just trying to record when an object is present. Started off with just tracking a person and walking out in front of the camera and nothing happens in events. 

Started with 'record: all' 'events: motion' and changed it to what my config says now thinking that might be it.

Any help is appreciated. Ive had an earlier version up and running in the past, so im not completely out of my element with troubleshooting this, just no idea what direction to go at this point.

Its probably something simple ive overlooked...

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false

logger:
  default: debug


detectors:
  GPU:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  width: 320
  height: 320

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0


record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects
    pre_capture: 5
    post_capture: 10


review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - person

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true

cameras:
  FrontYard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://camera/h265Preview_01_main
          roles:
            - detect
            - record
    motion:
      mask: 0.047,0.052,0.229,0,0.366,0.004,0.252,0.133,0.042,0.124
    objects:
      track:
        - person
  BackYard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://camera/h265Preview_01_main
          roles:
            - detect
            - record

    motion:
      threshold: 55
      contour_area: 30
      improve_contrast: true
      mask: 0.135,0.097,0.58,0.039,0.902,0.056,0.778,0.152
    objects:
      track:
        - person
  Sidegate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://camera/h265Preview_01_main
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
  Doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://camera/h265Preview_01_main
          roles:
            - detect
            - record

    motion:
      mask: 0.532,0.243,0.568,0.444,0.735,0.469,0.841,0.236
    objects:
      track:
        - person
        - package


version: 0.14
```

### Relevant Frigate log output

```shell
no errors in debug mode
```

### Relevant go2rtc log output

```shell
no errors in info
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

Detector Inference Speed
GPU
10.7ms
Detector CPU Usage
GPU
10.1%
Detector Memory Usage
GPU
1.5%
GPUs
GPU Usage
NVIDIA GeForce GTX 1060 6GB
3.0%
GPU Memory
NVIDIA GeForce GTX 1060 6GB
28.87%
Other Processes
Process CPU Usage
go2rtc
0.0%
logger
0.0%
recording
2.1%
review segment
0.3%
Process Memory Usage
go2rtc
0.1%
logger
0.6%
recording
0.7%
review segment
0.6%
