### DISCUSSION TITLE
[Config Support]:  Automation is missing pictures/clips

### DISCUSSION THREAD

**Discussion by leonbrag** [blakeblackshear/frigate#13306] [Config Support] [answered]
### Describe the problem you are having

I have following automation that sends email with the attached image:

```
alias: Front Camera Email
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: Front_Door
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
      before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
      score: "{{ trigger.payload_json['after']['score'] }}"
      time_clip_start: "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"

condition:
  # This condition is used to ensure that I am only notified of objects that are new or only just entered a zone. This is to avoid getting loads of updated notifications for the same dog in my backyard (as an example).
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['type'] == 'new' }}"

action:
  - data:
      title: >-
        Camera {{trigger.payload_json['after']['camera']}}:
        {{trigger.payload_json['after']['label']}} detected
      message: ""
      data:
        images:
          - >-
            /media/clips/{{trigger.payload_json['after']['camera']}}-{{trigger.payload_json['after']['id']}}.jpg
        html: >
    action: notify.email_send
mode: parallel
max: 10

```

I noticed that while sometime it does indeed attach snapshot with bounding box, most of the time no image attached.

### Version

.14

### Frigate config file

```yaml
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - dog



Front_Door: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.10.13
      port: 80
      user: admin
      password: Camera123
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.13/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.13/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.045,0.035,0.636,0.038,0.637,0.086,0.042,0.089

    snapshots:
      required_zones:
        - frontYard

    review:
      alerts:
        required_zones: frontYard
      detections: {}
#    mqtt:
#      required_zones:
#        - frontYard

    zones:
      frontYard:
        coordinates: 
          0.519,0.065,0.625,0.078,0.625,0.163,0.626,0.182,0.69,0.186,0.741,0.363,0.835,0.698,0.888,0.91,0.907,0.981,0.337,0.994,0.015,0.981,0.012,0.032,0.395,0.022,0.4,0.471
        loitering_time: 0
        objects:
          - person
          - car
          - cat
```

### Relevant Frigate log output

```shell
homeassistant  | 2024-08-23 17:14:08.743 WARNING (SyncWorker_42) [homeassistant.components.smtp.notify] Attachment /media/clips/Front_Door-1724458448.266207-a4vtgj.jpg not found. Skipping
homeassistant  | 2024-08-23 17:14:09.121 WARNING (SyncWorker_33) [homeassistant.components.smtp.notify] Attachment /media/clips/Front_Door-1724458448.266207-a4vtgj.jpg not found. Skipping
homeassistant  | 2024-08-23 17:14:09.122 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif(update, 'none', sound) }}'
homeassistant  | 2024-08-23 17:14:09.123 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif((update or sound == 'none'), 0, volume) }}'
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino
