### DISCUSSION TITLE
[Support]: Frigate crashes my server periodically, a possible Memory leak.

### DISCUSSION THREAD

**Discussion by tomerh2001** [blakeblackshear/frigate#13302] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Note: I'm a Frigate+ subscriber.

It has become common; my system crashes and quickly reboots randomly. I noticed that all the available RAM/swap is consumed before crashes. So, I opened Netdata and started working on it.

**Overview**
Firstly, an overview of a crash, followed by what appears to be another crash:
![image](https://github.com/user-attachments/assets/8486aee7-cd1d-4dd4-abe8-d9539e24d27f)

**Exhibit 0:** There's a random spike of reads/writes
![image](https://github.com/user-attachments/assets/305d0b32-f0ac-49f3-ada6-5b8b9b47a83f)

**Exhibit 1:** Right after, there's a 1 min period where all the available RAM is being consumed
![image](https://github.com/user-attachments/assets/57345431-a669-4fc5-bac8-c505591a8747)

**Exhibit 2:** The swap slowly fills up to the maximum during this period.
![image](https://github.com/user-attachments/assets/c96e48dc-920f-4bb3-8a6b-7a3e5d888c9a)

**Exhibit 3:** Right after the RAM hits 100% usage, a spike of ZFS memory ops occurs
![image](https://github.com/user-attachments/assets/75366303-8b45-4f51-bd75-84117e0a77d4)

**Exhibit 4:** This is immediately followed by disk writes to dm-0
![image](https://github.com/user-attachments/assets/38761000-85bb-400c-86f6-816c4a49a5c0)

**Exhibit 5:** It seems like we've found our culprit. Frigate.
![image](https://github.com/user-attachments/assets/91e63ece-ecf9-4887-9382-1527d927c126)

### Steps to reproduce

I have no idea, but this has happened to me for over weeks.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
database:
  path: /config/frigate.db

model:
  path: plus://X

ui:
  time_format: 24hour

mqtt:
  host: 10.0.0.X
  user: frigate
  password: X

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    living-room:
      - rtsp://X:X@10.0.0.X:554/cam/realmonitor?channel=1&subtype=0
    living-room-sub:
      - rtsp://X:X@10.0.0.X:554/cam/realmonitor?channel=1&subtype=1
    office:
      - rtsp://X:X@10.0.0.X:554/cam/realmonitor?channel=1&subtype=0
    office-sub:
      - rtsp://X:X@10.0.0.X:554/cam/realmonitor?channel=1&subtype=1
    cats:
      - nest:?client_id=X.apps.googleusercontent.com&client_secret=X&device_id=X

cameras:
  living-room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living-room
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/living-room-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.653,0.089,0.655,0.033,0.974,0.034,0.979,0.086
    zones:
      Home_Entrance:
        coordinates: 0.602,0.78,0.764,0.87,0.93,0.033,0.646,0.029
        loitering_time: 0
      Living_room_couch:
        coordinates: 0.432,0.455,0.246,0.615,0.122,0.401,0.261,0.271,0.45,0.326
        loitering_time: 10
    objects:
      mask: 0.549,0.449,0.589,0.491,0.607,0.151,0.554,0.138,0.546,0.445
    review:
      alerts:
        required_zones: Home_Entrance
  office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/office-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.653,0.025,0.657,0.094,0.975,0.102,0.981,0.027
    zones:
      Office_Table:
        coordinates: 0.097,0.77,0.41,0.518,0.552,0.946,0.519,1,0.526,1,0.214,0.99
        loitering_time: 10
        objects: person
  cats:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cats
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    zones:
      Cat_Tree:
        coordinates: 0.416,0.391,0.421,0.982,0.613,1,0.607,0.414,0.431,0.371,0.44,0.358
        loitering_time: 10
        objects: cat
      Top_of_dryer:
        coordinates: 0.12,0.476,0.108,0.329,0.108,0.287,0.289,0.266,0.309,0.449
        loitering_time: 10
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30
  timestamp: false
  bounding_box: false
  crop: true
  quality: 100
  height: 500

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - cat
    - dog
    - cell phone
version: 0.14
```

### Relevant Frigate log output
I truncated the timeframe of the previously mentioned crash. If you need the full log, let me know.
```shell
2024-08-23 18:02:38.597522531  127.0.0.1 - - [23/Aug/2024:18:02:38 +0300] "" 400 0 "-" "-" "-"
2024-08-23 18:03:15.795667584  172.18.0.9 - - [23/Aug/2024:18:03:15 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:03:16.313702464  172.18.0.9 - - [23/Aug/2024:18:03:16 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:03:18.225936305  172.18.0.9 - - [23/Aug/2024:18:03:18 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:03:22.706180446  172.18.0.9 - - [23/Aug/2024:18:03:22 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:03:38.640530506  127.0.0.1 - - [23/Aug/2024:18:03:38 +0300] "" 400 0 "-" "-" "-"
2024-08-23 18:03:38.856673747  172.18.0.9 - - [23/Aug/2024:18:03:38 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:03:54.517899752  172.18.0.9 - - [23/Aug/2024:18:03:54 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:04:14.045596651  [2024-08-23 18:04:14] watchdog.cats                  INFO    : cats exceeded fps limit. Exiting ffmpeg...
2024-08-23 18:04:14.045630868  [2024-08-23 18:04:14] watchdog.cats                  INFO    : Waiting for ffmpeg to exit gracefully...
2024-08-23 18:04:38.653481605  127.0.0.1 - - [23/Aug/2024:18:04:38 +0300] "" 400 0 "-" "-" "-"
2024-08-23 18:04:39.662274804  172.18.0.9 - - [23/Aug/2024:18:04:39 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:04:47.920592758  172.18.0.9 - - [23/Aug/2024:18:04:47 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:04:53.076945499  172.18.0.9 - - [23/Aug/2024:18:04:53 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:04:54.218442570  172.18.0.9 - - [23/Aug/2024:18:04:54 +0300] "GET /api/events HTTP/1.1" 200 600748 "-" "-" "-"
2024-08-23 18:07:09.270228111  [2024-08-23 18:06:33] watchdog.living-room           INFO    : No frames received from living-room in 20 seconds. Exiting ffmpeg...
2024-08-23 18:08:10.844882309  [2024-08-23 18:07:09] watchdog.living-room           INFO    : Waiting for ffmpeg to exit gracefully...
2024-08-23 18:08:10.905203883  [2024-08-23 18:06:36] watchdog.office                INFO    : No frames received from office in 20 seconds. Exiting ffmpeg...
2024-08-23 18:08:10.905344390  [2024-08-23 18:07:09] watchdog.office                INFO    : Waiting for ffmpeg to exit gracefully...
2024-08-23 18:08:10.943394814  [2024-08-23 18:08:10] watchdog.living-room           INFO    : FFmpeg did not exit. Force killing...
```

### Relevant go2rtc log output

```shell
Not sure where to look.
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Amercest, Google Nest

### Screenshots of the Frigate UI's System metrics pages and any other screenshots pertinent to your issue.

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/f70114b6-d255-45b6-9939-bc9d86d4f1f9">
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/c75645eb-57b3-4360-8be3-25048d5aaca0">
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/6ab97428-8dc0-432a-806f-712dae60efe0">
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/c876b604-7b04-4aa5-a90e-96fd2874aa6c">

### Any other information that may be helpful

I am not sure what to select in "operating system." I'm running the docker image using compose, and the host is an Ubuntu server, but I assume you want the OS inside the container, which is something I don't know.

**Comment by NickM-27** [comment]
> but I assume you want the OS inside the container

No, that would be Debian which we configure as part of docker image. 

To understand what is happening here it would be good to see the docker compose but also really helpful if you got a shell in the container while it was occurring to see what exactly is using the memory.

**Reply by tomerh2001** [reply]
This is the docker compose:
```
services:
  frigate:
    image: ${IMAGE}:${TAG:-latest}
    container_name: ${SLUG}
    restart: always
    shm_size: 256mb
    privileged: true
    environment:
      TZ: Asia/Jerusalem
      PUID: 1000
      PGID: 1000
      PLUS_API_KEY: X
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/bus/usb:/dev/bus/usb
      - ${SERVICES_DATASET}/${SLUG}:/config
      - ${MEDIA_DATASET}/media/${SLUG}:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1gb
    ports:
      - 5000:5000
      - 1935:1935
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    depends_on:
      traefik:
        condition: service_started
      emqx:
        condition: service_started
      coral:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SLUG}.rule=HostRegexp(`${DOMAIN}`)
      - traefik.http.routers.${SLUG}.entrypoints=websecure
      - traefik.http.routers.${SLUG}.tls=true
      - traefik.http.services.${SLUG}.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${SLUG}.middlewares=auth
      - homepage.group=${GROUP}
      - homepage.name=${NAME}
      - homepage.icon=${SLUG}.png
      - homepage.description=${DESCRIPTION}
      - homepage.href=https://${DOMAIN}/
      - homepage.weight=1
      - homepage.widget.type=${SLUG}
      - homepage.widget.url=http://${SLUG}:${PORT}
      # - homepage.widget.key=${API_KEY}
      - kuma.${SLUG}.http.name=${NAME}
      - kuma.${SLUG}.http.url=http://${SLUG}:${PORT}
      - kuma.${SLUG}.http.parent_name=${GROUP_SLUG}
      - kuma.${GROUP_SLUG}.group.name=${GROUP}

  coral:
    restart: no
    build:
      context: .
      dockerfile: coral/Dockerfile
    devices:
      - /dev/bus/usb
```

I also updated the post with the logs I found.
