### DISCUSSION TITLE
[Config Support]: QNAP Docker Compose - Bridge vs Host - Host Access Returns a 400 Bad Request ?

### DISCUSSION THREAD

**Discussion by nodecentral** [blakeblackshear/frigate#13310] [Config Support] [answered]
### Describe the problem you are having

Hi, following the guidance online for installation with QNAP; I created an associated compose file which installed successfully via Container Station and is reporting to be up and running; however it did not seem to use the bridge facility and obtain an IP, but as I can see references to 127.0.0.1 in the log, so I assume it has tied itself to the host, so I’ve tried to access it via the host IP and the 8971 port, but it returns a 400 error ?

<img width="385" alt="image" src="https://github.com/user-attachments/assets/80de1e13-82fe-4328-80a2-664c65a88545">

### Version

 ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    image: ghcr.io/blakeblackshear/frigate:stable
    network_mode: bridge
    shm_size: 256m 
    environment:
      - TZ:Europe/London
    working_dir: /opt/frigate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/frigate/config:/config
      - /share/Container/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    labels:
      - com.qnap.qcs.network.mode=nat
      - com.qnap.qcs.gpu=False
    deploy:
        resources:
            limits:
                memory: 4g
                cpus: “2”
    tty: true
    restart: unless-stopped
```

### Relevant Frigate log output

```shell
Using Dozzle to monitor the logs and there are a huge amount of entries in there, if there is something specific I should look for (key word/phrase to search) please let me know.
```

### Relevant go2rtc log output

```shell
Sorry not sure where to access this ?
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)
