### DISCUSSION TITLE
[Config Support]: Config file indentation

### DISCUSSION THREAD

**Discussion by phlnil** [blakeblackshear/frigate#13315] [Config Support] [answered]
### Describe the problem you are having

Hi, 
The question is why "Filter is Slow" (>50ms) ?
![immagine](https://github.com/user-attachments/assets/cf5d4e08-6e95-4276-9647-472ed001cce3)

Please tell me if I miss something.

Thank you.

### Version

0.14.0-da913d8

### In which browser(s) are you experiencing the issue with?

Chrome 128.0.6613.85 

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb


  filters:
    person:
      min_area: 5000
      max_area: 100000

cameras:
  FrontCam:
    ffmpeg:
      inputs:

        # Low Resolution Stream
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@IP/Streaming/channels/102
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,25,0,480,640,480,640,142,616,158,450,278,397,225,460,139,506,190,574,72,640,42,640,0,0,0
    objects:
      track:
        - person
        - car

  RearCam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:PW@IP/
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:PW@IP/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5
      enabled: true
    motion:
      mask:
        - 0,55,704,50,704,0,0,0
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Parking_area:
        coordinates: 608,224,553,332,412,227,555,0,704,0
    objects:
      track:
        - person
        - dog
        - cat
        - car

    review:
      alerts:
        required_zones: Parking_area
record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 1
      mode: active_objects
    post_capture: 9

motion:
  mask:
    - 0,25,480,29,480,0,0,0
  improve_contrast: true
version: 0.14
camera_groups:
  All:
    order: 1
    icon: LuAtom
    cameras:
      - FrontCam
      - RearCam
```

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardwa>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:rw
      - /cctv_clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "_"
      FRIGATE_RTSP_USER: "_"
```

### Relevant Frigate log output

```shell
no error
```

### Relevant go2rtc log output

```shell
2024-08-24 08:52:10.579158317  [INFO] Preparing new go2rtc config...
2024-08-24 08:52:10.882974396  [INFO] Starting go2rtc...
2024-08-24 08:52:11.009312261  08:52:11.009 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-08-24 08:52:11.009315640  08:52:11.009 INF config path=/dev/shm/go2rtc.yaml
2024-08-24 08:52:11.009676345  08:52:11.009 INF [rtsp] listen addr=:8554
2024-08-24 08:52:11.009709202  08:52:11.009 INF [api] listen addr=:1984
2024-08-24 08:52:11.009773777  08:52:11.009 INF [webrtc] listen addr=:8555/tcp
2024-08-24 08:52:20.578152760  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
please let me know if it could be useful in this case.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua, hikvision

### Screenshots of the Frigate UI's System metrics pages

![immagine](https://github.com/user-attachments/assets/72bbd078-fd16-427b-b8fc-a212f62cac28)

### Any other information that may be helpful

upgraded from 0.13 no issue at all... but this (.14) seems really slower of the previous  version :( ... (switching from "settings" to "live"...  sometimes require more 2-3 seconds )

**Comment by hawkeye217** [comment, marked as answer]
You have mistakenly put `filters` under your `detectors:` section in your config. You need to insert `objects:` so that it looks like this:

```
detectors:
  coral:
    type: edgetpu
    device: usb


objects:
  filters:
    person:
      min_area: 5000
      max_area: 100000
```
