### DISCUSSION TITLE
[Support]: Frigate crashes when trying to export on 0.14.0

### DISCUSSION THREAD

**Discussion by Floyd-Schramm** [blakeblackshear/frigate#13313] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Every time I try to export a specific time slot (10:13 - 11:18) from our front door frigate crashed and reboots itself. However I am able to export time slot 11:10 to 11:18 without a problem. Either way the error "Recording clip is missing or empty" shows up right before frigate crashes.
![image](https://github.com/user-attachments/assets/16706fd7-5086-4bf1-bc5d-a40ee7091e47)
This is the time slot I would like to export, either via the user interface as a realtime video or via the api as a time-lapse. This is the command I used to export via the api:
`curl -X POST http://frigate:5000/api/export/haustuer/start/1724487180/end/1724491080 -d "playback=timelapse_25x" -H "Content-Type: application/json" `
Could this brief interruption of the recording before the time slot have something to do with the error? If so, would there be a fix for exporting the given time slot?
![image](https://github.com/user-attachments/assets/b9831c72-d0c4-4849-a47e-c84a514605f2)

### Steps to reproduce

1. Select camera and timeslot
2. Press export or start the export via the api
3. See frigate crash, restart and adding another failed and loading export clip to the list: 
![image](https://github.com/user-attachments/assets/4e270818-d3da-42b5-b588-51cc97ebbd7b)

...

### Version

0.14.0-

### In which browser(s) are you experiencing the issue with?

Google Chrome Version 128.0.6613.84 / not Browser specific

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.143
  port: 1883
  topic_prefix: frigate
  client_id: friagte
  user: [username]
  password: [password]
  stats_interval: 60
  
######

cameras:
  vorgarten:
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorgarten
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/vorgarten_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy

  haustuer:
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: all
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/haustuer
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/haustuer_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac

  garten:
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garten_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
      
######
ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  enabled: false

audio:
  enabled: false

snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 7

record:
  enabled: true
  events:
    pre_capture: 10
    post_capture: 25

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
Installed frigate via Proxmox helper script (https://tteck.github.io/Proxmox/#frigate-lxc). Initial install should have been via this docker-compose but it now runs a service.

version: "3"
services:
  devcontainer:
    container_name: frigate-devcontainer
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: yolov7-320
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
```

### Relevant Frigate log output

```shell
Type warning | Timestamp 2024-08-24 12:49:41 | Tag frigate.api.media | Message Recording clip is missing or empty: /media/frigate/recordings/2024-08-24/09/haustuer/18.00.mp4
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Doorbell

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/add67424-37e3-4721-b5f2-0b1f231d288d)
![image](https://github.com/user-attachments/assets/b5e058b7-3333-4472-80f9-39c3bff148dc)
![image](https://github.com/user-attachments/assets/fb866ab6-e170-4983-b248-8cb69a3711eb)
![image](https://github.com/user-attachments/assets/a01625f6-bf43-4499-a73f-c834e07e6999)
(Spikes are the export tries and crashes)
