### DISCUSSION TITLE
[Config Support]: Automation fires for test camera but not real camera

### DISCUSSION THREAD

**Discussion by leonbrag** [blakeblackshear/frigate#13328] [Config Support] [answered]
### Describe the problem you are having

I finally got automation working to send attachment (coming from Frigate API) snapshot with email! 

This automation is triggered and fired perfectly for test camera that is just a looping video of ppl walking.
However, the same automation does not fire at all for real camera (note that camera is where loop video was saved from). 

I keep comparing with working Push Blueprint notification, but just can't see what I am doing wrong!

What am I doing wrong for actual camera automation trigger ?

Any help is greatly appreciated.

```
alias: Front email v3
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: front_door
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
      before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
      score: "{{ trigger.payload_json['after']['score'] }}"
      time_clip_start: "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"
      input_zones:
        - frontYard
      zones: "{{ input_zones }}"
condition: []
action:
  - sequence:
```
Under sequence I have 3 actions (that work for test stream):
1. Save Frigate snapshot from API to local file via shell script using wget
2. send email with attachment
3. invoke shell script second time to delete localfile

I have added last 3 lines for actual camera, but it did not help. 

I used https://github.com/blakeblackshear/frigate/discussions/2898 as starting point, but really just want same notification in email as shows as alerts in timeline

### Version

.14

### Frigate config file

```yaml
cameras:

  test:
    enabled: true 
    ffmpeg:
      inputs:
      - path:  /media/frigate/exports/Front_Door_boyk11.mp4
        input_args: -re -stream_loop -1 -fflags +genpts
        roles:
          - detect
          - record

Front_Door: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.10.13
      port: 80
      user: xxx
      password: xxx
    ffmpeg:
      inputs:
        - path: rtsp://xx:xxx@192.168.10.13/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.13/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.045,0.035,0.636,0.038,0.637,0.086,0.042,0.089

    snapshots:
      required_zones:
        - frontYard

    review:
      alerts:
        required_zones: frontYard
      detections: {}
    mqtt:
      required_zones:
        - frontYard

    zones:
      frontYard:
        coordinates: 
          0.519,0.065,0.625,0.078,0.625,0.163,0.626,0.182,0.69,0.186,0.741,0.363,0.835,0.698,0.888,0.91,0.907,0.981,0.337,0.994,0.015,0.981,0.012,0.032,0.395,0.022,0.4,0.471
        loitering_time: 0
        objects:
          - person
          - car
          - cat
```

### Relevant Frigate log output

```shell
na
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

**Comment by NickM-27** [comment]
What are the conditions?

**Reply by leonbrag** [reply]
Hmm. None:

```
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: front_door
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
      before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
      score: "{{ trigger.payload_json['after']['score'] }}"
      time_clip_start: "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"
      input_zones:
        - frontYard
      zones: "{{ input_zones }}"
condition: []
action:
```
..

What I am really confused, when change camera to test cam that looping walking ppl (without changing anything but camera name) notifications are triggered.

The objective is just to fire automation when alerts on cars, ppl are triggered. 

Or on all motion in the zone.
