### DISCUSSION TITLE
[Config Support]: File size assistance needed

### DISCUSSION THREAD

**Discussion by Zer0Cntrl** [blakeblackshear/frigate#13325] [Config Support] [answered]
### Describe the problem you are having

I had a Reolink NVR and it died, so I decided to take the plunge and get Frigate up and running instead of sticking with a proprietary ecosystem.  I have Frigate all set up and working with 6 Reolink cameras.  However, the files I get out of Frigate for video recording are almost 2x the file size at the same resolution and a lower framerate.  4k @ 25fps vs 4k @ 15fps.

I could really use some help in understanding or what I can do to reduce some of that file size will at least preserving some of the quality and detail.  You can see my configs below with relevant information only

### Version

0.14.0-da913d8

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    driveway_garage_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_IP_ONE}:554/h265Preview_01_main
      - ffmpeg:driveway_garage_main#video=h264#hardware#audio=aac

cameras:
    driveway_garage:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOCAL_IP}:8554/driveway_garage_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    live:
      stream_name: driveway_garage_main

version: 0.14
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

TensorRT
