### DISCUSSION TITLE
[Support]: Authentik Configuration

### DISCUSSION THREAD

**Discussion by jasonlaguidice** [blakeblackshear/frigate#13329] [General Support]
### Describe the problem you are having

Now that Frigate supports auth - does someone have an example configuration on the Authentik side to auth with Frigate?

I don't have a reverse proxy or anything in front of frigate right now and only access it locally via mDNS but would like to potentially open it up (which would end up going through a Cloudflare tunnel) and secure it through Authentik.

Is a reverse proxy required?

I've tried a few combinations with the Authentik proxy but can't find something that passes headers appropriately. Just setting auth to disabled (as shown in the attached config) allows anyone in with no authentication whatsoever so that's not ideal.

### Version

14.0

### Frigate config file

```yaml
auth:
  enabled: False
  trusted_proxies:
    - 192.168.1.204

proxy:
  header_map:
    user: X-authentik-username

version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Multiple

**Comment by NickM-27** [comment]
if you want to use frigate's built in authentication then there is no need for a reverse proxy to provide authentication. If you want to use proxy authentication then yes frigate's authentication would be disabled. The configuration of the proxy auth is something that you would find better support elsewhere

**Comment by miloszlipski** [comment]
https://docs.frigate.video/configuration/authentication/#proxy-configuration

**Comment by chrislawso** [comment]
Were you able to complete the authentik auth setup with frigate or did you use any other auth proxy?

**Reply by jasonlaguidice** [reply]
> Were you able to complete the authentik auth setup with frigate or did you use any other auth proxy?

No, but I'm relatively unfamiliar with a proxy provider with Authentik. I'll give it another pass today and see if I can make it work as expected.

My goal was to have the frigate address exposed on a public URL and logins allowed only via Authentik but it didn't seem like this was possible at first pass - I would have had to have Frigate behind something else protecting it (like, just not exposing it and VPN'ing in) which totally defeats the need for any sort of authentication.

**Comment by jasonlaguidice** [comment]
So this is specific to my setup but it looks like I was able to make it work this time. Since this is still the top result if I Google Authentik Frigate - I should probably provide some sort of help. I don't know how much of this is necessary as this was frustrating to get working.

For this setup I am using Cloudflare tunnels for all access. My Authentik host is accessed through a CF tunnel. The Authentik host is on the same network as the Frigate host and can be accessed with mDNS.

### Frigate 
Frigate config changes:
```
auth:
  enabled: false
  trusted_proxies:
    - [your_proxy_ip/subnet]
proxy:
  header_map:
    user: x-authentik-username
```

### Authentik
In Authentik make a provider with the following settings:
Type: Proxy
External host: `https://your-frigate-external-address.com`
Internal host: `http://frigate.local:5000` (or whatever you're running frigate locally at - this would be the address the Authentik host can reach the Frigate host at)
Disable internal host SSL Validation

Navigate to Applications -> Outposts

Edit the authentik Embedded Outpost and add the provider to the list

Create an Application for Frigate and select the provider created previously (no other changes should be necessary). Set up your preferred access rules

### Cloudflare
Modify the tunnel providing access to your Authentik instance. Add a second hostname for `your-frigate-external-address.com` forwarded to the same port that Authentik is typically accessed at. For me, this is `localhost:9000`

Deploy and that's it. When accessing the frigate external address you will be prompted to login to Authentik. Once logged in you will be transparently passed through to Frigate. All traffic to Frigate will flow through Authentik's proxy.

**Reply by janstadt** [reply]
This looks great but unfortunately it doesnt seem to be working for me. The config in authentik is fine, but every time i go to my fqdn it just shows all the cameras and shows that im "anonymous". Im looking for the ability to completely wall off frigate unless authenticated. Im using caddy for my reverse proxy and am using the 8971 port. 

config

```
tls:
  enabled: false
auth:
  enabled: false
  trusted_proxies:
    - 192.168.1.89
proxy:
  header_map:
    user: x-authentik-username
```

Any ideas:
hitting port 5000 makes sense:
<img width="352" height="202" alt="image" src="https://github.com/user-attachments/assets/21ba872f-a9fe-4ada-b818-408d4a610924" />

hitting port 8971 is whats confusing to me:
<img width="350" height="199" alt="image" src="https://github.com/user-attachments/assets/07b0fba5-905e-4c25-94cb-45dc4f4e505b" />

Originally i was redirecting to http:// with the 5000 port and that makes sense to show no auth, but if i have it configured like this im unable to use my fqdn:
<img width="644" height="301" alt="image" src="https://github.com/user-attachments/assets/1751df8a-f6a1-4aae-892e-f3fc354167a9" />

**Reply by janstadt** [reply]
fwiw, when i set it to http:// it does in fact load frigate correctly, but it still isnt forcing authentication. I want to ensure that the fqdn is blocked unless an authenticated user is fully logged in.

**Reply by jasonlaguidice** [reply]
As was mentioned frigate doesn't support the mapping of OIDC claims to Frigate users. You'll get all-or-nothing with access through Authentik

You have to choose one or the other - Frigate's access mechanism or Authentik's.

If you choose Authentik - nothing prevents you from accessing the Frigate UI directly by its IP address. But the address you provide through Authentik will be controlled by Authentik's proxy.

**Reply by janstadt** [reply]
Im aware of that. What im saying is with what appears like a correctly configured fqdn in caddy, i can get directly to the frigate UI without logging in.

**Comment by danieledwardgeorgehitchcock** [comment]
Hi all, I know this thread is closed but, I thought I'd share my setup with Frigate, Traefik and Authentik:

### Frigate
Docker Compose Labels:
```yaml
    labels:
      traefik.enable: true
      traefik.http.services.frigate.loadbalancer.server.port: "8971"
      traefik.http.routers.frigate.service: "frigate"  #Change this to suit your setup
      traefik.http.routers.frigate.rule: "Host(`frigate.fqdn`)"  #Change this to suit your setup
      traefik.http.routers.frigate.entrypoints: "http-secure" #Change this to suit your setup
      traefik.http.routers.frigate.tls: true
      traefik.http.routers.frigate.tls.certresolver: "letsencrypt" #Change this to suit your setup
      traefik.http.routers.frigate.middlewares: "authentik@file"
```

config.yaml:
```yaml
tls:
  enabled: false #Enabling will result in 400 error due to http-https mismatch

auth:
  enabled: false
  trusted_proxies:
    - IP.OF.PROXY.NETWORK/16 #Docker reverse-proxy network - Change this to suit your setup

proxy:
  header_map:
    user: x-authentik-username
    role: x-authentik-groups
    role_map:
      admin:
        - "frigate Admins"
      viewer:
        - "frigate Users"
```

### Authentik:
Application: `Frigate`

Provider:
Type: `Proxy`
Provider Name: `Frigate`
Authorization Flow: `default-provider-authorization-implicit-consent (Authorize Application)` #Change this to suit your setup
Proxy Type: `Forward auth (single application)`
External Host: `https://frigate.fqdn` #Change this to suit your setup

Outposts:
authentik Embedded Outpost:
Selected Applications: `Frigate`

Directory:
Groups:
New: `frigate Admins`
New: `frigate Users`

frigate Admins:
Users: #Add admin users here

frigate Users:
Users: #Add viewer users here

### Traefik:
Middlewares:
authentik.yaml:
```yaml
http:
  middlewares:
    authentik:
      forwardAuth:
        address: http://authentik:9000/outpost.goauthentik.io/auth/traefik #Change this to suit your setup
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
