### DISCUSSION TITLE
Detections not triggering

### DISCUSSION THREAD

**Discussion by Grunticus03** [blakeblackshear/frigate#13339] [General]
As the picture shows below, Frigate isn't reporting any detections.

![image](https://github.com/user-attachments/assets/51bc446b-1cf3-4d55-b985-066c34e5a39d)

Also, in Home Assistant, the occupancy and count entities aren't triggering.

![image](https://github.com/user-attachments/assets/553a67d8-bb2d-475f-96a3-9c1f31f0b90f)

What do I have configured wrong?  I confirmed all four video feeds are accessible using the same links in VLC Media Player.

```
mqtt:
  enabled: false

go2rtc:
  streams:
    Driveway:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.50.10:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Driveway#audio=opus
    Driveway_sub:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.50.10:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:Driveway_sub#audio=opus
    Porch:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.50.11:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Driveway#audio=opus
    Porch_sub:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.50.11:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:Driveway_sub#audio=opus
  webrtc:
    candidates:
      - 192.168.50.2:8555
      - stun:8555

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  Driveway:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: Driveway
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask: 0.336,0.335,0.227,0.67,0.376,0.755,0.434,0.374
    zones:
      zone_driveway:
        coordinates: 
          0,0.438,0.149,0.275,0.456,0,0.942,0.002,0.93,0.015,0.848,0.368,0.771,0.666,0.675,0.998,0,0.999
        inertia: 3
        loitering_time: 0
      zone_side-yard:
        coordinates: 0.999,0.002,1,1,0.679,1,0.931,0.016,0.946,0.002
        inertia: 3
        loitering_time: 0
      zone_front-yard:
        coordinates: 0.001,0.436,0.101,0.324,0.242,0.185,0.265,0.167,0.456,0,0,0
        inertia: 3
        loitering_time: 0
  Porch:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Porch
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: Porch
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.091,0.169,0.145,0.15,0.252,0.127,0.254,0.031,0.234,0.001,0.094,0,0.083,0.135
        - 0.423,0,0.471,0.106,0.53,0.107,0.582,0.062,0.584,0
        - 0.829,0.207,0.771,0.17,0.774,0.088,0.811,0.133,0.828,0.138,0.833,0.161
        - 0.026,0,0.025,0.016,0.028,0.042,0.024,0.07,0.025,0.107,0.02,0.134,0.022,0.18,0.024,0.253,0.028,0.323,0.032,0.36,0.039,0.418,0.046,0.477,0.062,0.566,0.084,0.646,0.104,0.721,0.137,0.816,0.181,0.927,0.214,0.998,0.001,0.998,0.001,0
        - 0.482,0.555,0.429,0.653,0.417,0.703,0.434,0.762,0.464,0.824,0.474,0.855,0.464,0.926,0.479,0.974,0.67,0.992,0.692,0.919,0.708,0.8,0.673,0.728,0.61,0.718,0.623,0.654,0.612,0.583,0.607,0.51,0.541,0.474,0.506,0.502
        - 0.567,0.379,0.535,0.388,0.539,0.457,0.576,0.482,0.611,0.497,0.618,0.464,0.628,0.407,0.595,0.378
        - 0.668,0.541,0.645,0.594,0.633,0.702,0.724,0.755,0.746,0.657,0.748,0.578
        - 0.7,0.014,0.678,0.034,0.658,0.07,0.666,0.108,0.655,0.154,0.667,0.165,0.655,0.205,0.715,0.226,0.723,0.157,0.714,0.116,0.709,0.083,0.723,0.064
    zones:
      zone_driveway:
        coordinates: 0.219,0.327,0.404,0.389,0.775,0.561,0.8,0.389,0.349,0.227
        inertia: 3
        loitering_time: 0
      zone_porch:
        coordinates: 0.776,0.565,0.677,0.999,0.894,0.999,0.902,0.626,0.954,0.322,0.834,0.169
        inertia: 3
        loitering_time: 0
      zone_front-yard:
        coordinates: 
          0.206,0.326,0.042,0.433,0.103,0.709,0.215,0.998,0.671,0.998,0.771,0.561,0.398,0.389
        inertia: 3
        loitering_time: 0
      zone_cul-de-sac:
        coordinates: 
          0.027,0.331,0.039,0.435,0.132,0.374,0.215,0.325,0.346,0.227,0.36,0.203,0.365,0.186,0.363,0.172,0.352,0.154,0.333,0.136,0.296,0.132,0.253,0.13,0.206,0.151,0.165,0.17,0.132,0.185,0.076,0.22,0.042,0.243,0.022,0.256
        inertia: 3
        loitering_time: 0
      zone_road:
        coordinates: 
          0.452,0.057,0.355,0.091,0.254,0.129,0.333,0.135,0.352,0.154,0.382,0.113,0.489,0.075
        loitering_time: 0
    objects:
      filters:
        person:
          mask:
            - 0.791,0.295,0.79,0.333,0.806,0.338,0.808,0.293
            - 0.054,0.408,0.067,0.488,0.09,0.609,0.097,0.605,0.08,0.512,0.091,0.499,0.087,0.471,0.072,0.468,0.063,0.405
            - 0.162,0.257,0.179,0.259,0.191,0.355,0.177,0.356,0.17,0.3,0.165,0.292
        car:
          mask: 0.374,0.072,0.349,0.069,0.351,0.058,0.374,0.062
objects:
  track:
    - bicycle
    - motorcycle
    - car
    - cat
    - dog
    - person

record:
  preview:
    quality: high
  events:
    pre_capture: 10
    post_capture: 10

review:
  alerts:
    labels:
      - bicycle
      - motorcycle
      - car
      - cat
      - dog
      - person
  detections:
    labels:
      - bicycle
      - motorcycle
      - car
      - cat
      - dog
      - person

snapshots:
  enabled: true
  timestamp: true

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  width: 1920
  height: 1080
  quality: 5

ui:
  timezone: America/Chicago
  date_style: medium
  time_style: medium
version: 0.14


```
