### DISCUSSION TITLE
[Detector Support]: Coral USB No EdgeTPU was detected.

### DISCUSSION THREAD

**Discussion by fernent** [blakeblackshear/frigate#13357] [Detector Support] [answered]
### Describe the problem you are having

I was running frigate on my rpi4 with USB coral. 

I needed to change the sd card and once I have done it and install frigate this error message appears : 
`ValueError: Failed to load delegate from libedgetpu.so.1.0
`
and frigate cannot starts.

I tried to solve the problem. I did many and different fresh installs on several sd cards of Raspberry PI OS.
I setup the coral device using : https://coral.ai/docs/accelerator/get-started/
and I have tested it with the pycoral library : everything is working as expected (related to the classifying example at the end of the page). I obtained the same results when usb coral is plugged (if it is not plugged I got the same error as in frigate : `ValueError: Failed to load delegate from libedgetpu.so.1.0
`)

I am aware there are a lot of discussions about this error. Often it's an hardware problem: not enough power, problem with usb cable, coral usb not initiated ... but in my case I believe it is not (I have two usb coral, I bought a cable that was working with the former sd card, I have a usb hub with its own alimentation (and  no usb port is used except for the coral usb device).
However the `lsusb` output is : 
`Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp. 
`
I also tested it by installing the device rules using this repo :

https://github.com/google-coral/webcoral

After it (make reset), the lsusb changes its output  :
`Bus 002 Device 009: ID 18d1:9302 Google Inc. 
`
but still frigate could not start. Altough it seems that the coral usb was initiated by flashing the firmware, this is not persistent (restarting the rpi or changing the usb port).

My question is : if the usb coral is working with the pycoral library, does it tell us it's not an hardware problem ? 

I think the usb coral have blinking white led at startup. Now mine is always a fixed white led, I wonder if it does tell something. It's working with pycoral but not the frigate container.

### Version

ghcr.io/blakeblackshear/frigate:stable 

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    #image: ghcr.io/blakeblackshear/frigate:0.13.0-standard-arm64
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
frigate  | 2024-08-26 17:47:58.370716774  2024/08/26 17:47:58 [error] 162#162: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate  | 2024-08-26 17:47:58.370788052  2024/08/26 17:47:58 [error] 162#162: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate  | 2024-08-26 17:47:59.223730975  [2024-08-26 17:47:59] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
frigate  | 2024-08-26 17:47:59.224530362  [2024-08-26 17:47:59] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-08-26 17:47:59.241432405  [2024-08-26 17:47:59] frigate.util.config            INFO    : copying config as backup...
frigate  | 2024-08-26 17:47:59.243530049  [2024-08-26 17:47:59] frigate.util.config            INFO    : Migrating frigate config from 0.13 to 0.14...
frigate  | 2024-08-26 17:47:59.255211676  [2024-08-26 17:47:59] frigate.util.config            INFO    : Migrating export file names...
frigate  | 2024-08-26 17:47:59.261699201  [2024-08-26 17:47:59] frigate.util.config            INFO    : Finished frigate config migration...
frigate  | 2024-08-26 17:48:00.367500983  [2024-08-26 17:48:00] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
frigate  | 2024-08-26 17:48:00.416873889  [tcp @ 0x428b1ed0] Connection to tcp://127.0.0.1:554?timeout=0 failed: Connection refused
frigate  | 2024-08-26 17:48:00.497681699  [2024-08-26 17:48:00] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-08-26 17:48:00.501231692  [2024-08-26 17:48:00] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-08-26 17:48:00.515533239  [2024-08-26 17:48:00] frigate.app                    INFO    : Recording process started: 378
frigate  | 2024-08-26 17:48:00.530392896  [2024-08-26 17:48:00] frigate.app                    INFO    : Recording process started: 379
frigate  | 2024-08-26 17:48:00.546029977  [2024-08-26 17:48:00] frigate.app                    INFO    : go2rtc process pid: 102
frigate  | 2024-08-26 17:48:00.620171429  [2024-08-26 17:48:00] detector.coral                 INFO    : Starting detection process: 406
frigate  | 2024-08-26 17:48:00.620551317  [2024-08-26 17:48:00] frigate.app                    INFO    : Output process started: 408
frigate  | 2024-08-26 17:48:00.625179623  [2024-08-26 17:48:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate  | 2024-08-26 17:48:03.633090656  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-08-26 17:48:26.071651440  [2024-08-26 17:48:00] frigate.app                    INFO    : Camera processor not started for disabled camera dummy_camera
frigate  | 2024-08-26 17:48:26.071984976  [2024-08-26 17:48:00] frigate.app                    INFO    : Capture process not started for disabled camera dummy_camera
frigate  | 2024-08-26 17:48:26.073444694  [2024-08-26 17:48:26] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
frigate  | 2024-08-26 17:48:26.074025248  Process detector:coral:
frigate  | 2024-08-26 17:48:26.077468460  Traceback (most recent call last):
frigate  | 2024-08-26 17:48:26.077529386    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
frigate  | 2024-08-26 17:48:26.077532663      delegate = Delegate(library, options)
frigate  | 2024-08-26 17:48:26.077535830    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
frigate  | 2024-08-26 17:48:26.077546682      raise ValueError(capture.message)
frigate  | 2024-08-26 17:48:26.078004014  ValueError
frigate  | 2024-08-26 17:48:26.078013884  
frigate  | 2024-08-26 17:48:26.078016681  During handling of the above exception, another exception occurred:
frigate  | 2024-08-26 17:48:26.078018106  
frigate  | 2024-08-26 17:48:26.078020069  Traceback (most recent call last):
frigate  | 2024-08-26 17:48:26.078022810    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-08-26 17:48:26.078024384      self.run()
frigate  | 2024-08-26 17:48:26.078026958    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-08-26 17:48:26.078037255      self._target(*self._args, **self._kwargs)
frigate  | 2024-08-26 17:48:26.078103199    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2024-08-26 17:48:26.078107680      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-08-26 17:48:26.078110403    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2024-08-26 17:48:26.078112736      self.detect_api = create_detector(detector_config)
frigate  | 2024-08-26 17:48:26.078222680    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-08-26 17:48:26.078226698      return api(detector_config)
frigate  | 2024-08-26 17:48:26.078289180    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 41, in __init__
frigate  | 2024-08-26 17:48:26.078292772      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
frigate  | 2024-08-26 17:48:26.078296235    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
frigate  | 2024-08-26 17:48:26.078298754      raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate  | 2024-08-26 17:48:26.078301235  ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

none

Related unsolved issue : 
https://github.com/google-coral/edgetpu/issues/715#issue-1560735383

This one suggests it is related to a docker problem :

https://forums.docker.com/t/docker-desktop-container-not-seeing-host-usb-port-new-to-docker/135930

**Comment by hawkeye217** [comment]
Try specifying the `device` in your config ([docs](https://docs.frigate.video/configuration/object_detectors#edge-tpu-detector)):

```
detectors:
  coral:
    type: edgetpu
    device: usb
```
