### DISCUSSION TITLE
[Config Support]: Optimisation of config, is hardware acceleration being used?

### DISCUSSION THREAD

**Discussion by Markus9955** [blakeblackshear/frigate#13364] [Config Support]
### Describe the problem you are having

No current problems, I have "winged it" to get my config up and going so would value an expert look over to see if I have any gaps and to ensure that hardware acceleration is actually in use. 

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xxx
  user: un
  password: pw

detectors:
  coral_pci:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

logger:
  logs:
    frigate.record: info

go2rtc:
  rtsp:
    username: un
    password: pw
  streams:
    # Reolink doorbell POE
    doorbell: # 2560 * 1920
      - ffmpeg:http://192.168.4.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=un&password=pw#video=copy#audio=copy#audio=opus
    doorbell_sub: # 640 * 480
      - ffmpeg:http://192.168.4.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=un&password=pw

    # Empire IPC-T54IR-ZE-S3
    garden: # 2560 * 1440
      - ffmpeg:rtsp://un:pw@192.168.4.xxx:554/cam/realmonitor?channel=1&subtype=0#video=copy#audio=copy#audio=opus
    garden_sub: # 1280 * 720
      - ffmpeg:rtsp://un:pw@192.168.4.xxx:554/cam/realmonitor?channel=1&subtype=2

    # Reolink E1 Pro  
    3dprinter: # 2560 * 1440
      - ffmpeg:rtsp://un:pw@192.168.4.xxx:554/h264Preview_01_main
    3dprinter_sub: # 640 * 360
      - ffmpeg:rtsp://un:pw@192.168.4.xxx:554/h264Preview_01_sub

  webrtc:
    candidates:
      - 192.168.1.xxx:8555
      - stun:8555

birdseye:
  enabled: true
  mode: continuous

snapshots:
  enabled: true
  retain:
    default: 30

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - car
    zones:
      Driveway:
        coordinates: 
          0.994,0.501,0.915,0.446,0.85,0.451,0.816,0.464,0.777,0.485,0.755,0.495,0.743,0.572,0.698,0.581,0.639,0.587,0.592,0.592,0.528,0.584,0.449,0.601,0.36,0.597,0.29,0.574,0.212,0.6,0.132,0.642,0.032,0.679,0.006,0.693,0.001,0.714,0.002,0.999,1,0.995
        inertia: 3
    review:
      alerts:
        required_zones: Driveway


  garden:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - car
    zones:
      No_detect:
        coordinates: 0.537,0.704,0.577,0.712,0.581,0.755,0.535,0.765
        inertia: 3
    review:
      alerts:
        required_zones: No_detect
      detections:
        required_zones: No_detect
    motion:
      threshold: 45
      contour_area: 17
      improve_contrast: true


  3dprinter:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/3dprinter?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/3dprinter_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - car


camera_groups: {}
version: 0.14
```

### Relevant Frigate log output

```shell
2024-08-26 20:10:28.575881451  [INFO] Preparing Frigate...
2024-08-26 20:10:28.613477087  [INFO] Starting Frigate...
2024-08-26 20:10:30.431183850  [2024-08-26 20:10:30] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
2024-08-26 20:10:30.431393035  [2024-08-26 20:10:30] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-08-26 20:10:30.465533625  [2024-08-26 20:10:30] frigate.util.config            INFO    : frigate config does not need migration...
2024-08-26 20:10:55.819130087  [2024-08-26 20:10:55] peewee_migrate.logs            INFO    : Starting migrations
2024-08-26 20:10:55.819134427  [2024-08-26 20:10:55] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-26 20:10:55.824892216  [2024-08-26 20:10:55] frigate.app                    INFO    : Recording process started: 352
2024-08-26 20:10:55.831048979  [2024-08-26 20:10:55] frigate.app                    INFO    : Recording process started: 356
2024-08-26 20:10:55.835333635  [2024-08-26 20:10:55] frigate.app                    INFO    : go2rtc process pid: 99
2024-08-26 20:10:55.877985576  [2024-08-26 20:10:55] frigate.app                    INFO    : Output process started: 382
2024-08-26 20:10:55.892061031  [2024-08-26 20:10:55] detector.coral_pci             INFO    : Starting detection process: 381
2024-08-26 20:10:55.914712474  [2024-08-26 20:10:55] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-08-26 20:10:55.914716632  [2024-08-26 20:10:55] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-08-26 20:10:56.287333716  [2024-08-26 20:10:56] frigate.app                    INFO    : Camera processor started for doorbell: 430
2024-08-26 20:10:56.294979007  [2024-08-26 20:10:56] frigate.app                    INFO    : Camera processor started for garden: 433
2024-08-26 20:10:56.302482542  [2024-08-26 20:10:56] frigate.app                    INFO    : Camera processor started for 3dprinter: 436
2024-08-26 20:10:56.309870280  [2024-08-26 20:10:56] frigate.app                    INFO    : Capture process started for doorbell: 438
2024-08-26 20:10:56.317674619  [2024-08-26 20:10:56] frigate.app                    INFO    : Capture process started for garden: 444
2024-08-26 20:10:56.336356582  [2024-08-26 20:10:56] frigate.app                    INFO    : Capture process started for 3dprinter: 448
```

### Relevant go2rtc log output

```shell
2024-08-26 20:10:28.574271225  [INFO] Preparing new go2rtc config...
2024-08-26 20:10:29.041002857  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-08-26 20:10:29.087063566  [INFO] Starting go2rtc...
2024-08-26 20:10:29.290353644  20:10:29.288 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-08-26 20:10:29.290357814  20:10:29.288 INF config path=/dev/shm/go2rtc.yaml
2024-08-26 20:10:29.290362808  20:10:29.289 INF [rtsp] listen addr=:8554
2024-08-26 20:10:29.290365431  20:10:29.289 INF [webrtc] listen addr=:8555
2024-08-26 20:10:29.290858200  20:10:29.290 INF [api] listen addr=:1984
2024-08-26 20:10:38.566861848  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"3dprinter":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":448,"detection_enabled":true,"detection_fps":19.1,"ffmpeg_pid":670,"pid":436,"process_fps":7.1,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":438,"detection_enabled":true,"detection_fps":10.2,"ffmpeg_pid":454,"pid":430,"process_fps":10.1,"skipped_fps":0.0},"garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":444,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":460,"pid":433,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"124":{"cmdline":"python3 -u -m frigate","cpu":"2.6","cpu_average":"9","mem":"1.8"},"1265":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1331":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"134":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"159":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"163":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"305":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"332":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.5"},"34":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"352":{"cmdline":"frigate.recording_manager","cpu":"3.9","cpu_average":"2","mem":"0.7"},"356":{"cmdline":"frigate.review_segment_manager","cpu":"0.5","cpu_average":"0","mem":"0.5"},"380":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(62)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"381":{"cmdline":"frigate.detector.coral_pci","cpu":"4.6","cpu_average":"2","mem":"0.6"},"382":{"cmdline":"frigate.output       ","cpu":"2.1","cpu_average":"1","mem":"0.5"},"400":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"405":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"410":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"415":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"430":{"cmdline":"frigate.process:doorbell","cpu":"6.9","cpu_average":"6","mem":"0.7"},"433":{"cmdline":"frigate.process:garden","cpu":"1.0","cpu_average":"1","mem":"0.7"},"436":{"cmdline":"frigate.process:3dprinter","cpu":"6.8","cpu_average":"2","mem":"0.7"},"438":{"cmdline":"frigate.capture:doorbell","cpu":"1.7","cpu_average":"1","mem":"0.7"},"444":{"cmdline":"frigate.capture:garden","cpu":"1.2","cpu_average":"0","mem":"0.7"},"448":{"cmdline":"frigate.capture:3dprinter","cpu":"0.6","cpu_average":"0","mem":"0.7"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"454":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_sub?video=copy -r 10 -vf fps=10,scale=896:672 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.6","cpu_average":"4","mem":"0.2"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"460":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub?video=copy -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.7","cpu_average":"2","mem":"0.2"},"472":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.1"},"476":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.4.xx2:554/cam/realmonitor?channel=1&subtype=2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/34dd2369c776c568a3477feb9ab498aa","cpu":"0.4","cpu_average":"0","mem":"0.1"},"477":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.4.xx1/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/581624fa76a03d22ea7d4d40aa7709dd","cpu":"0.6","cpu_average":"0","mem":"0.1"},"478":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.1"},"483":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.4.xx2:554/cam/realmonitor?channel=1&subtype=0 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/7a357d1110b233650e31e719bb5e92fe","cpu":"2.2","cpu_average":"1","mem":"0.1"},"487":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/3dprinter?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/3dprinter@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"488":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.4.xx1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/21abf46015e085798410251336d87905","cpu":"1.9","cpu_average":"1","mem":"0.1"},"492":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.4.xx3:554/h264Preview_01_main -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/10070ae78cf1b9966468ac0df7103b82","cpu":"1.3","cpu_average":"1","mem":"0.1"},"670":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/3dprinter_sub?video=copy -r 7 -vf fps=7,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.3","cpu_average":"0","mem":"0.1"},"672":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.4.xx3:554/h264Preview_01_sub -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b0a244756fdd404f6029b01d75c6a1fe","cpu":"0.3","cpu_average":"0","mem":"0.1"},"84":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"95":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"99":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"1.6","cpu_average":"1","mem":"0.1"},"frigate.full_system":{"cpu":"22.2","mem":"87.5"}},"detection_fps":29.3,"detectors":{"coral_pci":{"detection_start":0.0,"inference_speed":6.82,"pid":381}},"gpu_usages":{"intel-vaapi":{"gpu":"2.79%","mem":"-%"}},"processes":{"go2rtc":{"pid":99},"logger":{"pid":332},"recording":{"pid":352},"review_segment":{"pid":356}},"service":{"last_updated":1724699731,"latest_version":"0.14.0","storage":{"/dev/shm":{"free":123.6,"mount_type":"tmpfs","total":128.0,"used":4.4},"/media/frigate/clips":{"free":6506.4,"mount_type":"ext4","total":468355.7,"used":437986.4},"/media/frigate/recordings":{"free":6506.4,"mount_type":"ext4","total":468355.7,"used":437986.4},"/tmp/cache":{"free":934.8,"mount_type":"tmpfs","total":953.7,"used":18.9}},"temperatures":{"apex_0":52.05},"uptime":275,"version":"0.14.0-da913d8"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a14b867b-3142-4992-94e3-9cf521d6b8f3)
