### DISCUSSION TITLE
[Question]: When are Snapshots Sent to the Media/Frigate/Clips Folder

### DISCUSSION THREAD

**Discussion by PablaV** [blakeblackshear/frigate#13363] [Ask A Question] [answered]
### What is your question?

Unrelated to the[ MQTT snapshot issues ](https://github.com/blakeblackshear/frigate/discussions/11696#discussion-6766663)I have been having, I was wondering when the snapshots that live in the media/frigate/clips folder are sent. For example I have a vehicle enter the driveway zone, it is correctly recognized as it being inside the zone and an event id is created. However the snapshot is not created in the folder. Sometime later, once the vehicle leaves the zone the snapshot is created, but its the snapshot from when the vehicle entered the zone and not when it leaves. My logic would have it that a snapshot is created when the vehicle enters, then another new one is created once its leaves unless I have it wrong. 

For example you can see the snapshot below was _created_ at 11:49am (when the vehicle left the driveway zone) but the snapshot was _taken_ at 11:10am which was when the vehicle first entered the driveway zone. 
![image](https://github.com/user-attachments/assets/d3ec27cf-d901-41f3-b8c4-853e8c6bc17f)

```
mqtt:
  host: 192.168.8.85
  port: 1883
  user: Arman
  password: xxxx
cameras:
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 2560
      height: 1920
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
      filters:
        car:
          min_area: 7500
          min_score: 0.85
        person:
          min_area: 2600
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 30
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 1,0,1,0.037,0.654,0.035,0.655,0
        - 0.164,0.256,0.216,0.386,0.216,0.461,0.688,0.494,0.678,0.409,0.767,0.227,0.876,0.177,0.818,0.073,0.576,0.123,0.228,0.134
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 
          0.176,0.33,0.174,0.586,0.308,0.54,0.495,0.545,0.717,0.578,0.719,0.348,0.928,0.252,0.999,0.216,0.996,0.996,0.004,0.996,0.002,0.208
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones:
          - driveway
        labels: 
          - person
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package
      detections: {}
    mqtt:
      quality: 100
      required_zones:
        - driveway

go2rtc:
  streams:
    front_doorbell:
      - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus#async
      - rtsp://xxxx:xxxx@192.168.8.186:554/h264Preview_01_sub
    front_doorbell_sub:
      - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx
    front_door: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
    front_east: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=2&subtype=0
    front_entrance_east: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=5&subtype=0
    front_entrance_east_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=5&subtype=1
    front_entrance_west: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=6&subtype=0
    west_side_back: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=12&subtype=0
    east_side_house: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=8&subtype=0
    back_garden: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=3&subtype=0
    backyard: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=7&subtype=0
    back_landing: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=4&subtype=0
    bar_landing: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=10&subtype=0
    deck_stairs: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=9&subtype=0
    deck_door: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=11&subtype=0
    deck_door_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=11&subtype=1

  webrtc:
    candidates:
      - 192.168.8.85:8555
      - stun:8555
snapshots:
  enabled: true
  required_zones:
    - driveway
  clean_copy: false
  timestamp: true
  bounding_box: True
  crop: true
  height: 270
  quality: 100

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac #this allows audio in recordings 
  hwaccel_args: preset-vaapi

model:
  path: plus://9611b11ed8a2a025a5a31fd7898db08e

timestamp_style:
  position: bl
  format: '%-I:%M:%S %p %Y-%m-%d'
  color:
    red: 0
    green: 0
    blue: 0

# logger:
#   default: debug
#   logs:
#     frigate.mqtt: debug

version: 0.14
```
