### DISCUSSION TITLE
[Camera Support]: Live video is not showing on ios

### DISCUSSION THREAD

**Discussion by izzygold** [blakeblackshear/frigate#13373] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When opening a specific camera in live view, only on IOS, some cameras show "loading" forever.
These cameras work perfectly in the "all cameras" live view, and in "review" page.

I looked in the safary console (through my mac) and I see the I get the following error:

WebSocket connection to 'wss://mydomain.com/live/webrtc/api/ws?src=eastern_path' failed: The operation couldn’t be completed. Socket is not connected

### Steps to reproduce

Use chrome/safari on iphone 13pro, get the the main frigate ui and press one of the cameras.

I would be happy to provide credentails and my url for you to try it out, can I mail it to you? to which address?

### Version

0.14

### In which browser(s) are you experiencing the issue with?

Crhome 128.0.6613.92

### Frigate config file

```yaml
mqtt:
  host: 192.168.68.65
  user: frigate
  password: 

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi


go2rtc:
  streams:
    back_forest:
      - rtsp://IP.71:554/1
    entrance_car:
      - rtsp://IP.106:554/1
    front_yard:
      - rtsp://IP.108:554/1
    eastern_path:
      - rtsp://IP.75:554/1
audio:
  enabled: true
  listen:
    - explosion
    - gunshot
    - machine_gun
    - artillery_fire
    - cap_gun
    - fireworks
    - siren
    - civil_defense_siren
    - aircraft
    - aircraft_engine
    - bang
    - woosh
    - thump
    - thunk
  filters:
    civil_defense_siren:
      threshold: 0.5

tls:
  enabled: false

motion:
  threshold: 20

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front_yard: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
        host: 192
        port: 8899
        user: 
        password: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://IP.108:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: true
    zones:
      street:
        coordinates: 
          0.668,0.232,0.666,0.461,0.675,0.473,0.717,0.41,0.771,0.388,0.785,0.392,0.797,0.282,0.797,0.255,0.792,0.243,0.77,0.237,0.732,0.233,0.705,0.234,0.692,0.233
        loitering_time: 0
      Yard:
        coordinates: 
          0.06,0.321,0.275,0.262,0.409,0.262,0.608,0.212,0.667,0.225,0.664,0.434,0.712,0.425,0.742,0.405,0.779,0.394,0.788,0.387,0.795,0.305,0.79,0.263,0.79,0.246,0.823,0.246,0.854,0.258,0.867,0.275,0.884,0.316,0.927,0.326,0.958,0.32,0.969,0.324,0.99,0.345,0.99,0.571,0.949,0.942,0.924,0.999,0.103,0.998,0.007,0.425,0.003,0.295
        inertia: 1
        loitering_time: 0
    review:
      alerts:
        required_zones: Yard
  entrance_car: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
        host: 192.168.68.106
        port: 8899
        user: 
        password:     
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://IP.106:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: true

    zones:
      road:
        coordinates: 
          0.133,0.208,0.123,0.178,0.156,0.11,0.242,0.077,0.351,0.059,0.409,0.155,0.486,0.147,0.512,0.085,0.604,0.06,0.783,0.068,0.85,0.101,0.872,0.117,0.932,0.118,0.984,0.13,0.946,0.328,0.828,0.356,0.637,0.343,0.493,0.336,0.416,0.327,0.367,0.346,0.238,0.389,0.162,0.394,0.14,0.391
        loitering_time: 0
      street:
        coordinates: 
          0.145,0.401,0.341,0.363,0.401,0.336,0.785,0.35,0.864,0.365,0.858,0.503,0.302,0.5,0.169,0.479
        loitering_time: 0
      Parking:
        coordinates: 
          0.162,0.47,0.331,0.541,0.474,0.528,0.688,0.528,0.866,0.527,0.955,0.862,0.909,0.964,0.867,0.986,0.101,0.992,0.073,0.926,0.036,0.949,0.001,0.947,0.004,0.28,0.081,0.217,0.134,0.412
        loitering_time: 0
    review:
      alerts:
        required_zones: Parking
  back_forest: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.68.71
      port: 8899
      user: 
      password: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://IP.71:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: true

  eastern_path: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
        host: 192.168.68.75
        port: 8899
        user: 
        password:     
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://IP.75:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 90
          mode: motion
    snapshots:
      enabled: true
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    privileged: true
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8555:8555"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
```

### Relevant Frigate log output

```shell
nothing relevant is shown on the logs
```

### Relevant go2rtc log output

```shell
nothing relevant is shown on the logs
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision, dont know which model, all cameras are the same model

### Screenshots of the Frigate UI's System metrics pages

not relevant
