### DISCUSSION TITLE
[Camera Support]: Intermittent graphics error in live display since update to .14; colour shifting

### DISCUSSION THREAD

**Discussion by nsprawling** [blakeblackshear/frigate#13377] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

On two cameras, colours for the video feed are offset/incorrectly placed relative to the video feed itself in the live view of the Frigate UI.
![image](https://github.com/user-attachments/assets/7399e2d8-0b14-42c9-94b7-412b5fa868a7)
![image](https://github.com/user-attachments/assets/beff75f9-aedb-4c7a-95a8-3262c9838435)

This only occurs in the live view for 2 of our 5 cameras. Both are unique types; one is a hikvision ptz, the other a rpi zero with a zerocam. The bug is not apparent in recordings or birdseye. The bug does not always occur immediately on loading the feed but is persistent across browser and device once it occurs. 

Have had a good look for similar issues reported and couldn't see.

### Steps to reproduce

Issue has occurred since updating to 0.14 without any specific interactions.

### Version

0.14.0-da913d8

### In which browser(s) are you experiencing the issue with?

Chrome 128.0.6613.85, Edge 128.0.2739.42, iOS Safari / OSX Safari

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.60.205
  port: 1883
  user: mqtt
  password: mqtt

detectors:
  coral:
    type: edgetpu
    device: pci:0

#hwaccel
ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  stationary:
    threshold: 50

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - bus
    - motorcycle
    - cat
    - dog

record:
  enabled: true
  events:
    retain:
      default: 7
      mode: active_objects
      objects:
        car: 14
        bus: 14
        motorcycle: 14

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: true
  # Optional: Width of the output resolution (default: shown below)
  width: 3840
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 10
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

cameras:
  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://--@192.168.60.2:554/Streaming/Channels/101 # <----- The stream you want to use for recording
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,0,3101,0,3040,632,0,409
    objects:
      mask:
        - 0,0,3101,0,3040,632,0,409
        - 1175,1236,1296,1245,1296,1045,1196,1036
        - 1677,631,1713,634,1719,520,1677,517

  Yard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://--@192.168.60.2:554/Streaming/Channels/301 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
    objects:
      filters:
        car:
          mask:
            - 2273,729,2303,427,3096,516,3223,749,2885,848
        person:
          mask:
            - 3685,427,3772,698,3433,708,3433,398

  Farmhouse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://--@192.168.60.2:554/Streaming/Channels/201 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,1171,622,1117,719,848,523,640,264,0,0,0
    objects:
      mask:
        - 0,1171,622,1117,719,848,523,640,264,0,0,0
      filters:
        car:
          mask:
            - 3556,1650,3360,2160,1414,2160,767,1066,1157,861

  YardPTZ: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://--@192.168.60.2:554/Streaming/Channels/401 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 2550 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
    objects:
      filters:
        car:
          mask:
            - 0,1440,1571,1440,1533,724,0,792

  PrintCam: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.60.207:8554/cam # <----- The stream you want to use for detection
      hwaccel_args: preset-vaapi
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 2550 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
    birdseye:
      enabled: false
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/nspr/frigate/config:/config
      - /home/nspr/frigate/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "--"
```

### Relevant Frigate log output

```shell
Don't see relevant logs
```

### Relevant go2rtc log output

```shell
Don't see relevant logs
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Mixed Hikvision & rpi using MediaMtx

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a71fa4a6-fdd1-4f89-a04f-5cddc1a7eaab)
![image](https://github.com/user-attachments/assets/c000e552-804f-4ff7-bd3b-5611d45bcaa5)
