### DISCUSSION TITLE
[Config Support]: "Car/Person Entering Driveway" - Objects moving from one zone to another trigger (crossing lines)

### DISCUSSION THREAD

**Discussion by xeryax** [blakeblackshear/frigate#13384] [Config Support]
### Describe the problem you are having

I am having an issue with my config, where i _think_ i have things configured correctly, but they dont seem to be working as desired.
As you can see in my debug window below, I have two zones "Outside" circled in blue, and "Driveway" circled in Yellow.

I don't care about when a person walks from the grass into the driveway, I only care when someone walks into the driveway from the blue, or when a car drives in from the blue.

I have tried a few configurations where the zones share a border, where they overlap (current config), and when they dont touch. I've even tried a tiered zone entering my driveway hoping that an event fires when the before message contains "outside" and the after contains "driveway", but it seems the events dont fire enough for me to adequately track that particular case...

What am I missing here? Are there any examples of what I am trying to do in a sample config somewhere? (apologies, my google/git search-fu came up short).

Moreso than just capturing a video event/snapshot, I'd like to be able to fire an event (in either mqtt/homeassistant/nodered so that i can trigger a high res snapshot from the same camera for ALPR/Facial Rec, etc.) As I am not sending a 4k signal through frigate for detection :)

![image](https://github.com/user-attachments/assets/9233760d-6ca4-4428-936d-3498eeeb31a1)

### Version

0.14.0-da913d8

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: <IP1>
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: <username>
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: <password>
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
go2rtc:
  streams:
    GarageFrontyard:
      - rtspx://<IP1>
    office:
      - rtspx://<IP1>
    doorbell:
      - rtspx://<IP1>

cameras:
  GarageFrontyard:
    ffmpeg:
      inputs:
        - path: rtsps://<IP1>
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
    zones:
      driveway:
        coordinates: 
          0.209,0.096,0.186,0.224,0.158,0.419,0.14,0.603,0.143,0.844,0.153,0.987,0.997,0.993,0.996,0.749,0.814,0.589,0.716,0.478,0.597,0.342,0.517,0.232,0.455,0.15,0.42,0.092
        loitering_time: 0
        inertia: 3
      outside:
        coordinates: 
          0,0.09,0.206,0.065,0.206,0.117,0.433,0.114,0.413,0.065,0.481,0.068,0.541,0.075,0.628,0.097,0.684,0.125,0.759,0.186,0.866,0.234,0.954,0.308,1,0.351,1,0,0,0
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.004,0.033,0.161,0.034,0.161,0.007,0.003,0.007
      threshold: 34
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections: {}
    snapshots:
      required_zones:
        - driveway

  office:
    ffmpeg:
      inputs:
        - path: rtsps://<IP1>
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp

    zones:
      outside:
        coordinates: 0.347,0.9,0.338,0.225,0.49,0.207,0.5,0.904
        loitering_time: 0
        inertia: 3
      office_z:
        coordinates: 0.338,0,0.347,0.905,0.502,0.902,0.487,0,1,0,1,1,0,1,0,0
        loitering_time: 0
        inertia: 3

  doorbell:
    ffmpeg:
      inputs:
        - path: rtsps://<IP1>
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    motion:
      mask: 0.095,0.025,0.161,0.028,0.163,0.006,0.003,0.006,0.002,0.026
    zones:
      frontwalk:
        coordinates: 
          0.605,0.627,0.666,0.662,0.732,0.702,0.826,0.775,0.901,0.849,0.967,0.974,0.974,0.999,0.439,0.999,0.421,0.761,0.568,0.727,0.642,0.773,0.667,0.73,0.614,0.678,0.561,0.648
        loitering_time: 0
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: False
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70
  
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -c:v h264_cuvid
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3
version: 0.14
```

### Relevant Frigate log output

```shell
no errors
```

### Relevant go2rtc log output

```shell
no errors
```

### Frigate stats

```json
{"cameras":{"GarageFrontyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":529,"detection_enabled":true,"detection_fps":6.8,"ffmpeg_pid":537,"pid":512,"process_fps":5.1,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":543,"detection_enabled":true,"detection_fps":5.6,"ffmpeg_pid":554,"pid":521,"process_fps":5.1,"skipped_fps":0.0},"office":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":538,"detection_enabled":true,"detection_fps":2.0,"ffmpeg_pid":549,"pid":513,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"4.4","cpu_average":"6","mem":"0.6"},"128":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"171":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"350":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"399":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.2"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"464":{"cmdline":"frigate.recording_manager","cpu":"0.7","cpu_average":"0","mem":"0.2"},"472":{"cmdline":"frigate.review_segment_manager","cpu":"0.9","cpu_average":"0","mem":"0.2"},"48502":{"cmdline":"frigate.detector.coral","cpu":"26.2","cpu_average":"25","mem":"0.4"},"492":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)","cpu":"0.4","cpu_average":"0","mem":"0.0"},"495":{"cmdline":"frigate.output       ","cpu":"5.0","cpu_average":"3","mem":"0.2"},"512":{"cmdline":"frigate.process:GarageFrontyard","cpu":"40.2","cpu_average":"37","mem":"0.3"},"513":{"cmdline":"frigate.process:office","cpu":"8.9","cpu_average":"15","mem":"0.3"},"521":{"cmdline":"frigate.process:doorbell","cpu":"28.2","cpu_average":"9","mem":"0.2"},"529":{"cmdline":"frigate.capture:GarageFrontyard","cpu":"2.9","cpu_average":"2","mem":"0.2"},"537":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsps://172.18.15.1:7441/miGqJbr1si2Ws9Sf?enableSrtp -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -f rawvideo -pix_fmt yuv420p pipe:","cpu":"17.7","cpu_average":"15","mem":"0.4"},"538":{"cmdline":"frigate.capture:office","cpu":"2.9","cpu_average":"2","mem":"0.2"},"543":{"cmdline":"frigate.capture:doorbell","cpu":"2.3","cpu_average":"2","mem":"0.2"},"549":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsps://172.18.15.1:7441/rZTfAMHHsGZe247A?enableSrtp -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -f rawvideo -pix_fmt yuv420p pipe:","cpu":"17.4","cpu_average":"15","mem":"0.4"},"554":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsps://172.18.15.1:7441/MMRD7BTZDYMLl37x?enableSrtp -r 5 -vf fps=5,scale_cuda=w=960:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -f rawvideo -pix_fmt yuv420p pipe:","cpu":"15.7","cpu_average":"13","mem":"0.4"},"570":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"575":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"580":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 960x720 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"585":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"84999":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"85005":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"15.5","mem":"10.7"}},"detection_fps":14.4,"detectors":{"coral":{"detection_start":1724786503.551204,"inference_speed":33.33,"pid":48502}},"gpu_usages":{"Quadro P2200":{"dec":"61.0%","enc":"100.0%","gpu":"36.0%","mem":"29.06%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":399},"recording":{"pid":464},"review_segment":{"pid":472}},"service":{"last_updated":1724786503,"latest_version":"0.14.0","storage":{"/dev/shm":{"free":499.3,"mount_type":"tmpfs","total":512.0,"used":12.7},"/media/frigate/clips":{"free":60399.2,"mount_type":"ext4","total":100220.9,"used":34685.7},"/media/frigate/recordings":{"free":60399.2,"mount_type":"ext4","total":100220.9,"used":34685.7},"/tmp/cache":{"free":60399.2,"mount_type":"ext4","total":100220.9,"used":34685.7}},"temperatures":{},"uptime":90017,"version":"0.14.0-da913d8"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/7d32f956-5be4-4d34-93ee-77f4f06a6eb9)
![image](https://github.com/user-attachments/assets/10e3b5b9-7a7e-41eb-a02a-b4415bd00b27)
![image](https://github.com/user-attachments/assets/ce239190-adda-49f0-8d78-037effd89239)

### Any other information that may be helpful

The event object that came from MQTT during a valid event where a person walked from "outside" to "driveway" as you can see, for whatever reason frigate detected this as a new object/event, rather than an update from an existing tracked person.
`{"before":{"id":"1724783410.502817-tc652c","camera":"GarageFrontyard","frame_time":1724783410.502817,"snapshot":null,"label":"person","sub_label":null,"top_score":0,"false_positive":true,"start_time":1724783410.502817,"end_time":null,"score":0.640625,"box":[289,21,319,78],"area":1710,"ratio":0.5263157894736842,"region":[80,0,884,804],"stationary":false,"motionless_count":0,"position_changes":0,"current_zones":[],"entered_zones":[],"has_clip":false,"has_snapshot":false,"attributes":{},"current_attributes":[]},"after":{"id":"1724783410.502817-tc652c","camera":"GarageFrontyard","frame_time":1724783416.304023,"snapshot":{"frame_time":1724783416.304023,"box":[240,15,310,174],"area":11130,"region":[126,0,446,320],"score":0.84375,"attributes":[]},"label":"person","sub_label":null,"top_score":0.701171875,"false_positive":false,"start_time":1724783410.502817,"end_time":null,"score":0.84375,"box":[240,15,310,174],"area":11130,"ratio":0.44025157232704404,"region":[126,0,446,320],"stationary":false,"motionless_count":3,"position_changes":1,"current_zones":["driveway"],"entered_zones":["driveway"],"has_clip":false,"has_snapshot":false,"attributes":{},"current_attributes":[]},"type":"new","zone":"driveway"}`

This is an event from a person stepping out of a car that had previously triggered an event:

`{"before":{"id":"1724778919.506644-h9nbzr","camera":"GarageFrontyard","frame_time":1724778920.088075,"snapshot":{"frame_time":1724778920.088075,"box":[732,215,886,372],"area":24178,"region":[666,130,986,450],"score":0.8046875,"attributes":[]},"label":"person","sub_label":null,"top_score":0.701171875,"false_positive":false,"start_time":1724778919.506644,"end_time":null,"score":0.8046875,"box":[732,215,886,372],"area":24178,"ratio":0.9808917197452229,"region":[666,130,986,450],"stationary":false,"motionless_count":1,"position_changes":0,"current_zones":[],"entered_zones":[],"has_clip":false,"has_snapshot":false,"attributes":{},"current_attributes":[]},"after":{"id":"1724778919.506644-h9nbzr","camera":"GarageFrontyard","frame_time":1724778921.086415,"snapshot":{"frame_time":1724778920.088075,"box":[732,215,886,372],"area":24178,"region":[666,130,986,450],"score":0.8046875,"attributes":[]},"label":"person","sub_label":null,"top_score":0.736328125,"false_positive":false,"start_time":1724778919.506644,"end_time":null,"score":0.74609375,"box":[769,243,874,381],"area":14490,"ratio":0.7608695652173914,"region":[628,123,948,443],"stationary":false,"motionless_count":3,"position_changes":0,"current_zones":["driveway"],"entered_zones":["driveway"],"has_clip":false,"has_snapshot":false,"attributes":{},"current_attributes":[]},"type":"update","zone":"driveway"}`
