### DISCUSSION TITLE
[Support]: Update from 0.13.2 to 0.14.0 not working

### DISCUSSION THREAD

**Discussion by nulkathos** [blakeblackshear/frigate#13380] [General Support]
### Describe the problem you are having

I update the configuration inside the compose file using the image "ghcr.io/blakeblackshear/frigate:0.14.0"
The frigate starts but the page is empty and I can see only the bar on the left side.
I tried to go to setting page or to see the system log but without success. the system seems like is loading something and the performance low but the final result is that is not showing nothing.
Camera page are not showing anything.
![image](https://github.com/user-attachments/assets/124a6b22-30af-4f33-bed8-7e96ccc03675)
![image](https://github.com/user-attachments/assets/c70aca43-a5af-46bc-85dc-212828bb81c1)
the only page that is working:
![image](https://github.com/user-attachments/assets/06248a59-0407-4bc6-addc-50c5c68c7c83)

### Version

0.14.0

### What browser(s) are you using?

chrome 128.0.6613.85

### Frigate config file

```yaml
# ~/docker/frigate/config.yml
# yaml-language-server: $schema=http://192.168.88.222:5000/api/config/schema.json

ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 192.168.88.220
  port: 1883
  user: mqttusr
  password: XXXXXXXXXXXXXXXXXX
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

record:
  expire_interval: 10

ffmpeg:
  hwaccel_args: preset-nvidia-h264 
#  hwaccel_args: preset-intel-qsv-h264

detectors: # <---- add detectors
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

model:
  path: plus://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
logger:
  default: info

rtmp:
  enabled: false

live:
  height: 1280
  quality: 1

birdseye:
  enabled: True
  #restream: false
  width: 1280
  height: 720
  quality: 1
  mode: continuous

go2rtc:
  streams:
    ovestnord:
      - rtsp://viewer:XXXXXXXXX@192.168.88.244:554/cam/realmonitor?channel=1&subtype=0
    ovestnord_sub:
      - rtsp://viewer:XXXXXXXXXXX@192.168.88.244:554/cam/realmonitor?channel=1&subtype=2
    nordovest:
      - rtsp://viewer:XXXXXXXXXXX@192.168.88.243:554/cam/realmonitor?channel=1&subtype=0
    nordovest_sub:
      - rtsp://viewer:XXXXXXXXXXXXXXXXXX@192.168.88.243:554/cam/realmonitor?channel=1&subtype=2
    nordest:
      - rtsp://viewer:XXXXXXXXXXXXXX@192.168.88.242:554/cam/realmonitor?channel=1&subtype=0
    nordest_sub:
      - rtsp://viewer:XXXXXXXXXXXXXXX@192.168.88.242:554/cam/realmonitor?channel=1&subtype=2
    estnord:
      - rtsp://viewer:XXXXXXXXXXXX@192.168.88.241:554/cam/realmonitor?channel=1&subtype=0
    estnord_sub:
      - rtsp://viewer:XXXXXXXXXXXXX@192.168.88.241:554/cam/realmonitor?channel=1&subtype=2
    estsud:
      - rtsp://viewer:XXXXXXXXXXXXXXX@192.168.88.240:554/cam/realmonitor?channel=1&subtype=0
    estsud_sub:
      - rtsp://viewer:XXXXXXXXXXX@192.168.88.240:554/cam/realmonitor?channel=1&subtype=2
    sudest:
      - rtsp://viewer:XXXXXXXXXXX@192.168.88.238:554/cam/realmonitor?channel=1&subtype=0
    sudest_sub:
      - rtsp://viewer:XXXXXXXXXXX@192.168.88.238:554/cam/realmonitor?channel=1&subtype=2
    sudovest:
      - rtsp://viewer:XXXXXXXXXXXXXX@192.168.88.239:554/cam/realmonitor?channel=1&subtype=0
    sudovest_sub:
      - rtsp://viewer:XXXXXXXXXXX@192.168.88.239:554/cam/realmonitor?channel=1&subtype=2
    webrtc:
      candidates:
        - 192.168.88.222:8555

cameras:
  ovestnord:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/ovestnord_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/ovestnord
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          min_score: .80
          threshold: .85
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 1

  nordovest:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/nordovest_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/nordovest
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          min_score: .80
          threshold: .85
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 2

  nordest:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/nordest_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/nordest
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
       # - car
      filters:
        person:
          min_score: .80
          threshold: .85
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 3

  estnord:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/estnord_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/estnord
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
      #  - car
      filters:
        person:
          min_score: .80
          threshold: .85
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 4

  estsud:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/estsud_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/estsud
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
       # - car
      filters:
        person:
          min_score: .80
          threshold: .85
     #   car:
      #    mask:
      #      - 0,1140,1217,642,2658,513,3840,1412,3840,2160,0,2160
       #     - 2774,360,2784,287,2993,349,2974,440,2877,429
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 5

  sudest:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/sudest_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/sudest
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
       # - car
      filters:
        person:
          min_score: .80
          threshold: .85
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 6

  sudovest:
    ffmpeg:
      inputs:
     #   - path: rtsp://127.0.0.1:8554/sudovest_sub
      #    input_args: preset-rtsp-restream
      #    roles:
       #     - detect
        - path: rtsp://127.0.0.1:8554/sudovest
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 6
    objects:
      track:
        - person
      #  - car
      filters:
        person:
          min_score: .80
          threshold: .85
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 15
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 7
        post_capture: 15
    birdseye:
      order: 7
```

### Relevant Frigate log output

```shell
no log can be retrieved
```

### Relevant go2rtc log output

```shell
no log can be retrieved
```

### FFprobe output from your camera

```shell
no log can be retrieved
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision ds-2cd2t86g2-4i

### Screenshots of the Frigate UI's System metrics pages

metrics page not available
