### DISCUSSION TITLE
[Support]: No Audio in recordings

### DISCUSSION THREAD

**Discussion by rici44** [blakeblackshear/frigate#13395] [General Support] [answered]
### Describe the problem you are having

I have no audio in recordings.

### Version

0.14.0-da913d8

### What browser(s) are you using?

Google Chrome Version 127.0.6533.120 (Official Build) (arm64)

### Frigate config file

```yaml
mqtt:
  enabled: false

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  coral:
    type: edgetpu
    device: usb

# Optional: ffmpeg configuration
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: auto
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy

# Optional: Detect configuration
detect:
  width: 640
  height: 480
  fps: 5
  enabled: true
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50

# Optional: Object configuration
objects:
  track:
    - person
    - car
    - dog
    - cat
    - bus
    - motorcycle

# Optional: Motion configuration
motion:
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 100
  mask:
    - 438,24,445,48,611,46,612,24
  improve_contrast: true

# Optional: Record configuration
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 1
    mode: all
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: false
  height: 175
  retain:
    default: 1
  quality: 70

go2rtc:
  streams:
    camera_vpredu:
      - rtsp://admin:xxxxx@192.168.0.142:554/stream1
      - ffmpeg:camera_vpredu#audio=opus
    camera_vpredu_sub:
      - rtsp://admin:xxxxx@192.168.0.142:554/stream2
      - ffmpeg:camera_vpredu_sub#audio=opus
    camera_vzadu:
      - rtsp://admin:xxxxx@192.168.0.143:554/stream1
      - ffmpeg:camera_vzadu#audio=opus
    camera_vzadu_sub:
      - rtsp://admin:xxxxx@192.168.0.143:554/stream2
      - ffmpeg:camera_vzadu_sub#audio=opus
    camera_vratnik:
      - rtsp://admin:xxxxx@192.168.0.109:554/stream1
      - ffmpeg:camera_vratnik#audio=opus

cameras:
  camera_vpredu:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_vpredu
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_vpredu_sub
          roles:
            - detect
    live:
      stream_name: camera_vpredu_sub
      height: 480
      quality: 16

    motion:
      mask: 0.005,0.011,0.006,0.108,0.258,0.11,0.256,0.012

  camera_vzadu:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_vzadu
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_vzadu_sub
          roles:
            - detect
    live:
      stream_name: camera_vzadu_sub
      height: 480
      quality: 16

  camera_vratnik:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_vratnik
          roles:
            - detect
            - record
    live:
      stream_name: camera_vratnik
      height: 480
      quality: 16

version: 0.14
camera_groups: {}
```

### Relevant Frigate log output

```shell
2024-08-28 11:23:08.517580589  [INFO] Preparing Frigate...
2024-08-28 11:23:08.633167740  [INFO] Starting Frigate...
2024-08-28 11:23:16.878861066  [2024-08-28 11:23:16] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
2024-08-28 11:23:16.879605446  [2024-08-28 11:23:16] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-08-28 11:23:17.071192563  [2024-08-28 11:23:17] frigate.util.config            INFO    : frigate config does not need migration...
2024-08-28 11:23:17.564603280  [2024-08-28 11:23:17] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2024-08-28 11:23:17.692480284  [2024-08-28 11:23:17] peewee_migrate.logs            INFO    : Starting migrations
2024-08-28 11:23:17.697849620  [2024-08-28 11:23:17] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-08-28 11:23:17.719859581  [2024-08-28 11:23:17] frigate.app                    INFO    : Recording process started: 382
2024-08-28 11:23:17.737690281  [2024-08-28 11:23:17] frigate.app                    INFO    : Recording process started: 388
2024-08-28 11:23:17.758245900  [2024-08-28 11:23:17] frigate.app                    INFO    : go2rtc process pid: 96
2024-08-28 11:23:17.841792046  [2024-08-28 11:23:17] detector.coral                 INFO    : Starting detection process: 410
2024-08-28 11:23:17.853079378  [2024-08-28 11:23:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-08-28 11:23:17.859052794  [2024-08-28 11:23:17] frigate.app                    INFO    : Output process started: 412
2024-08-28 11:23:18.009887151  [2024-08-28 11:23:17] frigate.app                    INFO    : Camera processor started for camera_vpredu: 430
2024-08-28 11:23:18.059660267  [2024-08-28 11:23:18] frigate.app                    INFO    : Camera processor started for camera_vzadu: 435
2024-08-28 11:23:18.083435505  [2024-08-28 11:23:18] frigate.app                    INFO    : Camera processor started for camera_vratnik: 438
2024-08-28 11:23:18.107783320  [2024-08-28 11:23:18] frigate.app                    INFO    : Capture process started for camera_vpredu: 443
2024-08-28 11:23:18.133481054  [2024-08-28 11:23:18] frigate.app                    INFO    : Capture process started for camera_vzadu: 451
2024-08-28 11:23:18.177252752  [2024-08-28 11:23:18] frigate.app                    INFO    : Capture process started for camera_vratnik: 461
2024-08-28 11:23:20.589440985  [2024-08-28 11:23:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
2024-08-28 11:23:08.604925056  [INFO] Preparing new go2rtc config...
2024-08-28 11:23:10.701635628  [INFO] Starting go2rtc...
2024-08-28 11:23:10.885420756  11:23:10.885 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2
2024-08-28 11:23:10.885502428  11:23:10.885 INF config path=/dev/shm/go2rtc.yaml
2024-08-28 11:23:10.887834449  11:23:10.887 INF [api] listen addr=:1984
2024-08-28 11:23:10.888705712  11:23:10.887 INF [rtsp] listen addr=:8554
2024-08-28 11:23:10.889441050  11:23:10.889 INF [webrtc] listen addr=:8555/tcp
2024-08-28 11:23:18.524161799  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.0.142/stream1/",
      "remote_addr": "192.168.0.142:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1724844384670865 1 IN IP4 192.168.0.142\r\ns=stream server\r\ni=stream1\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2014.03.25\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:stream server\r\na=x-qt-text-inf:stream1\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:1228\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D4032;sprop-parameter-sets=Z01AMpWgCQAwabAQ,aO48gA==\r\na=Media_header:MEDIAINFO=494D4B48010100000400010010710110401F000000FA000000000000000000000000000000000000\r\na=framerate:15\r\na=framesize:96 2304-1536\r\na=control:trackID=1\r\nm=audio 0 RTP/AVP 8\r\nc=IN IP4 0.0.0.0\r\nb=AS:12\r\na=control:trackID=2\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.0",
        "audio, recvonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=260939307, senders=2",
        "8 PCMA/8000, bytes=5261600, senders=2"
      ],
      "recv": 268533515
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/5042b1261134cf7ccd7c4906d5960e2f",
      "remote_addr": "127.0.0.1:33404",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.9.2\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat 60.16.100\r\nm=audio 0 RTP/AVP 96\r\nb=AS:64\r\na=rtpmap:96 opus/48000/2\r\na=control:streamid=0\r\n",
      "medias": [
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 OPUS/48000/2, bytes=0, senders=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/camera_vpredu",
      "remote_addr": "127.0.0.1:58598",
      "user_agent": "FFmpeg Frigate/0.14.0-da913d8",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D4032;sprop-parameter-sets=Z01AMpWgCQAwabAQ,aO48gA==\r\na=control:trackID=0\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=379988548, receivers=1"
      ],
      "send": 383991059
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/camera_vpredu?audio",
      "remote_addr": "127.0.0.1:33402",
      "user_agent": "go2rtc/ffmpeg",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 PCMA/8000\r\na=control:trackID=0\r\n",
      "medias": [
        "audio, sendonly, ANY"
      ],
      "senders": [
        "96 PCMA/8000, bytes=1600, receivers=1"
      ],
      "send": 1632
    },
    {
      "type": "probe",
      "remote_addr": "10.11.11.7:51194",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "8 PCMA/8000, bytes=0, receivers=1",
        "96 OPUS/48000/2, bytes=0, receivers=1"
      ]
    }
  ]
}
```

### Frigate stats

```json
{"cameras":{"camera_vpredu":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":443,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":456,"pid":430,"process_fps":5.0,"skipped_fps":0.0},"camera_vratnik":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":461,"detection_enabled":true,"detection_fps":4.3,"ffmpeg_pid":472,"pid":438,"process_fps":5.0,"skipped_fps":0.0},"camera_vzadu":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":451,"detection_enabled":true,"detection_fps":1.8,"ffmpeg_pid":470,"pid":435,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"5.6","cpu_average":"9","mem":"3.6"},"114":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"130":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"14":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"164":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"177":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1956":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(49)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"23":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"301":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"348":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"1.6"},"382":{"cmdline":"frigate.recording_manager","cpu":"6.9","cpu_average":"9","mem":"1.8"},"388":{"cmdline":"frigate.review_segment_manager","cpu":"1.3","cpu_average":"1","mem":"1.7"},"409":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)","cpu":"0.8","cpu_average":"0","mem":"0.1"},"410":{"cmdline":"frigate.detector.coral","cpu":"8.9","cpu_average":"10","mem":"1.9"},"412":{"cmdline":"frigate.output       ","cpu":"6.2","cpu_average":"6","mem":"1.8"},"43":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"430":{"cmdline":"frigate.process:camera_vpredu","cpu":"4.1","cpu_average":"4","mem":"1.8"},"435":{"cmdline":"frigate.process:camera_vzadu","cpu":"5.2","cpu_average":"5","mem":"1.9"},"438":{"cmdline":"frigate.process:camera_vratnik","cpu":"10.5","cpu_average":"9","mem":"1.8"},"443":{"cmdline":"frigate.capture:camera_vpredu","cpu":"1.7","cpu_average":"1","mem":"1.7"},"4496":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"451":{"cmdline":"frigate.capture:camera_vzadu","cpu":"1.7","cpu_average":"1","mem":"1.7"},"456":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/camera_vpredu_sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.8","cpu_average":"7","mem":"0.4"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"461":{"cmdline":"frigate.capture:camera_vratnik","cpu":"1.7","cpu_average":"1","mem":"1.7"},"4622":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"470":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/camera_vzadu_sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.1","cpu_average":"7","mem":"0.4"},"472":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/camera_vratnik -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/camera_vratnik@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.4","cpu_average":"7","mem":"0.4"},"474":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/camera_vpredu -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/camera_vpredu@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"1","mem":"0.3"},"477":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-da913d8 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/camera_vzadu -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/camera_vzadu@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"1","mem":"0.3"},"529":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 640x480 -codec:v mpeg1video -q 16 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"534":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 640x480 -codec:v mpeg1video -q 16 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"546":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 640x480 -codec:v mpeg1video -q 16 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"553":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"84":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"96":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"13.7","cpu_average":"13","mem":"0.4"},"frigate.full_system":{"cpu":"27.9","mem":"19.9"}},"detection_fps":6.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":15.27,"pid":410}},"processes":{"go2rtc":{"pid":96},"logger":{"pid":348},"recording":{"pid":382},"review_segment":{"pid":388}},"service":{"last_updated":1724837993,"latest_version":"0.14.0","storage":{"/dev/shm":{"free":1020.3,"mount_type":"tmpfs","total":1024.0,"used":3.7},"/media/frigate/clips":{"free":149591.0,"mount_type":"ext4","total":233466.6,"used":71948.1},"/media/frigate/recordings":{"free":149591.0,"mount_type":"ext4","total":233466.6,"used":71948.1},"/tmp/cache":{"free":1867.0,"mount_type":"tmpfs","total":1907.4,"used":40.4}},"temperatures":{},"uptime":995,"version":"0.14.0-da913d8"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hiseeu ipcam-100

### Screenshots of the Frigate UI's System metrics pages

<img width="2003" alt="Screenshot 2024-08-28 at 11 46 09" src="https://github.com/user-attachments/assets/2712e2ad-4c5c-40da-9edc-8ff84737edee">

**Comment by hawkeye217** [comment]
See the documentation: https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Comment by rici44** [comment]
Yes, I read it and already tested it, but not luck so far.

**Reply by NickM-27** [reply, marked as answer]
Your cameras are likely not using aac by default. You need to update the go2rtc config to have `aac` instead of `opus`

**Reply by rici44** [reply]
I changed go2rtc part like this:
```
go2rtc:
  streams:
    camera_vpredu:
      - rtsp://admin:xxxxx@192.168.0.142:554/stream1
      - ffmpeg:camera_vpredu#audio=aac
    camera_vpredu_sub:
      - rtsp://admin:xxxxx@192.168.0.142:554/stream2
      - ffmpeg:camera_vpredu_sub#audio=aac
    camera_vzadu:
      - rtsp://admin:xxxxx@192.168.0.143:554/stream1
      - ffmpeg:camera_vzadu#audio=aac
    camera_vzadu_sub:
      - rtsp://admin:xxxxx@192.168.0.143:554/stream2
      - ffmpeg:camera_vzadu_sub#audio=aac
    camera_vratnik:
      - rtsp://admin:xxxxx@192.168.0.109:554/stream1
      - ffmpeg:camera_vratnik#audio=aac
```
And I tested VLC on go2rtc links:
rtsp with only one video and one audio / codecs: any - AUDIO WORKS
rtsp for MP4 recording (Hass or Frigate) / codecs: H264, H265, AAC - AUDIO WORKS
rtsp with all tracks / codecs: any - AUDIO WORKS

But recording in Frigate is WITHOUT AUDIO
