### DISCUSSION TITLE
[Config Support]: Blocked myself from go2rtc API with `listen: "127.0.0.1:1984"` 🤦‍♂️

### DISCUSSION THREAD

**Discussion by jparthum** [blakeblackshear/frigate#13393] [Config Support] [answered]
### Describe the problem you are having

I'm migrating from HA Frigate add-on to a Proxmox Frigate LXC and hastily blocked API access to all but the Frigate/go2rtc container (localhost).
I've already tried adding this to Frigate config in hopes it would override saved go2rtc config, but no luck:
```
go2rtc:
  api:
    listen: ":1984"
```
I do have SSH access.  Is there something similar to a `go2rtc.yaml` that I can edit?

### Version

0.14.0- (verbatim from `\system` page)

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 7

snapshots:
  enabled: True
  retain:
    default: 30

detect:
  enabled: false

go2rtc:
#  api:
#    listen: ":1984"
  streams:
    frontptz: onvif://user:pass@192.168.1.212?subtype=MediaProfile000

cameras:
  frontptz:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontptz
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
      host: 192.168.1.112
      port: 80
      user: user
      password: pass

version: 0.14
```

### Relevant Frigate log output

```shell
No relevant logs, not a warning/error condition.
```

### Relevant go2rtc log output

```shell
No relevant logs, not a warning/error condition.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

CPU (no coral)
