### DISCUSSION TITLE
[Config Support]: Live View in Mobile working with webrtc but has warning

### DISCUSSION THREAD

**Discussion by csvke** [blakeblackshear/frigate#13408] [Config Support] [answered]
### Describe the problem you are having

I want to have the camera's live view viewable smoothly with mobile devices on iOS and Android.
AFAIK, MSE won't quite work (maybe my knowledge is limited) so I opt for WebRTC using go2rtc.

Following the documentation [here](https://docs.frigate.video/configuration/live/#webrtc-extra-configuration), I can get it working but there's a warning in the detailed go2rtc log: 
`[app] read config error=yaml: unmarshal errors: line 15: cannot unmarshal !!map into string`

So I commented out `-stun: 8555` in my `config.yaml` and it works as expected now.

Am I right that the HA add-on will create a STUN server?  

### Version

0.14.0-da913d8

### Frigate config file

```yaml
# yaml-language-server: $schema=http://rock-5b.local:5000/api/config/schema.json

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-rk-h264

detectors: # required
  rknn: # required
    type: rknn # required
    # number of NPU cores to use
    # 0 means choose automatically
    # increase for better performance if you have a multicore NPU e.g. set to 3 on rk3588
    num_cores: 3

model: # required
  # name of model (will be automatically downloaded) or path to your own .rknn model file
  # possible values are:
  # - deci-fp16-yolonas_s
  # - deci-fp16-yolonas_m
  # - deci-fp16-yolonas_l
  # - /config/model_cache/your_custom_model.rknn
  path: deci-fp16-yolonas_l
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolo models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc
  # needs to be adjusted to model, see below
  labelmap_path: /labelmap/coco-80.txt # required

go2rtc:
  streams:
    openipc-gk7205v300-alpha:
      - rtsp://root:password@192.168.1.70/stream=0
  webrtc:
    candidates:
      - 192.168.1.32:8555
      # - stun: 8555

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

objects:
  track:
    - person
    - keyboard
    - cell phone
    - laptop

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 1280
  height: 720
  fps: 5

cameras:
  openipc-gk7205v300-alpha: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://root:H0rse!@192.168.1.70/stream=0
        #- path: rtsp://root:H0rse!@192.168.1.70/stream=0
          roles:
            - record
        - path: rtsp://root:H0rse!@192.168.1.70/stream=1
        #- path: rtsp://root:H0rse!@192.168.1.70/stream=1
          roles:
            - detect

version: 0.14
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

RKNN
