### DISCUSSION TITLE
[Config Support]: 100% full for just a cam

### DISCUSSION THREAD

**Discussion by phlnil** [blakeblackshear/frigate#13409] [Config Support] [answered]
### Describe the problem you are having

not a problem.. just a question: 100% space full (see jpg attached) was referred to the actually space dedicated to a cam (rear) that will be overwrite when full ... or instead it's a problem ?

Thank you.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb


objects:
  filters:
    person:
      min_area: 5000
      max_area: 100000

cameras:
  FrontCam:
    ffmpeg:
      inputs:

        # Low Resolution Stream
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@IP:port/Streaming/channels/102
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,25,0,480,640,480,640,142,616,158,450,278,397,225,460,139,506,190,574,72,640,42,640,0,0,0
    objects:
      track:
        - person
        - car

  RearCam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:PW@IP:PORT/
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:PW@IP:PORT/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5
      enabled: true
    motion:
      mask:
        - 0,55,704,50,704,0,0,0
      threshold: 32
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Parking_area:
        coordinates: 608,224,553,332,412,227,555,0,704,0
    objects:
      track:
        - person
        - dog
        - cat
        - car

    review:
      alerts:
        required_zones: Parking_area
record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 1
      mode: active_objects
    post_capture: 9

motion:
  mask:
    - 0,25,480,29,480,0,0,0
  improve_contrast: true
version: 0.14
camera_groups:
  All:
    order: 1
    icon: LuAtom
    cameras:
      - FrontCam
      - RearCam
```

### Relevant Frigate log output

```shell
no issue
```

### Relevant go2rtc log output

```shell
no issue
```

### Frigate stats

```json
no issue
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![s](https://github.com/user-attachments/assets/7debdabf-11a7-4dd1-b30c-651f3e8fc1c2)
