### DISCUSSION TITLE
Help with RESTful command

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#13417] [General]
Hi,

I'm trying to send a RESTful command to record an event and adjust the default 30 seconds duration.  I have no issues with recording the event, but I can't get the syntax right for setting the duration.
```  
rest_command:
  Test:
      url: "http://ccab4aaf-frigate-fa-beta:5000/api/events/dahua/cat/create"
      method: POST
      payload: '{"duration": 60}'
```

**Comment by hawkeye217** [comment]
Maybe try setting the `content_type`, eg:
```
rest_command:
  Test:
      url: "http://ccab4aaf-frigate-fa-beta:5000/api/events/dahua/cat/create"
      method: POST
      content_type: 'application/json; charset=utf-8'
      payload: '{"duration": 60}'
```
