### DISCUSSION TITLE
[Config Support]: Tuning Motion Detection During the Night

### DISCUSSION THREAD

**Discussion by RN-Say** [blakeblackshear/frigate#13415] [Config Support] [answered]
### Describe the problem you are having

The docs contain the following statement:

> However, if the preferred day settings do not work well at night it is recommended to use HomeAssistant or some other solution to automate changing the settings. That way completely separate sets of motion settings can be used for optimal day and night motion detection.

Can somebody explain _how_ to use HomeAssistant to change the settings? My specific goal is to use home assistant to toggle person detection off on our indoor cameras when the family is home, while leaving cat detection running. 

### Version

0.14.0-da913d8

### Frigate config file

```yaml
## Away mode 
   objects:
      track:
        - person
        - cat

## Home mode
   objects:
      track:
        - cat
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

**Comment by NickM-27** [comment]
You use the home assistant integration, which has many switches for control https://github.com/blakeblackshear/frigate-hass-integration

**Reply by RN-Say** [reply]
It seems that there is not a solution for my use case at this time then.

**Reply by NickM-27** [reply]
Not sure what you mean, if you use home assistant then there absolutely is based on what you've described

**Reply by RN-Say** [reply]
Yes, I use Home Assistant. When I look at the switches available to me through the add-on I can globally turn "detect" on an off for the camera, but I can't toggle person tracking on and off by itself, unless I'm missing something.

**Reply by NickM-27** [reply]
I got this request mixed up with another one I was answering, if you want to specifically control only person detection then a more custom solution would be needed as you are correct that is not currently supported

**Reply by RN-Say** [reply]
This is the solution I'm trying out.

I created my two different frigate.yaml files. frigate_away.yaml and frigate_home.yaml

I added this to configuration.yaml

```
shell_command:
  frigate_away: cp /config/frigate_away.yaml /config/frigate.yaml
  frigate_home: cp /config/frigate_home.yaml /config/frigate.yaml
```

I restarted home assistant and made the following automation:

```
alias: Frigate Home Away mode when "Residents"  Home Away state changes
description: ""
trigger:
  - platform: state
    entity_id:
      - group.residents
    to: Away
    id: Residents Away
  - platform: state
    entity_id:
      - group.residents
    to: home
    id: Residents Home
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Residents Away
        sequence:
          - action: shell_command.frigate_away
            data: {}
      - conditions:
          - condition: trigger
            id:
              - Residents Home
        sequence:
          - action: shell_command.frigate_home
            data: {}
  - action: hassio.addon_start
    data:
      addon: ccab4aaf_frigate
mode: single
```

**Reply by n3qik** [reply]
Landed here as I am looking to adjust motion for day and night. One question, when the yaml file is changed by this script. Does Frigate need to be restarted? Or is this just when it is edited via the configuration editor.

**Reply by RN-Say** [reply]
Have a look on the github page for the toggle_block script, there is an example automation. But, yes Frigate needs to be restarted after the script runs. That's why I recommend to push the options available in the Home Assistant integration as far as possible before using toggle_block since that _doesn't_ require a restart. On the plus side, my frigate restarts very quickly.

**Reply by n3qik** [reply]
Thanks.

**Reply by Caddyman68** [reply]
I have tried the integration to set different values for threshold and contour area. It seems to work   - the integration log shows they changed to the new values - but when I go to the addon and check under motion tuner it sets them to whatever is on the slider there (which doesn't correspond to what I set in the integration) without hitting save. I just wasted hours going back and forth with ChatGPT and I'm frustrated. Is the integration actually setting the values? I know on a restart of Frigate it will probably set the values to whatever is in the yaml file. I am trying to prevent dust particles from triggering motion at night in infrared and still get normal triggers when it's daytime and normal lighting. I bet the answer is simple, even if it's not what I want. ChatGPT doesn't do simple

**Reply by NickM-27** [reply]
Yes, the integration sends an MQTT message which changes the values used in frigate until frigate is restarted or the values are changed elsewhere

**Reply by Caddyman68** [reply]
Thanks Nick - that was lightning quick. So by me going to the motion tuner or restarting Frigate addon it changes the settings I made in the integration. But the settings I make in the integration are the actual ones the running instance of Frigate is using (ie Frigate yaml starts threshold at 50, I change that to 30 in integration, motion threshold remains at 30 until something else changes it). My confusion was the log showing the changed values (including the 30 I set), but I inadvertently changed those just by looking at the tuner settings and then (again) by restarting the addon. Thanks for the reply

**Comment by RN-Say** [comment, marked as answer]
After using the above file swapping solution for a few days I decided that it wasn't a good long term solution and that it wasn't scalable. I figured I would soon have 5 similar frigate.yaml files to maintain and I didn't like not being able to use the built-in configuration editor. So I came up with a script that will toggle sections of frigate.yaml on and off by commenting and uncommenting tagged blocks, which works orders of magnitude better. All of the configuration stays in one place and just gets activated when needed from an automation. Here is an example of what that looks like:

<table>
  <tr>
    <th>When Home</th>
    <th>When Away</th>
  </tr>
  <tr>
    <td>
       
```yaml
objects:
  track:
    - cat
    #<away>
    # - person
    # - umbrella
    #</away>
    #<home>
    - cell phone
    - wine glass
    #</home>
  filters:
    #<away>
    # person:
      # max_ratio: 1
      # min_area: 100000
    #</away>
```
</td>
<td>
   
```yaml
objects:
  track:
    - cat
    #<away>
    - person
    - umbrella
    #</away>
    #<home>
    # - cell phone
    # - wine glass
    #</home>
  filters:
    #<away>
    person:
      max_ratio: 1
      min_area: 100000
    #</away>
```
</td>
</tr> </table>

I think this works well for anything that can't be managed with the Home Assistant integration. The added benefit is that it can be used on any other files in the file system that use `#` for comments just by adding the required tags. I put the script and the instructions for using it up on github.

https://github.com/RN-Say/toggle_block
