### DISCUSSION TITLE
[Bug]: Preview gets lost if the camera is offline on the hour

### DISCUSSION THREAD

**Discussion by murtaugh82** [blakeblackshear/frigate#13430] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I run Frigate with cameras that are not online 24/7. The preview is lost on the hour if the cameras are offline during the transition from one hour to the next. 

However, if the cameras are online during the transition from one hour to the next, the preview for one hour is retained. It does not matter whether the cameras were continuously online or temporarily offline during this hour

### Steps to reproduce

case 1
1. disconnect camera at xx:55
2. reconnect camera at (xx+1):05
-> preview for hour xx is lost

case 2
1. continuous connection to the camera between yy:55 and (yy+1):05
-> preview for hour yy is retained

### Version

0.14.0 (HA Addon -> Frigate (Full Access) Beta)

### In which browser(s) are you experiencing the issue with?

Firefox 129.0.2, Chrome 128.0.6613.86, HA-App IOS & Android

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: core-mosquitto
  user: mqtt
  password: mqtt
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

ffmpeg:
  hwaccel_args: auto

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false

objects:
  track:
    - person
    - cat

detect:
  width: 640
  height: 360
  fps: 5

snapshots:
  enabled: true
  retain:
    default: 30
    objects:
      person: 90

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 90
      mode: all
  preview:
    quality: high

ui:
  time_format: 24hour

cameras:
  Outdoor_Entrance:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://a889bffc-go2rtc:8554/Outdoor_Entrance
          roles:
            - record
        - path: rtsp://a889bffc-go2rtc:8554/Outdoor_Entrance_Sub
          roles:
            - detect
    motion:
      mask:
        - 0,0.936,0.294,0.471,0.467,0.468,0.528,0.469,0.53,0.357,0.608,0.365,0.678,0.363,0.88,0.458,1,0.517,1,0,0,0
        - 0.322,0.646,0.26,0.652,0.253,0.55,0.198,0.546,0.199,0.44,0.237,0.408,0.27,0.448,0.289,0.525,0.303,0.555,0.327,0.566,0.334,0.611
        - 0.359,0.648,0.384,0.661,0.406,0.643,0.419,0.606,0.417,0.57,0.406,0.532,0.385,0.535,0.363,0.523,0.337,0.537,0.331,0.589,0.335,0.625
        - 0.509,0.997,0.503,0.906,0.569,0.866,0.586,0.85,0.649,0.84,0.692,0.825,0.726,0.82,0.754,0.827,0.78,0.902,0.757,0.947,0.702,0.98,0.656,0.998
    objects:
      mask:
        - 0.832,0.515,0.805,0.765,0.933,0.953,0.968,0.907,0.999,0.759,1,0.635
        - 0.551,0.151,0.579,0.129,0.577,0.007,0.552,0.049
        - 0.725,0,0.728,0.072,0.791,0.037,0.789,0
  Outdoor_Backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://a889bffc-go2rtc:8554/Outdoor_Backyard
          roles:
            - record
        - path: rtsp://a889bffc-go2rtc:8554/Outdoor_Backyard_Sub
          roles:
            - detect
    motion:
      mask:
        - 1,0,0,0,0,1,0.071,1,0.065,0.877,0.274,0.575,0.388,0.409,0.568,0.207,0.678,0.201,0.668,0.362,0.746,0.365,0.745,0.129,0.928,0.114,1,0.197
        - 0.179,0.867,0.236,0.858,0.276,0.951,0.29,0.933,0.266,0.827,0.303,0.731,0.309,0.63,0.262,0.592,0.18,0.599,0.141,0.675,0.133,0.759,0.146,0.821
        - 0.44,0.568,0.429,0.479,0.408,0.504,0.382,0.505,0.367,0.455,0.375,0.39,0.42,0.351,0.468,0.376,0.495,0.415,0.494,0.468,0.478,0.498,0.454,0.503,0.452,0.565
        - 0.546,0.366,0.555,0.366,0.552,0.281,0.567,0.262,0.571,0.223,0.557,0.191,0.534,0.195,0.513,0.215,0.513,0.26,0.533,0.283
        - 0.608,0.258,0.617,0.256,0.616,0.216,0.619,0.173,0.609,0.14,0.593,0.142,0.58,0.163,0.586,0.192,0.6,0.217
    objects:
      mask:
        - 0.684,0.108,0.705,0.105,0.703,0.376,0.664,0.372
        - 0.252,0.916,0.299,0.91,0.302,0.955,0.255,0.958
        - 0.426,0.549,0.462,0.547,0.463,0.577,0.431,0.577
        - 0.536,0.35,0.563,0.348,0.563,0.37,0.537,0.372
        - 0.536,0.35,0.563,0.348,0.563,0.37,0.537,0.372
        - 0.536,0.35,0.563,0.348,0.563,0.37,0.537,0.372
        - 0.624,0.244,0.624,0.26,0.601,0.262,0.6,0.246
  Outdoor_Terrace:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://a889bffc-go2rtc:8554/Outdoor_Terrace
          roles:
            - record
        - path: rtsp://a889bffc-go2rtc:8554/Outdoor_Terrace_Sub
          roles:
            - detect
    motion:
      mask: 
        0.266,0.191,0.383,0.12,0.491,0.074,0.504,0.197,0.634,0.197,0.663,0.229,0.872,0.243,0.87,0.371,0.94,0.388,1,0.58,1,0,0,0,0,0.458,0.119,0.307
    objects:
      mask:
        - 0,0.496,0.154,0.327,0.313,0.203,0.388,0.699,0.206,1,0.123,1,0.06,0.855,0,0.674
        - 0.458,0.392,0.497,0.348,0.473,0.096,0.431,0.113
    zones: {}
version: 0.14
camera_groups:
  Outside:
    order: 1
    icon: LuWebcam
    cameras:
      - Outdoor_Backyard
      - Outdoor_Entrance
      - Outdoor_Terrace
```

### docker-compose file or Docker CLI command

```yaml
HA-Addon
```

### Relevant Frigate log output

```shell
log output is identical in positive and negative cases
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Tapo C410

### Screenshots of the Frigate UI's System metrics pages

-

**Comment by NickM-27** [comment]
Thanks, will look into the best way to handle this case

**Comment by hawkeye217** [comment]
This has been fixed in https://github.com/blakeblackshear/frigate/pull/13449

**Comment by murtaugh82** [comment]
@NickM-27 thanks for your work, but unfortunately 
the problem still occurs in my environment (0.15.0-33825f6). The previews only persist when the cameras are online on the hour. The previews on the current hour always work without problems until the next hour begins.

**Reply by NickM-27** [reply]
That doesn't seem like the same issue, because the original issue was referring to cases when the camera was offline

**Reply by murtaugh82** [reply]
Maybe i didn't describe it clearly, but the steps to reproduce still lead to the same error for me. So I would say that it is still the same problem

**Reply by murtaugh82** [reply]
@hawkeye217 can you reopen this issue or should I create a clone?

**Reply by murtaugh82** [reply]
Hi, i wanted to ask again whether you will look at this topic again in the future? I haven't quite understood what the difference is between the bugs in this section and the issues, because there is no longer a point on the topic. Unfortunately I can't use frigate well without a fix because I rarely get previews and the whole navigation doesn't work well without them. Thanks anyway for the great work. I wish you a happy new year

**Reply by NickM-27** [reply]
I will take a look at this sometime this week.

**Reply by murtaugh82** [reply]
Hi, is there any news on this topic?

**Reply by NickM-27** [reply]
I have not been able to reproduce the issue, can you elaborate on the situation. Are all cameras offline or just some?

**Reply by mikesoares** [reply]
@NickM-27 I am also experiencing this or something similar, though it's hard to gauge if it happens "on the hour" per this issue. I am using FFmpeg on another device to push a USB camera's MJPEG stream via RTSP (mediamtx). Frigate is set up to pull this RTSP stream and convert it to H264 via go2rtc. The USB camera periodically misbehaves and shuts off, causing there to be nothing on the RTSP stream. Once it comes back online, Frigate no longer does any detection or records any footage for that camera (preview works fine, but appears pixelated on initial load) until I restart Frigate.
```yaml
mqtt:
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 30
go2rtc:
  streams:
    back_area:
      - ffmpeg:rtsp://192.168.99.132:8554/back_area#video=h264#hardware
cameras:
  back_area:
    enabled: true
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_area
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
auth:
  enabled: true
version: 0.15-1
```
