### DISCUSSION TITLE
[Bug]: Changing dates retains position on page vertically in review page

### DISCUSSION THREAD

**Discussion by sylv3rblade** [blakeblackshear/frigate#13440] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

wondering if this behavior is intentional, can close if it is.

https://github.com/user-attachments/assets/9c6b8113-ae65-4914-939f-557b57396d95

### Steps to reproduce

1. go to review page
2. scroll down so that videos up top are not visible
3. click calendar icon
4. change date
5. review page is still in the position it previously was from the previous date
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    vios_garage:
    - rtsp://user:pass@ip/stream1
    - ffmpeg:vios_garage#audio=aac#async

    vios_garage_sub:
    - rtsp://user:pass@ip/stream2
    - ffmpeg:vios_garage_sub#audio=aac#async

cameras:
  vios_garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vios_garage
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/vios_garage_sub
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    privileged: true
    shm_size: "200mb" # update for your cameras based on calculation above
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
      - /dev/video-dec0:/dev/video-dec0
      - /dev/video-enc0:/dev/video-enc0
    group_add:
      - "106" # render
      - "109"
      - "44"  # video
      - "46"  # plugdev
      - "992" #getent group render
    ports:
      - '5000:5000'
      - '8554:8554'
      - '8554:8554/udp'
      - '8555:8555'
      - '8555:8555/udp'
    volumes:
      - ./container_data/frigate:/config
      - /mnt/cctv/frigate:/media/frigate
      - /etc/localtime:/etc/localime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      LIBVA_DRIVER_NAME: radeonsi
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tapo C25WB

### Screenshots of the Frigate UI's System metrics pages

n/a
