### DISCUSSION TITLE
[Support]:  Downsize stream for HA Frigate card?

### DISCUSSION THREAD

**Discussion by Phantomx2** [blakeblackshear/frigate#13447] [General Support]
### Describe the problem you are having

I'm using frigate cards in home assistant and while it works fine on my Wifi, I'm having an issue using it with Home assistant cloud.

The problem is that my Reolink camera is 4k and it looks like it doesn't play well with 5g as the Home assistant app will disconnect when viewing the stream and need to be restarted every time.
I tried using the sub stream instead of the main stream for the record section and then it works fine, but low resolution.

Is there a way to have an additional low res stream for remote viewing while keeping the video recording to full 4k?
( camera in question is **back_1** )

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.xxx
  user: MQTT
  password: xxxxxxx

go2rtc:
  streams:
    front_1: # <- for RTSP streams
      - rtsp://user:pass@192.168.0.10:554/stream1 # <- stream which supports video & aac audio
    front_1_sub:
      - rtsp://user:pass@192.168.0.10:554/stream1substream
    front_2:
      - ffmpeg:rtsp://user:pass@192.168.0.62:554/stream1
    front_2_sub:
      - ffmpeg:rtsp://user:pass@192.168.0.62:554/stream1substream
    back_1:
      - rtsp://admin:pass@192.168.0.87/Preview_01_main
      - "ffmpeg:reolink#audio=opus"
    back_1_sub:
      - rtsp://admin:pass@192.168.0.87/Preview_01_sub

  restream:
    force_audio: false

ffmpeg:
  hwaccel_args: preset-vaapi

objects:
  track:
    - person
    - dog

  filters:
    person:
      min_score: 0.6
      threshold: 0.7
    dog:
      min_score: 0.5
      threshold: 0.7

snapshots:
  enabled: true
  retain:
    default: 2


record:
  enabled: true
  retain:
    days: 2
    mode: active_objects
  events:
    retain:
      default: 2
      mode: active_objects

detectors:
  coral:
    type: edgetpu
    device: usb

# https://docs.frigate.video/configuration/cameras
cameras:
  # Front 1 ============================================================
  front_1:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
      # Highres
        - path: rtsp://127.0.0.1:8554/front_1   # <--- the name here must match the name of the camera in restream
        #input_args: preset-rtsp-restream
          roles:
            - record
              #- detect
          # Lowres
        - path: rtsp://127.0.0.1:8554/front_1_sub
        #input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      #stationary:
      #  interval: 20
      #  threshold: 20
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0,36,414,33,411,0,0,0

  # Front 2 ===================================================
  front_2:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
      # Highres
        - path: rtsp://127.0.0.1:8554/front_2
          roles:
            - record
      # Lowres
        - path: rtsp://127.0.0.1:8554/front_2_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,45,611,48,616,0,0,0
# back 1 ===================================================
  back_1:
    objects:
      filters:
        person:
          min_score: 0.6
          threshold: 0.7

    ffmpeg:
      output_args:
        record: preset-record-generic
      
      inputs:
      # Highres
        - path: rtsp://127.0.0.1:8554/back_1
          roles:
            - record
      # Lowres
        - path: rtsp://127.0.0.1:8554/back_1_sub
          roles:
            - detect
    
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.643,0.069,0.975,0.072,0.977,0.016,0.644,0.02

version: 0.14

camera_groups:
  Front:
    order: 1
    icon: LuDoorClosed
    cameras:
      - front_1
      - front_2
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-820A
