### DISCUSSION TITLE
[Question]: Can I only detect Car objects on one camera? Not just for alerts but for coral/CPU detection usage

### DISCUSSION THREAD

**Discussion by doublesupersteve** [blakeblackshear/frigate#13453] [Ask A Question] [answered]
### What is your question?

Loving Frigate, one challenge I am having is that all defined objects in the objects section are detected in all cameras even if not in the zone filters for detection. The filtering works for alerts and event recording, but the problem is I have excessive detection usage when i have 4+ cars parked on one cam.

This is problematic for me as i have 6 cars, and within vision of the cameras are about 10 cars (neighbours and street traffic). This results in high detection usage as I see a constant stream of 6-10 objects.

Is it possible to only detect (from CPU/Coral) car objects on one single camera? 

Here is an example of how many vehicles it might detect
![image](https://github.com/user-attachments/assets/22698088-5a6c-4ebe-a7ef-ac9e775f28e9)

Heres an example of it with cars turned off in objects.
![image](https://github.com/user-attachments/assets/234859e4-3d5a-46d5-9451-6d71502864e0)

This is the config for Objects and for the camera, note that car is not a listed object type in the zone filters of house_side

If I have another issue that is manifesting as high detect and lots of objects, or I need to tackle this from a different angle (e.g. increasing detect stream bitrate/resolution) please do let me know. 

There is probably room to tune the motion tuner. There are lots of trees moving in the wind reflected on the car bodies, but hoping I can just turn it off except for a few. I could adjust the area but ideally would detect people at the back of the back yard too incase the other camera fails.

The other idea I have is to use another small NUC without a coral purely for car detections off the driveway cam restream- but less is more and ideally would not have to have another system I maintain.

Thanks!

```
objects:
  track:
    - person
    - cat
    - dog
    - car
  filters:
    person:
      threshold: 0.75
    cat:
      threshold: 0.80
```

```
house_side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_side #rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.15.15.3:554/Preview_01_main 
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/house_side_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    review:
      alerts:
        labels:
          - person
          - cat
        required_zones:
          - side_yard
      detections:
        labels:
          - person
          - cat
        required_zones:
          - side_yard
    motion:
      mask:
        - 1,0,1,0.087,0.709,0.083,0.707,0
        - 0.193,0.193,0.235,0.103,0.371,0,0,0,0,0.191,0,0.351,0,0.497,0,0.564,0.056,0.477,0.111,0.36,0.12,0.312,0.132,0.286
        - 0.855,0,1,0,1,0.507,0.954,0.517,0.912,0.448,0.871,0.369,0.864,0.347,0.795,0.252,0.572,0,0.794,0
      threshold: 30
      contour_area: 30
      improve_contrast: 'false'
    live:
      stream_name: house_side_detect
    zones:
      side_yard:
        coordinates: 
          0,1,1,1,1,0.622,0.969,0.521,0.89,0.441,0.847,0.348,0.791,0,0.374,0,0.245,0.118,0.125,0.352,0.04,0.522,0,0.596 # 0,1728,4608,1728,4608,425,4237,694,3126,0,1844,0,1383,119,1160,186,936,358,613,560,559,702,0,1043    #
        objects:
          - person
          - cat
        filters:
          person:
            threshold: 0.8
        inertia: 3
        loitering_time: 0
```

**Comment by hawkeye217** [comment, marked as answer]
Just define `objects` at the camera level in your config. Anything defined at the camera level overrides what you've defined at the global level. For example, this will cause all cameras you've defined to track `person` and `cat`, but `camera1` overrides that and will only track `person`:

```
objects:
  track:
    - person
    - cat

cameras:
  camera1:
    enabled: true
    objects:
      track:
        - person
    ffmpeg:
      ...

  camera2:
    enabled: true
    ffmpeg:
      ...
```
The [reference config in the docs](https://docs.frigate.video/configuration/reference) mentions this when it says "NOTE: Can be overridden at the camera level".
