### DISCUSSION TITLE
[HW Accel Support]: Nvidia drivers not installed properly in container

### DISCUSSION THREAD

**Discussion by ajw107** [blakeblackshear/frigate#13458] [Hardware Acceleration Support]
### Describe the problem you are having

The use of a nvidia card does not work in current containers as the drivers are not linked properly.  If you run `nvidia-smi` it will report that it cannot find `libnvidia-ml.so` and the logs report that they cannot find `libcuda.so`

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Google Chrome 127.0.6533.120

### Frigate config file

```yaml
birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 8
  mode: continuous

mqtt:
  enabled: true
  host: <removed>
  port: 1883
  user: <removed>
  password: <removed>

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rw_timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
    - -probesize
    - 1000M
    - -analyzeduration
    - 1000M

go2rtc:
  streams:
    front:
      - rtspx://<removed>/<removed>
    doorbell_main:
      - "ffmpeg:http://<removed>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<removed>#video=copy#audio=copy#audio=opus"
      - rtsp://admin:<removed>@<removed>/Preview_01_sub
    doorbell_sub:
      - "ffmpeg:http://<removed>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<removed>"
  ## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
  webrtc:
    candidates:
      - <removed>:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front_garden_g4pro:
    enabled: True
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 500
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 3840
      height: 2160
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 0,181,0,0,755,0,779,176
        - 3840,0,2375,0,2240,193,2531,451,2699,648,2917,882,3019,1116,3237,1411,3077,1461,2950,1797,3061,1858,2974,2160,3840,2160

  doorbell:
    enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 500
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -ar 44100 -c:a aac -c:v copy
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell_sub
    detect:
      enabled: true
      width: 896
      height: 672
      fps: 7
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 293,1570,241,1264,1272,1283,665,1121,613,607,1627,818,1723,1089,1958,1187,1980,1105,2533,1083,2560,342,0,222,0,1614

    objects:
      track:
        - person
        - cat
      mask: 293,1570,241,1264,1272,1283,665,1121,613,607,1627,818,1723,1089,1958,1187,1980,1105,2533,1083,2560,342,0,222,0,1614

detect:
  fps: 5
  max_disappeared: 100
  stationary:
    interval: 10
    threshold: 200

snapshots:
  enabled: true
  retain:
    default: 60

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - dog
      - cat
      - bird
      - mouse
      - car
      - bicycle
      - motorcycle
    retain:
      default: 30
      mode: active_objects
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
### YAML Anchors ###
x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
#            capabilities: ["compute", "utility", "graphics"]

x-restart: &restart
  restart: unless-stopped

volumes:
  frigate-appdata-volume:
    <<: *default-local-volume
    driver_opts:
      type: none
      o: bind
      device: ${APPDATA_ROOT}/frigate/config

  frigate-storage-volume:
    <<: *default-local-volume
    driver_opts:
      type: none
      o: bind
      device: ${EXT4_DATA_ROOT}/frigate

services:
  &name frigate-service:
    <<: [ *gpu, *restart ]
    container_name: *name
    privileged: true # this may not be necessary for all setups
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "4096mb" # update for your cameras based on calculation above (mine is >201mb)
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate-appdata-volume:/config
      - frigate-storage-volume:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" # goRTC API
#    environment:
#      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
See description above, unfortunately I;ve deleted the log entries, sorry
```

### Relevant go2rtc log output

```shell
See description above, unfortunately I've deleted the log entries, sorry
```

### FFprobe output from your camera

```shell
Basically ffmepg complainign it can not see the stream (as the libcuda.so drvier is missing)
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Doorbell PoE, Unifi G4 Pro

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-08-31 at 12 57 18](https://github.com/user-attachments/assets/80d7cb30-e2e6-459c-a7d2-0cb79849a4f4)
![Screenshot 2024-08-31 at 12 58 12](https://github.com/user-attachments/assets/907f1daf-e282-45d6-955a-c738557c6b6a)

### Any other information that may be helpful

To temporarily fix it (needs running after every container update until the drivers are fixed) run these commands:
```docker exec -it frigate /bin/bash #to get into the container
for file in /usr/lib/x86_64-linux-gnu/*.560.35.03; \
  do ln -s "${file}" /usr/lib/x86_64-linux-gnu/"$(basename "${file}" ".560.35.03")"; \
done #replaces the missing symlinks
ldconfig #tells the OS to reload the driver files
```
**NOTE:** if it doesn't work, check the driver file version by `ls -alF /usr/lib/x86_64-linux-gnu`
This will symlink all the `*so.560.35.03` driver files to their `*.so` counterparts, which are missing.  There are also `*.so.1`, etc missing, but adding the `*.so` ones seems to be suffient, although I am getting high CPU warnings, so it it may need further things doing to correct it.
