### DISCUSSION TITLE
[Detector Support]: Car detected when not there, but can sometimes be there.

### DISCUSSION THREAD

**Discussion by domainret** [blakeblackshear/frigate#13451] [Detector Support]
### Describe the problem you are having

Hi guys!

First of, thank you for creating this excellent software. I've been testing it out for the last two months and its impressive. 

I have an issue where near my gate (screenshot attached) a car is detected under certain lighting conditions every day for a few hours. 

There is no car at this gate as it is a human only gate, however, a car can exist in the same shot near the gate. 

I'm trying to figure out how I can improve my detection to eliminate the false positive of the car at the gate, but also not eliminate cars that are actually passing through on the road near the gate and cars entering into the car gate from the road (which is a dirt road as per image). Furthermore, since my car gate is next to the human gate, cars will pass within the same image as the human gate just slightly below it and large vehicles will overlap the human gate. 

![Screenshot 2024-08-30 at 4 40 50 PM](https://github.com/user-attachments/assets/fbcd7fac-cada-4638-9c1f-2cb79dabf50e)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
cameras:
  cam7: 
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://ZZZ:ZZZ@192.168.9.28:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://ZZZ:ZZZ@192.168.9.28:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: True 
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    record:
      enabled: True
      events:
        retain:
          default: 10

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track: 
    - person
    - car
    - car
    - bicycle
    - bus
    - truck

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

N/A
