### DISCUSSION TITLE
How tell Live page to display Main stream and not Sub stream[Config Support]:

### DISCUSSION THREAD

**Discussion by 34bwood** [blakeblackshear/frigate#13461] [Config Support]
### Describe the problem you are having

My amcrest camera has 2 streams.  Main: 1080p and Sub: 702x460.  I'm recording the main stream and detecting with Sub stream.  When I go to the live page, it shows the detect low res stream.  I'm not able to get the Main stream to display on the live page.  I've tried adding - live to the Main stream's role, but that gives a configuration error.  

I'm not sure if I need to set something up with go2rtc to get the results I'm hoping for.  I'm new to Frigate and just trying to get something basic set up first.

Thanks in advance, Brian

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
cameras:
  FrontDoor: # <--- this will be changed to your actual camera later
    ffmpeg:
      inputs:
        # Hi Resolution Stream
        - path: rtsp://******:******@*********:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
#            - live
        # Low Resolution Stream
        - path: rtsp://******:******@*********:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral
