### DISCUSSION TITLE
Updated Config Now Camera Packet Corruption - Pixelated Feed

### DISCUSSION THREAD

**Discussion by loca5790** [blakeblackshear/frigate#13469] [Config Support]
### Describe the problem you are having

CPU resources via htop spike in a VM to over 100% CPU load and results are pixaleted camera feeds.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 
  port: 1883
  topic_prefix: 
  user: 
  password: 

database:
  path: /db/frigate.db

cameras:
  porch:
    ffmpeg:
      hwaccel_args: #preset-nvidia-h264
        - -hwaccel
        - cuda
        - -c:v
#        - hevc_cuvid
        - h264_cuvid
      input_args:
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - discardcorrupt
      output_args:
        record: preset-record-generic-audio-aac
#      output_args:
#        record:
#         - -c:a
#         - copy
      inputs:
        - path: rtsp:///
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - package
      filters:
        person:
          threshold: .75
        car:
          min_score: .5
          threshold: .7
        bicycle:
          threshold: .75
        dog:
          threshold: .75
        package:
          threshold: .75
    detect:
      width: 2592
      height: 1944
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
      retain:
        default: 20
        objects:
          person: 60
          dog: 20
          car: 30
    motion:
      threshold: 50
      contour_area: 15
    #  mask: 0,900,1080,900,1080,1920,0,1920
      improve_contrast: 'true'
    #  lightning_threshold: 0.8
      mask: 0.199,0.757,0.339,0.496,0.463,0.284,0.311,0.165,0.205,0.1,0,0.327,0.085,0.55
    zones:
      Porch:
        coordinates: 0.098,1,0.695,1,0.788,0.072,0.688,0.048
        loitering_time: 0
  backyard_deck:
    ffmpeg:
      hwaccel_args: #preset-nvidia-h264
        - -hwaccel
        - cuda
        - -c:v
#        - hevc_cuvid
        - h264_cuvid
      input_args:
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp:///
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
      filters:
        person:
          threshold: .75
        car:
          min_score: .5
          threshold: .7
        bicycle:
          threshold: .75
        dog:
          threshold: .75
    detect:
      width: 2592
      height: 1944
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
      retain:
        default: 20
        objects:
          person: 60
          dog: 20
          car: 30
    motion:
      threshold: 45
      contour_area: 20
      mask:
        - 0.682,0.02,0.955,0.685,0.636,1
        - 0,0,0.382,0,0,0.326
      improve_contrast: 'true'
    #  lightning_threshold: 0.8
  master_bedroom:
    ffmpeg:
      hwaccel_args: #preset-nvidia-h264
        - -hwaccel
        - cuda
        - -c:v
#        - hevc_cuvid
        - h264_cuvid
      input_args:
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp:///
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
      filters:
        person:
          threshold: .75
        car:
          min_score: .5
          threshold: .7
        bicycle:
          threshold: .75
        dog:
          threshold: .75
        package:
          mask: 0,0,0.761,0,0.619,1,0.004,0.998
    detect:
      width: 2592
      height: 1944
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
      retain:
        default: 20
        objects:
          person: 60
          dog: 20
          car: 30
    motion:
      threshold: 55
      contour_area: 25
    #  mask: 0,900,1080,900,1080,1920,0,1920
      improve_contrast: 'true'
    #  lightning_threshold: 0.8
  garage:
    ffmpeg:
      hwaccel_args: #preset-nvidia-h264
        - -hwaccel
        - cuda
        - -c:v
        - h264_cuvid
      input_args:
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp:///
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - bicycle
        - car
      filters:
        person:
          threshold: .8
        car:
          min_area: 80000
          min_score: .3
          threshold: .6
        bicycle:
          min_score: .5
          threshold: .7
      mask:
        - 0.856,0.101,0.832,0.251,0.768,0.613,0.784,0.629,0.871,0.115
        - 0.597,0.094,0.565,0.362,0.574,0.374,0.609,0.104
        - 0.334,0.919,0.313,0.918,0.331,0.448,0.37,0,0.395,0,0.359,0.454
    detect:
      max_disappeared: 50
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
      retain:
        default: 20
        objects:
          person: 60
          dog: 20
          car: 30
    motion:
      threshold: 45
      contour_area: 21
    #  mask: 0,900,1080,900,1080,1920,0,1920
      improve_contrast: 'true'
    #  lightning_threshold: 0.8
    zones:
      Car_Zone_1:
        coordinates: 
          0.487,0.023,0.459,0.326,1,0.811,1,0.223,0.799,0.067,0.722,0.111,0.656,0.12,0.599,0.104
        loitering_time: 10
        objects: car
      Car_Zone_2:
        coordinates: 0.166,0.339,0.361,0.995,0.837,0.999,0.941,0.847,1,0.439,0.461,0.03,0.188,0.019
        loitering_time: 10
  garage_outside:
    ffmpeg:
      hwaccel_args: #preset-nvidia-h264
        - -hwaccel
        - cuda
        - -c:v
        - h264_cuvid      #decreases CPU usage by 3% to keep system happy
#        - hevc_cuvid
      input_args:
        - -analyzeduration
        - 500M
        - -probesize
        - 500M
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp:///
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
      filters:
        person:
          threshold: .75
        car:
          min_score: .4
          threshold: .6
        bicycle:
          min_score: .4
          threshold: .6
        dog:
          threshold: .75
    detect:
      max_disappeared: 50
      width: 3840
      height: 2160
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
      retain:
        default: 20
        objects:
          person: 60
          dog: 20
          car: 30
    motion:
      threshold: 40
      contour_area: 15
    #  mask: 0,900,1080,900,1080,1920,0,1920
      improve_contrast: 'true'
    #  lightning_threshold: 0.8

      mask: 0.773,0,1,0.174,1,0
detectors:
  coral1:
    type: edgetpu
    device: pci
#    cpu1:
#      type: cpu
#      num_threads: 8

birdseye:
  enabled: true
  mode: continuous

version: 0.14
```

### Relevant Frigate log output

```shell
wn
2024-08-31 19:20:33
unknown
[h264 @ 0x7f35f0026b80] cabac decode of qscale diff failed at 87 53
Unknown
2024-08-31 19:20:33
unknown
[h264 @ 0x7f35f0026b80] error while decoding MB 87 53, bytestream 169911
Unknown
2024-08-31 19:20:53
unknown
[h264 @ 0x7f35f0032040] left block unavailable for requested intra mode
Unknown
2024-08-31 19:20:53
unknown
[h264 @ 0x7f35f0032040] error while decoding MB 0 56, bytestream 93654
Unknown
2024-08-31 19:22:13
unknown
[h264 @ 0x7f35f01d10c0] error while decoding MB 27 69, bytestream -5
Unknown
2024-08-31 19:22:23
unknown
[h264 @ 0x7f35f0026b80] error while decoding MB 164 129, bytestream -6
Unknown
2024-08-31 19:27:34
unknown
[h264 @ 0x7f35f0204c40] error while decoding MB 111 80, bytestream -7
Unknown
2024-08-31 19:28:04
unknown
[h264 @ 0x7f35f01d7bc0] left block unavailable for requested intra mode
Unknown
2024-08-31 19:28:04
unknown
[h264 @ 0x7f35f01d7bc0] error while decoding MB 0 81, bytestream 80276
Unknown
2024-08-31 19:31:24
unknown
[h264 @ 0x7f35f0011240] error while decoding MB 42 133, bytestream -8
Unknown
2024-08-31 19:32:44
unknown
[h264 @ 0x7f35f0278ac0] error while decoding MB 180 131, bytestream -7
Unknown
2024-08-31 19:33:04
unknown
[h264 @ 0x7f35f0278ac0] error while decoding MB 112 116, bytestream -13
Unknown
2024-08-31 19:33:49
unknown
[h264 @ 0x7f35f01de500] error while decoding MB 57 120, bytestream -23
Unknown
2024-08-31 19:34:04
unknown
[h264 @ 0x7f35f01de500] cabac decode of qscale diff failed at 89 125
Unknown
2024-08-31 19:34:04
unknown
[h264 @ 0x7f35f01de500] error while decoding MB 89 125, bytestream -8
Unknown
2024-08-31 19:34:14
unknown
[h264 @ 0x7f35f000e180] cabac decode of qscale diff failed at 112 132
Unknown
2024-08-31 19:34:14
unknown
[h264 @ 0x7f35f000e180] error while decoding MB 112 132, bytestream -4
Unknown
2024-08-31 19:34:44
unknown
[h264 @ 0x7f35f0145a40] error while decoding MB 17 112, bytestream -9
```

### Relevant go2rtc log output

```shell
None
```

### Frigate stats

```json
{"cameras":{"backyard_deck":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":556,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":569,"pid":515,"process_fps":5.0,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":572,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":584,"pid":517,"process_fps":5.0,"skipped_fps":0.0},"garage_outside":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":581,"detection_enabled":true,"detection_fps":5.2,"ffmpeg_pid":596,"pid":520,"process_fps":5.1,"skipped_fps":0.0},"master_bedroom":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":566,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":577,"pid":516,"process_fps":5.1,"skipped_fps":0.0},"porch":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":536,"detection_enabled":true,"detection_fps":4.1,"ffmpeg_pid":558,"pid":514,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"9.4","cpu_average":"24","mem":"1.7"},"127":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"12799":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"12902":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"175":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"176":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"177":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"178":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"179":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"335":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"376":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"45":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"455":{"cmdline":"frigate.recording_manager","cpu":"6.2","cpu_average":"5","mem":"0.3"},"456":{"cmdline":"frigate.review_segment_manager","cpu":"1.5","cpu_average":"1","mem":"0.3"},"46":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"483":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)","cpu":"0.9","cpu_average":"0","mem":"0.0"},"484":{"cmdline":"frigate.detector.coral1","cpu":"5.6","cpu_average":"3","mem":"0.3"},"486":{"cmdline":"frigate.output       ","cpu":"12.9","cpu_average":"17","mem":"0.4"},"514":{"cmdline":"frigate.process:porch","cpu":"30.0","cpu_average":"16","mem":"0.4"},"515":{"cmdline":"frigate.process:backyard_deck","cpu":"3.0","cpu_average":"5","mem":"0.4"},"516":{"cmdline":"frigate.process:master_bedroom","cpu":"2.9","cpu_average":"6","mem":"0.4"},"517":{"cmdline":"frigate.process:garage","cpu":"3.2","cpu_average":"6","mem":"0.4"},"520":{"cmdline":"frigate.process:garage_outside","cpu":"32.2","cpu_average":"20","mem":"0.4"},"536":{"cmdline":"frigate.capture:porch","cpu":"13.3","cpu_average":"12","mem":"0.3"},"546":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2592x1944 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"2","mem":"0.1"},"556":{"cmdline":"frigate.capture:backyard_deck","cpu":"13.1","cpu_average":"12","mem":"0.3"},"558":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -c:v h264_cuvid -analyzeduration 1000M -probesize 1000M -i rtsp://*:*@192.168.1.228:554/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/porch@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2592:1944 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"17.2","cpu_average":"13","mem":"0.4"},"566":{"cmdline":"frigate.capture:master_bedroom","cpu":"12.7","cpu_average":"12","mem":"0.3"},"567":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2592x1944 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"569":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -c:v h264_cuvid -analyzeduration 1000M -probesize 1000M -i rtsp://*:*@192.168.1.233:554/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/backyard_deck@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2592:1944 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"19.3","cpu_average":"16","mem":"0.4"},"572":{"cmdline":"frigate.capture:garage","cpu":"7.1","cpu_average":"5","mem":"0.3"},"577":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -c:v h264_cuvid -analyzeduration 1000M -probesize 1000M -i rtsp://*:*@192.168.1.235:554/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/master_bedroom@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2592:1944 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"17.5","cpu_average":"13","mem":"0.4"},"581":{"cmdline":"frigate.capture:garage_outside","cpu":"19.9","cpu_average":"19","mem":"0.4"},"582":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2592x1944 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"1","mem":"0.1"},"584":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -c:v h264_cuvid -analyzeduration 1000M -probesize 1000M -i rtsp://*:*@192.168.1.230:554/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"18.0","cpu_average":"16","mem":"0.3"},"596":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -c:v h264_cuvid -analyzeduration 500M -probesize 500M -i rtsp://*:*@192.168.1.236:554/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garage_outside@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=3840:2160 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"44.3","cpu_average":"43","mem":"0.5"},"599":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"604":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"4","mem":"0.1"},"609":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"885":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.1","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"19.8","mem":"15.5"}},"detection_fps":9.3,"detectors":{"coral1":{"detection_start":1725132988.934496,"inference_speed":8.74,"pid":484}},"gpu_usages":{"Quadro P600":{"dec":"10.0%","enc":"0.0%","gpu":"4.0%","mem":"66.42%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":376},"recording":{"pid":455},"review_segment":{"pid":456}},"service":{"last_updated":1725132988,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":4056.4,"mount_type":"tmpfs","total":4096.0,"used":39.6},"/media/frigate/clips":{"free":7646293.1,"mount_type":"cifs","total":8687374.1,"used":1041081.0},"/media/frigate/recordings":{"free":7646293.1,"mount_type":"cifs","total":8687374.1,"used":1041081.0},"/tmp/cache":{"free":931.0,"mount_type":"tmpfs","total":953.7,"used":22.7}},"temperatures":{"apex_0":50.05},"uptime":1040,"version":"0.14.0-da913d8"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/18489aba-971d-479b-8d04-5e65c12de766)

### Any other information that may be helpful

Running in TrueNas Scale
Two E5-2690v4 CPUs
768Gb ECC Ram
2 P600 GPU's
Corral TPU
NVME Samsung990 Pros

The VM:
Host Passthrough CPU
4 CPUs, 2 cores 2 thread
64 GB ram
P600 in GPU Pass Through
