### DISCUSSION TITLE
MQTT update on autotrack move command?

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#13468] [General]
Hi,

I have my PTZ mounted on the gable wall of my house.  The issue with this is that when auto tracking at night, it can pan round causing the gable wall to come into the field of view, which means the wall is lit up, but the rest of the image is dark.

![vlcsnap-2024-08-31-19h33m42s047](https://github.com/user-attachments/assets/90801732-e986-4481-8417-48ed3d65468d)

I have come up with a crude solution to pan the PTZ away from the wall, but I have to constantly spam the Dahua API while Frigate is autotracking to check the PTZ pan position. I've noticed the video can get a bit glitchy during autotracking, which I'm guessing is due to the spamming of the API.
```
command_line:
  - sensor:
      name: "Dahua PTZ Pan Position"
      command: curl -s -g --digest -u user:password "http://192.168.1.2/cgi-bin/ptz.cgi?action=getStatus"
      unit_of_measurement: " "
      value_template: '{{ (value|regex_findall("status.Postion.0.=([\d\.]*)"))[0] }}'
```
My automation is set to constantly check the PTZ pan position while Frigate is autotracking using the state topic: ```frigate/dahua/ptz_autotracker/active``` I then pan the PTZ away from the wall in 10 degree increments until it is back into an acceptable pan range.
```
shell_command:
  dahua_ptz_move_right: curl -s -g --digest -u user:password "http://192.168.1.2/cgi-bin/ptz.cgi?action=moveRelatively&channel=1&arg1=0.05&arg2=0&arg3=0"
```
Is there anything in MQTT that will allow me to trigger the command line sensor only after an autotrack move command? Or can anyone think of a better way of doing this?
