### DISCUSSION TITLE
[Support]: msjpeg stream distortion

### DISCUSSION THREAD

**Discussion by bdoiron74** [blakeblackshear/frigate#13463] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When the ui drops back to msjpeg mode for live view I often see this:
![image](https://github.com/user-attachments/assets/7d804b75-3582-40b2-b71c-04b155354716)

Notice how the color and I guess luminosity are out of sync. Live view and recordings do not show this issue. 

I am currently using two streams, one for recording (recording=1920x1080@8fps, live=856x480@24fps) but I think I've also seen this using just the 856x480@24fps for both live and record. 

### Steps to reproduce

Nothing fancy - I'm just leaving the frigate live view running. I'm not sure exactly what causes it to drop back to msjpeg mode, I usually just refresh the page. 

### Version

0.15.0-6a0b5c3 (also various 0.14.1 builds)

### Frigate config file

```yaml
live:
  height: 480

record:
  enabled: true
  retain:
    days: 3
    mode: all

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic

go2rtc:
  streams:
    CAM-A20024:
      - rtsp://CAM-A20024:554/stream
    CAM-A20024_HQ:
      - rtsp://CAM-A20024:553/stream
    
  Surface_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM-A20024_HQ
          roles:
            - detect
            - record
    live:
      stream_name: CAM-A20024
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:6a0b5c3 # latest official build
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - /opt/media/frigate/:/media/frigate
      - ./frigate/nginx.conf:/usr/local/nginx/conf/nginx.conf
    # network_mode: host # may be required for udp-only cameras?
    networks: [ localnet ]
    ports:
      - "127.0.0.1:8971:8971" # https
      - "127.0.0.1:5000:5000" # http, Internal unauthenticated access. Expose carefully.
      - "127.0.0.1:1984:1984" # go2rtc direct
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    devices:
      - /dev/dri # HW acceleration: intel driver
    cap_add:
      - CAP_PERFMON # HW acceleration: intel gpu stats
```

### Relevant Frigate log output

```shell
not sure what to look for here
```

### Relevant go2rtc log output

```shell
nothing out of the ordinary
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Pacidal NMHD2290D

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/520e7743-f5b0-41cd-9584-c60b7f58d95f)
![image](https://github.com/user-attachments/assets/efd8f122-0bc8-4b51-bf7e-d34c05f4e433)
![image](https://github.com/user-attachments/assets/fee21cef-cd62-44c0-9e9e-efbc3ebf266a)

**Comment by hawkeye217** [comment, marked as answer]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Usage question 15.

**Reply by bdoiron74** [reply]
okay, I feel dumb for not remembering seeing that FAQ. Thanks, I'll git it a shot. 
Given I'm running two resolutions for live vs recording, should I match the recorded video?

**Reply by hawkeye217** [reply]
No problem :)

The jsmpeg feed always uses the input of your `detect` role, so you'll want to explicitly define the width and height of that stream.

Let me know if you're still having issues after you apply that and we can dive further if so.

**Reply by bdoiron74** [reply]
well... simply changing the config and restarting frigate got me this:
![image](https://github.com/user-attachments/assets/558f3a08-7ba9-487f-a200-fac89a93183a)

But then refreshing the browser page, followed by restarting frigate and things are happy!
![image](https://github.com/user-attachments/assets/b05141b4-0532-4e08-b08c-495a2f93d18a)

(the ui always falls back to msjpeg when I restart frigate with the live view showing)

**Reply by bdoiron74** [reply]
playing around with it, it seems that the live height has to evenly divide into the detect height. Is that expected?

```
detect:
  width: 1920
  height: 1080
live:
  height: 480 # distorted
live: 
  height: 540 # not distorted
```
