### DISCUSSION TITLE
[Config Support]: View low res, while detecting on highres?

### DISCUSSION THREAD

**Discussion by illivanillie** [blakeblackshear/frigate#13467] [Config Support]
### Describe the problem you are having

Is there a way to determine the stream/file for watching events?
I want to record both, high res and low res, detect on high res, but for convenience/speed purpose watch events in low res.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
.
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

TensorRT

**Comment by hawkeye217** [comment]
You should read the official documentation: https://docs.frigate.video/configuration/live#setting-stream-for-live-ui

**Reply by illivanillie** [reply]
My question is not about live view, it's about watching events/recorded files.

**Reply by NickM-27** [reply]
The previews for recordings are generated automatically. Only one resolution of film recordings is available on top of the previews

**Reply by illivanillie** [reply]
Would you mind sharing a little bit about that process? Which stream is played when? 
Plus: I had a break from frigate for a while and miss the recordings section. If there’s no event I can only watch (I guess it is) motion stream on 8x/4x

**Reply by NickM-27** [reply]
The previews are shown while scrubbing to give a very quick way to see what occurred, then full recordings will play back normally

> If there’s no event I can only watch (I guess it is) motion stream on 8x/4x

That's not true. You can use the history button on a cameras live view or just click on any camera in the motion view to go to recordings

**Reply by illivanillie** [reply]
Once again, I think I made myself not very clear.
Take a look at this config:
```
  Camera1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/camera1_hq
          roles:
            - detect
            - record
        - path: rtsp://IP:8554/camera1_lq
          roles:
            - record
```
How can I determine, which recorded file/resolution is displayed, when viewing an event in the frigate UI. Again, I want to see/stream lq, but detect on hq (which also has recording enabled just in case).
Or maybe I am misunderstanding your answers. In case, give me a hint please, sorry.
