### DISCUSSION TITLE
[Config Support]: Parked Car keeps getting detected?

### DISCUSSION THREAD

**Discussion by jubjubrsx** [blakeblackshear/frigate#13474] [Config Support]
### Describe the problem you are having

my parked car keeps setting off home assistant and an event that a car was detected, I've masked off the entire area yet it still happens any thoughts? for the moment I just removed car from the tracking list.

### Version

14.1

### Frigate config file

```yaml
Carport: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Carport
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
        car:
          mask: 
            0.313,0.115,0.646,0.16,0.84,0.259,0.769,0.971,0.501,1,0.104,0.773,0.02,0.565,0.197,0.203
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30
```

### Relevant Frigate log output

```shell
no output
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral
