### DISCUSSION TITLE
[HW Accel Support]: New Coral install on NUC running HAOS

### DISCUSSION THREAD

**Discussion by RCG-SW** [blakeblackshear/frigate#13477] [Hardware Acceleration Support]
### Describe the problem you are having

Frigate crashes trying to detect USB Coral

```
2024-09-01 02:50:31.384884989  [2024-08-31 20:50:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as auto
2024-09-01 02:50:31.391335138  Process detector:coral:
2024-09-01 02:50:31.391338580  Traceback (most recent call last):
2024-09-01 02:50:31.391339899    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-09-01 02:50:31.391340839      self.run()
2024-09-01 02:50:31.391341932    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-09-01 02:50:31.391342991      self._target(*self._args, **self._kwargs)
2024-09-01 02:50:31.391344070    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-09-01 02:50:31.391347636      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-09-01 02:50:31.391366380    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-09-01 02:50:31.391367711      self.detect_api = create_detector(detector_config)
2024-09-01 02:50:31.391368735    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-09-01 02:50:31.391389365      return api(detector_config)
2024-09-01 02:50:31.391390587    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 43, in __init__
2024-09-01 02:50:31.391391996      self.interpreter = Interpreter(
2024-09-01 02:50:31.391393071    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2024-09-01 02:50:31.391404673      _interpreter_wrapper.CreateWrapperFromFile(
2024-09-01 02:50:31.391405759  ValueError: Model provided has model identifier 'l ve', should be 'TFL3'
2024-09-01 02:50:31.391406587  
2024-09-01 02:50:31.391651885  [2024-08-31 20:50:31] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-09-01 02:50:31.391817218  [2024-08-31 20:50:31] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Version

Frigate (Full Access) Current version: 0.14.1

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: lestoucans.local
  port: 1883
  user: xxx
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: false
  width: 1280
  height: 720

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 3
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0


objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    # - cat
    # - sheep
live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
  stream_name: camera_name
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 20

detectors:
  coral:
    type: edgetpu
    # device: usb
  ov:
    type: openvino
    device: GPU
    # model:
    #   path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  path: /openvino-model/ssdlite_mobilenet_v2.xml

go2rtc:
  streams:
    Barn1: rtsp://xxx:xxx@192.168.1.223:554/cam/realmonitor?channel=1&subtype=00
    Driveway: rtsp://xxx:xxx@192.168.1.17:554/cam/realmonitor?channel=1&subtype=00

cameras:
  Barn1: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.223:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
    onvif:
      host: 192.168.1.223
      port: 80
      user: xxx
      password: xxx
    #   autotracking:
    #     # Optional: enable/disable object autotracking. (default: shown below)
    #     enabled: true
    #     # Optional: calibrate the camera on startup (default: shown below)
    #     # A calibration will move the PTZ in increments and measure the time it takes to move.
    #     # The results are used to help estimate the position of tracked objects after a camera move.
    #     # Frigate will update your config file automatically after a calibration with
    #     # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
    #     calibrate_on_startup: true
    #     # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
    #     # Available options are: disabled, absolute, and relative
    #     #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
    #     #   absolute - use absolute zooming (supported by most PTZ capable cameras)
    #     #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
    #     zooming: disabled
    #     # # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
    #     # # A lower value will keep more of the scene in view around a tracked object.
    #     # # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
    #     # # The value should be between 0.1 and 0.75
    #     # zoom_factor: 0.3
    #     # # Optional: list of objects to track from labelmap.txt (default: shown below)
    #     track:
    #       - person
    #       - sheep
    #     # Required: Begin automatically tracking an object when it enters any of the listed zones.
    #     required_zones:
    #       - barn_inside
    #     # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
    #     return_preset: Home
    #     # Optional: Seconds to delay before returning to preset. (default: shown below)
    #     timeout: 10
    #     # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
    #     # movement_weights: []
    zones:
      barn_inside:
        coordinates: 0,720,1280,720,1280,0,0,0
    motion:
      threshold: 30
      contour_area: 20
      # improve_contrast: true
  Driveway: # <--- this will be changed to your actual camera later
    enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.17:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
    motion:
      threshold: 30
      contour_area: 25
      # improve_contrast: 'true'
    zones:
      Main:
        coordinates: 
          0,0,0.678,0,0.686,0.191,1,0.452,1,1,0.328,0.995,0.384,0.733,0.271,0.723,0.139,1,0,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Main
      detections:
        required_zones: Main

  Barn: # <--- this will be changed to your actual camera later
    enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.71:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
    motion:
      threshold: 33
      contour_area: 17
      # improve_contrast: true
    zones:
      Main:
        coordinates: 0,0,0.749,0,0.752,0.098,1,0.09,1,1,0.328,0.995,0.367,0.338,0.152,0.358,0,0.89
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Main
      detections:
        required_zones: Main
  Barn2: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.157:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
    onvif:
      host: 192.168.1.157
      port: 80
      user: xxx
      password: xxx
    detect:
      enabled: false
    record:
      enabled: false
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 2
          mode: motion
    motion:
      threshold: 38
      contour_area: 61
      # improve_contrast: 'true'
  Barn3: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.159:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
    onvif:
      host: 192.168.1.159
      port: 80
      user: xxx
      password: xxx
    detect:
      enabled: false
    record:
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
  Barn4: # <--- this will be changed to your actual camera later
    enabled: true
    detect:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.161:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
    onvif:
      host: 192.168.1.161
      port: 80
      user: xxx
      password: xxx
    record:
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
  nw: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.69:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
    onvif:
      host: 192.168.1.69
      port: 80
      user: xxx
      password: xxx
    detect:
      enabled: false
    record:
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
2024-09-01 02:50:31.384884989  [2024-08-31 20:50:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as auto 2024-09-01 02:50:31.391335138  Process detector:coral: 2024-09-01 02:50:31.391338580  Traceback (most recent call last): 2024-09-01 02:50:31.391339899    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap 2024-09-01 02:50:31.391340839      self.run() 2024-09-01 02:50:31.391341932    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run 2024-09-01 02:50:31.391342991      self._target(*self._args, **self._kwargs) 2024-09-01 02:50:31.391344070    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector 2024-09-01 02:50:31.391347636      object_detector = LocalObjectDetector(detector_config=detector_config) 2024-09-01 02:50:31.391366380    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__ 2024-09-01 02:50:31.391367711      self.detect_api = create_detector(detector_config) 2024-09-01 02:50:31.391368735    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector 2024-09-01 02:50:31.391389365      return api(detector_config) 2024-09-01 02:50:31.391390587    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 43, in __init__ 2024-09-01 02:50:31.391391996      self.interpreter = Interpreter( 2024-09-01 02:50:31.391393071    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__ 2024-09-01 02:50:31.391404673      _interpreter_wrapper.CreateWrapperFromFile( 2024-09-01 02:50:31.391405759  ValueError: Model provided has model identifier 'l ve', should be 'TFL3' 2024-09-01 02:50:31.391406587   2024-09-01 02:50:31.391651885  [2024-08-31 20:50:31] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found 2024-09-01 02:50:31.391817218  [2024-08-31 20:50:31] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Amcrest

### Screenshots of the Frigate UI's System metrics pages

Firgate crashes trying to detect
