### DISCUSSION TITLE
[Support]: HASS occupancy count > 0 but nothing in alerts or detections

### DISCUSSION THREAD

**Discussion by sjtrny** [blakeblackshear/frigate#13475] [General Support]
### Describe the problem you are having

Hi all, I use frigate to detect cats in my backyard. There are times when the occupancy count in home assistant changes to > 0 but I do not get any matching recordings in alerts or detections.

Scrolling back on the motion timeline reveals that a cat was actually present at that time but often it was moving quickly across my backyard.

My understanding is that the default behaviour of Frigate is for all tracked objects to end up as "detections" on the UI, because of this comment in the reference config that says that by default we should have detections for all tracked objects.

```
# Optional: Review configuration
# NOTE: Can be overridden at the camera level
review:
  ....
  # Optional: detections configuration
  detections:
    # Optional: labels that qualify as a detection (default: all labels that are tracked / listened to)
```

Have I misunderstood and/or how should I adjust my config so that every tracked cat ends up at least as a "detection" in the UI.

### Version

0.14

### Frigate config file

```yaml
version: 0.14

mqtt:
  host: mqtt

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  webrtc:
    candidates:
      - 192.168.20.10:8555
  streams:
    greenhouse_record:
      - rtsp://camerapi:raspberry@192.168.20.14/stream1
    backyard_record:
      - rtsp://camerapi:raspberry@192.168.20.15/stream1

record:
  enabled: true
  retain:
    days: 7 # <- number of days to keep 24/7 recordings
    mode: all
  events:
    retain:
      default: 365
      mode: all

cameras:
  greenhouse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/greenhouse_record?video&audio
          roles:
            - record
            - detect
    live:
      stream_name: greenhouse_record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
          min_area: 50000
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.043,0.316,0.045,0.314,0,0,0
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_record?video&audio
          roles:
            - record
            - detect
    live:
      stream_name: backyard_record
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.043,0.316,0.045,0.314,0,0,0
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.9
          min_area: 2500
        cat:
          min_area: 1250
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

TensorRT

### Network connection

Wireless

### Camera make and model

TAPO-C325WB
