### DISCUSSION TITLE
Frigate (w/ Coral TPU) + remote CodeProject.AI facial detection

### DISCUSSION THREAD

**Discussion by morikplay** [blakeblackshear/frigate#13478] [Ask A Question]
### What is your question?

(I'm rather new to Frigate so please pardon the obvious boo-boo)
**Issue**: Frigate w/ Coral TPU and a working (and reachable) remote CPAI (w/ various models). In attempting to perform facial recognition on my face (label: "Morik"), CPAI gets the request from Frigate (I presume upon motion), recognizes "Morik", but subsequently Frigate only shows motion and person detections (due to Coral TPU); not specifically person and/or face detection ("Morik").

To compare and contrast, I used my working BlueIris setup which does setup a PERSON label, using which HomeAssistant trigger (via a self-written blueprint) is done.

How would one go about setup / troubleshooting this behavior in Frigate?

**Frigate**: 0.14.0-da913d8
**Frigate HW**: Intel i13NUC w/ iGPU + Coral TPU enabled
**Link between Frigate & CPAI**: 100Gbps backbone w/ 2Gbps seen on NUC
**CPAI**: 
```
Server version:   2.6.5
System:           Linux
Operating System: Linux (Ubuntu 22.04)
CPUs:             Intel(R) Xeon(R) Platinum 8351N CPU @ 2.40GHz (Intel)
                  8 CPUs x 1 core. 1 logical processors (x64)
GPU (Primary):     (NVIDIA), CUDA: 12.4 (up to: 12.4), Compute: 8.0, cuDNN: 8.9.7
System RAM:       63 GiB
Platform:         Linux
BuildConfig:      Release
Execution Env:    Native
Runtime Env:      Production
Runtimes installed:
  .NET runtime:     7.0.19
  .NET SDK:         7.0.119
  Default Python:   3.10.12
  Go:               Not found
  NodeJS:           Not found
  Rust:             Not found
Video adapter info:
  VMware SVGA II Adapter:
    Driver Version     
    Video Processor
System GPU info:
  GPU 3D Usage       0%
  GPU RAM Usage      0
Global Environment variables:
  CPAI_APPROOTPATH = <root>
  CPAI_PORT        = 32168
```
**frigate config** (relevant parts)
```
mqtt:
  enabled: true
  host: <homeassistant.fqdn>
  port: <some_port>
  topic_prefix: frigate
  client_id: frigate_pve_vm
  user: <some_user>
  password: <some_password>
  stats_interval: 60
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
  cpai:
    api_url: http://cpai.fqdn:32168/v1/vision/detection
    api_timeout: 20
    type: deepstack
detect:
  enabled: true
  fps: 5
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
motion:
  threshold: 30
  contour_area: 20
  lightning_threshold: 0.8
  frame_height: 100
  frame_alpha: 0.01
  improve_contrast: true
  mqtt_off_delay: 5
objects:
  track:
    - person
    - bicycle
    - car
    - bird
    - dog
    - eye glasses
    - plate
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.7
review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - car
      - person

...

cameras:
  FrontDoorBell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoorBell_RTSP
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoorBell_RTSP_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    motion:
      mask: 
        0.63,0.772,0.624,0.669,0.548,0.629,0.5,0.56,0.527,0.466,0.587,0.438,0.648,0.484,0.719,0.51,0.817,0.549,0.829,0.614,0.799,0.612,0.706,0.593
    zones:
      near_front_door:
        coordinates: 
          0.001,0.745,0.049,0.701,0.266,0.614,0.382,0.614,0.462,0.659,0.527,0.653,0.542,0.707,0.504,0.734,0.492,0.794,0.515,0.878,0.508,0.997,0.068,0.995
        loitering_time: 0
        objects:
          - dog
          - person
          - bicycle
    review:
      alerts:
        required_zones: near_front_door
      detections:
        required_zones: near_front_door

```

Inference stats:
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/d2d68c26-1fcf-4b08-8f47-c48b9c84357f">

Your guidance is much appreciated!
