### DISCUSSION TITLE
Recordings not Deleted when Changed Retention

### DISCUSSION THREAD

**Discussion by moogoos** [blakeblackshear/frigate#13472] [General Support]
### Describe the problem you are having

I have 8 cameras, they have configs set like so for record

```
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 90
          mode: motion
```

but when I changed them to 14 days. and 30 days respectively, the next day I expected the recordings to be deleted. The UI seems to have disassocated the recordings being available as I get a not found for the days between 14 and 30 days ago, but on the file system the directories by day are still there with 50GB:

```2024-08-02``` for example

ive set sync_recordings as well globally and also tried setting it at each camera config. Feels like it was running as load increased significantly for a period of time but then settled down.

### Version

14.1

### Frigate config file

```yaml
record:
  sync_recordings: true
...


  backyard-center:
    live:
      stream_name: backyard-center_main
    ui:
      order: 8
    birdseye:
      order: 8
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard-center_main?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard-center_sub?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      max_not_heard: 30
      min_volume: 200
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
      filters:
        bark:
          threshold: 0.7
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      events:
        retain:
          default: 60
          mode: motion

    zones:
      Backyard:
        coordinates: 0.239,0.479,0.086,0.994,0.996,0.995,0.996,0.581
        loitering_time: 0
    motion:
      mask: 0.029,0.909,0.353,0.912,0.353,0.947,0.024,0.948
```
```


### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision

**Comment by NickM-27** [comment]
> but when I changed them to 14 days. and 30 days respectively,

that's not what your config shows

```
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      events:
        retain:
          default: 60
          mode: motion
```
