### DISCUSSION TITLE
Playback issue

### DISCUSSION THREAD

**Discussion by phlnil** [blakeblackshear/frigate#13481] [Config Support]
### Describe the problem you are having

Hi, 
while I reviewing  he timeline (sliding the time indicator) for a camera, 
I got _sometimes_ in this issue:
frigate record the event correctly but it miss first seconds... but in the preview scrolling quicky the time line ... the moment is there.
On the log appears 
`No recordings found for RearCam during the requested time range`
 adding a "pre_capture: 5" is the correct way to solve it ?
(I wouldn't add MB for events... and keep at the minimal the config, if it's possible)

Thank you.

### Version

0.14.0-da913d8

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb


objects:
  filters:
    person:
      min_area: 5000
      max_area: 100000

cameras:
  FrontCam:
    ffmpeg:
      inputs:

        # Low Resolution Stream
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@ip:port/Streaming/channels/102
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,25,0,480,640,480,640,142,616,158,450,278,397,225,460,139,506,190,574,72,640,42,640,0,0,0
    objects:
      track:
        - person
        - car

  RearCam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:pwq@ip:port/
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:pwq@ip:port/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5
      enabled: true
    motion:
      mask:
        - 0,55,704,50,704,0,0,0
      threshold: 32
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Parking_area:
        coordinates: 608,224,553,332,412,227,555,0,704,0
    objects:
      track:
        - person
        - dog
        - cat
        - car

    review:
      alerts:
        required_zones: Parking_area
record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 1
      mode: active_objects
    post_capture: 9

motion:
  mask:
    - 0,25,480,29,480,0,0,0
  improve_contrast: true
version: 0.14
camera_groups:
  All:
    order: 1
    icon: LuAtom
    cameras:
      - FrontCam
      - RearCam
```

### Relevant Frigate log output

```shell
no issue, please ask if useful
```

### Relevant go2rtc log output

```shell
no issue, please ask if useful
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral
