### DISCUSSION TITLE
[Config Support]: Night Time Camera

### DISCUSSION THREAD

**Discussion by plex804** [blakeblackshear/frigate#13485] [Config Support]
### Describe the problem you are having

I added a camera facing my driveway to notify me if a vehicle or person is spotted on it. The camera and settings do a fantastic job during the day. At night the camera has never detected a car and has detected me when I tested walking the driveway.
I have followed so many guides/videos on making setting adjustments and then undoing them that I think I am losing my mind. 
Does anyone have an idea why frigate doesn’t detect the vehicle at night? https://youtu.be/pt7azWmEvns

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: true
  host:  
  port: 1883
  user:  
  password:  
  #topic_prefix: frigate



detectors:
 #  cpu1:
 #    type: cpu
  coral:
    type: edgetpu
    device: usb


# Optional: Database configuration
# database:
  # The path to store the SQLite DB (default: shown below)
 # path: /media/frigate/frigate.db



# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  enabled: True
  restream: False
#  width: 1960
#  height: 1080
  quality: 8
  mode: continuous

# Optional: ffmpeg configuration


# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
  # Optional: Frequency for confirming stationary objects (default: shown below)
   # When set to 0, object detection will not confirm stationary objects until movement is detected.
   # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 15
  # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
  # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
   # This can help with false positives for objects that should only be stationary for a limited amount of time.
  # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
   # car at the default.
  # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
   #          There are very few situations where you would want it disabled. It is NOT recommended to
   #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
   # Optional: Default for all object types (default: not set, track forever)
      default: 3000
  # Optional: Object specific values
      objects:
        person: 1000

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 5
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 5
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
 # mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 5

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: true
  expire_interval: 22000
  retain:
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    objects:
      - person
      - dog
      - car

    retain:
      mode: motion
      objects:
        person: 15
        car: 15
        dog: 3

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 1080

  # Optional: Camera override for retention settings (default: global values)
  retain:
 # Required: Default retention days (default: shown below)
    default: 21
 # Optional: Per object retention days
    objects:
      person: 21
      car: 21
      dog: 3


go2rtc:
  streams:

    Driveway:
      - rtsp:// /cam/realmonitor?channel=1&subtype=1
    Driveway_sub:
      - rtsp:// /cam/realmonitor?channel=1&subtype=1
 

# Required
cameras:
 
  Driveway:
    enabled: True
    motion:
     mask:
        - 0,84,640,56,640,0,0,0
    ffmpeg:
      inputs:
        - path: rtsp:// /cam/realmonitor?channel=1&subtype=0
          roles:
           # - detect
            - record
        - path: rtsp:// /cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
           # - record
    detect:
      width: 640 # <- optional, by default Frigate tries to automatically detect resolution
      height: 480 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 15
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
             - 420,248,393,257,372,233,373,211,413,216
             - 46,156,39,86,84,86,243,142
    live:
      stream_name: Driveway
    zones:
      driveway_yard:
        coordinates: 324,123,243,142,146,157,115,157,432,219,427,239,640,321,640,123,374,72
        objects:
          - car
          - person
      driveway_road:
        coordinates: 0,144,381,126,369,82,112,102,0,94
        objects:
          - car
          - person
    birdseye:
      order: 2
 #   ui:
 #     order: 4
 #     dashboard: True

# Optional
ui:
  live_mode: mse
  use_experimental: False

telemetry:
  # Optional: Enabled network interfaces for bandwidth stats monitoring (default: empty list, let nethogs search all)
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  # Optional: Configure system stats
  stats:
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: False
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant Frigate log output

```shell
aa
```

### Relevant go2rtc log output

```shell
2024-08-28 03:35:56.195861483 [INFO] Preparing new go2rtc config... 2024-08-28 03:36:00.601288635 [INFO] Starting go2rtc... 2024-08-28 03:36:00.791820319 03:36:00.791 INF go2rtc version 1.8.4 linux/amd64 2024-08-28 03:36:00.792408133 03:36:00.792 INF [rtsp] listen addr=:8554 2024-08-28 03:36:00.792664517 03:36:00.792 INF [webrtc] listen addr=:8555 2024-08-28 03:36:00.793154113 03:36:00.793 INF [api] listen addr=:1984 2024-08-28 03:36:03.931476487 [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Any other information that may be helpful

These are the settings for my camera https://imgur.com/a/1MX6Avq

IPC-HFW5241E-Z12E-S2
