### DISCUSSION TITLE
[Support]: failed_login_rate_limit seems not to work as expected

### DISCUSSION THREAD

**Discussion by GMagician** [blakeblackshear/frigate#13480] [General Support]
### Describe the problem you are having

It's problably I didn't understand how it works but I'm expecting that with below line
  failed_login_rate_limit: "1/second;5/minute;20/hour"
if I do a wrong login I have to wait 1 second before retrying and after 5 wrong tries I have to wait 5 minutes for the next.

I did a lot of wrong login without being limited in time

I added it to configuration then button save & restart

### Version

0.14.1

### Frigate config file

```yaml
version: 0.14

auth:
  enabled: true
  failed_login_rate_limit: "1/second;5/minute;20/hour"
  session_length: 3600

mqtt:
  enabled: true
  tls_ca_certs: /certs/root-CA.crt
  tls_client_cert: /certs/frigate.crt
  tls_client_key: /certs/frigate.key
  port: 8883
  host: _placeholder_
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

birdseye:
  enabled: true
  mode: continuous

detectors:
  rknn:
    type: rknn
    num_cores: 3

ffmpeg:
  hwaccel_args: preset-rk-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    Balcone_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.113:554/0#video=copy#audio=copy
    Balcone_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.113:554/1#video=copy#audio=copy
    Retro_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.115:554/0#video=copy#audio=copy
    Retro_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.115:554/1#video=copy#audio=copy

cameras:
  Balcone:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Balcone_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Balcone_sub
          roles:
            - detect
    birdseye:
      order: 1
    live:
      stream_name: Balcone_sub
    motion:
      threshold: 20
      mask:
        - 1,1,0.61,0.999,0.48,0.395,0.653,0.28,0.874,0.332,1,0.436
        - 0.002,0.994,0.002,0.007,0.267,0.003,0.268,0.393,0.185,0.45,0.102,0.71,0.087,1
    detect:
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.65
  Retro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Retro_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Retro_sub
          roles:
            - detect
    birdseye:
      order: 2
    live:
      stream_name: Retro_sub
    onvif:
      host: 192.168.0.115
      port: 80
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
    motion:
      threshold: 12
    detect:
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.65

timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

review:
  alerts:
    labels:
      - person

record:
  enabled: true
  retain:
    days: 0
  events:
    objects:
      - person
    pre_capture: 5
    post_capture: 10
    retain:
      default: 5
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: false
  timestamp: true
```

### Relevant Frigate log output

```shell
Not yed logged it
```

### Relevant go2rtc log output

```shell
Not yed logged it
```

### FFprobe output from your camera

```shell
Not yed logged it
```

### Operating system

Other

### Install method

Docker Compose

### Object Detector

RKNN

### Network connection

Wired

### Camera make and model

DSE

### Any other information that may be helpful

In composer I redirected port 8971 to 443 to use https to access web page
