### DISCUSSION TITLE
[Support]: Cameras are not available in Home IOS app

### DISCUSSION THREAD

**Discussion by derekngibbs** [blakeblackshear/frigate#13493] [General Support]
### Describe the problem you are having

I have Frigate 0.14.1 on Ubuntu with Docker. I added port 1984 in Docker compose and I can access Frigate, go2rtc, and HA can view my streams. I can not get Home (ios app) to see my cameras from Frigate.

Frigate-go2rtc logs
2024-08-31 12:40:17.100594612 [INFO] Preparing new go2rtc config...
2024-08-31 12:40:17.498596250 [INFO] Starting go2rtc...
2024-08-31 12:40:17.695534039 12:40:17.695 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-08-31 12:40:17.695562213 12:40:17.695 INF config path=/dev/shm/go2rtc.yaml
2024-08-31 12:40:17.696130256 12:40:17.696 INF [api] listen addr=:1984
2024-08-31 12:40:17.696207141 12:40:17.696 INF [rtsp] listen addr=:8554
2024-08-31 12:40:17.696468620 12:40:17.696 INF [webrtc] listen addr=:8555/tcp
2024-08-31 12:40:27.096682468 [INFO] Starting go2rtc healthcheck service...

GO2RTC config from web interface
api:
origin: '*'
hass:
config: /config
homekit:
your_oco_camera:
name: boat house
your_reolink_camera:
name: workout
log:
format: text
network_mode: host
rtsp:
default_query: mp4
streams:
your_oco_camera:

rtsp://user:Pw@192.168.1.237:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
your_oco_camera_sub:
rtsp://user:Pw@192.168.1.237:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
your_reolink_camera:
ffmpeg:http://192.168.2.206/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pw-1#video=copy#audio=copy#audio=opus
your_reolink_camera_sub:
rtsp://user:pw-1@192.168.2.206:554/h264Preview_01_sub
webrtc:
candidates:
stun:8555
Any ideas what I've done wrong?

Originally posted by @derekngibbs in https://github.com/blakeblackshear/frigate/discussions/13428#discussioncomment-10508232

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.195
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mqttuser
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

detectors:
#   ov:
#    type: openvino
#    device: AUTO
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    your_reolink_camera:
#      - "http://192.168.1.237/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pw#video=copy#audio=copy#audio=opus"
#      - "ffmpeg:your_reolink_camera#audio=opus"
      - ffmpeg:http://192.168.2.206/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pw#video=copy#audio=copy#audio=opus
    your_reolink_camera_sub:
#       - "ffmpeg:http://192.168.1.237/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=pw&audio=copy"
      - rtsp://admin:Reolinkpw-1@192.168.2.206:554/h264Preview_01_sub
#       - "http://192.168.1.79/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=pw"
#       - "ffmpeg:your_reolink_camera_sub#audio=opus"

    your_oco_camera:
      - rtsp://admin:Password@192.168.1.237:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
     # - ffmpeg:your_oco_camera#video=h264#hardware  # if your camera doesn't support H264, important for HomeKit
     # - ffmpeg:your_oco_camera#audio=opus           # only OPUS audio supported by HomeKit
#      - "http://192.168.1.189/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&Password=pw#video=copy#audio=copy#audio=opus"
#      - "ffmpeg:your_reolink_camera#audio=opus"
#       - "http://admin:Pw@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"
    your_oco_camera_sub:
      - rtsp://admin:Pw@192.168.1.237:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
#       - "http://admin:Pw@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"
#       - "http://192.168.1.79/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&Password=pw-1"
#       - "ffmpeg:your_reolink_camera_sub#audio=opus"
  network_mode: host
  homekit:
    your_oco_camera:
      name: boat house
    your_reolink_camera:
      name: workout

audio:
  enabled: true
  min_volume: 200
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - laughter
    - crying
    - singing
    - groan
    - snoring
    - cough
    - sneeze
    - burping
    - hiccup
    - fart
    - finger_snapping
    - clapping
    - meow
    - purr
    - hiss
    - quack
    - duck
    - chirp
    - bell
    - water
    - raindrop
    - police_car
    - fire_engine
    - lawn_mower
    - doorbell
    - gunsho - explosion
    - whistling


objects:
  track:
    - person
    - car
    - bird
    - airplane
    - bicycle
    - motorcycle
    - bus
    - cat
    - dog
    - cell phone
    - boat

cameras:

  
  dwcamera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/your_reolink_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
 #           - audio
        - path: rtsp://127.0.0.1:8554/your_reolink_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    zones:
      zone_driveway:
        coordinates: 1447,481,947,478,387,452,0,529,0,1080,1920,1080,1920,673
 #       objects:
 #         - person
 #         - car
 #         - dog
 #         - bus

      zone_dwe:
        coordinates: 1543,466,1579,428,567,425,416,471
#        objects:
#          - car

#    audio:
#      enabled: True
    live:
      stream_name: your_reolink_camera
    #detect:
     # stationary:
       # interval: 1
       # threshold: 50
       # max_frames:
      # Optional: Default for all object types (default: not set, track forever)
       #   default: 3000
      # Optional: Object specific values
      #    objects:
        #    car: 500
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 1
          mode: active_objects
#        required_zones:
#       - zone_dwe
#        - zone_driveway
    detect:
      fps: 5
 #     width: 1920
 #     height: 1080
#max_disappeared: 50

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      enabled: true
        # Optional: save a clean PNG copy of the snapshot image (default: shown below)
        # clean_copy: True
       # Optional: print a timestamp on the snapshots (default: shown below)
        #timestamp: False
       # Optional: draw bounding box on the snapshots (default: shown below)
       #  bounding_box: True
       # Optional: crop the snapshot (default: shown below)
       # crop: False
       # Optional: height to resize the snapshot to (default: original size)
       # height: 175
       # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
       # required_zones: []
       # Optional: Camera override for retention settings (default: global values)
      retain:
      # Required: Default retention days (default: shown below)
        default: 2
    # Optional: Per object retention days
    #objects:
     # person: 15 
  ococamera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
   #     - path: rtsp://admin:Pw@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
        - path: rtsp://127.0.0.1:8554/your_oco_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
#        - path: rtsp://admin:Pw@192.168.1.148:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
        - path: rtsp://127.0.0.1:8554/your_oco_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
 #   zones: 
 #     zone_driveway:
 #       coordinates: 1447,481,947,478,387,452,0,529,0,1080,1920,1080,1920,673
 #       objects:
 #         - person
 #         - car
 #         - dog
 #         - bus

#      zone_dwe:
#        coordinates: 1543,466,1579,428,567,425,416,471
#        objects:
#          - car

#    audio:
#      enabled: True
    live:
      stream_name: your_oco_camera
    #detect:
     # stationary:
       # interval: 1
       # threshold: 50
       # max_frames:
      # Optional: Default for all object types (default: not set, track forever)
       #   default: 3000
      # Optional: Object audiospecific values
      #    objects:
        #    car: 500
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 1
          mode: active_objects
#        required_zones:
#       - zone_dwe
#        - zone_driveway
#    detect:
 #     fps: 5
#      width: 1920
 #     height: 1080
#max_disappeared: 50

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      enabled: true
        # Optional: save a clean PNG copy of the snapshot image (default: shown below)
        # clean_copy: True
       # Optional: print a timestamp on the snapshots (default: shown below)
        #timestamp: False
       # Optional: draw bounding box on the snapshots (default: shown below)
       #  bounding_box: True
       # Optional: crop the snapshot (default: shown below)
       # crop: False
       # Optional: height to resize the snapshot to (default: original size)
       # height: 175
       # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
       # required_zones: []
       # Optional: Camera override for retention settings (default: global values)
      retain:
      # Required: Default retention days (default: shown below)
        default: 2
    # Optional: Per object retention days
    #objects:
     # person: 15 
version: 0.14
```

### Relevant Frigate log output

```shell
Frigate-go2rtc logs
2024-08-31 12:40:17.100594612 [INFO] Preparing new go2rtc config...
2024-08-31 12:40:17.498596250 [INFO] Starting go2rtc...
2024-08-31 12:40:17.695534039 12:40:17.695 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-08-31 12:40:17.695562213 12:40:17.695 INF config path=/dev/shm/go2rtc.yaml
2024-08-31 12:40:17.696130256 12:40:17.696 INF [api] listen addr=:1984
2024-08-31 12:40:17.696207141 12:40:17.696 INF [rtsp] listen addr=:8554
2024-08-31 12:40:17.696468620 12:40:17.696 INF [webrtc] listen addr=:8555/tcp
2024-08-31 12:40:27.096682468 [INFO] Starting go2rtc healthcheck service...
```

### Relevant go2rtc log output

```shell
Frigate-go2rtc logs
2024-08-31 12:40:17.100594612 [INFO] Preparing new go2rtc config...
2024-08-31 12:40:17.498596250 [INFO] Starting go2rtc...
2024-08-31 12:40:17.695534039 12:40:17.695 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-08-31 12:40:17.695562213 12:40:17.695 INF config path=/dev/shm/go2rtc.yaml
2024-08-31 12:40:17.696130256 12:40:17.696 INF [api] listen addr=:1984
2024-08-31 12:40:17.696207141 12:40:17.696 INF [rtsp] listen addr=:8554
2024-08-31 12:40:17.696468620 12:40:17.696 INF [webrtc] listen addr=:8555/tcp
2024-08-31 12:40:27.096682468 [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Let me know if you need this information.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reo link 520 and Oco

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-09-01 153651](https://github.com/user-attachments/assets/b741f93e-d60b-4e6e-b879-d59e064a99df)
