### DISCUSSION TITLE
[Support]: Does 0.14(.1?) have significantly increased IO requirements

### DISCUSSION THREAD

**Discussion by skyphyr** [blakeblackshear/frigate#13507] [General Support]
### Describe the problem you are having

Yesterday, I upgraded from 0.13(.2, I believe, that's what I downgraded to again after) to 0.14.1. While initially all seems fine after operating for a while (unclear exactly when but within 30-60 minutes), it will eventually lock the entire machine (though its running in docker) due to a massive demand for disk I/O (in top I'll see the wa increase, eventually getting into the 90s) before the machine becomes unusable requiring a hard reboot. During this the Frigate UI initially seems to work, but becomes unreliable until it fails (as all operations on that machine do). Reverting to 0.13.2 resolved this. I was using stable-tensorrt, but don't have the build identifier available due to the reversion.

Config file is the config while running 0.14 (I didn't modify it, from 0.13, but if I read the release notes correctly, it may have handled some conversion). 

The hard drive Frigate is writing to is a spinning platter (yeah, old), but it's not caused issues in prior versions. Have I/O requirements increased with 0.14?

### Version

0.14.1 (stable-tensorrt as of 2024-09-01)

### Frigate config file

```yaml
# yaml-language-server: $schema=http://gitlab:5000/api/config/schema.jso

mqtt:
  host: gitlab
  port: 1883
  user: *****
  password: *****

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - bicycle
    - motorcycle
    - car
    - bear
    - cat
    - dog
    - horse
  filters:
    person:
      min_area: 576
      min_score: 0.76
      threshold: 0.8
    car:
      min_area: 1800
    bicycle:
      min_area: 1400
      min_score: 0.75
      threshold: 0.82
    motorcycle:
      min_area: 1400
      min_score: 0.75
      threshold: 0.82


record:
  enabled: true
  retain:
    days: 2

  events:
    retain:
      default: 30

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  streams:
    backyard:
      - rtsp://frigate:2305TheB3stCam5@192.0.0.101:554/cam/realmonitor?channel=1&subtype=0
    office:
      - rtsp://frigate:2305TheB3stCam5@192.0.0.102:554/cam/realmonitor?channel=1&subtype=0
    balcony:
      - rtsp://frigate:2305TheB3stCam5@192.0.0.103:554/cam/realmonitor?channel=1&subtype=0
    driveway:
      - rtsp://frigate:2305TheB3stCam5@192.0.0.104:554/cam/realmonitor?channel=1&subtype=0
    frontdoor:
      - rtsp://frigate:2305TheB3stCam5@192.0.0.105:554/cam/realmonitor?channel=1&subtype=0
  webrtc:
    candidates:
      - 192.0.0.69:8555
      - stun:8555

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    detect:
      width: 2048
      height: 900

  office:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/office
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    objects:
      filters:
        bear:
          min_area: 576
          min_score: 0.85
          threshold: 0.9

    detect:
      width: 2048
      height: 900

  balcony:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/balcony
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    detect:
      width: 1920
      height: 1080

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    detect:
      width: 2048
      height: 900

  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    detect:
      width: 1920
      height: 1080
version: 0.14
```

### Relevant Frigate log output

```shell
Couldn't get this due to the machine being unresponsive, could try again, but would need pointers as to most important data there's a limited window before everything grinds to a halt.
```

### Relevant go2rtc log output

```shell
Couldn't get this due to the machine being unresponsive, could try again, but would need pointers as to most important data there's a limited window before everything grinds to a halt.
```

### FFprobe output from your camera

```shell
Couldn't get this due to the machine being unresponsive, could try again, but would need pointers as to most important data there's a limited window before everything grinds to a halt.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

IPC-Color4K-B180

### Docker Compose file
```
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /storage/Frigate/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - /storage/Frigate/mosquitto/config:/mosquitto/config
      - /storage/Frigate/mosquitto/data:/mosquitto/data
      - /storage/Frigate/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 1883:1883
      - 9001:9001
  frigate:
    container_name: frigate
    #privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "8562mb" # update for your cameras based on calculation above
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/Frigate/config:/config
      - /storage/Frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC
    environment:
      - FRIGATE_RTSP_PASSWORD=*****
      - PLUS_API_KEY=*****
      - YOLO_MODELS=yolov7x-640,yolov7-640,yolov7-320,yolov7x-320,yolov7-tiny-416
```
