### DISCUSSION TITLE
[Detector Support]: Correctly identified object, yet repeatedly.

### DISCUSSION THREAD

**Discussion by leonbrag** [blakeblackshear/frigate#13504] [Detector Support]
### The same object identified as new on any light/motion changes

This is a situation for both driveway and garage. 

I have a parked car (in both cases). Every time there is change of lighting condition (say at night light from passing car change many pixels) or in garage window there is motion, **new** car alert is triggered.

I can see logic:
1. Motion is detected
2. Motion is correctly quantified as car, since there is a car parked.

However I don't want to be alerted about the same parked car.

None of the motion turning nor selecting zone help .

What can I do to not be alerted about the **same** car ? 

### Version

.14

### Frigate config file

```yaml
Garage: #
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.17/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.17/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.043,0.053,0.367,0.056,0.37,0.093,0.043,0.096

      threshold: 30
      contour_area: 19
      improve_contrast: 'true'
    review:
      alerts:
        required_zones: zoneGarage


    zones:
      zoneGarage:
        coordinates: 
          0.011,0.127,0.26,0.134,0.301,0.157,0.353,0.
```

### docker-compose file or Docker CLI command

```yaml
na
```

### Relevant Frigate log output

```shell
na
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

na

**Comment by NickM-27** [comment]
We need to see your entire config.

**Reply by leonbrag** [reply]
```
mqtt:
  enabled: true
#  enabled: false
#  host: 192.168.4.33
  host: hpdebian
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  topic_prefix: frigate
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  fps: 5

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - dog


detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt



go2rtc:
  rtsp:
    username: xxx
    password: xxx
  streams:
    Driveway:  #example camera without audio 
      - rtsp://xxx:xxx@192.168.10.11/Streaming/Channels/101
    Front_Door: # example camera with audio
      - rtsp://xxx:xxx@192.168.10.13/Streaming/Channels/101
    Back_Yard:  #example camera without audio
      - rtsp://xxx:xxx@192.168.10.22/Streaming/Channels/101
    Basement:  #example camera with audio
      - rtsp://xxx:xxx@192.168.10.14/Streaming/Channels/101
    Side_Yard:  #example camera without audio
      - rtsp://xxx:xxx@192.168.10.23/Streaming/Channels/101
    Garage:  #example camera with audio
      - rtsp://xxx:xxx@192.168.10.17/Streaming/Channels/101
    Bedroom:  #example camera with audio
      - rtsp://xxx:xxx@192.168.10.10/Streaming/Channels/101

birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720

snapshots:
  enabled: true

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion


cameras:

  # test:
  #   enabled: true 
  #   ffmpeg:
  #     inputs:
  #     - path:  /media/frigate/exports/Front_Door_boyk11.mp4
  #       input_args: -re -stream_loop -1 -fflags +genpts
  #       roles:
  #         - detect
  #         - record


  Driveway: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.11/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.11/Streaming/Channels/101
          roles:
            - record
    motion:
      mask:
        - 0.039,0.048,0.371,0.05,0.373,0.093,0.042,0.096
        - 0.725,0.909,0.829,0.911,0.833,0.957,0.725,0.952
        - 0.3,0.003,0.991,0.013,0.996,0.377
      threshold: 45
      contour_area: 33
      improve_contrast: 'true'

    snapshots:
      required_zones:
        - zoneFrontYard

    review:
      alerts:
        required_zones: zoneFrontYard
      detections: {}

    mqtt:
      required_zones:
        - zoneFrontYard

    zones:
      zoneFrontYard:
        coordinates: 
          0.028,0.374,0.092,0.218,0.145,0.146,0.181,0.111,0.261,0.027,0.282,0.008,0.395,0.04,0.512,0.096,0.54,0.121,0.587,0.137,0.678,0.203,0.774,0.288,0.837,0.346,0.917,0.412,0.98,0.473,0.98,0.495,0.989,0.963,0.016,0.971
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - person
          - car


  Front_Door: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.10.13
      port: 80
      user: xxx
      password: xxx
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.13/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.13/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.045,0.035,0.636,0.038,0.637,0.086,0.042,0.089

      threshold: 35
      contour_area: 17
      improve_contrast: 'true'
    snapshots:
      required_zones:
        - frontYard

    review:
      alerts:
        required_zones: frontYard
        labels:
          - person
      #detections: {}
    mqtt:
      required_zones:
        - frontYard

    zones:
      frontYard:
        coordinates: 
          0.519,0.065,0.625,0.078,0.625,0.163,0.626,0.182,0.69,0.186,0.741,0.363,0.835,0.698,0.888,0.91,0.907,0.981,0.337,0.994,0.015,0.981,0.012,0.032,0.395,0.022,0.4,0.471
        loitering_time: 0
        objects:
          - person
          #- car
          - cat


  Back_Yard: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.10.22
      port: 80
      user: xxx
      password: xxx
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.22/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.22/Streaming/Channels/101
          roles:
            - record
    motion:
      mask:
        - 0.046,0.034,0.637,0.031,0.638,0.095,0.046,0.096
        - 0.793,0.916,0.975,0.916,0.978,0.97,0.794,0.976
      threshold: 47
      contour_area: 27
      improve_contrast: 'true'


  Basement: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.14/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.14/Streaming/Channels/101
          roles:
            - record
    motion:
      mask:


        - 0.042,0.061,0.639,0.061,0.641,0.122,0.04,0.119
        - 0.725,0.872,0.907,0.871,0.911,0.92,0.725,0.922
  Side_Yard: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.23/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.23/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.042,0.04,0.371,0.04,0.37,0.083,0.043,0.083


      threshold: 36
      contour_area: 15
      improve_contrast: 'true'


  Garage: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.17/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.17/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.043,0.053,0.367,0.056,0.37,0.093,0.043,0.096

      threshold: 30
      contour_area: 19
      improve_contrast: 'true'
    review:
      alerts:
        required_zones: zoneGarage


    zones:
      zoneGarage:
        coordinates: 
          0.011,0.127,0.26,0.134,0.301,0.157,0.353,0.177,0.636,0.087,0.998,0.679,0.998,0.971,0.01,0.989


  Bedroom: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.10.10/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.10.10/Streaming/Channels/101
          roles:
            - record
    motion:
      mask:

        - 0.041,0.066,0.637,0.061,0.638,0.115,0.042,0.122
        - 0.724,0.871,1,0.87,1,0.919,0.728,0.926
      threshold: 59
      contour_area: 52
      improve_contrast: 'true'
version: 0.14
camera_groups:
  Front:
    order: 1
    icon: LuWarehouse
    cameras:
      - Driveway
      - Front_Door

```

These are the example of garage alerts for the same car parked there:

![image](https://github.com/user-attachments/assets/f8d7ab67-ee86-4098-bbeb-e1278dbcf111)
