### DISCUSSION TITLE
[Camera Support]: Audio Level 0db in Audio Detection

### DISCUSSION THREAD

**Discussion by Morphy99** [blakeblackshear/frigate#13511] [Camera Support]
### Describe the problem you are having

Just testing out audio detection and although my camera plays back audio, the audio level sensor in the HA integration is stuck on 0db.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: *

detectors:
  coral0:
    type: edgetpu
    device: pci:0
auth:
  enabled: false
objects:
  track:
    - person
    - car
    - dog
    - bird
    - mouse
  filters:
    person:
      threshold: 0.7
      max_ratio: 0.6
review:
  alerts:
    labels:
      - person

record:
  expire_interval: 10
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 20
      mode: motion
    pre_capture: 2
    post_capture: 30

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 20

detect:
  stationary:
    interval: 10

motion:
  improve_contrast: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    front:
      - ffmpeg:http://*/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*#video=copy#audio=opus
    front_sub:
      - ffmpeg:http://*/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=*#video=copy#audio=opus

cameras:
##############################################################front########################################################################
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      max_disappeared: 160
      width: 2048
      height: 1536
      fps: 8
    audio:
      enabled: True
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-520

### Screenshots of the Frigate UI's System metrics pages

-
