### DISCUSSION TITLE
Frigate seems slow to start or restart and I get a bunch of these errrors?

### DISCUSSION THREAD

**Discussion by TheeDudenator** [blakeblackshear/frigate#13517] [General Support]
### Describe the problem you are having

192.168.1.30 is my Linux machine that is running Frigate in docker

2024-09-03 08:03:39.399306351  2024/09/03 08:03:39 [error] 159#159: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.30, server: , request: "GET /ws HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "192.168.1.30:5000"

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.20
  port: 1883
  user: mqtt-user
  password: mqtt-user
  
detectors:
  coral_USB:
    type: edgetpu
    device: usb
  coral_PCIa:
    type: edgetpu
    device: pci:0
  coral_PCIb:
    type: edgetpu
    device: pci:1

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects
  
snapshots:
  enabled: True
  retain:
    default: 30

record:
  enabled: True
  retain:
    days: 5
    mode: all
  events:
    retain:
      default: 5
      mode: motion

cameras:
  Porch_Front: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
```

### Relevant Frigate log output

```shell
Nothing in log
```

### Relevant go2rtc log output

```shell
Nothing in log
```

### FFprobe output from your camera

```shell
Nothing in log
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua
