### DISCUSSION TITLE
Frigate won't play .mp4 on review page, loading forever

### DISCUSSION THREAD

**Discussion by screwb0x** [blakeblackshear/frigate#13514] [General]
Hi,
so i set up Frigate with just 2 cams and I'm quite happy with it. But, those cameras don't have a rtsp stream. I can grab the stream via http and all is working. Basicly all the log is saying:
`"Copied /media/frigate/recordings/2024-09-03/09/Foscam/41.34.mp4 in 0.1179051399230957 seconds."` etc.
I have live streams, i have previews, no other errors on log only "info". Even the .mp4 files which are prefectly recorded to a share are fine and i can view them if i mount the share and use VLC etc.
But if i click on a event the http://x.x.x.x:5000/review page opens and the first frame of the video shows a loading icon which never finishes.
Even then. No errors in Log. Only:
`"GET /api/preview/all/start/1725267600/end/1725357600 HTTP/1.1" 200 7622 "http://192.168.1.6:5000/review" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" "-"`
And nothing happening.
I already read a seemingly simmilar issue which was mainly about transcoding and using go2rtc but i can not get this to work and on the other hand the browser should be perfectly fine to load and show an .mp4 file or am i wrong?
Do i miss somehting?

Commented the go2rtc lines out because it was not working, but here is my atm working camera config:

```
# go2rtc:
#   streams:
#     Foscam: ffmpeg:http://192.168.1.77/videostream.cgi?user=admin&pwd=password

cameras:
  Foscam:    #<-- you can change your camera name here
    ffmpeg:
      #output_args:
        #record: -f segment -segment_time 10 -strftime 1 -c copy
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps
        1
      inputs:
        #- path: rtsp://192.168.1.6:8554/Foscam
        - path: http://192.168.1.77/videostream.cgi?user=admin&pwd=password
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    detect:
      enabled: true
      width: 1280
      height: 768
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      quality: 100
      height: 600
```

**Comment by NickM-27** [comment]
It seems the browser is failing to play the recordings, you can check browser logs as well as maybe try different browsers

**Reply by jjavin** [reply]
In the browser, the last hour ones are displayed correctly, the problem is that after 1 hour, they disappear automatically. The ones that I can see now, for example, will be gone in 1 hour (from the alert). 

<img width="1454" alt="CAP1" src="https://github.com/user-attachments/assets/29954df2-14e5-48e9-8921-7cb895de9b88">

**Reply by NickM-27** [reply]
So these videos don't play when you hover after an hour? Could be a browser issue because the current hour isn't a video it is a stream of images

**Reply by jjavin** [reply]
Sorry I have explained myself wrong, in one hour it does not appear directly in alerts (nor the preview), it is not a problem of reproduction, it is that the alert disappears, if you look at the sidebar, I only have red dots in the last hour, when there were really alerts throughout the morning, but the ones before 14:00 have disappeared. 
<img width="113" alt="Captura de pantalla 2024-09-03 a las 14 54 37" src="https://github.com/user-attachments/assets/ebc4fd88-c661-43d1-85d9-a3556f495ea0">

**Reply by NickM-27** [reply]
oh, that would be an issue of the recordings being deleted so the review items are deleted as well

**Reply by jjavin** [reply]
The camera recordings are intact, only the alerts disappear after one hour (always just 1 hour).

For example, right now the hour has already passed: 

<img width="1448" alt="Captura de pantalla 2024-09-03 a las 15 11 18" src="https://github.com/user-attachments/assets/efc7ebbe-a3a6-4930-825a-958bb6eeb762">


In the log: 

```
Type
Info
Timestamp
2024-09-03 14:51:45
Tag
frigate.record.cleanup
Message
the list is ['1725364319.794265-g38ev9', '1725364326.741567-phtbyk', '1725364820.009902-r016xu', '1725364824.617275-6by2uo', '1725364910.53537-m3fuqq', '1725364985.512321-e4t2si', '1725364988.302803-4bnndw', '1725365074.333023-mffmfp', '1725365213.553856-2ojb4u', '1725365278.58281-24ysgk', '1725365386.773513-90hlpo', '1725365420.198815-9ipovq', '1725365481.787543-jfh5qc', '1725365486.142204-cex0ls', '1725365646.481597-5mymv6', '1725365732.902724-ptqzr4', '1725365833.522753-tfdv0r', '1725365886.291044-jzqp0l', '1725365920.503959-qnaln5', '1725365926.137799-3emhof', '1725365989.545239-28050i', '1725365992.301917-ko7si7', '1725366046.155621-4ux8dz', '1725366123.341456-36r5p5', '1725366193.151485-wfg0hl', '1725366239.007537-nls7xl', '1725366253.031748-alum8w', '1725366478.122785-suj048', '1725366527.130333-8equ2k', 
```

**Reply by NickM-27** [reply]
you didn't specify that you are running 0.15, and it's not clear if you and the author are different users or not. Either way, a full config, copy of logs, etc is needed

**Reply by screwb0x** [reply]
I tried Fedora with Chrome and Firefox, same in Windows. Always same behavior. Doubt it is the Browser or OS. That’s why i‘m so confused…

**Reply by jjavin** [reply]
I have nothing to do with screwb0x, I am another user. 

I'm running a docker with proxmox and version: 0.15.0-21a50cc
I'll pass you the complete log.
[frigate-logs.txt](https://github.com/user-attachments/files/16849470/frigate-logs.txt)

**Reply by NickM-27** [reply]
then you shouldn't be commenting on an entirely unrelated discussion. you should be making your own discussion

**Reply by NickM-27** [reply]
@screwb0x you will want to check browser logs and see if anything is there, would be better if you can describe in more detail exactly what is going on

**Reply by screwb0x** [reply]
That‘s the point. I was just replying to @NickM-27 who was trying to help me. That’s why I‘m replying to this specific answer.
Will try to get some more logs. But there is not much more in Frigate logs and I‘m not very familiar with browser logs and how to get them. But I‘ll try and cone back later.
I thought I at least described it precisely enough but again. It is as simple as that. Recordings are working. The .mp4 files are playable in VLC but if i try to watch them in browser through Frigate there is only a running „loading“ circle in the middle and nothing happens.  Independently of the Browser or OS. Live stream is working. Previews are working everything is fine. But video is not loading and even with „debug“ on there is no error in Frigate.
Is there some cli tool I could leverage to get more logs out of my container or any kind of help/tutorial which I can follow to obtain logs which would help here?

**Reply by NickM-27** [reply]
what you are describing sounds like the browsers are unable to playback the recordings, VLC working does not mean there is nothing wrong with the recordings, just that VLC is able to handle it. You can get browser logs by right clicking, pressing inspect element, then go to console

**Reply by screwb0x** [reply]
Found a snippet in the ngnix log on Frigate maybe this is a clue?
`2024/09/03 16:51:05 [error] 163#163: *12290 ngx_http_vod_validate_streams: no matching streams were found while reading media header, client: 192.168.1.13, server: , request: "GET /vod/Foscam/start/1725372000/end/1725375066/master.m3u8 HTTP/1.1", host: "192.168.1.6:5000", referrer: "http://192.168.1.6:5000/review"`

This is the only [error] i can find when opening the review page

**Reply by screwb0x** [reply]
Got this out of the Browser following your steps:
![image](https://github.com/user-attachments/assets/e29299c5-778f-4797-97b7-8b89ff4c83f5)

**Reply by NickM-27** [reply]
I am not sure what that first message is related to, maybe some kind of extension? Looks like something is not correct, can you show a screenshot of the network tab?

**Reply by screwb0x** [reply]
Hope this helps?
![image](https://github.com/user-attachments/assets/564ac42e-1e7f-45ba-aaa7-00147f0f411f)

**Reply by screwb0x** [reply]
Recently found out i also have Problems with expoting also. So there is more to that and i think i points to the Docker container itself and that something with my network etc is not "okay"?
![image](https://github.com/user-attachments/assets/7f485912-8678-4ebc-92ce-1830a8825ff7)

Here are the Errors in Detail:
`Failed to export recording for command ffmpeg -hide_banner -y -protocol_whitelist pipe,file,http,tcp -i http://127.0.0.1:5000/vod/Foscam/start/1725436737/end/1725436797/index.m3u8 -c copy -movflags +faststart /media/frigate/exports/Foscam_fjg2w3.mp4`

`[http @ 0x55a07f8f23c0] HTTP error 400 Bad Request
`

`http://127.0.0.1:5000/vod/Foscam/start/1725436737/end/1725436797/index.m3u8: Server returned 400 Bad Request`

Maybe I'm missing some network specific settings in my config? It all boils down to "Bad Request" every time if something is using the recordings.

I'm quite new to Frigate, did a lot of copy and paste, writing some stuff on my own and figured out a way so that at least my camerastreams are working, recordings are made and everything seems fine because no errors on the starting page. But more and more it seems I'm missing something.

**Reply by NickM-27** [reply]
That's very odd, what is your docker compose

**Reply by screwb0x** [reply]
I don't know if you are familiar with Unraid, but I use it for years and handling many docker container is quite good and way easier than as example portainer. So im posting a Screenshot and I think you will see that it resembles all the docker variables in a GUI like tool. Maybe i missed something here.
![image](https://github.com/user-attachments/assets/65666428-ff32-4892-b2a7-d0570ffd2195)


If not, i could easily write down a compose with all of the options if it is not so obvious as I think. Just let me know.
I'm following a support thread on Unraid.com also, but it seems that it is a uncommon problem. Many people use it with Unraid and have no problems it seems.

**Reply by NickM-27** [reply]
yes, I use unraid. 

it seems very odd that this would be occurring, please try reproducing this and then copy the latest nginx logs and paste here

**Reply by screwb0x** [reply]
Will do, but as it looks to me it all boils down to a 400 Bad Request if my Browser requests anything regarding recordings. Lifestreams or thumbnail-previews work flalessly. Same to motion detection. I'm not that good at those points. But what could be the problem with this master.m3u8 file.
Is this generated on demand if the browser requests it and the generation of it is not working etc?
I even deleted everything out of my /appdata/frigate folder and started from scratch only carrying over my config.yml.
Seems to me it has to do something with it. So here it is. As i say, im not very skilled and it consists to 80% of copy and paste from couple tutorials etc.

```
mqtt:
  host: 192.168.1.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
  user: mqtt
  password: xxxxx

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  
birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

logger:
  logs:
    frigate.record.maintainer: debug

objects:
  track:
    - person

cameras:
  Foscam:   
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: http://192.168.1.77/videostream.cgi?user=admin&pwd=xxxxx
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    detect:
      enabled: true
      width: 1280
      height: 768
      fps: 5
    motion:
      mask: 0.327,0.102,0.465,0.095,0.484,0.336,0.353,0.328

  picam:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict
        experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: http://192.168.1.76:8081
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    detect:
      enabled: true
      width: 1280
      height: 768
      fps: 5
```
