### DISCUSSION TITLE
[Camera Support]: Dahua / Empire Tech Andy IPC-Color4K-T180 LED lights stop working

### DISCUSSION THREAD

**Discussion by jhmeier** [blakeblackshear/frigate#13513] [Camera Support]
### Describe the problem you are having

Hello,

I have a weird issue with my IPC-Color4k-T180 from Empire Tech Andy (it's a labeled Dahua camera). The camera has LED lights for the night. These can either be turned on automatically or manually.
The strange thing is now if I connect with go2rtc using RTSP this function stops to work after some time.  Thus the lights neither turn on automatically nor can be turned on manually. If I change it to the sub stream the issue occurs directly.

Andys current solution is unfortunately only to point to his software.

Anyone else had the same issue or has an idea what can cause this?

### Version

0.14.1

### Frigate config file

```yaml
go2rtc:
  streams:
    cam03_terrace_main:
      - rtsp://user:password@ip:554/cam/realmonitor?channel=1&subtype=0

cameras:
  cam03-terrace:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: true
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/cam03_terrace_main
          input_args: preset-rtsp-restream
          roles:
            - record
            #- audio
            - detect
      hwaccel_args: []
    objects:
      track:
        - dog
        - cat
        - deer
```

### Relevant Frigate log output

```shell
No issues in log file
```

### Relevant go2rtc log output

```shell
No issues in log file
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Proxmox

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua IPC-Color4K-T180 LED

### Screenshots of the Frigate UI's System metrics pages

.

**Comment by hawkeye217** [comment]
Can you provide the output of `http://frigate_ip:port/api/go2rtc/streams/cam03_terrace_main`?

**Comment by jhmeier** [comment]
{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:50720","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=1;sprop-sps=QgEBAUAAAAMAgAAAAwAAAwC0oACACAHCWNrksrZrlxAIAAADAAgAAAMAofxYlA==;sprop-pps=RAHA4YPAwUUk;sprop-vps=QAEMAf//AUAAAAMAgAAAAwAAAwC0rAk=\r\na=control:trackID=0\r\n","send":2325110827,"senders":["96 H265, bytes=2298243803, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/cam03_terrace_main","user_agent":"FFmpeg Frigate/0.14.1-f4f3cfa"},{"medias":["video, sendonly, ALL","audio, sendonly, ALL","audio, recvonly, ANY"],"remote_addr":"127.0.0.1:38668","senders":["98 H265, bytes=0, receivers=1","8 PCMA/8000, bytes=0, receivers=1"],"type":"probe","user_agent":"python-requests/2.32.3"}],"producers":[{"medias":["video, recvonly, H265","audio, recvonly, PCMA/8000"],"receivers":["98 H265, bytes=2298243803, senders=2","8 PCMA/8000, bytes=0, senders=1"],"recv":2318433935,"remote_addr":"x.x.x.x:554","sdp":"v=0\r\no=- 2252283416 2252283416 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-packetization-supported:IV\r\na=x-rtppayload-supported:IV\r\na=x-summary:Oversea\r\nm=video 0 RTP/AVP 98\r\na=control:trackID=0\r\na=framerate:20.000000\r\na=rtpmap:98 H265/90000\r\na=fmtp:98 profile-id=1;sprop-sps=QgEBAUAAAAMAgAAAAwAAAwC0oACACAHCWNrksrZrlxAIAAADAAgAAAMAofxYlA==;sprop-pps=RAHA4YPAwUUk;sprop-vps=QAEMAf//AUAAAAMAgAAAAwAAAwC0rAk=\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=1\r\na=rtpmap:8 PCMA/8000\r\na=recvonly\r\n","type":"RTSP active producer","url":"rtsp://x.x.x.x:554/cam/realmonitor?channel=1&subtype=0/","user_agent":"go2rtc/1.9.2"}]}

**Reply by hawkeye217** [reply]
The output looks fine. This must be some limitation or bug with the camera firmware. I’m not aware of any way to work around it if you want to continue to use the main stream.

**Comment by jhmeier** [comment]
Thanks for your quick support - hope Andy finds a solution with the firmware.

**Reply by hawkeye217** [reply]
Happy to help. Andy has been super helpful to me in the past, hope he can be for you too!

**Comment by fitzd** [comment]
Hey I have the same camera and run the same setup as you and have the same problem. You're not the only one :(

**Reply by jhmeier** [reply]
Andy asks for a test with this firmware:
https://we.tl/t-E4GERO4ssY

Maybe you can also test this one.

**Reply by jhmeier** [reply]
Still the same issue for me :/

**Reply by fitzd** [reply]
Same issue still for me too. Andy provided me the same one as well. I noticed if I switch resolution to a lower one other than the maximum, the scheduling works for a day and then same issue. Switching back to max resolution immediately causes the leds to turn off even if its scheduled to be on.

**Reply by jhmeier** [reply]
That's interesting - when the LEDs are turned on before I connect with RTSP they keep working the whole night. They are also automatically turned off (in auto mode) in the morning but turning them back on fails.
Andy said he is going to open a case at Dahua.

**Reply by fitzd** [reply]
Good info thank you, eager to see what Dahua says

**Comment by The1Percent** [comment]
Same issue here. I have not found a workaround yet. I wonder if the hikvision version has the same problem.

**Reply by jhmeier** [reply]
As @fitzd suggested I reduced FPS and resolution - now it takes some days until the error occurs. Unfortunately still no update from Andy.

**Reply by jquatier** [reply]
Also seeing this. Very weird, let me know if you find out anything.

**Comment by DD81** [comment]
I have the same problem and contacted Andy.
Finally, the Dahua engineer investigated and said that there is some problem with the go2rtc implementation, since the problem does not occur if the stream is read via ffmpeg.
In fact, I was able to avoid the lighting control problem by setting the go2rtc section to read the stream from the IPC-Color4K-T180 LED by doing the following

`ffmpeg:rtsp://USER:PASS@IPADDR:554/cam/realmonitor?channel=1&subtype=0`

It has been several months since I set this up and the lighting control is still working fine.

The following error is recorded when reading the IPC-Color4K-T180 stream directly in go2rtc.

`2024-09-21 11:47:10.706743334  20:47:10.706 INF [streams] can't add track error="wrong response on DESCRIBE"`
`2024-09-21 11:47:10.706823634  20:47:10.706 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://user:pass@ipaddr:554/cam/realmonitor?channel=1&subtype=2`

**Reply by NickM-27** [reply]
Have you tried disabling back channel? Add `#backchannel=0` to the end of the url

**Reply by DD81** [reply]
I disabled the back channel. I will test it for a few days to see if it causes any problems with lighting control.

As an aside, when I directly read streams from IPC-Color4K-T180 or SDT4E425-8P-GB-APV1 (Dahua X-Spans series) with go2rtc, there was an issue where the AI ​​object detection + sound warning on the camera side would not work.
That issue was fixed by adding `#backchannel=0` to the end of the URL.

**Reply by DD81** [reply]
It has been a few days since I disabled the backchannel and so far the lighting control is working fine.
The problems with the IPC-Color4K-T180 and SDT4E425-8P-GB-APV1 seem to be caused by the backchannel connection being enabled.

Does Frigate plan to support two way audio?

**Reply by NickM-27** [reply]
Frigate already supports two way audio

**Reply by DD81** [reply]
I did not know that Frigate supports 2-way audio.
I tried enabling the back channel connection again, but the microphone icon does not appear in the Live view of the IPC-Color4K-T180.
I get the following error when I enable the back channel connection, is there another setting I need to do?

```
2025-01-08 13:18:54.646882190  [INFO] Preparing new go2rtc config...
2025-01-08 13:18:54.696081119  [INFO] Got IP address from supervisor: 192.168.1.20
2025-01-08 13:18:54.716934590  [INFO] Got WebRTC port from supervisor: 8555
2025-01-08 13:18:54.989837866  [INFO] Starting go2rtc...
2025-01-08 13:18:55.076878947  22:18:55.076 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-08 13:18:55.076882615  22:18:55.076 INF config path=/dev/shm/go2rtc.yaml
2025-01-08 13:18:55.077209124  22:18:55.077 INF [api] listen addr=:1984
2025-01-08 13:18:55.077361758  22:18:55.077 INF [rtsp] listen addr=:8554
2025-01-08 13:18:55.077493657  22:18:55.077 INF [webrtc] listen addr=:8555/tcp
2025-01-08 13:19:04.641106927  [INFO] Starting go2rtc healthcheck service...
2025-01-08 13:19:10.459478990  22:19:10.459 INF [streams] can't add track error="wrong response on DESCRIBE"
2025-01-08 13:19:10.459564452  22:19:10.459 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://id:pass@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
2025-01-08 13:19:15.668763997  22:19:15.668 INF [streams] can't add track error="wrong response on DESCRIBE"
2025-01-08 13:19:15.669022965  22:19:15.668 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://id:pass@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
2025-01-08 13:20:19.387333616  22:20:19.387 INF [streams] can't add track error="wrong response on DESCRIBE"
2025-01-08 13:20:19.387393755  22:20:19.387 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://id:pass@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
2025-01-08 13:20:27.982457669  22:20:27.982 INF [streams] can't add track error="wrong response on DESCRIBE"
2025-01-08 13:20:27.982604949  22:20:27.982 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://id:pass@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
```

**Reply by NickM-27** [reply]
in general it is recommended to leave the first stream with backchannel disabled and define a second connection to the sub stream with it enabled.

**Reply by DD81** [reply]
Now I have connected the back channel to the sub stream only and set it to display the sub stream in the live view.
The go2rtc error that occurred earlier has disappeared, but the microphone icon is not displayed.

**Reply by NickM-27** [reply]
you'll need to use the probe button in go2rtc or check the network response of the probe call in the browser dev tools when clicking on a camera

**Reply by DD81** [reply]
I accessed port 1984 and clicked the Probe button to get the data.
Is this data correct?

```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.8.20:554/cam/realmonitor?channel=1\u0026subtype=2/",
      "remote_addr": "192.168.8.20:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 2252288914 2252288914 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-packetization-supported:IV\r\na=x-rtppayload-supported:IV\r\na=x-summary:Oversea\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:15.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D6033;sprop-parameter-sets=Z01gM4mNUCgCPQgAAAMACAAAAwDweLE1AA==,KO4CPIAA\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/64000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1108\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=5\r\na=rtpmap:8 PCMA/8000\r\na=sendonly\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPEG4-GENERIC/64000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=0, senders=1",
        "97 MPEG4-GENERIC/64000, bytes=0, senders=1"
      ],
      "senders": [
        "8 PCMA/8000, bytes=0, receivers=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "probe",
      "remote_addr": "172.30.32.1:51248",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        "0 ANY, bytes=0, senders=1"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/64000, bytes=0, receivers=1"
      ]
    }
  ]
}
```

**Reply by NickM-27** [reply]
Okay your camera supports two way audio. Are you connecting to Frigate using a secure connection? This is required

**Reply by DD81** [reply]
I installed Frigate using the Homeassistant add-on.
How do I set up Frigate to connect via HTTPS?

**Reply by NickM-27** [reply]
Via nabu casa, reverse proxy, DDNS, etc.

**Reply by DD81** [reply]
I tested with nabu casa and the microphone icon appears and the microphone works.
However, when I click on the microphone button, the sound from the camera is muted.
Even if I disable the microphone button, the sound from the camera is still muted, so I have to reload the page.

Also, the AI object detection alerts no longer work, probably because I set `#backchannel=1` in the sub-stream.

The following error was recorded when switching Enable/Disable for the microphone.

```
2025-01-08 15:43:04.166903758  [INFO] Preparing new go2rtc config...
2025-01-08 15:43:04.213880785  [INFO] Got IP address from supervisor: 192.168.1.20
2025-01-08 15:43:04.230154536  [INFO] Got WebRTC port from supervisor: 8555
2025-01-08 15:43:04.525466689  [INFO] Starting go2rtc...
2025-01-08 15:43:04.635231524  00:43:04.635 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-08 15:43:04.635234462  00:43:04.635 INF config path=/dev/shm/go2rtc.yaml
2025-01-08 15:43:04.635589119  00:43:04.635 INF [api] listen addr=:1984
2025-01-08 15:43:04.635703139  00:43:04.635 INF [rtsp] listen addr=:8554
2025-01-08 15:43:04.635832046  00:43:04.635 INF [webrtc] listen addr=:8555/tcp
2025-01-08 15:43:14.163298087  [INFO] Starting go2rtc healthcheck service...
2025-01-08 15:47:19.414365966  00:47:19.414 INF [streams] can't get track error="wrong response on DESCRIBE"
2025-01-08 15:47:19.414459830  00:47:19.414 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:Administrator@192.168.8.20:554/cam/realmonitor?channel=1&subtype=2#backchannel=1
2025-01-08 15:56:24.098138016  00:56:24.098 INF [streams] can't add track error="wrong response on DESCRIBE"
2025-01-08 15:56:24.098216322  00:56:24.098 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:Administrator@192.168.8.20:554/cam/realmonitor?channel=1&subtype=2#backchannel=1
2025-01-08 15:57:15.635286219  00:57:15.635 INF [streams] can't get track error="wrong response on DESCRIBE"
2025-01-08 15:57:15.635428954  00:57:15.635 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:Administrator@192.168.8.20:554/cam/realmonitor?channel=1&subtype=2#backchannel=1
```

**Reply by NickM-27** [reply]
Do you have opus audio transcoding configured? That is required for webrtc audio

**Reply by DD81** [reply]
Thanks for the quick response.

I did not set up Opus transcoding.
I set up the go2rtc section as described below and I no longer get the go2rtc error.
However, the transceiver-like status is still the same and I cannot hear the sound from the camera unless I disable the microphone.
The only thing that has changed from earlier is that the sound from the camera is now restored without reloading the page.

Am I missing something else?

```
go2rtc:
  webrtc:
    candidates:
      - 192.168.1.20:8555
      - stun:8555
  streams:
    c01:
      - rtsp://id:pass@192.168.8.11:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c01_sub:
      - rtsp://id:pass@192.168.8.11:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c02:
      - rtsp://id:pass@192.168.8.112:554/cam/realmonitor?channel=1&subtype=0#media=video#backchannel=0
      - ffmpeg:c01_sub#audio=copy
    c02_sub:
      - rtsp://id:pass@192.168.8.112:554/cam/realmonitor?channel=1&subtype=2#media=video#backchannel=0
      - ffmpeg:c01_sub#audio=copy
    c02_panorama:
      - rtsp://id:pass@192.168.8.12:554/cam/realmonitor?channel=1&subtype=0#media=video#backchannel=0
      - ffmpeg:c01_sub#audio=copy
    c02_panorama_sub:
      - rtsp://id:pass@192.168.8.12:554/cam/realmonitor?channel=1&subtype=2#media=video#backchannel=0
      - ffmpeg:c01_sub#audio=copy
    c02_ptz:
      - rtsp://id:pass@192.168.8.12:554/cam/realmonitor?channel=2&subtype=0#media=video#backchannel=0
      - ffmpeg:c01_sub#audio=copy
    c02_ptz_sub:
      - rtsp://id:pass@192.168.8.12:554/cam/realmonitor?channel=2&subtype=2#media=video#backchannel=0
      - ffmpeg:c01_sub#audio=copy
    c03:
      - rtsp://id:pass@192.168.8.13:554/cam/realmonitor?channel=1&subtype=0#media=video#backchannel=0
      - ffmpeg:c03_spotter#audio=copy
    c03_sub:
      - rtsp://id:pass@192.168.8.13:554/cam/realmonitor?channel=1&subtype=2#media=video#backchannel=0
      - ffmpeg:c03_spotter#audio=copy
    c03_spotter:
      - rtsp://id:pass@192.168.8.113:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c03_spotter_sub:
      - rtsp://id:pass@192.168.8.113:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c04:
      - rtsp://id:pass@192.168.8.14:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c04_sub:
      - rtsp://id:pass@192.168.8.14:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c05:
      - rtsp://id:pass@192.168.8.15:554/cam/realmonitor?channel=1&subtype=0#media=video#backchannel=0
      - ffmpeg:c04#audio=copy
    c05_sub:
      - rtsp://id:pass@192.168.8.15:554/cam/realmonitor?channel=1&subtype=2#media=video#backchannel=0
      - ffmpeg:c04#audio=copy
    c06:
      - rtsp://id:pass@192.168.8.16:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c06_sub:
      - rtsp://id:pass@192.168.8.16:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c07:
      - rtsp://id:pass@192.168.8.17:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c07_sub:
      - rtsp://id:pass@192.168.8.17:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c08:
      - rtsp://id:pass@192.168.8.18:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c08_sub:
      - rtsp://id:pass@192.168.8.18:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c09:
      - rtsp://id:pass@192.168.8.19:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c09_sub:
      - rtsp://id:pass@192.168.8.19:554/cam/realmonitor?channel=1&subtype=2#backchannel=0#video=copy#audio=copy#audio=opus
    c10:
      - rtsp://id:pass@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    c10_sub:
      - rtsp://id:pass@192.168.8.20:554/cam/realmonitor?channel=1&subtype=2#backchannel=1#video=copy#audio=copy#audio=opus
```
