### DISCUSSION TITLE
[Support]: Frigate keeps on brining false positives

### DISCUSSION THREAD

**Discussion by aaronjrodrigues** [blakeblackshear/frigate#13512] [General Support]
### Describe the problem you are having

So basically I have around 13 cameras set up in frigate and the feed is pulled using a rtsp stream. Detection is done by the coral detector, however I've noticed that it keeps on detecting trashcans and bags as humans for some reason. I created an object mask for the area that it keeps on bringing false positives but doesn't honour it at all.
It's pretty much driving me crazy, does anyone know why it keeps on sending me notifications even though I've put an object mask? Any help would be appreciated.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Safari 18.1

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

mqtt:
  enabled: true
  host: 192.168.1.114
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    cam1:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/101
    cam2:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/701
    cam3:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/301
    cam4:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/401
    cam5:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/501
    cam6:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/601
    cam7:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/201
    cam8:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/801
    cam9:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/901
    cam10:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/1301
    cam11:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/1101
    cam12:
      - rtsp://admin:password@192.168.1.116:554/Streaming/Channels/1201
    cam13:
      - rtsp://admin:password@192.168.1.137:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif


  webrtc:
    candidates:
      - 192.168.1.114:8555
      - stun:8555

cameras:
  cam1:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/101
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
    objects:
      filters:
        person:
          mask:
            - 0.514,0.26,0.499,0.249,0.489,0.23,0.486,0.208,0.484,0.18,0.485,0.138,0.485,0.124,0.506,0.128,0.505,0.154,0.505,0.182,0.515,0.197,0.521,0.186,0.527,0.201,0.53,0.215,0.539,0.23,0.539,0.246,0.53,0.259
            - 0.436,0.753,0.444,0.71,0.446,0.681,0.462,0.645,0.478,0.632,0.481,0.605,0.496,0.57,0.502,0.552,0.515,0.527,0.53,0.518,0.546,0.527,0.568,0.548,0.576,0.573,0.586,0.594,0.583,0.622,0.579,0.669,0.578,0.714,0.577,0.764,0.577,0.799,0.547,0.824,0.527,0.852,0.495,0.872,0.478,0.87,0.458,0.829,0.444,0.788
            - 0.501,0.911,0.519,0.941,0.53,0.978,0.548,0.992,0.561,0.996,0.591,0.999,0.615,0.986,0.644,0.979,0.645,0.934,0.645,0.853,0.658,0.749,0.643,0.71,0.621,0.665,0.608,0.703,0.588,0.741,0.561,0.771,0.522,0.793,0.507,0.848
  cam2:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/701
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam3:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/301
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
    objects:
      filters:
        person:
          mask: 
            0.58,0.085,0.601,0.079,0.63,0.079,0.641,0,0.682,0.001,0.738,0.003,0.788,0.004,0.809,0.004,0.851,0.029,0.899,0.063,0.954,0.121,0.978,0.134,0.999,0.163,0.996,0.211,0.985,0.311,0.977,0.389,0.956,0.523,0.945,0.583,0.907,0.579,0.874,0.512,0.855,0.462,0.846,0.521,0.834,0.568,0.816,0.57,0.781,0.564,0.764,0.568,0.752,0.592,0.744,0.607,0.762,0.371,0.737,0.326,0.72,0.323,0.708,0.339,0.686,0.323,0.676,0.292,0.659,0.273,0.656,0.25,0.638,0.242,0.623,0.228,0.618,0.195,0.612,0.156,0.603,0.135,0.584,0.134,0.568,0.109
    motion:
      mask: 
        0.566,0.108,0.586,0.077,0.63,0.081,0.662,0.089,0.662,0.065,0.676,0.039,0.685,0.053,0.692,0.089,0.702,0.073,0.713,0.073,0.72,0.096,0.747,0.096,0.778,0.107,0.778,0.146,0.778,0.182,0.773,0.224,0.739,0.225,0.676,0.25,0.615,0.227,0.584,0.178,0.57,0.135
  cam4:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/401
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam5:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/501
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam6:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/601
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
    objects:
      filters:
        person:
          mask: 
            0.804,0.521,0.831,0.535,0.861,0.551,0.887,0.574,0.916,0.6,0.913,0.633,0.895,0.673,0.889,0.703,0.911,0.706,0.943,0.729,0.968,0.743,0.968,0.775,0.956,0.82,0.936,0.829,0.906,0.813,0.878,0.78,0.854,0.742,0.818,0.717,0.798,0.677,0.777,0.647,0.786,0.566
    motion:
      mask: 
        0.889,0.785,0.845,0.745,0.81,0.712,0.791,0.667,0.788,0.651,0.78,0.617,0.78,0.577,0.795,0.542,0.802,0.529,0.84,0.535,0.881,0.568,0.907,0.602,0.91,0.618,0.895,0.673,0.893,0.717,0.914,0.719,0.946,0.734,0.966,0.741,0.965,0.79,0.945,0.813,0.899,0.809
  cam7:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/201
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam8:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/801
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
    objects:
      filters:
        person:
          mask: 
            0.918,0.992,0.909,0.935,0.916,0.879,0.944,0.841,0.979,0.829,0.996,0.839,0.999,0.882,0.999,0.949,0.995,0.982,0.971,0.995
    motion:
      mask: 
        0.908,0.958,0.912,0.902,0.921,0.862,0.956,0.833,0.99,0.836,0.999,0.936,0.991,0.975,0.966,0.996,0.92,0.992
  cam9:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/901
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam10:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/1301
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
    objects:
      filters:
        person:
          mask:
            - 0.269,0.76,0.282,0.734,0.299,0.743,0.316,0.737,0.316,0.711,0.336,0.694,0.357,0.681,0.372,0.678,0.405,0.703,0.415,0.736,0.441,0.711,0.478,0.714,0.491,0.73,0.522,0.77,0.569,0.835,0.602,0.841,0.615,0.87,0.63,0.883,0.643,0.913,0.656,0.944,0.665,0.958,0.684,0.932,0.706,0.926,0.717,0.938,0.739,0.967,0.738,0.991,0.706,0.999,0.637,0.997,0.588,0.995,0.517,0.995,0.46,0.991,0.44,0.995,0.395,0.945,0.358,0.897,0.318,0.849
            - 0.796,0.799,0.789,0.721,0.793,0.672,0.816,0.607,0.836,0.581,0.861,0.566,0.897,0.587,0.927,0.625,0.932,0.686,0.929,0.754,0.891,0.823,0.845,0.842
    motion:
      mask:
        - 0.265,0.755,0.273,0.734,0.295,0.737,0.312,0.733,0.331,0.707,0.356,0.685,0.377,0.686,0.397,0.698,0.405,0.73,0.418,0.743,0.441,0.724,0.469,0.712,0.477,0.729,0.479,0.751,0.507,0.762,0.518,0.775,0.536,0.799,0.56,0.827,0.574,0.836,0.604,0.844,0.611,0.858,0.644,0.879,0.644,0.901,0.648,0.918,0.654,0.943,0.676,0.941,0.694,0.927,0.715,0.936,0.727,0.957,0.727,0.971,0.728,0.996,0.707,0.997,0.682,0.997,0.654,0.997,0.616,0.997,0.559,0.995,0.508,0.995,0.444,0.992,0.417,0.979,0.383,0.923,0.344,0.889,0.32,0.846,0.283,0.776
        - 0.892,0.818,0.852,0.828,0.82,0.822,0.804,0.798,0.803,0.71,0.806,0.655,0.823,0.602,0.866,0.569,0.921,0.604,0.935,0.669,0.935,0.764
  cam11:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/1101
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam12:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.116:554/Streaming/Channels/1201
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 1024
  cam13:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:password@192.168.1.137:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision DS-2CE16D0T

### Screenshots of the Frigate UI's System metrics pages

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/200beedf-8c5e-46c4-a2d4-5a0bd4fdc26f">
