### DISCUSSION TITLE
How to enable two-way audio in 0.14?

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#13522] [Config Support]
I am having trouble finding documentation on how to enable two-way audio, is there a page for it? What I gather from various reddit threads and blog posts is that a microphone icon should appear in the live view if things are setup correctly. It seems to be missing from my icons, is that correct:

![image](https://github.com/user-attachments/assets/c3f23b56-120f-4715-90ae-99e3d18c0753)

The bits to setup, from what I piecemealed, are:

#### webrtc
```yaml
go2rtc:
  webrtc:
    candidates:
      - 10.1.2.10:8555 # is it possible to use a domain here instead of IP?
      - stun:8555
```
#### enable and detect audio in camera config
```yaml
  baby:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/baby
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/baby-sub
          roles:
            - detect
            - audio # detecting
    audio:
      enabled: true  # enabled
```

#### webrtc for good measure
```yaml
    baby:
      - rtsp://{FRIGATE_RTSP_UN}:{FRIGATE_RTSP_PASSWORD}@baby.{FRIGATE_RTSP_DOMAIN}:554/stream1
      - ffmpeg:baby#audio=aac
    baby-sub:
      - rtsp://{FRIGATE_RTSP_UN}:{FRIGATE_RTSP_PASSWORD}@baby.{FRIGATE_RTSP_DOMAIN}:554/stream2
```

Any idea how to debug?
