### DISCUSSION TITLE
[Support]: constant motion detection when there is no motion

### DISCUSSION THREAD

**Discussion by davison** [blakeblackshear/frigate#13536] [General Support] [answered]
### Describe the problem you are having

Since upgrading to 0.14 I see an issue on one (but not both) of my cameras where motion seems to be permanently detected (images are constantly sent to the remote Coral about 4-5 times per second). This behaviour was not apparent in 0.13.x

Typically this happens in infra-red/low-light mode, but can happen during the day or when the scene is well lit. It's clear to the eye that there is no motion in the stream, and in the debug view for the camera, there are no motion boxes visible. Yet the regions and bounding boxes can be seen, and seen to constantly change as new motion is "detected" and the results are received back from Coral. Setting the motion tuning threshold to maximum values has no impact on the behaviour and alerts/detections continue to be generated on a permanent basis. Motion boxes certainly work though; I can reduce the threshold on the motion sensitivity for example and start to see red motion boxes when the level is very low or when real motion occurs in the stream.

It appears that the motion detector just gets stuck in some sort of loop - the only way to stop it from happening is to turn off detect and record on the camera for some time and then re-enable it later. After re-enabling it, the behaviour may or may not start up again.

Any suggestions as to where to start troubleshooting or fixing this?

### Version

0.14.0-da913d8

### What browser(s) are you using?

Brave 1.69.160 Chromium: 128.0.6613.114 (Official Build) (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant
  port: 1883
  user: mqtt
  password: xxx

cameras:
  office:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office_main
          input_args: preset-rtsp-restream
          roles:
            - record

  rear_deck:
    enabled: true
    live:
      stream_name: rear_deck_sub
    audio:
      enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_deck_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear_deck_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    zones:
      deck:
        coordinates: 3169,2160,3328,1241,2185,1132,1616,1695,1303,1625,672,2160
    snapshots:
      required_zones:
        - deck
    motion:
      mask:
        - 0,2160,1087,2160,1423,1835,1292,1205,2121,628,2048,106,3840,168,3840,0,0,0
    objects:
      filters:
        person:
          min_area: 100000

    review:
      alerts:
        required_zones:
          - deck
  front_porch:
    enabled: true
    live:
      stream_name: front_porch_main
    audio:
      enabled: true
    detect:
      enabled: true
      annotation_offset: -200
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    zones:
      driveway:
        inertia: 1
        coordinates: 560,360,417,135,237,0,0,0,0,360
        objects:
          - person
          - cat
      main_gate:
        coordinates: 0.769,0.689,0.669,0.39,0.562,0.279,0.64,0.629
        objects: car
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - driveway
        - main_gate
    motion:
      mask:
        - 1,1,1,0,0.273,0,0.662,0.35,0.748,0.631,0.867,1
        - 0.155,0.053,0.289,0.053,0.289,0.094,0.155,0.094
        - 0.523,1,0.466,1,0.459,0.539,0.498,0.456
      threshold: 40
      contour_area: 15
      improve_contrast: 'false'
    review:
      alerts:
        required_zones:
          - driveway
          - main_gate
go2rtc:
  streams:
    office_main:
      - ffmpeg:device?video=0&video_size=1280x720#video=h264
    front_porch_main:
      - rtsp://viewer:xxx@cctv-dome1:554/live/main
    front_porch_sub:
      - rtsp://viewer:xxx@cctv-dome1:554/live/sub
    rear_deck_main:
      - rtsp://viewer:xxx@cctv-bullet1:554/live/main
    rear_deck_sub:
      - rtsp://viewer:xxx@cctv-bullet1:554/live/sub

detectors:
  deepstack:
    api_url: http://192.168.21.125:32168/v1/vision/detection
    type: deepstack
    api_timeout: 1.0

motion:
  threshold: 30
  lightning_threshold: 0.5
  contour_area: 15

objects:
  track:
    - person
    - car
    - cat
  filters:
    person:
      min_score: 0.4
      threshold: 0.5

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects
      objects:
        person: 30

snapshots:
  enabled: true
  bounding_box: true
  height: 320
  required_zones:
    - driveway
    - main_gate
    - deck
  retain:
    default: 3
    objects:
      person: 15
  quality: 70

version: 0.14
camera_groups: {}
```

### Relevant Frigate log output

```shell
no log output during the abnormal behaviour apart from the occasional read timeout on deepstack (due to Frigate overloading it probably)

Error calling deepstack API: HTTPConnectionPool(host='192.168.21.125', port=32168): Read timed out. (read timeout=1.0)
```

### Relevant go2rtc log output

```shell
no logs generated
```

### FFprobe output from your camera

```shell
root@1fb6a1420833:/opt/frigate# ffprobe rtsp://viewer:xxx@cctv-dome1:554/live/sub
ffprobe version 4.3.7-0+deb11u1+rpt1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt1 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://viewer:xxx@cctv-dome1:554/live/sub':
  Metadata:
    title           : IPCAM
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x360, 11.99 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, stereo, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

H.VIEW 	UK800S6
