### DISCUSSION TITLE
Basic Config Review

### DISCUSSION THREAD

**Discussion by cloudbr34k84** [blakeblackshear/frigate#13535] [General]
Below is my config, im really struggling to understand the new 14.1. Based on the below config im not seeing anything in Alerts, Detections or Motion.  What am i missing pls?

```
mqtt:
  host: xxxxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xx-xxxx
  password: xx
  stats_interval: 60
  enabled: true

version: 0.14

camera_groups: {}
logger:
  default: debug
  logs:
    frigate.event: debug
    frigate.video: debug
    frigate.ffmpeg: debug
    frigate.app: debug
    frigate.mqtt: error
    frigate.object_detection: debug

objects:
  track:
    - person
    - dog
    - car
    - cat
    - motorcycle

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true

model:
  width: 320
  height: 320
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi

go2rtc:
  streams:

    frigate_front_top_camera:
      - rtsp://viewer:x@xxxx:554/h264Preview_01_main
    frigate_front_top_camera_sub:
      - rtsp://viewer:xxx@xx:554/h264Preview_01_sub

cameras:

  frigate_front_top_camera:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:xx@xx:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://viewer:xx@xx:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True 
    record:
      enabled: True
    motion:
      enabled: True

```

**Comment by hawkeye217** [comment]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Upgrade issues question 8.

**Reply by cloudbr34k84** [reply]
I had the below added to the camera? does it need to be a global setting?
record:
  enabled: True

**Reply by cloudbr34k84** [reply]
nothing changed? there are cars and people walking by my house and no motion nothing.. really lost here

**Reply by NickM-27** [reply]
best to check the UI to make sure recordings are enabled, also check the debug live view to see that objects are being detected

**Reply by cloudbr34k84** [reply]
Yep checked
![image](https://github.com/user-attachments/assets/c8a5cec7-f4ff-4110-ad08-16fa48ae3bce)
Yeah under debug im seeing red and green boxes
![image](https://github.com/user-attachments/assets/ebfab30b-c934-4e53-85b3-556e85b1c2d0)

**Reply by NickM-27** [reply]
No objects are detected, this is a pretty limited view, not sure any cars would be detected unless they started moving.

**Reply by cloudbr34k84** [reply]
> No objects are detected, this is a pretty limited view, not sure any cars would be detected unless they started moving.

a car just drove past i wanst quick enough to take the screenshot. In frigate 13 it would contstant record parked cars etc?

**Reply by NickM-27** [reply]
no, 0.13 did not constantly record parked cars, however there would be ongoing events in the UI when a car was parked. But this is not intuitive because a car that is parked is not an event, so 0.14 only shows review items when activity occurs

**Reply by cloudbr34k84** [reply]
so i just had a delivery, right up to my doorbell nothing happened, no alert, no detector no motion?? I can see the little red dot on the feed, but nothing happening
![image](https://github.com/user-attachments/assets/06042937-c887-4af5-a8ca-2b2da5cd301b)
The other camera
![image](https://github.com/user-attachments/assets/5fa67839-ebf4-40f7-b0a3-87153cfba2c3)

**Comment by cloudbr34k84** [comment]
This is my docker-compose running on Synology DSM 7.2.1-69057 Update 5 with 1 google coral
```
version: "3.9"
networks:
  traefik:
    external: true
services:  
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/config
      - /volume3/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs: #hkljljljlkjl
          size: 1000000000
    ports:
      - "5698:5000"
      - "8554:8554" # RTSP feeds
      - "5697:8555/tcp" # WebRTC over tcp
      - "5696:8555/udp" # WebRTC over udp
    environment:
      TZ: Australia/Brisbane
      FRIGATE_RTSP_PASSWORD: "xxxx"
      PLUS_API_KEY: "xxx"
    labels:
      - "homepage.description=Is used as our homes security camera system. Its Integrated into Home Assistant for automations"    
      - "homepage.group=Docker Containers"
      # - "traefik.http.routers.${SVCName}.middlewares=auth@file"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.${SVCName}.loadbalancer.server.port=5000"
    extends:
          file: ../common-services-app.yml
          service: app
```
