### DISCUSSION TITLE
[Config Support]: change go2rtc ffmpeg timeout to 15 seconds

### DISCUSSION THREAD

**Discussion by Unspec7** [blakeblackshear/frigate#13539] [Config Support]
### Describe the problem you are having

Need to change the go2rtc ffmpeg timeout to 15 seconds as the default 5 seconds is way too short.

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false
go2rtc:
  streams:
    ## #video=copy is needed for a single line ffmpeg config when using audio tags, or else video stream is dropped
    doorway:
      - ffmpeg:rtsp://redacted:redacted@192.168.XX.XX:88/videoMain#hardware#timeout=15  **##Note: #timeout=15 doesn't do anything**
      #- ffmpeg:doorway#audio=aac#audio=volume#hardware
      - ffmpeg:doorway#audio=opus#audio=volume#hardware

  ## THIS INCREASES VOL AND PREVENTS THE AUDIO COMING OUT FROM THE CAMERA SOUNDING MUFFLED
  ## Source https://www.youtube.com/watch?v=upXyBVMR4RM
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
    myinput: "-timeout 15000000" **## This doesn't do anything either**
  webrtc:
    candidates:
      - 192.168.XX.XX:8555
      - stun:8555
cameras:
  doorway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorway?timeout=15
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
            # - rtmp
    onvif:
      host: 192.168.XX.XX
      port: 888
      user: redacted
      password: redacted
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 5
      enabled: false
  #test:
  #  ffmpeg:
  #    inputs:
  #      - path: /media/frigate/person-bicycle-car-detection.mp4
  #        input_args: -re -stream_loop -1 -fflags +genpts
  #        roles:
  #          - detect
  #          - rtmp
  #  detect:
  #    height: 1080
  #    width: 1920
  #    fps: 5

ffmpeg:
  hwaccel_args: preset-vaapi
  #retry_interval: 10

detectors:
  ov:
    type: openvino
    #device: AUTO
    device: CPU
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

CPU (no coral)
