### DISCUSSION TITLE
[Config Support]: non alert events do not have clips in home assistant media browser

### DISCUSSION THREAD

**Discussion by ivanjx** [blakeblackshear/frigate#13538] [Config Support] [answered]
### Describe the problem you are having

when i am trying to check the clips folder in media browser, it only has the zone `inside` mainly while i get both `inside` and `outside` on the snapshots folder.

clips count:
![image](https://github.com/user-attachments/assets/aea55b8e-b4d0-4fb1-9d76-9e87b455b719)

snapshots count:
![image](https://github.com/user-attachments/assets/1110f3ca-f7fa-4518-baa8-cf32e5c765bc)

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  host: home-assistant-mq
  user: hass
  password: '12345678'

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# model:
#   model_type: yolonas
#   width: 256
#   height: 256
#   input_tensor: nchw
#   input_pixel_format: bgr
#   path: /models/yolo_nas_sp.onnx
#   labelmap_path: /labelmap/coco-80.txt

go2rtc:
  ffmpeg:
    cam: -rtsp_transport tcp -i {input}
  streams:
    cam1:
      - ffmpeg:rtsp://192.168.20.21/stream1#input=cam#video=copy#audio=aac
    cam2:
      - ffmpeg:rtsp://192.168.20.22/stream1#input=cam#video=copy#audio=aac
    cam3:
      - ffmpeg:rtsp://192.168.20.23/stream1#input=cam#video=copy#audio=aac

ffmpeg:
  hwaccel_args: ' '
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-rtsp-restream

objects:
  filters:
    person:
      min_score: 0.1
      threshold: 0.5
    cat:
      min_score: 0.1
      threshold: 0.5
    dog:
      min_score: 0.1
      threshold: 0.5
  track:
    - person
    - cat
    - dog

detect:
  min_initialized: 1
  fps: 5

review:
  alerts:
    labels:
      - person
      - cat
      - dog
    required_zones:
      - inside

record:
  enabled: true
  expire_interval: 5
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 7
      mode: all

snapshots:
  enabled: true
  timestamp: true
  crop: true
  bounding_box: true
  clean_copy: false
  quality: 100
  retain:
    default: 7

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - record
            - detect
    detect:
      fps: 7
    motion:
      mask:
        - 0,0.047,0.297,0.043,0.297,0,0,0
        - 0.116,0,0.125,0.161,0.414,0.024,0.413,0
      improve_contrast: 'true'
      threshold: 30
      contour_area: 5
    zones:
      inside:
        coordinates: 0,0.668,0.518,0.221,0.519,0,1,0,1,1,0,1
        inertia: 1
        loitering_time: 0
      outside:
        coordinates: 0.002,0,0,0.661,0.514,0.219,0.515,0
        inertia: 1
        loitering_time: 0
    objects:
      mask:
        - 0.231,0.285,0.269,0.47,0.369,0.379,0.349,0.206
        - 0.109,0.379,0.194,0.317,0.221,0.512,0.147,0.589
        - 0.115,0,0.123,0.159,0.413,0.021,0.413,0
  cam2:
    onvif:
      host: 192.168.20.22
      port: 2020
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2
          roles:
            - record
            - detect
    motion:
      mask: 0,0,0.336,0,0.336,0.07,0,0.072
      improve_contrast: 'true'
      threshold: 20
      contour_area: 5
    zones:
      inside:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 1
    objects:
      filters:
        person:
          mask: 
            0.536,0.167,0.527,0.212,0.516,0.269,0.51,0.314,0.511,0.34,0.513,0.369,0.514,0.431,0.514,0.463,0.514,0.489,0.511,0.52,0.513,0.54,0.514,0.578,0.52,0.633,0.533,0.676,0.558,0.702,0.59,0.693,0.614,0.663,0.626,0.574,0.63,0.529,0.63,0.457,0.617,0.354,0.604,0.265,0.595,0.18,0.558,0.137
      mask: 0.547,0.475,0.663,0.182,0.836,1,0.572,1
  cam3:
    onvif:
      host: 192.168.20.23
      port: 2020
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3
          roles:
            - record
            - detect
    motion:
      improve_contrast: 'true'
      threshold: 30
      contour_area: 10
      mask:
        - 0,0,0.325,0,0.324,0.06,0,0.064
        - 1,0,1,0.389,0.753,0.302,0.702,0.38,0.57,0.33,0.563,0.407,0.474,0.369,0.474,0
    zones:
      inside:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 1
version: 0.14
```

### Relevant Frigate log output

```shell
no errors
```

### Relevant go2rtc log output

```shell
no errors
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

**Comment by NickM-27** [comment, marked as answer]
this is working as expected because in 0.14 the required_zones fields are used to fill in for the previous required_zones field in recordings, since in 0.13 detections did not exist. 

In 0.15 this is fixed with an explicit config for recording alerts and detections

**Reply by ivanjx** [reply]
so the new config is available on the latest dev branch? may i know the new config for it? thanks

**Reply by NickM-27** [reply]
yes

```
record:
  alerts:
    retain:
      days: X
  detections:
    retain:
      days:  Y
```

**Reply by ivanjx** [reply]
will clips duplicate the video files on the disk?

**Reply by ivanjx** [reply]
also i think the pre and post capture settings are ignored in detections:
```yaml
record:
  enabled: true
  expire_interval: 5
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 7
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 3
    pre_capture: 15
    post_capture: 15
```
