### DISCUSSION TITLE
[Config Support]: More Reolink 2-Way Audio Issues

### DISCUSSION THREAD

**Discussion by duckdude555** [blakeblackshear/frigate#13532] [Config Support] [answered]
### Describe the problem you are having

I've been trying this for months, even RMA'ing my doorbell - I have no idea what else I can try. I am not able to use the mic on my computer/device, and I do not see the icon for it in Frigate (I do see the speaker icon which works fine). 

I have tried following this thread closely: https://github.com/blakeblackshear/frigate/discussions/13418 , but the solution has not worked for me. I have been focusing mainly on Frigate, because I am assuming (hopefully correctly) that if the mic won't work on Frigate, it likely won't inHome Assistant/Lovelace card too. 

Reolink WiFi Video Doorbell, firmware V3.0.0.3215_2401262240, hardware DB_566128M5MP_W. This is "front_door"

Thank you!!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.69.12
  port: 1883
  user: frigatemqtt
  password: josephrocks
  topic_prefix: frigate
  client_id: frigate

#detectors:
#  cpu:
#    type: cpu
#    num_threads: 8


#birdseye:
#  restream: true
go2rtc:
  streams:
    front_door:
      #- ffmpeg:https://192.168.10.5/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=joseph&password=PASSWORD#video=copy#audio=copy#audio=opus
      - "ffmpeg:http://192.168.10.5/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=joseph&password=PASSWORD#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.10.5/Preview_01_sub
      
    front_door_sub:
      - "ffmpeg:http://192.168.10.5/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=joseph&password=PASSWORD"
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
  #ui:
   # live_mode: webrtc
  webrtc:
    candidates:
      - 192.168.69.40:8555
      - stun:8555



cameras:
  front_door:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: preset-record-generic-audio-copy

      inputs:
        #high res
        - path: rtsp://127.0.0.1:8554/front_door #?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio

      #low res
        - path: rtsp://127.0.0.1:8554/front_door_sub #?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - car
        - dog

      filters:
        car:
          threshold: 0.6
          min_score: 0.6
          mask: 
            0.804,0.677,0.99,0.737,0.991,1,0,0.997,0,0,1,0,0.991,0.541,0.51,0.51,0.442,0.534,0.719,0.594,0.279,0.559,0.286,0.664,0.525,0.655
        dog:
          mask: 0.988,0.523,0.276,0.519,0.335,0.99,0.007,0.99,0,0.003,0.999,0.003
        person:
          min_score: 0.6 # min score for object to initiate tracking (default: 0.5
          threshold: 0.7 # 
          mask: 
            0.992,0.528,0.754,0.535,0.714,0.578,0.555,0.582,0.487,0.498,0.274,0.502,0.34,1,0.008,0.999,0.004,0.008,1,0.011,1,0.543,0.394,0.487
    motion:
      mask: 
        0.011,0,0.999,0,1,0.502,0.746,0.54,0.661,0.567,0.557,0.574,0.512,0.51,0.296,0.51,0.294,0.596,0.322,0.877,0.344,0.99,0.009,0.985
      threshold: 50
      contour_area: 30
      improve_contrast: 'true'
    zones:
      On_Street:
        coordinates: 0.993,0.721,0.797,0.641,0.697,0.569,0.466,0.53,0.574,0.511,1,0.521
      On_Property:
        coordinates: 0.975,0.981,0.501,0.65,0.809,0.643,0.997,0.724
      On_Property_2:
        coordinates: 0.727,0.606,0.313,0.59,0.297,0.532,0.614,0.546,0.715,0.576
      Driveway_and_Front_Step:
        coordinates: 0.791,0.645,0.497,0.652,0.966,0.988,0.322,0.995,0.245,0.559,0.725,0.586
        inertia: 3
    review:
      alerts:
        required_zones: Driveway_and_Front_Step
      detections:
        required_zones:
          - On_Street
          - On_Property_2
          - On_Property
          - Driveway_and_Front_Step
    onvif:
      host: 192.168.10.5
      user: joseph
      password: PASSWORD


  garage:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        #high res
        - path: rtsp://admin:PASSWORD@192.168.69.41/Preview_01_main
          roles:
            - record
      #low res
        - path: rtsp://admin:PASSWORD@192.168.69.41/Preview_01_sub
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 1536
      height: 576
      fps: 7
    objects:
      track:
        - person
        - car
        - dog

      filters:
        car:
          threshold: 0.7
          min_score: 0.7
          mask: 
            0.521,0.261,0.418,0.343,0.39,0.456,0.65,0.471,0.844,1,0.227,0.989,0.002,0.995,0.001,0.008,0.994,0.013,0.995,0.992,0.833,0.997,0.713,0.697,0.617,0.399,0.612,0.346,0.637,0.33,0.53,0.231
        person:
          threshold: 0.7
          min_score: 0.7
          mask: 
            0.078,0.899,0.221,0.729,0.234,0.583,0.23,0.514,0.248,0.416,0.315,0.308,0.41,0.261,0.499,0.221,0.525,0.253,0.626,0.326,0.613,0.372,0.655,0.504,0.734,0.528,0.739,0.424,0.829,0.481,0.89,0.567,0.853,0.744,0.737,0.743,0.852,0.98,0.998,0.982,1,0.008,0.008,0,0.008,0.652,0.051,0.796
        dog:
          threshold: 0.6
          min_score: 0.6
          mask: 
            0.002,0.008,0.992,0.013,0.994,0.997,0.835,0.822,0.894,0.569,0.828,0.479,0.495,0.207,0.391,0.194,0.282,0.237,0.242,0.255,0.073,0.529,0.004,0.524
    motion:

      improve_contrast: 'true'
      mask: 
        0.236,0.263,0.33,0.218,0.394,0.199,0.449,0.197,0.502,0.213,0.629,0.319,0.693,0.237,1,0.745,0.995,0.011,0.003,0.005,0.001,0.548,0.091,0.612,0.151,0.572,0.221,0.524,0.243,0.444
      threshold: 50
      contour_area: 23
    zones:
      In_Driveway:
        coordinates: 
          0.22,0.976,0.077,1,0.069,0.814,0.194,0.654,0.279,0.559,0.398,0.396,0.523,0.239,0.633,0.332,0.825,0.479,0.893,0.59,0.829,0.851,0.898,1
        objects:
          - dog
          - person
        inertia: 3
      In_Driveway_car:
        coordinates: 0.395,0.458,0.64,0.464,0.637,0.329,0.532,0.236,0.422,0.349
        objects: car
        inertia: 3
    review:
      alerts:
        required_zones: In_Driveway

  backyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        #high res
        - path: rtsp://admin:PASSWORD@192.168.69.43/Preview_01_main
          roles:
            - record
      #low res
        - path: rtsp://admin:PASSWORD@192.168.69.43/Preview_01_sub
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 896
      height: 512
      fps: 7
    objects:
      track:
        - person
        - car
        - dog

    motion:

      improve_contrast: 'true'
    onvif:
      host: 192.168.69.43
      user: admin
      password:PASSWORD




version: 0.14
```

### Relevant Frigate log output

```shell
Nothing relevant
```

### Relevant go2rtc log output

```shell
2024-09-03 18:21:15.149791836  [INFO] Preparing new go2rtc config...
2024-09-03 18:21:15.407306469  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-09-03 18:21:15.436341084  [INFO] Starting go2rtc...
2024-09-03 18:21:15.561700331  18:21:15.561 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-03 18:21:15.561703938  18:21:15.561 INF config path=/dev/shm/go2rtc.yaml
2024-09-03 18:21:15.562081619  18:21:15.562 INF [rtsp] listen addr=:8554
2024-09-03 18:21:15.562155959  18:21:15.562 INF [api] listen addr=:1984
2024-09-03 18:21:15.562345175  18:21:15.562 INF [webrtc] listen addr=:8555
2024-09-03 18:21:25.144956819  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":562,"detection_enabled":true,"detection_fps":5.7,"ffmpeg_pid":578,"pid":544,"process_fps":7.0,"skipped_fps":0.0},"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":550,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":554,"pid":535,"process_fps":7.1,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.2,"capture_pid":553,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":581,"pid":541,"process_fps":7.2,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"2.3","cpu_average":"3","mem":"2.1"},"123":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"170":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"171":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"172":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"173":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"174":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2556":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2683":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"307":{"cmdline":"bash ./run.user certsync","cpu":"0.1","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"361":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.7"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"490":{"cmdline":"frigate.recording_manager","cpu":"1.7","cpu_average":"0","mem":"1.1"},"492":{"cmdline":"frigate.review_segment_manager","cpu":"0.4","cpu_average":"0","mem":"0.9"},"518":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)","cpu":"0.2","cpu_average":"0","mem":"0.1"},"519":{"cmdline":"frigate.detector.cpu ","cpu":"124.9","cpu_average":"159","mem":"1.0"},"521":{"cmdline":"frigate.output       ","cpu":"2.4","cpu_average":"2","mem":"1.0"},"535":{"cmdline":"frigate.process:front_door","cpu":"2.0","cpu_average":"1","mem":"1.0"},"541":{"cmdline":"frigate.process:garage","cpu":"1.8","cpu_average":"2","mem":"1.0"},"544":{"cmdline":"frigate.process:backyard","cpu":"9.4","cpu_average":"10","mem":"1.0"},"550":{"cmdline":"frigate.capture:front_door","cpu":"0.9","cpu_average":"0","mem":"0.9"},"553":{"cmdline":"frigate.capture:garage","cpu":"2.1","cpu_average":"1","mem":"0.9"},"554":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_door_sub -r 7 -vf fps=7,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"4","mem":"0.6"},"562":{"cmdline":"frigate.capture:backyard","cpu":"1.2","cpu_average":"0","mem":"0.9"},"570":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.10.5/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/f55fb8c5fee2254966bdfde3d24ae564","cpu":"0.4","cpu_average":"0","mem":"0.2"},"578":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.69.43/Preview_01_sub -r 7 -vf fps=7,scale=896:512 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.4","cpu_average":"1","mem":"0.6"},"581":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.69.41/Preview_01_sub -r 7 -vf fps=7,scale=1536:576 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.6","cpu_average":"2","mem":"0.7"},"582":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.69.43/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"0","mem":"0.2"},"587":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.2"},"590":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.69.41/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.2"},"591":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.10.5/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1aa589ee418e7c87722083963ca010ca","cpu":"1.7","cpu_average":"1","mem":"0.2"},"592":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"606":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1536x576 -i pipe: -threads 1 -f mpegts -s 1920x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"611":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"616":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.9","cpu_average":"1","mem":"0.2"},"frigate.full_system":{"cpu":"15.6","mem":"47.8"}},"detection_fps":5.8,"detectors":{"cpu":{"detection_start":1725402378.307875,"inference_speed":65.6,"pid":519}},"gpu_usages":{"intel-vaapi":{"gpu":"1.0%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":361},"recording":{"pid":490},"review_segment":{"pid":492}},"service":{"last_updated":1725402379,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":59.8,"mount_type":"tmpfs","total":64.0,"used":4.2},"/media/frigate/clips":{"free":1516631.4,"mount_type":"ext4","total":3754317.8,"used":2237670.4},"/media/frigate/recordings":{"free":1516631.4,"mount_type":"ext4","total":3754317.8,"used":2237670.4},"/tmp/cache":{"free":919.3,"mount_type":"tmpfs","total":953.7,"used":34.3}},"temperatures":{},"uptime":301,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Any other information that may be helpful

/api/go2rtc/streams/front_door while audio is playing:

`{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:50192","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n","send":185798599,"senders":["96 H264, bytes=182357434, receivers=1","97 MPEG4-GENERIC/16000, bytes=1368861, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/front_door","user_agent":"FFmpeg Frigate/0.14.1-f4f3cfa"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"192.168.69.150, 127.0.0.1:44596","senders":["96 H264, bytes=0, receivers=1","97 MPEG4-GENERIC/16000, bytes=0, receivers=1"],"type":"MSE/WebSocket active consumer","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"},{"medias":["video, sendonly, ALL","audio, sendonly, ALL","audio, recvonly, ANY"],"remote_addr":"127.0.0.1:44582","senders":["96 H264, bytes=0, receivers=1","97 MPEG4-GENERIC/16000, bytes=0, receivers=1","98 OPUS/48000/2, bytes=0, receivers=1"],"type":"probe","user_agent":"python-requests/2.32.3"}],"producers":[{"medias":["video, recvonly, H.264 High 5.1","audio, recvonly, MPEG4-GENERIC/16000","audio, recvonly, OPUS/48000/2"],"receivers":["96 H264, bytes=182357434, senders=3","97 MPEG4-GENERIC/16000, bytes=1368861, senders=3","98 OPUS/48000/2, bytes=3202401, senders=1"],"recv":188697964,"remote_addr":"127.0.0.1:42288","sdp":"v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n","type":"RTSP passive producer","url":"rtsp://127.0.0.1:8554/1aa589ee418e7c87722083963ca010ca","user_agent":"ffmpeg/go2rtc"},{"url":"rtsp://192.168.10.5/Preview_01_sub"}]}`

**Comment by NickM-27** [comment]
Open the network tools for browser and check the response for the probe request

**Reply by duckdude555** [reply]
I'm sorry but  am not exactly sure what you mean... on my Safari Web Inspector, I see the front_door response but it's the same as what I posted above.  

In the other thread I linked - @hawkeye217 mentioned something about needing to see send only and recvonly in medias under the producers. I only have recvonly - could this be causing my issues?

**Reply by NickM-27** [reply]
it's most likely to be a bit different, best to copy and paste from the web inspector

**Reply by duckdude555** [reply]
Fair enough! Here it is (front_door with the audio playing): 

```
{
    "consumers": [
        {
            "medias": [
                "video, sendonly, H264, H265",
                "audio, sendonly, MPEG4-GENERIC"
            ],
            "remote_addr": "127.0.0.1:50192",
            "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
            "send": 2654547032,
            "senders": [
                "96 H264, bytes=2605505608, receivers=1",
                "97 MPEG4-GENERIC/16000, bytes=19498560, receivers=1"
            ],
            "type": "RTSP passive consumer",
            "url": "rtsp://127.0.0.1:8554/front_door",
            "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa"
        },
        {
            "medias": [
                "video, sendonly, ALL",
                "audio, sendonly, ALL",
                "audio, recvonly, ANY"
            ],
            "remote_addr": "127.0.0.1:53238",
            "senders": [
                "96 H264, bytes=0, receivers=1",
                "97 MPEG4-GENERIC/16000, bytes=0, receivers=1",
                "98 OPUS/48000/2, bytes=0, receivers=1"
            ],
            "type": "probe",
            "user_agent": "python-requests/2.32.3"
        }
    ],
    "producers": [
        {
            "medias": [
                "video, recvonly, H.264 High 5.1",
                "audio, recvonly, MPEG4-GENERIC/16000",
                "audio, recvonly, OPUS/48000/2"
            ],
            "receivers": [
                "96 H264, bytes=2605505608, senders=2",
                "97 MPEG4-GENERIC/16000, bytes=19498560, senders=2",
                "98 OPUS/48000/2, bytes=42102195, senders=1"
            ],
            "recv": 2692324707,
            "remote_addr": "127.0.0.1:42288",
            "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
            "type": "RTSP passive producer",
            "url": "rtsp://127.0.0.1:8554/1aa589ee418e7c87722083963ca010ca",
            "user_agent": "ffmpeg/go2rtc"
        },
        {
            "url": "rtsp://192.168.10.5/Preview_01_sub"
        }
    ]
}
```

**Reply by NickM-27** [reply]
it's not opening the preview for some reason

**Reply by duckdude555** [reply]
Interesting... how can I troubleshoot that?

**Reply by NickM-27** [reply]
it would be a go2rtc issue, I recall someone else had a similar issue but I can't find where they posted it on the go2rtc repo

**Reply by duckdude555** [reply, marked as answer]
Update: Solved. Updated my config per @peetipablo's suggestion in another thread:

```
go2rtc:
  webrtc:
    listen: :8555
    candidates:
      - <frigate-ip>:8555
      - stun:8555
  streams:
    birdseye:
      - rtsp://localhost:8554
    doorbell:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@<doorbell-ip>:554/
      - ffmpeg:http://<doorbell-ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#audio=opus#audio=volume
    doorbell_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@<doorbell-ip>:554/h264Preview_01_sub
      - ffmpeg:http://<doorbell-ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#audio=opus#audio=volume
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"
```
