### DISCUSSION TITLE
[Camera Support]: Doorbird Audio only on Live Stream, no sound on recordings

### DISCUSSION THREAD

**Discussion by kobelka** [blakeblackshear/frigate#13545] [Camera Support] [answered]
### Describe the problem you are having

Hi,
my doorbird (haustuercam) generally works, but I have no sound on recordings (only on the Livestream) 
On my other cameras i have also sound on recordings.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# Frigate Configuration file
# Defaults: https://docs.frigate.video/configuration/#full-configuration-reference

# MQTT needed for Smart Home Applications 
mqtt:
  host: 10.11.1.236 # <---- same mqtt broker that home assistant uses
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
#ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
#  live_mode: webrtc
detectors:
  coral:
    type: edgetpu
    #device: pci
# Hardware acceleration of video conversion
ffmpeg:
  # global hwaccel args
  hwaccel_args: preset-vaapi
  #hwaccel_args: preset-intel-qsv-h265


database:
  path: /config/frigate.db

# Overview of all cameras https://frigate.video/images/birdseye-2-optimized.jpg
birdseye:
  enabled: true
  mode: objects
  restream: true

# Snapshots of events
snapshots:
  # Enable writing jpg snapshot to /media/frigate/clips
  enabled: true
  # print a timestamp on the snapshots
  timestamp: true

# List of objects to capture https://docs.frigate.video/configuration/objects/
objects:
  track:
    - car
    - person
    - cat
    - dog
    - bicycle
    - eye glasses
    - backpack
    - handbag

go2rtc:
  log:
    exec: trace
  ffmpeg:
    input_mulaw: -f mulaw -ar 8000 -i {input}
    noise_filter: -af highpass=200,lowpass=3000,afftdn
  streams:
    carportcam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.70:88/videoMain
      - ffmpeg:carportcam#audio=aac
    carportcam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.70:88/videoSub # <- stream which supports video & aac audio.
      - ffmpeg:carportcam_sub#audio=aac   # <- copy of the stream which transcodes audio to opus for webrtc 
    haustuercam:
      - rtsp://{FRIGATE_DOORBIRD_USER}:{FRIGATE_DOORBIRD_PASSWORD}@10.11.1.71/mpeg/media.amp#media=video
      - ffmpeg:http://{FRIGATE_DOORBIRD_USER}:{FRIGATE_DOORBIRD_PASSWORD}@10.11.1.71/bha-api/bha-api/audio-receive.cgi#media=audio#backchannel=0#input=input_mulaw#audio=opus#audio=noise_filter
    hausseitecam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.72:88/videoMain
      - ffmpeg:hausseitecam#audio=aac
    hausseitecam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.72:88/videoSub # <- stream which supports video & aac audio.
      - ffmpeg:hausseitecam_sub#audio=aac
    werkstattcam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.76/stream1
      - ffmpeg:werkstattcam#audio=aac
    werkstattcam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.76/stream1 # <- stream which supports video & aac audio.
      - ffmpeg:werkstattcam_sub#audio=aac   # <- copy of the stream which transcodes audio to opus for webrtc        
    terrassecam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.75:88/videoMain
      - ffmpeg:hausseitecam_sub#audio=aac
    terrassecam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.75:88/videoSub # <- stream which supports video & aac audio.
      - ffmpeg:hausseitecam_sub#audio=aac
    babycam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.77/live0
      - ffmpeg:babycam#audio=opus
    babycam_onvif:
      - onvif://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.77
    babycam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.77/live0 # <- stream which supports video & aac audio.
      - ffmpeg:babycam_sub#audio=opus   # <- copy of the stream which transcodes audio to opus for webrtc              
    gartencam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.73:554/cam/realmonitor?channel=1&subtype=0
      #- ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.73:554/cam/realmonitor?channel=1&subtype=0
      #- ffmpeg:gartencam#video=h264#audio=aac
    gartencam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.73:554/cam/realmonitor?channel=1&subtype=2
      #- ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.73:554/cam/realmonitor?channel=1&subtype=1
      #- ffmpeg:gartencam_sub#video=h264#audio=aac
    webrtc:
    candidates:
      - 10.11.1.3:8555
      - stun:8555
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

# List of cameras
cameras:
  carportcam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/carportcam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/carportcam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: carportcam_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      required_zones:
        - pforte
        - auffahrt
        - komplett
    zones: {}
    motion:
      mask:
        - 1,0,0.731,0,0.726,0.089,0.851,0.144,1,0.218
        - 0.241,0.389,0.107,0.686,0.085,1,0,1,0,0.486,0.074,0.295,0.21,0.229,0.198,0,0.416,0,0.486,0,0.513,0.049,0.465,0.117,0.305,0.159,0.311,0.267,0.435,0.256,0.431,0.371
        - 0.157,0.026,0.157,0,0,0.002,0,0.028
      threshold: 36
      contour_area: 10
      improve_contrast: 'true'
    objects:
      filters:
        person:
          mask: 487,143,521,138,519,63,486,68
        car:
          mask:
            - 0.308,0.248,0.392,0.246,0.398,0.332,0.311,0.334
            - 0.404,0.047,0.406,0.194,0.644,0.182,0.641,0.052
            - 0.785,0.078,0.791,0.034,1,0.098,0.998,0.184
            - 0.594,0.692,0.998,0.697,1,1,0.591,1

#    review:
#      alerts:
#        required_zones:
#          - pforte
#          - auffahrt
#          - komplett
    review:
      alerts: {}
  haustuercam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://10.11.1.3:8554/haustuercam?video=all&audio=all
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones: {}
    snapshots:
      required_zones:
        - komplett
    live:
      stream_name: haustuercam
    detect:
      width: 1280
      height: 720
      fps: 5

    review: {}
    objects:
      filters:
        car:
          mask: 0.058,0.215,0.326,0.212,0.335,0.712,0.049,0.686
    motion:
      mask: 
        0.055,0.446,0.997,0.419,1,0.619,0.961,0.684,0.784,0.787,0.664,0.837,0.426,0.868,0.225,0.821,0.102,0.792,0.06,0.712
  hausseitecam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/hausseitecam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/hausseitecam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: hausseitecam_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0.772,1,1,1,1,0.814,0.984,0.597,0.721,0.187,0.78,0.205,0.784,0.13,0.79,0,0.731,0,0.601,0,0.559,0.171,0.667,0.583,0.629,0.653,0.63,0.775,0.675,0.847,0.717,0.85
        - 0.159,0,0.158,0.033,0,0.033,0,0
        - 0.423,0.534,0.554,0.547,0.579,0.8,0.416,0.769
      threshold: 36
      contour_area: 19
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask: 0.588,0,0.795,0,0.806,0.255,0.595,0.202
  werkstattcam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/werkstattcam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/werkstattcam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: werkstattcam_sub
    snapshots:
      required_zones:
        - autowerkstatt
        - komplett
    zones:
      autowerkstatt:
        coordinates: 609,94,612,0,909,0,928,80,911,289,0,202,91,96
        objects:
          - car
    motion:
      mask:
        - 0.264,0.329,0,0.864,0,0.131,0.216,0
        - 0.32,0.047,0.318,0,0,0,0,0.044
        - 0.566,0,0.557,0.109,0.635,0.122,0.663,0.147,0.667,0.06,0.641,0.007
    review:
      alerts:
        required_zones: autowerkstatt
    objects:
      mask: 0.467,0,0.471,0.104,0.256,0.103,0.255,0.005
      filters:
        car:
          mask:
            - 0.467,0,0.471,0.104,0.256,0.103,0.255,0.005
            - 0.684,0.997,0.643,0.299,0.225,0.272,0,1
            - 0.467,0,0.471,0.104,0.256,0.103,0.255,0.005
            - 0.219,0,0.271,0.335,0,0.868,0,0.119
            - 0.467,0,0.471,0.104,0.256,0.103,0.255,0.005
            - 0.467,0,0.471,0.104,0.256,0.103,0.255,0.005
  terrassecam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/terrassecam?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/terrassecam_sub?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0.264,0.329,0,0.864,0,0.131,0.216,0
        - 0,0.044,0.236,0.042,0.237,0,0,0.002
    record:
      events:
        objects:
          - person
          - cat
          - dog
          - bicycle
          - eye glasses
          - backpack
          - handbag
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: terrassecam_sub
    objects:
      filters:
        handbag:
          threshold: 0.8
        person:
          threshold: 0.76
  gartencam:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.1.3:8554/gartencam?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.11.1.3:8554/gartencam_sub?video&audio
       # input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0.184,0.55,0.143,0.743,0.093,1,0,1,0,0.131,0,0,0.279,0
        - 0.564,0,1,0,1,0.333,0.577,0.194
    snapshots:
      required_zones:
        - komplett
    zones: {}
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: gartencam_sub
    objects:
      filters:
        handbag:
          threshold: 0.8
        person:
          threshold: 0.76

        car:
          mask: 0.226,0.114,0.39,0.145,0.394,0.293,0.202,0.272
    review:
      alerts: {}
version: 0.14
camera_groups:
  Home:
    order: 2
    icon: LuHome
    cameras:
      - carportcam
      - gartencam
      - hausseitecam
      - haustuercam
      - terrassecam
      - werkstattcam
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
--
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Doorbird

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/21ad2884-f647-4fcb-8a1b-4b3c9ff34aca)
