### DISCUSSION TITLE
[Support]: Events/Timeline Very Slow to Load

### DISCUSSION THREAD

**Discussion by spikked27** [blakeblackshear/frigate#13549] [General Support]
### Describe the problem you are having

When opening the events page either on mobile or desktop (on local ethernet) the clips are very slow to load, the same is true while scrubbing the timeline, frigate is running on a computer with a core i9-9900k, ample RAM and an NVIDIA GPU, all recordings are kept on a single 4TB hard drive that's constantly spinning so it's not a wake up issue.  Anyone else experiencing this?

### Version

0.14.1

### What browser(s) are you using?

Chrome Mobile/Desktop

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxxxxx
  port: xxxx
  user: xxxx
  password: xxxxxx
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

tls:
  enabled: false

logger:
  default: debug
  logs:
    frigate.ffmpeg.front_door: error

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    front_door:
      - ffmpeg:http://xxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxxxx#video=copy#audio=copy#audio=opus
      #- exec:./neolink/neolink_talk.sh#backchannel=1
      - rtsp://xxxxx:xxxxx@xxxxx:554/h264Preview_01_sub
    front_door_sub:
      - ffmpeg:http://xxxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxx
    front_door_snapshot:
      - onvif://xxxxx:xxxxx@xxxxxx:8000?subtype=000&snapshot
#    driveway_main:
#      - "https://xxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxxx#video=copy#audio=copy#audio=opus"
#      - rtsp://xxxxx:xxxxx@xxxxx:554/h264Preview_01_main  
#    driveway_sub:
#      - "https://xxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxxx"
#      - rtsp://xxxxx:xxxxx@xxxxx:554/h264Preview_01_sub
    webrtc:
    candidates:
      - xxxxxx:8555
      - stun:8555

cameras:
  front_door:
    ffmpeg:
 #     hwaccel_args: 
 #       - c:v hevc_cuvid
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_door

    motion:
      threshold: 30
      contour_area: 94
      improve_contrast: True
      mask: 
        0.974,0.497,0.973,0.478,0.975,0.4,0.936,0.171,0.874,0,0.052,0,0,0,0,0.314,0.054,0.351,0.058,0.553,0,0.545,0,0.625,0.133,0.649,0.395,0.647,0.581,0.626,0.749,0.582,0.845,0.585,0.887,0.591,0.914,0.595,0.933,0.594,0.943,0.595,0.967,0.594,0.967,0.584,0.967,0.575,0.971,0.555,0.973,0.54,0.971,0.519
    
    objects:
      filters:
        car:
          mask: 
            0.001,0.515,0.077,0.531,0.136,0.485,0.198,0.485,0.263,0.498,0.357,0.51,0.44,0.5,0.482,0.489,0.495,0.42,0.521,0.426,0.694,0.463,0.705,0.491,0.773,0.494,0.816,0.469,0.856,0.472,0.839,0.523,0.97,0.531,0.962,0.602,0.748,0.58,0.654,0.624,0.539,0.648,0.414,0.665,0.313,0.668,0.175,0.67,0.053,0.664,0,0.663
        person:
          mask: 
            0.001,0.515,0.077,0.531,0.136,0.485,0.198,0.485,0.213,0.537,0.42,0.534,0.504,0.529,0.482,0.489,0.486,0.456,0.694,0.463,0.705,0.491,0.773,0.494,0.816,0.469,0.856,0.472,0.839,0.523,0.97,0.531,0.962,0.602,0.748,0.58,0.65,0.609,0.535,0.631,0.41,0.645,0.312,0.65,0.175,0.653,0.048,0.64,0,0.663
    
    zones:
      Stoop:
        coordinates: 0.217,0.998,0.239,0.724,0.604,0.707,0.716,0.809,0.898,0.89,0.999,0.998
      Front_of_House:
        coordinates: 
          0.049,0.645,0.396,0.649,0.603,0.624,0.71,0.591,0.747,0.583,0.962,0.605,1,0.61,0.998,0.813,0.733,0.772,0.629,0.687,0.223,0.711,0.185,0.999,0,1,0,0.631
    
    review:
      alerts:
        required_zones: Stoop

 # driveway:
 #   ffmpeg:
 #     output_args:
 #       record: preset-record-generic-audio-copy
 #     inputs:
 #       - path: rtsp://127.0.0.1:8554/driveway_sub
 #         input_args: preset-rtsp-restream
 #         roles:
 #           - detect
 #       - path: rtsp://127.0.0.1:8554/driveway_main
 #         input_args: preset-rtsp-restream
 #         roles:
 #           - record
 #   live:
 #       stream_name: driveway_sub

detect:
  width: 640
  height: 480
  fps: 4

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 5
    post_capture: 15    
    retain:
      default: 182
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 365

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - suitcase

audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

version: 0.14
camera_groups:
  All_Cameras:
    order: 1
    icon: LuChevronUpCircle
    cameras: front_door
```

### Relevant Frigate log output

```shell
No errors
```

### Relevant go2rtc log output

```shell
No errors
```

### FFprobe output from your camera

```shell
No errors
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink video doorbell

### Screenshots of the Frigate UI's System metrics pages

<img width="1277" alt="image" src="https://github.com/user-attachments/assets/6edc5f2d-b0c2-4800-8325-59ad394a61f3">
