### DISCUSSION TITLE
[Support]: Slow/no rendering of System Metrix when using Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by Damien0505** [blakeblackshear/frigate#13552] [General Support]
### Describe the problem you are having

When attempting to access the System Metrix on a Windows base PC web browser, the /system#general page becomes unresponsive.  This is a weird one, does the same thing on Chrome, Firefox and Edge.
This only happens when using the FQDN/NPM.  If I access the webUI directly (by IP address) it works okay.

Chrome on Android works fine as does Firefox on Ubuntu when using the FQDN/NPM.

This has only occurred since upgrading to 0.14.1 .  Any suggestions would be greatly appreciated.

Cheers,
Damo

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# ~/docker/frigate/config.yml
# yaml-language-server: $schema=http://10.13.2.217:5000/api/config/schema.json

# ui:
#   use_experimental: false
#   live_mode: mse

mqtt:
  host: 10.0.0.34
  port: 1883
  user: MQTT_User
  password: xxxx
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

record:
  expire_interval: 10

ffmpeg:
  hwaccel_args: preset-nvidia-h264

# Only enable the detector if you are using coral PCIe passthrough
detectors:
  #coral:
  #  type: edgetpu
  #  device: pci
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

logger:
  default: info

live:
  height: 720
  quality: 1

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 1
  mode: continuous

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@10.0.0.52:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
 
    detect:
      width: 1280
      height: 720
      fps: 5
      max_disappeared: 200
    objects:
      track:
        - person
        - dog
        - cat
        - cow
        - horse
        - sheep
        - bear
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
        bird:
          min_score: 0.5
          threshold: 0.6
          min_area: 250
        cat:
          min_score: 0.4
          threshold: 0.5
          min_area: 150


    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 10
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
version: 0.14
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":448,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":456,"pid":441,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"114":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"125":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"126":{"cmdline":"python3 -u -m frigate","cpu":"1.5","cpu_average":"2","mem":"1.7"},"135":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"167":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"168":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"169":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"170":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"171":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"19651":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"19926":{"cmdline":"tail -f /usr/local/nginx/logs/error.log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"21":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24024":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24078":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"304":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"387":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.7"},"389":{"cmdline":"frigate.recording_manager","cpu":"1.1","cpu_average":"0","mem":"0.9"},"390":{"cmdline":"frigate.review_segment_manager","cpu":"0.3","cpu_average":"0","mem":"0.8"},"417":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"418":{"cmdline":"frigate.detector.coral1","cpu":"0.0","cpu_average":"0","mem":"0.9"},"420":{"cmdline":"frigate.detector.coral2","cpu":"0.0","cpu_average":"0","mem":"0.9"},"422":{"cmdline":"frigate.output       ","cpu":"2.3","cpu_average":"2","mem":"0.9"},"441":{"cmdline":"frigate.process:backyard","cpu":"2.1","cpu_average":"2","mem":"1.0"},"448":{"cmdline":"frigate.capture:backyard","cpu":"2.0","cpu_average":"2","mem":"0.8"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"456":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@10.0.0.52:554/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.3","cpu_average":"5","mem":"0.8"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"478":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"1","mem":"0.2"},"483":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"5.7","cpu_average":"5","mem":"0.2"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"2.9","mem":"8.5"}},"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":9.7,"pid":418},"coral2":{"detection_start":0.0,"inference_speed":9.53,"pid":420}},"gpu_usages":{"NVIDIA GeForce GTX 750 Ti":{"dec":"3.0%","enc":"0.0%","gpu":"0.0%","mem":"7.87%"}},"processes":{"go2rtc":{"pid":114},"logger":{"pid":387},"recording":{"pid":389},"review_segment":{"pid":390}},"service":{"last_updated":1725458368,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":252.1,"mount_type":"tmpfs","total":256.0,"used":3.9},"/media/frigate/clips":{"free":4175.3,"mount_type":"ext4","total":253866.3,"used":236724.1},"/media/frigate/recordings":{"free":4175.3,"mount_type":"ext4","total":253866.3,"used":236724.1},"/tmp/cache":{"free":948.1,"mount_type":"tmpfs","total":953.7,"used":5.6}},"temperatures":{"apex_0":59.05,"apex_1":63.3},"uptime":10548,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

multiple - not the issue

### Screenshots of the Frigate UI's System metrics pages

![frigate_stats (Medium)](https://github.com/user-attachments/assets/74cffba9-981b-4f34-a49d-9a7c0b5bce37)
