### DISCUSSION TITLE
[Config Support]: No events on one of the cameras after 0.14

### DISCUSSION THREAD

**Discussion by sim4dim** [blakeblackshear/frigate#13555] [Config Support] [answered]
### Describe the problem you are having

Hi All,
After upgrading to 0.14 I had noticed that one of the cameras is not marking event. Recording is working just fine.
Camera that is working fine  Reolink RLC-510WA
Camera with "events" issues is Reolink E1 Pro
Frigate is running under TrueNAS with Nvidia drivers and Coral USB detector.
Nothing was manually changed in config ... but there is no events detection on "back" camera ...

### Version

0.14

### Frigate config file

```yaml
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    ffmpeg: info

detectors:

  coral:
    type: edgetpu
    device: usb

mqtt:
  enabled: true
  host: 192.168.1.10
model:
  labelmap:
    1: car
    2: car
    3: car
    4: car
    5: car
    6: car
    7: car
    8: car
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal


birdseye:
 
  enabled: true
  
  quality: 8
  
  mode: continuous
ffmpeg:
  input_args: -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt
    -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
  hwaccel_args: preset-nvidia-h264
  
go2rtc:
  streams:
    back:
      
      - http://192.168.1.152/flv?port=1935&app=bcs&stream=channel0_main.bcs
      - ffmpeg:back
      - ffmpeg:back#video=h264#hardware    # if your camera doesn't support H264, important for HomeKit
      - ffmpeg:back#audio=opus             # only OPUS audio supported by HomeKit
    front:
      - http://192.168.1.153/flv?port=1935&app=bcs&stream=channel0_main.bcs
      - ffmpeg:front
      - ffmpeg:front#video=h264#hardware    # if your camera doesn't support H264, important for HomeKit
      - ffmpeg:front#audio=opus             # only OPUS audio supported by HomeKit
    
  homekit:
    front:                   # same stream ID from streams list
      pin: 12345678           # custom PIN, default: 19550224
      name: Reolink_Front      # custom camera name, default: generated from stream ID
      device_id: front       # custom ID, default: generated from stream ID
      device_private: front # custom key, default: generated from stream ID  

    back:                   # same stream ID from streams list
      pin: 12345678           # custom PIN, default: 19550224
      name: Reolink_Back      # custom camera name, default: generated from stream ID
      device_id: back       # custom ID, default: generated from stream ID
      device_private: back # custom key, default: generated from stream ID    
  webrtc:
    candidates:
      - 192.168.1.10:8555
      - stun:8555

cameras:
  
  front:
    motion:
      improve_contrast: true
      
    ffmpeg:
      inputs:
        - path: 
            http://192.168.1.153/flv?port=1935&app=bcs&stream=channel0_sub.bcs
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-generic
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    record:
      enabled: true
      retain:
        days: 4
        mode: all
      events:
        retain:
          default: 2
          mode: active_objects
    snapshots:
      enabled: true
    objects:
      filters:
        person:
          threshold: 0.80
        animal:
          threshold: 0.72
        car:
          threshold: 0.80
      track:
        - person
        - animal
        - car


  back:
    motion:
      improve_contrast: true

    ffmpeg:
      inputs:
        - path: 
            http://192.168.1.152/flv?port=1935&app=bcs&stream=channel0_sub.bcs
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-generic
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    record:
      enabled: true
      retain:
        days: 4
        mode: all
      events:
        retain:
          default: 2
          mode: active_objects
    snapshots:
      enabled: true
    objects:
      filters:
        person:
          threshold: 0.77
        animal:
          threshold: 0.72
      track:
        - person
        - animal




version: 0.14
```

### Relevant Frigate log output

```shell
info
2024-09-04 14:25:42
startup
Preparing Frigate...
info
2024-09-04 14:25:42
startup
Starting Frigate...
info
2024-09-04 14:26:02
frigate.app
Starting Frigate (0.14.1-f4f3cfa)
info
2024-09-04 14:26:02
frigate.util.config
Checking if frigate config needs migration...
info
2024-09-04 14:26:02
frigate.util.config
frigate config does not need migration...
info
2024-09-04 14:26:11
peewee_migrate.logs
Starting migrations
info
2024-09-04 14:26:11
peewee_migrate.logs
There is nothing to migrate
info
2024-09-04 14:26:11
frigate.app
Recording process started: 386
info
2024-09-04 14:26:11
frigate.app
Recording process started: 388
info
2024-09-04 14:26:11
frigate.app
go2rtc process pid: 111
info
2024-09-04 14:26:11
detector.coral
Starting detection process: 416
info
2024-09-04 14:26:11
frigate.app
Output process started: 418
info
2024-09-04 14:26:11
frigate.detectors.plugins.edgetpu_tfl
Attempting to load TPU as usb
info
2024-09-04 14:26:11
frigate.app
Camera processor started for front: 434
info
2024-09-04 14:26:14
frigate.detectors.plugins.edgetpu_tfl
TPU found
info
2024-09-04 14:26:11
frigate.app
Camera processor started for back: 435
info
2024-09-04 14:26:11
frigate.app
Capture process started for front: 437
info
2024-09-04 14:26:11
frigate.app
Capture process started for back: 440
```

### Relevant go2rtc log output

```shell
info
2024-09-04 14:25:42
startup
Removing stale config from last run...
info
2024-09-04 14:25:42
startup
Preparing new go2rtc config...
info
2024-09-04 14:25:47
startup
Not injecting WebRTC candidates into go2rtc config as it has been set manually
info
2024-09-04 14:25:48
startup
Starting go2rtc...
info
2024-09-04 14:25:48
startup
go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info
2024-09-04 14:25:48
startup
config path=/dev/shm/go2rtc.yaml
info
2024-09-04 14:25:48
rtsp
listen addr=:8554
info
2024-09-04 14:25:48
webrtc
listen addr=:8555
info
2024-09-04 14:25:48
api
listen addr=:1984
info
2024-09-04 14:25:52
startup
Starting go2rtc healthcheck service...
```

### Frigate stats

```json
"cameras": {
    "back": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 440,
      "detection_enabled": true,
      "detection_fps": 10.6,
      "ffmpeg_pid": 461,
      "pid": 435,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "front": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 437,
      "detection_enabled": true,
      "detection_fps": 6.7,
      "ffmpeg_pid": 460,
      "pid": 434,
      "process_fps": 4.2,
      "skipped_fps": 0.8
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "101": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "102": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "103": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "111": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "4.1",
      "cpu_average": "4",
      "mem": "0.1"
    },
    "119": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "120": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "1.5",
      "cpu_average": "2",
      "mem": "1.2"
    },
    "136": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "175": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "176": {
      "cmdline": "nginx: worker process",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "177": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "178": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "192": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "21": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "23": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "319": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "35": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "36": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "368": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "37": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "38": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "386": {
      "cmdline": "frigate.recording_manager",
      "cpu": "2.6",
      "cpu_average": "4",
      "mem": "0.7"
    },
    "388": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "39": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "40": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "415": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "416": {
      "cmdline": "frigate.detector.coral",
      "cpu": "7.9",
      "cpu_average": "8",
      "mem": "0.6"
    },
    "418": {
      "cmdline": "frigate.output       ",
      "cpu": "7.1",
      "cpu_average": "7",
      "mem": "0.6"
    },
    "434": {
      "cmdline": "frigate.process:front",
      "cpu": "6.7",
      "cpu_average": "8",
      "mem": "0.6"
    },
    "435": {
      "cmdline": "frigate.process:back ",
      "cpu": "17.5",
      "cpu_average": "18",
      "mem": "0.6"
    },
    "437": {
      "cmdline": "frigate.capture:front",
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "440": {
      "cmdline": "frigate.capture:back ",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "460": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.1.153/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -r 5 -vf fps=5,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.8",
      "cpu_average": "1",
      "mem": "0.7"
    },
    "461": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.1.152/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -r 5 -vf fps=5,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.8",
      "cpu_average": "1",
      "mem": "0.7"
    },
    "476": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/front@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.5",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "477": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/back -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/back@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "500": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "505": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "51": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "510": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "2.8",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "5101": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "5129": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "52": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "99": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "35.5",
      "mem": "95.5"
    }
  },
  "detection_fps": 17.3,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 10.07,
      "pid": 416
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 750 Ti": {
      "dec": "1.0%",
      "enc": "0.0%",
      "gpu": "1.0%",
      "mem": "4.41%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 111
    },
    "logger": {
      "pid": 368
    },
    "recording": {
      "pid": 386
    },
    "review_segment": {
      "pid": 388
    }
  },
  "service": {
    "last_updated": 1725461394,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 50.7,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 13.3
      },
      "/media/frigate/clips": {
        "free": 2098900.5,
        "mount_type": "zfs",
        "total": 2563344,
        "used": 464443.5
      },
      "/media/frigate/recordings": {
        "free": 2098900.5,
        "mount_type": "zfs",
        "total": 2563344,
        "used": 464443.5
      },
      "/tmp/cache": {
        "free": 921.1,
        "mount_type": "tmpfs",
        "total": 1024,
        "used": 102.9
      }
    },
    "temperatures": {

    },
    "uptime": 1423,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
