### DISCUSSION TITLE
[Config Support]: How to enable ffmpeg logs?

### DISCUSSION THREAD

**Discussion by Unspec7** [blakeblackshear/frigate#13562] [Config Support]
### Describe the problem you are having

I'm having ffmpeg issues but cannot for the life of me figure out how to view these logs. All I see is:

`The following ffmpeg logs include the last 100 lines prior to exit.`

From the watchdog, and then a "rtsp://127.0.0.1:8554/doorway: Invalid data found when processing input" log. _Where the hell are these ffmpeg logs?!_ The documentation on how to _actually_ setup logging is hilariously opaque.

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    ffmpeg.doorway: error

[Rest of setup redacted as not relevant]
```

### Relevant Frigate log output

```shell
Irrelevant
```

### Relevant go2rtc log output

```shell
Irrelevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

CPU (no coral)
