### DISCUSSION TITLE
[HW Accel Support]: core i7-6500U, debian 12, Hassio addon.

### DISCUSSION THREAD

**Discussion by override80** [blakeblackshear/frigate#13574] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hi, i'm running frigate 0.14.1 as an Hassio addon. Host system is a Debian 12. Platform ia a core 17-6500U. I'm trying to get HWAccel to work. So far it does nto raise any error with this config:

```
environment_vars:
  LIBVA_DRIVER_NAME: i965

...

ffmpeg:
  hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD129 -hwaccel_output_format yuv420p
```
I run `#echo 2 >  /proc/sys/kernel/perf_event_paranoid` to get GPU stats in Frigte.

I see very low GPU usage (about 2-3% with 8 cameras) and CPU usage up to 50%.

vainfo in the contaienr:
```
root@ccab4aaf-frigate-fa:/opt/frigate# vainfo --display drm --device /dev/dri/renderD129
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI

```

vainfo in the host:

```
# LIBVA_DRIVER_NAME=i965 vainfo --display drm --device /dev/dri/renderD129
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.3.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointStats
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointStats
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointStats
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice

```

Further debugging, i tried to enter the container and manually run command i found with a ps aux:

root         767  1.3  0.3 131244 26080 ?        Ss   18:12   0:00 ffmpeg -hide_banner -loglevel warning -user_agent FFmpegFrigate -hwaccel vaapi -hwaccel_device /dev/dri/renderD129 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/studio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/whatever@%Y%m%d%H%M%S%z.mp4

I thought there were some issues with the user_agent containing spaces, so i tired to override it in global_args, but i saw that doing so will add an additional "-user_agent XXXX" argument to the process (maybe it's expected?)... Anyway it's not related the ffmpeg command for sure has added quotes which are not shown in ps aux.

Well... any idea is welcome. I know i should upgrade to at least 7th gen, just wondering if somebody has some other hints!

Thanks

### Version

0.14.1

### Frigate config file

```yaml
version: 0.14

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  LIBVA_DRIVER_NAME: i965

ffmpeg:
  hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD129 -hwaccel_output_format yuv420p
  global_args: -hide_banner -loglevel warning -user_agent "FFmpegFrigate"
...
```

### docker-compose file or Docker CLI command

```yaml
Hassio Addon
```

### Relevant Frigate log output

```shell
Unfortunately i see no relevant errors
```

### Relevant go2rtc log output

```shell
As above
```

### FFprobe output from your camera

```shell
I have many different cameras, none is using HW Accel
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Mainly Hikvision

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a1fb1eff-0ad8-47a3-98e5-094e5fcbe139)

**Comment by cvroque** [comment]
I believe you need to run the Frigate (Full Access) addon and disable protection in order for HW acceleration to work.

**Comment by override80** [comment]
Sorry, forgot to mention - yes it is the Full Access add-on and protection is disabled

**Comment by NickM-27** [comment]
you should be running `preset-vaapi` not manual args.

**Reply by override80** [reply]
I tried again with prset vaapi - CPU usage is very high as with my attempts.

It seems I can't get acceleration to work

**Reply by NickM-27** [reply]
in your first example acceleration is working, we can tell because the GPU is being used. Most likely you are running on high res stream or high detect fps that is causing cpu usage to still be high

**Reply by override80** [reply]
I am using 640x360 6 fps streams for detection, full res (8MP) 15fps for recording - via go2rtc.

Let me attach part of the config, what do you think?

```
go2rtc:
  streams:
    gate:
      - rtsp://admin:aaa@10.11.12.100:554/Streaming/Channels/101
    gate_sub:
      - rtsp://admin:aaa@10.11.12.100:554/Streaming/Channels/102
...
  gate:
    ui:
      order: 1
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 480
    ffmpeg:
      #read on post to try this - no changes though
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD129
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://127.0.0.1:8554/gate
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    motion:
      contour_area: 15
      frame_height: 20
      improve_contrast: 'true'
      mask: 1,0,1,1,0.792,0.425,0.831,0.231,0.553,0.172,0,0.289,0,0
      threshold: 36
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
          objects:
            person: 7
            car: 2
    detect:
      enabled: true
      fps: 6
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          threshold: 0.7
        cat:
          threshold: 0.3
          min_score: 0.2
    zones:
      porch:
        coordinates:
          0.001,0.423,0.445,0.354,0.567,0.423,0.57,0.324,0.628,0.332,0.785,0.336,0.785,0.434,1,1,0.001,0.996
        objects:
          - person
          - cat
          - car
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - porch
```
