### DISCUSSION TITLE
[Support]: Firefox only: Cameras on main page of 0.14 are often blank

### DISCUSSION THREAD

**Discussion by mintjberry** [blakeblackshear/frigate#13577] [General Support] [answered]
### Describe the problem you are having

As per title, the individual camera feed on the main frigate UI page in 0.14 is often blank. This wasn't a problem on 0.13.
Initially when I load the page they all appear, then some quickly start disappearing and go blank. The ones that don't go blank stay permanently, or at least a lot longer. The others don't come back.

Firefox (v130.0) and Floop (Firefox fork)
![364968028-3bcb06fd-a66f-4e24-86b0-4003234f3d8e](https://github.com/user-attachments/assets/491154bf-abe4-41c1-97ee-1e9a4ff059aa)

On Chrome this is not an issue:
![364968148-834f4916-2d34-40e8-9c9d-91d62ce5e124](https://github.com/user-attachments/assets/f80f8a40-e1e9-4023-a8c1-7427c901e5b9)

GIF of issue occurring:
![Frigate2](https://github.com/user-attachments/assets/9fb34704-44a5-4236-9350-2ee87c3b1ea5)

Am not sure if it's a Frigate issue or Firefox, but would be good to get it fixed or know how to fix it.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox v130.0, Floorp (preferred) v11.17.8

### Frigate config file

```yaml
model:
  path: plus://zzzzzzzzzzzzz

mqtt:
  enabled: true
  host: 10.1.1.111
  user: zzzzzz
  password: zzzzzzz
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 1.5
    mode: all
  events:
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 21

detectors:
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    Entrance_Left:
      - ffmpeg:rtsp://username:password@10.1.1.51:554/Streaming/Channels/1
    Entrance_Right:
      - ffmpeg:rtsp://username:password@10.1.1.65:554/Streaming/Channels/1
    House_Front:
      - ffmpeg:rtsp://username:password@10.1.1.92:554/Streaming/Channels/1
    Duck_Area_Tree:
      - ffmpeg:rtsp://username:password@10.1.1.85:554/Streaming/Channels/1
    House_Garage:
      - ffmpeg:rtsp://username:password@10.1.1.7:554/Streaming/Channels/1
    House_Lawn_Left:
      - ffmpeg:rtsp://username:password@10.1.1.8:554/Streaming/Channels/1
    House_Lawn_Right:
      - ffmpeg:rtsp://username:password@10.1.1.36:554/Streaming/Channels/1
    Garage_Garden_Bed:
      - ffmpeg:rtsp://username:password@10.1.1.52:554/Streaming/Channels/1
    Shed_Lean_To:
      - ffmpeg:rtsp://username:password@10.1.1.82:554/h264Preview_01_main
    Duck_House_Inside:
      - ffmpeg:rtsp://username:password@10.1.1.60/avstream/channel=1/stream=0.sdp

cameras:
  Entrance_Left:
    enabled: true
    ui:
      order: 0
    detect:
      fps: 15
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.51:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.51:554/Streaming/Channels/2
          roles:
            - detect
    objects:
      filters:
        person:
          min_score: 0.84
          threshold: 0.84
        car:
          min_score: 0.85
          threshold: 0.85
        license_plate:
          min_score: 0.7
          threshold: 0.7
        dog:
          min_score: 0.9
          threshold: 0.9
        cat:
          min_score: 0.91
          threshold: 0.91
      track:
        - car
        - license_plate
        - dog
        - person
        - cat

  Entrance_Right:
    enabled: true
    ui:
      order: 1
    detect:
      fps: 25
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.65:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.65:554/Streaming/Channels/2
          roles:
            - detect
    motion:
      threshold: 20
    objects:
      filters:
        person:
          min_score: 0.84
          threshold: 0.84
        car:
          min_score: 0.83
          threshold: 0.83
        license_plate:
          min_score: 0.7
          threshold: 0.7
        dog:
          min_score: 0.87
          threshold: 0.87
        cat:
          min_score: 0.91
          threshold: 0.91
      track:
        - car
        - license_plate
        - dog
        - person
        - cat

  House_Front:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.92:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.92:554/Streaming/Channels/2
          roles:
            - detect
    motion:
      mask:
        - 0,0,329,0,337,169,0,334
        - 1280,0,429,0,438,147,618,253
        - 1280,0,1149,326,745,207
    objects:
      filters:
        person:
          min_score: 0.85
          threshold: 0.85
        dog:
          min_score: 0.85
          threshold: 0.85
        cat:
          min_score: 0.85
          threshold: 0.85
      track:
        - person
        - dog
        - cat

  House_Lawn_Left:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.8:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.8:554/Streaming/Channels/2
          roles:
            - detect
    motion:
      mask:
        - 0,295,0,480,141,480
        - 704,0,564,83,439,86,314,203,80,267,44,0
        - 0,127,0,0,68,0,57,91
        - 0,150,23,263,0,295
    objects:
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
        dog:
          min_score: 0.87
          threshold: 0.87
        cat:
          min_score: 0.91
          threshold: 0.91

  House_Lawn_Right:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.36:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.36:554/Streaming/Channels/2
          roles:
            - detect
    motion:
      mask:
        - 927,720,447,329,367,373,373,480,529,720
        - 391,0,463,197,1280,140,1280,0
    objects:
      filters:
        person:
          min_score: 0.80
          threshold: 0.80
        dog:
          min_score: 0.87
          threshold: 0.87
        cat:
          min_score: 0.91
          threshold: 0.91

  House_Garage:
    enabled: true
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.7:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.7:554/Streaming/Channels/2
          roles:
            - detect
    objects:
      filters:
        person:
          min_score: 0.75
          threshold: 0.75
        dog:
          min_score: 0.87
          threshold: 0.87
        cat:
          min_score: 0.91
          threshold: 0.91

  Garage_Garden_Bed:
    enabled: true
    ui:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.52:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.52:554/Streaming/Channels/2
          roles:
            - detect
    motion:
      mask:
        - 0,45,141,27,174,148,0,228
        - 330,0,640,0,640,341,595,264
    objects:
      filters:
        person:
          min_score: 0.8
          threshold: 0.8

  Duck_Area_Tree:
    enabled: true
    ui:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.85:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@10.1.1.85:554/Streaming/Channels/2
          roles:
            - detect
    objects:
      filters:
        person:
          min_score: 0.88
          threshold: 0.88

  Duck_House_Inside:
    enabled: true
    ui:
      order: 8
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.60/avstream/channel=1/stream=1.sdp
          roles:
            - record
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.9
          threshold: 0.9

  Shed_Lean_To:
    enabled: true
    ui:
      order: 9
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.1.1.82:554/h264Preview_01_main
          roles:
            - record
        - path: rtsp://username:password@10.1.1.82:554/h264Preview_01_sub
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.87
          threshold: 0.87
    snapshots:
      required_zones:
        - left
        - right
    zones:
      left:
        coordinates: 0,156,185,88,295,72,262,178,355,208,357,360,0,360
      right:
        coordinates: 640,360,640,58,419,63,303,82,397,162,320,202,321,360
    review:
      alerts:
        required_zones:
          - left
          - right
version: 0.14
camera_groups: {}
```

### Relevant Frigate log output

```shell
N/A. No related error in frigate.
```

### Relevant go2rtc log output

```shell
N/A. No related error in frigate.
```

### FFprobe output from your camera

```shell
Not sure if this is relevant, but can try this if necessary. Will just need a bit of guidance.
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Mostly Anpviz

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b257fb3e-746d-4a62-bc1a-ee00e14d4de6)

**Comment by hawkeye217** [comment]
Can you provide the output of `http://frigate_ip:port/api/go2rtc/streams`?

**Reply by mintjberry** [reply]
```
{
  "Duck_Area_Tree": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264",
          "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
        ],
        "remote_addr": "10.1.1.109, 127.0.0.1:50840",
        "send": 28910,
        "senders": [
          "8 FLAC/8000, bytes=12160, receivers=1"
        ],
        "type": "MSE/WebSocket active consumer",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265",
          "audio, recvonly, PCMA/8000"
        ],
        "receivers": [
          "96 H265, bytes=747362, senders=0",
          "8 PCMA/8000, bytes=12160, senders=1"
        ],
        "recv": 766250,
        "remote_addr": "127.0.0.1:36548",
        "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=RTSP/RTP stream from icamra ipc\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHFja5JMmuWcAgAAB9IAAJxoE; sprop-pps=RAHgdrAmQA==\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 8\r\nb=AS:64\r\na=control:streamid=1\r\n",
        "type": "RTSP passive producer",
        "url": "rtsp://127.0.0.1:8554/1995ea60c7dec9b0b6495ac275c7ab89",
        "user_agent": "ffmpeg/go2rtc"
      }
    ]
  },
  "Duck_House_Inside": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.60/avstream/channel=1/stream=0.sdp"
      }
    ]
  },
  "Entrance_Left": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.51:554/Streaming/Channels/1"
      }
    ]
  },
  "Entrance_Right": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264",
          "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
        ],
        "remote_addr": "10.1.1.109, 127.0.0.1:39840",
        "send": 12102408,
        "senders": [
          "8 FLAC/8000, bytes=5087680, receivers=1"
        ],
        "type": "MSE/WebSocket active consumer",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265",
          "audio, recvonly, PCMA/8000"
        ],
        "receivers": [
          "96 H265, bytes=374448760, senders=0",
          "8 PCMA/8000, bytes=5087680, senders=1"
        ],
        "recv": 382914612,
        "remote_addr": "127.0.0.1:56728",
        "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=RTSP/RTP stream from icamra ipc\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABRCAHmWWuSTJrlnAIAAAfSAADDghA; sprop-pps=RAHgdrAmQA==\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 8\r\nb=AS:64\r\na=control:streamid=1\r\n",
        "type": "RTSP passive producer",
        "url": "rtsp://127.0.0.1:8554/e6fb6acfcbb83c60f1f01354fe98cad1",
        "user_agent": "ffmpeg/go2rtc"
      }
    ]
  },
  "Garage_Garden_Bed": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.52:554/Streaming/Channels/1"
      }
    ]
  },
  "House_Front": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.92:554/Streaming/Channels/1"
      }
    ]
  },
  "House_Garage": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.7:554/Streaming/Channels/1"
      }
    ]
  },
  "House_Lawn_Left": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.8:554/Streaming/Channels/1"
      }
    ]
  },
  "House_Lawn_Right": {
    "consumers": [],
    "producers": [
      {
        "url": "ffmpeg:rtsp://*:*@10.1.1.36:554/Streaming/Channels/1"
      }
    ]
  },
  "Shed_Lean_To": {
    "consumers": [
      {
        "medias": [
          "video, sendonly, H264",
          "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
        ],
        "remote_addr": "10.1.1.109, 127.0.0.1:50838",
        "send": 27280,
        "senders": [
          "97 MPEG4-GENERIC/16000, bytes=22968, receivers=1"
        ],
        "type": "MSE/WebSocket active consumer",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
      }
    ],
    "producers": [
      {
        "medias": [
          "video, recvonly, H265",
          "audio, recvonly, MPEG4-GENERIC/16000"
        ],
        "receivers": [
          "96 H265, bytes=981910, senders=0",
          "97 MPEG4-GENERIC/16000, bytes=22968, senders=1"
        ],
        "recv": 1013862,
        "remote_addr": "127.0.0.1:34830",
        "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=Session streamed by \"preview\"\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=; sprop-pps=RAHAcvCJBAcONkg=\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\n",
        "type": "RTSP passive producer",
        "url": "rtsp://127.0.0.1:8554/dc59f4b9c0ad6fdbcc4c299967d62c2d",
        "user_agent": "ffmpeg/go2rtc"
      }
    ]
  }
}```

**Reply by hawkeye217** [reply]
There could be an audio codec issue with Firefox. Can you try changing your go2rtc line for `Entrance_Right` to:

```

go2rtc:
  streams:
    ...
    Entrance_Right:
      - ffmpeg:rtsp://username:password@10.1.1.65:554/Streaming/Channels/1#video=copy#audio=aac
```

Then try opening that camera in Firefox.

**Reply by mintjberry** [reply]
Didn't help. Also when I click into the entrance_right camera to view it it's just a blank page, the video feed doesn't appear. Edit - actually it does load, can just take a few seconds.

If it helps, here's my Frigate log after reboot, it seems to have some issues with entrance_left for some reason (shows 'no frames received' error for a while - after the others have loaded), but the feed eventually the entrance_left loads on the main ui (even if it then blanks out). Not sure if that is related to the issue at all.


2024-09-06 11:01:21.708257227  [INFO] Preparing Frigate...
2024-09-06 11:01:21.779090231  [INFO] Starting Frigate...
2024-09-06 11:01:23.704196773  [2024-09-06 11:01:23] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-06 11:01:23.704272473  [2024-09-06 11:01:23] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-06 11:01:23.770457263  [2024-09-06 11:01:23] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-06 11:01:53.859050521  [ WARN:0@31.378] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30063.794480 ms
2024-09-06 11:01:53.863508017  [2024-09-06 11:01:53] frigate.config                 WARNING : Entrance_Left detect fps is set to 15. This does NOT need to match your camera's frame rate. High values could lead to reduced performance. Recommended value is 5.
2024-09-06 11:01:55.680545194  [2024-09-06 11:01:55] frigate.config                 WARNING : Entrance_Right detect fps is set to 25. This does NOT need to match your camera's frame rate. High values could lead to reduced performance. Recommended value is 5.
2024-09-06 11:02:30.475821880  [2024-09-06 11:02:30] peewee_migrate.logs            INFO    : Starting migrations
2024-09-06 11:02:30.476040718  [2024-09-06 11:02:30] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-06 11:02:30.523500833  [2024-09-06 11:02:30] frigate.app                    INFO    : Recording process started: 481
2024-09-06 11:02:30.530388875  [2024-09-06 11:02:30] frigate.app                    INFO    : Recording process started: 490
2024-09-06 11:02:30.534017270  [2024-09-06 11:02:30] frigate.app                    INFO    : go2rtc process pid: 96
2024-09-06 11:02:30.571598147  [2024-09-06 11:02:30] frigate.app                    INFO    : Output process started: 536
2024-09-06 11:02:30.597932689  [2024-09-06 11:02:30] detector.coral_pci             INFO    : Starting detection process: 534
2024-09-06 11:02:30.602033974  [2024-09-06 11:02:30] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-09-06 11:02:30.602412854  [2024-09-06 11:02:30] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-09-06 11:02:30.729425422  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for Entrance_Left: 592
2024-09-06 11:02:30.742913700  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for Entrance_Right: 600
2024-09-06 11:02:30.749827915  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for House_Front: 613
2024-09-06 11:02:30.757725843  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for House_Lawn_Left: 622
2024-09-06 11:02:30.768728027  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for House_Lawn_Right: 632
2024-09-06 11:02:30.784764376  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for House_Garage: 646
2024-09-06 11:02:30.784768770  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for Garage_Garden_Bed: 655
2024-09-06 11:02:30.793580605  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for Duck_Area_Tree: 667
2024-09-06 11:02:30.802286489  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for Duck_House_Inside: 676
2024-09-06 11:02:30.810706878  [2024-09-06 11:02:30] frigate.app                    INFO    : Camera processor started for Shed_Lean_To: 685
2024-09-06 11:02:30.820248356  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for Entrance_Left: 697
2024-09-06 11:02:30.828501789  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for Entrance_Right: 707
2024-09-06 11:02:30.836407689  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for House_Front: 711
2024-09-06 11:02:30.844199963  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for House_Lawn_Left: 716
2024-09-06 11:02:30.862650203  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for House_Lawn_Right: 727
2024-09-06 11:02:30.877495020  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for House_Garage: 735
2024-09-06 11:02:30.885307740  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for Garage_Garden_Bed: 739
2024-09-06 11:02:30.914261534  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for Duck_Area_Tree: 743
2024-09-06 11:02:30.914266056  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for Duck_House_Inside: 751
2024-09-06 11:02:30.918076513  [2024-09-06 11:02:30] frigate.app                    INFO    : Capture process started for Shed_Lean_To: 755
2024-09-06 11:02:35.856345642  [2024-09-06 11:02:35] frigate.video                  ERROR   : Entrance_Left: Unable to read frames from ffmpeg process.
2024-09-06 11:02:35.856350454  [2024-09-06 11:02:35] frigate.video                  ERROR   : Entrance_Left: ffmpeg process is not running. exiting capture thread...
2024-09-06 11:02:50.891345999  [2024-09-06 11:02:50] watchdog.Entrance_Left         ERROR   : Ffmpeg process crashed unexpectedly for Entrance_Left.
2024-09-06 11:02:50.891350016  [2024-09-06 11:02:50] watchdog.Entrance_Left         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-06 11:02:50.891351891  [2024-09-06 11:02:50] ffmpeg.Entrance_Left.detect    ERROR   : [tcp @ 0x5b75ae4402c0] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:02:50.891355945  [2024-09-06 11:02:50] ffmpeg.Entrance_Left.detect    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/2: Connection timed out
2024-09-06 11:02:50.947934084  [2024-09-06 11:02:50] ffmpeg.Entrance_Left.record    ERROR   : [tcp @ 0x6253ed434400] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:02:50.947938546  [2024-09-06 11:02:50] ffmpeg.Entrance_Left.record    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/1: Connection timed out
2024-09-06 11:02:50.947940100  [2024-09-06 11:02:50] watchdog.Entrance_Left         INFO    : Terminating the existing ffmpeg process...
2024-09-06 11:02:50.947941454  [2024-09-06 11:02:50] watchdog.Entrance_Left         INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-06 11:02:55.966448956  [2024-09-06 11:02:55] frigate.video                  ERROR   : Entrance_Left: Unable to read frames from ffmpeg process.
2024-09-06 11:02:55.966454394  [2024-09-06 11:02:55] frigate.video                  ERROR   : Entrance_Left: ffmpeg process is not running. exiting capture thread...
2024-09-06 11:03:00.982988668  [2024-09-06 11:03:00] watchdog.Entrance_Left         ERROR   : Ffmpeg process crashed unexpectedly for Entrance_Left.
2024-09-06 11:03:00.982996483  [2024-09-06 11:03:00] watchdog.Entrance_Left         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-06 11:03:00.983507693  [2024-09-06 11:03:00] ffmpeg.Entrance_Left.detect    ERROR   : [tcp @ 0x5cf7398e42c0] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:03:00.983791159  [2024-09-06 11:03:00] ffmpeg.Entrance_Left.detect    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/2: Connection timed out
2024-09-06 11:03:00.996586563  [2024-09-06 11:03:00] ffmpeg.Entrance_Left.record    ERROR   : [tcp @ 0x60368445c400] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:03:00.997030277  [2024-09-06 11:03:00] ffmpeg.Entrance_Left.record    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/1: Connection timed out
2024-09-06 11:03:00.997438649  [2024-09-06 11:03:00] watchdog.Entrance_Left         INFO    : Terminating the existing ffmpeg process...
2024-09-06 11:03:00.997443836  [2024-09-06 11:03:00] watchdog.Entrance_Left         INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-06 11:03:06.013995273  [2024-09-06 11:03:06] frigate.video                  ERROR   : Entrance_Left: Unable to read frames from ffmpeg process.
2024-09-06 11:03:06.014503517  [2024-09-06 11:03:06] frigate.video                  ERROR   : Entrance_Left: ffmpeg process is not running. exiting capture thread...
2024-09-06 11:03:11.032054600  [2024-09-06 11:03:11] watchdog.Entrance_Left         ERROR   : Ffmpeg process crashed unexpectedly for Entrance_Left.
2024-09-06 11:03:11.032063208  [2024-09-06 11:03:11] watchdog.Entrance_Left         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-06 11:03:11.032067463  [2024-09-06 11:03:11] ffmpeg.Entrance_Left.detect    ERROR   : [tcp @ 0x5c94cecbe2c0] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:03:11.032071104  [2024-09-06 11:03:11] ffmpeg.Entrance_Left.detect    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/2: Connection timed out
2024-09-06 11:03:11.049524742  [2024-09-06 11:03:11] ffmpeg.Entrance_Left.record    ERROR   : [tcp @ 0x559eb7fe0400] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:03:11.049750957  [2024-09-06 11:03:11] ffmpeg.Entrance_Left.record    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/1: Connection timed out
2024-09-06 11:03:11.049853651  [2024-09-06 11:03:11] watchdog.Entrance_Left         INFO    : Terminating the existing ffmpeg process...
2024-09-06 11:03:11.049977109  [2024-09-06 11:03:11] watchdog.Entrance_Left         INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-06 11:03:16.063699233  [2024-09-06 11:03:16] frigate.video                  ERROR   : Entrance_Left: Unable to read frames from ffmpeg process.
2024-09-06 11:03:16.064059608  [2024-09-06 11:03:16] frigate.video                  ERROR   : Entrance_Left: ffmpeg process is not running. exiting capture thread...
2024-09-06 11:03:21.067044227  [2024-09-06 11:03:21] watchdog.Entrance_Left         ERROR   : Ffmpeg process crashed unexpectedly for Entrance_Left.
2024-09-06 11:03:21.079847000  [2024-09-06 11:03:21] watchdog.Entrance_Left         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-06 11:03:21.079855071  [2024-09-06 11:03:21] ffmpeg.Entrance_Left.detect    ERROR   : [tcp @ 0x5f3a81e5f2c0] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:03:21.079858311  [2024-09-06 11:03:21] ffmpeg.Entrance_Left.detect    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/2: Connection timed out
2024-09-06 11:03:21.088943025  [2024-09-06 11:03:21] ffmpeg.Entrance_Left.record    ERROR   : [tcp @ 0x6346790ba400] Connection to tcp://10.1.1.51:554?timeout=5000000 failed: Connection timed out
2024-09-06 11:03:21.088950043  [2024-09-06 11:03:21] ffmpeg.Entrance_Left.record    ERROR   : rtsp://*:*@10.1.1.51:554/Streaming/Channels/1: Connection timed out
2024-09-06 11:03:21.088952562  [2024-09-06 11:03:21] watchdog.Entrance_Left         INFO    : Terminating the existing ffmpeg process...
2024-09-06 11:03:21.088954770  [2024-09-06 11:03:21] watchdog.Entrance_Left         INFO    : Waiting for ffmpeg to exit gracefully...

**Reply by hawkeye217** [reply]
Okay, try changing it to this then:

```
go2rtc:
  streams:
    ...
    Entrance_Right:
      - ffmpeg:rtsp://username:password@10.1.1.65:554/Streaming/Channels/1#video=h264
```
