### DISCUSSION TITLE
Same object as alerts and detections in different zones

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#13598] [General]
Hi,

Is it possible to have the same object set for both alerts and detections?

For example, have a person in the driveway zone as an alert, then a person in the street zone as a detection?

**Comment by NickM-27** [comment]
if I understand you correctly, yes, just set driveway as a required zone for alerts and street as a required zone for detections, this can be done in the UI

**Reply by jakeycrx** [reply]
Good to know, thanks.  Will it recategorize previous events once I make the change? Or will it only apply to events created after the change?

**Reply by NickM-27** [reply]
only applies to future

**Reply by jakeycrx** [reply]
My goal is to have cats and dogs that enter the overall detection zone and people who enter the driveway zone as alerts.  I would like a car or person in the street zone to be detections.

Can I list a person in alerts and detections, but in different zones? 
```
    zones:
      street_dahua:
        coordinates: 
          0.279,0.192,0.034,0.238,0.024,0,0.480,0,0.611,0,0.615,0.192,0.509,0.158,0.405,0.154
        objects:
          - car
          - person
      overall_detection_dahua:
        coordinates: 0,1,1,1,1,0,0,0
        inertia: 1
        objects:
          - cat
          - dog
      driveway_dahua:
        coordinates: 
          0.893,1,0.12,1,0.016,0.304,0.067,0.292,0.248,0.232,0.348,0.243,0.505,0.253,0.678,0.428,0.741,0.544,0.731,0.683
        objects:
          - person
```
```
    review:
      alerts:
        labels:
          - cat
          - dog
          - person
        required_zones:
          - overall_detection_dahua
          - driveway_dahua
      detections:
        labels:
          - car
          - person
        required_zones:
          - street_dahua
```
