### DISCUSSION TITLE
[Support]: Unable to play exported video on IOS

### DISCUSSION THREAD

**Discussion by xsleepejelly** [blakeblackshear/frigate#13602] [General Support] [answered]
### Describe the problem you are having

Opening the Export to play on Safari/Chrome on apple device shows a media player with controls with a 00:00 seekbar with no video preview.  Video playback through history/timeline works as intended.  Downloading the export is only playable if external VLC is being used to play file.  Is it possible to download straight to photo album to play video from there?

![Frigate](https://github.com/user-attachments/assets/5b974f8d-3ebb-4ca3-b111-f67d4dbacf10)
[Video Export.txt](https://github.com/user-attachments/files/16914176/Video.Export.txt)

### Version

0.14.0-

### What browser(s) are you using?

Google Chrome 128.0.6613.98

### Frigate config file

```yaml
birdseye:
  enabled: true
  layout:
    scaling_factor: 3
  mode: motion

go2rtc:
  streams:
    A:
      - rtsp://login:password@192.168.1.101:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    A_sub:
      - rtsp://login:password@192.168.1.101:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    B:
      - rtsp://login:password@192.168.1.109:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    B_sub:
      - rtsp://login:password@192.168.1.109:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    Hallway:
      - rtsp://login:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Hallway_sub:
      - rtsp://login:password@192.168.1.108:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    LivingRoom:
      - rtsp://login:password@192.168.1.106:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    LivingRoom_sub:
      - rtsp://login:password@192.168.1.106:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    Kitchen:
      - rtsp://login:password@192.168.1.107:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Kitchen_sub:
      - rtsp://login:password@192.168.1.107:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    Driveway:
      - rtsp://login:password@192.168.1.104:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Driveway_sub:
      - rtsp://login:password@192.168.1.104:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    FrontDoor:
      - rtsp://login:password@192.168.1.102:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    FrontDoor_sub:
      - rtsp://login:password@192.168.1.102:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    Pool:
      - rtsp://login:password@192.168.1.105:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Pool_sub:
      - rtsp://login:password@192.168.1.105:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif

mqtt:
  enabled: true
  host: 192.168.1.123
  port: 1883
  user: login
  password: password

detect:
  height: 640
  width: 480
  fps: 5
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - car
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 14
  quality: 70

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  A:
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 0
            person: 14
    mqtt:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/A
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/A_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    motion:
      mask: 0.98,0.038,0.975,0.086,0.704,0.081,0.705,0.033
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Azone:
        coordinates: 0,0,0,1,1,1,1,0
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        labels:
          - person
        required_zones: Azone
      detections:
        required_zones: Azone
  B:
    review:
      alerts:
        labels:
          - person
        required_zones: Bzone
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 0
            person: 14
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/B
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/B_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    motion:
      mask:
        - 1,0,1,0.047,0.834,0.045,0.835,0
        - 0.675,0.033,0.407,0.095,0.091,0.267,0,0.282,0,0,0.695,0
        - 1,0.433,0.965,0.435,0.864,0.047,1,0.04
      threshold: 35
      contour_area: 15
      improve_contrast: 'true'
    zones:
      Bzone:
        coordinates: 0.153,0.498,0.188,1,1,1,0.818,0.246,0.181,0.376
        loitering_time: 0
        objects: person
  Hallway:
    review:
      alerts:
        labels:
          - car
        required_zones: hallwayzone
      detections:
        labels:
          - person
        required_zones: hallwayzone
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          objects:
            person: 14
    mqtt:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Hallway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Hallway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    onvif:
      host: 192.168.1.108/onvif/ptz_service
      port: 8000
      user: login
      password: password
    motion:
      mask: 0.622,0.05,0.244,0.05,0.245,0,0.623,0
    zones:
      hallwayzone:
        coordinates: 1,1,0,1,0,0,1,0
        inertia: 1
        loitering_time: 0
        objects: person
  LivingRoom:
    review:
      alerts:
        labels:
          - car
        required_zones: livingzone
      detections:
        labels:
          - person
        required_zones: livingzone
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          objects:
            person: 14
    mqtt:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/LivingRoom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/LivingRoom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    onvif:
      host: 192.168.1.106/onvif/ptz_service
      port: 8000
      user: login
      password: password
    motion:
      mask: 0.351,0.047,0,0.044,0,0,0.355,0
    zones:
      livingzone:
        coordinates: 1,0,0,0,0,1,1,1
        loitering_time: 0
        objects: person
  Kitchen:
    review:
      alerts:
        labels:
          - car
        required_zones: kitchenzone
      detections:
        labels:
          - person
        required_zones: kitchenzone
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          objects:
            person: 14
    mqtt:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kitchen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.1.107/onvif/ptz_service
      port: 8000
      user: login
      password: password
    motion:
      mask: 1,0.046,0.662,0.042,0.665,0,1,0
    zones:
      kitchenzone:
        coordinates: 0,1,1,1,1,0,0,0
        loitering_time: 0
        objects: person
        inertia: 1
  Driveway:
    objects:
      filters:
        person:
          max_area: 125000
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1,0,1,0.052,0.83,0.052,0.832,0
        - 1,0.454,0.849,0.363,0.678,0.259,0.471,0.144,0.224,0.088,0,0.106,0,0,1,0
      threshold: 45
      contour_area: 30
      improve_contrast: 'true'
    zones:
      drivewaypersonzone:
        coordinates: 1,0.603,1,1,0,1,0,0.172,0.076,0.133,0.281,0.205,0.596,0.363
        inertia: 3
        loitering_time: 0
    review:
      detections:
        required_zones: drivewaypersonzone
      alerts:
        labels:
          - person
        required_zones: drivewaypersonzone
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 
        1,0,1,0.082,0.779,0.092,0.593,0.109,0.444,0.151,0.346,0.191,0.256,0.232,0.174,0.275,0.044,0.337,0,0.367,0,0
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
    zones:
      frontdoorfar:
        coordinates: 
          0,0.372,0.294,0.227,0.465,0.164,0.603,0.12,0.765,0.107,0.899,0.102,0.977,0.095,1,0.095,1,0.331,0.434,0.457,0,0.664
        inertia: 3
        loitering_time: 0
        objects: person
      frontdoornear:
        coordinates: 1,0.331,1,1,0,1,0,0.663,0.433,0.456
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
    review:
      alerts:
        required_zones:
          - frontdoorfar
          - frontdoornear
      detections:
        required_zones:
          - frontdoorfar
          - frontdoornear
  Pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1,0.253,0.728,0.164,0.709,0,0.992,0
        - 0.278,0.072,0,0.198,0,0,0.243,0
        - 0.541,0.199,0.495,0.201,0.495,0.244,0.508,0.249,0.51,0.376,0.528,0.374,0.532,0.254,0.544,0.246
    zones:
      poolzone:
        coordinates: 0,1,1,1,1,0.489,0.463,0.262,0.477,0.068,0.282,0.089,0,0.217
        loitering_time: 0
        objects:
          - person
          - cat
      carportzone:
        coordinates: 1,0.465,1,0.275,0.695,0.175,0.671,0,0.516,0,0.501,0.237,0.731,0.347
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - cat
    review:
      alerts:
        required_zones: poolzone
      detections:
        required_zones:
          - carportzone
          - poolzone
detectors:
  coral:
    type: edgetpu
    device: pci
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuAperture
    cameras: birdseye
  Indoor:
    order: 2
    icon: LuWarehouse
    cameras:
      - B
      - A
      - Hallway
      - Kitchen
      - LivingRoom
  Outside:
    order: 3
    icon: LuTreePine
    cameras:
      - Driveway
      - FrontDoor
      - Pool
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Amcrest IP4M-1041

**Comment by NickM-27** [comment]
This is usually an issue because the hvc1 tag isn't used by the source video. We need to add that to the exports.

**Reply by skuznyuk** [reply]
I can confirm when I ran this command to add the hvc1 tag the tagged_video is now able to be played.

`ffmpeg -i driveway_0py3w7.mp4 -c copy -tag:v hvc1 tagged_video.mp4 `

Whats the actual solution for frigate? Does it need a PR update or can I set something in the config?

**Reply by NickM-27** [reply]
We will need to update the exports code, there is no config for that. We will do that along with a new recording preset for general recordings

**Reply by ClarkCheekyKent** [reply]
I was able to fix it by adding `input_args: -tag:v hvc1` to the record stream.

**Reply by Daylights** [reply]
> I was able to fix it by adding `input_args: -tag:v hvc1` to the record stream.

I'm having the same issue with 0.14.1. However, this doesn't seem to work well with input_args: preset-rtsp-restream?

**Reply by NickM-27** [reply]
you have to use manual args, can't combine manual and presets

**Reply by Daylights** [reply]
Thank you, that helps! I now set the input_args like this:

          input_args:
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts
            - -tag:v
            - hvc1

**Comment by TA2k** [comment]
Same for Frigate 0.15 beta also set ffmpg to v5 is not working here only to downgrade to 0.14 make all snapshots playable again.

**Comment by TA2k** [comment]
Is it planned to fix this in Frigate 0.15?
Clips are working on Safari with 0.14 but after update I have the  hvc1 tag issue. reverting back to 0.14 The clips are working again.

**Reply by hawkeye217** [reply]
This fix will be available in Frigate 0.16. 

https://github.com/blakeblackshear/frigate/pull/15795

**Comment by TA2k** [comment]
I tested 0.16.0-beta-1 still the same issue on safari (Desktop/iOS) with with Dahua cameras and 264 Stream and config
```
ffmpeg:
  apple_compatibility: true  # <- Adds compatibility with MacOS and iPhone
  output_args:
    record: preset-record-generic-audio-aac
```

ffprobe output:
```
 Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso6iso2avc1mp41
    encoder         : Lavf61.1.100
  Duration: 00:00:11.77, start: 0.000000, bitrate: 2264 kb/s
  Stream #0:0[0x1](und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 1280x960, 2240 kb/s, 5.14 fps, 90k tbr, 90k 

```

ffmpeg v5 is also not fixing this encoder changed but still using the new compatible_brands
