### DISCUSSION TITLE
[Config Support]: Recordings & motion data unavailable in Frigate afer updating docker-compose.yml

### DISCUSSION THREAD

**Discussion by jerome71** [blakeblackshear/frigate#13606] [Config Support] [answered]
### Describe the problem you are having

When I update docker.compose.yml, recordings and other data produced by Frigate are no longer available in Frigate (as well as users).
Recordings are still in the file system (on a USB drive), but not watchable in the Frigate UI. Previews do not work either.

I've just installed Frigate (on a Pi 5 ) and am playing with it - apart from this I am very impressed, but this (losing a lot of data if updating docker.compose.yml) is not workable in the long run.

Is there a way I can change things like port mapping, networking, device access, without losing previews and recordings?
Is there such a way with Docker compose, with Docker in another way, or should I install Frigate without Docker (if that's even possible)?

Or, is there a way to reprocess old recordings and produce again the lost data?

Thanks in advance.

I'll attach the docker-compose config instead of the Frigate config because it seems more relevant.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10 #Map the Pi hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/igor/frigate-nvr/config.yml:/config/config.yml
      - /home/igor/frigate-nvr/storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
#      - "5000:5000"
      - "1984:1984" #Go2RTC
      - "5353:5353" #mDNS
      - "51827:51827" #HomeKit  
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD"
```

### Relevant Frigate log output

```shell
No relevant Frigate log output
```

### Relevant go2rtc log output

```shell
No relevant go2rtc log output
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)
