### DISCUSSION TITLE
[Config Support]: Config to make go2rtc streams available in HomeKit

### DISCUSSION THREAD

**Discussion by jerome71** [blakeblackshear/frigate#13605] [Config Support] [answered]
### Describe the problem you are having

My config looks OK but, in Apple Home App, I do not see the go2rtc "cameras" and therefore cannot add them.

I did the recommended install of Frigate via docker compose on a 8GB Raspberry Pi 5, and it works fine with 6 1080p cameras (Coral ordered but not yet arrived).
I use 2 streams for each camera (record, detect), fetched by go2rtc as recommended.

I added the homekit config in the go2rtc section for 1 camera.
I mapped additional ports in docker-compose.yml (the usual 8971, 8554, 8555 TCP+UDP) plus 1984 for go2rtc, and 5353 (mDNS/Bonjour) and 51827 (HomeKit), with no success.

Yet the Home app on my iPhone finds no new device when I try to add one.

In the go2rtc Web UI, in the Add tab, HomeKit section, I can see the camera, but it has a strange IP address: 172.18.0.2, URL homekit://172.18.0.2:1984?device_id=4B:46:B5:FC:94:CA&feature=0&status=1.
Trying to pair it in the go2rtc webUI, I get errors
07/09/2024 14:44:49	error	[homekit] unknown host: 172.18.0.2:1984
07/09/2024 14:44:49	error	undefined error=tlv8: unmarshal zero data caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52

I am pretty new to Frigate, docker, these forums, so sorry if I am doing things in a bad way.

Any idea what I am doing wrong?
Thanks in advance

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
go2rtc: 
  streams:
    Escalier_Hameau:
      - rtsp://user:password@myIPcamera/axis-media/media.amp?resolution=1920x1080 
    Escalier_Hameau_small: # <- for RTSP streams
      - rtsp://user:password@myIPcamera/axis-media/media.amp?resolution=640x360&fps=5
  homekit:
    Escalier_Hameau:                   # same stream ID from streams list
      name: Escalier      # custom camera name, default: generated from stream ID
      pin: 12345678           # custom PIN, default: 19550224
```

### Relevant Frigate log output

```shell
Nothing special in Frigate logs.
Everything works fine except this particular issue.
```

### Relevant go2rtc log output

```shell
07/09/2024 14:44:49	error	[homekit] unknown host: 172.18.0.2:1984
07/09/2024 14:44:49	error	undefined error=tlv8: unmarshal zero data caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

**Comment by NickM-27** [comment, marked as answer]
You have to run Frigate with host networking mode

**Comment by jerome71** [comment]
Thank you. Just added "network_mode: host" under frigate in docker-compose.yml and my camera appeared in the Home app. Great!!!
Now I just have to block port 5000 on my Pi.

**Comment by 5at0ri** [comment]
hi I have the same issue but my go2rtc is an add-on for home assistant which was a os install onto my vm. 
here are the go2rtc logs: 

```
00:51:51.359	error	undefined error=hap: wrong PIN format: 123456 caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52
00:51:57.659	error	[homekit] unknown host: 10.1.2.15:1984
00:51:57.659	error	undefined error=tlv8: unmarshal zero data caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52
00:52:06.203	error	[homekit] unknown host: 172.30.232.1
00:53:26.385	error	[homekit] unknown host: 10.1.2.15:1984
00:53:26.386	error	undefined error=tlv8: unmarshal zero data caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52
```

here is my config:

```
streams:
  front_door:
    - rtsp://thisworks_live        # Stream URL from your Ring MQTT setup
    - ffmpeg:front_door#video=h264#hardware  # if your camera doesn't support H264, important for HomeKit
    - ffmpeg:front_door#audio=opus           # only OPUS audio supported by HomeKit

homekit:
  front_door:
    name: Front Door       # Name displayed in HomeKit
    pin: 12345678        # PIN to pair with HomeKit
    device_id: front_door  # Unique identifier for HomeKit
    device_private: front_door  # custom key, default: generated from stream ID
```
I also get this when seeing the new divide in hass

<img width="622" alt="image" src="https://github.com/user-attachments/assets/b1756937-054c-4883-81d9-597ba1e36cd1">

**Reply by hanjo** [reply]
I read somewhere that PINs for Homekit cannot be consecutive numbers. Try a random PIN.

**Comment by evrelse12** [comment]
Hi!
The same problem.

Have installed frigate 0.15b4 with external go2rtc 1.9.8 and ffmpeg 7.0 in /usr/lib/ffmpeg/7.0/bin/ffmpeg
frigate work as docker compose, network_mode: host, required ports opened 
go2rtc config:
```
streams:
  front:
  - rtsp://admin:password@192.168.1.101/live
  - ffmpeg:dahua1#audio=opus
  birdseye: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -f rawvideo -pix_fmt
    yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v h264_qsv -g 50
    -bf 0 -profile:v high -level:v 4.1 -async_depth:v 1 -rtsp_transport tcp -f rtsp
    {output}
homekit:
  birdseye:                    # same stream ID from streams list
    pin: 19550224           # custom PIN, default: 19550224
    name: Birdseye         # custom camera name, default: generated from stream ID
    device_id: birdseye        # custom ID, default: generated from stream ID
    device_private: birdseye   # custom key, default: generated from stream ID
  front:                    # same stream ID from streams list
    pin: 19550224           # custom PIN, default: 19550224
    name: FrontYard         # custom camera name, default: generated from stream ID
    device_id: front        # custom ID, default: generated from stream ID
    device_private: front   # custom key, default: generated from stream ID

api:
  origin: '*'
hass:
  config: /config
log:
  format: text
webrtc:
  candidates:
  - stun:8555
rtsp:
  default_query: mp4
ffmpeg:
  bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg
```
Good news:
Two streams appears on the Streams page. Both have worked preview by link "stream".
Both streams has loaded on Add -> Apple HomeKit page.
Bad news:
When I start to pair any of stream, have got message

> 192.168.1.61:1984 says
> ERROR: tlv8: unmarshal zero data

in logs:
6:49:57.914 PM | info | go2rtc version=1.9.8 platform=linux/amd64 revision=199fdd6
-- | -- | --
6:49:57.915 PM | info | config path=/dev/shm/go2rtc.yaml
6:49:57.915 PM | info | [rtsp] listen addr=:8554
6:49:57.915 PM | info | [api] listen addr=:1984
6:49:57.915 PM | info | [webrtc] listen addr=:8555/tcp
6:51:03.091 PM | error | [homekit] unknown host: 192.168.1.61:1984
6:51:03.092 PM | error | undefined error=tlv8: unmarshal zero data caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52
7:03:42.271 PM | error | [homekit] unknown host: 192.168.1.61:1984
7:03:42.271 PM | error | undefined error=tlv8: unmarshal zero data caller=github.com/AlexxIT/go2rtc/internal/homekit/api.go:52

Made next tests:
Frigate 0.14.1 (current) + go2rtc 1.9.2 (in distr) = the same result
Frigate 0.14.1 + go2rtc 1.9.6 = the same result
Frigate 0.14.1 + go2rtc 1.9.7 = the same result
Frigate 0.14.1 + go2rtc 1.9.8 = the same result
Frigate 0.15b4 + go2rtc 1.9.8 = the same result, as described above

Looks like host 192.168.1.61, where is frigate/go2rtc, unreachible by HomeKit. Host with HK is identified In mDNS.

May be you have any ideas how to solve problem?
