### DISCUSSION TITLE
[Support]: On camera rename: "Error occurred when attempting to maintain recording cache'

### DISCUSSION THREAD

**Discussion by bdoiron74** [blakeblackshear/frigate#13618] [Config Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

If I update my config to rename a camera, after reboot the log has continuous error messages about maintaining the cache for the camera that no longer exists.

Manually deleting files associated with the old name from /tmp/cache causes the error messages  to stop. Should /tmp/cache be fully cleared at startup?

### Steps to reproduce

1. Run frigate with a camera
2. Change the name of the camera in the config and restart frigate

...

### Version

0.15.0-764cca5

### Frigate config file

```yaml
version: 0.15-0

tls:
  enabled: false

logger:
  default: warning

mqtt:
  enabled: false

detect:
  enabled: false
  fps: 4

birdseye:
  enabled: false

record:
  enabled: true
  retain:
    days: 3
    mode: all
  # sync_recordings: True # TODO: not recommended

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic

go2rtc:
  log:
    level: info

  webrtc:
    candidates:
      - 10.187.214.2:8555
      - 192.168.88.1:8555
      - 192.168.88.84:8555

  streams:
    CAM-A20024:
      - rtsp://10.187.214.32:554/stream
    CAM-A20024_HQ:
      - rtsp://10.187.214.32:553/stream

cameras:
  Surface_1:
    enabled: true
    detect:
      width: 1920
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM-A20024_HQ
          roles:
            - detect
            - record
    live:
      stream_name: CAM-A20024
      height: 540
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:764cca5 # latest official dev build
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - /opt/frigate/:/media/frigate
    networks: [ localnet ]
    ports:
      - "127.0.0.1:8971:8971" # https
      - "127.0.0.1:5000:5000" # http, Internal unauthenticated access. Expose carefully.
      - "127.0.0.1:1984:1984" # go2rtc direct
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    devices:
      - /dev/dri # HW acceleration: intel driver
    cap_add:
      - CAP_PERFMON # HW acceleration: intel gpu stats
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:5000/"]
      interval: 30s
      timeout: 1s
      retries: 10
    mem_limit: 8gb      # frigate has a memory leak when cameras drop out and come back - appears to be related to using an 'exec ffmpeg' front end process for go2rtc to wrangle a bad camera
    memswap_limit: 8gb  # == mem_limit means no-swap
    restart: unless-stopped
```

### Relevant Frigate log output

```shell
frigate  | 2024-09-07 22:52:50.676586806  [2024-09-07 22:52:50] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
frigate  | 2024-09-07 22:52:50.676668999  [2024-09-07 22:52:50] frigate.record.maintainer      ERROR   : 'Surface_3'
frigate  | 2024-09-07 22:52:53.680598299  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-09-07 22:52:55.720336122  [2024-09-07 22:52:55] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
frigate  | 2024-09-07 22:52:55.720404409  [2024-09-07 22:52:55] frigate.record.maintainer      ERROR   : 'Surface_3'
frigate  | 2024-09-07 22:53:00.887344849  [2024-09-07 22:53:00] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
frigate  | 2024-09-07 22:53:00.887412314  [2024-09-07 22:53:00] frigate.record.maintainer      ERROR   : 'Surface_3'
frigate  | 2024-09-07 22:53:05.936270128  [2024-09-07 22:53:05] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
frigate  | 2024-09-07 22:53:05.936329543  [2024-09-07 22:53:05] frigate.record.maintainer      ERROR   : 'Surface_3
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Pacidal NMHD2290D

### Screenshots of the Frigate UI's System metrics pages

n/a

**Comment by NickM-27** [comment]
This is not a bug. You have not mapped a tmpfs file system for /tmp/cache like the docs instruct to https://docs.frigate.video/frigate/installation#storage

**Reply by bdoiron74** [reply]
Thank you - missed that!

**Reply by bdoiron74** [reply]
I think I see what I did - I think I saw the tmpfs mapping as [optional](https://docs.frigate.video/frigate/installation/), only to reduce wear on the drive. 

```
    - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
