### DISCUSSION TITLE
frigate should be able to detect if recording is not working

### DISCUSSION THREAD

**Discussion by ivanjx** [blakeblackshear/frigate#13620] [General]
just today, i found out that my cameras arent recording anything for a few hours for no reason (probably something killed by oom killer). i have set up a notification on home assistant to notify me if any cameras are unavailable but they dont seem to be triggered because live view is apparently still working. only restarting the container made the recording working again but now i cant sleep well at night knowing that frigate may not record silently.

![image](https://github.com/user-attachments/assets/be9873d6-b469-4f32-83e0-94bfd72ee6fb)

go2rtc config:
```yaml
go2rtc:
  ffmpeg:
    cam: -rtsp_transport tcp -i {input}
  streams:
    cam1:
      - ffmpeg:rtsp://192.168.20.21/stream1#input=cam#audio=aac#video=copy
    cam2:
      - ffmpeg:rtsp://192.168.20.22/stream1#input=cam#audio=aac#video=copy
    cam3:
      - ffmpeg:rtsp://192.168.20.23/stream1#input=cam#audio=aac#video=copy
```

HA automation:
```yaml
alias: notify on camera errors
description: ""
trigger:
  - platform: state
    entity_id:
      - camera.cam1
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - platform: state
    entity_id:
      - camera.cam2
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - platform: state
    entity_id:
      - camera.cam3
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
```
