### DISCUSSION TITLE
Events in Frigate dissapear although I've received a telegram snapshot of the event

### DISCUSSION THREAD

**Discussion by D4nb4** [blakeblackshear/frigate#13647] [Ask A Question] [answered]
Not sure if this is a bug or anything I might have set up wrong, but since upgrading from 013.2 to 0.14 I sometimes receive a telegram notification for an event but there is no video comming afterwards (using a telegram blueprint that has worked well for 0.13.2). As far as I remember, this only occurs during night time. When checking within frigate for the event, there is only the motion preview that shows that there was motion and I can see the event, but of course, in bad quality. I checked the errorlogs but nothing, checked if frigate might have restarted during the event but home assistant claims it was 'up' all day. Is anyone else experiencing such things?

![photo_2024-09-10_08-55-43](https://github.com/user-attachments/assets/cc3233e0-738c-486f-a7d9-b3b1b3407712)

**Comment by NickM-27** [comment]
Would be best to see your config. In general this would be because the object didn't qualify for a review item

**Comment by D4nb4** [comment]
Thanx for your reply NickM,

does this mean that, even if the score of an object was high enough, it still can disqualify later on, if the score drops to something low?

```
mqtt:
  host: 10.10.10.1
  user: mqtt
  password: xxxxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  global_args: -hide_banner -loglevel warning -threads 2
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -fflags
    - +genpts+discardcorrupt
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy
  retry_interval: 10

birdseye:
  enabled: false
  width: 1280
  height: 720
  quality: 8
  mode: motion

detect:
  enabled: true
  min_initialized: 2
  max_disappeared: 30
  stationary:
    interval: 50 
    threshold: 50 
#  annotation_offset: 0

motion:
  threshold: 25 
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.05
  frame_height: 100
  improve_contrast: false #  will be set to true from 1h before sunset until 1h after sunrise - via HA

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 0
    mode: all
  sync_recordings: false
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects
  preview:
    quality: very_high
  export:
    timelapse_args: -vf setpts=0.25*PTS -r 24

snapshots:
  enabled: true
  timestamp: true
  clean_copy: false
  bounding_box: true
  crop: true
  height: 600
  retain:
    default: 14
  quality: 99

objects:
  track:
    - person
    - dog
    - cat
    - car
  filters:
    person:
      min_area: 1800
      max_area: 300000
      min_ratio: 0.22
      max_ratio: 3.0
      min_score: 0.65
      threshold: 0.67

go2rtc:
  streams:
    Gate_low:
      - rtsp://user:pass*@10.10.10.15:554/livestream/13 
    Gate:
      - rtsp://user:pass*@10.10.10.15:554/livestream/12 
      - ffmpeg:Gate#audio=opus
  webrtc:
    candidates:
      - 10.10.10.1:8555
      - stun:8555

cameras:
  Gate: # Instar IN9408 via WiFi connection 5G @ 85%+
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Gate_low
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://localhost:8554/Gate
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: false
    ui:
      order: 0
      dashboard: true
    detect:
      fps: 7
      width: 1280
      height: 720
    zones:
      Gate_Hof:
        coordinates: 
          0,1,1,1,1,1,1,0.891,0.813,0.573,0.815,0.5,0.712,0.48,0.701,0.531,0.585,0.536,0.581,0.491,0.442,0.484,0.442,0.559,0.321,0.606,0.202,0.606,0.125,0.536,0,0.535
        inertia: 1
        loitering_time: 0
        objects:
          - person
          - cat
          - dog
      Gate_Balkon:
        coordinates: 0,0.016,0.396,0.013,0.4,0.252,0.423,0.253,0.429,0.481,0,0.491
        inertia: 1
        loitering_time: 0
        objects: person
      Gate_Treppe:
        coordinates: 0.821,0.505,0.899,0.511,0.898,0.272,0.817,0.251
        inertia: 3
        loitering_time: 0
        objects: person
      Gate_Strasse:
        coordinates: 1,0.881,0.816,0.573,0.817,0.51,0.9,0.516,0.903,0.422,1,0.397
        loitering_time: 0
        objects:
          - person
          - car
          - cat
          - dog
        inertia: 1
    objects:
      filters:
        car:
          mask: 0,0,1,0,1,0.568,0.88,0.567,0.88,0.681,1,0.881,1,1,0,1
        person:
          mask:
            - 0,0,1,0,1,0.188,1,0.396,0.904,0.418,0.898,0.273,0.812,0.248,0.817,0.503,0.714,0.481,0.704,0.54,0.587,0.531,0.58,0.486,0.436,0.478,0.423,0.249,0.4,0.245,0.397,0.011,0.092,0.015,0.09,0.332,0.05,0.336,0,0.397
            - 0.085,0.564,0.134,0.561,0.22,0.877,0.053,0.908
        cat:
          mask: 1,0.566,0.891,0.566,0.321,0.63,0.364,1,1,1
        dog:
          mask: 1,0.566,0.882,0.566,0.322,0.634,0.367,1,0,1,0,0,1,0
    motion:
      mask:
        - 0,0,1,0,1,0.393,0.902,0.417,0.901,0.273,0.814,0.247,0.815,0.501,0.712,0.483,0.701,0.537,0.588,0.532,0.582,0.488,0.433,0.48,0.425,0.247,0.402,0.248,0.397,0.01,0.094,0.013,0.095,0.276,0.145,0.301,0.146,0.459,0.076,0.458,0.052,0.338,0,0.402
        - 0.001,0.68,0.203,0.716,0.331,0.784,0.336,0.898,0.284,1,0,1
    best_image_timeout: 60
    webui_url: http://10.10.10.15
    review:
      detections:
        required_zones: Gate_Strasse
      alerts:
        required_zones:
          - Gate_Balkon
          - Gate_Hof
          - Gate_Treppe

ui:
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%d.%m.%Y %H:%M'

timestamp_style:
  position: tl
  format: '%d.%m.%Y %H:%M:%S'
  color:
    red: 240
    green: 240
    blue: 240
  thickness: 1
  effect: solid

version: 0.14
```
