### DISCUSSION TITLE
[Support]: gotortc error out of nowhere

### DISCUSSION THREAD

**Discussion by JoshuaSeidel** [blakeblackshear/frigate#13643] [General Support]
### Describe the problem you are having

getting this error in the logs. but so far everything seems to be working

github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.4:50056->192.168.9.127:554: i/o timeout" url=rtsp://nvr:password@192.168.9.127:554/Preview_01_sub

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Chrome

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: frigate_mqtt
  password: password
  host: 192.168.7.83

ffmpeg:
  hwaccel_args: preset-nvidia-h264
 # input_args: preset-rtsp-stream
  #output_args:
   # record: preset-record-generic-audio-copy


cameras:
  steps_cam: # <------ Name the camera
    enabled: true
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://wb:cCa3gT-password@wyze-bridge:8554/steps-cam # <----- The stream you want to use for detection
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
    review:
      detections:
        labels:
          - dog
          - person
        required_zones: steps
    zones:
      steps:
        coordinates: 0.412,0.006,0.222,1,0.824,1,0.578,0.009
        loitering_time: 0
    motion:
      mask: 0.723,0.938,0.974,0.933,0.976,0.98,0.723,0.979

  doorbell:
    enabled: true
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: doorbell
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
    review:
      detections:
        labels:
          - dog
          - person
      alerts:
        required_zones:
          - Porch
          - sidewalk
    zones:
      Porch:
        coordinates: 
          0.381,0.999,0.384,0.961,0.47,0.969,0.473,0.908,0.723,0.866,0.73,0.874,0.875,0.801,0.999,0.881,0.999,0.999
        loitering_time: 0
        objects:
          - package
          - person
          - dog
          - cat
        inertia: 3
      sidewalk:
        coordinates: 
          0.57,0.897,0.584,0.791,0.624,0.758,0.67,0.74,0.706,0.724,0.698,0.78,0.696,0.82,0.694,0.866
        loitering_time: 0
        objects:
          - dog
          - person
  driveway:
    enabled: true
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
      filters:
        car:
          mask: 0.726,0,0.717,0.057,0.846,0.091,0.828,0,0.798,0
    review:
      detections:
        labels:
          - dog
          - person
          - car
          - motorcycle
    #onvif:
    #  host: 192.168.9.4
    #  port: 8000
    #  user: admin
    #  password: password
    #  autotracking:
    #    enabled: false
    #    calibrate_on_startup: false
    #    zooming: absolute
    #    zoom_factor: 0.3
    #    track:
    #      - person
    #      - car
    #    return_preset: home
    #    timeout: 10
    #    required_zones:
    #      - complete
        required_zones: complete
      alerts:
        required_zones: leanna-parking
    zones:
      complete:
        coordinates: 
          0.077,0.208,0.105,0.184,0.207,0.109,0.334,0.05,0.452,0.036,0.561,0.067,0.718,0.129,0.846,0.202,0.916,0.261,1,0.344,0.999,0.347,0.997,0.994,0.221,1,0.16,0.848
        loitering_time: 0
        inertia: 3
      leanna-parking:
        coordinates: 0.227,0.215,0.271,0.165,0.364,0.215,0.428,0.487,0.25,0.518,0.158,0.372
        inertia: 3
        loitering_time: 5
      kaiden-parking:
        coordinates: 0.384,0.65,0.531,0.646,0.639,0.911,0.46,0.986,0.423,0.984,0.27,0.781
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: true
      mask: 0.583,0.933,0.988,0.931,0.989,0.971,0.585,0.974
version: 0.14

go2rtc:
  streams:
    steps_Cam:
      - rtsp://wb:cCa3gT-password@wyze-bridge:8554/steps-cam
    doorbell:
      - rtsp://nvr:password@192.168.9.127:554/Preview_01_main#backchannel=0
      - rtsp://nvr:password@192.168.9.127:554/Preview_01_sub
      - ffmpeg:doorbell#audio=opus#hardware#video=h264
    doorbell_sub:
      - rtsp://nvr:password@192.168.9.127:554/Preview_01_sub
      - ffmpeg:doorbell#audio=opus#hardware#video=h264
    driveway:
      - ffmpeg:rtsp://nvr:password@192.168.9.4:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
    driveway_sub:
      - ffmpeg:rtsp://nvr:password@192.168.9.4:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.9.144:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

detectors:
  coral:
    type: edgetpu
    device: pci

#detectors:
 # tensorrt:
  #  type: tensorrt
   # device: 0

model:
  path: plus://api_key

#model:
 # path: /config/model_cache/tensorrt/yolov7-320.trt
 # input_tensor: nchw
 # input_pixel_format: rgb
 # width: 320
 # height: 320

review:
  alerts:
    labels:
      - person
      - dog
      - car
  detections:
    labels:
      - person
      - dog
      - car

record:
  enabled: true
  retain:
    days: 7
    mode: motion

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 800
  height: 480
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  mode: continuous #motion #objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

tls:
  enabled: true

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

# Include all cameras by default in Birdseye view
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.4:50056->192.168.9.127:554: i/o timeout" url=rtsp://nvr:password@192.168.9.127:554/Preview_01_sub
```

### FFprobe output from your camera

```shell
tried but it just hangs
```

### Frigate stats

```json
{
  "cameras": {
    "doorbell": {
      "audio_dBFS": -53.4745,
      "audio_rms": 69.4588,
      "camera_fps": 5,
      "capture_pid": 445,
      "detection_enabled": true,
      "detection_fps": 7.8,
      "ffmpeg_pid": 456,
      "pid": 426,
      "process_fps": 5,
      "skipped_fps": 0
    },
    "driveway": {
      "audio_dBFS": -29.9771,
      "audio_rms": 1038.9541,
      "camera_fps": 5.1,
      "capture_pid": 453,
      "detection_enabled": true,
      "detection_fps": 0.2,
      "ffmpeg_pid": 462,
      "pid": 432,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "steps_cam": {
      "audio_dBFS": -49.8577,
      "audio_rms": 105.3328,
      "camera_fps": 5,
      "capture_pid": 437,
      "detection_enabled": false,
      "detection_fps": 0,
      "ffmpeg_pid": 459,
      "pid": 425,
      "process_fps": 5,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "115": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "120": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "4.5",
      "cpu_average": "4",
      "mem": "3.2"
    },
    "132": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "161": {
      "cmdline": "nginx: worker process",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "162": {
      "cmdline": "nginx: worker process",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "163": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "166": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "326": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "357": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "359": {
      "cmdline": "frigate.recording_manager",
      "cpu": "2.5",
      "cpu_average": "3",
      "mem": "0.9"
    },
    "361": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "387": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(59)",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "388": {
      "cmdline": "frigate.detector.coral",
      "cpu": "1.7",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "390": {
      "cmdline": "frigate.output       ",
      "cpu": "3.0",
      "cpu_average": "2",
      "mem": "0.9"
    },
    "425": {
      "cmdline": "frigate.process:steps_cam",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.9"
    },
    "426": {
      "cmdline": "frigate.process:doorbell",
      "cpu": "16.9",
      "cpu_average": "8",
      "mem": "0.9"
    },
    "432": {
      "cmdline": "frigate.process:driveway",
      "cpu": "4.6",
      "cpu_average": "5",
      "mem": "0.9"
    },
    "437": {
      "cmdline": "frigate.capture:steps_cam",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "445": {
      "cmdline": "frigate.capture:doorbell",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "453": {
      "cmdline": "frigate.capture:driveway",
      "cpu": "1.5",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "456": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac -r 5 -vf fps=5,scale_cuda=w=800:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.3",
      "cpu_average": "2",
      "mem": "0.9"
    },
    "459": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@wyze-bridge:8554/steps-cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/steps_cam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=800:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.7",
      "cpu_average": "2",
      "mem": "1.0"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "460": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.7",
      "cpu_average": "1",
      "mem": "1.0"
    },
    "462": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac -r 5 -vf fps=5,scale_cuda=w=800:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.9"
    },
    "480": {
      "cmdline": "ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.9.4:554/h264Preview_01_sub -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/4c58fcc388ffb581ea264a15b3a4582e",
      "cpu": "1.3",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "481": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.3",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "482": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@wyze-bridge:8554/steps-cam -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "483": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.5",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "492": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "494": {
      "cmdline": "ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.9.4:554/h264Preview_01_main -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5b47182d9205d62cfd06d5a6eeb27c6b",
      "cpu": "7.1",
      "cpu_average": "6",
      "mem": "0.2"
    },
    "503": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "527": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 800x480 -i pipe: -threads 1 -f mpegts -s 1200x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "544": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 800x480 -i pipe: -threads 1 -f mpegts -s 1200x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "549": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 800x480 -i pipe: -threads 1 -f mpegts -s 1200x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "554": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "64775": {
      "cmdline": "bash",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "64979": {
      "cmdline": "bash",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "65237": {
      "cmdline": "bash",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "65385": {
      "cmdline": "bash",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "65464": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "65505": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "7768": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "86": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "15.2",
      "cpu_average": "12",
      "mem": "0.5"
    },
    "frigate.full_system": {
      "cpu": "21.4",
      "mem": "22.3"
    }
  },
  "detection_fps": 8,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 6.22,
      "pid": 388
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 1660 SUPER": {
      "dec": "0.0%",
      "enc": "0.0%",
      "gpu": "0.0%",
      "mem": "6.45%"
    }
  },
  "processes": {
    "audio_detector": {
      "pid": 460
    },
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 357
    },
    "recording": {
      "pid": 359
    },
    "review_segment": {
      "pid": 361
    }
  },
  "service": {
    "last_updated": 1725912843,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 8187.9,
        "mount_type": "tmpfs",
        "total": 8192,
        "used": 4.1
      },
      "/media/frigate/clips": {
        "free": 2853688.2,
        "mount_type": "nfs4",
        "total": 3743423.9,
        "used": 889619.6
      },
      "/media/frigate/recordings": {
        "free": 2853688.2,
        "mount_type": "nfs4",
        "total": 3743423.9,
        "used": 889619.6
      },
      "/tmp/cache": {
        "free": 934.6,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 19.1
      }
    },
    "temperatures": {
      "apex_0": 33.05
    },
    "uptime": 20717,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Doorbell

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/0e578821-9fb9-4608-96a1-5d22aed74c58)
![image](https://github.com/user-attachments/assets/c60d660a-2db4-4ca7-a130-a78483479ce8)
