### DISCUSSION TITLE
[Config Support]: Reolink RLC-823A onvif setup Errors

### DISCUSSION THREAD

**Discussion by milkam** [blakeblackshear/frigate#13646] [Config Support] [answered]
### Describe the problem you are having

Followed the instruction. Got 2 cameras that are on the support list for PTZ Reolink RLC-823A
Verified the config of the camera on their webui, onvif enabled (And was working in BlueIris) on port 8000

I see my cameras on the Frigate UI. Both preview and main subs. 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.158
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass

go2rtc:
  streams:
    PTZ_Gauche:
      - rtsp://user:pass@192.168.1.98/Preview_01_main
    PTZ_Garage:
      - rtsp://user:pass@192.168.1.10/Preview_01_main

cameras:
  PTZ_Gauche:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.98/Preview_01_main # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.98/Preview_01_sub
          roles:
            - detect

    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640
      height: 360

    onvif:
      host: 192.168.1.98
      
    motion:
      mask: 0.734,0.002,0.355,0.011,0.016,0.16,0.003,0.982,0.989,0.99,0.991,0.015
      threshold: 50
      contour_area: 22
      improve_contrast: true
    objects:
      mask: 0.018,0.151,0.618,0.017,0.984,0.022,0.978,0.949,0.023,0.974

  PTZ_Garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.10/Preview_01_main # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.10/Preview_01_sub
          roles:
            - detect

    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640
      height: 360

    onvif:
      host: user:pass@192.168.1.98

    motion:
      mask: 0.333,0.321,0.766,0.293,1,0.501,0.998,0.998,0.003,0.997,0.008,0.356
    objects:
      mask: 
        0.337,0.328,0.352,0.604,0.01,0.634,0.008,0.992,0.993,0.993,0.997,0.511,0.766,0.298

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

audio:
  # Optional: Enable audio events (default: shown below)
  enabled: false
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 100
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 3.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: false
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 120
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Recording Export Settings
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.04*PTS -r 30
  # Optional: Recording Preview Settings
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: high
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      - cat
      - dog
      - umbrella
      - hat
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 200
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion


version: 0.14
```

### Relevant Frigate log output

```shell
2024-09-09 21:04:54.942763314  [INFO] Preparing Frigate...
2024-09-09 21:04:54.949104062  [INFO] Starting Frigate...
2024-09-09 21:04:56.002662906  [2024-09-09 21:04:56] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-09 21:04:56.002728998  [2024-09-09 21:04:56] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-09 21:04:56.027324230  [2024-09-09 21:04:56] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-09 21:04:56.145704794  [2024-09-09 21:04:56] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-09-09 21:04:56.152261543  [2024-09-09 21:04:56] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-09-09 21:04:56.159714171  [2024-09-09 21:04:56] peewee_migrate.logs            INFO    : Starting migrations
2024-09-09 21:04:56.160286161  [2024-09-09 21:04:56] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-09 21:04:56.233536630  [2024-09-09 21:04:56] frigate.ptz.onvif              ERROR   : Onvif connection to PTZ_Gauche failed: Unknown error: The CapabilityCategory type doesn't accept collections as value
2024-09-09 21:04:56.343172489  [2024-09-09 21:04:56] frigate.ptz.onvif              ERROR   : Onvif connection to PTZ_Garage failed: Unknown error: The CapabilityCategory type doesn't accept collections as value
2024-09-09 21:04:56.347309183  [2024-09-09 21:04:56] frigate.app                    INFO    : Recording process started: 429
2024-09-09 21:04:56.351498570  [2024-09-09 21:04:56] frigate.app                    INFO    : Recording process started: 438
2024-09-09 21:04:56.353265584  [2024-09-09 21:04:56] frigate.app                    INFO    : go2rtc process pid: 98
2024-09-09 21:04:56.369531035  [2024-09-09 21:04:56] detector.ov                    INFO    : Starting detection process: 458
2024-09-09 21:04:56.371647600  [2024-09-09 21:04:56] frigate.detectors.plugins.openvino WARNING : OpenVINO AUTO device type is not currently supported. Attempting to use GPU instead.
2024-09-09 21:04:56.372841313  [2024-09-09 21:04:56] frigate.app                    INFO    : Output process started: 460
2024-09-09 21:04:56.396504870  [2024-09-09 21:04:56] frigate.app                    INFO    : Camera processor started for PTZ_Gauche: 476
2024-09-09 21:04:56.396984808  [2024-09-09 21:04:56] frigate.app                    INFO    : Camera processor started for PTZ_Garage: 481
2024-09-09 21:04:56.402532192  [2024-09-09 21:04:56] frigate.app                    INFO    : Capture process started for PTZ_Gauche: 492
2024-09-09 21:04:56.415658130  [2024-09-09 21:04:56] frigate.app                    INFO    : Capture process started for PTZ_Garage: 504
2024-09-09 21:04:58.964240360  [2024-09-09 21:04:58] frigate.detectors.plugins.openvino ERROR   : SSD model input doesn't match. Found [1,300,300,3].
2024-09-09 21:05:27.201572361  [2024-09-09 21:05:27] frigate.ptz.onvif              ERROR   : Onvif is not setup for PTZ_Garage
2024-09-09 21:09:34.731435739  [2024-09-09 21:09:34] frigate.ptz.onvif              ERROR   : Onvif is not setup for PTZ_Gauche
```

### Relevant go2rtc log output

```shell
I don`t pthink anything is relevant here
2024-09-09 21:04:54.944530680  [INFO] Preparing new go2rtc config...
2024-09-09 21:04:55.218713950  [INFO] Starting go2rtc...
2024-09-09 21:04:55.314828639  21:04:55.314 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-09 21:04:55.314842050  21:04:55.314 INF config path=/dev/shm/go2rtc.yaml
2024-09-09 21:04:55.315231221  21:04:55.315 INF [rtsp] listen addr=:8554
2024-09-09 21:04:55.315233896  21:04:55.315 INF [api] listen addr=:1984
2024-09-09 21:04:55.315307649  21:04:55.315 INF [webrtc] listen addr=:8555/tcp
2024-09-09 21:05:04.942797859  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
  "cameras": {
    "PTZ_Garage": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 504,
      "detection_enabled": false,
      "detection_fps": 0,
      "ffmpeg_pid": 516,
      "pid": 481,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "PTZ_Gauche": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 492,
      "detection_enabled": false,
      "detection_fps": 0,
      "ffmpeg_pid": 503,
      "pid": 476,
      "process_fps": 5.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "86": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "105": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "111": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "1.5"
    },
    "132": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "158": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "165": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "178": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "296": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "350": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "429": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "1.0"
    },
    "438": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "457": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(59)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "458": {
      "cmdline": "frigate.detector.ov  ",
      "cpu": "0.0",
      "cpu_average": "3",
      "mem": "2.7"
    },
    "460": {
      "cmdline": "frigate.output       ",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "1.0"
    },
    "475": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "476": {
      "cmdline": "frigate.process:PTZ_Gauche",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "481": {
      "cmdline": "frigate.process:PTZ_Garage",
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "491": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "492": {
      "cmdline": "frigate.capture:PTZ_Gauche",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "503": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.98/Preview_01_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "504": {
      "cmdline": "frigate.capture:PTZ_Garage",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "509": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "516": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.10/Preview_01_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "522": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.98/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/PTZ_Gauche@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "525": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.10/Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/PTZ_Garage@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "1560": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "1686": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "2.1",
      "mem": "34.9"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "ov": {
      "detection_start": 0,
      "inference_speed": 10,
      "pid": 458
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.33%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 350
    },
    "recording": {
      "pid": 429
    },
    "review_segment": {
      "pid": 438
    }
  },
  "service": {
    "last_updated": 1725930648,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 766.4,
        "mount_type": "tmpfs",
        "total": 768,
        "used": 1.6
      },
      "/media/frigate/clips": {
        "free": 174176.7,
        "mount_type": "ext4",
        "total": 230569.9,
        "used": 44609.8
      },
      "/media/frigate/recordings": {
        "free": 174176.7,
        "mount_type": "ext4",
        "total": 230569.9,
        "used": 44609.8
      },
      "/tmp/cache": {
        "free": 942.7,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 10.9
      }
    },
    "temperatures": {},
    "uptime": 352,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c8e2a174-712c-4d77-9aef-7ed2c1fc6d1a)

### Any other information that may be helpful

Started this configuration a few hours ago and this all seems weird that somehow, a camera that is present on the documentation as compatible would not be.. Must be something I forgot and that I could not find.

**Comment by milkam** [comment]
I`ve tried with the admin user and its pass on the configuration, Without username password, with the username and password in the same line: user:pass@ip
and with one config line for each
onvif:
      host: 10.0.10.10
      port: 8000
      user: admin
      password: password
the port has beenb left as default 8000

**Reply by hawkeye217** [reply, marked as answer]
We've seen this error before from users who have a camera that doesn't have an onvif username and password, and from users who set it up incorrectly in their config file.

You're correct, you need to specify it this way:

```
cameras:
  PTZ_Garage:
    ...
    onvif:
      host: 192.168.1.10
      port: 8000
      user: admin
      password: password
```

Do not specify the host with `user:pass@192.168.1.10`. That will not work. Keep everything separate as above.
