### DISCUSSION TITLE
[Config Support]: No recording for detection events (only preview) and they vanish after an hour

### DISCUSSION THREAD

**Discussion by didrocks** [blakeblackshear/frigate#13653] [Config Support] [answered]
### Describe the problem you are having

I am opening this as a support question as it’s probably due to a misconfiguration.

So have two zones defined on my cameras that restrict the alerts. Those are properly recorded and available.

However, detections (so car and persons outside of the required zones) are displayed with their counts in the UI, but:
- I can’t see the recording (I don’t think there is any) on those events
- There is only the "preview" view, with the weak resolution and manual scrolling on the side bar
- If there is no other "alerts" during that time, they are cleaned up after an hour.

I looked for other issues and it seems that people can view those detections events similarly to alerts and they are stored as such, which is what make me think the issue is more on my configuration side.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

# Force correct driver for hw acceleration (it will pick iHD otherwise)
environment_vars:
  LIBVA_DRIVER_NAME: i965

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  enabled: true
  width: 896
  height: 672
review:
  alerts:
    required_zones:
      - detection_zone
      - car_zone
record:
  enabled: true

objects:
  track:
    - person
    - car
  filters:
    person:
      threshold: 0.7
      min_score: 0.5
    car:
      threshold: 0.7
      min_score: 0.5

go2rtc:
  streams:
    mirador1:
      - ffmpeg:http://192.168.1.100/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
    mirador1_sub:
      - ffmpeg:http://192.168.1.100/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED
    mirador2:
      - ffmpeg:http://192.168.1.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
    mirador2_sub:
      - ffmpeg:http://192.168.1.101/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED

cameras:
  mirador1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mirador1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mirador1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.994,0.982,0.994,0.946,0.577,0.946,0.577,0.982
    zones:
      detection_zone:
        coordinates: 348,210,616,121,896,232,896,672,0,672,0,204
        objects:
          - person
      car_zone:
        coordinates: 0.392,0.329,0.633,0.213,0.996,0.412,0.996,1,0.327,0.36
        objects: car
        inertia: 3
        loitering_time: 0
      portillon_zone:
        coordinates: 0.282,0.385,0.384,0.497,0.552,0.397,0.427,0.293
        objects: person
        inertia: 3
        loitering_time: 0
    mqtt:
      # Restrict where to publish snapshot via mqtt for camera
      required_zones:
        - detection_zone
        - car_zone

  mirador2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mirador2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mirador2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.994,0.982,0.994,0.946,0.577,0.946,0.577,0.982
    zones:
      detection_zone:
        coordinates: 0.152,0.333,0.432,0.121,0.619,0.254,0.866,0.058,1,0.135,1,1,0,1,0,0.348
        objects: person
        inertia: 3
        loitering_time: 0
      car_zone:
        coordinates: 0.098,0.366,0.402,0.14,0.654,0.345,0.337,0.674
        objects: car
        inertia: 3
        loitering_time: 0
      portillon_zone:
        coordinates: 0.273,0.394,0.163,0.482,0.095,0.372,0.183,0.299
        objects: person
        inertia: 3
        loitering_time: 0
    mqtt:
      # Restrict where to publish snapshot via mqtt for camera
      required_zones:
        - detection_zone
        - car_zone
version: 0.14
```

### Relevant Frigate log output

```shell
I did not have any error/warning logs at this time around. I’m happy to provide further logs in debug if needed.
```

### Relevant go2rtc log output

```shell
ditto
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![Capture d’écran](https://github.com/user-attachments/assets/4e083510-e36c-4de4-8cd9-434f3c8d3a7b)

**Comment by NickM-27** [comment, marked as answer]
this is working as expected because, since you added required zones to alerts, only those are considered "events". This is of course confusing, so in the next version of Frigate the recording config will be refactored so you can configure how long to retain alerts and detections specifically. 

For now, you can enable continuous recording with the mode as active_objects to record detetions

```
record:
  enabled: True
  retain:
    days: 2
    mode: active_objects
```
