### DISCUSSION TITLE
[Support]: Frigate fails to playback video from more than 1 day

### DISCUSSION THREAD

**Discussion by talshum** [blakeblackshear/frigate#13661] [General Support]
### Describe the problem you are having

When I'm trying to play back video from 2-3 days ago, the video doesn't load (just the snapshot loads)

### Version

0.14.0-da913d8

### What browser(s) are you using?

chrome

### Frigate config file

```yaml
cameras:
  driveway_frigate: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:xx@192.168.7.214:554/h264Preview_04_main # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    objects:
      track:
        - person
    zones:
      sidewalk:
        coordinates: 0.72,0.432,0.158,0.49,0.075,0.464,0.331,0.334,0.537,0.311,0.682,0.306
        inertia: 2
        loitering_time: 0
      driveway:
        coordinates: 0.536,0.487,0.252,0.504,0.154,0.997,0.741,0.997,0.767,0.765
        loitering_time: 0
        inertia: 3
      catchs_all:
        coordinates: 0.043,0.216,0.065,0.466,0.779,0.362,0.771,0.017
        loitering_time: 0
    motion:
      threshold: 52
      contour_area: 10
    review:
      alerts:
        required_zones: driveway
      detections:
        required_zones: driveway
    record:
      enabled: true
      preview:
        # Optional: Quality of recording preview (default: shown below).
        # Options are: very_low, low, medium, high, very_high
        quality: medium
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30
          mode: motion
```

### Relevant Frigate log output

```shell
Tag
frigate.api.media
Message
No recordings found for living_room_frigate during the requested time range
Timestamp
2024-09-10 11:30:50
Tag
frigate.api.review
Message
No motion data found for the requested time range
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

reolink

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-09-10 at 11 34 56 AM](https://github.com/user-attachments/assets/dc3b9957-ca6b-4789-866c-f90950f68882)

### Any other information that may be helpful

playback same day or 24 hours back works
