### DISCUSSION TITLE
[Support]: Frequent "No frames have been received" since update to 0.14

### DISCUSSION THREAD

**Discussion by Leon99** [blakeblackshear/frigate#13673] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I had v0.13 working great with my single camera under Docker Desktop on M1 Mini. After update to v0.14, more often than not it shows "No frames have been received, check error logs" instead of the camera view. When it happens, it consumes all the CPU resources the container is allocated. When the camera works, CPU usage is fine, similar to v0.13.

### Steps to reproduce

See description

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
database:
  path: /db/frigate.db
mqtt:
  host: 192.168.xx.xx
  user: xxx
  password: xxx

detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  front_yard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://user:pwd@mycam:554/H264/ch1/main/av_stream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 15
          mode: active_objects
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/config/
      - ./db/:/db/
      - /Volumes/nvr/frigate/storage/clips:/media/frigate/clips
      - /Volumes/nvr/frigate/storage/recordings:/media/frigate/recordings
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "pwd"
    shm_size: "140mb" # update for your cameras based on calculation above
```

### Relevant Frigate log output

```shell
Tag
frigate.record.maintainer
Message
Unable to keep up with recording segments in cache for front_yard. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Relevant go2rtc log output

```shell
No errors
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Annke I91BN

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/3a470e2e-87bb-40db-9ae2-450d48125eb3)
![image](https://github.com/user-attachments/assets/7de3450f-1e85-4c99-8fd7-df8c74bacce4)
![image](https://github.com/user-attachments/assets/4c3f7560-a7b0-4466-a923-293d428c7762)

### Any other information that may be helpful

I'm considering downgrading to v0.13 but not sure if it's possible without losing data.
