### DISCUSSION TITLE
[Config Support]: Disabling "Camera 1 has high FFMPEG CPU usage (23%)" alerts in the web UI

### DISCUSSION THREAD

**Discussion by jerome71** [blakeblackshear/frigate#13670] [Config Support] [answered]
### Describe the problem you are having

I have Frigate running on a Raspberry Pi 5 8GB with a USB Coral.
It seems to be running well. top indicates 50% CPU usage overall.

However, the UI shows alerts (with a red triangle) about CPU usage by FFMPEG for the cameras.
3 Dahua cameras have  (done in CPU because the Pi 5 no longer has 264 encode acceleration) reencoding from 1080p/25 to 720p/5 for detection (the secondary stream is limited to 704x576, aka. PAL DVD so I'd prefer to use the main stream).

Frigate system metrics show between 20% and 30% for each camera. This is obviously a percentage of individual cores 'there are 4 on the Pi 5), so actually between 4% and 7.5% of the total CPU.
IMHO this does not deserve a "danger" alert.

So here are my questions:
- is it possible to disable these "Camera 1 has high FFMPEG CPU usage (23%)" alerts, or have a higher, configurable threshold?
- if not, could the alert be based on total CPU usage, instead of percentage of a single CPU core?
- could system metrics for cameras also show percentages of total CPU instead of single core? (100% meaning comple usage of the CPU)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
go2rtc:
  streams:
    Hameau_Entree: 
      - rtsp://user:pswd@CameraIP:port/axis-media/media.amp?resolution=1920x1080

  Hameau_Entree: #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Hameau_Entree #The Stream you want to monitor
          roles:
            - record
    detect:
      enabled: true # Detection is disabled
      width: 1280 # The Cameras resolution
      height: 720 # The Cameras resolution
      fps: 5
```

### Relevant Frigate log output

```shell
No performance issue detected in the Frigate logs
```

### Relevant go2rtc log output

```shell
No performance issue detected in the Go2rtc logs
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1840" alt="Capture d’écran 2024-09-11 à 09 15 37" src="https://github.com/user-attachments/assets/a9d3297e-ddbc-4cd7-9412-f19fe769e25d">
