### DISCUSSION TITLE
[Support]:Live view freezes updates within 30 seconds unless activity is detected due to failed WebSocket connection: "Received a broken close frame"

### DISCUSSION THREAD

**Discussion by calebunleashed** [blakeblackshear/frigate#13699] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

In Birdseye view, if there is no object or motion for a camera, it is meant to stop updating the frames after the default birdseye.inactivity_threshold value which is 30 seconds according to the doco & is confirmed in the code: [frigate/frigate/config.py](https://github.com/blakeblackshear/frigate/blob/b4acf4f341fe9c630720a150ad1fa3b5575d1175/frigate/config.py#L821)

If you set this value to 120 seconds, or anything actually, it does not change the behaviour of Frigate and it will still stop updating a camera's frames after 30 seconds of the last active frame. I think the code for that is here: https://github.com/blakeblackshear/frigate/blob/b4acf4f341fe9c630720a150ad1fa3b5575d1175/frigate/output/birdseye.py#L402

BTW hard coding a value on line 402 above didn't seem to change anything either, it still stops at 30 seconds.

I have four cameras in total, three Reolink and one Logitech, same experience with all.

I have opened the direct web link for the cameras and they do not pause, their feed is continuous. 

! ! ! UPDATE ! ! !

It was not the config as pointed out by @NickM-27 and @hawkeye217, this appears to be an issue between the server and browser.

I didn't notice the console log appeared at the same time as a camera in the live view freezing:
`WebSocket connection to 'ws://192.168.1.100:5000/live/jsmpeg/cam1-home' failed: Received a broken close frame containing a reserved status code.`

This is happening consistently with all cameras... any ideas?

### Steps to reproduce

1. Set up Frigate with cameras
2. Either put the cameras in a dark room, or wait until it's pitch black at night
3. Wait for no movement to be detected
4. Watch the timestamp on you camera stop in 30 seconds

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Brave Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64) AND Safari Version 16.5.1 (18615.2.9.11.7) AND Brave on Android

### Frigate config file

```yaml
telemetry:
  stats:
    network_bandwidth: true

mqtt:
  enabled: true
  host: mqtt
  port: 1883
  user: user
  password: password

record:
  enabled: true
  retain:
    days: 7
    mode: all
  export:
    timelapse_args: -c:a aac -b:a 192k   # this is just a test, doubt it will work
  events:
    pre_capture: 7
    post_capture: 10
    retain:
      default: 30
      mode: all

motion:
  enabled: True
  # Sensitive=1, Non Sensitive=255, Default = 30
  threshold: 25
  # Higher is more sensitive
  # Default = 0.8
  lightning_threshold: 0.9
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  # Default=10
  contour_area: 8

snapshots:
  enabled: true
  retain:
    default: 90
  quality: 80

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  # Required for all:
  input_tensor: nchw
  input_pixel_format: rgb

  # yolov7-tiny-416
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  width: 416
  height: 416

detect:
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  # min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  # max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    # interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

birdseye:
  enabled: true
  mode: continuous
  restream: true 
  # 1 is the highest quality, and 31 is the lowest. Default=8
  quality: 16
  inactivity_threshold: 43200 # 12 hours

go2rtc:
  streams:
    cam1_home_sub:
      - rtsp://user:password@192.168.1.10:554/h264Preview_01_sub
      - ffmpeg:cam1_home_sub#audio=opus

cameras:
  cam1-home:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_home_sub
          input_args: preset-rtsp-restream
          hwaccel_args: preset-nvidia-h264
          roles:
            - detect
            - audio
        - path: rtsp://user:password@192.168.1.10:554/h264Preview_01_main
          hwaccel_args: preset-nvidia-h264
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    audio:
      enabled: true
    detect:
      enabled: true

version: 0.14

####################################################################################################
####################################################################################################
##                                                                                                 #
##                                                                                                 #
##                                       OBJECTS HERE                                              #
##                                                                                                 #
##                                                                                                 #
####################################################################################################
####################################################################################################


objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - truck
    - dog
    - cat
    - traffic_light
  filters:
    person:
      threshold: 0.70
    bicycle:
      threshold: 0.70
    car:
      threshold: 0.70
    motorcycle:
      threshold: 0.70
    bus:
      threshold: 0.70
    truck:
      threshold: 0.70
    dog:
      threshold: 0.40
    cat:
      threshold: 0.40

review:
  alerts:
    labels:

      - person # Temporary as it was too noisy
      - bicycle
      - car
      - motorcycle
      - bus
      - truck
      - dog
      - cat
      - traffic_light

  detections:
    labels:

      - person
      - bicycle
      - car
      - motorcycle
      - bus
      - truck
      - dog
      - cat
      - traffic_light

audio: # <- enable audio events for all camera
  enabled: true
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 15
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  sensitivity: 200=high, 500=medium, 1000=low
  min_volume: 200
```

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "2048MB"
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel
      - /dev/dri/renderD129:/dev/dri/renderD129 # Nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - /mnt/ext/NVR:/media/frigate
      # - ./py/birdseye.py:/opt/frigate/frigate/output/birdseye.py # Just for testing this bug
    ports:
      - "5000:5000" # Main UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    labels:
      - "logging=promtail"
      - "logging_jobname=containerlogs"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - YOLO_MODELS=yolov7-tiny-416
      - USE_FP16=false
      - TRT_MODEL_PREP_DEVICE=0
      - FRIGATE_RTSP_PASSWORD="password"
```

### Relevant Frigate log output

```shell
Not applicable
```

### Relevant go2rtc log output

```shell
Not applicable
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-820A, RLC-510A, 

### Screenshots of the Frigate UI's System metrics pages

<img width="1218" alt="Screenshot 2024-09-12 at 22 45 13" src="https://github.com/user-attachments/assets/cc579799-bcd8-4a5d-b52c-f82e9b8d5fd9">
<img width="1209" alt="Screenshot 2024-09-12 at 22 45 25" src="https://github.com/user-attachments/assets/657f8882-e247-422f-98d0-017be0e8c169">
<img width="1222" alt="Screenshot 2024-09-12 at 22 45 48" src="https://github.com/user-attachments/assets/f52b92a6-8bd0-482f-92c9-aed905b66187">
