### DISCUSSION TITLE
[Bug]: `pre_capture` and `post_capture` are not workling

### DISCUSSION THREAD

**Discussion by Danit2** [blakeblackshear/frigate#13694] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have set `pre_capture` and `post_capture` to 60 in the `record` settings. 
But when i go to review and select a event i don't see the 60 seconds befor the event. The review start directli with the event. 

### Steps to reproduce

Set the `pre_capture` and `post_capture` to 60 and see whats happen.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 14
    mode: motion
  events:
    pre_capture: 60
    post_capture: 60
    retain:
      default: 14
      mode: motion
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Other

### Install method

Docker CLI

### Network connection

Mixed

### Camera make and model

Wyze and Dahua

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/1569bc3e-b473-4611-abf6-18e3024d6d7f)
