### DISCUSSION TITLE
[Camera Support]: Stuttering and audio out of sync

### DISCUSSION THREAD

**Discussion by n07r1x** [blakeblackshear/frigate#13701] [Camera Support]
### Describe the problem you are having

Hello everyone,

I have a problem with my two Reolink RLC-811A cameras. Sadly I don't know exactly when this started to happen.
But the first problem is that in the event review in frigate the video is stuttering every 1-2 seconds so these videos look very chopped off. On the recordings there is no stuttering.
The second problem is that in the event review and also the recordings on hard drive the audio is massively delayed.
When restarting frigate, audio is in sync for a while, but after a few minutes it starts to get out of sync again. I don't know if the stuttering and the audio delay are related.
With the other camera, a Hikvision, there are no issues at all.
What I already tried:

- reduced the resolution
- reduced bitrate
- reduced fps
- different firmware versions
- tried h265 and h264

Thanks for help in advance!

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 130.0 , Safari 17.4.1

### Frigate config file

```yaml
mqtt:
  host: xy
  user: mqtt
  password: mqtt

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Stellplatz:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            http://10.10.0.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs
          roles:
            - detect
          input_args: preset-http-reolink

        - path: rtsp://xx:yy@10.10.0.201:554/h265Preview_01_main
          roles:
            - record
          input_args: preset-rtsp-generic
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy

    detect:
      width: 896
      height: 512
      fps: 10

    record:
      enabled: true
      retain:
        days: 14
      events:
        retain:
          default: 14

    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

    motion:
      mask:
        - 792,512,829,512,827,468,794,470

  Hinterhof:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            http://10.10.0.202/flv?port=1935&app=bcs&stream=channel0_ext.bcs
          roles:
            - detect
          input_args: preset-http-reolink

        - path: rtsp://xx:yy@10.10.0.202:554/h265Preview_01_main
          roles:
            - record

          input_args: preset-rtsp-generic
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy

    detect:
      width: 896
      height: 512
      fps: 10

    record:
      enabled: true
      retain:
        days: 14
      events:
        retain:
          default: 14

    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

    motion:
      mask:
        - 792,512,829,512,827,468,794,470
  Eingang:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xx:yy@10.10.0.203:554/Streaming/Channels/103
          roles:
            - detect
          input_args: preset-rtsp-generic

        - path: rtsp://xx:yy@10.10.0.203:554/Streaming/Channels/101
          roles:
            - record

          input_args: preset-rtsp-generic
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy

    detect:
      width: 1920
      height: 1080
      fps: 10

    record:
      enabled: true
      retain:
        days: 14
      events:
        retain:
          default: 14

    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          min_score: 0.65
          threshold: 0.75

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14
      required_zones:
        - zone_auffahrt
        - zone_alles
    motion:
      mask:
        - 1920,980,1920,1025,1863,1028,1862,983
    zones:
      zone_auffahrt:
        coordinates: 1310,126,1123,341,1920,1080,1920,348
        objects:
          - car
      zone_alles:
        coordinates: 0,1080,1920,1080,1920,0,0,0
        objects:
          - person
          - cat
    review:
      alerts:
        required_zones:
          - zone_auffahrt
          - zone_alles
version: 0.14
```

### Relevant Frigate log output

```shell
2024-09-12 14:45:38.188779150  [INFO] Preparing Frigate...
2024-09-12 14:45:38.200382523  [INFO] Starting Frigate...
2024-09-12 14:45:39.419529414  [2024-09-12 14:45:39] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-12 14:45:39.419616663  [2024-09-12 14:45:39] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-12 14:45:39.451831820  [2024-09-12 14:45:39] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-12 14:45:39.575551197  [2024-09-12 14:45:39] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-09-12 14:45:39.602940971  [2024-09-12 14:45:39] peewee_migrate.logs            INFO    : Starting migrations
2024-09-12 14:45:39.603034981  [2024-09-12 14:45:39] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-12 14:45:39.612379528  [2024-09-12 14:45:39] frigate.app                    INFO    : Recording process started: 381
2024-09-12 14:45:39.617518489  [2024-09-12 14:45:39] frigate.app                    INFO    : Recording process started: 390
2024-09-12 14:45:39.620539053  [2024-09-12 14:45:39] frigate.app                    INFO    : go2rtc process pid: 98
2024-09-12 14:45:39.643142464  [2024-09-12 14:45:39] detector.coral                 INFO    : Starting detection process: 410
2024-09-12 14:45:42.259977028  [2024-09-12 14:45:39] frigate.app                    INFO    : Output process started: 412
2024-09-12 14:45:42.260115329  [2024-09-12 14:45:40] frigate.app                    INFO    : Camera processor started for Stellplatz: 430
2024-09-12 14:45:42.263708424  [2024-09-12 14:45:39] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-09-12 14:45:42.263729179  [2024-09-12 14:45:40] frigate.app                    INFO    : Camera processor started for Hinterhof: 434
2024-09-12 14:45:42.263799995  [2024-09-12 14:45:42] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-09-12 14:45:42.263905709  [2024-09-12 14:45:40] frigate.app                    INFO    : Camera processor started for Eingang: 439
2024-09-12 14:45:42.263973859  [2024-09-12 14:45:40] frigate.app                    INFO    : Capture process started for Stellplatz: 442
2024-09-12 14:45:42.263997462  [2024-09-12 14:45:40] frigate.app                    INFO    : Capture process started for Hinterhof: 452
2024-09-12 14:45:42.264041659  [2024-09-12 14:45:40] frigate.app                    INFO    : Capture process started for Eingang: 455
```

### Relevant go2rtc log output

```shell
2024-09-12 14:45:38.188701681  [INFO] Preparing new go2rtc config...
2024-09-12 14:45:38.498265671  [INFO] Starting go2rtc...
2024-09-12 14:45:38.602347980  14:45:38.602 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-12 14:45:38.602372733  14:45:38.602 INF config path=/dev/shm/go2rtc.yaml
2024-09-12 14:45:38.602780313  14:45:38.602 INF [rtsp] listen addr=:8554
2024-09-12 14:45:38.602891582  14:45:38.602 INF [webrtc] listen addr=:8555/tcp
2024-09-12 14:45:38.603456260  14:45:38.603 INF [api] listen addr=:1984
2024-09-12 14:45:48.184751459  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://xx:yy@10.10.0.201:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000813, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{
  "cameras": {
    "Eingang": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 10.1,
      "capture_pid": 455,
      "detection_enabled": true,
      "detection_fps": 20.1,
      "ffmpeg_pid": 472,
      "pid": 439,
      "process_fps": 10,
      "skipped_fps": 0
    },
    "Hinterhof": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 10.1,
      "capture_pid": 452,
      "detection_enabled": true,
      "detection_fps": 0,
      "ffmpeg_pid": 458,
      "pid": 434,
      "process_fps": 10.1,
      "skipped_fps": 0
    },
    "Stellplatz": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 10.1,
      "capture_pid": 442,
      "detection_enabled": true,
      "detection_fps": 0,
      "ffmpeg_pid": 468,
      "pid": 430,
      "process_fps": 10,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "85": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "86": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "91": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "109": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "3.2",
      "cpu_average": "3",
      "mem": "2.5"
    },
    "111": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "130": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "158": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "161": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "291": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "296": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "337": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "381": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "390": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "409": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "410": {
      "cmdline": "frigate.detector.coral",
      "cpu": "6.8",
      "cpu_average": "7",
      "mem": "0.6"
    },
    "412": {
      "cmdline": "frigate.output       ",
      "cpu": "3.0",
      "cpu_average": "3",
      "mem": "0.6"
    },
    "430": {
      "cmdline": "frigate.process:Stellplatz",
      "cpu": "1.8",
      "cpu_average": "2",
      "mem": "0.6"
    },
    "434": {
      "cmdline": "frigate.process:Hinterhof",
      "cpu": "1.7",
      "cpu_average": "3",
      "mem": "0.7"
    },
    "439": {
      "cmdline": "frigate.process:Eingang",
      "cpu": "10.5",
      "cpu_average": "7",
      "mem": "0.7"
    },
    "442": {
      "cmdline": "frigate.capture:Stellplatz",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.6"
    },
    "452": {
      "cmdline": "frigate.capture:Hinterhof",
      "cpu": "1.0",
      "cpu_average": "1",
      "mem": "0.6"
    },
    "455": {
      "cmdline": "frigate.capture:Eingang",
      "cpu": "4.0",
      "cpu_average": "3",
      "mem": "0.6"
    },
    "458": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://10.10.0.202/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 10 -vf fps=10,scale_vaapi=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.7",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "459": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "468": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://10.10.0.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 10 -vf fps=10,scale_vaapi=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.7",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "472": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.0.203:554/Streaming/Channels/103 -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "9.5",
      "cpu_average": "9",
      "mem": "0.2"
    },
    "481": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.0.202:554/h265Preview_01_main -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Hinterhof@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.2",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "482": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "484": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.0.203:554/Streaming/Channels/101 -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Eingang@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.0"
    },
    "485": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.10.0.201:554/h265Preview_01_main -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Stellplatz@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.2",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "490": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "495": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "610": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "8146": {
      "cmdline": "sh",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "8313": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "8347": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "8.6",
      "mem": "48.3"
    }
  },
  "detection_fps": 20.1,
  "detectors": {
    "coral": {
      "detection_start": 1726155738.435789,
      "inference_speed": 8,
      "pid": 410
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "2.34%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 337
    },
    "recording": {
      "pid": 381
    },
    "review_segment": {
      "pid": 390
    }
  },
  "service": {
    "last_updated": 1726155738,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 93.5,
        "mount_type": "tmpfs",
        "total": 100,
        "used": 6.5
      },
      "/media/frigate/clips": {
        "free": 768819.1,
        "mount_type": "ext4",
        "total": 3754443,
        "used": 2794835.6
      },
      "/media/frigate/recordings": {
        "free": 768819.1,
        "mount_type": "ext4",
        "total": 3754443,
        "used": 2794835.6
      },
      "/tmp/cache": {
        "free": 811.8,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 141.9
      }
    },
    "temperatures": {},
    "uptime": 3398,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-811A

### Screenshots of the Frigate UI's System metrics pages

<img width="2554" alt="Bildschirmfoto 2024-09-12 um 17 45 00" src="https://github.com/user-attachments/assets/766f5f9a-d2a8-4108-b3b0-89a4cd4c792d">
<img width="2557" alt="Bildschirmfoto 2024-09-12 um 17 45 10" src="https://github.com/user-attachments/assets/e2e37402-d4f6-4007-bdf8-4b70e9d8c430">
