### DISCUSSION TITLE
[Config Support]: Birdseye restreaming not working

### DISCUSSION THREAD

**Discussion by reassuringgreet** [blakeblackshear/frigate#13700] [Config Support] [answered]
### Describe the problem you are having

I'm trying to set up birdseye restreaming to rtsp according to [this](https://docs.frigate.video/configuration/restream/) and can't get it to work. All cameras work correctly when viewed individually, but birdseye only works in jsmpeg, not mse or webrtc. Logs in go2rtc show `2024-09-12 11:14:36.628482083  11:14:36.628 WRN [rtsp] error="streams: exec: exit status 1" stream=birdseye`, nothing else I could find. The stream at `rtsp://<frigate-host>:8554/birdseye` is also not working in vlc. 
Frigate's running on docker.

Go2rtc streams page shows the following:

```
birdseye	
consumers	null
producers	
0	
url	"exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -rtsp_transport tcp -f rtsp {output}"
calle1	
consumers	null
producers	
0	
url	"http://192.168.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*"
calle2	
consumers	null
producers	
0	
url	"http://192.168.1.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*"
timbre1	
consumers	null
producers	
0	
url	"http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*"
timbre2	
consumers	null
producers	
0	
url	"http://192.168.1.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=*"
```

### Version

System 0.13.2-f4a44fd

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.1
  user: MQTT-user
  password: passw0rd

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 15
  mode: continuous


ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy
    
record:
  enabled: true
  retain:
    days: 21
    mode: all
detect:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  retain:
    default: 21


objects:
  track:
  - car
  - cat
  - person
  - dog
  - mouse
  filters:
    person:
      min_score: 0.5
      threshold: 0.8
    cat:
      min_score: 0.5
      threshold: 0.8
    dog:
      min_score: 0.5
      threshold: 0.8

motion:
  mask: 906,64,1670,64,1673,0,894,0
  threshold: 50
  lightning_threshold: 0.5
  
go2rtc:
  streams:
    calle1:
      - "http://192.168.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"    
    calle2:
      - "http://192.168.1.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"    
    timbre1:
      - "http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"    
    timbre2:
      - "http://192.168.1.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"        
cameras:
  calle1:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - car
      
      filters:
        person:
          mask:
            - 0,1277,2560,393,2560,0,0,0
        car:
          mask:
            - 0,1277,2560,393,2560,0,0,0
        dog:
          mask:
            - 0,1277,2560,393,2560,0,0,0

  calle2:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect

  timbre1:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat

  timbre2:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          mask:
            - 337,888,1117,800,1113,994,354,1180
```

### Relevant Frigate log output

```shell
mqtt:
  host: 192.168.1.10
  user: MQTT-user
  password: passw0rd

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 15
  mode: continuous


ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy
    
record:
  enabled: true
  retain:
    days: 21
    mode: all
detect:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  retain:
    default: 21


objects:
  track:
  - car
  - cat
  - person
  - dog
  - mouse
  filters:
    person:
      min_score: 0.5
      threshold: 0.8
    cat:
      min_score: 0.5
      threshold: 0.8
    dog:
      min_score: 0.5
      threshold: 0.8

motion:
  mask: 906,64,1670,64,1673,0,894,0
  threshold: 50
  lightning_threshold: 0.5
  
go2rtc:
  streams:
    calle1:
      - "http://192.168.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"    
    calle2:
      - "http://192.168.1.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"    
    timbre1:
      - "http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"    
    timbre2:
      - "http://192.168.1.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd"        
cameras:
  calle1:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - car
      
      filters:
        person:
          mask:
            - 0,1277,2560,393,2560,0,0,0
        car:
          mask:
            - 0,1277,2560,393,2560,0,0,0
        dog:
          mask:
            - 0,1277,2560,393,2560,0,0,0

  calle2:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect

  timbre1:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat

  timbre2:
    birdseye:
      enabled: true
    ffmpeg:
      inputs:
        - path: "http://192.168.1.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=passw0rd#video=copy#audio=copy"
          input_args: preset-http-reolink
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          mask:
            - 337,888,1117,800,1113,994,354,1180
```

### Relevant go2rtc log output

```shell
2024-09-12 11:13:35.846073286  [INFO] Preparing new go2rtc config...
2024-09-12 11:13:36.373352507  [INFO] Starting go2rtc...
2024-09-12 11:13:36.429147824  11:13:36.429 INF go2rtc version 1.8.4 linux/amd64
2024-09-12 11:13:36.429472488  11:13:36.429 INF [rtsp] listen addr=:8554
2024-09-12 11:13:36.429508868  11:13:36.429 INF [api] listen addr=:1984
2024-09-12 11:13:36.429588189  11:13:36.429 INF [webrtc] listen addr=:8555
2024-09-12 11:13:45.840994418  [INFO] Starting go2rtc healthcheck service...
2024-09-12 11:14:36.628482083  11:14:36.628 WRN [rtsp] error="streams: exec: exit status 1" stream=birdseye
```

### Frigate stats

```json
cameras	
calle1	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	691
detection_enabled	1
detection_fps	1.1
ffmpeg_pid	699
pid	685
process_fps	5.1
skipped_fps	0
calle2	
audio_dBFS	0
audio_rms	0
camera_fps	5
capture_pid	695
detection_enabled	1
detection_fps	0.4
ffmpeg_pid	701
pid	686
process_fps	5
skipped_fps	0
timbre1	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	700
detection_enabled	1
detection_fps	2.3
ffmpeg_pid	710
pid	687
process_fps	5.1
skipped_fps	0
timbre2	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	704
detection_enabled	1
detection_fps	4.7
ffmpeg_pid	711
pid	689
process_fps	5.1
skipped_fps	0
cpu_usages	
1	
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
15	
cmdline	"s6-supervise s6-linux-init-shutdownd"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
17	
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
24	
cmdline	"s6-supervise go2rtc-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
25	
cmdline	"s6-supervise frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
26	
cmdline	"s6-supervise frigate-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
27	
cmdline	"s6-supervise go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
28	
cmdline	"s6-supervise nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
29	
cmdline	"s6-supervise go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
30	
cmdline	"s6-supervise s6rc-oneshot-runner"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
31	
cmdline	"s6-supervise s6rc-fdholder"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
32	
cmdline	"s6-supervise nginx-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
41	
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
42	
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
80	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
81	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
82	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
89	
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
97	
cmdline	"bash ./run.user go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
98	
cmdline	"python3 -u -m frigate"
cpu	"1.4"
cpu_average	"4"
mem	"5.4"
113	
cmdline	"nginx: master process nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
145	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
146	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
147	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
148	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
160	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
183	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
209	
cmdline	"nginx: worker process"
cpu	"0.1"
cpu_average	"0"
mem	"0.0"
244	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
277	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
314	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
345	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
381	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
417	
cmdline	"nginx: cache manager process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
583	
cmdline	"frigate.logger       "
cpu	"0.0"
cpu_average	"0"
mem	"0.3"
650	
cmdline	"frigate.recording_manager"
cpu	"2.8"
cpu_average	"2"
mem	"0.6"
659	
cmdline	"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)"
cpu	"0.2"
cpu_average	"0"
mem	"0.0"
660	
cmdline	"frigate.detector.coral"
cpu	"3.3"
cpu_average	"6"
mem	"0.5"
662	
cmdline	"frigate.output       "
cpu	"30.4"
cpu_average	"29"
mem	"0.5"
668	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
669	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
670	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
671	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
672	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 15 -bf 0 pipe:"
cpu	"5.3"
cpu_average	"5"
mem	"0.2"
685	
cmdline	"frigate.process:calle1"
cpu	"2.3"
cpu_average	"5"
mem	"0.9"
686	
cmdline	"frigate.process:calle2"
cpu	"1.6"
cpu_average	"4"
mem	"0.9"
687	
cmdline	"frigate.process:timbre1"
cpu	"3.8"
cpu_average	"10"
mem	"0.9"
689	
cmdline	"frigate.process:timbre2"
cpu	"10.4"
cpu_average	"7"
mem	"0.9"
691	
cmdline	"frigate.capture:calle1"
cpu	"4.9"
cpu_average	"4"
mem	"0.8"
695	
cmdline	"frigate.capture:calle2"
cpu	"3.2"
cpu_average	"3"
mem	"0.8"
699	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-f4a44fd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/calle1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"5.3"
cpu_average	"5"
mem	"0.7"
700	
cmdline	"frigate.capture:timbre1"
cpu	"5.2"
cpu_average	"4"
mem	"0.8"
701	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-f4a44fd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.1.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/calle2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1440:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"4.1"
cpu_average	"4"
mem	"0.6"
704	
cmdline	"frigate.capture:timbre2"
cpu	"4.6"
cpu_average	"4"
mem	"0.8"
710	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-f4a44fd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/timbre1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"5.2"
cpu_average	"5"
mem	"0.7"
711	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.2-f4a44fd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.1.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/timbre2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"5.0"
cpu_average	"5"
mem	"0.7"
6571	
cmdline	"sleep 30s"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
6754	
cmdline	"ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6442530e1f75e11730e7ee15cfc6043a"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
detection_fps	8.5
detectors	
coral	
detection_start	0
inference_speed	7.94
pid	660
gpu_usages	
NVIDIA GeForce RTX 2060	
dec	"30.0%"
enc	"0.0%"
gpu	"2.0%"
mem	"12.54%"
processes	
go2rtc	
pid	89
logger	
pid	583
recording	
pid	650
service	
last_updated	1726151231
latest_version	"0.14.1"
storage	
/dev/shm	
free	2016.2
mount_type	"tmpfs"
total	2048
used	31.8
/media/frigate/clips	
free	36955
mount_type	"ext4"
total	13245591
used	12541023.3
/media/frigate/recordings	
free	36955
mount_type	"ext4"
total	13245591
used	12541023.3
/tmp/cache	
free	1880.1
mount_type	"tmpfs"
total	1907.4
used	27.2
temperatures	{}
uptime	805
version	"0.13.2-f4a44fd"
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a71b6dde-1401-4e21-828b-13523b20a8ea)
![image](https://github.com/user-attachments/assets/939b1a36-b905-40ff-b662-2c4c353f2844)
![image](https://github.com/user-attachments/assets/1e413063-4179-4313-bae1-6d64e97aa543)
