### DISCUSSION TITLE
[Bug]: Frigate+ View is zoomed in so I cant reach "Not Person" buttons

### DISCUSSION THREAD

**Discussion by TheQue42** [blakeblackshear/frigate#13714] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I try to browse the snapshots in the frigate+ view, to mark all the images that have been wrongly labeled as persons, etc, I cannot reach the buttons, because the image is so zoomed in, and I cant scroll out either.
I noticed that SOME pictures, (which I think came from a camera with different aspect), did work, but now, all the images that are left, are not possible to manually upload to frigaste.

I first noticed it in my firefox browser 129.0.1 (64-bitars), but I have now tried running with chromium and chrome (on Opensuse tumbleweed updated today), and with the same result.

### Steps to reproduce

1. Open frigate web ui.
2. select frigate+ view
3. try to tag an image for upload to frigate+ web.
...
__

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Version 128.0.6613.119 (openSUSE Build) stable (64-bit), Firefox 129.0.1, Chrome Version 128.0.6613.137 (Official Build) (64-bit)

### Frigate config file

```yaml
mqtt:
  host: vimes.disc-world.se
  client_id: frigate
  topic_prefix: frigate
model:
  path: plus://XXXXX
go2rtc:
  streams:
    snipped:
#  log:
#    level: info
#    rtsp: info
#    streams: info
#    webrtc: debug
cameras:
  fr_framsida:
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      height: 360
      quality: 85
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - fr_entren
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fr_framsida
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fr_framsida_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
        - 0,0.319,0.241,0.294,0.665,0.214,0.704,0.146,0.731,0,0.514,0,0.183,0,0,0
        - 1,0.419,1,1,0.772,1,0.802,0.625,0.811,0.403,0.855,0.236
        - 1,0.169,1,0.294,0.906,0.256,0.875,0.144
        - 1,0,1,0.144,0.811,0.081,0.786,0
        - 0,1,0.309,1,0.309,0.931,0,0.931
        - 0,0.358,0,0.539,0,0.708,0.183,0.492,0.163,0.408,0.073,0.442,0.058,0.308
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
    objects:
      track:
        - person
        - face
        - car
        - dog
        - cat
      filters:
        car:
          mask: 
            0.785,0.417,0.611,0.411,0.59,0.123,0.525,0.139,0.161,0.207,0.199,0.506,0.005,0.772,0,1,0.767,1,0.778,0.878
    zones:
      fr_entren:
        coordinates: 
          0.78,0.423,0.615,0.421,0.588,0.121,0.508,0.03,0.166,0.199,0.2,0.506,0,0.782,0,1,0.767,1,0.778,0.878
        objects:
          - person
          - face
        inertia: 3
        loitering_time: 0
      fr_driveway:
        coordinates: 
          189,138,543,152,574,125,640,136,640,88,640,50,525,28,502,0,469,0,453,68,409,81,101,85,29,114,49,147
        objects:
          - car
    review:
      alerts:
        required_zones:
          - fr_entren
  fr_baksidan:
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      height: 576
      quality: 85
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fr_baksidan
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fr_baksidan_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
    motion:
      mask:
        - 265,179,156,197,21,451,0,190,0,0,589,0,1024,0,1024,150,965,147,950,177,825,173,717,174
        - 643,576,1024,576,1024,447
      threshold: 40
      contour_area: 15
      improve_contrast: 'true'
    objects:
      track:
        - person
        - face
        - cat
        - dog
      filters:
        person:
          min_score: .7
          threshold: .75
  fr_hallen:
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      height: 480
      quality: 75
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fr_hallen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fr_hallen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0,0,0.522,0.258,0.303,0.246,0
    detect:
      width: 640
      height: 480
      fps: 7
      enabled: false
    objects:
      track:
        - person
        - face
#      filters:
#        person:
#          threshold: 0.73
  fr_kitchen:
    snapshots:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fr_kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fr_kitchen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 6
      enabled: false
    motion:
      mask: 
        0.594,0.839,0.577,0.678,0.682,0.385,0.802,0.416,0.852,0.512,0.943,0.578,0.931,0.903,0.849,0.95
    objects:
      track:
        - person
        - face
  fr_vardagsrum:
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      height: 576
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fr_vardagsrum
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fr_vardagsrum_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1024
      height: 576
      fps: 5
      enabled: false
    motion:
      mask:
        - 463,136,458,0,1024,0,1024,376,928,351,962,85,840,63,788,214
        - 198,162,364,136,363,24,172,49
    objects:
      track:
        - person
        - face
  fr_gillestugan:
    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      height: 640
      quality: 75
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fr_gillestugan
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fr_gillestugan_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0,0,278,255,146,260,0
    detect:
      width: 640
      height: 480
      fps: 6
      enabled: false
    objects:
      track:
        - person
        - face
detectors:
  coral_pci:
    type: edgetpu
    device: pci

ffmpeg:
  global_args: -hide_banner -loglevel info
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detect:
  stationary:
    interval: 40
    max_frames:
      default: 3000 # Default forever

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .75
    car:
      min_score: .65
      threshold: .85

motion:
  threshold: 35
  lightning_threshold: 0.8
  contour_area: 15

record:
  enabled: true
  expire_interval: 300    # reduce the frequency of deleting recording segments
  sync_recordings: true
  retain:
    days: 1 # segments will be deleted from the cache if no events are in progress.
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 2
      mode: active_objects

snapshots:
  enabled: false
  retain:
    default: 3
    objects:
      person: 5
      face: 5
  timestamp: false
  bounding_box: true
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  #height: 720
  # Optional: Set the encode quality of the live stream (default: 8)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

birdseye:
  enabled: true
  mode: objects

logger:
  default: warning
  logs:
    frigate.mqtt: warning
    frigate.nginx: warning
#    peewee.sqliteq: warning
#    peewee: warning
#    ffmpeg.fr_frontside: debug
#    frigate.record: debug
#    frigate.event: debug
version: 0.14
camera_groups:
  Utomhus:
    order: 1
    icon: LuLogOut
    cameras:
      - fr_baksidan
      - fr_framsida
  Köket:
    order: 2
    icon: LuBanana
    cameras:
      - fr_hallen
      - fr_kitchen
  Vrum_och_Altan:
    order: 3
    icon: LuBaby
    cameras:
      - fr_vardagsrum
      - fr_baksidan
```

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate --privileged --restart=always \
       --mount type=tmpfs,target=/tmp/cache,tmpfs-size=2147483648 \
       --device /dev/apex_0:/dev/apex_0 --device /dev/dri/renderD128 \
       --shm-size=64m \
       -v $FRIGATE_MEDIA_PATH:/media/frigate \
       -v $FRIGATE_BASE/config.yml:/config/config.yml \
       -v /etc/localtime:/etc/localtime:ro \
       -e FRIGATE_RTSP_PASSWORD="$FRIGATE_PSW" \
       -e PLUS_API_KEY=$FRIGATE_PLUS \
       -p 5555:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp \
       ghcr.io/blakeblackshear/frigate:stable
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Lots

### Screenshots of the Frigate UI's System metrics pages

![bild](https://github.com/user-attachments/assets/a56caa30-3693-4644-b4fe-2bf51c218f0b)
