### DISCUSSION TITLE
[Development]: (Semantic Search) Event description only shows in "Find Similar" tracked object

### DISCUSSION THREAD

**Discussion by nwish** [blakeblackshear/frigate#13723] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

On the "Explore" page, event descriptions are only displaying after using "Find Similar", then finding the event again there.  I just pulled 641f124, but I've been testing semantic search with Gemini for a few days now.  Freaking awesome work guys.  

Anyway, so to reproduce this, you'd go to Explore, then pick a tracked object.  No event description is shown.  After selecting "Find Similar" then tracking down the same event there, the event description from Gemini will be shown.  See screenshots:

Tracked object first selected from Explore page:
![image](https://github.com/user-attachments/assets/697aa1e1-5d3a-4026-be96-0136bdfd9595)

After selecting "Find Similar" and selecting the same tracked object:
![image](https://github.com/user-attachments/assets/161a7a8b-1ce6-4fb3-bec1-5c3832a0e159)

### Steps to reproduce

1. Navigate to Explore page
2. Choose a tracked object
3. Notice that there is no description of event
4. Choose "Find Similar"
5. Find same tracked object
6. Notice that there is now a description from Gemini

### Version

0.15.0-641f124

### In which browser(s) are you experiencing the issue with?

Google Chrome Version 128.0.6613.138

### Frigate config file

```yaml
I don't know that it's relevant, but please let me know if it's needed.
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:0.13.2
    image: ghcr.io/blakeblackshear/frigate:641f124
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
      - /dev/dri/card0
      #- /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config/:/config/
      - /mnt/wd3tb/frigate/storage:/media
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - LIBVA_DRIVER_NAME=i965
      - PLUS_API_KEY=***
    ports:
      - 8971:8971
      - 5000:5000
      - 8554:8554
      - 1935:1935 # RTMP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Mashup of several brands/models

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/cb0770bb-6094-4ef2-9ced-ee3f9b51f4a8)
![image](https://github.com/user-attachments/assets/530cd36c-7018-425a-86be-f2b954e9e17f)
