### DISCUSSION TITLE
False detection of stationary objects

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#13734] [Ask A Question] [answered]
Hi.

I noticed that my frigate detects (stores) stationary objects.
Example:

![Nathalie-1726307500 857294-nylj0x](https://github.com/user-attachments/assets/d6082bf2-a963-4758-b4f6-9c1c19ee4a92)
https://github.com/user-attachments/assets/ed0ab08f-c077-4f2d-a9e3-e331e5af0f18

![Jedilnica-1726306760 599083-2h17g3](https://github.com/user-attachments/assets/f3d74e72-36eb-47ff-9446-ca6b259e20d2)
https://github.com/user-attachments/assets/04c70a3a-dfa6-4302-8eb8-bc93f04eb175

`Frigate Configuration sample`
```yaml
#*****************************************************************************************************************************************
#                                                                                             CAMERAS
#*****************************************************************************************************************************************
cameras:                                                
#*****************************************************************************************************************************************
#                             Camera-Dining room
#*****************************************************************************************************************************************
  Jedilnica:                                            
    enabled: true                                       
    ffmpeg:                                             
      inputs:                                           
        - path: rtsp://192.168.1.42:8554/Jedilnica-HD      
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 1  
    
#***************************************************
# DETECT
#***************************************************
    detect:                 
      enabled: true         
      width: 1920            
      height: 1080          
      fps: 10

#***************************************************
# OBJECTS
#***************************************************
    objects:                                
      track:                                
        - person
        - car
        - bicycle
        - motorcycle
      filters:                              
        person:
          threshold: 0.65                    
        car:
          threshold: 0.65
        bicycle:
          threshold: 0.65
        motorcycle:
          threshold: 0.65

#***************************************************
# MOTION
#***************************************************
    motion:
      threshold: 30
      contour_area: 10 
      frame_height: 50  
      improve_contrast: 'true' 

#***************************************************
# RECORD
#***************************************************
    record:                 
      enabled: true
      retain:               
        days: 3             
        mode: active_objects
      events:
        pre_capture: 2
        post_capture: 5
        retain:
          default: 3
          mode: active_objects
        
#***************************************************
# SNAPSHOTS
#***************************************************
    snapshots:              
      enabled: true           
      timestamp: true       
      bounding_box: true    
      crop: true            
      retain:               
        default: 3   
```

For some settings, I don't know if they are set correctly. 
`If anyone has any ideas I would be grateful for the help`

**Comment by hawkeye217** [comment]
Frigate tracks stationary objects by design.

https://docs.frigate.video/configuration/stationary_objects/

**Reply by Trzinka** [reply]
Thanks for the reply.

On the link you wrote, it says, among other things, `This serves to reduce resource usage and redundant detections when there has been no motion near the tracked object.`

Does this mean that the Frigate also monitors the changing datetime record (top left)?
![Jedilnica-1726306760 599083-2h17g3-TimeDate](https://github.com/user-attachments/assets/01cefea1-5599-4c5f-9c74-fa9be2ca5551)

Because where it is marked with an X, not only does the object not move, but it is also misrecognized.
![20240912-Frigate](https://github.com/user-attachments/assets/a0736824-e732-4c2b-aeba-849fb28be75f)
![Frigate-Nathalie_Not person](https://github.com/user-attachments/assets/50f27d04-4018-4739-a174-38f317acd453)
![Frigate-Nathalie_person](https://github.com/user-attachments/assets/bf199ac9-40a9-44a1-851b-64f7959d949a)


As far as I've noticed Frigate can't detect multiple moving objects at the same time either!?

**If the answer to the previous question is positive (date time), how can I extract this part from the observation?**

Thank you.

**Comment by Trzinka** [comment]
Thanks for the reply.

On the link you wrote, it says, among other things, `This serves to reduce resource usage and redundant detections when there has been no motion near the tracked object.`

Does this mean that the Frigate also monitors the changing datetime record (top left)?
![Jedilnica-1726306760 599083-2h17g3-TimeDate](https://github.com/user-attachments/assets/01cefea1-5599-4c5f-9c74-fa9be2ca5551)

Because where it is marked with an X, not only does the object not move, but it is also misrecognized.
![20240912-Frigate](https://github.com/user-attachments/assets/a0736824-e732-4c2b-aeba-849fb28be75f)
![Frigate-Nathalie_Not person](https://github.com/user-attachments/assets/50f27d04-4018-4739-a174-38f317acd453)
![Frigate-Nathalie_person](https://github.com/user-attachments/assets/bf199ac9-40a9-44a1-851b-64f7959d949a)


As far as I've noticed Frigate can't detect multiple moving objects at the same time either!?

**If the answer to the previous question is positive (date time), how can I extract this part from the observation?**

Thank you.

**Reply by Trzinka** [reply]
I did the following:
I marked:
![Frigate-Mask](https://github.com/user-attachments/assets/b5fe5682-2aa4-4407-8389-855c7672d1b4)
Which added to `frigate.yaml` under `motion:`
```yaml
 mask: 0.005,0.013,0.255,0.013,0.256,0.056,0.007,0.059
```

Under Motion tuner I can see:
![Frigate-Motion tuner](https://github.com/user-attachments/assets/1a737fdc-b111-482d-b032-5af658412b37)

And under Debug I can see:
![Frigate-Debug](https://github.com/user-attachments/assets/3dff280d-1ae0-4f4e-b13d-fdbe44455c5e)

In map media\frigate\clips still getting it
![Nathalie-1726389690 762694-ehcuad](https://github.com/user-attachments/assets/ca7cf6aa-a0cb-46f5-9fbc-7757e1c61cfc)
which is a falsely detected object and not moving?

Did I correctly add that it doesn't track movements in the field marked as `Mask`!?

**Reply by Trzinka** [reply]
**How stupid am I!!!!?????**

_I did not restart Frigate after setting `Mask`. I've fixed it now._

**Reply by Trzinka** [reply]
After a few more corrections/adjustments, I now have, in addition to `mask: date, time':
![20240915-Frigate-Di](https://github.com/user-attachments/assets/14b9448b-4628-467e-9379-56b2ffe0ed53)

and
![20240915-Frigate-Nati](https://github.com/user-attachments/assets/bcc3ff35-c2cf-415d-a4dc-4d9ec0d2485e)

`So far, it looks promising.`

**Reply by Trzinka** [reply]
WHAT HAPPENED HERE???

Falsely detected moving object (car)
![Diane-1726394557 123849-mvyzgu](https://github.com/user-attachments/assets/a03b5ae9-cf0d-4d9d-ac95-b3726952a212)

https://github.com/user-attachments/assets/9d16194e-a84b-49c7-9c28-bd1586bf68ca

**Reply by Trzinka** [reply]
ANOTHER EXAMPLE ?????

![Diane-1726397610 269556-wfcabb](https://github.com/user-attachments/assets/fb52fd56-8c7b-436b-ac45-e35c4624ff38)

https://github.com/user-attachments/assets/907218f4-80a0-4384-9b70-c7e435ff7dd7

**Reply by hawkeye217** [reply, marked as answer]
The car was part of a region that Frigate scanned for objects, because there was motion near it. Read this to understand how Frigate uses motion detection: https://docs.frigate.video/configuration/masks/#further-clarification

Also, related to another question you asked earlier: your thresholds are set fairly low from the defaults, so you are getting some false positives. See the docs: https://docs.frigate.video/configuration/object_filters/#object-shape

**Reply by Trzinka** [reply]
Hi. Thanks again.

After specifying `mask (date, time)` and incrementing:
```yaml
 objects:
 tracks:
 - person
 - Tsar
 - bicycle
 - motorcycle
 filters:
 person:
 threshold: 0.72
 Emperor:
 threshold: 0.72
 bicycles:
 threshold: 0.72
 motorcycles:
 threshold: 0.72
```
now I have much fewer false or false perceptions of objects!!!

**Thanks for the direction!**
