### DISCUSSION TITLE
[Support]: Driveway Parked Car Alerts

### DISCUSSION THREAD

**Discussion by spikked27** [blakeblackshear/frigate#13732] [General Support]
### Describe the problem you are having

I've created alert zones for my driveway per the docs with a small area at the entry with alerts for cars included and the overall driveway without cars enabled, even though the parked car is recognized as remaining in the non-alert zone I get events every few minutes.  Creating a car object mask in the driveway helps but I don't feel this is the correct solution.  Any help is appreciated!

### Version

0.14.1

### What browser(s) are you using?

Chrome on Android

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.107
  port: 1883
  user: 
  password:
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

tls:
  enabled: false

#logger:
  #default: debug
  #logs:
  #  frigate.ffmpeg.front_door: error

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    front_door:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_main.bc#video=copy#audio=copy#audio=opus
      #- exec:./neolink/neolink_talk.sh#backchannel=1
      - rtsp://192.168.0.112:554/h264Preview_01_sub
    front_door_sub:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_ext.bcs
    front_door_snapshot:
      - onvif://192.168.0.112:8000?subtype=000&snapshot
    driveway:
      - rtsp://192.168.0.113:554/11
      - ffmpeg:driveway#audio=opus
    driveway_sub:
      - rtsp://@192.168.0.113:554/12
      - ffmpeg:driveway#audio=opus
    driveway_snapshot:
      - http://@192.168.0.113/tmpfs/auto.jpg

    webrtc:
      candidates:
        - 192.168.0.101:8555
        - stun:8555

cameras:
  front_door:
    ffmpeg:
 #     hwaccel_args: 
 #       - c:v hevc_cuvid
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_door

    motion:
      threshold: 30
      contour_area: 94
      improve_contrast: true
      mask: 
        0.974,0.497,0.973,0.478,0.975,0.4,0.936,0.171,0.874,0,0.052,0,0,0,0,0.314,0.054,0.351,0.058,0.553,0,0.545,0,0.625,0.133,0.649,0.395,0.647,0.581,0.626,0.749,0.582,0.845,0.585,0.887,0.591,0.914,0.595,0.933,0.594,0.943,0.595,0.967,0.594,0.967,0.584,0.967,0.575,0.971,0.555,0.973,0.54,0.971,0.519

    objects:
      filters:
        car:
          mask: 
            0.001,0.515,0.077,0.531,0.136,0.485,0.198,0.485,0.263,0.498,0.357,0.51,0.44,0.5,0.482,0.489,0.495,0.42,0.521,0.426,0.694,0.463,0.705,0.491,0.773,0.494,0.816,0.469,0.856,0.472,0.839,0.523,0.97,0.531,0.962,0.602,0.748,0.58,0.654,0.624,0.539,0.648,0.414,0.665,0.313,0.668,0.175,0.67,0.053,0.664,0,0.663
        person:
          mask: 
            0.001,0.515,0.077,0.531,0.136,0.485,0.198,0.485,0.213,0.537,0.42,0.534,0.504,0.529,0.482,0.489,0.486,0.456,0.694,0.463,0.705,0.491,0.773,0.494,0.816,0.469,0.856,0.472,0.839,0.523,0.97,0.531,0.962,0.602,0.748,0.58,0.65,0.609,0.535,0.631,0.41,0.645,0.312,0.65,0.175,0.653,0.048,0.64,0,0.663

    zones:
      Stoop:
        coordinates: 0.217,0.998,0.239,0.724,0.604,0.707,0.716,0.809,0.898,0.89,0.999,0.998
        loitering_time: 0
        inertia: 3
      Front_of_House:
        coordinates: 
          0.049,0.645,0.396,0.649,0.603,0.624,0.71,0.591,0.747,0.583,0.962,0.605,1,0.61,0.998,0.813,0.733,0.772,0.629,0.687,0.223,0.711,0.185,0.999,0,1,0,0.631
        loitering_time: 0

        inertia: 3
    review:
      alerts:
        required_zones: Stoop

  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: driveway

    zones:
      Front_of_House:
        coordinates: 0.466,0.459,0.69,0.434,0.748,0.425,0.746,0.484,0.744,0.548,0.564,0.509
        loitering_time: 0
        inertia: 3
      Driveway_Area:
        coordinates: 
          0.048,0.534,0.074,0.472,0.084,0.583,0.313,0.547,0.509,0.499,0.549,0.531,0.586,0.538,0.773,0.568,0.784,0.373,0.789,0.304,1,0.367,1,1,0,1,0,0.638
        inertia: 10
        loitering_time: 1
        objects:
          - bicycle
          - bird
          - cat
          - dog
          - motorcycle
          - person
          - suitcase
      Driveway_Entry:
        coordinates: 0.101,0.522,0.448,0.457,0.486,0.485,0.094,0.558
        loitering_time: 0
        inertia: 3
    motion:
      mask: 
        0,0.361,0.001,0,1,0,1,0.361,0.775,0.292,0.77,0.374,0.662,0.329,0.575,0.322,0.43,0.313,0.419,0.265,0.377,0.272,0.378,0.295,0.304,0.304,0.166,0.313
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask:
            - 0,0.301,0.17,0.259,0.289,0.236,0.379,0.238,0.427,0.268,0.466,0.281,0.507,0.285,0.505,0.161,0.669,0.176,0.767,0.199,0.76,0.422,0.527,0.441,0.445,0.449,0.417,0.438,0.298,0.451,0.223,0.463,0.163,0.478,0.118,0.484,0.087,0.493,0.055,0.506,0,0.613
            - 0.503,0.511,0,0.613,-0.002,1,1,1,1,0.477,0.781,0.439,0.775,0.579,0.54,0.562
        person:
          mask: 0.662,0.307,0.778,0.385,0.786,0.158,0.51,0.155,0.506,0.312
detect:
  width: 640
  height: 480
  fps: 4

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 5
    post_capture: 15
    retain:
      default: 182
      mode: motion
  sync_recordings: true

snapshots:
  enabled: true
  retain:
    default: 365

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - suitcase

#audio:
#  enabled: true
#  listen:
#    - bark
#    - fire_alarm
#    - scream
#    - speech
#    - yell

version: 0.14
camera_groups: {}
```

### Relevant Frigate log output

```shell
No log entries for events
```

### Relevant go2rtc log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

SV3C 5mp

### Screenshots of the Frigate UI's System metrics pages

![Screenshot_20240913_231002_Chrome Beta](https://github.com/user-attachments/assets/3dd6b1ce-01d8-46cc-9790-2d40021dd0a9)

### Any other information that may be helpful

Video of debug screen showing car stationary well within the driveway zone but I'm still getting alerts every few minutes: https://photos.app.goo.gl/2fWXJb761J2MVM8H6
