### DISCUSSION TITLE
USB Coral TPU - did mine die?

### DISCUSSION THREAD

**Discussion by Plawasan** [blakeblackshear/frigate#13741] [Detector Support] [answered]
I have (up until now) a pretty stable Frigate install, currently on 0.14.1 running on a Intel I7 NUC with Proxmox, LXC container with Debian and Frigate running as a docker container. I am passing Coral through to the LXC, it's correctly recognized by Frigate and up until last night, I had no issues with performance (with 5 cameras), inference was steadily under 10ms and the NUC (which runs a few other services, HA, Unifi etc) was running with load of typically <2, perfectly acceptable. Frigate is the most demanding service on the server by far.

I woke up to the NUC running at load 55 and frigate reporting "Coral is very slow" with inference times up to 900ms. Since then I tried
- restarting anything and everything
- reconnecting the Coral to a different USB 3.0 port
- I've also seen a couple errors where frigate couldn't keep up with the recoding cache - I've updated my mount config (recordings go to a synology NAS) to use nfs instead of cifs, I no longer see these errors but I assume they were a byproduct of the extreme load.

![image](https://github.com/user-attachments/assets/0c6137cc-965a-4172-9dc2-4caf5cf313f2)

![image](https://github.com/user-attachments/assets/f8a4bc75-0192-485f-87c5-2db55ade96c0)

For troubleshooting, I've temporarily added `detect - enabled: false`  but it doesn't really seem to make a difference, the moment I start the Frigate container load shoots up to 55-60 and the whole system becomes unusable.

Any help will be highly appreciated as I'm stuck without any CCTV right now.. thanks!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.10
  user: frigate
  password: xxxx

database:
  path: /media/frigate-db/frigate.db

# logger:
#   logs:
#     frigate.record.maintainer: debug

environment_vars:
  PLUS_API_KEY: xxx                                                                                                                                                                                                                                                                                                                                                    
  LIBVA_DRIVER_NAME: i965

record:
  enabled: true
  export:
    timelapse_args: -vf setpts=0.005*PTS -r 30
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects
      objects:
        person: 7

ui:
  time_format: 24hour

objects:
  track:
    - person
    - dog
    - cat
    - car
    - bicycle
    - motorcycle

go2rtc:
  streams:
    entry_camera:
      - rtsp://onvif:xxx@192.168.4.10:554/video1
      - ffmpeg:entry_camera#audio=aac
    entry_camera_sub:
      - rtsp://onvif:xxx@192.168.4.10:554/video2
      - ffmpeg:entry_camera_sub#audio=aac
    garden_camera:
      - rtsp://onvif:xxx@192.168.4.11:554/video1
      - ffmpeg:garden_camera#audio=aac
    garden_camera_sub:
      - rtsp://onvif:xxx@192.168.4.11:554/video2
      - ffmpeg:garden_camera_sub#audio=aac

    street_camera:
      - rtsp://onvif:xxx@192.168.4.12:554/video1
      - ffmpeg:street_camera#audio=aac
    street_camera_sub:
      - rtsp://onvif:xxx@192.168.4.12:554/video2
      - ffmpeg:street_camera_sub#audio=aac

    siderear_camera:
      - rtsp://onvif:xxx@192.168.4.13:554/video1
      - ffmpeg:siderear_camera#audio=aac
    siderear_camera_sub:
      - rtsp://onvif:xxx@192.168.4.13:554/video2
      - ffmpeg:siderear_camera_sub#audio=aac
    sidefront_camera:
      - rtsp://onvif:xxx@192.168.4.14:554/video1
      - ffmpeg:sidefront_camera#audio=aac
    sidefront_camera_sub:
      - rtsp://onvif:xxx@192.168.4.14:554/video2
      - ffmpeg:sidefront_camera_sub#audio=aac
    tapo:
      - rtsp://tapocam:xxx@192.168.4.21:554/stream1
      - ffmpeg:tapo#audio=aac

  webrtc:
    candidates:
      - 192.168.1.11:8555
      - stun:8555

cameras:
  entry_camera:
    # onvif:
    #     host: 192.168.4.10
    #     port: 2020
    #     user: onvif
    #     password: xxxx
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entry_camera
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/entry_camera_sub
          roles:
            - detect

    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    ui:
      order: 1
    birdseye:
      order: 1

    zones:
      front_entry:
        coordinates:
          0.988,0.424,0.949,0.711,0.888,0.997,0.153,0.997,0.088,0.811,0.407,0.41                                                                                                                                                                                                                                                                                                                                                           2,0.739,0.634,0.848,0.353
        inertia: 3
        filters:
          person:
            min_area: 20000
      front_garden:
        coordinates:
          0.086,0.792,0.389,0.42,0.576,0.205,0.563,0.026,0.397,0.025,0.282,0.083                                                                                                                                                                                                                                                                                                                                                           ,0.094,0.218,0.003,0.292,0.003,0.424
        inertia: 3
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones:
          - front_entry
          - front_garden
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
      mask: 0.606,-0.002,0.998,-0.002,1,0.222,1,0.417,0.618,0.225

street_camera:
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street_camera
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/street_camera_sub
          roles:
            - detect

    ui:
      order: 2
    birdseye:
      order: 2

    zones:
      front_garage:
        coordinates:
          0.375,0.586,0.542,0.684,0.753,0.798,0.895,0.863,0.874,1,0,1,0,0.485,0.                                                                                                                                                                                                                                                                                                                                                           063,0.732,0.134,0.922,0.206,0.825
        inertia: 3
      front_entry:
        coordinates: 0.027,0.597,0.159,0.427,0.379,0.589,0.324,0.663,0.134,0.924                                                                                                                                                                                                                                                                                                                                                           ,0.05,0.687
        inertia: 3
      front_street:
        coordinates:
          0.912,0.846,0.896,1,1,1,1,0.266,0.907,0.224,0.756,0.181,0.595,0.166,0.                                                                                                                                                                                                                                                                                                                                                           458,0.149,0.32,0.161,0.267,0.2,0.201,0.255,0.227,0.281,0.27,0.362,0.277,0.5,0.48                                                                                                                                                                                                                                                                                                                                                           2,0.629
        inertia: 3
        loitering_time: 4
    review:
      alerts:
        required_zones:
          - front_garage
          - front_entry
      detections:
        required_zones: front_street
    motion:
      mask:
        0.307,0.157,0.575,0.154,0.837,0.192,0.998,0.25,0.998,-0.002,0,0,0,0.414,                                                                                                                                                                                                                                                                                                                                                           0.144,0.269
  garden_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_camera_sub
          roles:
            - detect

    ui:
      order: 3
    birdseye:
      order: 3

    zones:
      back_garden:
        coordinates:
          0.155,1,0.12,0.503,0.086,0.505,0.089,0.257,0.092,0.058,0.483,0.053,0.7                                                                                                                                                                                                                                                                                                                                                           76,0.038,0.841,0.145,0.962,0.375,1,0.445,1,1,0.78,1
        objects:
          - person
          - dog
          - cat
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: back_garden
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
      mask:
        0.083,0.504,0.093,0.028,0.322,0.032,0.57,0.032,0.779,0.023,0.91,0.242,1,                                                                                                                                                                                                                                                                                                                                                           0.4,1,0,0,0,0,1,0.155,1,0.12,0.502
  siderear_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/siderear_camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/siderear_camera_sub
          roles:
            - detect

    ui:
      order: 4
    birdseye:
      order: 4

    zones:
      side_garden:
        coordinates: 0,1,0,0.124,0.259,0.063,0.62,0.07,0.805,0.45,0.482,1
        objects:
          - cat
          - dog
          - person
        inertia: 3
      front_garden:
        coordinates: 0.811,0.071,0.618,0.065,0.81,0.451,0.909,0.278
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones:
          - side_garden
          - front_garden
    motion:
      mask: 0.903,0,0.952,0.101,0.942,0.122,0.971,0.176,1,0.118,1,0
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'

  sidefront_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sidefront_camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sidefront_camera_sub
          roles:
            - detect

    ui:
      order: 5
    birdseye:
      enabled: false

    zones:
      side_garden:
        coordinates: 0.227,0.805,0.344,0.048,0.68,0.034,1,0.061,1,1,0.572,1
        objects:
          - cat
          - dog
          - person
        inertia: 3
      back_garden:
        coordinates: 0.023,0.669,0.225,0.8,0.339,0.052,0.206,0.071,0.144,0.084
        inertia: 3
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones:
          - side_garden
          - back_garden
    motion:
      threshold: 50
      contour_area: 40
      improve_contrast: 'true'


  tapo:
    onvif:
      host: 192.168.4.21
      port: 2020
      user: tapocam
      password: xxx

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo

    ui:
      order: 10
    birdseye:
      enabled: false

    detect:
      enabled: false
      # width: 2304
      # height: 1296

    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'

########################################################

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi

birdseye:
  enabled: true
  mode: continuous
  restream: true

detectors:
  coral:
    type: edgetpu
    device: usb

camera_groups:
  External:
    order: 1
    icon: LuTrees
    cameras:
      - entry_camera
      - garden_camera
      - sidefront_camera
      - siderear_camera
      - street_camera

  Babycam:
    order: 2
    icon: LuBaby
    cameras:
      - tapo

  Garden:
    order: 3
    icon: LuFlower2
    cameras:
      - sidefront_camera
      - siderear_camera
      - garden_camera
version: 0.14
```


### docker-compose file or Docker CLI command

```yaml
services:  
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    restart: always
    shm_size: "1GB"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/frigate/config.yml:/config/config.yml
      - /mnt/cctv:/media/frigate
      - /mnt/frigate-db:/media/frigate-db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
           size: 1500000000      
    ports:
      - 5000:5000
      - 1935:1935
      - 1984:1984 #- direct go2rtc access
      - 8555:8555/tcp
      - 8555:8555/udp  
      - 8554:8554/tcp
      - 8554:8554/udp  

    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
```


### Relevant Frigate log output

```shell
2024-09-14 16:54:10.442348106  [2024-09-14 16:54:10] peewee_migrate.logs            INFO    : Starting migrations
2024-09-14 16:54:10.442581764  [2024-09-14 16:54:10] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-14 16:54:10.960131656  [2024-09-14 16:54:10] frigate.app                    INFO    : Recording process started: 479
2024-09-14 16:54:10.969564481  [2024-09-14 16:54:10] frigate.app                    INFO    : Recording process started: 481
2024-09-14 16:54:10.975739569  [2024-09-14 16:54:10] frigate.app                    INFO    : go2rtc process pid: 98
2024-09-14 16:54:11.020955518  [2024-09-14 16:54:11] detector.coral                 INFO    : Starting detection process: 508
2024-09-14 16:54:11.025571992  [2024-09-14 16:54:11] frigate.app                    INFO    : Output process started: 510
2024-09-14 16:54:11.478369075  [2024-09-14 16:54:11] frigate.comms.dispatcher       INFO    : Turning off recordings for tapo
2024-09-14 16:54:11.512100691  [2024-09-14 16:54:11] frigate.comms.dispatcher       INFO    : Turning on snapshots for entry_camera
2024-09-14 16:54:11.615093770  [2024-09-14 16:54:11] frigate.app                    INFO    : Camera processor started for entry_camera: 564
2024-09-14 16:54:11.620619562  [2024-09-14 16:54:11] frigate.app                    INFO    : Camera processor started for street_camera: 567
2024-09-14 16:54:11.642969451  [2024-09-14 16:54:11] frigate.app                    INFO    : Camera processor started for garden_camera: 578
2024-09-14 16:54:11.678598617  [2024-09-14 16:54:11] frigate.app                    INFO    : Camera processor started for siderear_camera: 583
2024-09-14 16:54:11.685546279  [2024-09-14 16:54:11] frigate.app                    INFO    : Camera processor started for sidefront_camera: 591
2024-09-14 16:54:11.709783168  [2024-09-14 16:54:11] frigate.app                    INFO    : Camera processor started for tapo: 602
2024-09-14 16:54:11.727717862  [2024-09-14 16:54:11] frigate.app                    INFO    : Capture process started for entry_camera: 605
2024-09-14 16:54:11.745424562  [2024-09-14 16:54:11] frigate.app                    INFO    : Capture process started for street_camera: 613
2024-09-14 16:54:11.768328267  [2024-09-14 16:54:11] frigate.app                    INFO    : Capture process started for garden_camera: 620
2024-09-14 16:54:11.795574799  [2024-09-14 16:54:11] frigate.app                    INFO    : Capture process started for siderear_camera: 628
2024-09-14 16:54:11.821533627  [2024-09-14 16:54:11] frigate.app                    INFO    : Capture process started for sidefront_camera: 634
2024-09-14 16:54:11.854287773  [2024-09-14 16:54:11] frigate.app                    INFO    : Capture process started for tapo: 640
2024-09-14 16:54:11.862644618  [2024-09-14 16:54:11] frigate.app                    INFO    : Audio process started: 646
2024-09-14 16:54:13.883083569  [2024-09-14 16:54:11] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-09-14 16:54:13.886931429  [2024-09-14 16:54:13] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```


### Relevant go2rtc log output

```shell
2024-09-14 16:58:54.651947464  [INFO] Preparing new go2rtc config...
2024-09-14 16:58:55.429068160  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-09-14 16:58:55.488977606  [INFO] Starting go2rtc...
2024-09-14 16:58:55.848259247  16:58:55.848 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-14 16:58:55.848298854  16:58:55.848 INF config path=/dev/shm/go2rtc.yaml
2024-09-14 16:58:55.849477510  16:58:55.849 INF [api] listen addr=:1984
2024-09-14 16:58:55.850057718  16:58:55.849 INF [rtsp] listen addr=:8554
2024-09-14 16:58:55.851030721  16:58:55.850 INF [webrtc] listen addr=:8555
2024-09-14 16:59:04.644475436  [INFO] Starting go2rtc healthcheck service...
```


### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c780261a-f55e-4f0d-87e0-168eb84b1026)


### Any other information that may be helpful

top

```
root@docker /home/frigate# top
top - 16:55:17 up 39 min,  1 user,  load average: 33.90, 11.19, 9.94
Tasks: 136 total,  27 running, 109 sleeping,   0 stopped,   0 zombie
%Cpu(s): 62.2 us, 28.1 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  9.7 si,  0.0 st
MiB Mem :   8192.0 total,   3964.5 free,   1666.6 used,   2561.0 buff/cache
MiB Swap:    512.0 total,    512.0 free,      0.0 used.   6102.0 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  10496 root      20   0 1241136  38856      0 S  43.8   0.5   0:25.91 /usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml
  11145 root      20   0  177260  20608  16512 R  19.6   0.2   0:05.83 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/garden_camera_sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/2e0b9d97a4e171dff4789193172d4c7a
  11229 root      20   0  177388  21120  16768 R  18.2   0.3   0:05.58 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/tapo?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b7ef344d8710cc60fb3c292b67458e7c
   1197 root      20   0 1251616  39524  21248 S  14.6   0.5   1:54.90 tailscaled
  11177 root      20   0  177260  20992  16768 R  13.1   0.3   0:05.07 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/sidefront_camera?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6ee7e2e42ed2189d88c0e4c9610d13eb
  10514 root      20   0 3628052 316564  91268 S  11.9   3.8   0:13.16 python3 -u -m frigate
  10976 root      20   0 3049180 165072  23748 R  11.9   2.0   0:13.07 frigate.output
  11151 root      20   0  177260  20608  16512 R  11.6   0.2   0:05.15 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/garden_camera?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/dbd34827d92617db47320755c1a7c5ff
  11146 root      20   0  177260  20736  16512 R  10.7   0.2   0:05.39 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/street_camera?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/dabbe571c9b18396438802ce8a1a2a67
  11096 root      20   0  130888  24208  17024 R  10.1   0.3   0:05.01 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11071 root      20   0 2117080 182248   6872 S   9.8   2.2   0:04.34 frigate.capture:entry_camera
  11094 root      20   0 2117080 182804   7072 S   9.8   2.2   0:04.09 frigate.capture:siderear_camera
  11100 root      20   0 2117080 182592   6840 S   9.2   2.2   0:04.07 frigate.capture:sidefront_camera
  11155 root      20   0  177260  21376  17024 R   9.2   0.3   0:04.38 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/siderear_camera?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/247f26a221c9aebc50ca2a11fbc2f2bc
  11079 root      20   0 2117080 181808   6148 S   8.6   2.2   0:04.11 frigate.capture:street_camera
  11107 root      20   0  465188  41000  22524 R   8.6   0.5   0:03.20 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11134 root      20   0  177260  20736  16640 R   8.3   0.2   0:05.22 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/street_camera_sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/352f7bcecf2d550ceb8898ecf4a89c1a
  11086 root      20   0 2117080 182800   7096 S   8.0   2.2   0:04.35 frigate.capture:garden_camera
  10974 root      20   0 1539156 163344  19972 R   7.7   1.9   0:08.64 frigate.detector.coral
  11137 root      20   0  177260  20992  16896 R   7.7   0.3   0:03.36 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/entry_camera_sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/2de84779ad458e12afcb032826501b72
  11144 root      20   0  177388  20992  16896 R   7.7   0.3   0:05.01 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/siderear_camera_sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/18d1654ee814094b470a3ac8d56b4e7c
  11150 root      20   0  177260  20736  16512 R   7.7   0.2   0:04.58 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/sidefront_camera_sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9a4f674a48f6e4c4cd7d31ff8cbb437b
  11122 root      20   0  130964  24980  17792 R   7.4   0.3   0:04.57 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  10945 root      20   0 1319356 180260  18692 S   7.1   2.1   0:06.77 frigate.recording_manager
  11093 root      20   0  131376  24532  17024 R   6.5   0.3   0:04.31 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11148 root      20   0  177260  20992  16768 S   6.2   0.3   0:03.15 ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/entry_camera?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/cf37d46e8a5f9eb12954eca8518c323d
  11095 root      20   0  466512  49668  22272 R   5.7   0.6   0:03.14 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11106 root      20   0 2150344 191360   9820 S   5.7   2.3   0:04.62 frigate.capture:tapo
  11105 root      20   0  131172  24736  17280 S   5.4   0.3   0:04.73 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11114 root      20   0  131820  25276  17152 R   5.4   0.3   0:04.10 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11080 root      20   0  464528  42332  22668 R   5.1   0.5   0:03.19 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11102 root      20   0  466660  45436  22648 R   5.1   0.5   0:02.98 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11085 root      20   0  464996  44792  21896 S   4.8   0.5   0:03.04 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0+
  11143 root      20   0  130564  24220  17536 R   4.8   0.3   0:04.21 ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/street_camera -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:
   1199 systemd+  20   0 2635292 174560  62080 S   4.5   2.1   0:52.18 mongod --bind_ip_all
```

Hardware Info:

`{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:Inteli965driverforIntel(R)CoffeeLake-2.4.1nvainfo:SupportedprofileandentrypointsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileH264MultiviewHigh:tVAEntrypointVLDnVAProfileH264MultiviewHigh:tVAEntrypointEncSlicenVAProfileH264StereoHigh:tVAEntrypointVLDnVAProfileH264StereoHigh:tVAEntrypointEncSlicenVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileNone:tVAEntrypointVideoProcnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile0:tVAEntrypointEncSlicenVAProfileVP9Profile2:tVAEntrypointVLD"}`

lsusb (relevant bits)

```
root@docker /home/frigate# lsusb
Bus 002 Device 005: ID 18d1:9302 Google Inc.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
root@docker /home/frigate# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
    |__ Port 2: Dev 5, If 0, Class=Vendor Specific Class, Driver=, 5000M
```
