### DISCUSSION TITLE
[Detector Support]: libnvjpeg.so not found on Jetson AGX Xavier with stable-tensorrt-jp5 image

### DISCUSSION THREAD

**Discussion by dustin-richards-was-here** [blakeblackshear/frigate#13742] [Detector Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Not able to start `ffmpeg` at all (at least in Bash in no arguments) on the `stable-tensorrt-jp5` image running on a Jetson AGX Xavier. Cannot get hardware acceleration to work. Mysteriously, `ffmpeg` appears to run fine when started by Frigate to decode video streams. I was trying to run `ffmpeg -decoders | grep nvmpi` as [mentioned in the docs](https://docs.frigate.video/configuration/hardware_acceleration#setup-decoder-1) when I noticed this.

### Steps to reproduce

1. On host: `sudo docker run -it --entrypoint bash ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp5`
2. In container: `ffmpeg`
3. Output: `ffmpeg: error while loading shared libraries: libnvjpeg.so: cannot open shared object file: No such file or directory`

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

_No response_

### Frigate config file

```yaml
mqtt:
  enabled: false

auth:
  enabled: false

detect:
  enabled: false

birdseye:
  enabled: true
  mode: motion

record:
  enabled: true
  retain:
    days: 7
    mode: motion

motion:
  mask: 0.024,0.103,0.284,0.099,0.278,0.039,0.025,0.039

cameras:
  camera1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://camera1.rnd.xyz/ch0_1.h264
          roles:
            - audio
            - detect
            - record
  camera2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://camera2.rnd.xyz/ch0_1.h264
          roles:
            - audio
            - detect
            - record
  camera4:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://camera4.rnd.xyz/ch0_1.h264
          roles:
            - audio
            - detect
            - record
  camera5:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://camera5.rnd.xyz/ch0_1.h264
          roles:
            - audio
            - detect
            - record
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuAsterisk
    cameras: birdseye
```


### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp5
    runtime: nvidia
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/dustin/frigate/config:/config
      - /home/dustin/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8553:8554" # RTSP feeds
      - "8556:8555/tcp" # WebRTC over tcp
      - "8556:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```


### Relevant Frigate log output

```shell
frigate    | s6-rc: info: service s6rc-fdholder: starting                                                                                                                                                                                                                                                                     
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting                                                                                                                                                                                                                                                               
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started                                                                                                                                                                                                                                                    
frigate    | s6-rc: info: service fix-attrs: starting                                                                                                                                                                                                                                                                         
frigate    | s6-rc: info: service s6rc-fdholder successfully started                                                                                                                                                                                                                                                          
frigate    | s6-rc: info: service fix-attrs successfully started                                                                                                                                                                                                                                                              
frigate    | s6-rc: info: service legacy-cont-init: starting                                                                                                                                                                                                                                                                  
frigate    | s6-rc: info: service legacy-cont-init successfully started                                                                                                                                                                                                                                                       
frigate    | s6-rc: info: service trt-model-prepare: starting                                                                                                                                                                                                                                                                 
frigate    | s6-rc: info: service log-prepare: starting                                                                                                                                                                                                                                                                       
frigate    | s6-rc: info: service log-prepare successfully started                                                                                                                                                                                                                                                            
frigate    | No models to convert.                                                                                                                                                                                                                                                                                            
frigate    | s6-rc: info: service nginx-log: starting                                                                                                                                                                                                                                                                         
frigate    | s6-rc: info: service go2rtc-log: starting                                                                                                                                                                                                                                                                        
frigate    | s6-rc: info: service frigate-log: starting                                                                                                                                                                                                                                                                       
frigate    | s6-rc: info: service certsync-log: starting                                                                                                                                                                                                                                                                      
frigate    | s6-rc: info: service trt-model-prepare successfully started                                                                                                                                                                                                                                                      
frigate    | s6-rc: info: service go2rtc-log successfully started                                                                                                                                                                                                                                                             
frigate    | s6-rc: info: service go2rtc: starting                                                                                                                                                                                                                                                                            
frigate    | s6-rc: info: service frigate-log successfully started                                                                                                                                                                                                                                                            
frigate    | s6-rc: info: service certsync-log successfully started                                                                                                                                                                                                                                                           
frigate    | s6-rc: info: service nginx-log successfully started                                                                                                                                                                                                                                                              
frigate    | s6-rc: info: service go2rtc successfully started                                                                                                                                                                                                                                                                 
frigate    | s6-rc: info: service go2rtc-healthcheck: starting                                                                                                                                                                                                                                                                
frigate    | s6-rc: info: service frigate: starting                                                                                                                                                                                                                                                                           
frigate    | s6-rc: info: service frigate successfully started                                                                                                                                                                                                                                                                
frigate    | s6-rc: info: service nginx: starting                                                                                                                                                                                                                                                                             
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started                                                                                                                                                                                                                                                     
frigate    | 2024-09-14 11:16:44.377115960  [INFO] Preparing Frigate...                                                                                                                                                                                                                                                       
frigate    | 2024-09-14 11:16:44.396507740  [INFO] Starting NGINX...                                                                                                                                                                                                                                                          
frigate    | 2024-09-14 11:16:44.447337415  [INFO] Preparing new go2rtc config...                                                                                                                                                                                                                                             
frigate    | 2024-09-14 11:16:44.478181809  [INFO] Starting Frigate...                                                                                                                                                                                                                                                        
frigate    | 2024-09-14 11:16:45.497601258  [INFO] Starting go2rtc...                                                                                                                                                                                                                                                         
frigate    | 2024-09-14 11:16:45.674754186  11:16:45.674 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2                                                                                                                                                                                                       
frigate    | 2024-09-14 11:16:45.674767499  11:16:45.674 INF config path=/dev/shm/go2rtc.yaml                                                                                                                                                                                                                                 
frigate    | 2024-09-14 11:16:45.676913938  11:16:45.676 INF [rtsp] listen addr=:8554                                                                                                                                                                                                                                         
frigate    | 2024-09-14 11:16:45.677892417  11:16:45.677 INF [webrtc] listen addr=:8555/tcp                                                                                                                                                                                                                                   
frigate    | 2024-09-14 11:16:45.678756299  11:16:45.677 INF [api] listen addr=:1984                                                                                                                                                                                                                                          
frigate    | s6-rc: info: service nginx successfully started                                                                                                                                                                                                                                                                  
frigate    | s6-rc: info: service certsync: starting                                                                                                                                                                                                                                                                          
frigate    | s6-rc: info: service certsync successfully started                                                                                                                                                                                                                                                               
frigate    | s6-rc: info: service legacy-services: starting                                                                                                                                                                                                                                                                   
frigate    | 2024-09-14 11:16:45.717852193  [INFO] Starting certsync...                                                                                                                                                                                                                                                       
frigate    | s6-rc: info: service legacy-services successfully started                                                                                                                                                                                                                                                        
frigate    | 2024-09-14 11:16:45.942977154  127.0.0.1 - - [14/Sep/2024:11:16:45 -0500] "" 400 0 "-" "-" "-"                                                                                                                                                                                                                   
frigate    | 2024-09-14 11:16:49.035136407  [2024-09-14 11:16:49] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)                                                                                                                                                                                  
frigate    | 2024-09-14 11:16:49.035754261  [2024-09-14 11:16:49] frigate.util.config            INFO    : Checking if frigate config needs migration...                                                                                                                                                                      
frigate    | 2024-09-14 11:16:49.079143096  [2024-09-14 11:16:49] frigate.util.config            INFO    : frigate config does not need migration...                                                                                                                                                                          
frigate    | 2024-09-14 11:16:49.440218740  [2024-09-14 11:16:49] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
```


### Relevant go2rtc log output

```shell
Not relevant?
```


### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Yi with Yi-Hack

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/0faaa04d-a0e7-4487-90e3-1370c6aa75c1)
![image](https://github.com/user-attachments/assets/b6557a51-2a9d-46fb-aa15-d03fab01a3d9)
![image](https://github.com/user-attachments/assets/bf964225-519e-415e-8f15-3c5f925426e7)


### Any other information that may be helpful

_No response_

**Comment by dustin-richards-was-here** [comment]
I should note, this is on a slightly hacky OS setup. I flashed this Jetson with Ubuntu 20.04, then `do-release-upgrade`'d to 22.04 since 20.04 is the newest I could flash to an AGX Xavier. I had to fix a couple things to get Docker to run in the first place, but I don't expect they're related to this issue:

1. `sudo update-alternatives --set iptables /usr/sbin/iptables-legacy`
2. Add `systemd.unified_cgroup_hierarchy=0` to kernel commandline

**Comment by NickM-27** [comment]
This is not a bug, the host has to provide the drivers

**Reply by dustin-richards-was-here** [reply]
Thank you! Do you ever get tired of telling people "this is not a bug"? 

I'll poke around and see what I can figure out.

**Comment by dustin-richards-was-here** [comment, marked as answer]
For posterity, this was a result of a couple things:
1. The `docker run` command I was using doesn't attach to an existing container or use the config from `docker-compose.yml`, so of course `libnvjpeg` couldn't be found since nothing was being passed on from the host. This explains why `ffmpeg` started without issue when running via `docker-compose up`. 100% PEBCAK.
2. Another one of my concerns was the `WARNING : Did not detect hwaccel ...` at the bottom of the Frigate log. This was a result of my `hwaccel_args: preset-jetson-h264` being listed individually for each camera. Creating a root `ffmpeg:` entry with the `hwaccel_args:` as a child fixed this.

An additional thing I did to get detection running on my Xavier was to set up the detector and model parameters, nice and simple, as [described in the docs](https://docs.frigate.video/configuration/object_detectors/#configuration-parameters).
```yaml
detectors:
  tegra:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```
