### DISCUSSION TITLE
Corrupted video

### DISCUSSION THREAD

**Discussion by tve** [blakeblackshear/frigate#1374] [Ask A Question] [answered]
I have a Phylink PLC-335PW camera and the video feed is giving me trouble. I'm using a 768x432 H.264 RTSP stream and when I look at the camera live view in frigate I frequently see crap. The motion bounding boxes seem to bound the bad areas, so I suspect the corruption happens before motion detection. If I run mpv on the same stream from the camera at the same time it looks perfect. Where should I look for troubleshooting?

Here's what the corruption looks like:
![image](https://user-images.githubusercontent.com/39480/125368402-fac2c000-e32e-11eb-8194-77f5e49c7112.png)
I sometimes see errors in the log, but often the image is corrupted without error messages:
```
[h264 @ 0x55cab97bbf00] out of range intra chroma pred mode
[h264 @ 0x55cab97bbf00] error while decoding MB 32 18
[h264 @ 0x55e742cd8f00] P sub_mb_type 32 out of range at 6 7
[h264 @ 0x55c000cd2f00] negative number of zero coeffs at 41 18
```

**Comment by tve** [comment]
Here's a similarly corrupt snapshot picture:
![image](https://user-images.githubusercontent.com/39480/125680961-87406097-1427-4471-845f-a68741a7c508.png)
the video clip also has lots of similar corruption with pieces of the image frozen and "left behind" while other parts of the image continue updating. This smells to me like an I/B/P frame issue when stitching stuff together?

**Reply by tve** [reply]
I looked at the recording that straddles this snapshot... the recording has the artifacts... so it seems that either the camera sends garbage (possibly due to wifi) or ffmpeg messes up. This snapshot is pretty smack in the middle of the recording.

**Reply by blakeblackshear** [reply]
If you are using the default args for recordings, ffmpeg just makes a direct copy of the video stream without modification.

**Reply by tve** [reply]
How does it deal with I/B frames at segment boundaries? I don't have a "output_args" for this camera, so it's the default, which creates 60 second segments. Empirically, the segments are not exactly 60 seconds. Does ffmpeg extend a segment until the next I-Frame comes in so it can start the next segment with that? Or how does that work?

For reference, my config for this camera is:
```
cameras:
  gate:
    ffmpeg:
      inputs:
        - path: rtsp://phycam.voneicken.com/live/1/h264.sdp
          roles:
            - detect
            - rtmp
            - clips
            - record
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -stimeout
        - "5000000"
      output_args:
        rtmp: -c:v copy -an -f flv
    width: 768
    height: 432
    fps: 4
    clips:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
    record:
      enabled: True
      retain_days: 3
    motion:
      mask:
        - 768,0,581,0,544,152,540,432,768,432
    objects:
      track: [ 'person', 'car', 'dog', 'cat', 'sheep', 'bycicle', 'motorcycle', 'truck', 'bus' ]
```
