### DISCUSSION TITLE
How to disable saving to a folder \media\frigate\clips\review

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#13758] [Ask A Question] [answered]
Hi!

How can I disable saving to \media\frigate\clips\review?

If I am correct, I can see these same pictures in the \media\frigate\clips folder, where I have them saved in full size (not cropped).

```yaml
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3
```

**Did I miss something?**
