### DISCUSSION TITLE
How to disable saving to a folder \media\frigate\clips\previews

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#13759] [Ask A Question] [answered]
Hi.

How to disable saving to a folder \media\frigate\clips\previews because the recording is in some weird format and is completely useless.

![media-frigate-clips-previews](https://github.com/user-attachments/assets/0617cb36-856f-4c92-8b46-660654412486)

`Example setting:`
```yaml
  Diane:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/Di-HD
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 1

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10
#      max_disappeared: 25
#      stationary:
#        interval: 30
#        threshold: 20

    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.72
        car:
          threshold: 0.72
        bicycle:
          threshold: 0.72
        motorcycle:
          threshold: 0.72

    motion:
      threshold: 30
      contour_area: 10
      frame_height: 50
      improve_contrast: 'true'
      mask:
        - 0.005,0.011,0.252,0.013,0.252,0.056,0.005,0.06
        - 0,0.401,0.029,0.365,0.065,0.321,0.096,0.281,0.142,0.214,0.123,0.18,0.098,0.133,0.098,0.062,0.095,0,-0.001,0.001

    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        pre_capture: 2
        post_capture: 5
        retain:
          default: 3
          mode: active_objects

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3
```

**Any idea?**
Thank you.
