### DISCUSSION TITLE
[Config Support]: Event/History Playback doesn't work after updating audio codec

### DISCUSSION THREAD

**Discussion by spikked27** [blakeblackshear/frigate#13751] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I had the wrong audio settings for my driveway camera so I wasn't getting audio, I updated the config with `- "ffmpeg:rtsp://@192.168.0.113:554/11#video=copy#audio=copy#audio=aac#hardware"` per the docs and now audio works, however, now when I go to scrub the timeline or watch an event after this change took place the video doesn't load, all previous events and timeline still work.

### Steps to reproduce

1.  Let the camera record
2.  Update the ffmpeg config to change audio to 'AAC' (was previously PCM)
3.  Attempt to watch an event or scrub the timeline
...

### Version

0.14.1

### In which browser(s) are you experiencing the issue with?

Chrome

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.107
  port: 1883
  user: 
  password: 
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

tls:
  enabled: false

#logger:
  #default: debug
  #logs:
  #  frigate.ffmpeg.front_door: error

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    front_door:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password=#video=copy#audio=copy#audio=opus#hardware
      #- exec:./neolink/neolink_talk.sh#backchannel=1
      - rtsp://@192.168.0.112:554/h264Preview_01_sub
    front_door_sub:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=&password=
    front_door_snapshot:
    #  - onvif://@192.168.0.112:8000?subtype=000&snapshot
      - http://192.168.0.112/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=&password=
    driveway:
      - "ffmpeg:rtsp://@192.168.0.113:554/11#video=copy#audio=copy#audio=aac#hardware"
    #  - ffmpeg:driveway#audio=aac
    driveway_sub:
      - rtsp://@192.168.0.113:554/12
    #  - ffmpeg:driveway#audio=opus
    driveway_snapshot:
      - http://@192.168.0.113/tmpfs/auto.jpg
    kitchen_display:
      - rtsp://192.168.0.101:8654/kitchen_display
    #  - ffmpeg:kitchen_display#audio=opus

    webrtc:
      candidates:
        - 192.168.0.101:8555
        - stun:8555

cameras:
  front_door:
    ffmpeg:
 #     hwaccel_args: 
 #       - c:v hevc_cuvid
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_door

    motion:
      threshold: 30
      contour_area: 94
      improve_contrast: true
      mask: 
        0.974,0.497,0.973,0.478,0.975,0.4,0.936,0.171,0.874,0,0.052,0,0,0,0,0.314,0.054,0.351,0.058,0.553,0,0.545,0,0.625,0.133,0.649,0.395,0.647,0.581,0.626,0.749,0.582,0.845,0.585,0.887,0.591,0.914,0.595,0.933,0.594,0.943,0.595,0.967,0.594,0.967,0.584,0.967,0.575,0.971,0.555,0.973,0.54,0.971,0.519

    objects:
      filters:
        car:
          mask: 
            0.001,0.515,0.077,0.531,0.136,0.485,0.198,0.485,0.263,0.498,0.357,0.51,0.44,0.5,0.482,0.489,0.495,0.42,0.521,0.426,0.694,0.463,0.705,0.491,0.773,0.494,0.816,0.469,0.856,0.472,0.839,0.523,0.97,0.531,0.962,0.602,0.748,0.58,0.654,0.624,0.539,0.648,0.414,0.665,0.313,0.668,0.175,0.67,0.053,0.664,0,0.663
        person:
          mask: 
            0.001,0.515,0.077,0.531,0.136,0.485,0.198,0.485,0.213,0.537,0.42,0.534,0.504,0.529,0.482,0.489,0.486,0.456,0.694,0.463,0.705,0.491,0.773,0.494,0.816,0.469,0.856,0.472,0.839,0.523,0.97,0.531,0.962,0.602,0.748,0.58,0.65,0.609,0.535,0.631,0.41,0.645,0.312,0.65,0.175,0.653,0.048,0.64,0,0.663

    zones:
      Stoop:
        coordinates: 0.217,0.998,0.239,0.724,0.604,0.707,0.716,0.809,0.898,0.89,0.999,0.998
        loitering_time: 0
        inertia: 3
      Front_of_House:
        coordinates: 
          0.049,0.645,0.396,0.649,0.603,0.624,0.71,0.591,0.747,0.583,0.962,0.605,1,0.61,0.998,0.813,0.733,0.772,0.629,0.687,0.223,0.711,0.185,0.999,0,1,0,0.631
        loitering_time: 0

        inertia: 3
    review:
      alerts:
        required_zones: Stoop
##################################
#######    Driveway     ##########
##################################
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: driveway
    review:
      alerts:
        required_zones:
          - Front_of_House
          - Driveway_Area
          - Driveway_Entry
    zones:
      Front_of_House:
        coordinates: 0.444,0.446,0.675,0.424,0.752,0.417,0.751,0.483,0.744,0.553,0.56,0.513
        loitering_time: 0
        inertia: 3
      Driveway_Area:
        coordinates: 
          0.048,0.534,0.077,0.517,0.098,0.533,0.303,0.497,0.469,0.468,0.556,0.518,0.62,0.53,0.773,0.568,0.784,0.373,0.789,0.304,1,0.367,1,1,0,1,0,0.638
        inertia: 60
        loitering_time: 0
        objects:
          - bicycle
          - bird
          - cat
          - dog
          - motorcycle
          - person
          - suitcase
      Driveway_Entry:
        coordinates: 0.112,0.484,0.425,0.435,0.436,0.442,0.111,0.493
        loitering_time: 0
        inertia: 25
        objects: car
      Street:
        coordinates: 
          0,0.342,0.163,0.297,0.378,0.284,0.38,0.268,0.418,0.265,0.432,0.311,0.7,0.313,0.754,0.336,0.753,0.383,0.578,0.399,0.409,0.417,0.3,0.433,0.198,0.447,0.145,0.456,0.112,0.46,0.042,0.47,0,0.481
        loitering_time: 0
        inertia: 15
        objects:
          - bird
          - bicycle
          - cat
          - dog
          - motorcycle
          - person
          - suitcase
      Sidewalk:
        coordinates: 
          0.001,0.482,0.042,0.472,0.202,0.447,0.405,0.417,0.751,0.385,0.752,0.414,0.618,0.425,0.44,0.443,0.429,0.438,0.248,0.465,0.11,0.489,0.093,0.492,0.001,0.51
        loitering_time: 0
        objects:
          - bicycle
          - bird
          - cat
          - dog
          - person
          - suitcase
          - motorcycle
    motion:
      mask:
        - 0,0.337,0.001,0,1,0,1,0.361,0.775,0.292,0.77,0.374,0.662,0.329,0.577,0.31,0.432,0.311,0.419,0.265,0.377,0.268,0.378,0.282,0.297,0.286,0.163,0.294
        - 0,0.966,0.361,0.944,0.576,0.866,0.683,0.818,0.766,0.725,0.833,0.705,0.9,0.679,0.932,0.643,0.972,0.641,1,0.659,1,1,0,1
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask:
            - 0,0.301,0.131,0.265,0.162,0.234,0.289,0.226,0.486,0.224,0.505,0.225,0.505,0.157,0.671,0.155,0.766,0.156,0.76,0.422,0.527,0.441,0.445,0.449,0.417,0.431,0.298,0.445,0.223,0.456,0.162,0.467,0.115,0.473,0.087,0.493,0.055,0.506,0,0.613
            - 0,0.64,0.046,0.534,0.075,0.516,0.101,0.532,0.471,0.467,0.558,0.519,0.773,0.568,0.789,0.302,1,0.367,1,1,0,1
        person:
          mask: 0.662,0.307,0.778,0.385,0.786,0.158,0.51,0.155,0.506,0.312

  kitchen_display:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_display
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480

# END CAMERA CONFIG

    motion:
      mask: 
        0,0.301,0.024,0.268,0.036,0.27,0.274,0.552,0.35,0.575,0.624,0.579,0.71,0.532,0.806,0.425,1,0.181,1,0,0,0
detect:
  width: 640
  height: 480
  fps: 4

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 5
    post_capture: 15
    retain:
      default: 182
      mode: motion
  sync_recordings: true

snapshots:
  enabled: true
  retain:
    default: 365

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - suitcase

#audio:
#  enabled: true
#  listen:
#    - bark
#    - fire_alarm
#    - scream
#    - speech
#    - yell

version: 0.14
camera_groups: {}
```

### docker-compose file or Docker CLI command

```yaml
UnRAID Docker
```

### Relevant Frigate log output

```shell
2024-09-15 12:22:28.391490339  [ERROR:0@3769.198] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-09-15 12:22:32.451228  2024-09-15 12:22:28.391492854
2024-09-15 12:22:28.391494118  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-09-15 12:22:32.451230  2024-09-15 12:22:28.391494872
2024-09-15 12:22:32.451231  2024-09-15 12:22:28.391495617
2024-09-15 12:22:38.395752399  [ERROR:0@3779.202] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-09-15 12:22:42.481496  2024-09-15 12:22:38.395755903
2024-09-15 12:22:38.395757573  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-09-15 12:22:42.481498  2024-09-15 12:22:38.395758523
2024-09-15 12:22:42.481500  2024-09-15 12:22:38.395759469
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

SV3C 5mp

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/99668d0b-e4fb-47de-8fa2-cb74f105a72a)
