### DISCUSSION TITLE
record enabled: false // still showing thumbnail images

### DISCUSSION THREAD

**Discussion by oknowletssee** [blakeblackshear/frigate#13757] [Config Support] [answered]
### Describe the problem you are having

Hi together, this is my first issue I'd like to commit to this Wonderfull project, so be patient with me :-)
I noticed when jog-dialing through the timeline in to history, that snapshots are still shown although I deactivated recordings and snapshots within my config file. This could be privacy issue since one still can see a near-fluent time-lapse-sort-of video while moving the red timeline marker.

Reproduction steps:
- frigate live view > click on camera image > history > grab and hold red timeline marker > move it up/down

Current behaviour
- low-res snapshots are displayed on the left as near-continuous stream while moving the red timeline marker

Expected behaviour
- blank window, where no recordings were captured due to config settings. Alternatively show message e.g. "No recordings in selected time slot"

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: ...
  user: ...
  password: ...

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: false
  retain:
    days: 3
  events:
    retain:
      default: 5

snapshots:
  enabled: false

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - cat
      - squirl
      - dog

cameras:
  c1: ################################
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args:
        - -c:v:1
        - h264_v4l2m2m
      inputs:
        - path: rtsp://...
          roles:
            - detect
        - path: rtsp://...
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 4
    motion:
      mask: 0,0,0.372,0,0.371,0.081,0,0.08
      threshold: 67
      contour_area: 34
      improve_contrast: 'true'
    zones:
      Tür:
        coordinates: 0.447,0.138,0.481,0.986,0.77,0.962,0.781,0.129
        loitering_time: 3
    review:
      alerts:
        required_zones: Tür
  c2: ###########################
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args:
        - -c:v:1
        - h264_v4l2m2m
      inputs:
        - path: rtsp://...
          roles:
            - detect
        - path: rtsp://...
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 4
    motion:
      mask: 0.366,0.08,0,0.078,0,0,0.366,0
      threshold: 63
      contour_area: 28
      improve_contrast: 'true'
version: 0.14
```

### Relevant Frigate log output

```shell
No errors. UI issue.
```

### Relevant go2rtc log output

```shell
No relevant log. UI issue.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral
