### DISCUSSION TITLE
Are the objects too fast for the camera to detect (car)

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#13764] [Ask A Question] [answered]
Hi.

Am I configured incorrectly so that my camera does not detect "fast" moving objects such as a car?

Part of my yaml configuration
```yaml
cameras:
  Jedilnica:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/Jedilnica-HD
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 1

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10

    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.72
        car:
          threshold: 0.72
        bicycle:
          threshold: 0.72
        motorcycle:
          threshold: 0.72

    motion:
      threshold: 30
      contour_area: 10
      frame_height: 50
      improve_contrast: 'true'
      mask: 0.005,0.013,0.255,0.013,0.256,0.056,0.007,0.059               

    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        pre_capture: 2      # Izbirno: število sekund pred dogodkom, ki ga je treba vključiti ?
        post_capture: 5     # Izbirno: število sekund po dogodku za vključitev ?
        retain:
          default: 3
          mode: active_objects

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3


  Diane:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/Di-HD
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 1

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10

    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.72
        car:
          threshold: 0.72
        bicycle:
          threshold: 0.72
        motorcycle:
          threshold: 0.72

    motion:
      threshold: 30
      contour_area: 10
      frame_height: 50
      improve_contrast: 'true'
      mask:
        - 0.005,0.011,0.252,0.013,0.252,0.056,0.005,0.06
        - 0,0.401,0.029,0.365,0.065,0.321,0.096,0.281,0.142,0.214,0.123,0.18,0.098,0.133,0.098,0.062,0.095,0,-0.001,0.001

    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        pre_capture: 2
        post_capture: 5
        retain:
          default: 3
          mode: active_objects

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

  Nathalie:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/Nata-HD
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 1

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10

    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.72
        car:
          threshold: 0.72
        bicycle:
          threshold: 0.72
        motorcycle:
          threshold: 0.72

    motion:
      threshold: 30
      contour_area: 10
      frame_height: 50
      improve_contrast: 'true'
      mask:
        - 0.007,0.008,0.252,0.008,0.255,0.057,0.005,0.063
        - 0.818,0,0.834,0.056,0.845,0.097,0.874,0.143,0.894,0.174,0.917,0.2,0.951,0.217,0.998,0.176,0.997,0      

    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        pre_capture: 2
        post_capture: 5
        retain:
          default: 3
          mode: active_objects

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3


  Spalnica:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/Spalnica-HD
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 1

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10

    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.72
        car:
          threshold: 0.72
        bicycle:
          threshold: 0.72
        motorcycle:
          threshold: 0.72

    motion:
      threshold: 30
      contour_area: 10
      frame_height: 50
      improve_contrast: 'true'
      mask: 0.005,0.011,0.258,0.011,0.258,0.056,0.005,0.056    

    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      events:
        pre_capture: 2
        post_capture: 5
        retain:
          default: 3
          mode: active_objects

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3
```

camera: Jedilnica
![Jedilnica-1726485802 848193-yiu81k](https://github.com/user-attachments/assets/995486a1-c14b-4b50-ba67-48d4f149f0fd)
https://github.com/user-attachments/assets/805cf895-a99b-4109-8574-66b6b86f49ee
`car is detected`

camera: Diane
![Diane-1726485343 609282-96ipas](https://github.com/user-attachments/assets/e10e4305-8688-48b3-93d1-f64f892e9976)
`car is not detected`

camera: Nathalie
![Nathalie-1726485340 132498-cszl61](https://github.com/user-attachments/assets/b1557bea-4c36-4342-a4c4-1285be526510)
`car is not detected`

camera: Spalnica
![Spalnica-1726485734 640865-eyworg](https://github.com/user-attachments/assets/8c0a8727-f54e-4b9c-843b-8ba876840ff6)
https://github.com/user-attachments/assets/90abb306-21b7-4201-b3b6-756c3e86ea0d
`car is not detected`

**Am I missing something** or `is 10fps enough` for detection? I have a `coral dual TPU`!
