### DISCUSSION TITLE
[Camera Support]: Pan/Tilt/Presets Works from Frigate UI but not from mqtt or HA Integration service call

### DISCUSSION THREAD

**Discussion by Cheerpipe** [blakeblackshear/frigate#13768] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I try to move my camera using Frigate PTZ service from HA integration or from mqtt it doesn't work.

PTZ (PT and presets) works well from frigate UI.

### Steps to reproduce

Case A: From HA Integration service Call

1. From HA, run this service call:

```
action: frigate.ptz
data:
  action: move
  argument: UP
target:
  entity_id: camera.frigate_entrada

```

Case B: From MQTT

1. From HA MQTT config, send the followin payload to `frigate/entrada/ptz`

![image](https://github.com/user-attachments/assets/b0b957b0-cff1-4c12-a5f9-cf874ba6737a)

For both cases i get same result:

1. Camera don't move.
2. Nothing in HA logs.
3. Nothing in Frigate logs. Not even the expected "frigate.comms.dispatcher" "Setting ptz command to move_down for entrada" AND "Setting ptz command to stop for entrada" i get when using PT from Frigate WebUI.

### Version

0.15.0-e4ea35e

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.53
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

#logger:
  #default: error

#################### Openvino YoloNAS #######################
detectors:
  ov:
    type: openvino
    device: GPU
model:
  model_type: yolonas
  path: /custom/models/yolo_nas_s_256.onnx
  width: 256
  height: 256
  input_tensor: nchw
  input_pixel_format: bgr

audio:
  enabled: false
  listen:
    - scream
    - speech
    - yell
    - crying
    - children_playing
    - alarm

go2rtc:
  log:
    level: error
  rtsp:
    username: '{FRIGATE_RTSP_USER}'
    password: '{FRIGATE_RTSP_PASSWORD}'
  webrtc:
    candidates:
      - 192.168.1.53:8555
      - 127.0.0.1:8555
      - 172.17.0.12:8555
      - stun:8555
  streams:
    ##########################################################################################################
    salon:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.221:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:salon#audio=opus
    salon_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.221:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################  
    salon_secundaria:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.205:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:salon_secundaria#audio=opus
    salon_secundaria_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.205:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################  
    pasillo:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.121:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:pasillo#audio=opus
    pasillo_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.121:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################  
    entrada:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.229:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:entrada#audio=opus
    entrada_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.229:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################  
    cocina:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.115:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:cocina#audio=opus
    cocina_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.115:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################  
    dormitorio_pequeno:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.154:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:dormitorio_pequeno#audio=opus
    dormitorio_pequeno_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.154:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################   
    dormitorio_principal:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.233:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:dormitorio_principal#audio=opus
    dormitorio_principal_sub:
      - rtsp://{CAM_USERNAME}@{CAM_PASSWORD}@192.168.1.233:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    ##########################################################################################################   


cameras:
  entrada:
    onvif:
      host: 192.168.1.229
      port: 80
      user: ONVIF_USERNAME
      password: ONVIF_PASSWORD
    audio:
      min_volume: 750
      enabled: false
    ui:
      order: 10
    birdseye:
      order: 10
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/entrada #_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
        # - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/entrada?audio
        #   roles:
        #     - audio
    objects:
      filters:
        person:
          min_area: 10000

  cocina:
    onvif:
      host: 192.168.1.115
      port: 80
      user: ONVIF_USERNAME
      password: ONVIF_PASSWORD
    audio:
      min_volume: 750
      enabled: false
    ui:
      order: 20
    birdseye:
      order: 20
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/cocina #_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/cocina?audio
          roles:
            - audio

  salon:
    onvif:
      host: 192.168.1.238
      port: 80
      user: ONVIF_USERNAME
      password: ONVIF_PASSWORD
    ui:
      order: 40
    birdseye:
      order: 40
    detect:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/salon #_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/salon?audio
          roles:
            - audio

  salon_secundaria:
    onvif:
      host: 192.168.1.205
      port: 80
      user: ONVIF_USERNAME
      password: ONVIF_PASSWORD
    ui:
      order: 50
    birdseye:
      order: 50
    audio:
      enabled: false
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/salon_secundaria #_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    # live:
    #   stream_name: salon_secundaria

  pasillo:
    onvif:
      host: 192.168.1.121
      port: 80
      user: ONVIF_USERNAME
      password: ONVIF_PASSWORD
    audio:
      min_volume: 750
      enabled: false
    ui:
      order: 60
    birdseye:
      order: 60
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/pasillo #_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/pasillo?audio
          roles:
            - audio
    #live:
    #  stream_name: pasillo


  dormitorio_pequeno:
    onvif:
      host: 192.168.1.154
      port: 80
      user: ONVIF_USERNAME
      password: ONVIF_PASSWORD
    audio:
      enabled: false
    ui:
      order: 70
    birdseye:
      order: 70
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/dormitorio_pequeno #_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/dormitorio_pequeno?audio
          roles:
            - audio
    # live:
    #   stream_name: dormitorio_pequeno

  # dormitorio_principal:
  #   onvif:
  #     host: 192.168.1.233
  #     port: 80
  #     user: ONVIF_USERNAME
  #     password: ONVIF_PASSWORD
  #   detect:
  #     enabled: true
  #   ui:
  #     order: 80
  #   birdseye:
  #     order: 80
  #     threshold: 30
  #     contour_area: 10
  #   ffmpeg:
  #     inputs:
  #       - path: 
  #           rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/dormitorio_principal #_sub
  #         input_args: preset-rtsp-restream-low-latency
  #         roles:
  #           - detect
  #           - record
  #       - path: 
  #           rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/dormitorio_principal?audio
  #         roles:
  #           - audio
  #   # live:
  #   #   stream_name: dormitorio_principal


  #   # motion:
  #   #   threshold: 30
  #   #   contour_area: 10
  #   #   improve_contrast: 'true'
ffmpeg:
  retry_interval: 5
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi #intel-qsv-h264

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  mode: objects

objects:
  track:
    - person
    - cat
  filters:
    cat:
      min_score: 0.5
      threshold: 0.5
    person:
#      min_score: 0.6
#      threshold: 0.7
      min_score: 0.4
      threshold: 0.5
#      min_area: 2500

snapshots:
  enabled: true

detect:
  enabled: true
  width: 1280 #640
  height: 720 #480
  fps: 5
  #stationary:
    #interval: 75
    #threshold: 50
  #max_disappeared: 75

record:
  enabled: true
  retain:
    days: 30
    mode: all
      #  alerts:
      #retain:
      #    days: 30
      #detections:
      #retain:
      # days: 30

motion:
  frame_alpha: 0.02
  mqtt_off_delay: 15
  lightning_threshold: 0.9
  improve_contrast: false

  threshold: 30
  frame_height: 50
  contour_area: 10
  mask:
    - 0.599,0.117,0.602,0,1,0,1,0.117

tls:
  enabled: false


version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate-dev
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    network_mode: bridge
    restart:  unless-stopped
    shm_size: "4096mb"
    image: ghcr.io/blakeblackshear/frigate:e4ea35e

    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /config/frigate-dev/data:/config
      - /mnt/f/frigate/media:/media/frigate
      - /config/frigate-dev/custom/models:/custom/models
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
     - /dev/dri
    environment:
      - FRIGATE_RTSP_USER=XXXXXXXXXXXXXXXX
      - FRIGATE_RTSP_PASSWORD=XXXXXXXXXXXXXXXX
      - FRIGATE_MQTT_USER=XXXXXXXXXXXXXXXX
      - FRIGATE_MQTT_PASSWORD=XXXXXXXXXXXXXXXX
      - OverrideGpuAddressSpace=48
      - NEOReadDebugKeys=1
    ports:
      - "5000:5000"
      - "5080:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"
    deploy:
      resources:
        limits:
          memory: 8192M
```

### Relevant Frigate log output

```shell
I get nothing for the bug, at least with default log configuration.
```

### Relevant go2rtc log output

```shell
Nothing relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

IMOU Cruiser SE+

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/7be8fd67-f28f-4599-993c-4ef29c2cdac5)

### Any other information that may be helpful

192.168.X.X:5000/api/entrada/ptz/info response

```
{
    "features": [
        "pt"
    ],
    "name": "entrada",
    "presets": [
        "preset1",
        "preset2"
    ]
}
```

##############################

My camera supports ONVIF ports and profiles, but does not meet auto-tracking requirements. I get:

`Disabling autotracking for ranger2_test: FOV relative movement not supported`

(I know autotracking won't work, just added as realted info)
