### DISCUSSION TITLE
[Support]: Recordings are saved with audio only no video

### DISCUSSION THREAD

**Discussion by nosar77** [blakeblackshear/frigate#13774] [General Support]
### Describe the problem you are having

I made a change to my camera configurations and my file a longtime ago but recently noticed that my recordings are only being captured in audio. I verified this by checking the files on the disk directly and they play just fine with correct audio just no video. 

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Brave Version 1.69.153 Chromium: 128.0.6613.85 

### Frigate config file

```yaml
mqtt:
  host: SECRET     # YOUR MQTT IP
  port: SECRET
  topic_prefix: frigate
  user: frigate               # YOUR MQTT USERNAME
  password: SECRET  # YOUR MQTT PASSWORD

detectors:
  tensorrt:
    type: tensorrt
    device: 0  # This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    front_door_bell:
      - rtsp://SECRET:SECRET@192.168.0.13:554/h264Preview_01_main
      - ffmpeg:front_door_bell#audio=opus#audio=volume
    front_door_bell_sub:
      - rtsp://SECRET:SECRET@192.168.0.13:554/h264Preview_01_sub
      - ffmpeg:front_door_bell_sub#audio=opus#audio=volume

    backyard_cam:
      - rtsp://SECRET:SECRET@192.168.0.17:88/videoMain
      - ffmpeg:backyard_cam#audio=opus
    backyard_cam_sub:
      - rtsp://SECRET:SECRET@192.168.0.17:88/videoSub
      - ffmpeg:backyard_cam#audio=opus

    garage_floodlight:
      - rtsp://SECRET:SECRET@192.168.0.6:554/Preview_01_main
      - ffmpeg:garage_floodlight#video=h264#audio=opus

    garage_floodlight_sub:
      - rtsp://SECRET:SECRET@192.168.0.6:554/Preview_01_sub
      - ffmpeg:garage_floodlight#audio=opus
  webrtc:
    candidates:
      - 192.168.0.182:8555
      - stun:8555

  ## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30"

# Camera configuration
cameras:
  front_door_bell:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        # Main stream for recording
        - path: rtsp://127.0.0.1:8554/front_door_bell
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        # Sub-stream for detection
        - path: rtsp://127.0.0.1:8554/front_door_bell_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
      filters:
        person:
          min_area: 600
          max_area: 100000
          min_score: 0.85
          threshold: 0.7

    motion:
      threshold: 30
      contour_area: 18
      improve_contrast: true
  backyard_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        # Main stream for recording
        - path: rtsp://127.0.0.1:8554/backyard_cam
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        # Sub-stream for detection
        - path: rtsp://127.0.0.1:8554/backyard_cam_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.7
          threshold: 0.8

    motion:
      threshold: 51
      contour_area: 69
      improve_contrast: 'true'
  garage_floodlight:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        # Main stream for recording
        - path: rtsp://127.0.0.1:8554/garage_floodlight
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        # Sub-stream for detection
        - path: rtsp://127.0.0.1:8554/garage_floodlight_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1536
      height: 576
      fps: 7
    objects:
      track:
        - person
      filters:
        person:
          min_area: 10000
          max_area: 100000
          min_score: 0.75
          threshold: 0.85

#Global camera Config

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 14

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

  sync_recordings: true

tls:
  enabled: false

version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker CLI

### Object Detector

TensorRT

### Network connection

Mixed

### Camera make and model

Reolink Doorbell, Reolink Duo Floodlight, Foscam Floodlight
