### DISCUSSION TITLE
[Support]: Since upgrading to System 0.14.1-f4f3cfa, Live camera view is laggy, doesn't load sometimes etc

### DISCUSSION THREAD

**Discussion by voron69-bit** [blakeblackshear/frigate#13782] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Using the Frigate UI the main page loads, but clicking on a camera to get the live feed in a larger window results in a delay of up to 15 secs in Chrome, Brave won't load often, even with their blocker turned off. When going back to the main page from live individual cameras, sometimes some cameras show up with the black box of death saying no frames found for 20-30 secs. 
Never had any problems previously, this just started happening after 0.14.1 from a couple weeks ago.

### Steps to reproduce

1. Launch Frigate Live page
2. Click on any camera to get to the live individual page
3. Delay or camera doesn't load.
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
model:
  path: plus://redacted
ffmpeg:
  hwaccel_args: preset-vaapi
mqtt:
  host: 192.168.1.80
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate2022
  stats_interval: 300
record:
  expire_interval: 10
go2rtc:
  streams:
    drive:
      - rtsp://user:pass@192.168.1.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    drive_sub:
      - rtsp://user:pass@192.168.1.95:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    build_rear:
      - rtsp://user:pass@192.168.1.94:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    build_rear_sub:
      - rtsp://user:pass@192.168.1.94:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    build1_front:
      - rtsp://user:pass@192.168.1.93:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    build1_front_sub:
      - rtsp://user:pass@192.168.1.93:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    build1_side:
      - rtsp://user:pass@192.168.1.90:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    build1_side_sub:
      - rtsp://user:pass@192.168.1.90:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    build1_back1:
      - rtsp://user:pass@192.168.1.91:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    build1_back1_sub:
      - rtsp://user:pass@192.168.1.91:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    build_side:
      - rtsp://user:pass@192.168.1.92:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    build_side_sub:
      - rtsp://user:pass@192.168.1.92:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    barn:
      - rtsp://user:pass@192.168.1.141:554/stream1
    doorbell1:
      - rtsp://user:pass@192.168.1.50:554/h264Preview_01_sub
      - ffmpeg:rtsp://user:pass@192.168.1.50:554/h264Preview_01_sub#audio=pcm#audio=volume
    doorbell2:
      - rtsp://user:pass@192.168.1.51:554/h264Preview_01_sub
      - ffmpeg:rtsp://user:pass@192.168.1.51:554/h264Preview_01_sub#audio=pcm#audio=volume
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  webrtc:
    candidates:
      - 192.168.1.79:8555
      - stun:8555
timestamp_style:
  position: tr
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
objects:
  track:
    - face
    - person
    - car
    - ups
    - fedex
    - amazon
    - package
    - dog
  filters:
    face:
      min_score: 0.7
      threshold: 0.9
    dog:
      min_score: 0.7
      threshold: 0.9
    person:
      min_score: 0.7
      threshold: 0.9
    car:
      min_score: 0.6
      threshold: 0.85
    ups:
      min_score: 0.7
      threshold: 0.9
    fedex:
      min_score: 0.7
      threshold: 0.9
    amazon:
      min_score: 0.7
      threshold: 0.9
cameras:
  drive:
    live:
      stream_name: drive_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drive_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/drive
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_drive
        - monitor_car_detect
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_drive:
        coordinates: 
          0,0.44,0.043,0.365,0.115,0.283,0.161,0.241,0.191,0.227,0.225,0.189,0.256,0.155,0.335,0.092,0.361,0.081,0.389,0.069,0.417,0.064,0.484,0.049,0.545,0.055,0.604,0.055,0.68,0.056,0.719,0.063,0.734,0.063,0.745,0.089,0.788,0.092,0.824,0.101,0.859,0.11,0.885,0.119,0.917,0.128,0.955,0.152,1,0.185,1,1,0,1
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
        inertia: 3
      monitor_car_detect:
        coordinates: 0.567,0.159,0.39,0.186,0.422,0.128,0.433,0.07,0.476,0.059
        objects:
          - car
          - fedex
          - ups
          - amazon
        inertia: 3
    motion:
      mask:
        - 0,0,0.221,0,0.38,0,0.381,0.031,0.324,0.082,0.16,0.204,0,0.367
        - 0.963,0.039,0.965,0.084,0.746,0.075,0.746,0.037
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_drive
          - monitor_car_detect
      detections:
        required_zones:
          - monitor_drive
          - monitor_car_detect
  build1_front:
    live:
      stream_name: build1_front_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/build1_front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/build1_front
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_build1_front
        - monitor_car_detect
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_build1_front:
        coordinates: 
          0,0.194,0.023,0.186,0.055,0.169,0.101,0.136,0.167,0.104,0.214,0.088,0.299,0.064,0.384,0.042,0.483,0.019,0.541,0.019,0.597,0.019,0.645,0.06,0.73,0.11,0.824,0.173,0.921,0.251,1,0.328,1,1,0,1
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
        inertia: 3
    motion:
      mask:
        - 1853,40,1858,86,1440,87,1442,39
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones: monitor_build1_front
      detections:
        required_zones: monitor_build1_front
  build_rear:
    live:
      stream_name: build_rear_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/build_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/build_rear
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - face
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_build_rear
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_build_rear:
        coordinates: 
          0,1,0.881,1,0.915,0.841,1,0.765,1,0.373,0.989,0.34,0.975,0.309,0.931,0.244,0.875,0.211,0.855,0.207,0.624,0.147,0.594,0.1,0.573,0.053,0.564,0.024,0.531,0.019,0.439,0,0.294,0,0.211,0.023,0.111,0.077,0,0.162
        objects:
          - face
          - person
        inertia: 3
    motion:
      mask:
        - 0.894,0.855,1,0.725,1,1,0.843,1
        - 0.748,0.074,0.961,0.077,0.961,0.031,0.749,0.035
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones: monitor_build_rear
  build1_side:
    live:
      stream_name: build1_side_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/build1_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/build1_side
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_build1_side
        - monitor_build1_side_dog
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_build1_side:
        coordinates: 
          0.14,0.82,0.196,0.748,0.165,0.621,0.116,0.509,0.086,0.435,0.05,0.467,0.033,0.384,0.015,0.275,0.01,0.253,0.071,0.199,0.1,0.172,0.128,0.15,0.21,0.108,0.246,0.09,0.296,0.069,0.334,0.056,0.368,0.045,0.41,0.035,0.455,0.029,0.492,0.023,0.531,0.021,0.566,0.022,0.601,0.024,0.633,0.027,0.666,0.035,0.702,0.045,0.733,0.059,0.773,0.083,0.816,0.106,0.849,0.128,0.901,0.158,1,0.209,1,0.393,1,1,0.207,1
        objects:
          - face
          - person
        stationary:
          duration: 60
          filter:
            car: {}
        inertia: 3
      monitor_build1_side_dog:
        coordinates: 
          0.011,0.258,0.03,0.246,0.045,0.232,0.059,0.22,0.081,0.2,0.104,0.181,0.126,0.164,0.188,0.136,0.221,0.115,0.249,0.099,0.281,0.081,0.292,0.07,0.306,0.071,0.324,0.06,0.339,0.06,0.369,0.051,0.402,0.045,0.433,0.039,0.459,0.035,0.489,0.03,0.545,0.021,0.587,0.022,0.635,0.023,0.682,0.031,0.767,0.082,0.639,0.102,0.53,0.135,0.385,0.19,0.208,0.275,0.096,0.363,0.034,0.415
        objects: dog
        inertia: 3
    motion:
      mask: 0.961,0.031,0.964,0.078,0.75,0.077,0.75,0.037
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_build1_side_dog
          - monitor_build1_side
      detections:
        required_zones:
          - monitor_build1_side_dog
          - monitor_build1_side
  build1_back1:
    live:
      stream_name: build1_back1_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/build1_back1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/build1_back1
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_build1_back1
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_build1_back1:
        coordinates: 
          0.84,1,1,0.671,1,0.546,0.928,0.461,0.958,0.418,0.987,0.299,0.946,0.258,0.899,0.214,0.853,0.185,0.807,0.153,0.759,0.105,0.694,0.081,0.658,0.06,0.595,0.037,0.549,0.025,0.502,0.019,0.464,0.019,0.42,0.019,0.372,0.019,0.332,0.023,0.281,0.033,0.243,0.031,0.185,0.059,0.102,0.074,0,0.118,0,1
        objects:
          - face
          - person
        inertia: 3
    motion:
      mask: 0.961,0.031,0.964,0.078,0.75,0.077,0.75,0.037
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones: monitor_build1_back1
  doorbell1:
    live:
      stream_name: doorbell1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 2560
      height: 1920
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_doorbell1
        - monitor_doorstep
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_doorbell1:
        coordinates: 
          0.079,0.93,0.258,0.782,0.295,0.775,0.47,0.826,0.685,0.874,0.69,1,1,1,1,0.515,0.635,0.477,0.494,0.47,0.313,0.52,0.262,0.546,0.195,0.585,0,0.652,0,0.738
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
        inertia: 3
      monitor_doorstep:
        coordinates: 
          0.122,1,0.589,1,0.607,0.867,0.303,0.79,0.263,0.79,0.22,0.816,0.168,0.859,0.129,0.889,0.107,0.913,0.084,0.931
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
          - package
        inertia: 3
    motion:
      mask: 1,0.046,1,0,0.654,0,0.657,0.04
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_doorstep
          - monitor_doorbell1
      detections:
        required_zones:
          - monitor_doorstep
          - monitor_doorbell1
  doorbell2:
    live:
      stream_name: doorbell2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 2560
      height: 1920
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_doorbell2
        - monitor_doorbell2step
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_doorbell2:
        coordinates: 
          0,1,0.308,1,0.321,0.843,0.435,0.828,0.529,0.816,0.714,0.768,0.744,0.432,0.696,0.44,0.549,0.429,0.39,0.441,0.268,0.458,0,0.499,0,0.738
        objects:
          - face
          - person
        stationary:
          duration: 60
          filter:
            car: {}
        inertia: 3
      monitor_doorbell2step:
        coordinates: 
          2272,1920,2428,1750,1977,1488,1918,1488,1837,1482,1737,1488,1062,1599,1073,1723,1113,1920
        objects:
          - face
          - person
    motion:
      mask:
        - 2560,89,2560,0,1668,0,1669,84
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones:
          - monitor_doorbell2step
          - monitor_doorbell2
  build_side:
    live:
      stream_name: build_side_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/build_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/build_side
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_build_side
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_build_side:
        coordinates: 
          1,1,1,0.164,0.903,0.09,0.778,0.019,0.535,0,0.367,0.021,0.261,0.03,0.163,0.036,0.111,0.125,0.074,0.222,0,0.45,0,1
        objects:
          - face
          - person
          - dog
          - car
        stationary:
          duration: 60
          filter:
            car: {}
        inertia: 3
    motion:
      mask:
        - 1844,43,1843,94,1450,87,1446,45
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    review:
      alerts:
        required_zones: monitor_build_side
  barn:
    live:
      stream_name: barn
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/barn
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
    record:
      enabled: true  # Enable recording
      retain:
        days: 2  # Retain recordings for 2 days

detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: continuous
live:
  height: 640
  quality: 1
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    environment:
      PLUS_API_KEY: "redacted"
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "2048mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker-compose/frigate:/config
      - unraid_frigate_nfs:/media/frigate
      - /mnt/data/efficientdet_lite3_512_ptq_edgetpu.tflite:/models/efficientdet_lite3_512_ptq_edgetpu.tflite
      - /mnt/data/coco_labels.txt:/models/coco_labels.txt
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554"
      - "8080:8080"
      - "8555:8555/tcp"
      - "8555:8555/udp"

volumes:
  unraid_frigate_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.1.78,nolock,soft,rw,timeo=500,retrans=10,proto=tcp,vers=4,sec=sys"
      device: ":/mnt/disks/frigate"
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
info
2024-09-16 22:12:57
startup
Preparing new go2rtc config...
info
2024-09-16 22:12:57
startup
Not injecting WebRTC candidates into go2rtc config as it has been set manually
info
2024-09-16 22:12:57
startup
Starting go2rtc...
info
2024-09-16 22:12:58
startup
go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info
2024-09-16 22:12:58
startup
config path=/dev/shm/go2rtc.yaml
info
2024-09-16 22:12:58
api
listen addr=:1984
info
2024-09-16 22:12:58
rtsp
listen addr=:8554
info
2024-09-16 22:12:58
webrtc
listen addr=:8555
2024-09-16 22:13:07
startup
Starting go2rtc healthcheck service...
```

### Operating system

Ubuntu

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

amcrest and reolink doorbells

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c8aee329-2e65-4abb-a01e-c420a7382477)
![image](https://github.com/user-attachments/assets/b9778a8f-4bee-4550-a2ce-c197a650be58)

### Any other information that may be helpful

I see this fix went in 3 weeks ago, I assume it was put into this build?
https://github.com/blakeblackshear/frigate/pull/13143
If so, the issue persists. If it wasn't added, tell me to shut up and wait. LOL
Otherwise, I'd love to be able to give more feedback to get this issue resolved. Just tell me what I need to give you guys!
