### DISCUSSION TITLE
[Support]: Inference speed of Coral TPU becomes incredibly (e.g. 1 Billion of milliseconds) and all cameras have the black image with no frames received

### DISCUSSION THREAD

**Discussion by StefanoGiu** [blakeblackshear/frigate#13784] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After some times, the inference speed of Coral TPU becomes incredibly (e.g. 1 Billion of milliseconds) and all cameras have the black image with no frames received.
E.g. now I have: coral 6107.5ms

If I restart, inference goes back to 10 ms and everything is ok, but then it happens again after some hours...

### Steps to reproduce

wait some time after the latest restart

### Version

 0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Not a browser issue

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: XX.XX.XX.63
  port: 1883
  topic_prefix: frigate

audio: # <- enable audio events for all camera
  enabled: true

go2rtc:
  streams:
    Veranda:
      - rtsp://XXXX:XXXXX@XX.XX.XX.10:14000/tcp/av0_0
      - ffmpeg:Veranda#audio=aac
    Veranda2:
      - rtsp://XXXX:XXXXX@XX.XX.XX.11:14000/tcp/av0_0
      - ffmpeg:Veranda2#audio=aac
    Veranda3:
      - rtsp://XXXX:XXXXX@XX.XX.XX.12:14000/tcp/av0_0
      - ffmpeg:Veranda3#audio=aac
    Cucina:
      - rtsp://XXXX:XXXXX@XX.XX.XX.13:14000/tcp/av0_0
      - ffmpeg:Cucina#audio=aac
    Cucina2:
      - rtsp://XXXX:XXXXX@XX.XX.XX.14:14000/tcp/av0_0
      - ffmpeg:Cucina2#audio=aac
    Retro:
      - rtsp://XXXX:XXXXX@XX.XX.XX.15:14000/tcp/av0_0
      - ffmpeg:Retro#audio=aac
    Retro2:
      - rtsp://XXXX:XXXXX@XX.XX.XX.16:14000/tcp/av0_0
      - ffmpeg:Retro2#audio=aac
    Retro3:
      - rtsp://XXXX:XXXXX@XX.XX.XX.17:14000/tcp/av0_0
      - ffmpeg:Retro3#audio=aac
    Giovanni:
      - rtsp://XXXX:XXXXX@XX.XX.XX.18:14000/tcp/av0_0
      - ffmpeg:Giovanni#audio=aac
    Giovanni2:
      - rtsp://XXXX:XXXXX@XX.XX.XX.19:14000/tcp/av0_0
      - ffmpeg:Giovanni2#audio=aac
    Giovanni3:
      - rtsp://XXXX:XXXXX@XX.XX.XX.20:8554/Streaming/Channels/101
      - ffmpeg:Giovanni3#audio=aac
    Aurora:
      - rtsp://XXXX:XXXXX@XX.XX.XX.21:14000/tcp/av0_0
      - ffmpeg:Aurora#audio=aac
    Aurora2:
      - rtsp://XXXX:XXXXX@XX.XX.XX.22:14000/tcp/av0_0
      - ffmpeg:Aurora2#audio=aac
    Viale:
      - rtsp://XXXX:XXXXX@XX.XX.XX.23:8554/Streaming/Channels/101
      - ffmpeg:Viale#audio=aac
    Giardino:
      - rtsp://XXXX:XXXXX@XX.XX.XX.24:8554/Streaming/Channels/101
      - ffmpeg:Giardino#audio=aac
    Cancello:
      - rtsp://XXXX:XXXXX@XX.XX.XX.26:8554/Streaming/Channels/101
      - ffmpeg:Cancello#audio=aac
    Forno:
      - rtsp://XXXX:XXXXX@XX.XX.XX.27:8554/Streaming/Channels/101
      - ffmpeg:Forno#audio=aac

# ffmpeg:
  # hwaccel_args: preset-vaapi
cameras:
  Veranda:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Veranda #rtsp://XXXX:XXXXX@XX.XX.XX.10:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 0,0,0.317,0,0.383,0,0,0.231
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Veranda2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Veranda2 #rtsp://XXXX:XXXXX@XX.XX.XX.11:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0,0,0.066,0,0.065,0.192,0.097,0.28,0.159,0.369,0.22,0.602,0.365,0.676,0.416,0.875,0.441,0.973,0.408,1,0,1
        - 0.232,0.136,0.24,0.081,0.241,0,0.339,0,0.648,0,0.759,0,0.757,0.186,0.716,0.494,0.677,0.521
        - 1,0.496,0.826,0.408,0.864,0,1,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Veranda3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Veranda3 #rtsp://XXXX:XXXXX@XX.XX.XX.12:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0.058,0.674,0.053,0,0,0,0,1,0.104,1,0.148,1
        - 0.818,0.187,0.805,0.356,0.763,0.578,0.79,0.592,0.9,0.329,0.951,0.194,1,0.124,1,0,0.956,0,0.735,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Cucina:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cucina #rtsp://XXXX:XXXXX@XX.XX.XX.13:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 0.295,0,0,0,0,0.382
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Cucina2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cucina2 #rtsp://XXXX:XXXXX@XX.XX.XX.14:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 744,0,0,0,0,146,252,114,426,107,640,103,829,104,939,119,1038,116,1027,297,1174,365,1280,424,1280,187,1280,0,1148,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Retro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Retro #rtsp://XXXX:XXXXX@XX.XX.XX.15:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Retro2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Retro2 #rtsp://XXXX:XXXXX@XX.XX.XX.16:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 379,151,1280,462,1280,0,0,0,0,257
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Retro3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Retro3 #rtsp://XXXX:XXXXX@XX.XX.XX.17:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 311,212,351,162,715,63,725,0,0,0,0,347
        - 987,0,1280,0,1280,55,1233,101
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Giovanni:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Giovanni #rtsp://XXXX:XXXXX@XX.XX.XX.18:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0.749,0,0.728,0.215,0.725,0.34,0.717,0.351,0.694,0.426,0.691,0.515,0.761,0.501,0.826,0.49,0.839,0.394,0.77,0.28,0.954,0.393,1,0.729,1,0.543,1,0
        - 0,0,0,0.343,0.557,0.104,0.719,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Giovanni2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Giovanni2 #rtsp://XXXX:XXXXX@XX.XX.XX.19:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 
        0.681,0,1,0,1,0.083,1,0.369,0.906,0.353,0.815,0.289,0.781,0.254,0.726,0.185,0.616,0.207,0.487,0.12,0.121,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Giovanni3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Giovanni3 #rtsp://XXXX:XXXXX@XX.XX.XX.20:8554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 1,0,1,0.306,0.609,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Aurora:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Aurora #rtsp://XXXX:XXXXX@XX.XX.XX.21:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 
        0,0,1,0,1,0.115,0.825,0.657,0.872,0.411,0.825,0.395,0.808,0.336,0.742,0.33,0.656,0.282,0.61,0.235,0.582,0.302,0.523,0.283,0.453,0.314,0.416,0.268,0.37,0.279,0.349,0.275,0.168,0.256,0.136,0.164,0,0.101
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Aurora2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Aurora2 #rtsp://XXXX:XXXXX@XX.XX.XX.22:14000/tcp/av0_0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 0,0,0.295,0,0.312,0.05,0.277,0.093,0.242,0.108,0.185,0.117,0.145,0.178,0.143,0.261,0.183,0.397,0.173,0.439,0.136,0.437,0.07,0.408,0,0.174
        - 0.941,0.135,1,0.096,1,0,0.762,0,0.795,0.076
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Viale:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Viale #rtsp://XXXX:XXXXX@XX.XX.XX.23:8554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 
        1,0,1,0.328,0.941,0.283,0.884,0.244,0.883,0.126,0.727,0.09,0.502,0.031,0.389,0.044,0.366,0.137,0.27,0.153,0.27,0.242,0.275,0.344,0.219,0.314,0.164,0.263,0.108,0.208,0.034,0.225,0.079,0.747,0.127,1,0,1,0,0.275,0,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Giardino:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Giardino #rtsp://XXXX:XXXXX@XX.XX.XX.24:8554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 
        0,0,0.5,0,1,0,1,0.39,0.973,0.377,0.89,0.328,0.904,0.252,0.847,0.242,0.829,0.373,0.793,0.463,0.787,0.542,0.709,0.535,0.736,0.378,0.686,0.274,0.628,0.277,0.581,0.248,0.574,0.169,0.515,0.163,0.418,0.223,0.348,0.239,0.322,0.353,0.291,0.209,0.254,0.318,0.219,0.304,0.207,0.336,0.2,0.534,0.116,0.381,0.092,0.537,0.066,0.427,0,0.367
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Cancello:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cancello #path: rtsp://XXXX:XXXXX@XX.XX.XX.26:8554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
  Forno:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Forno
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: motion

detectors:
  coral:
    # type: cpu
    type: edgetpu
    device: usb
# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects


# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 20
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 25
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
  lightning_threshold: 0.8
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Eye4, CloudEdge

### Screenshots of the Frigate UI's System metrics pages

-
