### DISCUSSION TITLE
[Config Support]: Motion Detection Tuner page saves "improve_contrast: 'true'" to the config but the editor shows a type error.

### DISCUSSION THREAD

**Discussion by dandandanp** [blakeblackshear/frigate#13797] [Config Support]
### Describe the problem you are having

When using the Motion Detection Tuner page and altering the settings for motion on a camera, the parameters added to the config put single quotes around the true/false statement for the improve_contrast key.
Both `'true'` and `true` work but there is a 'squiggly' highlight on the config editor, see image:
![image](https://github.com/user-attachments/assets/e250697f-768d-4a48-a01c-7f1af1fc6557)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
...
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
...
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
