### DISCUSSION TITLE
[HW Accel Support]: DS920+ tapo Camera

### DISCUSSION THREAD

**Discussion by max5962** [blakeblackshear/frigate#13798] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hello,

HW accel seems not working for me.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
cameras:
  camera1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX:XXXXXX@192.168.1.XXX:554/stream1 # <----- The stream you want to use for detection
          roles:
            - record
       hwaccel_args: preset-vaapi 
    record:
      enabled: true
    onvif:
      host: 192.168.1.XX
      port: 2020
      user: XXXXX
      password: 'XXXX'
    detect:
      enabled: false
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
frigate:
       container_name: frigate
       privileged: true
       restart: unless-stopped
       image: ghcr.io/blakeblackshear/frigate:stable
       shm_size: "150mb"
       devices:
          - /dev/dri/renderD128:/dev/dri/renderD128
       volumes:
          - /etc/localtime:/etc/localtime:ro
          - /volume2/docker/frigate/config/:/config
          - /volume1/frigate_storage:/media/frigate
       ports:
          - "8971:8971"
          - "8554:8554"
          - "8555:8555/tcp"
          - "8555:8555/udp"
       environment:
         FRIGATE_RTSP_PASSWORD: "XXXXXXX"
         LIBVA_DRIVER_NAME: i965
       network_mode: host
```

### Relevant Frigate log output

```shell
frigate  | 2024-09-17 18:28:35.464198905  [2024-09-17 18:28:35] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
frigate  | 2024-09-17 18:28:35.464310680  [2024-09-17 18:28:35] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-09-17 18:28:35.477440383  [2024-09-17 18:28:35] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-09-17 18:28:35.751353281  [2024-09-17 18:28:35] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
frigate  | 2024-09-17 18:28:39.118510052  [2024-09-17 18:28:39] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-09-17 18:28:39.118660643  [2024-09-17 18:28:39] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-09-17 18:28:39.665071443  [2024-09-17 18:28:39] frigate.app                    INFO    : Recording process started: 387
frigate  | 2024-09-17 18:28:39.665079023  [2024-09-17 18:28:39] frigate.app                    INFO    : Recording process started: 388
frigate  | 2024-09-17 18:28:39.670317215  [2024-09-17 18:28:39] frigate.app                    INFO    : go2rtc process pid: 105
frigate  | 2024-09-17 18:28:39.704573722  [2024-09-17 18:28:39] frigate.app                    INFO    : Output process started: 416
frigate  | 2024-09-17 18:28:39.741441147  [2024-09-17 18:28:39] detector.cpu                   INFO    : Starting detection process: 415
frigate  | 2024-09-17 18:28:39.741942874  [2024-09-17 18:28:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2024-09-17 18:28:39.745533649  [2024-09-17 18:28:39] frigate.app                    INFO    : Camera processor started for camera1: 432
frigate  | 2024-09-17 18:28:39.762029477  [2024-09-17 18:28:39] frigate.app                    INFO    : Capture process started for camera1: 433
frigate  | 2024-09-17 18:28:42.466872964  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-09-17 18:28:42.949851083  192.168.1.113 - - [17/Sep/2024:18:28:42 +0200] "GET /api/profile HTTP/1.1" 200 21 "https://192.168.1.100:8971/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-"
frigate  | 2024-09-17 18:29:03.011881808  [2024-09-17 18:29:03] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Invalid argument)
frigate  | 2024-09-17 18:29:03.011888319
frigate  | 2024-09-17 18:29:03.025487861  192.168.1.113 - - [17/Sep/2024:18:29:03 +0200] "GET /api/config HTTP/1.1" 200 7844 "https://192.168.1.100:8971/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-"
frigate  | 2024-09-17 18:29:03.027038698  192.168.1.113 - - [17/Sep/2024:18:29:03 +0200] "GET /api/review?limit=10&severity=alert HTTP/1.1" 200 3 "https://192.168.1.100:8971/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-"
frigate  | 2024-09-17 18:29:04.986327224  192.168.1.113 - - [17/Sep/2024:18:29:04 +0200] "GET /api/camera1/latest.webp?h=356&cache=1726590545703 HTTP/1.1" 200 31786 "https://192.168.1.100:8971/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-"
```

### Relevant go2rtc log output

```shell
info
2024-09-17 18:30:00
startup
Preparing new go2rtc config...
info
2024-09-17 18:30:00
startup
Starting go2rtc...
info
2024-09-17 18:30:01
startup
go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info
2024-09-17 18:30:01
startup
config path=/dev/shm/go2rtc.yaml
info
2024-09-17 18:30:01
rtsp
listen addr=:8554
info
2024-09-17 18:30:01
api
listen addr=:1984
info
2024-09-17 18:30:01
webrtc
listen addr=:8555/tcp
info
2024-09-17 18:30:10
startup
Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

TAPO C200

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/4ae16b6e-e43c-470f-93a5-c80c1cf4c41c)
