### DISCUSSION TITLE
[Config Support]: No live view for Foscam camera in Safari

### DISCUSSION THREAD

**Discussion by jerome71** [blakeblackshear/frigate#13807] [Config Support] [answered]
### Describe the problem you are having

I get no live view (I just have the spinning thing) in Safari for a Foscam camera (probably R4M but not 100% sure).
- this applies to Safari in macOS Sequoia, iOS 18? as well as iPadOS 18.1 beta 4.
- live view for this Foscam camera works in Chrome, Edge and Safari on the Mac
- live view works in Safari for my other cameras (Axis and Dahua)
- detection via secondary stream and recording/playback of the primary stream work well, including playback in Safari.

If I change Go2RTC settings for this camera from the raw rtsp stream to ffmpeg, with video=copy or video=h264, I get a working live view in Safari, but using the secondary stream (I can see that because the timestamp is bigger), whereas Chrome, Edge and Firefox on the Mac always show the primary stream. 

This is workable for me for now - I use Safari mostly, and exclusively on iPhone and iPad.
I've seen the similar discussion and I'd love to be help but do not know where to look.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
go2rtc:
  streams:
    Aiguebelle_Baie: # <- for RTSP streams
      - ffmpeg:rtsp://user:pswd@192.168.51.102:554/videoMain#video=copy#
#      - rtsp://user:pswd@192.168.51.102:554/videoMain#media=video # 
    Aiguebelle_Baie_small: # <- for RTSP streams
      - rtsp://user:pswd@192.168.51.102:554/videoSub 

cameras:
  Aiguebelle_Baie: #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Aiguebelle_Baie  #The Stream you want to monitor
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Aiguebelle_Baie_small  #The Stream you want to monitor
          roles:
            - detect
    detect:
      enabled: true # Detection is disabled
      fps: 5
```

### Relevant Frigate log output

```shell
Nothing seemingly relevant here
```

### Relevant go2rtc log output

```shell
Nothing seemingly relevant here
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral
