### DISCUSSION TITLE
[Support]: Frigate not able to connect to camera after the frame dropout happened

### DISCUSSION THREAD

**Discussion by devdems** [blakeblackshear/frigate#13823] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

So i have a camera that occasionally has some dropouts from WiFi. Issue is that Frigate is not able to establish by itself connection to camera after dropout happened but the issue is not present anymore.

What I need to do is stop Frigate and start it and then it again works.

This are the logs I'm getting before I restart it. The log is spammed by exact same lines:

2024-09-19 12:37:09.141244780  [2024-09-19 12:37:09] watchdog.street                ERROR   : Ffmpeg process crashed unexpectedly for street.
2024-09-19 12:37:09.141332345  [2024-09-19 12:37:09] watchdog.street                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-19 12:37:09.141376850  [2024-09-19 12:37:09] ffmpeg.street.detect           ERROR   : rtsp://127.0.0.1:8554/street_sub: Invalid data found when processing input
2024-09-19 12:37:09.166254114  [2024-09-19 12:37:09] watchdog.street                ERROR   : No new recording segments were created for street in the last 120s. restarting the ffmpeg record process...
2024-09-19 12:37:09.166339515  [2024-09-19 12:37:09] watchdog.street                INFO    : Terminating the existing ffmpeg process...
2024-09-19 12:37:09.166400848  [2024-09-19 12:37:09] watchdog.street                INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-19 12:37:14.278047989  [2024-09-19 12:37:14] frigate.video                  ERROR   : street: Unable to read frames from ffmpeg process.
2024-09-19 12:37:14.278125718  [2024-09-19 12:37:14] frigate.video                  ERROR   : street: ffmpeg process is not running. exiting capture thread...
2024-09-19 12:37:24.189481260  [2024-09-19 12:37:24] watchdog.street                ERROR   : Ffmpeg process crashed unexpectedly for street.
2024-09-19 12:37:24.189485939  [2024-09-19 12:37:24] watchdog.street                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-19 12:37:24.189488146  [2024-09-19 12:37:24] ffmpeg.street.detect           ERROR   : rtsp://127.0.0.1:8554/street_sub: Invalid data found when processing input
2024-09-19 12:37:24.213757621  [2024-09-19 12:37:24] watchdog.street                ERROR   : No new recording segments were created for street in the last 120s. restarting the ffmpeg record process...
2024-09-19 12:37:24.213813397  [2024-09-19 12:37:24] watchdog.street                INFO    : Terminating the existing ffmpeg process...
2024-09-19 12:37:24.213848510  [2024-09-19 12:37:24] watchdog.street                INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-19 12:37:29.326413429  [2024-09-19 12:37:29] frigate.video                  ERROR   : street: Unable to read frames from ffmpeg process.
2024-09-19 12:37:29.326485540  [2024-09-19 12:37:29] frigate.video                  ERROR   : street: ffmpeg process is not running. exiting capture thread...
2024-09-19 12:37:39.234152825  [2024-09-19 12:37:39] watchdog.street                ERROR   : Ffmpeg process crashed unexpectedly for street.
2024-09-19 12:37:39.234157462  [2024-09-19 12:37:39] watchdog.street                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-19 12:37:39.234177590  [2024-09-19 12:37:39] ffmpeg.street.detect           ERROR   : rtsp://127.0.0.1:8554/street_sub: Invalid data found when processing input
2024-09-19 12:37:39.257572503  [2024-09-19 12:37:39] watchdog.street                ERROR   : No new recording segments were created for street in the last 120s. restarting the ffmpeg record process...
2024-09-19 12:37:39.257577888  [2024-09-19 12:37:39] watchdog.street                INFO    : Terminating the existing ffmpeg process...
2024-09-19 12:37:39.257606651  [2024-09-19 12:37:39] watchdog.street                INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-19 12:37:44.370285001  [2024-09-19 12:37:44] frigate.video                  ERROR   : street: Unable to read frames from ffmpeg process.
2024-09-19 12:37:44.370346124  [2024-09-19 12:37:44] frigate.video                  ERROR   : street: ffmpeg process is not running. exiting capture thread...

 

### Steps to reproduce

1. Camera not having connection to wifi for short period of time
2. Frigate cannot reconnect to it without manually restarting the Frigate.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
#frigate sample config.yml
mqtt:
  # Required: host name
  host: x.x.x.10
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  #user: mqtt user here
  # Optional: 
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  #password: mqtt pass here
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /config/model_cache/tensorrt/yolov7-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy
  # Optional: Time in seconds to wait before ffmpeg retries connecting to the camera. (default: shown below)
  # If set too low, frigate will retry a connection to the camera's stream too frequently, using up the limited streams some cameras can allow at once
  # If set too high, then if a ffmpeg crash or camera stream timeout occurs, you could potentially lose up to a maximum of retry_interval second(s) of footage
  # NOTE: this can be a useful setting for Wireless / Battery cameras to reduce how much footage is potentially lost during a connection timeout.
  retry_interval: 15

go2rtc:
  streams:
    backyard: # <- for RTSP streams
      - rtsp://xxxxxx:xxxxxxx@x.x.x.59:554/live/ch0 # <- stream which supports video & aac audio
      - "ffmpeg:backyard#video=h264#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    backyard_sub: # <- for RTSP streams
      - "ffmpeg:backyard#video=h264#width=640#height=360" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    garage: # <- for other streams
      - rtsp://xxxxxx:xxxxxxx@x.x.x.60:554/live/ch0 # <- stream which supports video & aac audio
      - "ffmpeg:garage#video=h264#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    garage_sub: # <- for other streams
      - "ffmpeg:garage#video=h264#width=640#height=360" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    frontdoor: # <- for other streams
      - rtsp://xxxxxx:xxxxxxx@x.x.x.61:554/live/ch0 # <- stream which supports video & aac audio
      - "ffmpeg:frontdoor#video=h264#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    frontdoor_sub: # <- for other streams
      - "ffmpeg:frontdoor#video=h264#width=640#height=360" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    street: # <- for other streams
      - rtsp://xxxxxx:xxxxxxx@x.x.x.70:554/live/ch0 # <- stream which supports video & aac audio
      - "ffmpeg:street#video=h264#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    street_sub: # <- for other streams
      - "ffmpeg:street#video=h264#width=640#height=360" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus) 
  webrtc:
    candidates:
      - x.x.x.10:8555
      - stun:8555

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: enables detection for the camera (default: True)
  enabled: true
# Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  #fps: 10
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 7
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10

# Include all cameras by default in Birdseye view
birdseye:
  enabled: false
  mode: continuous

cameras:
  backyard:
    enabled: true
    birdseye:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: x.x.x.59
      port: 8899
      user: xxxx
      password: xxxxx
    motion:
      mask: 0.727,0.003,0.729,0.05,0.978,0.049,0.979,0.003
    objects: {}
  garage:
    enabled: true
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: x.x.x.60
      port: 8899
      user: xxxx
      password: xxxxx
    motion:
      mask: 0.726,0.001,0.726,0.049,0.976,0.052,0.976,0.005
  frontdoor:
    enabled: true
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: x.x.x.61
      port: 8899
      user: xxxx
      password: xxxxx
    motion:
      mask: 0.726,0.004,0.725,0.049,0.972,0.05,0.971,0.002
  street:
    enabled: true
    birdseye:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/street
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: x.x.x.70
      port: 8899
      user: xxxx
      password: xxxxx
    motion:
      mask: 0.728,0.049,0.972,0.05,0.972,0.008,0.728,0.004
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
Unraid docker-
```

### Relevant Frigate log output

```shell
2024-09-19 12:37:09.141244780  [2024-09-19 12:37:09] watchdog.street                ERROR   : Ffmpeg process crashed unexpectedly for street.
2024-09-19 12:37:09.141332345  [2024-09-19 12:37:09] watchdog.street                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-19 12:37:09.141376850  [2024-09-19 12:37:09] ffmpeg.street.detect           ERROR   : rtsp://127.0.0.1:8554/street_sub: Invalid data found when processing input
2024-09-19 12:37:09.166254114  [2024-09-19 12:37:09] watchdog.street                ERROR   : No new recording segments were created for street in the last 120s. restarting the ffmpeg record process...
2024-09-19 12:37:09.166339515  [2024-09-19 12:37:09] watchdog.street                INFO    : Terminating the existing ffmpeg process...
2024-09-19 12:37:09.166400848  [2024-09-19 12:37:09] watchdog.street                INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-19 12:37:14.278047989  [2024-09-19 12:37:14] frigate.video                  ERROR   : street: Unable to read frames from ffmpeg process.
2024-09-19 12:37:14.278125718  [2024-09-19 12:37:14] frigate.video                  ERROR   : street: ffmpeg process is not running. exiting capture thread...
2024-09-19 12:37:24.189481260  [2024-09-19 12:37:24] watchdog.street                ERROR   : Ffmpeg process crashed unexpectedly for street.
2024-09-19 12:37:24.189485939  [2024-09-19 12:37:24] watchdog.street                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-19 12:37:24.189488146  [2024-09-19 12:37:24] ffmpeg.street.detect           ERROR   : rtsp://127.0.0.1:8554/street_sub: Invalid data found when processing input
2024-09-19 12:37:24.213757621  [2024-09-19 12:37:24] watchdog.street                ERROR   : No new recording segments were created for street in the last 120s. restarting the ffmpeg record process...
2024-09-19 12:37:24.213813397  [2024-09-19 12:37:24] watchdog.street                INFO    : Terminating the existing ffmpeg process...
2024-09-19 12:37:24.213848510  [2024-09-19 12:37:24] watchdog.street                INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-19 12:37:29.326413429  [2024-09-19 12:37:29] frigate.video                  ERROR   : street: Unable to read frames from ffmpeg process.
2024-09-19 12:37:29.326485540  [2024-09-19 12:37:29] frigate.video                  ERROR   : street: ffmpeg process is not running. exiting capture thread...
2024-09-19 12:37:39.234152825  [2024-09-19 12:37:39] watchdog.street                ERROR   : Ffmpeg process crashed unexpectedly for street.
2024-09-19 12:37:39.234157462  [2024-09-19 12:37:39] watchdog.street                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-19 12:37:39.234177590  [2024-09-19 12:37:39] ffmpeg.street.detect           ERROR   : rtsp://127.0.0.1:8554/street_sub: Invalid data found when processing input
2024-09-19 12:37:39.257572503  [2024-09-19 12:37:39] watchdog.street                ERROR   : No new recording segments were created for street in the last 120s. restarting the ffmpeg record process...
2024-09-19 12:37:39.257577888  [2024-09-19 12:37:39] watchdog.street                INFO    : Terminating the existing ffmpeg process...
2024-09-19 12:37:39.257606651  [2024-09-19 12:37:39] watchdog.street                INFO    : Waiting for ffmpeg to exit gracefully...
2024-09-19 12:37:44.370285001  [2024-09-19 12:37:44] frigate.video                  ERROR   : street: Unable to read frames from ffmpeg process.
2024-09-19 12:37:44.370346124  [2024-09-19 12:37:44] frigate.video                  ERROR   : street: ffmpeg process is not running. exiting capture thread...
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Mixed

### Camera make and model

Galayou 2K Y4

### Screenshots of the Frigate UI's System metrics pages

na
