### DISCUSSION TITLE
[Support]: Frigate 0.14.1 unable to play history on fast speeds

### DISCUSSION THREAD

**Discussion by d3relict** [blakeblackshear/frigate#13826] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Unable to play camera history on speeds 4x, 8x, or 16x, which was possible using 0.12.x.
Monitoring the machine does not indicate bottlenecks, no high disk io, no high iowait on the cpu.
I'm using 9 cameras total, and all 8 of them are displayed during this (might be related), which i can not seem to change anywhere.

### Steps to reproduce

1. open an individual camera
2. switch to history
3. navigate to a random point in time
4. select 16x playback
5. notice the stream constantly stopping and loading animation appear

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: ****
  user: ****
  password: ****

database:
  path: /media/frigate/db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  expire_interval: 360
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 15
      objects:
        car: 5

snapshots:
  enabled: true
  retain:
    default: 30

objects:
  track:
    - person
    - car
    - cat

birdseye:
  enabled: false

detect:
  stationary:
    interval: 10
    threshold: 50

go2rtc:
  streams:
    carport_1:
      - ****
    carport_2:
      - ****
    backyardeast_1:
      - ****
    backyardeast_2:
      - ****
    pavement_1:
      - ****
    pavement_2:
      - ****
    deck_1:
      - ****
    deck_2:
      - ****
    gate_1:
      - ****
    gate_2:
      - ****
    living_room_1:
      - ****
    living_room_2:
      - ****
    lenas_room_1:
      - ****
    lenas_room_2:
      - ****
    nursery_1:
      - ****
    nursery_2:
      - ****
    street_1:
      - ****
      - ffmpeg:street_1#audio=aac
    street_2:
      - ****
  webrtc:
    listen: :8555
    candidates:
      - ****
  ffmpeg:
    myraw: -probesize 32 -analyzeduration 0 -avioflags direct -rtsp_transport udp
      -framedrop

cameras:
  Street:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/street_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/street_2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - car
        - cat
    zones:
      Street-Driveway:
        coordinates: 0.931,1,0.951,0.882,0.809,0.806,0.596,0.676,0.468,0.716,0.29,0.753,0.302,1

        inertia: 3
        loitering_time: 0
  BackyardEast:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyardeast_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyardeast_2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask: 
        0,0,0.989,0,0.986,0.111,0.816,0.035,0.664,0,0.473,0,0.344,0.044,0.195,0.104,0,0.228
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 2000
          min_score: 0.60
        car:
          min_area: 25000
        cat:
          min_score: 0.40
          threshold: 0.65
    zones:
      BackyardEast-Backyard:
        coordinates: 
          0.875,0.337,0.78,0.528,0.684,0.702,0.456,0.514,0.363,0.517,0.074,0.788,0.043,0.409,0.017,0.24,0.209,0.112,0.432,0.031,0.437,0.153,0.685,0.242
        inertia: 3
        loitering_time: 0
      BackyardEast-Carport:
        coordinates: 0.805,0.051,0.802,0.171,0.705,0.243,0.58,0.195,0.436,0.151,0.434,0.027,0.593,0
        inertia: 3
        loitering_time: 0
      BackyardEast-Walkway:
        coordinates: 
          0.893,0.693,0.854,0.854,0.708,0.726,0.806,0.526,0.869,0.378,0.864,0.368,0.904,0.259,0.954,0.287,0.922,0.548

        inertia: 3
        loitering_time: 0
        objects: person
      BackyardEast-Deck:
        coordinates: 0.075,0.791,0.36,0.519,0.456,0.514,0.679,0.702,0.855,0.858,0.817,1,0.11,0.999
        inertia: 3
        loitering_time: 0
  Carport:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/carport_2
          roles:
            - detect
    detect:
      # width: 896
      width: 1280
      # height: 672
      height: 720
      fps: 10
    objects:
      track:
        - person
        - car
        - cat
      filters:
        cat:
          min_score: 0.40
          threshold: 0.65
        person:
          min_score: 0.65
          threshold: 0.75
    zones:
      Carport-Carport:
        coordinates: 
          0.017,1,0.923,1,1,0.679,1,0.581,0.66,0.387,0.488,0.298,0.263,0.388,0.029,0.502,0.014,0.785
        inertia: 3
        loitering_time: 0
      Carport-Backyard:
        coordinates: 
          0.636,0.158,0.693,0.177,0.721,0.182,0.771,0.172,0.773,0.054,0.911,0.101,1,0.154,1,0.58,0.643,0.373,0.38,0.245,0.381,0.221,0.491,0.199,0.492,0.177
        inertia: 3
        loitering_time: 0
      Carport-Pavement:
        coordinates: 
          0.489,0.297,0.233,0.395,0.031,0.498,0.073,0.187,0.112,0.17,0.142,0.251,0.205,0.228,0.264,0.285,0.38,0.248
        inertia: 3
        loitering_time: 0
      Carport-Walkway-East:
        coordinates: 0.335,0.239,0.268,0.265,0.208,0.212,0.197,0.173,0.236,0.161,0.248,0.201
        inertia: 3
        loitering_time: 0
      Carport-Walkway-North:
        coordinates: 0.44,0.186,0.487,0.199,0.336,0.234,0.305,0.219

        inertia: 3
        loitering_time: 0
  Pavement:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pavement_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pavement_2
          roles:
            - detect
    detect:
      width: 720
      height: 1280
      fps: 10
    motion:
      mask:
        - 720,321,578,199,404,87,421,22,271,0,720,0
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 2000
          max_area: 80000
        car:
          min_area: 12000
        cat:
          min_score: 0.40
          threshold: 0.65
    zones:
      Pavement-Walkway-East:
        coordinates: 307,1026,0,1074,0,331,138,328,226,782
      Pavement-Walkway-South:
        coordinates: 515,1280,693,1187,613,951,296,1031,0,1085,0,1280
      Pavement-Pavement:
        coordinates: 
          0,335,134,327,241,853,308,1021,612,949,688,1157,720,1161,720,319,482,131,450,241,222,227,0,233
      Pavement-Carport:
        coordinates: 214,223,442,240,481,124,345,47,181,31,0,30,0,226

  Deck:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
        - person
        - cat
      filters:
        cat:
          min_score: 0.40
          threshold: 0.65
    zones:
      Deck-Grass:
        coordinates: 785,175,1185,268,1118,720,413,720,224,720,360,589,348,571
      Deck-Walkway:
        coordinates: 
          548,384,738,210,608,187,407,327,234,459,228,440,58,592,157,720,194,720,351,578,349,567

  Gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gate_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_2
          roles:
            - detect
    detect:
      width: 720
      height: 1280
      fps: 10
    motion:
      mask:
        - 0,182,380,52,374,30,469,21,675,21,674,0,0,0
    objects:
      track:
        - person
        - car
        - cat
      filters:
        car:
          min_area: 7500
        cat:
          min_score: 0.40
          threshold: 0.65
    zones:
      Gate-Gate:
        coordinates: 488,141,690,146,679,23,476,19
      Gate-Driveway:
        coordinates: 608,1280,671,1034,699,658,699,355,695,147,484,136,348,317,165,575,0,833,0,1280

  LivingRoom:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_2
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 15
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        cat:
          min_score: 0.40
          threshold: 0.65
        person:
          min_score: 0.65
          threshold: 0.75
    record:
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 3
          objects:
            person: 5

  LenasRoom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/lenas_room_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lenas_room_2
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 15
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        cat:
          min_score: 0.40
          threshold: 0.65
        person:
          min_score: 0.65
          threshold: 0.75
    record:
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 3
          objects:
            person: 5

  Nursery:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nursery_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nursery_2
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.65
          threshold: 0.75
    detect:
      width: 640
      height: 360
      fps: 15
version: 0.14
camera_groups:
  Outdoors:
    order: 1
    icon: LuTreeDeciduous
    cameras:
      - BackyardEast
      - Carport
      - Deck
      - Gate
      - Street
      - Pavement
  Indoors:
    order: 2
    icon: LuSofa
    cameras:
      - LenasRoom
      - LivingRoom
      - Nursery
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /storage/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 536870912
    ports:
      - "5000:5000"
      - "1984:1984" # go2rtc
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ****
      PLUS_API_KEY: ****
    deploy:
      resources:
        limits:
          memory: 3G
```

### Relevant Frigate log output

```shell
nothing relevant
```

### Relevant go2rtc log output

```shell
nothing relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

mostly hikvision, some reolink

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/8c216643-af57-44a7-a7c9-72770cb4e9c7)
