### DISCUSSION TITLE
How to use the GPU on Celeron J4125 processors

### DISCUSSION THREAD

**Discussion by tve** [blakeblackshear/frigate#1382] [General]
I recently bought a cheap Minisforum GX41 Intel J4125 based box and am dumping Frigate onto it. It's running Ubuntu and Frigate in docker. I have one 1080p bullet camera producing an H.264 RTSP stream and 3x esp32-CAMs producing MJPEG. At first all the encoding to turn the MJPEG into H.264 used libx264, i.e. CPU. And yes, the CPU was pegged.

After beating my head against the wall trying to get the h264_qsv encoder to work I found that h264_vaapi works well. Specifically, I used the following global config:
```
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```
And then for each esp32 camera I used:
```
esp32-cam:
    ffmpeg:
      inputs:
        - path: http://esp32-cam2.voneicken.com:81
          roles:
            - detect
            - rtmp
            - clips
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -r
        - "2"
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v
 h264_vaapi -vf format=nv12,hwupload -r 2 -an
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v
h264_vaapi -vf format=nv12,hwupload -r 2 -an
        rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 2 -an -f flv
```
On the esp32 I'm using relatively high resolution (XGA or larger) so it doesn't produce a lot of FPS, which is OK with me. The firmware I use is https://github.com/easytarget/esp32-cam-webserver
The current result is that the GPU is ~22% busy and the CPU spends about that time on ffmpeg. The object detector is now chewing up 2 cores depending on the amount of motion. I'm waiting for a Coral EdgeTPU to arrive tomorrow...
Hope all this helps someone...

**Edit:**
- With Frigate 0.11.0 and later the environment variable `LIBVA_DRIVER_NAME=i965` is needed (see below or official docs)
- To check what the GPU is doing, run `sudo intel_gpu_top` (on linux), video and render should be > 0% if HW acceleration is working
