### DISCUSSION TITLE
[Camera Support]: ONVIF - The CapabilityCategory type doesn't accept collections as value

### DISCUSSION THREAD

**Discussion by bwaayer** [blakeblackshear/frigate#13845] [Camera Support] [answered]
### Describe the problem you are having

Attempting to setup ONVIF connection to my Dahua camera, initially with Authentication setup on the Dahua it would fail to connect, after disabling authentication I now receive this error in the logs: Onvif connection to driveway failed: Unknown error: The CapabilityCategory type doesn't accept collections as value

This is the same as issue:8836 albeit Frigate does not crash with this error anymore.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Chrome 128.0.6613.138

### Frigate config file

```yaml
mqtt:
  host: 192.168.30.23
  port: 1883
  user: braydon
  password: '{FRIGATE_RTSP_PASSWORD}'

detectors:
  CPU1:
    type: cpu

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic

objects:
  track:
    - person
    - cat
    - dog

detect:
  width: 1920
  height: 1080
  fps: 6

record:
  enabled: true
  retain:
    days: 5

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 7

birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous

cameras:
  entrance:
    ui:
      order: 1
    objects:
      filters:
        car:
          mask: 177,0,421,0
      track:
        - car
        - person
        - cat
        - dog
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.30.169:554/Streaming/Channels/101/?transportmode=unicast
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
  driveway:
    ui:
      order: 3
    objects:
      filters:
        car:
          mask: 177,0,421,0
      track:
        - car
        - person
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.30.190/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-generic
          roles:
            - detect   
        - path: 
            rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.30.190/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-generic
          roles:
            - record
          
    onvif:
      host: 192.168.30.190
      port: 80
      # autotracking:
      #   enabled: true
      #   calibrate_on_startup: true
      #   zooming: relative 
      #   track:
      #     - person
      #   required_zones:
      #     - door
      #   return_preset: door

  doorbell:
    ui:
      order: 2
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/frontdoor_cam
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/frontdoor_cam_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    objects:
      track:
      - person
      - dog
      - cat
    detect:
      width: 640
      height: 480
    live:
      stream_name: frontdoor_cam_sub
```

### Relevant Frigate log output

```shell
Type
error
Timestamp
2024-09-20 22:27:36
Tag
frigate.ptz.onvif
Message
Onvif connection to driveway failed: Unknown error: The CapabilityCategory type doesn't accept collections as value
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":424,"detection_enabled":true,"detection_fps":1.6,"ffmpeg_pid":439,"pid":405,"process_fps":6.1,"skipped_fps":0.0},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.0,"capture_pid":418,"detection_enabled":true,"detection_fps":5.6,"ffmpeg_pid":438,"pid":393,"process_fps":6.0,"skipped_fps":0.0},"entrance":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":412,"detection_enabled":true,"detection_fps":6.0,"ffmpeg_pid":420,"pid":392,"process_fps":6.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"113":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"118":{"cmdline":"python3 -u -m frigate","cpu":"1.4","cpu_average":"1","mem":"1.1"},"13285":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"13445":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"135":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"159":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"167":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"296":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"345":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"347":{"cmdline":"frigate.recording_manager","cpu":"1.7","cpu_average":"1","mem":"0.5"},"354":{"cmdline":"frigate.review_segment_manager","cpu":"0.3","cpu_average":"0","mem":"0.4"},"375":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"376":{"cmdline":"frigate.detector.CPU1","cpu":"153.4","cpu_average":"144","mem":"0.4"},"378":{"cmdline":"frigate.output       ","cpu":"2.2","cpu_average":"2","mem":"0.5"},"392":{"cmdline":"frigate.process:entrance","cpu":"3.5","cpu_average":"2","mem":"0.5"},"393":{"cmdline":"frigate.process:driveway","cpu":"4.2","cpu_average":"4","mem":"0.6"},"405":{"cmdline":"frigate.process:doorbell","cpu":"1.5","cpu_average":"2","mem":"0.4"},"412":{"cmdline":"frigate.capture:entrance","cpu":"2.3","cpu_average":"2","mem":"0.4"},"418":{"cmdline":"frigate.capture:driveway","cpu":"2.4","cpu_average":"2","mem":"0.4"},"420":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.30.169:554/Streaming/Channels/101/?transportmode=unicast -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/entrance@%Y%m%d%H%M%S%z.mp4 -r 6 -vf fps=6,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.5","cpu_average":"7","mem":"0.2"},"424":{"cmdline":"frigate.capture:doorbell","cpu":"0.5","cpu_average":"0","mem":"0.4"},"438":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.30.190/cam/realmonitor?channel=1&subtype=1 -r 6 -vf fps=6,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"9.6","cpu_average":"9","mem":"0.2"},"439":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_cam_sub -r 6 -vf fps=6,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.2","cpu_average":"1","mem":"0.2"},"444":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.30.190/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"1","mem":"0.1"},"445":{"cmdline":"ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.168.30.33/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ca4e995442bd29d1de1e05d248a1751e","cpu":"0.5","cpu_average":"0","mem":"0.1"},"45":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"452":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"454":{"cmdline":"ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.168.30.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/c8ff82ccb582279370bf25f97fae3c06","cpu":"1.5","cpu_average":"1","mem":"0.1"},"46":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"486":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"491":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"496":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"501":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"95":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.6","cpu_average":"0","mem":"0.1"},"frigate.full_system":{"cpu":"43.0","mem":"79.8"}},"detection_fps":13.2,"detectors":{"CPU1":{"detection_start":0.0,"inference_speed":39.12,"pid":376}},"gpu_usages":{"intel-vaapi":{"gpu":"2.23%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":345},"recording":{"pid":347},"review_segment":{"pid":354}},"service":{"last_updated":1726831458,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":1008.6,"mount_type":"tmpfs","total":1024.0,"used":15.4},"/media/frigate/clips":{"free":5410.0,"mount_type":"zfs","total":942019.6,"used":936609.6},"/media/frigate/recordings":{"free":5410.0,"mount_type":"zfs","total":942019.6,"used":936609.6},"/tmp/cache":{"free":17439.7,"mount_type":"overlay","total":40013.2,"used":20509.5}},"temperatures":{},"uptime":3402,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Object Detector

CPU (no Coral)

### Network connection

Wired

### Camera make and model

Dahua DH-SD42212T-HN

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/5bf110e0-9913-4981-8611-6acd06a33ee9)
