### DISCUSSION TITLE
[Support]: recording playback not working in Chrome

### DISCUSSION THREAD

**Discussion by GoldieLocks89** [blakeblackshear/frigate#13849] [General Support]
### Describe the problem you are having

Playing back a recording does not work, I just get the preview image from the sub stream and a black spinner, and it never plays.
Live view is working perfectly. 
Exporting and downloading clips and they work perfectly. 
Some cameras are H264 and others are H265, but I'm in Chrome Version 129.0.6668.59 (Official Build) (64-bit) so that shouldn't be an issue right? 
I've tried to transcode to H264 and the issue is still there, so to me it doesn't seem like that's the issue - but I'm happy to be schooled!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: frigate-mqtt
  password: XXXX
  host: server

#logger:
  # Optional: default log level (default: shown below)
  #default: debug

tls:
  enabled: false

auth:
  enabled: false

go2rtc:
  streams:
    driveway_front: 
      rtsp://user:XXXX@192.168.2.201/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    driveway_front_sub: 
      rtsp://user:XXXX@192.168.2.201/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    driveway_back: 
      rtsp://user:XXXX@192.168.2.123/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    driveway_back_sub: 
      rtsp://user:XXXX@192.168.2.123/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    front_left: 
      rtsp://user:XXXX@192.168.2.144/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front_left_sub: 
      rtsp://user:XXXX@192.168.2.144/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    front_right: 
      rtsp://user:XXXX@192.168.2.235/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front_right_sub: 
      rtsp://user:XXXX@192.168.2.235/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    back_garden: 
      rtsp://user:XXXX@192.168.2.147/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    back_garden_sub: 
      rtsp://user:XXXX@192.168.2.147/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    doorbell: 
      rtsp://admin:XXXX@192.168.2.238:8554/cam/realmonitor?channel=1&subtype=0&authbasic=auth64#backchannel=0
    doorbell_sub: 
      rtsp://admin:XXXX@192.168.2.238:8554/cam/realmonitor?channel=1&subtype=1&authbasic=auth64#backchannel=0

detectors:
  #cpu1:
  #  type: cpu
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - car
    - dog
    - cat
    - bird

ffmpeg:
  input_args: preset-rtsp-restream
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 5
    post_capture: 20
    retain:
      default: 7
      mode: active_objects

cameras:
  driveway_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_front
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_front_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 360
      height: 640
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    zones:
      driveway:
        coordinates: 1,0,0.669,0,0.227,0,0.136,0.133,0.231,0.231,0.058,0.325,0.278,0.48,1,1
        inertia: 3
  driveway_back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_back?video&audio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_back_sub?video&audio
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    zones:
      driveway:
        coordinates: 
          1,1,1,0,0.901,0,0.883,0.192,0.872,0.4,0.731,0.436,0.573,0.481,0.312,0.489,0.048,0.519,0.033,0.211,0,0.256,0,1
        inertia: 3
    motion:
      threshold: 40
      contour_area: 30
      improve_contrast: true
  front_left:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_left
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_left_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 6
    zones:
      front_garden:
        coordinates: 640,480,640,384,640,296,590,303,505,294,422,281,318,267,200,258,69,282,0,480
  front_right:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_right
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_right_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 480
      height: 640
      fps: 6
    zones:
      front_garden:
        coordinates: 116,640,224,477,312,353,361,263,393,162,371,103,247,48,87,0,39,233,0,640
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    motion: {}
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video&audio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video&audio
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 720
      height: 576
      fps: 10
    zones:
      front_garden:
        coordinates: 
          0.001,0.734,0.12,0.672,0.194,0.694,0.282,0.718,0.395,0.755,0.493,0.766,0.553,0.773,0.684,0.787,0.802,0.787,0.86,0.784,0.932,0.8,0.994,0.818,0.998,0.999,0.002,0.999
        inertia: 3
      front_garden_entrance:
        coordinates: 
          0,0.649,0.114,0.6,0.264,0.618,0.415,0.664,0.532,0.683,0.689,0.693,0.869,0.687,0.957,0.679,0.995,0.69,0.997,0.81,0.866,0.779,0.684,0.784,0.515,0.763,0.402,0.752,0.29,0.72,0.19,0.69,0.122,0.664,0.001,0.728
        inertia: 3
    motion:
      contour_area: 60

version: 0.14
camera_groups:
  Front:
    order: 1
    icon: LuSquirrel
    cameras:
      - front_left
      - front_right
      - doorbell
  Driveway:
    order: 2
    icon: LuCar
    cameras:
      - driveway_front
      - driveway_back
  Back:
    order: 3
    icon: LuFlower
    cameras: back_garden
```

### Relevant Frigate log output

```shell
2024-09-20 12:42:24.364470827  [INFO] Preparing Frigate...
2024-09-20 12:42:24.427966859  [INFO] Starting Frigate...
2024-09-20 12:42:25.695528169  [2024-09-20 12:42:25] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-20 12:42:25.695548691  [2024-09-20 12:42:25] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-20 12:42:25.718241063  [2024-09-20 12:42:25] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-20 12:42:25.952013052  [2024-09-20 12:42:25] peewee_migrate.logs            INFO    : Starting migrations
2024-09-20 12:42:25.952324031  [2024-09-20 12:42:25] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-20 12:42:25.974748864  [2024-09-20 12:42:25] frigate.app                    INFO    : Recording process started: 382
2024-09-20 12:42:25.977849706  [2024-09-20 12:42:25] frigate.app                    INFO    : Recording process started: 386
2024-09-20 12:42:25.978885960  [2024-09-20 12:42:25] frigate.app                    INFO    : go2rtc process pid: 96
2024-09-20 12:42:25.991957956  [2024-09-20 12:42:25] detector.ov                    INFO    : Starting detection process: 411
2024-09-20 12:42:25.993477355  [2024-09-20 12:42:25] frigate.app                    INFO    : Output process started: 413
2024-09-20 12:42:26.176078367  [2024-09-20 12:42:26] frigate.app                    INFO    : Camera processor started for driveway_front: 429
2024-09-20 12:42:26.180526363  [2024-09-20 12:42:26] frigate.app                    INFO    : Camera processor started for driveway_back: 430
2024-09-20 12:42:26.185700304  [2024-09-20 12:42:26] frigate.app                    INFO    : Camera processor started for front_left: 433
2024-09-20 12:42:26.190718924  [2024-09-20 12:42:26] frigate.app                    INFO    : Camera processor started for front_right: 446
2024-09-20 12:42:26.197728404  [2024-09-20 12:42:26] frigate.app                    INFO    : Camera processor started for back_garden: 461
2024-09-20 12:42:26.203351562  [2024-09-20 12:42:26] frigate.app                    INFO    : Camera processor started for doorbell: 464
2024-09-20 12:42:26.208042780  [2024-09-20 12:42:26] frigate.app                    INFO    : Capture process started for driveway_front: 470
2024-09-20 12:42:26.212555702  [2024-09-20 12:42:26] frigate.app                    INFO    : Capture process started for driveway_back: 479
2024-09-20 12:42:26.217225441  [2024-09-20 12:42:26] frigate.app                    INFO    : Capture process started for front_left: 484
2024-09-20 12:42:26.223399880  [2024-09-20 12:42:26] frigate.app                    INFO    : Capture process started for front_right: 486
2024-09-20 12:42:26.228031637  [2024-09-20 12:42:26] frigate.app                    INFO    : Capture process started for back_garden: 495
2024-09-20 12:42:26.235141233  [2024-09-20 12:42:26] frigate.app                    INFO    : Capture process started for doorbell: 501
```

### Relevant go2rtc log output

```shell
2024-09-20 12:42:24.428178956  [INFO] Preparing new go2rtc config...
2024-09-20 12:42:24.810694171  [INFO] Starting go2rtc...
2024-09-20 12:42:24.897520107  12:42:24.897 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-20 12:42:24.897571435  12:42:24.897 INF config path=/dev/shm/go2rtc.yaml
2024-09-20 12:42:24.897908926  12:42:24.897 INF [rtsp] listen addr=:8554
2024-09-20 12:42:24.898035696  12:42:24.898 INF [webrtc] listen addr=:8555/tcp
2024-09-20 12:42:24.898570862  12:42:24.898 INF [api] listen addr=:1984
2024-09-20 12:42:34.363271758  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"back_garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":495,"detection_enabled":true,"detection_fps":1.0,"ffmpeg_pid":512,"pid":461,"process_fps":10.1,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":501,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":516,"pid":464,"process_fps":10.0,"skipped_fps":0.0},"driveway_back":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.0,"capture_pid":479,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":485,"pid":430,"process_fps":6.0,"skipped_fps":0.0},"driveway_front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":470,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":483,"pid":429,"process_fps":10.0,"skipped_fps":0.0},"front_left":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":484,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":493,"pid":433,"process_fps":6.1,"skipped_fps":0.0},"front_right":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":486,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":500,"pid":446,"process_fps":6.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"1.6","cpu_average":"2","mem":"1.5"},"12460":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"125":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1673":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(56)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"179":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"180":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"181":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"182":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"184":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"361":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"379":{"cmdline":"sleep 9999","cpu":"0.0","cpu_average":"0","mem":"0.0"},"380":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"382":{"cmdline":"frigate.recording_manager","cpu":"1.3","cpu_average":"1","mem":"0.5"},"386":{"cmdline":"frigate.review_segment_manager","cpu":"0.5","cpu_average":"0","mem":"0.4"},"410":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(67)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"411":{"cmdline":"frigate.detector.ov  ","cpu":"0.5","cpu_average":"3","mem":"0.7"},"413":{"cmdline":"frigate.output       ","cpu":"1.0","cpu_average":"1","mem":"0.4"},"429":{"cmdline":"frigate.process:driveway_front","cpu":"0.6","cpu_average":"0","mem":"0.6"},"430":{"cmdline":"frigate.process:driveway_back","cpu":"0.5","cpu_average":"0","mem":"0.6"},"433":{"cmdline":"frigate.process:front_left","cpu":"0.5","cpu_average":"1","mem":"0.6"},"446":{"cmdline":"frigate.process:front_right","cpu":"0.5","cpu_average":"0","mem":"0.6"},"45":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"461":{"cmdline":"frigate.process:back_garden","cpu":"1.2","cpu_average":"1","mem":"0.6"},"464":{"cmdline":"frigate.process:doorbell","cpu":"1.1","cpu_average":"1","mem":"0.6"},"470":{"cmdline":"frigate.capture:driveway_front","cpu":"0.4","cpu_average":"0","mem":"0.6"},"479":{"cmdline":"frigate.capture:driveway_back","cpu":"0.2","cpu_average":"0","mem":"0.6"},"483":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_front_sub -r 10 -vf fps=10,scale_vaapi=w=360:h=640:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.1"},"484":{"cmdline":"frigate.capture:front_left","cpu":"0.3","cpu_average":"0","mem":"0.6"},"485":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_back_sub?video&audio -r 6 -vf fps=6,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.5","cpu_average":"0","mem":"0.1"},"486":{"cmdline":"frigate.capture:front_right","cpu":"0.3","cpu_average":"0","mem":"0.6"},"493":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_left_sub -r 6 -vf fps=6,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.5","cpu_average":"0","mem":"0.1"},"494":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_front@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"495":{"cmdline":"frigate.capture:back_garden","cpu":"0.4","cpu_average":"0","mem":"0.6"},"500":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_right_sub -r 6 -vf fps=6,scale_vaapi=w=480:h=640:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.7","cpu_average":"0","mem":"0.1"},"501":{"cmdline":"frigate.capture:doorbell","cpu":"0.5","cpu_average":"0","mem":"0.6"},"505":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_back?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/driveway_back@%Y%m%d%H%M%S%z.mp4","cpu":"1.3","cpu_average":"1","mem":"0.1"},"512":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_garden_sub -r 10 -vf fps=10,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.1"},"513":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_left -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_left@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"516":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_sub?video&audio -r 10 -vf fps=10,scale_vaapi=w=720:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"0","mem":"0.1"},"517":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_right -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_right@%Y%m%d%H%M%S%z.mp4","cpu":"0.2","cpu_average":"0","mem":"0.1"},"520":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_garden@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"523":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.1"},"721":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 360x640 -i pipe: -threads 1 -f mpegts -s 405x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"726":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"732":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"737":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 480x640 -i pipe: -threads 1 -f mpegts -s 540x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"742":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"747":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -threads 1 -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"752":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"96":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"11.5","cpu_average":"11","mem":"0.2"},"frigate.full_system":{"cpu":"5.0","mem":"48.3"}},"detection_fps":1.1,"detectors":{"ov":{"detection_start":0.0,"inference_speed":6.14,"pid":411}},"gpu_usages":{"intel-vaapi":{"gpu":"0.29%","mem":"-%"}},"processes":{"go2rtc":{"pid":96},"logger":{"pid":380},"recording":{"pid":382},"review_segment":{"pid":386}},"service":{"last_updated":1726835817,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":505.1,"mount_type":"tmpfs","total":512.0,"used":6.9},"/media/frigate/clips":{"free":611694.8,"mount_type":"fuse.shfs","total":5723166.5,"used":5109148.2},"/media/frigate/recordings":{"free":611694.8,"mount_type":"fuse.shfs","total":5723166.5,"used":5109148.2},"/tmp/cache":{"free":833.1,"mount_type":"tmpfs","total":953.7,"used":120.6}},"temperatures":{},"uptime":3271,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

various - mostly Hikvision

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/9ce5ec2b-9efc-449d-8342-a6bcd2085fcc)
![image](https://github.com/user-attachments/assets/158f7672-5c91-4264-8fcc-910f42cc6679)

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/fc6c97de-9cc6-4fbb-b508-84866f027fa1)
