### DISCUSSION TITLE
Sharing cameras between 2 VPN nodes

### DISCUSSION THREAD

**Discussion by madjetey** [blakeblackshear/frigate#13844] [General Support]
I have Frigate running in Home Assistant supervised on 2 servers on separate networks across a field. Both HA instances are linked by Tailscale VPN and now I'm struggling trying to push one of the camera feeds from one instance into Frigate on the other.  Since I'm using go2rtc to manage my streams on both machines, I tried pushing the stream via port 1984, 8554 and 5000 but I can't figure out the proper path to use for any of those.

Server 1 (sending)
```
go2rtc:
  streams:
    FrigateCam1:
      - rtsp://localip:36855/683d353e5bf33313
      - ffmpeg:rtsp_cam#audio=copy#audio=opus
cameras:
  LocalCam:
      inputs:
       # High resolution
        - path: rtsp://127.0.0.1:8554/FrigateCam1
          roles:
            - record
```

Server 2 (receiving)
```
go2rtc:
  streams:
    LocalCam:
      - rtsp://user:password@localip:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:#video=copy#audio=copy#audio=aac
    RemoteCam:
      - rtsp://tailscaleip:8554/FrigateCam1
      #- http://tailscaleip:1984/api/stream.mp4?src=FrigateCam1&mp4=flac
      - ffmpeg:#video=copy#audio=copy#audio=aac
cameras:
  LocalCam:
      inputs:
       # High resolution
        - path: rtsp://127.0.0.1:8554/LocalCam
          roles:
            - record
  RemoteCam:
      inputs:
       # High resolution
        - path: rtsp://127.0.0.1:8554/RemoteCam
          roles:
            - record
```
