### DISCUSSION TITLE
[Support]: WS Error from Frigate Proxy into Frigate

### DISCUSSION THREAD

**Discussion by JoshuaSeidel** [blakeblackshear/frigate#13857] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Ive been having troubles with notifications on iOS18 they wont display snapshots or clips most of the time, sometimes frigate doesnt even have the images its referencing, sometimes it does. while troubleshooting i noticed the errors in frigate proxy and then coorisponding errors in frigate and i wonder if they are connected to my issue. this is with the /ws endpoint

### Steps to reproduce

1. setup notifications
2. get movement or object detection
3. check on logs
...

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Google Chrome 127.0.6533.122

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: frigate_mqtt
  password: password
  host: 192.168.7.83

ffmpeg:
  hwaccel_args: preset-nvidia-h264
 # input_args: preset-rtsp-stream
  #output_args:
   # record: preset-record-generic-audio-copy


cameras:
  steps_cam: # <------ Name the camera
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      inputs:
        #- path: rtsp://192.68.9.144:37039/b042a8dc7e3d6779?rtsp_transport=udp
        - path: rtsp://wb:cCa3gT-password@wyze-bridge:8554/steps-cam # <----- The stream you want to use for detection
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
    review:
      detections:
        labels:
          - dog
          - person
        required_zones: steps
    zones:
      steps:
        coordinates: 0.412,0.006,0.222,1,0.824,1,0.578,0.009
        loitering_time: 0
    motion:
      mask: 0.723,0.938,0.974,0.933,0.976,0.98,0.723,0.979

  doorbell:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: doorbell
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
    review:
      detections:
        labels:
          - dog
          - person
      alerts:
        required_zones:
          - Porch
          - sidewalk
    zones:
      Porch:
        coordinates: 
          0.381,0.999,0.384,0.961,0.47,0.969,0.473,0.908,0.723,0.866,0.73,0.874,0.875,0.801,0.999,0.881,0.999,0.999
        loitering_time: 0
        objects:
          - package
          - person
          - dog
          - cat
        inertia: 3
      sidewalk:
        coordinates: 
          0.57,0.897,0.584,0.791,0.624,0.758,0.67,0.74,0.706,0.724,0.698,0.78,0.696,0.82,0.694,0.866
        loitering_time: 0
        objects:
          - dog
          - person
  driveway:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
      filters:
        car: {}
    review:
      detections:
        labels:
          - dog
          - person
          - car
          - motorcycle
    #onvif:
    #  host: 192.168.9.4
    #  port: 8000
    #  user: admin
    #  password: uu9zu7sdR6i
    #  autotracking:
    #    enabled: false
    #    calibrate_on_startup: false
    #    zooming: absolute
    #    zoom_factor: 0.3
    #    track:
    #      - person
    #      - car
    #    return_preset: home
    #    timeout: 10
    #    required_zones:
    #      - complete
        #required_zones: complete
      #alerts:
        #required_zones: leanna-parking
      alerts:
        required_zones: parking
    zones:
      parking:
        coordinates: 0,0.631,0.228,0.372,0.223,0.297,0.639,0.483,0.577,1,0.014,0.998
        inertia: 3
        loitering_time: 0
    motion:
      threshold: 41
      contour_area: 30
      improve_contrast: 'true'
      mask: 0.583,0.933,0.988,0.931,0.989,0.971,0.585,0.974
version: 0.14

go2rtc:
  streams:
    steps_Cam:
      - rtsp://192.168.9.144:37039/b042a8dc7e3d6779?rtsp_transport=udp
      - rtsp://wb:cCa3gT-password@wyze-bridge:8554/steps-cam
    doorbell:
      - rtsp://nvr:password@192.168.9.127:554/Preview_01_main#backchannel=0
      #- rtsp://nvr:password@192.168.9.127:554/Preview_01_sub
      - ffmpeg:doorbell#audio=aac#hardware#video=h264
    doorbell_sub:
      - ffmpeg:http://192.168.9.127/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=nvr&password=password
      - ffmpeg:doorbell#audio=aac#hardware
    driveway:
      - rtsp://nvr:password@192.168.9.4:554/Preview_01_main
    driveway_sub:
      - rtsp://nvr:password@192.168.9.4:554/Preview_01_sub
  webrtc:
    candidates:
      - 192.168.9.144:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

detectors:
  coral:
    type: edgetpu
    device: pci

#detectors:
 # tensorrt:
  #  type: tensorrt
   # device: 0

model:
  path: plus://api_key

#model:
 # path: /config/model_cache/tensorrt/yolov7-320.trt
 # input_tensor: nchw
 # input_pixel_format: rgb
 # width: 320
 # height: 320

review:
  alerts:
    labels:
      - person
      - dog
      - car
      - ups
      - fedex
      - amazon
  detections:
    labels:
      - person
      - dog
      - car
      - ups
      - fedex
      - amazon

record:
  enabled: true
  retain:
    days: 7
    mode: motion

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 800
  height: 480
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  mode: continuous #motion #objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

tls:
  enabled: true

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

# Include all cameras by default in Birdseye view
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "8GB" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/nvidia0:/dev/dri/nvidia0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .config:/config
      - /mnt/data/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "443:8971"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "key"
      TRT_MODEL_PREP_DEVICE: '0'
    networks:
       - secure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
networks:
  secure:
    external: true
```

### Relevant Frigate log output

```shell
2024-09-19 20:00:22.952507499 Traceback (most recent call last): 2024-09-19 20:00:22.952559044 File “/usr/lib/python3.9/wsgiref/handlers.py”, line 137, in run 2024-09-19 20:00:22.952565383 self.result = application(self.environ, self.start_response) 2024-09-19 20:00:22.952571516 File “/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgiutils.py”, line 101, in call 2024-09-19 20:00:22.952576606 raise HandshakeError(‘Header %s is not defined’ % key) 2024-09-19 20:00:22.952581650 ws4py.exc.HandshakeError: Header HTTP_UPGRADE is not defined
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolink

### Screenshots of the Frigate UI's System metrics pages

n/a
