### DISCUSSION TITLE
RTSP via VLC works. Not in Frigate.

### DISCUSSION THREAD

**Discussion by thesebastianf** [blakeblackshear/frigate#13854] [Ask A Question]
Hey
I already have a couple of cameras in frigate.
Today I tried to add a new one but I only see it timed out in frigate.

When I open the RTSP stream in VLC the camera actually shows a video.
Any hints how I could investigate further what could be the issue?

Thanks

```
2024-09-20 17:15:37.881008501  [2024-09-20 17:15:37] audio.mobil                    ERROR   : ffmpeg process is not running, restarting...
2024-09-20 17:15:41.683653201  [2024-09-20 17:15:41] watchdog.haustuere             ERROR   : Ffmpeg process crashed unexpectedly for haustuere.
2024-09-20 17:15:41.683662811  [2024-09-20 17:15:41] watchdog.haustuere             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-09-20 17:15:41.683666680  [2024-09-20 17:15:41] ffmpeg.haustuere.detect        ERROR   : [tcp @ 0x56244ebf9380] Connection to tcp://192.168.1.119:554?timeout=5000000 failed: Connection timed out
2024-09-20 17:15:41.683669974  [2024-09-20 17:15:41] ffmpeg.haustuere.detect        ERROR   : rtsp://192.168.1.119:554/user=*&password=* Connection timed out
```

**Comment by NickM-27** [comment]
vlc uses udp by default, you could try using udp in frigate

**Reply by thesebastianf** [reply]
unfortunately same timeout error

```
      inputs:
        - path: rtsp://192.168.1.119:554/user=admin&password=aaa&channel=1&stream=0.sdp
          input_args: preset-rtsp-udp
          roles:
            - rtmp
            - record
#            - detect
        - path: rtsp://192.168.1.119:554/user=admin&password=aaa&channel=1&stream=1.sdp
          input_args: preset-rtsp-udp
          roles:
            - detect
            - audio
```

**Reply by NickM-27** [reply]
the camera is just not sending data consistently, frigate needs a constant stream to be able to decode the stream correctly, VLC is able to avoid these errors because it is just displaying a stream

**Reply by thesebastianf** [reply]
mhhh 
I think its something else.
I had cameras at distances that reached barely wifi, pings to them 500ms and above and frigate still works with them. sometimes the seconds counter from the camera even jumped multiple seconds and frigate still did it.

the above camera is for testing inside currently close to the router with max mbit connected to the wifi and I can ping it under 10ms

**Reply by NickM-27** [reply]
Timeout error means it's not receiving data in the required amount of time, there's not any ambiguity there. You could try increasing the timeout in the input args and see if that helps

**Reply by thesebastianf** [reply]
I noticed now the timeout still shows TCP
` [tcp @ 0x5fd25e868440] Connection to tcp://192.168.1.119:554?timeout=5000000 failed: Connection timed out`

I added the input arg udp config as above. so should the log say udp:// ?

**Reply by NickM-27** [reply]
hmm, are you sure you are editing the correct config? I would expect that you would have config errors due to duplicated `detect` role and `rtmp` role is no longer valid

**Reply by thesebastianf** [reply]
yes definately the correct config as the camera is shown on the UI also after I added the config for it today.
one of the detects is commented out above #. so no duplicated error.
RTMP I didnt know - but its not throwing errors in validation aswell.

![image](https://github.com/user-attachments/assets/31f820ab-0bcf-49db-bdd2-43430c44ab7b)

**Reply by thesebastianf** [reply]
```
  haustuere:
    ffmpeg:
      retry_interval: 20        
      inputs:
        - path: rtsp://192.168.1.119:554/user=admin&password=aaa&channel=1&stream=0.sdp
          input_args: preset-rtsp-udp
          roles:
            - rtmp
            - record
#            - detect
        - path: rtsp://192.168.1.119:554/user=admin&password=aaa&channel=1&stream=1.sdp
          input_args: preset-rtsp-udp
          roles:
            - detect
            - audio
  
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
      fps: 5

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 7
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True

    record:
      enabled: True
      retain:
        days: 30
#        mode: motion
        mode: active_objects

      events:
        retain:
          default: 30
          mode: active_objects



    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 90
        # Optional: Per object retention days
        # objects:
        #   person: 15


    objects:
      track:
        - person
        - bird
        - dog
        - cat

```

**Reply by thesebastianf** [reply]
this is the full config ... I just lazy copied a working config for another camera and changed the RTSP in my frist try.
RTMP is actually disabled a bit lower in the config. I should clean my configs up. 
However I hope this nor related that this camera is not working as all others do work.

**Reply by NickM-27** [reply]
right, you're running an outdated version of frigate which explains that.

**Reply by NickM-27** [reply]
maybe try setting the input args at the main camera level

**Reply by thesebastianf** [reply]
as a test I added the camera with a minimalistic config. same timeout.  (also tried UDP again)

```
  test:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: True
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://192.168.1.119:554/user=admin&password=aaa&channel=1&stream=1.sdp
          roles:
            - audio
            - detect
            - record
```

**Reply by thesebastianf** [reply]
> maybe try setting the input args at the main camera level

ok will try :)

**Reply by thesebastianf** [reply]
> maybe try setting the input args at the main camera level

that reults in a config validation error

**Reply by thesebastianf** [reply]
I checked the codec infos in VLC (camera does not allow to change it)
it's H265 ... is that the issue? Frigate only can do 264?

![image](https://github.com/user-attachments/assets/79ce0177-e0da-4d7c-8d64-dc6f2d85f698)

**Reply by NickM-27** [reply]
Frigate supports h.265 without any issues

> that reults in a config validation error

what did you put? most likely it was not done correclty

**Reply by thesebastianf** [reply]
> what did you put? most likely it was not done correclty

sorry it took a while. I upgraded to latest stable frigate ... so many changes in config needed .. :(

but my problem is still persisting.
I again tried UDP at camera level --> Still shows TCP timeout
I also tried UDP at globale level -> also the log says TCP timeout

```
# Global ffmpeg configuration
ffmpeg:
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-udp
  retry_interval: 10
```

![image](https://github.com/user-attachments/assets/7f2583e3-ae67-4c27-9c91-c378aec21f09)
