### DISCUSSION TITLE
[TRT] [W] Unable to determine GPU memory usage

### DISCUSSION THREAD

**Discussion by joeblack2k** [blakeblackshear/frigate#13876] [Detector Support]
### Describe the problem you are having

I have been struggling with this for more then 8 hours now.. i can't figure this one out.

i tried: other drivers 535 550 and 560

running the small cuda docker works and i get smi on that.. just not on frigate..

### Version

i don't have webui but its the latest

### Frigate config file

```yaml
there is no config file yet
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.14.1-tensorrt
    container_name: frigate
    networks:
      - mediaserver
    environment:
      - FRIGATE_RTSP_PASSWORD=enterpassword
      - PLUS_API_KEY=
      - NVIDIA_VISIBLE_DEVICES=ALL
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - YOLO_MODELS=yolov4-416
    volumes:
      - /media/appdata/frigate:/config
      - /media/array/media/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - /tmp/cache:/tmp/cache:tmpfs
    ports:
      - 8971:8971
      - 3554:3554
      - 5051:5000
      - 3555:8555/tcp
      - 3555:8555/udp
  
    shm_size: '1gb'
    restart: unless-stopped

networks:
  mediaserver:
    external: true
```

### Relevant Frigate log output

```shell
TypeError: pybind11::init(): factory function returned nullptr

[09/21/2024-20:36:05] [TRT] [W] Unable to determine GPU memory usage

[09/21/2024-20:36:05] [TRT] [W] Unable to determine GPU memory usage

[09/21/2024-20:36:05] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

Loading the ONNX file...

Available tensorrt models:

ls: cannot access '*.trt': No such file or directory

s6-rc: warning: unable to start service trt-model-prepare: command exited 2
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

-

### Any other information that may be helpful

inside the LXC:

root@cameras:/media/array/downloads# nvidia-smi
Sat Sep 21 20:35:23 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    Off |   00000000:01:00.0 Off |                  N/A |
| 44%   42C    P8             11W /  125W |       1MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

inside the proxmox:

root@pve:/media/array/downloads# nvidia-smi
Sat Sep 21 20:31:28 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    On  |   00000000:01:00.0 Off |                  N/A |
| 44%   46C    P0             28W /  125W |       1MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
