### DISCUSSION TITLE
Change Motion Configuration via API / MQTT?

### DISCUSSION THREAD

**Discussion by forkineye** [blakeblackshear/frigate#1387] [Ask A Question]
I'm having to really crank the sensitivity on one of my cameras to pickup people in the  yard at night.  It's more motion related vs object detection related.  With the default settings, motion detection wasn't even grabbing this.  Using the following config tracks it enough for object detection to grab it. I tried being more conservative with threshold and delta_alpha, but this was the only way to make it reliable.  I'm also using an object person filter ```min_score: 0.4``` and zone person filter ```threshold: 0.5```.  This of course makes it way too sensitive for the daytime and I'm getting person detections from clouds in my vehicle windows. Being able to change motion settings based on day / night via automation or other means would be handy.  From looking at the docs, it doesn't seem possible right now.  Any tips on how to handle this?
```yaml
    width: 896
    height: 512
    fps: 5
    motion:
      threshold: 10
      contour_area: 40
      delta_alpha: 0.8
      frame_alpha: 0.1
      frame_height: 180
```
![image](https://user-images.githubusercontent.com/4047923/125650753-ca2e19b4-8f6f-4bc7-811c-7595b2a45590.png)
![image](https://user-images.githubusercontent.com/4047923/125650360-d9ab7dc6-5293-4c38-b02c-f4795c2adaae.png)
