### DISCUSSION TITLE
[Support]: ONVIF IP Address substitution.

### DISCUSSION THREAD

**Discussion by Damien0505** [blakeblackshear/frigate#13887] [General Support] [answered]
### Describe the problem you are having

I have a camera which supports PTZ via ONVIF.  It has WIFI and a wired network connection.  Currently due to access difficulties I am using it over WIFI.

Any other software seems to use the correct IP address (WIFI interface) for the ONVIF and hence PTZ controls, but for some reason Frigate wants to use the wired network connection address; I am assuming this is being sent back when the connection for ONVIF is being queried.

Is there anyway I can force Frigate to use the WIFI IP address for the PTZ control, or have it substitute the correct address in as I am unable to disable the wired NIC in the camera.

(IP address for WIFI connection is 10.0.0.51, Frigate is trying to connect via 192.168.1.10 which is for the wired NIC that is not connected)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# ~/docker/frigate/config.yml
# yaml-language-server: $schema=http://10.13.2.217:5000/api/config/schema.json

# ui:
#   use_experimental: false
#   live_mode: mse

mqtt:
  host: 10.0.0.34
  port: 1883
  user: MQTT_User
  password: xxxx
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

record:
  expire_interval: 10

#ffmpeg:
  #hwaccel_args: preset-nvidia
  #hwaccel_args: preset-nvidia-h264

# Only enable the detector if you are using coral PCIe passthrough
detectors:
  #coral:
  #  type: edgetpu
  #  device: pci
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

logger:
#  default: info
  logs:
    frigate.ptz.onvif: debug


live:
  height: 720
  quality: 8

timestamp_style:
  position: "tr"
  format: "%d/%m/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 8
  mode: continuous
  layout:
    scaling_factor: 3.0

go2rtc:
  streams:
    backyard:
      - rtsp://xxxx:xxxx@10.0.0.52:554/stream1
    #driveway:
    #  - rtsp://xxxx:xxxx@10.0.0.51:554/user=xxxx_password=xxxx_channel=0_stream=0&onvif=0.sdp?real_stream
    driveway_crop:
      - ffmpeg:rtsp://xxxx:xxxx@10.0.0.51:554/user=xxxx_password=xxxx_channel=0_stream=0&onvif=0.sdp?real_stream#video=h265#hardware#raw=-vf
        "crop=iw:ih/2:0:0"                                                                                                                                                  #Driveway_crop top
    frontdoor_crop:
      - ffmpeg:rtsp://xxxx:xxxx@10.0.0.51:554/user=xxxx_password=xxxx_channel=0_stream=0&onvif=0.sdp?real_stream#video=h265#hardware#raw=-vf
        "crop=iw:ih/2:0:oh"                                                                                                                                                  #Frontdoor_crop bottom
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@10.0.0.52:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxxx:xxxx@10.0.0.52:554/stream2
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
      max_disappeared: 200
    objects:
      track:
        - person
        - dog
        - cat
        - cow
        - horse
        - sheep
        - bear
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
        bird:
          min_score: 0.5
          threshold: 0.6
          min_area: 250
        cat:
          min_score: 0.4
          threshold: 0.5
          min_area: 150

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 30
        mode: motion
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 10
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
  Drive1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_crop
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2304
      height: 1296
      fps: 5
    #onvif:
    #  host: 10.0.0.51
    #  port: 8899
    #  user: frigate
    #  password: xxxx
    objects:
      track:
        - person
        - dog
        - cat
        - cow
        - horse
        - sheep
        - bear
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
        bird:
          min_score: 0.5
          threshold: 0.6
          min_area: 250
        cat:
          min_score: 0.4
          threshold: 0.5
          min_area: 150
        car:
          min_score: 0.6
          threshold: 0.7
          min_area: 250
        bicycle:
          min_score: 0.6
          threshold: 0.7
          min_area: 250
        motorcycle:
          min_score: 0.6
          threshold: 0.7
          min_area: 250
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 10
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.273,0.413,0.378,0.415,0.428,0.328,0.432,0.126,0.261,0.138
  Frontdoor1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_crop
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2304
      height: 1296
      fps: 5
    onvif:
      host: 10.0.0.51
      port: 8899
      user: frigate
      password: xxxx
      ignore_time_mismatch: true
      
    objects:
      track:
        - person
        - dog
        - cat
        - cow
        - horse
        - sheep
        - bear
        - car
        - bicycle
        - motorcycle
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
        bird:
          min_score: 0.5
          threshold: 0.6
          min_area: 250
        cat:
          min_score: 0.4
          threshold: 0.5
          min_area: 150
        car:
          min_score: 0.6
          threshold: 0.7
          min_area: 250
        bicycle:
          min_score: 0.6
          threshold: 0.7
          min_area: 250
        motorcycle:
          min_score: 0.6
          threshold: 0.7
          min_area: 250
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 10
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.998,0.992,0.998,0,0.973,0.091,0.972,0.34,0.825,0.449,0.807,0.698
version: 0.14
camera_groups:
  BirdseyeGroup:
    order: 1
    icon: LuWebcam
    cameras: birdseye
```

### Relevant Frigate log output

```shell
2024-09-23 00:25:47.484033366  [2024-09-23 00:25:47] frigate.ptz.onvif              DEBUG   : Onvif media xaddr for Frontdoor1: http://192.168.1.10:8899/onvif/media_service
2024-09-23 00:25:47.484775285  [2024-09-23 00:25:47] frigate.ptz.onvif              DEBUG   : Onvif capabilities for Frontdoor1: ('http://192.168.1.10:8899/onvif/ptz_service', '/usr/local/lib/python3.9/site-packages/wsdl/ptz.wsdl', '{http://www.onvif.org/ver20/ptz/wsdl}PTZBinding')
2024-09-23 00:27:57.138234412  [2024-09-23 00:27:57] frigate.ptz.onvif              ERROR   : Unable to get Onvif media profiles for camera: Frontdoor1: Unknown error: HTTPConnectionPool(host='192.168.1.10', port=8899): Max retries exceeded with url: /onvif/media_service (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8575ea3df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

ASECAM
