### DISCUSSION TITLE
[Config Support]: Fail to get audio working

### DISCUSSION THREAD

**Discussion by mihoaut** [blakeblackshear/frigate#13896] [Config Support] [answered]
### Describe the problem you are having

Hi all,

i am sorry i tried so much to not bother here with my problem but after days of failing i ask for help. in my HA frigate addon i have neither audio in the live veiw, nor in the recordings, but i would like to have it in both. i have a couple of identical reolink e1 zoom cameras (i managed to have audio with them with the webrtc camera integration, so it must work somehow).

can you tell me what am i doing wrong, to not have audio ? the config is just a current snapshot in time, i had it changed so often already, but i do not manage to have the right combination of necessary config settings i guess.

thank you!

PS: this was the webrtc card url with wich audio is working fine: `url: >-
  ffmpeg:rtsp://admin:XXXXXX@192.168.1.130/h264Preview_01_main#video=copy#audio=opus`

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 1
  events:
    retain:
      default: 1

version: 0.14

mqtt:
  enabled: false

detectors:
  cpu:
    type: cpu

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person

audio:
  enabled: True

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5

go2rtc:
  streams:
    kids_cam:
      - rtsp://admin:adminadmin@192.168.1.130/h264Preview_01_main
      - "ffmpeg:kids_cam#video=copy#audio=opus"
    vorraum_cam:
      - rtsp://admin:adminadmin@192.168.1.131/h264Preview_01_main
      - "ffmpeg:vorraum_cam#video=copy#audio=opus"
    kueche_cam:
      - rtsp://admin:adminadmin@192.168.1.132/h264Preview_01_main
      - "ffmpeg:kueche_cam#video=copy#audio=opus"
    schlafzimmer_cam:
      - rtsp://admin:adminadmin@192.168.1.133/h264Preview_01_main
      - "ffmpeg:schlafzimmer_cam#video=copy#audio=opus"
    wohnzimmer_cam:
      - rtsp://admin:Cam4r4adm!n@192.168.1.134/h264Preview_01_main
      - "ffmpeg:wohnzimmer_cam#video=copy#audio=opus"

cameras:
  kids:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kids_cam
          roles:
            - detect
            - audio
            - record
  vorraum:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorraum_cam
          roles:
            - detect
            - audio
            - record
  kueche:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kueche_cam
          roles:
            - detect
            - audio
            - record
  schlafzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/schlafzimmer_cam
          roles:
            - detect
            - audio
            - record
  wohnzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wohnzimmer_cam
          roles:
            - detect
            - audio
            - record
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
2024-09-23 07:51:35.007689724  [INFO] Preparing new go2rtc config...
2024-09-23 07:51:35.026431029  [INFO] Got IP address from supervisor: 192.168.1.200
2024-09-23 07:51:35.045402139  [INFO] Got WebRTC port from supervisor: 8556
2024-09-23 07:51:35.326139203  [INFO] Starting go2rtc...
2024-09-23 07:51:35.401148515  09:51:35.401 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-23 07:51:35.401151932  09:51:35.401 INF config path=/dev/shm/go2rtc.yaml
2024-09-23 07:51:35.401586536  09:51:35.401 INF [api] listen addr=:1984
2024-09-23 07:51:35.401658402  09:51:35.401 INF [rtsp] listen addr=:8554
2024-09-23 07:51:35.401819137  09:51:35.401 INF [webrtc] listen addr=:8555/tcp
2024-09-23 07:51:45.005332093  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
Have a look at the documentation: https://docs.frigate.video/configuration/live/#camera-settings-recommendations

You'll want to make sure your camera is sending AAC audio for the best compatibility.

**Reply by mihoaut** [reply]
hi hawkeye, thanks for your reply. yes i looked at the docs. i think my config exactly refelcts this part of your mentioned documentation in the section audio support:
```
go2rtc:
  streams:
    rtsp_cam: # <- for RTSP streams
      - rtsp://192.168.1.5:554/live0 # <- stream which supports video & aac audio
      - "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    http_cam: # <- for http streams
      - http://192.168.50.155/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password # <- stream which supports video & aac audio
      - "ffmpeg:http_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
```
      
also in the section **Setting Stream For Live UI**  of this docu page i have the following present in my config:

```
   ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
```

am i missing something? am i not getting something ? please help me. thx !!!
