### DISCUSSION TITLE
[Support]: Misleading free space reported on Storage Stats

### DISCUSSION THREAD

**Discussion by bobemoe** [blakeblackshear/frigate#13892] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Looking at the "Storage Stats" page, I see:
![image](https://github.com/user-attachments/assets/5a163488-b6f2-44f7-83cb-dee41b445f3d)
Which, looking at recordings saying 21.9GB of 823GB leads me to believe I have 800GB free space!
However in reality I only have 149GB free space, as see from `du` inside the container:
```
root@9d46d2cf4802:/opt/frigate# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         824G  634G  149G  82% /
tmpfs            64M     0   64M   0% /dev
shm              64M  2.0M   63M   4% /dev/shm
/dev/sda2       824G  634G  149G  82% /config
tmpfs           954M   21M  934M   3% /tmp/cache
```

Is this expected? I guess its true to say 21.9GB of the 823GB disk is used for recordings. But saying that without also saying that 600GB is also used by OS/other storage seems to make it useless?

Nowhere does it say how much free space there is?

I am concerned this means free space calculation is inaccurate and will let the disk fill up without triggering the disk full cleanup process?

### Steps to reproduce

1. install frigate with docker onto a disk that is already partly full
2. view storage stats

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

FireFox 115.5.0esr (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: false

# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - dog
    - truck
    - bicycle
    - bird
    - horse
    - sheep
    - cow
    - motorcycle

cameras:
  Cam1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxxx/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://xxxx/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
#      width: 1280
#      height: 720
    zones:
      Outside:
        coordinates: 0.471,0.191,0.242,0.341,0.234,0.189,0.09,0.287,0.213,0.016,0.495,0.054
        loitering_time: 0
        inertia: 3
      Driveway:
        coordinates: 0,0.357,0.228,0.187,0.247,0.321,0.48,0.191,0.991,0.99,0,1
        loitering_time: 0
        inertia: 3
      Car_Park:
        coordinates: 0.435,0.227,0.516,0.014,0.898,0.09,1,0.225,1,0.988
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Driveway
          - Car_Park
      detections:
        required_zones: Outside
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion

    objects:
      filters:
        car:
          mask: 0,0,0.229,0.191,0.334,0.996,0,1
    motion:
      mask: 0,0.486,0.209,0.006,0.901,0.102,1,0.209,1,0,0,0
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision

### Screenshots of the Frigate UI's System metrics pages

as above
