### DISCUSSION TITLE
[Config Support]: Reolink Doorbell button not working after starting 2-way audio

### DISCUSSION THREAD

**Discussion by brdva** [blakeblackshear/frigate#13904] [Config Support]
### Describe the problem you are having

I recently got the 2-way audio feature working both via the add-on and the Frigate card, but I noticed that my Reolink Doorbell and Chime are not producing any sound after someone presses the doorbell button. Additionally, the quick reply messages and the siren are also silent after the button is pressed. I’ve been investigating to figure out what might be causing this issue.

Here’s what I’ve observed:

1. **LED Behavior via Home Assistant**:
   - I have the doorbell LED set to **Auto** mode in Home Assistant. When someone approaches the camera, the LED turns on. It turns off after they walk away.
   - However, when I click to view the live stream from the add-on, the LED turns on and stays on for a few seconds after I leave the stream. During this time, the doorbell button becomes unresponsive, but the motion detection and the visitor entity still activate. It seems that after a short delay, the system becomes "ready" for visitors again.

2. **LED and Button Behavior via Frigate Card**:
   - When using the Frigate card, the LED only turns on when I press the microphone icon.
   - Unfortunately, in this scenario, the doorbell button, chime, and other features (e.g., quick reply and siren) stop working entirely, and I can’t seem to find an easy way to exit this "active mode." 

While the system is in this state (not working), pressing the siren or quick reply buttons generates the following errors in Home Assistant:
![image](https://github.com/user-attachments/assets/57f3f441-aabb-4335-bf7e-97992902cfaa)
![image](https://github.com/user-attachments/assets/7d62a55f-50b1-4a44-8a2b-b7cb87624bf6)

Does anyone have insights or suggestions on what could be causing this issue? I’d appreciate any guidance on how to resolve it or further troubleshoot. Thanks in advance!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.xx
  port: xxx
  topic_prefix: frigate
  client_id: frigate
  user: xxxx
  password: xxxxxxxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    doorbell_sub:
      - rtsp://xxxxxx:xxxxxxx@192.168.xxx.x:554/h264Preview_01_sub
      - "ffmpeg:https://192.168.xxx.x/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxxx&password=xxxxxxx#audio=copy#video=copy#audio=opus
  webrtc:
    candidates:
      - 192.168.x.xx
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

cameras:
  doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/doorbell_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: false
    live:
      stream_name: doorbell_sub
version: 0.14
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.x.xxx:554/Preview_01_sub/",
      "remote_addr": "192.168.x.xxx:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1727052524823820 1 IN IP4 192.168.x.xxx\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=18602852, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=2240556, senders=1"
      ],
      "senders": [
        "0 PCMU/8000, bytes=58880, receivers=0"
      ],
      "recv": 21137552,
      "send": 64768
    },
    {
      "url": "ffmpeg:https://192.168.x.xxx/flv?port=1935\u0026app=bcs\u0026stream=channel0_ext.bcs\u0026user=xxxxxx\u0026password=xxxxxxxxx#audio=copy#video=copy#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:554/doorbell_sub",
      "remote_addr": "127.0.0.1:36296",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=17673548, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=2130738, receivers=1"
      ],
      "send": 20156193
    }
  ]
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Any other information that may be helpful

Frigate Lovelace card configuration:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    go2rtc:
      modes:
        - webrtc
      stream: doorbell_sub
    live_provider: go2rtc
    hide: false
    triggers:
      occupancy: false
    webrtc_card: {}
menu:
  buttons:
    microphone:
      enabled: true
      alignment: matching
      type: toggle
      priority: 80
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
      alignment: matching
    camera_ui:
      enabled: false
    substreams:
      enabled: false
    play:
      enabled: false
    clips:
      enabled: false
    screenshot:
      enabled: true
    snapshots:
      enabled: false
    image:
      enabled: false
    live:
      priority: 100
    fullscreen:
      priority: 90
  live:
    enabled: true
  clips:
    enabled: false
  snapshots:
    enabled: false
  style: outside
  position: top
  button_size: 60
live:
  controls:
    thumbnails:
      mode: none
  preload: false
  microphone:
    always_connected: false
    disconnect_seconds: 60
  lazy_load: false
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
view:
  update_force: false
image:
  mode: screensaver
media_viewer: {}
performance: {}
```

**Comment by NickM-27** [comment]
this is how the doorbell is designed to work, if two way audio is enabled then those features won't work. This is why the recommended reolink config has the http-flv stream _and then_ the rtsp stream

```
go2rtc:
  streams:
    doorbell_sub:
      - "ffmpeg:https://192.168.xxx.x/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxxx&password=xxxxxxx#audio=copy#video=copy#audio=opus
      - rtsp://xxxxxx:xxxxxxx@192.168.xxx.x:554/h264Preview_01_sub
```
