### DISCUSSION TITLE
[Support]: Double Take cannot detect faces in MQTT snapshots

### DISCUSSION THREAD

**Discussion by FabianGabor** [blakeblackshear/frigate#13927] [General Support]
### Describe the problem you are having

Frigate is working fine, publishes topics to MQTT. Double Take can also connect to MQTT and sees the published topics.

However, when I use the following Double Take config, it doesn't detect or recognize a person anymore, no new images show up in the Matches tab.
```
frigate:
  ...
  attempts:
    latest: 0
    snapshot: 0
    mqtt: true
```

If latest/snapshot is not 0, it has no issues. But I would like to feed DT only a cropped image, no need to scan an entire uncropped snapshot/latest image.

The best would be to only feed DT a cropped face since Frigate can already detect that.

Tried both frigate/events and frigate/reviews topics, makes no difference.

frigate/hatso_bejarat/person/snapshot topic's content doesn't seem to be a valid image file: [snapshot.jfif.txt](https://github.com/user-attachments/files/17112321/snapshot.jfif.txt)

[double-take.yaml.txt](https://github.com/user-attachments/files/17112149/double-take.yaml.txt)
[double-take.log](https://github.com/user-attachments/files/17111823/double-take.log)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt.primergy.lan
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 30

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://...

logger:
  default: info

ffmpeg:
#   # hwaccel_args: preset-nvidia
  hwaccel_args: preset-vaapi # Intel

detect:
  enabled: true
  width: 2688
  height: 1520
  fps: 5
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 3
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 150
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    max_frames:
      objects:
        person: 4500
        cat: 1800

objects:
  track:
    - person
    - face
    - car
    - dog
    - cat
  filters:
    person:
      min_score: 0.75
      threshold: 0.8
    car:
      min_score: 0.8
      threshold: 0.85
    cat:
      min_score: 0.6
      threshold: 0.7
    dog:
      min_score: 0.6
      threshold: 0.7
    face:
      min_score: 0.75
      threshold: 0.85

review:
  alerts:
    labels:
      - person
      - car
      - cat
      - dog

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: 30)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default:  0.8)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 10)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.010
  # Optional: Height of the resized motion frame (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 190
  improve_contrast: true
  mqtt_off_delay: 15

record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: false
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 1
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  events:
    pre_capture: 2
    post_capture: 5
    objects:
      - person
      - face
      # - license_plate
      - dog
      - cat
      - car
      # - package
    # required_zones: []
    retain:
      # Required: Default retention days (default: shown below)
      default: 3
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # objects:
      #   car: 15
      #   person: 15

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  # height: 720 #175
  required_zones: []
  retain:
    default: 10
    # objects:
    #   car: 15
    #   person: 15

go2rtc:
  streams:
    hatso_bejarat:
      - rtsp://{FRIGATE_NVR_USER}:{FRIGATE_NVR_PASSWORD}@{FRIGATE_NVR_HOST}:554/cam/realmonitor?channel=2&subtype=0

cameras:
  hatso_bejarat:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hatso_bejarat
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: hatso_bejarat
    snapshots:
      enabled: true
      required_zones:
        - hatso_kert
    record:
      enabled: true
    best_image_timeout: 30
    motion:
      mask: 0.536,0,0,0,0,0.201,0.232,0.141
      threshold: 30
      # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
      #           needs to recalibrate. (default: 0.8)
      # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
      # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
      # a doorbell camera.
      lightning_threshold: 0.8
      # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 10)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 10 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      contour_area: 10
      improve_contrast: true
    zones:
      hatso_kert:
        coordinates: 1,1,0,1,0,0,0.302,0,0.408,0.092,0.541,0.085,0.753,0.114,1,0.192
          # coordinates: 704,396,301,396,167,253,86,105,57,21,425,23,651,57,704,60
        # Optional: Number of consecutive frames required for object to be considered present in the zone (default: 3).
        inertia: 3 # / 5 fps = 1 sec
        objects:
          - person
          - face
          - dog
          - cat
          # - car
        loitering_time: 0
    mqtt:
      enabled: true
      crop: true
      # Optional: height to resize the snapshot to (default: 270)
      height: 900
      # Optional: jpeg encode quality (default: 70)
      quality: 90
      required_zones:
        - hatso_kert
    ui:
      order: 0
      dashboard: true

version: 0.14
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

I would like to feed DT only a cropped snapshot so it doesn't scan the full size camera image for faces again.

**Comment by NickM-27** [comment]
Are you sure doubletake is connecting to mqtt correctly? I'd just leave the doubletake config as default when it comes to mqtt topics

**Reply by FabianGabor** [reply]
Yes, I'm sure. MQTT status is green in the top status and does publish to it.

Just went in front of my camera named hatso_bejarat and checked MQTT afterwards.

double-take/cameras/hatso_bejarat
{"id":"1727204903.607853-94rlrw","duration":14.88,"timestamp":"2024-09-24T19:08:39.517Z","attempts":3,"camera":"hatso_bejarat","zones":[],"matches":[{"name":"gábor","confidence":99.83,"match":true,"box":{"top":325,"left":2087,"width":104,"height":145},"type":"snapshot","duration":0.85,"detector":"rekognition","filename":"7ebd7e84-25cf-4137-b45c-de47300d0ec7.jpg"}]}

**Reply by FabianGabor** [reply]
I went back to the default frigate/events topic setting before posting this, just experimented a bit with the reviews topic.

**Reply by NickM-27** [reply]
there is no way it will be able to use the reviews topic

**Reply by FabianGabor** [reply]
Yeah, I noticed that it doesn't work with it, that's why I went back to the events topic. Still doesn't explain the fact why this doesn't work and I'm not getting any images:
```
attempts:
    latest: 0
    snapshot: 0
```

What's even more strange is that DT receives the cropped snapshot as well as the uncropped full size snapshot and latest when I set this:
```
attempts:
    latest: 1
    snapshot: 5
```
![latest: 1, snapshot: 5](https://github.com/user-attachments/assets/3719b8bc-51d6-420c-81a7-9dccd37633e7)

**Reply by FabianGabor** [reply]
Maybe the question I shohuld be asking: when does the snapshot get cropped?
I suspect the cropped ones are from mqtt, the full size images through the api, right @NickM-27 ?

**Reply by NickM-27** [reply]
The API can send cropped ones too depending on your config

**Comment by FabianGabor** [comment]
Went outside again. Frigate did recognize me and posted this to MQTT:
frigate/events
`{"before": {"id": "1727206400.196353-5f4uty", "camera": "elso_bejarat", "frame_time": 1727206436.807099, "snapshot": {"frame_time": 1727206436.807099, "box": [2008, 115, 2432, 326], "area": 89464, "region": [1296, 0, 2688, 1392], "score": 0.9375, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.962890625, "false_positive": false, "start_time": 1727206400.196353, "end_time": null, "score": 0.9375, "box": [2008, 115, 2432, 326], "area": 89464, "ratio": 2.009478672985782, "region": [1296, 0, 2688, 1392], "stationary": true, "motionless_count": 183, "position_changes": 0, "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "after": {"id": "1727206400.196353-5f4uty", "camera": "elso_bejarat", "frame_time": 1727206497.375274, "snapshot": {"frame_time": 1727206436.807099, "box": [2008, 115, 2432, 326], "area": 89464, "region": [1296, 0, 2688, 1392], "score": 0.9375, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.962890625, "false_positive": false, "start_time": 1727206400.196353, "end_time": null, "score": 0.9453125, "box": [2024, 130, 2327, 318], "area": 56964, "ratio": 1.6117021276595744, "region": [1967, 16, 2383, 432], "stationary": true, "motionless_count": 485, "position_changes": 0, "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "type": "update"}`

When I have this set:
```
attempts:
    latest: 0
    snapshot: 0
```
DT doesn't receive any new images. This is for the same camera, the latest published message is the same published old one I posted earlier.
double-take/cameras/hatso_bejarat
`{"id":"1727204903.607853-94rlrw","duration":14.88,"timestamp":"2024-09-24T19:08:39.517Z","attempts":3,"camera":"hatso_bejarat","zones":[],"matches":[{"name":"gábor","confidence":99.83`

**Reply by NickM-27** [reply]
need to be sure and set mqtt: true explicitly I think

**Reply by NickM-27** [reply]
your problem is probably because of this

```
    mqtt:
      enabled: true
      crop: true
      # Optional: height to resize the snapshot to (default: 270)
      height: 900
      # Optional: jpeg encode quality (default: 70)
      quality: 90
      required_zones:
        - hatso_kert
```

you have frigate configured to only send an mqtt image when you enter the required zone

**Reply by FabianGabor** [reply]
I commented out the required_zones but did not make a difference. Snapshots had those required_zones as well but they do get generated.

Frigate:
```
mqtt:
  enabled: true
  # timestamp: true
  # bounding_box: true
  crop: true
  # Optional: height to resize the snapshot to (default: 270)
  # height: 1520
  # Optional: jpeg encode quality (default: 70)
  quality: 90
  # required_zones:
  #   - hatso_kert
```

DT:
```
frigate:
  url: http://192.168.88.12:5000
  update_sub_labels: true
  stop_on_match: false
  min_area: 0
  labels:
    - person

  attempts:
    latest: 0
    snapshot: 0
    mqtt: true
    delay: 0
```
