### DISCUSSION TITLE
[Config Support]: Raspberry Pi issue

### DISCUSSION THREAD

**Discussion by scopedial** [blakeblackshear/frigate#13920] [Config Support] [answered]
### Describe the problem you are having

I am seeing a peculiar error on both of my raspberry pis. I have configured both a 4 and a 5 and I am seeing the
same behavior on both. The initialization of Frigate seems to hang half way through and becomes unresponsive.
On both I am using the most recent version of Pi OS lite, with all updates. I have installed docker as described
at the debian web site.
When starting the container it remains in a "starting" state.
Linux is - Linux frigate 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

Errors that appear in journalctl -

_Sep 23 20:19:18 frigate systemd[1]: docker-4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422.scope: Consumed 8.678s CPU time.
Sep 23 20:19:18 frigate containerd[692]: time="2024-09-23T20:19:18.347870905-04:00" level=info msg="shim disconnected" id=4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422 namespace=moby
Sep 23 20:19:18 frigate containerd[692]: time="2024-09-23T20:19:18.348047573-04:00" level=warning msg="cleaning up after shim disconnected" id=4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422 namespace=moby
Sep 23 20:19:18 frigate containerd[692]: time="2024-09-23T20:19:18.348090906-04:00" level=info msg="cleaning up dead shim" namespace=moby
Sep 23 20:19:18 frigate dockerd[750]: time="2024-09-23T20:19:18.348472390-04:00" level=info msg="ignoring event" container=4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 23 20:19:18 frigate dockerd[750]: time="2024-09-23T20:19:18.372596244-04:00" level=warning msg="ShouldRestart failed, container will not be restarted" container=4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422 daemonShuttingDown=false error="restart canceled" execDuration=11.033242758s exitStatus="{1 2024-09-24 00:19:18.320847573 +0000 UTC}" hasBeenManuallyStopped=true restartCount=2
Sep 23 20:19:18 frigate kernel: veth1f6e4b9: renamed from eth0
Sep 23 20:19:18 frigate kernel: br-a6f493682820: port 1(veth4470474) entered disabled state
Sep 23 20:19:18 frigate NetworkManager[593]: <info>  [1727137158.6159] manager: (veth1f6e4b9): new Veth device (/org/freedesktop/NetworkManager/Devices/15)
Sep 23 20:19:18 frigate avahi-daemon[552]: Interface veth4470474.IPv6 no longer relevant for mDNS.
Sep 23 20:19:18 frigate kernel: br-a6f493682820: port 1(veth4470474) entered disabled state
Sep 23 20:19:18 frigate avahi-daemon[552]: Leaving mDNS multicast group on interface veth4470474.IPv6 with address fe80::70d9:98ff:fe6d:ad72.
Sep 23 20:19:18 frigate avahi-daemon[552]: Withdrawing address record for fe80::70d9:98ff:fe6d:ad72 on veth4470474.
Sep 23 20:19:18 frigate kernel: veth4470474 (unregistering): left allmulticast mode
Sep 23 20:19:18 frigate kernel: veth4470474 (unregistering): left promiscuous mo_

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://c5fb4700c973a5e5618e460d822e2692

ffmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration

cameras:
#  tapo1:  #Name for your comment
#    ffmpeg:
#      inputs:
#        - path: rtsp://tapocam:m1kemike@192.168.0.53:554/stream1 #The Stream you want to monitor
#          roles:
#            - record
#        - path: rtsp://tapocam:m1kemike@192.168.0.53:554/stream2 #The Stream you want to monitor
#          roles:
#            - detect
#    detect:
#      enabled: true # Detection is ?
#      width: 1920 # The Cameras resolution
#      height: 1080 # The Cameras resolution
#    motion:
#      mask:
#        - 762,0,863,0,1045,0,1920,0,1880,393,686,262,0,455,0,0

  tapo2:  #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://tapocam:m1kemike@192.168.217.179:554/stream1 #The Stream you want to monitor
          roles:
            - record
        - path: rtsp://tapocam:m1kemike@192.168.217.179:554/stream2 #The Stream you want to monitor
          roles:
            - detect
     #       - audio
    audio:
      enabled: true

    detect:
      enabled: true # Detection is ?
      width: 1920 # The Cameras resolution
      height: 1080 # The Cameras resolution

    #record: 

    motion:
      mask:
        - 0.797,0,0.801,0.103,0.553,0.183,0.548,0
        - 0.472,0,0,0,0,0.391,0.474,0.209
      threshold: 35
      contour_area: 25
      improve_contrast: true
      
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60

  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 14
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 25

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - dog
    - rabbit
    - bird
    - animal
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  mask: 0,0,1000,0,1000,200,0,200

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 7
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

go2rtc:
  publish:
    tapo1:
      - rtmp://a.rtmp.youtube.com/live2/mss2-2a4k-urtd-yf02-5g5f

  streams:
    tapo1: rtsp://tapocam:foxtrot3cho@192.168.232.180:554/stream1

  log:
    publish: debug
    streams: error
    rtsp: error
    stream: error

database:
  path: /db/frigate.db

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.app: error
    go2rtc: error

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
version: 0.14
camera_groups:
  Primary:
    order: 1
    icon: LuBoxes
    cameras:
      - tapo1
      - MiniCam1
```

### Relevant Frigate log output

```shell
none available
```

### Relevant go2rtc log output

```shell
none available
```

### Frigate stats

```json
none available
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### docker compose
_#version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:0.13.2-standard-arm64
      #image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10 #Map the Pi hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/dad/frigate-nvr/:/config/
      #- /mnt/backups/frigate:/media/frigate
      - /home/dad/frigate-nvr/media:/media/frigate
      - /home/dad/frigate-nvr/storage:/db
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
        #- "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
        #- "8555:8555/udp" # WebRTC over udp
        #environment:
      # FRIGATE_RTSP_PASSWORD: "Alpha3cho"
    environment:_

adding some more logs from journalctl. They look related. I started the container and then stopped it.

_Sep 24 18:38:45 frigate dockerd[750]: time="2024-09-24T18:38:45.293106155-04:00" level=warning msg="path in container /dev/bus/usb already exists in privileged mode" container=4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422 spanID=15a67cec206067ea traceID=c5ac77249b057ac03ea3632d398564f7
Sep 24 18:38:45 frigate dockerd[750]: time="2024-09-24T18:38:45.293220409-04:00" level=warning msg="path in container /dev/video10 already exists in privileged mode" container=4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422 spanID=15a67cec206067ea traceID=c5ac77249b057ac03ea3632d398564f7
Sep 24 18:38:45 frigate containerd[694]: time="2024-09-24T18:38:45.338497124-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Sep 24 18:38:45 frigate containerd[694]: time="2024-09-24T18:38:45.338674172-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Sep 24 18:38:45 frigate containerd[694]: time="2024-09-24T18:38:45.338712651-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Sep 24 18:38:45 frigate containerd[694]: time="2024-09-24T18:38:45.339574426-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.pause\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Sep 24 18:38:45 frigate systemd[1]: run-docker-runtime\x2drunc-moby-4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422-runc.utmMcM.mount: Deactivated successfully.
Sep 24 18:38:45 frigate systemd[1]: Started docker-4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422.scope - libcontainer container 4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422.
Sep 24 18:38:45 frigate kernel: eth0: renamed from veth9b5e4cb
Sep 24 18:38:45 frigate NetworkManager[606]: <info>  [1727217525.5879] device (vethd36012f): carrier: link connected
Sep 24 18:38:45 frigate NetworkManager[606]: <info>  [1727217525.5883] device (br-a6f493682820): carrier: link connected
Sep 24 18:38:45 frigate containerd[694]: time="2024-09-24T18:38:45.623224256-04:00" level=warning msg="error from *cgroupsv2.Manager.EventChan" error="failed to add inotify watch for \"/sys/fs/cgroup/system.slice/docker-4ad6ec9c5c810665699d52850b0a1b568e54490f31676b0ec0c7399cf5bb6422.scope/memory.events\": no such file or directory"
Sep 24 18:38:47 frigate avahi-daemon[554]: Joining mDNS multicast group on interface vethd36012f.IPv6 with address fe80::6499:5fff:fe48:f86a.
Sep 24 18:38:47 frigate avahi-daemon[554]: New relevant interface vethd36012f.IPv6 for mDNS._
