### DISCUSSION TITLE
[Development]: dev build 0.15 saving config changes

### DISCUSSION THREAD

**Discussion by JoshuaSeidel** [blakeblackshear/frigate#13931] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

changing motion masks, errors and wont save to config file.

### Steps to reproduce

1. modify a motion mask
2. get error
3. restart it doesnt apply
...

### Version

0.15.0-dc54981

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: frigate_mqtt
  password: **********
  host: 192.168.7.83

ffmpeg:
  hwaccel_args: preset-nvidia-h264
 # input_args: preset-rtsp-stream
  #output_args:
   # record: preset-record-generic-audio-copy


cameras:
  steps_cam: # <------ Name the camera
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://wb:cCa3gT-do14ncGTn5mZXJIDLz3depg5EmV9DM4NH@wyze-bridge:8554/steps-cam # <----- The stream you want to use for detection
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
    review:
      detections:
        labels:
          - dog
          - person
        required_zones: steps
    zones:
      steps:
        coordinates: 0.412,0.006,0.222,1,0.824,1,0.578,0.009
        loitering_time: 0
    motion:
      mask: 0.723,0.938,0.974,0.933,0.976,0.98,0.723,0.979

  doorbell:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: doorbell
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
      filters:
        car:
          mask:
            - 0.631,0.673,0.679,0.535,0.844,0.531,0.825,0.677
            - 0.491,0.518,0.552,0.513,0.562,0.593,0.499,0.597
    review:
      detections:
        labels:
          - dog
          - person
      alerts:
        required_zones:
          - Porch
          - sidewalk
    zones:
      Porch:
        coordinates: 
          0.381,0.999,0.384,0.961,0.47,0.969,0.473,0.908,0.723,0.866,0.73,0.874,0.875,0.801,0.999,0.881,0.999,0.999
        loitering_time: 0
        objects:
          - package
          - person
          - dog
          - cat
        inertia: 2
      sidewalk:
        coordinates: 
          0.57,0.897,0.584,0.791,0.624,0.758,0.67,0.74,0.706,0.724,0.698,0.78,0.696,0.82,0.694,0.866
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 2
    motion:
      mask: 0.491,0.5,0.488,0.602,0.626,0.597,0.629,0.469
  driveway:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
      filters:
        car: {}
    review:
      detections:
        labels:
          - dog
          - person
          - car
          - motorcycle
      alerts:
        required_zones: parking
    onvif:
      host: 192.168.9.4
      port: 8000
      user: nvr
      password: **********
    #  autotracking:
    #    enabled: false
    #    calibrate_on_startup: false
    #    zooming: absolute
    #    zoom_factor: 0.3
    #    track:
    #      - person
    #      - car
    #    return_preset: home
    #    timeout: 10
    #    required_zones:
    #      - complete
        #required_zones: complete
      #alerts:
        #required_zones: leanna-parking
     # alerts:
      #  required_zones: parking
    zones:
      parking:
        coordinates: 
          0.013,0.527,0.032,0.385,0.169,0.295,0.63,0.265,0.689,0.356,0.59,0.987,0.013,0.987
        inertia: 2
        loitering_time: 0
    motion:
      threshold: 31
      contour_area: 15
      improve_contrast: 'true'
      mask:
        - 0.583,0.933,0.988,0.931,0.989,0.971,0.585,0.974
        - 0.629,0.199,0.698,0.358,1,0.473,1,0,0.702,0
        - 0.718,0.359,0.785,0.018,0.053,0.031,0,0.07,0,0.402,0.088,0.336,0.152,0.298,0.377,0.279,0.473,0.272
  backyard:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - cat
        - face
        - package
        - car
    detect:
      width: 1536
      height: 576
      fps: 5
    review:
      detections:
        labels:
          - dog
          - person
          - face
      alerts:
        required_zones:
          - back-grass
          - back-steps
          - back-side
          - patio
          - garden
    motion:
      mask:
        - 0.753,0.919,0.981,0.915,0.98,0.958,0.752,0.956
        - 0.235,0.17,0.241,0.305,0.344,0.248,0.331,0.106
        - 0.392,0.099,0.389,0.184,0.552,0.156,0.847,0.305,0.796,0.113
    zones:
      patio:
        coordinates: 0.213,0.989,0.314,0.655,0.62,0.459,0.802,1
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - package
        inertia: 1
      back-driveway:
        coordinates: 0.916,0.674,0.911,0.773,0.642,0.234,0.68,0.177
        loitering_time: 0
        objects:
          - car
          - person
        inertia: 3
      kens-yard:
        coordinates: 
          0.203,0.546,0.296,0.376,0.342,0.283,0.231,0.316,0.096,0.505,0.004,0.604,0.017,0.705,0.148,0.532
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
      back-steps:
        coordinates: 0.088,0.998,0.136,0.917,0.24,0.684,0.298,0.686,0.207,0.996
        loitering_time: 0
        objects:
          - person
          - face
          - dog
          - cat
      back-side:
        coordinates: 0.03,0.827,0.154,0.582,0.258,0.58,0.061,0.936
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - face
          - dog
          - cat
      back-grass:
        coordinates: 
          0.208,0.553,0.348,0.284,0.354,0.173,0.41,0.148,0.457,0.182,0.526,0.15,0.646,0.231,0.787,0.53,0.85,0.693,0.817,0.742,0.913,0.794,0.917,0.896,0.901,0.995,0.767,0.996,0.794,0.942,0.694,0.637,0.62,0.447,0.307,0.65,0.228,0.645
        inertia: 3
        loitering_time: 0
        objects:
          - face
          - dog
          - cat
          - person
      garden:
        coordinates: 0.064,0.942,0.224,0.645,0.274,0.661,0.254,0.758,0.225,0.737,0.088,1
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
version: 0.15-0

go2rtc:
  streams:
    steps_Cam:
      - rtsp://192.168.9.144:37039/b042a8dc7e3d6779?rtsp_transport=udp
      - rtsp://wb:**********@wyze-bridge:8554/steps-cam
    doorbell:
      - rtsp://nvr:**********@192.168.9.127:554/Preview_01_main #backchannel=0
    doorbell_sub:
      - rtsp://nvr:**********@192.168.9.127:554/Preview_01_sub
    driveway:
      - rtsp://nvr:**********@192.168.9.4:554/Preview_01_main
    driveway_sub:
      - rtsp://nvr:**********@192.168.9.4:554/Preview_01_sub
    backyard:
      - rtsp://admin:**********@192.168.9.171:554/Preview_01_main
    backyard_sub:
      - rtsp://admin:**********@192.168.9.171:554/Preview_01_sub
  webrtc:
    candidates:
      - 192.168.9.144:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

detectors:
  coral:
    type: edgetpu
    device: pci

#detectors:
 # tensorrt:
  #  type: tensorrt
   # device: 0

model:
  path: plus://**********

#model:
 # path: /config/model_cache/tensorrt/yolov7-320.trt
 # input_tensor: nchw
 # input_pixel_format: rgb
 # width: 320
 # height: 320

genai:
  enabled: true
  provider: openai
  model: gpt-4o
  api_key: **********
  prompt: Describe the {label} in these images from the {camera} security camera.
  object_prompts:
    person: Describe the main person in these images (gender, age, clothing, activity,
      etc). Do not include where the activity is occurring (sidewalk, concrete, driveway,
      etc).
    car: Label the primary vehicle in these images with just the name of the company
      if it is a delivery vehicle, or the color make and model.
    dog: Describe the main dog in these images (breed, color, size, activity). Do
      not include where the activity is occuring (yard. patio, street, etc).

semantic_search:
  enabled: true
  reindex: false

review:
  alerts:
    labels:
      - person
      - face
      - dog
      - car
      - ups
      - fedex
      - amazon
      - package
  detections:
    labels:
      - person
      - dog
      - car
      - ups
      - face
      - fedex
      - amazon
      - package

record:
  enabled: true
  retain:
    days: 14
    mode: motion

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 800
  height: 480
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  mode: continuous #motion #objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

tls:
  enabled: true

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

# Include all cameras by default in Birdseye view
notifications:
  enabled: 'true'
  email: **********
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dc54981-amd64
    pull_policy: always
    shm_size: "8GB" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/nvidia0:/dev/dri/nvidia0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .config:/config
      - /mnt/data/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "443:8971"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "*************"
      PLUS_API_KEY: "***************"
      TRT_MODEL_PREP_DEVICE: '0'
    networks:
       - secure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
networks:
  secure:
    external: true
```

### Relevant Frigate log output

```shell
unknown
2024-09-24 08:43:58
unknown
motion.mask.list[str].468
unknown
2024-09-24 08:43:58
unknown
Input should be a valid string [type=string_type, input_value=array([255, 255, 255, 255... 255, 255], dtype=uint8), input_type=ndarray]
unknown
2024-09-24 08:43:58
unknown
For further information visit https://errors.pydantic.dev/2.8/v/string_type
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolinks

### Screenshots of the Frigate UI's System metrics pages

n/a?
