### DISCUSSION TITLE
How to limit the detection fps

### DISCUSSION THREAD

**Discussion by t0ny-peng** [blakeblackshear/frigate#1394] [Ask A Question]
The camera I have provides a raw 20fps rtsp stream, but it's limited at 5fps in the frigate YAMl configuration.
```yaml
  balcony:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.220/ch0_0.h264
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
```
When movement is detected in the camera, the detection speed could sometimes reach 18~20fps, which is unnecessary for just person detection. Before diving into the code(which I will this weekend), is there any easy way to limit the detect fps?

Thanks in advance.
