### DISCUSSION TITLE
Zones not being honored

### DISCUSSION THREAD

**Discussion by JoshuaSeidel** [blakeblackshear/frigate#13979] [General Support]
How do I troubleshoot a zone alert not being honored. It's very clear that the cars passing infront of my house are not going into the zone I specified. Yet it is triggering an event. Is it not the object but the bounding box around the object? How would one debug an event? I know you can do live debugging but that only helps when objects are actively moving

Example: ![image](https://github.com/user-attachments/assets/f0b61e4a-ae4f-4e13-93dc-a46529f752c1)

Thanks!

**Comment by NickM-27** [comment]
It is the bounding box, that is all Frigate has to go off of. Without your config there is not much help we can really offer, it is possible you have not configured your zone correctly to be required. 

Debugging is mostly live in 0.14, tools for debugging these types of things have already been added for the next version (0.15)

**Comment by JoshuaSeidel** [comment]
@NickM-27 here is my config

```yaml
mqtt:
  enabled: true
  user: frigate_mqtt
  password: *******
  host: 192.168.7.83

ffmpeg:
  hwaccel_args: preset-nvidia-h264
 # input_args: preset-rtsp-stream
  #output_args:
   # record: preset-record-generic-audio-copy


cameras:
  steps_cam: # <------ Name the camera
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://wb:cCa3gT-*******@wyze-bridge:8554/steps-cam # <----- The stream you want to use for detection
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
    review:
      detections:
        labels:
          - dog
          - person
        required_zones: steps
    zones:
      steps:
        coordinates: 0.454,0,0.215,0.968,0.866,0.994,0.62,0.003
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.723,0.938,0.974,0.933,0.976,0.98,0.723,0.979

  doorbell:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: doorbell
    objects:
      track:
        - dog
        - person
        - cat
        - fedex
        - ups
        - amazon
        - face
        - package
      filters:
        car:
          mask:
            - 0.631,0.673,0.679,0.535,0.844,0.531,0.825,0.677
            - 0.491,0.518,0.552,0.513,0.562,0.593,0.499,0.597
    review:
      detections:
        labels:
          - dog
          - person
        required_zones:
          - sidewalk
          - Porch
      alerts:
        required_zones:
          - Porch
          - sidewalk
    zones:
      Porch:
        coordinates: 
          0.381,0.999,0.384,0.961,0.47,0.969,0.473,0.908,0.723,0.866,0.73,0.874,0.875,0.801,0.999,0.881,0.999,0.999
        loitering_time: 0
        objects:
          - package
          - person
          - dog
          - cat
        inertia: 2
      sidewalk:
        coordinates: 
          0.57,0.897,0.584,0.791,0.624,0.758,0.67,0.74,0.706,0.724,0.698,0.78,0.696,0.82,0.694,0.866
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 2
    motion: {}
  driveway:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
      filters:
        car: {}
    review:
      detections:
        labels:
          - dog
          - person
          - car
          - motorcycle
        required_zones:
          - front-grass
          - parking
      alerts:
        required_zones:
          - parking
          - front-grass
    onvif:
      host: 192.168.9.4
      port: 8000
      user: nvr
      password: *******
    #  autotracking:
    #    enabled: false
    #    calibrate_on_startup: false
    #    zooming: absolute
    #    zoom_factor: 0.3
    #    track:
    #      - person
    #      - car
    #    return_preset: home
    #    timeout: 10
    #    required_zones:
    #      - complete
        #required_zones: complete
      #alerts:
        #required_zones: leanna-parking
     # alerts:
      #  required_zones: parking
    zones:
      parking:
        coordinates: 
          0.013,0.527,0.04,0.412,0.216,0.322,0.635,0.358,0.689,0.356,0.59,0.987,0.013,0.987
        inertia: 2
        loitering_time: 0
        objects:
          - motorcycle
          - car
          - person
      front-grass:
        coordinates: 0.682,0.354,0.995,0.451,1,1,0.568,0.993
        loitering_time: 0
        objects:
          - dog
          - cat
          - person
    motion:
      threshold: 31
      contour_area: 15
      improve_contrast: 'true'
      mask: 0.583,0.933,0.988,0.931,0.989,0.971,0.585,0.974
  backyard:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - cat
        - face
        - package
    detect:
      width: 1536
      height: 576
      fps: 5
    review:
      alerts:
        required_zones:
          - yard
          - patio
          - back-steps
      detections:
        required_zones:
          - back-steps
          - yard
          - patio
    motion: {}
    zones:
      patio:
        coordinates: 0.18,0.997,0.295,0.53,0.556,0.576,0.632,0.567,0.748,0.998
        loitering_time: 0
        objects:
          - dog
          - package
          - person
          - cat
      yard:
        coordinates: 
          0.754,0.995,0.868,1,0.814,0.86,0.696,0.548,0.627,0.415,0.596,0.332,0.555,0.291,0.514,0.191,0.448,0.174,0.412,0.156,0.406,0.03,0.347,0.039,0.341,0.164,0.182,0.43,0,0.73,0.058,0.946,0.233,0.5,0.478,0.555,0.631,0.56
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 3
      back-steps:
        coordinates: 0.041,0.99,0.234,0.505,0.291,0.529,0.178,0.997
        loitering_time: 0
        objects:
          - person
          - dog
version: 0.14

go2rtc:
  streams:
    steps_Cam:
      - rtsp://wb:cCa3gT-*******@wyze-bridge:8554/steps-cam
    doorbell:
      - rtsp://nvr:*******@192.168.9.127:554/Preview_01_main
    doorbell_sub:
      - rtsp://nvr:*******@192.168.9.127:554/Preview_01_sub
    driveway:
      - rtsp://nvr:*******@192.168.9.4:554/Preview_01_main
    driveway_sub:
      - rtsp://nvr:*******@192.168.9.4:554/Preview_01_sub
    backyard:
      - rtsp://admin:*******@192.168.9.171:554/Preview_01_main
    backyard_sub:
      - rtsp://admin:/***********@192.168.9.171:554/Preview_01_sub
  webrtc:
    candidates:
      - 192.168.9.144:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

detectors:
  coral:
    type: edgetpu
    device: pci

#detectors:
 # tensorrt:
  #  type: tensorrt
   # device: 0

model:
  path: plus://***********

#model:
 # path: /config/model_cache/tensorrt/yolov7-320.trt
 # input_tensor: nchw
 # input_pixel_format: rgb
 # width: 320
 # height: 320

review:
  alerts:
    labels:
      - person
      - face
      - dog
      - car
      - ups
      - fedex
      - amazon
      - package
  detections:
    labels:
      - person
      - dog
      - car
      - ups
      - face
      - fedex
      - amazon
      - package

record:
  enabled: true
  retain:
    days: 14
    mode: motion

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 800
  height: 480
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  mode: continuous #motion #objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

tls:
  enabled: true

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

# Include all cameras by default in Birdseye view

```
