### DISCUSSION TITLE
Frigate + Telegram duplicated notifications

### DISCUSSION THREAD

**Discussion by krustophenia** [blakeblackshear/frigate#13975] [Ask A Question]
Hi. 

I'm using this automation to send all frigate detections to telegram and it's working but sends the notifications duplicated (sometimes even more) and I'm not sure what I'm doing wrong.

```
alias: test1
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: cam1
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
    id: cam1
    enabled: true
  - platform: mqtt
    topic: frigate/events
    payload: cam2
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
    id: cam2
  - platform: mqtt
    topic: frigate/events
    payload: cam3
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
    id: cam3
  - platform: mqtt
    topic: frigate/events
    payload: cam4
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
    id: cam4
  - platform: mqtt
    topic: frigate/events
    payload: cam5
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
    id: cam5
condition:
  - condition: template
    value_template: "{{ type != 'end' }}"
    enabled: true
action:
  - repeat:
      sequence:
        - wait_for_trigger:
            - platform: mqtt
              topic: frigate/events
              payload: "{{id}}"
              value_template: "{{ value_json['after']['id'] }}"
          timeout:
            minutes: 2
          continue_on_timeout: true
          enabled: true
        - condition: template
          value_template: "{{ wait.trigger.payload_json['type'] == 'end' }}"
          enabled: true
        - data:
            caption: That's what frigate detected
            authentication: digest
            file: ../media/frigate/clips/{{camera}}-{{id}}.jpg
          enabled: true
          action: telegram_bot.send_photo
        - delay:
            hours: 0
            minutes: 0
            seconds: 15
            milliseconds: 0
          enabled: true
        - data:
            caption: Video of the event
            authentication: digest
            url: http://REDACTED/api/events/{{id}}/clip.mp4
          enabled: true
          action: telegram_bot.send_video
      until:
        - condition: template
          value_template: "{{ wait.trigger.payload_json['type'] == 'end' }}"
mode: parallel
max: 10
```
