### DISCUSSION TITLE
[Detector Support]: Error: Disjointed yx or hw! in AMDMIGraphX

### DISCUSSION THREAD

**Discussion by artur-braga** [blakeblackshear/frigate#13982] [Detector Support]
### Describe the problem you are having

Hello,
I am trying to use the rocm version of frigate but sadly I am getting the following error:
Invalid MLIR created: Error: Disjointed yx or hw!
This error occurs when using rocm 6.1.2. A PR for it can be found:
https://github.com/blakeblackshear/frigate/pull/13981

@NickM-27 I took the dev version as I saw that you merged your PR already.

### Version

dev

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  wall_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.terrace_wall_light_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
# detectors:
#   rocm:
#     type: rocm
#     model:
#       path: /config/yolo_nas_s.onnx
detectors:
  onnx:
    type: rocm

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3"
services:
  devcontainer:
    image: docker.io/library/frigate:latest-rocm-gfx1100
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    environment:
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
    devices:
      - /dev/dri # for intel hwaccel, needs to be updated for your hardware
      - /dev/kfd
    volumes:
      - .:/workspace/frigate:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /usr/share/hassio/media/frigate:/media/frigate
      - ./debug:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
```

### Relevant Frigate log output

```shell
what():  Thread 0x/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/AMDMIGraphX/src/targets/gpu/mlir.cpp:723: run_high_level_pipeline: Invalid MLIR created: Error: Disjointed yx or hw!
devcontainer-1  | 2024-09-26 14:22:14.399522309  Note: see current operation: %5 = "rock.conv2d"(%3, %2, %4) <{arch = "gfx1100", dilations = [1 : i32, 1 : i32], features = #rock<GemmFeatures dot|atomic_add|atomic_fmax_f32>, numCU = 6 : i32, padding = [0 : i32, 0 : i32, 0 : i32, 0 : i32], strides = [1 : i32, 1 : i32]}> {filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "wi", "gi", "ci", "hi"], output_layout = ["no", "wo", "go", "ko", "ho"]} : (tensor<1x1x17x1x1xf32>, tensor<1x4x1x17x100xf32>, tensor<1x4x1x1x100xf32>) -> tensor<1x4x1x1x100xf32>
```

### Relevant go2rtc log output

```shell
nothing relevant
```

### Operating system

HassOS

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

nothing relevant
