### DISCUSSION TITLE
[Bug]: Frigate UI config editor reports no access to file, then deletes entire config

### DISCUSSION THREAD

**Discussion by nwish** [blakeblackshear/frigate#13984] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

![image](https://github.com/user-attachments/assets/f846a687-8472-4b50-9f70-2590e409e291)

When using the UI's config editor, I am encountering this error upon clicking "Save Only".  Then after that, the config.yml file becomes empty.  Within a few minutes, the Frigate UI no longer loads a config file in the editor (just the spinning circle).  Upon restart, Frigate then reports all kinds of errors about not finding proper config.

Luckily I make regular backups of the config, so no harm done on my end.

### Steps to reproduce

1. Navigate to Settings -> Configuration Editor
2. Make changes, or don't
3. Click "Save Only"
5. Find your config.yml file and note that it is now empty

### Version

0.15.0-35a4460

### In which browser(s) are you experiencing the issue with?

Latest Chrome

### Frigate config file

```yaml
Omitting for the sake of getting this reported
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:35a4460
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    shm_size: "1gb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0
      #- /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config/:/config/
      - /mnt/wd3tb/frigate/storage:/media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - LIBVA_DRIVER_NAME=i965
      - PLUS_API_KEY=
    ports:
      - 8971:8971
      - 5000:5000
      - 8554:8554
      - 1935:1935 # RTMP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
Nothing unusual appears in the logs
```

### Relevant go2rtc log output

```shell
Same ^^
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Various

### Screenshots of the Frigate UI's System metrics pages

N/A
