### DISCUSSION TITLE
MQTT notifications that lead to missing thumbnails and clips

### DISCUSSION THREAD

**Discussion by rccoleman** [blakeblackshear/frigate#13989] [Ask A Question] [answered]
I've been trying to track down a recurring issue with notifications from Frigate to the Frigate integration via MQTT to a mobile notification.  Most of the time, after updating to Frigate 0.14, I get a notification via MQTT that results in a thumbnail that just shows "Can't load attachment" with a status code of 404 (not found).  When I try to open the notification, I get the following message: `{"message":"Event not found","success":false}`.  I'm trying to figure out whether there's something wrong in Frigate, in the HA integration, or in the paths that I'm constructing for the notification thumbnail and clip.  Sometimes the thumbnail and clip for an event are displayed correctly and sometimes they result in the errors above, and I haven't been able to track down a pattern.

I've started logging the thumbnail and clip path that I construct when I receive a notification in the `frigate/reviews` MQTT topic, and here's an example from this morning.  The paths are based on [the docs](https://docs.frigate.video/integrations/home-assistant#notification-api), and were working fine in Frigate 0.13:
```
2024-09-26 06:50:43.370 INFO (MainThread) [homeassistant.components.system_log.external] Review: /api/frigate/notifications/1727358643.126067-8t8d67/thumbnail.jpg /api/frigate/notifications/1727358643.126067-8t8d67/family_room/clip.mp4
```
When I search for that event ID in the directory where all my Frigate artifacts are stored, I see exactly one match with the same time:
```
rcoleman@rcoleman-linux /nfs/NVR % find . -name "*1727358643.126067*" -ls       
  9492650      4 -rwxrwxrwx   1 1024     users        3546 Sep 26 06:50 ./clips/review/thumb-family_room-1727358643.126067-8t8d67.webp
```

That appears to just be a thumbnail and I don't see a clip anywhere with that timestamp.

If I try to manually load either the clip or thumbnail using the API paths that I constructed above, I can repro the "not found" error:
`https://my_ha_url/api/frigate/notifications/1727358643.126067-8t8d67/thumbnail.jpg` & `https://my_ha_url/api/frigate/notifications/1727358643.126067-8t8d67/clip.mp4` both return `{"message":"Event not found","success":false}`

This same issue repeated a few minutes later:

`2024-09-26 07:00:17.018 INFO (MainThread) [homeassistant.components.system_log.external] Review: /api/frigate/notifications/1727359216.770585-865f3f/thumbnail.jpg /api/frigate/notifications/1727359216.770585-865f3f/family_room/clip.mp4`

```
rcoleman@rcoleman-linux /nfs/NVR % find . -name "*1727359216.770585*" -ls
  9492996      4 -rwxrwxrwx   1 1024     users        2204 Sep 26 07:00 ./clips/review/thumb-family_room-1727359216.770585-865f3f.webp
```

With the same errors occuring during the notification and when I manually try to pull the thumbnail or clip manually via the browser.

It seems like there's some name mangling going on to transform the filename into how to refer to it via the integration API, but I can't figure out what's going wrong here.  Is an artifact missing?  Or I am constructing the wrong path?

The camera is working fine in Frigate - I can view snapshots and live video.  Camera config is here:

```
  family_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://rcoleman-linux:8554/family_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://rcoleman-linux:8554/family_room_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: family_room
    onvif:
      host: 192.168.1.140
      port: 80
      user: username
      password: password
    objects:
      track:
        - person
        - cat
    motion:
      mask: 0.642,0.041,0.966,0.04,0.966,0.078,0.641,0.075
    detect:
      enabled: true
    snapshots:
      enabled: true
```

Detect,  motion, recording, and snapshots were all enabled via HA when both of these events occurred.
