### DISCUSSION TITLE
[Config Support]: 0 Detections in Frigate 0.14

### DISCUSSION THREAD

**Discussion by berndthiel** [blakeblackshear/frigate#13987] [Config Support]
### Describe the problem you are having

in my HA my Frigate doesnt detect objects correctly and also make no snapshots by detection.

![image](https://github.com/user-attachments/assets/236837fb-b5d2-4c97-a3cd-1722f4a3a12b)

![image](https://github.com/user-attachments/assets/68401aa5-17ab-4e22-ae48-98591fc5ed8a)

### Version

newest

### Frigate config file

```yaml
# MQTT settings
mqtt:
  host: 192.168.100.51
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: mqtt-password
  stats_interval: 60

# ui
detectors:
  cpu1:
    type: cpu
    num_threads: 1

# Live view settings
live:
  height: 720
  quality: 7

# Birdseye
birdseye:
  enabled: false
  mode: continuous

objects:
  track:
    - person
    - car
    - cat
    - dog
    - horse
    - bicycle
  filters:
    person:
      threshold: 0.72

# Record, Detect, Snapshots
record:
  enabled: false
  retain:
    days: 14
    mode: motion

detect:
  width: 600
  height: 300
  fps: 5

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: true
  retain:
    default: 30

### go2rtc ###
go2rtc:
  streams:
    parking:
      - rtsp://xxx@192.168.100.11/cam1/mpeg4
      #- "ffmpeg:parking#audio=aac"
    carport:
      - rtsp://xxx@192.168.100.14:554/h264Preview_01_main
      #- "ffmpeg:https://192.168.100.14/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=thielcamPL112B#video=copy#audio=copy#audio=opus"
      #- "ffmpeg:carport#audio=aac"
    housedoor:
      - rtsp://xxx@192.168.100.12:554/live/main
      #- "ffmpeg:housedoor#audio=aac"
    garden:
      - rtsp://xxx@192.168.100.15:554/h264Preview_01_main
      #- "ffmpeg:garden#audio=aac"

##############################################################

cameras:
# parking
  parking:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/parking
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    motion:
      mask:
        - 0.001,0.35,1,0.364,1,0,0.002,0.004
        - 0.287,0.35,0.232,0.516,0.227,0.686,0.152,0.99,-0.001,0.997,0,0.343
        - 0.239,0.481,0.227,0.686,0.502,0.64,0.531,0.99,0.698,0.997,0.582,0.474
        - 0.65,0.364,0.88,0.997,1,1,1,0.357
      threshold: 45
      contour_area: 25
      improve_contrast: 'true'
    zones:
      parking001:
        coordinates: 0.561,0.375,0.697,0.99,0.875,0.993,0.651,0.361
        loitering_time: 0
        objects:
          - person
          - horse
          - dog
        inertia: 2
      parking001_car:
        coordinates: 0.281,0.368,0.557,0.375,0.582,0.47,0.235,0.481
        loitering_time: 0
        objects:
          - car
          - person
      parking002_car:
        coordinates: 0.227,0.689,0.165,0.99,0.531,0.993,0.511,0.643
        loitering_time: 0
        objects: car
  housedoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/housedoor
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect

    motion:
      mask:
        - 0.169,0,0.172,0.124,0.416,0.558,0.105,0.983,-0.001,0.997,-0.001,0.004
        - 0.511,0,0.478,0.604,0.736,0.859,0.677,0.993,0.997,0.986,0.999,-0.003
      threshold: 41
      contour_area: 10
      improve_contrast: 'true'
    zones:
      housedoor_001:
        coordinates: 0.47,0.65,0.505,0,0.165,0,0.17,0.145
        inertia: 3
        loitering_time: 0
      housedoor_002:
        coordinates: 0.14,1,0.681,1,0.887,0.439,0.737,0.361,0.423,0.57

# carport
        inertia: 3
        loitering_time: 0
        objects: person
    objects:
      filters:
        car:
          mask: 0.174,0.164,0.006,0.492,0.11,0.998,0.484,0.522
  carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect

    motion:
      threshold: 30
      contour_area: 14
      improve_contrast: 'true'
      mask:
        - 0,0.571,0.165,0.368,0.386,0.354,0.503,0.334,0.707,0.338,0.744,-0.003,0.001,0.007,0,0.351
        - 0.873,0.502,0.842,0.604,0.885,0.71,1,1,1,0
        - 0.863,0.388,0.882,0.502,0.999,-0.003,0.742,0,0.704,0.342
    zones:
      carport001:
        coordinates: 0.723,0.329,0.184,0.335,0,0.574,0,1,1,1
        loitering_time: 0
        objects: car
        inertia: 3
      carport002:
        coordinates: 0.863,0.392,0.882,0.516,0.857,0.594,0.803,0.382
        loitering_time: 0
        objects: car
    objects:
      filters:
        car: {}
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect

    motion:
      mask:
        - 0,0.908,0.502,0,0,0
        - 0.191,0.566,0.419,0.569,0.455,0.498,0.564,0.502,0.695,0,0.504,0
        - 0.691,0,0.564,0.502,0.568,0.587,1,0.717,0.997,0.011
        - 0.041,0.834,0.07,1,0,1,0,0.894
        - 0.062,1,0.114,0.905,0.896,0.926,0.905,1
        - 0.225,0.65,0.119,0.898,0.893,0.922,0.896,0.848,0.932,0.806,0.483,0.636,0.421,0.615
      threshold: 40
      contour_area: 39
      improve_contrast: 'true'
    zones:
      garden_001:
        coordinates: 0.993,0.712,0.993,0.812,0.456,0.617,0.576,0.592
        inertia: 3
        loitering_time: 0
      garden_002:
        coordinates: 336,152,338,174,264,179,264,155
      garden_003:
        coordinates: 0.064,1,0.044,0.864,0.196,0.574,0.253,0.584
        inertia: 3
        loitering_time: 0
      garden_004:
        coordinates: 600,300,534,300,542,255,600,209
      garden003:
        coordinates: 0.26,0.58,0.225,0.654,0.437,0.608,0.426,0.562
        loitering_time: 0
        objects: person
    objects:
      mask:
        - 0.009,0.813,0.207,0.513,0.37,0.212,0.006,0.191
        - 0.576,0.551,0.988,0.689,0.995,0.339,0.389,0.18,0.213,0.544,0.425,0.548,0.472,0.491,0.555,0.495
version: 0.14
```

### Relevant Frigate log output

```shell
2024-09-26 15:25:56.554319241  [INFO] Preparing Frigate...
2024-09-26 15:25:56.653116775  [INFO] Starting Frigate...
2024-09-26 15:26:00.334860302  [2024-09-26 17:26:00] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-26 15:26:00.335640376  [2024-09-26 17:26:00] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-09-26 15:26:00.341764293  [2024-09-26 17:26:00] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-26 15:26:00.394511422  [2024-09-26 17:26:00] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-26 15:26:00.443791508  [2024-09-26 17:26:00] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2024-09-26 15:26:00.491792799  [2024-09-26 17:26:00] peewee_migrate.logs            INFO    : Starting migrations
2024-09-26 15:26:00.492731448  [2024-09-26 17:26:00] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-26 15:26:00.518984632  [2024-09-26 17:26:00] frigate.app                    INFO    : Recording process started: 280
2024-09-26 15:26:00.519588435  [2024-09-26 17:26:00] frigate.app                    INFO    : Recording process started: 281
2024-09-26 15:26:00.524382765  [2024-09-26 17:26:00] frigate.app                    INFO    : go2rtc process pid: 98
2024-09-26 15:26:00.576192244  [2024-09-26 17:26:00] detector.cpu1                  INFO    : Starting detection process: 309
2024-09-26 15:26:00.576196544  [2024-09-26 17:26:00] frigate.app                    INFO    : Output process started: 311
2024-09-26 15:26:00.644693543  [2024-09-26 17:26:00] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-09-26 15:26:00.928628144  [2024-09-26 17:26:00] frigate.app                    INFO    : Camera processor started for parking: 347
2024-09-26 15:26:00.943958382  [2024-09-26 17:26:00] frigate.app                    INFO    : Camera processor started for housedoor: 348
2024-09-26 15:26:00.945300167  [2024-09-26 17:26:00] frigate.app                    INFO    : Camera processor started for carport: 361
2024-09-26 15:26:00.962396321  [2024-09-26 17:26:00] frigate.app                    INFO    : Camera processor started for garden: 364
2024-09-26 15:26:00.962399821  [2024-09-26 17:26:00] frigate.app                    INFO    : Capture process started for parking: 372
2024-09-26 15:26:00.975349641  [2024-09-26 17:26:00] frigate.app                    INFO    : Capture process started for housedoor: 381
2024-09-26 15:26:00.989612650  [2024-09-26 17:26:00] frigate.app                    INFO    : Capture process started for carport: 385
2024-09-26 15:26:00.989883407  [2024-09-26 17:26:00] frigate.app                    INFO    : Capture process started for garden: 388
2024-09-26 16:39:03.211297253  [2024-09-26 18:39:03] frigate.comms.dispatcher       INFO    : Setting motion threshold for carport: 30
2024-09-26 16:39:03.216983139  [2024-09-26 18:39:03] frigate.comms.dispatcher       INFO    : Setting motion contour area for carport: 14
2024-09-26 16:39:13.975760108  [2024-09-26 18:39:13] frigate.comms.dispatcher       INFO    : Setting motion threshold for carport: 30
2024-09-26 16:39:13.975765208  [2024-09-26 18:39:13] frigate.comms.dispatcher       INFO    : Setting motion contour area for carport: 14
```

### Relevant go2rtc log output

```shell
2024-09-26 15:25:56.559294142  [INFO] Preparing new go2rtc config...
2024-09-26 15:25:56.612192347  [INFO] Got IP address from supervisor: 192.168.100.51
2024-09-26 15:25:56.676404935  [INFO] Got WebRTC port from supervisor: 18555
2024-09-26 15:25:57.779259122  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2024-09-26 15:25:57.779985805  [INFO] Starting go2rtc...
2024-09-26 15:25:57.925829683  17:25:57.925 INF go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4
2024-09-26 15:25:57.929429105  17:25:57.928 INF config path=/dev/shm/go2rtc.yaml
2024-09-26 15:25:57.929433005  17:25:57.928 INF [rtsp] listen addr=:8554
2024-09-26 15:25:57.929437504  17:25:57.928 INF [webrtc] listen addr=:8555/tcp
2024-09-26 15:25:57.929439904  17:25:57.929 INF [api] listen addr=:1984
2024-09-26 15:26:06.598805219  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

**Comment by NickM-27** [comment]
There are a number of problems in this config:

1. CPU detectors are being used. This is not recommended, if you have an intel CPU you should be using openvino
2. You do not have recording enabled. As it says in the docs and the 0.14 release notes, recording is required for review items to show. 
3. you have overmasked, you should not be putting masks in the non-zoned areas as that makes Frigate's job harder not easier

**Reply by berndthiel** [reply]
1. also when i only have an CPU but not external GPU?

2024-09-26 17:02:21.753583410  [2024-09-26 19:02:21] frigate.detectors.plugins.openvino WARNING : OpenVINO AUTO device type is not currently supported. Attempting to use GPU instead.

2. when i activate recording is than only snapshorts acrtive or also video recording? i only need snapshots which was what i see in dashboard activated

3. you mean the "red" i should remove?

**Reply by NickM-27** [reply]
1. yes, integrated GPU works just fine. The log you are showing does not mean there is an issue
2. Video recordings are required to be enabled for the new UI
3. yes, or make them smaller to be specific areas where objects will not be

**Reply by berndthiel** [reply]
1. ok, but it shows 

024-09-26 17:19:06.566537397  Process detector:ov:
2024-09-26 17:19:06.569235463  Traceback (most recent call last):
2024-09-26 17:19:06.569503420    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-09-26 17:19:06.569506219      self.run()
2024-09-26 17:19:06.569507819    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-09-26 17:19:06.569509219      self._target(*self._args, **self._kwargs)
2024-09-26 17:19:06.569514318    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-09-26 17:19:06.569535315      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-09-26 17:19:06.569537014    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-09-26 17:19:06.569538914      self.detect_api = create_detector(detector_config)
2024-09-26 17:19:06.569540314    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-09-26 17:19:06.569541614      return api(detector_config)
2024-09-26 17:19:06.569543113    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 43, in __init__
2024-09-26 17:19:06.569564810      self.interpreter = self.ov_core.compile_model(
2024-09-26 17:19:06.569566610    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 521, in compile_model
2024-09-26 17:19:06.569580207      super().compile_model(model, device_name, {} if config is None else config),
2024-09-26 17:19:06.569581707  RuntimeError: Exception from src/inference/src/cpp/core.cpp:123:
2024-09-26 17:19:06.569583107  Exception from src/inference/src/dev/plugin.cpp:59:
2024-09-26 17:19:06.569584607  Check 'contexts.count(device_id)' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:204:
2024-09-26 17:19:06.569585907  [GPU] Context was not initialized for 0 device
2024-09-26 17:19:06.569587006  
2024-09-26 17:19:06.569588006  

and after frigate stops.

**Reply by berndthiel** [reply]
3. i thought masks are their, to mark areas which should not be in detection to reduce cpu/gpu ressources blocking?

**Reply by NickM-27** [reply]
what CPU do you have?

**Reply by NickM-27** [reply]
> i thought masks are their, to mark areas which should not be in detection to reduce cpu/gpu ressources blocking?

no, masks are to block areas where objects will not be and ignore the motion there (like a camera timestamp or the sky). If you mask as much as you did it confuses and works against frigate

**Reply by berndthiel** [reply]
Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
in a Hyper-V VM

**Reply by berndthiel** [reply]
![image](https://github.com/user-attachments/assets/926c7a93-af7d-434c-a663-fd168e6fe50f)
here you see my 4 cameras and my idea with "mask" was to "mask" all areas where i dont wanna detect/react to reduce usage of CPU

**Reply by NickM-27** [reply]
Gotcha, in that case you should change the device from `AUTO` to `CPU`, it will still perform bette

**Reply by NickM-27** [reply]
> here you see my 4 cameras and my idea with "mask" was to "mask" all areas where i dont wanna detect/react to reduce usage of CPU

yes, and as I said that is incorrect and not how masks should be used. Frigate is designed for you to use zones to tell it the areas you do care about. And from the images in the OP it appears you already have zones setup so you should just remove the masks and make sure the zones are set as required

**Reply by berndthiel** [reply]
when i change type to CPU i got following warnings and errors

2024-09-26 17:27:18.629277385  [2024-09-26 19:27:18] detector.ov                    INFO    : Starting detection process: 310
2024-09-26 17:27:18.634186193  Process detector:ov:
2024-09-26 17:27:18.634500242  Traceback (most recent call last):
2024-09-26 17:27:18.634523039    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-09-26 17:27:18.634524538      self.run()
2024-09-26 17:27:18.634525938    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-09-26 17:27:18.634527338      self._target(*self._args, **self._kwargs)
2024-09-26 17:27:18.634538136    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-09-26 17:27:18.634539636      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-09-26 17:27:18.634541036    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-09-26 17:27:18.634542335      self.detect_api = create_detector(detector_config)
2024-09-26 17:27:18.634543935    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-09-26 17:27:18.634561432      return api(detector_config)
2024-09-26 17:27:18.634562932    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 39, in __init__
2024-09-26 17:27:18.634564832      if not os.path.isfile(detector_config.model.path):
2024-09-26 17:27:18.634571931    File "/usr/lib/python3.9/genericpath.py", line 30, in isfile
2024-09-26 17:27:18.634573130      st = os.stat(path)
2024-09-26 17:27:18.634574530  TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Reply by berndthiel** [reply]
so when i set ov with CPU AUTO or GPU i got "no frames have been received, check error logs"

2024-09-26 17:32:10.786202822  [2024-09-26 19:32:10] frigate.app                    INFO    : Capture process started for garden: 391
2024-09-26 17:32:12.369655560  172.30.32.2 - - [26/Sep/2024:19:32:12 +0200] "GET /api/parking/latest.webp?cache=1727371931498 HTTP/1.1" 200 13176 "https://berniabc.duckdns.org:8123/api/hassio_ingress/-H9sFopUFwWPQ-yuspgNWMrCg-0JljO1b_4UPSefL3Q/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "83.230.42.100, 172.30.32.1"
2024-09-26 17:32:12.475523500  172.30.32.2 - - [26/Sep/2024:19:32:12 +0200] "GET /api/profile HTTP/1.1" 200 18 "https://berniabc.duckdns.org:8123/api/hassio_ingress/-H9sFopUFwWPQ-yuspgNWMrCg-0JljO1b_4UPSefL3Q/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "83.230.42.100, 172.30.32.1"
2024-09-26 17:32:15.546690508  172.30.32.2 - - [26/Sep/2024:19:32:15 +0200] "GET /api/carport/latest.webp?cache=1727371934606 HTTP/1.1" 200 13176 "https://berniabc.duckdns.org:8123/api/hassio_ingress/-H9sFopUFwWPQ-yuspgNWMrCg-0JljO1b_4UPSefL3Q/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "83.230.42.100, 172.30.32.1"
2024-09-26 17:32:16.857360806  [INFO] Starting go2rtc healthcheck service...
2024-09-26 17:32:17.447635289  172.30.32.2 - - [26/Sep/2024:19:32:17 +0200] "GET /api/config HTTP/1.1" 200 25911 "https://berniabc.duckdns.org:8123/api/hassio_ingress/-H9sFopUFwWPQ-yuspgNWMrCg-0JljO1b_4UPSefL3Q/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "83.230.42.100, 172.30.32.1"
2024-09-26 17:32:18.577488525  172.30.32.2 - - [26/Sep/2024:19:32:18 +0200] "GET /ws HTTP/1.1" 101 51 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "83.230.42.100, 172.30.32.1"
s6-rc: info: service legacy-services: stopping

**Reply by NickM-27** [reply]
your config is incorrect then. This should be your config

```
detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```
