### DISCUSSION TITLE
[Detector Support]: Coral Inference Time about 0.1 seconds

### DISCUSSION THREAD

**Discussion by ryosoftware** [blakeblackshear/frigate#13999] [Detector Support]
### Describe the problem you are having

I have 4 cameras (TP-Link Tapo) connected to my Frigate, running in a docker, in a i4590. Also I have a Coral connected to the hardware and configured into the Frigate settings, but I do not know why, the inference speed of the Coral is too high: about 0.1 seconds if I'm not wrong. 
Is there a reason to this? Is there anything any setting change I can do to solve it? 
I have another install with a similar hardware and I do not have this issue.
Thanks

![image](https://github.com/user-attachments/assets/bda9439f-e556-4acb-9bb3-a566a05becb1)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: localhost
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects

motion:
  improve_contrast: true

detect:
  enabled: false
  width: 1920
  height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

objects:
  track:
    - person
    - dog
    - cat
  filters:
    person:
      min_score: .8
      threshold: .85

go2rtc:
  streams:
    entrada:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.41.231/stream1
    comedor:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.41.232/stream1
    cocina:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.41.233/stream1
    dormitorio_principal:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.41.234/stream1
cameras:
  entrada:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrada
          roles:
            - record
            - detect

  comedor:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/comedor
          roles:
            - record
            - detect

  cocina:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cocina
          roles:
            - record
            - detect

  dormitorio_principal:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dormitorio_principal
          roles:
            - record
            - detect

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    privileged: true
    shm_size: "192mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../dockers-data/frigate:/config
      - ../dockers-data-extra/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554"
    labels:
      traefik.enable: "true"
      traefik.http.routers.frigate.rule: "Host(`XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`)"
      traefik.http.routers.frigate.entrypoints: "https"
      traefik.http.routers.frigate.tls: "true"
      traefik.http.services.frigate.loadbalancer.server.port: "5000"
      traefik.http.services.frigate.loadbalancer.server.scheme: "http"
    environment:
      LIBVA_DRIVER_NAME: "i965"
      FRIGATE_MQTT_USER: "mosquitto"
      FRIGATE_MQTT_PASSWORD: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      FRIGATE_RTSP_USER: "frigate"
      FRIGATE_RTSP_PASSWORD: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      PLUS_API_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginxpm_network
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d3da635d-20f8-45b2-ad3d-023049bd5ee2)
