### DISCUSSION TITLE
Record only in zone, other detection only snapshot:

### DISCUSSION THREAD

**Discussion by MichalDoom** [blakeblackshear/frigate#14001] [Config Support]
### Describe the problem you are having

Hello

i migrated from older version to last one and now its not working my old settigs.
The goal is to start record only detected person in zone and make only picture snapshot for other object detection out of the zone.
can somebody help me how to do these settings or what to change in my config?
This is my old settings but events and requiered zones settings is not supported:

 thank You very much for help

### Version

0.14.1

### Frigate config file

```yaml
cameras:
  cam_vchod:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_vchod
          roles:
            - detect
            - rtmp
            - record
          input_args: preset-rtsp-restream
    detect:
      width: 1280
      height: 800
      fps: 5
    zones:
      vchod-branka:
        inertia: 35
        objects:
            - person
        coordinates: 295,96,310,348,580,331,625,100
        mask:
          - 300,319,589,303,613,93,266,96
    record:
      enabled: true
      retain:
          days: 0
          mode: motion
      events:
        required_zones:
          - vchod-branka
        retain:
          default: 10
          mode: active_objects
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 10
    motion:
      mask:
         - 1280,0,1280,177,961,136,523,106,0,135,0,0
         - 0,800,1280,800,1280,217,928,168,595,167,551,340,370,342,325,166,0,177
```

### Relevant Frigate log output

```shell
--
```

### Relevant go2rtc log output

```shell
--
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral
