### DISCUSSION TITLE
[Camera Support]: Reolink E1 Outdoor send 30 FPS with http/flv. Config is 15 FPS. RTSP works with 15

### DISCUSSION THREAD

**Discussion by SnipeyBB** [blakeblackshear/frigate#14004] [Camera Support]
### Describe the problem you are having

Hi,

sorry for my bad english. 

My Reolink E1 Outdoor send 30 FPS with go2rtc, if i connect with http. RTSP is 15 FPS. Configured in CAM Web GUI is 15 FPS.
Sub Channel is 7 FPS configured. RTSP works with 7, http get 30 FPS. 
So my Record Storage incraes fast.

As Workaround I have set in go2rtc the record stream to RTSP Stream, but this ist with bad quality and sound.
If Iuse in go2rtc the RTSP Stream all works fine with 15 FPS.

Is the the Oportunity to use http with only 15 FPR with Reolink E1?

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

All Browsers

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.211
  user: X
  password: X

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    Garten_Sub:
      - rtsp://adminX:X@192.168.1.43:554/stream2
      - ffmpeg:Garten_Sub#audio=aac
    Garten:
      - rtsp://adminX:X@192.168.1.43:554/stream1
      - ffmpeg:Garten#audio=aac
    Gartenkueche_Sub:
      - rtsp://adminX:X@192.168.1.42:554/stream2
      - ffmpeg:Gartenkueche_Sub#audio=aac
    Gartenkueche:
      - rtsp://adminX:X@192.168.1.42:554/stream1
      - ffmpeg:Gartenkueche#audio=aac
    Vorgarten_Sub:
      - ffmpeg:http://192.168.1.41/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=adminX&password=X#video=copy#audio=copy#audio=opus
    Vorgarten:
      - rtsp://adminX:X@192.168.1.41:554/Preview_01_main

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 2
        cat: 7
        person: 14

version: 0.14

cameras:
  Vorgarten: # <------ Name the camera
    enabled: true
    onvif:
      host: 192.168.1.41
      port: 8000
      user: X
      password: X
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Vorgarten # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Vorgarten_Sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 5
    zones:
      VorZone:
        coordinates: 
          0.85,0.992,0.995,0.387,0.997,0.246,0.902,0.25,0.764,0.2,0.726,0.241,0.543,0.244,0.473,0.305,0.417,0.333,0,0.507,0.015,0.983,0.146,0.991
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 3
    live:
      stream_name: Vorgarten
    review:
      alerts:
        required_zones: VorZone
    motion:
      mask: 0.15,0.949,0.251,0.95,0.254,0.983,0.149,0.986
  Gartenkueche: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Gartenkueche # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Gartenkueche_Sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Gartenzone:
        coordinates: 
          0.004,0.373,0.163,0.292,0.424,0.309,0.438,0.284,0.66,0.301,0.666,0.155,0.753,0.205,0.772,0.309,0.953,0.308,0.953,1,0.004,0.987,0,0.596
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    live:
      stream_name: Gartenkueche
    review:
      alerts:
        required_zones: Gartenzone
    motion:
      mask:
        - 0.204,0.002,0.362,0.003,0.362,0.056,0.203,0.056
        - 0.958,0.315,1,0.315,0.997,0.973,0.957,0.519
    objects:
      filters:
        person:
          mask: 
            0.385,0.373,0.362,0.387,0.35,0.409,0.351,0.52,0.386,0.538,0.425,0.517,0.421,0.417,0.408,0.39
  Garten: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten_Sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Garten


    zones:
      Wiese:
        coordinates: 
          0.702,0.993,0.829,1,0.875,0.857,0.833,0.811,0.936,0.529,0.925,0.471,0.941,0.287,0.629,0.101,0.577,0.068,0.118,0.168,0.145,0.707,0.174,0.744,0.223,0.99
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    motion:
      mask:
        - 0.185,0.002,0.326,0.002,0.327,0.042,0.186,0.044
        - 0.085,0.223,0.071,0.389,0.097,0.542,0.124,0.518,0.12,0.238
    review:
      alerts:
        required_zones: Wiese
    objects:
      filters:
        person:
          mask: 0.244,0.195,0.281,0.187,0.285,0.221,0.234,0.235
```

### Relevant Frigate log output

```shell
There is nothing in Logs.

2024-09-27 11:57:42.002650099  [INFO] Preparing Frigate...
2024-09-27 11:57:42.019442615  [INFO] Starting Frigate...
2024-09-27 11:57:43.960840110  [2024-09-27 11:57:43] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-27 11:57:43.961021715  [2024-09-27 11:57:43] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-27 11:57:44.004338607  [2024-09-27 11:57:44] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-27 11:57:58.709899570  [2024-09-27 11:57:58] peewee_migrate.logs            INFO    : Starting migrations
2024-09-27 11:57:58.711363306  [2024-09-27 11:57:58] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-27 11:57:59.090741423  [2024-09-27 11:57:59] frigate.app                    INFO    : Recording process started: 392
2024-09-27 11:57:59.098834472  [2024-09-27 11:57:59] frigate.app                    INFO    : Recording process started: 400
2024-09-27 11:57:59.104993377  [2024-09-27 11:57:59] frigate.app                    INFO    : go2rtc process pid: 98
2024-09-27 11:57:59.250796616  [2024-09-27 11:57:59] detector.coral                 INFO    : Starting detection process: 421
2024-09-27 11:57:59.259911823  [2024-09-27 11:57:59] frigate.app                    INFO    : Output process started: 427
2024-09-27 11:57:59.304056906  [2024-09-27 11:57:59] frigate.app                    INFO    : Camera processor started for Vorgarten: 441
2024-09-27 11:57:59.304064774  [2024-09-27 11:57:59] frigate.app                    INFO    : Camera processor started for Gartenkueche: 444
2024-09-27 11:57:59.331081108  [2024-09-27 11:57:59] frigate.app                    INFO    : Camera processor started for Garten: 448
2024-09-27 11:57:59.331087982  [2024-09-27 11:57:59] frigate.app                    INFO    : Capture process started for Vorgarten: 460
2024-09-27 11:57:59.349308411  [2024-09-27 11:57:59] frigate.app                    INFO    : Capture process started for Gartenkueche: 468
2024-09-27 11:57:59.370234515  [2024-09-27 11:57:59] frigate.app                    INFO    : Capture process started for Garten: 472
2024-09-27 11:58:02.393148013  [2024-09-27 11:57:59] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-09-27 11:58:02.399439018  [2024-09-27 11:58:02] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
There is nothing in Logs.

2024-09-27 11:57:42.005010723  [INFO] Preparing new go2rtc config...
2024-09-27 11:57:42.505116248  [INFO] Starting go2rtc...
2024-09-27 11:57:42.700668217  11:57:42.700 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-27 11:57:42.700704192  11:57:42.700 INF config path=/dev/shm/go2rtc.yaml
2024-09-27 11:57:42.701586757  11:57:42.701 INF [api] listen addr=:1984
2024-09-27 11:57:42.701592427  11:57:42.701 INF [rtsp] listen addr=:8554
2024-09-27 11:57:42.701986988  11:57:42.701 INF [webrtc] listen addr=:8555/tcp
2024-09-27 11:57:51.999963553  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Camera Direkt:
ffprobe.exe "http://192.168.1.41/flv?port=1935&app
=bcs&stream=channel0_main.bcs&user=admin&password=Nti87258"
ffprobe version 7.0.2-essentials_build-www.gyan.dev Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, flv, from 'http://192.168.1.41/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Nti87258':
  Metadata:
    displayWidth    : 2048
    displayHeight   : 1536
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2048x1536, 14 fps, 15 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

Camera After go2rtc:
ffprobe.exe rtsp://192.168.1.12:8554/Vorgarten
ffprobe version 7.0.2-essentials_build-www.gyan.dev Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[rtsp @ 00000284ef82e600] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://192.168.1.12:8554/Vorgarten':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2048x1536, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink E1 Outdoor

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-09-27 120408](https://github.com/user-attachments/assets/4ae32a75-c8d2-4c7a-a259-bfc546c63148)
![grafik](https://github.com/user-attachments/assets/db8e8f4e-bbe3-4108-8986-91eb7dd11894)
