### DISCUSSION TITLE
Playback failed for records or alerts older than two hours

### DISCUSSION THREAD

**Discussion by juanraRios** [blakeblackshear/frigate#14005] [General Support] [answered]
### Describe the problem you are having

I have video files that play perfectly fine when I do a export but I try playback straight alert or move with timeline to the past the server response is 503.

I have notice that records or alerts that are recently for example less than one hour are working properly.

<img width="2038" alt="image" src="https://github.com/user-attachments/assets/9239a920-5158-4e59-bf0d-e9aadab5e5f3">

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 130.0.1 (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000

go2rtc:
  streams:
    front:
      - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0&unicast=true
      - ffmpeg:front#audio=opus
    front_sub:
      - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=1&unicast=true

cameras:
  frontCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion

    detect:
      width: 480
      height: 360
      fps: 5

    zones:
      zoneA:
        coordinates: 0,0.526,0.949,0.527,0.988,0.647,0.451,0.772,0,0.635
        loitering_time: 0
        objects: person
        inertia: 3
      zoneB:
        coordinates: 
          0,0.667,0.572,0.818,0.703,0.735,0.818,0.756,0.99,0.663,0.961,0.929,0.952,0.97,0.193,1,0.015,0.986
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - zoneA
          - zoneB
version: 0.14
```

### Relevant Frigate log output

```shell
nothing, only info logs
```

### Relevant go2rtc log output

```shell
nothing, only info logs
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Dahua
