### DISCUSSION TITLE
[Development]: Log warning about small SHM recomends smaller size

### DISCUSSION THREAD

**Discussion by TomW1605** [blakeblackshear/frigate#14006] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

basically in the title, the log warning about the SHM size being too small recomends a *smaller* size setting
![image](https://github.com/user-attachments/assets/ce46c6a0-be8a-4da1-b32b-65d83ba8acfb)

### Steps to reproduce

1. set the SHM size too small
2. look at logs

### Version

0.15.0-ddfdb71

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: 192.168.xxx.xxx
  user: frigate
  password: xxx

objects:
  track:
    - person
    - dog
    - bicycle
    - car
    - bird
    - cat
    - motorcycle
  # filters:
  #   bird:
  #     min_area: 350

review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - car
      - person
      - cat

timestamp_style:
  format: '%Y-%m-%d %H:%M:%S'
  thickness: 1

birdseye:
  enabled: true
  mode: continuous

record:
  enabled: true
  retain:
    days: 2
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  alerts:
    retain:
      days: 21
  detections:
    retain:
      days: 21
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true

go2rtc:
  streams:
    sv07_nozzle_cam_inverted: ffmpeg:rtsp://192.168.xxx.xxx:8554/stream.h264#video=h264#rotate=180

cameras:
  side_gate:
    enabled: true
    ui:
      order: 1
    birdseye:
      order: 1
    webui_url: http://192.168.xxx.xxx/
    ffmpeg:
      inputs:
        - path: 
            'rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - record
            - detect
        # - path: 
        #     rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=1
        #   roles:
        #     - detect
    motion:
      mask:
        - 998,720,1280,720,1280,720,1280,684,999,683
    zones:
      Gate:
        coordinates: 0.724,1,0.738,0.664,0.359,0.542,0.096,1
        inertia: 3
      Nextdoor_Driveway:
        coordinates: 
          0.36,0.274,0.529,0.108,0.38,0.093,0.248,0.161,0.122,0.22,0.045,0.234,0.13,0.537,0.187,0.497
        inertia: 3
      Nextdoor_Side_Path:
        coordinates: 
          0.302,0.34,0.466,0.171,0.547,0.207,0.475,0.315,0.3,0.628,0.209,0.804,0.168,0.767,0.119,0.671,0.019,0.617,0.191,0.503
        inertia: 3

      Front_Garden:
        coordinates: 0.969,0.232,0.796,0.183,0.799,0.392,0.934,0.421
        inertia: 3
      Front_Wall:
        coordinates: 0.699,0.134,0.699,0.175,0.647,0.178,0.65,0.122
        inertia: 3
        loitering_time: 0
      Side_Path:
        coordinates: 0.494,0.629,0.692,0.671,0.691,0.165,0.645,0.164,0.63,0.265,0.607,0.265
        inertia: 3
    review:
      alerts:
        required_zones:
          - Gate
          - Front_Garden
          - Front_Wall
          - Side_Path
    objects:
      filters:
        car:
          mask:
            - 0.135,0.068,0.2,0.05,0.201,0.094,0.135,0.112
            - 0.227,0.014,0.3,0.013,0.298,0.075,0.226,0.075
  front_door:
    ui:
      order: 2
    birdseye:
      order: 2
    webui_url: http://192.168.xxx.xxx/
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            'rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - record
            - detect
        # - path: 
        #     rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=1
        #   roles:
        #     - detect
        # - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0
        #   roles:
        #     - record
    motion:
      mask:
        - 998,720,1280,720,1280,720,1280,684,999,683
        - 967,0,970,67,831,155,626,84,626,0
    zones:
      Door:
        coordinates: 0.252,1,0.542,1,0.306,0.626,0.178,0.807
        inertia: 3
      Steps:
        coordinates: 0.652,0.194,0.883,0.389,0.937,0.09,0.827,0
        inertia: 3
      Front_Garden:
        coordinates: 0.289,0,0.472,0.065,0.643,0.161,0.809,0
        inertia: 3
      Side_Path:
        coordinates: 0.133,0.16,0.225,0.076,0.216,0,0.109,0
        inertia: 3
      Front_Verandah:
        coordinates: 0.133,0.163,0.301,0.023,0.877,0.395,0.719,0.995,0.549,1,0.306,0.618,0.258,0.697
    objects:
      track:
        - person
        - dog
        - bicycle
        - bird
        - cat

    review:
      alerts:
        required_zones:
          - Door
          - Side_Path
          - Steps
      detections:
        required_zones: Front_Verandah
  # driveway:
  #   ui:
  #     order: 3
  #   birdseye:
  #     order: 3
  #   webui_url: http://192.168.xxx.xxx/
  #   enabled: true
  #   ffmpeg:
  #     inputs:
  #       - path: 
  #           'rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0'
  #         roles:
  #           - record
  #           - detect
  #       # - path: 
  #       #     rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=1
  #       #   roles:
  #       #     - detect
  #   motion:
  #     mask:
  #       - 998,720,1280,720,1280,720,1280,684,999,683

  # sv07_bed_cam:
  #   enabled: true
  #   ui:
  #     order: 4
  #   birdseye:
  #     enabled: false
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://192.168.xxx.xxx:8555/stream.h264
  #         roles:
  #           - record
  #   detect:
  #     enabled: false
  #   record:
  #     enabled: true
  #     retain:
  #       days: 2
  #       mode: all
  #   snapshots:
  #     enabled: false

  # sv07_nozzle_cam:
  #   enabled: true
  #   ui:
  #     order: 5
  #   birdseye:
  #     enabled: false
  #   ffmpeg:
  #     inputs:
  #       # - path: rtsp://192.168.xxx.xxx:8554/stream.h264
  #       # - path: http://192.168.xxx.xxx:1984/api/stream.mjpeg?src=nozzle_cam
  #       - path: rtsp://127.0.0.1:8554/sv07_nozzle_cam_inverted
  #       # - path: rtsp://192.168.xxx.xxx:8554/stream.h264
  #       # - path: rtsp://127.0.0.1:8554/sv07_nozzle_cam
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #   detect:
  #     enabled: false
  #   record:
  #     enabled: true
  #     retain:
  #       days: 2
  #       mode: all
  #   snapshots:
  #     enabled: false
  #   motion:
  #     mask:
  #       - 0,1088,0,0,182,0,191,241,271,378,344,411,569,410,581,479,659,562,1015,587,1025,713,1249,841,1920,874,1920,1088

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.15-0
camera_groups:
  Security_Cams:
    order: 1
    icon: LuWebcam
    cameras:
      - driveway
      - front_door
      - side_gate
  Printer_Cams:
    order: 2
    icon: LuPrinter
    cameras:
      - sv07_bed_cam
      - sv07_nozzle_cam
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:ddfdb71
    privileged: true # this may not be necessary for all setups
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - 1984:1984 #go2rtc web ui
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/configs/frigate:/config
      - /frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
      PLUS_API_KEY: "xxx"
    shm_size: "110mb" # update for your cameras based on calculation above
    restart: unless-stopped
```

### Relevant Frigate log output

```shell
2024-09-27 19:14:53.853553610  [INFO] Preparing Frigate...
2024-09-27 19:14:53.901758136  [INFO] Starting Frigate...
2024-09-27 19:15:01.178616178  [2024-09-27 19:15:01] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-27 19:15:01.221693763  [2024-09-27 19:15:01] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-27 19:15:01.444521457  [2024-09-27 19:15:01] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-09-27 19:15:04.853923379  [2024-09-27 19:15:04] frigate.app                    INFO    : Starting Frigate (0.15.0-ddfdb71)
2024-09-27 19:15:04.897118551  [2024-09-27 19:15:04] peewee_migrate.logs            INFO    : Starting migrations
2024-09-27 19:15:04.897431199  [2024-09-27 19:15:04] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-27 19:15:05.213708045  [2024-09-27 19:15:05] frigate.app                    INFO    : Recording process started: 424
2024-09-27 19:15:05.214560579  [2024-09-27 19:15:05] frigate.app                    INFO    : Review process started: 433
2024-09-27 19:15:05.217945158  [2024-09-27 19:15:05] frigate.app                    INFO    : go2rtc process pid: 114
2024-09-27 19:15:05.251037217  [2024-09-27 19:15:05] frigate.app                    INFO    : Output process started: 457
2024-09-27 19:15:05.455793021  [2024-09-27 19:15:05] frigate.app                    INFO    : Camera processor started for side_gate: 495
2024-09-27 19:15:05.464053809  [2024-09-27 19:15:05] frigate.app                    INFO    : Camera processor started for front_door: 496
2024-09-27 19:15:05.464617720  [2024-09-27 19:15:05] frigate.app                    WARNING : The current SHM size of 110.0MB is too small, recommend increasing it to at least 62MB.
2024-09-27 19:15:05.472860486  [2024-09-27 19:15:05] frigate.app                    INFO    : Capture process started for side_gate: 498
2024-09-27 19:15:05.473349451  [2024-09-27 19:15:05] frigate.app                    WARNING : The current SHM size of 110.0MB is too small, recommend increasing it to at least 62MB.
2024-09-27 19:15:05.483362234  [2024-09-27 19:15:05] frigate.app                    INFO    : Capture process started for front_door: 506
2024-09-27 19:15:05.780582800  [2024-09-27 19:15:05] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2024-09-27 19:15:07.890121227  [2024-09-27 19:15:05] detector.coral                 INFO    : Starting detection process: 455
2024-09-27 19:15:07.890297749  [2024-09-27 19:15:05] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-09-27 19:15:07.895823008  [2024-09-27 19:15:07] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua DH-IPC-HDW2531EMP-AS-S2-AUS-BLK

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/4c0ae6d1-973c-44d9-b6e9-58904e88d232)
![image](https://github.com/user-attachments/assets/3a878d6b-6431-45a1-8cdd-cba57695013b)
![image](https://github.com/user-attachments/assets/e2ff5350-bdb7-43af-a218-71c97a73de4d)
