### DISCUSSION TITLE
[Support]: Space Issue in /dev/shm

### DISCUSSION THREAD

**Discussion by ancoraunaltro** [blakeblackshear/frigate#14014] [General Support]
### Describe the problem you are having

After 2 days of the container running without issues, Frigate stop responding and I find a lot of rows with this couple of error in container log:
`s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
s6-log: warning: unable to write to /dev/shm/logs/frigate/current: No space left on device`
Upon checking, I found that /dev/shm has 0 bytes free

### Version

0.14.1-a7f1f8d

### What browser(s) are you using?

Edge 129.0.2792.52 (arm64)

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.97.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <password>

detectors:
  coral:
    type: edgetpu
    device: usb

#birdseye:
#  enabled: true
#  mode: continuous
#  mode: motion
#  width: 1920
#  height: 1080

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  enabled: true
  fps: 5
  width: 1280
  height: 720
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - cat
    - dog
#    - car

record:
  enabled: true
  retain:
    days: 8
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10
      mode: active_objects
#      mode: motion

snapshots:
  enabled: true
#  timestamp: true
  retain:
    default: 8

#timestamp_style:
#  position: tl
#  format: '%d/%m/%Y %H:%M:%S'
#  color:
#    red: 255
#    green: 255
#    blue: 255
#  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  #effect: None

cameras:
  Garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.199:554/stream2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.199:554/stream1
          roles:
            - record
  Portico_NE:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.200:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.200:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  Portico_SO:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.201:554/live.sdp
          roles:
            - detect
            - record
  Cuccia_S:
    enabled: true  
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.202:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.202:554/h264Preview_01_main
          roles:
            - record
  Cuccia_N:
    enabled: true  
    ffmpeg:
      inputs:
        - path: rtsp://admin:<password>@192.168.97.204:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<password>@192.168.97.204:554/h264Preview_01_main
          roles:
            - record
  Giardino_NO:
    enabled: true  
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.205:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.205:554/h264Preview_01_main
          roles:
            - record
  Giardino_NE:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.206:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.206:554/h264Preview_01_main
          roles:
            - record
  Ingresso_Garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.207:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.207:554/h264Preview_01_main
          roles:
            - record
  Portico_NO:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.208:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.208:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  Ingresso_Posteriore:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.209:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.209:554/h264Preview_01_main
          roles:
            - record
  Appartamento_NE:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.210:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.210:554/h264Preview_01_main
          roles:
            - record
  Appartamento_SE:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.211:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.211:554/h264Preview_01_main
          roles:
            - record
  Portico_SE:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.97.212:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user>:<password>@192.168.97.212:554/h264Preview_01_main
          roles:
            - record

version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
s6-log: warning: unable to write to /dev/shm/logs/frigate/current: No space left on device
s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
s6-log: warning: unable to write to /dev/shm/logs/frigate/current: No space left on device
s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
s6-log: warning: unable to write to /dev/shm/logs/frigate/current: No space left on device
```

### Relevant go2rtc log output

```shell
I haven't accesso to log, Frigate is unresponsive.
```

### FFprobe output from your camera

```shell
bash: ffprobe: command not found
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Tapo C100, Vivotek IB8367, Dahua HDBW1235EP HFW2431SP, REOLINK RLC510A

**Comment by NickM-27** [comment]
need to see your docker compose file

**Reply by ancoraunaltro** [reply]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:a7f1f8d
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ancoraunaltro/docker/frigate/config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
