### DISCUSSION TITLE
ffmpeg not found in path with cab497e-h8l image

### DISCUSSION THREAD

**Discussion by hiteshsharma** [blakeblackshear/frigate#14027] [General Support]
Hi,

I'm using `cab497e-h8l` on a raspberry pi 5 with hailo AI kit. When running frigate, I'm getting this error in go2rtc logs

`tag: exec`
```
error="exec: \"ffmpeg\": executable file not found in $PATH" url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/reolink_sub?audio -c:a libopus -application:a lowdelay -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/3fb6f19f79c4b85b2824e1d718216c96"
```

docker-compose.yml
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:cab497e-h8l
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/hailo0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "*******"
```

Frigate `config.yml`
```
mqtt:
  host: 192.168.1.99         # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_2               # YOUR MQTT USERNAME
  password: ********       # YOUT MQTT PASSWORD
  stats_interval: 60

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    record:
      enabled: true

#ffmpeg:
#  hwaccel_args: preset-rpi-64-h264

    motion:
      mask: 0.322,0.02,0.655,0.016,0.655,0.045,0.329,0.05
go2rtc:
  streams:
                    ## CHANGE RTSP USERNAME AND PASSWORD
    reolink:
      #- rtsp://admin:password@192.168.1.100:554/Preview_01_main
      - ffmpeg:reolink#audio=opus
      - rtsp://admin:password@192.168.1.100:554/Preview_01_main#audio=pcm#audio=volume
    reolink_sub:
      - ffmpeg:reolink_sub#audio=opus
      - rtsp://admin:password@192.168.1.100:554/Preview_01_sub#audio=pcm#audio=volume


## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED

  ffmpeg:

    bin: ffmpeg

    volume: -af "volume=30dB"


detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: ssd
version: 0.15-0
```
Camera: Reolink Poe Doorbell
I'm able to see the live view and also persons are getting detected. From logs it also seems that hailo is being used for detection.

First time using Frigate. Help appreciated.
