### DISCUSSION TITLE
[Support]: Incorrect Free Disk Space in storage - causing device to fill and not remove old recordings

### DISCUSSION THREAD

**Discussion by dsanner** [blakeblackshear/frigate#14030] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Incorrect Free Disk Space in storage - causing device to fill and not remove old recordings.  
system#storage is reporting 3.18 GiB/97.87 GiB and unused free space at Unused Free Space 94.65 GiB

However, df -h in the docker container shows: 
<img width="585" alt="Screenshot 2024-09-28 at 5 25 14 AM" src="https://github.com/user-attachments/assets/e00bd76a-7027-4f01-8ac2-9a4867f02414">

```
root@intelbeelink:~/frigate# docker exec -it frigate df -h
Filesystem                         Size  Used Avail Use% Mounted on
overlay                             98G   25G   68G  27% /
tmpfs                               64M     0   64M   0% /dev
shm                                512M  383M  130M  75% /dev/shm
/dev/mapper/ubuntu--vg-ubuntu--lv   98G   25G   68G  27% /config
tmpfs                              1.9G   37M  1.9G   2% /tmp/cache
```

This is causing the device to fill completely not not delete older recordings when drive fills. (seems similar to problem referenced in https://github.com/blakeblackshear/frigate/issues/9275#issuecomment-2369703122) 

### Steps to reproduce

fresh install with 0.15.0-08941ab and docker compose running as root on ubuntu 

### Version

0.15.0-08941ab

### In which browser(s) are you experiencing the issue with?

Safari

### Frigate config file

```yaml
.
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: always
    image: "ghcr.io/blakeblackshear/frigate:08941ab"
    cap_add:
      - CAP_PERFMON
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config/:/config/
      - /root/frigate/media/:/media/frigate/
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
ports:
      - "5000:5000"
      - "1984:1984/tcp"
      - "1984:1984/udp"
      - "8554:8554/tcp"
      - "8554:8554/udp"
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

.

### Screenshots of the Frigate UI's System metrics pages

.
