### DISCUSSION TITLE
Reolink Dooerbell [POE] probelm with 2 way audio - no have option to turn on mic - the Icon doesn't exists on the camera page

### DISCUSSION THREAD

**Discussion by antonbek89** [blakeblackshear/frigate#14032] [Config Support]
### Describe the problem you are having

So I follow over Frigate documentation and copy the relevant lines for Reolink doorbell
but I not have option to start microphone on Frigate

### Version

0.14.1- f4f3cfa 

### Frigate config file

```yaml
go2rtc:
  streams:
    Doorbell:
      - ffmpeg:http://192.168.1.142/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=admin#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.142/Preview_01_sub
    Doorbell_sub:
      - ffmpeg:http://192.168.1.142/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=admin

cameras:

  Doorbell:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
```

### Relevant Frigate log output

```shell
*
```

### Relevant go2rtc log output

```shell
*
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
docker compose up

version: "3.9"
services:
  frigate:
    container_name: FrigateNvidia14.RC1
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
#              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    shm_size: "1024mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /home/a/Downloads/frigateNvidia/config/config.yml:/config/config.yml
      - /home/a/Downloads/New_Frigate_Drive:/media/frigate
      - /home/a/Downloads/frigateNvidia/config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Object Detector

Coral
