### DISCUSSION TITLE
[Bug]: Frigate reports Person Occupancy but person image doesnt update & HASS

### DISCUSSION THREAD

**Discussion by rourke750** [blakeblackshear/frigate#14039] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Using 5.4.0/0.14.1-f4f3cfa of frigate for homeassistant and running 0.14.1-f4f3cfa based on metrics page.  I've noticed that person count and person occupancy will increase even though there isnt a person there.  The person image does not update and the frigate ui does not have any events.  I noticed based on my automation:

```
trigger:
    - platform: mqtt
      topic: frigate/events
      encoding: ""
  condition:
    - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    - "{{ trigger.payload_json['after']['camera'] == 'front_door' }}"
  action:
    - service: shell_command.upload_rocketchat_frontdoor
      data:
        url: 'http://xxx:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg'
    - service: notify.xxx
      data:
        message: "Movement detected: Front Door"
    - delay: 00:00:05
  ```

![image](https://github.com/user-attachments/assets/eb80cb79-96f9-4d54-8cdb-e416bbfb01a2)
![image](https://github.com/user-attachments/assets/23223e9a-5503-4693-b1e8-6de4e33c3262)

### Steps to reproduce

I am unsure how to reproduce it almost seems lighting based.

### Version

5.4.0/0.14.1-f4f3cfa

### Frigate config file

```yaml
NA
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

NA

### Screenshots of the Frigate UI's System metrics pages

NA
