### DISCUSSION TITLE
HA automation to prevent recording

### DISCUSSION THREAD

**Discussion by mariomare22** [blakeblackshear/frigate#14047] [Ask A Question]
Hello!

This is part of my `confif.yaml` in home assistant I have the integration configured and I would like to disable recording when I come back home and enable it once i go out. But the recordings, snapshots, and detect gets enabled automatically and keeps recording continously.

What am I doing wrong in my configuration?

```
detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.85

detect:
  width: 1280
  height: 720
  fps: 5

record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 720
  retain:
    default: 10
    objects:
      person: 15

cameras:
  sala:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-http-reolink
      inputs:
        - path:
            http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming
          roles:
            - record
        - path:
            http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming
          roles:
            - detect
```
Automation:
```
alias: disable_recordings_frigate
description: ""
trigger:
  - platform: state
    entity_id:
      - group.family
    to: Home
condition: []
action:
  - action: switch.turn_off
    target:
      entity_id:
        - switch.sala_recordings
        - switch.sala_snapshots
    data: {}
  - alias: tg message
    data:
      message: Recording Disabled
    action: telegram_bot.send_message
mode: single
```

**Comment by NickM-27** [comment]
if frigate restarts then the recordings will be enabled, other than that you should check the logs to see why recordings were enabled again

**Comment by mariomare22** [comment]
Ok that is clear now! thank you for your constant help!
My question now is:
I would like to enable recording once i am away from home BUT only record and snapshots in order to receive also notifications from HA via automation
```
record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 720
  retain:
    default: 10
    objects:
      person: 15
```   
**when detection takes place**  
```
detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.85

detect:
  width: 1280
  height: 720
  fps: 5
 ```
and once I am home disable again the recordings

What is the best way to achieve this?

**Comment by mariomare22** [comment]
Excuse me Nick, now I am not getting any detection in my system and also I am not sure I am using hw acceleration with the nvidia Quadro, and the detection of the Coral USB 😢 
Can you please help me?
```
services:
  frigate:
    container_name: frigate
    environment:
      - PUID=1000
      - PGID=1000
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb 
    shm_size: "64mb"
    networks:
      - proxy_inet
    ports:
      - 1935:1935
      - 5000:5000
    restart: unless-stopped
    volumes:
      - /mnt/ssd/config/frigate/:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas_nfs/frigate/:/media/frigate
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```              


```
mqtt:
  host: server.home
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: objects
#  mode: continuous

motion:
  threshold: 30

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  filters:
    person:
      min_score: 0.85

detect:
  width: 1280
  height: 720
  fps: 5

record:
  enabled: true
  retain:
    days: 10
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 720
  retain:
    default: 10
    objects:
      person: 15
go2rtc:
  streams:
    sala:
      - "ffmpeg:http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming"
      - "ffmpeg:sala#audio=opus"
    sala_sub:
      - "ffmpeg:http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming"
    elisa:
      - "ffmpeg:http://10.22.30.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming"
      - "ffmpeg:elisa#audio=opus"
    elisa_sub:
      - "ffmpeg:http://10.22.30.2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming"
cameras:
  sala:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sala
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sala_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  elisa:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/elisa
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/elisa_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

version: 0.14
camera_groups: {}
```
