### DISCUSSION TITLE
Struggling to rotate a camera feed

### DISCUSSION THREAD

**Discussion by meatballs** [blakeblackshear/frigate#14041] [Ask A Question]
Similar to https://github.com/blakeblackshear/frigate/discussions/6807

I have a ipc-t250h by hikvision.

If I use the following config, all works just fine:

```
go2rtc:
  streams:
    front_porch_hd:
      - rtsp://<user>:<pwd>@<address>/Streaming/Channels/101
    front_porch:
      - rtsp://<user>:<pwd>@<address>/Streaming/Channels/102

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch_hd
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/front_porch
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
```

but, I need to mount the camera at 90 degrees, so I'd like to rotate the stream. I've tried:

```
go2rtc:
  streams:
    front_porch_hd:
      - ffmpeg:rtsp://<user>:<pwd>@<address>/Streaming/Channels/101#video=h264#rotate=90
    front_porch:
      - ffmpeg:rtsp://<user>:<pwd>@<address>/Streaming/Channels/102#video=h264#rotate=90

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch_hd
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/front_porch
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
```

as suggested in the linked discussion, but then get:

```
frigate  | 2024-09-28 18:36:38.234042950  [2024-09-28 18:36:38] watchdog.front_porch           ERROR   : Ffmpeg process crashed unexpectedly for front_porch.
frigate  | 2024-09-28 18:36:38.235914487  [2024-09-28 18:36:38] watchdog.front_porch           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-09-28 18:36:38.235927821  [2024-09-28 18:36:38] ffmpeg.front_porch.detect      ERROR   : rtsp://127.0.0.1:8554/front_porch: Invalid data found when processing input
```

Any suggestions for where I might go next gratefully received!
