### DISCUSSION TITLE
[Config Support]: High CPU Usage of ffmpeg on one camera

### DISCUSSION THREAD

**Discussion by tkorves** [blakeblackshear/frigate#14059] [Config Support]
### Describe the problem you are having

Hi there,

I constantly get the warning, that one camera (Office Ceiling) is creating high cpu usage of ffmpeg - with no reason I'm able to see. I attached the config.

Running on a Mini-PC with an Intel N100, 8GB RAM, NVMe SSD, Coral TPU attached to it via USB3. I installed the Intel GPU drivers on my Debian 12 install. Running with Docker compose and also mapped the TPU as well as the GPU to the container.

Thanks for any heads up.

Tim

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.6
  port: 1883
  user: frigate
  password: PASSWORD
  topic_prefix: frigate

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - car
    - person
    - dog

cameras:
  # UniFi Doorbell Camera (start)
  home_doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://100.71.3.39:7447/YcfiatsJCdeD0hpf
          roles:
            - detect
            - record
    detect:
      enabled: true

    zones:
      home_doorbell_person:
        coordinates: 
          0.459,0.631,0.478,0.634,0.497,0.671,0.561,0.715,0.556,0.83,0.651,0.842,0.801,1,0.001,0.997,0.001,0.001,0.543,0.001,0.469,0.254
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      detections:
        required_zones: home_doorbell_person
      alerts:
        required_zones: home_doorbell_person
    motion:
      mask:
        - 0.004,0.028,0.263,0.029,0.26,0.002,0.003,0.004
        - 0.461,0.627,0.48,0.631,0.5,0.669,0.563,0.712,0.558,0.828,0.661,0.849,0.804,1,1,1,1,0,0.546,0,0.47,0.258
    objects:
      track:
        - person

    record:
      enabled: true
      retain:
        days: 2
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: active_objects
        objects:
          - person

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
  # UniFi Doorbell Camera (end)

  # UniFi Street West Camera (start)
  home_street:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://100.71.3.39:7447/zyE1F60XmV8zzzNf
          roles:
            - detect
            - record
    detect:
      enabled: true

    zones:
      home_street_person:
        coordinates: 0.353,0.997,0.325,0.563,0.386,0.138,0.477,0.115,0.473,0,0.999,0,0.999,0.997
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: home_street_person
      detections:
        required_zones: home_street_person
    motion:
      mask: 0.352,1,0.324,0.564,0.385,0.135,0.475,0.115,0.472,0,0,0,0,0.999
    objects:
      track:
        - person

    record:
      enabled: true
      retain:
        days: 2
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: active_objects
        objects:
          - person

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
  # UniFi Street West Camera (end)

  # UniFi Porch Camera (start)
  home_porch:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://100.71.3.39:7447/zRIShkYhrufAWpqd
          roles:
            - detect
            - record
    detect:
      enabled: true

    zones:
      home_porch_person:
        coordinates: 
          0.001,0.95,0.09,0.84,0.024,0.414,0.001,0.379,0,0.322,0.036,0.303,0.037,0.353,0.14,0.292,0.185,0.486,0.449,0.314,0.46,0.101,0.825,0.162,0.772,0.201,0.716,0.296,0.736,0.322,0.897,0.242,0.999,0.357,0.999,0.999,0,0.999
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: home_porch_person
      detections:
        required_zones: home_porch_person
    motion:
      mask:
        - 0.001,0.316,0.037,0.301,0.038,0.351,0.14,0.292,0.187,0.481,0.447,0.31,0.46,0.078,0,0.071
        - 0.772,0.202,0.716,0.295,0.732,0.323,0.898,0.242,0.999,0.356,0.999,0.198,0.829,0.16
    objects:
      track:
        - person

    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 7
  # UniFi Porch Camera (end)

  # UniFi Alleyway Camera (start)
  home_alleyway:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://100.71.3.39:7447/9uc3HsQUisTczix5
          roles:
            - detect
            - record
    detect:
      enabled: true

    zones:
      home_alleyway_person:
        coordinates: 0,0.338,0.511,0.266,0.518,0,0.999,0,0.999,0.999,0.001,0.999
        loitering_time: 0
        objects: person
    objects:
      track:
        - person

    record:
      enabled: true
      retain:
        days: 2
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: active_objects
        objects:
          - person

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
  # UniFi Alleyway Camera (end)

  # UniFi Office Ceiling Camera (start)
    review:
      alerts:
        required_zones: home_alleyway_person
      detections:
        required_zones: home_alleyway_person
    motion:
      mask: 0,0.336,0.511,0.265,0.518,0,0,0
  office_ceiling:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://100.71.3.39:7447/x7uUuHaDqd7Se3tv
          roles:
            - detect
            - record
    detect:
      enabled: true

    zones:
      office_ceiling_person:
        coordinates: 
          0.045,0.736,0,0.739,0.001,0,0.245,0,0.27,0.429,0.44,0.408,0.656,0.397,0.652,0.001,0.735,0,0.736,0.542,0.764,0.724,0.721,0.981,0.452,0.908,0.391,0.897,0.408,0.832
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: office_ceiling_person
      detections:
        required_zones: office_ceiling_person
    motion:
      mask:
  # UniFi Office Ceiling Camera (end)

  # UniFi Office Street Camera (start)
        - 0.204,0.507,0.175,0.04,0,0.038,0,0,0.65,0.001,0.656,0.396,0.455,0.404,0.46,0.507
        - 0.001,0.996,0.001,0.736,0.044,0.736,0.409,0.831,0.392,0.897,0.721,0.982,0.767,0.723,0.737,0.537,0.737,0,0.754,0,0.78,0.036,0.784,0.158,0.894,0.282,0.874,0.662,0.834,0.996
  office_street:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://100.71.3.39:7447/6JPx0tXNVrS8ZYa7
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:

        - 0.308,1,0.303,0.439,0.832,0.426,0.812,0.724,0.303,0.56,0.307,1,1,1,1,0,0,0,0,1
        - 0.003,0.03,0.171,0.036,0.17,0.004,0.004,0.004
    objects:
      track:
        - car

    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 1
          mode: active_objects
        objects:
          - car

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 7

    zones:
      street:
        coordinates: 
          0.306,0.56,0.304,0.44,0.492,0.429,0.553,0.432,0.617,0.426,0.659,0.422,0.737,0.424,0.832,0.428,0.813,0.727
        inertia: 1
        loitering_time: 0
        objects: car
    review:
      alerts:
        required_zones: street
      detections:
        required_zones: street
  # UniFi Office Street Camera (end)

version: 0.14

camera_groups:
  Home:
    order: 1
    icon: LuHome
    cameras:
      - home_alleyway
      - home_doorbell
      - home_porch
      - home_street
  Office:
    order: 2
    icon: LuFolder
    cameras: office_ceiling
```

### Relevant Frigate log output

```shell
2024-09-30 10:40:59.585135243  [INFO] Preparing Frigate...
2024-09-30 10:40:59.606421318  [INFO] Starting Frigate...
2024-09-30 10:41:00.957761996  [2024-09-30 10:41:00] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-09-30 10:41:00.957903250  [2024-09-30 10:41:00] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-09-30 10:41:01.020177653  [2024-09-30 10:41:01] frigate.util.config            INFO    : frigate config does not need migration...
2024-09-30 10:41:06.667836929  [2024-09-30 10:41:06] peewee_migrate.logs            INFO    : Starting migrations
2024-09-30 10:41:06.667941707  [2024-09-30 10:41:06] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-09-30 10:41:07.757410408  [2024-09-30 10:41:07] frigate.app                    INFO    : Recording process started: 369
2024-09-30 10:41:07.757415372  [2024-09-30 10:41:07] frigate.app                    INFO    : Recording process started: 375
2024-09-30 10:41:07.760013112  [2024-09-30 10:41:07] frigate.app                    INFO    : go2rtc process pid: 111
2024-09-30 10:41:07.789620546  [2024-09-30 10:41:07] detector.coral                 INFO    : Starting detection process: 398
2024-09-30 10:41:10.437824585  [2024-09-30 10:41:07] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-09-30 10:41:10.439666543  [2024-09-30 10:41:07] frigate.app                    INFO    : Output process started: 402
2024-09-30 10:41:10.439674906  [2024-09-30 10:41:07] frigate.app                    INFO    : Camera processor started for home_doorbell: 418
2024-09-30 10:41:10.439678513  [2024-09-30 10:41:07] frigate.app                    INFO    : Camera processor started for home_street: 419
2024-09-30 10:41:10.439687292  [2024-09-30 10:41:07] frigate.app                    INFO    : Camera processor started for home_porch: 427
2024-09-30 10:41:10.439847053  [2024-09-30 10:41:07] frigate.app                    INFO    : Camera processor started for home_alleyway: 429
2024-09-30 10:41:10.440311196  [2024-09-30 10:41:07] frigate.app                    INFO    : Camera processor started for office_ceiling: 441
2024-09-30 10:41:10.440646105  [2024-09-30 10:41:07] frigate.app                    INFO    : Camera processor started for office_street: 449
2024-09-30 10:41:10.441071161  [2024-09-30 10:41:07] frigate.app                    INFO    : Capture process started for home_doorbell: 452
2024-09-30 10:41:10.441218069  [2024-09-30 10:41:07] frigate.app                    INFO    : Capture process started for home_street: 462
2024-09-30 10:41:10.442417375  [2024-09-30 10:41:08] frigate.app                    INFO    : Capture process started for home_porch: 472
2024-09-30 10:41:10.442424318  [2024-09-30 10:41:08] frigate.app                    INFO    : Capture process started for home_alleyway: 476
2024-09-30 10:41:10.442428201  [2024-09-30 10:41:08] frigate.app                    INFO    : Capture process started for office_ceiling: 479
2024-09-30 10:41:10.442431476  [2024-09-30 10:41:08] frigate.app                    INFO    : Capture process started for office_street: 484
2024-09-30 10:41:10.445010524  [2024-09-30 10:41:10] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-09-30 10:41:41.172123641  [2024-09-30 10:41:41] frigate.comms.dispatcher       INFO    : Setting motion threshold for home_alleyway: 30
2024-09-30 10:41:41.186405695  [2024-09-30 10:41:41] frigate.comms.dispatcher       INFO    : Setting motion contour area for home_alleyway: 10
```

### Relevant go2rtc log output

```shell
2024-09-30 10:40:59.591008476  [INFO] Preparing new go2rtc config...
2024-09-30 10:41:00.103505298  [INFO] Starting go2rtc...
2024-09-30 10:41:00.202773415  10:41:00.201 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-30 10:41:00.202778150  10:41:00.202 INF config path=/dev/shm/go2rtc.yaml
2024-09-30 10:41:00.202780153  10:41:00.202 INF [rtsp] listen addr=:8554
2024-09-30 10:41:00.202781957  10:41:00.202 INF [webrtc] listen addr=:8555/tcp
2024-09-30 10:41:00.203631313  10:41:00.203 INF [api] listen addr=:1984
2024-09-30 10:41:09.586169582  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
    "cameras": {
        "home_alleyway": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 476,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 494,
            "pid": 429,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "home_doorbell": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 452,
            "detection_enabled": true,
            "detection_fps": 0.3,
            "ffmpeg_pid": 474,
            "pid": 418,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "home_porch": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 472,
            "detection_enabled": true,
            "detection_fps": 2.7,
            "ffmpeg_pid": 487,
            "pid": 427,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "home_street": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 462,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 473,
            "pid": 419,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "office_ceiling": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 479,
            "detection_enabled": true,
            "detection_fps": 0.8,
            "ffmpeg_pid": 486,
            "pid": 441,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "office_street": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 484,
            "detection_enabled": true,
            "detection_fps": 4.4,
            "ffmpeg_pid": 497,
            "pid": 449,
            "process_fps": 5,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "46": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "86": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "111": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "122": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "123": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "5.4",
            "cpu_average": "11",
            "mem": "22.6"
        },
        "132": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "164": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "165": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "166": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "167": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "168": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "301": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "340": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "1.5"
        },
        "369": {
            "cmdline": "frigate.recording_manager",
            "cpu": "3.8",
            "cpu_average": "3",
            "mem": "2.4"
        },
        "375": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "2.2"
        },
        "397": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(67)",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "398": {
            "cmdline": "frigate.detector.coral",
            "cpu": "5.3",
            "cpu_average": "9",
            "mem": "2.1"
        },
        "402": {
            "cmdline": "frigate.output       ",
            "cpu": "5.3",
            "cpu_average": "6",
            "mem": "2.6"
        },
        "418": {
            "cmdline": "frigate.process:home_doorbell",
            "cpu": "1.5",
            "cpu_average": "3",
            "mem": "3.4"
        },
        "419": {
            "cmdline": "frigate.process:home_street",
            "cpu": "1.2",
            "cpu_average": "3",
            "mem": "3.6"
        },
        "427": {
            "cmdline": "frigate.process:home_porch",
            "cpu": "2.9",
            "cpu_average": "3",
            "mem": "3.2"
        },
        "429": {
            "cmdline": "frigate.process:home_alleyway",
            "cpu": "1.8",
            "cpu_average": "2",
            "mem": "3.5"
        },
        "441": {
            "cmdline": "frigate.process:office_ceiling",
            "cpu": "1.7",
            "cpu_average": "1",
            "mem": "3.4"
        },
        "449": {
            "cmdline": "frigate.process:office_street",
            "cpu": "3.6",
            "cpu_average": "5",
            "mem": "3.3"
        },
        "452": {
            "cmdline": "frigate.capture:home_doorbell",
            "cpu": "2.5",
            "cpu_average": "2",
            "mem": "3.0"
        },
        "462": {
            "cmdline": "frigate.capture:home_street",
            "cpu": "3.8",
            "cpu_average": "4",
            "mem": "3.1"
        },
        "472": {
            "cmdline": "frigate.capture:home_porch",
            "cpu": "3.2",
            "cpu_average": "3",
            "mem": "3.1"
        },
        "473": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://100.71.3.39:7447/zyE1F60XmV8zzzNf -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/home_street@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2688:h=1512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "22.4",
            "cpu_average": "24",
            "mem": "1.3"
        },
        "474": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://100.71.3.39:7447/YcfiatsJCdeD0hpf -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/home_doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1600:h=1200:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "18.2",
            "cpu_average": "16",
            "mem": "1.0"
        },
        "476": {
            "cmdline": "frigate.capture:home_alleyway",
            "cpu": "3.4",
            "cpu_average": "3",
            "mem": "3.1"
        },
        "479": {
            "cmdline": "frigate.capture:office_ceiling",
            "cpu": "4.5",
            "cpu_average": "4",
            "mem": "3.1"
        },
        "484": {
            "cmdline": "frigate.capture:office_street",
            "cpu": "2.9",
            "cpu_average": "2",
            "mem": "3.1"
        },
        "486": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://100.71.3.39:7447/x7uUuHaDqd7Se3tv -r 5 -vf fps=5,scale_vaapi=w=2688:h=1512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "22.0",
            "cpu_average": "22",
            "mem": "1.3"
        },
        "487": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://100.71.3.39:7447/zRIShkYhrufAWpqd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/home_porch@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "18.8",
            "cpu_average": "17",
            "mem": "1.1"
        },
        "494": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://100.71.3.39:7447/9uc3HsQUisTczix5 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/home_alleyway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "17.7",
            "cpu_average": "17",
            "mem": "1.1"
        },
        "497": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://100.71.3.39:7447/6JPx0tXNVrS8ZYa7 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/office_street@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "18.1",
            "cpu_average": "18",
            "mem": "1.2"
        },
        "536": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1600x1200 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "541": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2688x1512 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "546": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "551": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "556": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2688x1512 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "561": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "566": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "826": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(56)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "6886": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "6924": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "44.8",
            "mem": "54.8"
        }
    },
    "detection_fps": 8.2,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 9.9,
            "pid": 398
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "20.63%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 111
        },
        "logger": {
            "pid": 340
        },
        "recording": {
            "pid": 369
        },
        "review_segment": {
            "pid": 375
        }
    },
    "service": {
        "last_updated": 1727686883,
        "latest_version": "0.14.1",
        "storage": {
            "/dev/shm": {
                "free": 484.3,
                "mount_type": "tmpfs",
                "total": 512,
                "used": 27.7
            },
            "/media/frigate/clips": {
                "free": 99472.7,
                "mount_type": "ext4",
                "total": 118147.7,
                "used": 12628.3
            },
            "/media/frigate/recordings": {
                "free": 99472.7,
                "mount_type": "ext4",
                "total": 118147.7,
                "used": 12628.3
            },
            "/tmp/cache": {
                "free": 943.8,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 9.9
            }
        },
        "temperatures": {},
        "uptime": 1215,
        "version": "0.14.1-f4f3cfa"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/config:/config
      - ./data/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD"
```

### Object Detector

Coral
