### DISCUSSION TITLE
[Camera Support]: Error Tag frigate.ptz.onvif Message Onvif is not setup for frontnorth

### DISCUSSION THREAD

**Discussion by dz4news** [blakeblackshear/frigate#14056] [Camera Support] [answered]
### Describe the problem you are having

I am getting an error message in the frigate logs that has recently been showing up. I think this may be associated with the recent release with the Frigate Camera Card update, but I am not sure. From what I can tell, the error gets generated when I view the cameras within HA. However, none of my cameras are PTZ capable and never have been. Is there a setting I am missing? Do I need to have Onvif activated on my cameras? 

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  host: 
  port: 
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 15
  # Optional: TLS configuration
tls:
  # Optional: Enable TLS for port 8080 (default: shown below)
  enabled: false
review:
  alerts:
    labels:
      - car
      - person
      - face
      - amazon
      - ups
      - fedex
  detections:
    labels:
      - deer
      - dog
      - cat
      - thunder
      - thunderstorm
      - bark
      - howl
      - gunshot
detectors:
  #coral_usb:
  #  type: edgetpu
  #  device: usb
  coral_pci_0:
    type: edgetpu
    device: pci:0
  coral_pci_1:
    type: edgetpu
    device: pci:1
# logger:
#  default: error
#  logs:
#    frigate.record.maintainer: warning
model:
  path: plus://
### Global Setting ###
audio:
  enabled: true
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (200 high ; 1000 low)
  min_volume: 300
  listen:
    - gunshot
    - explosion
    - honk
    - emergency_vehicle
    - bark
    - meow
    - thunder
    - thunderstorm
    - speech
    - yell
    - howl
  filters:
    speech:
      threshold: 0.85
    honk:
      threshold: 0.7
    gunshot:
      threshold: 0.6
    bark:
      threshold: 0.5
    thunder:
      threshold: 0.5
    thunderstorm:
      threshold: 0.5
    howl:
      threshold: 0.5
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  quality: 100
  height: 500
  crop: false
  retain:
    default: 5
    mode: active_objects
  required_zones:
    - frontyard
    - driveway
    - backpatio
    - back_yard
    - back_yard_north
    - street
birdseye:
  enabled: false
  restream: false
  mode: objects
record:
  enabled: true
  sync_recordings: false
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 10
    post_capture: 10
    objects:
      - person
      - license_plate
      - dog
      - car
      - cat
      - deer
      - bird
      - amazon
      - fedex
      - ups
      - face
    retain:
      default: 7
      mode: motion
      objects:
        dog: 5
        car: 7
        license_plate: 7
        person: 10
        amazon: 7
        fedex: 7
        ups: 7
        speech: 10
        gunshot: 3
        bark: 3
        thunder: 5
        honk: 3
        explotion: 3
        emergency_vehicle: 5
        thunderstorm: 5
### Timestamp Style Setting ###
timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 1
  effect: solid
#### go2rtc config ###
go2rtc:
  streams:
    frontnorth:
      - rtsp://.../live0
      - ffmpeg:frontnorth#audio=opus
    frontnorth_sub: rtsp://.../cam/realmonitor?channel=1&subtype=2
    frontsouth:
      - rtsp://.../live0
      - ffmpeg:frontsouth#audio=opus
    frontsouth_sub: rtsp://.../cam/realmonitor?channel=1&subtype=2
    carport:
      - rtsp://.../live0
      - ffmpeg:carport#audio=opus
    carport_sub: rtsp://.../cam/realmonitor?channel=1&subtype=2
    backporch:
      - rtsp://.../live0
      - ffmpeg:backporch#audio=opus
    backporch_sub: rtsp://.../cam/realmonitor?channel=1&subtype=2
    backyard:
      - rtsp://.../live0
      - ffmpeg:backyard#audio=opus
    backyard_sub: rtsp://.../cam/realmonitor?channel=1&subtype=2
    backyard_north:
      - rtsp://.../live0
      - ffmpeg:backyard_north#audio=opus
    backyard_north_sub: rtsp://.../cam/realmonitor?channel=1&subtype=2
  webrtc:
    candidates:
      - ...:8555
      - stun:8555
#### Global Camera Settings ###
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  annotation_offset: -800
objects:
  track:
    - person
    - dog
    - deer
    - car
    - license_plate
    - cat
    - amazon
    - fedex
    - ups
    - face
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy
motion:
  threshold: 25
  improve_contrast: false
### Camera Settings ###
### Front Camera - Facing North IPC-T5442TM-AS 2.8mm ###
cameras:
  frontnorth:
    enabled: true
    audio:
      enabled: true
    ui:
      order: 0
    birdseye:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://.../frontnorth_sub
          roles:
            - audio
            - detect
        - path: rtsp://.../frontnorth
          roles:
            - record
    objects:
      filters:
        bird:
          min_score: 0.75
        car:
          min_area: 2000
          max_area: 24000000
          min_score: 0.75
        amazon:
          min_score: 0.75
        fedex:
          min_score: 0.75
        ups:
          min_score: 0.75
        cat:
          min_score: 0.80
          threshold: 0.7
        dog:
          min_score: 0.80
          threshold: 0.7
        deer:
          min_score: 0.85
          threshold: 0.7
        person:
          min_score: 0.90
          threshold: 0.7
    motion:
      mask:
        - 0.412,1,0.41,0.924,0,0.935,0,1
        - 0.382,0,0.233,0,0.116,0.2,0.347,0.138
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    zones:
      frontyard:
        coordinates: 
          0.117,0.362,0.367,0.258,0.996,0.55,0.998,0.995,0.005,0.992,0.022,0.603,0.065,0.405,0.105,0.373
        loitering_time: 0
        objects:
          - dog
          - person
    review:
      detections: {}
      alerts:
        required_zones: frontyard
  frontsouth:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 1
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://.../frontsouth_sub
          roles:
            - audio
            - detect
        - path: rtsp://.../frontsouth
          roles:
            - record
    objects:
      filters:
        bird:
          min_score: 0.90
        car:
          min_score: 0.80
          min_area: 5000
          max_area: 24000000
        license_plate:
          min_score: 0.75
        amazon:
          min_score: 0.75
        fedex:
          min_score: 0.75
        ups:
          min_score: 0.75
        cat:
          min_score: 0.85
          threshold: 0.7
        dog:
          min_score: 0.80
          threshold: 0.5
        deer:
          min_score: 0.85
          threshold: 0.7
        person:
          min_score: 0.90
          threshold: 0.7
    motion:
      mask: 0.738,0,0.741,0.05,0.912,0.051,0.916,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    zones:
      frontyard:
        coordinates: 
          0.077,0.708,0.091,0.628,0.648,0.161,0.853,0.197,0.928,0.187,0.989,0.733,0.994,0.988,0.166,0.99
        loitering_time: 0
        objects:
          - dog
          - person
    review:
      alerts:
        required_zones: frontyard
  carport:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 2
    birdseye:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://.../carport_sub
          roles:
            - audio
            - detect
        - path: rtsp://.../carport
          roles:
            - record
    objects:
      filters:
        deer:
          min_score: 0.85
        bird:
          min_score: 0.90
        car:
          min_score: 0.85
          max_area: 200000
          mask: 0.555,0.52,1,0.862,1,0.081,0.557,0.069
        license_plate:
          min_score: 0.75
        amazon:
          min_score: 0.75
        fedex:
          min_score: 0.75
        ups:
          min_score: 0.75
        cat:
          min_score: 0.90
          threshold: 0.7
        dog:
          min_score: 0.85
          threshold: 0.7
        person:
          min_score: 0.90
    motion:
      mask:
        - 1,0,1,0.069,0.576,0.071,0.546,0
        - 0,0.917,0.085,0.967,0.27,0.951,0.287,0.734,0.22,0.413,0,0.44,0,0.656
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    zones:
      street:
        coordinates: 0.005,0.225,0.509,0.135,0.513,0.178,0.009,0.259
        inertia: 1
        loitering_time: 0
        objects:
          - car
          - person
      driveway:
        coordinates: 
          0.517,0.495,0.35,0.409,0.2,0.298,0.099,0.248,0.162,0.24,0.235,0.256,0.387,0.291,0.513,0.315,0.515,0.393
        loitering_time: 0
        objects:
          - car
          - dog
          - person
    review:
      alerts:
        required_zones: driveway
  backporch:
    enabled: true
    audio:
      enabled: true
    ui:
      order: 3
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://.../backporch_sub
          roles:
            - audio
            - detect
        - path: rtsp://.../backporch
          roles:
            - record
    objects:
      filters:
        car:
          min_area: 500000
          min_score: 0.99
        bird:
          min_score: 0.90
          threshold: 0.7
        cat:
          min_score: 0.80
          threshold: 0.7
        dog:
          min_score: 0.85
          threshold: 0.7
        person:
          min_score: 0.90
          max_ratio: 0.55
    motion:
      mask:
        - 610,125,943,133,950,74,1280,64,1280,0,606,0
        - 850,290,1008,368,1060,213,896,163
        - 612,481,773,617,946,516,984,374,784,278,632,343
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    zones:
      backpatio:
        coordinates: 
          0.085,0.775,0.113,0.708,0.715,0.346,0.894,0.525,0.935,0.685,0.979,0.877,0.881,0.996,0.112,0.992
        loitering_time: 0
        objects:
          - dog
          - person
    review:
      alerts:
        required_zones: backpatio
  backyard:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 4
    birdseye:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://.../backyard_sub
          roles:
            - audio
            - detect
        - path: rtsp://.../backyard
          roles:
            - record
    objects:
      filters:
        bird:
          min_score: 0.85
        deer:
          min_score: 0.85
          threshold: 0.7
        car:
          min_area: 2000
          max_area: 24000000
          min_score: 0.90
        cat:
          max_area: 20000
          min_score: 0.80
          threshold: 0.5
        dog:
          max_area: 40000
          min_score: 0.80
          threshold: 0.5
        person:
          min_score: 0.90
    motion:
      mask:
        - 944,52,1193,48,1192,0,940,0
        - 184,92,289,77,400,31,449,0,0,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    zones:
      back_yard:
        coordinates: 
          0.005,0.409,0.003,0.253,0.132,0.145,0.501,0.11,0.631,0.12,0.997,0.185,0.995,0.986,0.009,0.993
        loitering_time: 0
        objects:
          - deer
          - dog
          - person
          - cat
    review:
      alerts:
        required_zones: back_yard
  backyard_north:
    enabled: true
    audio:
      enabled: true
    ui:
      order: 5
    birdseye:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://.../backyard_north
          roles:
            - record
        - path: rtsp://.../backyard_north_sub
          roles:
            - detect
            - audio
    objects:
      filters:
        bird:
          min_area: 1000
          max_area: 100000
          min_score: 0.85
          threshold: 0.7
        deer:
          min_score: 0.90
          threshold: 0.7
        car:
          min_score: 0.85
          min_area: 2000
        cat:
          max_area: 20000
          min_score: 0.90
          threshold: 0.7
        dog:
          max_area: 40000
          min_score: 0.85
          threshold: 0.7
        person:
          min_score: 0.90
    motion:
      mask: 0.572,0.178,0.914,0.21,0.948,0.104,0.928,0,0.538,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'false'
    zones:
      back_yard_north:
        coordinates: 
          0.002,0.231,0.296,0.154,0.351,0.169,0.53,0.143,0.995,0.354,0.995,0.983,0.007,0.99
        loitering_time: 0
        objects:
          - deer
          - dog
          - person
    review:
      alerts:
        required_zones: back_yard_north
camera_groups:
  Backyard:
    order: 2
    icon: LuArrowBigDown
    cameras:
      - backporch
      - backyard
      - backyard_north
  Frontyard:
    order: 1
    icon: LuArrowBigUp
    cameras:
      - carport
      - frontnorth
      - frontsouth
version: 0.14
```

### Relevant Frigate log output

```shell
2024-09-29 18:25:57.301483427  [2024-09-29 18:25:57] frigate.ptz.onvif              ERROR   : Onvif is not setup for frontsouth
2024-09-29 18:25:57.305985337  [2024-09-29 18:25:57] frigate.ptz.onvif              ERROR   : Onvif is not setup for frontnorth
2024-09-29 18:25:57.309845165  [2024-09-29 18:25:57] frigate.ptz.onvif              ERROR   : Onvif is not setup for carport
2024-09-29 18:25:57.313523003  [2024-09-29 18:25:57] frigate.ptz.onvif              ERROR   : Onvif is not setup for backyard
2024-09-29 18:25:57.314256381  [2024-09-29 18:25:57] frigate.ptz.onvif              ERROR   : Onvif is not setup for backporch
2024-09-29 18:25:57.315473817  [2024-09-29 18:25:57] frigate.ptz.onvif              ERROR   : Onvif is not setup for backyard_north
```

### Relevant go2rtc log output

```shell
2024-09-29 18:23:19.562370507  [INFO] Preparing new go2rtc config...
2024-09-29 18:23:20.024962574  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-09-29 18:23:20.074779391  [INFO] Starting go2rtc...
2024-09-29 18:23:20.235168739  18:23:20.235 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-09-29 18:23:20.235172219  18:23:20.235 INF config path=/dev/shm/go2rtc.yaml
2024-09-29 18:23:20.235824071  18:23:20.235 INF [api] listen addr=:1984
2024-09-29 18:23:20.235888847  18:23:20.235 INF [rtsp] listen addr=:8554
2024-09-29 18:23:20.236286356  18:23:20.236 INF [webrtc] listen addr=:8555
2024-09-29 18:23:29.558351915  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
..
```

### Frigate stats

```json
..
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua IPC-T5442TM-AS

### Screenshots of the Frigate UI's System metrics pages

<img width="1388" alt="Screenshot 2024-09-29 at 6 47 52 PM" src="https://github.com/user-attachments/assets/676f8590-a6e6-45f9-9676-fffb6ad2cb62">
<img width="1430" alt="Screenshot 2024-09-29 at 6 49 17 PM" src="https://github.com/user-attachments/assets/d8b27caf-9ae2-4dcf-80d5-104a2c33abc4">
