### DISCUSSION TITLE
Detection is inconsistent when loop testing

### DISCUSSION THREAD

**Discussion by forkineye** [blakeblackshear/frigate#1407] [Ask A Question]
I've been fine tuning the detection for one of my cameras and am running into issues with repeatability / consistency.  I took a clip from my 24/7 recording that didn't detect last night (same stream is used for detection), and set it up as a test camera.  The mask, zones, motion, etc... are all setup just as they are on the physical camera (listed below).  The issue that I'm having is that this 60sec clip is not consistently being detected.  Sometimes, it'll detect every minute or two, sometimes it will take 5-15min.  The stream from the camera (Reolink RLC-810A) is 20fps rtmp ( it's the ext sub-stream that can't be configured) and configured for 10fps in Frigate.  I've tested with it configured for 20fps as well and still experience issues.  Example of what I'm seeing and setup / camera / stats data below.  Any ideas as to why this is happening? I'm thinking it may have something to do with how Frigate chunks everything up into 60sec clips? Does this happen for detection as well?

### Setup:
Dell T420 - 2x E5-2450L - 64GB RAM
Proxmox 7.0
Ubuntu 20.04 VM (32GB RAM, 8 CPUs)
Frigate 0.8.4-5043040 in Docker
Coral Mini PCIe

### Camera config:
```yaml
cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/ndtest1.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    width: 896
    height: 512
    fps: 10
    motion:
      contour_area: 40
      frame_height: 180
      mask:
        - 896,0,896,92,147,88,141,201,0,234,0,81,0,0
        - 896,270,896,209,850,191,824,220,849,266
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.4
          max_area: 8000
        car:
          mask:
            - 0,512,896,512,896,0,738,0,734,77,782,137,764,181,654,221,348,222,247,218,178,186,164,147,254,80,251,0,0,0
    zones:
      front_yard:
        coordinates: 896,512,896,375,720,237,493,254,297,252,232,245,150,230,0,284,0,512
        filters:
          person:
            threshold: 0.5
      front_alarm:
        coordinates: 896,342,753,269,195,282,0,512,896,512
        filters:
          person:
            threshold: 0.5
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 1
```

### Stats:
```json
{
  "detection_fps": 7.0, 
  "detectors": {
    "coral_pci": {
      "detection_start": 0.0, 
      "inference_speed": 9.86, 
      "pid": 43
    }
  }, 
  "driveway": {
    "camera_fps": 5.1, 
    "capture_pid": 58, 
    "detection_fps": 0.0, 
    "pid": 50, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "front_porch": {
    "camera_fps": 5.1, 
    "capture_pid": 62, 
    "detection_fps": 0.0, 
    "pid": 51, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "living_room": {
    "camera_fps": 5.1, 
    "capture_pid": 68, 
    "detection_fps": 0.0, 
    "pid": 53, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 125.7, 
        "mount_type": "tmpfs", 
        "total": 134.2, 
        "used": 8.5
      }, 
      "/media/frigate/clips": {
        "free": 1057442.4, 
        "mount_type": "zfs", 
        "total": 1930527.2, 
        "used": 873084.9
      }, 
      "/media/frigate/recordings": {
        "free": 1057442.4, 
        "mount_type": "zfs", 
        "total": 1930527.2, 
        "used": 873084.9
      }, 
      "/tmp/cache": {
        "free": 693.4, 
        "mount_type": "tmpfs", 
        "total": 1000.0, 
        "used": 306.6
      }
    }, 
    "uptime": 2970, 
    "version": "0.8.4-5043040"
  }, 
  "street": {
    "camera_fps": 5.1, 
    "capture_pid": 55, 
    "detection_fps": 0.0, 
    "pid": 48, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "test": {
    "camera_fps": 10.0, 
    "capture_pid": 54, 
    "detection_fps": 7.0, 
    "pid": 46, 
    "process_fps": 10.0, 
    "skipped_fps": 0.0
  }
}
```

![firgate](https://user-images.githubusercontent.com/4047923/126341805-ad8ccafb-e411-4eca-af48-33ba14971e60.JPG)
