### DISCUSSION TITLE
request help to find the right installation configuration according to my material

### DISCUSSION THREAD

**Discussion by orrionis** [blakeblackshear/frigate#14080] [Ask A Question]
Hello All

For long time i'm agent DVR but now i want to try Frigate but i'm lost for configure the install

for material: 
Intel(R) Core(TM) i5-3470 CPU @ 3.20GH
Ram 16GO
GPU Nvidia Quatro P400 gb

first question do i use the cpu or the gpu, ?
Knowing that I use the GPU to run Codeprojetc.

and i want use code project for detector and facial.
now there are just 2 camera but for future maybe 5 or 6
the first camera is doorbell and tjhis is my most important . facial for it 's not an option .

Now i want just configure the right way for install facial is for later whan the system work fine.

This my docker compose

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation : Example for 8 cameras detecting at 1280x720, including logs
                      # python -c 'print("{:.2f}MB".format(((1280 * 720 * 1.5 * 9 + 270480) / 1048576) * 8 + 30))'
                      #126.99MB
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1 # number of GPUs
#              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config/:/config/
      - /docker/frigate/data:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"
    environment:
      FRIGATE_RTSP_PASSWORD: "????"
```

and this is mi conf
````
mqtt:
  host: 172.16.128.127
  port: 1883
  user: mqtt
  password: 
  stats_interval: 60

detectors:
  aiserver:
    url: http://172.16.128.41:32168
    timeout: 30
  # # deepstack:
    # # api_url: http://172.16.128.41:32168/v1/vision/detection
    # # type: deepstack
    # # api_timeout: 0.1 # seconds

birdseye:
  enabled: false
snapshots:
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 3
    # Optional: Per object retention days
    objects:
      person: 3

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    #mode: active_objects
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 3
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 3

cameras:
  sonette:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sonette
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
#      width: 1280 #width of the frame for the input with the detect role
#      height: 720 #height of the frame for the input with the detect role (default: shown below)
      fps: 5 #Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      enabled: true

    objects:
      track:
        - person
#        - dog
#        - cat
#        - bird
#        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8

  test:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/test
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
#      width: 1280 #width of the frame for the input with the detect role
#      height: 720 #height of the frame for the input with the detect role (default: shown below)
      fps: 5 #Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      enabled: true

    objects:
      track:
        - person
#        - dog
#        - cat
#        - bird
#        - mouse
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8


go2rtc:
  streams:
    sonette:
      - rtsp://192.168.42.124:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
    test:
      - rtsp://172.16.128.28:554/ch0.h264
  webrtc:
    listen: :8555     # address of your local server and port (TCP/UDP)
    candidates:
      - 172.16.128.41:8555    # if you have static public IP-address (1.2.3.4 To replace by External Public IP)
      - stun:8555   # if you have dynamic public IP-address
version: 0.14
```

Thanks for your help
