### DISCUSSION TITLE
[Support]: `reviews` mqtt endpoint not correct - zones appear in 'before' at the same time as 'after' blocks

### DISCUSSION THREAD

**Discussion by dlgoodr** [blakeblackshear/frigate#14081] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

<details><summary>mqtt payload from `reviews` event</summary>

```json
[
    {
        "time_ms": 1727739975159,
        "time": "2024-09-30_18:46:15",
        "message": {
            "type": "new",
            "before": {
                "id": "1727739974.849716-32hrsg",
                "camera": "front_door",
                "start_time": 1727739974.849716,
                "end_time": null,
                "severity": "alert",
                "thumb_path": "/media/frigate/clips/review/thumb-front_door-1727739974.849716-32hrsg.webp",
                "data": {
                    "detections": [
                        "1727739972.64988-amhvje"
                    ],
                    "objects": [
                        "person"
                    ],
                    "sub_labels": [],
                    "zones": [
                        "driveway"
                    ],
                    "audio": []
                }
            },
            "after": {
                "id": "1727739974.849716-32hrsg",
                "camera": "front_door",
                "start_time": 1727739974.849716,
                "end_time": null,
                "severity": "alert",
                "thumb_path": "/media/frigate/clips/review/thumb-front_door-1727739974.849716-32hrsg.webp",
                "data": {
                    "detections": [
                        "1727739972.64988-amhvje"
                    ],
                    "objects": [
                        "person"
                    ],
                    "sub_labels": [],
                    "zones": [
                        "driveway"
                    ],
                    "audio": []
                }
            }
        }
    },
    {
        "time_ms": 1727740009825,
        "time": "2024-09-30_18:46:49",
        "message": {
            "type": "end",
            "before": {
                "id": "1727739974.849716-32hrsg",
                "camera": "front_door",
                "start_time": 1727739974.849716,
                "end_time": null,
                "severity": "alert",
                "thumb_path": "/media/frigate/clips/review/thumb-front_door-1727739974.849716-32hrsg.webp",
                "data": {
                    "detections": [
                        "1727739972.64988-amhvje"
                    ],
                    "objects": [
                        "person"
                    ],
                    "sub_labels": [],
                    "zones": [
                        "driveway",
                        "entrance"
                    ],
                    "audio": []
                }
            },
            "after": {
                "id": "1727739974.849716-32hrsg",
                "camera": "front_door",
                "start_time": 1727739974.849716,
                "end_time": 1727739979.442071,
                "severity": "alert",
                "thumb_path": "/media/frigate/clips/review/thumb-front_door-1727739974.849716-32hrsg.webp",
                "data": {
                    "detections": [
                        "1727739972.64988-amhvje"
                    ],
                    "objects": [
                        "person"
                    ],
                    "sub_labels": [],
                    "zones": [
                        "driveway",
                        "entrance"
                    ],
                    "audio": []
                }
            }
        }
    }
]

```

</details>
you can see in the first message that the `entrance` zone is not detected.

you can see in the second message that the `entrance` zone is detected, but in both the `before` and `after` blocks. I would expect it not to be in the `before` block of the second message because it was not in the first message.

It is making reliable alerting in HomeAssistant difficult.

### Steps to reproduce

1. Be unlucky
2. log all mqtt messages
3. wonder how someone got to your door without an alert

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

n/a, mqtt

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtthost.local
  user: frigate
  password: xxx_notyours
objects:
  track:
    - person

go2rtc:
  streams:
    front_door:
      - rtsp://admin:asdfadsf@doorbell.local/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:front_door#audio=opus
      - ffmpeg:front_door#video=mjpeg

ffmpeg:
  hwaccel_args: preset-vaapi

timestamp_style:
  position: br
  effect: solid

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  retain:
    default: 60

detectors:
  cpu1:
    type: cpu
    num_threads: 3

birdseye:
  enabled: true
  mode: motion
  restream: true

cameras:
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      enabled: true
      width: 720
      height: 576
    motion:
      mask:
        - 1,0,1,0.101,0.689,0.099,0.688,0
        - 0.194,0.481,0.2,0.528,0.193,0.586,0.163,0.602,0.146,0.58,0.154,0.446,0.176,0.448
        - 0.058,0.474,0.039,0.508,0.052,0.563,0.076,0.569,0.078,0.462
    zones:
      entrance:
        coordinates: 0.2,0,0.158,0.448,0.46,0.465,0.46,0.62,0.147,0.58,0.197,0,0,0,0,1,1,1,1,0
        inertia: 3
        loitering_time: 0
      driveway:
        coordinates: 0.399,0.606,0.268,0.587,0.183,0.575,0.155,0.582,0.158,0.652
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
      filters:
        person:
          threshold: .75
        car:
          threshold: .75
          mask:
            - 230,297,152,315,128,304,206,290
    review:
      alerts:
        required_zones:
          - driveway
          - entrance
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "100mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config:/config
      - /docker/frigate/media:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" # go2rtc something
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
      LIBVA_DRIVER_NAME: i965  
      PLUS_API_KEY: xxx
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

amcrest 

### Screenshots of the Frigate UI's System metrics pages

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/ee9771d8-1e87-4d05-99ce-0fa45e0be7ee">
