### DISCUSSION TITLE
[Support]: Record Only Events without global retain not working as expected

### DISCUSSION THREAD

**Discussion by gvillo** [blakeblackshear/frigate#14089] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Hi! I just only need to retain events (active_objects) so my config was to accomplish that (following the docs https://docs.frigate.video/configuration/record#minimum-events-only), but it's not storing any video (just snapshots). On the other side if I set record.retain.days=2 works ok, I think the bug is related when record.retain.days=0 is not storing event videos for some weird reason.

I have played a little bit and if I set record.retain works, I don't need that config but I just set it to motion or active_objects (instead of mode=all) as a workaround for now

### Steps to reproduce

1. Set record.retain.days=0 and set record events to store active_object for a week or so
2. Wait some time to collect/detect and record a few events, also take note of the storage used for recordings (it doesn't grow)
3. Check if recorded events are working and if storage has increased

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Brave v1.70.119

### Frigate config file

```yaml
snapshots:
  enabled: true
  retain:
    default: 90 # days

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 90 # days
      mode: active_objects
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/frigate/config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984/tcp" # go2rtc over tcp
      - "1984:1984/udp" # go2rtc over udp
    environment:
      - PLUS_API_KEY=XXXXXXXXXX
      - TZ=America/Argentina/Buenos_Aires
    cap_add:
      - CAP_PERFMON
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4096M
        reservations:
          cpus: '2.00'
          memory: 2048M
```

### Relevant Frigate log output

```shell
I have no issues in Frigate except for
Tag: frigate.ptz.onvif
Message: Onvif is not setup for Frente

But that's because I am using beta frigate card in Home Assistant, it's not related to this
```

### Relevant go2rtc log output

```shell
I have no issues at all in go2rtc
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink cameras (6 cameras)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/ee192ce9-f712-44da-a233-346858807669)

**Comment by hawkeye217** [comment]
From the docs link you posted:  
> If you only want to retain video that occurs during an event, this config will discard video unless an event is ongoing.

When an event ends, the video for that event is removed. This is expected behavior.

Are you saying that the recording never even begins?

**Reply by gvillo** [reply]
the event appears in frigate correctly, but the video is not there, it never loads.

**Reply by hawkeye217** [reply]
With `days: 0`, the footage will only be retained while the event is ongoing. When the event ends, the video is immediately discarded.

**Reply by gvillo** [reply]
ohh got it, so it's a feature not a bug. So if I just set `record.retain.days: 1`, the event will be retained for 90 days (based on my events config)? (this is kinda confusing btw, but I can live with it)

**Reply by NickM-27** [reply]
to be clear if you click on the review item then the recording should be there for the review item in most cases, just not anything before or after. We can't really tell exactly what is going on here without your full config

**Reply by hawkeye217** [reply]
> ohh got it, so it's a feature not a bug. So if I just set `record.retain.days: 1`, the event will be retained for 90 days? (this is kinda confusing btw, but I can live with it)

The configuration options have been updated in the upcoming version of Frigate to be clearer. However, as @NickM-27 said, we need to see your full config as there are other factors that are likely contributing to this.

**Reply by gvillo** [reply]
posted full frigate config on the other @hawkeye217 answer! Thank you guys!

**Reply by NickM-27** [reply]
when you click on a review item and recordings don't load, are you clicking on a detection or alert?

**Reply by gvillo** [reply]
clicking on `detection`, I didn't test it out clicking on an alert, but I think the behavior will be the same.
I think @hawkeye217 hit on target with this comment https://github.com/blakeblackshear/frigate/discussions/14089#discussioncomment-10809288 (I am a spanish speaker and I didn't read that statement carefully, sorry about that).

Anyways I still believe that config is kinda confusing, the `record.events` is a different config than `record.retain` (`events` is not inside of `retain`, it's a sibiling)  and it shouldn't be affected by that setting IMO.

**Reply by NickM-27** [reply, marked as answer]
> clicking on detection, I didn't test it out clicking on an alert, but I think the behavior will be the same.

no, it would not be the same, and I think you are misunderstanding what is going on here. The problem here is that you have required_zones set so `event` is only applied to alerts and detections are not recorded at all unless you have continuous recording enabled. This is confusing, but it was done this way to keep the config consistent with the previous version of Frigate. The next version of frigate removes `events` and has two separate configs for how long to record alerts and detections

**Reply by gvillo** [reply]
confirming that this config works ok with detections now (this works for **frigate v0.14**, this will change in the next version, I'm editing this for the records!).

```yaml
record:
  enabled: true
  retain:
    days: 1
    mode: active_objects
  events:
    retain:
      default: 90 # days
      mode: active_objects
```

**Reply by gvillo** [reply]
neat! awesome, thanks for taking time and explaining everything with so many details! I'll wait for the new frigate version to update the config :)

**Reply by hawkeye217** [reply]
We agree. We didn't want to have too many breaking changes for 0.14, and this would have been a big one for most users. So we decided to push it off to 0.15.

**Comment by hawkeye217** [comment]
Also, what is your full frigate config?

**Reply by gvillo** [reply]
sure thing, I was removing all the sensitive data of it

```yaml
mqtt:
  enabled: true
  host: XXXX
  user: XXXX
  password: XXXXXX

birdseye:
  enabled: false

ui:
  timezone: America/Argentina/Buenos_Aires

detectors:
  coral:
    type: edgetpu
    device: pci # or usb

snapshots:
  enabled: true
  retain:
    default: 90 # days

record:
  enabled: true
  retain:
    days: 1
    mode: active_objects
  events:
    retain:
      default: 90 # days
      mode: active_objects

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

objects:
  # https://github.com/blakeblackshear/frigate/blob/dev/labelmap.txt
  track:
    - person
    - umbrella
    - car
    - motorcycle
    - bicycle
    - cat
    - dog
  filters:
    umbrella:
      min_score: 0.65
      threshold: 0.77
    person:
      min_score: 0.65
      threshold: 0.77

detect:
  width: 1280
  height: 720
  fps: 5

motion:
  threshold: 66

logger:
  default: info

cameras:
  Frente:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara.frente
          roles:
            - detect
            - record
            - audio
    live:
      stream_name: camara.frente_720p
    motion:
      contour_area: 10
      mask: 0,0.294,0.14,0.188,0.279,0.123,0.458,0.078,0.635,0.06,1,0.117,1,0,0,0
    audio:
      enabled: true
      listen:
        - car_alarm
        - fire_alarm
        - alarm
        - siren
        - yell

    zones:
      frente_casa:
        coordinates: 0,0.74,0,1,1,1,1,0.88,0.711,0.936,0.291,0.916
        objects: person
        inertia: 3
        loitering_time: 0
      frente_vereda_casa:
        coordinates: 584,386,1158,387,1194,512,645,530,74,471,74,372
        objects:
          - person
          - umbrella
    review:
      alerts:
        required_zones: frente_casa
  Calle:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara.calle_wide
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    live:
      stream_name: camara.calle_wide_720p
    motion:
      threshold: 85
      contour_area: 22
      mask:
        - 0,118,0,47,0,0,0,0,381,0,383,35,186,39
      #- 688,0,521,0,363,0,386,31,588,41,659,62
    audio:
      enabled: true
      listen:
        - car_alarm
        - fire_alarm
        - alarm
        - siren
        - yell

    zones:
      calle_porch_y_trotera:
        coordinates: 0.78,0.465,0.836,1,1,1,1,0.264,0.865,0.196,0.725,0.175
        objects: person
        inertia: 3
        loitering_time: 0
      calle_vereda_y_calle:
        coordinates: 0,48,0,720,845,720,864,518,867,267,857,49,548,39,386,46
      calle_vereda_casa:
        coordinates: 0.195,1,0.516,0.317,0.673,0.328,0.655,1
        objects:
          - person
          - umbrella
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: calle_porch_y_trotera
  Patio:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara.patio
          roles:
            - detect
            - record
    live:
      stream_name: camara.patio_720p
    objects:
      track:
        - person

    motion:
      mask:
        - 379,0,381,37,0,37,0,0
        - 734,257,950,267,1151,279,1155,217,978,197,732,187
        - 0,720,123,720,111,27,0,24
    zones:
      patio_pasto:
        coordinates: 
          0,0.382,0.328,0.7,0.558,0.706,0.849,0.635,0.885,0.103,1,0.099,1,0.485,1,0.781,1,1,0,1,0,0.685
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: patio_pasto
  Patio2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara.patio2
          roles:
            - detect
            - record
        #- audio
    live:
      stream_name: camara.patio2_720p
    motion:
      threshold: 80
      mask:
        - 937,0,945,207,686,198,757,201,639,193,527,135,522,118,493,106,495,0
        - 385,0,382,45,0,43,0,0
    audio:
      enabled: false
      listen:
        - car_alarm
        - fire_alarm
        - alarm
        - siren

    zones:
      patio2_casa:
        coordinates: 
          0,1,0,0.287,0.231,0.137,0.315,0.104,0.368,0.06,0.377,0.216,0.476,0.222,0.484,0.306,0.788,0.342,0.803,0.04,1,0,1,1
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person

    review:
      alerts:
        required_zones: patio2_casa
  Pasillo:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara.pasillo
          roles:
            - detect
            - record
    live:
      stream_name: camara.pasillo_720p
    motion:
      mask:
        - 0,720,424,720,765,133,758,0,0,0
        - 1280,0,1280,31,1024,31,1025,0
    zones:
      pasillo_lado_de_casa:
        coordinates: 1280,54,1280,720,424,720,510,622,614,489,696,362,786,243,823,161,819,77
    objects:
      track:
        - person

    review:
      alerts:
        required_zones: pasillo_lado_de_casa
  Garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camara.garage
          roles:
            - detect
            - record
            - audio
    live:
      stream_name: camara.garage_720p
    objects:
      track:
        - person

    audio:
      enabled: true
      listen:
        - fire_alarm

    motion:
      mask:
        - 388,0,387,42,0,39,0,0
go2rtc:
  api:
    listen: :1984      # default ":1984", HTTP API port ("" - disabled)
    origin: '*'
    username: tttt    # default "", Basic auth for WebUI
    password: XXXXXXX     # default "", Basic auth for WebUI

  rtsp:
    listen: :8554      # RTSP Server TCP port, default - 8554
    username: yyyy    # optional, default - disabled
    password: EEEEEEEE     # optional, default - disabled

  # Codecs: https://github.com/AlexxIT/go2rtc/#codecs-madness
  streams:
    # Source RTSP
    camara.frente:         #2160p >> 6mbps >> h265/AAC (16:9) >> 25 fps >> needs MSE instead of RTC
      - ffmpeg:rtsp://xxx@wwww@10.0.0.15/h265Preview_01_main#input=rtsp-reolink-low-latency
    camara.frente.sub:     #512p  >> 1mbps >> h264/AAC (16:9) >> 25 fps
      #- ffmpeg:http://10.0.0.15/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
      - ffmpeg:rtsp://xxx@wwww@10.0.0.15/h264Preview_01_sub#input=rtsp-reolink-low-latency   # 360p 512kbps 15fps

    camara.calle_wide:     #2160p >> 6mbps >> h265/AAC (16:9) >> 25 fps >> needs MSE instead of RTC
      - ffmpeg:rtsp://xxx@wwww@10.0.0.14/h265Preview_01_main#input=rtsp-reolink-low-latency
    camara.calle_wide.sub: #512p  >> 712kbps >> h264/AAC (16:9) >> 25 fps
      #- ffmpeg:http://10.0.0.14/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
      - ffmpeg:rtsp://xxx@wwww@10.0.0.14/h264Preview_01_sub#input=rtsp-reolink-low-latency
    camara.calle_tele:     #2160p >> 6mbps >> h265/AAC (16:9) >> 25 fps >> needs MSE instead of RTC
      - ffmpeg:rtsp://xxx@wwww@10.0.0.14/h265Preview_02_main#input=rtsp-reolink-low-latency
    camara.calle_tele.sub: #512p  >> 1mbps >> h264/AAC (16:9) >> 25 fps
      - ffmpeg:rtsp://xxx@wwww@10.0.0.14/h264Preview_02_sub#input=rtsp-reolink-low-latency

    camara.patio:     #1440p >> 2mbps >> h264/AAC (16:9) >> 30 fps
      - ffmpeg:http://10.0.0.13/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.13/h264Preview_01_main#input=rtsp-reolink
    camara.patio.sub: #896x672  >> 512kbps >> h264/AAC (4:3) >> 12.5 fps
      - ffmpeg:http://10.0.0.13/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.13/h264Preview_01_sub#input=rtsp-reolink  #480p  >> 256kbps >> h264/AAC (4:3) >> 15 fps
    camara.patio2:     #1440p >> 3mbps >> h264/AAC (16:9) >> 30 fps
      - ffmpeg:http://10.0.0.18/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.18/h264Preview_01_main#input=rtsp-reolink
    camara.patio2.sub: #896x672  >> 512kbps >> h264/AAC (4:3) >> 12.5 fps
      - ffmpeg:http://10.0.0.18/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.18/h264Preview_01_sub#input=rtsp-reolink  #480p  >> 256kbps >> h264/AAC (4:3) >> 15 fps

    camara.pasillo:     #1440p >> 3mbps >> h264/AAC (16:9) >> 30 fps
      - ffmpeg:rtsp://xxx@wwww@10.0.0.11/h265Preview_01_main#input=rtsp-reolink-low-latency
    camara.pasillo.sub: #896x672  >> 512kbps >> h264/AAC (4:3) >> 12.5 fps
      - ffmpeg:http://10.0.0.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.11/h264Preview_01_sub#input=rtsp-reolink  #480p  >> 256kbps >> h264/AAC (4:3) >> 15 fps

    camara.garage:     #1440p >> 3mbps >> h264/AAC (16:9) >> 20 fps
      - ffmpeg:http://10.0.0.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.12/h264Preview_01_main#input=rtsp-reolink
    camara.garage.sub: #896x672  >> 1500kbps >> h264/AAC (4:3) >> 20 fps
      - ffmpeg:http://10.0.0.12/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=rrrrrr$#video=copy#audio=copy#audio=opus#input=http-reolink
    #- ffmpeg:rtsp://xxx@wwww@10.0.0.12/h264Preview_01_sub#input=rtsp-reolink  #480p  >> 256kbps >> h264/AAC (4:3) >> 15 fps

    # bitrate cheatsheet: https://www.hikvision.com/content/dam/hikvision/ca/faq-document/H.2645-&-H.2645-Recommended-Bit-Rate-at-General-Resolutions.pdf
    # renditions: 360p, 480p, 720p and 1080p
    camara.frente_360p: ffmpeg:camara.frente.sub#video=h264#hardware#audio=opus#audio=aac#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 1M -g 50
    camara.frente_480p: ffmpeg:camara.frente.sub#video=copy#audio=copy#audio=opus
    camara.frente_720p: ffmpeg:camara.frente#video=h264#hardware#audio=opus#audio=aac#height=720#raw=-b:v
      1M -maxrate 2M -bufsize 8M -g 50
    camara.frente_1080p: ffmpeg:camara.frente#video=h264#hardware#audio=opus#audio=aac#height=1080#raw=-b:v
      2M -maxrate 3M -bufsize 8M -g 50

    # camara.calle_wide_360p: ffmpeg:camara.calle_wide#video=h264#audio=opus#height=360#raw=-b:v
    #   512K -maxrate 768K -bufsize 6M -g 50
    # camara.calle_wide_480p: ffmpeg:camara.calle_wide#video=h264#audio=opus#height=720#raw=-b:v
    #   756K -maxrate 1M -bufsize 6M -g 50
    camara.calle_wide_360p: ffmpeg:camara.calle_wide.sub#video=h264#hardware#audio=opus#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 3M -g 40
    camara.calle_wide_480p: ffmpeg:camara.calle_wide.sub#video=h264#hardware#audio=opus#audio=aac
    camara.calle_wide_720p: ffmpeg:camara.calle_wide.sub#video=h264#hardware#audio=opus#audio=aac
    # camara.calle_wide_720p: ffmpeg:camara.calle_wide#video=h264#audio=opus#height=720#raw=-b:v
    #   1M -maxrate 2M -bufsize 6M -g 50
    camara.calle_wide_1080p: ffmpeg:camara.calle_wide#video=h264#audio=opus#audio=aac#height=1080#raw=-b:v
      2M -maxrate 3M -bufsize 6M -g 50
    camara.calle_tele_360p: ffmpeg:camara.calle_tele.sub#video=h264#audio=opus#audio=aac#hardware#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 2M -g 50
    camara.calle_tele_480p: ffmpeg:camara.calle_tele.sub#video=h264#hardware#audio=opus#audio=aac
    camara.calle_tele_720p: ffmpeg:camara.calle_tele#video=h264#hardware#audio=opus#audio=aac#height=720#raw=-b:v
      1M -maxrate 2M -bufsize 4M -g 50
    camara.calle_tele_1080p: ffmpeg:camara.calle_tele#video=h264#hardware#audio=opus#audio=aac#height=1080#raw=-b:v
      2M -maxrate 4M -bufsize 4M -g 50

    camara.patio_360p: ffmpeg:camara.patio#video=h264#hardware#audio=opus#audio=aac#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 2M -g 60
    camara.patio_480p: ffmpeg:camara.patio#video=h264#hardware#audio=opus#audio=aac#height=480#raw=-b:v
      768K -maxrate 1M -bufsize 2M -g 60
    camara.patio_720p: ffmpeg:camara.patio#video=h264#hardware#audio=opus#audio=aac#height=720#raw=-b:v
      2M -maxrate 2M -bufsize 2M -g 60
    camara.patio_1080p: ffmpeg:camara.patio#video=h264#hardware#audio=opus#audio=aac#height=1080#raw=-b:v
      3M -maxrate 3M -bufsize 2M -g 60

    camara.patio2_360p: ffmpeg:camara.patio2#video=h264#hardware#audio=opus#audio=aac#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 3M -g 60
    camara.patio2_480p: ffmpeg:camara.patio2#video=h264#hardware#audio=opus#audio=aac#height=480#raw=-b:v
      768K -maxrate 1M -bufsize 3M -g 60
    camara.patio2_720p: ffmpeg:camara.patio2#video=h264#hardware#audio=opus#audio=aac#height=720#raw=-b:v
      1M -maxrate 2M -bufsize 3M -g 60
    camara.patio2_1080p: ffmpeg:camara.patio2#video=h264#hardware#audio=opus#audio=aac#height=1080#raw=-b:v
      2M -maxrate 3M -bufsize 3M -g 60

    camara.pasillo_360p: ffmpeg:camara.pasillo#video=h264#hardware#audio=opus#audio=aac#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 3M -g 60
    camara.pasillo_480p: ffmpeg:camara.pasillo#video=h264#hardware#audio=opus#audio=aac#height=480#raw=-b:v
      768K -maxrate 1M -bufsize 3M -g 60
    camara.pasillo_720p: ffmpeg:camara.pasillo#video=h264#hardware#audio=opus##audio=aac#height=720#raw=-b:v
      1M -maxrate 2M -bufsize 3M -g 60
    camara.pasillo_1080p: ffmpeg:camara.pasillo#video=h264#hardware#audio=opus#audio=aac#height=1080#raw=-b:v
      2M -maxrate 3M -bufsize 3M -g 60

    camara.garage_360p: ffmpeg:camara.garage#video=h264#hardware#audio=opus#audio=aac#height=360#raw=-b:v
      512K -maxrate 768K -bufsize 3M -g 40
    camara.garage_480p: ffmpeg:camara.garage#video=h264#hardware#audio=opus#audio=aac#height=480#raw=-b:v
      768K -maxrate 1M -bufsize 3M -g 40
    camara.garage_720p: ffmpeg:camara.garage#video=h264#hardware#audio=opus#audio=aac#height=720#raw=-b:v
      1M -maxrate 2M -bufsize 3M -g 40
    camara.garage_1080p: ffmpeg:camara.garage#video=h264#hardware#audio=opus#audio=aac#height=1080#raw=-b:v
      2M -maxrate 3M -bufsize 3M -g 40

    # birdseye
    birdseye: rtsp://localhost:554/birdseye
  ffmpeg:
    # inputs
    http-reolink: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags
      low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout
      5000000 -i {input}

    rtsp-generic: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -timeout
      5000000 -use_wallclock_as_timestamps 1 -user_agent go2rtc/ffmpeg -rtsp_flags
      prefer_tcp -i {input}
    rtsp-generic-low-latency: -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt
      -flags low_delay -timeout 5000000 -use_wallclock_as_timestamps 1 -user_agent
      go2rtc/ffmpeg -rtsp_flags prefer_tcp -i {input}

    rtsp-reolink-low-latency: -fflags +genpts+discardcorrupt -flags low_delay -timeout
      5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i {input}
    rtsp-reolink: -fflags +genpts+discardcorrupt -timeout 5000000 -user_agent go2rtc/ffmpeg
      -rtsp_flags prefer_tcp -i {input}

    # codecs
    h264: -c:v libx264    -g 30       -profile:v high -level:v 4.1 -preset veryfast
      -tune zerolatency -pix_fmt yuv420p -movflags +faststart
    h264/vaapi: -c:v h264_vaapi -g 30 -bf 0 -profile:v high -level:v 4.1 -preset faster
      -tune zerolatency -sei:v 0         -movflags +faststart

    h265: -c:v libx265    -g 30       -profile:v main -level:v 5.1 -preset veryfast
      -tune zerolatency          -movflags +faststart # avoid using h265 software, it uses a lot of CPU
    h265/vaapi: -c:v hevc_vaapi -g 50 -bf 0 -profile:v main -level:v 5.1 -preset faster
      -tune zerolatency -sei:v 0 -movflags +faststart

  log:
    api: info
    exec: info
    format: text
    level: info
    ngrok: info
    rtsp: info
    streams: info
    webrtc: info

  webrtc:
    candidates:
      - 10.0.0.88:8555
      - stun:8555
    listen: :8555
version: 0.14
```
