### DISCUSSION TITLE
message: API error whilst retrieving events for cameras for Frigate instance frigate

### DISCUSSION THREAD

**Discussion by theDontKnowGuy** [blakeblackshear/frigate#14099] [Ask A Question]
Getting these errors all the time, in random occasions.
Seeing it in Home Assistant.
Proxmox CLX.
Version 14.1
 
config: 
```
version: 0.14

mqtt:
  host: 192.168.22.252
  port: 1883
  user: mqttuser
  password: xxxxx
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

# ffmpeg:
#  hwaccel_args: preset-vaapi


cameras:
  Front_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.22.51/ucast/1
          roles:
            - detect
    detect:
      enabled: true
      width: 1080
      height: 960
      fps: 2
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7
    zones: {}
    review: {}
  Clinic_Entrance:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.22.51/ucast/2
          roles:
            - detect
            - record
    detect:
      width: 1080
      height: 960
      fps: 1
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7

  Back_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.22.51/ucast/3
          roles:
            - detect
            - record
    detect:
      width: 1080
      height: 960
      fps: 1
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7

  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.22.51/ucast/4
          roles:
            - detect
            - record
    detect:
      width: 1080
      height: 960
      fps: 1
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7
  PeepHole:
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:xxx@192.168.22.52/user=admin&password=xxxx&channel=1&stream=0.sdp?real_stream--rtp-caching=100?video=copy&audio=aac
          roles:
            - detect
            - record
    detect:
      width: 1080
      height: 960
      fps: 1
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7

  Storage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.22.144/11
        #rtsp://admin:xxxxx@192.168.22.51/ucast/7
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 1
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7


```
