### DISCUSSION TITLE
Frigate showing same clip for every detection

### DISCUSSION THREAD

**Discussion by rsteckler** [blakeblackshear/frigate#14094] [General Support] [answered]
I'm looking at the detections screen here:
![image](https://github.com/user-attachments/assets/25913f59-fae9-4b30-8f3f-48f8309a3dc1)

If I hover over a detection I get the expected clip as a preview.  It matches the still image.  For example, the still image that detected the school bus shows the bus in the preview:
![image](https://github.com/user-attachments/assets/772a2154-261c-4d20-b4f0-5b0f2858f749)

But when I click on ANY of these clips, I get the same video over and over.  The video is from an earlier detection today.  Here I click on the bus video and see the gate open and a car leaving, which was hours before the bus was detected:
![image](https://github.com/user-attachments/assets/91f32af7-0970-4fc7-ade3-064f8ba6ecd9)

Here's the inspect element on the summary clip/image:
```
<div data-start="1727796130.689642" data-segment-start="1727796060" class="review-item relative rounded-lg"><div class="aspect-video overflow-hidden rounded-lg"><div class="relative size-full cursor-pointer"><div class="visible"><img class="size-full select-none transition-opacity opacity-100" draggable="false" src="https://REDACTED/clips/review/thumb-camera_front_gate_driveway-1727796130.689642-7tk5k9.webp" loading="lazy"><div class="rounded-t-l pointer-events-none absolute inset-x-0 top-0 h-[30%] w-full bg-gradient-to-b from-black/60 to-transparent z-10"></div><div class="absolute left-0 top-2 z-40"><div class="flex"><div class="mx-3 pb-1 text-sm text-white" data-state="closed"><div class="rounded-2xl px-2 py-1.5 flex items-start justify-between space-x-1 bg-gradient-to-br bg-green-600 from-green-600 to-green-700 z-10"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 640 512" class="size-3 text-white" height="20" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M544 192h-16L419.22 56.02A64.025 64.025 0 0 0 369.24 32H155.33c-26.17 0-49.7 15.93-59.42 40.23L48 194.26C20.44 201.4 0 226.21 0 256v112c0 8.84 7.16 16 16 16h48c0 53.02 42.98 96 96 96s96-42.98 96-96h128c0 53.02 42.98 96 96 96s96-42.98 96-96h48c8.84 0 16-7.16 16-16v-80c0-53.02-42.98-96-96-96zM160 432c-26.47 0-48-21.53-48-48s21.53-48 48-48 48 21.53 48 48-21.53 48-48 48zm72-240H116.93l38.4-96H232v96zm48 0V96h89.24l76.8 96H280zm200 240c-26.47 0-48-21.53-48-48s21.53-48 48-48 48 21.53 48 48-21.53 48-48 48z"></path></svg></div></div></div></div><div class="rounded-b-l pointer-events-none absolute inset-x-0 bottom-0 h-[20%] w-full bg-gradient-to-t from-black/60 to-transparent z-10"><div class="mx-3 flex h-full items-end justify-between pb-1 text-sm text-white"><span>22m ago</span>Oct 1, 08:22 AM</div></div></div></div></div><div class="review-item-ring pointer-events-none absolute inset-0 z-10 size-full rounded-lg outline outline-[3px] -outline-offset-[2.8px] outline-transparent duration-500"></div></div>

.... and the inner image:

<img class="size-full select-none transition-opacity opacity-100" draggable="false" src="https://frigate.elfuerte.casa/clips/review/thumb-camera_front_gate_driveway-1727796130.689642-7tk5k9.webp" loading="lazy">
```

Here's the inspect element on the video playback:  
```
<video class="size-full rounded-lg bg-black md:rounded-2xl " preload="auto" autoplay="" playsinline="" src="blob:https://frigate.elfuerte.casa/46bc1025-a53d-4fb9-acfa-04ee394d84c4"></video>
```

There's not an obvious link between those two like I was hoping, but still wanted to share in case it's helpful.

I'm on 14.0 and don't want to restart/upgrade in case the current running setup is helpful for debugging.

**Comment by NickM-27** [comment]
when you click on a review item, does it always show the same time on the timeline?

**Reply by rsteckler** [reply]
Yes - When I hover on a preview, it shows the correct time (8:45am for this event):
![image](https://github.com/user-attachments/assets/1f38ece5-aedc-49ce-af26-39ea0c8724eb)

But when I click, the timeline **briefly** shows the correct time (8:45am), then jumps back to 8am (which matches the incorrect video):
![image](https://github.com/user-attachments/assets/d019e6f3-6e6a-4330-8b63-3a1ba78c422d)

**Reply by NickM-27** [reply]
most likely what is happening here is you don't have full res recordings saved for these detections, this can happen depending on your config. The next version of frigate fixes this by refactoring the recording config to account for both alerts and detections

it would be easier to tell for sure by seeing the config

**Reply by rsteckler** [reply]
System has been up and running for a very long time (years) without this issue, so I don't think it's config, but here it is for that cam:
```
  camera_front_gate_driveway:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 960
    ffmpeg:
      output_args:
        detect: -vf 
          hwdownload,v360=fisheye:flat:ih_fov=185:iv_fov=180:h_fov=80:v_fov=80:roll=-10:pitch=-20:yaw=-35:rorder=pyr:w=1280:h=960,format=yuv420p
          -f rawvideo -pix_fmt yuv420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/camera_front_gate
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    audio:
      enabled: true
    detect:
      width: 1280
      height: 960
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 960
      retain:
        default: 365
        objects:
          person: 50
    objects:
      filters:
        car:
          min_score: .5
          threshold: .85
      track:
        - person
        - dog
        - cat
        - car
        - face
        - amazon
        - fedex
        - ups
        - license_plate
    zones:
      front_gate_driveway_notify:
        coordinates: 889,498,1280,724,1280,960,0,960,0,341,566,446
    review:
      alerts:
        required_zones: front_gate_driveway_notify
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
```

I think the system is devolving the longer it stays online.  Now, I don't even see those detections anymore:
![image](https://github.com/user-attachments/assets/b213e9ab-04de-4621-9b4a-1183cdbbfa43)

Note all of the detections previously shown in screenshots between 8am and 9am are now just...totally gone.  It's not a filtering problem.

For the detections that remain, the preview works, but clicking in results in a spinner on the video, which never plays.  I get the folowing in the JS console:
```
Failed to load resource: the server responded with a status of 502 ()Understand this error
BirdseyeLivePlayer-DH4kjljD.js:9 WebSocket connection to 'wss://REDACTED/live/jsmpeg/camera_front_gate_walkway' failed: Received a broken close frame containing a reserved status code.
s.start @ BirdseyeLivePlayer-DH4kjljD.js:9Understand this error
BirdseyeLivePlayer-DH4kjljD.js:9 WebSocket connection to 'wss://REDACTED/live/jsmpeg/camera_front_gate_driveway' failed: Received a broken close frame containing a reserved status code.
s.start @ BirdseyeLivePlayer-DH4kjljD.js:9Understand this error
vod/camera_front_gate_driveway/start/1727798400/end/1727799104/master.m3u8:1 
        
        
       Failed to load resource: the server responded with a status of 502 ()
```

**Reply by NickM-27** [reply]
> System has been up and running for a very long time (years) without this issue, so I don't think it's config, but here it is for that cam:

that is entirely irrelevant considering what I am referring to is new for 0.14. also `detections` as a concept is new in 0.14.

You haven't included your recording config but what I suggested is most likely the case, because you have required zones set for alerts, only alerts are considered events and detections are not having recordings saved for them. and to reiterate what I said before, this will be improved in the next version of frigate

**Reply by rsteckler** [reply]
That all makes me think maybe the system is having issues, but everything looks good here:
![image](https://github.com/user-attachments/assets/5b711068-ba83-4938-b4c2-978009d65bb3)

Seeing this in the logs, which is referencing the camera for which the recordings disappeared.
```
2024-10-01T09:08:14.937009418-07:00 2024-10-01 16:08:14.936830495  [2024-10-01 16:08:14] frigate.api.media              ERROR   : No recordings found for camera_front_gate_driveway 
during the requested time range
2024-10-01T09:08:14.937461183-07:00 2024-10-01 16:08:14.937279524  2024/10/01 16:08:14 [error] 169#169: *690871 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: IP_REDACTED, server: , request: "GET /vod/camera_front_gate_driveway/start/1727798400/end/1727798814/master.m3u8 HTTP/1.1", host: "REDACTED", referrer: "https://REDACTED/review"
2024-10-01T09:08:14.937494023-07:00 2024-10-01 16:08:14.937321033  IP_REDACTED - - [01/Oct/2024:16:08:14 +0000] "GET /vod/camera_front_gate_driveway/start/1727798400/end/1727798814/master.m3u8 HTTP/1.1" 502 559 "https://REDACTED/review" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "192.168.2.1"
```

**Reply by NickM-27** [reply]
I don't see anything indicating the system is having issues, it seems this is working as we would expect for 0.14 depending on your record config

**Reply by rsteckler** [reply]
> You haven't included your recording config but what I suggested is most likely the case, because you have required zones set for alerts, only alerts are considered events and detections are not having recordings saved for them. and to reiterate what I said before, this will be improved in the next version of frigate

Sorry - wasn't sure which part of the config to include.  Here's the recording config:
```
record:
  enabled: true
  events:
    retain:
      mode: active_objects
      default: 10
```

Note that this is the only camera having a problem, so I assumed any issue would be in that camera's specific configuration.
All of the other cameras work great, and this one did yesterday, too.

**Reply by rsteckler** [reply]
> I don't see anything indicating the system is having issues, it seems this is working as we would expect for 0.14 depending on your record config

I wouldn't think that detections showing up, then disappearing would be as-expected in .14 regardless of recording config?

**Reply by NickM-27** [reply]
so for now to fix this you can do

```
record:
  enabled: true
  retain:
    days: 10
    mode: active_objects
  events:
    retain:
      mode: active_objects
      default: 10
```

and the issue will stop occurring. Otherwise you can wait for 0.15 which as I said will update the config and provide more control / stop this from happening

**Reply by rsteckler** [reply]
Sorry for the flurry of notes.  I need to head out to work so will be offline for a few hours.  I'll leave it broken in this state for now in case it's helpful.  Also happy to reboot which I'm sure will solve it, but don't want to do that if this indicates a problem ya'll want to understand better.

**Reply by NickM-27** [reply]
it is expected, the detection gets created, but then it doesn't have any recordings saved for it so then the detection is deleted. This is all because you are using a config that does not actually record objects that entered required zones.

**Reply by NickM-27** [reply]
> Sorry for the flurry of notes. I need to head out to work so will be offline for a few hours. I'll leave it broken in this state for now in case it's helpful. Also happy to reboot which I'm sure will solve it, but don't want to do that if this indicates a problem ya'll want to understand better.

there is no need, this is working as expected currently

**Reply by rsteckler** [reply]
Got it.  Thanks for the patience.  I swear I'm a smart person, but maybe not understanding this.  I added the config you mentioned and if you're not worried, then I'm not worried :)

I'm admittedly confused why I can watch full videos of detections from last week, but as long as it makes sense to you, I'm good.

Thanks for the help!

**Reply by NickM-27** [reply, marked as answer]
> I'm admittedly confused why I can watch full videos of detections from last week, but as long as it makes sense to you, I'm good.

your config is set to only record events, in order to keep consistency with previous recording config, only `alerts` are considered events because you have only defined required_zones for alerts. So the recordings are available for alerts

**Reply by rsteckler** [reply]
I get that.  But I'm watching **detections** from last week.  Not alerts.

Here's an example on the front door (config here):
```
camera_front_door:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/camera_front_door
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    audio:
      enabled: true
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
        - 1300,30,1850,30,1850,100,1300,100
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      front_door_notify:
        coordinates: 0,0,0,1080,1920,1080,1920,0
    objects:
      track:
        - person
        - dog
        - cat
        - face
        - package
        - amazon
        - fedex
        - ups
      filters:
        person:
          min_area: 50000
    review:
      alerts:
        required_zones: front_door_notify
```
That has an alert zone (that's essentially the whole frame)

If I look at Sept 24 alerts, there's **not a** package alert at 11:42am:
![image](https://github.com/user-attachments/assets/156718f5-553b-43b8-9146-692f8566f9f2)

But there is a package **detection** at 11:42am (last one in the list):
![image](https://github.com/user-attachments/assets/6ee0a2ba-3098-4c24-a166-fc233f41eee0)

So that's clearly not an alert, but I can tap it and watch the full video:
![image](https://github.com/user-attachments/assets/a7ea87ad-18c3-4c90-9484-905117e7d01d)

Note that's the matching video (the timestamp is an hour off because of daylight savings time)
