### DISCUSSION TITLE
retentions and the auto disk space freeing

### DISCUSSION THREAD

**Discussion by bobemoe** [blakeblackshear/frigate#14104] [Ask A Question] [answered]
I am trying to get my head round retentions and the auto disk space freeing...

All of my events from >2 days ago have disappeared! I configured it to keep them for 30 days.

I also have motion configured to keep for 3 days.

Turns out the wind has created constant motion and my disk is full so Frigate deletes an hour of (the oldest?) footage.

I guess this means my oldest events get deleted.

I would rather (and kind of, wrongly, expected) it to delete only footage that did not form part of an event. Start by deleting the oldest 24/7 or motion footage and preserve events.

Am i understanding this correctly? Is there any way to prioritise what gets deleted?

I've dropped my retention for motion down from 3 days to 1 day, but I would prefer 3 and when its not windy this leaves plenty of space.

```
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
```
