### DISCUSSION TITLE
[Config Support]:MQTT Not Authorized/use_username_as_clientid

### DISCUSSION THREAD

**Discussion by neoresin** [blakeblackshear/frigate#14105] [Config Support] [answered]
### Describe the problem you are having

Hi all, so I was having some trouble connecting Frigate to MQTT without utilizing the username and password functionality (it's completely unset in my config.yaml, and only 
```
mqtt:
  enabled: true
  host: leviaserver.levianetwork.lan
  port: 1883

```
are set) and I thought I'd share my findings. I have an MQTT server on a remote box that my HomeAssistant instance connects to (which is also on that box, as it happens). I was having the hardest time connecting, getting "frigate.comms.mqtt ERROR: Unable to connect to MQTT server: MQTT Not authorized" in the logs, and as far as I could see, I was getting a: 
```
mqtt New connection from <frigatebox IP>:50791 on port 1883.
mqtt Sending CONNACK to frigate (0, 5)
mqtt Client frigate disconnected, not authorised.
```
I troubleshot it awhile, eventually giving up because the error message didn't make sense since there were no certificates involved nor was username and password set, so I was left not understanding why it wasn't letting me connect. 
Come to find out today when I set 'use_username_as_clientid' to 'false', it was able to connect, though my logs in MQTT are now not as clear as they used to be. Fortunately, none of the MQTT clients actually NEED the username to be set as clientID, but it would be nice if Frigate would be able to utilize this function of MQTT without error. 
Is getting that functionality enabled planned?

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: <mqtt_host>
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  #topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  #client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  #user: frigate
    # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /config/mosquitto_ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /config/levianetwork_frigate_client.crt
  #tls_client_key: /config/levianetwork_frigate_client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:
  amcrestdomecam: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://admin:password@IPADDRESS:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-generic
          roles:
            - record
            - audio
        - path: 
            rtsp://admin:password@IPADDR:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif     # <----- The stream you want to use for detection
          input_args: preset-rtsp-generic
          roles:
            - detect
    record: # <----- Enable recording
      enabled: true
    zones:
      Pre-sit:
        coordinates: 
          0.473,0.62,0.649,0.621,0.649,0.704,0.678,0.726,0.802,0.717,0.819,0.93,0.668,0.952,0.633,0.996,0.365,0.998,0.436,0.971,0.462,0.904,0.467,0.72
        loitering_time: 0
      Sit:
        coordinates: 
          0.417,0.19,0.392,0.271,0.391,0.367,0.418,0.445,0.461,0.61,0.472,0.618,0.648,0.616,0.828,0.61,0.85,0.418,0.796,0.319,0.529,0.226
        loitering_time: 0
    review:
      alerts:
        required_zones: Pre-sit
      detections:
        required_zones: Pre-sit
detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 704
  height: 480
  fps: 5

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2

objects:
  track:
    - person


# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: True)
  clean_copy: false
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  #crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 15
    # Optional: Per object retention days
    #objects:
    #  person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 90

version: 0.14
```

### Relevant Frigate log output

```shell
frigate  | 2024-10-01 18:45:07.352261626  [2024-10-01 18:45:07] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
frigate  | 2024-10-01 18:45:08.565419290  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-10-01 18:45:15.358068661  [2024-10-01 18:45:15] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "165mb" # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1
      - /dev/apex_2:/dev/apex_2
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config:/config
      - /frigate/clips:/media/frigate/clips
      - /frigate/recordings:/media/frigate/recordings
      - /frigate/exports:/media/frigate/exports
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /frigate/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
#    environment:
#      FRIGATE_RTSP_PASSWORD: ""
```

### Object Detector

Coral
