### DISCUSSION TITLE
[HW Accel Support]: Support for Intel Arc GPU?

### DISCUSSION THREAD

**Discussion by memarkham303** [blakeblackshear/frigate#14127] [Hardware Acceleration Support]
### Describe the problem you are having

I got a new Beelink GTi14 today and wanted to try Frigate on it.  This machine has the Intel® Core™ Ultra 9 Processor 185H with Intel Arc Graphics.

I tried the default Intel GPU setting in my docker-compose.yml file with "/dev/dri/renderD128" however, I'm getting an error: ""/dev/dri/renderD128": no such file or directory".

I'm not sure how to determine the correct value for the Intel Arc GPU. 

Anyone have a suggestion?
Thanks!

### Version

0.14

### Frigate config file

```yaml
GNU nano 7.2                                               docker-compose.yml                                                         
#version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - ./config:/config
      - /media/frigate-storage:/media/frigate # for when the hard drive is installed
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971" # web UI
      - "8554:8554" # RTSP feeds
      - "5000:5000" # Home Assistant
      - "1984:1984" # go2rtc api
    devices:
      - /dev/dri/renderD128 # Hardware acceleration for Intel chips
      - /dev/bus/usb:/dev/bus/sub # USB Coral(s)
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

n/a
