### DISCUSSION TITLE
Reduce recording video quality

### DISCUSSION THREAD

**Discussion by aayush-eatclub** [blakeblackshear/frigate#14130] [Ask A Question] [answered]
I have many cameras configured via Frigate. While recording from each camera , a 10 sec clip occupies 5MB of my disk space. I want to reduce this size. This can be done by changing codec , bitrate etc. I am unable to figure out how to do so in frigate. 
Can you please give me some suggestions to reduce my video size of recorded videos.

Below is my frigate configuration.

```
birdseye:
  enabled: false
cameras:
  cam_31:
    detect:
      enabled: false
      height: 720
      width: 1280
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@1234@192.168.1.31/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_32:
    detect:
      enabled: false
      height: 720
      width: 1280
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@1234@192.168.1.32/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_33:
    detect:
      enabled: false
      height: 720
      width: 1280
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@1234@192.168.1.33/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
detect:
  enabled: false
detectors:
  detector_name:
    type: cpu
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
motion:
  enabled: false
mqtt:
  enabled: false
record:
  enabled: true
  retain:
    days: 1
    mode: all
  sync_recordings: true
tls:
  enabled: false
version: 0.14
```
