### DISCUSSION TITLE
[Config Support]: PIPELINE_ERROR_DECODE only on Samsung Tablet A9

### DISCUSSION THREAD

**Discussion by 888Jay** [blakeblackshear/frigate#14147] [Config Support] [answered]
### Describe the problem you are having

For the past few weeks, I've been getting a "Failed to play recordings (error 3): PIPELINE_ERROR_DECODING" error in a red box when I try to access a camera's recording history. But it ONLY happens on my Samsung Tablet A9 (Android 14) and it ONLY happens with my five Hikvision cameras. Recording history for my Reolink doorbell works fine. Accessing record history of the Hikvision cameras on my Pixel 8A (also Android 14), Windows 11 PCs, iPad, and iPhone all work fine.

I tried changing my default browser on the Samsung tablet from Firefox Focus to Chrome. I get the error via Remote UI, Chrome, and Firefox. All cameras are set to H.264 in firmware. I also tried #video=h264#hardware in my configuration. No joy.

Summary:
1) Error only occurs on Samsung Tablet A9
2) Error only occurs with Hikvision cameras
3) Worked for three months until a few weeks ago. 

Any suggestions would be appreciated.

![Screenshot 2024-10-03 175032](https://github.com/user-attachments/assets/ff817355-724d-44c2-9935-1e8fcfdbcea6)

### Version

5.4.0/0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  user: user
  password: password

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency

birdseye:
  restream: true
  width: 1920
  height: 1080
  mode: continuous

go2rtc:
  streams:
    front_porch:
      - rtsp://user:password@192.168.1.239:554/Streaming/Channels/101
    front_porch_sub:
      - rtsp://user:password@192.168.1.239:554/Streaming/Channels/102
    deck_east:
      - rtsp://user:password@192.168.1.241:554/Streaming/Channels/101
    deck_east_sub:
      - rtsp://user:password@192.168.1.241:554/Streaming/Channels/102
    deck_west:
      - rtsp://user:password@192.168.1.240:554/Streaming/Channels/101
    deck_west_sub:
      - rtsp://user:password@192.168.1.240:554/Streaming/Channels/102
    garage_1:
      - rtsp://user:password@192.168.1.242:554/Streaming/Channels/101
    garage_1_sub:
      - rtsp://user:password@192.168.1.242:554/Streaming/Channels/102
    garage_2:
      - rtsp://user:password@192.168.1.243:554/Streaming/Channels/101
    garage_2_sub:
      - rtsp://user:password@192.168.1.243:554/Streaming/Channels/102
    reolink:
      - rtsp://user:password@192.168.1.248:554/h264Preview_01_sub
      - ffmpeg:rtsp://user:password@192.168.1.248:554/h264Preview_01_sub#audio=pcm#audio=volume
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
  webrtc:
    candidates:
      - 192.168.1.105:8555
      - stun:8555

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 5
    post_capture: 5

snapshots:
  enabled: true
  retain:
    default: 14

cameras:
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          roles:
            - detect
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    motion:
      threshold: 30
      contour_area: 30
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    live:
      stream_name: front_porch_sub
    ui:
      order: 1
    birdseye:
      order: 1

  deck_east:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_east
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_east_sub
          roles:
            - detect
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    motion:
      threshold: 30
      contour_area: 30
    objects:
      track:
        - person
        - cat
        - dog
    live:
      stream_name: deck_east_sub
    ui:
      order: 2
    birdseye:
      order: 2

  deck_west:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_west
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_west_sub
          roles:
            - detect
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 217,252,341,190,336,53,239,41
      threshold: 30
      contour_area: 30
    objects:
      track:
        - person
    live:
      stream_name: deck_west_sub
    ui:
      order: 3
    birdseye:
      order: 3

  garage_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_1_sub
          roles:
            - detect
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    motion:
      threshold: 30
      contour_area: 30
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    live:
      stream_name: garage_1_sub
    ui:
      order: 4
    birdseye:
      order: 4

  garage_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_2_sub
          roles:
            - detect
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    motion:
      threshold: 30
      contour_area: 30
    objects:
      track:
        - person
    live:
      stream_name: garage_2_sub
    ui:
      order: 5
    birdseye:
      order: 5

  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.248:554/h264Preview_01_sub
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy

version: 0.14
camera_groups: {}
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

CPU (no coral)
