### DISCUSSION TITLE
[Config Support]: Alerts versus detections

### DISCUSSION THREAD

**Discussion by xavan83** [blakeblackshear/frigate#14149] [Config Support]
### Describe the problem you are having

I have a zone for cars with loitering_time and coordinates.
I want to have these events classified as alerts and others cars classified as detection.
Something it works and something not

### Version

0.15.0-1fa050f

### Frigate config file

```yaml
zones:
      streetpeople:
        objects: person
        coordinates: 0,1,1,1,1,0.603,0,0.626
        loitering_time: 10
      streetcar:
        objects:
          - car
          - bicycle
          - bus
          - motorcycle
        coordinates: 0,1,1,1,1,0.603,0,0.626
        loitering_time: 10
      boiteauxlettres:
        objects:
          - person
          - face
        coordinates: 1,0.98,1,1,0,1,0,0.982
        inertia: 3
 objects:
      filters:
        car: {}
        cat: {}
        dog: {}
      track:
        - face
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
        - horse
        - package
        - license_plate
      mask: 0,0.66,0.495,0.664,1,0.598,1,0,0,-0.002
    review:
      alerts:
        required_zones:
          - streetpeople
          - streetcar
          - boiteauxlettres
      detections:
        labels:
          - person
          - bicycle
          - car
          - motorcycle
          - bus
          - cat
          - dog
          - horse
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral
