### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by mariomare22** [blakeblackshear/frigate#14144] [Config Support]
### Describe the problem you are having

after upgrade to 0.14 and migration to coral usb detection and nvidia hw acceleration I am not able to see events in mqtt via home assistant.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: server.home
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 10
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 720
  retain:
    default: 10
    objects:
      person: 15

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.85

go2rtc:
  streams:
    sala:
      - "ffmpeg:http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming"
      - "ffmpeg:reolink#audio=opus#hardware"
    sala_sub:
      - "ffmpeg:http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming"
    elisa:
      - "ffmpeg:http://10.22.30.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming"
      - "ffmpeg:reolink#audio=opus#hardware"
    elisa_sub:
      - "ffmpeg:http://10.22.30.2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming"
cameras:
  sala:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sala
          input_args: preset-rtsp-restream
          hwaccel_args: preset-nvidia-h264
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sala_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  elisa:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/elisa
          input_args: preset-rtsp-restream        
          hwaccel_args: preset-nvidia-h264
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/elisa_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
version: 0.14
```

### Relevant Frigate log output

```shell
I don't see any relevant log, in mqtt Explorer I don't see events fired, no events are recorded on hard drives.

I am going crazy :-D
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
{
  "cameras": {
    "elisa": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 453,
      "detection_enabled": true,
      "detection_fps": 3.5,
      "ffmpeg_pid": 462,
      "pid": 438,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "sala": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 447,
      "detection_enabled": true,
      "detection_fps": 4.9,
      "ffmpeg_pid": 459,
      "pid": 435,
      "process_fps": 5,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "85": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "87": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "3.5",
      "cpu_average": "3",
      "mem": "0.2"
    },
    "106": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "107": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "1.5",
      "cpu_average": "2",
      "mem": "1.5"
    },
    "130": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "167": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "168": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "169": {
      "cmdline": "nginx: worker process",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "170": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "171": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "323": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "341": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "379": {
      "cmdline": "frigate.recording_manager",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "385": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "407": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(59)",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "408": {
      "cmdline": "frigate.detector.coral",
      "cpu": "6.0",
      "cpu_average": "7",
      "mem": "0.9"
    },
    "410": {
      "cmdline": "frigate.output       ",
      "cpu": "3.4",
      "cpu_average": "2",
      "mem": "0.9"
    },
    "435": {
      "cmdline": "frigate.process:sala ",
      "cpu": "6.5",
      "cpu_average": "6",
      "mem": "0.9"
    },
    "438": {
      "cmdline": "frigate.process:elisa",
      "cpu": "4.5",
      "cpu_average": "6",
      "mem": "0.9"
    },
    "447": {
      "cmdline": "frigate.capture:sala ",
      "cpu": "1.9",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "453": {
      "cmdline": "frigate.capture:elisa",
      "cpu": "1.6",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "459": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/sala_sub -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.0",
      "cpu_average": "2",
      "mem": "0.7"
    },
    "462": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/elisa_sub -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.9",
      "cpu_average": "2",
      "mem": "0.7"
    },
    "465": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/dec5b83bb9b58cc7bb183eb4fcabfc0b",
      "cpu": "1.4",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "466": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/sala -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/sala@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "469": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.22.30.2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/75447353dcca0300ecae9e1bf8231bc6",
      "cpu": "1.3",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "470": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/elisa -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/elisa@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "471": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.22.30.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ea323a11c70e8260c0343eefd6ce7951",
      "cpu": "1.6",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "476": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.22.30.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/a2c47534ae837809f8b503fb6e5df1d6",
      "cpu": "1.5",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "499": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "504": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "509": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "871": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "889": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "7.9",
      "mem": "87.0"
    }
  },
  "detection_fps": 8.4,
  "detectors": {
    "coral": {
      "detection_start": 1727978748.290947,
      "inference_speed": 9.08,
      "pid": 408
    }
  },
  "gpu_usages": {
    "Quadro M2000": {
      "dec": "4.0%",
      "enc": "0.0%",
      "gpu": "0.0%",
      "mem": "6.06%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 341
    },
    "recording": {
      "pid": 379
    },
    "review_segment": {
      "pid": 385
    }
  },
  "service": {
    "last_updated": 1727978748,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 61,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 3
      },
      "/media/frigate/clips": {
        "free": 5804990.6,
        "mount_type": "nfs4",
        "total": 6335426,
        "used": 530435.4
      },
      "/media/frigate/recordings": {
        "free": 5804990.6,
        "mount_type": "nfs4",
        "total": 6335426,
        "used": 530435.4
      },
      "/tmp/cache": {
        "free": 196059.6,
        "mount_type": "overlay",
        "total": 233933.6,
        "used": 25919.7
      }
    },
    "temperatures": {},
    "uptime": 146,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    environment:
      - PUID=1000
      - PGID=1000
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb
    shm_size: "64mb"
    networks:
      - proxy_inet
    ports:
      - 1935:1935
      - 5000:5000
    restart: unless-stopped
    volumes:
      - /mnt/ssd/config/frigate/:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas_nfs/frigate/:/media/frigate
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  proxy_inet:
    external: true
    name: proxy_inet
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1547" alt="image" src="https://github.com/user-attachments/assets/11fd92b9-ac25-4e2e-894b-2a151f77d097">

### Any other information that may be helpful

```
Thu Oct  3 20:07:48 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro M2000                   On  | 00000000:01:00.0 Off |                  N/A |
| 63%   58C    P0              24W /  75W |    189MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1767      G   /usr/lib/xorg/Xorg                           19MiB |
|    0   N/A  N/A    404978      C   ffmpeg                                       82MiB |
|    0   N/A  N/A    404981      C   ffmpeg                                       82MiB |
+---------------------------------------------------------------------------------------+
Thu Oct  3 20:07:49 2024
```
