### DISCUSSION TITLE
Takes forever to load live view when clicking on camera

### DISCUSSION THREAD

**Discussion by JRascagneres** [blakeblackshear/frigate#14151] [General Support] [answered]
Hi all,

Not sure what else to try really. I have an issue where when I click on a camera, it often takes forever (if it loads at all) to load up the live view of the camera. Detection and recording seem to work fine. Additionally if I visit go2rtc directly and click 'stream' it seems to work fine.

Any ideas?

Indoor never seems to load, doorbell and front is slow.

Notably - It works fine for recording, detection and the live views work flawlessly in the HA integration.

Current config:

```
database:
  path: /db/frigate.db

mqtt:
  host: homeassistant.lan
  user: mqtt-user
  password: password

detectors:
  coral_pci:
    type: edgetpu
    device: pci

# ffmpeg:
#   hwaccel_args: preset-nvidia-h264


model:
  path: plus://6827e65d6fcb74ed76de5794000e0eaf

objects:
  filters:
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

go2rtc:
  streams:
    doorbell_reolink:
      - ffmpeg:https://192.168.4.189/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:Fx8ayCvN6*nyW9Gr@192.168.4.189:554/h264Preview_01_sub
    doorbell_reolink_sub:
      - ffmpeg:https://192.168.4.189/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    front_reolink:
      - ffmpeg:https://192.168.4.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
    front_reolink_sub:
      - ffmpeg:https://192.168.4.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=-password
    back_reolink:
      - ffmpeg:https://192.168.4.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
    back_reolink_sub:
      - ffmpeg:https://192.168.4.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    garage_reolink:
      - ffmpeg:https://192.168.4.188/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
    garage_reolink_sub:
      - ffmpeg:https://192.168.4.188/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    indoor_camera_1:
      - rtsp://admin:password@192.168.4.74:554/h264Preview_01_main
      - ffmpeg:indoor_camera_1#video=copy#audio=copy#audio=opus#timeout=30
    indoor_camera_1_sub:
      - rtsp://admin:password@192.168.4.74:554/h264Preview_01_sub
      - ffmpeg:indoor_camera_1#video=copy#audio=copy#audio=opus#timeout=30
    indoor_camera_2:
      - rtsp://admin:password@192.168.4.76:554/h264Preview_01_main
      # - ffmpeg:indoor_camera_2#video=copy#audio=copy#audio=opus#timeout=30
    indoor_camera_2_sub:
      - rtsp://admin:password@192.168.4.76:554/h264Preview_01_sub
      # - ffmpeg:indoor_camera_2#video=copy#audio=copy#audio=opus#timeout=30
  webrtc:
    candidates:
      - homeserver.lan:8555
      - homeassistant.lan:8555
      - 192.168.1.100:8555

cameras:
  doorbell_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - bicycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      required_zones:
        - plant bed
        - path
        - road and path
      retain:
        default: 30
    # live:
    #   stream_name: doorbell_reolink
    motion:
      mask:
        - 640,0,0,0,0,298,224,303,510,294,542,282,640,298,640,222
        - 640,480,640,480,640,447,369,447,367,480
      threshold: 45
      contour_area: 20
      improve_contrast: 'false'
    zones:
      plant bed:
        coordinates: 262,474,398,446,523,391,604,325,528,306,246,365
        objects:
          - person
      path:
        coordinates: 579,480,626,411,609,382,631,329,607,323,553,369,450,429,256,480
        objects:
          - person
      road and path:
        coordinates: 323,282,472,270,506,282,585,287,508,315,417,340,301,356,140,360,149,267,233,280
        objects:
          - person
          - bicycle
    ui:
      order: 0
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    review:
      alerts:
        labels:
          - person
        required_zones:
          - plant bed
          - path
          - road and path
      detections:
        labels:
          - person
          - dog
        required_zones:
          - path
          - plant bed
          - road and path
  front_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - car
        - dog
        - bicycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30
    motion:
      mask:
        - 640,0,0,0,0,165,0,312,37,373,394,163,387,63,640,154
        - 640,480,640,480,640,447,369,447,367,480
      threshold: 30
      contour_area: 20
      improve_contrast: 'true'
    zones:
      front_path:
        coordinates: 458,480,190,273,42,362,0,292,0,480
      front_pavement:
        coordinates: 640,301,640,197,425,113,346,164
      front_road:
        coordinates: 640,205,640,71,546,33,432,117
    # live:
    #   stream_name: front_reolink
    ui:
      order: 1
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    review:
      alerts:
        required_zones:
          - front_path
          - front_pavement
      detections:
        required_zones:
          - front_path
          - front_pavement
  back_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_reolink_sub?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      max_disappeared: 600
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30
    motion:
      improve_contrast: true
      mask:
        - 640,480,640,480,640,447,369,447,367,480
    zones:
      patio:
        coordinates: 323,248,271,203,16,259,79,480,434,480,290,343,185,379,127,291
      grass:
        coordinates: 323,248,271,203,527,147,640,187,640,480,434,480,290,343,185,379,127,291
    ui:
      order: 2
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
  garage_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_reolink?video=copy&audio=copy
          input_args:
            - -timeout
            - '50000000'
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_reolink_sub?video=copy
          input_args:
            - -timeout
            - '50000000'
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
      # This is frames. FPS is 10 so this value / 10 is in seconds.
      max_disappeared: 1200

    objects:
      track:
        - person
        - car
        - bicycle
      # filters:
      #   person:
      #     min_score: 0.6
      #     threshold: 0.7
      #   car:
      #     min_score: 0.4
      #     threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      required_zones:
        - driveway
      retain:
        default: 30
    motion:
      improve_contrast: true
      threshold: 150
      contour_area: 50
      delta_alpha: 0.1
      mask:
        - 367,480,640,480,640,444,367,444
    zones:
      driveway:
        coordinates: 96,480,320,0,445,0,640,480,544,480
      driveway_entrance:
        coordinates: 0.459,0.108,0.726,0.105,0.694,0,0.497,0
        objects: car
        inertia: 3
        loitering_time: 0
    ui:
      order: 3
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1920
    review:
      alerts:
        required_zones: driveway
      detections:
        required_zones: driveway
  indoor_reolink_1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor_camera_1?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            # - detect
        - path: rtsp://127.0.0.1:8554/indoor_camera_1_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    onvif:
      host: 192.168.4.74
      port: 8000
      user: admin
      password: password
    detect:
      width: 640
      height: 360
      fps: 5
      max_disappeared: 900
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30

    motion:
      mask:
        - 446,360,640,360,640,337,448,337
    # live:
    #   stream_name: indoor_camera_1
    ui:
      order: 4
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
  indoor_reolink_2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor_camera_2?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            # - detect
        - path: rtsp://127.0.0.1:8554/indoor_camera_2_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    onvif:
      host: 192.168.4.76
      port: 8000
      user: admin
      password: 'password'
    detect:
      width: 640
      height: 360
      fps: 5
      max_disappeared: 900
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      events:
        retain:
          default: 20

    motion:
      mask:
        - 446,360,640,360,640,337,448,337
    # live:
    #   stream_name: indoor_camera_2
    ui:
      order: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

birdseye:
  enabled: true
  mode: continuous
  quality: 1
  restream: true

live:
  quality: 1
  height: 2560

record:
  enabled: True
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 7
      mode: active_objects

snapshots:
  retain:
    objects:
      person: 15

detect:
  # Number of frames before someone has disappeared --> measured in frames. So frames * framerate
  max_disappeared: 300
version: 0.14
```
