### DISCUSSION TITLE
[Config Support]: Reolink Wifi Doorbell two way audio

### DISCUSSION THREAD

**Discussion by Handrail9** [blakeblackshear/frigate#14154] [Config Support]
### Describe the problem you are having

I am very confused about how two way audio works, and if my device is supported.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.xx.xxx
  port: 8095
  user: xxxx
  password: xxxx

detectors:
  coral:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    camera_1_original:
      - rtsp://xxxx:xxxx@192.168.xx.xxx:554/11
      - ffmpeg:camera_1_original#audio=aac
    camera_1:
      - ffmpeg:camera_1_original#video=h264#hardware#rotate=270#audio=aac
    camera_2:
      - rtsp://192.168.xx.xxx:8080/video/h264
      - ffmpeg:camera_2#audio=aac#video=h264#hardware
    camera_3:
      - rtsp://xxxx:xxx@192.168.xx.xxx/video/h264
      - ffmpeg:camera_3#audio=aac#video=h264#hardware
    reolink_wifi_doorbell:
      - "ffmpeg:http://192.168.xx.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"
      - rtsp://xxxx:xxxx@192.168.xx.xxx/Preview_01_sub
    reolink_wifi_doorbell_sub:
      - "ffmpeg:http://192.168.xx.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx"
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  webrtc:
    candidates:
      - http://192.168.xx.xxx:8555
      - stun:8555



cameras:
  camera_2: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2
          roles:
            - record
            - detect
    detect:
      enabled: true
    motion:
      mask: 0.435,0.966,0.444,0.521,0.164,0.515,0.157,0.967
    record: # <----- Enable recording
      enabled: true
  reolink_wifi_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_wifi_doorbell
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled:
        true
      listen:
        - bark
        - speech
    onvif:
      host: 192.168.xx.xxx
      port: 8080
      user: xxx
      password: 'xxxx'
    detect:
      enabled: true
    record:
      enabled: true
  camera_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1
          roles:
            - record
            - detect
    onvif:
      host: 192.168.xx.xxx
      port: 8080
      user: xxxx
      password: xxxx
    detect:
      enabled: true
    record:
      enabled: true
  camera_3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3
          roles:
            - record
            - detect
    onvif:
      host: 192.168.xx.xxx
      port: 8000
      user: xxxx
      password: xxxx
    detect:
      enabled: true
    record:
      enabled: true
    motion:
      threshold: 37
      contour_area: 23
      improve_contrast: 'true'
  camera_4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.xx.xxx:554/11
          roles:
            - record
            - detect
    onvif:
      host: 192.168.xx.xxx
      port: 8080
      user: xxxx
      password: xxxx
    detect:
      enabled: true
    record:
      enabled: true
version: 0.14
```

### Relevant Frigate log output

```shell
Nothing relevant afaikt
```

### Relevant go2rtc log output

```shell
Nothing relevant afaict
```

### Frigate stats

```json
nothing relevant afaict
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    #  privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 512mb # update for your cameras based on calculation above
    devices:
      #  - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #  - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - 1984:1984 # gortc
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      DOCKER_HOST: dockersocket
    labels:
      - com.centurylinklabs.watchtower.enable=true
  frigate-mqtt:
    stdin_open: true
    tty: true
    container_name: frigate-mqtt
    restart: always
    ports:
      - 8095:1883
    environment:
      DOCKER_HOST: dockersocket
    networks:
      traefik: null
    volumes:
      - /opt/frigate/mosquitto/config:/mosquitto/config
      - /opt/frigate/mosquitto/data:/mosquitto/data
      - /opt/frigate/mosquitto/log:/mosquitto/log
    image: eclipse-mosquitto
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  traefik:
    external: true
```

### Object Detector

Coral

### Any other information that may be helpful

I tried copying information from [discussion 10619](https://github.com/blakeblackshear/frigate/discussions/10619) but i may have made a typo or my doorbell may not be supported. I'm unsure. Here's my doorbell info:
ModelReolink Video Doorbell WiFi
Item No.D340W
Hardware No.DB_566128M5MP_W
Config Versionv3.0.0.0
Firmware Versionv3.0.0.3215_2401262240

**Comment by NickM-27** [comment]
You need to change`reolink_wifi_camera` to `reolink_wifi_doorbell`

**Reply by Handrail9** [reply]
Okay, I've got camera audio! but I can't hear anything through the two-way audio. I'm testing using the Home Assistant lovelace card and I am holding the mic button but i dont hear anything, I'm also not hearing the audio through HA, only in frigate
Here's my lovelace yaml if this helps
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.reolink_wifi_doorbell
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
menu:
  buttons:
    microphone:
      enabled: true
      alignment: opposing
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
      alignment: opposing
    camera_ui:
      enabled: false
  style: overlay
  position: left
  button_size: 80
live:
  controls:
    thumbnails:
      mode: none
  auto_mute: all
  preload: false
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
```
