### DISCUSSION TITLE
Settings Page Blank on 0.14.1

### DISCUSSION THREAD

**Discussion by shawnsi** [blakeblackshear/frigate#14156] [General Support] [answered]
I'm seeing an issue where my settings page appears blank. This is on a system which was working as expected previously. I've tested a vanilla configuration file and empty media directory just to see if the settings UI would load but it still appears blank.

There is no server side log that appears related. The web page appears to be a HTTP 200 in web browser console but does show console errors for client side code.

**Server log**
```2024-10-04 20:51:08.109167802  [INFO] Preparing Frigate...
2024-10-04 20:51:08.224450031  [INFO] Starting Frigate...
2024-10-04 20:51:09.911243905  [2024-10-04 20:51:09] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-04 20:51:09.911381868  [2024-10-04 20:51:09] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-04 20:51:09.979783296  [2024-10-04 20:51:09] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-04 20:51:21.651435063  [2024-10-04 20:51:21] peewee_migrate.logs            INFO    : Starting migrations
2024-10-04 20:51:21.652809577  [2024-10-04 20:51:21] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-04 20:51:21.688934710  [2024-10-04 20:51:21] frigate.app                    INFO    : Recording process started: 375
2024-10-04 20:51:21.704633156  [2024-10-04 20:51:21] frigate.app                    INFO    : Recording process started: 384
2024-10-04 20:51:21.705594560  [2024-10-04 20:51:21] frigate.app                    INFO    : go2rtc process pid: 113
2024-10-04 20:51:21.749662943  [2024-10-04 20:51:21] detector.coral                 INFO    : Starting detection process: 404
2024-10-04 20:51:21.760926626  [2024-10-04 20:51:21] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-10-04 20:51:21.769333356  [2024-10-04 20:51:21] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-10-04 20:51:21.772783530  [2024-10-04 20:51:21] frigate.app                    INFO    : Output process started: 407
2024-10-04 20:51:21.854826726  [2024-10-04 20:51:21] frigate.app                    INFO    : Camera processor started for front_doorbell: 445
2024-10-04 20:51:21.873030810  [2024-10-04 20:51:21] frigate.app                    INFO    : Camera processor started for back_patio: 448
2024-10-04 20:51:21.889831715  [2024-10-04 20:51:21] frigate.app                    INFO    : Camera processor started for south_garden: 453
2024-10-04 20:51:21.949112675  [2024-10-04 20:51:21] frigate.app                    INFO    : Camera processor started for front_porch: 465
2024-10-04 20:51:21.981882358  [2024-10-04 20:51:21] frigate.app                    INFO    : Camera processor started for under_deck: 478
2024-10-04 20:51:22.008981856  [2024-10-04 20:51:21] frigate.app                    INFO    : Capture process started for front_doorbell: 489
2024-10-04 20:51:22.008987967  [2024-10-04 20:51:22] frigate.app                    INFO    : Capture process started for back_patio: 497
2024-10-04 20:51:22.045302711  [2024-10-04 20:51:22] frigate.app                    INFO    : Capture process started for south_garden: 502
2024-10-04 20:51:22.069023517  [2024-10-04 20:51:22] frigate.app                    INFO    : Capture process started for front_porch: 511
2024-10-04 20:51:22.109093637  [2024-10-04 20:51:22] frigate.app                    INFO    : Capture process started for under_deck: 516```
```

**Client side web console errors**
```
SyntaxError: missing ) after argument list (at Settings-Ra-cKUZy.js:35:11028)
Uncaught SyntaxError: missing ) after argument list (at Settings-Ra-cKUZy.js:35:11028)
WebSocket connection to 'ws://gemini:5000/ws' failed: Received a broken close frame containing a reserved status code.
```

**Comment by hawkeye217** [comment]
What's your Frigate config? Do you have any browser plugins or extensions installed? Does it still happen in incognito mode?

**Comment by shawnsi** [comment]
It happens in incognito with no extensions active. A stub config also reproduces the problem. Here is my current config that has the same symptom:

```
mqtt:
  host: mqtt

model:
  path: plus://REDACTED

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  # this setting is critical for smooth recording
  # https://github.com/blakeblackshear/frigate/issues/7349
  input_args: preset-rtsp-restream
  hwaccel_args: preset-rpi-64-h264 # for H264 streams

objects:
  track:
    - person
    - face
    - car
    - cat
    - dog
    - deer
    - package
    - fedex
    - ups
    - amazon
    - license_plate
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .80
    car:
      min_score: .55
      threshold: .75

go2rtc:
  streams:
    front_doorbell:
      - rtsp://REDACTED:8554/front-doorbell # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    front_doorbell_sub:
      - rtsp://REDACTED:8554/front-doorbell-sub # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    back_patio:
      - rtsp://REDACTED:8554/back-patio
    back_patio_sub:
      - rtsp://REDACTED:8554/back-patio-sub
    south_garden:
      - rtsp://REDACTED:8554/south-garden
    south_garden_sub:
      - rtsp://REDACTED:8554/south-garden-sub
    front_porch:
      - rtsp://REDACTED:8554/front-porch
    front_porch_sub:
      - rtsp://REDACTED:8554/front-porch-sub
    under_deck:
      - rtsp://REDACTED:8554/under-deck
    under_deck_sub:
      - rtsp://REDACTED:8554/under-deck-sub

cameras:
  front_doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect

    motion:
      mask:
        - 0.636,0.578,0.589,0.649,0.547,0.654,0.554,0.713,0.596,0.818,0.63,0.848
        - 0.73,0.951,0.731,0.985,0.965,0.984,0.967,0.953
    zones:
      front_property:
        coordinates: 
          0.173,0.652,0.445,0.626,0.587,0.601,0.645,0.576,0.617,0.231,0.927,0.199,1,1,0,1,0,0.145,0.191,0.139
        inertia: 3
        loitering_time: 0
      roadway:
        coordinates: 0.171,0.646,0.384,0.633,0.521,0.619,0.642,0.585,0.626,0.441,0.2,0.475
        inertia: 3
        loitering_time: 0

    mqtt:
      enabled: true

    review:
      alerts:
        required_zones: front_property
        # remove this after garage is sorted out
        labels:
          - person
      detections:
        required_zones:
          - front_property
          - roadway

  back_patio:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_patio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_patio_sub
          roles:
            - detect

    motion:
      mask:
        - 0.108,0.263,0,0.309,0.093,0.441,0.329,0.394,0.486,0.389,0.632,0.393,0.834,0.365,1,0.346,1,0.009
        - 0.781,0.936,0.782,0.986,0.971,0.988,0.97,0.943

    objects:
      filters:
        person:
          min_area: 700
          max_area: 40000

    zones:
      back_property:
        coordinates: 0,0.291,0.828,0.243,0.839,0.441,1,0.555,1,1,0,1
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - cat
          - deer
    review:
      alerts:
        required_zones: back_property
        labels:
          - person
      detections:
        required_zones: back_property
        labels:
          - person
          - cat
          - dog
          - deer

    mqtt:
      enabled: true

  south_garden:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/south_garden
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/south_garden_sub
          roles:
            - detect

    motion:
      mask:
        - 0.777,0.94,0.778,0.983,0.971,0.986,0.97,0.944
        - 0.188,0.274,0.07,0.314,0,0.172,0,0,1,0,1,0.417,1,0.562,0.836,0.405,0.715,0.342,0.484,0.289,0.364,0.269,0.284,0.272
        - 0.001,0.68,0.002,0.759,0.093,0.995,0.506,0.996,0.522,0.568
    objects:
      filters:
        person:
          min_area: 500
          min_score: 0.55
          threshold: 0.70
          mask: 0.604,0.382,0.602,0.433,0.622,0.444,0.632,0.387
    mqtt:
      enabled: true

    zones:
      side_property:
        coordinates: 0,0.443,0.001,0.681,0.508,1,1,1,1,0.621,0.838,0.409,0.396,0.298,0.183,0.302
        loitering_time: 0
        objects:
          - person
          - deer
          - cat
          - dog
    review:
      detections:
        labels:
          - person
          - cat
          - dog
          - deer
      alerts:
        required_zones: side_property
        labels:
          - person

  front_porch:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          roles:
            - detect

    mqtt:
      enabled: true
    motion:
      mask:
        - 0.777,0.938,0.777,0.988,0.975,0.992,0.974,0.936
        - 0.169,0.474,0.193,0.479,0.194,0.555,0.169,0.56
        - 0.168,0,0.246,0.286,0.427,0.342,0.571,0.288,0.757,0.22,0.894,0
    zones:
      front_property:
        coordinates: 0,0.662,0,1,1,1,1,0.654,0.472,0.673,0.169,0.646
        loitering_time: 0
        inertia: 1
        objects:
          - person
          - deer
          - cat
      roadway:
        coordinates: 0.23,0.618,0.475,0.669,1,0.648,1,0.556,0.674,0.596,0.244,0.586
        loitering_time: 0
        inertia: 3

    review:
      detections:
        required_zones:
          - front_property
          - roadway
      alerts:
        required_zones: front_property

    objects:
      filters:
        car:
          threshold: 0.75
        person:
          min_score: 0.55
          threshold: 0.75
          min_area: 300

  under_deck:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/under_deck
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/under_deck_sub
          roles:
            - detect

    review:
      detections:
        labels:
          - person
          - cat
          - dog
          - deer
      alerts:
        labels:
          - person

    mqtt:
      enabled: true

    objects:
      filters:
        person:
          mask:
            - 0.517,0,0.509,0.113,0.773,0.347,1,0.573,1,0
            - 0,0,0,0.362,0,0.741,0.067,0.662,0.042,0.334,0.218,0.217,0.358,0.409,0.503,0.178,0.516,0
      mask: 
        0,0,0,0.362,0,0.741,0.067,0.662,0.042,0.334,0.218,0.217,0.358,0.409,0.503,0.178,0.516,0

snapshots:
  enabled: true
  retain:
    default: 30

record:
  enabled: true
  retain:
    days: 4
    mode: all
  events:
    retain:
      default: 30
      mode: motion

telemetry:
  stats:
    network_bandwidth: true

birdseye:
  mode: continuous

version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuActivitySquare
    cameras: birdseye

  Vertical:
    order: 2
    icon: LuAlignVerticalJustifyEnd
    cameras:
      - front_porch
      - front_doorbell
      - south_garden
      - back_patio
      - under_deck

````
