### DISCUSSION TITLE
[Config Support]: Use Port 8971 for Home Assistant and deactivate port 5000?

### DISCUSSION THREAD

**Discussion by kankadev** [blakeblackshear/frigate#14162] [Config Support] [answered]
### Describe the problem you are having

I'm just "migrating" from 0.13 to 0.14 and I thought I can close port 5000 because I want to secure my frigate instance. It works well now in the browser but the connection between Home Assistant and Frigate is gone now. In the documentation I read I have to use unauthenticated port 5000. 

In my opinion, this makes no sense. I now have an access-restricted port, but I still have to leave the insecure port 5000 open if I want to use the Home Assistant integration. Anyone on the network (even guests) can then access Frigate without authorization. Or am I misunderstanding something here? If not, is it planned that Home Assistant will also use port 8971 in the future? 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.135
  user: mosq
  password: secret
  port: 1883
  topic_prefix: frigate
  client_id: frigate

auth:
  enabled: true
  failed_login_rate_limit: 1/second;3/minute;8/hour
  trusted_proxies:
    - 172.19.0.0/16

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

objects:
  track:
    - person
    - dog
    - cat
    - car
    - motorcycle
    - bicycle
  filters:
    person:
      min_area: 400
      max_area: 1000000

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 7
    post_capture: 10
    retain:
      default: 15
      mode: active_objects

cameras:
  inside_door:
    ffmpeg:
      inputs:
        - path: rtsp://user:secret@192.168.3.221/stream1
          roles:
            - record
        - path: rtsp://user:secret@192.168.3.221/stream2
          roles:
            - detect
            - audio
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0,0.062,0.357,0.068,0.36,0,0,0
    audio:
      enabled: True
      max_not_heard: 10
      min_volume: 500
      listen:
        - scream
        - speech
        - yell
  inside_office:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://user:secret@192.168.0.104:554/h264Preview_01_main
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://user:secret@192.168.0.104:554/h264Preview_01_sub
          roles:
            - detect
            - audio
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 0.676,0.167,0.765,0.166,0.768,0.053,0.681,0.035
        - 0.351,0.065,0.644,0.068,0.643,0.023,0.348,0.027
    audio:
      enabled: True
      max_not_heard: 10
      min_volume: 500
      listen:
        - scream
        - speech
        - yell
  inside_studio_kitchen:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://user:secret@192.168.0.108:554/h264Preview_01_main
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://user:secret@192.168.0.108:554/h264Preview_01_sub
          roles:
            - detect
            - audio
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0.701,0.977,0.994,0.977,0.996,0.939,0.699,0.938
    audio:
      enabled: True
      max_not_heard: 10
      min_volume: 500
      listen:
        - scream
        - speech
        - yell
  inside_studio_living:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://user:secret@192.168.0.109:554/h264Preview_01_main
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://user:secret@192.168.0.109:554/h264Preview_01_sub
          roles:
            - detect
            - audio
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0.012,0.065,0.31,0.063,0.306,0.028,0.014,0.029
    audio:
      enabled: True
      max_not_heard: 10
      min_volume: 500
      listen:
        - scream
        - speech
        - yell
  outside_door:
    ffmpeg:
      inputs:
        - path: rtsp://user:secret@192.168.0.103/stream1
          roles:
            - record
        - path: rtsp://user:secret@192.168.0.103/stream2
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 360
      fps: 5
    zones:
      poi:
        coordinates:
          0,1,1,1,1,0.192,0.925,0.146,0.92,0.217,0.824,0.171,0.831,0.084,0.712,0.045,0,0.282
        inertia: 3
        loitering_time: 1
    motion:
      mask:
        - 0.046,0.178,0.045,0.21,0.1,0.197,0.095,0.145
        - 0.872,0,1,0,1,0.188,0.922,0.141,0.915,0.21,0.83,0.167,0.836,0.083,0.707,0.039,0.714,0
        - 0.358,0.048,0.358,0,0,0,0,0.048
    review:
      alerts:
        required_zones: poi
  outside_front_door:
    ffmpeg:
      inputs:
        - path: rtsp://user:secret@192.168.0.101/stream1
          roles:
            - record
        - path: rtsp://user:secret@192.168.0.101/stream2
          roles:
            - detect
            - audio
    detect:
      width: 1280
      height: 720
      fps: 20
    motion:
      mask:
        - 0.367,0,0.36,0.098,0.199,0.09,0,0.122,0,0
        - 0.15,1,0,1,0,0.535,0.024,0.536
        - 0.495,0.001,1,0,1,0.332
        - 0.576,0.168,0.699,0.391,1,0.978,1,0.408
    zones:
      poi:
        coordinates:
          0.026,0.528,0.155,1,1,1,0.587,0.19,0.516,0.174,0.495,0.14,0.486,0.287,0.345,0.285,0.344,0.151,0,0.206,0,0.529
        inertia: 3
        loitering_time: 1
    review:
      alerts:
        required_zones: poi
    audio:
      enabled: True
      max_not_heard: 10
      min_volume: 500
      listen:
        - scream
        - speech
        - yell
  outside_left_front:
    ffmpeg:
      inputs:
        - path: rtsp://user:secret@192.168.0.106/stream1
          roles:
            - record
        - path: rtsp://user:secret@192.168.0.106/stream2
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    zones:
      poi:
        coordinates: 1,1,0,1,0,0.886,0.724,0.098,0.996,0.104
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0.369,0.45,0.669,0.153,0.656,0,0,0,0,0.878
        - 0.698,0,0.69,0.091,0.989,0.088,0.988,0
    review:
      alerts:
        required_zones: poi
  outside_left_behind:
    ffmpeg:
      inputs:
        - path: rtsp://user:secret@192.168.0.105/stream1
          roles:
            - record
        - path: rtsp://user:secret@192.168.0.105/stream2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 20
    zones:
      poi:
        coordinates: 0.459,1,0.814,1,0.822,0.207,0.727,0.197
        inertia: 3
        loitering_time: 1
    motion:
      mask:
        - 0,1,0.453,1,0.725,0.19,0.827,0.201,0.824,0,0,0
        - 0.853,1,1,1,1,0,0.83,0
    review:
      alerts:
        required_zones: poi
  outside_back:
    ffmpeg:
      inputs:
        - path: rtsp://user:secret@192.168.0.107/stream1
          roles:
            - record
        - path: rtsp://user:secret@192.168.0.107/stream2
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0,1,0,1,0.105,1,0.695,0.096,0.854,0.119,0.855,0,0.708,0,0,0
    zones:
      poi:
        coordinates: 118,360,575,360,553,45,444,36

    review:
      alerts:
        required_zones: poi
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
  Inside:
    order: 2
    icon: LuBedDouble
    cameras:
      - inside_door
      - inside_office
      - inside_studio_kitchen
      - inside_studio_living
  Outside:
    order: 3
    icon: LuFlower2
    cameras:
      - outside_back
      - outside_door
      - outside_front_door
      - outside_left_behind
      - outside_left_front
```

### Relevant Frigate log output

```shell
---
```

### Relevant go2rtc log output

```shell
---
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      #- "5000:5000" # deprecated 
      - "8971:8971" # new restricted access port since 0.14.x
      #- "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "secret"
```

### Object Detector

Coral
