### DISCUSSION TITLE
AMD CPU XDNA(NPU) better than iGPU, use openvino get 3ms

### DISCUSSION THREAD

**Discussion by Vincent5220** [blakeblackshear/frigate#14186] [General]
Im new here, 
I was using reolink independently.
And want to use Frigate NVR for more flexibility.

I now truly love the Frigate NVR.
Want to share setting for AMD CPU XDNA(NPU) user.
You wont need iGPU or dGPU at all.

System: 
Miniforum UM790
AMD 7940HS which include `XDNA(NPU)`
Running Frigate on Ubuntu 24.04 using `Portainer`

Camera detect at 
1x Reolink Doorbell 2K
2x Reolink RLC810A 4K

Set the Frigate config to use Openvino as Official Doc described.
Just remember to us `CPU` as detector type.
DONT USE `Auto` and `GPU`, Frigate will failed to Start.

```
detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

And you will get Inference Speed about 3-5ms
Also you can use `YoloNAS model`, you will get 7-9ms.

Truly Amazing, excellent job Frigate with NPU.
For everyone with AMD CPU XDNA(NPU).

![Screenshot_20241007_144736_Home Assistant](https://github.com/user-attachments/assets/c19e8586-209f-4ddd-96c9-aa25b2ed09e9)
