### DISCUSSION TITLE
Zone specific alerts / detections

### DISCUSSION THREAD

**Discussion by tpjanssen** [blakeblackshear/frigate#14188] [Ideas]
I would like a function to configure zone specific alerts and detections on label level. Something like this:

```yaml
cameras:
  backyard:
    review:
      alerts:
        zones:
          zone_fence:
            - person
            - cat
            - dog
          zone_terrace:
            - cat
            - dog
          zone_garden:
            - cat
            - dog
      detections:
        zones:
          zone_terrace:
            - person
          zone_garden:
            - person
```

This gives me the option to get a person alert for zone_fence only, while for all other zones I only want a detection. What do you think about this?
