### DISCUSSION TITLE
[Support]: No Snapshots in NEW history view

### DISCUSSION THREAD

**Discussion by Redwid** [blakeblackshear/frigate#14189] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After updating to the new UI 0.14.1-f4f3cfa I can't find where is a snapshots now.
Is that moved or that feature removed now?
I see that frigate still generates pngs in clips folder. But can't find that in UI.

### Steps to reproduce

1.
2.
3.
...

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

128.3.0esr (64-bit)

### Frigate config file

```yaml
mqtt:
  host: ...

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p

...
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
Docker cli
```

### Relevant Frigate log output

```shell
...
```

### Relevant go2rtc log output

```shell
...
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Multiple cameras

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/35301ddb-c7f8-4e00-b3e5-769358593fdb)
