### DISCUSSION TITLE
Only one camera but coral is very slow (162.65ms)

### DISCUSSION THREAD

**Discussion by nguyenvanchiem** [blakeblackshear/frigate#14197] [Detector Support]
I install latest version (0.14.1) and have coral ls /dev/apex* show /dev/apex_0
The basic config in Frigate

```
mqtt:
  enabled: false
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: pci
cameras:
  test: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.44:39423/a42e6c77cee82b0f # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
version: 0.14
```

But the coral is alsway high. The coral is very high as image below. it is alsway 162. Do you have advice for this case?
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/d3edd3f7-f898-4c78-bf8a-938b2f310a1f">
<img width="412" alt="image" src="https://github.com/user-attachments/assets/d7f0130b-0019-43b4-adb5-2fd5a3dcc7d5">
<img width="753" alt="image" src="https://github.com/user-attachments/assets/cef09298-f002-4c5b-8791-627138287a6c">
