### DISCUSSION TITLE
The coral is very slow. It always shows 162ms

### DISCUSSION THREAD

**Discussion by nguyenvanchiem** [blakeblackshear/frigate#14199] [Detector Support]
I install latest version (0.14.1) and have coral ls /dev/apex* show /dev/apex_0
The basic config in Frigate

```
mqtt:
enabled: false
detectors: # <---- add detectors
coral:
type: edgetpu
device: pci
cameras:
test: # <------ Name the camera
enabled: true
ffmpeg:
inputs:
- path: rtsp://192.168.1.44:39423/a42e6c77cee82b0f # <----- The stream you want to use for detection
roles:
- detect
detect:
enabled: false # <---- disable detection until you have a working camera feed
version: 0.14
```
But the coral is alsway high. The coral is very high as image below. it is alsway 162. Do you have advice for this case?
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/c1498d06-727d-466e-8e1e-e23c58153672">
<img width="760" alt="image" src="https://github.com/user-attachments/assets/91cfccd3-9334-481a-9b67-bed05d6c3050">

**Comment by NickM-27** [comment]
you need to answer all of the requested information

**Reply by NickM-27** [reply]
we need to know the host OS, how frigate is installed, etc

**Reply by nguyenvanchiem** [reply]
My OS is Ubuntu 24.04.1 LTS.
I use docker compose file to install.
Please let me know if I missed anything

```
version: "3.9"
services:
  frigate:
    container_name: frigate.0.14.1
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "600mb" # update for your cameras based on calculation abov
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5001:5000"
      - "8555:8554" # RTSP feeds
      - "8972:8971"
    environment:
      - TZ=Asia/Ho_Chi_Minh
```
