### DISCUSSION TITLE
[Detector Support] RTX 1660 Super | AttributeError: 'TensorRtDetector' object has no attribute 'outputs'

### DISCUSSION THREAD

**Discussion by scrouillou** [blakeblackshear/frigate#14204] [Detector Support] [answered]
EDIT : Fixed, I forgot the `model` part of the config, you’ll find below a working configuration

### Describe the problem you are having

Hi, I’m trying to add a GPU for detecting after several months of flawless work on my instance with a cpu decoder to enhance my ~70ms inference speed.

I run my Frigate within a docker container on a VM in TrueNAS scale, have passed the GPU through the layers, but am blocked at what seems to be the last link of the chain.

The passthrough is working, with CPU detector I have GPU decoding without issue.

It seems this kind of issue has already been encountered, but I’m a C++ developer whom never delved into machine learning / tensor flow, so I have not found the solution by myself

https://github.com/blakeblackshear/frigate/issues/5058  : This tickets talks about a missing ′libyolo_layer.so′ ; I have no such file on my volume, could this be the issue ? How can I solve it ?

I have also tried different models, but I do not really understand what I am doing. What configuration do you recommend with my GPU ? Which Model? Should I enable or disable FP16?

Thank you very much.

### Version

0.14.1-f4f3cfa

### Frigate config file

```
mqtt:
  enabled: false

objects:
  track:
    - person
    - cat
    - car

detect:
  enabled: true

record:
  enabled: true

snapshots:
  enabled: true

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  cam01:
    enabled: true
    webui_url: http://xxx
    ffmpeg:
      inputs:
        - path: rtsp://xxx
          roles:
            - detect
        - path: rtsp://xxx
          roles:
            - record
  xxx

version: 0.14

```

### Relevant log output

```

2024-10-08 00:10:06.472087907  [2024-10-08 00:10:06] detector.tensorrt              INFO    : Starting detection process: 434
2024-10-08 00:10:06.557526144  Process detector:tensorrt:
2024-10-08 00:10:06.558297207  Traceback (most recent call last):
2024-10-08 00:10:06.558300653    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-10-08 00:10:06.558305993      self.run()
2024-10-08 00:10:06.558309290    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-10-08 00:10:06.558311774      self._target(*self._args, **self._kwargs)
2024-10-08 00:10:06.558313678    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-10-08 00:10:06.558343383      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-10-08 00:10:06.558345918    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-10-08 00:10:06.558347551      self.detect_api = create_detector(detector_config)
2024-10-08 00:10:06.558369092    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-10-08 00:10:06.558370765      return api(detector_config)
2024-10-08 00:10:06.558372378    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 246, in __init__
2024-10-08 00:10:06.558373941      self.engine = self._load_engine(detector_config.model.path)
2024-10-08 00:10:06.558375654    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 90, in _load_engine
2024-10-08 00:10:06.558377167      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
2024-10-08 00:10:06.558378780  TypeError: expected str, bytes or os.PathLike object, not NoneType
2024-10-08 00:10:06.558380403  Exception ignored in: <function TensorRtDetector.__del__ at 0x7efd57f4c1f0>
2024-10-08 00:10:06.558381755  Traceback (most recent call last):
2024-10-08 00:10:06.558384110    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 265, in __del__
2024-10-08 00:10:06.558441638      if self.outputs is not None:
2024-10-08 00:10:06.558444103  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

And then the container restarts

### System

AMD Ryzen 7 2700X / GTX 1660 Super
TrueNas Scale
Debian VM with 1 CPU (4 cores x 2theads), 16GiB RAM, GPU passed through
Dockerized

### Dockerfile

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
      # - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: [̦'0'] # this is only needed when using multiple GPUs
              count: all # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/frigate/config:/config
      - /mnt/vault/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
    networks:
      - caddy_default # for reverse proxy

networks:
  caddy_default:
    external: true
```

### Config directory

```
➜  config ll -R
.:
total 274K
   6  11K drwxr-xr-x 3 root root   14 Oct  8 00:22 .
   5  512 drwxr-xr-x 4 root root    4 Aug  8 03:57 ..
  24 6.0K -rw-r--r-- 1 root root 1.4K Oct  7 22:15 backup_config.yaml
  25 107K -rw-r--r-- 1 root root 448K Oct  7 22:15 backup.db
6461 6.0K -rw-r--r-- 1 root root 1.4K Oct  8 00:22 config.yml
 687  512 -rw-r--r-- 1 root root   17 Oct  7 22:16 .exports
1170 107K -rw-r--r-- 1 root  568 500K Oct  8 00:10 frigate.db
 391  17K -rw-r--r-- 1 root root 100K Aug 19 03:01 frigate.db.bkp
6376 6.0K -rw-r--r-- 1 root  568  32K Oct  8 00:23 frigate.db-shm
6847 6.0K -rw-r--r-- 1 root  568  25K Oct  8 00:23 frigate.db-wal
 318 6.0K -rw-r--r-- 1 root root  128 Oct  7 22:16 .jwt_secret
 769  512 drwxr-xr-x 3 root root    3 Oct  7 22:06 model_cache
 651  512 -rw-r--r-- 1 root root   17 Aug  8 03:59 .timeline
 653  512 -rw-r--r-- 1 root root   17 Oct  7 19:23 .vacuum

./model_cache:
total 12K
769 512 drwxr-xr-x 3 root root  3 Oct  7 22:06 .
  6 11K drwxr-xr-x 3 root root 14 Oct  8 00:22 ..
542 512 drwxr-xr-x 3 root root  5 Oct  8 00:22 tensorrt

./model_cache/tensorrt:
total 2.5K
 542 512 drwxr-xr-x 3 root root  5 Oct  8 00:22 .
 769 512 drwxr-xr-x 3 root root  3 Oct  7 22:06 ..
 426 512 drwxr-xr-x 2 root root  4 Oct  7 23:00 8.5.3
7426 512 lrwxrwxrwx 1 root root 49 Oct  8 00:22 yolov4-288.trt -> /config/model_cache/tensorrt/8.5.3/yolov4-288.trt
7298 512 lrwxrwxrwx 1 root root 49 Oct  7 22:57 yolov7-320.trt -> /config/model_cache/tensorrt/8.5.3/yolov7-320.trt

./model_cache/tensorrt/8.5.3:
total 334M
 426  512 drwxr-xr-x 2 root root    4 Oct  7 23:00 .
 542  512 drwxr-xr-x 3 root root    5 Oct  8 00:22 ..
6159 250M -rw-r--r-- 1 root root 251M Oct  7 23:00 yolov4-288.trt
1557  84M -rw-r--r-- 1 root root  86M Oct  7 22:15 yolov7-320.trt

```

### Nvidia SMI
```
➜  config nvidia-smi
Tue Oct  8 01:08:37 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    On  | 00000000:00:07.0 Off |                  N/A |
|  0%   60C    P2              33W / 125W |    270MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    162141      C   ffmpeg                                       93MiB |
|    0   N/A  N/A    162158      C   ffmpeg                                       91MiB |
|    0   N/A  N/A    162159      C   ffmpeg                                       81MiB |
+---------------------------------------------------------------------------------------+
```
