### DISCUSSION TITLE
[Config Support]: Masks ignored so lot of unasked Recordings

### DISCUSSION THREAD

**Discussion by berndthiel** [blakeblackshear/frigate#14219] [Config Support]
### Describe the problem you are having

In my Garden Setup i have a precise Setup what i wanna analyze and record and which not

![image](https://github.com/user-attachments/assets/12183032-984a-4bfa-b522-21696615c111)
![image](https://github.com/user-attachments/assets/0d09bfe9-5924-476b-845a-f699cd42d1e3)
![image](https://github.com/user-attachments/assets/c4453fdb-27e8-40bd-81cf-31f312eb0ad8)

but it seems it will be ignored, see
![image](https://github.com/user-attachments/assets/eec5849d-2257-48b7-9804-ed25e2d6ab4d)

so 
- all 10min a new Recording
- 19 alerts
- 0 detections
- 0 motion

i have no clue what i have to adapt in my config, but actually i have 700MB Recordings in Garden which are unneeded :(

### Version

newest

### Frigate config file

```yaml
# MQTT settings
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: mqtt-password
  stats_interval: 60

# ui
detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# Live view settings
live:
  height: 720
  quality: 10

# Birdseye
birdseye:
  enabled: false
  mode: continuous

objects:
  track:
    - person
    - car
    - cat
    - dog
    - horse
    - bicycle
  filters:
    person:
      threshold: 0.72

# Record, Detect, Snapshots
record:
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 14 # <- number of days to keep event recordings
      mode: active_objects

detect:
  width: 600
  height: 300
  fps: 5

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: true
  retain:
    default: 30

### go2rtc ###
go2rtc:
  streams:
    # JideTech
    parking:
      - rtsp://admin:xxx@192.168.100.11/cam1/mpeg4
    #H.VIEW
    housedoor:
      - rtsp://admin:xxx@192.168.100.12:554/live/main
    #Reolink
    carport_main:
      - rtsp://admin:xxx@192.168.100.14:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
    carport_sub:
      - rtsp://admin:xxx@192.168.100.14:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
    garden_main:
      - rtsp://admin:xxx@192.168.100.15:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
    garden_sub:
      - rtsp://admin:xxx@192.168.100.15:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus

##############################################################

cameras:
# parking
  parking:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/parking
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record

    motion:
      threshold: 45
      contour_area: 25
      improve_contrast: 'true'
      mask: 
        -0.002,0.361,0.279,0.363,0.275,0.228,0.644,0.238,0.635,0.358,0.99,0.363,1,-0.002,0.002,-0.002
    zones:
      parking_einfahrt:
        coordinates: 0.278,0.38,0.663,0.385,0.803,0.444,0.166,0.475
        loitering_time: 3
        inertia: 5
      parking_parkplatz:
        coordinates: 0.162,0.475,0.105,0.581,0.152,0.992,0.994,0.989,0.989,0.464,0.82,0.441
        loitering_time: 0
      Parking_Dog:
        coordinates: 0.059,1,0.073,0.346,0.285,0.257,0.626,0.257,0.88,0.358,0.994,0.916,1,1
        loitering_time: 0
        objects: dog
    objects:
      mask: 
        0.005,0,0.003,0.363,0.278,0.363,0.274,0.228,0.644,0.241,0.635,0.363,0.75,0.421,0.844,0.441,0.993,0.461,0.993,0.008
      filters:
        person:
          mask:
            - 0.005,0,0.003,0.363,0.278,0.363,0.274,0.228,0.644,0.241,0.635,0.363,0.75,0.421,0.844,0.441,0.993,0.461,0.993,0.008
            - 0.282,0.231,0.285,0.368,0.642,0.373,0.643,0.249
        bicycle:
          mask:
            - 0.005,0,0.003,0.363,0.278,0.363,0.274,0.228,0.644,0.241,0.635,0.363,0.75,0.421,0.844,0.441,0.993,0.461,0.993,0.008
            - 0.276,0.227,0.29,0.356,0.657,0.366,0.672,0.242
        car:
          mask:
            - 0.005,0,0.003,0.363,0.278,0.363,0.274,0.228,0.644,0.241,0.635,0.363,0.75,0.421,0.844,0.441,0.993,0.461,0.993,0.008
            - 0.005,0.183,0.992,0.205,0.997,0.397,0,0.382
  housedoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/housedoor
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record

    motion:
      threshold: 41
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.005,0.075,0.194,0.103,0.205,0.04,0.012,0.023
    zones:
      housedoor_001:
        coordinates: 0.47,0.65,0.505,0,0.165,0,0.17,0.145
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - car
          - bicycle
      housedoor_002:
        coordinates: 0.106,1,0.681,1,0.887,0.439,0.737,0.361,0.471,0.609,0.251,0.302,0,0.615,0,0.785

# carport
        inertia: 3
        loitering_time: 2
        objects:
          - person
          - dog
          - cat
    objects:
      filters:
        car: {}
      mask:
        - 0.002,0.441,0.062,0.411,0.206,0.887,0.121,0.993,0.002,0.993
        - 0,0.098,0.21,0.123,0.213,0.015,0.006,0.003
  carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      threshold: 28
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.139,0.362,0.7,0.35,0.86,0.481,0.881,0.689,1,0.959,1,0,0,0,0,0.186,0.134,0.172
    zones:
      carport001:
        coordinates: 
          0.555,0.353,0.139,0.366,0.061,0.464,0,0.574,0,1,1,1,0.868,0.627,0.791,0.467,0.705,0.352
        loitering_time: 3
        objects:
          - car
          - person
          - dog
          - cat
        inertia: 10
    objects:
      filters:
        car:
          mask:
            - 0.483,0.199,1,0.663,1,0,0.472,0
            - 0.006,0.011,0.014,0.15,0.543,0.125,0.538,0.007
      mask: 0.006,0.011,0.014,0.15,0.543,0.125,0.538,0.007
    review:
      alerts:
        required_zones: carport001
      detections:
        required_zones: carport001
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      threshold: 40
      contour_area: 39
      improve_contrast: 'true'
      mask: 0,0.931,0.201,0.547,0.561,0.492,0.591,0.568,1,0.693,1,0,0,0
    zones:
      garden_001:
        coordinates: 0.993,0.712,0.993,0.812,0.456,0.617,0.576,0.592
        inertia: 3
        loitering_time: 0
      garden_002:
        coordinates: 336,152,338,174,264,179,264,155
      garden_003:
        coordinates: 0.064,1,0.044,0.864,0.196,0.574,0.253,0.584
        inertia: 3
        loitering_time: 0
      garden_004:
        coordinates: 600,300,534,300,542,255,600,209
      garden003:
        coordinates: 0.26,0.58,0.225,0.654,0.437,0.608,0.426,0.562
        loitering_time: 0
        objects: person
    objects:
      filters:
        car:
          mask:
            - 0,0.887,0.199,0.539,0.198,0.414,0.134,0.441,0.003,0.514
            - 0.58,0.554,0.995,0.674,0.992,0.474,0.485,0.439
version: 0.14
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral
