### DISCUSSION TITLE
Struggling with MQTT & Frigate

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#14220] [Ask A Question]
I'm running the Frigate add-on in HA and it's working great. However, I'm running into an issue with MQTT. I can't seem to get it to connect with MQTT so all my entities in HA are greyed out. See below:

![Screenshot 2024-10-08 100709](https://github.com/user-attachments/assets/b3404333-d0b4-41e1-90b7-a495bef5276a)

All I'm trying to do is get it to detect people. I don't need it to record a clip of the detection. 

Here is my code. I've tried both my HA server IP (192.168.107.2) and 'core-mosquito' as the host name, but neither worked to ungrey the detect sensor.

```
mqtt:
  host: core-mosquitto

go2rtc:
  streams:
    FrontPorch:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=0

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: false
```

Any suggestions?
