### DISCUSSION TITLE
[Config Support]: Conflicts on S6 unit go2rtc-healthcheck

### DISCUSSION THREAD

**Discussion by dj4n60** [blakeblackshear/frigate#14231] [Config Support] [answered]
### Describe the problem you are having

Following the go2rtc documentation i configured the base_path and change it from the default. Changing it, frigate become unstable and the go2rtc streams keep restarting around every 30 second. Further analysis shows that the frigate have the S6 supervision suite more specifically /etc/s6-overlay/s6-rc.d/go2rtc-healthcheck/ the run file check the static string  http://127.0.0.1:1984/api/streams.
The above means that  changing the base_path or listen under the api section conflict with the static health-check file.
For future reference my solution was to change the string to the new localhost port and path and everything worked as expected

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
version: 0.14
tls:
  enabled: false
database:
  path: /db/frigate.db
mqtt: # If you have a MQTT server then update this section, if not delete it.
  enabled: False
record: # how long to record before and after motion
  enabled: True
  sync_recordings: True
  retain:
    mode: all
    days: 14
snapshots:
  enabled: False
detect:
  enabled: false
cameras:
  demoRoomCamera:   # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
go2rtc:
  api:
    listen: ":1984"
    username: "X"
    password: "X"
    base_path: "/rtc"
    origin: "*"
    tls_listen: ":19984"
    tls_cert: |
    tls_key: |
    unix_listen: "/tmp/go2rtc.sock"

  webrtc:
    listen: ":8555"
    candidates:
    ice_servers:
  streams:
    camera_1: 
  ffmpeg:
    bin: "ffmpeg"

  log:
    format: "color"
    level: "debug"
    output: "stdout"
    time: "UNIXMS"
```

### Relevant Frigate log output

```shell
~Not exactly relevant~
DBG [hass] can't import config: open /config/.storage/core.config_entries: no such file or directory
frigate  | 2024-10-09 07:43:49.306853373  [2024-10-09 07:43:49] watchdog.demoRoomCamera        ERROR   : Ffmpeg process crashed unexpectedly for demoRoomCamera.
frigate  | 2024-10-09 07:43:49.320143537  [2024-10-09 07:43:49] watchdog.demoRoomCamera        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-10-09 07:43:49.320800726  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [segment @ 0x5649998bc540] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | 2024-10-09 07:43:49.320808657  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x564999c8ea80] [swscaler @ 0x564999c9ba80] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.321351361  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x564999c8ea80] [swscaler @ 0x564999cccbc0] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.321359164  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [segment @ 0x5649998bc540] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frigate  | 2024-10-09 07:43:49.321870235  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x5649999a0e40] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.321916375  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x564999c97e80] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322376082  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x5649999a0e40] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322383055  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x564999c97e80] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322387772  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x5649999a0e40] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322895526  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x564999c97e80] deprecated pixel format used, make sure you did set range correctly
```

### Relevant go2rtc log output

```shell
~Not exactly relevant~
DBG [hass] can't import config: open /config/.storage/core.config_entries: no such file or directory
frigate  | 2024-10-09 07:43:49.306853373  [2024-10-09 07:43:49] watchdog.demoRoomCamera        ERROR   : Ffmpeg process crashed unexpectedly for demoRoomCamera.
frigate  | 2024-10-09 07:43:49.320143537  [2024-10-09 07:43:49] watchdog.demoRoomCamera        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-10-09 07:43:49.320800726  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [segment @ 0x5649998bc540] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | 2024-10-09 07:43:49.320808657  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x564999c8ea80] [swscaler @ 0x564999c9ba80] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.321351361  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x564999c8ea80] [swscaler @ 0x564999cccbc0] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.321359164  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [segment @ 0x5649998bc540] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frigate  | 2024-10-09 07:43:49.321870235  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x5649999a0e40] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.321916375  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x564999c97e80] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322376082  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x5649999a0e40] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322383055  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x564999c97e80] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322387772  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x5649999a0e40] deprecated pixel format used, make sure you did set range correctly
frigate  | 2024-10-09 07:43:49.322895526  [2024-10-09 07:43:49] ffmpeg.demoRoomCamera.detect   ERROR   : [swscaler @ 0x56499989fa00] [swscaler @ 0x564999c97e80] deprecated pixel format used, make sure you did set range correctly
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml
      - /opt/frigate/storage:/media/frigate
      - /opt/frigate/database:/db/
      #- /opt
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: "host"
```

### Object Detector

CPU (no coral)
