### DISCUSSION TITLE
Crash Every 24 hours - Is there daily tasks Frigate does?

### DISCUSSION THREAD

**Discussion by sluflyer06** [blakeblackshear/frigate#14238] [Ask A Question]
Hi.

Yesterday I woke up and Frigate was nearly unresponsive, checking the VM stats, the CPU's were working up to being 100% on every thread, restarting Frigate corrected the behavior for the entire VM.

This morning I did not catch it as early, when I went to check frigate on my phone there was no response, neither was anything on this VM responding at all, going to xen orchestra I saw every thread on the VM was at 100% load at exactly the same time as yesterday. I was unable to access the VM at all and had to force reboot it so I'm not sure any frigate logs would still be there.

Are there any daily tasks or tasks run every 24 hour by Frigate to do anything that might cause the same thing to happen at a 24 hour interval?

**Comment by NickM-27** [comment]
What time was it? There are a few different tasks that happen on a daily basis

**Reply by sluflyer06** [reply]
Somewhere around 5am CST local time which I think is about 10:00 UST

**Reply by NickM-27** [reply]
it uses localtime, and 5 am is not one of them. What is your config

**Comment by sluflyer06** [comment]
```
mqtt:
  host: 10.10.10.60
  port: 1883
#  client_id: frigate
  user: *****
  password: 
  topic_prefix: frigate
#  stats_interval: 60
auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.18.0.0/16# <---- this is the subnet for the internal docker compose network
telemetry:
  network_interfaces:
    - enX0
  stats:
    network_bandwidth: true
objects:
  track:
    - person
    - car
    - dog
    - cat
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 1000
    car:
      min_area: 5000

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
#  path: /trt-models/yolov7-tiny-416.trt
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

cameras:
  frontdoor:
    zones:
      yard:
        coordinates: 21,555,716,565,708,433,12,319
      porch:
        coordinates: 720,576,565,576,588,440,208,447,0,429,0,576
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            rtsp://admin:****#@10.10.10.200:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          hwaccel_args: preset-nvidia
          roles:
            - detect
        - path: 
            rtsp://admin:****#@10.10.10.200:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          hwaccel_args: preset-nvidia
          roles:
            - record
            - audio
    detect:
      width: 720
      height: 576
      fps: 5
    snapshots:
      enabled: true
      required_zones:
        - yard
      quality: 90
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30
    motion:
      mask:
        - 339,264,720,294,720,0,0,0,0,218,65,258
    review:
      alerts:
        required_zones:
          - yard
  garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:****#@10.10.10.174:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          hwaccel_args: preset-nvidia
          roles:
            - record
            - audio
        - path: 
            rtsp://admin:*****@10.10.10.174:554/cam/realmonitor?channel=1&subtype=2&authbasic=64
          hwaccel_args: preset-nvidia
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      required_zones:
        - test
      quality: 90
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30

    zones:
      GarageZone:
        coordinates: 0.005,0.763,0.726,0.361,0.951,0.37,0.895,0.983,0.012,0.997
        loitering_time: 0
    review:
      alerts:
        required_zones: GarageZone
    motion:
      mask: 
        0.002,0.003,0.003,0.283,0.132,0.296,0.23,0.287,0.466,0.214,0.517,0.173,0.52,0.003
    objects:
      filters:
        car:
          mask:
            - 0.307,0.303,0.383,0.282,0.355,0.169,0.237,0.202,0.24,0.31
            - 0.805,0.324,0.809,0.235,0.941,0.275,0.951,0.353,0.928,0.356
  backyardmain:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:****@10.10.10.153:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          hwaccel_args: preset-nvidia
          roles:
            - record
            - audio
        - path: 
            rtsp://admin:******#@10.10.10.153:554/cam/realmonitor?channel=1&subtype=2&authbasic=64
          hwaccel_args: preset-nvidia
          roles:
            - detect
    onvif:
      host: 10.10.10.153
      port: 80
      user: admin
      password: ******
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      required_zones:
        - test2
      quality: 90
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30
    zones:
      Sidebackyard:
        coordinates: 0.565,0.974,0.737,0.152,0.818,0.107,0.946,0.167,0.998,0.294,0.975,0.934
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
      Back-backyard:
        coordinates: 0.632,0.296,0.264,0.252,0.36,0.141,0.563,0.111,0.706,0.104
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones:
          - Sidebackyard
          - Back-backyard
    motion:
      mask: 
        0.235,0.101,0.595,0.037,0.713,0.045,0.809,0.057,0.863,0.059,0.918,0.087,0.943,0.114,0.961,0.138,0.998,0.165,0.999,0.004,0.226,0
    objects:
      filters:
        person:
          mask: 
            0,0.669,0.127,0.722,0.166,0.762,0.194,0.81,0.216,0.855,0.235,0.901,0.237,0.946,0.227,0.968,0.154,0.996,0.003,0.994
version: 0.14
```
