### DISCUSSION TITLE
Detect camera in error and restarting only this camera instead of entire Frigate

### DISCUSSION THREAD

**Discussion by spyjo** [blakeblackshear/frigate#14232] [General Support] [answered]
Hello,

Sometimes I have a camera showing "No frames have been received, check error logs" at the homepage, but clicking on it to view it live is working great.
So to make it work again I have to catch the error (I'm not going to the Frigate UI every day), then I have to restart Frigate entirely.

If I'm not mistaken, in MQTT we are not able to get the status of the camera to detect the error.

It would be great to be able to detect the error automatically through MQTT, and also restart only this camera through MQTT instead of entire Frigate, what do you think ?

Thanks

Frigate version 0.14.1-f4f3cfa on Debian 12 with 5 Tapo cameras and Coral usb.

**Comment by NickM-27** [comment, marked as answer]
Restarting is really not a solution, this is likely a problem that should be fixed in the config

> If I'm not mistaken, in MQTT we are not able to get the status of the camera to detect the error.

That is incorrect, camera_fps = 0 represents this error

**Reply by spyjo** [reply]
Thank you for your answer

Indeed I missed the "camera_fps" value, I will update my scripts to retrieve it :)

For the random crash of one of cameras, I'm not sure it's due to the config, as it can work for days before being in error. But may be I miss a better "restart automatically the process after crash" config value somewhere ?

It seems sometimes go2rtc get an invalid rtsp feed (due to camera rebooting for update, or loosing wifi few seconds, or other), and is not able to catch up again the video feed and stays crashed. And it's not a particular camera, it's totally random.

Here is the latest log of the current crashed camera:
`error="streams: dial tcp 192.168.1.93:554: i/o timeout, exec: rtsp://127.0.0.1:8554/devant_garage?video&audio: Invalid data found when processing input\n" stream=devant_garage
`
but opening the live feed on Frigate is working great.


Here is my config:

```
mqtt:
  enabled: true
  user: ***
  password: ***
  host: 192.168.1.18
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    devant_garage:
      - rtsp://user:***@192.168.1.93:554/stream1
      - ffmpeg:devant_garage#video=copy#audio=copy#audio=aac
    devant_garage_sd:
      - rtsp://user:***@192.168.1.93:554/stream2
    derriere_garage:
      - rtsp://user:***@192.168.1.94:554/stream1
      - ffmpeg:derriere_garage#video=copy#audio=copy#audio=aac
    derriere_garage_sd:
      - rtsp://user:***@192.168.1.94:554/stream2
    interieur_garage:
      - rtsp://user:***@192.168.1.95:554/stream1
      - ffmpeg:interieur_garage#video=copy#audio=copy#audio=aac
    interieur_garage_sd:
      - rtsp://user:***@192.168.1.95:554/stream2
    salon:
      - rtsp://user:***@192.168.1.96:554/stream1
      - ffmpeg:salon#video=copy#audio=copy#audio=aac
    salon_sd:
      - rtsp://user:***@192.168.1.96:554/stream2
    bureau:
      - rtsp://user:***@192.168.1.35:554/stream1
      - ffmpeg:bureau#video=copy#audio=copy#audio=aac
    bureau_sd:
      - rtsp://user:***@192.168.1.35:554/stream2

cameras:
  devant_garage:
    ui:
      order: 1
    onvif:
      host: 192.168.1.93
      port: 2020
      user: user
      password: ***
      ignore_time_mismatch: true
      autotracking:
        enabled: False
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/devant_garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/devant_garage_sd
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      #- car
        - bicycle
        - motorcycle
      mask:
        - 614,0,595,147,403,75,421,0
    motion:
      mask:
        - 0.934,0,0.9,0.391,0.63,0.208,0.658,0
        - 0.357,0,0.355,0.053,0,0.051,0.002,0
    detect:
      width: 640
      height: 360
      fps: 15
      annotation_offset: -1000
      max_disappeared: 300

  derriere_garage:
    ui:
      order: 3
    onvif:
      host: 192.168.1.94
      port: 2020
      user: user
      password: ***
      ignore_time_mismatch: true
      autotracking:
        enabled: False
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/derriere_garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/derriere_garage_sd
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    motion:
      mask:
        - 0.357,0,0.356,0.056,0,0.053,0.002,0
        - 0.392,0,0.396,0.225,0.781,1,0.956,0
    detect:
      width: 640
      height: 360
      fps: 15
      #annotation_offset: -1000
      max_disappeared: 300

  interieur_garage:
    ui:
      order: 2
    onvif:
      host: 192.168.1.95
      port: 2020
      user: user
      password: ***
      ignore_time_mismatch: true
      autotracking:
        enabled: False
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/interieur_garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/interieur_garage_sd
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
    motion:
      mask: 0.356,0,0.357,0.053,0,0.053,0.002,0
    detect:
      width: 640
      height: 360
      fps: 15
      #annotation_offset: -1000
      max_disappeared: 300

  salon:
    ui:
      order: 4
    onvif:
      host: 192.168.1.96
      port: 2020
      user: user
      password: ***
      ignore_time_mismatch: true
      autotracking:
        enabled: False
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/salon
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/salon_sd
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    motion:
      mask: 0.356,0,0.356,0.053,0,0.053,0.002,0
    detect:
      width: 640
      height: 360
      fps: 15
      #annotation_offset: -1000
      max_disappeared: 300

  bureau:
    ui:
      order: 5
    onvif:
      host: 192.168.1.35
      port: 2020
      user: user
      password: ***
      ignore_time_mismatch: true
      autotracking:
        enabled: False
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bureau
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bureau_sd
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    motion:
      mask: 0.356,0,0.356,0.053,0,0.053,0.002,0
    detect:
      width: 640
      height: 360
      fps: 15
      #annotation_offset: -1000
      max_disappeared: 300

record:
  enabled: true
  retain:
    days: 0
    mode: all
  preview:
    quality: high
  events:
    pre_capture: 10
    post_capture: 20
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 30
  quality: 80

ui:
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%Y/%m/%d %H:%M:%S'

version: 0.14

```
