### DISCUSSION TITLE
How to increase cache

### DISCUSSION THREAD

**Discussion by balajeek** [blakeblackshear/frigate#1424] [Ask A Question]
Frigate latest version running on docker on ubuntu intel core i5
I have 3 1080p camera's and all seem to be working fine and clips are getting stored.
But i see this error message in the log that repeats every min.

frigate.events                 WARNING : Proactively cleaning up the cache...
frigate.events                 WARNING : More than 90% of the cache is used.
frigate.events                 WARNING : Consider increasing space available at /tmp/cache or reducing max_seconds in your clips config.

I tried to change tempfs to 600m in the docker-compose, that did not help.

I tried to change the following in the config.yml and that did not help either.
  max_seconds: 200
  tmpfs_cache_size: 256m

What does this error mean? and What should be fixing.

Thank you.

**Comment by lawm** [comment]
Compare your docker compose file with
https://blakeblackshear.github.io/frigate/installation#docker
```
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
