### DISCUSSION TITLE
Can I add a timestamp to a video stream I am already encoding?

### DISCUSSION THREAD

**Discussion by CancunManny** [blakeblackshear/frigate#14259] [Ask A Question]
So under my Go2rtc streams I have this:
```
mjpeg_cam: ffmpeg:http://10.XX.XX:XX:8080/#video=h264#hardware
```

And under the camera I have:
```
  mjpeg_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam
          roles:
            - detect
 ```
 I did some reading and they say adding timestamps is not recommended since Frigate would have to re-encode the stream, but I am already re encoding the stream so adding the timestamp shouldn't  add much overhead to what I am already doing.
 
 This is what NickM mentioned on a similar question:

> Adding timestamps to a recording is very expensive operation as it requires decoding the frames, inserting the timestamp, then re-encoding. Most cameras support this so that is the recommended path. If not, then you can use the ffmpeg -> output_args to include a timestamp https://superuser.com/questions/1491264/ffmpeg-filter-to-add-timestamp-on-video

I did visit the link, but can't seem to figure out where/how I would put the code they are talking about.
