### DISCUSSION TITLE
No recording found, but thumb nail has the recording.  What am I missing/

### DISCUSSION THREAD

**Discussion by CancunManny** [blakeblackshear/frigate#14258] [Ask A Question] [answered]
Pictures might tell the story better.
![image](https://github.com/user-attachments/assets/309e606a-4f4d-4931-a6e9-7d5cc5910dde)
That is my videos page view.  The first picture on the top left shows an orange car.  When I hover mouse over it, it shows the car pulling in.

![image](https://github.com/user-attachments/assets/ef4ec6eb-25e4-4050-88c4-804f1812c01d)

When I click on the video to view the full clip I get to see this for a second

![image](https://github.com/user-attachments/assets/e133c613-b84b-4fc4-8f0f-2ec54a4e5d0b)
 
and after a second or two I get a static image

![image](https://github.com/user-attachments/assets/ae8826da-468a-4691-9c3a-2a1068708d4b)

I have that camera with detect only, no record.  Is that the problem?  But where is it getting the clip that shows on the thumbnail then?

**Comment by hawkeye217** [comment]
What is your frigate config?

**Reply by CancunManny** [reply]
So I had read frigate docs in the past, but it seemed it was in chinese cause I couldn't make much sense of what I was reading.  I think I am starting to piece things together now.  I just modified my record config section.

This is what I had:
```
record:
  enabled: true
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 14
      mode: active_objects
    objects:
      - person
      - bird
      - cat
      - dog
 ```
I had no parameters for record (motion based), so it was only recording detected objects

my new record config looks like this;

```
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 14
      mode: active_objects
    objects:
      - person
      - bird
      - cat
      - dog
      - car
 ```

If I am understanding correctly, only the two cameras that have roles of detect and record are the ones that will record all motion for 7 days, while the other 2 cameras that have role detect only, will keep only recording when an object is detected.  Am I right?

And finally started playing with masks and zones.  One of the cameras that has role record has a mask on a tree.  I assume when the tree moves it will ignore it and not record at all, but if something else moves it will record right?

I am guessing the thumb nail showing the movement is sortha like a glitch.  It pulled recording info to create the thumbnail but didn't actually create the recording since that camera didn't have a role to record.  Am I right on this assumption as well?
