### DISCUSSION TITLE
Confirm ESP 32 Cam setup as a MJPEG stream

### DISCUSSION THREAD

**Discussion by CancunManny** [blakeblackshear/frigate#14255] [Ask A Question] [answered]
So I tried a few things to set up an ESP32 Cam and haven't been able to.  Figured I would start with basics.

The frigate docs suggest this configuration:
```
go2rtc:
  streams:
    mjpeg_cam: "ffmpeg:{your_mjpeg_stream_url}#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.

cameras:
  ...
  mjpeg_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam
          roles:
            - detect
            - record
```
According to the EPS32 webserver documentation my camera URL should be http://10.xx.xx.xx:8080/  So what is the correct way to put in my URL on the code?

```
mjpeg_cam: "ffmpeg:{http://10.xx.xx.xx:8080/}#video=h264#hardware"

```
Would that be the correct way?  Do I take the last / out?  The brackets stay?

Now as far as #hardware does something else need to be configured for #hardware to work?

This is part of my config file

```
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

record:
  enabled: true
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 14
      mode: active_objects
    objects:
      - person
      - bird
      - cat
      - dog
```

Since the record is not tied to each camera, does it mean that is a global setting?  If I wanted a camera to record with different settings would if create a conflict if I just add record arguments under the camera?

For example

**Comment by NickM-27** [comment]
There should be no brackets, the brackets signify you have to enter that part 

Yes, you can set record settings for each camera

**Reply by CancunManny** [reply]
ok, so the correct way would this, with the last / in place?

```
mjpeg_cam: "ffmpeg: http://10.xx.xx.xx:8080/#video=h264#hardware"
```
There is a space between the colon after cam and the " before the http, or should there be no space there?

How about the #hardware part.  Is there something else I have to set up to get that hardware to work, or it is already taken care of?

**Reply by NickM-27** [reply]
No there should be no spaces inside of the "", the last / shouldn't matter either way. 

Try to get it working then add #hardware later

**Reply by CancunManny** [reply, marked as answer]
Great, got it working!

The code should look something like this
```
go2rtc:
  streams:
    mjpeg_cam: "ffmpeg:http://XX.XX.XX.XX}#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.

cameras:
  ...
  mjpeg_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam
          roles:
            - detect
            - record
```
Seem both of these would work "ffmpeg:http://..... or "ffmpeg: http://.....  but I assume the norm is no spaces in quote marks, which is the way I left it.

Also seems the #hardware works on its own, as it didn't give me any errors and I don't think i have any hardware setup other than preset vappi.

Thanks again Nick.  Last week was trying to figure this out, spent over 5 hours on it, until I eventually crashed frigate.
