### DISCUSSION TITLE
[Support]: Randomly Artifacted image on multiple cameras

### DISCUSSION THREAD

**Discussion by makerwolf** [blakeblackshear/frigate#14277] [General Support] [answered]
### Describe the problem you are having

Since Frigate 0.14 I'm sometimes having issues viewing streams in the browser (Safai and Chrome alike, multiple different cameras, all Mac OS)

Sometimes the stream looks like this:
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/f952adec-c43b-42ab-8db9-a3bb3d8e7e10">

Any idea what this could be and maybe even a possible fix? 

It sometimes happens, sometimes not, sometimes this camera, then the other. Sometimes in the live stream, then the recording. But it seem the recording itself is unaffected. I'm really having trouble reproducing the behaviour. 

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Safari 18.0.1, Chrome 129.0.6668.90

### Frigate config file

```yaml
-
```

### Relevant Frigate log output

```shell
nothing
```

### Relevant go2rtc log output

```shell
nothing
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
-
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

multiple (reolink, tapo, noname)

**Comment by NickM-27** [comment]
If it happens in the recording then it's nothing Frigate is doing as that's copied directly from the camera

**Comment by makerwolf** [comment]
It does not happen in the recording, as I have indicated.

**Reply by NickM-27** [reply]
> sometimes this camera, then the other. Sometimes in the live stream, then the recording

That implies it does happen in the recording

**Reply by makerwolf** [reply]
the recording itself is fine, it's only in the playback of the recording in the browser. And only sometimes. That's the weird part. I am absolutely unable to reproduce it if I wanted to. It either happens, or not.

**Comment by hawkeye217** [comment]
What is your frigate config and what cameras are specifically affected?

**Reply by makerwolf** [reply]
I would love to give you specific how to steps to reproduce the issue with make model and config, however it does not happen specific for cameras. It has happened on every camera I use (5 different models, 4 different brands) seemingly randomly. It also sometimes happens in the frigate card in home assistant, but as I said: sometimes. I've had it ever since 0.14 was released and I just never posted because I am unable to reproduce it. As of right now it does not happen, all cameras work just fine. There is also nothing in the logs. Also never seen this kind of artifacting before. 🤯🤷‍♂️

here is the config: 
<details>
  <summary>config:</summary>

```
database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://#

mqtt:
  host: #
  user: #
  password: #

birdseye:
  enabled: true
  mode: continuous

record:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    Camera1:
      - rtsp://#:#@IP:554/h264Preview_01_main
    Camera190:
      - ffmpeg:Camera1#video=h264#rotate=90#hardware
    Camera1_sub:
      - rtsp://#:#@IP:554/h264Preview_01_sub
    Camera1_sub90:
      - ffmpeg:Camera1_sub#video=h264#rotate=90#hardware
    Camera2:
      - ffmpeg:rtsp://#:#@IP:554/stream1#video=copy#audio=copy#audio=aac#hardware
    Camera2_sub:
      - ffmpeg:rtsp://#:#@IP9:554/stream2#hardware
    Camera3:
      - ffmpeg:rtsp://#:#@IP:554/stream1#video=copy#audio=copy#audio=aac#hardware
    Camera3_sub:
      - ffmpeg:rtsp://#:#@IP:554/stream2#hardware
    Camera4:
      - rtsp://#:#@IP:554/11
    Camera4_sub:
      - rtsp://#:#@IP:554/12
    Camera5:
      - rtsp://#:#@IP6:554/11
    Camera5_sub:
      - rtsp://#:#@1IP:554/12

cameras:
  Camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera2_sub
          roles:
            - detect
    objects:
      track:
        - person
        - package
      filters:
        person:
          threshold: 0.82
          min_score: 0.7
          mask: 0.308,0.892,0,0.469,0,0,0.353,0,0.491,0.358
    motion:
      mask:
        - 204,277,0,114,0,0,226,0,314,129
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 10
        retain:
          default: 31
          mode: active_objects
      retain:
        days: 4
        mode: all
    snapshots:
      enabled: true
  Camera3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera3
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera3_sub
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.9
          min_score: 0.8
          mask: []
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 10
        retain:
          default: 15
          mode: active_objects
      retain:
        days: 4
        mode: all
    snapshots:
      enabled: true
  Camera190:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera190
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera1_sub90
          roles:
            - detect
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.85
          min_score: 0.65
          mask: []
    motion:
      mask: 
        0,0.402,0.318,0.285,0.634,0.262,0.515,0.388,0.666,0.379,1,0.32,0.997,0.003,0.001,-0.001,0.001,-0.001
    detect:
      enabled: true
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 0
        retain:
          default: 3
          mode: active_objects
      retain:
        days: 1
        mode: all
    snapshots:
      enabled: true
  Camera4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera4
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera4_sub
          roles:
            - detect
    onvif:
      host: IP
      port: 8080
      user: #
      password: #
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.9
          min_score: 0.85
          mask: []
    motion:
      mask: []
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 10
        retain:
          default: 7
          mode: active_objects
      retain:
        days: 1
        mode: all
    snapshots:
      enabled: true
  Camera5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera5
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera5_sub
          roles:
            - detect
    onvif:
      host: IP
      port: 8080
      user: #
      password: #
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.9
          min_score: 0.85
          mask: []
    motion:
      mask: []
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 10
        retain:
          default: 7
          mode: active_objects
      retain:
        days: 1
        mode: all
    snapshots:
      enabled: true

version: 0.14
camera_groups:
  Camera5:
    order: 1
    icon: LuTrees
    cameras:
      - Camera5
      - Camera4
  Camera2:
    order: 2
    icon: LuWarehouse
    cameras:
      - Camera2
      - Camera3
      - Camera190

```

</details>

**Reply by hawkeye217** [reply]
Thanks. Let's focus on a specific camera, `Camera2`. What's the resolution you have set for the main stream and substream on that camera?

**Reply by makerwolf** [reply]
That's a Tapo C320WS, Resolution is 2560*1440, and the substream is 640x360.

**Reply by hawkeye217** [reply]
Great. Can you provide the output of `http://frigate_ip:5000/api/ffprobe?paths=camera.Camera2`?

**Reply by makerwolf** [reply]
Hmm, I'm only getting `Invalid request`, regardless which camera, and also for other API endpoints ...

**Reply by hawkeye217** [reply]
Ah, you're running the HA addon. You'll need to enable the port in the addon configuration.

**Reply by makerwolf** [reply]
Phew, that was a bit tricky, had to change the port to 5001 or frigate wouldn't start, because something else is already on 5000 ...

`[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC (Advanced Audio Coding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":360,"width":640}]}}]`

fwiw, right now there is two cameras hicupping on the live stream, and that's their output: 
`[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/2","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/2","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":448,"width":800}]}}]`

`[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":1080,"width":1920}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":352,"width":640}]}}]`

On both those cameras, If I watch the live output, it has a diagonal and color shift in the live feed. If I watch the recording it's just fine.

**Reply by hawkeye217** [reply]
So here is your issue:

`"height":352,"width":640}`
and
`"height":448,"width":800}]`

These two cameras that are currenty hiccuping have non-standard aspect ratios. You need to explicitly set the `detect` width and height if this is the case. Otherwise, you'll see the artifacting you're seeing when Frigate is using the jsmpeg player.

See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Usage question 15.

**Reply by makerwolf** [reply]
hmm, I have now added a detect section with the resolutions as per the ffprobe output, but the problem remains the same :(
These 3 lines just below the snapshots section, double checked resolutions match the output. 

```
    snapshots:
      enabled: true
    detect:
      width: 640
      height: 352
```

**Reply by hawkeye217** [reply, marked as answer]
Does it improve if you explicitly set it to:
```
    detect:
      width: 640
      height: 360
```

**Reply by makerwolf** [reply]
Indeed, this fixed the issue. Interesting, 352 is divisible by 4 ... this also fixed another camera. Now I only have one more camera left, which is a little bit special, it is 4k, loads fine every time, but after 5 seconds I get a spinning wheel, and it switches to the artifacted image with the diagnoal again. This is the ffprobe output: 
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"299/12","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":3840,"width":2160},{"avg_frame_rate":"0/0","codec_long_name":"AAC (Advanced Audio Coding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","height":640,"width":360}]}}]

(I'm also failing to get audio recording on that camera, but that's another issue)

**Reply by hawkeye217** [reply]
Glad to hear it's working for most of your cameras.

What's the name of the camera in your config that is still failing?

**Reply by makerwolf** [reply]
It's a Reolink CX810, Camera1 in the config, rotated by 90 degree in frigate.

**Reply by hawkeye217** [reply]
If it's rotated, did you try swapping width/height in the detect section?

```
    detect:
      width: 360
      height: 640
```

**Reply by makerwolf** [reply]
hmm, no I did not, but would that not seriously mess up detection?

**Reply by hawkeye217** [reply]
It depends what you're trying to do with your streams. If you watch Frigate's debug view, does the frame look distorted?

**Reply by makerwolf** [reply]
Well just the usual security camera thing in frigate. Record the stream and detect people entering my yard. 
The frame does not look distorted at all in debug view. Everything works normally there.

**Reply by hawkeye217** [reply]
Shouldn't be an issue then for you to set detect as width: 360 and height: 640

**Reply by makerwolf** [reply]
Uh ah wait, I misunderstood what you meant when you said swap width and height, because it is set like this in the first place: 
```
    detect:
      enabled: true
      width: 360
      height: 640
 ```

I thought you meant swap to have them set in landscape mode, which not surprisingly messes things up bigger than the diagonal artifact ...
