### DISCUSSION TITLE
Question about frigate and HA networking storage

### DISCUSSION THREAD

**Discussion by ovizii** [blakeblackshear/frigate#14281] [Ask A Question]
I have it working, but there seems to have been an issue recently, where the samba share where frigate saves its media "broke" or became unavailable.

The result seems to be that frigate then simply saves into the folder where the share used to be mounted.
After a period of time, I notice the problem but now I can't mount the network storage as it is not empty, meaning I have to stop frigate, move the content of frigate's media folder to the share, then connect the share and restart frigate.

Currently, I have set up an automation to inform me as soon as the share becomes disconnected with this binary sensor:

```
# pve01 share on /media/frigate mounted
  - sensor:
      name: SMB frigate mounted
      command: "df -h | grep -q '/media/frigate' && echo '1' || echo '0'"
      value_template: '{{ value }}'
      scan_interval: 60
```

The question boils down to is there a better way to prevent frigate from saving media when the network storage is unmounted?
