### DISCUSSION TITLE
zones support in 0.14 Frigate

### DISCUSSION THREAD

**Discussion by bend94** [blakeblackshear/frigate#14282] [General Support]
### Describe the problem you are having

Hi all
In the previous version 0.13, zones was defined in the frigate.yml file with the help of the GUI to get the points related to the zone.
Then a binary_sensor.zone xxx was defined in homeassistant.

In the new version, i can define a zone directly in the GUI.
But what about the definition in homeassistant ?
i can't see my new zone in the "Developpment tools" and "states" part ?

Thx for your support

### Version

0.14

### Frigate config file

```yaml
logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.stream: debug
#ui:
#  use_experimental: false
mqtt:
  host: 192.168.1.22
  port: 1883
  topic_prefix: frigate
  user: umqtt
  password: pass4UMQTT


detectors:
  coral:
    type: edgetpu
    device: usb
  #cpu1:
  #  type: cpu
#    num_threads: 4
  #cpu2:
  #  type: cpu

go2rtc:
  streams:
    devant:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.20:554/Streaming/Channels/101/
    devant_sub:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.20:554/Streaming/Channels/102/
    interphone:
      - ffmpeg:rtsp://BLABLABLA:BLABLABLA@192.168.1.13:554/mpeg/media.amp
    inter:
      - ffmpeg:rtsp://BLABLABLA:BLABLABLA@192.168.1.13:554/mpeg/media.amp
    terrasse_sub:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.22:554/Streaming/Channels/102/
    terrasse:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.22:554/Streaming/Channels/101/
    salon_sub:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.21:554/Streaming/Channels/102/
    salon:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.21:554/Streaming/Channels/101/
    cuisine_sub:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.23:554/Streaming/Channels/102/
    cuisine:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.23:554/Streaming/Channels/101/
    bureau_sub:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.25:554/Streaming/Channels/102/
    bureau:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.25:554/Streaming/Channels/101/
    couloir_sub:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.24:554/Streaming/Channels/102/
    couloir:
      - rtsp://BLABLABLA:BLABLABLA@192.168.1.24:554/Streaming/Channels/101/


  snapshots:
    timestamp: true
    bounding_box: true
    quality: 100

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

birdseye:
  enabled: true
#  width: 896
#  height: 672
  width: 1920
  height: 1080

  quality: 1
  mode: continuous


cameras:
  terrasse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrasse_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/terrasse
          #input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
        #- dog
        #- cat
    motion:
      mask:
        - 287,159,298,33,320,0,320,240,252,240
        - 0,0,299,0,172,25,153,39,60,65,0,109
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      laterrasse:
        coordinates: 
          0.658,0.203,0.573,0.215,0.399,0.267,0.26,0.311,0.105,0.444,0.098,0.57,0.007,0.82,0.008,0.961,0.008,1,0.777,0.995,0.884,0.663,0.899,0.493,0.911,0.35,0.909,0.273,0.84,0.205,0.774,0.182,0.715,0.166
        loitering_time: 0
  cuisine:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cuisine_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cuisine
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
        - 162,159,159,0,320,0,320,240,83,240,161,240
        - 0,0,113,0,105,45,72,73,0,109
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
  salon:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/salon_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/salon
          roles:
            - record
    detect:
      width: 640 #320
      height: 480 #240
      fps: 4
    objects:
      track:
        - person
      #  - dog
      #  - cat
    motion:
      threshold: 40
      mask:
        - 640,480,640,0,555,0,554,63,496,480
        - 359,0,342,0,217,0,117,0,0,0,0,350,98,260,214,212,212,145,213,52,557,59,550,0
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_salon_alarme:
        coordinates: 13,468,12,243,72,211,210,153,210,77,339,74,375,146,475,158,483,57,556,69,502,468
  bureau:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bureau_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/bureau
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0,320,0,320,62,320,173,217,135,170,114,132,110,157,240,0,240
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
  couloir:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/couloir_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/couloir
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
        - 320,0,0,0,0,83,108,47,255,49,320,240
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
  interphone:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/inter
          #input_args: preset-rpi-64-h264
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/inter
          #input_args: preset-rpi-64-h264
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - horse
        - bicycle
        - motorcycle
      filters:
        car:
          mask:
            - 0,0,320,0,320,107,0,109
        person:
          mask:
            - 0,0,320,0,320,107,0,109
        dog:
          mask:
            - 0,0,320,0,320,107,0,109
        cat:
          mask:
            - 0,0,320,0,320,107,0,109
    motion:
      mask:
        - 0,0,192,0,320,0,320,138,170,151,50,142,0,132
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      quality: 100
      retain:
        default: 5
        mode: motion
  devant:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/devant_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/devant
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 2
    objects:
      track:
        - person
    motion:
      mask:
        - 62,480,24,305,85,243,164,196,302,193,547,202,640,263,640,0,159,0,0,0,0,112,0,240,0,480
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      required_zones:
        - zone_devant_alarme
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_devant_alarme:
        coordinates: 130,209,22,229,64,470,632,472,629,232,300,207
    review:
      alerts:
        required_zones:
          - zone_devant_alarme
version: 0.14
camera_groups:
  dehors:
    order: 1
    icon: LuSprout
    cameras:
      - terrasse
      - interphone
      - devant
      - cuisine
      - bureau
  maison:
    order: 2
    icon: LuWarehouse
    cameras:
      - salon
      - couloir
  Birdeye:
    order: 3
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
2024-10-11 13:50:43.282203486  [INFO] Preparing Frigate...
2024-10-11 13:50:43.441320194  [INFO] Starting Frigate...
2024-10-11 13:50:46.544544763  [2024-10-11 15:50:46] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-11 13:50:46.544666595  [2024-10-11 15:50:46] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-10-11 13:50:46.544730262  [2024-10-11 15:50:46] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-11 13:50:46.619837644  [2024-10-11 15:50:46] frigate.util.config            INFO    : frigate config does not need migration...
```

### Relevant go2rtc log output

```shell
2024-10-11 13:50:43.375508177  [INFO] Preparing new go2rtc config...
2024-10-11 13:50:43.427716301  [INFO] Got IP address from supervisor: 192.168.1.22
2024-10-11 13:50:43.469491844  [INFO] Got WebRTC port from supervisor: 8555
2024-10-11 13:50:44.268282638  [INFO] Starting go2rtc...
2024-10-11 13:50:44.411022785  15:50:44.410 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2
2024-10-11 13:50:44.411028674  15:50:44.410 INF config path=/dev/shm/go2rtc.yaml
2024-10-11 13:50:44.411748169  15:50:44.411 INF [api] listen addr=:1984
2024-10-11 13:50:44.412045037  15:50:44.411 INF [rtsp] listen addr=:8554
2024-10-11 13:50:44.412265129  15:50:44.412 INF [webrtc] listen addr=:8555/tcp
2024-10-11 13:50:53.283907024  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
..
```

### Frigate stats

```json
..
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
..
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision

### Screenshots of the Frigate UI's System metrics pages

..

### Any other information that may be helpful

;.
