### DISCUSSION TITLE
[Support]: packages not getting detected on my doorbell

### DISCUSSION THREAD

**Discussion by JoshuaSeidel** [blakeblackshear/frigate#14291] [General Support] [answered]
### Describe the problem you are having

Anytime any kind of package is left on my doorstep my camera never picks it up. I’m using frigate plus

### Version

0.15

### What browser(s) are you using?

Chrome latest

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: frigate_mqtt
  password: password
  host: 192.168.7.83

ffmpeg:
  hwaccel_args: preset-nvidia-h264
 # input_args: preset-rtsp-stream
  #output_args:
   # record: preset-record-generic-audio-copy

cameras:
  steps_cam: # <------ Name the camera
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/steps_cam # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/steps_cam_sub
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
    detect:
      width: 640
      height: 360
      fps: 5
    review:
      detections:
        labels:
          - dog
          - person
        required_zones: steps
    zones:
      steps:
        coordinates: 0.454,0,0.215,0.968,0.866,0.994,0.62,0.003
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.723,0.938,0.974,0.933,0.976,0.98,0.723,0.979
  pet_cam:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pet_cam # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pet_cam_sub
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - dog
        - person
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    review:
      detections:
        labels:
          - dog
          - person

  doorbell:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: doorbell
    objects:
      track:
        - dog
        - person
        - cat
        - fedex
        - ups
        - amazon
        - face
        - package
      filters:
        car:
          mask:
            - 0.631,0.673,0.679,0.535,0.844,0.531,0.825,0.677
            - 0.491,0.518,0.552,0.513,0.562,0.593,0.499,0.597
    detect:
      width: 640
      height: 480
      fps: 5
    review:
      detections:
        labels:
          - dog
          - person
        required_zones:
          - sidewalk
          - Porch
      alerts:
        required_zones:
          - Porch
          - sidewalk
    zones:
      Porch:
        coordinates: 
          0.381,0.999,0.384,0.961,0.47,0.969,0.473,0.908,0.723,0.866,0.73,0.874,0.875,0.801,0.999,0.881,0.999,0.999
        loitering_time: 0
        objects:
          - package
          - person
          - dog
          - cat
        inertia: 2
      sidewalk:
        coordinates: 
          0.57,0.897,0.584,0.791,0.624,0.758,0.67,0.74,0.706,0.724,0.698,0.78,0.696,0.82,0.694,0.866
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 2
    motion: {}
  driveway:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - car
        - motorcycle
        - cat
        - bicycle
        - fedex
        - ups
        - amazon
        - face
        - package
        - license_plate
      filters:
        car:
          mask: 0.432,0.009,0.454,0.112,0.544,0.112,0.56,0
    detect:
      width: 896
      height: 512
      fps: 5
    review:
      detections:
        labels:
          - dog
          - person
          - car
          - motorcycle
        required_zones:
          - front-grass
          - parking
      alerts:
        required_zones:
          - parking
          - front-grass
    onvif:
      host: 192.168.9.4
      port: 8000
      user: nvr
      password: password
    #  autotracking:
    #    enabled: false
    #    calibrate_on_startup: false
    #    zooming: absolute
    #    zoom_factor: 0.3
    #    track:
    #      - person
    #      - car
    #    return_preset: home
    #    timeout: 10
    #    required_zones:
    #      - complete
        #required_zones: complete
      #alerts:
        #required_zones: leanna-parking
     # alerts:
      #  required_zones: parking
    zones:
      parking:
        coordinates: 0,0.653,0.117,0.519,0.27,0.363,0.616,0.456,0.659,0.471,0.589,1,0,1
        inertia: 5
        loitering_time: 0
        objects:
          - motorcycle
          - car
          - person
      front-grass:
        coordinates: 0.67,0.419,1,0.526,1,1,0.568,0.993
        loitering_time: 0
        objects:
          - dog
          - cat
          - person
        inertia: 3
    motion:
      threshold: 40
      contour_area: 15
      improve_contrast: 'true'
      lightning_threshold: 1.0
      mask: 0.583,0.933,0.988,0.931,0.989,0.971,0.585,0.974
  backyard:
    enabled: true
    audio:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - dog
        - person
        - cat
        - face
        - package
    detect:
      width: 1536
      height: 432
      fps: 5
    review:
      alerts:
        required_zones:
          - yard
          - patio
          - back-steps
      detections:
        required_zones:
          - back-steps
          - yard
          - patio
    motion: {}
    zones:
      patio:
        coordinates: 0.18,0.997,0.295,0.53,0.556,0.576,0.632,0.567,0.748,0.998
        loitering_time: 0
        objects:
          - dog
          - package
          - person
          - cat
      yard:
        coordinates: 
          0.754,0.995,0.868,1,0.814,0.86,0.696,0.548,0.654,0.434,0.623,0.313,0.587,0.31,0.514,0.191,0.448,0.174,0.412,0.156,0.406,0.03,0.347,0.039,0.341,0.164,0.182,0.43,0,0.73,0.058,0.946,0.233,0.5,0.478,0.555,0.631,0.56
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 3
      back-steps:
        coordinates: 0.041,0.99,0.234,0.505,0.291,0.529,0.178,0.997
        loitering_time: 0
        objects:
          - person
          - dog
version: 0.14

go2rtc:
  streams:
    steps_cam:
      - rtsp://wb:cCa3gT-password@wyze-bridge:8554/steps-cam
    steps_cam_sub:
      - rtsp://wb:cCa3gT-password@wyze-bridge:8554/steps-cam-sub
    pet_cam:
      - rtsp://taponvr:password@192.168.9.30:554/stream1
    pet_cam_sub:
      - rtsp://taponvr:password@192.168.9.30:554/stream2
    doorbell:
      - rtsp://nvr:password@192.168.9.127:554/Preview_01_main
    doorbell_sub:
      - rtsp://nvr:password@192.168.9.127:554/Preview_01_sub
    driveway:
      - rtsp://nvr:password@192.168.9.4:554/Preview_01_main
    driveway_sub:
      - rtsp://nvr:password@192.168.9.4:554/Preview_01_sub
    backyard:
      - rtsp://admin:password@192.168.9.171:554/Preview_01_main
    backyard_sub:
      - rtsp://admin:password@192.168.9.171:554/Preview_01_sub
  webrtc:
    candidates:
      - 192.168.9.144:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

detectors:
  coral:
    type: edgetpu
    device: pci

#detectors:
 # tensorrt:
  #  type: tensorrt
   # device: 0

model:
  path: plus://api-key

#model:
 # path: /config/model_cache/tensorrt/yolov7-320.trt
 # input_tensor: nchw
 # input_pixel_format: rgb
 # width: 320
 # height: 320

review:
  alerts:
    labels:
      - person
      - face
      - dog
      - car
      - ups
      - fedex
      - amazon
      - package
  detections:
    labels:
      - person
      - dog
      - car
      - ups
      - face
      - fedex
      - amazon
      - package

record:
  enabled: true
  sync_recordings: false
  retain:
    days: 14
    mode: motion

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 800
  height: 480
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  mode: continuous #motion #objects

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

tls:
  enabled: true

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

# Include all cameras by default in Birdseye view
camera_groups:
  Front:
    order: 1
    icon: LuArrowBigUp
    cameras:
      - doorbell
      - driveway
```

### Relevant Frigate log output

```shell
N/a
```

### Relevant go2rtc log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink white doorbell pie

### Any other information that may be helpful

![IMG_3847](https://github.com/user-attachments/assets/cf2b896c-ab93-4a95-8a55-db7ad825fd48)
![IMG_3807](https://github.com/user-attachments/assets/dc24145d-6ab7-46ec-a943-0fcc82305bea)
