### DISCUSSION TITLE
Frigate stopping again and again due to this error.

### DISCUSSION THREAD

**Discussion by aayush-eatclub** [blakeblackshear/frigate#14306] [Ask A Question] [answered]
I am running frigate on my linux system. But after some hours , it stops automatically throwing this error.
I am unable to figure out the issue causing this error.
Please let me know how to fix this.
<img width="1318" alt="image" src="https://github.com/user-attachments/assets/ca395a71-8187-47af-a388-0fbf32cda5fc">

**Comment by hawkeye217** [comment]
We'll need to see the full log and your Frigate config in order to be able to help.

**Comment by aayush-eatclub** [comment]
There are 2 types of error logs.
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/02dff07a-81cf-431f-825e-e2b46a3ae17c">

Another one which I am more concerned about is :
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/19838a61-22a9-4d79-a0d6-d2479deb1b3f">


This is my docker-compose.yml file
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "4096mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /home/outletmanager/outletvideocam:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5001:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
        resources:
            limits:
              cpus: 2
              memory: 2000M
            reservations:
              cpus: 1
              memory: 1500M
```

- And here is my config file.
```
auth:
  enabled: false
birdseye:
  enabled: false
cameras:
  cam_31:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.31/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_34:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.34/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_35:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.35/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_36:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.36/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_38:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.38/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_39:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.39/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_40:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.40/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_42:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.42/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_43:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.43/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_44:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@123@192.168.9.44/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
detect:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
motion:
  enabled: false
mqtt:
  enabled: false
record:
  enabled: true
  retain:
    days: 1
    mode: all
  sync_recordings: true
tls:
  enabled: false
version: 0.14
```
