### DISCUSSION TITLE
Unable to view recordings on h.265 camera

### DISCUSSION THREAD

**Discussion by yourpalfranc** [blakeblackshear/frigate#14309] [Ask A Question]
I'm a new Frigate user (evaluating for a move from BI) and I have an installation that has been working well for a few weeks. I have 3 Reolink RLC-811A cameras that are my main outdoor detection cameras. They were initially very easy to set up in Frigate by only copying the path from my BI installation. They seem to be recording and detecting motion in Frigate very well, but will not play back the recorded video. The only thing that displays is a still image from the camera with a spinning arrow. My research seemed to indicate that this might be an issue with the RLC-811A supporting h.265. The Frigate documentation FAQ that appears to specifically address this topic indicates that transcoding/restreaming should solve the issue. So, I've set that up on one camera and the restream seem to work fine for display, but I'm still not able to playback the video...still a spinning arrow. What have I missed.

Here's a bit of my config.yaml (with credentials edited) to illustrate. Also, confirmed port 8554 enabled by docker-compose:

********************************
  retain:
    default: 30

go2rtc:
  streams:
    driveway:
      - rtsp://admin:password@ip/h264Preview_01_main
    driveway_sub:
      - rtsp://admin:password@ip/h264Preview_01_sub

cameras:
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
*******************************************

**Comment by hawkeye217** [comment]
H.265 requires proper browser support. Some browsers explicitly don't support H.265 for patent, monetary, and political reasons. What browser are you using?

**Reply by yourpalfranc** [reply]
After setting up the restream, I only tried it in Chrome. I can give Firefox a try.

**Reply by hawkeye217** [reply]
Chrome should be fine, Firefox doesn't support H.265 actually. 

Can you post your full config and your Frigate logs at the time you try to play back a recording?

**Reply by yourpalfranc** [reply]
Here's the frigate log. I'll need to edit out credentials from the config file as I haven't set up env vars yet.

**************************************
2024-10-12 19:00:56.537676872  [INFO] Preparing Frigate...
2024-10-12 19:00:56.723360325  [INFO] Starting Frigate...
2024-10-12 19:01:03.045260110  [2024-10-12 19:01:03] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-12 19:01:03.045346881  [2024-10-12 19:01:03] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-12 19:01:03.070597322  [2024-10-12 19:01:03] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-12 19:01:03.128053734  [2024-10-12 19:01:03] peewee_migrate.logs            INFO    : Starting migrations
2024-10-12 19:01:03.128619408  [2024-10-12 19:01:03] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-12 19:01:03.283663447  [2024-10-12 19:01:03] frigate.app                    INFO    : Recording process started: 360
2024-10-12 19:01:03.283820865  [2024-10-12 19:01:03] frigate.app                    INFO    : Recording process started: 362
2024-10-12 19:01:03.286655776  [2024-10-12 19:01:03] frigate.app                    INFO    : go2rtc process pid: 96
2024-10-12 19:01:03.325878436  [2024-10-12 19:01:03] detector.coral                 INFO    : Starting detection process: 388
2024-10-12 19:01:03.328041786  [2024-10-12 19:01:03] frigate.app                    INFO    : Output process started: 390
2024-10-12 19:01:03.376875627  [2024-10-12 19:01:03] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-10-12 19:01:03.382117409  [2024-10-12 19:01:03] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-10-12 19:01:03.564703910  [2024-10-12 19:01:03] frigate.app                    INFO    : Camera processor started for Driveway: 447
2024-10-12 19:01:03.571743703  [2024-10-12 19:01:03] frigate.app                    INFO    : Camera processor started for FrontPorch: 450
2024-10-12 19:01:03.578234553  [2024-10-12 19:01:03] frigate.app                    INFO    : Camera processor started for BackPorch: 456
2024-10-12 19:01:03.584257049  [2024-10-12 19:01:03] frigate.app                    INFO    : Camera processor started for BackYardNorth: 462
2024-10-12 19:01:03.590324083  [2024-10-12 19:01:03] frigate.app                    INFO    : Camera processor started for FrontPorchDoorbell: 468
2024-10-12 19:01:03.596806436  [2024-10-12 19:01:03] frigate.app                    INFO    : Capture process started for Driveway: 474
2024-10-12 19:01:03.604962588  [2024-10-12 19:01:03] frigate.app                    INFO    : Capture process started for FrontPorch: 490
2024-10-12 19:01:03.611391671  [2024-10-12 19:01:03] frigate.app                    INFO    : Capture process started for BackPorch: 494
2024-10-12 19:01:03.621499089  [2024-10-12 19:01:03] frigate.app                    INFO    : Capture process started for BackYardNorth: 500
2024-10-12 19:01:03.631638775  [2024-10-12 19:01:03] frigate.app                    INFO    : Capture process started for FrontPorchDoorbell: 507
2024-10-12 19:01:12.166437692  [2024-10-12 19:01:12] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
2024-10-12 20:11:35.288376  2024-10-12 19:01:12.166448845
******************************

**Reply by yourpalfranc** [reply]
Here's the config.yaml:

note: BackYardNorth is a lower res Reolink and FrontPorchDoorbell is a Reolink doorbell camera that both work great.

*******************************
```
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

go2rtc:
  streams:
    driveway:
      - rtsp://admin:password@ip/h264Preview_01_main
    driveway_sub:
      - rtsp://admin:password@ip/h264Preview_01_sub

cameras:
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

  FrontPorch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@ip/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@ip/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

  BackPorch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@ip/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@ip/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

  BackYardNorth:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@ip/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@ip/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

  FrontPorchDoorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@ip/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@ip/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

review:
  alerts:
    labels:
      - car
      - person
version: 0.14
```
**************************************************

**Reply by hawkeye217** [reply]
Can you provide the output of `http://frigate_ip:5000/api/go2rtc/streams/driveway`?

**Reply by yourpalfranc** [reply]
I tried browsing http://192.168.xxx.xxx:5000/api/go2rtc/streams/driveway and Chrome returned This Site Can't be Reached. Is that what you meant by output?

**Reply by hawkeye217** [reply]
Are you running Frigate via Home Assistant addon? If so, you need to enable the port in the addon settings.

**Reply by yourpalfranc** [reply]
Negative. My install is on a Dell i7-6700 PC, with Debian 12 and Coral PCIe per the documented installation. Well, to the best of my ability.

**Reply by hawkeye217** [reply]
I see your issue.

You've named the stream in go2rtc `driveway` and the camera name is `Driveway`. You'll want to match these so that Frigate's live view uses go2rtc.

**Reply by hawkeye217** [reply]
But to be clear, that doesn't affect recordings. We still need to figure out what codecs (video and audio) your camera is sending.

What is your docker compose?

**Reply by yourpalfranc** [reply]
I was hopeful, seems like it's always syntax that bites you, but it didn't seem to help. Or, I still didn't get it right?? Here's that section of config:

************************
go2rtc:
  streams:
    Driveway:
      - rtsp://user:password/ip/h264Preview_01_main
    Driveway_sub:
      - rtsp://user:password/ip/h264Preview_01_sub

cameras:
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
****************************

**Reply by yourpalfranc** [reply]
Docker-compose.yaml:

**********************
# version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
    devices:
      - /dev/dri/renderD128
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
***************************

**Reply by yourpalfranc** [reply]
That output was copied from nano, so the indentation is all skewed.

**Reply by hawkeye217** [reply]
Ah, you're running frigate with auth. Paste the output of this: `http://frigate_ip:8971/api/go2rtc/streams/driveway`

**Comment by yourpalfranc** [comment]
Returned...{"message":"Error fetching stream data","success":false}

Then I corrected driveway to Driveway and returned:

{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:44168","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=;sprop-pps=RAHAcvCUHjZI\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n","send":1481413778,"senders":["96 H265, bytes=1449552540, receivers=1","97 MPEG4-GENERIC/16000, bytes=14824680, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/Driveway","user_agent":"FFmpeg Frigate/0.14.1-f4f3cfa"},{"medias":["audio, sendonly, ALL","video, sendonly, ALL","audio, recvonly, ANY"],"receivers":["0 ANY, bytes=0, senders=1"],"remote_addr":"127.0.0.1:49322","senders":["97 MPEG4-GENERIC/16000, bytes=0, receivers=1","96 H265, bytes=0, receivers=1"],"type":"probe","user_agent":"python-requests/2.32.3"}],"producers":[{"medias":["video, recvonly, H265","audio, recvonly, MPEG4-GENERIC/16000","audio, sendonly, PCMU/8000"],"receivers":["96 H265, bytes=1449552540, senders=2","97 MPEG4-GENERIC/16000, bytes=14824680, senders=2"],"recv":1477200948,"remote_addr":"192.168.0.209:554","sdp":"v=0\r\no=- 1728208861107866 1 IN IP4 192.168.0.209\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=;sprop-pps=RAHAcvCUHjZI\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly","senders":["0 PCMU/8000, bytes=0, receivers=1"],"type":"RTSP active producer","url":"rtsp://192.168.0.209/Preview_01_main/","user_agent":"go2rtc/1.9.2"}]}

**Reply by yourpalfranc** [reply]
I turned Pretty Print on and got this....

********************
```
{
  "consumers": [
    {
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "remote_addr": "127.0.0.1:44168",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=;sprop-pps=RAHAcvCUHjZI\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "send": 1481413778,
      "senders": [
        "96 H265, bytes=1449552540, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=14824680, receivers=1"
      ],
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/Driveway",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa"
    },
    {
      "medias": [
        "audio, sendonly, ALL",
        "video, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        "0 ANY, bytes=0, senders=1"
      ],
      "remote_addr": "127.0.0.1:49322",
      "senders": [
        "97 MPEG4-GENERIC/16000, bytes=0, receivers=1",
        "96 H265, bytes=0, receivers=1"
      ],
      "type": "probe",
      "user_agent": "python-requests/2.32.3"
    }
  ],
  "producers": [
    {
      "medias": [
        "video, recvonly, H265",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H265, bytes=1449552540, senders=2",
        "97 MPEG4-GENERIC/16000, bytes=14824680, senders=2"
      ],
      "recv": 1477200948,
      "remote_addr": "192.168.0.209:554",
      "sdp": "v=0\r\no=- 1728208861107866 1 IN IP4 192.168.0.209\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=;sprop-pps=RAHAcvCUHjZI\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "senders": [
        "0 PCMU/8000, bytes=0, receivers=1"
      ],
      "type": "RTSP active producer",
      "url": "rtsp://192.168.0.209/Preview_01_main/",
      "user_agent": "go2rtc/1.9.2"
    }
  ]
}
```

**Reply by hawkeye217** [reply]
So the video is indeed H.265 as expected.

Next thing to look at is the requests to the backend from Chrome. Open Chrome devtools to the network pane, browse to the History view for that camera, and try playback. You should see the browser try to pull a .m3u8 file and some .ts files. Grab a screenshot of what you see.

**Reply by yourpalfranc** [reply]
![Screenshot from 2024-10-12 17-35-35](https://github.com/user-attachments/assets/c148258c-95b3-4329-9fb8-df4447d681cb)


Am I in the right place?

**Reply by hawkeye217** [reply]
Yes, that's the right place. If you click on the master.m3u8 file there in the network pane, what do you see?

**Reply by yourpalfranc** [reply]
![Screenshot from 2024-10-12 17-46-50](https://github.com/user-attachments/assets/e1f944aa-7428-4cd3-b79f-066b0e23dbe7)
![Screenshot from 2024-10-12 17-47-46](https://github.com/user-attachments/assets/12e7f331-9b5b-40b2-81d1-0babc59e6af6)

There's a tad bit more in the scroll, do you need it, too?

**Reply by hawkeye217** [reply]
When you drag the red handlebar down to an area that has motion, do you see any .ts files load in the network pane?

**Reply by yourpalfranc** [reply]
Sorry. I had to bail. I'll try to recreate things again tomorrow. Thanks very much for your help so far.

**Reply by yourpalfranc** [reply]
OK. I'm back at this again. Oh, and one other thing I wanted to mention...after creating restream on the one Reolink camera the display has become very unreliable. In most cases, I have to refresh the browser to get to display, and in a bit it goes away. All other cameras remain rock steady.

So, I went out and created another motion event. I don't see any .ts files in the network pane (screenshot attached). The headers detail is from the new master.m3u8 file created by this motion event.

Thanks!
![Screenshot from 2024-10-13 12-24-21](https://github.com/user-attachments/assets/39d7dc19-708f-44ea-bcb6-b3adb5363700)

**Reply by yourpalfranc** [reply]
I see what you mean about .ts files, though. This is a shot from a lower res Reolink camera that works well with lots of .ts files.
![Screenshot from 2024-10-13 12-34-48](https://github.com/user-attachments/assets/25a925c5-0125-4e53-8502-45009c9eee8a)

**Reply by hawkeye217** [reply]
The .ts files are the actual video data, so if there truly is footage available, they should be fetched along with the .m3u8 file. From the config file you posted, it doesn't seem like there would be an issue with recordings. Are you seeing review items (alerts/detections) generated from that particular camera?

**Reply by yourpalfranc** [reply]
So right now the driveway camera is the only one set to restream. When I create a motion event by walking through the driveway the clips show up in the top row. When I click to view I get the still image with the spinning arrow, however I can scrub fully through the timeline as far back as I want, the video just doesn't play. And, you can see by the last shot that when I returned to the main view the driveway camera wasn't displayed...until I refreshed the browser. I'm going to set up a restream from my doorbell camera which is lower resolution to see if it shows this same problem. I'm thinking it probably won't.

![Screenshot from 2024-10-14 10-24-58](https://github.com/user-attachments/assets/852bb800-cb99-42c4-9398-be426ddea766)
![Screenshot from 2024-10-14 10-25-23](https://github.com/user-attachments/assets/c642bca6-88a8-42a6-94e6-4d150c8cb104)

![Screenshot from 2024-10-14 10-23-19](https://github.com/user-attachments/assets/cc27b8bd-7ab0-4b38-998d-27c36d125fe8)
![Screenshot from 2024-10-14 10-23-39](https://github.com/user-attachments/assets/d0be2cc7-97ad-4c97-9bb4-e44f31af0ceb)
![Screenshot from 2024-10-14 10-23-59](https://github.com/user-attachments/assets/b6b9ff6e-1dd7-44c8-bad7-50be72d48b29)

**Reply by hawkeye217** [reply]
Another user had a good experience using the ffmpeg source in go2rtc, perhaps this could help you as well.

```
go2rtc:
  streams:
    driveway:
      - rtsp://admin:password@ip/h264Preview_01_main#video=copy#audio=aac
    driveway_sub:
      - ffmpeg:rtsp://admin:password@ip/h264Preview_01_sub#video=copy#audio=aac
```
