### DISCUSSION TITLE
[Config Support]: Weird artifacts on live feed

### DISCUSSION THREAD

**Discussion by vehkh** [blakeblackshear/frigate#14300] [Config Support] [answered]
### Describe the problem you are having

Hello,
I have a problem with my frigate setup. On live feed I'm getting artifacts (see screenshoot). I know that this could be related to inappropriate size defined in detect section like described here https://github.com/blakeblackshear/frigate/discussions/12897. 
I have checked my camera streams and it looks like I've done everything correct: first stream resolution is 1920x1080 and second, used for detection, 640x352. That was checked on camera config page and via VLC stream details.
![Screenshot_20241012_142658](https://github.com/user-attachments/assets/435917c4-1d26-49cb-9ab4-0327fdaac33d)
![Screenshot_20241012_143516](https://github.com/user-attachments/assets/8466f2ea-134b-4ed2-83bd-ab09bf7c7403)
What I am doing wrong as this must be related to settings - while having both roles (detect and record) on main stream and height and width = 1920x1080 I'm not experiencing similar issues.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.180
  user: admin
  password: <psswd>

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: auto
  input_args: preset-rtsp-generic

detect:
  fps: 5
  enabled: true

objects:
  track:
    - person
    - car
    - cat
    - dog
  filters:
    person:
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.6
      threshold: 0.7

review:
  alerts:
    labels:
      - car
      - person
motion:
  enabled: true
  threshold: 30

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 2
    retain:
      default: 3
      mode: all
  preview:
    quality: medium

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  retain:
    default: 3

cameras:

  Frontyard:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.10:554/11
          roles:
            - record
            #- detect
        - path: rtsp://192.168.0.10:554/12
          roles:
            #- record
            - detect
    detect:
      width: 640
      height: 352
      fps: 5
      enabled: true
    onvif:
      host: 192.168.0.10
      port: 8080
      user: admin
      password: <psswd>
    motion:
      mask: 0.001,0.075,1,0.518,1,0,0,0
    objects:
      mask: 0.001,0.074,0.001,0.005,0.998,0,0.998,0.517

  Backyard:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.11:554/11
          roles:
            - record
            - detect
    detect:
    #   width: 1920
    #   height: 1080
      fps: 5
      enabled: true
    onvif:
      host: 192.168.0.11
      port: 8080
      user: admin
      password: <psswd>

  Home:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.12:554/11
          roles:
            - record
            - detect
    detect:
    #   width: 1920
    #   height: 1080
      fps: 5
      enabled: true
    onvif:
      host: 192.168.0.12
      port: 8080
      user: admin
      password: <psswd>

  Garage_1:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.13:554/11
          roles:
            - record
            - detect
    detect:
    #   width: 1920
    #   height: 1080
      fps: 5
      enabled: true
    onvif:
      host: 192.168.0.13
      port: 8080
      user: admin
      password: <psswd>

  Garage_2:
    enabled: true
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.14:554/11
          roles:
            - record
            - detect
    detect:
    #   width: 1920
    #   height: 1080
      fps: 5
      enabled: true
    onvif:
      host: 192.168.0.14
      port: 8080
      user: admin
      password: <psswd>
version: 0.14
```

### Relevant Frigate log output

```shell
2024-10-12 14:10:15.958984881  [INFO] Preparing Frigate...
2024-10-12 14:10:15.999046152  [INFO] Starting Frigate...
2024-10-12 14:10:17.714403205  [2024-10-12 14:10:17] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-12 14:10:17.714544733  [2024-10-12 14:10:17] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-12 14:10:17.748554830  [2024-10-12 14:10:17] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-12 14:10:17.879801296  [2024-10-12 14:10:17] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-10-12 14:10:17.884108558  [2024-10-12 14:10:17] frigate.config                 WARNING : Frontyard: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2024-10-12 14:10:19.779301862  [2024-10-12 14:10:19] frigate.config                 WARNING : Backyard: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2024-10-12 14:10:21.662158765  [2024-10-12 14:10:21] frigate.config                 WARNING : Home: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2024-10-12 14:10:23.850633935  [2024-10-12 14:10:23] frigate.config                 WARNING : Garage_1: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2024-10-12 14:10:26.613087041  [2024-10-12 14:10:26] frigate.config                 WARNING : Garage_2: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2024-10-12 14:10:26.650747724  [2024-10-12 14:10:26] peewee_migrate.logs            INFO    : Starting migrations
2024-10-12 14:10:26.651094277  [2024-10-12 14:10:26] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-12 14:10:27.463475864  [2024-10-12 14:10:27] frigate.app                    INFO    : Recording process started: 411
2024-10-12 14:10:27.469924255  [2024-10-12 14:10:27] frigate.app                    INFO    : Recording process started: 419
2024-10-12 14:10:27.473732702  [2024-10-12 14:10:27] frigate.app                    INFO    : go2rtc process pid: 98
2024-10-12 14:10:27.501797827  [2024-10-12 14:10:27] detector.coral                 INFO    : Starting detection process: 440
2024-10-12 14:10:30.701017806  [2024-10-12 14:10:27] frigate.app                    INFO    : Output process started: 443
2024-10-12 14:10:30.701392369  [2024-10-12 14:10:27] frigate.app                    INFO    : Camera processor started for Frontyard: 459
2024-10-12 14:10:30.701559701  [2024-10-12 14:10:27] frigate.app                    INFO    : Camera processor started for Backyard: 462
2024-10-12 14:10:30.701710715  [2024-10-12 14:10:27] frigate.app                    INFO    : Camera processor started for Home: 463
2024-10-12 14:10:30.701806048  [2024-10-12 14:10:27] frigate.app                    INFO    : Camera processor started for Garage_1: 465
2024-10-12 14:10:30.704648451  [2024-10-12 14:10:27] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-10-12 14:10:30.704790067  [2024-10-12 14:10:27] frigate.app                    INFO    : Camera processor started for Garage_2: 471
2024-10-12 14:10:30.704917998  [2024-10-12 14:10:30] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-10-12 14:10:30.705040939  [2024-10-12 14:10:27] frigate.app                    INFO    : Capture process started for Frontyard: 481
2024-10-12 14:10:30.705142300  [2024-10-12 14:10:27] frigate.app                    INFO    : Capture process started for Backyard: 496
2024-10-12 14:10:30.705228334  [2024-10-12 14:10:27] frigate.app                    INFO    : Capture process started for Home: 507
2024-10-12 14:10:30.705327474  [2024-10-12 14:10:27] frigate.app                    INFO    : Capture process started for Garage_1: 512
2024-10-12 14:10:30.705414985  [2024-10-12 14:10:27] frigate.app                    INFO    : Capture process started for Garage_2: 516
2024-10-12 14:26:09.737355746  [2024-10-12 14:26:09] frigate.comms.dispatcher       INFO    : Setting ptz command to stop for Frontyard
```

### Relevant go2rtc log output

```shell
2024-10-12 14:10:15.958080562  [INFO] Preparing new go2rtc config...
2024-10-12 14:10:16.511130229  [INFO] Starting go2rtc...
2024-10-12 14:10:16.675244680  14:10:16.675 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-10-12 14:10:16.675268930  14:10:16.675 INF config path=/dev/shm/go2rtc.yaml
2024-10-12 14:10:16.675656910  14:10:16.675 INF [rtsp] listen addr=:8554
2024-10-12 14:10:16.675818672  14:10:16.675 INF [webrtc] listen addr=:8555/tcp
2024-10-12 14:10:16.675950711  14:10:16.675 INF [api] listen addr=:1984
2024-10-12 14:10:25.956201396  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
    "cameras": {
        "Backyard": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 496,
            "detection_enabled": true,
            "detection_fps": 15,
            "ffmpeg_pid": 506,
            "pid": 462,
            "process_fps": 0.7,
            "skipped_fps": 4.4
        },
        "Frontyard": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 481,
            "detection_enabled": true,
            "detection_fps": 9.5,
            "ffmpeg_pid": 505,
            "pid": 459,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "Garage_1": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 512,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 523,
            "pid": 465,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "Garage_2": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 516,
            "detection_enabled": true,
            "detection_fps": 1,
            "ffmpeg_pid": 529,
            "pid": 471,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "Home": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 507,
            "detection_enabled": true,
            "detection_fps": 13.3,
            "ffmpeg_pid": 514,
            "pid": 463,
            "process_fps": 1.8,
            "skipped_fps": 3.1
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "46": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "86": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "87": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "98": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "110": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "115": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "2.2",
            "cpu_average": "2",
            "mem": "4.2"
        },
        "132": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "158": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "159": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "160": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "170": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "183": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "307": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "336": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.7"
        },
        "411": {
            "cmdline": "frigate.recording_manager",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "1.2"
        },
        "419": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "1.1"
        },
        "439": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "440": {
            "cmdline": "frigate.detector.coral",
            "cpu": "51.1",
            "cpu_average": "49",
            "mem": "1.1"
        },
        "443": {
            "cmdline": "frigate.output       ",
            "cpu": "5.6",
            "cpu_average": "5",
            "mem": "1.3"
        },
        "459": {
            "cmdline": "frigate.process:Frontyard",
            "cpu": "6.6",
            "cpu_average": "5",
            "mem": "1.1"
        },
        "462": {
            "cmdline": "frigate.process:Backyard",
            "cpu": "10.1",
            "cpu_average": "11",
            "mem": "1.4"
        },
        "463": {
            "cmdline": "frigate.process:Home ",
            "cpu": "9.6",
            "cpu_average": "8",
            "mem": "1.2"
        },
        "465": {
            "cmdline": "frigate.process:Garage_1",
            "cpu": "1.5",
            "cpu_average": "2",
            "mem": "1.3"
        },
        "471": {
            "cmdline": "frigate.process:Garage_2",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "1.2"
        },
        "481": {
            "cmdline": "frigate.capture:Frontyard",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "496": {
            "cmdline": "frigate.capture:Backyard",
            "cpu": "2.9",
            "cpu_average": "2",
            "mem": "1.1"
        },
        "505": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.0.10:554/12 -r 5 -vf fps=5,scale_vaapi=w=640:h=352:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "506": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.0.11:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Backyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.8",
            "cpu_average": "3",
            "mem": "0.4"
        },
        "507": {
            "cmdline": "frigate.capture:Home ",
            "cpu": "3.1",
            "cpu_average": "3",
            "mem": "1.1"
        },
        "512": {
            "cmdline": "frigate.capture:Garage_1",
            "cpu": "2.9",
            "cpu_average": "3",
            "mem": "1.1"
        },
        "514": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.0.12:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Home@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "4.2",
            "cpu_average": "4",
            "mem": "0.4"
        },
        "516": {
            "cmdline": "frigate.capture:Garage_2",
            "cpu": "3.0",
            "cpu_average": "3",
            "mem": "1.1"
        },
        "521": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.0.10:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Frontyard@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "523": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.0.13:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garage_1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.7",
            "cpu_average": "3",
            "mem": "0.4"
        },
        "529": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.0.14:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garage_2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.7",
            "cpu_average": "4",
            "mem": "0.4"
        },
        "532": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -threads 1 -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "537": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "542": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "551": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "556": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "561": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "885": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "8942": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "9099": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "34.0",
            "mem": "29.2"
        }
    },
    "detection_fps": 38.8,
    "detectors": {
        "coral": {
            "detection_start": 1728737049.644964,
            "inference_speed": 26.53,
            "pid": 440
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "4.57%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 98
        },
        "logger": {
            "pid": 336
        },
        "recording": {
            "pid": 411
        },
        "review_segment": {
            "pid": 419
        }
    },
    "service": {
        "last_updated": 1728737050,
        "latest_version": "0.14.1",
        "storage": {
            "/dev/shm": {
                "free": 131.7,
                "mount_type": "tmpfs",
                "total": 165,
                "used": 33.3
            },
            "/media/frigate/clips": {
                "free": 82597,
                "mount_type": "ext4",
                "total": 232684.7,
                "used": 138196.9
            },
            "/media/frigate/recordings": {
                "free": 82597,
                "mount_type": "ext4",
                "total": 232684.7,
                "used": 138196.9
            },
            "/tmp/cache": {
                "free": 831.5,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 122.1
            }
        },
        "temperatures": {},
        "uptime": 2023,
        "version": "0.14.1-f4f3cfa"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "165mb"
    devices:
      - /dev/bus/usb/002/002:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/vekh/Documents:/config
      - /home/vekh/Documents/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![screencapture-192-168-0-201-5000-system-2024-10-12-14_40_26](https://github.com/user-attachments/assets/7977b687-1885-42b3-b78b-303332764609)
