### DISCUSSION TITLE
After changing shm size, frigate fails to start

### DISCUSSION THREAD

**Discussion by vespaman** [blakeblackshear/frigate#14303] [General]
So, this is the first day of starting up my frigate setup. I installed one camera after the other, arrived to 5 cameras, where one would not give picture, so I looked in the log, and found a message saying shm size too small.
So I changed shm to 256, forgetting the 'mb' after, restarted and got errors saying 
```
frigate  | s6-log: warning: unable to write to /dev/shm/logs/certsync/current: No space left on device
frigate  | s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
frigate  | s6-log: warning: unable to write to /dev/shm/logs/go2rtc/current: No space left on device
frigate  | s6-log: warning: unable to write to /dev/shm/logs/certsync/current: No space left on device
```
So I googled and found my mistake. Also found a recommendation to change to 2048mb, which I did. But still the same error message.
I have rebooted, and restarted docker compose many times now.
I tried to set the last couple of cameras 'enabled: false' but still the same problem.

Don't know what to do now. Wipe and re-install?

$ cat docker-compose.yml
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/micke/frigate/config/:/config
      - /mnt/frigate_storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

`cat config/config.yaml
```
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  front_cam: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
       # - path: rtsp://10.1.200.18:554/live # <----- The stream you want to use for detection
        - path: rtsp://admin:pwd@10.1.200.17:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://admin:pwd@10.1.200.17:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record:
      enabled: true

    zones:
      Framsida:
        coordinates: 
          0.793,0.043,0.616,0.102,0.584,0.175,0.543,0.228,0.47,0.25,0.211,0.468,0.11,0.607,0.193,0.999,0.563,0.995,0.708,0.439,0.787,0.415
        loitering_time: 0
    motion:
      mask:
        - 0.8,0.418,0.716,0.442,0.583,0.995,0.995,0.995,0.996,0,0.802,0
        - 0.184,0.99,0.002,0.992,0.002,0.001,0.277,0.004,0.073,0.147,0.105,0.611
    review:
      alerts:
        required_zones: Framsida

  entrance_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pwd@10.1.200.18:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://admin:pwd@10.1.200.18:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record:
      enabled: true

    motion:
      mask:
        - 0.456,0.919,0.433,0.624,0.532,0.29,0.67,0.227,0.806,0.262,0.871,0.372,0.9,0.492,0.857,0.994,0.468,0.996
        - 0.209,0.761,0.133,0.804,0.107,0.797,0.072,0.794,0,0.783,0,0.383,0.113,0.507,0.096,0.552,0.102,0.571,0.099,0.603,0.114,0.587,0.147,0.595,0.161,0.628,0.171,0.66
        - 0.046,0.051,0.279,0.048,0.281,0.079,0.046,0.079
  backside_cam: # <------ Name the camera
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:pwd@10.1.200.15:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://admin:pwd@10.1.200.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record:
      enabled: true

  balcony_cam: # <------ Name the camera
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://10.1.200.14:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://10.1.200.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record:
      enabled: true

  office_cam:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:pwd@10.1.200.19:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://admin:pwd@10.1.200.19:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record:
      enabled: true

version: 0.14
```
