### DISCUSSION TITLE
[Support]: no audio stream on ios

### DISCUSSION THREAD

**Discussion by izzygold** [blakeblackshear/frigate#14311] [General Support] [answered]
### Describe the problem you are having

When trying to play stream on ios after "installing" frigate as app, I don't have the sound option, at first it is turned on, after a few seconds when the video is loading the sound option disappears.
This issue does not happen on chrome/safari via mac os.

### Version

commit ddcec82

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: 
  user: frigate
  password: 

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

logger:
  default: info

auth:
  enabled: true
  reset_admin_password: false

go2rtc:
  streams:
    back_forest:
      - rtsp://------@192.168.68.71:554/1
    entrance_car:
      - rtsp://------@192.168.68.106:554/1
    front_yard:
      - rtsp://------@192.168.68.108:554/1
    eastern_path:
      - rtsp://------@192.168.68.75:554/1
audio:
  enabled: true
  listen:
    - explosion
    - gunshot
    - machine_gun
    - artillery_fire
    - cap_gun
    - fireworks
    - siren
    - civil_defense_siren
    - aircraft
    - aircraft_engine
    - bang
    - woosh
    - thump
    - thunk
  filters:
    civil_defense_siren:
      threshold: 0.5

tls:
  enabled: false

motion:
  threshold: 20

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  width: 1280
  height: 960
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front_yard: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.68.108
      port: 8899
      user: admin
      password: ---
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://------@192.168.68.108:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 90
    snapshots:
      enabled: true
    zones:
      street:
        coordinates: 
          0.668,0.232,0.666,0.461,0.675,0.473,0.717,0.41,0.771,0.388,0.785,0.392,0.797,0.282,0.797,0.255,0.792,0.243,0.77,0.237,0.732,0.233,0.705,0.234,0.692,0.233
        loitering_time: 0
      Yard:
        coordinates: 
          0.06,0.321,0.275,0.262,0.409,0.262,0.608,0.212,0.667,0.225,0.664,0.434,0.712,0.425,0.742,0.405,0.779,0.394,0.788,0.387,0.795,0.305,0.79,0.263,0.79,0.246,0.823,0.246,0.854,0.258,0.867,0.275,0.884,0.316,0.927,0.326,0.958,0.32,0.969,0.324,0.99,0.345,0.99,0.571,0.949,0.942,0.924,0.999,0.103,0.998,0.007,0.425,0.003,0.295
        inertia: 1
        loitering_time: 0
    review:
      alerts:
        required_zones: Yard
    motion:
      threshold: 36
      contour_area: 18
      improve_contrast: true
  entrance_car: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.68.106
      port: 8899
      user: admin
      password: ---
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://------@192.168.68.106:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 90
    snapshots:
      enabled: true

    zones:
      road:
        coordinates: 
          0.133,0.208,0.123,0.178,0.156,0.11,0.242,0.077,0.351,0.059,0.409,0.155,0.486,0.147,0.512,0.085,0.604,0.06,0.783,0.068,0.85,0.101,0.872,0.117,0.932,0.118,0.984,0.13,0.946,0.328,0.828,0.356,0.637,0.343,0.493,0.336,0.416,0.327,0.367,0.346,0.238,0.389,0.162,0.394,0.14,0.391
        loitering_time: 0
      street:
        coordinates: 
          0.145,0.401,0.341,0.363,0.401,0.336,0.785,0.35,0.864,0.365,0.858,0.503,0.302,0.5,0.169,0.479
        loitering_time: 0
      Parking:
        coordinates: 
          0.162,0.47,0.331,0.541,0.474,0.528,0.688,0.528,0.866,0.527,0.955,0.862,0.909,0.964,0.867,0.986,0.101,0.992,0.073,0.926,0.036,0.949,0.001,0.947,0.004,0.28,0.081,0.217,0.134,0.412
        loitering_time: 0
    review:
      alerts:
        required_zones: Parking
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  back_forest: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.68.71
      port: 8899
      user: admin
      password: ---
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://------@192.168.68.71:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 90
    snapshots:
      enabled: true

    zones:
      Road:
        coordinates: 
          0.054,0.487,0.225,0.583,0.292,0.641,0.553,0.76,0.709,0.791,0.917,0.791,0.975,0.781,0.99,0.778,0.994,0.874,0.923,0.924,0.865,0.921,0.803,0.906,0.738,0.899,0.625,0.896,0.423,0.864,0.214,0.78,0.145,0.728,0.056,0.68,0.005,0.644,0.001,0.454
        loitering_time: 0
      forest:
        coordinates: 
          0.009,0.406,0.005,0.07,0.178,0.078,0.18,-0.002,0.999,0,0.997,0.753,0.878,0.772,0.67,0.767,0.485,0.704,0.324,0.634,0.202,0.555,0.016,0.447
        loitering_time: 0
      CloseToYard:
        coordinates: 
          0.005,0.662,0.237,0.803,0.393,0.859,0.779,0.914,0.918,0.939,0.979,0.907,0.998,0.882,0.998,0.995,0.101,0.995,0.091,0.955,0.052,0.954,0.02,0.952,0,0.947
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - CloseToYard
          - forest
    motion:
      threshold: 38
      contour_area: 10
      improve_contrast: true
  eastern_path: # <--- this will be changed to your actual camera later
    enabled: true
    onvif:
      host: 192.168.68.75
      port: 8899
      user: admin
      password: ---
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://------@192.168.68.75:554/1
          roles:
            - record
            - detect
            - audio
    record:
      export:
        timelapse_args: -vf setpts=PTS/60 -r 25
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 90
        pre_capture: 10
        post_capture: 10
    snapshots:
      enabled: true
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
version: 0.15-0
notifications:
  enabled: true
  email: israel.g.88@gmail.com
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision, dont know which model, all cameras are the same model

**Comment by hawkeye217** [comment]
So after you navigate to the Live view for an individual camera, the camera stream begins playing back, you can see video and hear sound, and then it switches to a stream with video but no sound?

**Reply by izzygold** [reply]
I don't hear sound at all, but I see the sound icon at first and then it disappears.

**Reply by hawkeye217** [reply]
What camera is this happening on? All of them, or just a specific one?

**Reply by izzygold** [reply]
All of them.

**Reply by hawkeye217** [reply]
What audio codec are your cameras outputting?

**Reply by izzygold** [reply]
How can I check that?

**Reply by hawkeye217** [reply]
The reason why the audio icon disappears is because your browser reports that it can't play back the stream that your cameras are sending from go2rtc, so it switches to the low quality, no-audio jsmpeg player.

This is usually caused by using a video and/or audio codec that is unsupported by your browser.

See the [camera settings recommendations docs](https://docs.frigate.video/configuration/live/#camera-settings-recommendations) for what we suggest.

**Reply by hawkeye217** [reply]
> How can I check that?

It'd be settings in your camera's firmware. 

But we can also see it from go2rtc. Paste the output of `http://frigate_ip:5000/api/go2rtc/streams`

**Reply by izzygold** [reply]
{
  "back_forest": {
    "producers": [
      {
        "url": "rtsp://*:*@192.168.68.71:554/1"
      }
    ],
    "consumers": []
  },
  "eastern_path": {
    "producers": [
      {
        "url": "rtsp://*:*@192.168.68.75:554/1"
      }
    ],
    "consumers": []
  },
  "entrance_car": {
    "producers": [
      {
        "url": "rtsp://*:*@192.168.68.106:554/1"
      }
    ],
    "consumers": null
  },
  "front_yard": {
    "producers": [
      {
        "url": "rtsp://*:*@192.168.68.108:554/1"
      }
    ],
    "consumers": []
  }
}

**Reply by hawkeye217** [reply]
Since you aren't using restream (go2rtc for recording and detection), you'll need to open up Live view for one of those cameras and grab the output in the first few seconds that it's trying to connect.

**Reply by izzygold** [reply]
Thanks for your prompt help! 

{"back_forest":{"producers":[{"type":"RTSP active producer","url":"rtsp://192.168.68.71:554/1","remote_addr":"192.168.68.71:554","user_agent":"go2rtc/1.9.2","sdp":"v=0\r\no=- 38990265062388 38990265062388 IN IP4 192.168.68.71\r\ns=RTSP Session\r\nt=0 0\r\na=control:*\r\na=range:npt=0-\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 192.168.68.71\r\na=rtpmap:96 H264/90000 \r\na=fmtp:96 profile-level-id=4d0033; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIfSssIRZAAADA+gAAF3ABA==,aO48gA==\r\na=framerate:25\r\na=control:trackID=3\r\nm=audio 0 RTP/AVP 8\r\nc=IN IP4 192.168.68.71\r\na=control:trackID=4\r\n","medias":["video, recvonly, H.264 Main 5.1","audio, recvonly, PCMA/8000"],"receivers":["96 H264, bytes=243058, senders=1","8 PCMA/8000, bytes=3200, senders=0"],"recv":248502},{"url":"ffmpeg:back_forest#audio=opus"}],"consumers":[{"type":"MSE/WebSocket active consumer","remote_addr":"172.18.0.1, 127.0.0.1:43488","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"senders":["96 H264, bytes=243058, receivers=1"],"send":243057}]},"eastern_path":{"producers":[{"url":"rtsp://*:*@192.168.68.75:554/1"}],"consumers":[]},"entrance_car":{"producers":[{"url":"rtsp://*:*@192.168.68.106:554/1"}],"consumers":null},"front_yard":{"producers":[{"url":"rtsp://*:*@192.168.68.108:554/1"},{"url":"ffmpeg:front_yard#audio=opus"}],"consumers":[]}}

**Comment by hawkeye217** [comment]
```
go2rtc:
  streams:
    back_forest:
      - rtsp://------@192.168.68.71:554/1
    entrance_car:
      - rtsp://------@192.168.68.106:554/1
    front_yard:
      - rtsp://------@192.168.68.108:554/1
    eastern_path:
      - rtsp://------@192.168.68.75:554/1
```

Are you sure this is your full go2rtc config?

**Reply by izzygold** [reply]
After entering the link you provided I made the following change:
go2rtc:
  streams:
    back_forest:
      - rtsp://@192.168.68.71:554/1
      - "ffmpeg:back_forest#audio=opus"
    entrance_car:
      - rtsp://@192.168.68.106:554/1
    front_yard:
      - rtsp://@192.168.68.108:554/1
      - "ffmpeg:front_yard#audio=opus" 
    eastern_path:
      - rtsp://@192.168.68.75:554/1

**Reply by hawkeye217** [reply]
You'll want to make sure you provide AAC audio, which is what iOS needs. 

https://docs.frigate.video/configuration/live#audio-support

**Reply by izzygold** [reply]
Adding       - "ffmpeg:eastern_path#audio=aac#audio=opus"
did not help, I fear that my cameras don't support aac. I have ordered actual hikvision cameras (and not my weird hikvision clone cameras) and I hope I'll be able to better configure them.

**Reply by hawkeye217** [reply]
Does it work if you remove `#audio=opus`?

**Reply by zenguru84** [reply]
@izzygold did you solved this? 
i'm in the same situation.
no audio and poor quality stream in chrome on windows.

**Reply by izzygold** [reply]
not really

**Reply by zenguru84** [reply]
my cameras worked fine with frigate 0.13.. the issue is with 0.14.

**Reply by izzygold** [reply]
same here, i hope i will have some more time to dig deeper next weekend

**Reply by zenguru84** [reply, marked as answer]
try this and let me know. mine are working, after 14 hours of digging. :) 

```
go2rtc:
  streams:
    back_forest:
      - rtsp://@192.168.68.71:554/1#audio=opus
```

**Reply by izzygold** [reply]
Oh my, that worked!

Thank you so much! you definitely brought more -zen- to my life, -guru-.

**Reply by izzygold** [reply]
@hawkeye217 is there a reason why this shouldn't be the defaulted? or is the #audio=opus in the end of the link unique to our cameras?

**Reply by hawkeye217** [reply]
Opus is just an audio format, like AAC. So `#audio=opus` is transcoding your camera's audio to opus format. This is unique to your camera, it's not something that should be the default. This chart on the go2rtc repo shows you what is supported for each browser and streaming technology: https://github.com/AlexxIT/go2rtc/#codecs-madness

**Reply by izzygold** [reply]
I see, maybe it should be explicitly mentioned in the docs that one can use "rtsp://@ip:554/1#audio=opus" if one doesn't have audio on iphones? 

The only place it is show is in:
Some examples:
rtsp://192.168.1.123:8554/camera1?video=h264&audio=aac&audio=opus - H264 video codec and two separate audio tracks

I mean, zenguru spent 14 hours to find this rather simple solution. 

What do you think?

**Reply by NickM-27** [reply]
It is in the docs https://docs.frigate.video/configuration/live#audio-support

**Reply by hawkeye217** [reply]
> I see, maybe it should be explicitly mentioned in the docs that one can use "rtsp://@ip:554/1#audio=opus" if one doesn't have audio on iphones?
> 

@NickM-27 is correct. 

The example in the docs shows a camera that supports AAC audio natively, which most cameras are able to do. The 2nd line in the go2rtc config transcodes that native audio to opus format.

If your camera doesn't provide AAC audio, you need to transcode it, which is also suggested in the docs and on the go2rtc repo. Eg:

```
go2rtc:
  streams:
    back_forest:
      - ffmpeg:rtsp://------@192.168.68.71:554/1#video=copy#audio=aac
      - ffmpeg:back_forest#audio=opus
```
