### DISCUSSION TITLE
[Config Support]: Always detect but only alert when switch is flipped in HA

### DISCUSSION THREAD

**Discussion by LakesideMiners** [blakeblackshear/frigate#14316] [Config Support] [answered]
### Describe the problem you are having

I am using Firgate as an NVR with 24/7 recording. and, I want to actualy make use of the 
Is this kind of setup able to be done? Thank You!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
record:
  enabled: true
  retain:
    days: 2


go2rtc:
  streams:
    Living_Room: tapo://REDACTED@192.168.1.190
    Bedroom: tapo://REDACTED@192.168.1.200
  webrtc:
    candidates:
      - stun:8555
database:
  path: /config/frigate.db
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  Living_Room: # <------ Name the camera
    enabled: true
    onvif:
      host: 192.168.1.190
      port: 2020
      user: REDACTED
      password: REDACTED

    ffmpeg:
      inputs:
        - path: rtsp://REDACTED:REDACTED@192.168.1.190:554/stream2 # <----- The stream you want to use for detection
          roles:
            - audio
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    motion:
      mask: 0.361,0.05,0.238,0.06,0.219,0.055,0.211,0.096,0,0.101,0,0,0.356,0
      threshold: 48
      contour_area: 63
      improve_contrast: true

  Bedroom: # <------ Name the camera
    enabled: true
    onvif:
      host: 192.168.1.200
      port: 2020
      user: REDACTED
      password: REDACTED

    ffmpeg:
      inputs:
        - path: rtsp://REDACTED:REDACTED@192.168.1.200:554/stream2 # <----- The stream you want to use for detection
          roles:
            - audio
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    motion:
      mask: 0.361,0.05,0.238,0.06,0.219,0.055,0.211,0.096,0,0.101,0,0,0.356,0
      threshold: 48
      contour_area: 63
      improve_contrast: true
    zones: {}
version: 0.14
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

Coral
