### DISCUSSION TITLE
[Config Support]: Is ffmpeg display_rotation supported

### DISCUSSION THREAD

**Discussion by HomeAssistantPim** [blakeblackshear/frigate#14324] [Config Support]
### Describe the problem you are having

Thanx for frigate :)
I managed to rotate my camera using go2rtc and ffmpeg's rotate argument.
As I run frigate on my HAOS and my hardware is not that fantastic, I was wondering whether the ffmpeg display_rotation argument is supported as well (only rewrites meta data, no transcoding)?
I tried but it didn't work (or I didn't do it properly) 

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false
#  host: 192.168.0.14

database:
  path: /config/frigate.db

go2rtc:
  streams:
    hal:
      - rtsp://.../Preview_01_sub
      - ffmpeg:hal#video=h264
    hal_rotated:
      - ffmpeg:hal#video=h264#rotate=270
    hal_hq:
      - rtsp://.../Preview_01_main
      - ffmpeg:hal_hq#video=h264
    hal_hq_rotated:
      - ffmpeg:hal_hq#video=h264#rotate=270

cameras:
  hal:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hal_hq_rotated
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hal_rotated
          input_args: preset-rtsp-restream
          roles:
            - detect

      output_args:
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -an

    motion:
      mask: 0.736,0.595,0.605,0.593,0.594,0.677,0.726,0.679
record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 30
      mode: motion
version: 0.14
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
hacs managed
```

### Object Detector

CPU (no coral)
