### DISCUSSION TITLE
[Support]: Reviewed events disappearing unexpectedly

### DISCUSSION THREAD

**Discussion by tehsquid** [blakeblackshear/frigate#14332] [General Support]
### Describe the problem you are having

Reviewed events seem to completely disappear from frigate and cannot be found again (even when using the show reviewed toggle).  The time on the timeline also shows that nothing is there.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.2
  port: 1883
  user: mqtt
  password: ####

go2rtc:
  streams:
    backyard:
      - rtsp://admin:######@192.168.1.52:554/ch04/0
    frontdoor:
      - rtsp://admin:######@192.168.1.52:554/ch01/0
    laundrydoor:
      - rtsp://admin:######@192.168.1.52:554/ch02/0
    driveway:
      - rtsp://admin:######@192.168.1.52:554/ch03/0
  webrtc:
    candidates:
      - 192.168.1.2:8555
      - stun:8555

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  backyard:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    zones:
      back_yard:
        coordinates: 0,1080,1920,1080,1920,265,1334,157,1332,50,874,43,856,0,0,0
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      filters:
        person:
          min_score: 0.8
        cat:
          min_score: 0.6
        dog:
          min_score: 0.6
        bird:
          min_score: 0.8
    review:
      alerts:
        required_zones:
          - back_yard
        labels:
          - person

  frontdoor:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 0,0,0.271,0,0.272,0.273,0,0.343
        - 1,0,1,0.182,0.34,0.196,0.343,0
    zones:
      frontyard:
        coordinates: 1,1,1,0.189,0.888,0.191,0.883,0.447,0.652,0.408,0,0.908,0,1
        inertia: 3
        loitering_time: 0
      frontlawn:
        coordinates: 0.02,1,0.652,1,0.676,0.951,0.521,0.877,0.778,0.444,0.647,0.42,0.018,0.93
        inertia: 3
        loitering_time: 0
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      filters:
        person:
          min_area: 5000
        car:
          min_area: 50000
        cat:
          min_score: 0.6
        dog:
          min_score: 0.6
    review:
      alerts:
        required_zones:
          - frontyard
        labels:
          - person
          - car
          - bicycle
          - motorcycle

  laundrydoor:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/laundrydoor
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 966,315,98,0,90,235,246,291,253,423,976,393
    zones:
      sideofhouse:
        coordinates: 0,1080,1920,1080,1920,310,982,316,982,460,0,1003
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      filters:
        bird:
          min_score: 0.8
    review:
      alerts:
        required_zones:
          - sideofhouse
        labels:
          - person

  driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask: 0,0,1,0,1,0.133,0.47,0.12,0,0.2
    zones:
      frontyard:
        coordinates: 1920,1080,0,1080,0,587,1920,731
      drivewaylawn:
        coordinates: 1920,1080,1920,706,1422,654,1359,1080
      frontyard_enter:
        coordinates: 1,0.636,0,0.486,0,0.638,1,0.774
        loitering_time: 0
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      filters:
        cat:
          min_score: 0.6
        dog:
          min_score: 0.6
    review:
      alerts:
        required_zones:
          - frontyard_enter
        labels:
          - person
          - car
          - bicycle
          - motorcycle
objects:
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog
    - bicycle
    - bird
  filters:
    person:
      min_score: 0.6
      min_area: 5000
    bird:
      min_score: 0.75
record:
  events:
    retain:
      default: 30
      objects:
        person: 90
    pre_capture: 10
    post_capture: 10
snapshots:
  retain:
    default: 30
    objects:
      person: 90
birdseye:
  enabled: true
version: 0.14
review:
  alerts:
    labels:
      - cat
      - dog
```

### Relevant Frigate log output

```shell
None.
```

### Relevant go2rtc log output

```shell
None.
```

### FFprobe output from your camera

```shell
root@8274376c5c97:/opt/frigate# ffprobe rtsp://127.0.0.1:8554/driveway 
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5fd733ddb140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/driveway':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.080000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 tbr, 90k tbn
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0,"audio_rms":0,"camera_fps":5,"capture_pid":605,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":2520870,"pid":575,"process_fps":5,"skipped_fps":0},"driveway":{"audio_dBFS":0,"audio_rms":0,"camera_fps":5,"capture_pid":619,"detection_enabled":true,"detection_fps":5.6,"ffmpeg_pid":2520804,"pid":597,"process_fps":5,"skipped_fps":0},"frontdoor":{"audio_dBFS":0,"audio_rms":0,"camera_fps":5.1,"capture_pid":610,"detection_enabled":true,"detection_fps":0.3,"ffmpeg_pid":2520840,"pid":576,"process_fps":5.1,"skipped_fps":0},"laundrydoor":{"audio_dBFS":0,"audio_rms":0,"camera_fps":5,"capture_pid":614,"detection_enabled":true,"detection_fps":3.4,"ffmpeg_pid":2520868,"pid":587,"process_fps":5,"skipped_fps":0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"105":{"cmdline":"python3 -u -m frigate","cpu":"3.5","cpu_average":"2","mem":"8.9"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"122":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"178":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"179":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"18":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"180":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"181":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2520774":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"1.3","cpu_average":"1","mem":"0.2"},"2520804":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.7","cpu_average":"2","mem":"1.2"},"2520840":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontdoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontdoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.5","cpu_average":"2","mem":"1.2"},"2520868":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/laundrydoor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/laundrydoor@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.5","cpu_average":"2","mem":"1.2"},"2520870":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.7","cpu_average":"2","mem":"1.2"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2719856":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2720266":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2720376":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"278":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"350":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.0"},"352":{"cmdline":"frigate.recording_manager","cpu":"2.3","cpu_average":"1","mem":"1.9"},"354":{"cmdline":"frigate.review_segment_manager","cpu":"0.3","cpu_average":"0","mem":"0.1"},"381":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.1","cpu_average":"0","mem":"0.0"},"382":{"cmdline":"frigate.detector.coral","cpu":"1.1","cpu_average":"1","mem":"0.1"},"384":{"cmdline":"frigate.output       ","cpu":"2.0","cpu_average":"2","mem":"0.3"},"410":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"492":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"497":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"502":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"517":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"575":{"cmdline":"frigate.process:backyard","cpu":"0.9","cpu_average":"2","mem":"0.4"},"576":{"cmdline":"frigate.process:frontdoor","cpu":"1.2","cpu_average":"2","mem":"0.6"},"587":{"cmdline":"frigate.process:laundrydoor","cpu":"2.9","cpu_average":"3","mem":"0.4"},"597":{"cmdline":"frigate.process:driveway","cpu":"7.3","cpu_average":"5","mem":"0.8"},"605":{"cmdline":"frigate.capture:backyard","cpu":"2.0","cpu_average":"1","mem":"0.1"},"610":{"cmdline":"frigate.capture:frontdoor","cpu":"1.9","cpu_average":"1","mem":"0.1"},"614":{"cmdline":"frigate.capture:laundrydoor","cpu":"1.8","cpu_average":"1","mem":"0.1"},"619":{"cmdline":"frigate.capture:driveway","cpu":"1.8","cpu_average":"1","mem":"0.1"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"875":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"5.7","mem":"32.8"}},"detection_fps":9.4,"detectors":{"coral":{"detection_start":0,"inference_speed":6.23,"pid":382}},"gpu_usages":{"NVIDIA GeForce GTX 1070":{"dec":"7.0%","enc":"0.0%","gpu":"1.0%","mem":"10.15%"}},"processes":{"go2rtc":{"pid":94},"logger":{"pid":350},"recording":{"pid":352},"review_segment":{"pid":354}},"service":{"last_updated":1728895611,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":239.1,"mount_type":"tmpfs","total":256,"used":16.9},"/media/frigate/clips":{"free":2969086.4,"mount_type":"ext4","total":3754443.8,"used":594569},"/media/frigate/recordings":{"free":2969086.4,"mount_type":"ext4","total":3754443.8,"used":594569},"/tmp/cache":{"free":38894.5,"mount_type":"overlay","total":111596.2,"used":66987.8}},"temperatures":{"apex_0":63.3},"uptime":604548,"version":"0.14.1-f4f3cfa"}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/htpc/config/frigate/:/config/
      - /mnt/cameras:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Swann DVR4-4480V

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/3941934c-e2d9-4cf5-9d65-9440840eab43)
![image](https://github.com/user-attachments/assets/bc006d82-4e84-478c-9a02-3bee140db0a8)
![image](https://github.com/user-attachments/assets/b76ca434-5fb6-4792-9684-254a1172c88c)

### Any other information that may be helpful

Review alert or detection, return to UI, detection may disappear from list.
I think the issue may relate to stationary vehicles being constantly detected?

**Comment by hawkeye217** [comment]
As the release notes for 0.14 make clear, reviewed alerts and detections are hidden after they are reviewed. You can flip the "Show reviewed" switch to show them all again. The green chip in the top left corner indicates if they are reviewed. 

If you are saying that they "completely disappear", can you provide screenshots with an example?

**Comment by tehsquid** [comment]
Yeah, this is with the switch toggled.  I'm still having alerts and detections disappear randomly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tehsquid** [comment]
Hard to provide a screenshot as it something that's not there, and I'm not consistently seeing the behaviour.

As an example, there should be events between 5:30 and 5:55PM in the attached screenshot, but they have disappeared:

![image](https://github.com/user-attachments/assets/83df6852-5344-4c3b-b087-7f48e9e49b24)

**Reply by hawkeye217** [reply]
Review items are consolidated from your tracked objects. Are you only seeing the "lost" review items with cars?

**Reply by NickM-27** [reply]
this is a similar issue to  https://github.com/blakeblackshear/frigate/discussions/14089#discussioncomment-10809633

in 0.14 detections are not considered events when you have required zones set for alerts, so because you don't have continuous recording configured it is being deleted. For now you can solve this by adding continuous recording for only active objects. In the next version of frigate this config will be much easier to set and understand 

```
record:
  retain:
    days: 30
    mode: active_objects
  events:
    retain:
      default: 30
      objects:
        person: 90
    pre_capture: 10
    post_capture: 10
```
