### DISCUSSION TITLE
Define Cameras IP/credentials in frigate.yaml

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#14336] [Ask A Question] [answered]
Is it possible to define Camera credentials (IP and rtsp options) at the top of FRIGATE.YAML? Then replace the input path with the Camera_Profile name?

````
Camera_Profile:
    Road_main: rtsp://admin:passwd@192.168.0.222:8554/profile0
    Road_sub: rtsp://admin:passwd@192.168.0.222:8554/profile1

    Old_Driveway:
      - rtsp://192.168.0.187:554/user=admin_password=passwd_channel=0_stream=1.sdp?real_stream

  cameras:
     Road:
          inputs:
        - path: Road_sub       
          roles:
            - detect
        - path: Road_main
        - roles:
            - record
```
