### DISCUSSION TITLE
[Support]: h265 Camera recordings stop playing back after elapsed time

### DISCUSSION THREAD

**Discussion by mbaran5** [blakeblackshear/frigate#14342] [General Support]
### Describe the problem you are having

I am seeing a similar issue to https://github.com/blakeblackshear/frigate/discussions/14309 with an h265 cam and go2rtc where certain videos will never play. When I first launch frigate, everything works well. At some point, my ability to play back recordings fails. When opening a single .mp4 file from the affected period I get a file ~10MB in size but thinks it has a ~4h duration, seen below. My config is very simple with one camera right now as I've been testing, also below. If I restart Frigate, thinks seem to work well for a little bit then choke again. 

![image](https://github.com/user-attachments/assets/ed21bf82-c193-4329-8b91-eae0e94bc9d8)

![image](https://github.com/user-attachments/assets/980649f3-376f-4c34-8c88-9b242f49a468)

note: even though the stream is named h264Preview_01_main, the resulting data is hevc.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Edge 130.0.2849.35, Chrome 129.0.6668.100

### Frigate config file

```yaml
audio:
  enabled: True

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

review:
  alerts:
    labels:
      - person
      - speech

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    Front:
      - rtsp://user:pass@192.168.1.68:554/h264Preview_01_main
    Front_sub:
      - rtsp://user:pass@192.168.1.68:554/h264Preview_01_sub

cameras:
  Front:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/Front_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: True
    zones: {}
    motion:
      threshold: 30
      contour_area: 31
      improve_contrast: true

objects:
  track:
    - car
    - truck
    - person
    - cat
    - dog
version: 0.14
```

### Relevant Frigate log output

```shell
2024-10-14 09:41:45.458881504  [INFO] Preparing Frigate...
2024-10-14 09:41:45.502816453  [INFO] Starting Frigate...
2024-10-14 09:41:47.331439170  [2024-10-14 09:41:47] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-14 09:41:47.331475907  [2024-10-14 09:41:47] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-14 09:41:47.344146073  [2024-10-14 09:41:47] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-14 09:41:47.719567420  [2024-10-14 09:41:47] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-10-14 09:41:48.690743396  [h264 @ 0x4af05c0] Overread VUI by 8 bits
2024-10-14 09:41:50.101025192  [2024-10-14 09:41:50] peewee_migrate.logs            INFO    : Starting migrations
2024-10-14 09:41:50.101559410  [2024-10-14 09:41:50] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-14 09:41:50.416166085  [2024-10-14 09:41:50] frigate.app                    INFO    : Recording process started: 566
2024-10-14 09:41:50.416283139  [2024-10-14 09:41:50] frigate.app                    INFO    : Recording process started: 568
2024-10-14 09:41:50.418455631  [2024-10-14 09:41:50] frigate.app                    INFO    : go2rtc process pid: 98
2024-10-14 09:41:50.446220164  [2024-10-14 09:41:50] frigate.app                    INFO    : Output process started: 596
2024-10-14 09:41:50.450864488  [2024-10-14 09:41:50] detector.ov                    INFO    : Starting detection process: 594
2024-10-14 09:41:50.502104445  [2024-10-14 09:41:50] frigate.app                    INFO    : Camera processor started for Front: 610
2024-10-14 09:41:50.502927319  [2024-10-14 09:41:50] frigate.app                    INFO    : Capture process started for Front: 611
2024-10-14 09:41:50.510820113  [2024-10-14 09:41:50] frigate.app                    INFO    : Audio process started: 620
```

### Relevant go2rtc log output

```shell
2024-10-14 09:41:45.474794135  [INFO] Preparing new go2rtc config...
2024-10-14 09:41:45.997445600  [INFO] Starting go2rtc...
2024-10-14 09:41:46.113963457  09:41:46.113 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-10-14 09:41:46.113970580  09:41:46.113 INF config path=/dev/shm/go2rtc.yaml
2024-10-14 09:41:46.114102790  09:41:46.114 INF [rtsp] listen addr=:8554
2024-10-14 09:41:46.114423573  09:41:46.114 INF [webrtc] listen addr=:8555/tcp
2024-10-14 09:41:46.115362662  09:41:46.114 INF [api] listen addr=:1984
2024-10-14 09:41:55.460127904  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
root@6af8abe56970:/opt/frigate# ffprobe "rtsp://localhost:8554/Front?video=copy&audio=aac"
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5b1c640b8140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://localhost:8554/Front?video=copy&audio=aac':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 4096x1152, 20 fps, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
[1]+  Done                    ffprobe rtsp://localhost:8554/Front?video=copy
root@6af8abe56970:/opt/frigate#
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 64mb # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hdd/nvr/frigate/config:/config
      - /mnt/hdd/nvr/frigate/video:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: password
networks: {}
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Reolink Duo 3 POE

**Comment by hawkeye217** [comment]
On some cameras, the discrepancy between media length and size is often due to the use of a "smart codec" that severely alters the [keyframe interval](https://gardinal.net/understanding-the-keyframe-interval/) on the footage.

I've seen this with Hikvision's "+" codecs, but I don't own a Reolink to be able to confirm. Can you check your camera's settings to see if there's any kind of "smart codec" enabled?

**Reply by mbaran5** [reply]
clips that I can successfully playback via the UI have the correct data. it's only the clips that fail to play that show 10+ hours in duration at only 10MB in size. 

![image](https://github.com/user-attachments/assets/07982e89-2d7c-4ed8-85c2-a71661ed5431)

On the Reolink side, it appears to be standard CBR ,1x keyframes. 

![image](https://github.com/user-attachments/assets/3f605436-92d7-4ac6-b237-38de45b10562)

**Reply by mbaran5** [reply]
I also get this error from Edge/Chrome

<html>
<body>

"Failed to reconcile encoded audio times with decoded output."
--



</body>
</html>

**Reply by hawkeye217** [reply]
Does it help if you use go2rtc's ffmpeg source? Like:

```
go2rtc:
  streams:
    Front:
      - ffmpeg:rtsp://user:pass@192.168.1.68:554/h264Preview_01_main
    Front_sub:
      - ffmpeg:rtsp://user:pass@192.168.1.68:554/h264Preview_01_sub
```

**Reply by mbaran5** [reply]
I've made the change and will let it run for the day and see.

**Reply by mbaran5** [reply]
this seems to have helped, as we're now on the 2nd day and my ability to review alerts and detections is still working including audio.

That said, this may (I can't say I tested before fully as it was so tempermental) have introduced a decent audio delay, maybe 1-2s. Is there a way to try to get that closer to sync?

**Reply by hawkeye217** [reply]
You could try a few things.

First, try using go2rtc's aac transcoder:

```
go2rtc:
  streams:
    Front:
      - ffmpeg:rtsp://user:pass@192.168.1.68:554/h264Preview_01_main#video=copy#audio=aac
    Front_sub:
      - ffmpeg:rtsp://user:pass@192.168.1.68:554/h264Preview_01_sub#video=copy#audio=aac
```

If that still produces undesirable results, try using `#async`. I'm not sure if this parameter still exists in the current go2rtc version, though.


```
go2rtc:
  streams:
    Front:
      - ffmpeg:rtsp://user:pass@192.168.1.68:554/h264Preview_01_main#video=copy#audio=aac#async
    Front_sub:
      - ffmpeg:rtsp://user:pass@192.168.1.68:554/h264Preview_01_sub#video=copy#audio=aac#async
```
