### DISCUSSION TITLE
[HW Accel Support]: Unable to get GPU status under sriov

### DISCUSSION THREAD

**Discussion by xemxx** [blakeblackshear/frigate#14356] [Hardware Acceleration Support]
### Describe the problem you are having

I started frigate with a simple configuration with only one camera providing h265 streams and configured hardware acceleration.

But I found some error logs about getting the GPU state

I observe that my GPU is actually working, via the command

```bash
intel_gpu_top -d sriov
```
<img width="1943" alt="image" src="https://github.com/user-attachments/assets/78c9be30-a3dc-446e-b2e4-0a5f616b62ab">

My OS environment is lxc deployed based on pve and running docker, configured sriov support on pve and passthrough raw gpu to lxc, then running frigate on docker.

I'll make sure no other programs are using the gpu on my machine.

I think this should be fixable.

Your help would be appreciated, thanks!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 5
    mode: all

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

snapshots:
  enabled: false
  retain:
    default: 30

detect:
  enabled: false

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
cameras:
  tp-link:
    enabled: true
    ffmpeg:
      inputs:
        - path: hidden
          roles:
            - record
            - detect
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on   calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
```

### Relevant Frigate log output

```shell
frigate  | 2024-10-15 17:02:18.434368645  [2024-10-15 17:02:18] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to detect engines! (No such file or directory)
frigate  | 2024-10-15 17:02:18.434374816  (Kernel 4.16 or newer is required for i915 PMU support.)
frigate  | 2024-10-15 17:02:18.434377845  timeout: the monitored command dumped core
```

### Relevant go2rtc log output

```shell
nothing
```

### FFprobe output from your camera

```shell
ok
```

### Install method

Proxmox via Docker

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

 TP-link  TL-IPC44AW-COLOR 6.0

### Screenshots of the Frigate UI's System metrics pages

<img width="1956" alt="image" src="https://github.com/user-attachments/assets/6d8ef309-5d29-4934-a41d-4905613419db">
<img width="1956" alt="image" src="https://github.com/user-attachments/assets/b6f13551-60f4-4b9c-bfbf-0cac5625093e">

### Any other information that may be helpful

My  PVE

<img width="1283" alt="image" src="https://github.com/user-attachments/assets/13006ad4-780d-4106-ac6f-e986702d84c8">
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/fe6eba4e-8db2-482e-aa2b-61430c9a11da">

My docker lxc

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/a43ddf3b-90e9-473f-8cf9-fb31f20cee13">
