### DISCUSSION TITLE
[Support]: Unable to View Clips on iPhone from Notification Blueprint

### DISCUSSION THREAD

**Discussion by johnlento** [blakeblackshear/frigate#14363] [General Support] [answered]
### Describe the problem you are having

I am using the Blueprint linked off the main frigate page here: https://community.home-assistant.io/t/frigate-mobile-app-notifications-2-0/559732 in order to push notifications for iOS devices via Home Assistant. The integration appears to work however when I click it from iOS it redirects me to my home assistant install to view the clip. The clip never plays in Safari on iOS and just gives me a play button with a slash through it. If I send the link to my Windows desktop then the clip plays fine. 

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Safari iPhone 12 Max

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
mqtt:
  host: 192.168.9.10
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  enabled: true
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_GARAGE_PASSWORD}@192.168.11.13:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_GARAGE_PASSWORD}@192.168.11.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
  backyard_south:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_S_PASSWORD}@192.168.11.14:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_S_PASSWORD}@192.168.11.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: false
  backyard_north:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_N_PASSWORD}@192.168.11.15:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_N_PASSWORD}@192.168.11.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: false
  south_basement:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_USER}@192.168.40.249:554/12
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_USER}@192.168.40.249:554/11
          roles:
            - record
    detect:
      enabled: true
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_DOORBELL_PASSWORD}@192.168.11.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_DOORBELL_PASSWORD}@192.168.11.11:554/
          roles:
            - record
    detect:
      enabled: true
version: 0.14
```

### Relevant Frigate log output

```shell
No relevant output.
```

### Relevant go2rtc log output

```shell
No relevant output.
```

### FFprobe output from your camera

```shell
Not relevant.
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "300mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/captain/frigate/config.yaml:/config/config.yaml
      - /home/captain/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
```

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

Dahua DH-DB6I

### Screenshots of the Frigate UI's System metrics pages

<img width="1360" alt="Screenshot 2024-10-15 080910" src="https://github.com/user-attachments/assets/239b629c-3f58-4b18-8109-c341d7115f30">

### Any other information that may be helpful

![signal-2024-10-15-080753](https://github.com/user-attachments/assets/c8b6b687-385c-4c26-911a-a14b8b2c7f6a)
