### DISCUSSION TITLE
Utilize 3rd GPU

### DISCUSSION THREAD

**Discussion by ves1120** [blakeblackshear/frigate#14379] [Ask A Question] [answered]
Followed solution from https://github.com/blakeblackshear/frigate/discussions/7792#discussioncomment-7059216 for 2 GPUs which supported up to 60 camera feeds. Tried to add 10 more on a third gpu but appeared to have maxed out vram on all 3 gpus.

![frig2 nvidia-smi2](https://github.com/user-attachments/assets/4a1bb6af-6d41-4af0-b909-06978d555d49)

Streams divided between the 3 GPUs using config from #7792.
GPU0 = 30
GPU1 = 21
GPU2 = 18

```
ffmpeg:
  input_args: preset-rtsp-restream
  hwaccel_args: preset-nvidia-h264

go2rtc:
 ffmpeg:
   cuda0: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 0 -rtsp_transport tcp -i {input}"
   cuda1: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 1 -rtsp_transport tcp -i {input}"
   cuda2: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 2 -rtsp_transport tcp -i {input}"

  streams:
    cam1:
      - rtsp://xxx/Streaming/Channels/101
    cam1Rtc:
      - "ffmpeg:cam1#input=cuda1#video=h264#raw=-fpsmax 10 -gpu 1#hardware=cuda"
```

Also tried using ffmpeg directly.
```
    cam2Rtc:
      - "ffmpeg:rtsp://xxx/Streaming/Channels/101#input=cuda0#video=h264#raw=-fpsmax 10 -gpu 0#hardware=cuda"
```

Have I hit some sort of limit? The web gui only shows 2 gpus btw.

Errors
```
[AVHWDeviceContext @ 0x5d1d8eee53c0] cu->cuCtxCreate(&hwctx->cuda_ctx, desired_flags, hwctx->internal->cuda_device) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory

[h264 @ 0x63ba4df85000] No device available for decoder: device type cuda needed for codec h264.

Device creation failed: -542398533.

Device setup failed for decoder on input stream #0:0 : Generic error in an external library
```

**Comment by NickM-27** [comment]
What error are you getting?

**Reply by ves1120** [reply]
Ah right forgot about that. Updated post.
I didn't keep a copy of the logs when I had the full config. Switched to non gpu version to record for now `ghcr.io/blakeblackshear/frigate:stable`.
Some of the errors may not be relevant. I do remember seeing `CUDA_ERROR_OUT_OF_MEMORY` previously.

Errors
```
[AVHWDeviceContext @ 0x5d1d8eee53c0] cu->cuCtxCreate(&hwctx->cuda_ctx, desired_flags, hwctx->internal->cuda_device) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory

[h264 @ 0x63ba4df85000] No device available for decoder: device type cuda needed for codec h264.

Device creation failed: -542398533.

Device setup failed for decoder on input stream #0:0 : Generic error in an external library
```

**Reply by NickM-27** [reply]
Are you changing hwaccel args / global args too or trying to use the same GPU for decoding?

**Reply by ves1120** [reply]
Not familiar with ffmpeg or hwaccel args. Using whatever I see here or in the docs.

1. Is it better to use a different GPU for decoding?
2. Is it possible to use software decoding when I run out of GPU VRAM? eg. `-hwaccel none`

**Reply by NickM-27** [reply]
You can set hwaccel_args: [] to disable it. If you posted your full config it would be easy to make a suggestion

**Comment by ves1120** [comment]
Tried `hwaccel_args: []` on some cameras and increased count to 69.

GPU1 = 30
GPU2 = 24
CPU = 15

```
detectors:
  cuda:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

birdseye:
  enabled: false

detect:
  enabled: false

record:
  enabled: true
  retain:
    days: 35
    mode: all

ffmpeg:
  input_args: preset-rtsp-restream
  hwaccel_args: preset-nvidia-h264

go2rtc:
 ffmpeg:
   cuda1: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 1 -rtsp_transport tcp -i {input}"
   cuda2: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 2 -rtsp_transport tcp -i {input}"

 streams:
    #============================================== GPU 1 ==================================================
    cam01:
      - rtsp://xxx/Streaming/Channels/101
    cam01Rtc:
      - "ffmpeg:cam01#input=cuda1#video=h264#raw=-fpsmax 10 -gpu 1#hardware=cuda"

    #============================================== GPU 2 ==================================================
    cam02:
      - rtsp://xxx/Streaming/Channels/101
    cam02Rtc:
      - "ffmpeg:cam02#input=cuda2#video=h264#raw=-fpsmax 10 -gpu 2#hardware=cuda"

    #============================================== CPU ====================================================
    cam03:
      - rtsp://xxx/Streaming/Channels/101
    cam03Rtc:
      - "ffmpeg:cam03#video=h264"
    C01_Carpark:
      - rtsp://xxx/Streaming/Channels/101
    C01_CarparkRtc:
      - "ffmpeg:C01_Carpark#video=h264#width=5120#height=1440"
  
cameras:
  #============================================== GPU 1 ==================================================
  cam01: #------------------------------------
    ffmpeg:

      inputs:
        - path: rtsp://127.0.0.1:8554/cam01Rtc
          roles:
            - record
  #============================================== GPU 2 ==================================================
  cam02: #------------------------------------
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam02Rtc
          roles:
            - record

  #============================================== CPU ====================================================
  cam03: #------------------------------------
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://127.0.0.1:8554/cam03Rtc
          roles:
            - record
  C01_Carpark: #------------------------------------
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://127.0.0.1:8554/C01_CarparkRtc
          roles:
            - record

version: 0.14
```

![frig gpu consum3](https://github.com/user-attachments/assets/a1f41257-e50d-4bd8-9753-3703975f55c2)


1. Is it correct to assume that go2rtc will create a ffmpeg stream for detection even when detection is turned off globally? If so, how do you turn off detection completely? skip go2rtc? The way it's currently configured, only 7 more cameras can be added before GPU0 is maxed out with detection streams.
3. I included `C01_Carpark` because of error msgs displayed when running on GPU. Probably a ffmpeg limitation `Video width 5120 not within range from 48 to 4096`. Any ffmpeg or go2rtc workarounds to make it work on cuda?

In one of the iterations while trying different things:
```
2024-10-18 10:56:42.353729629  10:56:42.353 WRN [rtsp] error="streams: exec: 
[h264 @ 0x60ec53b40340] Video width 5120 not within range from 48 to 4096\n
[h264 @ 0x60ec53b40340] Failed setup for format cuda: hwaccel initialisation returned error.\n
[h264_nvenc @ 0x60ec53ad4a00] Provided device doesn't support required NVENC features\n
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0
 - maybe incorrect parameters such as bit_rate, rate, width or height\n" stream=C01_CarparkRtc
```
Otherwise it's a repeat of the following:
```
2024-10-18 15:17:35.027433428  [2024-10-18 15:17:35] frigate.video                  ERROR   : C01_Carpark: Unable to read frames from ffmpeg process.
2024-10-18 15:17:35.028621498  [2024-10-18 15:17:35] frigate.video                  ERROR   : C01_Carpark: ffmpeg process is not running. exiting capture thread...
2024-10-18 15:17:39.911457279  [2024-10-18 15:17:39] watchdog.C01_Carpark           ERROR   : Ffmpeg process crashed unexpectedly for C01_Carpark.
2024-10-18 15:17:39.911464696  [2024-10-18 15:17:39] watchdog.C01_Carpark           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-10-18 15:17:39.911467343  [2024-10-18 15:17:39] ffmpeg.C01_Carpark.detect      ERROR   : rtsp://127.0.0.1:8554/C01_CarparkRtc: Invalid data found when processing input
```

Error goes away when `hwaccel_args` is empty and whole server seems stable besides a few warning msgs during boot `Unable to read frames from ffmpeg process.`

**Reply by NickM-27** [reply, marked as answer]
You can use more just need to set global args at the camera level to set which GPU to use. There should be an example on that or a similar post asking about multiple gpus

**Reply by ves1120** [reply]
Thank you. Used config from https://github.com/blakeblackshear/frigate/discussions/13693#discussioncomment-10661280

``` yaml
cameras:
  cam01:
    ffmpeg:
      global_args: -hide_banner -loglevel warning -threads 2 -hwaccel_device 0
```
