### DISCUSSION TITLE
My Frigate storage is full in a day, Frigate stops working.

### DISCUSSION THREAD

**Discussion by askmurphy** [blakeblackshear/frigate#14373] [Ask A Question]
Hello,
I like Frigate a lot, I have 3 camera's and I do some recordings (2 days max)..
BUT: my storage is full in 1 a 2 days too, is there an option to limit the storage space with something like: max storage = 100GB, and that the oldest recordings are erased when there is 10% left ?

**Comment by NickM-27** [comment]
You limit storage based on number of days. If you're not recording continuously then it sounds like you need to tune motion detection, but we can't help without seeing your config

**Comment by askmurphy** [comment]
Ok, here is is, I removed 2 camera's, so the config is not too large:
```

#############################################################################################################
mqtt:
  enabled: true
  host: 192.168.1.20
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: secret1
  stats_interval: 60
#############################################################################################################
#database:
#  path: /config/frigate.db
#############################################################################################################
timestamp_style:
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  effect: shadow
#############################################################################################################
go2rtc:
  streams:
    Zijdeur_reolink_doorbell:
    - ffmpeg:https://192.168.1.36/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=me&password=secret2
    - rtsp://me:secret2@192.168.1.36:554/Preview_01_sub
    - ffmpeg:doorbell#audio=opus # required by WebRTC # this doesn’t work: #audio=volume
      ffmpeg:
      bin: ffmpeg
      volume: "-af \"volume=30dB\""
#############################################################################################################
cameras:
  Zijdeur_reolink_doorbell:
    enabled: true
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        - path: rtsp://me:secret2@192.168.1.36:554/h264Preview_01_sub
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 1024 # <---- update for your camera's resolution
      fps: 10
    objects:
      track:
        - person
        - face
        - cat
        - dog
        - package
        - bird
        - motorcycle
        - horse
    record:
      enabled: True
      retain:
        days: 5        # Number of days to retain recordings
      events:
        retain:
          default: 10  # Retain event-based recordings for 10 days

    # Configure snapshots
    snapshots:
      enabled: True
      retain:
        default: 10  # Retain snapshots for 10 days
      bounding_box: True
      timestamp: True  
#############################################################################################################
detectors:
  coral:
    type: edgetpu
    device: usb
#############################################################################################################
```
