### DISCUSSION TITLE
Using Frigate and Double Take to ring virtual door bell

### DISCUSSION THREAD

**Discussion by mofman** [blakeblackshear/frigate#14377] [Ask A Question]
I appreciate this is more relating to Double Take and Home Assistant but thought it would be valuable to this dicussion too.

I'm trying to get a virtual door bell to ring when double take detects  an unknown face in a specific camera (and zone)

What are the steps I need to take in order for this to work? I already have double take entities appearing in home assistant

This is the sort of idea I have in Home Assistant below...

```
homekit:
  filter:
    include_entities:
      - camera.front_door
  entity_config:
    camera.front_door:
      linked_doorbell_sensor: sensor_double_take_unkown && sensor_double_take_front_door
      video_codec: copy
      support_audio: True
```
