### DISCUSSION TITLE
[Config Support]: Require a Bearer Token for Public Frigate Notification API

### DISCUSSION THREAD

**Discussion by johnlento** [blakeblackshear/frigate#14372] [Config Support]
### Describe the problem you are having

My home assistant installation and WebUI is public to ensure certain webhooks and other features work appropriately. I noticed that that Notification API listed here: https://docs.frigate.video/integrations/home-assistant#notification-api is truly public. Is there a way to have the API require a bearer token like the other HA APIs?

### Version

 0.14.1-f4f3cfa

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
mqtt:
  host: 192.168.9.10
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  enabled: true
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
objects:
  track:
    - person
    - fedex
    - ups
    - amazon
    - deer
    - face
    - package
    - license_plate
    - car
cameras:
  garage:
    ffmpeg:
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_GARAGE_PASSWORD}@192.168.11.13:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - audio
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_GARAGE_PASSWORD}@192.168.11.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
  backyard_south:
    ffmpeg:
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_S_PASSWORD}@192.168.11.14:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - audio
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_S_PASSWORD}@192.168.11.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: false
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: true
  backyard_north:
    ffmpeg:
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_N_PASSWORD}@192.168.11.15:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - audio
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_BACKYARD_N_PASSWORD}@192.168.11.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: false
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: true
  south_basement:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_USER}@192.168.40.249:554/12
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_USER}@192.168.40.249:554/11
          roles:
            - record
    detect:
      enabled: true
  doorbell:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_DOORBELL_PASSWORD}@192.168.11.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - audio
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_DOORBELL_PASSWORD}@192.168.11.11:554/
          roles:
            - record
    detect:
      enabled: true
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
version: 0.14
```

### Relevant Frigate log output

```shell
Not relevant.
```

### Relevant go2rtc log output

```shell
Not relevant.
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "300mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/captain/frigate/config.yaml:/config/config.yaml
      - /home/captain/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
```

### Object Detector

TensorRT

### Any other information that may be helpful

None.
