### DISCUSSION TITLE
[Camera Support]: Unable to get two way audio working on Imou Cameras

### DISCUSSION THREAD

**Discussion by aaronjrodrigues** [blakeblackshear/frigate#14383] [Camera Support]
### Describe the problem you are having

I have two Imou ranger camera's and I've added them into frigate and I'm able to view my camera feed, head audio, etc. But for some reason it seems two way audio isn't working as I don't see a mic icon when clicking on the camera. I know for sure that it supports two way audio because I am able to do so when using the Imou app.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Safari 18.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.116
  port: 1883
  user: mqtt
  password: redacted

model:
  path: plus://redacted

objects:
  track:
    - person
    - dog
    - cat
    - car
    - license_plate

snapshots:
  enabled: true

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    cam1:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/101
    cam2:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/701
    cam3:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/301
    cam4:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/401
    cam5:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/501
    cam6:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/601
    cam7:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/201
    cam8:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/801
    cam9:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/901
    cam10:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/1301
    cam11:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/1101
    cam12:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/1201
    cam13:
      - rtsp://admin: redacted@192.168.1.137:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:cam13#audio=opus"
    cam14:
      - rtsp://admin: redacted@192.168.1.142:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:cam14#audio=opus"
    cam15:
      - rtsp://admin: redacted@192.168.1.144:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:cam15#audio=opus"
    low1:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/102
    low2:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/702
    low3:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/302
    low4:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/402
    low5:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/502
    low6:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/602
    low7:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/202
    low8:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/802
    low9:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/902
    low10:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/1302
    low11:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/1102
    low12:
      - rtsp://admin: redacted@192.168.1.160:554/Streaming/Channels/1202
    low13:
      - rtsp://admin: redacted@192.168.1.137:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    low14:
      - rtsp://admin: redacted@192.168.1.142:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    low15:
      - rtsp://admin: redacted@192.168.1.144:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
  webrtc:
    candidates:
      - 192.168.1.115:8555
      - stun:8555
      - redacted:8555
      - redacted:8555

cameras:
  cam1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low1
          roles:
            - detect
        - path: rtsp://localhost:8554/cam1
          roles:
            - record
    detect:
      enabled: true
  cam2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low2
          roles:
            - detect
        - path: rtsp://localhost:8554/cam2
          roles:
            - record
    detect:
      enabled: true
  cam3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low3
          roles:
            - detect
        - path: rtsp://localhost:8554/cam3
          roles:
            - record
    detect:
      enabled: true
  cam4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low4
          roles:
            - detect
        - path: rtsp://localhost:8554/cam4
          roles:
            - record
    detect:
      enabled: true
  cam5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low5
          roles:
            - detect
        - path: rtsp://localhost:8554/cam5
          roles:
            - record
    detect:
      enabled: true
  cam6:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low6
          roles:
            - detect
        - path: rtsp://localhost:8554/cam6
          roles:
            - record
    detect:
      enabled: true
  cam7:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low7
          roles:
            - detect
        - path: rtsp://localhost:8554/cam7
          roles:
            - record
    detect:
      enabled: true
  cam8:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low8
          roles:
            - detect
        - path: rtsp://localhost:8554/cam8
          roles:
            - record
    detect:
      enabled: true
  cam9:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low9
          roles:
            - detect
        - path: rtsp://localhost:8554/cam9
          roles:
            - record
    detect:
      enabled: true
  cam10:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low10
          roles:
            - detect
        - path: rtsp://localhost:8554/cam10
          roles:
            - record
    detect:
      enabled: true
  cam11:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low11
          roles:
            - detect
        - path: rtsp://localhost:8554/cam11
          roles:
            - record
    detect:
      enabled: true
  cam12:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low12
          roles:
            - detect
        - path: rtsp://localhost:8554/cam12
          roles:
            - record
    detect:
      enabled: true
  cam13:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low13
          roles:
            - detect
        - path: rtsp://localhost:8554/cam13#backchannel=0
          roles:
            - record
    detect:
      enabled: true
  cam14:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low14
          roles:
            - detect
        - path: rtsp://localhost:8554/cam14#backchannel=0
          roles:
            - record
    detect:
      enabled: true
  cam15:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low15
          roles:
            - detect
        - path: rtsp://localhost:8554/cam15#backchannel=0
          roles:
            - record
    detect:
      enabled: true

version: 0.14

camera_groups: {}
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Imou Ranger

### Screenshots of the Frigate UI's System metrics pages

<img width="1268" alt="Screenshot 2024-10-16 at 14 34 43" src="https://github.com/user-attachments/assets/1b25186a-f1d1-44d5-99ca-72eb29e7f566">
