### DISCUSSION TITLE
[Detector Support]: Tensorrt INT8 operations

### DISCUSSION THREAD

**Discussion by bludhemn** [blakeblackshear/frigate#14384] [Detector Support]
Hi, 

Not really a problem, but I was wondering what would be required to enable INT8 operations, as per this [link](https://docs.frigate.video/configuration/object_detectors#minimum-hardware-support)?

> If you wish to use newer features such as INT8 optimization, more work is required.

I am running yolov7x-320 on an Nvidia 3060.  

All these models produce seg faults:
yolov7-tiny-416
yolov7-640
yolov7x-640

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false
auth:
  enabled: False

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

record:
  enabled: true
  retain:
    days: 15
    mode: motion
  events:
    retain:
      default: 20
      mode: motion

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10
    mode: all

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7
    car:
      min_area: 20000
      max_area: 200000
      threshold: 0.7

go2rtc:
  streams:
    garage1:
      - rtsp://123:123@10.0.1.182:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:back#video=h264
    driveway:
      - rtsp://123:123@10.0.1.181:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:back#video=h264
    deck:
      - rtsp://123:123@10.0.1.180:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:back#video=h264
    reo:
      - ffmpeg:https://10.0.1.159/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=123&password=123#video=copy#audio=copy#audio=opus
    reo_sub:
      - ffmpeg:https://10.0.1.159/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=123&password=123

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reo
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reo_sub
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - detect
    motion:
      mask: 
        0.364,0.241,0.355,0.494,0.484,0.437,0.728,0.427,0.728,0.335,0.663,0.327,0.6,0.142
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://123:123@10.0.1.181:554/cam/realmonitor?channel=1&subtype=0
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - record
        - path: rtsp://123:123@10.0.1.181:554/cam/realmonitor?channel=1&subtype=1
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576
      max_disappeared: 25
    best_image_timeout: 10
    motion:
      mask: 
        0.003,0.578,0.152,0.306,0.362,0.233,0.416,0.289,0.244,0.705,0.121,0.783,0.012,0.944
    zones:
      driveway-zone:
        coordinates: 0.152,0.996,0.459,0.208,0.571,0.208,0.624,0.28,0.73,0.255,0.761,0.615,0.771,1
        loitering_time: 5
        inertia: 3
        objects:
          - bicycle
          - car
          - motorcycle
          - person
    review:
      alerts:
        required_zones: driveway-zone

  garage1:
    ffmpeg:
      inputs:
        - path: rtsp://123:123@10.0.1.182:554/cam/realmonitor?channel=1&subtype=0
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - record
        - path: rtsp://123:123@10.0.1.182:554/cam/realmonitor?channel=1&subtype=1
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576
      stationary:
        interval: 50
        threshold: 50
    best_image_timeout: 10

    zones:
      garage-zone:
        coordinates: 
          0.117,0.207,0.1,0.299,0.162,0.996,0.997,0.992,0.995,0.336,0.963,0.216,0.973,0.008,0.337,0.002
        loitering_time: 0
        objects:
          - car
          - motorcycle
          - person
  deck:
    ffmpeg:
      inputs:
        - path: rtsp://123:123@10.0.1.180:554/cam/realmonitor?channel=1&subtype=0
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - record
        - path: rtsp://123:123@10.0.1.180:554/cam/realmonitor?channel=1&subtype=1
          input_args: -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps
            1
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576

    motion:
      mask: 0.069,0.308,0.266,0.135,0.238,0,0.134,0.04,0.048,0.097
      threshold: 30
      contour_area: 14
      improve_contrast: true
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "250mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/appdata/frigate/config:/config
      - /data/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/dri/renderD128
    environment:
      YOLO_MODELS: "yolov7-tiny-288,yolov7-tiny-416,yolov7-640,yolov7-320,yolov7x-640,yolov7x-320"
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![Screenshot_2024-10-16_22-39-10](https://github.com/user-attachments/assets/0c0ded22-26c8-4d9f-aab8-b4afced37e22)
