### DISCUSSION TITLE
Empiretech/Dahua cameras - Slow in Home Assistant

### DISCUSSION THREAD

**Discussion by deliverer33** [blakeblackshear/frigate#14392] [Config Support]
### Describe the problem you are having

I have everything working, but playing back video in Home Assistant is extremely slow.  It will take anywhere from 30-60 seconds to start a video.  The same video from the Frigate web interface loads instantly.  Any ideas on what might be wrong?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci:0

#Global Object Settings
objects:
  track:
    - person
    - car
    - dog

snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

birdseye:
  enabled: true
  mode: motion

go2rtc:
  streams:
    Patio_High:
      - rtsp://admin:password@192.168.4.20:554/cam/realmonitor?channel=1&subtype=0
    Patio_Low:
      - rtsp://admin:password@192.168.4.20:554/cam/realmonitor?channel=1&subtype=2
    Front_Center_High:
      - rtsp://admin:password@192.168.4.25:554/cam/realmonitor?channel=1&subtype=0
    Front_Center_Low:
      - rtsp://admin:password@192.168.4.25:554/cam/realmonitor?channel=1&subtype=2
    Front_Right_High:
      - rtsp://admin:password@192.168.4.23:554/cam/realmonitor?channel=1&subtype=0
    Front_Right_Low:
      - rtsp://admin:password@192.168.4.23:554/cam/realmonitor?channel=1&subtype=2
    Front_Left_High:
      - rtsp://admin:password@192.168.4.26:554/cam/realmonitor?channel=1&subtype=0
    Front_Left_Low:
      - rtsp://admin:password192.168.4.26:554/cam/realmonitor?channel=1&subtype=2

cameras:
  Patio: # <--- this will be changed to your actual camera later
    webui_url: https://192.168.4.20
    objects:
      track:
        - person
        - dog
        - car
        - deer
    ffmpeg:
      inputs:
       ## High Resolution
        - path: rtsp://127.0.0.1:8554/Patio_High # subnet
          roles:
            - record
       ## Low Resolution
        - path: rtsp://127.0.0.1:8554/Patio_Low # subnet
          roles:
            - detect
            - audio
    audio:
      enabled: true
  Front_Center: # <--- this will be changed to your actual camera later
    webui_url: https://192.168.4.25
    objects:
      track:
        - person
        - dog
        - car
        - deer
    ffmpeg:
      inputs:
       ## High Resolution
        - path: rtsp://127.0.0.1:8554/Front_Center_High # subnet
          roles:
            - record
       ## Low Resolution
        - path: rtsp://127.0.0.1:8554/Front_Center_Low # subnet
          roles:
            - detect
            - audio
    audio:
      enabled: true
  Front_Right: # <--- this will be changed to your actual camera later
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Right_High # subnet
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Right_Low # subnet
          roles:
            - detect
    onvif:
      host: 192.168.4.23
      port: 80
      user: admin
      password: password
      autotracking:
        enabled: true
        calibrate_on_startup: false
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: relative
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.50
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - Front_Right_Zone
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: Preset1
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 15
        # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
        movement_weights: 0.04, 1.0, 1.0418295860290527, 1.2608747169535648, 0.3684004699030233

    zones:
      Front_Right_Zone:
        coordinates: 0.99,0.05,0.987,0.941,0.027,0.912,0,0.052,0.407,0.027
        loitering_time: 5
    review:
      alerts:
        required_zones: Front_Right_Zone
  Front_Left: # <--- this will be changed to your actual camera later
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Left_High # subnet
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Left_Low # subnet
          roles:
            - detect
    onvif:
      host: 192.168.4.26
      port: 80
      user: admin
      password: password
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: relative
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.50
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - Front_Left_Zone
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: Preset1
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 15
        # Optional: modify these manually. (default: shown below)
        movement_weights: 0.04, 1.0, 0.819617509841919, 1.3141255768396525, -0.03828837794642279

    zones:
      Front_Left_Zone:
        coordinates: 1,0.985,1,0.679,1,0.242,0,0.493,0,1
        loitering_time: 5
    review:
      alerts:
        required_zones: Front_Left_Zone
version: 0.14
camera_groups:
  BirdsEye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
No errors on Frigate or HA side
```

### Relevant go2rtc log output

```shell
warning
Timestamp
2024-10-16 10:32:40
Tag
startup
Message
github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225 > error="parse \"\\xe0\\x97\\xbb`X\\xb0+\\xed\\xac&\\xe7]\\xd2r\\xf9,\\xba4\\x83\\xee>O1\\f\\xae\\xf6G\\x1b\\xa0\\t2\\xc9\\x00\": net/url: invalid control character in URL"
```

### Frigate stats

```json
{
  "cameras": {
    "Front_Center": {
      "audio_dBFS": -30.5612,
      "audio_rms": 971.3873,
      "camera_fps": 5,
      "capture_pid": 587,
      "detection_enabled": true,
      "detection_fps": 4.8,
      "ffmpeg_pid": 6285,
      "pid": 554,
      "process_fps": 5,
      "skipped_fps": 0
    },
    "Front_Left": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 597,
      "detection_enabled": true,
      "detection_fps": 28.6,
      "ffmpeg_pid": 6341,
      "pid": 569,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "Front_Right": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 591,
      "detection_enabled": true,
      "detection_fps": 25,
      "ffmpeg_pid": 6289,
      "pid": 560,
      "process_fps": 5.1,
      "skipped_fps": 0
    },
    "Patio": {
      "audio_dBFS": -52.0603,
      "audio_rms": 81.7399,
      "camera_fps": 5.1,
      "capture_pid": 584,
      "detection_enabled": true,
      "detection_fps": 2.8,
      "ffmpeg_pid": 6260,
      "pid": 552,
      "process_fps": 5.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "114": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "115": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "2.2",
      "cpu_average": "1",
      "mem": "0.4"
    },
    "132": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "158": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "161": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "162": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "2043": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "315": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "3588": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "3682": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "385": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "464": {
      "cmdline": "frigate.recording_manager",
      "cpu": "3.2",
      "cpu_average": "3",
      "mem": "0.2"
    },
    "473": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "491": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "492": {
      "cmdline": "frigate.detector.coral",
      "cpu": "5.2",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "494": {
      "cmdline": "frigate.output       ",
      "cpu": "2.4",
      "cpu_average": "5",
      "mem": "0.1"
    },
    "514": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "519": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "524": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "529": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "535": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "1",
      "mem": "0.0"
    },
    "552": {
      "cmdline": "frigate.process:Patio",
      "cpu": "3.5",
      "cpu_average": "4",
      "mem": "0.2"
    },
    "554": {
      "cmdline": "frigate.process:Front_Center",
      "cpu": "4.4",
      "cpu_average": "5",
      "mem": "0.2"
    },
    "560": {
      "cmdline": "frigate.process:Front_Right",
      "cpu": "20.2",
      "cpu_average": "5",
      "mem": "0.2"
    },
    "569": {
      "cmdline": "frigate.process:Front_Left",
      "cpu": "19.4",
      "cpu_average": "9",
      "mem": "0.2"
    },
    "584": {
      "cmdline": "frigate.capture:Patio",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "587": {
      "cmdline": "frigate.capture:Front_Center",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "591": {
      "cmdline": "frigate.capture:Front_Right",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "597": {
      "cmdline": "frigate.capture:Front_Left",
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "605": {
      "cmdline": "frigate.audio_manager",
      "cpu": "1.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "6260": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Patio_Low -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "0.0"
    },
    "6262": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Patio_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Patio@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "6272": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Patio_Low -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "6273": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Center_Low -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "6285": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Center_Low -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "6287": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Center_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Center@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "6289": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Right_Low -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.0"
    },
    "6293": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Right_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Right@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "6341": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Left_Low -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "0.1"
    },
    "6343": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front_Left_High -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Left@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "85": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "6.8",
      "cpu_average": "6",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "5.1",
      "mem": "62.2"
    }
  },
  "detection_fps": 61.2,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 9.94,
      "pid": 492
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.54%",
      "mem": "-%"
    }
  },
  "processes": {
    "audio_detector": {
      "pid": 605
    },
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 385
    },
    "recording": {
      "pid": 464
    },
    "review_segment": {
      "pid": 473
    }
  },
  "service": {
    "last_updated": 1729093386,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 240.1,
        "mount_type": "tmpfs",
        "total": 256,
        "used": 15.9
      },
      "/media/frigate/clips": {
        "free": 21355368.9,
        "mount_type": "zfs",
        "total": 22740906.1,
        "used": 1385537.2
      },
      "/media/frigate/recordings": {
        "free": 21355368.9,
        "mount_type": "zfs",
        "total": 22740906.1,
        "used": 1385537.2
      },
      "/tmp/cache": {
        "free": 757.5,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 196.2
      }
    },
    "temperatures": {
      "apex_0": 47.3
    },
    "uptime": 59166,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

UNRAID

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Not sure how to get this in unraid?  I have screenshots but can't attach here.
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![metrics](https://github.com/user-attachments/assets/1e6e33c8-4865-4421-bb54-5d6feec750c0)
