### DISCUSSION TITLE
[Config Support]:How to use my local Database

### DISCUSSION THREAD

**Discussion by Aadi4401** [blakeblackshear/frigate#14402] [Config Support]
### Describe the problem you are having

I want to connect my local database to Frigate so it can store data in it. Can someone guide me on the steps to do this? Also, which file do I need to modify to make this change?

### Version

version: 0.14

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  school1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://flowers:12345678/abcd # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
  school2: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://flowers:12345678/abcd # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
  school3: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://flowers:12345678/abcd # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false 
      width: 1280
      height: 720
  school4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://flowers:12345678/abcd # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false 
      width: 1280
      height: 720
# database:
#   path: C:\Users\adars\Frigate_NVR.db 
version: 0.14
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
# version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      #   /path/to/your/config:/config
      # - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral
