### DISCUSSION TITLE
Recording does not cover full preview

### DISCUSSION THREAD

**Discussion by vespaman** [blakeblackshear/frigate#14407] [General]
So after a couple of days, I am so impressed by frigate, and how well it operates on a low power EQ13 (N100) box.

However, I have one issue that I don't understand;
I have one camera (HikVision) that has a very crappy (low res) second stream, so I decided to use the normal screen scaled down for detection instead (don't know if this is related, though).
This works well, the detector detects me early in walking towards the camera, and the preview shows it.
But:- the recording (non-scaled) does not contains the first (5-8?) seconds of the preview, so it is missing important stuff.

Is there anything I can do to remedy this, and/or is this related to the scaling? I'd rather not change the camera, since it is mounted high up, and the picture (4k) is rather good. Can I manually add some pre-recording?

Thanks

**Comment by NickM-27** [comment]
this will be a config issue

**Comment by vespaman** [comment]
So, yesterday, I added "pre_capture:  10" to the camera->record section in my config, but still similar result. I.e. the review lowres sequence is perfect, but the "full" recording is missing a lot in the beginning. 
Since the review video is a scaled down of the full stream, I would have thought start/stop time would be identical, or at least similar? 

Is there a way to see the trigger point in the review video, so one know how much to add onto the recording?


Edit: maybe I am in the wrong forum, but I did not find a way to move it.

**Reply by NickM-27** [reply]
You should show your config so we can see why this might be happening

> Since the review video is a scaled down of the full stream, I would have thought start/stop time would be identical, or at least similar?

No, they come from entirely different sources

**Comment by vespaman** [comment]
OK, config looks like this;

```
~/frigate/config $ cat config.yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  entrance_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pwd@10.1.200.18:554/Streaming/Channels/101/
          roles:
            - detect
        - path: rtsp://admin:pwd@10.1.200.18:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true
    record:
      enabled: true
      events:
        pre_capture: 10

```
The stream at 101 is setup as follows;
![image](https://github.com/user-attachments/assets/d8c478e2-a3b9-47cd-b12e-ec42526ec5bb)

**Reply by NickM-27** [reply]
So the preview includes a buffer before the object is detected for what is shown in the ui. Pre capture only applies if the retention mode still matches. If you add

```
record:
  enabled: true
  events:
    retain:
      mode: all
    pre_capture: 10
```
