### DISCUSSION TITLE
[Camera Support]: Dahua C5A (Firefox Liveview Issue)

### DISCUSSION THREAD

**Discussion by mofman** [blakeblackshear/frigate#14408] [Camera Support]
### Describe the problem you are having

I've just bought a Dahua C5A camera from Ali Express, its a H.265 camera but I have changed it to H.264 using the Config Tool.

My issue is that when I try to use live view or feeds using Firefox, its seems to revert to the basic jpeg view that that you get when not using go2rtc. As Firefox doesnt support H.265 I assume this could be the issue although the go2rtc seems to be getting the correct stream and even the exports appear to be in H.264.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 130

### Frigate config file

```yaml
mqtt:
  host: localhost
  port: 1883

go2rtc:
  streams:
    Front_of_House:
      - rtsp://admin:xxxxx@192.168.0.112/live0
    Kitchen:
      - rtsp://admin:xxxxx@192.168.0.176/live0
    Kitchen_New:
      - rtsp://admin:xxxxxx@192.168.0.249:554/cam/realmonitor?channel=1&subtype=0
    Front_Door:
      - rtsp://admin:xxxxx@192.168.0.186/live0
    Front_Door_Tapo:
      - rtsp://admin1:xxxxx1@192.168.0.195:554/stream1
    Back_of_House:
      - rtsp://admin:xxxxx@192.168.0.165/live0
  homekit:
    Back_of_House:
      device_id: eufy1
      device_private: eufy1
      name: Back of House
      pin: 12345678
      pairings:
        - client_id=xxxxxx&client_public=xxxxx&permissions=1
        - client_id=xxxxxx&client_public=xxxxx&permissions=0
    Front_of_House:
      device_id: eufy2
      device_private: eufy2
      name: Font of House
      pin: 12345678
      pairings:
        - client_id=xxxxxx&client_public=xxxxx&permissions=1
        - client_id=xxxxxx&client_public=xxxxx&permissions=0
    Front_Door:
      device_id: eufy3
      device_private: eufy3
      name: Front Door
      pin: 12345678
      pairings:
        - client_id=xxxxxx&client_public=xxxxx&permissions=1
        - client_id=xxxxxx&client_public=xxxxx&permissions=0
    Kitchen:
      device_id: eufy4
      device_private: eufy4
      name: Kitchen
      pin: 12345678
      pairings:
        - client_id=xxxxxx&client_public=xxxxx&permissions=1
        - client_id=xxxxxx&client_public=xxxxx&permissions=0


detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 7

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

cameras:
  Kitchen_New:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen_New
  Front_Door_Tapo:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door_Tapo
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask: 0,0.556,1,0.522,1,0,0,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  Front_of_House:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_of_House
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 0,0,1,0,1,0.434,0.513,0.46,0,0.462
        - 0.629,0.785,0.703,1,1,1,0.878,0.815,0.746,0.843,0.689,0.768
  Kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask: 0.705,0.063,1,0.065,1,0,0.704,0.002
  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask: 0,0,0,0.38,1,0.366,1,0
    zones:
      Visitor:
        coordinates: 0.286,0.251,0.369,0.426,0.538,0.535,0.531,1,0,1,0,0.255
        loitering_time: 4
        objects: person
        inertia: 3
  Back_of_House:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_of_House
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask: 0,0,0,0.467,0.111,0.579,0.312,0.606,0.643,0.627,0.907,0.603,1,0.507,1,0

version: 0.14
```

### Relevant Frigate log output

```shell
x
```

### Relevant go2rtc log output

```shell
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.0.249:554/cam/realmonitor?channel=1\u0026subtype=0/",
      "remote_addr": "192.168.0.249:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 2229913047 2229913047 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-summary:Oversea\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:25.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0032;sprop-parameter-sets=Z00AMukAWgGb88IAAAMAAgAAAwBlCAA=,aOqMbIAA\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=5\r\na=rtpmap:8 PCMA/8000\r\na=sendonly\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.0",
        "audio, recvonly, MPEG4-GENERIC/8000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=107358782, senders=1",
        "97 MPEG4-GENERIC/8000, bytes=535769, senders=1"
      ],
      "senders": [
        "8 PCMA/8000, bytes=0, receivers=0"
      ],
      "recv": 108855135
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/Kitchen_New",
      "remote_addr": "127.0.0.1:56880",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0032;sprop-parameter-sets=Z00AMukAWgGb88IAAAMAAgAAAwBlCAA=,aOqMbIAA\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=107358782, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=535769, receivers=1"
      ],
      "send": 109175095
    }
  ]
}
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x7fd8ac00a000] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://192.168.0.101:8554/Kitchen_New':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2880x1620, 25 fps, 25 tbr, 90k tbn, 50 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua C5A

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-10-17 at 14-28-27 Cameras Stats - Frigate](https://github.com/user-attachments/assets/d54de05c-e0ac-4357-b0d8-5f2974851af4)
![Screenshot 2024-10-17 at 14-28-05 General Stats - Frigate](https://github.com/user-attachments/assets/efb61770-0fd6-4a5f-acdd-3065b1c0e52a)

**Comment by hawkeye217** [comment]
Have you ruled out Firefox by trying another browser?

**Reply by mofman** [reply]
Sorry I should have clarified that, yea it works perfectly in Chrome...

**Reply by mofman** [reply]
Also I can watch the stream perfectly using the go2rtc web interface from Firefox:

http://192.168.0.101:1984/stream.html?src=Kitchen_New

**Reply by hawkeye217** [reply]
What streaming technology type does go2rtc show it's using when you watch it from there?

**Reply by mofman** [reply]
It shows as RTC

**Reply by hawkeye217** [reply]
Frigate's Live view prioritizes MSE first (as it's the most supported and widely compatible). If the MSE stream can't be loaded, it then tries WebRTC (if set up in your Frigate config). If that fails, it finally falls back to jsmpeg.

It still seems like there's something with the camera's codec that Firefox doesn't like, since the go2rtc web interface also tries MSE first.

If you still wanted to use Firefox without any other changes to your camera, you could [configure WebRTC in Frigate](https://docs.frigate.video/configuration/live/#webrtc-extra-configuration).

**Comment by mofman** [comment]
To be fair I have 3 types brands of cameras set up in go2rtc and when I view them all using go2rtc they all use RTC to stream after first attempting MSE - just the Dahua is causing me problems.

**Reply by hawkeye217** [reply]
Right, so as I said if you set up WebRTC in your Frigate config, Frigate will use that in Firefox without any camera changes.

**Reply by mofman** [reply]
I'm just a little confused as to how the rest of the cameras are all working with Frigate when they are using the same mode. 

I did try this already and it hasnt made any improvement, but Im not 100% sure if I've done this correctly...

```
go2rtc:
  webrtc:
    candidates:
      - 192.168.0.101:8555
      - stun:8555
```


```
version: '3'
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: always
    network_mode: host
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate:/config
      - /mnt/PVR/Recordings:/media/frigate/recordings
      - /mnt/PVR/Temp:/tmp/cache
      - /mnt/PVR/Exports:/media/frigate/export
      - /mnt/PVR/Clips:/media/frigate/clips
    ports:
      - "5000:5000"
```

**Reply by hawkeye217** [reply]
Firefox could also be failing on the audio codec, but if it's working fine on Chrome, it seems more likely there's something still odd with the video codec. 

If you open Firefox's devtools and examine the websocket's response when you open Live view, that will give us more information.

Open your browser dev tools to the Network pane, select the WS option to only view websockets, and look for a `ws?src=<camera_name>` entry. Click on that entry, and then choose the "Response" tab in the inspector pane.

You should see video data coming through the socket on Chrome, but this will probably only show a few lines on Firefox.

It'd be helpful to see a screenshot of the first few entries of this pane, just as you start streaming a single camera.

**Comment by mofman** [comment]
Spotted something intesting, I'm using an nginx reverse proxy, if I access the WebUI directly using the port, I get a proper video feed in firefox (although it takes at least 10 seconds to initiate it seems ffmpeg is transcoding it which isn't ideal etiher)


**Firefox**
<img width="908" alt="Screenshot 2024-10-17 at 17 27 21" src="https://github.com/user-attachments/assets/8ff98e11-40eb-4cf3-a9ee-965e9a6a2ede">
<img width="909" alt="Screenshot 2024-10-17 at 17 27 36" src="https://github.com/user-attachments/assets/b648e3f9-ec9a-4a4c-a919-61efffdaa8da">

**Chrome**
<img width="1315" alt="Screenshot 2024-10-17 at 17 31 11" src="https://github.com/user-attachments/assets/eac194c1-0fc8-4976-9c27-0c4c5141a384">
<img width="1319" alt="Screenshot 2024-10-17 at 17 31 21" src="https://github.com/user-attachments/assets/8ae26766-9863-48da-8fec-316788d305e9">




```
  location /frigate/ {
      proxy_http_version 1.1;
      proxy_cache_bypass $http_upgrade;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
      proxy_set_header Host $http_host;
      proxy_set_header X-Ingress-Path "/frigate";
      proxy_set_header Authorization "";
      proxy_pass http://127.0.0.1:5000/;
      access_log off;
  }
```

**Reply by hawkeye217** [reply]
Ah, the reverse proxy is why. You need to enable websockets through the proxy. 

See the docs: https://docs.frigate.video/guides/reverse_proxy/#setup-reverse-proxy-settings

**Reply by mofman** [reply]
Okay I've been able to get WebRTC working through firefox, I think it may have been a caching issue but I reflashed the firmware and changed its IP address. 

My main issue with it though even though it using WebRTC there is a 10-15 delay when initalizing the camera in liveview. When using the go2rtc WebUI this is almost instant even while using WebRTC, is there a reason why Frigate takes so long initialize WebRTC in liveview or is there anything I can try to get MSE working on the camera in Firefox?

**Reply by hawkeye217** [reply]
There's a few helpful points in the Live view [recommended camera settings](https://docs.frigate.video/configuration/live/#camera-settings-recommendations), but you'll want to make sure you've set the i-frame interval to be the same as your framerate.

According to your screenshots, MSE data is streaming, so nothing is wrong from Frigate's end. Were those screenshots from the direct/non-proxied connection, though?

**Reply by mofman** [reply]
Odd because Firefox dev tools shows MSE yet go2rtc shows its using RTC as shown below (both screenshot below are using reverse proxy)
<img width="957" alt="Screenshot 2024-10-17 at 21 22 30" src="https://github.com/user-attachments/assets/071e810d-9903-4200-9328-7997e0baa190">

Screenshots of go2rtc of both firefox and chrome streaming from frigate liveview
<img width="967" alt="Screenshot 2024-10-17 at 21 00 23" src="https://github.com/user-attachments/assets/28f75ee5-c329-4ceb-a778-9e8cce01b24d">

**Reply by hawkeye217** [reply]
If you look at the timestamps there in the devtools pane, you'll see there's no data arriving between 21:20:12.922 and 21:20:14.140. But if you look back at your non-proxied screenshot, data is uninterrupted and is streaming quickly.

Frigate prioritizes showing you a live view as quickly as possible, so when Frigate doesn't receive enough data in time, it tries switching stream types. That's what's happening in your case.

**Reply by mofman** [reply]
I'm not sure that is what is happening here, I've recorded a quick video of loading the stream non proxied via frigate and go2rtc and you can see aabout 15 second delay with Frigate while its instant in go2rtc, then you can see the consumers in go2rtc are both using RTC...

**Reply by hawkeye217** [reply]
Frigate attempts to use MSE first. When that fails (in your case, times out), it attempts WebRTC. That's where your delay in Frigate is coming from.

**Reply by mofman** [reply]
Okay I think I understand better now, it might be an idea to implement an option for which mode to use for edge cases like this, but personally I'm probably going to return this camera, appreciate all your assistance today, have a much clearer understanding of whats happening now.

**Reply by hawkeye217** [reply]
For some other possible solutions to try to nail down the cause of the lag, you can try:

1) Disabling audio temporarily.
2) Transcoding to h264 in go2rtc, eg: `- ffmpeg:rtsp://admin:xxxxxx@192.168.0.249:554/cam/realmonitor?channel=1&subtype=0#video=h264#audio=aac#hardware`
3) Lowering the resolution and/or bitrate.

However, because MSE streams successfully without the proxy, there's something related to that which may be the ultimate cause.

With that said, I'm happy to have helped in some way!

**Comment by jrb80** [comment]
I am thinking about buying the [Dahua C5A camera](https://www.dahuasecurity.com/products/All-Products/Network-Cameras/Wireless-Series/NEW-Channel/Indoor-Camera/Cube-Series/C5A), can you confirm it supports local API? 

A few examples

Get firmware version
`
curl --user admin:<password> --digest http://<IP address>:80/cgi-bin/magicBox.cgi?action=getSoftwareVersion
`

Get camera name
`
curl --user admin:<password> --digest http://<IP address>:80/cgi-bin/magicBox.cgi?action=getMachineName
`

**Comment by stilsch** [comment]
Mine is running fine with this config:

```
cameras:
  cam_Dahua_C5A:
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:<PW>@<IP>:554/cam/realmonitor?channel=1&subtype=0    #h265 hevc yuv420p 2880x1620 25fps, pcm_alaw, 8000 Hz, mono, s16, 64 kb/s 
          roles:
            - record
        - path: 
            rtsp://admin:<PW>@<IP>:554/cam/realmonitor?channel=1&subtype=1    #h264 yuv420p 640x360 25fps, pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
          roles:
            - detect
    record:
      enabled: true
    detect:
      enabled: true
    objects:
      filters:
        person: {}
```
