### DISCUSSION TITLE
[Detector Support]: labelmap for Frigate+ yolonas model

### DISCUSSION THREAD

**Discussion by zoechi** [blakeblackshear/frigate#14418] [Detector Support]
### Describe the problem you are having

I just generated my first model. I used yolonas with OpenVINO.
The docs https://docs.frigate.video/configuration/object_detectors/#yolo-nas say with such a model the label_map should be `labelmap_path: /labelmap/coco-80.txt`
I don't know what a labelmap is or does and also not where I should get that `coco-80.txt` file from.
I installed Frigate using NixOS which includes `coco_91cl_bkgr.txt` and `labelmap.txt`.

What is the purpose of the labelmap and how should this be resolved?

Currently I have `coco_91cl_bkgr.txt` configured and I don't get an error. 
Are there any disadvantages of using not the labelmap as suggested in the docs?

### Version

0.14.1

### Frigate config file

```yaml
birdseye:
  enabled: true
  mode: continuous
  restream: true
cameras:
  cam_east_north:
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://[fd00::2:12]:8554/cam_east_north
        roles:
        - audio
      - input_args: preset-rtsp-restream
        path: rtsp://[fd00::2:12]:8554/cam_east_north_sub
        roles:
        - detect
        - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam_east_north
    motion:
      contour_area: 10
      mask:
      - 0.284,0.086,0.295,0,0.434,0,0.449,0.108,0.439,0.149,0.402,0.182,0.343,0.105,0.303,0.147,0.281,0.218
  cam_garage_north:
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://[fd00::2:12]:8554/cam_garage_north
        roles:
        - audio
      - input_args: preset-rtsp-restream
        path: rtsp://[fd00::2:12]:8554/cam_garage_north_sub
        roles:
        - detect
        - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam_garage_north
    motion:
      mask:
      - 0.025,0.334,0,0.426,0,0.692,0.07,0.697,0.12,1,0,1,0,0.285
  cam_west:
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://[fd00::2:12]:8554/cam_west
        roles:
        - audio
      - input_args: preset-rtsp-restream
        path: rtsp://[fd00::2:12]:8554/cam_west_sub
        roles:
        - detect
        - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam_west
    motion:
      contour_area: 20
      mask:
      - 0.232,0.002,0.23,0.27,0.33,0.305,0.39,0.394,0.462,0.299,0.556,0.347,0.57,0.152,0.645,0
database:
  path: /var/lib/frigate/frigate.db
detectors:
  ov:
    device: CPU
    type: openvino
ffmpeg: {}
model:
  height: 300
  input_pixel_format: bgr
  input_tensor: nchw
  labelmap_path: /nix/store/c5rnwjs7l79q5z993whrfri3vb6ri0h8-frigate-0.14.1/share/frigate/coco_91cl_bkgr.txt
  path: plus://373d2276296b9a115937117a0eb568e7
  width: 300
mqtt:
  enabled: true
  host: mqtt-ipv6.zburbach.eu
  password: '{FRIGATE_MQTT_PASSWORD}'
  user: frigate
objects:
  track:
  - person
  - car
  - dog
  - cat
  - deer
record:
  enabled: true
  events:
    post_capture: 8
    pre_capture: 5
    retain:
      default: 400
      mode: active_objects
  retain:
    days: 11
    mode: all
review:
  alerts:
    labels:
    - person
    - car
    - dog
    - deer
snapshots:
  bounding_box: true
  enabled: true
  retain:
    default: 400
  timestamp: true
timestamp_style:
  format: '%Y-%m-%d %H:%M:%S'
  position: tl
ui:
  date_style: short
  strftime_fmt: '%Y-%m-%d %H:%M'
  time_format: 24hour
  time_style: short
```

### docker-compose file or Docker CLI command

```yaml
Installed using NixOS, there is no such file
```

### Relevant Frigate log output

```shell
none
```

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

Shouldn't be neccessary
