### DISCUSSION TITLE
[Config Support]: Go2RTC CPU Usage Normal?

### DISCUSSION THREAD

**Discussion by EPiSKiNG** [blakeblackshear/frigate#14415] [Config Support]
### Describe the problem you are having

I'm a bit curious to see if I can lower my overall power consumption on my 14th gen Intel Core 155h / Arc GPU, running bare metal Ubuntu Server 24.04 with coral and GPU.

Running 10 8MP cameras at full resolution/frames/quality for storage and substreams at lower resolution (640x360 and 6fps).  I do have a couple of devices that are monitoring the video feeds via the Home Assistant Frigate Card, and none are viewing the substreams at this point.

Config, hardware info and screenshot of stats page attached.

Thanks for any assistance!! Much appreciated!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
version: 0.14

mqtt:
  host: [ip address] # <---- same mqtt broker that home assistant uses
  user: user
  password: password

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat
    - car
    - bicycle

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  streams:
    pergola: rtsp://admin:Password@LAN.IP.SUB.201:554/Streaming/channels/101
    pergola_sub: rtsp://admin:Password@LAN.IP.SUB.201:554/Streaming/channels/102

    front_walkway: rtsp://admin:Password@LAN.IP.SUB.202:554/Streaming/channels/101
    front_walkway_sub: rtsp://admin:Password@LAN.IP.SUB.202:554/Streaming/channels/102

    northwest_lawn: rtsp://admin:Password@LAN.IP.SUB.203:554/Streaming/channels/101
    northwest_lawn_sub: rtsp://admin:Password@LAN.IP.SUB.203:554/Streaming/channels/102

    front_door: rtsp://admin:Password@LAN.IP.SUB.205:554/Streaming/channels/101
    front_door_sub: rtsp://admin:Password@LAN.IP.SUB.205:554/Streaming/channels/102

    bedroom_slider: rtsp://admin:Password@LAN.IP.SUB.208:554/Streaming/channels/101
    bedroom_slider_sub: rtsp://admin:Password@LAN.IP.SUB.208:554/Streaming/channels/102

    driveway: rtsp://admin:Password@LAN.IP.SUB.209:554/Streaming/channels/101
    driveway_sub: rtsp://admin:Password@LAN.IP.SUB.209:554/Streaming/channels/102

    living_room_slider: rtsp://admin:Password@LAN.IP.SUB.211:554/Streaming/channels/101
    living_room_slider_sub: rtsp://admin:Password@LAN.IP.SUB.211:554/Streaming/channels/102

    backyard: rtsp://admin:Password@LAN.IP.SUB.212:554/Streaming/channels/101
    backyard_sub: rtsp://admin:Password@LAN.IP.SUB.212:554/Streaming/channels/102

    side_yard: rtsp://admin:Password@LAN.IP.SUB.214:554/Streaming/channels/101
    side_yard_sub: rtsp://admin:Password@LAN.IP.SUB.214:554/Streaming/channels/102

    closet: rtsp://admin:Password@LAN.IP.SUB.216:554/stream1
    closet_sub: rtsp://admin:Password@LAN.IP.SUB.216:554/stream2
    


  webrtc:
    candidates:
      - ip.addr.sub.net:8555
      - ip.addr.sub.net:8555
      - stun:8555

cameras:
  front_door:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0101
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0102
          roles:
            - detect
    live:
      stream_name: front_door
    zones:
      zone_front_yard:
        coordinates: 0.197,1,0.806,1,0.661,0.833,0.767,0,0.338,0
        inertia: 3
        loitering_time: 0

  front_walkway:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
      mask: 0,0.397,0.596,0.725,0.755,1,1,1,1,0,0,0,0,0.194
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_walkway  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0301
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_walkway_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0302
          roles:
            - detect
    live:
      stream_name: front_walkway
    zones:
      zone_front_yard:
        coordinates: 0,1,0.741,1,0.694,0.894,0.616,0.739,0.465,0.667,0,0.43,0,0.678
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.429,0,0,1,0,1,0,1,1,0.807,1,0.741,1,0.627,0.748

  side_yard:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_yard  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1301
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_yard_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1302
          roles:
            - detect
    live:
      stream_name: side_yard
    zones:
      zone_side_yard:
        coordinates: 0,1,1,1,1,0,0.502,0,0.334,0,0.291,0.594
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.781,0.382,0.423,0.341,0,0,0

  driveway:
    detect:
      width: 640
      height: 360
      fps: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1501
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1502
          roles:
            - detect
    live:
      stream_name: driveway
    zones:
      zone_driveway:
        coordinates: 0,1,1,1,1,0.589,0.52,0.189,0.389,0.111,0,0.253
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.353,0.452,0.133,1,0.536,1,0.4,1,0,0,0

  bedroom_slider:
    detect:
      width: 360
      height: 640
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_slider  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1001
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroom_slider_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1002
          roles:
            - detect
    live:
      stream_name: bedroom_slider
    zones:
      zone_patio:
        coordinates: 0.194,1,1,1,1,0.291,0.397,0.105
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,1,0,0,0.372,0,0.531,0,0.5,0.232,0.363,0.258,0.334,1

  living_room_slider:
    detect:
      width: 360
      height: 640
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_slider  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0901
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_slider_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0902
          roles:
            - detect
    live:
      stream_name: living_room_slider
    zones:
      zone_patio:
        coordinates: 0,0,0.517,0,0.516,0.242,0,0.245
        inertia: 3
        loitering_time: 0
      zone_living_patio:
        coordinates: 0,1,0.607,1,0.702,0.236,0,0.195
        inertia: 3
        loitering_time: 0

  pergola:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
      mask: 0.576,0.332,0.794,0.413,1,0.476,1,0.066,0.458,0.066,0.449,0.233
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pergola  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1101
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pergola_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1102
          roles:
            - detect
    live:
      stream_name: pergola
    zones:
      zone_pergola:
        coordinates: 
          0,0.731,0,1,0.348,1,0.419,0.492,0.522,1,1,1,0.898,0.55,0.87,0.5,0.9,0.323,0.927,0.533,0.898,0.551,1,1,1,0.096,0.745,0.12,0.6,0.241,0.218,0.276,0,0.388
        inertia: 3
        loitering_time: 0

  closet:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/closet  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1101
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/closet_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1102
          roles:
            - detect
    live:
      stream_name: closet
    zones:
      zone_closet:
        coordinates: 0.159,0.076,0.174,0.943,0.382,0.943,0.397,0.057
        loitering_time: 0
        inertia: 6

  northwest_lawn:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/northwest_lawn  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1301
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/northwest_lawn_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1302
          roles:
            - detect
    live:
      stream_name: northwest_lawn
    zones:
      zone_backyard:
        coordinates: 0,1,0.62,1,0.209,0.298,0.665,0.165,0.686,0,0.334,0,0,0,0,0.533
        inertia: 3
        loitering_time: 0
  backyard:
    detect:
      width: 640
      height: 360
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1301
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/1302
          roles:
            - detect
    live:
      stream_name: backyard
    zones:
      zone_backyard:
        coordinates: 0,0.614,0.68,0.412,0.701,0,0.502,0,0.334,0,0,0
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,1,1,1,1,0.319,1,0,0.707,0,0.674,0.429,0,0.613
```

### Relevant Frigate log output

```shell
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSliceLPnVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSliceLPnVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile0:tVAEntrypointEncSliceLPnVAProfileVP9Profile1:tVAEntrypointVLDnVAProfileVP9Profile1:tVAEntrypointEncSliceLPnVAProfileVP9Profile2:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointEncSliceLPnVAProfileVP9Profile3:tVAEntrypointVLDnVAProfileVP9Profile3:tVAEntrypointEncSliceLPnVAProfileHEVCMain12:tVAEntrypointVLDnVAProfileHEVCMain422_10:tVAEntrypointVLDnVAProfileHEVCMain422_12:tVAEntrypointVLDnVAProfileHEVCMain444:tVAEntrypointVLDnVAProfileHEVCMain444:tVAEntrypointEncSliceLPnVAProfileHEVCMain444_10:tVAEntrypointVLDnVAProfileHEVCMain444_10:tVAEntrypointEncSliceLPnVAProfileHEVCMain444_12:tVAEntrypointVLDnVAProfileHEVCSccMain:tVAEntrypointVLDnVAProfileHEVCSccMain:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain10:tVAEntrypointVLDnVAProfileHEVCSccMain10:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain444:tVAEntrypointVLDnVAProfileHEVCSccMain444:tVAEntrypointEncSliceLPnVAProfileAV1Profile0:tVAEntrypointVLDnVAProfileAV1Profile0:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain444_10:tVAEntrypointVLDnVAProfileHEVCSccMain444_10:tVAEntrypointEncSliceLP"}
```

### Relevant go2rtc log output

```shell
No anomalies
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
#version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    cap_add:
      - CAP_PERFMON
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
     # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/username/frigate/config/:/config/
      - /media/frigate-storage/:/media/frigate/
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 10000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984/tcp" # Go2RTC over tcp
      - "1984:1984/udp" # Go2RTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "thisismypassword"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/7bfd7f66-948c-4947-82a0-3fbaffc7abc1)

**Comment by NickM-27** [comment]
yes, restreaming an 8mp stream uses non-negligible amounts of CPU resources

**Comment by EPiSKiNG** [comment]
I'm re-streaming?  When I turn off the devices that are viewing the Frigate Card in Home Assistant, I don't see any change in CPU usage...  Viewing the Go2RTC panel shows a single connection to the Go2RTC stream... I suppose I could remove Go2RTC altogether, and then have my Frigate card point to the streams directly from the camera to avoid Go2RTC processing altogether?

Thanks for pointing me in the right direction.

**Reply by NickM-27** [reply]
yes, this is restreaming

```
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_slider  # With Go2RTC
          #path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0901
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_slider_sub  # With Go2RTC
        #- path: rtsp://admin:Password@LAN.IP.SUB.250:8741/Streaming/channels/0902
          roles:
            - detect
```

**Comment by EPiSKiNG** [comment]
I reformatted the config to eliminate the Go2RTC restreaming and interestingly enough, I'm actually consuming about 2-3 watts more power!  Perhaps the continuous recording is essentially performing the same amount of processing as restreaming?

**Reply by NickM-27** [reply]
No, recording is very lightweight

**Reply by NickM-27** [reply]
you probably have some other issues in your config

**Reply by EPiSKiNG** [reply]
Any guidance about how to pinpoint those issues?

**Reply by NickM-27** [reply]
well we can see the new config, that would likely show the issue. The system and camera metrics page will also show what is using cpu usage in this case

**Reply by EPiSKiNG** [reply]
Here's the config:

```
version: 0.14

mqtt:
  host: net.sub.net.220 # <---- same mqtt broker that home assistant uses
  user: user
  password: password

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat
    - car
    - bicycle

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  front_door:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.205:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.205:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: front_door
    zones:
      zone_front_yard:
        coordinates: 0.197,1,0.806,1,0.661,0.833,0.767,0,0.338,0
        inertia: 3
        loitering_time: 0

  front_walkway:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
      mask: 0,0.397,0.596,0.725,0.755,1,1,1,1,0,0,0,0,0.194
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.202:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.202:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: front_walkway
    zones:
      zone_front_yard:
        coordinates: 0,1,0.741,1,0.694,0.894,0.616,0.739,0.465,0.667,0,0.43,0,0.678
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.429,0,0,1,0,1,0,1,1,0.807,1,0.741,1,0.627,0.748

  side_yard:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.214:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.214:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: side_yard
    zones:
      zone_side_yard:
        coordinates: 0,1,1,1,1,0,0.502,0,0.334,0,0.291,0.594
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.781,0.382,0.423,0.341,0,0,0

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.209:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.209:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: driveway
    zones:
      zone_driveway:
        coordinates: 0,1,1,1,1,0.589,0.52,0.189,0.389,0.111,0,0.253
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.353,0.452,0.133,1,0.536,1,0.4,1,0,0,0

  bedroom_slider:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.208:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.208:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: bedroom_slider
    zones:
      zone_patio:
        coordinates: 0.194,1,1,1,1,0.291,0.397,0.105
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,1,0,0,0.372,0,0.531,0,0.5,0.232,0.363,0.258,0.334,1

  living_room_slider:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.211:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.211:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: living_room_slider
    zones:
      zone_patio:
        coordinates: 0,0,0.517,0,0.516,0.242,0,0.245
        inertia: 3
        loitering_time: 0
      zone_living_patio:
        coordinates: 0,1,0.607,1,0.702,0.236,0,0.195
        inertia: 3
        loitering_time: 0

  pergola:
    objects:
      track:
        - person
        - dog
        - cat
      mask: 0.576,0.332,0.794,0.413,1,0.476,1,0.066,0.458,0.066,0.449,0.233
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.201:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.201:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: pergola
    zones:
      zone_pergola:
        coordinates: 
          0,0.731,0,1,0.348,1,0.419,0.492,0.522,1,1,1,0.898,0.55,0.87,0.5,0.9,0.323,0.927,0.533,0.898,0.551,1,1,1,0.096,0.745,0.12,0.6,0.241,0.218,0.276,0,0.388
        inertia: 3
        loitering_time: 0

  closet:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.216:554/stream1
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.216:554/stream2
          roles:
            - detect
    live:
      stream_name: closet
    zones:
      zone_closet:
        coordinates: 0.214,0.097,0.229,0.964,0.595,0.969,0.59,0
        loitering_time: 0
        inertia: 6

  northwest_lawn:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.203:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.203:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: northwest_lawn
    zones:
      zone_backyard:
        coordinates: 0,1,0.62,1,0.209,0.298,0.665,0.165,0.686,0,0.334,0,0,0,0,0.533
        inertia: 3
        loitering_time: 0

  backyard:
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@net.sub.net.212:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://admin:password@net.sub.net.212:554/Streaming/channels/102
          roles:
            - detect
    live:
      stream_name: backyard
    zones:
      zone_backyard:
        coordinates: 0,0.614,0.68,0.412,0.701,0,0.502,0,0.334,0,0,0
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,1,1,1,1,0.319,1,0,0.707,0,0.674,0.429,0,0.613

```

System Metrics:

![image](https://github.com/user-attachments/assets/da37f252-0f02-4170-b733-207b6d9b74b3)


Cameras:

![image](https://github.com/user-attachments/assets/e2a3a34d-85e9-4eff-ad71-a9905a98c772)

Thanks again for the assistance!!! I very much appreciate it!
