### DISCUSSION TITLE
How to use Frigate+ onnx with NVIDIA RTX 4060

### DISCUSSION THREAD

**Discussion by philippedegeer** [blakeblackshear/frigate#14428] [Ask A Question] [answered]
Goodmorning,

I have a fully functional Frigate setup with an NVIDIA RTX 4060 card and can run all the yolo models that are mentioned in the Frigate documentation.

Can someone guide me on how to use my Frigate+ onnx with tensorrt and the NVIDIA card ? Unless I am mistaken, there is no mention of this part in the doc. I have done the same as for other Frigate+ detector setups :

```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
#  path: /config/model_cache/tensorrt/yolov7x-320.trt 
  path: plus://xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 320
#  height: 320
#  labelmap_path: /models/coco_80cl.txt
```

but I get the message ...

"Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)". This tells me there is something wrong with versioning.

I am using the Frigate+ onnx right for this case ?

Thanks - Philippe
