### DISCUSSION TITLE
[Bug]: OS Refreshed and reusing a backup frigate folders+config resulting in missing pictures/recordings

### DISCUSSION THREAD

**Discussion by marc4s** [blakeblackshear/frigate#14426] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I had an issue with the base OS on the hardware frigate was running on.
So I created a backup and reinstalled the OS, copied back frigate to /root/frigate (like it was before) connected the external USB HDD and mounted it back to the old path /data1TB where all the frigatre recordings belong to /data1TB/frigatestorage/

- it seems it cannot access the old snapshot photos AND is not creating new ones
so all files/folders stopped by 2024-10-05
- then I completly deleted them all in friagte and local on the disk
- I tried it with chmod -R 777 for those paths without success

### Steps to reproduce

1. stop frigate and backup the docker-compose related folder and the storage folder
2. install new ubuntu-server 24.04, apt install docker
3. copy back all data and start frigate
...

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Firefox

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: true
  # Required: host name
  host: xxxxx
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: HIDDENUSER
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: STRONGPASSWORD
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  #stats_interval: 60
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    hauseingang_reo:
      - ffmpeg:https://192.168.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=HIDDENUSER&password=STRONGPASSWORD#video=copy#audio=copy#audio=opus
    hauseingang_reo_sub:
      - ffmpeg:https://192.168.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=HIDDENUSER&password=STRONGPASSWORD
    garage_reo:
      - ffmpeg:https://192.168.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=HIDDENUSER&password=STRONGPASSWORD#video=copy#audio=copy#audio=opus
    garage_reo_sub:
      - ffmpeg:https://192.168.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=HIDDENUSER&password=STRONGPASSWORD
# terasse deaktiviert. unnötig. hohe CPU Last
#    terasse: "ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.158.xx/live/ch0#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.
#    garagetor: "ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/live/ch0#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.
#    carport: "ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/live/ch0#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.
#    haus: "ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/live/ch0#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.
#    carport: ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/live/ch0#video=h264#hardware   # <- use hardware acceleration to create an h264 stream usable for other components.
    hausflur: ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/video.h264 #video=h264#   # <- use hardware acceleration to create an h264 stream usable for other components.
    garagetor: ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/live/ch1#video=h264#hardware   # <- use hardware acceleration to create an h264 stream usable for other components.
#    untermcarport: ffmpeg:rtsp://HIDDENUSER:STRONGPASSWORD@192.168.xx/live/ch1#video=h264#hardware   # <- use hardware acceleration to create an h264 stream usable for other components.

model:
  path: plus://44c31ab79a325b34f0d161202b1e77e4

cameras:
  # terasse deaktiviert. unnötig. hohe CPU Last
  #terasse:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/terasse
  #        input_args: preset-rtsp-restream
  #        roles:
  #          - detect
  #          - record
  #  detect:
  #    width: 1280
  #    height: 720
  #    fps: 7
  #  motion:
  #    mask:    
  #      - 424,0,458,720,0,720,0,0
  #  zones:
  #    zone_0:
  #      coordinates: 1172,0,446,0,424,720,1050,720
  garagetor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagetor
          roles:
            - detect
            - record
    motion:
      mask:
        - 563,0,0,0,0,128
    zones:
      UnterDemCarport:
        coordinates: 0.731,0.662,0.921,0.712,0.963,0.448,0.759,0.377
        inertia: 3
        objects: person
      AmHoftor:
        coordinates: 0.257,0.266,0.422,0.288,0.437,0.551,0.126,0.467
        objects: person
      VorDerGarage:
        coordinates: 0.007,0.987,0.128,0.473,0.974,0.732,0.991,0.989
        objects: person
      AmBaumhaus:
        coordinates: 0.581,0.604,0.618,0.227,0.737,0.265,0.727,0.648
        objects: person
  #carport:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/carport
  #        roles:
  #          - detect
  #          - record
  #untermcarport:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/untermcarport
  #        roles:
  #          - detect
  #          - record
#  haus:
#    ffmpeg:
#      inputs:
#        - path: rtsp://127.0.0.1:8554/haus
#          roles:
#            - detect
#            - record
    objects:
      mask: 
        0.003,0.43,0.25,0.329,0.26,0.262,0.317,0.246,0.386,0.274,0.434,0.295,0.438,0.204,0,0.077
  hausflur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hausflur
          roles:
            - detect
            - record
    objects:
      mask:
        - 0.748,0.078,0.863,0.185,0.893,0.959,0.773,0.868,0.745,0.08
        - 0.457,0.781,0.363,0.35,0.216,0.41,0.292,0.87,0.465,0.828
    zones:
      Haustür:
        coordinates: 0.36,0.003,0.664,0.009,0.741,0.676,0.776,0.975,0.498,0.983,0.316,0.01
        loitering_time: 0
      Flurfenster:
        coordinates: 0.117,0.004,0.003,0.004,0,0.423,0.181,0.376
        loitering_time: 0
  #esp32terassehausflur:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://192.168.158.83:554/mjpeg/1
  #        roles:
  #          - detect
  #          - record
  #  detect:
  #    width: 800
  #    height: 600
  #    fps: 5
  #  record: 
  #    enabled: True    
  hauseingang:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hauseingang_reo?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hauseingang_reo_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.355,0,0.354,0.094,0.251,0.086,0.192,0
    objects:
      mask:
        - 0.253,0.099,0.279,0.798,0.173,0.771,0.173,0.895,0.334,0.963,0.393,0.804,0.486,0.808,0.587,0.698,0.613,0.474,0.543,0.393,0.546,0.062
        - 0.834,0.821,0.903,0.856,0.934,0.625,0.842,0.625
        - 0.837,0.856,0.829,0.982,0.926,0.982,0.939,0.846
    zones:
      VorderHaustür:
        coordinates: 0.993,0.103,0.928,0.567,0.591,0.431,0.608,0.063
        loitering_time: 0
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_reo?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_reo_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask: 0.145,0.143,0.184,0.009,0.946,0.016,0.953,0.148,0.131,0.174
    zones:
      AmHoftor:
        coordinates: 0.986,0.155,0.819,0.156,0.856,0.447,0.982,0.332
        objects: person
      VorDerGarage:
        coordinates: 0.008,0.259,0.007,0.654,0.871,0.552,0.812,0.154,0.143,0.178
        objects: person
      AufDemHof:
        coordinates: 
          0.254,0.63,0.387,0.993,0.998,0.999,0.998,0.539,0.996,0.528,0.997,0.325,0.861,0.449,0.878,0.552
        objects: person
detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  max_disappeared: 500


objects:
  track:
    - person
    - face
    - package
    - amazon
snapshots:
  enabled: true
  retain:
    default: 30

record:
  enabled: true
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 100
      #mode: motion
      mode: active_objects
      objects:
        dog: 14
        car: 30
        person: 365

# Include all cameras by default in Birdseye view
# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous



# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
#  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Europe/Berlin
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
#  use_experimental: false
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: full
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: '%Y/%m/%d %H:%M'

# Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
root@zmrechnermobile:~# cat /root/frigate/docker-compose.yml 
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
#    image: ghcr.io/blakeblackshear/frigate:stable
#    image: ghcr.io/blakeblackshear/frigate:0.13.2
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "400mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /root/frigate/config.yml:/config/config.yml
      - /root/frigate/:/config/
      - /data1TB/frigatestorage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PLUS_API_KEY: "HIDDEN"
      FRIGATE_RTSP_PASSWORD: "HIDDEN"
```

### Relevant Frigate log output

```shell
absolutly no info/errors related to any storage/paths
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Wansview, reolink

### Screenshots of the Frigate UI's System metrics pages

![Bildschirmfoto vom 2024-10-18 09-33-06](https://github.com/user-attachments/assets/7301abc6-4881-44ac-9ed8-599b7c839782)
![Bildschirmfoto vom 2024-10-18 09-45-52](https://github.com/user-attachments/assets/1beb3602-dd5f-475a-ae94-e7c251d2c8f8)

### Any other information that may be helpful

![Bildschirmfoto vom 2024-10-18 09-33-25](https://github.com/user-attachments/assets/04de0293-6836-4c66-b43c-f773ccf6e658)
