### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by lakime** [blakeblackshear/frigate#14430] [Config Support]
### Describe the problem you are having

I would like to split view from my camera into two cameras, as I got some Chinese cam, which is giving view from 2 lens in one rtsp stream

Describe the solution you'd like
I can try to crop it via ffmpeg, or try to play with some input ffmpeg parameters, but whenever I do that, frigate fails

whenever I do add some customer input_args - camera is failing to start

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.xx  # IP address of your MQTT broker
  port: 1883            # Port of your MQTT broker (default is 1883)
  user: xxx
  password: xxx # (Optional) Password for the MQTT broker
  topic_prefix: frigate  # Prefix for MQTT topics (optional, default is 'frigate')

detect:
  width: 1280
  height: 720
    #  min_area: 500
  fps: 5  # Lower FPS for detection to save resources

motion:
  threshold: 40
  contour_area: 20
# Global record settings
record:
  enabled: true
  retain:
    days: 5  
    mode: motion
  events:
    retain:
      default: 
      mode: motion
cameras:
  przod_prawo:
    enabled: true
    ffmpeg:
      hwaccel_args:
        - -c:v:1
        - hevc_vaapi
      inputs:
        - path: rtsp://xxx:xxx@192.168.0.xx:554/rtsp 
          roles:
            - detect
            - motion
  tyl_prawo:
    enabled: true
    ffmpeg:
      hwaccel_args:
        - -c:v:1
        - hevc_vaapi
      inputs:
        - path: rtsp://xxx:xxx@192.168.0.227:554/rtsp 
          roles:
            - detect
            - motion
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: '3.8'

services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT port
    volumes:
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/log:/mosquitto/log
    environment:
      - MQTT_USER=xxx # Set your MQTT username
      - MQTT_PASSWORD=xxx # Set your MQTT password
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2GB" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/:/dev/dri/ # For intel hwaccel, needs to be updated for your hardware
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - LIBVA_DRIVER_NAME=i965  # Set to force the use of the i965 driver
      - VAAPI_DRIVER=i965  # Optional but can reinforce the driver choice
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/:/config
      - /opt/frigate/media/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "5000:5000/tcp" # 
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped  # Automatically restarts the container
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /opt/homeassistant/config:/config  # Path to your config
    ports:
      - "8123:8123"  # Expose Home Assistant GUI
      - "8124:8124"  # Additional port if needed
```

### Object Detector

Coral
