### DISCUSSION TITLE
[Support]: Audio in live and recorded files but no audio in review tab or exported file

### DISCUSSION THREAD

**Discussion by cleme29** [blakeblackshear/frigate#14447] [General Support]
### Describe the problem you are having

Hi,

I just finished setting up my Frigate instance with 3 Tp link Tapo C210 cameras.
I have issues getting the audio playback working in review tab in browser or in exported file in VLC.
The video works fine in either case, just no audio.

The audio and video works fine in the live view and on the local files recorded on my hard drive. 
Could you help me getting through this issue, please ?
Ask me if you need more details.

Thanks in advance !

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Brave Version 1.71.114 Chromium: 130.0.6723.58 | Microsoft Edge Version 130.0.2849.46 | Firefox 131.0.3

### Frigate config file

```yaml
cameras:
  sejour: # Name
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://{FRIGATE_RTSP_SEJOUR_USER}:{FRIGATE_RTSP_SEJOUR_PASSWORD}@{FRIGATE_RTSP_SEJOUR_IP}:554/stream2 # Low res
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/sejour?video&audio # High res
          roles:
            - record
          input_args: preset-rtsp-restream
    onvif:
      host: *.*.*.*
      port: 2020
      user: "{FRIGATE_RTSP_SEJOUR_USER}"
      password: "{FRIGATE_RTSP_SEJOUR_PASSWORD}"

  chambre: # Name
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://{FRIGATE_RTSP_CHAMBRE_USER}:{FRIGATE_RTSP_CHAMBRE_PASSWORD}@{FRIGATE_RTSP_CHAMBRE_IP}:554/stream2
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/chambre?video&audio
          roles:
            - record
          input_args: preset-rtsp-restream
    onvif:
      host: *.*.*.*
      port: 2020
      user: "{FRIGATE_RTSP_CHAMBRE_USER}"
      password: "{FRIGATE_RTSP_CHAMBRE_PASSWORD}"

  bureau: # Name
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://{FRIGATE_RTSP_BUREAU_USER}:{FRIGATE_RTSP_BUREAU_PASSWORD}@{FRIGATE_RTSP_BUREAU_IP}:554/stream2
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/bureau?video&audio
          roles:
            - record
          input_args: preset-rtsp-restream
    onvif:
      host: *.*.*.*
      port: 2020
      user: "{FRIGATE_RTSP_BUREAU_USER}"
      password: "{FRIGATE_RTSP_BUREAU_PASSWORD}"

go2rtc:
  streams:
    sejour:
      # - rtsp://{FRIGATE_RTSP_SEJOUR_USER}:{FRIGATE_RTSP_SEJOUR_PASSWORD}@{FRIGATE_RTSP_SEJOUR_IP}:554/stream1
      # - "ffmpeg:sejour#audio=opus"
      - tapo://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PASSWORD}@{FRIGATE_RTSP_SEJOUR_IP}
      # - "ffmpeg:sejour#audio=aac"
    # sejour_sub:
    #   - rtsp://{FRIGATE_RTSP_SEJOUR_USER}:{FRIGATE_RTSP_SEJOUR_PASSWORD}@{FRIGATE_RTSP_SEJOUR_IP}:554/stream2
      # - "ffmpeg:sejour_sub#audio=opus"
    chambre:
      # - rtsp://{FRIGATE_RTSP_CHAMBRE_USER}:{FRIGATE_RTSP_CHAMBRE_PASSWORD}@{FRIGATE_RTSP_CHAMBRE_IP}:554/stream1
      # - "ffmpeg:chambre#audio=opus"
      - tapo://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PASSWORD}@{FRIGATE_RTSP_CHAMBRE_IP}
      # - "ffmpeg:chambre#audio=aac"
    # chambre_sub:
    #   - rtsp://{FRIGATE_RTSP_CHAMBRE_USER}:{FRIGATE_RTSP_CHAMBRE_PASSWORD}@{FRIGATE_RTSP_CHAMBRE_IP}:554/stream2
      # - "ffmpeg:chambre_sub#audio=opus"
    bureau:
      # - rtsp://{FRIGATE_RTSP_BUREAU_USER}:{FRIGATE_RTSP_BUREAU_PASSWORD}@{FRIGATE_RTSP_BUREAU_IP}:554/stream1
      # - "ffmpeg:bureau#audio=opus"
      - tapo://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PASSWORD}@{FRIGATE_RTSP_BUREAU_IP}
      # - "ffmpeg:bureau#audio=aac"
    # bureau_sub:
    #   - rtsp://{FRIGATE_RTSP_BUREAU_USER}:{FRIGATE_RTSP_BUREAU_PASSWORD}@{FRIGATE_RTSP_BUREAU_IP}:554/stream2
      # - "ffmpeg:bureau_sub#audio=opus"

ffmpeg:
  hwaccel_args: preset-vaapi
    # record: preset-record-generic-audio-copy

motion: # timestamp
  mask: 0,0.053,0.358,0.053,0.358,0,0,0

audio:
  enabled: true

detect:
  enabled: true
  width: 640 # res stream 2
  height: 360

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

mqtt:
  enabled: false

version: 0.14
```

### Relevant Frigate log output

```shell
2024-10-19 14:44:39.077556336  [INFO] Preparing Frigate...
2024-10-19 14:44:39.082955857  [INFO] Starting Frigate...
2024-10-19 14:44:39.866787395  [2024-10-19 14:44:39] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-19 14:44:39.866813043  [2024-10-19 14:44:39] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-19 14:44:39.878124022  [2024-10-19 14:44:39] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-19 14:44:39.899193886  [2024-10-19 14:44:39] peewee_migrate.logs            INFO    : Starting migrations
2024-10-19 14:44:39.899511279  [2024-10-19 14:44:39] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-19 14:44:40.184223308  [2024-10-19 14:44:40] frigate.app                    INFO    : Recording process started: 350
2024-10-19 14:44:40.184303992  [2024-10-19 14:44:40] frigate.app                    INFO    : Recording process started: 351
2024-10-19 14:44:40.185313222  [2024-10-19 14:44:40] frigate.app                    INFO    : go2rtc process pid: 98
2024-10-19 14:44:40.201249355  [2024-10-19 14:44:40] detector.ov                    INFO    : Starting detection process: 378
2024-10-19 14:44:40.203953077  [2024-10-19 14:44:40] frigate.app                    INFO    : Output process started: 380
2024-10-19 14:44:40.212150295  [2024-10-19 14:44:40] frigate.app                    INFO    : Camera processor started for sejour: 395
2024-10-19 14:44:40.215809324  [2024-10-19 14:44:40] frigate.app                    INFO    : Camera processor started for chambre: 396
2024-10-19 14:44:40.219445902  [2024-10-19 14:44:40] frigate.app                    INFO    : Camera processor started for bureau: 402
2024-10-19 14:44:40.223198777  [2024-10-19 14:44:40] frigate.app                    INFO    : Capture process started for sejour: 410
2024-10-19 14:44:40.226555903  [2024-10-19 14:44:40] frigate.app                    INFO    : Capture process started for chambre: 415
2024-10-19 14:44:40.229783138  [2024-10-19 14:44:40] frigate.app                    INFO    : Capture process started for bureau: 418
2024-10-19 14:44:40.233151811  [2024-10-19 14:44:40] frigate.app                    INFO    : Audio process started: 424
2024-10-19 14:44:50.145038329  [2024-10-19 14:44:50] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
2024-10-19 15:20:47.133169  2024-10-19 14:44:50.145042097
2024-10-19 14:57:26.298375922  [2024-10-19 14:57:26] frigate.comms.dispatcher       INFO    : Setting motion threshold for bureau: 30
2024-10-19 14:57:26.298988778  [2024-10-19 14:57:26] frigate.comms.dispatcher       INFO    : Setting motion contour area for bureau: 10
2024-10-19 14:57:30.521994302  [2024-10-19 14:57:30] frigate.comms.dispatcher       INFO    : Setting motion threshold for bureau: 30
2024-10-19 14:57:30.522591002  [2024-10-19 14:57:30] frigate.comms.dispatcher       INFO    : Setting motion contour area for bureau: 10
2024-10-19 14:57:32.183139465  [2024-10-19 14:57:32] frigate.comms.dispatcher       INFO    : Setting motion threshold for chambre: 30
2024-10-19 14:57:32.183566656  [2024-10-19 14:57:32] frigate.comms.dispatcher       INFO    : Setting motion contour area for chambre: 10
2024-10-19 14:57:34.058520672  [2024-10-19 14:57:34] frigate.comms.dispatcher       INFO    : Setting motion threshold for sejour: 30
2024-10-19 14:57:34.058837846  [2024-10-19 14:57:34] frigate.comms.dispatcher       INFO    : Setting motion contour area for sejour: 10
2024-10-19 14:57:37.315148929  [2024-10-19 14:57:37] frigate.comms.dispatcher       INFO    : Setting motion threshold for bureau: 30
2024-10-19 14:57:37.315427460  [2024-10-19 14:57:37] frigate.comms.dispatcher       INFO    : Setting motion contour area for bureau: 10
```

### Relevant go2rtc log output

```shell
2024-10-19 14:44:39.077565822  [INFO] Preparing new go2rtc config...
2024-10-19 14:44:39.305811497  [INFO] Starting go2rtc...
2024-10-19 14:44:39.389451791  14:44:39.388 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-10-19 14:44:39.389455687  14:44:39.388 INF config path=/dev/shm/go2rtc.yaml
2024-10-19 14:44:39.389457409  14:44:39.388 INF [rtsp] listen addr=:8554
2024-10-19 14:44:39.389459068  14:44:39.388 INF [webrtc] listen addr=:8555/tcp
2024-10-19 14:44:39.389460382  14:44:39.389 INF [api] listen addr=:1984
2024-10-19 14:44:49.077349645  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
root@7e55d9235d9f:/opt/frigate# ffprobe rtsp://***:***@*.*.*.*/stream1
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://***:***@*.*.*.*/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2304x1296, 15 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
{"cameras":{"bureau":{"audio_dBFS":-60.7938,"audio_rms":29.906,"camera_fps":5.1,"capture_pid":418,"detection_enabled":true,"detection_fps":5.1,"ffmpeg_pid":440,"pid":402,"process_fps":5.1,"skipped_fps":0.0},"chambre":{"audio_dBFS":-65.3792,"audio_rms":17.6397,"camera_fps":5.0,"capture_pid":415,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":427,"pid":396,"process_fps":5.0,"skipped_fps":0.0},"sejour":{"audio_dBFS":-56.9837,"audio_rms":46.373,"camera_fps":5.0,"capture_pid":410,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":419,"pid":395,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"1.4","cpu_average":"1","mem":"0.9"},"10734":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"11444":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"11476":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"128":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"157":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"159":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"295":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"348":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"350":{"cmdline":"frigate.recording_manager","cpu":"0.5","cpu_average":"0","mem":"0.5"},"351":{"cmdline":"frigate.review_segment_manager","cpu":"0.2","cpu_average":"0","mem":"0.4"},"377":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(58)","cpu":"0.1","cpu_average":"0","mem":"0.0"},"378":{"cmdline":"frigate.detector.ov  ","cpu":"4.2","cpu_average":"3","mem":"1.0"},"380":{"cmdline":"frigate.output       ","cpu":"0.9","cpu_average":"0","mem":"0.5"},"395":{"cmdline":"frigate.process:sejour","cpu":"0.7","cpu_average":"0","mem":"0.5"},"396":{"cmdline":"frigate.process:chambre","cpu":"0.7","cpu_average":"0","mem":"0.5"},"402":{"cmdline":"frigate.process:bureau","cpu":"2.8","cpu_average":"2","mem":"0.5"},"410":{"cmdline":"frigate.capture:sejour","cpu":"0.3","cpu_average":"0","mem":"0.4"},"415":{"cmdline":"frigate.capture:chambre","cpu":"0.3","cpu_average":"0","mem":"0.4"},"418":{"cmdline":"frigate.capture:bureau","cpu":"0.3","cpu_average":"0","mem":"0.4"},"419":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@*.*.*.*:554/stream2 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.7","cpu_average":"0","mem":"0.1"},"424":{"cmdline":"frigate.audio_manager","cpu":"0.2","cpu_average":"0","mem":"0.5"},"427":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@*.*.*.*:554/stream2 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.7","cpu_average":"0","mem":"0.1"},"440":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@*.*.*.*:554/stream2 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.1"},"449":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/chambre?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/chambre@%Y%m%d%H%M%S%z.mp4","cpu":"1.0","cpu_average":"0","mem":"0.0"},"45":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"450":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/sejour?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/sejour@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.0"},"451":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@*.*.*.*:554/stream2 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.2","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"462":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@*.*.*.*:554/stream2 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.3","cpu_average":"0","mem":"0.0"},"463":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/bureau?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/bureau@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.0"},"472":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@*.*.*.*:554/stream2 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.2","cpu_average":"0","mem":"0.0"},"486":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"495":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"500":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"514":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"800":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(50)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"1.4","cpu_average":"1","mem":"0.1"},"frigate.full_system":{"cpu":"3.8","mem":"75.5"}},"detection_fps":5.1,"detectors":{"ov":{"detection_start":0.0,"inference_speed":8.9,"pid":378}},"gpu_usages":{"error-gpu":{"gpu":"","mem":""}},"processes":{"audio_detector":{"pid":424},"go2rtc":{"pid":98},"logger":{"pid":348},"recording":{"pid":350},"review_segment":{"pid":351}},"service":{"last_updated":1729351491,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":59.2,"mount_type":"tmpfs","total":64.0,"used":4.8},"/media/frigate/clips":{"free":175121.4,"mount_type":"ext4","total":201014.7,"used":16640.9},"/media/frigate/recordings":{"free":175121.4,"mount_type":"ext4","total":201014.7,"used":16640.9},"/tmp/cache":{"free":1894.3,"mount_type":"tmpfs","total":1907.4,"used":13.0}},"temperatures":{},"uptime":2411,"version":"0.14.1-f4f3cfa"}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    env_file: .env
    volumes:
      - ./config:/config
      - /mnt/frigate_data:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
    devices:
      - /dev/dri/renderD128
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

TP LINK Tapo C210

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/24e3cc40-a567-4213-88b5-a0b2418d18e0)
![image](https://github.com/user-attachments/assets/e2fe6528-dd66-4ab5-bc9b-183d2dccc4ed)
![image](https://github.com/user-attachments/assets/fcd88637-7822-4630-af48-267531f73e90)

### Any other information that may be helpful

A mediainfo of a recorded file on my drive :

`me@machine:/mnt/frigate_data/recordings/2024-10-19/14/bureau$ mediainfo 50.40.mp4 
General
Complete name                            : 50.40.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 417 KiB
Duration                                 : 10 s 17 ms
Overall bit rate                         : 341 kb/s
Frame rate                               : 14.976 FPS
Movie name                               : go2rtc/1.9.2
Writing application                      : Lavf59.27.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L5
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Format settings, GOP                     : M=1, N=15
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 10 s 17 ms
Bit rate                                 : 310 kb/s
Width                                    : 2 304 pixels
Height                                   : 1 296 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 14.976 FPS
Minimum frame rate                       : 9.298 FPS
Maximum frame rate                       : 23.704 FPS
Original frame rate                      : 15.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.007
Stream size                              : 380 KiB (91%)
Codec configuration box                  : avcC

**Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 9 s 976 ms
Source duration                          : 9 s 956 ms
Bit rate mode                            : Constant
Bit rate                                 : 26.3 kb/s
Channel(s)                               : 1 channel
Channel layout                           : M
Sampling rate                            : 8 000 Hz
Frame rate                               : 7.812 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 31.9 KiB (8%)
Source stream size                       : 31.9 KiB (8%)
Default                                  : Yes
Alternate group                          : 1**`
