### DISCUSSION TITLE
[Support]: Frigate out of space

### DISCUSSION THREAD

**Discussion by gcormier** [blakeblackshear/frigate#14442] [General Support]
### Describe the problem you are having

Do I have something configured wrong? 

```
s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
```

Running in docker. Should frigate be logging elsewhere then shared memory?

### Version

14.1

### Relevant Frigate log output

```shell
s6-log: warning: unable to write to /dev/shm/logs/nginx/current: No space left on device
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    #privileged: true  # privileged allows GPU stats to run via intel_gpu_top
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    cap_add:
      - CAP_PERFMON
    shm_size: "512mb" # update for your cameras based on calculation above
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - PLUS_API_KEY=exxxxxxx
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      #- /dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate:/config
      - /drives/6t/frigate:/media/frigate
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink
