### DISCUSSION TITLE
[Support]: bounding box for detected objects in 0.14

### DISCUSSION THREAD

**Discussion by capnjip** [blakeblackshear/frigate#14444] [General Support] [answered]
### Describe the problem you are having

In older versions of frigate, when an object (eg. person) was detected, the software created an image with a yellow bounding box and area of said box. This information was useful in adjusting the Object filters parameters to reduce false positives. Now in 0.14, I cannot seem to find this image with bounding box. I am trying to reduce false positives due to shadows, but don't even know what frigate is flagging as the person in the saved event. What tools do people utilize in this newer version to better resolve false positives?

### Version

0.14

### What browser(s) are you using?

firefox

### Frigate config file

```yaml
## v1.0 used on unRAID server. 05Mar2023
## First install, 13Jan2022. Following https://docs.frigate.video/guides/getting_started "creating a config file"
## Upgrade to Frigate 0.12 27May2023
## Upgrade to Frigate 0.14 beta4 23Jul2024
auth:
  enabled: true
  reset_admin_password: false

tls:
  enabled: false

mqtt:
  host: 192.168.X.XX
  port: 1883
  user: mqtt
  password: {password}

detectors:
  coral:
    type: edgetpu
    device: pci:0

birdseye:
  enabled: true

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-nvidia-h264

objects:
  track:
    - person
    - dog
    - cat
#    - car
#added as attempt to reduce false positives ID'ing Cars as People
  filters:
    person:
      # decimal of percentage certainty of object. Higher requires more positive certainty of object, lower more false positives.
      threshold: 0.58
      min_area: 8000
#      min_ratio: 0.2
      max_ratio: 0.88
      # minimum score to initiate tracking, same params as Threshold.
      min_score: 0.4
    cat:
      threshold: 0.58
    dog:
      threshold: 0.58

#enabling audio caused a no-boot situation?
audio:
  enabled: False

motion:
#scale: 1-255, higher = less sensitive
  threshold: 40
#Rule of thumb: 15 high, 30 med, 50 low sensitivity
  contour_area: 35
#alpha values: high values mean single frame makes for motion, too low won't show motion at all
  delta_alpha: 0.18
  frame_alpha: 0.18

record:
  enabled: true
  retain:
    days: 20
    mode: all
  events:
    retain:
      default: 20
      mode: all

snapshots:
  enabled: true
  retain:
    default: 20

go2rtc:
  streams:
    sidedoor:
      - rtsp://eyeball:eyeseaewe2@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0
    driveway:
      - rtsp://eyeball:eyeseaewe2@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0
    acunit:
      - rtsp://eyeball:eyeseaewe2@192.168.x.x/h265Preview_01_main
    frontyard:
      - rtsp://eyeball:eyeseaewe2@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0
    backdoor:
      - rtsp://eyeball:eyeseaewe2@192.168.x.x/h265Preview_01_main
    frontdoor:
      - rtsp://eyeball:eyeseaewe2@192.168.x.x/h265Preview_01_main
    garagedoor:
      - rtsp://eyeball:eyeseaewe2@192.168.32.10/h265Preview_01_main
  webrtc:
    candidate:
      - 192.168.x.x:8555

cameras:
  frontdoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
        - 1310,0,2560,0,2560,318,1302,21,0,252,0,0
    objects:
      filters:
        dog: {}
        person:
          mask: 1,0.53,0.787,0.784,0.761,1,1,1
  sidedoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/sidedoor
          roles:
            - detect
    detect:
      enabled: true
      width: 2688
      height: 1520
    motion:
      mask:
        - 0,672,752,584,2641,578,2581,369,1912,276,1711,293,942,340,0,383
    objects:
      filters:
        car:
          mask:
            - 0,672,752,584,2641,578,2581,369,1912,276,1711,293,942,340,0,383

  driveway:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
    detect:
      enabled: true
      width: 2688
      height: 1520
    motion:
      mask:
        - 2688,0,2688,732,2222,491,1857,358,1160,271,409,251,338,0
    objects:
      filters:
        car:
          mask:
            - 2688,0,2688,732
        person:
          mask:
            - 0.824,0.32,0.664,0.222,0.557,0.191,0.553,0,1,0,1,0.472
            - 0,0.66,0.179,0.676,0.183,0.537,0,0.516
  backdoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/backdoor
          roles:
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
        - 2560,0,2560,926,1810,675,1850,433,1546,319,1003,227,0,212,0,0
        - 0,1440,1072,1440,732,1002,0,1078
    objects:
      filters:
        car:
          mask:
            - 0,1440,2560,1440,2560,0,0,0

  acunit:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/acunit
          roles:
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
        - 2535,630,2560,0,0,0,0,967,626,692,923,89,2017,69,2098,597
    objects:
      filters:
        car:
          mask:
            - 2560,0,2560,1440,0,1440,0,0

  garagedoor:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/garagedoor
          roles:
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask:
        - 2335,0,2340,422,2125,428,2129,166,1482,222,1121,373,487,537,0,709,0,0
    objects:
      filters:
        car:
          mask: 0,0,0.455,0,0.607,0,0.608,0.159,0.37,0.259,0.257,0.325,0,0.489
        person:
          mask:
            - 2231,488,2369,486,2365,323,2226,322

  frontyard:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          roles:
            - detect
    detect:
      enabled: true
      width: 2304
      height: 1296
    motion:
      mask: 0,0.434,0.254,0.239,0.475,0.135,0.689,0.112,0.69,0.006,0,0
    objects:
      filters:
        car:
          mask: 0,0.434,0.246,0.242,0.47,0.133,0.82,0.115,0.821,0,0,0
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
UnRaid commnuity applications template of CLI
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

amcrest and reolinks

### Screenshots of the Frigate UI's System metrics pages

N/A

### Any other information that may be helpful

General inquiry
