### DISCUSSION TITLE
[Support]: Export 2 cameras' recordings of a specific hour

### DISCUSSION THREAD

**Discussion by jiiins** [blakeblackshear/frigate#14443] [General Support] [answered]
### Describe the problem you are having

The police is asking for two of my cameras' feeds for a specific hour of a day. I can see the right hour's feeds in the Frigate UI, but I can't find the entire video in the storage. In the day/camera folder I can only see pieces named like 13.34.mp4 or 25.14.mp4, but they seem in random order, and I don't have a timestamp on the recordings.

So I'm asking:
1. How can I export (or copy via terminal) the entire hour, like it's seen in the Frigate UI?
2. As the recording is made of the clips triggered by motion, is there a way to recover the timestamp from them (like they are shown in the UI)?
3. Today is the 18th and the requested day is the 4th. Based on the config below, is it correct that all motion-triggered recordings should still be available?

Thanks a lot

### Version

13.2

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 21
    mode: motion
  events:
    pre_capture: 3
    post_capture: 3
    objects:
    - person
    - car
    - dog
    retain:
      mode: active_objects
      default: 14
      objects:
        person: 31
        car: 10
        dog: 7
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

n/a
