### DISCUSSION TITLE
[Config Support]: Can ffmpeg be skipped when idle for this stripped down config where detection and recording are disabled ?

### DISCUSSION THREAD

**Discussion by saket424** [blakeblackshear/frigate#14452] [Config Support]
### Describe the problem you are having

I have a niche use case where I want to use frigate with authentication as a frontend for go2rtc and I simply want to serve up live camera streams for hundreds of cameras but only on-demand from go2rtc without the need for any motion detection, object detection or recording. I don't expect ffmpeg to be running constantly in capture mode. Is there a way to disable ffmpeg for this specific use case?

I have an important use case for when we want to run frigate in the cloud and be frugal on the bandwidth pulled from the premise system where the cameras are housed

I want to emulate this behavior . This is from the author go2rtc. Exactly what I was hoping for on-demand streaming
https://github.com/AlexxIT/go2rtc/issues/134
AlexxIT commented on Dec 20, 2022 • 

go2rtc won't run exec/ffmpeg just after you add stream via API. Someone needs to request this stream from go2rtc via RTSP or MSE or WebRTC... And go2rtc will stop ffmpeg when client will stop viewing stream.

### Version

0.15.0-5d8bcb42

### Frigate config file

```yaml
mqtt:
  host: 172.17.0.1
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

objects:
  track:
    - person
    - car
    - bus
    - dog
    - bicycle
    - truck

tls:
  enabled: True

# Optional: Authentication configuration
auth:
  # Optional: Enable authentication
  enabled: True
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: False
  # Optional: Cookie to store the JWT token for native auth (default: shown below)
  #cookie_name: frigate_token
  # Optional: Set secure flag on cookie. (default: shown below)
  # NOTE: This should be set to True if you are using TLS
  cookie_secure: True
  # Optional: Session length in seconds (default: shown below)
  session_length: 86400 # 24 hours
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  #failed_login_rate_limit: None
  # Optional: Trusted proxies for determining IP address to rate limit
  # NOTE: This is only used for rate limiting login attempts and does not bypass
  # authentication. See the authentication docs for more details.
  trusted_proxies: []
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000

genai:
  enabled: false

semantic_search:
  enabled: false
  reindex: false

logger:
  default: info


detectors:
# coral:
#    type: edgetpu
#    device: pci:0
  cpu01:
    type: cpu

audio:
  # Optional: Enable audio events (default: shown below)
  enabled: False

motion:
  enabled: false
#  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
#  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
#  # The value should be between 1 and 255.
#  # default was 30
#  threshold: 100

ffmpeg:
  #hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream

birdseye:
  enabled: false
  restream: false

record:
  enabled: false
  retain:
    days: 1
    mode: motion
  alerts:
    retain:
      days: 1
      mode: active_objects
  detections:
    retain:
      days: 1
      mode: active_objects

detect:
  enabled: false
  width: 640
  height: 480
  fps: 5

#live:
#  height: 480

go2rtc:
  streams:
    hioutdoor1:
      - rtsp://admin:password@192.168.167.118:554/cam/realmonitor?channel=1&subtype=0
    looutdoor1:
      - rtsp://admin:password@192.168.167.118:554/cam/realmonitor?channel=1&subtype=1

  webrtc:
    candidates:
      - 172.17.0.1:8555
      - stun:8555


cameras:
  outdoor1:
    enabled: true
    detect:
      enabled: false
    record:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hioutdoor1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/looutdoor1
          roles:
            - detect

snapshots:
  enabled: false
  bounding_box: false
  quality: 100
  clean_copy: false
version: 0.15-0
```

### Relevant Frigate log output

```shell
docker-compose up
Creating network "frigate-stuff_default" with the default driver
Creating frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service certsync-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service certsync-log successfully started
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | 2024-10-19 18:55:20.362337677  [INFO] Preparing new go2rtc config...
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | 2024-10-19 18:55:20.372061846  [INFO] Preparing Frigate...
frigate    | 2024-10-19 18:55:20.377557049  [INFO] Starting NGINX...
frigate    | 2024-10-19 18:55:20.386781435  [INFO] Starting Frigate...
frigate    | 2024-10-19 18:55:21.063956937  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
frigate    | 2024-10-19 18:55:21.123342936  [INFO] Starting go2rtc...
frigate    | 2024-10-19 18:55:21.286095966  18:55:21.285 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate    | 2024-10-19 18:55:21.286135706  18:55:21.286 INF config path=/dev/shm/go2rtc.yaml
frigate    | 2024-10-19 18:55:21.287879486  18:55:21.287 INF [rtsp] listen addr=:8554
frigate    | 2024-10-19 18:55:21.287882378  18:55:21.287 INF [api] listen addr=:1984
frigate    | 2024-10-19 18:55:21.288969569  18:55:21.288 INF [webrtc] listen addr=:8555
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service certsync: starting
frigate    | s6-rc: info: service certsync successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2024-10-19 18:55:21.609687081  [INFO] Starting certsync...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2024-10-19 18:55:21.784011190  127.0.0.1 - - [19/Oct/2024:18:55:21 -0400] "" 400 0 "-" "-" "-"
frigate    | 2024-10-19 18:55:25.588293542  [2024-10-19 18:55:25] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate    | 2024-10-19 18:55:25.643942207  [2024-10-19 18:55:25] frigate.util.config            INFO    : frigate config does not need migration...
frigate    | 2024-10-19 18:55:25.813679029  [2024-10-19 18:55:25] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
frigate    | 2024-10-19 18:55:25.842974550  [2024-10-19 18:55:25] frigate.app                    INFO    : Starting Frigate (0.15.0-5d8bcb42)
frigate    | 2024-10-19 18:55:25.872609954  [2024-10-19 18:55:25] peewee_migrate.logs            INFO    : Starting migrations
frigate    | 2024-10-19 18:55:25.874860479  [2024-10-19 18:55:25] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate    | 2024-10-19 18:55:25.893996229  [2024-10-19 18:55:25] frigate.app                    INFO    : Recording process started: 306
frigate    | 2024-10-19 18:55:25.912861284  [2024-10-19 18:55:25] frigate.app                    INFO    : Review process started: 311
frigate    | 2024-10-19 18:55:25.920012250  [2024-10-19 18:55:25] frigate.app                    INFO    : go2rtc process pid: 104
frigate    | 2024-10-19 18:55:25.990435018  [2024-10-19 18:55:25] detector.cpu01                 INFO    : Starting detection process: 323
frigate    | 2024-10-19 18:55:26.006230607  [2024-10-19 18:55:25] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | 2024-10-19 18:55:26.042315146  [2024-10-19 18:55:26] frigate.app                    INFO    : Output process started: 339
frigate    | 2024-10-19 18:55:26.123903044  [2024-10-19 18:55:26] frigate.app                    INFO    : Camera processor started for outdoor1: 362
frigate    | 2024-10-19 18:55:26.267513814  [2024-10-19 18:55:26] frigate.app                    INFO    : Capture process started for outdoor1: 413
frigate    | 2024-10-19 18:55:26.440307712  [2024-10-19 18:55:26] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate    | 2024-10-19 18:55:30.371085157  [INFO] Starting go2rtc healthcheck service...
^CGracefully stopping... (press Ctrl+C again to force)
Stopping frigate ...
```

### Relevant go2rtc log output

```shell
No go2rtc error
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:stable
    image: asetlur13/frigate:0.15.0-5d8bcb42
    shm_size: "256mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/storage:/media/frigate
      - ./frigate/certs:/etc/letsencrypt/live/frigate:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      #- "5000:5000"
      #- "1984:1984"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
```

### Object Detector

Other
