### DISCUSSION TITLE
Live view aspect ratio is not correct for Wyze Cam V2 with wz_mini_hacks

### DISCUSSION THREAD

**Discussion by hua-bing** [blakeblackshear/frigate#14459] [Ask A Question] [answered]
I have one Wyze Cam V2 running on wz_mini_hacks firmware.  The aspect ratio is shown as 4:3 from live view in Frigate 0.14.1.  The aspect ratio is shown correctly in Frigate 0.12.1.  I did observe that Frigate first has it set to 16:9 for a split of second and then changed it to 4:3 when I first load the page.  I tried to force the correct ratio in config.yml following the doc:
`birdseye:`
`  enabled: true`
`  mode: continuous`
`  width: 1920`
`  height: 1080`
But this didn't help.

The go2rtc setting for this camera is:
`go2rtc:`
`  streams:`
`    front_door:`
`        # rtsp url format for wz_mini_hacks`
`      - rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast`
`      - ffmpeg:front_door#audio=aac`
And here is how I use it:
`cameras:`
`  front_door:`
`    ffmpeg:`
`      inputs:`
`        - path: rtsp://localhost:8554/front_door`
`          input_args: preset-rtsp-restream`
`          roles:`
`            - detect`
`            - record`

**Comment by hawkeye217** [comment]
This is incorrect. You need to set the appropriate width and height in your `detect` section, eg:

```
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: ???
      height: ???
```

**Reply by hua-bing** [reply]
Thanks.  I didn't know that piece info. is necessary for my question.  I have that set globally:
`detect:`
`  enabled: true`
`  width: 1920`
`  height: 1080`

**Reply by hawkeye217** [reply]
You just need to match the aspect ratio of your camera to the aspect ratio of `detect`. 1920/1080 is a 16/9 aspect ratio. 1920/1280 would be a 4/3 aspect ratio.

**Reply by hua-bing** [reply]
Thanks but I am a bit lost.  I don't see anywhere in my config file that has 1280 to make it 4:3:
`grep -c 1280 config.yml`
`0`
Including this V2 with wz_mini_hacks, I have total of 7 Wyze cameras (other 6 running Wyze RTSP firmware).  And they are set up in the same way.  Only this one is having this aspect ratio issue.

**Reply by hua-bing** [reply]
BTW, I updated my original question to mention that the aspect ratio was fine for this camera in Frigate 0.12.1.

**Reply by hawkeye217** [reply]
There have been many changes with the way Frigate works since 0.12.

Can you provide the output of `http://frigate_ip:5000/api/ffprobe?paths=camera.front_door`?

**Reply by hua-bing** [reply]
Here is the ouptut:
```
[
    {
        "return_code": 0,
        "stderr": "",
        "stdout": {
            "programs": [],
            "streams": [
                {
                    "avg_frame_rate": "15/1",
                    "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
                    "height": 1080,
                    "width": 1920
                },
                {
                    "avg_frame_rate": "0/0",
                    "codec_long_name": "AAC (Advanced Audio Coding)"
                }
            ]
        }
    }
]
```
Other cameras have "avg_frame_rate: 20/1".  That's the only difference that I spotted (the output is very short after all).

**Reply by hawkeye217** [reply]
So if you set:

```
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```

Frigate should display everything at a 16:9 aspect ratio. 

Are you seeing something different?

**Reply by hawkeye217** [reply]
Also, if you run ffprobe on the camera URL (`rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast`), what does it show?

**Reply by hua-bing** [reply]
> Also, if you run ffprobe on the camera URL (`rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast`), what does it show?

```
# binary info omitted
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
# several repeats of this
[h264 @ 0x5568e039f0c0] decode_slice_header error
[h264 @ 0x5568e039f0c0] no frame!
Input #0, rtsp, from 'rtsp://xxx:xxx@192.168.xxx.xxx:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2022.04.26
    comment         : LIVE555 Streaming Media v2022.04.26
  Duration: N/A, start: 0.000875, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 15 fps, 14.92 tbr, 90k tbn
  Stream #0:1: Audio: pcm_s16be, 8000 Hz, mono, s16, 128 kb/s
```

**Reply by hawkeye217** [reply]
I don't see anything that would cause Frigate to display your camera in a 4:3 aspect ratio. What is your full Frigate config?

**Reply by hua-bing** [reply]
> So if you set:
> 
> ```
> cameras:
>   front_door:
>     ffmpeg:
>       inputs:
>         - path: rtsp://localhost:8554/front_door
>           input_args: preset-rtsp-restream
>           roles:
>             - detect
>             - record
>     detect:
>       width: 1920
>       height: 1080
> ```
> 
> Frigate should display everything at a 16:9 aspect ratio.
> 
> Are you seeing something different?

I thought it is not necessary because I have it set globally.  Anyway, I just tried, still shows 4:3.

**Reply by hawkeye217** [reply]
What is your full Frigate config?

**Reply by hua-bing** [reply]
> I don't see anything that would cause Frigate to display your camera in a 4:3 aspect ratio. What is your full Frigate config?

```
mqtt:
  host: 192.168.xxx.xxx

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    front_door:
        # rtsp url format for wz_mini_hacks
      - rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast
      - ffmpeg:front_door#audio=aac

    garage_side:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:garage_side#audio=aac

    porch:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:porch#audio=aac

    backyard:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:backyard#audio=aac

    garage_outside:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:garage_outside#audio=aac

    under_deck:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:under_deck#audio=aac

    house_side:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:house_side#audio=aac

  webrtc:
    candidates:
      - 192.168.xxx.xxx:49173
      - stun:49173

detect:
  enabled: true
  width: 1920
  height: 1080

objects:
  track:
    - person
    - cat
    - bird

motion:
  mask:
    - &wyze_timestamp_mask 1870,1011,1870,1053,1391,1053,1391,1011

record:
  enabled: true
  retain:
    days: 60
    mode: all

snapshots:
  enabled: true

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  garage_side:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_side
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  garage_outside:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_outside
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  porch:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/porch
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  house_side:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/house_side
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  under_deck:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/under_deck
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

version: 0.14
```
BTW, looks I should have set "roles" globally because it's the same for all cameras.

**Reply by hawkeye217** [reply]
I believe I know what's happening, but to be sure, can you change your `front_door` input to the actual URL, just to test:

```
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast
```
        
This will temporarily bypass go2rtc. Does the live video appear as 16/9 then?

**Reply by hua-bing** [reply]
> I believe I know what's happening, but to be sure, can you change your `front_door` input to the actual URL, just to test:
> 
> ```
> cameras:
>   front_door:
>     ffmpeg:
>       inputs:
>         - path: rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast
> ```
> 
> This will temporarily bypass go2rtc. Does the live video appear as 16/9 then?

Thanks, but bypassing go2rtc didn't change the aspect ratio.  BTW, I didn't use go2rtc restreaming in 0.12.1.

**Reply by hawkeye217** [reply]
Can you post a screenshot of what you're seeing? If you bypass go2rtc and set the `detect` dimensions to `1920` and `1080`, the stream should absolutely be displaying at 16/9.

**Reply by hua-bing** [reply]
> Can you post a screenshot of what you're seeing? If you bypass go2rtc and set the `detect` dimensions to `1920` and `1080`, the stream should absolutely be displaying at 16/9.

Sure:
![wrong_aspect_ratio](https://github.com/user-attachments/assets/0e56c782-337f-4e69-bef1-d6ab9479b90e)

**Reply by hawkeye217** [reply]
Have you also removed or renamed the entry in your go2rtc config after bypassing it?

```
go2rtc:
  streams:
    front_door:          <---- rename or delete this stream
        # rtsp url format for wz_mini_hacks
      - rtsp://xxxx:xxxx@192.168.xxx.xxx:8554/unicast
      - ffmpeg:front_door#audio=aac
```

**Reply by hua-bing** [reply]
> Have you also removed or renamed the entry in your go2rtc config after bypassing it?

Ok, I removed it and now it shows 16:9.

**Reply by hawkeye217** [reply]
Ok, great. One more test.

If you re-enable it in go2rtc and view the stream from the go2rtc dashboard (you may have to map port 1984 either using the Docker CLI (`-p 1984:1984`) or adding `1984:1984` to the ports list in your docker-compose file), does the stream show as 4:3 or 16:9?

`http://frigate_ip:1984/stream.html?src=front_door`

**Reply by hua-bing** [reply]
shows 16:9 under http://frigate_ip:1984/stream.html?src=front_door

**Reply by hawkeye217** [reply, marked as answer]
Ok. This might be a bug with wz_mini_hacks.

Frigate's frontend loads the dimensions of the video from the HTML video element. See the code here: https://github.com/blakeblackshear/frigate/blob/6c70e560598c46f708739c03c041f38aba9f4672/web/src/components/player/MsePlayer.tsx#L77 and https://github.com/blakeblackshear/frigate/blob/6c70e560598c46f708739c03c041f38aba9f4672/web/src/components/player/MsePlayer.tsx#L552

It then uses these dimensions to scale the player appropriately here: https://github.com/blakeblackshear/frigate/blob/6c70e560598c46f708739c03c041f38aba9f4672/web/src/views/live/LiveCameraView.tsx#L272

Since your config is simple, the only reason I can see why this would be displaying as 4:3 is that the video tag is receiving the wrong dimensions from your browser's `<video>` tag.

Your workaround is to not use restreaming/go2rtc.

**Reply by my-umd** [reply]
Thanks.  If I do not use restreaming/go2rtc, will Homeassistant integration be affected?  My impression is that go2rtc is needed for Homeassistant integration.

**Reply by hawkeye217** [reply]
If you are using the Frigate card in Home Assistant, you can still choose the jsmpeg live provider. Or you could still use go2rtc, but change the stream name to anything other than `front_door`.

But go2rtc is not strictly necessary to use the official Frigate HA integration.

**Reply by hua-bing** [reply]
That's great.  Thanks for your help.

**Reply by hawkeye217** [reply]
Happy to help!

**Reply by computergreek** [reply]
@hawkeye217 hey, what do you mean by "change the stream name to anything other than `x`"? I'm having this same issue, and think i confirmed that it's an issue with [wyze_mini_hacks](https://github.com/gtxaspec/wz_mini_hacks/issues/671).

as of today, the aspect ratio is working well when i'm viewing records and the live stream **from the home assistant integration** card. however, it's still appearing in the 4:3 aspect ratio when viewing the live stream through frigate itself.

any idea on how to get around that? 
it's my understanding that there are basically two separate instances of go2rtc being used with what i'm trying to do--one within wyze_mini_hacks and one within frigate. when you suggested the workaround to not use re-streaming/go2rtc, which one specifically did you mean?

sidenote, it is neat and curious that the home assistant integration is working well with its native 16:9 resolution so it looks like that part got resolved--just not with the live view within frigate itself.

**Reply by hawkeye217** [reply]
The HA integration is probably not using MSE. This seems to be an issue with the MSE stream only.

You can use jsmpeg in Frigate to work around the issue. Without seeing your config, I can't give you the exact steps you need, however.

**Reply by computergreek** [reply]
so in my continued testing of this, i'm currently looking at it in 2 ways: one, 'natively' through frigate (http://local-frigate-instance:5000/#doggy-cam) and through home assistant's frigate proxy (http://homeassistant.local:8123/ccab4aaf_frigate-proxy/ingress). 

it looks fine (native 16:9) through the home assistant frigate proxy add-on, but when looking at it through frigate's own 'native' webapp (http://local-frigate-instance:5000/#doggy-cam), the live preview is shown in 4:3. 

any thoughts on what's going on with that? this is kinda neat and confusing at the same time.

**Reply by hawkeye217** [reply]
It could be because of a few reasons, but perhaps the 4:3 preview you're seeing is using MSE and that the 16:9 preview is using jsmpeg.

Are you using Chrome? And are you viewing the HA proxied stream on the same browser as the native frigate UI?

You can see the stream type being used by inspecting the player's HTML element. If it's a `video` tag, it's using MSE (or WebRTC if configured). If it's a `canvas` element, it's using jsmpeg.

**Reply by computergreek** [reply]
> That's great. Thanks for your help.

@hua-bing @hawkeye217 
i think might've found a solution (or at least a workaround for this issue): i set ffmpeg (via go2rtc) to transcode (re-encode?) the stream to force it to be in 16:9 aspect ratio. here's what my setup looks like:

```
go2rtc:
  streams:
    wyze_cam_v3_main:
      - ffmpeg:rtsp://192.168.3.151:8554/1080p?mp4#video=h264#video_filter=setdar=16/9#audio=opus
```


& it's now brilliant! i'm very pleased that i'm now seeing the wyze cam v3's live stream in the correct aspect ratio (16:9) and not in 4:3.
