### DISCUSSION TITLE
[Support]: frigate/<camera_name>/<object_name>/snapshot MQTT trigger payload decoding error

### DISCUSSION THREAD

**Discussion by rpanachi** [blakeblackshear/frigate#14462] [General Support] [answered]
### Describe the problem you are having

The events published on frigate/<camera_name>/<object_name>/snapshot can't be used as MQTT trigger on automations, causing a `Can't decode payload` error.

Automation yaml:
```
alias: "MQTT trigger test"
trigger:
  - platform: mqtt
    topic: frigate/doorbell/person/snapshot
action:
  - service: notify.notify
    metadata: {}
    data:
      message: Snapshot triggered
mode: single
```

Frigate: v5.4.0
Frigate integration: 0.14.1
Home Assistant Core: 2024.6.1
Home Assistant Supervisor: 2024.10.2

### Version

v5.4.0

### What browser(s) are you using?

Google Chrome 126.0.6478.185

### Frigate config file

```yaml
cameras:
  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.0.123/Preview_01_sub
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
```

### Relevant Frigate log output

```shell
2024-10-20 17:10:40.538 WARNING (MainThread) [homeassistant.components.mqtt.client] Can't decode payload
b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff
...(many lines of binary data output)
on frigate/doorbell/person/snapshot with encoding utf-8 (for <Job None HassJobType.Callback <function async_attach_trigger.<locals>.mqtt_automation_listener at 0x7f4546de40>>)
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua (IMOU)

**Comment by hawkeye217** [comment]
The MQTT payload is base64 image data, so you'd need to use a `notify` service that supports images. For example, this is how it works for iOS:

```
action:
  - service: notify.mobile_app_<your_device>
    data:
      message: Snapshot triggered
      data:
        image: /api/frigate/notifications/<event_id>/thumbnail.jpg
```
