### DISCUSSION TITLE
[Support]: Frigate integration is using the deprecated constant MEDIA_CLASS_IMAGE, provoking error messages from Home Assistant.

### DISCUSSION THREAD

**Discussion by jeffstearns** [blakeblackshear/frigate#14464] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Home Assistant Core is logging messages complaing that the Frigate integration is using the deprecated constant MEDIA_CLASS_IMAGE.

At this point, the log messages are just warnings. They will become errors in HA Core 2025.10.

### Steps to reproduce

1. Go to Home Assistant -> Settings -> System -> Logs.
2. Search for log messages containing "Frigate".
3. Here's what I see:

`Log details (WARNING)
Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: October 19, 2024 at 1:12:29 PM (6 occurrences)
Last logged: October 19, 2024 at 1:12:29 PM

MEDIA_CLASS_IMAGE was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.IMAGE instead, please report it to the author of the 'frigate' custom integration
MEDIA_CLASS_MOVIE was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.MOVIE instead, please report it to the author of the 'frigate' custom integration
MEDIA_CLASS_VIDEO was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.VIDEO instead, please report it to the author of the 'frigate' custom integration
MEDIA_TYPE_IMAGE was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.IMAGE instead, please report it to the author of the 'frigate' custom integration
MEDIA_TYPE_VIDEO was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.VIDEO instead, please report it to the author of the 'frigate' custom integration`

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# 2024-05-27 - This file is "config.yml" -- created by JPS when migrating Frigate from Home Assistant to its own LXC.
#
##################################################################################################
#
#  WARNING: DON'T EDIT THIS FILE USING Frigate's BUILT-IN CONFIG FILE EDITOR.
#           AND DON'T USE FRIGATE's BUILT-IN "Save and restart" BUTTON.
#           DOING EITHER OF THESE TWO THINGS CAN CAUSE YOU TO LOSE THE CONTENTS OF THIS FILE.
#
#           INSTEAD, USE HOME ASSISTANT'S "File editor" TOOL TO EDIT frigate.yaml,
#           AND RESTART FRIGATE USING HOME ASSISTANT'S RESTART OPERATION.
#
##################################################################################################
#
#
# The official reference document for this file is https://docs.frigate.video/configuration/reference


mqtt:
  enabled: false

# Edge TPU Detector using Coral USB device
#
# Ref: https://docs.frigate.video/configuration/object_detectors/#single-usb-coral
detectors: # <-------- Add this section to specify the detectors you want to use
  coral: # <---------- Name your detector (you can choose any name)
    type: edgetpu # <-- This specifies that you want to use the Coral USB Accelerator
    device: usb # <-- This tells Frigate to use the USB connected Coral device

# ffmpeg
#
# This block is copied from https://docs.frigate.video/configuration/reference and modified by JPS as noted.
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
#
# Read this helpful description of video pipeline at https://docs.frigate.video/frigate/video_pipeline
# It really helps explain why certain config values are used:
#
# Frigate uses ffmpeg to receive a video stream from the camera and bust it into individual frames which are passed to the detector.
# This is CPU-intensive.  A GPU is a huge help, but our CWWK computers don't have a GPU.
# Intel processors have VAAPI to help with video decoding.  ffmpeg can use VAAPI when Frigate runs within a Proxmox LXC,
# but not when running within Home Assistant; I suspect a virtualization/privilege configuration problem.  Google "Proxmox VAAPI" to see postings about this.
#
# So in the meantime, we have to run ffmpeg entirely on the CPU.  To keep the CPU load tolerable,
# we feed ffmpeg from the camera's reduced resolution substream feed at a low framerate.  There's no need
#to run detection any faster than 1 fps.
#
# Read this great guide on substream configuration:
#   https://ipcamtalk.com/wiki/sub-stream-guide/
#
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  #global_args: -hide_banner -loglevel warning -threads 2
  #
  # Optional: global hwaccel args (default: shown below)
  hwaccel_args: preset-vaapi  # 2024-03-10 - Set by JPS because we have an Intel CPU (and no GPU).
  #hwaccel_args: []  # 2024-03-10 - JPS - Can use preset-vaapi when Frigate runs as a Proxmox LXC, but not when it runs within Home Assistant.  Probable virtualization/privilege configuration problem.
  #
  # Optional: global input args (default: shown below)
  #input_args: preset-rtsp-generic
  #
  # Optional: global output args
  #
  #output_args:
    # Optional: output args for detect streams (default: shown below)
    #detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    #
    # Optional: output args for record streams (default: shown below)
    #record: preset-record-generic
    #
    # Optional: output args for rtmp streams (default: shown below)
    #rtmp: preset-rtmp-generic
  #
  # Optional: Time in seconds to wait before ffmpeg retries connecting to the camera. (default: shown below)
  # If set too low, frigate will retry a connection to the camera's stream too frequently, using up the limited streams some cameras can allow at once
  # If set too high, then if a ffmpeg crash or camera stream timeout occurs, you could potentially lose up to a maximum of retry_interval second(s) of footage
  # NOTE: this can be a useful setting for Wireless / Battery cameras to reduce how much footage is potentially lost during a connection timeout.
  retry_interval: 10

# This block created and maintained by JPS:
cameras:
  casita_nw_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 90  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/casita_nw_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/casita_nw_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion: # <----- I created this block using Frigate -> Cameras -> CASITA NW CAM -> Debug -> Show Options -> Mask & Zone creator (http://haos.local:8123/cameras/casita_nw_cam/editor)
      mask:
        - 402,50,542,86,704,152,704,0,465,0,197,0
        - 0,480,113,480,66,249,82,0,0,0
        - 547,480,704,480,704,350,652,360
    webui_url: http://10.5.8.57   # Optional: URL to visit the camera web UI directly from the system page.

  casita_se_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 80  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/casita_se_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/casita_se_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 437,35,704,38,704,0,443,0
        - 581,480,704,480,704,0,607,0
        - 195,280,466,149,389,103,118,185
    webui_url: http://10.5.8.56   # Optional: URL to visit the camera web UI directly from the system page.

  dining_room_camera: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 5  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/dining_room_camera # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
##        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
##        - path: rtsp://127.0.0.1:8554/dining_room_camera_substream # <--- the name here must match the name of the camera in go2rtc config section below.
##          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
##          roles:
##            - detect
##    detect:
##      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
##    snapshots:
##      enabled: true # <----- Enable snapshots
##    motion:
##      mask:
##        - 1789,107,1862,107,1862,55,1789,55
##    objects:
##      filters:
##        person:
##          mask:
##            - 0,0,0,389,1920,375,1920,0
##    # webui_url:   # Optional: URL to visit the camera web UI directly from the system page.  The AD410 has no web UI, just an API.

  front_doorbell_camera: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 40  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/front_doorbell_camera # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/front_doorbell_camera_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 720,0,424,0,427,256,720,261
    # webui_url:   # Optional: URL to visit the camera web UI directly from the system page.  The AD410 has no web UI, just an API.

  garage_ne_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 10  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/garage_ne_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/garage_ne_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 704,86,479,82,480,45,704,46
        - 400,341,545,348,519,72,459,80
        - 0,270,65,0,151,0,227,64,52,319
    objects:
      filters:
        person:
          mask:
            - 168,213,333,229,367,49,231,62 # <------ Mask out the truck windshield; the object detector sometimes thinks its a person
    webui_url: http://10.5.8.51   # Optional: URL to visit the camera web UI directly from the system page.

  garage_nw_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 110  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/garage_nw_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/garage_nw_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 480,262,264,278,146,71,95,67,88,0,480,0
        - 480,393,480,629,426,628,358,441
        - 0,321,0,272,222,246,234,282
        - 0,277,53,269,66,0,0,0
        - 246,582,0,606,0,537,86,487,197,470
    objects:
      filters:
        person:
          mask:
            - 480,262,313,270,147,50,126,0,480,0
    webui_url: http://10.5.8.50   # Optional: URL to visit the camera web UI directly from the system page.

  garage_sw_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 100  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/garage_sw_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/garage_sw_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 0,480,242,480,237,439,0,436
        - 0,99,68,163,303,68,414,35,459,26,450,0,0,0
        - 636,103,664,480,704,480,704,0,620,0
        - 302,346,543,437,522,480,311,415,129,303,152,265
        - 125,480,51,195,61,284,21,268
    objects:
      filters:
        person:
          mask:
            - 51,195,189,119,415,45,415,0,0,0
    webui_url: http://10.5.8.58   # Optional: URL to visit the camera web UI directly from the system page.

  house_se_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 70  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/house_se_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/house_se_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 455,0,448,53,704,57,704,0
        - 0,285,271,276,481,181,517,0,0,0
        - 70,480,133,437,86,239,27,262
        - 429,480,522,480,621,321,573,296
    webui_url: http://10.5.8.55   # Optional: URL to visit the camera web UI directly from the system page.

  mech_room_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 50  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/mech_room_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/mech_room_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 480,0,480,524,410,507,431,389,402,337,420,264,417,0
        - 0,704,167,704,272,704,267,566,197,516,0,497
        - 0,175,480,114,480,0,0,0
    webui_url: http://10.5.8.54   # Optional: URL to visit the camera web UI directly from the system page.

  office_ne_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 30  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/office_ne_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/office_ne_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 623,480,704,480,704,64,583,107
        - 268,109,99,313,383,424,427,110
        - 149,69,69,173,95,216,264,57
        - 0,480,227,480,229,446,0,447
    webui_url: http://10.5.8.53   # Optional: URL to visit the camera web UI directly from the system page.

  office_nw_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 20  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/office_nw_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/office_nw_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 130,480,238,480,235,439,136,438
        - 263,177,463,276,533,57,270,0
        - 586,56,704,134,704,75,599,0
    webui_url: http://10.5.8.52   # Optional: URL to visit the camera web UI directly from the system page.

  pool_equipment_cam: # <------ Camera name seen by Home Assistant
    enabled: true
    ui:
      order: 60  # Set sort order of cameras in the UI. Larger numbers come later.  (default: alphabetic)
      dashboard: true  # Optional: Show the camera in the Frigate UI? (default: true)
    ffmpeg:
      inputs:
        # High resolution stream, used for viewing and recording.  We pull this from the go2rtc restreamer.
        - path: rtsp://127.0.0.1:8554/pool_equipment_cam # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - record
        # Low resolution stream, used for detection.  We pull this directly from the camera; no need for go2rtc here.
        - path: rtsp://127.0.0.1:8554/pool_equipment_cam_substream # <--- the name here must match the name of the camera in go2rtc config section below.
          input_args: preset-rtsp-restream  # ffmpeg args optimized for having Frigate pull from restreamer
          roles:
            - detect
    detect:
      enabled: true # <----- Enable object detection
    record:
      enabled: true # <----- Enable recording
    snapshots:
      enabled: true # <----- Enable snapshots
    motion:
      mask:
        - 0,143,0,0,240,0
        - 240,0,110,300,48,298,27,352,240,352
    webui_url: http://10.5.8.70   # Optional: URL to visit the camera web UI directly from the system page.







# RESTREAMING:
#
# Frigate can restream your video feed as an RTSP feed for other applications such as Home Assistant.
# This allows you to use a video feed for detection in Frigate and Home Assistant live view at the same time
# without having to make two separate connections to the camera.  The video feed is copied
# from the original video feed directly to avoid re-encoding. This feed does not include any annotation by Frigate.
#
# Frigate uses go2rtc to provide restream and MSE/WebRTC capabilities.
#
# Frigate makes the stream available at rtsp://<frigate_host>:8554/<camera_name>.  Port 8554 must be open.
# We installed Frigate within Home Assistant, so <frigate_host> has the same IP address as Home Assistant itself: 10.5.3.40
#
# go2rtc configuration is important but sadly is somewhat hidden in the frigate config docs.
# It's documented in a separate "Guides > Configuring go2rtc" section of the Frigate manual.
#
# You need to read all three of the following docs to learn about why you want restreaming,
# and how to configure it.
#   https://docs.frigate.video/guides/getting_started
#   https://docs.frigate.video/guides/configuring_go2rtc
#   https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream
go2rtc:
# Boost logging for now.  Reference: https://github.com/blakeblackshear/frigate/issues/5983
# XXX This log directive doesn't seem to make any difference.
  log:
    exec: trace

  streams:
    dining_room_camera:
      - rtsp://***@10.5.4.68:554/cam/realmonitor?channel=1&subtype=0&authbasic=64 # N.B. This camera is on the IoT VLAN, not the camera VLAN
    dining_room_camera_substream:
      - rtsp://***@10.5.4.68:554/cam/realmonitor?channel=1&subtype=1&authbasic=64 # N.B. This camera is on the IoT VLAN, not the camera VLAN

    front_doorbell_camera:
      - rtsp://***@10.5.4.84:554/cam/realmonitor?channel=1&subtype=0 # N.B. The doorbell camera is on the IoT VLAN, not the camera VLAN
    front_doorbell_camera_substream:
      - rtsp://***@10.5.4.84:554/cam/realmonitor?channel=1&subtype=1 # N.B. The doorbell camera is on the IoT VLAN, not the camera VLAN

    garage_nw_cam:
      - rtsp://***!!@10.5.8.50:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    garage_nw_cam_substream:
      - rtsp://***!!@10.5.8.50:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    garage_ne_cam:
      - rtsp://***!!@10.5.8.51:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    garage_ne_cam_substream:
      - rtsp://***!!@10.5.8.51:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    office_nw_cam:
      - rtsp://***!!@10.5.8.52:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    office_nw_cam_substream:
      - rtsp://***!!@10.5.8.52:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    office_ne_cam:
      - rtsp://***!!@10.5.8.53:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    office_ne_cam_substream:
      - rtsp://***!!@10.5.8.53:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    mech_room_cam:
      - rtsp://***!!@10.5.8.54:554/Streaming/Channels/1  # Hikvision camera -- Main stream=1, substream=2
    mech_room_cam_substream:
      - rtsp://***!!@10.5.8.54:554/Streaming/Channels/2  # Hikvision camera -- Main stream=1, substream=2

    pool_equipment_cam:
      - rtsp://***!!@10.5.8.70:554/Streaming/Channels/1  # Hikvision camera -- Main stream=1, substream=2
    pool_equipment_cam_substream:
      - rtsp://***!!@10.5.8.70:554/Streaming/Channels/2  # Hikvision camera -- Main stream=1, substream=2

    house_se_cam:
      - rtsp://***!!@10.5.8.55:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    house_se_cam_substream:
      - rtsp://***!!@10.5.8.55:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    casita_se_cam:
      - rtsp://***!!@10.5.8.56:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    casita_se_cam_substream:
      - rtsp://***!!@10.5.8.56:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    casita_nw_cam:
      - rtsp://***!!@10.5.8.57:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    casita_nw_cam_substream:
      - rtsp://***!!@10.5.8.57:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream

    garage_sw_cam:
      - rtsp://***!!@10.5.8.58:554/cam/realmonitor?channel=1&subtype=0  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream
    garage_sw_cam_substream:
      - rtsp://***!!@10.5.8.58:554/cam/realmonitor?channel=1&subtype=1  # Amcrest camera; subtype=0 for main stream; subtype=1 for substream


version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
Nothing relevant in the Frigate log.  The relevant messages are in the Home Assistant system log.  See above.
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Various Amcrest models.  Specifics probably don't matter in this case.

### Screenshots of the Frigate UI's System metrics pages

N/A
