### DISCUSSION TITLE
Clips not available (since adding audio?)

### DISCUSSION THREAD

**Discussion by TheSleepySlee** [blakeblackshear/frigate#1447] [Ask A Question]
Hi,

I have added audio to 2 out of 5 cameras. And I am getting no clips on all cameras.
Issue seems similar to: https://github.com/blakeblackshear/frigate/discussions/608

Logs:
```
frigate.events                 WARNING : Unable to create clip for garageptz and event 1627370811.981592-aj0sny. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for z5 and event 1627371195.593651-n5trq1. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for japonais and event 1627371601.040464-rp0p9h. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for japonais and event 1627371603.03982-qelqqu. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for z5 and event 1627371609.400927-41dxbz. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for japonais and event 1627371615.040893-09ep65. There were no cache files for this event.
```

Config:
```
ffmpeg:
  global_args: -hide_banner -loglevel info
```

Full log after restart:
```
 * Starting nginx nginx
   ...done.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.coral                 INFO    : Starting detection process: 39
frigate.app                    INFO    : Camera processor started for garageptz: 42
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for japonais: 44
frigate.app                    INFO    : Camera processor started for z5: 46
frigate.app                    INFO    : Camera processor started for garage: 47
frigate.app                    INFO    : Camera processor started for portailcam: 49
frigate.app                    INFO    : Capture process started for garageptz: 50
frigate.app                    INFO    : Capture process started for japonais: 52
frigate.app                    INFO    : Capture process started for z5: 54
frigate.app                    INFO    : Capture process started for garage: 58
frigate.app                    INFO    : Capture process started for portailcam: 62
frigate.edgetpu                INFO    : TPU found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5626d749c140] moov atom not found
/tmp/cache/japonais-20210727094706.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: japonais-20210727094706.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558eff12a140] moov atom not found
/tmp/cache/z5-20210727094707.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: z5-20210727094707.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x556d9a944140] moov atom not found
/tmp/cache/garage-20210727094706.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: garage-20210727094706.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5610ce766140] moov atom not found
/tmp/cache/garageptz-20210727094706.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: garageptz-20210727094706.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b2e8d2a140] moov atom not found
/tmp/cache/portailcam-20210727094706.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: portailcam-20210727094706.mp4
frigate.events                 WARNING : Unable to create clip for japonais and event 1627372110.455279-w9cp4i. There were no cache files for this event.
```

Config for one of the cameras which has no audio enabled:
```
  japonais:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.0.206:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://xxx:yyy@192.168.0.206:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
      output_args:
    # Optional: output args for detect streams (default: shown below)
        detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for clips streams (default: shown below)
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

    # Required: width of the frame for the input with the detect role
    width: 1280
    # Required: height of the frame for the input with the detect role
    height: 720
    motion:
      mask: 1279,0,989,0,1279,107

    best_image_timeout: 60

    zones:
      portail:
        coordinates: 1220,101,1208,164,1033,131,1139,31
    detect:
      enabled: True
      max_disappeared: 10
    clips:
      enabled: True
      pre_capture: 10
      post_capture: 120
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30
    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 300
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 300
```

Other cam with audio:
```
      output_args:
    # Optional: output args for detect streams (default: shown below)
        detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for clips streams (default: shown below)
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```
