### DISCUSSION TITLE
Loud microphone feedback with Reolink Doorbell

### DISCUSSION THREAD

**Discussion by Roboreli** [blakeblackshear/frigate#14471] [Ask A Question]
Hello, 

Here is my configuration:

- Doorbell Reolink (firmware : v3.0.0.4110_2410111120)
- Frigate add-on version: 0.14.1

Home Assistant : 

- Core2024.10.3
- Supervisor2024.10.2
- Operating System13.2

Here is my frigate configuration file frigate.yaml:
```
mqtt:
  host: core-mosquitto
  port: 1883
  user: admin
  password: pwd
  topic_prefix: frigate
  stats_interval: 60

go2rtc:
  streams:
    reolink:
      - rtsp://admin:pwd@192.168.1.80:554/h264Preview_01_sub
      - ffmpeg:rtsp://admin:pwd@192.168.1.80:554/h264Preview_01_sub#audio=pcm

cameras:

  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=copy

          roles:
            - detect
    record:
      enabled: false
    detect:
      enabled: false
    motion:
      enabled: false
version: 0.14
```

I have a difficulty that I cannot overcome despite the different configurations that I have been able to test: when I speak, I hear myself very loudly in return. It seems the sound emitted by the speaker is picked up by the microphone.

In this [thread](https://github.com/blakeblackshear/frigate/issues/9657), @TheDescender says "reolink doorbell puts a huge noise gate on the mic when 2way is engaged", but it does not seem to apply in my case when I use Frigate (no pb with the reolink app).

Has this ever happened to any of you? 

Best regards
