### DISCUSSION TITLE
MQTT events vs Frigate+ snapshots?

### DISCUSSION THREAD

**Discussion by ibrewster** [blakeblackshear/frigate#14484] [Ask A Question] [answered]
I've been working on a notification system that uses the MQTT frigate/events feed. I check the "after" portion of the payload, and check for a number of things:

- end_time is not None (if it is, I remove the object from consideration)
- false_positive is not True (if it is, I ignore it)
- current_zones contains *something*, i.e. the object is in one of my defined zones.

If all of the above match, I make a note of the object ID, and trigger a "notification". This seems to work well, except that using this criteria I have been getting a number of notifications for objects where I am not getting corresponding events/snapshots in the web interface.

I have checked the required_zones property in my config, and it matches what I am checking for. So my question is, in what scenario might the above criteria all be the case, but no snapshot be saved or event created? It does seem that most of these events are short - perhaps there is a minimum time parameter I missed to create snapshots/events in the web interface that does not apply to the MQTT feed?

Since the system is considering these to be true positives, and they are in my designated zones, ideally they should all create snapshots and events in the web interface. If not, I can look into making my system save snapshots itself.

Thanks!

**Comment by NickM-27** [comment]
if you want the system to match what you see in the UI then you should use the /reviews topic not /events

**Comment by ibrewster** [comment]
I'm using events because that's what you recommended. That said, are what I am seeing in /events actually false positives then, even though they claim not to be? Because if there *is* really a person, and they *are* really in one of my zones, I want a snapshot and event to be created in the UI. If not, then why is the message being posted to /events, marked as *not* a false positive, and showing one or more of my zones?

Sorry for being dense, I'm just trying to understand what is going on here - if the event is valid, why is it not creating a snapshot/review, and if not why is it being posted to /events?

**Reply by NickM-27** [reply]
There are more filters for an object to become a review item, for example it has to have moved. if a car is detected in a drive then a review item won't be created until the car moves since there is no activity occurring.

**Reply by ibrewster** [reply]
EDIT: Ok, I think I may have found it. It looks like, by default, "detections" uses all labels, but "alerts" defaults to only people and cars. Am I correct in thinking that in the case I get a detection, but not an alert, I'll see the event in the /events feed, but not get a snapshot/review item? If not, then the below applies.

Well, moving obviously isn't the deciding factor here, since we are talking about new objects that have either a) been initially detected in, or  b) moved into one of my zones. We aren't talking something that is marked "stationary" here, because as I mentioned I keep track of what I have seen, and these are _new_ detections. Unless a new detection is marked stationary until it moves?

So I guess it's one of these other "filters" that is causing events to not become review items. Is there a list somewhere so I can see what filters might be accounting for this? The most obvious would be one that says an event must exist for a certain length of time before becoming a review item, in which case I want to set that length of time to zero - if the system detects a true positive in one of my required_zones, I want an event, even if that object isn't there for long.

**Reply by NickM-27** [reply]
> Am I correct in thinking that in the case I get a detection, but not an alert, I'll see the event in the /events feed, but not get a snapshot/review item?

No, the snapshot will be taken for any object that the snapshot config applies to. But to be clear the Frigate UI in 0.14 does not show snapshots anymore except in the Frigate+ page so it is not clear if you truly mean snapshot or review item

**Reply by NickM-27** [reply]
the easiest way to help would be to see a /events mqtt payload for an object that did not get a snapshot

**Reply by ibrewster** [reply]
Ok, here's one: The car pulled into my driveway and parked, but the first (and only) snapshot I get is of the *person* in the car getting out and heading inside. No snapshot or review video of the car itself pulling in. Incidentally - perhaps this is related? - I was watching the debug screen the other day, with a car marked as stationary in my driveway. I was able to watch it back all the way down the driveway, and turn around almost all the way, marked as "stationary" the entire time. Perhaps the issue is related? Dunno.

```
{
  "before": {
    "id": "1729748593.816228-5skssm",
    "camera": "drivecam",
    "frame_time": 1729748594.002228,
    "snapshot": {
      "frame_time": 1729748594.002228,
      "box": [745, 241, 1515, 931],
      "area": 531300,
      "region": [605, 32, 1653, 1080],
      "score": 0.98828125,
      "attributes": []
    },
    "label": "car",
    "sub_label": null,
    "top_score": 0.98828125,
    "false_positive": false,
    "start_time": 1729748593.816228,
    "end_time": null,
    "score": 0.98828125,
    "box": [745, 241, 1515, 931],
    "area": 531300,
    "ratio": 1.1159420289855073,
    "region": [605, 32, 1653, 1080],
    "stationary": false,
    "motionless_count": 1,
    "position_changes": 0,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": false,
    "has_snapshot": false,
    "attributes": {},
    "current_attributes": []
  },
  "after": {
    "id": "1729748593.816228-5skssm",
    "camera": "drivecam",
    "frame_time": 1729748594.395397,
    "snapshot": {
      "frame_time": 1729748594.002228,
      "box": [745, 241, 1515, 931],
      "area": 531300,
      "region": [605, 32, 1653, 1080],
      "score": 0.98828125,
      "attributes": []
    },
    "label": "car",
    "sub_label": null,
    "top_score": 0.98828125,
    "false_positive": false,
    "start_time": 1729748593.816228,
    "end_time": null,
    "score": 0.98828125,
    "box": [747, 245, 1508, 927],
    "area": 519002,
    "ratio": 1.1158357771260996,
    "region": [613, 44, 1649, 1080],
    "stationary": false,
    "motionless_count": 3,
    "position_changes": 0,
    "current_zones": ["Driveway"],
    "entered_zones": ["Driveway"],
    "has_clip": false,
    "has_snapshot": false,
    "attributes": {},
    "current_attributes": []
  },
  "type": "update"
}
```

**Reply by NickM-27** [reply]
no snapshot was created for the car because it has not moved `    "position_changes": 0,`

**Reply by ibrewster** [reply]
Ok...but it has. It was not in my driveway before, and it drove in. You don't get much more movement than that!. So then the issues _do_ seem to be related, in that my configuration apparently isn't detecting objects as moving even though they are. Which means the question then becomes "what parameters do I need to change so that a car pulling into or out of my driveway is detected as a moving object"?

This is probably made more difficult by the fact that "into" or "out of" my driveway movement is mostly towards/away from the camera, and as such is reflected more in a change of size of the object than a significant change of position. I could see this being difficult for the system to pick up on.

**Reply by ibrewster** [reply]
This is my current config, if it helps any:

```
mqtt:
  enabled: true
  host: mqtt.server.name
  user: mqttuser
  password: mqttpassword

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    drivecam:
      - rtsp://my.camera.url/video/path
  webrtc:
    canidates:
      - my.server.ip:8555
      - stun:8555

snapshots:
  enabled: true

cameras:
  drivecam: 
    enabled: true
    snapshots:
      enabled: true
      quality: 80
      required_zones:
        - Driveway
        - Porch
        - Yard
    mqtt:
      required_zones:
        - Driveway
        - Porch
        - Yard
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/drivecam
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - audio
            - detect
    record:
      enabled: true
    detect:
      enabled: true
      fps: 5
    zones:
      Driveway:
        coordinates: 
          0.002,0.167,0.091,0.17,0.106,0.158,0.36,0.165,0.863,0.898,0.792,1,0,1,0,0.885,0.2,0.882,0.166,0.519,0.021,0.473
        loitering_time: 0
        inertia: 3
      Porch:
        coordinates: 0.612,0.527,0.864,0.396,1,0.542,1,0.636,0.951,0.802,0.863,0.896
        loitering_time: 0
        inertia: 3
      Yard:
        coordinates: 0.612,0.523,0.361,0.164,0.689,0.197,0.865,0.396
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - horse
          - person
    motion:
      mask: 0.763,0.04,0.76,0.002,0.999,0,0.999,0.04
      threshold: 35
      contour_area: 15
      improve_contrast: 'true'
    review:
      alerts:
        labels:
          - car
          - person
          - cat
          - dog
          - horse
        required_zones:
          - Driveway
          - Porch
          - Yard
      detections:
        required_zones:
          - Driveway
          - Porch
          - Yard
model:
  path: plus://<model_id>
detectors:
  coral:
    type: edgetpu
    device: pci
objects:
  track:
    - person
    - car
    - cat
    - dog
    - horse
  filters:
    person:
      min_score: 0.72
      threshold: 0.75
    car:
      min_score: 0.75
      threshold: 0.85
    cat:
      min_score: 0.70
      threshold: 0.80
    dog:
      min_score: 0.70
      threshold: 0.80
    horse:
      min_score: 0.3
      threshold: 0.5
version: 0.14
```
