### DISCUSSION TITLE
Why do i not have the full footage of this detection?

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#14515] [Ask A Question]
This is a part of my config where you can see that I have a review section without labels (default is person and cars), and a detection also without labels (default: all labels that are tracked).

So there was a cat moving around, but the detection video only contains the first half of the movement.. Why? 

Btw. my detection zone is the front part of the cabinet. So as soon as the cat moves through the cabinet, it will be recorded. Video is attached.

```
record:
  enabled: true

objects:
  track:
    - person
    - dog
    - cat
    - umbrella

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    review:
      alerts:
        required_zones: vorgarten
      detections:
        required_zones: vorgarten
    zones:
      vorgarten:
        coordinates: 
          0.603,0.255,0.61,0.355,0.613,0.436,0.615,0.517,0.614,0.59,0.611,0.729,0.612,0.744,0.567,0.753,0.504,0.763,0.42,0.774,0.318,0.778,0.19,0.771,0.097,0.752,0.065,0.658,0.058,0.507,0.063,0.351,0.077,0.265,0,0.266,0,1,1,1,1,0
        loitering_time: 0
    live:
      stream_name: reolink_doorbell
```

https://github.com/user-attachments/assets/a79ab6ab-4b7f-4fe3-a9b6-b2699332c7ed

This is also the "vorgarten" zone (actually the whole front part):
<img width="732" alt="Bildschirmfoto 2024-10-22 um 20 50 17" src="https://github.com/user-attachments/assets/27612167-f6ad-464d-83af-bce3aca5c944">

May it be because of this rule: "Presence in a zone is evaluated based on the bottom center of the bounding box for the object"?
In this case the feet of the cat intersect with the border of my zone/cam?
