### DISCUSSION TITLE
Yet another plea for help with hwaccel

### DISCUSSION THREAD

**Discussion by lagnat** [blakeblackshear/frigate#14517] [Hardware Acceleration Support]
### Describe the problem you are having

Running a Beelink EQ13, Ubuntu 24 and docker compose.  Frigate finds the GPU but my ffmpeg processes are still at 15-25% of the CPU.  I've read in other places that ffmpeg should be closer to 2%.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  Garage:
    enabled: true
    detect:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://xxx:xxx@192.168.1.68
        roles:
        - record
        - detect

  FrontDoor:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://xxx:xxx@192.168.1.65
        roles:
        - record
        - detect

  BackStairs:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://xxx:xxx@192.168.1.66
        roles:
        - record
        - detect
          
  Deck:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://xxx:xxx@192.168.1.67
        roles:
        - record
        - detect

motion:
  enabled: false

record:
  enabled: true
  retain:
    days: 5
    mode: all

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "160mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /cams:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
frigate  | 2024-10-22 19:31:52.564541930  [INFO] Preparing Frigate...
frigate  | 2024-10-22 19:31:52.566129612  [INFO] Preparing new go2rtc config...
frigate  | 2024-10-22 19:31:52.569595675  [INFO] Starting NGINX...
frigate  | 2024-10-22 19:31:52.581061510  [INFO] Starting Frigate...
frigate  | 2024-10-22 19:31:52.583253440  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2024-10-22 19:31:52.881709793  [INFO] Starting go2rtc...
frigate  | 2024-10-22 19:31:53.048540052  19:31:53.048 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-10-22 19:31:53.049989167  19:31:53.049 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-10-22 19:31:53.050391847  19:31:53.050 INF [api] listen addr=:1984
frigate  | 2024-10-22 19:31:53.050730706  19:31:53.050 INF [rtsp] listen addr=:8554
frigate  | 2024-10-22 19:31:53.051633618  19:31:53.051 INF [webrtc] listen addr=:8555/tcp
frigate  | 2024-10-22 19:31:53.937457718  [2024-10-22 19:31:53] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
frigate  | 2024-10-22 19:31:53.937557002  [2024-10-22 19:31:53] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-10-22 19:31:53.951094077  [2024-10-22 19:31:53] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-10-22 19:31:54.146455470  [2024-10-22 19:31:54] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-10-22 19:31:55.547155962  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-10-22 19:31:59.129662498  [2024-10-22 19:31:59] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-10-22 19:31:59.129797429  [2024-10-22 19:31:59] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-10-22 19:31:59.138023391  [2024-10-22 19:31:59] frigate.app                    INFO    : Recording process started: 405
frigate  | 2024-10-22 19:31:59.143432844  [2024-10-22 19:31:59] frigate.app                    INFO    : Recording process started: 414
frigate  | 2024-10-22 19:31:59.146198481  [2024-10-22 19:31:59] frigate.app                    INFO    : go2rtc process pid: 98
frigate  | 2024-10-22 19:31:59.167206186  [2024-10-22 19:31:59] detector.cpu                   INFO    : Starting detection process: 433
frigate  | 2024-10-22 19:31:59.171306981  [2024-10-22 19:31:59] frigate.app                    INFO    : Output process started: 435
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
Not readily available but I can get it if it would help.
```

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Multiple HikVision cameras

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-10-22 at 3 37 52 PM](https://github.com/user-attachments/assets/cc71351f-0bbc-4fd8-9ac8-c490515a5e7c)
![Screenshot 2024-10-22 at 3 38 11 PM](https://github.com/user-attachments/assets/20892d3c-a2d1-49eb-b9f2-5cf49f3279d3)
![Screenshot 2024-10-22 at 3 38 27 PM](https://github.com/user-attachments/assets/0366cb63-db4f-4720-adc3-6ce96d829003)

### Any other information that may be helpful

There are several cameras.  3 of them are recording at 1080p, H264 and 1 of them is recording at 2560x1440.  Note that I only want to record so if it's possible to further disable some features, I would do that.

**Comment by NickM-27** [comment]
You need to map the GPU into the container like the docs explain

**Reply by lagnat** [reply]
I tried the following and it didn't help.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "160mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /cams:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
