### DISCUSSION TITLE
[Support]: I have 64Gb storage but only Storage stats only show 14Gb

### DISCUSSION THREAD

**Discussion by oneline99** [blakeblackshear/frigate#14510] [General Support]
### Describe the problem you are having

I am new to Frigate. I am using USB stick as storage. which has 64Gb capacity. The recording and export was working fine until i restarted the device. The export files start to blink but live video was still streaming in. The storage usage was showing 140%  but recording can still be done. Can someone guide me how to restore this back to normal ? It seems like export function is now working after I restarted Frigate (not the device) but the storage is still showing 140%. 
![Screenshot 2024-10-22 223144](https://github.com/user-attachments/assets/d1185659-5ab0-4fe8-bd1d-9ad7917e6afd)

### Version

0.14

### What browser(s) are you using?

Google Chrome

### Frigate config file

```yaml
mqtt:
  enabled: false

auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false

tls:
  # Optional: Enable TLS for port 8971 (default: shown below)
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: auto detect)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-rpi-64-h264

cameras:
  test_rtsp: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.100.100.100
          roles:
            - detect
version: 0.14
camera_groups:
  Group_Test:
    order: 1
    icon: LuAirplay
    cameras: test_rtsp
```

### Relevant Frigate log output

```shell
where to capture?
```

### Relevant go2rtc log output

```shell
where to capture?
```

### FFprobe output from your camera

```shell
where to capture?
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    #devices:
    #  - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #  - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/newuser/frigate/config:/config
      - /mnt/sandisk:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      #- "8554:8554" # RTSP feeds
      #- "8555:8555/tcp" # WebRTC over tcp
      #- "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      homeassistant-network:
        ipv4_address: 10.5.0.5

  mqtt:
    container_name: mqtt
    hostname: mqtt
    image: "eclipse-mosquitto:latest"
    restart: unless-stopped
    volumes:
      - /home/newuser/mosquitto:/mosquitto:rw
    #ports:
    #  - "1883:1883"
    networks:
      homeassistant-network:
        ipv4_address: 10.5.0.7

networks:
  homeassistant-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-10-22 223144](https://github.com/user-attachments/assets/4c8b4af8-2d4a-4de0-b63e-d5fae79bff20)
![Screenshot 2024-10-22 214944](https://github.com/user-attachments/assets/1dd9bb7a-0028-4e08-b418-6c240a097e6d)
