### DISCUSSION TITLE
Cpu at 80%

### DISCUSSION THREAD

**Discussion by pressurejets** [blakeblackshear/frigate#14522] [General]
Please can someone help I have 3 camera reolink , Which is working and dropping all the time, all running on lan cables 
i have rtc version=1.9.2 
MY CPU IS AT 90%  thats like 30% per camera,, 
Questions: 
1, is this the right config settings for my camera.
2, what should the Frame Rate (FPS) on camera / config be set too
3. what should detect: be set to >> would it be Clear or Fluent of the camera setup

Please I'm so confused  as i can run video from RTC  using http://homeassistant.local:1984/stream.html?src=Back_Camera_frigate and working fine, but the frigate side of it not 

```
mqtt:
  host: XXXXXXXX
  port: XXXXXX
  user: XXXXXXX
  password: XXXXXXXX
  topic_prefix: frigate

database:
  path: /config/frigate.db


ffmpeg:
  hwaccel_args: preset-vaapi


go2rtc:
  streams:
    Back_Camera_frigate: 
    http://XXXXXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXXX
    Front_Camera_frigate: 
      http://XXXXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXXX
    Door_Camera_frigate: 
      http://XXXXXXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXXX


## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED

  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"


cameras:
  Back_Camera_frigate:
    ffmpeg:
      inputs:
        - path: 
            http://XXXXXX/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXXXXX
          input_args: preset-http-reolink
          roles:
            #- detect
            - record

    record:
      enabled: true
      retain:
        days: 10
        mode: all

    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10

  Front_Camera_frigate:
    ffmpeg:
      inputs:
        
        - path: 
            http://XXXXXXX/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXXXX
          input_args: preset-http-reolink
         
          roles:
            #- detect
            - record

    record:
      enabled: true
      events:
        retain:
          default: 10
          mode: all

    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10


  Door_Camera_frigate:
    ffmpeg:
      inputs:
 
        - path: 
            http://XXXXXX/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXXXX
            input_args: preset-http-reolink
   
          roles:
            #- detect
            - record

    record:
      enabled: true
      events:
        retain:
          default: 10
          mode: all

    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10

version: 0.14

```

my camera setting 

```
Stream
Clear
Resolution:
2560*1920
Note: May require device restart for change to take effect.

Frame Rate (FPS)
15
Max Bitrate (Kbps)
4096
Fluent
Resolution:
640*480
Note: May require device restart for change to take effect.

Frame Rate (FPS)
10
Max Bitrate (Kbps)
160
Default
```
