### DISCUSSION TITLE
stream not working in home assistant with frigate integration

### DISCUSSION THREAD

**Discussion by balajeek** [blakeblackshear/frigate#1454] [General]
My frigate docker setup and from the frigate web ui, i see all 3 cameras and when i click any one of them i can see it stream live.  which is great and thanks for the developers

I also have the hass integration and it shows all the entities exposed by frigate.  so form home assistant it shows all the latest snapshots, from media browser i see all the clips and can play them fine.

but from hass ui, if i use the entity exposed by frigate, for example one of the camera, it opens up streaming modal popup and its shows spinning bar, no video is streamed.

in home assistant i this log:

2021-07-31 14:31:02 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtmp://192.168.99.13/live/front

any idea why this happen?

![image](https://user-images.githubusercontent.com/19213088/127749600-c52f99aa-5209-428e-bdfd-f5e87e0a1c8b.png)

**Comment by blakeblackshear** [comment]
It really helps to provide the information requested in the template.

**Reply by balajeek** [reply]
I thought i was just opening up a discussion and not bug report which has template, when i open discussion its just an empty container to start.  Sure i would be happy to provide any details, please let me know.  thanks.

**Reply by balajeek** [reply]
would it be helpful if i post the docker-compose and config sections?

**Comment by shred86** [comment]
Post the camera: section of your config.yml ([example](https://blakeblackshear.github.io/frigate/configuration/cameras#example)). Obviously redact any username/passwords. Do you have the appropriate ffmpeg settings in your config file as well for an RTMP feed ([see here](https://blakeblackshear.github.io/frigate/configuration/cameras#rtmp-cameras)).

**Comment by balajeek** [comment]
Here is the camera section on one of the camera

```
mqtt:
  host: 192.168.1.3
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

database:
  path: /media/frigate/clips/frigate.db

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.13:8554/frontdoor
          roles:
            - detect
            - rtmp
            - record
    width: 1920
    height: 1080
    fps: 10
    objects:
      track:
        - person
        - animal
        - vehicle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: true
      retain:
        default: 7
        objects:
          person: 7
          animal: 2
          vehicle: 2
    record:
      enabled: true
      retain_days: 7
```
