### DISCUSSION TITLE
Best config combination to show a mainstream video on my low performance Fire HD Tablet?

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#14542] [Ask A Question]
I would like to show the live **mainstream** with audio (of my Reolink cams) with [frigate-card](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file) on my Fire HD Tablet. I **do not need** any 2 way audio, i just want to display the mainstream with audio. 

There are plenty of combinations i tried, some of them are working good, some bad, i am not sure if there is any other better option for my case. 

### 1. In Frigate Docu. suggested reolink go2rtc stream with http-flv + webrtc mode in frigate-card:

```yaml
go2rtc:
  webrtc:
    candidates:
      - 192.168.178.13:8555
      - stun:8555
  streams:
    reolink_doorbell:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.178.114/Preview_01_sub
    reolink_doorbell_sub:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
```

```yaml
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        stream: reolink_doorbell
        modes:
          - webrtc
```

Result: Does work on Browser or iPhone, but not on Fire-HD Tablet. [Here](https://github.com/AlexxIT/WebRTC/issues/459#issuecomment-1493069357) somebody says "_... because the primary (main) stream resolution was too high to be displayed consistently on the FireHD._". I do not know if that is really the case..

When i use the reolink_doorbell_sub in stream part of go2rtc config of the card, it is working.

### 2. The same frigate config from above + mse mode in frigate-card:

```yaml
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        stream: reolink_doorbell
        modes:
          - mse
```

Result: This results a choppy video on tablet (after some seconds the stream even stops), and it does not work on iPhones at all.

### 3. RTSP Stream in Frigate config + webrtc mode in frigate-card

```yaml
go2rtc:
  streams:
    doorbell_stream:
      - rtsp://admin:password@192.168.178.114/Preview_01_main
    e1_zoom_stream:
      - rtsp://admin:password@192.168.178.115/Preview_01_main
```

Result: On browser/iPhone just video without sound, on Fire HD does not work at all.

### 4. RTSP Stream in Frigate config + mse mode in frigate-card

```yaml
go2rtc:
  streams:
    doorbell_stream:
      - rtsp://admin:password@192.168.178.114/Preview_01_main
    e1_zoom_stream:
      - rtsp://admin:password@192.168.178.115/Preview_01_main
```

```yaml
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        stream: doorbell_stream
        modes:
          - mse
```

Result: This works best. I feel like the video loading needs at the beginning or while switching cams always 1-2 seconds more, but it works everywhere smooth, with audio, and with the high resolution stream.

Do you think this solution is my best bet?  I know there are plenty of others who have the exact same setup with reolink products and Fire Hd Tablets.

### I would also want to compare the option 4, with a scaled live stream + webrtc like this, but it does not work at all:

```yaml
go2rtc:
  webrtc:
    candidates:
      - 192.168.178.13:8555
      - stun:8555
  streams:
    reolink_doorbell:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.178.114/Preview_01_sub
    reolink_doorbell_sub:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    live:
      stream_name: reolink_doorbell
     # Optional: I just want to begin/try with a bad quality and increase the quality later, but this does not work at all
      height: 720 
      quality: 20
```

```yaml
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        stream: reolink_doorbell
        modes:
          - webrtc
```

Result: Same like the Option 1. As far as i understand from the frigate docs, my mainstream should be downscaled to 720x height and frigate card should use that with webrtc mode. Do I understand correctly? 
I somehow see the full resolution on iPhone and browser, and on Fire HD nothing.

Thanks for any help.
