### DISCUSSION TITLE
Issue after Frigate 14 upgrade - CPU 100%

### DISCUSSION THREAD

**Discussion by juampick** [blakeblackshear/frigate#14548] [General]
Hello! I've been using Frigate within Hassio for the last 2+ years. Before with Frigate 13 everything was working fine. I loved Frigate 14 but after upgrade, I have started to have issues and basically CPU goes to 100% and hangs frigate/hassio. The only solution is actually rebooting server. 
My setup is an Intel Nuc with i5 (8th generation) + 16gb ram DDR4 + ssd + intel coral for frigate + 8 cameras (almost all are Dahua). The installation type is over HassOS as an Addon.
I use go2rtc, detect with substream pretty slow res (640px - 5fps) and then record with full res (1080p or 2k). 

Everything runs fine, until many movements/motion is detected in any camera and then things starts to run pretty bad and hangs.

![image](https://github.com/user-attachments/assets/77958b94-eb39-4917-92b3-6a8a5c0b4eab)
<img width="947" alt="image" src="https://github.com/user-attachments/assets/fba99819-86de-4dc1-92bf-d046489901f3">

Frigate is the responsible for this, cpu gets stuck at 100%, Coral also has an average of less than 10 ms of inference speed (when everything is without movement), but when things are bad goes to 300-500 ms.

My config is the following: (I will keep it with 1 camera for simplicity only, but is the same with 8).

Things that I tried: changing from `hwaccel_args: preset-vaapi` to `hwaccel_args: preset-intel-qsv-h264` (same results).
```
mqtt:
  enabled: true
  host: <host>
  port: 1883
  user: <user>
  password: <pass>

ffmpeg:
 hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

##########################################################################
cameras:

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - cat 

version: 0.14
##########################################################################
go2rtc:
  log:
    exec: trace
  streams:
    front:
      - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
    front-sub:
      - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=1
# ##########################################################################

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  timestamp: true

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

objects:
  track:
    - car
    - person
##########################################################################
version: 0.14
```

Can anyone help me? I have been struggling for the last 2 weeks or more trying to solve this issue. 

Thanks ;)
