### DISCUSSION TITLE
[Bug]: Person Occupancy doesn't reset after Frigate restart with person detected status on

### DISCUSSION THREAD

**Discussion by miketyson666** [blakeblackshear/frigate#14547] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

If Frigate is restarted when the person occupancy sensor is "Detected", the value is not cleared after restart until it detect another person. Big issue when the camera is used into an alarm system because it activate immediately when armed.

### Steps to reproduce

1. let Frigate detect a person occupancy
2. when the status is still Detected, restart Frigate
3. After restart the Occupancy is still Detected, the person count to 1 and the all occupancy is clear
4. The Person Occupancy is cleared only after the camera detect a person again
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

model:
  path: plus://XXXXXXXX
mqtt:
  host: 192.168.3.90
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xx
  stats_interval: 60

cameras:
  fronte:
    enabled: true #fronte
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        #- path: rtsp://127.0.0.1:8554/fronte
        #  #input_args: preset-rtsp-restream
        #  roles:
        #    - detect
        - path: rtsp://admin:Elettra666$X@192.168.3.37:554//h264Preview_01_main
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1024
      height: 768
      fps: 8
    objects:
      track:
        - person
        - dog
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 8000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.55
          mask: 0.055,0,0.208,0.004,0.185,0.25,0.172,0.497,0.063,0.496,0.041,0.261
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2

    zones:
      vfronte:
        coordinates: 
          0.057,0,0.05,0.135,0.054,0.329,0.081,0.602,0.127,0.822,0.181,1,0.72,0.995,0.714,0.003
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 2
    motion:
      mask:
        - 0.25,0.687,0.252,0.611,0.316,0.597,0.355,0.574,0.41,0.568,0.458,0.596,0.559,0.721,0.616,0.784,0.63,0.803,0.68,0.71,0.688,0.666,0.66,0.614,0.598,0.572,0.624,0.352,0.588,0.349,0.456,0.382,0.381,0.287,0.362,0.216,0.323,0.168,0.228,0.096,0.226,0,1,0,1,1,0.401,1,0.37,0.903,0.299,0.79
        - 0.059,0,0.048,0.191,0.056,0.397,0.061,0.455,0.117,0.788,0.172,1,0,1,0.002,0.002
      threshold: 21
      contour_area: 7
      improve_contrast: 'true'

    review:
      detections:
        required_zones: vfronte
      alerts:
        required_zones: vfronte
  strada:
    enabled: true #strada
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        #- path: rtsp://127.0.0.1:8554/strada
          #input_args: preset-rtsp-restream
        #  roles:
        #    - detect
        - path: rtsp://admin:Elettra666$X@192.168.3.95:554//h264Preview_01_main
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1024
      height: 768
      fps: 8
    objects:
      track:
        - person
        - dog
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 8000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.54
      mask:
        - 0.437,0.996,0.447,0.864,0.477,0.745,0.505,0.738,0.527,0.896,0.538,0.996
        - 0.486,0.457,0.479,0.504,0.479,0.572,0.522,0.56,0.519,0.482
        - 0.57,0.153,0.54,0.233,0.5,0.328,0.526,0.386,0.586,0.299,0.611,0.199
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2

    zones:
      vstrada:
        coordinates: 0.255,0,0.256,1,0.666,1,0.681,0
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 2
    motion:
      mask:
        - 0,1,0.001,0.004,0.481,0,0.407,0.295,0.393,0.325,0.348,0.477,0.33,0.629,0.341,0.641,0.314,0.757,0.278,1
        - 0.552,1,0.472,1,0.462,0.815,0.458,0.779,0.472,0.711,0.44,0.654,0.47,0.579,0.479,0.538,0.477,0.442,0.511,0.387,0.511,0.336,0.534,0.269,0.551,0.232,0.566,0.183,0.598,0.087,0.472,0.044,0.481,0,0.573,0,0.698,0,1,0.001,1,1
      threshold: 17
      contour_area: 7
      improve_contrast: 'true'

    review:
      detections:
        required_zones: vstrada
      alerts:
        required_zones: vstrada
  retro0:
    enabled: true #retro0
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        #- path: rtsp://127.0.0.1:8554/retro0
          #input_args: preset-rtsp-restream
        #  roles:
        #    - detect
        - path: rtsp://admin:Elettra666$X@192.168.3.96:554//h264Preview_01_main
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1024
      height: 768
      fps: 8
    objects:
      track:
        - person
        - dog
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 6000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.55
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2

    zones:
      vretro0:
        coordinates: 
          0.607,1,0.871,1,0.906,0.869,0.841,0.749,0.88,0.597,0.914,0.374,0.917,0.11,0.916,0,0.842,0,0.841,0.076,0.831,0.268,0.787,0.506,0.724,0.724,0.652,0.901
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 2
    motion:
      mask:
        - 0,0,0.811,0,0.806,0.084,0.779,0.236,0.758,0.388,0.737,0.54,0.696,0.679,0.651,0.843,0.593,1,0,1
        - 0.787,1,0.833,0.792,0.871,0.618,0.895,0.418,0.912,0.203,0.914,0.038,0.914,0,0.994,0,1,0,0.999,1
      threshold: 21
      contour_area: 9
      improve_contrast: 'true'

    review:
      alerts:
        required_zones: vretro0
      detections:
        required_zones: vretro0
  patio0:
    enabled: true #patio0
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        #- path: rtsp://127.0.0.1:8554/patio0
          #input_args: preset-rtsp-restream
        #  roles:
        #    - detect
        - path: rtsp://admin:Elettra666$X@192.168.3.35:554//h264Preview_01_main
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 896
      height: 512
      fps: 8
    objects:
      track:
        - person
        - dog
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 6000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          #min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          #threshold: 0.55

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
  casa11:
    enabled: true #casa11
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:Elettra666$X@192.168.3.97:554//h264Preview_01_main
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 896
      height: 506
      fps: 5
    objects:
      track:
        - person
        - dog


      mask:
        - 0.307,0.002,0.318,0.125,0.273,0.167,0.249,0.202,0.258,0.232,0.272,0.251,0.314,0.258,0.354,0.255,0.382,0.23,0.387,0.197,0.357,0.156,0.339,0.156,0.333,0.105,0.339,0.04,0.344,0.004
        - 0.018,0.221,0.093,0.583,0.129,0.805,0.157,0.999,0.001,0.998,0,0.23
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2




    zones:
      vcasa11:
        coordinates: 
          0.105,0.63,0.133,0.819,0.128,0.882,0.16,0.995,0.614,0.991,0.885,0.455,0.59,0.17,0.583,0.071,0.522,0.01,0.518,0.003,0.29,0.001,0.002,0.003,0.016,0.212
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: vcasa11
      detections:
        required_zones: vcasa11
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.494,0.003,0.496,0.045,0.65,0.047,0.651,0.001
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 4
      mode: active_objects
      objects:
        person: 6

version: 0.14
camera_groups:
  Esterno:
    order: 1
    icon: LuActivitySquare
    cameras:
      - birdseye
      - frigate_front_home_cam
      - frigate_retro_home_cam
      - frigate_strada_home_cam
```

### docker-compose file or Docker CLI command

```yaml
non relevant
```

### Relevant Frigate log output

```shell
not relevant
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

reolink CX410

### Screenshots of the Frigate UI's System metrics pages

not relevant
