### DISCUSSION TITLE
Just recording any motion without detecting any object

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#14554] [Ask A Question] [answered]
Is it possible just to record any motion (with audio) without detecting any object?

Recently i wanted to change the config for my daughter's room, to only record any motion with audio. **I do not have to distinguish the type of object in that room**. But this config does not record anything:

```yaml
mqtt:
  host: 192.168.178.6
  user: xxx
  password: xxx

audio:
  enabled: true

record:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb 

go2rtc:
  streams:
    ...  # streams for other cameras 
    ...
    reolink_e1_zoom:
      - ffmpeg:http://192.168.178.115/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.178.115/Preview_01_sub
    reolink_e1_zoom_sub:
      - ffmpeg:http://192.168.178.115/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password  

cameras:
  ...  # other cameras 
  ...
  my_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_e1_zoom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_e1_zoom_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect    
    detect:
      enabled: false
    live:
      stream_name: reolink_e1_zoom  
version: 0.14
 
```

Any help appreciated.
