### DISCUSSION TITLE
[Config Support]: go2rtc does not provide AAC transcoding ?

### DISCUSSION THREAD

**Discussion by bonjour81** [blakeblackshear/frigate#14552] [Config Support] [answered]
### Describe the problem you are having

I have set my config to get AAC transcoding, but vlc says it's PCM MU LAW ?
did I do something wrong ? 

I just paste go2rtc link in VLC :
rtsp://mydockermachineIP:8554/indoor1?video&audio 
or
rtsp://mydockermachineIP:8554/indoor1_sub?video&audio

then in VLC : tool / codec information :  PCM MU-LAW (mlaw)  8kHz, 16bits.

sub question : it is a foscam R5 camera: specs says "PCM/AAC" audio, but I was not able to figure out how to get AAC directly from cam with rtsp.

### Version

0.14

### Frigate config file

```yaml
go2rtc:
  streams:
    indoor1:
      - rtsp://fred:mypassword@192.168.5.81:88/videoMain
      - "ffmpeg:indoor1#audio=aac"
    indoor1_sub:
      - rtsp://fred:mypassword@192.168.5.81:88/videoSub
      - "ffmpeg:indoor1_sub#audio=aac"


....


indoor1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor1?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/indoor1_sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant Frigate log output

```shell
I didn't find any relevant error to report from logs.
```

### Relevant go2rtc log output

```shell
I didn't find any relevant error to report from logs.
```

### Operating system

Debian

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
docker run -d \
--name frigate \
--net mynetwork \
--restart=unless-stopped \
--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
--device /dev/bus/usb:/dev/bus/usb \
--device /dev/dri/renderD128 \
--device /dev/apex_0:/dev/apex_0 \
--shm-size=512m \
-v frigate:/media/frigate \
-v frigate_conf:/config/  \
-v frigate_db:/database/  \
-v /etc/localtime:/etc/localtime:ro \
-e FRIGATE_RTSP_PASSWORD='password' \
-e PLUS_API_KEY='xxxx' \
-p 8083:5000 \
-p 8971:8971 \
-p 8554:8554 \
-p 8555:8555/tcp \
-p 8555:8555/udp \
--cap-add=PERFMON \
ghcr.io/blakeblackshear/frigate:stable
```

### Object Detector

Coral
