### DISCUSSION TITLE
[Detector Support]: OpenVino model files missing, can't save config

### DISCUSSION THREAD

**Discussion by partytimeexcellent** [blakeblackshear/frigate#14551] [Detector Support]
### Describe the problem you are having

With a fresh install via the Proxmox LXC TTeck helper script, I cannot save the config file with the OpenVino detector and default model enabled. I get the following error:

```
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
  File &#34;/opt/frigate/frigate/detectors/detector_config.py&#34;, line 74, in __init__
    **load_labels(config.get(&#34;labelmap_path&#34;, &#34;/labelmap.txt&#34;)),
  File &#34;/opt/frigate/frigate/util/builtin.py&#34;, line 155, in load_labels
    with open(path, &#34;r&#34;, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: &#39;/openvino-model/coco_91cl_bkgr.txt&#39;
```

The GPU (Intel Pentium G5905 with Intel HD Graphics 610) is detected and working in the LXC, confirmed via vainfo. I have the exact same install on another machine (but with i5 10500 CPU) and it works without issue. I went digging around in the file system and discovered that on my working install, I have the following directory present: `/openvino-model`, while on the non-working install, that entire directory is missing, in addition the directory `/opt/frigate/models/` is empty.

Something is preventing these necessary files from being installed. Any idea why? 

### Version

14.1

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  test:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml

cameras:
  test:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: /media/frigate/person-bicycle-car-detection.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
#      height: 1080
#      width: 1920
      fps: 5


version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
#<div align='center'><a href='https%3A//Helper-Scripts.com' target='_blank' rel='noopener noreferrer'><img src='https%3A//raw.githubusercontent.com/tteck/Proxmox/main/misc/images/logo-81x112.png'/></a>
#
#  # Frigate LXC
#
#  <a href='https%3A//ko-fi.com/proxmoxhelperscripts'><img src='https%3A//img.shields.io/badge/&#x2615;-Buy me a coffee-blue' /></a>
#  </div>
arch: amd64
cores: 2
features: nesting=1
hostname: frigate
memory: 1024
net0: name=eth0,bridge=vmbr0,hwaddr=BC:24:11:E5:0E:97,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: SSD-500:102/vm-102-disk-0.raw,size=20G
swap: 512
tags: proxmox-helper-scripts
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyUSB1       dev/ttyUSB1       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
```

### Relevant Frigate log output

```shell
Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
  File &#34;/opt/frigate/frigate/detectors/detector_config.py&#34;, line 74, in __init__
    **load_labels(config.get(&#34;labelmap_path&#34;, &#34;/labelmap.txt&#34;)),
  File &#34;/opt/frigate/frigate/util/builtin.py&#34;, line 155, in load_labels
    with open(path, &#34;r&#34;, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: &#39;/openvino-model/coco_91cl_bkgr.txt&#39;
```

### Install method

Proxmox via TTeck Script

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

<img width="986" alt="Screenshot 2024-10-23 at 9 59 14 PM" src="https://github.com/user-attachments/assets/0f6edd5c-bd33-449d-bfbb-a43648d6501a">
