### DISCUSSION TITLE
[Camera Support]: Amcrest IP4M-1098EW AI

### DISCUSSION THREAD

**Discussion by ha88rgc** [blakeblackshear/frigate#14559] [Camera Support]
### Describe the problem you are having

Hello,

I'm having an ONVIF setup issue with the Amcrest IP4M-1098EW AI PTZ camera. In talking to Amcrest support I was told that ONVIF is supported and available on port 80. The guy sent me a screen shot for a valid Blue Iris config, on which it is working.

In the Frigate logs however, I get the following error `Onvif is not setup for 92_ml_driveway_cam`. Streaming and recording works fine. Please see my config below the screen shot. What am I doing wrong here? Should be working in Frigate if it's working in Blue Iris, right?

![image](https://github.com/user-attachments/assets/61c9a0d1-fa3c-4d83-aa30-814d6c75f5aa)

 

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Brave v1.69.168

### Frigate config file

```yaml
92_ml_driveway_cam:
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        #High res
        - path: 
            rtsp://streamer:REDACTED@192.168.5.XX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        #Low res
        - path: 
            rtsp://streamer:REDACTED@192.168.5.XX:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - audio
    detect:
      width: 1280
      height: 720
      fps: 15
    audio:
      enabled: true
      min_volume: 200
      listen:
        - smoke_detector
        - glass
        - siren
        - shatter
      filters:
        glass:
          threshold: 0.7
        smoke_detector:
          threshold: 0.6
        siren:
          threshold: 0.6
        shatter:
          threshold: 0.7
    record:
      enabled: true
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
    birdseye:
      order: 10
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.5.XX
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: streamer
      # Optional: password for login.
      password: REDACTED
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: false
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.3
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        # required_zones:
        #   - zone_name
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
        # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
        # movement_weights: []
```

### Relevant Frigate log output

```shell
Onvif is not setup for 92_ml_driveway_cam
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Amcrest IP4M-1098EW AI

### Screenshots of the Frigate UI's System metrics pages

NA
