### DISCUSSION TITLE
using genai to update sub_label for USPS, UPS, fedex, amazon with home assistant

### DISCUSSION THREAD

**Discussion by jameslivulpi** [blakeblackshear/frigate#14567] [Show and tell]
quick and dirty example of using genai and listening to the `event_update` topic to add sub_labels to events based on courier, can be updated for various things. I know it should really be done within model but would like to see others automations, ideas etc they use with genai plugin:

```yaml
alias: courier sub label update 
description: ""
triggers:
  - alias: topic published to /reviews
    topic: frigate/event_update
    id: frigate-event
    value_template: "{{ value_json }}"
    variables:
      description: "{{ trigger.payload_json['description'] | lower }}"
      event_id: "{{ trigger.payload_json['id'] }}"
    trigger: mqtt
actions:
  - alias: Parse data
    variables:
      courier: |
        {%- if 'ups' in description -%}
          UPS
        {% elif 'fedex' in description %}
          FEDEX
        {% elif 'usps' in description %}
          USPS
        {% elif 'amazon' in description %}
          amazon
        {% endif -%}
  - if:
      - condition: template
        value_template: "{{ courier | length > 0 }}"
    then:
      - data_template:
          event_id: "{{ event_id }}"
          sub_label: "{{ courier }}"
        action: rest_command.frigate_sub_label
mode: parallel
trace:
  stored_traces: 10
max: 10
```

then using rest_command yaml config:
```yaml
frigate_sub_label:
  url: "http://..../api/events/{{event_id}}/sub_label"
  method: POST
  headers:
    accept: "application/json"
  payload: '{"subLabel": "{{ sub_label }}", "subLabelScore": 1 }'
  content_type:  'application/json'
```
