### DISCUSSION TITLE
Frigate detects motion at night wenn footage is completely black

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#14565] [Ask A Question] [answered]
Can please somebody explain me this? (I have masked out the timestamp)

https://github.com/user-attachments/assets/7eed05d1-803f-432a-972b-647e37d48b14

Motion Tuner is also at its default (30, 10)
This is the relevant config part, so i am trying only to record motions, without object detection.

```
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 60
          mode: motion
    detect:
      enabled: false
```
