### DISCUSSION TITLE
Record config with vs. without events section

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#14573] [Ask A Question] [answered]
I am using currently this config for recording just the motion parts (I do not have any detection active):

```yaml
record:
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 60
      mode: motion
```

I find this part of config very confusing.. I understand that there are 2 parts (retain and events/retain) in case you want to distinguish e.g. the last 3 days from the older footage. But in my case, where i just want to keep all the motion parts always, it is confusing to have both.

I played with the config a bit, and i am just curious..

This config seems also working:

```yaml
record:
  retain:
    days: 60
    mode: motion
```

Is there any difference between both?

And when "no", why is not stated this case more clear in documentation instead of this:

<img width="615" alt="Bildschirmfoto 2024-10-25 um 09 31 19" src="https://github.com/user-attachments/assets/8d16e5f3-0112-448b-aea4-9ab985617c66">
