### DISCUSSION TITLE
genai timeout ollama

### DISCUSSION THREAD

**Discussion by divemasterjm** [blakeblackshear/frigate#14572] [General Support]
### Describe the problem you are having

genai using ollama takes 2-3 minutes (i don't have gpu), is possible to define a time out? i use it in another programs and it works with the timeout.

### Version

0.15

### Frigate config file

```yaml
genai:
  enabled: true
  provider: ollama
  base_url: http://192.168.8.38:11434
  model: llava
```

### Relevant Frigate log output

```shell
no log error
```

### Relevant go2rtc log output

```shell
no errors
```

### FFprobe output from your camera

```shell
it not related to a camera
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
not relevant
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

dahua
