### DISCUSSION TITLE
[Config Support]: Moving vehicle still considered stationary.

### DISCUSSION THREAD

**Discussion by ibrewster** [blakeblackshear/frigate#14598] [Config Support]
### Describe the problem you are having

When a car is parked in my driveway, it is - correctly - marked as stationary, as indicated by the white outline in the debug view. However, when said car starts to move again, it *remains* marked as stationary, generally until it reaches the road and starts moving out-of-frame. I made a screen recording of a small example of this, here: https://drive.google.com/file/d/1-2CDvldS72QDZNAabWebWEGiNc6OQHHp/view?usp=sharing

How might I be able to get the system to "release" the object from stationary status more readily? There is clearly some tweaking needed, as I don't want small changes to trigger movement.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt.server.name
  user: mqttuser
  password: mqttpassword

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    drivecam:
      - rtsp://my.camera.url/video/path
  webrtc:
    canidates:
      - my.server.ip:8555
      - stun:8555

snapshots:
  enabled: true

cameras:
  drivecam: 
    enabled: true
    snapshots:
      enabled: true
      quality: 80
      required_zones:
        - Driveway
        - Porch
        - Yard
    mqtt:
      required_zones:
        - Driveway
        - Porch
        - Yard
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/drivecam
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - audio
            - detect
    record:
      enabled: true
    detect:
      enabled: true
      fps: 5
    zones:
      Driveway:
        coordinates: 
          0.002,0.167,0.091,0.17,0.106,0.158,0.36,0.165,0.863,0.898,0.792,1,0,1,0,0.885,0.2,0.882,0.166,0.519,0.021,0.473
        loitering_time: 0
        inertia: 3
      Porch:
        coordinates: 0.612,0.527,0.864,0.396,1,0.542,1,0.636,0.951,0.802,0.863,0.896
        loitering_time: 0
        inertia: 3
      Yard:
        coordinates: 0.612,0.523,0.361,0.164,0.689,0.197,0.865,0.396
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - horse
          - person
    motion:
      mask: 0.763,0.04,0.76,0.002,0.999,0,0.999,0.04
      threshold: 35
      contour_area: 15
      improve_contrast: 'true'
    review:
      alerts:
        labels:
          - car
          - person
          - cat
          - dog
          - horse
        required_zones:
          - Driveway
          - Porch
          - Yard
      detections:
        required_zones:
          - Driveway
          - Porch
          - Yard
model:
  path: plus://<model_id>
detectors:
  coral:
    type: edgetpu
    device: pci
objects:
  track:
    - person
    - car
    - cat
    - dog
    - horse
  filters:
    person:
      min_score: 0.72
      threshold: 0.75
    car:
      min_score: 0.75
      threshold: 0.85
    cat:
      min_score: 0.70
      threshold: 0.80
    dog:
      min_score: 0.70
      threshold: 0.80
    horse:
      min_score: 0.3
      threshold: 0.5
version: 0.14
```

### Relevant Frigate log output

```shell
No logs from the timeframe in question.
```

### Relevant go2rtc log output

```shell
Not relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Shouldn't be relevant, but let me know if I am wrong.
```

### Object Detector

Coral
