### DISCUSSION TITLE
Frigate Events in GUI - How to recreate from MQTT messages?

### DISCUSSION THREAD

**Discussion by YogoGit** [blakeblackshear/frigate#14595] [Ask A Question] [answered]
The GUI generates events as configured by the user as expected.  However, when using the MQTT trigger as done in the Blueprint in Home Assistant (https://github.com/SgtBatten/HA_blueprints/) or using the example blueprint @NickM-27 provided (https://github.com/blakeblackshear/frigate/discussions/2898), the notifications don't match up with the same set of events the GUI generates.

In particular, I would like all of my notifications to have both a snapshot and a clip (which is included in the MQTT events), but in both cases, many times I've received 'new' events but no clip/snapshot was included, and in other situations, attempting to only consider events with clips/snapshots filtered out events that showed up in the GUI.

I looked through the code, and it appears that the snapshot is generated/written when the final (end) event is generated, which in some cases may take many minutes.  However, that hasn't been my experience in the GUI, so I'm missing something.

object_processing.py
```
def end(camera, obj: TrackedObject, current_frame_time):
    # populate has_snapshot
    obj.has_snapshot = self.should_save_snapshot(camera, obj)
    obj.has_clip = self.should_retain_recording(camera, obj)

    # write the snapshot to disk
    if obj.has_snapshot:
        snapshot_config: SnapshotsConfig = self.config.cameras[camera].snapshots
        jpg_bytes = obj.get_jpg_bytes(
```

Finally, only some of my cameras (externally facing) use zones, but in a few others (internal), no zones are necessary, but I'd prefer not to have multiple triggers as they all generate notifications the same way, so I'm trying to avoid the use of zones in my triggers to determine is something should be notified.  The frigate configuration (currently) limits the GUI generated events to the proper zones correctly, and it seems that I shouldn't have to duplicate that same logic in my MQTT automation triggers.

Here's is a snapshot of my current (misbehaving) automation trigger.  I know this is incorrect, but I want to make sure that any notifications I send contain the snapshot/clip, as otherwise they are not very useful.

```yaml
automation:
  - alias: frigate_camera_notification
    id: frigate_camera_notification
    mode: queued
    # only trigger on 'new' events
    trigger:
      - platform: mqtt
        topic: frigate/events
        payload: new
        value_template: "{{ value_json['type']}}"
        variables:
          cooldown: 30
          camera: "{{ trigger.payload_json['after']['camera'] }}"
          has_clip: "{{ trigger.payload_json['after']['has_clip'] }}"
          has_snapshot: "{{ trigger.payload_json['after']['has_snapshot'] }}"
          id: "{{ trigger.payload_json['after']['id'] }}"
          label: "{{ trigger.payload_json['after']['label'] }}"
    # Conditions filter out objects / detections that are not of interest
    condition:
      - condition: state
        entity_id: input_boolean.alert_enabled
        state: "on"
      # Don't keep alerting for this automation over and over
      - condition: template
        value_template: >-
          {{ not this.attributes.last_triggered or (now() - this.attributes.last_triggered).seconds > cooldown }}
      # This ensures that we have a snapshot/clip, indicating a valid event
      - condition: template
        value_template: >-
          {{ has_clip and has_snapshot }}
    action:
      - service: script.turn_on
        target:
          entity_id: script.alert_all_frigate
...
```

The alert script is passed in the id and label so it can create an appropriate notification (both email and mobile), and this occasionally generates proper events.  However, many (valid) events are skipped, as they don't have a clip when the 'new' event is generated.

I do realize my cooldown logic could possible cause new events to get filtered out (I could have multiple independent events that happen very quickly across multiple cameras), but in my case, I'm (not) generating notifications across events that span many 10s of minutes or more, but yet I'm seeing multiple events in the GUI.

Rather than re-invent the wheel, I'd like to mirror the same logic for notifications as the GUI uses to determine valid events.

(Note, I'm still using version 0.13, but as I understand, the MQTT streams are backwards compatible with newer versions, so whatever solution should be portable across all versions.)

I've considered using a different trigger logic based on the existence of snapshots, but based on my (very quick) analysis of the code, that seems like it might lead to missed notifications IFF the clips are only generated at the end.  (Which doesn't seem to be what happens in the GUI, as I've seen 'in-progress' event images shown on the screen.)

```
automation:
  - alias: frigate_camera_notification
    id: frigate_camera_notification
    mode: queued
    # only trigger on 'new' events
    trigger:
      - platform: mqtt
        topic: frigate/events
        variables:
          cooldown: 30
          camera: "{{ trigger.payload_json['after']['camera'] }}"
          before_clip: "{{ trigger.payload_json['before']['has_clip'] }}"
          after_clip: "{{ trigger.payload_json['after']['has_clip'] }}"
          before_snapshot: "{{ trigger.payload_json['before']['has_snapshot'] }}"
          after_snapshot: "{{ trigger.payload_json['after']['has_snapshot'] }}"
          id: "{{ trigger.payload_json['after']['id'] }}"
          label: "{{ trigger.payload_json['after']['label'] }}"
    # Conditions filter out objects / detections that are not of interest
    condition:
      # This ensures that we have a snapshot/clip, indicating a valid event
      - condition: template
         value_template: >-
           {{ not before_clip and not before_snapshot and after_clip and after_snapshot }}
      - condition: state
        entity_id: input_boolean.alert_enabled
        state: "on"
      # Don't keep alerting for this automation over and over
      - condition: template
        value_template: >-
          {{ not this.attributes.last_triggered or (now() - this.attributes.last_triggered).seconds > cooldown }}
     action:
...
```

Thanks in advance!

Nate
