### DISCUSSION TITLE
[Detector Support]: Wrong recognition of humans

### DISCUSSION THREAD

**Discussion by comfuzio** [blakeblackshear/frigate#14601] [Detector Support]
### Describe the problem you are having

Thank you guys for frigate, it is amazing! But I am facing some issues which I need your help!
None of what I am writing bellow is meant as criticism to the project, obviously I have something wrong somewhere in my config.

My frigate installation in HaOS recognizes my motorcycle, "air" and "nothing" as humans but doesn't recognize real humans.
Also it fails to detect my motorcycle entirely.
Recently I got a new motorcycle (shown in the pics bellow) and I am trying to setup alerts if people go near the door of my yard or if it detects people near my motorcycle.
I am getting every now and then alerts that it detected people in the regions I have marked, I look on the notification only to see nothing and noone!
If I spend time looking at the frigate's camera output, I see it does some squares on literally nothing and marks them as person with 95% positivity.
Also when I go near my motorcycle, no alert whatsoever. I believe I am a person, or human being, at least I pass the captcha which I believe is what separates humans from robots.
In the config file I have it also to look for motorcycles, I would like to know when a delivery comes for example, so far it haven't detected a single one! 
I have frigate+ and I got a model code which I have in my config. I am trying to "train" it that my motorcycle is not a person which frigate thinks it is with 90+% positivity for some reason.
In frigate+ page it doesn't have the ability to mark my motorcycle as...a motorcycle at all, which is very odd.
The camera is clean and the image quality I believe is good for a 2k resolution camera.
I will post a few pictures of my area that it monitors, it has my motorcycle and in the last one it is my cat which is also recognized as a person.

So my goal is to monitor for people going to my door and into my yard near my moto. I would like to get alerts if indeed there is a human there, not thin air.

Any help is appreciated!
![image](https://github.com/user-attachments/assets/bd987283-4053-4c76-9779-59659d6f5ca5)

![image](https://github.com/user-attachments/assets/7eb515cf-77ac-4fe5-8d79-56a3fd280111)
![image](https://github.com/user-attachments/assets/3222677c-e550-42f9-b631-3f7d0da0740e)

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  host: "host"
  user: "user"
  password: "pass"

cameras:
  entrance_camera:
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: 
            rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorbike
    - laptop
    - keyboard
    - mouse
    - tv

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
        dog: 1
        cat: 1
        car: 1
        bird: 1
        tv: 1

birdseye:
  enabled: true
  quality: 8
  mode: continuous

go2rtc:
  streams:
    entrance_camera:
      - rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0

model:
  path: plus://your-plus-id
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
no docker-compose
```

### Relevant Frigate log output

```shell
2024-10-26 06:00:20.084391880  [INFO] Preparing Frigate...
2024-10-26 06:00:20.153104471  [INFO] Starting Frigate...
2024-10-26 06:00:22.091708861  [2024-10-26 09:00:22] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-26 06:00:22.094251852  [2024-10-26 09:00:22] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-10-26 06:00:22.094312024  [2024-10-26 09:00:22] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-26 06:00:22.104486313  [2024-10-26 09:00:22] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-26 06:00:22.127853574  [2024-10-26 09:00:22] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2024-10-26 06:00:22.142686299  [2024-10-26 09:00:22] peewee_migrate.logs            INFO    : Starting migrations
2024-10-26 06:00:22.143238408  [2024-10-26 09:00:22] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-26 06:00:22.161455297  [2024-10-26 09:00:22] frigate.app                    INFO    : Recording process started: 357
2024-10-26 06:00:22.166789846  [2024-10-26 09:00:22] frigate.app                    INFO    : Recording process started: 363
2024-10-26 06:00:22.167084618  [2024-10-26 09:00:22] frigate.app                    INFO    : go2rtc process pid: 95
2024-10-26 06:00:22.185653306  [2024-10-26 09:00:22] frigate.app                    INFO    : Output process started: 387
2024-10-26 06:00:22.186736792  [2024-10-26 09:00:22] detector.coral1                INFO    : Starting detection process: 386
2024-10-26 06:00:22.239912387  [2024-10-26 09:00:22] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-10-26 06:00:22.242612157  [2024-10-26 09:00:22] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-10-26 06:00:23.743446286  [2024-10-26 09:00:23] frigate.app                    INFO    : Camera processor started for entrance_camera: 429
2024-10-26 06:00:23.751480035  [2024-10-26 09:00:23] frigate.app                    INFO    : Capture process started for entrance_camera: 436
```

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/87935f80-c2aa-4af5-b3c1-b22ab0596026)
![image](https://github.com/user-attachments/assets/1280279f-b864-4824-bcc6-84906a8e4606)

### Any other information that may be helpful

The system is a ASRock Deskmeet B660 with an intel i3 13100 and coral AI TPU. It runs proxmox (latest) as host OS with HaOS vm (from tteck's site), it has pci-e passthrough for the TPU.

**Comment by NickM-27** [comment]
You should start by adjusting your config for the Frigate+ model https://docs.frigate.video/plus/first_model#step-4-adjust-your-object-filters-for-higher-scores

**Reply by comfuzio** [reply]
I will try this but the part I am bothered is that had 90+% positivity for basically nothing, so I will still be getting those false positives.
Also why does it fail to detect my motorcycle?

**Reply by NickM-27** [reply]
> Also why does it fail to detect my motorcycle?

Because motorcycle is not currently a supported label like it says in the Frigate+ docs. Though it will be soon.

**Reply by NickM-27** [reply]
Your cat bounding box is also looking too large, be sure that the box is accurately around the object

**Reply by comfuzio** [reply]
Today I was out cleaning my moto, not once I got an alert that a person was detected. 5 minutes after I was done and in my home, I got an alert that a person was detected. Of course it was thin air again.
What have I done wrong with my config?
I am using frigate+ 2024.2 model

**Reply by NickM-27** [reply]
what is your current config? have you tried walking around while looking at the debug live view? that would be good to see

**Reply by comfuzio** [reply]
I was walking around the moto to clean it, facing the camera and having the camera on my back, well actually the camera got a 360 of me xD
I was also moving around the front area of the moto, if you see the pic in the starting post.
My current config:
```
mqtt:
  host: hotst-emqx
  user: user
  password: 'password'

cameras:
  entrance_camera:
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: 
            rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 576
      fps: 5

# Optional: Database configuration
    zones:
      porta:
        coordinates: 0.255,0.208,0.367,0.158,0.397,0.406,0.294,0.462
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - motorbike
          - person
      motorcycle:
        coordinates: 
          0.762,0.127,0.997,0.28,0.839,0.998,0.12,0.904,0.121,0.623,0.302,0.504,0.253,0.217,0.756,0.074
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - motorbike
    review:
      alerts:
        required_zones:
          - porta
          - motorcycle
    motion:
      mask: 0.555,0.035,0.951,0.036,0.953,0.076,0.554,0.077
    objects:
      filters:
        motorbike:
          mask:
            - 0.662,0.248,0.793,0.204,0.857,0.3,0.718,0.442,0.665,0.403
            - 0.152,0.214,0.555,0.026,0.554,0.096,0.173,0.257
            - 0.226,0.176,0.315,0.551,0.141,0.685,0.142,0.878,0.424,0.677,0.891,0.276,0.732,0.091,0.375,0.186,0.366,0.152,0.333,0.13
database:
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorbike
    - laptop
    - keyboard
    - mouse
    - tv

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
        dog: 1
        cat: 1
        car: 1
        bird: 1
        tv: 1

birdseye:
  enabled: true
  quality: 8
  mode: continuous

go2rtc:
  streams:
    entrance_camera:
      - rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0

model:
  path: plus://2024.2
version: 0.14
```
