### DISCUSSION TITLE
[Support]: frigate keep restarting - Same as #12896

### DISCUSSION THREAD

**Discussion by tootai** [blakeblackshear/frigate#14606] [General Support] [answered]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/12896 ###

I have similar problem: frigate restart as soon as started

rtmp is removed, I also add database path in case of, no changes. Than I removed my config.yml file and frigate is starting. I reinstalled my config file and removed one by one each chapter including cameras one. Each time there is no cameras chapter, frigate start and complain about missing cameras.

Here is the point: as soon as I add this chapter, ***even using camera sample from default config file*** frigate keeps restarting!

Thanks for any hint.
Daniel

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: true   
  host: localhost    
  port: 1883                          
  topic_prefix: frigate
  user: mqttuser
  password: mqttpwd
  #user: '{FRIGATE_MQTT_USER}'
  #password: '{FRIGATE_MQTT_PASSWORD}'
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi
cameras:
  name_of_your_camera: # <------ Name the camera
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
version: 0.14
```

### Relevant Frigate log output

```shell
frigate  | 2024-10-26 12:49:34.189890732  [2024-10-26 12:49:34] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
frigate  | 2024-10-26 12:49:34.189991915  [2024-10-26 12:49:34] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-10-26 12:49:34.243038130  [2024-10-26 12:49:34] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-10-26 12:49:34.315840751  [2024-10-26 12:49:34] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-10-26 12:49:34.316572343  [2024-10-26 12:49:34] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-10-26 12:49:34.321092588  [2024-10-26 12:49:34] frigate.app                    INFO    : Recording process started: 340
frigate  | 2024-10-26 12:49:34.325835089  [2024-10-26 12:49:34] frigate.app                    INFO    : Recording process started: 342
frigate  | 2024-10-26 12:49:34.329820352  [2024-10-26 12:49:34] frigate.app                    INFO    : go2rtc process pid: 113
frigate  | 2024-10-26 12:49:34.364811606  [2024-10-26 12:49:34] detector.coral                 INFO    : Starting detection process: 369
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2024-10-26 12:49:34.397328131  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | 2024-10-26 12:49:34.397362752  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully
```

### Relevant go2rtc log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:                                                                                                                                                    
    image: "ghcr.io/blakeblackshear/frigate:stable"
    privileged: true                                                           
    cap_add:                  
      - CAP_PERFMON
    container_name: frigate
    shm_size: "512MB"
    network_mode: host                                                         
    environment:                                                               
      CAMERA_USER: user
      CAMERA_PWD: pwd  
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /opt/homeassistant/frigate:/config
      - /media/local/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    restart: unless-stopped
    ports:
      - 554:554
      - 1935:1935
      - 5000:5000
      - 8554:8554
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

NA
