### DISCUSSION TITLE
Will not recognize dogs

### DISCUSSION THREAD

**Discussion by Clark2** [blakeblackshear/frigate#14609] [Config Support]
### Describe the problem you are having

I've done a lot of reading on this and I can't tell what I'm missing.  I've included a couple pictures of what I think should have been easily identified as a dog but it didn't pick it up. It does a great job with people, just not dogs.  I've played around with the threshold, contrast and contour but then don't seem to make a difference (it would be a lot easier if there were more dogs walking around).  Can you see anything in the config file that would cause this problem (it's the driveway camera).
<img width="533" alt="Dog1" src="https://github.com/user-attachments/assets/93b90feb-40ff-46a7-b535-80d70e01aadc">
<img width="537" alt="Dog2" src="https://github.com/user-attachments/assets/374b28e1-d410-4f84-8a8e-04a7c6aa5f88">

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: me
  password: pass

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -an

go2rtc:
  streams:
    Front_Door:
      - ffmpeg:https://192.168.68.200/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      # - rtsp://192.168.68.200/Preview_01_sub
    Front_Door_sub:
      - ffmpeg:https://192.168.68.200/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    Driveway:
      - rtsp://admin:password@192.168.68.201:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:password@192.168.68.201:554/cam/realmonitor?channel=1&subtype=1
    Pool:
      - rtsp://admin:password@192.168.68.202:554/cam/realmonitor?channel=1&subtype=0
    Pool_sub:
      - rtsp://admin:password@192.168.68.202:554/cam/realmonitor?channel=1&subtype=1
    Back:
      - rtsp://admin:password@192.168.68.203:554/cam/realmonitor?channel=1&subtype=0
    Back_sub:
      - rtsp://admin:password@192.168.68.203:554/cam/realmonitor?channel=1&subtype=1
    Side:
      - rtsp://admin:password@192.168.68.204:554/cam/realmonitor?channel=1&subtype=0
    Side_sub:
      - rtsp://admin:password@192.168.68.204:554/cam/realmonitor?channel=1&subtype=1

objects:
  track:
    - person
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  Front_Door:
    enabled: true
    detect:
      width: 640
      height: 480
      fps: 7
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 
        0,0.493,0.139,0.505,0.377,0.519,0.381,0.407,0.496,0.423,0.504,0.51,0.703,0.541,0.711,0.469,1,0,0.003,0.005
  Driveway:
    enabled: true
    detect:
      width: 704
      height: 480
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 
        0,0.551,0.245,0.371,0.271,0.254,0.258,0.22,0.488,0.199,0.719,0.208,1,0.306,1,0,0.002,0.005
  Pool:
    enabled: true
    detect:
      width: 704
      height: 480
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  Back:
    enabled: true
    detect:
      width: 704
      height: 480
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Back_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  Side:
    enabled: true
    detect:
      width: 704
      height: 480
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask: 0,0.211,0.242,0.136,0.612,0.06,0.919,0.108,0.994,0.124,0.998,0.005,0.006,0.005
version: 0.14
```

### Relevant Frigate log output

```shell
2024-10-25 21:21:44
frigate.comms.dispatcher
Setting motion threshold for Driveway: 16
Info
2024-10-25 21:21:44
frigate.comms.dispatcher
Setting motion threshold for Driveway: 15
Info
2024-10-25 21:22:06
frigate.comms.dispatcher
Turning on improve contrast for Driveway
Info
2024-10-25 21:22:44
frigate.comms.dispatcher
Setting motion threshold for Driveway: 30
Info
2024-10-25 21:22:44
frigate.comms.dispatcher
Turning off improve contrast for Driveway
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
the one from unraid App Store
```

### Object Detector

Coral
