### DISCUSSION TITLE
QSV Accelaration

### DISCUSSION THREAD

**Discussion by thesebastianf** [blakeblackshear/frigate#14602] [Ask A Question] [answered]
I use (not recommended I know) in a Debian VM on Proxmox virt,
Its currently running actually ok.
Howver since its a pain in the a.. to passthrough D128 HWaccel and also Coral I run it on OpenVino for now until I can find working solutions for Coral.

I wanted to add hardware accelaration at least for the streams and since I have an I3 12100 wanted to give QSV a shot.

The documentation says to describe it directly for the stream so I tried
![image](https://github.com/user-attachments/assets/f172cbfa-2a5f-4813-9ea5-814c4024aaf0)

and set h265 for main and h264 for sub - which is how the cams are configured. It does not work and I think I might misinterpreting the documentation how or where to actually configure this.

**Comment by thesebastianf** [comment]
ok maybe I found it
and the config is part of camera config like below. as it only needs to decode the detect stream h264 only should be fine.
But can I find out if it is really used for accelaration?

EDIT: the detect stream stopped working now. so still wrong I guess. maybe I was seeing the live stream before and thought its working

```
cameras:
  hauseingang:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/hauseingang
          input_args: preset-rtsp-restream     
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hauseingang_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 1920 # <- optional, by default Frigate tries to automatically detect resolution, gesetzt damit die Ausloesgung im Overview nicht springt zwischen live und still bild
      height: 1080 # <- optional, by default Frigate tries to automatically detect resolution            
    live:
      stream_name: hauseingang
```
