### DISCUSSION TITLE
[Config Support]: reset_admin_password value?

### DISCUSSION THREAD

**Discussion by ki9us** [blakeblackshear/frigate#14611] [Config Support] [answered]
### Describe the problem you are having

What do I set `reset_admin_password` to in my config file?  I have tried: 

```yaml
reset_admin_password
```
```yaml
reset_admin_password:
```
```yaml
reset_admin_password: true
```

And the logs all say "invalid"

### Version

0.14

### Frigate config file

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
What is your config?

**Comment by ki9us** [comment]
```yaml
version: 0.14
tls:
  enabled: false
# https://docs.frigate.video/configuration/camera_specific/#mjpeg-cameras
go2rtc:
  streams:
    mjpeg_camera: 
      ffmpeg:https://user:notmypassword@example.com/backyard/#video=h264#hardware
cameras:
  camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_camera
          roles:
            - detect
            - record
    detect:
      enabled: false
      width: 1280
      height: 720
```
