### DISCUSSION TITLE
Clip and snapshot not available for some events

### DISCUSSION THREAD

**Discussion by fl42** [blakeblackshear/frigate#14617] [Ask A Question]
Hello,

I'm using the `events` MQTT topic to trigger workflows when objects are detected, such as pushing the clip/snapshot to a remote storage.
Frigate is configured to keep all recording segments and snapshots for 30 days.
I'm using 0.14.1-f4f3cfa.

It works nicely for most events, but for some events the clip and snapshot are not available: HTTP API returns 404 when trying to retrieve clip/snapshot for the event, and MQTT event has `has_clip: false` and `has_snapshot: false`.

What could be wrong?

Thank you for your help ;)

Below an example of an event:
```
{"before": {"id": "1729980086.225972-v2uw7d", "camera": "AAA_000023", "frame_time": 1729980086.225972, "snapshot": null, "label": "bird", "sub_label": null, "top_score": 0.0, "false_positive": true, "start_time": 1729980086.225972, "end_time": null, "score": 0.7367673516273499, "box": [811, 503, 839, 516], "area": 364, "ratio": 2.1538461538461537, "region": [678, 400, 998, 720], "stationary": false, "motionless_count": 0, "position_changes": 0, "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "after": {"id": "1729980086.225972-v2uw7d", "camera": "AAA_000023", "frame_time": 1729980086.225972, "snapshot": {"frame_time": 1729980087.585224, "box": [811, 503, 839, 516], "area": 364, "region": [678, 400, 998, 720], "score": 0.7367673516273499, "attributes": []}, "label": "bird", "sub_label": null, "top_score": 0.7367673516273499, "false_positive": false, "start_time": 1729980086.225972, "end_time": null, "score": 0.7367673516273499, "box": [811, 503, 839, 516], "area": 364, "ratio": 2.1538461538461537, "region": [678, 400, 998, 720], "stationary": false, "motionless_count": 0, "position_changes": 0, "current_zones": ["proche"], "entered_zones": ["proche"], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "type": "new"}
{"before": {"id": "1729980086.225972-v2uw7d", "camera": "AAA_000023", "frame_time": 1729980086.225972, "snapshot": {"frame_time": 1729980087.585224, "box": [811, 503, 839, 516], "area": 364, "region": [678, 400, 998, 720], "score": 0.7367673516273499, "attributes": []}, "label": "bird", "sub_label": null, "top_score": 0.7367673516273499, "false_positive": false, "start_time": 1729980086.225972, "end_time": null, "score": 0.7367673516273499, "box": [811, 503, 839, 516], "area": 364, "ratio": 2.1538461538461537, "region": [678, 400, 998, 720], "stationary": false, "motionless_count": 0, "position_changes": 0, "current_zones": ["proche"], "entered_zones": ["proche"], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "after": {"id": "1729980086.225972-v2uw7d", "camera": "AAA_000023", "frame_time": 1729980086.225972, "snapshot": {"frame_time": 1729980087.585224, "box": [811, 503, 839, 516], "area": 364, "region": [678, 400, 998, 720], "score": 0.7367673516273499, "attributes": []}, "label": "bird", "sub_label": null, "top_score": 0.7367673516273499, "false_positive": false, "start_time": 1729980086.225972, "end_time": 1729980095.874126, "score": 0.7367673516273499, "box": [811, 503, 839, 516], "area": 364, "ratio": 2.1538461538461537, "region": [678, 400, 998, 720], "stationary": false, "motionless_count": 0, "position_changes": 0, "current_zones": ["proche"], "entered_zones": ["proche"], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "type": "end"}
```

Frigate config:
```
[...]

objects:
  track:
    - bird
    [...]

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: all

snapshots:
  enabled: true
  crop: true
  bounding_box: true
  retain:
    default: 30

cameras:
  AAA_000023:
    ffmpeg:
      inputs:
        - input_args: preset-rtsp-restream-low-latency
          path: 
            rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@HOST:8554/AAA_000023
          roles:
            - record
            - detect
    mqtt:
      required_zones:
        - proche
    zones:
      proche:
        coordinates: 0,0.111,1,0.362,1,1,0,1
        inertia: 1
        loitering_time: 0
    objects:
      track:
        - bird
```
