### DISCUSSION TITLE
Sharing my Home Assistant notification blueprints

### DISCUSSION THREAD

**Discussion by edalquist** [blakeblackshear/frigate#14616] [Show and tell]
I've set up two automations in Home Assistant to handle Frigate notifications, figured I'd share here if others need something similar.

The first automation sends notifications on new reviewable person events, except for one trail camera. It only triggers when we aren't home or the alarm is set. It includes a gif of the event and has two reaction options to snooze alerts for some amount of time. Clicking on the event takes you to the event UI in the Frigate Web App.

The second automation handles the snooze responses on the alerts by disabling the notification automation for the specified period of time.

```
alias: "!Frigate: Person Alerts"
description: ""
triggers:
  - topic: frigate/reviews
    payload: "on"
    value_template: |-
      {{'on' if (
          value_json.type in ['new'] and 
          'person' in value_json.after.data.objects and 
          value_json.after.camera not in ['trail']
        ) else 'off'}}
    trigger: mqtt
conditions:
  - condition: or
    conditions:
      - condition: numeric_state
        entity_id: zone.home
        below: 1
      - condition: state
        entity_id: alarm_control_panel.abode_gateway
        state: armed_home
        for:
          hours: 0
          minutes: 5
          seconds: 0
      - condition: state
        entity_id: alarm_control_panel.abode_gateway
        state: armed_away
        for:
          hours: 0
          minutes: 5
          seconds: 0
    enabled: true
actions:
  - action: notify.iq_notify_eric
    data:
      message: "{{trigger.payload_json.after.camera}} detected a person"
      data:
        image: >-
          https://ha.example.com/api/frigate/notifications/{{trigger.payload_json.after.id}}/review_preview.gif
        url: >-
          https://nvr.example.com/review?id={{trigger.payload_json.after.id}}
        clickAction: >-
          https://nvr.example.com/review?id={{trigger.payload_json.after.id}}
        tag: "{{trigger.payload_json.after.id}}"
        when: "{{trigger.payload_json.after.start_time|int}}"
        group: camera_person
        channel: camera_person
        importance: high
        actions:
          - action: FRIGATE_SNOOZE_5
            title: Silence 5m
          - action: FRIGATE_SNOOZE_30
            title: Silence 30m
mode: single
```

```
alias: "!Frigate: Snooze"
description: ""
triggers:
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      group: camera_person
conditions:
  - condition: template
    value_template: "{{snooze_time > 0}}"
actions:
  - action: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      entity_id: automation.frigate_person_alerts
  - delay:
      hours: 0
      minutes: |
        {{snooze_time}}
      seconds: 0
      milliseconds: 0
  - action: automation.turn_on
    target:
      entity_id:
        - automation.frigate_testing_person_alerts
    data: {}
variables:
  snooze_time: |
    {{trigger.event.data.action | regex_replace('FRIGATE_SNOOZE_','')|int}}
mode: single
```
