### DISCUSSION TITLE
HA frigate Card shows a recording, which is not seen on Frigate WebUI

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#14612] [Ask A Question] [answered]
I have realized today for the first time, that i have some recordings which are seen on the HA Card, but they do not exist in Frigate WebUI Alerts/Detections. Btw. I do not mean that the count of items on card grid is different. I am aware of that the card shows the events in different intervals, so in frigate UI i have sometimes 2 different events from a 2 minutes period, and the card shows me out of that 2 minutes 5 boxes in total. I mean a complete time frame is missing on the WebUI.

This is frigate Card:
![FrigateCard](https://github.com/user-attachments/assets/872fd848-8598-4a74-a7f4-2de0919837c7)

And this is the Web UI:
<img width="939" alt="Bildschirmfoto 2024-10-26 um 21 32 10" src="https://github.com/user-attachments/assets/931549e5-2299-4513-ad7d-b7be3d46f0ad">

Since Card cannot show a non existent recording, why does not Frigate WebUI show this?

More interesting is that, the detection is a false positive. I have zones, and i only get alerts from this zone. So there the woman is out of that zone, so i should not have gotten an event from that. 

This is my zone:
<img width="1126" alt="Bildschirmfoto 2024-10-26 um 21 39 57" src="https://github.com/user-attachments/assets/7a6ef131-9aa4-4e18-ac99-4a7282fb4ede">

And this is my config which actually worked pretty well until today:

```yaml
mqtt:
  host: 192.168.178.6
  user: xxx
  password: xxx

record:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    reolink_doorbell:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.178.114/Preview_01_sub
    reolink_doorbell_sub:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    doorbell_stream_fuer_mode_mse:
      - rtsp://admin:password@192.168.178.114/Preview_01_main 

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    audio:
      enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - umbrella
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - umbrella
        required_zones: vorgarten
      detections:
        required_zones: vorgarten
    zones:
      vorgarten:
        coordinates: 
          0.603,0.255,0.61,0.355,0.613,0.436,0.615,0.517,0.614,0.59,0.611,0.729,0.612,0.744,0.567,0.753,0.504,0.763,0.42,0.774,0.318,0.778,0.19,0.771,0.097,0.752,0.065,0.658,0.058,0.507,0.063,0.351,0.077,0.265,0,0.266,0,1,1,1,1,0
    live:
      stream_name: reolink_doorbell
version: 0.14
```
