### DISCUSSION TITLE
2-way audio + HA Card Config Clarification

### DISCUSSION THREAD

**Discussion by bjvanst** [blakeblackshear/frigate#14623] [Ask A Question] [answered]
I struggled to get two way audio working with Home Assistant Core, Frigate 0.114 in Docker, and my Reolink Wifi Doorbell but believe I've figured it out.  I'm hoping someone can help clear up some confusion I have.

1. The configuration examples in the documentation enclose ffmpeg strings in quotations but doing so doesn't work on my installation.  Is this a difference between using Frigate as an HA Add-on vs running Frigate in Docker? Did something change in 0.114?  Confused about the discrepancy.

2. Is it normal to have to specify which stream to use in the Frigate card?  I have my doorbell set up with the main and sub stream and the final step in getting 2-way audio working was explicitly telling it to use a stream.  I haven't seen that mentioned elsewhere:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    go2rtc:
      modes:
        - webrtc
      stream: doorbell_sub
    webrtc_card: {}
    live_provider: go2rtc
    frigate: {}
```

3. If someone would be kind enough to give the config I've settled on a second set of eyes to see if I've done anything weird, I'd appreciate it:

```
go2rtc:
  streams:
    doorbell_main:
      - ffmpeg:https://<CAM_IP>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<USERNAME>&password=<PASSWORD>#video=copy#audio=copy#audio=opus
      - rtsp://<USERNAME>:<PASSWORD>@<CAM_IP>/Preview_01_main
    doorbell_sub:
      - ffmpeg:https://<CAM_IP>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<USERNAME>&password=<PASSWORD>#video=copy#audio=copy#audio=opus
      - rtsp://<USERNAME>:<PASSWORD>@<CAM_IP>/Preview_01_sub
  webrtc:
    candidates:
      - <FRIGATE_IP>:8555
      - stun:8555

cameras:
  doorbell:
    enabled: true
    mqtt:
      enabled: true
      height: 720
      quality: 100

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```
