### DISCUSSION TITLE
[Config Support]: Object Detection Active For Stationary Objects On Dashboard

### DISCUSSION THREAD

**Discussion by tdashmike** [blakeblackshear/frigate#14627] [Config Support]
### Describe the problem you are having

For my garage camera, when there are cars parked in it, the object detector says it's stationary which is great. Is there a way to get rid of the little car icon in the top left hand corner and the red box around the image on the dashboard?

![image](https://github.com/user-attachments/assets/b3f1dd3b-b90f-4101-9630-616ebf43950a)

![image](https://github.com/user-attachments/assets/c656858f-4c8e-4f0e-a65f-134029354088)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
GARAGE1:
    ui:
      order: 8
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/GARAGE1_LOW
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    motion:
      mask: 0.025,0.043,0.262,0.043,0.261,0.09,0.027,0.088
      lightning_threshold: 0.4
    zones:
      garage:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
        objects:
          - bear
          - bicycle
          - bird
          - bus
          - cat
          - dog
          - person
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    review:
      alerts:
        labels:
          - person
        required_zones:
          - garage
      detections:
        required_zones:
          - garage
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

CPU (no coral)
