### DISCUSSION TITLE
[Config Support]: Limit event detection to zone with 0.13.2

### DISCUSSION THREAD

**Discussion by koopernick** [blakeblackshear/frigate#14639] [Config Support] [answered]
### Describe the problem you are having

Hello,

I have a very basic config issue. Unfortunately I must use the 0.13.2 version, and the doc is no longer available for that version it seems (0.14.1 is not stable and random kernel panic / segway fault every other day for me sadly).

Regarding my basic issue, I can't make the event detection limited to a specific zone. The doc mention some variables that are not compatible with 0.13.2 it seems.

You can check my config, it's very easy and basic. I just want to limit the event reporting to the specified zone.

Thank you for your help ! 

### Version

0.13.2

### Frigate config file

```yaml
mqtt:
  enabled: false

ui:
  time_format: 24hour
  date_style: medium

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  quality: 3

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 7
      mode: motion

cameras:
  1front_left:
    ffmpeg:
      inputs:
      - path: 
          rtsp://$username:$password@192.168.1.152:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - detect
        - record
    zones:
      zone_1:
        coordinates: 2698,2108,3017,1231,2714,1107,2856,572,2576,522,269,2077
```

### Relevant Frigate log output

```shell
Not required
```

### Relevant go2rtc log output

```shell
Not required
```

### Frigate stats

```json
Not required
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.2
    shm_size: "2048mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/config:/config
      - /home/recording:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

not required

### Any other information that may be helpful

not required

**Comment by NickM-27** [comment, marked as answer]
you just need to set

```
snapshots:
  required_zones

record:
  events:
    required_zones:
```
