### DISCUSSION TITLE
[Camera Support]: Two of my cameras have consistently high ffmpeg CPU usage

### DISCUSSION THREAD

**Discussion by jbolla** [blakeblackshear/frigate#14633] [Camera Support] [answered]
### Describe the problem you are having

Two of my seven cameras have very high CPU usage as shown under system metrics. They are usually in the 30% - 35% range, sometimes a bit higher or lower. A couple of the other cameras can get into the 20s, but most tend to stay in the 10s most of the time.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant.mydomain.cc
  port: 1883
  topic_prefix: frigate
  user: username
  password: fake

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false
  restream: true
  width: 3840
  height: 2160
  mode: motion
  layout:
    scaling_factor: 1.5

ffmpeg:
  hwaccel_args: preset-vaapi

#Global Object Settings
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - cat
    - dog
    - horse
    - mouse

motion:
  enabled: true
  threshold: 30
  contour_area: 20
  improve_contrast: True

record:
  enabled: true
  retain:
    days: 1 # <- number of days to keep continuous recordings
  events:
    retain:
      default: 10 # <- number of days to keep event recordings

snapshots:
  enabled: true

go2rtc:
  streams:
    doorbell:
      - ffmpeg:https://doorbell.camera.mydomain.cc/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=fake#video=copy#audio=copy#audio=opus
      - rtsp://admin:fake@doorbell.camera.mydomain.cc/Preview_01_sub
    doorbell_sub:
      - ffmpeg:https://doorbell.camera.mydomain.cc/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=fake

    front_yard:
      - rtsp://admin:fake@front-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@front-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    front_periscope:
      - rtsp://admin:fake@front-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@front-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    back_periscope:
      - rtsp://admin:fake@back-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@back-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    side_yard:
      - rtsp://admin:fake@side-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@side-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    garage_entry:
      - rtsp://admin:fake@garage-entry.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@garage-entry.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    back_doors:
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

  webrtc:
    candidates:
      - 192.168.1.31:8555
      - stun:8555


cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - front_yard_all
    motion:
      mask:
        - 875,0,875,37,456,37,456,0
    zones:
      front_yard_all:
        coordinates: 0,672,896,672,896,383,95,335,0,350

    review:
      alerts:
        required_zones:
          - front_yard_all
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - front_yard_all
        - driveway
    motion:
      mask:
        - 3955,173,3957,65,3044,72,3044,164
    zones:
      front_yard_all:
        coordinates: 0,1396,0,1800,4096,1800,3627,714,2982,374,2238,104,1997,55,1442,72
      driveway:
        coordinates: 1147,832,1912,28,1560,53,571,881,0,1415,0,1800,132,1800
    birdseye:
      order: 1

    review:
      alerts:
        required_zones:
          - front_yard_all
          - driveway
  front_periscope:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_periscope
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    onvif:
      host: front-periscope.camera.mydomain.cc
      port: 80
      user: admin
      password: fake
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 1860,37,1865,99,1309,95,1311,31
  back_periscope:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_periscope
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    onvif:
      host: back-periscope.camera.mydomain.cc
      port: 80
      user: admin
      password: fake
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 1850,92,1848,31,1305,36,1305,94
        - 1754,190,1920,229,1920,0,1625,0

  side_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - side_yard_all
    birdseye:
      order: 2
    motion:
      mask:
        - 3023,162,3948,155,3937,65,3021,65
        - 0,483,696,294,1089,238,1831,210,2365,264,3777,481,3890,0,0,0
    zones:
      side_yard_all:
        coordinates: 4096,1800,4096,1204,3356,952,2231,631,1993,633,1602,703,911,818,102,1800

    review:
      alerts:
        required_zones:
          - side_yard_all
  garage_entry:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_entry
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - driveway
    motion:
      mask:
        - 3706,76,3701,150,3125,139,3125,72
    zones:
      driveway:
        coordinates: 0,2160,3840,2160,3840,0,2503,0,2236,63,1883,171,1424,327,0,917

    review:
      alerts:
        required_zones:
          - driveway
  back_doors:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_doors
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - back_yard_all
    motion:
      mask:
        - 3116,152,3706,154,3708,78,3127,89
        - 2449,342,3840,362,3840,0,2434,0
    zones:
      back_yard_all:
        coordinates: 0,2160,3840,2160,3840,758,3591,674,3361,644,2678,550,2449,568,2488,670,0,1240
      back_yard_close:
        coordinates: 0,2160,3840,2160,3840,1404,3556,1099,3339,940,3073,815,2440,670,0,1274

    review:
      alerts:
        required_zones:
          - back_yard_all
version: 0.14
```

### Relevant Frigate log output

```shell
Back doors has high FFMPEG CPU usage (34%)
```

### Relevant go2rtc log output

```shell
Back doors has high FFMPEG CPU usage (34%)
```

### FFprobe output from your camera

```shell
--- Back Doors
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:fake@back-doors.camera.dreamnet.cc':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.133000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 3840x2160, 15 fps, 15 tbr, 90k tbn

--- Garage Entry
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:fake@garage-entry.camera.dreamnet.cc':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.067000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 3840x2160, 15 fps, 15 tbr, 90k tbn
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

EmpireTech IPC-Color4K-X 8MP and EmpireTech IPC-B5842E-Z4E 1/1.8" CMOS 8MP

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/386b1e18-e602-4340-82d6-2a57434bef22)
![image](https://github.com/user-attachments/assets/78ba0aad-5e02-4f7c-b847-69123a66c4a0)

**Comment by NickM-27** [comment, marked as answer]
You should be using a sub stream not running detect on 4k stream

**Reply by jbolla** [reply]
Okay this is embarrassing, but isn't that what I'm doing by having two lines, one with subtype 0 and one with subtype 1? Do I need to have separate entries in go2rtc and assign roles to each?

```
  back_doors_main:
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  back_doors_sub:
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

  back_doors:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_doors_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_doors_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - back_yard_all
```

**Reply by NickM-27** [reply]
That's not what your original config shows

**Reply by jbolla** [reply]
Right, I'm asking if that's what I'm supposed to do. The original up above is what I have now, and it's what I thought had brought in the susbtreams with:
```
    back_doors:
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1
``` 
Reading https://docs.frigate.video/configuration/restream/#with-sub-stream
I thought that what I had now was the way to get the substream with one connection, and the way I posted in the comment right above is to do the same but with multiple connections.

**Reply by NickM-27** [reply]
All that does is define streams. It has nothing to do with how frigate interacts with the streams. You need to do it like your previous example. There's no reason go2rtc needs to be used for both, frigate can connect directly to the camera substream

**Reply by jbolla** [reply]
Thank you. I updated the configuration to separate out the substream and use it for detect and the CPU usage is way down.

**Reply by jbolla** [reply]
This change does seem to have increased my go2rtc CPU usage a fair bit. It used to be about 9% and now its staying around 26%.

**Reply by NickM-27** [reply]
What is the current config?

**Reply by jbolla** [reply]
```
mqtt:
  enabled: true
  host: homeassistant.mydomain.cc
  port: 1883
  topic_prefix: frigate
  user: jason
  password: fake

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false
  restream: true
  width: 3840
  height: 2160
  mode: motion
  layout:
    scaling_factor: 1.5

ffmpeg:
  hwaccel_args: preset-vaapi

#Global Object Settings
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - cat
    - dog
    - horse
    - mouse

motion:
  enabled: true
  threshold: 30
  contour_area: 20
  improve_contrast: true

record:
  enabled: true
  retain:
    days: 1 # <- number of days to keep continuous recordings
  events:
    retain:
      default: 10 # <- number of days to keep event recordings

snapshots:
  enabled: true

go2rtc:
  streams:
    doorbell:
      - ffmpeg:https://doorbell.camera.mydomain.cc/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=fake#video=copy#audio=copy#audio=opus
      - rtsp://admin:fake@doorbell.camera.mydomain.cc/Preview_01_sub
    doorbell_sub:
      - ffmpeg:https://doorbell.camera.mydomain.cc/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=fake

    front_yard:
      - rtsp://admin:fake@front-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_yard_sub:
      - rtsp://admin:fake@front-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    front_periscope:
      - rtsp://admin:fake@front-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_periscope_sub:
      - rtsp://admin:fake@front-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    back_periscope:
      - rtsp://admin:fake@back-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    back_periscope_sub:
      - rtsp://admin:fake@back-periscope.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    side_yard:
      - rtsp://admin:fake@side-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    side_yard_sub:
      - rtsp://admin:fake@side-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    garage_entry:
      - rtsp://admin:fake@garage-entry.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_entry_sub:
      - rtsp://admin:fake@garage-entry.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

    back_doors:
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    back_doors_sub:
      - rtsp://admin:fake@back-doors.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1

  webrtc:
    candidates:
      - 192.168.1.31:8555
      - stun:8555


cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - front_yard_all
    motion:
      mask:
        - 875,0,875,37,456,37,456,0
    zones:
      front_yard_all:
        coordinates: 0,672,896,672,896,383,95,335,0,350
    review:
      alerts:
        required_zones:
          - front_yard_all

  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - front_yard_all
        - driveway
    motion:
      mask: 0.966,0.095,0.966,0.035,0.708,0.041,0.708,0.097
    zones:
      front_yard_all:
        coordinates: 0,349,0,450,1024,450,907,179,746,94,560,26,499,14,361,18
      driveway:
        coordinates: 287,208,478,7,390,13,143,220,0,354,0,450,33,450
    birdseye:
      order: 1
    review:
      alerts:
        required_zones:
          - front_yard_all
          - driveway

  front_periscope:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_periscope
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_periscope_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    onvif:
      host: front-periscope.camera.mydomain.cc
      port: 80
      user: admin
      password: fake
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask: 0.967,0.033,0.97,0.092,0.589,0.094,0.588,0.037
  back_periscope:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_periscope
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_periscope_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    onvif:
      host: back-periscope.camera.mydomain.cc
      port: 80
      user: admin
      password: fake
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.967,0.085,0.966,0.042,0.597,0.046,0.597,0.082
        - 0.548,0.117,0.595,0.142,0.595,0,0.511,0
  side_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - side_yard_all
    birdseye:
      order: 2
    motion:
      mask:
        - 0.706,0.099,0.964,0.086,0.961,0.035,0.707,0.043
        - 0,0.268,0.17,0.164,0.266,0.133,0.447,0.117,0.577,0.146,0.922,0.265,0.95,0,0,0
    zones:
      side_yard_all:
        coordinates: 1024,450,1024,301,839,238,558,158,498,158,401,176,228,205,26,450
    review:
      alerts:
        required_zones:
          - side_yard_all

  garage_entry:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_entry
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_entry_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - driveway
    motion:
      mask: 0.964,0.035,0.965,0.082,0.596,0.085,0.595,0.041
    zones:
      driveway:
        coordinates: 0,480,704,480,704,0,459,0,410,14,345,38,261,73,0,204
    review:
      alerts:
        required_zones:
          - driveway

  back_doors:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_doors
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_doors_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - back_yard_all
    motion:
      mask:
        - 0.597,0.089,0.965,0.085,0.964,0.035,0.596,0.04
        - 0.257,0.185,0.428,0.147,0.442,0.347,0.268,0.413
    zones:
      back_yard_all:
        coordinates: 0,480,704,480,704,168,658,150,616,143,490,122,449,126,456,148,0,276
      back_yard_close:
        coordinates: 0,480,704,480,704,312,652,244,612,209,563,181,447,149,0,283
    review:
      alerts:
        required_zones:
          - back_yard_all
version: 0.14
```

**Reply by NickM-27** [reply]
right, you don't need to restream all of those sub streams, you can just have Frigate connect directly to the camera

**Reply by jbolla** [reply]
To be clear, you are suggesting removing all of the `some_camera_sub` entries from go2rtc streams, replacing `rtsp://127.0.0.1:8554/some_camera_sub` with the direct url of the camera (same as is currently in the go2rtc section), and changing the input_args to preset-rtsp-generic. I should keep the main substream in go2rtc to make for better live viewing, right?

Except for the doorbell, which I set up differently to begin with since it's following some reolink specific instructions I found while the rest of the cameras are Dahua's or rebadged Dahuas.

**Reply by jbolla** [reply]
I did the above. Deleted the _sub from gortc except doorbell_sub, used the rtsp url directly as the path in the camera config, and changed the input arg. It dropped the go2rtc usage from 27% to around 23%, which is better but still more than double  the previous. Example:

```
go2rtc:
  streams:
    front_yard:
      - rtsp://admin:fake@front-yard.camera.dreamnet.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
...
cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:fake@front-yard.camera.dreamnet.cc/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-generic
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - front_yard_all
        - driveway
    motion:
      mask: 0.966,0.095,0.966,0.035,0.708,0.041,0.708,0.097
    zones:
      front_yard_all:
        coordinates: 0,349,0,450,1024,450,907,179,746,94,560,26,499,14,361,18
      driveway:
        coordinates: 287,208,478,7,390,13,143,220,0,354,0,450,33,450
    birdseye:
      order: 1
    review:
      alerts:
        required_zones:
          - front_yard_all
          - driveway
```

**Reply by NickM-27** [reply]
that's not abnormal for restreaming multiple 4K streams

**Reply by jbolla** [reply]
Fair enough, and 23% CPU use isn't really a problem for me. The machine is dedicated solely to frigate. But it's puzzling since the previous setup used 9%.

```
go2rtc:
  streams:
    front_yard:
      - rtsp://admin:fake@front-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:fake@front-yard.camera.mydomain.cc/cam/realmonitor?channel=1&subtype=1
...
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - front_yard_all
        - driveway
    motion:
      mask:
        - 3955,173,3957,65,3044,72,3044,164
    zones:
      front_yard_all:
        coordinates: 0,1396,0,1800,4096,1800,3627,714,2982,374,2238,104,1997,55,1442,72
      driveway:
        coordinates: 1147,832,1912,28,1560,53,571,881,0,1415,0,1800,132,1800
    birdseye:
      order: 1
    review:
      alerts:
        required_zones:
          - front_yard_all
          - driveway
```

The new version moves a path out of the go2rtc section and into the camera section. Maybe that path was going entirely unused since I saw documentation suggesting that's treated like a failover in case the first path doesn't work. But would the direct connection in the camera section count against go2rtc CPU use at all? And the one I moved was the lower resolution substream. All the 4k+ streams were already in go2rtc and used for recording and detection (which was inappropriate as you helped me fix).
