### DISCUSSION TITLE
[HW Accel Support]: Using S7150 as decoder - 10 cameras limit ?

### DISCUSSION THREAD

**Discussion by cupertinomiranda** [blakeblackshear/frigate#14632] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hi everyone,

I am using an AMD S7150 gpu for h264 decoding.

After I enable more then 10 cameras I get a couple of them missing with what appears to be an AMD driver error, and sometimes a mention that there are not UVD instances available.
My perception is that there is a hard limit to 10 consecutive decoders, regardless of the bitrate of the stream.

2 questions:
 - Does anyone has experience with AMD gpus and can tell me with certainty that my assumption is correct?
 - How to make any other of the 10+ cameras having decoding being done by CPU ?

Thanks 

### Version

0.14.1-8fcb8e5

### Frigate config file

```yaml
10+ cameras like this:

  house_garage_door:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.199.82:554/media/video1
          roles:
            - record
        - path: rtsp://192.168.199.82:554/media/video2
          roles:
            - detect
          hwaccel_args: preset-vaapi
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

NA

### Screenshots of the Frigate UI's System metrics pages

NA
