### DISCUSSION TITLE
[Config Support]: Going from QNAP and Wyze cameras to UGREEN NAS and Ubiquiti camera

### DISCUSSION THREAD

**Discussion by dimmanramone** [blakeblackshear/frigate#14630] [Config Support] [answered]
### Describe the problem you are having

I had Frigate working with Doubletake and Compreface in my QNAP and Wyzes cameras working without any problem for a while now. 

Last week I went over to a UGREEN NAS and ubiquiti cameras and used as a base my old configuration but I guess I have to clear my config a little bit and I am a little bit lost. I can even see a high usage of CPU by ffpmpeg.

The UGREEN NAS has an Intel Pentium Gold 8505 with Intel UHD Graphics Xe G4, and I'm using a Coral TPU.

Any help appreciated.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.1
  user: user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    hall_cam:
      - rtspx://192.168.1.1:7441/stream1
      - "ffmpeg:hall_cam#audio=opus"
    lounge_cam:
      - rtspx://192.168.1.1:7441/stream2
      - "ffmpeg:lounge_cam#audio=opus"
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 30000000 -use_wallclock_as_timestamps 1
  output_args:
    record: preset-record-ubiquiti

detect:
  width: 1920
  height: 1080

objects:
  track:
    - person

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects

audio:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

cameras:
  hall_cam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/stream1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  lounge_cam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/stream2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
version: 0.14
```

### Relevant Frigate log output

```shell
2024-10-27 13:33:01.599928558  [2024-10-27 13:33:01] ffmpeg.lounge_cam.detect       ERROR   : rtsps://192.168.1.1:7441/stream2: Input/output error
2024-10-27 13:33:01.600100930  [2024-10-27 13:33:01] ffmpeg.lounge_cam.detect       ERROR   : [tcp @ 0x556aeee4e680] ffurl_read returned 0xdfb9b0bb
2024-10-27 13:33:01.600241214  [2024-10-27 13:33:01] ffmpeg.lounge_cam.detect       ERROR   : rtsps://192.168.1.1:7441/stream2: Input/output error
2024-10-27 13:33:06.750191686  [2024-10-27 13:33:06] frigate.video                  ERROR   : lounge_cam: Unable to read frames from ffmpeg process.
2024-10-27 13:33:06.750491974  [2024-10-27 13:33:06] frigate.video                  ERROR   : lounge_cam: ffmpeg process is not running. exiting capture thread...
2024-10-27 13:33:11.611511668  [2024-10-27 13:33:11] watchdog.lounge_cam            ERROR   : Ffmpeg process crashed unexpectedly for lounge_cam.
```

### Relevant go2rtc log output

```shell
2024-10-26 20:50:18.943674387  [INFO] Preparing new go2rtc config...
2024-10-26 20:50:19.173961125  [INFO] Starting go2rtc...
2024-10-26 20:50:19.257539979  20:50:19.257 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-10-26 20:50:19.257544452  20:50:19.257 INF config path=/dev/shm/go2rtc.yaml
2024-10-26 20:50:19.257883232  20:50:19.257 INF [api] listen addr=:1984
2024-10-26 20:50:19.257948084  20:50:19.257 ERR [rtsp] listen error="listen tcp :8554: bind: address already in use"
2024-10-26 20:50:19.258072992  20:50:19.258 INF [webrtc] listen addr=:8555/tcp
2024-10-26 20:50:28.944363755  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    privileged: true # this may not be necessary for all setups
    network_mode: host
    shm_size: 256mb # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../appdata/security/frigate/config:/config
      - ../../appdata/security/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    # memory: "4g"
    # cpus: 2
    environment:
      FRIGATE_RTSP_PASSWORD: pass
      #LIBVA_DRIVER_NAME: i965
```

### Object Detector

Coral

**Comment by dimmanramone** [comment, marked as answer]
I did some changes and it seems that I'm not getting any errors. Still confused if it is the best configuration for ubiquiti cameras. So any help/tips appreciated.

```
mqtt:
  host: 192.168.1.1
  user: mqttuser
  password: mqttpass

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    hall_cam:
      - rtsps://192.168.1.1:7441/hall_cam_stream
      - "ffmpeg:hall_cam#audio=opus"
    lounge_cam:
      - rtsps://192.168.1.1:7441/lounge_cam_stream
      - "ffmpeg:lounge_cam#audio=opus"
ffmpeg:
  hwaccel_args: preset-vaapi

  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-ubiquiti

objects:
  track:
    - person

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects

audio:
  enabled: false

snapshots:
  enabled: true
  timestamp: true

cameras:
  hall_cam:
    ffmpeg:

      inputs:
        - path: rtsp://127.0.0.1:8554/hall_cam
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  lounge_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lounge_cam
          roles:
            - record
            - detect

    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
version: 0.14
```
