### DISCUSSION TITLE
[Support]: Wrong layout in "All cameras" view both desktop and mobile

### DISCUSSION THREAD

**Discussion by quantummobile** [blakeblackshear/frigate#14634] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Camera has large black margins on both sides in "All cameras" view when viewed in desktop. This looks weird and occupies lots of space for no reason. When viewed in mobile/responsive, that particular camera is too small.

### Steps to reproduce

I believe it is related to Reolink Duo 2 WiFi camera, as it has unusual resolution of 4608X1728.

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Microsoft Edge Version 130.0.2849.52 (Official build) (arm64)

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: *.*.*.*
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  #topic_prefix: homeassistant
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: ***
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: ***

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    # frigate.event: debug
    frigate.record: debug
    frigate.record.maintainer: debug

detectors:
  coral:
    type: edgetpu
    device: usb

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db

ffmpeg:
  hwaccel_args: preset-vaapi

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    # max_frames:
    #   # Optional: Default for all object types (default: not set, track forever)
    #   default: 3000
    #   # Optional: Object specific values
    #   objects:
    #     person: 1000

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - bird
    - cat
    - dog
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  # mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  # filters:
  #   person:
  #     # Optional: minimum width*height of the bounding box for the detected object (default: 0)
  #     min_area: 70
  #     # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
  #     # max_area: 100000
  #     # Optional: minimum width/height of the bounding box for the detected object (default: 0)
  #     min_ratio: 0.5
  #     # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
  #     max_ratio: 2.0
  #     # Optional: minimum score for the object to initiate tracking (default: shown below)
  #     min_score: 0.5
  #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
  #     threshold: 0.85
  #     # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
  #     # Checks based on the bottom center of the bounding box of the object
  #     # mask: 0,0,1000,0,1000,200,0,200

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 10
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  # mask: 0,900,1080,900,1080,1920,0,1920
  mask:
    - 292,82,202,80,162,82,160,68,166,54,178,38,321,43,500,48,437,94,404,88
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  # mqtt_off_delay: 30

# # Optional: Record configuration
# # NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: true

  sync_recordings: false
  
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 14
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  export:
    timelapse_args: -vf setpts=PTS/60 -r 25
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 60
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 60
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      # - bicycle
      - bird
      - cat
      - dog
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
   # required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 14
        car: 14
        bicycle: 14
        bird: 14
        cat: 14
        dog: 14
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  # height: 768
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 14
    # Optional: Per object retention days
    # objects:
    #   person: 2
    #   car: 2
    #   dog: 2
    #   bike: 2
    #   cat: 2

go2rtc:
  streams:
    reolink:
      - ffmpeg:http://*.*.*.*/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***#video=copy#audio=copy#audio=opus
    reolink_sub:
      - ffmpeg:http://*.*.*.*/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=***&password=***
    reolink_duo:
      - rtsp://***:***@*.*.*.*:554/h264Preview_01_main
    reolink_duo_sub:
      - rtsp://***:***@*.*.*.*:554/h264Preview_01_sub

cameras:
  front_door:
    ui:
      order: 0
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect       
    detect:
      width: 640
      height: 360
      fps: 7
      stationary:
        interval: 50
        threshold: 50

    motion:
      mask:
        - 0.456,0.228,0.316,0.222,0.253,0.228,0.25,0.189,0.259,0.15,0.278,0.106,0.502,0.119,0.781,0.133,0.683,0.261,0.631,0.244
        - 0.572,0.061,0.572,0.003,0.997,0.008,0.998,0.063
      threshold: 35
      contour_area: 10
      improve_contrast: true
      
  backyard:
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_duo?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_duo_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect    
    detect:
      width: 768
      height: 288
      fps: 7
      stationary:
        interval: 50
        threshold: 50
        
version: 0.14
camera_groups:
  Test:
    order: 1
    icon: LuBird
    cameras:
      - front_door
      - backyard
```

### docker-compose file or Docker CLI command

```yaml
#################################################
version: "3.9"
services:
  frigate-beta:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/:/config/
      - /mnt/frigate-nfs:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000      
    ports:
      #- "5000:5000"
      #- "1935:1935" # RTMP feeds
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-410W, Reolink Duo 2 WiFi

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-10-28 at 09 06 20](https://github.com/user-attachments/assets/fe2c8bd3-4865-4033-85de-250a6af2f7b1)
![9E68649C-9D71-4AB8-8108-E504796DEF8B](https://github.com/user-attachments/assets/d29ac315-faf2-4647-9093-488f3873d23d)
