### DISCUSSION TITLE
clip.mp4 is 22 GB huge

### DISCUSSION THREAD

**Discussion by kankadev** [blakeblackshear/frigate#14646] [Ask A Question]
Hi,

I was wondering why my “Clip to Google Drive Uploader” script was throwing errors so often today. The disk space ran full because a clip.mp4 is more than 22 GB and my script tries to upload this file all the time, but there is not that much disk space in the Docker container. 

The question is much more how a single clip.mp4, which has a total length of over 10 hours, can become so large? In this clip you can see a compilation of over two days. Why weren't more than one clip.mp4 created from these many events?

And I'm also wondering how I can now “safely” remove this clip. Can I simply delete the clip from the hard disk or should I also edit the database? As far as I know, there is unfortunately no filter to find a clip directly in the GUI by its ID.

/api/events/1729942912.297013-cg99hs/clip.mp4

```yml
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000" # deprecated 
      - "8971:8971" # new restricted access port since 0.14.x
      #- "1935:1935" # RTMP feeds
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
```

```yml
mqtt:
  host: 192.168.0.135
  user: mosq
  password: xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate

auth:
  enabled: true
  failed_login_rate_limit: 1/second;3/minute;8/hour
  trusted_proxies:
    - 172.19.0.0/16

#proxy:
#  auth_secret:
#    xxx


ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

objects:
  track:
    - person
    - dog
    - cat
    - car
    - motorcycle
    - bicycle
  filters:
    person:
      min_area: 400
      max_area: 1000000

go2rtc:
  log:
    exec: trace
  rtsp:
    username: camera
    password: xxx
  webrtc:
    candidates:
      - 192.168.0.151:8555
      - 192.168.0.150:8555
      - stun:8555
  streams:
    inside_door:
      - rtsp://cam:xxx@192.168.3.221/stream1
      - ffmpeg:inside_door#audio=opus
    inside_door_sub:
      - rtsp://cam:xxx@192.168.3.221/stream2
      - ffmpeg:inside_door_sub#audio=opus

    inside_office:
      - rtsp://cam:xxx@192.168.0.104:554/h264Preview_01_main
      - ffmpeg:inside_office#audio=opus
    inside_office_sub:
      - rtsp://cam:xxx@192.168.0.104:554/h264Preview_01_sub
      - ffmpeg:inside_office_sub#audio=opus

    inside_studio_kitchen:
      - rtsp://cam:xxx@192.168.0.108:554/h264Preview_01_main
      - ffmpeg:inside_studio_kitchen#audio=opus
    inside_studio_kitchen_sub:
      - rtsp://cam:xxx@192.168.0.108:554/h264Preview_01_sub
      - ffmpeg:inside_studio_kitchen_sub#audio=opus

    inside_studio_living:
      - rtsp://cam:xxx@192.168.0.109:554/h264Preview_01_main
      - ffmpeg:inside_studio_living#audio=opus
    inside_studio_living_sub:
      - rtsp://cam:xxx@192.168.0.109:554/h264Preview_01_sub
      - ffmpeg:inside_studio_living_sub#audio=opus

    outside_door:
      - rtsp://cam:xxx@192.168.0.103/stream1
      - ffmpeg:outside_door#audio=opus
    outside_door_sub:
      - rtsp://cam:xxx@192.168.0.103/stream2
      - ffmpeg:outside_door_sub#audio=opus

    outside_front_door:
      - rtsp://cam:xxx@192.168.0.101/stream1
      - ffmpeg:outside_front_door#audio=opus
    outside_front_door_sub:
      - rtsp://cam:xxx@192.168.0.101/stream2
      - ffmpeg:outside_front_door_sub#audio=opus

    outside_left_front:
      - rtsp://cam:xxx@192.168.0.106/stream1
      - ffmpeg:outside_left_front#audio=opus
    outside_left_front_sub:
      - rtsp://cam:xxx@192.168.0.106/stream2
      - ffmpeg:outside_left_front_sub#audio=opus

    outside_left_behind:
      - rtsp://cam:xxx@192.168.0.105/stream1
      - ffmpeg:outside_left_behind#audio=opus
    outside_left_behind_sub:
      - rtsp://cam:xxx@192.168.0.105/stream2
      - ffmpeg:outside_left_behind_sub#audio=opus

    outside_back:
      - rtsp://cam:xxx@192.168.0.107/stream1
      - ffmpeg:outside_back#audio=opus
    outside_back_sub:
      - rtsp://cam:xxx@192.168.0.107/stream2
      - ffmpeg:outside_back_sub#audio=opus

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  events:
    pre_capture: 7
    post_capture: 7
    retain:
      default: 10
      mode: active_objects

cameras:
  inside_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/inside_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/inside_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: inside_door_sub
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0,0.062,0.357,0.068,0.36,0,0,0
  inside_office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/inside_office
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/inside_office_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: inside_office_sub
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 0.676,0.167,0.765,0.166,0.768,0.053,0.681,0.035
        - 0.351,0.065,0.644,0.068,0.643,0.023,0.348,0.027
  inside_studio_kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/inside_studio_kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/inside_studio_kitchen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: inside_studio_kitchen_sub
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0.701,0.977,0.994,0.977,0.996,0.939,0.699,0.938
  inside_studio_living:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/inside_studio_living
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/inside_studio_living_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: inside_studio_living_sub
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0.012,0.065,0.31,0.063,0.306,0.028,0.014,0.029
  outside_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outside_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: outside_door_sub
    detect:
      width: 640
      height: 360
      fps: 5
    zones:
      poi:
        coordinates: 
          0.002,1,0.857,1,0.826,0.171,0.833,0.084,0.815,0.077,0.806,0.147,0.724,0.112,0.731,0.046,0.609,0,0.002,0.106
        inertia: 3
        loitering_time: 1
    motion:
      mask:
        - 0.872,0,1,0,1,0.188,1,1,0.882,1,0.836,0.083,0.707,0.039,0.714,0
        - 0.358,0.048,0.358,0,0,0,0,0.048
        - 0,0.076,0.019,0.074,0.021,0.184,0,0.184
    review:
      alerts:
        required_zones: poi
  outside_front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outside_front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: outside_front_door_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0.367,0,0.36,0.098,0.199,0.09,0,0.122,0,0
        - 0.15,1,0,1,0,0.535,0.024,0.536
        - 0.495,0.001,1,0,1,0.332
        - 0.576,0.168,0.699,0.391,1,0.978,1,0.408
    zones:
      poi:
        coordinates: 
          0.026,0.528,0.155,1,1,1,0.587,0.19,0.516,0.174,0.495,0.14,0.486,0.287,0.345,0.285,0.344,0.151,0,0.206,0,0.529
        inertia: 3
        loitering_time: 1
    review:
      alerts:
        required_zones: poi
    objects:
      filters:
        car:
          mask: 0.812,0.115,1,0.314,1,0.438,0.753,0.292
  outside_left_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_left_front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outside_left_front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: outside_left_front_sub
    detect:
      width: 640
      height: 360
      fps: 5
    zones:
      poi:
        coordinates: 1,1,0,1,0,0.886,0.724,0.098,0.996,0.104
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0.369,0.45,0.669,0.153,0.656,0,0,0,0,0.878
        - 0.698,0,0.69,0.091,0.989,0.088,0.988,0
    review:
      alerts:
        required_zones: poi
  outside_left_behind:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_left_behind
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outside_left_behind_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: outside_left_behind_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      poi:
        coordinates: 0.459,1,0.85,1,0.822,0.207,0.727,0.197,0.716,0.279
        inertia: 3
        loitering_time: 1
    motion:
      mask:
        - 0,1,0.453,1,0.707,0.28,0.725,0.19,0.827,0.201,0.824,0,0,0
        - 0.853,1,1,1,1,0,0.83,0
    review:
      alerts:
        required_zones: poi
    objects:
      mask: 0,0,0.826,0,0.828,0.202,0.728,0.191,0.456,1,0,1
  outside_back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_back
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outside_back_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: outside_back_sub
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0,1,0,1,0.17,1,0.693,0.158,0.855,0.171,0.855,0,0.708,0,0,0
    zones:
      poi:
        coordinates: 0.184,1,0.898,1,0.857,0.195,0.695,0.18
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: poi
    objects:
      mask: 0,0,0.861,0,0.865,0.117,0.695,0.096,0.135,1,0,1
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
  Inside:
    order: 2
    icon: LuBedDouble
    cameras:
      - inside_door
      - inside_office
      - inside_studio_kitchen
      - inside_studio_living
  Outside:
    order: 3
    icon: LuFlower2
    cameras:
      - outside_back
      - outside_door
      - outside_front_door
      - outside_left_behind
      - outside_left_front
```
