### DISCUSSION TITLE
[Support]: Upgraded to 0.14.1 - Preview has werid coloured streak

### DISCUSSION THREAD

**Discussion by adirburke** [blakeblackshear/frigate#14650] [General Support]
### Describe the problem you are having

The preview screen has a werid green streak across the image and there is a dotted line from corner to corner

Just started after i upgraded to 0.14.1

![Screenshot 2024-10-29 at 11 34 22 am](https://github.com/user-attachments/assets/1f4f5a73-f946-4023-993a-82d13d88fab3)

### Version

0.14.1

### What browser(s) are you using?

Version 129.0.6668.101 (Official Build) (arm64)

### Frigate config file

```yaml
mqtt:
  enabled: false

birdseye:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h265

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

detect:
  fps: 5
  enabled: true

objects:
  track:
    - person
    - car

cameras:
  back_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c2/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c2/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
  street_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c3/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c3/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
  street_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c7/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c7/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c6/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c6/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
  front_stairs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c4/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c4/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c5/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c5/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
  side_up:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c1/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c1/s1/live
          roles:
            - detect
            # - rtmp
    detect:
      fps: 5
      height: 704
      width: 576
    motion:
      mask:
        - 0,0,231,0,219,576,0,576
        - 349,0,426,0,565,0,596,0,704,0,704,576,428,576,279,103
  side_down:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c8/s0/live
          roles:
            - record
        - path: rtsp://admin:Rexy2022@10.30.0.210:554/unicast/c8/s1/live
          roles:
            - detect
            # - rtmp
  front_gate_intercom:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:adir2039@10.30.0.6:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - record
        - path: rtsp://admin:adir2039@10.30.0.6:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            # - rtmp
  front_door_intercom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_intercom
          # hwaccel_args: preset-nvidia-h265
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://admin:adir2039@10.30.0.5:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          hwaccel_args: preset-nvidia-h264
          roles:
            - detect
            # - rtmp
go2rtc:
  streams:
    front_door_intercom:
      - rtsp://admin:adir2039@10.30.0.5:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:front_door_intercom#video=h265

version: 0.14
```

### Relevant Frigate log output

```shell
Visional issue with preview
```

### Relevant go2rtc log output

```shell
Visional issue with preview
```

### FFprobe output from your camera

```shell
Visional issue with preview
```

### Frigate stats

```json
{"cameras":{"back_yard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":677,"detection_enabled":true,"detection_fps":5.4,"ffmpeg_pid":681,"pid":597,"process_fps":5.1,"skipped_fps":0.0},"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":690,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":698,"pid":621,"process_fps":5.1,"skipped_fps":0.0},"front_door_intercom":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":732,"detection_enabled":true,"detection_fps":9.8,"ffmpeg_pid":744,"pid":669,"process_fps":5.0,"skipped_fps":0.0},"front_gate_intercom":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":727,"detection_enabled":true,"detection_fps":16.0,"ffmpeg_pid":737,"pid":661,"process_fps":5.1,"skipped_fps":0.0},"front_stairs":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":699,"detection_enabled":true,"detection_fps":2.7,"ffmpeg_pid":705,"pid":629,"process_fps":4.9,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":706,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":713,"pid":637,"process_fps":5.0,"skipped_fps":0.0},"side_down":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":719,"detection_enabled":true,"detection_fps":30.3,"ffmpeg_pid":726,"pid":653,"process_fps":5.1,"skipped_fps":0.0},"side_up":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":711,"detection_enabled":true,"detection_fps":7.7,"ffmpeg_pid":718,"pid":645,"process_fps":5.1,"skipped_fps":0.0},"street_1":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":680,"detection_enabled":true,"detection_fps":5.4,"ffmpeg_pid":685,"pid":605,"process_fps":5.1,"skipped_fps":0.0},"street_2":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":684,"detection_enabled":true,"detection_fps":10.2,"ffmpeg_pid":691,"pid":613,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1026":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(64)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"104":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"126":{"cmdline":"python3 -u -m frigate","cpu":"21.5","cpu_average":"25","mem":"8.7"},"133":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"159":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"162":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"296":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"344":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"488":{"cmdline":"frigate.recording_manager","cpu":"2.7","cpu_average":"2","mem":"0.6"},"490":{"cmdline":"frigate.review_segment_manager","cpu":"0.7","cpu_average":"0","mem":"0.5"},"515":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(72)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"516":{"cmdline":"frigate.detector.coral","cpu":"18.9","cpu_average":"19","mem":"0.5"},"518":{"cmdline":"frigate.output       ","cpu":"4.9","cpu_average":"5","mem":"0.5"},"526":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"531":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"536":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"541":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"546":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"551":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"556":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 576x704 -i pipe: -threads 1 -f mpegts -s 589x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"561":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -threads 1 -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"567":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"572":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"577":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"597":{"cmdline":"frigate.process:back_yard","cpu":"2.5","cpu_average":"2","mem":"2.8"},"605":{"cmdline":"frigate.process:street_1","cpu":"4.9","cpu_average":"5","mem":"2.8"},"613":{"cmdline":"frigate.process:street_2","cpu":"4.9","cpu_average":"6","mem":"2.8"},"621":{"cmdline":"frigate.process:front_door","cpu":"0.5","cpu_average":"0","mem":"2.8"},"629":{"cmdline":"frigate.process:front_stairs","cpu":"1.9","cpu_average":"2","mem":"2.8"},"637":{"cmdline":"frigate.process:garage","cpu":"0.5","cpu_average":"0","mem":"2.8"},"645":{"cmdline":"frigate.process:side_up","cpu":"4.7","cpu_average":"5","mem":"2.8"},"653":{"cmdline":"frigate.process:side_down","cpu":"13.4","cpu_average":"10","mem":"2.8"},"661":{"cmdline":"frigate.process:front_gate_intercom","cpu":"9.4","cpu_average":"9","mem":"2.8"},"669":{"cmdline":"frigate.process:front_door_intercom","cpu":"4.3","cpu_average":"4","mem":"2.8"},"677":{"cmdline":"frigate.capture:back_yard","cpu":"0.3","cpu_average":"0","mem":"2.8"},"680":{"cmdline":"frigate.capture:street_1","cpu":"0.3","cpu_average":"0","mem":"2.8"},"681":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c2/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"1","mem":"0.8"},"684":{"cmdline":"frigate.capture:street_2","cpu":"0.3","cpu_average":"0","mem":"2.8"},"685":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c3/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"1","mem":"0.8"},"690":{"cmdline":"frigate.capture:front_door","cpu":"0.3","cpu_average":"0","mem":"2.8"},"691":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c7/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"1","mem":"0.8"},"692":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c2/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_yard@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"697":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c3/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/street_1@%Y%m%d%H%M%S%z.mp4","cpu":"1.2","cpu_average":"1","mem":"0.1"},"698":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c6/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.4"},"699":{"cmdline":"frigate.capture:front_stairs","cpu":"0.3","cpu_average":"0","mem":"2.8"},"704":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c7/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/street_2@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"1","mem":"0.1"},"705":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c4/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.4"},"706":{"cmdline":"frigate.capture:garage","cpu":"0.4","cpu_average":"0","mem":"2.8"},"711":{"cmdline":"frigate.capture:side_up","cpu":"0.4","cpu_average":"0","mem":"2.8"},"712":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c6/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"713":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c5/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.4"},"718":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c1/s1/live -r 5 -vf fps=5,scale_cuda=w=576:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.4"},"719":{"cmdline":"frigate.capture:side_down","cpu":"0.3","cpu_average":"0","mem":"2.8"},"723":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c4/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_stairs@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"725":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c5/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"726":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c8/s1/live -r 5 -vf fps=5,scale_cuda=w=704:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.4"},"727":{"cmdline":"frigate.capture:front_gate_intercom","cpu":"0.7","cpu_average":"0","mem":"2.8"},"732":{"cmdline":"frigate.capture:front_door_intercom","cpu":"0.6","cpu_average":"0","mem":"2.8"},"734":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c1/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side_up@%Y%m%d%H%M%S%z.mp4","cpu":"0.6","cpu_average":"0","mem":"0.1"},"737":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.6:554/cam/realmonitor?channel=1&subtype=0 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"2","mem":"0.8"},"744":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.5:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"2","mem":"0.8"},"745":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.210:554/unicast/c8/s0/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side_down@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"748":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.30.0.6:554/cam/realmonitor?channel=1&subtype=1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_gate_intercom@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.1"},"751":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_door_intercom -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door_intercom@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.1"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"8873":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"9007":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"2.2","cpu_average":"1","mem":"0.1"},"frigate.full_system":{"cpu":"8.5","mem":"29.5"}},"detection_fps":87.6,"detectors":{"coral":{"detection_start":1730165717.745063,"inference_speed":7.39,"pid":516}},"gpu_usages":{"NVIDIA RTX A4000":{"dec":"5.0%","enc":"0.0%","gpu":"2.0%","mem":"13.57%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":344},"recording":{"pid":488},"review_segment":{"pid":490}},"service":{"last_updated":1730165717,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":1007.8,"mount_type":"tmpfs","total":1024.0,"used":16.2},"/media/frigate/clips":{"free":12043459.4,"mount_type":"cifs","total":12043459.6,"used":0.2},"/media/frigate/recordings":{"free":12043459.4,"mount_type":"cifs","total":12043459.6,"used":0.2},"/tmp/cache":{"free":1816.9,"mount_type":"tmpfs","total":1907.4,"used":90.5}},"temperatures":{},"uptime":476,"version":"0.14.1-f4f3cfa"}}
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
      container_name: frigate
      privileged: true
      restart: unless-stopped
      image: ghcr.io/blakeblackshear/frigate:0.14.1
      shm_size: 1G # update for your cameras based on calculation above
      devices:
        - /dev/bus/usb:/dev/bus/usb
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /opt/frigate/config:/config
        - /my:/media/frigate
        - type: tmpfs # Optional: 2GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: 2000000000
      ports:
          - "5000:5000"
          - "8554:8554" # RTSP feeds
          - "8555:8555/tcp" # WebRTC over tcp
          - "8555:8555/udp" # WebRTC over udp
      environment:
        FRIGATE_RTSP_PASSWORD: "password"  #modify to whatever if using rtsp
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Fermax
