### DISCUSSION TITLE
[Detector Support]: trying to use frigate+ model on rocm chip but load fails

### DISCUSSION THREAD

**Discussion by lortiejp** [blakeblackshear/frigate#14664] [Detector Support]
### Describe the problem you are having

Hello!

I'm trying to use a frigate+ model that I requested yesterday from my subscription. As per instructions, I asked for a yolonas model and got it this morning. I'm using this image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1-rocm which properly loads the rocm libraries. In my config, under model, I have:

>   model_type: yolonas
>   path: plus://2dd01205132f082b04531f15399bdf5c

I also see that this model is the proper type in my model list. When I start the docker, I get in the logs:

> frigate  | 2024-10-29 09:22:47.005132625  [2024-10-29 09:22:46] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: loaded migraphx module
> frigate  | 2024-10-29 09:22:47.005172158  [2024-10-29 09:22:46] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: switching HIP to blocking mode to conserve CPU

and then, right after:

> frigate  | 2024-10-29 09:22:47.014778308  Process detector:rocm:
> frigate  | 2024-10-29 09:22:47.014780592  Traceback (most recent call last):
> frigate  | 2024-10-29 09:22:47.014781604    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
> frigate  | 2024-10-29 09:22:47.014786022      self.run()
> frigate  | 2024-10-29 09:22:47.014787716    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
> frigate  | 2024-10-29 09:22:47.014788637      return run(*args, **kwargs)
> frigate  | 2024-10-29 09:22:47.014807563    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
> frigate  | 2024-10-29 09:22:47.014808645      self._target(*self._args, **self._kwargs)
> frigate  | 2024-10-29 09:22:47.014810298    File "/opt/frigate/frigate/object_detection.py", line 109, in run_detector
> frigate  | 2024-10-29 09:22:47.014811279      object_detector = LocalObjectDetector(detector_config=detector_config)
> frigate  | 2024-10-29 09:22:47.014812231    File "/opt/frigate/frigate/object_detection.py", line 61, in __init__
> frigate  | 2024-10-29 09:22:47.014813143      self.detect_api = create_detector(detector_config)
> frigate  | 2024-10-29 09:22:47.014838650    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
> frigate  | 2024-10-29 09:22:47.014839662      return api(detector_config)
> frigate  | 2024-10-29 09:22:47.014858307    File "/opt/frigate/frigate/detectors/plugins/rocm.py", line 111, in __init__
> frigate  | 2024-10-29 09:22:47.014859369      raise Exception(f"AMD/ROCm: unknown model format {path}")
> frigate  | 2024-10-29 09:22:47.014860521  Exception: AMD/ROCm: unknown model format /config/model_cache/2dd01205132f082b04531f15399bdf5c

I checked that this model is in the model_cache directory (there's a json and the file without extension). So the file is there but cannot be loaded.

I know that the rocm support was suspended for a while but I just bought a ryzen 9 8945 and was really hoping to use it as my DVR. Using cpu for detectors is just painful because the fans buzz restlessly. :-) (I have 12 cameras.) My USB-coral dongle is a bit too unstable for now.

Do you think there's a way to make this work? It looks like a file format error but I'm not sure what it is.

If anyone can help, it would be great. Thanks!

### Version

0.15-beta1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.231
  user: mqtt_frigate
  password: xxx
  enabled: true


detectors:
  rocm:
    type: rocm


model:
  model_type: yolonas
  path: plus://2dd01205132f082b04531f15399bdf5c

birdseye:
  enabled: true
  mode: motion

logger:
  logs:
    #frigate.record.maintainer: debug
    ffmpeg.Sonnette: debug

record:
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7
snapshots:
  enabled: true
  bounding_box: true

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - dog
    - deer
    - amazon
    - fedex
    - ups

telemetry:
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: true
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: true

detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 704
  height: 480
  stationary:
    interval: 50
    threshold: 50

<snipped camera definitions>
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1-rocm
    shm_size: "1507.50mb" # update for your cameras based on calculation above
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    devices:
      - /dev/dri
      - /dev/kfd
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config:/config
      - /home/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      - "5000:5000"
      - "8971:8971"
        #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: xxx
      PLUS_API_KEY: xxx
      LIBVA_DRIVER_NAME: radeonsi
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
```

### Relevant Frigate log output

```shell
frigate  | 2024-10-29 11:31:22.304251667  [INFO] Preparing Frigate...
frigate  | 2024-10-29 11:31:22.305090539  [INFO] Starting NGINX...
frigate  | 2024-10-29 11:31:22.307226536  [INFO] Starting Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-10-29 11:31:22.389465848  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-10-29 11:31:22.463190886  127.0.0.1 - - [29/Oct/2024:11:31:22 -0400] "" 400 0 "-" "-" "-"
frigate  | 2024-10-29 11:31:22.539557944  [INFO] Starting go2rtc...
frigate  | 2024-10-29 11:31:22.594232753  11:31:22.594 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-10-29 11:31:22.594237542  11:31:22.594 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-10-29 11:31:22.594815608  11:31:22.594 INF [api] listen addr=:1984
frigate  | 2024-10-29 11:31:22.594975366  11:31:22.594 INF [rtsp] listen addr=:8554
frigate  | 2024-10-29 11:31:22.595376433  11:31:22.595 INF [webrtc] listen addr=:8555/tcp
frigate  | 2024-10-29 11:31:23.301540842  2024/10/29 11:31:23 [error] 169#169: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.231, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "frigate.local:5000"
frigate  | 2024-10-29 11:31:23.301562963  2024/10/29 11:31:23 [error] 169#169: *2 auth request unexpected status: 502 while sending to client, client: 192.168.1.231, server: , request: "GET /api/stats HTTP/1.1", host: "frigate.local:5000"
frigate  | 2024-10-29 11:31:23.490808731  [2024-10-29 11:31:23] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-10-29 11:31:23.521990859  [2024-10-29 11:31:23] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-10-29 11:31:24.286041088  [2024-10-29 11:31:24] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
frigate  | 2024-10-29 11:31:24.360365504  [2024-10-29 11:31:24] frigate.app                    INFO    : Starting Frigate (0.15.0-33825f6)
frigate  | 2024-10-29 11:31:24.362021687  [2024-10-29 11:31:24] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-10-29 11:31:24.362248540  [2024-10-29 11:31:24] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-10-29 11:31:24.372700571  [2024-10-29 11:31:24] frigate.app                    INFO    : Recording process started: 557
frigate  | 2024-10-29 11:31:24.372953221  [2024-10-29 11:31:24] frigate.app                    INFO    : Review process started: 566
frigate  | 2024-10-29 11:31:24.374157493  [2024-10-29 11:31:24] frigate.app                    INFO    : go2rtc process pid: 98
frigate  | 2024-10-29 11:31:24.394767497  [2024-10-29 11:31:24] detector.rocm                  INFO    : Starting detection process: 574
frigate  | 2024-10-29 11:31:24.395150380  [2024-10-29 11:31:24] frigate.app                    INFO    : Output process started: 591
frigate  | 2024-10-29 11:31:24.410379515  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Ouest-Nord-Est: 616
frigate  | 2024-10-29 11:31:24.418790967  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Ouest-Nord-Ouest: 623
frigate  | 2024-10-29 11:31:24.430685363  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Est-Sud-Est: 639
frigate  | 2024-10-29 11:31:24.436763680  [2024-10-29 11:31:24] frigate.detectors.plugins.rocm WARNING : AMD/ROCm: detected gfx1103 but HSA_OVERRIDE_GFX_VERSION already present (11.0.0), not overriding!
frigate  | 2024-10-29 11:31:24.437038702  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Sud-Sud-Est: 650
frigate  | 2024-10-29 11:31:24.438137769  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Est-Terrasse: 662
frigate  | 2024-10-29 11:31:24.444627782  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Est-Sud-Ouest: 671
frigate  | 2024-10-29 11:31:24.451686525  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Salle-Mecanique: 688
frigate  | 2024-10-29 11:31:24.458148958  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Sonnette: 700
frigate  | 2024-10-29 11:31:24.465110950  [2024-10-29 11:31:24] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: loaded migraphx module
frigate  | 2024-10-29 11:31:24.465268023  [2024-10-29 11:31:24] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: switching HIP to blocking mode to conserve CPU
frigate  | 2024-10-29 11:31:24.471214505  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Entree-Ouest: 711
frigate  | 2024-10-29 11:31:24.472216470  [2024-10-29 11:31:24] frigate.app                    INFO    : Camera processor started for Dehors-Garage-Gauche: 726
frigate  | 2024-10-29 11:31:24.474234828  Process detector:rocm:
frigate  | 2024-10-29 11:31:24.474236801  Traceback (most recent call last):
frigate  | 2024-10-29 11:31:24.474237893    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-10-29 11:31:24.474242642      self.run()
frigate  | 2024-10-29 11:31:24.474244185    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2024-10-29 11:31:24.474245087      return run(*args, **kwargs)
frigate  | 2024-10-29 11:31:24.474265004    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-10-29 11:31:24.474266106      self._target(*self._args, **self._kwargs)
frigate  | 2024-10-29 11:31:24.474267729    File "/opt/frigate/frigate/object_detection.py", line 109, in run_detector
frigate  | 2024-10-29 11:31:24.474268731      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-10-29 11:31:24.474269703    File "/opt/frigate/frigate/object_detection.py", line 61, in __init__
frigate  | 2024-10-29 11:31:24.474270584      self.detect_api = create_detector(detector_config)
frigate  | 2024-10-29 11:31:24.474299538    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-10-29 11:31:24.474301011      return api(detector_config)
frigate  | 2024-10-29 11:31:24.474324194    File "/opt/frigate/frigate/detectors/plugins/rocm.py", line 111, in __init__
frigate  | 2024-10-29 11:31:24.474325627      raise Exception(f"AMD/ROCm: unknown model format {path}")
frigate  | 2024-10-29 11:31:24.474327200  Exception: AMD/ROCm: unknown model format /config/model_cache/2dd01205132f082b04531f15399bdf5c
frigate  | 2024-10-29 11:31:24.480134122  [2024-10-29 11:31:24] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: loading model from /config/model_cache/2dd01205132f082b04531f15399bdf5c
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

I can't show this as my instance doesn't even come up. Here is the one when cpu's are enabled.

![Capture d’écran 2024-10-29 114908](https://github.com/user-attachments/assets/28fd2167-c091-426a-b11a-900dff514d60)

**Comment by NickM-27** [comment]
I'd suggest using onnx as the `type` instead of `rocm`

**Reply by lortiejp** [reply]
Hello and thanks for answering. I now get this:

> frigate  | 2024-10-29 13:12:10.378766684  MIGraphX Error: 
> 
>  /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/AMDMIGraphX/src/targets/gpu/hip.cpp:109: allocate_gpu: Memory not available to allocate buffer: 8
> 

 and then:

> frigate  | 2024-10-29 13:12:10.426178859  Process detector:onnx:
> frigate  | 2024-10-29 13:12:10.426179851  Traceback (most recent call last):
> frigate  | 2024-10-29 13:12:10.426180282    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
> frigate  | 2024-10-29 13:12:10.426180623      self.run()
> frigate  | 2024-10-29 13:12:10.426181013    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
> frigate  | 2024-10-29 13:12:10.426181364      return run(*args, **kwargs)
> frigate  | 2024-10-29 13:12:10.426181775    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
> frigate  | 2024-10-29 13:12:10.426182145      self._target(*self._args, **self._kwargs)
> frigate  | 2024-10-29 13:12:10.426182546    File "/opt/frigate/frigate/object_detection.py", line 109, in run_detector
> frigate  | 2024-10-29 13:12:10.426182937      object_detector = LocalObjectDetector(detector_config=detector_config)
> frigate  | 2024-10-29 13:12:10.426183348    File "/opt/frigate/frigate/object_detection.py", line 61, in __init__
> frigate  | 2024-10-29 13:12:10.426183718      self.detect_api = create_detector(detector_config)
> frigate  | 2024-10-29 13:12:10.426184129    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
> frigate  | 2024-10-29 13:12:10.426184430      return api(detector_config)
> frigate  | 2024-10-29 13:12:10.426184820    File "/opt/frigate/frigate/detectors/plugins/onnx.py", line 44, in __init__
> frigate  | 2024-10-29 13:12:10.426185171      self.model = ort.InferenceSession(
> frigate  | 2024-10-29 13:12:10.426185642    File "/usr/local/lib/python3.9/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
> frigate  | 2024-10-29 13:12:10.426186063      self._create_inference_session(providers, provider_options, disabled_optimizers)
> frigate  | 2024-10-29 13:12:10.426186554    File "/usr/local/lib/python3.9/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 483, in _create_inference_session
> frigate  | 2024-10-29 13:12:10.426186954      sess.initialize_session(providers, provider_options, disabled_optimizers)
> frigate  | 2024-10-29 13:12:10.426203285  onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: Failed to call function
> 

Thanks again!

**Reply by NickM-27** [reply]
The GPU does not have enough memory allocated, you'll need to increase this in the BIOS

**Reply by lortiejp** [reply]
That's an annoyance. The A8 doesn't have this option in the bios. Do I need to go around this?

**Reply by lortiejp** [reply]
Ok. After researching more, I found this: https://winstonhyypia.medium.com/amd-apu-how-to-modify-the-dedicated-gpu-memory-e27b75905056 which guides you through changing this option from a generic bios utility. You also need to upgrade your Linux kernel to above 6.9.9 apparently (I did this too.) With this value changed, the onnx detector started successfuly.

**Reply by lortiejp** [reply]
...except now, it doesn't detect anything. Is there a way to debug this? Thanks for your help!

**Reply by NickM-27** [reply]
what is your current config?

**Reply by lortiejp** [reply]
I changed the detector section:

> detectors:
>   onnx:
>     type: onnx

And model:

> model:
>   path: plus://2dd01205132f082b04531f15399bdf5c
> 

The rest is unchanged from what I posted above. Thanks!

**Reply by lortiejp** [reply]
I also added this:

```
logger:
  logs:
    frigate.detector: debug
    detector.onnx: debug
```
But I only get a message telling me the model is loaded. Nothing else...
