### DISCUSSION TITLE
[Detector Support]:  Tensorrt not detecting anything but CPU detecting

### DISCUSSION THREAD

**Discussion by tet024** [blakeblackshear/frigate#14663] [Detector Support] [answered]
### Describe the problem you are having

Hello,

I am experiencing issues with object detection in Frigate using TensorRT. The Nvidia GeForce GTX 1050 Ti is correctly detected by Frigate, and the hardware acceleration with FFmpeg (preset-nvidia-h265) is configured. However, when I enable TensorRT for object detection with either the yolov4-416.trt or yolov4-tiny models, no detections occur. When I switch to CPU detection by commenting out the TensorRT configuration, everything works flawlessly—motion is detected, and bounding boxes correctly appear around objects like people and dogs.

# detectors:
#  tensorrt:
#    type: tensorrt
#    device: 0
#model:
#  path: /config/model_cache/tensorrt/yolov4-416.trt
#  input_tensor: nhwc
#  input_pixel_format: rgb
#  width: 416
#  height: 416

### Version

0.14 - UNRAID

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.x
  user: xxxxxxx
  password: xxxxxxx
  topic_prefix: frigate


detectors:
  tensorrt:
    type: tensorrt
    device: 0
#  cpu:
#    type: cpu 

model:
  path: /config/model_cache/tensorrt/yolov4-416.trt
  input_tensor: nhwc
  input_pixel_format: rgb
  width: 416
  height: 416

ffmpeg:
  hwaccel_args: preset-nvidia-h265


cameras:
  frontdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.3:554/
          roles:
            - detect
            - record
    zones: {}
    review: {}
    motion:
      threshold: 34
      contour_area: 10
      improve_contrast: 'true'
  terrace:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.2:8554/profile0 
          roles:
            - rtmp
            - record
            - detect
    zones: {}
    review: {}
    motion:
      threshold: 20
      contour_area: 22
      improve_contrast: 'true'
objects:
  track:
    - person
    - cat
    - dog
    - car
    - bicycle
    - bird
detect:
  width: 2304
  height: 1296
  fps: 5
  stationary:
    interval: 10

record:
  enabled: true
  expire_interval: 10080
  retain:
    days: 2
    mode: all

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    # Retention days
    default: 10
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
UNRAID
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker CLI

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

n/a
