### DISCUSSION TITLE
Min score ignored? False positives

### DISCUSSION THREAD

**Discussion by thomasfals** [blakeblackshear/frigate#14677] [Ask A Question]
Hi
I'm struggling with a lot of false positives. I have set min_score but still get detections that are below both min_score and threshold. What is wrong with my config?

Last night I got an alarm trigger for a "person" at 51% score. 

```
mqtt:
  host: redacted.12
  user: redacted
  password: redacted

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

objects:
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      threshold: 0.82
      min_score: 0.75
    cat:
      threshold: 0.8
go2rtc:
  streams:
    olivia:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103
    front:
      - rtsp://redacted:redacted@redacted554/Streaming/Channels/103
    side:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103
    side_2:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103
    back:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103
    garden:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103
    utility:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103
    carport:
      - rtsp://redacted:redacted@redacted:554/Streaming/Channels/103

cameras:
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 0,201,287,102,283,38,479,0,0,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: true
      events:
        retain:
          default: 10
  olivia:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 860,0,948,0,1215,66,1213,94
            - 980,720,1021,614,1006,591,975,564,942,545,923,530,903,520,871,531,836,576,847,614,813,609,786,633,741,679,720,720
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10

  front:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 0,238,337,222,357,291,473,272,445,230,607,246,895,298,1050,360,1147,406,1208,450,1280,342,1280,0,0,0
        cat:
          mask:
            - 0,238,337,222,357,291,473,272,445,230,607,246,895,298,1050,360,1147,406,1208,450,1280,342,1280,0,0,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10
    motion:
      mask:
        - 1280,247,1280,317,1210,461,1146,418,1099,398,1050,360,1016,340,991,306,938,294,904,277,863,266,651,232,603,228,446,218,438,252,458,281,363,286,337,208,306,197,164,214,0,222,0,176,0,0,1280,0
  back:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 122,450,87,301,74,122,0,120,0,720,259,720
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10
    motion:
      mask:
        - 322,220,166,558,256,720,808,720,903,502

  side_2:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10

  utility:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10

  carport:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: true
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 928,0,563,0,571,25,922,99
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10
    motion:
      mask:
        - 539,0,544,24,914,104,932,0

  side:
    ffmpeg:
      inputs:
        - path: rtsp://redacted
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          mask:
            - 473,0,473,111,537,108,542,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 10
version: 0.14

```

**Comment by NickM-27** [comment]
Need to see an example of detections below the min score

**Reply by thomasfals** [reply]
![Screenshot 2024-10-30 at 16 41 25](https://github.com/user-attachments/assets/206d783b-ed6b-47ba-982d-099ad317195e)
This was scored as person with 51%

But is the point of the min score not to discard this totally? In my case I set min score to 0.75

**Reply by NickM-27** [reply]
how do you know it scored as 51%? if you have object metadata it would be great to see all of it

**Reply by thomasfals** [reply]
Where would I find this metadata? It does not appear to be readily available in the interface.

**Reply by NickM-27** [reply]
Right, it is readily available in the next version of Frigate.

**Comment by thomasfals** [comment]
Here is another example. With these settings a 71% score should not trigger right?

```
filters:
    person:
      threshold: 0.82
      min_score: 0.75
```
![Screenshot 2024-11-05 at 11 37 34](https://github.com/user-attachments/assets/9be2bfab-bed9-4641-aa3f-1587de551c66)
