### DISCUSSION TITLE
Cant send new images to Frigate+[Support]:

### DISCUSSION THREAD

**Discussion by oskarax** [blakeblackshear/frigate#14710] [General Support]
### Describe the problem you are having

I was having Frigate + set up and working and i have untill now sent 157 images. But from nowhere it stopped working. I have checked my logs and its related to api key and network connections. I have updated the api key and i can ping google.com from the container. I have erased my passwords and API-key in the config file. I cant ping api.frigate.video from anywhere.

### Version

 0.14.1-

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.23
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mitt-frigate
  password: .......
  stats_interval: 60

ui:
  time_format: 24hour

go2rtc:
  webrtc:
    candidates:
      - 192.168.10.168:5000
      - stun.l.google.com:19302  # Public STUN server
  streams:
    balkongen_main:
      - rtsp://root:.....@192.168.10.136:554/axis-media/media.amp?streamprofile=ACC_High_B8A44F9495C8_0
    balkongen_sub:
      - rtsp://root:.....@192.168.10.136:554/axis-media/media.amp?streamprofile=ACC_Low_B8A44F9495C8_0

#ACC_High_B8A44F9495C8_0
#ACC_Low_B8A44F9495C8_0

cameras:
  Axis:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://192.168.10.168:8554/balkongen_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.10.168:8554/balkongen_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - dog
        - cat

    motion:
      mask: 0.696,0.958,0.698,0.997,1,1,1,0.958
live:
  stream_name: balkongen_main

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 3
      mode: active_objects
      objects:
        dog: 3
        car: 3
        person: 3
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 3

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - cat
      - dog
  



detectors:
  cpu1:
    type: cpu

version: 0.14
camera_groups:
  Balkongen:
    order: 1
    icon: LuCloudSun
    cameras: Axis
  Översikt:
    order: 2
    icon: LuTally4
    cameras: birdseye




Container config:
[Unit]
Description=Frigate service
After=go2rtc.service
After=create_directories.service
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
Environment=PLUS_API_KEY=...........................
ExecStartPre=+rm /dev/shm/logs/frigate/current
ExecStart=/bin/bash -c "bash /opt/frigate/docker/main/rootfs/etc/s6-overlay/s6-rc.d/frigate/run 2> >(/usr/bin/ts '%%Y-%>
StandardOutput=file:/dev/shm/logs/frigate/current
StandardError=file:/dev/shm/logs/frigate/current

[Install]
WantedBy=multi-user.target
```

### Relevant Frigate log output

```shell
quests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.frigate.video', port=443): Max retries exceeded with url: /v1/auth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b84dbc1fdf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

raise ConnectionError(e, request=request)
```

### Relevant go2rtc log output

```shell
Not needed
```

### FFprobe output from your camera

```shell
Not needed
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
I am not sure. Its a LXC container in Proxmox.
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Axis
