### DISCUSSION TITLE
[Detector Support]: Facial recognition with distant face on 4k camera

### DISCUSSION THREAD

**Discussion by USER19464727** [blakeblackshear/frigate#14725] [Detector Support] [answered]
### Describe the problem you are having

I have Frigate installed on HAOS. I got facial recognition working via double-take and codeproject.ai. However, one of my cameras is a 4k wide view camera. Faces are identifiable on the full-resolution image, but despite my best efforts I cannot seem to get a true full-res image to codeproject.ai. I have tried turning off the "crop" option for snapshots and mqtt and set the height to the full height of the camera (2160). I see in the double-take logs that an image comes in but the face wasn't recognized and I can tell it's because it's too blurry since it's a small ROI on a lower-resolution image. Can someone give me some guidance?

Frigate config:
```
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: false
  height: 2160
cameras:
  cam2:
    mqtt:
      crop: false
      height: 2160
```

Double-take config:
```
frigate:
  attempts:
    latest: 10
    snapshot: 10
    mqtt: true
  image:
    height: 2160
```

Home assistant config:
```
image_processing:
  - platform: codeproject_ai_object
      scale: 1.0
      roi_x_min: 0
      roi_y_min: 0
      roi_x_max: 1
      roi_y_max: 1
      crop_to_roi: False
```

### Version

Latest for each as of 11/1/2024

### Frigate config file

```yaml
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: false
  height: 2160
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

Not important for this
