### DISCUSSION TITLE
[Config Support]: additional config needed for macOS M1 docker install/setup?

### DISCUSSION THREAD

**Discussion by ronbruins** [blakeblackshear/frigate#14735] [Config Support] [answered]
### Describe the problem you are having

I have setup my MacBook Air M1 and was able to get frigate up and running. Do I / Can I configure anything that allows me make a better use of the resources? like GPU usage or neural engine?

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.35
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: **********
  password: **********

# logger:
#   # Optional: default log level (default: shown below)
#   default: debug
tls:
  enabled: false

ui:
  time_format: 24hour
  date_style: short


go2rtc:
  log:
    format: text
    level: error
    #exec: trace
  streams:
    deurbel:
      - rtsp://*****:******@192.168.1.148:554/h264Preview_01_main
      - ffmpeg:achter#audio=opus

detectors:
  cpu1:
    type: cpu
model:
  path: plus://**********
  labelmap:
    16: Kat

snapshots:
  enabled: true
  retain:
    default: 1

detect:
  enabled: true # <---- turn on detection

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 7
      mode: motion

objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package
  filters:
    cat:
      min_area: 3000
      threshold: 0.83
    dog:
      min_area: 3000
      threshold: 0.8
    person:
      min_area: 5500
      threshold: 0.8

cameras:
  deurbel:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/deurbel?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac -tag:v hvc1
    detect:
      width: 1280
      height: 960
    live:
      stream_name: deurbel
    motion:
      threshold: 75
      mask:
        - 0.216,0.548,0.294,0.525,0.296,0.431,0.214,0.43
        - 0.644,0.035,0.492,0.036,0.492,0.002,0.647,0
    objects:
      filters:
        car:
          mask:
            - 0.738,0.689,0.72,0.788,0.141,0.818,0.116,0.736,0.508,0.715
            - 0.736,0.425,0.743,0.623,0,0.642,0,0.476
        cat:
          mask: 0.004,0.005,0.002,0.204,0.234,0.221,0.283,0.008

    zones:
      Muurtje:
        coordinates: 0.124,0.938,0.336,0.999,0.341,0.925,0.149,0.892
        loitering_time: 0
        objects: cat
```

### Relevant Frigate log output

```shell
no log
```

### Relevant go2rtc log output

```shell
no log
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate_014B
    privileged: true # this may not be necessary for all setups
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-standard-arm64
    shm_size: "256mb" # update for your cameras based on calculation above

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/root/docker/frigate/config:/config
      - /var/root/docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      #ports:
      #- "5000:5000"
      #- "1984:1984"
      #- "8554:8554" # RTSP feeds
      #- "8555:8555/tcp" # WebRTC over tcp
      #- "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "*******"
      PLUS_API_KEY: "************"
```

### Object Detector

CPU (no coral)

**Comment by NickM-27** [comment, marked as answer]
The neural engine is used automatically with the CPU detector. It's impossible to use the GPU because docker on macos does not support device passthrough

**Reply by ronbruins** [reply]
> The neural engine is used automatically with the CPU detector. It's impossible to use the GPU because docker on macos does not support device passthrough 

So just the cpu detector should be enough, but do I need add more (cpu 2,3 ..) or will just one use all cores and threads?

**Reply by NickM-27** [reply]
depends if you have skipped fps, the default should be fine for 6 cameras or so, otherwise can just add another cpu detector

**Reply by ronbruins** [reply]
Ok and last but not least, I read that the M1 is powerful enough to handle frigate (I have 4 cameras) without using a coral? Would it (could it) make sense to split up, to put go2rtc on one machine(M1) and the frigate on another (Linux)and then using the coral on that one? Or would all on the m1 be fine?

**Reply by NickM-27** [reply]
all on m1 should be fine

**Comment by deadrubberboy** [comment]
I’m going same on m1 MacMini.  How do I add a cpu? I have 6 cams and dropping frames.

**Reply by ronbruins** [reply]
Add another cpu detector. I tried 4 detectors and they all stayed below 10ms however I'm currently testing some other ways, running go2rtc on the m1 and frigate on the former with the coral. This I have best of both worlds and it seems to work perfectly fine. But even so, it was running very well on the M1 with 4 cpu detectors configured.

**Reply by deadrubberboy** [reply]
Understood. I'd rather avoid buying a coral since they are 4 years outside of support already. I've also heard, like you say that the M chips can handle it well. Side note: Scrypted even specifically recommends M over Coral for their pay version.

What / where do I add a CPU? Is it in the docker yaml or frigate config? I'm not sure of the syntax etc. 

Thank you for your reply!

**Reply by ronbruins** [reply]
https://docs.frigate.video/configuration/object_detectors

And see the full reference config. 

I had this:

```
detectors:
  cpul:
    type: cpu
  cpu2:
    type: cpu
  срu3:
    type: cpu
  срu4:
    type: срu
```
