### DISCUSSION TITLE
[Support]: Dev-Container setup | s6-rc error

### DISCUSSION THREAD

**Discussion by IxcheI** [blakeblackshear/frigate#14736] [General Support]
### Describe the problem you are having

Hi, I'm trying to run a dev-container so I can properly edit and test code on my system, I got my dev-container to build and run in docker but I'm being stopped by this error: 
`s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/certsync/type: must be oneshot, longrun, or bundle`

How I got there:
1. Git cloned the dev branch and set up a basic compose file. 
2. Since I'm on windows I got complains about line endings which this quick command fixed 
`find . -type f -name "*.sh" -print0 | xargs -0 dos2unix` (run via git bash)
3. Then ran `docker-compose -f docker-compose.dev.yml up -d` (custom yml).

I verified that the file exists and that it contains `longrun`, no issues there.
I'm accessing frigate via its 5000 port so I don't think I need certification stuff to work.

### Version

dev branch

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt5
  port: 1883

tls:
  enabled: False

go2rtc:
  streams:
    back:
      - rtsp://stream

review:
  alerts:
    labels:
      #- person
      - cat
      - fox
      - bird
      - dog
  detections:
    labels:
      - person

cameras:
  back:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 
            rtsp://stream
          roles:
            - detect
        - path: 
            rtsp://stream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      # width: 640
      # height: 480
      enabled: true
      # fps: 10
      max_disappeared: 100
      stationary:
        # threshold: 100
        max_frames:
          default: 3000
      annotation_offset: -600
    objects:
      track:
        - person
        - dog
        - fox
        - cat
        - bird ##
      filters:
        cat:
          min_score: 0.2
          threshold: 0.4
        bird:
          min_score: 0.2
          threshold: 0.4
        dog:
          min_score: 0.2
          threshold: 0.4
    snapshots:
      enabled: true
    record:
      enabled: true
    motion:
      mask: 0.695,0.046,0.97,0.045,0.969,0.095,0.695,0.095
      threshold: 50
      contour_area: 10
      improve_contrast: true

    zones: {}

record:
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 20
  detections:
    retain:
      days: 7
  sync_recordings: false

snapshots:
  enabled: true
  clean_copy: false
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 20
  quality: 90


detectors:
  onnx_0:
    type: onnx
    device: GPU
model:
  model_type: yolonas
  labelmap_path: /trt-models/labelmap.txt
  path: /trt-models/yolov7x_custom_best.onnx
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

# detectors:
#   tensorrt:
#     type: tensorrt
#     device: 0
# model:
#   # path: /trt-models/yolov7x_custom_best_fp16.trt
#   path: /trt-models/yolov7x-640.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 640
#   height: 640

version: 0.15-0
```

### Relevant Frigate log output

```shell
s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/certsync/type: must be oneshot, longrun, or bundle
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Install method

Windows WSL2

### docker-compose file or Docker CLI command

```yaml
version: "3.3"
services:
  devcontainer:
    container_name: frigate-devcontainer
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: devcontainer
    volumes:
      - \\wsl$$\Ubuntu\etc\localtime:/etc/localtime:ro
      - C:\Users\Leo\frigate\config:/config
      - C:\Users\Leo\frigate\clips:/media/frigate
      - C:\Users\Leo\frigate\trt-models:/trt-models:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5005:5000"
```

### Object Detector

Other

### Network connection

Wired

### Camera make and model

Dahua
