### DISCUSSION TITLE
[Config Support]: Stream HLS to Google Nest Hub

### DISCUSSION THREAD

**Discussion by tnemrap** [blakeblackshear/frigate#14747] [Config Support]
### Describe the problem you are having

I have searched for an solution to stream to Google Nest Hub but has not find any that works.
In openHab  i run  `ffmpeg -hide_banner -loglevel warning -rtsp_transport tcp -i rtsp://admin:XXXXXX@192.168.192.82/Streaming/channels/101 -strict -2 -f lavfi -i aevalsrc=0 -acodec aac -vcodec copy -hls_flags delete_segments -hls_time 2 -hls_list_size 4 /etc/openhab/html/camera/pool.m3u8

Then i can cast this to Nest Hub. http//openhab:8080/camera/pool.m3u8`
How can i implement this into Frigate (or go2rtc)

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: false
  # Required: host name
  host: mosquitto
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate

logger:
  # Optional: default log level (default: shown below)
  default: info

objects:
    # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - bicycle
    - door

go2rtc:

  streams:
    terrace:
      - rtsp://admin:Gaston35@192.168.192.84/Streaming/channels/101#video=copy#audio=aac
      - ffmpeg:terrace#audio=aac
      - isapi://admin:Gaston35@192.168.192.84:80/
    terrace_sub:
      - rtsp://admin:Gaston35@192.168.192.84/Streaming/channels/102
      - isapi://admin:Gaston35@192.168.192.84:80/
    terrace_hls: 
    - "ffmpeg:rtsp://admin:Gaston35@192.168.192.84/Streaming/channels/101#video=h264#audio=opus#width=1920#height=1080"

    front:
      - rtsp://admin:Gaston35@192.168.192.82/Streaming/channels/101#video=copy#audio=aac #2688x1520
      - ffmpeg:front#audio=aac
    front_sub:
      - rtsp://admin:Gaston35@192.168.192.82/Streaming/channels/102 #640x360
      - isapi://admin:Gaston35@192.168.192.82:80/
    front_hls: 
    - "ffmpeg:rtsp://admin:Gaston35@192.168.192.82/Streaming/channels/101#video=h264#audio=opus#width=1920#height=1080"

    pool:
      - rtsp://admin:Gaston35@192.168.192.86/Streaming/channels/101#video=copy#audio=aac #2688x1520
      - isapi://admin:Gaston35@192.168.192.86:80/
      - ffmpeg:pool#audio=aac
    pool_sub:
      - rtsp://admin:Gaston35@192.168.192.86/Streaming/channels/102 #640x360
      - isapi://admin:Gaston35@192.168.192.86:80/


  webrtc:
    candidates:
      - 192.168.192.22:8555
      - stun:8555


ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  terrace: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrace?video&audio # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
#        - path: rtsp://192.168.192.22:8554/terrace_sub # <----- The stream you want to use for detection
#          roles:
#            - detect

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 2048
      height: 1536
      stationary:
        interval: 1
        threshold: 50

    zones:
      Terrace_Area:
        coordinates: 0.994,0.118,0,0.125,0.003,0.995,0.999,0.993
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.026,0.044,0.026,0.109,0.486,0.104,0.487,0.048

      threshold: 30
      contour_area: 20
      improve_contrast: 'true'

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        objects:
          cat: 2

    objects:

      track:
        - cat
        - person
      filters:
        cat: 
          min_score: 0.3 # 0.5 default
          threshold: 0.5 # 0.7 default
        person:
          mask: 0.004,0.342,0.057,0.332,0.092,0.48,0.003,0.501
      mask:
        - 0.337,0.368,0.339,0.244,0.251,0.224,0.246,0.305
        - 0.621,0.282,0.617,0.383,0.719,0.399,0.721,0.291
    review:
      detections: {}

  front: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video&audio # <----- The stream you want to use for detection
          roles:
            - record
            - audio
            - detect
#        - path: rtsp://127.0.0.1:8554/front_sub # <----- The stream you want to use for detection
#          roles:
#            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 2688
      height: 1520
      stationary:
        interval: 1
        threshold: 50
    zones:
      Door:
        coordinates: 0.008,0.109,0.234,0.104,0.243,0.513,0.008,0.603
        loitering_time: 0
        inertia: 3
      Garage:
        coordinates: 0.788,0.346,0.8,0.133,0.494,0.065,0.486,0.223
        loitering_time: 0
        inertia: 3
      Bilar:
        coordinates: 1,0.428,1,0.334,0.8,0.245,0.795,0.327
        loitering_time: 0
        inertia: 3
      FrontArea:
        coordinates: 0,0,1,0,0.997,0.995,0,1
        loitering_time: 0
        inertia: 3
    objects:
      mask: 
        0.797,0,0.365,0,0,0,0,0.198,0.365,0.147,0.493,0.062,0.777,0.124,0.77,0.232,1,0.342,1,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        objects:
          person: 2
    motion:
      mask: 0.035,0.046,0.331,0.044,0.332,0.095,0.033,0.099
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'

  pool: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool?video&audio # <----- The stream you want to use for detection
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/pool_sub # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 360
      stationary:
        interval: 1
        threshold: 50
        
    objects:
      mask: 1,0,1,0.209,0.82,0.373,0.609,0.275,0.474,0.237,0.474,0.013
      track:
        - cat
        - person
    motion:
      mask:
        - 0.037,0.044,0.334,0.044,0.333,0.095,0.037,0.099
        - 0.472,0.23,0.473,0,0.995,0.002,0.997,0.211,0.82,0.368
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 5
      mode: motion

# default lightning_threshold:
motion:
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.7

  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30

  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10

ui:
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%Y-%m-%d %H:%M'
timestamp_style:
      # Optional: Position of the timestamp (default: shown below)
      #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
      position: "tl"
      # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
      #           Additional Examples:
      #             german: "%d.%m.%Y %H:%M:%S"
      format: "%Y-%m-%d %H:%M:%S TEST"
      # Optional: Color of font
      color:
        # All Required when color is specified (default: shown below)
        red: 255
        green: 255
        blue: 255
      # Optional: Line thickness of font (default: shown below)
      thickness: 2

version: 0.14
```

### Relevant Frigate log output

```shell
2024-11-03 00:42:17.306914  [INFO] Preparing Frigate...
2024-11-03 00:42:17.306993  [INFO] Starting Frigate...
2024-11-03 00:42:18.735810  [2024-11-03 00:42:18] frigate.app                    INFO    : Starting Frigate (0.14.1-)
2024-11-03 00:42:18.735916  [2024-11-03 00:42:18] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-03 00:42:18.783954  [2024-11-03 00:42:18] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-03 00:42:18.847750  [2024-11-03 00:42:18] peewee_migrate.logs            INFO    : Starting migrations
2024-11-03 00:42:18.848410  [2024-11-03 00:42:18] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-11-03 00:42:18.939800  [2024-11-03 00:42:18] frigate.app                    INFO    : Recording process started: 12273
2024-11-03 00:42:18.946224  [2024-11-03 00:42:18] frigate.app                    INFO    : Recording process started: 12279
2024-11-03 00:42:18.949357  [2024-11-03 00:42:18] frigate.app                    INFO    : go2rtc process pid: 126
2024-11-03 00:42:18.986086  [2024-11-03 00:42:18] detector.ov                    INFO    : Starting detection process: 12301
2024-11-03 00:42:18.987097  [2024-11-03 00:42:18] frigate.app                    INFO    : Output process started: 12303
2024-11-03 00:42:19.036752  [2024-11-03 00:42:19] frigate.app                    INFO    : Camera processor started for terrace: 12318
2024-11-03 00:42:19.068321  [2024-11-03 00:42:19] frigate.app                    INFO    : Camera processor started for front: 12319
2024-11-03 00:42:19.088533  [2024-11-03 00:42:19] frigate.app                    INFO    : Camera processor started for pool: 12322
2024-11-03 00:42:19.088646  [2024-11-03 00:42:19] frigate.app                    INFO    : Capture process started for terrace: 12341
2024-11-03 00:42:19.108832  [2024-11-03 00:42:19] frigate.app                    INFO    : Capture process started for front: 12349
2024-11-03 00:42:19.127018  [2024-11-03 00:42:19] frigate.app                    INFO    : Capture process started for pool: 12353
```

### Relevant go2rtc log output

```shell
2024-11-02 23:10:15.870603  [INFO] Preparing new go2rtc config...
2024-11-02 23:10:16.268011  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-11-02 23:10:16.320117  [INFO] Starting go2rtc...
2024-11-02 23:10:16.454602  23:10:16.454 INF go2rtc platform=linux/amd64 revision=8cca8de version=1.9.6
2024-11-02 23:10:16.454682  23:10:16.454 INF config path=/dev/shm/go2rtc.yaml
2024-11-02 23:10:16.455249  23:10:16.455 INF [rtsp] listen addr=:8554
2024-11-02 23:10:16.455321  23:10:16.455 INF [api] listen addr=:1984
2024-11-02 23:10:16.455697  23:10:16.455 INF [webrtc] listen addr=:8555
```

### Operating system

Debian

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
Not Used
```

### Object Detector

CPU (no coral)
