### DISCUSSION TITLE
Events missing in explore section

### DISCUSSION THREAD

**Discussion by jakeycrx** [blakeblackshear/frigate#14742] [General Support]
### Describe the problem you are having

Hi,

I switched to 0.15 beta a couple of days ago and it's a great improvement. The object life cycle is very useful.

Some objects aren't showing in the new explore section since the upgrade though. Cars don't show at all and only people from certain zones are shown. All cat/dog events are present though. I've double checked the filters and nothing is filtered out.

The last car events were prior to upgrading:

![image](https://github.com/user-attachments/assets/59eca4d5-872f-4168-8342-11d49f7470d5)

### Version

0.15.0-33825f6

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.160
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: ****
  stats_interval: 60

go2rtc:
  streams:
    reolink:
      - http://192.168.1.6/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****
    dahua:
      - rtsp://****:****@192.168.1.2:554/cam/realmonitor?channel=1&subtype=0
    dahua_sub:
      - rtsp://****:****@192.168.1.2:554/cam/realmonitor?channel=1&subtype=2
    front:
      - rtsp://****:****@192.168.1.4:554/Streaming/Channels/101
    front_sub:
      - rtsp://****:****@192.168.1.4:554/Streaming/Channels/103
    rear:
      - rtsp://****:****@192.168.1.5:554/Streaming/Channels/101
    rear_sub:
      - rtsp://****:****@192.168.1.5:554/Streaming/Channels/103
    e1:
      - http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****
    e1_sub:
      - http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=****&password=****

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://****

cameras:
  reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: 
            http://192.168.1.6/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****
          input_args: -avoid_negative_ts make_zero -analyzeduration 1000M -probesize
            1000M -rw_timeout "5000000"
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          max_ratio: 0.8
          min_score: 0.65
          threshold: 0.8
        cat:
          min_score: 0.6
          threshold: 0.75
        dog:
          min_score: 0.6
          threshold: 0.75
        car:
          mask:
            - 0.404,0.541,0.508,0.535,0.496,0.590,0.551,0.741,0.826,0.815,0.858,0.495,0.627,0.466,0.366,0.452,0.252,0.452,0.250,0.554
            - 0.134,0.667,0.169,0.855,0.233,0.793,0.246,0.718,0.249,0.664,0.250,0.598,0.227,0.559,0.198,0.531,0.164,0.516,0.130,0.503
    zones:
      car_detection:
        coordinates: 0.444,0.695,0.293,0.611,0.241,0.567,0.463,0.544,0.452,0.612
        objects:
          - car
      overall_detection:
        coordinates: 0.782,1,0.112,1,0.052,0.353,0.845,0.359,0.85,0.535,0.833,0.765
        inertia: 1
        objects:
          - cat
      overall_detection_2:
        coordinates: 0.782,1,0.112,1,0.052,0.353,0.845,0.359,0.85,0.535,0.833,0.765
        inertia: 1
        objects:
          - dog
      overall_detection_3:
        coordinates: 0.782,1,0.112,1,0.052,0.353,0.845,0.359,0.85,0.535,0.833,0.765
        inertia: 1
        objects:
          - person
      light_detection_reolink:
        coordinates: 
          0.789,1,0,1,0,0.626,0,0.395,0,0,0.187,0,0.158,0.209,0.132,0.415,0.127,0.517,0.136,0.586,0.145,0.617,0.238,0.623,0.307,0.613,0.417,0.606,0.461,0.601,0.664,0.629,0.725,0.626,0.782,0.606,0.786,0.544,0.861,0.546,0.857,0.603
        inertia: 1
        objects:
          - person
      Cat_Spotter_Reolink:
        coordinates: 
          0.214,0.509,0.441,0.497,0.608,0.495,0.609,0.56,0.528,0.565,0.425,0.575,0.214,0.595
        inertia: 1
        loitering_time: 0
        objects: cat
    motion:
      mask:
        - 0.835,0.76,0.847,0.543,0.844,0.43,0.706,0.445,0.555,0.401,0.139,0.354,0.146,0.129,0,0.125,0,0,1,0,1,1,0.815,1
        - 0,1,0.327,1,0.326,0.964,0,0.965
      threshold: 20
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      alerts:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
    snapshots:
      required_zones:
        - overall_detection
        - overall_detection_2
        - Cat_Spotter_Reolink
      enabled: true
      clean_copy: true
      retain:
        default: 5
        objects:
          cat: 90
          dog: 90
    review:
      alerts:
        labels:
          - cat
          - person
        required_zones:
          - overall_detection
          - light_detection_reolink
          - Cat_Spotter_Reolink
      detections:
        labels:
          - car
          - dog
          - person
        required_zones:
          - overall_detection_2
          - overall_detection_3
          - car_detection
    ui:
      order: 4
###################################dahua###################################                 
    detect:
      annotation_offset: -1000
  dahua:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://****:****@192.168.1.2:554/cam/realmonitor?channel=1&subtype=0
          input_args: -avoid_negative_ts make_zero -timeout 5000000 -buffer_size 10000K
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          max_ratio: 0.8
          min_score: 0.65
          threshold: 0.8
        cat:
          min_score: 0.6
          threshold: 0.75
          mask: 0.194,0.732,0.228,0.719,0.234,0.771,0.196,0.778
        dog:
          min_score: 0.6
          threshold: 0.75
        car:
          mask: 0,1,0,0.295,0.372,0.184,0.415,0.177,0.522,0.193,0.632,0.247,0.629,0,1,0.001,1,1
    detect:
      fps: 10
      annotation_offset: -1100
    zones:
      car_detection_dahua:
        coordinates: 
          0.279,0.192,0.034,0.238,0.024,0,0.480,0,0.611,0,0.615,0.192,0.509,0.158,0.405,0.154
        objects:
          - car
      overall_detection_dahua:
        coordinates: 0,1,1,1,1,0,0,0
        inertia: 1
        objects:
          - cat
          - dog
      light_detection_dahua:
        coordinates: 
          0.893,1,0.12,1,0.016,0.304,0.067,0.292,0.248,0.232,0.348,0.243,0.505,0.253,0.678,0.428,0.741,0.544,0.731,0.683
        inertia: 1
        objects:
          - person
          - cat
          - dog
    motion:
      mask: 0.832,0.99,0.97,0.991,0.969,0.9,0.904,0.904,0.904,0.948,0.871,0.948,0.833,0.949
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      alerts:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
    snapshots:
      required_zones:
        - overall_detection_dahua
      enabled: true
      clean_copy: true
      retain:
        default: 5
        objects:
          cat: 90
          dog: 90
    onvif:
      host: 192.168.1.2
      port: 80
      user: ****
      password: ****
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: relative
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.3
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          - cat
          - dog
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - light_detection_dahua
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
        # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
        movement_weights: 0.08, 1.0, 1.1915912628173828, 1.4895845510626349, 0.3264420809284335
    review:
      alerts:
        labels:
          - cat
          - dog
          - person
        required_zones:
          - overall_detection_dahua
          - light_detection_dahua
      detections:
        labels:
          - car
        required_zones:
          - car_detection_dahua
    ui:
      order: 1
###################################front###################################            
  front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - car
        - cat
        - dog
        - person
      filters:
        car:
          min_score: 0.6
          threshold: 0.75
          mask: 
            0,0,1,0,0.998,0.996,0.823,0.996,0.658,0.304,0.576,0.135,0.492,0.118,0.314,0.12,0.33,0.322,0.242,0.334,0.146,0.707,0.203,0.729,0.291,0.997,0,1
        cat:
          min_score: 0.6
          threshold: 0.75
          mask:
            - 0.216,0.289,0.246,0.292,0.263,0.37,0.214,0.413
            - 0.704,0.763,0.728,0.769,0.728,0.804,0.702,0.804
            - 0.456,0.317,0.491,0.311,0.499,0.383,0.457,0.383
            - 0.87,0.403,0.897,0.421,0.897,0.454,0.869,0.439
        dog:
          min_score: 0.6
          threshold: 0.75
        person:
          max_ratio: 0.8
          min_score: 0.65
          threshold: 0.8
    detect:
      fps: 8
      annotation_offset: -1000
    zones:
      overall_detection_front:
        coordinates: 0,1,1,1,1,0,0,0
        inertia: 1
        objects:
          - cat
      overall_detection_front_2:
        coordinates: 0,1,1,1,1,0,0,0
        inertia: 1
        objects:
          - dog
      Light_Detection_Front:
        coordinates: 
          0.116,0.723,0.229,0.295,0.322,0.266,0.324,0.325,0.458,0.309,0.574,0.301,0.67,0.307,0.734,0.323,0.808,0.365,0.873,0.425,0.935,0.507,1,0.63,1,1,0.042,1
        inertia: 1
        objects:
          - person
          - cat
          - dog
        loitering_time: 0
      Cat_Spotter_Front:
        coordinates: 0.306,0,0.322,0.196,0.658,0.173,0.778,0.192,0.917,0.231,1,0.268,1,0
        inertia: 1
        loitering_time: 0
        objects: cat
      Car_Light_Detection_Front:
        coordinates: 
          0.227,0.404,0.434,0.38,0.688,0.381,0.724,0.549,0.782,0.814,0.814,0.975,0.298,0.975,0.208,0.716,0.144,0.708
        inertia: 1
        loitering_time: 0
        objects: car
    motion:
      mask: 0,0.984,0.274,0.987,0.273,0.94,0.183,0.939,0.127,0.939,0.042,0.942,0,0.94
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      alerts:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
    snapshots:
      required_zones:
        - Cat_Spotter_Front
        - overall_detection_front
        - overall_detection_front_2
      enabled: true
      clean_copy: true
      retain:
        default: 5
        objects:
          cat: 90
          dog: 90
    review:
      alerts:
        labels:
          - cat
          - dog
          - person
        required_zones:
          - Cat_Spotter_Front
          - overall_detection_front
          - Light_Detection_Front
      detections:
        labels:
          - dog
        required_zones:
          - overall_detection_front_2
    ui:
      order: 2
###################################rear###################################                    
  rear:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rear
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - cat
        - dog
      filters:
        cat:
          max_area: 12500
          min_score: 0.6
          threshold: 0.75
        dog:
          min_score: 0.6
          threshold: 0.75
    detect:
      fps: 6
    zones:
      overall_detection_rear:
        coordinates: 0,1,1,1,1,0,0,0
        inertia: 1
        objects:
          - cat
      overall_detection_rear_2:
        coordinates: 0,1,1,1,1,0,0,0
        inertia: 1
        objects:
          - dog
      Spotter_Left:
        coordinates: 
          0.114,0.337,0.24,0.304,0.36,0.272,0.446,0.451,0.54,0.637,0.662,0.885,0.719,1,0.197,1,0.165,0.834,0.122,0.497
        inertia: 1
        loitering_time: 0
        objects: cat
      Spotter_Right:
        coordinates: 
          0.372,0.274,0.559,0.25,0.569,0.193,0.761,0.449,0.999,0.768,1,1,0.727,0.999,0.528,0.594,0.436,0.416
        inertia: 1
        loitering_time: 0
        objects: cat
      Cat_Spotter_Street_Rear:
        coordinates: 0.31,0,0.601,0,0.57,0.162,0.356,0.13
        inertia: 1
        loitering_time: 0
        objects: cat
      Cat_Detection_Rear:
        coordinates: 
          0.114,0.338,0.111,0.129,0.191,0.124,0.255,0.126,0.324,0.136,0.373,0.157,0.407,0.171,0.452,0.22,0.559,0.211,0.569,0.178,0.999,0.768,1,0.997,0.727,0.999,0.42,0.386,0.223,0.461,0.211,0.307
        inertia: 1
        loitering_time: 0
        objects: cat
    motion:
      mask:
        - 0.001,0.94,0.278,0.938,0.279,0.988,0,0.985
        - 0.112,0,0.108,0.269,0.11,0.44,0.135,0.692,0.191,1,0,1,0,0.003
      threshold: 20
      contour_area: 10
      improve_contrast: true
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      alerts:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 5
        pre_capture: 30
        post_capture: 30
    snapshots:
      required_zones:
        - overall_detection_rear
        - overall_detection_rear_2
      enabled: true
      clean_copy: true
      retain:
        default: 5
        objects:
          cat: 90
          dog: 90
    review:
      alerts:
        labels:
          - cat
        required_zones: overall_detection_rear
      detections:
        labels:
          - dog
        required_zones:
          - overall_detection_rear_2
    ui:
      order: 3
###################################e1###################################         
  e1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      input_args: preset-http-reolink
      inputs:
        - path: 
            http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****
          roles:
            - record
        - path: 
            http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=****&password=****
          roles:
            - detect
            - audio
    audio:
      enabled: true
      # Optional: Configure the amount of seconds without detected audio to end the event (default: shown 30)
      max_not_heard: 30
      # Optional: Configure the min rms volume required to run audio detection (default: 500)
      # As a rule of thumb:
      #  - 200 - high sensitivity
      #  - 500 - medium sensitivity
      #  - 1000 - low sensitivity
      min_volume: 200
      # Optional: Types of audio to listen for (default: shown below)
      listen:
        - speech
        - babbling
        - yell
        - groan
        - grunt
        - whistling
        - breathing
        - wheeze
        - snoring
        - gasp
        - pant
        - snort
        - cough
        - throat_clearing
        - sneeze
        - sniff
        - chewing
        - biting
        - gargling
        - burping
        - hiccup
      filters:
        speech:
          threshold: 0.5
        babbling:
          threshold: 0.5
        yell:
          threshold: 0.5
        groan:
          threshold: 0.5
        grunt:
          threshold: 0.5
        whistling:
          threshold: 0.5
        breathing:
          threshold: 0.5
        wheeze:
          threshold: 0.5
        snoring:
          threshold: 0.5
        gasp:
          threshold: 0.5
        pant:
          threshold: 0.5
        snort:
          threshold: 0.5
        cough:
          threshold: 0.5
        throat_clearing:
          threshold: 0.5
        sneeze:
          threshold: 0.5
        sniff:
          threshold: 0.5
        chewing:
          threshold: 0.5
        biting:
          threshold: 0.5
        gargling:
          threshold: 0.5
        burping:
          threshold: 0.5
        hiccup:
          threshold: 0.5
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      alerts:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
    onvif:
      host: 192.168.1.3
      port: 8000
      user: ****
      password: ****
      autotracking:
        enabled: false
    motion:
      mask:
        - 0.011,0.938,0.48,0.942,0.48,0.991,0.011,0.985
        - 0.835,0,0.833,0.184,1,0.728,1,0
      threshold: 20
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        labels: []
      detections:
        labels: []
    ui:
      order: 5
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.app: info

ui:
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 12hour
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: full

telemetry:
  # Optional: Configure system stats
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: true
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_****, cap_net_raw capabilities enabled.
    network_bandwidth: true
version: 0.15-0
camera_groups:
  Test:
    order: 1
    icon: LuBanana
    cameras:
      - dahua
      - reolink
      - e1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Various

**Comment by hawkeye217** [comment]
Without any filters, Explore will display all of the objects Frigate tracks. Footage will still be deleted according to your record retention policy, so if you are not seeing certain tracked objects, you'll want to check what objects are being categorized as alerts/detections and your retention policy for those alerts/detections.

**Reply by jakeycrx** [reply]
Cars are set as detections, but they don't show up in the explore section.

![image](https://github.com/user-attachments/assets/0aa7fb96-d862-4a57-a797-dd5ec19bd326)

**Reply by hawkeye217** [reply]
Are you looking at the grid view or the summary view in Explore? When you navigate to `http://frigate_ip:5000/explore?labels=car`, you should see all of the `car` tracked objects in Frigate's database.

**Reply by jakeycrx** [reply]
It's the same on both views

I've never been able to reach the Frigate URL for some reason:

![image](https://github.com/user-attachments/assets/6162a733-3917-45cb-8548-c384adb14f1a)

 I never have a problem reaching HA though
 
![image](https://github.com/user-attachments/assets/18fe6166-f999-4486-845e-dd98414d1ee7)

**Reply by hawkeye217** [reply]
If you're running the addon, you need to expose the port in the addon settings.

**Reply by jakeycrx** [reply]
It's the same:

![image](https://github.com/user-attachments/assets/9b0dabb9-ffca-41cf-b41f-06670d286eff)

**Reply by hawkeye217** [reply]
What is the output of `http://192.168.1.160:5000/api/events?labels=car`?

**Reply by hawkeye217** [reply]
And can you post a screenshot of the Review Item Details pane when you click on the gray chip on one of those car detections from your original screenshot?

**Reply by jakeycrx** [reply]
It was too big for pastebin!

https://drive.google.com/file/d/1VrQ9q7H3W06fteImKS7ptEWcBNLCtcOE/view?usp=sharing

**Reply by hawkeye217** [reply]
Also, when you click on one of those review items to watch it in History view (not just hovering over it), does it show you the full-res footage?

**Reply by jakeycrx** [reply]
This screen?

![image](https://github.com/user-attachments/assets/51e7cc1b-5501-46ff-aca5-5d3f6c56e094)

**Reply by hawkeye217** [reply]
> This screen?
> 
No, the Review Item Details screen from the Review page. Click on the chip for a Review Item under Detections.

**Reply by jakeycrx** [reply]
> Also, when you click on one of those review items to watch it in History view (not just hovering over it), does it show you the full-res footage?

I have the full res footage, but I do record continuously.

**Reply by hawkeye217** [reply]
> It was too big for pastebin!
> 
> https://drive.google.com/file/d/1VrQ9q7H3W06fteImKS7ptEWcBNLCtcOE/view?usp=sharing

The API is returning all of the car events, so that's good. Can you look at `http://192.168.1.160:5000/explore?labels=car` in incognito mode in your browser?

**Reply by jakeycrx** [reply]
> > This screen?
> 
> No, the Review Item Details screen from the Review page. Click on the chip for a Review Item under Detections.

I only have snapshots set to save for cats and dogs.

![image](https://github.com/user-attachments/assets/c21d8402-0c6a-4844-a450-112f23604ad3)

**Reply by hawkeye217** [reply]
That tells us what's going on. There are no `car` objects associated with that review item. You would see "Car" listed under "Objects".

**Reply by jakeycrx** [reply]
> > It was too big for pastebin!
> > https://drive.google.com/file/d/1VrQ9q7H3W06fteImKS7ptEWcBNLCtcOE/view?usp=sharing
> 
> The API is returning all of the car events, so that's good. Can you look at `http://192.168.1.160:5000/explore?labels=car` in incognito mode in your browser?

![image](https://github.com/user-attachments/assets/583a38d2-d486-4094-8d6b-dd9d5b9f1041)

**Reply by jakeycrx** [reply]
> That tells us what's going on. There are no `car` objects associated with that review item. You would see "Car" listed under "Objects".

Strange, it has saved it as an event though. Is that the expected behaviour?

**Reply by jakeycrx** [reply]
It's the same scenario for the missing people in the explore section as well

![image](https://github.com/user-attachments/assets/aa555dd3-b664-45ed-aa13-ec3264c31047)
![image](https://github.com/user-attachments/assets/f9301e94-1837-49ab-b33c-8078723a4594)

**Reply by hawkeye217** [reply]
Let's see what @NickM-27 says. There may be something around retention that he can explain.

**Reply by jakeycrx** [reply]
It does work for people in some zones

![image](https://github.com/user-attachments/assets/4c8dd93d-a055-4cf8-bc04-840220dcb923)
![image](https://github.com/user-attachments/assets/f2983ec8-7a13-42cf-8967-258c131ba558)
![image](https://github.com/user-attachments/assets/4f7c1556-ef32-446a-a762-d473df25c989)

**Reply by hawkeye217** [reply]
Right, you have those specified as `required_zones` in your alerts and detections config.

**Reply by hawkeye217** [reply]
So in your screenshot above that doesn't have any objects listed, `overall_detection_3` is the zone that was entered, but that zone is only set to track `person`.

**Reply by jakeycrx** [reply]
It seems to be objects that don't save snapshots that are also set as detections.

**Reply by hawkeye217** [reply]
I'm seeing something in dev that may be related to this. Do you enable/disable recordings for the cameras you're seeing this with?

**Reply by hawkeye217** [reply]
> It seems to be objects that don't save snapshots that are also set as detections.

To be clear, an object must have a clip or a snapshot associated with it to end up in Explore.

**Reply by jakeycrx** [reply]
> I'm seeing something in dev that may be related to this. Do you enable/disable recordings for the cameras you're seeing this with?

No disabling of recordings for the cameras in question.

> To be clear, an object must have a clip or a snapshot associated with it to end up in Explore.

They definitely have clips and show under detections.

**Reply by hawkeye217** [reply]
Ok, likely unrelated then.

Can you post a screenshot of your browser's dev tools network tab when accessing `http://192.168.1.160:5000/explore?labels=car`, specifically highlighting the "events?labels=car..." GET request? It would be good to see the response from that request.

**Reply by jakeycrx** [reply]
> Ok, likely unrelated then.
> 
> Can you post a screenshot of your browser's dev tools network tab when accessing `http://192.168.1.160:5000/explore?labels=car`, specifically highlighting the "events?labels=car..." GET request? It would be good to see the response from that request.

I'm on the network tab I'm not sure about the GET request though?

![image](https://github.com/user-attachments/assets/5692d47a-e3e1-47bc-8bc5-05bac583f925)

**Reply by hawkeye217** [reply]
You'll need to click "All", and then select the "events?labels=car..." from the Name column. Then, choose "Response" in the panel that appears.

**Reply by jakeycrx** [reply]
![image](https://github.com/user-attachments/assets/0a39d25c-01b3-41a7-936a-334c7332fd7b)

https://pastebin.com/T1nHeJY9

**Reply by hawkeye217** [reply]
The call is returning 25 tracked objects, just as it should. 

Are you seeing any errors in the console?

Can you copy the source code of the page itself after loading?

**Reply by jakeycrx** [reply]
I don't see any errors anywhere 

This is the source code from http://192.168.1.160:5000/explore?labels=car

https://pastebin.com/ATxLQxfR

**Reply by hawkeye217** [reply]
That paste is private, I can't view it

**Reply by hawkeye217** [reply]
I took the JSON returned from your API call and plugged it as a static object into the Frigate code. The Explore grid view is working correctly (without your thumbnails, of course).

But I better understand your issue now - you're not seeing *new* tracked objects appearing in Explore's `car` view since 31-Oct.

**Reply by jakeycrx** [reply]
Pastebin is pending moderation?

https://drive.google.com/file/d/18QiMFQ1yNr-mGznjoiWI4q5Q7q-onQE4/view?usp=sharing

I upgraded to 0.15 beta on 31 Oct

**Reply by hawkeye217** [reply]
Thanks. Nick and I will look at this more deeply, there might be something going on with the new retain config settings.

**Reply by jakeycrx** [reply]
No problem

**Reply by hawkeye217** [reply]
Can you do us a favor and enable debug logs for object processing?

```
logger:
  default: info
  logs:
    frigate.object_processing: debug
```

Then send the portion of the log when you see a review item generated but no tracked object in Explore, as well as a screenshot of the review item details that shows the time/score/zones.

I suppose you'll hit this pretty quickly because no new tracked objects have been generated in Explore for a bit.
