### DISCUSSION TITLE
[Camera Support]: Stuttering in live/playback; Via Reolink app no issues

### DISCUSSION THREAD

**Discussion by rpm5099** [blakeblackshear/frigate#14743] [Camera Support]
### Describe the problem you are having

I have an issue with my video stuttering, both live and recorded.  I have searched and read through every single issue and post on every site that could even be remotely related, tried every suggestion and configuration, and gotten nowhere.  I built this as a dedicated system specifically for security cameras, I'm not running it on proxmox or raspberry pi - it's a 20 core Intel i5 with 64GB of memory, GTX 1650 GPU, 2 coral TPU's and NVME hdd.  The OS is Ubuntu 22.04 and running docker compose 

I have several 4k Reolink Trackmix Wifi cameras connected via ethernet cable, only one is currently connected because I have not yet mounted the others outside.  Viewing the video via the web interface or from the Reolink desktop app the video looks fine, no stuttering at all.  This includes if I copy the saved video files off the SD card in the cameras.  I'm pretty much ruling out issues with the camera itself due to that (I sniffed the reolink app, but it must use some proprietary protocol on port 9000).

In addition, I am getting frequent crashes of ffmpeg for various reasons, probably related to all the settings changes I have been continually making.  I have not included those logs.  The crashes are mostly related to detect errors and "unable to read frames from ffmpeg process"

```
ffmpeg.reolinkbackyardtrackmix.detect ERROR   : [rtsp @ 0x5d059b6d9d40] RTP: PT=61: bad cseq 06c8e xpected=edc1
ffmpeg.reolinkbackyardtrackmix.detect ERROR   : [out_0_0 @ 0x5d059c6266c0] 100 buffers queued in out_0_0, something may be wrong. 
...
WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=rtsp://REMOVED@10.0.0.32:554/h264Preview_01_main  
WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=rtsp://REMOVED@10.0.0.32:554/h264Preview_01_sub
ERROR   : reolinkbackyardtrackmix: Unable to read frames from ffmpeg process.
ERROR   : reolinkbackyardtrackmix: Unable to read frames from ffmpeg process.
ERROR   : reolinkbackyardtrackmix: ffmpeg process is not running. exiting capture thread... 
```

I have to admit I'm pretty frustrated at this point, I can't proceed with adding additional cameras until I get this resolved.  I am not going to tolerate stuttering video.  Everyone has been very helpful in other posts here, hopefully I am just doing something dumb.  Thanks in advance.

### Version

System 0.14.1-f4f3cfa

### What browser(s) are you using?

Thorium Version 124.0.6367.218 (Official Build) (64-bit)

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.record: info
    frigate.event: info
    frigate.record.maintainer: info
    frigate.record.export: info
    peewee: info
    peewee.sqliteq: info
    frigate.events.maintainer: info
mqtt:
  enabled: false

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
version: 0.14

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -flags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - --flags
    - +genpts+discardcorrupt
    - -rw_timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'

go2rtc:
  streams:
    reolinkbackyardtrackmix:
      - rtsp://REMOVED@10.0.0.32:554/h264Preview_01_main
    reolinkbackyardtrackmix_sub:
      - rtsp://REMOVED@10.0.0.32:554/h264Preview_01_sub
telemetry:
  network_interfaces:
    - enp
  stats:
    intel_gpu_stats: true
    network_bandwidth: true

tls:
  enabled: false

detectors:
  coral_pci:
    type: edgetpu
    device: pci
  coral_usb:
    type: edgetpu
    device: usb

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 600
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8
birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous
  inactivity_threshold: 30
  layout:
    scaling_factor: 2.0

objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package
    - bear
    - bird
    - airplane
    - bicycle


record:
  enabled: true
  expire_interval: 1440
  sync_recordings: true
  retain:
    days: 30
    mode: all
  export:
    timelapse_args: -vf setpts=0.02*PTS -r 30
  preview:
    quality: high
  events:
    pre_capture: 60
    post_capture: 60

snapshots:
  enabled: true
  timestamp: true
  crop: False
  retain:
    default: 30
  quality: 100


cameras:
  reolinkbackyardtrackmix:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolinkbackyardtrackmix 
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/reolinkbackyardtrackmix_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 896
      height: 512
      fps: 5

    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0.001,0.003,0,0.391,0.043,0.444,0.039,0.508,0.051,0.542,0.116,0.566,0.188,0.535,0.262,0.51,0.304,0.482,0.322,0.429,0.323,0.367,0.339,0.341,0.384,0.326,0.427,0.297,0.465,0.21,0.495,0.153,0.498,0.096,0.5,0.016,0.501,0.003
        - 0.999,0.004,0.999,0.515,0.955,0.464,0.916,0.516,0.887,0.503,0.856,0.465,0.843,0.389,0.841,0.346,0.858,0.325,0.775,0.225,0.742,0.255,0.644,0.298,0.598,0.283,0.455,0.235,0.501,0.001
        - 0.085,0.998,0.15,0.822,0.224,0.802,0.314,0.812,0.373,0.84,0.401,0.901,0.413,0.999
        - 0.255,0.503,0.243,0.597,0.275,0.619,0.309,0.603,0.323,0.574,0.314,0.533,0.298,0.477
    live:
      stream_name: reolinkbackyardtrackmix
      height: 720 
      quality: 8
    onvif:
      host: 10.0.0.32
      port: 8000
      user: REMOVED
      password: REMOVED
      ignore_time_mismatch: true
    zones:
      coop:
        coordinates: 0.307,0.474,0.416,0.618,0.567,0.413,0.46,0.36,0.456,0.237,0.332,0.339
        loitering_time: 0
      pool:
        coordinates: 0.454,0.21,0.778,0.191,0.886,0.44,0.601,0.417,0.46,0.357
        loitering_time: 0
      swing:
        coordinates: 0.15,0.552,0.311,0.475,0.416,0.619,0.308,0.81,0.19,0.731
        loitering_time: 0
      shed:
        coordinates: 0.001,0.396,0.152,0.554,0.301,0.808,0.138,0.998,0.001,0.997
        loitering_time: 0
      yard:
        coordinates: 0.566,0.408,0.311,0.807,0.415,0.998,0.998,0.998,0.999,0.479,0.888,0.439
        loitering_time: 0
    review:
      detections:
        required_zones:
          - coop
          - pool
          - shed
          - swing
          - yard
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
x@frigate:~$ffprobe rtsp://REMOVED@10.0.0.32:554/h265Preview_01_main
ffprobe version N-71064-gd5e603ddc0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      59. 27.100 / 59. 27.100
  libavcodec     61.  9.100 / 61.  9.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Input #0, rtsp, from 'rtsp://REMOVED@10.0.0.32:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000563, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp


ffprobe rtsp://REMOVED@10.0.0.32:554/h264Preview_01_sub
ffprobe version N-71064-gd5e603ddc0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      59. 27.100 / 59. 27.100
  libavcodec     61.  9.100 / 61.  9.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Input #0, rtsp, from 'rtsp://REMOVED@10.0.0.32:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000313, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x512, 20 fps, 40 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp


#FFMPROBE ON EXPORTED VIDEO FILE
ffprobe reolinkbackyardtrackmix_dnaqix.mp4
ffprobe version N-71064-gd5e603ddc0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      59. 27.100 / 59. 27.100
  libavcodec     61.  9.100 / 61.  9.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'reolinkbackyardtrackmix_dnaqix.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:03:29.91, start: 0.000000, bitrate: 8465 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv), 3840x2160, 8392 kb/s, 25.01 fps, 90k tbr, 90k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 66 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
```

### Frigate stats

```json
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7140  100  7140    0     0   842k      0 --:--:-- --:--:-- --:--:--  871k
{
  "bandwidth_usages": {
    "96": {
      "bandwidth": 1011.6
    }
  },
  "cameras": {
    "reolinkbackyardtrackmix": {
      "audio_dBFS": -41.9649,
      "audio_rms": 261.339,
      "camera_fps": 5.1,
      "capture_pid": 437,
      "detection_enabled": true,
      "detection_fps": 2.6,
      "ffmpeg_pid": 454,
      "pid": 432,
      "process_fps": 5.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "105": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "106": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "0.5"
    },
    "115": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "158": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "161": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "162": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "315": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "333": {
      "cmdline": "sleep 9999",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "381": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "383": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "385": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "410": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "411": {
      "cmdline": "frigate.detector.coral_pci",
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "414": {
      "cmdline": "frigate.output       ",
      "cpu": "10.9",
      "cpu_average": "10",
      "mem": "0.2"
    },
    "431": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "432": {
      "cmdline": "frigate.process:reolinkbackyardtrackmix",
      "cpu": "17.9",
      "cpu_average": "17",
      "mem": "0.2"
    },
    "437": {
      "cmdline": "frigate.capture:reolinkbackyardtrackmix",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "438": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "4.4",
      "cpu_average": "4",
      "mem": "0.0"
    },
    "441": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.2",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "454": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/reolinkbackyardtrackmix_sub -r 5 -vf fps=5,scale_cuda=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.0",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "484": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/reolinkbackyardtrackmix -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/reolinkbackyardtrackmix@%Y%m%d%H%M%S%z.mp4",
      "cpu": "3.5",
      "cpu_average": "2",
      "mem": "0.0"
    },
    "485": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/reolinkbackyardtrackmix -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.0"
    },
    "663": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(46)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "7174": {
      "cmdline": "frigate.detector.coral_usb",
      "cpu": "2.7",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "7898": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "86": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "96": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "8.3",
      "cpu_average": "8",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "3.3",
      "mem": "4.5"
    }
  },
  "detection_fps": 2.6,
  "detectors": {
    "coral_pci": {
      "detection_start": 0,
      "inference_speed": 8.47,
      "pid": 411
    },
    "coral_usb": {
      "detection_start": 0,
      "inference_speed": 10.24,
      "pid": 7174
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 1650": {
      "dec": "1.0%",
      "enc": "0.0%",
      "gpu": "0.0%",
      "mem": "7.25%"
    }
  },
  "processes": {
    "audio_detector": {
      "pid": 441
    },
    "go2rtc": {
      "pid": 96
    },
    "logger": {
      "pid": 381
    },
    "recording": {
      "pid": 383
    },
    "review_segment": {
      "pid": 385
    }
  },
  "service": {
    "last_updated": 1730576906,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 4092.5,
        "mount_type": "tmpfs",
        "total": 4096,
        "used": 3.5
      },
      "/media/frigate/clips": {
        "free": 7368980.2,
        "mount_type": "xfs",
        "total": 7607034,
        "used": 238053.8
      },
      "/media/frigate/recordings": {
        "free": 7368980.2,
        "mount_type": "xfs",
        "total": 7607034,
        "used": 238053.8
      },
      "/tmp/cache": {
        "free": 905.7,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 48
      }
    },
    "temperatures": {
      "apex_0": 41.3
    },
    "uptime": 2690,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

    - Model: Reolink TrackMix Wifi     - UID: 95270006ZAUT1WDV     - Build No. build 2408281837     - Hardware No. IPC_529SD78MP     - Config Version: v3.0.0.0     - Firmware Version: v3.0.0.3748_2408281837     - Details: IPC_529SD78MPS16E1W72100000001

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/12fd46c0-224b-4d2d-9af3-fdd7ef5d9704)
![image](https://github.com/user-attachments/assets/a5abdbb8-a99b-4abf-951f-3095d3c401f1)

### Any other information that may be helpful

Frigate Docker Image
ghcr.io/blakeblackshear/frigate   stable    d1502760b3b1   2 months ago    1.92GB

- Camera Model
    - Model: Reolink TrackMix Wifi
    - UID: 95270006ZAUT1WDV
    - Build No. build 2408281837
    - Hardware No. IPC_529SD78MP
    - Config Version: v3.0.0.0
    - Firmware Version: v3.0.0.3748_2408281837
    - Details: IPC_529SD78MPS16E1W72100000001

Docker Version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by hawkeye217** [comment]
You might try using the ffmpeg module with go2rtc, eg:

```
go2rtc:
  streams:
    reolinkbackyardtrackmix:
      - ffmpeg:rtsp://REMOVED@10.0.0.32:554/h264Preview_01_main
    reolinkbackyardtrackmix_sub:
      - ffmpeg:rtsp://REMOVED@10.0.0.32:554/h264Preview_01_sub
```

**Reply by rpm5099** [reply]
Yes, I actually had that enabled for some time, but I will give it another shot and see if it makes any difference with the rest of the current settings. Thanks for the suggestion, I guess I need to look more into go2rtc troubleshooting.  

On that note, is there a way to easily see how settings end up being translated into raw ffmpeg parameters?  I looked into the presets and  it appears they are dynamically generated via several python scripts, but the only place I know of to look for the result is with `ps`.  The presets seem to work well for most people, and are a major advantage over Shinobi aka "ffmpeg hell".  I have no interest in becoming an ffmpeg expert, but at this point I will go that direction if I have to.  Thanks again.

**Reply by hawkeye217** [reply]
You shouldn't have to tweak any of the ffmpeg parameters on Frigate's side as it's just pulling the stream from go2rtc. You'll want to keep an eye on the go2rtc logs for any clues. You could enable `trace` logs with go2rtc to really get into the details of what go2rtc is doing with your stream.

**Reply by rpm5099** [reply]
I am definitely going to do that, but after 5 hours of messing with this I think I may have found something that works - tell me if this makes any sense.  This uses a lot more cpu (and virtually no gpu) so I think that it is re-encoding the h265 down to h264 before consumption by Frigate.  This particular camera there is no way to force the main stream to be h264 or reduce the resolution, which I refuse to do anyways.  This is the only settings I have found that displays the video without stuttering, which I was not able to do via VLC either.  In hindsight I would not have bought these cameras, and for the rest of them they will either not be Reolink or I will test them and return if they have this limitation.  I need to ensure that go2rtc is using hardware accel and not cpu, if you have any suggestions there.  Thanks again.

```yaml
go2rtc:
  streams:
    reolinkbackyardtrackmix:
      - rtsp://XXX@10.0.0.32:554/h264Preview_01_main
      - ffmpeg:reolinkbackyardtrackmix#video=h264#audio=opus#hardware
    reolinkbackyardtrackmix_sub:
      - rtsp://XXX@10.0.0.32:554/h264Preview_01_sub
    reolinkfronttrackmix:
      - rtsp://XXX@10.0.0.34:554/h264Preview_01_main
      - ffmpeg:reolinkfronttrackmix#video=h264#audio=opus#hardware
    reolinkfronttrackmix_sub:
      - rtsp://XXX@10.0.0.34:554/h264Preview_01_sub
```
