### DISCUSSION TITLE
Detec on low FPS camera but record in High quality fps camera

### DISCUSSION THREAD

**Discussion by karopodgajecki** [blakeblackshear/frigate#14756] [General]
Hello, 

Im pooking around Frigate and I found strange issue (if its even issue). Example config: 

```
  tylprawa:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://1111:1111@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://1111:1111@192.168.1.5:554
          roles:
            - record
```

I thought that first role "detect" is using only for detecting objects, but when it detect it for recording stream changes to record - In my opinion this is not working like this - question is if its even possible to get high quality of videos while object was detected and event is captured   ?
