### DISCUSSION TITLE
[Support]: 15.0 Breaks FFMPEG with go2rtc / Reolink

### DISCUSSION THREAD

**Discussion by duckdude555** [blakeblackshear/frigate#14754] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When upgrading to the 15.0 Beta 1 image, my go2rtc stream broke - the camera was reported as not connected, and I had constant errors that the FFMPEG process was not started. All other streams worked fine. I downgraded to 14.0 using my old config, and my stream started working again. 

I unfortunately did not save my 15.0-upgraded config file, but will paste my working 14.0 file below. I am not sure if the error was caused by 15 trying to automatically upgrade my config file, or if the bug was inherent to 15. If the information I provided isn’t helpful (I’m not sure if this is an obvious issue or not) I can try again to get the relevant log outputs - sorry!

### Steps to reproduce

1. Pull 15.0 Beta 1 docker image
2. 
3.
...

### Version

15.0-Beta1

### Frigate config file

```yaml
mqtt:
  host: 192.168.xx.xx
  port: 1883
  user: xxxx
  password: xxxx
  topic_prefix: frigate
  client_id: frigate



tls:
  enabled: false
#detectors:
#  cpu:
#    type: cpu
#    num_threads: 8


#birdseye:
#  restream: true

birdseye:
  enabled: true
  mode: continuous
  restream: true

go2rtc:
  webrtc:
    listen: :8555
    candidates:
      - 192.168.xx.xx:8555
      - stun:8555
  streams:
    front_door:
     #- ffmpeg:https://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus
      #- rtsp://xx:xx@192.168.xx.xx:554/
      - ffmpeg:https://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#audio=opus#audio=volume #THIS
      - rtsp://xx:xx@192.168.xx.xx:554/ #THIS
    front_door_sub:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xx#audio=opus#audio=volume    #THIS but with ""
      - rtsp://xx:xx@192.168.xx.xx:554/h264Preview_01_sub #THIS
    
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"
  #ui:
   # live_mode: webrtc




cameras:
  front_door:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: preset-record-generic-audio-copy

      inputs:
        #high res
        - path: rtsp://127.0.0.1:8554/front_door #?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio

      #low res
        - path: rtsp://127.0.0.1:8554/front_door_sub #?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_door_sub
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - car
        - dog

      filters:
        car:
          threshold: 0.6
          min_score: 0.6
          mask: 
            0.804,0.677,0.99,0.737,0.991,1,0,0.997,0,0,1,0,0.991,0.541,0.51,0.51,0.442,0.534,0.719,0.594,0.279,0.559,0.286,0.664,0.525,0.655
        dog:
          mask: 0.988,0.523,0.276,0.519,0.335,0.99,0.007,0.99,0,0.003,0.999,0.003
        person:
          min_score: 0.65 # min score for object to initiate tracking (default: 0.5
          threshold: 0.75 # 
          mask: 
            0.992,0.528,0.754,0.535,0.714,0.578,0.555,0.582,0.487,0.498,0.274,0.502,0.34,1,0.008,0.999,0.004,0.008,1,0.011,1,0.543,0.394,0.487
    motion:
      mask: 
        0.011,0,0.999,0,1,0.502,0.746,0.54,0.661,0.567,0.557,0.574,0.512,0.51,0.296,0.51,0.294,0.596,0.322,0.877,0.344,0.99,0.009,0.985
      threshold: 50
      contour_area: 30
      improve_contrast: 'true'
    zones:
      On_Street:
        coordinates: 0.993,0.721,0.797,0.641,0.697,0.569,0.466,0.53,0.574,0.511,1,0.521
      On_Property:
        coordinates: 0.975,0.981,0.501,0.65,0.809,0.643,0.997,0.724
      On_Property_2:
        coordinates: 0.727,0.606,0.313,0.59,0.297,0.532,0.614,0.546,0.715,0.576
      Driveway_and_Front_Step:
        coordinates: 0.791,0.645,0.497,0.652,0.966,0.988,0.322,0.995,0.245,0.559,0.725,0.586
        inertia: 3
    review:
      alerts:
        required_zones: Driveway_and_Front_Step
      detections:
        required_zones:
          - On_Street
          - On_Property_2
          - On_Property
          - Driveway_and_Front_Step


  indoor:
    birdseye:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: preset-record-generic-audio-aac

      inputs:
        #high res
        - path: rtsp://xx:xx@192.168.xx.xx/Preview_01_main
          roles:
            - record
            - audio
      #low res
        - path: rtsp://xx:xx@192.168.xx.xx/Preview_01_sub
          roles:
            - detect

    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - dog
      filters:
        dog:
          mask: 
            0.09,0.392,0.465,0.351,0.558,0.388,0.789,0.339,0.996,0.424,0.997,0.88,0.935,0.996,0.005,0.993,-0.001,0.596
        person:
          mask: 
            0.296,0.214,0.346,0.202,0.469,0.201,0.554,0.238,0.792,0.212,0.997,0.24,0.999,0.993,0.008,0.991,0.003,0.433,0.078,0.234
    onvif:
      host: 192.168.xx.xx
      user: xx
      password: xx


    motion:
      mask: 
        0.004,0.005,0,0.769,0.083,0.388,0.072,0.185,0.398,0.17,0.561,0.102,0.828,0.178,0.994,0.201,1,0
      threshold: 46
      contour_area: 29
      improve_contrast: 'true'
  garage:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        #high res
        - path: rtsp://xx:xx@192.168.xx.xx/Preview_01_main
          roles:
            - record
      #low res
        - path: rtsp://xx:xx@192.168.xx.xx/Preview_01_sub
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 1536
      height: 576
      fps: 7
    objects:
      track:
        - person
        - car
        - dog

      filters:
        car:
          threshold: 0.7
          min_score: 0.7
          mask: 
            0.521,0.261,0.418,0.343,0.39,0.456,0.65,0.471,0.844,1,0.227,0.989,0.002,0.995,0.001,0.008,0.994,0.013,0.995,0.992,0.833,0.997,0.713,0.697,0.617,0.399,0.612,0.346,0.637,0.33,0.53,0.231
        person:
          threshold: 0.7
          min_score: 0.7
          mask: 
            0.078,0.899,0.221,0.729,0.234,0.583,0.23,0.514,0.248,0.416,0.315,0.308,0.41,0.261,0.499,0.221,0.525,0.253,0.626,0.326,0.613,0.372,0.655,0.504,0.734,0.528,0.739,0.424,0.829,0.481,0.89,0.567,0.853,0.744,0.737,0.743,0.852,0.98,0.998,0.982,1,0.008,0.008,0,0.008,0.652,0.051,0.796
        dog:
          threshold: 0.6
          min_score: 0.6
          mask: 
            0.002,0.008,0.992,0.013,0.994,0.997,0.835,0.822,0.894,0.569,0.828,0.479,0.495,0.207,0.391,0.194,0.282,0.237,0.242,0.255,0.073,0.529,0.004,0.524
    motion:

      improve_contrast: 'true'
      mask: 
        0.236,0.263,0.33,0.218,0.394,0.199,0.449,0.197,0.502,0.213,0.629,0.319,0.693,0.237,1,0.745,0.995,0.011,0.003,0.005,0.001,0.548,0.091,0.612,0.151,0.572,0.221,0.524,0.243,0.444
      threshold: 50
      contour_area: 23
    zones:
      In_Driveway:
        coordinates: 
          0.22,0.976,0.077,1,0.069,0.814,0.194,0.654,0.279,0.559,0.398,0.396,0.523,0.239,0.633,0.332,0.825,0.479,0.893,0.59,0.829,0.851,0.898,1
        objects:
          - dog
          - person
        inertia: 3
      In_Driveway_car:
        coordinates: 0.395,0.458,0.64,0.464,0.637,0.329,0.532,0.236,0.422,0.349
        objects: car
        inertia: 3
    review:
      alerts:
        required_zones: In_Driveway

  backyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        #high res
        - path: rtsp://xx:xx@192.168.xx.xx/Preview_01_main
          roles:
            - record
      #low res
        - path: rtsp://xx:xx@192.168.xx.xx/Preview_01_sub
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true

    detect:
      enabled: true
      width: 896
      height: 512
      fps: 7
    objects:
      track:
        - person
        - car
        - dog

      filters:
        car:
          mask: 0.003,0.01,0.992,0.009,0.992,0.986,0.004,0.988
    motion:

      improve_contrast: 'true'
      mask: 
        0,0,1,0,0.997,0.465,0.673,0.491,0.657,0.311,0.583,0.314,0.573,0.427,0.37,0.464,0.246,0.458,0.004,0.497
      threshold: 50
      contour_area: 40
    onvif:
      host: 192.168.xx.xx
      user: xx
      password: xx




    zones:
      people_and_pets:
        coordinates: 
          0.003,0.51,0.243,0.471,0.383,0.53,0.575,0.435,0.589,0.324,0.646,0.324,0.66,0.422,0.998,0.408,0.992,0.987,0.003,0.999
        loitering_time: 0
        objects:
          - dog
          - person
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
# https://github.com/blakeblackshear/frigate

networks:
  dockerBridge: #default:
    external:
      name: dockerBridge
      #name: frigateBridge
 
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.0
  #  ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
   # devices:
   #   - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
   #   - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
   #   - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-uuid-c2a02e1a-dcbd-4907-8843-5043fb66a36f/compose/frigate/config:/config/
      - /srv/dev-disk-by-uuid-c2a02e1a-dcbd-4907-8843-5043fb66a36f/compose/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000 # 500gb
    mac_address: xxxxxx
    networks:
      dockerBridge:
        ipv4_address: 192.168.xx.xx
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971"
      - "443:8971"
#    network_mode: "host"
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Doorbell

### Screenshots of the Frigate UI's System metrics pages

N/A
