### DISCUSSION TITLE
[Config Support]: how to disable to verbose http log entries, as it is hiding actual log messages

### DISCUSSION THREAD

**Discussion by ronbruins** [blakeblackshear/frigate#14771] [Config Support] [answered]
### Describe the problem you are having

When checking the logs for errors or general matters that need attention, there is this endless stream of log entree from the guy (GET) can this be disabled? I already tried this:

```
logger:
  default: error
  logs:
    frigate.record.maintainer: debug
    frigate.app: critical
```

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: 192.168.1.35
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ****
  password: ******

tls:
  enabled: false

ui:
  time_format: 24hour
  date_style: short

logger:
  default: error
  logs:
    frigate.record.maintainer: debug

birdseye:
  enabled: true
  mode: continuous

go2rtc:
  log:
    format: text
    level: error

  streams:
    balkon:
      - rtsp://*:*@192.168.1.123:554/h264Preview_01_main
      - ffmpeg:balkon#video=h264#audio=opus
    balkon_sub:
      - ffmpeg:http://192.168.1.123/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****
    achter:
      - rtsp://admin:****@192.168.1.181:554/h264Preview_01_main
    achter_sub:
      - ffmpeg:http://192.168.1.181/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****
    voordeur:
      - rtsp://admin:****@192.168.1.37:554/h265Preview_01_main
      - ffmpeg:voordeur#video=h264#audio=opus
    voordeur_sub:
      - rtsp://admin:****@192.168.1.37:554/h264Preview_01_sub
    deurbel:
      - rtsp://admin:****@192.168.1.148:554/h264Preview_01_main
    deurbel_sub:
      - ffmpeg:http://192.168.1.148/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

model:
  path: plus://****

snapshots:
  enabled: true
  retain:
    default: 1

detect:
  enabled: true

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 7
      mode: motion

objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package
  filters:
    cat:
      min_area: 3000
      threshold: 0.83
    dog:
      min_area: 3000
      threshold: 0.8
    person:
      min_area: 5500
      threshold: 0.8

cameras:
  balkon:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/balkon
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/balkon_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0.49,0,0.492,0.072,0.641,0.078,0.637,0.009
        - 0,0.433,0.235,0,0.001,0
    objects:
      filters:
        car:
          mask:
            - 0.003,0.437,0.006,0.556,0.997,0.326,0.997,0.24
            - 0,0.83,0.341,0.806,0.527,0.772,1,0.561,0.991,0.649,0.656,0.86,0.301,0.917,0.003,0.936
            - 0.002,0.39,0.201,0.004,0.001,0.004
      mask: 0.002,0.39,0.201,0.004,0.001,0.004
  achter:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/achter
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/achter_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.485,0.011,0.486,0.059,0.64,0.058,0.64,0.003
  voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/voordeur
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/voordeur_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.773,0.005,0.774,0.073,0.924,0.071,0.924,0.005
  deurbel:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deurbel
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deurbel_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 0.216,0.697,0.215,0.747,0.487,0.757,0.72,0.707,0.722,0.679
            - 0.231,0.585,0.236,0.624,0.385,0.639,0.687,0.613,0.729,0.606,0.73,0.576
      mask: 0.311,0.517,0.212,0.585,0.205,0.413,0.314,0.404
    motion:
      mask:
        - 0.476,0.012,0.478,0.062,0.628,0.056,0.629,0.006
        - 0.316,0.522,0.119,0.66,0.107,0.419,0.316,0.4
version: 0.14
```

### Relevant Frigate log output

```shell
frigate_014B  | 2024-11-04 08:37:09.014044378  192.168.65.1 - - [04/Nov/2024:08:37:09 +0100] "GET /fonts/Inter-Light.woff2 HTTP/1.1" 200 109992 "http://*****/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15" "51.235.240.136"
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

CPU (no coral)
