### DISCUSSION TITLE
[Camera Support]: review page not works after update to 15.0-beta1

### DISCUSSION THREAD

**Discussion by Poseidonhun** [blakeblackshear/frigate#14773] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I can only see the loading icon when I navigate to the review page. Multiple camera scrolling not works for motion.
![image](https://github.com/user-attachments/assets/a440f517-770d-4bbc-86c8-773c8b9127f6)

What is interesting, when I select earlier date, then the fast scrolling is loading fine. It seems after the update not works.
I have enabled debug mode, but I cannot see the exact problem. No errors, not tracebacks.

When I clicking on the dashboard on one of the camera then the fast scrolling is loading and works.

### Steps to reproduce

1. Clicking on review page

### Version

0.15.0-beta1

### In which browser(s) are you experiencing the issue with?

Brave 1.71.121 Chromium: 130.0.6723.91

### Frigate config file

```yaml
mqtt:
  enabled: false

tls:
  enabled: false

logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  #logs:
  #  frigate.event: debug

# Optional: Authentication configuration
auth:
  # Optional: Enable authentication
  enabled: True
  cookie_secure: True
  # Optional: Session length in seconds (default: shown below)
  session_length: 864000 # 24 hours
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  failed_login_rate_limit: None
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000

#detectors:
#  cpu:
#    enabled: false
#    type: cpu

#detectors:
#  ov:
#    type: openvino
#    device: AUTO
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml

#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: false
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

database:
  path: /config/frigate.db

record:
  enabled: true
  sync_recordings: false
  retain:
    days: 180
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: false
  quality: 100
  bounding_box: false
  retain:
    default: 10

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 60
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 20
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  #frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  #frame_height: 100
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
    #mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  #improve_contrast: True
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
    #mqtt_off_delay: 30
go2rtc:
  streams:
    5HSB0LCV:
      - rtsp://url:8554/5HSB0LCV#media=video#video=h264#timeout=60backchannel=0
    SZ822WNA:
      - rtsp://url:8554/SZ822WNA#media=video#video=h264#timeout=60#backchannel=0
    WJM3WP2O:
      - rtsp://url:8554/WJM3WP2O#media=video#video=h264#timeout=60#backchannel=0
  webrtc:
    candidates:
      - 192.168.0.2:8555
      - stun:8555
# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: auto detect)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
  #  - -hwaccel 
  #  - vulkan
    - -c:v
    - h264_v4l2m2m
  # Optional: global input args (default: shown below preset-rtsp-generic, preset-rtsp-restream-low-latency)
  input_args: preset-rtsp-generic
  #  - -avoid_negative_ts
  #  - make_zero
  #  - -fflags
  #  - +genpts+discardcorrupt
  #  - -rtsp_transport
  #  - tcp
  #  - -timeout
  #  - '10000000'
  #  - -use_wallclock_as_timestamps
  #  - '1'
  #  - -flags
  #  - low_delay
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
  # Optional: Time in seconds to wait before ffmpeg retries connecting to the camera. (default: shown below)
  # If set too low, frigate will retry a connection to the camera's stream too frequently, using up the limited streams some cameras can allow at once
  # If set too high, then if a ffmpeg crash or camera stream timeout occurs, you could potentially lose up to a maximum of retry_interval second(s) of footage
  # NOTE: this can be a useful setting for Wireless / Battery cameras to reduce how much footage is potentially lost during a connection timeout.
  retry_interval: 10

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: false
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0

cameras:
  5HSB0LCV:
    enabled: true
    review:
      detections:
        labels: []
    ffmpeg:
      inputs:
        - path: rtsp://url:8554/5HSB0LCV
          roles:
            - record
  SZ822WNA:
    enabled: true
    review:
      detections:
        labels: []
    ffmpeg:
      inputs:
        - path: rtsp://url:8554/SZ822WNA
          roles:
            - record
  WJM3WP2O:
    enabled: false
    review:
      detections:
        labels: []
    ffmpeg:
      inputs:
        - path: rtsp://url:8554/WJM3WP2O
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
nvr:
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "128mb" # update for your cameras based on calculation above
#    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video10:/dev/video10 # For Raspberry Pi 4B
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- E:/frigate/config:/config
      #- E:/frigate/storage:/media/frigate
      - /media/nas/frigate/config:/config
      - /media/nas/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      #- "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.routers.${STACK_NAME?Variable not set}-nvr-https.rule=(Host(`nvr.${DOMAIN?Variable not set}`))
      - traefik.http.routers.${STACK_NAME?Variable not set}-nvr-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-nvr-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-nvr-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?Variable not set}-nvr.loadbalancer.server.port=8971
      #- traefik.http.services.${STACK_NAME?Variable not set}-nvr.loadbalancer.server.scheme=https
```

### Relevant Frigate log output

```shell
no errors on server side
```

### Relevant go2rtc log output

```shell
no errors on server side
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

raspberry rtsp

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/cc3d817c-8a62-4d4f-bcf2-a0768c33e7d2)

### Any other information that may be helpful

I am not sure this is relevant
![image](https://github.com/user-attachments/assets/bd5c4ac4-fe0c-4fd0-98a8-608e38d1643a)
