### DISCUSSION TITLE
[Config Support]: Frigate not detecting persons

### DISCUSSION THREAD

**Discussion by spotlesscoder** [blakeblackshear/frigate#14796] [Config Support]
### Describe the problem you are having

I was standing in front of the camera both during day and night but I was not detected - at least I think so. The motion was detected and shown in the recordings but the detections tab still has 0 detections

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: <ip>
  port: <port>
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - cat
    - dog

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 2
    mode: motion
  events:
    retain:
      default: 2
      mode: motion

cameras:
  cam1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:password@camera1/stream
          roles:
            - detect
            - record
    onvif:
      host: <ip>
      port: 8000
      user: admin
      password: pass
    detect:
      enabled: true
      width: 2560
      height: 1920

  cam2: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:password@camera2/stream
          roles:
            - detect
            - record
    onvif:
      host: <ip>
      port: 8000
      user: admin
      password: pass
    detect:
      enabled: true
      width: 2560
      height: 1920

version: 0.14
```

### Relevant Frigate log output

```shell
found nothing that I would consider relevant
```

### Relevant go2rtc log output

```shell
info
2024-11-04 22:06:20
startup
Preparing new go2rtc config...
info
2024-11-04 22:06:21
startup
Starting go2rtc...
info
2024-11-04 22:06:21
startup
go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info
2024-11-04 22:06:21
startup
config path=/dev/shm/go2rtc.yaml
info
2024-11-04 22:06:21
api
listen addr=:1984
info
2024-11-04 22:06:21
rtsp
listen addr=:8554
info
2024-11-04 22:06:21
webrtc
listen addr=:8555/tcp
info
2024-11-04 22:06:30
startup
Starting go2rtc healthcheck service...
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    #  - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #  - /dev/video11:/dev/video11 # For Raspberry Pi 4B
    #  - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Object Detector

Coral
