### DISCUSSION TITLE
[Support]: Opening a camera takes 5-30 seconds

### DISCUSSION THREAD

**Discussion by mr-manuel** [blakeblackshear/frigate#14802] [General Support] [answered]
### Describe the problem you are having

Hello,

when clicking on a camera from the `All Cameras` overview page, it takes from 5 to 30 seconds to open that camera. I checked the 

### Version

0.15.0-33825f6 (but also in 0.14.1)

### What browser(s) are you using?

Firefox 132.0

### Frigate config file

```yaml
version: 0.15-0

mqtt:
  host: 192.168.4.203
  port: 1883
  stats_interval: 15

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /database/frigate.db

tls:
  enabled: false

logger:
  default: warning

birdseye:
  enabled: true
  width: 1400
  height: 788
  quality: 8
  mode: motion

detect:
  fps: 5
  enabled: true
  max_disappeared: 25
  stationary:
    interval: 60
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
  annotation_offset: -500

objects:
  filters:
    person:
      min_area: 0
      max_area: 24000000
      min_score: 0.5
      threshold: 0.7

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: false
  mqtt_off_delay: 30

record:
  enabled: true
  expire_interval: 300
  retain:
    days: 6
    mode: all
  alerts:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: true
  timestamp: false
  bounding_box: false
  crop: true
  retain:
    default: 7
    objects:
      person: 14

go2rtc:
  log:
    format: text
    level: warn  # default level
    api: warn
    exec: warn
    ngrok: warn
    rtsp: warn
    streams: error
    webrtc: fatal
  rtsp:
    default_query: mp4
  streams:
    Porch:
      - rtsp://192.168.0.80:554/11
    Backyard:
      - rtsp://192.168.0.81:554/stream0
  webrtc:
    listen: :8555
    candidates:
      - 192.168.4.205:8555 # <--- enter frigate host IP here
#      - frigate:8555 # <--- needed?
#      - stun:8555

live:
  height: 1120
  quality: 8

cameras:

  Porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      width: 2560
      height: 1920
    best_image_timeout: 60
    zones:
      Zone_1:
        coordinates: 584,817,770,1579,1021,1472,1031,1224,1781,784,1817,445
      Zone_2:
        coordinates: 1835,841,2431,340,1956,75
        objects:
          - person
      Zone_3:
        coordinates: 0,1920,0,923,503,829,759,1745,754,1920
    motion:
      mask:
        - 2560,331,2466,331,1826,802,1780,1035,996,1536,718,1738,704,1920,111,1920,80,1427,248,1335,195,938,1896,397,1958,53,2466,331,2560,331,2560,0,0,0,0,1920,2560,1920
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      quality: 70
    objects:
      track:
        - person
        - bird
        - cat
        - dog
    ui:
      order: 0
      dashboard: true

  Backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      width: 3840
      height: 2144
    best_image_timeout: 60
    zones:
      Zone_1:
        coordinates: 
          1560,502,1563,652,1443,1036,1349,1546,1340,1793,1492,1766,1500,2144,2854,2144,2832,2004,3138,1621,3310,1556,3108,984,2757,393,2355,409
      Zone_2:
        coordinates: 
          3150,0,3840,696,3840,1647,3741,1749,3620,1342,3452,979,3263,671,2955,341,2834,223,2811,315,2694,283,2447,281,2459,95,2401,0
        objects:
          - bicycle
          - car
          - motorcycle
      Zone_3:
        coordinates: 
          906,1606,1033,1557,977,1830,1229,1830,1222,2144,1504,2144,1501,1699,1322,1737,1325,1293,855,1484
      Zone_4:
        coordinates: 3310,1556,3341,1642,3442,1950,3295,2037,3058,2144,2863,2144,2832,2004,3138,1621
    motion:
      mask:
        - 0,0,1521,0,1519,218,1540,526,1580,811,1475,1237,245,1778,627,2011,999,2144,0,2144
        - 3840,0,3840,674,3116,0
        - 3840,2144,3840,1643,3622,1824,3322,1997,2990,2144
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      quality: 70
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - bird
        - cat
        - dog
      filters:
        person:
          mask:
            - 3334,1191,3471,1503,3581,1862,3840,1655,3840,0,0,0,0,2144,889,2144,1046,1579,1408,1410,1584,818,2266,675,2271,433,2794,380,3153,858
            - 1278,2144,664,2144,664,1685,1278,1685
    ui:
      order: 1
      dashboard: true

  X-Porch-Zoom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          roles:
            - detect
      hwaccel_args: -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device
        /dev/dri/renderD128 -hwaccel_output_format vaapi
      output_args:
        detect: -vf fps=5,hwdownload,format=yuv420p,crop=510:610:1900:130 -threads
          1 -f rawvideo
    detect:
      width: 510
      height: 610
      enabled: false
    snapshots:
      enabled: false
    record:
      enabled: false
    mqtt:
      enabled: false
    birdseye:
      enabled: false
    ui:
      order: 10
      dashboard: false

  X-Backyard-Zoom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          roles:
            - detect
      hwaccel_args: -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device
        /dev/dri/renderD128 -hwaccel_output_format vaapi
      output_args:
        detect: -vf fps=5,hwdownload,format=yuv420p,crop=850:750:2970:1294 -threads
          1 -f rawvideo
    detect:
      width: 850
      height: 750
      enabled: false
    snapshots:
      enabled: false
    record:
      enabled: false
    mqtt:
      enabled: false
    birdseye:
      enabled: false
    ui:
      order: 11
      dashboard: false

camera_groups:
  Birdseye:
    order: 1
    icon: LuMonitor
    cameras: birdseye

ui:
  timezone: Europe/Rome
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%Y/%m/%d %H:%M:%s'
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### FFprobe output from your camera

```shell
# root@e4ce871a31f5:/opt/frigate# ffprobe rtsp://192.168.0.80:554/11
# Input #0, rtsp, from 'rtsp://192.168.0.80:554/11':
#   Metadata:
#     title           : 10
#   Duration: N/A, start: 0.080000, bitrate: N/A
#     Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 2560x1920, 12.50 fps, 12.50 tbr, 90k tbn, 180k tbc

# root@e4ce871a31f5:/opt/frigate# ffprobe rtsp://192.168.0.80:554/12
# Input #0, rtsp, from 'rtsp://192.168.0.80:554/12':
#   Metadata:
#     title           : 11
#   Duration: N/A, start: 0.080000, bitrate: N/A
#     Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 800x600, 12.50 fps, 12.50 tbr, 90k tbn, 180k tbc



# root@e4ce871a31f5:/opt/frigate# ffprobe rtsp://192.168.0.81:554/stream0
# Input #0, rtsp, from 'rtsp://192.168.0.81:554/stream0':
#   Metadata:
#     title           : RTSP/RTP stream from anjvision ipcamera
#   Duration: N/A, start: 0.448000, bitrate: N/A
#     Stream #0:0: Video: h264, yuv420p(progressive), 3840x2144, 20 fps, 20 tbr, 90k tbn, 40 tbc

# root@e4ce871a31f5:/opt/frigate# ffprobe rtsp://192.168.0.81:554/stream1
# Input #0, rtsp, from 'rtsp://192.168.0.81:554/stream1':
#   Metadata:
#     title           : RTSP/RTP stream from anjvision ipcamera
#   Duration: N/A, start: 0.348000, bitrate: N/A
#     Stream #0:0: Video: h264, yuv420p(progressive), 704x480, 20 fps, 20 tbr, 90k tbn, 40 tbc
```

### Frigate stats

```json
{
    "cameras": {
        "Porch": {
            "camera_fps": 5.1,
            "process_fps": 5.1,
            "skipped_fps": 0,
            "detection_fps": 0,
            "detection_enabled": true,
            "pid": 479,
            "capture_pid": 491,
            "ffmpeg_pid": 512,
            "audio_rms": 0,
            "audio_dBFS": 0
        },
        "Backyard": {
            "camera_fps": 5,
            "process_fps": 5,
            "skipped_fps": 0,
            "detection_fps": 0,
            "detection_enabled": true,
            "pid": 480,
            "capture_pid": 505,
            "ffmpeg_pid": 525,
            "audio_rms": 0,
            "audio_dBFS": 0
        },
        "X-Porch-Zoom": {
            "camera_fps": 5.1,
            "process_fps": 5.1,
            "skipped_fps": 0,
            "detection_fps": 0,
            "detection_enabled": false,
            "pid": 481,
            "capture_pid": 516,
            "ffmpeg_pid": 531,
            "audio_rms": 0,
            "audio_dBFS": 0
        },
        "X-Backyard-Zoom": {
            "camera_fps": 5,
            "process_fps": 5,
            "skipped_fps": 0,
            "detection_fps": 0,
            "detection_enabled": false,
            "pid": 482,
            "capture_pid": 519,
            "ffmpeg_pid": 533,
            "audio_rms": 0,
            "audio_dBFS": 0
        }
    },
    "detectors": {
        "coral": {
            "inference_speed": 9.97,
            "detection_start": 0,
            "pid": 412
        }
    },
    "detection_fps": 0,
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "21.04%",
            "mem": "-%"
        }
    },
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
        },
        "15": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise s6-linux-init-shutdownd"
        },
        "16": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
        },
        "24": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise frigate"
        },
        "25": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise nginx"
        },
        "26": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise nginx-log"
        },
        "27": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise go2rtc-log"
        },
        "28": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise s6rc-fdholder"
        },
        "29": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise frigate-log"
        },
        "30": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise go2rtc-healthcheck"
        },
        "31": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise go2rtc"
        },
        "32": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise certsync"
        },
        "33": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise s6rc-oneshot-runner"
        },
        "34": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise certsync-log"
        },
        "45": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
        },
        "46": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
        },
        "85": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
        },
        "88": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
        },
        "89": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
        },
        "90": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
        },
        "102": {
            "cpu": "22.4",
            "cpu_average": "17",
            "mem": "0.7",
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
        },
        "121": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "bash ./run.user go2rtc-healthcheck"
        },
        "126": {
            "cpu": "5.1",
            "cpu_average": "7",
            "mem": "12.8",
            "cmdline": "python3 -u -m frigate"
        },
        "132": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2",
            "cmdline": "nginx: master process nginx"
        },
        "170": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "nginx: worker process"
        },
        "171": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "nginx: worker process"
        },
        "172": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "nginx: worker process"
        },
        "173": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "nginx: worker process"
        },
        "174": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "nginx: cache manager process"
        },
        "308": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "bash ./run.user certsync"
        },
        "327": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "sleep 9999"
        },
        "395": {
            "cpu": "4.9",
            "cpu_average": "3",
            "mem": "2.6",
            "cmdline": "frigate.recording_manager"
        },
        "397": {
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "2.4",
            "cmdline": "frigate.review_segment_manager"
        },
        "411": {
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(29)"
        },
        "412": {
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "2.6",
            "cmdline": "frigate.detector.coral"
        },
        "428": {
            "cpu": "1.6",
            "cpu_average": "1",
            "mem": "3.0",
            "cmdline": "frigate.output       "
        },
        "435": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "1.1",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -threads 1 -f mpegts -s 1493x1120 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "442": {
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "1.9",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2144 -i pipe: -threads 1 -f mpegts -s 2005x1120 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "449": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 510x610 -i pipe: -threads 1 -f mpegts -s 936x1120 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "456": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 850x750 -i pipe: -threads 1 -f mpegts -s 1269x1120 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "464": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1400x788 -i pipe: -threads 1 -f mpegts -s 1400x788 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "479": {
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "2.8",
            "cmdline": "frigate.process:Porch"
        },
        "480": {
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "2.9",
            "cmdline": "frigate.process:Backyard"
        },
        "481": {
            "cpu": "1.2",
            "cpu_average": "0",
            "mem": "2.8",
            "cmdline": "frigate.process:X-Porch-Zoom"
        },
        "482": {
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "2.8",
            "cmdline": "frigate.process:X-Backyard-Zoom"
        },
        "491": {
            "cpu": "8.3",
            "cpu_average": "8",
            "mem": "2.9",
            "cmdline": "frigate.capture:Porch"
        },
        "505": {
            "cpu": "13.6",
            "cpu_average": "13",
            "mem": "3.1",
            "cmdline": "frigate.capture:Backyard"
        },
        "512": {
            "cpu": "14.7",
            "cpu_average": "14",
            "mem": "1.3",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-33825f6 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Porch -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Porch@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1920,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "516": {
            "cpu": "1.3",
            "cpu_average": "1",
            "mem": "2.7",
            "cmdline": "frigate.capture:X-Porch-Zoom"
        },
        "519": {
            "cpu": "1.7",
            "cpu_average": "1",
            "mem": "2.7",
            "cmdline": "frigate.capture:X-Backyard-Zoom"
        },
        "525": {
            "cpu": "23.0",
            "cpu_average": "22",
            "mem": "2.1",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-33825f6 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Backyard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=3840:h=2144,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "531": {
            "cpu": "4.4",
            "cpu_average": "4",
            "mem": "0.9",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-33825f6 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Porch -r 5 -vf fps=5,scale=510:610 -vf fps=5,hwdownload,format=yuv420p,crop=510:610:1900:130 -threads 1 -f rawvideo pipe:"
        },
        "533": {
            "cpu": "7.0",
            "cpu_average": "7",
            "mem": "1.3",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-33825f6 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Backyard -r 5 -vf fps=5,scale=850:750 -vf fps=5,hwdownload,format=yuv420p,crop=850:750:2970:1294 -threads 1 -f rawvideo pipe:"
        },
        "2872": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "sleep 30s"
        },
        "frigate.full_system": {
            "cpu": "37.2",
            "mem": "54.1"
        }
    },
    "service": {
        "uptime": 950,
        "version": "0.15.0-33825f6",
        "latest_version": "0.14.1",
        "storage": {
            "/media/frigate/recordings": {
                "total": 468355.7,
                "used": 439849.1,
                "free": 4643.6,
                "mount_type": "ext4"
            },
            "/media/frigate/clips": {
                "total": 238220.3,
                "used": 40749.9,
                "free": 185298.3,
                "mount_type": "ext4"
            },
            "/tmp/cache": {
                "total": 2048,
                "used": 12.3,
                "free": 2035.7,
                "mount_type": "tmpfs"
            },
            "/dev/shm": {
                "total": 1024,
                "used": 909.8,
                "free": 114.2,
                "mount_type": "tmpfs"
            }
        },
        "temperatures": {},
        "last_updated": 1730798992
    },
    "processes": {
        "recording": {
            "pid": 395
        },
        "review_segment": {
            "pid": 397
        },
        "go2rtc": {
            "pid": 102
        }
    }
}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    shm_size: '1024m'
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FRIGATE_ROOT_PATH}/config/:/config/
      - ${FRIGATE_ROOT_PATH}/database/:/database/
      - ${FRIGATE_ROOT_PATH}/media/frigate/:/media/frigate/
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2G
    ports:
      - '80:5000'
      - '5000:5000'
      - '8554:8554'
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - 'FRIGATE_RTSP_USER=${FRIGATE_RTSP_USER}'
      - 'FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}'
      # needed for Intel J4125 CPU hardware acceleration
      - 'LIBVA_DRIVER_NAME=i965'
      - 'PLUS_API_KEY=*************'
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Some cameras from Aliexpress

### Screenshots of the Frigate UI's System metrics pages

![grafik](https://github.com/user-attachments/assets/ad74ab3e-a354-4345-84bb-0324711a35f5)

### Any other information that may be helpful

![grafik](https://github.com/user-attachments/assets/5e8dc89f-832c-4d4e-8079-6be835dc1c6a)
