### DISCUSSION TITLE
[Config Support]: How to eliminate False positives for parked cars (Stationary Objects)

### DISCUSSION THREAD

**Discussion by beeptech13** [blakeblackshear/frigate#14800] [Config Support]
### Describe the problem you are having

I get a lot of car images for parked cars.  I tried following instructions about removing stationary objects with the following commands but it didn't work.  I'm not sure exactly where I should put the commands.

detect:
  stationary:
    interval: 50
    threshold: 50

Should this go under each camera in the config file?  If so, to what level should it be indented?  Also, any help on things that could be improved in my config file would be greatly appreciated.  Thanks in advance.

### Version

0.14.0-7c39b17

### Frigate config file

```yaml
database:
  path: /config/frigate.db
mqtt:
  host: 192.168.1.221
  user: mqtt-user
  password: <pass>
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
ffmpeg:
  hwaccel_args: preset-vaapi
record:
  enabled: true
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - face
      - license_plate
      - dog
      - cat
      - car
      - amazon
      - fedex
      - ups
      - package

# Include all cameras by default in Birdseye view
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 2560
  # Optional: Height of the output resolution (default: shown below)
  height: 1440
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  restream: true

objects:
  # Optional: list of objects to track (frigate+ list)
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package

  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  # mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.79

go2rtc:
  streams:
    front_door:
      - rtsp://192.168.1.1:####/#########
      - birdseye -> restream
    front_door_sub:
      - rtsp://192.168.1.1:####/#########
    front_door_package:
      - rtsp://192.168.1.1:####/#########
    front_driveway:
      - rtsp://admin:######@192.168.8.202:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - birdseye -> restream
    front_driveway_sub:
      - rtsp://admin:#######@192.168.8.202:554/cam/realmonitor?channel=1&subtype=2 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    frontlawn:
      - rtsp://admin:#######@192.168.8.203:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - birdseye -> restream
    frontlawn_sub:
      - rtsp://admin:#######@192.168.8.203:554/cam/realmonitor?channel=1&subtype=2 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    frontyard:
      - rtsps://192.168.1.1:####/############# # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - birdseye -> restream
    frontyard_sub:
      - rtsps://192.168.1.1:####/#############
    backyard_stairs:
      - rtsp://admin:#######@192.168.8.201:554/h264Preview_01_main # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - ffmpeg:backyard_stairs#audio=aac   # <- copy of the stream which transcodes audio to aac
      - birdseye -> restream
    backyard_stairs_sub:
      - rtsp://admin:#######@192.168.8.201:554/h264Preview_01_sub # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    backyard_main:
      - rtsp://admin:#######@192.168.8.207:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - birdseye -> restream
    backyard_main_sub:
      - rtsp://admin:#######@192.168.8.207:554/cam/realmonitor?channel=1&subtype=2 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    backyard_corner:
      - rtsps://192.168.1.1:####/##############
      - birdseye -> restream
    backyard_corner_sub:
      - rtsps://192.168.1.1:####/##############
    backyard_on_shed:
      - rtsp://admin:#######@192.168.8.204:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - birdseye -> restream
    backyard_on_shed_sub:
      - rtsp://admin:#######@192.168.8.204:554/cam/realmonitor?channel=1&subtype=2 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg


cameras:
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 480
      height: 360
      fps: 10

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package


    motion:
      mask: 
        0.233,0.632,0.711,0.565,0.706,0.258,0.542,0.112,0.443,0.086,0.361,0.107,0.287,0.112,0.227,0.356
    objects:
      filters:
        car:
          mask: 0.235,0.607,0.711,0.559,0.706,0.378,0.229,0.41
  front_door_package:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_package # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1600
      height: 1200
      fps: 2

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - package

  front_driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_driveway_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
      stationary:
        interval: 50
        threshold: 50

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package

    motion:
      mask: 0.931,0.298,0.514,0.188,0.161,0.189,0.09,0.208,0.002,0.237,0,0,1,0.001,1,0.234
    objects:
      filters:
        car:
          mask: 0,0.194,0.227,0.135,0.59,0.112,1,0.198,1,0,0,0

  frontyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
      stationary:
        interval: 50
        threshold: 50

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package

    objects:
      filters:
        car: {}
    zones: {}
    review: {}
    motion:
      mask:
        - 0.206,0.993,0.35,0.408,0.473,0.376,0.545,0.586,0.579,0.542,0.615,0.534,0.661,0.53,0.746,0.494,0.792,0.712,0.895,0.708,0.974,0.668,1,1
        - 0.163,0.003,0.162,0.037,0.096,0.035,0.094,0.001
  frontlawn:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/frontlawn # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontlawn_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
      stationary:
        interval: 50
        threshold: 50

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package
    motion:
      mask: 0,0.458,1,0.4,1,0,0,0
    objects:
      filters:
        car:
          mask:
            - 0.024,0.041,0.327,0.043,0.341,0.209,0.015,0.227
            - 0.808,0.049,0.799,0.209,0.995,0.201,0.996,0.027
  backyard_corner:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_corner # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_corner_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - dog
          - cat

    motion:
      mask:
        - 0.4,0.57,0.464,0.509,0.421,0.317,0.437,0.119,0.385,0.134,0.341,0.161,0.392,0.339
        - 0.552,0.079,0.555,0.235,0.57,0.287,0.537,0.287,0.533,0.223,0.5,0.093
        - 0.811,1,0.596,0.617,0.38,0.651,0.205,0.758,0.173,1,0.554,1,0.576,1
        - 0,1,0.172,1,0.205,0.756,0.377,0.647,0.265,0.46,0.28,0.395,0.37,0.193,0.391,0,0,0
        - 0.831,0,0.846,0.106,0.848,0.188,0.864,0.251,0.793,0.256,0.767,0.141,0.79,0.058,0.765,0

  backyard_on_shed:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_on_shed # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_on_shed_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
        - 0,0,0,720,95,720,283,409,347,353,406,286,440,191,443,96,506,91,508,0,399,0
        - 1001,115,930,237,894,434,845,419,894,79
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - dog
          - cat

  backyard_stairs:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_stairs # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_stairs_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 7

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - dog
          - cat
    motion:
      mask:
        - 640,0,592,37,573,71,558,137,524,146,494,111,550,52,547,0


  backyard_main:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_main # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_main_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
      stationary:
        interval: 50
        threshold: 50

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - dog
          - cat
    motion:
      mask:
        - 1,0,1,0.665,0.903,0.366,0.821,0.329,0.852,0
        - 0.834,0.207,0.803,0.395,0.758,0.695,0.712,0.724,0.687,0.66,0.751,0.432,0.73,0.186
        - 0.287,0.445,0.278,0.67,0.382,0.687,0.33,0.434,0.347,0.175,0.215,0.186
        - 0.062,0.622,0.12,0.583,0.064,0.436,0.051,0.237,0,0.265
        - 0.174,0.297,0.231,0.314,0.202,0.192,0.184,0.191
        - 0.141,0,0,0,0,0.245
version: 0.14
camera_groups:
  Front_Yard:
    order: 1
    icon: LuDoorOpen
    cameras:
      - front_driveway
      - frontlawn
      - front_door
      - front_door_package
      - frontyard
  Backyard:
    order: 2
    icon: LuPalmtree
    cameras:
      - backyard_main
      - backyard_on_shed
      - backyard_corner
      - backyard_stairs
```

### Relevant Frigate log output

```shell
I don't have an error, just get false positives.
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
unraid installation
```

### Object Detector

Coral
