### DISCUSSION TITLE
[Bug]: 0.15.0-beta1 - recording preview turns black instead of playing timelapse video

### DISCUSSION THREAD

**Discussion by QBANIN** [blakeblackshear/frigate#14811] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After hovering mouse cursor over recording thumbnail/preview it turns black instead of playing timelapse video. On some recordings works fine for a while but eventually this bug hits them too.

This is happening after upgrade from 0.14.1 to 0.15-beta1. 0.14.x was ok.

### Steps to reproduce

1. Open Frigate
2. Navigate to Review panel
3. Hover mouse cursor over one of recordins preview.
4. Preview turns into black window
![obraz](https://github.com/user-attachments/assets/6dad6b3d-d4d1-4476-96e2-cc158547973c)

### Version

0.15.0-beta1

### In which browser(s) are you experiencing the issue with?

Latest Firefox/Chrome/Brave Browser

### Frigate config file

```yaml
mqtt:
  host: x.x.x.x
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxx
  password: xxxxxxxxxxxx

detectors:
  deepstack:
    api_url: http://yyyyyyyyyyyyy:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.1

genai:
  enabled: true
  provider: ollama
  base_url: http://yyyyyyyyyyyyyy:11434
  model: llava:7b

logger:
  default: info
  logs:
    frigate.event: debug

birdseye:
  enabled: false
  width: 1280
  height: 720
  quality: 8
  mode: objects

ffmpeg:
#  global_args: -hide_banner -loglevel warning
  hwaccel_args: auto
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    udp -use_wallclock_as_timestamps 1
  output_args:
    detect: -threads 4 -f rawvideo -pix_fmt yuv420p
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -filter:v scale=4096:-1 -c:v h264_nvenc -codec:a aac
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    record: preset-record-generic-audio-copy
#    rtmp: -c copy -f flv
go2rtc:
  streams:
    one:
      - rtsp://xxxxxxxxxxxxxxxxx/h264Preview_01_sub


record:
  enabled: true
  expire_interval: 60
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 7
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 7
    pre_capture: 5
    post_capture: 5

snapshots:
  enabled: true
  timestamp: false
  bounding_box: false
  crop: true
#  required_zones: []
  retain:
    default: 14
    objects:
      person: 14
      car: 14
      bus: 14
      dog: 14
      cat: 14
      bicycle: 14
      motorcycle: 14

live:
  height: 720
  quality: 8

timestamp_style:
  position: bl
  format: '%d/%m/%Y %H:%M:%S'
  effect: shadow

cameras:
  front:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    motion:
      threshold: 20
      contour_area: 5
      delta_alpha: 1.0 # def 0.2
      frame_alpha: 1.0 # def 0.2
      frame_height: 50
      improve_contrast: 'true'
      mask:
        - 0,0,1280,0,1280,0,1280,215,0,213
        - 914,720,1280,720,1280,620
        - 24,720,24,680,341,679,341,720
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://xxxxxxxxxxxxxx/video0.sdp
          roles:
            - detect
#            - rtmp
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
      enabled: true
#      stationary:
#        interval: 5
    objects:
      track:
        - person
        - car
        - bus
        - dog
        - cat
        - bicycle
        - motorcycle

      filters:
        person:
          min_score: 0.5
          threshold: 0.5
          min_area: 2000
        car:
          min_score: 0.5
          threshold: 0.5
          min_area: 25000
        bus:
          min_score: 0.5
          threshold: 0.5
          min_area: 25000
        cat:
          min_score: 0.5
          threshold: 0.5
          min_area: 2000
        dog:
          min_score: 0.5
          threshold: 0.5
          min_area: 2000
        bicycle:
          min_score: 0.5
          threshold: 0.5
          min_area: 5000
        motorcycle:
          min_score: 0.5
          threshold: 0.5
          min_area: 5000

  one:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    motion:
      threshold: 20
#      contour_area: 10
      delta_alpha: 1.0 # def 0.2
#      frame_alpha: 0.5 # def 0.2
      frame_height: 100
      improve_contrast: 'true'
      lightning_threshold: 0.3
      mask:
        - 0.25,0.924,0.254,1,0,1,0,0.927
        - 0,0,1,0,1,0.248,1,0.638,0.857,0.418,0.827,0.371,0.833,0.321,0.707,0.135,0.612,0.062,0.537,0.04,0.45,0.038,0.453,0.098,0.461,0.127,0.466,0.164,0.464,0.238,0.448,0.34,0.301,0.451,0.268,0.369,0.277,0.278,0.262,0.129,0.146,0.251,0.092,0.31,0,0.42
      contour_area: 15
    detect:
      width: 1536
      height: 576
      fps: 10
      enabled: true
#        stationary:
#           interval: 5
    record:
      alerts:
        retain: {}
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 1
    objects:
      track:
        - person
        - car
        - bus
        - dog
        - cat
        - bicycle
        - motorcycle

      filters:
        person:
          min_score: 0.5
          threshold: 0.5
          min_area: 500
        car:
          min_score: 0.5
          threshold: 0.5
          min_area: 5000
        bus:
          min_score: 0.5
          threshold: 0.5
          min_area: 5000
        cat:
          min_score: 0.5
          threshold: 0.5
          min_area: 200
        dog:
          min_score: 0.5
          threshold: 0.5
          min_area: 200
        bicycle:
          min_score: 0.5
          threshold: 0.5
          min_area: 2000
        motorcycle:
          min_score: 0.5
          threshold: 0.5
          min_area: 2000



    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxx/one
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt
            -use_wallclock_as_timestamps 1
          hwaccel_args:
            - -c:v
            - h264_cuvid
          roles:
            - detect


        - path: rtsp://xxxxxxxxxxxxxxxxxxxxx/h265Preview_01_main
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt
            -use_wallclock_as_timestamps 1
          hwaccel_args:
            - -c:v
            - hevc_cuvid
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -codec:a copy

    review:
      alerts:
        required_zones:
          - podworko
          - ulica
          - przed_domem
          - druga_strona_ulicy

    # Optional: Configuration for AI generated tracked object descriptions
    genai:
      # Optional: Enable AI description generation (default: shown below)
      enabled: true
      # Optional: Use the object snapshot instead of thumbnails for description generation (default: shown below)
      use_snapshot: false
      # Optional: The default prompt for generating descriptions. Can use replacement
      # variables like "label", "sub_label", "camera" to make more dynamic. (default: shown below)
      # prompt: "Describe the {label} in the sequence of images with as much detail as possible. Do not describe the background."
      # Optional: Object specific prompts to customize description results
      # Format: {label}: {prompt}
      #object_prompts:
        #person: "My special person prompt."
      # Optional: objects to generate descriptions for (default: all objects that are tracked)
      objects:
        - person
        - dog
        - cat
      # Optional: Restrict generation to objects that entered any of the listed zones (default: none, all zones qualify)
      required_zones: []


version: 0.15-0
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1-tensorrt
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:rw
      - /opt/frigate/media:/media/frigate
      - ./trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1G


    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # go2rtc
    environment:
        FRIGATE_RTSP_PASSWORD: "zzzzzzzzzzzzzzzzzzz"
        NVIDIA_VISIBLE_DEVICES: "all"
        NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
        YOLO_MODELS: "yolov7x-640,yolov7x-320"
```

### Relevant Frigate log output

```shell
frigate  | 2024-11-05 13:34:09.274784795  192.168.10.21 - - [05/Nov/2024:13:34:09 +0100] "GET /api/preview/one/start/1730809239/end/1730809305/frames HTTP/1.1" 200 2 "http://xxxxxxxxxxxx/review" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "-"
frigate  | 2024-11-05 13:34:10.159942019  192.168.10.21 - - [05/Nov/2024:13:34:10 +0100] "GET /api/preview/one/start/1730809063/end/1730809129/frames HTTP/1.1" 200 2 "http://xxxxxxxxxxxx/review" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "-"
frigate  | 2024-11-05 13:34:11.040424394  192.168.10.21 - - [05/Nov/2024:13:34:11 +0100] "GET /api/preview/one/start/1730808653/end/1730808720/frames HTTP/1.1" 200 2 "http://xxxxxxxxx/review" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "-"
frigate  | 2024-11-05 13:34:11.938515042  192.168.10.21 - - [05/Nov/2024:13:34:11 +0100] "GET /api/preview/one/start/1730808179/end/1730808260/frames HTTP/1.1" 200 2 "http://xxxxxxxxxx/review" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "-"
frigate  | 2024-11-05 13:34:12.693214524  192.168.10.21 - - [05/Nov/2024:13:34:12 +0100] "GET /api/preview/one/start/1730808276/end/1730808383/frames HTTP/1.1" 200 2 "http://xxxxxxxxxx/review" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "-"
```

### Relevant go2rtc log output

```shell
2024-11-05 00:18:12.453281978  [INFO] Preparing new go2rtc config...
2024-11-05 00:18:13.384741893  [INFO] Starting go2rtc...
2024-11-05 00:18:13.556303991  00:18:13.556 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-05 00:18:13.556310959  00:18:13.556 INF config path=/dev/shm/go2rtc.yaml
2024-11-05 00:18:13.557156181  00:18:13.557 INF [api] listen addr=:1984
2024-11-05 00:18:13.557659327  00:18:13.557 INF [rtsp] listen addr=:8554
2024-11-05 00:18:13.558316386  00:18:13.558 INF [webrtc] listen addr=:8555/tcp
2024-11-05 00:18:22.457196195  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink 2 Duo and some noname model

### Screenshots of the Frigate UI's System metrics pages

![obraz](https://github.com/user-attachments/assets/ebb1b6eb-52f1-44ad-b85d-828e6b3a0a71)
