### DISCUSSION TITLE
[Config Support]: Eufy Battery Cameras snapshot and stream

### DISCUSSION THREAD

**Discussion by beze** [blakeblackshear/frigate#14827] [Config Support]
### Describe the problem you are having

As Everyone knows, battery cameras is not ideal, but it is what I have. I am running HASOS on an intel computer, with frigate, webrtc, go2rtc, mosquito, eufy integratione tc.

I do have a set of 4 Eufy 2c pro cameras, connected to painel solar. 

The RTSP feed is only started when it detects movement, meaning my dashboard stays with lot of black holes. 

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/3ddd6347-3114-4508-97fd-74a5904e90f7">

I sucessifull dia an automation to start the camera, create an snapshot on /media and stop the camera every minute.

My goal is to create a RTSP that will stream this image, and IF the camera starts to stream due to some detection, this stream will be used.

So first things first, I am not able to create a RTSP stream from the JPG file, can someone give me a hand with that?

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.5.111
  port: 1883
  user: hamqtt
  password: Teste336!
  topic_prefix: frigate
  client_id: frigate

motion:
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10

go2rtc:
  streams:

  corridor2:
    exec: ffmpeg -re -loop 1 -i /media/side_door.jpg -vf scale=640:360,format=yuv420p -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/corridor2

  

cameras:

  Corridor2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Corridor2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp  # For streaming with detected objects highlighted
    detect:
      width: 1280
      height: 720
      fps: 10
    live:
      stream_name: Corridor2  # Stream name for live view

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog

record:
  enabled: true
  retain: 
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: True
  bounding_box: True  # Highlight detected objects in snapshots
  retain:
    default: 5
    objects:
      person: 7

version: 0.14
```

### Relevant Frigate log output

```shell
On Frigate start, it still says the stream could not be found

2024-11-06 04:11:19.394498320  [2024-11-06 01:11:19] frigate.video                  ERROR   : corridor2: Unable to read frames from ffmpeg process.
2024-11-06 04:11:19.394544586  [2024-11-06 01:11:19] frigate.video                  ERROR   : corridor2: ffmpeg process is not running. exiting capture thread...
```

### Relevant go2rtc log output

```shell
no logs
```

### Frigate stats

```json
running
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

CPU (no coral)
