### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by ops244** [blakeblackshear/frigate#14826] [Config Support] [answered]
### Describe the problem you are having

hi, everything works with this configuration, I would like the detector to work on the second stream (SD)
. What did I do, nothing works, tell me how to add a second stream for the detector here, and leave this one only for recording?

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.
  user: 
  password: 


ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


snapshots:
  enabled: false
  retain:
    default: 5
    objects:
      person: 5
  quality: 75

go2rtc:
  exec: trace
  streams:
    Camera1:
      - rtsp://......@192.168.1...../stream1
      - ffmpeg:Camera1#audio=aac

cameras:
  Camera1:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    motion:
      threshold: 15
      contour_area: 5
      improve_contrast: 'true'
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true


objects:
  track:
    - person



record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 1
      mode: motion
      objects:
        person: 1
  expire_interval: 480
  sync_recordings: true
version: 0.14
```

### Relevant Frigate log output

```shell
There are no errors
```

### Relevant go2rtc log output

```shell
There are no errors
```

### Frigate stats

```json
There are no errors
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
There are no errors
```

### Object Detector

OpenVino
