### DISCUSSION TITLE
[Support]: 2way audio: No sound on Reolink Doorbell speakers

### DISCUSSION THREAD

**Discussion by christophprinz90** [blakeblackshear/frigate#14838] [General Support]
### Describe the problem you are having

Hi!

I am trying to setting up 2way-audio communication on my Reolink Doorbell in my Home Assistent dashboard.
Therefore, I installed the frigate integration in Home Assistant. 

My camera stream is working and I can hear the sound of the camera on my laptop (where I open the dashboard).
However, I am not able to hear any sounds on my reolink camera. 

I am kind of lost how to fix this issue. I am also using HTTPS.

Anybody an idea what I am doing wrong?

Thanks for you help.

best regards!

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Google Chrome

### Frigate config file

```yaml
mqtt:
  host: 192.168.68.65      # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user           # YOUR MQTT USERNAME
  password: mqtt_password    # YOUT MQTT PASSWORD
  stats_interval: 60

logger:
  default: debug
  logs:
   frigate.comms.mqtt: debug


go2rtc:
  streams:
    reolink:
      - ffmpeg:https://192.168.68.51/flv?port=554&amp;app=bcs&amp;stream=channel0_ext.bcs&amp;user=USER&amp;password=PASS
      - rtsp://USER:PASS@192.168.68.51:554/Preview_01_sub
      - ffmpeg:doorbell#audio=opus 

  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

##########################################################################

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASS@192.168.68.51:554/h264Preview_01_sub
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy

ui:
  live_mode: webrtc #Add at the end of config
```

### Relevant Frigate log output

```shell
- no errors
```

### Relevant go2rtc log output

```shell
- no errors
```

### FFprobe output from your camera

```shell
-
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

Reolink doorbell

**Comment by NickM-27** [comment]
You need to use the Frigate card for two way audio in home assistant

**Comment by christophprinz90** [comment]
This is my frigate card configuration:


```
type: custom:frigate-card
cameras:
  - camera_entity: camera.reolink_video_doorbell_wifi_fliessend
    live_provider: auto
    go2rtc:
      modes:
        - webrtc
      stream: reolink
menu:
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      priority: 100
      type: toggle
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
      alignment: opposing
    camera_ui:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
  style: overlay
  position: bottom
  button_size: 120
live:
  controls:
    thumbnails:
      mode: none
  auto_mute: all
  preload: true
  draggable: false
  zoomable: false
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
```




However, the microphone button does not appear in the dashboard-card.
