### DISCUSSION TITLE
No audio in 0.9.0 beta

### DISCUSSION THREAD

**Discussion by Minglarn** [blakeblackshear/frigate#1483] [Ask A Question] [answered]
Could be wrong place to ask this but.. 
Since 0.9.0-92aa16c-amd64 my Reolink cams wont record audio. 
When running 0.9.0-dada764-amd64 it works. No change in config.yaml.
At the moment i'm using this:
`  output_args:
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -codec:a aac
`
At the moment i'm running the lastest 0.9.0-1823bd0-amd64 and still have the issues.
What could be the change in dada vs later docker images?

**Comment by blakeblackshear** [comment, marked as answer]
Add those args to the record output_args. The latest versions use the record stream for clips.

**Reply by Minglarn** [reply]
Aha... ok.. Will try...

**Reply by Minglarn** [reply]
Made this, but no change... 

`record:
  enabled: False
  retain_days: 2
  events: True
  clips: -c:a aac`

Must be missing something..

**Reply by blakeblackshear** [reply]
You need to add it to the output_args for record.

```yaml
ffmpeg:
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```
