### DISCUSSION TITLE
[Bug]: 15 beta 1 /dev/shm "out of space"

### DISCUSSION THREAD

**Discussion by tmjpugh** [blakeblackshear/frigate#14849] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Frigate stops function after approx 10hrs due to "/dev/shm" out of space error.  Currently my /dev/shm size is 500mb.  I increased for testing with little/no change

### Steps to reproduce

1. install 15 beta 1
2. wait until error 
3.
...

### Version

0.15.0-33825f6

### In which browser(s) are you experiencing the issue with?

firefox

### Frigate config file

```yaml
################################
#           AUTH               #
################################
auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.18.0.0/24 # <---- this is the subnet for the internal docker compose network

tls:
  enabled: false


################################
#           MQTT               #
################################
mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate
  stats_interval: 60


################################
#          DETECTORS:          #
################################
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1


################################
#            MODEL             #
################################
#model:
  # Optional: path to the model (default: automatic based on detector)
#  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
#  labelmap_path: /config/labelmap.txt
  # Required: Object detection model input width (default: shown below)
#  width: 320
  # Required: Object detection model input height (default: shown below)
#  height: 320
  # Optional: Label name modifications. These are merged into the standard labelmap.
#  labelmap:
#    2: vehicle


################################
#           GLOBAL             #
################################
birdseye:
  enabled: true
  width: 2592
  height: 1944
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  mode: motion

#restream:
#  birdseye: true
#live:
#  #height: 500
#  quality: 1



################################
#            LOGGER            #
################################
#logger:
#  logs:
#    frigate.app: debug


################################
#            FFMPEG            #
################################
#ffmpeg:
#  hwaccel_args: preset-vaapi


################################
#            GO2RTC            #
################################
go2rtc:
#  log:
#    format: text
#    level: debug

  api:
    listen: :1984      # default ":1984", HTTP API port ("" - disabled), i think frigate relies on this using 1984 to start and changes prevents start
    #base_path: "/rtc"  # default "", API prefix for serve on suburl (/api => /rtc/api)
    #static_dir: "www"  # default "", folder for static files (custom web interface)
    #origin: "*"    

  webrtc:
    listen: :8555
    candidates:
      - 10.88.30.12:8555
      - frigate:8555


################################
#           STREAMS            #
################################
  streams:
    streams:
    birdseyemjpeg:
      - exec:ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye
        -c:v mjpeg -force_duplicated_matrix:v 1 -huffman:v 0 -pix_fmt:v yuvj420p -an
        -rtsp_transport tcp -f rtsp {{output}}

#    Frigate_Test:
#      - /media/frigate/recordings/2024-07-14/17/Frigate_Gate01/01.37.mp4
      #- rtsp://10.88.20.243:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
##      - ffmpeg:Frigate_Attic#audio=opus

#    Frigate_Doorbell:
#      #- rtsp://admin:t$3rcm@@10.88.20.168/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
#      - rtsp://admin:t$3rcm@@10.88.20.168:554/cam/realmonitor?channel=1&subtype=1
#      #- "ffmpeg:Frigate_Doorbell#audio=opus"

    Frigate_FrontDr:
      - rtsp://homeassistant:3m0h@10.88.20.93:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:Frigate_FrontDr

    Frigate_Gate01:
      - rtsp://homeassistant:3m0h@10.88.20.218:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:Frigate_Gate01#audio=opus

    Frigate_Gate02:
      - rtsp://homeassistant:3m0h@10.88.20.125:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:Frigate_Gate03

#    Frigate_Gate03:
#      - rtsp://homeassistant:3m0h@10.88.20.106:554/cam/realmonitor?channel=1&subtype=0
# #     - ffmpeg:Frigate_Pool2

    Frigate_Goat:
      - rtsp://admin:w@n$v13w@10.88.20.35/live/ch0
#      - "ffmpeg:Frigate_Goat#audio=opus"

    Frigate_Goat01:
      - rtsp://homeassistant:3m0h@10.60.27.40:554/cam/realmonitor?channel=1&subtype=0
#      - "ffmpeg:Frigate_Goat2#audio=opus"

    Frigate_Goat01low:
      - rtsp://homeassistant:3m0h@10.60.27.40:554/cam/realmonitor?channel=1&subtype=1
#      - "ffmpeg:Frigate_Goat2#audio=opus"

    Frigate_MasterPatio:
      - rtsp://homeassistant:3m0h@10.88.20.107:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Frigate_MasterPatio#audio=opus

    Frigate_Pool:
      - rtsp://homeassistant:3m0h@10.88.20.66:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Frigate_Pool#audio=opus

    Frigate_South01:
      - rtsp://homeassistant:3m0h@10.88.20.111:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:Frigate_South01

    Frigate_South02:
      - rtsp://homeassistant:3m0h@10.88.20.149:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:Frigate_South02

#    Frigate_TempRat:
#      - rtsp://homeassistant:3m0h@10.88.20.92:554/cam/realmonitor?channel=1&subtype=0
##      - ffmpeg:Frigate_TempRat

#    Frigate_xtra:
#      - rtsp://homeassistant:3m0h@10.88.20.42:554/cam/realmonitor?channel=1&subtype=0
##      - ffmpeg:Frigate_xtra

#    Frigate_Reolink:
#      - rtsp://admin:reolink@10.88.20.163:554/h264Preview_01_main
#      - "ffmpeg:Frigate_Reolink#audio=opus"


################################
#           HOMEKIT            #
################################
#  homekit:
#    Frigate_Attic:  # same stream ID from streams list
#      pin: 12345678  # custom PIN, default: 19550224
      #name:  # custom camera name, default: generated from stream ID
      #device_id: # custom ID, default: generated from stream ID
      #device_private: # custom key, default: generated from stream ID



################################
#          CAMERAS             #
################################
cameras:

######
#Attic
#  Frigate_Test:
#    birdseye:
#      enabled: false
#
#    ffmpeg:
#      inputs:
#        #- path: rtsp://admin:w@n$v13w@10.88.20.36/live/ch0
#        #RESTREAM
#        - path: rtsp://frigate:8554/Frigate_Test
#          roles:
#            - detect
##      output_args:
##        record: preset-record-generic-audio-aac

#    detect:
#      width: 3840
#      height: 2160
#      fps: 15
#      enabled: false
##      max_disappeared: 25

##    best_image_timeout: 30
##    record:
##      enabled: true
###      retain:
##        days: 10
##      events:
##        retain:
##          default: 30

#    objects:
#      track:
#        - animal
#        - car
#        - motorcycle
#        - person


#    snapshots:
#      enabled: false
#      timestamp: false
#      bounding_box: true
#      crop: false
##      height: 175
#      required_zones: []
#      retain:
#        default: 30
##        objects:
##          person: 15

#    motion:
#      mask: 0.93,0.038,0.994,0.036,0.997,0.077,0.929,0.08
  Frigate_FrontDr:
    birdseye:
      mode: motion

    ffmpeg:
      inputs:
       # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.93:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      # RESTREAM    
        - path: rtsp://frigate:8554/Frigate_FrontDr
          roles:
            - record

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: true
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 15
      detections:
        retain:
          days: 15
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person
      filters:
        car:
          min_score: 0.8
          threshold: 0.9

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10
#        objects:
#          person: 15

#    motion:
#      contour_area: 50

    zones:
      entry:
        coordinates: 579,480,491,480,418,432,561,329,658,386

    motion:
      mask:
        - 0.873,0.034,0.972,0.032,0.972,0.075,0.866,0.081
        - 0.278,0.007,0.357,0.424,0.626,0.009
        - 0.009,0.075,0.075,0.263,0.202,0.025
  Frigate_Gate01:
    ffmpeg:
      inputs:
       # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.218:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
#       # HD STREAM
#       - path: rtsp://homeassistant:3m0h@10.88.20.111:554/cam/realmonitor?channel=1&subtype=0
#         roles:
#           - restream
       # RE Stream  
        - path: rtsp://frigate:8554/Frigate_Gate01
          roles:
            - record
#            - audio

      output_args:
        record: preset-record-generic-audio-aac

#    audio:
#      enabled: true

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: true
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 20
      detections:
        retain:
          days: 20
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
#      required_zones: []
      retain:
        default: 10
 #       objects:
 #        person: 15

    #motion:
    #  contour_area: 50

    motion:
      mask:
        - 0,0,0.005,0.366,0.118,0.32,0.13,0.237,0.523,0.219,0.909,0.235,1,0.264,1,0
        - 0.209,0.454,0.375,0.445,0.381,0.765,0.23,0.8
        - 0.902,0.285,1,0.308,1,0.601,0.869,0.482
      threshold: 54
      contour_area: 10
      improve_contrast: true
    zones:
      outside:
        coordinates: 0.393,0.34,0.391,0.484,0.389,0.596,0.839,0.447,0.684,0.32
        inertia: 2
      mailbox:
        coordinates: 0.126,0.436,0.112,0.376,0.133,0.327,0.155,0.311,0.174,0.36,0.179,0.414
        inertia: 2
    review:
      alerts:
        required_zones:
          - mailbox
          - outside
      detections:
        required_zones:
          - mailbox
          - outside

  Frigate_Goat:
    ui:
      order: 10
    birdseye:
      enabled: false

    ffmpeg:
      inputs:
#        - path: rtsp://admin:w@n$v13w@10.88.20.35/live/ch0
       # Restream 
        - path: rtsp://frigate:8554/Frigate_Goat
          roles:
            - detect
            - record

#      output_args:
#        record: preset-record-generic-audio-aac

    detect:
      width: 1280
      height: 720
      fps: 10
      enabled: false
#       max_disappeared: 25

#    best_image_timeout: 30

    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 30
 #       objects:
 #         person: 15

 #   motion:
 #     contour_area: 50


  #######################################
  #                GOAT1                #
  #######################################
  Frigate_Goat01:
    ui:
      order: 9
    birdseye:
      enabled: false

    ffmpeg:
      inputs:
       # SD Stream
        - path: rtsp://frigate:8554/Frigate_Goat01low
          roles:
            - detect
      # RESTREAM
        - path: rtsp://frigate:8554/Frigate_Goat01
          roles:
            - record

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: false
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 20
      detections:
        retain:
          days: 20
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10
 #       objects:
 #        person: 15

  #  motion:
  #    contour_area: 50


  #######################################
  #               MASTER                #
  #######################################
    motion:
      mask: 0.872,0.031,0.97,0.034,0.975,0.076,0.877,0.087
  Frigate_MasterPatio:
    ffmpeg:
      inputs:
      # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.107:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
#     # HD STREAM
        - path: rtsp://frigate:8554/Frigate_MasterPatio
          roles:
            - record
            - audio

      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: true
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 15
      detections:
        retain:
          days: 15
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person
    snapshots: # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10
#        objects:
#          person: 15

   # motion:
   #   contour_area: 50

    zones:
      entry:
        coordinates: 0.726,1,0.467,1,0.888,0.393,0.957,0.443
        inertia: 3
      leaving:
        coordinates: 704,92,704,120,591,62,596,40

  #######################################
  #               POOL                  #
  #######################################
    motion:
      mask: 0.73,0.034,0.971,0.03,0.974,0.079,0.728,0.081
    review:
      alerts:
        required_zones: entry
      detections:
        required_zones: entry
  Frigate_Pool:
    ffmpeg:
      inputs:
      # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.66:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      # RESTREAM
        - path: rtsp://frigate:8554/Frigate_Pool
          roles:
            - record
            - audio

      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: true
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 15
      detections:
        retain:
          days: 15
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10
 #       objects:
 #         person: 15

    #motion:
    #  contour_area: 50

    zones:
      entry:
        coordinates: 134,480,277,480,144,339,80,366
      water:
        coordinates: 414,136,647,215,677,131,486,63,395,98



  #######################################
  #              POOL2                  #
  #######################################
    motion:
      mask: 0.866,0.033,0.969,0.031,0.973,0.079,0.869,0.082
  Frigate_Gate02:
    ffmpeg:
      inputs:
       # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.125:554/cam/realmonitor?channel=1&subtype=1
        #- path: rtsp://admin:reolink@10.88.20.163:554/h264Preview_01_sub
          roles:
            - detect
       # RESTREAM  
        - path: rtsp://frigate:8554/Frigate_Gate02
          roles:
            - record
            - audio

      output_args:
        record: preset-record-generic-audio-aac

    audio:
      enabled: true


    detect:
      width: 704
      height: 480
      fps: 10
      enabled: false
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 20
      detections:
        retain:
          days: 20
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10

#    motion:
#      contour_area: 50



  #########################################
  #                SOUTH01                #
  #########################################
    motion:
      mask: 0,0,1,0,1,0.499,0,0.326
  Frigate_South01:
    ffmpeg:
      inputs:
       # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.111:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
#       # HD STREAM
#       - path: rtsp://homeassistant:3m0h@10.88.20.111:554/cam/realmonitor?channel=1&subtype=0
#         roles:
#           - restream
       # RE Stream  
        - path: rtsp://frigate:8554/Frigate_South01
          roles:
            - record

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: true
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 20
      detections:
        retain:
          days: 20
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10
 #       objects:
 #        person: 15

    #motion:
    #  contour_area: 50


  #######################################
  #             SOUTH02                 #
  #######################################
    motion:
      mask: 0.261,0,0.934,0,0.971,0.084,0.858,0.082,0.241,0.062
  Frigate_South02:
    ffmpeg:
      inputs:
       # SD Stream
        - path: 
            rtsp://homeassistant:3m0h@10.88.20.149:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
       # RESTREAM  
        - path: rtsp://frigate:8554/Frigate_South02
          roles:
            - record

    detect:
      width: 704
      height: 480
      fps: 10
      enabled: true
#       max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 20
      detections:
        retain:
          days: 20
    objects:
      track:
        - animal
        - car
        - motorcycle
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
#      height: 175
      required_zones: []
      retain:
        default: 10
        #objects:
          #person: 15

    #motion:
    #  contour_area: 50




    motion:
      mask: 0,0,1,0,1,0.265,0,0.067
version: 0.15-0
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
services:

###############################################
#               FRIGATE                       #
###############################################
  frigate:
    container_name: frigate
    hostname: frigate  
    privileged: false
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:0.14.1
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "500mb" #((1280 * 720 * 1.5 * qtycameras + 270480) / 1048576) * 8 + 30)) 11/4/24 increased to 4GB
    devices:
      - /dev/tpu_d0:/dev/apex_0
      - /dev/tpu_d1:/dev/apex_1      
    volumes:
      - "/srv/cam_6/media_frigate:/media/frigate"
      - "/srv/main/docker/frigate/application/config2:/config"
#      - "/srv/main/docker/frigate/application/config/frigate-go2rtc.yaml:/config/frigate-go2rtc.yaml"
#      - "/srv/main/docker/frigate/application/config/labelmap.txt:/config/labelmap.txt:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984/tcp" # go2rtc UI
      - "5000:5000/tcp" # frigate UI
      - "8971:8971/tcp" # frigate UI   
      - "8554:8554/tcp" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8282:8080/tcp" # WebRTC over udp
    environment:
      -FRIGATE_RTSP_PASSWORD: "frigate"
      -PLUS_API_KEY: "5fa2c913-e7ec-4de6-807c-df925d0f8ec7:9e6da3dc1914f549aa16386dd33bce21fa117c7c"
    networks:
      reverseproxy:
      dockerlocal:
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 17000M
        reservations:
          cpus: '2'
          memory: 8000M
        
         
##########################################
#              NETWORKS                  #
##########################################      
networks:
  dockerlocal:
    external: true 
  reverseproxy:
    external: trueservices:

###############################################
#               FRIGATE                       #
###############################################
  frigate:
    container_name: frigate
    hostname: frigate  
    privileged: false
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:0.14.1
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "500mb" #((1280 * 720 * 1.5 * qtycameras + 270480) / 1048576) * 8 + 30)) 11/4/24 increased to 4GB
    devices:
      - /dev/tpu_d0:/dev/apex_0
      - /dev/tpu_d1:/dev/apex_1      
    volumes:
      - "/srv/cam_6/media_frigate:/media/frigate"
      - "/srv/main/docker/frigate/application/config2:/config"
#      - "/srv/main/docker/frigate/application/config/frigate-go2rtc.yaml:/config/frigate-go2rtc.yaml"
#      - "/srv/main/docker/frigate/application/config/labelmap.txt:/config/labelmap.txt:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984/tcp" # go2rtc UI
      - "5000:5000/tcp" # frigate UI
      - "8971:8971/tcp" # frigate UI   
      - "8554:8554/tcp" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8282:8080/tcp" # WebRTC over udp
    environment:
      -FRIGATE_RTSP_PASSWORD: "passwd"
      -PLUS_API_KEY: "key"
    networks:
      reverseproxy:
      dockerlocal:
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 17000M
        reservations:
          cpus: '2'
          memory: 8000M
        
         
##########################################
#              NETWORKS                  #
##########################################      
networks:
  dockerlocal:
    external: true 
  reverseproxy:
    external: true
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

amcrest

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

rollback to 14 to fix. reported for info only
