### DISCUSSION TITLE
[HW Accel Support]: v0.15.0-b1 Apple Mac Mini ffmpeg hwaccel_args

### DISCUSSION THREAD

**Discussion by DaveTSG** [blakeblackshear/frigate#14856] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I was previously running v0.13 without any issues.
I then upgraded to v0.15.0-b1. I noted I might need to change hwaccel (as noted in the breaking changes section of [the release notes](https://github.com/blakeblackshear/frigate/releases/tag/v0.15.0-beta1)) as I am running Frigate via Docker on an older Apple Mac Mini (with an Intel CPU) (the Mac is running Debian v12.6, not MacOS).

My original config.yml file appeared to be working fine under v0.15.0-b1. In that original file, I had 

```
ffmpeg:
  hwaccel_args: preset-vaapi
```
Everything worked fine (I was able to use the live views of the various cameras, use the review screen, upload snapshots to Frigate+, and so on), but the Frigate log had many ffmpeg-related errors, e.g.:

> 2024-11-08 16:42:06.693641560  [INFO] Preparing Frigate...
> 2024-11-08 16:42:06.697752537  [INFO] Starting Frigate...
> 2024-11-08 16:42:08.698666508  [2024-11-08 16:42:08] frigate.util.config            INFO    : Checking if frigate config needs migration...
> 2024-11-08 16:42:08.713339332  [2024-11-08 16:42:08] frigate.util.config            INFO    : frigate config does not need migration...
> 2024-11-08 16:42:08.752839941  [2024-11-08 16:42:08] frigate.app                    INFO    : Starting Frigate (0.15.0-33825f6)
> 2024-11-08 16:42:08.764238670  [2024-11-08 16:42:08] peewee_migrate.logs            INFO    : Starting migrations
> 2024-11-08 16:42:08.764600805  [2024-11-08 16:42:08] peewee_migrate.logs            INFO    : There is nothing to migrate
> 2024-11-08 16:42:08.837151639  [2024-11-08 16:42:08] frigate.app                    INFO    : Recording process started: 343
> 2024-11-08 16:42:08.837541974  [2024-11-08 16:42:08] frigate.app                    INFO    : Review process started: 347
> 2024-11-08 16:42:08.839666954  [2024-11-08 16:42:08] frigate.app                    INFO    : go2rtc process pid: 98
> 2024-11-08 16:42:08.854278528  [2024-11-08 16:42:08] detector.coral                 INFO    : Starting detection process: 360
> 2024-11-08 16:42:11.497554127  [2024-11-08 16:42:08] frigate.app                    INFO    : Output process started: 379
> 2024-11-08 16:42:11.497622709  [2024-11-08 16:42:08] frigate.app                    INFO    : Camera processor started for FrontDoor: 407
> 2024-11-08 16:42:11.497649466  [2024-11-08 16:42:08] frigate.app                    INFO    : Camera processor started for PackageCam: 408
> 2024-11-08 16:42:11.497671080  [2024-11-08 16:42:08] frigate.app                    INFO    : Camera processor started for GarageCam: 411
> 2024-11-08 16:42:11.497695484  [2024-11-08 16:42:08] frigate.app                    INFO    : Capture process started for FrontDoor: 413
> 2024-11-08 16:42:11.499517338  [2024-11-08 16:42:08] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
> 2024-11-08 16:42:11.499717922  [2024-11-08 16:42:11] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
> 2024-11-08 16:42:11.499743511  [2024-11-08 16:42:08] frigate.app                    INFO    : Capture process started for PackageCam: 421
> 2024-11-08 16:42:11.499776118  [2024-11-08 16:42:08] frigate.app                    INFO    : Capture process started for GarageCam: 428
> 2024-11-08 16:42:11.499880174  [2024-11-08 16:42:09] frigate.api.fastapi_app        INFO    : Starting FastAPI app
> 2024-11-08 16:42:11.499882239  [2024-11-08 16:42:09] frigate.api.fastapi_app        INFO    : FastAPI started
> 2024-11-08 16:43:36.604131535  [2024-11-08 16:43:36] frigate.video                  ERROR   : GarageCam: Unable to read frames from ffmpeg process.
> 2024-11-08 16:43:36.604170599  [2024-11-08 16:43:36] frigate.video                  ERROR   : GarageCam: ffmpeg process is not running. exiting capture thread...
> 2024-11-08 16:43:38.974960447  [2024-11-08 16:43:38] watchdog.GarageCam             ERROR   : Ffmpeg process crashed unexpectedly for GarageCam.
> 2024-11-08 16:43:38.975057665  [2024-11-08 16:43:38] watchdog.GarageCam             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> 2024-11-08 16:43:38.975059937  [2024-11-08 16:43:38] ffmpeg.GarageCam.detect        ERROR   : [AVHWFramesContext @ 0x7ff894089640] Failed to sync surface 0x13: 1 (operation failed).
> 2024-11-08 16:43:38.975087990  [2024-11-08 16:43:38] ffmpeg.GarageCam.detect        ERROR   : [hwdownload @ 0x7ff8a4003980] Failed to download frame: -5.
> 2024-11-08 16:43:38.975100703  [2024-11-08 16:43:38] ffmpeg.GarageCam.detect        ERROR   : [vf#0:0 @ 0x556cb7c70e80] Error while filtering: Input/output error
> 2024-11-08 16:43:38.975180298  [2024-11-08 16:43:38] ffmpeg.GarageCam.detect        ERROR   : [vf#0:0 @ 0x556cb7c70e80] Task finished with error code: -5 (Input/output error)
> 2024-11-08 16:43:38.975182547  [2024-11-08 16:43:38] ffmpeg.GarageCam.detect        ERROR   : [vf#0:0 @ 0x556cb7c70e80] Terminating thread with return code -5 (Input/output error)
> 2024-11-08 16:43:55.397311730  [2024-11-08 16:43:55] frigate.record.export          ERROR   : Failed to export recordings for command /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -y -protocol_whitelist pipe,file,http,tcp -i http://127.0.0.1:5000/vod/FrontDoor/start/1731042043/end/1731042103/index.m3u8 -c copy -movflags +faststart /media/frigate/exports/FrontDoor_vtbfwy.mp4
> 2024-11-08 16:43:55.397314799  [2024-11-08 16:43:55] frigate.record.export          ERROR   : [http @ 0x55571d9e7680] HTTP error 404 Not Found
> 2024-11-08 16:43:55.397330867  [in#0 @ 0x55571d9e69c0] Error opening input: Server returned 404 Not Found
> 2024-11-08 16:43:55.397332608  Error opening input file http://127.0.0.1:5000/vod/FrontDoor/start/1731042043/end/1731042103/index.m3u8.
> 2024-11-08 16:43:55.397333798  Error opening input files: Server returned 404 Not Found
> 2024-11-08 16:45:05.444024  2024-11-08 16:43:55.397334636
> 2024-11-08 16:43:55.398815228  Exception in thread Thread-7:
> 2024-11-08 16:43:55.398818557  Traceback (most recent call last):
> 2024-11-08 16:43:55.398819755    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
> 2024-11-08 16:43:55.399695914      self.run()
> 2024-11-08 16:43:55.399698664    File "/opt/frigate/frigate/record/export.py", line 338, in run
> 2024-11-08 16:43:55.399761841      Path(thumb_path).unlink(missing_ok=True)
> 2024-11-08 16:43:55.399769317    File "/usr/lib/python3.9/pathlib.py", line 1343, in unlink
> 2024-11-08 16:43:55.400245965      self._accessor.unlink(self)
> 2024-11-08 16:43:55.400282544  IsADirectoryError: [Errno 21] Is a directory: '.'
> 2024-11-08 16:44:47.369924867  [2024-11-08 16:44:47] frigate.video                  ERROR   : FrontDoor: Unable to read frames from ffmpeg process.
> 2024-11-08 16:44:47.369968706  [2024-11-08 16:44:47] frigate.video                  ERROR   : FrontDoor: ffmpeg process is not running. exiting capture thread...
> 2024-11-08 16:44:48.960419439  [2024-11-08 16:44:48] watchdog.FrontDoor             ERROR   : Ffmpeg process crashed unexpectedly for FrontDoor.
> 2024-11-08 16:44:48.960515479  [2024-11-08 16:44:48] watchdog.FrontDoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> 2024-11-08 16:44:48.960517846  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 4 with DTS 83090137393691, packet 5 with DTS 83090137398432
> 2024-11-08 16:44:48.960519432  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 8 with DTS 83090137398438, packet 9 with DTS 83090137401575
> 2024-11-08 16:44:48.960534687  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 1: packet 15 with DTS 83090137406565, packet 16 with DTS 83090137409655
> 2024-11-08 16:44:48.960563047  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 28 with DTS 83090137417718, packet 29 with DTS 83090137422286
> 2024-11-08 16:44:48.960649317  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 40 with DTS 83090137430662, packet 41 with DTS 83090137434492
> 2024-11-08 16:44:48.960651156  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 1: packet 45 with DTS 83090137434492, packet 46 with DTS 83090137438367
> 2024-11-08 16:44:48.960652628  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 1: packet 49 with DTS 83090137438414, packet 50 with DTS 83090137443081
> 2024-11-08 16:44:48.960659905  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 1: packet 54 with DTS 83090137443183, packet 55 with DTS 83090137446404
> 2024-11-08 16:44:48.960759393  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 1: packet 62 with DTS 83090137451162, packet 63 with DTS 83090137455167
> 2024-11-08 16:44:48.960761743  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 64 with DTS 83090137455168, packet 65 with DTS 83090137458493
> 2024-11-08 16:44:48.960774462  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 80 with DTS 83090137471964, packet 81 with DTS 83090137475097
> 2024-11-08 16:44:48.960831075  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 1: packet 88 with DTS 83090137475134, packet 89 with DTS 83090137478766
> 2024-11-08 16:44:48.960833454  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [rtsp @ 0x5653c54a8240] DTS discontinuity in stream 0: packet 84 with DTS 83090137475133, packet 85 with DTS 83090137478794
> 2024-11-08 16:44:48.960842284  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [AVHWFramesContext @ 0x7ff59c0469c0] Failed to sync surface 0x10: 1 (operation failed).
> 2024-11-08 16:44:48.960861384  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [hwdownload @ 0x7ff5a8003980] Failed to download frame: -5.
> 2024-11-08 16:44:48.960887109  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [vf#0:0 @ 0x5653c5596f00] Error while filtering: Input/output error
> 2024-11-08 16:44:48.960906326  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [vf#0:0 @ 0x5653c5596f00] Task finished with error code: -5 (Input/output error)
> 2024-11-08 16:44:48.960928896  [2024-11-08 16:44:48] ffmpeg.FrontDoor.detect        ERROR   : [vf#0:0 @ 0x5653c5596f00] Terminating thread with return code -5 (Input/output error)
> 2024-11-08 16:44:51.467601880  [2024-11-08 16:44:51] frigate.video                  ERROR   : GarageCam: Unable to read frames from ffmpeg process.
> 2024-11-08 16:44:51.467615489  [2024-11-08 16:44:51] frigate.video                  ERROR   : GarageCam: ffmpeg process is not running. exiting capture thread...
> 2024-11-08 16:44:58.987252387  [2024-11-08 16:44:58] watchdog.GarageCam             ERROR   : Ffmpeg process crashed unexpectedly for GarageCam.
> 2024-11-08 16:44:58.987301675  [2024-11-08 16:44:58] watchdog.GarageCam             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> 2024-11-08 16:44:58.987332737  [2024-11-08 16:44:58] ffmpeg.GarageCam.detect        ERROR   : [AVHWFramesContext @ 0x7f7bc0046580] Failed to sync surface 0xf: 1 (operation failed).
> 2024-11-08 16:44:58.987405741  [2024-11-08 16:44:58] ffmpeg.GarageCam.detect        ERROR   : [hwdownload @ 0x7f7bcc003980] Failed to download frame: -5.
> 2024-11-08 16:44:58.987407923  [2024-11-08 16:44:58] ffmpeg.GarageCam.detect        ERROR   : [vf#0:0 @ 0x5584b25e7400] Error while filtering: Input/output error
> 2024-11-08 16:44:58.987417286  [2024-11-08 16:44:58] ffmpeg.GarageCam.detect        ERROR   : [vf#0:0 @ 0x5584b25e7400] Task finished with error code: -5 (Input/output error)
> 2024-11-08 16:44:58.987532495  [2024-11-08 16:44:58] ffmpeg.GarageCam.detect        ERROR   : [vf#0:0 @ 0x5584b25e7400] Terminating thread with return code -5 (Input/output error)

I then changed the config file to:

```
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
```

...which had the same errors, but otherwise all worked.
So I then tried:

```
ffmpeg:
  hwaccel_args: preset-intel-qsv-h265
```

And then the errors stopped appearing in the log file (there wasn't a single error in the logs).
I was able to view the live video feeds (I could see people walking past, for instance, so I knew the video was working fine), but there was an error overlay saying that the video stream was offline. 

I have since switched back to the original config:

```
ffmpeg:
  hwaccel_args: preset-vaapi
```

Live video feeds still work, but I can't view any videos in the review screen. If I click on a video in the review screen, the thumbnail loads, but I just get a never-ending loading symbol and the video itself doesn't ever display.

Interestingly, videos that were recorded before I started changing the config file load perfectly fine in the review screen, but those recorded after I started fiddling are not viewable.

### Version

v0.15.0-b1

### Frigate config file

```yaml
mqtt:
  host: 192.168.3.22
  enabled: true
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 30

# # Uncomment the following when Google Coral USB TPU has been plugged into the system...:
detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://REDACTED

ffmpeg:
  hwaccel_args: preset-intel-qsv-h265 #preset-intel-qsv-h264

go2rtc:
  streams:
    FrontDoor:
      - rtsps://192.168.1.1:7441/HZ6BuVp4F3iWXAwl
      - ffmpeg:FrontDoor#audio=opus
    PackageCam:
      - rtsps://192.168.1.1:7441/7EBFyiGKgiRhf0jU
      - ffmpeg:PackageCam#audio=opus
    GarageCam:
      - rtsps://192.168.1.1:7441/fLIVSyOaCypG4V7R
      - ffmpeg:GarageCam#audio=opus
  webrtc:
    candidates:
      - 192.168.4.7:8555
      - stun:8555

cameras:
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/HZ6BuVp4F3iWXAwl?enableSrtp?video&audio
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/NhxjoXQg5OVd0KiN?enableSrtp?video&audio
          roles:
            - record
        # - audio
      output_args:
        record: preset-record-ubiquiti
        # record: preset-record-generic-audio-aac
    # audio:
    #   enabled: true
    detect:
      enabled: true #Change this to true when Coral USB TPU is plugged in.
      width: 960
      height: 720
    motion:
      mask:
        - 244,268,276,274,311,277,309,318,315,358,302,378,295,413,289,439,283,452,278,439,253,389,208,369,188,298,204,277
        - 0,326,65,336,100,343,105,359,123,393,134,430,141,453,135,499,113,533,92,550,54,578,0,582
        - 235,526,257,521,289,528,297,538,301,559,305,592,300,623,283,635,256,644,246,634,229,619,209,596,208,572,230,549
        - 356,455,383,480,399,484,409,477,417,459,421,437,419,416,409,407,390,406,364,417,346,430
        - 485,457,511,466,529,433,518,409,492,403,466,433
        - 724,620,751,609,759,434,764,401,774,350,728,335,693,333,672,337,637,383,637,405,642,423,635,468,609,490,611,539
        - 0,0,960,0,960,165,750,241,682,263,616,295,524,292,381,314,310,321,195,319,141,321,0,307
  PackageCam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/7EBFyiGKgiRhf0jU?enableSrtp?video&audio
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true #Change this to true when Coral USB TPU is plugged in.
      width: 1600
      height: 1200
    motion:
      mask:
        - 572,870,561,919,536,967,487,988,473,1028,492,1085,466,1170,457,1200,423,1200,380,1200,298,1200,218,1200,161,1200,114,1200,64,1200,0,1200,0,1124,0,802,51,802,114,800,185,807,222,812,235,811,270,805,310,755,332,737,384,714,427,705,445,701,434,629,447,563,475,520,516,480,510,423,546,402,582,395,613,417,617,466,621,499,686,507,710,521,693,547,611,580,576,597,538,584,510,608,504,643,504,675,541,724,571,769,581,816
        - 166,180,185,158,215,155,256,165,278,175,295,193,309,209,338,222,363,247,370,271,379,304,362,328,332,354,311,367,264,378,210,378,187,374,166,361,155,361,130,340,117,318,118,292,125,261,131,222,143,200
        - 1600,0,1600,169,1516,309,1506,331,1513,356,1480,387,1435,404,1399,370,1362,324,1296,270,1259,253,1218,218,1188,183,1180,145,1188,124,1208,87,1203,42,1223,24,1243,0
        - 1600,1200,1600,867,1600,718,1574,752,1506,785,1423,814,1260,883,1140,936,1063,956,998,990,862,999,321,1200
  GarageCam:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/fLIVSyOaCypG4V7R?enableSrtp?video&audio
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/hR3g7Ce9h8UqzBLo?enableSrtp?video&audio
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true #Change this to true when Coral USB TPU is plugged in.
      width: 1280
      height: 1280


birdseye:
  enabled: true
  # width: 1280
  # height: 720
  mode: continuous
  # layout:
  #   scaling_factor: 4

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 60
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 60
    pre_capture: 10
    post_capture: 10
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  retain:
    default: 90

objects:
  track:
    - bus #Australia Post vans are detected as buses.
    - car
    - person


ui:
  timezone: Australia/Melbourne

telemetry:
  version_check: true
  stats:
    network_bandwidth: true
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    env_file: .env
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    cap_add:
      - CAP_PERFMON
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Enables Google Coral EdgeAI USB TPU
      - /dev/dri/renderD128:/dev/dri/renderD128 # Intel-based iGPU hardware acceleration.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/dockerfilesNotOnNAS/frigate-config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8555:8555"
    environment:
      PLUS_API_KEY: REDACTED

networks:
  proxy:
    external: true
```

### Relevant Frigate log output

```shell
2024-11-08 16:19:28.578199578  [INFO] Preparing Frigate...
2024-11-08 16:19:28.582349327  [INFO] Starting Frigate...
2024-11-08 16:19:30.658147722  [2024-11-08 16:19:30] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-08 16:19:30.678675184  [2024-11-08 16:19:30] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-08 16:19:30.718565975  [2024-11-08 16:19:30] frigate.app                    INFO    : Starting Frigate (0.15.0-33825f6)
2024-11-08 16:19:30.730491710  [2024-11-08 16:19:30] peewee_migrate.logs            INFO    : Starting migrations
2024-11-08 16:19:30.730744649  [2024-11-08 16:19:30] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-11-08 16:19:30.804321906  [2024-11-08 16:19:30] frigate.app                    INFO    : Recording process started: 343
2024-11-08 16:19:30.804369240  [2024-11-08 16:19:30] frigate.app                    INFO    : Review process started: 347
2024-11-08 16:19:30.806652437  [2024-11-08 16:19:30] frigate.app                    INFO    : go2rtc process pid: 98
2024-11-08 16:19:30.821189041  [2024-11-08 16:19:30] detector.coral                 INFO    : Starting detection process: 360
2024-11-08 16:19:30.830399308  [2024-11-08 16:19:30] frigate.app                    INFO    : Output process started: 379
2024-11-08 16:19:30.877077283  [2024-11-08 16:19:30] frigate.app                    INFO    : Camera processor started for FrontDoor: 407
2024-11-08 16:19:30.877080340  [2024-11-08 16:19:30] frigate.app                    INFO    : Camera processor started for PackageCam: 408
2024-11-08 16:19:30.882477494  [2024-11-08 16:19:30] frigate.app                    INFO    : Camera processor started for GarageCam: 411
2024-11-08 16:19:30.892378356  [2024-11-08 16:19:30] frigate.app                    INFO    : Capture process started for FrontDoor: 414
2024-11-08 16:19:30.898840094  [2024-11-08 16:19:30] frigate.app                    INFO    : Capture process started for PackageCam: 428
2024-11-08 16:19:30.898843598  [2024-11-08 16:19:30] frigate.app                    INFO    : Capture process started for GarageCam: 435
2024-11-08 16:19:30.986329043  [2024-11-08 16:19:30] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2024-11-08 16:19:31.082648316  [2024-11-08 16:19:31] frigate.api.fastapi_app        INFO    : FastAPI started
2024-11-08 16:19:33.461731651  [2024-11-08 16:19:30] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-11-08 16:19:33.464206787  [2024-11-08 16:19:33] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
2024-11-08 16:19:28.577356932  [INFO] Preparing new go2rtc config...
2024-11-08 16:19:28.851163386  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-11-08 16:19:28.879109176  [INFO] Starting go2rtc...
2024-11-08 16:19:28.969639161  16:19:28.969 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-08 16:19:28.969652123  16:19:28.969 INF config path=/dev/shm/go2rtc.yaml
2024-11-08 16:19:28.969965921  16:19:28.969 INF [api] listen addr=:1984
2024-11-08 16:19:28.970109974  16:19:28.970 INF [rtsp] listen addr=:8554
2024-11-08 16:19:28.970320276  16:19:28.970 INF [webrtc] listen addr=:8555
2024-11-08 16:19:38.578054529  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
docker exec -it frigate sh

ffprobe rtsps://192.168.1.1:7441/HZ6BuVp4F3iWXAwl
sh: 4: ffprobe: not found
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Ubiquiti, various models

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-11-08 at 5 01 39 PM](https://github.com/user-attachments/assets/2a366a49-fad4-4b9a-a4f5-9dedbf913535)
![Screenshot 2024-11-08 at 5 02 39 PM](https://github.com/user-attachments/assets/5e46967a-5a14-4438-9ed9-0519c913eabd)
![Screenshot 2024-11-08 at 5 02 45 PM](https://github.com/user-attachments/assets/28638598-af1a-407b-aaa4-14e89878bc9e)

### Any other information that may be helpful

Hardware info from button within the System Metrics page:

> {"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.22(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-24.3.3()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLD"}
