### DISCUSSION TITLE
[Config Support]: lightest configuration for recording only

### DISCUSSION THREAD

**Discussion by Suxsem** [blakeblackshear/frigate#14853] [Config Support]
### Describe the problem you are having

Hi all. I'm trying to have the lightest possible configuration to only record 7x24 streams of 5 cameras.
No object detection, no motion detection, no transcoding, nothing.
I tried to disable all features but the CPU usage of my linux VM is always around 20%.
If I stop frigate the CPU usage drops to about 1%.

There is anything that I can do? Is my config correct?

I know frigate is best for motion detection, but i really like the UI to view live feed and review recordings. That said, if you think that my use case is not suitable for frigate and you know a better software to do so please suggest to me.

Thanks!

### Version

 0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

birdseye:
  enabled: false
  mode: continuous
  restream: false
  layout:
    scaling_factor: 1.0

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  citofono:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/citofono
          roles:
            - detect
            - record
      output_args:
        #record: preset-record-generic-audio-aac
        record: preset-record-generic
    onvif:
      host: citofono.lan
      port: 80
      user: admin
      password: ***
    detect:
      enabled: false
      width: 320
      height: 240
      fps: 2
    record:
      enabled: true
      retain:
        days: 1
        mode: all
    birdseye:
      enabled: false

    motion:
      enabled: false
      threshold: 80
      contour_area: 100
      improve_contrast: true
      mask: 0,0.103,0,0.904,0.592,0.916,0.445,0.168

  camera-avanti-sx:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-avanti-sx
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: false
      width: 320
      height: 240
      fps: 2
    record:
      enabled: true
      retain:
        days: 0.5
        mode: all
    birdseye:
      order: 1

    motion:
      enabled: false
      mask: 
        0.079,0.963,0.082,0.847,0.027,0.83,0.028,0.089,0.23,0.087,0.248,0.03,0.972,0.018,0.984,0.969
      threshold: 80
      contour_area: 100
      improve_contrast: true

  camera-avanti-dx:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-avanti-dx
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: false
      width: 320
      height: 240
      fps: 2
    record:
      enabled: true
      retain:
        days: 0.5
        mode: all
    birdseye:
      order: 2

    motion:
      enabled: false
      mask: 
        0.047,0.967,0.082,0.962,0.091,0.847,0.045,0.835,0.021,0.108,0.202,0.085,0.286,0.038,0.94,0.02,0.963,0.955
      threshold: 80
      contour_area: 100
      improve_contrast: true

  camera-retro:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-retro
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: false
      width: 320
      height: 240
      fps: 2
    record:
      enabled: true
      retain:
        days: 0.5
        mode: all
    birdseye:
      order: 3

    motion:
      enabled: false
      mask: 
        0.017,0.099,0.018,0.85,0.077,0.855,0.082,0.982,0.98,0.975,0.977,0.018,0.241,0.017,0.24,0.095
      threshold: 80
      contour_area: 100
      improve_contrast: true

  camera-garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-garage
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: false
      width: 320
      height: 240
      fps: 2
    record:
      enabled: true
      retain:
        days: 0.5
        mode: all
    birdseye:
      order: 4

    motion:
      enabled: false
      mask: 
        0.035,0.389,0.042,0.165,0.262,0.116,0.311,0.023,0.985,0.021,0.982,0.984,0.097,0.97,0.096,0.842,0.039,0.807
      threshold: 50
      contour_area: 30
      improve_contrast: true
      
go2rtc:
  streams:
    citofono:
      - rtsp://admin:***@citofono.lan/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - rtsp://admin:***@citofono.lan/cam/realmonitor?channel=1&subtype=1
    camera-avanti-sx:
      - rtsp://admin:***@camera-avanti-sx.lan/ch0_0.h264
    camera-avanti-dx:
      - rtsp://admin:***@camera-avanti-dx.lan/ch0_0.h264
    camera-retro:
      - rtsp://admin:***@camera-retro.lan/ch0_1.h264
    camera-garage:
      - rtsp://admin:***@camera-garage.lan/ch0_0.h264

version: 0.14
camera_groups:
  home:
    order: 1
    icon: LuHome
    cameras:
      - camera-avanti-dx
      - camera-avanti-sx
      - camera-garage
      - camera-retro
      - citofono
```

### Relevant Frigate log output

```shell
not relevant
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
      container_name: frigate
      privileged: true # this may not be necessary for all setups
      restart: unless-stopped
      image: ghcr.io/blakeblackshear/frigate:stable
      shm_size: "64mb" # update for your cameras based on calculation above
      devices:
        - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
        - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
        - /dev/video11:/dev/video11 # For Raspberry Pi 4B
        - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./frigate/config:/config
        - /shared/frigate:/media/frigate
        - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: 1000000000
      ports:
        - "8971:8971"
        - "5000:5000" # Internal unauthenticated access. Expose carefully.
        - "8554:8554" # RTSP feeds
        - "8555:8555/tcp" # WebRTC over tcp
        - "8555:8555/udp" # WebRTC over udp
        - "1984:1984" # go2rtc http
      environment:
        FRIGATE_RTSP_PASSWORD: "***"
        LIBVA_DRIVER_NAME: i965
```

### Object Detector

CPU (no coral)
