### DISCUSSION TITLE
[Support]: Export through API does not generate thumbnails

### DISCUSSION THREAD

**Discussion by blounolito** [blakeblackshear/frigate#14855] [General Support]
### Describe the problem you are having

Hi,

When I create an export (realtime or timelapse) through UI, everything is generated (video & thumbnail), when I request this export through API, only video is generated, and I can't play the export through UI.

**When I create en export through UI, everything is working fine**, here is a capture of the AJAX request made to API ;
URL : https://frigate:30060/api/export/camera1/start/1731033571/end/1731037171
POST Payload :
`{playback: "realtime", name: "From UI"}`

**When I use Postman, or any other REST client**, with the exact same payload, cookies, URL, **Frigate does not generate the thumbnail, and I can't click on the preview block.**

I tried to turn DEBUG log level on, there's absolutely nothing related to an error. The thumbnail corresponding to the recording ID is created on filesystem, but its size is 8 bytes.

I'm not sure what to do.
Thanks,

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Google Chrome 130.0.6723.92

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    camera1:
      - rtsp://1.2.3.4:31021/camera1
      - rtsp://1.2.3.4:31021/camera1-sub

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/camera1?stream=main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/camera1?stream=sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 21
        mode: all
    detect:
      enabled: false
      fps: 20

version: 0.14
```

### Relevant Frigate log output

```shell
"POST /api/export/camera1/start/1731033546/end/1731037146 HTTP/1.1" 200
206... segments
... nothing else.
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.8"
services:
  frigate_nvr:
    container_name: frigate_nvr
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 4096mb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Nvr-Pool/nvr-config:/config
      - /mnt/Nvr-Pool/nvr-recordings:/media/frigate
    ports:
      - 30060:8971
      - 30058:8554 # RTSP feeds
      - 30059:8555/tcp # WebRTC over tcp
      - 30059:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ***
networks: {}
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Wize Cam 4

### Screenshots of the Frigate UI's System metrics pages

![from_postman](https://github.com/user-attachments/assets/ccdde590-3b02-46df-9d8a-4c7019320675)
![from_ui](https://github.com/user-attachments/assets/36ecb7ea-1482-47e0-9a39-8984a69e4bfb)

### Any other information that may be helpful

I am not using any detection.
