### DISCUSSION TITLE
[Detector Support]: Unable to start frigate with nvidia tensorrt detector

### DISCUSSION THREAD

**Discussion by toperichvania** [blakeblackshear/frigate#14863] [Detector Support] [answered]
### Describe the problem you are having

Unable to start frigate with tensorrt detector

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.101.99.252
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    bd_crew_corridor_fwd_cl_103:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.103/ONVIF/MediaInput?profile=def_profile1
    bd_crew_hall_ps_100:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.100/ONVIF/MediaInput?profile=def_profile1
    bd_exterior_aft_93:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.93/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    bd_exterior_aft_95:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.95/ONVIF/MediaInput?profile=def_profile1
    bd_exterior_aft_98:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.98/ONVIF/MediaInput?profile=def_profile1
    bd_exterior_aft_99:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.99/ONVIF/MediaInput?profile=def_profile1
    bd_exterior_fwd_ps_104:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.104/ONVIF/MediaInput?profile=def_profile1
    bd_exterior_fwd_ptz_106:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.106/ONVIF/MediaInput?profile=def_profile1
    bd_exterior_fwd_sb_105:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.105/ONVIF/MediaInput?profile=def_profile1
    bd_guest_corridor_cl_101:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.101/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    bd_guest_corridor_cl_102:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.102/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    bd_guest_corridor_cl_96:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.96/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    bod_av_rack_cl_25:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.25/ONVIF/MediaInput?profile=def_profile1
    bod_nemo_lounge_24:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.24/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    bod_tech_space_cl_26:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.26/ONVIF/MediaInput?profile=def_profile1
    ld_aft_peak_stairs_ps_46:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.46/ONVIF/MediaInput?profile=def_profile1
    ld_aft_peak_stairs_sb_50:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.50/ONVIF/MediaInput?profile=def_profile1
    ld_aft_peak_stairs_sb2_52:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.52/ONVIF/MediaInput?profile=def_profile1
    ld_beach_club_sb_53:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.53/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    ld_crew_stairway_fwd_cl_63:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.63/ONVIF/MediaInput?profile=def_profile1
    ld_elec_locker_sb_57:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.57/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    ld_guest_lobby_58:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.58/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    ld_guest_lobby_59:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.59/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    ld_bunker_station_115:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.115/ONVIF/MediaInput?profile=def_profile1
    ld_passage_56:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.56/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    ld_passage_62:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.62/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    ld_passage_61:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.61/ONVIF/MediaInput?profile=def_profile1
    ld_provisioning_60:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.60/ONVIF/MediaInput?profile=def_profile1
    ld_tender_garage_ps_ptz_54:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.54/ONVIF/MediaInput?profile=def_profile1
    ld_tender_garage_sb_ptz_55:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.55/ONVIF/MediaInput?profile=def_profile1
    mast_ptz_ps_111:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.111/ONVIF/MediaInput?profile=def_profile1
    mast_ptz_sb_112:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.112/ONVIF/MediaInput?profile=def_profile1
    md_aft_peak_ps_65:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.65/ONVIF/MediaInput?profile=def_profile1
    md_aft_peak_ps_67:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.67/ONVIF/MediaInput?profile=def_profile1
    md_aft_peak_sb_69:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.69/ONVIF/MediaInput?profile=def_profile1
    md_aft_peak_sb_71:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.71/ONVIF/MediaInput?profile=def_profile1
    md_crew_corridor_fwd_84:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.84/ONVIF/MediaInput?profile=def_profile1
    md_exterior_aft_ps_75:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.75/ONVIF/MediaInput?profile=def_profile1
    md_exterior_aft_ps_76:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.76/ONVIF/MediaInput?profile=def_profile1
    md_exterior_aft_sb_78:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.78/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    md_exterior_aft_sb_73:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.73/ONVIF/MediaInput?profile=def_profile1
    md_exterior_aft_sb_77:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.77/ONVIF/MediaInput?profile=def_profile1
    md_lobby_staircase_80:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.80/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    md_mooring_ps_89:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.89/ONVIF/MediaInput?profile=def_profile1
    md_mooring_sb_90:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.90/ONVIF/MediaInput?profile=def_profile1
    md_mooring_360_87:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.87/ONVIF/MediaInput?profile=def_profile1
    md_passage_ps_108:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.108/ONVIF/MediaInput?profile=def_profile1
    md_rescue_boat_ps_360_85:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.85/ONVIF/MediaInput?profile=def_profile1
    md_rescue_boat_sb_360_86:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.86/ONVIF/MediaInput?profile=def_profile1
    md_vip_corridor_83:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.83/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    md_vip_corridor_mid_79:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.79/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    md_vip_corridor_mid_82:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.82/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    od_crew_hall_ps_81:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.81/ONVIF/MediaInput?profile=def_profile1
    od_lobby_107:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.107/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    sd_emergency_room_110:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.110/ONVIF/MediaInput?profile=def_profile1
    sd_main_stairs_109:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.109/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    td_aux_space_39:
      - ffmpeg:rtsp://Frankentek:$PJ821$24@10.101.99.39/ONVIF/MediaInput?profile=def_profile1

cameras:
  bd_crew_corridor_fwd_cl_103:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_crew_corridor_fwd_cl_103
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_crew_hall_ps_100:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_crew_hall_ps_100
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_exterior_aft_93:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_aft_93
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false
  bd_exterior_aft_95:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_aft_95
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_exterior_aft_98:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_aft_98
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_exterior_aft_99:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_aft_99
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_exterior_fwd_ps_104:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_fwd_ps_104
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_exterior_fwd_ptz_106:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_fwd_ptz_106
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.106
      port: 80
      user: Frankentek
      password: $PJ821$24
  bd_exterior_fwd_sb_105:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_exterior_fwd_sb_105
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_guest_corridor_cl_101:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_guest_corridor_cl_101
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_guest_corridor_cl_102:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_guest_corridor_cl_102
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bd_guest_corridor_cl_96:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bd_guest_corridor_cl_96
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bod_av_rack_cl_25:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bod_av_rack_cl_25
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bod_nemo_lounge_24:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bod_nemo_lounge_24
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  bod_tech_space_cl_26:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bod_tech_space_cl_26
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.26
      port: 80
      user: Frankentek
      password: $PJ821$24
  ld_aft_peak_stairs_ps_46:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_aft_peak_stairs_ps_46
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_aft_peak_stairs_sb_50:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_aft_peak_stairs_ps_46
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_aft_peak_stairs_sb2_52:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_aft_peak_stairs_sb2_52
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_beach_club_sb_53:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_beach_club_sb_53
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_crew_stairway_fwd_cl_63:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_crew_stairway_fwd_cl_63
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_elec_locker_sb_57:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_elec_locker_sb_57
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_guest_lobby_58:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_guest_lobby_58
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_guest_lobby_59:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_guest_lobby_59
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_bunker_station_115:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_bunker_station_115
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_passage_56:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_passage_56
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_passage_62:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_passage_62
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_passage_61:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_passage_61
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_provisioning_60:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_provisioning_60
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  ld_tender_garage_ps_ptz_54:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_tender_garage_ps_ptz_54
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.54
      port: 80
      user: Frankentek
      password: $PJ821$24
  ld_tender_garage_sb_ptz_55:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ld_tender_garage_sb_ptz_55
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.55
      port: 80
      user: Frankentek
      password: $PJ821$24
  mast_ptz_ps_111:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mast_ptz_ps_111
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.111
      port: 80
      user: Frankentek
      password: $PJ821$24
  mast_ptz_sb_112:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mast_ptz_sb_112
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.112
      port: 80
      user: Frankentek
      password: $PJ821$24
  md_aft_peak_ps_65:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_aft_peak_ps_65
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_aft_peak_ps_67:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_aft_peak_ps_67
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_aft_peak_sb_69:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_aft_peak_sb_69
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_aft_peak_sb_71:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_aft_peak_sb_71
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_crew_corridor_fwd_84:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_crew_corridor_fwd_84
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_exterior_aft_ps_75:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_exterior_aft_ps_75
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.75
      port: 80
      user: Frankentek
      password: $PJ821$24
  md_exterior_aft_ps_76:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_exterior_aft_ps_76
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_exterior_aft_sb_78:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_exterior_aft_sb_78
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_exterior_aft_sb_73:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_exterior_aft_sb_73
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_exterior_aft_sb_77:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_exterior_aft_sb_77
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_lobby_staircase_80:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_lobby_staircase_80
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_mooring_ps_89:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_mooring_ps_89
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_mooring_sb_90:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_mooring_sb_90
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false
  md_mooring_360_87:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_mooring_360_87
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_passage_ps_108:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_passage_ps_108
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_rescue_boat_ps_360_85:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_rescue_boat_ps_360_85
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_rescue_boat_sb_360_86:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_rescue_boat_sb_360_86
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_vip_corridor_83:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_vip_corridor_83
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_vip_corridor_mid_79:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_vip_corridor_mid_79
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  md_vip_corridor_mid_82:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/md_vip_corridor_mid_82
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  od_crew_hall_ps_81:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/od_crew_hall_ps_81
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  od_lobby_107:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/od_lobby_107
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  sd_emergency_room_110:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sd_emergency_room_110
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
    onvif:
      host: 10.101.99.110
      port: 80
      user: Frankentek
      password: $PJ821$24
  sd_main_stairs_109:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sd_main_stairs_109
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
  td_aux_space_39:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/td_aux_space_39
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true




  PTZ:
    enabled: false
    objects:
      track:
        - backpack
        - handbag
        - cellphone
    mqtt:
      enabled: true
      height: 720
      quality: 100
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ptz_main
          input_args: preset-rtsp-restream
          roles:
            - record
        # - path: rtsp://127.0.0.1:8554/ptz_sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    onvif:
      host: 192.168.1.88
      port: 80
      user: admin
      password: Ftek3835!
    detect:
      enabled: false
      # width: 1280
      # height: 720
    live:
      stream_name: ptz_main

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: true
  height: 720
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
  quality: 100

detect:
  fps: 5
  enabled: true

record:
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 3
      mode: motion

detectors:
  # deepstack:
  #   api_url: http://10.101.99.252:32168/v1/vision/detection
  #   type: deepstack
  #   api_timeout: 0.1

  tensorrt:
    type: tensorrt

objects:
  track:
    - person
    - cell phone
    - backpack
    - handbag
  filters:
    backpack:
      min_score: 0.5
      threshold: 0.6

review:
  alerts:
    labels:
      - person
      - cell phone
      - backpack
      - handbag
  detections:
    labels:
      - person
      - cell phone
      - backpack
      - handbag

# logger:
#   logs:
#     frigate.record.maintainer: debug

version: 0.14
camera_groups:
  Bridge_Deck:
    order: 1
    icon: LuBringToFront
    cameras:
      - bd_crew_corridor_fwd_cl_103
      - bd_crew_hall_ps_100
      - bd_exterior_aft_93
      - bd_exterior_aft_95
      - bd_exterior_aft_98
      - bd_exterior_aft_99
      - bd_exterior_fwd_ps_104
      - bd_exterior_fwd_ptz_106
      - bd_exterior_fwd_sb_105
      - bd_guest_corridor_cl_101
      - bd_guest_corridor_cl_102
      - bd_guest_corridor_cl_96
  Lower_Deck:
    order: 2
    icon: LuWorkflow
    cameras:
      - ld_tender_garage_ps_ptz_54
      - ld_tender_garage_sb_ptz_55
      - ld_aft_peak_stairs_ps_46
      - ld_aft_peak_stairs_sb2_52
      - ld_aft_peak_stairs_sb_50
      - ld_beach_club_sb_53
      - ld_crew_stairway_fwd_cl_63
      - ld_elec_locker_sb_57
      - ld_guest_lobby_58
      - ld_guest_lobby_59
      - ld_bunker_station_115
      - ld_passage_56
      - ld_passage_62
      - ld_passage_61
      - ld_provisioning_60
  BOD:
    order: 3
    icon: LuBookTemplate
    cameras:
      - bod_av_rack_cl_25
      - bod_nemo_lounge_24
      - bod_tech_space_cl_26
  Mast:
    order: 4
    icon: LuBringToFront
    cameras:
      - mast_ptz_ps_111
      - mast_ptz_sb_112
  Main_Deck:
    order: 5
    icon: LuWorkflow
    cameras:
      - md_exterior_aft_ps_75
      - md_exterior_aft_ps_76
      - md_exterior_aft_sb_78
      - md_exterior_aft_sb_73
      - md_exterior_aft_sb_77
      - md_lobby_staircase_80
      - md_aft_peak_ps_65
      - md_aft_peak_ps_67
      - md_aft_peak_sb_69
      - md_aft_peak_sb_71
      - md_crew_corridor_fwd_84
      - md_mooring_ps_89
      - md_mooring_sb_90
      - md_mooring_360_87
      - md_rescue_boat_ps_360_85
      - md_rescue_boat_sb_360_86
      - md_passage_ps_108
      - md_vip_corridor_83
      - md_vip_corridor_mid_79
      - md_vip_corridor_mid_82
  Owner_Deck:
    order: 6
    icon: LuBookTemplate
    cameras:
      - od_crew_hall_ps_81
      - od_lobby_107
      - sd_emergency_room_110
      - sd_main_stairs_109
  Tank_Deck:
    order: 7
    icon: LuBringToFront
    cameras:
      - td_aux_space_39
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    privileged: true
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "4gb"
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /shared/recordings:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    depends_on:
      - mqtt
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      FRIGATE_MQTT_USER: "dev"
      FRIGATE_MQTT_PASSWORD: "password"
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_auth:/mosquitto/config/mosquitto_auth
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-log:
```

### Relevant Frigate log output

```shell
2024-11-08 08:35:01.548029861 [2024-11-08 08:35:01] frigate.watchdog INFO : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service go2rtc-healthcheck: stopping
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

does not start

### Any other information that may be helpful

works fine with deepstack (apart from high skipped detection frames
