### DISCUSSION TITLE
ONNX detector specify GPU#

### DISCUSSION THREAD

**Discussion by numminorih-git** [blakeblackshear/frigate#14897] [Ask A Question] [answered]
Dear community, 

please advise, can I specify which GPU (I have multiple nvidia in server) onnx detector should use. For example, in tensorrt detector i can set  "device: 1" or "device: 0" and detector's process will run on indicated videocard.

**Comment by NickM-27** [comment]
Currently no, I will add this

**Reply by NickM-27** [reply, marked as answer]
implemented in https://github.com/blakeblackshear/frigate/pull/14898

**Comment by numminorih-git** [comment]
ghcr.io/blakeblackshear/frigate:0.15.0-beta2-tensorrt
specify device: 1 with onnx detector doesn't work, and cause error in config:

```
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 187, in config_save
    FrigateConfig.parse_yaml(new_config)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 696, in parse_yaml
    return cls.parse(config_yaml, is_json=False, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 692, in parse
    return cls.parse_object(config, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 702, in parse_object
    return cls.model_validate(
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
onnx.device
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
```

```
detectors:
  onnx:
    type: onnx
    device: 1   #This is the default, select the first GPU
model:
 model_type: yolonas
 width: 320 # <--- should match whatever was set in notebook
 height: 320 # <--- should match whatever was set in notebook
 input_pixel_format: bgr
 path: /config/yolo_nas_s.onnx
 input_tensor: nchw
 labelmap_path: /labelmap/coco-80.txt
```
