### DISCUSSION TITLE
[HW Accel Support]: vendor-agnostic *_gpu_top tool

### DISCUSSION THREAD

**Discussion by Arol450** [blakeblackshear/frigate#14904] [Hardware Acceleration Support]
### Describe the problem you are having

People seem to be having problems with intel_gpu_top.
I myself could not get it to work within a (podman) container. Rootless, systemd-started, system-user-mapped.
I tried all permutations of Capabilities, AmbientCapabilities, added capabilities, etc.

frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)

I can get a different tool to work, a hardware agnostic version of intel_gpu_top.
https://gitlab.freedesktop.org/drm/igt-gpu-tools
https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/master/NEWS : ' ...- New vendor agnostic gputop tool. (Tvrtko Ursulin) ...'

DRM minor 128                                                                                       
 PID      MEM      RSS    render       copy       video      compute    NAME                        
1861     166M     161M |  0.0%    ||  0.0%    ||  0.0%       ||  0.0%    || 60.7% █▉ | frigate.detecto 
2280       1G     603M    |  0.0%    ||  0.0%    ||  5.7% ▎  ||  0.0%    ||  0.0%    | ffmpeg          
2330       1G     648M    |  0.0%    |  0.0%      ||  5.0% ▎  ||  0.0%    ||  0.0%    | ffmpeg          
2176     587M     331M |  0.0%    ||  0.0%    ||  3.1% ▏  ||  0.0%    ||  0.0%    | ffmpeg          
2177     556M     302M |  0.0%    ||  0.0%    ||  2.9% ▏  ||  0.0%    ||  0.0%    | ffmpeg          
2171     556M     302M |  0.0%    ||  0.0%    ||  2.9% ▏  ||  0.0%    ||  0.0%    | ffmpeg          
2184     559M     301M |  0.0%    ||  0.0%    ||  2.9% ▏  ||  0.0%    ||  0.0%    | ffmpeg          
2154     557M     307M |  0.0%    ||  0.0%    ||  2.6% ▏  ||  0.0%    ||  0.0%    | ffmpeg          
2231     552M     361M |  0.0%    ||  0.0%    ||  2.4% ▏  ||  0.0%    ||  0.0%    | ffmpeg          
2573     451M     246M |  0.0%    ||  0.0%    ||  2.1% ▏  ||  0.0%    ||  0.0%    | ffmpeg          

I get pretty believable statistics for video acceleration and detector-compute utilization.
I thought i would mention this.

This is on Intel Meteorlake hardware, a medium yolo_nas model on OpenVino, and transparently trans-coding the main stream to AV1 video format, saving a ton of space on the drive, h264_qsv -> av1_qsv
CPU is bored, 90%idle with 18 4MP cameras.

### Version

0.15.0-a68c7f4

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO

model:
  model_type: yolonas
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_m.onnx
  labelmap_path: /labelmap/coco-80.txt

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

go2rtc:
  streams:
    Cars_live:
      - ffmpeg:rtsp://****:****@192.168.2.44/Streaming/Channels/1

cameras:
  Cars:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v av1_qsv -global_quality:v 31 -an
      inputs:
        - path: rtsp://localhost:8554/Cars_live  
          input_args: -loglevel error -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv
          roles:
            - record
        - path: rtsp://****:****@192.168.2.44/Streaming/Channels/102
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    live:
      stream_name: Cars_live
```

### docker-compose file or Docker CLI command

```yaml
systemd.service:

[Unit]
Wants=network-online.target
After=network-online.target
Description=Run frigate-vpl in a container

[Service]
User=frigate
#Group=users
Type=notify
Restart=always
KillMode=control-group
TimeoutStartSec=180
TimeoutStopSec=360

ExecStart=/usr/bin/podman run -d \
    --name=frigate-vpl \
    --cidfile=/run/user/967/frigate-vpl.cid \
    --replace --rm --cgroups=split \
    --sdnotify=conmon \
    -p 8971:8971 \
    --device /dev/dri:/dev/dri:rwm \
    --device /dev/accel/accel0:/dev/accel/accel0:rwm \
    -v /mnt/frigate/config:/config \
    -v /mnt/frigate/storage:/media/frigate \
    -v /home/frigate/ssl/cert.crt:/etc/letsencrypt/live/frigate/fullchain.pem:ro \
    -v /home/frigate/ssl/cert.key:/etc/letsencrypt/live/frigate/privkey.pem:ro \
    --mount type=tmpfs,tmpfs-size=1G,destination=/tmp/cache \
    --shm-size=1G \
    --stop-timeout=320 \
#    --privileged \
#    --cap-add CAP_PERFMON \
#    --cap-add PERFMON \
#    --cap-add CAP_SYS_ADMIN \
#    --cap-add SYS_ADMIN \
    ghcr.io/blakeblackshear/frigate:a68c7f4
ExecStop=/usr/bin/podman rm -v -f -i  --cidfile=/run/user/967/frigate-vpl.cid
Delegate=yes

NotifyAccess=all
SyslogIdentifier=%N

# an attempt of hardening

#MemoryDenyWriteExecute=yes
#SystemCallFilter=~memfd_create
#CapabilityBoundingSet=CAP_SETGID CAP_SETUID CAP_SYS_PACCT CAP_KILL CAP_WAKE_ALARM CAP_LINUX_IMMUTABLE CAP_IPC_LOCK CAP_SYS_MODULE CAP_SYS_BOOT CAP_LEASE CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW CAP_SYS_NICE CAP_SYS_RESOURCE CAP_NET_ADMIN CAP_SYS_PTRACE CAP_SYS_RAWIO CAP_SYS_ADMIN CAP_SYSLOG CAP_SYS_TIME CAP_MKNOD  CAP_BLOCK_SUSPEND CAP_CHOWN CAP_FSETID CAP_SETFCAP

#AmbientCapabilities=CAP_PERFMON CAP_SYS_ADMIN

# restrict IP address ranges to 192.168.2.1-192.168.2.128 and
IPAddressDeny=any
IPAddressAllow=localhost @frigate_group

[Install]
WantedBy=multi-user.target
```

### Relevant Frigate log output

```shell
frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
cameras are not the problem
```

### Install method

Docker CLI

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Hitosino something something

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/3bfb9973-8cf7-4359-8ccd-b921f4cf9040)
![image](https://github.com/user-attachments/assets/5b058b29-5c3d-433a-bd17-0bb6604d5602)
