### DISCUSSION TITLE
Camera retain values and individual zone retain values possible?

### DISCUSSION THREAD

**Discussion by katschub88** [blakeblackshear/frigate#14900] [Ask A Question] [answered]
Is it possible to use different retain settings for the same camera by using zones?
Currently I have one retain setting (first one) for the camera, set to 60 days.
I'd like to lower that value to 30, but have a higher retain value for events inside a certain zone, e.g. 90 days.
Is this possible in frigate 0.13? I'm still stuck at this version due to the missing rocm support and the flawed deletion logic in 0.14.
What about 0.14 or 0.15?

Would something like this work?
```
cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: ...
...
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
...
    zones:
      zone1:
        coordinates: ...
        objects:
          - person
          - animal
          - vehicle
        events:
          retain:
            default: 90
            mode: active_objects
```

I'd expect that all events for objects not entering zone1 to be deleted after 30 days. But events for objects entering zone1 should be deleted after 90 days.
