### DISCUSSION TITLE
[Camera Support]: Archos Hello7 with Wallpanel MJPEG stream

### DISCUSSION THREAD

**Discussion by bonjour81** [blakeblackshear/frigate#14918] [Camera Support]
### Describe the problem you are having

Hello,
In addition to my RTSP camera, I have an Archos Hello7 (home tablet?) that run [Wallpanel](https://wallpanel.xyz/) browser to display some nodered dashboard.
Wallpanel offers to use the android camera to stream what it sees by mjpeg (480x640) that I set to 5 FPS (it can do more)
It is a poor camera (no night view, very reduced resolution), but it sees some angle where I have no other cam, so why not get use of it.
The Mjpeg stream works very well on VLC  ( http://<archosIP>:2971/camera/stream ).

When it comes to Frigate, it's an other story.
Sometimes it works, sometimes not.

I have this message looping in my Frigate log:
```
error 2024-11-11 11:10:17  frigate.video  archos: Unable to read frames from ffmpeg process. 
error 2024-11-11 11:10:17  frigate.video  archos: ffmpeg process is not running. exiting capture thread... 
error 2024-11-11 11:10:22  watchdog.archos  Ffmpeg process crashed unexpectedly for archos.  
error 2024-11-11 11:10:22  watchdog.archos  The following ffmpeg logs include the last 100 lines prior to exit.  
error 2024-11-11 11:10:22  ffmpeg.archos.detect  rtsp://127.0.0.1:8554/archos: Invalid data found when processing input
```

in go2rtc logs, I see this:

`warning  2024-11-11 09:41:04 startup  github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:archos#video=h264#hardware`

Is there any mean to improve this? (or to have more information on what cause this "Ffmpeg process crashed unexpectedly" ?

Note: I'm aware it's a pretty poor conditions, I don't expect a lot from this camera and I can live without it. But still: the mjpeg stream is quite stable in VLC, so maybe I'm very close to make it stable in Frigate too.
Also the low resolution is both an disadvantage and an advantage: as it's indoor, image is still quite usable and I would expect a low impact on ressource needed for conversion.

### Version

0.14.0-da913d8  (docker)

### What browser(s) are you using?

Firefox 131.0.3

### Frigate config file

```yaml
go2rtc:
  streams:
    archos:
      - http://192.168.x.x:2971/camera/stream         
      - ffmpeg:archos#video=h264#hardware

  archos:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/archos
          roles:
            - record
            - detect
    live:
      stream_name: archos
      height: 640
    detect:
      width: 480
      height: 640
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 640
      quality: 95
      required_zones: []
    motion:
      threshold: 40
      contour_area: 20
```

### Relevant Frigate log output

```shell
error 2024-11-11 11:10:17  frigate.video  archos: Unable to read frames from ffmpeg process. 
error 2024-11-11 11:10:17  frigate.video  archos: ffmpeg process is not running. exiting capture thread... 
error 2024-11-11 11:10:22  watchdog.archos  Ffmpeg process crashed unexpectedly for archos.  
error 2024-11-11 11:10:22  watchdog.archos  The following ffmpeg logs include the last 100 lines prior to exit.  
error 2024-11-11 11:10:22  ffmpeg.archos.detect  rtsp://127.0.0.1:8554/archos: Invalid data found when processing input
```

### Relevant go2rtc log output

```shell
warning  2024-11-11 09:41:04 startup  github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:archos#video=h264#hardware
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mpjpeg, from 'http://192.168.x.x:2971/camera/stream':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 480x640 [SAR 1:1 DAR 3:4], 25 tbr, 25 tbn
```

### Operating system

Debian

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

Archos Hello7 (android tablet) with Wallpanel.

### Screenshots of the Frigate UI's System metrics pages

![Capture d’écran du 2024-11-11 11-38-47](https://github.com/user-attachments/assets/00c6c133-08f3-475f-a06d-44651ae4351c)
![Capture d’écran du 2024-11-11 11-39-08](https://github.com/user-attachments/assets/ea899973-bef8-4036-834b-a7a692bbb955)

### Any other information that may be helpful

You can in metrics screenshot that this camera gets back to work around 11:28 (I did nothing special).
