### DISCUSSION TITLE
[Config Support]: Constant HDD Write on Frigate + Synology Container Manager (Docker)

### DISCUSSION THREAD

**Discussion by alegria20** [blakeblackshear/frigate#14912] [Config Support]
### Describe the problem you are having

**HW Setup:**
- Synology DS718+
- 2x local hdd in SHR (kind of RAID)
- 1x usb hdd
- 1x Coral

**Intent**
Trying to move all write constant activity to the USB hdd (inexpensive) to avoid wear of local hdds.

**Problem description:**
As can be seen in the docker compose file, I map both /media/frigate and /config folders in the USB hdd.

Even though, from my lack of understanding I believe it does not make sense as these are RAM mounted folders, I also tried mapping /dev/shm and /tmp/cache to the USB hdd, with same results.

As shown in the following two image taken moments appart, the write activity is constant in both local hdds. 
At the moment the frigate container is stopped, this write activity is gone.

![image](https://github.com/user-attachments/assets/4c6a1622-d697-4e42-aa70-85860fd0c81f)

![image](https://github.com/user-attachments/assets/86ff90e8-d87b-40cf-bc43-a92867a53a45)

I appreciate any help or guidance to fix this.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
#HOME ASSISTANT
mqtt:
  enabled: false
#  host: 192.168.xx.x
#  port: 1883
#  topic_prefix: frigate
#  client_id: frigate
#  user: your_mqtt_user_name
#  password: $tr0ngPassw0rd

tls:
  enabled: false

motion:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: true
  #width: 1280
  #height: 720
  fps: 5

record:
  enabled: true
  retain:
    days: 7
    mode: all
  export:
    timelapse_args: -vf setpts=0.02*PTS -r 30    # <----- 24 hours into 30 mins of timelapse
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    #- car
    #- bicycle
    #- motorcycle
    - cat
    - dog
    - bird
  filters:
    person:
      # Optional: minimum score for the object to initiate tracking (default: 0.5)
      #min_score: 0.50
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      threshold: 0.78
    cat:
      threshold: 0.78
    dog: 
      threshold: 0.78
    bird: 
      threshold: 0.78

review:
  alerts:
    labels: []  # <----- To remove PERSON as default alert
  detections:
    labels:
    - person
    - cat
    - dog
    - bird

birdseye:
  enabled: false

timestamp_style:
  position: tr   # <----- "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  format: '%Y-%m-%d %H:%M:%S'
  # Optional: Color of font
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 3 # <----- Optional: Line thickness of font (default: shown below)
  effect: solid   # Letter Effect: None, "solid" (solid background in inverse color of font) or "shadow".

logger:
  default: debug

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    CAM1:
      - rtsp://SECRET/stream1
      - "ffmpeg:CAM1#audio=aac"
    CAM2:
      - rtsp://SECRET/stream1
      - "ffmpeg:CAM1#audio=aac"
    CAM3:
      - rtsp://SECRET/stream1
      - "ffmpeg:CAM1#audio=aac"
    CAM4:
      - rtsp://SECRET/stream1
      - "ffmpeg:CAM1#audio=aac"

cameras:
  CAM1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM1?video&audio # <----- Stream for detection
          roles:
            - record
        - path: rtsp://SECRET/stream2 # <----- Stream for record
          roles:
            - detect

  CAM2: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM2?video&audio # <----- Stream for record
          roles:
            - record
        - path: rtsp://SECRET/stream2 # <----- Stream for detection
          roles:
            - detect

  CAM3: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM3?video&audio # <----- Stream for record
          roles:
            - record
        - path: rtsp://SECRET/stream2 # <----- Stream for detection
          roles:
            - detect

  CAM4: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM4?video&audio # <----- Stream for record
          roles:
            - record
        - path: rtsp://SECRET/stream2 # <----- Stream for detection
          roles:
            - detect

version: 0.14
#MORE INFO: https://www.youtube.com/watch?v=NQkfkMwn9gE

camera_groups:
  Home:
    order: 1
    icon: LuWebcam
    cameras:
      - CAM1
      - CAM2
      - CAM3
      - CAM4
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "500mb" # Default is 64mb. See frigate doc to see calucations
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/frigate/config:/config
      - /volumeUSB1/usbshare/docker/frigate/storage:/media/frigate 
      - type: tmpfs # Optional, 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

### Object Detector

Coral

**Comment by alegria20** [comment]
When updated the docker compose to mount the volumnes as follows, there is a workload distribution in favor of the USB hdd, but still there is some activity going on in the local RAID hdds

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/frigate/config:/config
      - /volumeUSB1/usbshare/docker/frigate/storage:/media/frigate 
      - /volumeUSB1/usbshare/docker/frigate/tmp:/tmp
      - /volumeUSB1/usbshare/docker/frigate/shm:/dev/shm
```

![image](https://github.com/user-attachments/assets/4f0a3ee4-6487-4160-9f71-90945e2279c1)

Just for context, when the frigate docker container is off, the write values go down to 0~20 KB/s, so all the write activity here is assumed to be frigate related.

**Comment by NickM-27** [comment]
you have continuous recording enabled so in general this is not unexpected that it will be writing continuously

**Reply by alegria20** [reply]
Hi @NickM-27 thanks for the fast reply. 

My concern is not about continuous writing, but where it is writing. In order to avoid wear of local RAID hhds, I would like all (or at least most) the writing in the USB hdd instead of the local RAID hhds.

Is this not possible?

**Reply by NickM-27** [reply]
```
      - type: tmpfs # Optional, 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

will write to RAM, /tmp/cache and /dev/shm should not be mounted to from a fileysystem. You have `/volumeUSB1/usbshare/docker/frigate/storage:/media/frigate` so assuming that volume is setup correctly I see no reason it would write to the RAID device

**Reply by alegria20** [reply]
@NickM-27  thanks again.

This mounted filesystem /tmp/cache and /dev/shm is just a test to try to see what was going on from my original issue. 

The original config is as follows, and with it, there is a continuous write to the local RAID HHD volume, which I understand is unexpected.

I can confirm that the `- /volumeUSB1/usbshare/docker/frigate/storage:/media/frigate`  is correctly mounted as I can access all the recordings, clips and so on when I open that folder.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "500mb" # Default is 64mb. See frigate doc to see calucations
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/frigate/config:/config
      - /volumeUSB1/usbshare/docker/frigate/storage:/media/frigate 
      - type: tmpfs # Optional, 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

**Comment by alegria20** [comment]
And this is the continuous writing with no recording, no detection... Almost all disabled (see config file below).
I believe this is not an expected behavior, is it?

![image](https://github.com/user-attachments/assets/b154bbbd-09d4-4b89-9f2c-c0987cd1237f)

```

mqtt:
  enabled: false

tls:
  enabled: false

motion:
  enabled: false

detect:
  enabled: false

  fps: 5

record:
  enabled: false

snapshots:
  enabled: false

birdseye:
  enabled: false

cameras:
  CAM1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://SECRET/stream1 # <----- Stream for detection

  CAM2: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://SECRET/stream1 # <----- Stream for record

  CAM3: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://SECRET/stream1 # <----- Stream for record

  CAM4: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://SECRET:554/stream1 # <----- Stream for record

version: 0.14

camera_groups:
  Home:
    order: 1
    icon: LuWebcam
    cameras:
      - CAM1
      - CAM2
      - CAM3
      - CAM4

```

**Reply by NickM-27** [reply]
if this is the case then something is setup incorrectly with docker itself, it is writing to the docker layers

**Reply by alegria20** [reply]
This statement may be correct, but since I have been running other 5 docker containers for years with no issues, and the frigate docker-compose seems pretty straightforward, I do not know what else to do. 

I am open for ideas on what to do next in regards of Docker, as well as any other action to be taken in frigate.


```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "500mb" # Default is 64mb. See frigate doc to see calucations
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/frigate/config:/config
      - /volumeUSB1/usbshare/docker/frigate/storage:/media/frigate 
      - type: tmpfs # Optional, 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
