### DISCUSSION TITLE
[Bug]: go2rtc config generation failes in 0.15-beta

### DISCUSSION THREAD

**Discussion by mhetzi** [blakeblackshear/frigate#14919] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I try the newest beta version go2rtc is not starting:

No camera streams are playing. Frigate does nothing.
I have no hwaccel because my processor is too old.
Work flawlessly with 0.14.1

### Steps to reproduce

1. Upgrade version

### Version

0.15.0-beta1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://xeon.lan:5000/api/config/schema

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
    ffmpeg: debug

mqtt:
  host: xeon.lan
  port: 1883
  topic_prefix: frigate
  client_id: m_frigate
  user: dMotion
  password: [REDACTED]

objects:
  track:
    - person
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

model:
  path: plus://[REDACTED]

snapshots:
  # Optional: Retention settings (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
    objects:
      person: 60

database:
  path: /db/frigate.db

record:
  # Optional: Enable recording (default: shown below)
  enabled: true
  # Optional: Number of days to retain (default: shown below)
  retain:
    days: 2
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include in the event (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include in the event (default: shown below)
    post_capture: 5
    # Optional: Retention settings for clips (default: shown below)
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Per object retention days
      objects:
        person: 120
      mode: active_objects

detect:
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
  max_disappeared: 95
  width: 1920
  height: 1080
  fps: 30
  stationary:
   # Optional: Frequency for running detection on stationary objects (default: shown below)
   # When set to 0, object detection will never be run on stationary objects. If set to 10, it will be run on every 10th frame.
    interval: 30
   # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 75

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  webrtc:
    candidates:
      - 192.168.55.11:8555
      - [REDACTED]:8555
      - stun:8555
  streams:
    stadtplatz_cam:
      - rtsp://[REDACTED]@192.168.57.72:554/stream1
      - ffmpeg:stadtplatz_cam#audio=opus
    Vorhaus_cam:
      - rtsp://[REDACTED]@IN-9008FHD-PoE-10d1dc223ce2.lan/11
      - ffmpeg:Vorhaus_cam#audio=opus
    garagehof_cam:
      - rtsp://[REDACTED]@192.168.57.59:554/h264Preview_01_main
      #- http://192.168.57.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=[REDACTED]
      - ffmpeg:garagehof_cam#audio=opus
    garagetor_cam:
      - rtsp://[REDACTED]@192.168.57.54:554/h264Preview_01_main
      #- http://192.168.57.54/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=[REDACTED]
      - ffmpeg:garagetor_cam#audio=opus
    hof_cam:
      - rtsp://[REDACTED]@cam-hof.iot:554//h265Preview_01_main
      - ffmpeg:hof_cam#audio=opus
    garten_cam:
      - rtsp://[REDACTED]@garten.iot:554/h264Preview_01_main
      - ffmpeg:garten_cam#audio=opus

birdseye:
  enabled: true
  mode: continuous  #objects
  restream: true

cameras:
  vorhaus:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Vorhaus_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Vorhaus_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      contour_area: 90
      mask:
        - 1736,705,1722,473,1686,348,1624,338,1582,346,1514,310,1527,0,1642,0,1920,0,1920,694,1920,850
        - 462,97,465,233,332,329,306,115,245,55,169,175,194,479,0,393,0,0,667,0
        - 446,290,557,332,600,375,612,436,507,731,351,609,318,407

    snapshots:
      timestamp: true
      bounding_box: true

    record:
      events:
        pre_capture: 10

    detect:
      enabled: true
      max_disappeared: 210
      width: 1920
      height: 1080
      fps: 10

    zones:
      Weg:
        coordinates: 659,202,932,208,936,696,1248,704,1512,1080,378,1080
      Tor:
        coordinates: 687,262,950,252,957,0,688,19
      Heizhaus:
        coordinates: 441,112,543,87,571,275,601,372,613,414,610,456,454,310
      StiegeOben:
        coordinates: 167,141,280,96,362,539,532,730,471,877,273,782,151,420
      StiegeWH2:
        coordinates: 1544,341,1544,0,1238,65,1070,255,1153,340
      StiegeTechnikk:
        coordinates: 1185,3,1199,179,949,272,961,159,969,0,1006,0,1063,0
      Keller2:
        coordinates: 1413,441,1361,774,1572,912,1787,496,1635,337


    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.91
          mask:
            - 1920,1080,1482,1080,1512,838,1760,515,1920,527
            - 347,550,374,598,480,696,532,701,579,616,610,430,569,340,479,316,414,230,305,342

  GarageHof:
    ffmpeg:
      global_args: -hide_banner -loglevel debug -threads 2
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garagehof_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garagehof_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    snapshots:
      timestamp: true
      bounding_box: true
    record:
      events:
        pre_capture: 10
    motion:
      contour_area: 75
      mask:
        - 2514,160,2560,0,1805,0,1751,114,1900,109
    zones:
      ghMitte:
        coordinates: 
          1259,282,655,366,591,961,0,1920,2000,1920,1685,1802,1740,1346,2315,850,2147,724,1545,750,1263,629
        objects:
          - person
          - car
          - dog
        filters:
          car:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      gRightSide:
        coordinates: 682,643,644,0,0,0,0,847,0,1616
        track:
          - person
      gLeftSide:
        coordinates: 
          1544,1172,1320,592,1341,196,1585,185,1873,256,1998,290,2001,522,2560,648,2560,1920,1715,1920
        track:
          - person
    detect:
      enabled: true
      max_disappeared: 1000
      height: 1920
      width: 2560
      fps: 10
    objects:
      track:
        - car
        - person
        - dog
      filters:
        car:
          mask:
            - 2560,850,2528,0,1873,0,0,0,0,1336,0,1480,674,632,665,103,1255,21,1292,46,1309,611

    review:
      alerts:
        required_zones:
          - ghMitte
          - gRightSide
          - gLeftSide
  GarageTor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garagetor_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garagetor_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

   # height: 1232
   # width: 1640
   # fps: 19
    snapshots:
      timestamp: true
      bounding_box: true
    record:
      events:
        pre_capture: 20
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.75
        car:
          mask:
            - 1370,29,1279,633,1440,854,1877,1536,2048,1536,2048,0,466,0,0,0,0,565,0,735,548,547,626,39
    motion:
      contour_area: 75
      mask:
        - 2048,0,2048,66,1294,67,1288,0
      threshold: 35
      improve_contrast: 'true'
    zones:
      ghMitte:
        objects:
          - person
          - car
          - dog
        filters:
          car:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
        coordinates: 
          100,1536,1609,1536,1552,942,1280,626,1403,0,723,0,732,261,730,408,528,713,415,795,139,969
      gRightSide:
        coordinates: 1648,1102,1310,636,1353,274,1356,0,2048,0,2048,461,2048,1536,1762,1536
        track:
          - person
      gLeftSide:
        coordinates: 0,1066,201,822,153,246,309,0,750,0,765,570,139,1536,0,1536
        track:
          - person
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
      max_disappeared: 1000
      height: 1536
      width: 2048
      # 2048*1536
      fps: 10

    review:
      alerts:
        required_zones:
          - ghMitte
          - gRightSide
          - gLeftSide
  Hof:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/hof_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hof_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect


   # height: 1080
   # width: 1920
   # fps: 10
    snapshots:
      timestamp: true
      bounding_box: true
    record:
      events:
        #enabled: True
        pre_capture: 10
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
      max_disappeared: 1000
      #height: 1080
      #width: 1920
      fps: 10
    motion:
      contour_area: 60
      mask:
        - 984,382,1067,382,1126,375,1127,210,978,208
        - 946,1080,1563,1080,1920,539,1920,0,1365,0,1389,275,1303,475,1262,570,1198,689,1109,877
    zones:
      HofWeg:
        coordinates: 
          988,1080,1191,709,1231,659,1254,598,1355,436,1407,312,1314,277,1280,322,1218,353,1204,462,623,1080
        objects:
          - person
          - dog
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.55
          dog:
            threshold: 0.8
    objects:
      filters:
        person:
          mask:
            - 1449,1080,1506,569,1430,505,1294,468,1029,1080


  Garten:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garten_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garten_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

  #  height: 1920
  #  width: 2560

   # fps: 20
    snapshots:
      timestamp: true
      bounding_box: true
    record:
      events:
        pre_capture: 10
    motion:
      contour_area: 70
      threshold: 37
      improve_contrast: 'true'
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
      max_disappeared: 1000
      height: 1296
      width: 2304
      # 2304*1296
      fps: 10
    zones:
      garten_car_zone:
        filters:
          person:
            min_area: 10000
            max_area: 100000
            threshold: 0.80
          dog:
            threshold: 0.87
            min_area: 5000
          car:
            min_area: 6000
            max_area: 100000
        coordinates: 853,1296,2304,1296,2304,740,1787,229,1277,128,902,88,335,145
        objects:
          - person
          - car
          - dog
    objects:
      track:
        - person
        - car
        - dog
      filters:
          person:
            min_area: 10000
            max_area: 100000
            threshold: 0.7
    #objects:
    #  filters:
    #    car:
    #      mask:
    #        - 2560,850,2528,0,1873,0,0,0,0,1336,76,1390,674,632,665,103,1255,21,1368,24,1303,576




    review:
      alerts:
        required_zones:
          - garten_car_zone
  stadtplatz:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/stadtplatz_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stadtplatz_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      contour_area: 90
      mask:
        - 0,0,754,0,698,320,0,640

    snapshots:
      timestamp: true
      bounding_box: true

    record:
      events:
        pre_capture: 10

    detect:
      enabled: true
      max_disappeared: 70
      width: 2560
      height: 1440
      fps: 10

    #zones:
    #  Weg:
    #    coordinates: 653,241,930,239,936,696,1248,704,1512,1080,378,1080


    objects:
      track:
        - person
        - dog
        - shoe
        - package
      filters:
        person:
          min_area: 20000
          threshold: 0.35
        dog:
          threshold: 0.35
          min_area: 20000
        package:
          threshold: 0.68
    #      mask:
    #        - 1920,1080,1482,1080,1512,838,1760,515,1920,527
    #        - 347,550,374,598,480,696,532,701,579,616,610,430,569,340,479,316,414,230,305,342
version: 0.14
camera_groups:
  Kameras:
    order: 1
    icon: LuDoorClosed
    cameras:
      - GarageHof
      - GarageTor
      - Garten
      - Hof
      - stadtplatz
      - vorhaus
```

### docker-compose file or Docker CLI command

```yaml
/usr/bin/podman run --name %N -h %N --memory=6g --ip 10.88.0.7 --shm-size=4096m --pids-limit=8100 -e PLUS_API_KEY="[REDACTED]" --device=/dev/bus/usb:/dev/bus/usb -v /mnt/config/docker/frigate:/config -v /etc/localtime:/etc/localtime:ro -v /mnt/config/docker/frigate/database:/db -v /mnt/dataArray/cams/Frigate:/media/frigate:Z -v /tmp/frigate:/tmp/cache -p 5000:5000 -p 1935:1935 -p 8555:8554/tcp -p 8555:8554/udp -e FRIGATE_RTSP_PASSWORD='password' -a stdin -a stdout -a stderr ghcr.io/blakeblackshear/frigate:0.15.0-beta1
```

### Relevant Frigate log output

```shell
Nov 11 11:50:01 xeon.lan podman[86467]:   File "/opt/frigate/frigate/ffmpeg_presets.py", line 227, in parse_preset_hardware_acceleration_encode
Nov 11 11:50:01 xeon.lan podman[86467]:     return arg_map["default"].format(input, output)
Nov 11 11:50:01 xeon.lan podman[86467]: IndexError: Replacement index 2 out of range for positional args tuple
Nov 11 11:50:01 xeon.lan frigate[88404]:   File "/usr/local/go2rtc/create_config.py", line 168, in <module>
Nov 11 11:50:01 xeon.lan frigate[88404]:     ffmpeg_cmd = f"exec:{parse_preset_hardware_acceleration_encode(ffmpeg_path, config.get('ffmpeg', {}).get('hwaccel_args'), input, '-rtsp_transport tcp -f rtsp {output}')}"
Nov 11 11:50:01 xeon.lan frigate[88404]:   File "/opt/frigate/frigate/ffmpeg_presets.py", line 227, in parse_preset_hardware_acceleration_encode
Nov 11 11:50:01 xeon.lan frigate[88404]:     return arg_map["default"].format(input, output)
Nov 11 11:50:01 xeon.lan frigate[88404]: IndexError: Replacement index 2 out of range for positional args tuple
Nov 11 11:50:01 xeon.lan frigate[88404]: 2024-11-11 11:50:01.872878477  [INFO] The go2rtc service exited with code 1 (by signal 0)
Nov 11 11:50:01 xeon.lan podman[86467]: 2024-11-11 11:50:01.872878477  [INFO] The go2rtc service exited with code 1 (by signal 0)
Nov 11 11:50:02 xeon.lan frigate[88404]: 2024-11-11 11:50:02.879162590  [INFO] Preparing new go2rtc config...
Nov 11 11:50:02 xeon.lan podman[86467]: 2024-11-11 11:50:02.879162590  [INFO] Preparing new go2rtc config...
Nov 11 11:50:03 xeon.lan frigate[88404]: 2024-11-11 11:50:03.421226214  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
Nov 11 11:50:03 xeon.lan frigate[88404]: Traceback (most recent call last):
Nov 11 11:50:03 xeon.lan podman[86467]: 2024-11-11 11:50:03.421226214  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
Nov 11 11:50:03 xeon.lan podman[86467]: Traceback (most recent call last):
Nov 11 11:50:03 xeon.lan podman[86467]:   File "/usr/local/go2rtc/create_config.py", line 168, in <module>
Nov 11 11:50:03 xeon.lan podman[86467]:     ffmpeg_cmd = f"exec:{parse_preset_hardware_acceleration_encode(ffmpeg_path, config.get('ffmpeg', {}).get('hwaccel_args'), input, '-rtsp_transport tcp -f rtsp {output}')}"
Nov 11 11:50:03 xeon.lan podman[86467]:   File "/opt/frigate/frigate/ffmpeg_presets.py", line 227, in parse_preset_hardware_acceleration_encode
Nov 11 11:50:03 xeon.lan podman[86467]:     return arg_map["default"].format(input, output)
Nov 11 11:50:03 xeon.lan podman[86467]: IndexError: Replacement index 2 out of range for positional args tuple
Nov 11 11:50:03 xeon.lan frigate[88404]:   File "/usr/local/go2rtc/create_config.py", line 168, in <module>
Nov 11 11:50:03 xeon.lan frigate[88404]:     ffmpeg_cmd = f"exec:{parse_preset_hardware_acceleration_encode(ffmpeg_path, config.get('ffmpeg', {}).get('hwaccel_args'), input, '-rtsp_transport tcp -f rtsp {output}')}"
Nov 11 11:50:03 xeon.lan frigate[88404]:   File "/opt/frigate/frigate/ffmpeg_presets.py", line 227, in parse_preset_hardware_acceleration_encode
Nov 11 11:50:03 xeon.lan frigate[88404]:     return arg_map["default"].format(input, output)
Nov 11 11:50:03 xeon.lan frigate[88404]: IndexError: Replacement index 2 out of range for positional args tuple
Nov 11 11:50:03 xeon.lan frigate[88404]: 2024-11-11 11:50:03.467063396  [INFO] The go2rtc service exited with code 1 (by signal 0)
Nov 11 11:50:03 xeon.lan podman[86467]: 2024-11-11 11:50:03.467063396  [INFO] The go2rtc service exited with code 1 (by signal 0)
Nov 11 11:50:04 xeon.lan frigate[88404]: 2024-11-11 11:50:04.474739050  [INFO] Preparing new go2rtc config...
Nov 11 11:50:04 xeon.lan podman[86467]: 2024-11-11 11:50:04.474739050  [INFO] Preparing new go2rtc config...
Nov 11 11:50:05 xeon.lan frigate[88404]: 2024-11-11 11:50:05.054595846  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Mostly Reolink

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/ca970c2b-b6a8-4e53-beee-bdfc3a69a8bc)
