### DISCUSSION TITLE
[Support]: Cat detection - review filter on 'person/car' cannot be changed?

### DISCUSSION THREAD

**Discussion by Trashmee** [blakeblackshear/frigate#14914] [General Support]
### Describe the problem you are having

Hi,

I've used frigate for cat detection (are they sane also they don't come around for food..) for long, since 0.14 or so with very little luck. There are a couple of tickets in that regards, seems it might be an area where model tuning.. went sideway.

By accident I noticed that the frigate integration started to show me cats once in a while, however I cannot get the same events to appear in the frigate review tap.

Example: 
 - Frigate shows a nice pic of the cat 6am. Looks like a good, non trivial detection
 - In Frigate /review view I have filters 'all / car / person' - neither of those three options will show the 6am event. 'Show reviewed' is also checked.

I ran through the full reference config, but did not see how I can expand the parameter section to include cat. I added this one (didn't make much sense to me, but seemed closest) - didn't make a difference.

```
review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - person
      - cat
```

I must have a valid detection setup (saw multiple detections in homeassistant integration) - so the question is really - how to remove an implicite filter that seems to be in place?

### Version

frigate:0.15.0-beta1

### Frigate config file

```yaml
version: 0.15-0
logger:
  default: info
  logs:
    frigate.mqtt: error

mqtt:
  host: mqtt.domain.com
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: Password

detectors:
  coral:
    type: edgetpu
    device: usb


database:
  path: /media/frigate/database/frigate.db

semantic_search:
  enabled: True
  reindex: False

birdseye:
  enabled: true
  width: 1920
  height: 1080
  mode: continuous


go2rtc:
  streams:
    vorgarten:
      - rtsp://frigate:Password@192.168.190.53/cam/realmonitor?channel=1&subtype=0
    vorgarten_sub:
      - rtsp://frigate:Password@192.168.190.53/cam/realmonitor?channel=1&subtype=1
    eingang:
      - rtsp://frigate:Password@192.168.190.56/cam/realmonitor?channel=1&subtype=0
    eingang_sub:
      - rtsp://frigate:Password@192.168.190.56/cam/realmonitor?channel=1&subtype=1
    garten:
      - rtsp://frigate:Password@192.168.190.57/cam/realmonitor?channel=1&subtype=0
    garten_sub:
      - rtsp://frigate:Password@192.168.190.57/cam/realmonitor?channel=1&subtype=1
    terasse:
      - rtsp://frigate:Password@terasse.domain.com/cam/realmonitor?channel=1&subtype=0
    terasse_sub:
      - rtsp://frigate:Password@terasse.domain.com/cam/realmonitor?channel=1&subtype=1
    gartentor:
      - rtsp://frigate:Password@gartentor.domain.com:554/h265Preview_01_main
    gartentor_sub:
      - rtsp://frigate:Password@gartentor.domain.com:554/h264Preview_01_sub

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 10
    mode: all
  alerts:
    retain:
      days: 11
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 11
    pre_capture: 5
    post_capture: 5
cameras:
  vorgarten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorgarten
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/vorgarten_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        0.652,1,0.642,0.758,0.794,0.434,0.914,0.493,0.951,0.298,0.79,0.093,0.395,0.168,0.421,0.379,0.107,0.685,0.07,0.992,0.004,0.992,0.001,0.002,0.998,0.01,0.998,0.989
      threshold: 30
      contour_area: 25
      improve_contrast: 'true'
    objects:
      track:
        - person
        - car
        - cat
  eingang:
    detect:
      width: 704
      height: 576
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/eingang
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/eingang_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0.794,0.254,0.786,0.028,0.492,0.067,0.23,0.465,0.209,1,0.245,1,0,0,0
    objects:
      track:
        - person
        - cat
  terasse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terasse
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terasse_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
    motion:
      mask: 0,0,1,0,1,1,0.906,1,0.938,0.779,0.97,0.245,0.736,0.223,0.465,0.343,0,0.651
  garten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garten_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      threshold: 30
      contour_area: 25
      improve_contrast: 'true'
      mask: 1,0.329,0.725,0.199,0.648,0.159,0.117,0.249,0,0.457,0,0,1,0
    objects:
      track:
        - person
        - cat
  gartentor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gartentor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gartentor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat

    motion:
      mask: 0.999,0.982,0.993,0.206,0.25,0.204,0,0.206,0,0,1,0



review:
  alerts:
    labels:
      - person
      - cat
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua + Reolinks
