### DISCUSSION TITLE
[Support]: audio hum in 0.15.0 beta1

### DISCUSSION THREAD

**Discussion by azithromycin** [blakeblackshear/frigate#14913] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Audio hum in 0.15.0 beta1. This also happened in a dev build of 0.15 a month or so ago which triggered me to downgrade back to 0.14.1 which fixed it. At the start of this week I re-upgraded to 0.15.0 beta 1, but the bug is still there.

### Steps to reproduce

Video is attached so you can hear what it sounds like, although it is intermittent and happens when there is sound going on. When it's just ambient, the hum kind of dissapears.

### Version

0.15.0-33825f6

### Frigate config file

```yaml
mqtt:
  enabled: false

semantic_search:
  enabled: True
  reindex: False

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxx

go2rtc:
  streams:
    front_yard_camera:
      - rtsp://frigate:xxxxxxxxx@192.168.0.11:554/Streaming/Channels/101 #Hikvision full stream 101
    driveway_camera:
      - rtsp://frigate:xxxxxxxxxxx@192.168.0.13:554/Streaming/Channels/101 #Hikvision full stream 101
    doorbell_camera:
      - ffmpeg:https://192.168.0.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=xxxxxxxxxx#video=copy#audio=copy#audio=opus

cameras:
  front_yard_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxxxxxxxxxx@192.168.0.11:554/Streaming/Channels/102 # <----- The stream you want to use for detection. hikvision substream 102
          roles:
            - detect
        - path: rtsp://frigate:xxxxxxxxxx@192.168.0.11:554/Streaming/Channels/101 # <----- high res stream for recording
          roles:
            - record
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    motion:
      mask: 0.019,0.053,0.317,0.05,0.316,0.092,0.018,0.092
  driveway_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxxxxxxxxxx@192.168.0.13:554/Streaming/Channels/102 # <----- The stream you want to use for detection. hikvision substream 102
          roles:
            - detect
        - path: rtsp://frigate:xxxxxxxxxx@192.168.0.13:554/Streaming/Channels/101 # <----- high res stream for recording
          roles:
            - record
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    motion:
      mask: 0.019,0.051,0.315,0.05,0.315,0.1,0.021,0.097
  doorbell_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxxxxxxx@192.168.0.12:554/h265Preview_01_sub # <----- The stream you want to use for detection. hikvision substream 102
          roles:
            - detect
        - path: rtsp://frigate:xxxxxxxxx@192.168.0.12:554/h265Preview_01_main # <----- high res stream for recording
          roles:
            - record
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720

    motion:
      mask: 0.009,0.012,0.303,0.008,0.303,0.056,0.009,0.058
record:
  enabled: true
  retain:
    days: 28
    mode: all
  alerts:
    retain:
      days: 60
  detections:
    retain:
      days: 60
objects:
  track:
    - person
    - cat
    - dog
    - bird

snapshots:
  enabled: true
  retain:
    default: 60

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/accel/accel0:/dev/accel/accel0
      - /dev/bus/usb:/dev/bus/usb # USB coral
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      #FRIGATE_RTSP_PASSWORD: "temp"
      PLUS_API_KEY: "xxxxxxxxxxxxxxxxxxxx"
```

### Relevant Frigate log output

```shell
none relevant
```

### Relevant go2rtc log output

```shell
none relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2387G2-LSU/SL

### Screenshots of the Frigate UI's System metrics pages

2024-11-11 16:13:59.141762261  [INFO] Preparing Frigate...
2024-11-11 16:13:59.145996298  [INFO] Starting Frigate...
2024-11-11 16:14:00.521722970  [2024-11-11 16:14:00] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-11 16:14:00.538517211  [2024-11-11 16:14:00] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-11 16:14:00.738246260  [2024-11-11 16:14:00] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-11-11 16:14:00.756169622  [2024-11-11 16:14:00] frigate.app                    INFO    : Starting Frigate (0.15.0-33825f6)
2024-11-11 16:14:00.764432810  [2024-11-11 16:14:00] peewee_migrate.logs            INFO    : Starting migrations
2024-11-11 16:14:00.765016028  [2024-11-11 16:14:00] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-11-11 16:14:00.779060871  [2024-11-11 16:14:00] frigate.app                    INFO    : Recording process started: 546
2024-11-11 16:14:00.784083007  [2024-11-11 16:14:00] frigate.app                    INFO    : Review process started: 548
2024-11-11 16:14:00.786358140  [2024-11-11 16:14:00] frigate.app                    INFO    : go2rtc process pid: 98
2024-11-11 16:14:00.804315635  [2024-11-11 16:14:00] detector.coral                 INFO    : Starting detection process: 563
2024-11-11 16:14:03.624317632  [2024-11-11 16:14:00] frigate.app                    INFO    : Embedding process started: 565
2024-11-11 16:14:03.629099030  [2024-11-11 16:14:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-11-11 16:14:03.629103870  [2024-11-11 16:14:03] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-11-11 16:14:03.629110672  [2024-11-11 16:14:00] frigate.app                    INFO    : Output process started: 587
2024-11-11 16:14:03.629142019  [2024-11-11 16:14:00] frigate.app                    INFO    : Camera processor started for front_yard_camera: 601
2024-11-11 16:14:03.629312904  [2024-11-11 16:14:00] frigate.app                    INFO    : Camera processor started for driveway_camera: 602
2024-11-11 16:14:03.629317098  [2024-11-11 16:14:00] frigate.app                    INFO    : Camera processor started for doorbell_camera: 604
2024-11-11 16:14:03.629576398  [2024-11-11 16:14:00] frigate.app                    INFO    : Capture process started for front_yard_camera: 607
2024-11-11 16:14:03.629580640  [2024-11-11 16:14:00] frigate.app                    INFO    : Capture process started for driveway_camera: 619
2024-11-11 16:14:03.629594436  [2024-11-11 16:14:00] frigate.app                    INFO    : Capture process started for doorbell_camera: 625
2024-11-11 16:14:03.629766036  [2024-11-11 16:14:00] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2024-11-11 16:14:03.629770007  [2024-11-11 16:14:01] frigate.api.fastapi_app        INFO    : FastAPI started
2024-11-11 16:14:20.896798412  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [segment @ 0x5f3674764380] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2024-11-11 16:14:20.903945425  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x5f3674742300] Queue input is backward in time
2024-11-11 16:14:20.904166196  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   :     Last message repeated 1 times
2024-11-11 16:14:20.904169117  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x5f3674742300] Input contains (near) NaN/+-Inf
2024-11-11 16:14:20.904170985  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x5f3674741e80] Error submitting audio frame to the encoder
2024-11-11 16:14:20.904198244  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x5f3674741e80] Error encoding a frame: Invalid argument
2024-11-11 16:14:20.904200433  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x5f3674741e80] Task finished with error code: -22 (Invalid argument)
2024-11-11 16:14:20.904202158  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x5f3674741e80] Terminating thread with return code -22 (Invalid argument)
2024-11-11 16:14:20.904224722  [2024-11-11 16:14:20] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x5f3674742300] 3 frames left in the queue on closing
2024-11-11 16:14:20.904241720  [2024-11-11 16:14:20] watchdog.front_yard_camera     INFO    : Terminating the existing ffmpeg process...
2024-11-11 16:14:20.904243054  [2024-11-11 16:14:20] watchdog.front_yard_camera     INFO    : Waiting for ffmpeg to exit gracefully...
2024-11-11 16:14:30.921588185  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [segment @ 0x606acef16f80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2024-11-11 16:14:30.921593217  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x606aceefbf40] Input contains (near) NaN/+-Inf
2024-11-11 16:14:30.921595751  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x606aceeed540] Error submitting audio frame to the encoder
2024-11-11 16:14:30.921597693  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x606aceeed540] Error encoding a frame: Invalid argument
2024-11-11 16:14:30.921616908  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x606aceeed540] Task finished with error code: -22 (Invalid argument)
2024-11-11 16:14:30.921623318  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x606aceeed540] Terminating thread with return code -22 (Invalid argument)
2024-11-11 16:14:30.921792955  [2024-11-11 16:14:30] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x606aceefbf40] 3 frames left in the queue on closing
2024-11-11 16:14:30.921796337  [2024-11-11 16:14:30] watchdog.front_yard_camera     INFO    : Terminating the existing ffmpeg process...
2024-11-11 16:14:30.921798618  [2024-11-11 16:14:30] watchdog.front_yard_camera     INFO    : Waiting for ffmpeg to exit gracefully...
2024-11-11 16:14:40.937633955  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [segment @ 0x61069b2e8f80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2024-11-11 16:14:40.937686922  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x61069b2c7f80] Queue input is backward in time
2024-11-11 16:14:40.937731081  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   :     Last message repeated 1 times
2024-11-11 16:14:40.937770481  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x61069b2c7f80] Input contains (near) NaN/+-Inf
2024-11-11 16:14:40.937810056  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x61069b3169c0] Error submitting audio frame to the encoder
2024-11-11 16:14:40.937847572  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x61069b3169c0] Error encoding a frame: Invalid argument
2024-11-11 16:14:40.937885122  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x61069b3169c0] Task finished with error code: -22 (Invalid argument)
2024-11-11 16:14:40.937922188  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aost#0:1/aac @ 0x61069b3169c0] Terminating thread with return code -22 (Invalid argument)
2024-11-11 16:14:40.937958498  [2024-11-11 16:14:40] ffmpeg.front_yard_camera.record ERROR   : [aac @ 0x61069b2c7f80] 3 frames left in the queue on closing
2024-11-11 16:14:40.937994543  [2024-11-11 16:14:40] watchdog.front_yard_camera     INFO    : Terminating the existing ffmpeg process...
2024-11-11 16:14:40.938034799  [2024-11-11 16:14:40] watchdog.front_yard_camera     INFO    : Waiting for ffmpeg to exit gracefully...

### Any other information that may be helpful

https://github.com/user-attachments/assets/72435229-c9b7-45d3-ad01-c4bd5bdd0e10
