### DISCUSSION TITLE
[Support]: HA frigate integration is not showing clips

### DISCUSSION THREAD

**Discussion by karopodgajecki** [blakeblackshear/frigate#14938] [General Support]
### Describe the problem you are having

Hello, 

I have strange issue maybe somone will be able to help. Frigate instance is running perfectly Im able to get recordings view alerts etc. 

What more Im able to see Live view in HA (screenshot): 

![image](https://github.com/user-attachments/assets/63e81732-da0f-4e7b-95c1-9c3c76a409dc)

Problem is when I try to go to media -> frigate -> recordings. It looks like this: 

![image](https://github.com/user-attachments/assets/bc46f418-c06e-4894-ad73-be6ef2883d5a)

The undefined part in request is suprising for me. 

http://ha-link:8123/media-browser/browser/app%2Cmedia-source%3A%2F%2Ffrigate/video%2Cmedia-source%3A%2F%2Ffrigate%2Ffrigate%2Frecordings%2F%2F%2F/video%2Cmedia-source%3A%2F%2Ffrigate%2Ffrigate%2Frecordings%2Ftylsrodek%2F%2F/**undefined**

Do you maybe have any idea what is going on ? 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.250
  port: 1883
  user: secretuser
  password: secretpassword

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  przodsrodek:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.6:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.6:554
          roles:
            - record
    motion:
      mask: 0,0.401,0.39,0.405,0.692,0.443,0.837,0.469,1,0.506,0.994,0.003,0,0.001
    zones:
      Detect:
        coordinates: 0,0.402,0.001,0.993,0.996,0.991,1,0.509,0.829,0.468,0.688,0.44,0.393,0.409
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Detect
      detections:
        required_zones: Detect
  przodlewa:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.4:554
          roles:
            - record
    motion:
      mask: 
        0.129,0.994,0.447,0.431,0.514,0.287,0.523,0.227,0.521,0.003,0.013,0.039,0.002,0.991
    zones:
      Detect:
        coordinates: 
          0.142,0.991,0.517,0.319,0.543,0.238,0.536,0.178,0.535,0.014,0.62,0.012,0.651,0.991
        loitering_time: 0
    review:
      alerts:
        required_zones: Detect
      detections:
        required_zones: Detect
  przodprawa:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.7:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.7:554
          roles:
            - record
  garaz:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.2:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.2:554
          roles:
            - record
  tylsrodek:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.3:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.3:554
          roles:
            - record
  tyllewa:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.8:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.8:554
          roles:
            - record
    motion:
      mask: 
        0.597,0.313,0.943,0.988,0.998,0.991,0.988,0.017,0.443,0.003,0.469,0.24,0.587,0.237,0.595,0.306
    zones:
      Detekcja:
        coordinates: 0.486,0.992,0.941,0.986,0.568,0.238,0.467,0.234
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Detekcja
      detections:
        required_zones: Detekcja
    objects:
      mask: 
        0.587,0.242,0.62,0.339,0.945,0.986,0.999,0.988,0.985,0.02,0.458,0.001,0.478,0.237
  tylprawa:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://user:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://user:password123123@192.168.1.5:554
          roles:
            - record
detect:
  enabled: true


objects:
  track:
    - person
    - car
    - bicycle
    - bus

review:
  alerts:
    labels:
      - car
      - person
      - bicycle
      - bus
  detections:
    labels:
      - car
      - person
      - bicycle
      - bus


record:
  enabled: true
  expire_interval: 1440
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 12
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: medium
  events:
    pre_capture: 10
    post_capture: 30
    objects:
      - car
      - person
      - bicycle
      - bus
    retain:
      default: 10
      mode: motion


snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  quality: 70

motion:
  enabled: true

version: 0.14

camera_groups:
  Przod:
    order: 1
    icon: LuArrowBigUp
    cameras:
      - przodlewa
      - przodprawa
      - przodsrodek
  Tyl:
    order: 2
    icon: LuArrowBigDown
    cameras:
      - tylsrodek
      - tylprawa
      - tyllewa

```

### Relevant Frigate log output

```shell
No needed
```

### Relevant go2rtc log output

```shell
No needed
```

### FFprobe output from your camera

```shell
No needed
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
No need
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

BCS
