### DISCUSSION TITLE
[Support]: Sometimes Review Motion keeps loading without any results

### DISCUSSION THREAD

**Discussion by Dave-c-Ross** [blakeblackshear/frigate#14943] [General Support] [answered]
### Describe the problem you are having

Like the screenshot shows, sometimes I am not able to see motions in the Review->Motion panel. It keeps loading and loading without ends. I am trying to figure out what can cause this. 

![image](https://github.com/user-attachments/assets/89aa1e5d-2f21-4b23-bcaf-9e7b91d0d8ef)

### Version

0.15.0-33825f6

### What browser(s) are you using?

Google Chrome 130.0.6723.93

### Frigate config file

```yaml
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: []
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic

audio:
  enabled: false

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  min_initialized: 2

  max_disappeared: 25
  stationary:
    interval: 10
    threshold: 50

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog

motion:
  threshold: 15
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: false
  mqtt_off_delay: 30

record:
  sync_recordings: false
  enabled: true

  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 15
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 15
    pre_capture: 5
    post_capture: 5

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  required_zones: []
  retain:
    default: 10

live:
  height: 1080
  quality: 1

timestamp_style:
  position: tr
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid

cameras:

  Frontyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@IP:PORT/s0
          roles:
            - detect
            - record
            # - rtmp
    best_image_timeout: 60
    mqtt:
      enabled: false
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []

    ui:
      order: 0
      dashboard: true

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.002,0.315,0.052,0.437,0.094,0.616,0.121,0.636,0.105,0.565,0.252,0.525,0.418,0.545,0.518,0.488,0.64,0.425,0.726,0.467,0.861,0.475,0.938,0.469,0.968,0.528,1,0.545,1,1,0.79,1,0,1
        - 0,0,1,0,1,0.061,0.848,0.033,0.689,0.028,0.501,0.035,0.307,0.053,0.17,0.078,0,0.127
    zones:
      Lawn:
        coordinates: 
          0.348,0.202,0.689,0.204,0.974,0.238,1,0.263,0.997,0.871,0.741,0.839,0.402,0.753,0.365,0.56,0.473,0.311,0.233,0.298
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
      Entrance:
        coordinates: 0.191,0.175,0.152,0.199,0.343,0.202,0.386,0.174
        loitering_time: 0
        objects: car
        inertia: 3
      Sidewalk:
        coordinates: 0.35,0.2,0.483,0.109,0.748,0.108,0.912,0.124,0.998,0.151,0.998,0.238
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
      Driveway:
        coordinates: 
          0,0.3,0.116,0.202,0.346,0.202,0.122,0.389,0.299,0.432,0.195,0.667,0,0.575,0,0.457
        loitering_time: 0
        objects: car
    review:
      alerts:
        required_zones:
          - Driveway
          - Entrance
          - Lawn
    detect:
      annotation_offset: -550
mqtt:
  enabled: false
detectors:
  cpu_1:
    type: cpu
    num_threads: 6
database:
  path: /media/frigate/frigate.db
logger:
  default: info
  logs:
    frigate.event: debug
birdseye:
  enabled: false
tls:
  enabled: false
version: 0.15-0
```

### Relevant Frigate log output

```shell
None, no log are produced during that motion loading time.
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
root@frigate-deployment-7cf7b8b44d-bkjwr:/opt/frigate# ffprobe
bash: ffprobe: command not found
```

### Frigate stats

```json
{
"cameras": {
"Salon": {
"camera_fps": 5,
"process_fps": 5,
"skipped_fps": 0,
"detection_fps": 2.7,
"detection_enabled": true,
"pid": 486,
"capture_pid": 487,
"ffmpeg_pid": 507,
"audio_rms": 0,
"audio_dBFS": 0
}
},
"detectors": {
"cpu_1": {
"inference_speed": 74.88,
"detection_start": 0,
"pid": 454
}
},
"detection_fps": 2.7,
"cpu_usages": {
"1": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
},
"15": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6-linux-init-shutdownd"
},
"16": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
},
"24": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-oneshot-runner"
},
"25": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-fdholder"
},
"26": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync"
},
"27": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync-log"
},
"28": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate"
},
"29": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate-log"
},
"30": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc"
},
"31": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-healthcheck"
},
"32": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-log"
},
"33": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx"
},
"34": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx-log"
},
"45": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
},
"46": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
},
"86": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
},
"87": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
},
"89": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
},
"90": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
},
"98": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
},
"106": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user go2rtc-healthcheck"
},
"107": {
"cpu": "1.3",
"cpu_average": "2",
"mem": "0.3",
"cmdline": "python3 -u -m frigate"
},
"126": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: master process nginx"
},
"240": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"241": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"242": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"246": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"258": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: cache manager process"
},
"416": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user certsync"
},
"434": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 9999"
},
"437": {
"cpu": "1.2",
"cpu_average": "1",
"mem": "0.2",
"cmdline": "frigate.recording_manager"
},
"444": {
"cpu": "0.3",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "frigate.review_segment_manager"
},
"453": {
"cpu": "0.1",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(23)"
},
"454": {
"cpu": "142.0",
"cpu_average": "143",
"mem": "0.2",
"cmdline": "frigate.detector.cpu_1"
},
"471": {
"cpu": "0.1",
"cpu_average": "1",
"mem": "0.2",
"cmdline": "frigate.output       "
},
"485": {
"cpu": "0.1",
"cpu_average": "5",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1920x1080 -codec:v mpeg1video -q 1 -bf 0 pipe:"
},
"486": {
"cpu": "10.9",
"cpu_average": "11",
"mem": "0.2",
"cmdline": "frigate.process:Salon"
},
"487": {
"cpu": "1.7",
"cpu_average": "1",
"mem": "0.2",
"cmdline": "frigate.capture:Salon"
},
"507": {
"cpu": "29.5",
"cpu_average": "28",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-33825f6 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.1.211:554/s0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Salon@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"721": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(46)"
},
"7884": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 30s"
},
"frigate.full_system": {
"cpu": "35.3",
"mem": "27.9"
}
},
"service": {
"uptime": 3408,
"version": "0.15.0-33825f6",
"latest_version": "0.14.1",
"storage": {
"/media/frigate/recordings": {
"total": 2096128,
"used": 17235.1,
"free": 2078892.9,
"mount_type": "xfs"
},
"/media/frigate/clips": {
"total": 2096128,
"used": 17235.1,
"free": 2078892.9,
"mount_type": "xfs"
},
"/tmp/cache": {
"total": 228359.6,
"used": 79287.1,
"free": 149072.5,
"mount_type": "overlay"
},
"/dev/shm": {
"total": 95405.6,
"used": 66.9,
"free": 95338.7,
"mount_type": "tmpfs"
}
},
"temperatures": {},
"last_updated": 1731434863
},
"processes": {
"recording": {
"pid": 437
},
"review_segment": {
"pid": 444
},
"go2rtc": {
"pid": 98
}
}
}
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
#Installed on OpenShift
#Here is the deployment 


kind: Deployment
apiVersion: apps/v1
metadata:
  name: frigate-deployment
  namespace: frigate
  labels:
    app: frigate-deployment

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

  selector:
    matchLabels:
      app: frigate-app
  
  template:
    metadata:
      labels:
        app: frigate-app

    spec:
      serviceAccountName: frigate-sa
      restartPolicy: Always
      schedulerName: default-scheduler
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      securityContext: {}

      initContainers:
      - name: init-config
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - cp /tmp/config.yml /config/config.yml
        volumeMounts:

          - name: frigate-config-volume
            mountPath: /tmp/config.yml
            subPath: config.yml

          - name: config-volume
            mountPath: /config

          # - name: data-volume
          #   mountPath: /data

      containers:
        
        - name: frigate

          # image: 'ghcr.io/blakeblackshear/frigate:stable'
          image: 'ghcr.io/blakeblackshear/frigate:0.15.0-beta1'
          imagePullPolicy: IfNotPresent

          terminationMessagePolicy: File
          terminationMessagePath: /dev/termination-log

          resources:
            limits:
              cpu: '6'
    
          readinessProbe:
            httpGet:
              path: /api/version
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

          env:
            - name: TZ
              value: America/New_York
    
          ports:
              # Authenticated UI and API access without TLS. Reverse proxies should use this port.
            - containerPort: 8971
              protocol: TCP

              #Internal unauthenticated UI and API access. Access to this port should be limited. Intended to be used within the docker network for services that integrate with Frigate.
            # - containerPort: 5000
            #   protocol: TCP

              # RTSP restreaming. By default, these streams are unauthenticated. Authentication can be configured in go2rtc section of config.
            - containerPort: 8554
              protocol: TCP

              # WebRTC connections for low latency live views.
            - containerPort: 8555
              protocol: TCP
            - containerPort: 8555
              protocol: UDP

          volumeMounts:
            - name: config-volume
              mountPath: /config

            # - name: frigate-config-volume
            #   mountPath: /config/config.yml
            #   subPath: config.yml
            
            - name: frigate-data-volume
              mountPath: /media/frigate
            
            - name: cache-volume
              mountPath: /config/model_cache

            - name: dshm
              mountPath: /dev/shm

      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 500Mi

        - name: config-volume
          persistentVolumeClaim:
            claimName: frigate-config-pvc

        - name: frigate-config-volume
          configMap:
            name: frigate-config
            defaultMode: 0666

        - name: frigate-data-volume
          persistentVolumeClaim:
            claimName: frigate-data-pvc

        - name: dshm
          emptyDir:
            medium: Memory
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Unifi Bullet Flex 3

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/8df52969-8998-49fe-966a-050f2bb14b58)

**Comment by NickM-27** [comment]
this is likely an issue with using CPU detector, what hardware are you running on?

**Comment by Dave-c-Ross** [comment]
Actually the whole review panel seems to get this issue now, Alerts Detections and Motion. But I can see the recordings when using explore. I do use CPU detector, I am waiting on my Coral to be shipped :), that said I didn't thought it would be the issue since it happen after the motion/detection/recording (for the issue in review->Alerts).

I am using an Intel server with 2 CPU Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz each 10 core and HT enabled, probably not the best rig, and I was thinking on disabling HT, it probably generate a lots of interrupts.

FYI it was working OK with 0.14 🤔

**Comment by Dave-c-Ross** [comment]
Rollback to 0.14.1-f4f3cfa and now the whole review pan works, including Motion

![image](https://github.com/user-attachments/assets/59789627-85ad-4483-a257-03ac755923ab)

I haven't changed the config file except commenting out the retain.alerts and retain.detections as they aren't in the 0.14 schema and give error when starting Frigate

```
record:
  sync_recordings: false
  enabled: true
  # expire_interval: 60

  retain:
    days: 2
    mode: all
  # alerts:
  #   retain:
  #     days: 15
  #   pre_capture: 5
  #   post_capture: 5
  # detections:
  #   retain:
  #     days: 15
  #   pre_capture: 5
  #   post_capture: 5
```
