### DISCUSSION TITLE
[Config Support]: Cameras do not load on Android and iOS in Homeassistant

### DISCUSSION THREAD

**Discussion by Se7enair** [blakeblackshear/frigate#14941] [Config Support]
### Describe the problem you are having

I try to open the camera stream on a homeassistant 2024.11 instance.
On Windows and Linux desktop the stream opens after a short loading time and plays live.

On android and iOS it does not open. Android loads forever and on iOS I got the message `"Failed to connect WebRTC stream: Attempted to assign to readonly property."`

Frigate is 0.14.1
Homeassistant 2024.11.1

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 
  user: 
  password: 
go2rtc:
  # rtsp:
  #   username: ""
  #   password: ""
  streams:
    gartentuere:
      - ffmpeg:http://xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
    gartentuere_sub:
      - ffmpeg:http://xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx
    hof:
      - ffmpeg:http://xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
    hof_sub:
      - ffmpeg:http://xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx
  webrtc:
    candidates:
      - 10.0.30.101:8555
      - 192.168.178.31:8555
      - stun:8555
cameras:
  gartentuere:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gartentuere?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gartentuere_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    # live:
    #   stream_name: gartentuere_sub
    detect:
      max_disappeared: 100
      width: 896
      height: 514
      fps: 7
      stationary:
        max_frames:
          default: 500
    objects:
      track:
        - person
        - bicycle
      filters:
        car: {}
    motion:
      mask:
        - 280,250,339,215,508,0,0,0,0,437,312,441
      threshold: 50
      contour_area: 150
    snapshots:
      enabled: true
      crop: false
      retain:
        default: 30
        objects:
          person: 40
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 12
        retain:
          default: 10
          mode: all
          objects:
            person: 15
    ui:
      order: 1

    zones:
      entrance:
        coordinates: 0.451,0.265,0.703,0.292,0.687,0.857,0.331,0.667,0.32,0.487
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: entrance
      detections:
        required_zones: entrance
  hof:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hof?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hof_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      max_disappeared: 100
      width: 896
      height: 672
      fps: 7
      stationary:
        interval: 50
        threshold: 50
    zones:
      einfahrt:
        coordinates: 566,57,896,276,765,584,114,672,0,372,0,93
        objects:
          - car
      strasse:
        coordinates: 148,117,590,85,556,49,136,82
        objects:
          - car
      full:
        coordinates: 0,0.085,0.625,0.045,1,0.463,0.816,1,0,1
        objects:
          - person
          - bicycle
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - bicycle
      filters:
        car:
          mask:
            - 148,63,245,360,49,411,0,357,0,86
    motion:
      threshold: 50
      contour_area: 150
    snapshots:
      enabled: true
      crop: false
      required_zones:
        - strasse
        - full
      retain:
        default: 30
        objects:
          person: 40
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 12
        retain:
          default: 10
          mode: all
          objects:
            person: 15
            car: 3
    ui:
      order: 2

    review:
      alerts:
        required_zones:
          - full
          - einfahrt
      detections:
        required_zones: einfahrt
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  mode: continuous
version: 0.14
camera_groups:
  Dashboard:
    order: 1
    icon: LuLayoutDashboard
    cameras: dashboard
```

### Relevant Frigate log output

```shell
there is no relevant log
```

### Relevant go2rtc log output

```shell
also here
```

### Frigate stats

```json
{
    "cameras": {
        "gartentuere": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 7,
            "capture_pid": 405,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 423,
            "pid": 397,
            "process_fps": 7,
            "skipped_fps": 0
        },
        "hof": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 7,
            "capture_pid": 412,
            "detection_enabled": true,
            "detection_fps": 0,
            "ffmpeg_pid": 426,
            "pid": 401,
            "process_fps": 7,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "34": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "47": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "87": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "88": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "90": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "102": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "3.1",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "123": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "1.1"
        },
        "124": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "133": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "156": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "157": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "158": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "159": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "288": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "297": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "323": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "332": {
            "cmdline": "frigate.recording_manager",
            "cpu": "1.9",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "341": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "360": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(59)",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "361": {
            "cmdline": "frigate.detector.coral",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "363": {
            "cmdline": "frigate.output       ",
            "cpu": "1.3",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "371": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x514 -i pipe: -threads 1 -f mpegts -s 1255x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "3.3",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "377": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "2.6",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "382": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "397": {
            "cmdline": "frigate.process:gartentuere",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "401": {
            "cmdline": "frigate.process:hof  ",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "405": {
            "cmdline": "frigate.capture:gartentuere",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "412": {
            "cmdline": "frigate.capture:hof  ",
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "423": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gartentuere_sub?video=copy -r 7 -vf fps=7,scale=896:514 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.3",
            "cpu_average": "3",
            "mem": "0.1"
        },
        "426": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hof_sub?video=copy -r 7 -vf fps=7,scale=896:672 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "3.5",
            "cpu_average": "3",
            "mem": "0.1"
        },
        "428": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.0.30.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9117806c952d8dcad75da83efd85d3ab",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "429": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gartentuere?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/gartentuere@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "432": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.0.30.28/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/0844c3c858617a13127bcf18a0381fc7",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "433": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hof?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/hof@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "437": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.0.30.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/545cf6eb6618f3efa7065504c638a305",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "440": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.0.30.28/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b1ef6df356abe206baec671a73cfb8dc",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "964": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(48)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "9406": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "9423": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "26.5",
            "mem": "56.9"
        }
    },
    "detection_fps": 0,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 10.38,
            "pid": 361
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 102
        },
        "logger": {
            "pid": 323
        },
        "recording": {
            "pid": 332
        },
        "review_segment": {
            "pid": 341
        }
    },
    "service": {
        "last_updated": 1731414664,
        "latest_version": "0.14.1",
        "storage": {
            "/dev/shm": {
                "free": 508.9,
                "mount_type": "tmpfs",
                "total": 512,
                "used": 3.1
            },
            "/media/frigate/clips": {
                "free": 6545.7,
                "mount_type": "ext4",
                "total": 100221.1,
                "used": 88785.2
            },
            "/media/frigate/recordings": {
                "free": 6545.7,
                "mount_type": "ext4",
                "total": 100221.1,
                "used": 88785.2
            },
            "/tmp/cache": {
                "free": 945.4,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 8.3
            }
        },
        "temperatures": {},
        "uptime": 4832,
        "version": "0.14.1-f4f3cfa"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/frigate/config:/config:rw
      - /media/frigate/media:/media/frigate:rw

      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" #restream
      - "8555:8555/tcp" #webrtc over tcp
      - "8555:8555/udp" #webrtc over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
```

### Object Detector

Coral
