### DISCUSSION TITLE
Motion detected with no movements

### DISCUSSION THREAD

**Discussion by woody4165** [blakeblackshear/frigate#14950] [Config Support] [answered]
### Describe the problem you are having

Hi all

During day, I get a lot of false motion probably due to road floor and I don't know how to avoid it
I tried with and without improve contrast, reducing contour area and threshold, but I always get those red squares

![Screenshot 2024-11-13 alle 09 45 00](https://github.com/user-attachments/assets/44f59892-0a53-4b14-8d34-8059e7657cfa)

What can I do ?
 
Thanks

### Version

0.14.1-

### Frigate config file

```yaml
mqtt:
  host: xxxxxx
  user: xxxxx
  password: xxxxxxx
  topic_prefix: frigate
detectors:
  coral:
    type: edgetpu
    device: usb



ffmpeg:
  hwaccel_args: preset-vaapi


review:
  alerts:
    labels:
      - car
      - motorcycle
      - bicycle
      - person
  detections:
    labels:
      - cat
      - dog
      - speech


record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: motion
  expire_interval: 10

snapshots:
  enabled: true
  retain:
    default: 7

cameras:



  vialetto:
    ui:
      order: 1
    birdseye:
      order: 1

    ffmpeg:
      inputs:
        - path: 
            rtsp://xxxxxx:xxxxx@xxxxxxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif

          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1024
      height: 768
      fps: 5
      min_initialized: 2
      # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    mqtt:
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 500


    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
      filters:
        car:
          min_area: 5000
          max_area: 400000

          min_score: 0.3
          threshold: 0.5

        dog:
          min_score: 0.3
          threshold: 0.7
        cat:
          threshold: 0.6
          min_score: 0.4


    motion:
      mask:
        - 0.148,0,0.17,0.291,0.415,0.276,0.6,0.238,0.627,0
        - 1,1,1,1,0.946,1,0.958,0.639,0.977,0.008,1,0
        - 0.962,0.111,0.967,0.052,0.839,0.049,0.841,0.103
      threshold: 15
      lightning_threshold: 0.8
      contour_area: 10
      frame_alpha: 0.01
      improve_contrast: 'false'


    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2
        mode: active_objects
        objects:
          dog: 1
          cat: 1
          car: 2
          person: 5
    record:
      preview:
        quality: high
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 10
        post_capture: 20
        retain:
          default: 7
          mode: active_objects
          objects:
            dog: 1
            cat: 1
            car: 2
            person: 5


    zones:
      viale:
        coordinates: 0.989,0.008,0.007,0.007,0,1,0.981,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: viale
      detections:
        required_zones: viale


model:
  path: /edgetpu_model.tflite

version: 0.14
```

### Relevant Frigate log output

```shell
no relevant log
```

### Relevant go2rtc log output

```shell
no relevant log
```

### Operating system

Proxmox

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

Coral
