### DISCUSSION TITLE
Frigate feeds in HA are choppy via CloudFlare

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#14959] [Ask A Question]
Maybe more of a HA question but I haven't gotten any guidance on HA forums so I thought I'd post it here.

I have a cloudflare tunnel to access my HA server when remote. I use the Frigate add-on (6 IP cameras, RTSP) and when I'm connected to my home network, the streams via webRTC are perfect.

But when I view remotely (at work, on a my parent's wifi, on my phone's 5G, etc.), the feeds are super choppy. I'm wondering if that has to do with the CloudFlare tunnel and not allowing it to adequately use webRTC. I've seen a few mentions of this online but have yet to find a conclusive answer.

I'm thinking it may be better to just use NabaCasa for remote but I don't want to do all those changes if this isn't the actual issue. 

Happy to provide more info if needed.

**Comment by NickM-27** [comment]
would be good to see the frigate config

**Reply by templeowls21** [reply]
Sorry, see below:

```
mqtt:
  host: 192.168.107.2
  port: 1883
  user: username
  password: password
  topic_prefix: frigate

go2rtc:
  streams:
    FrontPorch:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=0
    FrontPorch_sub:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=1
    Driveway:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=1
    FrontYardRight:
      - rtsp://admin:admin@192.168.107.48:554/cam/realmonitor?channel=1&subtype=0
    FrontYardRight_sub:
      - rtsp://admin:admin@192.168.107.48:554/cam/realmonitor?channel=1&subtype=1
    BackDeck:
      - rtsp://admin:admin@192.168.107.43:554/cam/realmonitor?channel=1&subtype=0
    BackDeck_sub:
      - rtsp://admin:admin@192.168.107.43:554/cam/realmonitor?channel=1&subtype=1
    BackPatio:
      - rtsp://admin:admin@192.168.107.41:554/cam/realmonitor?channel=1&subtype=0
    BackPatio_sub:
      - rtsp://admin:admin@192.168.107.41:554/cam/realmonitor?channel=1&subtype=1
    SideYardLeft:
      - rtsp://admin:admin@192.168.107.44:554/cam/realmonitor?channel=1&subtype=0
    SideYardLeft_sub:
      - rtsp://admin:admin@192.168.107.44:554/cam/realmonitor?channel=1&subtype=1

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
  Driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
      mask: 0.113,1,0.152,0.697,0.699,0.69,0.822,1
  FrontYardRight:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontYardRight
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontYardRight_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
  BackDeck:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BackDeck
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackDeck_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: false
  BackPatio:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BackPatio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackPatio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: false
  SideYardLeft:
    ui:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/SideYardLeft
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SideYardLeft_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: false
```
