### DISCUSSION TITLE
[Support]: Review clips not playing in Frigate 0.15.0-beta1-h8l

### DISCUSSION THREAD

**Discussion by hiteshsharma** [blakeblackshear/frigate#14968] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I'm using 0.15.0-beta1-h8l. Detection and record is working file but when I open a clip to review, the clip doesn't plays. I see that the video element in html is using the clip `https://localhost:8971/vod/doorbell/start/1731528000/end/1731531600/master.m3u8`. The clips preview shows on UI and the play icon shows ⏸️ (playing) icon but the clip doesn't plays. When I open the clip url in a new window, same thing happens. Browser's native media player shows the first frame but the clip doesn't plays.

I tried in Firefox and Safari, same thing. No error in console. No error in logs. 
In network tab I see an error for request `https://localhost:8971/vod/doorbell/start/1731528000/end/1731531600/seg-48-v1-a1.ts` but the status is 200 ok.

Issue is also reproducible on home assistant lovelace card

### Steps to reproduce

1. Click a clip to review on either frigate home page or on review page
2. Clip doesn't plays on review page.
...

### Version

0.15.0-33825f6

### In which browser(s) are you experiencing the issue with?

Safari 17.5 (19618.2.12.11.6) and Firefox 132.0.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.98         
  #port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ******              
  password: ********  
  stats_interval: 60

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub?timeout=30
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell?timeout=30
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
    live:
      stream_name: doorbell
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_sub?timeout=30
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage?timeout=30
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 4
    objects:
      track:
        - person
    live:
      stream_name: garage

    motion:
      threshold: 60
      contour_area: 30
      improve_contrast: false
ffmpeg:
  input_args: preset-rtsp-restream-low-latency #-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    record: preset-record-generic-audio-copy
 # hwaccel_args:
#    - -c:v:1
   # - hevc_v4l2m2m
go2rtc:
  webrtc:
    listen: ":8555/tcp" 
    candidates:
      - 192.168.1.98:8555
      - stun:8555
      - mydomain:8555
    ice_servers:
      - urls: [ stun:stun1.l.google.com:19302 ]

      
  streams:
                    ## CHANGE RTSP USERNAME AND PASSWORD
    doorbell:
      - rtsp://*****:*******@192.168.1.100:554/h264Preview_01_main
      - ffmpeg:doorbell#video=copy#audio=opus#async#timeout=30

    doorbell_sub:
      - rtsp://*****:*******@192.168.1.100:554/h264Preview_01_sub
      - ffmpeg:doorbell_sub#video=copy#async#timeout=30 #audio=opus#async#raw=-filter:v "fps=4"

    garage:
      - rtsp://*****:*******@192.168.1.103:554/h264Preview_01_main
      - ffmpeg:garage#video=copy#audio=opus#async#timeout=30
    garage_sub:
      - rtsp://*****:*******@192.168.1.103:554/h264Preview_01_sub
      - ffmpeg:garage_sub#video=copy#async#timeout=30

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    volume: \"-af highpass=f=80, lowpass=f=10000, volume=3.0, bass=g=3\"
    #myinput: "-fflags nobuffer -flags low_delay -timeout 5000000 -fflags +genpts -filter_complex \"[0:v]fps=4[v]\" -map \"[v]\" -map 0:a -i {input}"

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: ssd

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
  sync_recordings: true
version: 0.15-0

logger:
  logs:
    frigate.record: debug
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:ddfdb71-h8l
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1-h8l
    shm_size: "164mb" # update for your cameras based on calculation above
    devices:
      - /dev/hailo0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "1984:1984"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "60604:60604" # Port for go2rtc two-way audio stream
```

### Relevant Frigate log output

```shell
no errors or relevant logs in log
```

### Relevant go2rtc log output

```shell
no errors or relevant logs in log
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink PoE doorbell

### Screenshots of the Frigate UI's System metrics pages

<img width="1667" alt="Screenshot 2024-11-13 at 3 32 00 PM" src="https://github.com/user-attachments/assets/9545032f-4e9b-4e99-925b-04ee07dac5d5">
