### DISCUSSION TITLE
Review Logic Seems Flawed — Nevermind...

### DISCUSSION THREAD

**Discussion by johnmarksilly** [blakeblackshear/frigate#14971] [Ask A Question] [answered]
So here is my biggest gripe with the review mechanism. Before I could ignore all events that weren't on my property through a label, but now all events get grouped together with property labeled events if they occur with close timestamps. 

I have a camera facing an intersection right in front of my house. I want to record the intersection, but I don't care about most events. 

I mark the config, alerts -> required_zones: property. I don't care if detections contain non-property events. 

Unfortunately though, when this intersection gets busy and a car does come into my driveway, every subsequent car that passes by re-triggers an update to this review item. Attached is an example. 

Only one car is actually on my property, but because all the other cars happened to drive by within short time periods of each other, they re-trigger the alert. 

![image](https://github.com/user-attachments/assets/687446dc-230c-4158-b8ea-6c6b26af7f8e)

Everything further down is a vehicle passing by. 

Any suggestions?

Basically my only thought is to now remove cars as a label for alerts, but even people will be an issue since that intersection is a bus pickup.

**Comment by NickM-27** [comment]
Just remove car from the detections -> label list

**Reply by johnmarksilly** [reply]
The problem with removing car is that I no longer will see the snapshot in the detections section. 

My scenario is as follows, all alerts should be labels I care about that enter my property zone. 

These are the only things I want alerts for. 

However, just recently I had a situation where I needed to see if  I got a plate for a particular car. So I needed cars as a label in the detections category in order to see the ones not on my property. 

I have 24/7 recordings of everything, but it's not helpful to scrub through hours of footage. Now that individual events aren't surfaced up, I don't see those without having the detection set up in review. 

I'm not sure I understand why setting required_zones doesn't force review items to actually require that zone. It basically just means, required_start_zones. 

There should be a configurable cooldown that I could set to 5 seconds or something low or be able to force all events to also be of a zone before aggregating them together.

When the feature was rolled out, I thought it would aggregate across cameras too which would be ideal.

**Reply by NickM-27** [reply]
> I'm not sure I understand why setting required_zones doesn't force review items to actually require that zone. It basically just means, required_start_zones.

If someone came and stole packages of your porch then walked to the next house and did the same that would all be part of one activity. It doesn't make sense to only include the time when the object is in the zone because you lose context for that objects activity.

> There should be a configurable cooldown that I could set to 5 seconds or something low or be able to force all events to also be of a zone before aggregating them together.

There is a cool down, I suppose it could be made configurable but if it's too low you'll find times where objects are in and out of frame (like unloading a car) to be put into separate review items

**Reply by johnmarksilly** [reply]
That is obviously the use-case and is the preferred way of handling events, but that's in a perfect world where only those events are the ones that are captured.

In the real world, that happens much less frequently than the common scenario; packages or people arrive, do their thing, and leave.

In any case, the documentation should be revised to be very specific about that setting and potentially show a sequence diagram. The `required_zones` field isn't descriptive enough because in the past, for events, that meant no event would be created without it occurring within the zone.

> There is a cool down, I suppose it could be made configurable but if it's too low you'll find times where objects are in and out of frame (like unloading a car) to be put into separate review items

I think I would prefer the old event system to the review system because of this exact flaw. I like the idea of bundling the events together and I think it provides the best UX (even bundling events across cameras together), but in its current state, it is less than ideal. The only way it works is if a model is trained to correlate labels across events.

**Reply by NickM-27** [reply]
> In the real world, that happens much less frequently than the common scenario; packages or people arrive, do their thing, and leave.

We have not received any feedback like this and even in my case living on a busy street I don't have this issue so I would say it is not that common. 

> I think I would prefer the old event system to the review system because of this exact flaw. I like the idea of bundling the events together and I think it provides the best UX (even bundling events across cameras together), but in its current state, it is less than ideal. 

The explore view pretty much covers that in 0.15, I don't foresee any major changes happening to the review system. I don't think it would be that difficult to have some logic that understands when an alert causing object is gone and end the current review item and immediately start a new one, but that is just more complicated and not something that anymore reported during the beta or release thus far. 

> The only way it works is if a model is trained to correlate labels across events.

Not sure what you mean, an "event" (tracked object) is the same throughout the time that object is tracked.

**Comment by johnmarksilly** [comment]
First off, holy shit… I’ve never even clicked on the explore view. This is exactly what I was thinking. I’m so sorry.

Second this is all anecdotal right? The review system is still pretty young so either way it would be difficult to understand usage.

So, let me demonstrate this issue right here:

I have an event right now in my Alerts from a car arriving on my driveway (wife came home). This occurred at 7:10 PM last night. I assume because it is stationary and still on my property the event continues. All night, cars have been added to this event. I think there is a total of 6 cars listed in the review item. My wife left our house in the same car at 7:15 AM and it is in the exact same review item! That’s 12 hours! This should not have kept going that long. 

￼

**Reply by NickM-27** [reply]
> Second this is all anecdotal right? The review system is still pretty young so either way it would be difficult to understand usage.

we spent 8 months developing the new UI throughout which we had ~20 users using the dev images and giving feedback and also 4 months of that was a beta period where we had ~ 5000 users using the beta many of which gave feedback (multiple discussions with 1000s of comments). Given the issues that were caught during this period and the immense feedback that we have received, I disagree that its usage is difficult to understand. 

> I have an event right now in my Alerts from a car arriving on my driveway (wife came home). This occurred at 7:10 PM last night. I assume because it is stationary and still on my property the event continues. All night, cars have been added to this event. I think there is a total of 6 cars listed in the review item. My wife left our house in the same car at 7:15 AM and it is in the exact same review item! That’s 12 hours! This should not have kept going that long.

stationary objects will not keep a review item going, as they are only periods of activity. Sounds like something is wrong with the config or some other issue is occurring.

**Reply by johnmarksilly** [reply]
I’m feeling a bit confused about the review system. I’m not criticizing it, I just want to understand how it works. I also think the alerts should be shorter. Maybe I should have started with a more friendly message. Looking back it looks a little combative.

This is my config for that camera:
```
  southwest:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/southwest
          roles:
            - record
            - detect
    motion:
      threshold: 35
      mask:
        - 0.834,0.936,0.835,0.976,0.992,0.98,0.991,0.936
        - 0,0.228,0.1,0.224,0.193,0.169,0.383,0.093,0.465,0.082,0.461,0.138,0.657,0.154,0.773,0.177,0.927,0.223,1,0.248,1,0,0,0
      contour_area: 10
      improve_contrast: true
    zones:
      property:
        coordinates: 
          0,0.555,0.076,0.458,0.154,0.404,0.24,0.386,0.469,0.406,0.719,0.421,0.939,0.439,1,0.44,1,1,0,1
        inertia: 3
        loitering_time: 0
      property_edge:
        coordinates: 
          0,0.456,0.068,0.392,0.119,0.366,0.185,0.33,0.256,0.325,0.462,0.318,0.763,0.339,0.981,0.384,1,0.404,1,0.44,0.258,0.387,0.158,0.404,0.071,0.463,0,0.554
        inertia: 10
        loitering_time: 0
    review:
      alerts:
        required_zones: property
```

I don't think it is anything out of the ordinary. Does the review item continue to aggregate based solely on motion? I think it has to be a bug because on that particular camera, there were probably 30 more car detections that I can see on that camera over the same time period that went into the event.
