### DISCUSSION TITLE
[Config Support]: Excluding a camera from alerts not working

### DISCUSSION THREAD

**Discussion by skycryer** [blakeblackshear/frigate#14997] [Config Support]
### Describe the problem you are having

I try to config 2 cameras to detect persons (baby beds) but I do not want alerts only detections maybe. If not possible then disable both.

I added the code as shown on the website . I saw the post with that code also but they seem to work. Not sure why it still shows alert for me for that cameras where I added the exclude code.

### Version

0.14.1

### Frigate config file

```yaml
indoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.73/stream2
          roles:
            - detect
        - path: rtsp://192.168.1.2:8554/indoor
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

    objects:
      track:
        - person

    record:
      enabled: true
      retain:
        days: 2
        mode: motion

    review:
      detections:
        labels: []
```

### Relevant Frigate log output

```shell
No log available
```

### Relevant go2rtc log output

```shell
No log available
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
not available
```

### Object Detector

Coral
