### DISCUSSION TITLE
Audio only detection camera (aka babyphone)

### DISCUSSION THREAD

**Discussion by ministryofsillywalks** [blakeblackshear/frigate#15007] [Ask A Question]
I have a wifi camera setup to monitor or baby from a different room. All completely offline and on separate vlan.
Now I wanted to add this camera to frigate to monitor it here but the way I understand it every camera added to frigate runs motion detection, which in this case is far from ideal, as first of all I don't want motion detection and secondly the camera doesn't provide a substream and thus I would run motion detection on 1080p.
Is there any way to disable motion detection completely or what would be the best course of action to minimize the impact on the systems resources?
I just want an alert on audio detected (like crying) and want to be able to view the camera via the web interface.

**Comment by NickM-27** [comment]
you can provide a blank stream to the detect role, and do the rest like normal.

**Reply by ministryofsillywalks** [reply]
How and where so I create a blank stream?

**Reply by hawkeye217** [reply]
One way would be to download or even just create a blank/black video and loop it with ffmpeg arguments in your config.

```
cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/black-video.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
```
