### DISCUSSION TITLE
[Config Support]: docker compose run wont start - fails with "environment_vars: Value error, too many values to unpack (expected 2)" in the config validation errors

### DISCUSSION THREAD

**Discussion by klaus7269** [blakeblackshear/frigate#15003] [Config Support]
### Describe the problem you are having

getting a constant validation error in the starting of the docker container

frigate  | 2024-11-15 14:44:41.238302784  [2024-11-15 14:44:41] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-11-15 14:44:41.322487471  *************************************************************
frigate  | 2024-11-15 14:44:41.322491804  *************************************************************
frigate  | 2024-11-15 14:44:41.322494563  ***    Your config file is not valid!                     ***
frigate  | 2024-11-15 14:44:41.322498693  ***    Please check the docs at                           ***
frigate  | 2024-11-15 14:44:41.322499804  ***    https://docs.frigate.video/configuration/          ***
frigate  | 2024-11-15 14:44:41.322501397  *************************************************************
frigate  | 2024-11-15 14:44:41.322502471  *************************************************************
frigate  | 2024-11-15 14:44:41.322504471  ***    Config Validation Errors                           ***
frigate  | 2024-11-15 14:44:41.322521082  *************************************************************
frigate  | 2024-11-15 14:44:41.322522267  environment_vars: Value error, too many values to unpack (expected 2)
frigate  | 2024-11-15 14:44:41.322523286  *************************************************************
frigate  | 2024-11-15 14:44:41.322524249  ***    End Config Validation Errors                       ***
frigate  | 2024-11-15 14:44:41.322525230  *************************************************************
frigate  | 2024-11-15 14:44:41.835109823  [INFO] Service Frigate exited with code 1 (by signal 0)

### Version

15.0

### Frigate config file

```yaml
owner@raspberrypi:~/frigate $ cat config/config.yml
mqtt:
  enabled: true
  host: 192.168.1.76
  port: 1883
  topic_prefix: frigate
  user: mqtt_user
  password: Internet123!!
  stats_interval: 120  # Increased to reduce MQTT traffic

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8_cache/ssd_mobilenet_v1.hef

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: ssd

#  coral:
#    type: edgetpu
#    device: usb

#  deepstack:
#    api_url: http://192.168.1.30:32168/v1/vision/detection
#    type: deepstack
#    api_timeout: 35 # seconds

semantic_search:
  enabled: true
  model_size: small
  reindex: false

go2rtc:
  streams:
    CamHBDrive:
      - rtsp://admin:xxx@192.168.1.115:554/h265Preview_01_main
      - ffmpeg:CamHBDrive#video=h264
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
# stream 0:
#   codec: MPEG-H Part 2/HEVC (H.265) (hevc)
#   type: video
#   video resolution: 3840x2160
#   frame rate: 15
# stream 1:
#   codec: MPEG AAC Audio (mp4a)
#   type: audio
#   channels: stereo
#   sample rate: 32000 Hz
#   bits pers sample: 32
    CamHBDrive_sub:
      - rtsp://admin:xxx@192.168.1.115:554/h264Preview_01_sub
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
# stream 0:
#   codec: H264 - MPEG-4 AVC (part 10) (h264)
#   type: video
#   video resolution: 896x512
#   frame rate: 15
# stream 1:
#   codec: MPEG AAC Audio (mp4a)
#   type: audio
#   channels: stereo
#   sample rate: 32000 Hz
#   bits pers sample: 32
    CamHBDriveZoom:
      - rtsp://admin:xxx@192.168.1.115:554/h265Preview_02_main
      - ffmpeg:CamHBDriveZoom#video=h264
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    CamHBDriveZoom_sub:
      - rtsp://admin:xxx@192.168.1.115:554/h264Preview_02_sub
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    CamSLDrive:
      - rtsp://admin:xxx@90.217.77.120:554/h265Preview_01_main
      - ffmpeg:CamSLDrive#video=h264
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    CamSLDrive_sub:
      - rtsp://admin:xxx@90.217.77.120:554/h264Preview_01_sub
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
#    CamSLGarden:
#      - rtsp://admin:xxx@90.217.77.120:553/h265Preview_01_main
#      - ffmpeg:CamSLGarden#video=h264
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
#    CamSLGarden_sub:
#      - rtsp://admin:xxx@90.217.77.120:553/h264Preview_01_sub
#    CamSLGardenZoom:
#      - rtsp://admin:xxx@90.217.77.120:553/h265Preview_02_main
#      - ffmpeg:CamSLGarden#video=h264
#      - "ffmpeg:name_your_rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
#    CamSLGardenZoom_sub:
#      - rtsp://admin:xxx@90.217.77.120:553/h264Preview_02_sub

#    GardenCam:     rtsp://admin:xxx@192.168.1.94:554/1080p
#    GardenCam_sub: rtsp://admin:xxx@192.168.1.94:554/360p
#    GarageCam:
#      - rtsp://garage:xxx@192.168.1.185:554/live

logger:
  default: info
  logs:
    frigate.mqtt: warning # debug

objects:
  track:
    - person
    - car
    - dog
    - license-plate
    - cat

review:
  detections:
    labels:
      - cat
      - dog
      - license-plate
  alerts:
    labels:
      - person

motion:
  enabled: true
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 100
  improve_contrast: false
  mqtt_off_delay: 30

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

cameras:
  CAMHBDrive:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CamHBDrive # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-rpi-64-h265
        - path: rtsp://127.0.0.1:8554/CamHBDrive_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - audio # <- only necessary if audio detection is enabled
            - detect
          hwaccel_args: preset-rpi-64-h264
    best_image_timeout: 60
    detect:
      width: 896
      height: 512
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    # Optional: Live stream configuration for WebUI
    # NOTE: Can be overridden at the camera level
    live:
      # Optional: Set the height of the live stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
      height: 720
      # Optional: Set the encode quality of the live stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    mqtt:
      quality: 100
      height: 500
    objects:
      filters:
        car:
          mask:
            - 0.378,0.287,0.572,0.284,0.574,0.452,0.378,0.462
            - 0.735,0.195,0.74,0.509,0.92,0.492,0.896,0.172
            - 0.594,0.507,0.876,0.412,1,1,0.21,1,0.221,0.683,0.384,0.561
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: false
      mask:
        0.115,0.293,0.872,0.275,0.888,0.274,0.912,0.258,0.913,0.261,1,0.264,0.99,0.009,0.002,0.001,0,0.842,0.016,0.841,0.082,0.839,0.119,0.829
    zones:
      Motion:
        coordinates: 0.115,0.311,0.856,0.296,0.866,0.822,0.123,0.832
        loitering_time: 0
    review:
      alerts:
        required_zones: Motion
      detections:
        required_zones: Motion
  CamHBDriveZoom:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CamHBDriveZoom # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-rpi-64-h265
        - path: rtsp://127.0.0.1:8554/CamHBDriveZoom_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - audio # <- only necessary if audio detection is enabled
            - detect
          hwaccel_args: preset-rpi-64-h264
    # Optional: Live stream configuration for WebUI
    # NOTE: Can be overridden at the camera level
    live:
      # Optional: Set the height of the live stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
      height: 720
      # Optional: Set the encode quality of the live stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8
    best_image_timeout: 60
    detect:
      width: 896
      height: 512
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    review:
      alerts:
        required_zones: ZoomZone
      detections:
        required_zones: ZoomZone
    objects:
      track:
        - person
        - car
        - license-plate
        - dog
      filters:
        car:
          mask:
            - 0.364,0.203,0.633,0.181,0.638,0.414,0.37,0.418
            - 0.681,0.389,1,0.407,0.987,1,0.016,0.969,0.093,0.566
            - 0.872,0.141,0.997,0.134,0.996,0.452,0.836,0.462
    mqtt:
      quality: 100
      height: 500
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: 'false'
    zones:
      ZoomZone:
        coordinates: 0,0.249,0,0.867,1,0.829,1,0.172
        loitering_time: 0
  CamSLDrive:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CamSLDrive # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-rpi-64-h265
        - path: rtsp://127.0.0.1:8554/CamSLDrive_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - audio # <- only necessary if audio detection is enabled
            - detect
          hwaccel_args: preset-rpi-64-h264
    # Optional: Live stream configuration for WebUI
    # NOTE: Can be overridden at the camera level
    live:
      # Optional: Set the height of the live stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
      height: 720
      # Optional: Set the encode quality of the live stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8
    best_image_timeout: 60
    detect:
      width: 640
      height: 360
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 100
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    review:
      alerts:
        required_zones: ZoomZone2
      detections:
        required_zones: ZoomZone2
    objects:
      track:
        - person
        - car
        - license-plate
        - dog
      filters:
        car: {}
    mqtt:
      quality: 100
      height: 500
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: 'false'
      mask: 0.66,0.069,0.662,0.172,0.84,0.184,0.843,0.069
    zones:
      ZoomZone2:
        coordinates:
          0.033,0.171,0.048,0.891,0.898,0.906,0.901,0.178,0.842,0.184,0.658,0.174,0.654,0.171
        loitering_time: 0
        inertia: 3

  CamSLGarden:
    enabled: false
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8553/CamSLGarden # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-rpi-64-h265
        - path: rtsp://127.0.0.1:8553/CamSLGarden_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - audio # <- only necessary if audio detection is enabled
            - detect
          hwaccel_args: preset-rpi-64-h264
    best_image_timeout: 60
    detect:
      width: 896
      height: 512
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    # Optional: Live stream configuration for WebUI
    # NOTE: Can be overridden at the camera level
    live:
      # Optional: Set the height of the live stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
      height: 720
      # Optional: Set the encode quality of the live stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    mqtt:
      quality: 100
      height: 500
    objects:
      filters:
        car:
          mask:
            - 0.378,0.287,0.572,0.284,0.574,0.452,0.378,0.462
            - 0.735,0.195,0.74,0.509,0.92,0.492,0.896,0.172
            - 0.594,0.507,0.876,0.412,1,1,0.21,1,0.221,0.683,0.384,0.561
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: false
      mask:
        0.115,0.293,0.872,0.275,0.888,0.274,0.912,0.258,0.913,0.261,1,0.264,0.99,0.009,0.002,0.001,0,0.842,0.016,0.841,0.082,0.839,0.119,0.829
    zones:
      Motion:
        coordinates: 0.115,0.311,0.856,0.296,0.866,0.822,0.123,0.832
        loitering_time: 0
    review:
      alerts:
        required_zones: Motion
      detections:
        required_zones: Motion

#  GarageCam:
#    enabled: false
#    ffmpeg:
#      output_args:
#        record: preset-record-generic-audio-copy
#      inputs:
#        - path: rtsp://127.0.0.1:8554/GarageCam # <--- the name here must match the name of the camera in restream
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#            - record
#          hwaccel_args: preset-rpi-64-h264
#    best_image_timeout: 60
#    detect:
#      width: 640
#      height: 360
#      fps: 1
#      stationary:
#        max_frames:
#          objects:
#            car: 150
#    motion:
#      mask: 0.905,0.06,0.847,0.503,1,0.778,1,0.054
#    objects:
#      filters:
#        car:
#          mask: 0.066,0.466,0.824,0.482,0.993,0.806,0.984,0.974,0.007,0.993,0.004,0.655
#  GardenCam:
#    enabled: false
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.1.94:8554/1080p
#          input_args: -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay
#            -rtsp_transport tcp
#          roles:
#            - record
#          hwaccel_args: preset-rpi-64-h264 # for H264 streams
#        - path: rtsp://192.168.1.94:8554/360p
#          input_args: -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay
#            -hide_banner -rtsp_transport tcp
#          roles:
#            - detect
#          hwaccel_args: preset-rpi-64-h264 # for H264 streams
#    best_image_timeout: 60
#    detect:
#      width: 480
#      height: 360
#      fps: 1
#    # Optional: Live stream configuration for WebUI
#    # NOTE: Can be overridden at the camera level
#    live:
#      # Optional: Set the height of the live stream. (default: 720)
#      # This must be less than or equal to the height of the detect stream. Lower resolutions
#      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
#      height: 720
#      # Optional: Set the encode quality of the live stream (default: shown below)
#      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#      quality: 8
#    objects:
#      track:
#        - person
#        - car
#        - license-plate
#        - dog
#      filters:
#        car: {}
#    mqtt:
#      quality: 100
#      height: 500
#    motion:
#      threshold: 30
#      contour_area: 10
#      improve_contrast: 'false'
#        inertia: 3
version: 0.15-0
```

### Relevant Frigate log output

```shell
owner@raspberrypi:~/frigate $ docker compose up
WARN[0000] /home/owner/frigate/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/0
 ✔ Container frigate  Created                                                                                                                 0.0s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | 2024-11-15 14:50:51.824717379  [INFO] Preparing new go2rtc config...
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-11-15 14:50:51.831114304  [INFO] Starting NGINX...
frigate  | 2024-11-15 14:50:51.834196165  [INFO] Preparing Frigate...
frigate  | 2024-11-15 14:50:51.842382057  [INFO] Starting Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2024-11-15 14:50:52.033781043  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-11-15 14:50:52.298787581  127.0.0.1 - - [15/Nov/2024:14:50:52 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-11-15 14:50:52.358966468  [INFO] Starting go2rtc...
frigate  | 2024-11-15 14:50:52.438917298  14:50:52.438 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2
frigate  | 2024-11-15 14:50:52.438942298  14:50:52.438 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-11-15 14:50:52.439728911  14:50:52.439 INF [api] listen addr=:1984
frigate  | 2024-11-15 14:50:52.440145134  14:50:52.440 INF [rtsp] listen addr=:8554
frigate  | 2024-11-15 14:50:52.440557635  14:50:52.440 INF [webrtc] listen addr=:8555/tcp
frigate  | 2024-11-15 14:50:54.359052122  2024/11/15 14:50:54 [error] 158#158: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.1, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "nickcooper123cams.zapto.org:5000"
frigate  | 2024-11-15 14:50:54.359078807  2024/11/15 14:50:54 [error] 158#158: *2 auth request unexpected status: 502 while sending to client, client: 192.168.1.1, server: , request: "GET /api/stats HTTP/1.1", host: "nickcooper123cams.zapto.org:5000"
frigate  | 2024-11-15 14:50:54.671900108  [2024-11-15 14:50:54] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-11-15 14:50:54.758401789  [2024-11-15 14:50:54] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-11-15 14:50:54.842964502  *************************************************************
frigate  | 2024-11-15 14:50:54.842967965  *************************************************************
frigate  | 2024-11-15 14:50:54.842970020  ***    Your config file is not valid!                     ***
frigate  | 2024-11-15 14:50:54.842973724  ***    Please check the docs at                           ***
frigate  | 2024-11-15 14:50:54.842974835  ***    https://docs.frigate.video/configuration/          ***
frigate  | 2024-11-15 14:50:54.842976391  *************************************************************
frigate  | 2024-11-15 14:50:54.842977483  *************************************************************
frigate  | 2024-11-15 14:50:54.842992557  ***    Config Validation Errors                           ***
frigate  | 2024-11-15 14:50:54.842993761  *************************************************************
frigate  | 2024-11-15 14:50:54.842994817  environment_vars: Value error, too many values to unpack (expected 2)
frigate  | 2024-11-15 14:50:54.843050743  *************************************************************
frigate  | 2024-11-15 14:50:54.843052502  ***    End Config Validation Errors                       ***
frigate  | 2024-11-15 14:50:54.843053484  *************************************************************
frigate  | 2024-11-15 14:50:55.358777729  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2024-11-15 14:50:55.368193459  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | 2024-11-15 14:50:55.368974757  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service certsync successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service certsync-log: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | s6-rc: info: service certsync-log successfully stopped
frigate  | 2024-11-15 14:50:55.430653834  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | 2024-11-15 14:50:55.434514418  exit with signal: terminated
frigate  | 2024-11-15 14:50:55.438344873  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Relevant go2rtc log output

```shell
does not create any
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1-h8l
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev/hailo0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config:/config
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_MQTT_USER: "xxxxxxxxxx"
      FRIGATE_MQTT_PASSWORD: "xxxxxxxxxxx"
```

### Object Detector

Other
