### DISCUSSION TITLE
[Config Support]: Issue with variables

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#15013] [Config Support]
### Describe the problem you are having

So when I add the section below for envirometn vars

```
environment_vars:
  FRIGATE_RTSP_USER: Username
  FRIGATE_RTSP_PASS: pass1234
```

This works fine and the system can reset. The problem I run into is when I go to use these vars in an RTSP String IE

```
  Back_Yard:
    ui:
      order: 1

    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASS}@192.168.86.218/Preview_01_main
          roles:
            - record
            
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASS}@192.168.86.218/Preview_01_sub
          roles:
            - detect
```

My system wont boot. Am I not using this right ?

### Version

0.14.1

### Frigate config file

```yaml
environment_vars:
  FRIGATE_RTSP_USER: Username
  FRIGATE_RTSP_PASS: pass1234

cameras:

  Back_Yard:
    ui:
      order: 1

    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASS}@192.168.86.218/Preview_01_main
          roles:
            - record
            
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASS}@192.168.86.218/Preview_01_sub
          roles:
            - detect
```
```


### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

TensorRT
