### DISCUSSION TITLE
[Support]: camera preview resolution changes when motion is detected

### DISCUSSION THREAD

**Discussion by kanemari** [blakeblackshear/frigate#15017] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have 6 cameras streaming in the live screen view. They have been the same cameras for at least 6 months. Recently, 2 of them (both Wyze v3) have started flickering between a 1920x1080 preview and what appears to be a narrower distorted resolution, something close to 1440x1080. The resolution change only happens when motion is detected. this happens on PC browsers and the android app.

If I change to a different browser tab and switch back to Frigate, the previews refresh are the correct size momentarily, and if one of those 2 cameras is in the process of detecting motion it will switch to the narrower resolution about 2 seconds after refreshing.

I have checked the rtsp feed, it displays normally.

### Steps to reproduce

1.Wait for motion to be detected
2.Watch preview resolution change
3.
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.x
  user: frigate
  password: x

database:
  path: /config/frigate.db

go2rtc:
  streams:
    #15_mobile_1:
       # - ffmpeg:rtsp://campan:x@192.168.20.x:8554/unicast#video=copy#audio=opus#audio=aac
       # - rtsp://192.168.1.x:38554/15-edith-mobile-1
      #- rtsp://campan:x@192.168.20.x:8554/unicast
      #- ffmpeg:15_mobile_1#audio=aac
    #15_mobile_2:
       # - ffmpeg:rtsp://campan:x@192.168.20.x:8554/unicast#video=copy#audio=opus#audio=aac
       # - rtsp://192.168.1.x:38554/15-edith-mobile-2
      #- rtsp://campan:x@192.168.20.x:8554/unicast
      #- ffmpeg:15_mobile_2#audio=aac
    #15_mobile_4:
       # - ffmpeg:rtsp://campan:x@192.168.20.x:8554/unicast#video=copy#audio=opus#audio=aac
       # - rtsp://192.168.1.x:38554/15-edith-mobile-4
      #- rtsp://campan:x@192.168.20.x:8554/1080p?mp4
      #- ffmpeg:15_mobile_4#audio=opus#audio=copy
    15_garage:
       # - ffmpeg:rtsp://campan:x@192.168.20.x:8554/unicast#video=copy#audio=opus#audio=aac
       # - rtsp://192.168.1.x:38554/15-edith-garage
       # - webrtc:ws://192.168.20.x:1984/api/ws?src=1080p
      - rtsp://campan:x@192.168.20.x:8554/1080p?mp4
      - ffmpeg:15_garage#audio=opus#audio=copy
    15a_garage:
    #  - ffmpeg:rtsp://campan:x@192.168.20.x:8554/unicast#video=copy#audio=opus#audio=aac
    #  - rtsp://192.168.1.x:38554/15a-edith-garage
      - rtsp://campan:x@192.168.20.x:8554/1080p?mp4
      - ffmpeg:15a_garage#audio=opus
    15_driveway:
    #  - ffmpeg:rtsp://ringcam:x@192.168.1.x:38554/54e019b76dd5_live#video=copy#audio=opus#audio=copy
      - rtsp://ringcam:x@192.168.20.x:38555/54e019b76dd5_live
      - ffmpeg:15_driveway#audio=aac
    15_backyard:
    #  - ffmpeg:rtsp://ringcam:x@192.168.1.x:38554/9c7613b33f56_live#video=copy#audio=opus#audio=copy
      - rtsp://ringcam:x@192.168.20.x:38555/9c7613b33f56_live
      - ffmpeg:15_backyard#audio=aac
    15_intercom:
    #  - ffmpeg:rtsp://admin:x@192.168.1.x/Streaming/Channels/101#video=copy#audio=opus#audio=aac
      - rtsp://admin:x@192.168.20.x/Streaming/Channels/101
      - ffmpeg:15_intercom#audio=aac
    15a_intercom:
    #  - ffmpeg:rtsp://admin:x@192.168.1.x/Streaming/Channels/101#video=copy#audio=opus#audio=aac
      - rtsp://admin:x@192.168.20.x/Streaming/Channels/101
      - ffmpeg:15a_intercom#audio=aac
  webrtc:
    candidates:
      - 192.168.1.x:8555
      - 192.168.20.x:8555
      - stun:8555

cameras:
  15_mobile_1:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_mobile_1
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 1
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        #required_zones: []
        retain:
          default: 7
          objects:
            person: 14
  15_mobile_2:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_mobile_2
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 1
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        #required_zones: []
        retain:
          default: 7
          objects:
            person: 14
    motion:
      threshold: 35
      contour_area: 30
      improve_contrast: 'true'
  15_mobile_4:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_mobile_4
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 360
      fps: 10
    mqtt:
      enabled: false
      timestamp: true
      bounding_box: true
      crop: true
      height: 360
      required_zones: []
    snapshots:
      enabled: false
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 7
    record:
      enabled: true
      retain:
        days: 2
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      #events:
      #  pre_capture: 2
      #  post_capture: 4
      #  retain:
      #    default: 7
      #    objects:
      #      person: 14
    #motion:
      #mask:
        #- 0,0,1280,0,1280,388,1036,376,900,385,709,379,563,375,486,370,412,345,340,342,255,315,172,320,0,298
  15_driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_driveway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 1
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        #required_zones: []
        retain:
          default: 7
          objects:
            person: 14
    objects:
    # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
        - dog
        - cat
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below
      #mask: 0,0,1000,0,1000,200,0,200
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 18000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 200000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.4
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
          # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
          # Checks based on the bottom center of the bounding box of the object
          #mask: 0,1080,570,1080,570,625,0,625
          #mask:
            #- 243,1080,657,1080,658,592,236,593
        car:
          mask:
            - 1277,0,1920,0,1920,518,1732,311,1466,138
        dog:
          mask:
            - 1116,493,1116,1080,417,1080,422,502
            - 878,0,931,101,992,187,1047,265,1075,418,984,611,831,600,767,636,783,720,644,720,664,620,605,620,461,593,424,506,376,417,376,290,440,208,459,91,523,21,630,0
    motion:
      mask:
        - 1920,0,1920,496,1732,321,1736,295,1488,133,1503,100,1370,62,1361,40,1297,24,1293,0,927,0,653,41,550,78,567,106,470,140,473,175,363,229,359,260,0,429,0,0
    zones:
      walkable:
        coordinates: 0,1080,0,913,506,305,609,209,817,167,1318,174,1824,1080
    review:
      alerts:
        required_zones:
          - walkable
  15_backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_backyard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 1
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        #required_zones: []
        retain:
          default: 7
          objects:
            person: 14
    objects:
    # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - dog
        - cat
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below
      #mask: 0,0,1000,0,1000,200,0,200
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 18000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 150000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.4
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.2
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
          # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
          # Checks based on the bottom center of the bounding box of the object
          #mask: 179,887,537,991,630,684,272,612
    motion:
      mask:
        - 1920,0,1920,523,1410,72,1290,24,502,37,446,53,366,147,115,574,0,737,0,0
  15_garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_garage
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://campan:x@192.168.20.x:8554/1080p?mp4
          input_args: preset-rtsp-generic
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 1
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        #required_zones: []
        retain:
          default: 7
          objects:
            person: 14
    motion:
      mask:
        - 0,684,0,0,1920,0,1920,454,1391,180,625,180
  15a_garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15a_garage
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://campan:x@192.168.20.x:8554/1080p?mp4
          input_args: preset-rtsp-generic
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 1
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        #required_zones: []
        retain:
          default: 7
          objects:
            person: 14
    motion:
      mask:
        - 0,403,0,0,1920,0,1920,563,1276,131,534,136
  15_intercom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_intercom
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://admin:x@192.168.20.x/Streaming/Channels/101
          input_args: preset-rtsp-generic
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 14
    record:
      enabled: true
      retain:
        days: 2
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        retain:
          default: 7
          objects:
            person: 14
    objects:
    # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          mask:
            - 112,639,224,630,226,526,324,486,402,331,345,221,292,146,189,23,30,0,0,55,0,381,0,500,74,535

    motion:
      mask:
        - 0,0,1280,0,1280,385,1145,383,967,388,900,385,596,355,563,375,486,370,412,345,360,366,270,370,194,378,172,320,0,298

      threshold: 40
      contour_area: 25
      improve_contrast: 'true'
  15a_intercom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15a_intercom
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://admin:x@192.168.20.x/Streaming/Channels/101
          input_args: preset-rtsp-generic
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 720
      required_zones: []
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #height: 175
      #required_zones: []
      retain:
        default: 7
        objects:
          person: 7
    record:
      enabled: true
      retain:
        days: 2
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      events:
        pre_capture: 2
        post_capture: 4
        retain:
          default: 7
          objects:
            person: 14
    objects:
    # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          mask: 
            0.686,0,0.727,0.14,0.775,0.26,0.818,0.368,0.84,0.581,0.745,0.89,0.652,0.878,0.599,0.883,0.612,1,0.503,1,0.51,0.875,0.451,0.879,0.369,0.851,0.331,0.703,0.294,0.579,0.294,0.403,0.344,0.289,0.359,0.126,0.409,0.029,0.492,0
    motion:
      mask:
        - 0,0,1280,0,1280,388,1036,376,900,385,709,379,563,375,486,370,412,345,340,342,255,315,172,320,0,298
        #- 878,0,931,101,992,187,1047,265,1075,418,984,611,831,600,767,636,783,720,644,720,664,620,605,620,461,593,424,506,376,417,376,290,440,208,459,91,523,21,630,0

      threshold: 35
      contour_area: 15
      improve_contrast: 'true'
ffmpeg:
  #global_args: -hide_banner -loglevel warning
  global_args: -loglevel warning
  #hwaccel_args: preset-vaapi
    #- -hwaccel
    #- qsv
    #- -qsv_device /dev/dri/renderD128
    #- -c:v h264_v4l2m2m
  input_args: preset-rtsp-restream-low-latency
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    #detect: -vf hwdownload,format=nv12 -f rawvideo -pix_fmt yuvj420p
    #detect: -threads 1 -f rawvideo -pix_fmt yuv420p
    detect: -avioflags direct -threads 1 -fps_mode vfr -muxdelay 0 -flags low_delay
      -flush_packets 1 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac
    #record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 8000 -c:a aac
    #clips: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    #rtmp: -c copy -f flv
    #rtmp: -c:v copy -ar 8000 -c:a aac -f flv
birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  restream: true
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb
    #num_threads: 3
timestamp_style:
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
    #- mouse
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  #mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 10000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 250000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.4
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 1.2
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.65
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200

# ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  # use_experimental: false
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
using as Home Assistant add-on - no custom settings
```

### Relevant Frigate log output

```shell
no relevant errors for this camera in the logs
```

### Relevant go2rtc log output

```shell
no relevant errors for this camera in the logs
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Wyze v3

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d0cb4acf-e76c-40c0-86f7-6849f25cb3e1)
![image](https://github.com/user-attachments/assets/f64d5eba-9f74-48ea-a64d-2280630ea6f9)
![image](https://github.com/user-attachments/assets/4208297c-d1a4-4b92-9edd-13a02232cc37)

### Any other information that may be helpful

https://github.com/user-attachments/assets/bdb9f7ce-c6d8-4e86-8885-fdf23530fd10
