### DISCUSSION TITLE
Motion detection triggered in snowfall/

### DISCUSSION THREAD

**Discussion by 210392** [blakeblackshear/frigate#15015] [Ask A Question]
Is it possible to configure the configuration file so that the frigate does not detect movement during snowfall?
My current config file
```
#yaml-language-server: $schema=http://ccab4aaf-frigate:5000/api/config/schema.json

mqtt:
  host: 888.888.8.888
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: false

#Global Detect Settings
detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2

detect:
  height: 640
  width: 720
  fps: 5
  min_initialized: 10
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 20
    max_frames:
      default: 300
      objects:
        person: 100
        car: 150

#Global Object Settings
objects:
  track:
    - person
    - car
    - motorcycle
  filters:
    person:
      min_area: 5000
      max_area: 20000
    car:
      min_area: 8000
      max_area: 35000

#Global Record Settings
record:
  enabled: true
  retain:
    days: 7
    mode: active_objects

motion:
  threshold: 60
  lightning_threshold: 0.6
  contour_area: 70
  frame_height: 50
  improve_contrast: true
  mqtt_off_delay: 2

#Cameras Settings
cameras:
#Camera Vorota-------------------------------------------------------------------------------
  cam_Vorota:
    ffmpeg:
      inputs:
        - path: rtsp://888.888.8.888:554/user=8888_password=8888_channel=0_stream=1 
          roles:
            - detect
        - path: rtsp://888.888.8.888:554/user=8888_password=8888_channel=0_stream=0
          roles:
            - record
    #
    zones:
      Vorota:
        coordinates: 
          1,1,0.002,0.997,0,1,0,0.612,0.18,0.565,0.519,0.565,0.723,0.563,0.781,0.598,0.489,0.625,0.495,0.78,0.65,0.844,0.781,0.903,1,0.908,1,0.167,0.828,0.176,0.768,0.185,0.785,0.284,0.707,0.322,0.594,0.314,0.559,0.275,0.605,0.215,0.765,0.202,0.764,0.183,0.616,0.203,0.546,0.225,0.366,0.273,0,0.365,0.12,0.433,0.234,0.499,1,0.495
        loitering_time: 2
        inertia: 3
        objects: person
      Vorota2:
        coordinates: 0.564,0.273,0.607,0.22,0.77,0.207,0.776,0.287,0.71,0.317,0.586,0.311
        inertia: 3
        loitering_time: 2
        objects: person
      Vorota3:
        coordinates: 0.491,0.627,0.492,0.78,0.779,0.9,0.997,0.906,0.994,0.795,0.807,0.728,0.781,0.602
        inertia: 3
        loitering_time: 2
        objects: person
    review:
      alerts: {}
      detections: {}
    motion:
      mask: 
        0,0.363,0,0.609,0,0.362,0.553,0.22,0.598,0.206,0.675,0.198,0.814,0.177,1,0.165,1,0,-0.001,0,-0.001,0,0,0.611,0.179,0.564,0.73,0.558,0.783,0.598,0.811,0.73,1,0.795,1,0.495,0.231,0.5
#Camera Dvor-------------------------------------------------------------------------------
  cam_Dvor:
    ffmpeg:
      inputs:
        - path: rtsp://888.888.8.888:554/user=8888_password=8888_channel=0_stream=1
          roles:
            - detect
        - path: rtsp://888.888.8.888:554/user=8888_password=8888_channel=0_stream=0
          roles:
            - record
#
    zones:
      Dvor_1:
        coordinates: 0.996,0.495,0,0.501,0,0.131,0.311,0.097,0.661,0.077,0.81,0.12,0.994,0.194
        inertia: 3
        loitering_time: 2
        objects: person
      Dvor_1_2:
        coordinates: 
          1,0.881,0.871,0.881,0.867,1,0.401,1,0.22,0.628,0.193,0.631,0.186,1,0,1,0,0.6,0.286,0.568,0.368,0.561,0.414,0.57,0.423,0.643,0.463,0.652,0.472,0.566,0.664,0.578,1,0.622
        inertia: 3
        loitering_time: 2
        objects: person
    review: {}
    motion:
      mask:
        - 0.194,1,0.194,0.637,0.223,0.635,0.394,0.997
        - 0.873,1,0.871,0.885,1,0.885,1,1
        - 1,0.618,0.713,0.581,0.56,0.566,0.467,0.561,0.457,0.652,0.426,0.642,0.424,0.563,0.368,0.56,0.234,0.57,0.071,0.586,0,0.597,0,0.597,0,0.503,1,0.499
        - 1,0.191,0.816,0.12,0.667,0.075,0.5,0.085,0.302,0.096,0,0.13,0,0,1,0
#Camera Dvor 2-------------------------------------------------------------------------------
  cam_Dvor_2:
    ffmpeg:
      inputs:
        - path: rtsp://888.888.8.888:554/user=8888_password=8888_channel=0_stream=1
          roles:
            - detect
        - path: rtsp://888.888.8.888:554/user=8888_password=8888_channel=0_stream=0
          roles:
            - record
#
    zones:
      Dvor_2:
        coordinates: 
          -0.001,0.335,0.503,0.081,0.999,0.186,1,0.5,0.004,0.501,0,0.587,0.019,0.579,0.997,0.872,0.999,0.997,0,0.999,0,0.402,0,0.333,-0.003,0.332
        loitering_time: 2
        objects: person
        inertia: 3
    review:
      alerts: {}
    motion:
      mask: 
        0.5,0.081,0.739,0.127,0.833,0.153,0.796,0.501,1,0.5,1,0,0,0,0,0.168,0,0.337,0,0.505,1,0.5,1,0.872,0.022,0.575,0,0.587,0,0.335

semantic_search:
  enabled: false
  reindex: false
  model_size: small
```
![Screenshot_4](https://github.com/user-attachments/assets/ba59e2fa-fc0b-499b-a604-16044863f853)
![Screenshot_2](https://github.com/user-attachments/assets/e5793b7c-1459-40e8-9210-c3395a27c1be)
