### DISCUSSION TITLE
[Config Support]: Getting a better picture on the live dashboard

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#15018] [Ask A Question] [answered]
So I would really like to get a better looking feed on the Live dashboard. I have been reading every where that this means that I have to use the Go2RTC system. You will set up your streams there and then name them. THen in your camera: section of the config you will not refrence those feeds by name by using `rtsp://127.0.0.1:8554/Camera_Name` and then also setting the live.stream_name to tell the live dashboard what one of the named streams you want to use for the live dashboard.

THis is all great and seems to be working kind of as expected.

Question I have is:

If i am understanding this correctly you are streaming to go2rtc then this is being re-streamed to the camera section of the config so basically the stream is being handled twice (Not from the same source but more like waterfall effect) Is this right? I did notice for my 6 cameras (Main & Sub feeds) this added about 5% - 10% CPU (see screen shot below when i changed my config to use go2rtc) usage to my TrueNAS box. I know others use this to re-stream their live feeds to HA or other dashboards like Hubitat. But if you only want to have a better live feed (on demand) on the frigate dashboard is there no way to just capture the main feed and display it instead of re-streaming it or even having the option for main/sub so you can choose? Seems like with go2rtc you are re-streaming all of your streams 24/7 for the use of it maybe 0.2% of the time you might look at the dashboard and need that live feed in high res.

So this is just a long way of asking is there no better way so that the main feed is only loaded on demand when you need it and not running 24/7? Am I understanding how this works wrong?

And seriously how can I buy you a beer Josh ? (AKA donate to the cause for all your efforts) as I know you will probably answer this :)

![000031](https://github.com/user-attachments/assets/9e27eddf-48d2-497a-b73f-95f1ea3f798b)

Example of my config for one camera
```
live:
  stream_name: camera_name
  height: 720
  quality: 8

go2rtc:
  streams:
    Ripleys_Room_Main:    rtsp://user:password@192.168.86.218/Preview_01_main
    Ripleys_Room_Sub:    rtsp://user:password@192.168.86.218/Preview_01_sub


cameras: 
Ripleys_Room:
    ui:
      order: 6

    live:
      stream_name: Ripleys_Room_Main

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Ripleys_Room_Main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Ripleys_Room_Sub
          roles:
            - detect
```
