### DISCUSSION TITLE
[Detector Support]: High GPU usage using onnx & Frigate+ yolonas model, vs tensorRT and yolov7. Why?

### DISCUSSION THREAD

**Discussion by robby-d** [blakeblackshear/frigate#15023] [Detector Support] [answered]
### Describe the problem you are having

Running the newest dev (7fdf42a) on an RTX A4000. I managed to successfully switch to the onnx detector, using my custom Frigate+ model (as a yolonas build). Detection works fine, but am having an issue with high GPU usage.

With tensorrt and the stock yolov7-tiny-416, my inference speed is 2.07ms and GPU usage ranges from 5% to 20% (average around 10%). But with onnx and my custom frigate+ image, inference speed is 6.02ms and GPU usage ranges from in the 35% to 65%. This is with the same cameras, scenes (just stopped one setup, tweaked the config and started with the different decoder).

Are others seeing this big of a jump switching to the Frigate+/yolonas models and onnx detection over the stock yolo models and tensorrt? Any ideas why?

### Version

0.15.0-7fdf42a

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  host: REDACTED
  user: frigate
  password: REDACTED

logger:
  #default: debug
  logs:
    frigate.event: debug

timestamp_style:
  position: br

#Disable TLS on auth port as we use nginx to handle it
tls:
  enabled: false

auth:
  enabled: true
  trusted_proxies:
    - 127.0.0.0/24

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
#    - dog
#    - cat
  filters:
    person:
      threshold: 0.8
    car:
      threshold: 0.8
    motorcycle:
      threshold: 0.8
    bicycle:
      threshold: 0.8

record:
  enabled: true
  #sync_recordings: True
  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 30
  quality: 90

detectors:
  #############
  #FRIGATE PLUS
  #onnx:
  #  type: onnx

  #############
  #NON-FRIGATE PLUS
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

birdseye:
  enabled: true
  restream: true
  mode: objects

ffmpeg:
  hwaccel_args: preset-nvidia-h265
  output_args:
    #record: preset-record-generic-audio-aac
    record: preset-record-generic-audio-copy

model:
  #############
  #FRIGATE PLUS
  #path: plus://REDACTED

  #############
  #NON-FRIGATE PLUS
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: rgb

semantic_search:
  enabled: true
  model_size: large
  reindex: false

notifications:
  enabled: 'true'
  email: REDACTED

#motion:
  #threshold: 23
  #contour_area: 20
  #improve_contrast: true

go2rtc:
  streams:
    fg-cam-pole-1:
      - rtsp://operator:{FRIGATE_RTSP_PASSWORD}@fg-cam-pole.mydomain:554/Streaming/Channels/103/
    # OTHERS REDACTED

  webrtc:
    candidates:
      - 10.0.0.235:8555
      - stun:8555

#config camera streams similar to https://docs.frigate.video/guides/camera_setup/#example-camera-configuration
cameras:
  fg-cam-pole-1:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/fg-cam-pole-1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
    motion:
      mask:
        #REDACTED
    objects:
      filters:
        #REDACTED

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
name: 'frigate'

services:
  frigate:
    container_name: frigate
    #privileged: true # this may not be necessary for all setups
    restart: 'always'
    image: ghcr.io/blakeblackshear/frigate:7fdf42a-tensorrt
    runtime: nvidia
    shm_size: '16gb' #increase as necessary as cameras are added, see frigate docs
    volumes:
      - ./frigate/config:/config
      - /mnt/surveillance_frigate:/media/frigate
      - type: tmpfs # Optional: 4GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      - "5000:5000" #no auth web interface
      - "8971:8971" #authed web interface
      - "8554:8554" # RTSP feeds
      - "1984:1984" # webrtc feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      TZ: "America/New_York"
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      FRIGATE_ONVIF_USERNAME: "admin"
      FRIGATE_ONVIF_PASSWORD: "REDACTED"
      YOLO_MODELS: "yolov7-640,yolov7-320,yolov7x-640,yolov7-tiny-416"
      PLUS_API_KEY: "REDACTED"
      I_PROMISE_I_WONT_MAKE_AN_ISSUE_ON_GITHUB: "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

N/A

**Comment by NickM-27** [comment]
we need to see the system metrics to know what is going on

**Comment by robby-d** [comment]
Sure here you go. Same frame content...taken within 5-10 minutes of each other.

Hardware info:
`{"0":{"name":"NVIDIA RTX A4000","driver":"550.127.05","cuda_compute":8.6,"vbios":"94.04.57.00.09"}}`

**General tab - tensorRT/yolov7:**
<img width="1502" alt="frigate-tensorrt-general-1" src="https://github.com/user-attachments/assets/97d867d5-b186-4701-886d-922b071a20d5">
<img width="1439" alt="frigate-tensorrt-general-2" src="https://github.com/user-attachments/assets/36d5df83-f7d0-498f-9cba-2f3299532c2e">

**Cameras tab - tensorRT/yolov7:**
<img width="1499" alt="frigate-tensorrt-cameras-1" src="https://github.com/user-attachments/assets/a0a882e6-c369-4e7c-819f-0999f75c0f4f">
<img width="1489" alt="frigate-tensorrt-cameras-2" src="https://github.com/user-attachments/assets/c3d510a4-5b4a-4e98-92a0-a29ac661aa13">

**General tab - onnx/yolonas:**
<img width="1500" alt="frigate-onnx-general-1" src="https://github.com/user-attachments/assets/5fcbf0a7-48a5-4d5b-ac03-7d93b8d2cc1e">
<img width="1438" alt="frigate-onnx-general-2" src="https://github.com/user-attachments/assets/32c7a67d-d5ef-4311-b2b0-25f84d3be9cf">

**Cameras tab - onnx/yolonas:**
<img width="1444" alt="frigate-onnx-cameras-1" src="https://github.com/user-attachments/assets/25709041-f4e9-4c5e-8712-a140ea75149c">
<img width="1447" alt="frigate-onnx-cameras-2" src="https://github.com/user-attachments/assets/0d6eb723-2bf3-4f21-8a60-21c1b840f9c7">

**Reply by NickM-27** [reply]
In general yolonas is a larger model, and has different input characteristics so the differences in general are not unexpected. What cpu are you using? And to be clear you're using the tensorrt image variant in both cases right?

**Reply by robby-d** [reply]
Yes, using tensorrt image variant in both cases. The machine has an AMD EPYC 9124 Processor.

**Reply by NickM-27** [reply]
this is what mine looks like with a Ryzen 5700 and a 3050 during typical conditions. With the lower base clocks it seems like it could make sense for % of single CPU core. 

![Screen Shot 2024-11-16 at 16 00 46 PM](https://github.com/user-attachments/assets/f92224f7-6255-4536-9c41-5b14845bbc96)

**Reply by robby-d** [reply]
Thanks. Is there any config options that might help trim up the onnx detector usage? Is the detector GPU usage coming from motion detection, object classification, or both?

Lastly, can I use the generated tensorRT yolo images with onnx? I think the next step might be to use a stock yolonas image, as well as a stock yolov7 (or similar) image with onnx, to see if GPU usage is considerably less vs the custom Frigate+ yolonas image.

**Reply by NickM-27** [reply]
There is no detector GPU usage graph. Assuming you meant detector CPU usage, it has to do with changing the pixel format, cropping, etc to the input tensor, running the inference.

You could try using (on latest dev)

```
detectors:
  onnx:
    type: onnx
    device: Tensortt
```

and see if those results are better

**Reply by heviiguy** [reply]
I'm quite surprised at the high GPU usage. Seeing that mine barely ever goes above 2% makes me wonder whether I've misconfigured something.

- running with a Coral and a 3050 GPU

**Reply by NickM-27** [reply]
@heviiguy you have a coral, unless you're using your GPU for object detection then it's not relevant

**Reply by robby-d** [reply]
I added the line and it seemed to help, but I am not totally sure yet (the runs below were 3 minutes apart but there still could be material scene differences, and later runs without the line had better GPU usage). I'll continue to monitor it over the next week and see if performance degrades again. Thanks!

Without line:
<img width="1425" alt="without line" src="https://github.com/user-attachments/assets/3ecdd2dc-3216-456a-ae0e-2128307248e4">

With line:
<img width="1419" alt="with" src="https://github.com/user-attachments/assets/a7eac66e-d101-41f9-9996-c7833a9f1b29">

**Reply by robby-d** [reply]
So many of the GPU peaks might be related to detection peaks on one of the cameras in particular (where I am monitoring a construction scene that sometimes gets complex - with the peaks in question there were 3+ vehicles and 4+ people moving, showing peaks of 60-75 detections). I am at 6 fps, 1280x720 resolution, but I wonder if there is some kind of better way to optimize detections besides things like motion masks, which don't help here because it's a PTZ camera and the scene changes depending what it's pointed at.

<img width="709" alt="Screenshot 2024-11-17 at 10 40 48 AM" src="https://github.com/user-attachments/assets/58c35268-e02d-4dcc-b627-8ee7611ccefb">

**Reply by heviiguy** [reply]
> @heviiguy you have a coral, unless you're using your GPU for object detection then it's not relevant

Money well spent. Thanks for making this clear, @NickM-27

**Reply by levski** [reply]
> I'm quite surprised at the high GPU usage. Seeing that mine barely ever goes above 2% makes me wonder whether I've misconfigured something.
> 
>     * running with a Coral and a 3050 GPU

dumb question alert.
the 3050 is used for h265 decode?
was thinking of a similar setup, btw how many cameras you running?

sorry not hijacking the post, just wanted the clarify. frigate new guy here.

**Reply by robby-d** [reply]
GPU detection usage seems to be high when I have several busy scenes. With a second GPU in the machine and passed through to Frigate, would the object detection be distributed across both cards? I have an RTX A2000 I could put in the server as well...

**Reply by NickM-27** [reply]
You can specify a device number (0, 1) as the device to distribute it

**Reply by heviiguy** [reply]
> btw how many cameras you running?

Running 6 cameras. Apparently, however, the 3050 is superfluous in this regard as the Coral TPU seems to be doing the heavy lifting. Oh well, at least I've got redundancy!

**Reply by robby-d** [reply]
Considering running a few USB Corals with Frigate (I'm running ESXI 8 and the USB ones seem to be the only ones that work with ESXI right now). Does anyone have a real world measurement of FPS (or avg inference speed) that a Coral can handle with a Frigate+ `mobiledet` detector in use? Wanted to see if this was viable vs using GPUs.

**Reply by robby-d** [reply]
I moved to proxmox, added a second GPU (A2000) into the system, and got both the A4000 and A2000 passed through to the frigate VM. Everything works fine with the A4000. I wanted to see if it was possible to balance the load across the A4000 and A2000. I modified my docker compose file, adding:
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1'] # this is only needed when using multiple GPUs
                #count: 1
              capabilities: [gpu]
```

Also modified my frigate config, adding:
```
detectors:
  onnx0:
    type: onnx
    device: Tensortt
    device_id: 0
  onnx1:
    type: onnx
    device: Tensortt
    device_id: 1
```

Both detectors show up in the frigate interface, but detection load is still all on the first GPU. Am I missing something?

**Reply by NickM-27** [reply]
You need to set device as 0/1 not device id

**Reply by robby-d** [reply]
While I was looking into this and looking at the source, I noticed a typo in my config. The device was "Tensortt", not "Tensorrt". Also, from a recent commit (https://github.com/blakeblackshear/frigate/commit/96c0c43dc8d61bafd1be258c9cbc4b1df9204411) it looks like it's "device_id", unless I am misunderstanding something here. Given that, I changed the detectors snippet of my config to:

```
detectors:
  onnx_0:
    type: onnx
    device: Tensorrt
    device_id: 0
  onnx_1:
    type: onnx
    device: Tensorrt
    device_id: 1
```

When I start the container back up, Frigate now starts complaining about `libnvinfer.so.10` being missing:
```
frigate  | 2024-11-22 13:38:56.057912874  [2024-11-22 08:38:56] detector.onnx_0                INFO    : Starting detection process: 394
frigate  | 2024-11-22 13:38:56.057957004  [2024-11-22 08:38:56] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
frigate  | 2024-11-22 13:38:56.064890164  2024-11-22 08:38:56.064832024 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory
frigate  | 2024-11-22 13:38:56.067208585  2024-11-22 08:38:56.067138235 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory
frigate  | 2024-11-22 13:38:56.067210015
frigate  | 2024-11-22 13:38:56.164837733  [2024-11-22 08:38:56] detector.onnx_1                INFO    : Starting detection process: 396
```

Unsure if this file is required on the host side, or is missing from the frigate tensorrt container build? Going off of https://packages.ubuntu.com, Ubuntu at least does not seem to include `libnvinfer.so.*` in any pre-built package (and I am using Ubuntu packages for the nvidia drivers and runtimes on the box).

**Reply by NickM-27** [reply]
it is using the device field

> device_id = 0 if not device.isdigit() else int(device)

**Reply by robby-d** [reply, marked as answer]
Was still having high GPU usage during times of high activity: 70% with a single A4000 and 40% on both an A4000 and A2000 when running dual GPU.

I think what I'll do is just switch to a dual coral TPU setup for detection, and use the GPU for hwaccel/decoding. Using a single USB coral for testing and it seems much better than the GPU setup for detection! I'll close this issue. Thanks for the help.

**Comment by chrislawso** [comment]
Hi,

I saw your docker compose has
```
environment:
      YOLO_MODELS: "yolov7-640,yolov7-320,yolov7x-640,yolov7-tiny-416"
```
and your config model has
```
model:
  #############
  #NON-FRIGATE PLUS
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: rgb
```

Curious why you chose to run with the `yolov7-tiny-416.trt` compared to the others?

Thanks
