### DISCUSSION TITLE
[Support]: BirdsEye keep unavailable camera thumb

### DISCUSSION THREAD

**Discussion by tapsystem** [blakeblackshear/frigate#15036] [General Support] [answered]
### Describe the problem you are having

Hello,

Everythings works fine, i don't understand why or what's my mistake in the birdseye camera, because if one of my camera become unavailable, the thumbnail of the camera stay visible in the birdseye ... So i can't detect camera error  because it's just look like nothing was moving on camera but in reality camera is off .... ( occur in frigate web UI and in card too).

Thanks by advance for ideas

### Version

0.14.1 FA

### Frigate config file

```yaml
## --config v2 
## >> configuration doc : https://docs.frigate.video/configuration/reference

version: 0.14

database:
  path: /config/frigate.db #frigate network storage config : https://docs.frigate.video/guides/ha_network_storage

mqtt:
  enabled: true
  host: 192.168.***.***
  user: ***
  password: ****


#============================
#-------- STREAMS ----------
#============================

ffmpeg:
  hwaccel_args: preset-vaapi #preset-intel-qsv-h264  #preset-intel-qsv-h265
  #global_args: -hide_banner -loglevel warning -threads 2

go2rtc:
  streams:
    cam_entree_rtsp: # <- for RTSP streams
      - rtsp://****:****@192.168.***.***:554/cam/realmonitor?channel=1&subtype=1 
    cam_cuisine_rtsp: # <- for RTSP streams
      - rtsp://****:****@192.168.***.***:554/cam/realmonitor?channel=1&subtype=1
    cam_salon_rtsp: # <- for RTSP streams
      - rtsp://****:****@192.168.***.***:554/cam/realmonitor?channel=1&subtype=1
    cam_garage_rtsp: # <- for RTSP streams
      - rtsp://****:****@192.168.***.***:554/cam/realmonitor?channel=1&subtype=1
    cam_devant_rtsp: # <- for RTSP streams
      - rtsp://****:****@192.168.***.***:554/cam/realmonitor?channel=1&subtype=1

#recherche url imou :
# subtype = 0 >  H265 en 2304x1296 / subtype = 1 > H264 en 640x480

# Live stream configuration for WebUI
live:
  quality: 8 

#==============================================
#-------- EVENTS / RECORDS / GRABS  ----------
#==============================================

# audio events
audio:
  enabled: false

# snapshots
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  quality: 90
  retain:
    # Default retention days
    default: 10
    # Per object retention days
    objects:
      person: 15

#record  # https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 15
    post_capture: 30
    objects:
      - person
    retain:
      default: 3
      objects:
        person: 7

#============================
#-------- BirdsEye ----------
#============================

birdseye:
  # Optional: Enable birdseye view (default: true)
  enabled: true
  mode: continuous # show all camera all the time
  width: 1280
  height: 720
  # Optional: Restream birdseye via RTSP (default: false)
  restream: false
  # inactivity threshold can be adjusted to control how long a camera must be inactive before it is removed from the Birdseye view (default 30 sec)
  inactivity_threshold: 5
  # Optional: Encoding quality of the mpeg1 feed : 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  layout:
    # Optional: Scaling factor for the layout calculator, range 1.0-5.0 (default: 2.0)
    scaling_factor: 4.0

#============================
#-------- DETECTION ----------
#============================

detectors:
  coral:
    type: edgetpu
    device: usb

objects: # voir https://docs.frigate.video/configuration/objects
  track:
    - person
    - cat
    - car

detect:
  enabled: true
  width: 720
  height: 480
  fps: 4
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 20
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0


#============================
#-------- CAMERAS ----------
#============================

cameras:
  cam_entree:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_entree_rtsp
          roles:
            - record
            - detect
    ui:
      order: 1 # Adjust sort order of cameras in the UI. Larger numbers come later
      dashboard: true # Optional: Whether or not to show the camera in the Frigate UI
    # onvif:      # ONVIF ne marche pas en mode frigate, utiliser l'integration onvif directement
    #   host: 192.168.1.118 # host of the camera      
    #   port: 8000 # ONVIF port (Optional).
    #   user: admin
    #   password: Gxm4GeHwbvmXoZYBZiP
    #   autotracking:
    #     enabled: False
    birdseye:
      order: 1


  cam_cuisine:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_cuisine_rtsp
          roles:
            - record
            - detect
    ui:
      order: 4
      dashboard: true
    birdseye:
      order: 4

  cam_salon:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_salon_rtsp
          roles:
            - record
            - detect
    ui:
      order: 3
      dashboard: true
    birdseye:
      order: 3

  cam_garage:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_garage_rtsp
          roles:
            - record
            - detect
    ui:
      order: 2
      dashboard: true
    birdseye:
      order: 2

  cam_devant:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_devant_rtsp
          roles:
            - record
            - detect
    ui:
      order: 0
      dashboard: true
    birdseye:
      order: 0

#============================
#============================
camera_groups:
  BirdsEye:
    order: 1
    icon: LuView
    cameras: birdseye
```

### Relevant Frigate log output

```shell
no specific oupout
```

### Relevant go2rtc log output

```shell
no specific oupout
```

### FFprobe output from your camera

```shell
no specific oupout
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
...
```

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

IMOU cruiser 3MP and  Ranger C2
