### DISCUSSION TITLE
[Support]: 503 Service Unavailable During Playback After Update to 0.14

### DISCUSSION THREAD

**Discussion by DustyArmstrong** [blakeblackshear/frigate#15034] [General Support]
### Describe the problem you are having

I am getting a 503 error on the review page since updating to 0.14 today. I am trying to look at footage from one of my cameras that has continuous recording, but it gives me the following: 

```XHRGET
https://cctv.mydomain.com/vod/reocam1/start/1731852000/end/1731853316/seg-1-v1-a1.ts
[HTTP/1.1 503 Service Temporarily Unavailable 63ms]

Status
503
Service Temporarily Unavailable
VersionHTTP/1.1
Transferred374 B (197 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem
```

This seems to primarily happen in Firefox browsers but also occurs on others. I didn't have any problems before and don't generally get video playback errors, it is only Frigate since updating to 0.14 today.

I can watch the cameras live without issue. Seemed to work fine in Safari for a bit but now doesn't, the native files themselves on my network storage (where they end up) playback fine, worst in Firefox. 

Have tried rebooting the server, refreshing browsers but the issue persists. Everything seems generally slower and sluggish compared to v13 so not sure if there's something else I should be tweaking.

I use an Nginx reverse proxy but even when I try it directly on the port with no proxying it still returns an error 503 that the .ts file is unavailable at the IP.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 133.0.2

### Frigate config file

```yaml
go2rtc:
  streams:
    reocam1:
      - ffmpeg:http://192.168.1.102/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Password#video=copy#audio=copy#audio=opus
    reocam1_sub:
      - ffmpeg:http://192.168.1.102/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Password
    reocam2:
      - ffmpeg:http://192.168.1.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Password#video=copy#audio=copy#audio=opus
    reocam2_sub:
      - ffmpeg:http://192.168.1.101/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Password
    doorbellcam:
      - ffmpeg:http://192.168.1.103/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Password#video=copy#audio=copy#audio=opus
      - rtsp://admin:Password@192.168.1.103:554/h264Preview_01_sub
    doorbellcam_sub:
      - ffmpeg:http://192.168.1.103/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Password
    dogcam:
      - ffmpeg:http://192.168.1.104/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Password#video=copy#audio=copy#audio=opus
    dogcam_sub:
      - ffmpeg:http://192.168.1.104/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Password

cameras:
  reocam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.1.102:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:Password@192.168.1.102:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      required_zones:
        - driveway
        - full
    record:
      enabled: true
      retain:
        days: 5
        mode: all
    mqtt:
      required_zones:
        - driveway
        - full
    zones:
      driveway:
        coordinates: 207,265,377,270,450,242,448,0,640,0,640,442,437,436,440,480,0,480,0,243
        objects:
          - car
          - motorcycle
      full:
        coordinates: 0,480,418,480,426,440,640,440,640,27,535,32,488,0,382,85,0,93
        objects:
          - person
          - dog
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
      filters:
        car:
          mask: 0.006,0.144,0.666,0.188,0.656,0.485,0,0.461
    motion:
      mask:
        - 0,0,308,0,321,235,0,233

    review:
      alerts:
        required_zones:
          - driveway
          - full
  reocam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.1.101:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:Password@192.168.1.101:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
    snapshots:
      required_zones:
        - garden
    mqtt:
      required_zones:
        - garden
    zones:
      garden:
        coordinates: 640,0,640,480,205,480,274,0
        objects:
          - person
          - dog
    motion:
      mask:
        - 640,0,258,0,220,480,0,480,0,0

    review:
      alerts:
        required_zones:
          - garden
  doorbellcam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbellcam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbellcam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      required_zones:
        - entryway
    mqtt:
      required_zones:
        - entryway
    zones:
      entryway:
        coordinates: 145,77,411,66,429,256,433,303,485,480,162,480,90,224
        objects:
          - person
          - dog
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 275,46,289,0,0,0,0,46

    review:
      alerts:
        required_zones: entryway
  dogcam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dogcam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dogcam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - dog
    motion:
      mask:
        - 0,60,302,62,299,0,0,0

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

tls:
  enabled: false

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30
mqtt:
  host: xx.xx.xx.xx
  enabled: true
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqttuser
  password: pw

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay
    -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy

record:
  enabled: true
  events:
    pre_capture: 3
    post_capture: 2
    retain:
      default: 30
      mode: motion
    objects:
      - person
      - dog
      - car
      - motorcycle

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

version: 0.14
camera_groups:
  Birdseye_-_All_Cameras:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
Nothing logged
```

### Relevant go2rtc log output

```shell
Nothing logged
```

### FFprobe output from your camera

```shell
Unsure what URL to probe, probing the URL in the configuration returns errors for all cameras (HTTP Reolink).
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    #cap_add:
    #  - CAP_PERFMON
    networks:
      - containershare
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb
      #- /dev/apex_0:/dev/apex_0
      #- /dev/apex_1:/dev/apex_1
      - /dev/dri/card0 
      - /dev/dri/card1 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/Dockerfiles/frigate/config:/config
      - /home/user/Dockerfiles/frigate/config/config.yml:/config/config.yml
      - /media/footage/frigate/clips:/media/frigate/clips
      - /media/footage/frigate/recordings:/media/frigate/recordings
      - /media/footage/frigate:/media/frigate
      - /home/user/Dockerfiles/frigate/db:/media/frigate/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "1935:1935" # RTMP feeds (deprecated)
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "Password"
      LIBVA_DRIVER_NAME: i965
    security_opt:
      - no-new-privileges:true

networks:
  containershare:
    name: containershare
    external: true
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

Only seems to be with Frigate playback, 503 unavailable. I also get some other issues around playback but this only seems to be Firefox on MacOS.
