### DISCUSSION TITLE
[Support]: Frigate detecting motion on Reolink doorbell, but Home Assistant notification not working...

### DISCUSSION THREAD

**Discussion by captainkev76** [blakeblackshear/frigate#15041] [General Support]
### Describe the problem you are having

I have an existing Reolink Camera set up in Frigate, and I have the MQTT all set up so that when motion is detected Home Assistant sends a notification to my phone. It works pretty well. However, I've just added a new Reolink Video Doorbell PoE and nothing I do seems to make it do the same. I've set it up almost identically in Frigate. HomeAssistant has detected there's a new camera, and I have created a new automation using the same blueprint, with almost the same settings (just the entity being different).

When I create motion on the camera, Frigate triggers a recording and I then see the clip in the Frigate gallery, but HomeAssistant doesn't seem to be getting the trigger to send the notification. 

I've tried rebooting everything, but it just won't work. Anyone got any suggestions?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
mqtt:
  enabled: true
  user: frigate_mqtt
  password: password
  host: 192.168.1.xx
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
go2rtc:
  streams:
    driveway_main:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_main
      - ffmpeg:driveway_main#audio=opus
    driveway_sub:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_sub
      - ffmpeg:driveway_sub#audio=opus
    side_main:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_main
      - ffpmeg:side_main#audio=opus
    side_sub:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_sub
      - ffmpeg:side_sub#audio=opus
    garden_main:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_main
      - ffmpeg:garden_main#audio=opus
    garden_sub:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_sub
      - ffmpeg:garden_sub#audio=opus
    garage:
      - rtsp://user:password@192.168.50.xx/live0
      - ffmpeg:garage#audio=opus
    doorbell_main:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_main
      - ffmpeg:doorbell_main#audio=opus
    doorbell_sub:
      - rtsp://user:password@192.168.50.xx:554/h264Preview_01_sub
      - ffmpeg:doorbell_sub#audio=opus

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.x:8554/driveway_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://192.168.1.x:8554/driveway_main
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    motion:
      mask: 0,0,0.198,0,0.369,0,0.319,0.08,0.099,0.326,0,0.439,0,1
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 90
          mode: active_objects
          objects:
            car: 10
            person: 90
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.50.xx:554/h264Preview_01_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://user:password@192.168.50.xx:554/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 90
          mode: active_objects
          objects:
            car: 10
            person: 90
    motion:
      mask: 0.997,0.154,0.936,0.1,0.872,0.033,0.86,0.002,0.904,0,1,0,1,0.097
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.xx:8554/doorbell_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://192.168.1.x:8554/doorbell_main
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 90
          mode: active_objects
          objects:
            car: 10
            person: 90
    zones:
      full:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.x:8554/garden_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://192.168.1.x:8554/garden_main
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
          objects:
            car: 10
            person: 90
  side_path:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.x:8554/side_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://192.168.1.x:8554/side_main
          roles:
            - record
    motion:
      mask:
        - 0,0,127,0,205,0,222,40,175,259,152,480,0,480
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
          objects:
            car: 30
            person: 30
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.xx:8554/garage # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
          objects:
            person: 90

version: 0.14
```

### Relevant Frigate log output

```shell
Nothing
```

### Relevant go2rtc log output

```shell
Nothing
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://user:password@192.168.50.xxx:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000375, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 10 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024M" # update for your cameras based on calculation
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/docker/frigate:/config.yml:ro # modify to match your setup
      - /mnt/cctv/frigate:/media/frigate # modify to match your setup
      - /root/frigate:/db # modify to match your setup
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    environment:
      FRIGATE_RTSP_PASSWORD: "password" #modify to whatever if using rtsp
      TZ: Europe/London
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell PoE
