### DISCUSSION TITLE
Disable certain object detaction for specific camera 0.15_beta [Config Support]:

### DISCUSSION THREAD

**Discussion by minigranis** [blakeblackshear/frigate#15042] [Config Support] [answered]
### Describe the problem you are having

I am trying to disable object detection for car on one of my cameras, but not for all and I cant figure out how to do it.
Right now I am using a zone but I would like to remove car from the camera all together. 
I have tried using an "objects: track: -person -cat -dog" on the "ffmpeg: input:" level in the config but that doesnt work.
Where do I put the "objects: track:" section on the 0.15-beta ?
Any hints are welcome.

### Version

0.15.0-beta1

### Frigate config file

```yaml
Tallnas_Carport_Inne:  # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:!Os2warp0@192.168.1.22:554/Streaming/Channels/02
          roles:
            - detect
        - path: rtsp://admin:!Os2warp0@192.168.1.22:554/rtsp # <----- The stream you want to use for detection
          roles:
            - record
    record: # <----- Enable recording
      enabled: true
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      stationary:
        interval: 50
        threshold: 50
    motion:
      mask: 0.034,0.014,0.286,0.015,0.287,0.07,0.038,0.072
      #mask: 0.034,0.017,0.284,0.013,0.287,0.064,0.037,0.072
    objects:
      filters:
        car:
          threshold: 0.9
    zones:
      full:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 1
        objects:
          - bear
          - bicycle
          - bird
          - cat
          - cow
          - dog
          - elephant
          - giraffe
          - horse
          - person
          - sheep
          - zebra
        inertia: 3
    review:
      alerts:
        required_zones: full
      detections:
        required_zones: full
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral

**Comment by hawkeye217** [comment, marked as answer]
Don't put it in the `ffmpeg` `input` level, just add to what you already have in the `objects` entry, eg:

```
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        car:
          threshold: 0.9
```
