### DISCUSSION TITLE
Onvif camera

### DISCUSSION THREAD

**Discussion by IncByteLC** [blakeblackshear/frigate#15040] [Ask A Question]
Unable to add onvif camera using IP.
Current config is:
```
## Camera 1 ##
  Sonoff:
    ffmpeg:
      inputs:
        - path: rtsp://xxx
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 20
```
Was trying to onvif based on the documentation, but always error: ffmpeg: is required....
