### DISCUSSION TITLE
High load while turning on detection with i5-8500T on board

### DISCUSSION THREAD

**Discussion by puzver1** [blakeblackshear/frigate#15053] [Ask A Question]
Hello

I got two Chinese cameras, h265, unsplitable two lens in one stream ... and need to have them splitted - I have created such config 

```
mqtt:
  host: 192.168.0.xxx 
  port: 1883         
  user: xxxx
  password: xxxx 
  topic_prefix: frigate  # Prefix for MQTT topics (optional, default is 'frigate')

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  width: 640
  height: 360
    #  min_area: 500
  fps: 5  # Lower FPS for detection to save resources

motion:
  threshold: 40
  contour_area: 20
# Global record settings
record:
  enabled: true
  retain:
    days: 5  # Retain recordings for 7 days
    mode: motion
  events:
    retain:
      default: 10  # Retain event clips for 10 days
      mode: motion
cameras:
  top_tp:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/top_tp
          input_args: preset-rtsp-restream
          roles:
            - detect
            - motion
  bottom_tp:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/bottom_tp
          input_args: preset-rtsp-restream
          roles:
            - detect
            - motion
  top_pp:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/top_pp
          input_args: preset-rtsp-restream
          roles:
            - detect
            - motion
  bottom_pp:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/bottom_pp
          input_args: preset-rtsp-restream
          roles:
            - detect
            - motion
go2rtc:
  streams:
    top_tp: ffmpeg:rtsp://xxx:xxxx@192.168.0.2xx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:0"
    bottom_tp: ffmpeg:rtsp://xxxx:xxxx@192.168.0.2xx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:in_h/2"
    top_pp: ffmpeg:rtsp://uxxxx:xxxx@192.168.0.xxx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:0"
    bottom_pp: ffmpeg:rtsp://xxx:xxxx@192.168.0.xxx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:in_h/2"



version: 0.14


```

I have currently change my server, as previously spliting the image genereated very big load - but now - I see that intel gpu is being turned on and with 4 cameras out of 2 - everything works fine ... as long as I will not turn on detection - then CPU!!! (not gpu) load is reaching 100 % 
frigate is running on docker

**Comment by NickM-27** [comment]
would be best to see screenshots of system and camera metrics

**Comment by puzver1** [comment]
It is interesting 
![image](https://github.com/user-attachments/assets/8ece9b3a-6838-4793-ae25-d6886d4acb7f)

![image](https://github.com/user-attachments/assets/472cd0cf-8f4a-419d-8f35-f6ec3a2bd4e5)

![image](https://github.com/user-attachments/assets/0b3dbc44-146f-4734-b1ab-ed2dc8edfe56)

**Comment by puzver1** [comment]
![image](https://github.com/user-attachments/assets/12eac351-8353-4053-acb4-b789604d23c5)

**Comment by puzver1** [comment]
I have even disabled "-detect" role in every camera - and still load on cpu is 100 %

**Comment by hawkeye217** [comment]
This seems to indicate there's something else running on the server using excess cpu.

**Comment by puzver1** [comment]
yes, it's ffmpeg 
<img width="581" alt="image" src="https://github.com/user-attachments/assets/d8b58a79-dc88-4087-970f-82a1cb00d5f0">

and I believe it is coming from here go2rtc:
```

  streams:
    top_tp: ffmpeg:rtsp://xxx:xxxx@192.168.0.2xx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:0"
    bottom_tp: ffmpeg:rtsp://xxxx:xxxx@192.168.0.2xx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:in_h/2"
    top_pp: ffmpeg:rtsp://uxxxx:xxxx@192.168.0.xxx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:0"
    bottom_pp: ffmpeg:rtsp://xxx:xxxx@192.168.0.xxx:554/rtsp#video=h265#hardware=hevc_vaapi#raw=-vf "crop=in_w:in_h/2:0:in_h/2"

```
