### DISCUSSION TITLE
[Camera Support]: Reolink Cameras causing ffmpeg crashes

### DISCUSSION THREAD

**Discussion by death2all110** [blakeblackshear/frigate#15060] [Camera Support]
### Describe the problem you are having

Frigate logs are getting filled with ffmpeg related errors from my Reolink Cameras. I do get the occasional error from my Amcrest doorbell, but the largest offender is by far my 2 reolink cameras.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 132.0.2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 172.18.0.10
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: <redacted>
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: pci
ffmpeg:
  hwaccel_args: preset-nvidia
  global_args: '-hide_banner -loglevel level+info' 
go2rtc:
  streams:
    driveway:
      - http://192.168.11.119/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED
      - ffmpeg:driveway#audio=aac
    driveway_sub:
      - http://192.168.11.119/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=REDACTED
    backyard:
      - http://192.168.11.39/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED
      - ffmpeg:backyard#audio=aac
    backyard_sub:
      - http://192.168.11.39/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=REDACTED
    frontdoor:
      - rtsp://admin:REDACTED@192.168.11.170:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:frontdoor#audio=opus
    frontdoor_sub:
      - rtsp://admin:REDACTED@192.168.11.170:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    webrtc:
    candidates:
      - 172.18.0.10:8555
      - 192.168.11.192:8555
      - stun:8555
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 14
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 720
      height: 576
      fps: 5
birdseye:
  enabled: true
  mode: continuous
logger:
  default: warning
  logs:
    ffmpeg: debug
version: 0.14
```

### Relevant Frigate log output
[frigate-2024-11-18T22-13-35.zip](https://github.com/user-attachments/files/17807122/frigate-2024-11-18T22-13-35.zip)

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:REDACTED@192.168.11.119:554':
  Metadata:
    title           : Session streamed by "preview"
    comment         : 
  Duration: N/A, start: 0.000313, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 30 fps, 30 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-510A

### Screenshots of the Frigate UI's System metrics pages

![2024-11-18 16_32_42-explorer-%t](https://github.com/user-attachments/assets/5aef278e-196d-4ac7-a92c-f66503134b71)

### Any other information that may be helpful
![2024-11-18 16_08_41-explorer-%t](https://github.com/user-attachments/assets/425f1733-1e42-4c39-be10-ba078ff9cf0d)
![2024-11-18 16_05_50-explorer-%t](https://github.com/user-attachments/assets/f94ba61f-6017-4550-a05a-e71c9449c162)
![2024-11-18 16_06_32-explorer-%t](https://github.com/user-attachments/assets/218c175c-36ab-47b4-bea6-379b8f4e579b)

_No response_
