### DISCUSSION TITLE
Having issues with frigate since upgrading to 0.14 from 0.13

### DISCUSSION THREAD

**Discussion by delusr** [blakeblackshear/frigate#15063] [General Support]
### Describe the problem you are having

Ive got 3 Dahua cameras 2x HDBW1430DE-SW (dont work) and a SD22404DB-GNY-W IK10 (works) they all worked in Frigate 0.13 since updating to 0.14 I can only get 1 to work Im using HAOS on a standalone (Odroid H3+) machine with 32Gb ram with a dual edge TPU

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant.local
  user: username
  password: password

cameras:
  Driveway:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://username:password@192.168.69.80:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
        - path: rtsp://username:password@192.168.69.80:554/live
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
```

### Relevant Frigate log output

```shell
Preparing Frigate...
Starting Frigate...
frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate.util.config            INFO    : frigate config does not need migration...
frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
peewee_migrate.logs            INFO    : Starting migrations
peewee_migrate.logs            INFO    : There is nothing to migrate
frigate.app                    INFO    : Recording process started: 362
frigate.app                    INFO    : Recording process started: 364
frigate.app                    INFO    : go2rtc process pid: 98
detector.coral1                INFO    : Starting detection process: 391
frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
frigate.app                    INFO    : Output process started: 397
detector.coral2                INFO    : Starting detection process: 393
frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate.app                    INFO    : Camera processor started for Driveway: 439
frigate.app                    INFO    : Capture process started for Driveway: 441
frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.
frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...
watchdog.Driveway              ERROR   : Ffmpeg process crashed unexpectedly for Driveway.
watchdog.Driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ffmpeg.Driveway.detect         ERROR   : rtsp://*:*@192.168.69.80:554/live: Invalid data found when processing input
```

### Relevant go2rtc log output

```shell
2024-11-19 06:16:41.518667546  [INFO] Preparing new go2rtc config...
2024-11-19 06:16:41.575977653  [INFO] Got IP address from supervisor: 192.168.69.109
2024-11-19 06:16:41.628984801  [INFO] Got WebRTC port from supervisor: 8555
2024-11-19 06:16:42.243990417  [INFO] Starting go2rtc...
2024-11-19 06:16:42.421354856  16:16:42.421 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-19 06:16:42.421940942  16:16:42.421 INF config path=/dev/shm/go2rtc.yaml
2024-11-19 06:16:42.422944912  16:16:42.422 INF [rtsp] listen addr=:8554
2024-11-19 06:16:42.422961581  16:16:42.422 INF [api] listen addr=:1984
2024-11-19 06:16:42.422967224  16:16:42.422 INF [webrtc] listen addr=:8555/tcp
2024-11-19 06:16:51.514745936  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Cannot access API from HAOS
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
Using HAOS as a standalone
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua

**Comment by hawkeye217** [comment]
The stream at `rtsp://username:password@192.168.69.80:554/live` is sending bad data. Are you sure this is the correct url?

**Reply by delusr** [reply]
Yes it worked on v0.13  without issue but I will look into it after work

**Comment by amm009uk** [comment]
You could try rtsp://username:password@192.168.69.80:554/live with vlc just to make sure its not the camera

**Reply by delusr** [reply]
I cannot get any of them to work in VLC. They still all work in frigate 0.13 and the only one that works in frigate 0.14 also doesnt work in VLC.

**Reply by hawkeye217** [reply]
My Dahua URLs look like this:

`rtsp://username:password@ip_address:554/cam/realmonitor?channel=1&subtype=0`
`rtsp://username:password@ip_address:554/cam/realmonitor?channel=1&subtype=1`

**Comment by delusr** [comment]
The camera that does work in frigate but not in vlc does also work using ffplay.

ffplay rtsp://admin:password@192.168.69.92:554/cam/realmonitor?channel=1&subtype=0

**Comment by amm009uk** [comment]
I'm only starting out with frigate but my old wifi cameras worked and then they didn't! Made so many changes not sure what caused the problem. But I know the wifi was weak so I've been redoing the mesh setup to improve wifi. So I stuck it out with vlc thinking if vlc can't play the rtsp then what chance in frigate. I've managed to improve wifi and now vlc is working and so is frigate. Here's a snippet in case it helps - add go2rtc like most others have:

------------------
```
go2rtc:
  streams:
    Build1:
      - rtsp://username:password@192.168.2.150:80/videoMain
    Build1_sub:
      - rtsp://username:password@192.168.2.150:80/videoSub
  
cameras:
  Build1:
    enabled: true
    ffmpeg:
      hwaccel_args: auto
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/Build1
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://127.0.0.1:8554/Build1_sub
          roles:
            - detect
    detect:
      enabled: true
```
------------------
