### DISCUSSION TITLE
[Support]: v15 Beta1: OpenVINO 2024.3 Fails to run INT8 YOLO-NAS Models correctly on the GPU

### DISCUSSION THREAD

**Discussion by aeozyalcin** [blakeblackshear/frigate#15061] [Detector Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I found that OpenVINO 2024.3 is not running INT8 YOLO-NAS models correctly with the GPU. Running the INT8 model on the CPU, or using the default FP16/32 images on the GPU does not exhibit this issue. See shared image below - the inference generates a bunch of noise. 

I found that hopping into the container, and updating the openvino python package to `openvino-2024.4.0` fixes this issue. I recommend updating OpenVINO to 2024.4 going forward.

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/55e9bbc9-8f6c-4a54-b5d6-b489097aa536">

### Steps to reproduce

1. Export Yolo-NAS model with the following parameters:
```
   model.export("yolo_nas_s_int8.onnx",
                 output_predictions_format=DetectionOutputFormatMode.FLAT_FORMAT,
                 quantization_mode=ExportQuantizationMode.INT8,
                 max_predictions_per_image=20,
                 confidence_threshold=0.4,
                 input_image_shape=(416,416),
                )
```

2.  Load onto computer and configure Frigate to use this model, with GPU 
3.
4.
...

### Version

v15 Beta 1  (0.15.0-33825f6)

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 416 # <--- should match whatever was set in notebook
  height: 416 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /media/frigate/openvino-models/yolo_nas_s_int8_11_4.onnx
  labelmap_path: /media/frigate/openvino-models/coco_80cl.txt
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate_beta
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      # - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/raid1_hdd/frigate_v15/config:/config
      - /mnt/raid1_hdd/frigate_v15/media:/media/frigate      
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    cap_add:
      - CAP_PERFMON
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "blah"
```

### Relevant Frigate log output

```shell
No errors/messages logged
```

### Relevant go2rtc log output

```shell
No errors/messages logged
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink & Amcrest

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/038c9573-60f8-43e4-aee3-ec21c5722efe)
