### DISCUSSION TITLE
[Config Support]: 0.15.0-beta1 does not honor pre_capture settings in record

### DISCUSSION THREAD

**Discussion by hacsjalano** [blakeblackshear/frigate#15073] [Report a Bug] [answered]
### Describe the problem you are having

In release 0.14.1, I had this configuration and pre_capture was working correctly:

```
record:
  enabled: true
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: all
```

In 0.15.0-beta1, this has been auto-adjusted on startup to look like this:

```
record:
  enabled: true
  alerts:
    pre_capture: 15
    post_capture: 15
    retain:
      days: 30
      mode: all
  detections:
    pre_capture: 15
    post_capture: 15
    retain:
      days: 30
      mode: all
```

However, I am no longer getting the 15-second of pre_capture on my recordings.  No errors occur on startup; it just behaves as though the pre_capture setting is not there.

I have reverted back to 0.14.1 to confirm it still works.

I have also tried the image ghcr.io/blakeblackshear/frigate:9ae839a-amd64 and it also behaves the same way.

### Version

0.15.0-33825f6

### Frigate config file

```yaml
logger:
  # normal is info
  default: warning
tls:
  enabled: false
mqtt:
  host: 192.168.1.120
  port: 1883
  user: mqtt-user
  password: redacted
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  mode: motion
  inactivity_threshold: 15
review:
  alerts:
    labels:
      - car
      - motorcycle
      - bicycle
      - cat
      - dog
      - bear
      - bird
      - raccoon
      - fox
      - squirrel
      - rabbit
      - person
record:
  enabled: true
  alerts:
    retain:
      days: 30
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 30
    pre_capture: 15
    post_capture: 15
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image
  clean_copy: true
  bounding_box: true
  timestamp: false
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  height: 175

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - car
    - motorcycle
    - bicycle
    - cat
    - dog
    - bear
    - bird
    - raccoon
    - fox
    - squirrel
    - rabbit
    - person
ffmpeg:
  hwaccel_args: preset-vaapi
model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## BEGIN Cameras and re-stream section
go2rtc:
  streams:
    front_door:
      rtsp://user:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0#loryta

cameras:
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 854
      height: 480
    objects:
      track:
        - person
        - dog
        - cat
        - bear
        - deer
        - bird
        - raccoon
        - squirrel
        - rabbit
      filters:
        person:
          min_area: 350
version: 0.15-0
```

### Relevant Frigate log output

```shell
no relevant logs
```

### Relevant go2rtc log output

```shell
no relevant logs
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate

    # only so GPU stats can be seen
    privileged: true
    # restart: unless-stopped
    restart: "no"

    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1

    shm_size: "512mb" # update for your cameras if needed.  See shm_cameras.txt
    # network_mode is host for webRTC
    network_mode: "host"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config/:/config/
      - /frigate/media:/media/frigate
      - type: tmpfs # Optional: 4GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "redacted"
```

### Object Detector

Coral
