### DISCUSSION TITLE
Birdseye works.  Live view does not work. Recordings do work.

### DISCUSSION THREAD

**Discussion by tlundste** [blakeblackshear/frigate#15079] [Ask A Question] [answered]
Frigate 0.14.1 running in Docker on Ubuntu 24.04 LTS.
What I have changed:
- I moved my entire docker system, and several running containers, including Frigate, from an Ubuntu 20.04 LTS install on one IP to Ubuntu 24.04 LTS on a different IP.

I have three cameras: an Amcrest doorbell camera, and two Reolink E1 Zoom cameras.
Frigate works to record all cameras on the 24.04 install, just like it did before on the 20.04 install, complete with object detection, event processing, etc.
Birdseye works as it did... for all cameras, including motion events playing in the inset window, and new events populating above them.
From Birdseye...
- if I select the Amcrest doorbell camera... all is fine.. can even turn on the sound and listen.
- if I select either of the Reolink cameras, I just get a spinny... nothing ever shows up.  The little picture-pop-out icon disappears after a second or two, but that's the only thing that changes.  If I select History, I am still able to see all of the newly recorded history just fine... just can't watch the current live stream.  In the logs, I see a "frigate.api.app ERROR : Failed to fetch streams from go2rtc" at the same time I see a GET get logged for the camera and the IP:port of the Frigate server.

All of this was working fine (except I was never able to get audio from the two Reolinks cameras in live view, only in recorded content) on the old 20.04 install.
What am I not checking?

**Comment by NickM-27** [comment]
Need to see go2rtc logs

**Comment by tlundste** [comment]
Nothing exciting there... do you agree? Do I need to enable some higher level of logging?
```
2024-11-19 18:19:41.243855403  [INFO] Preparing new go2rtc config...
2024-11-19 18:19:41.743949972  [INFO] Starting go2rtc...
2024-11-19 18:19:41.855993145  18:19:41.855 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-19 18:19:41.855997534  18:19:41.855 INF config path=/dev/shm/go2rtc.yaml
2024-11-19 18:19:41.862477459  18:19:41.862 INF [api] listen addr=:1984
2024-11-19 18:19:41.862734799  18:19:41.862 INF [rtsp] listen addr=:8554
2024-11-19 18:19:41.863279888  18:19:41.863 INF [webrtc] listen addr=:8555/tcp
2024-11-19 18:19:51.244022051  [INFO] Starting go2rtc healthcheck service...
```

Also... after my initial post, I saw someone having issues with a reo-link doorbell (mine are not doorbells), but I followed the link suggested in that one, too, and made a change (see below): no difference in behavior: birdseye works, recording works (I didn't change the path in the camera to the 127.0.0.1 stuff, though), and live view does not work, just like before.
```
go2rtc:
  streams:
    frontdoor:
      - rtsp://user:somepass@doorbell_ip:554/cam/realmonitor?channel=1&subtype=0
    reo-main:
#      - rtsp://user:somepass@main-reo_ip:554/h264Preview_01_main
      - "ffmpeg:http://main-reo_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=somepass#video=copy#audio=copy#audio=opus"
    reo-basement:
      - rtsp://user:somepass@basement-reo_ip:554/h264Preview_01_main
```

**Reply by NickM-27** [reply]
what is the full config

**Comment by tlundste** [comment]
I am hoping this is sufficiently sanitized.
mqtt_ip, doorbell_ip, and the frigate docker IP are all on the same primary network.
The cameras at basement_ip and main_ip are on a different subnet that has no access to the internet... if that matters at all.  The docker IP has full access to that camera subnet, though.

```
mqtt:
  host: mqtt_ip
detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
    frontdoor:
      - rtsp://user:password@doorbell_ip:554/cam/realmonitor?channel=1&subtype=0
    reo-main:
#      - rtsp://user:password@main_ip:554/h264Preview_01_main
      - "ffmpeg:http://main_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    reo-basement:
      - rtsp://user:password@basement_ip:554/h264Preview_01_main
cameras:
  frontdoor:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -codec:a aac
      inputs:
        - path: rtsp://user:password@doorbell_ip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - detect
            - rtmp
            - record
    audio:
      enabled: true
      listen:
        - bark
      filters:
        bark:
          threshold: 0.8
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - dog
        - person
        - car
      filters:
        car:
          mask:
            - 594,687,1260,695,1314,739,1625,755,1636,446,1729,386,1584,52,1737,53,1733,0,1625,0,1521,0,1297,169,1059,95,876,69,703,146,669,307,624,278,495,310,437,369
            - 191,1080,139,812,1140,1080
            - 1576,1080,1202,1080,1142,936,933,820,734,778,877,732,1137,748,1613,814
          threshold: 0.65
        person:
          mask:
            - 594,687,1260,695,1314,739,1625,755,1636,446,1729,386,1584,52,1737,53,1733,0,1625,0,1521,0,1297,169,1059,95,876,69,703,146,669,307,624,278,495,310,437,369
            - 358,965,537,887,522,861,348,869
            - 1072,0,1288,0,1290,1080,1081,1080
        dog:
          mask:
            - 594,687,1260,695,1314,739,1625,755,1636,446,1729,386,1584,52,1737,53,1733,0,1625,0,1521,0,1297,169,1059,95,876,69,703,146,669,307,624,278,495,310,437,369
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: all
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    motion:
      mask: 
        0.321,0.617,0.615,0.619,0.849,0.609,0.854,0.416,0.901,0.357,0.825,0.048,0.875,0.064,0.908,0.063,0.903,0,0.846,0,0.792,0,0.676,0.156,0.543,0.051,0.397,0.078,0.34,0.156,0.343,0.257,0.325,0.257,0.26,0.256,0.217,0.325
    zones:
      fntdr_drvwy:
        coordinates: 0.458,0.68,0.324,0.747,0.319,0.66,0.375,0.656
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - dog
          - person
      fntdr_prch:
        coordinates: 0.099,1,0.072,0.752,0.594,1
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
      fntdr_strt:
        coordinates: 
          0.575,0.688,0.604,0.692,0.608,0.608,0.532,0.606,0.393,0.629,0.317,0.622,0.322,0.652,0.379,0.662,0.468,0.675
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - person
      fntdr_wlkwy:
        coordinates: 
          0.585,0.856,0.64,0.977,0.365,0.944,0.404,0.846,0.41,0.775,0.334,0.752,0.376,0.721,0.482,0.756
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
      fntdr_yard:
        coordinates: 
          0.821,1,0.626,1,0.595,0.867,0.486,0.759,0.382,0.72,0.457,0.678,0.592,0.693,0.84,0.754
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
          - car
  reo-main:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -codec:a aac
      inputs:
        - path: rtsp://user:password@main_ip:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: all
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2    motion:
      mask: 0.571,0.037,0.569,0,0.472,0,0.47,0.037
  reo-basement:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -codec:a aac
      inputs:
        - path: rtsp://user:password@basement_ip:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: all
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    motion:
      mask:
        - 877,39,876,0,582,0,585,40
    zones: {}
version: 0.14
```

**Comment by tlundste** [comment]
I tried substituting the 127.0.0.1 path in the camera definition:
```
      inputs:
        - path: rtsp://user:password@main_ip:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
````
became...
```
      inputs:
        - path: rtsp://127.0.0.1:8554/reo-main
#        - path: rtsp://user:password@main_ip:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
```
And my docker compose is showing 8554 for the port...
```
   ports:
     - "5000:5000"
     - "1935:1935" # RTMP feeds
     - "8554:8554" # RTSP feeds
 ```

The result of that caused my (what I thought was my) Birdseye view to not have any feed for that camera.  So, to be clear... "birdseye", as I understand it, is the page of groups of cameras visible when you click on the little frigate bird symbol in the upper left of the screen, and that is the feed from go2rtc... and "live view" is viewable when you click on any one of those smaller displays on the birdseye screen (which takes it's feed from the "cameras:" definition of the config.yaml)... is that correct?
I also tried replacing the relevant input_args statement for that camera: entry to be `input_args: preset-rtsp-restream` when the inputs: path: was set to the 127.0.0.1 entry but that had no effect, either
I also tried to use VLC to go to my frigate servers IPs on 8554 to view the rtsp stream, and got an error:
```
Your input can't be opened:
VLC is unable to open the MRL 'rtsp://frigate_ip:8554/reo-main'. Check the log for details.
```
Found where to create logs for that activity... nothing really helpful in there that I could see.

Still...
-- there is a feed visible in what I call the birdseye view.. and there is no feed visible in the live view for the two reo-xxxx cameras defined, when the config is set to the full config above (as well as reversing the commented section of the "streams:" portion of reo-main).
-- there is no feed for either if I change the "cameras: reo-main: inputs: section as listed in this post.

Still struggling to figure out what's wrong.

**Comment by tlundste** [comment]
Also... for kicks and grins, using the full config post above:
I tried to go to rtsp://frigate_ip:8554/frontdoor from my Windows based VLC app... and that worked (amcrest doorbell).
I tried to go to rtsp://frigate_ip:8554/reo-basement, and that did not work (same error as reo-main).

I then changed my Frigate config.yaml file... I changed the cameras: input: paths: to use the 127.0.0.1 for "frontdoor".  I didnt' change any of the input_args for this test.  I could see the acmrest camera in the birdseye, and in the live view (with audio), and in recorded history (not sure if I'm getting audio recorded or not, yet... just testing it.
So, the go2rtc, and recording portions seems to work just fine for the amcrest.  I'm missing something to get it to work with the Reo.

**Comment by tlundste** [comment]
Lastly, I investigated the camera and found port 1935 was not enabled.
I first changed the frigate config.yaml go2rtc: stream: statement for the reo-main to use 554.  No joy.
I then changed the config.yaml statement back to 1935, and enabled 1935 on the camera: No joy.
I then updated the camera: input: line to use 127.0.0.1.  No joy.
I then added the preset-rtsp-restream statement in (removing the other input_args: statements).  No joy
All of the No joy attempts, above, resulted in no feed for Birdseye, and no feed for live view for reo-main, and no recordings.

I went back to the full config post as listed above... back to a feed for birdseye, and no feed for live view, and a working feed for recording.

**Reply by NickM-27** [reply]
So what is the config now? Seems like some things were being changed that should be left alone

**Comment by tlundste** [comment]
Nothing has changed with regard to the problem cameras.  I was trying different things to get it to work and to understand (or confirm my understanding of) things, and documented what I tried along the way, but with no changes to the behavior, I put it back to the full code listing above.  The only thing that has changed, and is still working, is I replaced the cameras: frontdoor: input: path to use the 127.0.0.1 that is documented for Reo cameras, just to see if it worked, and it did.  But, that "frontdoor" doorbell camera is Amcrest, not Reo, and has been working just fine all along.
So, to recap...
What is broken? My "live view" video for my Reolink cameras: reo-main and reo-basement (what I understand is birdseye works fine, as well as recording, it's just the live view that has a spinny arrow that never turns into a video feed).
What changed to cause the failure?  I upgraded my mini PC docker setup, initially running on Ubuntu 20.04 on an Intel NUC and moved to Ubuntu 24.04 on a Beelink mini PC... IP address changed as part of this.
After finding everything I could think of where my old IP needed to change to my new IP, all but the live view for the Reolink cameras works.

Oh... yeah... I also found that the Reo cameras were not presenting on port 1935, so, that has been changed on reo-main... I have enabled port 1935 (I didn't disable things) on the camera, itself.  Because the recommended string for the go2rtc includes "port=1935" I thought I should verify that it is actually allowed at the camera, and it wasn't, so I enabled it.

**Reply by tlundste** [reply]
@NickM-27 
You ask me questions.  Do you have suggestions what I might check that might cause this; some method that I might try (short of spinning up a whole new Frigate instance from scratch) that would help me figure out what is wrong?

**Reply by NickM-27** [reply]
What is the full config now?

**Reply by tlundste** [reply]
Not much different than before.  Like I said, I changed the Amcrest doorbell setup to be the same as what is recommended for the Reo-link cameras, and it works (and I left it that way, reflected in this config), but neither my original setup, nor the recommended setup for the Reolink cameras works as expected.  Birdseye works.  Recording works.  Live view does not (for the Reolinks).
Here is the current running config, with "user" and "password" real values simply replaced with "user" and "password", here.
```
mqtt:
  host: mqtt_ip
detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
    frontdoor:
      - rtsp://user:password@doorbell_ip:554/cam/realmonitor?channel=1&subtype=0
    reo-main:
#      - rtsp://user:password@main_ip:554/h264Preview_01_main
      - "ffmpeg:http://main_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    reo-basement:
      - rtsp://user:password@basement_ip:554/h264Preview_01_main
cameras:
  frontdoor:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -codec:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
#        - path: rtsp://user:password@doorbell_ip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - audio
            - detect
            - rtmp
            - record
    audio:
      enabled: true
      listen:
        - bark
      filters:
        bark:
          threshold: 0.8
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - dog
        - person
        - car
      filters:
        car:
          mask:
            - 594,687,1260,695,1314,739,1625,755,1636,446,1729,386,1584,52,1737,53,1733,0,1625,0,1521,0,1297,169,1059,95,876,69,703,146,669,307,624,278,495,310,437,369
            - 191,1080,139,812,1140,1080
            - 1576,1080,1202,1080,1142,936,933,820,734,778,877,732,1137,748,1613,814
          threshold: 0.65
        person:
          mask:
            - 594,687,1260,695,1314,739,1625,755,1636,446,1729,386,1584,52,1737,53,1733,0,1625,0,1521,0,1297,169,1059,95,876,69,703,146,669,307,624,278,495,310,437,369
            - 358,965,537,887,522,861,348,869
            - 1072,0,1288,0,1290,1080,1081,1080
        dog:
          mask:
            - 594,687,1260,695,1314,739,1625,755,1636,446,1729,386,1584,52,1737,53,1733,0,1625,0,1521,0,1297,169,1059,95,876,69,703,146,669,307,624,278,495,310,437,369
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: all
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    motion:
      mask: 
        0.321,0.617,0.615,0.619,0.849,0.609,0.854,0.416,0.901,0.357,0.825,0.048,0.875,0.064,0.908,0.063,0.903,0,0.846,0,0.792,0,0.676,0.156,0.543,0.051,0.397,0.078,0.34,0.156,0.343,0.257,0.325,0.257,0.26,0.256,0.217,0.325
    zones:
      fntdr_drvwy:
        coordinates: 0.458,0.68,0.324,0.747,0.319,0.66,0.375,0.656
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - dog
          - person
      fntdr_prch:
        coordinates: 0.099,1,0.072,0.752,0.594,1
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
      fntdr_strt:
        coordinates: 
          0.575,0.688,0.604,0.692,0.608,0.608,0.532,0.606,0.393,0.629,0.317,0.622,0.322,0.652,0.379,0.662,0.468,0.675
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - person
      fntdr_wlkwy:
        coordinates: 
          0.585,0.856,0.64,0.977,0.365,0.944,0.404,0.846,0.41,0.775,0.334,0.752,0.376,0.721,0.482,0.756
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
      fntdr_yard:
        coordinates: 
          0.821,1,0.626,1,0.595,0.867,0.486,0.759,0.382,0.72,0.457,0.678,0.592,0.693,0.84,0.754
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
          - car
  reo-main:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -timeout 5000000 -use_wallclock_as_timestamps 1
#      input_args: preset-rtsp-stream
      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -codec:a aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/reo-main
        - path: rtsp://user:password@main_ip:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: all
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    motion:
      mask: 0.571,0.037,0.569,0,0.472,0,0.47,0.037
  reo-basement:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy -codec:a aac
      inputs:
        - path: rtsp://user:password@basement_ip:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: all
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    motion:
      mask:
        - 877,39,876,0,582,0,585,40
    zones: {}
version: 0.14
```
