### DISCUSSION TITLE
[Bug]: Memory leak 0.15.0-beta1 ?

### DISCUSSION THREAD

**Discussion by rolf-tx** [blakeblackshear/frigate#15081] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

There may possibly be a memory leak in frigate 0.15.0-beta1.
In 7 days the memory usage for frigate addon in HA increased from 13% to 30%. 
Doing a restart from inside frigate gui reduced the memory usage back to 13%.

This is on x86 system with 8GB.
3 cameras, coral tpu.

### Steps to reproduce

1.Monitor memory usage
2.
3.
...

### Version

 0.15.0-33825f6

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: ha.x.x
  user: frigate-mqtt
  password: xxxxx
database:
  path: /config/frigate.db


go2rtc:
  streams:
    garage:
      - rtsp://y:x.x@hikvision1.x.x:554/Streaming/Channels/101/
    driveway:
      - rtsp://y:xxxx@hikvision2.x.x:554/Streaming/Channels/101/
    frontentry:
      - rtsp://y:xxx@hikvision3.x.x:554/Streaming/Channels/101/
    garage_sub:
      - rtsp://y:xxx@hikvision1.x.x:554/Streaming/Channels/102/
    driveway_sub:
      - rtsp://y:xxx@hikvision2.x.x:554/Streaming/Channels/102/
    frontentry_sub:
      - rtsp://y:xxx@hikvision3.x.x:554/Streaming/Channels/102/

cameras:
  garage:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 6
      width: 640
      height: 480
    birdseye:
      order: 2
    motion:
      mask: 0.518,0.122,0.517,0.069,0.1,0.071,0.037,0.072,0.037,0.122


  driveway:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 6
      width: 640
      height: 360
    birdseye:
      order: 3
    motion:
      mask: 0.043,0.069,0.283,0.067,0.284,0.106,0.041,0.105
    zones:
      zone_driveway_pavement:
        coordinates: 
          0.036,0.999,0.117,0.585,0.192,0.442,0.225,0.296,0.544,0.262,0.602,0.298,0.726,0.293,0.85,0.399,0.842,0.473,0.989,0.783,0.991,1,0.499,1
        inertia: 3
    objects:
      filters:
        car:
          mask: 0.911,0.252,1,0.258,1,0.078,0.907,0.073
          max_area: 85000
          threshold: 0.85
        person:
          threshold: 0.82
    review:
      alerts:
        required_zones: zone_driveway_pavement

  frontentry:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/frontentry
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontentry_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 6
      width: 480
      height: 640
    motion:
      threshold: 50
      mask:
        - 0.131,0.164,0.295,0.146,0.304,0.084,0.131,0.081
        - 0,0.084,0.067,0.083,0.152,0.083,0.306,0.084,0.542,0.089,0.54,0,0.375,0,0,0
        - 0.073,0.167,0,0.155,0,0.661,0.184,0.537
    zones:
      zone_frontentry:
        coordinates: 0.423,1,0.723,0.823,0.725,0.275,0.301,0.247,0,0.964
        inertia: 3
    birdseye:
      order: 1
    objects:
      filters:
        dog:
          threshold: 0.85
          #max_area: 20000
        person:
          threshold: 0.85
          #max_area: 35000
        car:
          threshold: 0.85
          #mask:
          #- 0,640,50,640,228,640,480,640,480,574,480,218,0,225
    review:
      alerts:
        required_zones: zone_frontentry



detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - face
    - car
    - motorcycle
    - bicycle
    - boat
    - amazon
    - usps
    - fedex
    - ups
    - dog
    - cat
    - raccoon
    - fox
    - squirrel
    - rabbit
    - package
    - waste_bin

timestamp_style:
  position: tl
model:
  path: plus://cxyznxbxbx
  
  

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
#  hwaccel_args: preset-intel-vaapi
#  hwaccel_args: '""'

record:
  enabled: true
  retain:
    days: 15
    mode: all
  alerts:
    retain:
      days: 30
      mode: active_objects
  detections:
    retain:
      days: 30
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 15

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720
  restream: true

version: 0.15-0

semantic_search:
  enabled: false
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
N/A HA addon
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Hikvision 

### Screenshots of the Frigate UI's System metrics pages

N/A
