### DISCUSSION TITLE
Memory Allocations in Frigate's Docker Container

### DISCUSSION THREAD

**Discussion by aayush-eatclub** [blakeblackshear/frigate#15084] [Ask A Question] [answered]
I have defined `shm_size` and docker resource limits in` docker_compose.yml ` as given below.
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "4096mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /home/outletmanager/outletvideocam:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5001:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
        resources:
            limits:
              cpus: "2"
              memory: 4000M
            reservations:
              cpus: "1"
              memory: 2000M

```
I wanted to know whether shm_size and cache is included in docker's memory limit or it is a different allocation ? In simple terms what can be maximum memory usage by Frigate - `SHM_size + docker limit + temp_cache` or just `docker limit`.
