### DISCUSSION TITLE
[Camera Support]: Discoloration / Artifacts in live view but not recording

### DISCUSSION THREAD

**Discussion by walmartshopper** [blakeblackshear/frigate#15111] [Camera Support]
### Describe the problem you are having

I only have one camera set up.  I am using one stream for both detect and record.  All recorded videos look OK, but the live view has a white triangle on the right side.  All the colors inside the triangle are off, and the rest of the image has some splotchy discoloration.  I believe it started happening with the 0.14 update, and is still present on the current dev build.  I tried setting the camera stream to h264 and h265, changed the frigate hwaccel_args between preset-vaapi, preset-intel-qsv-h264, and preset-intel-qsv-h265 and no change.  Also happens with both cpu and openvino detector.  Frigate is installed using docker-compose running directly on a proxmox host  (not in a vm or lxc).

This is the recording which looks normal:
![Screenshot_20241120_192322](https://github.com/user-attachments/assets/7950e74e-d848-4c95-bf86-8206f7e09a3a)

This is the live view:
![Screenshot_20241120_164306](https://github.com/user-attachments/assets/ef99360d-292c-4e50-b016-0987ccb58db3)

### Version

0.15.0-ff92b13 (also happened in 0.14 stable)

### What browser(s) are you using?

Brave 1.73.89 Chromium: 131.0.6778.69 (same result in Chromium and Firefox)

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  enabled: false

detectors:
  driveway:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

#detectors:
#  driveway:
#    type: cpu
#    num_threads: 2

ffmpeg:
  hwaccel_args: preset-intel-qsv-h265

cameras:
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@driveway/1/h264major
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - bicycle
      filters:
        person:
          mask:
            - 596,691,622,782,458,931,259,959,136,591,305,437,452,525
    detect:
      enabled: true
    motion:
      threshold: 25
      contour_area: 10
      frame_height: 100
      mask:
        - 0,1520,344,1520,0,1177
        - 829,0,0,0,0,162
        - 271,688,416,766,240,902,70,953,28,764,158,691

      improve_contrast: true
record:
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 15
    pre_capture: 1
    post_capture: 1
  detections:
    retain:
      days: 15
    pre_capture: 1
    post_capture: 1
timestamp_style:
  position: tl
  format: '%Y-%m-%d %H:%M:%S'
  thickness: 1
  effect: shadow

snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 15

birdseye:
  enabled: false

version: 0.15-0
```

### Relevant Frigate log output

```shell
2024-11-21 00:54:09.372564421  [INFO] Preparing Frigate...
2024-11-21 00:54:09.379918240  [INFO] Starting Frigate...
2024-11-21 00:54:11.541985040  [2024-11-21 00:54:11] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-21 00:54:11.558743797  [2024-11-21 00:54:11] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-21 00:54:17.062232012  [2024-11-21 00:54:17] frigate.config.config          WARNING : Customizing more than a detector model path is unsupported.
2024-11-21 00:54:17.064502926  [2024-11-21 00:54:17] frigate.app                    INFO    : Starting Frigate (0.15.0-ff92b13)
2024-11-21 00:54:17.070220169  [2024-11-21 00:54:17] peewee_migrate.logs            INFO    : Starting migrations
2024-11-21 00:54:17.070500908  [2024-11-21 00:54:17] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-11-21 00:54:17.077830286  [2024-11-21 00:54:17] frigate.app                    INFO    : Recording process started: 339
2024-11-21 00:54:17.085002079  [2024-11-21 00:54:17] frigate.app                    INFO    : Review process started: 348
2024-11-21 00:54:17.087435406  [2024-11-21 00:54:17] frigate.app                    INFO    : go2rtc process pid: 97
2024-11-21 00:54:17.100257076  [2024-11-21 00:54:17] detector.driveway              INFO    : Starting detection process: 355
2024-11-21 00:54:17.109507885  [2024-11-21 00:54:17] frigate.app                    INFO    : Output process started: 370
2024-11-21 00:54:17.158085746  [2024-11-21 00:54:17] frigate.app                    INFO    : Camera processor started for driveway: 401
2024-11-21 00:54:17.187603874  [2024-11-21 00:54:17] frigate.app                    INFO    : Capture process started for driveway: 407
2024-11-21 00:54:17.389866435  [2024-11-21 00:54:17] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2024-11-21 00:54:17.490833631  [2024-11-21 00:54:17] frigate.api.fastapi_app        INFO    : FastAPI started
```

### Relevant go2rtc log output

```shell
2024-11-21 00:54:09.371376263  [INFO] Preparing new go2rtc config...
2024-11-21 00:54:09.800554250  [INFO] Starting go2rtc...
2024-11-21 00:54:09.898649774  00:54:09.898 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-21 00:54:09.898654246  00:54:09.898 INF config path=/dev/shm/go2rtc.yaml
2024-11-21 00:54:09.899064574  00:54:09.899 INF [rtsp] listen addr=:8554
2024-11-21 00:54:09.899192826  00:54:09.899 INF [api] listen addr=:1984
2024-11-21 00:54:09.899235184  00:54:09.899 INF [webrtc] listen addr=:8555/tcp
2024-11-21 00:54:19.372268477  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:admin@driveway/1/h264major
ffprobe version n7.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.1 (GCC) 20240910
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[rtsp @ 0x60cccef0f100] Error parsing AU headers
^C  Last message repeated 206 times
```

### Frigate stats

```json
{"cameras":{"driveway":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":27.3,"detection_enabled":true,"pid":401,"capture_pid":407,"ffmpeg_pid":417,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"driveway":{"inference_speed":12.86,"detection_start":0.0,"pid":355}},"detection_fps":27.3,"gpu_usages":{"intel-qsv":{"gpu":"11.15%","mem":"-%","clients":{"355":"64.83%","417":"0.82%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"25.6","mem":"32.9"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"97":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"105":{"cpu":"3.5","cpu_average":"0","mem":"2.8","cmdline":"python3 -u -m frigate"},"110":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"130":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: master process nginx"},"154":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"155":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"156":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"221":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"222":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"291":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"339":{"cpu":"0.1","cpu_average":"0","mem":"1.2","cmdline":"frigate.recording_manager"},"348":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.review_segment_manager"},"355":{"cpu":"33.8","cpu_average":"4","mem":"1.9","cmdline":"frigate.detector.driveway"},"370":{"cpu":"2.1","cpu_average":"0","mem":"1.2","cmdline":"frigate.output       "},"376":{"cpu":"0.8","cpu_average":"0","mem":"0.4","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2592x1520 -i pipe: -threads 1 -f mpegts -s 1227x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"401":{"cpu":"35.7","cpu_average":"4","mem":"1.5","cmdline":"frigate.process:driveway"},"407":{"cpu":"3.5","cpu_average":"3","mem":"1.2","cmdline":"frigate.capture:driveway"},"417":{"cpu":"7.5","cpu_average":"7","mem":"1.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -load_plugin hevc_hw -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v hevc_qsv -user_agent FFmpeg Frigate/0.15.0-ff92b13 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@driveway/1/h264major -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=2592:h=1520:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"10561":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash"},"10626":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"10637":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":8489,"version":"0.15.0-ff92b13","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":301290.8,"used":211616.9,"free":74297.9,"mount_type":"ext4"},"/media/frigate/clips":{"total":301290.8,"used":211616.9,"free":74297.9,"mount_type":"ext4"},"/tmp/cache":{"total":976.6,"used":1.4,"free":975.1,"mount_type":"tmpfs"},"/dev/shm":{"total":1024.0,"used":930.9,"free":93.1,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1732158946},"processes":{"recording":{"pid":339},"review_segment":{"pid":348},"go2rtc":{"pid":97}}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

JideTech 5MP POE Outdoor IP Security Camera

### Screenshots of the Frigate UI's System metrics pages

![Screenshot_20241120_192045](https://github.com/user-attachments/assets/2eecbeee-5df6-4f41-b01e-5777f7a95f3c)
![Screenshot_20241120_191941](https://github.com/user-attachments/assets/99ac78c9-7014-426b-828f-4eacd724bdf0)
