### DISCUSSION TITLE
passthrough video using go2rtc

### DISCUSSION THREAD

**Discussion by jamesonuk** [blakeblackshear/frigate#15113] [Ask A Question]
This is a bit of a follow on to https://github.com/blakeblackshear/frigate/discussions/12123
I have had go2rtc setup and I get streams in HA and all is good.   I did however have a bit of an issue and started digging into the details and noticed the feed coming out of go2rtc is not the same as the one coming out the camera

The camera is outputting at 25fps but the go2rtc feed is outputting at 29.97 fps so the video is obviously being transcoded.
Is there a way to just get go2rtc to passthrough the video feed without transcoding (which should reduce the CPU usage)?

## Camera feed
![direct](https://github.com/user-attachments/assets/8276ef4b-c394-4c51-b5db-56d2f2b2cf1c)

## go2rtc feed
![go](https://github.com/user-attachments/assets/360faf3d-9c4b-4342-977b-72ad26829ef0)

**Comment by hawkeye217** [comment]
What is your go2rtc config?

**Reply by jamesonuk** [reply]
> What is your go2rtc config?

nothing really.    If I change resolution on camera this gets reflected but fps always seems to end up as 29

```
go2rtc:
  streams:
    landing_camera_frigate:
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@landing-camera/Preview_01_main
 ```

and camera config is then just 

```
cameras:
  landing_camera_frigate:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@landing-camera/Preview_01_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/landing_camera_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
```
