### DISCUSSION TITLE
[Support]: Packages not detected

### DISCUSSION THREAD

**Discussion by USER19464727** [blakeblackshear/frigate#15124] [General Support]
### Describe the problem you are having

I have Frigate working well and I am now using Frigate+. It is successfully detecting people, cars, FedEx, license plates, etc. I even have Double-Take and codeproject.ai involved and updating the label for people to assign a name to them in Frigate. However, the one thing it won't do is detect a package. For the life of me I'm not sure what is wrong. I have "package" as part of the objects to track. It will put a motion box around it but never tracks it as an object. I've tried adjusting the min_area, min_ratio, max_ratio, min_score, threshold. I've tried putting the box in different positions in frame. It's a large-enough package that it should be recognized (see image).
![image1](https://github.com/user-attachments/assets/3969e9e8-e9d4-4733-84e9-8f9a431d26f3)
![image2](https://github.com/user-attachments/assets/e18b3179-5e03-4fdd-b5ac-52b98ce92f16)

### Version

0.14.1

### What browser(s) are you using?

Brave 1.73.89

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: (REDACTED)
  password: (REDACTED)

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://(REDACTED)

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 700
  listen:
    - speech
    - scream
    - yell
    - crying
    - bark
    - fire_alarm

birdseye:
  enabled: true
  restream: false
  mode: objects
  quality: 31

ffmpeg:
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-aac

motion:
  enabled: true

detect:
  enabled: true
  fps: 5
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    # People
    - person
    - face
    # Vehicles
    - car
    - bicycle
    - motorcycle
    - license_plate
    # Animals
    - deer
    - dog
    - cat
    # Deliveries
    - amazon
    - fedex
    - usps
    - ups
    - package
  filters:
    dog:
      min_score: 0.7
      threshold: 0.9
    cat:
      min_score: 0.65
      threshold: 0.8
    face:
      min_score: 0.7
    package:
      min_area: 0
      min_ratio: 0
      max_ratio: 1000
      min_score: 0
      threshold: 0.2
    license_plate:
      min_score: 0.6
    amazon:
      min_score: 0.75
    ups:
      min_score: 0.75
    fedex:
      min_score: 0.75
    person:
      min_score: 0.65
      threshold: 0.85
    car:
      min_score: 0.65
      threshold: 0.90

review:
  alerts:
    labels:
      - person
      - face
      - car
      - bicycle
      - motorcycle
      - license_plate
      - deer
      - amazon
      - fedex
      - usps
      - ups
      - package
      - crying # audio
      - yell # audio
      - scream # audio
  detections:
    labels:
      - bark # audio
      - fire_alarm # audio
      - speech # audio

go2rtc:
  streams:
    doorbell_latest: #for double-take full-res snapshots
      - onvif://(REDACTED):(REDACTED)@192.168.50.219:8000?subtype=MediaProfile00000&snapshot
    doorbell_main:
      - rtsp://(REDACTED):(REDACTED)@192.168.50.219:554/Preview_01_main#backchannel=0
      - rtsp://(REDACTED):(REDACTED)@192.168.50.219:554/Preview_01_sub
      - ffmpeg:doorbell_main#audio=opus#hardware
    doorbell_sub:
      - rtsp://(REDACTED):(REDACTED)@192.168.50.219:554/Preview_01_sub
      - ffmpeg:doorbell_sub#audio=opus#hardware

record:
  enabled: true
  retain:
    days: 7
    mode: motion

snapshots:
  enabled: true
  bounding_box: true
  crop: true
  height: 200
  retain:
    default: 30
  quality: 100

cameras:
  doorbell:
    enabled: true
    ui:
      order: 0
    audio:
      enabled: true
      min_volume: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          roles:
            - detect
            - audio
    objects:
      mask: 
        0.279,0.372,0.481,0.439,0.48,0.611,0.399,0.615,0.412,0.772,0.296,0.776,0.268,0.57
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - package
        required_zones:
          - entryway
          - top-of-steps
      detections:
        labels: []
    motion:
      mask: 0,0.051,1,0.051,1,0,0,0
    zones:
      top-of-steps:
        coordinates: 0,0.915,0.163,0.747,0.861,0.678,1,0.693,1,1,0,1
        loitering_time: 0
        inertia: 3
      entryway:
        coordinates: 0.837,0.055,1,0.261,1,1,0.177,1,0.103,0.483,0.23,0.057
        loitering_time: 0
        inertia: 3
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Doorbell camera is WiFi, everything else wired

### Camera make and model

Reolink WiFi Doorbell
