### DISCUSSION TITLE
[Config Support]: ERROR:frigate.plus:Plus API Key is not formatted correctly.

### DISCUSSION THREAD

**Discussion by jchrisos1** [blakeblackshear/frigate#15125] [Config Support] [answered]
### Describe the problem you are having

I've followed the [documentation ](https://docs.frigate.video/integrations/plus)to enable Frigate+ but no matter what I try, frigate isn't accepting my API key. In my frigate logs I get this error:
`ERROR:frigate.plus:Plus API Key is not formatted correctly.`

I'm running a bare metal Ubuntu system (bookworm/sid) with frigate running in a docker container. I've tried adding the PLUS_API_KEY to my docker compose file two ways (with an '=' and with a ':') as outlined [here](https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/). It still doesn't appear to be working. I can even SSH into my docker and see my key yet the frigate UI isn't showing me anything related to Frigate+. I do have snapshots enabled.

When I say I've tried with an '=' and ':' this is what I mean (from docker compose):
`- PLUS_API_KEY=[key]`
and
`- PLUS_API_KEY: "[key]"`

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
#logger:
#  default: debug # Available log levels are: debug, info, warning, error, critical

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  enabled: true
  host: 192.168.50.50
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: '{FRIGATE_MQTT_USER}'
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: '{FRIGATE_MQTT_PASSWORD}'

#go2rtc:
#  streams:
#    street:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.11:554/cam/realmonitor?channel=1&subtype=0
#    front_door:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.13:554/cam/realmonitor?channel=1&subtype=0
#    driveway:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.12:554/cam/realmonitor?channel=1&subtype=1
#    back_door:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.14:554/cam/realmonitor?channel=1&subtype=1
#    tree_cam:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_AMCREST_PASSWORD}@192.168.50.16:554/cam/realmonitor?channel=1&subtype=1
#live:
#  stream_name:
#    - street
#    - front_door
#    - driveway
#    - back_door
#    - tree_cam

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - truck
    - bus
    - cat
    - dog
    - baseball bat
    - baseball glove
    - knife

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: false)
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 90
    # Optional: Per object retention days
    #objects:
    #  person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: 70)
  quality: 100
cameras:
  street:
    enabled: true
    webui_url: http://192.168.50.11/
    ffmpeg:
#      hwaccel_args: preset-vaapi # Use Intel NUC iGPU (optional)
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 15
    review:
      alerts:
        labels: [] # We don't want to review alerts. They should only be detections. https://docs.frigate.video/configuration/review/
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    motion:
      mask: 0,0.346,0.804,0.253,0.799,0,1,0,1,1,0,1
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
    objects:
      filters:
        car: {}
      mask: 0,0.37,0.81,0.266,0.798,0,1,0,1,1,0,1
  front_door:
    enabled: true
    webui_url: https://192.168.50.13/
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    detect:
      enabled: true
      width: 480
      height: 704
      fps: 15
    motion:
      mask: 0.575,0.049,0.854,0.045,0.856,0.082,0.58,0.082
    objects:
      filters:
        car:
          mask: 0.361,0.336,0.739,0.298,0.729,0.207,0.353,0.216,0,0.228,0,0,1,0,1,1,0,1,0,0.375
  driveway:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-vaapi # Use Intel NUC iGPU (optional)
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 15
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    motion:
      mask:
        - 0.781,0.044,0.915,0.042,0.915,0.077,0.781,0.077
        - 0.832,0.657,1,0.648,1,1,0.803,1,0.797,0.821,0.839,0.788
        - 0,0.845,0.133,0.926,0.238,0.969,0.327,0.992,0.332,1,0,1
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask:
            - 0.127,0,0.128,0.222,0.366,0.231,0.428,0.228,0.537,0.235,0.536,0
            - 0.3,0.295,0.409,0.297,0.41,0.347,0.299,0.349
            - 0.722,0.905,1,0.902,1,1,0.728,1
  back_door:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-vaapi # Use Intel NUC iGPU (optional)
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.14:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.50.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 480
      height: 704
      fps: 15
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    motion:
      mask: 0.584,0.048,0.583,0.082,0.862,0.082,0.859,0.046
  tree_cam:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-vaapi # Use Intel NUC iGPU (optional)
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_AMCREST_PASSWORD}@192.168.50.16:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_AMCREST_PASSWORD}@192.168.50.16:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 15
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    objects:
      filters:
        person:
          mask:
            - 0.409,0.521,0.516,0.518,0.517,0.59,0.405,0.596
            - 0.66,0.53,0.717,0.529,0.723,0.579,0.657,0.579
    motion:
      mask: 0.753,0.043,0.905,0.042,0.906,0.088,0.754,0.087
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
version: 0.14
```

### Relevant Frigate log output

```shell
2024-11-21 23:51:25.703986185  [INFO] Preparing new go2rtc config...
2024-11-21 23:51:25.704359191  [INFO] Preparing Frigate...
2024-11-21 23:51:25.708456340  [INFO] Starting NGINX...
2024-11-21 23:51:25.716031142  [INFO] Starting Frigate...
2024-11-21 23:51:25.860369855  [INFO] Starting certsync...
2024-11-21 23:51:26.074626561  [INFO] Starting go2rtc...
2024-11-21 23:51:26.255633080  23:51:26.255 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-21 23:51:26.255636804  23:51:26.255 INF config path=/dev/shm/go2rtc.yaml
2024-11-21 23:51:26.256015437  23:51:26.255 INF [rtsp] listen addr=:8554
2024-11-21 23:51:26.256164896  23:51:26.256 INF [api] listen addr=:1984
2024-11-21 23:51:26.256230328  23:51:26.256 INF [webrtc] listen addr=:8555/tcp
2024-11-21 23:51:27.134834928  ERROR:frigate.plus:Plus API Key is not formatted correctly.
2024-11-21 23:51:27.142504393  [2024-11-21 23:51:27] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-11-21 23:51:27.142590208  [2024-11-21 23:51:27] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-21 23:51:27.197023484  [2024-11-21 23:51:27] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-21 23:51:27.412197491  [2024-11-21 23:51:27] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
```

### Relevant go2rtc log output

```shell
2024-11-21 23:51:25.703986185  [INFO] Preparing new go2rtc config...
2024-11-21 23:51:26.074626561  [INFO] Starting go2rtc...
2024-11-21 23:51:26.255633080  23:51:26.255 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-21 23:51:26.255636804  23:51:26.255 INF config path=/dev/shm/go2rtc.yaml
2024-11-21 23:51:26.256015437  23:51:26.255 INF [rtsp] listen addr=:8554
2024-11-21 23:51:26.256164896  23:51:26.256 INF [api] listen addr=:1984
2024-11-21 23:51:26.256230328  23:51:26.256 INF [webrtc] listen addr=:8555/tcp
2024-11-21 23:51:35.701786186  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"back_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.1,"capture_pid":479,"detection_enabled":true,"detection_fps":2.2,"ffmpeg_pid":497,"pid":435,"process_fps":14.8,"skipped_fps":0.4},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.1,"capture_pid":476,"detection_enabled":true,"detection_fps":4.7,"ffmpeg_pid":498,"pid":433,"process_fps":14.7,"skipped_fps":0.1},"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.0,"capture_pid":472,"detection_enabled":true,"detection_fps":1.1,"ffmpeg_pid":477,"pid":431,"process_fps":14.7,"skipped_fps":0.4},"street":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.1,"capture_pid":467,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":473,"pid":429,"process_fps":15.0,"skipped_fps":0.0},"tree_cam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.0,"capture_pid":481,"detection_enabled":true,"detection_fps":18.7,"ffmpeg_pid":500,"pid":455,"process_fps":9.1,"skipped_fps":6.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"116":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"123":{"cmdline":"python3 -u -m frigate","cpu":"10.7","cpu_average":"10","mem":"1.8"},"136":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15668":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15724":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"162":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"164":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"165":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"166":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"235":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"337":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.8"},"34":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"381":{"cmdline":"frigate.recording_manager","cpu":"4.8","cpu_average":"4","mem":"1.0"},"382":{"cmdline":"frigate.review_segment_manager","cpu":"2.7","cpu_average":"2","mem":"0.9"},"409":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)","cpu":"1.6","cpu_average":"1","mem":"0.1"},"410":{"cmdline":"frigate.detector.coral","cpu":"67.9","cpu_average":"61","mem":"0.9"},"412":{"cmdline":"frigate.output       ","cpu":"9.4","cpu_average":"9","mem":"1.0"},"429":{"cmdline":"frigate.process:street","cpu":"6.8","cpu_average":"8","mem":"0.9"},"431":{"cmdline":"frigate.process:front_door","cpu":"6.4","cpu_average":"8","mem":"0.9"},"433":{"cmdline":"frigate.process:driveway","cpu":"12.0","cpu_average":"9","mem":"0.9"},"435":{"cmdline":"frigate.process:back_door","cpu":"7.0","cpu_average":"7","mem":"0.9"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"455":{"cmdline":"frigate.process:tree_cam","cpu":"33.9","cpu_average":"25","mem":"0.9"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"467":{"cmdline":"frigate.capture:street","cpu":"3.6","cpu_average":"3","mem":"0.8"},"472":{"cmdline":"frigate.capture:front_door","cpu":"3.7","cpu_average":"3","mem":"0.8"},"473":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.11:554/cam/realmonitor?channel=1&subtype=1 -r 15 -vf fps=15,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.0","cpu_average":"8","mem":"0.4"},"476":{"cmdline":"frigate.capture:driveway","cpu":"3.6","cpu_average":"3","mem":"0.8"},"477":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.13:554/cam/realmonitor?channel=1&subtype=1 -r 15 -vf fps=15,scale_vaapi=w=480:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.8","cpu_average":"7","mem":"0.4"},"479":{"cmdline":"frigate.capture:back_door","cpu":"3.8","cpu_average":"3","mem":"0.8"},"481":{"cmdline":"frigate.capture:tree_cam","cpu":"3.6","cpu_average":"3","mem":"0.8"},"486":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.13:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"4.7","cpu_average":"4","mem":"0.1"},"494":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.11:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/street@%Y%m%d%H%M%S%z.mp4","cpu":"4.5","cpu_average":"4","mem":"0.2"},"497":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.14:554/cam/realmonitor?channel=1&subtype=1 -r 15 -vf fps=15,scale_vaapi=w=480:h=704:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.1","cpu_average":"8","mem":"0.4"},"498":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.12:554/cam/realmonitor?channel=1&subtype=1 -r 15 -vf fps=15,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.8","cpu_average":"7","mem":"0.4"},"500":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.16:554/cam/realmonitor?channel=1&subtype=1 -r 15 -vf fps=15,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"4","mem":"0.3"},"505":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.14:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_door@%Y%m%d%H%M%S%z.mp4","cpu":"4.6","cpu_average":"4","mem":"0.1"},"508":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.12:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"4.5","cpu_average":"4","mem":"0.1"},"509":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.50.16:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/tree_cam@%Y%m%d%H%M%S%z.mp4","cpu":"4.2","cpu_average":"4","mem":"0.1"},"523":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"528":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 480x704 -i pipe: -threads 1 -f mpegts -s 490x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"533":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"538":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 480x704 -i pipe: -threads 1 -f mpegts -s 490x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"543":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"548":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"7982":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"83":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"frigate.full_system":{"cpu":"64.0","mem":"11.9"}},"detection_fps":26.7,"detectors":{"coral":{"detection_start":1732236592.527191,"inference_speed":36.46,"pid":410}},"gpu_usages":{"intel-vaapi":{"gpu":"1.55%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":337},"recording":{"pid":381},"review_segment":{"pid":382}},"service":{"last_updated":1732236593,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":120.8,"mount_type":"tmpfs","total":128.0,"used":7.2},"/media/frigate/clips":{"free":3260461.1,"mount_type":"ext4","total":4730590.7,"used":1231648.4},"/media/frigate/recordings":{"free":3260461.1,"mount_type":"ext4","total":4730590.7,"used":1231648.4},"/tmp/cache":{"free":961.3,"mount_type":"tmpfs","total":1024.0,"used":62.7}},"temperatures":{},"uptime":3506,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passthrough of Coral USB TPU
      - /dev/dri/renderD129 # Passthrough Intel NUC iGPU (optional)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/jchrisos/frigate/config.yml:/config/config.yml
      - /media/hdd/frigate_storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_USER=qeqwewqeqwewq
      - FRIGATE_RTSP_PASSWORD=xxxxxxxxxx
      - FRIGATE_MQTT_USER=wqeqweqweqwewqqwe
      - FRIGATE_MQTT_PASSWORD=xxxxxxxxxx
      - FRIGATE_RTSP_AMCREST_PASSWORD=xxxxxxxxxxxxx
      - PLUS_API_KEY=hex:hex
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/df1216e9-dc62-427e-9dc0-443b34297598)

### Any other information that may be helpful

Showing API key from within the frigate docker:

`user@docker:~/frigate$ sudo docker exec -it frigate /bin/bash`
`root@docker:/opt/frigate# echo $PLUS_API_KEY`
`"hex:hex"`
`root@docker:/opt/frigate#`
