### DISCUSSION TITLE
[Config Support]: Restreaming reolink cameras on separate device through vpn not working consistently

### DISCUSSION THREAD

**Discussion by mbronstein1** [blakeblackshear/frigate#15136] [Config Support]
### Describe the problem you are having

I am trying to restream a few reolink cameras from one device to another device through a vpn. On the main device, the restream is working for all cameras (27 cameras). However, when I try to connect to the restream on the separate devices through the vpn, I am getting very poor streams/no streams at all. I am able to access the streams using the same rtsp url through vlc, but not through frigate. Other re-streamed cameras from other devices not using reolink work successfully. Certain things have been redacted from the config, logs, and stats (dictated by <>).

This has worked in the past, but something has changed, and it doesn't seem to be due to the newer versions of Frigate because I'm having the same issue with this running on 0.13.2 on a different device. Originally, I thought it might've been a bandwidth issue from the original device's network, **BUT** I am able to restream through VLC without issue. So I feel like it's something with my configurations somehow.

It's most likely not an issue with Frigate, but I'm just hoping to get more eyes on the problem to see if there's something I'm missing or some way I can optimize restreaming with these stupid reolink cameras.

### Version

0.15.0-e76f4e9 (also having issues on 0.13.2-6476f8a)

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mqtt
  port: 8883
  topic_prefix: nvr
  user: <user>
  password:<password>

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic

objects:
  track:
    - person
    - vehicle
    - truck
    - forklift

review:
  alerts:
    labels:
      - person
      - vehicle
      - truck
      - forklift

# yolonas_model
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /yolonas/yolonas_qat_1x3x320x320_ptq.onnx
model:
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: rgb
  labelmap_path: /yolonas/labelmap.txt
  model_type: yolonas

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
motion:
  threshold: 80
  contour_area: 30
record:
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 7
      mode: active_objects
snapshots:
  enabled: true
  bounding_box: false
  retain:
    default: 1
cameras:
  Center_Towards_Back:
    enabled: true
    ffmpeg:
      inputs:
        - path: >-
            rtsp://<non-reolink host>:8554/Center_towards_back_detect
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - forklift
  Dock_External:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<non-reolink host>:8554/Dock_External_detect
          roles:
            - detect
        - path: rtsp://<non-reolink host>:8554/Dock_External_record
          roles:
            - record
    detect:
      enabled: true
    objects:
      track: &ref_0
        - vehicle
        - truck
    zones:
      left_door_inner:
        coordinates: 442,662,692,450,785,544,754,575,605,720,442,662
        objects: *ref_0
      left_door_outer:
        coordinates: 664,478,690,454,730,424,846,347,970,363,757,572,664,478
        objects: *ref_0
      right_door_inner:
        coordinates: 631,720,875,471,1117,626,1093,720,631,720
        objects: *ref_0
      right_door_outer:
        coordinates: 853,505,982,371,1150,397,1096,660,853,505
        objects: *ref_0
    snapshots:
      required_zones: &ref_3
        - left_door_inner
        - left_door_outer
        - right_door_inner
        - right_door_outer
    live:
      stream_name: Dock_External_record
    review:
      alerts:
        required_zones: *ref_3
  aisle_2_3:
    ffmpeg:
      inputs:
        - path: rtsp://<reolink host>:8554/aisle_2_3?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://<reolink host>:8554/aisle_2_3_sub?video=copy
          roles:
            - detect
    objects:
      track:
        - forklift
        - person
    live:
      stream_name: aisle_2_3
  drivers_desk:
    ffmpeg:
      inputs:
        - path: rtsp://<reolink host>:8554/drivers_desk?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://<reolink host>:8554/drivers_desk_sub?video=copy
          roles:
            - detect
    objects:
      track:
        - forklift
        - person
    live:
      stream_name: drivers_desk
telemetry:
  stats:
    amd_gpu_stats: True
    intel_gpu_stats: True
    network_bandwidth: True
  version_check: True
timestamp_style:
  position: 'tl'
  color:
    red: 0
    green: 51
    blue: 102
  thickness: 2
version: 0.15-0
```

### Relevant Frigate log output

```shell
nvr                   | 2024-11-22 11:06:59.407694302  [2024-11-22 11:06:59] frigate.video                  ERROR   : aisle_2_3: Unable to read frames from ffmpeg process.
nvr                   | 2024-11-22 11:06:59.408829910  [2024-11-22 11:06:59] frigate.video                  ERROR   : aisle_2_3: ffmpeg process is not running. exiting capture thread...
nvr                   | 2024-11-22 11:06:59.410480149  [2024-11-22 11:06:59] frigate.video                  ERROR   : drivers_desk: Unable to read frames from ffmpeg process.
nvr                   | 2024-11-22 11:06:59.411727101  [2024-11-22 11:06:59] frigate.video                  ERROR   : drivers_desk: ffmpeg process is not running. exiting capture thread...
nvr                   | 2024-11-22 11:07:00.654519651  [2024-11-22 11:07:00] watchdog.drivers_desk          ERROR   : Ffmpeg process crashed unexpectedly for drivers_desk.
nvr                   | 2024-11-22 11:07:00.654530039  [2024-11-22 11:07:00] watchdog.drivers_desk          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
nvr                   | 2024-11-22 11:07:00.655347456  [2024-11-22 11:07:00] ffmpeg.drivers_desk.detect     ERROR   : [tcp @ 0x557b69624080] Connection to tcp://<reolink host>:8554?timeout=5000000 failed: Connection timed out
nvr                   | 2024-11-22 11:07:00.655356641  [2024-11-22 11:07:00] ffmpeg.drivers_desk.detect     ERROR   : [in#0 @ 0x557b69622d80] Error opening input: Connection timed out
nvr                   | 2024-11-22 11:07:00.656257510  [2024-11-22 11:07:00] ffmpeg.drivers_desk.detect     ERROR   : Error opening input file rtsp://<reolink host>:8554/drivers_desk_sub?video=copy.
nvr                   | 2024-11-22 11:07:00.656264911  [2024-11-22 11:07:00] ffmpeg.drivers_desk.detect     ERROR   : Error opening input files: Connection timed out
nvr                   | 2024-11-22 11:07:03.855198230  [2024-11-22 11:07:03] watchdog.aisle_2_3             ERROR   : Ffmpeg process crashed unexpectedly for aisle_2_3.
nvr                   | 2024-11-22 11:07:03.871444912  [2024-11-22 11:07:03] watchdog.aisle_2_3             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
nvr                   | 2024-11-22 11:07:03.871451205  [2024-11-22 11:07:03] ffmpeg.aisle_2_3.detect        ERROR   : [tcp @ 0x555e7fc3a080] Connection to tcp://<reolink host>:8554?timeout=5000000 failed: Connection timed out
nvr                   | 2024-11-22 11:07:03.871454485  [2024-11-22 11:07:03] ffmpeg.aisle_2_3.detect        ERROR   : [in#0 @ 0x555e7fc38d80] Error opening input: Connection timed out
nvr                   | 2024-11-22 11:07:03.871458079  [2024-11-22 11:07:03] ffmpeg.aisle_2_3.detect        ERROR   : Error opening input file rtsp://<reolink host>:8554/aisle_2_3_sub?video=copy.
nvr                   | 2024-11-22 11:07:03.871461370  [2024-11-22 11:07:03] ffmpeg.aisle_2_3.detect        ERROR   : Error opening input files: Connection timed out
nvr                   | 2024-11-22 11:07:09.404932807  [2024-11-22 11:07:09] frigate.video                  ERROR   : drivers_desk: Unable to read frames from ffmpeg process.
nvr                   | 2024-11-22 11:07:09.406323534  [2024-11-22 11:07:09] frigate.video                  ERROR   : aisle_2_3: Unable to read frames from ffmpeg process.
nvr                   | 2024-11-22 11:07:09.406450385  [2024-11-22 11:07:09] frigate.video                  ERROR   : drivers_desk: ffmpeg process is not running. exiting capture thread...
nvr                   | 2024-11-22 11:07:09.407545902  [2024-11-22 11:07:09] frigate.video                  ERROR   : aisle_2_3: ffmpeg process is not running. exiting capture thread...
nvr                   | 2024-11-22 11:07:10.688703936  [2024-11-22 11:07:10] watchdog.drivers_desk          ERROR   : Ffmpeg process crashed unexpectedly for drivers_desk.
nvr                   | 2024-11-22 11:07:10.689041654  [2024-11-22 11:07:10] watchdog.drivers_desk          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
nvr                   | 2024-11-22 11:07:10.689046080  [2024-11-22 11:07:10] ffmpeg.drivers_desk.detect     ERROR   : [tcp @ 0x5629149a3080] Connection to tcp://<reolink host>:8554?timeout=5000000 failed: Connection timed out
nvr                   | 2024-11-22 11:07:10.689069995  [2024-11-22 11:07:10] ffmpeg.drivers_desk.detect     ERROR   : [in#0 @ 0x5629149a1d80] Error opening input: Connection timed out
nvr                   | 2024-11-22 11:07:10.689132562  [2024-11-22 11:07:10] ffmpeg.drivers_desk.detect     ERROR   : Error opening input file rtsp://<reolink host>:8554/drivers_desk_sub?video=copy.
nvr                   | 2024-11-22 11:07:10.689185128  [2024-11-22 11:07:10] ffmpeg.drivers_desk.detect     ERROR   : Error opening input files: Connection timed out
```

### Relevant go2rtc log output

```shell
No relevant logs for these specific cameras (drivers_desk and aisle_2_3)
```

### Frigate stats

```json
{
"cameras": {
"Center_Towards_Back": {
"camera_fps": 5,
"process_fps": 5,
"skipped_fps": 0,
"detection_fps": 0,
"detection_enabled": true,
"pid": 393,
"capture_pid": 441,
"ffmpeg_pid": 452,
"audio_rms": 0,
"audio_dBFS": 0
},
"Dock_External": {
"camera_fps": 5.1,
"process_fps": 5.1,
"skipped_fps": 0.2,
"detection_fps": 9.5,
"detection_enabled": true,
"pid": 396,
"capture_pid": 451,
"ffmpeg_pid": 5910,
"audio_rms": 0,
"audio_dBFS": 0
},
"aisle_2_3": {
"camera_fps": 7,
"process_fps": 6.2,
"skipped_fps": 0.6,
"detection_fps": 1.4,
"detection_enabled": true,
"pid": 408,
"capture_pid": 461,
"ffmpeg_pid": 9504,
"audio_rms": 0,
"audio_dBFS": 0
},
"drivers_desk": {
"camera_fps": 0,
"process_fps": 0.1,
"skipped_fps": 0,
"detection_fps": 1.2,
"detection_enabled": true,
"pid": 425,
"capture_pid": 472,
"ffmpeg_pid": 18598,
"audio_rms": 0,
"audio_dBFS": 0
}
},
"detectors": {
"ov": {
"inference_speed": 40.79,
"detection_start": 0,
"pid": 354
}
},
"detection_fps": 12.1,
"gpu_usages": {
"intel-vaapi": {
"gpu": "8.44%",
"mem": "-%",
"clients": {
"354": "128.66%",
"452": "2.65%",
"5910": "5.95%",
"9504": "6.73%"
}
}
},
"cpu_usages": {
"1": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
},
"15": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6-linux-init-shutdownd"
},
"17": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
},
"24": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-oneshot-runner"
},
"25": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-fdholder"
},
"26": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync"
},
"27": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync-log"
},
"28": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate"
},
"29": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate-log"
},
"30": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc"
},
"31": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-healthcheck"
},
"32": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-log"
},
"33": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx"
},
"34": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx-log"
},
"45": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
},
"46": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
},
"86": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
},
"87": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
},
"88": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
},
"91": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
},
"97": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
},
"115": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user go2rtc-healthcheck"
},
"117": {
"cpu": "9.3",
"cpu_average": "8",
"mem": "3.1",
"cmdline": "python3 -u -m frigate"
},
"125": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: master process nginx"
},
"156": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"157": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"158": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"159": {
"cpu": "0.1",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"160": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: cache manager process"
},
"293": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user certsync"
},
"338": {
"cpu": "1.7",
"cpu_average": "2",
"mem": "1.2",
"cmdline": "frigate.recording_manager"
},
"347": {
"cpu": "0.6",
"cpu_average": "0",
"mem": "1.1",
"cmdline": "frigate.review_segment_manager"
},
"354": {
"cpu": "66.6",
"cpu_average": "62",
"mem": "2.4",
"cmdline": "frigate.detector.ov  "
},
"370": {
"cpu": "4.0",
"cpu_average": "3",
"mem": "1.2",
"cmdline": "frigate.output       "
},
"377": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"393": {
"cpu": "4.7",
"cpu_average": "5",
"mem": "1.2",
"cmdline": "frigate.process:Center_Towards_Back"
},
"396": {
"cpu": "17.5",
"cpu_average": "13",
"mem": "1.3",
"cmdline": "frigate.process:Dock_External"
},
"399": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"408": {
"cpu": "2.6",
"cpu_average": "1",
"mem": "1.3",
"cmdline": "frigate.process:aisle_2_3"
},
"425": {
"cpu": "0.1",
"cpu_average": "0",
"mem": "1.3",
"cmdline": "frigate.process:drivers_desk"
},
"438": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"441": {
"cpu": "1.4",
"cpu_average": "1",
"mem": "1.1",
"cmdline": "frigate.capture:Center_Towards_Back"
},
"449": {
"cpu": "0.1",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"451": {
"cpu": "1.2",
"cpu_average": "1",
"mem": "9.8",
"cmdline": "frigate.capture:Dock_External"
},
"452": {
"cpu": "3.0",
"cpu_average": "2",
"mem": "0.4",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<non-reolink host>:8554/center_towards_back_detect -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Interchange_Test@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"461": {
"cpu": "1.2",
"cpu_average": "0",
"mem": "1.1",
"cmdline": "frigate.capture:aisle_2_3"
},
"469": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"472": {
"cpu": "0.3",
"cpu_average": "0",
"mem": "1.1",
"cmdline": "frigate.capture:drivers_desk"
},
"474": {
"cpu": "1.1",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<reolink host>:8554/Dock_External_record -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Dock_External@%Y%m%d%H%M%S%z.mp4"
},
"5910": {
"cpu": "4.2",
"cpu_average": "3",
"mem": "0.4",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<reolink host>:8554/Dock_External_detect -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"9504": {
"cpu": "20.8",
"cpu_average": "6",
"mem": "0.5",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<reolink host>:8554/aisle_2_3_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"17408": {
"cpu": "38.0",
"cpu_average": "17",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<reolink host>:8554/aisle_2_3?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/aisle_2_3@%Y%m%d%H%M%S%z.mp4"
},
"18433": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 60"
},
"18597": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 30s"
},
"18598": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<reolink host>:8554/drivers_desk_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"18600": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-e76f4e9 -rtsp_transport tcp -timeout 5000000 -i rtsp://<reolink host>:8554/drivers_desk?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/drivers_desk@%Y%m%d%H%M%S%z.mp4"
},
"frigate.full_system": {
"cpu": "57.6",
"mem": "49.0"
}
},
"service": {
"uptime": 4190,
"version": "0.15.0-e76f4e9",
"latest_version": "0.14.1",
"storage": {
"/media/frigate/recordings": {
"total": 112358,
"used": 57466.1,
"free": 49666.1,
"mount_type": "btrfs"
},
"/media/frigate/clips": {
"total": 112358,
"used": 57466.1,
"free": 49666.1,
"mount_type": "btrfs"
},
"/tmp/cache": {
"total": 953.7,
"used": 69.5,
"free": 884.2,
"mount_type": "tmpfs"
},
"/dev/shm": {
"total": 512,
"used": 383.5,
"free": 128.5,
"mount_type": "tmpfs"
}
},
"temperatures": {},
"last_updated": 1732298086
},
"processes": {
"recording": {
"pid": 338
},
"review_segment": {
"pid": 347
},
"go2rtc": {
"pid": 97
}
}
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
nvr:
    container_name: nvr
    restart: unless-stopped
    # image: ghcr.io/blakeblackshear/frigate:0.13.2
    # image: ghcr.io/blakeblackshear/frigate:9afa135
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta2
    shm_size: '512mb' # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/nvr/config:/config
      - ./docker/nvr/storage:/media/frigate
      # - ./docker/models/yolov8n_final:/yolov8n
      - ./docker/models/yolonas_model:/yolonas
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    cap_add:
      - CAP_PERFMON
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    ports:
      - '5000:5000'
      - '8554:8554' # RTSP feeds
      - '8555:8555/tcp' # WebRTC over tcp
      - '8555:8555/udp' # WebRTC over udp
```

### Object Detector

OpenVino

### Any other information that may be helpful

main device go2rtc setup
```yaml
go2rtc:
  webrtc:
    candidates:
      - localhost:8555
      - stun:8555
  streams:
    drivers_desk:
      - >-
        ffmpeg:http://<host>/flv?port=<port>&app=bcs&stream=channel3_main.bcs&user=<user>&password=<password>
      - ffmpeg:drivers_desk#audio=aac
    aisle_2_3:
      - >-
        ffmpeg:http://<host>/flv?port=<port>&app=bcs&stream=channel9_main.bcs&user=<user>&password=<password>
      - ffmpeg:aisle_2_3#audio=aac
 ```

docker stats from main device
```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT    MEM %     NET I/O          BLOCK I/O        PIDS
e83ea621eea7   nvr       315.17%   5.745GiB / 15.4GiB   37.31%    129GB / 10.8GB   229MB / 38.2GB   975
```

docker stats from restreaming device
```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O        PIDS
7a57ada1f62d   nvr       59.70%    3.706GiB / 15.49GiB   23.93%    4.97GB / 227MB   282MB / 1.12GB   422
```
