### DISCUSSION TITLE
[Support]: Incorrect Person Count?

### DISCUSSION THREAD

**Discussion by jiiins** [blakeblackshear/frigate#15131] [General Support]
### Describe the problem you are having

In HA I use the person_count sensors to trigger some automations. Since 0.14, sometimes I get a 1 count even though there is no person and I can't find any alert/detection in Frigate. Just for reference, here is the sensor indication, although nobody was there and I couldn't find a false positive in Frigate:

![image](https://github.com/user-attachments/assets/e13620dc-658d-40a4-9154-bed4b982ceca)

How can this happen? Or better, how can I ensure that the HA person_count sensor show only actual alerts?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
Relevant parts (I think):

  08_lavanderia:
    ffmpeg:
      inputs:
        - path: 
            rtsp://192.168.xx.xxx/axis-media/media.amp?streamprofile=hass_detect
          roles:
            - detect
        - path: rtsp://hass:ha33ss.@192.168.31.114/axis-media/media.amp?streamprofile=hass_view
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      filters:
        person:
          max_area: 100000
          mask:
            - 1,1,1,0,0
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

axis

### Any other information that may be helpful

Frigate HA integration 5.4.0

HA:
Core 2024.11.2
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2
