### DISCUSSION TITLE
0.15 Beta 2 - instant crash when webinterface is opened

### DISCUSSION THREAD

**Discussion by flyersa** [blakeblackshear/frigate#15146] [Ask A Question]
Hey,

upgraded my frigate 0.14 to 0.15-beta2 . Once started up it works as long you do not open the webinterface. As soon as i login to the webui i get:

2024-11-23 12:32:33.468416264  Fatal Python error: Segmentation fault
2024-11-23 12:32:33.468419917
2024-11-23 12:32:33.468421280  Thread 0x00007ad92b4006c0 (most recent call first):
2024-11-23 12:32:33.468422622    File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 193 in __init__

any idea?

config:

```
mqtt:
  enabled: true
  host: localhost
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 7
    pre_capture: 5
    post_capture: 10
  detections:
    retain:
      days: 7
    pre_capture: 5
    post_capture: 10
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
  input_args: >-
    -avoid_negative_ts make_zero
    -fflags +genpts+discardcorrupt
    -rtsp_transport tcp
    -bufsize 5000k
    -reorder_queue_size 10000
    -max_delay 5000000

go2rtc:
  streams:
    H58_SXP:
      - rtsp://admin:REDACTED@192.168.11.189
      - webrtc
    S26_Vorne:
      - rtsp://redacted:554/s0
      - webrtc
    Plessa_Einfahrt:
      - rtsp://ubnt:REDACTED@192.168.8.95:554/s0
      - webrtc
    Plessa_Werkstatt:
      - rtsp://ubnt:REDACTED@192.168.8.92:554/s0
      - webrtc
    Plessa_LHaus:
      - rtsp://ubnt:REDACTED@192.168.8.93:554/s0
      - webrtc
    Plessa_Vorraum:
      - rtsp://ubnt:REDACTED@192.168.8.91:554/s0
      - webrtc
    Plessa_Mietraum:
      - rtsp://ubnt:REDACTED@192.168.8.33:554/s0
      - webrtc

cameras:
  H58_SXP:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/H58_SXP
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    onvif:
      host: 192.168.11.189
      port: 8000
      user: admin
      password: REDACTED
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
      mask: 0.088,0.285,0.204,0.39,1,0.535,0.996,0.008,0.082,0.003
    motion:
      mask: 0.088,0.29,0.209,0.393,1,0.539,1,0,0.082,0

  S26_Vorne:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/S26_Vorne
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog

  Plessa_Einfahrt:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Plessa_Einfahrt
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - car

  Plessa_Werkstatt:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Plessa_Werkstatt
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - animal
        - car

  Plessa_LHaus:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Plessa_LHaus
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - animal
        - car

  Plessa_Vorraum:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Plessa_Vorraum
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person

  Plessa_Mietraum:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Plessa_Mietraum
          input_args: >-
            -re
            -thread_queue_size 512
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person

version: 0.15-0

camera_groups:
  Plessa:
    order: 1
    icon: LuAlertOctagon
    cameras:
      - Plessa_Einfahrt
      - Plessa_Werkstatt
      - Plessa_LHaus
      - Plessa_Vorraum
      - Plessa_Mietraum
```
