### DISCUSSION TITLE
0.15 beta 2 generative AI home assistant notification.

### DISCUSSION THREAD

**Discussion by clsferguson** [blakeblackshear/frigate#15141] [Show and tell]
Set up to use signal messenger.

edit: updated the automation with a bug fix.

```yaml
alias: Notification of camera events
triggers:
  - topic: frigate/events
    trigger: mqtt
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'end' }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['entered_zones'] | length > 0 }}"
actions:
  - variables:
      event_id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
  - wait_for_trigger:
      - topic: frigate/tracked_object_update
        value_template: >
          {{ value_json['type'] == 'description' and value_json['id'] ==
          event_id }}
        variables:
          event_id: "{{ event_id }}"
        trigger: mqtt
    timeout: "10"
    continue_on_timeout: true
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger is defined }}"
        sequence:
          - variables:
              description: "{{ wait.trigger.payload_json['description'] }}"
          - data:
              message: >
                {{ description }} - View Snapshot:
                https://pub.domain.com/api/frigate/notifications/{{ event_id
                }}/snapshot.jpg - View clip:
                https://pub.domain.com/api/frigate/notifications/{{ event_id
                }}/clip.mp4
              data:
                verify_ssl: false
                urls:
                  - >-
                    http://10.0.1.11:8123/api/frigate/notifications/{{ event_id
                    }}/thumbnail.jpg
            action: notify.signal
    default:
      - data:
          message: >
            A {{ label }} was detected on the {{ camera }} camera. - View
            Snapshot: https://pub.domain.com/api/frigate/notifications/{{
            event_id }}/snapshot.jpg - View clip:
            https://pub.domain.com/api/frigate/notifications/{{ event_id
            }}/clip.mp4
          data:
            verify_ssl: false
            urls:
              - >-
                http://10.0.1.11:8123/api/frigate/notifications/{{ event_id
                }}/thumbnail.jpg
        action: notify.signal
mode: queued
max: 25
```

Edit: added a telegram bot notification.
```yaml
alias: Notification of camera events
triggers:
  - topic: frigate/events
    trigger: mqtt
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'end' }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['entered_zones'] | length > 0 }}"
actions:
  - variables:
      event_id: "{{ trigger.payload_json['after']['id'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
  - wait_for_trigger:
      - topic: frigate/tracked_object_update
        value_template: >
          {{ value_json['type'] == 'description' and value_json['id'] ==
          event_id }}
        variables:
          event_id: "{{ event_id }}"
        trigger: mqtt
    timeout: "15"
    continue_on_timeout: true
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger is not none }}"
        sequence:
          - variables:
              description: "{{ wait.trigger.payload_json['description'] }}"
          - data:
              message: >
                {{ description }} - View Snapshot:
                https://pub.domain.com/api/frigate/notifications/{{ event_id
                }}/snapshot.jpg - View clip:
                https://pub.domain.com/api/frigate/notifications/{{ event_id
                }}/clip.mp4
              data:
                verify_ssl: false
                urls:
                  - >-
                    http://10.0.1.11:8123/api/frigate/notifications/{{ event_id
                    }}/thumbnail.jpg
            action: notify.signal
          - data:
              url: >-
                http://10.0.1.11:8123/api/frigate/notifications/{{ event_id
                }}/thumbnail.jpg
              caption: >
                <b>Camera Alert</b> 🚨

                ├ <i>Camera:</i> {{ camera }} 

                └ <i>Event:</i> ┐

                {{ description }}


                <a href="https://pub.domain.com/api/frigate/notifications/{{
                event_id }}/snapshot.jpg">📷 View Snapshot 📷</a>


                <a href="https://pub.domain.com/api/frigate/notifications/{{
                event_id }}/clip.mp4">🎥 View Clip 🎥</a>
              parse_mode: html
              disable_web_page_preview: true
            action: telegram_bot.send_photo
    default:
      - data:
          message: >
            A {{ label }} was detected on the {{ camera }} camera. - View
            Snapshot: https://pub.domain.com/api/frigate/notifications/{{
            event_id }}/snapshot.jpg - View clip:
            https://pub.domain.com/api/frigate/notifications/{{ event_id
            }}/clip.mp4
          data:
            verify_ssl: false
            urls:
              - >-
                http://10.0.1.11:8123/api/frigate/notifications/{{ event_id
                }}/thumbnail.jpg
        action: notify.signal
      - data:
          target: -123456789 # chat ID
          url: >-
            http://10.0.1.11:8123/api/frigate/notifications/{{ event_id
            }}/thumbnail.jpg
          caption: >
            <b>Camera Alert</b> 🚨

            ├ <i>Camera:</i> {{ camera }}

            └ <i>Event:</i> {{ label }} detected


            <a href="https://pub.domain.com/api/frigate/notifications/{{ event_id
            }}/snapshot.jpg">📷 View Snapshot 📷</a>


            <a href="https://pub.domain.com/api/frigate/notifications/{{ event_id
            }}/clip.mp4">🎥 View Clip 🎥</a>
          parse_mode: html
          disable_web_page_preview: true
        action: telegram_bot.send_photo
  - delay: "00:00:01.2" # rate limit
mode: queued
```

example in telegram:
![image](https://github.com/user-attachments/assets/6d874c69-0b63-43e9-b2ba-08bdea60203b)

**Comment by erasmus83** [comment]
Have you tried doing this with the frigate/reviews topic rather than events? Scratching my head over that one, but not brilliant with HA Automations.

**Reply by clsferguson** [reply]
No, I haven't. Not really sure the best thing to do there. 

With this one, it will catch the event when it is done, then wait 15 seconds for the gen ai to output a description, if none is sent to the mqtt, it outputs a generic description.

**Comment by quincy5891** [comment]
Did you ever have issues with the template not waiting and would take first one that comes in? Already have detection list in my variables above. It will go through my wait for trigger then fail the next condition and show me the value id which doesn't match any on the detections list. included log of what the events say too.

Any ideas?


 ```
 - wait_for_trigger:
      - platform: mqtt
        topic: frigate/tracked_object_update
        value_template: >
          {{ value_json['type'] == 'description' and value_json['id'] in detections_list }}
        variables:
          detections_list: "{{ detections_list }}"
    timeout: "{{ wait_timeout | int }}" # Configurable timeout (optional)
    continue_on_timeout: true

  # Log the result of the waits
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ wait.trigger is not none and wait.trigger.payload_json.id in detections_list}}
        sequence:
          - service: logbook.log
            data:
              name: "After Wait Trigger"
              message: >
                Matched ID: {{wait.trigger.payload_json.id}}
                Detections List: {{detections_list}}
    default:
      - service: logbook.log
        data:
          name: "After Wait Trigger"
          message: "Matched ID: {{wait.trigger.payload_json.id if wait.trigger is not none else 'No matching ID was found. Continuing after timeout.'}} Detections List: {{detections_list}}"
```

```

Executed: January 4, 2025 at 11:27:59 PM
Result:
wait:
  remaining: 23.024687054974493
  completed: true
  trigger:
    id: '0'
    idx: '0'
    alias: null
    platform: mqtt
    topic: frigate/tracked_object_update
    payload: |-
      {"type": "description",
      "id": "1736012466.033084-lw9qkudwa",
      "description": "The car is a red sedan moving away from the camera."}
    qos: 0
    description: mqtt topic frigate/tracked_object_update
    payload_json:
      type: description
      id: 1736012466.033084-lw9qkudwa
      description: The car is a red sedan moving away from the camera.

```
```
Executed: January 4, 2025 at 11:28:06 PM
Result:
params:
  domain: logbook
  service: log
  service_data:
    name: After Wait Trigger
    message: >-
      Matched ID: 1736012466.033084-lw9qkudwa Detections List:
      ['1736002172.133266-g4hx1n', '1736012466.033084-lw9qku']
  target: {}
running_script: false
```
