### DISCUSSION TITLE
[HowTo] Install as PWA (App) despite Unsecure Connection (in docker setup: ERR_CERT_AUTHORITY_INVALID)

### DISCUSSION THREAD

**Discussion by drewsed** [blakeblackshear/frigate#15147] [General Support] [answered]
### Describe the problem you are having

Hi, I tried to install frigate as a PWA and read online, that this requires a secure connection. Mine doesnt seem to be secure.
I get the error ERR_CERT_AUTHORITY_INVALID in Chrome Browser on Android and Firefox on Win11. On the PC I saw that the certificate hostname is localhost, I connect wit an IP from a different machine.

How do I properly set this up? Can somebody help me?

Thank you very much in advance.

### Version

0.14

### What browser(s) are you using?

Brave / Firefox latest stable

### Frigate config file

```yaml
default config after setup
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable

    shm_size: "220.62mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/andi/docker_data/frigate/config:/config
      #- /home/andi/docker_data/frigate/media/frigate:/media/frigate
      - /media/Data/docker_data/frigate/media/frigate/:/media/frigate
      #- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #  target: /tmp/cache
      #  tmpfs:
      #    size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxx"
      # LIBVA_DRIVER_NAME: "i965" # old HW Driver hat nicht funktioniert, paar mal probiert, die HW kann einfach nur bis 2048
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

none
