### DISCUSSION TITLE
[HW Accel Support]: Asus NUC 14 Pro / Intel Core Ultra 7 155H

### DISCUSSION THREAD

**Discussion by matknowles** [blakeblackshear/frigate#15153] [Hardware Acceleration Support]
### Describe the problem you are having

Hello, Can't seem to get hardware acceleration working with my new Asus Pro NUC14RVHU7 NUC. Initially tried just vaapi but got no frames, so tried all combinations of environment_vars: LIBVA_DRIVER_NAME: i965 + ffmpeg: hwaccel_args: preset-vaapi and hwaccel_args: preset-intel-qsv-h265 (am using all H265 cameras). Frigate is working if I comment out the ffmpeg hwaccel_args at about 26% CPU, but isn't ideal. I can only find that the Core 7 Ultra 155H uses "Intel Arc" graphics. 

Trying qsv gives me errors like: 
`Ffmpeg process crashed unexpectedly for FrontPath.
2024-11-23 18:16:07.540300350  [2024-11-23 18:16:07] watchdog.FrontPath             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-11-23 18:16:07.540360396  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : [AVHWDeviceContext @ 0x55d77a47b680] No VA display found for device -hwaccel_output_format.
2024-11-23 18:16:07.540421443  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : Device creation failed: -22.
2024-11-23 18:16:07.540460040  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : Failed to set value '-hwaccel_output_format' for option 'qsv_device': Invalid argument
2024-11-23 18:16:07.540500334  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : Error parsing global options: Invalid argument`

Using environment vars i965 and vaapi gives:
`[2024-11-23 19:25:39] frigate.util.services          ERROR   : Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found
2024-11-23 19:25:39.325736919  
2024-11-23 19:25:39.604099052  [2024-11-23 19:25:39] frigate.video                  ERROR   : FrontPath: Unable to read frames from ffmpeg process.`
and 
`[2024-11-23 19:25:58] ffmpeg.FrontPath.detect ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
2024-11-23 19:25:58.894778812  [2024-11-23 19:25:58] watchdog.FrontPath             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-11-23 19:25:58.894966237  [2024-11-23 19:25:58] ffmpeg.FrontPath.detect ERROR   : Error parsing options for output file vaapi.
2024-11-23 19:25:58.894972777  [2024-11-23 19:25:58] ffmpeg.FrontPath.detect ERROR   : Error opening output files: Invalid argument
2024-11-23 19:25:58.894979279  [2024-11-23 19:25:58] ffmpeg.FrontPath.detect        ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.`

Just using vaapi:
`[2024-11-23 19:30:28] frigate.video                  ERROR   : FrontPath: Unable to read frames from ffmpeg process.
2024-11-23 19:30:28.648519630  [2024-11-23 19:30:28] frigate.video                  ERROR   : FrontPath: ffmpeg process is not running. exiting capture thread...
[2024-11-23 19:30:29] frigate.util.services          ERROR   : Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nerror: failed to initialize display\n"`

I haven't tried 0.15 beta yet, but I bought this new NUC to hopefully be powerful enough for Frigate going into the future. If I'm going to have a bad time I may as well return it.

It's just occured to me that I restored this home assistant install from a backup from my old NUC that died (hardware failure), so I wonder if the XDG_RUNTIME_DIR is invalid has anything to do with that? Apologies for my ignorance.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
database:
  path: /config/frigate.db0

#environment_vars:
#  LIBVA_DRIVER_NAME: i965

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error

model:
  path: plus://

mqtt:
  host: core-mosquitto
  user: mqtt
  password: 

#semantic_search:
#  enabled: true
#  reindex: true
#  model_size: large

#genai:
#  enabled: True
#  provider: gemini
#  api_key: ""
#  model: gemini-1.5-flash

ffmpeg: # try "ffmpeg -decoders | grep cuvid" in terminal to see available decoders
  #hwaccel_args: preset-vaapi # Intel H264+H265 (recommended as of 2023)
  #hwaccel_args: preset-intel-qsv-h265 #Intel >10th Gen H265 (use if problems with vaapi)
  #hwaccel_args: preset-intel-qsv-h264 #Intel >10th Gen H264
  #hwaccel_args: preset-rpi-64-h265 #Raspi H265
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 8 is default. 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 4
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  # Optional: Threshold for camera activity to stop showing camera (default: shown below)
  #inactivity_threshold: 30
  # Optional: Configure the birdseye layout
  #layout:
    # Optional: Scaling factor for the layout calculator, range 1.0-5.0 (default: shown below)
   # scaling_factor: 2.0
    # Optional: Maximum number of cameras to show at one time, showing the most recent (default: show all cameras)
    #max_cameras: 1

go2rtc:
  streams:
    FrontPath:
      - rtsp://@192.168.1.11:554/main

detect:
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - bird
    - cat
    - dog
    - horse
    - bear
    - hat
    - backpack
    - umbrella
    - eye glasses
    - handbag
    - suitcase
    - face
    - license_plate
    - amazon
    - ups
    - fedex
    - package
    #- dhl
    #- dpd
    #- fox
    #- squirrel
    #- waste_bin
  filters:
    #global filters
    # defaults below taken from Frigate+ documentation: https://docs.frigate.video/plus/
    person:
      min_score: 0.6 #0.56 calibrated for porch night
      threshold: 0.62 #0.63 calibrated for porch night
    car:
      min_score: 0.65
      threshold: 0.85
    bicycle:
      min_score: 0.5
      threshold: 0.7
    motorcycle:
      min_score: 0.5
      threshold: 0.7
    bus:
      min_score: 0.5
      threshold: 0.7
    bird:
      min_score: 0.5
      threshold: 0.7
    cat:
      min_score: 0.65
      threshold: 0.8
    dog:
      min_score: 0.7
      threshold: 0.9
    hat:
      min_score: 0.5
      threshold: 0.7
    backpack:
      min_score: 0.5
      threshold: 0.7
    umbrella:
      min_score: 0.5
      threshold: 0.7
    eye glasses:
      min_score: 0.5
      threshold: 0.7
    handbag:
      min_score: 0.5
      threshold: 0.7
    suitcase:
      min_score: 0.5
      threshold: 0.7
    face:
      min_score: 0.7
      threshold: 0.7
    license_plate:
      min_score: 0.6
      threshold: 0.7
    amazon:
      min_score: 0.75
      threshold: 0.7
    fedex:
      min_score: 0.75
      threshold: 0.7
    ups:
      min_score: 0.75
      threshold: 0.7
    package:
      min_score: 0.65
      threshold: 0.9
    #dhl:
    #  min_score: 0.65
    #  threshold: 0.9
    #dpd:
    #  min_score: 0.65
    #  threshold: 0.9
    #fox:
    #  min_score: 0.65
    #  threshold: 0.9
    #squirrel:
    #  min_score: 0.65
    #  threshold: 0.9
    #waste_bin:
    #  min_score: 0.65
    #  threshold: 0.9

record:
  #sync_recordings: true # = synchronises files which may have been deleted outside of Frigate; uses considerable CPU resources and is mostly not needed.
  enabled: true
  retain:
    days: 14
    mode: motion
  events:
    retain:
      default: 14
      mode: all #- all records all segments of an event start to finish, motion=only motion during event, active_objects=only when objects active (car/people moving etc)
      #objects: # - retention policy for individual objects
      #  dog: 7
      #  person: 14
      #  package: 10
  export:
    timelapse_args: -vf setpts=0.02*PTS -r 25

#review:
  # global objects to produce alerts
  #alerts:
    #labels:
      #- person
      #- car
      #- bicycle
      #- motorcycle
      #- bus
      #- bird
      #- cat
      #- dog
      #- horse
      #- bear
      #- hat
      #- backpack
      #- umbrella
      #- eye glasses
      #- handbag
      #- suitcase
      #- face
      #- license_plate
      #- amazon
      #- ups
      #- fedex
      #- package
      #- dhl
      #- dpd
      #- fox
      #- squirrel
      #- waste_bin

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  retain:
    default: 14
    objects:
      person: 30
      car: 14
      bicycle: 30
      bus: 14
      bird: 30
      cat: 30
      dog: 30

cameras:
  FrontPath:
    detect:
      #width: 704
      #height: 576
      fps: 10
    enabled: true
    ffmpeg:
      inputs:
        #- path: rtsp://127.0.0.1:8554/FrontPath_Sub
        #  input_args: preset-rtsp-restream
          #roles:
          #  - detect
        - path: rtsp://127.0.0.1:8554/FrontPath_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/FrontPath
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      filters:
        person:
          #min_area: 2000
          #max_area: 14000
          #min_ratio: 0.25
          #max_ratio: 0.8
          min_score: 0.72
          threshold: 0.7
          #min_score: 0.15
          #threshold: 0.1
    zones:
      FrontPathway:
        coordinates: 0.604,0.502,0.793,0.478,0.937,0.541,0.794,0.999,0.425,0.997
        loitering_time: 0
        inertia: 3
        #filters:
        #  person:
        #    min_area: 2000
        #    max_area: 14000
        #    min_score: 0.5
        #    threshold: 0.52
        objects:
          - backpack
          - bicycle
          - bird
          - cat
          - dog
          - eye glasses
          - handbag
          - hat
          - package
          - person
          - suitcase
          - umbrella
      CarTrack:
        coordinates: 0.763,0.175,0.975,0.328,0.95,0.498,0.627,0.305
        loitering_time: 0
        objects:
          - car
          - motorcycle
        inertia: 3
    review:
      alerts:
        labels:
          - backpack
          - bicycle
          - bird
          - cat
          - dog
          - eye glasses
          - handbag
          - hat
          - package
          - person
          - suitcase
          - umbrella
        #required_zones: FrontPathway
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0.195,0.914,0.213,0.911,0.212,0.945,0.195,0.944
        - 0.465,0.003,0.45,0.042,0.424,0.109,0.404,0.176,0.389,0.2,0.385,0.273,0.297,0.407,0.359,0.511,0.373,0.595,0.323,0.642,0.321,0.709,0.362,0.764,0.4,0.788,0.453,0.836,0.512,0.812,0.573,0.834,0.586,0.757,0.589,0.7,0.583,0.649,0.583,0.605,0.59,0.563,0.593,0.531,0.601,0.496,0.599,0.452,0.593,0.423,0.598,0.393,0.595,0.369,0.601,0.324,0.599,0.299,0.605,0.281,0.568,0.268,0.568,0.241,0.599,0.188,0.562,0.197,0.556,0.161,0.552,0.136,0.566,0.103,0.529,0.076,0.52,0.072,0.52,0.041,0.51,0.026,0.496,0.014,0.48,0.012
        - 0.008,0.636,0.043,0.651,0.07,0.994,0.006,0.997

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
Trying qsv gives me errors like: 
`Ffmpeg process crashed unexpectedly for FrontPath.
2024-11-23 18:16:07.540300350  [2024-11-23 18:16:07] watchdog.FrontPath             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-11-23 18:16:07.540360396  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : [AVHWDeviceContext @ 0x55d77a47b680] No VA display found for device -hwaccel_output_format.
2024-11-23 18:16:07.540421443  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : Device creation failed: -22.
2024-11-23 18:16:07.540460040  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : Failed to set value '-hwaccel_output_format' for option 'qsv_device': Invalid argument
2024-11-23 18:16:07.540500334  [2024-11-23 18:16:07] ffmpeg.FrontPath.detect        ERROR   : Error parsing global options: Invalid argument`

Using environment vars i965 and vaapi gives:
`[2024-11-23 19:25:39] frigate.util.services          ERROR   : Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found
2024-11-23 19:25:39.325736919  
2024-11-23 19:25:39.604099052  [2024-11-23 19:25:39] frigate.video                  ERROR   : FrontPath: Unable to read frames from ffmpeg process.`
and 
`[2024-11-23 19:25:58] ffmpeg.FrontPath.detect ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
2024-11-23 19:25:58.894778812  [2024-11-23 19:25:58] watchdog.FrontPath             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-11-23 19:25:58.894966237  [2024-11-23 19:25:58] ffmpeg.FrontPath.detect ERROR   : Error parsing options for output file vaapi.
2024-11-23 19:25:58.894972777  [2024-11-23 19:25:58] ffmpeg.FrontPath.detect ERROR   : Error opening output files: Invalid argument
2024-11-23 19:25:58.894979279  [2024-11-23 19:25:58] ffmpeg.FrontPath.detect        ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.`

Just using vaapi:
`[2024-11-23 19:30:28] frigate.video                  ERROR   : FrontPath: Unable to read frames from ffmpeg process.
2024-11-23 19:30:28.648519630  [2024-11-23 19:30:28] frigate.video                  ERROR   : FrontPath: ffmpeg process is not running. exiting capture thread...
[2024-11-23 19:30:29] frigate.util.services          ERROR   : Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nerror: failed to initialize display\n"`
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
don't know how to do this, sorry
```

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

milesight/dahua

### Screenshots of the Frigate UI's System metrics pages

![metrics](https://github.com/user-attachments/assets/444c5c0a-d156-4e6b-b5dd-71f8b7c5a556)
