### DISCUSSION TITLE
[Camera Support]: Unable to get audio on live or recordings

### DISCUSSION THREAD

**Discussion by Chrissica06** [blakeblackshear/frigate#15159] [Camera Support]
### Describe the problem you are having

In go2rtc I can view the live steam with audio.  I can't figure out what needs to be done to enable audio in frigate.    I have searched found alot of info around transcoding audio but my cameras put out aac audio so i don't think i need to transcode it.

### Version

0.14.1-

### What browser(s) are you using?

Edge 131.0.2903.63

### Frigate config file

```yaml
mqtt:
  host: 10.146.1.10
  port: 1883
  user: mqtt-user
  password: MA5on20!3!
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
#birdseye:
#  enabled: True
#  mode: continuous

go2rtc:
  streams:
    Office_g2:
      - rtsp://frigate:frigate1@10.146.1.243:554/cam/realmonitor
    Office_g2_sub:
      - rtsp://frigate:frigate1@10.146.1.243:554/cam/realmonitor?channel=1&subtype=1
    FrontYard_g2:
      - onvif://frigate:frigate1@10.146.1.241?subtype=MediaProfile000
      - "ffmpeg:rtsp_cam#audio=aac"
      #- rtsp://frigate:frigate1@10.146.1.241:554/cam/realmonitor?channel=1&subtype=0
    FrontYard_g2_sub:
      - rtsp://frigate:frigate1@10.146.1.241:554/cam/realmonitor?channel=1&subtype=2
    BackYard_g2:
      - rtsp://frigate:frigate1@10.146.1.242:554/cam/realmonitor?channel=1&subtype=0
    BackYard_g2_sub:
      - rtsp://frigate:frigate1@10.146.1.242:554/cam/realmonitor?channel=1&subtype=2
    webrtc:
      candidates:
        - 10.146.1.30:8555
        #- stun:8555
#live:
#  stream_name: FrontYard_g2
cameras:
  Office:
    detect:
      width: 640
      height: 480
      fps: 9
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Office_g2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Office_g2
          input_args: preset-rtsp-restream
          roles:
            - record
      #inputs:
      #  - path: rtsp://frigate:frigate1@10.146.1.243:554/cam/realmonitor?channel=1&subtype=0
      #    roles:
      #      - record
      #      - audio
      #  - path: rtsp://frigate:frigate1@10.146.1.243:554/cam/realmonitor?channel=1&subtype=1
      #    roles:
      #      - detect
  FrontYard:
    detect:
      width: 1280
      height: 720
      fps: 9
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
     # output_args:
     #  record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontYard_g2
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/FrontYard_g2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #inputs:
      #  - path: rtsp://frigate:frigate1@10.146.1.241:554/cam/realmonitor?channel=1&subtype=0
      #    roles:
      #      - record
      #      - audio
      #  - path: rtsp://frigate:frigate1@10.146.1.241:554/cam/realmonitor?channel=1&subtype=2
      #    roles:
      #      - detect
    zones:
      Frontyard_zn:
        coordinates: 
          0.001,0.035,0.006,0.99,0.988,0.99,0.991,0.105,0.561,0.101,0.544,0.016,0.004,0.019
        loitering_time: 0
    review:
      alerts:
        required_zones: Frontyard_zn
  BackYard:
    detect:
      width: 1280
      height: 720
      fps: 9
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/BackYard_g2
          input_args: preset-rtsp-restream-audio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard_g2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #inputs:
      #  - path: rtsp://frigate:frigate1@10.146.1.242:554/cam/realmonitor?channel=1&subtype=0
      #    roles:
      #      - record
      #     - audio
      #  - path: rtsp://frigate:frigate1@10.146.1.242:554/cam/realmonitor?channel=1&subtype=2
      #    roles:
      #      - detect
    zones:
      Backyard_zn:
        coordinates: 0.546,0.023,0.01,0.034,0.011,1,0.985,0.979,0.983,0.103,0.555,0.111
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: Backyard_zn
    motion:
      mask: 
        0.003,0.401,0.017,0.431,0.046,0.477,0.09,0.545,0.175,0.643,0.212,0.699,0.276,0.762,0.391,0.859,0.484,0.929,0.549,0.977,0.534,0.996,0.46,0.964,0.362,0.887,0.261,0.799,0.195,0.732,0.143,0.664,0.087,0.592,0.036,0.529,0.005,0.458
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - dog
      - car
    retain:
      default: 30
      mode: motion
  #ov:
  #  type: openvino
  #  device: CPU
  #  model:
  #    path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
#model:
#  width: 320
#  height: 320
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
version: 0.14
```

### Relevant Frigate log output

```shell
no error message
```

### Relevant go2rtc log output

```shell
not really getting an error.  

Time	Level	Message
5:27:36.175 PM	info	go2rtc version=1.9.7 platform=linux/amd64 revision=dbe9e4a
5:27:36.175 PM	info	config path=/dev/shm/go2rtc.yaml
5:27:36.175 PM	info	[rtsp] listen addr=:8554
5:27:36.175 PM	info	[api] listen addr=:1984
5:27:36.176 PM	info	[webrtc] listen addr=:8555/tcp
8:38:16.115 PM	warn	undefined error=read tcp 10.146.1.30:49538->10.146.1.241:554: i/o timeout url=rtsp://frigate:frigate1@10.146.1.241:554/cam/realmonitor?channel=1&subtype=2 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
8:38:16.119 PM	warn	undefined error=read tcp 10.146.1.30:49554->10.146.1.241:554: i/o timeout url=onvif://frigate:frigate1@10.146.1.241?subtype=MediaProfile000 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
8:38:16.150 PM	warn	undefined error=read tcp 10.146.1.30:55304->10.146.1.243:554: i/o timeout url=rtsp://frigate:frigate1@10.146.1.243:554/cam/realmonitor?channel=1&subtype=1 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
8:38:16.150 PM	warn	undefined error=read tcp 10.146.1.30:55292->10.146.1.243:554: i/o timeout url=rtsp://frigate:frigate1@10.146.1.243:554/cam/realmonitor?channel=1&subtype=0 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
8:38:16.156 PM	warn	undefined error=read tcp 10.146.1.30:48672->10.146.1.242:554: i/o timeout url=rtsp://frigate:frigate1@10.146.1.242:554/cam/realmonitor?channel=1&subtype=2 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
8:38:16.165 PM	warn	undefined error=read tcp 10.146.1.30:48676->10.146.1.242:554: i/o timeout url=rtsp://frigate:frigate1@10.146.1.242:554/cam/realmonitor?channel=1&subtype=0 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
8:38:32.201 PM	warn	[rtsp] error=streams: dial tcp 10.146.1.242:554: i/o timeout stream=BackYard_g2
```

### FFprobe output from your camera

```shell
{
    "producers": [
        {
            "id": 1125,
            "format_name": "rtsp",
            "protocol": "rtsp+tcp",
            "remote_addr": "10.146.1.241:554",
            "url": "rtsp://frigate:frigate1@10.146.1.241:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif",
            "sdp": "v=0\r\no=- 2252453651 2252453651 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:15.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D4033;sprop-parameter-sets=Z01AM42NQB4AIf//48QjxA3AQEBQAAA+gAAHUw6GAB1MAAAOThwu8uNDAA6mAAAHJw4XeXCgAA==,aO44gAA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=recvonly\r\nm=application 0 RTP/AVP 107\r\na=control:trackID=4\r\na=rtpmap:107 vnd.onvif.metadata/90000\r\na=recvonly\r\n",
            "user_agent": "go2rtc/1.9.7",
            "medias": [
                "video, recvonly, H264",
                "audio, recvonly, MPEG4-GENERIC/8000",
                "application, recvonly, VND.ONVIF.METADATA"
            ],
            "receivers": [
                {
                    "id": 1134,
                    "codec": {
                        "codec_name": "h264",
                        "codec_type": "video",
                        "level": 51,
                        "profile": "Main"
                    },
                    "childs": [
                        1135,
                        2509
                    ],
                    "bytes": 2174558624,
                    "packets": 1598999
                },
                {
                    "id": 1136,
                    "codec": {
                        "codec_name": "aac",
                        "codec_type": "audio",
                        "sample_rate": 8000
                    },
                    "childs": [
                        1137,
                        2510
                    ],
                    "bytes": 4473088,
                    "packets": 17681
                }
            ],
            "bytes_recv": 2198471736
        }
    ],
    "consumers": [
        {
            "id": 1124,
            "format_name": "rtsp",
            "protocol": "rtsp+tcp",
            "remote_addr": "127.0.0.1:49894",
            "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.7\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D4033;sprop-parameter-sets=Z01AM42NQB4AIf//48QjxA3AQEBQAAA+gAAHUw6GAB1MAAAOThwu8uNDAA6mAAAHJw4XeXCgAA==,aO44gAA=\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=control:trackID=1\r\n",
            "user_agent": "FFmpeg Frigate/0.14.1-",
            "medias": [
                "video, sendonly, H264, H265",
                "audio, sendonly, MPEG4-GENERIC"
            ],
            "senders": [
                {
                    "id": 1135,
                    "codec": {
                        "codec_name": "h264",
                        "codec_type": "video",
                        "level": 51,
                        "profile": "Main"
                    },
                    "parent": 1134,
                    "bytes": 2174558624,
                    "packets": 1598999
                },
                {
                    "id": 1137,
                    "codec": {
                        "codec_name": "aac",
                        "codec_type": "audio",
                        "sample_rate": 8000
                    },
                    "parent": 1136,
                    "bytes": 4473088,
                    "packets": 17681
                }
            ],
            "bytes_send": 2204898592
        },
        {
            "id": 2508,
            "format_name": "probe",
            "protocol": "http",
            "remote_addr": "10.146.1.200:59033",
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
            "medias": [
                "video, sendonly, ALL",
                "audio, sendonly, ALL",
                "audio, recvonly, ANY"
            ],
            "senders": [
                {
                    "id": 2509,
                    "codec": {
                        "codec_name": "h264",
                        "codec_type": "video",
                        "level": 51,
                        "profile": "Main"
                    },
                    "parent": 1134
                },
                {
                    "id": 2510,
                    "codec": {
                        "codec_name": "aac",
                        "codec_type": "audio",
                        "sample_rate": 8000
                    },
                    "parent": 1136
                }
            ]
        }
    ]
}
```

### Frigate stats

```json
not sure what this is
```

### Operating system

Debian

### Install method

Proxmox via TTeck Script

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Amcrest IP8M #####

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/86d4f2a7-9517-4c21-8f48-867f2d9c8d36)

### Any other information that may be helpful

Very basic setup.  I am new to frigate moving away from blueiris.   I am a cctv technician with 21 years of experience but enterprise systems are GUI based so this is a learning experience for me.   Despite the learning curve I love it so far.  If only my HA playback worked.
