### DISCUSSION TITLE
[Camera Support]: Hikvision DS-2CD2387G2P-LSU/SL live stream doesn't load correctly

### DISCUSSION THREAD

**Discussion by Mystically11** [blakeblackshear/frigate#15170] [Camera Support]
### Describe the problem you are having

Anytime i click on the camera's live stream, it loads for around 20 seconds, then the loading icon disappears, there is a red border around the stream that i can't see for a couple seconds, then it starts loading again and ends up loading the low quality substream which looks broken, there are random colors and lines in all placed and it runs at around 5 fps. Inside the camera administrator UI, both streams load fine with a clear image.

I am expecting it to load the "record" stream and play smoothly.

Recording playbacks work fine and show the actual 4k main stream in the right framerate. Camera stream is set to h264, network is stable.

Does anyone have an idea of what could be causing this issue?

### Version

0.15.0-e76f4e9

### What browser(s) are you using?

Firefox 132.0.2

### Frigate config file

```yaml
ffmpeg:
  output_args:
    record: preset-record-generic
  #hwaccel_args: preset-nvidia-h264

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: false
  min_initialized: 2

semantic_search:
  enabled: true
  reindex: false

record:
  enabled: true
  retain:
    days: 2
  alerts:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 10
snapshots:
  enabled: false
  timestamp: true

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.7
      threshold: 0.7
      min_ratio: 0.25
      max_ratio: 3

go2rtc:
  streams:
    mainentrance_cam:
      - rtsp://redacted:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/101
      - "ffmpeg:mainentrance_cam#video=h264#audio=aac"
    mainentrance_cam_sub:
      - rtsp://redacted:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/102
      - "ffmpeg:mainentrance_cam_sub#video=h264#audio=aac"
  webrtc:
    candidates:
      - 192.168.xx.xx:8555
      - stun:8555

cameras:
  mainentrance_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/mainentrance_cam
          roles:
            - record
        - path: rtsp://localhost:8554/mainentrance_cam_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 536
      enabled: true
    zones:
      entrance_zone:
        coordinates: 0.271,0.834,0.584,0.829,0.874,0.574,0.936,0.642,0.842,1,0.19,1
        inertia: 3
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: true
    motion:
      mask:
        - 0.88,0.299,0.969,0.468,0.942,0.644,0.874,0.551
        - 0.19,0.564,0.179,0,0,0,0,0.592,0.082,0.517,0.153,0.473
        - 0.943,0.66,1,0.701,1,1,0.844,1
    review:
      alerts: {}
      detections: {}
```

### Relevant Frigate log output

```shell
No errors
```

### Relevant go2rtc log output

```shell
info    | 2024-11-25 11:44:31 | startup | Preparing new go2rtc config...
info    | 2024-11-25 11:44:31 | startup | Not injecting WebRTC candidates into go2rtc config as it has been set manually
info    | 2024-11-25 11:44:31 | startup | Starting go2rtc...
info    | 2024-11-25 11:44:31 | startup | go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info    | 2024-11-25 11:44:31 | startup | config path=/dev/shm/go2rtc.yaml
info    | 2024-11-25 11:44:31 | api     | listen addr=:1984
info    | 2024-11-25 11:44:31 | rtsp    | listen addr=:8554
info    | 2024-11-25 11:44:31 | webrtc  | listen addr=:8555
info    | 2024-11-25 11:44:41 | startup | Starting go2rtc healthcheck service...
info    | 2024-11-25 11:44:59 | streams | can't add track error="wrong media: audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/48000"
warning | 2024-11-25 11:44:59 | startup | github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://redacted:redacted@192.168.xx.xx:554/Streaming/Channels/101
warning | 2024-11-25 11:44:59 | startup | github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:mainentrance_cam#video=h264#audio=aac
```

### FFprobe output from your camera

```shell
bash: ffprobe: not found
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2387G2P-LSU/SL

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/e9d08cc8-6bae-425b-866c-7582b5ee350d)
![image](https://github.com/user-attachments/assets/cbea0481-7cad-4476-979d-485fb88cfe47)
![image](https://github.com/user-attachments/assets/de7ac46c-f2b6-48cc-b2f9-038e1f022f64)
