### DISCUSSION TITLE
Frigate Missing Recordings

### DISCUSSION THREAD

**Discussion by aayush-eatclub** [blakeblackshear/frigate#15183] [Ask A Question]
When analyzing the recording summary, I've noticed that some portions of each hour are missing from Frigate's recordings. This issue appears consistently across all hours, as the recording duration is always less than the ideal 3600 seconds for a full hour.

What could be the probable reasons for this discrepancy?
```
[{'hour': '11', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 1820}, {'hour': '10', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3124}, {'hour': '09', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3216}, {'hour': '08', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3243}, {'hour': '07', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3253}, {'hour': '06', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3304}, {'hour': '05', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3243}, {'hour': '04', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 3145}, {'hour': '03', 'events': 0, 'motion': 0, 'objects': 0, 'duration': 2542}]
```

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "3072mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /home/outletmanager/outletvideocam:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "8971:8971"
      - "5001:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
        resources:
            limits:
              cpus: "2"
              memory: 6000M
            reservations:
              cpus: "1"
              memory: 3000M
```

```
auth:
  enabled: false
birdseye:
  enabled: false
cameras:
  cam_31:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.31/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_34:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.34/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_35:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.35/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_36:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.36/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_38:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.38/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_39:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.39/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_40:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.40/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_42:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.42/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_43:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.43/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
  cam_44:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:box8@123@192.168.9.44/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
detect:
  enabled: false
detectors:
  detector_name:
    type: cpu
ffmpeg:
  hwaccel_args: preset-vaapi
motion:
  enabled: false
mqtt:
  enabled: false
record:
  enabled: true
  retain:
    days: 1
    mode: all
  sync_recordings: true
tls:
  enabled: false
version: 0.15-0
```
