### DISCUSSION TITLE
Recording not available in Frigate Dash

### DISCUSSION THREAD

**Discussion by pvillmann** [blakeblackshear/frigate#15181] [Ask A Question]
Hi,

I have a problem with the configuration of recordings.

My plan the store the recordings like the example "Reduced storage" in the docs.
For that, like in docs, I set the camera specific config like follwing.

At the Frigate Dash i see only recordings from the last 3 days.
In Homeassistant, where Frigate is connected via the offical integration, i see at the Folder recordings also only 3 days, but at the folder "Clips", is see all clips within the last 30 days but cannot play them (i found something about an issue here with HomeAssistant right?)

The main question is, why i see only the last 3 days in Frigate Dash?

```
Haustuer_CAM:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/haustuer
          input_args: preset-rtsp-generic
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/haustuer_sub
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      retain:
        default: 10
        objects:
          person: 30
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
    motion:
      mask:
        - 0.281,0.013,0.698,0.012,0.702,0.05,0.281,0.053
        - 0.466,0.553,0.464,0.365,0,0.314,0,0.672
    live:
      stream_name: haustuer
    review:
      detections:
        labels:
        required_zones: private
      alerts:
        required_zones: private
    zones:
      private:
        coordinates: 
          0,0.874,0.464,0.594,0.464,0.131,0.707,0.113,0.724,0.002,0.997,0.003,0.996,0.997,0.003,0.994
```
