### DISCUSSION TITLE
[Bug]: Submit to Frigate+ widescreen issue

### DISCUSSION THREAD

**Discussion by WGrobler** [blakeblackshear/frigate#15195] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When using the "Submit to Frigate+" feature the div height exceeds the screen size resulting in the top and bottom buttons falling outside the screen area. 

I tried it on Chrome _[131.0.6778.86 (Official Build) (64-bit)]_ as well as Firefox _[132.0.2 (64-bit)]_

I've included some screenshots about the issue:

![image](https://github.com/user-attachments/assets/c9568242-9724-4569-92cd-138a09b33bb8)

![image](https://github.com/user-attachments/assets/f91153d8-1c97-49a0-8b3d-4c6433f77554)

When using on mobile/portrait mode it works correctly

![image](https://github.com/user-attachments/assets/553e83c2-f7df-4254-8383-9c32b8bcb98e)

### Steps to reproduce

1. Set up frigate v 0.14.1
2. Connect Frigate+ API
3. Open detection for review
...

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Chrome 131.0.6778.86 (Official Build) (64-bit)

### Frigate config file

```yaml
mqtt:
detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 5
    mode: active_objects

snapshots:
  enabled: true
  clean_copy: false
  timestamp: true
  bounding_box: true
  crop: true
  retain:
    default: 30
    objects:
      person: 45
  quality: 70

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - car
    - dog

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - bark
      - dog
      - scream
      - speech
      - yell

cameras:
  camera_name:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://username:password@192.168.20.2:554/Streaming/Channels/1
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - speech
        - yell    
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "512mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: all # number of GPUs
              capabilities: [gpu]
  hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5001:5000"
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Hikvision

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/df5bfe01-ba49-4077-aa08-d3443fa85baa)
