### DISCUSSION TITLE
[Support]: s6-overlay-suexec fatal error

### DISCUSSION THREAD

**Discussion by luisrx7** [blakeblackshear/frigate#15191] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I was up & running Frigate since August 2024 without any issues until yesterday when I edited the compose file and increased the `shm_size` from `300mb` to `400mb` I could not start the container anymore. The only error I get is `s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable`. I tried to change the `shm_size` to the old value but this error keeps popping up

### Steps to reproduce

1. stop container
2. increase shm_size
3. start container

### Version

0.14.1

### In which browser(s) are you experiencing the issue with?

issue not related with browser

### Frigate config file

```yaml
go2rtc:
  streams:
    Garagem:
      - dvrip://XXXXXXXXXX:XXXXXXXXXXXX@192.168.2.199:34567?channel=0&subtype=0
    Gabinete:
      - dvrip://XXXXXXXXXX:XXXXXXXXXXXX@address1:34567?channel=0&subtype=0
    Entrada_Alhadas:
      - dvrip://XXXXXXXXXX:XXXXXXXXXXXX@address2:34567?channel=0&subtype=0
    Traseiras_Alhadas:
      - dvrip://XXXXXXXXXX:XXXXXXXXXXXX@address2:34568?channel=0&subtype=0

cameras:
  Traseiras_Alhadas:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Traseiras_Alhadas?video&audio 
          input_args: preset-rtsp-restream
          roles:
             - detect
          #   - record
             - audio
    onvif:
      host: address2
      port: 8999
      user: XXXXXXXXXX
      password: XXXXXXXXXXXX
  Garagem:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Garagem?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    onvif:
      host: 192.168.2.199
      port: 8899
      user: XXXXXXXXXX
      password: XXXXXXXXXXXX

    detect:
      enabled: true 
      #width: 1280
      #height: 720
    motion:
      mask:
        - 0.796,0.043,0.996,0.046,0.995,0.025,0.787,0.022
        - 0.263,0,0.294,0.02,0.291,0.046,0.409,0.053,0.416,0.034,0.482,0
      threshold: 30
      contour_area: 12
      improve_contrast: true
    zones:
      zo_gar_estrada:
        coordinates: 
          0.149,0.497,0,0.495,0.001,0.234,0.127,0.173,0.271,0.124,0.345,0.101,0.409,0.092,0.475,0.08,0.487,0.09,0.413,0.118,0.312,0.184,0.232,0.321
        loitering_time: 0
        inertia: 3
      zo_gar_frente_da_casa:
        coordinates: 
          0.486,0.105,0.42,0.13,0.329,0.184,0.249,0.316,0.164,0.495,0.508,0.495,0.484,0.309,0.496,0.182,0.482,0.173
        loitering_time: 1
        inertia: 3
      zo_gar_porta_cozinha:
        coordinates: 
          0.517,0.499,0.489,0.317,0.507,0.03,0.783,0.039,0.781,0.229,1,0.278,1,0.498,0.668,0.496
        loitering_time: 0
        inertia: 3
      zo_gar_vizinho:
        coordinates: 
          0.001,0.226,0.146,0.162,0.27,0.118,0.354,0.095,0.421,0.084,0.486,0.074,0.487,0.043,0.421,0.038,0.42,0.055,0.29,0.05,0.29,0.023,0.25,0,0.066,0,0.065,0.017,0,0.023
        loitering_time: 0
    objects:
      mask: 0.781,0.579,0.869,0.607,0.87,0.675,0.81,0.665,0.749,0.652
    review:
      alerts:
        required_zones:
          - zo_gar_porta_cozinha
          - zo_gar_frente_da_casa
  Gabinete:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Gabinete?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio

    detect:
      enabled: true 
      #width: 1280
      #height: 720
    motion:
      threshold: 35
      contour_area: 18
      improve_contrast: 'true'

    zones:
      zo_gab_entrada:
        coordinates: 0.45,0.226,0.449,0.353,0.72,0.204,0.696,0.196,0.699,0.101,0.452,0.126
        loitering_time: 10
        objects: person
        inertia: 3
      zo_gab_estacionamento:
        coordinates: 
          0.453,0.391,0.937,0.495,1,0.249,0.974,0.231,0.927,0.23,0.811,0.21,0.681,0.194,0.551,0.24,0.451,0.277
        loitering_time: 10
        objects:
          - person
          - bicycle
          - car
        inertia: 3
      zo_gab_passagem:
        coordinates: 
          0.407,0.395,0.11,0.293,0,0.217,0,0.146,0.044,0.14,0.053,0.179,0.277,0.225,0.403,0.22
        loitering_time: 10
        objects:
          - person
          - car
      zo_gab_cave:
        coordinates: 0.17,0.198,0.172,0.086,0.402,0.072,0.403,0.212,0.278,0.22
        loitering_time: 10
        objects: []
      zo_gab_varanda:
        coordinates: 0.177,0.076,0.496,0.07,0.497,0.001,0.18,0.003
        loitering_time: 10
        objects: []
      zo_gab_jardim:
        coordinates: 0.001,0.225,0.104,0.304,0.406,0.402,0.173,0.495,0,0.496
        loitering_time: 10
        objects: []
    review:
      alerts:
        required_zones:
          - zo_gab_entrada
          - zo_gab_estacionamento
          - zo_gab_passagem


    objects:
      mask: 0.409,0.504,0.409,0.561,0.609,0.543,0.603,0.502
      filters:
        car:
          mask:
            - 0.409,0.504,0.409,0.561,0.609,0.543,0.603,0.502
            - 0.746,0.127,0.733,0.196,0.947,0.224,0.966,0.152
            - 0.409,0.504,0.409,0.561,0.609,0.543,0.603,0.502
            - 0.314,0.573,0.318,0.643,0.418,0.655,0.591,0.655,0.586,0.574
            - 0.409,0.504,0.409,0.561,0.609,0.543,0.603,0.502
            - 0.65,0.623,0.734,0.786,0.823,0.76,0.997,0.767,0.995,0.606,0.784,0.589,0.655,0.582
  Entrada_Alhadas:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Entrada_Alhadas?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    onvif:
      host: address2
      port: 8899
      user: XXXXXXXXXX
      password: XXXXXXXXXXXX

    detect:
      enabled: true 
      #width: 1280
      #height: 720
    motion:
      threshold: 30
      contour_area: 12
      improve_contrast: true
      mask:
        - 0.47,0.145,0.445,0.179,0.541,0.19,0.572,0.164,0.564,0.146
        - 0.537,0.197,0.582,0.286,0.615,0.291,0.687,0.204,0.695,0.144,0.66,0.115,0.629,0.108,0.588,0.114,0.572,0.139
    zones:
      zo_ea_jardim:
        coordinates: 0.001,0.495,0,0.261,0.077,0.222,0.866,0.295,0.845,0.414,0.687,0.39,0.645,0.495
        loitering_time: 2
        objects:
          - person
          - car
      zo_ea_janela_frente:
        coordinates: 0.648,0.495,0.688,0.391,0.844,0.416,0.835,0.494
        loitering_time: 2
        inertia: 3
        objects:
          - person
      zo_ea_estrada:
        coordinates: 0,0.251,0.075,0.216,0.455,0.16,0.456,0.115,0.071,0.142,0.002,0.18
        loitering_time: 5
        objects: []
        inertia: 3
      zo_ea_vizinha:
        coordinates: 
          0.107,0.214,0.864,0.282,0.873,0.089,0.609,0.074,0.574,0.114,0.472,0.106,0.462,0.122,0.462,0.163
        loitering_time: 5
      zo_ea_entrada:
        coordinates: 
          0,0.51,0.586,0.505,0.777,0.505,0.976,0.506,0.979,0.558,0.998,0.578,0.995,0.997,0.003,0.998
        loitering_time: 2
        objects:
          - car
          - cat
          - person
    objects:
      filters:
        car: {}
      mask: 0.467,0.143,0.56,0.143,0.576,0.158,0.553,0.2,0.436,0.185
    review:
      alerts:
        required_zones:
          - zo_ea_janela_frente
          - zo_ea_jardim
          - zo_ea_entrada
version: 0.14


audio:
  enabled: true
  listen:
    - bark
    - scream
    - speech
    - yell

record:
  enabled: true
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: very_high
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 30
  quality: 100

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640


review:
  alerts:
    labels:
      - car
      - person


objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - cat
    - dog

  filters:
    person:
      # # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 1000
      # # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      # max_area: 100000
      # # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      # min_ratio: 0.5
      # # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      # max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.55
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
    car:
      min_score: 0.7
      threshold: 0.85

    bicycle:
      min_area: 1000
      min_score: 0.65

detect:
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  restream: true
  # width: 2304
  # height: 2592
  mode: objects


mqtt:
  enabled: true
  host: 192.168.2.60
  port: 1883
  user: fri123gate
  password: 'secretpassword'
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: '350mb' # update for your cameras based on calculation above
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
          cpus: '0.25'
          memory: 4G
        limits:
          cpus: '0.50'
          memory: 5G
          pids: 1

    #devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/nvr/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - YOLO_MODELS=yolov7x-640
      - USE_FP16=false
    healthcheck:
      test: curl --fail http://localhost:5000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
```

### Relevant Frigate log output

```shell
root@g-docker:~/frigate# docker compose up
[+] Running 1/0
 ✔ Container frigate  Created                                                                     0.0s 
Attaching to frigate
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate exited with code 0
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
frigate  | s6-overlay-suexec: fatal: unable to spawn /package/admin/s6-overlay-3.1.5.0/libexec/preinit: Resource temporarily unavailable
```

### Relevant go2rtc log output

```shell
can even boot go2rtc to get any logs
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

aliexpress model that's been working file

### Screenshots of the Frigate UI's System metrics pages

cannot boot frigate to show this

### Any other information that may be helpful

I tried booting Frigate without any `config.yaml`  and `frigate.db` but got the same error.
I deleted the docker image and pulled it again but got the same error.

**Comment by hawkeye217** [comment]
"Resource temporarily unavailable" when trying to spawn a process is sometimes related to threading limits. 

What system are you running on? Have you tried rebooting? Can you consistently reproduce the error?

**Reply by luisrx7** [reply]
I'm running Proxmox on a 4-core CPU with 40GB of RAM, frigate was running on a privileged LXC container with 10GB of RAM and 4 vCPU. I have tried rebooting the host multiple times, I tried booting only the frigate LXC container to evaluate your hypothesis of being a threading limit without any luck. 
I cannot reproduce the error because I don't have disk space to recreate the LXC container.

**Reply by hawkeye217** [reply]
Proxmox is technically an unsupported installation method, and this isn't an error we've seen before. I'll close this for now but if you are able to reproduce it, feel free to reopen this discussion.

**Reply by luisrx7** [reply, marked as answer]
For anyone encountering this issue in the future:  

After reproducing the problem several times, I discovered the root cause of the problem. When I was configuring the memory limits using the following settings:  

```yaml
limits:
  cpus: '0.50'
  memory: 5G
  pids: 1
```

The issue was caused by the `pids: 1` setting. Once I commented it out, Frigate started running smoothly.
