### DISCUSSION TITLE
[Config Support]: Frequent Crashes F driver/usb/usb_driver.cc:815]

### DISCUSSION THREAD

**Discussion by vcdx71** [blakeblackshear/frigate#15193] [Config Support]
### Describe the problem you are having

New setup. Host is Unraid, specs:
2 x Intel® Xeon® CPU E5-2690 v2 @ 3.00GHz
256 GB RAM
~50 TB ZFS volume
2 x Coral USB
Nvidia Quadro P1000
Unifi Protect Cameras

Corals are plugged into a 4 port PCIe USB 3 card in the server.

My setup will run anywhere from 10 minutes to a few hours, then crashes and restarts. About half the time on restart only some of the camera feeds will start, the rest of time I get the No frames received message.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.2.18
  user: frigate
  password: XXXX

auth:
  enabled: true
  reset_admin_password: false
  session_length: 86400 # 24 hours
  refresh_time: 43200 # 12 hours
  hash_iterations: 600000

record:
  enabled: true
  retain:
    days: 30
    mode: motion
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      mode: motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 10
    objects:
      person: 20
  quality: 100

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

objects:
  track:
    - person
    - car
    - bird
    - dog
  filters:
    person:
      min_area: 1000
      max_area: 24000000
      min_ratio: 0
      max_ratio: 24000000
      min_score: 0.5
      threshold: 0.7

detect:
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

review:
  alerts:
    labels:
      - car
      - person
      - bird

ffmpeg:
  output_args:
    record: preset-record-ubiquiti
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    gate:
      - rtspx://192.168.2.1:7441/rsH6U41A4i16bHar
    game_room:
      - rtspx://192.168.2.1:7441/CuL15huinYRtcris
    fish:
      - rtspx://192.168.2.1:7441/LlhaseMiS5hjdZtD
    school:
      - rtspx://192.168.2.1:7441/odzfUlXUanYCA0Is
    dylan:
      - rtspx://192.168.2.1:7441/ASPBVru6CM8uxvbZ
    chickens:
      - rtspx://192.168.2.1:7441/YAW2hpitAn9OWaGt
    field:
      - rtspx://192.168.2.1:7441/NkqgXgNq4gjuXQeT
    jobe:
      - rtspx://192.168.2.1:7441/1Z9Zx3qiFP8l8m69
    joss:
      - rtspx://192.168.2.1:7441/IzXWlUGpZRQ8e3mb
  webrtc:
    candidates:
      - 192.168.2.3:8555
      - stun:8555


cameras:
  gate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate
          roles:
            - record
            - detect
    motion:
      mask:
        - 0.257,0.034,0.258,0,0.002,0.001,0.004,0.035
        - 0.218,0,0.222,0.176,1,0.358,0.996,0.001
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Driveway:
        coordinates: 0.221,0.444,0.371,1,1,1,1,0.628,0.771,0.472,0.592,0.352,0.369,0.381
        loitering_time: 0
        inertia: 3
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  game_room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/game_room
          roles:
            - record
            - detect
    motion:
      mask:
        - 0.315,0.036,0.315,0.004,0.002,0.001,0.003,0.038
        - 0.624,0.299,0.626,0.365,0.745,0.373,0.742,0.303
        - 0.707,0.08,0.701,0.22,0.984,0.211,0.991,0.067
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  fish:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fish
          roles:
            - record
            - detect
    motion:
      mask: 0.256,0.033,0.255,0,0.002,0.001,0.003,0.038
      threshold: 60
      contour_area: 20
      improve_contrast: 'true'
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  school:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/school
          roles:
            - record
            - detect
    motion:
      mask: 0.312,0.038,0.312,0,0.002,0.001,0.003,0.038
    zones:
      schoolRoom:
        coordinates: 0.199,1,0.359,0.963,0.628,0.867,0.89,0.706,0.75,0.49,0.687,0.315,0.235,0.386
        loitering_time: 0
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  dylan:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dylan
          roles:
            - record
            #- detect
    motion:
      mask: 0.27,0.039,0.269,0,0.002,0.001,0.003,0.038
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  chickens:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/chickens
          roles:
            - record
            - detect
    motion:
      mask: 0.294,0.033,0.294,0,0.002,0.001,0.003,0.038
      threshold: 34
      contour_area: 10
      improve_contrast: 'true'
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  field:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/field
          roles:
            - record
            #- detect
    motion:
      mask: 1,0.592,1,0,0.002,0.001,0,0.594
      threshold: 34
      contour_area: 10
      improve_contrast: 'true'
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  jobe:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jobe
          roles:
            - record
            - detect
    motion:
      mask:
        - 0.256,0.033,0.255,0,0.002,0.001,0.003,0.038
        - 0.296,0.82,0.296,0.921,0.454,0.95,0.383,0.762
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
  joss:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/joss
          roles:
            - record
            - detect
    motion:
      mask: 0.256,0.033,0.255,0,0.002,0.001,0.003,0.038
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
version: 0.14
```

### Relevant Frigate log output

```shell
2024-11-25 16:34:26.808522878  F driver/usb/usb_driver.cc:815] [0-0] bulk out for header failed. Abort. Unavailable: USB error -4 [AsyncBulkOutTransfer]
024-11-25 16:34:26.808549744  Fatal Python error: Aborted
2024-11-25 16:34:26.808551453  
2024-11-25 16:34:26.808604154  Thread 0x000014806c9de6c0 (most recent call first):
2024-11-25 16:34:26.808675645    File "/usr/lib/python3.9/threading.py", line 312 in wait
2024-11-25 16:34:26.808703415    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
2024-11-25 16:34:26.808750567    File "/usr/lib/python3.9/threading.py", line 892 in run
2024-11-25 16:34:26.808803359    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
2024-11-25 16:34:26.808840810    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
2024-11-25 16:34:26.808842313  
2024-11-25 16:34:26.808851040  Thread 0x00001480b6bd5740 (most recent call first):
2024-11-25 16:34:26.808902701    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
2024-11-25 16:34:26.808971340    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 61 in detect_raw
2024-11-25 16:34:26.809019263    File "/opt/frigate/frigate/object_detection.py", line 75 in detect_raw
2024-11-25 16:34:26.809075921    File "/opt/frigate/frigate/object_detection.py", line 125 in run_detector
2024-11-25 16:34:26.809177367    File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
2024-11-25 16:34:26.809258576    File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
2024-11-25 16:34:26.809405869    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
2024-11-25 16:34:26.809490605    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
2024-11-25 16:34:26.809596406    File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
2024-11-25 16:34:26.809669653    File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
2024-11-25 16:34:26.809719077    File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
2024-11-25 16:34:26.809775863    File "/opt/frigate/frigate/object_detection.py", line 183 in start_or_restart
2024-11-25 16:34:26.809824539    File "/opt/frigate/frigate/object_detection.py", line 151 in __init__
2024-11-25 16:34:26.809902925    File "/opt/frigate/frigate/app.py", line 429 in start_detectors
2024-11-25 16:34:26.809951941    File "/opt/frigate/frigate/app.py", line 690 in start
2024-11-25 16:34:26.810029871    File "/opt/frigate/frigate/__main__.py", line 17 in <module>
2024-11-25 16:34:26.810103790    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
2024-11-25 16:34:26.810168679    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
2024-11-25 16:34:35.387327183  [2024-11-25 16:34:35] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
```

### Relevant go2rtc log output

```shell
None that I've seen.
```

### Frigate stats

```json
{"cameras":{"chickens":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":755,"detection_enabled":true,"detection_fps":1.1,"ffmpeg_pid":761,"pid":696,"process_fps":5.0,"skipped_fps":0.0},"dylan":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":750,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":756,"pid":686,"process_fps":5.0,"skipped_fps":0.0},"field":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":760,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":766,"pid":702,"process_fps":5.0,"skipped_fps":0.0},"fish":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":740,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":748,"pid":670,"process_fps":5.0,"skipped_fps":0.0},"game_room":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":736,"detection_enabled":true,"detection_fps":6.7,"ffmpeg_pid":744,"pid":662,"process_fps":5.0,"skipped_fps":0.0},"gate":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":728,"detection_enabled":true,"detection_fps":0.6,"ffmpeg_pid":737,"pid":661,"process_fps":5.1,"skipped_fps":0.0},"jobe":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":765,"detection_enabled":true,"detection_fps":5.3,"ffmpeg_pid":771,"pid":710,"process_fps":5.1,"skipped_fps":0.0},"joss":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":770,"detection_enabled":true,"detection_fps":3.9,"ffmpeg_pid":781,"pid":720,"process_fps":5.1,"skipped_fps":0.0},"school":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":745,"detection_enabled":true,"detection_fps":2.5,"ffmpeg_pid":753,"pid":678,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"6.0","cpu_average":"12","mem":"0.1"},"121":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"189":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"193":{"cmdline":"nginx: worker process","cpu":"0.2","cpu_average":"0","mem":"0.0"},"195":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"198":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"203":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2116":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(62)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2553":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2558":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2563":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2574":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2688x1512 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2591":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2596":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2618":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2624":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2645":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2651":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"381":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"4054":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"446":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.0"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"603":{"cmdline":"frigate.recording_manager","cpu":"8.0","cpu_average":"6","mem":"0.1"},"607":{"cmdline":"frigate.review_segment_manager","cpu":"1.8","cpu_average":"0","mem":"0.1"},"631":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(73)","cpu":"0.6","cpu_average":"0","mem":"0.0"},"632":{"cmdline":"frigate.detector.coral1","cpu":"5.2","cpu_average":"10","mem":"0.1"},"635":{"cmdline":"frigate.detector.coral2","cpu":"5.1","cpu_average":"8","mem":"0.1"},"640":{"cmdline":"frigate.output       ","cpu":"9.5","cpu_average":"9","mem":"0.1"},"661":{"cmdline":"frigate.process:gate ","cpu":"3.4","cpu_average":"17","mem":"0.1"},"662":{"cmdline":"frigate.process:game_room","cpu":"20.8","cpu_average":"27","mem":"0.1"},"670":{"cmdline":"frigate.process:fish ","cpu":"1.6","cpu_average":"6","mem":"0.1"},"678":{"cmdline":"frigate.process:school","cpu":"7.4","cpu_average":"18","mem":"0.1"},"686":{"cmdline":"frigate.process:dylan","cpu":"1.4","cpu_average":"18","mem":"0.1"},"696":{"cmdline":"frigate.process:chickens","cpu":"5.6","cpu_average":"8","mem":"0.1"},"702":{"cmdline":"frigate.process:field","cpu":"1.5","cpu_average":"3","mem":"0.1"},"710":{"cmdline":"frigate.process:jobe ","cpu":"20.1","cpu_average":"34","mem":"0.1"},"720":{"cmdline":"frigate.process:joss ","cpu":"9.6","cpu_average":"12","mem":"0.1"},"728":{"cmdline":"frigate.capture:gate ","cpu":"3.2","cpu_average":"2","mem":"0.1"},"736":{"cmdline":"frigate.capture:game_room","cpu":"3.3","cpu_average":"2","mem":"0.1"},"737":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/gate -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/gate@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.7","cpu_average":"8","mem":"0.1"},"740":{"cmdline":"frigate.capture:fish ","cpu":"3.2","cpu_average":"2","mem":"0.1"},"744":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/game_room -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/game_room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.7","cpu_average":"8","mem":"0.1"},"745":{"cmdline":"frigate.capture:school","cpu":"6.0","cpu_average":"5","mem":"0.1"},"748":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/fish -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/fish@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.3","cpu_average":"8","mem":"0.1"},"750":{"cmdline":"frigate.capture:dylan","cpu":"1.6","cpu_average":"0","mem":"0.1"},"753":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/school -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/school@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=2688:h=1512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"13.6","cpu_average":"13","mem":"0.1"},"755":{"cmdline":"frigate.capture:chickens","cpu":"3.2","cpu_average":"2","mem":"0.1"},"756":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/dylan -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/dylan@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"4","mem":"0.1"},"760":{"cmdline":"frigate.capture:field","cpu":"3.3","cpu_average":"2","mem":"0.1"},"761":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/chickens -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/chickens@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.4","cpu_average":"8","mem":"0.1"},"765":{"cmdline":"frigate.capture:jobe ","cpu":"3.1","cpu_average":"2","mem":"0.1"},"766":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/field -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/field@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.4","cpu_average":"8","mem":"0.1"},"770":{"cmdline":"frigate.capture:joss ","cpu":"3.2","cpu_average":"2","mem":"0.1"},"771":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/jobe -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/jobe@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.1","cpu_average":"8","mem":"0.1"},"781":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/joss -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac /tmp/cache/joss@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.4","cpu_average":"8","mem":"0.1"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"5.6","cpu_average":"5","mem":"0.0"},"frigate.full_system":{"cpu":"16.9","mem":"25.5"}},"detection_fps":20.1,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":9.07,"pid":632},"coral2":{"detection_start":1732574732.756868,"inference_speed":9.01,"pid":635}},"gpu_usages":{"Quadro P1000":{"dec":"41.0%","enc":"0.0%","gpu":"4.0%","mem":"26.92%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":446},"recording":{"pid":603},"review_segment":{"pid":607}},"service":{"last_updated":1732574732,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":4048.5,"mount_type":"tmpfs","total":4096.0,"used":47.5},"/media/frigate/clips":{"free":44138565.9,"mount_type":"fuse.shfs","total":89456448.0,"used":45317882.1},"/media/frigate/recordings":{"free":44138565.9,"mount_type":"fuse.shfs","total":89456448.0,"used":45317882.1},"/tmp/cache":{"free":1390.0,"mount_type":"tmpfs","total":1430.5,"used":40.5}},"temperatures":{},"uptime":146,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='bridge'
  --pids-limit 2048
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="DarkKnight"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='XXXX'
  -e 'PLUS_API_KEY'='XXXXX'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-539f384d-1ecf-6512-b03d-4ea1bedb218f'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='compute,utility,video'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8971]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '8971:8971/tcp'
  -p '8554:8554/tcp'
  -p '5000:5000/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -v '/mnt/cache/appdata/frigate':'/config':'rw'
  -v '/mnt/user/Media/frigate':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/bus/usb'
  --shm-size=4G
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1500000000
  --restart unless-stopped
  --runtime=nvidia 'ghcr.io/blakeblackshear/frigate:stable'
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/8192f638-4c60-4039-ac0a-4bc9598b8720)
![image](https://github.com/user-attachments/assets/b13a3bbd-fc83-4d24-9369-fb705d087ca3)
![image](https://github.com/user-attachments/assets/22af47e0-9340-4120-bada-dcb51499e36b)
![image](https://github.com/user-attachments/assets/254094a2-498a-4e8d-bd05-f8354e01b05d)
![image](https://github.com/user-attachments/assets/8f528a9f-8f67-4eb4-a092-3411dca103b3)

### Any other information that may be helpful

I was previously seeing python bus errors, after bumping SHM up I no longer see those.
