### DISCUSSION TITLE
[Support]: Mask creation in brave does not allow me to close polygon.

### DISCUSSION THREAD

**Discussion by xanderphillips** [blakeblackshear/frigate#15229] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Brave: 1.73.9
Frigate: 0.14.1-f4f3cfa

When attempting to create a mask I cannot get the polygon to close.  Even if I hover the mouse around to get the first point to swell in size it just creates an additional point.  In Edge the polygon closes as expected.

### Steps to reproduce

1. Gear, General Settings, Masks / Zones
2. Plus to make new mask
3. Create multiple polygon points to create an enclosed space.
4. Unable to close polygon by clicking first point.
Only happening in Brave.  Edge works fine.

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Brave: 1.73.9

### Frigate config file

```yaml
# api key: redacted

# yaml-language-server: $schema=http://frigate:5000/api/config/schema.json
mqtt:
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  enabled: true
  host: mqtt

# Coral tpu device for object detection 
detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 15
    mode: active_objects
  events:
    pre_capture: 2
    retain:
      default: 90
      mode: active_objects

snapshots:
  enabled: true
  timestamp: true
  clean_copy: true
  crop: true
  retain:
    default: 30
    objects:
      person: 30

objects:
  track:
    - person
    - car
    - cat
    - dog
    - horse
    - motorcycle
  filters:
    person:
      min_score: 0.6

go2rtc:
  streams:
#    shop:
#      - "ffmpeg:rtsp://redacted:redacted@shopcam:554"
    driveway_camera:
      - ffmpeg:http://driveway/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=redacted&password=redacted

cameras:
#  shop:
#    ffmpeg:
#      hwaccel_args: preset-vaapi
#      inputs:
#        - path: rtsp://127.0.0.1:8554/shop
#          input_args: preset-rtsp-restream
#          roles:
#          - detect
#          - record

  office:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@10.1.1.19:554/ch0
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  woodshop:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@10.1.1.5/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    objects:
      filters:
        person:
          mask: 0.644,0.473,0.794,0.487,0.76,0.734,0.638,0.713
    motion:
      mask: 0.041,0.926,0.265,0.929,0.265,0.965,0.041,0.964
  driveway_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_camera
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      filters:
        car:
          mask: 1,0.14,0.825,0.127,0.811,0.209,1,0.549
    motion:
      mask: 0.496,0.924,0.971,0.927,0.971,0.971,0.495,0.978
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /frigate_data:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
 #     - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    environment:
      FRIGATE_RTSP_PASSWORD: "redacted"
      FRIGATE_MQTT_PASSWORD: "redacted"
      FRIGATE_MQTT_USER: "mqtt"
      LIBVA_DRIVER_NAME: "iHD"
      REOLINK_USER: "redacted"
      REOLINK_PW: "redacted"
```

### Relevant Frigate log output

```shell
N/a
```

### Relevant go2rtc log output

```shell
N/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/a

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-11-27 185327](https://github.com/user-attachments/assets/0f7fc19f-9146-4d05-a353-6b96d89a6de0)
![Screenshot 2024-11-27 185353](https://github.com/user-attachments/assets/a638471f-fc8c-4565-9d8e-44ac6e1cf729)
![Screenshot 2024-11-27 185419](https://github.com/user-attachments/assets/1663905f-2e7d-4634-be57-5c78554ecbc1)
