### DISCUSSION TITLE
[Detector Support]: 0.15 Beta2 custom Openvino/Onnx Yolo-Nas models causing wild detections on Frigate restart -- possible issue with model_cache

### DISCUSSION THREAD

**Discussion by mbronstein1** [blakeblackshear/frigate#15220] [Detector Support]
### Describe the problem you are having

Since upgrading to the newer version of Frigate 0.14+ (currently using Frigate 0.15 beta2), I've noticed some unexpected behaviors only on certain devices regarding detections. I am currently using a custom openvino/onnx yolo-nas model, and when Frigate starts up for the first time, everything runs smoothly.
![Screenshot 2024-11-27 at 9 50 53 AM](https://github.com/user-attachments/assets/c001cec3-4638-4a3a-bff3-67b7c3840909)

 However, when I restart Frigate in any way (either through the UI or docker compose), the detections go crazy, with up to 20 detections for forklift at 100% confidence (which is the 0 index in my labelmap).
![Screenshot 2024-11-27 at 9 51 37 AM](https://github.com/user-attachments/assets/71ec501c-419a-4701-8b9a-ce5c180f7059)

I noticed that a blob file is being added to the model_cache directory on startup and on restart is when it goes haywire. I decided to delete the model_cache file (which requires sudo permissions) and restart Frigate, and everything was working perfectly again. But again, the model_cache file gets created and when I restart Frigate, crazy detections again.
![Screenshot 2024-11-27 at 9 52 01 AM](https://github.com/user-attachments/assets/1af5cf50-964a-4aea-9249-83cad85f2d23)

I can't find much on model_cache in the docs or in the discussions but what I can find seems to be related to users with Frigate+ (which I am not). Looking through the source code, the only thing I notice w/ regards to the model_cache is downloading the model during embedding (not sure what that means tbh)? And the path always is pointing towards the model_cache dir. I cannot find anywhere where a blob file is being added to the model_cache dir.

When using Frigate 0.13.2, I noticed that I had a model_cache dir but it was always empty so I don't know if the model_cache is being filled by accident somehow now in 0.14+?

__a couple more observations__
- During these inconsistent detections, it is always `forklift`, which is the 0 index on my custom labelmap. I noticed that the default model for openvino/yolonas uses coco-80 and I believe the 0 index is `background`. I'm wondering if there is some mixup occurring where the built-in model is incorrectly being loaded on restart (or being saved in the model_cache accidentally) but my custom labelmap is still being referenced?
- This seems to mainly be happening on [Beelink EQ12 devices](https://www.amazon.com/Beelink-Windows-Desktop-Gigabit-Ethernet/dp/B09DPV3D4N/ref=mp_s_a_1_4?crid=3BT507DUWVBSM&dib=eyJ2IjoiMSJ9.znP-LV340Tq1_JdegpD3BI1zOY0LesssO-SHR2zCGIGSRtFAl92ChoeYe2Mj3UMfxgODvB3vCyvNx_7uw2KIbTQgMnqCG7dvsxf_yktG2vWh_x2TR6chRT5p28ycUvF6CyNbOLW98h3UNN7Xy-cD0pHRjKEbSjDBN2SGDec3lpiFsMAvnQdkv2WFUkstzdiuZuN83GZWtLzLfOh6baEQoQ.cFYWXBx2M4vIGay2th4aakTdogyQwGuRc-On2s9rLsk&dib_tag=se&keywords=eq12&qid=1732719536&sprefix=eq12%2Caps%2C115&sr=8-4). I tried running it on my personal Linux Fedora device and have not seen this issue once (even with a blob file being added to the model_cache dir).
- I do not store my models in /config but instead store them in a models dir (which is also added to the container volumes with the correct path in the config.yml)
![Screenshot 2024-11-27 at 10 28 01 AM](https://github.com/user-attachments/assets/7520f91a-3def-482d-a4ea-2db076088e8b)
- While I am currently using an openvino-exported model (.xml), originally I was using an onnx model (.onnx), and the results were the same (both listed in the image above).
- I have updated and upgraded all services on the device and rebooted many times, with the same results.

### Version

0.15.0-ff92b13

### Frigate config file

```yaml
mqtt:
  host: mqtt
  port: 8883
  topic_prefix: nvr
  client_id: nvr
  user: <username>
  password: <password>
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic
detectors:
  ov:
    type: openvino
    device: GPU
model:
  path: /model/yolo_nas_s.xml
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: rgb
  labelmap_path: /model/labelmap.txt
  model_type: yolonas
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true

objects:
  track:
    - person
    - forklift

review:
  alerts:
    labels:
      - person
      - forklift
motion:
  threshold: 60
  contour_area: 20
record:
  enabled: true
  retain:
    days: 1
    mode: motion
  alerts:
    retain:
      days: 7
      mode: active_objects
snapshots:
  enabled: true
  retain:
    default: 1
  bounding_box: true
  crop: true
logger:
  default: critical
auth:
  enabled: false
cameras:
  Repair21:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<hostname>:8554/repair21_detect
          roles:
            - detect
        - path: rtsp://<hostname>:8554/repair21_record
          roles:
            - record
    objects:
      track:
        - forklift
        - person
    live:
      stream_name: repair21_record
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
nvr:
    container_name: nvr
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:ff92b13 # beta2 + fix for manual event creation
    shm_size: '512mb' # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/nvr/config:/config
      - ./docker/nvr/storage:/media/frigate
      # - ./docker/models/yolonas_model:/model
      - ./docker/models/yolonas_ov_model:/model
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    # Add this to get GPU stats in Frigate
    cap_add: 
      - CAP_PERFMON
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    ports:
      # - '8971:8971' # for auth -- KEEP COMMENTED FOR NOW
      - '5000:5000'
      - '8554:8554' # RTSP feeds
      - '8555:8555/tcp' # WebRTC over tcp
      - '8555:8555/udp' # WebRTC over udp
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

N/A
