### DISCUSSION TITLE
Loss of recording during an emergency power outage

### DISCUSSION THREAD

**Discussion by ThisIsLamer** [blakeblackshear/frigate#15234] [General Support]
Hello everyone, I ran into an unpleasant incident yesterday. My house suddenly lost power, and accordingly, since my equipment did not have an uninterruptible power supply, it turned off. When the power came on, I found that the 4th street cameras were no longer online (but this situation has nothing to do with Frigate), and recording from these cameras was available exactly an hour before the emergency shutdown. That is, the power was turned off at 18:58, records are available until 18:00. At the same time, there is an activity of recordings in the web interface, that is, it seems as if the recording was conducted but disappeared somewhere.

You can see this in the screenshot below
-- Recording is available
![Без имени (1)](https://github.com/user-attachments/assets/3471133c-13ce-4fd7-a45e-6e72c9a91fbc)

-- There is no record
![image](https://github.com/user-attachments/assets/381b2b09-d93f-4558-9cdb-0f8967c7c9aa)

The availability of the recording disappears exactly at the 59th minute of the 59th second

here's what actually happens in the files
![image](https://github.com/user-attachments/assets/ae837373-1671-4e2d-8aa0-cb437124843d)

I also noticed that video files are recorded in mp4 format, which is not safe, since such files must be recorded to the end, if recording is prevented, such a file becomes unreadable

Also, the slider on the right shows that the cameras were still active at that time, for almost the entire hour, this can be determined by the yellow activity marks on the slider on the right

I can assume that maybe I don't have the correct configuration, so I'm attaching it too.

```yml
logger:
  default: warning

mqtt:
  host: mosquitto
  port: 1883
  user: '{FRIGATE_MQTT_LOGIN}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detect:
  enabled: true
  fps: 5

detectors:
  rknn:
    type: rknn
    num_cores: 3

objects:
  track:
    - person

model:
  path: deci-fp16-yolonas_m
  input_pixel_format: bgr
  width: 320
  height: 320
  input_tensor: nhwc

record:
  enabled: true
  retain:
    days: 42
    mode: all
  events:
    retain:
      default: 42

snapshots:
  enabled: true
  retain:
    default: 42

birdseye:
  enabled: true
  restream: true
  mode: continuous

go2rtc:
  streams:
    Street:
      rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.11/Streaming/Channels/101
    Entry:
      rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.12/Streaming/Channels/101
    Front_Yard:
      rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.13/Streaming/Channels/101
    Back_Yard:
      rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.14/Streaming/Channels/101
    Server_Room:
      rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.15/Streaming/Channels/101

cameras:
  Street:
    birdseye:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.11/Streaming/Channels/102
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h264
          roles:
            - audio
            - detect
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.11/Streaming/Channels/101
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h265
          roles:
            - record

  Entry:
    birdseye:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.12/Streaming/Channels/102
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h264
          roles:
            - audio
            - detect
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.12/Streaming/Channels/101
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h265
          roles:
            - record

  Front_Yard:
    birdseye:
      mode: objects
      order: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.13/Streaming/Channels/102
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h264
          roles:
            - audio
            - detect
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.13/Streaming/Channels/101
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h265
          roles:
            - record

  Back_Yard:
    birdseye:
      mode: objects
      order: 4
    ffmpeg:
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.14/Streaming/Channels/102
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h264
          roles:
            - detect
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.14/Streaming/Channels/101
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h265
          roles:
            - record

  Server_Room:
    birdseye:
      mode: objects
      order: 5
    ffmpeg:
      inputs:
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.15/Streaming/Channels/102
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h264
          roles:
            - detect
        - path:
            rtsp://{FRIGATE_CAMERA_LOGIN}:{FRIGATE_CAMERA_PASSWORD}@192.168.10.15/Streaming/Channels/101
          input_args: preset-rtsp-restream
          hwaccel_args: preset-rk-h264
          roles:
            - record

version: 0.14
```
