### DISCUSSION TITLE
[Support]: Issue with green video feeds, wrong orientation

### DISCUSSION THREAD

**Discussion by grainsoflight** [blakeblackshear/frigate#15231] [General Support] [answered]
### Describe the problem you are having

When the preview screen loads, some of my streams load with green screens. Often, this resolves after a few seconds, sometimes it doesnt resolve at all. Additionally, my "front" camera often appears with a portrait orientation, which also sometimes corrects itself, other times does not. There are no logged errors.

![Screenshot 2024-11-27 225717](https://github.com/user-attachments/assets/628badd5-e28f-4911-abff-a0d3ecaf9d9b)
![Screenshot 2024-11-27 225755](https://github.com/user-attachments/assets/da4abcb3-113f-4543-9a34-8cd5d64fdbf6)

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Brave v1.73.91

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: '!hponhftT13'
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.3:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://0.0.0.0:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    record:
      enabled: true
      retain:
        days: 14
    motion:
      mask:
        - 422,0,421,26,208,29,207,0
        - 222,112,293,45,436,51,453,123,442,279,218,302
    objects:
      filters:
        person:
          mask:
            - 301,0,0,0,0,480,230,480,229,100,265,99
            - 438,40,640,0,640,480,501,480,438,437
            - 234,102,305,21,440,52,445,187,228,185
    snapshots:
      enabled: true
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://0.0.0.0:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 8
    motion:
      mask:
        - 231,36,649,40,650,0,267,0,236,0
        - 456,0,460,217,374,258,347,0
        - 126,0,203,273,309,222,263,0
        - 587,0,578,138,508,167,509,0
        - 896,0,896,114,800,49,811,0
        - 114,41,174,49,174,84,38,80,39,43
    record:
      enabled: true
      retain:
        days: 14
    snapshots:
      enabled: true
    onvif:
      host: 192.168.5.2
      user: admin
      password: BW5ynKNVLDhQyS
    zones:
      zone_0:
        coordinates: 801,77,896,124,896,512,0,512,0,0
  backzoom: 
    ffmpeg:
      inputs:
        - path: rtsp://0.0.0.0:8554/backzoom
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    snapshots:
      enabled: false
    motion:
      mask:
        - 1259,0,1263,56,617,56,620,0
        - 356,78,361,166,54,159,59,68
    zones:
      zone_0:
        coordinates: 1920,0,1920,1080,0,1080,0,0
  # garage:
    # ffmpeg:
      #inputs:
      #- path: rtsp://0.0.0.0:8554/garage
       # input_args: preset-rtsp-restream
        #roles:
        #- record
        #- detect
    #detect:
     # width: 1920
      #height: 1080
      #fps: 5
   # record:
      #enabled: true
      #retain:
       # days: 7
        #mode: motion
      #events:
       # retain:
        #  default: 7
         # mode: active_objects
          #objects:
           # person: 14

    review:
      alerts:
        required_zones:
          - zone_0
  front:
    ffmpeg:
      inputs:
        - path: rtsp://0.0.0.0:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record    
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.4:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      height: 640
      width: 360
      fps: 7
    record:
      enabled: true
      retain:
        days: 14  
go2rtc:
  streams:
    doorbell:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.3:554/h264Preview_01_main
      - ffmpeg:doorbell#audio=opus
    backyard:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_main
    # "#raw=-vf hwdownload,format=nv12" resolves issue where hevc would not transcode properly
    # by converting the GPU pixels to a format the CPU can read
      - ffmpeg:backyard#audio=opus#video=h264#hardware#raw=-vf hwdownload,format=nv12
    backzoom:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_02_main
      - ffmpeg:backzoom#video=h264#hardware#raw=-vf hwdownload,format=nv12
    front:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.4:554/h264Preview_01_main
      - ffmpeg:front#video=h264#hardware#raw=-vf hwdownload,format=nv12    
    # garage:
    # - rtsp://jpfeifer14:wtdmhcbE13@192.168.5.4/live
  webrtc:
    candidates:
      - 192.168.0.11:8555
      - stun:8555

birdseye:
  enabled: true
  restream: true
  mode: continuous


version: 0.14
```

### Relevant Frigate log output

```shell
2024-11-27 22:53:38.234171575  [INFO] Preparing Frigate...
2024-11-27 22:53:38.240774665  [INFO] Starting Frigate...
2024-11-27 22:53:38.986306104  [2024-11-27 22:53:38] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-11-27 22:53:38.986309733  [2024-11-27 22:53:38] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-11-27 22:53:39.005341640  [2024-11-27 22:53:39] frigate.util.config            INFO    : frigate config does not need migration...
2024-11-27 22:53:41.411288885  [2024-11-27 22:53:41] peewee_migrate.logs            INFO    : Starting migrations
2024-11-27 22:53:41.411605409  [2024-11-27 22:53:41] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-11-27 22:53:41.677421279  [2024-11-27 22:53:41] frigate.app                    INFO    : Recording process started: 409
2024-11-27 22:53:41.681576095  [2024-11-27 22:53:41] frigate.app                    INFO    : Recording process started: 418
2024-11-27 22:53:41.682789516  [2024-11-27 22:53:41] frigate.app                    INFO    : go2rtc process pid: 110
2024-11-27 22:53:41.700092310  [2024-11-27 22:53:41] detector.coral                 INFO    : Starting detection process: 438
2024-11-27 22:53:44.854761318  [2024-11-27 22:53:41] frigate.app                    INFO    : Output process started: 440
2024-11-27 22:53:44.854807782  [2024-11-27 22:53:41] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-11-27 22:53:44.858195676  [2024-11-27 22:53:44] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-11-27 22:53:44.858246328  [2024-11-27 22:53:41] frigate.app                    INFO    : Camera processor started for doorbell: 457
2024-11-27 22:53:44.858271576  [2024-11-27 22:53:41] frigate.app                    INFO    : Camera processor started for backyard: 461
2024-11-27 22:53:44.858290074  [2024-11-27 22:53:41] frigate.app                    INFO    : Camera processor started for backzoom: 464
2024-11-27 22:53:44.858301229  [2024-11-27 22:53:41] frigate.app                    INFO    : Camera processor started for front: 465
2024-11-27 22:53:44.858317028  [2024-11-27 22:53:41] frigate.app                    INFO    : Capture process started for doorbell: 473
2024-11-27 22:53:44.858441035  [2024-11-27 22:53:41] frigate.app                    INFO    : Capture process started for backyard: 476
2024-11-27 22:53:44.858477638  [2024-11-27 22:53:41] frigate.app                    INFO    : Capture process started for backzoom: 480
2024-11-27 22:53:44.858500212  [2024-11-27 22:53:41] frigate.app                    INFO    : Capture process started for front: 486
2024-11-27 23:02:25.895458179  [2024-11-27 23:02:25] frigate.comms.dispatcher       INFO    : Setting motion threshold for backyard: 30
2024-11-27 23:02:25.897431178  [2024-11-27 23:02:25] frigate.comms.dispatcher       INFO    : Setting motion contour area for backyard: 10
```

### Relevant go2rtc log output

```shell
2024-11-27 22:53:38.237252843  [INFO] Preparing new go2rtc config...
2024-11-27 22:53:38.420016769  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-11-27 22:53:38.451140808  [INFO] Starting go2rtc...
2024-11-27 22:53:38.527788776  22:53:38.527 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-27 22:53:38.527791856  22:53:38.527 INF config path=/dev/shm/go2rtc.yaml
2024-11-27 22:53:38.528087161  22:53:38.528 INF [api] listen addr=:1984
2024-11-27 22:53:38.528222474  22:53:38.528 INF [rtsp] listen addr=:8554
2024-11-27 22:53:38.528406851  22:53:38.528 INF [webrtc] listen addr=:8555
2024-11-27 22:53:48.234802810  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://admin:BW5ynKNVLDhQyS@192.168.5.4:554/h264Preview_01_main
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:BW5ynKNVLDhQyS@192.168.5.4:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000375, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"cameras":{"backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":8.1,"capture_pid":476,"detection_enabled":true,"detection_fps":0.4,"ffmpeg_pid":481,"pid":461,"process_fps":8.2,"skipped_fps":0.0},"backzoom":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":480,"detection_enabled":true,"detection_fps":2.4,"ffmpeg_pid":496,"pid":464,"process_fps":5.1,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":473,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":477,"pid":457,"process_fps":7.1,"skipped_fps":0.0},"front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.2,"capture_pid":486,"detection_enabled":true,"detection_fps":2.9,"ffmpeg_pid":508,"pid":465,"process_fps":7.2,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"100":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"101":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"102":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"5.1","cpu_average":"5","mem":"0.3"},"120":{"cmdline":"python3 -u -m frigate","cpu":"1.2","cpu_average":"2","mem":"2.7"},"123":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"139":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"170":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"171":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"172":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"173":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"17684":{"cmdline":"sh","cpu":"0.0","cpu_average":"0","mem":"0.0"},"183":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"21031":{"cmdline":"sh","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23868":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23949":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"308":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"36":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"37":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"38":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"39":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"391":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.7"},"40":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"409":{"cmdline":"frigate.recording_manager","cpu":"1.3","cpu_average":"0","mem":"1.1"},"41":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"418":{"cmdline":"frigate.review_segment_manager","cpu":"0.3","cpu_average":"0","mem":"0.9"},"42":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"43":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"437":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"438":{"cmdline":"frigate.detector.coral","cpu":"2.6","cpu_average":"3","mem":"1.0"},"44":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"440":{"cmdline":"frigate.output       ","cpu":"3.2","cpu_average":"3","mem":"1.0"},"45":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"457":{"cmdline":"frigate.process:doorbell","cpu":"0.7","cpu_average":"0","mem":"1.0"},"46":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"461":{"cmdline":"frigate.process:backyard","cpu":"1.0","cpu_average":"1","mem":"1.0"},"464":{"cmdline":"frigate.process:backzoom","cpu":"2.2","cpu_average":"2","mem":"1.2"},"465":{"cmdline":"frigate.process:front","cpu":"1.7","cpu_average":"1","mem":"1.0"},"473":{"cmdline":"frigate.capture:doorbell","cpu":"0.4","cpu_average":"0","mem":"0.9"},"476":{"cmdline":"frigate.capture:backyard","cpu":"0.5","cpu_average":"0","mem":"0.9"},"477":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.5.3:554/h264Preview_01_sub -r 7 -vf fps=7,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.9"},"480":{"cmdline":"frigate.capture:backzoom","cpu":"1.3","cpu_average":"1","mem":"0.9"},"481":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.5.2:554/h264Preview_01_sub -r 8 -vf fps=8,scale_cuda=w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.9"},"486":{"cmdline":"frigate.capture:front","cpu":"0.3","cpu_average":"0","mem":"0.9"},"496":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://0.0.0.0:8554/backzoom -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backzoom@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.5","cpu_average":"2","mem":"1.1"},"502":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://0.0.0.0:8554/doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.2"},"508":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.5.4:554/h264Preview_01_sub -r 7 -vf fps=7,scale_cuda=w=360:h=640:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.7","cpu_average":"0","mem":"0.9"},"510":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://0.0.0.0:8554/backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.2"},"519":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://0.0.0.0:8554/front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.2"},"536":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"541":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"546":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"551":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 360x640 -i pipe: -threads 1 -f mpegts -s 405x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"556":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"1.4","cpu_average":"1","mem":"0.2"},"57":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"58":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"4.5","mem":"11.9"}},"detection_fps":5.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":25.43,"pid":438}},"gpu_usages":{"NVIDIA GeForce GTX 1660 SUPER":{"dec":"2.0%","enc":"0.0%","gpu":"1.0%","mem":"14.19%"}},"processes":{"go2rtc":{"pid":110},"logger":{"pid":391},"recording":{"pid":409},"review_segment":{"pid":418}},"service":{"last_updated":1732770848,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":247.2,"mount_type":"tmpfs","total":256.0,"used":8.8},"/media/frigate/clips":{"free":2380952.4,"mount_type":"fuse.shfs","total":3815447.8,"used":1428200.2},"/media/frigate/recordings":{"free":2380952.4,"mount_type":"fuse.shfs","total":3815447.8,"used":1428200.2},"/tmp/cache":{"free":932.5,"mount_type":"tmpfs","total":953.7,"used":21.2}},"temperatures":{},"uptime":1227,"version":"0.14.1-f4f3cfa"}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Unraid Community App
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

REolink E1, Doorbell, TrackMix

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-11-27 231542](https://github.com/user-attachments/assets/9911635e-edbd-41a2-b7f3-48a01a490530)
![Screenshot 2024-11-27 231603](https://github.com/user-attachments/assets/c55db135-dda2-4f05-870c-be28b6d1b933)
![Screenshot 2024-11-27 231615](https://github.com/user-attachments/assets/80e3f65c-02c6-4628-b4bb-555ac47aadcd)
