### DISCUSSION TITLE
[Detector Support]: ONNX YOLO-NAS Model Loading Error with TensorRT Provider in Frigate 0.15 Beta 2

### DISCUSSION THREAD

**Discussion by olegchumakov** [blakeblackshear/frigate#15238] [Detector Support]
### Describe the problem you are having

I'm experiencing an error while trying to run YOLO-NAS ONNX model with TensorRT in Frigate NVR. The system is unable to load the TensorRT provider library due to a missing dependency. And it doesn't detect anything in video, only audio.
```error
2024-11-28 15:21:38.611061867 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory
```

Everything works ok with standart tensorrt detector + yolov7.

### Version

0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  home:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/Streaming/Channels/101
          roles:
            - audio
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
    onvif:
      host: <ip>
      port: <port>
      user: <user>
      password: <password>
      ignore_time_mismatch: true

  roof:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/2/h264minor
          roles:
            - detect
            - record
    onvif:
      host: <ip>
      port: <port>
      user: <user>
      password: <password>
      ignore_time_mismatch: true

  domofon:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record

    objects:
      mask: 0.323,0.755,0.34,0.76,0.342,0.806,0.39,0.793,0.399,0.882,0.338,0.882
  porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/live/sub
          roles:
            - detect
            - record

  south:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/live/sub
          roles:
            - detect
            - record

  north:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/live/sub
          roles:
            - detect
            - record

  lake:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<user:pass>@<ip>/live/sub
          roles:
            - detect
            - record


    objects:
      mask: 0.297,0,0.298,0.104,0.383,0.101,0.385,0
go2rtc:
  streams:
    home:
      - rtsp://<user:pass>@<ip>/Streaming/Channels/101

ffmpeg:
  hwaccel_args: -c:v h264_cuvid

detect:
  fps: 5
  enabled: true

detectors:
  onnx:
    type: onnx
    device: Tensorrt

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 0
    mode: motion
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: motion

objects:
  track:
    - person
    - car
    - dog
    - cat
    - speech

  filters:
    person:
      min_score: 0.8
    dog:
      min_score: 0.8
    car:
      min_score: 0.8
    cat:
      min_score: 0.8

review:
  alerts:
    labels:
      - car
      - person
      - dog
      - cat
      - speech


motion:
  enabled: true

ui:
  time_format: 24hour

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    environment:
      - FRIGATE_RTSP_PASSWORD="password"
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta2-tensorrt
    shm_size: "512mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: all # number of GPUs
              capabilities: [gpu]
    volumes:
      - \\wsl$$\Ubuntu\etc\localtime:/etc/localtime:ro
      - \\wsl$$\Ubuntu\home\user\frigate\config:/config
      - \\wsl$$\Ubuntu\home\user\frigate\clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
2024-11-28 15:21:38.608060156  [2024-11-28 15:21:38] detector.onnx                  INFO    : Starting detection process: 511
2024-11-28 15:21:38.609335601  [2024-11-28 15:21:38] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
2024-11-28 15:21:38.609923014  [2024-11-28 15:21:38] frigate.detectors.plugins.onnx INFO    : ONNX: loading /config/yolo_nas_s.onnx
2024-11-28 15:21:38.611208140  2024-11-28 15:21:38.611061867 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory
2024-11-28 15:21:39.139557766  [2024-11-28 15:21:39] frigate.detectors.plugins.onnx INFO    : ONNX: /config/yolo_nas_s.onnx loaded
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/232b3f48-63e6-417a-97b8-20b8163d84e3)
