### DISCUSSION TITLE
[Support]: deprecated pixel format used & Timestamps are unset in a packet for stream errors

### DISCUSSION THREAD

**Discussion by lee-costa** [blakeblackshear/frigate#15240] [General Support]
### Describe the problem you are having

Suddenly, after adjusting the time on my cameras (not sure if a coincidence), I started seeing this in the logs:

    frigate[1007]: 2024-11-28 08:01:58.602837698 [2024-11-28 08:01:58] ffmpeg.driveway_cam.detect ERROR : [swscaler @ 0x55ec8fa31a40] [swscaler @ 0x55ec8f99bfc0] deprecated pixel format used, make sure you did set range correctly

and 

    Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly

All my three cameras are showing the same thing even though nothing has changed on my configuration. I simply disabled DST on all cameras and restarted Frigate.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 132.0.2

### Frigate config file

```yaml
#########################################################
## Global
#########################################################

mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db


go2rtc:
  streams:
    driveway_cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
    backyard_cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0
    living_room_cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.16:554/cam/realmonitor?channel=1&subtype=0

live:
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 2160
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5

##########################################################
## Driveway
##########################################################

cameras:
  driveway_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: true

    zones:
      street:
        coordinates: 0.627,0.675,0.943,0.835,0.958,0.712,0.711,0.6
        objects:
          - person
          - dog
          - cat
          - car
          - bicycle
        inertia: 3
        loitering_time: 0
      driveway:
        coordinates: 
          0.596,0.708,0.444,0.633,0.134,0.717,0.131,0.767,0.004,0.807,0.002,0.895,0,1,0.325,0.997,0.996,0.999,1,0.875,0.623,0.681
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - person
        inertia: 3

    objects:
      track:
        - person
        - dog
        - car
        - cat
        - bicycle
      filters:
        person:
          min_area: 8000
          max_area: 100000
        dog:
          max_area: 12000
        car:
          max_area: 200000
        cat: {}
        bicycle: {}
      mask: 
        0.128,0.706,0.113,0.744,0.005,0.781,0.001,0.001,0.998,0.001,0.998,0.429,1,0.721,0.709,0.588,0.643,0.652,0.593,0.699,0.435,0.622
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 
        0.128,0.706,0.113,0.744,0.005,0.781,0.001,0.001,0.998,0.001,0.998,0.429,1,0.721,0.709,0.588,0.643,0.652,0.593,0.699,0.435,0.622

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 15
          mode: motion

    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - driveway
        - street
      retain:
        default: 7

    review:
      alerts:
        labels: []
      detections:
        labels:
          - car
          - person
          - dog
          - cat
          - bicycle
        required_zones:
          - driveway
          - street

##########################################################
## Backyard
##########################################################

  backyard_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

# Detect
    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: true

    motion:
      threshold: 30
      mask:
        - 0.814,0.274,0.846,0.195,1,0.236,1,0,0,0,0.011,0.494,0.597,0.303
        - 0.992,0.598,0.885,0.524,0.84,0.707,0.945,0.808
    objects:
      track:
        - person
        - dog
        # - bird
      filters:
        dog:
          mask:
            - 1562,296,1624,211,1920,255,1920,0,0,0,21,534,1146,327
        person:
          mask:
            - 1562,296,1624,211,1920,255,1920,0,0,0,21,534,1146,327
        # bird: {}
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 15
          mode: motion

    snapshots:
      enabled: true
      bounding_box: true
      required_zones: []
      retain:
        default: 7

    review:
      alerts:
        labels: []

      detections:
        labels: []

##########################################################
## Living Room
##########################################################

  living_room_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    motion:
      mask:
        - 0.832,0.332,0.86,0.654,0.605,0.658,0.602,0.642,0.597,0.388
        - 0.97,0,0.747,0,0.75,0.092,0.969,0.097
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 0.823,0.343,0.841,0.636,0.61,0.653,0.606,0.397
            - 0.97,0,0.747,0,0.75,0.092,0.969,0.097
    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: true

    record:
      enabled: true
      retain:
        days: 7
        # mode: active_objects
        mode: motion
      events:
        retain:
          default: 7
          # mode: active_objects
          mode: motion

    snapshots:
      enabled: true
      bounding_box: true
      required_zones: []
      retain:
        default: 7

version: 0.14
```

### Relevant Frigate log output

```shell
frigate[1007]: 2024-11-28 08:07:15.572472115 [2024-11-28 08:07:15] ffmpeg.driveway_cam.detect ERROR : [segment @ 0x55a587566880] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly

frigate[1007]: 2024-11-28 08:07:15.572478274 [2024-11-28 08:07:15] ffmpeg.driveway_cam.detect ERROR : [swscaler @ 0x55a58783d4c0] [swscaler @ 0x55a5877a6d40] deprecated pixel format used, make sure you did set range correctly
```

### Relevant go2rtc log output

```shell
2024-11-27 18:06:51.202357580  [INFO] Preparing new go2rtc config...
2024-11-27 18:06:51.703223647  [INFO] Starting go2rtc...
2024-11-27 18:06:51.836792469  18:06:51.836 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-11-27 18:06:51.836810404  18:06:51.836 INF config path=/dev/shm/go2rtc.yaml
2024-11-27 18:06:51.837455633  18:06:51.837 INF [rtsp] listen addr=:8554
2024-11-27 18:06:51.837459340  18:06:51.837 INF [api] listen addr=:1984
2024-11-27 18:06:51.837463263  18:06:51.837 INF [webrtc] listen addr=:8555/tcp
2024-11-27 18:07:01.199406451  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1g" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/REDACTED/docker-compose/frigate/config/frigate.yml:/config/config.yml
#      - /home/REDACTED//docker-compose/frigate/config:/config
      - /home/REDACTED/docker-compose/frigate/frigate_db:/db
      - /mnt/freenas/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feed
    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      FRIGATE_RTSP_USER: "ha"
      PLUS_API_KEY: "REDACTED"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.139.24:8514"
#        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        tag: "{{.Name}}"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

IP8M-2496EW-AI-V3

### Screenshots of the Frigate UI's System metrics pages

<img width="1726" alt="Screenshot 2024-11-28 at 9 10 51 AM" src="https://github.com/user-attachments/assets/32f16778-7c29-45f4-b75c-ca2113665449">
