### DISCUSSION TITLE
[Support]: Frigate keep freezing host

### DISCUSSION THREAD

**Discussion by ouafnico** [blakeblackshear/frigate#15242] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Since some weeks, Frigate is killing the host every 1-2 days.

I'm using frigate v0.14, on docker, on LXC with Proxmox.
The host is dying very fast without any notice, no logs, no different load, nothing curious.

I've found similar closed bugs, but can't find a solution.

I've tried :

- use another host (got 3x dell 3050 with i5-6500T) : same problem
- use another kernel : i've tried 6.1, 6.2, 6.5, 6.11 pve kernels : same problem
- try different `hwaccel_args` :
  preset-intel-qsv-h264 : same
  preset-vaapi : same
  without : actually testing
- test other frigate versions : 0.14, and 0.15 beta : same (didn't want to rollback on v0.13)
- increase shm : actually 1Gb, but frigate shows less 20Mo used

If someone have any idea...

### Steps to reproduce

1. Use frigate last version on docker, on LXC/Proxmox
2. Wait a day

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: hidden
  user: hidden
  password: hidden
  topic_prefix: frigate
  client_id: frigate

go2rtc:
  streams:
    externe:
      - rtsp://hidden@hidden:8888/unicast
    annke-cam-1-main:
      - rtsp://hidden@hidden:554/H264/ch1/main/av_stream
    annke-cam-1-sub:
      - rtsp://hidden@hidden:554/H264/ch1/sub/av_stream
    annke-cam-2-main:
      - rtsp://hidden@hidden:554/H264/ch1/main/av_stream
    annke-cam-2-sub:
      - rtsp://hidden@hidden:554/H264/ch1/sub/av_stream
cameras:
  externe:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/externe
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1600
      height: 1200
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - zone_0
    zones:
      zone_0:
        coordinates: 1600,1200,1600,534,1073,525,484,512,303,689,0,881,0,1200
    motion:
      mask:
        - 0,0,0,675,0,922,317,522,1600,520,1600,0
    review:
      alerts:
        required_zones:
          - zone_0
  annke-cam-1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/annke-cam-1-sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/annke-cam-1-main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: annke-cam-1-main
    motion: {}
  annke-cam-2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/annke-cam-2-sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/annke-cam-2-main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: annke-cam-2-main
    motion:
      mask: 
        0.622,0.657,0.637,0.545,0.664,0.495,0.677,0.464,0.681,0.385,0.692,0.352,0.695,0.244,0.69,0.144,0.708,0.034,0.721,0.004,0.923,0,0.948,0.085,0.945,0.171,0.916,0.314,0.897,0.37,0.857,0.412,0.817,0.491,0.808,0.582,0.811,0.634,0.789,0.741,0.75,0.817,0.697,0.8,0.661,0.763,0.619,0.707
#ffmpeg:
  #hwaccel_args: preset-intel-qsv-h264
  #hwaccel_args: preset-vaapi

birdseye:
  enabled: true
  width: 1600
  height: 1200
  quality: 8
  restream: true
  mode: continuous

detect:
  enabled: true
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      default: 3000
      objects:
        car: 10000

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 0
    #mode: all
    mode: active_objects
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  retain:
    default: 7

live:
  height: 1200
  quality: 8

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

logger:
  default: critical

telemetry:
  network_interfaces:
    - eno1
  stats:
    amd_gpu_stats: false
    intel_gpu_stats: true

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb"
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/:/config/
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - LIBVA_DRIVER_NAME=i965
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

raspberry/annke

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b54d7e72-7ee1-4f7a-b8e8-51ea2367c9c8)
