### DISCUSSION TITLE
[Support]: MQTT /review Topic Showing Detections as Alerts

### DISCUSSION THREAD

**Discussion by PablaV** [blakeblackshear/frigate#15245] [General Support]
### Describe the problem you are having

Not sure if this is a bug or not but I have a few sensors created to show when a object is detected as an alert (see below for sensor code). I have an example of an MQTT message below where a person entered the driveway zone and was correctly identified as an alert but in the background a vehicle was detected as a detection. The vehicle was correctly identified in the UI as a detection and the person as an alert. However, the MQTT message shows them both as a severity: alert.. this ends up tripping my car sensor to go true when there is not a car detected in my driveway zone. 

I would expect 2 separate messages to be sent when this occurs, one with severity: alert for the person and another severity: detection for the vehicle. Or maybe I need to tweak my sensor a bit. 

I understand that I *could* use the /events stream for my sensor, but I want to 1:1 match my notifications (which use the mqtt sensor) to every alert that would show up in the UI. 

![image](https://github.com/user-attachments/assets/94cdeb17-6ea9-4452-a90e-9b74efac001f)
Vehicle detected on the road outside driveway zone - detection 

![image](https://github.com/user-attachments/assets/2eda028a-ee35-4901-bf8e-8620f45ffb54)
Person detected in the driveway - alert

MQTT Message:
```
{
    "type": "update",
    "before": {
        "id": "1732824558.096492-aj3xqr",
        "camera": "front_doorbell",
        "start_time": 1732824558.096492,
        "end_time": null,
        "severity": "alert",
        "thumb_path": "/media/frigate/clips/review/thumb-front_doorbell-1732824558.096492-aj3xqr.webp",
        "data": {
            "detections": [
                "1732824582.81398-kx5432",
                "1732824557.026012-z7gal2",
                "1732824577.499162-30ybag"
            ],
            "objects": [
                "person"
            ],
            "sub_labels": [],
            "zones": [
                "driveway"
            ],
            "audio": []
        }
    },
    "after": {
        "id": "1732824558.096492-aj3xqr",
        "camera": "front_doorbell",
        "start_time": 1732824558.096492,
        "end_time": null,
        "severity": "alert",
        "thumb_path": "/media/frigate/clips/review/thumb-front_doorbell-1732824558.096492-aj3xqr.webp",
        "data": {
            "detections": [
                "1732824582.81398-kx5432",
                "1732824557.026012-z7gal2",
                "1732824577.499162-30ybag",
                "1732824588.867896-4ftre8"
            ],
            "objects": [
                "car",
                "person"
            ],
            "sub_labels": [],
            "zones": [
                "driveway"
            ],
            "audio": []
        }
    }
}
```

Sensor for object detection (same code for person): 
```
- name: "Front Doorbell Vehicle Mqtt"
  icon: mdi:car
  state_topic: "frigate/reviews"
  value_template: >-
    {% if ('car' in value_json.after.data.objects and value_json.after.data.zones[0] == 'driveway' and value_json.type != 'end' and value_json.after.severity == 'alert') %}
      true
    {% elif ('car' in value_json.after.data.objects and value_json.type == 'end' and value_json.after.severity == 'alert') %}
      false
    {% else %}
      false
    {% endif %}    
```

### Version

0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  host: 192.168.8.85
  port: 1883
  user: Arman
  password: xxxx
cameras:
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 2560
      height: 1920
      annotation_offset: 1
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
      filters:
        car:
          min_area: 7500
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
        package:
          min_score: 0.85
          mask: 0.004,0.006,0,0.754,0.22,0.871,0.624,0.768,0.837,0.704,1,0.567,0.999,0.006
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 10
        post_capture: 30
      detections:
        retain:
          days: 3
    motion:
      mask:
        - 1,0,1,0.037,0.654,0.035,0.655,0
        - 0.164,0.256,0.216,0.386,0.216,0.461,0.688,0.494,0.678,0.409,0.767,0.227,0.876,0.177,0.818,0.073,0.576,0.123,0.228,0.134
      threshold: 30
      contour_area: 20
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 
          0.176,0.33,0.172,0.566,0.287,0.549,0.494,0.549,0.589,0.579,0.717,0.578,0.719,0.348,0.928,0.252,0.999,0.216,1,1,0,1,0.002,0.208
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones:
          - driveway
        labels:
          - person
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package
      detections: {}
    mqtt:
      quality: 100
      required_zones:
        - driveway
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
      mask: 0,0.282,0.042,0.321,0.305,0.213,0.293,0.003,0,0
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  front_east:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_east?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_east_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
      mask: 0.632,0.119,0.998,0.138,1,0,0.635,0.003
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  front_entrance_east:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_entrance_east?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_entrance_east_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
          mask:
            - 0.568,0,0.633,0.041,1,0.206,1,0
            - 0.232,0.227,0,0.426,0,0.001,0.23,0.001
            - 0.538,0.894,0.543,0.997,0.997,0.994,0.995,0.894
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
      mask:
        - 0.568,0,0.633,0.041,1,0.206,1,0
        - 0.232,0.227,0,0.426,0,0.001,0.23,0.001
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.009,0.013,0.008,0.073,0.308,0.073,0.307,0.013
      threshold: 30
      contour_area: 100
      improve_contrast: true
  front_entrance_west:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_entrance_west?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_entrance_west_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
      mask:
        - 0,0.29,0,0,0.475,0.001
        - 0.779,0,1,0.134,0.997,0.004
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  east_side_house:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/east_side_house?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/east_side_house_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  west_side_back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/west_side_back?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/west_side_back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.681,0.914,0.684,0.962,0.981,0.965,0.979,0.913
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
      threshold: 30
      contour_area: 30
      improve_contrast: true
  back_landing:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_landing?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_landing_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  bar_landing:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bar_landing?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bar_landing_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  deck_stairs:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_stairs?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_stairs_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922
  deck_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_door?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_door_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        car:
          min_score: 0.85
        person:
          min_score: 0.85
        cat:
          min_score: 0.85
        dog:
          min_score: 0.85
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 3
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - car
      detections: {}
    motion:
      mask: 0.68,0.919,0.683,0.967,0.98,0.97,0.979,0.922


go2rtc:
  streams:
    front_doorbell:
      - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus#async
      - rtsp://xxxx:xxxx@192.168.8.186:554/h264Preview_01_sub
    front_doorbell_sub:
      - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx
    front_door: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
    front_door_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=1&subtype=1
    front_east: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=2&subtype=0
    front_east_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=2&subtype=1
    front_entrance_east: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=5&subtype=0
    front_entrance_east_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=5&subtype=1
    front_entrance_west: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=6&subtype=0
    front_entrance_west_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=6&subtype=1
    west_side_back: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=12&subtype=0
    west_side_back_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=12&subtype=1
    east_side_house: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=8&subtype=0
    east_side_house_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=8&subtype=1
    back_garden: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=3&subtype=0
    back_garden_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=3&subtype=1
    backyard: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=7&subtype=0
    backyard_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=7&subtype=1
    back_landing: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=4&subtype=0
    back_landing_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=4&subtype=1
    bar_landing: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=10&subtype=0
    bar_landing_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=10&subtype=1
    deck_stairs: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=9&subtype=0
    deck_stairs_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=9&subtype=1
    deck_door: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=11&subtype=0
    deck_door_sub: rtsp://xxxx:xxxx@192.168.8.20:554/cam/realmonitor?channel=11&subtype=1

  webrtc:
    candidates:
      - 192.168.8.85:8555
      - stun:8555
snapshots:
  enabled: true
  # required_zones:
  #   - driveway
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: true
  height: 270
  quality: 100

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac #this allows audio in recordings 
  hwaccel_args: preset-vaapi

model:
  path: plus://xxxx
timestamp_style:
  position: bl
  format: '%-I:%M:%S %p %Y-%m-%d'
  color:
    red: 0
    green: 0
    blue: 0

semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: True
  provider: gemini
  api_key: xxxxx
  model: gemini-1.5-flash

birdseye:
  enabled: true
  mode: objects
  width: 1920
  height: 1080
  restream: true


version: 0.15-0
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

n/a
