### DISCUSSION TITLE
MJPEG stream, most recent frame, detection and recording stop working

### DISCUSSION THREAD

**Discussion by bikemike** [blakeblackshear/frigate#15244] [Ask A Question]
I'd like some help figuring out why frigate stops processing a camera stream.  (System 0.15.0-33825f6)

After some time I get a "No frames have been received, check error logs" for the camera thumbnail on the main page. If I click that image, the camera stream is fine. In the history view, there are no recordings, and no events. I can scroll back the timeline to the when it happens and see that the video corrupt for some frames.

The birdseye view is also stuck on a corrupt frame.

The mjpeg stream (api) shows the same last corrupt image as the birdseye view. The latest image(api) shows "No frames have been received, check the error logs".

Restarting frigate corrects the issue but I'd prefer if I could solve this without resorting to such drastic measures.

This is the camera config:

```
  coopcam:
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/coopcam_low # detect low res
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/coopcam_high # restream from go2rtc, record high res stream
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: coopcam_low
    detect:
      width: 640
      height: 360
    objects:
      track:
        - bird

go2rtc:
  streams:
    coopcam_low:
      - exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -rtsp_flags prefer_tcp -i rtsp://192.168.31.212:8554/video4_unicast -map 0:0 -map 0:1 -c:v copy -c:a:0 aac -ar:0 44100 -c:a:1 libopus -rtsp_transport tcp -f rtsp {{output}}
    coopcam_high:
      - exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -rtsp_flags prefer_tcp -i rtsp://192.168.31.212:8554/video3_unicast -map 0:0 -map 0:1 -c:v copy -c:a:0 aac -ar:0 44100 -c:a:1 libopus -rtsp_transport tcp -f rtsp {{output}}   
```
