### DISCUSSION TITLE
cannot play recording video on Frigate

### DISCUSSION THREAD

**Discussion by thematrixdev** [blakeblackshear/frigate#15250] [Ask A Question]
I have Go2RTC installed on "office-desk", reading USB camera and 3.5mm jack microphone.

Frigate at home reads Go2RTC at office via Tailscale IP.

On Frigate UI, live streaming could be played smoothly.
The recorded video in review section cannot be played.
It just shows a loading circle.

The recorded videos are find on server, and could be played normally.
![image](https://github.com/user-attachments/assets/7d11abf8-d903-42dc-90f2-ed1e06d6da1d)
![image](https://github.com/user-attachments/assets/31116519-9d06-4d04-a602-8ae9884a9907)

I don't see any particular error on Chrome networking or console:

![image](https://github.com/user-attachments/assets/51b9f98c-84d9-4b6c-8b18-e611b7d0aef0)

FFPlay:

```
$ ffplay rtsp://100.100.50.10:8554/office-desk
ffplay version 7.0.2-3ubuntu1 Copyright (c) 2003-2024 the FFmpeg developers
  built with gcc 14 (Ubuntu 14.2.0-2ubuntu1)
  configuration: --prefix=/usr --extra-version=3ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-libmfx --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[rtsp @ 0x7bc7b8000c80] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://100.100.50.10:8554/office-desk':
  Metadata:
    title           : go2rtc/1.9.6
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 44100 Hz, mono, fltp
  Stream #0:1: Video: hevc (Main), yuv420p(tv, bt470bg/unknown/unknown), 1920x1080, 30 fps, 30 tbr, 90k tbn
```

`docker-compose.yaml` on `office-desk`:

```
services:
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc
    volumes:
      - type: bind
        source: /dev/video0
        target: /dev/video0
      - type: bind
        source: /dev/dri/renderD128
        target: /dev/dri/renderD128
      - type: bind
        source: /dev/snd
        target: /dev/snd
      - type: bind
        source: ./config
        target: /config
    ports:
      - "1984:1984/tcp"
      - "8554:8554/tcp"
      - "8555:8555"
    privileged: true
    restart: unless-stopped
```

`go2rtc.yaml` on `office-desk`:

```
streams:
  office-desk:
    - ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080#video=h265#hardware
    - exec:ffmpeg -f alsa -ac 1 -i hw:0,0 -c:a aac -ar:a 44100 -ac:a 1 -af "afftdn=nf=-20" -rtsp_transport tcp -b:a 128k -listen 1 -reconnect 1 -f rtsp {output}
```

On Frigate at home:

```
...

cameras:
  office-desk:
    ffmpeg:
      inputs:
        - path: rtsp://100.100.50.10:8554/office-desk
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    record:
      enabled: true
    snapshots:
      enabled: true

...
```

Go2RTC UI on `office-desk`
![image](https://github.com/user-attachments/assets/e7d0a433-aeba-4cb3-93d8-4caa27b4e8c2)

The video by hardware accelerated H264 looks very broken so I want to keep H265.
And tried switching to H264 the recorded video (afterwards) does not play neither.
