### DISCUSSION TITLE
[Bug]: when clicking on live view: TypeError: can't access property "toUpperCase", g[0] is undefined

### DISCUSSION THREAD

**Discussion by Niedzwiedzw** [blakeblackshear/frigate#15253] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

when clicking on live view: TypeError: can't access property "toUpperCase", g[0] is undefined

### Steps to reproduce

1.
2.
3.
...

### Version

System 0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Firefox Nightly 133.0a1 (2024-11-27) (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    furtka__high_res:
      - rtsp://admin:password@192.168.1.29:554/cam/realmonitor?channel=1&subtype=0
    furtka__low_res:
      - rtsp://admin:password@192.168.1.29:554/cam/realmonitor?channel=1&subtype=1

cameras:
  furtka__high_res: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/furtka__high_res # <----- Add stream you want to record from
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/furtka__low_res # <----- Add stream you want to record from
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: furtka__high_res
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    record: # <----- Enable recording
      enabled: true
      retain:
          # Optional: Number of days to retain recordings regardless of events (default: shown below)
          # NOTE: This should be set to 0 and retention should be defined in events section below
          #       if you only want to retain recordings of events.
        days: 7
          # Optional: Mode for retention. Available options are: all, motion, and active_objects
          #   all - save all recording segments regardless of activity
          #   motion - save all recordings segments with any detected motion
          #   active_objects - save all recording segments with active/moving objects
          # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
    zones:
      podwórki:
        coordinates: 0,0.274,1,0.33,1,1,0.051,1
        loitering_time: 0
      droga:
        coordinates: 0,0.054,1,0.094,0.996,0.321,0,0.263
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones:
          - podwórki
          - droga
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
      # - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "192.168.1.3:5000:5000" # Internal unauthenticated access. Expose carefully.
      - "192.168.1.3:8971:8971"
      - "192.168.1.3:8554:8554" # RTSP feeds
      - "192.168.1.3:8555:8555/tcp" # WebRTC over tcp
      - "192.168.1.3:8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
TypeError: can't access property "toUpperCase", g[0] is undefined
```

### Relevant go2rtc log output

```shell
---
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

AMCREST IP5M

### Screenshots of the Frigate UI's System metrics pages

https://github.com/user-attachments/assets/8ab2363c-44e9-48b1-8048-38ed64d13fb6
