### DISCUSSION TITLE
[Camera Support]: Issues using 2-way audio with Reolink POE Doorbell

### DISCUSSION THREAD

**Discussion by NightTrain** [blakeblackshear/frigate#15267] [Camera Support] [answered]
### Describe the problem you are having

I've recently been attempting to leverage a new Reolink POE doorbell in HomeAssistant Via the Frigate Add-on. More specifically the 2-way audio feature. I've been able to successfully stream the current live view of the camera with audio, but have yet to get the 2-way audio working properly.

Notably when accessing via HTTPS (Which I believe is a WebRTC requirement) The microphone button does appear in Frigate, and my browser does turn on my microphone, but when I click it the stream hangs and I get a loading indicator like this:

![image](https://github.com/user-attachments/assets/d0feaf3d-0779-4199-b04a-7f5095b2b1cf)

This screen never changes unless I re-click the microphone button or refresh the page.

Even with DEBUG output turned on, there's very little I see in the frigate logs other than this line:

> 2024-11-30 04:33:38.195595805  127.0.0.1 - - [29/Nov/2024:23:33:38 -0500] "" 400 0 "-" "-" "-"

I've tried a number of configurations from this github, reddit, and elsewhere, but have yet to be able to get this working.

Current Camera Firmware: v3.0.0.4110_2410111120

I don't need to record, detect, or snapshot, I just need to be able to view the camera with audio and leverage the 2-way audio. Once this is working in the frigate add-on I do plan to add a lovelace card to a dashboard, but that's a separate task.

Any help is greatly appreciated!

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 132.0.2

### Frigate config file

```yaml
mqtt:
  host: <MQTT_HOST_IP>        # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <MQTT_USER> # YOUR MQTT USERNAME
  password: <MQTT_PASS>        # YOUT MQTT PASSWORD
  stats_interval: 60

go2rtc:
  streams:
    reolink:
      - ffmpeg:rtsp://<CAMERA_IP>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<CAMERA_USER>&<CAMERA_PASS>#video=copy#audio=copy#audio=opus
      - rtsp://<CAMERA_USER>:<CAMERA_PASS>@<CAMERA_IP>:554/h264Preview_01_sub

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"

##########################################################################

cameras:

  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video&audio

    detect:
      enabled: false
    record:
      enabled: false
    mqtt:
      enabled: false
    live:
      stream_name: reolink

logger:
  default: debug
version: 0.14
```

### Relevant Frigate log output

```shell
2024-11-30 04:33:38.195595805  127.0.0.1 - - [29/Nov/2024:23:33:38 -0500] "" 400 0 "-" "-" "-"
```

### Relevant go2rtc log output

```shell
11/29/2024, 11:26:37 PM	info	go2rtc version=1.9.2 platform=linux/amd64 revision=b2399f3
11/29/2024, 11:26:37 PM	info	config path=/dev/shm/go2rtc.yaml
11/29/2024, 11:26:37 PM	info	[api] listen addr=:1984
11/29/2024, 11:26:37 PM	info	[rtsp] listen addr=:8554
11/29/2024, 11:26:37 PM	info	[webrtc] listen addr=:8555/tcp
```

### FFprobe output from your camera

```shell
Not running a frigate container.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell POE X003YEKD9X

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/51a126a4-4e76-46ab-a7bd-fcdfe817cdbb)
