### DISCUSSION TITLE
Recommended changes to config file for new set-up

### DISCUSSION THREAD

**Discussion by raspman** [blakeblackshear/frigate#15262] [Config Support] [answered]
### Describe the problem you are having

I am slowly migrating from a Raspberry Pi4 running HA Supervised and the Frigate add-on to a Dell Optiplex 7070 i5-9500 with 8GB RAM, 1TB SSD, 6TB HDD and Proxmox running HAOS and Frigate LXC.

The below config file worked pretty well on the Raspberry Pi, but I realize some parts need to be changed now. If you could please give me some input on what lines to be updated, I'd appreciate it.

### Version

0.14.1-

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: XX
  password:  XX

record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    retain:
      default: 3

ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-http-reolink
detectors:
  cpu1:
    type: cpu

go2rtc:
# log:
#   exec: trace
  streams:
    garage:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus
    frontdoor:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus

cameras:
  garage:
    ffmpeg:
      inputs:
        # Record HD stream
        - path: 
            http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx
          roles:
            - record
        # Use low quality and low FPS stream for object detection
        - path: 
            http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xx&password=xx
          roles:
            - detect
    motion:
      mask:
        - 597,0,591,140,169,80,159,0
        - 0,25,213,26,213,0,0,0
    zones:
      garage_driveway:
        coordinates: 640,360,640,102,477,133,203,360
    objects:
      track:
        - person

  frontdoor:
    ffmpeg:
      inputs:
        # Record HD stream
        - path: 
            http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx
          roles:
            - record
        # Use low quality and low FPS stream for object detection
        - path: 
            http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xx&password=xx
          roles:
            - detect
    motion:
      mask:
        - 640,0,640,452,640,321,0,307,0,0

    objects:
      track:
        - person
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

HassOS

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
.
```

### Object Detector

OpenVino
