### DISCUSSION TITLE
[Bug]: 0.15.0 B2 - Still doesnt show all cameras

### DISCUSSION THREAD

**Discussion by vertex-github** [blakeblackshear/frigate#15266] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

0.15.0 B2 doesnt startup properly - logs seem ok, but UI does not show all cameras.  I get 1-2/12 cameras showing in the live view.  I can click on each camera and see the specific camera feed, but the main live view page doesnt show all cameras.  Dropped back to backup and 0.14.1 and everything comes up fine.  I checked status monitor - CPU was around 22%, with much lower % mem usage.  Nothing seemed out of the ordinary on the other stats.  TPU intefernce speed was around 8ms.

### Steps to reproduce

1. Changed docker image form 0.14.1 to 0.15.0-beta2
2.
3.
...

### Version

0.15.2-b2

### In which browser(s) are you experiencing the issue with?

Firefox (latest dev version) 134.0b2

### Frigate config file

```yaml
n/a
```

### docker-compose file or Docker CLI command

```yaml
frigate:
# NOTE: Frigate TPU requires OS Kernel module installation.  If /dev/apex_0 is missing then the module isnt installed or the TPU isnt passed-through
# New ffmpeg borks on hwaccel args when you dont have HW.  Older versions ignored the settings.
#    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1 - fail 20211111
#    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta2 - fail 20241129
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    container_name: frigate
    privileged: true
    restart: unless-stopped
    environment:
#      TZ: America/New_York
      FRIGATE_RTSP_PASSWORD: "XYZXYZXYZ"
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/frigate/config/:/config/
      - ./volumes/frigate/config/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./volumes/frigate/config/tls.conf:/usr/local/nginx/conf/tls.conf
      - ./volumes/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
```

### Relevant Frigate log output

```shell
no errors in logs
```

### Relevant go2rtc log output

```shell
no errors here
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Various - REolink. Amcrest, Axis

### Screenshots of the Frigate UI's System metrics pages

I didnt grab them - CPU was < 25% stable, memory was < 10%
