### DISCUSSION TITLE
[Config Support]: Detect parking car as long as it's parking

### DISCUSSION THREAD

**Discussion by cruunnerr** [blakeblackshear/frigate#15283] [Config Support] [answered]
### Describe the problem you are having

Hi together,

I have a parking lot directly at my side entrance and there is a power socket to load my car while it's parking there. 
I am using iobroker.frigate (like Home Assistant) to get messages from frigate over mqtt for using the informations to my smart home.

I want to be able to switch on the power socket if I am parking in my parking lot and disable the socket when I leave.
The detection of my car works and frigate sends a 1 (true) to iobroker when it detects the car.
BUT, after some seconds the state switches to 0 (false) although I am still parking. 

Is there a way, that the state only changes if there IS actually a change. Otherwise it's getting tricky. Because at the moment the scenario is like:

parking lot empty = state is 0 (false)
I am parking = state is 1 (true)
I get out of my car and leave = state is back to 0 although my car is still parking
I went to my car and drive away = state witches again shortly to 1 and back to 0.

I wish to turn on my power socket as long as my car is parking and turn the socket off only when I drive away.

Hope I described comprehensible. Many thanks for any idea.

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.10.10.20
  port: 1889
  stats_interval: 60

go2rtc:
  streams:
    Nebeneingang:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_UTC}@10.10.20.201/streaming/channels/101#video=copy#audio=copy#audio=aac#hardware
    

cameras:

  Nebeneingang: ###########################################################   NEW CAMERA   ###################################################################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Nebeneingang
          roles:
            - record
            - detect
        #- path: 
        #    rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD_UTC}@10.10.20.201/streaming/channels/102
        #  roles:
        #    - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      #width: 640
      #height: 480
      #fps: 5
    objects:
      track:
        - person
        - dog
        - umbrella
        - car
      filters:
        car:
          mask: 
            0.099,0.007,0.984,0.004,0.996,0.324,0.934,0.445,0.83,0.336,0.759,0.245,0.655,0.189,0.576,0.161,0.525,0.15,0.438,0.142,0.338,0.152,0.275,0.183,0.192,0.208,0.104,0.223
    zones:
      Buergersteig_gegenueber:
        coordinates: 
          0.1,0.06,0.288,0.035,0.368,0.035,0.549,0.033,0.666,0.056,0.792,0.086,0.906,0.124,0.976,0.15,0.968,0.185,0.959,0.191,0.817,0.141,0.723,0.124,0.615,0.097,0.497,0.091,0.385,0.095,0.264,0.107,0.144,0.128,0.101,0.134
        loitering_time: 1
      Strasse:
        coordinates: 
          0.101,0.137,0.185,0.12,0.325,0.102,0.447,0.09,0.555,0.093,0.696,0.11,0.802,0.134,0.906,0.164,0.964,0.187,0.963,0.233,0.859,0.216,0.769,0.2,0.674,0.196,0.58,0.188,0.44,0.191,0.331,0.198,0.218,0.216,0.105,0.227
        inertia: 3
        loitering_time: 0
      Buergersteig:
        coordinates: 
          0.104,0.231,0.339,0.198,0.598,0.187,0.775,0.192,0.957,0.225,0.949,0.274,0.87,0.272,0.756,0.273,0.574,0.277,0.438,0.285,0.254,0.313,0.11,0.341
        inertia: 3
        loitering_time: 1
      Nachbarn:
        coordinates: 
          0.882,0.526,0.904,0.44,0.928,0.373,0.946,0.303,0.948,0.273,0.786,0.277,0.537,0.284,0.754,0.517,0.856,0.595
        inertia: 3
        loitering_time: 0
      Seiteneingang:
        coordinates: 
          0.112,0.344,0.065,0.18,0.046,0.27,0.037,0.325,0,0.353,0.003,0.995,0.997,0.994,0.994,0.292,0.944,0.428,0.856,0.603,0.756,0.525,0.663,0.411,0.531,0.279,0.442,0.29,0.277,0.311
        inertia: 3
        loitering_time: 0
    motion:
      threshold: 35
      contour_area: 25
      improve_contrast: 'true'
      mask:
        - 0.001,0.313,0.027,0.312,0.135,0.995,0.004,0.999
        - 0.756,0.003,1,0,1,0.161,0.897,0.105,0.791,0.053
    review:
      alerts:
        required_zones:
          - Seiteneingang
          - Nachbarn
      detections: {}


record: ###########################################################   RECORDING SETTINGS   ###################################################################
  enabled: true
  expire_interval: 30
  sync_recordings: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 5
    post_capture: 10
    objects:
      - person


# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  cpu1:
    # Required: type of the detector
    # Frigate provided types include 'cpu', 'edgetpu', 'openvino' and 'tensorrt' (default: shown below)
    type: cpu

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  timestamp: true

version: 0.14
```

### Relevant Frigate log output

```shell
not relevant
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
not relevant
```

### Object Detector

CPU (no coral)
