### DISCUSSION TITLE
[Detector Support]: Tensorrt version won't start - stuck on starting go2rtc healthcheck service

### DISCUSSION THREAD

**Discussion by yangrusen** [blakeblackshear/frigate#15288] [Detector Support]
### Describe the problem you are having

I encountered a similar issue with https://github.com/blakeblackshear/frigate/issues/9619, where my Frigate installation is trying to access the internet to download TensorRT models, but my network restrictions prevent this. Since I am in China, Frigate container cannot access the necessary URLs.

Is there a way to download the TensorRT models separately and then upload them to the appropriate folder manually? Any guidance on how to do this would be greatly appreciated!

### Version

latest stable-tensorrt

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.2 #mqtt的ip
  port: 1883 #mqtt端口
  user: elvis #mqtt用户名,如果没有的话,可不写
  password: jlksp100 #mqtt密码,如果没有的话,可不写
  client_id: frigate #用于区分

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

objects:
  filters:
    person: #这里是设置需要检测的对象,官网有很多种类型,这里以检测人为准
      min_score: 0.7 #这是最小分值,当检测到的物体,超过70%的概率为人体,才确认是人体,这个参数根据自己环境的物体和光线自己调整

cameras:
  camera_1: # <--- this will be changed to your actual camera later
    enabled: true
    record:
      enabled: false #是否开启录制功能
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:jlksp100@192.168.2.80:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      stationary:
        interval: 50
        threshold: 50
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate2'
  --net='bridge'
  --pids-limit 2048
  --privileged=true
  -e TZ="Asia/Shanghai"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid"
  -e HOST_CONTAINERNAME="frigate2"
  -e 'NVIDIA_VISIBLE_DEVICES'='all'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '5000:5000/tcp'
  -v '/mnt/user/appdata/frigate2':'/config':'rw'
  -v '/mnt/user/appdata/frigate2/Media':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --runtime=nvidia
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped 'ghcr.nju.edu.cn/blakeblackshear/frigate:stable-tensorrt'
```

### Relevant Frigate log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: warning: unable to start service trt-model-prepare: command exited 4
Generating the following TRT Models: yolov7-320
Downloading yolo weights
2024-12-01 11:11:46.113449109  [INFO] Preparing new go2rtc config...
2024-12-01 11:11:47.229158848  [INFO] Starting go2rtc...
2024-12-01 11:11:47.327835284  11:11:47.327 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-12-01 11:11:47.327839481  11:11:47.327 INF config path=/dev/shm/go2rtc.yaml
2024-12-01 11:11:47.328331173  11:11:47.328 INF [api] listen addr=:1984
2024-12-01 11:11:47.328425433  11:11:47.328 INF [rtsp] listen addr=:8554
2024-12-01 11:11:47.328674906  11:11:47.328 INF [webrtc] listen addr=:8555/tcp
2024-12-01 11:11:55.930287914  [INFO] Starting go2rtc healthcheck service...
```

### Install method

Docker CLI

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

Can‘t see UI
