### DISCUSSION TITLE
[Support]: frigate.output pegging CPU cores at 100% - box is unresponsive - how to track down/diagnose?

### DISCUSSION THREAD

**Discussion by victorhooi** [blakeblackshear/frigate#15298] [General Support]
### Describe the problem you are having

I have a ARM64 host (256 cores), with a Coral USB TPU, running Frigate in a container.

I recently updated to the latest dev release, and also enable the new Semantic Search feature (not sure if this caused the issue or not)

At first, it all seemed to be working fine. However, the following day, I noticed that the machine running Frigate was very unresponsive:
* The Frigate web UI wasn't accessible via the browser.
* SSH-ing into the server itself took a *long* time - e.g. ~ 10 minutes to get to the password prompt, then maybe another 10 minutes after entering in the password to get to a prompt.
* top does show a few `frigate.output` processes that are pegging their respective cores at 100%.
![CleanShot 2024-12-02 at 09 47 19@2x](https://github.com/user-attachments/assets/0c11b850-a1cf-4488-9087-1439dd561634)
* Trying to stop the Frigate container just seems to spin indefinitely:
```
victorhooi@ampere-01 ~/frigate-docker> docker compose stop
WARN[0000] /home/victorhooi/frigate-docker/compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Stopping 0/1
 ⠴ Container frigate  Stopping                                                                                                                                                                                                           3153.6s
```
(About 52 minutes so far)
* Even trying to get docker logs from the container seems to hang indefinitely as well.

I'm assuming the box being unresponsive is related to the high CPU usage - would that be a reasonable hypothesis?

Does anybody know what exactly is `frigate.output`, or what it's responsible for? Is there an easy way to track down what specifically is causing the high CPU consumption? (I can try disabling the Semantic Search feature if that's the issue - but the reindexing only took around 70 seconds, so it didn't seem overly taxing on the box before, at least).

I haven't rebooted the box yet - but it seems I might have to, if I want to get logs - but is there any other diagnostic information I should collect first?

### Version

ee816b2-standard-arm64

### What browser(s) are you using?

_No response_

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect

  bedroom:
    enabled: true
    ffmpeg:
      inputs:
        - path:
            rtsp://root:FOOBAR@10.5.1.190:554/axis-media/media.amp?streamprofile=hdwitnessSecondary
          roles:
            - detect
        - path:
            rtsp://root:FOOBAR@10.5.1.190:554/axis-media/media.amp?streamprofile=hdwitnessPrimary
          roles:
            - record
    # detect:
    #   width: 640 # <- optional, by default Frigate tries to automatically detect resolution
    #   height: 360 # <- optional, by default Frigate tries to automatically detect resolution

    zones: {}
    review: {}

  kids_bedroom:
    enabled: true
    ffmpeg:
      inputs:
        - path:
            rtsp://root:FOOBAR@10.5.1.193:554/axis-media/media.amp?streamprofile=hdwitnessSecondary
          roles:
            - detect
        - path:
            rtsp://root:FOOBAR@10.5.1.193:554/axis-media/media.amp?streamprofile=hdwitnessPrimary
          roles:
            - record
    # detect:
    #   width: 640 # <- optional, by default Frigate tries to automatically detect resolution
    #   height: 360 # <- optional, by default Frigate tries to automatically detect resolution

    zones: {}
    review: {}

  living_room:
    enabled: true
    ffmpeg:
      inputs:
        - path:
            rtsp://root:FOOBAR@10.5.1.199:554/axis-media/media.amp?streamprofile=hdwitnessSecondary
          roles:
            - detect
        - path:
            rtsp://root:FOOBAR@10.5.1.199:554/axis-media/media.amp?streamprofile=hdwitnessPrimary
          roles:
            - record
    # detect:
    #   width: 640 # <- optional, by default Frigate tries to automatically detect resolution
    #   height: 360 # <- optional, by default Frigate tries to automatically detect resolution

    zones: {}
    review: {}

  stairway:
    enabled: true
    ffmpeg:
      inputs:
        - path:
            rtsp://root:FOOBAR@10.5.1.157:554/axis-media/media.amp?streamprofile=hdwitnessSecondary
          roles:
            - detect
        - path:
            rtsp://root:FOOBAR@10.5.1.157:554/axis-media/media.amp?streamprofile=hdwitnessPrimary
          roles:
            - record
    # detect:
    #   width: 640 # <- optional, by default Frigate tries to automatically detect resolution
    #   height: 360 # <- optional, by default Frigate tries to automatically detect resolution

    zones: {}
    review: {}

version: 0.15-0

model:
  #path: plus://d31dec2d1734b0f0dfdd21f67599e721
  path: plus://7ec1cf3edb785d6d442aa030c6a10af5

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
  track:
    - person
    - car
    - dog
    - cat
    - face
    - package
    - umbrella
    - waste_bin

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  retain:
    default: 30

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```


### Relevant Frigate log output

```shell
Unable to get for now.
```


### Relevant go2rtc log output

```shell
N/A
```


### FFprobe output from your camera

```shell
N/A
```


### Frigate stats

_No response_

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    #    image: ghcr.io/blakeblackshear/frigate:stable
    #image: ghcr.io/blakeblackshear/frigate:b4acf4f-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:9c75123-standard-arm64 # crashes with some go2rtc index out of rnage issue
#    image: ghcr.io/blakeblackshear/frigate:039ab1c-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:47ad0ca-standard-arm64
#    image: ghcr.io/blakeblackshear/frigate:0b71cfa-standard-arm64
#    image: ghcr.io/blakeblackshear/frigate:ee8091b-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:0fc7999-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:eda52a3-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:5f77408-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:6294ce7-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:2137de3-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:d12c780-standard-arm64
    #image: ghcr.io/blakeblackshear/frigate:ed9c678-standard-arm64
    image: ghcr.io/blakeblackshear/frigate:ee816b2-standard-arm64

    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11  # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/victorhooi/frigate-docker/config:/config
      - /home/victorhooi/frigate-docker/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: ${PLUS_API_KEY}
```


### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Axis LV 3248

### Screenshots of the Frigate UI's System metrics pages

_No response_

### Any other information that may be helpful

_No response_
