### DISCUSSION TITLE
Sometimes "no recordings found for this time" but not always

### DISCUSSION THREAD

**Discussion by bonjour81** [blakeblackshear/frigate#15306] [Ask A Question]
Hello,

Yesterday evening I had some events with "no recordings found for this time" : I can see the event in review tab, I have snapshots, I even have working video preview if I hover my mouse on the preview picture. but I cannot open the video footage.

2 days ago I setup frigate+ custom model and modified my config, so maybe it has something to do with it that if I didn't understood correctly some configuration.

Today I had a few captured events, with video, no more problem.

Here is an extract of my config:
```

detectors:
  coral:
    type: edgetpu
    device: pci:0

model:
  path: plus://xxxx

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .65  # default 0.85
    car:
      min_score: .65
      threshold: .85

record:
  enabled: true
  #sync_recordings: true
  expire_interval: 1440  # =24h Number of minutes to wait between cleanup runs
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    objects:
      - person
    retain:
      default: 20 # days
      mode: all
      objects:  # is this need if default is same 20days?
        person: 20

snapshots:
  timestamp: true
  retain:
    default: 100  # days

go2rtc:
  streams:
    indoor1:  # Foscam R5
      - rtsp://login:pass@192.168.x.x:88/videoMain
    indoor1_sub:
      - rtsp://login:pass@192.168.x.x:88/videoSub
      - "ffmpeg:indoor1_sub#audio=aac"


########################### CAMERAS ###############################
cameras:


############################ INDOOR1 ##############################
  indoor1:
    enabled: true
    onvif:   # pour gérer les mouvements de la camera
      host: 192.168.x.x
      port: 888
      user: an_other_login
      password: an_other_pass
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor1?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/indoor1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 1024
      height: 768
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    objects:
      track:
        - person
      filters:
        person:
          threshold: .7
          min_score: .7

    audio:
      enabled: true
      max_not_heard: 1  # Optional: Configure the amount of seconds without detected audio to end the event (default: 30)
      # Optional: Configure the min rms volume required to run audio detection (default: shown below)
      # As a rule of thumb:
      #  - 200 - high sensitivity
      #  - 500 - medium sensitivity
      #  - 1000 - low sensitivity
      min_volume: 100
      # Optional: Types of audio to listen for (default: shown below)
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
        - crying
        - cough
        - scream
        - speech
        - yell
        - babbling
        - whispering
        - sigh
        - groan
        - grunt
        - knock
        - cupboard_open_or_close
        - drawer_open_or_close
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1920
      quality: 95
      required_zones: []
    motion:
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.   default : 30
      threshold: 30
      # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 10 - high sensitivity   default
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      improve_contrast: 'true'
      contour_area: 20
      mask: 0.291,0,0.291,0.062,0.328,0.062,0.329,0
```

Note: while it's a wifi camera, it's usually pretty stable and I didn't notice error message in logs (unless I missed it)

In order to setup my frigate+ model, I just follow like explained here :  https://docs.frigate.video/plus/first_model
But I'm not fully sure of the need of step 4 here and what does it do vs my current config with objects/tracks/filters inside the camera settings.  
Is this section at root of config mandatory ? 

Note: I have not very high threshold on purpose (you can 0.65 or 0.7) to have more detection than expected, in order to evaluate where I am with new model and tune it later for each camera. 

As I'm not sure about the purpose of object/filter at root of config file (step4), I was wondering : can it be that frigate trigger an event starting from 0.65 that I set here but filters recording below 0.7 as I set in camera settings ? 
Say Frigate detect something at level 0.68...could it pass the 0.65 and trigger an event but won't record because it's below 0.7 ?
