### DISCUSSION TITLE
docker image under unraid started filling up after last release?

### DISCUSSION THREAD

**Discussion by simondsmason** [blakeblackshear/frigate#15316] [Ask A Question]
About a week ago I started to get warnings about the docker image getting too big and filling up.  The container size stats show nothing out of the ordinary.

frigate12                                       1.92 GB                  4.38 MB                  9.49 MB

I have been able to point the finger at Frigate through process of elimination of shutting down containers and bringing them up one at a time.  It takes a few hours for this to happen.

I don't see anything in the logs that points me to anything but happy to post if that is useful? I haven't looked at them when the docker image is filling up as I am usually remote and just restart frigate.

I thought I could step back a version to see if it continues?  But I am not really sure how to do that so if this is a reasonable test please advise on how to do that.

startup parameters:

--shm-size=512mb --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --restart unless-stopped --runtime=nvidia

config file:

```
mqtt:
  host: 192.168.2.110
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: ##########
  stats_interval: 60
ffmpeg:
  hwaccel_args: preset-nvidia-h264
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 30
    mode: all
birdseye:
  enabled: true
  width: 1024
  height: 576
#  width: 1280
#  height: 720
#  width: 1920
#  height: 1080
  mode: continuous
  restream: true
  layout:
    scaling_factor: 1.5
#    max_cameras: 9
go2rtc:
  streams:
    driveway:
      - rtsp://admin:#########@192.168.2.234:554//h264Preview_01_main
      - ffmpeg:driveway#audio=opus
    drivewaysub:
      - rtsp://admin:#########@192.168.2.234:554//h264Preview_01_sub
      - ffmpeg:driveway#audio=opus
    back_garden:
      - rtsp://admin:#########@192.168.2.33:554//h264Preview_01_main
      - ffmpeg:back_garden#audio=opus
    back_gardensub:
      - rtsp://admin:#########@192.168.2.33:554//h264Preview_01_sub
      - ffmpeg:back_garden#audio=opus
    front_door:
      - rtsp://admin:#########@192.168.2.160:554//h264Preview_01_main
      - ffmpeg:front_door#audio=opus
    front_doorsub:
      - rtsp://admin:#########@192.168.2.160:554//h264Preview_01_sub
      - ffmpeg:front_door#audio=opus
    porch:
      - rtsp://admin:#########@192.168.2.161:554//h264Preview_01_main
      - ffmpeg:porch#audio=opus
    porchsub:
      - rtsp://admin:#########@192.168.2.161:554//h264Preview_01_sub
      - ffmpeg:porch#audio=opus
    front_garden:
      - rtsp://admin:#########@192.168.2.149:554//h264Preview_01_main
      - ffmpeg:front_garden#audio=opus
    front_gardensub:
      - rtsp://admin:#########@192.168.2.149:554//h264Preview_01_sub
      - ffmpeg:front_garden#audio=opus
    kitchen:
      - rtsp://admin:#########@192.168.2.227:554//h264Preview_01_main
      - ffmpeg:kitchen#audio=opus
    kitchensub:
      - rtsp://admin:#########@192.168.2.227:554//h264Preview_01_sub
      - ffmpeg:kitchen#audio=opus
    garage:
      - rtsp://192.168.2.110:8556/garage_inside/main
      - ffmpeg:garage#audio=opus
    patio:
      - rtsp://admin:#########6667@192.168.2.95:554//h264Preview_01_main
      - ffmpeg:driveway#audio=opus
    patiosub:
      - rtsp://admin:#########6667@192.168.2.95:554//h264Preview_01_sub
      - ffmpeg:driveway#audio=opus
    #home_office:
    #  - rtsp://admin:#########@192.168.2.217:554/live
    #  - ffmpeg:home_office#audio=opus
    #home_theater:
    #  - rtsp://admin:#########@192.168.2.233:554/live
    #  - ffmpeg:home_theater#audio=opus
    birdseye:
      - rtsp://127.0.0.1:8554/birdseye
  webrtc:
    candidates:
      - 192.168.2.110:8555
      - stun:8555
cameras:
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drivewaysub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      required_zones:
        - entire_frame_driveway
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 0,1,0.352,1,0.353,0.926,0,0.926
        - 0,0,0,0.766,0.357,0.852,0.399,0.5,0.377,0.252,0.305,0
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      driveway_car:
        coordinates: 0.771,0.332,0.811,0.218,0.759,0.167,0.609,0.172,0.63,0.231,0.581,0.314
        inertia: 3
        loitering_time: 0
        objects: car
      driveway_not_car:
        coordinates: 
          0.133,0.805,0.168,0.913,0.355,0.918,0.357,0.99,0.996,0.988,0.996,0.003,0.839,0,0.837,0.135,0.602,0.125,0.351,0.155,0.38,0.247,0.402,0.497,0.359,0.853
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones: driveway_car
  back_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      required_zones:
        - entire_frame_back_garden
        - back_step
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 0,720,469,720,471,670,0,670
    zones:
      entire_frame_back_garden:
        coordinates: 
          1204,0,1135,395,1044,223,970,215,911,259,868,395,879,509,958,581,970,720,473,720,469,664,0,669,0,0
        objects:
          - person
      back_step:
        coordinates: 0.756,1,0.959,1,0.891,0.664,0.745,0.664
        objects:
          - dog
          - cat
        inertia: 3
        loitering_time: 0
    review:
      alerts: {}
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 0,673,479,673,485,720,0,720
    zones:
      entire_front_door:
        coordinates: 1280,127,1280,720,664,720,268,212,70,321,0,127
        objects:
          - person
          - dog
          - cat
      front_step:
        coordinates: 0.106,0.69,0.052,0.451,0.209,0.297,0.515,1,0.384,1,0.195,1,0.084,0.728
        objects:
          - dog
          - cat
        inertia: 3
        loitering_time: 0
  porch:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/porch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porchsub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 442,707,442,664,14,665,12,711
  front_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_gardensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      required_zones:
        - entire_frame_front_garden
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 12,705,439,703,437,666,11,671
    zones:
      entire_frame_front_garden:
        coordinates: 1280,720,1280,288,982,292,725,308,438,355,181,400,0,469,0,661,454,665,457,720
    review:
      alerts:
        required_zones:
          - entire_frame_front_garden
  kitchen:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
#            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kitchensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    detect:
      enabled: true
    motion:
      mask:
        - 0,352,230,352,231,320,0,320
        - 419,141,468,151,465,98,419,87
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          roles:
            - rtmp
            - detect
    detect:
      enabled: true
    birdseye:
      enabled: true
    motion:
      mask:
        - 0,720,475,720,476,664,0,664
  patio:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/patio?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patiosub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      required_zones:
        - entire_frame_patio
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 0,720,448,720,446,671,0,672
    zones:
      entire_frame_patio:
        coordinates: 1280,720,1280,0,0,0,0,661,454,665,457,720
    review:
      alerts:
        required_zones:
          - entire_frame_patio
  #home_office:
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/home_office?video=copy&audio=aac
  #        roles:
  #          - rtmp
  #          - detect
  #  objects:
  #    track:
  #      - person
  #      - dog
  #      - cat
  #  snapshots:
  #    enabled: true
  #    timestamp: true
  #    bounding_box: true
  #    retain:
  #      default: 30
  #  record:
  #    enabled: true
  #    retain:
  #      days: 30
  #      mode: all
  #    events:
  #      pre_capture: 1
  #      post_capture: 1
  #  birdseye:
  #    enabled: true
#    motion:
#      mask:
#        - 1349,1080,1920,1080,1920,1002,1347,1002
#        - 652,1080,1185,1080,1155,548,847,541
#  home_theater:
#    ffmpeg:
#      inputs:
#        - path: rtsp://127.0.0.1:8554/home_theater?video=copy&audio=aac
#          roles:
#            - rtmp
#            - detect
#    objects:
#      track:
#      - person
#      - dog
#      - cat
#    snapshots:
#      enabled: true
#      timestamp: true
#      bounding_box: true
#      retain:
#        default: 30
#    record:
#      enabled: true
#      retain:
#        days: 30
#        mode: all
#      events:
#        pre_capture: 1
#        post_capture: 1
#    detect:
#      enabled: false
#    birdseye:
#      enabled: false
#    motion:
#      mask:
#        - 1356,1080,1920,1080,1920,1005,1357,1004
version: 0.14
camera_groups:
  Minus_Kitchen:
    order: 1
    icon: LuCamera
    cameras:
      - back_garden
      - driveway
      - front_door
      - front_garden
      - garage
      - patio
      - porch
```
