### DISCUSSION TITLE
[Support]: Environment variable in go2rtc stream configuration is not url encoded

### DISCUSSION THREAD

**Discussion by jsternberg** [blakeblackshear/frigate#15313] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

If you use an environment variable such as `FRIGATE_RTSP_PASSWORD` to fill in a password like so:

```
cameras:
  mycamera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://username:${FRIGATE_RTSP_PASSWORD}@192.168.1.100
```

This works fine as-is even if the password contains non-url safe characters like `@` or `%`. The password gets urlencoded.

If you do the same in the `go2rtc` section, the password must be urlencoded in the environment variable file otherwise it won't work.

```
cameras:
  mycamera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mycamera

go2rtc:
  streams:
    mycamera:
      - rtsp://username:${FRIGATE_RTSP_PASSWORD}@192.168.1.100
```

The `FRIGATE_RTSP_PASSWORD` here doesn't get url encoded automatically. It has to be url encoded manually. If you do that, it works fine.

### Steps to reproduce

1. Create environment variable `FRIGATE_RTSP_PASSWORD` with an `@` symbol in the password (or any character that needs to be url encoded).
2. Have your camera use that password.
3. Attempt to use the password as-is without manually url encoding it.

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
cameras:
  mycamera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mycamera

go2rtc:
  streams:
    mycamera:
      - rtsp://username:${FRIGATE_RTSP_PASSWORD}@192.168.1.100
```

### docker-compose file or Docker CLI command

```yaml
docker  \
  run \
  --rm \
  --name=frigate \
  --log-driver=journald \
  --env-file /etc/secrets.d/frigate.conf \
  -v /etc/localtime:/etc/localtime:ro \
  -v /var/lib/frigate:/config \
  -v /data/frigate:/media/frigate \
  --privileged \
  '--net=host' \
  '--shm-size=8g' \
  '--mount=target=/tmp/cache,tmpfs-size=1000000000,type=tmpfs' \
  '--device=/dev/dri' \
  '--device=/dev/dma_heap' \
  '--device=/dev/rga' \
  '--device=/dev/mpp_service' \
  ghcr.io/blakeblackshear/frigate:0.14.1-rk
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
Dec 02 14:37:22 nixos docker-frigate-start[7093]: 2024-12-02 14:37:22.873962966  14:37:22.873 WRN [rtsp] error="streams: parse \"rtsp://username:password@192.168.1.100:554/Streaming/channels/101/\": net/url: invalid userinfo" stream=mycamera
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

LTS

### Screenshots of the Frigate UI's System metrics pages

N/A
