### DISCUSSION TITLE
[Config Support]: priorities with zones objects filters vs cameras objects filters

### DISCUSSION THREAD

**Discussion by bonjour81** [blakeblackshear/frigate#15335] [Config Support]
### Describe the problem you are having

Hi, 
I have time to time some false detection in foreground (objects seen as person) while I may miss some person in the background.
So, I was considering using zones to set different filtering threshold.

But I was wondering how this is managed by frigate as there different places to set thresholds.

Let take the config here as example.

- Is the "0.62" threshold higher priority than zones ? 
- How can I set a default threshold for are not covered by any zone ?
- Shall I remove the whole filter 0.62 section to keep only filters in zone (and make sure the while image is covered by zones?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
########################### OUTDOOR4 ##############################
  outdoor4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outdoor4   # 2688x1520 15FPS
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outdoor4_sub  # 1280x720  6FPS
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          threshold: .62
          min_score: .62
    motion:
      threshold: 20
      mask: 0.248,0,0.293,0,0.289,0.062,0.247,0.064          # mask seconds time stamp
    zones:
      foreground:
        coordinates: 0,0.475,0.384,0.29,1,0.649,1,1,0,1
        loitering_time: 0
        filters:
          person:
            threshold: .8
            min_score: .8

      background:
        coordinates: 0.006,0.455,0.009,0.017,0.555,0.026,0.98,0.047,0.978,0.569,0.364,0.26
        loitering_time: 0
        filters:
          person:
            threshold: .5
            min_score: .5
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

n/a
