### DISCUSSION TITLE
How to switch frigate container to host networking mode?

### DISCUSSION THREAD

**Discussion by jjuzwik** [blakeblackshear/frigate#15346] [Ask A Question] [answered]
I'd like to get an Apple TV device to display my cameras via HomeKit, and it is my understanding that the frigate docker container needs to run in 'host' mode. I believe mine is running in bridge mode currently. Everything is working well currently, so I'm hoping for assistance in safely switching frigate to run in this manner.  Thx for the help!

**Comment by NickM-27** [comment, marked as answer]
https://docs.docker.com/engine/network/drivers/host/

**Reply by jjuzwik** [reply]
Thx, it looks pretty straight forward to rebuild the container in host mode... Will the frigate data be preserved, like events, detections, snapshots etc?

**Reply by NickM-27** [reply]
assuming your docker compose is setup correctly, yes

**Reply by jjuzwik** [reply]
I was able to rebuild the container in host mode, but it basically created a new working frigate container (using the same frigate config), missing previous data.  No big deal because I am not in production yet.  The data is there on disc, like clips and recordings, frigate now just seems to be ignoring it. Any thoughts on this one?  I'll add my before/after compose files below...




*****PREVIOUS 
cat OG_docker-compose.yml 

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5900:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXXXXX"
      PLUS_API_KEY: "XXXXXXXXX"
```

CURRENT

cat docker-compose.yml 

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    network_mode: host
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXXXX"
      PLUS_API_KEY: "XXXXXXXXX"
```
