### DISCUSSION TITLE
[Detector Support]: which detector to get

### DISCUSSION THREAD

**Discussion by spitfire** [blakeblackshear/frigate#15344] [Detector Support]
### Describe the problem you are having

I'm currently using Frigate installed in a container using an Nvidia GPU, which does pretty well, but uses a lot of power. I was wondering if I could use my TrueNAS Scale system running on an Intel CPU. It does work and with the following configuration I'm getting < 10ms Detector Inference Speed with 4 cameras. I have only enabled detection so far and looked ash the debug view.
However the detection rate is not as good as on the Nvidia container.
As the GPU seems pretty bored I was wondering if there are other models that I could try.
Can someone  point me on to which models I can try and how to install them?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### docker-compose file or Docker CLI command

```yaml
[
    {
        "Id": "29aeeb89383e28765c4fa345ff030baace7789325689567accba47b85b9e8eb1",
        "Created": "2024-12-04T15:10:18.528168209Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2091479,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-12-04T15:10:18.705085529Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2024-12-04T17:08:39.515045412+01:00",
                        "End": "2024-12-04T17:08:39.577573455+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-12-04T17:08:49.577979373+01:00",
                        "End": "2024-12-04T17:08:49.638122575+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-12-04T17:08:59.638460311+01:00",
                        "End": "2024-12-04T17:08:59.707535967+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-12-04T17:09:09.708027976+01:00",
                        "End": "2024-12-04T17:09:09.798983827+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2024-12-04T17:09:19.800434847+01:00",
                        "End": "2024-12-04T17:09:19.909584123+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:d1502760b3b1eb627b63bb4f7f44b786228930d98403a12852f9708f1a6fd4c0",
        "ResolvConfPath": "/mnt/.ix-apps/docker/containers/29aeeb89383e28765c4fa345ff030baace7789325689567accba47b85b9e8eb1/resolv.conf",
        "HostnamePath": "/mnt/.ix-apps/docker/containers/29aeeb89383e28765c4fa345ff030baace7789325689567accba47b85b9e8eb1/hostname",
        "HostsPath": "/mnt/.ix-apps/docker/containers/29aeeb89383e28765c4fa345ff030baace7789325689567accba47b85b9e8eb1/hosts",
        "LogPath": "/mnt/.ix-apps/docker/containers/29aeeb89383e28765c4fa345ff030baace7789325689567accba47b85b9e8eb1/29aeeb89383e28765c4fa345ff030baace7789325689567accba47b85b9e8eb1-json.log",
        "Name": "/ix-frigate01-frigate-1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": [
            "b30520319d997888876e4babbe255b9ab68411bba74b1dd5ad50b60746b2738c"
        ],
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": [
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "PERFMON",
                "SETGID",
                "SETUID"
            ],
            "CapDrop": [
                "ALL"
            ],
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": [
                "44",
                "107",
                "568"
            ],
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "no-new-privileges"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 2000000000,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [
                {
                    "PathOnHost": "/dev/dri",
                    "PathInContainer": "/dev/dri",
                    "CgroupPermissions": "rwm"
                }
            ],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 8589934592,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Target": "/tmp",
                    "VolumeOptions": {}
                },
                {
                    "Type": "bind",
                    "Source": "/mnt/.ix-apps/app_mounts/frigate01/cache",
                    "Target": "/tmp/cache",
                    "BindOptions": {
                        "Propagation": "rprivate"
                    }
                },
                {
                    "Type": "bind",
                    "Source": "/mnt/.ix-apps/app_mounts/frigate01/config",
                    "Target": "/config",
                    "BindOptions": {
                        "Propagation": "rprivate"
                    }
                },
                {
                    "Type": "bind",
                    "Source": "/mnt/.ix-apps/app_mounts/frigate01/media",
                    "Target": "/media",
                    "BindOptions": {
                        "Propagation": "rprivate"
                    }
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/.ix-apps/docker/overlay2/973a900ce9d4e6799a72bf017cb102f2889fdad0525098a9e5cdaa70b91da3ce-init/diff:/mnt/.ix-apps/docker/overlay2/3106185c4708485a4a4ed2ee5d76ffd92b5625bc9ab28a247b6106c6bbf439f4/diff:/mnt/.ix-apps/docker/overlay2/31a9a52a60529d25c39795722bfebd2525041d82c11e800e7b4b8eb3ebd43fee/diff:/mnt/.ix-apps/docker/overlay2/55abc72d938d0c7bd6b062a7f6770839f2e198727152246cb219fb6fd48d13a4/diff:/mnt/.ix-apps/docker/overlay2/9f7c279d54fa34e468cd5ca82397f6a0c8ea879fedf87b801e446669d9f9f3d5/diff:/mnt/.ix-apps/docker/overlay2/efd96eb4d9056d18502619a527ab0079f921803054fe703e45b9b598b37b4145/diff:/mnt/.ix-apps/docker/overlay2/01369817c89b08803c4521656d03b9574d6137f4a6505c237a09980350b54562/diff:/mnt/.ix-apps/docker/overlay2/8cb5059be020adf45f2d57a39914a4994fdaaac8f06495d0e00e5833e5dafc05/diff",
                "MergedDir": "/mnt/.ix-apps/docker/overlay2/973a900ce9d4e6799a72bf017cb102f2889fdad0525098a9e5cdaa70b91da3ce/merged",
                "UpperDir": "/mnt/.ix-apps/docker/overlay2/973a900ce9d4e6799a72bf017cb102f2889fdad0525098a9e5cdaa70b91da3ce/diff",
                "WorkDir": "/mnt/.ix-apps/docker/overlay2/973a900ce9d4e6799a72bf017cb102f2889fdad0525098a9e5cdaa70b91da3ce/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "0d44da5151679e3f8328a6710141266f52b4fd39eeecc943299b5db4a441744f",
                "Source": "/mnt/.ix-apps/docker/volumes/0d44da5151679e3f8328a6710141266f52b4fd39eeecc943299b5db4a441744f/_data",
                "Destination": "/tmp",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/mnt/.ix-apps/app_mounts/frigate01/cache",
                "Destination": "/tmp/cache",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/.ix-apps/app_mounts/frigate01/config",
                "Destination": "/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/.ix-apps/app_mounts/frigate01/media",
                "Destination": "/media",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "s01truenas01",
            "Domainname": "",
            "User": "0:0",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5000/tcp": {},
                "8554/tcp": {},
                "8555/tcp": {},
                "8555/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "NVIDIA_VISIBLE_DEVICES=void",
                "TZ=Europe/Warsaw",
                "UMASK=002",
                "UMASK_SET=002",
                "PATH=/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/tempio/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
                "S6_LOGGING_SCRIPT=T 1 n0 s10000000 T",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl --silent --output /dev/null --show-error --fail http://127.0.0.1:5000/api"
                ],
                "Interval": 10000000000,
                "Timeout": 5000000000,
                "StartPeriod": 10000000000,
                "StartInterval": 5000000000,
                "Retries": 30
            },
            "Image": "ghcr.io/blakeblackshear/frigate:0.14.1",
            "Volumes": null,
            "WorkingDir": "/opt/frigate/",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "cc39de980d75511bcb1c41ff1d1b61482e3eb737c2fc4f65b2742fa84e9438f1",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:d1502760b3b1eb627b63bb4f7f44b786228930d98403a12852f9708f1a6fd4c0",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ix-frigate01",
                "com.docker.compose.project.config_files": "/mnt/.ix-apps/app_configs/frigate01/versions/1.1.7/templates/rendered/docker-compose.yaml",
                "com.docker.compose.project.working_dir": "/mnt/.ix-apps/app_configs/frigate01/versions/1.1.7/templates/rendered",
                "com.docker.compose.service": "frigate",
                "com.docker.compose.version": "2.29.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "df351c5411e096792f9ac0f786e3b163cb8452a5bfb2c1097bd5f79990721495",
            "SandboxKey": "/var/run/docker/netns/default",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "",
                    "DriverOpts": null,
                    "NetworkID": "a18d504f6d4aa9ab066d602e592a804fc1c83d9ee952b119c1bf54875757c979",
                    "EndpointID": "6b58a8f8035b8ee15fa0c34c3ff32a5a509a24a8fa09e3110f3f69eb9d83dc9b",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": null
                }
            }
        }
    }
]
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker CLI

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

<img width="1810" alt="Zrzut ekranu 2024-12-4 o 17 07 19" src="https://github.com/user-attachments/assets/23d3e597-34fa-456f-a25
<img width="1807" alt="Zrzut ekranu 2024-12-4 o 17 07 42" src="https://github.com/user-attachments/assets/df47887b-7636-4f10-b2f8-95fe04f44b91">
5-58d09b061718">

### Any other information that may be helpful

`{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLD"}`
