### DISCUSSION TITLE
[Config Support]: Best way to display camera feeds in HA?

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#15350] [Config Support]
### Describe the problem you are having

Sorry if this is a stupid question. I'm trying to figure out what the best current way is to display my frigate camera feeds in my HA dashboard. 

There's a variety of different cards (HA card, frigate card, web2rtc card, etc.) plus I'm not sure if I need something in my config to better facilitate it. Also, I'm not sure if HA's recent udpate of web2rtc changes things. I do have "Use Frigate-native WebRTC support" enabled in my Frigate HA integration if relevant.

Right now, I use Frigate cards but the streams are often very choppy both internally and remotely (via CloudFlare tunnel). 

But if I go to the Frigate UI in HA, they are perfectly sharp. Maybe this is just an HA issue, but I thought I'd atleast check.

I run Frigate via Docker & Portainer on my Intel NUC seperate from HA.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.107.2
  port: 1883
  user: user1
  password: password1
  topic_prefix: frigate

go2rtc:
  streams:
    FrontPorch:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=0
    FrontPorch_sub:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=1
    Driveway:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=1
    FrontYardRight:
      - rtsp://admin:admin@192.168.107.48:554/cam/realmonitor?channel=1&subtype=0
    FrontYardRight_sub:
      - rtsp://admin:admin@192.168.107.48:554/cam/realmonitor?channel=1&subtype=1
    BackDeck:
      - rtsp://admin:admin@192.168.107.43:554/cam/realmonitor?channel=1&subtype=0
    BackDeck_sub:
      - rtsp://admin:admin@192.168.107.43:554/cam/realmonitor?channel=1&subtype=1
    BackPatio:
      - rtsp://admin:admin@192.168.107.41:554/cam/realmonitor?channel=1&subtype=0
    BackPatio_sub:
      - rtsp://admin:admin@192.168.107.41:554/cam/realmonitor?channel=1&subtype=1

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
  Driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
      mask: 0.189,0.697,0.812,0.743,1,0.982,0.001,0.996,0.004,0.703
  FrontYardRight:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontYardRight
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontYardRight_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
  BackDeck:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BackDeck
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackDeck_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
  BackPatio:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BackPatio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackPatio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
version: 0.14
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/frigate:/config
      - /media/user/T7:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral
