### DISCUSSION TITLE
[Support]: ONNX thread error in logs on container start

### DISCUSSION THREAD

**Discussion by YenLegion** [blakeblackshear/frigate#15351] [General Support] [answered]
### Describe the problem you are having

Been seeing the following error in the last few dev builds of 0.15. Seems to be running okay aside from the known Proxmox issues.

Running Docker in a Debian 12 privileged LXC on Proxmox 8.3.1 kernel 6.11.0-1-pve

SR-IOV passthrough of iGPU into LXC 

```
[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 530, index: 3, mask: {6, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.)

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 528, index: 1, mask: {4, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 527, index: 0, mask: {2, 3, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 533, index: 6, mask: {9, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 535, index: 8, mask: {11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity 
```

### Version

0.15.0:4dddc53 

### What browser(s) are you using?

Chromium: 131.0.6778.85

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: REDACTED
  port: 1883
  client_id: REDACTED
  user: REDACTED
  password: REDACTED
  topic_prefix: REDACTED
  stats_interval: 15

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: false
  provider: gemini
  api_key: REDACTED
  model: gemini-1.5-flash

auth:

  enabled: true
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - REDACTED

birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 8
  mode: objects
  inactivity_threshold: 30
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    REDACTED:
      - ffmpeg:http://REDACTED/h264.flv#video=copy
    REDACTED:
     - rtsp://REDACTED:8554/REDACTED
     - ffmpeg:REDACTED#video=copy#audio=copy#audio=opus
    REDACTED:
      - ffmpeg:https://REDACTED/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
      - rtsp://REDACTED:REDACTED@REDACTED:554/h264Preview_01_sub
      - ffmpeg:REDACTED#audio=opus#audio=volume
      - ffmpeg:REDACTED#audio=aac#audio=volume
    REDACTED_sub:
      - http://REDACTED/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=REDACTED&password=REDACTED
      - rtsp://REDACTED:REDACTED@REDACTED:554/h264Preview_01_sub
      - ffmpeg:REDACTED_sub#audio=copy#audio=opus
    REDACTED:
      - rtsp://REDACTED:REDACTED@REDACTED/cam/realmonitor?channel=1&subtype=0&authbasic=REDACTED
      - ffmpeg:REDACTED#audio=opus
    REDACTED_sub:
      - rtsp://REDACTED:REDACTED@REDACTED/cam/realmonitor?channel=1&subtype=1&authbasic=REDACTED
      - ffmpeg:REDACTED_sub#audio=opus
    REDACTED:
      - rtsp://REDACTED/live.sdp
      - ffmpeg:REDACTED#video=copy
  ffmpeg:
    volume: -af "volume=50dB"
  webrtc:
    candidates:
      - REDACTED:8555
      - stun:8555
cameras:
  REDACTED:
    enabled: false
    webui_url: http://REDACTED
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/REDACTED
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      retry_interval: 10
    detect:
      enabled: false
      fps: 5
    audio:
      enabled: false
      min_volume: 0
      max_not_heard: 1
    mqtt:
      enabled: true
    genai:
      enabled: false

  REDACTED:
    enabled: false
    webui_url: http://REDACTED
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/
          input_args: preset-rtsp-restream
          roles:
            - record
      retry_interval: 15
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    audio:
      enabled: false
      min_volume: 10
      max_not_heard: 30
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
    snapshots:
      enabled: true
    motion:
      mask: 0,0,0.995,0.003,1,0.192,0,0.287
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      REDACTED_zone:
        coordinates: 0,0.308,0.002,1,1,1,1,0.211
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: REDACTED_zone

  REDACTED:
    enabled: true
    webui_url: http://REDACTED
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/REDACTED
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      retry_interval: 10
    audio:
      enabled: false
      min_volume: 0
      max_not_heard: 1
    mqtt:
      enabled: true
    detect:
      enabled: false
      fps: 5
    motion:
      threshold: 80
      contour_area: 100
      improve_contrast: 'true'
    genai:
      enabled: false

  REDACTED:
    webui_url: http://REDACTED
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/REDACTED
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/REDACTED_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
      retry_interval: 10
    genai:
      enabled: true
    detect:
      width: 1280
      height: 960
      fps: 5
    audio:
      enabled: true
      min_volume: 40
      max_not_heard: 30
      filters:
        speech:
          threshold: 0.7
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
    zones:
      REDACTED_zone:
        coordinates: 0.385,0.688,0.533,0.678,0.643,0.757,0.699,0.743,1,0.683,1,1,0.344,1
        inertia: 3
        loitering_time: 0
        objects: person
      REDACTED:
        coordinates: 0.378,0.586,0.96,0.598,0.947,0.642,0.383,0.687
        loitering_time: 0
        objects:
          - car
          - person
        inertia: 3
    review:
      alerts:
        required_zones:
          - REDACTED_zone
          - REDACTED_zone
    snapshots:
      enabled: true
      required_zones:
        - REDACTED_zone
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: false
      mask:
        - 0.377,0,0.358,0.506,1,0.487,1,0,0.849,0
        - 0,0.006,0,1,0.173,1,0.368,0.748,0.383,0.009
    objects:
      filters:
        car:
          mask:
            - 0.346,1,0.482,0.997,0.423,0.88,0.399,0.878
            - 0.523,0.616,0.537,0.672,0.649,0.75,0.775,0.706,0.762,0.611,0.723,0.591,0.677,0.582,0.595,0.581
        person:
          mask: 0.666,0.482,0.671,0.591,0.849,0.596,0.845,0.487
          
  REDACTED:
    webui_url: http://REDACTED
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/REDACTED
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/REDACTED_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      retry_interval: 10
    detect:
      width: 704
      height: 480
      fps: 5
    audio:
      enabled: true
      min_volume: 0
      max_not_heard: 30
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
    zones:
      REDACTED_zone:
        coordinates: 0.256,0.108,0.378,1,1,1,1,0.185,0.701,0.081
        objects: person
        inertia: 3
        loitering_time: 0
    snapshots:
      enabled: true
      required_zones:
        - REDACTED_zone
    review:
      alerts:
        required_zones: REDACTED_zone
    motion:
      mask: 0.234,0.009,0.006,0.011,0.003,0.996,0.364,0.99
      threshold: 30
      contour_area: 10
      improve_contrast: true
    objects:
      filters:
        car:
          mask: 0.355,0,0.421,0,0.426,0.06,0.358,0.085

  REDACTED:
    enabled: true
    webui_url: http://REDACTED
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/REDACTED
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      retry_interval: 5
    audio:
      enabled: false
      min_volume: 0
      max_not_heard: 30
    detect:
      width: 1280
      height: 800
      fps: 5
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
      mask: 1,0,1,0.299,0,0.29,0.002,0.005
    zones:
      REDACTED_zone:
        coordinates: 0,0.513,1,0.536,0.998,1,0.002,0.996
        loitering_time: 0
        objects: person
        inertia: 3
    snapshots:
      enabled: true
      required_zones:
        - REDACTED_zone
    review:
      alerts:
        required_zones: REDACTED_zone

objects:
  track:
    - person
    - car
review:
  alerts:
    labels:
      - emergency_vehicle
      - police_car
      - ambulance
      - fire_engine
      - person
      - music
      - doorbell
      - smoke_detector
      - fire_alarm
      - car_alarm
      - alarm
      - alarm_clock
      - whistle
      - explosion
      - fireworks
      - firecracker
      - speech
audio:
  listen:
    - emergency_vehicle
    - police_car
    - ambulance
    - fire_engine
    - person
    - music
    - doorbell
    - smoke_detector
    - fire_alarm
    - car_alarm
    - alarm
    - alarm_clock
    - whistle
    - explosion
    - fireworks
    - firecracker
    - speech
detectors:
  coral:
    type: edgetpu
    device: usb
ui:
  time_format: browser
record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 365
    mode: all
  preview:
    quality: medium
  alerts:
    retain:
      days: 365
  detections:
    retain:
      days: 365
snapshots:
  retain:
    default: 365
telemetry:
  stats:
    intel_gpu_stats: false
    network_bandwidth: false
camera_groups:
  all:
    order: 1
    icon: LuActivity
    cameras:
      - REDACTED
      - REDACTED
      - REDACTED
notifications:
  enabled: true
  email: REDACTED
version: 0.15-0
```

### Relevant Frigate log output

```shell
[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 530, index: 3, mask: {6, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.)

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 528, index: 1, mask: {4, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 527, index: 0, mask: {2, 3, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 533, index: 6, mask: {9, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

[E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 535, index: 8, mask: {11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    cap_add:
      - CAP_PERFMON
    network_mode: host
    restart: always
    image: ghcr.io/blakeblackshear/frigate:4dddc53
    shm_size: 512mb
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/config/
      - /mnt/frigate/:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1G
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    environment:
      - FRIGATE_MQTT_USER=${FRIGATE_MQTT_USER}
      - FRIGATE_MQTT_PASS=${FRIGATE_MQTT_PASS}
      - FRIGATE_MQTT_HOST=${FRIGATE_MQTT_HOST}
      - FRIGATE_GEMINI_API_KEY="REDACTED"
    deploy:
      resources:
         limits:
           memory: 8G

networks: {}
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink, Amcrest
