### DISCUSSION TITLE
[Config Support]: Port 8971 and HomeAssistant on a different machine

### DISCUSSION THREAD

**Discussion by koudonojinchuu** [blakeblackshear/frigate#15352] [Config Support] [answered]
### Describe the problem you are having

I'm running Frigate on a machine A, using docker-compose,
and on a machine B (a HomeAssistant Yellow), I'm running HA in baremetal.

I'd like to connect the two of them, but securely, so avoiding port 5000 and using 8971 instead.
However, reading the doc and the other questions here, it would seem that it is not possible?
Is the port 5000 unavoidable when connecting to HA?

### Version

stable-tensorrt

### Frigate config file

```yaml
mqtt:
  host: mqtt

ffmpeg:
  hwaccel_args: preset-nvidia-h264 

cameras:
  camera_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:mypw@192.168.0.xxx:554/Preview_01_sub 
          roles:
            - detect
        - path: rtsp://admin:mypw@192.168.0.xxx:554/Preview_01_main 
          roles:
            - record
    detect:
      enabled: true 
      width: 640 
      height: 480
      fps: 5 
    onvif:
      host: 192.168.0.xxx
      port: 8000
      user: admin
      password: mypw

auth:
  reset_admin_password: true
```

### Relevant Frigate log output

```shell
$ docker-compose up
Recreating frigatefw ... done
Attaching to frigatefw
frigatefw  | s6-rc: info: service s6rc-fdholder: starting
frigatefw  | s6-rc: info: service s6rc-oneshot-runner: starting
frigatefw  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigatefw  | s6-rc: info: service fix-attrs: starting
frigatefw  | s6-rc: info: service s6rc-fdholder successfully started
frigatefw  | s6-rc: info: service fix-attrs successfully started
frigatefw  | s6-rc: info: service legacy-cont-init: starting
frigatefw  | s6-rc: info: service legacy-cont-init successfully started
frigatefw  | s6-rc: info: service trt-model-prepare: starting
frigatefw  | s6-rc: info: service log-prepare: starting
frigatefw  | Generating the following TRT Models: yolov7-320
frigatefw  | Downloading yolo weights
frigatefw  | s6-rc: info: service log-prepare successfully started
frigatefw  | s6-rc: info: service nginx-log: starting
frigatefw  | s6-rc: info: service go2rtc-log: starting
frigatefw  | s6-rc: info: service frigate-log: starting
frigatefw  | s6-rc: info: service certsync-log: starting
frigatefw  | s6-rc: info: service nginx-log successfully started
frigatefw  | s6-rc: info: service go2rtc-log successfully started
frigatefw  | s6-rc: info: service go2rtc: starting
frigatefw  | s6-rc: info: service frigate-log successfully started
frigatefw  | s6-rc: info: service certsync-log successfully started
frigatefw  | s6-rc: info: service go2rtc successfully started
frigatefw  | s6-rc: info: service go2rtc-healthcheck: starting
frigatefw  | s6-rc: info: service go2rtc-healthcheck successfully started
frigatefw  | 2024-12-05 16:08:11.267308533  [INFO] Preparing new go2rtc config...
frigatefw  | 2024-12-05 16:08:11.470748934  [INFO] Starting go2rtc...
frigatefw  | 2024-12-05 16:08:11.540640503  16:08:11.540 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigatefw  | 2024-12-05 16:08:11.540643207  16:08:11.540 INF config path=/dev/shm/go2rtc.yaml
frigatefw  | 2024-12-05 16:08:11.540838807  16:08:11.540 INF [rtsp] listen addr=:8554
frigatefw  | 2024-12-05 16:08:11.540864399  16:08:11.540 INF [api] listen addr=:1984
frigatefw  | 2024-12-05 16:08:11.540917101  16:08:11.540 INF [webrtc] listen addr=:8555/tcp
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigatefw
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml:ro
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Object Detector

TensorRT
