### DISCUSSION TITLE
Optimal configuration for different substreams?

### DISCUSSION THREAD

**Discussion by lyneld** [blakeblackshear/frigate#15359] [Ask A Question] [answered]
Hi All! Not sure if this is the right place to ask my question, but I tried looking around a bit and couldn't find anything definitive. I have about 5 cameras configured in Frigate with a different stream for detection (360p) and recording & live view (1080p). Is my configuration optimal for this setup? I'm confused if I should be entering all my sub streams into the go2rtc section and then using the relevant restream path in the cameras section. Appreciate any tips! 

PS. at the moment everything works quite well, so no real complaints!
PPS. configuration has been trimmed to just 1 cam. also I realize that there are some redundant/default options (e.g. disabled detection), but I've left this in there for ease of making changes later.

```
mqtt:
  host: xxx.xxx.xxx.xxx
  user: xxxx
  password: xxxxxxxx

database:
  path: /config/frigate.db

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
    
go2rtc:
  streams:
    Garage:
      - rtsp://192.168.1.109:8554/1080p?mp4
      - ffmpeg:Garage#video=copy#audio=opus

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.109:8554/360p?mp4
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 0.723,0.938,0.723,0.981,0.977,0.983,0.973,0.94
        - 0.106,0.002,0.362,0.003,0.476,0.081,0.437,0.19,0.297,0.105,0.269,0.084,0.152,0.039,0.138,0.043,0.096,0.031
    record:
      enabled: true
    detect:
      enabled: false
    snapshots:
      enabled: false
      retain:
        default: 7

detect:
  enabled: true
  width: 640
  height: 360
  fps: 5

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: false
  retain:
    default: 3

objects:
  track:
    - person

version: 0.14
```
