### DISCUSSION TITLE
[Config Support]:  Frigate + , portainer APIKEY placement

### DISCUSSION THREAD

**Discussion by balgerion** [blakeblackshear/frigate#15353] [Config Support]
### Describe the problem you are having

I have hard time to make firgate+ page apear :) i think i tried every apikey placement i found in doc and reddit/github - nothing work. 
any suggestion ? 

not working:
![image](https://github.com/user-attachments/assets/08575205-dad9-46cb-bc4f-a193e3fc14fb)
![image](https://github.com/user-attachments/assets/be4c9f07-cb6c-49c4-9270-5cde21de50da)
![image](https://github.com/user-attachments/assets/8e97036b-eca9-4b4e-a06f-ec091ace6313)

### Version

0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.101
  user: MQTT
  password: 

record:
  enabled: true
  retain:
    days: 0
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
snapshots:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rk-h264



cameras:
  Dzwonek:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.1.49:8554/Streaming/Channels/101
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - bird
        - cat
        - dog
    zones:
      Droga:
        coordinates: 0,0.027,1,0,1,1,0,1
        loitering_time: 0
    motion:
      mask:
        - 1,0.649,0.645,0.659,0.62,0.011,0.996,0.004
        - 0.281,0.65,0.363,0.647,0.36,0.516,0.278,0.509
        - 0.027,0.05,0.028,0.101,0.362,0.103,0.363,0.047
    review:
      alerts:
        required_zones: Droga
      detections:
        required_zones: Droga
  FapLab_cam2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.165:7441/JrXtnkyUfC9cgslW?enableSrtp
          roles:
            - detect
        - path: rtsps://192.168.1.165:7441/NqKS15rUdoTbTNpN?enableSrtp
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - bird
        - cat
        - dog
    motion:
      mask:
        - 1,0.336,0.847,0.299,0.649,0.251,0.648,0.101,0.623,0.087,0.623,0.002,0.998,0.005
        - 0,0.033,0.168,0.032,0.168,0,0,0.001
        - 0.887,0.307,0.867,0.998,0.999,0.998,1,0.335
    zones:
      Ogrod:
        coordinates: 
          0.001,0.775,0.011,0.755,0.044,0.821,0.182,0.704,0.419,0.908,0.617,0.602,0.491,0.543,0.663,0.367,0.636,0.35,0.662,0.318,0.649,0.27,0.652,0.258,0.996,0.335,1,1,0,1
        loitering_time: 0
      Taras:
        coordinates: 
          0.043,0.819,0.182,0.702,0.419,0.905,0.617,0.605,0.493,0.542,0.663,0.362,0.636,0.348,0.66,0.315,0.649,0.263,0.649,0.101,0.625,0.086,0.623,0,0,0.002,0,0.766,0.009,0.756
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Ogrod
          - Taras
      detections:
        required_zones:
          - Ogrod
          - Taras
  FapLab_cam1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:FMXDEM@192.168.1.104/ch1/sub/
          roles:
            - detect
        - path: rtsp://admin:FMXDEM@192.168.1.104
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - bird
        - cat
        - dog
    zones:
      Ogrod:
        coordinates: 
          0.396,0.452,0.512,0.448,0.813,0.767,0.877,0.728,0.915,0.781,0.953,0.738,0.996,0.781,0.999,0.998,0.244,0.995
        loitering_time: 0
        inertia: 3
      Taras:
        coordinates: 
          0.647,0.579,0.816,0.762,0.88,0.728,0.916,0.776,0.985,0.697,0.987,0.658,0.992,0.632,0.999,0.612,1,0.598,1,0.561,1,0.507,0.906,0.458,0.841,0.462,0.839,0.52,0.666,0.53,0.608,0.545
        loitering_time: 0
        inertia: 3
      Podjazd:
        coordinates: 0.395,0.445,0.527,0.444,0.518,0.367,0.4,0.365
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones:
          - Ogrod
          - Taras
          - Podjazd
      detections:
        required_zones:
          - Ogrod
          - Taras
          - Podjazd
    motion:
      mask:
        - 0.242,1,0.392,0.452,0.398,0.361,0.521,0.362,0.524,0.261,0.507,0.261,0.532,0.002,0,0,0,1
        - 0.24,1,0.337,1,0.337,0.928,0.245,0.931
  FapLab_cam0:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:BVPHLT@192.168.1.69/ch1/sub/
          roles:
            - detect
        - path: rtsp://admin:BVPHLT@192.168.1.69
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 576
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - bird
        - cat
        - dog
    zones:
      FapLab:
        coordinates: 
          0.667,0.682,0.716,0.057,0.681,0.001,0.001,0.001,0,0.993,0.998,0.998,0.997,0.535,0.809,0.977
        loitering_time: 0
        inertia: 3
      FapLab_wejscie:
        coordinates: 
          0.669,0.682,0.807,0.977,1,0.527,1,0.281,0.929,0.149,0.911,0.172,0.797,0.193,0.761,0.124,0.718,0.052
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - FapLab
          - FapLab_wejscie
      detections:
        required_zones:
          - FapLab
          - FapLab_wejscie
    motion:
      mask:
        - 0.038,0.997,0.039,0.962,0.242,0.963,0.243,0.997
        - 1,0.276,0.928,0.146,0.912,0.172,0.8,0.193,0.678,0,1,0
version: 0.15-0
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta2-rk
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config:/config
      - /home/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    environment:
      - PLUS_API_KEY=532f7d9e-dc78-48bd-acbf-************
```

### Object Detector

Coral
