### DISCUSSION TITLE
[Bug]: When two cameras have recording off, the third camera does not trigger events

### DISCUSSION THREAD

**Discussion by italicize9610** [blakeblackshear/frigate#15368] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have 3 cameras set up. I also have an automation to turn off detection and recordings for 2 of those cameras (facing into my house) when I leave my house. The 3rd camera (doorbell camera, facing outwards) is constantly recording and detecting and is never turned off.

In Frigate 0.15 Beta 2, when my automation turns off detection and recordings for 2 of those cameras, the doorbell camera also fails to produce any events. It is as if detection and recording is also turned off for the 3rd camera.

In Frigate 0.14, with the exact same config and the exact same automation, the doorbell camera continues to produce events. The only change between the versions is that I point the integration to -beta (so that the entities continue to exist). Everything else is the same.

### Steps to reproduce

1. Create an automation turning off record and detection (switch.camera_recordings and switch.camera_detect) for 2 of 3 cameras for any trigger.
2. Activate the automation.
3. Note that Camera 3, the unaffected camera, also fails to produce any events somehow, even though it is still recording and detecting. Cameras 1 and 2 also do not produce events but that is expected.
4. Turn on record and detection for the 2 of 3 cameras.
5. Now note that Camera 3 begins to produce events as expected (as do Cameras 1 and 2 as expected).

### Version

0.15 - Beta 2

### Frigate config file

```yaml
go2rtc:
  streams:
    doorbell: 
      - ffmpeg:rtsp://XXX:XXX@192.168.50.XXX/Preview_01_main#video=copy#audio=copy#audio=opus       
    upstairs: 
      - ffmpeg:rtsp://XXX:XXX@192.168.50.XXX/Preview_01_main#video=copy#audio=copy#audio=opus      
    downstairs: 
      - ffmpeg:rtsp://XXX:XXX@192.168.50.XXX/Preview_01_main#video=copy#audio=copy#audio=opus       

mqtt:
  enabled: true
  host: core-mosquitto
  port: XXX
  user: XXX
  password: XXX

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
###### DOORBELL CAMERA ######
  doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.139,0.958,0.295,0.958,0.296,0.995,0.139,0.993
    zones:
      Front_of_door:
        coordinates: 0.001,0.001,0.001,0.999,0.999,0.999,0.999,0.001
        loitering_time: 5
        inertia: 3
    review:
      alerts:
        required_zones: Front_of_door

###### UPSTAIRS CAMERA ######  
  upstairs: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upstairs
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.14,0.957,0.141,0.998,0.299,0.996,0.3,0.959
###### DOWNSTAIRS CAMERA ###### 
  downstairs: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/downstairs
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.139,0.959,0.143,0.997,0.294,0.998,0.292,0.962

record:
  enabled: true
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 7
      mode: all

objects:
  track:
    - person

detect:
  enabled: true
  width: 1280
  height: 960
  fps: 5

snapshots:
  enabled: true
  retain:
    default: 7

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant Frigate log output
2024-12-05 05:49:40.885762891  [INFO] Preparing Frigate...
2024-12-05 05:49:40.902637216  [INFO] Starting Frigate...
2024-12-05 05:49:42.421329923  [2024-12-05 13:49:42] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-12-05 05:49:42.421465371  [2024-12-05 13:49:42] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-12-05 05:49:42.421468870  [2024-12-05 13:49:42] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-12-05 05:49:42.446101226  [2024-12-05 13:49:42] frigate.util.config            INFO    : frigate config does not need migration...
2024-12-05 05:49:42.642761937  [2024-12-05 13:49:42] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2024-12-05 05:49:42.674583401  [2024-12-05 13:49:42] peewee_migrate.logs            INFO    : Starting migrations
2024-12-05 05:49:42.675374983  [2024-12-05 13:49:42] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-12-05 05:49:42.684617324  [2024-12-05 13:49:42] frigate.app                    INFO    : Recording process started: 391
2024-12-05 05:49:42.690980987  [2024-12-05 13:49:42] frigate.app                    INFO    : Recording process started: 397
2024-12-05 05:49:42.691203673  [2024-12-05 13:49:42] frigate.app                    INFO    : go2rtc process pid: 98
2024-12-05 05:49:42.716377978  [2024-12-05 13:49:42] detector.coral                 INFO    : Starting detection process: 420
2024-12-05 05:49:45.331755252  [2024-12-05 13:49:42] frigate.app                    INFO    : Output process started: 422
2024-12-05 05:49:45.332259228  [2024-12-05 13:49:42] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-12-05 05:49:45.332943978  [2024-12-05 13:49:42] frigate.app                    INFO    : Camera processor started for doorbell: 439
2024-12-05 05:49:45.333226642  [2024-12-05 13:49:42] frigate.app                    INFO    : Camera processor started for upstairs: 440
2024-12-05 05:49:45.333448146  [2024-12-05 13:49:42] frigate.app                    INFO    : Camera processor started for downstairs: 444
2024-12-05 05:49:45.333454321  [2024-12-05 13:49:42] frigate.app                    INFO    : Capture process started for doorbell: 451
2024-12-05 05:49:45.333614895  [2024-12-05 13:49:42] frigate.app                    INFO    : Capture process started for upstairs: 457
2024-12-05 05:49:45.333781056  [2024-12-05 13:49:42] frigate.app                    INFO    : Capture process started for downstairs: 466
2024-12-05 05:49:45.337564005  [2024-12-05 13:49:45] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-12-05 05:51:36.618180711  [2024-12-05 13:51:36] frigate.comms.dispatcher       INFO    : Turning off recordings for upstairs
2024-12-05 05:51:36.661292944  [2024-12-05 13:51:36] frigate.comms.dispatcher       INFO    : Turning off detection for downstairs
2024-12-05 05:51:36.662990781  [2024-12-05 13:51:36] frigate.comms.dispatcher       INFO    : Turning off detection for upstairs
2024-12-05 05:51:36.664259772  [2024-12-05 13:51:36] frigate.comms.dispatcher       INFO    : Turning off recordings for downstairs
2024-12-05 11:40:59.855988578  [2024-12-05 19:40:59] frigate.comms.dispatcher       INFO    : Turning on recordings for upstairs
2024-12-05 11:40:59.897637702  [2024-12-05 19:40:59] frigate.comms.dispatcher       INFO    : Turning on detection for downstairs
2024-12-05 11:40:59.898478192  [2024-12-05 19:40:59] frigate.comms.dispatcher       INFO    : Turning on detection for upstairs
2024-12-05 11:40:59.899943943  [2024-12-05 19:40:59] frigate.comms.dispatcher       INFO    : Turning on recordings for downstairs

### Relevant go2rtc log output
2024-12-05 05:49:40.890668208  [INFO] Preparing new go2rtc config...
2024-12-05 05:49:40.940279545  [INFO] Got IP address from supervisor: 192.168.50.139
2024-12-05 05:49:40.970793289  [INFO] Got WebRTC port from supervisor: 8555
2024-12-05 05:49:41.267213523  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2024-12-05 05:49:41.267217408  [INFO] Starting go2rtc...
2024-12-05 05:49:41.421013832  13:49:41.420 INF go2rtc platform=linux/amd64 revision=dbe9e4a version=1.9.7
2024-12-05 05:49:41.423549136  13:49:41.422 INF config path=/dev/shm/go2rtc.yaml
2024-12-05 05:49:41.423552359  13:49:41.422 INF [rtsp] listen addr=:8554
2024-12-05 05:49:41.423553555  13:49:41.422 INF [api] listen addr=:1984
2024-12-05 05:49:41.423562132  13:49:41.422 INF [webrtc] listen addr=:8555/tcp
2024-12-05 05:49:50.884943862  [INFO] Starting go2rtc healthcheck service...

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Mixed

### Camera make and model

Reolink E1 Zoom x2 and Wireless Doorbell

### Screenshots of the Frigate UI's System metrics pages

NA. Coral running at 9-10 ms inference speeds.

### Any other information that may be helpful

I use Reolink cameras. But this occurs whether I use HTTP streams or not, whether I use a separate substream or not, whether I use restream preset or generic preset. The only config difference between 0.14 to 0.15 is that instead of events it is now split into alert and detections (this was done via the migration on startup of 0.15). For what it's worth, my setup runs 100% stable on 0.14 with the config above (uptime more than 7 days without a single error).

**Comment by hawkeye217** [comment]
Your Frigate logs will show when recording and detection is enabled/disabled for each camera. We can't help without those logs.

If no logs are produced, this would point to an issue with the integration or how you've set it up.

**Reply by italicize9610** [reply]
hey @hawkeye217 , i've updated with the logs above. but as you can see, there's nothing out of the ordinary here. the 3rd camera (doorbell) is untouched by the automation.

i have also checked through the livestream, and when detect/record is off for upstairs and downstairs, doorbell still shows the blue icons for detect and record.

**Reply by hawkeye217** [reply]
When you say "the doorbell camera also fails to produce any events", what happens when you watch the debug view? Are you seeing objects detected?

**Reply by italicize9610** [reply]
Yes, objects are detected. Even in the live view, the red border appears around the doorbell camera livestream. It's just that nothing ever appears in the review panel.

**Reply by hawkeye217** [reply]
You should note that the config file for recording retention has changed between 0.14 and 0.15 beta. See the breaking changes in the [release notes](https://github.com/blakeblackshear/frigate/releases/tag/v0.15.0-beta2). If you are not making those changes between versions, you most certainly will have retention issues.

**Reply by italicize9610** [reply]
@hawkeye217 doesn't 0.15 beta automatically migrate the config? I saw that my record -> events became record -> alerts and record -> detections. but i did not change that other than what frigate 0.15 did automatically upon startup.

**Reply by hawkeye217** [reply]
Yes, migration should happen automatically, but you should review it to make sure it's going to retain what you want it to. https://deploy-preview-13787--frigate-docs.netlify.app/configuration/record/

**Reply by italicize9610** [reply]
got it, i will go back to 0.15 beta 2 and recheck the migrated config for record. will update here when i find out what's wrong.

**Reply by italicize9610** [reply]
@hawkeye217 i have just tested and it doesn't make a difference. i also realised one thing. if i retain the frigate 0.15 migrated config and make no changes, the doorbell behaves correctly when upstairs and downstairs are recording/detecting. but when upstairs and downstairs are not recording/detecting, it does not.

since my record/detect settings are global, logically this implies that the migrated config is behaving as i want it to. is my assumption correct?

**Reply by hawkeye217** [reply]
Could you paste your 0.15 config file?

**Reply by italicize9610** [reply]
apologies, here you go. was away and without internet for a week. updated my config a bit, it's working fine but still has the same issue on beta 3. also signed up for frigate+ and added a new camera. but the same problem occurs.

```
go2rtc:
  streams:
    doorbell:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_main
    doorbell_sub:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_sub
    e1upstairs:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_main
    e1upstairs_sub:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_sub
    e1downstairs:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_main
    e1downstairs_sub:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_sub
    e1livingroom:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_main
    e1livingroom_sub:
      - ffmpeg:rtsp://admin:password@192.168.50.XXX/Preview_01_sub

model:
  path: plus://XXX

mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  user: XXX
  password: XXX

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
###### DOORBELL CAMERA ######
  doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.148,0.945,0.15,0.971,0.254,0.97,0.253,0.945
      threshold: 45
      contour_area: 10
    zones:
      door_front_alert:
        coordinates: 0.001,0.001,0.001,0.999,0.999,0.999,0.999,0.001
        loitering_time: 5
      door_front_detect:
        coordinates: 0.001,0.001,0.001,0.999,0.999,0.999,0.999,0.001
        loitering_time: 0
    review:
      alerts:
        required_zones: door_front_alert
      detections:
        required_zones: door_front_detect

  e1upstairs: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/e1upstairs
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/e1upstairs_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.145,0.954,0.146,0.985,0.252,0.985,0.253,0.953
    review:
      alerts:
        labels:
          - person

###### DOWNSTAIRS CAMERA ###### 
  e1downstairs: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/e1downstairs
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/e1downstairs_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.147,0.954,0.149,0.98,0.25,0.98,0.25,0.953
    review:
      alerts:
        labels:
          - person

###### LIVING ROOM CAMERA ###### 
  e1livingroom: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/e1livingroom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/e1livingroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask: 0.146,0.954,0.146,0.98,0.254,0.98,0.251,0.953
    review:
      alerts:
        labels:
          - person
record:
  enabled: true
  alerts:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10
objects:
  track:
    - person
    - dog
  filters:
    dog:
      min_score: 0.7
      threshold: 0.8
    person:
      min_score: 0.7
      threshold: 0.8

detect:
  enabled: true

snapshots:
  enabled: true
  retain:
    default: 7

version: 0.15-0
```
