### DISCUSSION TITLE
How to confirm that Frigate is using Ollama?

### DISCUSSION THREAD

**Discussion by rwlove** [blakeblackshear/frigate#15364] [Ask A Question] [answered]
I have Ollama running as well as Frigate. How can I confirm that Frigate is using Ollama?

I'm on Frigate 0.15.0-e76f4e9 and Ollama 0.4.7.

```
genai:
  enabled: true
  provider: ollama
  base_url: http://ollama.ai:11434
  model: llava:7b
```
