### DISCUSSION TITLE
Frigate live/record resolution not the highest

### DISCUSSION THREAD

**Discussion by raspman** [blakeblackshear/frigate#15360] [Config Support] [answered]
### Describe the problem you are having

version: 0.14version: 0.14
Hi, below is my frigate config.  It works great, except for whatever reason, it is causing both the live and record feeds to display at a lower level.  I have a Reolink CX 410 and Reolink Doorbell Cam.  When logging directly into each camera on a web browser (and also via the Reolink app) both cameras can display at the highest resolution, which is called "clear."  However, within Frigate, they are both playing/recording at the "balanced" level.  Reolinks have (3) different levels:  "Fluent," which is the lowest resolution, "Balanced," which is a mid-resolution and "Clear," which is the highest resolution.
I know both cameras are displaying/recording (within Frigate) at the "balanced" resolution, as I can match up how the time/date stamp appears on the screen .  For example, on the garage camera, the time/date stamp text size is different when displaying at the balanced and clear levels.  I can also match up how the video looks between watching the camera live directly through the cameras and the Frigate integration.
The question is, what change(s) do I need to make to the configuration to tell Frigate to play/record the "clear" feed?

### Version

version: 0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.xx.xx
  port: 1883
  user: xx
  password: xx
  topic_prefix: frigate

record:
  enabled: true
  retain:
    days: 12
    mode: all
  events:
    retain:
      default: 3

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-http-reolink

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    garage:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus
    frontdoor:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0,0.005,0.08,0.472,0.083,0.47,0
        - 0.279,0.02,0.945,0,0.933,0.36,0.285,0.223
    zones:
      garage_driveway:
        coordinates: 0.325,1,0.735,0.403,1,0.275,1,1
        loitering_time: 0
    objects:
      track:
        - person
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0,1,0,1,0.652,0,0.623
    objects:
      track:
        - person
version: 0.14
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
.
```

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

.

### Any other information that may be helpful

.
