### DISCUSSION TITLE
[Config Support]: number < max_number in function 'icvExtractPattern' with Ollama reindexing

### DISCUSSION THREAD

**Discussion by rwlove** [blakeblackshear/frigate#15362] [Config Support] [answered]
### Describe the problem you are having

I'm trying out an Ollama configuration and on my initial scan I'm getting the below assertion failures. Indexing hasn't completed so I'm not sure if this is a meaningful problem - I will report back after the scan has completed, but I figured I should report it to the community anyway.

### Version

0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  host: emqx.home.svc.cluster.local
  topic_prefix: frigate
  user: '{FRIGATE_MQTT_USERNAME}'
  password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  global_args: [-hide_banner, -loglevel, info]
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://e21115a1e2505f108de1baf746d5eb0c
  #path: plus://'{FRIGATE_PLUS_MODEL}'

auth:
  enabled: false

tls:
  enabled: false

logger:
  default: info

#logger:
#  logs:
#    frigate.record: debug

database:
  path: /config/frigate.db

genai:
  enabled: true
  provider: ollama
  base_url: http://ollama.ai:11434
  model: llava:7b

objects:
  track:
    - person
    - dog
    - car
    - deer
    - raccoon
    - fox
    - rabbit
    - face
    - license_plate
    - amazon
    - ups
    - fedex
    - package
    - waste_bin

record:
  enabled: true
  retain:
    days: 182
    mode: all
  alerts:
    retain:
      days: 365
  detections:
    retain:
      days: 365
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false

go2rtc:
  webrtc:
    candidates:
      - 10.10.40.102:1984
      - stun:1984
  streams:
    #backyard:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-backyard:554/cam/realmonitor?channel=1?subtype=1
    #backyard_substream:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-backyard:554/cam/realmonitor?channel=1?subtype=0
    pool:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-pool:554/cam/realmonitor?channel=1?subtype=0
    pool_substream:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-pool:554/cam/realmonitor?channel=1?subtype=1
    frontyard:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-frontyard:554/cam/realmonitor?channel=1?subtype=0
    frontyard_substream:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-frontyard:554/cam/realmonitor?channel=1?subtype=1
    garage:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-garage:554/cam/realmonitor?channel=1?subtype=0
    garage_substream:
      - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-garage:554/cam/realmonitor?channel=1?subtype=1
    #office:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-office:554/cam/realmonitor?channel=1?subtype=1
    #office_substream:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-office:554/cam/realmonitor?channel=1?subtype=0
    #turret:
    #  - rtsp://admin:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-turret:554/cam/realmonitor?channel=1?subtype=1
    #turret_substream:
    #  - rtsp://admin:{FRIGATE_AMCREST_RTSP_PASSWORD}@amcrest-turret:554/cam/realmonitor?channel=1?subtype=0
    #bookshelf:
    #  - rtsp://wyze:{FRIGATE_WYZECAM_RTSP_PASSWORD}@wyzecam-2/live
    #familyroom:
    #  - rtsp://wyze:{FRIGATE_WYZECAM_RTSP_PASSWORD}@wyzecam-1/live
    #kitchen:
    #  - rtsp://wyze:{FRIGATE_WYZECAM_RTSP_PASSWORD}@wyzecam-3/live
    #backyard2:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@loryta-backyard:554/cam/realmonitor?channel=1?subtype=1
    #backyard2_substream:
    #  - rtsp://user:{FRIGATE_AMCREST_RTSP_PASSWORD}@loryta-backyard:554/cam/realmonitor?channel=1?subtype=0
    frontdoor:
      # For HTTP: Need to have both RTMP and HTTP enabled under Settings->Network->Advanced->Server Settings
      #- ffmpeg:http://reolink-frontdoor/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password={FRIGATE_REOLINK_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
      - rtsp://user:{FRIGATE_REOLINK_RTSP_PASSWORD}@reolink-frontdoor:554/h264Preview_01_main
    frontdoor_substream:
      # For HTTP: Need to have both RTMP and HTTP enabled under Settings->Network->Advanced->Server Settings
      #- "ffmpeg:http://reolink-frontdoor/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password={FRIGATE_REOLINK_RTSP_PASSWORD}"
      - rtsp://user:{FRIGATE_REOLINK_RTSP_PASSWORD}@reolink-frontdoor:554/h264Preview_01_sub
    bush:
      # Need to have both RTMP and HTTP enabled under Settings->Network->Advanced->Server Settings
      #- ffmpeg:http://reolink-bush/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password={FRIGATE_REOLINK_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
      - rtsp://user:{FRIGATE_REOLINK_RTSP_PASSWORD}@reolink-bush:554/h264Preview_01_main
      #- ffmpeg:bush#video=h264#hardware
    bush_substream:
      # Need to have both RTMP and HTTP enabled under Settings->Network->Advanced->Server Settings
      #- ffmpeg:http://reolink-bush/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password={FRIGATE_REOLINK_RTSP_PASSWORD}
      - rtsp://user:{FRIGATE_REOLINK_RTSP_PASSWORD}@reolink-bush:554/h264Preview_01_sub
      #- ffmpeg:bush_sub#hardware
    backyard:
      - ffmpeg:rtsp://user:{FRIGATE_REOLINK_RTSP_PASSWORD}@reolink-backyard:554/h264Preview_01_main#video=h264#audio=copy#audio=opus
    backyard_substream:
      - rtsp://user:{FRIGATE_REOLINK_RTSP_PASSWORD}@reolink-backyard:554/h264Preview_01_sub
    deck:
      - rtsp://user:password123@loryta-deck:554/live
    deck_substream:
      - rtsp://user:password123@loryta-deck:554/cam/realmonitor?channel=1&subtype=1

cameras:
  reolink_frontdoor:
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 7
      width: 640
      height: 480
    zones:
      driveway:
        coordinates: 
          0.268,0.556,0.38,0.557,0.469,0.554,0.555,0.553,0.605,0.555,0.664,0.558,0.712,0.563,0.759,0.575,0.643,0.584,0.597,0.59,0.543,0.596,0.469,0.602,0.351,0.601,0.27,0.596
        inertia: 3
        objects:
          - car
          - deer
          - dog
          - person
        loitering_time: 0
      street:
        coordinates: 
          1,0.541,0.998,0.591,0.93,0.581,0.866,0.57,0.798,0.559,0.76,0.55,0.711,0.546,0.587,0.52,0.643,0.508,0.745,0.512,0.877,0.522
        inertia: 3
        objects:
          - car
          - deer
          - dog
          - person
        loitering_time: 0
      walkway:
        coordinates: 
          0.338,0.739,0.46,0.741,0.436,0.673,0.515,0.692,0.616,0.737,0.658,0.799,0.581,0.842,0.416,0.847,0.249,0.822,0.249,0.722
        inertia: 3
        objects:
          - deer
          - dog
          - person
          - package
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - walkway
          - driveway
      detections:
        required_zones: street
    snapshots:
      required_zones:
        - walkway
        - driveway
        - street
    #objects:
    #  filters:
    #    person:
    #      max_area: 35000
    #    dog:
    #      max_area: 35000
    live:
      stream_name: frontdoor

    motion:
      mask:
        - 0.646,0.132,0.66,0.183,0.809,0.41,0.898,0.487,0.953,0.502,1,0.49,1,0,0.695,0
        - 0.723,0.596,0.715,0.659,0.659,0.723,0.687,0.794,0.79,0.809,0.848,0.826,0.893,0.859,0.931,0.866,0.961,0.846,0.983,0.763,0.986,0.684,0.961,0.652,0.921,0.633,0.887,0.638,0.86,0.629,0.852,0.585
        - 0.642,0.865,0.684,0.766,0.719,0.764,0.78,0.817,0.807,0.804,0.893,0.831,0.92,0.899,0.945,1,0.653,1,0.616,0.913
        - 0,0.304,0.076,0.437,0.115,0.512,0.126,0.564,0.101,0.619,0.08,0.624,0.097,0.652,0.108,0.672,0.107,0.701,0.045,0.704,0.022,0.731,0,0.751
        - 0.296,0.189,0.284,0.329,0.277,0.431,0.277,0.466,0.315,0.479,0.398,0.469,0.451,0.481,0.503,0.484,0.562,0.481,0.651,0.477,0.751,0.476,0.841,0.488,0.82,0.448,0.809,0.375,0.724,0.234,0.692,0.153,0.718,0.072,0.323,0.072,0.311,0.18
  amcrest_frontyard:
    ui:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 10
      width: 704
      height: 480
    motion:
      mask:
        - 0.796,1,1,1,1,0.691,1,0.528,0.952,0.529,0.923,0.551,0.906,0.598,0.914,0.682,0.884,0.736,0.825,0.717,0.785,0.679,0.74,0.675,0.663,0.69,0.615,0.725,0.582,0.822,0.581,1,0.671,1
        - 0.873,0.172,0.876,0.223,0.889,0.244,0.89,0.271,0.907,0.272,0.906,0.249,0.92,0.237,0.915,0.189,0.898,0.163
        - 0.729,0.038,0.731,0.083,0.972,0.081,0.971,0.033
    zones:
      walkway:
        coordinates: 
          0.863,0.762,1,0.705,1,0.552,0.895,0.561,0.808,0.589,0.701,0.638,0.58,0.679,0.463,0.708,0.411,0.729,0.353,0.731,0.269,0.733,0.196,0.707,0.129,0.676,0,0.62,0,0.74,0.273,0.869,0.475,0.856,0.491,1,0.571,1,0.57,0.841,0.767,0.775
        objects:
          - person
          - dog
          - deer
        inertia: 3
      driveway:
        coordinates: 
          0.061,0.394,0.107,0.34,0.183,0.264,0.123,0.293,0.076,0.328,0.034,0.37,0,0.408,0.001,0.46
        objects:
          - person
          - car
          - deer
          - dog
        inertia: 3
        loitering_time: 0
      street:
        coordinates: 
          0.428,0.103,0.557,0.109,0.666,0.117,0.811,0.135,1,0.198,1,0.278,0.777,0.242,0.679,0.23,0.589,0.223,0.483,0.223,0.344,0.221,0.214,0.244,0,0.336,0,0.215,0.081,0.186,0.182,0.151,0.241,0.138,0.322,0.128
        objects:
          - person
          - car
          - deer
          - dog
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - walkway
          - driveway
      detections:
        required_zones: street
    snapshots:
      required_zones:
        - walkway
        - driveway
        - street
    #objects:
    #  filters:
    #    person: {}
    live:
      stream_name: frontyard

  amcrest_garage:
    ui:
      order: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 10
      width: 704
      height: 480
    live:
      stream_name: garage
    motion:
      mask:
        - 0.971,0.036,0.729,0.04,0.731,0.075,0.973,0.075
        - 0,0.312,0.344,0.154,0.581,0.037,0.731,0.037,0.823,0.034,0.815,0,0,0
    zones:
      driveway:
        coordinates: 
          0.039,0.865,0.185,0.705,0.331,0.579,0.348,0.551,0.345,0.53,0.331,0.519,0.303,0.513,0.235,0.51,0.457,0.348,0.512,0.339,0.504,0.366,0.509,0.382,0.559,0.397,0.639,0.407,0.761,0.413,0.904,0.421,0.998,0.43,0.997,0.554,0.95,0.56,0.915,0.576,0.874,0.601,0.841,0.639,0.804,0.703,0.778,0.779,0.747,0.882,0.72,1,0.074,1
        loitering_time: 0
        objects:
          - car
          - package
          - person
          - dog
      neighbors:
        coordinates: 
          0.189,0.227,0.319,0.169,0.445,0.107,0.578,0.042,0.717,0.04,0.719,0.113,0.675,0.13,0.665,0.156,0.632,0.191,0.6,0.214,0.563,0.215,0.536,0.212,0.488,0.199,0.449,0.236,0.34,0.263,0.293,0.325,0.155,0.405,0.001,0.508,0.003,0.313,0.112,0.263
        loitering_time: 0
        objects:
          - dog
          - person
      shed:
        coordinates: 
          0.394,0.254,0.412,0.321,0.408,0.376,0.515,0.371,0.55,0.306,0.592,0.256,0.565,0.178,0.489,0.173,0.432,0.21
        loitering_time: 0
        objects: person
      weather_station:
        coordinates: 0.839,0.135,0.788,0.132,0.766,0.037,0.826,0.036,0.891,0.033,0.908,0.127
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - driveway
          - neighbors
          - shed
          - weather_station

  amcrest_pool:
    ui:
      order: 4
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 5
      width: 640
      height: 480
    #objects:
    #  filters:
    #    person:
    #      threshold: 0.75
    zones:
      pool:
        coordinates: 
          0.842,1,1,1,1,0.392,0.869,0.367,0.748,0.358,0.606,0.35,0.502,0.327,0.402,0.317,0.208,0.306,0.116,0.306,0,0.281,0,0.51,0,1,0.194,1,0.309,1,0.416,1,0.558,1,0.672,1
        objects:
          - person
          - dog
        inertia: 3
      greenway:
        coordinates: 
          0.234,0.412,0.478,0.412,1,0.5,1,0.338,0.698,0.294,0.366,0.273,0.105,0.285,0.106,0.448
        objects:
          - person
          - car
          - deer
          - dog
        inertia: 3
    review:
      alerts:
        required_zones:
          - pool
          - greenway
    snapshots:
      required_zones:
        - pool
        - greenway
    live:
      stream_name: pool

    motion:
      mask: 0.699,0.036,0.7,0.084,0.973,0.089,0.973,0.038

  loryta_deck:
    ui:
      order: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/deck
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 7
      width: 704
      height: 480
    live:
      stream_name: deck

    motion:
      mask: 0,0.079,0,0,1,0,1,0.27,0.657,0.128,0.343,0.065,0.195,0.059
    zones:
      kitchen_door:
        coordinates: 0.023,0.156,0.062,0.139,0.065,0.321,0.078,0.368,0.032,0.392,0.023,0.343
        loitering_time: 0
      deck:
        coordinates: 
          0.107,0.593,0.27,0.516,0.243,0.433,0.331,0.392,0.34,0.369,0.341,0.267,0.154,0.183,0.064,0.213,0.065,0.146,0.02,0.155,0.02,0.332,0.023,0.4,0.035,0.541,0.092,0.513
        loitering_time: 0
      greenway:
        coordinates: 
          0.872,0.331,0.779,0.293,0.724,0.313,0.644,0.29,0.566,0.262,0.488,0.243,0.435,0.229,0.441,0.193,0.419,0.179,0.395,0.187,0.37,0.159,0.358,0.173,0.347,0.192,0.335,0.214,0.329,0.228,0.264,0.232,0.154,0.182,0.074,0.205,0.077,0.15,0.219,0.142,0.413,0.147,0.522,0.158,0.625,0.18,0.715,0.207,0.869,0.255,1,0.303,1,0.376
        loitering_time: 0
    review:
      alerts:
        required_zones: greenway

  reolink_bush:
    ui:
      order: 6
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bush
          input_args: preset-rtsp-restream
          #input_args: preset-http-reolink
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bush_substream
          input_args: preset-rtsp-restream
          #input_args: preset-http-reolink
          roles:
            - detect
    detect:
      fps: 7
      #width: 1280
      #height: 960
      width: 640
      height: 480
    zones:
      greenway:
        coordinates: 
          0.347,0.223,0.194,0.188,0.103,0.181,0.095,0.275,0.147,0.313,0.192,0.344,0.256,0.381,0.321,0.41,0.401,0.455,0.441,0.479,0.472,0.5,0.497,0.511,0.538,0.536,0.583,0.571,0.653,0.611,0.747,0.661,0.886,0.743,1,0.802,1,0.662,1,0.498,0.859,0.432,0.673,0.356,0.511,0.285
        inertia: 3
        objects:
          - car
          - deer
          - dog
          - person
      pool:
        coordinates: 0.239,0.387,0.083,0.244,0.002,0.236,0.002,0.348,0,0.565,0.231,0.512
        inertia: 3
        objects:
          - dog
          - person
      street:
        coordinates: 0.205,0.283,0.206,0.307,0.157,0.304,0.099,0.29,0.093,0.268,0.15,0.275
        inertia: 3
        objects:
          - car
          - deer
          - dog
          - person
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - greenway
          - pool
      detections: {}
    snapshots:
      required_zones:
        - greenway
        - pool
    #objects:
    #  filters:
    #    car: {}
    live:
      stream_name: bush
    motion:
      mask: 
        0,0.147,0.071,0.169,0.183,0.174,0.352,0.214,0.483,0.263,0.643,0.336,0.765,0.386,0.907,0.448,1,0.492,1,0,0,0

  reolink_backyard:
    ui:
      order: 7
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 7
      width: 1536
      height: 576
    review:
      detections:
        labels: []
      alerts:
        labels: []
    live:
      stream_name: backyard

version: 0.15-0
camera_groups:
  Front_Yard:
    order: 1
    icon: LuChevronUp
    cameras:
      - amcrest_frontyard
      - reolink_frontdoor
      - amcrest_garage
  Back_Yard:
    order: 2
    icon: LuChevronDown
    cameras:
      - amcrest_pool
      - reolink_backyard
      - reolink_bush
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### Relevant Frigate log output

```shell
2024-12-05 18:52:48.179135133  [ERROR:0@543.968] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-12-05 18:52:48.179147942  
2024-12-05 18:52:48.179159878  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
```
```


### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
running as a pod in a k8s cluster
```

### Object Detector

Coral
