### DISCUSSION TITLE
Frigate asks for login when accessing camera history via companion app on external network

### DISCUSSION THREAD

**Discussion by ArmandLinkens** [blakeblackshear/frigate#15375] [Ask A Question]
Hi all, hoping you can help me with an issue i'm unable to solve myself. 
When accessing camera footage history via frigate on my reolink doorbell, frigate asks for login, but only when i'm doing this via the companion app on android via an external network (both wifi and 4G). Strangely, when accessing frigate via my home assistant URL (which is the same as the external URL in the companion app) i'm able to view camera footage history. Additionally, when I try to login, i simply get routed back to the live view. 

Please see my config below and i'm happy to provide further info!

```
mqtt:
  host: 192.168.178.76       # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: SECRET             # YOUR MQTT USERNAME
  password: SECRET        # YOUT MQTT PASSWORD
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

database:
  path: /config/frigate.db

##########################################################################

go2rtc:
  streams:
    reolink:
      - ffmpeg:http://192.168.178.67/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=SECRET&password=SECRET#video=h264#width=1600#height=1200#audio=copy#audio=opus
      - rtsp://SECRET:SECRET@192.168.178.67:554/h264Preview_01_sub
    schuur:
      - rtsp://SECRET:SECRET@192.168.178.100:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
  webrtc:
    candidates:
      - 192.168.178.76:8555
      - 192.168.178.100:8555
      - stun:8555

##########################################################################

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      required_zones:
        - voortuin
    audio:
      enabled: false
      listen:
        - speech
    motion:
      mask:
        - 0.186,0.907,0.353,0.795,0.419,0.813,0.409,0.66,0.409,0.639,0.41,0.605,0.406,0.578,0.394,0.549,0.373,0.544,0.349,0.564,0.344,0.605,0.309,0.601,0.264,0.588,0.21,0.573,0.191,0.514,0.129,0.509,0.135,0.465,0.176,0.443,0.182,0.31,0.114,0.242,0,0.319,0,0.482,0,0.819,0.065,0.964
        - 1,0.613,1,0.52,1,0.416,1,0.13,0.892,0.133,0.874,0.19,0.912,0.237,0.9,0.287,0.911,0.352,0.886,0.449,0.858,0.482,0.845,0.537,0.859,0.597,0.864,0.625,0.896,0.642,0.945,0.627
        - 0.027,0.326,0.017,0.016,0.993,0.029,1,0.319,0.887,0.353,0.833,0.358,0.769,0.409,0.729,0.408,0.698,0.305,0.637,0.262,0.585,0.293,0.488,0.326,0.396,0.328,0.356,0.282,0.32,0.331,0.253,0.32,0.185,0.379,0.083,0.328
    zones:
      voortuin:
        coordinates: 1,1,1,0.742,0.949,0.78,0.606,0.846,0.611,0.837,0.343,0.808,0.195,0.913,0.066,1
        inertia: 3
        loitering_time: 0
      straat:
        coordinates: 1150,936,1345,912,1504,882,1600,837,1600,528,531,540,0,529,336,823,802,936
    objects:
      filters:
        person:
          mask:
            - 1529,547,1405,552,1374,592,1379,636,1386,746,1491,743,1564,733,1576,653
            - 1600,203,1515,99,1441,107,1433,194,1439,418,1463,434,1548,497,1600,404
            - 653,666,606,651,547,668,567,965,666,984
            - 936,972,958,971,972,741,950,745
            - 717,950,709,721,741,735,746,963
    review:
      alerts:
        required_zones: voortuin
      detections:
        required_zones: voortuin
  schuur:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://SECRET:SECRET@192.168.178.100:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      width: 1280 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
    onvif:
      host: 192.168.178.100
      port: 80
      user: SECRET
      password: SECRET
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.3
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - achter
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: pui
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
        # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
        movement_weights: 0.0, 1.0, 4.8007683753967285, 5.759384140404324, -0.30440398954576076
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
    motion:
      mask:
        - 0.968,0,0.963,0.103,0.678,0.09,0.676,0
        - 0.683,0.958,0.644,0.924,0.711,0.238,0.778,0.283
    zones:
      achter:
        coordinates: 0.131,0.134,0.82,0.15,0.847,0.899,0.165,0.875
        inertia: 3
        loitering_time: 0
logger:
  logs:
    frigate.ptz.autotrack: debug
    frigate.ptz.onvif: debug
version: 0.14
```
