### DISCUSSION TITLE
[Config support] Detection work - no Snaphots shown in Gui

### DISCUSSION THREAD

**Discussion by BigChris** [blakeblackshear/frigate#15379] [Ask A Question]
Hello, I am trying to create and display snapshots. The detection works, the snapshots are saved under .../clips. 
However, the images are not displayed in the interface. I assume that I have to activate record additionally, but I am not sure how to do this.
Thank you very much for your help!

```
cameras:
  Haustuer: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:%paranoid23!@10.10.10.18:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
    objects:
      track:
      - person
      - cat
      - dog
    snapshots:
      enabled: true
      timestamp: true
      retain:
        default: 31

```
