### DISCUSSION TITLE
Frigate container taking 100% resources periodically

### DISCUSSION THREAD

**Discussion by Mister-A** [blakeblackshear/frigate#15371] [Ask A Question]
Looking for some guidance in trouble shooting the following problem please.

I've run Frigate in an LXC within Proxmox for a couple of years.

When I was running Frigate 0.12.x in this setup with intel Mac mini hardware as my proxmox node all was well.

Recently I upgraded my setup as I was running out of resources as I added more cameras and added a 13th gen i5 NUC as a proxmox node and moved the Frigate container there, leaving the existing mac node for HA and PiHole.

At the same time I upgraded Frigate to 0.14.1

Since then, perhaps weekly, sometimes every couple of days, I notice the fan of the NUC maxed and Frigate becomes unresponsive, proxmox shows the Frigate container is using 99-100% of the 8GB RAM, 99-100% of the 4GB swap and 98+% of the allocated 4 CPUs.

Console won't respond so I can't check what process is using the resources, the only option is to force a reboot of the container.

It's not a progressive leak, it's quite sudden:
![image](https://github.com/user-attachments/assets/debfd744-898a-4fe0-a565-079b97a1cf00)

CPU spike comes out of no where:
![image](https://github.com/user-attachments/assets/1349788d-15ab-4fdc-b66e-c28ab5763368)

Any one had similar experiances or can suggest how to pin down the cause?

Thanks

**Comment by NickM-27** [comment]
not much help that can be provided without seeing configs.

**Reply by Mister-A** [reply]
Thanks for responding Nick, initial description was just in case someone instantly knew the issue.

My frigate config is as follows

```
mqtt:
  host: 192.168.1.10
  user: ******
  password: ******
detectors:
  coral:
    type: edgetpu
    device: usb
model:
  path: plus://******
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      mode: active_objects
      default: 45
snapshots:
  enabled: true
  retain:
    default: 45
    mode: active_objects
birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720
objects:
  track:
    - person
    - car
    - motorcycle
    - bus
    - dog
    - cat
    - face
    - package
    - amazon
    - fedex
    - ups
    - fox
    - bird
  filters:
    person:
      min_score: 0.80
      threshold: 0.82
    car:
      min_score: 0.76
      threshold: 0.80
    cat:
      min_score: 0.75
      threshold: 0.8
    dog:
      min_score: 0.75
      threshold: 0.8
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  input_args: -rtsp_transport tcp
go2rtc:
  streams:
    front_wide:
      - rtsp://******:******@10.0.0.71:554/1/1#hardware
      - ffmpeg:front_wide#audio=aac
    front_door:
      - rtsp://******:******@192.168.1.61:554/stream1#hardware
      - ffmpeg:front_door#audio=aac
    front_door2:
      - rtsp://******:******@10.0.0.67:554/1/1#hardware
      - ffmpeg:front_door2#audio=aac
    garden_wide:
      - rtsp://******:******@10.0.0.70:554/Preview_01_main#hardware
      - ffmpeg:garden_wide#audio=aac
    chickens:
      - rtsp://******:******@192.168.1.83:554/Preview_01_main#hardware
      - ffmpeg:chickens#audio=aac
    garden:
      - rtsp://******:******@192.168.1.60:10554/tcp/av0_1#hardware
      - ffmpeg:garden#audio=aac
    cat_cam:
      - rtsp://******:******@192.168.1.86:554/stream1#hardware
      - ffmpeg:cat_cam#audio=aac
cameras:
  front_wide:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@10.0.0.71:554/1/1
          roles:
            - record
            - detect
    ui:
      order: 20
    birdseye:
      order: 20
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 1280,0,1280,465,1110,385,893,426,820,422,930,309,1033,236,1006,132,865,107,746,110,688,130,618,235,555,252,422,229,360,221,323,208,35,183,0,169,0,60,0,0
        - 39,720,669,720,721,677,758,640,796,594,823,565,854,534,848,496,834,479,815,418,791,407,750,409,725,394,701,378,683,324,578,276,74,203,160,358,53,401,0,481,0,596,0,661
      threshold: 35
      contour_area: 15
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 995,285,911,256,832,243,766,241,638,251,577,288,688,414,821,421
    objects:
      filters:
        car:
          mask: 
            0.211,0.279,0.38,0.282,0.479,0.24,0.521,0.193,0.583,0.157,0.748,0.211,1,0.319,1,0,0.722,0,0,0,0,0.217
  front_door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@192.168.1.61:554/stream1
          roles:
            - record
            - detect
    ui:
      order: 1
    birdseye:
      order: 1
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 1220,0,0,0,0,38,564,69,696,615,769,680,879,684,1170,510
  front_door2:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@10.0.0.67:554/1/1
          roles:
            - record
            - detect
    ui:
      order: 10
    birdseye:
      order: 10
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 640,0,0,0,0,21,161,21,365,21,439,100,464,294,640,360
  garden_wide:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@10.0.0.70:554/Preview_01_main
          roles:
            - record
            - detect
    ui:
      order: 30
    birdseye:
      order: 30
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 0,0,1280,0,1280,720,1061,720,966,439,941,334,892,309,862,497,744,504,583,464,584,398,600,220,515,233,521,350,433,442,0,665
    objects:
      track:
        - person
        - dog
        - cat
        - face
        - package
        - fox
      filters:
        person:
          mask:
            - 0,0,1280,0,1280,720,1061,720,966,439,941,334,892,309,836,472,744,504,583,464,584,398,602,219,527,220,473,311,443,434,0,625
  chickens:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@192.168.1.83:554/Preview_01_main
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - face
        - fox
        - bird
    ui:
      order: 50
    birdseye:
      order: 50
  cat_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@192.168.1.86:554/stream1
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
    ui:
      order: 60
    birdseye:
      order: 60
  garden:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://******:******@192.168.1.60:10554/tcp/av0_1
          roles:
            - record
            - detect
    ui:
      order: 40
    birdseye:
      order: 40
    detect:
      width: 1152
      height: 648
    motion:
      mask:
        - 0,0,177,0,845,0,1152,0,1152,339,266,329,0,257
version: 0.14
camera_groups:
  Outside:
    order: 1
    icon: LuCamera
    cameras:
      - chickens
      - front_door2
      - front_wide
      - garden_wide
```

Docker:

`docker run --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 -d --name frigate --privileged --restart=always --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/dri --device /dev/bus/usb:/dev/bus/usb --shm-size=256m -v /storage/media:/media/frigate -v /storage/config:/config -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='****' -e PLUS_API_KEY='****' -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp ghcr.io/blakeblackshear/frigate:stable`
