### DISCUSSION TITLE
Recording playback fails

### DISCUSSION THREAD

**Discussion by raspman** [blakeblackshear/frigate#15388] [General Support]
### Describe the problem you are having
(This should have been posted in issues - not sure if you can move it?)

I have 2 cameras recording, the Reolink Wifi Doorbell cam and the CX410.  I was reviewing recordings earlier today on both cameras noticed that a few hours of video was missing for the Doorbell cam. 

As I slid the red button on the right of the screen, I could see the video was captured as it was playing in fast motion.  However, when I released the button to have the video play at the normal speed, either the screen would be black or the circle would be spinning in the middle of the screen.  I then looked at the same time frame on the other camera and it played back perfectly.  I also (temporarily) have a Raspberry Pi 4 recording the same cameras on the same 0.14.0 version and playback during the same time frame was fine on both cameras (although the config is different.)

After I restarted HA and Frigate,  recording on both cameras has been fine.  Live play on both cameras is excellent. Not sure what caused this?

### Version

0.14.0

### What browser(s) are you using?

Chrome, Firefox and HA App 

### Frigate config file

```yaml
mqtt:
  host: 
  port: 1883
  user: 
  password: 
  topic_prefix: frigate

record:
  enabled: true
  retain:
    days: 12
    mode: all
  events:
    retain:
      default: 3

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-http-reolink

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    garage:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus
    frontdoor:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0,0.005,0.08,0.472,0.083,0.47,0
        - 0.279,0.02,0.945,0,0.933,0.36,0.285,0.223
    zones:
      garage_driveway:
        coordinates: 0.325,1,0.735,0.403,1,0.275,1,1
        loitering_time: 0
    objects:
      track:
        - person
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0,1,0,1,0.652,0,0.623
    objects:
      track:
        - person
version: 0.14
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
.
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Wifi Doorbell 

### Screenshots of the Frigate UI's System metrics pages

.

### Any other information that may be helpful

.
