### DISCUSSION TITLE
[Bug]: Possible camera name collision if names only differ by a number at the end resulting in "Unable to read frames from ffmpeg proceess"

### DISCUSSION THREAD

**Discussion by SonarClouds** [blakeblackshear/frigate#15380] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After the upgrade from frigate 0.13.2 to 0.15.0-beta2 I notiched "Unable to read frames from ffmpeg proceess." after some trial and error I could narrow it down to the naming of the cameras.
"cam_carport" & "cam_carport2" lead to "Unable to read frames from ffmpeg proceess." for the camera "cam_carport".
Changing the name solves this issue i.e. "cam_carport_inside" & "cam_carport_outside"

Go2RTC works fine => Cameras can be opend via vlc using the Go2RTC provided streams

The bug does not occure if the cameras are named cam_carport1 & cam_carport2, only when they are named "cam_carport" & "cam_carport2"!

### Steps to reproduce

1. Setup frigate config similar to one supplied with two cameras named similar but one ending with a number i.e. 2
2. Start frigate
3. Look at the log which reports "Unable to read frames from ffmpeg proceess " for the first camera entry with no number

### Version

0.15.0-beta2

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO

model:
  path: xxxx


logger:
  default: warning

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.75

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-rtsp-restream


ui: {}
birdseye:
  enabled: true
  restream: true
  width: 2560
  height: 1440
  mode: continuous
  layout:
    scaling_factor: 3.0

go2rtc:
  streams:
    cam_carport_rec:
      - rtsp://user:password@aaa:554/h264Preview_01_main
    cam_carport2_rec:
      - rtsp://user:password@bbb:554/h264Preview_01_main
    cam_entrance_rec:
      - rtsp://user:password@ccc:554/h264Preview_01_main

cameras:
  cam_carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_carport_rec?video=copy&audio=copy
          roles:
            - record
            - detect

  cam_carport2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_carport2_rec?video=copy&audio=copy
          roles:
            - record
            - detect

  cam_entrance:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_entrance_rec?video=copy&audio=copy
          roles:
            - record
            - detect
```

### docker-compose file or Docker CLI command

```yaml
No relevance for this bug. Tested with custom and Reference from https://docs.frigate.video/frigate/installation/
```

### Relevant Frigate log output

```shell
2024-12-06 16:47:44.061125237  [2024-12-06 16:47:44] frigate.video                  ERROR   : cam_carport: Unable to read frames from ffmpeg process.
2024-12-06 16:47:44.061127787  [2024-12-06 16:47:44] frigate.video                  ERROR   : cam_carport: Unable to read frames from ffmpeg process.
....
```

### Relevant go2rtc log output

```shell
No errors in go2rtc log.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-520A & 810A

### Screenshots of the Frigate UI's System metrics pages

Not necessary for reproduction.
