### DISCUSSION TITLE
Low quality recording and live

### DISCUSSION THREAD

**Discussion by array81** [blakeblackshear/frigate#15386] [Ask A Question]
I use Frigate with Google Coral and 4 IMOU cameras. I set the URLs to pass the high definition stream for recording and the low resolution stream for detection. The problem is that the recording and even the live broadcast always happen in low resolution although the URL of the high resolution stream is correct. This is my setup:

```
mqtt:
  enabled: true
  host: 192.168.XXX.XXX
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: myuser
  password: mypass
cameras:
  Taverna:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
    objects:
      track:
        - person
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Soggiorno:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
    objects:
      track:
        - person
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Mansarda:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
    objects:
      track:
        - person
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Giardino:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
        - path: rtsp://admin:pass@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
    objects:
      track:
        - person
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
```
