### DISCUSSION TITLE
MQTT "Unable to publish to Road/audio/dBFS: client is not connected" error

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#15382] [Ask A Question] [answered]
I keep getting this error on one camera, "Unable to publish to Road/audio/dBFS: client is not connected" always pointing to Road/audio/**xyz**  (not only dBFS)
All else from this camera is working OK.
Which client is the error referring to? The MQTT server or the Road camera?
As far as I can tell my mosquitto server is running OK
![frigate](https://github.com/user-attachments/assets/a5057303-a875-4b2a-a35e-58b53d6df28b)

**Comment by NickM-27** [comment]
it is referring to MQTT, what is your config

**Comment by 18923** [comment]
```yaml
# Dec 6-2024

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.0.200
  port: 1883
  # topic_prefix: frigate100

logger:
  default: info
  logs:
    frigate.comms.mqtt: debug

model:
  labelmap:
    0: person
    1: bicycle
    2: car
    3: bicycle # motorcycle
    5: car # bus
    7: car # truck
    15: bird
    16: cat
    17: dog
    18: animal # horse
    19: animal # sheep
    20: animal # cow
    22: animal # bear

go2rtc:
  streams:
    Road:
      rtsp://admin:password@192.168.0.222:8554/profile0
    Road_Sub:
      rtsp://admin:password@192.168.0.222:8554/profile1

    Old_Driveway: 
      rtsp://192.168.0.187:554/user=admin_password=password_channel=0_stream=1.sdp?real_stream
      # rtsp://192.168.0.187:554/user=admin_password=1kNMar5n_channel=0_stream=0.sdp?real_stream
    Old_Driveway_Sub: 
      rtsp://192.168.0.187:554/user=admin_password=password_channel=0_stream=1.sdp?real_stream

    Front:
      rtsp://admin:password@192.168.0.171:554/cam/realmonitor?channel=1&subtype=0
    Front_Sub:
      rtsp://admin:password@192.168.0.171:554/cam/realmonitor?channel=1&subtype=1

    Firepit:
      rtsp://admin:password@192.168.0.246:554/Streaming/channels/101
    Firepit_Sub:
      rtsp://admin:password@192.168.0.246:554/Streaming/channels/102

    Shed:
      rtsp://192.168.0.226:554/1
    Shed_Sub:
      rtsp://192.168.0.226:554/2

    IPC_Cam:
      rtsp://192.168.0.223:554/live/main
    IPC_Cam_Sub:
      rtsp://192.168.0.223:554/live/sub

    Island:
      rtsp://admin:password@192.168.0.245:554/Streaming/channels/101
    Island_Sub:
      rtsp://admin:password@192.168.0.245:554/Streaming/channels/102

# ffmpeg:
#   hwaccel_args: preset-vaapi
# record: # Only enable as needed
#   sync_recordings: True # Only enable as needed

cameras:
############# Road Camera ################
  Road:
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Road_Sub?video&audio=all
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/Road
          roles:
            - record
    audio:
      enabled: true
      min_volume: 15 # Change if necessary
      listen:
        - howl
        - car_alarm
        - reversing_beeps
        - train_whistle
        - bark
        - laughter
        - scream
        - speech
        - yell
        - singing
        - owl
        - music
        - rain
        - honk
        - slam
        - gunshot
        - explosion    
        
    detect:
      width: 640 #640
      height: 360 #360
      fps: 5
      # stationary:
      #    interval: 1
      #    threshold: 20
      #    max_frames:
      #     objects:
      #       car: 100
      #       person: 100
    objects:
      track: # add more object types under this if you want
        - car
        - bus
        - person
        - animal
        - bicycle
        - bird
        # - motorcycle
      filters:
        car: # added threshold and areas March 17 2023
          threshold: 0.6
        #   min_area: 5000
        #   max_area: 100000
        animal: {}
        bicycle: {}
        person:
          threshold: 0.6
          # min_area: 500
      mask: 0.308,0.426,0.341,0.45,0.219,0.985,0.122,0.989
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      improve_contrast: true
      # threshold: 15   # Nov 11-2022 Fernando increase motion sensitivity
      mask:
        - 1,0.768,1,0,0.528,0,0,0,0,0.417,0.065,0.416,0.121,0.338,0.406,0.346,0.461,0.441
        - 0.039,1,0.266,1,0.296,0.845,0.163,0.797
      threshold: 50
      contour_area: 16
    record:
      enabled: true
      retain:
        days: 4
        mode: motion
    zones:
      Road_Driveway:
        coordinates: 0.089,0.384,0.195,0.404,0.319,0.399,0.303,0.459,0.09,0.439
        loitering_time: 0
        inertia: 3
        objects:
          - car
          - person
    review:
      alerts:
        required_zones: Road_Driveway

############# Front Camera ################
  Front:
    ui:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi

      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Sub
          roles:
            - detect # only if you want object detection
            # - audio
        - path: rtsp://127.0.0.1:8554/Front
          roles:
            - record
            - audio
    audio:
      enabled: false
      min_volume: 15 # Change if necessary
      listen:
        - howl
        - car
        - car_alarm
        - reversing_beeps
        - train_whistle
        - bark
        - babbling
        - laughter
        - fire_alarm
        - scream
        - speech
        - yell
        - whoop
        - singing
        - footsteps
        - owl
        - music
        - rain
        - wind
        - car
        - honk
        - motorcycle
        - aircraft
        - slam
        - squeak
        - gunshot
        - explosion            
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    objects:
      track: # add more object types under this if you want
        - person # only if you want to detect persons
        - car
        - animal
        - dog
        - bird
      filters:
        person:
          threshold: .6
          mask: 0.985,0.125,0.866,0.117,0.851,0.297,0.971,0.323
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      improve_contrast: true
      mask: 1,0,1,0.099,0.794,0.101,0.757,0.068,0.544,0.033,0.541,0
      threshold: 56
      contour_area: 30
    record:
      enabled: true
      retain:
        days: 4
        mode: motion

      alerts:
        retain:
          days: 4
      detections:
        retain:
          days: 4
    zones:
      Front_Walkway:
        coordinates: 0.523,0.112,0.381,0.355,0.451,0.993,0.728,0.989,0.528,0.344,0.605,0.118
        loitering_time: 0
        objects:
          - person
          - animal
          - dog
      Front_Driveway:
        coordinates: 0.276,0,0.541,0.023,0.797,0.055,0.8,0.15,0.141,0.139
        loitering_time: 0
        objects:
          - car
          - person
############# Firepit Camera ################
  Firepit:
    ui:
      order: 4
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Firepit_Sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Firepit
          roles:
            - record

    detect:
      width: 640 #352
      height: 360 #240
      fps: 5
    objects:
      track:
        - person
        - animal
        - car
        - bird
      filters:
        car: {}
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      improve_contrast: true
      mask: 0,0,0,0.206,0.349,0.153,0.705,0.166,0.985,0.33,1,0
      threshold: 45
      contour_area: 35
    record:
      enabled: true
      alerts:
        retain:
          days: 4
      detections:
        retain:
          days: 4
  Shed:
    ui:
      order: 5
    ffmpeg:
      hwaccel_args: preset-vaapi
      # Next line added to eliminate "timeout" to camera connection, default 10000000
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 12000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://127.0.0.1:8554/Shed
          roles:
            - detect
            - record
    detect:
      width: 1920 #640
      height: 1080 #480 #352
      fps: 5
      stationary:
        interval: 50
        threshold: 50
        max_frames:
          objects:
            # car: 100
            person: 100

    objects:
      track:
        - person
        - animal
        - dog
        - car
        - bird
      filters:
        person:
          threshold: 0.6
          min_area: 800
          # max_area: 100000
        car:
          mask: 0.472,0.124,0.549,0.136,0.556,0.198,0.487,0.211
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      improve_contrast: true
      mask: 0,0.108,0.172,0.164,0.382,0.211,0.654,0.196,1,0.264,1,0,0,0
      threshold: 45
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 4
        mode: motion
      alerts:
        retain:
          days: 4
      detections:
        retain:
          days: 4

 ###########################################################         
  IPC_Cam:
    ui:
      order: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi

      inputs:
        - path: rtsp://127.0.0.1:8554/IPC_Cam_Sub
          roles:
            - detect # only if you want object detection
            - audio
        - path: rtsp://127.0.0.1:8554/IPC_Cam_Main
          roles:
            - record
            # - audio
    audio:
      enabled: false
      min_volume: 15 # Change if necessary
      listen:
        - howl
        - car
        - car_alarm
        - reversing_beeps
        - train_whistle
        - bark
        - babbling
        - laughter
        - fire_alarm
        - scream
        - speech
        - yell
        - whoop
        - singing
        - footsteps
        - owl
        - music
        - rain
        - wind
        - car
        - honk
        - motorcycle
        - aircraft
        - slam
        - squeak
        - gunshot
        - explosion
    detect:
      width: 640
      height: 480   #480
      fps: 5
    objects:
      track: # add more object types under this if you want
        - person # only if you want to detect persons
        - animal
        - car
        - dog
        - bird
      filters:
        car:
          mask: 0.344,0.322,0.343,0.16,0.509,0.175,0.511,0.303
        person:
          mask: 0.538,0.234,0.595,0.239,0.601,0.324,0.538,0.324
           # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    motion:
      improve_contrast: true
      mask:
        - 0,44,347,62,640,67,640,0,0,0
      threshold: 36
      contour_area: 20
    record:
      enabled: true
        # events:
      retain:
        days: 4
        mode: motion

############# Island Camera ################
  Island:
    ui:
      order: 9
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        # - path: rtsp://mika:password@192.168.0.246:554/Streaming/Channels/2
        - path: rtsp://127.0.0.1:8554/Island_Sub
          roles:
            - detect # only if you want object detection
            #- clips # only if you want to record video and stills
        # - path: rtsp://mika:password@192.168.0.246:554/Streaming/Channels/1
        - path: rtsp://127.0.0.1:8554/Island

          roles:
            - record

    detect:
      width: 640 #352
      height: 360 #240
      fps: 5
    objects:
      track: # add more object types under this if you want
        - person # only if you want to detect persons
        - animal
        - car
        - bird
      filters:
        car: {}
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      improve_contrast: true
      mask: 0,0,0,0.136,0.348,0.126,0.7,0.191,1,0.31,1,0
      threshold: 45
      contour_area: 35
    record:
      enabled: true
      alerts:
        retain:
          days: 4
      detections:
        retain:
          days: 4


############# Old Driveway Camera ################
  Old_Driveway:
    ui:
      order: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Old_Driveway_Sub  #?video&audio=all
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/Old_Driveway  #?video&audio=all
          roles:
            - record
    audio:
      enabled: false
      min_volume: 15 # Change if necessary
      listen:
        - howl
        - car
        - car_alarm
        - reversing_beeps
        - train_whistle
        - bark
        - babbling
        - laughter
        - fire_alarm
        - scream
        - speech
        - yell
        - whoop
        - singing
        - footsteps
        - owl
        - music
        - rain
        - wind
        - car
        - honk
        - motorcycle
        - aircraft
        - slam
        - squeak
        - gunshot
        - explosion
        
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - animal
        - car
        - dog
        - bird
      filters:
        person:
          mask:
            - 463,161,60,0,640,0,640,173
      # mask:
        # - 705,565,716,319,318,156,0,191,0,568        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      improve_contrast: true
      mask:
        - 638,2,68,0,0,0,0,55,275,121,402,150,448,157,525,171,640,197
    # zones:
    #   zone_0:
    #     coordinates: 0,0,0,159,640,176,640,0,299,0
        # objects:
        #   person:
        #   animal:  
      # objects:
      #   filters:
      #     animal:
      #       mask:
      #     car:
      #       mask:
      #         - 0,160,640,125,640,0,0,0
      threshold: 35
      contour_area: 25
    record:
      enabled: true
        # events:
      retain:
        days: 5
        mode: motion

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest default 8. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
version: 0.15-0
camera_groups: {}
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```
