### DISCUSSION TITLE
MP4s not deleting when age is greater than "retain" days

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#15381] [Ask A Question] [answered]
Hey,

I've set all my cameras to retain recordings for 7 days. However, it would appear that files aren't being deleted automatically after their age is 7 days +. I wanted to ask if what I'm describing is a bug or as intended? Also if there is a way via Frigate to auto delete files that are beyond the defined retain amount?

Many Thanks

**Comment by NickM-27** [comment]
We need to see your config

**Reply by Lockie85** [reply]
```
mqtt:
  enabled: true
  host: <MQTT_HOST>
  port: 1883
  user: <MQTT_USER>
  password: <MQTT_PASSWORD>
  topic_prefix: frigate

logger:
  # Optional: default log level (default: shown below). Available log levels are: debug, info, warning, error, critical
  default: info

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    driveway_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/stream1
      - ffmpeg:driveway_stream#audio=aac
    living_room_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/stream1
      - ffmpeg:living_room_stream#audio=aac
    cat_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/stream1
      - ffmpeg:cat_stream#audio=aac
    kitten_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/stream1
      - ffmpeg:kitten_stream#audio=aac
    baby_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/stream1
      - ffmpeg:baby_stream#audio=aac
    kitchen_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/Preview_01_main
      - ffmpeg:kitchen_stream#audio=aac
    front_stream:
      - rtsp://<USERNAME>:<PASSWORD>@<CAMERA_IP>/Preview_01_main
      - ffmpeg:front_stream#audio=aac

cameras:
  living_room_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_stream
          roles:
            - record
          input_args: preset-rtsp-generic
    record:
      enabled: true
      retain:
        days: 3
        mode: all
    detect:
      enabled: false  # This disables detection for this camera
    motion:
      mask: 0,0,0.32,0,0.32,0.054,0,0.056
  cat_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/cat_stream
          roles:
            - detect
            - record
          input_args: preset-rtsp-generic
    motion:
      mask: 0,0.056,0.324,0.056,0.324,0,0,0
    objects:
      track:
        - cat
        - mouse
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
    zones:
      zone_eating:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
        objects: cat
  kitten_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/kitten_stream
          roles:
            - detect
            - record
          input_args: preset-rtsp-generic
    motion:
      mask: 0,0.056,0.324,0.056,0.324,0,0,0
    objects:
      track:
        - cat
        - mouse
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
    zones:
      zone_eating:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
        objects: cat
  baby_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/baby_stream
          roles:
            - detect
            - record
          input_args: preset-rtsp-generic
    detect:
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
    motion:
      mask: 0,0.056,0.318,0.053,0.319,0,0,0
    objects:
      track:
        - cat
        - mouse
  driveway_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_stream
          roles:
            - record
            - detect
          input_args: preset-rtsp-generic
    motion:
      mask: 0,0.056,0.322,0.053,0.32,0,0,0
    objects:
      track:
        - person
        - cat
    detect:
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
      events:
        retain:
          default: 7
          mode: all
  kitchen_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_stream
          roles:
            - record
            - detect
          input_args: preset-rtsp-generic
    motion:
      mask: 0,0,0.002,0.049,0.299,0.048,0.3,0
    objects:
      track:
        - cat
        - person
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: all
    zones:
      worktop:
        coordinates: 
          0,0,0.888,0,0.886,0.281,0.624,0.232,0.406,0.243,0.159,0.575,0.163,0.674,0.319,0.725,0.493,0.766,0.699,0.799,0.853,0.815,1,0.799,1,1,0,1
        loitering_time: 0
        objects: cat
        inertia: 3
    review:
      alerts:
        required_zones: worktop
  front_stream:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_stream
          roles:
            - record
            - detect
          input_args: preset-rtsp-generic
    motion:
      mask: 0,0,0.002,0.049,0.299,0.048,0.3,0
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: all
version: 0.14
camera_groups:
  Cats:
    order: 1
    icon: LuCat
    cameras:
      - cat_stream
      - kitten_stream

```
