### DISCUSSION TITLE
[Detector Support]: Frigate+ model falsely detects cars in many occasions

### DISCUSSION THREAD

**Discussion by mike2307** [blakeblackshear/frigate#15383] [Detector Support]
### Describe the problem you are having

Hi,

first of all thank you for the great work. I'm a frigate user for almost 2 years now and it's great!

Since about 1.5 weeks I'm also a subscriber to frigate+. But here I encountered quite some issues...
At one of my two locations the cameras are located outside in the wild with a surrounding forest. I was really looking forward for deer, rabbit, squirrel, etc. detections.

But what I have at the moment can be best described as some kind of "car mania". The model sees cars in almost anything (like tree branches, cabins, ...).
In total I submitted 781 images in this short time frame (yes, I've spend a LOT of time on it). Out of these images there are 422 (!) false positives on cars!

In between my submissions I requested new models. Now I'm at 4 and it's only sightly getting better. I feel like I'll be ending up consuming all of my 12 requests/year in just a few weeks.

Who can help me out here?
I would like to add more annotated images but I feel like I'll be running out of model requests soon.
I could also share my registered mail address for the account if that helps (it's different to the one on github).

Thanks a lot in advance.

(this is a copy of my original post here https://github.com/blakeblackshear/frigate/discussions/14762#discussioncomment-11488283)

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: false

birdseye:
  enabled: true
  restream: false
  mode: continuous
  width: 1280
  height: 720
  layout:
    scaling_factor: 2.0

ui:
  live_mode: mse
  timezone: Europe/Vienna
  date_style: medium

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  coral_pci0:
    type: edgetpu
    device: pci:0
  coral_pci1:
    type: edgetpu
    device: pci:1

model:
  path: plus://XXXXXXXX

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5

record:
  enabled: true
  retain:
    days: 21
    mode: all
  export:
    # fits 1 hour into 1 minute (1/60), 15 FPS
    timelapse_args: -vf setpts=PTS/60 -r 15 -qp 36
  events:
    retain:
      default: 100
      mode: active_objects
  sync_recordings: true

snapshots:
  enabled: true
  quality: 90
  clean_copy: true
  retain:
    default: 1000

go2rtc:
  streams:
    Bach_HQ:
    - rtsp://admin:XXXXXXXX@10.42.0.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Bach_LQ:
    - ffmpeg:Bach_HQ#video=h264#width=960#audio=copy#hardware=vaapi#raw=-r 15 -qp
      32
    - ffmpeg:Bach_LQ#audio=opus # for WebRTC
    Werkzeughuette_HQ:
    - rtsp://admin:XXXXXXXX@10.42.0.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Werkzeughuette_LQ:
    - ffmpeg:Werkzeughuette_HQ#video=h264#width=960#audio=copy#hardware=vaapi#raw=-r
      15 -qp 32
    - ffmpeg:Werkzeughuette_LQ#audio=opus # for WebRTC
    Garage_HQ:
    - rtsp://admin:XXXXXXXX@10.42.0.5:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Garage_LQ:
    - ffmpeg:Garage_HQ#video=h264#width=960#audio=copy#hardware=vaapi#raw=-r 15 -qp
      32
    - ffmpeg:Garage_LQaudio=opus # for WebRTC
  log:
    streams: debug
    exec: debug
    ffmpeg: warn

cameras:
  Bach:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Bach_HQ
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    ui:
      order: 0
    birdseye:
      order: 0
    live:
      stream_name: Bach_LQ
    motion:
      mask:
      - 1920,704,1320,534,1092,497,846,480,705,464,702,320,1011,318,1301,293,1443,247,1920,198,1920,0,0,0,0,1080,1920,1080

  Werkzeughuette:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Werkzeughuette_HQ
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    ui:
      order: 1
    birdseye:
      order: 1
    live:
      stream_name: Werkzeughuette_LQ
    motion:
      mask:
      - 0,74,174,38,178,249,821,227,1373,237,1599,252,1528,102,1719,97,1781,171,1814,283,1920,310,1920,0,0,0

  Garage:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Garage_HQ
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    ui:
      order: 2
    birdseye:
      order: 2
    live:
      stream_name: Garage_LQ
    motion:
      mask:
      - 1804,444,1899,373,1836,304,1700,395,1638,366,1447,314,1333,286,1100,223,1012,195,1035,240,1205,395,702,470,587,271,411,282,407,198,554,184,525,125,442,127,361,136,333,74,260,93,167,118,72,209,0,319,0,0,1920,0,1920,503

objects:
  track:
  # People:
  - person
  - face
  # Vehicles:
  - car
  - motorcycle
  - bicycle
  - license_plate
  # Delivery Logos:
  # Animals:
  - dog
  - cat
  - deer
  - horse
  - bird
  - raccoon
  - fox
  - bear
  - cow
  - squirrel
  - goat
  - rabbit
  # Other:
  - bbq_grill
  - umbrella
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.13.2
    shm_size: "128m"
    cap_add:
      - SYS_ADMIN
    environment:
      LIBVA_DRIVER_NAME: "radeonsi"
      PLUS_API_KEY: "XXXXXXXX"
    devices:
      - /dev/dri/renderD128
      - /dev/apex_0
      - /dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:Z
      - ./config.yml:/config/config.yml:Z
      - ./custom_models:/custom_models:Z
      - /mnt/external/frigate/storage:/media/frigate:Z
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/stats || exit 1"]
#    labels:
#      - "io.containers.autoupdate=registry"
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 16G

  frigate-notify:
    container_name: frigate-notify
    restart: always
    image: ghcr.io/0x2142/frigate-notify:latest
    depends_on:
      frigate:
        condition: service_healthy
    extra_hosts:
      - 'frigate-host:host-gateway'
    environment:
      - TZ=Europe/Vienna
    volumes:
      - ./config_notify.yml:/app/config.yml:Z
    logging:
      driver: k8s-file
      options:
        path: /opt/frigate/notify.log
        max-size: 10mb
    labels:
      - "io.containers.autoupdate=registry"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
```

### Relevant Frigate log output

```shell
2024-12-06 16:23:49.170725702  [INFO] Preparing Frigate...
2024-12-06 16:23:49.177708189  [INFO] Starting Frigate...
2024-12-06 16:23:50.392823333  [2024-12-06 16:23:50] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-12-06 16:23:57.155720498  [2024-12-06 16:23:57] peewee_migrate.logs            INFO    : Starting migrations
2024-12-06 16:23:57.161037428  [2024-12-06 16:23:57] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-12-06 16:23:57.183015570  [2024-12-06 16:23:57] frigate.app                    INFO    : Recording process started: 729
2024-12-06 16:23:57.185328377  [2024-12-06 16:23:57] frigate.app                    INFO    : go2rtc process pid: 88
2024-12-06 16:23:57.204557870  [2024-12-06 16:23:57] detector.coral_pci0            INFO    : Starting detection process: 738
2024-12-06 16:23:57.234682067  [2024-12-06 16:23:57] detector.coral_pci1            INFO    : Starting detection process: 740
2024-12-06 16:23:57.237781444  [2024-12-06 16:23:57] frigate.app                    INFO    : Output process started: 743
2024-12-06 16:23:57.237919551  [2024-12-06 16:23:57] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-12-06 16:23:57.238013763  [2024-12-06 16:23:57] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
2024-12-06 16:23:57.238097635  [2024-12-06 16:23:57] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-12-06 16:23:57.238172229  [2024-12-06 16:23:57] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-12-06 16:23:57.286102880  [2024-12-06 16:23:57] frigate.app                    INFO    : Camera processor started for Bach: 781
2024-12-06 16:23:57.286236859  [2024-12-06 16:23:57] frigate.app                    INFO    : Camera processor started for Werkzeughuette: 782
2024-12-06 16:23:57.292933363  [2024-12-06 16:23:57] frigate.app                    INFO    : Camera processor started for Garage: 784
2024-12-06 16:23:57.299381268  [2024-12-06 16:23:57] frigate.app                    INFO    : Capture process started for Bach: 786
2024-12-06 16:23:57.305746423  [2024-12-06 16:23:57] frigate.app                    INFO    : Capture process started for Werkzeughuette: 790
2024-12-06 16:23:57.312169409  [2024-12-06 16:23:57] frigate.app                    INFO    : Capture process started for Garage: 794
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![Screenshot from 2024-12-06 20-39-49](https://github.com/user-attachments/assets/ee1244dc-5894-4e83-9f1a-44b3e0a65e46)
![Screenshot from 2024-12-06 20-40-14](https://github.com/user-attachments/assets/c53e74dd-ef1c-4757-af3f-2c28b6bcc3fc)
![Screenshot from 2024-12-06 20-40-32](https://github.com/user-attachments/assets/4f3d9d2e-1fc8-4602-9185-1ee589dd53ca)

**Comment by NickM-27** [comment]
you should follow the docs for the steps to do after getting your Frigate+ model https://docs.frigate.video/plus/first_model#step-4-adjust-your-object-filters-for-higher-scores

**Reply by mike2307** [reply]
Alright; I'll give it a try. Thanks.
Is there also a template or suggestions somewhere in the documentation, which contain all frigate+ labels (for the latest model)?

**Comment by mike2307** [comment]
Here are some examples I wanted to attach in my original post. Just for consistency reasons:
![Screenshot from 2024-12-06 20-43-20](https://github.com/user-attachments/assets/120bbe4f-3d28-4af7-b4e3-0e89d7549f81)
![Screenshot from 2024-12-06 20-43-59](https://github.com/user-attachments/assets/dfe32454-5785-448e-b029-ff98a1f4d2df)

**Reply by NickM-27** [reply]
https://docs.frigate.video/plus/#available-label-types

**Reply by mike2307** [reply]
Yes, I'm aware of the labels.
But I meant the filter suggestions for each of the labels (like in the documentation page you sent in your first reply).

**Reply by NickM-27** [reply]
the values in the docs I linked above are general recommendations that should work fine, there is not a specific label by label recommendation. Any of the new animal labels I would suggest not increasing their score given that you have not uploaded any images of them yet.

**Reply by mike2307** [reply]
Okay, perfect. Thanks. I'll add the entire section to my config then (except the labels I haven't in the track section).
It will take a few days before I can give a definite feedback on the solution.
I'll mark the discussion as answered it all works out well :)

**Reply by ElectronicBattle** [reply]
I started with Frigate in  June of this year and joined F+ at the same time. I have used up four model training runs so far;  I was also worried that I'd burn through them too quickly.  In reality though, that has not been the case and I have enough left to last me until the summer of 2025. 

When the first model was generated I saw a vast improvement in false alarm rates and I think I remember that I did need to read the documentation several times to get the best "value" from the model.

**Reply by mike2307** [reply]
So back a again after about 2 days with some feedback.
The entire situation got a bit better but not by a huge margin. I'm still getting some occasional false car an person recognitions with rather high scores (otherwise it would have been excluded by the additional filtering).

Therefore I've got some new questions...
What's the suggested way to go onwards here?

Shall I continue submitting true and false positives and do periodic trainings (like every 100-200 additional submissions)? In that case I'll probably burn through the 12 trainings/year soon. 

Does it make sense to submit every false positives I run across? Until now I've been doing that but that included likely many duplicates. Further it's a bit tiring.

When do I get the new 12 trainings? Is that based on the calendar year or on the date of the initial subscription? Would there be a possibility to get additional trainings unlocked?

Shall I raise the scores for the filters?

Thanks a lot in advance.

**Reply by NickM-27** [reply]
What is your current configuration now? If you're worried about running out of trainings I'd suggest spacing them out a bit more. New training credits are added on the date of the subscription

**Reply by mike2307** [reply]
I added the sections from https://docs.frigate.video/plus/first_model#step-4-adjust-your-object-filters-for-higher-scores that apply to my labels at both of my CCTV locations, which for person and cars is:

```.
  filters:
    ...
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    ...
```

I have to admit that for the forest location things are much better. At the moment I mostly have false positives for the bbq_grill label but that's just a gimmick at the moment and probably I'll add a filter for that.

But for an indoor camera at my 2nd location I don't see that much of an improvement.
Here are 2 examples:

![Screenshot from 2024-12-08 16-13-39](https://github.com/user-attachments/assets/d86ad352-49d2-4d4e-9ce6-2d47ccb96934)
![Screenshot from 2024-12-08 16-12-58](https://github.com/user-attachments/assets/c369b14c-ff9b-4203-af72-9d075766fe11)

**Reply by NickM-27** [reply]
Why do you have car label enabled on an indoor camera?

**Reply by mike2307** [reply]
When the door is open it might see a car nevertheless.
So it's possible to get a car in the frame (at least partially).

At the moment I have the track config section globally; not camera specific.
But I can disable it for that camera if it helps to reduce model confusion...

**Reply by NickM-27** [reply]
I mean, I guess I don't see how that's actually useful, and there's no point trying to train the model to not see cars inside unless there is some reason to keep car detection on the camera.

**Reply by mike2307** [reply]
The reason why I didn't bother about camera specific tracking configuration was mostly because my previous model I used didn't have these kinds of false positives. It had many others to be fully honest (mostly detecting humans as animals when they were in an unnatural position, like picking something up from the floor).

With the frigate+ model I have the impression that it's a bit obsessed about persons and cars. :)

So as far as I understood so far, one path forward would be to use a camera specific object tracking configurations to exclude anything that isn't very likely to occur and/or of high interest at that place (especially if indoor and outdoor cams are used together in a particular location).

But what about false positives of objects at cameras that are indeed highly wanted (like a person indoors)?
Would it make sense to raise the filter scores? If so, which one? The min_score, threshold or both?

Further does it make sense to submit very similar false positives?

**Reply by NickM-27** [reply]
right, but in any case it doesn't make sense to have a camera spend resources tracking objects that don't matter. for example in my case I have a doorbell camera that sees cars but I don't have it detect cars because there is no point, there is an overview camera that sees the same area. 

I would absolutely recommend setting each camera to only track what is important on that camera. 

Depends what the score of the false positives are, if they are all around a low value like 85% it might make sense to increase the threshold a bit. But if you are seeing higher scoring false positives then setting the threshold higher than that might negate lower scoring true positives

yes, submitting similar false positives does still help

**Reply by mike2307** [reply]
Alright; then I'll do some further tweaking by
* having the object tracking configuration per camera
* having the object filtering configuration globally (for maintainability reasons)
* trying to sharpen the object filtering values

I'll get back with an update in a few days then. :)

But in case it's turning out to become more tedious, one question in advance:
Would it be possible to get additional training credits unlocked (maybe even paid ones)?

**Reply by NickM-27** [reply]
You'd have to ask @blakeblackshear

**Reply by blakeblackshear** [reply]
Once your available trainings hits 0, you will have the option to purchase more.

**Reply by ElectronicBattle** [reply]
@mike2307 when I started with Frigate six months I just added the basic filters and thresholds at the start of my config as values to apply globally, and my results, when I later submitted my images and integrated the subsequent model, were very good:

```
objects:
  filters:
    dog:
      min_score: .8
      threshold: .9
    cat:
      min_score: .75
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
```
After my first model submission I experienced a big improvement, and then again with the next. I now get detection accuracies in excess of (best guess, I expect there's a way to work it out accurately, but not sure how, at the moment) 95%.  

After the first or second or third training, I modified some of the values slightly,  and the above is what I am running now. 

Later on I added some specific tracked items per camera, for example:

```
track:
    - person
    - face
    - car
    - license_plate
```
or

```
track:
    - cat
    - dog
    - fox
    - bird
    - squirrel
    - package
    - bicycle
```
Some of this config is for my "experimental" 0.15 docker compose installation which I only run from time to time during the week, and some is from my original 0.13 which is still my main service running 24/7 .
