### DISCUSSION TITLE
[Support]: "Filters is very slow "

### DISCUSSION THREAD

**Discussion by Oli1549** [blakeblackshear/frigate#15390] [General Support]
### Describe the problem you are having

Filters are very slow, often 500ms+

Cant figure out why, as it didn't seem to do it when I first setup frigate.

im using a usb google coral TPU

Please see: https://i.imgur.com/j1epqVR.png

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.3
  user: *
  password: *

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

## logger:
 ## logs:
 ##   frigate.record: debug

detectors:
  coral:
    type: edgetpu
    device: usb


#Global Object Settings
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
  streams:
    Backyard:
      - rtsp://admin:*@192.168.1.80/Streaming/Channels/101/
    Backyard-sub:
      - rtsp://admin:*@192.168.1.80/Streaming/Channels/102/
    Front:
      - rtsp://admin:*@192.168.1.81/Streaming/Channels/101/
    Front-sub:
      - rtsp://admin:*@192.168.1.81/Streaming/Channels/102/
    Drive:
      - rtsp://admin:*@192.168.1.82/Streaming/Channels/101/
    Drive-sub:
      - rtsp://admin:*@192.168.1.82/Streaming/Channels/102/
    Lawn:
      - rtsp://admin:*@192.168.1.83/Streaming/Channels/101/
    Lawn-sub:
      - rtsp://admin:*@192.168.1.83/Streaming/Channels/102/




cameras:
  Backyard: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard-sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Backyard # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog
    snapshots:
      enabled: true

    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
  Front: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog

    snapshots:
      enabled: true

    motion:
      threshold: 70
      contour_area: 30
      improve_contrast: 'true'
  Drive: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Drive-sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Drive # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720

    snapshots:
      enabled: true

    motion:
      threshold: 70
      contour_area: 10
      improve_contrast: 'true'
    objects:
      track:
        - person
        - car
  Lawn: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Lawn-sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Lawn # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog
    snapshots:
      enabled: true

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'


version: 0.14
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
https://imgur.com/a/nJvslgw
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Ran through unraid docker.

--shm-size=256m --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --restart unless-stopped
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision 4K x4

**Comment by hawkeye217** [comment]
You are missing `objects:` above `filters:` in your config. It should look like this:

```

#Global Object Settings
objects:
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

```
