### DISCUSSION TITLE
[Detector Support]: Hailo 8L and the Frigate Plus model support.

### DISCUSSION THREAD

**Discussion by chrismcdowell25** [blakeblackshear/frigate#15397] [Detector Support] [answered]
### Describe the problem you are having

I am trying to use the Hailo 8L with my Frigate Plus model.  I am getting an error on all of the different model options that they are not supported.  I am assuming that I need to convert this to Hailo's HEF format.  I am trying to use the hailo DFC program but am having issues with those conversion commands.

### Version

15 Beta

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: CCCCCCCCC
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: CCCCCCCCC
  password: CCCCCCCCC

ffmpeg:
  hwaccel_args: preset-vaapi
  #input_args: preset-rtsp-udp
  #output_args: preset-record-generic-audio-copy

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef
      #path: plus://5da8db58f6b07967ee161de9c004fe52

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: ssd

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - motorcycle
    - bicycle
    - boat
    - deer
    - dog
    - horse
    - deer
    - bird
    - raccoon
    - fox
    - squirrel
    - rabbit
    - package
    - umbrella
    - face
    - fedex
    - amazon
    - usps
    - dhl
    - license_plate
    - package
    - person
    - ups

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 60
    # Optional: Per object retention days
    objects:
      person: 100
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 80

cameras:
  logan_north_front:
    ffmpeg:
      inputs:
        - path: rtsp://CCCCCCCCC
          roles:
            - record
            - detect
    detect:
      width: 2592 # <- optional, by default Frigate tries to automatically detect resolution
      height: 1944

    record:
      enabled: true
#      retain:
#        days: 60
#        mode: motion
#      events:
        # Optional: Number of seconds before the event to include (default: shown below)
#        pre_capture: 10
        # Optional: Number of seconds after the event to include (default: shown below)
#        post_capture: 10
        # Optional: Objects to save recordings for. (default: all tracked objects)
#        retain:
#          default: 100
#          mode: motion

    motion:
      mask: 0.628,0.306,0.269,0.31,0.103,0.353,0.101,0.216,0.217,0.004,0.695,0.002
      threshold: 32
      contour_area: 8
      improve_contrast: true
    zones:
      North_Gate:
        coordinates: 
          0.003,0.547,0.587,0.574,0.666,0.567,0.675,0.469,0.998,0.63,0.995,0.993,0.005,0.991
        loitering_time: 0
    review:
      alerts:
        required_zones: North_Gate
  logan_door_front:
    ffmpeg:
      inputs:
        - path: rtsp://CCCCCCCCC
          roles:
            - record
            - detect

    record:
      enabled: true
#      retain:
#        days: 60
#        mode: motion
#      events:
        # Optional: Number of seconds before the event to include (default: shown below)
#        pre_capture: 10
        # Optional: Number of seconds after the event to include (default: shown below)
#        post_capture: 10
        # Optional: Objects to save recordings for. (default: all tracked objects)
#        retain:
#          default: 100
#          mode: motion

    zones:
      Entry:
        coordinates: 0,0,0.268,0,0.242,0.349,0.439,0.472,0.516,0.544,0.543,1,0,1
        loitering_time: 0
        inertia: 3
        objects:
          - package
          - person
    motion:
      mask: 
        0.313,0.142,0.405,0.229,0.448,0.327,0.457,0.406,0.427,0.49,0.379,0.549,0.253,0.621,0.245,0.523,0.268,0.135
    review:
      alerts:
        required_zones: Entry
    detect:
      annotation_offset: 0
  logan_south_front:
    ffmpeg:
      inputs:
        - path: rtsp://CCCCCCCCC
          roles:
            - record
            - detect

    record:
      enabled: true
#      retain:
#        days: 60
#        mode: motion
#      events:
        # Optional: Number of seconds before the event to include (default: shown below)
#        pre_capture: 15
        # Optional: Number of seconds after the event to include (default: shown below)
#        post_capture: 15
        # Optional: Objects to save recordings for. (default: all tracked objects)
#        retain:
#          default: 100
#          mode: motion
    zones:
      South_Gate:
        coordinates: 0.115,0.384,0.998,0.402,0.997,0.996,0.003,0.996,0.005,0.561
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: South_Gate
version: 0.15-0
semantic_search:
  enabled: false
  reindex: false
  model_size: small
camera_groups:
  Main:
    order: 1
    icon: LuActivity
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:d0cc8cb-h8l
    #image: ghcr.io/blakeblackshear/frigate:0.14.0-beta4
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/dri/card1 # for intel hwaccel, needs to be updated for your hardware
      #- /dev/fb0
      - /dev/hailo0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Video/Frigate/config/:/config
      - /mnt/Video/Frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "cccccc"
      PLUS_API_KEY: "cccccc"
      LIBVA_DRIVER_NAME: "radeonsi"
```

### Relevant Frigate log output

```shell
2024-12-07 22:52:55.874153370  2024/12/07 22:52:55 [error] 172#172: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"

2024-12-07 22:52:56.842034795  [2024-12-07 22:52:56] frigate.config.config          WARNING : Customizing more than a detector model path is unsupported.

2024-12-07 22:52:56.842789278  *************************************************************

2024-12-07 22:52:56.842794287  *************************************************************

2024-12-07 22:52:56.842798445  ***    Your config file is not valid!                     ***

2024-12-07 22:52:56.842804987  ***    Please check the docs at                           ***

2024-12-07 22:52:56.842807391  ***    https://docs.frigate.video/configuration/          ***

2024-12-07 22:52:56.842834522  *************************************************************

2024-12-07 22:52:56.842836886  *************************************************************

2024-12-07 22:52:56.842839160  ***    Config Validation Errors                           ***

2024-12-07 22:52:56.842841294  *************************************************************

2024-12-07 22:52:56.842916324  : Value error, Model does not support detector type of hailo8l

2024-12-07 22:52:56.842920762  *************************************************************

2024-12-07 22:52:56.842923497  ***    End Config Validation Errors                       ***

2024-12-07 22:52:56.842926202  *************************************************************

2024-12-07 22:52:57.285537606  [INFO] Service Frigate exited with code 1 (by signal 0)

s6-rc: info: service legacy-services: stopping
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

N/A
