### DISCUSSION TITLE
[Config Support]: My configured person threshold appears to be ignored

### DISCUSSION THREAD

**Discussion by dstretch** [blakeblackshear/frigate#15393] [Config Support] [answered]
### Describe the problem you are having

I have a global configuration entry for filtering the person threshold to 0.7 but I keep regularly seeing alerts and reviews in the UI for "person"s under 70%. Am I misunderstanding this setting?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.88.20
  user: ********
  password: ********

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: all

cameras:
  reolinkDoorbell:
    ffmpeg:
      inputs:
        - path: rtsp://********:********@192.168.88.134:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://********:********@192.168.88.134:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    motion:
      mask: 0.342,0.012,0.343,0.059,0.649,0.057,0.649,0.008
    zones:
      Helen's_drive:
        coordinates: 1,0.516,0.682,0.502,0.735,0.76,1,0.754
        loitering_time: 0
        inertia: 3
      Front_garden:
        coordinates: 0,0.764,0,0.631,0.311,0.769,0.999,0.756,1,1,0,0.997
        loitering_time: 0
      Drive:
        coordinates: 0,0.456,0.683,0.5,0.729,0.757,0.309,0.764,0,0.628
        loitering_time: 0
        inertia: 3
      Sky:
        coordinates: 0,0,1,0,1,0.515,0.519,0.487,0,0.455
        loitering_time: 5
        inertia: 3
    review:
      alerts:
        required_zones:
          - Drive
          - Front_garden
    live:
      stream_name: reolink_doorbell
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://********:********@192.168.88.171:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://********:********@192.168.88.171:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    motion:
      mask:
        - 0.211,-0.001,0.209,0.064,0.921,0.077,0.916,0
        - 0.816,0.456,0.678,0.648,0.635,0.82,0.51,1,1,1,1,0.466
    live:
      stream_name: driveway
  backGarden:
    ffmpeg:
      inputs:
        - path: rtsp://********:********@192.168.88.159:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://********:********@192.168.88.159:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    live:
      stream_name: backGarden
  #dericamP2:
    #ffmpeg:
      #hwaccel_args: preset-vaapi
      #inputs:
        #- path: rtsp://********:********@192.168.88.204:554/11
        #  input_args: preset-rtsp-restream
        #  roles:
        #    - record
        #- path: rtsp://********:********@192.168.88.204:554/12
        #  input_args: preset-rtsp-restream
        #  roles:
        #    - detect
      #output_args:
      #  record: preset-record-generic-audio-copy
    #detect:
    #  width: 640
    #  height: 352
    #  fps: 5
    #objects:
    #  track:
    #    - person
    #snapshots:
    #  enabled: true
    #  timestamp: false
    #  bounding_box: true
    #  retain:
    #    default: 2

    motion:
      mask:
        - 0.714,0,0.621,0.245,0.707,0.632,0.834,1,1,1,1,0
        - 0.347,0.015,0.347,0.048,0.643,0.048,0.643,0.013
go2rtc:
  streams:
    reolink_doorbell:
      - ffmpeg:http://192.168.88.134/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=********&password=********#video=copy#audio=copy#audio=opus
      - rtsp://192.168.88.134/Preview_01_sub
    reolink_doorbell_sub:
      - ffmpeg:http://192.168.88.134/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=********&password=********
    driveway:
      - ffmpeg:http://192.168.88.171/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=********&password=********#video=copy#audio=copy#audio=opus
      - rtsp://192.168.88.171/Preview_01_sub
    driveway_sub:
      - ffmpeg:http://192.168.88.171/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=********&password=********
    backGarden:
      - ffmpeg:http://192.168.88.159/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=********&password=********#video=copy#audio=copy#audio=opus
      - rtsp://192.168.88.159/Preview_01_sub
    backGarden_sub:
      - ffmpeg:http://192.168.88.159/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=********&password=********
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
From the Unraid app marketplace
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![backGarden-1733595390 421233-07a38u](https://github.com/user-attachments/assets/1291b9e9-b9db-4e5a-accb-afc1b4bebd35)
![backGarden-1733592336 244846-k9tt9z](https://github.com/user-attachments/assets/eb85063d-a3cf-4746-9f80-6555a1429986)
