### DISCUSSION TITLE
What do these erros mean?

### DISCUSSION THREAD

**Discussion by Imwithstupid007** [blakeblackshear/frigate#15396] [Ask A Question]
```
Does anybody know what these errors mean?
My complete log is filling up with them.


2024-12-07 22:31:33.592790  2024-12-07 20:57:53.525568696
2024-12-07 22:31:33.592794  2024-12-07 20:57:53.525569618
2024-12-07 20:58:03.531099366  [ERROR:0@22280.232] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-12-07 22:31:33.592799  2024-12-07 20:58:03.531103424
2024-12-07 20:58:03.531105624  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-12-07 22:31:33.592804  2024-12-07 20:58:03.531106674
2024-12-07 22:31:33.592808  2024-12-07 20:58:03.531107722
2024-12-07 20:58:13.536737516  [ERROR:0@22290.237] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-12-07 22:31:33.592812  2024-12-07 20:58:13.536741902
2024-12-07 20:58:13.536744083  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-12-07 22:31:33.592817  2024-12-07 20:58:13.536745280
2024-12-07 22:31:33.592821  2024-12-07 20:58:13.536746286
2024-12-07 20:58:23.545816286  [ERROR:0@22300.246] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-12-07 22:31:33.592825  2024-12-07 20:58:23.545820623
2024-12-07 20:58:23.545823001  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-12-07 22:31:33.592830  2024-12-07 20:58:23.545824269
2024-12-07 22:31:33.592834  2024-12-07 20:58:23.545825361
2024-12-07 20:58:33.552469166  [ERROR:0@22310.253] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-12-07 22:31:33.592839  2024-12-07 20:58:33.552473466
2024-12-07 20:58:33.552475868  OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-12-07 22:31:33.592843  2024-12-07 20:58:33.552477106
2024-12-07 22:31:33.592847  2024-12-07 20:58:33.552478156
2024-12-07 20:58:43.563193124  [ERROR:0@22320.264] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-12-07 22:31:33.592852  2024-12-07 20:58:43.563197674

**Comment by NickM-27** [comment]
It means opencv can't process the recordings but it isn't a problem because ffprobe is used in that case. In the next version these messages won't be shown

**Reply by Imwithstupid007** [reply]
Thank for your quick reply.
But, there is definitely something going on.  The recordings are cut short and not visible anymore.
 
![image](https://github.com/user-attachments/assets/43d36ef0-d342-431f-a37b-69f5c5b07aae)

**Reply by NickM-27** [reply]
What is your recording config

**Reply by Imwithstupid007** [reply]
This is my config.


```
ui:
  time_format: 24hour
  strftime_fmt: '%d/%m/%Y %H:%M:%S'

mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

#logger:
#  default: info
#  logs:
#    frigate.record: debug

birdseye:
  enabled: false
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  sync_recordings: false
  retain:
    days: 10
    mode: all
  events:
    retain:
      default: 10

go2rtc:
  streams:
    tuinhuiscam:
      - rtsp://rtspuser:xxxxxxx@192.168.1.64:554/Streaming/Channels/101
      # 2560 x 1440 @ 20 fps
    tuinhuiscam_sub:
      - rtsp://rtspuser:xxxxxx@192.168.1.64:554/Streaming/Channels/102
      # 640 x 480 @ 6 fps
    deurbel:
      - ffmpeg:http://192.168.1.65/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx#video=copy#audio=copy#audio=opus
    deurbel_sub:
      - ffmpeg:http://192.168.1.65/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxxx
      # 968 x 672 @ 30 fps


cameras:
  tuinhuiscam: # geen output_args: geen audio
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/tuinhuiscam?video&audio
          roles:
            - record
        - path: rtsp://localhost:8554/tuinhuiscam_sub
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0.321,0.308,0.195,0.307,0,0,0
        - 1,0,1,1,0.962,1,0.858,0
        - 0.815,0.441,0.849,0.442,0.849,0.152,0.815,0.151
        - 0,0.323,0.077,0.291,0.082,1,0,1
    zones:
      tuin:
        coordinates: 0.961,1,0.873,0.164,0.388,0.166,0,0.324,0,1
        objects: person
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: tuin
  deurbel: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/deurbel
          roles:
            - record
        - path: rtsp://localhost:8554/deurbel_sub
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
        - bicycle
        - motorcycle
    motion:
      mask: 0,0,1,0,1,0.413,0,0.413
    zones:
      straat:
        coordinates: 0,1,1,1,1,0.414,0,0.414
        objects:
          - person
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: straat
version: 0.14
camera_groups: {}
```
