### DISCUSSION TITLE
Why Frigate silently fails to delete old recordings?

### DISCUSSION THREAD

**Discussion by Caian** [blakeblackshear/frigate#15391] [Ask A Question]
I have my cameras set up to retain only 3 days worth of recordings:

```
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: 
            rtsp: ...
          roles:
            - record
    detect:
      enabled: false
      width: 1280
      height: 720
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 3
        mode: all
```

But Frigate will eventually leave some recordings behind:

```
recordings# ls 
2024-11-25  2024-11-26  2024-12-04  2024-12-05  2024-12-06  2024-12-07
```

And these old folders do contain recordings, as Frigate reports only 37GB used of storage whereas the recordings folder contains 49GB of files.

I'm deploying version 0.14.1-f4f3cfa in a rootless podman container instead of docker.

Edit: The logs contain no errors nor mentions to storage full. I really don't want to wait for it to fill because this partition is shared with other services.
