### DISCUSSION TITLE
[Support]: Clicking on date(s) within the calendar view periodically causes the entire screen to go blank (white)

### DISCUSSION THREAD

**Discussion by raspman** [blakeblackshear/frigate#15406] [General Support]
### Describe the problem you are having

I've reproduced this in multiple devices on multiple browsers.  I click on the camera live view, then click on history, then click on last 24 hours, which brings up the calendar view.  Even if I click on today's date, which I know there is video available for, it causes the entire screen to go blank (white screen.)  It doesn't happen every time.  I've used multiple browsers on multiple devices and can reproduce the issue (including the HA app.)  I can re-visit either Frigate direclty or HAOS proxy add-on and the GUI is back. 

### Version

0.14.0

### What browser(s) are you using?

Firefox 133.0 (aarch64), Safari (Version 18.1.1 (20619.2.8.11.12)) and the HA App. 

### Frigate config file

```yaml
mqtt:
  host: xx
  port: 1883
  user: xx
  password: xx
  topic_prefix: xx

record:
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 1
 
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-http-reolink

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    garage:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus
    frontdoor:
      - ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus
      
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0,0.005,0.08,0.472,0.083,0.47,0
        - 0.279,0.02,0.945,0,0.933,0.36,0.285,0.223
    zones:
      garage_driveway:
        coordinates: 0.325,1,0.735,0.403,1,0.275,1,1
        loitering_time: 0
    objects:
      track:
        - person
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0,1,0,1,0.652,0,0.623
    objects:
      track:
        - person
version: 0.14
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.14.0
    privileged: true
    restart: unless-stopped
    shm_size: '512mb'
    #devices:
    # - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate/config:/config
      - /mnt/frigateVideos:/media/frigate
      - /etc/frigate:/database
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8554:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "somepassword"
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Reolink WiFi Doorbell Cam and Reolink CX410
