### DISCUSSION TITLE
[Detector Support]: Labelmap incorrect

### DISCUSSION THREAD

**Discussion by StickySide** [blakeblackshear/frigate#15421] [Detector Support]
### Describe the problem you are having

Using the yolov-tiny-416 model, it identified people perfectly but never my cats. I set up some test footage with looping mp4s and it never ever detected them. Detected cars and people perfectly. On a whim I decided to have it detect the first 20 or so objects on labelmap.txt... It was detecting the cats as birds, and dogs as cats (IE incorrect label mapping of "15: bird" when it should be "15: cat").

I added:
model:
  path: /config/model_cache/tensorrt/yolov4-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
  labelmap:
    15: cat # <----- was incorrectly mapped as "15: bird" but 15 is cat
    16: dog # <----- was incorrectly mapped as "16: cat" but 16 is dog
    
  and it is now detecting dogs and cats perfectly. Not sure how far back the error in the labelmap goes, I didnt feel like setting up test footage for motorcycles etc.. but it IS correct for people and cars.
  
 Is there an updated label map maybe im missing?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

#logger:
#  default: info
#  logs:
#    frigate.detectors: debug  

##### Detection

detectors:
  tensorrt:
    type: tensorrt
    device: 0

audio:
  enabled: true

model:
  path: /config/model_cache/tensorrt/yolov4-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
  labelmap: # <----- Fixing incorrect mappings
    15: cat
    16: dog

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - car
    - boat
    - traffic light
    - fire hydrant
    - street sign
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
  filters:
    cat:
      min_score: 0.3 # <----- not sure if this helps detecting the cats


###### Review Settings (Global) 

#review:
#  alerts:
#    labels:
#      - cat # <----- temporary for testing
#  detections:
#    labels:
#      - person

##### Timestamp
timestamp_style:
  position: tl

###### Web streams

#go2rtc:
#  streams:
#    Livingroom:
#      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main
#      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main
#    Livingroom_sub:
#      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub
#      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub
#    Kitchen:
#      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
#      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
#    Kitchen_sub:
#      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub
#      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub



###### Cameras

cameras:

## LIVINGROOM ##
  Livingroom:
    enabled: true

    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: /media/frigate/testing/dog.mp4 # TESTING
          input_args: -re -stream_loop -1 -fflags +genpts # TESTING
#            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub     # <----- The stream you want to use for detection.. add one for recording later
#          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main # <----- Recording stream
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac # <----- audio on recordings

    review:
      alerts:
        labels:
          - cat
      detections:
        labels:
          - person

    detect:
      enabled: true
      width: 1280
      height: 720

    onvif:
      host: 192.168.80.10
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    record: # <----- Recording setting
      enabled: false
      retain:
        days: 0      # <----- "3" for reduced settings, "0" for events only
        mode: all # <----- "motion" for reduced settings, "all" for events only preset
      events:
        retain:
          default: 30
          mode: motion

## KITCHEN ##
  Kitchen:
    enabled: true

    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: /media/frigate/testing/dog1.mp4 # TESTING
          input_args: -re -stream_loop -1 -fflags +genpts # TESTING
#            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub     # <----- The stream you want to use for detection.. add one for recording later
#          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac # <----- audio on recordings

    review:
      alerts:
        labels:
          - cat
      detections:
        labels:
          - person

    detect:
      enabled: true
      width: 1280
      height: 720

    onvif:
      host: 192.168.80.11
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    record: # <----- Recording setting
      enabled: false

      retain:
        days: 0      # <----- "3" for reduced settings, "0" for events only
        mode: all # <----- "motion" for reduced settings, "all" for events only preset
      events:
        retain:
          default: 30
          mode: motion



camera_groups:
  Indoors:
    order: 1
    icon: LuCat
    cameras:
      - Kitchen
      - Livingroom

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
Unraid
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker CLI

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2024-12-09 151644](https://github.com/user-attachments/assets/f4442ea0-634c-47e7-a620-2a9f2c59ee86)
