### DISCUSSION TITLE
Reolink camera stream artifacts

### DISCUSSION THREAD

**Discussion by Plyn1x** [blakeblackshear/frigate#15429] [Camera Support]
Hi, I’m experiencing issues with my Reolink Duo 2 cameras over PoE. The RTSP stream seems to break up despite several adjustments. I’ve configured the stream to use the fluent (low-bandwidth) profile, set CBR (Constant Bitrate) mode, and adjusted the interframe spacing to 1. I’ve also prioritized fluency over quality with the “Fluency First” option, but the issue persists only in Frigate.

Any ideas or suggestions for resolving this would be greatly appreciated.
Here is also my Frigate Config: 
```

mqtt:
  host: homeassistant.local
  port: 1883
  user: <your-mqtt-username>
  password: <your-mqtt-password>  # Replace with your MQTT password

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac  # Enable audio support

cameras:
  Einfahrt:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<camera-username>:<camera-password>@192.168.178.52:8554/h264Preview_01_main
          roles:
            - detect
            - record
            - audio
    detect:
      fps: 5
      enabled: true
      stationary:
        interval: 50
        threshold: 100
        max_frames:
          default: 500
          objects:
            car: 500
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 5
        pre_capture: 60
        post_capture: 60
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 5
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - parcel  # Parcel tracking limited to Einfahrt
      filters:
        car:
          min_area: 5000
          max_area: 100000
          min_score: 0.7
          threshold: 0.8
        parcel:
          min_area: 3000
          max_area: 50000
          min_score: 0.75
          threshold: 0.85
    motion:
      mask:
        - 0.796,0.638,1,0.724,1,0.638
        - 0.822,0,0.823,0.08,1,0.086,1,0

  3D-Drucker:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<camera-username>:<camera-password>@192.168.178.55:8554/h264Preview_01_main
          roles:
            - detect
            - record
            - audio
    detect:
      fps: 5
      enabled: true
      stationary:
        interval: 50
        threshold: 100
        max_frames:
          default: 500
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 5
        pre_capture: 60
        post_capture: 60
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 5
    objects:
      track:
        - person
        - dog  # No parcel tracking in 3D-Drucker camera
      mask: 
        0.237,0,0.307,0.387,0.346,0.452,0.529,0.536,0.667,0.58,0.836,0.625,1,0,0.707,0,0.446,0,0.456,0.139,0.372,0.194,0.348,0,0.309,0,0.294,0,0.26,0
    motion:
      mask:
        - 0.705,0.004,0.707,0.031,1,0.037,0.998,0.005

  Vor-Garage:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<camera-username>:<camera-password>@192.168.178.88:8554/h264Preview_01_main
          roles:
            - detect
            - record
            - audio
    detect:
      fps: 5
      enabled: true
      stationary:
        interval: 50
        threshold: 100
        max_frames:
          default: 500
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 5
        pre_capture: 60
        post_capture: 60
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 5
    objects:
      track:
        - person
        - dog
        - cat

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - siren
    - glass
  filters:
    bark:
      threshold: 0.7
    fire_alarm:
      threshold: 0.7
    scream:
      threshold: 0.7
    speech:
      threshold: 0.7
    yell:
      threshold: 0.7
    siren:  # Custom threshold for sirens
      threshold: 0.7
    alarm:  # Custom threshold for alarms
      threshold: 0.7
    glass:
      threshold: 0.7

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: debug

version: 0.14

```
Could it be that my Intel NUC is running into its limits I have nearly 100% usage with Coral Edge TPU (high FFMPEG usage)
