### DISCUSSION TITLE
[Config Support]: How to use sound detection for events, without recording those?

### DISCUSSION THREAD

**Discussion by akcasoy** [blakeblackshear/frigate#15435] [Config Support]
### Describe the problem you are having

Hi,

I'm using Frigate with a Reolink camera, which has a built-in microphone. I want to be able to use sound detection for events (for example using as a babyphone), but do not want to record those.

Is there a way to configure it that way?

This is my current configuration, where i record motions of the last 60 days (without object detection). I recently added as intended the part "audio", but the current config records nights a black screen while the baby crying.

* I do not need recording, since i get a Home Assistant Notification as soon as baby cries. So my audio detection works as expected. I just do not want to record those moments unnecessarily.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.6
  user: x
  password: x

record:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    reolink_e1_zoom:
      - ffmpeg:http://192.168.178.115/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.178.115/Preview_01_sub
    reolink_e1_zoom_sub:
      - ffmpeg:http://192.168.178.115/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password

cameras:
  defne_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_e1_zoom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_e1_zoom_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect # man sollte trotz "nur record" ein detect stream haben: https://docs.frigate.video/configuration/cameras
    record:
      retain:
        days: 60
        mode: motion
    detect:
      enabled: false
    audio:
      enabled: true
      min_volume: 300
      listen:
        - scream
        - speech
        - yell
        - crying
    live:
      stream_name: reolink_e1_zoom # Für Frigate WebUI
    motion:
      mask: 0.294,0.016,0.706,0.016,0.706,0.052,0.294,0.052 # Timestamp Mask
      improve_contrast: false # Mit eingeschaltetem Flag erkennt die Kamera nachts immer irgendwelche "motions"
      # lightning_threshold: 0.8 # Damit das Einschalten von Licht/IR keine Recording auslöst 
version: 0.14
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral

**Comment by NickM-27** [comment]
In general it seems a bit counterintuitive because the only way to review audio is by listening to recordings. If you only want it for HA then you can define `detections` and not include audio labels

**Reply by akcasoy** [reply]
Thank you Nick, i do not understand your suggestion clearly. I also do not want any **review** of audio events. 
Could u write some parts of that config you mean?

**Reply by NickM-27** [reply]
https://docs.frigate.video/configuration/review#restricting-detections-to-specific-labels

**Reply by akcasoy** [reply]
> https://docs.frigate.video/configuration/review#restricting-detections-to-specific-labels

sorry, i still do not get how that will give me want i want.. 

should i write sth. like this? 

```
review:
  detections:
    labels:
      - scream
      - speech
      - yell
      - crying
```

without audio - enabled: true?
How will that not record those?
And how will i setup the audio event sensitivity without audio (min_volume att.)?

**Reply by NickM-27** [reply]
You need to define the detections as the object labels and not include the audio labels, telling frigate you don't care about the audio labels for review

**Comment by Ricetato** [comment]
It's been a few months since your post and hopefully you figured it out. It sounds like your requirements are similar (but different) to mine but in case any future travellers need this... this is what I'm doing.

My high level requirements were:
1. Do not record and camera footage at all, no events, no 24/7 recording - Unifi already does this and don't want two separate boxes processing video
2. Automatically detect when certain sounds occur from a particular camera
3. Make events available in Home Assistant to create automations on and visualise

That being said, how I came across your thread was I just started searching up whether it's possible to record video _only_ during an audio event.

I'm not actually using Frigate for its main use-case of video recording and detections since I already vendor-locked myself into Ubiquiti (whoops lol). I'm not using the Frigate integration in HA either, I'm just using MQTT events to minimise the number of "full" third party integrations.

I had a crack at using Tensorflow with YAMNet to detect audio events but found that just using the Frigate docker container used less CPU than the python scripts I was able to cobble together with the help of an LLM. I probably could've made it more efficient but wasn't worth my time given Frigate with audio detections uses minimal resources (great job team!) I also imagine a custom solution would've been a lot less reliable than Frigate and require frequent maintenance.


Sample frigate config:
```
mqtt:
  enabled: true
  host: example.com
  port: 1883
  user: example
  password: example

go2rtc:
  streams:
    cameraname: rtspx://0.0.0.0/

cameras:
  cameraname:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/cameraname
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    record:
      enabled: false
    detect:
      enabled: false
    motion:
      enabled: false
    audio:
      enabled: true
      listen:
        - crying
```


Sample Home Assistant config (from configuration.yaml):
```
mqtt:
  binary_sensor:
    - name: Cameraname Crying Detector
      unique_id: cameraname_crying
      state_topic: frigate/cameraname/audio/crying
      device:
        connections: [["mac", "ff:ff:ff:ff:ff:ff"]] #Replace with your camera's MAC or change the entire "connections" to make the detector show up in your device's page in HA
      device_class: sound
      icon: mdi:baby-face
```
