### DISCUSSION TITLE
[Config Support]: Detector isn't finding anything, but shows it is active. So I believe my config is confused somewhere

### DISCUSSION THREAD

**Discussion by isaacolsen94** [blakeblackshear/frigate#15452] [Config Support] [answered]
### Describe the problem you are having

I'm running Frigate on Unraid via docker with a GPU passed through. When I use nvidia-smi it shows 3 ffmpeg commands and 1 tensorrt task running. My home assistant shows the objects I have called out in config for detection. But detections never show up and home assistant shows the broken image icon and never gets updated. I'm not sure where to begin to narrow down what is going on. I can provide any info needed! Just didn't know what was relevant. 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
#yaml-language-server: $schema=http://10.10.50.2:5000/api/config/schema.json
version: 0.14
mqtt:
  enabled: false

go2rtc:
  streams:
    garage_amcrestpoe: # H.264/AAC 3840x2160 15fps
      - rtsp://REDACTED:REDACTED@10.10.30.10:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:garage_amcrestpoe#audio=opus
    doorbell_reolinkpoe: # H.264/AAC 2560x1920 20fps
      #- "rtsp://REDACTED:REDACTED@10.10.30.173:554/h264Preview_01_main"
      #- "ffmpeg:reolink_doorbell_poe#audio=opus"
      - ffmpeg:http://10.10.30.90/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus#hardware
      #- rtsp://reolink_ip/Preview_01_sub
    doorbell_reolinkpoe_sub:
      - ffmpeg:http://10.10.30.90/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED
    front_reolinkpoe: # H.265/AAC 4512x2512 20fps
      - rtsp://REDACTED:REDACTED@10.10.30.229:554/h265Preview_01_main
      - ffmpeg:front_reolinkpoe#audio=opus

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

birdseye:
  enabled: true
  restream: true
  mode: continuous
  width: 3840
  height: 2160

detectors:
  tensorrt:
    type: tensorrt
    device: 0

objects:
  track:
   - person
   - car
   - cat

model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt

review:
  alerts:
    labels:
      - person
      - car
  detections:
    labels:
      - car
      - person
      - cat

snapshots:
  enabled: true

record:
  enabled: true
  retain:
    days: 3
    mode: motion
#  events:
#    retain:
#      days: 14
#      mode: active_objects

cameras:
  garage_amcrestpoe: 
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_amcrestpoe # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 3840
      height: 2160
  doorbell_reolinkpoe: 
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_reolinkpoe 
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell_reolinkpoe_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      enabled: true 
      width: 2560
      height: 1920
      fps: 10
  front_reolinkpoe: 
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_reolinkpoe # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 4512
      height: 2512

camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
2024-12-11 17:12:37.778692199  [INFO] Preparing Frigate...
2024-12-11 17:12:37.801246513  [INFO] Starting Frigate...
2024-12-11 17:12:40.252282181  [2024-12-11 17:12:40] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-12-11 17:12:40.252350639  [2024-12-11 17:12:40] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-12-11 17:12:40.271990392  [2024-12-11 17:12:40] frigate.util.config            INFO    : frigate config does not need migration...
2024-12-11 17:12:43.289068752  [2024-12-11 17:12:43] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2024-12-11 17:12:43.808576663  [2024-12-11 17:12:43] peewee_migrate.logs            INFO    : Starting migrations
2024-12-11 17:12:43.808801901  [2024-12-11 17:12:43] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-12-11 17:12:43.809294977  [2024-12-11 17:12:43] frigate.app                    INFO    : Running database vacuum
2024-12-11 17:12:45.780707178  [2024-12-11 17:12:45] frigate.app                    INFO    : Recording process started: 415
2024-12-11 17:12:45.786020837  [2024-12-11 17:12:45] frigate.app                    INFO    : Recording process started: 424
2024-12-11 17:12:45.789147449  [2024-12-11 17:12:45] frigate.app                    INFO    : go2rtc process pid: 118
2024-12-11 17:12:45.808733487  [2024-12-11 17:12:45] detector.tensorrt              INFO    : Starting detection process: 443
2024-12-11 17:12:47.165130805  [2024-12-11 17:12:45] frigate.app                    INFO    : Output process started: 445
2024-12-11 17:12:47.165380761  [2024-12-11 17:12:45] frigate.app                    INFO    : Camera processor started for garage_amcrestpoe: 460
2024-12-11 17:12:47.165460539  [2024-12-11 17:12:45] frigate.app                    INFO    : Camera processor started for doorbell_reolinkpoe: 461
2024-12-11 17:12:47.165539637  [2024-12-11 17:12:45] frigate.app                    INFO    : Camera processor started for front_reolinkpoe: 462
2024-12-11 17:12:47.165571930  [2024-12-11 17:12:45] frigate.app                    INFO    : Capture process started for garage_amcrestpoe: 463
2024-12-11 17:12:47.165654619  [2024-12-11 17:12:45] frigate.app                    INFO    : Capture process started for doorbell_reolinkpoe: 476
2024-12-11 17:12:47.165693157  [2024-12-11 17:12:45] frigate.app                    INFO    : Capture process started for front_reolinkpoe: 482
2024-12-11 17:12:47.165748737  [2024-12-11 17:12:45] frigate.app                    INFO    : Audio process started: 494
2024-12-11 17:12:47.433613653  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 148 MiB
2024-12-11 17:12:47.601813370  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 315, GPU 228 (MiB)
2024-12-11 17:12:47.608950859  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 317, GPU 238 (MiB)
2024-12-11 17:12:47.611479972  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +147, now: CPU 0, GPU 147 (MiB)
2024-12-11 17:12:47.617665884  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 169, GPU 230 (MiB)
2024-12-11 17:12:47.619177887  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 169, GPU 238 (MiB)
2024-12-11 17:12:47.619233878  [2024-12-11 17:12:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +19, now: CPU 0, GPU 166 (MiB)
```

### Relevant go2rtc log output

```shell
2024-12-11 17:12:37.776447862  [INFO] Preparing new go2rtc config...
2024-12-11 17:12:38.459883039  [INFO] Starting go2rtc...
2024-12-11 17:12:38.569296839  17:12:38.569 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-12-11 17:12:38.569302616  17:12:38.569 INF config path=/dev/shm/go2rtc.yaml
2024-12-11 17:12:38.571714807  17:12:38.569 INF [api] listen addr=:1984
2024-12-11 17:12:38.571718266  17:12:38.571 INF [rtsp] listen addr=:8554
2024-12-11 17:12:38.571719831  17:12:38.571 INF [webrtc] listen addr=:8555/tcp
2024-12-11 17:12:47.774824136  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"doorbell_reolinkpoe":{"audio_dBFS":-55.3363,"audio_rms":56.0577,"camera_fps":10.1,"capture_pid":476,"detection_enabled":true,"detection_fps":5.3,"ffmpeg_pid":483,"pid":461,"process_fps":10.1,"skipped_fps":0},"front_reolinkpoe":{"audio_dBFS":-33.8326,"audio_rms":666.5289,"camera_fps":5.1,"capture_pid":482,"detection_enabled":true,"detection_fps":0.8,"ffmpeg_pid":505,"pid":462,"process_fps":5.1,"skipped_fps":0},"garage_amcrestpoe":{"audio_dBFS":-49.5781,"audio_rms":108.7789,"camera_fps":5,"capture_pid":463,"detection_enabled":true,"detection_fps":0.5,"ffmpeg_pid":477,"pid":460,"process_fps":5,"skipped_fps":0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"108":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"118":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"9.1","cpu_average":"8","mem":"0.1"},"12878":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"13046":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"131":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"151":{"cmdline":"python3 -u -m frigate","cpu":"1.6","cpu_average":"2","mem":"1.9"},"157":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"181":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"182":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"183":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"191":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"207":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"319":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"36":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"367":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"37":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"38":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"39":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"40":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"415":{"cmdline":"frigate.recording_manager","cpu":"1.5","cpu_average":"1","mem":"0.8"},"42":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"424":{"cmdline":"frigate.review_segment_manager","cpu":"0.4","cpu_average":"0","mem":"0.7"},"43":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"44":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"442":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(58)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"443":{"cmdline":"frigate.detector.tensorrt","cpu":"5.9","cpu_average":"8","mem":"1.9"},"445":{"cmdline":"frigate.output       ","cpu":"36.7","cpu_average":"38","mem":"1.0"},"45":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"460":{"cmdline":"frigate.process:garage_amcrestpoe","cpu":"1.5","cpu_average":"2","mem":"0.8"},"461":{"cmdline":"frigate.process:doorbell_reolinkpoe","cpu":"4.1","cpu_average":"4","mem":"0.8"},"462":{"cmdline":"frigate.process:front_reolinkpoe","cpu":"1.5","cpu_average":"2","mem":"0.9"},"463":{"cmdline":"frigate.capture:garage_amcrestpoe","cpu":"7.5","cpu_average":"7","mem":"0.8"},"476":{"cmdline":"frigate.capture:doorbell_reolinkpoe","cpu":"8.6","cpu_average":"8","mem":"0.7"},"477":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_amcrestpoe -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage_amcrestpoe@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"15.7","cpu_average":"15","mem":"0.9"},"482":{"cmdline":"frigate.capture:front_reolinkpoe","cpu":"10.2","cpu_average":"10","mem":"0.8"},"483":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_reolinkpoe -r 10 -vf fps=10,scale_cuda=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.8","cpu_average":"8","mem":"0.7"},"494":{"cmdline":"frigate.audio_manager","cpu":"2.0","cpu_average":"1","mem":"0.8"},"505":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_reolinkpoe -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_reolinkpoe@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=4512:h=2512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"13.2","cpu_average":"13","mem":"1.2"},"506":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.10.30.90/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5b59a70e77b80240f0d7b1ed18f1ad2e","cpu":"1.7","cpu_average":"1","mem":"0.1"},"507":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_reolinkpoe_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/doorbell_reolinkpoe@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.1"},"516":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_amcrestpoe -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.6","cpu_average":"0","mem":"0.1"},"525":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.10.30.90/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b68816772e4ac02afd919f12ebf9032f","cpu":"0.4","cpu_average":"0","mem":"0.1"},"526":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_reolinkpoe_sub -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.2","cpu_average":"0","mem":"0.1"},"536":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_reolinkpoe -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.8","cpu_average":"0","mem":"0.1"},"552":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"557":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"562":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 4512x2512 -i pipe: -threads 1 -f mpegts -s 1293x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"567":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 3840x2160 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"19.4","cpu_average":"19","mem":"0.4"},"57":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"58":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"28.3","mem":"17.5"}},"detection_fps":6.6,"detectors":{"tensorrt":{"detection_start":0,"inference_speed":10.57,"pid":443}},"gpu_usages":{"NVIDIA GeForce GTX 1660":{"dec":"23.0%","enc":"0.0%","gpu":"10.0%","mem":"30.79%"}},"processes":{"audio_detector":{"pid":494},"go2rtc":{"pid":118},"logger":{"pid":367},"recording":{"pid":415},"review_segment":{"pid":424}},"service":{"last_updated":1733964621,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":962.8,"mount_type":"tmpfs","total":1024,"used":61.2},"/media/frigate/clips":{"free":425198.8,"mount_type":"fuse.shfs","total":1068277.2,"used":642842.3},"/media/frigate/recordings":{"free":425198.8,"mount_type":"fuse.shfs","total":1068277.2,"used":642842.3},"/tmp/cache":{"free":917,"mount_type":"tmpfs","total":953.7,"used":36.7}},"temperatures":{},"uptime":2256,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A, used Unraid's Community Applications to install
```

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/bf4c6c59-02cc-4c72-b792-5ff57b394359)

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/0fa38e70-fa1e-4689-8d01-d02f1b725614)
