### DISCUSSION TITLE
[Support]: Frigate+ Model not found after upgrade

### DISCUSSION THREAD

**Discussion by blaess** [blakeblackshear/frigate#15456] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After upgrading to Beta 3, Frigate does not start because of the following error.

FileNotFoundError: [Errno 2] No such file or directory: '/config/model_cache/f44b4011251f72f538afa19                                                                                            cb8acbab0'

Model path on Config:

model:
   path: plus://f44b4011251f72f538afa19cb8acbab0

I already had the same issue during the upgrade to Beta 1 AND Beta 2.

Workaround:
1) remove Frigate+ Model
2) start frigate
3) stop frigate
4) add Frigate+ Model
5) start frigate

### Steps to reproduce

1. Upgrade Frigate to latest Beta
2. Start Frigate (docker-compose up)
3.

...

### Version

0.15.0-beta3 - UI does not start

### Frigate config file

```yaml
# Required: mqtt configuration
mqtt:
  # Required: host name
  host: 192.168.1.32
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: loxberry
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}. 
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: XXXXXX

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

model:
   path: plus://f44b4011251f72f538afa19cb8acbab0

record:
  # Optional: Enable recording (default: shown below)
  enabled: true
  # Optional: Number of days to retain (default: shown below)
  retain:
    days: 0
    mode: motion
  # Optional: Event recording settings
  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
ffmpeg:
  # hwaccel_args: auto
  hwaccel_args: preset-intel-qsv-h264

# Optional: Global object filters for all cameras.
# NOTE: can be overridden at the camera level

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    #max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      # default: 3000
      # Optional: Object specific values
      # objects:
       # person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - face
    - bicycle
    - dog
    - cat
    - deer
    - hourse
    - bird
    - raccoon
    - fox
    - cow
    - squirrel
    - goat
    - package
    - waste_bin
    - bbq_grill
    - robot_lawnmower
    - umbrella
  filters:
    person:
      min_score: .65
      threshold: .75
    face:
      min_score: .6
    car:
      min_score: .65
      threshold: .75
    motorcycle:
      min_score: .65
      threshold: .75
    bicycle:
      min_score: .65
      threshold: .75
    license_plate:
      min_score: .5
    fedex:
      min_score: .75
    ups:
      min_score: .75
    dhl:
      min_score: .75
    dpd:
      min_score: .75
    dog:
      min_score: .65
      threshold: .75
    cat:
      min_score: .65
      threshold: .75
    deer:
      min_score: .65
      threshold: .75
    horse:
      min_score: .65
      threshold: .75
    bird:
      min_score: .65
      threshold: .75
    raccoon:
      min_score: .65
      threshold: .75
    fox:
      min_score: .65
      threshold: .75
    cow:
      min_score: .65
      threshold: .75
    squirrel:
      min_score: .65
      threshold: .75
    goat:
      min_score: .65
      threshold: .75
    rabbit:
      min_score: .65
      threshold: .75
    package:
      min_score: .65
      threshold: .75
    waste_bin:
      min_score: .65
      threshold: .75
    bbq_grill:
      min_score: .65
      threshold: .75
    robot_lawnmower:
      min_score: .65
      threshold: .75
    umbrella:
      min_score: .65
      threshold: .75

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 14
    # Optional: Per object retention days
    objects:
      person: 30
      car: 30
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

# Optional: jsmpeg stream configuration for WebUI
live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
  stream_name: camera_name
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

# Required: configuration section for cameras
cameras:
  # Required: name of the camera
  east:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: Source passed to ffmpeg after the -i parameter.
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
      inputs:
        - path: rtsp://192.168.1.20:554/11
          roles:
            - detect
            - record

    snapshots: # <----- Enable snapshots
      enabled: true

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: zones for this camera
    zones:
      # Required: name of the zone
      # NOTE: This must be different than any camera names, but can match with another zone on another
      #       camera.
      forecourt:
        # Required: List of x,y coordinates to define the polygon of the zone.
        # NOTE: Coordinates can be generated at https://www.image-map.net/
        coordinates: 0,1,1,1,1,0.643,0.832,0.363,0.75,0.21,0.729,0.14,0.622,0.12,0.508,0,0,0
        # Optional: Zone level object filters.
        # NOTE: The global and camera filters are applied upstream.
        #    filters:
        #      person:
        #        min_area: 5000
        #        max_area: 100000
        #        threshold: 0.8

        inertia: 1
        loitering_time: 0
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - car
        - motorcycle
        - license_plate
        - fedex
        - ups
        - dhl
        - dpd
        - person
        - face
        - bicycle
        - dog
        - cat
        - deer
        - hourse
        - bird
        - raccoon
        - fox
        - cow
        - squirrel
        - goat
        - package
        - waste_bin
        - bbq_grill
        - robot_lawnmower
        - umbrella

  # Required: name of the camera
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    detect:
      annotation_offset: -1500

  sud-east:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: Source passed to ffmpeg after the -i parameter.
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
      inputs:
        - path: rtsp://192.168.1.21:554/11
          roles:
            - detect
            - record

    snapshots: # <----- Enable snapshots
      enabled: true

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - rabbit
        - person
        - face
        - bicycle
        - dog
        - cat
        - deer
        - hourse
        - bird
        - raccoon
        - fox
        - cow
        - squirrel
        - goat
        - package
        - waste_bin
        - bbq_grill
        - umbrella

    motion:
      mask:
        - 1920,92,1726,0,1852,0,1920,0
        - 0,1080,218,1080,134,610,124,289,151,0,0,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  sud-west:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: Source passed to ffmpeg after the -i parameter.
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
      inputs:
        - path: rtsp://192.168.1.22:554/11
          roles:
            - detect
            - record

    snapshots: # <----- Enable snapshots
      enabled: true
    # Optional: motion mask
    # NOTE: see docs for more detailed info on creating masks
    #mask: poly,0,900,1080,900,1080,1920,0,1920

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - car
        - motorcycle
        - fedex
        - ups
        - dhl
        - dpd
        - rabbit
        - person
        - face
        - bicycle
        - dog
        - cat
        - deer
        - hourse
        - bird
        - raccoon
        - fox
        - cow
        - squirrel
        - goat
        - package
        - waste_bin
        - bbq_grill
        - umbrella

    motion:
      mask:
        - 0.632,0,0.999,0,0.999,0.612,0.927,0.703,0.825,0.425
        - 0.714,1,1,1,1,0.652
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  west:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: Source passed to ffmpeg after the -i parameter.
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
      inputs:
        - path: rtsp://192.168.1.23:554/11
          roles:
            - detect
            - record

    snapshots: # <----- Enable snapshots
      enabled: true

      # Optional: motion mask
      # NOTE: see docs for more detailed info on creating masks
      #mask: poly,0,900,1080,900,1080,1920,0,1920

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - car
        - motorcycle
        - fedex
        - ups
        - dhl
        - dpd
        - rabbit
        - person
        - face
        - bicycle
        - dog
        - cat
        - deer
        - hourse
        - bird
        - raccoon
        - fox
        - cow
        - squirrel
        - goat
        - package
        - waste_bin
        - bbq_grill
        - umbrella

    motion:
      mask: 0.41,0,0.168,0.067,0,0.143,0,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
camera_groups:
  Home:
    order: 1
    icon: LuCamera
    cameras:
      - east
      - sud-east
      - sud-west
      - west
version: 0.15-0
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:   
    frigate:
        container_name: frigate
        privileged: true
        restart: unless-stopped
        image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3
        shm_size: "512mb"
        devices:
            - /dev/bus/usb:/dev/bus/usb
        volumes:
            - /home/frigate/config/config.yml:/config/config.yml
            - /home/frigate/media:/media/frigate
            - /home/frigate:/db
            - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
              target: /tmp/cache
              tmpfs:
                size: 1000000000
        ports:
            - "5000:5000"
            - "1935:1935" # RTMP feeds
        environment:
            FRIGATE_RTSP_PASSWORD: "XXX"
            PLUS_API_KEY: XXXX
```

### Relevant Frigate log output

```shell
frigate@Frigate:~$ docker-compose up
Creating network "frigate_default" with the default driver
Creating frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service certsync-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service certsync-log successfully started
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | 2024-12-12 07:14:05.627061409  [INFO] Preparing new go2rtc config...
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | 2024-12-12 07:14:05.634299864  [INFO] Starting NGINX...
frigate    | 2024-12-12 07:14:05.635910423  [INFO] Preparing Frigate...
frigate    | 2024-12-12 07:14:05.642182750  [INFO] Starting Frigate...
frigate    | 2024-12-12 07:14:05.643484867  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate    | 2024-12-12 07:14:06.077067366  [INFO] Starting go2rtc...
frigate    | 2024-12-12 07:14:06.204798659  07:14:06.204 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate    | 2024-12-12 07:14:06.204864349  07:14:06.204 INF config path=/dev/shm/go2rtc.yaml
frigate    | 2024-12-12 07:14:06.205845176  07:14:06.205 INF [rtsp] listen addr=:8554
frigate    | 2024-12-12 07:14:06.205849480  07:14:06.205 INF [api] listen addr=:1984
frigate    | 2024-12-12 07:14:06.205990844  07:14:06.205 INF [webrtc] listen addr=:8555/tcp
frigate    | 2024-12-12 07:14:06.667184479  2024/12/12 07:14:06 [error] 169#169: *1 connect() failed (111: Connection refused) while connecting                                                                                              to upstream, client: 192.168.1.106, server: , request: "GET /ws HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "1                                                                                             92.168.1.29:5000"
frigate    | 2024-12-12 07:14:06.667205616  2024/12/12 07:14:06 [error] 169#169: *1 auth request unexpected status: 502 while sending to client,                                                                                              client: 192.168.1.106, server: , request: "GET /ws HTTP/1.1", host: "192.168.1.29:5000"
frigate    | 2024-12-12 07:14:06.667279180  192.168.1.106 - - [12/Dec/2024:07:14:06 +0000] "GET /ws HTTP/1.1" 500 579 "-" "Mozilla/5.0 (Windows                                                                                              NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
frigate    | 2024-12-12 07:14:06.681726809  2024/12/12 07:14:06 [error] 170#170: *3 connect() failed (111: Connection refused) while connecting                                                                                              to upstream, client: 192.168.1.116, server: , request: "GET /ws HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "1                                                                                             92.168.1.29:5000"
frigate    | 2024-12-12 07:14:06.681730883  2024/12/12 07:14:06 [error] 170#170: *3 auth request unexpected status: 502 while sending to client,                                                                                              client: 192.168.1.116, server: , request: "GET /ws HTTP/1.1", host: "192.168.1.29:5000"
frigate    | 2024-12-12 07:14:06.681776344  192.168.1.116 - - [12/Dec/2024:07:14:06 +0000] "GET /ws HTTP/1.1" 500 579 "-" "Mozilla/5.0 (Windows                                                                                              NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
frigate    | 2024-12-12 07:14:06.713653182  2024/12/12 07:14:06 [error] 172#172: *5 connect() failed (111: Connection refused) while connecting                                                                                              to upstream, client: 192.168.1.106, server: , request: "GET /api/review?limit=10&severity=alert HTTP/1.1", subrequest: "/auth", upstream: "http:                                                                                             //127.0.0.1:5001/auth", host: "192.168.1.29:5000", referrer: "http://192.168.1.29:5000/"
frigate    | 2024-12-12 07:14:06.713674279  2024/12/12 07:14:06 [error] 172#172: *5 auth request unexpected status: 502 while sending to client,                                                                                              client: 192.168.1.106, server: , request: "GET /api/review?limit=10&severity=alert HTTP/1.1", host: "192.168.1.29:5000", referrer: "http://192.                                                                                             168.1.29:5000/"
frigate    | 2024-12-12 07:14:06.713777374  192.168.1.106 - - [12/Dec/2024:07:14:06 +0000] "GET /api/review?limit=10&severity=alert HTTP/1.1" 50                                                                                             0 579 "http://192.168.1.29:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.                                                                                             36" "-"
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service certsync: starting
frigate    | s6-rc: info: service certsync successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2024-12-12 07:14:07.586497959  [INFO] Starting certsync...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2024-12-12 07:14:07.726444138  127.0.0.1 - - [12/Dec/2024:07:14:07 +0000] "" 400 0 "-" "-" "-"
frigate    | 2024-12-12 07:14:07.934956835  2024/12/12 07:14:07 [error] 169#169: *9 connect() failed (111: Connection refused) while connecting                                                                                              to upstream, client: 192.168.1.116, server: , request: "GET /live/jsmpeg/sud-west HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:50                                                                                             01/auth", host: "192.168.1.29:5000"
frigate    | 2024-12-12 07:14:07.934961055  2024/12/12 07:14:07 [error] 169#169: *9 auth request unexpected status: 502 while sending to client,                                                                                              client: 192.168.1.116, server: , request: "GET /live/jsmpeg/sud-west HTTP/1.1", host: "192.168.1.29:5000"
frigate    | 2024-12-12 07:14:07.934992047  192.168.1.116 - - [12/Dec/2024:07:14:07 +0000] "GET /live/jsmpeg/sud-west HTTP/1.1" 500 579 "-" "Moz                                                                                             illa/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
frigate    | 2024-12-12 07:14:08.321865063  [2024-12-12 07:14:08] frigate.util.config            INFO    : Checking if frigate config needs migr                                                                                             ation...
frigate    | 2024-12-12 07:14:08.393537752  [2024-12-12 07:14:08] frigate.util.config            INFO    : frigate config does not need migratio                                                                                             n...
frigate    | 2024-12-12 07:14:10.846523066  Traceback (most recent call last):
frigate    | 2024-12-12 07:14:10.846539840    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate    | 2024-12-12 07:14:10.846542131      return _run_code(code, main_globals, None,
frigate    | 2024-12-12 07:14:10.846545781    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate    | 2024-12-12 07:14:10.846547763      exec(code, run_globals)
frigate    | 2024-12-12 07:14:10.846549143    File "/opt/frigate/frigate/__main__.py", line 64, in <module>
frigate    | 2024-12-12 07:14:10.846599963      main()
frigate    | 2024-12-12 07:14:10.846601501    File "/opt/frigate/frigate/__main__.py", line 35, in main
frigate    | 2024-12-12 07:14:10.846603354      config = FrigateConfig.load(install=True)
frigate    | 2024-12-12 07:14:10.846618307    File "/opt/frigate/frigate/config/config.py", line 668, in load
frigate    | 2024-12-12 07:14:10.846619725      return FrigateConfig.parse(f, **kwargs)
frigate    | 2024-12-12 07:14:10.846621115    File "/opt/frigate/frigate/config/config.py", line 696, in parse
frigate    | 2024-12-12 07:14:10.846663830      return cls.parse_object(config, **context)
frigate    | 2024-12-12 07:14:10.846665434    File "/opt/frigate/frigate/config/config.py", line 706, in parse_object
frigate    | 2024-12-12 07:14:10.846667203      return cls.model_validate(
frigate    | 2024-12-12 07:14:10.846668769    File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 568, in model_validate
frigate    | 2024-12-12 07:14:10.846685696      return cls.__pydantic_validator__.validate_python(
frigate    | 2024-12-12 07:14:10.846687241    File "/opt/frigate/frigate/config/config.py", line 588, in post_validation
frigate    | 2024-12-12 07:14:10.846688914      self.model.check_and_load_plus_model(self.plus_api)
frigate    | 2024-12-12 07:14:10.846690451    File "/opt/frigate/frigate/detectors/detector_config.py", line 127, in check_and_load_plus_model
frigate    | 2024-12-12 07:14:10.846692040      with open(self.path, "wb") as f:
frigate    | 2024-12-12 07:14:10.846693632  FileNotFoundError: [Errno 2] No such file or directory: '/config/model_cache/f44b4011251f72f538afa19                                                                                             cb8acbab0'
frigate    | 2024-12-12 07:14:11.175139268  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | s6-rc: info: service certsync: stopping
frigate    | 2024-12-12 07:14:11.185149463  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2024-12-12 07:14:11.186601282  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate    | s6-rc: info: service certsync successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service certsync-log: stopping
frigate    | s6-rc: info: service certsync-log successfully stopped
frigate    | 2024-12-12 07:14:11.294162620  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | 2024-12-12 07:14:11.302901534  exit with signal: terminated
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | 2024-12-12 07:14:11.307565622  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Instar IN-9008

### Screenshots of the Frigate UI's System metrics pages

N/A
