### DISCUSSION TITLE
[Detector Support]: Why is my CPU maxed out when upgrading from 0.13 to 0.14 ?

### DISCUSSION THREAD

**Discussion by jmccroha** [blakeblackshear/frigate#15457] [Detector Support] [answered]
### Describe the problem you are having

Hi all,

Your help would be greatly appreciated for a performance issue I'm experiencing with Frigate.
I had a stable 0.13 release running about a year ago on a dedicated NUC (Debian bullseye) with a USB Coral TPU and five ethernet-connected cameras.  I then had to put everything into storage while we renovated our home and 9 months later, updated everything to 0.14..  Wow!  What an upgrade!  I love the new interface, as does my wife.

However, I have been plagued with performance issues and had to remove one of my cameras to reduce the load and prevent the system complaining that it was unable to keep up with the task of copying to storage (see log extract below).  I'm recording the streams to a Synology 2423+ NAS over a gigabit ethernet connection, so I very much doubt that I have a storage bottleneck.  At the bottom of the web interface, I was seeing "CPU 99%" "Intel GPU 3%". at the time of the problem.  Now, with only four cameras, I'm still at 70% CPU constantly.

Despite the fact that Frigate claims to have found the TPU on startup, I can't help feeling that the NUC's CPU is doing all the work.  I don't understand the metrics pages, and can't see where the problem is.

Can someone help?  My objective is to have 6 cameras running on this system, and I don't believe it's under-specced for the task.

![image](https://github.com/user-attachments/assets/c8673979-36e2-44ad-9193-701df2f43726)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/jmccroha/Documents/frigate/config/config.yml:/config/config.yml:rw
#      - /home/jmccroha/Documents/frigate/config/go2rtc:/config/go2rtc
      - /media/nvr/frigate:/media/frigate
      - /media/footage:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### docker-compose file or Docker CLI command

```yaml
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistant
  password: *password*
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

##########################################################################

#auth:
#  reset_admin_password: true

database:
  path: /db/frigate.db

go2rtc:
  streams:
    terrasse_main:
      - rtsp://login:password@192.168.1.10:554/media/video1
    terrasse_sub:
      - rtsp://login:password@192.168.1.10:554/media/video0
    doorbell_main:
#      - rtsp://login:password@192.168.1.6:554/h264Preview_01_main
      - ffmpeg:http://192.168.1.6/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=login&password=password#video=copy#audio=copy#audio=opus
      - rtsp://login:password@192.168.1.6/Preview_01_sub
    doorbell_sub:
#      - rtsp://login:password@192.168.1.6:554/h264Preview_01_sub
#      - ffmpeg:rtsp://login:password@192.168.1.6:554/h264Preview_01_sub
      - ffmpeg:http://192.168.1.6/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=password
    rooftop_main:
      - rtsp://login:password@192.168.1.7:554/cam/realmonitor?channel=1&subtype=0
    rooftop_sub:
      - rtsp://login:password@192.168.1.7:554/cam/realmonitor?channel=1&subtype=1
    camavant_main:
      - rtsp://login:password@192.168.1.12:554/h264Preview_01_main
    camavant_sub:
      - rtsp://login:password@192.168.1.12:554/h264Preview_01_sub

  restream:
    force_audio: false
  ffmpeg:
    hwaccel_args: preset-vaapi
#     rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
#      -rtsp_transport tcp -i {input}

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 2
    post_capture: 2
    retain:
      default: 14
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 10
    objects:
      person: 14

birdseye:
  enabled: true
  mode: continuous

##########################################################################

logger:
  default: info
#  logs:
#    frigate.record.maintainer: error

cameras:  # Camera 1
  terrasse:
    ffmpeg:
      inputs:
        # High resolution stream and role
        - path: rtsp://127.0.0.1:8554/terrasse_main
          input_args: preset-rtsp-restream
          roles:
            - record
        # Low resolution stream and role
        - path: rtsp://127.0.0.1:8554/terrasse_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask:
        - 0.1,0.686,0.129,0.841,0.077,1,0,1,0,0,0.388,0.004,0.4,0.239,0.311,0.419,0.176,0.728
        - 0.487,0.002,0.517,0.088,0.61,0.093,0.637,0.165,0.786,0.367,0.992,0.775,0.993,0
    mqtt:
      required_zones:
        - deck

    record:
      enabled: true
    snapshots:
      required_zones:
        - deck

    zones:
      deck:
        coordinates:
          0.125,0.831,0.104,0.684,0.169,0.724,0.305,0.432,0.402,0.245,0.392,0.004,0.483,0.004,0.516,0.088,0.612,0.09,0.638,0.166,0.782,0.362,0.992,0.773,0.998,0.998,0.08,1,0.105,0.91
        loitering_time: 0
        objects: person
        inertia: 3
    detect:
      width: 1280
      height: 720
      fps: 5

    review: {}
  doorbell:  # Camera 2
    ffmpeg:
      inputs:
        # High resolution stream and role
        - path: rtsp://127.0.0.1:8554/doorbell_main
          input_args: preset-rtsp-restream
          roles:
            - record
        # Low resolution stream and roles
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask:
        0,0.492,0.193,0.453,0.362,0.406,0.543,0.406,0.654,0.61,0.798,0.609,0.737,1,1,1,1,0,0,0,0,0.265
    zones:
      shore:
        coordinates:
          0.736,1,0,1,0,0.498,0.165,0.46,0.361,0.407,0.541,0.409,0.659,0.611,0.795,0.607,0.78,0.779
        inertia: 3
        loitering_time: 0
        objects: person
    mqtt:
      required_zones:
        - shore

    record:
      enabled: true
    snapshots:
      required_zones:
        - shore

    detect:
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        required_zones: shore
  rooftop:  # Camera 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rooftop_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rooftop_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask:
        0,0.275,0.067,0.235,0.126,0.201,0.185,0.176,0.214,0.188,0.349,0.232,0.58,0.33,1,0.578,1,0,0,0
    mqtt:
      required_zones:
        - roof

    zones:
      roof:
        coordinates: 0,720,1280,720,1280,422,1075,350,647,216,302,146,246,0,0,0,0,316
        objects:
          - person

    record:
      enabled: true
    snapshots:
      required_zones:
        - roof

    detect:
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        required_zones:
          - roof
  camavant:  # Camera 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camavant_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camavant_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask:
        1,0,0,0,0,0.667,0.239,0.455,0.355,0.402,0.539,0.374,0.777,0.464,0.892,0.522,1,0.682,1,1,1,0
    mqtt:
      required_zones:
        - pic-avant

    zones:
      pic-avant:
        coordinates:
          0.54,0.379,0.776,0.465,0.892,0.525,1,0.689,1,1,0,1,0,0.667,0.238,0.464,0.347,0.408
        inertia: 3
        loitering_time: 0
        objects: person
    record:
      enabled: true
    snapshots:
      required_zones:
        - pic-avant

    detect:
      width: 1280
      height: 720

    review:
      alerts: {}
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuCamera
    cameras: birdseye
```

### Relevant Frigate log output

```shell
WARNING : Unable to keep up with recording segments in cache for Camxx. Keeping the 5 most recent segments out of 6 and discarding the rest..
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b4c57baf-dd74-4bcf-baa9-26d7bcf0466b)

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/4c806d66-2496-4c68-b38c-64fd8e42b964)
