### DISCUSSION TITLE
[HW Accel Support]: ERROR   : Unrecognized option 'preset-nvidia-h264'.

### DISCUSSION THREAD

**Discussion by miczlo** [blakeblackshear/frigate#15461] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Getting ERROR   : Unrecognized option 'preset-nvidia-h264'.

I'm trying to migrate frigate from current host with coral to another with an nvidia gpu. I might move to new host with coral but wanted to compare as my CPU is running out of juice on old one.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.30
  client_id: frigate
  user: mqtt_frigate
  password: '{FRIGATE_MQTT_PASSWORD}'

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.50.70:554/h264Preview_01_main #doorbell
      - ffmpeg:back#video=h264 #tried getting rid of this
  webrtc:
    listen: :8555
    candidates:
      - 192.168.50.242:8555   # <--- enter frigate host IP here
      - stun:8555
database:
  path: /config/frigate.db
detectors:
  tensorrt: #tried nvidia here as well
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320


detect:
  fps: 5

cameras:
  doorbell:
    audio:
      enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.50.70:554/h264Preview_01_sub
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/doorbell #tried getting rid of this as well
          roles:
            - record
    detect:
      width: 640
      height: 480
    record:
      enabled: true
    objects:
      track:
        - person
        - cat
        - car
        - dog








    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
    # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
    # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
    # Optional: crop the snapshot (default: shown below)
  crop: false

    # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
    # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 60
      # Optional: Per object retention days
    objects:
      person: 90
ffmpeg:
  hwaccel_args: #Intel <10th gen Quicksync
    - -preset-nvidia-h264
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 14
    mode: all
  events:
    #max_seconds: 500
    pre_capture: 20
    post_capture: 20
    retain:
      default: 21
      mode: active_objects
      objects:
        person: 30
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "128mb" # update for your cameras based on calculation above

    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - ./cctv_clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host
    environment:
#variables
```

### Relevant Frigate log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | No models to convert.
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service trt-model-prepare successfully started
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2024-12-12 10:58:28.241180197  [INFO] Preparing new go2rtc config...
frigate  | 2024-12-12 10:58:28.241890360  [INFO] Starting NGINX...
frigate  | 2024-12-12 10:58:28.243690456  [INFO] Preparing Frigate...
frigate  | 2024-12-12 10:58:28.246317762  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2024-12-12 10:58:28.250013340  [INFO] Starting Frigate...
frigate  | 2024-12-12 10:58:28.476000175  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
frigate  | 2024-12-12 10:58:28.502967974  [INFO] Starting go2rtc...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | 2024-12-12 10:58:28.513477290  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-12-12 10:58:28.595616070  10:58:28.594 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2024-12-12 10:58:28.595619265  10:58:28.594 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2024-12-12 10:58:28.595622925  10:58:28.594 INF [rtsp] listen addr=:8554
frigate  | 2024-12-12 10:58:28.595624488  10:58:28.595 INF [webrtc] listen addr=:8555
frigate  | 2024-12-12 10:58:28.595625833  10:58:28.595 INF [api] listen addr=:1984
frigate  | 2024-12-12 10:58:28.603006180  127.0.0.1 - - [12/Dec/2024:10:58:28 +0000] "" 400 0 "-" "-" "-"
frigate  | 2024-12-12 10:58:29.475049310  [2024-12-12 10:58:29] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
frigate  | 2024-12-12 10:58:29.475103291  [2024-12-12 10:58:29] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2024-12-12 10:58:29.490037638  [2024-12-12 10:58:29] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2024-12-12 10:58:29.605200950  [2024-12-12 10:58:29] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2024-12-12 10:58:29.605664900  [2024-12-12 10:58:29] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2024-12-12 10:58:29.610278123  [2024-12-12 10:58:29] frigate.app                    INFO    : Recording process started: 347
frigate  | 2024-12-12 10:58:29.614941622  [2024-12-12 10:58:29] frigate.app                    INFO    : Recording process started: 356
frigate  | 2024-12-12 10:58:29.616922111  [2024-12-12 10:58:29] frigate.app                    INFO    : go2rtc process pid: 104
frigate  | 2024-12-12 10:58:29.633455229  [2024-12-12 10:58:29] detector.nvidia                INFO    : Starting detection process: 376
frigate  | 2024-12-12 10:58:30.689942618  [2024-12-12 10:58:29] frigate.app                    INFO    : Output process started: 378
frigate  | 2024-12-12 10:58:30.690134912  [2024-12-12 10:58:29] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
frigate  | 2024-12-12 10:58:30.690136434  [2024-12-12 10:58:29] frigate.app                    INFO    : Camera processor started for doorbell: 393
frigate  | 2024-12-12 10:58:30.690140147  [2024-12-12 10:58:29] frigate.app                    INFO    : Capture process started for doorbell: 399
frigate  | 2024-12-12 10:58:30.690141264  [2024-12-12 10:58:29] frigate.app                    INFO    : Audio process started: 410
frigate  | 2024-12-12 10:58:30.690158392  [2024-12-12 10:58:29] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-12-12 10:58:30.760132305  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 72 MiB
frigate  | 2024-12-12 10:58:30.854991554  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 212, GPU 169 (MiB)
frigate  | 2024-12-12 10:58:30.859151310  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 213, GPU 179 (MiB)
frigate  | 2024-12-12 10:58:30.867778529  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +70, now: CPU 0, GPU 70 (MiB)
frigate  | 2024-12-12 10:58:30.867897642  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 142, GPU 171 (MiB)
frigate  | 2024-12-12 10:58:30.867900181  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 142, GPU 179 (MiB)
frigate  | 2024-12-12 10:58:30.867901572  [2024-12-12 10:58:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +15, now: CPU 0, GPU 85 (MiB)
frigate  | 2024-12-12 10:58:38.241487610  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-12-12 10:58:49.687085351  [2024-12-12 10:58:49] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
frigate  | 2024-12-12 10:58:49.687226481  [2024-12-12 10:58:49] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2024-12-12 10:58:49.687228325  [2024-12-12 10:58:49] ffmpeg.doorbell.detect         ERROR   : Unrecognized option 'preset-nvidia-h264'.
frigate  | 2024-12-12 10:58:49.687229450  [2024-12-12 10:58:49] ffmpeg.doorbell.detect         ERROR   : Error splitting the argument list: Option not found
frigate  | 2024-12-12 10:58:49.695723926  [2024-12-12 10:58:49] ffmpeg.doorbell.record         ERROR   : Unrecognized option 'preset-nvidia-h264'.
frigate  | 2024-12-12 10:58:49.695873768  [2024-12-12 10:58:49] ffmpeg.doorbell.record         ERROR   : Error splitting the argument list: Option not found
frigate  | 2024-12-12 10:58:49.695875825  [2024-12-12 10:58:49] watchdog.doorbell              INFO    : Terminating the existing ffmpeg process...
frigate  | 2024-12-12 10:58:49.695876917  [2024-12-12 10:58:49] watchdog.doorbell              INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2024-12-12 10:58:49.699030190  [2024-12-12 10:58:49] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
frigate  | 2024-12-12 10:58:49.699080499  [2024-12-12 10:58:49] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | 2024-12-12 10:58:54.948037618  192.168.50.1 - - [12/Dec/2024:10:58:54 +0000] "GET /api/doorbell/latest.webp?h=330&cache=1734001136408 HTTP/1.1" 200 3374 "http://192.168.50.242:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
```

### Relevant go2rtc log output

```shell
2024-12-12 10:59:55.310266047  [INFO] Preparing new go2rtc config...
2024-12-12 10:59:55.534405592  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-12-12 10:59:55.560115095  [INFO] Starting go2rtc...
2024-12-12 10:59:55.698072511  10:59:55.698 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-12-12 10:59:55.698640703  10:59:55.698 INF config path=/dev/shm/go2rtc.yaml
2024-12-12 10:59:55.698643562  10:59:55.698 INF [rtsp] listen addr=:8554
2024-12-12 10:59:55.699270242  10:59:55.698 INF [api] listen addr=:1984
2024-12-12 10:59:55.699272491  10:59:55.698 INF [webrtc] listen addr=:8555
2024-12-12 11:00:05.310527165  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:password@192.168.50.70:554/h264Preview_01_sub
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:password@192.168.50.70:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 10 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Install method

Proxmox via TTeck Script

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

Reolink doorbell

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/bc2af0f0-5551-46b8-8b82-89098df5a623)

### Any other information that may be helpful
```
root@frigate:/opt# nvidia-smi
Thu Dec 12 11:05:12 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A2000 Laptop GPU    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0            752W /   80W |       1MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```
---------------------------------
```
root@frigate:/opt# nvidia-container-runtime --version
NVIDIA Container Runtime version 1.16.1
commit: a470818ba7d9166be282cd0039dd2fc9b0a34d73
spec: 1.2.0

runc version 1.1.13
commit: v1.1.13-0-g58aa920
spec: 1.0.2-dev
go: go1.22.6
libseccomp: 2.5.4
```
---------------------------------
```
root@frigate:/opt# docker info | grep Runtimes
 Runtimes: io.containerd.runc.v2 nvidia runc
```
------------------------------------
```
root@frigate:/opt# ffmpeg -decoders | grep cuvid
ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
 V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)
```

EDIT:
- Tried [0.15.0 Beta 3](https://github.com/blakeblackshear/frigate/releases/tag/v0.15.0-beta3) but same deal so must be me doing something wrong
