### DISCUSSION TITLE
[Bug]: Modifying motion tuning from the UI creates a config that violates the schema

### DISCUSSION THREAD

**Discussion by cryptk** [blakeblackshear/frigate#15478] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When modifying the motion tuning settings from the UI, when you save them, the improve_contrast setting is saved as the string value `'true'` rather than the boolean value `true`. Even if improve_contrast is already set to the correct (according to the yaml schema) boolean value, as soon as you click either Reset or Save in the Motion Tuning UI, the value will be changed to a string, so even if I fix it, the next time I adjust the motion tuning settings, the schema violation notification will come back in the configuration UI.

### Steps to reproduce

1. Modify the Motion Tuning settings for a camera
2. Click Save
3. View the frigate configuration via the Configuration editor UI
4. Observe the schema violation warning about improve_contrast being set to `'true'` rather than `true`

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

All

### Frigate config file

```yaml
version: 0.14

model:
  path: plus://REDACTED

mqtt:
  enabled: true
  user: REDACTED
  password: REDACTED
  host: REDACTED

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    doorbell:
      - REDACTED
    doorbell_medium:
      - REDACTED
    doorbell_low:
      - REDACTED
    doorbell_package:
      - REDACTED
    garage:
      - REDACTED
    garage_medium:
      - REDACTED
    garage_low:
      - REDACTED
    front_yard:
      - REDACTED
    front_yard_medium:
      - REDACTED
    front_yard_low:
      - REDACTED
    back_porch:
      - REDACTED
    back_porch_medium:
      - REDACTED
    back_porch_low:
      - REDACTED

cameras:
  garage:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_medium
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: garage
    objects:
      track:
        - car
        - dog
        - motorcycle
        - person
      filters:
        person:
          threshold: 0.8
        car:
          min_score: 0.1
          threshold: 0.2
    motion:
      mask:
        - 0.265,0.037,0.265,0,0,0,0,0.036
        - 0.637,0.353,0.502,0.532,0.502,0.586,0.738,0.527,0.878,0.456,0.845,0.363,0.742,0.334
  doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: doorbell
    motion:
      mask:
        - 0.289,0.032,0.289,0,0.002,0.001,0,0.034
        - 0.587,0.453,0.56,0.456,0.544,0.48,0.539,0.514,0.539,0.55,0.551,0.571,0.573,0.57,0.588,0.546
      threshold: 32
      contour_area: 10
    objects:
      track:
        - car
        - dog
        - cat
        - motorcycle
        - person
        - package
        - face
  doorbell_package:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_package
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - dog
        - cat
        - package
  front_yard:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_medium
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_yard
    objects:
      track:
        - car
        - dog
        - cat
        - motorcycle
        - person
        - face
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dhl
    zones:
      Driveway:
        coordinates: 
          0.166,0.45,0.142,0.552,0.129,0.72,0.162,0.892,0.211,1,0.834,1,0.917,0.732,0.992,0.432,0.839,0.34,0.719,0.288,0.618,0.222,0.546,0.287,0.373,0.374
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Driveway
    motion:
      mask:
        - 0.658,0,0.677,0.124,0.818,0.138,0.863,0.081,0.889,0
        - 0.995,0.112,0.925,0.104,0.903,0.187,0.929,0.251,0.974,0.266
        - 0,0,0,0.047,0.292,0.044,0.291,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'  # <-- this is the value that shouldn't have quotes
  back_porch:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_porch_medium
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: back_porch
    objects:
      track:
        - dog
        - cat
        - person
      filters:
        person:
          mask: 0.468,0,0.495,0.322,0.571,0.317,0.538,0
    motion:
      mask: 0.295,0.037,0.295,0,0,0,0,0.039
record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 30

snapshots:
  enabled: true

review:
  detections:
    labels:
      - car
      - dog
      - motorcycle
      - person

objects:
  track:
    - car
    - dog
    - motorcycle
    - person
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

birdseye:
  enabled: true
  mode: motion
  restream: true

detectors:
  coral:
    type: edgetpu
    device: pci

camera_groups:
  Overview:
    order: 1
    icon: LuEye
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
N/A for this issue
```

### Relevant Frigate log output

```shell
None, this is just a nuisance in the configuration editor
```

### Relevant go2rtc log output

```shell
None, this is just a nuisance in the configuration editor
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

unifi protect, various models

### Screenshots of the Frigate UI's System metrics pages

N/A for this issue

### Any other information that may be helpful

This isn't an error as far as I can tell. It does seem like Frigate happily interprets the string 'true' as a truthy boolean value.  It's mostly just annoying to see the yellow squiggly line under the value.  Also, you would think that frigate itself should generate 100% schema-valid configurations.
