### DISCUSSION TITLE
[Camera Support]: reolink https / tls

### DISCUSSION THREAD

**Discussion by tbowmo** [blakeblackshear/frigate#15475] [Camera Support]
### Describe the problem you are having

Been trying to get go2rtc working on my reolink RLC-520A cameras the last couple of days, trying lots of different settings. Most of them suggest using go2rtc and http protocol to connect to the cameras, which keeps failing for me.

So I finally found the logs for go2rtc, and found the following log

```
error="streams: Get \"https://192.168.x.x\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.3.121 because it doesn't contain any IP SANs" stream=syd
```

It fails, because the cameras automatically tries to upgrade to TLS with a selfsigned certificate. So should I just switch to HTTP on the camera, or is there something missing in my configuration?

Ps. tried the config from here: https://docs.frigate.video/configuration/camera_specific/#reolink-cameras

My config is a mess, because I'm trying different settings.

### Version

0.15.0-e76f4e9

### What browser(s) are you using?

Firefox 133.0.3 (64-bit)

### Frigate config file

```yaml
ui:
  time_format: 24hour

tls:
  enabled: false

mqtt:
  enabled: true
  host: 192.168.3.117
  user: mqtt
  password: SuperSecretPassword

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: objects
  width: 1280
  height: 720
  restream: true
  layout:
    max_cameras: 2

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog
    - hat
    - backpack
    - handbag
    - cell phone
    - umbrella

go2rtc:
  streams:
    syd:
      #- ffmpeg:http://192.168.3.121/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy
      #- rtsp://admin:password@192.168.3.121:554/h265Preview_01_main
      #- ffmpeg:syd#video=h264#hardware
      http://192.168.3.121/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    #syd_sub:
      #- ffmpeg:http://192.168.3.121/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}
      #- rtsp://admin:password@192.168.3.121:554/h264Preview_01_sub
      #- ffmpeg:syd_sub#hardware
    nord:
      #- ffmpeg:http://192.168.3.122/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy
      - rtsp://admin:password@192.168.3.122:554/h265Preview_01_main
      - ffmpeg:nord#video=h264#hardware
    nord_sub:
      #- ffmpeg:http://192.168.3.122/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}
      - rtsp://admin:password@192.168.3.122:554/h264Preview_01_sub
      - ffmpeg:nord_sub#hardware

    syd_laden: 
      - ffmpeg:http://192.168.3.111/cgi-bin/hi3510/snap.cgi?&-getstream&-chn=1#video=h264#hardware
    nord_laden: 
      - ffmpeg:http://192.168.3.112/cgi-bin/hi3510/snap.cgi?&-getstream&-chn=1#video=h264#hardware
  webrtc:
    candidates:
      - 46.32.147.198:8555
      - 192.168.1.72:8555

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  retain:
    default: 30
ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  syd: # <------ Name the camera
    ui:
      order: 1
    enabled: true
    ffmpeg:
      inputs:
        - path: http://192.168.3.122/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/syd
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask: 0,0,0.999,0,1,0.187,0,0.273
    birdseye:
      order: 1
    zones:
      Frondoor:
        coordinates: 1,0.649,1,0.274,0.478,0.253,0,0.417
        inertia: 3
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - motorcycle
          - person
          - cell phone
          - handbag
          - hat
          - umbrella
          - backpack
      Driveway:
        coordinates: 0,0.486,1,0.656,0.998,0.998,0.001,0.998
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        car:
          mask:
            - 0.113,0.727,0.625,0.843,0.627,1,0.142,1
            - 0.998,0.437,1,0.586,0.774,0.528,0.798,0.4
            - 0.402,0.272,0.378,0.455,0.478,0.489,0.643,0.39,0.658,0.264
    review:
      alerts:
        required_zones: Driveway
  nord: # <------ Name the camera
    ui:
      order: 2
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nord_sub 
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/nord
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 0.156,0,1,0,1,0.186,0.852,0.286,0.242,0.205
        - 0.702,0.667,0.569,1,1,1,1,0.541
      threshold: 30
      contour_area: 10
      improve_contrast: true
    birdseye:
      order: 2
    zones:
      Frontdoor:
        coordinates: 0,0.222,0.416,0.218,0.407,0.492,0,0.662
        inertia: 3
        loitering_time: 0
        objects:
          - bicycle
          - backpack
          - cat
          - cell phone
          - dog
          - handbag
          - hat
          - motorcycle
          - person
          - umbrella
      Driveway:
        coordinates: 0.418,0.219,0.412,0.495,0,0.672,0,1,1,1,1,0.218
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: Driveway
    objects:
      filters:
        car:
          mask:
            - 0,0.399,0.35,0.3,0.403,0.406,0.052,0.522
            - 0.632,0.67,0.861,0.653,0.838,0.898,0.627,0.887
  syd_laden:
    ui:
      order: 3
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/syd_laden
          roles:
            - detect
    birdseye:
      order: 3
    zones: {}
    review: {}
    objects:
      filters:
        car:
          mask: 0.787,0.148,0.995,0.175,0.988,0.464,0.769,0.406
        person:
          mask: 0.758,0.69,0.927,0.686,0.957,1,0.763,0.991
  nord_laden:
    ui:
      order: 4
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nord_laden
          roles:
            - detect
    birdseye:
      enabled: false
    zones:
      Porten:
        coordinates: 0,0,0.459,0,0.473,0.564,0.282,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: Porten
      detections:
        required_zones: Porten
    objects:
      filters:
        car:
          mask: 0,0,1,0,1,1,0,1
version: 0.15-0
camera_groups:
  Birdseye:
    order: 1
    icon: LuAirplay
    cameras: birdseye
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
|                     |               | 
error | 2024-12-12 20:44:45 | frigate.video | syd: Unable to read frames from ffmpeg process.
error | 2024-12-12 20:44:45 | frigate.video | syd: ffmpeg process is not running. exiting capture thread...
```

### Relevant go2rtc log output

```shell
2024-12-12 20:40:53.092203354  20:40:53.092 WRN [rtsp] error="streams: Get \"https://192.168.3.121\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.3.121 because it doesn't contain any IP SANs" stream=syd
```

### FFprobe output from your camera

```shell
thomas at huginn in ~ 
>docker exec -it d39 /bin/sh
# ffprobe
/bin/sh: 1: ffprobe: not found
#
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-520A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/3421a143-df2f-4045-8753-05947369c230)
