### DISCUSSION TITLE
[Camera Support]: No audio on anjvision 4MP 48V PoE

### DISCUSSION THREAD

**Discussion by decimoseptimo** [blakeblackshear/frigate#15485] [Camera Support] [answered]
### Describe the problem you are having

camera_1 is fine. camera_2 records with no audio and its live view seems to be a low quality (the substream?) jsmpeg.
All 4 streams rtsp URLs works ok on VLC (video and audio).

the only config that works is
`      # - rtsp://admin:123456@192.168.0.202:554/Stream0#media=video`

So it seems it doesn't like the camera's audio. I saw some erros on the probe, perhaps that's related?

### Version

14.1

### What browser(s) are you using?

chrome 131

### Frigate config file

```yaml
# yaml-language-server: $schema=http://localhost:5000/api/config/schema.json
mqtt:
  host: mosquitto
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  # hwaccel_args: preset-intel-qsv-h265
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    camera_1:
      - rtsp://admin:XXX@192.168.0.201:554/Streaming/Channels/101
    camera_1_sub:
      - rtsp://admin:XXX@192.168.0.201:554/Streaming/Channels/103
    camera_2:
      # - rtsp://admin:123456@192.168.0.202:554/Stream0
      # - "ffmpeg:camera_2#audio=aac"
      # - rtsp://admin:123456@192.168.0.202:554/Stream0#media=video
      - rtsp://admin:123456@192.168.0.202:554/Stream0#audio=aac
      # - "ffmpeg:rtsp://admin:123456@192.168.0.202:554/Stream0#video=copy#audio=aac"
    camera_2_sub:
      # - rtsp://admin:123456@192.168.0.202:554/Stream1
      - rtsp://admin:123456@192.168.0.202:554/Stream1#media=video
      # - "ffmpeg:camera_2_sub#audio=opus"
cameras:
  camera_1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_1_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
        - motorcycle
        - car
      filters:
        person:
          min_area: 500 # prevents fence fittings
          mask:
            - 1731,183,1713,285,1684,265,1697,175 # prevents neighbor's fence 1080p
    detect:
      enabled: true
      # width: 1920 # <---- update for your camera's resolution
      # height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 1333,21,1541,58,1654,100,1655,146,1623,207,1588,270,1559,394,1487,451,1373,441,1371,397,1247,318,1231,172,1085,0 # prevents tree 1080p
    zones:
      sidewalk:
        coordinates: 0.844,0.397,0.465,0.384,0.206,0.389,0.215,0.471,0.834,0.469 # 1080p
        inertia: 3
        loitering_time: 0
  camera_2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_2_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
        - motorcycle
        - car
    detect:
      enabled: true
      # width: 2688 # <---- update for your camera's resolution
      # height: 1520 # <---- update for your camera's resolution
record:
  enabled: true
  retain:
    days: 7
    mode: all
  # events:
  #   retain:
  #     default: 30
  #     mode: motion
snapshots:
  enabled: true
version: 0.14
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
xuser@android-xu54s87er:~$ ffprobe rtsp://admin:123456@192.168.0.202:554/Stream0
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 5 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 8 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 4 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 3 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 4 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 4 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 9 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 2 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 4 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 3 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 2 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 3 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 14 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 7 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 15 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 4 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 6 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 3 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 6 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 4 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 8 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 4 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 3 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 2 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 1 packets
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 6 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 3 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 8 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 18 times
[rtsp @ 0x55e4dc5fcec0] max delay reached. need to consume packet
[rtsp @ 0x55e4dc5fcec0] RTP: missed 4 packets
[rtsp @ 0x55e4dc5fcec0] Error parsing AU headers
    Last message repeated 9 times
Input #0, rtsp, from 'rtsp://admin:123456@192.168.0.202:554/Stream0':
  Metadata:
    title           : RTSP/RTP stream from icamra ipc
  Duration: N/A, start: 0.120000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 2688x1520, 25 fps, 16.83 tbr, 90k tbn, 25 tbc
  Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
xuser@android-xu54s87er:~$ ffprobe rtsp://admin:123456@192.168.0.202:554/Stream1
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x564edd40fec0] Error parsing AU headers
    Last message repeated 6 times
[rtsp @ 0x564edd40fec0] max delay reached. need to consume packet
[rtsp @ 0x564edd40fec0] RTP: missed 1 packets
[rtsp @ 0x564edd40fec0] Error parsing AU headers
    Last message repeated 7 times
[rtsp @ 0x564edd40fec0] max delay reached. need to consume packet
[rtsp @ 0x564edd40fec0] RTP: missed 1 packets
[rtsp @ 0x564edd40fec0] max delay reached. need to consume packet
[rtsp @ 0x564edd40fec0] RTP: missed 1 packets
[rtsp @ 0x564edd40fec0] Error parsing AU headers
    Last message repeated 5 times
[rtsp @ 0x564edd40fec0] max delay reached. need to consume packet
[rtsp @ 0x564edd40fec0] RTP: missed 1 packets
[rtsp @ 0x564edd40fec0] Error parsing AU headers
    Last message repeated 3 times
[rtsp @ 0x564edd40fec0] max delay reached. need to consume packet
[rtsp @ 0x564edd40fec0] RTP: missed 2 packets
[rtsp @ 0x564edd40fec0] Error parsing AU headers
    Last message repeated 17 times
[rtsp @ 0x564edd40fec0] max delay reached. need to consume packet
[rtsp @ 0x564edd40fec0] RTP: missed 1 packets
[rtsp @ 0x564edd40fec0] Error parsing AU headers
    Last message repeated 42 times
Input #0, rtsp, from 'rtsp://admin:123456@192.168.0.202:554/Stream1':
  Metadata:
    title           : RTSP/RTP stream from icamra ipc
  Duration: N/A, start: 0.138000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 640x360, 10 fps, 14.42 tbr, 90k tbn, 10 tbc
  Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

anjvision 4MP 48V PoE https://www.aliexpress.com/item/1005004741864983.html?spm=a2g0o.order_list.order_list_main.35.16e11802YWNmdo

### Screenshots of the Frigate UI's System metrics pages

![Cameras-Stats-Frigate-12-13-2024_12_10_AM](https://github.com/user-attachments/assets/97c1eb88-353a-4827-8da9-1c22495b2e73)
![General-Stats-Frigate-12-13-2024_12_10_AM](https://github.com/user-attachments/assets/39b0ed76-0507-404b-a4f2-0e5c3b3a5556)
