### DISCUSSION TITLE
[Support]: XFS media disk failing on a bi/daily basis

### DISCUSSION THREAD

**Discussion by farirat** [blakeblackshear/frigate#15487] [General Support]
### Describe the problem you are having

Running Frigate for 20 days now, every 1-2 days I get a XFS crash on the media disk:

dmesg:
```
[Fri Dec 13 01:11:06 2024] XFS (sdb): Metadata corruption detected at xfs_inode_buf_verify+0x149/0x170 [xfs], xfs_inode block 0x13e549ff0 xfs_inode_buf_verify
[Fri Dec 13 01:11:06 2024] XFS (sdb): Unmount and run xfs_repair
[Fri Dec 13 01:11:06 2024] XFS (sdb): First 128 bytes of corrupted metadata buffer:
[Fri Dec 13 01:11:06 2024] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] 00000070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[Fri Dec 13 01:11:06 2024] XFS (sdb): metadata I/O error in "xfs_imap_to_bp+0x53/0x80 [xfs]" at daddr 0x13e549ff0 len 32 error 117
[Fri Dec 13 01:11:06 2024] XFS (sdb): Metadata I/O Error (0x1) detected at xfs_trans_read_buf_map+0x178/0x2f0 [xfs] (fs/xfs/xfs_trans_buf.c:296).  Shutting down filesystem.
[Fri Dec 13 01:11:06 2024] XFS (sdb): Please unmount the filesystem and rectify the problem(s)
```

Usually I do umount the disk, xfs_repair -L it and restart Frigate, everything takes off before the issue raises again ...

smartctl -a:
```
# smartctl -a /dev/sdb
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.8.4-2-pve] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Seagate IronWolf
Device Model:     ST8000VN004-3CP101
Serial Number:    WWZ3W8YQ
LU WWN Device Id: 5 000c50 0f67e4d7d
Firmware Version: SC60
User Capacity:    8,001,563,222,016 bytes [8.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database 7.3/5319
ATA Version is:   ACS-4 (minor revision not indicated)
SATA Version is:  SATA 3.3, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri Dec 13 10:42:09 2024 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x82)	Offline data collection activity
					was completed without error.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever
					been run.
Total time to complete Offline
data collection: 		(  567) seconds.
Offline data collection
capabilities: 			 (0x7b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine
recommended polling time: 	 (   1) minutes.
Extended self-test routine
recommended polling time: 	 ( 710) minutes.
Conveyance self-test routine
recommended polling time: 	 (   2) minutes.
SCT capabilities: 	       (0x50bd)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 10
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   072   064   044    Pre-fail  Always       -       17380936
  3 Spin_Up_Time            0x0003   092   091   000    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   020    Old_age   Always       -       22
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   088   060   045    Pre-fail  Always       -       644129955
  9 Power_On_Hours          0x0032   097   097   000    Old_age   Always       -       3370
 10 Spin_Retry_Count        0x0013   100   100   097    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   020    Old_age   Always       -       22
 18 Head_Health             0x000b   100   100   050    Pre-fail  Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
188 Command_Timeout         0x0032   100   100   000    Old_age   Always       -       0
190 Airflow_Temperature_Cel 0x0022   055   041   000    Old_age   Always       -       45 (Min/Max 44/57)
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       18
193 Load_Cycle_Count        0x0032   100   100   000    Old_age   Always       -       170
194 Temperature_Celsius     0x0022   045   059   000    Old_age   Always       -       45 (0 30 0 0 0)
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0
240 Head_Flying_Hours       0x0000   100   100   000    Old_age   Offline      -       3367h+23m+25.766s
241 Total_LBAs_Written      0x0000   100   253   000    Old_age   Offline      -       166163054612
242 Total_LBAs_Read         0x0000   100   253   000    Old_age   Offline      -       52123859977

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%      3370         -
# 2  Extended offline    Interrupted (host reset)      00%      2462         -
# 3  Short offline       Completed without error       00%      2424         -
# 4  Short offline       Interrupted (host reset)      60%         0         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

And **xfs_repair -n** outcome: [pastebin](https://pastebin.com/MwZqGKdf)

### Version

0.14

### Frigate config file

```yaml
tls:
  enabled: false

#birdseye:
#  enabled: True
#  mode: continuous

objects:
  track:
    - person

auth:
  #reset_admin_password: true
  enabled: true
  session_length: 86400
  hash_iterations: 1600000

mqtt:
  enabled: true
  host: ____
  port: 1884
  user: ____
  password: ____

detectors:
  cpu:
    type: cpu
    num_threads: 3
#  cpu_tensorflow:
#    type: cpu
#    num_threads: 3
#    model:
#      path: "/custom_model.tflite"
#  ovino:
#    type: openvino
#    device: GPU

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

go2rtc:
  streams:
    door_ring:
      - rtsp://____:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:door_ring#audio=aac
    door_ring_sub:
      - rtsp://____:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:door_ring_sub#audio=aac
    cam01:
      - rtsp://____:554/h264Preview_01_main
    cam01_sub:
      - rtsp://____:554/h264Preview_01_sub
    cam02:
      - rtsp://____:554/h264Preview_01_main
    cam02_sub:
      - rtsp://____:554/h264Preview_01_sub
    cam03:
      - rtsp://____:554/h264Preview_01_main
    cam03_sub:
      - rtsp://____:554/h264Preview_01_sub
    cam06:
      - rtsp://____:554/h264Preview_01_main
    cam06_sub:
      - rtsp://____:554/h264Preview_01_sub
    cam07:
      - rtsp://____:554/h264Preview_01_main
    cam07_sub:
      - rtsp://____:554/h264Preview_01_sub

cameras:
  door_ring:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/door_ring_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/door_ring
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      max_disappeared: 150
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.6
    motion:
      mask:
        - 0.404,0.479,0.426,0.48,0.447,0.527,0.386,0.533
        - 0.682,0.018,0.993,0.369,0.997,0.011
      threshold: 30
      contour_area: 60
      improve_contrast: 'true'
    zones:
      Entrée:
        coordinates: 0.996,0.987,0.988,0.372,0.668,0.019,0.334,0.007,0.003,0.335,0.006,0.989
        loitering_time: 0
  cam01:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam01_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/cam01
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    motion:
      mask: 0.323,0.029,0.655,0.031,0.656,0.064,0.324,0.063
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
    zones:
      Porte_pietonne:
        coordinates: 0.659,0.115,0.747,0.118,0.845,0.418,0.547,0.434
        loitering_time: 0
      Parking_entry:
        coordinates: 0.409,0.095,0.644,0.101,0.535,0.43,0.013,0.529,0.01,0.179
        loitering_time: 0
      Parking:
        coordinates: 0.014,0.545,0.529,0.448,0.85,0.436,0.992,0.583,0.995,0.99,0.109,0.985,0.01,0.786
        loitering_time: 0
  cam02:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam02_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/cam02
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    motion:
      mask:
        - 0.756,0.176,0.787,0.188,0.783,0.243,0.751,0.24
        - 0.832,0.19,0.996,0.241,0.994,0.991,0.805,0.628,0.91,0.337,0.814,0.291
        - 0.314,0.026,0.663,0.026,0.666,0.072,0.703,0.172,0.613,0.165,0.587,0.104,0.31,0.096
        - 0.078,0.15,0.198,0.14,0.206,0.301,0.093,0.319
    zones:
      Kitchen_zone:
        coordinates: 0.58,0.168,0.725,0.215,0.716,0.485,0.455,0.382
        loitering_time: 0
      Majel:
        coordinates: 0.755,0.321,0.88,0.397,0.674,0.982,0.011,0.993,0.004,0.366,0.407,0.271
        loitering_time: 0
  cam03:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam03_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/cam03
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: 'true'
      mask:
        - 0.624,0.127,0.63,0.122,0.672,0.219,0.707,0.208,0.835,0.461,0.999,0.493,0.999,0.003,0.021,0.003,0.025,0.134,0.206,0.117,0.249,0.057,0.368,0.064,0.568,0.082
        - 0.004,0.419,0.13,0.99,0.217,0.994,0.191,0.806,0.14,0.681,0.075,0.393,0.037,0.309
    zones:
      Garden_and_alley:
        coordinates:
          0.044,0.295,0.086,0.384,0.239,0.985,0.998,0.997,0.996,0.505,0.823,0.468,0.56,0.092,0.255,0.069,0.217,0.132
        loitering_time: 0
  cam06:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam06_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/cam06
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.6
          max_area: 100000
        car:
          min_score: 0.65
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
      mask:
        - 0.878,0.006,0.854,0.076,0.858,0.49,0.865,0.602,0.998,0.598,0.997,0.229,0.947,0.012
        - 0.889,0.789,0.963,0.785,0.963,0.984,0.885,0.976
        - 0.344,0.042,0.641,0.044,0.643,0.085,0.349,0.084
    zones:
      Private_entrance:
        coordinates:
          0.013,0.669,0.326,0.011,0.646,0.011,0.67,0.21,0.846,0.216,0.862,0.605,0.875,0.997,0.066,0.995
        loitering_time: 0
      Roufa_zone:
        coordinates: 0.163,0.011,0.279,0.079,0.019,0.637,0.009,0.171
        loitering_time: 0
  cam07:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam07_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/cam07
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
#camera_groups:
#  front_door:
#    cameras:
#      - door_ring_sub
#    icon: LuCar
#    order: 0

    motion:
      mask:
        - 0.001,0.006,0.003,0.99,0.123,0.994,0.083,0.003
        - 0.683,0.018,0.701,0.068,0.748,0.089,0.779,0.008
        - 0.345,0.039,0.64,0.048,0.646,0.094,0.348,0.085
    zones:
      Entry:
        coordinates:
          0.13,0.989,0.105,0.202,0.281,0.013,0.643,0.04,0.935,0.413,0.996,0.566,0.992,0.985
        loitering_time: 0
logger:
  default: info
    #  logs:
    #    frigate.record.maintainer: debug

ffmpeg:
  # Optional: global ffmpeg args
  global_args: -hide_banner -loglevel warning -threads 4
  # Optional: global hwaccel args
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: auto
  # Optional: global input args
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams
    detect: -threads 4 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams
    record: preset-record-generic-audio-aac
  # Optional: Time in seconds to wait before ffmpeg retries connecting to the camera.
  # If set too low, frigate will retry a connection to the camera's stream too frequently, using up the limited streams some cameras can allow at once
  # If set too high, then if a ffmpeg crash or camera stream timeout occurs, you could potentially lose up to a maximum of retry_interval second(s) of footage
  # NOTE: this can be a useful setting for Wireless / Battery cameras to reduce how much footage is potentially lost during a connection timeout.
  retry_interval: 10

record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day
  sync_recordings: true
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 5
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Recording Export Settings
  export:
    # Optional: Timelapse Output Args
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.04*PTS -r 30
  # Optional: Recording Preview Settings
  preview:
    # Optional: Quality of recording preview
    # Options are: very_low, low, medium, high, very_high
    quality: very_low
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include
    pre_capture: 10
    # Optional: Number of seconds after the event to include
    post_capture: 15
    # Optional: Objects to save recordings for.
    objects:
      - person
      - car
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days
      default: 30
      # Optional: Mode for retention.
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 30
        car: 30

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image
  clean_copy: true
  # Optional: print a timestamp on the snapshots
  timestamp: false
  # Optional: draw bounding box on the snapshots
  bounding_box: true
  # Optional: crop the snapshot
  crop: false
  # Optional: height to resize the snapshot to
  height: 250
  # Optional: Restrict snapshots to objects that entered any of the listed zones
  required_zones: []
  # Optional: Camera override for retention settings
  retain:
    # Required: Default retention days
    default: 90
    # Optional: Per object retention days
    objects:
      person: 365
      car: 365
  # Optional: quality of the encoded jpeg, 0-100
  quality: 70

version: 0.14
```

### Relevant Frigate log output

```shell
2024-12-13 03:55:52.384435691  [2024-12-13 03:55:52] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam02. Keeping the 6 most recent segments out of 9 and discarding the rest...
2024-12-13 03:55:57.388973995  [2024-12-13 03:55:57] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam01. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:55:57.390212963  [2024-12-13 03:55:57] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam03. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:55:57.392021944  [2024-12-13 03:55:57] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam06. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:55:57.393267791  [2024-12-13 03:55:57] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam07. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:55:57.394009692  [2024-12-13 03:55:57] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam02. Keeping the 6 most recent segments out of 8 and discarding the rest...
2024-12-13 03:56:02.393038472  [2024-12-13 03:56:02] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for door_ring. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:56:02.393360569  [2024-12-13 03:56:02] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam01. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:56:02.394523272  [2024-12-13 03:56:02] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam02. Keeping the 6 most recent segments out of 9 and discarding the rest...
2024-12-13 03:56:07.396894334  [2024-12-13 03:56:07] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam06. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:56:07.397829831  [2024-12-13 03:56:07] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam03. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:56:07.398950777  [2024-12-13 03:56:07] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam07. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:56:07.399715567  [2024-12-13 03:56:07] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam02. Keeping the 6 most recent segments out of 8 and discarding the rest...
2024-12-13 03:56:12.401863054  [2024-12-13 03:56:12] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for door_ring. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-12-13 03:56:12.402134188  [2024-12-13 03:56:12] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam02. Keeping the 6 most recent segments out of 9 and discarding the rest...
2024-12-13 03:56:17.407607022  [2024-12-13 03:56:17] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cam01. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Relevant go2rtc log output

```shell
N/D
```

### FFprobe output from your camera

```shell
N/D
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    network_mode: host
    container_name: frigate
    privileged: true
    restart: no
    shm_size: "128mb" # Calculation: https://docs.frigate.video/frigate/installation#calculating-required-shm-size
    entrypoint: ["/bin/bash", "/startup-hook.sh"]
      #devices:
      #- /dev/bus/usb:/dev/bus/usb # USB Coral
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./frigate/config:/config
      - ./frigate/scripts/startup-hook.sh:/startup-hook.sh
      - /opt/storage/data/frigate/media/exports:/media/frigate/exports
      - /opt/storage/data/frigate/media/clips:/media/frigate/clips
      - /opt/storage/data/frigate/media/recordings:/media/frigate/recordings
      - type: tmpfs # Optional: 2GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    env_file:
      - .frigate-env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

Worth noting:

Running docker-compose inside a proxmox vm, 36G Ram, 6 Cores and the media disk is completely dedicated to frigate.

My startup-hook.sh:
```
#!/bin/bash

echo "######### Startup hook - begin"

echo "Disabling nginx access logs"
sed -i 's/access_log \/dev\/stdout main;/access_log \/dev\/null main;/g' /usr/local/nginx/conf/nginx.conf

echo "######### Startup hook - end"

# Delegate to original entrypoint
exec /init "$@"
```
