### DISCUSSION TITLE
[Config Support]: Please help with max_area for camera detection of a person

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#15493] [Config Support] [answered]
### Describe the problem you are having

I must be doing something wrong with max_area, probably calculating the area wrong? I have a Reolink Video Doorbell WiFi camera, listed with a resolution of "5MP 2K+ Super HD". From what I can find, that apparently means 2560 x 1920. If I'm understanding right, that means a total of 4,915,200 pixels. I'm trying to prevent detection of a spider web strand at my front door (spider keeps rebuilding it and hiding where I can't find it) - I'm getting hundreds of notifications a night from it. So anyway, I thought I could reduce it some because a lot of the notifications take up a majority of the image, like this: 

![image](https://github.com/user-attachments/assets/db68b94c-6dd3-4e63-8ade-c6d07fb2ab10)

So I thought if I reduced the detection max size down to around 60% that should keep a good chunk of the notifications down, so I entered 

```
person:
          max_area: 3000000
```
for that camera, as seen in the config snippet below. 

Am I doing something wrong? I'm still getting a ton of notifications like the one above, which looks like way bigger than 60% of the image to me. 

Thanks!!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.739,0,0.511,0.373,0.506,0.612,0.458,0.714,0.409,1,0.867,1,1,1,1,0.58,1,0,0.916,0
        - 0.539,0.458,0.544,0.496,0.368,0.49,0.374,0.455
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      zone_0:
        coordinates: 0,1,0,0.227,0.376,0.333,0.51,0.378,0.518,0.588,0.597,1
        inertia: 3
    review:
      alerts:
        required_zones: zone_0
      detections:
        required_zones: zone_0
    objects:
      filters:
        person:
          max_area: 3000000
        car:
          mask: 0.394,0.421,0.374,0.438,0.376,0.496,0.499,0.506,0.542,0.514,0.634,0.523,0.582,0.47,0.513,0.414
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/recordings:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - PLUS_API_KEY=XXX
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/61627747-2a80-4f96-9780-c4f1a8a1eb70)
![image](https://github.com/user-attachments/assets/f8616f96-9e1e-433f-a64a-e6fac364e768)
{"return_code":0,"stderr":"","stdout":"vainfo:VA-`APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLD"}`
