### DISCUSSION TITLE
MQTT Event - Zone Loitering behavior - Clarification

### DISCUSSION THREAD

**Discussion by rowskilled14** [blakeblackshear/frigate#15506] [Ask A Question] [answered]
I wanted to quickly clarify the expected behavior for a loitering zone requirement, and depending on that expected behavior, the best course of action I should take.  I've read the docs, but I'm still a touch confused on this issue.

1. If loitering is required for a zone for say 5 seconds, does that mean that the object is not considered in the zone until the object has been present for 5 seconds?  I would presume yes.
2. Does MQTT report events regardless of if the object is present in a zone or not, even if the object is detected at a location where a zone is present?  For example, if I've got a zone set up over the whole screen with a requirement of loitering for 5 seconds, will MQTT events be fired immediately, even though the required zone isn't triggering yet?  I previously would have assumed not, but I'm starting to think it would now.  Sample config below.
3. If I want to filter out MQTT events which have an object detected in a zone's borders but do not meet the zone's requirements for being considered, "in the zone", what is the easiest way for me to accomplish this goal?  Preferably, I would want to change this on a per-camera basis and not take actions which would require adding zones to every camera or some similar actions.  In other words, I would like to take actions on MQTT events which have an object loitering in a zone, but not merely passing through.  I would also want to take actions on all other objects outside of this zone.  

Sample config:

``` yaml
camera_name:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_name
          roles:
            - record
            - detect
    record:
      enabled: true
    objects:
      track:
        - person
        - car
    zones:
      zone_a:
        coordinates: <some_coords>
        loitering_time: 5
        inertia: 5
```

___

For my point/question 3, I'm thinking that I might have to filter something specific for my camera in my mqtt-reading program.  But, I'm hoping there's another approach which I'm overlooking using the given Frigate API.  

Thank you very much!
