### DISCUSSION TITLE
[Config Support]: Remove audio not working at all

### DISCUSSION THREAD

**Discussion by Palleri** [blakeblackshear/frigate#15509] [Config Support]
### Describe the problem you are having

I cannot for the love of me get this to work.
I am trying to add two streams one with audio and video for recording and one for live only without audio.

Ive tried everything and cannot get it to work.
I get audio both in home assistant and in the frigate UI.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.0.5.100
  port: 1883
  #topic_prefix: frigate
  user: asd
  password: asd

go2rtc:
  streams:
    3dcamera-live:
      - rtsp://asd:asd@192.168.111.102:554/stream2
      - ffmpeg:3dcamera-live#video=copy
    3dcamera-record:
      - rtsp://asd:asd@192.168.111.102:554/stream1
cameras:
  3dcamera-live:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/3dcamera-live # <--- the name here must match the name of the camera in restream
    record:
      enabled: false
    audio:
      enabled: False
    motion:
      threshold: 80
      contour_area: 10
      improve_contrast: 'true'

  3dcamera-record:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/3dcamera-record # <--- the name here must match the name of the camera in restream
          roles:
            - record
    record:
      enabled: True
    motion:
      threshold: 80
      contour_area: 10
      improve_contrast: 'true'
    live:
      stream_name: 3dcamera-live


version: 0.14
```

### Relevant Frigate log output

```shell
Donno
```

### Relevant go2rtc log output

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  int-frigate:
    container_name: int-frigate
    privileged: true # this may not be necessary for all setups
    networks:
      int-prod:
        ipv4_address: 10.0.115.27
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yaml:/config/config.yml
      - /mnt/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      FRIGATE_RTSP_USERNAME: "admin"
      FRIGATE_MQTT_USERNAME: "frigate"
```

### Object Detector

Coral
