### DISCUSSION TITLE
Attempting to re-encode audio but getting invalid argument

### DISCUSSION THREAD

**Discussion by ideal2545** [blakeblackshear/frigate#1550] [Ask A Question]
Hi, 

I'm trying to get some audio out of a hikvision cam that doesnt support AAC unfortunately. I read the documentation which suggests adding -c:a aac to the output arguments of whatever role you want to use but for me I get an 'invalid argument error'. I read a discussion where someone suggested doing a copy first but I'm getting the same error. Am I perhaps not putting the argument in the right spot? 

```
  jemma:
    ffmpeg:
      output_args: 
        rtmp: -c:v copy -c:a aac
      inputs:
        - path: rtsp://xx:xx@<ip>:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://xx:xx@<ip>:554/Streaming/Channels/101
          roles:
            - clips
            - rtmp

    #width and height only used for the detect role
    width: 640
    height: 360
    fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true 
      retain:
        default: 1
    clips:
      enabled: true
      retain:
        default: 1
```
error: `rtmp://127.0.0.1/live/jemma: Invalid argument`

I also tried moving it out from underneath a specific camera like the below but also the same. 

```
ffmpeg:
   output_args:
     rtmp: -c:v copy -c:a aac
```

**Comment by blakeblackshear** [comment]
You are replacing all of the default args when you specify output_args. You need to copy and modify rather than remove the existing ones all together. Defaults are here: https://blakeblackshear.github.io/frigate/configuration/index#ffmpeg

**Reply by ideal2545** [reply]
Ah I understand, thank you, ill give it a go.

**Reply by ideal2545** [reply]
So I gave this a go, but cant seem to get the audio to come through, maybe I'm still malforming something? I basically added it to just the specific camera, and then only to the RTMP role: " rtmp: -c copy -f flv -c:v copy -c:a aac"

I'm trying to just get the audio to come through the RTMP stream so that when I pass audio through to HA, i can then use homekit to hear the audio. In the docs I see its mentioned to ovveride the -an but thats only for clips and recordings, maybe it doesnt apply to the rtmp role?

```
cameras:
  jemma:
    ffmpeg:
      inputs:
        - path: rtsp://a@192.168.1.63:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://@192.168.1.63:554/Streaming/Channels/101
          roles:
            - clips
            - rtmp
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
        rtmp: -c copy -f flv -c:v copy -c:a aac
```

**Reply by blakeblackshear** [reply]
This should work. You can try connecting to the rtmp feed frigate provides directly with VLC to see if you hear the audio.

**Reply by ideal2545** [reply]
Thanks so much for the help, it started working today. I'm not sure why it didnt work right away but it was probably user-error but with the above its working great now and audio is coming through HA and through homekit!

**Reply by krasatos** [reply]
This worked for me too, thanks.
I tried adding the `-c:a aac` to the record arguments too but the clip recorded is still w/o sound. 
Any ideas?

Working with a Tapo C200 camera and here is my config:
```
  up_lr_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://xxx/stream1
          roles:
            - record 
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -c:a aac
        rtmp: -c copy -f flv -c:v copy -c:a aac
```

Edit: I removed the -an flag from the record arguments, as stated in the FAQ. 
Now i'm getting these error and logs:
`[2022-09-20 10:30:08] ffmpeg.up_lr_cam.record        ERROR   : Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 1, only the last option '-c:a aac' will be used.`

```
[2022-09-20 10:45:33] ffmpeg.up_lr_cam.record        ERROR   : [mp4 @ 0x561751770900] Could not find tag for codec pcm_alaw in stream #1, codec not currently supported in container
[2022-09-20 10:45:33] ffmpeg.up_lr_cam.record        ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
[2022-09-20 10:45:33] ffmpeg.up_lr_cam.record        ERROR   : 
[2022-09-20 10:45:33] watchdog.up_lr_cam             INFO    : Terminating the existing ffmpeg process...
```
