### DISCUSSION TITLE
[Config Support]: MJPEG camera latency

### DISCUSSION THREAD

**Discussion by Dillton** [blakeblackshear/frigate#15519] [Config Support] [answered]
### Describe the problem you are having

Hello.
I have USB camera connected to rpi 4 where go2rtc is currently running and I am able to view the live stream in MJPEG in browser without any issues. The stream is fluent and latency is minimal.
What I am trying to do is to run this stream through Frigate which is running on different piece of HW to have the possibility to use Frigate advanced function like motion detection etc...
My problem is that in Frigate the latency of this stream very very high.
Below is of course my current config. Before this config I tried to add the camera in frigate directly with rtsp but the result was the same, high latency.
So anyone have some experince how to adjust the Frigate config?

### Version

0.14.1

### Frigate config file

```yaml
cameras:
  logitech_c922:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/logitech_c922_rtc
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
go2rtc:
  streams:
    logitech_c922_rtc:
      - ffmpeg:http://10.0.0.83:1984/api/stream.mjpeg?src=logitech_c922#video=h264#hardware
  webrtc:
    candidates:
      - 10.0.0.83:8555
      - stun:8555
record:
  enabled: false
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
motion:
  threshold: 200
  contour_area: 30
  lightning_threshold: 0.8
version: 0.14
```

### Relevant Frigate log output

```shell
As the stream is working somehow there are no error logs.
```

### Relevant go2rtc log output

```shell
As the stream is working somehow there are no error logs.
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/frigate/config:/config
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "20085:5000" # Internal unauthenticated access. Expose carefully.
      - "20086:1984" # go2rtc
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/9343ab8b-eb40-4843-a77a-9b96fed3b73c)
