### DISCUSSION TITLE
[Config Support]: Config only VISUAL motion

### DISCUSSION THREAD

**Discussion by Palleri** [blakeblackshear/frigate#15518] [Config Support]
### Describe the problem you are having

Ive done alot of configuration in my live but this takes the price.
This might be the most complex configuration in my live.
Ive read the whole documentation for frigate configuration and I cannot wrap my head around it.
I might be having a total brain fart or something.

Can someone explain to me what is going on.

Why cant I have a camera that record only on VISUAL motion and not audio and visual.
Why shall I have two streams from the same camera, main and sub other than to run detect which is heavy on the CPU on the sub (that one I get) other than that why? As far as I understand detect is only run when wanting to identify objects or persons and such.
I do not need detect to identify for example a fart.

I want a camera acting as a baby monitor, ONLY record and tell my home assistant a baby is crying OR moving.
Not to record when the baby slamming things nor me talking in the room or other noises.

Ive come to the conclusion that motion is capturing audio as motion as well, why?
Or how can I achieve what I am trying to do?

I have no idea what I am doing with my config....

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
Babycam-main:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Babycam-main # <--- the name here must match the name of the camera in restream
          roles:
            - record
            - audio
    motion:
      threshold: 80
      contour_area: 10
      improve_contrast: 'true'
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    audio:
      min_volume: 1000
      filters:
        crying:
          threshold: 0.5
      enabled: true
      listen:
        - crying
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Other

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
.
```

### Object Detector

CPU (no coral)
