### DISCUSSION TITLE
[Support]: Home Assistant Notifications with Review Items

### DISCUSSION THREAD

**Discussion by easez88** [blakeblackshear/frigate#15526] [General Support] [answered]
### Describe the problem you are having

Hello, 

I am trying to  create home assistant notifications for review items instead of detections. My issue is that the urls are different from those in events. A  review item gives me a thumb_path like `"thumb_path": "/media/frigate/clips/review/thumb-garage_camera-1734303040.847597-j2o7zb.webp",` However, when I try to go to `MYHAIP/media/frigate/clips/review/thumb-garage_camera-1734303040.847597-j2o7zb.webp` I  get 401 unauthorized. Is there a different URL  I should be  using instead. Previously I could get a snapshot.jpg and a clip.mp4. I'm trying to recreate that, but for review items instead of individual events. 

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Chrome Latest

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.2.10
  port: 1883
  user: user
  password: Pass
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-nvidia-h265

go2rtc:
  streams:
    garage_camera_main:
      - rtsp://192.168.2.11:61245/23790536cefb7f72
      - ffmpeg:59b903d41f201af1#audio-opus
    garage_camera_sub:
      - rtsp://192.168.2.11:61245/eda406359626353f
      - ffmpeg:b64c92afe72751be#audio-opus

cameras:
  garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://192.168.1.10:8554/garage_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.10:8554/garage_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
    motion:
      mask: 0.631,0.923,1,0.923,1,0.973,0.63,0.974
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'

detectors:
  cpu1:
    type: cpu
    num_threads: 3

record:
  enabled: true
  retain:
    days: 7
    mode: all

  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 7
version: 0.14
```

### Relevant Frigate log output

```shell
N/A  401 error from Home Assistant
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11 # For Raspberry Pi 4B
    #   - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - config:/config
      - media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
volumes:
  config:
  media:
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolinks

### Any other information that may be helpful

Event notifications work, trying to transition to review items
