### DISCUSSION TITLE
[Detector Support]:

### DISCUSSION THREAD

**Discussion by Roagert** [blakeblackshear/frigate#15530] [Detector Support]
### Describe the problem you are having

I seem to have a slow tensorrt or the NVIDIA GPU is very loaded. Seems like its working hard to keep up

### Version

0.15.0-beta3-tensorrt

### Frigate config file

```yaml
go2rtc:
  streams:
    camera_driveway1:
      - rtsp://admin:XX@192.168.86.27:554/ch_100
    camera_driveway1_sub:
      - rtsp://admin:XX@192.168.86.27:554/ch_400
    camera_driveway2:
      - rtsp://admin:XX@192.168.86.27:554/ch_105
    camera_driveway2_sub:
      - rtsp://admin:XX@192.168.86.27:554/ch_405
    camera_garden2:
      - rtsp://admin:XX@192.168.86.27:554/ch_101
    camera_garden2_sub:
      - rtsp://admin:XX@192.168.86.27:554/ch_401
    camera_garage:
      - rtsp://admin:XX@192.168.86.27:554/ch_102
    camera_garage_sub:
      - rtsp://admin:XX@192.168.86.27:554/ch_402
    camera_garden1:
      - rtsp://admin:XX@192.168.86.27:554/ch_103
    camera_garden1_sub:
      - rtsp://admin:XX@192.168.86.27:554/ch_403
    camera_garden3:
      - rtsp://admin:XX@192.168.86.27:554/ch_104
    camera_garden3_sub:
      - rtsp://admin:XX@192.168.86.27:554/ch_404

mqtt:
  enabled: true
  host: 192.168.86.26
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate

genai:
  enabled: True
  provider: gemini
  api_key: "XX"
  model: gemini-1.5-flash

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/8.5.3/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

detect:
  width: 640
  height: 480
  fps: 5
  enabled: true

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - dog
    - car
    - bicycle
    - motorcycle

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 0
    mode: all
  preview:
    quality: medium
  alerts:
    retain:
      days: 10
    pre_capture: 15
    post_capture: 5
  detections:
    retain:
      days: 10
    pre_capture: 15
    post_capture: 5
audio:
  enabled: false
  max_not_heard: 30
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

snapshots:
  enabled: true
  retain:
    default: 30
  bounding_box: true
  crop: false

cameras:
  Driveway1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_driveway1
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac

    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.064,0,0,1,0,1,0.064

    objects:
      mask:
        - 0,0.064,0,0,1,0,1,0.064
        - 0,0.548,0.105,0.376,0.249,0.226,0.337,0.21,0.353,0.177,0.39,0.177,0.402,0.155,0.429,0.151,0.542,0.166,0.635,0.186,0.692,0.21,0.687,0.239,0.806,0.33,0.946,0.471,0.984,0.309,1,0.31,1,0,0.703,0.002,0,0
    zones:
      driveway_inside:
        coordinates: 
          0.251,0.225,0.34,0.211,0.443,0.221,0.443,0.197,0.674,0.237,0.768,0.302,0.935,0.453,1,0.551,1,1,0,1,0,0.546,0.105,0.377
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - car
      driveway_outside:
        coordinates: 
          0.307,0.13,0.304,0.174,0.442,0.18,0.441,0.196,0.487,0.202,0.685,0.234,0.687,0.219,0.699,0.169,0.641,0.151,0.501,0.117,0.358,0.105,0.308,0.106
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - car
      garden_inside:
        coordinates: 0.947,0.467,0.984,0.308,0.999,0.313,0.997,0.542
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 3
      entire_frame:
        coordinates: 0,0,1920,0,1920,1080,0,1080
        objects:
          - person
          - cat

    mqtt:
      enabled: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []
    live:
      stream_name: camera_driveway1


  Driveway2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_driveway2
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.064,0,0,1,0,1,0.064
    objects:
      mask:
        - 0,0.064,0,0,1,0,1,0.064
        - 0,0.367,0.438,0.195,0.46,0.195,0.47,0.208,0.479,0.218,0.5,0.227,0.515,0.223,0.511,0.186,0.51,0.167,0.519,0.146,0.528,0.146,0.537,0.153,0.551,0.152,0.574,0.148,0.607,0.148,0.677,0.161,0.654,0.287,0.635,0.487,0.711,0.539,0.741,0.519,0.827,0.339,0.853,0.343,0.926,0.379,0.939,0.488,0.963,0.504,0.972,0.476,0.984,0.419,0.998,0.433,1,0.055,0,0.062
        - 0.728,0.529,0.702,0.624,0.705,0.719,0.715,0.802,0.816,0.865,0.89,0.755,0.927,0.604,0.93,0.532,0.907,0.459,0.885,0.39,0.818,0.415,0.779,0.438,0.751,0.487
    mqtt:
      enabled: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []
    zones:
      driveway_inside:
        coordinates: 
          0.497,0.186,0.663,0.262,0.657,0.306,0.193,0.592,0.029,0.673,0,0.595,0.002,0.382,0,0.243,0.095,0.185,0.381,0.143,0.412,0.197
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - dog
          - cat
          - car
      driveway_outside:
        coordinates: 0.512,0.161,0.502,0.181,0.665,0.255,0.68,0.165,0.512,0.133
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - car
      garden_inside:
        coordinates: 
          0.685,0.167,0.774,0.185,0.847,0.22,0.999,0.308,0.999,0.996,0.788,0.997,0.649,1,0.699,0.824,0.781,0.572,0.647,0.479,0.66,0.306
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 3
      frontdoor_door:
        coordinates: 
          0.031,0.679,0.355,0.497,0.658,0.312,0.646,0.48,0.687,0.507,0.764,0.556,0.775,0.569,0.645,1,0.131,0.996
        loitering_time: 0
      entire_frame:
        coordinates: 0,0,1920,0,1920,1080,0,1080
        objects:
          - person
          - cat
    review:
      alerts:
        required_zones: garden_inside
    live:
      stream_name: camera_driveway2
  Garden2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_garden2
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.064,0,0,1,0,1,0.064
    objects:
      mask:
        - 0,0.064,0,0,1,0,1,0.064
        - 0.168,0.254,0.356,0.228,0.35,0.253,0.351,0.319,0.358,0.33,0.568,0.462,0.629,0.442,0.642,0.312,0.574,0.264,0.403,0.218,0.573,0.217,0.701,0.283,0.901,0.414,1,0.522,1,0.369,1,0.062,0.955,0.064,0.756,0.066,0.688,0.066,0.555,0.065,0.481,0.065,0.17,0.054
        - 0.892,1,0.901,0.796,0.934,0.685,0.97,0.608,1,0.56,1,0.998
    mqtt:
      enabled: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []
    zones:
      garden_inside:
        coordinates: 
          0.167,0.257,0.379,0.222,0.572,0.218,0.699,0.284,0.9,0.415,0.999,0.519,0.998,0.997,0.291,0.999,0.177,0.691,0.137,0.491,0.189,0.418
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
      house_wall:
        coordinates: 
          0.287,0.997,0.173,0.686,0.134,0.494,0.188,0.415,0.169,0.177,0.098,0.203,0,0.145,0.001,0.997
        loitering_time: 0
        inertia: 3
      entire_frame:
        coordinates: 0,0,1920,0,1920,1080,0,1080
        objects:
          - person
          - cat
    live:
      stream_name: camera_garden2

  Garage:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_garage
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.064,0,0,1,0,1,0.064
    objects:
      mask:
        - 0,0.064,0,0,1,0,1,0.064
    mqtt:
      enabled: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []
    zones:
      garage_inside:
        coordinates: 0.728,0,0.692,0.22,0.98,0.496,0.865,0.708,0.675,1,0.006,0.997,0,0
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - car
      garage_outside:
        coordinates: 0.728,0,0.693,0.217,0.976,0.494,0.999,0.401,1,0.208,0.885,0.109
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - dog
          - cat
          - car
      house_wall:
        coordinates: 0.98,0.495,0.999,0.418,1,1,0.683,1,0.683,0.994,0.855,0.732
        loitering_time: 0
      entire_frame:
        coordinates: 0,0,1920,0,1920,1080,0,1080
        objects:
          - person
          - cat
          - dog
    review:
      alerts:
        required_zones: house_wall
      detections:
        required_zones:
          - garage_outside
          - garage_inside
    live:
      stream_name: camera_garage

  Garden1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_garden1
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.064,0,0,1,0,1,0.064
    objects:
      mask:
        - 0,0.064,0,0,1,0,1,0.064
        - 0.003,0.277,0.159,0.19,0.237,0.159,0.307,0.139,0.33,0.139,0.353,0.135,0.372,0.128,0.402,0.12,0.431,0.125,0.473,0.131,0.518,0.134,0.562,0.145,0.591,0.151,0.615,0.13,0.632,0.112,0.64,0.088,0.661,0.08,0.673,0.082,0.667,0.008,0.002,0.002
        - 0.17,0,0.166,0.186,0.179,0.306,0.185,0.343,0.139,0.354,0.102,0.377,0.094,0.436,0.101,0.506,0.132,0.519,0.183,0.517,0.224,0.47,0.273,0.428,0.288,0.386,0.26,0.318,0.239,0.283,0.223,0.2,0.217,0.139,0.211,0.061,0.202,0.026,0.195,0
    mqtt:
      enabled: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []
    zones:
      garden_inside:
        coordinates: 
          0.001,0.27,0.147,0.181,0.329,0.124,0.446,0.104,0.556,0.105,0.627,0.123,0.642,0.093,0.655,0.083,0.671,0.082,0.664,0.134,0.658,0.189,0.692,0.215,0.697,0.45,0.685,0.643,0.654,0.869,0.63,0.993,0.003,0.994
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - dog
          - cat
      house_wall:
        coordinates: 
          0.67,0.003,0.673,0.078,0.66,0.185,0.698,0.217,0.697,0.441,0.689,0.648,0.654,0.897,0.636,0.99,0.997,0.999,0.999,0.004
        loitering_time: 0
      entire_frame:
        coordinates: 0,0,1920,0,1920,1080,0,1080
        objects:
          - person
          - cat
    review:
      alerts:
        required_zones: garden_inside
      detections:
        required_zones: garden_inside
    live:
      stream_name: camera_garden1

  Garden3:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_garden3
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.064,0,0,1,0,1,0.064

    objects:
      mask:
        - 0,0.064,0,0,1,0,1,0.064
        - 0,0.31,0.245,0.205,0.382,0.187,0.468,0.219,0.546,0.247,0.555,0.205,0.737,0.227,1,0.333,1,0,0.6,0,0.601,0.004,0,0
        - 0,0.61,0.468,0.221,0.53,0.243,0.281,0.989,0.002,0.997
    mqtt:
      enabled: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []

    zones:
      garden_inside:
        coordinates: 0.466,0.219,0.545,0.245,0.549,0.513,0.542,1,0,1,0,0.613
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
        inertia: 3
      garden_outside:
        coordinates: 0,0.312,0,0.6,0.487,0.201,0.377,0.185,0.251,0.191
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - dog
          - cat
      house_wall:
        coordinates: 
          0.544,0.246,0.549,0.611,0.541,0.997,1,0.998,0.999,0.334,0.735,0.228,0.602,0.214,0.551,0.208
        loitering_time: 0
        inertia: 3
      neighbor_outside:
        coordinates: 
          0.543,0.245,0.548,0.213,0.493,0.19,0.397,0.148,0.273,0.123,0.142,0.103,0.064,0.103,0,0.114,0,0.304,0.244,0.188,0.379,0.178,0.484,0.2,0.47,0.219
        loitering_time: 0
      entire_frame:
        coordinates: 0,0,1920,0,1920,1080,0,1080
        objects:
          - person
          - cat
    live:
      stream_name: camera_garden3



version: 0.15-0
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    deploy:    # Nvidia GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
#              device_ids: ['0']
              count: 1 # number of GPUs
              capabilities: [gpu]
    container_name: frigate-nvidia
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3-tensorrt
    shm_size: "492mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config:/config
      - /mnt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"

    environment:
      #- YOLO_MODELS=yolov4-608,yolov7x-640
      #- YOLO_MODELS=yolov4-416
      - YOLO_MODELS=yolov7x-640
      - USE_FP16=false
```

### Relevant Frigate log output

```shell
I cant pinpoint whats wrong, i hadded the entire log file
```

### Install method

Proxmox via Docker

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/07fcadfb-217d-4f30-a203-6f5034d224b8)

### Any other information that may be helpful

[frigate-logs.txt](https://github.com/user-attachments/files/18147217/frigate-logs.txt)

6 camera's in the setup
