### DISCUSSION TITLE
[Config Support]: Tricky camera settings help (false positives)

### DISCUSSION THREAD

**Discussion by matknowles** [blakeblackshear/frigate#15536] [Config Support] [answered]
### Describe the problem you are having

Hi, I'm having a bit of trouble with false positives on a camera that overlooks my driveway. I've set everything I can think of short of a motion mask, but as the cars dont stay in the same spot I don't see how that'll fix the issue.

It seems like reflections in the car bodywork is being mistaken for a person. Also lights at night with passing cars triggers as a person sometimes too (worth noting not too often, but it's linked to TTS notifications on speakers all around my house so it's a bit annoying when it happens)

I've tested and set the ratio,size and I've kept bumping min_score and threshold up to help, but it's having the opposite effect now. An example, yesterday there was a bit of direct sunlight and it didn't detect actual people on the driveway.

If it matters, I'm using a Coral USB detector. OPENVINO seems to work well on my new machine, but it adds 10-15% more CPU usage constantly, so is not preferable unless a different detection model might fix it.

I seem to recall a discussion where someone said not to have the min_score and threshold too similar, so maybe this is my issue, but I've tried to keep them as low as possible to maximise detections in tricky lighting etc.

I've also submitted 20 images on Frigate+for this camera, so maybe I could submit more?

Thanks for any advice or help, (I've removed the image out of paranoia.)

I think it's unlucky yet hilarious that the reflections in the bodywork match the size and ratio of an actual person as well, typical.

### Version

0.15.0-6b12a45

### Frigate config file

```yaml
Driveway:
    webui_url: http://192.168.1.14/#/home
    detect:
      #width: 704
      #height: 576
      fps: 5
    enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
        - bird
        - chirp
        - dogs
        - car
        - emergency_vehicle
        - aircraft
        - siren
        - power_tool
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    #record:
    #  retain:
    #    days: 0
    #    mode: all
    objects:
      filters:
        person:
          min_area: 8000 #person at the end of the driveway
          max_area: 135000 #person at side/closer to camera
          min_ratio: 0.25
          max_ratio: 0.5
          min_score: 0.81
          threshold: 0.8
          #min_score: 0.15 #for testing
          #threshold: 0.1 #for testing
    zones:
      DrivewayBetweenCars:
        coordinates: 0.578,0.37,0.382,0.369,0.32,1,0.645,1
        objects:
          - person
          - umbrella
        #filters:
        #  person:
        #    #min_area: 8000
        #    #max_area: 135000
        #    threshold: 0.73
        #    min_score: 0.5
        notifications:
          enabled: true
          mqtt_topic: frigate/driveway/DrivewayBetweenCars
        inertia: 3
        loitering_time: 0
      Driveway_General:
        coordinates: 
          0.19,0.079,0.204,0.376,0.822,0.371,0.866,0.4,0.912,0.42,1,0.545,0.998,0.998,0.231,0.999,0.1,0.368,0.004,0.392,-0.001,0.231
        loitering_time: 0
        objects:
          - backpack
          - bicycle
          - bird
          - cat
          - dog
          - eye glasses
          - handbag
          - hat
          - horse
          - package
          - person
          - suitcase
          - umbrella
        inertia: 3
    review:
      alerts:
        labels:
          - person
        required_zones:
          - DrivewayBetweenCars
          - Driveway_General
    motion:
      mask: 0.779,0.917,0.995,0.922,0.995,0.943,0.777,0.941
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

**Comment by hawkeye217** [comment]
This is almost certainly model related. 

I'd definitely suggest submitting many more examples to Frigate+ and then using a tuned Frigate+ model. I had similar issues with reflections causing false positives, which have all been mitigated now with a Frigate+ model.

**Reply by matknowles** [reply]
OK thanks for that, I'll get on it. How many images in your experience before you noticed a difference? I'm hoping not hundreds as I have to label every object in each image which is pretty tedious.

**Reply by hawkeye217** [reply]
Are you a Frigate+ subscriber? Blake introduced "suggestions" recently which automatically puts bounding boxes around objects when verifying images. It's a huge time-saver.

**Reply by NickM-27** [reply]
>  I'm hoping not hundreds as I have to label every object in each image which is pretty tedious.

To be clear if you subscribe to Frigate+ then your images will be automatically annotated with the suggestions feature

**Reply by hawkeye217** [reply]
I noticed a difference after perhaps a few dozen images, with an 80/20 ratio of true positives to false positives.

**Reply by matknowles** [reply]
Yes I am subscribed. Didn't know about that, it's been a little while since I did any submissions because of that very issue, that sounds great, thanks.

**Reply by matknowles** [reply]
Oh wow that's fantastic. Just checked and indeed everything is automatically boxed. That's my afternoon sorted. I'll try and post back with results.

Do I have to resubmit a new model request to incorporate the new images? I'd assume so.

**Reply by hawkeye217** [reply]
> Do I have to resubmit a new model request to incorporate the new images? I'd assume so.

Yes

**Comment by matknowles** [comment]
As an update, my plan was to reduce the detection sensitivity, flag false positives in frigate+, get a new model then hope the false positives stop. I've requested a new model and incorporated it into my config, but unlike the initial case above, it seems like (at least some of) the false positives aren't showing in review or explore so that I can submit them as false positives. I'm wondering if it's an issue with how my home assistant automation is setup?

It's pretty simple; if person occupancy becomes occupied in either of the driveway zones it sends a TTS alert to my speakers.

I'm wondering why HA might be getting that trigger but frigate isn't recording it as an event/detection? I'm assuming it's my config, as that's all my tiny brain can come up with.

```
  Driveway:
    webui_url: http://192.168.1.14/#/home
    #detect:
      #width: 704
      #height: 576
     # fps: 5
    enabled: true
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
        - bird
        - chirp
        - dogs
        - car
        - emergency_vehicle
        - aircraft
        - siren
        - power_tool
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_Third
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    #record:
    #  retain:
    #    days: 0
    #    mode: all
    objects:
      filters:
        person:
          min_area: 8000
          max_area: 135000
          min_ratio: 0.25
          max_ratio: 0.5
          min_score: 0.7
          threshold: 0.68
          #min_score: 0.15
          #threshold: 0.1
    zones:
      DrivewayBetweenCars:
        coordinates: 0.578,0.37,0.382,0.369,0.32,1,0.645,1
        objects:
          - person
          - umbrella
        #filters:
        #  person:
        #    #min_area: 8000
        #    #max_area: 135000
        #    threshold: 0.73
        #    min_score: 0.5
        notifications:
          enabled: true
          mqtt_topic: frigate/driveway/DrivewayBetweenCars
        inertia: 3
        loitering_time: 0
      Driveway_General:
        coordinates: 
          0.19,0.079,0.204,0.376,0.822,0.371,0.866,0.4,0.912,0.42,1,0.545,0.998,0.998,0.231,0.999,0.1,0.368,0.004,0.392,-0.001,0.231
        loitering_time: 0
        objects:
          - backpack
          - bicycle
          - bird
          - cat
          - dog
          - eye glasses
          - handbag
          - hat
          - horse
          - package
          - person
          - suitcase
          - umbrella
        inertia: 3
    review:
      alerts:
        labels:
          - person
    motion:
      mask: 0.779,0.917,0.995,0.922,0.995,0.943,0.777,0.941
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
```

I can't see how to format the yaml properly, grr!! Sorry about that

Thanks
