### DISCUSSION TITLE
[Camera Support]: ReoLink 810A support (without lowering resolution)

### DISCUSSION THREAD

**Discussion by paul-fornage** [blakeblackshear/frigate#15543] [Camera Support] [answered]
### Describe the problem you are having

First of all, I have a list of about 4 issues that I need to resolve, so if you guys have a Discord or Matrix channel that I could seek help in without putting extra burden on the devs, let me know.

I cannot seem to get my ReoLink 810A camera to work with frigate for the life of me, it 'works on my machine' with `ffmpeg` and no funny business, but Frigate just won't do it, no matter what I try. I have tried every resource I can find, but the only thing that works is lowering the camera's resolution and using HTTP FLV, which as I understand is not supported for 4k. I wouldn't mind using a lower resolution, but unfortunately the 'devs' at ReoLink implemented lowering resolution as cropping the video, which makes the camera unusable for my application.

When I use the config I provided, it will partially work, giving me audio and images every once in a while, but no video.

My system has an RX7600 and R7 7700X, running TrueNas with frigate as a docker container.

I feel like I have tried everything, but I will take any suggestions I can take. 

Huge fan of this project and I really want to make this work, or help it succeed. If there are any tasks you guy's need done, I am happy to put in some PRs.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.8

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.8:8555
      - stun:8555
  streams:
    small_garage_cam:
      - "ffmpeg:rtsp://admin:<the_correct_password>@192.168.1.161/h265Preview_01_main"
 # Have tried, removing 'ffmpeg', changing h265 to h264, and everything else imaginable.


cameras:
  

  small_garage_cam:
    enabled: true
    detect:
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/small_garage_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - dog
        - cat
    mqtt:
      # Optional: print a timestamp on the snapshots (default: True)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: True)
      bounding_box: true




version: 0.14
```

### Relevant Frigate log output

```shell
2024-12-16 19:01:19.792880294  [INFO] Preparing Frigate...
2024-12-16 19:01:19.798237429  [INFO] Starting Frigate...
2024-12-16 19:01:20.744313680  [2024-12-16 19:01:20] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-12-16 19:01:20.744334199  [2024-12-16 19:01:20] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-12-16 19:01:20.750425061  [2024-12-16 19:01:20] frigate.util.config            INFO    : frigate config does not need migration...
2024-12-16 19:01:20.771183715  [2024-12-16 19:01:20] peewee_migrate.logs            INFO    : Starting migrations
2024-12-16 19:01:20.771410154  [2024-12-16 19:01:20] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-12-16 19:01:20.850304298  [2024-12-16 19:01:20] frigate.app                    INFO    : Recording process started: 376
2024-12-16 19:01:20.854752117  [2024-12-16 19:01:20] frigate.app                    INFO    : Recording process started: 385
2024-12-16 19:01:20.855893112  [2024-12-16 19:01:20] frigate.app                    INFO    : go2rtc process pid: 98
2024-12-16 19:01:20.870749313  [2024-12-16 19:01:20] detector.cpu                   INFO    : Starting detection process: 421
2024-12-16 19:01:20.872808584  [2024-12-16 19:01:20] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-12-16 19:01:20.873286742  [2024-12-16 19:01:20] frigate.app                    INFO    : Output process started: 423
2024-12-16 19:01:20.899239131  [2024-12-16 19:01:20] frigate.app                    INFO    : Camera processor started for small_garage_cam: 437
2024-12-16 19:01:20.903732930  [2024-12-16 19:01:20] frigate.app                    INFO    : Capture process started for small_garage_cam: 445
2024-12-16 19:16:46.639137225  [2024-12-16 19:16:46] frigate.comms.dispatcher       INFO    : Setting motion threshold for small_garage_cam: 30
2024-12-16 19:16:46.639722233  [2024-12-16 19:16:46] frigate.comms.dispatcher       INFO    : Setting motion contour area for small_garage_cam: 10
2024-12-16 19:16:50.587253758  [2024-12-16 19:16:50] frigate.comms.dispatcher       INFO    : Setting motion threshold for small_garage_cam: 30
2024-12-16 19:16:50.587662286  [2024-12-16 19:16:50] frigate.comms.dispatcher       INFO    : Setting motion contour area for small_garage_cam: 10
```

### Relevant go2rtc log output

```shell
2024-12-16 19:01:19.794887035  [INFO] Removing stale config from last run...
2024-12-16 19:01:19.795462302  [INFO] Preparing new go2rtc config...
2024-12-16 19:01:20.009526539  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-12-16 19:01:20.030312143  [INFO] Starting go2rtc...
2024-12-16 19:01:20.155050613  19:01:20.155 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-12-16 19:01:20.155052853  19:01:20.155 INF config path=/dev/shm/go2rtc.yaml
2024-12-16 19:01:20.155403762  19:01:20.155 INF [rtsp] listen addr=:8554
2024-12-16 19:01:20.155410942  19:01:20.155 INF [api] listen addr=:1984
2024-12-16 19:01:20.156665026  19:01:20.156 INF [webrtc] listen addr=:8555
2024-12-16 19:01:29.793213152  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://admin:Bd7DQsJWPI44cK@192.168.1.161/h265Preview_01_main
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:Bd7DQsJWPI44cK@192.168.1.161/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : reolink rtsp stream
  Duration: N/A, start: 0.000375, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
#
```

### Frigate stats

```json
{
  "cameras": {
    "small_garage_cam": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 445,
      "detection_enabled": true,
      "detection_fps": 4.5,
      "ffmpeg_pid": 453,
      "pid": 437,
      "process_fps": 5,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "106": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "107": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "4.0"
    },
    "131": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "13325": {
      "cmdline": "/bin/sh",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "14815": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15002": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "174": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "175": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "176": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "178": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "188": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "24": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "312": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "374": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.7"
    },
    "376": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "1.9"
    },
    "385": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.7"
    },
    "420": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "421": {
      "cmdline": "frigate.detector.cpu ",
      "cpu": "37.0",
      "cpu_average": "18",
      "mem": "1.8"
    },
    "423": {
      "cmdline": "frigate.output       ",
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "1.8"
    },
    "437": {
      "cmdline": "frigate.process:small_garage_cam",
      "cpu": "4.3",
      "cpu_average": "2",
      "mem": "1.8"
    },
    "445": {
      "cmdline": "frigate.capture:small_garage_cam",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "1.7"
    },
    "45": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "453": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/small_garage_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/small_garage_cam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.6",
      "cpu_average": "1",
      "mem": "1.8"
    },
    "455": {
      "cmdline": "ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.161/h265Preview_01_main -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1980be62da5afb85a65f6190f744a52f",
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "46": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "470": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "475": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "87": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "frigate.full_system": {
      "cpu": "10.9",
      "mem": "86.9"
    }
  },
  "detection_fps": 4.5,
  "detectors": {
    "cpu": {
      "detection_start": 0,
      "inference_speed": 22.07,
      "pid": 421
    }
  },
  "gpu_usages": {
    "amd-vaapi": {
      "gpu": "0.83%",
      "mem": "55.69%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 374
    },
    "recording": {
      "pid": 376
    },
    "review_segment": {
      "pid": 385
    }
  },
  "service": {
    "last_updated": 1734376834,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 1022.7,
        "mount_type": "tmpfs",
        "total": 1024,
        "used": 1.3
      },
      "/media/frigate/clips": {
        "free": 10897890.6,
        "mount_type": "zfs",
        "total": 12372180.4,
        "used": 1474289.8
      },
      "/media/frigate/recordings": {
        "free": 10897890.6,
        "mount_type": "zfs",
        "total": 12372180.4,
        "used": 1474289.8
      },
      "/tmp/cache": {
        "free": 4055.7,
        "mount_type": "tmpfs",
        "total": 4096,
        "used": 40.3
      }
    },
    "temperatures": {

    },
    "uptime": 1154,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

RLC-810A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/585e326f-5cf3-4c28-bba9-d1238c65607f)

### Any other information that may be helpful

I also have a second setup for another location that has similar but worse issues. I'm not seeking help for that yet, but it at least makes me think that it's nothing specific to this network.

Also, I am aware that this issue has been brought up before, but I've been trying to fix this issue following suggestions from those issues for about a month now, and I really can't figure it out.

**Comment by paul-fornage** [comment]
[Video showing the issue in the GUI](https://youtu.be/o3b3JqRY2CU)

**Reply by clsferguson** [reply]
video is private.

**Reply by paul-fornage** [reply]
Sorry, should be up now

**Comment by clsferguson** [comment]
> ```yaml
>   small_garage_cam:
>     enabled: true
>     detect:
>       width: 640
>       height: 360
>       fps: 5
>     ffmpeg:
>       inputs:
>         - path: rtsp://127.0.0.1:8554/small_garage_cam
>           input_args: preset-rtsp-restream
>           roles:
>             - record
>             - detect
> ```

just to clarify, this is a left over from trying to troubleshoot? the detect width and height don't match the native stream.

**Reply by paul-fornage** [reply]
Thank you for the response!

Yes, sorry, that's from when I had a separate detection stream. 

I can confirm this still does not work with the correct res and fps set. However, there are a couple changes;
1. There is a warning saying this: 
```
small_garage_cam detect fps is set to 25. This does NOT need to match your camera's frame rate. High values could lead to reduced performance. Recommended value is 5.
```
That checks out.
2. The CPU usage noticeably increases. This is expected because I am using a CPU detector for now.

**Comment by levski** [comment, marked as answer]
i got a pair of 810a myself and had it working prior to my rebuild.
since the rebuild, i got 4 e1 outdoor pros connected to frigate using 4k h265, no go2rtc.

i had to covert the 4k video to h264 when i was using go2rtc. iirc it's go2rtc that's finicky when passwords have special characters in the password. test to confirm.

**Reply by paul-fornage** [reply]
Thanks for the response!

This was it! I had no idea I could transcode the codec with the hashtags. 
Thanks for leading me down the right path!

**Reply by ginkel** [reply]
@paul-fornage Would you mind sharing your working config? Currently also struggling with my 810A... Thanks!

**Comment by m0ngrl** [comment]
I'm adding a comment here for users searching for RLC-810A Frigate config as this thread comes up when searching for a fix with Home Assistant.

## Environment
- Home Assistant OS 2026.2.2
- Frigate 0.16.4 (Add-on)

## My working config

```

mqtt:
  enabled: true

#ffmpeg:
#  hwaccel_args: preset-intel-qsv-h264 # I was having issues until I commented this block out
#  input_args: preset-rtsp-restream
#  output_args:
#    record: preset-record-generic-audio-copy

record:
  enabled: True
  retain:
    days: 3
    mode: all

go2rtc:
  streams:
    RLC810A:
      - rtsp://<username>:<password>@<cameraIP>:554/h264Preview_01_main
    RLC810A_sub:
      - rtsp://<username>:<password>@<cameraIP>:554/h264Preview_01_sub

cameras:
  RLC810A: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/RLC810A # Use loopback address or the IP address of frigate if it is hosted outside of HA OS
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/RLC810A_sub # Use loopback address or the IP address of frigate if it is hosted outside of HA OS
          roles:
            - detect

detect:
  enabled: true
version: 0.16-0

```

These Reddit threads also assisted:
https://www.reddit.com/r/frigate_nvr/comments/1ak5j2q/frigate_with_reolink_cameras_using_rtsp_and/
https://www.reddit.com/r/frigate_nvr/comments/19f7amr/struggling_with_adding_cameras_to_frigate_config/
