### DISCUSSION TITLE
Can I set up alerts for people in one zone and dogs in another?

### DISCUSSION THREAD

**Discussion by USER19464727** [blakeblackshear/frigate#15542] [Ask A Question] [answered]
I can't seem to figure this out and it's probably simpler than I'm making it. Let's say I want Frigate "alerts" for a person in my driveway zone and dogs in my yard zone. The following, however, would also alert for dogs in my driveway and people in my yard. 

```
    review:
      alerts:
        labels:
          - person
          - dog
        required_zones:
          - driveway
          - yard
```

I believe I could restrict my driveway zone to just people, but I might want to detect dogs in my driveway--just not have it be an alert. The following shows what I want to do, although this code would not work:

```
    review:
      alerts:
        labels:
          person:
            required_zones: 
             - driveway
          dog: 
            required_zones:
             - yard
```

**Comment by hawkeye217** [comment]
You can configure alerts based on specific labels and zones. Here's how to set this up:

1. First, add both 'person' and 'dog' to your alerts labels  [(1)](https://docs.frigate.video/configuration/review/#restricting-alerts-to-specific-labels) :

```yaml
review:
  alerts:
    labels:
    - person
    - dog
```

2. Then configure your zones with specific object restrictions  [(2)](https://docs.frigate.video/configuration/zones/) :

```yaml
cameras:
  name_of_your_camera:
    zones:
      driveway:
        coordinates: ... (your driveway coordinates)
        objects:
        - person
      yard:
        coordinates: ... (your yard coordinates)
        objects:
        - dog
```

Note that zone presence is evaluated based on the bottom center of the bounding box for the object . Make sure your zones are properly defined to cover the areas you want to monitor.

**Reply by USER19464727** [reply]
But if I do that, it would never detect dogs in the driveway, right? What if I do want dogs detected in the driveway--I just don't want it to be an alert.

**Reply by hawkeye217** [reply]
You can set up both alerts and detections separately. Here's how:

```yaml
cameras:
  name_of_your_camera:
    review:
      alerts:
        labels:
        - person
        required_zones:
        - driveway
      detections:
        labels:
        - dog
        - person
        required_zones:
        - driveway
        - yard
```
 [(1)](https://docs.frigate.video/configuration/review/#restricting-alerts-to-specific-labels) 

This configuration will:
- Create alerts only for people in the driveway 
- Still detect both dogs and people in both zones as detections 

The main difference between alerts and detections is that they allow you to prioritize which events are more important while still tracking everything else .

**Reply by USER19464727** [reply]
I had wanted to reserve the detections category for other purposes. If I understand correctly, it seems like from your responses that it is not possible to have people in the driveway and dogs in the yard be an alert (while still having dogs in the driveway and people in the yard being detected as objects and recorded). I would have to make one of them a detection instead of an alert (which I don't really want to do because I was reserving that for another use) OR I would have to disable the detection of one of them in the zone of the other (which I don't want to do because I still want to have the footage of the other objects--just not have it classified as an alert).

**Reply by hawkeye217** [reply, marked as answer]
You can have overlapping zones  [(1)](https://docs.frigate.video/configuration/zones/) . You could create:
1. A "driveway_person_alert" zone for person alerts
2. A "yard_dog_alert" zone for dog alerts
3. A "driveway" zone for all objects
4. A "yard" zone for all objects

Here's an example configuration:

```yaml
cameras:   
  name_of_your_camera:   
    review:   
      alerts:   
        required_zones:   
          - driveway_person_alert
          - yard_dog_alert   
    zones:   
      driveway_person_alert:   
        coordinates: ... (driveway area)   
        objects:   
          - person   
      yard_dog_alert:   
        coordinates: ... (yard area)   
        objects:   
          - dog
      driveway:
        coordinates: ... (same driveway area)
      yard:
        coordinates: ... (same yard area)
```


This way, you can:
- Get alerts for people in the driveway_person_alert zone
- Get alerts for dogs in the yard_dog_alert zone
- Still detect and record all objects in both the driveway and yard zones

Note that zones can overlap and share the same coordinates, and presence in a zone is evaluated based on the bottom center of the bounding box for the object.
