### DISCUSSION TITLE
[Bug]: No notification on manually triggered Events

### DISCUSSION THREAD

**Discussion by AbDhops** [blakeblackshear/frigate#15558] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have running frigate which monitors different cameras. Doorbell and Front cameras are few of them. On the event of doorbell pressed, I am triggering the manual event over API. I am also getting successfull notification as per docs. 
However, like other events (e.g. detection of person), no message is published over MQTT for this event. Which does not leads to notification. 

### Steps to reproduce

1. Trigger manual event as descirbed [here](https://docs.frigate.video/integrations/api/#post-apieventscamera_namelabelcreate)
2. Ensure to get the reply like below
` {"_msgid":"1f0cb5e8f2dc3ae3","payload":"{\"event_id\":\"1734460207.817876-h4qvwe\",\"message\":\"Successfully created event.\",\"success\":true}\n","topic":"","statusCode":200,"headers":{"server":"nginx/1.25.3","date":"Tue, 17 Dec 2024 18:30:07 GMT","content-type":"application/json","content-length":"95","connection":"keep-alive","cache-control":"no-store","x-node-red-request-node":"74f83018"},"responseUrl":"http://IP_ADDRESS:5000/api/events/Back/doorbell/create","redirectList":[],"retry":0}`
3. Monitor events over MQTT `frigate/events`

EXPECTED : 
Event notification over MQTT

Observed :
No notification over MQTT

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: IP
  user: viseron
  password: 9tmEpozxXQ35BEaj65yG
  topic_prefix: home/frigate_nvr

detectors:
  coral:
    type: edgetpu
    device: usb

# logger:
  # Optional: default log level (default: shown below)
  # default: warning

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: br
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

objects:
  track:
    - person
    - dog
    - cat
  filters:
    person:
      min_score: 0.6
      threshold: 0.7
      min_area: 10000

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 3
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects

detect:
  width: 896
  height: 672
  fps: 7

# ffmpeg:
  # hwaccel_args: preset-vaapi

cameras:
  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://FRIAGATE_USER_ID:FRIAGATE_PASSWORD@IP:554/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://FRIAGATE_USER_ID:FRIAGATE_PASSWORD@IP:554/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 428,104,0,224,0,0,896,0,896,196
    ui:
      order: 0
  Back: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: 
            rtmp://IP/bcs/channel0_main.bcs?channel=0&stream=0&user=FRIAGATE_USER_ID&password=FRIAGATE_PASSWORD
          input_args: 
            preset-rtmp-generic
          roles:
            - record
        - path: 
            rtmp://IP/bcs/channel0_sub.bcs?channel=0&stream=0&user=FRIAGATE_USER_ID&password=FRIAGATE_PASSWORD
          input_args: 
            preset-rtmp-generic
          roles:
            - detect
    motion:
      mask:
        - 0,188,326,0,538,21,896,76,896,0,896,0,896,0,0,0
    ui:
      order: 1
  Doorbell:
    ffmpeg:
      inputs:
        - path: 
            rtsp://FRIAGATE_USER_ID:FRIAGATE_PASSWORD@IP:554/Preview_01_main
          input_args: 
            preset-rtsp-restream
          roles:
            - record
    record:
      sync_recordings: true
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 30
          mode: all
    ui:
      order: 2
birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.14.1 # 20 Sep 2024
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: "64mb" # update for your cameras based on calculation above
    # hostname: frigate
    mac_address: SOME_MAC
    networks:
      ext_smartNet:
        ipv4_address: SOME_IP   # <-- Update
    volumes:
      - ./data/config:/config
      - ./data/media:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: i965

networks:
  ext_smartNet:
    external: true
    name: smartNet
```

### Relevant Frigate log output

```shell
<NO LOGS AVAILABLE>
```

### Relevant go2rtc log output

```shell
<NO LOGS AVAILABLE>
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/361e6a25-e61a-4677-9dca-e394df105a03)

### Any other information that may be helpful

I also noticed that events are getting created. I could see them "under review" section. But I am not able to play them. Not sure if those are getting stored and may be because of that it is not creating an events ?
