### DISCUSSION TITLE
[Detector Support]:  iGPU or ARC A380 GPU

### DISCUSSION THREAD

**Discussion by MomosX** [blakeblackshear/frigate#15557] [Detector Support]
### Describe the problem you are having

Hello,
I'm using Frigate in my Truenas Scale EE (24.10) with a Coral USB and HW acceleration form the Intel CPU with good results.
However i recently got an Intel ARC A380 GPU and wanted to configure Frigate to use that.

In the Frigate app from Truenas Scale EE there is only the option to pass GPU to the app.
![image](https://github.com/user-attachments/assets/0ab2d0ef-f6d6-4dfe-b719-e4982ba63f6f)
This works to pass both the iGPU and the A380 to the Frigate App (confirmed looking at the transcode settings in Plex where both are available to choose from.)

However i'm not sure how to only choose the A380 as detector and not the iGPU in Frigate.  Using the standard config seems to pick the iGPU, but i'm not sure about that either.

Hardware info from Frigate:
Vainfo Output
Return Code: 0
Process Output:
vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()  

This would seem is the iGPU.

Any ideas please ?

Thank you
 

### Version

0.14.1

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Wyze V3

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d6f97aee-3511-4931-82e4-83b7333374d8)

**Comment by NickM-27** [comment]
the main way to do this is via docker, so it is not great that truenas does not let you select a particular GPU

**Reply by MomosX** [reply]
There is not much flexibility in the Truenas Electric Eel apps.  They are good for novice users like myself but then you get into this sort of issues.   There is however terminal access to the Frigate container.
What would be the secondary way please ?  
Cheers

**Reply by MomosX** [reply]
Turns out there is a way to see what the ARC card doing in Truenas 24.10.
![image](https://github.com/user-attachments/assets/4f872a7b-e902-47b5-bd38-f8847a928cb8)

Seems like Frigate is using the card also.  But the performance is not very good.
![image](https://github.com/user-attachments/assets/d11f62d6-16e4-4a09-a6c8-f1797a66ac69)

Using the Coral USB , Detector CPU usage never looked so busy.

**Reply by NickM-27** [reply]
right, it is using a different model which requires different steps to prepare the image

**Comment by MomosX** [comment]
Cheers ! will keep an eye on the performance using the ARC card and switch back to Coral if needed.

**Reply by MomosX** [reply]
Hi,  i reopened the topic because i simply don't understand how it works :( 

Please let me explain in detail with pics worth a 1000 words:

![image](https://github.com/user-attachments/assets/f3716d70-475a-49b4-bb2f-a42a4430a907)
Intel iGPU and Intel ARC A380 , both available to Frigate 

![image](https://github.com/user-attachments/assets/81d7ab4e-2ca6-4376-ba8b-22cbd4a48131)
This is what is reported from gpu top, both outside the Frigate contaier and inside it.

I gave up for now to use the A380 as detector, switched back to Coral USB.  

I would like to make the HW acceleration work on the A380.

TEST1:

Setting it up like this:
`detectors:
  coral_usb:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD129`

works, but the result is weird: huge CPU usage, very bad Coral Inference.
![image](https://github.com/user-attachments/assets/9e70e303-7d49-4607-8d2f-7076af47889f)

gpu-top shows that A380 is used:
![image](https://github.com/user-attachments/assets/4ef4f3c2-09e5-4265-b02c-65ac8764b3b7)


TEST2:

Setting up like this:
detectors:
  coral_usb:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi

works and the result is good:
![image](https://github.com/user-attachments/assets/9c86de79-ecdf-4b79-9480-81b43961bfdd)

but gpu-top shows that the A380 is not used, instead is used the iGPU
![image](https://github.com/user-attachments/assets/3ebb2ec4-cda2-4160-a858-8388c6d4a898)
![image](https://github.com/user-attachments/assets/4039b61b-cb7a-4280-80dd-e7d898805a7d)


I did all sorts of tests and settings.  Can you @NickM-27 please help an old timer figure this out ?

thank you !!!

**Reply by NickM-27** [reply]
There is no way to specify a different GPU be used when both are intel and both inside of the container. I am not familiar with truenas enough to suggest how you would limit it to only one GPU

**Reply by MomosX** [reply]
I am trying to limit it to one GPU, but to the A380 m not the iGPU.
renderD129 specified in ffmpeg will pick the A380, renderD128 will pick the iGPU.  

But the results with renderD129 are very bad.  

How do i reopen the topic maybe someone has the same scenario please ? Can't seem to find the button...

**Comment by MomosX** [comment]
Ha ! i managed to solve it ! 
 As a result CPU usage dropped from 18-23% to 3-6%, memory usage droped with about 50% also ! And inference speed on the Coral is better also.   Power for the entire sistem went down from 110-115 W to 85-95 W - probably because the CPU was drawing more power then the A380 is.

I would say it's a good result :) 

![image](https://github.com/user-attachments/assets/756a9eb6-d7c6-4a94-843d-b1f405eb0ddb)

![image](https://github.com/user-attachments/assets/9466b3d6-f47c-48b2-bf64-ca237b9ee400)

For others who might be struggling with something similar the config that worked is:

detectors:
  coral_usb:
    type: edgetpu
    device: usb

ffmpeg:
  input_args:
    - -rtsp_transport
    - tcp
    - -r
    - '25'
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD129
    - -hwaccel_output_format
    - yuv420p

Will start playing next with openvino detector to compare with the coral.

**Reply by NickM-27** [reply]
to be clear this is not a recommended config in general, using manual hwaccel args reduces efficiency when you scale a camera's stream using detect along with other efficiencies that Frigate is not able to do. 

also those input args override some important input args that Frigate needs to have a steady and reliable stream in many cases.

**Reply by MomosX** [reply]
Understood ! 
Then i'd like to start eliminating them one by one to see if it still works.
Can you please tell me which of those args could stay and not cause any harm ?

Can use me as a "guinea pig" to test Frigate with Intel ARC A380 card :) 

thank you

**Reply by NickM-27** [reply]
Well in general both of the sets of args being manual and not a preset is problematic. But if you are set on using the A380 then the hwaccel args will have to stay if there is no way to specify this in the truenas config.

and to be clear, we already have had a few users including myself testing with Arc cards in Frigate

**Reply by MomosX** [reply]
Using a preset is the best of course.
I was merely trying multiple options , trial and error to see what works.

Is it possible to have something like ?
ffmpeg:
  hwaccel_args: 
    - preset-vaapi 
    - hwaccel_device /dev/dri/renderD129
 
So to use a preset but specify the device ?  It doesnt work in the form i wrote it. 
I think it all boils down to be able to specify the renderD129 and it should work in theory.

**Reply by NickM-27** [reply]
Like I said currently it is not possible, as generally the preset will try all GPUs and pick the first one that works which in this case is the iGPU. We could add an explicit option to the config but this is not currently supported

**Reply by MomosX** [reply]
ok. thank you very much for the patience:)  
would be great if such an explicit option would be allowed/added , from all my searches there are quite a few folks that struggle with the same issue.
Cheers !

**Reply by MomosX** [reply]
Hi,
An update as i wrote in the Truenas forum and devs replied that "Dockers GPU support for selecting is limited to nvidia only."
So nothing they can do about selecting Intel GPU's for now.
https://forums.truenas.com/t/intel-gpu-passthrough-to-apps-scale-ee-24-10/27956/3

Plex app in the same Truenas system has this option to select between GPU and it's working,   so hopefully when you get a chance and time maybe this could somehow be implemented also.

Thank you !!!

**Reply by rupisaini123** [reply]
@MomosX, are you able to figure out how to use detector using intel arc inside truenas scale?

**Reply by MomosX** [reply]
sure did. use openvino detectors.  If you have multiple GPU (like the ARC and iGPU) , you have to specify in the Frigate environment variables which one to use. see https://forums.truenas.com/t/intel-gpu-passthrough-to-apps-scale-ee-24-10/27956/5

**Reply by rupisaini123** [reply]
i got everything working, thank you very much.
but i still see some ffmpeg running on CPU when i run top command in container
<img width="1340" height="650" alt="image" src="https://github.com/user-attachments/assets/28f57f26-4a4b-414a-aeed-5b4d14468c0d" />

Here are the results from intel_gpu_top (using arc a310)
<img width="2928" height="730" alt="image" src="https://github.com/user-attachments/assets/27a94cb8-4c71-4d36-ab76-8f6ee79d0184" />

i am not able to figure out why CPU is still being used by ffmpeg
Trying to stream ring camera stream using ring-mqtt and below is the configuation

```
mqtt:
  enabled: false

detectors:
  ov:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
  ov_2:
    type: openvino
    device: GPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  Garage: # <------ Name the camera
    enabled: true
    ffmpeg: 
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.1.67:8554/9c7613b203a1_live # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
          
  FrontDoor: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.1.67:8554/047bcb1d9787_live # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion

  Backyard: # <------ Name the camera
    enabled: true
    ffmpeg: 
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.1.67:8554/48701e599b5b_live #<----- The stream you want to use for detection
          roles:
            - record
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      # width: 640
      # height: 480
      fps: 5
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
detect:
  enabled: true
version: 0.16-0
```

please let me know if i have missed anything

**Comment by MomosX** [comment]
heres mine:
the iGPU
<img width="3056" height="471" alt="image" src="https://github.com/user-attachments/assets/4e641df8-2216-45ce-b3e8-dd2cc6c611f3" />


The Arc380
<img width="3037" height="765" alt="image" src="https://github.com/user-attachments/assets/557f2e6e-a53a-4051-8a1e-fa0f3205a938" />

and my config:
```
mqtt:
  enabled: true
  host: 
  user:
  password:
detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
  ov_2:
    type: openvino
    device: GPU

model:
  path: plus://................

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
```

I'd change the ffmpeg to vaapi. i think this is the recommended settings in the manual.

I'm in no way an expert, just a regular user, so you have to experiment.   Processes on the CPU you might still see if Frigate has to resize the picture because the camera stream size does not match the detect settings maybe.
