### DISCUSSION TITLE
[Config Support]: Only Person alerts, although other options enabled.

### DISCUSSION THREAD

**Discussion by easez88** [blakeblackshear/frigate#15560] [Config Support] [answered]
### Describe the problem you are having

Only person is creating alerts, but cars are not. 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    garage_camera_main:
      - rtsp://192.168.1.10:13841/0e2fca2e77bd2734
      - ffmpeg:garage_camera_main#audio-opus
    garage_camera_sub:
      - rtsp://192.168.1.10:13841/682fcb36f7cd6841
      - ffmpeg:garage_camera_sub#audio-opus
    front_yard_main:
      - rtsp://192.168.1.10:13543/89dc37e6766f971f
      - ffmpeg:front_yard_main#audio-opus
    front_yard_sub:
      - rtsp://192.168.1.10:13543/d76df9ca8f972a66
      - ffmpeg:front_yard_sub#audio-opus

cameras:
  ##########################################################
  ## Garage Camera
  ##########################################################
  garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/garage_camera_main
          roles:
            - record
        - path: rtsp://192.168.1.10:8554/garage_camera_sub
          roles:
            - detect
    motion:
      mask: 0.612,0.923,1,0.923,1,0.973,0.611,0.975
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 
          coordinates here
        loitering_time: 0
        inertia: 3
      entryway:
        coordinates: coordinates here
        loitering_time: 0
        inertia: 3
      front_yard:
        coordinates:  coordinates here
        loitering_time: 0
        inertia: 3
      road:
        coordinates: coordinates here
        loitering_time: 0

  ##########################################################
  ## Front Yard
  ##########################################################
  front_yard_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/front_yard_main
          roles:
            - record
        - path: rtsp://192.168.1.10:8554/front_yard_sub
          roles:
            - detect
    motion:
      mask: 0.605,0.924,1,0.923,1,0.973,0.606,0.975
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    zones:
      entryway:
        coordinates: coordinates here
        loitering_time: 0
        inertia: 3
      driveway:
        coordinates: coordinates here
        loitering_time: 0
        inertia: 3
      fronty_yard:
        coordinates: coordinates here
        loitering_time: 0
        inertia: 3
      road:
        coordinates: coordinates here
        loitering_time: 0

auth:
  reset_admin_password: false
  trusted_proxies:
    - 192.168.1.0/24

mqtt:
  enabled: true
  host: 192.168.1.5
  port: 1883
  user: user
  password: Pass
  stats_interval: 60

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - cat
      - dog

detectors:
  cpu1:
    type: cpu
    num_threads: 3

record:
  enabled: true
  retain:
    days: 7
    mode: all

  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 7
version: 0.14
```

### Relevant Frigate log output

```shell
Nothing in logs, mqtt doesn't fire either.
```

### Relevant go2rtc log output

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Windows

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11 # For Raspberry Pi 4B
    #   - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - config:/config
      - media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8981:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
volumes:
  config:
  media:
```

### Object Detector

CPU (no coral)
