### DISCUSSION TITLE
[Bug]: v0.15.0-Beta3 - Review Preview URL Endless Loop

### DISCUSSION THREAD

**Discussion by easez88** [blakeblackshear/frigate#15579] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When going to the URL `https://nvr.domain.tld/review?id={{review_id}}` Frigate has and endless loop

https://github.com/user-attachments/assets/5ab609a7-1159-41a0-b4af-208cf959f569

### Steps to reproduce

1. Get the Id of a review Item
2. Go to the Review Url `https://nvr.domain.tld/review?id={{review_id}}`
3. Experience Loop

### Version

0.15.0-6b12a45

### In which browser(s) are you experiencing the issue with?

Chrome, Edge, Safari (IOS)

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    garage_camera_main:
      - rtsp://192.168.1.10:13841/0e2fca2e77bd2734
      - ffmpeg:garage_camera_main#audio-opus
    garage_camera_sub:
      - rtsp://192.168.1.10:13841/682fcb36f7cd6841
      - ffmpeg:garage_camera_sub#audio-opus
    front_yard_main:
      - rtsp://192.168.1.10:13543/89dc37e6766f971f
      - ffmpeg:front_yard_main#audio-opus
    front_yard_sub:
      - rtsp://192.168.1.10:13543/d76df9ca8f972a66
      - ffmpeg:front_yard_sub#audio-opus

cameras:
  ##########################################################
  ## Garage Camera
  ##########################################################
  garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/garage_camera_main
          roles:
            - record
        - path: rtsp://192.168.1.10:8554/garage_camera_sub
          roles:
            - detect
    motion:
      mask: 0.612,0.923,1,0.923,1,0.973,0.611,0.975
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 
          0.933,0.971,0.648,0.854,0.559,0.812,0.363,0.718,0.255,0.648,0.228,0.608,0.127,0.654,0,0.714,0.037,1,0.234,1,0.93,1
        loitering_time: 0
        inertia: 3
      entryway:
        coordinates: 
          0.559,0.808,0.649,0.848,0.935,0.969,0.963,0.785,0.978,0.577,0.977,0.572,0.954,0.609,0.938,0.629,0.759,0.591
        loitering_time: 0
        inertia: 3
      front_yard:
        coordinates: 
          0.232,0.608,0.259,0.651,0.361,0.714,0.556,0.811,0.762,0.587,0.937,0.629,0.978,0.572,0.98,0.457,0.726,0.41
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0,0.714,0.235,0.611,0.45,0.518,0.61,0.457,0.738,0.4,0.731,0.363,0.633,0.399,0.56,0.419,0.415,0.469,0.224,0.54,0.123,0.581,0,0.628
        loitering_time: 3
        inertia: 3

  ##########################################################
  ## Front Yard
  ##########################################################
  front_yard_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/front_yard_main
          roles:
            - record
        - path: rtsp://192.168.1.10:8554/front_yard_sub
          roles:
            - detect
    motion:
      mask: 0.605,0.924,1,0.923,1,0.973,0.606,0.975
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      entryway:
        coordinates: 0.104,0.953,0.305,0.838,0.514,0.688,0.271,0.519,0.039,0.606,0.085,0.883
        loitering_time: 0
        inertia: 3
      driveway:
        coordinates: 
          0.046,0.603,0.275,0.519,0.429,0.459,0.647,0.408,0.503,0.369,0.356,0.393,0.198,0.445,0.034,0.5
        loitering_time: 0
        inertia: 3
      fronty_yard:
        coordinates: 
          0.282,0.521,0.38,0.589,0.517,0.683,0.384,0.789,0.197,0.901,0.101,0.954,0.106,1,1,1,1,0.53,0.647,0.403,0.426,0.461
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0.998,0.444,0.998,0.524,0.741,0.429,0.646,0.402,0.504,0.368,0.383,0.346,0.302,0.323,0.354,0.303,0.438,0.308,0.566,0.323,0.69,0.352,0.876,0.403
        loitering_time: 3

objects:
  track:
    - person
    - car
    - dog
    - cat

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - cat
      - dog

record:
  enabled: true
  retain:
    days: 7
    mode: all

  alerts:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 15
  detections:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 7

detectors:
  cpu1:
    type: cpu
    num_threads: 3

auth:
  reset_admin_password: false
  trusted_proxies:
    - 192.168.0.0/16

mqtt:
  enabled: true
  host: 192.168.1.5
  port: 1883
  user: user
  password: pass
  stats_interval: 60
version: 0.15-0

notifications:
  enabled: 'true'
  email: myemail
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3
    shm_size: "512mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11 # For Raspberry Pi 4B
    #   - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - config:/config
      - media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8981:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
volumes:
  config:
  media:
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Windows

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolinks

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/4f24d826-1a5d-4334-9c4f-7eace73bcc97)
![image](https://github.com/user-attachments/assets/bcdfed1d-636e-492c-aab7-98272f819851)
![image](https://github.com/user-attachments/assets/b8a59d18-4fb2-4ff1-af12-1e5b99f547f1)
