### DISCUSSION TITLE
[Detector Support]: labelmap help

### DISCUSSION THREAD

**Discussion by danlo315** [blakeblackshear/frigate#15574] [Detector Support]
### Describe the problem you are having

I'm trying to group all vehicles and animals together, but somehow my vehicle detection has gone way down since I tried labelmap configuration.  Is there something that I'm doing wrong?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    22: animal

  floodlight:
    birdseye:
      order: 4
#    detect:
#      fps: 10
#      width: 640
#      height: 360
#      enabled: true
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    live:
      stream_name: floodlight
    ffmpeg:
      inputs:
        #- path: rtsp://admin:ioT12345@192.168.1.116:554/cam/realmonitor?channel=1&subtype=01&authbasic=64
        - path: rtsp://127.0.0.1:8554/floodlight
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a copy
    motion:
      threshold: 35
      mask:
        - 0.771,0.009,1,0.121,1,0,0,0,0,0.175,0.107,0.008
        - 1,1,1,0.911,0.691,0.925,0.692,1
      contour_area: 20
      improve_contrast: 'true'
    objects:
      track:
        - person
        - vehicle
        - dog
        - animal
      filters:
        person:
          threshold: 0.6
        vehicle:
          max_area: 75000
          threshold: 0.5
          mask:
            - 0.003,0.002,0.998,0.001,1,0.122,0.739,0,0.302,0.028,0,0.174
            - 0.003,0.002,0.998,0.001,1,0.122,0.77,0.009,0.105,0.009,0,0.174
        dog:
          threshold: 0.5
        animal:
          threshold: 0.5
      mask: 0.003,0.002,0.998,0.001,1,0.122,0.77,0.009,0.105,0.009,0,0.174
    zones:
      f_driveway:
        coordinates: 0.749,0.468,0.626,0.162,0.345,0.177,0.23,0.464
        inertia: 1
        loitering_time: 0
        objects: vehicle
      f_bard:
        coordinates: 
          1,0.204,0.768,0.138,0.662,0.126,0.284,0.148,0.089,0.25,0.003,0.317,0,0.18,0.104,0,0.296,0,0.758,0,1,0.128
        inertia: 1
        loitering_time: 0
        objects: vehicle
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/96ae0232-3955-4673-bd9a-05cfe6ee9856)
