### DISCUSSION TITLE
Are restreamed rtsp streams available outside Frigate?

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#15588] [Ask A Question]
I am running Frigate 0.14.1 without issue and have configured it to restream the hi-res rtsp streams using the built-in go2rtc. Are these restreams available outside the Frigate container to services running elsewhere on my network? For example, suppose one of my restreams is ```rtsp://10.57.1.5:8554/front_south```. Should I be able to access this rtsp restream using ```vlc``` on a separate machine in the same subnet?

**Comment by NickM-27** [comment]
assuming you have exposed the port in the docker config, yes

https://docs.frigate.video/configuration/restream#rtsp

**Reply by Cold-Lemonade** [reply]
In my ```frigate.yaml``` file that I use to start Frigate using docker compose, I have the following section:

```
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
```

Does that mean I have exposed the restream outside of Frigate?

**Reply by NickM-27** [reply]
yes

**Reply by Cold-Lemonade** [reply]
My goal is to access the restreams on a separate Ubuntu server that's connected to a monitor that I want to display the feeds on, as a surveillance camera monitor if you will.

So on a separate computer, I am trying to access this restream (namely ```rtsp://10.57.1.5:8554/front_south```) as a test. So I try to execute ```cvlc --fullscreen rtsp://10.57.1.5:8554/front_south``` and I get a the following error. It seems to be saying that it cannot connect to the restream.

```
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[0000620fe65e87a0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[0000620fe66210c0] main interface error: no suitable interface module
[0000620fe652b550] main libvlc error: interface "globalhotkeys,none" initialization failed
[0000620fe66210c0] dummy interface: using the dummy interface module...
[0000720a800015a0] satip stream error: Failed to setup RTSP session
[0000720a8c000c90] main input error: Your input can't be opened
[0000720a8c000c90] main input error: VLC is unable to open the MRL 'rtsp://10.57.1.5:8554/front_south'. Check the log for details.
```

**Reply by NickM-27** [reply]
what is your config?

**Reply by Cold-Lemonade** [reply]
Here's the more verbose log... it clearly doesn't see an rtsp stream there.

```
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[00005d9f969e1550] main libvlc debug: VLC media player - 3.0.20 Vetinari
[00005d9f969e1550] main libvlc debug: Copyright © 1996-2023 the VideoLAN team
[00005d9f969e1550] main libvlc debug: revision 3.0.20-0-g6f0d0ab126b
[00005d9f969e1550] main libvlc debug: configured with ./configure  '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-debug' '--config-cache' '--disable-update-check' '--enable-fast-install' '--docdir=/usr/share/doc/vlc' '--with-binary-version=3.0.20-3build6' '--enable-a52' '--enable-aa' '--enable-aribsub' '--enable-avahi' '--enable-bluray' '--enable-caca' '--enable-chromaprint' '--enable-chromecast' '--enable-dav1d' '--enable-dbus' '--enable-dca' '--enable-dvbpsi' '--enable-dvdnav' '--enable-faad' '--enable-flac' '--enable-fluidsynth' '--enable-freetype' '--enable-fribidi' '--enable-gles2' '--enable-gnutls' '--enable-harfbuzz' '--enable-jack' '--enable-kate' '--enable-libass' '--enable-libmpeg2' '--enable-libxml2' '--enable-lirc' '--enable-mad' '--enable-matroska' '--enable-mod' '--enable-mpc' '--enable-mpg123' '--enable-mtp' '--enable-ncurses' '--enable-notify' '--enable-ogg' '--enable-opus' '--enable-pulse' '--enable-qt' '--enable-realrtsp' '--enable-samplerate' '--enable-sftp' '--enable-shine' '--enable-shout' '--enable-skins2' '--enable-soxr' '--enable-spatialaudio' '--enable-speex' '--enable-srt' '--enable-svg' '--enable-svgdec' '--enable-taglib' '--enable-theora' '--enable-twolame' '--enable-upnp' '--enable-vdpau' '--enable-vnc' '--enable-vorbis' '--enable-x264' '--enable-x265' '--enable-zvbi' '--with-kde-solid=/usr/share/solid/actions/' '--disable-aom' '--disable-crystalhd' '--disable-d3d11va' '--disable-decklink' '--disable-directx' '--disable-dsm' '--disable-dxva2' '--disable-fdkaac' '--disable-fluidlite' '--disable-freerdp' '--disable-goom' '--disable-gst-decode' '--disable-libplacebo' '--disable-libtar' '--disable-live555' '--disable-macosx' '--disable-macosx-avfoundation' '--disable-macosx-qtkit' '--disable-mfx' '--disable-microdns' '--disable-opencv' '--disable-projectm' '--disable-schroedinger' '--disable-sdl-image' '--disable-sndio' '--disable-sparkle' '--disable-telx' '--disable-vpx' '--disable-vsxu' '--disable-wasapi' '--enable-alsa' '--enable-dc1394' '--enable-dv1394' '--enable-linsys' '--enable-nfs' '--enable-udev' '--enable-v4l2' '--enable-wayland' '--enable-vcd' '--enable-smbclient' '--disable-oss' '--enable-mmx' '--enable-sse' '--disable-neon' '--disable-altivec' '--disable-omxil' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/vlc-Lpjw7w/vlc-3.0.20=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/vlc-Lpjw7w/vlc-3.0.20=/usr/src/vlc-3.0.20-3build6 ' 'LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=3' 'CXXFLAGS=-g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/vlc-Lpjw7w/vlc-3.0.20=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/vlc-Lpjw7w/vlc-3.0.20=/usr/src/vlc-3.0.20-3build6 ' 'OBJCFLAGS=-g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/vlc-Lpjw7w/vlc-3.0.20=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/vlc-Lpjw7w/vlc-3.0.20=/usr/src/vlc-3.0.20-3build6'
[00005d9f969e1550] main libvlc debug: searching plug-in modules
[00005d9f969e1550] main libvlc debug: loading plugins cache file /usr/lib/x86_64-linux-gnu/vlc/plugins/plugins.dat
[00005d9f969e1550] main libvlc debug: recursively browsing `/usr/lib/x86_64-linux-gnu/vlc/plugins'
[00005d9f969e1550] main libvlc debug: plug-ins loaded: 518 modules
[00005d9f969e1550] main libvlc debug: opening config file (/home/cam-mon/.config/vlc/vlcrc)
[00005d9f969e18a0] main logger debug: looking for logger module matching "any": 4 candidates
[00005d9f969e18a0] main logger debug: using logger module "console"
[00005d9f969e1550] main libvlc debug: translation test: code is "C"
[00005d9f969e2700] main keystore debug: looking for keystore module matching "memory": 4 candidates
[00005d9f969e2700] main keystore debug: using keystore module "memory"
[00005d9f969e1550] main libvlc debug: CPU has capabilities MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 FPU
[00005d9f96a7bff0] main input debug: Creating an input for 'Media Library'
[00005d9f96a7bff0] main input debug: Input is a meta file: disabling unneeded options
[00005d9f96a7bff0] main input debug: using timeshift granularity of 50 MiB
[00005d9f96a7bff0] main input debug: using default timeshift path
[00005d9f96a7bff0] main input debug: `file/directory:///home/cam-mon/.local/share/vlc/ml.xspf' gives access `file' demux `directory' path `/home/cam-mon/.local/share/vlc/ml.xspf'
[00005d9f96a86240] main input source debug: creating demux: access='file' demux='directory' location='/home/cam-mon/.local/share/vlc/ml.xspf' file='/home/cam-mon/.local/share/vlc/ml.xspf'
[00005d9f96a863c0] main demux debug: looking for access_demux module matching "file": 18 candidates
[00005d9f96a863c0] main demux debug: no access_demux modules matched
[00005d9f96a90340] main stream debug: creating access: file:///home/cam-mon/.local/share/vlc/ml.xspf
[00005d9f96a90340] main stream debug:  (path: /home/cam-mon/.local/share/vlc/ml.xspf)
[00005d9f96a90340] main stream debug: looking for access module matching "file": 30 candidates
[00005d9f96a90340] main stream debug: using access module "filesystem"
[00005d9f96a91580] main stream debug: looking for stream_filter module matching "prefetch,cache_read": 26 candidates
[00005d9f96a91580] cache_read stream debug: Using stream method for AStream*
[00005d9f96a91580] cache_read stream debug: starting pre-buffering
[00005d9f96a91580] cache_read stream debug: received first data after 0 ms
[00005d9f96a91580] cache_read stream debug: pre-buffering done 296 bytes in 0s - 3854 KiB/s
[00005d9f96a91580] main stream debug: using stream_filter module "cache_read"
[00005d9f96a92680] main stream debug: looking for stream_filter module matching "any": 26 candidates
[00005d9f96a92680] playlist stream debug: using XSPF playlist reader
[00005d9f96a92680] main stream debug: using stream_filter module "playlist"
[00005d9f96a92680] main stream debug: stream filter added to 0x5d9f96a91580
[00005d9f96a95e20] main stream debug: looking for stream_filter module matching "any": 26 candidates
[00005d9f96a95e20] main stream debug: no stream_filter modules matched
[00005d9f96a7eea0] main stream_directory debug: looking for stream_directory module matching "any": 1 candidates
[00005d9f96a7eea0] main stream_directory debug: no stream_directory modules matched
[00005d9f96a86240] main input source debug: attachment of directory-extractor failed for file:///home/cam-mon/.local/share/vlc/ml.xspf
[00005d9f96a95e20] main stream debug: looking for stream_filter module matching "record": 26 candidates
[00005d9f96a95e20] main stream debug: using stream_filter module "record"
[00005d9f96a86240] main input source debug: creating demux: access='file' demux='directory' location='/home/cam-mon/.local/share/vlc/ml.xspf' file='/home/cam-mon/.local/share/vlc/ml.xspf'
[00005d9f96a863c0] main demux debug: looking for demux module matching "directory": 54 candidates
[00005d9f96a863c0] main demux debug: using demux module "directory"
[00005d9f96a99a10] main demux meta debug: looking for meta reader module matching "any": 2 candidates
[00005d9f96a99a10] lua demux meta debug: Trying Lua scripts in /home/cam-mon/.local/share/vlc/lua/meta/reader
[00005d9f96a99a10] lua demux meta debug: Trying Lua scripts in /usr/lib/x86_64-linux-gnu/vlc/lua/meta/reader
[00005d9f96a99a10] lua demux meta debug: Trying Lua playlist script /usr/lib/x86_64-linux-gnu/vlc/lua/meta/reader/filename.luac
[00005d9f96a99a10] lua demux meta debug: Trying Lua scripts in /usr/share/vlc/lua/meta/reader
[00005d9f96a99a10] main demux meta debug: no meta reader modules matched
[00005d9f96a7bff0] main input debug: `file/directory:///home/cam-mon/.local/share/vlc/ml.xspf' successfully opened
[00005d9f96a9e230] main xml reader debug: looking for xml reader module matching "any": 1 candidates
[00005d9f96a9e230] main xml reader debug: using xml reader module "xml"
[00005d9f96a7bff0] main input debug: EOF reached
[00005d9f96a863c0] main demux debug: removing module "directory"
[00005d9f96a95e20] main stream debug: removing module "record"
[00005d9f96a92680] main stream debug: removing module "playlist"
[00005d9f96a91580] main stream debug: removing module "cache_read"
[00005d9f96a90340] main stream debug: removing module "filesystem"
[00005d9f96a79820] main playlist debug: creating audio output
[00005d9f96a9e870] main audio output debug: looking for audio output module matching "any": 5 candidates
[00005d9f96a9e870] vlcpulse audio output debug: using library version 16.1.0
[00005d9f96a9e870] vlcpulse audio output debug:  (compiled with version 16.1.0, protocol 35)
[00005d9f96a9e870] vlcpulse audio output debug: connected locally to /run/user/1000/pulse/native as client #3
[00005d9f96a9e870] vlcpulse audio output debug: using protocol 35, server protocol 35
[00005d9f96a9e870] pulse audio output debug: adding sink 0: alsa_output.pci-0000_00_0e.0.analog-stereo (Built-in Audio Analog Stereo)
[00005d9f96a9e870] main audio output debug: using audio output module "pulse"
[00005d9f96a79820] main playlist debug: keeping audio output
[00005d9f96ac04e0] main interface debug: looking for interface module matching "dbus,none": 19 candidates
[00005d9f96ac04e0] dbus interface debug: listening on dbus as: org.mpris.MediaPlayer2.vlc
[00005d9f96ac04e0] main interface debug: using interface module "dbus"
[00005d9f96ac4b90] main interface debug: looking for interface module matching "hotkeys,none": 19 candidates
[00005d9f96ac4b90] main interface debug: using interface module "hotkeys"
[00005d9f96ac67c0] main interface debug: looking for interface module matching "globalhotkeys,none": 19 candidates
[00005d9f96ac67c0] main interface debug: no interface modules matched
[00005d9f96ac67c0] main interface error: no suitable interface module
[00005d9f969e1550] main libvlc error: interface "globalhotkeys,none" initialization failed
[00005d9f96ac67c0] main interface debug: looking for interface module matching "dummy": 19 candidates
[00005d9f96ac67c0] dummy interface: using the dummy interface module...
[00005d9f96ac67c0] main interface debug: using interface module "dummy"
[00005d9f96a79820] main playlist debug: processing request item: null, node: Playlist, skip: 0
[00005d9f96a79820] main playlist debug: rebuilding array of current - root Playlist
[00005d9f96a79820] main playlist debug: rebuild done - 1 items, index -1
[00005d9f96a79820] main playlist debug: starting playback of new item
[00005d9f96a79820] main playlist debug: resyncing on rtsp://10.57.1.5:8554/front_south
[00005d9f96a79820] main playlist debug: rtsp://10.57.1.5:8554/front_south is at 0
[00005d9f96a79820] main playlist debug: creating new input thread
[0000770648000c90] main input debug: Creating an input for 'rtsp://10.57.1.5:8554/front_south'
[00005d9f96a79820] main playlist debug: requesting art for new input thread
[0000770648000c90] main input debug: using timeshift granularity of 50 MiB
[0000770648000c90] main input debug: using default timeshift path
[0000770648000c90] main input debug: `rtsp://10.57.1.5:8554/front_south' gives access `rtsp' demux `any' path `10.57.1.5:8554/front_south'
[0000770644000fb0] main input source debug: creating demux: access='rtsp' demux='any' location='10.57.1.5:8554/front_south' file='(null)'
[0000770644001140] main demux debug: looking for access_demux module matching "rtsp": 18 candidates
[0000770644001140] main demux debug: no access_demux modules matched
[00007706440015a0] main stream debug: creating access: rtsp://10.57.1.5:8554/front_south
[00007706440015a0] main stream debug: looking for access module matching "rtsp": 30 candidates
[0000770638000c30] main meta fetcher debug: looking for meta fetcher module matching "any": 1 candidates
[0000770638000c30] lua meta fetcher debug: Trying Lua scripts in /home/cam-mon/.local/share/vlc/lua/meta/fetcher
[0000770638000c30] lua meta fetcher debug: Trying Lua scripts in /usr/lib/x86_64-linux-gnu/vlc/lua/meta/fetcher
[0000770638000c30] lua meta fetcher debug: Trying Lua scripts in /usr/share/vlc/lua/meta/fetcher
[00007706440015a0] satip stream debug: try to open 'rtsp://10.57.1.5:8554/front_south'
[00007706440015a0] satip stream debug: connect to host '10.57.1.5'
[00007706440015a0] main stream debug: net: connecting to 10.57.1.5 port 8554
[0000770638000c30] main meta fetcher debug: no meta fetcher modules matched
[0000770638000c30] main art finder debug: looking for art finder module matching "any": 2 candidates
[0000770638000c30] lua art finder debug: Trying Lua scripts in /home/cam-mon/.local/share/vlc/lua/meta/art
[0000770638000c30] lua art finder debug: Trying Lua scripts in /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art
[0000770638000c30] lua art finder debug: Trying Lua playlist script /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/00_musicbrainz.luac
[0000770638000c30] lua art finder debug: skipping script (unmatched scope) /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/00_musicbrainz.luac
[0000770638000c30] lua art finder debug: Trying Lua playlist script /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/01_googleimage.luac
[0000770638000c30] lua art finder debug: skipping script (unmatched scope) /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/01_googleimage.luac
[0000770638000c30] lua art finder debug: Trying Lua playlist script /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/02_frenchtv.luac
[0000770638000c30] lua art finder debug: skipping script (unmatched scope) /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/02_frenchtv.luac
[0000770638000c30] lua art finder debug: Trying Lua playlist script /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/03_lastfm.luac
[0000770638000c30] lua art finder debug: skipping script (unmatched scope) /usr/lib/x86_64-linux-gnu/vlc/lua/meta/art/03_lastfm.luac
[0000770638000c30] lua art finder debug: Trying Lua scripts in /usr/share/vlc/lua/meta/art
[0000770638000c30] main art finder debug: no art finder modules matched
[00007706440015a0] main stream debug: connection succeeded (socket = 11)
[00007706440015a0] main stream debug: net: opening 0.0.0.0 datagram port 9088
[00007706440015a0] main stream debug: net: opening 0.0.0.0 datagram port 9089
[00007706440015a0] satip stream error: Failed to setup RTSP session
[00007706440015a0] main stream debug: net: connecting to 10.57.1.5 port 8554
[00007706440015a0] main stream debug: connection succeeded (socket = 11)
[00007706440015a0] access_realrtsp stream warning: Cseq mismatch, got 1, assumed 0
[00007706440015a0] access_realrtsp stream debug: rtsp connected
[00007706440015a0] access_realrtsp stream warning: only real/helix rtsp servers supported for now
[00007706440015a0] main stream debug: no access modules matched
[0000770648000c90] main input error: Your input can't be opened
[0000770648000c90] main input error: VLC is unable to open the MRL 'rtsp://10.57.1.5:8554/front_south'. Check the log for details.
[00005d9f96a79820] main playlist debug: dead input
[00005d9f96a79820] main playlist debug: changing item without a request (current 0/1)
[00005d9f96a79820] main playlist debug: nothing to play
```

**Reply by Cold-Lemonade** [reply]
@NickM-27 Here's the config:

```
mqtt:
  enabled: false

detectors:
  coral1:
    type: edgetpu
    device: pci
  coral2:
    type: edgetpu
    device: usb

model:
  path: plus://REDACTED

record:
  enabled: true
  retain:
    days: 21
    mode: all
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 30

go2rtc:
  streams:
    front_south:
      - rtsp://REDACTED@192.168.50.28:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    front_north:
      - rtsp://REDACTED@192.168.50.30:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    rear_2nd_north:
      - rtsp://REDACTED@192.168.50.25:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    rear_2nd_south:
      - rtsp://REDACTED@192.168.50.29:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    rear_1st_north:
      - rtsp://REDACTED@192.168.50.21:554/cam/realmonitor?channel=1&subtype=0
    rear_1st_south:
      - rtsp://REDACTED@192.168.50.26:554/cam/realmonitor?channel=1&subtype=0
    entry_hallway:
      - rtsp://REDACTED@192.168.50.27:554/cam/realmonitor?channel=1&subtype=0
    parking_area:
      - rtsp://REDACTED@192.168.50.31:554/cam/realmonitor?channel=1&subtype=0
    lander_street:
      - rtsp://REDACTED@192.168.50.101:554/cam/realmonitor?channel=1&subtype=0
    back_alley:
      - rtsp://REDACTED@192.168.50.100:554/cam/realmonitor?channel=1&subtype=0

  webrtc:
    candidates:
      - 10.57.1.5:8555
      - stun:8555

cameras:
  front_south:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.28:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/front_south
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#            - audio
    audio:
      enabled: false
      min_volume: 500
      listen:
        - emergency_vehicle
        - explosion
        - gunshot
        - fusillade
        - cap_gun
        - fireworks
        - firecracker
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask:
        - 1,0.24,0.963,0.165,0.896,0.354,0.868,0.475,0.896,0.631,0.878,0.783,0.851,0.904,0.815,1,1,1
        - 1,0,1,0.094,0.648,0.094,0.648,0
        - 0,0,0,0.153,0.274,0.148,0.436,0.162,0.643,0.252,0.998,0.456,0.997,0.004
        - 0.191,0.997,0.001,0.995,0.001,0.004,0.031,0.002,0.038,0.162,0.056,0.354,0.075,0.465,0.092,0.581,0.112,0.694
    zones:
      front_flood_light_zone:
        coordinates:
          0,480,494,480,557,480,601,403,509,350,507,332,474,312,274,210,169,161,39,216,36,197,0,201
        objects:
          - person
      front_windows:
        coordinates: 200,200,89,248,0,203,0,179,87,228,170,190
        objects:
          - person
    ui:
      order: 1

  front_north:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.30:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/front_north
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#            - audio
    audio:
      enabled: false
      min_volume: 500
      listen:
        - emergency_vehicle
        - explosion
        - gunshot
        - fusillade
        - cap_gun
        - fireworks
        - firecracker
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask:
        - 0,0,0.378,0,0.378,0.1,0,0.1
        - 0.786,0.046,0.789,0.394,0.563,0.384,0.475,0.515,0.451,0.386,0.444,0.313,0.453,0.28,0.474,0.188,0.475,0,0.894,0,0.894,0.019,0.814,0.023
        - 0,0.606,0.373,0.261,0.717,-0.002,0,0
        - 0.892,0,0.894,0.326,0.899,0.445,0.88,0.444,0.862,0.688,0.868,0.706,0.84,1,1,1,1,0
    zones:
      front_flood_light_zone:
        coordinates:
          704,480,704,101,632,100,601,111,594,167,534,167,531,187,478,185,434,178,414,179,356,244,226,389,148,480
        objects:
          - person
      front_windows:
        coordinates: 704,480,285,480,408,278,619,286,620,214,679,210,677,0,704,0
        objects:
          - person
    ui:
      order: 2

  rear_2nd_north:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.25:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/rear_2nd_north
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#            - audio
    audio:
      enabled: false
      min_volume: 500
      listen:
        - emergency_vehicle
        - explosion
        - gunshot
        - fusillade
        - cap_gun
        - fireworks
        - firecracker
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask: 1,0,1,0.08,0.764,0.081,0.765,0
    zones:
      rear_deck:
        coordinates: 392,480,170,190,0,225,0,480
        objects:
          - person
      rear_stoop:
        coordinates: 302,269,347,325,240,245,188,183
        objects:
          - person
    ui:
      order: 4

  rear_2nd_south:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.29:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/rear_2nd_south
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#            - audio
    audio:
      enabled: false
      min_volume: 500
      listen:
        - emergency_vehicle
        - explosion
        - gunshot
        - fusillade
        - cap_gun
        - fireworks
        - firecracker
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          min_area: 2700
          min_score: 0.60
          threshold: 0.75
    motion:
      mask:
        - 244,0,0,0,0,48,244,48
    zones:
      rear_deck:
        coordinates: 615,480,658,329,671,227,530,206,450,326,317,480,401,480
        objects:
          - person
      rear_stoop:
        coordinates: 291,480,209,480,266,430,343,423
        objects:
          - person
    ui:
      order: 5

  rear_1st_north:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/rear_1st_north
#          input_args: preset-rtsp-restream
#          roles:
#            - record
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          min_area: 1000
          min_score: 0.6
    motion:
      mask:
        - 704,0,704,45,509,45,509,0
    zones:
      back_patio:
        coordinates: 250,275,240,231,154,183,0,232,0,480,529,480,597,341,338,240
        objects:
          - person
    ui:
      order: 7

  rear_1st_south:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.26:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/rear_1st_south
#          input_args: preset-rtsp-restream
#          roles:
#            - record
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
    motion:
      mask:
        - 704,0,704,42,508,42,508,0
    zones:
      back_patio:
        coordinates: 496,155,704,225,704,480,147,480,118,409,390,278,388,185
        objects:
          - person
    ui:
      order: 8

  entry_hallway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.27:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/entry_hallway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask:
        - 704,428,704,480,457,480,457,428
    ui:
      order: 10

  parking_area:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.31:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/parking_area
#          input_args: preset-rtsp-restream
#          roles:
#            - record
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask:
        - 1,0.877,1,1,0.635,1,0.635,0.877
        - 0,1,0.154,1,0.153,0.162,0.787,0.174,0.998,0.454,0.998,0.002,0.002,0.002
    ui:
      order: 9

  lander_street:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/lander_street
#          input_args: preset-rtsp-restream
#          roles:
#            - record
    onvif:
      host: 192.168.50.101
      port: 80
      user: REDACTED
      password: REDACTED
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask:
        - 704,0,704,46,452,46,452,0
    ui:
      order: 3

  back_alley:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path:
            rtsp://REDACTED@192.168.50.100:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
#        - path: rtsp://127.0.0.1:8554/back_alley
#          input_args: preset-rtsp-restream
#          roles:
#            - record
    onvif:
      host: 192.168.50.100
      port: 80
      user: REDACTED
      password: REDACTED
    detect:
      width: 704
      height: 480
      fps: 5
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    record:
      enabled: true
    motion:
      mask:
        - 704,0,704,46,452,46,452,0
    ui:
      order: 6
version: 0.14
camera_groups:
  Front_Cameras:
    order: 1
    icon: LuChevronUpCircle
    cameras:
      - front_north
      - front_south
      - lander_street
  Rear_Cameras:
    order: 2
    icon: LuChevronDownCircle
    cameras:
      - rear_2nd_north
      - rear_2nd_south
      - back_alley
      - rear_1st_north
      - rear_1st_south
      - parking_area
  Exterior:
    order: 3
    icon: LuShieldCheck
    cameras:
      - front_north
      - front_south
      - back_alley
      - lander_street
      - parking_area
      - rear_1st_north
      - rear_1st_south
      - rear_2nd_north
      - rear_2nd_south
```

**Reply by NickM-27** [reply]
I'd suggest checking go2rtc logs, from the frigate side there is no reason it shouldn't work

**Reply by Cold-Lemonade** [reply]
And here is the docker compose file:

```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    shm_size: "128mb"
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lander/frigate:/config
      - /media/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_PASSWORD=REDACTED
      - PLUS_API_KEY=REDACTED
```
