### DISCUSSION TITLE
[Camera Support]: Two-way audio with Neolink Talk using Frigate hass-card microphone.

### DISCUSSION THREAD

**Discussion by Joeviocoe** [blakeblackshear/frigate#15587] [Camera Support]
### Describe the problem you are having

I'm using Neolink talk command with a non-doorbell reolink camera. This test command works, `ffmpeg -i https://rhasspy.github.io/piper-samples/samples/en/en_US/lessac/high/speaker_0.mp3 -f  alaw -ar 8000 -f wav - | ./neolink talk front_door -c config.toml --volume=1.0 -m -i "fdsrc fd=0"` as I can hear the camera speak the arbitrary audio file.  Two-way audio does work with this camera using the official Reolink mobile app.  So I would think that Neolink should be able to do this too.

I am running Home Assistant (supervised with docker) with the Frigate and Neolink addons.  (_I still need to find out how to have ffmpeg/gstreamer preloaded and persistent across docker/addon restarts_).

But I am now trying to get my frigate hass card with the microphone button working.
I'm on the HomeAssistant Android app, and pressing the microphone button highlights it red, I speak into the phone mic, but no sound comes out of the camera speaker.
  
  I am looking for documentation, tutorial or guide that describes how it is "supposed to work" with a Reolink camera.

### Version

0.15.0-beta3

### What browser(s) are you using?

Home Assistant Companion app for Android

### Frigate config file

```yaml
go2rtc:
  streams:
    cam_backyard:
      - "ffmpeg:http://10.0.x.x/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=PASS#video=copy#audio=copy#audio=opus"
      - rtsp://admin:PASS@10.0.x.x/Preview_01_main
    cam_backyard_sub:
      - rtsp://admin:PASS@10.0.x.x/Preview_01_sub
      - exec:/config/neolink/neolink_talk.sh#backchannel=1
      
cameras:
  cam_backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam_backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant Frigate log output

```shell
2024-12-18 15:57:39.300183328  [INFO] Preparing Frigate...
2024-12-18 15:57:39.300424630  [INFO] Starting Frigate...
```

### Relevant go2rtc log output

```shell
2024-12-18 15:57:39.279314374  [INFO] Preparing new go2rtc config...
2024-12-18 15:57:39.382806311  [INFO] Got IP address from supervisor: 10.0.x.x
2024-12-18 15:57:39.483494480  [INFO] Got WebRTC port from supervisor: 8555
2024-12-18 15:57:40.633658597  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2024-12-18 15:57:40.633667965  [INFO] Starting go2rtc...
2024-12-18 15:57:40.786286437  08:57:40.786 INF go2rtc platform=linux/amd64 revision=dbe9e4a version=1.9.7
2024-12-18 15:57:40.786910995  08:57:40.786 INF config path=/dev/shm/go2rtc.yaml
2024-12-18 15:57:40.788116129  08:57:40.787 INF [rtsp] listen addr=:8554
2024-12-18 15:57:40.789000857  08:57:40.788 INF [webrtc] listen addr=:8555/tcp
2024-12-18 15:57:40.789687265  08:57:40.788 INF [api] listen addr=:1984
2024-12-18 15:57:49.301765597  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe "http://10.0.x.x/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=PASS#video=copy#audio=copy#audio=opus"
ffprobe version 5.1.6-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flv, from 'http://10.0.x.x/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=PASS#video=copy#audio=copy#audio=opus':
  Metadata:
    displayWidth    : 1536
    displayHeight   : 576
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1536x576, 19 fps, 20 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Duo & RLC-81MA

### Screenshots of the Frigate UI's System metrics pages

.

### Any other information that may be helpful

ModelReolink Duo Floodlight PoE
UID95270007WOT21ANR
Build No.build 2312234659
Hardware No.IPC_529B17B8MP
Config Versionv3.0.0.0
Firmware Versionv3.0.0.1889_2312234659
DetailsIPC_529B17B8MPS10E1W01100000001
