### DISCUSSION TITLE
[Bug]: Review page: No Preview Found for disabled cameras

### DISCUSSION THREAD

**Discussion by mr-manuel** [blakeblackshear/frigate#15599] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

If you have configured one or multiple cameras where you do not record and/or which is disabled in the gui, you get a `No Preview Found for ...` in the Review/History page.

I use the additional "cameras" only to zoom into regions of interest of other cameras.

![grafik](https://github.com/user-attachments/assets/153e1473-4c1e-43e2-8660-1b0f333b320c)

### Steps to reproduce

1. Add a camera with only the role `detect` and UI dashboard false.
2. Wait a bit that there is some history.
3. Switch to the review page and see the empty camera previews.

### Version

0.15.0-6b12a45

### In which browser(s) are you experiencing the issue with?

Firefox 133.0.3

### Frigate config file

```yaml
# relevant part

  X-Porch:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          roles:
            - detect
      hwaccel_args: -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device
        /dev/dri/renderD128 -hwaccel_output_format vaapi
      output_args:
        detect: -vf fps=8,hwdownload,format=yuv420p,crop=510:610:1900:130 -threads
          1 -f rawvideo
    detect:
      width: 510
      height: 610
      enabled: False
    snapshots:
      enabled: False
    record:
      enabled: False
    mqtt:
      enabled: False
    birdseye:
      enabled: False
    ui:
      order: 10
      dashboard: False

  X-Backyard:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Haustuer
          roles:
            - detect
      hwaccel_args: -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device
        /dev/dri/renderD128 -hwaccel_output_format vaapi
      output_args:
        detect: -vf fps=8,hwdownload,format=yuv420p,crop=850:750:2970:1294 -threads
          1 -f rawvideo
    detect:
      width: 850
      height: 750
      enabled: False
    snapshots:
      enabled: False
    record:
      enabled: False
    mqtt:
      enabled: False
    birdseye:
      enabled: False
    ui:
      order: 11
      dashboard: False
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

-

### Screenshots of the Frigate UI's System metrics pages

-

### Any other information that may be helpful

Only a GUI issue, that tries to visualize a camera that is disabled and has no recordings.

**Comment by NickM-27** [comment]
This is not a bug. As a user you can change when a camera is disabled. Just because a camera is disabled now doesn't mean it was disabled when you are scrubbing on the timeline

**Reply by mr-manuel** [reply]
Wow, thanks for the fast response!

I have this config from the beginning and the camera was never enabled. Are you trying to tell me, I have to disable it also elsewhere?

**Reply by NickM-27** [reply]
No, I'm saying frigate has no easy way of knowing that, so we need to make the camera available to you even if it is disabled in the config right now. 

If you want to exclude the camera from review you can create a camera group that excludes it and use that for reviewing.

**Reply by mr-manuel** [reply]
@NickM-27 in my opinion the cameras should be hidden, if I set

```yml
    ui:
      dashboard: False
```

since then they are also not displayed anywhere else.

Else the description in the full config is wrong:

https://deploy-preview-13787--frigate-docs.netlify.app/configuration/reference

```yml
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
```
