### DISCUSSION TITLE
Help with steps to upgrade from 13.1 to lates 14.1

### DISCUSSION THREAD

**Discussion by FigJam23** [blakeblackshear/frigate#15606] [Ask A Question]
Can someone point me to the right place that can show what I need to do to upgrade from 13.1 to 14.1 I'm not worried about retaining footage 

<html><body>
<div class="flex justify-between"><h1 class="font-semibold tracking-widest uppercase text-2xl ">System <span class="text-sm">0.13.1-34fb1c2</span></h1><span class="p-1">go2rtc 1.8.4 <a href="http://192.168.1.95:5000/api/go2rtc/streams" target="_blank" rel="noopener noreferrer" class="text-blue-500 hover:underline">streams info</a></span></div><p><span>Last refreshed: <span>just now</span></span></p><div class="flex justify-start"><h1 class="font-semibold tracking-widest uppercase text-lg self-center">Detectors</h1><div role="button" aria-disabled="false" tabindex="0" aria-label="Momentary resource usage of each process that is controlling the object detector. CPU % is for a single core." class="whitespace-nowrap flex items-center space-x-1 rounded-full transition-opacity text-gray-500 hover:bg-gray-500 hover:bg-opacity-20 focus:bg-gray-500 focus:bg-opacity-40 active:bg-gray-500 active:bg-opacity-40 font-sans inline-flex font-bold uppercase text-xs px-1.5 md:px-2 py-2 rounded outline-none focus:outline-none ring-opacity-50 transition-shadow transition-colors focus:ring-2 cursor-pointer"><svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5"></svg></div></div><div data-testid="detectors" class="grid grid-cols-1 3xl:grid-cols-3 md:grid-cols-2 gap-4"><div class="dark:bg-gray-800 shadow-md hover:shadow-lg rounded-lg transition-shadow"><div class="text-lg flex justify-between p-4">tensorrt</div><div class="p-2">
P-ID | Inference Speed | CPU % | Memory %
-- | -- | -- | --
505 | 11.02 ms | 4.3% | 2.4%

</div></div></div><div class="text-lg flex justify-between"><div class="flex justify-start"><h1 class="font-semibold tracking-widest uppercase text-lg self-center">GPUs</h1><div role="button" aria-disabled="false" tabindex="0" aria-label="Momentary resource usage of each GPU. Intel GPUs do not support memory stats." class="whitespace-nowrap flex items-center space-x-1 rounded-full transition-opacity text-gray-500 hover:bg-gray-500 hover:bg-opacity-20 focus:bg-gray-500 focus:bg-opacity-40 active:bg-gray-500 active:bg-opacity-40 font-sans inline-flex font-bold uppercase text-xs px-1.5 md:px-2 py-2 rounded outline-none focus:outline-none ring-opacity-50 transition-shadow transition-colors focus:ring-2 cursor-pointer"><svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5"></svg></div></div></div><div class="text-lg flex justify-between"><div role="button" aria-disabled="false" tabindex="0" class="whitespace-nowrap flex items-center space-x-1  text-white shadow focus:shadow-xl hover:shadow-md bg-blue-500 focus:bg-blue-400 active:bg-blue-600 ring-blue-300 font-sans inline-flex font-bold uppercase text-xs px-1.5 md:px-2 py-2 rounded outline-none focus:outline-none ring-opacity-50 transition-shadow transition-colors focus:ring-2 cursor-pointer">vainfo</div></div><div data-testid="gpus" class="grid grid-cols-1 3xl:grid-cols-3 md:grid-cols-2 gap-4"><div class="dark:bg-gray-800 shadow-md hover:shadow-lg rounded-lg transition-shadow"><div class="text-lg flex justify-between p-4">NVIDIA GeForce GTX 1660 SUPER</div></div></div>
</body>
</html>System 0.13.1-34fb1c2
go2rtc 1.8.4 [streams info](http://192.168.1.95:5000/api/go2rtc/streams)

Last refreshed: just now
Detectors
tensorrt
P-ID	Inference Speed	CPU %	Memory %
505	11.02 ms	4.3%	2.4%
GPUs
vainfo
NVIDIA GeForce GTX 1660 SUPER

```
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  #live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: false
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  #time_format: browser
 # Optional: Set the date style for a specified length.
 # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  #date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
 # time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  #strftime_fmt: "%Y/%m/%d %H:%M"

#environment_vars:
 # PLUS_API_KEY: f9be1e69-c600-4c0b-915b-489bb82cc4d2:c2fea8c97fc3784e6a7491338c21040b14ff9587



#logger:
  # Optional: default log level (default: shown below)
  #default: warning
  # Optional: module by module log level configuration
 # logs:
    #frigate.mqtt: error

#timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  #position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  #format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
 # color:
  # All Required when color is specified (default: shown below)
   # red: 255
   # green: 255 
   # blue: 255
  # Optional: Line thickness of font (default: shown below)
  #thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  #effect: solid

mqtt:
  host: 192.168.1.44
  port: 1883
  user: mqtt
  password: kk

#birdseye:
  #enabled: True
  #width: 1280
  #height: 760
  #quality: 1
  #mode: objects
birdseye:
    # Optional: Enable birdseye view (default: shown below)
  enabled: true
   # Optional: Width of the output resolution (default: shown below) 
  width: 1280
   # Optional: Height of the output resolution (default: shown below)
  height: 720
    # Optional: Encoding quality of the mpeg1 feed (default: shown below)
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.https://
  quality: 4
    # Optional: Mode of the view. Available options are: objects, motion, and continuous
    #   objects - cameras are included if they have had a tracked object within the last 30 seconds
    #   motion - cameras are included if motion was detected in the last 30 seconds
    #   continuous - all cameras are included always
  mode: objects
  restream: true
record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 7
    post_capture: 30
    retain:
      default: 5
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  clean_copy: true
  bounding_box: true
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
 # height: 300
  quality: 100
  retain:
    default: 10
    objects:
      person: 10




ffmpeg:
  hwaccel_args: preset-nvidia-h264



#Global Object Settings
objects:
  track:
  - person
  - car
  - cat
  - dog
  - bird
  - bicycle
  #- cell phone

 # filters:
   # person:
   #   min_area: 1000
    #  max_area: 100000
     #  min_ratio: 0.5
     #  max_ratio: 2.0
   #   min_score: 0.6
   #   threshold: 0.75
  #  cat:
   #   min_area: 1000
     # max_area: 100000
      # min_ratio: 0.5
     # max_ratio: 2.0
    #  min_score: 0.6
    #  threshold: 0.75
    #dog:
    #  min_area: 1000
     # max_area: 100000
     # min_ratio: 0.5
     # max_ratio: 2.0
   #   min_score: 0.6
    #  threshold: 0.75

rtmp:
  enabled: false

go2rtc:
  streams:
   # 360cam:
    #  - 192.168.1.66:50000/live/mainview3.html?Language=0
      #- rtsp://admin:kk@192.168.1.66:554/MediaInput/h264
     # - "ffmpeg:360cam#video=h264"
    front_entry:
    - rtsp://admin:kk@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:front_entry#video=h264#audio=aac
    front_deck:
    - rtsp://admin.kk@192.168.1.30:554/Streaming/channels/201
    driveway_cam:
    - rtsp://admin:kk@192.168.1.30:554/Streaming/channels/101
    back_shed:
    - rtsp://admin:kk@192.168.1.30:554/Streaming/channels/301
    sand_pit:
    - rtsp://admin:kk@192.168.1.30:554/Streaming/channels/401
    ptzcamera:
    - rtsp://root:kk@192.168.1.90:554/axis-media/media.amp 

# rtsp://127.0.0.1:8554/sand_pit
# rtsp://127.0.0.1:8554/back_shed
# rtsp://127.0.0.1:8554/driveway_cam
# rtsp://127.0.0.1:8554/front_deck
# rtsp://127.0.0.1:8554/front_entry
# rtsp://127.0.0.1:8554/360cam

detectors:
  tensorrt:
    type: tensorrt
    device: 0 # This is the default, select the first GPU
  #coral1:
  #  type: edgetpu
   # device: usb
model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt #yolov7-640.trt #yolov7-320.trt #yolov7-320.trt   #/config/model_cache/tensorrt/yolov7-320.trt    #trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
#########################################################################################################################################            
cameras:
########################################################################################################################################

  driveway_cam:
    ui:
      order: 0
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_cam #rtsp://admin:kk@192.168.1.30:554/Streaming/channels/101
        roles:
        - record
        - detect
    motion:
      threshold: 40
     #contour_area: 55
     #frame_height: 150
      mask:
       # - 2385,0,2429,519,2114,403,1667,465,1640,354,489,1072,465,2160,0,2160,27,27
       # - 3840,2160,1323,2160,1541,1863,1851,1930,2358,1310,2680,1146,2773,767,2692,253,2301,0,3840,0

      - 2385,0,2589,249,2534,508,2299,414,2153,485,1678,689,1636,356,433,1607,414,2121,0,1888,27,27
      - 3840,2160,1629,2160,1778,1943,1953,1684,2661,1397,2425,1025,2699,750,2764,556,2686,297,2441,449,2163,407,2301,0,3840,0

    zones:
      zone_driveway_cars:
        coordinates: 2258,399,2279,607,2040,752,1738,860,2677,1219,2960,614
        objects:
        - car
        filters:
          car:
            min_area: 50000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
            min_score: 0.60
            threshold: 0.77

      zone_driveway_all:
        coordinates: 2168,411,1708,666,1694,866,759,1720,279,1144,0,1388,0,2160,3840,2160,3840,935
        objects:
        - person
        - cat
        - dog
        - bicycle
      #    - bird

        filters:
          person:
            min_area: 5000
            max_area: 300000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.89

          cat:
            min_area: 2000
            max_area: 5200
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.77

          dog:
            min_area: 4000
            max_area: 6000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.7

        
          bicycle:
            min_area: 5000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.77

       #   bird: 
       #     min_area: 100
       #     max_area: 7000
       #     min_score: 0.6
        #    threshold: 0.7

      zone_driveway_entrance_people:
        coordinates: 2371,533,1702,844,2703,1115,2777,647
        objects:
        - person
        filters:
          person:
            min_area: 5000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.7

      zone_cars_road:
        coordinates: 2709,215,1907,86,1116,179,455,286,477,453,1405,318,2261,367,2917,587,3172,565,3840,864,3840,573
        objects:   
          - car
          - person
          - cat  
          - dog  
          - bicycle

        filters:
          car:
            min_area: 5000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
            min_score: 0.6
            threshold: 0.75

          person:
            min_area: 5400
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.77

          cat:
            min_area: 800
            max_area: 5700
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.7
          dog:
            min_area: 5000
            max_area: 10000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.7   
          bicycle:
            min_area: 800
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.77       
    detect:
      width: 3840
      height: 2160
      fps: 8
    objects:
      filters:
        car:
          mask:
          - 2748,1309,2976,534,3840,857,3840,2160,1572,2160,0,2160,0,0,1574,0,1662,932
          - 1725,918,1659,364,2085,387,2352,538,2227,734
         #   - 1494,0,806,54,466,150,483,387,532,688,1267,288,1871,271,2869,574,3810,742,3818,25     
        person:
          mask:
          - 3120,1178,3207,2160,3785,2160,3796,993
          - 385,1374,756,1778,566,2160,0,1943

        bicycle:
          mask:
          - 3483,2160,3294,1438,1034,703,0,1380,0,2160
    record:
      events:
        required_zones:
        - zone_driveway_cars
        - zone_driveway_all
        - zone_cars_road 
        - zone_driveway_entrance_people
    snapshots:
      required_zones:
      - zone_driveway_cars
      - zone_driveway_all
      - zone_cars_road
      - zone_driveway_entrance_people
###############################################################################################################################

 #####################################################################################################################################                     

  front_entry:
    ui:
      order: 1
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_entry #rtsp://admin:kk@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
        - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a copy
    motion:
      threshold: 25
     #contour_area: 55
     #frame_height: 150
      mask:
      - 1226,266,336,499,378,675,21,802,23,0,3072,0,3072,548,2599,383,2185,507
      - 621,422,453,766,1014,1177,1942,1709,2418,2048,3072,2048,2811,1373,2878,1050,2625,820,2240,1107
      - 0,1486,0,2048,323,2048,749,1269,0,841
    zones:
      zone_front_entry_people:
        coordinates: 3072,1630,2372,1180,2036,1027,2386,732,2753,915,3072,997
        objects:
        - person
        filters:
          person:
            min_area: 15000
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.7
            threshold: 0.82

      zone_front_entry_area:
        coordinates: 462,2048,2793,2048,2612,1857,488,627,0,806,293,1406,161,1493
        objects:
        - person
       # - cell phone
        - cat
        - dog
       #   - bird
        filters:
        #  cell phone:
         #   min_score: 0.3
         #   threshold: 0.7
            

          person:
            min_area: 90500
           # max_area: 100000
          #  min_ratio: 0.7
         #   max_ratio: 1.2
            min_score: 0.7
            threshold: 0.89

          cat:
            min_area: 4000
            max_area: 80000
           # min_ratio: 0.5
           # max_ratio: 2.0
            min_score: 0.7
            threshold: 0.80
          dog:
            min_area: 8000
           # max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
            min_score: 0.7
            threshold: 0.84

      #    bird: 
      ##      min_area: 100
       #     max_area: 7000
       #     min_score: 0.6
       #     threshold: 0.7

      zone_front_entry_dakoats_door:
        coordinates: 2561,527,2848,645,2783,863,2413,712
        objects:
        - person
        filters:
          person:
            min_area: 8000
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.79

      zone_front_entry_cat:
        coordinates: 177,1192,840,854,505,588,0,808
        objects:
        - cat
        - dog
        filters:
          cat:
            min_area: 4000
            max_area: 21000
           # min_ratio: 0.5
           # max_ratio: 2.0
            min_score: 0.6
            threshold: 0.71

          dog:
            min_area: 5000
            max_area: 21000
           # min_ratio: 0.5
           # max_ratio: 2.0
            min_score: 0.7
            threshold: 0.81


    detect:
      width: 3072
      height: 2048
      fps: 8
    objects:
      filters:
        person:
          mask:
          - 500,456,472,83,753,0,1125,0,1117,297
          - 827,1066,2515,2048,3072,2048,3072,1650,2919,1512,1641,749,596,437,566,862
          - 601,1134,1713,1878,1621,2048,0,2048,0,1365,0,1080
          - 0,236,279,146,346,614,0,777
        car:
          mask:
          - 3072,1664,2686,1361,2814,920,3072,789

    record:
      events:
        required_zones:
        - zone_front_entry_people
        - zone_front_entry_dakoats_door
        - zone_front_entry_area
        - zone_front_entry_cat
    snapshots:
      required_zones:
      - zone_front_entry_people
      - zone_front_entry_dakoats_door
      - zone_front_entry_area
      - zone_front_entry_cat
 ####################################################################################################################################################  
  front_deck:
    ui:
      order: 2
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_deck #rtsp://admin:kk@192.168.1.30:554/Streaming/channels/201
        roles:
        - record
        - detect
    motion:
      threshold: 38
     #contour_area: 55
     #frame_height: 150
      mask:
      - 0,2160,857,2160,169,793,0,0
      - 2664,537,3120,343,3323,504,3220,873,3627,1261,3611,1623
      - 2124,1245,2276,1005,2567,1154,2460,1426
      - 2017,215,2079,488,2051,869,1442,617,1434,343,959,188,698,233,0,0,1966,0,2050,0,2528,0,3840,0,3840,482,3468,284,2912,218
    zones:
      zone_front_deck:
        coordinates: 34,2160,0,270,2267,106,3115,900,3840,1748,3840,2160
        objects:
        - person
        - cat
        - dog
        - bird
        filters:
          person:
            min_area: 260000
        #    max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
            min_score: 0.6
            threshold: 0.83
          cat:
            min_area: 80000
         #   max_area: 500000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.70
          dog:
            min_area: 80000
        #    max_area: 500000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.75

          bird: 
            min_area: 50
            max_area: 4000
            min_score: 0.6
            threshold: 0.7

      zone_front_deck_road:
        coordinates: 3153,704,2970,583,2447,188,2626,0,3840,452,3840,1473
        objects:
        - car
        - person
        - dog
        - bicycle
        filters:
          car:
            min_area: 12000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
            min_score: 0.6
            threshold: 0.60

          person:
            min_area: 1900
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.65

          dog:
            min_area: 800
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.65

          bicycle:
            min_area: 800
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.67  

    detect:
      width: 3840
      height: 2160
      fps: 8
    objects:
      filters:
        car:
          mask:
          - 2254,0,3840,1401,3840,2160,0,2160,0,752,0,0
        person:
          mask:
          - 3608,598,3585,702,3495,650,3530,543
    record:
      events:
        required_zones:
        - zone_front_deck
        - zone_front_deck_road
    snapshots:
      required_zones:
      - zone_front_deck
      - zone_front_deck_road





############################################################################################################################################################### 
  back_shed:
    ui:
      order: 3
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/back_shed #rtsp://admin:kk@192.168.1.30:554/Streaming/channels/301
        roles:
        - record
        - detect

    motion:
     # threshold: 20
     #contour_area: 55
     #frame_height: 150      
      mask:
      - 0,2160,1645,2160,656,1253,357,1125,87,879,71,883,0,1684
      - 0,783,1187,463,2323,480,3840,803,3840,0,877,0,0,0
      - 3381,252,3120,407,3044,826,3581,939,3557,520
    detect:
      width: 3840
      height: 2160
      fps: 8
    objects:
      track:
      - person
      - cat
      - dog
     #   - bird

      filters:
        person:
          min_area: 62000
        #  max_area: 100000
         # min_ratio: 0.5
         # max_ratio: 2.0
          min_score: 0.6
          threshold: 0.75

          mask:
          - 281,1167,162,918,0,879,0,2160,1241,2160
        cat:
          min_area: 29000
          max_area: 155000
        #  min_ratio: 0.5
         # max_ratio: 2.0
          min_score: 0.6
          threshold: 0.7

        dog:
          min_area: 29000
          max_area: 155000
         # min_ratio: 0.5
         # max_ratio: 2.0
          min_score: 0.6
          threshold: 0.7

     #   bird: 
      #    min_area: 100
      #    max_area: 7000
      #    min_score: 0.6
      #    threshold: 0.7
##########################################################################################################################################################          
  sand_pit:
    ui:
      order: 4
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/sand_pit #rtsp://admin:kk@192.168.1.30:554/Streaming/channels/401
        roles:
        - record
        - detect
    motion:
      threshold: 28
     #contour_area: 55
     #frame_height: 150
      mask:
      - 0,2160,0,0,1419,0,1387,230,1358,627,899,708,905,595,48,766,110,1283,508,1209,982,1793,1128,2160
      - 453,0,3840,0,3840,972,2866,614,2897,905,3171,637,3436,831,3388,1193,3666,1232,3840,1322,3840,2160,3031,2160,1793,1232,1626,934,1762,449,1442,388,1429,233
      - 702,795,1148,905,1445,899,1671,1290,1400,1552,731,1545,336,1089
    zones:
      zone_sand_pit:
        coordinates: 32,2136,0,890,1278,647,1293,546,1753,543,2876,902,3673,1539,3840,2160
        objects:
        - person
        - cat
        - dog
       #   - bird

        filters:
          person:
            min_area: 180000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.75
            threshold: 0.89
          cat:
            min_area: 10500
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.73
          dog:
            min_area: 8000
           # max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.7
     #     bird: 
      #      min_area: 100
      #      max_area: 7000
      #      min_score: 0.6
       #     threshold: 0.7

      zone_sand_pit_over_fence_area:
        coordinates: 2984,848,1915,489,1443,376,1450,224,3840,651,3815,1669
        objects:
        - person
        - car
        - bicycle

        filters:
          person:
            min_area: 900
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.6
          car:
            min_area: 13000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
            min_score: 0.6
            threshold: 0.65
          bicycle:
            min_area: 800
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.77

    detect:
      width: 3840
      height: 2160
      fps: 8
    record:
      events:
        required_zones:
        - zone_sand_pit_over_fence_area
        - zone_sand_pit
    snapshots:
      required_zones:
      - zone_sand_pit_over_fence_area
      - zone_sand_pit



###########################################################################################################################          

  360cam:
    ui:
      order: 6
    ffmpeg:
      inputs:
      - path: rtsp://admin:kk@192.168.1.66:554/MediaInput/h264
        roles:
        - record
        - detect
    motion:
      threshold: 75
      contour_area: 55
     #frame_height: 150
      mask:
      - 1256,302,1920,360,1920,0,803,0,870,48,1038,40,1259,61
      - 0,0,0,918,280,826,1287,693,1366,768,1540,723,1524,540,787,543,626,535,692,0
      - 1920,535,1920,1080,1681,1080,1658,551
    zones:
      zone_360_nextdoor:
        coordinates: 1561,262,1276,198,1057,0,1203,0,1920,0,1920,261
        objects:
        - person
        filters:
          person:
            min_area: 10000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
            min_score: 0.6
            threshold: 0.75

    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
      - cat
      - dog
      #  - bird

      filters:
        person:
          min_area: 100000
          max_area: 350000
        #  min_ratio: 0.5
        #  max_ratio: 2.0
          min_score: 0.6
          threshold: 0.85

        cat:
          min_area: 800
          max_area: 24000
         # min_ratio: 0.5
         # max_ratio: 2.0
          min_score: 0.6
          threshold: 0.75

        dog:
          min_area: 800
          max_area: 24000
         # min_ratio: 0.5
         # max_ratio: 2.0
          min_score: 0.6
          threshold: 0.75

       # bird: 
        #  min_area: 100
       #   max_area: 7000
       #   min_score: 0.6
      #    threshold: 0.7
 #####################################################################################################################################         
#testing
#####################################################################################################################################                     
# restream formate  rtsp://127.0.0.1:8554/front_deck - input_args: preset-rtsp-restream





###########################################
#################   PTZ     ###############
###########################################


 # ptzcamera:
  #  ffmpeg:
   #   inputs:
   #     - path: rtsp://127.0.0.1:8554/ptzcamera
    #      roles:
    #       # - record
   #         - detect
  #  onvif:
  #    host: 192.168.1.90
   #   port: 80
   #   user: admin
    #  password: kk
#

#logger:
#  logs:
  #  frigate.ptz.autotrack: debug
  #  frigate.ptz.onvif: debug   

```
