### DISCUSSION TITLE
Coral interference speed and detector speed higher than expected

### DISCUSSION THREAD

**Discussion by BigChris** [blakeblackshear/frigate#15602] [Ask A Question] [answered]
hello,
I have a higher coral interference speed than I would expect. I currently get an **interference speed of 30ms** under general stats. The detector cpu usage (coral) is partially at 65%. 
Another value is intel-vaapi with1,08%

I had expected a lower Coral Interference speed, what could be the reason for this?

**My system:**
Lenovo m720q tiny
Intel i3 8100T
8GB Ram
Coral TPU USB

**My config file:**

```
mqtt:
  enabled: false
#
ffmpeg:
  hwaccel_args: preset-vaapi
#
detectors:
  coral:
    device: usb
    type: edgetpu
#
cameras:
  Haustuer: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:%paranoid23!@10.10.10.18:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
    objects:
      track:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      retain:
        default: 31
#
#
  Terrasse: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:%paranoid23!@10.10.10.19:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
    objects:
      track:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      retain:
        default: 31
#  
#
  Gartentor: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.60:554/av0_1&user=admin&password=admin # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 720
      height: 576
    objects:
      track:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      retain:
        default: 31
    motion:
    zones:
      tor-relevant:
        coordinates: 0.005,0.005,0.266,0.003,0.262,0.814,0.71,0.802,0.996,0.9,0.998,0.994,0.002,0.997
        loitering_time: 0
version: 0.14
#
camera_groups:
  Birdseye:
    order: 1
    icon: LuWallpaper
    cameras: birdseye
```
