### DISCUSSION TITLE
[Config Support]: Continuously recording despite no motion... what did I configure wrong?

### DISCUSSION THREAD

**Discussion by StickySide** [blakeblackshear/frigate#15619] [Config Support] [answered]
### Describe the problem you are having

I carefully (or so I thought) read the configuration document and tried to set my two cameras (driveway and porch) to the "reduced storage" setting. IE only saving video when motion is detected, retaining motion video for 3 days, and events for 30. Despite this, it seems as if those two cameras are recording continuously 24/7 even for long stretches (hours) when theres no motion detected (no yellow bars). I masked off the timestamps and other areas with motion that could trigger it, and I do not think there is any motion detected evidenced by a lack of yellow bars on the motion tab for those cameras as well as the "live" view only updating every minute. Ive watched the debug view and it seems solid IE no red boxes popping up.

All I can think of at this point is my car parked in the driveway is being recognized as an object, but its stationary and not triggering any new events unless I move the car. Still wouldnt explain why my porch camera is recording continuously either...

Its quickly taking up a lot of storage!

Im sure ive just configured this wrong, any help would be greatly appreciated. Frigate is an amazing tool!! Thanks for all the hard work! 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.30
  port: 1883
  topic_prefix: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

##### Logging

logger:
  default: info
  logs:
    frigate.detectors: debug

##### Video

ffmpeg:
  hwaccel_args: preset-nvidia-h264

##### Recording

record:
  # sync_recordings: true
  enabled: true
  retain:
    days: 3   # <----- "3" for reduced settings, "0" for events only
    mode: motion # <----- "motion" for reduced settings, "all" for events only preset
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 30
      mode: motion

##### Detection

detectors:
  tensorrt:
    type: tensorrt
    device: 0

audio:
  enabled: true

##### Snapshots

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10

##### Model

model:
  # path: /config/model_cache/tensorrt/yolov4-tiny-416.trt # <----- Tiny Model
  path: /config/model_cache/tensorrt/yolov4-416.trt # <----- Full model 
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
  labelmap:
    15: cat # <----- was incorrectly mapped as "15: bird" but 15 is cat
    16: dog # <----- was incorrectly mapped as "16: cat" but 16 is dog

##### Objects

objects:
  track:
    - person
    - car
    - cat
    - dog
#  filters:
#    cat:
#      min_score: 0.6 #
#    dog:
#      min_score: 0.6


###### Review Settings (Global) 

review:
  alerts:
    labels:
      - person
      - car
  # detections:
  #   labels:
  #     - person
  #     - car
  #     - cat
  #     - dog

###### Web streams

go2rtc:
  streams:
    Livingroom:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main
    Livingroom_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub
    Kitchen:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
    Kitchen_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub
    Driveway:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_main
    Driveway_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_sub
    Porch:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_main
    Porch_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_sub


###### Cameras

cameras:

## LIVINGROOM ##
  Livingroom:
    enabled: true

    record: # <----- Recording setting
      enabled: false

    detect:
      enabled: false
      width: 1280
      height: 720

    audio:
      enabled: false

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub # <----- The stream you want to use for detection.. add one for recording later
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main # <----- Recording stream
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac # <----- audio on recordings

    onvif:
      host: 192.168.80.10
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    review:
      detections:
        labels:
          - person
          - car
          - cat
          - dog
      alerts:
        labels: []

    motion:
      mask: 0.01,0.075,0.315,0.079,0.316,0.01,0.012,0.01

## KITCHEN ##
  Kitchen:
    enabled: true

    record:
      enabled: false

    detect:
      enabled: false
      width: 1280
      height: 720

    review:
      detections:
        labels:
          - person
          - cat
          - dog
          - car
      alerts:
        labels: []

    audio:
      enabled: false

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub     # <----- The stream you want to use for detection.. add one for recording later
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac # <----- audio on recordings

    onvif:
      host: 192.168.80.11
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    motion:
      mask: 0.01,0.07,0.308,0.075,0.311,0.019,0.01,0.014

## DRIVEWAY ##

  Driveway:
    enabled: true

    # record:
    #   enabled: true

    detect:
      enabled: true
      width: 1280
      height: 720

    review:
      alerts:
        required_zones: Driveway_zone

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy

    # ffmpeg:  ## TESTING CONFIG ##
    #   inputs:
    #     - path: /media/frigate/testing/car.mp4 # TESTING
    #       input_args: -re -stream_loop -1 -fflags +genpts # TESTING
    #       roles:
    #         - detect
    #         - audio
    #         - record
    #   # output_args:
    #   #   record: preset-record-generic-audio-aac # <----- audio on recordings

    onvif:
      host: 192.168.80.12
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    zones:
      Street:
        coordinates: 0,0.51,0,0.865,0.17,0.677,0.438,0.346,0.778,0.087,0.727,0.02,0.29,0.286
        loitering_time: 0
        inertia: 3
      Driveway_zone:
        coordinates: 0.914,0.261,0.613,0.228,0.444,0.365,0.068,0.85,0.162,1,0.995,1,1,0.383
        loitering_time: 0
        inertia: 3

    motion:
      mask:
        - 0,0.207,0.305,0.064,0.32,0,0,0
        - 0,0.777,0.054,0.652,0.054,0.354,0,0.245
        - 1,0.217,0.762,0.107,0.592,0.056,0.488,0.036,0.457,0,1,0
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'

## PORCH ##

  Porch:
    enabled: true

    # record:
    #   enabled: true

    detect:
      enabled: true
      width: 1280
      height: 720

    review:
      alerts:
        required_zones:
          - Porch_zone
          - Front_Yard
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_sub # <----- RTSP Stream... stutters sometimes? Specific to RLC-1240A
            # rtmp://192.168.80.13/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=xxxxxxx #<----- RTMP stream is smooth
          input_args: preset-rtsp-restream
          # input_args: preset-rtmp-generic #<------ RTSP stream           
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy

    # ffmpeg:  ## TESTING CONFIG ##
    #   hwaccel_args: preset-nvidia-h264
    #   inputs:
    #     - path: /media/frigate/testing/car.mp4 # TESTING
    #       input_args: -re -stream_loop -1 -fflags +genpts # TESTING
    #       roles:
    #         - detect
    #         - audio
    #         - record
    #   output_args:
    #     record: preset-record-generic-audio-aac # <----- audio on recordings

    onvif:
      host: 192.168.80.13
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    motion:
      mask:
        - 0.005,0.078,0.428,0.083,0.43,0.011,0.006,0.01
        - 0.967,0.654,0.937,0.569,0.94,0.469,0.951,0.352,1,0.292,1,0.707

    zones:
      Street:
        coordinates: 
          0.998,0.755,0.805,0.5,0.542,0.237,0.343,0.105,0.342,0.005,0.47,0.009,0.794,0.17,0.955,0.346,0.999,0.445
        loitering_time: 0
        inertia: 3

      Porch_zone:
        coordinates: 
          0.334,0.347,0.322,0.331,0.31,0.339,0.288,0.313,0.16,0.388,0.253,0.999,0.828,0.998,0.338,0.388
        loitering_time: 0
        objects:
          - cat
          - dog
          - person

      Front_Yard:
        coordinates: 0.509,0.266,0.78,0.56,0.901,0.722,0.876,0.815,0.345,0.243,0.455,0.206
        loitering_time: 0
        objects:
          - cat
          - dog
          - person

##### Groups

camera_groups:
  Indoors:
    order: 2
    icon: LuCat
    cameras:
      - Kitchen
      - Livingroom

  Outdoors:
    order: 1
    icon: LuTreePine
    cameras:
      - Driveway
      - Porch

version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
Unraid docker
```

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/ba8ac4e9-a914-4251-87ea-a4e444c7793c)

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/54d1b09b-ac21-4caa-9db3-55f5aaf192e1)
Playing recorded video at this point on the scrubber.
