### DISCUSSION TITLE
Camera Specific Configurations Reolink Doorbell

### DISCUSSION THREAD

**Discussion by Jack77777777** [blakeblackshear/frigate#15611] [Config Support] [answered]
### Describe the problem you are having

Not sure how to setup this [https://docs.frigate.video/configuration/camera_specific#reolink-doorbell](url) in frigate camera section and frigate card. Specially "a secondary rtsp stream can be added that will be using for the two way audio **only**.", is this a live cam to which the view switches when someone rings.
I would be much appreciated with examples.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: IP
  port: 1883

go2rtc:
  streams:
    haustuer:
      - rtsp://USER:PW@IP:554/h264Preview_01_sub
      - "ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=USER&password=PW#video=copy#audio=copy#audio=opus" #MAIN (2560x1920)
    haustuer_sub:
      - "ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=USER&password=PW"


  webrtc:
    candidates:
      - IP:8555
      - stun:8555

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

cameras:
  haustuer:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/haustuer_sub
          input_args: preset-rtsp-restream
    detect:
      enabled: false
    live:
      stream_name: haustuer_sub
version: 0.14
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Frigate stats

```json
None
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
None
```

### Object Detector

CPU (no coral)
