### DISCUSSION TITLE
[Detector Support]: Help with consistent false positive in one area

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#15621] [Detector Support] [answered]
### Describe the problem you are having

I'm getting false positive 'person' detection alerts for one specific area of my yard consistently. See below for the latest example:

![detection](https://github.com/user-attachments/assets/bfb45b46-0168-44f0-990b-c7ec3d98a557)

It's a mulch bed so I have that area object masked (see below), but it's still throwing out false positives. Some of the area in the red box above is my driveway which I don't want object masked.

![Mask](https://github.com/user-attachments/assets/9cc01644-9920-4787-9372-486903473d7c)

Any suggestions on how to fine tune my config to avoid these?

Thanks!

### Version

 0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  host: 192.168.107.2
  port: 1883
  user: user
  password: password
  topic_prefix: frigate

go2rtc:
  streams:
    Driveway:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.107.3:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    objects:
      track:
        - person
      mask:
        - 0.192,0.595,0.795,0.662,1,1,0.001,0.996,0.004,0.703
        - 0.965,0.692,0.911,0.659,0.692,0.382,0.788,0.327,0.859,0.325,0.93,0.363,0.99,0.44,0.999,0.512
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

Please note...my config above is only for the one camera. I have 10 cameras so I removed all that code for simplicity sake
