### DISCUSSION TITLE
[Support]: Jumping Bounding Boxes on Stationary Objects

### DISCUSSION THREAD

**Discussion by ofcedwards** [blakeblackshear/frigate#15629] [General Support] [answered]
### Describe the problem you are having

I don't believe there have been any changes to object detection, but I've been experiencing an increase in object detection constantly running on stationary objects in the past week or so. Stationary objects (particularly parked cars) have always been an issue for me, but usually they just generate short events and I get separate detections with thumbnails showing objects that truly moved.

However, lately I've been having an issue where a stationary vehicle (size > 100000 in debug) has object detection run on it for extended periods of time, which cause all other objects to get bundled into one single detection that only shows the stationary vehicle as the thumbnail. I've experienced detections that last for over an hour. This issue is also causing alerts (which I only have configured for people) to go for long periods of time because continued object detection doesn't allow the alert to end. 

I know object detection can get triggered from motion happening, but the bounding box will continue to jump even if minutes have gone by since the last motion was detected. I'm assuming that the best fix for this would be to get a model through Frigate+, but any other help would be appreciated.

### Version

0.15.0-1b7fe95

### Frigate config file

```yaml
mqtt:
  host: ***
  user: ***
  password: ***

database:
  path: /db/frigate.db

semantic_search:
  enabled: true
  reindex: false
  model_size: small

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record
            - detect
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      height: 960
      width: 1280
      fps: 5
      annotation_offset: -350
    zones:
      front_yard:
        coordinates: 
          0,1,1,1,1,0.578,0.914,0.568,0.742,0.589,0.562,0.599,0.348,0.599,0.137,0.589,0,0.609
    motion:
      mask:
        - 0.23,0,0.23,0.03,0.128,0.03,0.128,0
        - 0,0.249,0.153,0.152,0.309,0.087,0.415,0.067,0.396,0.443,0.321,0.394,0.266,0.446,0.263,0.477,0.155,0.477,0.123,0.455,0.066,0.462,0,0.456
        - 0.496,0.44,0.495,0.052,0.66,0.067,0.767,0.097,0.849,0.125,0.878,0.256,0.893,0.389,0.896,0.446,0.794,0.454,0.72,0.455,0.653,0.455,0.594,0.455,0.545,0.461
        - 0.966,0.415,0.947,0.262,0.922,0.152,0.906,0.095,0.878,0,1,0,1,0.41
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask: 0.164,0.556,0.26,0.564,0.371,0.567,0.371,0.496,0.238,0.497
        person:
          mask:
            - 0.236,0.562,0.261,0.563,0.26,0.554,0.236,0.554
            - 0.305,0.559,0.364,0.559,0.364,0.541,0.305,0.54
    review:
      alerts:
        labels:
          - person
        required_zones:
          - front_yard

record:
  enabled: true
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  retain:
    default: 30

objects:
  track:
    - person
    - car
    - dog
    - cat
    - bird
    - bicycle
    - motorcycle
    - bus
  filters:
    person:
      min_area: 250
    car:
      min_area: 500
      min_ratio: .75
    motorcycle:
      min_ratio: .75
    bird:
      min_area: 250

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci:0

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 1
  effect: solid

go2rtc:
  streams:
    front_door:
      - rtsp://user:pass@192.168.*.*:554/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0
      - ffmpeg:front_door#audio=opus
  webrtc:
    candidates:
      - 192.168.*.*:8555
      - stun:8555

version: 0.15-0
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

Amcrest
