### DISCUSSION TITLE
Duplicate-key error when saving config.yaml

### DISCUSSION THREAD

**Discussion by baitinghollow** [blakeblackshear/frigate#15620] [Config Support] [answered]
### Describe the problem you are having

Greetings, I have 5 cameras and all are working fine. Although I’m having trouble with the last one on my list. It is a Reolink Doorbell WIFI.  FrontDoorMain and FrontDoorSub
  The basic problem is that I can save the config file with either stream, but not both. Either stream works fine by itself. When trying to save both the main and sub streams a config error occurs with something about a duplicate-key. I have tried renaming the streams to no avail. 
  I can live with one stream or the other, but this is just bugging me
Any idea how to remedy this?
Thanks

### Version

frigate:0.15.0-beta3-tensorrt

### Frigate config file

```yaml
mqtt:
  host: 192.168.xx.10
  port: 1883
  user: homeassistant
  password: xxxxxxxxxxxxxxxxxxxx

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    DrivewayCam: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.51:554/cam/realmonitor?channel=1&subtype=0
    DrivewayCamSub: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.51:554/cam/realmonitor?channel=1&subtype=1
    YardCam: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.52:554/cam/realmonitor?channel=1&subtype=0
    YardCamSub: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.52:554/cam/realmonitor?channel=1&subtype=1
    PatioCam: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.53:554/cam/realmonitor?channel=1&subtype=0
    PatioCamSub: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.53:554/cam/realmonitor?channel=1&subtype=1
    FrontCam: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.54:554/cam/realmonitor?channel=1&subtype=0
    FrontCamSub: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.54:554/cam/realmonitor?channel=1&subtype=1
    FrontDoorMain: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.55:554/h265Preview_01_main
    FrontDoorSub: 
      ffmpeg:rtsp://admin:xxxxxxx@192.168.xx.55:554/h265Preview_01_sub

cameras:
  FrontDoorBell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoorMain
          input_args: preset-rtsp-restream
          roles:
            - record
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoorSub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant Frigate log output

```shell
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 187, in config_save
    FrigateConfig.parse_yaml(new_config)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 700, in parse_yaml
    return cls.parse(config_yaml, is_json=False, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 693, in parse
    config = yaml.load(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/main.py&#34;, line 451, in load
    return constructor.get_single_data()
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 116, in get_single_data
    return self.construct_document(node)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 125, in construct_document
    for _dummy in generator:
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 1476, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 1365, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 188, in construct_non_recursive_object
    for _dummy in generator:
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 1476, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 1365, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 188, in construct_non_recursive_object
    for _dummy in generator:
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 1476, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 1366, in construct_mapping
    if self.check_mapping_key(node, key_node, maptyp, key, value):
  File &#34;/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py&#34;, line 278, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in &#34;&lt;unicode string&gt;&#34;, line 37, column 5:
        ffmpeg:
        ^ (line: 37)
found duplicate key &#34;ffmpeg&#34; with value &#34;{&#39;inputs&#39;: [{&#39;path&#39;: &#39;rtsp://127.0.0.1:8554/FrontDoorSub&#39;, &#39;input_args&#39;: &#39;preset-rtsp-restream&#39;, &#39;roles&#39;: [&#39;detect&#39;]}]}&#34; (original value: &#34;{&#39;inputs&#39;: [{&#39;path&#39;: &#39;rtsp://127.0.0.1:8554/FrontDoorMain&#39;, &#39;input_args&#39;: &#39;preset-rtsp-restream&#39;, &#39;roles&#39;: [&#39;record&#39;]}]}&#34;)
  in &#34;&lt;unicode string&gt;&#34;, line 43, column 5:
        ffmpeg:
        ^ (line: 43)

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3-tensorrt
    shm_size: "2g"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/peter/frigate/config:/config
      - /home/peter/frigate/:/media/frigate
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Port used by the Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971"
    environment:
      FRIGATE_RTSP_PASSWORD: xxxxxxx
      YOLO_MODELS: yolov7x-640
```

### Object Detector

TensorRT
