### DISCUSSION TITLE
Auto tracking continues when toggled off.

### DISCUSSION THREAD

**Discussion by jnrollins** [blakeblackshear/frigate#15631] [Ask A Question] [answered]
Before I go too deep into details - could there be any reason why auto tracking would continue hours after toggling off the main auto tracking toggle and the camera level auto tracking toggle? I noticed one of my cameras continuing to auto track hours after toggling both switches off in the frigate UI.

**Comment by hawkeye217** [comment]
When you say "main" auto tracking toggle, what are you referring to?

**Reply by jnrollins** [reply]
Well I guess I should say top toggle button and bottom toggle button. When I click a camera preview to enter full size live view I have the upper button row in the ui with detect, record, snapshots, autotracking etc. Then in the ptz controls within the camera image there is a second autotracking button. I at least assume that's what it is bc it looks like the same icon and only appears when auto tracking is enabled in the config. There is no tooltip but it appeared to turn autotracking on and off..sometimes. They can both be toggled independently though which is confusing. I'm not at home but will take a screenshot when I get back.

**Reply by hawkeye217** [reply]
The button on the bar over the camera image with the PTZ arrows next to it is for Frigate's manual "click-to-track" feature. Clicking anywhere in the camera frame will center that point in the frame. 

The button at the top right of the Live camera view is what actually toggles Frigate's autotracking on and off.

**Reply by jnrollins** [reply]
Ah ok ty for the clarification. That makes more sense that two buttons for the same function. Still getting up to speed on everything. So, I guess then the question still stands - what might cause autotracking to continue after being disabled? The camera itself doesn't have autotracking so can rule that out. Just unsure where to start investigating.

**Reply by hawkeye217** [reply]
If you turn off autotracking (with the top right toggle in Live view), the camera will not move until you turn it back on.

You will see a message in your Frigate log when it's enabled or disabled via that toggle. If you're not seeing that, there's something else going on.

**Reply by jnrollins** [reply]
Here's a video just to show I'm not crazy.
https://photos.app.goo.gl/7rGNBy5z3v2vaFANA

I am not seeing any log message saying autotracking is being enabled/disabled when I toggle the switch. The only log message I see is frigate.ptz.onvif: Bedroom is already performing an action, not moving...

Now I am sure there are plenty of things to fix up in my config but really just want to zero in on the onvif issue at the moment.

```
mqtt:
  enabled: true
  host: 192.168.1.6
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password 

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 3

go2rtc:
  streams:
    FrontDoorbell:
      - rtsp://user:password@192.168.1.123/h264Preview_01_main
    FrontDoorbell_sub:
      - rtsp://user:password@192.168.1.123/h264Preview_01_sub
    Bedroom:
      - rtsp://user:password@192.168.1.104/cam/realmonitor?channel=1&subtype=0
    Bedroom_sub:
      - rtsp://user:password@192.168.1.104/cam/realmonitor?channel=1&subtype=1

cameras:
  FrontDoorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.208:8554/FrontDoorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.208:8554/FrontDoorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 480
      height: 640
      fps: 5
    objects:
      track:
        - person
        - cat
        - package
      filters:
        person:
          threshold: 0.60
        cat:
          threshold: 0.5
        package:
          threshold: 0.5
    record:
      enabled: true
    live:
      stream_name: FrontDoorbell
    motion:
      mask:
        - 0.713,0.004,0.269,0.002,0.267,0.035,0.714,0.041
        - 0.781,0.378,0.771,0.508,0.863,0.513,0.878,0.386
  Bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.208:8554/Bedroom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.208:8554/Bedroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.1.104
      port: 80
      user: admin
      password: Lorelei2022
      #ignore_time_mismatch: true
      autotracking:
        enabled: true
        calibrate_on_startup: false
        track:
          - person
        required_zones:
          - all
        return_preset: preset1
        timeout: 10
        movement_weights: 0.0, 1.0, 0.0730447769165039, 16321800.07529796, -7588743.644069071
    detect:
      enabled: true
      width: 850
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.55
        cat:
          threshold: 0.5
    record:
      enabled: true
    live:
      stream_name: Bedroom
    motion:
      mask: 0.753,0.037,0.963,0.037,0.963,0.078,0.753,0.081
    zones:
      all:
        coordinates: 0.003,0.006,0.003,0.994,0.997,0.968,0.996,0.005
        loitering_time: 0
        objects: person
version: 0.14
``` 

I read in another post that having a full screen zone is not ideal. I DO have a full screen zone for triggering autotracking but that was kinda just for testing things. Can't see how that would impact it being on when it should not be. Thanks for the replies and let me know if I am missing something glaring.
