### DISCUSSION TITLE
[Support]: Connection to home assistant keeps crashing

### DISCUSSION THREAD

**Discussion by kru96** [blakeblackshear/frigate#15649] [General Support]
### Describe the problem you are having

These lines keep appearing several times a day (20 to 30 times) in my home assistant log:

2024-12-13 09:22:09.285 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://192.168.1.150:5000/api/stats: 
2024-12-13 09:22:09.286 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data: 
2024-12-13 09:22:09.660 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=62 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=62, family=2, type=2, proto=0, laddr=('0.0.0.0', 60643)>
2024-12-13 09:22:09.663 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=63 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=63, family=10, type=2, proto=0, laddr=('::', 50589, 0, 0)>

The second 2 lines not always, sometimes just ends at "Error fetching frigate data: "

The corresponding Frigate server and cameras devices appear as "Unavailable" in the logbook. They stay unavailable for about 3 minutes.

This started happening some days (even weeks) after setting everything up for the first time and working properly AND before updating to the current version of frigate.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Chrome 131.0.6778.205 (Official Build) (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.149
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: #########
  password: ##########

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -an

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: pci

objects:
  track:
    - person

cameras:
  taller: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://####:######@192.168.1.66:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://###:######@192.168.1.66:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 6
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
    motion:
      mask:
        - 211,0,212,0,200,67,0,95,0,0
  entrada: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://########:#######@192.168.1.65:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://#####:#########@192.168.1.65:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 6
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
    motion:
      mask:
        - 211,0,212,0,200,67,0,95,0,0
  maqueta: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://########:#########@192.168.1.67:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://########:#####@192.168.1.67:554/Streaming/Channels/101/
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 6
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
    motion:
      mask:
        - 211,0,212,0,200,67,0,95,0,0

ui:
  strftime_fmt: '%d/%m/%Y %H:%M'
version: 0.14
```

### Relevant Frigate log output

```shell
No entries for weeks
```

### Relevant go2rtc log output

```shell
No entries for weeks
```

### FFprobe output from your camera

```shell
??
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/apex_0:dev/apex_0
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

HikVision DS-2CD1023G0E-I

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/48732b54-c88f-4af5-a2e3-e36539b4b476)
