### DISCUSSION TITLE
Missing audio in history playback

### DISCUSSION THREAD

**Discussion by tpjanssen** [blakeblackshear/frigate#15663] [Ask A Question]
I was running an old 0.13 installation, where camera streams were restreamed to my 0.15.0 beta installation. I'm moving away from this, now my 0.15.0 beta connects directly to my cameras. Having some problems with the audio of one of cameras now. The live view of the camera gives audio, however playing back history doesn't.

Relevant camera config:

```yaml
go2rtc:
  streams:
    voordeur:
      - rtsp://admin:REDACTED@192.168.5.143:554/cam/realmonitor?channel=1&subtype=1
    voordeur_detect:
      - rtsp://admin:REDACTED@192.168.5.143:554/cam/realmonitor?channel=1&subtype=0

cameras:
  voordeur:
    webui_url: http://192.168.5.143/
    mqtt:
      quality: 95
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/voordeur
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/voordeur_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: voordeur
```

The go2rtc API gives this on first "voordeur" stream:

```json
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.5.143:554/cam/realmonitor?channel=1\u0026subtype=1/",
      "remote_addr": "192.168.5.143:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 2261922225 2261922225 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-packetization-supported:IV\r\na=x-rtppayload-supported:IV\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:25.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=420028;sprop-parameter-sets=Z0IAKOkA8ARPywgAAB9IAAYcECAA,aMqPIAA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 0\r\na=control:trackID=1\r\na=rtpmap:0 PCMU/8000\r\na=recvonly\r\nm=audio 0 RTP/AVP 0\r\na=control:trackID=5\r\na=rtpmap:0 PCMU/8000\r\na=sendonly\r\n",
      "medias": [
        "video, recvonly, H.264 Baseline 4.0",
        "audio, recvonly, PCMU/8000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=101795130, senders=1"
      ],
      "recv": 102650682
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/voordeur",
      "remote_addr": "127.0.0.1:41758",
      "user_agent": "FFmpeg Frigate/0.15.0-87e7b62",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=420028;sprop-parameter-sets=Z0IAKOkA8ARPywgAAB9IAAYcECAA,aMqPIAA=\r\na=control:trackID=0\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=101795130, receivers=1"
      ],
      "send": 102934586
    }
  ]
}
```

And the other "voordeur_detect" stream:

```json
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.5.143:554/cam/realmonitor?channel=1\u0026subtype=0/",
      "remote_addr": "192.168.5.143:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 2261922225 2261922225 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-packetization-supported:IV\r\na=x-rtppayload-supported:IV\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:10.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=42001F;sprop-parameter-sets=Z0IAH+kAoAt0IAAAfSAACcaAgAA=,aMqPIAA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 0\r\na=control:trackID=1\r\na=rtpmap:0 PCMU/8000\r\na=recvonly\r\n",
      "medias": [
        "video, recvonly, H.264 Baseline 3.1",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=34672672, senders=1"
      ],
      "recv": 34978804
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/voordeur_detect",
      "remote_addr": "127.0.0.1:41806",
      "user_agent": "FFmpeg Frigate/0.15.0-87e7b62",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=42001F;sprop-parameter-sets=Z0IAH+kAoAt0IAAAfSAACcaAgAA=,aMqPIAA=\r\na=control:trackID=0\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=34672672, receivers=1"
      ],
      "send": 35077328
    }
  ]
}
```

Why I'm a missing audio in the history playback? I would expect it to be the same stream?

I'm using "Chrome 131.0.6778.205 (Official Build) (64-bit)", but other browsers have the same outcome.
