### DISCUSSION TITLE
[HW Accel Support]: Move from Intel iGPU to dual Quadro P200

### DISCUSSION THREAD

**Discussion by kavejo** [blakeblackshear/frigate#15665] [Hardware Acceleration Support]
### Describe the problem you are having

I am in the process of changing the hardware I am using for Frigate as I'd love to pair it with Double Take.

Currently I have a Lenovo M900 with i5-6500T having a built-in Intel HD Graphics 530 which with 11 Full HD streams (10 are h.246 and 1 is h.265) is practically maxed out. Detection is done by 2 Coral USB.

I've got hold of a Lenovo P520 with a Xeon CPU, more RAM, and 2 Nvidia Quadro P2000 built-in which I am planning to move Frigate to. I'd love to use both GPU for h/w decoding and for object detection, this last task paired with the Coral USBs.

I've read around and found https://docs.frigate.video/configuration/hardware_acceleration/ which suggest I need to modify the docker compose file and add the "deploy" portion, but how would I pass 2 Quadro? Would I need to increase the "count" or add more "device_ids"?

As I had issues with h.265 streams with the current hardware, would I be able to use h.265 streams (that are 4K instead of 1080p) in the new hardware?

Would I still need to use go2rtc? Or would it be unnecessary at that point?

Also, is there a way to simplify the config file as I feel there might be parts that are redundant but I am not entorely sure.

Thanks!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.1.4.2:5000/api/config/schema.json
# Stream 0: 2688x1520 h.265
# Stream 1: 704x576 mpeg
# Stream 2: 1920x1080 h.264

logger:
  default: warning

mqtt:
  host: x.x.x.x
  port: xxxx
  user: xxxxx
  password: xxxx

detectors:
  coral-right:
    type: edgetpu
    device: usb:0
  coral-left:
    type: edgetpu
    device: usb:1

objects:
  track:
    - person
    - car
    - motorcycle
  filters:
    person:
      min_score: 0.6
      threshold: 0.8
    car:
      min_score: 0.6
      threshold: 0.7
    motorcycle:
      min_score: 0.5
      threshold: 0.7

review:
  alerts:
    labels:
      - car
      - person
      - motorcycle
  detections:
    labels:
      - car
      - person
      - motorcycle

record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 14

birdseye:
  enabled: false

live:
  height: 1080
  quality: 8

ui:
  timezone: Europe/Rome

detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: true

audio:
  enabled: false
  listen:
    - bark
    - chatter
    - dog
    - explosion
    - scream
    - speech
    - yell

go2rtc:
  streams:
    01:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=1&subtype=2
      - ffmpeg:01#video=h264#hardware
    02:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=2&subtype=2
      - ffmpeg:02#video=h264#hardware
    03:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=3&subtype=2
      - ffmpeg:03#video=h264#hardware
    04:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=4&subtype=2
      - ffmpeg:04#video=h264#hardware
    05:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=5&subtype=2
      - ffmpeg:05#video=h264#hardware
    06:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=6&subtype=2
      - ffmpeg:06#video=h264#hardware
    07:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=7&subtype=2
      - ffmpeg:07#video=h264#hardware
    08:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=8&subtype=2
      - ffmpeg:08#video=h264#hardware
    09:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=9&subtype=2
      - ffmpeg:09#video=h264#hardware
    10:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=10&subtype=2
      - ffmpeg:10#video=h264#hardware
    11:
      - rtsp://USER:PASS@IP:PORT/cam/realmonitor?channel=11&subtype=1
      - ffmpeg:11#video=h264#hardware
  webrtc:
    candidates:
      - x.x.x.x:8555

cameras:

  01:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/01
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  02:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/02
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  03:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/03
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  04:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/04
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  05:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/05
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  06:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/06
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  07:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/07
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  08:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/08
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  09:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/09
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  10:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/10
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

  11:
    ffmpeg:
      inputs:
        - path: rtsp://LOCAL:PORT/11
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false

telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb"

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/CONFIG/Frigate/config.yml:/config/config.yml
      - /mnt/USB/Friguate/config:/config
      - /mnt/USB/Frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    ports:
      - "5000:5000" # Web UI
      - "1935:1935" # RTMP
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC over TCP
      - "8555:8555/udp" # WebRTC over UDP
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua

### Screenshots of the Frigate UI's System metrics pages

N/A

**Comment by NickM-27** [comment]
1. You can't run corals and Tensortt for detection at the same time 
2. Yes just set the count to 2
3. This change wouldn't affect anything regarding h265 compatibility, that is client dependent
4. Go2rtc is always necessary for the best live view experience

**Comment by kavejo** [comment]
Thanks @NickM-27.

1. In such case would I be best running Coral or Tensor? Is it just a matter to test and verify which one has a higher inference speed and lower false positives?

2. Ok, so something like the below? Is there any other capability that need to be added?
```
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','0'] # this is only needed when using multiple GPUs
              count: 2 # number of GPUs
              capabilities: [gpu]
```
3. Understood - So would I be better using h.265 for record/detect as the stream has a higher resolution and decode it to h.264 for the viewing on the clients (as for example notifications through HA were not viewable in iOS when the notification came with a h.265 feed)?

4. How would I best configure go2rtc for this? Would I just need to change the string "ffmpeg:01#video=h264#hardware"? Is it then best to do detect/record on the go2rtc stream or the source stream?

THanks!

**Reply by NickM-27** [reply]
1. That depends on you, the coral would be more power efficient but can't run large models like the GPU can
2. You should comment out the device_ids part
3. Not sure I know where you would be decoding the stream
4. I don't think it makes sense to transcode to h264 personally, provided the client supports h265 which most do

**Reply by kavejo** [reply]
Hi @NickM-27,

Finally I’m in the process of moving to the new hardware and I’m migrating the configuration.

My current line of thought is to get Frigate to deal with the streams in go2rtc as they come in (they are already all h.265 2688x1520 at 20fps) without decoding/encoding.

I’ve passed to Frigate both the P2000 on the docker compose. A couple of things I’m struggling with.
on the Web UI I only see 1 P2000 despite within the container of I run nvidia-smi I see both. And all the ffmpeg processes land on gpu 0, leaving gpu 1 practically idle.

Specifically for the second issue I’ve gone through https://github.com/blakeblackshear/frigate/discussions/7792 but In this other discussion there is a desire do decode/encode which I don’t have.

Could I kindly ask for some help?

**Reply by NickM-27** [reply]
> on the Web UI I only see 1 P2000 despite within the container of I run nvidia-smi I see both. And all the ffmpeg processes land on gpu 0, leaving gpu 1 practically idle.

this is a known issue because they have the same name. I will work on a fix for this.

> Specifically for the second issue I’ve gone through https://github.com/blakeblackshear/frigate/discussions/7792 but In this other discussion there is a desire do decode/encode which I don’t have.

you can define at the camera level the `global_args` where you copy the default global args and then include `-gpu 0` or `-gpu 1` depending on what GPU you want to be used

**Reply by kavejo** [reply]
Thanks @NickM-27  for the confirmation about the first issue.

I have tried to follow your guidance about the global_args, and review the content of the discussion linked earlier but I can't seem to get this working.

My current configuration is the following.

```
go2rtc:
  ffmpeg:
    cuda0: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 0 -rtsp_transport tcp -i {input}"
    cuda1: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 1 -rtsp_transport tcp -i {input}"
  streams:
    01-Cancello:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:01-Cancello#video=copy#audio=copy#hardware=cuda#input=cuda0#raw= -gpu 0"
    02-Entrata:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=2&subtype=0
      - "ffmpeg:02-Entrata#video=copy#audio=copy#hardware=cuda#input=cuda1#raw= -gpu 1"
    03-Garage:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=3&subtype=0
      - "ffmpeg:03-Garage#video=copy#audio=copy#hardware=cuda#input=cuda0#raw= -gpu 0"
    04-Giardino:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=4&subtype=0
      - "ffmpeg:04-Giardino#video=copy#audio=copy#hardware=cuda#input=cuda1#raw= -gpu 1"
    05-Terrazza:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=5&subtype=0
      - "ffmpeg:05-Terrazza#video=copy#audio=copy#hardware=cuda#input=cuda0#raw= -gpu 0"
    06-Pozzo:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=6&subtype=0
      - "ffmpeg:06-Pozzo#video=copy#audio=copy#hardware=cuda#input=cuda1#raw= -gpu 1"
    07-Uffici:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=7&subtype=0
      - "ffmpeg:07-Uffici#video=copy#audio=copy#hardware=cuda#input=cuda0#raw= -gpu 0"
    08-Retro:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=8&subtype=0
      - "ffmpeg:08-Retro#video=copy#audio=copy#hardware=cuda#input=cuda1#raw= -gpu 1"
    09-Campo:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=9&subtype=0
      - "ffmpeg:09-Campo#video=copy#audio=copy#hardware=cuda#input=cuda0#raw= -gpu 0"
    10-Riva:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=10&subtype=0
      - "ffmpeg:10-Riva#video=copy#audio=copy#hardware=cuda#input=cuda1#raw= -gpu 1"
    11-Campanello:
      - rtsp://{FRIGATE_RTSP_USER_NVR}:{FRIGATE_RTSP_PASSWORD_NVR}@{FRIGATE_RTSP_HOST_NVR}:554/cam/realmonitor?channel=11&subtype=1
      - "ffmpeg:11-Campanello#video=copy#audio=copy#hardware=cuda#input=cuda0#raw= -gpu 0"
  log:
    level: info
    exec: trace
    rtsp: warn
    streams: warn
    webrtc: warn
  webrtc:
    candidates:
      - stun:8555
```

However  on nvidia-smi I see everything on GPU 0.

![image](https://github.com/user-attachments/assets/8003fef2-ecb2-4820-b8aa-a1124449f37e)

**Reply by NickM-27** [reply]
The config you're showing here is not at all what I suggested doing

**Reply by kavejo** [reply]
Then I might have misudenrstood the reccomandation or got off a tangent when looking at the other discussion.

I read this and then looked at https://github.com/blakeblackshear/frigate/discussions/7792 regarding how I could do that.

> you can define at the camera level the global_args where you copy the default global args and then include -gpu 0 or -gpu 1 depending on what GPU you want to be used

Could I kindly ask you an example - even just for the first camera - about how you'd approach it so i could replicate it to the other 10?

Thanks!

**Reply by NickM-27** [reply]
```
cameras:
  one:
    ffmpeg:
      global_args: (default global args, see config reference) -gpu 0
    ...
```
