### DISCUSSION TITLE
[Support]: Built-in LPR

### DISCUSSION THREAD

**Discussion by xavan83** [blakeblackshear/frigate#15664] [General Support]
### Describe the problem you are having

Using 0.16, I am trying to test LPR detection. 
I add lpr enable true in the config file (not sure if I need to also add that config directly to the camera).
I see that some files are downloaded during first frigate startup.
My Frigate+ model is detecting license plates and I receive boxes containing license plates in mqtt messages.
However, Frigate+ does not add a sublabel in the car object containing the detected plate.
How can I add some logs in frigate to see if everything is correctly setup?

### Version

0.16.0-c7c96b65

### Frigate config file

```yaml
lpr:
  enabled: true
review:
  alerts:
    labels:
      - car
      - person
      - speech
  detections:
    labels:
      - bark
      - dog
      - cat

At camera level:
 objects:
      filters:
        car: {}
        cat: {}
        dog: {}
      track:
        - face
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
        - horse
        - package
        - license_plate
```

### Relevant Frigate log output

```shell
Nothing relevant
```

### Relevant go2rtc log output

```shell
Nothing relevant
```

### FFprobe output from your camera

```shell
Nothing relevant
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
nothing relevant
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

Last mqtt event:
topic frigate/events message: {"before": {"id": "1735032999.684493-vsha1q", "camera": "sonnette", "frame_time": 1735033002.196692, "snapshot": {"frame_time": 1735033000.545768, "box": [404, 290, 859, 537], "area": 112385, "region": [249, 0, 913, 664], "score": 0.9453125, "attributes": [{"label": "license_plate", "score": 0.71875, "box": [456, 463, 530, 509]}]}, "label": "car", "sub_label": null, "top_score": 0.9765625, "false_positive": false, "start_time": 1735032999.684493, "end_time": null, "score": 0.96875, "box": [786, 265, 959, 416], "area": 26123, "ratio": 1.1456953642384107, "region": [640, 191, 960, 511], "active": true, "stationary": false, "motionless_count": 0, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true, "attributes": {"license_plate": 0.71875}, "current_attributes": [], "pending_loitering": true, "max_severity": "detection"}, "after": {"id": "1735032999.684493-vsha1q", "camera": "sonnette", "frame_time": 1735033002.966957, "snapshot": {"frame_time": 1735033000.545768, "box": [404, 290, 859, 537], "area": 112385, "region": [249, 0, 913, 664], "score": 0.9453125, "attributes": [{"label": "license_plate", "score": 0.71875, "box": [456, 463, 530, 509]}]}, "label": "car", "sub_label": null, "top_score": 0.9765625, "false_positive": false, "start_time": 1735032999.684493, "end_time": 1735033006.9475, "score": 0.828125, "box": [916, 267, 959, 370], "area": 4429, "ratio": 0.4174757281553398, "region": [640, 159, 960, 479], "active": true, "stationary": false, "motionless_count": 0, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true, "attributes": {"license_plate": 0.71875}, "current_attributes": [], "pending_loitering": true, "max_severity": "detection"}, "type": "end"}
