### DISCUSSION TITLE
Recording not found after upgrade

### DISCUSSION THREAD

**Discussion by B0ndo2** [blakeblackshear/frigate#15660] [General Support] [answered]
### Describe the problem you are having

I upgraded to 0.14.0 and now I can't see my recordings in the UI (they are still on disk).
I followed the steps in the release notes (Recordings can still be viewed in the new UI using the recordings viewer (From Live view, click/tap on a camera and select the History button at the top left))

### Version

0.14.1

### What browser(s) are you using?

Firefox 133.0 (64-bit)

### Frigate config file

```yaml
# frigate.yml
detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
logger:
  logs:
    frigate.record.maintainer: debug
mqtt:
  # Required: host name
  host: caha.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: Fr1g@te21
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
rtmp:
  enabled: false
motion:
#  improve_contrast: false
  contour_area: 30
#  delta_alpha: 0.2
#  frame_alpha: 0.2
#  frame_height: 80
  threshold: 40
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

cameras:
  driveway:
    timestamp_style:
      position: tr
      color:
        red: 255
        green: 0
        blue: 0
    zones:
      sidewalk:
        coordinates: 409,52,368,17,241,18,227,50
        #coordinates: 114,64,232,57,302,62,409,68,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
        objects:
        - car
      drive_way:
        coordinates: 274,47,441,62,508,76,562,189,550,260,562,286,429,352,0,352,30,207,108,66
        objects:
        - person

    objects:
      track:
      - person
      - car
      filters:
        person:
          mask:
          - 114,64,231,43,292,43,364,47,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
          threshold: 0.6
          min_area: 1300
          max_area: 30320
    ffmpeg:
      inputs:
      - path: rtsp://xxx:xxx@192.168.6.140/2
        roles:
        - detect
        - audio
      - path: rtsp://xxx:xxx@192.168.6.140/1
        roles:
        - record

    audio:
      enabled: true
      min_volume: 600
      listen:
      - scream
      - speech
      - yell
    detect:
      width: 640
      height: 352
      fps: 5
   #   stationary:
    #    interval: 0
    #    threshold: 50
    motion:
      mask:
      - 0,0,181,0,100,81,0,304
      - 640,0,473,0,489,65,571,100,640,191
      - 234,14,399,18,504,45,474,0,172,0,151,27
    record:
      enabled: true
      retain:
        days: 0
      events:
        required_zones:
        - drive_way
        - sidewalk
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
      - drive_way
      - sidewalk
      timestamp: true
      retain:
        default: 7


################################################ 
  front_porch_camera:
    objects:
      track:
      - person
      filters:
        person:
          #threshold: 0.75
          mask:    
          - 176,352,171,122,173,12,377,8,518,57,640,168,640,0,0,0,0,352
    ffmpeg:
      inputs:
      - path: rtsp://xxx:xxx@192.168.6.141/2
        roles:
        - detect
      - path: rtsp://xxx:xxx@192.168.6.141/1
        roles:
        - record
    detect:
      width: 640
      height: 352
      fps: 5
    motion:
      mask:
      - 176,352,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 7
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

N/A

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/b0902a66-3690-4aae-98b8-3070c887048e)
