### DISCUSSION TITLE
Live View Wrong Res and No Audio

### DISCUSSION THREAD

**Discussion by Al-Dek** [blakeblackshear/frigate#15667] [Config Support] [answered]
### Describe the problem you are having

Hi!
I can't get high resolution and there is no sound (there is no speaker icon) in live view for H.265 cameras. 
H.264 cameras have no problems.
It may be a coincidence, but the sound disappeared today, as I noticed,  after updating the Frigate custom card to the version v6.1.2.
A Frigate Recording for all cameras (H.264 & H.265) works perfect with high res and sound (see pic.3).
Before update I have the Main Page View (pic.1) with low res for all H.265 cameras and the high res live view with sound for every camera on single (selected) camera page  (pic.2). 
Before update the high resolution for H.265 camera  appeared on the main page for a few seconds  after first time motion detected, but only first time, and after that only the low res of the detection mode appeared.
I have only low (detection) resolution now. 
I've tried various settings (inc. live: stream_name: Cam-0-s ... see attached config)  but with no success. 
Everything works fine in the go2rtc web interface and in the custom Frigate card. 
There are no errors in the logs. 
I want  to have high res on the Main page and high res + audio on the Live View pages for each camera.
Can you tell me where to see?
Thanks!
 
Cameras Info: 
Cam-0  3840x2160 H.265/AAC  (Dahua)
Cam-1  2560x1440 H.264/G711-ulaf (Hikvision PTZ, audio transcoded to AAC by go2rts)
Cam-2  1920x1080 H.264/AAC (Hikvision)
Cam-3  2866x1520 H.265/AAC (Dahua)
Cam-4  2866x1520 H.265/AAC (Dahua) 
Cam-5  2866x1520 H.265/AAC (Dahua)  

pic.1 Main Page View 
![image](https://github.com/user-attachments/assets/2f0ff4c9-534e-4f8b-b6ef-0365e1667167)
All H.265 cameras have low (detection) resolution.

pic.2 Live View Page
![image](https://github.com/user-attachments/assets/46de7339-a0da-44e3-858e-f1d5466da72d)
on Live View - low res and no audio :(

pic.3  History Page 
![image](https://github.com/user-attachments/assets/4f018c0a-eee6-49a1-819b-e289600f2c60)
on History Page all looks perfect :-)

### Version

0.14.1

### Frigate config file

```yaml
############################################################################
#============================== UI ========================================#
############################################################################

ui:
  time_format: 24hour

############################################################################
#============================== MQTT ======================================#
############################################################################

mqtt:
  enabled: true
  host: 192.168.2.43
  port: 1883
  user: xxxxx
  password: xxxxx
  stats_interval: 60

############################################################################
#============================== LOGGER ====================================#
############################################################################

logger:
  default: info
  # Optional: Component specific logger overrides
  #logs:
  #  frigate.object_detection: debug
  #  detector.coral: debug
  #  frigate.mqtt: debug
  #  frigate.event: debug

############################################################################
#====================== In-feed TIMESTAMP configuration ===================#
############################################################################
timestamp_style:
  position: bl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow #solid #shadow

############################################################################
#============================= VARIABLES ==================================#
############################################################################

environment_vars:
  LIBVA_DRIVER_NAME: iHD

############################################################################
#============================= BIRDSEYE ===================================#
############################################################################

birdseye:
  enabled: false
  mode: continuous
  layout:
    scaling_factor: 2.0

############################################################################
#================================= GO2RTC =================================#
############################################################################

go2rtc:

  streams:
    #---------- Recording -------------------------------------------------#
    Cam-0-s:
      - rtsp://x:x@192.168.2.51:554/cam/realmonitor?channel=1&subtype=0
    Cam-1-s:
      - rtsp://x:x@192.168.2.52/onvif/device_service
      - ffmpeg:Cam-1-s#audio=aac
    Cam-2-s:
      - rtsp://x:x@192.168.2.48/Streaming/Channels/101
    Cam-3-s:
      - rtsp://x:x@192.168.2.47:554/cam/realmonitor?channel=1&subtype=0
    Cam-4-s:
      - rtsp://x:x@192.168.2.35:554/cam/realmonitor?channel=1&subtype=0
    Cam-5-s:
      - rtsp://x:x@192.168.2.49:554/cam/realmonitor?channel=1&subtype=0
    #---------- Detecting -------------------------------------------------#
#    Cam-0-d:
#      - rtsp://x:x@192.168.2.51:554/cam/realmonitor?channel=1&subtype=1
#    Cam-1-d:
#      - rtsp://x:x@192.168.2.52/Streaming/Channels/103
#    Cam-2-d:
#      - rtsp://x:x@192.168.2.48/Streaming/Channels/102
#    Cam-3-d:
#      - rtsp://x:x@192.168.2.47:554/cam/realmonitor?channel=1&subtype=1
#    Cam-4-d:
#      - rtsp://x:x@192.168.2.35:554/cam/realmonitor?channel=1&subtype=1
#    Cam-5-d:
#      - rtsp://x:x@192.168.2.49:554/cam/realmonitor?channel=1&subtype=1


############################################################################
#============================== GLOBAL FFMPEG =============================#
############################################################################

ffmpeg:
#  input_args:
#    - -avoid_negative_ts
#    - make_zero
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  # hwaccel_args: preset-vaapi

############################################################################
#========================= GLOBAL SPANSHOTS ===============================#
############################################################################

snapshots:
  enabled: true    
  bounding_box: true
  clean_copy: true
  timestamp: true
  crop: false
  # height: 350
  retain:
    default: 10
    objects:
      person: 15  
  quality: 80

############################################################################
#============================ GLOBAL RECORD ===============================#
############################################################################

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      mode: active_objects
      default: 30

############################################################################
#============================== DETECTORS =================================#
############################################################################

detectors:
#  coral:
#    type: edgetpu
#    device: usb
  coral_pci:
    type: edgetpu
    device: pci

############################################################################
#============================== REWIEV ====================================#
############################################################################

review:
  alerts:
    labels:
      - person
      - cat
      - car
      - squirrel


############################################################################
#                                                                          #
#============================== CAMERAS ===================================#
#                                                                          #
############################################################################

cameras:

############################################################################
#============================== CAM-0 Main view from Entrance =============#
############################################################################

  Cam-0:
#__________________________________________________________________________#
#------------------  Web Interface ----------------------------------------#
    webui_url: http://192.168.2.51/
#__________________________________________________________________________#
#------------------ Cam-0 FFMPEG configuration ----------------------------#
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam-0-s
          roles:
            - record
        - path: rtsp://x:x@192.168.2.51:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy

#__________________________________________________________________________#
#------------------ Cam-0 MOTION configuration ----------------------------#
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: true
      mask: 0.314,0.192,0.537,0.158,1,0.286,1,0,0.391,0,0,0,0,0.2
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5

#__________________________________________________________________________#
#------------------ Cam-0 LIVE View configuration -------------------------#   
    live:
      stream_name: Cam-0-s
###########################################################################


############################################################################
#============================== CAM-1 MAIN CAMERA =========================#
############################################################################

  Cam-1:
#__________________________________________________________________________#
#------------------  Web Interface ----------------------------------------#
    webui_url: http://192.168.2.52/
#__________________________________________________________________________#
#------------------ Cam-1  ONVIF configuration ----------------------------#
    onvif:
      host: 192.168.2.52
      port: 80
      user: x
      password: x
      autotracking:
        enabled: false
        calibrate_on_startup: false
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
          - cat
          - car
        return_preset: home
        timeout: 10
        #movement_weights: []
#__________________________________________________________________________#
#------------------ Cam-1 FFMPEG configuration ----------------------------#
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.2.52/Streaming/Channels/103
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Cam-1-s
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
#__________________________________________________________________________#
#------------------ Cam-1  OBJECTS configuration --------------------------#
    objects:
      track:
        - person
        - cat
        - car
#__________________________________________________________________________#
#------------------ Cam-1  MOTION configuration ---------------------------#
    motion:
      threshold: 30  # value between 1- more sensitive and 255 - less.
      contour_area: 20
      delta_alpha: 0.2
      frame_alpha: 0.2
      frame_height: 100
      mask: 1,0,1,0.146,0.617,0.146,0.361,0.131,0.325,0.136,0.196,0.161,0,0.211,0,0
      improve_contrast: 'true'

#__________________________________________________________________________#
#------------------ Cam-1  DETECT configuration ---------------------------#
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

#__________________________________________________________________________#
#------------------ Cam-1  DETECT configuration ---------------------------#
    record:
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          mode: motion
          default: 15

#__________________________________________________________________________#
#------------------ Cam-1 LIVE View configuration -------------------------#   
    live:
      stream_name: Cam-1-s

############################################################################
#============================== CAM-2 GARAGE CAMERA =======================#
############################################################################ 

  Cam-2:
#__________________________________________________________________________#
#------------------  Web Interface ----------------------------------------#
    webui_url: http://192.168.2.48/
#__________________________________________________________________________#
#------------------ Cam-2 FFMPEG configuration ----------------------------#
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam-2-s
#          input_args: preset-rtsp-restream 
          roles:
            - record
        - path: rtsp://x:x@192.168.2.48/Streaming/Channels/102
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy

#__________________________________________________________________________#
#------------------ Cam-2 OBJECTS configuration ---------------------------#
    objects:
      track:
        - person
      filters:
          mask:
            - 0.563,0.429,0.623,0.42,0.652,0.533,0.623,0.606,0.588,0.602
            - 0.353,0.4,0.42,0.397,0.477,0.987,0.289,0.989

#__________________________________________________________________________#
#------------------ Cam-2 MOTION configuration ----------------------------#

    motion:
      threshold: 20
      contour_area: 40
      mask:
        - 186,409,186,432,27,432,27,409
        - 768,0,768,77,641,73,537,42,262,56,263,97,0,138,0,0

#__________________________________________________________________________#
#------------------ Cam-2 DETECT configuration ----------------------------#
    detect:
      enabled: true
      width: 768
      height: 432
      fps: 5

#__________________________________________________________________________#
#------------------ Cam-2 LIVE View configuration -------------------------#   
    live:
      stream_name: Cam-2-s


############################################################################
#============================== CAM-3 UTILITY ROOM ========================#
############################################################################

  Cam-3:
#__________________________________________________________________________#
#------------------  Web Interface ----------------------------------------#
    webui_url: http://192.168.2.47/
#__________________________________________________________________________#
#------------------ Cam-3 FFMPEG configuration ----------------------------#
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam-3-s
#          input_args: preset-rtsp-restream 
          roles:
            - record
        - path: rtsp://x:x@192.168.2.47:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy

#__________________________________________________________________________#
#------------------ Cam-3 OBJECTS configuration ---------------------------#
    objects:
      track:
        - person

#__________________________________________________________________________#
#------------------ Cam-3 MOTION configuration ----------------------------#
    motion:
      threshold: 25
      contour_area: 50
      mask:
        - 234,26,229,0,0,0,0,31   # timestamp

#__________________________________________________________________________#
#------------------ Cam-3 DETECT configuration ----------------------------#
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5

#__________________________________________________________________________#
#------------------ Cam-3 LIVE View configuration -------------------------#   
    live:
      stream_name: Cam-3-s


############################################################################
#============================== CAM-4 WORKSHOP ============================#
############################################################################

  Cam-4: # <------  Camera 4  Workshop 
#__________________________________________________________________________#
#------------------  Web Interface ----------------------------------------#
    webui_url: http://192.168.2.35/
#__________________________________________________________________________#
#------------------ Cam-4 FFMPEG configuration ----------------------------#
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam-4-s
          roles:
            - record
        - path: rtsp://x:x@192.168.2.35:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
#__________________________________________________________________________#
#------------------ Cam-4 OBJECTS configuration ---------------------------#
    objects:
      track:
        - person
        - cat
#__________________________________________________________________________#
#------------------ Cam-4 MOTION configuration ----------------------------#
    motion:
      threshold: 25
      contour_area: 30
      mask:
        - 704,38,704,0,0,0,0,38

##__________________________________________________________________________#
#------------------ Cam-4 DETECT configuration -----------------------------#     
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5

#__________________________________________________________________________#
#------------------ Cam-4 LIVE View configuration -------------------------#   
    live:
      stream_name: Cam-4-s


############################################################################
#============================== CAM-5 STORAGE =============================#
############################################################################

  Cam-5:
#__________________________________________________________________________#
#------------------  Web Interface ----------------------------------------#
    webui_url: http://192.168.2.49/
#__________________________________________________________________________#
#------------------ Cam-5 FFMPEG configuration ----------------------------#
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam-5-s
#          input_args: preset-rtsp-restream 
          roles:
            - record
        - path: rtsp://x:x@192.168.2.49:554/cam/realmonitor?channel=1&subtype=1 
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy

#__________________________________________________________________________#
#------------------ Cam-5 OBJECTS configuration ---------------------------#
    objects:
      track:
        - person
        - cat
#__________________________________________________________________________#
#------------------ Cam-5 MOTION configuration ----------------------------#
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: true
      mask:
        - 199,189,372,132,704,363,704,0,275,0,0,0,0,134,0,269
#__________________________________________________________________________#
#------------------ Cam-5 DETECT configuration ----------------------------#
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5

#__________________________________________________________________________#
#------------------ Cam-5 LIVE View configuration -------------------------#   
    live:
      stream_name: Cam-5-s

###########################################################################
###########################################################################
#                      END OF CONFIG


version: 0.14
```

### Relevant Frigate log output

```shell
2024-12-24 09:34:04.668498420  [INFO] Preparing Frigate...
2024-12-24 09:34:04.687241757  [INFO] Starting Frigate...
2024-12-24 09:34:06.249294059  [2024-12-24 12:34:06] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-12-24 09:34:06.249476582  [2024-12-24 12:34:06] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-12-24 09:34:06.249592034  [2024-12-24 12:34:06] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-12-24 09:34:06.317265827  [2024-12-24 12:34:06] frigate.util.config            INFO    : frigate config does not need migration...
2024-12-24 09:34:06.384470131  [2024-12-24 12:34:06] peewee_migrate.logs            INFO    : Starting migrations
2024-12-24 09:34:06.384817677  [2024-12-24 12:34:06] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-12-24 09:34:06.605285997  [2024-12-24 12:34:06] frigate.app                    INFO    : Recording process started: 350
2024-12-24 09:34:06.610599491  [2024-12-24 12:34:06] frigate.app                    INFO    : Recording process started: 354
2024-12-24 09:34:06.614370543  [2024-12-24 12:34:06] frigate.app                    INFO    : go2rtc process pid: 98
2024-12-24 09:34:06.642534205  [2024-12-24 12:34:06] detector.coral_pci             INFO    : Starting detection process: 379
2024-12-24 09:34:06.645632675  [2024-12-24 12:34:06] frigate.app                    INFO    : Output process started: 381
2024-12-24 09:34:06.662462734  [2024-12-24 12:34:06] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-12-24 09:34:06.675447992  [2024-12-24 12:34:06] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-12-24 09:34:06.693968315  [2024-12-24 12:34:06] frigate.app                    INFO    : Camera processor started for Cam-0: 408
2024-12-24 09:34:06.693972063  [2024-12-24 12:34:06] frigate.app                    INFO    : Camera processor started for Cam-1: 412
2024-12-24 09:34:06.700072621  [2024-12-24 12:34:06] frigate.app                    INFO    : Camera processor started for Cam-2: 419
2024-12-24 09:34:06.705300624  [2024-12-24 12:34:06] frigate.app                    INFO    : Camera processor started for Cam-3: 425
2024-12-24 09:34:06.710644789  [2024-12-24 12:34:06] frigate.app                    INFO    : Camera processor started for Cam-4: 429
2024-12-24 09:34:06.725877570  [2024-12-24 12:34:06] frigate.app                    INFO    : Camera processor started for Cam-5: 441
2024-12-24 09:34:06.730409162  [2024-12-24 12:34:06] frigate.app                    INFO    : Capture process started for Cam-0: 451
2024-12-24 09:34:06.732816626  [2024-12-24 12:34:06] frigate.app                    INFO    : Capture process started for Cam-1: 459
2024-12-24 09:34:06.756762690  [2024-12-24 12:34:06] frigate.app                    INFO    : Capture process started for Cam-2: 463
2024-12-24 09:34:06.776314925  [2024-12-24 12:34:06] frigate.app                    INFO    : Capture process started for Cam-3: 470
2024-12-24 09:34:06.776318797  [2024-12-24 12:34:06] frigate.app                    INFO    : Capture process started for Cam-4: 477
2024-12-24 09:34:06.778520291  [2024-12-24 12:34:06] frigate.app                    INFO    : Capture process started for Cam-5: 484
```

### Relevant go2rtc log output

```shell
2024-12-24 09:34:04.671346699  [INFO] Preparing new go2rtc config...
2024-12-24 09:34:04.718850034  [INFO] Got IP address from supervisor: 192.168.2.43
2024-12-24 09:34:04.752061630  [INFO] Got WebRTC port from supervisor: 8555
2024-12-24 09:34:05.179146822  [INFO] Starting go2rtc...
2024-12-24 09:34:05.286082623  12:34:05.284 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-12-24 09:34:05.286086735  12:34:05.284 INF config path=/dev/shm/go2rtc.yaml
2024-12-24 09:34:05.286088409  12:34:05.285 INF [rtsp] listen addr=:8554
2024-12-24 09:34:05.286090235  12:34:05.285 INF [webrtc] listen addr=:8555/tcp
2024-12-24 09:34:05.286642395  12:34:05.286 INF [api] listen addr=:1984
2024-12-24 09:34:14.665892285  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

**Comment by hawkeye217** [comment]
See the camera settings recommendations in the docs: https://docs.frigate.video/configuration/live#camera-settings-recommendations

What browser are you using?

**Reply by Al-Dek** [reply]
Chrome Version 131.0.6778.205 (Official Build) (64-bit)
I saw these recommendations.
And I have all streams working perfect in any case (Frigate recordings, go2rtc web, HA Frigate card, any browser) except Live View page in HA Frigate. :(

**Reply by hawkeye217** [reply]
Recordings use a different technology and player than Live view, so just because recordings work does not guarantee that Live view will work.

When you view the stream in the go2rtc dashboard, what does it say in the top right hand corner of the stream? What streaming technology is it using?

And in the Frigate card, are you using the go2rtc provider? If so, what streaming technology do you have selected?

Frigate's live view uses MSE as its first streaming technology. You don't have WebRTC configured with Frigate (see the [docs](https://docs.frigate.video/configuration/live/#webrtc-extra-configuration)), so since MSE is not loading correctly with your browser, it falls back to jsmpeg.

**Reply by Al-Dek** [reply]
I set up for all cameras live setting "live:" as mentioned in doc, like: 
```
live:
      stream_name: Cam-0-s  
```
 but it didn't help at all... no any changes...

**Reply by hawkeye217** [reply]
It'd be great to see a screenshot of the browser dev tools network pane when you open Live view for a camera.

**Comment by Al-Dek** [comment]
go2rtc web 
![image](https://github.com/user-attachments/assets/07b42a76-765b-446c-ab84-1db0cfd5b255)

**Reply by Al-Dek** [reply]
go2rtc config:
```
api:
  origin: '*'
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  Cam-0-s:
  - rtsp://192.168.2.51:554/cam/realmonitor?channel=1&subtype=0
  Cam-1-s:
  - rtsp://192.168.2.52/onvif/device_service
  - ffmpeg:Cam-1-s#audio=aac
  Cam-2-s:
  - rtsp://192.168.2.48/Streaming/Channels/101
  Cam-3-s:
  - rtsp://192.168.2.47:554/cam/realmonitor?channel=1&subtype=0
  Cam-4-s:
  - rtsp://192.168.2.35:554/cam/realmonitor?channel=1&subtype=0
  Cam-5-s:
  - rtsp://192.168.2.49:554/cam/realmonitor?channel=1&subtype=0
webrtc:
  candidates:
  - 192.168.2.43:8555
  - stun:8555
```
