### DISCUSSION TITLE
[Config Support]: pre_capture post_capture seem to not work?

### DISCUSSION THREAD

**Discussion by StickySide** [blakeblackshear/frigate#15673] [Config Support] [answered]
### Describe the problem you are having

Every event seems to begin recording at the moment an object is detected and ends the moment it leaves the cameras view, despite setting pre_capture and post_capture to 15. Maybe I dont understand how the pre/post recordings work!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.30
  port: 1883
  topic_prefix: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

##### Logging

logger:
  default: info
  logs:
    frigate.detectors: debug

##### Video

ffmpeg:
  hwaccel_args: preset-nvidia-h264

##### Recording

record:
  # sync_recordings: true
  enabled: true
  retain:
    days: 3   # <----- "3" for reduced settings, "0" for events only
    mode: motion # <----- "motion" for reduced settings, "all" for events only preset
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: motion

##### Detection

detectors:
  tensorrt:
    type: tensorrt
    device: 0

audio:
  enabled: false
  min_volume: 1000 # <----- Low sensitivity

##### Snapshots

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10

##### birdseye
birdseye:
  enabled: true
  mode: motion

##### Model

model:
  # path: /config/model_cache/tensorrt/yolov4-tiny-416.trt # <----- Tiny Model
  path: /config/model_cache/tensorrt/yolov4-416.trt # <----- Full model 
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
  labelmap:
    15: cat # <----- was incorrectly mapped as "15: bird" but 15 is cat
    16: dog # <----- was incorrectly mapped as "16: cat" but 16 is dog

##### Objects

objects:
  track:
    - person
    - car
    - cat
    - dog
#  filters:
#    cat:
#      min_score: 0.6 #
#    dog:
#      min_score: 0.6


###### Review Settings (Global) 

review:
  alerts:
    labels:
      - person
      - car
  # detections:
  #   labels:
  #     - person
  #     - car
  #     - cat
  #     - dog

###### Web streams

go2rtc:
  streams:
    Livingroom:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main
    Livingroom_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub
    Kitchen:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
    Kitchen_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub
    Driveway:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_main
    Driveway_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_sub
    Porch:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_main
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_main
    Porch_sub:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_sub
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_sub


###### Cameras

cameras:

## LIVINGROOM ##
  Livingroom:
    enabled: true

    record: # <----- Recording setting
      enabled: false

    detect:
      enabled: false
      width: 1280
      height: 720

    audio:
      enabled: false

    birdseye:
      order: 3

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_sub # <----- The stream you want to use for detection.. add one for recording later
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.10/h264Preview_01_main # <----- Recording stream
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy # <----- audio on recordings

    onvif:
      host: 192.168.80.10
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    review:
      detections:
        labels:
          - person
          - car
          - cat
          - dog
      alerts:
        labels: []

    motion:
      mask: 0.01,0.075,0.315,0.079,0.316,0.01,0.012,0.01

## KITCHEN ##
  Kitchen:
    enabled: true

    record:
      enabled: false

    detect:
      enabled: false
      width: 1280
      height: 720

    review:
      detections:
        labels:
          - person
          - cat
          - dog
          - car
      alerts:
        labels: []

    audio:
      enabled: false

    birdseye:
      order: 4

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_sub     # <----- The stream you want to use for detection.. add one for recording later
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.11/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy # <----- audio on recordings

    onvif:
      host: 192.168.80.11
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    motion:
      mask: 0.01,0.07,0.308,0.075,0.311,0.019,0.01,0.014

## DRIVEWAY ##

  Driveway:
    enabled: true

    # record:
    #   enabled: true
    #   retain:
    #     days: 3   # <----- "3" for reduced settings, "0" for events only
    #     mode: motion # <----- "motion" for reduced settings, "all" for events only preset
    #   events:
    #     pre_capture: 15
    #     post_capture: 15
    #     retain:
    #       default: 30
    #       mode: motion


    detect:
      enabled: true
      width: 1280
      height: 720

    review:
      alerts:
        required_zones: Driveway_zone

    birdseye:
      order: 2

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.12/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy

    # ffmpeg:  ## TESTING CONFIG ##
    #   inputs:
    #     - path: /media/frigate/testing/nodetect2.mp4 # TESTING
    #       input_args: -re -stream_loop -1 -fflags +genpts # TESTING
    #       roles:
    #         - detect
    #         - audio
    #         - record
    #   # output_args:
    #   #   record: preset-record-generic-audio-copy # <----- audio on recordings

    onvif:
      host: 192.168.80.12
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    zones:
      Street:
        coordinates: 0,0.51,0,0.865,0.17,0.677,0.438,0.346,0.778,0.087,0.727,0.02,0.29,0.286
        loitering_time: 0
        inertia: 3
      Driveway_zone:
        coordinates: 0.914,0.261,0.613,0.228,0.444,0.365,0.068,0.85,0.162,1,0.995,1,1,0.383
        loitering_time: 0
        inertia: 3

    motion:
      mask:
        - 0,0.207,0.305,0.064,0.32,0,0,0
        - 0,0.786,0.066,0.652,0.067,0.368,0,0.254
        - 1,0.268,0.754,0.164,0.583,0.088,0.488,0.036,0.457,0,1,0
      threshold: 60
      contour_area: 30
      improve_contrast: 'true'

## PORCH ##

  Porch:
    enabled: true

    # record:
    #   enabled: true

    detect:
      enabled: true
      width: 1280
      height: 720

    review:
      alerts:
        required_zones:
          - Porch_zone
          - Front_Yard

    birdseye:
      order: 1

    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_sub # <----- RTSP Stream... stutters sometimes? Specific to RLC-1240A
            # rtmp://192.168.80.13/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=c4nBudpQGxwyjiuJEMCc #<----- RTMP stream is smooth
          input_args: preset-rtsp-restream
          # input_args: preset-rtmp-generic #<------ RTSP stream           
          roles:
            - detect
            # - audio
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@192.168.80.13/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy

    # ffmpeg:  ## TESTING CONFIG ##
    #   hwaccel_args: preset-nvidia-h264
    #   inputs:
    #     - path: /media/frigate/testing/car.mp4 # TESTING
    #       input_args: -re -stream_loop -1 -fflags +genpts # TESTING
    #       roles:
    #         - detect
    #         - audio
    #         - record
    #   output_args:
    #     record: preset-record-generic-audio-copy # <----- audio on recordings

    onvif:
      host: 192.168.80.13
      port: 8000
      user: '{FRIGATE_REOLINK_USER}'
      password: '{FRIGATE_REOLINK_PASSWORD}'

    motion:
      mask:
        - 0.005,0.078,0.428,0.083,0.43,0.011,0.006,0.01
        - 0.897,0.587,0.86,0.452,0.85,0.303,0.86,0.15,1,0.267,1,0.722,0.972,0.697
      threshold: 30
      contour_area: 20
      improve_contrast: 'true'
    zones:
      Street:
        coordinates: 
          0.998,0.755,0.805,0.5,0.542,0.237,0.343,0.105,0.342,0.005,0.47,0.009,0.794,0.17,0.955,0.346,0.999,0.445
        loitering_time: 0
        inertia: 3

      Porch_zone:
        coordinates: 
          0.334,0.347,0.322,0.331,0.31,0.339,0.288,0.313,0.16,0.388,0.253,0.999,0.828,0.998,0.338,0.388
        loitering_time: 0
        objects:
          - cat
          - dog
          - person

      Front_Yard:
        coordinates: 0.509,0.266,0.78,0.56,0.901,0.722,0.876,0.815,0.345,0.243,0.455,0.206
        loitering_time: 0
        objects:
          - cat
          - dog
          - person

##### Groups

camera_groups:
  Indoors:
    order: 2
    icon: LuCat
    cameras:
      - Kitchen
      - Livingroom

  Outdoors:
    order: 1
    icon: LuTrees
    cameras:
      - Driveway
      - Porch
  Birdseye:
    order: 3
    icon: LuEye
    cameras: birdseye
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
Unraid docker manager
```

### Object Detector

TensorRT

**Comment by NickM-27** [comment]
Where are you seeing this / what behavior specifically makes you think it is not working?

**Reply by StickySide** [reply]
When I go to review events, the recording begins when the object is in full view, and ends a moment after they leave the frame. No recorded video exists before or after.

For example if I walk out of my front door, the recording begins as im standing on the porch so I don’t see me opening the door or walking out.

**Reply by StickySide** [reply]
I might be misunderstanding how frigate is working with this config.. if motion is set to record and be retained for 3 days, and then I have events with motion set to be retained for 30 days... if theres no motion in the 15 seconds before frigate recognizes an object, will it not record the 15 seconds? Or does it always have that buffer available regardless of how recording is set?

**Reply by NickM-27** [reply]
> if theres no motion in the 15 seconds before frigate recognizes an object, will it not record the 15 seconds?

Correct it won't record if there is no motion and your recording retention mode is set to motion

**Reply by StickySide** [reply]
Ahh, ok thank you!
So if i want the 15 seconds before/after an event to be recorded *even if theres no motion detected*, would I need only event recording set to "all"? Or both event and recording set to "all"? IE:

Option 1:
```yaml
record:
  enabled: true
  retain:
    days: 3 
    mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: all
```      
 OR
Option 2:
```yaml
record:
  enabled: true
  retain:
    days: 3 
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: all

**Reply by NickM-27** [reply]
The first one

**Reply by StickySide** [reply]
Hey Nick, really appreciate your help with this!
I configured the recording with event mode: all, but the recording behaviour seems the same. The events begin recording the moment the object is tracked (sometimes even after they are in full view of the camera). The recordings seem to end at most 2-3 seconds after the object is off screen, despite the pre/post_capture of 15 seconds being set.

**Reply by NickM-27** [reply]
to be clear, the UI will always open to the recording right when it starts. If pre / post capture is working then you can seek before or after this.

**Reply by StickySide** [reply]
I thought this might be the case, but I’ve checked several events and cannot scrub before the object appears, as no recording exists. I even tried exporting events and selecting a longer time frame but the recording is still short. I’ll try a longer pre capture but as it is now it certainly doesn’t seem like 15 seconds pre event

**Reply by StickySide** [reply]
Per this thread I changed my record settings to:
```yaml
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 20
    post_capture: 15
    retain:
      default: 30
      mode: all
```
I let this run a couple days and collected some events. Unfortunately most of them seem to only record the moment the objects come into view, not the 20 seconds prior. Even when selecting an event and scrubbing earlier most of the time there is no recording present. This is causing some events to be cut at the start, losing important video. The post_capture seems to work a little more consistently (about 1/2 the time), but it also seems to cut recordings off the moment the object is off camera many times. The only exception to this is if there is other motion (a tree or flag blowing) before or after the event, then the moments prior to the event is recorded. 

Do I need to set my recording retention (not just events) to "all"? Other threads here seem to indicate it should work as configured above. The desired result is to save all motion for 3 days, and events + 20 seconds prior and 15 seconds after.

The above is set globally and I have no recording settings in individual cameras set.. Do I need to set them individually?
Thanks for your time!
