### DISCUSSION TITLE
why?

### DISCUSSION THREAD

**Discussion by crazych1** [blakeblackshear/frigate#15671] [Ask A Question]
```
mqtt:
  enabled: false

go2rtc:
  streams:
    garage_on_home:
      - rtsp://admin:admin@172.16.1.206:554/cam/realmonitor?channel=1&subtype=0
    garage_on_home1:
      - rtsp://admin:admin@172.16.1.207:554/cam/realmonitor?channel=1&subtype=0

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3
  cpu5:
    type: cpu
    num_threads: 3
  cpu6:
    type: cpu
    num_threads: 3
  cpu7:
    type: cpu
    num_threads: 3
  cpu8:
    type: cpu
    num_threads: 3

live:
  stream_name: living_room



  garage_on_home1:
    detect:
      width: 1920
      height: 1080
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@172.16.1.207:554/cam/realmonitor?channel=1&subtype=0 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      threshold: 20
      contour_area: 6
      improve_contrast: true
      mask:
        - 0.748,0.042,0.973,0.037,0.976,0.089,0.747,0.1
        - 0.027,0.514,0.034,0.716,0.171,0.645,0.282,0.585,0.319,0.425,0.709,0.27,0.689,0,0,0.005
    zones:
      hh:
        coordinates: 0.705,0.276,0.266,0.414,0.042,0.533,0.082,0.996,0.997,0.996,0.998,0.284
        loitering_time: 1
        objects:
          - cat
          - person
          - dog
    objects:
      track:
        - person
        - car
        - dog
        - cat
      mask: 
        0.027,0.725,0.242,0.704,0.486,1,1,1,1,0.285,0.917,0.283,0.911,0.466,0.711,0.422,0.7,0.282,0.321,0.43,0.287,0.584,0.221,0.625
    review:
      alerts:
        required_zones: hh
      detections:
        required_zones: hh
```

I have this configuration. I have a desire to reduce the load on the processor that is engaged in detection. In this regard, I wanted to reduce the detection zone and set it in the config 
  garage_on_home1:
    detect:
      width: 800
      height: 600
      fps: 5

after that, I get a real-time image size of 800 by 600 pixels.
I don't really understand why the detection parameter affects the size of the camera display in live mode.
