### DISCUSSION TITLE
[Bug]: Submit to Frigate+ shows black frame

### DISCUSSION THREAD

**Discussion by tve** [blakeblackshear/frigate#15675] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When clicking on "submit to frigate+" I sometimes get a black frame:
![image](https://github.com/user-attachments/assets/9952c628-1b4d-4c91-b033-c4dfd8036e40)
Hitting space two times very rapidly to advance to the next frame generally fixes it.

### Steps to reproduce

1. View a detection clip
2. Stop at some frame
3. Click the frigate+ button
4. observe black frame (this is intermittent!)

### Version

0.15.0 beta 4 - 0.15.0-87e7b62

### In which browser(s) are you experiencing the issue with?

Floorp (based on firefox)

### Frigate config file

```yaml
mqtt:
  host: core.voneicken.com
  user: frigate
  password: 

timestamp_style:
  format: '%Y-%m-%d %H:%M:%S'

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  detections:
    retain:
      days: 30
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 200

birdseye:
  enabled: true
  mode: motion

environment_vars:
  LIBVA_DRIVER_NAME: i965 # required for vaapi to find the correct driver

ffmpeg:
  global_args: -hide_banner # -loglevel debug
  hwaccel_args: preset-vaapi
  # hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
  #   yuv420p
  #output_args:
  #  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  #cpu1:
    #type: cpu

go2rtc:
  streams:
    studio:
      - ffmpeg:http://esp32-cam2.voneicken.com:81#video=h264#hardware
    gate:
      - rtsp://frigate:@192.168.11.88:554/cam/realmonitor?channel=1&subtype=0
    patio:
      - rtsp://frigate:@192.168.11.91:554/cam/realmonitor?channel=1&subtype=0
    overview:
      - rtsp://frigate:@192.168.11.93:554/cam/realmonitor?channel=1&subtype=0

model:
  path: plus://db5e39d2f6b05cdfb7fefee0a328eaa2
objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    cow:
      min_score: .65
      threshold: .85
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

telemetry:
  stats:
    network_bandwidth: true

cameras:

  # Dahua IPC-HFW5442T-ASE-NI
  gate:
    ui:
      order: 0
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate
          roles: [record]
        - path: 
            rtsp://frigate:@192.168.11.88:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    zones:
      inside:
        coordinates: 0.654,1,0.668,0.673,0.373,0.683,0,0.481,0,1
        inertia: 2
        loitering_time: 0
      outside:
        coordinates: 0.374,0.184,0.713,0.2,0.64,0.559,0.346,0.587
        inertia: 2
        loitering_time: 0
    record:
      retain:
        days: 5
        mode: motion
    objects:
      track: [person, car, dog, cat, sheep, bicycle, motorcycle, truck, bus, horse,
        sheep, bear, face, license_plate, amazon, usps, fedex, ups, dhl, deer, raccoon,
        fox, squirrel, cow, goat, rabbit, waste_bin, package]
    review:
      alerts:
        required_zones: inside
    motion:
      mask:
        - 0.025,0.011,0.427,0.011,0.427,0.065,0.026,0.065
        - 0.687,0.53,0.66,0.997,0.737,0.992,0.751,0.524
    detect:
      annotation_offset: -1400
  overview:
    webui_url: http://frigate:@192.168.11.93/
    ui:
      order: 0
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/overview
          roles: [record]
        - path: 
            rtsp://frigate:view2frigate!@192.168.11.93:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    record:
      retain:
        days: 5
        mode: motion
    objects:
      track: [person, car, dog, cat, sheep, bicycle, motorcycle, truck, bus, horse,
        sheep, bear, amazon, usps, fedex, ups, dhl, deer, raccoon, fox, squirrel,
        cow, goat, rabbit]
    detect:
      annotation_offset: -1400
    motion:
      mask: 0.01,0.005,0.43,0.006,0.427,0.059,0.012,0.059
    onvif:
      host: 192.168.11.93
      port: 80
      user: frigate
      password: 
      autotracking:
        enabled: true
        calibrate_on_startup: false
        required_zones:
          - full
        zooming: relative
        track: [person, car, dog, cat, sheep, bicycle, motorcycle, truck, bus, horse,
          sheep, bear, amazon, usps, fedex, ups, dhl, deer, raccoon, fox, cow, goat]
        return_preset: Overview
        movement_weights: 0.04, 1.0, 1.0367317199707031, 1.3062768443938224, 0.3844547048691781
    zones:
      full:
        coordinates: 0,0.062,1,0.065,1,1,0,1
        loitering_time: 0
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          roles: [record]
        - path: 
            rtsp://frigate:@192.168.11.91:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    record:
      retain:
        days: 2
    objects:
      track: [person, car, dog, cat, sheep, bicycle, motorcycle, truck, bus, horse,
        sheep, bear, face, license_plate, amazon, usps, fedex, ups, dhl, deer, raccoon,
        fox, squirrel, cow, goat, rabbit, waste_bin, package]
    motion:
      mask:
        - 0.02,0.054,0.399,0.054,0.399,0,0.021,0
        - 0.028,0.917,0.196,0.917,0.195,0.967,0.027,0.967
    zones:
      tracking_start:
        coordinates: 0.344,0.121,0.224,0.493,0.562,0.863,0.871,0.903,0.892,0.565,0.77,0.4,0.757,0.163
        loitering_time: 1
        inertia: 3
    onvif:
      host: 192.168.11.91
      port: 80
      user: frigate
      password: 
      autotracking:
        enabled: true
        calibrate_on_startup: false
        zooming: relative
        required_zones:
          - tracking_start
        track:
          - person
          - dog
          - cat
          - sheep
        return_preset: Driveway
        movement_weights: 0.33, 1.0, 1.0782661437988281, 1.2704954603666898, 0.3403729777182304
    review:
      alerts:
        required_zones: tracking_start
    detect:
      annotation_offset: -1800
  old-gate:
    ui:
      order: 1
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://phycam.voneicken.com/live/1/h264.sdp
          roles: [detect, record]
      #input_args: [ -flags, low_delay, -strict, experimental ]
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -use_wallclock_as_timestamps
        - '1'
        - -timeout
        - '5000000'
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
    detect:
      enabled: false
      width: 768
      height: 432
      fps: 5
    timestamp_style:
      position: bl
    motion:
      mask:
        - 768,0,712,0,620,205,605,432,768,432
    record:
      retain:
        days: 2
    zones:
      inside:
        coordinates: 570,432,615,292,372,247,0,292,0,432
      outside:
        coordinates: 388,44,663,93,636,266,333,221
    objects:
      track: [person, car, dog, cat, sheep, bicycle, motorcycle, truck, bus]

  # rpi-cam2 -- rPi3a+imx462-based camera 1920x1080
  birdbath:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://rpi-cam2.voneicken.com:8554/cam5fps
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5
    #mqtt:
    #  event_history: True
    timestamp_style:
      position: bl
    motion:
      #threshold: 20  # default is 25, pixel value delta to detect motion
      #delta_alpha: 0.15  # default is 0.2
      #frame_alpha: 0.15  # default is 0.2
      contour_area: 50  # default is 100, misses hummingbirds
      mask:
        - 1468,0,1920,0,1920,198,1468,172
    record:
      retain:
        days: 3
    objects:
      track: [bird, cat, dog, bear, sheep, deer, raccoon, fox, squirrel, goat, rabbit]

  studio:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/studio
          roles: [detect, record]
    objects:
      track: [person, bird, cat, dog, bear, sheep, deer, raccoon, fox, squirrel, goat,
        rabbit, horse]
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
ExecStart=/usr/bin/docker run \
  --name %n \
  --restart=unless-stopped \
  -e PLUS_API_KEY= \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri:/dev/dri \
  -v /media:/media/frigate \
  -v /home/frigate/config:/config \
  -v /etc/localtime:/etc/localtime:ro \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --shm-size=256m \
  -p 5000:5000 \
  -p 1935:1935 \
  -p 1984:1984 \
  -p 8971:8971 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  --privileged \
  ghcr.io/blakeblackshear/frigate:0.15.0-beta4
```

### Relevant Frigate log output

```shell
There is no log message of any sort when this happens
```

### Relevant go2rtc log output

```shell
There is no log message of any sort when this happens.
```

### Operating system

Debian

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW5442T-ASE-NI

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/921cbc69-9a09-4cb6-886a-a75201e2e4e9)

### Any other information that may be helpful

I'm getting this black frame maybe 10%-20% of the time, not only for this camera (the others are Dahua too). It's annoying when I managed to stop on exactly the right frame that I loose it...

**Comment by hawkeye217** [comment]
I can't reproduce this at all. Can you try another browser like Chrome or Edge and see if have the same behavior there?

**Reply by tve** [reply]
Haven't been able to repro using chrome, I'll use that for a while and see whether it happens. I couldn't easily repro using floorp this morning (had to try dozens of times) but did manage once and the browser console showed no message pertaining to this issue.

**Reply by hawkeye217** [reply]
The code for this is all frontend/browser-based - if a video is loaded, it grabs a frame from it and puts it on a `canvas` in your browser. You can see what Frigate is doing here:

https://github.com/blakeblackshear/frigate/blob/00371546a3c394bf1e4806b67e3d489854aa0b94/web/src/components/player/VideoControls.tsx#L328

If you can reproduce this, it would be good to see a screenshot of the dev tools web inspector open with the `canvas` element selected.

**Reply by tve** [reply]
>if a video is loaded, it grabs a frame from it and puts it on a canvas in your browser

Weird, here's an example of what I see in the video (stopped) after I click the "submit to frigate" button:
<img width="1309" height="744" alt="image" src="https://github.com/user-attachments/assets/5684c4bb-b546-44ee-85a4-535ce9b25e99" />

and here is what I get in the frigate+ image annotation portal:
<img width="1522" height="861" alt="image" src="https://github.com/user-attachments/assets/4874cb63-c7cf-49dd-9566-eb25f7de7475" />

Clearly there is an offset. I'm running 0.16.0-beta3.

**Reply by tve** [reply]
Here is an example of a blank submission frame (0.16.0-beta3, browser firefox based):
<img width="1335" height="813" alt="image" src="https://github.com/user-attachments/assets/132012e8-35d5-4bca-a735-cc6e8fed7d01" />

and here is what the console says when I click the frigate+ icon:
<img width="1538" height="566" alt="image" src="https://github.com/user-attachments/assets/60592f26-0586-4e0d-b254-17268a37c2cc" />

it works fine with chromium, however, as above with the UPS truck, this image in the stopped video:
<img width="1425" height="812" alt="image" src="https://github.com/user-attachments/assets/c50ba75c-e55b-4c3e-b1a6-74316c3a982b" />
ends up like this in frigate+:
<img width="1532" height="853" alt="image" src="https://github.com/user-attachments/assets/5bcc5237-5a6d-481a-aa46-c23c18d229f2" />

In the config for this camera I have:
```
    detect:
      annotation_offset: -1400
```
which is pretty accurate. Could it be that this offset is applied incorrectly in this use-case?

**Reply by hawkeye217** [reply]
> Could it be that this offset is applied incorrectly in this use-case?

No. There is nothing involved with the backend here. All Frigate is doing is using a `canvas` HTML element to grab the pixels being rendered by the HTML video player.

The only thing I can think of is that the video decoder in your browser is processing frames ahead of what's being displayed. If it works fine with a Chromium-based browser, that would certainly point to the Firefox-based browser's renderer.

Can you share your browser name and version, screen resolution, and the video codec your camera is using?

**Reply by tve** [reply]
The black frame only happens with floorp, the time offset between what I see in the video and what shows up submitted in frigate+ is the same in floorp and chromium.

- Floorp 11.28.0 (64-bit) for Arch Linux
- Chromium Version 138.0.7204.92 (Official Build) Arch Linux (64-bit)
- Both on Wayland with Hyprland compositor
- Since you mention screen resolutions.... I tried chromium on my 2nd display, which is 2560x1440 rotated 90 degrees and 0.9x DPI scaling as well as on my primary display, which is 3840x2160 scaled 1.2x; in both cases the time offset is the same
- Camera is a Dahua IPC-HFW5442T with the following streams:

<img width="1104" height="428" alt="image" src="https://github.com/user-attachments/assets/0224a552-40f7-4346-92b7-ebf9d99f9f11" />

- I'm using go2rtc: `rtsp://frigate:gate2frigate!@192.168.0.0:554/cam/realmonitor?channel=1&subtype=0` and the ffmpeg config for this camera is:
```
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate
          roles: [record]
        - path: 
            rtsp://frigate:gate2frigate!@192.168.0.0:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
```
