### DISCUSSION TITLE
[Detector Support]: nvidia GPU vs. Google Coral

### DISCUSSION THREAD

**Discussion by sebastian-tischer** [blakeblackshear/frigate#15688] [Detector Support] [answered]
### Describe the problem you are having

Hi team,

as a big fan of Frigate and Frigate+ subscriber I truely love it :)

Frigate runs on my HPE Microserver with Intel Xeon 2,8 Ghz CPU + 32 GB RAM + NVIDIA T 400 4GB

Until now, I use Google Coral and just saw, I could use yolonas instead of mobiledet.

My question is, based on the above hardware, is it better to switch from Coral to GPU? :)

Thank you for the amazing product and your support.
Warm regards
Sebastian

### Version

0.15.0-87e7b62

### Frigate config file

```yaml
model:
  path: plus://0830f79ca1f72a7049d5d84c96b5a919

mqtt:
  enabled: true
  host: xxxx
  port: 1883
  user: hass-mqtt
  password: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia

motion:
  threshold: 15
  improve_contrast: true
  contour_area: 15

detect:
  enabled: true
  width: 1280
  height: 720
  fps: 10
  stationary:
    interval: 50
    threshold: 50

birdseye:
  enabled: true
  mode: continuous

record:
  enabled: true
  retain:
    mode: motion
  alerts:
    retain:
      days: 30
    pre_capture: 30
    post_capture: 30
  detections:
    retain:
      days: 30
    pre_capture: 30
    post_capture: 30
snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  crop: false
  retain:
    default: 30
    objects:
      person: 30
      cat: 30
      bicycle: 30
      motorcycle: 30
      car: 30

cameras:

  Klingel:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Klingel
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Klingel-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - bicycle
        - motorcycle
        - car
      filters:
        person:
          min_score: 0.75
          threshold: 0.85
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
        car:
          min_score: 0.80
          threshold: 0.86
          #      min_area: 5000
          #      min_ratio: 1.25
          #      max_ratio: 1.8
          mask:
            - 0.477,0.626,0.784,0.664,0.894,0.624,0.916,0.509,0.477,0.464
            - 0.265,0.668,0.28,0.608,0.255,0.529,0,0.471,0,0.603
        bicycle:
          min_score: 0.75
          threshold: 0.85
        motorcycle:
          min_score: 0.75
          threshold: 0.85
        cat:
          min_score: 0.80
          threshold: 0.90
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    #        dog:
    #          min_score: 0.60
    #          threshold: 0.75
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    review:
      alerts:
        labels:
          - person
          - alarm
          - fire_alarm
          - car_alarm
          - scream
          - crying
          - speech
          - yell
      detections:
        labels:
          - cat
          - car
          - bicycle
          - motorcycle
          - bark
          - meow

  Einfahrt:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Einfahrt
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Einfahrt-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - meow
        - alarm
        - fire_alarm
        - car_alarm
        - scream
        - crying
        - speech
        - yell
    objects:
      track:
        - person
        - cat
        - bicycle
        - motorcycle
        - car
      filters:
        person:
          min_score: 0.75
          threshold: 0.75
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
        car:
          min_score: 0.75
          threshold: 0.75
          #      min_area: 5000
          #      min_ratio: 1.25
          #      max_ratio: 1.8
          mask:
            - 0.076,0.25,0.449,0.166,0.445,0.493,0,0.522,0,0.272
            - 0.008,0.612,0.153,0.642,0.231,0.671,0.847,0.617,1,1,0.003,0.997
            - 0.587,0,0.604,0.223,0.915,0.196,0.92,0.036
        bicycle:
          min_score: 0.75
          threshold: 0.85
        motorcycle:
          min_score: 0.75
          threshold: 0.85
        cat:
          min_score: 0.80
          threshold: 0.85
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    #        dog:
    #          min_score: 0.60
    #          threshold: 0.80
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    review:
      alerts:
        labels:
          - person
          - alarm
          - fire_alarm
          - car_alarm
          - scream
          - crying
          - speech
          - yell
      detections:
        labels:
          - cat
          - car
          - bicycle
          - motorcycle
          - bark
          - meow
  Eingang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Eingang-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - meow
        - alarm
        - fire_alarm
        - car_alarm
        - scream
        - crying
        - speech
        - yell
    objects:
      track:
        - person
        - cat
        - bicycle
        - motorcycle
        - car
      filters:
        person:
          min_score: 0.70
          threshold: 0.75
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
        car:
          min_score: 0.70
          threshold: 0.75
          #      min_area: 5000
          #      min_ratio: 1.25
          #      max_ratio: 1.8
          mask:
            - 0.199,0.059,0.201,0,0.533,0,0.744,0,0.827,0,1,0,1,0.356,1,0.628,0.766,0.494,0.583,0.376,0.431,0.27,0.382,0.165,0.353,0.17
            - 0.34,0.519,0.457,0.095,0.719,0.115,1,0.235,0.98,0.956
        bicycle:
          min_score: 0.70
          threshold: 0.75
        motorcycle:
          min_score: 0.70
          threshold: 0.75
        cat:
          min_score: 0.70
          threshold: 0.80
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    #        dog:
    #          min_score: 0.60
    #          threshold: 0.75
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    review:
      alerts:
        labels:
          - person
          - alarm
          - fire_alarm
          - car_alarm
          - scream
          - crying
          - speech
          - yell
      detections:
        labels:
          - cat
          - car
          - bicycle
          - motorcycle
          - bark
          - meow

  Garten:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - meow
        - alarm
        - fire_alarm
        - car_alarm
        - scream
        - crying
        - speech
        - yell
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.70
          threshold: 0.80
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
        cat:
          min_score: 0.65
          threshold: 0.65
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    #        dog:
    #          min_score: 0.60
    #          threshold: 0.75
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
          mask: 
            0.264,0.691,0.551,0.464,0.674,0.411,0.855,0.478,0.837,0.88,0.797,1,0.17,1,0.175,0.836
    review:
      alerts:
        labels:
          - person
          - alarm
          - fire_alarm
          - car_alarm
          - scream
          - crying
          - speech
          - yell
      detections:
        labels:
          - cat
          - car
          - bicycle
          - motorcycle
          - bark
          - meow

  Haus:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Haus
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Haus-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - meow
        - alarm
        - fire_alarm
        - car_alarm
        - scream
        - crying
        - speech
        - yell
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.70
          threshold: 0.75
          min_area: 2000
          min_ratio: 0
          max_ratio: 0.8
        cat:
          min_score: 0.70
          threshold: 0.70
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    #        dog:
    #          min_score: 0.60
    #          threshold: 0.75
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
          mask: 0.548,0.407,0.665,0.399,0.675,0.522,0.552,0.54,0.541,0.505,0.544,0.465
    review:
      alerts:
        labels:
          - person
          - alarm
          - fire_alarm
          - car_alarm
          - scream
          - crying
          - speech
          - yell
      detections:
        labels:
          - cat
          - car
          - bicycle
          - motorcycle
          - bark
          - meow

  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - meow
        - alarm
        - fire_alarm
        - car_alarm
        - scream
        - crying
        - speech
        - yell
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.80
          threshold: 0.90
          min_area: 5000
          min_ratio: 0
          max_ratio: 0.8
        cat:
          min_score: 0.80
          threshold: 0.90
    #      min_area: 5000
    #      min_ratio: 1.25
    #      max_ratio: 1.9
    review:
      alerts:
        labels:
          - person
          - alarm
          - fire_alarm
          - car_alarm
          - scream
          - crying
          - speech
          - yell
      detections:
        labels:
          - cat
          - car
          - bicycle
          - motorcycle
          - bark
          - meow

go2rtc:
  streams:
    Klingel:
      - ffmpeg:rtsp://xx@xx/mpeg/media.amp#video=copy#audio=copy#audio=opus
    Klingel-Detect:
      - ffmpeg:rtsp://xx@xx/mpeg/media.amp#video=copy#audio=copy#audio=opus
    Einfahrt:
      - ffmpeg:rtsp:/xx@xx/livestream/11#video=copy#audio=copy#audio=opus
    Einfahrt-Detect:
      - ffmpeg:rtsp://xx@xx/livestream/12#video=copy#audio=copy#audio=opus
    Eingang:
      - ffmpeg:rtsp://xx@xx/livestream/11#video=copy#audio=copy#audio=opus
    Eingang-Detect:
      - ffmpeg:rtsp://xx@xx/livestream/12#video=copy#audio=copy#audio=opus
    Haus:
      - ffmpeg:rtsp://xx@xx/livestream/11#video=copy#audio=copy#audio=opus
    Haus-Detect:
      - ffmpeg:rtsp://xx@xx/livestream/12#video=copy#audio=copy#audio=opus
    Garten:
      - ffmpeg:rtsp://xx@xx/livestream/11#video=copy#audio=copy#audio=opus
    Garten-Detect:
      - ffmpeg:rtsp://xx@xx/livestream/12#video=copy#audio=copy#audio=opus
    Garage:
      - ffmpeg:rtsp://xx@xx/livestream/11#video=copy#audio=copy#audio=opus
    Garage-Detect:
      - ffmpeg:rtsp://xx@xx/livestream/12#video=copy#audio=copy#audio=opus

version: 0.15-0
camera_groups:
  Vorderseite:
    order: 1
    icon: LuArrowBigUp
    cameras:
      - Einfahrt
      - Eingang
      - Klingel
  Rückseite:
    order: 2
    icon: LuArrowBigDown
    cameras:
      - Garten
      - Garage
      - Haus
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

-
