### DISCUSSION TITLE
[Config Support]: Motion Detection Continuously Triggering

### DISCUSSION THREAD

**Discussion by tdashmike** [blakeblackshear/frigate#15681] [Config Support] [answered]
### Describe the problem you are having

I'm using deepstack and for one of the cameras it seems to sending images to the detector even though there is no movement. I don't see any red motion detection boxes but green boxes will pop up once in a while. Sometimes there are no green or red boxes but it looks like the car detection IDs are updating. I even tried setting the threshold to "255" and coutour_area to "50".

![Screenshot 2024-12-25 150858](https://github.com/user-attachments/assets/02f9604a-cce6-419f-81b6-d1d0c8a994ec)

![image](https://github.com/user-attachments/assets/7aff9512-eeff-48cc-849b-25e626e142ea)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
motion:
      mask: 0,0,1,0,1,0.479,0.804,0.422,0.598,0.392,0.351,0.379,0.209,0.427,0,0.654
      threshold: 255
      lightning_threshold: 0.5
      contour_area: 50
      improve_contrast: true
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    zones:
      frontyard:
        coordinates: 0,1,1,1,1,0.479,0.804,0.422,0.598,0.392,0.351,0.379,0.209,0.427,0,0.654
        inertia: 3
        loitering_time: 0
    record:
      enabled: true
      retain:
        days: 14
        mode: all
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Other
