### DISCUSSION TITLE
[Support]: Exception in ASGI application

### DISCUSSION THREAD

**Discussion by ptichalouf** [blakeblackshear/frigate#15694] [General Support] [answered]
### Describe the problem you are having

no more camera in GUI 

### Version

BETA 0.15.4

### What browser(s) are you using?

firefox

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.15
  # Optional: port (default: shown below)
  port: 1883
  user: ptichalouf
  password: xxxxxxxxxx
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate

audio:
  enabled: true
  listen:
    - bark
    - scream
    - speech
    - yell

cameras:
  Buanderie: # <------ Name the camera
    detect:
#      width: 1280
#      height: 720
      fps: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Buanderie # <----- Update for your camera
          roles:
            - record
            - audio
            - detect
#        - path: rtsp://127.0.0.1:8554/Buanderie_Sub # <----- Update for your camera
#          roles:
#            - detect
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args: preset-intel-qsv-h264
      # Optional: camera specific input args (default: inherit)
      input_args: preset-rtsp-generic
      # Optional: camera specific output args (default: inherit)
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Buanderie
    onvif:
      host: 192.168.1.20
      port: 2020
      user: ptichalouf
      password: xxxxxxx



  Salon: # <------ Name the camera
    detect:
#      width: 1280
#      height: 720
      fps: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Salon # <----- Update for your camera
          roles:
            - record
            - audio
            - detect
#        - path: rtsp://127.0.0.1:8554/Salon_Sub # <----- Update for your camera
#          roles:
#            - detect
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args: preset-intel-qsv-h264
      # Optional: camera specific input args (default: inherit)
      input_args: preset-rtsp-generic
      # Optional: camera specific output args (default: inherit)
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Salon
    onvif:
      host: 192.168.1.23
      port: 2020
      user: ptichalouf
      password: xxxxxxxxx





  Cuisine: # <------ Name the camera
    detect:
#      width: 1280
#      height: 720
      fps: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1080
    motion:
      mask:
        - 1073,381,1071,514,886,534,884,400
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cuisine # <----- Update for your camera
          roles:
            - record
            - audio
            - detect
#        - path: rtsp://127.0.0.1:8554/Cuisine_Sub # <----- Update for your camera
#          roles:
#            - detect
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args: preset-intel-qsv-h264
      # Optional: camera specific input args (default: inherit)
      input_args: preset-rtsp-generic
      # Optional: camera specific output args (default: inherit)
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Cuisine
    onvif:
      host: 192.168.1.21
      port: 2020
      user: ptichalouf
      password: xxxxxxxx



  Bureau: # <------ Name the camera
    detect:
#      width: 1280
#      height: 720
      fps: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Bureau # <----- Update for your camera
          roles:
            - record
            - audio
            - detect
#        - path: rtsp://127.0.0.1:8554/Bureau_Sub # <----- Update for your camera
#          roles:
#            - detect
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args: preset-intel-qsv-h264
      # Optional: camera specific input args (default: inherit)
      input_args: preset-rtsp-generic
      # Optional: camera specific output args (default: inherit)
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Bureau
    onvif:
      host: 192.168.1.24
      port: 2020
      user: ptichalouf
      password: xxxxxxxx





  Chambre: # <------ Name the camera
    detect:
#      width: 1280
#      height: 720
      fps: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Chambre # <----- Update for your camera
          roles:
            - record
            - audio
            - detect
#        - path: rtsp://127.0.0.1:8554/Chambre_Sub # <----- Update for your camera
#          roles:
#            - detect
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args: preset-intel-qsv-h264
      # Optional: camera specific input args (default: inherit)
      input_args: preset-rtsp-generic
      # Optional: camera specific output args (default: inherit)
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Chambre
    onvif:
      host: 192.168.1.22
      port: 2020
      user: ptichalouf
      password: xxxxxxxxxx






# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
#  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
#  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 60
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  # Optional: Threshold for camera activity to stop showing camera (default: shown below)
  inactivity_threshold: 30
  # Optional: Configure the birdseye layout
  layout:
    # Optional: Scaling factor for the layout calculator (default: shown below)
    scaling_factor: 2.0
    # Optional: Maximum number of cameras to show at one time, showing the most recent (default: show all cameras)
    max_cameras: 4









# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-intel-qsv-h264
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic-audio-copy
    # Optional: output args for rtmp streams (default: shown below)
  retry_interval: 10











objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
  filters:
    dog:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
#      mask:
#        - 488,395,634,371,626,249,490,253
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
#      mask:
#        - 488,395,634,371,626,249,490,253


# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70




# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
#  mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30







# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%d/%m/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)

# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.2.0)
go2rtc:
  streams:
    Buanderie:
      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.20/stream1
      - ffmpeg:Buanderie#audio=aac
    Buanderie_Sub:
#      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.20:554/stream2
#      - "ffmpeg:Buanderie#video=h264#audio=aac"
    Cuisine:
      - rtsp://ptichalouf:xxxxxxxx@192.168.1.21/stream1
      - ffmpeg:Cuisine#audio=aac
    Cuisine_Sub:
#      - rtsp://ptichalouf:xxxxxxxx@192.168.1.21:554/stream2
#      - "ffmpeg:Cuisine#video=h264#audio=aac"
    Chambre:
      - rtsp://ptichalouf:xxxxxxx@192.168.1.22/stream1
      - ffmpeg:Chambre#audio=aac
    Chambre_Sub:
#      - rtsp://ptichalouf:xxxxxx@192.168.1.22:554/stream2
#      - "ffmpeg:Chambre#video=h264#audio=aac"
    Salon:
      - rtsp://ptichalouf:xxxxxxx@192.168.1.23/stream1
      - ffmpeg:Salon#audio=aac
    Salon_Sub:
#      - rtsp://ptichalouf:xxxxxxxx@192.168.1.23:554/stream2
#      - "ffmpeg:Salon#video=h264#audio=aac"
    Bureau:
      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.24/stream1
      - ffmpeg:Bureau#audio=aac
    Bureau_Sub:
#      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.24:554/stream2
#      - "ffmpeg:Bureau#video=h264#audio=aac"
  webrtc:
    candidates:
      - 192.168.1.15:8555
      - stun:8555



# Optional
#ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
#  live_mode: webrtc
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
#  use_experimental: false
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
#  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
#  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
#  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
#  strftime_fmt: '%d/%m/%Y %H:%M'

# Optional: Telemetry configuration
telemetry:
  # Optional: Enabled network interfaces for bandwidth stats monitoring (default: empty list, let nethogs search all)
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  # Optional: Configure system stats
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: false
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: false
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: false

auth:
  enabled: false
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.17.0.0/16 # <---- this is the subnet for the internal docker compose network



# Optional: jsmpeg stream configuration for WebUI
#live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
#  stream_name: Buanderie
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
#  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8

database:
  path: /config/frigate.db
version: 0.15-0
semantic_search:
  enabled: true
  reindex: true
  model_size: small
```

### Relevant Frigate log output

```shell
2024-12-27 13:54:40.572327126      response = await call_next(request)
2024-12-27 13:54:40.572331834    File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 163, in call_next
2024-12-27 13:54:40.572335539      raise app_exc
2024-12-27 13:54:40.572340371    File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 149, in coro
2024-12-27 13:54:40.572344641      await self.app(scope, receive_or_disconnect, send_no_error)
2024-12-27 13:54:40.572349417    File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-12-27 13:54:40.572353872      await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-12-27 13:54:40.572358683    File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-12-27 13:54:40.572362341      raise exc
2024-12-27 13:54:40.572367376    File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-12-27 13:54:40.572371299      await app(scope, receive, sender)
2024-12-27 13:54:40.572376027    File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 715, in __call__
2024-12-27 13:54:40.572380270      await self.middleware_stack(scope, receive, send)
2024-12-27 13:54:40.572384946    File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 735, in app
2024-12-27 13:54:40.572388975      await route.handle(scope, receive, send)
2024-12-27 13:54:40.572393674    File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
2024-12-27 13:54:40.572397605      await self.app(scope, receive, send)
2024-12-27 13:54:40.572402229    File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 76, in app
2024-12-27 13:54:40.572406570      await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-12-27 13:54:40.572411350    File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-12-27 13:54:40.572414931      raise exc
2024-12-27 13:54:40.572419653    File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-12-27 13:54:40.572423592      await app(scope, receive, sender)
2024-12-27 13:54:40.572428177    File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 73, in app
2024-12-27 13:54:40.572431925      response = await f(request)
2024-12-27 13:54:40.572436487    File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 301, in app
2024-12-27 13:54:40.572440653      raw_response = await run_endpoint_function(
2024-12-27 13:54:40.572445405    File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
2024-12-27 13:54:40.572449660      return await run_in_threadpool(dependant.call, **values)
2024-12-27 13:54:40.572454502    File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
2024-12-27 13:54:40.572458681      return await anyio.to_thread.run_sync(func, *args)
2024-12-27 13:54:40.572463243    File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
2024-12-27 13:54:40.572467487      return await get_async_backend().run_sync_in_worker_thread(
2024-12-27 13:54:40.572472502    File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
2024-12-27 13:54:40.572476171      return await future
2024-12-27 13:54:40.572480892    File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 1005, in run
2024-12-27 13:54:40.572484759      result = context.run(func, *args)
2024-12-27 13:54:40.572488976    File "/opt/frigate/frigate/api/app.py", line 147, in config
2024-12-27 13:54:40.572492780      for item in stream:
2024-12-27 13:54:40.572496809  TypeError: 'NoneType' object is not iterable
```

### Relevant go2rtc log output

```shell
2024-12-27 08:01:37.145023521  [INFO] Preparing new go2rtc config...
2024-12-27 08:01:37.250044759  [INFO] Got IP address from supervisor: 192.168.1.15
2024-12-27 08:01:37.288061787  [INFO] Got WebRTC port from supervisor: 8555
2024-12-27 08:01:38.048487986  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-12-27 08:01:38.099590047  [INFO] Starting go2rtc...
2024-12-27 08:01:38.244813691  09:01:38.244 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-12-27 08:01:38.245566557  09:01:38.244 INF config path=/dev/shm/go2rtc.yaml
2024-12-27 08:01:38.245569421  09:01:38.245 INF [api] listen addr=:1984
2024-12-27 08:01:38.245582650  09:01:38.245 INF [rtsp] listen addr=:8554
2024-12-27 08:01:38.247664228  09:01:38.246 INF [webrtc] listen addr=:8555
2024-12-27 08:01:47.145686466  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
not possible sadly
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
hassOS addonbeta full access
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

tp c200

### Screenshots of the Frigate UI's System metrics pages

![Capture d'écran 2024-12-27 145614](https://github.com/user-attachments/assets/426237df-54f7-4185-89d7-a53f0280f4c1)

### Any other information that may be helpful

worked well from 0.11 to 0.15.2

**Comment by hawkeye217** [comment, marked as answer]
Thanks.

Can you change your go2rtc config temporarily to this and see if your issue is resolved?

```
go2rtc:
  streams:
    Buanderie:
      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.20/stream1
      - ffmpeg:Buanderie#audio=aac
#    Buanderie_Sub:
#      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.20:554/stream2
#      - "ffmpeg:Buanderie#video=h264#audio=aac"
    Cuisine:
      - rtsp://ptichalouf:xxxxxxxx@192.168.1.21/stream1
      - ffmpeg:Cuisine#audio=aac
#    Cuisine_Sub:
#      - rtsp://ptichalouf:xxxxxxxx@192.168.1.21:554/stream2
#      - "ffmpeg:Cuisine#video=h264#audio=aac"
    Chambre:
      - rtsp://ptichalouf:xxxxxxx@192.168.1.22/stream1
      - ffmpeg:Chambre#audio=aac
#    Chambre_Sub:
#      - rtsp://ptichalouf:xxxxxx@192.168.1.22:554/stream2
#      - "ffmpeg:Chambre#video=h264#audio=aac"
    Salon:
      - rtsp://ptichalouf:xxxxxxx@192.168.1.23/stream1
      - ffmpeg:Salon#audio=aac
#    Salon_Sub:
#      - rtsp://ptichalouf:xxxxxxxx@192.168.1.23:554/stream2
#      - "ffmpeg:Salon#video=h264#audio=aac"
    Bureau:
      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.24/stream1
      - ffmpeg:Bureau#audio=aac
#    Bureau_Sub:
#      - rtsp://ptichalouf:xxxxxxxxx@192.168.1.24:554/stream2
#      - "ffmpeg:Bureau#video=h264#audio=aac"
  webrtc:
    candidates:
      - 192.168.1.15:8555
      - stun:8555
```

Notice how I just commented out the *names* of the streams that had completely commented out stream definitions below it.
