### DISCUSSION TITLE
question about resolution and cpu usage

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#15719] [Ask A Question]
Two questions about stream resolution and cpu usage.

First, I understand from the documentation that 720p (1280x720) is the recommended resolution for detection. I have been using D1 (704x480) because this is the highest resolution on my substream. My cameras also have the ability to create a second substream at 720p. How much more demand will using 720p place on the cpu? I know that 720p has about 2.73x more pixels than D1. Does that mean 720p will use 2.73x more cpu resources if it is used for detection rather than D1?

Second, does resolution on the record stream impact cpu usage if the record stream is only being recorded?

**Comment by NickM-27** [comment]
It won't increase demand that much as motion detection is already run on a scaled down stream. The main difference is just pixel format changing but that won't increase load that much. 

And no record stream resolution won't affect cup usage for record processing

**Reply by Cold-Lemonade** [reply]
Will frames per second affect cpu usage for the record processing? I would think that the higher the fps then the more work the cpu must do to record the record stream to the hard drive.

**Reply by hawkeye217** [reply]
The `record` stream is just copied directly from your camera and not processed in any way by Frigate, so any CPU differences would be negligible.

**Comment by Cold-Lemonade** [comment]
In the go2rtc section, if I have already defined a camera called backyard_cam, can I resize it using the integrated GPU using this command?

```
go2rtc:
  streams:
    backyard_cam: 
...blah blah...
    backyard_cam_sub:
      - ffmpeg:backyard_cam#video=h264#width=1280#height=720#raw=-vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720"
```

Would this impose minimal demands on the cpu and also allow me to rescale the resolution of the backyard_cam while maintaining the original aspect ratio?
