### DISCUSSION TITLE
[Config Support]: min_area and min_score seems to be ignored

### DISCUSSION THREAD

**Discussion by wilcomir** [blakeblackshear/frigate#15712] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I am trying to improve detection accuracy in my setup by employing the `filters`. For one of my cameras I have the following configuration:

```
my_camera:
    ffmpeg:
      inputs:
        - path: rtsp://1.2.3.4
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      filters:
        peson:
          min_area: 100000
          min_score: 0.95
    review:
      alerts:
        labels: []
      detections:
        labels: []
```

There are no top level filters, or zones or anything like that in my config file. In my Explore section I get tons of person detection events with areas well below `100000`.

I did not provide the full config file below as I would need to clean it up a bit, I believe i just need a bit of help in debugging this. To be clear, this is not happening just for one camera, but for multiple cameras. I am using `filters` on all of them, not on zones, I have no top level filter configured, and yet it seems the setting is completely ignored.

### Steps to reproduce

1.
2.
3.
...

### Version

0.15.0-87e7b62

### In which browser(s) are you experiencing the issue with?

Safari

### Frigate config file

```yaml
not applicable
```

### docker-compose file or Docker CLI command

```yaml
not applicable
```

### Relevant Frigate log output

```shell
no relevant output that I am aware of
```

### Relevant go2rtc log output

```shell
not applicable
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

not applicable

### Screenshots of the Frigate UI's System metrics pages

not applicable
