### DISCUSSION TITLE
[Config Support]: Two cameras for the same stream, live preview shows one as fully black

### DISCUSSION THREAD

**Discussion by palves** [blakeblackshear/frigate#15715] [Config Support]
### Describe the problem you are having

I have a camera that I would like to stream both as is, and as zoomed/cropped to a specific region of the image [1] [2].
I thought I would do that by adding an extra camera to frigate, which is really streaming from the same URL as the original camera [3].

[1] - This is for convenience, to zoom on a driveway mirror.
[2] - I plan of using HASS as frontend for this.
[3] - Once I have this working, I would then tweak the ffmpeg settings of the new "camera" to apply a crop filter.)

See the simple config showing what I tried.  I removed hardware acceleration, etc, reduced it to bare minimum that can reproduce the problem.

So, I have go2rtc restreaming the original camera stream.  Then I create two frigate cameras, and both cameras feed from the same go2rtc restream path.

The problem is that while frigate understands that there are two cameras, in the frigate web UI, in the live view, I get two small preview squares, one for each camera, but only one of them shows a feed.  The other one shows a completely black image (with no text overlay, anything, just black, as if the camera was streaming a fully-black image).

If I click to open either of the frigate cameras in the live UI, then they both stream correctly (i.e., they both show the same real, live feed).  The issue seems to be really with the "Live" preview page.

What could I be doing wrong here?  Could this be a bug?

There are no errors in the logs.

(Any other suggestion of how to handle my use case?  I looked at the frigate card in home assistant, and couldn't find any way to statically pre-define a zoom/crop region for a camera, hence my idea to do it in frigate directly.)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
go2rtc:
  streams:
    cam1:
      - rtsp://user:pass@camera-ip:554/mpeg/media.amp

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
  cam1_zoom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
```

### Relevant Frigate log output

```shell
There are no errors in the log.
```

### Relevant go2rtc log output

```shell
There are no errors in the log.
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config:/config
      - /mnt/tank/data/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host
```

### Object Detector

CPU (no coral)
