### DISCUSSION TITLE
[Support]: Constant waste_bin detection

### DISCUSSION THREAD

**Discussion by slug56** [blakeblackshear/frigate#15720] [General Support] [answered]
### Describe the problem you are having

Before training my latest model, after the introduction of the waste_bin label, I labelled about 2,500 waste bins over about 1,000 previously submitted images.

I've created a "bins" zone to be able to get a sensor in Home Assistant that gives me a count of waste_bins in this zone to support some automation around waste collection.

I've noticed that detection is constantly jumping around by the waste bins when the video feed is as static as it could be. The count bounces between 1-2 several times a second (there are 2 bins in the zone).

https://github.com/user-attachments/assets/f2d7f2f3-8ae6-45df-a612-14cf0a2b4478

![Screenshot_20241228-222058](https://github.com/user-attachments/assets/8058d834-4658-4f13-8965-a21f222f458b)

I don't know what's causing it to do this. There are no red boxes in debug mode to suggest any motion is being detected, yet a constant stream of regions (green boxes) are being sent to the detector. Any ideas? 

### Version

0.15.0-87e7b62

### What browser(s) are you using?

Android Chrome 131.0.6778.200

### Frigate config file

```yaml
####################
### Global Setup ###
####################
camera_groups:
  All:
    order: 1
    icon: LuCamera
    cameras:
      - doorbell
      - garage
      - garden

database:
  path: /media/frigate/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    # Enable audio in recordings (original AAC)
    record: preset-record-generic-audio-copy

model:
  # Frigate+ model 20241106
  path: plus://0cfcdc52ff9aee05afad4a6d128e0ced

mqtt:
  enabled: true
  host: 10.20.39.23
  port: 1883
  user: aaa
  password: bbb

semantic_search:
  enabled: true
  reindex: false

ui:
  time_format: 24hour

version: 0.15-0

########################
### Recording Config ###
########################
audio:
  enabled: true
  listen:
    - bark
    - car_alarm
    - honk
    - speech
    - yell

birdseye:
  enabled: true
  mode: continuous

detect:
  annotation_offset: -1250

objects:
  filters:
    car:
      min_score: .65
      threshold: .85
    cat:
      min_score: .65
      threshold: .8
    dog:
      min_score: .65
      threshold: .8
    package:
      min_score: .65
      threshold: .9
    person:
      min_score: .65
      threshold: .85
    # The following objects don't have threshold scores (sub-labels)
    face:
      min_score: .7
    license_plate:
      min_score: .6

record:
  enabled: true
  retain:
    days: 31
    mode: all

  alerts:
    retain:
      days: 60
  detections:
    retain:
      days: 60
review:
  alerts:
    labels:
      - car
      - motorcycle
      - doorbell
      - person

snapshots:
  enabled: true

####################
### Stream Setup ###
####################
go2rtc:
  streams:
    doorbell:
      - ffmpeg:http://10.20.39.79/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=aaa&password=bbb#video=copy#audio=copy#audio=opus
      - rtsp://10.20.39.79/Preview_01_sub
    doorbell_sub:
      - ffmpeg:http://10.20.39.79/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=aaa&password=bbb
    garage:
      - rtsp://aaa:bbb@10.20.39.71:554/Streaming/Channels/101
    garage_sub:
      - rtsp://admin:m3SL67iY433aPHBP@10.20.39.71:554/Streaming/Channels/102
    garden:
      - rtsp://aaa:bbb@10.20.39.75:554/Streaming/Channels/101
    garden_sub:
      - rtsp://aaa:bbb@10.20.39.75:554/Streaming/Channels/102
  webrtc:
    candidates:
      - 10.20.39.32:8555
      - stun:8555

####################
### Camera Setup ###
####################
cameras:
  doorbell:
    detect:
      enabled: true
      fps: 7
      annotation_offset: -500
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
      output_args:
        # Enable audio in recordings transcoding to AAC
        record: preset-record-generic-audio-aac
    motion:
      mask: 
        0,0.481,0.106,0.476,0.317,0.507,0.316,0.641,0.017,0.592,0.023,0.674,0.132,0.748,0.252,0.787,0.359,0.814,0.499,0.822,0.639,0.811,0.816,0.779,0.912,0.735,1,0.634,1,0,0,0
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 672
    objects:
      filters:
        bicycle:
          mask:
            - 0,672,896,672,896,0,0,0,0,322,301,355,299,424,15,386,22,432,0,443
          min_area: 2000
          max_area: 60000
        car:
          mask:
            - 0,672,896,672,896,0,0,0,0,322,301,355,299,424,15,386,22,432,0,443
          min_area: 4000
          max_area: 75000
        cat:
          mask:
            - 141,441,375,483,597,485,783,441,896,392,896,0,0,0,0,399
          min_area: 1000
          max_area: 12000
        dog:
          mask:
            - 141,441,375,483,597,485,783,441,896,392,896,0,0,0,0,399
          min_area: 5000
          max_area: 40000
        face:
          mask:
            - 199,554,276,567,400,583,552,583,694,561,779,542,896,446,896,672,0,672,0,482
        motorcycle:
          mask:
            - 0,672,896,672,896,0,0,0,0,322,301,355,299,424,15,386,22,432,0,443
          min_area: 2000
          max_area: 60000
        package:
          mask:
            - 199,554,276,567,400,583,552,583,694,561,779,542,849,507,896,324,896,0,0,0,0,481
        person:
          mask:
            - 199,554,276,567,400,583,552,583,694,561,779,542,849,507,896,324,896,0,0,0,0,481
      track:
        - bicycle
        - car
        - cat
        - dog
        - face
        - motorcycle
        - package
        - person
    review:
      alerts:
        required_zones:
          - front_path
    zones:
      foster_avenue:
        coordinates: 0.339,0.515,0.07,0.478,0.072,0.667,0.328,0.718
        objects:
          - car
          - motorcycle
          - person
      front_path:
        coordinates: 186,550,326,573,469,591,627,575,734,549,896,500,896,672,0,672,0,490
        objects:
          - cat
          - dog
          - face
          - package
          - person

  garage:
    detect:
      enabled: true
      fps: 6
      annotation_offset: -4250
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.57,0.301,0.632,0.377,0.709,0.421,0.766,0.422,0.775,0.347,0.872,0.351,1,0.556,1,0,0.824,0,0.82,0.1,0.817,0.174,0.727,0.16,0.731,0,0.577,0
        - 0,0.56,0.109,0.36,0.168,0.274,0.154,0.21,0.133,0.184,0.145,0.06,0.022,0.06,0.022,0,0.315,0,0.314,0.058,0.283,0.099,0.283,0.19,0.298,0.302,0.224,0.567,0.13,1,0,1
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
    objects:
      track:
        - bicycle
        - car
        - cat
        - dog
        - license_plate
        - motorcycle
        - package
        - person
        - waste_bin
      filters:
        bicycle:
          mask:
            - 0,1,0,0.523,0.168,0.254,0.165,0.116,0,0.157,0,0,0.313,0,0.311,0.052,0.276,0.149,0.294,0.271,0.3,0.31,0.23,0.556,0.163,1
            - 0.738,0.428,0.622,0.399,0.565,0.286,0.575,0.219,0.581,0,0.72,0,0.717,0.189,0.83,0.216,0.837,0,1,0,1,1,0.985,1
        car:
          mask:
            - 0,1,0,0.523,0.168,0.254,0.165,0.116,0,0.157,0,0,0.313,0,0.311,0.052,0.276,0.149,0.294,0.271,0.3,0.31,0.23,0.556,0.163,1
            - 0.738,0.428,0.622,0.399,0.565,0.286,0.575,0.219,0.581,0,0.72,0,0.717,0.189,0.83,0.216,0.837,0,1,0,1,1,0.985,1
        cat:
          mask: 
            0.297,0.083,0.577,0.065,0.581,0.148,0.603,0.273,0.722,0.31,0.875,0.34,1,0.533,1,1,1,0,0,0,0,0.142
        dog:
          mask: 
            0.297,0.083,0.577,0.065,0.581,0.148,0.603,0.273,0.722,0.31,0.875,0.34,1,0.533,1,1,1,0,0,0,0,0.142
        license_plate:
          mask:
            - 0,1,0,0.523,0.167,0.242,0.145,0.069,0,0.118,0,0,0.313,0,0.311,0.052,0.295,0.146,0.294,0.271,0.3,0.31,0.23,0.556,0.163,1
            - 0.738,0.428,0.622,0.399,0.565,0.286,0.575,0.219,0.581,0,0.72,0,0.717,0.189,0.83,0.216,0.837,0,1,0,1,1,0.985,1
        motorcycle:
          mask:
            - 0,1,0,0.523,0.168,0.254,0.165,0.116,0,0.157,0,0,0.313,0,0.311,0.052,0.276,0.149,0.294,0.271,0.3,0.31,0.23,0.556,0.163,1
            - 0.738,0.428,0.622,0.399,0.565,0.286,0.575,0.219,0.581,0,0.72,0,0.717,0.189,0.83,0.216,0.837,0,1,0,1,1,0.985,1
        package:
          mask: 0,0,0,0.519,0.13,1,0.298,0.3,0.566,0.295,0.63,0.401,0.793,0.429,1,0.902,1,0
        person:
          mask:
            - 0,0.515,0.156,0.267,0.155,0.198,0.13,0.173,0.127,0.133,0.139,0,0.306,0,0.289,0.144,0.294,0.206,0.306,0.29,0.155,1,0,1
            - 1,1,0.983,1,0.841,0.613,0.863,0.365,0.808,0.37,0.704,0.354,0.644,0.338,0.576,0.288,0.58,0,1,0,1,0.654
        waste_bin:
          mask:
            - 0,1,0,0.523,0.168,0.254,0.165,0.116,0,0.157,0,0,0.313,0,0.311,0.052,0.276,0.149,0.294,0.271,0.3,0.31,0.23,0.556,0.163,1
            - 0.738,0.428,0.622,0.399,0.565,0.286,0.575,0.219,0.581,0,0.72,0,0.717,0.189,0.83,0.216,0.837,0,1,0,1,1,0.985,1
    review:
      alerts:
        required_zones:
          - driveway
          - kerb
      detections:
        required_zones:
          - foster_avenue
    zones:
      driveway:
        coordinates: 0.231,0.554,0.295,0.318,0.571,0.311,0.627,0.41,0.736,0.421,0.966,1,0.139,1
      foster_avenue:
        coordinates: 
          0.142,0.285,0.166,0.263,0.277,0.254,0.298,0.296,0.442,0.285,0.569,0.284,0.597,0.254,0.586,0.198,0.73,0.198,0.832,0.209,0.823,0.084,0.754,0.067,0.524,0.04,0.268,0.04,0,0.114,0.002,0.319
        objects:
          - bicycle
          - car
          - cat
          - dog
          - motorcycle
          - person
      kerb:
        coordinates: 
          0.297,0.295,0.588,0.281,0.572,0.21,0.572,0.148,0.571,0.109,0.556,0.042,0.267,0.039,0.255,0.141,0.259,0.245,0.267,0.292
        objects:
          - bicycle
          - car
          - cat
          - dog
          - motorcycle
          - person
          - waste_bin
        loitering_time: 30
        inertia: 3
      bins:
        coordinates: 0.86,0.365,1,0.632,1,1,0.848,1,0.657,0.364
        loitering_time: 0
        objects: waste_bin

  garden:
    detect:
      enabled: true
      fps: 6
      annotation_offset: -4100
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.445,1,0.178,0.599,0.213,0.523,0.203,0.298,0.311,0.221,0.374,0.231,0.391,0.315,0.607,0.309,0.671,0.537,0.653,0.67,0.66,0.865,0.676,1
        - 0.779,0.265,0.863,0.207,0.927,0.26,1,0.379,1,0.521,0.884,0.908,0.836,0.896,0.792,0.678,0.796,0.559
        - 0,1,0.15,1,0,0.531
        - 0,0,0.781,0,0.78,0.098,0.691,0.115,0.463,0.133,0.184,0.127,0.208,0.34,0,0.483
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
    objects:
      track:
        - cat
        - person
    zones:
      garden_path:
        coordinates: 
          0.108,0.516,0.423,0.951,0.658,0.946,0.67,0.483,0.765,0.5,0.839,0.899,0.926,0.916,0.94,0.58,1,0.582,1,1,0.136,1,0.012,0.607
      lawn:
        coordinates: 
          0.36,0.313,0.294,0.231,0.338,0.191,0.387,0.193,0.389,0.216,0.514,0.211,0.555,0.209,0.645,0.208,0.634,0.313,0.675,0.481,0.659,0.546,0.593,0.428,0.52,0.413,0.394,0.645,0.243,0.491
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### FFprobe output from your camera

```shell
TBC
```

### Frigate stats

```json
{"cameras":{"doorbell":{"camera_fps":5.9,"process_fps":3.6,"skipped_fps":1.3,"detection_fps":0.3,"detection_enabled":true,"pid":622,"capture_pid":646,"ffmpeg_pid":664,"audio_rms":18.4682,"audio_dBFS":-64.9805},"garage":{"camera_fps":6.1,"process_fps":6.0,"skipped_fps":0.0,"detection_fps":6.2,"detection_enabled":true,"pid":628,"capture_pid":665,"ffmpeg_pid":671,"audio_rms":12.7692,"audio_dBFS":-68.1857},"garden":{"camera_fps":6.1,"process_fps":6.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":638,"capture_pid":672,"ffmpeg_pid":697,"audio_rms":24.2431,"audio_dBFS":-62.6172}},"detectors":{"coral":{"inference_speed":8.77,"detection_start":1735425538.424018,"pid":555}},"detection_fps":6.5,"gpu_usages":{"intel-vaapi":{"gpu":"1.25%","mem":"-%","clients":{"664":"8.93%","671":"0.8%","697":"0.76%"}},"intel-qsv":{"gpu":"0.38%","mem":"-%","clients":{"664":"0.63%","671":"0.61%","697":"0.95%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"4.2","mem":"40.5"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"17":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"86":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"98":{"cpu":"8.2","cpu_average":"7","mem":"0.0","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"110":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"116":{"cpu":"5.5","cpu_average":"6","mem":"1.8","cmdline":"python3 -u -m frigate"},"128":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"159":{"cpu":"0.2","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"160":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"161":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"162":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"259":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"311":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"522":{"cpu":"0.5","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.20.39.79/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/7b5d517ef6ae3c77bb20309e99338828"},"539":{"cpu":"2.0","cpu_average":"1","mem":"0.8","cmdline":"frigate.recording_manager"},"548":{"cpu":"0.5","cpu_average":"0","mem":"0.8","cmdline":"frigate.review_segment_manager"},"555":{"cpu":"4.0","cpu_average":"4","mem":"0.3","cmdline":"frigate.detector.coral"},"559":{"cpu":"0.2","cpu_average":"2","mem":"1.2","cmdline":"frigate.embeddings_manager"},"580":{"cpu":"2.0","cpu_average":"2","mem":"0.8","cmdline":"frigate.output       "},"585":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"592":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"599":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"606":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"622":{"cpu":"1.1","cpu_average":"1","mem":"0.8","cmdline":"frigate.process:doorbell"},"628":{"cpu":"6.4","cpu_average":"6","mem":"0.8","cmdline":"frigate.process:garage"},"638":{"cpu":"2.1","cpu_average":"1","mem":"0.8","cmdline":"frigate.process:garden"},"646":{"cpu":"0.6","cpu_average":"0","mem":"0.8","cmdline":"frigate.capture:doorbell"},"664":{"cpu":"1.7","cpu_average":"1","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_sub -r 7 -vf fps=7,scale_vaapi=w=896:h=672,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"665":{"cpu":"1.8","cpu_average":"1","mem":"0.8","cmdline":"frigate.capture:garage"},"670":{"cpu":"1.1","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4"},"671":{"cpu":"3.2","cpu_average":"2","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_sub -r 6 -vf vpp_qsv=framerate=6:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"672":{"cpu":"1.8","cpu_average":"1","mem":"0.8","cmdline":"frigate.capture:garden"},"676":{"cpu":"1.9","cpu_average":"1","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://10.20.39.79/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/2964f461ca29341a105be7640ad1bf46"},"678":{"cpu":"1.2","cpu_average":"1","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4"},"679":{"cpu":"0.6","cpu_average":"0","mem":"0.8","cmdline":"python3 -u -m frigate"},"695":{"cpu":"0.2","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_sub -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:"},"697":{"cpu":"3.2","cpu_average":"2","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub -r 6 -vf vpp_qsv=framerate=6:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"739":{"cpu":"1.2","cpu_average":"1","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4"},"740":{"cpu":"1.3","cpu_average":"1","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_sub -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:"},"767":{"cpu":"1.3","cpu_average":"1","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:"},"6519":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"6651":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":1671,"version":"0.15.0-87e7b62","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":3754443.0,"used":3444401.6,"free":119253.1,"mount_type":"ext4"},"/media/frigate/clips":{"total":3754443.0,"used":3444401.6,"free":119253.1,"mount_type":"ext4"},"/tmp/cache":{"total":953.7,"used":44.8,"free":908.9,"mount_type":"tmpfs"},"/dev/shm":{"total":512.0,"used":177.5,"free":334.5,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1735425539},"processes":{"recording":{"pid":539},"review_segment":{"pid":548},"go2rtc":{"pid":98},"embeddings":{"pid":559},"audio_detector":{"pid":679}}}
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
TBC
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2346G2-IU
