### DISCUSSION TITLE
[Camera Support]: Reolink RLC-520A recordings not working

### DISCUSSION THREAD

**Discussion by awesomeruss** [blakeblackshear/frigate#15726] [Camera Support]
### Describe the problem you are having

I'm using a pair of new reolink POE cameras, connected via a POE switch to a new Beelink MINI S12 running docker, that is connected to the rest of my home network via wifi.

Live streams are fine. Detection is fine - events are added when I walk in front of the cams. go2rtc can access all the streams just fine (checked all 4 streams using go2rtc port 1984 web ui). The animated previews of events are fine.

Recordings are present on the disk as mp4 files. VLC tells me they are H264 - MPEG-4 AVC video files with resolution 2560x1920 and frame rate of 29.9fps with MPEG AAC 32KHz audio

Disk write operations are consistently below 0.01s according to frigate.record.maintainer log entries

Recording playback within the Frigate UI is not working. Numerous 404 errors appear in the browser console, e.g:
GET http://gml17:5000/api/preview/all/start/1735394400/end/1735484400 404 (NOT FOUND)

Occasionally if I wait for several minutes, a part of the recorded video will load in and play.
I suspected poor disk read performance may be the root cause, and tried mapping the frigate storage location to a USB micro SD card, but this did not show any improvement.

Disk performance appears to be around 55mbps write, 82mbps read on the system disk, 50/75 on the SD card when  Frigate isn't running.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: gml17
  user: hass
  password: secret

logger:
  default: debug
#  logs:
#    frigate.record.maintainer: debug

record:
#  sync_recordings: true
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 30
      mode: motion

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    cam1:
      - rtsp://homeassistant:mypassword@192.168.1.5:554/h264Preview_01_main
      - ffmpeg:cam1_rtsp#audio=opus
    cam1_sub:
      - rtsp://homeassistant:mypassword@192.168.1.5:554/h264Preview_01_sub
      - ffmpeg:cam1_sub_rtsp#audio=opus
    cam2:
      - rtsp://homeassistant:mypassword@192.168.1.6:554/h264Preview_01_main
      - ffmpeg:cam2_rtsp#audio=opus
    cam2_sub:
      - rtsp://homeassistant:T1f$mypassword@192.168.1.6:554/h264Preview_01_sub
      - ffmpeg:cam2_sub_rtsp#audio=opus
  hwaccel_args: preset-vaapi


cameras:

  cam1:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.01:8554/cam1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

  cam2:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.01:8554/cam2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

objects:
  track:
    - person
    - dog
    - animal

version: 0.14
```

### Relevant Frigate log output

```shell
I haven't seen any issues in the frigate, go2rtc or nginx logs
```

### Relevant go2rtc log output

```shell
I haven't seen any issues in the frigate, go2rtc or nginx logs
```

### FFprobe output from your camera

```shell
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.1.5/h264Preview_01_main/",
      "remote_addr": "192.168.1.5:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1735478438401207 1 IN IP4 0.0.0.0\r\ns=Session streamed by \"preview\"\r\ni=h264Preview_01_main\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2020.08.12\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:h264Preview_01_main\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:500\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:256\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:track2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        "96 H264, bytes=1252833236, senders=2",
        "97 MPEG4-GENERIC/16000, bytes=12840660, senders=2"
      ],
      "recv": 1276723232
    },
    {
      "url": "ffmpeg:cam1_rtsp#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.01:8554/cam1",
      "remote_addr": "127.0.0.1:33212",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=1252833236, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=12840660, receivers=1"
      ],
      "send": 1280364936
    },
    {
      "type": "probe",
      "remote_addr": "192.168.86.87:56456",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=0, receivers=1"
      ]
    }
  ]
}
```

### Frigate stats

```json
{
  "cameras": {
    "cam1": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5,
      "capture_pid": 468,
      "detection_enabled": true,
      "detection_fps": 2.9,
      "ffmpeg_pid": 473,
      "pid": 453,
      "process_fps": 5,
      "skipped_fps": 0
    },
    "cam2": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.1,
      "capture_pid": 471,
      "detection_enabled": true,
      "detection_fps": 4.8,
      "ffmpeg_pid": 480,
      "pid": 456,
      "process_fps": 5,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "101": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "13.7",
      "cpu_average": "13",
      "mem": "0.5"
    },
    "122": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "123": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "2.4",
      "cpu_average": "2",
      "mem": "4.5"
    },
    "132": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "158": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "230": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "235": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "24": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "295": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "338": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "1.5"
    },
    "34": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "404": {
      "cmdline": "frigate.recording_manager",
      "cpu": "1.6",
      "cpu_average": "1",
      "mem": "1.9"
    },
    "411": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "1.7"
    },
    "433": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(59)",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "434": {
      "cmdline": "frigate.detector.coral",
      "cpu": "15.5",
      "cpu_average": "18",
      "mem": "1.9"
    },
    "436": {
      "cmdline": "frigate.output       ",
      "cpu": "1.9",
      "cpu_average": "2",
      "mem": "1.8"
    },
    "45": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "453": {
      "cmdline": "frigate.process:cam1 ",
      "cpu": "3.4",
      "cpu_average": "3",
      "mem": "1.8"
    },
    "456": {
      "cmdline": "frigate.process:cam2 ",
      "cpu": "3.3",
      "cpu_average": "3",
      "mem": "1.9"
    },
    "46": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "468": {
      "cmdline": "frigate.capture:cam1 ",
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "1.7"
    },
    "471": {
      "cmdline": "frigate.capture:cam2 ",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "1.7"
    },
    "473": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam1_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "1.9",
      "cpu_average": "1",
      "mem": "0.7"
    },
    "480": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam2_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.0",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "483": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.01:8554/cam1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/cam1@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.3",
      "cpu_average": "1",
      "mem": "0.4"
    },
    "487": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.01:8554/cam2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/cam2@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.4"
    },
    "489": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.5"
    },
    "494": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "499": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3"
    },
    "656": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(48)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "85": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "8598": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "87": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "15.2",
      "mem": "31.9"
    }
  },
  "detection_fps": 7.7,
  "detectors": {
    "coral": {
      "detection_start": 1735484315.52092,
      "inference_speed": 27.44,
      "pid": 434
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.22%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 101
    },
    "logger": {
      "pid": 338
    },
    "recording": {
      "pid": 404
    },
    "review_segment": {
      "pid": 411
    }
  },
  "service": {
    "last_updated": 1735484316,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 60.5,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 3.5
      },
      "/media/frigate/clips": {
        "free": 212667.2,
        "mount_type": "ext4",
        "total": 237813.4,
        "used": 12994.8
      },
      "/media/frigate/recordings": {
        "free": 212667.2,
        "mount_type": "ext4",
        "total": 237813.4,
        "used": 12994.8
      },
      "/tmp/cache": {
        "free": 905.5,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 48.1
      }
    },
    "temperatures": {

    },
    "uptime": 2580,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

Reolink RLC-520A 

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d0e55a24-3214-4519-b424-588dcf4c62c7)

**Comment by awesomeruss** [comment]
Sorry - should add: Chrome browser.

**Comment by awesomeruss** [comment]
After a power cut last night it's magically fixed - looks like something was cleared by a reboot.

**Comment by cvandesande** [comment]
Sounds like you got this solved, but for anyone else I also use a pair of RLC-520As. They are problematic due to delays when starting the RTSP streams, but using the `ffmpeg` module with go2rtc seems to work nearly perfectly. The only caveat is that when Frigate starts or restarts the video feeds show errors for the first 30-45 seconds before it resolves itself. Same thing happens when testing the streams directly with `ffplay`.  Chalk it up to cost savings lol

```
cameras:
  reolink_front:
    ui:
      order: 0
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_front_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/reolink_front
          roles:
            - record
            - audio
    detect:
      width: 640
      height: 480
      fps: 10
            
  reolink_back:
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_back_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/reolink_back
          roles:
            - record
            - audio
    detect:
      width: 640
      height: 480
      fps: 10

go2rtc:
  streams:
    reolink_front:
      - ffmpeg:rtsp://admin:'{REOLINK_PASSWORD}'@reolink-front:554/h264Preview_01_main
    reolink_front_sub:
      - ffmpeg:rtsp://admin:'{REOLINK_PASSWORD}'@reolink-front:554/h264Preview_01_sub
    reolink_back:
      - ffmpeg:rtsp://admin:'{REOLINK_PASSWORD}'@reolink-back:554/h264Preview_01_main
    reolink_back_sub:
      - ffmpeg:rtsp://admin:'{REOLINK_PASSWORD}'@reolink-back:554/h264Preview_01_sub
```
