### DISCUSSION TITLE
[HW Accel Support]: Intel iGPU + ARC GPU

### DISCUSSION THREAD

**Discussion by magma1447** [blakeblackshear/frigate#15739] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I am running Frigate with `docker compose`. My system has an iGPU and also an ARC GPU.

If I start Frigate with the iGPU only everything works fine. I prevent the ARC GPU from being used by `echo "0000:03:00.0" | sudo tee /sys/bus/pci/drivers/i915/unbind`. As soon as I bind that device again Frigate fails to start (crashes). See *Relevant Frigate log output* below.

The host system is Debian stable. With a kernel (`6.11.10`) from backports since the `ARC A310` wasn't supported by Debian Stable's kernel (6.1, 6.3 was recommended, if I recall correctly).

If I instead disable the iGPU and enable the ARC a similar crash of Frigate happens.

If I run `clinfo` inside the container one *platform* is shown if having the iGPU only. ARC only or both ends with zero *platforms* returned.

My end goal is to provide two GPUs that can be used for detectors. Anyone having more clue than I have? Or should I just assume that it's an issue with the Intel drivers?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/models/yolo_nas_m.onnx
  labelmap_path: /labelmap/coco-80.txt
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    network_mode: bridge
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # passes GPU
      - /dev/dri/renderD129:/dev/dri/renderD129 # passes GPU
    
    shm_size: "384MB"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/config:/config
      - media_nfs01:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1073741824
    ports:
      - "5000:5000"
      - "9554:8554" #RTSP feeds
      - "9555:8555/tcp" # WebRTC over tcp
      - "9555:8555/udp" # WebRTC over udp
    environment:
      - TZ=Europe/Stockholm
      - FRIGATE_RTSP_PASSWORD="REDACTED"
volumes:
  media_nfs01:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=REDACTED,nfsvers=4,soft,noexec,nosuid,tcp,rw"
      device: ":/srv/frigate_media"
```

### Relevant Frigate log output

```shell
frigate  | 2024-12-30 18:15:33.540557222  Process detector:ov:
frigate  | 2024-12-30 18:15:33.541431447  Traceback (most recent call last):
frigate  | 2024-12-30 18:15:33.541434649    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-12-30 18:15:33.541436112      self.run()
frigate  | 2024-12-30 18:15:33.541437585    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-12-30 18:15:33.541441610      self._target(*self._args, **self._kwargs)
frigate  | 2024-12-30 18:15:33.541443256    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2024-12-30 18:15:33.541460205      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2024-12-30 18:15:33.541462324    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2024-12-30 18:15:33.541463555      self.detect_api = create_detector(detector_config)
frigate  | 2024-12-30 18:15:33.541464709    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2024-12-30 18:15:33.541482579      return api(detector_config)
frigate  | 2024-12-30 18:15:33.541484162    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 43, in __init__
frigate  | 2024-12-30 18:15:33.541485447      self.interpreter = self.ov_core.compile_model(
frigate  | 2024-12-30 18:15:33.541486662    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 521, in compile_model
frigate  | 2024-12-30 18:15:33.541505010      super().compile_model(model, device_name, {} if config is None else config),
frigate  | 2024-12-30 18:15:33.541506277  RuntimeError: Exception from src/inference/src/cpp/core.cpp:123:
frigate  | 2024-12-30 18:15:33.541507451  Exception from src/inference/src/dev/plugin.cpp:59:
frigate  | 2024-12-30 18:15:33.541508687  Check 'contexts.count(device_id)' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:204:
frigate  | 2024-12-30 18:15:33.541510079  [GPU] Context was not initialized for 0 device
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Several Hikvisions

### Screenshots of the Frigate UI's System metrics pages

N/A since Frigate doesn't start.

**Comment by NickM-27** [comment]
So does it work if you limit to one or the other via the compose config?

**Reply by magma1447** [reply]
That's the weird part, at least to me. They both show up in the container even though I remove them both.

```
services:
  frigate:
    container_name: frigate
    network_mode: bridge
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    #build:
    #  context: image
    #devices:
      #- /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral
      #- /dev/dri/renderD128:/dev/dri/renderD128 # passes GPU
      #- /dev/dri/renderD129:/dev/dri/renderD129 # passes GPU
```

```
docker compose down
vim docker-compose.yaml
docker compose up -d
docker exec -it frigate bash
root@e07748ae567a:/opt/frigate# ls -l /dev/dri
total 0
crw-rw---- 1 root video 226,   0 Dec 31 09:33 card0
crw-rw---- 1 root video 226,   1 Dec 31 09:33 card1
crw-rw---- 1 root   105 226, 128 Dec 31 09:33 renderD128
crw-rw---- 1 root video 226, 129 Dec 31 09:33 renderD129
```

That's why I disabled the ARC like this:
`echo "0000:03:00.0" | sudo tee /sys/bus/pci/drivers/i915/unbind`

Also, even if none of them are included in `docker-compose.yaml`, and the ARC is `unbind` the iGPU actually works. `sudo intel_gpu_top -d drm:/dev/dri/card0` shows that it's getting used. Just as shown above the dri device exists in the container even though I don't pass it.

I am using Docker's offical repositories.
`deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian   bookworm stable`

The operating system is a new fresh install. I have moved my Frigate installation (`docker-compose.yaml`) from an old (temporary) NUC to new hardware.
