### DISCUSSION TITLE
OpenVino, YOLO-nas, N150 Beelink EQ14, number of detectors and performance

### DISCUSSION THREAD

**Discussion by daubman** [blakeblackshear/frigate#15735] [Ask A Question] [answered]
I am migrating from a Beelink EQ12 N100 with m.2 Coral to an EQ14 N150 and trying Openvino to compare. I am using the latest 0.15.0 Beta 4 on both systems.

I have 10 cameras, detect is always using low-quaity substreams at 5-8fps. With the coral, everything was performant, speeds were ~10ms, coral never seemed busy.

I am currently using the basic config recommendations with two ov detectors and the yolo-nas model built from the (modified for new url) colab notebook:

```
detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt
```

This seem to be working OK (is there any discussion around detection accuracy/performance vs coral and default builtin model?) except I get sporadic (and especially startup) spikes very high for the ov detectors.

I also didn't see any discussion of how many detectors, and especially how to tell how many iGPU like N150 could/should support... The graphs look identical, but should I add more detectors? How many is enough vs too many, etc...

<img width="2000" alt="Screenshot 2024-12-30 at 9 08 22 AM" src="https://github.com/user-attachments/assets/f986c051-bc13-4d1f-b8a3-2e1ca1a56c46" />
<img width="694" alt="Screenshot 2024-12-30 at 9 08 32 AM" src="https://github.com/user-attachments/assets/fd0a9e22-1451-4134-9533-28080f8136c2" />

At 45 detections per second, I'm skipping 9 per second:
<img width="382" alt="Screenshot 2024-12-30 at 9 18 01 AM" src="https://github.com/user-attachments/assets/65559c49-542e-40a6-bb5a-dd50b5c0530e" />
