### DISCUSSION TITLE
Live view slow to start

### DISCUSSION THREAD

**Discussion by swazrgb** [blakeblackshear/frigate#15749] [Ask A Question]
When I click on a camera Frigate displays a spinner for 2-5 seconds before showing the camera feed. Is this normal or does it depend on the camera? Is there any way to speed this up?

My cameras are a Reolink RLC-520 (`your_realink_camera`) and a Reolink Video Doorbell PoE-W (`doorbell`)

I'm running on a Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, 16GB ram, and a PCIE Coral

When I look at the developer console I see websocket connection (`wss://172.16.44.10:8971/live/mse/api/ws?src=your_reolink_camera
`) being opened almost as soon as I click the camera, with the following timings:

![image](https://github.com/user-attachments/assets/6bc18375-c7f9-4518-90eb-a2bdaba4e172)

Config:

```
mqtt:
  enabled: false

tls:
  enabled: true

birdseye:
  enabled: true
  mode: motion

ffmpeg:
  hwaccel_args: preset-vaapi
  # hwaccel_args: preset-nvidia-h264

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 300


go2rtc:
  streams:
    your_reolink_camera:
      - ffmpeg:http://192.168.200.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=removed#video=copy#audio=copy#audio=opus
    your_reolink_camera_sub:
      - ffmpeg:http://192.168.200.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=removed
    doorbell:
      - ffmpeg:http://192.168.200.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=removed#video=copy#audio=copy#audio=opus
      - rtsp://admin:removed@192.168.200.2/Preview_01_sub
    doorbell_sub:
      - ffmpeg:http://192.168.200.2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=removed
  webrtc:
    candidates:
      - 172.16.44.10:8555
      - stun:8555


cameras:
  doorbell:
    detect:
      width: 480
      height: 640
      fps: 7
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.209,0.009,0.21,0.046,0.774,0.05,0.776,0.005
    live:
      stream_name: doorbell
  your_reolink_camera:
    live:
      stream_name: your_reolink_camera
    detect:
      width: 640
      height: 480
      fps: 7
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/your_reolink_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/your_reolink_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask: 0.567,0.067,0.982,0.065,0.983,0.023,0.568,0.023
camera_groups:
  Birdseye:
    order: 1
    icon: LuEye
    cameras: birdseye
version: 0.14
```
