### DISCUSSION TITLE
[Config Support]: Config issue with review/recording playback

### DISCUSSION THREAD

**Discussion by mwilky** [blakeblackshear/frigate#15741] [Config Support]
### Describe the problem you are having

So my live view works absolutely fine after using the `- ffmpeg:front_cam#video=h264#hardware` properties, but I still can't view the recordings/reviews on a windows PC using latest Chrome. I get the infinite loading circle. I can view them fine through my Pixel 8 Pro, so i know the issue lies somewhere with the codecs.

The PC I am trying to view on has a i7-7800X CPU and a really old AMD Radeon HD 6770 GPU, so if this is the case then forgive me.

### Version

0.15.0-6b12a45

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.119
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: XXXX

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    front_cam:
      - rtsp://admin:XXXX@192.168.0.50:554/Streaming/Channels/101?
      - ffmpeg:front_cam#video=h264#hardware
    front_cam_sub:
      - rtsp://admin:XXXX@192.168.0.50:554/Streaming/Channels/102?
      - ffmpeg:front_cam_sub#video=h264#hardware
    back_cam:
      - rtsp://admin:XXXX@192.168.0.51:554/Streaming/Channels/101?
      - ffmpeg:back_cam#video=h264#hardware
    back_cam_sub:
      - rtsp://admin:XXXX@192.168.0.5:554/Streaming/Channels/102?
      - ffmpeg:back_cam_sub#video=h264#hardware
cameras:
  front_cam:
    snapshots:
      required_zones:
        - drive
    live:
      stream_name: front_cam

    review:
      alerts:
        required_zones: drive
      detections:
        required_zones: drive
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://192.168.0.12:8554/front_cam # Mainstream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.0.12:8554/front_cam_sub # Substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    zones:
      drive:
        coordinates: 
          0.001,0.326,0.048,0.629,0.22,0.49,0.376,0.351,0.435,0.297,0.745,0.513,0.878,0.628,0.865,0.708,0.853,0.764,0.842,0.82,0.828,0.877,0.795,1,0.001,0.998
        inertia: 3
        loitering_time: 0
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: true

      mask: 0,0.107,0.345,0.128,0.339,0.002,0.011,-0.014
  back_cam:
    live:
      stream_name: back_cam
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.12:8554/back_cam # Mainstream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.0.12:8554/back_cam_sub # Substream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    motion:
      mask: 0,0,0,0.1,0.315,0.102,0.319,0.004
snapshots:
  enabled: true

objects:
  track:
    - person
    - car
    - cat

version: 0.15-0
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
Nothing I can see shows
```

### Relevant go2rtc log output

```shell
Nothing I can see shows
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Will grab shortly
```

### Object Detector

Coral
