### DISCUSSION TITLE
[Config Support]: Nest Cam - Configurations

### DISCUSSION THREAD

**Discussion by watsondan** [blakeblackshear/frigate#15758] [Config Support]
### Describe the problem you are having

Hello frigate friends:

I am working on getting a Google Nest Cam configured in my Frigate system. 

I have 2 POE ReoLink Cams and then I had an old Nest Cam that I did WAY too much research into trying to get this thing to work.

I have my Synology NAS - DSM 7.2.2 running a Container in Container Manager with Yaml configs.

On my google side of the universe I have created projects and created all the needed keys and ids from these steps: https://developers.google.com/nest/device-access/get-started

When I spin up Frigate and view the Go2rtc Logs I see the warnings for:

> error="streams: Post \"https://www.googleapis.com/oauth2/v4/token\": dial tcp: lookup www.googleapis.com on 127.0.0.11:53: read udp 127.0.0.1:34488->127.0.0.11:53: i/o timeout" stream=google_nest_cam

I surmise it is has something to do with my `webrtc` candidates. Maybe I have the wrong ip address there and whatever `0.11:53` is doesn't have bridged access... But also, there could be other configuration issues. As I am not getting my environment variables to work.

### Version

latest

### Frigate config file

```yaml
mqtt:
  #host: 192.168.86.24:1883
  enabled: false

go2rtc:
  streams:
    # Reolink Video Doorbell PoE
    reolink_doorbell:
      - ffmpeg:http://192.168.1.74/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={REOLINK_CAM_PASS}#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.74:554/Preview_01_sub
    reolink_doorbell_sub:
      - ffmpeg:http://192.168.1.74/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={REOLINK_CAM_PASS}
    # E1 Outdoor SE PoE
    reolink_ptz_camera:
      - ffmpeg:http://192.168.1.74/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={REOLINK_CAM_PASS}
    reolink_ptz_camera_sub:
      - ffmpeg:http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={REOLINK_CAM_PASS}#video=copy#audio=copy#audio=opus
    # Nest Cam
    google_nest_cam:
      - nest:?client_id={GOOGLE_CLIENT_ID}&client_secret={GOOGLE_CLIENT_PW}&device_id={GOOGLE_DEVICE_ID}&project_id={GOOGLE_PROJEC_ID}&refresh_token={GOOGLE_REFRES_TK}

  webrtc:
    candidates:
      - 192.168.86.24:8555 # <---- This is my NAS's LAN address.
      - stun:8555
cameras:
  kitchen_dine:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/google_nest_cam?video=h264&audio=opus
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480

  front_door_bell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1920
      
  back_yard_schroeder_rd:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_ptz_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_ptz_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    # onvif: << --- I am also missing something here... PTZ doesn't work...
    #   host: 192.168.1.75
    #   port: 8000
    #   user: admin
    #   password: sPlatter3ed
    detect:
      enabled: true
      width: 3840
      height: 2160
version: 0.14
camera_groups:
  house:
    order: 1
    icon: LuHome
    cameras:
      - birdseye
      - back_yard_schroeder_rd
      - front_door_bell
      # - kitchen_dine
```

### Relevant Frigate log output

```shell
ffmpeg.kitchen_dine.detect
rtsp://127.0.0.1:8554/google_nest_cam?video=h264&audio=opus: Invalid data found when processing input
```

### Relevant go2rtc log output

```shell
rtsp
error="streams: Post \"https://www.googleapis.com/oauth2/v4/token\": dial tcp: lookup www.googleapis.com on 127.0.0.11:53: read udp 127.0.0.1:34488->127.0.0.11:53: i/o timeout" stream=google_nest_cam
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: '3.9'

services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/security/frigate/config:/config:rw
      - /volume1/docker/security/frigate/media:/media/frigate:rw
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 1935:1935 
      - 5563:8971 #Web UI Interface Port
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp\
    environment:
     TZ: America/Chicago
     FRIGATE_RTSP_PASSWORD: xxxx
     REOLINK_CAM_PASS: xxxx
     GOOGLE_CLIENT_ID: xxxx
     GOOGLE_CLIENT_PW: xxxx
     GOOGLE_DEVICE_ID: xxxx
     GOOGLE_PROJEC_ID: xxxx
     GOOGLE_REFRES_TK: xxxx
```

### Object Detector

CPU (no coral)

### Any other information that may be helpful

https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-nest
https://github.com/AlexxIT/go2rtc/tree/v1.9.4?tab=readme-ov-file#module-webrtc
https://docs.frigate.video/frigate/installation/#synology-nas-on-dsm-7 && https://docs.frigate.video/frigate/installation/#docker
https://support.google.com/googlenest/answer/9259110?hl=en#zippy=%2Cnest-cam-indoor
https://docs.frigate.video/configuration/live/#webrtc-extra-configuration
