### DISCUSSION TITLE
[General Support]: Frigate+ Suggestions double tag Person

### DISCUSSION THREAD

**Discussion by easez88** [blakeblackshear/frigate#15759] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When submitting an  image to  frigate+ and  using suggestions to verify person objects get tagged twice. 

### Steps to reproduce

1. Upload image with Person to frigate+
2.  go to frigate+ -> Images -> Suggestions
3. Click on image to annotate
4. Notice objects will be auto tagged, but person object will be tagged twice one on top of the other. 

### Version

0.15.0-87e7b62

### In which browser(s) are you experiencing the issue with?

Chrome

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    garage_camera_main:
      - rtsp://192.168.1.10:37543/e188fb1d94a19a5f
      - ffmpeg:garage_camera_main#audio-opus
    garage_camera_sub:
      - rtsp://192.168.1.10:37543/5118ac596e6cc4cb
      - ffmpeg:garage_camera_sub#audio-opus
    # front_yard_main:
    #   - rtsp://192.168.1.10:38907/3eada5689d44477d
    #   - ffmpeg:front_yard_main#audio-opus
    # front_yard_sub:
    #   - rtsp://192.168.1.10:38907/70137290d9d7bf6a
    #   - ffmpeg:front_yard_sub#audio-opus
    #doorbell_camera_main:
    #  - rtsp://192.168.1.10:38123/08ef344b2146876b
    #  - ffmpeg:doorbell_camera_main#audio-opus
    #doorbell_camera_sub:
    #  - rtsp://192.168.1.10:38123/864449cbf05bdcd3
    #  - ffmpeg:doorbell_camera_sub#audio-opus
  webrtc:
    candidates:
      - 192.121.232.119:8555
      - stun:8555

cameras:
  ##########################################################
  ## Garage Camera
  ##########################################################
  garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_camera_main
          roles:
            - record
        - path: rtsp://localhost:8554/garage_camera_sub
          roles:
            - detect
    motion:
      mask:
        - 0.612,0.923,1,0.923,1,0.973,0.611,0.975
        - 0,0,1,0,1,0.178,0,0.182
      threshold: 40
      contour_area: 15
      improve_contrast: true
    zones:
      driveway:
        coordinates: 
          0.939,1,0.636,0.89,0.542,0.846,0.372,0.762,0.258,0.705,0.216,0.642,0.111,0.682,0,0.734,0.037,1,0.234,1,0.93,1
        loitering_time: 0
        inertia: 3
      entryway:
        coordinates: 
          0.544,0.845,0.632,0.886,0.94,1,0.98,0.779,0.978,0.577,0.973,0.605,0.954,0.628,0.927,0.656,0.744,0.624
        loitering_time: 0
        inertia: 3
      front_yard:
        coordinates: 
          0.221,0.646,0.268,0.712,0.359,0.752,0.541,0.845,0.745,0.621,0.93,0.655,0.977,0.596,0.981,0.477,0.715,0.44
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0,0.725,0.235,0.638,0.45,0.545,0.61,0.484,0.738,0.427,0.731,0.39,0.633,0.426,0.56,0.446,0.415,0.496,0.224,0.567,0.117,0.601,0,0.645
        loitering_time: 3
        inertia: 3

  ##########################################################
  ## Front Yard
  ##########################################################
  front_yard_camera: # <------ Name the camera
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_yard_main
          roles:
            - record
        - path: rtsp://localhost:8554/front_yard_sub
          roles:
            - detect
    motion:
      mask:
        - 0.605,0.924,1,0.923,1,0.973,0.606,0.975
        - 0,0,1,0,1,0.144,0,0.14
      threshold: 45
      contour_area: 25
      improve_contrast: true
    zones:
      entryway:
        coordinates: 0.104,0.953,0.305,0.838,0.514,0.688,0.271,0.519,0.039,0.606,0.085,0.883
        loitering_time: 0
        inertia: 3
      driveway:
        coordinates: 
          0.046,0.603,0.275,0.519,0.429,0.459,0.647,0.408,0.503,0.369,0.356,0.393,0.198,0.445,0.034,0.5
        loitering_time: 0
        inertia: 3
      front_yard:
        coordinates: 
          0.282,0.521,0.38,0.589,0.517,0.683,0.384,0.789,0.197,0.901,0.101,0.954,0.106,1,1,1,1,0.53,0.647,0.403,0.426,0.461
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0.998,0.444,0.998,0.524,0.741,0.429,0.646,0.402,0.504,0.368,0.383,0.346,0.302,0.323,0.354,0.303,0.438,0.308,0.566,0.323,0.69,0.352,0.876,0.403
        loitering_time: 3

##########################################################
  ## Doorbell Camera
  ##########################################################
  doorbell_camera: # <------ Name the camera
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/doorbell_camera_main
          roles:
            - record
        - path: rtsp://localhost:8554/doorbell_camera_sub
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
    motion:
      mask:
        - 0.612,0.923,1,0.923,1,0.973,0.611,0.975
        - 0,0,1,0,1,0.178,0,0.182
      threshold: 45
      contour_area: 20
      improve_contrast: true
    zones:
      driveway:
        coordinates: 
          0.939,1,0.636,0.89,0.542,0.846,0.372,0.762,0.258,0.705,0.216,0.642,0.111,0.682,0,0.734,0.037,1,0.234,1,0.93,1
        loitering_time: 0
        inertia: 3
      entryway:
        coordinates: 
          0.544,0.845,0.632,0.886,0.94,1,0.98,0.779,0.978,0.577,0.973,0.605,0.954,0.628,0.927,0.656,0.744,0.624
        loitering_time: 0
        inertia: 3
      front_yard:
        coordinates: 
          0.221,0.646,0.268,0.712,0.359,0.752,0.541,0.845,0.745,0.621,0.93,0.655,0.977,0.596,0.981,0.477,0.715,0.44
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0,0.725,0.235,0.638,0.45,0.545,0.61,0.484,0.738,0.427,0.731,0.39,0.633,0.426,0.56,0.446,0.415,0.496,0.224,0.567,0.117,0.601,0,0.645
        loitering_time: 3
        inertia: 3

objects:
  track:
    - person
    - car
    - dog
    - cat

review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - car
      - cat
      - dog

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 15
  detections:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 7

detectors:
  coral:
    type: edgetpu
    device: usb
#  ov:
#    type: openvino
#    device: CPU

#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

auth:
  reset_admin_password: false
  trusted_proxies:
    - 192.121.0.0/16

mqtt:
  enabled: true
  host: 192.168.1.11
  port: 1883
  user: user
  password: pass
  stats_interval: 60

notifications:
  enabled: 'true'
  email: myemail@domain.com
semantic_search:
  enabled: true
  reindex: false
  model_size: small

version: 0.15-0

logger:
  default: debug
  logs:
    ffmpeg.garage_camera.detect: critical
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

This is related to frigate+ so I'm not including some  items, but I can if needed. Also, I don't want to  upload an example picture have some if needed.

Please forgive me if this was not the right place to add this.
