### DISCUSSION TITLE
[Config Support]: Storage Location Configuration

### DISCUSSION THREAD

**Discussion by dwdonnelly** [blakeblackshear/frigate#15760] [Config Support] [answered]
### Describe the problem you are having

Recordings are not appearing in the configured storage location.``

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg: #move the ffmpeg stuff to global level when using go2rtc
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy
go2rtc:
  streams:
    Front_Door: #change the IP and add user pass to the camera's rtsp info.
      - "ffmpeg:http://192.168.0.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"
      - rtsp://uid:pwd@192.168.0.42:8554/h264Preview_01_main
#    Front_Door_sub:
#      - "ffmpeg:http://192.168.0.42:8554/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"

cameras:
  Front_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door #this is a loopback ip to access the go2rtc stream, after the "/" is the camera name, defined in the go2rtc section. 8554 is the port used for rtsp restream. previously you had 8555, which is not right, that port is for the webrtc stuff, don't worry about that yet.
          roles:
            - record
#        - path: rtsp://127.0.0.1:8554/Front_Door_sub
#          roles:
#            - detect
    detect:
      enabled: True # Detection is enabled
      width: 896 #correct sub stream res
      height: 672 #correct sub stream res
      fps: 5 #limit the fps that the detector has to detect on.
    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion

version: 0.14
```

### Relevant Frigate log output

```shell
log appears normal
```

### Relevant go2rtc log output

```shell
log appears normal
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1-standard-arm64
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10 #Map the Pi hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: pwd
```

### Object Detector

CPU (no coral)

### Any other information that may be helpful

This newbie to Docker and Frigate would appreciate some help on storage configuration.
I have confirmed Frigate is recording.  The recordings are going to /opt/stacks/frigate-nvr/storage/recordings...date...hour...videos.

But as I understand, docker created these volumes:
 
 ```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
```

And so the storage location is the volume named: storage, which that location maps to /media/frigate

Now the path location:  /media/frigate does exist, but nothing is being recorded here.  All recordings are going to /opt/stacks/frigate-nvr/storage/recordings/(date)/(hour) folder(s).

Questions:  Why is it not going to /media/frigate?  How / why is the mapping wrong or not working?
Once I understand this mapping issue, I want to map the file storage to an external USB 8TB drive.

All help is appreciated - Happy and safe New Year.

**Comment by hawkeye217** [comment]
First, you should have a look at the official Getting Started Guide, specifically the section on setting up your docker-compose.yaml file: https://docs.frigate.video/guides/getting_started#setup-directories

You're incorrectly mapping the config folder.

You should also read up a bit more on Docker and volumes. The line in question:

` - ./storage:/media/frigate`

tells Docker to take a subdirectory on your host filesystem named "storage" and map it to the /media/frigate directory inside the Docker container.

**Comment by dwdonnelly** [comment]
@hawkeye217 Thanks for the quick reply.  I have been reading to understand.
Ok - first off, thanks - in my mind, I had this mapping backwards (I think):  ./storage:/media/frigate
So - for clarity, as I slowly walk into this, ./storage on my host system is actually or physically located here:  /opt/stacks/frigate-nvr/storage
The ./ id's the working directory which is in this case is: /opt/stacks/frigate-nvr
Correct?
And as you said, inside the Docker container, the directory: /media/frigate is being mapped to my host system's/opt/stacks/frigate-nvr/storage folder.  Correct?  (if true - I had this backwards in my mind.)

If all that is true, then to change the location the files are being saved to, I would change the docker-compose.yml from:

```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

to my new storage location:

```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./my-new-8TB-USB-drive-on-my-host-system:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

This will map the Docker container directory:  /media/frigate to ./my-new-8TB-USB-drive-on-my-host-system
Now - when I make this change, will I need to create the folders:  clips, exports and recordings or will the system automatically create them?
So the recorded savings behavior I am seeing - is correct.  The system is working as designed.  I had the mapping backwards.
I have been reading: https://docs.docker.com/engine/storage/volumes/
And I am still reading - Thanks !


ok - now the incorrect mapping of the config folder.
So in reading https://docs.frigate.video/guides/getting_started/#setup-directories, and the Docker Volumes guide, I have the following structure:

```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
but I should have this structure:

```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

I should be mapping the Docker container /config/config.yml to the host system's /opt/stacks/frigate-nvr/config folder
Correct?
I have not created the /opt/stacks/frigate-nvr/config folder as of yet......pending your feedback on my understanding.  When I do, I will need to copy the existing /opt/stacks/frigate-nvr/config.yml to the new /opt/stacks/frigate-nvr/config folder
I need to do this copying of the config.yml file because it was not originally setup correctly.    
Correct?

As I walk through this, I am making one change at a time.
First - if I am correct on the config.yml mapping issue, I will make that change and reboot my host system.
If that works, then I will work the new external USB 8TB drive change - in a few days.  More reading and testing to understand.

Thanks in advance for your help, guidance, and counsel.  Happy and Safe holidays.

**Reply by hawkeye217** [reply]
Yes, everything you discovered and offered as the solution is correct. Just one small caveat - the `./` in your suggested path names to the left of the colon indicates a path relative to the *current directory* because of the `.` at the beginning of the path. If you want to specify an absolute path, just remove the `.`.

So, your final mapping would look something like this:

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/stacks/frigate-nvr/config:/config
      - /my-new-8TB-USB-drive-on-my-host-system:/media/frigate
```

The only directory you'll have to create is `/opt/stacks/frigate-nvr/config`, where you'll place your `config.yml` file. Frigate will create the necessary directories under `/my-new-8TB-USB-drive-on-my-host-system` when you start it up.

**Reply by dwdonnelly** [reply]
@hawkeye217 As discussed...one step at a time. (and things did not go well.)  First change attempted: correct the config.yml mapping issue.

So first I changed the mapping in the docker-compose.yml file as follows:

```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/stacks/frigate-nvr/config:/config
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000

```

Then I created the config directory:  /opt/stack/frigate-nvr/config
Then I copied the config.yml file to /opt/stack/frigate-nvr/config
Then I renamed the original config.yml file located within the /opt/stack/frigate-nvr folder to config.yml-o
Confirmed all folder and file locations.
Rebooted the system.
Frigate not accessible via web page: 192.168.0.50:8971

Looking at the files and folders within /opt/stack/frigate-nvr, I see a "directory" called config.yml.  odd.  That was not there.
So I deleted the config.yml directory.  Verified all files and rebooted the system.

Same result.  Frigate would not work and the config.yml directory was back.
Then I recalled this sentence: "Frigate will create a config file if one does not exist on the initial startup." from https://docs.frigate.video/guides/getting_started/#setup-directories

That appears to be happening.

 So - just to confirm, I placed a copy of the config.yml file in the /opt/stack/frigate-nvr folder..... rebooted the system and all worked.

What am I missing or doing wrong?  Thanks in advance.
