### DISCUSSION TITLE
[Config Support]: No Alerts of Detections appearing under Review. NVIDIA GeForce RTX 3050 & TensorRT

### DISCUSSION THREAD

**Discussion by Jsalas424** [blakeblackshear/frigate#15763] [Config Support] [answered]
### Describe the problem you are having

There are 0 Alerts and Detections in the Review tab. Motion is being detected correctly. There are no errors in the logs and the GPU reflects a load. 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  Front-Door: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://username:password@lan_ip:554/cam/realmonitor?channel=1&subtype=1     # Update with your camera info (Normally the lower res stream, 1280*720 would be a good detection res)
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front-Door
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    motion:
      mask:
        - 0.061,0,0,0.162,0,0.549,0.059,0.479,0.071,0.361,0.436,0.284,0.776,0.31,0.999,0.376,0.999,0.007
        - 0.05,0.688,0.179,0.747,0.25,0.611,0.271,0.458,0.199,0.322,0.064,0.353,0.038,0.493
      threshold: 35
      contour_area: 20
      improve_contrast: 'true'
    zones:
      Front_Porch:
        coordinates: 
          0.523,0.883,0.529,0.772,0.621,0.77,0.658,0.864,0.74,0.876,0.788,0.995,0,1,0.001,0.805,0.082,0.74,0.276,0.843
        loitering_time: 0
        inertia: 3
      Street_and_Sidewalk:
        coordinates: 
          0.094,0.509,0.223,0.509,0.516,0.524,0.703,0.538,1,0.538,1,0.723,0.633,0.768,0.533,0.768,0.104,0.657
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Front_Porch
          - Street_and_Sidewalk
      detections:
        required_zones:
          - Front_Porch
          - Street_and_Sidewalk
go2rtc:
  streams:
    Front-Door:
      - rtsp://username:password@lan_ip:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
  webrtc:
    candidates:
      - lan_ip:8555
      - stun:8555

ffmpeg:
  hwaccel_args: preset-nvidia-h264
    #preset-nvidia
  output_args:
    record: preset-record-generic-audio-copy

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - dog
    - bicycle
    - car
    - motorcycle
    - cell phone


# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: enables detection for the camera (default: True)
  # NOTE: Motion detection is required for object detection,
  #       setting this to False and leaving detect enabled
  #       will result in an error on startup.
  enabled: true

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 1280
  height: 720

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  timestamp: true
  quality: 99

version: 0.14
```

### Relevant Frigate log output

```shell
2025-01-01 14:00:16.917512209  [INFO] Preparing Frigate...
2025-01-01 14:00:16.925992948  [INFO] Starting Frigate...
2025-01-01 14:00:18.221617005  [2025-01-01 14:00:18] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2025-01-01 14:00:18.221742759  [2025-01-01 14:00:18] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-01 14:00:18.241584228  [2025-01-01 14:00:18] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-01 14:00:18.381336446  [2025-01-01 14:00:18] peewee_migrate.logs            INFO    : Starting migrations
2025-01-01 14:00:18.381973771  [2025-01-01 14:00:18] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-01 14:00:18.398227516  [2025-01-01 14:00:18] frigate.app                    INFO    : Recording process started: 358
2025-01-01 14:00:18.404875887  [2025-01-01 14:00:18] frigate.app                    INFO    : Recording process started: 367
2025-01-01 14:00:18.406940461  [2025-01-01 14:00:18] frigate.app                    INFO    : go2rtc process pid: 105
2025-01-01 14:00:18.430544271  [2025-01-01 14:00:18] frigate.app                    INFO    : Output process started: 389
2025-01-01 14:00:18.442789617  [2025-01-01 14:00:18] frigate.app                    INFO    : Camera processor started for Front-Door: 401
2025-01-01 14:00:18.450861472  [2025-01-01 14:00:18] detector.tensorrt              INFO    : Starting detection process: 386
2025-01-01 14:00:18.522353304  [2025-01-01 14:00:18] frigate.app                    INFO    : Capture process started for Front-Door: 411
2025-01-01 14:00:18.561969298  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 72 MiB
2025-01-01 14:00:18.677761205  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 213, GPU 165 (MiB)
2025-01-01 14:00:18.681964792  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 215, GPU 175 (MiB)
2025-01-01 14:00:18.691280965  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +70, now: CPU 0, GPU 70 (MiB)
2025-01-01 14:00:18.691504203  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 143, GPU 167 (MiB)
2025-01-01 14:00:18.691570522  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 143, GPU 175 (MiB)
2025-01-01 14:00:18.691638875  [2025-01-01 14:00:18] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +15, now: CPU 0, GPU 85 (MiB)
2025-01-01 14:01:00.268988211  [2025-01-01 14:01:00] frigate.comms.dispatcher       INFO    : Setting motion threshold for Front-Door: 30
```

### Relevant go2rtc log output

```shell
2025-01-01 14:00:16.920186511  [INFO] Preparing new go2rtc config...
2025-01-01 14:00:17.174565590  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-01-01 14:00:17.217769678  [INFO] Starting go2rtc...
2025-01-01 14:00:17.325517672  14:00:17.325 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-01 14:00:17.325522420  14:00:17.325 INF config path=/dev/shm/go2rtc.yaml
2025-01-01 14:00:17.325911433  14:00:17.325 INF [api] listen addr=:1984
2025-01-01 14:00:17.325953464  14:00:17.325 INF [rtsp] listen addr=:8554
2025-01-01 14:00:17.326201195  14:00:17.326 INF [webrtc] listen addr=:8555
2025-01-01 14:00:26.917704389  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
  "cameras": {
    "Front-Door": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 10.1,
      "capture_pid": 411,
      "detection_enabled": true,
      "detection_fps": 0,
      "ffmpeg_pid": 421,
      "pid": 401,
      "process_fps": 10.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "93": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "95": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "96": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "97": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "105": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "113": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "114": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.9",
      "cpu_average": "5",
      "mem": "1.3"
    },
    "141": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "165": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "166": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "167": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "169": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "176": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "303": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "356": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "358": {
      "cmdline": "frigate.recording_manager",
      "cpu": "1.0",
      "cpu_average": "0",
      "mem": "0.7"
    },
    "367": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "385": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "386": {
      "cmdline": "frigate.detector.tensorrt",
      "cpu": "0.1",
      "cpu_average": "1",
      "mem": "1.8"
    },
    "389": {
      "cmdline": "frigate.output       ",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.6"
    },
    "401": {
      "cmdline": "frigate.process:Front-Door",
      "cpu": "1.7",
      "cpu_average": "4",
      "mem": "0.7"
    },
    "411": {
      "cmdline": "frigate.capture:Front-Door",
      "cpu": "1.6",
      "cpu_average": "1",
      "mem": "0.6"
    },
    "420": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "421": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.69.69:554/cam/realmonitor?channel=1&subtype=1 -r 10 -vf fps=10,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.4"
    },
    "428": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "429": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Front-Door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Front-Door@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "3148": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "3219": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "frigate.full_system": {
      "cpu": "2.2",
      "mem": "60.2"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "tensorrt": {
      "detection_start": 0,
      "inference_speed": 10.4,
      "pid": 386
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce RTX 3050": {
      "dec": "1.0%",
      "enc": "0.0%",
      "gpu": "0.0%",
      "mem": "8.41%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 105
    },
    "logger": {
      "pid": 356
    },
    "recording": {
      "pid": 358
    },
    "review_segment": {
      "pid": 367
    }
  },
  "service": {
    "last_updated": 1735740914,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 59.4,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 4.6
      },
      "/media/frigate/clips": {
        "free": 46452.6,
        "mount_type": "ext4",
        "total": 50088.5,
        "used": 1059.9
      },
      "/media/frigate/recordings": {
        "free": 46452.6,
        "mount_type": "ext4",
        "total": 50088.5,
        "used": 1059.9
      },
      "/tmp/cache": {
        "free": 950.3,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 3.4
      }
    },
    "temperatures": {},
    "uptime": 896,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Debian

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
root@frigate:/opt/frigate# cat docker-compose.yml
version: "3.9"
services:
  frigate:
    container_name: frigate
#    privileged: true # 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "64mb" # update for your cameras based on calculation above
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

<img width="1440" alt="Screen Shot 2025-01-01 at 9 11 24 AM" src="https://github.com/user-attachments/assets/341b55af-8e71-4d95-91d2-98a5a87009c1" />

**Comment by NickM-27** [comment, marked as answer]
```
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 1280
  height: 720
```

your config is incorrect. The height and width of this model is 320
