### DISCUSSION TITLE
[Detector Support]: Openvino on Arm crashes

### DISCUSSION THREAD

**Discussion by halabut69** [blakeblackshear/frigate#15766] [Detector Support] [answered]
### Describe the problem you are having

I'm having issues with the Openvino object detector on a rk3566 (yes, I know the rknn detector should be better, but I don't have a kernel with the rknpu driver).
Essentially it hangs and is restarted with the warning "detection appears to be stuck. restarting detection process..." continually. Setting the log level to debug doesn't give any more info.
The rk3566 is an Arm v8a architecture so should work with openvino.
I'm using docker compose with the 'default' compose.yaml from the frigate docs for the rockchip platform and the default config.yaml entry for openvino with 'GPU' changed to 'CPU' of course.
Any ideas?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

logger:
 default: debug
 # logs:
    #detector.ov: debug

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
  sync_recordings: true

snapshots:
  enabled: false
  retain:
    default: 30

#detectors:
 # cpu1:
 #   type: cpu
#    num_threads: 4

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-rk-h264

cameras:
  outside: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://camera:camera@192.168.1.101:554/stream1 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    motion:
      mask: 0,0.037,0.311,0.041,0.309,0.003,0.001,0.003
version: 0.14

objects:
  track:
    - person
    - bird
  #  - cat
  #  - dog
  #  - horse
  #  - cow
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
    privileged: true
    devices:
  - /dev/dri
  - /dev/dma_heap
  - /dev/rga
  - /dev/mpp_service
```

### Relevant Frigate log output

```shell
2025-01-01 13:18:21
frigate.watchdog
Detection appears to be stuck. Restarting detection process...
info
2025-01-01 13:18:21
root
Waiting for detection process to exit gracefully...
info
2025-01-01 13:18:22
detector.ov
Signal to exit detection process...
info
2025-01-01 13:18:22
detector.ov
Exited detection process...
info
2025-01-01 13:18:22
root
Detection process has exited...
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

Not available

### Any other information that may be helpful

Cpu load is 300% for the detector.[](url)
