### DISCUSSION TITLE
[Detector Support]: New install fails on loading tensorrt detector

### DISCUSSION THREAD

**Discussion by gouthamravee** [blakeblackshear/frigate#15772] [Detector Support] [answered]
### Describe the problem you are having

I was able to get this running with detector set to CPU, but when ever I change it to tensorrt frigate crashes and keeps restarting. I'm having the problem with current stable, 14 and beta 15 beta 4.

nvidia-smi output from the host
```
$ nvidia-smi
Thu Jan  2 00:59:17 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.142                Driver Version: 550.142        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro P1000                   Off |   00000000:02:00.0 Off |                  N/A |
| 34%   48C    P0             N/A /  N/A  |     143MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     54998      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg                140MiB |
+-----------------------------------------------------------------------------------------+
```

nvidia-smi from inside the container

```
root@velan:/opt/frigate# nvidia-smi
Thu Jan  2 00:59:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.142                Driver Version: 550.142        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro P1000                   Off |   00000000:02:00.0 Off |                  N/A |
| 34%   50C    P0             N/A /  N/A  |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### Version

0.15-beta4

### Frigate config file

```yaml
# Required
cameras:
  # Required: name of the camera
  driveway_left:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://USER:PASSWORD@10.10.10.11/cam/realmonitor?channel=1&subtype=0
          #roles:
          #  - detect
    #detect:
      #enabled: True

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

#model:
#  path: /config/model_cache/tensorrt/yolov7x-640.trt

ffmpeg:
  hwaccel_args: preset-nvidia

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: false

# Optional: Authentication configuration
auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    network_mode: host
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4-tensorrt
    shm_size: "500mb"
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=America/New_York
      #- YOLO_MODELS=yolov7x-640
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      #- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #  target: /mnt/cache
      #  tmpfs:
      #    size: 50000000000
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: all # number of GPUs
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | tensorrt model preparation disabled
frigate  | s6-rc: info: service trt-model-prepare successfully started
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2025-01-02 00:51:23.413073099  [INFO] Starting NGINX...
frigate  | 2025-01-02 00:51:23.413096444  [INFO] Preparing new go2rtc config...
frigate  | 2025-01-02 00:51:23.413095574  [INFO] Preparing Frigate...
frigate  | 2025-01-02 00:51:23.431795390  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2025-01-02 00:51:23.480570937  [INFO] Starting Frigate...
frigate  | 2025-01-02 00:51:24.317658907  [INFO] Starting go2rtc...
frigate  | 2025-01-02 00:51:24.472261494  00:51:24.472 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2025-01-02 00:51:24.472273900  00:51:24.472 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2025-01-02 00:51:24.475143887  00:51:24.475 INF [api] listen addr=:1984
frigate  | 2025-01-02 00:51:24.475689084  00:51:24.475 INF [rtsp] listen addr=:8554
frigate  | 2025-01-02 00:51:24.476078305  00:51:24.476 INF [webrtc] listen addr=:8555/tcp
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2025-01-02 00:51:27.150790688  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2025-01-02 00:51:27.286336004  127.0.0.1 - - [02/Jan/2025:00:51:27 -0500] "" 400 0 "-" "-" "-"
frigate  | 2025-01-02 00:51:28.368214296  2025/01/02 00:51:28 [error] 183#183: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate  | 2025-01-02 00:51:28.368223730  2025/01/02 00:51:28 [error] 183#183: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate  | 2025-01-02 00:51:30.617367960  [2025-01-02 00:51:30] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2025-01-02 00:51:30.634753369  [2025-01-02 00:51:30] frigate.util.config            INFO    : copying config as backup...
frigate  | 2025-01-02 00:51:30.641064984  [2025-01-02 00:51:30] frigate.util.config            INFO    : Migrating frigate config from 0.14 to 0.15-0...
frigate  | 2025-01-02 00:51:30.651064817  [2025-01-02 00:51:30] frigate.util.config            INFO    : Finished frigate config migration...
frigate  | 2025-01-02 00:51:32.198416554  [2025-01-02 00:51:32] frigate.app                    INFO    : Starting Frigate (0.15.0-87e7b62)
frigate  | 2025-01-02 00:51:32.219790008  [2025-01-02 00:51:32] frigate.app                    INFO    : Making backup of DB before migrations...
frigate  | 2025-01-02 00:51:32.224657559  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2025-01-02 00:51:32.260627955  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : Migrate "026_add_notification_tokens"
frigate  | 2025-01-02 00:51:32.260727691  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : add_column ('user', 'notification_tokens', <JSONField: User.notification_tokens>)
frigate  | 2025-01-02 00:51:32.264908485  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : Done 026_add_notification_tokens
frigate  | 2025-01-02 00:51:32.274232159  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : Migrate "027_create_explore_index"
frigate  | 2025-01-02 00:51:32.274422397  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : sql ('CREATE INDEX IF NOT EXISTS "event_label_start_time" ON "event" ("label", "start_time" DESC)',)
frigate  | 2025-01-02 00:51:32.275247260  [2025-01-02 00:51:32] peewee_migrate.logs            INFO    : Done 027_create_explore_index
frigate  | 2025-01-02 00:51:32.304833187  [2025-01-02 00:51:32] frigate.app                    INFO    : Recording process started: 371
frigate  | 2025-01-02 00:51:32.307358697  [2025-01-02 00:51:32] frigate.app                    INFO    : Review process started: 373
frigate  | 2025-01-02 00:51:32.313702320  [2025-01-02 00:51:32] frigate.app                    INFO    : go2rtc process pid: 99
frigate  | 2025-01-02 00:51:32.360248532  [2025-01-02 00:51:32] frigate.app                    INFO    : Output process started: 403
frigate  | 2025-01-02 00:51:32.392216008  [2025-01-02 00:51:32] detector.tensorrt              INFO    : Starting detection process: 387
frigate  | 2025-01-02 00:51:32.392799003  [2025-01-02 00:51:32] frigate.app                    INFO    : Camera processor started for driveway_left: 418
frigate  | 2025-01-02 00:51:32.410743771  [2025-01-02 00:51:32] frigate.app                    INFO    : Capture process started for driveway_left: 427
frigate  | 2025-01-02 00:51:32.623245164  [2025-01-02 00:51:32] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate  | 2025-01-02 00:51:32.764299855  Process detector:tensorrt:
frigate  | 2025-01-02 00:51:32.764311917  Traceback (most recent call last):
frigate  | 2025-01-02 00:51:32.764315007    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2025-01-02 00:51:32.764325222      self.run()
frigate  | 2025-01-02 00:51:32.764329014    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2025-01-02 00:51:32.764331554      return run(*args, **kwargs)
frigate  | 2025-01-02 00:51:32.764391031    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2025-01-02 00:51:32.764394334      self._target(*self._args, **self._kwargs)
frigate  | 2025-01-02 00:51:32.764397814    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
frigate  | 2025-01-02 00:51:32.764400591      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2025-01-02 00:51:32.764403226    File "/opt/frigate/frigate/object_detection.py", line 68, in __init__
frigate  | 2025-01-02 00:51:32.764405706      self.detect_api = create_detector(detector_config)
frigate  | 2025-01-02 00:51:32.764477437    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2025-01-02 00:51:32.764480970      return api(detector_config)
frigate  | 2025-01-02 00:51:32.764530078    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 243, in __init__
frigate  | 2025-01-02 00:51:32.764533432      self.engine = self._load_engine(detector_config.model.path)
frigate  | 2025-01-02 00:51:32.764536515    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 87, in _load_engine
frigate  | 2025-01-02 00:51:32.764538753      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
frigate  | 2025-01-02 00:51:32.764541358  TypeError: expected str, bytes or os.PathLike object, not NoneType
frigate  | 2025-01-02 00:51:32.764543958  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f97045b0700>
frigate  | 2025-01-02 00:51:32.764545927  Traceback (most recent call last):
frigate  | 2025-01-02 00:51:32.764594829    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 262, in __del__
frigate  | 2025-01-02 00:51:32.764597076      if self.outputs is not None:
frigate  | 2025-01-02 00:51:32.764598791  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate  | 2025-01-02 00:51:32.896470968  [2025-01-02 00:51:32] frigate.api.fastapi_app        INFO    : FastAPI started
frigate  | 2025-01-02 00:51:33.411325775  [INFO] Starting go2rtc healthcheck service...
```

### Install method

Proxmox via Docker

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

Can't navigate far enough in the UI because frigate keeps restarting.

**Comment by NickM-27** [comment, marked as answer]
You're missing the required model config that is shown in the docs

**Reply by gouthamravee** [reply]
Hi, do you mean 

```
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

I didn't realize that was required. Will add it and test.

**Reply by NickM-27** [reply]
yes, it is required

**Reply by gouthamravee** [reply]
Yup that worked, thank you. 

Its confusing that this section says 'optional' on the top level config and then required on the sublevel

```
# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320
```

I thought it was only required if the `model` section is defined at all.
