### DISCUSSION TITLE
[Support]: high cpu ussage on frigate 14.x

### DISCUSSION THREAD

**Discussion by Matthiasfranck** [blakeblackshear/frigate#15774] [General Support] [answered]
### Describe the problem you are having

I am running frigate in home assistant (HassOS) on an intel NUC With frigate 13.x I had no problems at all, CPU usage between 20%-30%. When updating to 14.1 (tried 14.0 as well) I see high (80%-90%) cpu usage.

I found [this](https://github.com/blakeblackshear/frigate/discussions/12614) discussion that looks very similar, however the solution is not working for me.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu:
#    type: cpu
#    num_threads: 2

go2rtc:
  streams:
    tuin_high:
      - rtsp://192.168.65.166:554/live/main
      #- ffmpeg:tuin_high#audio=aac
    tuin:
      - rtsp://192.168.65.166:554/live/sub
      #- ffmpeg:tuin_low#audio=aac
    voordeur: tapo://admin:0A363D640BACA4CA46F4B3AC29E1D407@192.168.65.148
      # - rtsp://tapovoordeur:abc123@192.168.65.148/stream1
      # - "ffmpeg:voordeur#audio=aac"

cameras:
  tuin:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/tuin_high
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuin
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 20
        retain:
          default: 10
          mode: motion
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 177,0,180,43,0,40,0,0
        - 0,217,704,81,704,0,0,0
        - 704,0,704,576,563,576,642,0
  tuin_high:
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/tuin_high
          input_args: preset-rtsp-restream
    detect:
      enabled: false
    snapshots:
      enabled: true
  voordeur:
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/voordeur
    detect:
      enabled: false
version: 0.14
```

### Relevant Frigate log output
In the frigate UI I can see
```shell
Voordeur has high FFMPEG CPU usage (47%)
```

### Relevant go2rtc log output

```shell
/
```

### FFprobe output from your camera

```shell
/
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
/
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

/
