### DISCUSSION TITLE
[Config Support]: Events can be several hours long

### DISCUSSION THREAD

**Discussion by easez88** [blakeblackshear/frigate#15784] [Config Support] [answered]
### Describe the problem you are having

I recently upgrated to frigate+ and started using my own model. Since then, I'm having an issue where frigate will begin capturing an event and never stop. For example I have an alert that started at 5:30 PM and ended at 9:30  PM. I set the threshold to 0.7. If I set it to 0.8 I start missing alerts. Any ideas	

### Version

0.15.0-87e7b62

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    garage_camera_main:
      - rtsp://192.121.232.182:37543/e188fb1d94a19a5f
      - ffmpeg:garage_camera_main#audio-opus
    garage_camera_sub:
      - rtsp://192.121.232.182:37543/5118ac596e6cc4cb
      - ffmpeg:garage_camera_sub#audio-opus
  webrtc:
    candidates:
      - 192.121.232.119:8555
      - stun:8555

cameras:
  ##########################################################
  ## Garage Camera
  ##########################################################
  garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_camera_main
          roles:
            - record
        - path: rtsp://localhost:8554/garage_camera_sub
          roles:
            - detect
    motion:
      mask:
        - 0.612,0.923,1,0.923,1,0.973,0.611,0.975
        - 0,0,1,0,1,0.128,0,0.121
      threshold: 40
      contour_area: 20
      improve_contrast: true
    zones: {}
  front_yard_camera: # <------ Name the camera
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_yard_main
          roles:
            - record
        - path: rtsp://localhost:8554/front_yard_sub
          roles:
            - detect
    motion:
      mask:
        - 0.605,0.924,1,0.923,1,0.973,0.606,0.975
        - 0,0,1,0,1,0.144,0,0.14
      threshold: 45
      contour_area: 25
      improve_contrast: true
    zones:
      entryway:
        coordinates: 0.104,0.953,0.305,0.838,0.514,0.688,0.271,0.519,0.039,0.606,0.085,0.883
        loitering_time: 0
        inertia: 3
      driveway:
        coordinates: 
          0.046,0.603,0.275,0.519,0.429,0.459,0.647,0.408,0.503,0.369,0.356,0.393,0.198,0.445,0.034,0.5
        loitering_time: 0
        inertia: 3
      front_yard:
        coordinates: 
          0.282,0.521,0.38,0.589,0.517,0.683,0.384,0.789,0.197,0.901,0.101,0.954,0.106,1,1,1,1,0.53,0.647,0.403,0.426,0.461
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0.998,0.444,0.998,0.524,0.741,0.429,0.646,0.402,0.504,0.368,0.383,0.346,0.302,0.323,0.354,0.303,0.438,0.308,0.566,0.323,0.69,0.352,0.876,0.403
        loitering_time: 3


objects:
  track:
    - person
    - car
    - dog
    - cat
    - usps
    - ups
    - amazon
    - fedex
  filters:
    person:
      threshold: 0.7
    car:
      threshold: 0.7
review:
  alerts:
    labels:
      - person
      - usps
      - ups
      - amazon
      - fedex
  detections:
    labels:
      - car
      - cat
      - dog

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 15
  detections:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 7

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://6929875d17f22d0ee7a61b4c277e9039

auth:
  reset_admin_password: false
  trusted_proxies:
    - 192.121.0.0/16

mqtt:
  enabled: true
  host: 192.121.242.143
  port: 1883
  user: user
  password: pass
  stats_interval: 60

notifications:
  enabled: 'true'
  email: myemail@domain.tld
semantic_search:
  enabled: true
  reindex: false
  model_size: small

version: 0.15-0

logger:
  default: error
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Frigate stats

```json
{"cameras":{"garage_camera":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.2,"detection_enabled":true,"pid":431,"capture_pid":436,"ffmpeg_pid":1353,"audio_rms":0.0,"audio_dBFS":0.0},"front_yard_camera":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":null,"capture_pid":null,"ffmpeg_pid":0,"audio_rms":0.0,"audio_dBFS":0.0},"doorbell_camera":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":null,"capture_pid":null,"ffmpeg_pid":0,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":6.42,"detection_start":0.0,"pid":390}},"detection_fps":0.2,"gpu_usages":{"intel-vaapi":{"gpu":"0.29%","mem":"-%","clients":{"1353":"0.84%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"1.4","mem":"10.4"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"86":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"2.4","cpu_average":"2","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"106":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"1.9","cpu_average":"3","mem":"1.1","cmdline":"python3 -u -m frigate"},"123":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"165":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"166":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"167":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"168":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"170":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"323":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"374":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.recording_manager"},"380":{"cpu":"0.1","cpu_average":"0","mem":"0.5","cmdline":"frigate.review_segment_manager"},"390":{"cpu":"0.1","cpu_average":"0","mem":"0.6","cmdline":"frigate.detector.coral"},"392":{"cpu":"0.1","cpu_average":"0","mem":"2.1","cmdline":"frigate.embeddings_manager"},"416":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.output       "},"431":{"cpu":"3.2","cpu_average":"5","mem":"0.6","cmdline":"frigate.process:garage_camera"},"436":{"cpu":"1.3","cpu_average":"0","mem":"0.5","cmdline":"frigate.capture:garage_camera"},"539":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"546":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"1353":{"cpu":"2.7","cpu_average":"2","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garage_camera_sub -r 5 -vf fps=5,scale_vaapi=w=896:h=512,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"1355":{"cpu":"0.7","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garage_camera_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage_camera@%Y%m%d%H%M%S%z.mp4"},"1773":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"1863":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":524,"version":"0.15.0-87e7b62","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":10099492.0,"used":464133.0,"free":9635359.0,"mount_type":"nfs"},"/media/frigate/clips":{"total":10099492.0,"used":464133.0,"free":9635359.0,"mount_type":"nfs"},"/tmp/cache":{"total":953.7,"used":6.7,"free":947.0,"mount_type":"tmpfs"},"/dev/shm":{"total":512.0,"used":34.0,"free":478.0,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1735844003},"processes":{"recording":{"pid":374},"review_segment":{"pid":380},"go2rtc":{"pid":98},"embeddings":{"pid":392}}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    network_mode: host
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8981:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "frigatertsppassword"
      PLUS_API_KEY: "frigateapikey"
volumes:
  config:
  media:
```

### Object Detector

Coral
