### DISCUSSION TITLE
[HW Accel Support]: EdgeTPU not detected, any way to test in host?

### DISCUSSION THREAD

**Discussion by twinoijsdrfg** [blakeblackshear/frigate#15787] [Hardware Acceleration Support]
### Describe the problem you are having

My Coral TPU isn't being detected and Frigate will not boot when it is in use.

Is there anyway of testing the Coral TPU in the host without having to get the old version of Python as it's proving tricky to do with the latest Debian? I just want to confirm that my TPU is working before I start troubleshooting my container.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: cpu #This is currently cpu for testing but it was edgetpu

cameras:
  Tapo:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://cam:password@cameraip
          input_args:
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
          roles:
            - detect
    detect:
      enabled: true
      width: 2304
      height: 1296
      fps: 5
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: "no" # unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256m"  # Set shared memory size
    volumes:
      - ./config:/config
      - ./storage:/mnt/CCTV/storage
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      #- "8554:8554" # RTSP feeds

    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
      - /dev/dri/renderD128:/dev/dri/renderD128  # For GPU acceleration
    userns_mode: "host"
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Tapo

### Screenshots of the Frigate UI's System metrics pages

n/a
