### DISCUSSION TITLE
[Support]: Frigate doesn't fully start / boot-loops with a partially invalid `go2rtc` config

### DISCUSSION THREAD

**Discussion by kquinsland** [blakeblackshear/frigate#15783] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have a few camera / stream sources that I only need to enable sometimes. There's currently no way to do this "cleanly" (see [issue 1911](https://github.com/blakeblackshear/frigate/issues/1911)) so I have a crude reminder to go in and (un-)comment the streams in/out as needed.

Today that reminder went off and so I took a moment to \re-enable a few streams. When I went to the web UI to do so... I was not  able to get in.
The cached assets loaded but the loading spinner never went away.  After waiting for ~ 30 seconds, I poped in to take a look at the logs and saw this in a loop:

```shell
$ sudo journalctl -xfeu frigate.service
<...>
07:50:39.948019707  [INFO] Preparing new go2rtc config...
07:50:40 nvr docker[1910633]: Traceback (most recent call last):
07:50:40 nvr docker[1910633]:   File "/usr/local/go2rtc/create_config.py", line 119, in <module>
07:50:40 nvr docker[1910633]:     for name in go2rtc_config.get("streams", {}):
07:50:40 nvr docker[1910633]: TypeError: 'NoneType' object is not iterable
07:50:40 nvr docker[1910633]: 2025-01-02 07:50:40.312766254  [INFO] The go2rtc service exited with code 1 (by signal 0)
07:50:41 nvr docker[1910633]: 2025-01-02 07:50:41.339949587  [INFO] Preparing new go2rtc config...

<... repeat ...>
```

So I took a look at the config and this is what I had:

(see below)

**The issue**:

The `.get()` call has a default of `{}` which is defensive programming (good!) but it doesn't account for the case when the yaml file looks like the one below:

```yaml
go2rtc:
  streams:
  # Nothing here so `go2rtc.streams == None`
```

_A fix_ would be to first run the config file through something like [voluptuous](https://pypi.org/project/voluptuous/) or [pydantic](https://pypi.org/project/pydantic/). 

### Steps to reproduce

1. Stop frigate
2. Modify config so the `go2rtc.streams` object is empty / otherwise parses into `None`
3. Start frigate
4. Observe crash-loop as the `go2rtc` configu is never instantiated / boot never finishes

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# <...>
go2rtc:
  # Note: as of right now, there's no support for dynamically turning cameras on/off.
  # As to not waste bandwidth and energy, we have to manually (ugh!) en/disable
  #   the feeds when needed
  #
  # See: https://github.com/blakeblackshear/frigate/issues/1911
  ##
  streams:
    #mjpeg_src_1: "ffmpeg:https://someVeryLongURLHere.com#video=h264#hardware" 
    #mjpeg_src_2: "ffmpeg:https://someVeryLongURLHere.com#video=h264#hardware" 
    #mjpeg_src_3: "ffmpeg:https://someVeryLongURLHere.com#video=h264#hardware" 
    #mjpeg_src_4: "ffmpeg:https://someVeryLongURLHere.com#video=h264#hardware" 
    #mjpeg_src_5: "ffmpeg:https://someVeryLongURLHere.com#video=h264#hardware" 

# <...>

cameras:
  # See above note about having to manually turn these on/off.
  # Frigate will complain, but not break, if the streams are not available so don't bother commenting the blocks below out
  # Note: not bothering with object detection on these; just recording
  mjpeg_src_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_src_1
          roles:
            - record

  mjpeg_src_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_src_2
          roles:
            - record

  # And the other 3 here; you get the idea....

  otherCamera1:
    onvif:
      # <...>
  # More cameras here; they're all onvif so no pre-encode to rtsp needed


ui:
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour
  time_format: 24hour
  # iso8601 style
  strftime_fmt: '%Y-%m-%d %H:%M'

# We still pin the version in the systemd file to prevent a restart pulling updated version
version: 0.14
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
```

### docker-compose file or Docker CLI command

```yaml
ExecStart=/usr/bin/docker run --rm --name %n \
    --env-file /etc/frigate/secrets \
    --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
    --device /dev/dri/renderD128 \
    --device /dev/apex_0:/dev/apex_0 \
    --device /dev/apex_1:/dev/apex_1 \
    --shm-size=256m \
    --cap-add=CAP_PERFMON \
    -v /mnt/frigate/storage:/media/frigate \
    -v /mnt/frigate/config:/config \
    -v /etc/localtime:/etc/localtime:ro \
    -p 80:5000 \
    -p 1935:1935 \
    "ghcr.io/blakeblackshear/frigate:0.14.1"
```

### Relevant Frigate log output

```shell
(see above)
```

### Relevant go2rtc log output

```shell
(see above)
```

### Operating system

Other

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

N/A

### Screenshots of the Frigate UI's System metrics pages

N/A

**Comment by NickM-27** [comment]
This is not a bug, if go2rtc config is invalid and can't be started then Frigate will not be able to start. Also, Frigate already uses pydantic but we can not have a schema for go2rtc as we do not control go2rtc and users are allowed to use custom versions of go2rtc which may not always have consistent schemas with the current version included in Frigate.

**Reply by NickM-27** [reply]
Also just one additional note, I don't think there is really a reason to comment out the go2rtc streams because they are not used by default. They would only be used when you interact with them directly. 

It would be far easier to simply add `enabled` to the camera and change them all between `true` and `false` vs commenting things out.

For example:

```
cameras:
  mjpeg_src_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_src_1
          roles:
            - record

  mjpeg_src_2:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_src_2
          roles:
            - record
```
