### DISCUSSION TITLE
[Support]: Review thumbnails not loading

### DISCUSSION THREAD

**Discussion by Razielza** [blakeblackshear/frigate#15794] [General Support]
### Describe the problem you are having

I am having an issue where review thumbnails to not load, however hovering over them shows the brief clip before going into the event and loading the full clip 

![image](https://github.com/user-attachments/assets/fbe4c423-4252-488a-b107-79720c34f17b)

### Version

version: 0.15-0

### What browser(s) are you using?

Google chrome, firefox

### Frigate config file

```yaml
auth:
  enabled: true
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - <IP>

mqtt:
  host: <IP>
  user: 
  password: 

model:
  path: <nope>


objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 1200
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 1.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.70


snapshots:
  enabled: true

go2rtc:
  streams:
    Wisteria: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Greenhouse: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Path: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Porch: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Gate: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Yard: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Garage: # <- for RTSP streams
      - rtsp://<IP> # <- stream which supports video & aac audio
    Side: # <- for RTSP streams
      - rtsp://<IP>

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous
  restream: true

detect:
  enabled: true
  max_disappeared: 300

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 7
    pre_capture: 15
    post_capture: 20
  detections:
    retain:
      days: 7
    pre_capture: 15
    post_capture: 20
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  contour_area: 30

cameras:
  Wisteria:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask: 0,0,0.334,0,0.639,0,0.611,0.135,0.334,0.173,0.331,1,0,1,0,0.202
      threshold: 40
      contour_area: 40
      improve_contrast: 'true'
    objects:
      filters:
        person:
          mask: 0.332,1,0,1,0,0,0.334,0
    zones:
      Inside:
        coordinates: 0.764,0.345,0.69,0.523,0.799,0.768,0.899,0.487
        objects: person
        inertia: 3
      Notify:
        coordinates: 0.47,0.173,0.378,0.185,0.386,1,0.778,1
        inertia: 3
        objects: person
    review:
      detections: {}
      alerts:
        required_zones: Notify
  Greenhouse:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080


    motion:
      threshold: 40
      contour_area: 40
      improve_contrast: 'true'
  Porch:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080


  Side:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080


  Path:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080


  Gate:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080



    zones:
      Notify:
        coordinates: 
          0.002,0.904,0.137,0.707,0.237,0.581,0.279,0.5,0.328,0.398,0.767,0.406,1,0.538,0.993,0.997,0.003,0.997
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: Notify
      detections:
        required_zones: Notify
    motion:
      threshold: 40
      contour_area: 40
      improve_contrast: 'true'
  Yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080

    motion:
      mask: 0,0,0.694,0,0.382,0.37,0,0.625
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://<IP>
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080

version: 0.15-0
```

### Relevant Frigate log output

```shell
No logs/errors found
```

### Relevant go2rtc log output

```shell
No logs/errors found
```

### FFprobe output from your camera

```shell
Not related to camera
```

### Frigate stats

```json
{"cameras":{"Wisteria":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.1,"detection_enabled":true,"pid":612,"capture_pid":671,"ffmpeg_pid":680,"audio_rms":0.0,"audio_dBFS":0.0},"Greenhouse":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":613,"capture_pid":679,"ffmpeg_pid":684,"audio_rms":0.0,"audio_dBFS":0.0},"Porch":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.3,"detection_enabled":true,"pid":621,"capture_pid":687,"ffmpeg_pid":695,"audio_rms":0.0,"audio_dBFS":0.0},"Side":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.3,"detection_enabled":true,"pid":629,"capture_pid":692,"ffmpeg_pid":697,"audio_rms":0.0,"audio_dBFS":0.0},"Path":{"camera_fps":5.0,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.4,"detection_enabled":true,"pid":637,"capture_pid":696,"ffmpeg_pid":702,"audio_rms":0.0,"audio_dBFS":0.0},"Gate":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":645,"capture_pid":701,"ffmpeg_pid":710,"audio_rms":0.0,"audio_dBFS":0.0},"Yard":{"camera_fps":5.0,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":7.9,"detection_enabled":true,"pid":653,"capture_pid":706,"ffmpeg_pid":713,"audio_rms":0.0,"audio_dBFS":0.0},"Garage":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":661,"capture_pid":711,"ffmpeg_pid":722,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":23.75,"detection_start":1735905617.7185,"pid":31466}},"detection_fps":9.0,"cpu_usages":{"frigate.full_system":{"cpu":"17.9","mem":"19.6"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"18":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"85":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"101":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"102":{"cpu":"5.1","cpu_average":"4","mem":"1.2","cmdline":"python3 -u -m frigate"},"106":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"167":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"168":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"169":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"170":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"177":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"304":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"388":{"cpu":"6.9","cpu_average":"7","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"498":{"cpu":"1.7","cpu_average":"2","mem":"0.4","cmdline":"frigate.recording_manager"},"502":{"cpu":"1.0","cpu_average":"1","mem":"0.3","cmdline":"frigate.review_segment_manager"},"530":{"cpu":"22.4","cpu_average":"21","mem":"0.4","cmdline":"frigate.output       "},"535":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"542":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"549":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"556":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"564":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"571":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"578":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"585":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"592":{"cpu":"4.9","cpu_average":"4","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"612":{"cpu":"1.7","cpu_average":"2","mem":"0.4","cmdline":"frigate.process:Wisteria"},"613":{"cpu":"1.4","cpu_average":"1","mem":"0.5","cmdline":"frigate.process:Greenhouse"},"621":{"cpu":"2.3","cpu_average":"3","mem":"0.5","cmdline":"frigate.process:Porch"},"629":{"cpu":"2.7","cpu_average":"2","mem":"0.5","cmdline":"frigate.process:Side "},"637":{"cpu":"2.9","cpu_average":"2","mem":"0.5","cmdline":"frigate.process:Path "},"645":{"cpu":"1.4","cpu_average":"2","mem":"0.5","cmdline":"frigate.process:Gate "},"653":{"cpu":"23.9","cpu_average":"3","mem":"0.5","cmdline":"frigate.process:Yard "},"661":{"cpu":"1.3","cpu_average":"2","mem":"0.4","cmdline":"frigate.process:Garage"},"671":{"cpu":"2.9","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Wisteria"},"679":{"cpu":"2.9","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Greenhouse"},"680":{"cpu":"22.8","cpu_average":"22","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Wisteria -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Wisteria@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"684":{"cpu":"26.9","cpu_average":"26","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Greenhouse -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Greenhouse@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"687":{"cpu":"2.7","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Porch"},"692":{"cpu":"2.9","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Side "},"695":{"cpu":"26.5","cpu_average":"28","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Porch -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Porch@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"696":{"cpu":"2.7","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Path "},"697":{"cpu":"31.1","cpu_average":"30","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Side@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"701":{"cpu":"2.4","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Gate "},"702":{"cpu":"24.5","cpu_average":"26","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Path -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Path@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"706":{"cpu":"2.5","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Yard "},"710":{"cpu":"22.5","cpu_average":"23","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Gate -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Gate@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"711":{"cpu":"2.7","cpu_average":"2","mem":"0.4","cmdline":"frigate.capture:Garage"},"713":{"cpu":"25.8","cpu_average":"26","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Yard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Yard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"722":{"cpu":"28.4","cpu_average":"27","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"22043":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"22325":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"},"31466":{"cpu":"4.1","cpu_average":"2","mem":"1.1","cmdline":"frigate.detector.coral"}},"service":{"uptime":180548,"version":"0.15.0-87e7b62","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":17163366.7,"used":7333003.6,"free":9830363.1,"mount_type":"fuse.shfs"},"/media/frigate/clips":{"total":17163366.7,"used":7333003.6,"free":9830363.1,"mount_type":"fuse.shfs"},"/tmp/cache":{"total":953.7,"used":11.7,"free":942.0,"mount_type":"tmpfs"},"/dev/shm":{"total":256.0,"used":174.7,"free":81.3,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1735905617},"processes":{"recording":{"pid":498},"review_segment":{"pid":502},"go2rtc":{"pid":388}}}
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
Hosted on Unraid
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision cd2

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c6c8efe4-e31a-4140-9d07-112d2a8a37a9)
