### DISCUSSION TITLE
[Support]:  HASS Supervised, Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied).

### DISCUSSION THREAD

**Discussion by khalidaboelmagd** [blakeblackshear/frigate#15790] [General Support] [answered]
### Describe the problem you are having

I have frigate  0.15 Beta 4, as add-on on Home Assistant supervised under Debian 12,
intel GPU TOP is working fine but I'm getting   Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied).
it is NOT affecting the system but it would be nice to get GPU status in frigate 

### Version

0.15-beta4

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqttuser
  password: mqttuser
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
  enabled: true

database:
  path: /config/frigate.db

detectors:
  ov:
    type: openvino
    device: GPU

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    camera-1:
      - rtsp://
    doorbell:
      - rtsp://

cameras:
  camera-1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-1
          roles:
            - record
            - detect
            - audio
    detect:
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
        - truck
        - dog
        - cat
        - cycle
      filters:
        person:
          min_area: 800
          max_area: 25000
          threshold: 0.6
        car:
          min_area: 800
          max_area: 20000
          threshold: 0.65
        motorcycle:
          min_area: 500
          max_area: 18000
          threshold: 0.6
        bicycle:
          min_area: 400
          max_area: 15000
          threshold: 0.6
        truck:
          min_area: 1000
          max_area: 30000
          threshold: 0.65
        dog:
          min_area: 300
          max_area: 12000
          threshold: 0.6
        cat:
          min_area: 200
          max_area: 10000
          threshold: 0.6
        cycle:
          min_area: 400
          max_area: 15000
          threshold: 0.6
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      alerts:
        retain:
          days: 60
        pre_capture: 15
        post_capture: 20
      detections:
        retain:
          days: 30
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 90
    motion:
      threshold: 43
      contour_area: 35
      improve_contrast: true
      mask:
        - 0.995,0,0.723,0,0.73,0.039,0.747,0.147,0.755,0.191,0.765,0.269,0.761,0.33,0.771,0.388,0.793,0.472,0.805,0.513,0.803,0.555,0.804,0.593,0.814,0.634,0.867,0.678,0.905,0.702,0.997,0.726
        - 0,0.002,0.261,0,0.255,0.191,0,0.29
        - 0.717,0,0.748,0.148,0.253,0.184,0.264,0
    zones:
      kia:
        coordinates:
          0.636,0.372,0.633,0.331,0.623,0.297,0.613,0.281,0.6,0.273,0.58,0.27,0.565,0.275,0.552,0.295,0.547,0.31,0.546,0.345,0.548,0.379,0.567,0.395,0.595,0.406,0.628,0.404
        inertia: 3
        loitering_time: 0
      face:
        coordinates:
          0,0.322,0.1,0.312,0.394,0.382,0.647,0.41,0.781,0.472,0.817,0.993,0.005,0.994,0.002,0.413
        inertia: 3
        loitering_time: 0
        objects: person
    audio:
      enabled: true
    review:
      detections: {}
      alerts:
        required_zones: kia
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - record
            - audio
    detect:
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.6
        cat:
          threshold: 0.6
        dog:
          threshold: 0.6
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      alerts:
        retain:
          days: 60
        pre_capture: 15
        post_capture: 25
      detections:
        retain:
          days: 30
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 90
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.629,0,0.138,0,0.015,0,0.184,0.328,0.345,0.27
    zones:
      door:
        coordinates: 1,0,0.634,0.002,0.57,0.571,0.569,0.869,0.528,0.923,0.522,0.997,0.989,0.984
        inertia: 3
        loitering_time: 0
        objects:
          - person
    audio:
      enabled: true
    review:
      detections: {}
      alerts:
        required_zones: door

semantic_search:
  enabled: true
  reindex: false
  model_size: large
version: 0.15-0
```

### Relevant Frigate log output

```shell
Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied).
```

### Relevant go2rtc log output

```shell
not related
```

### FFprobe output from your camera

```shell
not related
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
add on on HA supervised
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

reolink
