### DISCUSSION TITLE
[Camera Support]: PTZ camera main feed not working for live

### DISCUSSION THREAD

**Discussion by andrewb106** [blakeblackshear/frigate#15798] [Camera Support]
### Describe the problem you are having

I recently set up an inexpensive Panoeagle PTZ camera in Frigate. I've had it set up feeding into a separate Hikvision NVR (which I have all of my Frigate cameras going to as a backup/recording all motion 24/7). I have ONVIF set up for the camera in Frigate and the PTZ controls work fine.

Issue I am having is that Frigate is only displaying the substream in live. I have the main stream set up in Go2RTC just like all of my other cameras, and have the live stream set up to point towards the Go2RTC adaption of the main stream. Nothing seems different than any other camera.

I have tested the main stream feed in VLC and it pops up and works fine there. So the stream I listed for the PTZ camera under Go2RTC is verified to work. I tried turning off the connection in my Hikvision NVR to make sure two main stream pulls was not too much for the camera but it didn't change anything.  I don't have this PTZ camera set up to record in Frigate as it's pointed at a high traffic roadway and I prefer to record to the Hikvision NVR and simply use the Frigate stream for live viewing.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
go2rtc:
  streams:
    Doorbell_Camera: ###
    Doorbell_Camera_Rotated: ###
    Doorbell_Camera_Sub: ###
    Doorbell_Camera_Sub_Rotated: ###
    Southeast_Camera: ###
    Back_Porch_Camera: ###
    Basement_Camera: ###
    Back_Yard_Camera: ###
    Driveway_Camera: ###
    South_Camera: ###
    PTZ_Camera: rtsp://xxx.xxx.xx.xx:554/h264?username=username&password=mypassword


  PTZ_Camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx.xx.xx.xx:554/h264cif?username=username&password=mypassword
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/PTZ_Camera
          roles:
            - record
    record:
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 2
          mode: active_objects
    snapshots:
      enabled: true
    onvif:
        host: xxx.xxx.xx.xx
        port: 80
        user: username
        password: mypassword
    live:
      stream_name: PTZ_Camera
```

### Relevant Frigate log output

```shell
nothing relevant
```

### Relevant go2rtc log output

```shell
nothing relevant
```

### FFprobe output from your camera

```shell
Not sure how to check FFprobe in .14?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Panoeagle PTZ Camera

### Screenshots of the Frigate UI's System metrics pages

![System Cameras](https://github.com/user-attachments/assets/877e7ddb-abff-492a-83c0-13eb55cbaa7b)
![System General](https://github.com/user-attachments/assets/b5011a2e-8055-4003-bc5e-289596f90f43)
