### DISCUSSION TITLE
[Config Support]: Event previews on Live page not showing.

### DISCUSSION THREAD

**Discussion by Herpgon** [blakeblackshear/frigate#15806] [Config Support] [answered]
### Describe the problem you are having

Events are being created on the live view but I cannot see the preview.
![image](https://github.com/user-attachments/assets/9797744c-f038-4d7a-8a71-b382f207e5fa)
When I click the review page I can hover the mouse over the video and it will scrub through
![image](https://github.com/user-attachments/assets/33efe941-59a9-451a-8326-f70862d26055)
but when I click the video from the review page I get a spinning cursor.
![image](https://github.com/user-attachments/assets/5cf107eb-6cb6-4b4d-be06-ed1d23d72497)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
version: 0.14
tls:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

mqtt:
  enabled: true
  host: 192.168.1.50
  port: 1883
  user: mquser
  password: password
  topic_prefix: frigate

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    front_door: ffmpeg:rtsp://<user>:<password>@192.168.1.139:554?subtype=media_profile2
    street: ffmpeg:rtsp://<user>:<password>@192.168.1.142:554?subtype=media_profile2
    side: ffmpeg:rtsp://<user>:<password>@192.168.1.138:554?subtype=media_profile2
    back_room: ffmpeg:rtsp://<user>:<password>@192.168.1.141:554?subtype=media_profile2
    front_room: ffmpeg:rtsp://<user>:<password>@192.168.1.140:554?subtype=media_profile2
    baby_room: ffmpeg:rtsp://<user>:<password>@192.168.1.143:554?subtype=media_profile2

cameras:
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1080
      height: 1920
    motion:
      mask: 0,0,0.002,0.236,0.511,0.102,0.727,0
    zones:
      entryway:
        coordinates: 0,0.245,0.388,0.145,1,0.302,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
        required_zones: entryway
      detections:
        required_zones: entryway
    snapshots:
      enabled: true
      required_zones:
        - entryway
      timestamp: true
      bounding_box: true
      retain:
        default: 2

  street:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
        required_zones:
          - yard
          - streetarea
          - driveway
      detections:
        required_zones:
          - yard
          - driveway
          - streetarea
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - yard
        - driveway
        - streetarea
      retain:
        default: 2

    motion:
      mask: 
        0.432,0.582,0.257,0.462,0.271,0.001,0.998,0.002,0.997,0.051,0.762,0.049,0.634,0.454,0.536,0.543,0.498,0.542,0.474,0.582
    zones:
      yard:
        coordinates: 
          0,0.628,0.045,0.624,0.086,0.64,0.113,0.655,0.142,0.669,0.16,0.682,0.177,0.692,0.22,0.708,0.271,0.727,0.334,0.736,0.392,0.749,0.437,0.75,0.581,0.757,0.783,1,0,1
        loitering_time: 0
      driveway:
        coordinates: 0.553,0.721,0.75,0.675,1,0.798,0.997,0.996,0.79,1
        loitering_time: 0
      streetarea:
        coordinates: 
          0,0.582,0.153,0.668,0.24,0.707,0.402,0.742,0.519,0.749,0.572,0.752,0.764,0.665,0.847,0.628,0.924,0.596,0.963,0.562,0.841,0.546,0.863,0.581,0.759,0.591,0.656,0.591,0.53,0.592,0.419,0.584,0.302,0.576,0.199,0.564,0.122,0.543,0,0.523
        loitering_time: 0

  side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1080
      height: 1920
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
        required_zones: sidegate
      detections:
        required_zones: sidegate
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - sidegate
      retain:
        default: 2
    motion:
      mask: 0.002,0.003,0,0.197,0.612,0.178,0.685,0.16,0.729,0.157,0.81,0.156,0.782,0.003
    zones:
      sidegate:
        coordinates: 0,0.202,0.621,0.183,0.673,0.168,0.738,0.161,0.855,0.168,1,0.207,1,1,0,1
        loitering_time: 0
        inertia: 3

  back_room:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_room
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion: {}
  front_room:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_room
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion: {}
  baby_room:
    detect:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/baby_room
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion: {}
```

### Relevant Frigate log output

```shell
2025-01-03 18:29:56.250800882  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 976
2025-01-03 18:29:56.250868948  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 968
2025-01-03 18:30:06.259787922  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 976
2025-01-03 18:30:06.259817787  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 968
2025-01-03 18:30:16.269870820  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 976
2025-01-03 18:30:16.270080820  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 968
2025-01-03 18:30:26.278827995  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 976
2025-01-03 18:30:26.278880804  [h264 @ 0x7f6d6c0f7fc0] SEI type 5 size 1344 truncated at 968
2025-01-03 18:30:36.286675399  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:30:36.286766513  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:30:46.295808264  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:30:46.295871575  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:30:56.304300349  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:30:56.304324324  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:31:06.313744512  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:31:06.313877734  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:31:16.322805561  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:31:16.322840707  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:31:26.331627105  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:31:26.331691779  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:31:36.340263425  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:31:36.340293923  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:31:46.349329967  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:31:46.349405880  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:31:56.358340056  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:31:56.358369450  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:32:06.367760454  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:32:06.367827680  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:32:16.377042101  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:32:16.377111623  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:32:26.385532136  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:32:26.385659196  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:32:36.394533508  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:32:36.394545004  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:32:46.403475603  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:32:46.403575278  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:32:56.413664617  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:32:56.413897186  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
2025-01-03 18:33:06.422172391  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 976
2025-01-03 18:33:06.422336849  [h264 @ 0x7f6d6c336900] SEI type 5 size 1344 truncated at 968
```

### Relevant go2rtc log output

```shell
2025-01-03 18:08:37.874663507  [INFO] Preparing new go2rtc config...
2025-01-03 18:08:38.147383193  [INFO] Starting go2rtc...
2025-01-03 18:08:38.229220212  18:08:38.229 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-03 18:08:38.229223198  18:08:38.229 INF config path=/dev/shm/go2rtc.yaml
2025-01-03 18:08:38.229789633  18:08:38.229 INF [api] listen addr=:1984
2025-01-03 18:08:38.229791753  18:08:38.229 INF [rtsp] listen addr=:8554
2025-01-03 18:08:38.229869680  18:08:38.229 INF [webrtc] listen addr=:8555/tcp
2025-01-03 18:08:47.872559969  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"baby_room":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":536,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":547,"pid":484,"process_fps":5.1,"skipped_fps":0.0},"back_room":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":518,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":542,"pid":476,"process_fps":5.1,"skipped_fps":0.0},"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":488,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":514,"pid":456,"process_fps":5.0,"skipped_fps":0.0},"front_room":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":526,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":541,"pid":483,"process_fps":5.0,"skipped_fps":0.0},"side":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":510,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":521,"pid":472,"process_fps":5.0,"skipped_fps":0.0},"street":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":498,"detection_enabled":true,"detection_fps":5.2,"ffmpeg_pid":513,"pid":459,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"103":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"108":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"117":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"1.5","cpu_average":"1","mem":"0.3"},"123":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"12825":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"131":{"cmdline":"python3 -u -m frigate","cpu":"4.1","cpu_average":"4","mem":"6.8"},"151":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"177":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"178":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"179":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"180":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"183":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"2117":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(56)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"27":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"320":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"338":{"cmdline":"sleep 9999","cpu":"0.0","cpu_average":"0","mem":"0.0"},"36":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"367":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.2"},"37":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"38":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"39":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"40":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"410":{"cmdline":"frigate.recording_manager","cpu":"2.3","cpu_average":"3","mem":"1.8"},"419":{"cmdline":"frigate.review_segment_manager","cpu":"0.5","cpu_average":"0","mem":"1.7"},"42":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"43":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"438":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(67)","cpu":"0.2","cpu_average":"0","mem":"0.1"},"439":{"cmdline":"frigate.detector.tensorrt","cpu":"1.7","cpu_average":"1","mem":"3.2"},"44":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"442":{"cmdline":"frigate.output       ","cpu":"4.1","cpu_average":"4","mem":"2.0"},"45":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"456":{"cmdline":"frigate.process:front_door","cpu":"0.5","cpu_average":"0","mem":"2.0"},"459":{"cmdline":"frigate.process:street","cpu":"1.8","cpu_average":"1","mem":"1.8"},"46":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"472":{"cmdline":"frigate.process:side ","cpu":"0.5","cpu_average":"1","mem":"2.0"},"476":{"cmdline":"frigate.process:back_room","cpu":"0.8","cpu_average":"0","mem":"1.7"},"483":{"cmdline":"frigate.process:front_room","cpu":"0.8","cpu_average":"0","mem":"1.7"},"484":{"cmdline":"frigate.process:baby_room","cpu":"0.8","cpu_average":"0","mem":"1.7"},"488":{"cmdline":"frigate.capture:front_door","cpu":"1.3","cpu_average":"1","mem":"1.7"},"498":{"cmdline":"frigate.capture:street","cpu":"0.5","cpu_average":"0","mem":"1.7"},"510":{"cmdline":"frigate.capture:side ","cpu":"1.2","cpu_average":"1","mem":"1.7"},"513":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/street -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/street@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.3","cpu_average":"1","mem":"1.5"},"514":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1080:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"1.5"},"517":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1080x1920 -i pipe: -threads 1 -f mpegts -s 405x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"518":{"cmdline":"frigate.capture:back_room","cpu":"5.3","cpu_average":"4","mem":"1.8"},"521":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=1080:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.0","cpu_average":"2","mem":"1.6"},"522":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.142:554?subtype=media_profile2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1d99b1c4dc1df85c9b5aaf8e5c68f6b3","cpu":"0.4","cpu_average":"0","mem":"0.2"},"524":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.139:554?subtype=media_profile2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/e5ceb208457d4485c3703a5f0f621b4f","cpu":"0.7","cpu_average":"0","mem":"0.2"},"526":{"cmdline":"frigate.capture:front_room","cpu":"4.9","cpu_average":"4","mem":"1.8"},"532":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"535":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.138:554?subtype=media_profile2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/d81940ab55b289a98fb573c4e2ef92f8","cpu":"0.8","cpu_average":"0","mem":"0.2"},"536":{"cmdline":"frigate.capture:baby_room","cpu":"5.5","cpu_average":"5","mem":"1.8"},"541":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_room -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.9","cpu_average":"6","mem":"1.8"},"542":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_room -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.1","cpu_average":"7","mem":"1.9"},"547":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/baby_room -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/baby_room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_cuda=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.1","cpu_average":"6","mem":"1.8"},"554":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.141:554?subtype=media_profile2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/24d26144e372bea358b29a282f26a94c","cpu":"0.7","cpu_average":"0","mem":"0.2"},"556":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.140:554?subtype=media_profile2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/30b44be93d2e32db9f86f1cc2c322f3e","cpu":"0.8","cpu_average":"0","mem":"0.2"},"558":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.143:554?subtype=media_profile2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/14292e7145f9f3b5b07788245fc7bf11","cpu":"0.5","cpu_average":"0","mem":"0.2"},"561":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1080x1920 -i pipe: -threads 1 -f mpegts -s 405x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"566":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"1","mem":"0.3"},"57":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"571":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"1","mem":"0.3"},"576":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"58":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"581":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"frigate.full_system":{"cpu":"13.5","mem":"44.2"}},"detection_fps":5.2,"detectors":{"tensorrt":{"detection_start":0.0,"inference_speed":2.77,"pid":439}},"gpu_usages":{"NVIDIA RTX A2000":{"dec":"0.0%","enc":"0.0%","gpu":"0.0%","mem":"57.91%"}},"processes":{"go2rtc":{"pid":117},"logger":{"pid":367},"recording":{"pid":410},"review_segment":{"pid":419}},"service":{"last_updated":1735958222,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":466.2,"mount_type":"tmpfs","total":512.0,"used":45.8},"/media/frigate/clips":{"free":877530.8,"mount_type":"ext4","total":937553.0,"used":12325.2},"/media/frigate/recordings":{"free":877530.8,"mount_type":"ext4","total":937553.0,"used":12325.2},"/tmp/cache":{"free":856.1,"mount_type":"tmpfs","total":953.7,"used":97.6}},"temperatures":{},"uptime":1692,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    runtime: nvidia
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - ./config:/config
      - /data/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      NVIDIA_VISIBLE_DEVICES: 0
      NVIDIA_DRIVER_CAPABILITIES: all
    networks:
      - athena-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=athena-proxy
      - traefik.http.routers.frigate-http.rule=Host(`frigate.jays-place.com`)
      - traefik.http.routers.frigate-http.entrypoints=http
      - traefik.http.routers.frigate-http.middlewares=https-redirect@file
      - traefik.http.routers.frigate-https.rule=Host(`frigate.jays-place.com`)
      - traefik.http.routers.frigate-https.entrypoints=https
      - traefik.http.routers.frigate-https.tls=true
      - traefik.http.routers.frigate-https.tls.certresolver=cloudflare
      - traefik.http.services.frigate.loadbalancer.server.port=8971
      - traefik.http.routers.frigate-https.middlewares=secured@file
networks:
  athena-proxy:
    external: true
```

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/1a2c41d4-a859-4d84-9256-b9915f3f9c9e)
