### DISCUSSION TITLE
[Config Support]: Please help with config after Frigate-Update

### DISCUSSION THREAD

**Discussion by albotroz** [blakeblackshear/frigate#15815] [Config Support] [answered]
### Describe the problem you are having

I have indeed read in changelog before updating that the latest Frigate Hass update leads to WebRTC changes.
I thought I could fix it then, but unfortunately I can't get it to look like it did before.

What should I do or change to make it look like it did before the update - apart from restoring backups and not running Frigate updates?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.178.23
  port: 1883
  user: ####
  password: ####

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

birdseye:
  enabled: false
  restream: false
  width: 1280
  height: 720
  quality: 15
  mode: continuous

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: false
  crop: false
  retain:
    default: 5
  quality: 100

go2rtc:
  streams:
    front:
# Copy of the stream which transcodes audio to opus
      - ffmpeg:http://192.168.178.185/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=####&password=#####video=copy
    front_sub:
# Copy of the stream which transcodes audio to opus
      - ffmpeg:http://192.168.178.185/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=####&password=#####video=copy
    hof:
# Stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - rtsp://####:####@192.168.178.31:554/11
    hof_sub:
# Stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - rtsp://####:####@192.168.178.31:554/12
    garage:
# Stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - rtsp://####:####@192.168.178.183:554/11
    garage_sub:
# Stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - rtsp://####:####@192.168.178.183:554/12

  webrtc:
    candidates:
      - 192.168.178.23:8555
      - stun:8555

timestamp_style:
  position: tl
  format: '%d.%m.%Y %H:%M:%S'
  color:
    red: 255
    green: 140
    blue: 0
  thickness: 2
#  effect: solid

#####################################################
# Camera Front - Reolink E1 Outdoor PoE via PoE
#####################################################

cameras:
  front:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        # Stream Low Res
        - path: rtsp://127.0.0.1:8554/front_sub
          roles:
            - detect
        # Stream High Res
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record

    detect:
      width: 640
      height: 360
      fps: 4
      enabled: true

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 2
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: motion

    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.6
        dog:
          threshold: 0.6

    review:
      alerts:
        required_zones: front_street_in
      detections:
        required_zones:
          - front_street_in
          - front_street_out
    zones:
      front_street_in:
        coordinates: 1,0.105,1,0.652,0.326,1,0,0.996,0.004,0.335
        inertia: 3
        loitering_time: 0
      front_street_out:
        coordinates: 1,0.633,0.995,0.987,0.294,1
        inertia: 3
        loitering_time: 0

#####################################################
# Camera Hof - upCam Tornado HD S via WLAN
#####################################################

  hof:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        # Stream Low Res
        - path: rtsp://127.0.0.1:8554/hof_sub
          roles:
            - detect
        # Stream High Res
        - path: rtsp://127.0.0.1:8554/hof
          roles:
            - record

    detect:
      width: 640
      height: 352
      fps: 5
      enabled: true

    record:
      enabled: true
      expire_interval: 60
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: motion

    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7

#####################################################
# Camera Garage - SV3C HX03 via WLAN
#####################################################

  garage:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        # Stream Low Res
        - path: rtsp://127.0.0.1:8554/garage_sub
          roles:
            - detect
        # Stream High Res
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - record

    detect:
      width: 640
      height: 352
      fps: 5
      enabled: true

    record:
      enabled: true
      expire_interval: 60
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: motion

    objects:
      track:
        - person
      mask: 0.764,0.936,0.691,1,0.586,0.98,0.587,0.51,0.737,0.42,0.974,0.488
      filters:
        person:
          threshold: 0.7

    review:
      alerts:
        required_zones: garage_street
      detections:
        required_zones: garage_street

    zones:
      garage_street:
        coordinates: 0.273,1,0.201,0.51,0.441,0.435,0.58,0.422,0.577,1,0.442,1
        inertia: 3
        loitering_time: 0

#####################################################
ui:
  timezone: Europe/Berlin
  time_format: 24hour
  date_style: full
  time_style: medium
  strftime_fmt: '%d/%m/%Y %H:%M'


version: 0.14
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

https://github.com/user-attachments/assets/8f83f597-904f-4300-b735-57079290f75b

### Any other information that may be helpful

kiosk_mode:
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
title: Home
views:
  - title: FRIGATECARD
    path: frigatecard
    subview: false
    type: sidebar
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.hof
                title: Hof SD
                frigate:
                  camera_name: hof_sub
                triggers:
                  occupancy: false
                  motion: true
                  entities:
                    - binary_sensor.hof_all_occupancy
                dependencies:
                  cameras:
                    - hof_sub
                webrtc_card: {}
                go2rtc:
                  modes: []
                live_provider: go2rtc
              - camera_entity: camera.hof
                title: Hof HD
                live_provider: go2rtc
                id: hof_sub
                hide: true
            menu:
              style: hidden
              buttons:
                substreams:
                  icon: mdi:high-definition
                expand:
                  enabled: false
            view:
              default: live
              camera_select: live
              dark_mode: 'off'
              update_seconds: 5
              timeout_seconds: 10
              update_force: true
              scan:
                enabled: true
                untrigger_seconds: 10
            live:
              preload: true
              auto_mute: all
              auto_pause: never
              auto_play: all
              lazy_load: false
              controls:
                next_previous: {}
              layout:
                fit: fill
              microphone:
                disconnect_seconds: 2
            media_gallery:
              controls:
                thumbnails:
                  show_details: true
            media_viewer:
              auto_pause: hidden
              auto_mute: all
              auto_play: never
            image:
              layout: {}
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.garage
                title: Garage SD
                frigate:
                  camera_name: garage_sub
                triggers:
                  occupancy: false
                  motion: true
                  entities:
                    - binary_sensor.garage_all_occupancy
                dependencies:
                  cameras:
                    - garage_sub
                webrtc_card: {}
                go2rtc:
                  modes: []
                live_provider: go2rtc
              - camera_entity: camera.garage
                title: Garage HD
                live_provider: go2rtc
                id: garage_sub
                hide: true
            menu:
              style: hidden
              buttons:
                substreams:
                  icon: mdi:high-definition
                expand:
                  enabled: false
            view:
              default: live
              camera_select: live
              dark_mode: 'off'
              update_seconds: 5
              timeout_seconds: 10
              update_force: true
              scan:
                enabled: true
                untrigger_seconds: 10
            live:
              preload: true
              auto_mute: all
              auto_pause: never
              auto_play: all
              lazy_load: false
              controls:
                next_previous: {}
              layout:
                fit: fill
              microphone:
                disconnect_seconds: 2
            media_gallery:
              controls:
                thumbnails:
                  show_details: true
            media_viewer:
              auto_pause: hidden
              auto_mute: all
              auto_play: never
            image:
              layout: {}
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.front
                title: Front SD
                frigate:
                  camera_name: front_sub
                triggers:
                  occupancy: false
                  motion: true
                  entities:
                    - binary_sensor.front_all_occupancy
                dependencies:
                  cameras:
                    - front_sub
                webrtc_card: {}
                go2rtc:
                  modes: []
                live_provider: go2rtc
              - camera_entity: camera.front
                title: Front HD
                live_provider: go2rtc
                id: front_sub
                hide: true
            menu:
              style: hidden
              buttons:
                substreams:
                  icon: mdi:high-definition
                expand:
                  enabled: false
            view:
              default: live
              camera_select: live
              dark_mode: 'off'
              update_seconds: 5
              timeout_seconds: 10
              update_force: true
              scan:
                enabled: true
                untrigger_seconds: 10
            live:
              preload: true
              auto_mute: all
              auto_pause: never
              auto_play: all
              lazy_load: false
              controls:
                next_previous: {}
              layout:
                fit: fill
              microphone:
                disconnect_seconds: 2
            media_gallery:
              controls:
                thumbnails:
                  show_details: true
            media_viewer:
              auto_pause: hidden
              auto_mute: all
              auto_play: never
            image:
              layout: {}
        view_layout:
          position: main
      - square: false
        type: grid
        columns: 3
        cards:
          - type: picture
            image_entity: image.hof_person
          - type: picture
            image_entity: image.front_person
          - type: picture
            image_entity: image.garage_person
