### DISCUSSION TITLE
[Config Support]: Active objects and regions despite no motion

### DISCUSSION THREAD

**Discussion by ki9us** [blakeblackshear/frigate#15816] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have one camera that is always recording because it always thinks there are active objects in the scene, even with no motion.  Note the large green "active region" box in the screenshot.  This camera always has a [red border in live view](https://github.com/blakeblackshear/frigate/discussions/14257#discussioncomment-10898841).  

![](https://github.com/user-attachments/assets/0ae8856a-1ea3-40c9-b0f6-7bb8bbf20746)

I've tried turning the motion threshold all the way up to no avail. 

### Steps to reproduce

I have a feeling this is caused by the large number of cars in the scene.  It has trouble telling how many cars are across the street (six really) and the object boxes jitter around which might cause them to be treated as active objects.  

I've also tried disabling car detection in the "across street" zone, but that doesn't help.  

![zone](https://github.com/user-attachments/assets/28d27297-3189-4122-8a60-f081e01950f1)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
version: 0.14

tls:
  enabled: false

ffmpeg:
  input_args: preset-rtsp-restream
  # https://docs.frigate.video/configuration/hardware_acceleration/#amdati-gpus-radeon-hd-2000-and-newer-gpus-via-libva-mesa-driver
  hwaccel_args: preset-vaapi # AMD GPU

snapshots:
  enabled: true

# https://docs.frigate.video/configuration/birdseye/
birdseye:
  enabled: true
  mode: continuous
#  restream: true

# Use PCIe Coral
# https://docs.frigate.video/configuration/object_detectors#single-pciem2-coral
detectors:
  coral:
    type: edgetpu
    device: pci:0

# https://docs.frigate.video/configuration/record
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
detect:
  enabled: true
  #width: 1280
  #height: 720
motion:
  enabled: true
  improve_contrast: true

mqtt:
  host: mosquitto
  user: frigate
  password: NOTAREALPASSWORD
  client_id: frigate

go2rtc:
  streams:
    frontyard:
      - rtsp://frigate:NOTAREALPASSWORD@192.168.1.2/cam/realmonitor?channel=1&subtype=0
    backyard:
      - rtsp://frigate:NOTAREALPASSWORD@192.168.1.3/stream1
    driveway:
      - rtsp://frigate:NOTAREALPASSWORD@192.168.1.4/cam/realmonitor?channel=1&subtype=0

cameras:
  frontyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: 
            rtsp://frigate:NOTAREALPASSWORD@192.168.1.2/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    audio:
      enabled: false
      listen:
        - speech
        - scream
        - yell
        - glass
        - gunshot
        - emergency_vehicle
    record:
      events:
        objects:
          - person
          - face
          - license_plate
          - amazon
          - fedex
          - ups
          - package
          - bicycle
          - car
          - dog
          - cat
    review:
      alerts:
        required_zones: frontyard_property
      detections:
        required_zones:
          - frontyard_property
          - frontyard_sidewalk
    zones:
      frontyard_property:
        coordinates: 0,1,0.174,0.365,0.489,0.232,0.84,0.105,1,0.26,1,1
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - package
        inertia: 3
      frontyard_sidewalk:
        coordinates: 
          0.752,0.032,0.752,0.144,0.494,0.229,0.171,0.369,0.13,0.08,0.094,0.11,0,0.351,0,0.19,0.126,0.087,0.299,0,0.762,0
        loitering_time: 0
        inertia: 3
    motion:
      improve_contrast: true
      mask: 
        0.563,0.184,0.521,0.523,0.424,0.219,0.304,0.115,0.289,0,1,0,1,0.259,0.882,0.136,0.853,0.374,0.811,0.357,0.829,0.101,0.75,0.03,0.768,0,0.643,0
      threshold: 35
      contour_area: 10
    objects:
      track:
        - person
        - face
        - package
        - amazon
        - fedex
        - ups
        - dog
        - car
        - cat
        - bicycle
      filters:
        person:
          min_score: 0.65
          threshold: 0.75
        dog:
          min_score: 0.5
          threshold: 0.7
        bicycle:
          min_score: 0.4
          threshold: 0.5
        cat:
          min_score: 0.4
          threshold: 0.5
        car:
          min_score: 0.4
          threshold: 0.5
        license_plate:
          min_score: 0.5
        face:
          min_score: 0.5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://frigate:NOTAREALPASSWORD@192.168.1.3/stream2
          roles:
            - detect
    audio:
      enabled: false
    record:
      events:
        objects:
          - person
          - dog
          - cat
          - face
    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true
      mask: 
        0.956,0.642,1,0.63,1,0,0,0,0.001,0.157,0.163,0.086,0.171,0.158,0.198,0.089,0.279,0.079,0.43,0.078,0.55,0.086,0.683,0.112,0.793,0.148,0.835,0.18,0.83,0.291,0.855,0.317,0.908,0.246,0.977,0.308,0.913,0.46
    review:
      detections:
        labels:
          - person
          - dog
          - cat
      alerts:
        required_zones: backyard_property
    zones:
      backyard_property:
        coordinates: 
          0.256,0.199,0.259,0.085,0.385,0.081,0.524,0.087,0.699,0.122,0.793,0.153,1,0.323,1,1,0,1,0,0.172,0.169,0.097,0.235,0.089,0.236,0.199
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - face
        - dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.75
        face:
          min_score: 0.5
        dog:
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: 
            rtsp://frigate:NOTAREALPASSWORD@192.168.1.4/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    audio:
      enabled: false
      listen:
        - speech
        - scream
        - yell
        - glass
        - gunshot
        - emergency_vehicle
    record:
      retain:
        mode: active_objects
      events:
        objects:
          - person
          - face
          - license_plate
          - amazon
          - fedex
          - ups
          - package
          - bicycle
          - car
          - dog
          - cat
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
      mask: 
        0.217,0.344,0.17,0.435,0,0.743,0,0,1,0,1,0.409,0.95,0.422,0.897,0.409,0.855,0.329,0.814,0.252,0.818,0.196,0.748,0.196,0.608,0.189,0.419,0.193,0.297,0.21,0.245,0.348
    review:
      alerts:
        required_zones: driveway_property
      detections:
        required_zones:
          - driveway_sidewalk
          - driveway_road
          - driveway_property
    zones:
      driveway_road:
        coordinates: 
          0.205,0.221,0.208,0.281,0.406,0.248,0.666,0.242,0.804,0.248,0.815,0.203,0.642,0.19,0.412,0.195
        inertia: 3
        loitering_time: 0
      driveway_property:
        coordinates: 
          0.787,0.474,0.802,0.259,1,0.41,1,1,0.999,0.996,1,1,0,1,0,0.265,0.198,0.143,0.212,0.365,0.256,0.363,0.263,0.476
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - package
          - person
      driveway_adjacent:
        coordinates: 
          0.206,0.219,0.201,0.113,0.374,0.072,0.574,0.067,0.747,0.084,0.891,0.101,0.855,0.203,0.682,0.188,0.423,0.19
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
      driveway_sidewalk:
        coordinates: 
          0.782,0.478,0.262,0.472,0.259,0.353,0.21,0.365,0.21,0.288,0.429,0.251,0.682,0.247,0.794,0.249
        loitering_time: 0
        inertia: 3
    objects:
      track:
        - person
        - face
        - package
        - amazon
        - fedex
        - ups
        - license_plate
        - dog
        - car
        - cat
        - bicycle
      filters:
        person:
          min_score: 0.65
          threshold: 0.75
        dog:
          min_score: 0.5
          threshold: 0.7
        bicycle:
          min_score: 0.4
          threshold: 0.5
        cat:
          min_score: 0.4
          threshold: 0.5
        car:
          min_score: 0.4
          threshold: 0.5
        license_plate:
          min_score: 0.5
        face:
          min_score: 0.5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
networks:
  frigate:
    name: frigate
    ipam:
      config:
        - subnet: '172.16.2.0/24'
  nginx:
    external: true
  homeassistant:
    external: true
  mqtt:
    external: true
services:

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    privileged: true
    networks:
      frigate:
      nginx:
      mqtt:
      homeassistant:
    environment:
      TZ: America/Denver
      # https://docs.frigate.video/configuration/hardware_acceleration/#amdati-gpus-radeon-hd-2000-and-newer-gpus-via-libva-mesa-driver
      LIBVA_DRIVER_NAME: radeonsi # AMD GPU
      FRIGATE_RTSP_PASSWORD: 'NOTAREALPASSWORD'
      PLUS_API_KEY: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    volumes:
      - '/etc/frigate:/config'
      - '/var/spool/frigate:/media/frigate'
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    # https://docs.frigate.video/frigate/installation#calculating-required-shm-size
    shm_size: "200MB"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # CPU intel hwaccel
      - /dev/dri/card0:/dev/dri/card0 # AMD Radeon GPU
      - /dev/apex_0:/dev/apex_0 # PCIe Coral
    ports:
      # WebRTC
      # https://docs.frigate.video/configuration/live#webrtc-extra-configuration
      - "8555:8555/tcp"
      - "8555:8555/udp"
      # RTSP restream
      - "554:8554/tcp"
      - "554:8554/udp"
```

### Relevant Frigate log output

```shell
No errors, no logs.  
Can provide verbose output on request.
```

### Relevant go2rtc log output

```shell
No error
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW2439SP-SA-LED-S2

### Screenshots of the Frigate UI's System metrics pages

![dash1](https://github.com/user-attachments/assets/8b9b2a52-613d-4416-b22b-13d6a1006c34)
![dash2](https://github.com/user-attachments/assets/d1a9973b-5079-4020-b0b0-1cd265234519)
![dash3](https://github.com/user-attachments/assets/9df94196-c3a6-4e7a-88b4-1f9ff69edb4d)
![dash4](https://github.com/user-attachments/assets/285ca70c-60c2-4d73-97fb-599d8ca69d8d)

**Comment by NickM-27** [comment]
This is not a bug, Frigate actively tracks objects. In this case there appear to be some small objects in the top right that are not being detected continuously so Frigate keeps sending regions to see if they are still there. In this case a min_area filter of 500 or so will likely solve the issue.

**Reply by ki9us** [reply]
It wasn't just the small size of the objects.  When several cars parked alongside each other, it struggled to tell where one car ends and the next begins.  The constantly changing object boxes were treated as active.  

This was happening with all cars in the parking lot, not just the tiny ones.  So I had to set `min_area` to 1500 to block all the cars across the street that can group up.  This still allows detecting cars driving past or entering the driveway.

**Comment by ki9us** [comment, marked as answer]
Although setting `min_area` worked to block out the cars across the street, I've also had success by dropping the `detect: stationary: threshold` for that camera: 

```yaml
cameras:
  driveway:
    detect:
      stationary:
        threshold: 5 # default: 50
```

From [the docs](https://docs.frigate.video/configuration/stationary_objects/#tuning-stationary-behavior): 

> `threshold` is the number of frames an object needs to remain relatively still before it is considered stationary.

This makes frigate think everything is stationary

![nocar](https://github.com/user-attachments/assets/e24b85d9-f8b9-4b39-b1bb-e9b064655ce3)

But it still gets overruled by the motion detector, so driving cars still activate detection.  

![car](https://github.com/user-attachments/assets/eb3c6c05-2ecc-49ff-a6a4-9701d7e73c3f)

The advantage to this is that I can still track cars across the street, and nerd out about it with homeassistant.  🤓

![cars](https://github.com/user-attachments/assets/b6d2758d-778e-425c-89d7-fbac0ec6207c)

The disadvantage (and reason this is not a bug) is explained better in [the docs](https://docs.frigate.video/configuration/stationary_objects/#why-does-frigate-track-stationary-objects): 

> One might simply think "Why not just run object detection any time there is motion around the driveway area and notify if the bounding box is in that zone?"
> 
> With that approach, what video is related to the car that entered the driveway? Did it come from the left or right? Was it parked across the street for an hour before turning into the driveway? 

With this setting, a car parked across the street for an hour would not be detected (or recorded) as long as it's not moving.
