### DISCUSSION TITLE
[Support]: Alerts Generated Outside of Zone

### DISCUSSION THREAD

**Discussion by ph0nebooth** [blakeblackshear/frigate#15822] [General Support] [answered]
### Describe the problem you are having

I am facing an issue where alerts are being generated for detections outside of a zone. I have the Driveway camera set to alert within the zone Driveway_Main and every other detection will show regardless of zone (but won't alert).

The detection's bounding box was well outside my defined zone; however, an alert was generated.

I have attached some screenshots.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Safari MacOS 18.2 (20620.1.16.11.8)

### Frigate config file

```yaml
objects:
  track:
    - person
    - car
tls:
  enabled: false

mqtt:
  enabled: true
  host: 192.168.178.253

auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.16.0.0/12 # <---- this is the subnet for the internal docker compose network
    - 192.168.0.0./16

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14 # <- number of days to keep event recordings
      mode: active_objects
snapshots:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc
  streams:
    Doorbell:
      - rtsp://admin:[redacted]@192.168.178.120:554/h264Preview_01_sub
      - ffmpeg:Doorbell#audio=opus
    #Doorbell:
     # - ffmpeg:http://192.168.178.120/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=[redacted]#video=copy#audio=copy#audio=opus
     # - ffmpeg:Doorbell#audio=opus
     # - rtsp://192.168.178.120/Preview_01_sub
    #Doorbell_sub:
      #- ffmpeg:http://192.168.178.120/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]
    Driveway:
      - rtsp://cctv:[redacted]@192.168.178.203:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:Driveway#audio=opus
      - rtsp://cctv:[redacted]@192.168.178.203:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://cctv:[redacted]@192.168.178.203:554/cam/realmonitor?channel=1&subtype=2#backchannel=0
      - ffmpeg:Driveway_sub#audio=opus
    Terrace:
      - rtsp://cctv:[redacted]@192.168.178.202:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:Terrace#audio=opus
      - rtsp://cctv:[redacted]@192.168.178.202:554/cam/realmonitor?channel=1&subtype=0
    Terrace_sub:
      - rtsp://cctv:[redacted]@192.168.178.202:554/cam/realmonitor?channel=1&subtype=2#backchannel=0
      - ffmpeg:Terrace_sub#audio=opus
    Backyard:
      - rtsp://cctv:[redacted]@192.168.178.201:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:Backyard#audio=opus
      - rtsp://cctv:[redacted]@192.168.178.201:554/cam/realmonitor?channel=1&subtype=0
    Backyard_sub:
      - rtsp://cctv:[redacted]@192.168.178.201:554/cam/realmonitor?channel=1&subtype=2#backchannel=0
      - ffmpeg:Backyard_sub#audio=opus
    Side:
      - rtsp://cctv:[redacted]@192.168.178.204:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:Side#audio=opus
      - rtsp://cctv:[redacted]@192.168.178.204:554/cam/realmonitor?channel=1&subtype=0
    Side_sub:
      - rtsp://cctv:[redacted]@192.168.178.204:554/cam/realmonitor?channel=1&subtype=2#backchannel=0
      - ffmpeg:Side_sub#audio=opus
    Kendra:
      - rtsp://andrew:[redacted]@192.168.178.42/stream1
  webrtc:
    candidates:
      - 192.168.178.253:8555
      -[redacted WAN IP]:8555

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  Terrace: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Terrace # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Terrace_sub # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    zones:
      Terrace_Main:
        coordinates: 0.095,0.099,0.153,0.092,0.167,0.3,0.213,0.284,0.739,0.997,0.192,0.997
        loitering_time: 0
        objects: person
        inertia: 3
      Terrace_Grass:
        coordinates: 
          0.457,0.303,0.695,0.226,0.997,0.401,0.996,0.84,0.609,0.503,0.409,0.578,0.253,0.305,0.451,0.307
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - Terrace_Grass
          - Terrace_Main
      detections: {}
    motion:
      threshold: 30
      contour_area: 38
      improve_contrast: 'true'
      mask:
        - 0.223,0.29,0.233,0,0.373,0,0.501,0.271,0.507,0.312,0.516,0.431,0.347,0.487
        - 0.472,0.087,0.512,0.239,0.687,0.292,0.819,0.325,1,0.366,0.995,0.129,1,0,0.478,0
        - 0.395,0.573,0.613,0.484,0.692,0.521,0.695,0.406,0.661,0.293,0.786,0.3,0.787,0.333,0.745,0.361,0.722,0.57,0.805,0.611,0.837,0.517,0.824,0.315,0.984,0.352,0.871,0.552,0.846,0.66,0.994,0.829,0.998,0.993,0.72,0.991
    objects:
      filters:
        car: {}
  Backyard: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Backyard_sub # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    motion:
      threshold: 30
      contour_area: 38
      improve_contrast: 'true'
      mask:
        - 0,0.291,0,0,0.378,0,0.623,0,0.613,0.154,0.285,0.202,0.157,0.288
        - 0.686,0.037,0.963,0.035,0.964,0.089,0.687,0.087
        - 0.665,0.003,0.997,0,0.998,0.139,0.853,0.105,0.771,0.026,0.705,0.03
    zones:
      Backyard_Main:
        coordinates: 
          0.003,0.307,0.283,0.103,0.674,0.052,0.84,0.085,0.997,0.146,0.997,0.995,0.003,0.991
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Backyard_Main
      detections:
        required_zones: Backyard_Main
  Doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    motion:
      threshold: 30
      contour_area: 38
      improve_contrast: 'true'
      mask:
        - 0.614,0.68,0.613,0.392,0.93,0.275,0.951,0.419,0.945,0.576,0.927,0.717,0.9,0.845
        - 0.002,0.96,0.295,0.96,0.293,0.997,0.002,0.997
    zones:
      Doorbell_Main:
        coordinates: 0.002,0,0.998,0.001,0.996,0.996,0.296,1,0,1
        loitering_time: 0
        objects: person
    objects:
      filters:
        car: {}
    review:
      alerts:
        required_zones: Doorbell_Main
      detections: {}
  Driveway: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    motion:
      threshold: 30
      contour_area: 32
      improve_contrast: 'true'
      mask:
        - 0.74,0.915,0.814,0.439,0.821,0.406,1,0.486,0.997,0.998
        - 0.691,0,0.684,0.111,0.82,0.199,0.88,0.431,1,0.484,1,0
    objects:
      filters:
        car: {}
    zones:
      Driveway_Main:
        coordinates: 0.003,0.118,0.405,0.003,0.39,0.378,0.664,0.177,0.985,0.381,1,1,0,0.998
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: Driveway_Main
      detections: {}
  Side: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Side_sub # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    motion:
      threshold: 30
      contour_area: 38
      improve_contrast: 'true'
      mask: 0.294,0.21,0.369,0.163,0.996,0.318,0.992,0.576
    objects:
      filters:
        car: {}
    zones:
      Side_Main:
        coordinates: 
          0.146,0.199,0.241,0.189,0.994,0.593,0.994,0.988,0.004,0.996,0.013,0.084,0.148,0.083
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Side_Main
      detections: {}
  Kendra:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kendra
          input_args: preset-rtsp-restream
    detect:
      enabled: false
      fps: 5
    motion:
      threshold: 30
      contour_area: 38
      improve_contrast: 'true'
    zones:
      Kendra_Main:
        coordinates: 0.379,0.466,0.752,0.543,0.742,1,0.234,1
        loitering_time: 0
        objects: person
version: 0.14
```

### Relevant Frigate log output

```shell
Unsure of what logs to put here as there is no exception/log generated for this issue.
```

### Relevant go2rtc log output

```shell
Unsure of what logs to put here as there is no exception/log generated for this issue.
```

### FFprobe output from your camera

```shell
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.178.203:554/cam/realmonitor?channel=1\u0026subtype=0/",
      "remote_addr": "192.168.178.203:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 2257061245 2257061245 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-packetization-supported:IV\r\na=x-rtppayload-supported:IV\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:15.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0033;sprop-parameter-sets=Z00AM5Y1QHgAh9NwUBBUAAADAAQAAAMAehAA,aO4xsgA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=recvonly\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPEG4-GENERIC/8000"
      ],
      "receivers": [
        "96 H264, bytes=293528730509, senders=2",
        "97 MPEG4-GENERIC/8000, bytes=820368746, senders=3"
      ],
      "recv": 296892908395
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/a855e4f695bd13a4fd1a004bc876d9f2",
      "remote_addr": "127.0.0.1:48192",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=go2rtc/1.9.2\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=audio 0 RTP/AVP 96\r\nb=AS:64\r\na=rtpmap:96 opus/48000/2\r\na=control:streamid=0\r\n",
      "medias": [
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 OPUS/48000/2, bytes=0, senders=1"
      ]
    },
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.178.203:554/cam/realmonitor?channel=1\u0026subtype=0/",
      "remote_addr": "192.168.178.203:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 2257061245 2257061245 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-packetization-supported:IV\r\na=x-rtppayload-supported:IV\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:15.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0033;sprop-parameter-sets=Z00AM5Y1QHgAh9NwUBBUAAADAAQAAAMAehAA,aO4xsgA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=5\r\na=rtpmap:8 PCMA/8000\r\na=sendonly\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPEG4-GENERIC/8000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=0, senders=1",
        "97 MPEG4-GENERIC/8000, bytes=0, senders=1"
      ],
      "senders": [
        "8 PCMA/8000, bytes=0, receivers=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/Driveway",
      "remote_addr": "127.0.0.1:35454",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0033;sprop-parameter-sets=Z00AM5Y1QHgAh9NwUBBUAAADAAQAAAMAehAA,aO4xsgA=\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=293528730509, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=820368746, receivers=1"
      ],
      "send": 297730223335
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/Driveway?audio",
      "remote_addr": "127.0.0.1:48190",
      "user_agent": "go2rtc/ffmpeg",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=audio 0 RTP/AVP 96\r\na=rtpmap:96 MPEG4-GENERIC/8000\r\na=fmtp:96 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1588\r\na=control:trackID=0\r\n",
      "medias": [
        "audio, sendonly, ANY"
      ],
      "senders": [
        "96 MPEG4-GENERIC/8000, bytes=845, receivers=1"
      ],
      "send": 893
    },
    {
      "type": "probe",
      "remote_addr": "192.168.178.152:56094",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        "0 ANY, bytes=0, senders=1"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "96 H264, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=0, receivers=1",
        "96 OPUS/48000/2, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=0, receivers=1"
      ]
    }
  ]
}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    network_mode: host
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/andrew/frigate/config:/config
      - /mnt/cctv/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "[redacted]"
      LIBVA_DRIVER_NAME: "radeonsi"
      PLUS_API_KEY: "[redacted]"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua TIOC HDW3849

### Any other information that may be helpful

Here are the screenshots to illustrate the issue: https://imgur.com/a/7uFw8fF
