### DISCUSSION TITLE
[Support]: audio OK on 0.13 but not 0.15

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#15827] [General Support] [answered]
### Describe the problem you are having

Using this part of config.yml

```
greenhouse:
    - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
    - ffmpeg:greenhouse#audio=opus
```

means that 0.13, hosted on a TrueNAS appliance, gets decent audio and the go2rtc logs simply show 

```
2024-12-29 16:04:12.748238910  [INFO] Preparing new go2rtc config...
2024-12-29 16:04:18.548619813  [INFO] Starting go2rtc healthcheck service...
2024-12-29 16:04:43.069218826  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-12-29 16:04:44.090829547  [INFO] Starting go2rtc...
2024-12-29 16:04:44.567874890  16:04:44.567 INF go2rtc version 1.8.4 linux/amd64
2024-12-29 16:04:44.568379804  16:04:44.568 INF [api] listen addr=:1984
2024-12-29 16:04:44.568554801  16:04:44.568 INF [rtsp] listen addr=:8554
2024-12-29 16:04:44.569069070  16:04:44.569 INF [webrtc] listen addr=:8555
```

However, 0.15 (admittedly via dockge on a different host) sees all sorts of problems when using that same part of the config (with other parts altered from 0.13 to suit 0.15), and in this case the go2rtc logs show

```
error="streams: exec: [in#0 @ 0x620a79cd0e80] Error opening input: Invalid data found when processing input\nError opening input file rtsp://127.0.0.1:8554/greenhouse?audio.\nError opening input files: Invalid data found when processing input\n" stream=greenhouse
```

Altering 0.15's config.yml to instead say

```
greenhouse:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
      - ffmpeg:greenhouse
```

gives me a clean go2rtc log the same as 0.13 

Disabling audio on the restream gets rid of the problem, but I would like to discover the likely cause.  Is it because the version of go2rtc is different between 0.13 and 0.15 and, if so, how might I start to fault find please?

### Version

0.13.2-6476F8A & 0.15.0-87e7b62

### What browser(s) are you using?

Version 131.0.6778.204 (Official Build) for Linux Mint (64-bit)

### Frigate config file

```yaml
please see main post for what I hope is the pertinent section
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
please see main post for pertinent section
```

### FFprobe output from your camera

```shell
0.13 says
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":360,"width":640},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]

0.15 says
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)","width":640,"height":360,"avg_frame_rate":"0/0"},{"codec_long_name":"PCM mu-law / G.711 mu-law","avg_frame_rate":"0/0","bit_rate":"64000"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)","width":1920,"height":1080,"avg_frame_rate":"16/1"},{"codec_long_name":"PCM mu-law / G.711 mu-law","avg_frame_rate":"0/0","bit_rate":"64000"}]}}]
```

### Frigate stats

```json
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
#version: "3.9"
services:
  frigate:
    container_name: frigate015
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    shm_size: 256mb # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      #host : container
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      LIBVA_DRIVER_NAME: i965
      PLUS_API_KEY: #####################################
networks: {}
```

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

Floureon: probably a Hikvision clone

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/5c6f11f4-53c6-4e50-abe1-f5687f773456)
