### DISCUSSION TITLE
v15b4 recording retention question

### DISCUSSION THREAD

**Discussion by rsteckler** [blakeblackshear/frigate#15835] [Ask A Question] [answered]
I'm reading through the new retention docs and a little confused on how alerts/detections and active_objects interact.  

Maybe a couple of questions will illustrate where I'm confused:
1. Isn't mode superfluous under the alerts/detections categories?  By definition if it's an alert/detection, there must have been motion and an active object?  What would be the difference between the different modes under the alert sections?
alert/all:  retain all recordings where an alert happened
alert/motion:  retain all recordings where an alert had motion (but isn't that redundant?)
alert/active_object:  retain all recordings where an alert happened because an active_object triggered it (again, redundant?)

2. So are these two configurations effectively the same?
Retain any active object for 3 days:
```
record:
  enabled: True
  retain:
    days: 3
    mode: active_objects 
```

Retain any alert or detected object for 3 days:
```
record:
  enabled: True
  alerts:
    retain:
      days: 3
      mode: all
  detections:
    retain:
      days: 3
      mode: all
```

Thanks for clearing it up!
