### DISCUSSION TITLE
Microphone Icon not showing in frigate

### DISCUSSION THREAD

**Discussion by MarcoGeraldi** [blakeblackshear/frigate#15832] [Camera Support]
### Describe the problem you are having

I am configuring a tapo camera with frigate but the microphone icon is not showing up.

I can correclty get the video and audio feedback, but i am not able to transmit audio via the ip camera. 

what I noticed is that if I try to enable the microphone icon in the lovelace card, this is not showing up

 
![image](https://github.com/user-attachments/assets/b095ef3e-cc72-4d32-a1bc-4a4ee6c80411)

### Version

 0.14.1

### Frigate config file

```yaml
mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: root

detectors: # <---- add detectors
  cpu:
    type: cpu
    num_threads: 2

go2rtc:
  streams:
    dahua_camera:
      - rtsp://admin:adminADMIN@192.168.1.21/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. 
    dahua_camera_sub:
      - rtsp://admin:adminADMIN@192.168.1.21/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio. 
    tapo_camera:
      - rtsp://tapoAdmin:tapoAdmin@192.168.1.41/stream1
      - tapo://APP_PASSWORD_IN_CLEAR@192.168.1.41
    tapo_camera_sub:
      - rtsp://tapoAdmin:tapoAdmin@192.168.1.41/stream2
      - tapo://APP_PASSWORD_IN_CLEAR@192.168.1.41

cameras:
  test_cam:
    ffmpeg:
      #output_args:
      #  record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/dahua_camera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dahua_camera_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: dahua_camera_sub
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7
    
    snapshots:
      enabled: true
    
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 10
    
    motion:
      mask: 0.728,0.018,0.724,0.111,0.988,0.112,0.99,0.014
  
  tapo_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_camera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
    
    live:
      stream_name: tapo_camera_sub
    
    snapshots:
      enabled: true
    
    record:
      enabled: true
      retain:
        days: 5

version: 0.14
```

### Relevant Frigate log output

```shell
Not Relevant
```

### Relevant go2rtc log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Tapo C520WS

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/762089fa-bb3b-4ac2-829b-a5a128f1077a)
