### DISCUSSION TITLE
[Config Support]: Streaming & Recording is limited to 5 fps & low iGPU usage (intel 12th gen)

### DISCUSSION THREAD

**Discussion by weber8thomas** [blakeblackshear/frigate#15841] [Config Support] [answered]
### Describe the problem you are having

I'm playing with frigate for quite some time and could not figure why frigate is restricting stream to 5fps while the camera is configured at 15 fps (working through VLC). Also, I find my CPU usage quite important while I'd like just to record without transcoding (from the documentation I understand that it should be possible to record directly h265). I'm using a Annke C800 with the configuration provided in frigate docs: https://docs.frigate.video/configuration/camera_specific/#annke-c800

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  annkec800_sd: #named _sd for legacy but will be updated 
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.0.221:554/Streaming/Channels/101
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
    detect:
      enabled: false
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 60
          mode: motion
```

### Relevant Frigate log output

```shell
root@frigate:~/frigate-0.13.2# docker compose logs -f
frigate  | s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2025-01-06 11:40:45.370993842  [INFO] Preparing Frigate...
frigate  | 2025-01-06 11:40:45.372005002  [INFO] Starting NGINX...
frigate  | 2025-01-06 11:40:45.372992391  [INFO] Preparing new go2rtc config...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2025-01-06 11:40:45.397698650  [INFO] Starting Frigate...
frigate  | 2025-01-06 11:40:45.738372778  [INFO] Starting go2rtc...
frigate  | 2025-01-06 11:40:45.827346394  11:40:45.827 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2025-01-06 11:40:45.827865287  11:40:45.827 INF [api] listen addr=:1984
frigate  | 2025-01-06 11:40:45.828071643  11:40:45.827 INF [rtsp] listen addr=:8554
frigate  | 2025-01-06 11:40:45.828335259  11:40:45.828 INF [webrtc] listen addr=:8555
frigate  | 2025-01-06 11:40:46.891697261  [2025-01-06 11:40:46] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
frigate  | 2025-01-06 11:40:46.891891308  [2025-01-06 11:40:46] frigate.app                    INFO    : Creating directory: /tmp/cache
frigate  | 2025-01-06 11:40:49.641156718  2025/01/06 11:40:49 [error] 142#142: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.104, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "XXX
frigate  | 2025-01-06 11:40:49.641185168  192.168.0.104 - - [06/Jan/2025:11:40:49 +0100] "GET /ws HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "192.168.1.1"
frigate  | 2025-01-06 11:40:50.172150334  [2025-01-06 11:40:50] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2025-01-06 11:40:50.192520579  [2025-01-06 11:40:50] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2025-01-06 11:40:50.201190329  [2025-01-06 11:40:50] frigate.app                    INFO    : Recording process started: 459
frigate  | 2025-01-06 11:40:50.203684124  [2025-01-06 11:40:50] frigate.app                    INFO    : go2rtc process pid: 89
frigate  | 2025-01-06 11:40:50.224622759  [2025-01-06 11:40:50] detector.cpu                   INFO    : Starting detection process: 468
frigate  | 2025-01-06 11:40:50.233268912  [2025-01-06 11:40:50] frigate.app                    INFO    : Output process started: 470
frigate  | 2025-01-06 11:40:50.234500720  [2025-01-06 11:40:50] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2025-01-06 11:40:50.254415703  [2025-01-06 11:40:50] frigate.app                    INFO    : Camera processor started for annkec800_transcode: 476
frigate  | 2025-01-06 11:40:50.259320088  [2025-01-06 11:40:50] frigate.app                    INFO    : Camera processor started for annkec800_sd: 477
frigate  | 2025-01-06 11:40:50.265383806  [2025-01-06 11:40:50] frigate.app                    INFO    : Capture process started for annkec800_transcode: 479
frigate  | 2025-01-06 11:40:50.270909772  [2025-01-06 11:40:50] frigate.app                    INFO    : Capture process started for annkec800_sd: 483
frigate  | 2025-01-06 11:40:50.317195731  2025/01/06 11:40:50 [error] 143#143: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
frigate  | 2025-01-06 11:40:55.371854820  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-01-06 11:41:55.664323184  192.168.0.104 - - [06/Jan/2025:11:41:55 +0100] "GET /ws HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "192.168.1.1"
```

### Relevant go2rtc log output

```shell
No go2rtc output
```

### Operating system

Proxmox

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.2
    shm_size: "456mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/proxmox-services/frigate/config:/config
      - /mnt/nfs/frigate:/media/frigate
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555" # WebRTC over tcp
    user: root
    environment:
      - LIBVA_DRIVER_NAME=iHD
      - PUID=0
      - PGID=0
      - DISPLAY=:0
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
      - FRIGATE_RTSP_PASSWORD="password"
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/76ec97e6-a3fe-43d3-8098-4073bb026b35)

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/c5e72707-99fe-4780-a882-db9e0d34eb40)
![image](https://github.com/user-attachments/assets/caa7e192-78e2-439e-a7ec-a4583a064c4e)

```
root@951573cf002b:/opt/frigate# ffmpeg -i rtsp://admin:password@192.168.0.221:554/Streaming/Channels/101/ -f null -
ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:password@192.168.0.221:554/Streaming/Channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc), 3840x2160 [SAR 1:1 DAR 16:9], 14.99 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    title           : Media Presentation
    encoder         : Lavf59.27.100
  Stream #0:0: Video: wrapped_avframe, yuvj420p(pc, progressive), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 14.99 fps, 14.99 tbn
    Metadata:
      encoder         : Lavc59.37.100 wrapped_avframe
  Stream #0:1: Audio: pcm_s16le, 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc59.37.100 pcm_s16le
[rtsp @ 0x5d47ab459880] max delay reached. need to consume packetspeed=  12x
[rtsp @ 0x5d47ab459880] RTP: missed 128 packets
[hevc @ 0x5d47abcce200] Could not find ref with POC 27itrate=N/A speed=3.56x
frame=  412 fps= 15 q=-0.0 size=N/A time=00:00:28.28 bitrate=N/A speed=1.06x
```
