### DISCUSSION TITLE
[Detector Support]: Cat detection not working

### DISCUSSION THREAD

**Discussion by beze** [blakeblackshear/frigate#15858] [Detector Support]
### Describe the problem you are having

Hello, 

I do have 4 Tapo c-120 integrated, plus a reolink doorbell exposed to homekit trough HA.

Apple did identified this cat, but Frigate didn't even got the movment detection. What should I enhance in my setup, for this cat to be identified?

(By the way, this cat runs into my house and let his poop gifts all over, he is the entire reason why I put cameras and NVR LOL). 

### Version

0.14

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 10.0.0.254
  port: 1883
  user: hamqtt
  password: Teste336!
  topic_prefix: frigate
  client_id: frigate

go2rtc:
  streams:
    Entrance1:
      - rtsp://rthome:Teste336!@10.0.0.240:554/h264Preview_01_main
    Entrance2:
      - rtsp://rthome:Teste336!@10.0.0.240:554/h264Preview_01_sub
    Frontyard1:
      - rtsp://rthome:Teste336!@10.0.0.241/stream1
    Frontyard2:
      - rtsp://rthome:Teste336!@10.0.0.241/stream2
    Sidedoor1:
      - rtsp://rthome:Teste336!@10.0.0.242/stream1
    Sidedoor2:
      - rtsp://rthome:Teste336!@10.0.0.242/stream2
    Backyard1:
      - rtsp://rthome:Teste336!@10.0.0.243/stream1
    Backyard2:
      - rtsp://rthome:Teste336!@10.0.0.243/stream2
    Corridor1:
      - rtsp://rthome:Teste336!@10.0.0.244/stream1
    Corridor2:
      - rtsp://rthome:Teste336!@10.0.0.244/stream2
    Office:
      - rtsp://Ox1b7clTbpl8:Ad32B2Fy9ckM@10.0.0.50/live0
    Oliverroom:
      - rtsp://Hb4rH0zYOP5x:Me6IsFUSOGvN@10.0.0.22/live0

cameras:
  Office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Office
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4

    motion:
      mask: 0.848,0.018,0.848,0.06,0.939,0.065,0.945,0.016
  Oliverroom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Oliverroom
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4

    motion:
      mask: 0.622,0.996,0.633,0.641,0.628,0.289,0.624,0,0.995,0.009,0.999,0.991
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard2
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Backyard1
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4

    motion:
      mask: 0.199,0.004,0.2,0.046,0.358,0.05,0.357,0.004
    objects:
      filters:
        car:
          mask: 0.008,0.049,0.983,0.085,0.994,0.979,0.016,0.981
  Frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Frontyard2
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Frontyard1
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4

    motion:
      mask:
        - 0.206,0.002,0.356,0.002,0.358,0.043,0.206,0.045
        - 0.752,0.643,0.768,0.639,0.773,0.727,0.756,0.728
        - 0.652,0.56,0.663,0.558,0.667,0.592,0.657,0.597
        - 0.492,0.674,0.51,0.659,0.528,0.729,0.512,0.737
        - 0.813,0.527,0.81,0.591,0.823,0.594,0.827,0.529
    objects:
      filters:
        car:
          mask:
            - 0.246,0.151,0.285,0.331,0.356,0.618,0.612,0.427,1,0.483,1,1,0.573,1,0.22,1,0,1,0,0.414
            - 0.443,0,0.391,0.229,0.538,0.223,0.645,0.226,0.632,0
  Corridor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Corridor2
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Corridor1
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4
    motion:
      mask: 0.205,0.011,0.206,0.043,0.357,0.043,0.357,0.004
    objects:
      filters:
        car:
          mask: 0.01,0.987,0.996,0.99,0.992,0.015,0.004,0.01
  Sidedoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Sidedoor2
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Sidedoor1
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4

    motion:
      mask: 0.206,0,0.205,0.045,0.352,0.045,0.355,0
    objects:
      filters:
        car:
          mask: 0.002,0.01,0.004,0.99,0.991,0.997,0.992,0.003
  Entrance:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Entrance2
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Entrance1
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 4
      events:
        retain:
          default: 4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4

    motion:
      mask:
        - 0.067,0.399,0.311,0.465,0.313,0.572,0.034,0.499
        - 0.616,0.481,0.62,0.588,0.996,0.603,0.993,0.463
        - 0.484,0,0.487,0.057,0.601,0.06,0.601,0
    objects:
      filters:
        car: {}
        person: {}
      mask:
        - 0.033,0.506,0.07,0.399,0.313,0.464,0.319,0.58
        - 0.618,0.478,0.621,0.629,0.823,0.64,1,0.628,0.995,0.461
objects:
  track:
    - person
    - car
    - dog
    - cat

logger:
  default: error

record:
  sync_recordings: true

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="612" alt="system metrics" src="https://github.com/user-attachments/assets/fde0670d-7865-42e2-9e56-85af78369548" />

### Any other information that may be helpful

https://github.com/user-attachments/assets/05d21a6f-07c7-4d67-afa8-df253d1a8af5

https://github.com/user-attachments/assets/9ce80d6a-ddbb-4686-af43-ce095ecf3bd8
