### DISCUSSION TITLE
False positives not showing up as snapshots

### DISCUSSION THREAD

**Discussion by tinimark** [blakeblackshear/frigate#15868] [General Support]
### Describe the problem you are having

This may well be user error.
I have a Node-Red flow set to turn lights on when a car is detected (this all works fine).
When the weather is bad I see the lights come on but no events or snapshots in Frigate+ are showing.
In Node-Red I can see mqtt is triggering binary_sensor.car_park_car_occupancy which is turning the lights on.
What conditions might I look for when Frigate is sending an MQTT msg but no video of snapshot is being recorded?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
model:
  path: plus://9b45ccdf8d2a8822b5f4ea998ac7823d

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

mqtt:
  host: 192.**
  user: **
  password: **

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion


birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

go2rtc:
  streams:
    car_park:
      - rtsp://**/Streaming/Channels/103

car_park:
    ffmpeg:

      inputs:
        - path: rtsp://**/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://**/Streaming/Channels/103
          roles:
            - detect
    detect:
      max_disappeared: 20
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - amazon
        - face
      filters:
        person:
          threshold: 0.8
        car:
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    motion:
      mask: 
        0,0.336,0.073,0.272,0.042,0.253,0.074,0.232,0.096,0.209,0.186,0.189,0.277,0.175,0.325,0.171,0.343,0.138,0.347,0.114,0.343,0.08,0.358,0.08,0.366,0.105,0.387,0.146,0.406,0.172,0.467,0.173,0.526,0.183,0.628,0.189,0.798,0.209,0.83,0.154,0.834,0,0,0
 version: 0.14
```

### Relevant Frigate log output

```shell
Nothing in the Log seems to mention anything useful relating to the issue.
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

HIK
