### DISCUSSION TITLE
[General Support]: diagonal line displayed after a few seconds

### DISCUSSION THREAD

**Discussion by adamoutler** [blakeblackshear/frigate#15864] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I view a camera, after a second or two it changes and displays a diagonal line along with color issues. 
[Screencast from 2025-01-06 15-13-56.webm](https://github.com/user-attachments/assets/1d8d0746-0009-4f1c-9aea-387172f9ed20)

### Steps to reproduce

1. Open UI 
2. scroll to camera
3. Wait 1-10s
4. Observe video change to low quality with bad color/artifacts
I don't know what confounding factors cause this. 

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Chome/firefox

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.8
  port: 1883
  user: home
  password: '{FRIGATE_MQTT_PASS}'
  client_id: frigate_instance_1


proxy:
  header_map:
    user: x-forwarded-user

objects:
  track:
    - dog
    - cat
    - person
    - bicycle
    - hot dog
    - face
    - car
    - sheep


detect:
  annotation_offset: 0

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

record:
  enabled: true
  retain:
    mode: motion
    days: 3
  events:
    retain:
      default: 30
      mode: active_objects

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
go2rtc:
  streams:
    right_side_of_house_stream:
      - rtsp://camera:camera@10.10.187.104:554/ch01.264?ptype=udp
    right_side_of_house_rotate:
      #- ffmpeg:right_side_of_house_stream#raw=-vf transpose=1,format=yuv420p
      - ffmpeg:right_side_of_house_stream#video=h264#preset=veryfast#raw=-vf transpose=1,format=nv12






    kitchen:
      - exec:ffmpeg -hide_banner -f mjpeg -i http://192.168.1.148:8080/?action=stream
        -c:v libx264 -preset ultrafast -tune zerolatency -an -f rtsp {{output}}
    front_porch_stream:
      - rtsp://admin:admin123@10.10.187.109:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:front_porch_stream#audio=opus
    front_porch_stream_sub:
      - rtsp://admin:admin123@10.10.187.109:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      - ffmpeg:front_porch_stream_sub#audio=opus
    cul_de_sac_stream:
      - rtsp://camera:camera@10.10.187.101:554/h264Preview_01_main
    cul_de_sac_stream_sub:
      - rtsp://camera:camera@10.10.187.101:554/h264Preview_01_sub
    # back_porch_stationary_steam:
    #   - rtsp://admin:admin123@10.10.187.102:555/main_stream1
    back_porch_ptz_stream:
      - rtsp://admin:admin123@10.10.187.102:554/main_stream
    back_porch_ptz_stream_sub:
      - rtsp://admin:admin123@10.10.187.102:554/sub_stream
    left_side_of_house:
      - rtsp://admin:admin@10.10.187.103:554/ch01.264?ptype=udp
    left_side_of_house_sub:
      - rtsp://admin:admin@10.10.187.103:554/ch01.264?ptype=udp
    back_yard_stream:
      - rtsp://admin:admin@10.10.187.105:554/ch01.264?ptype=udp
    back_yard_stream_sub:
      - rtsp://admin:admin@10.10.187.105:554/ch01_sub.264?ptype=udp
    driveway:
      - rtsp://admin:admin@10.10.187.108:554/ch01.264?ptype=udp
    driveway_sub:
      - rtsp://admin:admin@10.10.187.108:554/ch01.264?ptype=udp
cameras:

  right_side_of_house:
    ui:
      order: 8
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/right_side_of_house_rotate
          roles:
            - detect
            - record
    detect:
      enabled: true
    motion:
      mask:
        - 0.387,0.225,0.219,0.384,0.157,0.581,0.384,0.74,0.703,0.841,1,0.843,1,0.252,0.804,0.216
        - 0,0.037,0.11,0.021,0.201,0.084,0.188,0.15,0.136,0.214,0,0.195
        - 0.652,0,0.486,0.04,0.283,0.046,0.142,0.029,0,0
      threshold: 24
      contour_area: 8
      improve_contrast: 'true'
    zones:
      Front_yard:
        coordinates: 0.004,0.692,-0.002,0.994,0.994,0.997,0.998,0.691
        loitering_time: 3
        objects:
          - dog
          - cat
          - person
          - sheep
        inertia: 3
      Back_Yard:
        coordinates: 0.004,0.686,0.998,0.673,1,0.105,0,0.024
        loitering_time: 3
        objects:
          - dog
          - cat
          - person
          - sheep
        inertia: 3
      neighbors:
        coordinates: 1,0.104,0,0.025,0,0,1,0
        loitering_time: 3
        objects:
          - dog
          - cat
          - person
  cul_de_sac:
    ui:
      order: 3
    ffmpeg:
      inputs:
        # - path: rtsp://camera:camera@10.10.187.101/h264Preview_01_sub
        #   roles:
        #     - detect
        - path: rtsp://127.0.0.1:8554/cul_de_sac_stream
          roles:
            - detect
            - record

    detect:
      enabled: true
    onvif:
      host: 10.10.187.101
      port: 8000
      user: camera
      password: camera
    zones:
      Driveway:
        coordinates: 0.011,0.825,0,1,0.641,1,0.676,0.727,0.126,0.66
        inertia: 3
        loitering_time: 3
        objects:
          - bicycle
          - dog
          - cat
          - person
      neighbors:
        coordinates: 
          0.522,0.078,0.313,0.017,0.326,0.073,0,0.205,0.004,0.543,0.052,0.55,0.121,0.653,0.688,0.716,0.644,0.996,0.995,0.994,0.994,0.541,0.705,0.715,0.116,0.647,0.05,0.539,0.094,0.364,0.167,0.289,0.384,0.17
        loitering_time: 3
        inertia: 3
        objects:
          - car
          - dog
          - cat
          - person
      Street:
        coordinates: 
          0.563,0.067,0.534,0.078,0.392,0.166,0.166,0.289,0.098,0.368,0.058,0.444,0.053,0.539,0.121,0.649,0.216,0.722,0.348,0.757,0.675,0.729,0.978,0.558,0.993,0.481,0.996,0.302,0.764,0.226,0.62,0.183,0.568,0.164,0.568,0.222,0.677,0.306,0.658,0.325,0.601,0.356,0.454,0.364,0.394,0.313,0.409,0.28,0.465,0.243,0.568,0.125
        loitering_time: 3
        objects:
          - car
          - dog
          - cat
          - person

    motion:
      mask:
        - 0.587,0.231,0.633,0.179,1,0.267,1,0,0.308,0,0.391,0.056,0.553,0.065,0.563,0.123,0.403,0.327,0.677,0.308
        - 0.319,0.067,0.313,0,0.004,0.007,0.004,0.211
      threshold: 42
      contour_area: 19
      improve_contrast: true
    objects:
      filters:
        car:
          mask:
            - 0.109,0.178,0.26,0.23,0.132,0.317,0.056,0.549,0,0.556,0,0.351
            - 0.341,0.114,0.35,0.202,0.472,0.158,0.542,0.1,0.502,0.023
            - 0.465,0.052,0.774,0.08,0.776,0.015,0.462,0.006
            - 0,0.666,0.665,0.726,0.623,1,0,1
            - 0.465,0.052,0.774,0.08,0.776,0.015,0.462,0.006
            - 0.465,0.052,0.774,0.08,0.776,0.015,0.462,0.006
            - 1,0.181,0.948,0.245,0.941,0.355,1,0.378
      mask: 0.465,0.052,0.774,0.08,0.776,0.015,0.462,0.006
  back_porch:
    onvif:
      host: 10.10.187.102
      port: 8080
      user: admin
      password: admin123
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin123@10.10.187.102:554/main_stream
          roles:
            - record
            - detect
    detect:
      enabled: true


    zones:
      Back_Porch:
        coordinates: 0,0.283,1,0.225,1,1,0,1
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    motion:
      enabled: true  # Enable motion tracking
      threshold: 15  # Adjust threshold for sensitivity
      contour_area: 20  # Adjust for minimum object size
      improve_contrast: true  # Enhance contrast for motion detection
  # back_porch_stationary:
  #   ui:
  #     order: 4
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/back_porch_stationary_steam
  #         roles:
  #           - record
  #   detect:
  #     enabled: false
  #   zones: {}
  #   motion:
  #     threshold: 29
  #     contour_area: 40
  #     improve_contrast: true
    objects:
      filters:
        bicycle:
          mask: 0.807,0.506,0.863,0.512,0.883,0.647,0.8,0.656
        person:
          mask: 1,0.236,0,0.337,0,0,1,0
  back_yard:
    onvif:
      host: 10.10.187.105
      port: 8000
      user: admin
      password: admin
    ui:
      order: 6
    ffmpeg:
      inputs:
        # - path: rtsp://admin:admin@10.10.187.105:554/ch01_sub.264?ptype=udp
        #   roles:
        #     - detect
        #     - record
        - path: rtsp://127.0.0.1:8554/back_yard_stream
          roles:
            - record
            - detect

    motion:
      mask: 
        0.551,0.594,0.579,0.792,0.632,0.859,0.731,0.861,0.818,0.713,0.857,0.643,1,0.604,1,0,0,0,0,0.36,0.041,0.443,0.145,0.247,0.176,0.24,0.102,0.449,0.202,0.566,0.305,0.514,0.392,0.267,0.428,0.309,0.483,0.389
      threshold: 29
      contour_area: 20
      improve_contrast: 'true'
    zones:
      back_yard_zone:
        coordinates: 0,0.858,0,1,0.608,1,0.769,0.541,1,0.553,1,0.267,0.347,0.166
        loitering_time: 3
        inertia: 3
        objects:
          - dog
          - cat
          - person
          - sheep
      neighbors:
        coordinates: 0,0,1,0,1,0.273,0.348,0.165,0,0.859
        loitering_time: 3
        inertia: 3
        objects:
          - dog
          - cat
          - person
      Pool:
        coordinates: 0.769,0.542,0.999,0.555,1,0.842,0.672,0.82
        loitering_time: 3
        inertia: 3
        objects:
          - dog
          - cat
          - person
    review:
      detections:
        required_zones: back_yard_zone
    objects:
      filters:
        bicycle:
          mask: 0.357,0.342,0.495,0.368,0.516,0.643,0.292,0.639,0.328,0.449
  front_walkway_camera:
    onvif:
      host: 10.10.187.109
      port: 80
      user: admin
      password: admin123
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_porch_stream
          input_args: preset-rtsp-restream
            # rtmp://admin:admin123@10.10.187.109:1935/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
            # rtsp://admin:admin123@10.10.187.109:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=onvif
            # rtsp://admin:admin123@10.10.187.109:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - detect
        - path: 
            rtsp://admin:admin123@10.10.187.109:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - audio
    detect:
      enabled: true
    zones:
      Side_yard:
        coordinates: 0.233,1,0,1,0,0.485,0.148,0.274
        loitering_time: 0
        objects:
          - person
          - sheep
          - dog
          - cat
        inertia: 3
      Front_yard:
        coordinates: 0.636,0.083,0.64,0.584,0.274,0.76,0.276,0.105
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - sheep
          - face
        inertia: 3
      Front_Porch:
        coordinates: 1,1,0.772,1,0.25,1,0.223,0.808,0.632,0.592,0.632,0.065,1,0.312
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - face
        inertia: 3
    motion:
      threshold: 20
      contour_area: 14
      improve_contrast: 'true'
      mask:
        - 1,0,1,0.71,0.606,0.586,0.519,0.349,0.528,0.154,0.685,0.034
        - 0.008,0.796,0.104,0.751,0.162,0.599,0.098,0.496,0.059,0.057,0,0.127,0,0.626
        - 0.313,0.604,0.397,0.602,0.423,0.704,0.378,0.77,0.318,0.726
    review:
      alerts:
        required_zones:
          - Front_Porch
          - Front_yard
          - Side_yard
      detections:
        required_zones:
          - Front_Porch
          - Front_yard
          - Side_yard
    objects:
      filters:
        car:
          mask: 0.524,0.024,0.674,0.024,0.644,0.271,0.474,0.199,0.468,0.072
      mask: 0,0,0.098,0,0.137,0.113,0,0.281
  driveway:
    onvif:
      host: 10.10.187.108
      port: 8000
      user: admin
      password: admin
    ui:
      order: 2
    ffmpeg:
      inputs:
        # - path: rtsp://admin:admin@10.10.187.108:554/ch01_sub.264?ptype=udp
        #   roles:
        #     - detect
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
            - detect
    detect:
      enabled: true
    motion:
      mask:
        - 0.141,0,0.454,0,0.407,0.303,0.26,0.406
        - 0.735,0,0.816,0.24,0.997,0.247,0.997,0.001
        - 0.519,0.637,0.822,0.448,1,0.776,0.723,1
      threshold: 30
      contour_area: 25
      improve_contrast: 'true'
    zones:
      Yard:
        coordinates: 0.066,0.203,0.074,0.425,0.502,0.336,0.491,0.273
        loitering_time: 3
        inertia: 3
        objects:
          - bicycle
          - face
          - dog
          - cat
          - person
          - sheep
      Driveway:
        coordinates: 0.071,0.425,0,0.223,0.004,0.999,0.913,1,0.998,0.79,0.507,0.337
        loitering_time: 3
        inertia: 3
        objects:
          - bicycle
          - face
          - dog
          - cat
          - person
          - sheep
      neighbors:
        coordinates: 
          0.076,0.204,0.496,0.27,0.571,0.206,0.713,0.205,0.994,0.276,0.995,0.014,0.095,0.008
        loitering_time: 3
        inertia: 3
        objects:
          - dog
          - cat
          - person
      Street:
        coordinates: 0.99,0.276,0.762,0.221,0.695,0.204,0.557,0.203,0.495,0.269,0.509,0.36,1,0.794
        loitering_time: 3
        inertia: 3
        objects:
          - car
          - dog
          - cat
          - person
          - sheep
    objects:
      mask: 0.382,0.127,0.492,0.147,0.504,0.206,0.382,0.166
      filters:
        car:
          mask:
            - 0.326,0.843,0.566,0.463,0.934,0.472,0.937,0.506,0.996,1,0.351,1
            - 0.638,0.203,0.832,0.21,0.953,0.261,0.951,0.167,0.582,0.073
            - 0.382,0.127,0.492,0.147,0.504,0.206,0.382,0.166
            - 0.23,0.59,0.543,0.561,0.505,0.27,0.238,0.298
            - 0.382,0.127,0.492,0.147,0.504,0.206,0.382,0.166
    review:
      alerts:
        required_zones:
          - Driveway
          - Yard
  left_side_of_house:
    onvif:
      host: 10.10.187.103
      port: 8000
      user: admin
      password: admin
    ui:
      order: 7
    ffmpeg:
      inputs:
        # - path: rtsp://admin:admin@10.10.187.103:554/ch01_sub.264?ptype=udp
        #   roles:
        #     - detect
        - path: rtsp://127.0.0.1:8554/left_side_of_house
          roles:
            - record
            - detect
    detect:
      enabled: true
    zones:
      left_side:
        coordinates: 0.16,0.35,0.384,0.33,1,0.666,1,1,0.189,1
        loitering_time: 3
        inertia: 3
        objects:
          - face
          - dog
          - cat
          - person
          - sheep
      Front_Yard:
        coordinates: 0.376,0.336,0.161,0.346,0.159,0.22
        loitering_time: 3
      neighbors:
        coordinates: 0.21,0.243,1,0.666,0.999,0.004,0.161,0,0.193,0.164,0.324,0.184,0.363,0.214
        loitering_time: 3
        objects:
          - car
          - dog
          - cat
          - person
      Street:
        coordinates: 0.189,0.171,0.311,0.184,0.324,0.218,0.202,0.24
        loitering_time: 3
        objects:
          - car
          - dog
          - cat
          - person
      porch:
        coordinates: 0.124,0.199,0,0.415,0,1,0.185,1
        loitering_time: 3
    objects:
      filters:
        car:
          mask:
            - 0.246,0.474,0.38,0.969,0.14,0.968
            - 0.51,0.304,0.269,0.221,0.419,0.038
        person: {}
      mask: 0.246,0.474,0.38,0.969,0.14,0.968
    motion:
      threshold: 54
      contour_area: 56
      improve_contrast: 'true'
  kitchen:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          roles:
            - detect
    record:
      enabled: false
    detect:
      enabled: true
    motion:
      threshold: 80
      contour_area: 100
      improve_contrast: false
    zones:
      Kitchen:
        coordinates: 0.015,0.158,0.974,0.191,0.996,0.98,0.007,0.982
        loitering_time: 0
        objects:
          - hot dog
          - sheep
        inertia: 3
    objects:
      filters:
        person:
          mask: 0,0,1,0,1,1,0,1
    review:
      detections:
        required_zones: Kitchen


  3D_Printer:
    enabled: false
    ffmpeg:
      inputs:
        - path: http://192.168.1.251:8080/?action=stream
          roles:
            - detect
    record:
      enabled: false
    detect:
      enabled: false

birdseye:
  enabled: true
  mode: objects
camera_groups:
  Events:
    order: 1
    icon: LuBird
    cameras: birdseye

  Outdoor:
    order: 2
    icon: LuAperture
    cameras:
      - back_porch_stationary
      - back_yard
      - cul_de_sac
      - driveway
      - front_walkway_camera
      - left_side_of_house
      - right_side_of_house
  Indoor:
    order: 3
    icon: LuWarehouse
    cameras: kitchen
tls:
  enabled: false
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: '3.7'

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true # Need to determine which operations this is required
    ports:
      - "1935:1935"
      - "8971:8971"
      - "5000:5000" # Frigate Web UI
      - "8554:8554" # RTSP Restream
      - "8555:8555/tcp" # WebRTC over TCP
      - "8555:8555/udp" # WebRTC over UDP
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
      - frigate-config:/config:rw # Configuration files
      - frigate-media:/media/frigate:rw # Media files (clips, recordings, etc.)
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      PLUS_API_KEY: ${FRIGATE_PLUS_API_KEY}
      DETECTOR_CORAL: "usb"
      FRIGATE_RTSP_PASSWORD: "your_rtsp_password"
      TF_ENABLE_ONEDNN_OPTS: 1
      OMP_NUM_THREADS: 4
      FRIGATE_MQTT_PASS: ${frigateMQTTPass}
    restart: unless-stopped
    shm_size: "800mb"
    networks:
      - net

  redis:
    image: redis:7.2.3-alpine3.18
    restart: always
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 100'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis:/data
    networks:
      - net

  frigate-telegram:
    image: ghcr.io/oldtyt/frigate-telegram:amd64
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${FRIGATE_DOCKER_KEY}
      FRIGATE_URL: http://192.168.1.222:5000
      FRIGATE_EVENT_LIMIT: 5
      DEBUG: "False"
      TELEGRAM_CHAT_ID: "-4709982301"
      SLEEP_TIME: 30
      FRIGATE_EXTERNAL_URL: https://frigate.adamoutler.com
      TZ: "America/New_York"
      REDIS_ADDR: "redis:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  frigate-config:
  frigate-media:
  redis:
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

AMCREST IP4M-T1277EB-AI

### Screenshots of the Frigate UI's System metrics pages

I could use a second Coral TPU

![image](https://github.com/user-attachments/assets/b0367c44-893a-43a5-a4bb-2cc05be34594)

### Any other information that may be helpful

It seems like something switches in the UI after viewing the camera for a few seconds.  Maybe to save bandwidth or something..  Recordings appear unaffected.  This affects the browser stream.
