### DISCUSSION TITLE
[Config Support]: Intel QSV on sub stream for 360 camera fails but works directly from ffmpeg

### DISCUSSION THREAD

**Discussion by gaynetdinov** [blakeblackshear/frigate#15861] [Config Support] [answered]
### Describe the problem you are having

Hi!
It's kinda a little bit of show&tell and a question.

First I managed to make qsv work on my 12th gen Intel i5-12500 that I bought specifically for Frigate server. 
Initially I had vaapi, but with vaapi all of my 3 camera crashed ffmpeg time to time. The 3 cameras are Reolink FE-P, Reolink CX410 and Hikvision doorbell KV8113. 
By switching to qsv all those crashes are gone. Initially I had exactly the same issue as described here https://github.com/blakeblackshear/frigate/discussions/13863 by @bob454522, but Reolink cameras don't have PS option. However in the linked ffmpeg bug [there is last commend](https://trac.ffmpeg.org/ticket/9766#comment:17) that says that adding `-bsf:v dump_extra` fixes the issue. 
And it indeed fixed it for me!
Now I have this setup for ffmpeg instead of preset

```
ffmpeg:
  hwaccel_args:
    - -bsf:v
    - dump_extra
    - -hwaccel_output_format
    - qsv
    - -c:v
    - h264_qsv
 ```

And everything would've been great if not one issue with sub stream from FE-P (fisheye 360 camera that I will try to dewarp since I have qsv encoder). The main stream works fine, but I don't want to detect on 2560x2560 30fps stream. 
However the ffmpeg crashes on sub stream despite the fact, that ffmpeg does not crash when I open this stream from frigate container like shown below. It's worth noting that opening sub stream takes around 20-25 seconds (main stream is 3-4 seconds), so it might be simply a timeout issue, but I could not figure out where to put it (and if it's about timeout after all). 

Here is how this stream plays in the Frigate docker container

```
root@5c8409d55e23:/usr/lib/ffmpeg/7.0/bin# ./ffmpeg -v verbose -bsf:v dump_extra -hwaccel qsv -i rtsp://localhost:8554/hall_sub -f null -
ffmpeg version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[tcp @ 0x560ce6d965c0] Starting connection attempt to ::1 port 8554
[tcp @ 0x560ce6d965c0] Successfully connected to ::1 port 8554
[rtsp @ 0x560ce6d95c00] SDP:
v=0
o=- 1 1 IN IP4 0.0.0.0
s=go2rtc/1.9.2
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKBAAgZA,aO48sA==; profile-level-id=640033
a=control:trackID=0
m=audio 0 RTP/AVP 97
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408
a=control:trackID=1

[rtsp @ 0x560ce6d95c00] method SETUP failed: 461 Unsupported transport
[rtsp @ 0x560ce6d95c00] setting jitter buffer size to 0
    Last message repeated 1 times
[h264 @ 0x560ce6d97400] Reinit context to 1024x1024, pix_fmt: yuv420p
[rtsp @ 0x560ce6d95c00] max_analyze_duration 5000000 reached at 5056000 microseconds st:1
[vist#0:0/h264 @ 0x560ce6f0e200] WARNING: defaulting hwaccel_output_format to qsv for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format qsv".
Selecting decoder 'h264_qsv' because of requested hwaccel method qsv
Input #0, rtsp, from 'rtsp://localhost:8554/hall_sub':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), 1 reference frame, yuv420p(progressive), 1024x1024, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
[out#0/null @ 0x560ce6dd4d40] No explicit maps, mapping streams automatically...
[vost#0:0/wrapped_avframe @ 0x560ce6dab5c0] Created video stream from input stream 0:0
[AVHWDeviceContext @ 0x560ce6db8440] Trying to use DRM render node for device 0, with matching kernel driver (i915).
[AVHWDeviceContext @ 0x560ce6db8440] libva: VA-API version 1.22.0
[AVHWDeviceContext @ 0x560ce6db8440] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x560ce6db8440] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x560ce6db8440] libva: Found init function __vaDriverInit_1_22
[AVHWDeviceContext @ 0x560ce6db8440] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x560ce6db8440] Initialised VAAPI connection: version 1.22
[AVHWDeviceContext @ 0x560ce6db8440] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ().
[AVHWDeviceContext @ 0x560ce6db8440] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x560ce6db8080] Use Intel(R) oneVPL to create MFX session, API version is 2.13, the required implementation version is 1.3
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
[AVHWDeviceContext @ 0x560ce6db8080] Initialize MFX session: implementation version is 2.11
[h264_mp4toannexb @ 0x560ce729a580] The input looks like it is Annex B already
[aost#0:1/pcm_s16le @ 0x560ce72a2dc0] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
[vost#0:0/wrapped_avframe @ 0x560ce6dab5c0] Starting thread...
[aost#0:1/pcm_s16le @ 0x560ce72a2dc0] Starting thread...
[vf#0:0 @ 0x560ce6dab100] Starting thread...
[af#0:1 @ 0x560ce70d72c0] Starting thread...
[vist#0:0/h264 @ 0x560ce6f0e200] [dec:h264_qsv @ 0x560ce6dd7200] Starting thread...
[aist#0:1/aac @ 0x560ce6dba300] [dec:aac @ 0x560ce70d1500] Starting thread...
[in#0/rtsp @ 0x560ce6d958c0] Starting thread...
Press [q] to stop, [?] for help
[graph_1_in_0:1 @ 0x7c2b88003080] tb:1/16000 samplefmt:fltp samplerate:16000 chlayout:mono
[format_out_0_1 @ 0x7c2b88004280] auto-inserting filter 'auto_aresample_0' between the filter 'Parsed_anull_0' and the filter 'format_out_0_1'
[auto_aresample_0 @ 0x7c2b88005d80] ch:1 chl:mono fmt:fltp r:16000Hz -> ch:1 chl:mono fmt:s16 r:16000Hz
[AVHWDeviceContext @ 0x7c2b9c002d40] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ().
[AVHWDeviceContext @ 0x7c2b9c002d40] Driver not found in known nonstandard list, using standard behaviour.
[h264_qsv @ 0x560ce6db5e40] Decoder: output is video memory surface
[h264_qsv @ 0x560ce6db5e40] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[AVHWDeviceContext @ 0x7c2b9c00e9c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ().
[AVHWDeviceContext @ 0x7c2b9c00e9c0] Driver not found in known nonstandard list, using standard behaviour.
[h264_qsv @ 0x560ce6db5e40] Decoder: output is video memory surface
[h264_qsv @ 0x560ce6db5e40] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[graph 0 input from stream 0:0 @ 0x7c2ba4002d00] w:1024 h:1024 pixfmt:qsv tb:1/90000 fr:25/1 sar:0/1 csp:unknown range:tv
[graph 0 input from stream 0:0 @ 0x7c2ba4002d00] video frame properties congruent with link at pts_time: 0
Output #0, null, to 'pipe:':
  Metadata:
    title           : go2rtc/1.9.2
    encoder         : Lavf61.1.100
  Stream #0:0: Video: wrapped_avframe, 1 reference frame, qsv(tv, progressive), 1024x1024, q=2-31, 200 kb/s, 25 fps, 25 tbn
      Metadata:
        encoder         : Lavc61.3.100 wrapped_avframe
  Stream #0:1: Audio: pcm_s16le, 16000 Hz, mono, s16, 256 kb/s
      Metadata:
        encoder         : Lavc61.3.100 pcm_s16le
[out#0/null @ 0x560ce6dd4d40] Starting thread...
[in#0/rtsp @ 0x560ce6d958c0] Terminating thread with return code 0 (success)x
[aist#0:1/aac @ 0x560ce6dba300] [dec:aac @ 0x560ce70d1500] Decoder thread received EOF packet
[aist#0:1/aac @ 0x560ce6dba300] [dec:aac @ 0x560ce70d1500] Decoder returned EOF, finishing
[vist#0:0/h264 @ 0x560ce6f0e200] [dec:h264_qsv @ 0x560ce6dd7200] Decoder thread received EOF packet
[aist#0:1/aac @ 0x560ce6dba300] [dec:aac @ 0x560ce70d1500] Terminating thread with return code 0 (success)
[af#0:1 @ 0x560ce70d72c0] Filtergraph returned EOF, finishing
[af#0:1 @ 0x560ce70d72c0] All consumers returned EOF
[aost#0:1/pcm_s16le @ 0x560ce72a2dc0] Encoder thread received EOF
[aost#0:1/pcm_s16le @ 0x560ce72a2dc0] Terminating thread with return code 0 (success)
[af#0:1 @ 0x560ce70d72c0] Terminating thread with return code 0 (success)
[vist#0:0/h264 @ 0x560ce6f0e200] [dec:h264_qsv @ 0x560ce6dd7200] Decoder returned EOF, finishing
[vist#0:0/h264 @ 0x560ce6f0e200] [dec:h264_qsv @ 0x560ce6dd7200] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x560ce6dab100] Filtergraph returned EOF, finishing
[vf#0:0 @ 0x560ce6dab100] All consumers returned EOF
[vost#0:0/wrapped_avframe @ 0x560ce6dab5c0] Encoder thread received EOF
[vost#0:0/wrapped_avframe @ 0x560ce6dab5c0] Terminating thread with return code 0 (success)
[out#0/null @ 0x560ce6dd4d40] All streams finished
[out#0/null @ 0x560ce6dd4d40] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x560ce6dab100] Terminating thread with return code 0 (success)
[out#0/null @ 0x560ce6dd4d40] Output file #0 (pipe:):
[out#0/null @ 0x560ce6dd4d40]   Output stream #0:0 (video): 95 frames encoded; 95 packets muxed (41800 bytes);
[out#0/null @ 0x560ce6dd4d40]   Output stream #0:1 (audio): 208 frames encoded (212992 samples); 208 packets muxed (425984 bytes);
[out#0/null @ 0x560ce6dd4d40]   Total: 303 packets (467784 bytes) muxed
[out#0/null @ 0x560ce6dd4d40] video:41KiB audio:416KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame=   95 fps= 12 q=-0.0 Lsize=N/A time=00:00:09.44 bitrate=N/A speed=1.17x
[in#0/rtsp @ 0x560ce6d958c0] Input file #0 (rtsp://localhost:8554/hall_sub):
[in#0/rtsp @ 0x560ce6d958c0]   Input stream #0:0 (video): 95 packets read (345568 bytes); 95 frames decoded; 0 decode errors;
[in#0/rtsp @ 0x560ce6d958c0]   Input stream #0:1 (audio): 209 packets read (107008 bytes); 208 frames decoded; 0 decode errors (212992 samples);
[in#0/rtsp @ 0x560ce6d958c0]   Total: 304 packets (452576 bytes) demuxed
Exiting normally, received signal 2.
```

Please see below how ffmpeg crashes when I try to use hall_sub stream.

### Version

0.15-beta4

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args:
    - -bsf:v
    - dump_extra
    - -hwaccel_output_format
    - qsv
    - -c:v
    - h264_qsv

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: plus://id

model:
  path: plus://id

go2rtc:
  streams:
    # reolink cx410
    carport:
      - ffmpeg:https://192.168.2.184/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pass#video=copy#audio=copy#audio=opus
    carport_sub:
      - ffmpeg:https://192.168.2.184/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=pass
    # reolink 360
    hall:
      - ffmpeg:https://192.168.2.204/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pass#video=copy#audio=copy#audio=opus
    hall_sub:
      - ffmpeg:https://192.168.2.204/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=pass
    doorbell:
      - ffmpeg:rtsp://admin:pass@192.168.2.183/Streaming/Channels/101/
    doorbell_sub:
      - ffmpeg:rtsp://admin:pass@192.168.2.183/Streaming/Channels/102/


cameras:
  doorbell:
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    objects:
      track:
        - amazon
        - dhl
        - usps
        - ups
        - fedex
        - gls
        - dpd
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask: 0.673,0.767,0.974,0.764,0.974,0.826,0.674,0.825

 hall:
    detect:
      width: 1024
      height: 1024
      fps: 10
    record:
      enabled: true
      retain:
        days: 3
        mode: motion

    objects:
      track:
        - person
        - cat
        - face
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hall
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record

              #- path: rtsp://127.0.0.1:8554/hall_sub
              #  input_args: preset-rtsp-restream
              #  roles:
              #    - detect

  carport:
    objects:
      track:
        - person
        - cat
        - car
        - dog
        - bicycle
        - fox
        - raccoon
        - squirrel
        - rabbit
        - umbrella
        - motorcycle
        - license_plate
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record

        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask:
        - 0.708,0,0.707,0.079,0.287,0.08,0.285,0
        - 0.187,0.379,0.193,0.452,0.136,0.492,0.114,0.197,0.35,0.192,0.355,0.281
      threshold: 40
      contour_area: 20
      improve_contrast: true
    zones:
      Carport:
        coordinates:
          0.132,0.497,0.197,0.462,0.185,0.386,0.269,0.323,0.355,0.292,1,0.736,0.997,0.997,0.215,0.993
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Carport
      detections:
        required_zones: Carport
    record:
      enabled: true
      retain:
        days: 3
        mode: all

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  crop: true
  quality: 100
  retain:
    default: 60

version: 0.15-4
semantic_search:
  enabled: true
  reindex: true
  model_size: small
```

### Relevant Frigate log output

```shell
frigate  | 2025-01-06 18:34:07.642735607  [2025-01-06 18:34:07] frigate.embeddings.embeddings  INFO    : Indexing tracked object embeddings...
frigate  | 2025-01-06 18:34:12.127575525  [2025-01-06 18:34:12] frigate.video                  ERROR   : hall: Unable to read frames from ffmpeg process.
frigate  | 2025-01-06 18:34:12.127671565  [2025-01-06 18:34:12] frigate.video                  ERROR   : hall: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-01-06 18:34:27.036958313  [2025-01-06 18:34:27] watchdog.hall                  ERROR   : Ffmpeg process crashed unexpectedly for hall.
frigate  | 2025-01-06 18:34:27.037062040  [2025-01-06 18:34:27] watchdog.hall                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-01-06 18:34:27.037064334  [2025-01-06 18:34:27] ffmpeg.hall.detect             ERROR   : [in#0 @ 0x640d59594cc0] Error opening input: Invalid data found when processing input
frigate  | 2025-01-06 18:34:27.037067049  [2025-01-06 18:34:27] ffmpeg.hall.detect             ERROR   : Error opening input file rtsp://127.0.0.1:8554/hall_sub.
frigate  | 2025-01-06 18:34:27.037068749  [2025-01-06 18:34:27] ffmpeg.hall.detect             ERROR   : Error opening input files: Invalid data found when processing input
frigate  | 2025-01-06 18:34:32.161867688  [2025-01-06 18:34:32] frigate.video                  ERROR   : hall: Unable to read frames from ffmpeg process.
frigate  | 2025-01-06 18:34:32.161957021  [2025-01-06 18:34:32] frigate.video                  ERROR   : hall: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-01-06 18:34:37.051326422  [2025-01-06 18:34:37] watchdog.hall                  ERROR   : Ffmpeg process crashed unexpectedly for hall.
frigate  | 2025-01-06 18:34:37.051377450  [2025-01-06 18:34:37] watchdog.hall                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-01-06 18:34:37.051400537  [2025-01-06 18:34:37] ffmpeg.hall.detect             ERROR   : [in#0 @ 0x5de433bdccc0] Error opening input: Invalid data found when processing input
frigate  | 2025-01-06 18:34:37.051460305  [2025-01-06 18:34:37] ffmpeg.hall.detect             ERROR   : Error opening input file rtsp://127.0.0.1:8554/hall_sub.
frigate  | 2025-01-06 18:34:37.051463116  [2025-01-06 18:34:37] ffmpeg.hall.detect             ERROR   : Error opening input files: Invalid data found when processing input
```

### Relevant go2rtc log output

```shell
no logs here
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/damirca/frigate/config:/config
      - /home/damirca/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - PLUS_API_KEY=blah
```

### Object Detector

OpenVino

**Comment by NickM-27** [comment]
you'll need to adjust input_args to change the timeout. With that said I would be curious to know if `preset-intel-qsv-h254` works for you and if you add the bsf as a global_arg instead of manual hwaccel_args

**Reply by gaynetdinov** [reply, marked as answer]
yes, both your suggestions worked!

```
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  global_args: -hide_banner -loglevel warning -threads 2 -bsf:v dump_extra
```
qsv is working with this setup
and specifying higher timeout like so
```
 - path: rtsp://127.0.0.1:8554/hall_sub
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - detect
```

fixed the stream

thank a lot!
