### DISCUSSION TITLE
Exported clip has wrong times in export section

### DISCUSSION THREAD

**Discussion by raspman** [blakeblackshear/frigate#15860] [Ask A Question]
Yet, the times in the recording are correct. How to fix?

**Comment by NickM-27** [comment]
If you are referring to the default export filename in the UI, it is based on the server's timezone

**Reply by raspman** [reply]
Yes, that's the one.  I'm running Frigate on Proxmox and it's in a docker container.  I went to console and update the time, but it's still exporting to what looks like UTC time.  Do you know where I need to go to change this?

**Reply by NickM-27** [reply]
what changes did you make?

**Reply by raspman** [reply]
Within console, I did this command and changed to the local time zone.  Date shows the correct info within console now.  dpkg-reconfigure tzdata

**Reply by NickM-27** [reply]
I don't know that that would affect what python uses. In general you want to map `/etc/localtime` into the container and also set the env var `TZ` onto the container

**Reply by raspman** [reply]
I'm almost there - the time is marked an hour earlier than it should be now (as opposed to showing UTC time before.)  Console is showing the correct time for the machine (timedatectl status shows the correct time, ls -l /etc/localtime indicates set for Pacific and docker exec -it frigate date also shows the correct time)  Here's my updated docker-compose:

```
version: '3.9'
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    privileged: true
    restart: unless-stopped
    shm_size: '512mb'
    #devices:
    # - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate/config:/config
      - /mnt/frigateVideos:/media/frigate
      - /etc/frigate:/database
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8554:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "somepassword"
      TZ: "America/Los_Angeles"
```
