### DISCUSSION TITLE
[Bug]: Events created via HTTP api don't seem to create MQTT frigate/events messages

### DISCUSSION THREAD

**Discussion by randomiq** [blakeblackshear/frigate#15884] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Recently SeeedStudio released a compact wifi/ethernet camera that has built in NodeRed/MQTT and more specifically can run yolo models directly on device.  

1. I currently have the camera streaming to Frigate the video feed (works). 
2. I then have the camera look for objects I want to trigger for (works), example car.  
3. When the car is seen I trigger an HTTP request to Frigate so that I 'manually' create the event for the right detection (works).
4. I see the POST in the Frigate logs and the UI shows a new event created (yay!)
5. However, I don't see a subsequent MQTT message from Frigate showing that an event happened and then my normal email/sms automations can kick in.
NOTE: Frigate has its own working local MQTT host that it publishes messages too and it's own working node-red.  This is not the same as the reCamera one.  

Is there a way to have the Frigate treat these HTTP created events the same way as a locally detected event?  My ultimate goal is to have the end cameras which have a small 'TPU' in it do the object detection so that the Frigate host is really just storing and presenting the events as though it did all the work.

### Steps to reproduce

1.
2.
3.
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 10.10.2.13
birdseye:
  enabled: false
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 30
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 30
    retain:
      default: 30
      mode: motion
objects:
  track:
    - person
    - cat
    - car
    - bird
    - dog
    - horse
    - cow
    - bear
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-nvidia-h264
go2rtc:
  streams:
    Chipmunk:
      - rtsp://admin:12345@10.10.2.107:554/live
cameras:
  Chipmunk:
    detect:
      width: 1920
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Chipmunk
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 0.346,0.498,0.411,0.5,0.426,0.561,0.352,0.587
            - 0.845,0.387,0.789,0.404,0.775,0.463,0.865,0.462
        bird:
          mask: 0.109,0.59,0.172,0.565,0.194,0.69,0.124,0.727
  Rabbit:
    enabled: false
    detect:
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://10.10.2.21:8554/mjpeg/1
          roles:
            - detect
    motion:
      mask:
        - 0,0,640,0,640,152,0,152
    objects:
      filters:
        car:
          mask:
            - 640,311,528,300,545,237,640,234
            - 0,266,133,259,170,165,0,165
  Nighthawk:
    enabled: true
    detect:
      width: 1024
      height: 768
    ffmpeg:
      inputs:
        - path: rtsp://10.10.2.29:8554/unicast
          roles:
            - detect
    motion: {}
    objects:
      track:
        - cat
        - bird
        - dog
        - horse
        - cow
        - bear
      filters:
        bird: {}
  Owl:
    detect:
      width: 1024
      height: 768
    ffmpeg:
      inputs:
        - path: rtsp://10.10.2.28:8554/unicast
          roles:
            - detect
    objects:
      track:
        - cat
        - bird
        - dog
        - horse
        - cow
        - bear
      filters:
        bear:
          mask:
            - 0.404,0.149,0.585,0.158,0.588,0.344,0.418,0.353
            - 0.808,0.383,0.912,0.399,0.981,0.495,0.899,0.54
    motion:
      mask: 
        0.441,0.355,0.419,0.066,0.818,0.065,0.875,0.263,0.792,0.411,0.623,0.518,0.505,0.526
#logger:
  # Optional: default log level (default: shown below)
  #default: debug
version: 0.14
camera_groups:
  Garden:
    order: 1
    icon: LuFlower2
    cameras:
      - Nighthawk
      - Owl
  Driveway:
    order: 2
    icon: LuCar
    cameras: 
      - Rabbit
      - Chipmunk
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /srv/frigate/config:/config
      - /data/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "1935:1935" # RTMP feeds
      - "1984:1984" # GO2RTC
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
Type: Info
Timestamp: 2025-01-08 02:54:29
Tag: POST
Message:
10.10.2.107 - - [08/Jan/2025:02:54:29 +0000] "POST /api/events/Chipmunk/car/create HTTP/1.1" 200 95 "-" "got (https://github.com/sindresorhus/got)" "-"
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Seeedstudio reCamera

### Screenshots of the Frigate UI's System metrics pages

NA

### Any other information that may be helpful

Screenshots:

Workflow on reCamera:
<img width="1511" alt="Screenshot 2025-01-07 at 6 59 49 PM" src="https://github.com/user-attachments/assets/a88b6e8d-778a-471d-9ee7-dc82b5f04b50" />

POST event logged:
<img width="1800" alt="Screenshot 2025-01-07 at 7 04 19 PM" src="https://github.com/user-attachments/assets/991a2815-6df3-40c7-a4f3-491cee8dee78" />

UI showing event (yep it's night time)
<img width="1800" alt="Screenshot 2025-01-07 at 7 02 14 PM" src="https://github.com/user-attachments/assets/f32490f9-f31b-4980-a35d-7ad669aafeb3" />

No MQTT event  - This MQTT and node red is running on the same host as Frigate not on the camera?  
<img width="1620" alt="Screenshot 2025-01-07 at 7 01 37 PM" src="https://github.com/user-attachments/assets/606c562f-1d3f-4686-8375-edf5e2fbff1a" />
