### DISCUSSION TITLE
[Config Support]: Can't get audio and live view not always picking the high quality stream

### DISCUSSION THREAD

**Discussion by B0ndo2** [blakeblackshear/frigate#15880] [Config Support]
### Describe the problem you are having

I enable audio on my camera (front_porch_camera) and enable go2rtc.
There is no audio in live view
Live view only shows the high res video stream once and if I click on the camera view and go back  it shows the low res view

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# frigate.yml
detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
logger:
  logs:
    frigate.record.maintainer: debug
mqtt:
  # Required: host name
  host: caha.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: ssss
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
motion:
#  improve_contrast: false
  contour_area: 30
  threshold: 40
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
go2rtc:
  streams:
    driveway:
      - rtsp://admin:XXXX@192.168.6.140/1
    front_porch_camera:
      - rtsp://admin:XXXX@192.168.6.141/1
      - "ffmpeg:front_porch_camera#audio=opus"

cameras:
  driveway:
    timestamp_style:
      position: tr
      color:
        red: 255
        green: 0
        blue: 0
    zones:
      sidewalk:
        coordinates: 409,52,368,17,241,18,227,50
        #coordinates: 114,64,232,57,302,62,409,68,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
        objects:
          - car
      drive_way:
        coordinates: 274,47,441,62,508,76,562,189,550,260,562,286,429,352,0,352,30,207,108,66
        objects:
          - person

    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 114,64,231,43,292,43,364,47,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
          threshold: 0.6
          min_area: 1300
          max_area: 25000
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXX@192.168.6.140/2
          roles:
            - detect
            #- audio
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record

    audio:
      enabled: false
      min_volume: 600
      listen:
        - scream
        - speech
        - yell
    detect:
      width: 640
      height: 360
      fps: 5
   #   stationary:
    #    interval: 0
    #    threshold: 50
    motion:
      mask:
        - 0,0,0.283,0,0.156,0.225,0,0.844
        - 1,0,0.739,0,0.764,0.181,0.892,0.278,1,0.531
        - 0.366,0.039,0.623,0.05,0.787,0.125,0.741,0,0.269,0,0.236,0.075
        - 1,0.677,0.728,0.993,0.998,0.998
      threshold: 30
      contour_area: 26
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - drive_way
        - sidewalk
      timestamp: true
      retain:
        default: 7


################################################ 
    review:
      alerts:
        required_zones:
          - drive_way
          - sidewalk
  front_porch_camera:
    objects:
      track:
        - person
      filters:
        person:
          #threshold: 0.75
          mask:
            - 176,352,171,122,173,12,377,8,518,57,640,168,640,0,0,0,0,352
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:XXXX@192.168.6.141/2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_porch_camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
  
    
    audio:
      enabled: true
      min_volume: 600

    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 176,352,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 7

version: 0.14
camera_groups:
  Home:
    order: 1
    icon: LuCamera
    cameras:
      - driveway
      - front_porch_camera
```

### Relevant Frigate log output

```shell
error
2025-01-07 17:10:10
audio.front_porch_camera
ffmpeg process is not running, restarting...
error
2025-01-07 17:10:20
ffmpeg.front_porch_camera.audio
Output file #0 does not contain any stream
info
2025-01-07 17:10:20
audio.front_porch_camera
Terminating the existing ffmpeg process...
info
2025-01-07 17:10:20
audio.front_porch_camera
Waiting for ffmpeg to exit gracefully...
error
2025-01-07 17:10:23
audio.front_porch_camera
ffmpeg process is not running, restarting...
error
2025-01-07 17:10:33
ffmpeg.front_porch_camera.audio
Output file #0 does not contain any stream
info
2025-01-07 17:10:33
audio.front_porch_camera
Terminating the existing ffmpeg process...
info
2025-01-07 17:10:33
audio.front_porch_camera
Waiting for ffmpeg to exit gracefully...
error
2025-01-07 17:10:37
audio.front_porch_camera
ffmpeg process is not running, restarting...
error
2025-01-07 17:10:47
ffmpeg.front_porch_camera.audio
Output file #0 does not contain any stream
info
2025-01-07 17:10:47
audio.front_porch_camera
Terminating the existing ffmpeg process...
info
2025-01-07 17:10:47
audio.front_porch_camera
Waiting for ffmpeg to exit gracefully...
error
2025-01-07 17:10:50
audio.front_porch_camera
ffmpeg process is not running, restarting...
error
2025-01-07 17:11:00
ffmpeg.front_porch_camera.audio
Output file #0 does not contain any stream
info
2025-01-07 17:11:00
audio.front_porch_camera
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

**Comment by hawkeye217** [comment]
What is the output of `http://frigate_ip:5000/api/go2rtc/streams/front_porch_camera`?

**Reply by B0ndo2** [reply]
Unable to connect

**Reply by hawkeye217** [reply]
If you're running the HA addon, you'll need to open up the port in the addon settings.

**Reply by B0ndo2** [reply]
```
consumers	
0	
medias	
0	"video, sendonly, H264, H265"
1	"audio, sendonly, MPEG4-GENERIC"
remote_addr	"127.0.0.1:55084"
sdp	"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=000001;sprop-parameter-sets=AAAAAWdkACqsLGqB4Aiflm4CAgIE,AAAAAWjuMbIb\r\na=control:trackID=0\r\n"
send	1765479
senders	
0	"96 H264, bytes=1735847, receivers=1"
type	"RTSP passive consumer"
url	"rtsp://127.0.0.1:8554/front_porch_camera"
user_agent	"FFmpeg Frigate/0.14.1-f4f3cfa"
1	
medias	
0	"video, sendonly, ALL"
1	"audio, sendonly, ALL"
2	"audio, recvonly, ANY"
remote_addr	"127.0.0.1:48810"
senders	
0	"96 H264, bytes=0, receivers=1"
1	"97 G726-16/8000, bytes=0, receivers=1"
type	"probe"
user_agent	"python-requests/2.32.3"
producers	
0	
medias	
0	"video, recvonly, H.264 0x00 0.1"
1	"audio, recvonly, G726-16/8000"
receivers	
0	"96 H264, bytes=1735847, senders=2"
1	"97 G726-16/8000, bytes=57440, senders=1"
recv	1832743
remote_addr	"192.168.6.141:554"
sdp	"v=0\r\no=- 38990265062388 38990265062388 IN IP4 192.168.6.141\r\ns=10\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=range:npt=0-\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 packetization-mode=1;profile-level-id=000001;sprop-parameter-sets=AAAAAWdkACqsLGqB4Aiflm4CAgIE,AAAAAWjuMbIb\r\na=framesize:96 1920-1080\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 G726-16/8000\r\na=ptime:20\r\na=fmtp:97 packetization-mode=1\r\n"
type	"RTSP active producer"
url	"rtsp://192.168.6.141/1/"
user_agent	"go2rtc/1.9.2"
1	
url	"ffmpeg:front_porch_camera#audio=opus"``

**Reply by hawkeye217** [reply]
See the camera settings recommendation docs: https://docs.frigate.video/configuration/live/#camera-settings-recommendations

You should ensure the audio coming from your camera is AAC. If you can't change it in firmware, you should transcode it in go2rtc. For example:

```
go2rtc:
  streams:
    ...
    front_porch_camera:
      - ffmpeg:rtsp://admin:XXXX@192.168.6.141/1#video=copy#audio=aac
      - "ffmpeg:front_porch_camera#audio=opus"

**Reply by B0ndo2** [reply]
The audio is either G711 or G726 (now set at G726). I thought I did convert it by using:
``` - "ffmpeg:front_porch_camera#audio=opus"``  ```or otherwise what is this for ?

**Reply by NickM-27** [reply]
if your camera provides pcma then you should change the second stream to be `#audio=aac` instead of opus, that way audio transcoding is only done once

**Reply by hawkeye217** [reply]
> The audio is either G711 or G726 (now set at G726). I thought I did convert it by using: `` - "ffmpeg:front_porch_camera#audio=opus"`` ``or otherwise what is this for ?

Frigate's primary live view mode (MSE) requires AAC audio [[docs](https://docs.frigate.video/configuration/live/#audio-support)], not opus audio. The transcoding to opus audio makes WebRTC support possible.

**Reply by NickM-27** [reply]
Looks like we need to update the docs, MSE also works with PCMA/U via FLAC conversion

**Reply by B0ndo2** [reply]
so it should look like this:
```
go2rtc:
  streams:
    ...
    front_porch_camera:
      - ffmpeg:rtsp://admin:XXXX@192.168.6.141/1#video=copy#audio=aac
      - "ffmpeg:front_porch_camera#audio=aac"
```
Do I need the second ffmpeg if I only want audio in live view and recording ?
