### DISCUSSION TITLE
Snapshots Timing

### DISCUSSION THREAD

**Discussion by daoudeddy** [blakeblackshear/frigate#15888] [Ask A Question] [answered]
**Problem**:
Lately i joined frigate plus membership and I'm very happy with the result but i have a little problem where my snapshot are wrongly timed in the frame here's an example

**Frigate Version**:
0.15 beta

**Review Thumbnail is correct**
![Screenshot from 2025-01-08 10-45-38](https://github.com/user-attachments/assets/15ed099c-0cb7-4a8f-9b8b-699ba0dfd62b)
**Snapshot isn't**
![snapshot(4)](https://github.com/user-attachments/assets/1b2c3c2a-6b78-4f33-af81-3f1f7f26a033)

Config
```
cameras:
  home:
    review: {}
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/home
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_detect
          roles:
            - detect
    onvif:
      host: 10.1.3.XXX
      port: 80
      user: <USERNAME>
      password: <PASSWORD>
      autotracking:
        enabled: true
        zooming: disabled
        calibrate_on_startup: true
        return_preset: Home
        timeout: 15
        track:
          - person
        required_zones:
          - tracking
        movement_weights: 0.0, 1.0, 0.21836066246032715, 0.2725234185495684, 0.03727081667992383
    live:
      stream_name: home
    zones:
      tracking:
        coordinates: 
          0.861,0.839,0.958,0.239,0.744,0.051,0.11,0.265,0.035,0.502,0.059,0.958,0.784,0.958
        inertia: 2
        loitering_time: 0
        objects: person
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    detect:
      annotation_offset: -800
    record:
      enabled: true
      retain:
        days: 1
        mode: all
    genai:
      use_snapshot: true
      objects:
        - car
  office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/office_live
          roles:
            - record
    live:
      stream_name: office_live
    zones:
      Office_Door:
        coordinates: 0.511,0,0.518,0.296,0.848,0.469,0.895,0
        loitering_time: 0
        objects: person
        inertia: 3
      Office:
        coordinates: 
          1,0,1,1,0.166,1,0,0.387,0.003,0.167,0.182,0.041,0.394,0.032,0.507,0.032,0.512,0.145,0.879,0.186,0.905,0
        loitering_time: 0
        objects: person
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: true
      mask: 0,1,0,0,0.681,0,0.678,0.234,0.778,0.286,0.798,0.001,1,0,1,1
    review:
      detections: {}
      alerts:
        required_zones: Office_Door
    objects:
      track:
        - person
        - face
    genai:
      enabled: false
  # office_entrance:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/office_entrance
  #         roles:
  #           - record
  #       - path: rtsp://127.0.0.1:8554/office_entrance_detect
  #         roles:
  #           - detect
  #   live:
  #     stream_name: office_entrance
  #   motion:
  #     threshold: 80
  #     contour_area: 100
  #     improve_contrast: true
  #   objects:
  #     track:
  #       - person
  #       - face
  #   genai:
  #     enabled: false
  office_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office_door
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/office_door_live
          roles:
            - record
    live:
      stream_name: office_door_live
    zones:
      Front_Door:
        coordinates: 1,0.517,0.506,0.244,0,0.247,0,1,1,1
        loitering_time: 0
        objects: person
      Door_Side_Road:
        coordinates: 0,0.247,0,0,1,0,1,0.512,0.503,0.237
        loitering_time: 0
    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
      mask: 
        0.732,0.49,0.769,0.521,0.836,0.499,0.86,0.396,0.856,0.318,0.89,0.269,0.9,0.172,0.911,0.098,0.902,0,0.507,0,0.499,0.06,0.479,0.116,0.462,0.173,0.499,0.224,0.531,0.289,0.547,0.395,0.57,0.495,0.606,0.504,0.639,0.522,0.673,0.522
    review:
      detections: {}
      alerts:
        required_zones: Front_Door
    objects:
      track:
        - person
        - car
        - motorcycle
      mask: 0,0.343,0.101,0.312,0.09,0.125,-0.001,0.146
    detect:
      annotation_offset: -900
    genai:
      enabled: false
  windows:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/windows
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/windows_live
          roles:
            - record
    live:
      stream_name: windows_live
    zones:
      Windows:
        coordinates: 1,0.295,0.915,0.314,0.798,1,1,0.999,1,0.997
        loitering_time: 0
        objects: person
      Church_Side:
        coordinates: 0.795,1,0.914,0.315,1,0.292,1,0,-0.001,0,0,1
        loitering_time: 0
        objects:
          - person
          - car
          - motorcycle
    motion:
      threshold: 30
      contour_area: 20
      improve_contrast: true
    review:
      detections: {}
      alerts:
        required_zones: Windows
    objects:
      track:
        - person
        - car
        - motorcycle
    detect:
      annotation_offset: -900
    genai:
      use_snapshot: true
      objects:
        - car
  backside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backside
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backside_live
          roles:
            - record
    live:
      stream_name: backside_live
    zones:
      Backside:
        coordinates: 0.254,1,0.082,0.12,0.489,0.083,0.965,0.083,0.978,0.275,0.74,1
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      threshold: 50
      contour_area: 20
      improve_contrast: true
      mask: 0,1,0.266,1,0.094,0.132,0.954,0.093,0.97,0.283,0.729,1,1,1,1,0,0,0
    review:
      detections: {}
      alerts:
        required_zones: Backside
    objects:
      track:
        - person
    genai:
      enabled: false
  main_road:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/main_road
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/main_road_live
          roles:
            - record
    live:
      stream_name: main_road_live
    zones:
      Main_Road:
        coordinates: -0.013,0.008,1,-0.005,1,0.457,0,0.569
        loitering_time: 0
        inertia: 3
      Side_Road:
        coordinates: 0.844,0.473,0,0.569,0,1,1,1,1,0.477
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 50
      contour_area: 48
      improve_contrast: true
      mask: 
        0.003,0.82,0.096,0.776,0.074,0.701,0.086,0.643,0.088,0.57,0.062,0.467,0.102,0.398,0.105,0.287,0.067,0.239,0.01,0.287,0,0.364
    review:
      alerts:
        required_zones: Side_Road
      detections: {}
    objects:
      track:
        - person
        - car
        - motorcycle
    detect:
      annotation_offset: -900
    genai:
      use_snapshot: true
      objects:
        - car

detect:
  enabled: true
  fps: 10
  height: 720
  width: 1280
  max_disappeared: 15
  stationary:
    interval: 50
    threshold: 10

motion:
  contour_area: 30
  frame_alpha: 0.2
  frame_height: 100
  threshold: 25
  improve_contrast: true
  lightning_threshold: 0.5
  mqtt_off_delay: 1

objects:
  track:
    - person
    - face
    - license_plate
    - car
    - cat
    - dog
    - motorcycle
    - bicycle
  filters:
    dog:
      min_score: .5
      threshold: .75
    cat:
      min_score: .5
      threshold: .75
    face:
      min_score: .6
    license_plate:
      min_score: .5
    person:
      min_score: .65
      threshold: .80
    car:
      min_score: .65
      threshold: .80
    motorcycle:
      min_score: .65
      threshold: .80
    bicycle:
      min_score: .65
      threshold: .80

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  alerts:
    retain:
      days: 4
  detections:
    retain:
      days: 2

snapshots:
  bounding_box: true
  clean_copy: true
  crop: false
  enabled: true
  height: 720
  timestamp: false
  quality: 100
  retain:
    default: 30
    mode: all

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 8
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 8 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic

go2rtc:
  streams:
    home: ffmpeg:rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX/ch0#video=h264#hardware=vaapi
    home_detect: ffmpeg:rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX/ch1#video=h264#hardware=vaapi
    office_live: 
      ffmpeg:rtsp://127.0.0.1:8554/office#video=h264#width=1280#height=720#hardware=vaapi
    office: rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX:554/Streaming/channels/501
    office_door_live: 
      ffmpeg:rtsp://127.0.0.1:8554/office_door#video=h264#width=1280#height=720#hardware=vaapi
    office_door: rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX:554/Streaming/channels/301
    windows_live: 
      ffmpeg:rtsp://127.0.0.1:8554/windows#video=h264#width=1280#height=720#hardware=vaapi
    windows: rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX:554/Streaming/channels/201
    main_road_live: 
      ffmpeg:rtsp://127.0.0.1:8554/main_road#video=h264#width=1280#height=720#hardware=vaapi
    main_road: rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX:554/Streaming/channels/101
    backside_live: 
      ffmpeg:rtsp://127.0.0.1:8554/backside#video=h264#width=1280#height=720#hardware=vaapi
    backside: rtsp://<USERNAME>:<PASSWORD>@10.1.3.XXX:554/Streaming/channels/401

detectors:
  coral:
    type: edgetpu
    device: usb
    
model:
  path: plus://131500a675a4e3e7b6df744743d751db

mqtt:
  enabled: true
  host: 10.1.3.xxx
  user: <USERNAME>
  password: <PASSWORD>

logger:
  default: info

tls:
  enabled: false
  
semantic_search:
  enabled: true
  reindex: false
  model_size: large

notifications:
  enabled: true
  email: <EMAIL ADDRESS>

genai:
  enabled: true
  provider: gemini
  api_key: <API KEY>
  model: gemini-1.5-flash
  # provider: openai
  # api_key: <API KEY>
  # model: gpt-4o

birdseye:
  enabled: false
  height: 720
  mode: continuous
  quality: 8
  width: 1280

environment_vars:
  PLUS_API_KEY: <PLUS KEY>
  LIBVA_DRIVER_NAME: iHD

version: 0.15-0
```
