### DISCUSSION TITLE
[Camera Support]: Help with webrtc config

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#15898] [Camera Support]
### Describe the problem you are having

I'm running Frigate via Docker on a seperate server from my HA server. It works well except the camera feeds in any card I use (HA's picture card, Frigate card, etc.) are either outright static or very choppy both internal and remote. I feel like I've screwed up the webrtc config somehow, either in my config file or my router settings, but I can't identify anything wrong myself.

The feeds are perfect in the Frigate proxy UI in HA.

I have the extra webrtc config in my config file below and I do have the "Use Frigate-native WebRTC support" box checked in the integration.

Below is the port forward rule in my router settings:

![Screenshot 2025-01-08 130113](https://github.com/user-attachments/assets/027932bf-e682-4279-a9e7-9f16eea99a73)

Please note if relevant:
192.168.107.2 -> HA Server
192.168.107.3 -> Frigate Server

Any suggestions would be awesome. Thanks!

### Version

14

### Frigate config file

```yaml
mqtt:
  host: 192.168.107.2
  port: 1883
  user: <user>
  password: <password>
  topic_prefix: frigate

go2rtc:
  streams:
    FrontPorch:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=0
    FrontPorch_sub:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=1

  webrtc:
    candidates:
      - 192.168.107.3:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    objects:
      track:
        - person
        - dog
        - cat
        - bear
      filters:
        person:
          min_score: 0.7
        dog:
          min_score: 0.7
        cat:
          min_score: 0.7
        bear:
          min_score: 0.7
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Clearview

### Screenshots of the Frigate UI's System metrics pages

n/a
