### DISCUSSION TITLE
Person not detected (multiple times)

### DISCUSSION THREAD

**Discussion by B0ndo2** [blakeblackshear/frigate#15901] [General Support]
### Describe the problem you are having

The person in the photo was not detected on the driveway in more than one instance (over a few days).

There are no errors in the log file, other people are detected right before this person so I feel like it has to do with the colours/shape of the person as it relates to the model ?

![image](https://github.com/user-attachments/assets/6dc25ca8-2e97-4cbe-9ad6-3671336cae90)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
# frigate.yml
detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
logger:
  logs:
    frigate.record.maintainer: debug
mqtt:
  # Required: host name
  host: caha.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: ssss
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
motion:
#  improve_contrast: false
  contour_area: 30
  threshold: 40
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
go2rtc:
  streams:
    driveway:
      - rtsp://admin:XXXX@192.168.6.140/1
    front_porch_camera:
      - rtsp://admin:XXXX@192.168.6.141/1

cameras:
  driveway:
    timestamp_style:
      position: tr
      color:
        red: 255
        green: 0
        blue: 0
    zones:
      sidewalk:
        coordinates: 409,52,368,17,241,18,227,50
        #coordinates: 114,64,232,57,302,62,409,68,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
        objects:
          - car
      drive_way:
        coordinates: 274,47,441,62,508,76,562,189,550,260,562,286,429,352,0,352,30,207,108,66
        objects:
          - person

    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 114,64,231,43,292,43,364,47,430,50,480,62,521,80,553,84,529,51,389,20,242,16,176,25,147,34
          threshold: 0.6
          min_area: 1300
          max_area: 25000
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXX@192.168.6.140/2
          roles:
            - detect
            #- audio
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record

    audio:
      enabled: false
      min_volume: 600
      listen:
        - scream
        - speech
        - yell
    detect:
      width: 640
      height: 360
      fps: 5
   #   stationary:
    #    interval: 0
    #    threshold: 50
    motion:
      mask:
        - 0,0,0.283,0,0.156,0.225,0,0.844
        - 1,0,0.739,0,0.764,0.181,0.892,0.278,1,0.531
        - 0.366,0.039,0.623,0.05,0.787,0.125,0.741,0,0.269,0,0.236,0.075
        - 1,0.677,0.728,0.993,0.998,0.998
      threshold: 30
      contour_area: 26
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - drive_way
        - sidewalk
      timestamp: true
      retain:
        default: 7


################################################ 
    review:
      alerts:
        required_zones:
          - drive_way
          - sidewalk
  front_porch_camera:
    objects:
      track:
        - person
      filters:
        person:
          #threshold: 0.75
          mask:
            - 176,352,171,122,173,12,377,8,518,57,640,168,640,0,0,0,0,352
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:XXXX@192.168.6.141/2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_porch_camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
  
    
    audio:
      enabled: true
      min_volume: 600

    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask:
        - 176,352,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 7

version: 0.14
camera_groups:
  Home:
    order: 1
    icon: LuCamera
    cameras:
      - driveway
      - front_porch_camera
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

Chortau
