### DISCUSSION TITLE
[Config Support]: add duration to review clips

### DISCUSSION THREAD

**Discussion by pwarren** [blakeblackshear/frigate#15905] [Config Support] [answered]
### Describe the problem you are having

The current view of alert clips in the 'review' tab shows the detected object type via an icon, the 'x minutes/hours ago' and timestamp, is it possible to configure this to also show the duration of the clip?

This was available in the previous UI and was helpful.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
timestamp_style:
  format: '%Y-%m-%d %H:%M:%S'

mqtt:
  enabled: true
  host: ashpool.lan

ffmpeg:
  hwaccel_args: preset-vaapi

ui:
  strftime_fmt: '%Y-%m-%d %H:%M'

go2rtc:
  streams:
    corner:
      - rtsp://viewer:Vinezyain9@172.19.107.201:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:corner#audio=opus
    door:
      - rtsp://viewer:Vinezyain9@172.19.107.134:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:door#audio=opus
    drive:
      - rtsp://viewer:Vinezyain9@172.19.107.209:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway#audio=opus
    rear:
      - rtsp://viewer:Vinezyain9@172.19.107.192:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway#audio=opus
    side:
      - rtsp://viewer:Vinezyain9@172.19.107.231:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway#audio=opus
    webrtc:
      listen: :8555
      candidates:
        - 172.19.5.18:8555
        - 2404:e80:2e0:1eaf::18:8555
        - 103.205.29.172:8555

birdseye:
  enabled: true
  mode: continuous
  restream: true

cameras:
  corner:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@172.19.107.201:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/corner
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
# Ignore timestamp
      mask:
        - 868,72,1233,72,1233,26,867,26
# ignore cars (would like a negative config)
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - horse
        - cow
  door:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@172.19.107.134:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/door
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
# ignore timestamp and road
      mask:
        - 868,72,1233,72,1233,26,867,26
        - 0,141,615,77,1280,66,1280,0,578,0,0,0
    objects:
      filters:
# Ignore parked ute
        car:
          mask:
            - 898,471,1280,444,1280,95,902,137
# Zone where I care about people coming up the drive
    zones:
      driveway:
        coordinates: 563,0,1280,0,1280,720,551,720,46,720,283,0
    review:
      alerts:
        required_zones: driveway
  drive:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@172.19.107.209:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/drive
          input_args: preset-rtsp-restream
          roles:
            - record
    # Ignore timestamp
    motion:
      mask:
        - 868,72,1233,72,1233,26,867,26
  rear:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@172.19.107.192:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/rear
          input_args: preset-rtsp-restream
          roles:
            - record
    # Ignore timestamp
    motion:
      mask:
        - 868,72,1233,72,1233,26,867,26
    objects:
      filters:
        car:
          mask:
            - 1254,178,1031,78,941,250,1073,332
  side:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@172.19.107.231:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/side
          input_args: preset-rtsp-restream
          roles:
            - record
    # Ignore timestamp
    motion:
      mask:
        - 868,72,1233,72,1233,26,867,26
detectors:
#  cpu1:
#    type: cpu
#    num_threads: 6
#  cpu2:
#    type: cpu
#    num_threads: 6
#  ov1:
#    type: openvino
#    device: AUTO
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml
  coral1:
    type: edgetpu
    device: pci

#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
    - horse
    - cow
  filters:
    person:
      max_area: 250000
      min_area: 3000
    bird:
      min_area: 1200

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 21
      mode: active_objects
    pre_capture: 5
    post_capture: 15
version: 0.14
```

### Relevant Frigate log output

```shell
please let me know if you think this log output would be relevant
```

### Relevant go2rtc log output

```shell
please let me know if you think this log output would be relevant
```

### Frigate stats

```json
{"cameras":{"corner":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":689,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":1500716,"pid":656,"process_fps":5.0,"skipped_fps":0.0},"door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":699,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":1500664,"pid":662,"process_fps":5.1,"skipped_fps":0.0},"drive":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":703,"detection_enabled":true,"detection_fps":1.1,"ffmpeg_pid":712,"pid":665,"process_fps":5.1,"skipped_fps":0.0},"rear":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":707,"detection_enabled":true,"detection_fps":0.2,"ffmpeg_pid":724,"pid":673,"process_fps":5.1,"skipped_fps":0.0},"side":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":713,"detection_enabled":true,"detection_fps":0.1,"ffmpeg_pid":725,"pid":681,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"108":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"113":{"cmdline":"python3 -u -m frigate","cpu":"3.0","cpu_average":"3","mem":"1.0"},"12137":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"133":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1500664":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@172.19.107.134:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.0"},"1500666":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/door@%Y%m%d%H%M%S%z.mp4","cpu":"2.0","cpu_average":"1","mem":"0.0"},"1500716":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@172.19.107.201:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.0","cpu_average":"1","mem":"0.0"},"1500719":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/corner -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/corner@%Y%m%d%H%M%S%z.mp4","cpu":"1.9","cpu_average":"1","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"306":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"307":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.0"},"308":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"309":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"312":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"440":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"469":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"0.0"},"50":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"566":{"cmdline":"frigate.recording_manager","cpu":"7.5","cpu_average":"7","mem":"0.3"},"575":{"cmdline":"frigate.review_segment_manager","cpu":"0.7","cpu_average":"0","mem":"0.0"},"594":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(65)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"595":{"cmdline":"frigate.detector.coral1","cpu":"0.3","cpu_average":"3","mem":"0.0"},"597":{"cmdline":"frigate.output       ","cpu":"9.9","cpu_average":"13","mem":"0.1"},"615":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"621":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"626":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"631":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"636":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"641":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"3.5","cpu_average":"4","mem":"0.0"},"656":{"cmdline":"frigate.process:corner","cpu":"1.4","cpu_average":"2","mem":"0.1"},"662":{"cmdline":"frigate.process:door ","cpu":"1.4","cpu_average":"10","mem":"0.2"},"665":{"cmdline":"frigate.process:drive","cpu":"3.6","cpu_average":"9","mem":"0.2"},"673":{"cmdline":"frigate.process:rear ","cpu":"2.4","cpu_average":"12","mem":"0.1"},"681":{"cmdline":"frigate.process:side ","cpu":"2.0","cpu_average":"28","mem":"0.2"},"689":{"cmdline":"frigate.capture:corner","cpu":"1.9","cpu_average":"1","mem":"0.0"},"699":{"cmdline":"frigate.capture:door ","cpu":"1.8","cpu_average":"1","mem":"0.0"},"703":{"cmdline":"frigate.capture:drive","cpu":"1.8","cpu_average":"1","mem":"0.0"},"707":{"cmdline":"frigate.capture:rear ","cpu":"1.8","cpu_average":"1","mem":"0.0"},"712":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@172.19.107.209:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"2","mem":"0.0"},"713":{"cmdline":"frigate.capture:side ","cpu":"1.8","cpu_average":"1","mem":"0.0"},"717802":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"717812":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"724":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@172.19.107.192:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.0"},"725":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@172.19.107.231:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.6","cpu_average":"1","mem":"0.0"},"732":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/drive -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/drive@%Y%m%d%H%M%S%z.mp4","cpu":"1.9","cpu_average":"1","mem":"0.0"},"735":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rear -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/rear@%Y%m%d%H%M%S%z.mp4","cpu":"2.0","cpu_average":"1","mem":"0.0"},"736":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side@%Y%m%d%H%M%S%z.mp4","cpu":"1.9","cpu_average":"1","mem":"0.0"},"86":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"93":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"42.8","cpu_average":"42","mem":"0.1"},"frigate.full_system":{"cpu":"8.8","mem":"55.7"}},"detection_fps":1.4,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.22,"pid":595}},"gpu_usages":{"amd-vaapi":{"gpu":"1.67%","mem":"4.03%"}},"processes":{"go2rtc":{"pid":97},"logger":{"pid":469},"recording":{"pid":566},"review_segment":{"pid":575}},"service":{"last_updated":1736378589,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":492.3,"mount_type":"tmpfs","total":512.0,"used":19.7},"/media/frigate/clips":{"free":11166888.5,"mount_type":"xfs","total":30520982.0,"used":19354093.5},"/media/frigate/recordings":{"free":11166888.5,"mount_type":"xfs","total":30520982.0,"used":19354093.5},"/tmp/cache":{"free":871.5,"mount_type":"tmpfs","total":953.7,"used":82.1}},"temperatures":{"apex_0":43.8},"uptime":3553405,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
cat docker-compose.yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For AMDGPU hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /bucket/frigate/config:/config
      - /bucket/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "Vinezyain9"
      LIBVA_DRIVER_NAME: "radeonsi" # Also needed for AMDGPU hwaccel
```

### Object Detector

Coral
