### DISCUSSION TITLE
Frigate+ score / Review discrepency

### DISCUSSION THREAD

**Discussion by jamesonuk** [blakeblackshear/frigate#15911] [Ask A Question]
I have a camera which is giving lots of false positives but I think they should have been filtered out.
Eg. when I look in Frigate+ tab I see 
![f+](https://github.com/user-attachments/assets/7bbb9677-4170-4ed8-b0c1-b5f530f627fe)
so only one entry for today with a score of 52%
but I am seeing lots of reviews
![review](https://github.com/user-attachments/assets/5ec1583d-93f9-481d-8f99-240442bb16d7)
I don't have any global config around objects, thresholds, min scores etc. and the camera config is

<details>

<summary>Camera config</summary>

```yaml
  xxx_camera_frigate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@xxx-tapo-camera.mikeynet/stream2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/xxx_camera_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: xxx-tapo-camera.mikeynet
      port: 2020
      user: '{FRIGATE_TAPO_USER}'
      password: '{FRIGATE_TAPO_PWD}'
    motion:
      mask:
        - 0,54,462,54,462,0,0,0,0,0
```

</details>

so I believe everything should be using defaults and this should therefore be using a threshold of 0.7 ?   I am not seeing anything in Frigate + that is anywhere near 70% so I would have thought these should be excluded??   Am I missing something in the application of `threshold` or how the Frigate + entries are added?

**Comment by hawkeye217** [comment]
Have a look at the docs related to object scores: https://docs.frigate.video/configuration/object_filters

At some point, your object was detected with a score >= threshold, so the object was considered a true positive and the snapshot was created.

**Reply by jamesonuk** [reply]
> At some point, your object was detected with a score >= threshold, so the object was considered a true positive and the snapshot was created.

But why is there nothing in Frigate + ?    You can see in the timeline that there are a few different blocks (hence it must have triggered multiple times) but there is not a single entry in the Frigate + screen in this time frame

**Reply by hawkeye217** [reply]
It'd be helpful to see your full config. 

But in general this situation can be better diagnosed in 0.15 with the Object Lifecycle feature.

**Reply by NickM-27** [reply]
The reason is because the object is stationary so it gets a single snapshot but any time the bounding box changes, which is seen as activity, a review item is created for that time.

**Reply by jamesonuk** [reply]
> It'd be helpful to see your full config.
> 
> But in general this situation can be better diagnosed in 0.15 with the Object Lifecycle feature.

Nothing really that isn't default

<details>

<summary>Full Config</summary>

```yaml
mqtt:
  enabled: true
  host: mosquitto
  port: 8883
  tls_ca_certs: /config/mqtt_certs/root-ca.pem
  tls_client_cert: /config/mqtt_certs/ha_mqtt.cert.pem
  tls_client_key: /config/mqtt_certs/ha_mqtt.key.pem

go2rtc:
  streams:
    xxx_camera_frigate:
      - rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@xxx-tapo-camera.mikeynet/stream1
      - ffmpeg:xxx_camera_frigate#audio=aac#audio=copy
  webrtc:
    candidates:
      - 10.99.99.7:8555
      - 192.168.40.201:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb


ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  expire_interval: 1440
  retain:
    days: 7
    mode: motion

detect:
  enabled: true

snapshots:
  enabled: true

cameras:
  xxx_camera_frigate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@xxx-tapo-camera.mikeynet/stream2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/xxx_camera_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: xxx-tapo-camera.mikeynet
      port: 2020
      user: '{FRIGATE_TAPO_USER}'
      password: '{FRIGATE_TAPO_PWD}'
    motion:
      mask:
        - 0,54,462,54,462,0,0,0,0,0
```

</details>
