### DISCUSSION TITLE
[Config Support]: dewarp 360 camera using intel's QSV

### DISCUSSION THREAD

**Discussion by gaynetdinov** [blakeblackshear/frigate#15920] [Config Support] [answered]
### Describe the problem you are having

Hey folks!

After you helped me to fix my QSV config in previous thread https://github.com/blakeblackshear/frigate/discussions/15861 I would like to finally try to dewarp my 360 reolink fe-p camera. 

I have a command that works on my mac when I connect to go2rtc stream of my frigate instance. I can see the output exactly how I want it to be
```
ffplay -v verbose -i rtsp://192.168.2.56:8554/hall_sub -vf "v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy"
```

Then it seems like I figured out all the quirks regarding QSV hardware acceleration and this command works in the frigate docker instance

```
./ffmpeg -v verbose -hwaccel qsv -bsf:v dump_extra -i rtsp://localhost:8554/hall_sub -vf "hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -r 10 -b:v 3M -maxrate 3M -bufsize 6M -c:v h264_qsv -flags +cgop -f null -
```
no errors about DTS or bad filters, I will attach of this output to the go2rtc log output section below.

But when I put this ffmpeg arguments to frigate config, it does not work.
What should I do? Should I use presets? Should I override the ffmpeg's `hwaccel_args`? 
You help would be highly appreciated!
Thank you!

### Version

0.15-beta4

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  global_args: -hide_banner -loglevel warning -threads 4 -bsf:v dump_extra

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: plus://

model:
  path: plus://

go2rtc:
  streams:
    carport:
      - ffmpeg:https://192.168.2.184/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pass#video=copy#audio=copy#audio=opus
    carport_sub:
      - ffmpeg:https://192.168.2.184/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=pass
    hall:
      - ffmpeg:https://192.168.2.204/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pass#video=copy#audio=copy#audio=opus
    hall_sub:
      - ffmpeg:https://192.168.2.204/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=pass
    doorbell:
      - ffmpeg:rtsp://admin:pass@192.168.2.183/Streaming/Channels/101/
    doorbell_sub:
      - ffmpeg:rtsp://admin:pass@192.168.2.183/Streaming/Channels/102/

cameras:
  doorbell:
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    objects:
      track:
        - amazon
        - dhl
        - usps
        - ups
        - fedex
        - gls
        - dpd
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask: 0.673,0.767,0.974,0.764,0.974,0.826,0.674,0.825

  hall:
    detect:
      width: 1024
      height: 1024
    record:
      enabled: true
      retain:
        days: 3
        mode: motion

    objects:
      track:
        - person
        - cat
        - face

   ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hall
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record

        - path: rtsp://127.0.0.1:8554/hall_sub
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - detect

        #output_args:
          # record: -vf "hwdownload,format=nv12,format=yuv420p,v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -f segment -segment_time 10 -segment_format mp4

          #record: -vf hwdownload,format=nv12,format=yuv420p,v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1
          #detect: -vf "hwdownload,format=nv12,format=yuv420p,v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -r 10 -b:v 3M -maxrate 3M -bufsize 6M -c:v h264_qsv -f rawvideo -flags +cgop
        #record: -vf "v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_qsv
        #detect: -vf "v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1
        # -vf "hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -r 10 -b:v 3M -maxrate 3M -bufsize 6M -c:v h264_qsv -flags +cgop

 carport:
    objects:
      track:
        - person
        - cat
        - car
        - dog
        - bicycle
        - fox
        - raccoon
        - squirrel
        - rabbit
        - umbrella
        - motorcycle
        - license_plate
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record

        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask:
        - 0.708,0,0.707,0.079,0.287,0.08,0.285,0
        - 0.187,0.379,0.193,0.452,0.124,0.495,0.1,0.192,0.35,0.192,0.355,0.281
      threshold: 40
      contour_area: 20
      improve_contrast: true
    zones:
      Carport:
        coordinates:
          0.132,0.497,0.197,0.462,0.185,0.386,0.269,0.323,0.355,0.292,1,0.736,0.997,0.997,0.215,0.993
        loitering_time: 0
        inertia: 3
    review:
      alerts: {}
      detections: {}
    record:
      enabled: true
      retain:
        days: 3
        mode: all

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  crop: true
  quality: 100
  retain:
    default: 60


review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - car
      - person
      - cat
      - fox
      - raccoon
      - squirrel
      - rabbit

version: 0.15-4
semantic_search:
  enabled: true
  reindex: true
  model_size: small
```

### Relevant Frigate log output

```shell
frigate  | 2025-01-09 17:34:48.371493665  [2025-01-09 17:34:48] ffmpeg.hall.audio_record       ERROR   : Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
frigate  | 2025-01-09 17:34:48.378154763  [2025-01-09 17:34:48] ffmpeg.hall.audio_record       ERROR   : [vf#0:0 @ 0x63db01909740] Error reinitializing filters!
frigate  | 2025-01-09 17:34:48.378443286  [2025-01-09 17:34:48] ffmpeg.hall.audio_record       ERROR   : [vf#0:0 @ 0x63db01909740] Task finished with error code: -38 (Function not implemented)
frigate  | 2025-01-09 17:34:48.378627328  [2025-01-09 17:34:48] ffmpeg.hall.audio_record       ERROR   : [vf#0:0 @ 0x63db01909740] Terminating thread with return code -38 (Function not implemented)
frigate  | 2025-01-09 17:34:48.378629700  [2025-01-09 17:34:48] ffmpeg.hall.audio_record       ERROR   : [vost#0:0/libx264 @ 0x63db0190f3c0] Could not open encoder before EOF
```

### Relevant go2rtc log output

```shell
root@5c8409d55e23:/usr/lib/ffmpeg/7.0/bin# ./ffmpeg -v verbose -hwaccel qsv -bsf:v dump_extra -i rtsp://localhost:8554/hall_sub -vf "hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=30:pitch=20:rorder=rpy" -r 10 -b:v 3M -maxrate 3M -bufsize 6M -c:v h264_qsv -flags +cgop -f null -
ffmpeg version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[tcp @ 0x61c30b6b3880] Starting connection attempt to ::1 port 8554
[tcp @ 0x61c30b6b3880] Successfully connected to ::1 port 8554
[rtsp @ 0x61c30b6b2e80] SDP:
v=0
o=- 1 1 IN IP4 0.0.0.0
s=go2rtc/1.9.2
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKBAAgZA,aO48sA==; profile-level-id=640033
a=control:trackID=0
m=audio 0 RTP/AVP 97
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408
a=control:trackID=1
[rtsp @ 0x61c30b6b2e80] method SETUP failed: 461 Unsupported transport
[rtsp @ 0x61c30b6b2e80] setting jitter buffer size to 0
    Last message repeated 1 times
[h264 @ 0x61c30b6b4740] Reinit context to 1024x1024, pix_fmt: yuv420p
[rtsp @ 0x61c30b6b2e80] max_analyze_duration 5000000 reached at 5056000 microseconds st:1
[vist#0:0/h264 @ 0x61c30b6e09c0] WARNING: defaulting hwaccel_output_format to qsv for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format qsv".
Selecting decoder 'h264_qsv' because of requested hwaccel method qsv
Input #0, rtsp, from 'rtsp://localhost:8554/hall_sub':
  Metadata:
    title           : go2rtc/1.9.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), 1 reference frame, yuv420p(progressive), 1024x1024, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
[out#0/null @ 0x61c30b6f4000] No explicit maps, mapping streams automatically...
[vost#0:0/h264_qsv @ 0x61c30b6e1400] Created video stream from input stream 0:0
[AVHWDeviceContext @ 0x61c30b721580] Trying to use DRM render node for device 0, with matching kernel driver (i915).
[AVHWDeviceContext @ 0x61c30b721580] libva: VA-API version 1.22.0
[AVHWDeviceContext @ 0x61c30b721580] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x61c30b721580] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x61c30b721580] libva: Found init function __vaDriverInit_1_22
[AVHWDeviceContext @ 0x61c30b721580] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x61c30b721580] Initialised VAAPI connection: version 1.22
[AVHWDeviceContext @ 0x61c30b721580] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ().
[AVHWDeviceContext @ 0x61c30b721580] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x61c30b6f2080] Use Intel(R) oneVPL to create MFX session, API version is 2.13, the required implementation version is 1.3
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
[AVHWDeviceContext @ 0x61c30b6f2080] Initialize MFX session: implementation version is 2.11
[h264_mp4toannexb @ 0x61c30bd03200] The input looks like it is Annex B already
[aost#0:1/pcm_s16le @ 0x61c30bd04200] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
[vost#0:0/h264_qsv @ 0x61c30b6e1400] Starting thread...
[aost#0:1/pcm_s16le @ 0x61c30bd04200] Starting thread...
[vf#0:0 @ 0x61c30b74c240] Starting thread...
[af#0:1 @ 0x61c30ba09b00] Starting thread...
[vist#0:0/h264 @ 0x61c30b6e09c0] [dec:h264_qsv @ 0x61c30b843b00] Starting thread...
[aist#0:1/aac @ 0x61c30b720cc0] [dec:aac @ 0x61c30ba6dd00] Starting thread...
[in#0/rtsp @ 0x61c30b6b2b40] Starting thread...
Press [q] to stop, [?] for help
[AVHWDeviceContext @ 0x7d4abc002d40] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ().
[AVHWDeviceContext @ 0x7d4abc002d40] Driver not found in known nonstandard list, using standard behaviour.
[h264_qsv @ 0x61c30b8444c0] Decoder: output is video memory surface
[h264_qsv @ 0x61c30b8444c0] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[graph_1_in_0:1 @ 0x7d4ac4003080] tb:1/16000 samplefmt:fltp samplerate:16000 chlayout:mono
[format_out_0_1 @ 0x7d4ac4004280] auto-inserting filter 'auto_aresample_0' between the filter 'Parsed_anull_0' and the filter 'format_out_0_1'
[auto_aresample_0 @ 0x7d4ac4005d80] ch:1 chl:mono fmt:fltp r:16000Hz -> ch:1 chl:mono fmt:s16 r:16000Hz
[h264_qsv @ 0x61c30b8444c0] More data is required to decode header
    Last message repeated 34 times
[AVHWDeviceContext @ 0x7d4abc0144c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ().
[AVHWDeviceContext @ 0x7d4abc0144c0] Driver not found in known nonstandard list, using standard behaviour.
[h264_qsv @ 0x61c30b8444c0] Decoder: output is video memory surface
[h264_qsv @ 0x61c30b8444c0] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[graph 0 input from stream 0:0 @ 0x7d4acc005a40] w:1024 h:1024 pixfmt:qsv tb:1/90000 fr:25/1 sar:0/1 csp:unknown range:tv
[auto_scale_0 @ 0x7d4acc001a40] w:iw h:ih flags:'' interl:0
[Parsed_v360_2 @ 0x7d4acc003d80] auto-inserting filter 'auto_scale_0' between the filter 'Parsed_format_1' and the filter 'Parsed_v360_2'
[auto_scale_1 @ 0x7d4acc017e80] w:iw h:ih flags:'' interl:0
[format @ 0x7d4acc0074c0] auto-inserting filter 'auto_scale_1' between the filter 'Parsed_v360_2' and the filter 'format'
[auto_scale_0 @ 0x7d4acc001a40] w:1024 h:1024 fmt:nv12 csp:unknown range:tv sar:0/1 -> w:1024 h:1024 fmt:yuv420p csp:unknown range:tv sar:0/1 flags:0x00000004
[auto_scale_1 @ 0x7d4acc017e80] w:2048 h:1024 fmt:yuv420p csp:unknown range:tv sar:0/1 -> w:2048 h:1024 fmt:nv12 csp:unknown range:tv sar:0/1 flags:0x00000004
[graph 0 input from stream 0:0 @ 0x7d4acc005a40] video frame properties congruent with link at pts_time: 3.519
[AVHWFramesContext @ 0x7d4abc015180] Use Intel(R) oneVPL to create MFX session, API version is 2.13, the required implementation version is 2.11
[AVHWFramesContext @ 0x7d4abc015180] Initialize MFX session: implementation version is 2.11
[vost#0:0/h264_qsv @ 0x61c30b6e1400] *** 35 dup!
[h264_qsv @ 0x61c30b6efcc0] Using device qsv0 (type qsv) with h264_qsv encoder.
[h264_qsv @ 0x61c30b6efcc0] Encoder: input is system memory surface
[h264_qsv @ 0x61c30b6efcc0] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[h264_qsv @ 0x61c30b6efcc0] Using the constant bitrate (CBR) ratecontrol method
[h264_qsv @ 0x61c30b6efcc0] profile: avc high; level: 40
[h264_qsv @ 0x61c30b6efcc0] GopPicSize: 256; GopRefDist: 3; GopOptFlag: closed; IdrInterval: 0
[h264_qsv @ 0x61c30b6efcc0] TargetUsage: 4; RateControlMethod: CBR
[h264_qsv @ 0x61c30b6efcc0] BufferSizeInKB: 750; InitialDelayInKB: 562; TargetKbps: 3000; MaxKbps: 3000; BRCParamMultiplier: 1
[h264_qsv @ 0x61c30b6efcc0] NumSlice: 1; NumRefFrame: 2
[h264_qsv @ 0x61c30b6efcc0] RateDistortionOpt: OFF
[h264_qsv @ 0x61c30b6efcc0] RecoveryPointSEI: OFF
[h264_qsv @ 0x61c30b6efcc0] VDENC: OFF
[h264_qsv @ 0x61c30b6efcc0] Entropy coding: CABAC; MaxDecFrameBuffering: 2
[h264_qsv @ 0x61c30b6efcc0] NalHrdConformance: ON; SingleSeiNalUnit: ON; VuiVclHrdParameters: OFF VuiNalHrdParameters: ON
[h264_qsv @ 0x61c30b6efcc0] FrameRateExtD: 1; FrameRateExtN: 10
[h264_qsv @ 0x61c30b6efcc0] IntRefType: 0; IntRefCycleSize: 0; IntRefQPDelta: 0
[h264_qsv @ 0x61c30b6efcc0] MaxFrameSize: 0; MaxSliceSize: 0
[h264_qsv @ 0x61c30b6efcc0] BitrateLimit: ON; MBBRC: OFF; ExtBRC: OFF
[h264_qsv @ 0x61c30b6efcc0] Trellis: auto
[h264_qsv @ 0x61c30b6efcc0] RepeatPPS: OFF; NumMbPerSlice: 0; LookAheadDS: 2x
[h264_qsv @ 0x61c30b6efcc0] AdaptiveI: OFF; AdaptiveB: OFF; BRefType:off
[h264_qsv @ 0x61c30b6efcc0] MinQPI: 0; MaxQPI: 0; MinQPP: 0; MaxQPP: 0; MinQPB: 0; MaxQPB: 0
[h264_qsv @ 0x61c30b6efcc0] DisableDeblockingIdc: 0
[h264_qsv @ 0x61c30b6efcc0] SkipFrame: no_skip
[h264_qsv @ 0x61c30b6efcc0] PRefType: default
[h264_qsv @ 0x61c30b6efcc0] TransformSkip: unknown
[h264_qsv @ 0x61c30b6efcc0] IntRefCycleDist: 0
[h264_qsv @ 0x61c30b6efcc0] LowDelayBRC: OFF
[h264_qsv @ 0x61c30b6efcc0] MaxFrameSizeI: 0; MaxFrameSizeP: 0
[h264_qsv @ 0x61c30b6efcc0] ScenarioInfo: 0
Output #0, null, to 'pipe:':
  Metadata:
    title           : go2rtc/1.9.2
    encoder         : Lavf61.1.100
  Stream #0:0: Video: h264, 1 reference frame, nv12(tv, progressive), 2048x1024, q=2-31, 3000 kb/s, 10 fps, 10 tbn
      Metadata:
        encoder         : Lavc61.3.100 h264_qsv
      Side data:
        cpb: bitrate max/min/avg: 3000000/0/3000000 buffer size: 6000000 vbv_delay: N/A
  Stream #0:1: Audio: pcm_s16le, 16000 Hz, mono, s16, 256 kb/s
      Metadata:
        encoder         : Lavc61.3.100 pcm_s16le
[out#0/null @ 0x61c30b6f4000] Starting thread...
[in#0/rtsp @ 0x61c30b6b2b40] Terminating thread with return code 0 (success)0 speed=1.18x
[vist#0:0/h264 @ 0x61c30b6e09c0] [dec:h264_qsv @ 0x61c30b843b00] Decoder thread received EOF packet
[aist#0:1/aac @ 0x61c30b720cc0] [dec:aac @ 0x61c30ba6dd00] Decoder thread received EOF packet
[aist#0:1/aac @ 0x61c30b720cc0] [dec:aac @ 0x61c30ba6dd00] Decoder returned EOF, finishing
[aist#0:1/aac @ 0x61c30b720cc0] [dec:aac @ 0x61c30ba6dd00] Terminating thread with return code 0 (success)
[af#0:1 @ 0x61c30ba09b00] Filtergraph returned EOF, finishing
[af#0:1 @ 0x61c30ba09b00] All consumers returned EOF
[aost#0:1/pcm_s16le @ 0x61c30bd04200] Encoder thread received EOF
[aost#0:1/pcm_s16le @ 0x61c30bd04200] Terminating thread with return code 0 (success)
[af#0:1 @ 0x61c30ba09b00] Terminating thread with return code 0 (success)
[vist#0:0/h264 @ 0x61c30b6e09c0] [dec:h264_qsv @ 0x61c30b843b00] Decoder returned EOF, finishing
[vist#0:0/h264 @ 0x61c30b6e09c0] [dec:h264_qsv @ 0x61c30b843b00] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x61c30b74c240] Filtergraph returned EOF, finishing
[vf#0:0 @ 0x61c30b74c240] All consumers returned EOF
[vost#0:0/h264_qsv @ 0x61c30b6e1400] Encoder thread received EOF
[vf#0:0 @ 0x61c30b74c240] Terminating thread with return code 0 (success)
[vost#0:0/h264_qsv @ 0x61c30b6e1400] Terminating thread with return code 0 (success)
[out#0/null @ 0x61c30b6f4000] All streams finished
[out#0/null @ 0x61c30b6f4000] Terminating thread with return code 0 (success)
[out#0/null @ 0x61c30b6f4000] Output file #0 (pipe:):
[out#0/null @ 0x61c30b6f4000]   Output stream #0:0 (video): 196 frames encoded; 196 packets muxed (7165539 bytes);
[out#0/null @ 0x61c30b6f4000]   Output stream #0:1 (audio): 306 frames encoded (313344 samples); 306 packets muxed (626688 bytes);
[out#0/null @ 0x61c30b6f4000]   Total: 502 packets (7792227 bytes) muxed
[out#0/null @ 0x61c30b6f4000] video:6998KiB audio:612KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame=  196 fps= 13 q=13.0 Lsize=N/A time=00:00:19.40 bitrate=N/A dup=35 drop=0 speed=1.33x
[in#0/rtsp @ 0x61c30b6b2b40] Input file #0 (rtsp://localhost:8554/hall_sub):
[in#0/rtsp @ 0x61c30b6b2b40]   Input stream #0:0 (video): 197 packets read (649605 bytes); 161 frames decoded; 0 decode errors;
[in#0/rtsp @ 0x61c30b6b2b40]   Input stream #0:1 (audio): 306 packets read (156672 bytes); 306 frames decoded; 0 decode errors (313344 samples);
[in#0/rtsp @ 0x61c30b6b2b40]   Total: 503 packets (806277 bytes) demuxed
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/damirca/frigate/config:/config
      - /home/damirca/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - PLUS_API_KEY=blah
```

### Object Detector

OpenVino

**Comment by NickM-27** [comment]
If you are using a preset you don't have control over any video filters. Realistically, I would suggest doing the dewarping in go2rtc and then just pull that feed directly into frigate. That way dewarping only needs to be done once

**Reply by gaynetdinov** [reply]
> If you are using a preset you don't have control over any video filters.
does it mean that I'd have to simply copy paste actual ffmpeg arguments from preset into `hwaccel_args` inside specific camera config like so

```
ffmpeg:
      ffmpeg:
         hwaccel_args: ["-c:v", "qsv", "-bsf:v", "dump_extra", etc, etc, etc]
      inputs:
        - path: rtsp://127.0.0.1:8554/hall
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record

        - path: rtsp://127.0.0.1:8554/hall_sub
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - detect
```

But if I want to have 2 streams out of 360 camera? I mean my current filter simply 'cuts out' one part of 360 picture. I thought go2rtc is exactly what I need for that so I could use local stream twice. Would that work?

**Reply by gaynetdinov** [reply, marked as answer]
I think I figured it out.
I was not aware that one could build streams on top of another streams within go2rtc config, I thought one could use one defined stream in go2rtc multiple times in `cameras` setup. Also I was not aware of go2rtc's `exec` feature. With it it's much much simpler to apply sophisticated filters to the streams.

Original resolution of the main stream of the camera is 2560x2560, however qsv cannot handle such resolution, so I have to scale down to 1920x1920 using `vpp_qsv=w=1920:h=1920`. Then I use `vpp_qsv` once again to have proper resolution of the output stream.

```
go2rtc:
  streams:
    hall:
      - ffmpeg:https://192.168.2.204/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=pass#video=copy#audio=copy#audio=opus
    hall_sub:
      - ffmpeg:https://192.168.2.204/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=pass
  

    frontdoor: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hwaccel qsv -bsf:v dump_extra -i rtsp://localhost:8554/hall -vf "vpp_qsv=w=1920:h=1920,hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=45:pitch=23:rorder=rpy,vpp_qsv=w=1920:h=1080" -c:v h264_qsv -f rtsp {{output}}

    frontdoor_sub: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hwaccel qsv -bsf:v dump_extra -i rtsp://localhost:8554/hall_sub -vf "hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=45:pitch=23:rorder=rpy,vpp_qsv=w=1920:h=1080" -r 10 -c:v h264_qsv -f rtsp {{output}}

    frontdoor_back: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hwaccel qsv -bsf:v dump_extra -i rtsp://localhost:8554/hall -vf "vpp_qsv=w=1920:h=1920,hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=-120:pitch=23:rorder=rpy,vpp_qsv=w=1920:h=1080" -c:v h264_qsv -f rtsp {{output}}

    frontdoor_back_sub: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hwaccel qsv -bsf:v dump_extra -i rtsp://localhost:8554/hall_sub -vf "hwdownload,format=nv12,v360=fisheye:flat:id_fov=180:d_fov=90:roll=-120:pitch=23:rorder=rpy,vpp_qsv=w=1920:h=1080" -r 10 -c:v h264_qsv -f rtsp {{output}}
```

Unfortunately my i5-12500 is having hard times processing 4 streams out of 2, Frigate reports around 50-60% CPU and 20-30% GPU load. So I decided to use substreams as source for 2 new dewarp 'cameras' and one main stream with good quality only for recording.

```
cameras:
  hall:
    detect:
      enabled: false
    motion:
      enabled: false
    record:
      enabled: true
      retain:
        days: 3
        mode: all

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hall
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - record
            - audio

  frontdoor:
    record:
      enabled: true
      retain:
        days: 3
        mode: motion

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - record
            - audio
            - detect

  frontdoor_back:
    record:
      enabled: true
      retain:
        days: 3
        mode: motion

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_back_sub
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - record
            - audio
            - detect
```

With this setup I have detections and high quality recording (granted in 360 form) and Frigate reports not more than 20% CPU and around 5-15% GPU load handling in total of 5 cameras (2 real ones and 3 'cameras' made from a single fisheye camera).

@NickM-27 I'd happy to know if there are any tips how to make this setup less CPU intensive. Would dedicated GPU help here? Thank you!
