### DISCUSSION TITLE
[Support]: I need help passing in an external harddrive

### DISCUSSION THREAD

**Discussion by shwarnock** [blakeblackshear/frigate#15922] [General Support]
### Describe the problem you are having

I am running into issues getting an external hard drive passed into frigate. I am running frigate on a proxmox LXC container that is running docker compose. (Built from the tteck script). I have added a directory on the host that is the external harddrive. I see that media storage in proxmox and it has the proper size. I then added a mount point into the the frigate lxc container. I am able to verify that the directory exists on the proxmox node. I can create files and see those show up in the proxmox host's directory . I then add the volume into the docker compose file `- /frigate_media:/frigate/media`. However, when I load frigate and go to the storage tab, I only see the internal harddrive that the proxmox container runs on. Not sure what I am doing wrong. Any help would be appreciated!

I then add

### Version

0-14.1-

### What browser(s) are you using?

Google Chrome

### Frigate config file

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
version: "3"
services:
  devcontainer:
    container_name: frigate-devcontainer
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: yolov7-320
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /frigate_media:/media/frigate:rw
      - /dev/bus/usb:/dev/bus/usb
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink 

### Any other information that may be helpful

![Screenshot 2025-01-09 183240](https://github.com/user-attachments/assets/4b1e7081-9b08-4dd5-b720-a7acee730647)

**Comment by hawkeye217** [comment]
Proxmox is not an officially supported installation method, but some users may be able to help. However, you have pasted the `frigate-devcontainer` docker compose file, which is incorrect. You need to use the docker compose file outlined in the Frigate documentation: https://docs.frigate.video/guides/getting_started/#setup-directories

**Reply by shwarnock** [reply]
I am pretty sure this is the correct docker-compose file. It is the one that exists in /opt/frigate. I have added my coral TPU passthrough here and that worked fine. Maybe the frigate proxmox script is doing some special handling for the harddrive mounts?

**Reply by hawkeye217** [reply]
You may want to post on the proxmox community scripts github for help with the script itself. Frigate doesn't develop or provide official support for that.

**Reply by fatcat** [reply]
This is my docker compose file for frigate 15 beta3, but the "volumes" section is unchanged from version 14 to 15. /mnt/containers/frigate/media and /mnt/containers/frigate/config are both TrueNAS SMB shares mounted on the container host, and exposed in the container to the paths frigate expects.

I don't really see anything wrong with your compose file assuming that the mount points are correct. I'm not using the "rw" flag on mine, but that's the only real difference I see.

Incidentally, the container host is a Proxmox-hosted VM within which I run several containers including frigate and immich. This may not be a supported configuration but it works perfectly for me. I also pass a Nvidia card for transcoding and a Coral device into the VM, and then expose those in the container host and this also works as expected.

```yaml
services:
  frigate:
    container_name: frigate-0.15
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              #count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "1000mb" # update for your cameras based on calculation above
    devices:
      #- /dev/dri/renderD128
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/containers/frigate/config:/config
      - /mnt/containers/frigate/media:/media/frigate
      - /usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.1:/usr/lib/libcuda.so.1
      - ./db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8088:8080"
      - "1935:1935"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "rtsp-password"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
```
