### DISCUSSION TITLE
[Config Support]: Frigate+ API key doesn't seem to be accepted anymore so can't submit images to Frigate+

### DISCUSSION THREAD

**Discussion by numbersixnz** [blakeblackshear/frigate#15924] [Config Support]
### Describe the problem you are having

Frigate+ used to work fine for me but in recent days/weeks the Frigate+ icon (as per the docs) doesn't seem to show up in the sidebar anymore.

When I go to review a detection event I see the Frigate+ button for submitting the frame to Frigate+ but when I click it, I get a message saying:

`Failed to submit frame to Frigate+`

### Version

0.15.0-87e7b62

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 0.0.0.0
  port: 1883
  topic_prefix: frigate
  user: ---
  password: ---

detectors:
  # coral1:
  #   type: edgetpu
  #   device: usb:0
  # coral2:
  #   type: edgetpu
  #   device: usb:1
  ov1:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic-audio-copy

objects:
  track:
    - person
    - car
    - bird
    - dog
    - bicycle

review:
  detections:
    labels:
      - person
      - car
      - dog
  alerts:
    labels:
      - person

birdseye:
  enabled: true
  restream: true

motion:
  enabled: true

snapshots:
  enabled: true
  timestamp: true

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 3
    post_capture: 3
  detections:
    retain:
      days: 30
    pre_capture: 3
    post_capture: 3

detect:
  enabled: true

go2rtc:
  streams:
    01_main: 
      ffmpeg:rtsp://user:pass@0.0.0.0:554/Preview_01_main#video=h264
    01_sub: ffmpeg:rtsp://user:pass@0.0.0.0:554/Preview_01_sub#video=h264
    02_main: 
      ffmpeg:rtsp://user:pass@0.0.0.0:554/Preview_01_main#video=h264
    02_sub: ffmpeg:rtsp://user:pass@0.0.0.0:554/Preview_01_sub#video=h264
    03_main: ffmpeg:rtsp://user:pass@0.0.0.0:554/Preview_01_main#video=h264
    03_sub: ffmpeg:rtsp://user:pass@0.0.0.0:554/Preview_01_sub#video=h264
    04_main: ffmpeg:rtsp://user:pass@0.0.0.0:554/stream1
    04_sub: ffmpeg:rtsp://user:pass@0.0.0.0:554/stream2#timeout=10
    05_main: ffmpeg:rtsp://user:pass@0.0.0.0:554/stream1
    05_sub: ffmpeg:rtsp://user:pass@0.0.0.0:554/stream2#timeout=10

cameras:
  01:
    enabled: false
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/01_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
  02:
    enabled: false
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/02_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
  03:
    enabled: false
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/03_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
  04:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/04_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
  05:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/05_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
version: 0.15-0
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
semantic_search:
  enabled: false
  reindex: false
  model_size: large
notifications:
  enabled: 'false'
  email: x@x.net
```

### Relevant Frigate log output

```shell
Nothing to show.  One time the log had a `frigate.plus` entry indicating the API Key was formatted incorrectly but I tracked this back to an issue with my `.env` file and then an issue with my Docker secret.  Right now my Frigate+ API key is hard-coded into `docker-compose.yml` and there are no errors re Frigate+ anymore.
```

### Relevant go2rtc log output

```shell
No logs available.  Go2rtc works fine.
```

### Frigate stats

```json
{"cameras":{"01":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":null,"capture_pid":null,"ffmpeg_pid":0,"audio_rms":0.0,"audio_dBFS":0.0},"02":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":null,"capture_pid":null,"ffmpeg_pid":0,"audio_rms":0.0,"audio_dBFS":0.0},"03":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":null,"capture_pid":null,"ffmpeg_pid":0,"audio_rms":0.0,"audio_dBFS":0.0},"04":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":1.7,"detection_enabled":true,"pid":539,"capture_pid":555,"ffmpeg_pid":558,"audio_rms":0.0,"audio_dBFS":0.0},"05":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":542,"capture_pid":562,"ffmpeg_pid":570,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"ov1":{"inference_speed":8.36,"detection_start":0.0,"pid":509}},"detection_fps":1.7,"gpu_usages":{"intel-vaapi":{"gpu":"51.81%","mem":"-%","clients":{"558":"0.67%","509":"4.85%","570":"0.76%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"2.8","mem":"37.4"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"17":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"0.3","cpu_average":"0","mem":"0.0","cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml"},"105":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"0.9","cpu_average":"1","mem":"0.2","cmdline":"python3 -u -m frigate"},"126":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"173":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"174":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"175":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"176":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"177":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"311":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"493":{"cpu":"0.3","cpu_average":"0","mem":"0.1","cmdline":"frigate.recording_manager"},"495":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"frigate.review_segment_manager"},"509":{"cpu":"1.7","cpu_average":"3","mem":"0.2","cmdline":"frigate.detector.ov1 "},"525":{"cpu":"0.6","cpu_average":"0","mem":"0.1","cmdline":"frigate.output       "},"539":{"cpu":"0.9","cpu_average":"1","mem":"0.1","cmdline":"frigate.process:04"},"542":{"cpu":"0.9","cpu_average":"0","mem":"0.1","cmdline":"frigate.process:05 "},"555":{"cpu":"0.3","cpu_average":"0","mem":"0.1","cmdline":"frigate.capture:04"},"558":{"cpu":"0.6","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/04_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/04@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=736:h=416,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"561":{"cpu":"0.3","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.70.175:554/stream2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b0851f0eedf8f588e04d1f6a1f5e9a03"},"562":{"cpu":"0.2","cpu_average":"0","mem":"0.1","cmdline":"frigate.capture:05 "},"570":{"cpu":"0.7","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/05_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/05@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=736:h=416,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"572":{"cpu":"0.3","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.70.179:554/stream2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5de66638f32ba154d502e09a6d405ad9"},"597":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 736x416 -i pipe: -threads 1 -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"604":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 736x416 -i pipe: -threads 1 -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"611":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"3275":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"},"3342":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"}},"service":{"uptime":817,"version":"0.15.0-87e7b62","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":6841226.0,"used":135824.0,"free":6705402.0,"mount_type":"nfs"},"/media/frigate/clips":{"total":6841226.0,"used":135824.0,"free":6705402.0,"mount_type":"nfs"},"/tmp/cache":{"total":131072.0,"used":17952.1,"free":113119.9,"mount_type":"overlay"},"/dev/shm":{"total":412.0,"used":47.3,"free":364.7,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1736495942},"processes":{"recording":{"pid":493},"review_segment":{"pid":495},"go2rtc":{"pid":98}}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    privileged: true
    restart: always
    shm_size: "412mb"
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
      - 8971:8971/tcp
      - 1984:1984/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /appdata/frigate/config:/config
      - type: volume
        source: nvr
        target: /media/frigate
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLUS_API_KEY=${PLUS_API_KEY}
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
```

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/f446ff7d-1800-4dcb-b704-9956192a3b45)

![image](https://github.com/user-attachments/assets/3c71d257-6f0f-4538-a9da-ef905b25f1f7)

![image](https://github.com/user-attachments/assets/fd960ea2-52b8-4fa7-9417-78355e5917a3)

### Any other information that may be helpful

In the screenshots you can see the Frigate+ icon is missing.

I also have all sorts of issues about the system being unable to keep up with frames, which is why I currently have detect and record both using sub streams.  This is unrelated.
