### DISCUSSION TITLE
[Support]:  What Does This Red Dot Mean?

### DISCUSSION THREAD

**Discussion by royaltongue** [blakeblackshear/frigate#15939] [General Support] [answered]
### Describe the problem you are having

When viewing my cameras, only two of them have this red dot in the top right corner. Detect is turned off for all cameras, as is recording. What does the dot mean?

![image](https://github.com/user-attachments/assets/470cc595-ae8b-4e86-914e-902312fa6b6b)

### Version

0.14.0-da913d8

### What browser(s) are you using?

Edge ersion 131.0.2903.99 (Official build) (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.24
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: [redacted]

record:
  enabled: false
  expire_interval: 60
  retain:
    days: 2
    mode: all

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay
    -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000

go2rtc:
  streams:
    #################################
    front_camera: 
      ffmpeg:https://192.168.3.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]#video=copy#audio=copy#audio=opus
    #################################
    back_camera: 
      ffmpeg:https://192.168.3.6/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]#video=copy#audio=copy#audio=opus
    #################################
    dash_cam: 
      ffmpeg:https://192.168.3.7/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]#video=copy#audio=copy#audio=opus
    #################################
    front_doorbell: 
      ffmpeg:https://192.168.3.8/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]#video=copy#audio=copy#audio=opus
    #################################
    e1pro1:
      rtsp://admin:[redacted]@192.168.3.9:554/h264Preview_01_sub
    #################################
    e1pro2:
      rtsp://admin:[redacted]@192.168.3.11:554/h264Preview_01_sub
    #################################
  webrtc:
    candidates:
      - 192.168.1.24:8555
      - 100.107.122.155:8555
      - stun:8555

cameras:
  front_camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:8554/front_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        #- path: rtsp://192.168.1.24:8554/front_camera?video=copy
        #  input_args: preset-rtsp-restream
        #  roles:
        #      - record
    detect:
      enabled: false
      #width: 1280
      #height: 720
      #fps: 5
    #objects:
    #  track:
    #    - person
    #    - car
##################################################################
  back_camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:8554/back_camera
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false
##################################################################
  dash_cam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:8554/dash_cam
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false
    birdseye:
      enabled: false
##################################################################
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false
    #objects:
    #  track:
    #    - person
    #mqtt:
    #  height: 720
    #best_image_timeout: 20
##################################################################
  e1pro1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:8554/e1pro1
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
          host: 192.168.3.9
          port: 8000
          user: admin
          password: [redacted]
    detect:
      enabled: false
##################################################################
  e1pro2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:8554/e1pro2
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
          host: 192.168.3.11
          port: 8000
          user: admin
          password: [redacted]
    detect:
      enabled: false
##################################################################

#birdseye:
#  enabled: false
#  width: 1920
#  height: 1080
#  mode: continuous
#  restream: true

#snapshots:
#  enabled: false




version: 0.14
camera_groups:
  Outside:
    order: 1
    icon: LuTreeDeciduous
    cameras:
      - back_camera
      - front_camera
      - front_doorbell
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{
    "cameras": {
        "back_camera": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 656,
            "detection_enabled": false,
            "detection_fps": 0,
            "ffmpeg_pid": 660,
            "pid": 585,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "dash_cam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.2,
            "capture_pid": 664,
            "detection_enabled": false,
            "detection_fps": 0,
            "ffmpeg_pid": 677,
            "pid": 607,
            "process_fps": 5.2,
            "skipped_fps": 0
        },
        "e1pro1": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 666,
            "detection_enabled": false,
            "detection_fps": 0,
            "ffmpeg_pid": 678,
            "pid": 613,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "e1pro2": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 679,
            "detection_enabled": false,
            "detection_fps": 0,
            "ffmpeg_pid": 693,
            "pid": 614,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "front_camera": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 643,
            "detection_enabled": false,
            "detection_fps": 0,
            "ffmpeg_pid": 667,
            "pid": 580,
            "process_fps": 5.1,
            "skipped_fps": 0
        },
        "front_doorbell": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 665,
            "detection_enabled": false,
            "detection_fps": 0,
            "ffmpeg_pid": 683,
            "pid": 608,
            "process_fps": 5.1,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "14": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "23": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise certsync-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "33": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "44": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "45": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "92": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "95": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "96": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "106": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "2.9",
            "cpu_average": "2",
            "mem": "0.4"
        },
        "114": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "2.3",
            "cpu_average": "2",
            "mem": "1.1"
        },
        "115": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "140": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "168": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "169": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "196": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "197": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "198": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "312": {
            "cmdline": "bash ./run.user certsync",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "381": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "526": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "528": {
            "cmdline": "frigate.review_segment_manager",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "554": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(71)",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "556": {
            "cmdline": "frigate.detector.tensorrt",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "560": {
            "cmdline": "frigate.output       ",
            "cpu": "1.5",
            "cpu_average": "3",
            "mem": "0.5"
        },
        "565": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "570": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "580": {
            "cmdline": "frigate.process:front_camera",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "585": {
            "cmdline": "frigate.process:back_camera",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "589": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "599": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "607": {
            "cmdline": "frigate.process:dash_cam",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "608": {
            "cmdline": "frigate.process:front_doorbell",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "613": {
            "cmdline": "frigate.process:e1pro1",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "614": {
            "cmdline": "frigate.process:e1pro2",
            "cpu": "0.8",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "643": {
            "cmdline": "frigate.capture:front_camera",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "646": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "651": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "656": {
            "cmdline": "frigate.capture:back_camera",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "657": {
            "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "660": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.24:8554/back_camera -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "664": {
            "cmdline": "frigate.capture:dash_cam",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "665": {
            "cmdline": "frigate.capture:front_doorbell",
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "666": {
            "cmdline": "frigate.capture:e1pro1",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "667": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.24:8554/front_camera?video=copy&audio=aac -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "677": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.24:8554/dash_cam -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "678": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.24:8554/e1pro1 -r 5 -vf fps=5,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "679": {
            "cmdline": "frigate.capture:e1pro2",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "680": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.3.6/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/da4f6b05be913cae6bbf8120b8930a1f",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "683": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.24:8554/front_doorbell -r 5 -vf fps=5,scale_cuda=w=896:h=672:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.4",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "691": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.3.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/7fa99868ca2066147908277010568308",
            "cpu": "1.3",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "693": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.24:8554/e1pro2 -r 5 -vf fps=5,scale_cuda=w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "696": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.3.7/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/778468b3ae47a2ebf9d90c53a6fbb6c1",
            "cpu": "1.3",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "698": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.3.8/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ca9d5dd2d220b12507a28b481a90c28d",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "348190": {
            "cmdline": "sleep 60",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "348207": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "frigate.full_system": {
            "cpu": "12.5",
            "mem": "62.4"
        }
    },
    "detection_fps": 0,
    "detectors": {
        "tensorrt": {
            "detection_start": 0,
            "inference_speed": 10,
            "pid": 556
        }
    },
    "gpu_usages": {
        "NVIDIA GeForce GTX 1080": {
            "dec": "3.0%",
            "enc": "0.0%",
            "gpu": "1.0%",
            "mem": "16.05%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 106
        },
        "logger": {
            "pid": 381
        },
        "recording": {
            "pid": 526
        },
        "review_segment": {
            "pid": 528
        }
    },
    "service": {
        "last_updated": 1736564638,
        "latest_version": "0.14.1",
        "storage": {
            "/dev/shm": {
                "free": 249.6,
                "mount_type": "tmpfs",
                "total": 256,
                "used": 6.4
            },
            "/media/frigate/clips": {
                "free": 4127024.4,
                "mount_type": "fuse.mergerfs",
                "total": 71903809.4,
                "used": 67776689
            },
            "/media/frigate/recordings": {
                "free": 4127024.4,
                "mount_type": "fuse.mergerfs",
                "total": 71903809.4,
                "used": 67776689
            },
            "/tmp/cache": {
                "free": 951.9,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 1.8
            }
        },
        "temperatures": {},
        "uptime": 314818,
        "version": "0.14.0-da913d8"
    }
}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    privileged: true
    shm_size: "256mb"
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${dcs}/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - ${pool}/frigatestorage/media/frigate:/media/frigate
    hostname: frigate
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    restart: unless-stopped
```

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

Reolink E1 Pro/RLC-520/WiFi Doorbell
