### DISCUSSION TITLE
[Config Support]: A single camera has no audio only in livestream

### DISCUSSION THREAD

**Discussion by wastelandgunner** [blakeblackshear/frigate#15933] [Config Support] [answered]
### A single camera has no audio only in livestream 

I have two Wyze V3 cameras, both loaded with Mini Hacks. They are both set up identically, except for a hostname difference in the config. Of my two cameras, one of them has no audio in the livestream preview, however it does record audio in the reviewable clips/exports. My config for each is also identical. The other camera works perfectly fine with no audio issues. 

I'm fairly new to Home Assistant, Frigate, Go2RTC, etc so it's entirely possible I misconfigured something or just don't understand how a certain software works. I'm using Frigate on unRAID as a Docker container with it plumbed into Home Assistant via Frigate Proxy. Please forgive me if I forget to mention any critical details or have any blatantly long misconfiguration, I'm still learning!

Thank you!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false
go2rtc:
  streams:
    Wyze_Living_Room:
      - rtsp://192.168.50.15:8554/1080p?mp4
      - "ffmpeg:Wyze_Living_Room#audio=aac"
    Wyze_Hallway:  
      - rtsp://192.168.50.16:8554/1080p?mp4
      - "ffmpeg:Wyze_Hallway#audio=aac"
  webrtc:
    candidates:
      - 192.168.50.15:8555
      - 192.168.50.16:8555
audio:

  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - door
    - siren
    - civil_defense_siren
    - buzzer
    - smoke_detector
    - crack
    - glass
    - smash
    - breaking
    - splinter
record:
  enabled: true
  events:
    retain:
      default: 30
      mode: active_objects
cameras:
  Wyze_Living_Room: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.50.15:8554/1080p?mp4 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
            - audio
      hwaccel_args: 
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
      output_args: 
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
  Wyze_Hallway: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.50.16:8554/1080p?mp4 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
            - audio
      hwaccel_args: 
            - -hwaccel
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
      output_args: 
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
version: 0.14
```

### Relevant Frigate log output

```shell
There is nothing relevant contained in the logs.
```

### Relevant go2rtc log output

```shell
There is nothing relevant contained in the logs.
```

### Operating system

UNRAID

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Screenshot of my unRAID Docker configuration:
https://i.imgur.com/Jh50u35.png
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/7268b70a-d395-4358-bde8-b6cf6804da57)
![image](https://github.com/user-attachments/assets/abe7e5ca-4bfc-4a74-8454-7732d4dbc102)
