### DISCUSSION TITLE
[Bug]: Settings -> Debug -> Zones not updated after zones config change

### DISCUSSION THREAD

**Discussion by baylanger** [blakeblackshear/frigate#15944] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After updating the zones' area using the UI, going into "Settings -> Debug" and enable "Zones" (show an outline of any defined zones), the zones don't appear updated. A restart will fix this issue.

### Steps to reproduce

1.Go in Settings -> Masks/Zones
2.Make change to zones
3.Go in Settings -> Debug
4.Enable "Zones"

### Version

0.15.0-beta4

### In which browser(s) are you experiencing the issue with?

Safari & HA Companion

### Frigate config file

```yaml
mqtt:
  client_id: frigate
  host: mqtt.zutzut.com
  password: '{FRIGATE_MQTT_PASSWORD}'
  port: 1883
  topic_prefix: frigate
  user: '{FRIGATE_MQTT_USER}'

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous
  layout:
    max_cameras: 4

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - cat
    - dog

go2rtc:
  streams:
    2office:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.63:554/Streaming/Channels/101
    2office_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.63:554/Streaming/Channels/103

  webrtc:
    candidates:
      - 192.168.1.66:8555
      - 107.171.135.117:8555

audio:
  enabled: false
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

cameras:
  2office:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/2office
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/2office_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720
      fps: 8

    zones:
      street:
        coordinates: 0,0.891,1,0.335,1,0.223,0,0.707
        objects:
          - bicycle
          - car
          - person
        inertia: 3
        loitering_time: 0
      front-r:
        coordinates: 0.626,0.38,0.568,0.286,0.409,0.352,0.473,0.452
        objects:
          - car
          - person
        inertia: 3
        loitering_time: 0
      front-door-r:
        coordinates: 687,229,759,209,713,131,656,144
        objects:
          - person
      front-l:
        coordinates: 0,0.707,0,0.504,0.128,0.457,0.074,0.672
        objects:
          - bicycle
          - car
          - person
        inertia: 3
        loitering_time: 0
      front-door-l:
        coordinates: 0.126,0.517,0.18,0.482,0.162,0.351,0.113,0.383
        objects: person
        inertia: 3
        loitering_time: 0
      frontyard:
        coordinates: 0.497,0.66,1,0.362,1,0.687,0.698,0.98

        inertia: 3
        loitering_time: 0
        objects: person
      entrance:
        coordinates: 0.084,1,0.662,1,0.687,0.971,0.493,0.666,0.109,0.885
        inertia: 3
        loitering_time: 1
        objects:
          - bicycle
          - person
          - car
    objects:
      track:
        - bicycle
        - car
        - person

    motion:
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 10
        pre_capture: 15
        post_capture: 15
      detections:
        retain:
          days: 10
        pre_capture: 15
        post_capture: 15
    snapshots:
      enabled: false
      timestamp: false
      bounding_box: false
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15

logger:
  default: info
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    image: "ghcr.io/blakeblackshear/frigate:0.15.0-beta4"
    container_name: "frigate15"
    domainname: "zutzut.com"
    hostname: "frigate"
    privileged: true
    restart: "unless-stopped"
    shm_size: "128mb"
    devices:
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume1/docker/frigate15/config/:/config:rw"
      - "/volume1/docker/frigate15/media:/media/frigate:rw"
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
    environment:
      TZ: "Canada/Eastern"
      LIBVA_DRIVER_NAME: "i965"
      PLUS_API_KEY: "XXXXX"
    env_file:
      - "./secrets.env"
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

HassOS

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision

### Screenshots of the Frigate UI's System metrics pages

Irrelevant
