### DISCUSSION TITLE
[Support]: Audio pre capture behavior

### DISCUSSION THREAD

**Discussion by qtronixx** [blakeblackshear/frigate#15961] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I noticed this moment, when detecting speech, the parameter post_capture does not work. pre_capture works well.
that is, before the moment of voice detection there is a clean segment of the recording of 10 seconds, but after the speech stops, the recording immediately breaks off.
Frigate 0.15.0 Beta 5

### Steps to reproduce

1.
2.
3.
...

### Version

0.15.0 Beta 5

### Frigate config file

```yaml
####
# Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: true
  export:
    timelapse_args: -vf setpts=PTS/60 -r 25
  sync_recordings: true
  retain:
    #days: 7
    days: 5
    mode: motion
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
      # Mode for retention.
      #   all - save all recording segments for alerts regardless of activity
      #   motion - save all recordings segments for alerts with any detected motion
      #   active_objects - save all recording segments for alerts with active/moving objects
      mode: active_objects
  # detection recording settings
  detections:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 15
      # Mode for retention. (см выше.)
      mode: active_objects
```

### docker-compose file or Docker CLI command

```yaml
services:
    frigate:
      container_name: frigate15
      image: ghcr.io/blakeblackshear/frigate:0.15.0-beta5
      privileged: true # this may not be necessary for all setups
      restart: unless-stopped 
      group_add:
        - "106" # render
        - "44"  # video
        - "46"  # plugdev
      shm_size: "2048mb" # update for your cameras based on calculation above
      devices:
        - /dev/dri/renderD128:/dev/dri/renderD128
        #- /dev/dri/renderD129:/dev/dri/renderD129
        - /dev/dri/card0:/dev/dri/card0
        #- /dev/dri/card1:/dev/dri/card1
        #- /dev/rga
        - /dev/video-dec0:/dev/video-dec0
        - /dev/video-enc0:/dev/video-enc0    
      volumes:
        - /dev/bus/usb:/dev/bus/usb
        - /etc/localtime:/etc/localtime:ro
        - /docker/frigate15/config:/config:rw
        - /video:/media/frigate:rw
        - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: "12884901888"
      ports:
        - "1984:1984" # go2rtc WebUI
        - "1985:1985" # go2rtc TLS WebUI
        - "5000:5000" # Internal unauthenticated UI and API access. Access to this port should be limited. Intended to be used within the docker network for services that integrate with Frigate.
        - "1935:1935"
        - "8971:8971" # Authenticated UI and API access without TLS. Reverse proxies should use this port.
        - "8554:8554" # RTSP feeds
        - "8555:8555/tcp" # WebRTC over tcp
        - "8555:8555/udp" # WebRTC over udp 
      device_cgroup_rules:
        - "c 189:* rmw"
      environment:
        PLUS_API_KEY: MY_FRIGATE_PLUS_API_KEY
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

xiaomi

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/6eb8a83c-efef-4148-af55-a13d0e666f54)
