### DISCUSSION TITLE
[Support]: HTTP 404 in Home Assistant Notifications

### DISCUSSION THREAD

**Discussion by kavejo** [blakeblackshear/frigate#15972] [General Support] [answered]
### Describe the problem you are having

I must be missing something pretty basic but I can't seem to be able to get the thumbnail/snapshots in the Home Assistant notifications triggered via Home Assistant Automation.

I am running Home Assistant on Docker and on the same Docker host I also run Frigate.

In Frigate I have set the "Person" detection to be an alert, while all other detections are just detections.
In Home Assistant I am checking the MQTT events and if the notification is for an alert, then HA triggers the notification.

In Frigate, for example, I have this Alert:
![image](https://github.com/user-attachments/assets/9020c93f-27c5-4413-9d4d-82246d311cf2)

The notification received in the HA Companion App is missing the thumbnail (tried with the snapshot as well, with no change):
![image](https://github.com/user-attachments/assets/198ecaab-e01b-4be6-baf5-1efdd40d2f4e)

However if I press on the notification I can see the video stream correctly:
![image](https://github.com/user-attachments/assets/b2960675-4a94-48c2-8f0a-94c484f2df23)

My HA Automation look like the following; I've tried to use both a custom domain (cloudflared) as well as Nabu casa.

```
triggers:
  - trigger: mqtt
    topic: frigate/reviews
conditions:
  - condition: template
    value_template: '{{ trigger.payload_json[''after''][''severity''] == ''alert'' }}'
actions:
  - variables:
      ha_url: MY_DOMAIN
      nabu_url: MY_NABU_CASA
  - action: notify.MY_MOBILE
    metadata: {}
    data:
      message: Persona rilevata da {{trigger.payload_json["after"]["camera"]}}
      data:
        image: >-
          {{nabu_url}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=1
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        entity_id: >-
          camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
          lower}}
        clickAction: >-
          {{nabu_url}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=1
        push:
          sound:
            name: default
            critical: 1
            volume: 1
```

If I browse to the URL that is being sent from the automation, I can see the following error.

![image](https://github.com/user-attachments/assets/d07b4f20-d353-410e-839a-2880e549d23f)

The Integration is set as per documentation:

![image](https://github.com/user-attachments/assets/483ac7e3-1905-4bcd-818e-8c890054e0f2)

Browsing through Media Browser however shows the image.

![image](https://github.com/user-attachments/assets/84e9074f-d79b-441a-8c8d-cd33245f0c6b)

As such I think I must be missing something pretty basic, but I can't work out what that is.
The same code used to work when I was running HassOS and Frigate Proxy but I never got it working on this new installation.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

N/A

### Frigate config file

```yaml
[...]
snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 365
[...]
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
HomeAssistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: HomeAssistant
    volumes:
      - ${CONTAINER_LOCATION}/Automation/HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - Automation-Net
    ports:
      - 8123:8123
    depends_on:
      MariaDB:
        condition: service_started
        restart: true
      Mosquitto:
        condition: service_started
        restart: true
    restart: always
    privileged: true

  Frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: Frigate
    privileged: true
    shm_size: "1024mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_LOCATION}/NVR/Frigate/config:/config
      - ${MEDIA_LOCATION}:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
      - NVR-Net
    ports:
      - 5000:5000 # Web UI
      - 8971:8971 # Authenticated Web UI
      - 1935:1935 # RTMP
      - 8554:8554 # RTSP
      - 8555:8555/tcp # WebRTC over TCP
      - 8555:8555/udp # WebRTC over UDP
    environment:
      PLUS_API_KEY: ${PLUS_API_KEY}
      FRIGATE_MQTT_USER: ${FRIGATE_MQTT_USER}
      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
      FRIGATE_RTSP_HOST_NVR: ${FRIGATE_RTSP_HOST_NVR}
      FRIGATE_RTSP_USER_NVR: ${FRIGATE_RTSP_USER_NVR}
      FRIGATE_RTSP_PASSWORD_NVR: ${FRIGATE_RTSP_PASSWORD_NVR}
#      YOLO_MODELS: yolov7-tiny-416,yolov7-640,yolov7x-640
#      USE_FP16: false
    cap_add:
      - PERFMON
    restart: always
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua
