### DISCUSSION TITLE
[HW Accel Support]: How google coral usb affects CPU load and what to do to reduce it?

### DISCUSSION THREAD

**Discussion by Xld137** [blakeblackshear/frigate#15979] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Hello, folks.

I'm starting to think about google coral usb for my humble setup of frigate on Intel NUC with Intel Celeron J3455 2/4. Now with 1 cam 1080p and 2 cams 480p (all three cams were set up to use low quality 5 fps substream for detection and main stream for record) CPU is constantly 100% loaded, I always get this "CPU is very slow 130 ms". I'd like to reduce CPU load as much as I can without loosing detection.

From your experience how much google coral usb will affect my setup? Will it reduce CPU load significantly or I shouldn't bother?

I've noticed that my built in GPU is always less than 2% loaded, no mater what hwaccel option I use (vaapi, qsv-264). May be it's the reason..?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  input_args: preset-rtsp-restream
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
  retry_interval: 10

detectors:
  cpu1:
    type: cpu
    num_threads: 3
    model:
      path: "/cpu_model.tflite"

motion:
  enabled: true

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 30
      mode: motion

review:
  detections:
    labels:
      - person

detect:
  enabled: true
  fps: 5

cameras:
  cam1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: substream
          roles:
            - detect
        - path: mainstream
          roles:
            - record
  cam2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: substream
          roles:
            - detect
        - path: mainstream
          roles:
            - record
  cam3:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: substream
          roles:
            - detect
        - path: mainstream
          roles:
            - record

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    hostname: nuc
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "120mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker/compose/frigate/config:/config
      - /home/user/docker/containers/frigate/recs:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
#      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "mypassword"
```

### Relevant Frigate log output

```shell
Nothing to show I guess...
```

### Relevant go2rtc log output

```shell
Same
```

### FFprobe output from your camera

```shell
One of the cameras:

Input #0, rtsp, from 'mainstream':
  Metadata:
    title           : QV Media
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
  Stream #0:2: Data: none
```

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

TS

### Screenshots of the Frigate UI's System metrics pages

<img width="1387" alt="shot" src="https://github.com/user-attachments/assets/e5ba7c83-0f48-4c37-afc0-acd924fed4aa" />
