### DISCUSSION TITLE
Need assistance with docker compose and config files[Config Support]:

### DISCUSSION THREAD

**Discussion by edernunez61** [blakeblackshear/frigate#15973] [Config Support]
### Describe the problem you are having

Hi all, I am new to frigate, and am trying to set up the docker compose and config files. The issue I am having is that, when I set the ffmpeg hwaccel args to the preset vaapi, the camera feed doesn't work. When setting to auto, or removing the args entirely, it works on cpu. How can I use either my laptop's intel Xe graphics or nvidia 4060, and what modifications do I have to make to the docker compose and config files to make it happen?

Also, what object detector would I use here? Openvino/tensorrt, etc?

Thanks in advance for any assistance, I am very new to this type of software!

### Version

Latest stable

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: auto

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: -------------------------------------
          roles:
            - detect
        - path: -------------------------------------
          roles:
            - record
    detect:
      width: 640  
      height: 480 
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all

detect:
  enabled: true
version: 0.14
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Windows

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - C:\frigate\config.yml:/config/config.yml
      - C:\frigate\storage:/media/frigate 
    ports:
      - "5000:5000" # Frigate web UI
      - "8555:8555/tcp" # WebRTC over TCP
      - "8555:8555/udp" # WebRTC over UDP
    environment:
      FRIGATE_RTSP_PASSWORD: "your_password"
```

### Object Detector

OpenVino
