### DISCUSSION TITLE
[Config Support]: Review Filter UI missing Objects

### DISCUSSION THREAD

**Discussion by especially-relative** [blakeblackshear/frigate#15987] [Config Support]
### Describe the problem you are having

In my config I have the following objects tracked:

```
    review:
      alerts:
        labels:
          - car
          - person
          - cat
          - dog
          - bird
          - bicycle
          - doorbell
          - honk
    objects:
        track:
            - person
            - car
            - cat
            - dog
            - bird
            - bicycle
            - honk
            - doorbell
            - door
            - emergency_vehicle
            - bird
```

but the dropdown for the review only lists person/car/speech/bicycle. Back in 0.13 cat/dog detections were common enough, and I have seen HA notifications but still never see dog/cat/bird in the review filter UI

Actually with the current UI I don't have any idea how to say bring up "all bird detections" or "all dog detections from the back camera" like I could in 0.13.

### Version

0.14

### Frigate config file

```yaml
birdseye:
      enabled: False
    database:
      path: /database/frigate.db
    logger:
      default: info
      logs:
        frigate.event: debug
    mqtt:
      host: mqtt
      user: frigate
      password: "{FRIGATE_MQTT_PASSWORD}"
    detect:
      width: 704
      height: 480
      fps: 15
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
    go2rtc:
      streams:
    detectors:
      gpu:
        type: tensorrt
    model:
      input_tensor: nchw
      input_pixel_format: rgb
      path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
      width: 416
      height: 416
      #path: /config/model_cache/tensorrt/yolov7-640.trt
      #width: 640
      #height: 640
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    review:
      alerts:
        labels:
          - car
          - person
          - cat
          - dog
          - bird
          - bicycle
          - doorbell
          - honk
    objects:
        track:
            - person
            - car
            - cat
            - dog
            - bird
            - bicycle
            - honk
            - doorbell
            - door
            - emergency_vehicle
            - bird
    record:
      enabled: true
      retain:
        days: 8
        mode: motion
      events:
        retain:
          default: 8
          mode: motion
          objects:
            person: 15
    cameras:
      porch:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/porch
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/porch-sub
              roles:
                - detect
                - audio
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
kubernetes deployment
```

### Object Detector

TensorRT
