### DISCUSSION TITLE
Recommendation for 4k camera with good sensor

### DISCUSSION THREAD

**Discussion by Lallassu** [blakeblackshear/frigate#15994] [Ask A Question]
I'm currently running Frigate with 6x TP-Link vigi c340 cameras + 3xUnifi G3 and it works like a charm. But I have a specific "problem" I want to solve. I want to identify license plates on cars passing. It doesn't have to be during night, so I don't really require 100% success rate here. Currently my VIGI 5MP is just too grainy when zooming in (via frigate) on the plate. This is on a distance of maybe 10-20m from the side. So I was thinking about getting a 4k camera with a better sensor to be able to at least have a chance of reading the plates.

Then I saw that there are quite a lot of issues with Reolink 4k that can't stream in 4k to frigate and the recommended camera list on frigate wiki might not fit my case.

Does anyone have tips on cameras that might handle this situation better? (budget around ~$100-$200)

Once again, it's not about getting perfect LPR, it's just to be able to at least try to read the plates manually.

Example of how it looks now:
![image](https://github.com/user-attachments/assets/5bcedcb6-a445-4307-81a3-1fe543af93aa)

**Comment by NickM-27** [comment]
I think the higher resolution will actually work against you, what you need is a camera that can see something clearly despite motion. According to IP cam talk, [IPC-B52IR-Z12E](https://www.amazon.com/Loryta-IPC-HFW5241E-Z12E-Starlight-Network-English/dp/B07RJQT9NB/ref=sr_1_3?imprToken=eNnu.Pmf5hsW5hcTVECAQg&linkCode=w61&m=A329YQ83EBQGJF&marketplaceID=ATVPDKIKX0DER&qid=1648168425&redirect=true&s=merchant-items&slotNum=0&sr=1-3&tag=ipctk-20&th=1) is recommended for ALPR. 

https://ipcamtalk.com/threads/the-importance-of-focal-length-over-mp-in-camera-selection.62472/

**Reply by Lallassu** [reply]
> I think the higher resolution will actually work against you, what you need is a camera that can see something clearly despite motion. According to IP cam talk, [IPC-B52IR-Z12E](https://www.amazon.com/Loryta-IPC-HFW5241E-Z12E-Starlight-Network-English/dp/B07RJQT9NB/ref=sr_1_3?imprToken=eNnu.Pmf5hsW5hcTVECAQg&linkCode=w61&m=A329YQ83EBQGJF&marketplaceID=ATVPDKIKX0DER&qid=1648168425&redirect=true&s=merchant-items&slotNum=0&sr=1-3&tag=ipctk-20&th=1) is recommended for ALPR.
> 
> https://ipcamtalk.com/threads/the-importance-of-focal-length-over-mp-in-camera-selection.62472/

Thanks for your reply. I've seen that as well. Unfortunately, that camera is very hard to get hold of in Sweden for a decent price (just the shipping cost from Amazon is above $100). When I read about that camera, it's good for LPR because it has vari-lens up to 60mm. I would however prefer to keep ~4mm if possible to still keep a good surveillance eye. The cars in my case only goes in roughly ~12Mph, so there is of course motion, but not very fast.

I guess a camera with faster shutter-speed would be to prefer if it is due to the motion. But still, enough megapixels to still see the plate.

**Reply by ehn** [reply]
I believe products sold by EmpireTech are typically rebranded Dahua hardware. EmpireTech is focused on the US market, but you may be able to find the same camera with a Dahua or Loryta brand elsewhere.

I don't know if they're identical, but  [Dahua IPC-HFW5241E-Z12E](https://www.dahuasecurity.com/products/All-Products/Network-Cameras/WizMind-5-Series/S-Series/2MP/IPC-HFW5241E-Z12E=S3) looks quite similar to [EmpireTech IPC-B52IR-Z12E-S2](https://empiretech01.com/products/empiretech-2mp-wdr-ir-bullet-ai-network-bullet-camera-ipc-b52ir-z12e-s2).

**Comment by WhoEverNot** [comment]
Hi Lallassu
Would you mind sharing your config.yml in regards the setup for the Vigi cameras please?
Im having trouble with recording on my TPLink vigi and Im quite certain I have the wrong parameters
Frigate shows the thumbnails of events but I cannot export/Play them as there has been no recording of the event.

Thanks

Error logs
[2025-02-12 16:11:24] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/Front@20250212161120-0800.mp4
ffmpeg.Back.record             ERROR   : [mp4 @ 0x555a6b222b80] Could not find tag for codec pcm_alaw in stream #1, codec not currently supported in container
ffmpeg.Back.record             ERROR   : [out#0/segment @ 0x555a6b234c40] Could not write header (incorrect codec parameters ?): Invalid argument

config.yml file

Back:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxx@192.168.xx.xx:554/stream1
          roles:
            - record
        - path: rtsp://xxxxxxxx@192.168.xx.xx:554/stream1
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1280
      height: 720

**Reply by Lallassu** [reply]
This is for one of my cameras, but it's the same config both my C330 and C340:
```
go2rtc:
  streams:
     backyard:
       - rtsp://user:pass@192.168.2.180:554/stream1
       - ffmpeg:backyard#audio=aac
     backyard_sub:
       - rtsp://user:pass@192.168.2.180:554/stream2

cameras:
 backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: backyard
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 100
          min_score: 0.55
          threshold: 0.65
        car:
          min_area: 300
          min_score: 0.55
          threshold: 0.65
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
    motion:
      threshold: 20
      contour_area: 20
      improve_contrast: 'true'
```
