### DISCUSSION TITLE
[Support]: Frigate constant crashes in LXC

### DISCUSSION THREAD

**Discussion by vdiogo** [blakeblackshear/frigate#15995] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I am running Frigate on a Proxmox LXC container with Coral accelerator, and have been experiencing multiple crashes since initial installation for which I would appreciate help on how to best troubleshoot.

I am constantly monitoring memory and logs, so the main actions I have performed were:
- Removed two WiFi Tapo C200 cameras from the configuration, as they were causing these crashes more frequently (daily)
- Increased the host memory
- Adjusted the configuration for the remaining cameras so i would use the lowest resolution possible (to minimize network related issues)

I am not able to capture the logs before the error (or at least I don't know how)

### Steps to reproduce

1. Restart Frigate after crash
2. Let it run for as much time as possible
3. Crash followed by restart
...

### Version

0.13.2-6476f8a

### In which browser(s) are you experiencing the issue with?

Google chrome 131.0.6778.140

### Frigate config file

```yaml
mqtt: # <----- MQTT SERVER
  host: 192.168.86.249
  port: 1883
  user: mqtt
  password: H@rley2019
  topic_prefix: frigate
  client_id: frigate

########################################## GLOBAL SETTINGS
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral: # <----- GOOGLE CORAL USB
    type: edgetpu
    device: usb

ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Europe/Lisbon

#################Global Object Settings
objects:
  track:
  - person
  - dog
  - cat
  - bicycle
  - car
  - motorcycle
  - bird
  - face
  - license_plate
  - package
  filters:
    person:
      threshold: 0.7 # <-------REDUZIDO DE 0.8 PARA 0.7 PARA TREINAR MODELO
      min_area: 5000
      max_area: 100000

#rtmp:
#  enabled: false

birdseye:
  enabled: true
  mode: objects
  restream: true
  quality: 8

record:
  enabled: true # <----- check the file system and delete any db entries for files which don't exist
  sync_recordings: true
  retain:
    days: 20 # <----- all motion segments are stored for 20 days
    mode: motion # <----- only retain video where motion was detected
  events:
    retain:
      default: 14 # <----- active objects are stored for 14 days
      mode: active_objects
      objects:
        dog: 2 # <----- recordings of dogs only need to be kept for 2 days
        car: 7 # <----- recordings of cars should be kept for 7 days
        motorcycle: 7 # <----- recordings of motorcycles should be kept for 7 days


###### ADICIONADO 23DEZ2024
#go2rtc:
#    streams:
#      tapo_garagem:
#        - rtsp://vdiogo:H@rley2019@192.168.86.21/stream1
#        - "ffmpeg:tapo_garagem#audio=aac"
#      tapo_arrumos:
#        - rtsp://vdiogo:H@rley2019@192.168.86.125/stream1
#        - "ffmpeg:tapo_arrumos#audio=aac"
###### ADICIONADO 23DEZ2024

cameras:
#  tapo_garagem: # <----- TAPO GARAGEM
#    enabled: true
#    birdseye:
#      mode: objects # <----- Objects mode prevents birdseye from being triggered by bushes in the wind.
#    ffmpeg:

###### ADICIONADO 23DEZ2024      
#      output_args:
#        record: preset-record-generic-audio-copy
###### ADICIONADO 23DEZ2024

       ###################HIGH RESOLUTION
#      inputs:
#      - path: rtsp://vdiogo:H@rley2019@192.168.86.21/stream1

###### ADICIONADO 23DEZ2024
#      - path: rtsp://127.0.0.1:8554/tapo_garagem # <----- The stream you want to use for record
#        input_args: preset-rtsp-restream
###### ADICIONADO 23DEZ2024
#        roles:
#        - record
#        - audio ###### ADICIONADO 23DEZ2024
       #################LOW RESOLUTION
#      - path: rtsp://vdiogo:H@rley2019@192.168.86.21/stream2
#        roles:
#        - detect

#    objects:
#      track:
#      - person
#      - face
#    detect:
#      width: 640
#      height: 360
#      fps: 5
#    snapshots:
#      enabled: true # <----- Enable snapshots
#    zones:
#      mota_garagem: # <----- Lugar da moto na garagem
#        coordinates: 454,228,497,360,338,360,219,236,269,170

  tapo_quartos: # <----- TAPO QUARTOS
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://vdiogo:H@rley2019@192.168.86.232/stream1
        global_args: -hide_banner -loglevel info #TEMPORARIO
        roles:
        - record
        input_args: #LESS AGRESSIVE INPUT ARGS
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
       #################LOW RESOLUTION
      - path: rtsp://vdiogo:H@rley2019@192.168.86.232/stream2
        global_args: -hide_banner -loglevel info #TEMPORARIO
        roles:
        - detect
        input_args: #LESS AGRESSIVE INPUT ARGS
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'        
    objects:
      track:
      - person
      - face
    detect:
      width: 640 #estava 1920
      height: 360 #estava 1080
      fps: 5 #estava 15   
    snapshots:
      enabled: true
    zones:
      quarto_meio:
        coordinates: 457,49,340,0,296,282,369,360
      escadas_quartos:
        coordinates: 162,360,74,360,60,284,90,267
      quarto_frente:
        coordinates: 77,0,127,0,137,103,98,108

#  tapo_arrumos: # <----- TAPO ARRUMOS
#    enabled: true
#    birdseye:
#      mode: objects
#    ffmpeg:

###### ADICIONADO 23DEZ2024      
#      output_args:
#        record: preset-record-generic-audio-copy
###### ADICIONADO 23DEZ2024  

       ###################HIGH RESOLUTION
#      inputs:
#      - path: rtsp://vdiogo:H@rley2019@192.168.86.125/stream1

###### ADICIONADO 23DEZ2024
#      - path: rtsp://127.0.0.1:8554/tapo_arrumos # <----- The stream you want to use for record
#        input_args: preset-rtsp-restream
###### ADICIONADO 23DEZ2024

#        roles:
#        - record
#        - audio
       #################LOW RESOLUTION
#      - path: rtsp://vdiogo:H@rley2019@192.168.86.125/stream2
#        roles:
#        - detect
#    objects:
#      track:
#      - person
#      - face
#      - dog
#      - cat
#    detect:
#      width: 640 #estava 1920
#      height: 360 #estava 1080
#      fps: 5 #estava 15      
#  zones:
#    porta_patio:
  ##      coordinates: 163,81,208,84,192,0,145,0
  ##  snapshots:
  ##    enabled: true # <----- Enable snapshots

  tapo_patio_hd: # <----- TAPO C520 WS PATIO 
    enabled: true
    birdseye:
      mode: objects
    ffmpeg:
       ###################HIGH RESOLUTION
      inputs:
      - path: rtsp://vdiogo:H@rley2019@192.168.86.53/stream1
        roles:
        - record
       #################LOW RESOLUTION
      - path: rtsp://vdiogo:H@rley2019@192.168.86.53/stream2
        roles:
        - detect
    objects:
      track:
      - person
      - face
      - dog
      - cat
    detect:
      width: 640 #estava 2560
      height: 360 #estava 1440
      fps: 5 #estava 15
    zones:
      porta_patio:
        coordinates: 230,71,272,66,268,0,214,0
    snapshots:
      enabled: true # <----- Enable snapshots

  tapo_jardim_hd: # <----- TAPO C520 WS JARDIM
    enabled: true
    birdseye:
      mode: objects
    ffmpeg:
       ###################HIGH RESOLUTION
      inputs:
      - path: rtsp://vdiogo:H@rley2019@192.168.86.45/stream1
        roles:
        - record
       #################LOW RESOLUTION
      - path: rtsp://vdiogo:H@rley2019@192.168.86.45/stream2
        roles:
        - detect
    objects:
      track:
      - person
      - face
      - dog
      - cat
    detect:
      enabled: true
      width: 640 #estava 2560
      height: 360 #estava 1440
      fps: 5 #estava 30
    #zones:
    #  porta_patio:
    #    coordinates: 230,71,272,66,268,0,214,0
    snapshots:
      enabled: true # <----- Enable snapshots

  tapo_qmeio: # <----- TAPO QUARTO AMÉLIA
    enabled: true
    birdseye:
      mode: objects # <----- Objects mode prevents birdseye from being triggered by bushes in the wind.
    ffmpeg:
       ###################HIGH RESOLUTION
      inputs:
      - path: rtsp://vdiogo:H@rley2019@192.168.86.37/stream1
        roles:
        - record
 #      #################LOW RESOLUTION
      - path: rtsp://vdiogo:H@rley2019@192.168.86.37/stream2
        roles:
        - detect

    objects:
      track:
      - person
      - face
    detect:
      width: 640 #estava 2560
      height: 360 #estava 1440
      fps: 5 #estava 30
    snapshots:
      enabled: true # <----- Enable snapshots
#    zones:
#      mota_garagem: # <----- Lugar da moto na garagem
#        coordinates: 454,228,497,360,338,360,219,236,269,170


  reolink_frente: # <----- REOLINK FRENTE
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
        # High Resolution Stream
 #       - path: rtsp://admin:Harley10@192.168.3.68:554//h265Preview_01_main
 #         input_args: preset-rtsp-restream
 #         roles:
 #           - record
          # Low Resolution Stream
 #       - path: rtsp://admin:Harley10@192.168.3.68:554//h264Preview_01_main
 #         input_args: preset-rtsp-restream
 #         roles:
 #           - detect
      inputs:
      - path: 
          http://192.168.3.68/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Harley10
 #         input_args: preset-rtsp-restream
        roles:
        - record
        - rtmp
        - detect

    motion:
      mask:
      - 1280,720,1280,0,1227,0,709,679,522,530,221,720
      - 237,263,877,0,0,0,0,351,210,228
    zones:
      entrada_principal: # <----- entrada em frente da casa
        coordinates: 
          230,428,298,500,803,178,981,341,694,673,523,519,366,624,277,699,222,720,0,720,0,566
        objects:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - face
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7 # <-------REDUZIDO DE 0.8 PARA 0.7 PARA TREINAR MODELO
    detect:
      enabled: true
      width: 840 #estava 3840
      height: 360 #estava 2160
      fps: 20 #estava 24
    snapshots:
      enabled: true

  reolink_garagem: # <----- REOLINk GARAGEM
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
      - path: 
          http://192.168.3.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Harley10
        roles:
        - record
        - rtmp
        - detect

#    rtmp:
#      enabled: false
#    ffmpeg:
#      inputs:
#        # High Resolution Stream
#        - path: rtsp://admin:H@rley2019@192.168.3.72:554//h265Preview_01_main
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#        # Low Resolution Stream
#        - path: rtsp://admin:H@rley2019@192.168.3.72:554//h264Preview_01_main
#          input_args: preset-rtsp-restream
#          roles:
#            - detect

    detect:
      enabled: true
      width: 840 #estava 3840
      height: 360 #estava 2160
      fps: 15 #estava 24
    snapshots:
      enabled: true
    motion:
      mask:
      - 257,360,0,360,0,0,480,0,840,145,737,360,224,24,95,36
    zones:
      porta_garagem:
        coordinates: 127,114,229,77,204,23,106,53
        objects:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - face
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups    
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /mnt/frigatedatacctv:/media/frigate
      - /frigate:/media/frigate
      - /home/frigate/config.yml:/config/config.yml
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXX"
      PLUS_API_KEY: 448d1d64-X
```

### Relevant Frigate log output

```shell
2025-01-15 08:48:31.831653101  [INFO] Preparing Frigate...
2025-01-15 08:48:32.146705362  [INFO] Starting Frigate...
2025-01-15 08:48:35.498685322  [2025-01-15 08:48:35] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2025-01-15 08:48:35.988686299  [2025-01-15 08:48:35] peewee_migrate.logs            INFO    : Starting migrations
2025-01-15 08:48:36.023001523  [2025-01-15 08:48:36] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-15 08:48:36.023460952  [2025-01-15 08:48:36] frigate.app                    INFO    : Running database vacuum
2025-01-15 08:49:11.385513016  [2025-01-15 08:49:11] frigate.app                    INFO    : Recording process started: 341
2025-01-15 08:49:11.388908731  [2025-01-15 08:49:11] frigate.app                    INFO    : go2rtc process pid: 96
2025-01-15 08:49:11.425716947  [2025-01-15 08:49:11] frigate.app                    INFO    : Output process started: 352
2025-01-15 08:49:11.471277872  [2025-01-15 08:49:11] detector.coral                 INFO    : Starting detection process: 351
2025-01-15 08:49:11.471281847  [2025-01-15 08:49:11] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-01-15 08:49:11.611044819  [2025-01-15 08:49:11] frigate.app                    INFO    : Camera processor started for tapo_quartos: 382
2025-01-15 08:49:11.623457040  [2025-01-15 08:49:11] frigate.app                    INFO    : Camera processor started for tapo_patio_hd: 383
2025-01-15 08:49:11.633434884  [2025-01-15 08:49:11] frigate.app                    INFO    : Camera processor started for tapo_jardim_hd: 384
2025-01-15 08:49:11.642503072  [2025-01-15 08:49:11] frigate.app                    INFO    : Camera processor started for tapo_qmeio: 385
2025-01-15 08:49:11.658526368  [2025-01-15 08:49:11] frigate.app                    INFO    : Camera processor started for reolink_frente: 387
2025-01-15 08:49:11.677860663  [2025-01-15 08:49:11] frigate.app                    INFO    : Camera processor started for reolink_garagem: 388
2025-01-15 08:49:11.695130815  [2025-01-15 08:49:11] frigate.app                    INFO    : Capture process started for tapo_quartos: 390
2025-01-15 08:49:11.708469819  [2025-01-15 08:49:11] frigate.app                    INFO    : Capture process started for tapo_patio_hd: 393
2025-01-15 08:49:11.717490573  [2025-01-15 08:49:11] frigate.app                    INFO    : Capture process started for tapo_jardim_hd: 394
2025-01-15 08:49:11.749162806  [2025-01-15 08:49:11] frigate.app                    INFO    : Capture process started for tapo_qmeio: 395
2025-01-15 08:49:11.751050626  [2025-01-15 08:49:11] frigate.app                    INFO    : Capture process started for reolink_frente: 397
2025-01-15 08:49:11.759229330  [2025-01-15 08:49:11] frigate.app                    INFO    : Capture process started for reolink_garagem: 398
2025-01-15 08:49:14.174524382  [2025-01-15 08:49:14] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
2025-01-15 08:48:32.146484867  [INFO] Preparing new go2rtc config...
2025-01-15 08:48:33.291250278  [INFO] Starting go2rtc...
2025-01-15 08:48:33.445008383  08:48:33.444 INF go2rtc version 1.8.4 linux/amd64
2025-01-15 08:48:33.446184771  08:48:33.446 INF [rtsp] listen addr=:8554
2025-01-15 08:48:33.446651028  08:48:33.446 INF [webrtc] listen addr=:8555
2025-01-15 08:48:33.446931028  08:48:33.446 INF [api] listen addr=:1984
2025-01-15 08:48:41.827613345  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Reolink RLC-821A, TP-Link C200, TP-Link C220, TP-Link C520WS

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/14e8b1d0-fc3b-4d87-a311-ce33140200e0)

![image](https://github.com/user-attachments/assets/2efb9029-09ff-4369-bfe6-cc09840715ba)

![image](https://github.com/user-attachments/assets/0dafc769-3f54-433e-a8ce-5b457f0389b4)

### Any other information that may be helpful

This is the LXC summary prior restarting it again:
![image](https://github.com/user-attachments/assets/a916e69d-f0d4-4f3d-8dfa-94892ef22566)

This is after I reboot the container:
![image](https://github.com/user-attachments/assets/e1862c2a-a687-44d1-bac4-7c9f87692acd)

**Comment by NickM-27** [comment]
I think the main recommendation would be to update to a more recent version of frigate as this will have a newer version of go2rtc. You may prefer to move directly to Frigate 0.15 which has a newer version of ffmpeg that some users have reported improved issues with unstable cameras

**Reply by vdiogo** [reply]
Thanks for the suggestion Nick. I do not have the go2rtc configuration in my config, so would this upgrade make any difference? Or should I add go2rtc config in my config?

**Reply by NickM-27** [reply]
It might still make a difference in other ways. With that said, I would suggest using ffmpeg presets and not manual input args. Also, would not recommend overriding the global args

**Reply by NickM-27** [reply]
The upgrade to 0.15 with the newer ffmpeg definitely has a good chance of making a difference

**Reply by vdiogo** [reply]
I used this script https://community-scripts.github.io/ProxmoxVE/scripts?id=frigate and installed 0.14, but now ran into a new issue:
![image](https://github.com/user-attachments/assets/fb18ecf9-a24d-4248-a388-8ef077d64f3b)

**Comment by vdiogo** [comment]
Running 0.15 beta which seems to have introduced a warning in the logs - or at least I don't remember having it on 0.13 - around SHM size (I had the default 64GB and adjusted - added this parameter in my stack - to 256MB) and its beens running smooth like a kitten.

Will keep on monitoring this, but by now (with all of my cameras enabled), previously Frigate would have crashed already.

**Comment by vdiogo** [comment]
@NickM-27 I created a new VM where I installed 0.15 Beta from Portainer (cloned existing VM and updated image target), and adjusted the configuration for the TP-Link cameras to use rtsp:
```
mqtt: # <----- MQTT SERVER
  host: 192.168.86.249
  port: 1883
  user: mqtt
  password: PASS
  topic_prefix: frigate
  client_id: frigate

########################################## GLOBAL SETTINGS
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral: # <----- GOOGLE CORAL USB
    type: edgetpu
    device: usb

ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  timezone: Europe/Lisbon

#################Global Object Settings
objects:
  track:
    - person
    - dog
    - cat
    - bicycle
    - car
    - motorcycle
    - bird
    - face
    - license_plate
    - package
  filters:
    person:
      threshold: 0.7 # <-------REDUZIDO DE 0.8 PARA 0.7 PARA TREINAR MODELO
      min_area: 5000
      max_area: 100000

#rtmp:
#  enabled: false

birdseye:
  enabled: true
  mode: objects # <----- Objects mode prevents birdseye from being triggered by bushes in the wind.
  restream: true
  quality: 8

record:
  enabled: true # <----- check the file system and delete any db entries for files which don't exist
  sync_recordings: true
  retain:
    days: 20 # <----- all motion segments are stored for 20 days
    mode: motion # <----- only retain video where motion was detected
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14



go2rtc:
  log:
    exec: trace
  streams:
## TAPO CORREDOR QUARTOS
    tapo_quartos_high: # TPLink C200
    - "ffmpeg:rtsp://USER:PASS@192.168.86.232/stream1"
    - "ffmpeg:tapo_quartos_high#audio=acc"
    tapo_quartos_low:
    - "ffmpeg:rtsp://USER:PASS@192.168.86.232/stream2"
    - "ffmpeg:tapo_quartos_low#audio=acc"

## TAPO ARRUMOS
    tapo_arrumos_high: # TPLink C200
    - "ffmpeg:rtsp://USER:PASS@192.168.86.125/stream1"
    - "ffmpeg:tapo_arrumos_high#audio=acc"
    tapo_arrumos_low:
    - "ffmpeg:rtsp://USER:PASS@192.168.86.125/stream2"
    - "ffmpeg:tapo_arrumos_low#audio=acc"    

## TAPO GARAGEM
    tapo_garagem_high: # TPLink C200
    - "ffmpeg:rtsp://USER:PASS@192.168.86.21/stream1"
    - "ffmpeg:tapo_garagem_high#audio=acc"
    tapo_garagem_low:
    - "ffmpeg:rtsp://USER:PASS@192.168.86.21/stream2"
    - "ffmpeg:tapo_garagem_low#audio=acc"    

## TAPO PÁTIO
    tapo_patio_high: # TPLink C520WS
    - "ffmpeg:rtsp://USER:PASS@192.168.86.53/stream1"
    - "ffmpeg:tapo_patio_high#audio=acc"
    tapo_patio_low:
    - "ffmpeg:rtsp://USER:PASS@192.168.86.53/stream2"
    - "ffmpeg:tapo_patio_low#audio=acc"    

## TAPO QUARTO MEIO
    tapo_qmeio_high: # TPLink C220
    - "ffmpeg:rtsp://USER:PASS@192.168.86.37/stream1"
    - "ffmpeg:tapo_qmeio_high#audio=acc"
    tapo_qmeio_low:
    - "ffmpeg:rtsp://USER:PASS@192.168.86.37/stream2"
    - "ffmpeg:tapo_qmeio_low#audio=acc"    

## TAPO JARDIM
    tapo_jardim_high: # TPLink C520WS
    - "ffmpeg:rtsp://USER:PASS@192.168.86.45/stream1"
    - "ffmpeg:tapo_jardim_high#audio=acc"
    tapo_jardim_low:
    - "ffmpeg:rtsp://USER:PASS@192.168.86.45/stream2"
    - "ffmpeg:tapo_jardim_low#audio=acc"    


cameras:
  tapo_quartos: # <----- TAPO QUARTOS
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/tapo_quartos_low
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tapo_quartos_high
        input_args: preset-rtsp-restream
        roles:
        - record
#        - audio
    live:
      stream_name: tapo_quartos_low
    objects:
      track:
        - person
        - face
    detect:
      width: 640 #estava 1920
      height: 360 #estava 1080
      fps: 5 #estava 15
      stationary:
        interval: 5
        threshold: 50      
    record:
      enabled: true
    snapshots:
      enabled: true
    zones:
      quarto_meio:
        coordinates: 0.792,0,0.531,0,0.521,0.525,0.673,0.709
        inertia: 3
        loitering_time: 0
      escadas_quartos:
        coordinates: 0.363,1,0.132,1,0.051,0.713,0.127,0.622
        inertia: 3
        loitering_time: 0
      quarto_frente:
        coordinates: 0.051,0,0.151,0,0.156,0.132,0.078,0.167
        inertia: 3
        loitering_time: 0


  tapo_garagem: # <----- TAPO GARAGEM
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/tapo_garagem_low
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tapo_garagem_high
        input_args: preset-rtsp-restream
        roles:
        - record
#        - audio
    live:
      stream_name: tapo_garagem_low
    objects:
      track:
        - person
        - face
      filters:
        motorcycle:
          mask: 0.444,0.61,0.589,0.526,0.792,0.595,0.833,0.975,0.591,0.973
    detect:
      width: 640
      height: 360
      fps: 5
    snapshots:
      enabled: true # <----- Enable snapshots
    zones:
      mota_garagem: # <----- Lugar da moto na garagem
        coordinates: 0.793,0.596,0.833,0.979,0.59,0.972,0.443,0.614,0.591,0.525

  tapo_arrumos: # <----- TAPO ARRUMOS
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/tapo_arrumos_low
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tapo_arrumos_high
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: tapo_arrumos_low
###### ADICIONADO 23DEZ2024      
#      output_args:
#        record: preset-record-generic-audio-copy
###### ADICIONADO 23DEZ2024  

       ###################HIGH RESOLUTION
#      inputs:
#        - path: rtsp://USER:PASS@192.168.86.125/stream1
#          roles:
#            - record
#            - audio
       #################LOW RESOLUTION
#        - path: rtsp://USER:PASS@192.168.86.125/stream2
#          roles:
#            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
    detect:
      width: 640 #estava 1920
      height: 360 #estava 1080
      fps: 5 #estava 15      
    zones:
      porta_patio:
        coordinates: 163,81,208,84,192,0,145,0
    snapshots:
      enabled: true # <----- Enable snapshots

  tapo_patio_hd: # <----- TAPO C520 WS PATIO 
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/tapo_patio_low
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tapo_patio_high
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: tapo_patio_low
    objects:
      track:
        - person
        - face
        - dog
        - cat
    detect:
      width: 640 #estava 2560
      height: 360 #estava 1440
      fps: 5 #estava 15
    zones:
      porta_vidro:
        coordinates: 0.299,0.278,0.279,0.009,0.209,0.007,0.234,0.288
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    snapshots:
      enabled: true # <----- Enable snapshots

  tapo_jardim_hd: # <----- TAPO C520 WS JARDIM
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/tapo_jardim_low
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tapo_jardim_high
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: tapo_jardim_low
    objects:
      track:
        - person
        - face
        - dog
        - cat
    detect:
      enabled: true
      width: 640 #estava 2560
      height: 360 #estava 1440
      fps: 5 #estava 30
    #zones:
    #  porta_patio:
    #    coordinates: 230,71,272,66,268,0,214,0
    snapshots:
      enabled: true # <----- Enable snapshots

  tapo_qmeio: # <----- TAPO QUARTO AMÉLIA
    birdseye:
      mode: objects # <----- Objects mode prevents birdseye from being triggered by bushes in the wind.
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/tapo_qmeio_low
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/tapo_qmeio_high
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: tapo_qmeio_low
    objects:
      track:
        - person
        - face
    detect:
      width: 640 #estava 2560
      height: 360 #estava 1440
      fps: 5 #estava 30
    snapshots:
      enabled: true # <----- Enable snapshots


  reolink_frente: # <----- REOLINK FRENTE
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: 
            http://192.168.3.68/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Harley10
          roles:
            - record
            - detect
 
    detect:
      enabled: true
      width: 840 #estava 3840
      height: 360 #estava 2160
      fps: 5 #estava 20
    snapshots:
      enabled: true

    zones:
      acesso_casa: # <-------- Zona pedonal para acesso a casa
        coordinates: 
          0.005,0.794,0.047,0.961,0.067,0.992,0.194,0.985,0.408,0.717,0.544,0.946,0.825,0.349,0.737,0.264,0.661,0.254,0.621,0.235,0.231,0.665,0.19,0.575
        loitering_time: 0
        objects: person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7 # <-------REDUZIDO DE 0.8 PARA 0.7 PARA TREINAR MODELO        


  reolink_garagem: # <----- REOLINk GARAGEM
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: 
            http://192.168.3.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Harley10
          roles:
            - record
#            - rtmp
            - detect

#    rtmp:
#      enabled: false
#    ffmpeg:
#      inputs:
#        # High Resolution Stream
#        - path: rtsp://admin:PASS@192.168.3.72:554//h265Preview_01_main
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#        # Low Resolution Stream
#        - path: rtsp://admin:PASS@192.168.3.72:554//h264Preview_01_main
#          input_args: preset-rtsp-restream
#          roles:
#            - detect

    detect:
      enabled: true
      width: 840 #estava 3840
      height: 360 #estava 2160
      fps: 5 #estava 15
    snapshots:
      enabled: true
    motion:
      mask: 
        0.309,0.985,0,0.986,0.005,0.01,0.574,0.01,1,0.418,0.836,0.985,0.267,0.067,0.088,0.054
    zones:
      porta_garagem:
        coordinates: 0.142,0.273,0.25,0.219,0.231,0.056,0.117,0.113
        objects:
          - person
          - car
          - motorcycle
          - face
        inertia: 3
        loitering_time: 0
version: 0.15-1

```

Restarts continue to happen but Frigate seems to be recovering well, but get a log of errors in the logs, some cameras stop streaming and Coral speed is sky high:
![image](https://github.com/user-attachments/assets/e7666d22-0602-4cae-a11e-e3523abe5e7a)
