### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by trevmlt** [blakeblackshear/frigate#15990] [Config Support]
### Describe the problem you are having

I keep seeing this line over and over in the Nginx log (I have this installed in Portainer):

2025-01-14 20:14:52.447021749  127.0.0.1 - - [14/Jan/2025:20:14:52 -0700] "" 400 0 "-" "-" "-"

The cameras are all working in Frigate and I can even pull them into Alexa. This doesn't say it is an error, but I would like to know what this is. Any help is appreciated!

Thanks.

### Version

0.14.1

### Frigate config file

```yaml
Config is ok
```

### Relevant Frigate log output

```shell
not the problem log - shows up in Nginx log
```

### Relevant go2rtc log output

```shell
not the problem log - shows up in Nginx log
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable

    shm_size: "256mb" # update for your cameras based on calculation

    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/db:/db
      - /home/frigate:/config:rw
      - /mnt/gp1Array/cams/frigate:/media/frigate                     # modify to match your setup
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    
    ports:
      - 5000:5000/tcp
      - 8554:8554/tcp
      - 8555:8555/tcp
      - 8555:8555/udp
      
    environment:
      FRIGATE_RTSP_PASSWORD: "whatever"  #modify to whatever if using rtsp
  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '12:30' ]; then
            docker restart frigate
          fi
          sleep 60
        done
```

### Object Detector

Coral
