### DISCUSSION TITLE
[Bug]: Tracked Object Details card + Gen AI

### DISCUSSION THREAD

**Discussion by qtronixx** [blakeblackshear/frigate#15993] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I updated to beta 5 yesterday, and noticed something interesting.
First, although Frigat identified the object as a bird, Gemini described it as a dog, and it is clear from the description that the prompta was transmitted to gemini from a dog.
Secondly, the "Regenerate" button has some numbers, and interestingly, the first 4 digits in the number on all the cards are the same, then +/- random.

### Steps to reproduce

.

### Version

0.15.0 Beta 5

### Frigate config file

```yaml
genai:
  enabled: true
  provider: gemini
  api_key: My_API_Key
  model: gemini-2.0-flash-exp
  prompt: Analyze the {label} in the sequence of images from the {camera} security
    camera with as much detail as possible. Focus on the actions and potential intent
    of the {label}. Reply in Russian
  object_prompts:
    # person: "Examine the main person in these images. What are they doing and what might their actions suggest about their intent (e.g., approaching a door, leaving an area, standing still)? Do not describe the surroundings or static details."
    car: Observe the primary vehicle in these images. Focus on its movement, direction,
      or purpose (e.g., parking, approaching, circling). Reply in Russian
    cat: Observe the cat in these images. Focus on its movement and intent (e.g.,
      wandering, hunting, interacting with objects). If the cat is near the flower
      pots or engaging in any specific actions, mention it. Reply in Russian
```

### docker-compose file or Docker CLI command

```yaml
.
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

misc

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/dcca2d31-5b6c-46c8-aeab-51579cb42cc5)
