### DISCUSSION TITLE
[Config Support]: Reolink - missing sound

### DISCUSSION THREAD

**Discussion by marc4s** [blakeblackshear/frigate#16018] [Config Support] [answered]
### Describe the problem you are having

I know that those cameras seems to be buggy. I know that  they are not recommended... but I still would like to understand

the sound (nativeaac) in the http stream is working fine and my local ffmpeg is recording it without special options. 
but even with multiple different variants of frigate config sound is not recognized and not recorded.

```
fmpeg -i "http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW"  reolink-flv.mp4
ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, flv, from 'http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW':
  Metadata:
    displayWidth    : 896
    displayHeight   : 672
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x672, 19 fps, 30 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x5d26b991f780] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5d26b991f780] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x5d26b991f780] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=21 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=20 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'reolink-flv.mp4':
  Metadata:
    displayWidth    : 896
    displayHeight   : 672
    encoder         : Lavf60.16.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 896x672, q=2-31, 20 fps, 10240 tbn
    Metadata:
      encoder         : Lavc60.31.102 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc60.31.102 aac
[out#0/mp4 @ 0x5d26b970df00] video:4546kB audio:309kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.524276%
frame=  925 fps= 21 q=-1.0 Lsize=    4880kB time=00:00:46.97 bitrate= 851.1kbits/s dup=1 drop=0 speed=1.04x    
[libx264 @ 0x5d26b991f780] frame I:4     Avg QP:17.24  size:246803
[libx264 @ 0x5d26b991f780] frame P:233   Avg QP:19.45  size: 15057
[libx264 @ 0x5d26b991f780] frame B:688   Avg QP:27.19  size:   231
[libx264 @ 0x5d26b991f780] consecutive B-frames:  0.8%  0.2%  0.0% 99.0%
[libx264 @ 0x5d26b991f780] mb I  I16..4:  8.0% 17.6% 74.4%
[libx264 @ 0x5d26b991f780] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4: 33.3%  1.3%  3.1%  0.0%  0.0%    skip:62.3%
[libx264 @ 0x5d26b991f780] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8: 13.9%  0.0%  0.0%  direct: 0.0%  skip:86.0%  L0:20.4% L1:79.2% BI: 0.5%
[libx264 @ 0x5d26b991f780] 8x8 transform intra:18.4% inter:19.7%
[libx264 @ 0x5d26b991f780] coded y,uvDC,uvAC intra: 99.6% 81.0% 57.2% inter: 5.9% 3.9% 0.3%
[libx264 @ 0x5d26b991f780] i16 v,h,dc,p:  3%  0% 73% 23%
[libx264 @ 0x5d26b991f780] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 10%  4% 31%  9%  7%  8% 10% 12%  8%
[libx264 @ 0x5d26b991f780] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 14%  5% 18% 12%  8%  9% 11% 13%  9%
[libx264 @ 0x5d26b991f780] i8c dc,h,v,p: 49% 16% 27%  9%
[libx264 @ 0x5d26b991f780] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x5d26b991f780] ref P L0: 87.4%  1.9% 10.1%  0.6%
[libx264 @ 0x5d26b991f780] ref B L0: 89.2% 10.7%  0.0%
[libx264 @ 0x5d26b991f780] ref B L1: 83.6% 16.4%
[libx264 @ 0x5d26b991f780] kb/s:805.10
[aac @ 0x5d26b97c45c0] Qavg: 64906.453
Exiting normally, received signal 2
```

I even tried to use the frigate config with opus instead of aac like it is described in some how to s but still no luck

### Version

0.15.x

### Frigate config file

```yaml
ffmpeg:
  #path: '5.0'
  output_args:
    #no sound with reolink:
    #record: preset-record-generic-audio-copy
    #no sound with reolink:
    record: preset-record-generic-audio-aac

#ModelRLC-410W
#UID95270005JALP1M36
#Build No.build 22042505
#Hardware No.IPC_30K128M4MP
#Config Versionv3.1.0.0
#Firmware Versionv3.1.0.739_22042505
#DetailsIPC_30K128M4MPS22E1W71100000001
    hauseingang_reo:
      #working but no sound and no recordings
      #- ffmpeg:http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=PW#video=copy#audio=copy#audio=aac
      - http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=PW
      - ffmpeg:hauseingang_reo#audio=copy#audio=aac
    hauseingang_reo_sub:
      #working but no sound:
      #- ffmpeg:http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW
      #working but no sound:
      #- http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW
      #- ffmpeg:hauseingang_reo_sub#audio=copy#audio=aac
      #working but no sound:
      - http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW
      - ffmpeg:hauseingang_reo_sub#audio=copy
      #DOES NOT WORK:
      #- rtmp://192.168.158.11/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=PW
      #- rtmp://192.168.158.11/bcs/channel0_sub.bcs?user=user&password=PW
      #WORKS even without FFMPEG but no sound and poor quality:
      #rtsp://user:PW@192.168.158.11:554/h264Preview_01_sub
      #WORKS even without FFMPEG but no sound and poor quality:
      #- rtsp://user:PW@192.168.158.11:554/h264Preview_01_sub#audio=copy#audio=opus
      #working but no sound
      #- rtsp://user:PW@192.168.158.11:554/h264Preview_01_sub
      #- "ffmpeg:hauseingang_reo_sub#audio=copy#audio=aac"
      #audio=copy#audio=opus
      #DOES NOT WORK with FFMPEG:RTSP ffmpeg:rtsp://user:PW@192.168.158.11:554/h264Preview_01_sub#audio=copy#audio=opus
      #- "ffmpeg:rtsp://user:PW@192.168.158.11:554/h264Preview_01_sub"
      #- "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"
```

### Relevant Frigate log output

```shell
2025-01-17 09:42:13.443488559  [INFO] Preparing Frigate...
2025-01-17 09:42:13.449146490  [INFO] Starting Frigate...
2025-01-17 09:42:15.527305701  [2025-01-17 09:42:15] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-17 09:42:15.574698619  [2025-01-17 09:42:15] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-17 09:42:15.663277653  [2025-01-17 09:42:15] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2025-01-17 09:42:42.475651379  [2025-01-17 09:42:42] frigate.app                    INFO    : Starting Frigate (0.15.0-173b7aa)
2025-01-17 09:42:42.478358530  [2025-01-17 09:42:42] peewee_migrate.logs            INFO    : Starting migrations
2025-01-17 09:42:42.497659851  [2025-01-17 09:42:42] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-17 09:42:42.498564221  [2025-01-17 09:42:42] frigate.app                    INFO    : Recording process started: 441
2025-01-17 09:42:42.498709702  [2025-01-17 09:42:42] frigate.app                    INFO    : Review process started: 450
2025-01-17 09:42:42.501541258  [2025-01-17 09:42:42] frigate.app                    INFO    : go2rtc process pid: 98
2025-01-17 09:42:42.518615541  [2025-01-17 09:42:42] detector.coral                 INFO    : Starting detection process: 457
2025-01-17 09:42:42.532040217  [2025-01-17 09:42:42] frigate.app                    INFO    : Output process started: 476
2025-01-17 09:42:42.585478583  [2025-01-17 09:42:42] frigate.app                    INFO    : Camera processor started for garagetor: 490
2025-01-17 09:42:42.597360965  [2025-01-17 09:42:42] frigate.app                    INFO    : Camera processor started for carport: 494
2025-01-17 09:42:42.597597326  [2025-01-17 09:42:42] frigate.app                    INFO    : Camera processor started for untermcarport: 504
2025-01-17 09:42:42.621766013  [2025-01-17 09:42:42] frigate.app                    INFO    : Camera processor started for hausflur: 513
2025-01-17 09:42:42.621912918  [2025-01-17 09:42:42] frigate.app                    INFO    : Camera processor started for hauseingang: 527
2025-01-17 09:42:42.625575246  [2025-01-17 09:42:42] frigate.app                    INFO    : Camera processor started for garage: 535
2025-01-17 09:42:42.653983856  [2025-01-17 09:42:42] frigate.app                    INFO    : Capture process started for garagetor: 554
2025-01-17 09:42:42.670115020  [2025-01-17 09:42:42] frigate.app                    INFO    : Capture process started for carport: 565
2025-01-17 09:42:42.685008680  [2025-01-17 09:42:42] frigate.app                    INFO    : Capture process started for untermcarport: 577
2025-01-17 09:42:42.728998571  [2025-01-17 09:42:42] frigate.app                    INFO    : Capture process started for hausflur: 601
2025-01-17 09:42:42.742712739  [2025-01-17 09:42:42] frigate.app                    INFO    : Capture process started for hauseingang: 604
2025-01-17 09:42:42.756457121  [2025-01-17 09:42:42] frigate.app                    INFO    : Capture process started for garage: 614
2025-01-17 09:42:42.888113049  [2025-01-17 09:42:42] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-01-17 09:42:42.976442250  [2025-01-17 09:42:42] frigate.api.fastapi_app        INFO    : FastAPI started
2025-01-17 09:42:45.267611812  [2025-01-17 09:42:42] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-01-17 09:42:45.272276801  [2025-01-17 09:42:45] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
no log output for this camera/ip
```

### Frigate stats

```json
{"cameras":{"garagetor":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":490,"capture_pid":554,"ffmpeg_pid":1201,"audio_rms":0.0,"audio_dBFS":0.0},"carport":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":494,"capture_pid":565,"ffmpeg_pid":1193,"audio_rms":0.0,"audio_dBFS":0.0},"untermcarport":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":504,"capture_pid":577,"ffmpeg_pid":1196,"audio_rms":0.0,"audio_dBFS":0.0},"hausflur":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":513,"capture_pid":601,"ffmpeg_pid":1199,"audio_rms":0.0,"audio_dBFS":0.0},"hauseingang":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":527,"capture_pid":604,"ffmpeg_pid":613,"audio_rms":0.0,"audio_dBFS":0.0},"garage":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":535,"capture_pid":614,"ffmpeg_pid":1205,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":10.81,"detection_start":0.0,"pid":457}},"detection_fps":0.0,"cpu_usages":{"frigate.full_system":{"cpu":"0.8","mem":"16.8"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"17":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"2.6","cpu_average":"1","mem":"0.2","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"114":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"116":{"cpu":"1.0","cpu_average":"3","mem":"2.0","cmdline":"python3 -u -m frigate"},"130":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: master process nginx"},"169":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"202":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"203":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"204":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"211":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"331":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"441":{"cpu":"0.6","cpu_average":"0","mem":"1.2","cmdline":"frigate.recording_manager"},"450":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.review_segment_manager"},"457":{"cpu":"0.1","cpu_average":"1","mem":"1.2","cmdline":"frigate.detector.coral"},"476":{"cpu":"0.3","cpu_average":"0","mem":"1.2","cmdline":"frigate.output       "},"490":{"cpu":"0.0","cpu_average":"0","mem":"1.2","cmdline":"frigate.process:garagetor"},"494":{"cpu":"0.1","cpu_average":"0","mem":"1.2","cmdline":"frigate.process:carport"},"504":{"cpu":"0.1","cpu_average":"0","mem":"1.2","cmdline":"frigate.process:untermcarport"},"507":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"513":{"cpu":"0.1","cpu_average":"0","mem":"1.2","cmdline":"frigate.process:hausflur"},"527":{"cpu":"0.7","cpu_average":"4","mem":"1.2","cmdline":"frigate.process:hauseingang"},"535":{"cpu":"0.0","cpu_average":"0","mem":"1.2","cmdline":"frigate.process:garage"},"538":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"553":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"554":{"cpu":"0.3","cpu_average":"0","mem":"1.1","cmdline":"frigate.capture:garagetor"},"563":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"565":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.capture:carport"},"577":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.capture:untermcarport"},"579":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"591":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"600":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"601":{"cpu":"0.2","cpu_average":"0","mem":"1.1","cmdline":"frigate.capture:hausflur"},"604":{"cpu":"0.5","cpu_average":"0","mem":"1.1","cmdline":"frigate.capture:hauseingang"},"613":{"cpu":"1.1","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hauseingang_reo_sub -r 5 -vf fps=5,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"614":{"cpu":"0.3","cpu_average":"0","mem":"1.1","cmdline":"frigate.capture:garage"},"1160":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"1181":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"},"1202":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/hauseingang_reo -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/hauseingang@%Y%m%d%H%M%S%z.mp4"},"1205":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_reo_sub -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"1207":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_reo -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4"},"1208":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/garage_reo?video&audio -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5bb6f9bddd7e2ef502ff7b68cbf75b86"},"1210":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/garage_reo_sub?audio -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/fa7e152374e1cbfa4f5277c674ec543c"}},"service":{"uptime":176,"version":"0.15.0-173b7aa","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":937803.7,"used":755670.1,"free":134424.2,"mount_type":"ext4"},"/media/frigate/clips":{"total":937803.7,"used":755670.1,"free":134424.2,"mount_type":"ext4"},"/tmp/cache":{"total":953.7,"used":5.0,"free":948.6,"mount_type":"tmpfs"},"/dev/shm":{"total":800.0,"used":18.7,"free":781.3,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1737107138},"processes":{"recording":{"pid":441},"review_segment":{"pid":450},"go2rtc":{"pid":98}}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
#    image: ghcr.io/blakeblackshear/frigate:stable
#    image: ghcr.io/blakeblackshear/frigate:0.13.2
#    image: ghcr.io/blakeblackshear/frigate:0.14.1
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta5
    shm_size: "800mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /root/frigate/config.yml:/config/config.yml
      - /root/frigate/:/config/
      - /data1TB/frigatestorage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          #size: 1000000000
          size: 1000000000
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PLUS_API_KEY: "hidden"
      FRIGATE_RTSP_PASSWORD: ""
```

### Object Detector

Coral

**Comment by marc4s** [comment]
meanwhle I found that the documentation here
https://docs.frigate.video/configuration/camera_specific/

differs from this reolink example in the ffmpeg_presets.
I adjusted it also to this example below but still no audio :
https://docs.frigate.video/configuration/ffmpeg_presets/
```
go2rtc:
  streams:
    reolink_cam: http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password

cameras:
  reolink_cam:
    ffmpeg:
      inputs:
        - path: http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
          input_args: preset-http-reolink
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/reolink_cam
          input_args: preset-rtsp-generic
          roles:
            - record
```

**Reply by hawkeye217** [reply]
You should set them up according to the documentation you already linked to:

https://docs.frigate.video/configuration/camera_specific/#reolink-cameras

Be sure you copy the code exactly as documented. Your example is missing some key elements.

**Comment by marc4s** [comment]
with this config below I have sound in records. but how to get it enabled in livestream?

```
 hauseingang_reo:
      - http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=PW
      - ffmpeg:hauseingang_reo#audio=opus
#moved from go2rtc to cameras itself


  hauseingang:
    ffmpeg:
      output_args:
        #record: preset-record-generic-audio-aac
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/hauseingang_reo
          input_args: preset-rtsp-generic
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/hauseingang_reo_sub
        - path: http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW
          input_args: preset-http-reolink
          roles:
            - detect
            - audio
  
```

**Reply by hawkeye217** [reply, marked as answer]
See [the docs](https://docs.frigate.video/guides/configuring_go2rtc/):

> You should set the stream name under go2rtc to match the name of your camera so that Frigate will automatically map it and be able to use better live view options for the camera.

Also, see the [Live view docs](https://docs.frigate.video/configuration/live).

**Reply by marc4s** [reply]
WOHOOO - thanks a lot

**Reply by hawkeye217** [reply]
Happy to help!

**Comment by marc4s** [comment]
as I started with frigate 0.13.x I retested the original config you mentioned and which was not working yet.
it ist still not working in frigate 0.15.x - I can see a stream in birds-eye but no recordings at all:

```
go2rtc:
  streams:
    your_reolink_camera:
      - "ffmpeg:http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=PW#video=copy#audio=copy#audio=opus"
    your_reolink_camera_sub:
      - "ffmpeg:http://192.168.158.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=PW"

cameras:
  your_reolink_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/your_reolink_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/your_reolink_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```
results in
```
2025-01-17 13:42:26.483353812  [2025-01-17 13:42:26] ffmpeg.hauseingang.record      ERROR   : [in#0 @ 0x5c6e81763c80] Error opening input: Invalid data found when processing input
2025-01-17 13:42:26.483377877  [2025-01-17 13:42:26] ffmpeg.hauseingang.record      ERROR   : Error opening input file rtsp://127.0.0.1:8554/hauseingang_reo.
2025-01-17 13:42:26.483403155  [2025-01-17 13:42:26] ffmpeg.hauseingang.record      ERROR   : Error opening input files: Invalid data found when processing input
```
