### DISCUSSION TITLE
[Support]: HTTP 502 Bad Gateway during recording playback

### DISCUSSION THREAD

**Discussion by numbersixnz** [blakeblackshear/frigate#16016] [General Support]
### Describe the problem you are having

Frigate worked fine for a while but in the last day or so I've been unable to playback recordings.

I can mouseover the thumbnails and the recordings playback OK.

As soon as I click to view a recording's detail, nothing happens in the browser.

In the browser dev console I get errors like this:

`GET http://192.168.1.88:5000/vod/carport/start/1737064800/end/1737068400/master.m3u8`

This exact error can be reproduced if I manually browse to the above URL.

Live streaming the substreams from the cameras works fine; only recording playback has issues.

Updated to latest Beta5 to see if that resolved the issue; it didn't.

### Version

0.15.0-173b7aa

### What browser(s) are you using?

- Google Chrome
- Firefox
- Brave

All show the same thing in their respective dev consoles.

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 0.0.0.0
  port: 1883
  topic_prefix: frigate
  user: user
  password: password

detectors:
  # coral1:
  #   type: edgetpu
  #   device: usb:0
  # coral2:
  #   type: edgetpu
  #   device: usb:1
  ov1:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic-audio-copy

objects:
  track:
    - person
    - car
    - bird
    - dog
    - bicycle

review:
  detections:
    labels:
      - person
      - car
      - dog
  alerts:
    labels:
      - person

birdseye:
  enabled: true
  restream: true

motion:
  enabled: true

snapshots:
  enabled: true
  timestamp: true

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 3
    post_capture: 3
  detections:
    retain:
      days: 30
    pre_capture: 3
    post_capture: 3

detect:
  enabled: true

go2rtc:
  streams:
    studio_sub: ffmpeg:rtsp://user:password@x.x.x.x:554/stream2#timeout=10
    shed_sub: ffmpeg:rtsp://user:password@x.x.x.x:554/stream2#timeout=10
    carport_sub: ffmpeg:rtsp://user:password@x.x.x.x:554/stream2#timeout=10


cameras:
  carport:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
  studio:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/studio_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
  shed:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/shed_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
2025-01-17 10:31:17.855731056  [INFO] Preparing Frigate...
2025-01-17 10:31:17.862931982  [INFO] Starting Frigate...
2025-01-17 10:31:19.265750484  [2025-01-17 10:31:19] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-17 10:31:19.277725143  [2025-01-17 10:31:19] frigate.util.config            INFO    : copying config as backup...
2025-01-17 10:31:19.293513168  [2025-01-17 10:31:19] frigate.util.config            INFO    : Migrating frigate config from 0.15-0 to 0.15-1...
2025-01-17 10:31:19.293743601  [2025-01-17 10:31:19] frigate.util.config            INFO    : Finished frigate config migration...
2025-01-17 10:31:29.752609623  [2025-01-17 10:31:29] frigate.app                    INFO    : Starting Frigate (0.15.0-173b7aa)
2025-01-17 10:31:29.753613160  [2025-01-17 10:31:29] frigate.app                    INFO    : Creating directory: /tmp/cache
2025-01-17 10:31:29.758440452  [2025-01-17 10:31:29] peewee_migrate.logs            INFO    : Starting migrations
2025-01-17 10:31:29.758822297  [2025-01-17 10:31:29] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-17 10:31:29.762728560  [2025-01-17 10:31:29] frigate.app                    INFO    : Recording process started: 403
2025-01-17 10:31:29.766145269  [2025-01-17 10:31:29] frigate.app                    INFO    : Review process started: 405
2025-01-17 10:31:29.767239107  [2025-01-17 10:31:29] frigate.app                    INFO    : go2rtc process pid: 98
2025-01-17 10:31:29.774417012  [2025-01-17 10:31:29] detector.ov1                   INFO    : Starting detection process: 419
2025-01-17 10:31:29.782581076  [2025-01-17 10:31:29] frigate.app                    INFO    : Output process started: 435
2025-01-17 10:31:29.805745118  [2025-01-17 10:31:29] frigate.app                    INFO    : Camera processor started for carport: 449
2025-01-17 10:31:29.810065462  [2025-01-17 10:31:29] frigate.app                    INFO    : Camera processor started for studio: 453
2025-01-17 10:31:29.814228132  [2025-01-17 10:31:29] frigate.app                    INFO    : Camera processor started for shed: 456
2025-01-17 10:31:29.818846358  [2025-01-17 10:31:29] frigate.app                    INFO    : Capture process started for carport: 460
2025-01-17 10:31:29.840505347  [2025-01-17 10:31:29] frigate.app                    INFO    : Capture process started for studio: 480
2025-01-17 10:31:29.846730798  [2025-01-17 10:31:29] frigate.app                    INFO    : Capture process started for shed: 483
2025-01-17 10:31:29.978799315  [2025-01-17 10:31:29] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-01-17 10:31:30.036269105  [2025-01-17 10:31:30] frigate.api.fastapi_app        INFO    : FastAPI started
2025-01-17 10:33:14.022521039  [2025-01-17 10:33:14] frigate.api.review             WARNING : No motion data found for the requested time range
2025-01-17 10:33:19.347096463  [2025-01-17 10:33:19] frigate.api.review             WARNING : No motion data found for the requested time range
2025-01-17 10:33:25.747739549  [2025-01-17 10:33:25] frigate.api.review             WARNING : No motion data found for the requested time range
2025-01-17 10:33:39.645884257  [2025-01-17 10:33:39] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:33:40.719050579  [2025-01-17 10:33:40] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:39:22.909369264  [2025-01-17 10:39:22] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:39:23.972167185  [2025-01-17 10:39:23] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:39:38.415433750  [2025-01-17 10:39:38] frigate.api.media              ERROR   : No recordings found for studio during the requested time range
2025-01-17 10:39:39.475909621  [2025-01-17 10:39:39] frigate.api.media              ERROR   : No recordings found for studio during the requested time range
2025-01-17 10:45:24.411061388  [2025-01-17 10:45:24] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:45:25.482881042  [2025-01-17 10:45:25] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:55:21.981470226  [2025-01-17 10:55:21] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
2025-01-17 10:55:23.055531418  [2025-01-17 10:55:23] frigate.api.media              ERROR   : No recordings found for carport during the requested time range
```

### Relevant go2rtc log output

```shell
N/A.  Go2rtc is working fine.  Home Assistant is using WebRTC streams without issue.
```

### FFprobe output from your camera

```shell
N/A.  Live playback is working fine + Home Assistant and Unifi can both stream from the cameras without issue.
```

### Frigate stats

```json
{"cameras":{"carport":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":4.8,"detection_enabled":true,"pid":449,"capture_pid":460,"ffmpeg_pid":463,"audio_rms":0.0,"audio_dBFS":0.0},"studio":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":453,"capture_pid":480,"ffmpeg_pid":488,"audio_rms":0.0,"audio_dBFS":0.0},"shed":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":456,"capture_pid":483,"ffmpeg_pid":493,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"ov1":{"inference_speed":6.04,"detection_start":0.0,"pid":419}},"detection_fps":4.8,"gpu_usages":{"intel-vaapi":{"gpu":"0.95%","mem":"-%","clients":{"419":"3.44%","463":"0.63%","488":"0.77%","493":"0.53%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"1.1","mem":"43.6"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"18":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"98":{"cpu":"0.2","cpu_average":"0","mem":"0.0","cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml"},"106":{"cpu":"0.8","cpu_average":"1","mem":"0.2","cmdline":"python3 -u -m frigate"},"108":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"129":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"169":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"170":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"171":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"172":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"173":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"306":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"403":{"cpu":"0.3","cpu_average":"0","mem":"0.1","cmdline":"frigate.recording_manager"},"405":{"cpu":"0.2","cpu_average":"0","mem":"0.1","cmdline":"frigate.review_segment_manager"},"419":{"cpu":"2.9","cpu_average":"7","mem":"0.4","cmdline":"frigate.detector.ov1 "},"435":{"cpu":"1.0","cpu_average":"2","mem":"0.1","cmdline":"frigate.output       "},"449":{"cpu":"1.7","cpu_average":"2","mem":"0.1","cmdline":"frigate.process:carport"},"453":{"cpu":"0.8","cpu_average":"1","mem":"0.1","cmdline":"frigate.process:studio"},"456":{"cpu":"0.7","cpu_average":"1","mem":"0.1","cmdline":"frigate.process:shed "},"460":{"cpu":"0.2","cpu_average":"0","mem":"0.1","cmdline":"frigate.capture:carport"},"463":{"cpu":"0.6","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/c540v_carport_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/carport@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=736:h=416,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"479":{"cpu":"0.3","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@0.0.0.180:554/stream2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6cd87af3f8acc02e30b93e3b4c7b0be3"},"480":{"cpu":"0.2","cpu_average":"0","mem":"0.1","cmdline":"frigate.capture:studio"},"483":{"cpu":"0.3","cpu_average":"0","mem":"0.1","cmdline":"frigate.capture:shed "},"488":{"cpu":"0.7","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/c540v_studio_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/studio@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=736:h=416,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"493":{"cpu":"0.6","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-173b7aa -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/c540_shed_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/shed@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=736:h=416,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"494":{"cpu":"0.3","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@0.0.0.175:554/stream2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b0851f0eedf8f588e04d1f6a1f5e9a03"},"496":{"cpu":"0.3","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@0.0.0.179:554/stream2 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5de66638f32ba154d502e09a6d405ad9"},"539":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 736x416 -i pipe: -threads 1 -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"546":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 736x416 -i pipe: -threads 1 -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"553":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 736x416 -i pipe: -threads 1 -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"560":{"cpu":"0.2","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"8403":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"8452":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":1766,"version":"0.15.0-173b7aa","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":7077333.0,"used":144735.0,"free":6932598.0,"mount_type":"nfs"},"/media/frigate/clips":{"total":7077333.0,"used":144735.0,"free":6932598.0,"mount_type":"nfs"},"/tmp/cache":{"total":131072.0,"used":19818.6,"free":111253.4,"mount_type":"overlay"},"/dev/shm":{"total":412.0,"used":70.1,"free":341.9,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1737072055},"processes":{"recording":{"pid":403},"review_segment":{"pid":405},"go2rtc":{"pid":98}}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    # image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta5
    privileged: true
    restart: always
    shm_size: "412mb"
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
      - 8971:8971/tcp
      - 1984:1984/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./media/frigate:/media/frigate
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLUS_API_KEY=${PLUS_API_KEY}
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

TP-Link Vigi C540 and C540V

### Screenshots of the Frigate UI's System metrics pages

<img width="2420" alt="image" src="https://github.com/user-attachments/assets/7d0af268-42d9-425f-9d91-aac44c1f593a" />

<img width="2427" alt="image" src="https://github.com/user-attachments/assets/61a34693-d5b5-4db5-85ae-a337caf13088" />

<img width="2431" alt="image" src="https://github.com/user-attachments/assets/55fbb7dc-634c-4f2a-ae4c-7013252a7015" />
