### DISCUSSION TITLE
[Support]:

### DISCUSSION THREAD

**Discussion by jazzjackrabbit-exe** [blakeblackshear/frigate#16019] [General Support]
### Describe the problem you are having

For some time now, I've been struggling with an issue where the Frigate card crashes my HA app on iOS. The problem only occurs on mobile internet – when I'm on Wi-Fi in the network where Home Assistant is running, everything works fine. The sequence of events is as follows: I launch the HA app, go to the tab with the Frigate cards. The image loads, I see the camera preview, and after a few seconds, I get a reconnecting message and a notification about losing connection to Home Assistant. At that point, I have to close the entire app, and after a few seconds, I can open it again. Does anyone know how to solve this problem?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: xxx
  user: xxx
  password: xxx

cameras:
  CAM0:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - record
    detect:
      width: 1280  
      height: 720  
      fps: 5      record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 10

 CAM1:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - record
    detect:
      width: 1280 
      height: 720  
      fps: 5  
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 10

  CAM2:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - record
    detect:
      width: 1280  
      height: 720 
      fps: 5
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 10

record:
  events:
    pre_capture: 5
    post_capture: 5

version: 0.14
```

### Relevant Frigate log output

```shell
error
2025-01-17 10:50:48
frigate.ptz.onvif
Onvif is not setup for CAM0
error
2025-01-17 10:50:48
frigate.ptz.onvif
Onvif is not setup for CAM1
error
2025-01-17 10:50:48
frigate.ptz.onvif
Onvif is not setup for CAM2
```

### Relevant go2rtc log output

```shell
No log after this error.
```

### FFprobe output from your camera

```shell
dont really know how to do it.
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
dont really know how to do it.
```

### Object Detector

CPU (no coral)

### Network connection

Wireless

### Camera make and model

SMAR PTZ IP H.265X 1080p

### Screenshots of the Frigate UI's System metrics pages

![9x9jpj4kddde1](https://github.com/user-attachments/assets/34896f73-796a-4527-a5d9-3bbc1776ebeb)
