### DISCUSSION TITLE
[Config Support]: SEI type 5 size 2512 truncated...

### DISCUSSION THREAD

**Discussion by gspitale** [blakeblackshear/frigate#16014] [Config Support] [answered]
### Describe the problem you are having

logs show repeated lines with this message:
2025-01-16 15:31:54.124595765  [h264 @ 0x7f7c38015980] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:31:54.125262162  [h264 @ 0x7f7c38015980] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:03.514400173  [h264 @ 0x7f7c395bc700] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:03.515185815  [h264 @ 0x7f7c395bc700] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:13.439177348  [h264 @ 0x7f7c39564e80] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:13.440382541  [h264 @ 0x7f7c39564e80] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:23.881177526  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:23.881884263  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:33.934780231  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:33.936451090  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:37.090106396  [h264 @ 0x7f7c395cb9c0] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:37.090820320  [h264 @ 0x7f7c395cb9c0] SEI type 5 size 2512 truncated at 1928

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: homeassistant.havenwood
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: Mosquitto
  password: xxxxx

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral_1:
    type: edgetpu
    device: pci:0
  coral_2:
    type: edgetpu
    device: pci:1

audio:
  enabled: true

objects:
  track:
    - person
    - bicycle
    - car
    - bird
    - cat
    - dog
    - bear
    - mouse
#  filters:
#    person:
#      min_area: 3000
#      max_area: 100000
#      threshold: .75
#    cat:
#      min_area: 500
#      max_area: 3000
#      threshold: .75
#    mouse:
#      max_area: 1000
#      threshold: .75
#    bird:
#     max_area: 4000
#      threshold: .75

review:
  alerts:
    labels:
      - person
      - bicycle
      - car
      - bird
      - cat
      - dog
      - bear
      - mouse

snapshots:
  enabled: true

go2rtc:
  streams:
#    FrontYard:
#      - rtsp://frontyard.camera.havenwood:554/media/video1
#      - ffmpeg:FrontYard#audio=aac
    FrontYardsub:
      - rtsp://frontyard.camera.havenwood:554/media/video2
      - ffmpeg:FrontYardsub#audio=aac
#    FrontDoor:
#      - rtsp://frontdoor.camera.havenwood:554/media/video1
#      - ffmpeg:FrontDoor#audio=aac
    FrontDoorsub:
      - rtsp://frontdoor.camera.havenwood:554/media/video2
      - ffmpeg:FrontDoorsub#audio=aac
#    Driveway1:
#      - rtsp://driveway1.camera.havenwood:554/media/video1
#      - ffmpeg:Driveway1#audio=aac
    Driveway1sub:
      - rtsp://driveway1.camera.havenwood:554/media/video2
      - ffmpeg:Driveway1sub#audio=aac
#    Driveway2:
#      - rtsp://driveway2.camera.havenwood:554/media/video1
#      - ffmpeg:Driveway2#audio=aac
    Driveway2sub:
      - rtsp://driveway2.camera.havenwood:554/media/video2
      - ffmpeg:Driveway2sub#audio=aac
#    Garage:
#      - rtsp://garage.camera.havenwood:554/media/video1
#      - ffmpeg:Garage#audio=aac
    Garagesub:
      - rtsp://garage.camera.havenwood:554/media/video2
      - ffmpeg:Garagesub#audio=aac
#    NorthYard:
#      - rtsp://northyard.camera.havenwood:554/media/video1
#      - ffmpeg:NorthYard#audio=aac
    NorthYardsub:
      - rtsp://northyard.camera.havenwood:554/media/video2
      - ffmpeg:NorthYardsub#audio=aac
#    BackYard1:
#      - rtsp://backyard1.camera.havenwood:554/media/video1
#      - ffmpeg:BackYard1#audio=aac
    BackYard1sub:
      - rtsp://backyard1.camera.havenwood:554/media/video2
      - ffmpeg:BackYard1sub#audio=aac
#    BackYard2:
#      - rtsp://backyard2.camera.havenwood:554/media/video1
#      - ffmpeg:BackYard2#audio=aac
    BackYard2sub:
      - rtsp://backyard2.camera.havenwood:554/media/video2
      - ffmpeg:BackYard2sub#audio=aac
#    NorthDeck:
#      - rtsp://northdeck.camera.havenwood:554/media/video1
#      - ffmpeg:NorthDeck#audio=aac
    NorthDecksub:
      - rtsp://northdeck.camera.havenwood:554/media/video2
      - ffmpeg:NorthDecksub#audio=aac
#    SouthDeck:
#      - rtsp://southdeck.camera.havenwood:554/media/video1
#      - ffmpeg:SouthDeck#audio=aac
    SouthDecksub:
      - rtsp://southdeck.camera.havenwood:554/media/video2
      - ffmpeg:SouthDecksub#audio=aac
#    SouthYard:
#      - rtsp://southyard.camera.havenwood:554/media/video1
#      - ffmpeg:SouthYard#audio=aac
    SouthYardsub:
      - rtsp://southyard.camera.havenwood:554/media/video2
      - ffmpeg:SouthYardsub#audio=aac

record:
  enabled: true
  retain:
    days: 30
    mode: all

cameras:
  FrontYard: # <------ Name the camera
    enabled: true
    ui:
      order: 1
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/FrontYard
#          input_args: preset-rtsp-restream
        - path: rtsp://frontyard.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontYardsub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 1,0.988,0.76,0.989,0.758,0.939,1,0.937
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  FrontDoor: # <------ Name the camera
    enabled: true
    ui:
      order: 2
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/FrontDoor
#          input_args: preset-rtsp-restream
        - path: rtsp://frontdoor.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoorsub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.252,1,0.008,0.996,0.006,0.946,0.251,0.944
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  Driveway1: # <------ Name the camera
    enabled: true
    ui:
      order: 3
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/Driveway1
#          input_args: preset-rtsp-restream
        - path: rtsp://driveway1.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway1sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.263,0.074,0.019,0.077,0.017,0.027,0.263,0.025
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  Driveway2: # <------ Name the camera
    enabled: true
    ui:
      order: 4
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/Driveway2
#          input_args: preset-rtsp-restream
        - path: rtsp://driveway2.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway2sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.261,0.066,0.021,0.067,0.019,0.017,0.261,0.015
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  Garage: # <------ Name the camera
    enabled: true
    ui:
      order: 5
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/Garage
#          input_args: preset-rtsp-restream
        - path: rtsp://garage.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garagesub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.251,0.996,0.011,0.997,0.009,0.947,0.251,0.945
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  NorthYard: # <------ Name the camera
    enabled: true
    ui:
      order: 6
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/NorthYard
#          input_args: preset-rtsp-restream
        - path: rtsp://northyard.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthYardsub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.251,0.989,0.011,0.99,0.009,0.94,0.251,0.938
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  BackYard1: # <------ Name the camera
    enabled: true
    ui:
      order: 7
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/BackYard1
#          input_args: preset-rtsp-restream
        - path: rtsp://backyard1.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard1sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.26,0.982,0.008,0.985,0.008,0.915,0.261,0.913
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  BackYard2: # <------ Name the camera
    enabled: true
    ui:
      order: 8
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/BackYard2
#          input_args: preset-rtsp-restream
        - path: rtsp://backyard2.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard2sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 1,0.996,0.76,0.999,0.76,0.947,1,0.945
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  NorthDeck: # <------ Name the camera
    enabled: true
    ui:
      order: 9
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/NorthDeck
#          input_args: preset-rtsp-restream
        - path: rtsp://northdeck.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthDecksub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.263,0.069,0.013,0.072,0.013,0.014,0.265,0.014
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    objects:
      filters:
        person: {}
  SouthDeck: # <------ Name the camera
    enabled: true
    ui:
      order: 10
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/SouthDeck
#          input_args: preset-rtsp-restream
        - path: rtsp://southdeck.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthDecksub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.263,0.07,0.02,0.072,0.018,0.018,0.262,0.016
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  SouthYard: # <------ Name the camera
    enabled: true
    ui:
      order: 11
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
#        - path: rtsp://127.0.0.1:8554/SouthYard
#          input_args: preset-rtsp-restream
        - path: rtsp://southyard.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthYardsub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    motion:
      mask: 0.258,0.067,0.018,0.07,0.018,0.018,0.258,0.016
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
version: 0.14
```

### Relevant Frigate log output

```shell
2025-01-16 15:31:54.124595765  [h264 @ 0x7f7c38015980] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:31:54.125262162  [h264 @ 0x7f7c38015980] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:03.514400173  [h264 @ 0x7f7c395bc700] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:03.515185815  [h264 @ 0x7f7c395bc700] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:13.439177348  [h264 @ 0x7f7c39564e80] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:13.440382541  [h264 @ 0x7f7c39564e80] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:23.881177526  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:23.881884263  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:33.934780231  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:33.936451090  [h264 @ 0x7f7c381fcc80] SEI type 5 size 2512 truncated at 1928
2025-01-16 15:32:37.090106396  [h264 @ 0x7f7c395cb9c0] SEI type 5 size 2512 truncated at 1936
2025-01-16 15:32:37.090820320  [h264 @ 0x7f7c395cb9c0] SEI type 5 size 2512 truncated at 1928
```

### Relevant go2rtc log output

```shell
2025-01-16 15:24:38.331227902  [INFO] Preparing new go2rtc config...
2025-01-16 15:24:38.832858670  [INFO] Starting go2rtc...
2025-01-16 15:24:39.052283193  15:24:39.052 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-16 15:24:39.052290148  15:24:39.052 INF config path=/dev/shm/go2rtc.yaml
2025-01-16 15:24:39.052857930  15:24:39.052 INF [api] listen addr=:1984
2025-01-16 15:24:39.052862671  15:24:39.052 INF [rtsp] listen addr=:8554
2025-01-16 15:24:39.053524024  15:24:39.053 INF [webrtc] listen addr=:8555/tcp
2025-01-16 15:24:48.327256745  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

HassOS

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
#    cap_add:
#      - CAP_PERFMON
    shm_size: "1000mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./config:/config
      - /mnt/frigate_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1184" alt="Screenshot 2025-01-16 at 3 56 04 PM" src="https://github.com/user-attachments/assets/b99aded5-b136-45da-bd23-b797818ab4fc" />
<img width="1188" alt="Screenshot 2025-01-16 at 3 56 18 PM" src="https://github.com/user-attachments/assets/9e771b0d-d385-4ccb-b1b7-d2397bfb0913" />
