### DISCUSSION TITLE
Coral is very slow (130ms)

### DISCUSSION THREAD

**Discussion by SebOM** [blakeblackshear/frigate#16020] [Detector Support]
### Describe the problem you are having

hi,

i have a problem my "Coral is very slow (130ms)
I don't understand why

root@frigate:~# lsusb
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 005: ID 18d1:9302 Google Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

Please Help me ;-)

### Version

 0.14.1-

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: jeedom
  password: xxxxxxxxxxxxxxxxxxxxxx
  host: 192.168.1.2
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
    
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    Salon: 
      - rtsp://xxxxx:xxxx@192.168.1.51/live
      - ffmpeg:rtsp_entree#audio=opus#audio=aac
    JardinHD:
      - rtsp://xxxx:xxxxx@192.168.1.50:554/live/stream1
      - ffmpeg:rtsp_entree#audio=opus#audio=aac

timestamp_style:
  #Yes, the legacy software is capable of showing the timestamp, but i like all the configurations to be the same place
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 3

snapshots:
  enabled: true

cameras:
  Salon:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Salon
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 3
        post_capture: 3
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.7
          threshold: 0.75
    motion:
      threshold: 10
      contour_area: 10
      improve_contrast: 'true'

  Jardin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/JardinHD
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 3
        post_capture: 3
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
      mask: 0.214,0.178,0.213,0.098,0.188,0,0.215,0,0.248,0.107,0.248,0.197
      filters:
        person:
          min_score: 0.7
          threshold: 0.75
    motion:
      threshold: 10
      contour_area: 10
      improve_contrast: 'true'
      mask: 
        0.688,0.08,1,0.233,1,0,0.342,0,0.177,0.047,0.327,0.021,0.346,0,0.34,0,0,0,0,0.049,0,0.111,0.309,0,0.192,0,0.212,0.036,0.34,0.009
model:
  path: /cpu_model.tflite
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
LXC CONTAINER

arch: amd64
cores: 4
features: nesting=1
hostname: frigate
memory: 7800
nameserver: 192.168.1.1
net0: name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:5E:E8:CA,ip=192.168.1.5/24,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-101-disk-0,size=500G
swap: 7800
tags: community-script;nvr
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.cgroup2.devices.allow: c 180:* rwm
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: a
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.cap.drop:
lxc.mount.auto: cgroup:rw
lxc.mount.entry: /dev/bus/usb/003 dev/bus/usb/003 none bind,optional,create=dir 0, 0
```

### Relevant Frigate log output

```shell
NO ERROR

info
2025-01-17 11:01:44
startup
Preparing Frigate...
info
2025-01-17 11:01:44
startup
Starting Frigate...
info
2025-01-17 11:01:45
frigate.app
Starting Frigate (0.14.1-)
info
2025-01-17 11:01:45
frigate.util.config
Checking if frigate config needs migration...
info
2025-01-17 11:01:45
frigate.util.config
frigate config does not need migration...
info
2025-01-17 11:01:47
peewee_migrate.logs
Starting migrations
info
2025-01-17 11:01:47
peewee_migrate.logs
There is nothing to migrate
info
2025-01-17 11:01:47
frigate.app
Recording process started: 2155
info
2025-01-17 11:01:47
frigate.app
Recording process started: 2161
info
2025-01-17 11:01:47
frigate.app
go2rtc process pid: 126
info
2025-01-17 11:01:47
detector.coral
Starting detection process: 2184
info
2025-01-17 11:01:47
frigate.app
Output process started: 2189
info
2025-01-17 11:01:47
frigate.detectors.plugins.edgetpu_tfl
Attempting to load TPU as usb
info
2025-01-17 11:01:48
frigate.app
Camera processor started for Salon: 2209
info
2025-01-17 11:01:48
frigate.app
Camera processor started for Jardin: 2216
info
2025-01-17 11:01:48
frigate.app
Capture process started for Salon: 2222
info
2025-01-17 11:01:48
frigate.app
Capture process started for Jardin: 2228
info
2025-01-17 11:01:50
frigate.detectors.plugins.edgetpu_tfl
TPU found
```

### Install method

Proxmox via TTeck Script

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![metric](https://github.com/user-attachments/assets/64bee616-0966-4611-a705-72db43cd48e7)
