### DISCUSSION TITLE
[Support]: Double Take is not adding sub_labels to Frigate+

### DISCUSSION THREAD

**Discussion by MarkEhmke** [blakeblackshear/frigate#16021] [General Support]
### Describe the problem you are having

I am getting matches via mqtt in double take but it doesn't update the sub_label in frigate/events, nor does it put a tick in the frigate ui
![DT](https://github.com/user-attachments/assets/9570b0d6-d0c6-4d4a-971d-e34ebc269045)
![f+](https://github.com/user-attachments/assets/4c6429f1-9787-4e94-bb12-f1d6215187a0)

### Version

0.14.0-da913d8

### What browser(s) are you using?

Firefox 134.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx.xxx.xxx.xxx
  port: 1883

model:
  path: plus://xxxxxxxxxxxxxxxxxxxx

objects: # Object to detect - https://docs.frigate.video/configuration/objects
  track:
    - person
    - face
    - car
    - license_plate
  filters:
    face:
      min_score: .2
    license_plate:
      min_score: .3
    person:
      min_score: .6
      threshold: .85
    car:
      min_score: .3
      threshold: .7

record: # how long to record before and after motion
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      mode: active_objects
      default: 7
    pre_capture: 3
    post_capture: 10
  preview:
    quality: low

detect:
  enabled: true
  min_initialized: 3
  max_disappeared: 5
  stationary:
    max_frames:
      objects:
        car: 5

motion:
  threshold: 70
  contour_area: 70

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    DORICam:
      - rtsp://xxxx:xxxx@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1&subtype=2#timeout=60
    Side:
      - rtsp://xxxx:xxxx@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1&subtype=1#timeout=30
    Front:
      - onvif://xxxx:xxxx@xxx.xxx.xxx.xxx:80?subtype=Profile_3

  webrtc:
    candidates:
      - xxx.xxx.xxx.xxx:8555
      - stun:8555

cameras:
  Front:
    enabled: true

    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    onvif:
      host: xxx.xxx.xxx.xxx
      port: 80
      user: xxxx
      password: xxxx
      autotracking:
        enabled: true
        calibrate_on_startup: false
        zooming: absolute
        track:
          - person
          - car
        return_preset: home
        required_zones:
          - front-area
        timeout: 10

        movement_weights: 0.0, 1.0, 0.32021427154541016, 0.6138117805563552, 0.3951447439887595
    detect:
      enabled: true # Detection is enabled
      fps: 6

    zones:
      front-area:
        coordinates: 
          0.049,0.355,0.106,0.38,0.072,0.456,0.103,0.485,1,0.511,0.996,0.992,0.002,0.997,0,0.438
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - person
    record: # what you want Frigate to record
      enabled: true
      retain:
        mode: active_objects
        days: 10

    snapshots:
      enabled: true
      required_zones:
        - front-area
      retain:
        mode: active_objects
        default: 10

    review:
      alerts:
        required_zones: front-area
      detections:
        required_zones: front-area
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      required_zones:
        - front-area

    motion:
      mask: 
        0,0,0,0.348,0,0.431,0.05,0.352,0.11,0.381,0.075,0.453,0.125,0.498,1,0.51,1,0,0.631,0,0.595,0
      threshold: 79
      contour_area: 99
      improve_contrast: false

  DORICam:
    enabled: true # <---- Manual Switch 
    detect:
      fps: 15

    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/DORICam
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi

    zones:
      gate:
        coordinates: 0.23,0.137,0.246,0,0.537,0,0.617,0.14
        loitering_time: 0
        objects:
          - car
          - person
        inertia: 1
      driveway:
        coordinates: 0.231,0.137,0.622,0.144,0.68,0.262,0.187,0.264,0.205,0.139,0.229,0.138
        inertia: 1
        loitering_time: 0
        objects:
          - car
          - person
      drive:
        coordinates: 
          0.159,0.604,0.145,0.702,0.778,0.702,0.781,0.6,0.86,0.597,0.682,0.268,0.184,0.264,0.129,0.577,0.098,0.589
        inertia: 1
        loitering_time: 0
        objects:
          - car
          - person
          - face
      plate:
        coordinates: 0.24,0.272,0.63,0.272,0.688,0.396,0.218,0.394
        inertia: 1
        loitering_time: 0
        objects:
          - car
          - license_plate
          - person
      corner:
        coordinates: 
          0.778,0.6,0.78,0.702,0.718,0.703,0.733,1,1,0.99,1,0.667,0.97,0.645,0.913,0.626,0.867,0.596
        inertia: 1
        loitering_time: 0
        objects:
          - car
          - license_plate
          - person
          - face
      entrance:
        coordinates: 0.002,0.63,0.093,0.598,0.158,0.603,0.144,0.702,0.716,0.705,0.733,1,0,1
        loitering_time: 0
        objects:
          - car
          - license_plate
          - person
        inertia: 1

    record: # what you want Frigate to record
      enabled: true
      retain:
        mode: active_objects
        days: 10

    snapshots:
      enabled: true
      required_zones:
        - drive
        - entrance
        - corner
      retain:
        mode: active_objects
        default: 10

    review:
      detections:
        required_zones:
          - gate
          - driveway
          - drive
          - plate
          - entrance
          - corner
      alerts:
        required_zones:
          - corner
          - plate
          - entrance
          - drive
          - driveway
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

      required_zones:
        - plates
        - corner
        - entrance

    motion:
      mask:
        - 0.867,0.602,1,0.656,1,0.157,1,0,0.762,0,0.542,0
        - 0.13,0.573,0,0.625,0,0,0.246,0,0.229,0.137,0.204,0.137
      threshold: 79
      contour_area: 99
      lightning_threshold: 0.6
      improve_contrast: false

  Side:
    enabled: true # <---- Manual Switch 
    detect:
      fps: 5

    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi

    record: # what you want Frigate to record
      enabled: true
      retain:
        mode: active_objects
        days: 7

    snapshots:
      enabled: true
      retain:
        mode: active_objects
        default: 7

    review:
      detections:
        required_zones:
          - sidewalk
      alerts:
        required_zones:
          - sidewalk

    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      required_zones:
        - sidewalk

    motion:
      threshold: 79
      contour_area: 99
      lightning_threshold: 0.6
      improve_contrast: true
      mask: 
        0,0,0,1,0.097,1,0.171,0.726,0.186,0.803,0.303,0.69,0.342,0.49,0.36,0.491,0.361,0.424,0.381,0.375,0.391,0.405,0.4,0.145,0.562,0.366,0.557,0.443,0.71,0.741,0.685,0.831,0.743,1,1,1,0.995,0.003

    zones:
      sidewalk:
        coordinates: 
          0.383,0.495,0.402,0.146,0.56,0.37,0.554,0.444,0.706,0.741,0.683,0.829,0.744,1,0.1,1,0.17,0.735,0.185,0.811,0.311,0.688,0.456,0.713,0.449,0.508
        loitering_time: 0
        objects: person
        inertia: 3

    objects:
      mask: 
        0.327,0.566,0.343,0.492,0.363,0.493,0.364,0.42,0.38,0.397,0.383,0.433,0.382,0.503,0.449,0.515,0.453,0.703,0.307,0.682
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuActivity
    cameras: birdseye
  Cameras:
    order: 2
    icon: LuEye
    cameras:
      - birdseye
      - DORICam
      - Front
      - Side
```

### Relevant Frigate log output

```shell
2025-01-16 13:28:30.957101201  [INFO] Preparing Frigate...
2025-01-16 13:28:30.992458212  [INFO] Starting Frigate...
2025-01-16 13:28:32.833355016  [2025-01-16 13:28:32] frigate.app                    INFO    : Starting Frigate (0.14.0-da913d8)
2025-01-16 13:28:32.833667332  [2025-01-16 13:28:32] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-16 13:28:32.894179345  [2025-01-16 13:28:32] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-16 13:28:33.103104711  [2025-01-16 13:28:33] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2025-01-16 13:28:42.362862746  [2025-01-16 13:28:42] frigate.config                 WARNING : DORICam detect fps is set to 15. This does NOT need to match your camera's frame rate. High values could lead to reduced performance. Recommended value is 5.
2025-01-16 13:28:47.173498630  [2025-01-16 13:28:47] peewee_migrate.logs            INFO    : Starting migrations
2025-01-16 13:28:47.173788071  [2025-01-16 13:28:47] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-16 13:28:47.410490748  [2025-01-16 13:28:47] frigate.app                    INFO    : Recording process started: 383
2025-01-16 13:28:47.410989891  [2025-01-16 13:28:47] frigate.app                    INFO    : Recording process started: 387
2025-01-16 13:28:47.411278722  [2025-01-16 13:28:47] frigate.app                    INFO    : go2rtc process pid: 107
2025-01-16 13:28:47.438594834  [2025-01-16 13:28:47] detector.coral                 INFO    : Starting detection process: 412
2025-01-16 13:28:47.447907316  [2025-01-16 13:28:47] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-01-16 13:28:47.449283597  [2025-01-16 13:28:47] frigate.app                    INFO    : Output process started: 414
2025-01-16 13:28:47.985415816  [2025-01-16 13:28:47] frigate.app                    INFO    : Camera processor started for Front: 454
2025-01-16 13:28:47.991789725  [2025-01-16 13:28:47] frigate.app                    INFO    : Camera processor started for DORICam: 456
2025-01-16 13:28:47.999127734  [2025-01-16 13:28:47] frigate.app                    INFO    : Camera processor started for Side: 462
2025-01-16 13:28:48.016092864  [2025-01-16 13:28:48] frigate.app                    INFO    : Capture process started for Front: 467
2025-01-16 13:28:48.026441435  [2025-01-16 13:28:48] frigate.app                    INFO    : Capture process started for DORICam: 476
2025-01-16 13:28:48.029895399  [2025-01-16 13:28:48] frigate.app                    INFO    : Capture process started for Side: 485
2025-01-16 13:28:50.277863767  [2025-01-16 13:28:50] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-01-16 15:47:48.033538841  [2025-01-16 15:47:48] frigate.comms.dispatcher       INFO    : Turning off detection for Front
2025-01-16 15:47:48.083352909  [2025-01-16 15:47:48] frigate.comms.dispatcher       INFO    : Turning off ptz autotracker for Front
2025-01-17 06:40:33.423701569  [2025-01-17 06:40:33] frigate.api.media              ERROR   : [concat @ 0x5db3641a5a40] No files to concat
2025-01-17 06:40:33.423704585  /dev/stdin: Invalid data found when processing input
2025-01-17 09:32:42.516686  2025-01-17 06:40:33.423705512
2025-01-17 06:40:35.979660276  [2025-01-17 06:40:35] frigate.api.media              ERROR   : [concat @ 0x5ef9ef1bea40] No files to concat
2025-01-17 06:40:35.979663636  /dev/stdin: Invalid data found when processing input
2025-01-17 09:32:42.516707  2025-01-17 06:40:35.979664479
2025-01-17 06:40:39.203666126  [2025-01-17 06:40:39] frigate.api.media              ERROR   : [concat @ 0x5b4b3deefa40] No files to concat
2025-01-17 06:40:39.203669180  /dev/stdin: Invalid data found when processing input
2025-01-17 09:32:42.516711  2025-01-17 06:40:39.203670052
```

### Relevant go2rtc log output

```shell
2025-01-16 13:28:30.958247017  [INFO] Preparing new go2rtc config...
2025-01-16 13:28:31.498482972  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-01-16 13:28:31.543441984  [INFO] Starting go2rtc...
2025-01-16 13:28:31.644589027  13:28:31.644 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-16 13:28:31.644788211  13:28:31.644 INF config path=/dev/shm/go2rtc.yaml
2025-01-16 13:28:31.645258597  13:28:31.645 INF [api] listen addr=:1984
2025-01-16 13:28:31.645627534  13:28:31.645 INF [rtsp] listen addr=:8554
2025-01-16 13:28:31.646062727  13:28:31.646 INF [webrtc] listen addr=:8555
2025-01-16 13:28:40.957954659  [INFO] Starting go2rtc healthcheck service...
2025-01-16 18:17:02.920528288  18:17:02.920 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225 > error="read tcp 172.18.0.2:8554->162.142.125.222:35002: read: connection reset by peer"
```

### FFprobe output from your camera

```shell
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain:tVAEntrypointEncSliceLPnVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileHEVCMain10:tVAEntrypointEncSliceLPnVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile0:tVAEntrypointEncSliceLPnVAProfileVP9Profile1:tVAEntrypointVLDnVAProfileVP9Profile1:tVAEntrypointEncSliceLPnVAProfileVP9Profile2:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointEncSliceLPnVAProfileVP9Profile3:tVAEntrypointVLDnVAProfileVP9Profile3:tVAEntrypointEncSliceLPnVAProfileHEVCMain12:tVAEntrypointVLDnVAProfileHEVCMain12:tVAEntrypointEncSlicenVAProfileHEVCMain422_10:tVAEntrypointVLDnVAProfileHEVCMain422_10:tVAEntrypointEncSlicenVAProfileHEVCMain422_12:tVAEntrypointVLDnVAProfileHEVCMain422_12:tVAEntrypointEncSlicenVAProfileHEVCMain444:tVAEntrypointVLDnVAProfileHEVCMain444:tVAEntrypointEncSliceLPnVAProfileHEVCMain444_10:tVAEntrypointVLDnVAProfileHEVCMain444_10:tVAEntrypointEncSliceLPnVAProfileHEVCMain444_12:tVAEntrypointVLDnVAProfileHEVCSccMain:tVAEntrypointVLDnVAProfileHEVCSccMain:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain10:tVAEntrypointVLDnVAProfileHEVCSccMain10:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain444:tVAEntrypointVLDnVAProfileHEVCSccMain444:tVAEntrypointEncSliceLPnVAProfileAV1Profile0:tVAEntrypointVLDnVAProfileHEVCSccMain444_10:tVAEntrypointVLDnVAProfileHEVCSccMain444_10:tVAEntrypointEncSliceLP"}
```

### Frigate stats

```json
{"cameras":{"DORICam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.3,"capture_pid":476,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":486,"pid":456,"process_fps":15.3,"skipped_fps":0.0},"Front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.0,"capture_pid":467,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":484,"pid":454,"process_fps":6.0,"skipped_fps":0.0},"Side":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":485,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":496,"pid":462,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"1.1","cpu_average":"1","mem":"0.1"},"125":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"126":{"cmdline":"python3 -u -m frigate","cpu":"8.0","cpu_average":"2","mem":"1.3"},"133":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144065":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144166":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"159":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"161":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"162":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"303":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"3124":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"330":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"34":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"383":{"cmdline":"frigate.recording_manager","cpu":"0.4","cpu_average":"0","mem":"0.5"},"387":{"cmdline":"frigate.review_segment_manager","cpu":"0.3","cpu_average":"0","mem":"0.5"},"411":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"412":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"0.5"},"414":{"cmdline":"frigate.output       ","cpu":"1.2","cpu_average":"1","mem":"0.5"},"421":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"426":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"431":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -threads 1 -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"436":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"454":{"cmdline":"frigate.process:Front","cpu":"0.5","cpu_average":"0","mem":"0.6"},"456":{"cmdline":"frigate.process:DORICam","cpu":"1.8","cpu_average":"1","mem":"0.6"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"462":{"cmdline":"frigate.process:Side ","cpu":"0.8","cpu_average":"0","mem":"0.5"},"467":{"cmdline":"frigate.capture:Front","cpu":"1.0","cpu_average":"1","mem":"0.5"},"476":{"cmdline":"frigate.capture:DORICam","cpu":"2.5","cpu_average":"2","mem":"0.5"},"484":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Front@%Y%m%d%H%M%S%z.mp4 -r 6 -vf fps=6,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.2"},"485":{"cmdline":"frigate.capture:Side ","cpu":"0.4","cpu_average":"0","mem":"0.5"},"486":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/DORICam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/DORICam@%Y%m%d%H%M%S%z.mp4 -r 15 -vf fps=15,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.5","cpu_average":"3","mem":"0.2"},"496":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.0-da913d8 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/Side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Side@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.1"},"84":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"9.0","mem":"39.2"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.83,"pid":412}},"gpu_usages":{"intel-vaapi":{"gpu":"0.66%","mem":"-%"}},"processes":{"go2rtc":{"pid":107},"logger":{"pid":330},"recording":{"pid":383},"review_segment":{"pid":387}},"service":{"last_updated":1737108213,"latest_version":"unknown","storage":{"/dev/shm":{"free":64.0,"mount_type":"tmpfs","total":72.0,"used":8.0},"/media/frigate/clips":{"free":1762455.0,"mount_type":"ext4","total":1885750.1,"used":27432.7},"/media/frigate/recordings":{"free":1762455.0,"mount_type":"ext4","total":1885750.1,"used":27432.7},"/tmp/cache":{"free":952.2,"mount_type":"tmpfs","total":953.7,"used":1.4}},"temperatures":{},"uptime":74085,"version":"0.14.0-da913d8"}}
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
secrets:
PLUS_API_KEY:
file: frigateplus_key.txt
services:
frigate:
container_name: frigate
privileged: true # this may not be necessary for all setups
restart: unless-stopped
image: ghcr.io/blakeblackshear/frigate:0.14.0
shm_size: "72mb"
cap_add:
-	CAP JPERFMON
devices:
-	/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
-	/dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
volumes:
-	/etc/localtime:/etc/localtime:ro
-	/opt/frigate/config:/config
-	/opt/frigate/storage:/media/frigate
-	type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
target: /tmp/cache
tmpfs:
size: 1000000000
ports:
-	"8971:8971"
-	"5000:5000"
-	"5001:5001"
-	"8554:8554" # RTSP feeds
-	"8555:8555/tcp" # WebRTC over tcp
-	"8555:8555/udp" # WebRTC over udp
environment:
FRlGATE_RTSP_PASSWORD: "xxxxxxxx"
secrets:
-	PLUS API KEY
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW5241E-Z12E

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/df5275b6-948c-463f-ab8b-01dc2ca3eb8f)

### Any other information that may be helpful

![mqtt](https://github.com/user-attachments/assets/05747ede-ddd3-41d1-83f2-7d92a1b378de)
