### DISCUSSION TITLE
[Support]: Frigate crashes and uses 100% when a camera feed goes offline.

### DISCUSSION THREAD

**Discussion by jasonwragg** [blakeblackshear/frigate#16032] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Some of my cameras reboot randomly or go offline, when this happens frigate stops responding and uses 100% CPU.

### Steps to reproduce

1. Camera reboots or the feed crashes
2. Frigate starts consuming 100% CPU

### Version

0.15.0-173b7aa

### In which browser(s) are you experiencing the issue with?

All

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.32
  topic_prefix: frigate
  user: mqtt
  password: XXXXX
go2rtc:
  log:
    format: text
    exec: error
  streams:
    doorbell:
      - ffmpeg:http://192.168.1.15/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXXX#video=copy#audio=copy#audio=opus
      - rtsp://admin:XXXX@192.168.1.15:554/h264Preview_01_main
    doorbell_sub:
      - rtsp://admin:XXXX@192.168.1.15:554/h264Preview_01_sub
      - ffmpeg:doorbell_sub#audio=opus
    ffmpeg:
      bin: ffmpeg
      volume: -af "volume=30dB"
    front_garden:
      - ffmpeg:http://192.168.1.86/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXX#video=copy#audio=copy#audio=opus
    front_garden_sub:
      - ffmpeg:http://192.168.1.86/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXX
    living_room_sofa:
      - ffmpeg:rtsp://frigate:XXXX@192.168.1.85:554/h264Preview_01_main#video=copy#audio=copy#audio=aac#hardware
    living_room_sofa_sub:
      - rtsp://frigate:XXXX@192.168.1.85:554/h264Preview_01_sub
    driveway:
      - ffmpeg:http://192.168.1.84/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXX#video=copy#audio=copy#audio=opus
    driveway_sub:
      - ffmpeg:http://192.168.1.84/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXX
    back_garden_utility:
      - ffmpeg:http://192.168.1.87/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=XXXX#video=copy#audio=copy#audio=opus
    back_garden_utility_sub:
      - ffmpeg:http://192.168.1.87/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=XXXX
    back_passage:
      - ffmpeg:http://192.168.1.80/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=XXXX#video=copy#audio=copy#audio=opus
    back_passage_sub:
      - ffmpeg:http://192.168.1.80/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=XXXX
    back_garden:
      - rtsp://xxx=@192.168.1.91:554/live/ch0
    back_garden_detect:
      - rtsp://xxx=@192.168.1.91:554/live/ch1
    landing:
      - rtsp://xxx@192.168.1.94:554/live/ch0
    landing_detect:
      - rtsp://xxx@192.168.1.94:554/live/ch1
    living_room:
      - rtsp://xxx@192.168.1.93:554/live/ch0
    living_room_detect:
      - rtsp://xxx@192.168.1.93:554/live/ch1
    kitchen:
      - rtsp://xxx@192.168.1.90:554/live/ch0
    kitchen_detect:
      - rtsp://xxx@192.168.1.90:554/live/ch1
    utility:
      - rtsp://xxx@192.168.1.89:554/live/ch0
    utility_detect:
      - rtsp://xxx@192.168.1.89:554/live/ch1
    study:
      - ffmpeg:http://192.168.1.81/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXX#video=copy#audio=copy#audio=opus
    study_sub:
      - ffmpeg:http://192.168.1.81/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXX
    dog_camera:
      - rtsp://admin:XXXX@192.168.1.92:554/live/ch0
  webrtc:
    candidates:
      - 192.168.1.32:8555
      - stun:8555
cameras:
  doorbell:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      width: 640
      height: 480
      fps: 4
    live:
      stream_name: doorbell_sub
    motion:
      mask:
        - 0.569,0.004,0.569,0.057,0.986,0.061,0.986,0.003
        - 0.841,0.439,0.384,0.449,0.315,0.274,0.496,0.08,0.583,0.098,0.61,0.256,0.817,0.276,0.998,0.274,0.997,0.403,0.866,0.422
        - 0.214,0.467,0.214,0.254,0,0.126,-0.001,0.459
        - 0.021,0.14,0.138,0.002,0,0,0,0.126
        - 1,0.149,0.999,0.002,0.898,-0.001,0.953,0.076
  dog_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/dog_camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask: 0.637,0.012,0.638,0.064,0.996,0.066,0.996,0.013
  living_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 768
      height: 432
      fps: 5
    motion:
      mask: 0.683,0,0.684,0.052,1,0.056,0.996,0.001
  landing:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/landing
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/landing_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      mask: 0.684,0,0.683,0.055,1,0.053,0.997,0
    zones:
      Landing_Only:
        coordinates: 
          0.772,0.368,0.801,0.049,0.744,0.043,0.739,0.001,0.002,0.001,0.004,0.996,0.755,1,0.813,0.835,0.738,0.735,0.762,0.611,0.67,0.624,0.784,0.413
        loitering_time: 0
        objects: person
  kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 768
      height: 432
      fps: 5
    motion:
      mask:
        - 0.683,0,0.681,0.053,1,0.056,0.998,0.001
        - 0.165,0.15,0.17,0.172,0.202,0.147,0.195,0.117
    audio:
      enabled: true
      listen:
        - bark
        - beep
        - fire_alarm
        - scream
        - yell
        - dog
        - howl
        - growling
        - siren
  utility:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/utility
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/utility_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
        - 0.727,0,0.73,0.053,0.974,0.046,0.974,0.001
        - 0.085,0,0.107,0.127,0,0.301,-0.001,-0.001
  back_garden:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 768
      height: 432
      fps: 5
    motion:
      mask:
        - 0.681,0,0.682,0.055,1,0.055,0.997,0.006
        - 0.275,0.149,0.311,0.112,0.41,0.408,0.342,0.532
        - 0.997,0.759,0.963,0.728,0.97,0.653,0.943,0.62,0.884,0.694,0.871,0.635,0.925,0.537,0.902,0.472,0.791,0.456,0.77,0.326,0.754,0.247,0.839,0.059,0.998,0.058
    objects:
      filters:
        person:
          mask: 0.211,0.147,0.397,0.016,0.468,0.349,0.31,0.568
  front_garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_garden_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - car
        - person
        - cat
        - dog
      filters:
        car:
          mask: 0.004,0.005,0.007,0.209,0.384,0.129,0.386,0
    motion:
      mask: 0.58,0.013,0.581,0.05,0.99,0.052,0.989,0.016
  driveway:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - car
        - person
        - cat
        - dog
      filters:
        car:
          mask: 
            0.878,0.461,0.999,0.689,0.919,0.778,0.851,0.66,0.868,0.615,0.852,0.57,0.856,0.479
    motion:
      mask:
        - 0.575,0.012,0.576,0.057,1,0.061,1,0.01
        - 0.593,0.055,0.659,0.148,0.65,0.382,0.51,0.304,0.474,0.209,0.247,0.02,0.245,0.001,0.54,0
        - 0.694,0.538,0.691,0.645,0.753,0.811,0.847,0.686,0.873,0.605,0.754,0.484
  back_passage:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_passage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_passage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 480
      fps: 4
    motion:
      mask: 0.576,0.013,0.575,0.053,1,0.055,1,0.016
  back_garden_utility:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden_utility
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_utility_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 480
      fps: 4
    motion:
      mask: 0.58,0.008,0.581,0.056,1,0.056,0.997,0.006
  living_room_sofa:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_sofa
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_sofa_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
        - 0.7,0.02,0.699,0.064,0.989,0.064,0.99,0.024
        - 0.169,0,0.177,0.17,0.417,0.042,0.417,0
        - 0.039,0.431,0.172,0.323,0.15,0.199,0,0.298
    objects:
      filters:
        person:
          mask:
            - 0.792,0,0.791,0.067,0.882,0.077,0.883,0
            - 0.172,0,0.176,0.169,0.418,0.042,0.418,0
  study:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/study
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/study_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 480
      fps: 4
    motion:
      mask:
        - 0.58,0.014,0.578,0.057,0.992,0.053,0.995,0.009
        - 0.703,0.945,0.702,0.988,0.992,0.987,0.991,0.943
    zones: {}
database:
  path: /config/frigate.db

objects:
  track:
    - person
    - cat
    - dog

record:
  enabled: true
  retain:
    days: 60
    mode: all

snapshots:
  enabled: true

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  #width: 1920
  # Optional: Height of the output resolution (default: shown below)
  #height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

semantic_search:
  enabled: true
  reindex: false
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
logger:
  default: warning
# Optional: Telemetry configuration
telemetry:
  # Optional: Enabled network interfaces for bandwidth stats monitoring (default: empty list, let nethogs search all)
  # Optional: Configure system stats
  stats:
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: true
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
version: 0.15-1
ffmpeg:
  global_args: -hide_banner -loglevel debug
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate14
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta5
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    shm_size: "2048mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your h>
      - /dev/dri/card0
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/config/
      - /srv/CCTV_Storage/frigate:/media/frigate
      - ./logs:/dev/shm/logs
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1G
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"
    deploy:
      resources:
        limits:
          cpus: "7"
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
      PLUS_API_KEY: xxx
```

### Relevant Frigate log output

```shell
Unresponsive so cannot get logs before rebooting
```

### Relevant go2rtc log output

```shell
Unresponsive so cannot get logs before rebooting
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Wansview & Reolink

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-01-18 at 15 31 06](https://github.com/user-attachments/assets/005bceeb-c12b-4d72-82e2-86d48251ac64)
