### DISCUSSION TITLE
[Support]: Events/Detections not happening for audio

### DISCUSSION THREAD

**Discussion by dutchstiphout** [blakeblackshear/frigate#16044] [General Support]
### Describe the problem you are having

I can see that audio is detected in the little green icons on the review page for detected object events, but if I speak (off-camera) there is no detected event. I'm new to frigate as of today, but I've spent hours scouring the web and trying different things in the config file and no luck. What am I missing?

Note that I am using H265. I've seen that can be problematic, but when I switched the camera over to H264, I was no longer able to see anything on the review page anymore; it showed 1 frame of video and went blank. When I switched back to H265, it started working again, and all the H264 footage was unviewable. (I did try a bunch of H264 settings, and I did restart frigate between each change.)

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Chrome

### Frigate config file

```yaml
#point to your host
mqtt:
  enabled: false
#  host: 10.0.1.30
#  user: dutch
#  password: (secret)

detectors:
  coral1:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

birdseye:
  width: 1280
  height: 720
  mode: continuous

go2rtc:
  streams:
    LR_amcrest:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.81:554/cam/realmonitor?channel=1&subtype=0
      #- ffmpeg:LR_amcrest#audio=aac

# Default objects to track. Can be overridden at camera level
objects:
  track:
    - person
    - cat
  filters:
    person:
      threshold: 0.8
    cat:
      threshold: 0.7

# Optional: Audio Events Configuration. This runs on CPU, not TPU
audio:
  # Optional: Enable audio events (default: shown below)
  enabled: true
  listen:
    - bark
    - cat
    - fire_alarm
    - scream
    - speech
    - yell

review:
  alerts:
    # Optional: labels that qualify as an alert
    labels:
      - person
      - cat
      - bark
      - cat
      - fire_alarm
      - scream
      - speech
      - yell
  detections:
    labels:
      - person
      - cat
      - bark
      - cat
      - fire_alarm
      - scream
      - speech
      - yell

motion:
  enabled: true
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30



record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 1440
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 1
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    retain:
      default: 3000 # About 8 years
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      mode: motion

snapshots:
  enabled: true
  timestamp: true
  crop: true
  retain:
    default: 3000


# Optional: set environment variables
#environment_vars:
  # I have these set in frigate's Docker stack compose file.
  #EXAMPLE_VAR: value

#-------------------------------------------------------------------------------------------------
cameras:
  LR_amcrest:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: true

    # Required: ffmpeg settings for the camera
    ffmpeg:
      hwaccel_args: auto
      output_args:
        # modification turns on audio recording (xxx using aac encoding xxx I changed to copy since cam outputs aac)
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a copy
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.81:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        # by default, the detect stream is used for the live view in the browser
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.81:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

    webui_url: https://lr-amcrest.stiphout.net/#/index/Preview/

    # Optional: Adjust sort order of cameras in the UI. Larger numbers come later
    ui:
    # By default the cameras are sorted alphabetically.
      order: 0
    # Optional: Whether or not to show the camera in the Frigate UI
      dashboard: true
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      # Optional: Set the name of the stream configured in go2rtc
      # that should be used for live view in frigate WebUI. (default: name of camera)
      # NOTE: In most cases this should be set at the camera level only.
      #stream_name: LR_amcrest
      height: 2160
      quality: 8

    # Optional: Audio Events Configuration. This runs on CPU, not TPU
    audio:
      # Optional: Enable audio events (default: shown below)
      enabled: true
      # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
      max_not_heard: 30
      # Optional: Configure the min rms volume required to run audio detection (default: shown below)
      # As a rule of thumb:
      #  - 200 - high sensitivity
      #  - 500 - medium sensitivity
      #  - 1000 - low sensitivity
      min_volume: 200
      # Optional: Types of audio to listen for (default: shown below)
      listen:
        - bark
        - cat
        - fire_alarm
        - scream
        - speech
        - yell
      # Optional: Filters to configure detection.
      filters:
        # Label that matches label in listen config.
        speech:
          # Minimum score that triggers an audio event (default: shown below)
          threshold: 0.8
    motion:
      enabled: true
      # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
      #           needs to recalibrate. (default: shown below)
      # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
      # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
      # a doorbell camera.
      lightning_threshold: 0.8
      # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
      mqtt_off_delay: 30
      mask: 0.685,0.04,0.962,0.036,0.964,0.087,0.686,0.087
version: 0.14
```

### Relevant Frigate log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2025-01-18 19:45:23.336391220  [INFO] Preparing Frigate...
2025-01-18 19:45:23.340601984  [INFO] Starting NGINX...
2025-01-18 19:45:23.344872814  [INFO] Preparing new go2rtc config...
2025-01-18 19:45:23.373918828  [INFO] Starting Frigate...
2025-01-18 19:45:24.348145127  [INFO] Starting go2rtc...
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
2025-01-18 19:45:24.567080971  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
2025-01-18 19:45:24.606927033  19:45:24.606 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-18 19:45:24.606938586  19:45:24.606 INF config path=/dev/shm/go2rtc.yaml
2025-01-18 19:45:24.607522245  19:45:24.607 INF [rtsp] listen addr=:8554
2025-01-18 19:45:24.607635962  19:45:24.607 INF [api] listen addr=:1984
2025-01-18 19:45:24.608521364  19:45:24.608 INF [webrtc] listen addr=:8555/tcp
2025-01-18 19:45:25.861696837  [2025-01-18 19:45:25] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2025-01-18 19:45:25.861965999  [2025-01-18 19:45:25] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-18 19:45:25.905147773  [2025-01-18 19:45:25] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-18 19:45:27.507668560  [2025-01-18 19:45:27] frigate.util.services          INFO    : Automatically detected nvidia hwaccel for video decoding
2025-01-18 19:45:27.598024254  [2025-01-18 19:45:27] peewee_migrate.logs            INFO    : Starting migrations
2025-01-18 19:45:27.600226599  [2025-01-18 19:45:27] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-18 19:45:27.639481420  [2025-01-18 19:45:27] frigate.app                    INFO    : Recording process started: 412
2025-01-18 19:45:27.643909180  [2025-01-18 19:45:27] frigate.app                    INFO    : Recording process started: 413
2025-01-18 19:45:27.653379644  [2025-01-18 19:45:27] frigate.app                    INFO    : go2rtc process pid: 98
2025-01-18 19:45:27.719934554  [2025-01-18 19:45:27] detector.coral1                INFO    : Starting detection process: 440
2025-01-18 19:45:27.720243585  [2025-01-18 19:45:27] frigate.app                    INFO    : Output process started: 442
2025-01-18 19:45:27.725855339  [2025-01-18 19:45:27] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-01-18 19:45:30.657213089  [2025-01-18 19:45:27] frigate.app                    INFO    : Camera processor started for LR_amcrest: 457
2025-01-18 19:45:30.657689691  [2025-01-18 19:45:27] frigate.app                    INFO    : Capture process started for LR_amcrest: 458
2025-01-18 19:45:30.657953704  [2025-01-18 19:45:27] frigate.app                    INFO    : Audio process started: 467
2025-01-18 19:45:30.666404119  [2025-01-18 19:45:30] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-01-18 19:45:33.339622395  [INFO] Starting go2rtc healthcheck service...
```

### Relevant go2rtc log output

```shell
2025-01-18 19:45:23.344872814  [INFO] Preparing new go2rtc config...
2025-01-18 19:45:24.348145127  [INFO] Starting go2rtc...
2025-01-18 19:45:24.606927033  19:45:24.606 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-18 19:45:24.606938586  19:45:24.606 INF config path=/dev/shm/go2rtc.yaml
2025-01-18 19:45:24.607522245  19:45:24.607 INF [rtsp] listen addr=:8554
2025-01-18 19:45:24.607635962  19:45:24.607 INF [api] listen addr=:1984
2025-01-18 19:45:24.608521364  19:45:24.608 INF [webrtc] listen addr=:8555/tcp
2025-01-18 19:45:33.339622395  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://frigate:(secret)@10.0.1.81:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.024000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp
```

### Frigate stats

```json
{
  "cameras": {
    "LR_amcrest": {
      "audio_dBFS": -69.5929,
      "audio_rms": 10.8593,
      "camera_fps": 5,
      "capture_pid": 458,
      "detection_enabled": true,
      "detection_fps": 0,
      "ffmpeg_pid": 470,
      "pid": 457,
      "process_fps": 5,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "108": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "109": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "1.7",
      "cpu_average": "2",
      "mem": "0.8"
    },
    "1118": {
      "cmdline": "bash",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "131": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "167": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "168": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "169": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "170": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "171": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "1801": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "1872": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "322": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "34": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "363": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "412": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "413": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "439": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "440": {
      "cmdline": "frigate.detector.coral1",
      "cpu": "0.1",
      "cpu_average": "1",
      "mem": "0.5"
    },
    "442": {
      "cmdline": "frigate.output       ",
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "457": {
      "cmdline": "frigate.process:LR_amcrest",
      "cpu": "2.3",
      "cpu_average": "3",
      "mem": "0.5"
    },
    "458": {
      "cmdline": "frigate.capture:LR_amcrest",
      "cpu": "2.8",
      "cpu_average": "2",
      "mem": "0.4"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "467": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "470": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.1.81:554/cam/realmonitor?channel=1&subtype=2 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.4",
      "cpu_average": "3",
      "mem": "0.5"
    },
    "487": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.1.81:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/LR_amcrest@%Y%m%d%H%M%S%z.mp4",
      "cpu": "2.9",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "489": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.1.81:554/cam/realmonitor?channel=1&subtype=0 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "3.0",
      "cpu_average": "2",
      "mem": "0.1"
    },
    "514": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 3840x2160 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "519": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "86": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "87": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "frigate.full_system": {
      "cpu": "2.9",
      "mem": "7.2"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "coral1": {
      "detection_start": 0,
      "inference_speed": 46.66,
      "pid": 440
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 1650 SUPER": {
      "dec": "0.0%",
      "enc": "0.0%",
      "gpu": "0.0%",
      "mem": "7.79%"
    }
  },
  "processes": {
    "audio_detector": {
      "pid": 467
    },
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 363
    },
    "recording": {
      "pid": 412
    },
    "review_segment": {
      "pid": 413
    }
  },
  "service": {
    "last_updated": 1737259031,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 97,
        "mount_type": "tmpfs",
        "total": 100,
        "used": 3
      },
      "/media/frigate/clips": {
        "free": 6596152.6,
        "mount_type": "smb3",
        "total": 9182109.4,
        "used": 2585956.8
      },
      "/media/frigate/recordings": {
        "free": 6596152.6,
        "mount_type": "smb3",
        "total": 9182109.4,
        "used": 2585956.8
      },
      "/tmp/cache": {
        "free": 1014.7,
        "mount_type": "tmpfs",
        "total": 1024,
        "used": 9.3
      }
    },
    "temperatures": {

    },
    "uptime": 704,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    #network_mode: bridge
    deploy: # <------------- Add this section for nvidia
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
    shm_size: "100mb" # update for your cameras based on calculation
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Surveillance/frigate/frigate.yml:/config/config.yml # modify to match your setup
      - /Surveillance/frigate:/media/frigate # modify to match your setup
      - /home/dutch/frigate:/db # modify to match your setup
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1073741824
    ports:
      - "10.0.1.10:5000:5000"
      # - "1935:1935" # RTMP feeds – comment out if not needed , it may conflict with other containers
    environment:
      FRIGATE_RTSP_PASSWORD: "(secret)" 
      FRIGATE_RTSP_USER: "frigate"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

IP8M-DT3949EW-3AI-V2

### Screenshots of the Frigate UI's System metrics pages

<img width="1232" alt="Screenshot 2025-01-18 at 8 03 41 PM" src="https://github.com/user-attachments/assets/1ce88435-3886-4ba6-9f32-b8308accede9" />
