### DISCUSSION TITLE
[HW Accel Support]: Coral is very slow

### DISCUSSION THREAD

**Discussion by SebOM** [blakeblackshear/frigate#16058] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

My Coral is very slow (130ms)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: true
  user: jeedom
  password: XKCuYAiiQNLnHavVPAVGO5b9yqljIMa3C29KN4ffddZNVQa79UdO0g9Mdbiq09tA
  host: 192.168.1.2
  port: 1883

ffmpeg:
  hwaccel_args: 
    preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
   coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

go2rtc:
  streams:
    Salon:
      - rtsp://freeboxcam:FqbmWqts@192.168.1.51/live
      - ffmpeg:rtsp_entree#audio=opus#audio=aac
    JardinHD:
      - rtsp://motion:allezlom@192.168.1.50:554/live/stream1
      - ffmpeg:rtsp_entree#audio=opus#audio=aac

timestamp_style:
  #Yes, the legacy software is capable of showing the timestamp, but i like all the configurations to be the same place
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 3

snapshots:
  enabled: true

cameras:
  Salon:
    ffmpeg:
      inputs:
        - path: rtsp://freeboxcam:FqbmWqts@192.168.1.51/live
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Salon
          input_args: preset-rtsp-restream
          roles:
            - detect
            
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 3
        post_capture: 3
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.7
          threshold: 0.75
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'

  Jardin:
    ffmpeg:
      inputs:
        - path: rtsp://motion:allezlom@192.168.1.50:554/live/stream1
          roles:
            - record
          #input_args: preset-rtsp-generic
        - path: rtsp://127.0.0.1:8554/JardinHD
          input_args: preset-rtsp-restream
          roles:
            
            - detect
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 3
        post_capture: 3
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
      mask: 0.214,0.178,0.213,0.098,0.188,0,0.215,0,0.248,0.107,0.248,0.197
      filters:
        person:
          min_score: 0.7
          threshold: 0.75
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 
        0.688,0.08,1,0.233,1,0,0.342,0,0.177,0.047,0.327,0.021,0.346,0,0.34,0,0,0,0,0.049,0,0.111,0.309,0,0.192,0,0.212,0.036,0.34,0.009
model:
  path: /cpu_model.tflite
version: 0.14

```

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
2025-01-20 08:52:06
frigate.detectors.plugins.edgetpu_tfl
TPU found
```

### Relevant go2rtc log output

```shell
2025-01-20 08:51:59.242888071  [INFO] Preparing new go2rtc config...
2025-01-20 08:51:59.794575840  [INFO] Starting go2rtc...
2025-01-20 08:51:59.914874756  08:51:59.914 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-20 08:51:59.914879832  08:51:59.914 INF config path=/dev/shm/go2rtc.yaml
2025-01-20 08:51:59.915392820  08:51:59.915 INF [rtsp] listen addr=:8554
2025-01-20 08:51:59.915488602  08:51:59.915 INF [api] listen addr=:1984
2025-01-20 08:51:59.915856282  08:51:59.915 INF [webrtc] listen addr=:8555/tcp
2025-01-20 08:52:09.139553028  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
No error
```

### Install method

Proxmox via Docker

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

TAPO & FreeBOX

### Screenshots of the Frigate UI's System metrics pages

![Sans titre](https://github.com/user-attachments/assets/06f5fc3e-6c20-4fe7-8ede-4501ce4b452e)
