### DISCUSSION TITLE
[Support]: docker compose, how do I modify it to include nvidia toolkit?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#16052] [General Support] [answered]
### Describe the problem you are having

 [This page](https://docs.frigate.video/configuration/hardware_acceleration/) says to add this:

![image](https://github.com/user-attachments/assets/8070a60f-1222-44c5-aef1-9d24165e3dc7)

to my docker compose file but in doing so I get errors because I don't know the exact format of the resultant file  which I should be aiming for:

```
container frigate015beta6  Recreated                                                             0.3s 
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
[+] Running 0/1
 ⠸ Container frigate015beta6  Starting                                                              0.3s 
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
validating /opt/stacks/frigate015beta6/compose.yaml: (root) Additional property deploy is not allowed
```
I realise that this might be painfully obvious for many people but I have tried half a dozen times to add the structure but I have got nowhere.

Can someone show me explicitly how / where I ought to add those lines please?  My unmodified docker compose is included here for ease:

```
version: "3.9"
services:
  frigate:
    container_name: frigate015beta6
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta6
    
    
    shm_size: 256mb # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      #host : container
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      #      mem_limit: 4096m # seemed to make load a bit worse
      #      cpus: "4" # seemed to make load a bit worse
      LIBVA_DRIVER_NAME: i965
      PLUS_API_KEY: ################################
networks: {}
```

I have installed an Nvidia GPU (a P620 PCIe card) into my test machine to use for Frigate in place of the existing intel iGPU, and next I shall need to fiddle with the Frigate config file.

Thanks!

### Version

0.15.0-3947e79

### What browser(s) are you using?

Version 131.0.6778.264 (Official Build) for Linux Mint (64-bit)

### Frigate config file

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate015beta6
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta6
    
    
    shm_size: 256mb # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      #host : container
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      #      mem_limit: 4096m # seemed to make load a bit worse
      #      cpus: "4" # seemed to make load a bit worse
      LIBVA_DRIVER_NAME: i965
      PLUS_API_KEY: ##################################
networks: {}
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

n/a

**Comment by NickM-27** [comment]
I think it would be better to see what you did, it should get copied directly under image like the example shows

**Reply by ElectronicBattle** [reply]
This is what  I did:


```
version: "3.9"
services:
  frigate:
    container_name: frigate015beta6
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta6
    
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] #only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
              
              
    shm_size: 256mb # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      #host : container
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      #      mem_limit: 4096m # seemed to make load a bit worse
      #      cpus: "4" # seemed to make load a bit worse
      LIBVA_DRIVER_NAME: i965
      PLUS_API_KEY: ###############
networks: {}
```

Which, when I run it, tells me

![image](https://github.com/user-attachments/assets/72d2bcc1-f25e-4cb2-b920-bdb966b456bc)


The error message in the dockge window is specifically

```
[+] Running 0/1
 ⠸ Container frigate015beta6  Starting                                                              0.3s 
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
```
I also tried including the additional section right at the end after the key but before `networks{}` because chatGPT suggested it. 

(As usual, chatGPT and I know about as much as each other when it comes to these things ...)
