### DISCUSSION TITLE
Edge changes camera aspect ratio in live mode

### DISCUSSION THREAD

**Discussion by realcnk** [blakeblackshear/frigate#16051] [Ask A Question]
Hi.

Few moths ago, after an Edge update, the cameras in live mode changes the aspect ratio when its switch to HD mode. It's only in MS Edge, in Opera shows in 16:9 and HD. How is it resolved?

**Comment by hawkeye217** [comment]
Frigate doesn't have any browser-specific code for Edge. What is your frigate config?

**Comment by realcnk** [comment]
Thanks. 

Frigate config:

```
mqtt:
  host: **
  user: **
  password: **

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

go2rtc:
  log:
    exec: trace
  webrtc:
    candidates:
      - **:8555
      - stun:8555

  streams:
    Salon:
      - tapo://admin:**@**  
	  
    Nenes:
      - tapo://admin:**@**  

    Pasillo:
      - tapo://admin:**@**  

    Pasillo_sub:
      - ffmpeg:rtsp://**@**:554/stream2
	  
    Dormitorio:
      - tapo://admin:**@**  


cameras:
  Pasillo:
    ui:
      order: 1
    onvif:
      host: **
      port: **
      user: ca**
      password: '**'
    
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Pasillo

    detect:
      enabled: false
      fps: 5
    objects:
      track:
        - person
      #filters:
      #person:
      #mask:
      #- 519,71,520,229
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion

    motion:
      threshold: 39
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0.171,0.527,0.172,0.678,0.234,0.702,0.229,0.551
        - 0.703,0.038,0.711,0.304,0.764,0.401,0.803,0.052
  Nenes:
    ui:
      order: 2
    onvif:
      host: **
      port: **
      user: ca**
      password: '**'
    
    ffmpeg:
      
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            #- rtmp
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Nenes
    detect:
      enabled: false
      fps: 5
    motion:
      threshold: 30
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion

  Salon:
    ui:
      order: 4
    onvif:
      host: **
      port: **
      user: ca**
      password: '**'
    #birdseye:
      #order: 4
    ffmpeg:
      
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            #- rtmp
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Salon
    detect:
      enabled: false
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion

  Dormitorio:
    ui:
      order: 3
    onvif:
      host: **
      port: **
      user: ca**
      password: '!**'
    #birdseye:
      #order: 3
    ffmpeg:
      
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            #- rtmp
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Dormitorio
    detect:
      enabled: false
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion
version: 0.14
camera_groups:
  Camaras:
    order: 1
    icon: LuVideo
    cameras:
      - Dormitorio
      - Nenes
      - Pasillo
      - Salon
  Birdeye:
    order: 2
    icon: LuBox
    cameras: birdseye
```

Edge: Low Quality mode aspect ratio ok, High quality shrinks the images.
Opera: All ok.

Opera:
![Opera](https://github.com/user-attachments/assets/f994c4d2-dd55-466c-a6e7-8565afbb9dc7)

Edge:
![Edge](https://github.com/user-attachments/assets/dafa3645-3482-4361-814f-f755b556d4f7)

Edge with all HQ:
![Edge2](https://github.com/user-attachments/assets/a3c00067-cb0e-4723-87a9-bbaa7026c146)

**Reply by hawkeye217** [reply]
This is a similar issue we've seen with Tapo cameras and Chromium-based browsers. 

A bug in Chromium causes incorrect the aspect ratio to be displayed. You may find success by using the `ffmpeg` source in go2rtc (instead of the `tapo` source), eg:

`ffmpeg:rtsp://...#video=copy#audio=copy`

See these related issues:

https://github.com/blakeblackshear/frigate/discussions/15049
https://github.com/blakeblackshear/frigate/discussions/14446

**Reply by realcnk** [reply]
ffmpeg get aspect ratio ok, but low quality stream.

**Reply by hawkeye217** [reply]
What is your current Frigate config?

**Reply by realcnk** [reply]
Only test with "Pasillo" cam

```
mqtt:
  host: **
  user: **
  password: **

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

go2rtc:
  log:
    exec: trace
  webrtc:
    candidates:
      - **:8555
      - stun:8555

  streams:
    Salon:
      - tapo://admin:**@**  
	  
    Nenes:
      - tapo://admin:**@**  

    Pasillo:
      - tapo://admin:**@**  

    Pasillo_sub:
      - ffmpeg:rtsp://**@**:554/stream2

    Pasillo_sub2:
      - ffmpeg:rtsp://**@**:554/stream1
      - "ffmpeg:Salon#audio=opus"
	  
    Dormitorio:
      - tapo://admin:**@**  


cameras:
  Pasillo:
    ui:
      order: 1
    onvif:
      host: **
      port: **
      user: ca**
      password: '**'
    
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Pasillo_sub2

    detect:
      enabled: false
      fps: 5
    objects:
      track:
        - person
      #filters:
      #person:
      #mask:
      #- 519,71,520,229
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion

    motion:
      threshold: 39
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0.171,0.527,0.172,0.678,0.234,0.702,0.229,0.551
        - 0.703,0.038,0.711,0.304,0.764,0.401,0.803,0.052
  Nenes:
    ui:
      order: 2
    onvif:
      host: **
      port: **
      user: ca**
      password: '**'
    
    ffmpeg:
      
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            #- rtmp
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Nenes
    detect:
      enabled: false
      fps: 5
    motion:
      threshold: 30
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion

  Salon:
    ui:
      order: 4
    onvif:
      host: **
      port: **
      user: ca**
      password: '**'
    #birdseye:
      #order: 4
    ffmpeg:
      
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            #- rtmp
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Salon
    detect:
      enabled: false
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion

  Dormitorio:
    ui:
      order: 3
    onvif:
      host: **
      port: **
      user: ca**
      password: '!**'
    #birdseye:
      #order: 3
    ffmpeg:
      
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://**@**:554/stream1
          roles:
            #- rtmp
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://**@**:554/stream2
          roles:
            - detect
          input_args: preset-rtsp-restream
    live:
      stream_name: Dormitorio
    detect:
      enabled: false
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
        mode: all
      #events:
      #retain:
      #default: 30
      #mode: motion
version: 0.14
camera_groups:
  Camaras:
    order: 1
    icon: LuVideo
    cameras:
      - Dormitorio
      - Nenes
      - Pasillo
      - Salon
  Birdeye:
    order: 2
    icon: LuBox
    cameras: birdseye
```
