### DISCUSSION TITLE
[Config Support]: Frigate+ API key

### DISCUSSION THREAD

**Discussion by gspitale** [blakeblackshear/frigate#16056] [Config Support] [answered]
### Describe the problem you are having

I've searched for the last few house, and for the life of me I cannot figure out how/where to enter the Frigate+ API key.

sudo docker compose up -d results in this response (not sure why it is lined out here):

giovanni@Frigate:~/docker_stacks/frigate$ sudo docker compose up -d
services.frigate.environment.[0]: unexpected type map[string]interface {}
giovanni@Frigate:~/docker_stacks/frigate$ 

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: homeassistant.havenwood
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: Mosquitto
  password: mosquitto1245h

environment_vars:
  PLUS_API_KEY: cda151ba-52e4-4c1d-8f4c-09a5ef12bbc6:518674032bc672a8cc58bfafe421de2f5160d9f0

ffmpeg:
#  hwaccel_args: preset-intel-qsv-h264
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac


detectors:
  coral_1:
    type: edgetpu
    device: pci:0
  coral_2:
    type: edgetpu
    device: pci:1

objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - bear

review:
  alerts:
    labels:
      - person
      - bicycle
      - car
      - cat
      - dog
      - bear

snapshots:
  enabled: true

audio:
  enabled: true

go2rtc:
  streams:
    FrontYard:
      - rtsp://frontyard.camera.havenwood:554/media/video1#backchannel=0
    FrontYardsub:
      - rtsp://frontyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:FrontYardsub#audio=aac
    FrontDoor:
      - rtsp://frontdoor.camera.havenwood:554/media/video1#backchannel=0
    FrontDoorsub:
      - rtsp://frontdoor.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:FrontDoorsub#audio=aac
    Driveway1:
      - rtsp://driveway1.camera.havenwood:554/media/video1#backchannel=0
    Driveway1sub:
      - rtsp://driveway1.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Driveway1sub#audio=aac
    Driveway2:
      - rtsp://driveway2.camera.havenwood:554/media/video1#backchannel=0
    Driveway2sub:
      - rtsp://driveway2.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Driveway2sub#audio=aac
    Garage:
      - rtsp://garage.camera.havenwood:554/media/video1#backchannel=0
    Garagesub:
      - rtsp://garage.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Garagesub#audio=aac
    NorthYard:
      - rtsp://northyard.camera.havenwood:554/media/video1#backchannel=0
    NorthYardsub:
      - rtsp://northyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:NorthYardsub#audio=aac
    BackYard1:
      - rtsp://backyard1.camera.havenwood:554/media/video1#backchannel=0
    BackYard1sub:
      - rtsp://backyard1.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackYard1sub#audio=aac
    BackYard2:
      - rtsp://backyard2.camera.havenwood:554/media/video1#backchannel=0
    BackYard2sub:
      - rtsp://backyard2.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackYard2sub#audio=aac
    NorthDeck:
      - rtsp://northdeck.camera.havenwood:554/media/video1#backchannel=0
    NorthDecksub:
      - rtsp://northdeck.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:NorthDecksub#audio=aac
    SouthDeck:
      - rtsp://southdeck.camera.havenwood:554/media/video1#backchannel=0
    SouthDecksub:
      - rtsp://southdeck.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:SouthDecksub#audio=aac
    SouthYard:
      - rtsp://southyard.camera.havenwood:554/media/video1#backchannel=0
    SouthYardsub:
      - rtsp://southyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:SouthYardsub#audio=aac

record:
  enabled: true
  retain:
    days: 21
    mode: all

cameras:
  FrontYard:
    enabled: true
    ui:
      order: 1
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://frontyard.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontYardsub
          roles:
            - audio
            - detect
    motion:
      mask: 0.737,0.903,0.982,0.902,0.981,0.958,0.735,0.96
  FrontDoor:
    enabled: true
    ui:
      order: 2
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://frontdoor.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoorsub
          roles:
            - audio
            - detect
    motion:
      mask: 0.016,0.961,0.273,0.963,0.273,0.899,0.014,0.892
  Driveway1:
    enabled: true
    ui:
      order: 3
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://driveway1.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway1sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.017,0.042,0.268,0.039,0.268,0.1,0.017,0.1
  Driveway2:
    enabled: true
    ui:
      order: 4
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://driveway2.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway2sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.735,0.957,1,0.954,1,0.902,0.734,0.905
  Garage:
    enabled: true
    ui:
      order: 5
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://garage.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garagesub
          roles:
            - audio
            - detect
    motion:
      mask: 0.268,0.959,0.024,0.961,0.023,0.904,0.269,0.906
  NorthYard:
    enabled: true
    ui:
      order: 6
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://northyard.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthYardsub
          roles:
            - audio
            - detect
    motion:
      mask: 0.022,0.959,0.267,0.961,0.267,0.902,0.022,0.902
  BackYard1:
    enabled: true
    ui:
      order: 7
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://backyard1.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard1sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.02,0.956,0.269,0.961,0.268,0.904,0.02,0.899
  BackYard2:
    enabled: true
    ui:
      order: 8
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://backyard2.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard2sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.735,0.954,0.977,0.954,0.978,0.904,0.733,0.906
  NorthDeck:
    enabled: true
    ui:
      order: 9
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://northdeck.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthDecksub
          roles:
            - audio
            - detect
    motion:
      mask: 0.022,0.09,0.268,0.092,0.268,0.044,0.023,0.039
  SouthDeck:
    enabled: true
    ui:
      order: 10
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://southdeck.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthDecksub
          roles:
            - audio
            - detect
    motion:
      mask: 0.735,0.954,0.979,0.952,0.979,0.904,0.734,0.904
  SouthYard:
    enabled: true
    ui:
      order: 11
    detect:
      enabled: true
    record:
      enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://southyard.camera.havenwood:554/media/video1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthYardsub
          roles:
            - audio
            - detect
    motion:
      mask: 0.02,0.087,0.267,0.092,0.267,0.044,0.023,0.044
version: 0.14
```

### Relevant Frigate log output

```shell
Nothing relevant
```

### Relevant go2rtc log output

```shell
Nothing relevant
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1000mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./config:/config
      - /mnt/frigate_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
      - "1984:1984"
    environment:
      - PLUS_API_KEY: "inside-the-quotes-I-entered-my-key"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1134" alt="Screenshot 2025-01-19 at 5 14 00 PM" src="https://github.com/user-attachments/assets/1b15e05b-201c-4d87-8cf7-899833027a35" />
