### DISCUSSION TITLE
Memory Handling in Frigate

### DISCUSSION THREAD

**Discussion by aayush-eatclub** [blakeblackshear/frigate#16065] [Ask A Question]
I am using frigate to read feeds from 16 cameras. I understand it requires larger memory and SHM to process the feeds , but even after increasing docker container limits to 8GB , my container throws Out Of Memory continuously and restarts again and again.
Is there any way I can control this memory consumption.
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "4096mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /home/outletmanager/outletvideocam:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "8971:8971"
      - "5001:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
        resources:
            limits:
              cpus: "2"
              memory: 8000M
            reservations:
              cpus: "1"
              memory: 4000M

```

config.yaml

```
auth:
  enabled: false
birdseye:
  enabled: false
cameras:
  cam_31:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.31/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_34:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.34/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_35:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.35/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_36:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.36/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_38:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.38/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_39:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.39/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_40:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.40/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_42:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.42/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_43:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.43/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
  cam_44:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:
      - path: rtsp://admin:admin@123@192.168.9.44/cam/realmonitor?channel=1&subtype=00
        roles:
        - record
    record:
      enabled: true
      retain:
        days: 2
        mode: all
detect:
  enabled: false
detectors:
  detector_name:
    type: cpu
motion:
  enabled: false
mqtt:
  enabled: false
record:
  enabled: true
  sync_recordings: true
tls:
  enabled: false
version: 0.15-0
```
