### DISCUSSION TITLE
[Support]: Portrait RTC video rendering diagonal 'tear' on Live view recording cameras

### DISCUSSION THREAD

**Discussion by maxlyth** [blakeblackshear/frigate#16068] [Config Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Portrait videos have a diagonal horizontal offset on luminance channel and flip of chroma channel when the camera is highlighted as recording. This occurs on Frigate 14 and 15b7 on current Safari, Chrome and Firefox on MacOS 15.2 but was also present on iOS 17/18 and MacOS 14.x on all browsers. This is a Frigate only rendering issues as occurs on no other devices when rendering direct Go2RTC streams. 

The source cameras are Hikvision DS-2CD2347G1-LU and the stream is rotated to portrait on camera but I don't believe the problem to be camera related as it still occurs if stream is re-sized and re-encoded in Go2RTC with ffmpeg. 

When the Frigate Live pane initially loads the video renders correctly but if the video has the red recording rectangle then the video 'tears' on the diagonal, probably as the browser renderer switches from MSE to RTC. In the screenshot below the left camera has a rendering bug that is correlated with the recording highlight:
![Recording RTX video rendering error](https://github.com/user-attachments/assets/ae308c6b-4842-4475-81b4-f75d17f98788)

It is likely that it is not Frigate altering the video stream but a bad combination of the CSS for highlighting a recording camera and the Apple RTC rendering framework as it affects all browser irrespective of HTML rendering archtectures. The same issue occurs when using the built in go2rtc or running a standalone go2rtc on an external machine, with or without, hardware acceleration or re-encoding.

### Steps to reproduce

1. Frigate Live view pane
2. Portrait cameras initally render correctly 
3. Wait 2-3 seconds
4. Cameras highlighted as recording render incorrectly with diagonal 'tear'

### Version

0.14 and 0.15beta7

### In which browser(s) are you experiencing the issue with?

Safari, Chrome and Firefox

### Frigate config file

```yaml
version: 0.14

mqtt:
  enabled: true
  host: mqtt.domain.lan
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  stats_interval: 60


auth:
  enabled: true
  reset_admin_password: false
  session_length: 604800
  refresh_time: 86400
  failed_login_rate_limit: None


audio:
  enabled: true
  max_not_heard: 5
  min_volume: 600
  listen:
    - speech
  filters:
    speech:
      threshold: 0.8


detectors:
  coral:
    type: edgetpu
    device: usb


model:
  path: plus://xxx


detect:
  enabled: true
  min_initialized: 5
  max_disappeared: 40
  stationary:
    interval: 10
    threshold: 50


objects:
  track:
    - person
    - face
    - car
    - vehicle
    - license_plate
    - bicycle
    - motorcycle
    - cat
    - dog
    - fox
    - horse
    - umbrella
    - package
    - waste_bin

review:
  alerts:
    labels:
      - person
      - face
      - license_plate
      - speech
  detections:
    labels:
      - person
      - face
      - car
      - vehicle
      - license_plate
      - bicycle
      - motorcycle
      - cat
      - dog
      - fox
      - horse
      - umbrella
      - package
      - waste_bin
      - speech


motion:
  enabled: true
  threshold: 30
  contour_area: 20
  frame_alpha: 0.01
  frame_height: 200
  improve_contrast: false


record:
  enabled: true
  expire_interval: 30
  retain:
    days: 10
    mode: motion
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 50
  preview:
    quality: medium
  events:
    retain:
      default: 30
      mode: active_objects


snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 45
    objects:
      person: 14
  quality: 70


cameras:
  camera_north:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc.domain.lan:8554/north-uhd
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://go2rtc.domain.lan:8554/north-hd
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
    best_image_timeout: 60
    webui_url: https://camera-north.domain.net
    ui:
      order: 10
      dashboard: true
    live:
      stream_name: north-uhd
    motion:
      mask:
        - 0.312,0.136,0.471,0.195,0.752,0.356,0.809,0.402,0.833,0.484,1,0.577,1,0,0,0,0,0.311,0.046,0.178,0.106,0.086,0.196,0.088,0.214,0.115
        - 0,0.717,0,1,0.179,1,0.096,0.893
    zones:
      Pavement:
        coordinates:
          0.097,0.088,0.176,0.089,0.17,0.172,0.198,0.317,0.274,0.518,0.385,0.738,0.626,1,0.138,1,0,0.8,0,0.283
        loitering_time: 0
        objects:
          - person
          - face
          - car
          - vehicle
          - license_plate
          - bicycle
          - motorcycle
          - cat
          - dog
          - package
          - umbrella
        inertia: 3
      Parking:
        coordinates:
          0.261,0.178,0.427,0.343,0.522,0.433,0.706,0.624,0.851,0.784,1,0.953,1,0.623,0.727,0.386,0.558,0.294,0.353,0.179
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - face
          - license_plate
          - bicycle
          - motorcycle
          - cat
          - dog
          - umbrella
          - fox
          - horse
      Door:
        coordinates: 0,0.541,0.209,0.535,0.328,0.773,0.048,0.785,0,0.691
        loitering_time: 0
        objects:
          - person
          - face
          - umbrella
          - package
        inertia: 3
    objects:
      filters:
        car: {}
  camera_south:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc.domain.lan:8554/south-uhd
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://go2rtc.domain.lan:8554/south-hd
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - audio
    best_image_timeout: 60
    webui_url: https://camera-south.domain.net
    ui:
      order: 20
      dashboard: true
    live:
      stream_name: south-uhd
    motion:
      mask:
        - 0,0.538,0.211,0.396,0.447,0.246,0.321,0.194,0.594,0.11,0.65,0.145,0.693,0.131,0.773,0.066,0.857,0.064,0.895,0.09,0.907,0.11,0.958,0.183,1,0.268,1,0,0,0
        - 0.81,1,0.921,0.849,1,0.673,1,1
    zones:
      Pavement:
        coordinates:
          0.391,1,0.618,0.753,0.778,0.466,0.843,0.295,0.861,0.134,0.856,0.098,0.814,0.059,0.836,0.059,0.866,0.07,0.894,0.09,1,0.257,1,0.715,0.841,1
        loitering_time: 0
        objects:
          - person
          - face
          - car
          - vehicle
          - license_plate
          - bicycle
          - motorcycle
          - cat
          - dog
          - package
          - umbrella
        inertia: 3
      Parking:
        coordinates:
          0,0.566,0.438,0.268,0.627,0.149,0.752,0.069,0.802,0.068,0.796,0.094,0.765,0.128,0.635,0.254,0.448,0.444,0.154,0.759,0,0.936
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - face
          - license_plate
          - bicycle
          - motorcycle
          - cat
          - dog
          - umbrella
      Door:
        coordinates: 0.786,0.509,1,0.515,1,0.795,0.674,0.779
        loitering_time: 0
        objects:
          - person
          - face
          - umbrella
          - package
        inertia: 3
    objects:
      filters:
        car: {}
telemetry:
  stats:
    intel_gpu_stats: true
    network_bandwidth: true
  version_check: true


logger:
  default: warning
  logs:
    frigate.app: info
    frigate.mqtt: error
    frigate.object_detection: info
    detector.coral: debug
    detector.ov: debug
```

### docker-compose file or Docker CLI command

```yaml
networks:
  vlandmz:
    external: true

volumes:
  cctv:
    driver_opts:
      type: "nfs"
      o: "addr=172.a.b.c,nolock,rw,soft,nfsvers=4"
      device: ":/media/CCTV"

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    cap_add:
      - CAP_PERFMON
    environment:
      TZ: "Europe/London"
      PLUS_API_KEY: xxx
    networks:
      vlandmz:
        ipv4_address: 172.a.b.xx
    ports:
      - "8971:8971"
      - "1984:1984" # Go2RTC Web interface
      - "1935:1935" # RTMP
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    shm_size: "192mb" # 192mb is actually enough based on calculation above
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./custom-start.sh:/custom-start.sh:ro
      - ./config:/config:delegated
      - ./data:/media/frigate:delegated
      - cctv:/media/nas
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1073741824
    entrypoint: ["/bin/bash", "/custom-start.sh"]
```

### Relevant Frigate log output

```shell
There is no correlated textual log output, this is a GUI rendering issue
```

### Relevant go2rtc log output

```shell
got2rtc produces no correlated log output
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2347G1-LU

### Screenshots of the Frigate UI's System metrics pages

![Frigate System Console](https://github.com/user-attachments/assets/d81363e9-0ce7-409a-9895-8d79a5241338)

### Any other information that may be helpful

I realise this is probably hard to recreate and debug but I could spin up a VM in a VLAN with docker, Frigate container, VSCode ssh keys with TailScale/Wireguard/OpenVPN/CloudFlareTunnel for the right person.

**Comment by hawkeye217** [comment]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Usage question 15.

**Comment by maxlyth** [comment]
Thanks for replying so quickly and this is seems likely the issue but I had already tried setting the detect dimensions:
```
detect:
  enabled: true
  width: 720
  height: 1280
```
However this does not fix the problem and I get exactely the same result. If I change the detect resolution to landscape:
```
detect:
  enabled: true
  width: 1280
  height: 720
```
This fixes the tearing but the vidoes are distorted into the wrong aspect ratio in the Live view:
![Frigate Live wrong aspect ratio](https://github.com/user-attachments/assets/cf977fd7-bf27-4e87-9f8b-c0fd189f7259)

If I check the stream info in go2rtc then the {producer:{sdp}} object contains `na=x-dimensions:1280,720` so the source stream seems to be implying landscape even though it is rotated. I think it is this mismatch that creates the wrong outcome whatever is set in the `detect` config. 

Could this be a go2rtc problem? I am currently using 1.9.8 in a separate container to supply both my 14 and 15b7 instances of Frigate.
