### DISCUSSION TITLE
[Support]: Parked car detection issues

### DISCUSSION THREAD

**Discussion by alec-pinson** [blakeblackshear/frigate#16061] [General Support] [answered]
### Describe the problem you are having

I'm having lots of notifications for parked cars that aren't moving and I'm not sure how to fix it.

![{1B26BE7D-BB38-4E09-BA1E-60BA6B9726A7}](https://github.com/user-attachments/assets/e419de02-cc28-40de-b4c3-45f0fae247bc)

Everything was fine with threshold 38 in the day time and contour 10, however since the blue car (see video) was parked, it's constantly triggering notifications.

I've tried to set threshold to 80 and contour to 50 and it's still happening, what else is worth looking at to fix this issue?
I looked at the stationary objects doc but didn't think it was relevant to this issue

I've uploaded a video to google drive of the debug:
https://drive.google.com/file/d/1Fp2qwwnvecLYUppvUfDvdgIqsrbDlJ_s/view?usp=sharing

### Version

0.15.0-87e7b62

### What browser(s) are you using?

131.0.6778.265 (Official Build) (x86_64)

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

tls:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci:0

semantic_search:
  enabled: True
  reindex: False

objects:
  track:
    - person
    - car

auth:
  enabled: False

record:
  enabled: True
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

notifications:
  enabled: True
  email: "xxxxxxxxxxxxx@gmail.com"

cameras:
  gate_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    review:
      alerts:
        labels:
          - car
          - person
        required_zones:
          - driveway
          - postbox
      detections:
        labels:
          - person
          - car
        required_zones:
          - driveway
          - postbox
          - driveway_grass
    zones:
      driveway:
        coordinates: 0.296,1,0.377,0.787,0.388,0.578,0.524,0.569,0.781,0.701,0.924,0.738,0.882,0.908,0.856,1
        objects:
          - person
          - car
      postbox:
        coordinates: 0.897,0.723,0.927,0.728,0.945,0.474,0.929,0.466,0.913,0.478
        objects:
          - person
      driveway_entry:
        coordinates: 0.387,0.574,0.525,0.562,0.475,0.52,0.395,0.523
        objects:
          - person
          - car
      driveway_grass:
        coordinates: 0.893,0.722,0.906,0.643,0.719,0.586,0.616,0.548,0.519,0.553,0.568,0.585,0.787,0.695
        objects:
          - person
      # neighbour:
      #   coordinates: 0.385,0.556,0.37,0.777,0.286,1,0,1,0,0.778,0,0,0.096,0,0.222,0,0.307,0.217,0.394,0.4,0.394,0.514
      #   objects:
      #     - person
      # footpath:
      #   coordinates: 0.901,0.632,0.915,0.42,0.634,0.417,0.531,0.434,0.526,0.458,0.528,0.486,0.612,0.541,0.734,0.585
      #   objects:
      #     - person
    motion:
      threshold: 32
      mask:
        # ignore date/time at top
        - 0.274,0,0.277,0.061,0.708,0.061,0.706,0
        # tree
        - 0.361,0.062,0.353,0.156,0.395,0.289,0.455,0.404,0.905,0.404,0.943,0.222,0.969,0,0.711,0,0.711,0.061
        # ignore neighbours
        - 0.385,0.556,0.37,0.777,0.286,1,0,1,0,0.778,0,0,0.096,0,0.222,0,0.307,0.217,0.394,0.4,0.394,0.514
        # ignore footpath
        - 0.901,0.632,0.915,0.42,0.634,0.417,0.531,0.434,0.526,0.458,0.528,0.486,0.612,0.541,0.734,0.585
        # ignore road
        - 0.396,0.519,0.538,0.518,0.531,0.413,0.396,0.414
    objects:
      filters:
        car:
          mask: 0.385,0.556,0.37,0.777,0.286,1,0,1,0,0.778,0,0,0.096,0,0.222,0,0.307,0.217,0.394,0.4,0.394,0.514
  driveway_left:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.62:554/ch01.264
          roles:
            - record
        - path: rtsp://192.168.4.62:554/ch01_sub.264
          roles:
            - detect
    review:
      alerts:
        labels:
          - car
          - person
        required_zones:
          - driveway
          - drive
      detections:
        labels:
          - person
          - car
        required_zones:
          - driveway
          - drive
    zones:
      # neighbour:
      #   coordinates: 0,0.656,0.254,0.327,0.204,0.218,0.135,0.053,0,0.05
      #   objects: []
      drive:
        coordinates: 0,0.688,0.347,0.256,0.503,0.106,0.711,0.184,0.842,0.247,1,0.364,1,1,0,1
        objects:
          - person
          - car
      driveway:
        coordinates: 0.159,0.103,0.213,0.071,0.257,0.095,0.277,0.082,0.402,0.156,0.405,0.189,0.271,0.331,0.253,0.308
        objects:
          - person
          - car
    motion:
      threshold: 80
      contour_area: 50
      mask:
        # ignore date/time at top
        - 0.321,0.051,0,0.049,0,0,0.321,0
        # ignore neighbours
        - 0.234,0.312,0.132,0.056,0,0.056,0,0.608
        # ignore footpath
        - 0.317,0.054,0.433,0.105,0.52,0.091,0.761,0.187,0.9,0.273,1,0.342,1,0,0.316,0
        # ignore road
        - 0.151,0.105,0.222,0.062,0.223,0.001,0.09,0.004
    objects:
      filters:
        car:
          mask: 0.163,0.132,0.285,0.38,0.197,0.543,0,0.716,0,0.548,0,0.067,0.128,0.056
  driveway_right:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.169:554/ch01.264
          roles:
            - record
        - path: rtsp://192.168.4.169:554/ch01_sub.264
          roles:
            - detect
    review:
      alerts:
        labels:
          - car
          - person
        required_zones:
          - drive
      detections:
        labels:
          - person
          - car
        required_zones:
          - drive
    zones:
      drive:
        coordinates: 0,0.408,0.107,0.217,0.217,0.06,0.508,0.051,0.8,0.088,0.893,0,1,0,1,1,0,0.999
        objects:
          - person
          - car
        # filters:
        #   person:
        #     threshold: 0.7 # 70% sure its a person
    motion:
      threshold: 40
      mask:
        # ignore date/time at top
        - 0.321,0.051,0,0.049,0,0,0.321,0
        # ignore neighbours + road
        - 0,0.35,0.245,0,-0.001,0.001

  garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.210:554/ch01.264
          roles:
            - record
        - path: rtsp://192.168.4.210:554/ch01_sub.264
          roles:
            - detect
    review:
      alerts:
        labels:
          - person
        required_zones:
          - back_door
          - patio
      detections:
        labels:
          - person
        required_zones:
          - back_door
          - patio
    zones:
      back_door:
        coordinates: 0.028,0.999,0.666,0.758,0.806,0.5,1,0.854,1,1
        objects:
          - person
      patio:
        coordinates: 0,1,0.001,-0.001,0.689,0,0.705,0.033,0.567,0.063,0.803,0.494,0.659,0.751
        objects:
          - person
    motion:
      mask:
        # ignore date/time at top
        - 0.321,0.051,0,0.049,0,0,0.321,0

go2rtc:
  streams:
    gate_doorbell:
      - "ffmpeg:http://192.168.5.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASS}#video=copy#audio=copy#audio=opus"
      - "rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASS}@192.168.5.72/h264Preview_01_sub"
      # - "rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASS}@192.168.5.72/Preview_01_sub"
    gate_doorbell_sub:
      - "ffmpeg:http://192.168.5.72/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASS}"
  # ffmpeg:
  #   volume: "-af \"volume=30dB\""
  webrtc:
    candidates:
      - 192.168.6.139:8555
      - stun:8555
```

### Relevant Frigate log output

```shell
no error
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)","width":3840,"height":2160,"avg_frame_rate":"0/0"},{"codec_long_name":"PCM mu-law / G.711 mu-law","avg_frame_rate":"0/0","bit_rate":"64000"},{"avg_frame_rate":"0/0"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)","width":720,"height":576,"avg_frame_rate":"5/1"},{"codec_long_name":"PCM mu-law / G.711 mu-law","avg_frame_rate":"0/0","bit_rate":"64000"},{"avg_frame_rate":"0/0"}]}}]
```

### Frigate stats

```json
{"cameras":{"gate_doorbell":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":421,"capture_pid":453,"ffmpeg_pid":807368,"audio_rms":0.0,"audio_dBFS":0.0},"driveway_left":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.1,"detection_enabled":true,"pid":424,"capture_pid":456,"ffmpeg_pid":719169,"audio_rms":0.0,"audio_dBFS":0.0},"driveway_right":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.2,"detection_enabled":true,"pid":435,"capture_pid":460,"ffmpeg_pid":697393,"audio_rms":0.0,"audio_dBFS":0.0},"garden":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":443,"capture_pid":467,"ffmpeg_pid":714535,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":8.76,"detection_start":0.0,"pid":368}},"detection_fps":0.3,"gpu_usages":{"intel-vaapi":{"gpu":"1.24%","mem":"-%","clients":{"697393":"2.45%","714535":"2.16%","719169":"0.88%","807368":"8.34%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"22.5","mem":"28.2"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"17":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"85":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"91":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"95":{"cpu":"2.2","cpu_average":"2","mem":"0.2","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"105":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"4.5","cpu_average":"4","mem":"3.6","cmdline":"python3 -u -m frigate"},"113":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: master process nginx"},"160":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"nginx: worker process"},"162":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"nginx: worker process"},"195":{"cpu":"0.1","cpu_average":"0","mem":"0.3","cmdline":"nginx: worker process"},"196":{"cpu":"0.1","cpu_average":"0","mem":"0.2","cmdline":"nginx: worker process"},"197":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"307":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"352":{"cpu":"1.8","cpu_average":"1","mem":"1.4","cmdline":"frigate.recording_manager"},"359":{"cpu":"0.8","cpu_average":"0","mem":"1.1","cmdline":"frigate.review_segment_manager"},"368":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.detector.coral"},"370":{"cpu":"0.2","cpu_average":"0","mem":"4.3","cmdline":"frigate.embeddings_manager"},"407":{"cpu":"1.3","cpu_average":"1","mem":"1.2","cmdline":"frigate.output       "},"421":{"cpu":"1.7","cpu_average":"1","mem":"1.2","cmdline":"frigate.process:gate_doorbell"},"424":{"cpu":"2.4","cpu_average":"1","mem":"1.2","cmdline":"frigate.process:driveway_left"},"435":{"cpu":"3.2","cpu_average":"2","mem":"1.4","cmdline":"frigate.process:driveway_right"},"443":{"cpu":"1.7","cpu_average":"1","mem":"1.2","cmdline":"frigate.process:garden"},"453":{"cpu":"1.3","cpu_average":"1","mem":"1.1","cmdline":"frigate.capture:gate_doorbell"},"456":{"cpu":"1.2","cpu_average":"1","mem":"1.1","cmdline":"frigate.capture:driveway_left"},"460":{"cpu":"1.1","cpu_average":"1","mem":"1.1","cmdline":"frigate.capture:driveway_right"},"467":{"cpu":"1.1","cpu_average":"1","mem":"1.1","cmdline":"frigate.capture:garden"},"486":{"cpu":"3.0","cpu_average":"3","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.4.169:554/ch01.264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_right@%Y%m%d%H%M%S%z.mp4"},"487":{"cpu":"0.0","cpu_average":"2","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.5.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b472f8bb25ffefc01882ef0b5c873c29"},"488":{"cpu":"2.6","cpu_average":"2","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.4.210:554/ch01.264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4"},"489":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"499":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -threads 1 -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"506":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -threads 1 -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"513":{"cpu":"0.1","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -threads 1 -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"520":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"489586":{"cpu":"0.1","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.5.72/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/abea0c9f567465f7d2ec81ab857e7859"},"490262":{"cpu":"1.0","cpu_average":"1","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gate_doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/gate_doorbell@%Y%m%d%H%M%S%z.mp4"},"490264":{"cpu":"5.1","cpu_average":"4","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.5.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b472f8bb25ffefc01882ef0b5c873c29"},"490307":{"cpu":"2.9","cpu_average":"3","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-87e7b62 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.4.62:554/ch01.264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_left@%Y%m%d%H%M%S%z.mp4"},"697393":{"cpu":"3.6","cpu_average":"3","mem":"0.3","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.4.169:554/ch01_sub.264 -r 5 -vf fps=5,scale_vaapi=w=720:h=576,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"714535":{"cpu":"2.5","cpu_average":"2","mem":"0.3","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.4.210:554/ch01_sub.264 -r 5 -vf fps=5,scale_vaapi=w=720:h=576,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"719169":{"cpu":"3.4","cpu_average":"3","mem":"0.3","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.4.62:554/ch01_sub.264 -r 5 -vf fps=5,scale_vaapi=w=720:h=576,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"807368":{"cpu":"4.4","cpu_average":"4","mem":"0.3","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-87e7b62 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gate_doorbell_sub -r 5 -vf fps=5,scale_vaapi=w=896:h=672,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"807370":{"cpu":"1.3","cpu_average":"1","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.5.72/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/abea0c9f567465f7d2ec81ab857e7859"},"815578":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 9999"},"847610":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":238282,"version":"0.15.0-87e7b62","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":3844576.5,"used":632846.6,"free":3016363.1,"mount_type":"ext4"},"/media/frigate/clips":{"total":3844576.5,"used":632846.6,"free":3016363.1,"mount_type":"ext4"},"/tmp/cache":{"total":1024.0,"used":21.9,"free":1002.1,"mount_type":"tmpfs"},"/dev/shm":{"total":1024.0,"used":138.5,"free":885.5,"mount_type":"tmpfs"}},"temperatures":{"apex_0":51.8},"last_updated":1737370849},"processes":{"recording":{"pid":352},"review_segment":{"pid":359},"go2rtc":{"pid":95},"embeddings":{"pid":370}}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
I actually use kubernetes helm chart to deploy but it is not an option
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Some chinese camera my friend has imported

### Screenshots of the Frigate UI's System metrics pages

![{905904D9-A242-42BA-B281-457B7F4EAFC1}](https://github.com/user-attachments/assets/6758c5ad-1ad6-42e8-8a87-d4fd4c4aa8d0)
