### DISCUSSION TITLE
Help with docker compose - Coming from the community scripts to the proper way to install

### DISCUSSION THREAD

**Discussion by Archy54** [blakeblackshear/frigate#16079] [Ask A Question]
Proxmox running community script docker-compose lxc privileged for just this container with portainer, I have no idea how to use docker sadly
I believe I pulled both the latest beta and the stable images to the /opt/frigate/ folder but no idea where they are stored (still learning)

I dunno if i created these files in the right place or right settings. The config.yaml was working fine on community/ttecks frigate script before. 
  
/opt/frigate/config.yml

```
mqtt:
  enabled: true
  host: 192.168.x.x
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: secret

cameras:
  Car_Port_North:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://secret@192.168.x.x0:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://secret@192.168.x.x0:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      min_initialized: 2
      max_disappeared: 25
    zones:
      CarPortNorthZone:
        coordinates: 0,0,1,0,0.991,0.603,1,0.838,1,1,0,1
        loitering_time: 0
        inertia: 3
    review:
      alerts: {}
    motion:
      mask:
        - 0.994,0.328,0.969,0.374,0.953,0.438,0.956,0.538,0.953,0.731,0.959,0.879,0.962,0.995,0.999,0.997
        - 0.227,0.082,0.209,0.226,0.013,0.39,0.006,0.074,0.202,0.028
        - 0.685,0.036,0.685,0.09,0.963,0.095,0.962,0.036
        - 0.937,0.246,0.858,0.192,0.851,0.092,0.933,0.003,0.996,0.005,0.994,0.285
  Shed:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://secret@192.168.x.x1:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://secret@192.168.x.x1:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

    zones:
      ShedZone:  # Rename this zone to ShedZone to avoid conflict with the camera name
        coordinates: 0,0,1920,0,1920,1080,0,1080  # Define the zone coordinates
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      min_initialized: 2
      max_disappeared: 25

    motion:
      mask:
        - 0.968,0.032,0.676,0.031,0.678,0.103,0.967,0.105
        - 0.377,0.146,0.678,0.141,0.672,0.159,0.377,0.172
  Laundry:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://secret@192.168.x.x2:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://secret@192.168.x.x2:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

    zones:
      LaundryZone:
        coordinates: 0.267,0.356,0.603,0.228,0.873,0.092,0.867,0.579,0.824,1,0,1,0,0.49
        inertia: 3
        loitering_time: 0
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      min_initialized: 2
      max_disappeared: 25

    motion:
      mask:
        - 0.001,0.498,0.09,0.456,0.14,0.415,0.63,0.221,0.665,0.205,0.811,0.215,0.831,0.128,0.76,0,0.461,0,0.135,0,0.001,0
        - 0.68,0.034,0.959,0.033,0.96,0.095,0.681,0.1

  BackYard:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://secret@192.168.x.x3:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://secret@192.168.x.x3:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      min_initialized: 2
      max_disappeared: 25

    motion:
      mask:
        - 0.655,0,0.613,0.215,0.92,0.451,0.96,0.308,0.963,0
        - -0.001,0.164,0.034,0.179,0.073,0.154,0.097,0.254,0,0.495
  Patio:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://secret@192.168.x.x4:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://secret@192.168.x.x4:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      min_initialized: 2
      max_disappeared: 25

    motion:
      mask: 0.962,0.097,0.681,0.103,0.681,0.036,0.963,0.028

    zones:
      PatioZone:
        coordinates: 0.001,0,0,1,1,1,1,0
        loitering_time: 0
  Front:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://secret@192.168.x.x5:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://secret@192.168.x.x5:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      min_initialized: 2
      max_disappeared: 25

    motion:
      mask: 
        0.452,0.005,0.447,0.108,0.437,0.169,0.462,0.274,0.455,0.326,0.47,0.338,0.486,0.292,0.506,0.323,0.508,0.382,0.519,0.408,0.55,0.441,0.557,0.485,0.528,0.608,0.659,0.795,0.728,0.538,0.782,0.503,0.805,0.441,0.812,0.356,0.832,0.474,0.855,0.51,0.865,0.585,0.885,0.613,0.831,0.815,0.87,0.915,0.891,0.967,0.94,0.969,0.996,0.913,0.996,0.008
    zones:
      FrontZone:
        coordinates: 0,0,1,0,0.996,0.997,0,1
        loitering_time: 0
        inertia: 3
objects:
  track:
    - person
    - cat
    - dog
    - bicycle
    - motorcycle
  filters:
    person:
      min_score: 0.8  # Require 80% confidence for detections
    cat:
      min_score: 0.7  # Require 70% confidence for detections
    dog:
      min_score: 0.7  # Require 70% confidence for detections
    bicycle:
      min_score: 0.75  # Require 75% confidence for detections
    motorcycle:
      min_score: 0.75  # Require 75% confidence for detections
record:
  enabled: true
  retain:
    days: 14
    mode: all
  storage:
    local:
      path: /mnt/frigate_cctv_hdd/recordings
  events:
    pre_capture: 5
    post_capture: 10
  sync_recordings: true


detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.14

logger:
  logs:
    frigate.record.maintainer: debug

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
#  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70
```
  
```

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    volumes:
      - /opt/frigate/config.yml:/config/config.yml:ro
      - /opt/frigate/config:/config
      - /mnt/frigate_cctv_hdd/recordings:/media/frigate/recordings
      - /mnt/frigate_cctv_hdd/recordings:/media/frigate/clips
      - /mnt/frigate_cctv_hdd/recordings:/media/frigate/exports
      - /opt/frigate:/opt/frigate:rw  # Ensure :rw for read-write access
      - /opt/frigate:/tmp/cache
      - /opt/frigate:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"  # Frigate Web UI
      - "1935:1935"  # RTMP stream
      - "8554:8554"  # RTSP restream
      - "8555:8555"  # WebRTC
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128  # Intel iGPU device
    shm_size: "400mb"  # Shared memory for FFmpeg
    privileged: true


```
    
    docker logs keep repeating a loop
```
s6-rc: info: service nginx: stopping
s6-rc: info: service certsync-log: stopping
s6-rc: info: service certsync-log successfully stopped
2025-01-22 14:07:41.403986606  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2025-01-22 14:08:45.637604414  [INFO] Preparing Frigate...
2025-01-22 14:08:45.638449361  [INFO] Starting NGINX...
2025-01-22 14:08:45.639110524  [INFO] Preparing new go2rtc config...
2025-01-22 14:08:45.642847391  [INFO] Starting Frigate...
2025-01-22 14:08:45.656030801  /usr/bin/python3: No module named frigate
2025-01-22 14:08:45.659760713  [INFO] Service Frigate exited with code 1 (by signal 0)
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 11, in <module>
    from frigate.const import BIRDSEYE_PIPE  # noqa: E402
ModuleNotFoundError: No module named 'frigate'
2025-01-22 14:08:45.664668354  [INFO] The go2rtc service exited with code 1 (by signal 0)
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
2025-01-22 14:08:45.679101703  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service certsync: stopping
2025-01-22 14:08:45.683338939  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2025-01-22 14:08:45.683929091  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
s6-rc: info: service certsync successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service certsync-log: stopping
s6-rc: info: service certsync-log successfully stopped
2025-01-22 14:08:45.719712748  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

I'm not exactly sure from the documentation on how to get this setup the normal way. I believe the mount point is passed through fully, from a .conf file for lxc including the 186 or 196 for coral and the usb which i see in the lxc as lsusb. 

I'd like to eventually add qsv as it's a 14700k. Furtherest I got was the interface but buttons clicking didn't goto pages. Now I straight up just don't get to the ip address, I'm guessing it's rebooting the docker. I just can't figure out why. I also wasn't sure what was needed in docker-compose - Will frigate automatically create a file structure and what do I need to tell it to run the mount point for recordings and nvme for rootfs? 1gig of tmp ram storage?

I've tried beta and stable so far. Many hours with chatgpt trying to figure it out.
