### DISCUSSION TITLE
[Camera Support]: How to address zones using a PTZ camera

### DISCUSSION THREAD

**Discussion by dz4news** [blakeblackshear/frigate#16076] [Camera Support] [answered]
### Describe the problem you are having

I have a PTZ camera on the front of my house that views my frontyard and can also view my driveway. The PTZ has a zone named "frontyard". I also have automations that alert when a person is in the frontyard. This is a view of the zone.
<img width="971" alt="Screenshot 2025-01-21 at 2 28 50 PM" src="https://github.com/user-attachments/assets/e6d3285f-e931-4d9a-9142-e9f6f0113cc6" />
I also use a spotter camera that points at my gate and a zone for the street. When a car enters the zone for a set period the PTZ rotates and zooms into the gate until the street zone becomes unoccupied,  then returns to the preset. 
<img width="993" alt="Screenshot 2025-01-21 at 2 46 04 PM" src="https://github.com/user-attachments/assets/6ff3580e-cb2c-43ef-b339-7edcbdc35814" />

My issue is that when the PTZ turns, the zone turns with it and I get a notification because of the situation below. 
<img width="752" alt="Screenshot 2025-01-21 at 2 29 39 PM" src="https://github.com/user-attachments/assets/b2eed4cd-f128-4b60-a9ad-a01bca5aeef1" />
This is basically showing there is a person in the frontyard, when they are actually at the gate.

This is expected behavior? If not, how do I address it?

### Version

0.15.0-83ac42c

### Frigate config file

```yaml
...
cameras:
  ptz_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.xxx:8554/ptz_cam_sub
          roles:
            - detect
            - audio
        - path: rtsp://192.168.0.xxx:8554/ptz_cam
          roles:
            - record
    objects:
      filters:
        bird:
          min_score: 0.90
        car:
          min_score: 0.80
        license_plate:
          min_score: 0.75
        amazon:
          min_score: 0.75
        fedex:
          min_score: 0.75
        ups:
          min_score: 0.75
        cat:
          min_score: 0.85
          threshold: 0.7
        dog:
          min_score: 0.80
          threshold: 0.5
        deer:
          min_score: 0.80
        person:
          min_score: 0.85
          threshold: 0.7
    onvif:
      host: 192.168.0.
      port: 80
      user:
      password: 
      autotracking:
        enabled: true
        calibrate_on_startup: false
        zooming: absolute
        zoom_factor: 0.2
        track:
          - car
          - person
          - dog
          - deer
        required_zones:
          - frontyard
          - street
        return_preset: home
        timeout: 10
        movement_weights: 0.25, 1.0, 1.5307116508483887, 1.6932586844249435, 0.5355383619185421
    live:
      stream_name: ptz_cam
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

EmpireTech PTZ1A4M-4X-S2 1/2.8" CMOS 4MP 4x Starlight IR 2.8mm–12mm Vari-Focal PTZ

### Screenshots of the Frigate UI's System metrics pages

n/a
