### DISCUSSION TITLE
[Config Support]: Pre and post capture - curious question

### DISCUSSION THREAD

**Discussion by italicize9610** [blakeblackshear/frigate#16085] [Config Support]
### Describe the problem you are having

I have a curious question. My set up doesn't have a lot of space (just 512gb), so I try not to do continuous recording. I am having trouble figuring out why pre and post capture works when my config is this. by works i mean that exported footage starts 10-20 seconds before the object enters the camera view.

```
record:
  enabled: true
  retain:
    days: 0.042
    mode: all
  alerts:
    retain:
      days: 7
      mode: all
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 7
      mode: all
    pre_capture: 10
    post_capture: 10
```

but it does not work when my config is this (i just removed the 1 hour of continuous recording). exported footage starts at the moment the object enters the camera view (not referring to the UI).

```
record:
  enabled: true
  alerts:
    retain:
      days: 7
      mode: all
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 7
      mode: all
    pre_capture: 10
    post_capture: 10
```

everything works fine, i would just like to refine my understanding of how retention works.

### Version

0.15 beta 5

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 0.042
    mode: all
  alerts:
    retain:
      days: 7
      mode: all
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 7
      mode: all
    pre_capture: 10
    post_capture: 10
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

**Comment by NickM-27** [comment]
Realistically it should be the same but perhaps something else in the config is affecting it. 

The reason the continuous recording makes a difference is that the segments are always kept and the review activity is not checked.

**Reply by italicize9610** [reply]
here's my full config, it's very simple and everything is global.

```
##---STREAMS---##

go2rtc:
  streams:
... this part works fine, will redact

##---GLOBAL SETTINGS---##

mqtt:
... this part works fine, will redact

detectors:
  coral:
    type: edgetpu
    device: pci

model:
  path: plus://XXX

ffmpeg:
  input_args: preset-rtsp-generic
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

record:
  enabled: true
#  retain:
#    days: 0.042
#    mode: all
  alerts:
    retain:
      days: 7
      mode: all
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 7
      mode: all
    pre_capture: 10
    post_capture: 10

detect:
  enabled: true
  width: 1280
  height: 960
  fps: 5

snapshots:
  enabled: true
  retain:
    default: 7

objects:
  track:
    - person
    - dog
  filters:
    person:
      min_score: 0.75
      threshold: 0.80
    dog:
      min_score: 0.75
      threshold: 0.80

version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large

review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - dog

##---CAMERA SETTINGS---##

cameras:
###### DOORBELL CAMERA ######
  doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - record
    motion:
      mask: 0.137,0.962,0.138,0.991,0.245,0.991,0.245,0.962
      threshold: 45
      contour_area: 20
      improve_contrast: true
  
  ###### UPSTAIRS CAMERA ###### 
  e1upstairs: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/e1upstairs
          roles:
            - record
            - detect
    motion:
      mask: 0.137,0.962,0.138,0.991,0.245,0.991,0.245,0.962

###### DOWNSTAIRS CAMERA ###### 
  e1downstairs: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/e1downstairs
          roles:
            - detect
            - record
    motion:
      mask: 0.137,0.962,0.138,0.991,0.245,0.991,0.245,0.962
    objects:
      filters:
        person:
          mask: 0.844,0.333,0.827,0.331,0.826,0.359,0.843,0.363

###### LIVING ROOM CAMERA ###### 
  e1livingroom: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/e1livingroom
          roles:
            - record
            - detect
    motion:
      mask: 0.137,0.962,0.138,0.991,0.245,0.991,0.245,0.962
```

i don't see any overriding from the camera level. also - could you clarify what you meant by "the review activity is not checked"?

in the second config (without continuous record), how many seconds of footage is stored in ram or cache? or maybe i'm asking the wrong question. i am wondering if without continuous record the pre-capture segments are discarded by the time the event finishes so there's nothing to stitch together.

**Reply by NickM-27** [reply]
Let's back up, when you say exporting the recordings what do you mean exactly?

> or maybe i'm asking the wrong question. i am wondering if without continuous record the pre-capture segments are discarded by the time the event finishes so there's nothing to stitch together.

it does consider the pre capture in when to delete segments from cache

**Reply by italicize9610** [reply]
I mean I navigate to the review menu, click on the event, click export, select from timeline, then I go to the export menu and download it. and then I review on vlc. not sure why it isn't working though without continuous recordings though.

**Reply by NickM-27** [reply]
There will be some variability just depending on when the segments start and end. You can use the preview feature to watch the recordings. It will be good to know the exact time cutoff.

**Reply by italicize9610** [reply]
@NickM-27 

with record set to 1 hour (0.042 days), I get pre and post captures that range between 10-20 seconds. seems about right.

without record retain, there's almost no pre or post captures (even though the default is 5 you would expect between 0-10 seconds).

under record->retain->mode, do I need to set it as all? the default is active objects, but if my days=0 then it doesn't matter right?

**Reply by NickM-27** [reply]
> under record->retain->mode, do I need to set it as all? the default is active objects, but if my days=0 then it doesn't matter right?

right

with that said I believe in your case this is a bug, not in the retention but actually in the cleanup where the pre_capture is not checked which can lead to the segment being deleted

**Reply by italicize9610** [reply]
got it. in beta 3 I commented in a post about pre and post captures not working which you then fixed. not sure if it's related. is there any information I can provide you with to help you resolve this bug?

I'm running haos+addon, system is all good with 12gb of memory and only 4-5gb used at any time. shouldn't be a cache size issue. no errors in the logs too, all clean as far as I can see. uptime other than restarts is 100%, all cameras connected via PoE.

**Comment by Polv89** [comment]
I have a similar issue, i havethis configuration:
```
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  Retro: # <------ Nome della telecamera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://.........//h264Preview_01_sub # <----- Stream sub per la rilevazione
          roles:
            - detect
        - path: rtsp://.........//h264Preview_01_Main # <----- Stream principale per la visualizzazione e la registrazione
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480

  Dietro_casa: # <------ Nome della telecamera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://.........//h264Preview_01_sub  # <----- Stream sub per la rilevazione
          roles:
            - detect
        - path: rtsp://.........//h264Preview_01_Main # <----- Stream principale per la visualizzazione e la registrazione
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480

  Ingresso: # <------ Nome della telecamera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://.........// # <----- Stream sub per la rilevazione
          roles:
            - detect
        - path: rtsp://.........// # <----- Stream principale per la visualizzazione e la registrazione
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 3
      mode: motion
  detections:
    retain:
      days: 3
      mode: motion


go2rtc:
  streams:
    retro:
      - rtsp://.........//h264Preview_01_sub
    dietro_casa:
      - rtsp://.........//h264Preview_01_sub
    ingresso:
      - rtsp://.........//


version: 0.15-1
```
when i go to Review => alert, i see some videos, when i open others i have "No recording founds for this time."
In review=>detection i haven't anything, only this message => There are no detections to review
In motion i have some videos, but i can't play all of them...
What's wrong?
thanks a lot
