### DISCUSSION TITLE
Using Frigate with Zoneminder (24/7 low resolution recording with high resolution event archiving)

### DISCUSSION THREAD

**Discussion by substeeze** [blakeblackshear/frigate#16082] [Show and tell]
As a long time user of Zoneminder moving to Frigate, I'm really liking the UI and excellent object detection that makes reviewing events a breeze.

But there's not a sensible way to have low resolution 24/7 recording with only events saved in high resolution. Sure, you can add the same camera twice into Frigate and set different retention policies, but it does clutter the UI - particularly the event review page (where you see everything twice unless you filter it), plus detection is running twice for the same camera and this is not cpu efficient.

It's also not straightforward to have the low resolution recordings on a SSD for fast access during review, but the high resolution on an HDD for archiving.

So I looked into whether I could get Frigate to initiate a recording on Zoneminder using a HomeAssistant automation. I'm pleased to report this is possible and it works very well. The implementation is possibly not the most elegant, so I'm keen to hear if there's a better way. It assumes you already have MQTT working between HA and Frigate.

For reference, this is what I have done...

1. Frigate is configured to use the low resolution camera sub-stream for both detection and recording.
2. Zoneminder is configured to use the high resolution camera stream for recording (then, under 'function' on the console page, set camera to Nodect and disable analysis and decoding. Then under Source/Storage choose your HDD storage area, disable save jpegs and video writer set to 'Camera Passthrough', with audio if you want it).
3. Under Zoneminder/Options/System, scroll down and ensure OPT_TRIGGERS is enabled. You will need to restart zoneminder (maybe from the command line). If you want to double check it's enabled, run htop on the command line and check to see the process zm_trigger.pl is running.
4. Then, in the command line, sudo nano the Home Assistant configuration.yaml and add the following...
```yaml
switch:
  platform: telnet
  switches:
    zm_trigger:
      resource: 'localhost'
      port: 6802
      command_on: '1|on|123|textstring1|textstring2'
      command_off: '1|off|123|textstring1|textstring2'
``` 
replace the '1' with the id number of your camera in Zoneminder. You can change the name zm_trigger to a more suitable name. If you have multiple cameras, you will need one of these switch definitions per camera. 123 is the alarm number assigned in ZM and textstring1/2 is just a description you can add. They don't matter for functionality.
5. Restart HomeAssistant and you should now see you have a zm_trigger switch entity.
6. Under HomeAssistant / Settings / Automations and Scenes, click create Automation and add the following...
```yaml
alias: Trigger Zoneminder Recording on Frigate Event
description: using MQTT frigate/reviews topic
triggers:
  - alias: Trigger on frigate/reviews topic
    topic: frigate/reviews
    variables:
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      type: "{{ trigger.payload_json['type'] }}"
    trigger: mqtt
conditions:
  - alias: Limit to a specific camera
    condition: template
    value_template: "{{ camera == \"drive_cam\" }}"
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ type == \"new\" }}"
        sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.zm_trigger
      - conditions:
          - condition: template
            value_template: "{{ type == \"end\" }}"
        sequence:
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.zm_trigger
mode: parallel
trace:
  stored_traces: 100
max: 10
``` 
Replace drive_cam with your Frigate camera name and zm_trigger with the name of the switch created in the HomeAssistant configuration.yaml file. For multiple cameras, you can just use multiples of this automation, modified with the appropriate camera and switch names.
