### DISCUSSION TITLE
Questions About Configuration File (ffmpeg, birdseye, etc.)

### DISCUSSION THREAD

**Discussion by neomikanagi** [blakeblackshear/frigate#16080] [Ask A Question] [answered]
Hello, I’m from Japan and I’m using a translation tool for communication. Please forgive any potential inaccuracies in my expression.

Thank you for taking the time to look at my questions. Before I proceed, I’ve listed my configuration below but omitted what I consider redundant or unnecessary parts.

```
version: 0.14

mqtt:
  enabled: true
  host: 192.168.1.31
  port: 1883

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30

detect:
  fps: 5
  width: 1280
  height: 720

go2rtc:
  streams:
    Foyer:
      - onvif://admin:pass@ip:2020
    Foyer_Sub:
      - rtsp://admin:pass@ip/stream2
    P:
      - rtsp://admin:pass@ip:554/h265/ch1/main/av_stream
    P_Sub:
      - rtsp://admin:pass@ip:554/h265/ch1/sub/av_stream
    IMOU:
      - onvif://admin:pass@ip
    IMOU_Sub: 
      - rtsp://admin:pass@ip/cam/realmonitor?channel=1&subtype=1

cameras:
  Foyer: #tapo
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Foyer
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Foyer_Sub
          roles:
            - detect
          hwaccel_args: preset-vaapi
  P: #ezviz
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/P
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/P_Sub
          roles:
            - detect
          hwaccel_args: preset-vaapi

  IMOU: #dahua
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/IMOU
          roles:
            - record
          hwaccel_args: preset-intel-qsv-h265
        - path: rtsp://127.0.0.1:8554/IMOU_Sub
          roles:
            - detect
          hwaccel_args: preset-vaapi

camera_groups:
  birdseye:
    order: 1
    icon: LuBird
    cameras:
      - birdseye
```
      
Questions:

Q1:
I prefer to use the birdseye mode instead of Allcameras because I like the default screen to remain blank until motion or events are detected. However, when using Allcameras, clicking on a specific camera shows a high-quality, low-latency stream.
In contrast, with birdseye, the camera resolution appears to be the substream resolution, with significant delay and low FPS when motion or events are detected.
Is there an issue with my configuration or usage, or is this behavior expected?

Q2:
In the ffmpeg settings, I use preset-intel-qsv-h264. However, in the go2rtc settings, I’ve configured it to read streams encoded in h265.
Is this configuration correct? I’ve rarely seen examples online using preset-intel-qsv-h265. Should I set everything to h264 instead?

Q3:
For the substream settings under the cameras configuration, if I don’t specify hwaccel_args: preset-vaapi, ffmpeg keeps restarting, and I encounter green screens.
Since setting hwaccel_args: preset-vaapi resolves the issue and doesn’t cause significant system resource usage, can I simply continue using this configuration without investigating further?

If anything is unclear or additional details are needed, please let me know. Thank you for your support!
