### DISCUSSION TITLE
[Support]: Setting threshold using 2 decimal numbers make frigate ignoring it

### DISCUSSION THREAD

**Discussion by peppe-terra** [blakeblackshear/frigate#16086] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I'm using a model built with Frigate+.

I try to set a decimal value for threshold using a value with two decimal number (0.85), but I get true positives under the default threshold value, which is 70% (e.g. 56%).

If I set a value with one decimal number (0.8) the threshold work as expcected.

### Steps to reproduce

1. Use a model built with Frigate+.
2. Set a threshold value with two decimal numbers (e.g. 0.85)
3. Wait for object revelation for the type you setted the threshold for.
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
auth:
  enabled: true

mqtt:
  host: 192.168.1.29
  user: hidden
  password: hidden

snapshots:
  enabled: true

detectors:
  ov:
    type: openvino
    device: GPU

model:
  path: plus://9e9082428a404f6917af731cbfdc2b3a

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:

  SantaMarina: # <--- this will be changed to your actual camera later
    enabled: true

    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.105:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect

      output_args:
        record: preset-record-generic-audio-aac

    onvif:
      host: 192.168.1.105
      port: 80
      user: admin
      password: pass

    objects:
      filters:
        person:
          threshold: .75
          mask: 0.349,0.427,0.413,0.421,0.401,0.213,0.345,0.218
          min_area: 6000
        cow:
          min_area: 7000
        car:
          threshold: 0.85    
    motion:
      mask: 0.873,0.041,0.875,0.119,0.974,0.112,0.974,0.046

  Ingresso:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.104:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect

      output_args:
        record: preset-record-generic-audio-aac

    onvif:
      host: 192.168.1.104
      port: 80
      user: admin
      password: pass

    objects:
      filters:
        car:
          threshold: 0.85
          mask: 0,0.45,0.429,0.395,0.618,0.988,0,1  
        sheep:
          min_area: 6000
        person:
          mask: 0.031,0.689,0.074,0.553,0.135,0.678,0.113,0.847
    motion:
      mask:
        - 0.875,0.056,0.96,0.056,0.961,0.094,0.878,0.096
        - 0.48,0,0.476,0.4,0.787,0.748,0.932,0.007
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
 
objects:
  track:
    - person
    - car
    - dog
    - sheep
    - cow
    - cat
    - goat

go2rtc:
  streams:
    SantaMarina: # <- for RTSP streams
      - rtsp://admin:pass@192.168.1.105:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <- stream which supports video & aac audio
  # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)   
    Ingresso:
      - rtsp://admin:pass@192.168.1.104:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 3
      mode: motion
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1 
    shm_size: "256mb"
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - ./letsencrypt/live/host.mydomain.net:/etc/letsencrypt/live/frigate:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971"
    devices:
      - /dev/dri/renderD128
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    secrets:
      - PLUS_API_KEY
    environment:
      - SECRET_FILE=/run/secrets/my_secret

secrets:
  PLUS_API_KEY:
    file: ./apiKey
```

### Relevant Frigate log output

```shell
No relevant output
```

### Relevant go2rtc log output

```shell
No relevant output
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Imou 

### Screenshots of the Frigate UI's System metrics pages

![immagine](https://github.com/user-attachments/assets/d6ffe752-0879-428f-8e55-71a0e183816e)
