### DISCUSSION TITLE
[Bug]: record.events fails validation

### DISCUSSION THREAD

**Discussion by masterkain** [blakeblackshear/frigate#16100] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

```
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 199, in config_save
    FrigateConfig.parse_yaml(new_config)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 689, in parse_yaml
    return cls.parse(config_yaml, is_json=False, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 685, in parse
    return cls.parse_object(config, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 695, in parse_object
    return cls.model_validate(
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
record.events
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;pre_capture&#39;: 5, &#39;post_...: 10, &#39;mode&#39;: &#39;motion&#39;}}, input_type=CommentedMap]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
```

### Steps to reproduce

```
      record:
        enabled: true
        retain:
          days: 0
          mode: all
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 10
            mode: motion
```

### Version

0.15.0-beta7-tensorrt

### Frigate config file

```yaml
mqtt:
        enabled: false

      detectors:
        tensorrt:
          type: tensorrt
          device: 0

      model:
        model_type: yolox
        path: /config/model_cache/tensorrt/yolov7-320.trt
        width: 320
        height: 320
        input_pixel_format: rgb
        input_tensor: nchw

      go2rtc:
        streams:
          tago:
            - rtsp://192.168.1.11:554/11

      record:
        enabled: true
        retain:
          days: 0
          mode: all
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 10
            mode: motion

      ui:
        time_format: 24hour
        timezone: Europe/Rome

      cameras:
        tago:
          enabled: true
          ffmpeg:
            hwaccel_args: preset-nvidia
            inputs:
              - path: rtsp://192.168.1.11:554/12
                roles:
                  - detect
              - path: rtsp://127.0.0.1:8554/tago
                input_args: preset-rtsp-restream
                roles:
                  - record
            output_args:
              record: preset-record-generic-audio-copy

          detect:
            fps: 5
            width: 640
            height: 352
            max_disappeared: 25

          live:
            height: 640
            quality: 1

          objects:
            track:
              - person
            filters:
              person:
                min_area: 5000
                max_area: 100000
                threshold: 0.7

          snapshots:
            enabled: true
            bounding_box: true
            timestamp: true
            retain:
              default: 3
              objects:
                person: 7

          webui_url: http://192.168.1.11/web/admin.html
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

-

### Screenshots of the Frigate UI's System metrics pages

-
