### DISCUSSION TITLE
[Config Support]:  Map storage to shared NAS Drive (Folder)

### DISCUSSION THREAD

**Discussion by dwdonnelly** [blakeblackshear/frigate#16103] [Config Support] [answered]
### Describe the problem you are having

I am not able to have Frigate save recordings to the NAS Shared folder.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false
# The following code is used to reset the Frigate password on reboot and comes from: 
# https://github.com/blakeblackshear/frigate/blob/dev/docs/docs/configuration/authentication.md#resetting-admin-password.

# Uncomment, save and reboot.
# Then navigate to the frgate-nvr folder and run the command: docker compose logs | grep Password:
# This command comes from https://pimylifeup.com/raspberry-pi-frigate-nvr/.
# This will show you the new system generated password.

#auth:
#  reset_admin_password: True

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg: #move the ffmpeg stuff to global level when using go2rtc
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    Front_Door: #Put in the IP and add user pass to the camera's rtsp info.
      - "ffmpeg:http://192.168.0.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"
      - rtsp://UID:pwd:8554/h264Preview_01_main
#    Front_Door_sub:
#      - "ffmpeg:http://192.168.0.42:8554/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"
    Back_Door:
      - rtsp://UID:pwd:554/h265Preview_01_main

cameras:
  Front_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door #this is a loopback ip to access the go2rtc stream, after the "/" is the camera name, defined in the go2rtc section. 8554 is the port used for rtsp restream.
          hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration
          roles:
            - record
#        - path: rtsp://127.0.0.1:8554/Front_Door_sub
#          roles:
#            - detect
    detect:
      enabled: True # Detection is enabled
      width:  1280   #896 #correct sub stream res
      height: 720    #672 #correct sub stream res
      fps: 5 #limit the fps that the detector has to detect on.
    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion

  Back_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door #this is a loopback ip to access the go2rtc stream, after the "/" is the camera name, defined in the go2rtc section. 8554 is the port used for rtsp restream.
          hwaccel_args: preset-rpi-64-h265 #Enable Hardware Acceleration
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Back_Door
          input_args: preset-rtsp-restream  
          roles:
            - detect
    detect:
      enabled: True # Detection is enabled
      width: 896 #correct sub stream res
      height: 672 #correct sub stream res
      fps: 5 #limit the fps that the detector has to detect on.
    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 30
          mode: motion

version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1-standard-arm64
    shm_size: "102mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10 #Map the Pi hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/stacks/frigate-nvr/config:/config
      - /mnt/nas/frigate_storage:/media/frigate
#      - /mnt/8TB_00/frigate-storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "pwd"
```

### Object Detector

Coral

### Any other information that may be helpful

The system originally stored recordings in the /mnt/8TB_00 location.  I created a share on my OMV NAS on another RPi4 called frigate_Storage.  I then created this structure on the frigate RPi4: /mnt/nas/frigate_storage.  I then mounted this share and tested that I can add, delete, and modify files in the /mnt/nas/frigate_storage location.  I further tested I can access this OMV shared folder via my WIN11 computer - again, I can add, delete, and modify files within this directory system.  In both cases, I see changes made on one system are reflected in the other system.

When I changed the frigate_nvr configuration.yml from 

`      - /mnt/8TB_00/frigate-storage:/media/frigate`

to

`     - /mnt/nas/frigate_storage:/media/frigate`

and commented out the old volume, I rebooted the whole system.

I expected to see the clips, exports, and recoding folders (etc) appear in the new shared folder location.  But the system is still recording to the old /mnt/8TB_00/frigate-storage location.

The share is mounted:
```
Fritz@docker-raspi1:~ $ df -h
Filesystem                      Size  Used Avail Use% Mounted on
udev                            3.6G     0  3.6G   0% /dev
tmpfs                           781M  1.5M  780M   1% /run
/dev/sda2                       1.8T  9.8G  1.7T   1% /
tmpfs                           3.9G  216K  3.9G   1% /dev/shm
tmpfs                           5.0M   16K  5.0M   1% /run/lock
/dev/sda1                       510M   67M  444M  14% /boot/firmware
/dev/sdb1                       7.3T  1.1G  6.9T   1% /mnt/8TB_00
tmpfs                           781M   48K  781M   1% /run/user/1000
//192.168.0.38/frigate_storage  4.6T  1.2G  4.6T   1% /mnt/nas/frigate_storage
```

From the fstab file:

`//192.168.0.38/frigate_storage /mnt/nas/frigate_storage cifs nofail,user=pi,password=pwd,uid=1000,gid=1000 0 0`

Thoughts on possible problem(s)?

Thanks in advance.
