### DISCUSSION TITLE
[Config Support]: Frigate not accessible anymore

### DISCUSSION THREAD

**Discussion by Allexio** [blakeblackshear/frigate#16104] [Config Support] [answered]
### Describe the problem you are having

Hi.
About a week ago I successfully managed to launch a Frigate docker instance, and a home assistant instance, and I managed to get the video stream working in HA.

Today I wanted to get MQTT working (first time using it, I am very new to HA and I just set it up specifically for frigate), which I did, but the stream stopped working as soon as I got MQTT working (sensors & captures were working in HA though!).

I decided to move Frigate to the same docker compose file as HA thinking it would better this way.

Everything broke.

I looked up compose files on the frigate website and saw a page saying it wasn't recommended to run Frigate with HA if the network mode was host, so I decided to split the docker compose files again.

Everything is still broken and I am at my wit's end trying to figure out why...

I can't even access the web UI anymore even though I had no problems doing that just earlier today.

Any help would be very, very much appreciated.

### Version

Latest docker image (can't access the UI)

### Frigate config file

```yaml
mqtt:
  enabled: false # disabled this to make sure it wasn't causing issues
  host: 192.168.1.171
  user: user1
  password: [mypassword]

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  dahua-living-room: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:OKBAqhKuiztUHFX4oy74JFdh3PhUmU@192.168.1.108:554/rtsp/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
version: 0.14
```

### Relevant Frigate log output

```shell
Nothing suspicious in the logs?

frigate  | 2025-01-23 21:21:34.547185075  [2025-01-23 21:21:34] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
frigate  | 2025-01-23 21:21:34.547230402  [2025-01-23 21:21:34] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2025-01-23 21:21:34.554191162  [2025-01-23 21:21:34] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2025-01-23 21:21:34.746922674  [2025-01-23 21:21:34] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
frigate  | 2025-01-23 21:21:34.767604718  [2025-01-23 21:21:34] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2025-01-23 21:21:34.767724427  [2025-01-23 21:21:34] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2025-01-23 21:21:34.775040192  [2025-01-23 21:21:34] frigate.app                    INFO    : Recording process started: 494
frigate  | 2025-01-23 21:21:34.782253638  [2025-01-23 21:21:34] frigate.app                    INFO    : Recording process started: 503
frigate  | 2025-01-23 21:21:34.784234625  [2025-01-23 21:21:34] frigate.app                    INFO    : go2rtc process pid: 98
frigate  | 2025-01-23 21:21:34.805631358  [2025-01-23 21:21:34] detector.coral                 INFO    : Starting detection process: 522
frigate  | 2025-01-23 21:21:34.810308717  [2025-01-23 21:21:34] frigate.app                    INFO    : Output process started: 525
frigate  | 2025-01-23 21:21:34.825609189  [2025-01-23 21:21:34] frigate.app                    INFO    : Camera processor started for dahua-living-room: 539
frigate  | 2025-01-23 21:21:34.833094250  [2025-01-23 21:21:34] frigate.app                    INFO    : Capture process started for dahua-living-room: 547
frigate  | 2025-01-23 21:21:37.441781278  [2025-01-23 21:21:34] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate  | 2025-01-23 21:21:37.446927275  [2025-01-23 21:21:37] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate  | 2025-01-23 21:21:43.489301729  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-01-23 21:22:33.637352903  127.0.0.1 - - [23/Jan/2025:21:22:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:23:33.653794124  127.0.0.1 - - [23/Jan/2025:21:23:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:24:33.671282089  127.0.0.1 - - [23/Jan/2025:21:24:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:25:33.687267269  127.0.0.1 - - [23/Jan/2025:21:25:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:26:33.702810456  127.0.0.1 - - [23/Jan/2025:21:26:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:27:33.719661504  127.0.0.1 - - [23/Jan/2025:21:27:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:28:33.735773333  127.0.0.1 - - [23/Jan/2025:21:28:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:29:33.752007975  127.0.0.1 - - [23/Jan/2025:21:29:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:30:33.767855359  127.0.0.1 - - [23/Jan/2025:21:30:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:31:33.783049510  127.0.0.1 - - [23/Jan/2025:21:31:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-01-23 21:32:33.799741325  127.0.0.1 - - [23/Jan/2025:21:32:33 +0000] "" 400 0 "-" "-" "-"
```

### Relevant go2rtc log output

```shell
Nothing really.
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/personal-raid-12GB-1/frigate-storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # tried with and without this specified
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: [mypassword]
```

### Object Detector

Coral
