### DISCUSSION TITLE
[Support]: recording/detect/motion are AUTO-enabled when cameras recovered from unavailable status

### DISCUSSION THREAD

**Discussion by dengke80622** [blakeblackshear/frigate#16107] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

There are 4 cameras connect to frigate in home assistant.
I need to enable recording for front-gate camera and disable other recordings for the rest ones to save SSD space.
Cameras will be unavailable and return to normal due to weak signal, in this case, I notice the switches for detect/motion/recording/snapshot will be turned on without any notice and my storage will be filled with recordings soon.
I hope the addon can remember these switch status and keep pervious when camera became available.
![image](https://github.com/user-attachments/assets/8f626183-c488-4fd6-b72c-593c3b8863dc)

### Steps to reproduce

1. turn off detect/motion/recording/snapshot
2. disconnect camera, wait until the camera status becomes unavailable
3. reconnect camrea
4. the switches will be turned on
...

### Version

0.14.1

### In which browser(s) are you experiencing the issue with?

Google Chrome 131.0.6778.265 (Official Build) (64-bit)

### Frigate config file

```yaml
#go2rtc: //has been moved to docker in openwrt, same setting
#  streams:
#    balcony_hd:
#      - rtsp://admin:12345678@192.168.10.229/stream1
#      - ffmpeg:rtsp_cam#audio=opus
#    front_door:
#      - rtsp://admin:12345678@192.168.10.223/stream1
#      - ffmpeg:rtsp_cam#audio=opus
#    bedroom_hd:
#      - rtsp://admin:12345678@192.168.10.129/stream1
#      - ffmpeg:rtsp_cam#audio=opus
#    kitchen:
#      - rtsp://admin:12345678@192.168.10.135/stream1
#      - ffmpeg:rtsp_cam#audio=opus

mqtt:
  host: 172.30.32.1
  port: 1883
  user: mqtt
  password: mqtt

cameras:
  balcony_hd:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.10.1:8554/balcony_hd
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
    motion:
      mask:
        - 179,121,802,124,801,51,180,53
  bedroom_hd:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.10.1:8554/bedroom_hd
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
    motion:
      mask:
        - 180,122,1020,124,1015,61,181,55
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.10.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
    motion:
      mask:
        - 164,113,672,108,667,48,165,46
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.10.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
    motion:
      mask:
        - 164,113,672,108,667,48,165,46

detectors:
  coral:
    type: edgetpu
    device: pci:0

snapshots:
  enabled: false
  retain:
    default: 30

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Asia/Chongqing
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
default setting in HAOS addon-on page
```

### Relevant Frigate log output

```shell
not captured
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

tplink

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/f4fa0c01-1d3f-4aa9-bdd6-d369c59e13d6)
