### DISCUSSION TITLE
[Support]: Cannot Review Footage From Specific Day, Just See Preview

### DISCUSSION THREAD

**Discussion by ahalekelly** [blakeblackshear/frigate#16127] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I go to the Review page and then the Motion tab and select one specific day, I can't view any of the footage. I get the low-res preview image when I scrub through the timeline, but the video never loads. I can review footage from before and after that day fine. In the browser console, I get these errors. This machine is rebooted at least once a day, it's possible that there was a hard power loss shutdown which caused files to be corrupted, but why would this corrupt the whole day's footage? Also, I looked at a couple of the files from the recordings folder and they look fine.
![Screenshot 2025-01-24 221618 Errors](https://github.com/user-attachments/assets/69fdf753-06e0-48d6-824b-86a29d612946)

### Steps to reproduce

Cannot provide steps to reproduce

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Both the latest Chrome and Firefox

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  burn_chamber_rear:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.10.51:8554/profile0
          roles:
            - record
    detect:
      enabled: false
      #fps: 1
    motion:
      enabled: true

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 90

logger:
  default: info
  logs:
    frigate.events: info
    peewee: info
    ws4py: info
    frigate.app: info
    frigate.video: info
    frigate.ffmpeg: info
    frigate.http: info

version: 0.14

ffmpeg:
  hwaccel_args: preset-jetson-h264

tls:
  enabled: false

birdseye:
  enabled: false

telemetry:
  stats:
    network_bandwidth: true
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp5
    runtime: nvidia
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "5000:5000"
```

### Relevant Frigate log output

```shell
Not sure if these are related but I'm seeing a bunch of these in my logs:

error 2025-01-25 06:34:56 frigate.api.media No recordings found for burn_chamber_rear during the requested time range

warning 2025-01-25 06:35:20 frigate.api.review No motion data found for the requested time range
```

### Relevant go2rtc log output

```shell
No errors in go2rtc logs
```

### Operating system

Nvidia Jetson Ubuntu

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Revotech I706-3-P

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/e250b1f5-6b1a-4517-8852-a518c5bbef73)
![image](https://github.com/user-attachments/assets/6b31ee89-3e0f-4581-b350-b9e9d06eee4c)
![image](https://github.com/user-attachments/assets/06a572d5-edb0-4e14-b657-51cc6086b9b9)
