### DISCUSSION TITLE
[Support]:  Frigate does not start when SMB share is set as recording folder

### DISCUSSION THREAD

**Discussion by Plastikman81** [blakeblackshear/frigate#16128] [General Support] [answered]
### Describe the problem you are having

I am experiencing an issue with Frigate where the container fails to start completely when an SMB share is specified as the recording directory. Despite this, Frigate creates the folder structure within the SMB share but does not fully start.

Steps Taken:
SMB Share Setup:
I initially attempted to configure an SMB share for the recording folder in Frigate.
The SMB share is set up on an Unraid server, and I’ve mounted it on the Docker host using the mount -t cifs command.
Mounting the SMB Share:

I have tried several approaches to mount the SMB share:
From the Docker host: I mounted the SMB share on the Docker host and passed it into the container using the Docker volume mount.
Using PCT: I mounted the SMB share from the Docker host into the container using Proxmox Container (PCT).
Directly within the Frigate container: I mounted the SMB share directly inside the Frigate container as well.
Frigate Configuration:

I edited the Frigate configuration to point to the SMB share as the recording path.

volumes:
  - /mnt/cctv:/media   # Mount SMB or NFS share in the container
I tested both mounting the share on the Docker host and directly inside the container.

Previous Working Configuration:
I had a fully working Frigate configuration previously where recordings were stored on a local path inside the container. This configuration worked fine without any issues.
Now, I am attempting to store the recordings on an SMB share (located on an Unraid server) instead of the local path, but Frigate fails to start when configured to use the SMB share.

Issue with Starting Frigate:
After specifying the SMB share as the recording folder in the Frigate configuration, Frigate fails to start.
The logs show errors related to the connection to the SMB share or database locks.
While Frigate successfully creates the folder structure for recordings within the SMB share, it does not fully initialize or launch the service.

Successful Launch with Local Path:
When I configure Frigate to use a local path for recordings (inside the container), it starts successfully without any issues.
The problem only occurs when attempting to use the SMB share for storing recordings.
SMB Share Permissions:

I have ensured that the SMB share has the correct permissions (file_mode=0777 and dir_mode=0777), giving full read/write access to the share for the Frigate container.
The share is accessible from the Docker host, and I can verify it by running ls and checking the folder structure inside the container.

Diagnostic Steps:
I mounted the SMB share manually on the Docker host.
sudo mount -t cifs //<ip_of_server>/mnt/cctv /mnt/video -o username=<username>,password=<password>,file_mode=0777,dir_mode=0777
I tested accessing the share from both the Docker host and within the Frigate container.

Logs:
Frigate logs indicate it is trying to access the mounted SMB share but encounters issues, and the container does not fully start.
There are errors like:
database is locked
connect() failed (111: Connection refused)
auth request unexpected status: 502

Expected Behavior:
Frigate should be able to start and use the SMB share as the recording folder without any issues, just as it works when using a local path.

Request:
Can anyone assist in identifying why Frigate fails to start when an SMB share is used for recordings?
Is there a special configuration or workaround needed for using SMB shares with Frigate in a Docker container?

### Version

0.14.0

### What browser(s) are you using?

edge, opera

### Frigate config file

```yaml
...
```

### Relevant Frigate log output

```shell
database is locked
connect() failed (111: Connection refused)
auth request unexpected status: 502
```

### Relevant go2rtc log output

```shell
...
```

### FFprobe output from your camera

```shell
...
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    restart: unless-stopped
    shm_size: "512mb" # Shared Memory für ffmpeg
    ports:
      - "5000:5000" # Web-GUI Port
      - "1935:1935" # RTMP-Stream Port
    volumes:
      - /mnt/cctv/config:/config         # Pfad für Konfigurationsdatei
      - /mnt/cctv:/media           # Pfad für Aufnahmen
      - /dev/dri:/dev/dri                # Für Hardware-Beschleunigung (z. B. Intel iGPU)
      - /dev/bus/usb:/dev/bus/usb        # Für USB Coral TPU
    environment:
#      - FRIGATE_RTSP_PASSWORD=your_rtsp_password
      - LIBVA_DRIVER_NAME=iHD
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

...
