### DISCUSSION TITLE
GPU usage is always zero

### DISCUSSION THREAD

**Discussion by Imwithstupid007** [blakeblackshear/frigate#16120] [Config Support] [answered]
### Describe the problem you are having

I'm using Frigate for some time now. I noticed in the stats page that my GPU always indicates no usage (0.0%).
As far as I understand Frigate uses the GPU to decode video and detection. So, shouldn't the GPU not always show some activity?

I'm running Frigate on a HardKernel Odroid H4 Ultra, Openmediavault 7.5.1-1 compose

### Version

14.1

### Frigate config file

```yaml
ui:
  time_format: 24hour
  strftime_fmt: '%d/%m/%Y %H:%M:%S'

mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

#logger:
#  default: info
#  logs:
#    frigate.record: debug

birdseye:
  enabled: false
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  sync_recordings: false
  retain:
    days: 10
    mode: all
  events:
    retain:
      default: 10

go2rtc:
  streams:
    tuinhuiscam:
      - rtsp://rtspuser:xxxxxxxx@192.168.1.64:554/Streaming/Channels/101
    tuinhuiscam_sub:
      - rtsp://rtspuser:xxxxxxxx@192.168.1.64:554/Streaming/Channels/102
    deurbel:
      - ffmpeg:http://192.168.1.65/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx#video=copy#audio=copy#audio=opus
    deurbel_sub:
      - ffmpeg:http://192.168.1.65/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxxxxx

cameras:
  tuinhuiscam: # geen output_args: geen audio
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/tuinhuiscam?video&audio
          roles:
            - record
        - path: rtsp://localhost:8554/tuinhuiscam_sub
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0.321,0.308,0.195,0.307,0,0,0
        - 1,0,1,1,0.962,1,0.858,0
        - 0.815,0.441,0.849,0.442,0.849,0.152,0.815,0.151
        - 0,0.323,0.077,0.291,0.082,1,0,1
    zones:
      tuin:
        coordinates: 0.961,1,0.873,0.164,0.388,0.166,0,0.324,0,1
        objects: person
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: tuin
  deurbel: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/deurbel
          roles:
            - record
        - path: rtsp://localhost:8554/deurbel_sub
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
        - bicycle
        - motorcycle
    motion:
      mask: 0,0,1,0,1,0.413,0,0.413
    zones:
      straat:
        coordinates: 0,1,1,1,1,0.414,0,0.414
        objects:
          - person
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: straat

version: 0.14
camera_groups: {}
```

### Relevant Frigate log output

```shell
2025-01-23 19:44:41.614384595  [INFO] Preparing Frigate...
2025-01-23 19:44:41.629946464  [INFO] Starting Frigate...
2025-01-23 19:44:43.023575141  [2025-01-23 19:44:43] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2025-01-23 19:44:43.023608418  [2025-01-23 19:44:43] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-23 19:44:43.045166453  [2025-01-23 19:44:43] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-23 19:44:55.405576938  [2025-01-23 19:44:55] peewee_migrate.logs            INFO    : Starting migrations
2025-01-23 19:44:55.405713468  [2025-01-23 19:44:55] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-23 19:44:55.426717633  [2025-01-23 19:44:55] frigate.app                    INFO    : Recording process started: 389
2025-01-23 19:44:55.432271876  [2025-01-23 19:44:55] frigate.app                    INFO    : Recording process started: 395
2025-01-23 19:44:55.436011066  [2025-01-23 19:44:55] frigate.app                    INFO    : go2rtc process pid: 98
2025-01-23 19:44:55.455842451  [2025-01-23 19:44:55] detector.coral                 INFO    : Starting detection process: 417
2025-01-23 19:44:55.458825736  [2025-01-23 19:44:55] frigate.app                    INFO    : Output process started: 419
2025-01-23 19:44:55.510036070  [2025-01-23 19:44:55] frigate.app                    INFO    : Camera processor started for tuinhuiscam: 436
2025-01-23 19:44:55.510121679  [2025-01-23 19:44:55] frigate.app                    INFO    : Camera processor started for deurbel: 439
2025-01-23 19:44:55.517653414  [2025-01-23 19:44:55] frigate.app                    INFO    : Capture process started for tuinhuiscam: 443
2025-01-23 19:44:55.519100171  [2025-01-23 19:44:55] frigate.app                    INFO    : Capture process started for deurbel: 453
2025-01-23 19:44:58.099822138  [2025-01-23 19:44:55] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-01-23 19:44:58.105723692  [2025-01-23 19:44:58] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
2025-01-23 19:44:41.621072254  [INFO] Preparing new go2rtc config...
2025-01-23 19:44:42.048059803  [INFO] Starting go2rtc...
2025-01-23 19:44:42.200435034  19:44:42.200 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-23 19:44:42.200439737  19:44:42.200 INF config path=/dev/shm/go2rtc.yaml
2025-01-23 19:44:42.200985150  19:44:42.200 INF [api] listen addr=:1984
2025-01-23 19:44:42.201328330  19:44:42.201 INF [rtsp] listen addr=:8554
2025-01-23 19:44:42.201529911  19:44:42.201 INF [webrtc] listen addr=:8555/tcp
2025-01-23 19:44:51.614775659  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
---
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
---
# https://github.com/blakeblackshear/frigate
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    # image: ghcr.io/blakeblackshear/frigate:0.13.2
    shm_size: "160mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    #  - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_TO_APPDATA}/frigate/config.yml:/config/config.yml
      - ${PATH_TO_MOVIES}/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b9f1ede3-1426-4cec-9b21-a3a36b65d9f0)
![image](https://github.com/user-attachments/assets/a60801e8-2f45-45f2-8be9-ea3b0877b5f7)

**Comment by NickM-27** [comment]
in your case the coral is used for detection, not the GPU. 

you can run `intel-gpu-top` on the host and see what processes are running, you should see 2 ffmpeg processes. Decoding is not a lot of work especially for a 12th gen iGPU like your device has

**Comment by Imwithstupid007** [comment]
I ran `intel_gpu_top` inside the corresponding Frigate container and it showed this (no ffmpeg processes):

![image](https://github.com/user-attachments/assets/bc0abbe0-463d-4efd-8160-49c9f696c2b0)

**Reply by NickM-27** [reply]
right, like I said you should run it on the host. would also be good to see hardware info from the metrics screen

**Comment by Imwithstupid007** [comment]
You mean this?

`{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain:tVAEntrypointEncSliceLPnVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileHEVCMain10:tVAEntrypointEncSliceLPnVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile0:tVAEntrypointEncSliceLPnVAProfileVP9Profile1:tVAEntrypointVLDnVAProfileVP9Profile1:tVAEntrypointEncSliceLPnVAProfileVP9Profile2:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointEncSliceLPnVAProfileVP9Profile3:tVAEntrypointVLDnVAProfileVP9Profile3:tVAEntrypointEncSliceLPnVAProfileHEVCMain12:tVAEntrypointVLDnVAProfileHEVCMain12:tVAEntrypointEncSlicenVAProfileHEVCMain422_10:tVAEntrypointVLDnVAProfileHEVCMain422_10:tVAEntrypointEncSlicenVAProfileHEVCMain422_12:tVAEntrypointVLDnVAProfileHEVCMain422_12:tVAEntrypointEncSlicenVAProfileHEVCMain444:tVAEntrypointVLDnVAProfileHEVCMain444:tVAEntrypointEncSliceLPnVAProfileHEVCMain444_10:tVAEntrypointVLDnVAProfileHEVCMain444_10:tVAEntrypointEncSliceLPnVAProfileHEVCMain444_12:tVAEntrypointVLDnVAProfileHEVCSccMain:tVAEntrypointVLDnVAProfileHEVCSccMain:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain10:tVAEntrypointVLDnVAProfileHEVCSccMain10:tVAEntrypointEncSliceLPnVAProfileHEVCSccMain444:tVAEntrypointVLDnVAProfileHEVCSccMain444:tVAEntrypointEncSliceLPnVAProfileAV1Profile0:tVAEntrypointVLDnVAProfileHEVCSccMain444_10:tVAEntrypointVLDnVAProfileHEVCSccMain444_10:tVAEntrypointEncSliceLP"}`

![image](https://github.com/user-attachments/assets/d5622c52-7b34-43e1-87ea-9f0f2bdb44bd)

**Reply by NickM-27** [reply]
looks like the driver is correct, so it should be using the GPU. If you run Frigate 0.15 then you will want to use qsv and that may show up on the stats

**Comment by Imwithstupid007** [comment]
0.15 is not yet official.
If I installed the latest beta (0.15-7) would it be sufficient to change this:

`ffmpeg:`
`  hwaccel_args: preset-vaapi`

into this

`ffmpeg:`
`  hwaccel_args: preset-intel-qsv-h264`

Because I experimented with this in 0.14 and it wasn't a success (no video from cameras)

**Reply by NickM-27** [reply]
yes that is the only change that is needed

**Comment by Imwithstupid007** [comment, marked as answer]
Just to roundup this issue.
After a reboot of the NAS things look like they should be.

![image](https://github.com/user-attachments/assets/b85db287-c781-4842-bdd3-745a865b4aa9)

![image](https://github.com/user-attachments/assets/13dc9e76-fe34-4822-aab9-4b6371391e37)

**Reply by lukpep** [reply]
Did it stay this way? I'm seeing similar stuff on my N150 machine. GPU is used... stats are correct and after a night it drops to 0%.
A still can see ffmpg processes with intel_gpu_top but not much is happening:

![CleanShot 2025-03-02 at 13 43 38@2x](https://github.com/user-attachments/assets/b75b6476-6b9c-4d62-9af3-3d62a408fd8c)

after machine reboot GPU usage is once again reported correctly in frigate

**Reply by raverlution** [reply]
> Did it stay this way? I'm seeing similar stuff on my N150 machine. GPU is used... stats are correct and after a night it drops to 0%. A still can see ffmpg processes with intel_gpu_top but not much is happening:
> 
> ![CleanShot 2025-03-02 at 13 43 38@2x](https://private-user-images.githubusercontent.com/2960580/418347302-b75b6476-6b9c-4d62-9af3-3d62a408fd8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0NDQ2MjgsIm5iZiI6MTc1MzQ0NDMyOCwicGF0aCI6Ii8yOTYwNTgwLzQxODM0NzMwMi1iNzViNjQ3Ni02YjljLTRkNjItOWFmMy0zZDYyYTQwOGZkOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MjVUMTE1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjYzIzY2FjOGExMzEyOTZmNzI1ZjJhOTU3MWMwMzhiYTAyZDUwMjdlZjAzODIzOTQ0MDM1Nzg3N2QyOGZhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2JmMowUlt3eZrc5ni4g02N7tDUJjJy4EXEAuRX87T5U)
> 
> after machine reboot GPU usage is once again reported correctly in frigate

I see the same. 

N150 HAOS Frigate as addon 

Does any have a solution?

A reboot solves it for about 12 hours. 
After about 1-2 days i can see under system metrics that my cpu rises for embeddings

**Comment by Imwithstupid007** [comment]
After a reboot of my NAS (i3-N305; OMV latest, Frigate 0.15 compose) all seems fine. In `intel_gpu_top` there is activity visible under `Video` and `VideoEnhance` (what ever that means).
Frigate shows some `GPU usage` which probably corresponds (my guess) to  `intel_gpu_top` `Video`.


![Screenshot 2025-02-22 165031](https://github.com/user-attachments/assets/fb52a93a-0520-4947-9b42-ad708e80003d)

![image](https://github.com/user-attachments/assets/b1b07cf1-87ee-440b-9ac3-f0530219766b)

But after some time `intel_gpu_top` only shows activity of `VideoEnhance`. The previous activity of `Video` is gone. Frigate shows a `GPU usage` of 0% (hence my assumption that Frigate shows `Video` as GPU usage).


![Screenshot 2025-02-23 110513](https://github.com/user-attachments/assets/392a30c4-ae7d-4338-8124-8e7c904fa359)

![image](https://github.com/user-attachments/assets/39b8d2ae-132f-475e-b61c-6cbad2a16b15)

Waiting some more time and the activity of `VideoEnhance` also disappears.


![Screenshot 2025-03-02 142257](https://github.com/user-attachments/assets/671259fb-60ee-4632-a1fa-20e8b897e6f3)


Remark: The typical Frigate processes ffmpeg, go2rtc, nginx and frigate.recording/process/output/capture/review under `top` seem to remain present/active. Maybe its just a visual bug.


Until now I found:
* no clear trigger to what causes this (nothing is logged) and 
* no other way as to reboot the NAS to make `Video`/`VideoEnhance`/`CPU Usage` active again. Restarting Frigate, the Frigate container, or docker complete makes no improvement.

Looking at your setup it seems to rule out that the cause is the hardware or the host OS. Maybe still an Intel driver issue.

**Reply by convicte** [reply]
> After a reboot of my NAS (i3-N305; OMV latest, Frigate 0.15 compose) all seems fine. In `intel_gpu_top` there is activity visible under `Video` and `VideoEnhance` (what ever that means). Frigate shows some `GPU usage` which probably corresponds (my guess) to `intel_gpu_top` `Video`.
> 
> ![Screenshot 2025-02-22 165031](https://private-user-images.githubusercontent.com/38496665/418347549-fb52a93a-0520-4947-9b42-ad708e80003d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2NjAyNzksIm5iZiI6MTc0NDY1OTk3OSwicGF0aCI6Ii8zODQ5NjY2NS80MTgzNDc1NDktZmI1MmE5M2EtMDUyMC00OTQ3LTliNDItYWQ3MDhlODAwMDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDE5NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NWY3NDk0ZDk5Y2JmYmVjNzE5NDU3ODkzYjcxYjA5ZWQ3NzYxYWJhNzQyYzgxNzNmODQwMDBmNjhiYzkxNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2fzviJHrt_Swg_B2CCcGfcohA5urOrdjmOtrlcH34hE)
> 
> ![image](https://private-user-images.githubusercontent.com/38496665/418347590-b1b07cf1-87ee-440b-9ac3-f0530219766b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2NjAyNzksIm5iZiI6MTc0NDY1OTk3OSwicGF0aCI6Ii8zODQ5NjY2NS80MTgzNDc1OTAtYjFiMDdjZjEtODdlZS00NDBiLTlhYzMtZjA1MzAyMTk3NjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDE5NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYjUxMDEwM2U2MmRjMTkwOTEyZGE3YjA3MWExMjc5ZDlhMDIyYjEzYzA5N2E3Y2ZhOTNhMDQzOGUxNTBiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I4q72ylcgqGmmRO0UIsJPyqCVvNRGZDZv8Sc0qohyfs)
> 
> But after some time `intel_gpu_top` only shows activity of `VideoEnhance`. The previous activity of `Video` is gone. Frigate shows a `GPU usage` of 0% (hence my assumption that Frigate shows `Video` as GPU usage).
> 
> ![Screenshot 2025-02-23 110513](https://private-user-images.githubusercontent.com/38496665/418347668-392a30c4-ae7d-4338-8124-8e7c904fa359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2NjAyNzksIm5iZiI6MTc0NDY1OTk3OSwicGF0aCI6Ii8zODQ5NjY2NS80MTgzNDc2NjgtMzkyYTMwYzQtYWU3ZC00MzM4LTgxMjQtOGU3YzkwNGZhMzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDE5NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGVhODg0M2MzMzc1ODIxOGJkYjIzMGFkNDRhNzcwMmI4MDRhZmZjNjY3MzAwZjkyNGIzY2M5OGFhNmFiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hlp_Dmu6bx9iEJpzwhkcaGGlRj_mHx-xwpL03GntaCE)
> 
> ![image](https://private-user-images.githubusercontent.com/38496665/418347696-39b8d2ae-132f-475e-b61c-6cbad2a16b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2NjAyNzksIm5iZiI6MTc0NDY1OTk3OSwicGF0aCI6Ii8zODQ5NjY2NS80MTgzNDc2OTYtMzliOGQyYWUtMTMyZi00NzVlLWI2MWMtNmNiYWQyYTE2YjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDE5NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYjZhYTNiOTJhNmNjN2M1NGM2N2NiMTIyY2RmOGM4NGQxZjFlODUzMmU0YTNmM2RmNDQ2MTE2MjJiMGE4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7gazw9u-BtIuotSP3f9QYwV6H6Shl2lVhSw-kTQSQjA)
> 
> Waiting some more time and the activity of `VideoEnhance` also disappears.
> 
> ![Screenshot 2025-03-02 142257](https://private-user-images.githubusercontent.com/38496665/418349805-671259fb-60ee-4632-a1fa-20e8b897e6f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2NjAyNzksIm5iZiI6MTc0NDY1OTk3OSwicGF0aCI6Ii8zODQ5NjY2NS80MTgzNDk4MDUtNjcxMjU5ZmItNjBlZS00NjMyLWExZmEtMjBlOGI4OTdlNmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDE5NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ODMyZGMwZDNiZTFkYmYxNWJhYjFmNTk3MmIwZmQwZDBjZDlkMjdmNTRkMWU4YmQyMTI4NjNmNmUwZDRjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.47DjK86WNDiZLPHj3lcn-7jVpdf1C5mDmN_f97ilbrs)
> 
> Remark: The typical Frigate processes ffmpeg, go2rtc, nginx and frigate.recording/process/output/capture/review under `top` seem to remain present/active. Maybe its just a visual bug.
> 
> Until now I found:
> 
> * no clear trigger to what causes this (nothing is logged) and
> * no other way as to reboot the NAS to make `Video`/`VideoEnhance`/`CPU Usage` active again. Restarting Frigate, the Frigate container, or docker complete makes no improvement.
> 
> Looking at your setup it seems to rule out that the cause is the hardware or the host OS. Maybe still an Intel driver issue.

Can reproduce the same exact behavior on A380 inside Unraid, where Frigate reports some usage and then silence....

**Reply by Calimerorulez** [reply]
Same here on my Arc a310

**Comment by lukpep** [comment]
> Until now I found:
> 
> no clear trigger to what causes this (nothing is logged) and
> no other way as to reboot the NAS to make Video/VideoEnhance/CPU Usage active again. Restarting Frigate, the Frigate container, or docker complete makes no improvement.

@Imwithstupid007  
my config: N150 chip + debian
on 6.1 kernel I couldn't use hw acceleration at all. Switched to https://liquorix.net/ and now I have:

```
lukpep@lpe-lab:~$ inxi -G
Graphics:
  Device-1: Intel Alder Lake-N [Intel Graphics] driver: i915 v: kernel
  Display: server: No display server data found. Headless machine? tty: 160x40
  API: OpenGL Message: GL data unavailable in console. Try -G --display
```

rest is the same as You described
