### DISCUSSION TITLE
[Config Support]: can't get H265 stream correctly

### DISCUSSION THREAD

**Discussion by dagord** [blakeblackshear/frigate#16134] [Config Support] [answered]
### Describe the problem you are having

I installed Frigate via Docker on a NUC with an N100 processor and Debian 12 OS.
I have no issues capturing streams using the H264 codec, but I’m running into problems with the H265 codec.

Specifically, I’m testing a Reolink Duo 2 camera that offers both an H265 high-resolution stream and an H264 low-resolution stream.
I’ve attached my config.yml, which I copied from some online examples without fully understanding it, so there’s definitely room for improvement.

The issues:
- I can see the overview correctly, but when I open the single-camera view, the stream appears completely gray on desktop (I’m using Google Chrome, which should natively support the H265 codec). On mobile (Google Chrome for Android), the stream works, but it’s very slow to load.
- I can’t play recordings: on desktop, it keeps loading indefinitely, while on mobile, I get the message "PIPELINE ERROR DECODE".
If I switch to the H264 stream, I don’t have any issues, but the stream is in low resolution so it's not a solution.

I'm not sure this is really an issue related to Frigate itself, but any advice would be very appreciated!

At the moment, I’m not interested in object detection—I’d just like to get live viewing and recording working properly.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    front-camera: 
      rtsp://admin:password@192.168.0.212/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
    terrace-camera: 
      rtsp://admin:password@192.168.0.213/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
    field-camera: 
      rtsp://admin:password@192.168.0.209/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
    reolink-camera:
      rtsp://admin:password@192.168.0.214:554/h265Preview_01_main

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  front-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://127.0.0.1:8554/front-camera
          roles:
            - detect
            - record
      hwaccel_args: []
      input_args: preset-rtsp-generic
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
  terrace-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://127.0.0.1:8554/terrace-camera
          roles:
            - detect
            - record
      hwaccel_args: []
      input_args: preset-rtsp-generic
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
  field-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://127.0.0.1:8554/field-camera
          roles:
            - detect
            - record
      hwaccel_args: []
      input_args: preset-rtsp-generic
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
  reolink-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://127.0.0.1:8554/reolink-camera
          roles:
            - detect
            - record
      hwaccel_args: []
      input_args: preset-rtsp-generic
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
version: 0.14
camera_groups:
  test:
    order: 1
    icon: LuAirplay
    cameras:
      - birdseye
      - name_of_your_camera
      - front-camera

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant Frigate log output

```shell
no relevant output/errors
```

### Relevant go2rtc log output

```shell
no relevant output/errors
```

### Frigate stats

```json
{"cameras":{"field-camera":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":486,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":506,"pid":467,"process_fps":5.0,"skipped_fps":0.0},"front-camera":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.2,"capture_pid":477,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":502,"pid":463,"process_fps":5.2,"skipped_fps":0.0},"reolink-camera":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":493,"detection_enabled":true,"detection_fps":3.2,"ffmpeg_pid":518,"pid":472,"process_fps":5.1,"skipped_fps":0.0},"terrace-camera":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":482,"detection_enabled":false,"detection_fps":0.0,"ffmpeg_pid":514,"pid":464,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"105":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"10.9","cpu_average":"10","mem":"0.2"},"122":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"123":{"cmdline":"python3 -u -m frigate","cpu":"2.4","cpu_average":"3","mem":"3.4"},"134":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"175":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"176":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"177":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"178":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"18":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"187":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"312":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.8"},"32":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"359":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"418":{"cmdline":"frigate.recording_manager","cpu":"2.2","cpu_average":"1","mem":"1.0"},"424":{"cmdline":"frigate.review_segment_manager","cpu":"0.6","cpu_average":"0","mem":"0.8"},"445":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"446":{"cmdline":"frigate.detector.ov  ","cpu":"5.7","cpu_average":"8","mem":"2.4"},"448":{"cmdline":"frigate.output       ","cpu":"5.8","cpu_average":"5","mem":"0.9"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"463":{"cmdline":"frigate.process:front-camera","cpu":"1.5","cpu_average":"1","mem":"0.9"},"464":{"cmdline":"frigate.process:terrace-camera","cpu":"1.8","cpu_average":"1","mem":"0.9"},"467":{"cmdline":"frigate.process:field-camera","cpu":"1.9","cpu_average":"1","mem":"0.9"},"472":{"cmdline":"frigate.process:reolink-camera","cpu":"3.3","cpu_average":"4","mem":"1.2"},"477":{"cmdline":"frigate.capture:front-camera","cpu":"1.4","cpu_average":"1","mem":"0.9"},"482":{"cmdline":"frigate.capture:terrace-camera","cpu":"1.7","cpu_average":"1","mem":"0.9"},"486":{"cmdline":"frigate.capture:field-camera","cpu":"1.9","cpu_average":"1","mem":"0.9"},"493":{"cmdline":"frigate.capture:reolink-camera","cpu":"2.1","cpu_average":"1","mem":"0.9"},"502":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/front-camera -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front-camera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"10.0","cpu_average":"10","mem":"0.3"},"506":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/field-camera -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/field-camera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"14.7","cpu_average":"13","mem":"0.3"},"514":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/terrace-camera -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/terrace-camera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"18.7","cpu_average":"18","mem":"0.3"},"518":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/reolink-camera?video=h264 -r 5 -vf fps=5,scale=1536:576 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.7","cpu_average":"8","mem":"0.3"},"521":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/reolink-camera?video=h265 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/reolink-camera@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.2"},"544":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"549":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"554":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"561":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1536x576 -i pipe: -threads 1 -f mpegts -s 1920x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"566":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"8385":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"85":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"8536":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"frigate.full_system":{"cpu":"25.6","mem":"12.8"}},"detection_fps":3.2,"detectors":{"ov":{"detection_start":0.0,"inference_speed":15.32,"pid":446}},"processes":{"go2rtc":{"pid":105},"logger":{"pid":312},"recording":{"pid":418},"review_segment":{"pid":424}},"service":{"last_updated":1737822602,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":633.2,"mount_type":"tmpfs","total":640.0,"used":6.8},"/media/frigate/clips":{"free":312534.4,"mount_type":"ext4","total":449996.0,"used":114531.3},"/media/frigate/recordings":{"free":312534.4,"mount_type":"ext4","total":449996.0,"used":114531.3},"/tmp/cache":{"free":859.7,"mount_type":"tmpfs","total":953.7,"used":94.0}},"temperatures":{},"uptime":2069,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "640mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/projects/frigate/config:/config
      - /home/user/projects/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

OpenVino

**Comment by NickM-27** [comment]
This might be an issue with the reolink stream directly where the browser is failing to playback. You can use `chrome://media-internals` to get logs about what is failing

**Reply by dagord** [reply]
Ok, I see... it's an issue on the client side! Actually, I'm using an old pc running Ubuntu 20.04 so I understand the hardware is not supported in relation to hevc support.
But I don't understand why I can see the stream in the overview page... the stream address should be the same as for the main camera view. What am I missing?

Anyway, reading on the web I'm guessing that ffmpeg could be used to decode the H265 stream to H264 in real time. Is this applicable?

**Reply by NickM-27** [reply]
Depends, you might be seeing the jpeg preview / jsmpeg instead of full live view

**Reply by dagord** [reply]
So, do you think I could use ffmpeg to convert H265 feed to H264?
Chatgpt suggested a workaround:
```
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.0.214:554/h265Preview_01_main
          roles:
            - detect
            - record
      input_args:
        - -rtsp_transport
        - tcp
        - -fflags
        - nobuffer
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
```

It works, but I need to disable Openvino otherwise I get this error: "hardware accelerator failed to decode picture"

**Reply by NickM-27** [reply]
that is using CPU which will be very inefficient. You'll be better off using go2rtc to do that most likely

**Reply by dagord** [reply]
Yes, I understand that it would be inefficient. What do you mean by using go2rtc? Can you point me to an example configuration?
Chatgpt (again :) )suggested this:

```
streams:
  reolink:
    - ffmpeg:rtsp://username:password@192.168.0.214:554/h265Preview_01_main|video=h264
    
cameras:
  reolink_cam:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/reolink
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
```
Adding the "video=h264" should do the trick, but I get an ""[rtsp] error="streams: wrong response on DESCRIBE" message, suggesting that the rtsp address is wrong
