### DISCUSSION TITLE
[Config Support]: HLS video jumping

### DISCUSSION THREAD

**Discussion by RobMeades** [blakeblackshear/frigate#16135] [Config Support]
### Describe the problem you are having

I have installed frigate on Ubuntu (24.04.1 LTS on an Intel i5-5200U 2.20GHz desktop) in order to capture an HLS live stream.  The stream is being encoded by FFMPEG (H.264, 15 fps, 950 x 540, 2 seconds per segment, 15 segments in the `.m3u8` file) by another machine on the same LAN and can be played by VLC (and in a browser running `hls.js`) on the machine that is running frigate without issue but whatever frigate configuration I try I can only get jumpy playback, i.e. a frame is displayed then a few seconds later a future frame is displayed, etc.

I have tried various configurations, including disabling detect (which is the configuration I have pasted in below: detect is nice to have but I don't require it) however no configuration has yet given me the 15 fps view/record I'm after.

What might I be doing wrong?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  watchdog:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: http://10.10.1.16/video/watchdog.m3u8
          roles:
            - record
      input_args: preset-http-mjpeg-generic
    detect:
      width: 950
      height: 540
      enabled: False
version: 0.14
```

### Relevant Frigate log output

```shell
2025-01-25 16:45:37.667685859  [INFO] Preparing Frigate...
2025-01-25 16:45:37.682939768  [INFO] Starting Frigate...
2025-01-25 16:45:39.673085812  [2025-01-25 16:45:39] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2025-01-25 16:45:39.673307294  [2025-01-25 16:45:39] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-25 16:45:39.682705546  [2025-01-25 16:45:39] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-25 16:45:39.799108573  [2025-01-25 16:45:39] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2025-01-25 16:45:39.829045066  [2025-01-25 16:45:39] peewee_migrate.logs            INFO    : Starting migrations
2025-01-25 16:45:39.830236119  [2025-01-25 16:45:39] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-25 16:45:39.837077576  [2025-01-25 16:45:39] frigate.app                    INFO    : Recording process started: 382
2025-01-25 16:45:39.845513651  [2025-01-25 16:45:39] frigate.app                    INFO    : Recording process started: 385
2025-01-25 16:45:39.851537927  [2025-01-25 16:45:39] frigate.app                    INFO    : go2rtc process pid: 98
2025-01-25 16:45:39.879831586  [2025-01-25 16:45:39] detector.cpu                   INFO    : Starting detection process: 410
2025-01-25 16:45:39.886581464  [2025-01-25 16:45:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2025-01-25 16:45:39.888604682  [2025-01-25 16:45:39] frigate.app                    INFO    : Output process started: 412
2025-01-25 16:45:39.915049006  [2025-01-25 16:45:39] frigate.app                    INFO    : Camera processor started for watchdog: 426
2025-01-25 16:45:39.915056293  [2025-01-25 16:45:39] frigate.app                    INFO    : Capture process started for watchdog: 429
```

### Relevant go2rtc log output

```shell
2025-01-25 16:45:37.666945468  [INFO] Preparing new go2rtc config...
2025-01-25 16:45:38.178041419  [INFO] Starting go2rtc...
2025-01-25 16:45:38.368374622  16:45:38.368 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-25 16:45:38.368506257  16:45:38.368 INF config path=/dev/shm/go2rtc.yaml
2025-01-25 16:45:38.369145995  16:45:38.369 INF [rtsp] listen addr=:8554
2025-01-25 16:45:38.369173088  16:45:38.369 INF [api] listen addr=:1984
2025-01-25 16:45:38.369459334  16:45:38.369 INF [webrtc] listen addr=:8555/tcp
2025-01-25 16:45:47.663272281  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
  "cameras": {
    "watchdog": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 5.8,
      "capture_pid": 429,
      "detection_enabled": false,
      "detection_fps": 0,
      "ffmpeg_pid": 442,
      "pid": 426,
      "process_fps": 3.2,
      "skipped_fps": 0.1
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "116": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "121": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "0.8",
      "cpu_average": "1",
      "mem": "3.3"
    },
    "133": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "161": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "162": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "246": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "255": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "26": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "2716": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "2744": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "310": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "339": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.5"
    },
    "34": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "382": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "1.6"
    },
    "385": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "1.6"
    },
    "409": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(54)",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "410": {
      "cmdline": "frigate.detector.cpu ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "1.6"
    },
    "412": {
      "cmdline": "frigate.output       ",
      "cpu": "1.0",
      "cpu_average": "1",
      "mem": "1.8"
    },
    "426": {
      "cmdline": "frigate.process:watchdog",
      "cpu": "1.7",
      "cpu_average": "1",
      "mem": "1.7"
    },
    "429": {
      "cmdline": "frigate.capture:watchdog",
      "cpu": "1.0",
      "cpu_average": "1",
      "mem": "1.6"
    },
    "442": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i http://10.10.1.16/video/watchdog.m3u8 -r 5 -vf fps=5,scale_vaapi=w=950:h=540:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.0",
      "cpu_average": "2",
      "mem": "0.6"
    },
    "445": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 950x540 -i pipe: -threads 1 -f mpegts -s 1266x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "450": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "86": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "frigate.full_system": {
      "cpu": "3.2",
      "mem": "30.1"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "cpu": {
      "detection_start": 0,
      "inference_speed": 10,
      "pid": 410
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.0%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 98
    },
    "logger": {
      "pid": 339
    },
    "recording": {
      "pid": 382
    },
    "review_segment": {
      "pid": 385
    }
  },
  "service": {
    "last_updated": 1737825386,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 62.7,
        "mount_type": "tmpfs",
        "total": 64,
        "used": 1.3
      },
      "/media/frigate/clips": {
        "free": 830440.1,
        "mount_type": "ext4",
        "total": 937291,
        "used": 59167.1
      },
      "/media/frigate/recordings": {
        "free": 830440.1,
        "mount_type": "ext4",
        "total": 937291,
        "used": 59167.1
      },
      "/tmp/cache": {
        "free": 950.1,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 3.5
      }
    },
    "temperatures": {

    },
    "uptime": 1847,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rob/frigate/config:/config
      - /home/rob/videos:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/89449a46-11ad-454d-bb18-13da4cb49c7a)

**Comment by NickM-27** [comment]
What is it encoded as?

**Reply by RobMeades** [reply]
Thanks for the swift response: YUV420P, GOP every 2 seconds (to match the segment duration).

**Reply by RobMeades** [reply]
...or maybe you wanted "MPEG4": here's what VLC says about the stream when it is being played:

![image](https://github.com/user-attachments/assets/2315da92-501f-4166-9a57-f8829274bdc4)

**Reply by NickM-27** [reply]
They are h264, so the input args you have in the config are wrong. You could try using preset-http-reolink and see if that works better.

**Reply by RobMeades** [reply]
Tried the following:

```
cameras:
  watchdog:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: http://10.10.1.16/video/watchdog.m3u8
          roles:
            - record
      input_args: preset-http-reolink
    detect:
      width: 950
      height: 540
      enabled: False
```

...same result unfortunately.  Just to check, I assume that when I click on the preview window to see the feed from my camera I should expect a real-time 15 FPS-type image to be displayed?

Is it worth me capturing a frigate debug log?

**Reply by NickM-27** [reply]
> I assume that when I click on the preview window to see the feed from my camera I should expect a real-time 15 FPS-type image to be displayed?

No, you need to setup go2rtc. It will be 5 fps without go2rtc

**Reply by RobMeades** [reply]
Ah, maybe that's it then: I have got as far as configuring frigate to record and the recordings, played back with VLC, are fine, it is playing "live" or trying to play back a recording from within frigate that is my problem, I hadn't realised it was 5 FPS unless I did something.  Let me see if I can configure `go2rtc` in that case...

**Comment by AndersonFontana** [comment]
I had the same issue even using the `go2rtc` approach.

Here's a suggestion for your config:

```yaml
# ...

go2rtc:
  streams:
    watchdog:
      - ffmpeg:http://10.10.1.16/video/watchdog.m3u8#input=file#video=copy

cameras:
  watchdog:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/watchdog
          input_args: preset-rtsp-restream
          roles:
            - record
# ...
```

After looking at the resources below, I found out about the input templates:
- https://github.com/AlexxIT/go2rtc/?tab=readme-ov-file#source-ffmpeg
- https://github.com/AlexxIT/go2rtc/blob/master/internal/ffmpeg/ffmpeg.go#L60

The `input=file` param is what fixed the issue for me, but it added a few seconds of delay.

I'm assuming it's something about the `-fflags nobuffer` or `-flags low_delay` (that other presets have). My guess is that when a segment is received, those flags causes the stream to jump to the end of the segment. And without those flags, it starts to buffer, allowing a smoother playback.
