### DISCUSSION TITLE
No audio in recording for Hikvision camera with G.711 ulaw

### DISCUSSION THREAD

**Discussion by PregLizZz** [blakeblackshear/frigate#16142] [Config Support]
### Describe the problem you are having

Hi,
I have audio in the live view, but in the recording there is no audio.
I use a Hikvision DS-2CD2142FWD-IWS with G.711 ulaw
I tried several different config changes now.
My config below works. Recordings also work, but no sound.
When I change - path: rtsp://127.0.0.1:8554/haustuer to - path: rtsp://127.0.0.1:8554/haustuer?video&audio my recordings are not playable any more, but no errors in the logs.
If I understand correctly normally it should be 
output_args:
        record: preset-record-generic-audio-aac
together with ?video&audio
for G.711ulaw.
Any help is appreciated. 

### Version

0.14

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.50
  user: user
  password: pass
go2rtc:
  streams:
    haustuer:
      - rtsp://user:pass@192.168.178.69/Streaming/Channels/101
      #- "ffmpeg:front#audio=aac"
      #- isapi://user:pass@192.168.178.69:80/
    haustuer_sub:
      - rtsp://user:pass@192.168.178.69/Streaming/Channels/102

tls: 
  enabled: true
  
cameras:
  haustuer: # <------ Name the camera
    enabled: true
    snapshots:
      enabled: true
      retain:
        default: 10
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/haustuer
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/haustuer_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    detect:
      width: 640
      height: 360
      fps: 4
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 7
    review:
      alerts:
        required_zones: front_yard
      detections:
        required_zones: front_yard
    objects:
      track:
        - person
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          #min_area: 5000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          #min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
    motion:
      mask: 
        0.246,0.003,0.264,0.292,0.455,0.264,0.64,0.264,0.713,0.287,0.998,0.382,0.989,0.677,0.729,0.73,0.658,0.61,0.649,0.59,0.643,0.515,0.645,0.434,0.646,0.343,0.6,0.374,0.557,0.421,0.571,0.476,0.578,0.541,0.602,0.613,0.677,0.58,0.742,0.8,0.792,0.836,0.993,0.775,0.996,0.995,0.001,0.995,0.004,0.005
      threshold: 40
      contour_area: 15
      improve_contrast: 'true'
    zones: # Move zones here
      front_yard:
        coordinates: 
          1280,720,1280,352,1194,265,1147,224,1075,177,1059,186,848,137,409,94,309,94,0,121,0,631,0,720,434,720

version: 0.14
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
None
```

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
Did you try transcoding with go2rtc? Eg:

```
    haustuer:
      - rtsp://user:pass@192.168.178.69/Streaming/Channels/101
      - "ffmpeg:hauster#audio=aac"
```

You could also try:

```
    haustuer:
      - ffmpeg:rtsp://user:pass@192.168.178.69/Streaming/Channels/101#video=copy#audio=aac
```

**Comment by BenJ1337** [comment]
The following proposed configuration works with Tapo C200 and Frigate 0.15.1

```yaml
go2rtc:
  streams:
    c200_main_stream:
      - rtsp://{FRIGATE_RTSP_USER_C200}:{FRIGATE_RTSP_PASSWORD_C200}@<ip of c200>:554/stream1

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  inputs:
    - path: rtsp://127.0.0.1:8554/c200_main_stream?video&audio
      input_args: preset-rtsp-restream
```

Source:
https://www.reddit.com/r/frigate_nvr/comments/17zv4jt/comment/ka1rc7m/
