### DISCUSSION TITLE
[Support]: ffmpeg errors when using audio detection with restream

### DISCUSSION THREAD

**Discussion by lngarrett** [blakeblackshear/frigate#16140] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I switched to restream, I started seeing ffmpeg errors. Disabling audio events resolves the issue. I've observed this behavior on `stable` and the latest beta rc using ffpmeg 7. 

```
2025-01-25 16:32:46.139850191 [2025-01-25 16:32:46] audio.bporchcam ERROR : ffmpeg process is not running, restarting...
2025-01-25 16:32:45.274493443 [2025-01-25 16:32:45] audio.bporchcam INFO : Waiting for ffmpeg to exit gracefully...
2025-01-25 16:32:45.274465341 [2025-01-25 16:32:45] audio.bporchcam INFO : Terminating the existing ffmpeg process...
2025-01-25 16:32:45.274444701 [2025-01-25 16:32:45] ffmpeg.bporchcam.audio ERROR : Output file #0 does not contain any stream
2025-01-25 16:32:35.264288611 [2025-01-25 16:32:35] audio.bporchcam ERROR : ffmpeg process is not running, restarting...
```

### Steps to reproduce

1. Configure restream
2. Configure audio event detection
...

### Version

v0.15.0-rc1 6d8234f (0.14.x stable does it too)

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
cameras:
  parkingcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/parkingcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/parkingcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

  westcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/westcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/westcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

  bporchcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/bporchcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/bporchcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

  byardcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/byardcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/byardcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

  eastcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/eastcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/eastcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask:
        - 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
        - 0.502,0.745,0.585,0.606,0.666,0.569,0.802,0.507,0.96,0.58,0.995,0.985,0.501,0.993
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'

  neighborcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/neighborcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/neighborcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.578,0.943,0.95,0.944,0.948,0.985,0.578,0.98

  alleynwcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/alleynwcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/alleynwcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

  alleysecam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/alleysecam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/alleysecam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

  porchcam:
    enabled: true
    ffmpeg:
      inputs:
          # Substream
        - path: rtsp://127.0.0.1:8554/porchcam_sub
          roles:
            - detect
            - audio
          # Mainstream
        - path: rtsp://127.0.0.1:8554/porchcam
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977

go2rtc:
  rtsp:
    username: admin
    password: password
  streams:
    parkingcam:
      - rtsp://admin:password@parkingcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:parkingcam#audio=opus"
    parkingcam_sub:
      - rtsp://admin:password@parkingcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:parkingcam_sub#audio=opus"
    westcam:
      - rtsp://admin:password@westcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:westcam#audio=opus"
    westcam_sub:
      - rtsp://admin:password@westcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:westcam_sub#audio=opus"
    bporchcam:
      - rtsp://admin:password@bporchcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:bporchcam#audio=opus"
    bporchcam_sub:
      - rtsp://admin:password@bporchcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:bporchcam_sub#audio=opus"
    byardcam:
      - rtsp://admin:password@byardcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:byardcam#audio=opus"
    byardcam_sub:
      - rtsp://admin:password@byardcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:byardcam_sub#audio=opus"
    eastcam:
      - rtsp://admin:password@eastcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:eastcam#audio=opus"
    eastcam_sub:
      - rtsp://admin:password@eastcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:eastcam_sub#audio=opus"
    neighborcam:
      - rtsp://admin:password@neighborcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:neighborcam#audio=opus"
    neighborcam_sub:
      - rtsp://admin:password@neighborcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:neighborcam_sub#audio=opus"
    alleynwcam:
      - rtsp://admin:password@alleynwcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:alleynwcam#audio=opus"
    alleynwcam_sub:
      - rtsp://admin:password@alleynwcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:alleynwcam_sub#audio=opus"
    alleysecam:
      - rtsp://admin:password@alleysecam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:alleysecam#audio=opus"
    alleysecam_sub:
      - rtsp://admin:password@alleysecam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:alleysecam_sub#audio=opus"
    porchcam:
      - rtsp://admin:password@porchcam.example.com:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:porchcam#audio=opus"
    porchcam_sub:
      - rtsp://admin:password@porchcam.example.com:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:porchcam_sub#audio=opus"

audio: # <- enable audio events for all camera
  enabled: true

birdseye:
  enabled: true
  mode: motion

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
auth:
  enabled: false
  trusted_proxies:
    - 172.18.0.0/16
proxy:
  header_map:
    user: x-authentik-username

tls:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

mqtt:
  enabled: true
  host: legionary.example.com
  user: hass
  password: pbb6egoyn5jxrq5

version: 0.15-1
camera_groups:
  BE:
    order: 1
    icon: LuBird
    cameras: birdseye

semantic_search:
  enabled: true
  model_size: large
  reindex: false
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate-house:
    container_name: frigate-house
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1
    shm_size: "1500mb"
    devices:
      - /dev/dri:/dev/dri
    cap_add:
      - CAP_PERFMON
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/warehouse/frigate/house:/config
      - /data/blueiris/frigate/house:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
      - traefik
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "127.0.0.1:8971:8971"  
      - "127.0.0.1:5050:5000" # note 5050 host port 
      - "127.0.0.1:8554:8554"  
      - "127.0.0.1:8555:8555" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.security-beta.rule=Host(`security-beta.example.com`)"
      - "traefik.http.routers.security-beta.entrypoints=websecure"
      - "traefik.http.routers.security-beta.tls.certresolver=myresolver"
      - "traefik.http.routers.security-beta.middlewares=authentik@file"
      - "traefik.http.services.security-beta.loadbalancer.server.port=8971"

networks:
  traefik:
    external: true
```

### Relevant Frigate log output

```shell
2025-01-25 16:32:46.139850191 [2025-01-25 16:32:46] audio.bporchcam ERROR : ffmpeg process is not running, restarting...
2025-01-25 16:32:45.274493443 [2025-01-25 16:32:45] audio.bporchcam INFO : Waiting for ffmpeg to exit gracefully...
2025-01-25 16:32:45.274465341 [2025-01-25 16:32:45] audio.bporchcam INFO : Terminating the existing ffmpeg process...
2025-01-25 16:32:45.274444701 [2025-01-25 16:32:45] ffmpeg.bporchcam.audio ERROR : Output file #0 does not contain any stream
2025-01-25 16:32:35.264288611 [2025-01-25 16:32:35] audio.bporchcam ERROR : ffmpeg process is not running, restarting...
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua 5442

### Screenshots of the Frigate UI's System metrics pages

all metrics are nominal
