### DISCUSSION TITLE
[Support]: Alerts in required_zones: not being respected

### DISCUSSION THREAD

**Discussion by Morphy99** [blakeblackshear/frigate#16149] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I've been getting the occasional event from objects in zones which aren't under `required_zones:` but they're being classified as Alerts and thus I'm getting notifications to my phone. This particular camera is the doorbell in the config and is a Reolink POE doorbell.

I've re-run the clip as a file input and looked in debugging but the only zones that get triggered are those out of the alert required zones bizarrely. 

### Steps to reproduce

1. Can't reproduce as it appears random
2.
3.
...

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: xxxxx

detectors:
  coral0:
    type: edgetpu
    device: pci:0
auth:
  enabled: false
objects:
  track:
    - person
    - dog
    - cat
review:
  alerts:
    labels:
      - person

record:
  expire_interval: 10
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 20
      mode: motion
    post_capture: 30

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 20

detect:
  stationary:
    interval: 10

motion:
  improve_contrast: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    front:
      - rtsp://admin:xxxxx@192.168.0.21/H265/ch1/main/av_stream
    front_sub:
      - rtsp://admin:xxxxx@192.168.0.21/H265/ch1/sub/av_stream
    doorbell:
      - ffmpeg:http://192.168.0.29/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=xxxxx#video=copy#audio=copy#audio=opus
    doorbell_sub:
      - ffmpeg:http://192.168.0.29/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=xxxxx
    back:
      - ffmpeg:http://192.168.0.26/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=xxxxx#video=copy#audio=copy#audio=opus
    back_sub:
      - ffmpeg:http://192.168.0.26/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password=xxxxx
    side:
      - rtsp://admin:xxxxx@192.168.0.27/H265/ch1/main/av_stream
      - ffmpeg:rtsp://admin:xxxxx@192.168.0.27/H265/ch1/main/av_stream#audio=opus
      - onvif://ha:xxxxx@192.168.0.27
      - isapi://admin:xxxxx@192.168.0.27:80
    side_h264:
      - rtsp://admin:xxxxx@192.168.0.27/H264/ch1/main/av_stream
      - ffmpeg:side#video=h264#audio=opus#hardware
    side_sub:
      - rtsp://admin:xxxxx@192.168.0.27/H265/ch1/sub/av_stream

  webrtc:
    candidates:
      - 192.168.0.5:8555
      - stun:8555

birdseye:
  enabled: false

cameras:

##############################################################front########################################################################
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:

            - detect
#            - audio
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 6
    zones:
      front_garden:
        coordinates: 0.231,0.999,0.171,0.686,0.373,0.499,0.918,0.885,0.86,1
        loitering_time: 0
        objects:
          - dog
          - person
      front_path:
        coordinates: 0.371,0.494,0.446,0.298,1,0.63,0.926,0.888
        loitering_time: 0
        objects:
          - dog
          - person
      front_drive:
        coordinates: 0.446,0.295,0.489,0.156,0.927,0.367,0.901,0.564
        loitering_time: 0
        objects:
          - dog
          - person
      front_street_path:
        coordinates: 
          0,0.606,0.003,0.251,0.294,0.115,0.489,0.057,0.49,0.153,0.445,0.292,0.37,0.496,0.169,0.681,0.133,0.545
        loitering_time: 0
        objects:
          - dog
          - person
      front_street_road:
        coordinates: 0,0.178,0,0.249,0.321,0.099,0.484,0.058,0.547,0.057,0.55,0.022,0.336,0.049
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - front_drive
          - front_garden
          - front_path
      detections:
        required_zones:
          - front_drive
          - front_garden
          - front_street_path
          - front_path
          - front_street_road
    objects:
      filters:
        person:
          threshold: 0.7
          max_ratio: 0.6
    mqtt:
      required_zones:
        - front_drive
        - front_garden
        - front_path
    snapshots:
      required_zones:
        - front_drive
        - front_garden
        - front_street_path
        - front_path
        - front_street_road

##############################################################doorbell######################################################################

  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 672
      fps: 20
    zones:
      front_garden:
        coordinates: 0.001,0.702,0.224,0.629,0.356,0.656,0.306,0.841,0.075,0.964,0.022,0.852
        loitering_time: 0
        objects:
          - dog
          - person
      front_path:
        coordinates: 0.079,0.966,0.104,0.999,0.7,0.996,0.502,0.638,0.36,0.653,0.309,0.844
        loitering_time: 0
        objects:
          - dog
          - person
      front_drive:
        coordinates: 0.505,0.638,0.75,0.591,1,0.728,0.903,0.999,0.704,1
        loitering_time: 0
        objects:
          - dog
          - person
      front_38:
        coordinates: 0,0.665,0.216,0.617,0.213,0.504,0,0.464
        loitering_time: 0
        objects:
          - dog
          - person
      front_street:
        coordinates: 
          0.214,0.488,0.218,0.625,0.351,0.652,0.504,0.633,0.753,0.587,0.744,0.519,0.438,0.52,0.314,0.513
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        person:
          threshold: 0.7
          max_ratio: 0.6
    mqtt:
      required_zones:
        - front_drive
        - front_garden
        - front_path
    snapshots:
      required_zones:
        - front_38
        - front_drive
        - front_garden
        - front_path
        - front_street
    review:
      alerts:
        required_zones:
          - front_drive
          - front_garden
          - front_path
      detections:
        required_zones:
          - front_38
          - front_drive
          - front_garden
          - front_path
          - front_street
#
##############################################################back######################################################################

  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2048
      height: 1536
      fps: 8
    objects:
      filters:
        person:
          threshold: 0.7
          max_ratio: 0.6
      track:
        - person
        - cat
        - dog
    zones:
      back_patio_right:
        coordinates: 0,0.722,0.467,0.339,0.986,0.585,0.856,1,0,1
        loitering_time: 0
        filters:
          person:
            min_area: 200000
            max_area: 400000
      back_patio_left:
        coordinates: 0.465,0.337,0.314,0.217,0.001,0.459,0,0.717
        loitering_time: 0
        filters:
          person:
            min_area: 100000
            max_area: 300000
      back_garden_right:
        coordinates: 0.985,0.575,0.994,0.095,0.649,0.042,0.467,0.339
        loitering_time: 0
      back_garden_left:
        coordinates: 0.649,0.036,0.448,0.001,0,0.007,0,0.458,0.312,0.217,0.469,0.334
        loitering_time: 0
        filters:
          person:
            min_area: 10000
            max_area: 300000
    mqtt:
      required_zones:
        - back_garden_left
        - back_garden_right
        - back_patio_left
        - back_patio_right
    snapshots:
      required_zones:
        - back_garden_left
        - back_garden_right
        - back_patio_left
        - back_patio_right
    review:
      detections:
        required_zones:
          - back_garden_left
          - back_garden_right
          - back_patio_left
          - back_patio_right
      alerts:
        required_zones:
          - back_garden_left
          - back_garden_right
          - back_patio_left
          - back_patio_right
###############################################################side######################################################################
  side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    detect:
      width: 1200
      height: 536
      fps: 6
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.7
          max_ratio: 1.0

    motion:
      mask:
        - 0.474,0,0.415,0.266,0.341,0.273,0.246,0.358,0.221,0.497,0.198,0.586,0.135,0.512,0,0.382,0.002,0.006
        - 0.67,0,0.826,0.179,0.985,0.573,1,0.569,1,0
    zones:
      Side_Path_Gate:
        coordinates: 0.076,0.659,0.128,0.505,0.278,0.716,0.228,0.949
        loitering_time: 0
        filters:
          person:
            min_area: 20000
            max_area: 40000
          dog:
            min_area: 1000
            max_area: 20000
      Side_Path_Door:
        coordinates: 0.279,0.716,0.219,1,0.875,1,0.8,0.707,0.537,0.787
        loitering_time: 0
        filters:
          person:
            min_area: 20000
            max_area: 40000
          dog:
            min_area: 1000
            max_area: 20000
        inertia: 3
      Back_Garden_Left:
        coordinates: 0.839,0.851,0.954,0.635,0.815,0.22,0.669,0.22,0.796,0.676
        loitering_time: 0
        filters:
          person:
            min_area: 1000
            max_area: 15000
          dog:
            min_area: 500
            max_area: 5000
      Back_Garden_Side:
        coordinates: 
          0.801,0.702,0.535,0.782,0.278,0.712,0.14,0.518,0.267,0.331,0.474,0.26,0.665,0.211
        loitering_time: 0
        filters:
          person:
            min_area: 1000
            max_area: 15000
          dog:
            min_area: 500
            max_area: 5000
version: 0.14
camera_groups:
  Main:
    order: 1
    icon: LuHome
    cameras:
      - front
      - doorbell
```

### docker-compose file or Docker CLI command

```yaml
HA OS
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink Doorbell POE

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/e06af045-21b6-41f3-ba70-b8eed5497e75)
![image](https://github.com/user-attachments/assets/1d32d0ca-4e69-4264-b42d-645072c00f75)
![image](https://github.com/user-attachments/assets/cfce53e5-0873-4f52-9602-85a4894a2b7e)
![image](https://github.com/user-attachments/assets/a294748b-70b7-4fdc-8eb3-24b385e7e2a9)

### Any other information that may be helpful

Events:
![image](https://github.com/user-attachments/assets/b83dfd8c-3044-488b-8c11-9baf008a11bb)
Zones:
![image](https://github.com/user-attachments/assets/744bd2cd-1c15-44da-a9cb-e3383b56344b)
Required zones:
![image](https://github.com/user-attachments/assets/dd38d2e4-b7b2-41b6-8147-ee8d5c4aa208)
