### DISCUSSION TITLE
[Support]: Lost frigate+ icon and ability to send images to frigate+

### DISCUSSION THREAD

**Discussion by horspiste** [blakeblackshear/frigate#16150] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I've lost the ability to send images to frigate+. The frigate+ icon has disapeared from the left menu. I don't see any other way to send images. Tried in chrome and chrome incognito and in edge. I remember that it was working fine a few weeks ago, it probably stopped after installed one the of the current betas. Currently running RC1.

To see if it was my api key that was not working, I've generated a new frigate+ api key and updated the docker-compose environment variables and did verify that the variable is set  properly by going into the frigate container shell (docker exec ...).

I see nothing in the logs.
![image](https://github.com/user-attachments/assets/e9a130f2-25fa-4d55-828c-dd3a554d367b)

### Steps to reproduce

1. start frigate
2. look at ui
3.
...

### Version

0.15.0-6d8234f

### In which browser(s) are you experiencing the issue with?

Chrome Version 131.0.6778.265 (Official Build) (64-bit) and Edge

### Frigate config file

```yaml
logger:
  default: warning
detectors:
  coral_m2_1:
    type: edgetpu
    device: pci:0
  coral_m2_2:
    type: edgetpu
    device: pci:1


model:
  path: plus://(redacted)

database:
# note that this database path is remapped in docker-compose.
  path: /db/frigate.db
mqtt:
  # Required: host name
  host: ubuntuvm2.vdl.local
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mqtt
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}
  password: '{FRIGATE_MQTT_PASSWORD}'
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
birdseye:
  restream: true
#ffmpeg:
#  hwaccel_args: preset-vaapi
go2rtc:
  streams:
#    ENT:
#      - ffmpeg:http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
##    - ffmpeg:http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#video=copy
#    - ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.149/h264Preview_01_main#video=copy
##    - ffmpeg:ENT
    ENT_sub:
      - ffmpeg:http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#video=copy
#      - ffmpeg:ENT_sub
    ENT2:
      - ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.147/h265Preview_01_main
      - ffmpeg:ENT2#audio=opus#audio=copy
    ENT2_sub:
      - ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.147/h264Preview_01_sub#video=copy
#    - ffmpeg:ENT2_sub
    Gar:
      - ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.150/h265Preview_01_main
#      - http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}video=copy#audio=copy#audio=opus
      - ffmpeg:Gar#audio=opus#audio=copy
    Gar_sub:
      - ffmpeg:http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#video=copy
#      - ffmpeg:Gar_sub
    Gen:
      - ffmpeg:rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.151/h265Preview_01_main
      - ffmpeg:Gen#audio=opus#audio=copy

    Gen_sub:
      - ffmpeg:http://192.168.2.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#video=copy
#      - ffmpeg:Gen_sub

#ffmpeg:
#  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
objects:
  track:
    - person
    - car
    - truck
    - bicycle
    - motorcycle
    - dog
    - cat
    - deer
    - racoon
    - fox
    - bear
    - rabbit
    - fedex
    - ups
    - dhl
    - purolator
    - face
  filters:
    person:
#      min_score: 0.4
#      threshold: 0.6
      min_area: 600
      max_area: 100000
    car:
      min_area: 5000
    cat:
      max_area: 100000
# Global Record Config
record:
  sync_recordings: true
  enabled: true
  retain:
    days: 5
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  crop: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  retain:
    default: 30

cameras:
  # Name of your camera
  ENT:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ENT_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: 
            http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
##      - path: rtsp://127.0.0.1:8554/ENT?video=copy
          input_args: preset-http-reolink
          roles:
            - record
    detect:
      width: 896
      height: 672
      fps: 4
    motion:
      mask:
        - 172,406,212,672,896,672,896,281
        - 41,95,93,88,94,0,38,0
        - 488,45,566,46,568,0,487,0
    objects:
      filters:
        person: {}
      mask: 0.03,0.002,0.035,0.161,0.119,0.161,0.128,0.003
  ENT2:
#    audio:
#      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/ENT2?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
        - path: rtsp://127.0.0.1:8554/ENT2_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 7
    motion:
      mask:
        - 480,34,574,37,575,0,484,0
  Gar:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Gar_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Gar?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 7
    motion:
      mask:
        - 483,34,567,36,572,0,486,0
  Gen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Gen_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Gen?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 727,184,856,102
    detect:
      width: 896
      height: 512
      fps: 7
    motion:
      mask:
        - 483,34,567,36,572,0,486,0
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuActivity
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1
    cap_add:
      - CAP_PERFMON
    shm_size: "256mb"
    devices:
      - /dev/dri/card0
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/config/
# the databases are stored in the local db directory because the default location does not work well when CIFS
      - ./db:/db
#     - ./media/:/media/frigate
      - /mnt/FastStorage/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554"
      - "8555:8555"
      - "1984:1984" # go2rtc web interface
    environment:
      FRIGATE_RTSP_PASSWORD: "redacted"
      FRIGATE_MQTT_PASSWORD: "redacted"
      PLUS_API_KEY: 'redacted'
```

### Relevant Frigate log output

```shell
Only errors with my reolink cameras but this is a different issue.
```

### Relevant go2rtc log output

```shell
Nothing
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

many reolinks 

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/573289b9-b667-40cb-a53a-7a565f5c3983)
