### DISCUSSION TITLE
[Detector Support]: Very High CPU Load for ONNX Model

### DISCUSSION THREAD

**Discussion by cknic** [blakeblackshear/frigate#16151] [Detector Support]
### Describe the problem you are having

I have had this issue with 15 beta (since 4) and still on the RC.  I am using the Frigate+ models with Onnx as i have two NVIDIA GPUs (1070ti & 4060ti).  This is running as docker on a ubuntu machine with AMD CPU, 48 cores (96 threads).  I am seeing huge CPU usage on average 60%+ and the detection time is up to 50ms.  It was a lot better in the past, i am not sure what changed to be honest.  It got to the point where i had to shut down frigate because the speed became so slow it wasn't worth it.  

### Version

0.15.0-rc1

### Frigate config file

```yaml
mqtt: # If you have a MQTT server then update this section, if not delete it.
  enabled: true
  host: <hostname>
  port: 1883
  topic_prefix: frigate
  user: frigate
  password:  <password>

ffmpeg:
  hwaccel_args: preset-nvidia

go2rtc:
  streams:
    doorbell: # <- for RTSP streams
      - rtsp://172.16.11.108:33159/979e46ba857111f6 # <- stream which supports video & aac audio
    doorbell-package: # <- for RTSP streams
      - rtsp://172.16.11.108:33159/64027b8b62cb90a6 # <- stream which supports video & aac audio
    landing: # <- for RTSP streams
      - rtsp://172.16.11.108:37705/530fee13281852c7 # <- stream which supports video & aac audio
    family: # <- for RTSP streams
      - rtsp://172.16.11.108:40845/87b18fd3ab061e33 # <- stream which supports video & aac audio
    dining: # <- for RTSP streams
      - rtsp://172.16.11.108:39285/1c58a4ba95f04d88 # <- stream which supports video & aac audio
    bar: # <- for RTSP streams
      - rtsp://172.16.11.108:41343/7566c865ac4e250c # <- stream which supports video & aac audio
    kitchen: # <- for RTSP streams
      - rtsp://172.16.11.108:42065/bef2fea3a0c5aecb # <- stream which supports video & aac audio
    backyard: # <- for RTSP streams
      - rtsp://172.16.11.108:45091/7b0117145271e027 # <- stream which supports video & aac audio
    basement-stairs: # <- for RTSP streams
      - rtsp://172.16.11.108:43211/c242a6a34eb1df69 # <- stream which supports video & aac audio
    basement-left: # <- for RTSP streams
      - rtsp://172.16.11.108:44649/7ab16abf45ee2f35 # <- stream which supports video & aac audio
    basement-right: # <- for RTSP streams
      - rtsp://172.16.11.108:36215/295d08600bc1dad5 # <- stream which supports video & aac audio
  webrtc:
    candidates:
      - 172.16.11.108:8555
      - stun:8555

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/doorbell # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio # <- only necessary if audio detection is enabled
    motion:
      mask: 0.003,0.335,0.994,0.447,0.996,0.003,0.001,0.003
      threshold: 40
      contour_area: 24
      improve_contrast: true
    objects:
      mask: 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
      filters:
        car:
          mask:
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.728,0.518,0.753,0.478,0.92,0.501,0.968,0.527,0.9,0.556
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.942,0.566,0.959,0.546,0.972,0.534,0.978,0.562,0.977,0.601,0.964,0.643,0.878,0.592
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.28,0.635,0.809,0.708,0.996,0.966,0.888,1,0.26,0.998,0.012,0.99,0.022,0.721
        person:
          mask:
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.551,0.786,0.611,0.804,0.606,0.853,0.558,0.841
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.377,0.773,0.394,0.756,0.286,0.689,0.267,0.706
            - 0.005,0.338,0.001,0,0.995,0.003,0.995,0.445
            - 0.79,0.772,0.858,0.744,0.852,0.533,0.764,0.543
    zones:
      porch:
        coordinates: 
          0.271,0.694,0.397,0.752,0.609,0.821,0.809,0.808,0.856,0.956,0.825,0.995,0.204,1,0.1,0.766
        loitering_time: 0
        inertia: 3
      driveway:
        coordinates: 0.212,0.642,0.479,0.573,0.389,0.55,0.31,0.558,0.193,0.573
        loitering_time: 0
      walkway:
        coordinates: 
          0.333,0.617,0.414,0.626,0.523,0.668,0.587,0.723,0.593,0.754,0.577,0.803,0.438,0.761,0.481,0.71,0.437,0.672,0.303,0.625
        loitering_time: 0
      street:
        coordinates: 
          0.289,0.513,0.387,0.55,0.529,0.576,0.785,0.594,0.935,0.57,0.96,0.553,0.943,0.534,0.906,0.552,0.832,0.561,0.75,0.558,0.596,0.555,0.456,0.529,0.332,0.503
        loitering_time: 0
      yard:
        coordinates: 
          0.492,0.573,0.354,0.61,0.465,0.641,0.571,0.699,0.598,0.748,0.585,0.799,0.808,0.799,0.863,0.803,0.935,0.752,0.967,0.642,0.872,0.594,0.623,0.594
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - porch
          - driveway
          - walkway
      detections:
        required_zones:
          - street
          - yard
  doorbell-package:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/doorbell-package # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 45
      contour_area: 30
      improve_contrast: true
    zones:
      Package-Porch:
        coordinates: 
          0.147,0.024,0.967,0.301,0.995,0.994,0.694,0.998,0.23,0.869,0.001,0.607,0.003,0.16
        loitering_time: 0
      package-walkway:
        coordinates: 0.62,0.18,0.626,0.002,0.475,0,0.428,0.104
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Package-Porch
          - package-walkway
  landing:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/landing # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio # <- only necessary if audio detection is enabled
    objects:
      track:
        - person
        - face
        - dog
        - cat
      mask: 0.75,0.233,0.797,0.262,0.821,0.034,0.77,0.014
    motion:
      mask:
        - 0.002,0.033,0.199,0.036,0.199,0.003,0.004,0.002
        - 0.775,0.019,0.751,0.232,0.794,0.259,0.818,0.029
    zones:
      stairs:
        coordinates: 0.513,0.664,0.642,0.861,0.718,0.758,0.747,0.556,0.703,0.557,0.652,0.569
        loitering_time: 0
      carters-room:
        coordinates: 0.859,0.062,0.742,0.779,0.859,0.938,1,0.434,0.998,0.173,0.916,0.099
        loitering_time: 0
      master:
        coordinates: 0.268,0.482,0.353,0.444,0.343,0.002,0.243,0.005
        loitering_time: 0
      landing-floor:
        coordinates: 
          0.856,0.943,0.84,0.998,0.328,0.993,0.248,0.6,0.284,0.587,0.269,0.487,0.353,0.446,0.359,0.22,0.521,0.178,0.705,0.319,0.685,0.535,0.512,0.659,0.642,0.873,0.722,0.76
        loitering_time: 0
    review:
      alerts:
        required_zones: master
  family:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/family # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
    motion:
      threshold: 61
      contour_area: 36
      improve_contrast: true
      mask: 0.007,0.027,0.194,0.031,0.197,0.005,0.001,0.003
    zones:
      All:
        coordinates: 0.974,0.028,0.979,0.965,0.028,0.941,0.023,0.003
        loitering_time: 0
    review:
      alerts: {}
      detections:
        required_zones: All
  bar:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/bar # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
      mask: 0.798,0.196,0.936,0.332,0.953,0.151,0.813,0.048
    motion:
      mask:
        - 0.81,0.197,0.933,0.317,0.951,0.151,0.818,0.053
        - 0.003,0.034,0.203,0.036,0.202,0.003,0.004,0.002
      threshold: 45
      contour_area: 23
      improve_contrast: true
    zones:
      Bar:
        coordinates: 0.16,0.986,0.212,0.581,0.279,0.381,0.372,0.201,0.472,0.192,0.493,0.991
        loitering_time: 0
      Counter:
        coordinates: 0.056,0.319,0.21,0.273,0.237,0.197,0.216,0.045,0.095,0.053,0.046,0.089
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - Bar
          - Counter
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/kitchen # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
      mask: 0.541,0.191,0.639,0.204,0.64,0.111,0.547,0.09
    motion:
      mask:
        - 0.543,0.189,0.637,0.207,0.639,0.113,0.548,0.094
        - 0.004,0.033,0.202,0.034,0.202,0,0.003,-0.002
      threshold: 42
      contour_area: 25
      improve_contrast: true
    zones:
      Kitchen-Coffee-Counter:
        coordinates: 
          0.276,0.389,0.33,0.427,0.464,0.317,0.419,0.288,0.43,0.134,0.436,0.046,0.276,0.075
        loitering_time: 0
        objects: person
      Kitchen-Counter:
        coordinates: 0.558,0.991,0.704,0.535,0.838,0.605,0.8,0.997
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - Kitchen-Coffee-Counter
          - Kitchen-Counter
  dining:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/dining # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - package
      mask:
        - 0.678,0.076,0.747,0.091,0.75,0.2,0.685,0.193
        - 0.782,0.109,0.818,0.109,0.822,0.189,0.791,0.192
        - 0.192,0.239,0.193,0.072,0.157,0.053,0.156,0.246
    motion:
      mask: 0.003,0.033,0.203,0.034,0.202,0.002,0.003,0.002
    zones:
      stairs:
        coordinates: 0.325,0.494,0.431,0.46,0.59,0.148,0.58,0.002,0.288,0.007,0.308,0.487
        loitering_time: 0
    review:
      alerts:
        required_zones: stairs
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/backyard # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio # <- only necessary if audio detection is enabled
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - umbrella
      filters:
        car:
          mask: 0.099,0.122,0.096,0.071,0.123,0.008,0.645,0.018,0.637,0.069,0.372,0.071
    motion:
      mask:
        - 0.727,0.057,0.73,0.086,0.945,0.084,0.937,0.058
        - 0.64,0.058,0.635,0.069,0.363,0.071,0.248,0.091,0.099,0.125,0.094,0.073,0.124,0.008,0.228,0,0.346,0.008,0.5,0.01,0.644,0.019
    zones:
      deck:
        coordinates: 0.075,0.33,0.62,0.184,0.95,0.439,0.654,0.99,0.198,0.994,0.047,0.4
        loitering_time: 0
      yard-back:
        coordinates: 0.083,0.311,0.542,0.184,0.79,0.17,0.681,0.099,0.376,0.091,0.026,0.196
        loitering_time: 0
      patio:
        coordinates: 0.951,0.429,0.991,0.327,0.841,0.188,0.676,0.188
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - patio
          - deck
  basement-stairs:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/basement-stairs # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.766,0.024,0.769,0.063,0.987,0.063,0.985,0.027
      threshold: 39
      contour_area: 25
      improve_contrast: true
    zones:
      basement-staircase:
        coordinates: 0.298,0.012,0.415,0.299,0.582,0.449,0.614,0.338,0.575,0
        loitering_time: 0
    objects:
      track:
        - person
        - face
    review:
      alerts:
        required_zones: basement-staircase
  basement-left:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/basement-left # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
    zones:
      washer:
        coordinates: 0.577,0.217,0.821,0.252,0.841,0.057,0.494,0.015,0.437,0.047
        loitering_time: 0
    motion:
      threshold: 40
      contour_area: 25
      improve_contrast: true
    review:
      alerts:
        required_zones: washer
  basement-right:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.11.108:8554/basement-right # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
    motion:
      threshold: 57
      contour_area: 48
      improve_contrast: true
      mask: 0.745,0.045,0.745,0.065,0.963,0.071,0.963,0.04
    zones:
      dryer:
        coordinates: 0.264,0.697,1,0.409,0.996,0.994,0.005,0.997,0.001,0.484
        loitering_time: 0
    review:
      alerts:
        required_zones: dryer
detectors:
#  tensorrt:
#    type: tensorrt
#    device: 1
  onnx_0:
    type: onnx
  onnx_1:
    type: onnx

model:
#  path: /config/model_cache/tensorrt/yolov7-320.trt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 320
#  height: 320
  path: plus://<pluskey>

version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
#genai:
#  enabled: false
#  provider: openai
#  api_key: 
#    <api-key>
#  model: gpt-4o-mini
genai:
  enabled: false
  provider: ollama
  base_url: http://172.16.11.125:11434
  model: llava:7b

record:
  enabled: true
  retain:
    days: 7
    mode: all
snapshots:
  enabled: true
  retain:
    default: 30

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: true
  width: 1920
  height: 1080
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  # Optional: Threshold for camera activity to stop showing camera (default: shown below)
  inactivity_threshold: 10
  layout:
    scaling_factor: 1.0
  # Optional: Configure the birdseye layout

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
    - package
    - face
    - amazon
    - fedex
    - ups
    - package
    - usps
    - dhl
  # Optional: filters to reduce false positives for specific object types

motion:
  # Optional: enables detection for the camera (default: True)
  # NOTE: Motion detection is required for object detection,
  #       setting this to False and leaving detect enabled
  #       will result in an error on startup.
  enabled: true
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  # Optional: motion mask
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
  Inside:
    order: 2
    icon: LuTv
    cameras:
      - landing
      - family
      - bar
      - dining
      - kitchen
  Outside:
    order: 3
    icon: LuTrees
    cameras:
      - doorbell
      - doorbell-package
      - backyard
  Basement:
    order: 4
    icon: LuToyBrick
    cameras:
      - basement-stairs
      - basement-left
      - basement-right
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: false # this may not be necessary for all setups
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1-tensorrt #<---Latest stable Frigate image with nvidia drivers and toolkit
    shm_size: "4096mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb/006:/dev/bus/usb/006 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
# passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidia-modeset
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-caps/nvidia-cap1
      - /dev/nvidia-caps/nvidia-cap2

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/model_cache:/config/model_cache
      - /opt/frigate/config.yaml:/config/config.yml
      - /Media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_USER=admin
      - FRIGATE_RTSP_PASSWORD=<password>
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - YOLO_MODELS=yolov7-320,yolov4-608,yolov7x-640
      - TRT_MODEL_PREP_DEVICE=1
      - PLUS_API_KEY=<api-key>

    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2 # number of GPUs
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
i don't have the logs atm but there were no errors that i saw.
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

<img width="1462" alt="Screenshot 2025-01-26 at 12 07 58 PM" src="https://github.com/user-attachments/assets/50548d90-f928-4aaf-aa6d-cc4e81968a30" />
<img width="1423" alt="Screenshot 2025-01-26 at 12 08 09 PM" src="https://github.com/user-attachments/assets/ef2bfc98-295b-4b4e-996c-ef362fd123d0" />
<img width="1379" alt="Screenshot 2025-01-26 at 12 08 20 PM" src="https://github.com/user-attachments/assets/a618e303-7c58-4466-bb2d-de46fbfee2d0" />
