### DISCUSSION TITLE
[Config Support]: Can't seem to get audio recording but audio present in live stream

### DISCUSSION THREAD

**Discussion by btrudgill** [blakeblackshear/frigate#16164] [Config Support] [answered]
### Describe the problem you are having

Hi,
The audio coming from my reolink cameras is AAC format, I want to record the audio as well as video. Previously I recorded the main stream and detect stream was the sub stream, however I found that I missed a few events due to the low resolution of the sub stream. Detecting on the main stream works much better, but now I seem to not be able to record audio (even though it did before...).

### Version

0.15.0-6d8234f

### Frigate config file

```yaml
mqtt:
  host: 
  port: 
  user: 
  password: 

detectors:
  coral:
    type: edgetpu
    device: pci

semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: true
  provider: gemini
  api_key: 
  model: gemini-1.5-flash #-8b
  prompt: Analyze the {label} in these images from the {camera} security camera using
    only 2 sentences. Focus on the actions and behavior of the {label}. Be succinct
    and only give relevant information. No preamble!
  object_prompts:
    package: In one sentence describe the {label} seen on the {camera} security camera,
      including shape, size, and colour. Specify what company it is from if the company
      logo is visible.
  #prompt: Very briefly describe what you see in this image from my security camera. Your message needs to be short to fit in a phone notification. Don't describe stationary objects or buildings. Don't describe vehicles. If there is a package, describe the package. Do not give a preamble.

record:
  enabled: true
  retain:
    days: 31
    mode: all
  alerts:
    retain:
      days: 31
  detections:
    retain:
      days: 31
auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false
  # Optional: Cookie to store the JWT token for native auth (default: shown below)

model:
  path: plus://

snapshots:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  path: '5.0'

birdseye:
  enabled: false
  mode: continuous

objects:
  filters:
    dog:
      min_score: .65
      threshold: .8
    cat:
      min_score: .65
      threshold: .8
    package:
      min_score: .6
      threshold: .8
    person:
      min_score: .6
      threshold: .8

go2rtc:
  streams:
    doorbell:
      #- ffmpeg:http://192.168.10.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=&password=#video=copy#audio=copy#audio=opus
      - ffmpeg:http://192.168.10.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password=#video=copy#audio=copy#audio=opus
    rear:
      #- ffmpeg:rtsp://:@192.168.10.10:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
      - ffmpeg:rtsp://:@192.168.10.10:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
  webrtc:
    candidates:
      - 192.168.10.5:8555
      - stun:8555
  ffmpeg:
    volume: -af "volume=30dB"

cameras:
  doorbell:
    ffmpeg:
      inputs:
        #- path: 
            #http://192.168.10.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password=#video=copy#audio=copy#audio=opus
          #input_args: preset-rtsp-restream
          #roles:
            #- record
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 2560
      height: 1920
      fps: 5
      enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - package
        - face
    motion:
      mask:
        - 1,0,1,0.177,1,0.43,0.886,0.379,0.781,0.37,0.661,0.369,0.52,0.371,0.432,0.37,0.218,0.372,0,0.386,0,0
        - 0,1,0.336,1,0.337,0.956,0,0.959
        - 0.718,0.781,0.842,0.786,0.846,0.583,0.739,0.617
        - 1,0.911,0.877,0.88,0.956,0.53,1,0.511
  rear:
    ffmpeg:
      inputs:
        #- path: rtsp://:@192.168.10.10:554/h264Preview_01_main
          #roles:
            #- record
        - path: rtsp://127.0.0.1:8554/rear?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 2560
      height: 1440
      fps: 5
      enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - package
        - face
      filters:
        cat:
          mask:
            - 0,0,0,1,0.352,1,0.426,0.466,0.283,0.379,0.521,0
        dog:
          mask:
            - 0,0,0,1,0.352,1,0.426,0.466,0.283,0.379,0.521,0
        package:
          mask:
            - 0,0,0,1,0.352,1,0.426,0.466,0.283,0.379,0.521,0
        person:
          mask:
            - 0,0,0,1,0.352,1,0.426,0.466,0.283,0.379,0.521,0
    motion:
      mask: 0,0,0,1,0.352,1,0.352,0.914,0.301,0.916,0.284,0.383,0.521,0
version: 0.15-1
camera_groups: {}
```

### Relevant Frigate log output

```shell
2025-01-27 10:24:52.820348103  [INFO] Preparing Frigate...
2025-01-27 10:24:52.914578134  [INFO] Starting Frigate...
2025-01-27 10:24:54.726246695  [2025-01-27 10:24:54] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-01-27 10:24:54.747326961  [2025-01-27 10:24:54] frigate.util.config            INFO    : frigate config does not need migration...
2025-01-27 10:24:54.788628539  [2025-01-27 10:24:54] frigate.app                    INFO    : Starting Frigate (0.15.0-6d8234f)
2025-01-27 10:24:54.795600447  [2025-01-27 10:24:54] peewee_migrate.logs            INFO    : Starting migrations
2025-01-27 10:24:54.795812339  [2025-01-27 10:24:54] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-01-27 10:24:54.810214995  [2025-01-27 10:24:54] frigate.app                    INFO    : Recording process started: 352
2025-01-27 10:24:54.810297535  [2025-01-27 10:24:54] frigate.app                    INFO    : Review process started: 361
2025-01-27 10:24:54.812655512  [2025-01-27 10:24:54] frigate.app                    INFO    : go2rtc process pid: 98
2025-01-27 10:24:54.828946221  [2025-01-27 10:24:54] detector.coral                 INFO    : Starting detection process: 368
2025-01-27 10:24:54.829002359  [2025-01-27 10:24:54] frigate.app                    INFO    : Embedding process started: 371
2025-01-27 10:24:54.829056555  [2025-01-27 10:24:54] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2025-01-27 10:24:54.829106217  [2025-01-27 10:24:54] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-01-27 10:24:54.841405821  [2025-01-27 10:24:54] frigate.app                    INFO    : Output process started: 403
2025-01-27 10:24:54.885621548  [2025-01-27 10:24:54] frigate.app                    INFO    : Camera processor started for doorbell: 417
2025-01-27 10:24:54.886975703  [2025-01-27 10:24:54] frigate.app                    INFO    : Camera processor started for rear: 418
2025-01-27 10:24:54.896249494  [2025-01-27 10:24:54] frigate.app                    INFO    : Capture process started for doorbell: 421
2025-01-27 10:24:54.921611157  [2025-01-27 10:24:54] frigate.app                    INFO    : Capture process started for rear: 438
2025-01-27 10:24:55.050162147  [2025-01-27 10:24:55] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-01-27 10:24:55.227135346  [2025-01-27 10:24:55] frigate.api.fastapi_app        INFO    : FastAPI started
```

### Relevant go2rtc log output

```shell
2025-01-27 10:24:52.818482027  [INFO] Preparing new go2rtc config...
2025-01-27 10:24:53.103657586  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-01-27 10:24:53.207059567  [INFO] Starting go2rtc...
2025-01-27 10:24:53.301375373  10:24:53.301 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-01-27 10:24:53.301393377  10:24:53.301 INF config path=/dev/shm/go2rtc.yaml
2025-01-27 10:24:53.301710158  10:24:53.301 INF [api] listen addr=:1984
2025-01-27 10:24:53.301752192  10:24:53.301 INF [rtsp] listen addr=:8554
2025-01-27 10:24:53.302054007  10:24:53.302 INF [webrtc] listen addr=:8555
2025-01-27 10:25:02.822278710  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"doorbell":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":3.0,"detection_enabled":true,"pid":417,"capture_pid":421,"ffmpeg_pid":431,"audio_rms":0.0,"audio_dBFS":0.0},"rear":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":418,"capture_pid":438,"ffmpeg_pid":447,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":5.52,"detection_start":0.0,"pid":368}},"detection_fps":3.0,"gpu_usages":{"intel-vaapi":{"gpu":"4.97%","mem":"-%","clients":{"431":"15.12%","447":"8.3%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"14.3","mem":"41.1"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"86":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"2.3","cpu_average":"2","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"104":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"112":{"cpu":"3.3","cpu_average":"2","mem":"2.1","cmdline":"python3 -u -m frigate"},"130":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"163":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"164":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"166":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"169":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"170":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"319":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"352":{"cpu":"2.1","cpu_average":"1","mem":"0.7","cmdline":"frigate.recording_manager"},"361":{"cpu":"0.3","cpu_average":"0","mem":"0.6","cmdline":"frigate.review_segment_manager"},"368":{"cpu":"0.3","cpu_average":"0","mem":"0.6","cmdline":"frigate.detector.coral"},"371":{"cpu":"0.1","cpu_average":"0","mem":"3.8","cmdline":"frigate.embeddings_manager"},"403":{"cpu":"1.7","cpu_average":"1","mem":"0.6","cmdline":"frigate.output       "},"417":{"cpu":"13.6","cpu_average":"16","mem":"0.8","cmdline":"frigate.process:doorbell"},"418":{"cpu":"1.5","cpu_average":"1","mem":"0.7","cmdline":"frigate.process:rear "},"421":{"cpu":"7.0","cpu_average":"6","mem":"0.7","cmdline":"frigate.capture:doorbell"},"431":{"cpu":"15.3","cpu_average":"15","mem":"0.4","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6d8234f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1920,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"438":{"cpu":"5.6","cpu_average":"5","mem":"0.6","cmdline":"frigate.capture:rear "},"440":{"cpu":"7.1","cpu_average":"7","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.10.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -c:v copy -c:a aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ed690cc5d9b2496649153abe9316dd19"},"447":{"cpu":"10.8","cpu_average":"10","mem":"0.4","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6d8234f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rear?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/rear@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"449":{"cpu":"4.3","cpu_average":"4","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.10.10:554/h264Preview_01_main -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/8dcee99cdf6924ec1c2abbe688bc38d3"},"473":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"480":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"2680":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"2777":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":899,"version":"0.15.0-6d8234f","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":22884371.9,"used":14542884.0,"free":8341487.9,"mount_type":"fuse.shfs"},"/media/frigate/clips":{"total":22884371.9,"used":14542884.0,"free":8341487.9,"mount_type":"fuse.shfs"},"/tmp/cache":{"total":953.7,"used":20.5,"free":933.1,"mount_type":"tmpfs"},"/dev/shm":{"total":500.0,"used":432.4,"free":67.6,"mount_type":"tmpfs"}},"temperatures":{"apex_0":44.8},"last_updated":1737974393},"processes":{"recording":{"pid":352},"review_segment":{"pid":361},"go2rtc":{"pid":98},"embeddings":{"pid":371}}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
Automatically generated by unraid.
```

### Object Detector

Coral
