### DISCUSSION TITLE
[Bug]: Public Endpoint Clips Shorter than Clip in Frigate Event Browser

### DISCUSSION THREAD

**Discussion by PablaV** [blakeblackshear/frigate#16162] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have recently switched over my notifications to include a clip of the tracked object once a clip is recorder. However, on occasion I have noticed that clip usually stop short when compared to the recording in the Frigate event browser. Attached is the clip from the endpoint  `https://HA_URL/api/frigate/notifications/<event-id>/clip.mp4` vs the clip in the event browser. Not sure if this is a bug or it's my misunderstanding of a "clip" and a recording in the event browser UI. 

Public Notification Endpoint Clip
https://github.com/user-attachments/assets/1ff1e92a-449e-4039-8bd9-0a5fdf213e61

Event Browser Clip
https://github.com/user-attachments/assets/58cf0e99-b999-46ec-9d15-eaa19357c04b

### Steps to reproduce

Steps in description 

### Version

Beta 15.0 RC1

### Frigate config file

```yaml
mqtt:
  host: 192.168.8.85
  port: 1883
  user: XXXX
  password: XXXX
cameras:
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 2560
      height: 1920
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
      filters:
        car:
          min_score: 0.8
        person:
          min_score: 0.8
        cat:
          min_score: 0.8
        dog:
          min_score: 0.8
        package:
          min_score: 0.8
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        pre_capture: 10
        post_capture: 30
        retain:
          days: 3
          mode: active_objects
      detections:
        retain:
          days: 7
          mode: active_objects
    motion:
      mask:
        - 0.999,0.959,0.999,0.996,0.653,0.994,0.654,0.959
        - 0.164,0.256,0.216,0.386,0.678,0.409,0.767,0.227,0.876,0.177,0.818,0.073,0.576,0.123,0.228,0.134
      threshold: 30
      contour_area: 50
      improve_contrast: true
    zones:
      driveway:
        coordinates: 
          0.176,0.33,0.172,0.566,0.287,0.549,0.494,0.549,0.589,0.579,0.717,0.578,0.719,0.348,0.928,0.252,0.999,0.216,1,1,0,1,0.002,0.208
        loitering_time: 0
        inertia: 3
      package_zone:
        coordinates: 0.109,0.866,0.943,0.674,0.998,0.675,0.997,0.995,0,1
        loitering_time: 0
        objects: package
    review:
      alerts:
        required_zones:
          - driveway
        labels:
          - person
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package
    #   detections: {}
    # mqtt:
    #   quality: 100
    #   required_zones:
    #     - driveway
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      mask: 0,0.282,0.042,0.321,0.349,0.234,0.349,0,0,0
  front_east:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_east?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_east_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      mask: 0.632,0.119,0.998,0.138,1,0,0.635,0.003
  front_entrance_east:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_entrance_east?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_entrance_east_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      mask:
        - 0.568,0,0.633,0.041,1,0.206,1,0
        - 0.232,0.227,0,0.426,0,0.001,0.23,0.001
    motion:
      mask: 0,0.913,0.003,0.951,0.21,0.951,0.212,0.913
  front_entrance_west:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_entrance_west?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_entrance_west_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    objects:
      mask:
        - 0,0.29,0,0,0.475,0.001
        - 0.735,0,1,0.301,0.997,0.004
    motion:
      mask: 0.747,0.924,0.8,0.962,0.957,0.962,0.959,0.924
  east_side_house:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/east_side_house?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/east_side_house_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.749,0.924,0.82,0.962,0.959,0.962,0.961,0.924
  west_side_back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/west_side_back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/west_side_back_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.749,0.923,0.82,0.961,0.959,0.961,0.961,0.923
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.749,0.924,0.82,0.962,0.959,0.962,0.961,0.924
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.749,0.924,0.82,0.962,0.959,0.962,0.961,0.924
  back_landing:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_landing?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_landing_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.749,0.923,0.82,0.961,0.959,0.961,0.961,0.923
  bar_landing:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bar_landing?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bar_landing_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.749,0.923,0.82,0.961,0.959,0.961,0.961,0.923
  deck_stairs:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_stairs?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_stairs_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704
    motion:
      mask: 0.748,0.92,0.81,0.958,0.958,0.958,0.96,0.92
  deck_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_door_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 840
      height: 704

    motion:
      mask: 0.749,0.925,0.82,0.963,0.959,0.963,0.961,0.925
go2rtc:
  streams:
    front_doorbell:
      - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXX&password=XXXX#video=copy#audio=copy#audio=opus#async
      - rtsp://XXXX:XXXX@192.168.8.186:554/h264Preview_01_sub
    front_doorbell_sub:
      - ffmpeg:http://192.168.8.186/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXX&password=XXXX
    front_door: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=1&subtype=0
    front_door_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=1&subtype=1
    front_east: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=2&subtype=0
    front_east_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=2&subtype=1
    front_entrance_east: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=3&subtype=0
    front_entrance_east_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=3&subtype=1
    front_entrance_west: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=4&subtype=0
    front_entrance_west_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=4&subtype=1
    west_side_back: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=5&subtype=0
    west_side_back_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=5&subtype=1
    east_side_house: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=6&subtype=0
    east_side_house_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=6&subtype=1
    back_garden: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=12&subtype=0
    back_garden_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=12&subtype=1
    backyard: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=8&subtype=0
    backyard_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=8&subtype=1
    back_landing: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=7&subtype=0
    back_landing_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=7&subtype=1
    bar_landing: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=9&subtype=0
    bar_landing_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=9&subtype=1
    deck_stairs: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=10&subtype=0
    deck_stairs_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=10&subtype=1
    deck_door: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=11&subtype=0
    deck_door_sub: 
      rtsp://XXXX:XXXXXXXX@192.168.8.20:554/cam/realmonitor?channel=11&subtype=1

  webrtc:
    candidates:
      - 192.168.8.85:8555
      - stun:8555
snapshots:
  enabled: true
  # required_zones:
  #   - driveway
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: true
  height: 270
  quality: 100

objects:
  track:
    - person
    - dog
    - cat
    - car
  filters:
    car:
      min_score: 0.8
    person:
      min_score: 0.8
    cat:
      min_score: 0.8
    dog:
      min_score: 0.8
review:
  alerts:
    labels:
      - person
      - dog
      - cat
      - car
record:
  enabled: true
  retain:
    days: 2
    mode: all
  alerts:
    pre_capture: 30
    post_capture: 30
    retain:
      days: 7
      mode: active_objects
  detections: {}
motion:
  mask: 0.749,0.936,0.82,0.974,0.959,0.974,0.961,0.936

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac #this allows audio in recordings 
  hwaccel_args: preset-vaapi

model:
  path: plus://xxxx
timestamp_style:
  position: bl
  format: '%-I:%M:%S %p %Y-%m-%d'
  color:
    red: 0
    green: 0
    blue: 0

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: true
  provider: gemini
  api_key: xxxx
  model: gemini-1.5-flash

birdseye:
  enabled: true
  mode: objects
  width: 1920
  height: 1080
  restream: true

version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink POE Doorbell 

### Screenshots of the Frigate UI's System metrics pages

<img width="1561" alt="Screenshot 2025-01-26 at 9 37 30 PM" src="https://github.com/user-attachments/assets/25cd3b1f-d397-469d-a646-850130078723" />
<img width="1561" alt="Screenshot 2025-01-26 at 9 37 41 PM" src="https://github.com/user-attachments/assets/1d8585ec-838f-4e84-9f06-0861251feaa7" />
