### DISCUSSION TITLE
A few ideas

### DISCUSSION THREAD

**Discussion by Archy54** [blakeblackshear/frigate#16179] [Ideas]
I'm not sure how feasible this is, I truly wish I knew enough about coding to add features. 
Just some random thoughts - Hailo8, would love to see it in frigate+ one day? Is it on the horizon? When I get 4 more cameras hopefully in a month or two I'll start the snapshots and get a frigate+ depending on my health. 

Masking - Trees make a lot of movement, wind, etc, a colour range mask would be awesome. 
Range - I guess this is gonna be super super hard due to focal length differences, camera distortion, for detecting say a cat at I dunno what a cat's bounding box is, 20,000pixels? If it moves closer that will be 40,000 right? (guestimate number). The edge of lens bends objects, camera distortion correction would be cool at like 2.8 but I dunno if that has much effect on tracking and I don't want the devs to be overloaded. A tape measure and a plane of reference To mark out in metric (Cmon USA upgrade to metric), mark out each 1 meter interval from camera to say 20-30m and the bounding box for a cat or person varies on where they are standing. I'm guessing this is extremely hard. And a reference angle of tilt to azimuth? as objects might be wider at the top vs bottom. This is seriously overthinking it so if it's not feasible drop to the bottom of list of ideas or don't worry. I'm not sure if dahua has for the varifocal a way to determine it's current FOV. Each cam I guess would need that from what I've read on chatgpt on feasability for calculating how to size the box. 

Bugs love IR - I dunno how this gets handled except floodlights off camera in IR, they make motion width. No idea how to fix this apart from disable onboard IR, floodlight IR (how far away? ). I've been trying to find a mouse in shed that's somewhat cluttered, I see they eat poison but never catch them on cam. Might be too hard. 

Thank you sooooo much to the team though, person detection seems very accurate. I've still got lots to learn. I did have a question if it's ok to ask here on - I can add a second usb coral, my gpu is passed through to a windows vm for testing blueiris and stable diffusion, what options and what's best to do face tracking and pass through to home assistant Joe Bloe detected? 

Is Dahua/empire tech 5542 s3 meta data still a mystery to all third parties? It's 2k to get the nvr and will I gain much from it? Easier phone app maybe or face detect, acupick, etc? Is this stuff that probably won't be reverse engineered? 

I was thinking frigate + blue Iris + CPAI or deepstack? or something, I am so disappointed I can't share gpus to other vm's on consumer hardware. 

Finally is frigate going to be an addon to nvrs or later add nvr functions like android app, better search (either way is fine, it's your app and I am privileged to use it). When my health gets better I'd like to learn some coding, eventually add to apps like this, what languages does frigate use and timescale to learn?

**Comment by NickM-27** [comment]
> Hailo8, would love to see it in frigate+ one day? Is it on the horizon?

See https://github.com/blakeblackshear/frigate/discussions/16099#discussioncomment-11937200

> >  Neither YOLO-NAS or mobiledet are supported by Hailo. I haven't been able to convert them using the tools they provide. I am hopeful that yolov9 will work out in the future.

> I did have a question if it's ok to ask here on - I can add a second usb coral

Yes, Frigate supports however many corals you want to give it.

> what options and what's best to do face tracking and pass through to home assistant Joe Bloe detected?

It is a complex subject, doubletake is still the easiest way to integrate with Frigate then you can pick CPAI or CompreFace. In 0.16 Frigate will support native face recognition.

> Finally is frigate going to be an addon to nvrs or later add nvr functions like android app, better search

Not quite sure what you mean, Frigate already has NVR features. You can already install Frigate as an app https://docs.frigate.video/configuration/pwa and Frigate 0.15 has implemented semantic search.

**Reply by Archy54** [reply]
Ah sweet, thanks so much. I gotta figure out how to do https access. Would I do that in the frigate app or have a certificate server, I haven't gotten that far in my homelab journey yet. Would I be best to tailscale in from my mobile outside of my network? I gotta get opnsense setup, vlans, all the fun stuff. Would doubletake/cpai/etc need it's own coral or just wait till 0.16? I think there's acme client on opnsense, would I be best using that, tailscale in? Although I had trouble tailscaling to a friends home assistant webrtc cards, but vlc worked.

**Reply by NickM-27** [reply]
> Would I do that in the frigate app or have a certificate server, I haven't gotten that far in my homelab journey yet. Would I be best to tailscale in from my mobile outside of my network?

Tailscale is one of many options. I use cloud flare tunnels personally

> Would doubletake/cpai/etc need it's own coral or just wait till 0.16? 

Most of that doesn't support coral

**Comment by Archy54** [comment]
Ah thanks for the reply. Can I run deepstack on a windows enterprise VM as that's got my gpu passed through. 

Is there a lack of development in TPU's? Seems to be expectation to run everything on one machine for each unless you have an expensive nvidia that can passthrough to multiple vms. My issue is I have a 4ru I am trying to run Frigate, Blue Iris + stable diffusion + windows stuff that has gpu), frigate has the coral + igpu. Sadly finances won't allow a second server, most I could do is a second 4060ti, I thought the hailo8 would have taken off. Also running a truenas on that machine. Australia is expensive. 

also quick question I believe my docker compose has an error, the /config stores the database volume path so updating to a new release doesn't delete db? I think I had that missing and it was inside the docker when I updated to rc recently, oops. My heads not thinking clearly as dog is sick but 
-- on LXC host? Currently /opt/frigate, just make /config and move config.yml there, update volume in docker compose? )   /config: Used to store the Frigate config file and sqlite database. You will also see a few files alongside the database file while Frigate is running.

/media would be my /mnt/frigatehdd mounting hdd right? 
/media/frigate/clips: Used for snapshot storage. In the future, it will likely be renamed from clips to snapshots. The file structure here cannot be modified and isn't intended to be browsed or managed manually.
/media/frigate/recordings: Internal system storage for recording segments. The file structure here cannot be modified and isn't intended to be browsed or managed manually.
/media/frigate/exports: Storage for clips and timelapses that have been exported via the WebUI or API.

This is in ram i presume with the docker-compose file?
/tmp/cache: Cache location for recording segments. Initial recordings are written here before being checked and converted to mp4 and moved to the recordings folder. Segments generated via the clip.mp4 endpoints are also concatenated and processed here. It is recommended to use a [tmpfs](https://docs.docker.com/storage/tmpfs/) mount for this.

Ignore this?
/dev/shm: Internal cache for raw decoded frames in shared memory. It is not recommended to modify this directory or map it with docker. The minimum size is impacted by the shm-size calculations below.


```
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1
    container_name: frigate
    restart: unless-stopped
    privileged: true  # Required for hardware access
    network_mode: host  # Recommended for hardware and RTSP access
    shm_size: "400mb"  # Shared memory for FFmpeg, adjust as needed
    volumes:
      - /opt/frigate/config.yml:/config/config.yml  # Configuration file
      - /mnt/frigate_cctv_hdd/recordings:/media/frigate/recordings  # Recordings directory
      - /mnt/frigate_cctv_hdd/clips:/media/frigate/clips  # Clips directory
      - /mnt/frigate_cctv_hdd/exports:/media/frigate/exports  # Exports directory
      - type: tmpfs  # Optional: Use RAM for cache to reduce SSD wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000  # Adjust size as needed
      - /etc/localtime:/etc/localtime:ro  # Sync container time with host
      - /dev/shm:/dev/shm  # Shared memory for FFmpeg
    devices:
      - /dev/dri:/dev/dri  # Intel iGPU for hardware acceleration
      - /dev/bus/usb:/dev/bus/usb  # USB Coral TPU
    ports:
      - "5000:5000"  # Frigate Web UI
      - "1935:1935"  # RTMP stream
      - "8554:8554"  # RTSP restream
      - "8555:8555"  # WebRTC
```
      - /path/to/your/config:/config (change config to this and move config.yml to it? 
      so this - /opt/frigate/config/:/config/config/)
      - /mnt/frigate_cctv_hdd/:/media/frigate (Will recordings, snapshots, clips auto go into this from now on or need to map each one? and double check the hdd existing files are in the right spot after changing? 
Remove the dev/sha? 
Keep - type: tmpfs etc for ram based cache?
Can I set a username/password in the docker-compose for my home assistant? 

Thanks for an awesome product.
