### DISCUSSION TITLE
[Support]: Frigate plugin in Home Assistant doesn't start after upgrade to 2025.1.4

### DISCUSSION THREAD

**Discussion by sven-daems** [blakeblackshear/frigate#16173] [General Support]
### Describe the problem you are having

After upgrading my home assistant tot 2025.1.4, it get following error after rebooting

```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 18:32:42 (1 occurrences)
Last logged: 18:32:42

Setup failed for custom integration 'frigate': Requirements for frigate not found: ['hass-web-proxy-lib==0.0.7'].
```

I've Frigate integration v 5.7.0 installed. My Home Assistant Core is running in version 2025.1.4 & my Home Assistant OS is v 14.1.

Before the upgrade, I didn't had a problem

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Brave v 1.74.50

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.33.254
  user: xxxx
  password: yyyy

go2rtc:
  streams:
    Camera_Garage:
      - rtsp://xxxx:yyyy@192.168.33.123:88/videoMain
    Camera_Garage_sub:
      - rtsp://xxxx:yyyy@192.168.33.123:88/videoSub
    Camera_fietsenberging:
      - rtsp://xxxx:yyyy@192.168.33.155:88/videoMain
    Camera_fietsenberging_sub:
      - rtsp://xxxx:yyyy@192.168.33.155:88/videoSub
    Camera_Deurbel:
      - ffmpeg:https://192.168.33.135/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=yyyy#video=copy#audio=copy#audio=opus
      - rtsp://frigate:Azerty123@192.168.33.135/Preview_01_sub
    Camera_Deurbel_sub:
      - ffmpeg:https://192.168.33.135/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=yyyy
    Camera_vogelhuisje:
      - rtsp://xxxx:yyyy@192.168.33.61/user=frigate_password=123456_channel=1_stream=0.sdp

cameras:
  Camera_Garage: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Garage_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Camera_Garage # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask: 0.001,0.056,0.003,0.006,0.415,0.007,0.419,0.058
    zones:
      DetectieZoneGarage:
        coordinates: 0.408,0.257,0.624,0.272,0.77,0.481,0.756,0.991,0.356,0.972
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: DetectieZoneGarage
      detections:
        required_zones: DetectieZoneGarage
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
  Camera_fietsenberging:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_fietsenberging_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Camera_fietsenberging # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask: 0.002,0.066,0.373,0.071,0.374,0.012,0.003,0.005
    zones:
      DetectieZoneFietsenberging:
        coordinates: 0.006,0.01,0.994,0.012,0.991,0.555,0.99,0.987,0,0.987
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: DetectieZoneFietsenberging
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
  Camera_Deurbel:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Deurbel_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Camera_Deurbel # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask: 0.347,0.01,0.347,0.054,0.645,0.063,0.646,0.008
    zones:
      DetectieZoneDeurbel:
        coordinates: 0.004,0,0.276,0,0.511,0.22,0.995,0.375,0.996,0.564,0.986,0.993,0,1,0,0.635
        loitering_time: 0
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: DetectieZoneDeurbel
      detections:
        required_zones: DetectieZoneDeurbel
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion

    objects:
      filters:
        person: {}
  Camera_vogelhuisje:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_vogelhuisje # <----- The stream you want to use for detection & recording
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask: 0.743,0.098,0.999,0.107,1,0.048,0.745,0.048
    zones:
      DetectieZoneVogelhuisje:
        coordinates: 0,0,0.994,0.012,0.991,0.555,0.99,0.987,0,0.987
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: DetectieZoneVogelhuisje
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

-
