### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by SauronsMaster** [blakeblackshear/frigate#16171] [Config Support]
### Describe the problem you are having

I'm running HAOS and Frigate on a mini pc with an AMD CPU, the HEVC can only support 4096x4096. 

I have 2 reolink duo cameras with super wide feeds 7000x2000, I'm setup to use the sub streams which are much lower res for detection, and the main stream for recording, it seems to work fine (not sure why) but the image is rotated 90o clockwise... 

I've tried a few different things I've found in other places but can't seem to get them working to get the video to rotate when I view recordings to no avail... When I first go to load the video, it looks like its going to load landscape, then changes to portrait (may be that its loading the sub stream thumbnail first, then loads the main video feed) 

Before I start setting up a raspberry pi to split the video into 2 left/right feeds, is there any other way to rotate the recordings in frigate?

### Version

0.15-1

### Frigate config file

```yaml
Front_Camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@192.168.0.110:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:REDACTED@192.168.0.110:554//h264Preview_01_main # <----- The stream you want to use for detection
          roles:
            - record

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1536
      height: 432

    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects # Retain recordings with objects you are tracking

    onvif:
      host: 192.168.0.110
      port: 8000
      user: admin
      password: REDACTED

    zones:
      Underpass:
        coordinates: 0.25,0.628,0.514,0.7,0.516,0.997,0.126,0.993
        loitering_time: 0
        inertia: 3
      Front_Garden:
        coordinates: 0.172,0.628,0.221,0.679,0.123,0.976,0.041,0.604,0.071,0.546
        loitering_time: 0
    review:
      alerts:
        required_zones: Front_Garden
      detections:
        required_zones:
          - Front_Garden
          - Underpass
    motion:
      mask: 0.776,0.021,0.781,0.101,0.992,0.105,0.99,0.014
```

### Relevant Frigate log output

```shell
No Error
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral
