### DISCUSSION TITLE
Can't find webui_url in webui

### DISCUSSION THREAD

**Discussion by HolgerHees** [blakeblackshear/frigate#16182] [Ask A Question] [answered]
Hello,

I added to my camera a webui_url but I can't find them inside the webui anywhere.

My config looks like

```
cameras:
  toolshed:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/toolshed_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/toolshed_sub
          roles:
            - detect
    live:
      stream_name: toolshed_main
    detect:
      enabled: true
    webui_url: https://192.168.0.103
```

I'm running frigate 0.15-1 as a container and I'm using the frigate webui. Means no HomeAssistent WebUI, because I'm a openHAB user.
