### DISCUSSION TITLE
[Bug]: frigate login triggers fail2ban

### DISCUSSION THREAD

**Discussion by jpriebe** [blakeblackshear/frigate#16197] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I am using frigate with [swag](https://github.com/linuxserver/docker-swag) as my reverse proxy.  Every time I logged in, traffic immediately stopped moving to frigate and all my other self-hosted applications.  It took a bit of digging, but the issue turned out to be that fail2ban was blocking my IP address.

Out of the box, swag is configured to look for 401 errors in the nginx logs (swag uses nginx under the hood).  If it finds 5 401 errors from the same IP address in a 10-minute period, it will ban the IP for 10 minutes.

If you look at the stripped-down access logs below, you'll see that opening the frigate "/" URL generates 5 401s before the user can even post the login form (there are four calls to API URLs and a call to the websocket URL).  I suppose that I could open "/login" directly to avoid these, but it seems like I should be able to open "/" without triggering fail2ban.  

I have configured fail2ban to allow for 6 failures in 10 minutes.  But I don't like reducing my security posture, and I spent a LOT of time trying to diagnose this problem.  I didn't realize fail2ban was baked into swag (I'm sure a lot of users would not know that either). 

Is there any way to avoid this large number of failures?  Maybe a 302 redirect from "/" to "/login" for unauthenticated users so that the home page never loads?

```
[28/Jan/2025:11:10:00 -0500] "GET / HTTP/2.0" 200 2639 "-" 
[28/Jan/2025:11:10:00 -0500] "GET /api/config HTTP/2.0" 401 581 "https://frigate.REDACTED.duckdns.org:8443/" 
[28/Jan/2025:11:10:00 -0500] "GET /api/profile HTTP/2.0" 401 581 "https://frigate.REDACTED.duckdns.org:8443/" 
[28/Jan/2025:11:10:00 -0500] "GET /api/stats HTTP/2.0" 401 581 "https://frigate.REDACTED.duckdns.org:8443/" 
[28/Jan/2025:11:10:00 -0500] "GET /fonts/Inter-Regular.woff2 HTTP/2.0" 200 108488 "https://frigate.REDACTED.duckdns.org:8443/assets/index-BsqM9WWT.css" 
[28/Jan/2025:11:10:00 -0500] "GET /api/review?limit=10&severity=alert HTTP/2.0" 401 581 "https://frigate.REDACTED.duckdns.org:8443/" 
[28/Jan/2025:11:10:00 -0500] "GET /login HTTP/2.0" 200 2641 "https://frigate.REDACTED.duckdns.org:8443/" 
[28/Jan/2025:11:10:00 -0500] "GET /ws HTTP/1.1" 401 581 "-" 
[28/Jan/2025:11:10:00 -0500] "GET /fonts/Inter-Medium.woff2 HTTP/2.0" 200 111380 "https://frigate.REDACTED.duckdns.org:8443/assets/index-BsqM9WWT.css" 
[28/Jan/2025:11:10:01 -0500] "GET /fonts/Inter-Regular.woff2 HTTP/2.0" 200 108488 "https://frigate.REDACTED.duckdns.org:8443/assets/index-BsqM9WWT.css" 
[28/Jan/2025:11:10:01 -0500] "GET /images/android-chrome-192x192.png HTTP/2.0" 200 9201 "https://frigate.REDACTED.duckdns.org:8443/login" 
[28/Jan/2025:11:10:09 -0500] "POST /api/login HTTP/2.0" 200 3 "https://frigate.REDACTED.duckdns.org:8443/login" 
```

### Steps to reproduce

1. Install frigate using docker compose
2. Install swag using docker compose
3. Configure swag to reverse proxy frigate
4. Access frigate from outside your local network
5. Five 401 errors will be logged to the nginx access log
6. The fail2ban log will show that it has banned your IP

### Version

0.14.1

### In which browser(s) are you experiencing the issue with?

Google Chrome 131.0.6778.265 MacOS

### Frigate config file

```yaml
mqtt:
  enabled: false

# disable tls so that swag can connect on port 8971
tls:
  enabled: false

go2rtc:
  streams:
    driveway_rtsp:
      - rtsp://admin:REDACTED@10.1.1.129:554/cam/realmonitor?channel=1&subtype=0  # <- stream which supports video & aac audio.
      - ffmpeg:driveway_rtsp#audio=opus                                           # <- copy of the stream which transcodes audio to opus (required for WebRTC)
    driveway_rtsp_sub:
      - rtsp://admin:REDACTED@10.1.1.129:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio.
      - ffmpeg:driveway_rtsp_sub#audio=opus                                      # <- copy of the stream which transcodes audio to opus (required for WebRTC)
    backyard_rtsp:
      - rtsp://admin:REDACTED@10.1.1.128:554/cam/realmonitor?channel=1&subtype=0  # <- stream which supports video & aac audio.
      - ffmpeg:backyard_rtsp#audio=opus                                           # <- copy of the stream which transcodes audio to opus (required for WebRTC)
    backyard_rtsp_sub:
      - rtsp://admin:REDACTED@10.1.1.128:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio.
      - ffmpeg:backyard_rtsp_sub#audio=opus                                      # <- copy of the stream which transcodes audio to opus (required for WebRTC)

cameras:
  driveway:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_rtsp                 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_rtsp_sub             # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720

    zones:
      drive-and-walk:
        coordinates:
          0.266,0.333,0.195,0.406,0,0.404,0,0.458,0.16,0.469,0.156,0.517,0.131,0.563,0.068,0.688,0.016,0.787,0.002,0.838,0,1,1,1,0.826,0.616,0.505,0.338
        loitering_time: 0
        inertia: 3
        objects:
          - animal
          - person
      driveway-entry:
        coordinates: 0.284,0.277,0.426,0.248,0.454,0.275,0.508,0.342,0.266,0.331
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones:
          - drive-and-walk
          - driveway-entry
    motion:
      mask:
        - 0.168,0.202,0.143,0.174,0.122,0.204,0.109,0.26,0,0.28,0,0,0.273,0.003,0.205,0.172
        - 0.633,0,0.593,0.214,0.566,0.279,0.59,0.338,0.631,0.423,0.676,0.474,0.771,0.514,0.849,0.479,0.91,0.535,1,0.605,1,0
      threshold: 45
      contour_area: 40
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask: 0.658,0.324,0.703,0.39,0.8,0.415,0.816,0.347,0.761,0.287,0.695,0.287
  backyard:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_rtsp                 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_rtsp_sub             # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      yard:
        coordinates:
          -0.001,0.424,0.13,0.395,0.288,0.365,0.447,0.357,0.575,0.351,0.64,0.359,0.707,0.384,0.773,0.411,0.83,0.453,0.893,0.48,0.955,0.522,1,0.568,1,1,0,1
        loitering_time: 0
        inertia: 3
    motion:
      mask:
        0.001,0.411,0.316,0.353,0.447,0.344,0.589,0.344,0.691,0.367,0.801,0.415,0.843,0.447,0.897,0.466,0.998,0.549,1,0,0,0
      threshold: 45
      contour_area: 40
      improve_contrast: 'true'
    review:
      alerts:
        required_zones: yard
record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    post_capture: 60
    retain:
      default: 90
      mode: all

detectors:
  coral:
    type: edgetpu
    device: pci
snapshots:
  enabled: true

model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - animal

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    restart: unless-stopped
    privileged: true # this may not be necessary for all setups
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /appdata/frigate/config:/config
      - /data/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984" # go2rtc web interface
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      PLUS_API_KEY: "REDACTED"
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

Sorry for all the "n/a" entries, but this is purely a web UI / authentication issue.  Cameras and metrics are all healthy -- once I'm logged in, everything works.
