### DISCUSSION TITLE
Frigate+ Symbol in left Menu

### DISCUSSION THREAD

**Discussion by ThorstenUm** [blakeblackshear/frigate#16198] [Ask A Question] [answered]
Hello,

I use version 15 beta 5.
I created a Plus account and generated an API key.
Then I configured the docker-compose.yml as follows:

```
    environment:
      LIBVA_DRIVER_NAME: i965
      FRIGATE_MQTT_USER: "xxx"
      FRIGATE_MQTT_PASSWORD: "xxx"
      FRIGATE_RTSP_USER: "xxx"
      FRIGATE_RTSP_PASSWORD: "xxx"
      PLUS_API_KEY: "xxx"
```

Then I set global in the config.yml as follows:

```
snapshots:
  enabled: true
  required_zones: []
  retain:
    default: 20
    objects:
      person: 15
  quality: 70
```

Per camera comparatively like:

```
    snapshots:
      bounding_box: true
      enabled: true
      timestamp: true
      retain:
        default: 20
```

Now I restart the frigate.
I can't find a Frigate+ button anywhere in the menu bar on the left
I actually followed the instructions exactly
https://docs.frigate.video/integrations/plus/#generate-an-api-key

Can someone help me?
