### DISCUSSION TITLE
Cars in garage being recorded.

### DISCUSSION THREAD

**Discussion by Vendo233** [blakeblackshear/frigate#16193] [Ask A Question]
For some reason I have started recording cars in my garage. How can I avoid ot? 

![Screenshot_20250128-075131](https://github.com/user-attachments/assets/8fbef370-cdad-42bb-845d-cd9878484d93)

**Comment by NickM-27** [comment]
we need to see your config

**Comment by Vendo233** [comment]
```
detectors:
  coral_pci:
    type: edgetpu
    device: pci

mqtt:
  host: 192.168.1.128
  port: 1883
  topic_prefix: frigate
  user:
  password: 

ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  global_args: -hide_banner -loglevel warning
  input_args: preset-rtsp-generic
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
cameras:
  Front_Door_Wyze2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.1.107/ch1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://@192.168.1.107/ch0
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
      annotation_offset: -1600
    record:
      enabled: true
      retain:
        days: 5
        mode: active_objects
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 2
    objects:
      track:
        - person
        - cat
        - dog

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      quality: 100
      height: 500
      retain:
        default: 2
        objects:
          person: 5
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 100
      height: 500

    motion:
      mask: 
        0.081,0.155,0.092,0.269,0.125,0.238,0.121,0.151,0.191,0.144,0.18,0.247,0.223,0.263,0.264,0.156,0.422,0.133,0.47,0.108,0.487,0.017,0.061,0.029,0.017,0.11
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.1.154:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://@192.168.1.154:554/h265Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
      annotation_offset: -900
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 2
    objects:
      track:
        - person
        - car
        - dog
        - cat

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1500
      retain:
        default: 2
        objects:
          person: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1500

  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.1.16:8554/video2_unicast
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://@192.168.1.16:8554/video1_unicast
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 2
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1000
      retain:
        default: 2
        objects:
          person: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000

  Backyard_V3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.1.213:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://a@192.168.1.213:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 2
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 500
      retain:
        default: 2
        objects:
          person: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  front_door_bell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://a@192.168.1.95:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://@192.168.1.95:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 2
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 1000
      retain:
        default: 2
        objects:
          person: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000

  Alley_Wyze3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.1.231/ch1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://@192.168.1.231/ch0
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
      annotation_offset: -1500
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 2
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask:
            - 0.315,0.215,0.277,0.39,0.272,0.478,0.299,0.598,0.342,0.808,0.427,0.88,0.483,0.89,0.548,0.608,0.54,0.492,0.506,0.384,0.459,0.42,0.387,0.412,0.357,0.191,0.34,0.158
            - 0.141,0.12,0.104,0.255,0.085,0.392,0.09,0.555,0.127,0.814,0.161,0.569,0.181,0.442,0.172,0.198
      mask: 
        0.587,0.423,0.686,0.44,0.736,0.493,0.747,0.553,0.64,0.583,0.568,0.579,0.553,0.472,0.563,0.42
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      quality: 100
      height: 500
      retain:
        default: 2
        objects:
          person: 5
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

#  Alley_Wyze4:
#    enabled: true
#    ffmpeg:
#      inputs:
#        - path: rtsp:/@192.168.1.127/ch1
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#        - path: rtsp://@192.168.1.127/ch1
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#    detect:
#      width: 640
#      height: 360
#      fps: 5
#    record:
#      enabled: true
#      retain:
#        days: 0
#        mode: active_objects
#      events:
#        retain:
#          default: 2
#          mode: active_objects
#          objects:
#            person: 5
#    objects:
#      track:
#        - person
#        - car
#    snapshots:
#      enabled: true
#      timestamp: false
#      bounding_box: false
#      crop: false
#      quality: 100
#      height: 500
#      retain:
#        default: 2
#        objects:
#          person: 5
#    mqtt:
#      timestamp: false
#      bounding_box: false
#      crop: true
#      quality: 100
#      height: 500
    motion:
      mask: 
        0.32,0.199,0.27,0.447,0.351,0.81,0.436,0.879,0.487,0.849,0.545,0.598,0.511,0.4,0.39,0.422,0.354,0.2,0.338,0.164
version: 0.15-0
```

**Reply by NickM-27** [reply]
if you don't want alerts for cars then you can set

```
review:
  alerts:
    labels:
      - person
```

on the garage camera config
