### DISCUSSION TITLE
Afterwards how the detector worked

### DISCUSSION THREAD

**Discussion by ThorstenUm** [blakeblackshear/frigate#16192] [Ask A Question]
Hello,

I currently have version 0.15.0 Beta 5 installed.
Recently I noticed that a cat was not recognized in the recording.

My global settings are:
```
objects:
  track:
    - person
    - cat
    - dog
    - car
    - bicycle
    - bus
    - motorcycle

review:
  alerts:
    labels:
      - person
      - car
      - bicycle
      - motorcycle
  detections:
    labels:
      - cat
      - dog
      - bus
```

The cat was not shown under Alarms or Detections.
Is it actually possible to debug old recordings? This would be helpful to check afterwards how the detector worked.

I also noticed that in the review the Filters section only shows "All labels", "Car" and "Person". Are other filters only offered for selection if there are corresponding labels within the time period of the timeline or why are no other objects offered for filtering?
