### DISCUSSION TITLE
Object Detection (my confusion).

### DISCUSSION THREAD

**Discussion by tlundste** [blakeblackshear/frigate#1620] [Ask A Question]
I have Frigate installed as a docker instance running on a Nuc8.  Other docker instances include HA Core on Docker, Zoneminder (trying to get Frigate to replace that, eventually), and a few other instances, including mqtt.
I have one camera, my doorbell camera that supports a high-res (0) and low-res (1) rtsp stream.
No Coral device, so running cpu detection at this time.
It is working.. but (and I'll have more advanced questions later)... here is my config.
```
mqtt:
  host: <ip of nuc8>
detectors:
  cpu1:
    type: cpu
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@<ip of camera>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
            - record
        - path: rtsp://<user>:<pass>@<ip of camera>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
    width: 640
    height: 480
    fps: 5
    objects:
      track:
        - person
        - car
        - truck
        - motorcycle
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    clips:
      enabled: true
      retain:
        default: 2
    motion:
      mask:
        - 139,158,271,295,616,297,640,0,470,0,432,126,379,53,351,40,272,45
    zones:
      fntdr_drvwy:
        coordinates: 289,326,195,363,205,318,243,305
      fntdr_wlkwy:
        coordinates: 318,357,416,459,237,459,249,339
      fntdr_prch:
        coordinates: 70,480,71,377,374,480
      fntdr_yard:
        coordinates: 521,480,417,480,307,326,536,348
      fntdr_strt:
        coordinates: 551,335,503,296,205,292,195,317
```
As you can see, I am tracking person, car, truck, motorcycle, and dog.  I only ever get person and car.  The neighbor has a motorcycle, and several trucks and cars.  Plus, there are both random pickup trucks, and van/delivery/trash trucks running down the street.  And at least once, a dog spent a minute or so sniffing around on, and in front of my front porch, pretty close to the camera.
Trucks get detected as cars in clips.  They trigger the clips to record, and are also identified as cars when a person triggers the clip to record.
The dog didn't trigger to record a clip at all.
Nor do motorcycles.
What am I missing?  Why are trucks not identified as trucks?  Why did the dog not trigger a clip to be recorded; it should have triggered due to zones "prch", "yard", and "wlkwy" as it spent time in all of those zones.
Also... what I am missing to get 24/7 recordings to work?  There are no "recordings" I can find... only clips.

**Comment by jasonpstokes** [comment]
There's probably a few things going on here, so I'd recommend you simplify you config to get the detections you want working before you introduce zones and masks. By default, Frigate uses a custom `labelmap.txt`, replacing Truck with Car and so all trucks get labelled as cars. So to get the default labels back you need to use your own custom label map as per [this page](https://blakeblackshear.github.io/frigate/configuration/objects) in the docs.

**Reply by blakeblackshear** [reply]
In my experience, cars will still be seen as trucks and vice versa by the model itself. It just can't distinguish well. It's why the default merges the two. As an object is tracked, a new event will be created each time the object type changes.

**Reply by jasonpstokes** [reply]
I didn't need to distinguish, but instead changed them all to 'vehicle' as it looked funny seeing a picture of a delivery truck or van labelled as a car!
```
0  person
1  bicycle
2  vehicle
3  vehicle
4  airplane
5  bus
6  train
7  vehicle
8 ...
```

**Reply by tlundste** [reply]
I can't really get rid of that mask... those are trees, blowing in the wind, and trigger motion constantly, and the time stamp is constantly changing, so I really have to leave that mask there.
I can get rid of the zones, but what good would that do?  I see persons triggered on the wlkwy, porch.  I see persons, and cars triggered on the strt and drvwy.  That part seems to be working.  What I don't see is trucks identified (you've explained that) or dogs or motorcycles, either triggered or identified.  And what I don't see is 24/7 recording happening.

**Reply by jasonpstokes** [reply]
If that's your full config, then you don't have recording enabled/configured and so check the docs again on how to do that. In version 8 it is not enabled by default, so although you've added it as a role to your camera, there's more needed.

As for not detecting the dog, what inference speeds are you getting on your single CPU detector? The only thing I can suggest is that perhaps one is not enough to keep up with the number of cameras you have?? Sorry, others will probably have better things to suggest.

**Reply by tlundste** [reply]
I'll dig into the docs, again.  I'm probably too new to the nomenclature to understand a "role" vs something else (that actually activates the recording).  I'll see if I can figure it out.  If you have more hints or direct info, that would help me learn.
Inference speed?  Following a quick google search, this link https://blakeblackshear.github.io/frigate/hardware/ indicates I have 8-10 ms on a nuc7.  I assume it's comparable on a nuc8, if not better.  My FPS is set to 5, and viewing the live images, it's choppy, looks like 5fps.  When viewing the clips, it's smooth (looks normal FPS).  I only have one camera... two feeds... one (low res) for detecting and eventual full-time recording, and one (high res) for recording clips.
Is there something in the Frigate_ip:5000 interface that tells me the inference speed?
(edit)
Found the inference speed in the debug.. 122.36... does that seem slow for a nuc8? 
(edit2)
After restarting with four CPUs configured, each showed a speed of 10, but I noticed the column where the inference speed appears seemed to have changed... so I backed out to one CPU, and with one CPU, the column order is detector, inference speed, detection start, pid... but with four CPUs, it is detector, detection start, inference speed, pid.  Regardless, after restarting with one or four CPUs, inference speed is 10.  I expect that number goes up once it detects something.  I'll leave it with four to see what happens.  All other questions above are still outstanding... I'll keep looking for the right config to "record"... and waiting for a dog to wander by.

**Reply by jasonpstokes** [reply]
Just note that the way Frigate records clips (detected objects) is changing between v8 and v9, so this will only work for v8. (v8 records individual recordings for each detected object, plus a 24/7 recording if enabled, whereas v9 records 24/7 and when an object is detected, records timestamps.)

To enable 24/7 recording in v8, you need to enable it as per [this](https://blakeblackshear.github.io/frigate/configuration/index#record), either as a global setting for all cameras (at the top) or per camera:
```
record:
  enabled: True
  # Optional: Number of days to retain
  retain_days: 30  # adjust to your storage capacity, as Frigate will stop working when you run out of space.
```
Try two CPU detectors. A CPU is only capable of processing a few frames per second (perhaps 2-3 frames), so if there's lots of movement in a frame, resulting in several areas to analyse, it may only process a shadow and not the dog or person you wanted to know about in the time they were in frame. (That's my understanding anyway!)

```
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```
