### DISCUSSION TITLE
different alert/detection objects in one camera but different zones

### DISCUSSION THREAD

**Discussion by GnomiBerlin** [blakeblackshear/frigate#16210] [Ask A Question]
### Ask a Question!

**Question: how can I setup a config to reach this?**
-----------------------------------------------------------

**Goal:**
----------

Camera A:
ZoneAA:
ZoneBB:

objects:
          - bicycle
          - bird
          - cat
          - dog
          - person

Alerts:
ZoneAA: person, bicycle
ZoneBB: person, cat, dog

Detections:
ZoneAA: cat, bird, dog
ZoneBB: bicycle

 ---------------------------------------------
used, but not correct:
I do not know, how I can separate the review alerts/detections  for the zones and if there is another error?

```
CameraA:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@192.168.xx.yy/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
        - path: rtsp://user:pw@192.168.xx.yy/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy #preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - bird
        - cat
        - dog

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - ZoneBB
        - ZoneAA
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
    ui:
      order: 2

    zones:
      ZoneAA:
        coordinates: 
          0.001,0.484,0.42,0.25,0.787,0.145,0.864,0.191,0.873,0.252,0.875,0.386,0.956,0.523,0.828,0.998,0,1
        loitering_time: 0
        objects:
          - bicycle
          - bird
          - cat
          - dog
          - person
      ZoneBB:
        coordinates: 0.123,0.232,0.671,0.024,0.674,0.003,0.189,0.001,0.002,0.253,0,0.393
        loitering_time: 0
        objects:
          - person
          - bicycle
          - dog
          - cat
    review:
      alerts:
        required_zones:
          - ZoneBB
          - ZoneAA
        labels:
          - bicycle
          - person
      detections:
        required_zones:
          - ZoneBB
          - ZoneAA
        labels:
          - cat
          - dog
          - bird
version: 0.14
```

**Comment by NickM-27** [comment]
If you allow the detections to come from anywhere that would simplify it a lot. Otherwise you'll need 4 zones

**Reply by GnomiBerlin** [reply]
Thank you for the answer, but what do you mean with anywhere? Also outside defined zones? Then no.

I clearly want to reach:

Alerts:
ZoneAA: person, bicycle
ZoneBB: person, cat, dog

Detections:
ZoneAA: cat, bird, dog
ZoneBB: bicycle

I do not understand, how 4 Zones exact configuration desription should look like for this requirement, if alert and detection differs with overlapping in the two zones?

**Reply by NickM-27** [reply]
Use the UI, create one zone for person and bicycle and make it required for alerts. create another zone for cat bird and dog and make it required for alerts. Create a third zone with person cat and dog and make it required for detections. Make a final zone for bicycle and make it required for detections

**Reply by GnomiBerlin** [reply]
whow, understood and not so straight forward for different zones with the same measure points only for different alerts.
But will try this later, thanks.

**Reply by NickM-27** [reply]
like I said, it is much simpler if you just want to limit alerts to zones and let detections be everything else.

**Reply by GnomiBerlin** [reply]
**o.k., but if I would make only Alerts zone specific, how should the config looks like?**

are the alers only used implicit due to the zone configuration and the review-part ignores the alert objet types, which are not defined in the zone?
Is the below config as you propose or how should it look like?

Assumption:
-------------

Alerts:
ZoneAA: person, bicycle
ZoneBB: person, cat, dog

-----------------------------------------------

```
CameraA:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@192.168.xx.yy/cam/realmonitor?channel=1&subtype=00
          roles:
            - record
        - path: rtsp://user:pw@192.168.xx.yy/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy #preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - bird
        - cat
        - dog

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - ZoneBB
        - ZoneAA
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
    ui:
      order: 2

    zones:
      ZoneAA:
        coordinates: 
          0.001,0.484,0.42,0.25,0.787,0.145,0.864,0.191,0.873,0.252,0.875,0.386,0.956,0.523,0.828,0.998,0,1
        loitering_time: 0
        objects:
          - bicycle
          - person
      ZoneBB:
        coordinates: 0.123,0.232,0.671,0.024,0.674,0.003,0.189,0.001,0.002,0.253,0,0.393
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
    review:
      alerts:
        required_zones:
          - ZoneBB
          - ZoneAA
        labels:
          - bicycle
          - person
          - dog
          - cat
      
version: 0.14
```

**Reply by NickM-27** [reply]
the config there looks fine, although defining the `labels` for `alerts` is redundant since it is already defined for the zone.

**Reply by GnomiBerlin** [reply]
Ok, now I saw not any alert during the last day. I will check all again and also remove the redundancy....

**Reply by GnomiBerlin** [reply]
so, I now removed the redundancy labels in the alerts of the review part and reached:

```
....    
  zones:
      ZoneAA:
        coordinates: 
          0.001,0.484,0.42,0.25,0.787,0.145,0.864,0.191,0.873,0.252,0.875,0.386,0.956,0.523,0.828,0.998,0,1
        loitering_time: 0
        objects:
          - bicycle
          - person
      ZoneBB:
        coordinates: 0.123,0.232,0.671,0.024,0.674,0.003,0.189,0.001,0.002,0.253,0,0.393
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
    review:
      alerts:
        required_zones:
          - ZoneBB
          - ZoneAA
```
![image](https://github.com/user-attachments/assets/bff4969a-b741-4cbf-b29d-c7df221afe3e)


**The result is, that in the GUI Alerts of default car,person are shown and not my Alert types**. 
I add the labels like person and dog again, it is shown correctly, but the same alerts in both zones??

![image](https://github.com/user-attachments/assets/e9b328f9-ec07-4ba9-897d-5345277c691a)
