### DISCUSSION TITLE
HW accerelation with Intel® Core™ i3-N305 Processor

### DISCUSSION THREAD

**Discussion by JanickGers85** [blakeblackshear/frigate#16229] [Ask A Question] [answered]
Hello there,
I've recently switched to a new home-made NAS and I don't know if I'm currently taking benefits about GPU acceleration.
I have 3 different cameras, CPU load is constanlty under 15-18% but from `intel_gpu_top` I'm getting nothing

![image](https://github.com/user-attachments/assets/4b49c13d-fc0d-4b21-8e17-d9eaa9e01b59)

I'm using go2rtc, here a sample of the camera configuration

```yaml
go2rtc:
  streams:
    garden-sub:
      - rtsp://***:***@192.168.1.181:554/live/0/SUB
      - ffmpeg:garden-sub#audio=aac

cameras:
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden-sub
          hwaccel_args: preset-intel-qsv-h264
          roles:
            - detect
            - audio
        - path: rtsp://***:***@192.168.1.181:554/live/0/MAIN
          hwaccel_args: preset-intel-qsv-h265
          roles:
            - record
```

Substream is in H264 while the main stream is in H265.
Here the relevant part of my docker-compose

```yaml
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    cap_add:
      - CAP_PERFMON
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri:/dev/dri
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1
    shm_size: "1gb"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ./docker/frigate:/config
      - /home/nuc/frigate/:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - 5000:5000
      - 1935:1935
      - 8554:8554
    environment:
      - PLUS_API_KEY=***
```
This happened even in the previous version (0.14), where I used the VAAPI preset for all my cameras.
What's wrong in my configuration/docker-compose file?
