### DISCUSSION TITLE
video recording is automatically disabled

### DISCUSSION THREAD

**Discussion by volinvladim** [blakeblackshear/frigate#16228] [Camera Support]
### Describe the problem you are having

Video recording on two cameras is automatically disabled.
![2025-01-30_12-00-09](https://github.com/user-attachments/assets/eff71aba-bdb6-45e2-ab94-cc7ca1e73da3)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.22
  user: 
  password: 
  port: 8883
database:
  path: /config/frigate.db

review:
  alerts:
    labels:
      - car
      - person
      - cat
      - dog
      - bicycle
      - motorcycle
#detectors:
#  coral:
#    type: edgetpu
#    device: usb

#  ov:    # 
#    type: openvino
#    device: AUTO
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml

cameras:
  ogorod:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.55:554
          roles:
            - detect
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - cat
        - dog
 

      mask:
        - 0.672,0.548,0.672,0.821,0.967,0.721,0.996,0.51
        - 0.298,0.107,0.366,0.005,0.897,0.059,0.886,0.184

    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 2
        post_capture: 2
        objects:
          - person
          - cat
          - bicycle
          - dog
          - car
          - motorcycle
        retain:
          default: 3
          mode: active_objects





  ptzcam:
    ffmpeg:

      inputs:
        - path: rtsp://admin:pasword@192.168.1.166:554
          roles:
            - detect
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
        - car
        - dog
        - bicycle
        - motorcycle
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 2
        post_capture: 2
        objects:
          - person
          - cat
          - bicycle
          - dog
          - car
          - motorcycle
        retain:
          default: 3
          mode: active_objects
    onvif:
      host: 192.168.1.166
      port: 8000
      user: admin
      password: pasword

  naves:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.168:554
          roles:
            - detect
        - path: rtsp://admin:pasword@192.168.1.168:554/1
          roles:
            - record        
    snapshots: # <----- Enable snapshots
      enabled: true
      retain:
        default: 3
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - cat
        - dog
        - person
        - car
        - bicycle
        - motorcycle
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 2
        post_capture: 2
        objects:
          - cat
          - bicycle
          - dog
          - motorcycle
          - car
          - persone
        retain:
          default: 3
          mode: active_objects    

  esp32cam2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.4:554/mjpeg/1
          roles:
            - detect
    snapshots:
      enabled: true
      retain:
        default: 3
    detect:
      width: 800
      height: 600
      fps: 5
    objects:
      track:
        - cat
        - dog

  esp32cam1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.5:554/mjpeg/1
          roles:
            - detect
    snapshots:
      enabled: true
      retain:
        default: 3
    detect:
      width: 800
      height: 600
      fps: 5
    objects:
      track:
        - cat
        - dog








  streetcam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.160/stream0
#        - path: rtsp://127.0.0.1:8554/streetcam # <--- the name here must match the name of the camera in restream
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:pasword@192.168.1.160/stream1
          roles:
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3
        
    record:
      enabled: true
      retain:
        days: 0
      events:
        pre_capture: 2
        post_capture: 2
        objects:
          - person
          - cat
          - bicycle
          - dog
          - car
          - motorcycle
        retain:
          default: 3
          mode: active_objects

    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
        - car
        - dog
        - bicycle
        - motorcycle


    zones:
      street:
        coordinates: 
          0.049,0.946,0.125,0.395,0.475,0.395,0.574,0.52,0.732,0.647,0.978,0.642,0.957,0.91
        inertia: 3
        loitering_time: 0


audio:
  # Optional: Enable audio events (default: shown below)
  enabled: false
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8


#go2rtc:        # какие то тормоза при использовании
#  streams:     # долго включается или не включается просмотр камеры
#    streetcam: # иногда пропадает во фригате, хотя во фригат карте работает
#      - rtsp://admin:123456@192.168.1.160/stream0


version: 0.14
```

### Relevant Frigate log output

```shell
I can't find any log entries during the video recording shutdown.
```

### Relevant go2rtc log output

```shell
not enable
```

### FFprobe output from your camera

```shell
wtat is it
```

### Frigate stats

```json
what is it
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

iptronics IPT_IPL1520

### Screenshots of the Frigate UI's System metrics pages

![2025-01-30_12-00-09](https://github.com/user-attachments/assets/d43aa979-4463-4e86-952a-5a0bb1c9d47f)
