### DISCUSSION TITLE
[Camera Support]: Uso de CPU nas cameras

### DISCUSSION THREAD

**Discussion by gilsonlima10** [blakeblackshear/frigate#16236] [Camera Support]
### Describe the problem you are having

possuo o coral e placa de video GPU ati radeon, no system metrics o grafico das cameras aparece com uso da  CPU , é normal ou faltou alguma configuração para usar a GPU.
A carga de processamento 15% parece normal

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false
tls:
  enabled: false
detectors:
  coral1:
    type: edgetpu
    device: pci:0
objects:
  track:
    - person
    - car
    - cat
    - dog
#record:
#  enabled: True
#  retain:
#    days: 7
#    mode: motion
#  events:
#    retain:
#      default: 30
#      mode: motion
#snapshots:
#  enabled: True
#  retain:
#    default: 60
go2rtc:
  streams:
    cozinha:
      - ffmpeg:rtsp://admin:a4i5n1X4@172.27.10.201:8554/profile0
    atendimento:
      - ffmpeg:rtsp://172.27.10.202:8554/main
    churrasqueira:
      - ffmpeg:rtsp://172.27.10.206:8554/main
```

### Relevant Frigate log output

```shell
nenhuma informação relevante
tertet
```

### Relevant go2rtc log output

```shell
retertertret
ertertretret
errtertret
```

### FFprobe output from your camera

```shell
nenhuma informação relevante
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

generica

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/fc84d3a7-14cf-4f41-a269-c4782ad1e9db)
![image](https://github.com/user-attachments/assets/79f32a2d-fe2f-4240-b282-b03bcb02eb6a)
