### DISCUSSION TITLE
RTSP/RTMP proxy/server to offload the cameras

### DISCUSSION THREAD

**Discussion by tubalainen** [blakeblackshear/frigate#1623] [Show and tell]
This has been a blessing for me, my cameras started to act weird because I had too many active RTSP / RTMP clients connected to each camera (like more than 3-4 connections).

I just started using this tool to offload the cameras and it has been working wonders for frame drops and strange artefacts in general.

https://github.com/aler9/rtsp-simple-server

Here is my (simple) yaml config for the tool:

```
protocols: [udp, multicast, tcp]
rtspPort: 8554
rtpPort: 8000
rtcpPort: 8001
readTimeout: 5s
writeTimeout: 5s
pprof: false

paths:
  cam1_ch1:
    source: "rtsp://username:passwd@192.168.1.30:554/Streaming/Channels/1"
  cam1_ch2:
    source: "rtsp://username:passwd@192.168.1.30:554/Streaming/Channels/2"
  cam2_ch1:
    source: "rtsp://username:passwd@192.168.1.31:554/Streaming/Channels/1"
  cam2_ch2:
    source: "rtsp://username:passwd@192.168.1.31:554/Streaming/Channels/2"
  cam3_ch1:
    source: "rtsp://username:passwd@192.168.1.32:554/Streaming/Channels/1"
  cam3_ch2:
    source: "rtsp://username:passwd@192.168.1.32:554/Streaming/Channels/2"

```

I use this docker creation string:

`docker run -d --network=host --name="rtsp-server" -v /usr/share/dockers/rtsp-server/conf.yml:/rtsp-simple-server.yml aler9/rtsp-simple-server`

Then from like frigate just use this RTSP URL (for cam1_ch1 in this example)

```
cameras:
  cam1_framsidan:
    ffmpeg:
      inputs:
        - path: rtsp://ip_or_hostname:8554/cam1_ch1

```

Hope it can help others :)

**Comment by blakeblackshear** [comment]
I'm planning to bake this into frigate directly in place of the existing RTMP restreaming implemented in nginx.

**Reply by tubalainen** [reply]
Sounds like a great idea! Personally I have found the RTMP restreaming in nginx to be a bit clunky.

**Reply by Sarelseekat** [reply]
> I'm planning to bake this into frigate directly in place of the existing RTMP restreaming implemented in nginx.

That would be a thing of beauty Blake.

**Comment by Minglarn** [comment]
THIS IS GREAT!
That means that I can take the streams of this RTSP docker instead of frigate for my Raspisurv instance..
Thanks!

**Reply by tubalainen** [reply]
Tjabba Minglarn - Exactly.

For me it serves:
- Frigate
- 2x Rpisurv installs
- Home Assistant

Only Blue Iris and rtsp-server connects to the cams directly as of today.

**Comment by tlundste** [comment]
Shouldn't there need to be some sort of security on the secondary rtsp(:8554) stream?  Since you've already auth'd to the camera via simple-server tool, doesn't that make the camera streams completely visible to any IP on that network?

**Reply by tubalainen** [reply]
You can easily add that if you want, just a matter of some more conf to rtsp-server, please check the config for the options.

**Reply by tubalainen** [reply]
And in my case, no, ive got all my cams on an iot vlan.

**Comment by Minglarn** [comment]
Question...
Got 8 ReoLink cams... Having a hard time to make them work nicely.. A lot of smearing and other stuff... 
Are you running your RTSP server on the same machine as frigate?
Or should I try to set this up on my Synology nas...

**Reply by tubalainen** [reply]
> Question...
> Got 8 ReoLink cams... Having a hard time to make them work nicely.. A lot of smearing and other stuff...
> Are you running your RTSP server on the same machine as frigate?
> Or should I try to set this up on my Synology nas...

Nope - on another machine. Ive noticed some issues when RTMP converts to RTSP via rtsp-simple-sever. As well as just redirecting RTMP to RTMP..... Havnt managed to figure out or tweak any configs.

Ive only got one reolink running RTMP and I also tried it via rtsp-simple-server with so-so results :/

RTSP to RTSP works flawlessly.

**Reply by tubalainen** [reply]
@Minglarn Posted an issue on the RTMP stream issues... Please go in and make a comment and say "Me too" or something :)
https://github.com/aler9/rtsp-simple-server/issues/585

**Reply by bm55** [reply]
I just tried it with my Reolink camera but I don't get the clear image. Do I need to make any changes ?
<img width="616" alt="Screen Shot 2021-09-28 at 8 43 58 PM" src="https://user-images.githubusercontent.com/7528001/135200065-b0150728-eaf8-4a52-b288-84c6ef3ba6a2.png">

**Comment by f0b04707** [comment]
How do you add it back to HA ? HA Generic platform requires a still_image_url which rtsp-simple-server does not provide.

**Reply by tubalainen** [reply]
> How do you add it back to HA ? HA Generic platform requires a still_image_url which rtsp-simple-server does not provide.

That is correct. Personally I still fetch the still image from the camera.

**Comment by rhatguy** [comment]
TLDR for anyone with reolink cams and stream stability issues, I highly recommend rtsp-simple-server as @tubalainen mentioned.  #gamechanger!


I have 5 Reolink cameras and have tried all manner of RTSP/RTMP/HTTP/neolink to integrate them into a frigate and maintain a "stable" connection.  I was almost to the point of just throwing in the towel and replacing a few of my more critical cams with another brand, but rtsp-simple-server has changed the game for me.  I run frigate on a separate RPi4 and have rtsp-simple-server running on a separate larger, more powerful host.  I haven't moved rtsp-simple-server onto the frigate RPi4 yet as its currently using ~40% of one core on an intel 6132 CPU.  I'm not sure yet if my RPI4 is going to be capable of running both frigate AND rtsp-simple-server with 10 streams (5*640x480 detect streams, and 5*5MP record streams).  My rtsp-simple server has been running now for 13 days without a restart, and frigate almost as long, as I only restarted it recently to upgrade to 0.91.  So far, I haven't had a single detect or record stream get stuck to the point that I've had to restart either component, which I was doing every couple of days before.  The rtsp-simple-server does restart streams from time to time, but frigate (and Home Assistant) seem to be able to handle the restart MUCH more gracefully than when frigate was talking directly to the cams.

Looking forward to what @blakeblackshear  has been mentioning around a more robust relay inside Frigate to hopefully eliminate the need for a separate rtsp-simple-server.

**Reply by tubalainen** [reply]
> TLDR for anyone with reolink cams and stream stability issues, I highly recommend rtsp-simple-server as @tubalainen mentioned. #gamechanger!
> 
> I have 5 Reolink cameras and have tried all manner of RTSP/RTMP/HTTP/neolink to integrate them into a frigate and maintain a "stable" connection. I was almost to the point of just throwing in the towel and replacing a few of my more critical cams with another brand, but rtsp-simple-server has changed the game for me. I run frigate on a separate RPi4 and have rtsp-simple-server running on a separate larger, more powerful host. I haven't moved rtsp-simple-server onto the frigate RPi4 yet as its currently using ~40% of one core on an intel 6132 CPU. I'm not sure yet if my RPI4 is going to be capable of running both frigate AND rtsp-simple-server with 10 streams (5_640x480 detect streams, and 5_5MP record streams). My rtsp-simple server has been running now for 13 days without a restart, and frigate almost as long, as I only restarted it recently to upgrade to 0.91. So far, I haven't had a single detect or record stream get stuck to the point that I've had to restart either component, which I was doing every couple of days before. The rtsp-simple-server does restart streams from time to time, but frigate (and Home Assistant) seem to be able to handle the restart MUCH more gracefully than when frigate was talking directly to the cams.
> 
> Looking forward to what @blakeblackshear has been mentioning around a more robust relay inside Frigate to hopefully eliminate the need for a separate rtsp-simple-server.

Great stuff @rhatguy !
Did you manage to get RTMP streams not to flood and cause issues with the rtsp-simple-server? If so, please share your rtsp-simple-server config. For me, I cannot use RTMP streams at all with rtmp-simple-server.

ref: https://github.com/aler9/rtsp-simple-server/issues/585

**Reply by rhatguy** [reply]
I did not get RTMP working.  I have been using rtsp from the reolink to the rtsp-simple-server.  I think I remember trying RTMP and ran into probably the same issue as you, but after I switch to RTSP it has been the most stable config I've been able to come up with.  I'll try to find some time to switch my cams over to RTMP and see if they experience the same issue.  I suspect I will, or else I'd already be using RTMP:)

FYI, I have a long standing case open with Reolink that the live555 proxy server they are using on camera for RTSP is from 2013.04.08.  They've said they'll have a developer update the version of the software in their next release, but I'm not holding my breath.  As can be expected, there has been a mountain of work on the live555 proxy server over the last 8+ years that aren't incorporated into our cams due to Reolink's choice to use such an outdated library.  You can see below where the camera reports its version of the library to ffprobe when queried.  I have to wonder if newer versions of the library would be more stable (at the very least, there have been multiple security related patches during that time where the developers have encouraged EVERYONE using live555 to upgrade (One example below).

http://www.live555.com/liveMedia/public/changelog.txt
2013.11.29:
- Updated the previous bug fix to close another vulnerability.  All applications that include
  RTSP server or RTSP client SHOULD UPGRADE to the latest version of the code!
  (Thanks to iSEC Partners <http://isecpartners.com/> for discovering and reporting this bug.)


root@raspberrypi:/home/pi# ffprobe -v trace 'rtsp://user:pass@10.1.1.75:554/h264Preview_01_sub'
ffprobe version 4.1.6-1~deb10u1+rpt2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --disable-mmal --enable-neon --enable-vout-drm --enable-v4l2-request --enable-libudev --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Probing rtsp score:100 size:0
[tcp @ 0x55be352730] No default whitelist set
[tcp @ 0x55be352730] Original list of addresses:
[tcp @ 0x55be352730] Address 10.1.1.75 port 554
[tcp @ 0x55be352730] Interleaved list of addresses:
[tcp @ 0x55be352730] Address 10.1.1.75 port 554
[tcp @ 0x55be352730] Starting connection attempt to 10.1.1.75 port 554
[tcp @ 0x55be352730] Successfully connected to 10.1.1.75 port 554
.
.
.
.
[rtsp @ 0x55be377150] SDP:
v=0
o=- 1628462560079207 1 IN IP4 10.1.1.75
s=Session streamed by "preview"
i=h264Preview_01_sub
t=0 0
**a=tool:LIVE555 Streaming Media v2013.04.08**

**Reply by jasonpstokes** [reply]
My RLC-520A cameras are running preview firmware which reports `a=tool:LIVE555 Streaming Media v2020.08.12`, so they are working on it - or at least for the 520!? Which model(s) do you have?

Firmware details from the camera web UI:
```
Model RLC-520A
Build No. build 21083101
Hardware No. IPC_523128M5MP
Config Version v3.0.0.0
Firmware Version v3.0.0.584_21083101
```

I will try RTSP again, but using http paths (plus the Balanced stream for detection, instead of fluent) has been stable for me.

**Reply by rhatguy** [reply]
I run 4 RLC-410-5MP and 1 RLC-511W, all on the latest firmware available on the reolink download-center.  Did you get a "preview" version of the firmware by working with support?  I'd be happy to try a preview version with the newer firmware on one of my cams.  Have you been able to try the rtsp based streams yet again?

ModelRLC-511W
Build No.build 20121804
Hardware No.IPC_51516M5M
Config Versionv3.0.0.0
Firmware Versionv3.0.0.142_20121804

ModelRLC-410-5MP
Build No.build 20121100
Hardware No.IPC_51516M5M
Config Versionv3.0.0.0
Firmware Versionv3.0.0.136_20121100

**Reply by jasonpstokes** [reply]
Sorry @rhatguy, forgot I'd offered to try RTSP! I ran it for 24 hours using Frigate's default FFmpeg args. On Frigate startup there were some green camera screens and broken frame errors in the logs, but after after ~10 seconds the streams connected and were stable. The recordings were only OK though with some freezing and a bit of studder. So perhaps some improvements in the 520A camera hardware and/or this firmware, but still not perfect.

Instead of playing with FFmpeg I switched to RTMP streams using a previous config and...wow it's so much better! No issues on start-up and (more importantly) smoother recordings.  My initial impressions are that, on this firmware, RTMP is as good ~~or better than~~ as the HTTP streams, so I'll keep comparing as I get more clips over the coming days and see what happens in the logs.

Yes, Reolink Support sent me this firmware after I logged issues with the RTSP/RTMP streams. They've sent two; the second/current one on 1st Sept which, after checking in with them again last week, is still the latest they're giving out. To confess, I had upgraded but not tested this one, until now! (As I'd got HTTP paths to work well-enough in between.)

[Here's the 520A beta firmware](https://drive.google.com/file/d/146KJQpU7M4gm5MI3f_4HDZagP8szs3eG/view?usp=sharing) they sent me - but it may void your warranty etc. and doubt it will work for other models.

0.9.1 RTMP config.yml
```yaml

detect:
  width: 896
  height: 672
  fps: 5

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -rw_timeout 5000000 -f live_flv
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy # -an

motion:
  mask:
    - 265,650,265,625,630,625,630,650   # Camera timestamp, bottom centre

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.71/bcs/channel0_ext.bcs?channel=0&stream=2&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - detect
        - path: rtmp://192.168.1.71/bcs/channel0_main.bcs?channel=0&stream=0&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - record
```

**Reply by rhatguy** [reply]
They have not offered me a beta version for my cams yet and keep saying they'll update in the next version, but no timeline on when that would be.  The fact that they've given you a beta with a 2020 version does seem promising though as I believe there is a lot of commonality between their cams from what I've seen.  It is interesting that if they were going to go through the trouble to upgrade they would go to 2020.08.12 instead of something newer.  Perhaps they were already working on upgrading the library since before our requests.  I get worried about things like the below, that were changed in the library AFTER 2020.08.12.

2021.05.17:
- If a stream has no known duration, then our "a=range:" line (in the server's SDP description)
  now says "npt=now-" rather than "npt=0-".  Although the latter appears to be valid
  (according to RFC 2326), it has been claimed that "ffmpeg" RTSP clients do not handle it.
  (Thanks to Dmitry Bely for raising this issue.)

**Reply by sandstormkeshav** [reply]
Would you mind sharing your rtsp-simple-server configuration for the reolink cameras?

**Reply by digiblur** [reply]
Reolink needs to fix their codec issues as they used to work fine in the past then it got bad in the last couple of years. I definitely make it a point to tell them anytime I can that people are not buying their gear due to this and I don't recommend them for custom stuff like BI or Frigate. Glad to see them working on things. As I do get it, swapping cameras can be expensive.

**Comment by jasonpstokes** [comment]
I know it's kind of OT, but after two weeks of switching between RTMP and HTTP streams on my 520A's with the 31 Aug beta firmware, both are great: stable streams and fluent recordings. So I'd encourage everyone with Reolink's to contact support to explain what you're seeing and ask if they are working on it - and hopefully they get the message and provide better firmware for all models! (Especially as they still sell them all)

Frigate has crashed a few times with Python errors, but without anything to reference I don't know if this is a Frigate thing or a Reolink thing??

I'm still running 0.8.4. These are the relevant configs for reference-

**0.8.4 HTTP config**
- Frigate's [recommended config](https://docs.frigate.video/configuration/camera_specific/#reolink-410520-possibly-others), but with Reolink's default camera stream settings.
- Note the Detect resolution; the detect stream is the 'Balanced' stream but the resolution in the docs is for the smaller 'Fluent' stream. (Support say the balanced stream isn't optimised and so not recommended, but it works a lot better than their "optimised" fluent stream!)
```yaml
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args: -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: http://192.168.1.71/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - detect
        - path: http://192.168.1.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - clips
      output_args:
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy # -an
    width: 896
    height: 672
    fps: 5
```

**0.8.4 RTMP config**
- from [charlesmunger's post](https://github.com/blakeblackshear/frigate/issues/1467)
```yaml

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args: -fflags nobuffer -flags low_delay -strict experimental -rw_timeout 5000000 -f live_flv

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.71/bcs/channel0_ext.bcs?channel=0&stream=2&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - detect
        - path: rtmp://192.168.1.71/bcs/channel0_main.bcs?channel=1&stream=0&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - clips
      output_args:
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy # -an
    width: 896
    height: 672
    fps: 5
```
