### DISCUSSION TITLE
[Config Support]: configurar o frigate no mesmo servidor do gateway (firewal)

### DISCUSSION THREAD

**Discussion by gilsonlima10** [blakeblackshear/frigate#16234] [Config Support]
### Describe the problem you are having

ao instalar o frigate no mesmo servidor do gateway as cameras ficam com timeout (não podem ser alcançadas)

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false
tls:
  enabled: false
detectors:
  coral1:
    type: edgetpu
    device: pci:0
objects:
  track:
    - person
    - car
    - cat
    - dog
go2rtc:
  streams:
    cozinha:
      - ffmpeg:rtsp://admin:a4i5n1X4@172.27.10.201:8554/profile0
    atendimento:
      - ffmpeg:rtsp://172.27.10.202:8554/main
    churrasqueira:
      - ffmpeg:rtsp://172.27.10.206:8554/main
    casa:
      - ffmpeg:rtsp://172.27.10.204:8554/main
cameras:
  cozinha:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:a4i5n1X4@172.27.10.201:8554/profile0
          hwaccel_args: preset-vaapi
          roles:
            - detect
    onvif:
      host: 172.27.10.201
      port: 6688
      user: admin
      password: a4i5n1X4
    detect:
      enabled: false # <---- disable detection until you have a working camera >
      width: 1920
      height: 1080
  atendimento:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://172.27.10.202:8554/main
          hwaccel_args: preset-vaapi
          roles:
            - detect
    onvif:
      host: 172.27.10.202
      port: 835
      user: admin
      password: a4i5n1X4
.
.
.
camera_groups:
  restdozeze:
    order: 1
    icon: LuActivitySquare
    cameras:
      - atendimento
      - casa
      - churrasqueira
      - cozinha
      - entrada
      - rua
      - salao
      - birdseye
version: 0.14
```

### Relevant Frigate log output

```shell
error
2025-01-30 18:35:05
ffmpeg.casa.detect
Last message repeated 1 times
error
2025-01-30 18:35:05
ffmpeg.casa.detect
rtsp://172.27.10.204:8554/main: Connection timed out
error
2025-01-30 18:35:05
ffmpeg.casa.detect
Last message repeated 1 times
```

### Relevant go2rtc log output

```shell
listen addr=:8554
info
2025-01-30 16:52:04
webrtc
listen addr=:8555/tcp
info
2025-01-30 16:52:13
startup
Starting go2rtc healthcheck service...
```

### Frigate stats

```json
firewall - script usada no server
#!/bin/sh

### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start firewall at boot time
# Description:       Enable service provided by firewall
### END INIT INFO

#######clear

echo "------------ FIREWALL ------------"

PORTS_INPUT="/etc/multiredes/gw/ports_input"
PORTS_OUTPUT="/etc/multiredes/gw/ports_output"
PORTS_FORWARD="/etc/multiredes/gw/ports_forward"
PORTS_REDIRECT="/etc/multiredes/gw/ports_redirect"
LINKS="/etc/multiredes/gw/links"
LINK_LAN="/etc/multiredes/gw/link_lan1"
MACS_BLOCK="/etc/multiredes/gw/macs_block"
SCRIPT_FIREWALL="/etc/init.d/firewall"
# CARREGAR MÓDULOS
echo "CARREGANDO MODULOS.......................................................................[OK]"
sudo modprobe ip_tables
sudo modprobe iptable_nat
sudo modprobe iptable_mangle
sudo modprobe ip_nat_ftp
sudo modprobe ip_nat_h323
sudo modprobe ipt_limit
sudo modprobe ipt_tos

#### LIMPAR REGRAS
echo "LIMPANDO REGRAS ANTIGAS..................................................................[OK]"
sudo iptables -F
sudo iptables -t nat -F
sudo iptables -t mangle -F
sudo iptables -X
sudo iptables -t nat -X
sudo iptables -t mangle -X
case "$1" in

start)

#### LIMPA TABELAS E ALTERA POLITICAS PARA DROP E OUTPUT PARA ACCEPT
sudo iptables -t nat -F
sudo iptables -F
#$flt -F INPUT
#$flt -F OUTPUT
#$flt -F FORWARD
#$flt -t mangle -F
#$flt -X
sudo iptables -P INPUT DROP
sudo iptables -P FORWARD DROP
sudo iptables -P OUTPUT ACCEPT


echo "LIMPANDO TABELAS E DEFININDO POLITICA PARA DROP E ACCEPT ................................[OK]"

# ativando repasse de pacotes
echo "1" > /proc/sys/net/ipv4/ip_dynaddr
echo "1" > /proc/sys/net/ipv4/ip_forward

# liberar acesso interno
echo "LIBERANDO ACESSO LOCAL...................................................................[OK]"
sudo iptables -A INPUT -i loopback -j ACCEPT
sudo iptables -A INPUT -s 127.0.0.1 -j ACCEPT
# aceitar pacotes de retorno
sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT


#evitar ataque de hacker ao asterisk - liberar porta do asterisk
#sudo iptables -A INPUT -p udp --dport 5060 -m state --state ESTABLISHED,RELATED -j ACCEPT
#sudo iptables -A INPUT -p udp --dport 5060 -m string --string "REGISTER sip:sip.multiredes.com.br" --algo bm -j ACCEPT
#sudo iptables -A INPUT -p udp --dport 5060 -m string --string "REGISTER sip:172.27.0.1" --algo bm -j ACCEPT
#sudo iptables -A INPUT -p udp --dport 5060 -m string --string "REGISTER sip:" --algo bm -j DROP
#sudo iptables -A INPUT -p udp --dport 5060 -m string --string "OPTIONS sip:" --algo bm -j DROP
#sudo iptables -A INPUT -p udp --dport 5060 -j ACCEPT

##sudo iptables -w --table filter --insert LIBVIRT_INP --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT

# Bloquear IPS indesejados
#sudo iptables -A INPUT -s 89.238.131.145 -j DROP
#sudo iptables -A INPUT -s 195.154.217.108 -j DROP
# BLOQUEIO DE MACS INDESEJAVEIS
#for i in `cat $MACS_BLOCK`; do
#MAC_BLOQUEIO=`echo $i | cut -d ';' -f 1`
#DESCRICAO=`echo $i | cut -d ';' -f 2`
#sudo iptables -A FORWARD -m mac --mac-source $MAC_BLOQUEIO -j DROP
#done

## BLOQUEIO DE REDES POR HORARIO  (gmt -3)
sudo iptables -A FORWARD -s 172.27.200.0/24 -m time --timestart 22:00 --timestop 00:00 -j DROP
sudo iptables -A FORWARD -s 172.27.200.0/24 -m time --timestart 00:00 --timestop 14:00 -j DROP
sudo iptables -A FORWARD -s 172.27.50.0/24 -m time --timestart 23:00 --timestop 00:00 -j DROP
sudo iptables -A FORWARD -s 172.27.50.0/24 -m time --timestart 00:00 --timestop 12:00 -j DROP
sudo iptables -A FORWARD -s 172.27.50.0/24 -m time --timestart 15:00 --timestop 18:00 -j DROP
sudo iptables -A FORWARD -s 172.27.90.0/255.255.255.0 -j DROP

#sudo iptables -A FORWARD -s 172.27.200.0/255.255.255.0 -j DROP 
##iptables REGRA -m time –timestart HORAINICIO –timestop HORAFIM –days DAYS -j AÇÃO

## proteções
## anti-ip spoofing - desativar por causa do iproute2
#if [ -e /proc/sys/net/ipv4/conf/all/rp_filter ]; then
#  for f in /proc/sys/net/ipv4/conf/*/rp_filter; do
#    echo 0 > $f
#  done
#fi
# serviços externos
echo "LIBERANDO ACESSO DOS SERVIÇOS............................................................[OK]"

# retorno proxy
sudo iptables -A INPUT -p tcp --dport 3128 --sport 80   -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 3128 --sport 8080 -j ACCEPT

#### PORTAS
## LIBERAR INPUT
for i in `cat $PORTS_INPUT`; do
NUMERO=`echo $i | cut -d ';' -f 1`
TIPO=`echo $i | cut -d ';' -f 2`

sudo iptables -A INPUT -p $TIPO -s 0.0.0.0/0.0.0.0 --dport $NUMERO -j ACCEPT

done

echo "LIBERADO PORTAS INPUT ...................................................................[OK]"

##### PORTAS
## LIBERAR OUTPUT
for i in `cat $PORTS_OUTPUT`; do
NUMERO=`echo $i | cut -d ';' -f 1`
TIPO=`echo $i | cut -d ';' -f 2`

sudo iptables -A OUTPUT -p $TIPO -s 0.0.0.0/0.0.0.0 --dport $NUMERO -j ACCEPT
done
echo "LIBERADO PORTAS OUTPUT ..................................................................[OK]"
echo "REDIRECIONAMENTO DE PORTAS ..............................................................[OK]"

for iw in `cat $LINKS`;do
        table_link=`echo $iw | cut -d ';' -f 1`
        link_iface=`echo $iw | cut -d ';' -f 2`
        link_ip_local=`echo $iw | cut -d ';' -f 3`
        link_gw=`echo $iw | cut -d ';' -f 4`

        if [ $table_link = "link_lan1" ]; then
                # Liberar Serviços Internos
                echo "comandos aqui!!"
                #sudo iptables -A INPUT -i $link_iface -p tcp --dport 22   -j ACCEPT
                #sudo iptables -A INPUT -i $link_iface -p tcp --dport 53   -j ACCEPT
                #sudo iptables -A INPUT -i $link_iface -p udp --dport 53   -j ACCEPT
                #sudo iptables -A INPUT -i $link_iface -p tcp --dport 80   -j ACCEPT
                #sudo iptables -A INPUT -i $link_iface -p tcp --dport 3128 -j ACCEPT
                #$ipt -A INPUT -s $link_ip_local -j ACCEPT

                else

                ##$ipt -A INPUT -i $link_iface -s 192.168.0.0/255.255.0.0 -j DROP
                ##$ipt -A INPUT -i $link_iface -s 172.0.0.0/255.0.0.0 -j DROP
                ##$ipt -A INPUT -i $link_iface -s 10.0.0.0/255.0.0.0 -j DROP

                #liberar Serviços Locais
                sudo ip rule del from $link_ip_local
                sudo ip rule add from $link_ip_local table $table_link

                for i in `cat /etc/multiredes/gw/$table_link`;do
                        ip=`echo $i | cut -d ';' -f 1`
                        sudo ip rule del from $ip
                        sudo ip rule add from $ip table $table_link

                        # aplicar mudanças no iproute
                           sudo ip route flush cache

                                for i in `cat $PORTS_FORWARD`; do
                                NUMERO=`echo $i | cut -d ';' -f 1`
                                TIPO=`echo $i | cut -d ';' -f 2`
                                sudo iptables -A FORWARD -p $TIPO -s $ip --dport $NUMERO -j ACCEPT
                                #$ipt -A FORWARD -s $ip -j ACCEPT
                                done
                done

        sudo ip route add $link_ip_local via $link_gw dev $link_iface table $table_link
        sudo ip route add default via $link_gw table $table_link

        fi
done

                        for im in `cat $LINK_LAN`; do
                                table_link=`echo $im | cut -d ';' -f 1`
                                IP_LAN=`echo $im | cut -d ';' -f 1`
                                        ### redirecionamento para o proxy
                                        #$ipt -t nat -A PREROUTING -p tcp -s $IP_LAN --dport 80 -j REDIRECT --to-port 3128
                                        #$ipt -t nat -A PREROUTING -p tcp -s $IP_LAN --dport 8080 -j REDIRECT --to-port 3128
                                        sudo iptables -t nat -A OUTPUT -p tcp -s $IP_LAN --dport 80 -j REDIRECT --to-port 3128
                                        sudo iptables -t nat -A OUTPUT -p tcp -s $IP_LAN --dport 8080 -j REDIRECT --to-port 3128

                        done

                        for it in `cat $LINKS`; do
                                table_link=`echo $it | cut -d ';' -f 1`
                                link_iface=`echo $it | cut -d ';' -f 2`
                                if [ $table_link != "link_lan1" ]; then
                                        echo  "PERMITE TRAFEGO PARA A INTERNET..........................................................[OK]"
                                         sudo iptables -t nat -A POSTROUTING -o $link_iface -j MASQUERADE
                                        #sudo iptables -t nat -A POSTROUTING -o $link_iface -s 0.0.0.0/0.0.0.0 -j MASQUERADE
                                echo -n "."
                                fi
                      done


echo ""
echo "-----------------------..................................................................[TUDO OK]"
sleep 5

;;

stop)

sudo iptables -t nat -F
sudo iptables -F
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT

echo "FIREWALL DESCARREGADO - SISTEMA LIBERADO"

;;
restart)
$SCRIPT_FIREWALL stop
$SCRIPT_FIREWALL start
;;

*)
echo "Use: $N {start|stop|restart}" >&2
echo "VOCÊ NÃO COLOCOU UM ARGUMENTO VÁLIDO . O FIREWALL IRÁ RESTARTAR EM 5 SEGUNDOS............"
sleep 5
$SCRIPT_FIREWALL restart
exit 1
esac
exit 0
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128 # for Intel hardware acceleration
#          devices:
#            - driver: nvidia # for nvidia hardware acceleration
#            #  device_ids: ['0'] # this is only needed when using multiple GPUs
#              count: 1 # number of GPUs
#              capabilities: [gpu]
    shm_size: "990mb"
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984" # go2rtc web interface
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "5001:5001" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
#      - LIBVA_DRIVER_NAME=i965 #uso com INTEL
      - LIBVA_DRIVER_NAME=radeonsi # uso com AMD Raden
```

### Object Detector

Coral
