### DISCUSSION TITLE
[Camera Support]: DAHUA Onvif SD3C405DB-GNY-A-PV tracking Timeout issue

### DISCUSSION THREAD

**Discussion by JBaptisme33** [blakeblackshear/frigate#16241] [Camera Support]
### Describe the problem you are having

Hello,

Onto Dahua SD3C405DB-GNY-A-PV , ONVIF command reach timeout issues
Preset always work. On startup, I calibrate camera. It seem work as expected.
When first tracking appear, ONVIF command work, but a timeout occur (In first command, or another one, I'me not sure).

After timeout, Tracking does not work anymore, until Frigate process reboot.

### Version

0.15.1

### Frigate config file

```yaml
onvif:
      host: XXXXXXX
      port: 80
      user: ''
      password: ''
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: true
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.1
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - full
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: first
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 3
        movement_weights: 0.0, 1.0, 4.153805494308472, 5.59576836247598, 2.202102678821934
    zones:
      full:
        coordinates: 
          0,0.099,0.711,0.05,0.714,0.195,0.808,0.258,0.982,0.466,0.982,0.532,0.974,0.638,0.999,0.696,1,0.794,0.896,1,0.004,0.995
        loitering_time: 0
```

### Relevant Frigate log output

```shell
info  | 2025-01-31 08:40:48 | frigate.ptz.autotrack   | Calibration for ptzcamera in progress: 93% complete
debug | 2025-01-31 08:40:48 | frigate.ptz.onvif       | ptzcamera called RelativeMove: pan: 1.0 tilt: 1.0 zoom: 0
debug | 2025-01-31 08:40:48 | frigate.ptz.onvif       | ptzcamera: PTZ start time: 0.0
debug | 2025-01-31 08:40:57 | frigate.ptz.onvif       | ptzcamera: PTZ stop time: 0.0
debug | 2025-01-31 08:41:03 | frigate.ptz.onvif       | ptzcamera: PTZ stop time: 0.0
info  | 2025-01-31 08:41:03 | frigate.ptz.autotrack   | Calibration for ptzcamera in progress: 97% complete
info  | 2025-01-31 08:41:03 | frigate.ptz.autotrack   | Calibration for ptzcamera complete
info  | 2025-01-31 08:41:03 | frigate.app             | Camera processor started for ptzcamera: 496
info  | 2025-01-31 08:41:03 | frigate.app             | Capture process started for ptzcamera: 497
info  | 2025-01-31 08:41:03 | frigate.api.fastapi_app | Starting FastAPI app
info     | 2025-01-31 08:41:03 | frigate.api.fastapi_app | FastAPI started
debug   | 2025-01-31 10:58:01 | frigate.ptz.onvif       | ptzcamera called RelativeMove: pan: -1.0 tilt: 1.0 zoom: 0
debug   | 2025-01-31 10:58:01 | frigate.ptz.onvif       | ptzcamera: PTZ start time: 1738321081.580013
unknown | 2025-01-31 10:58:11 | unknown                 | Exception in thread ptz_move_thread_ptzcamera:
unknown | 2025-01-31 10:58:11 | unknown                 | Traceback (most recent call last):
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
unknown | 2025-01-31 10:58:11 | unknown                 | response = conn.getresponse()
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 516, in getresponse
unknown | 2025-01-31 10:58:11 | unknown                 | httplib_response = super().getresponse()
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/lib/python3.9/http/client.py", line 1351, in getresponse
unknown | 2025-01-31 10:58:11 | unknown                 | response.begin()
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/lib/python3.9/http/client.py", line 316, in begin
unknown | 2025-01-31 10:58:11 | unknown                 | version, status, reason = self._read_status()
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/lib/python3.9/http/client.py", line 277, in _read_status
unknown | 2025-01-31 10:58:11 | unknown                 | line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/lib/python3.9/socket.py", line 704, in readinto
unknown | 2025-01-31 10:58:11 | unknown                 | return self._sock.recv_into(b)
unknown | 2025-01-31 10:58:11 | unknown                 | socket.timeout: timed out
unknown | 2025-01-31 13:36:11 | unknown                 | 25-01-31 10:58:11.930027949
unknown | 2025-01-31 10:58:11 | unknown                 | The above exception was the direct cause of the following exception:
unknown | 2025-01-31 13:36:11 | unknown                 | 25-01-31 10:58:11.930030817
unknown | 2025-01-31 10:58:11 | unknown                 | Traceback (most recent call last):
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 667, in send
unknown | 2025-01-31 10:58:11 | unknown                 | resp = conn.urlopen(
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 841, in urlopen
unknown | 2025-01-31 10:58:11 | unknown                 | retries = retries.increment(
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 474, in increment
unknown | 2025-01-31 10:58:11 | unknown                 | raise reraise(type(error), error, _stacktrace)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/util/util.py", line 39, in reraise
unknown | 2025-01-31 10:58:11 | unknown                 | raise value
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
unknown | 2025-01-31 10:58:11 | unknown                 | response = self._make_request(
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
unknown | 2025-01-31 10:58:11 | unknown                 | self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
unknown | 2025-01-31 10:58:11 | unknown                 | raise ReadTimeoutError(
unknown | 2025-01-31 10:58:11 | unknown                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.37', port=80): Read timed out. (read timeout=10)
unknown | 2025-01-31 13:36:11 | unknown                 | 25-01-31 10:58:11.931161759
unknown | 2025-01-31 10:58:11 | unknown                 | During handling of the above exception, another exception occurred:
unknown | 2025-01-31 13:36:04 | unknown                 | 25-01-31 10:58:11.931163714
unknown | 2025-01-31 10:58:11 | unknown                 | Traceback (most recent call last):
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 23, in wrapped
unknown | 2025-01-31 10:58:11 | unknown                 | return func(*args, **kwargs)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 153, in wrapped
unknown | 2025-01-31 10:58:11 | unknown                 | return call(params, callback)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 140, in call
unknown | 2025-01-31 10:58:11 | unknown                 | ret = func(**params)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/zeep/proxy.py", line 46, in __call__
unknown | 2025-01-31 10:58:11 | unknown                 | return self._proxy._binding.send(
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/zeep/wsdl/bindings/soap.py", line 127, in send
unknown | 2025-01-31 10:58:11 | unknown                 | response = client.transport.post_xml(options["address"], envelope, http_headers)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/zeep/transports.py", line 108, in post_xml
unknown | 2025-01-31 10:58:11 | unknown                 | return self.post(address, message, headers)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/zeep/transports.py", line 74, in post
unknown | 2025-01-31 10:58:11 | unknown                 | response = self.session.post(
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 637, in post
unknown | 2025-01-31 10:58:11 | unknown                 | return self.request("POST", url, data=data, json=json, **kwargs)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
unknown | 2025-01-31 10:58:11 | unknown                 | resp = self.send(prep, **send_kwargs)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
unknown | 2025-01-31 10:58:11 | unknown                 | r = adapter.send(request, **kwargs)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 713, in send
unknown | 2025-01-31 10:58:11 | unknown                 | raise ReadTimeout(e, request=request)
unknown | 2025-01-31 10:58:11 | unknown                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.37', port=80): Read timed out. (read timeout=10)
unknown | 2025-01-31 13:36:04 | unknown                 | 25-01-31 10:58:11.933053992
unknown | 2025-01-31 10:58:11 | unknown                 | During handling of the above exception, another exception occurred:
unknown | 2025-01-31 13:36:04 | unknown                 | 25-01-31 10:58:11.933056046
unknown | 2025-01-31 10:58:11 | unknown                 | Traceback (most recent call last):
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
unknown | 2025-01-31 10:58:11 | unknown                 | self.run()
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/lib/python3.9/threading.py", line 892, in run
unknown | 2025-01-31 10:58:11 | unknown                 | self._target(*self._args, **self._kwargs)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/opt/frigate/frigate/ptz/autotrack.py", line 672, in _process_move_queue
unknown | 2025-01-31 10:58:11 | unknown                 | self.onvif._move_relative(camera, pan, tilt, 0, 1)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/opt/frigate/frigate/ptz/onvif.py", line 453, in _move_relative
unknown | 2025-01-31 10:58:11 | unknown                 | onvif.get_service("ptz").RelativeMove(move_request)
unknown | 2025-01-31 10:58:11 | unknown                 | File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 26, in wrapped
unknown | 2025-01-31 10:58:11 | unknown                 | raise ONVIFError(err)
unknown | 2025-01-31 10:58:11 | unknown                 | onvif.exceptions.ONVIFError: Unknown error: HTTPConnectionPool(host='192.168.1.37', port=80): Read timed out. (read timeout=10)
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

DAHUA SD3C405DB-GNY-A-PV

### Screenshots of the Frigate UI's System metrics pages

N/A

**Comment by hawkeye217** [comment]
Your calibration movement weights are very odd. 

Is this camera connected via wifi?

**Reply by JBaptisme33** [reply]
Hello, 
Nope over ethernet/POE. Actually camera is badly positionned. It need to make a "350 degree" to go from right to left. The back of the camera is positioned on the front due to the mounting. Preset "full" look on  right side , but when camera need to good to left side, ~300-350 degree movement is needed,

**Reply by hawkeye217** [reply]
The motor seems very slow. Your calibration values indicate that it would take ~24 seconds to make a full range movement. 

Does the firmware have the ability to change the motor speed?

**Reply by JBaptisme33** [reply]
Yes it seem
![image](https://github.com/user-attachments/assets/b642fc93-f2f2-4267-8394-8243d0269df2)
I will try to test right now
How to obtain 24sec calculation ?

**Reply by JBaptisme33** [reply]
With "fast PTZ speed" (slow / med / fast configurable)

```
        movement_weights: 0.0, 1.0, 3.84318470954895, 5.611103928986415, 2.0233737976320336
    zones:
      full:
        coordinates: 
          0,0.099,0.711,0.05,0.714,0.195,0.808,0.258,0.982,0.466,0.982,0.532,0.974,0.638,0.999,0.696,1,0.794,0.896,1,0.004,0.995
```

**Reply by hawkeye217** [reply]
> Yes it seem ![image](https://private-user-images.githubusercontent.com/59478661/408634774-b642fc93-f2f2-4267-8394-8243d0269df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgzNDEwMTEsIm5iZiI6MTczODM0MDcxMSwicGF0aCI6Ii81OTQ3ODY2MS80MDg2MzQ3NzQtYjY0MmZjOTMtZjJmMi00MjY3LTgzOTQtODI0M2QwMjY5ZGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTMxVDE2MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNWJlY2IyMTNkMDUxYTU2NDMwODczN2Q4ZmMzMDRlOGEwODY4NmEzNzRjYTE1NzE1NDk2MzIxMTJjNDVmOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ugXWLfrKbCEGVZ470HC7jdwTb8JfhavZc8K9rto1LX0) I will try to test right now How to obtain 24sec calculation ?

I don't believe that speed control affects ONVIF movement. Is there another setting elsewhere?

**Reply by JBaptisme33** [reply]
I've just mount camera front size. All is better now. No more timeout issues actually.
I have issue during night movement now (cannot find personn type during night).

For information, after calibration I have values like below (cannot undersand if it is better ^^)
```
        timeout: 3
        movement_weights: 0.2, 1.0, 6.397319555282593, 11.602184839146108, 2.2382837503187125
    zones:
      full:
        coordinates: 
          0.008,0.022,0.72,0.013,0.718,0.096,0.836,0.205,1,0.364,1,0.54,1,0.639,0.999,0.696,1,0.794,0.896,1,0.004,0.995
```
