### DISCUSSION TITLE
[Detector Support]: how to test openvino from Frigate+ edgetpu baseline

### DISCUSSION THREAD

**Discussion by gspitale** [blakeblackshear/frigate#16246] [Detector Support]
### Describe the problem you are having

I'm not entirely clear on the steps required to try openvino / yolonas.

I currently have edgetpu with Frigate+ model defined.  I've read that openvino is better at detecting objects that are small or at distance.  My setup is a heavily wooded area with lots of wildlife, so I want to test openvino to see if I get better detections.

What do I need to do / change?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: homeassistant.havenwood
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-usr
  password: xxxxxxx

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
#  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac


detectors:
  coral_1:
    type: edgetpu
    device: pci:0
#  coral_2:
#    type: edgetpu
#    device: pci:1

model:
  path: plus://5dd697493e57fd0288cba90f60e656b6

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

review:
  alerts:
    labels:
      - person
      - bicycle
      - car
      - cat
      - dog
      - bear

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  retain:
    default: 21

audio:
  enabled: true

go2rtc:
  streams:
    FrontYard:
      - rtsp://frontyard.camera.havenwood:554/media/video1#backchannel=0
    FrontYardsub:
      - rtsp://frontyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:FrontYardsub#audio=aac
    FrontYardsub2:
      - rtsp://frontyard.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:FrontYardsub2#audio=aac
    FrontDoor:
      - rtsp://frontdoor.camera.havenwood:554/media/video1#backchannel=0
    FrontDoorsub:
      - rtsp://frontdoor.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:FrontDoorsub#audio=aac
    Driveway1:
      - rtsp://driveway1.camera.havenwood:554/media/video1#backchannel=0
    Driveway1sub:
      - rtsp://driveway1.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Driveway1sub#audio=aac
    Driveway1sub2:
      - rtsp://driveway1.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:Driveway1sub2#audio=aac
    Driveway2:
      - rtsp://driveway2.camera.havenwood:554/media/video1#backchannel=0
    Driveway2sub:
      - rtsp://driveway2.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Driveway2sub#audio=aac
    Driveway2sub2:
      - rtsp://driveway2.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:Driveway2sub2#audio=aac
    Garage:
      - rtsp://garage.camera.havenwood:554/media/video1#backchannel=00
    Garagesub:
      - rtsp://garage.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Garagesub#audio=aac
    Garagesub2:
      - rtsp://garage.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:Garagesub2#audio=aac
    NorthYard:
      - rtsp://northyard.camera.havenwood:554/media/video1#backchannel=00
    NorthYardsub:
      - rtsp://northyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:NorthYardsub#audio=aac
    NorthYardsub2:
      - rtsp://northyard.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:NorthYardsub2#audio=aac
    BackYard1:
      - rtsp://backyard1.camera.havenwood:554/media/video1#backchannel=0
    BackYard1sub:
      - rtsp://backyard1.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackYard1sub#audio=aac
    BackYard1sub2:
      - rtsp://backyard1.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:BackYard1sub2#audio=aac
    BackYard2:
      - rtsp://backyard2.camera.havenwood:554/media/video1#backchannel=0
    BackYard2sub:
      - rtsp://backyard2.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackYard2sub#audio=aac
    BackYard2sub2:
      - rtsp://backyard2.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:BackYard2sub2#audio=aac
    NorthDeck:
      - rtsp://northdeck.camera.havenwood:554/media/video1#backchannel=0
    NorthDecksub:
      - rtsp://northdeck.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:NorthDecksub#audio=aac
    SouthDeck:
      - rtsp://southdeck.camera.havenwood:554/media/video1#backchannel=0
    SouthDecksub:
      - rtsp://southdeck.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:SouthDecksub#audio=aac
    SouthDecksub2:
      - rtsp://southdeck.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:SouthDecksub2#audio=aac
    SouthYard:
      - rtsp://southyard.camera.havenwood:554/media/video1#backchannel=00
    SouthYardsub:
      - rtsp://southyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:SouthYardsub#audio=aac
    SouthYardsub2:
      - rtsp://southyard.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:SouthYardsub2#audio=aac


record:
  enabled: true
  retain:
    days: 21
    mode: all

cameras:
  FrontYard:
    enabled: true
    ui:
      order: 1
    detect:
      enabled: true
    record:
      enabled: true
#    live:
#      stream_name: FrontYardsub2
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontYard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontYardsub
          roles:
            - audio
            - detect
    motion:
      mask: 0.737,0.903,0.982,0.902,0.981,0.958,0.735,0.96
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  FrontDoor:
    enabled: true
    ui:
      order: 2
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
#    live:
#      stream_name: FrontDoorsub
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoor
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoorsub
          roles:
            - audio
            - detect
    motion:
      mask: 0.016,0.961,0.273,0.963,0.273,0.899,0.014,0.892
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  Driveway1:
    enabled: true
    ui:
      order: 3
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
#    live:
#      stream_name: Driveway1sub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway1sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.017,0.042,0.268,0.039,0.268,0.1,0.017,0.1
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  Driveway2:
    enabled: true
    ui:
      order: 4
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
#    live:
#      stream_name: Driveway2sub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway2sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.735,0.957,1,0.954,1,0.902,0.734,0.905
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  Garage:
    enabled: true
    ui:
      order: 5
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - dog
#    live:
#      stream_name: Garagesub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garagesub
          roles:
            - audio
            - detect
    motion:
      mask: 0.268,0.959,0.024,0.961,0.023,0.904,0.269,0.906
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  NorthYard:
    enabled: true
    ui:
      order: 6
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
#    live:
#      stream_name: NorthYardsub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/NorthYard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthYardsub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.022,0.959,0.267,0.961,0.267,0.902,0.022,0.902
        - 0.202,0,0.282,0.166,0.506,0.172,0.584,0
        - 0.964,0,0.926,0.119,0.941,0.22,1,0.277,1,0
      threshold: 30
      contour_area: 11
      improve_contrast: 'true'
  BackYard1:
    enabled: true
    ui:
      order: 7
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
#    live:
#      stream_name: BackYard1sub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/BackYard1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard1sub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.02,0.956,0.269,0.961,0.268,0.904,0.02,0.899
        - 0.831,0,1,0,1,0.174,1,1,0.933,1,0.902,0.547,0.824,0.437,0.733,0.229,0.7,0
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  BackYard2:
    enabled: true
    ui:
      order: 8
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
#    live:
#      stream_name: BackYard2sub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/BackYard2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard2sub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.735,0.954,0.977,0.954,0.978,0.904,0.733,0.906
        - 0.805,0,0.815,0.1,0.893,0.218,1,0.389,1,0
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  NorthDeck:
    enabled: true
    ui:
      order: 9
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
#    live:
#      stream_name: NorthDecksub
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/NorthDeck
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthDecksub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.022,0.09,0.268,0.092,0.268,0.044,0.023,0.039
        - 0.321,0.56,0.405,0.712,0.449,0.627,0.332,0.421
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  SouthDeck:
    enabled: true
    ui:
      order: 10
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
#    live:
#      stream_name: SouthDecksub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/SouthDeck
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthDecksub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.735,0.954,0.979,0.952,0.979,0.904,0.734,0.904
        - 0.527,0.412,0.595,0.44,0.595,0.493,0.529,0.472
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
  SouthYard:
    enabled: true
    ui:
      order: 11
    detect:
      enabled: true
    record:
      enabled: true
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
#    live:
#      stream_name: SouthYardsub2
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/SouthYard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthYardsub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.02,0.087,0.267,0.092,0.267,0.044,0.023,0.044
        - 0.575,0,0.591,0.415,0.7,0.492,1,0.637,1,0.274,1,0,0.804,0
        - 0,0,0,0.251,0,0.353,0.073,0.308,0.124,0.203,0.159,0
      threshold: 32
      contour_area: 11
      improve_contrast: 'true'
    zones: {}
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
#    network_mode: host
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1000mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./config:/config
      - /mnt/frigate_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
      - "1984:1984"
    environment:
      - PLUS_API_KEY=xxx
```

### Relevant Frigate log output

```shell
nothing relevant
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1274" alt="Screenshot 2025-01-31 at 8 49 00 AM" src="https://github.com/user-attachments/assets/9af6c397-ec41-4810-8e1a-30b05733693c" />
<img width="1479" alt="Screenshot 2025-01-31 at 8 49 58 AM" src="https://github.com/user-attachments/assets/80570bdb-3209-462c-a3d6-3cd7bddd40e6" />
