### DISCUSSION TITLE
[HW Accel Support]: Failed to initialize PMU

### DISCUSSION THREAD

**Discussion by Phyxsius7** [blakeblackshear/frigate#16242] [Hardware Acceleration Support]
### Describe the problem you are having

After having read the following issue https://github.com/blakeblackshear/frigate/issues/5271.
I would like to know if GPU support is still not support by Frigate addon.
The log message "ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied)" does seem to suggest that it is still not supported but maybe it is supported after additional setting have been set.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 11.22.33.44
  user: user
  password: password
cameras:
  Cam_D:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://us01:1234abc@11.22.33.11:123/stream/chn/01
          input_args: preset-rtsp-generic
          roles:
            - record
        - path: rtsp://us01:1234abc@11.22.33.11:554/stream/chn/02
          input_args: preset-rtsp-generic
          roles:
            - detect
    zones:
      Cam_D_01:
        coordinates: 0.26,0.991,0.648,0.355,0.641,0.296,0.938,0.367,0.968,0.633,0.986,1
        objects: 
          - person
          - car
          - dog
        inertia: 3
        loitering_time: 0
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - car
        - cat
        - dog
        - bird
        - handbag
        - package
      filters:
        car:
          mask: 0.497,0.057,0.56,0.03,0.583,0.332,0.528,0.406
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      quality: 100
      required_zones:
        - Cam_D_01
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 7
          mode: motion
    motion:
      mask: 0.022,0.035,0.313,0.038,0.312,0,0.024,0
    review:
      alerts:
        required_zones: 
          - Cam_D_01
  Cam_B:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user02:12345abc@11.22.33.12:123/stream/chn/01
          input_args: preset-rtsp-generic
          roles:
            - record
        - path: rtsp://user02:1234abc@11.22.33.12:123/stream/chn/02
          input_args: preset-rtsp-generic
          roles:
            - detect
    zones:
      Cam_B_01:
        coordinates: 0.152,0.994,0.102,0.759,0.053,0.295,0.399,0.133,0.896,0.466,0.834,0.994
        objective:
          - persons:
              min_score: 0.72 #0.65
              threshold: 0.70 #0.75
        inertia: 3
        loitering_time: 0
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - car
        - cat
        - dog
        - bird
        - handbag
        - package
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      quality: 100
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 7
          mode: motion
    motion:
      mask:
        - 0.021,0,0.317,0,0.319,0.036,0.021,0.034
        - 0.968,0.09,0.965,0.403,0.869,0.859,0.728,0.75,0.784,0.457,0.792,0.296,0.856,0.091
        - 0.092,0.069,0.048,0.072,0.053,0.292,0.077,0.54,0.125,0.504,0.117,0.356,0.114,0.198
        - 0.22,0.425,0.301,0.396,0.288,0.164,0.338,0.148,0.364,0.035,0.26,0.039,0.225,0.051,0.186,0.07
        - 0.626,0.004,0.998,0.001,0.997,0.231,0.648,0.069
    review:
      alerts:
        required_zones: Cam_B_01
  Cam_L:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user03:123456abc@11.22.33.13/l0
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      quality: 100
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: motion
    motion:
      mask: 0.674,0.021,0.673,0.06,0.979,0.064,0.979,0.016
  Cam_K:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user04:1234567abc@11.22.33.14/l0
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      quality: 100
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: motion
    motion:
      mask: 0.674,0.021,0.673,0.06,0.979,0.064,0.979,0.016
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
camera_groups:
  Cam_B:
    order: 1
    icon: LuTrees
    cameras: Cam_B
  Cam_D:
    order: 2
    icon: LuWarehouse
    cameras: Cam_D
  I_r:
    order: 3
    icon: LuSofa
    cameras:
      - Cam_L
      - Cam_K
```

### docker-compose file or Docker CLI command

```yaml
none
```

### Relevant Frigate log output

```shell
2025-01-31 11:53:58.015993141  [2025-01-31 12:53:58] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied)
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

several

### Screenshots of the Frigate UI's System metrics pages

![KxESlwFgZD](https://github.com/user-attachments/assets/af5e322a-90d1-4311-aa84-a6e522c4dde5)
![Bfks9opqMi](https://github.com/user-attachments/assets/8e19def4-fdee-4086-9db6-a0cbf348f89b)

### Any other information that may be helpful

Intel NUC NUC5i3RYH (Intel Core i3-5010U, 8GB RAM)
Debian 12
Home Assistant
- Core: 2025.1.4
- Supervisor: 2024.12.3
- Frontend: 20250109.2
Debian Frigate user has granted access to GPU.
