### DISCUSSION TITLE
[Support]: frigate.db-wal file is very large

### DISCUSSION THREAD

**Discussion by mpeter50** [blakeblackshear/frigate#16269] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

The `frigate.db-wal` file is very large, it takes up 1,6 GB. frigate.db is 10,9 MB in comparison, and frigate.db-shm is 3,3 MB.

### Steps to reproduce

Steps to reproduce are unknown beyond checking the configuration directory.

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  enabled: false

tls:
  enabled: false

auth:
  session_length: 604800
  refresh_time: 345600

detectors:
  cpu1:
    type: cpu
    num_threads: 1

birdseye:
  enabled: true
  mode: motion

cameras:
  camera-1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://somedomain/0
          roles:
            - record
        - path: rtsp://somedomain/1
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true

    motion:
      mask:
      threshold: 20
      contour_area: 10
      improve_contrast: 'true'

    timestamp_style:
      effect: solid

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

timestamp_style:
  position: tr
  format: '%Y-%m-%d %H:%M:%S'
  thickness: 1

ui:
  timezone: Europe/Budapest
  time_format: 24hour
  strftime_fmt: '%Y-%m-%d %H:%M:%S'

telemetry:
  version_check: false

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
    frigate:
        image: ghcr.io/blakeblackshear/frigate:0.14.1
        restart: unless-stopped
        networks:
            - proxy
            - camera-vlan
        volumes:
            - frigate_config:/config
            - frigate_media:/media/frigate
            - frigate_cache:/tmp/cache
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        container_name: frigate
        shm_size: "64mb"
```

### Relevant Frigate log output

```shell
No log lines contain "db" or "database", or other relevant terms.
```

### Relevant go2rtc log output

```shell
The issue is not related to go2rtc
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink

### Screenshots of the Frigate UI's System metrics pages

|General|Storage|Cameras|
|-|-|-|
|![image](https://github.com/user-attachments/assets/ebe760d6-5b8d-4602-a8a8-acc3bee99e79)|![image](https://github.com/user-attachments/assets/fbaf23a0-d500-496a-8a80-d11679d2c591)|![image](https://github.com/user-attachments/assets/b33d1bc7-2de9-4cc8-95ee-6abfca16ea95)|

### Any other information that may be helpful

The service was installed with the current version about a month ago.

Another user [here](https://github.com/blakeblackshear/frigate/discussions/16172) had a similar issue, but it was not resolved.
