### DISCUSSION TITLE
[Camera Support]: Annke FCD600

### DISCUSSION THREAD

**Discussion by pointless-oops** [blakeblackshear/frigate#16264] [Camera Support]
### Describe the problem you are having

Hi, I'm trying to enable 2 way audio on all of my Annke FCD600 cameras and for some reason it's not working. Everything looks fine, as far as I know.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Firefox 134.0.1 tried also latest Google Chrome and Chromium

### Frigate config file

```yaml
mqtt:
  host: virt-homeassistant.example.com
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: admin
  stats_interval: 60

go2rtc:
  streams:
    cam00_main:
      - rtsp://admin:pass@cctv-cam00/Streaming/channels/101
      - "ffmpeg:cam00_main#audio=opus"
      - isapi://admin:pass@cctv-cam00:80/
    cam00_sub:
      - rtsp://admin:pass@cctv-cam00/Streaming/channels/102
      - "ffmpeg:cam00_sub#audio=opus"
      - isapi://admin:pass@cctv-cam00:80/
    cam01_main:
      - rtsp://admin:pass@cctv-cam01/Streaming/channels/101
      - "ffmpeg:cam01_main#audio=opus"
      - isapi://admin:pass@cctv-cam01:80/
    cam01_sub:
      - rtsp://admin:pass@cctv-cam01/Streaming/channels/102
      - "ffmpeg:cam01_sub#audio=opus"
      - isapi://admin:pass@cctv-cam01:80/
    cam02_main:
      - rtsp://admin:pass@cctv-cam02/Streaming/channels/101
      - "ffmpeg:cam02_main#audio=opus"
      - isapi://admin:pass@cctv-cam02:80/
    cam02_sub:
      - rtsp://admin:pass@cctv-cam02/Streaming/channels/102
      - "ffmpeg:cam02_sub#audio=opus"
      - isapi://admin:pass@cctv-cam02:80/
    cam03_main:
      - rtsp://admin:pass@cctv-cam03/Streaming/channels/101
      - "ffmpeg:cam03_main#audio=opus"
      - isapi://admin:pass@cctv-cam03:80/
    cam03_sub:
      - rtsp://admin:pass@cctv-cam03/Streaming/channels/102
      - "ffmpeg:cam03_sub#audio=opus"
      - isapi://admin:pass@cctv-cam03:80/
    cam04_main:
      - rtsp://admin:pass@cctv-cam04/Streaming/channels/101
      - "ffmpeg:cam04_main#audio=opus"
      - isapi://admin:pass@cctv-cam04:80/
    cam04_sub:
      - rtsp://admin:pass@cctv-cam04/Streaming/channels/102
      - "ffmpeg:cam04_sub#audio=opus"
      - isapi://admin:pass@cctv-cam04:80/
    cam05_main:
      - rtsp://admin:pass@cctv-cam05/Streaming/channels/101
      - "ffmpeg:cam05_main#audio=opus"
      - isapi://admin:pass@cctv-cam05:80/
    cam05_sub:
      - rtsp://admin:pass@cctv-cam05/Streaming/channels/102
      - "ffmpeg:cam05_sub#audio=opus"
      - isapi://admin:pass@cctv-cam05:80/

cameras:
  cam00:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam00_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam00_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam00_main
    detect:
      enabled: true
      height: 536

  cam01:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam01_main
    detect:
      enabled: true
      height: 536

  cam02:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam02_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam02_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam02_main
    detect:
      enabled: true
      height: 536
      
  cam03:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam03_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam03_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam03_main
    detect:
      enabled: true
      height: 536

  cam04:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam04_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam04_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam04_main
    detect:
      enabled: true
      height: 536

  cam05:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam05_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam05_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam05_main
    detect:
      enabled: true
      height: 536

version: 0.14
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  fps: 5

record:
  enabled: True
  sync_recordings: True
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

objects: 
  track:
    - person
    - car
```

### Relevant Frigate log output

```shell
Nothing relevant to my issue, only logging about space freeing for recording
```

### Relevant go2rtc log output

```shell
info
2025-02-01 15:14:17
streams
can't add track error="wrong media: audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
warning
2025-02-01 15:14:17
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:pass@cctv-cam00/Streaming/channels/101
info
2025-02-01 15:17:43
streams
can't add track error="wrong media: audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
warning
2025-02-01 15:17:43
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:pass@cctv-cam02/Streaming/channels/101
info
2025-02-01 15:18:24
streams
can't add track error="wrong media: audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
warning
2025-02-01 15:18:24
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:pass@cctv-cam01/Streaming/channels/101
info
2025-02-01 15:21:42
streams
can't add track error="wrong media: audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
warning
2025-02-01 15:21:42
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:pass@cctv-cam05/Streaming/channels/101
warning
2025-02-01 16:15:34
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:pass@cctv-cam03/Streaming/channels/101
info
2025-02-01 16:15:34
streams
can't add track error="wrong media: audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
```

### FFprobe output from your camera

```shell
root@a24f3f96e0f7:/opt/frigate# ffprobe rtsp://admin:pass@cctv-cam00/Streaming/channels/101
ffprobe version 4.3.7-0+deb11u1+rpt2 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt2 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55ac808ba0] max delay reached. need to consume packet
[rtsp @ 0x55ac808ba0] RTP: missed 171 packets
[h264 @ 0x55ac80cf60] cabac decode of qscale diff failed at 173 80
[h264 @ 0x55ac80cf60] error while decoding MB 173 80, bytestream -3
[h264 @ 0x55ac80cf60] concealing 4870 DC, 4870 AC, 4870 MV errors in P frame
[h264 @ 0x55ac80cf60] Increasing reorder buffer to 1
[rtsp @ 0x55ac808ba0] max delay reached. need to consume packet
[rtsp @ 0x55ac808ba0] RTP: missed 13 packets
Input #0, rtsp, from 'rtsp://admin:pass@cctv-cam00/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, progressive), 3632x1632 [SAR 1:1 DAR 227:102], 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Annke FCD600

### Screenshots of the Frigate UI's System metrics pages

![frigate](https://github.com/user-attachments/assets/e1fe0eec-5f8a-4376-8c12-1e6be5ea1352)

**Comment by hawkeye217** [comment]
For two way talk, you need to:
- Set up go2rtc with [WebRTC](https://docs.frigate.video/configuration/live#webrtc-extra-configuration).
- Ensure you access Frigate via https (may require [opening port 8971](https://docs.frigate.video/frigate/installation/#ports)).
- For the HA card, [follow the docs](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#using-2-way-audio) for the correct source.

What is the purpose of the `isapi://admin:pass@cctv-cam00:80/` lines for each camera in your go2rtc config?

**Comment by pointless-oops** [comment]
Thanks for reply.

I'm trying to use 2 way audio via UI, using valid SSL cetrificate.

Someone said to add isapi for my camera (https://github.com/blakeblackshear/frigate/discussions/15824)

**Reply by hawkeye217** [reply]
What is the audio codec set to on the camera?

See https://github.com/AlexxIT/go2rtc/issues/972#issuecomment-1967395529

**Reply by pointless-oops** [reply]
It's the same. Only volume is higher, but I think that this doesn't matter.

**Reply by pointless-oops** [reply]
I mean, sound from camera is playing in web UI, but for some reason I cannot talk through it. That's my issue.

**Reply by hawkeye217** [reply]
Do you see the microphone icon even showing up in the Frigate UI?

**Reply by pointless-oops** [reply]
Yes. When I enable it, only the loading spinner appears, and I have to refresh the page to access the camera again

**Reply by hawkeye217** [reply]
Did you set up go2rtc with [WebRTC](https://docs.frigate.video/configuration/live#webrtc-extra-configuration)?

**Reply by pointless-oops** [reply]
I think so, based on my config. Sorry, I'm kind of a newbie at this.

**Reply by hawkeye217** [reply]
No worries, we are happy to help. 

A loading spinner often indicates that there is a network connection issue, which is why I asked about setting up WebRTC. Click that link and make sure you've worked through the instructions.

**Reply by pointless-oops** [reply]
I think my WebRTC setup is correct. I changed network_mode in docker compose to host to eliminate possible issues.

**Reply by hawkeye217** [reply]
What candidates have you defined in your go2rtc config for webrtc?

**Reply by pointless-oops** [reply]
Sorry for the delayed response.
I set this option to:

```yaml
webrtc:
  candidates:
    - 10.0.10.4:8555
```
10.0.10.4 is my Frigate IP address. My cameras are on a different subnet (10.0.20.1/24), but the routing is set up correctly.
