### DISCUSSION TITLE
[Support]: USPS Car detected but labeled as Fedex Car in UI

### DISCUSSION THREAD

**Discussion by rolf-tx** [blakeblackshear/frigate#16268] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

This is on 0.15.0-RC1
USPS Car detected but labeled as Fedex Car in UI.
Uploading to Frigate+ show object Detected as USPS Car as expected.

![Screenshot 2025-02-01 at 17 52 47](https://github.com/user-attachments/assets/d13b431d-ab32-4593-8ce6-355f6c742ef3)

### Steps to reproduce

1. N/A

### Version

0.15.0-RC1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: ha.example.com
  user: frigate-mqtt
  password: xxxxx
database:
  path: /config/frigate.db


go2rtc:
  streams:
    garage:
      - rtsp://rolfcam:password@hikvision1.example.com:554/Streaming/Channels/101/
    driveway:
      - rtsp://rolfcam:password@hikvision2.example.com:554/Streaming/Channels/101/
    frontentry:
      - rtsp://rolfcam:password@hikvision3.example.com:554/Streaming/Channels/101/
    garage_sub:
      - rtsp://rolfcam:password@hikvision1.example.com:554/Streaming/Channels/102/
    driveway_sub:
      - rtsp://rolfcam:password@hikvision2.example.com:554/Streaming/Channels/102/
    frontentry_sub:
      - rtsp://rolfcam:password@hikvision3.example.com:554/Streaming/Channels/102/


cameras:
  garage:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 6
      width: 640
      height: 480
      annotation_offset: -2500
    birdseye:
      order: 2
    motion:
      mask: 0.518,0.122,0.517,0.069,0.1,0.071,0.037,0.072,0.037,0.122
    objects:
      filters:
        car:
          mask: 0,0,0,1,1,1,1,0


  driveway:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 6
      width: 640
      height: 360
      annotation_offset: -2200
    birdseye:
      order: 3
    motion:
      mask: 0.043,0.069,0.283,0.067,0.284,0.106,0.041,0.105
    zones:
      zone_driveway_pavement:
        coordinates: 
          0.036,0.999,0.117,0.585,0.192,0.442,0.225,0.296,0.544,0.262,0.602,0.298,0.726,0.293,0.85,0.399,0.842,0.473,0.989,0.783,0.991,1,0.499,1
    review:
      alerts:
        required_zones: zone_driveway_pavement


  frontentry:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/frontentry
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontentry_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 6
      width: 480
      height: 640
      annotation_offset: -2600
    motion:
      threshold: 50
      mask:
        - 0.131,0.164,0.295,0.146,0.304,0.084,0.131,0.081
        - 0,0.084,0.067,0.083,0.152,0.083,0.306,0.084,0.542,0.089,0.54,0,0.375,0,0,0
        - 0.073,0.167,0,0.155,0,0.661,0.184,0.537
    zones:
      zone_frontentry:
        coordinates: 0.423,1,0.723,0.823,0.725,0.275,0.301,0.247,0,0.964
    birdseye:
      order: 1
    review:
      alerts:
        required_zones: zone_frontentry


objects:
  track:
    - person
    - face
    - car
    - motorcycle
    - bicycle
    - amazon
    - usps
    - fedex
    - ups
    - dog
    - cat
    - package
    - waste_bin
  filters:
    person:
      min_score: 0.7
      threshold: 0.8
    face:
      min_score: 0.6
      threshold: 0.7
    car:
      min_score: 0.7
      threshold: 0.8
    motorcycle:
      min_score: 0.7
      threshold: 0.8
    bicycle:
      min_score: 0.7
      threshold: 0.8
    amazon:
      min_score: 0.6
      threshold: 0.65
    usps:
      min_score: 0.6
      threshold: 0.65
    fedex:
      min_score: 0.6
      threshold: 0.65
    ups:
      min_score: 0.6
      threshold: 0.65
    dog:
      min_score: 0.6
      threshold: 0.7
    cat:
      min_score: 0.6
      threshold: 0.7
    package:
      min_score: 0.6
      threshold: 0.7
    waste_bin:
      min_score: 0.7
      threshold: 0.8
    license_plate:
      min_score: 0.7
      threshold: 0.8

timestamp_style:
  position: tl

detectors:
  coral:
    type: edgetpu
    device: usb
#    type: openvino
#    device: GPU
#  ov_1:
#    type: openvino
#    device: GPU

model:
  path: plus://e8909389a9daa14f88cb1bd968bb2200 #TPU 320x320
#  path: plus://65fda372873dc95736a771e0b4bd10fb #320x320
#  path: plus://a3d58c394707473b7236607a0ea39d81 #640x640 slow



#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt



ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
#  hwaccel_args: preset-intel-vaapi
#  hwaccel_args: '""'

record:
  enabled: true
  retain:
    days: 15
    mode: all
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
      mode: motion
  detections:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
      mode: motion
  preview:
    quality: high

snapshots:
  enabled: true
  retain:
    default: 30

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720
  restream: true

version: 0.15-1

semantic_search:
  enabled: false
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
Homeassistant integration
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

hikvision

### Screenshots of the Frigate UI's System metrics pages

N/A
