### DISCUSSION TITLE
Confused about Clips or Events in 0.9.0-rc1

### DISCUSSION THREAD

**Discussion by flaektrem** [blakeblackshear/frigate#1626] [Ask A Question]
Anyone have this working?
No clips are stored for my cameras.
Is this right config? I´m a bit confused if i should use ```clips```  (as before) or ```events``` that´s seems to be the new thing.

```
entre:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=1&user=xxx&password=xxx
          roles:
            # - clips
            - detect
            - rtmp
            - record
    detect:
      fps: 4
      width: 2560
      height: 1920
    objects:
      track:
        - person
    motion:
      mask:    
        - 2560,805,2382,719,2443,265,2560,303
        - 2075,292,1994,807,1891,759,1965,259
    mqtt:
      enabled: true
    record:
      enabled: False
      retain_days: 2
      events:
        enabled: True
        retain:
          default: 5
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
```

**Comment by jasonpstokes** [comment]
Try this:
```
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True

cameras:
  entre:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=1&user=xxx&password=xxx
          roles:
            - detect
            - record
            - rtmp
    detect:
      fps: 4
      width: 2560
      height: 1920

    motion:
      mask:    
        - 2560,805,2382,719,2443,265,2560,303
        - 2075,292,1994,807,1891,759,1965,259

    objects:
      track:
        - person

    mqtt:
      enabled: true

    record:
      retain_days: 0
      events:
        enabled: True
        retain:
          default: 5
``` 

You may want to do detection on a low quality stream though, to save your CPU; if you have a Reolink camera your paths would look like this: 

```
cameras:
  entre:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.XXX/bcs/channel0_sub.bcs?channel=0&stream=1&user=xxx&password=xxx
          roles:
            - detect
        - path: rtmp://192.168.1.XXX/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 4
```

**Reply by flaektrem** [reply]
Clips are working with this config 
```
   record:
      enabled: True
      retain_days: 0
      events:
         enabled: True
         retain:
            default: 5
```

But this config ALSO give me constant recording from that camera. I don´t want that. I just want it to save clips just like version 0.8.4.
If I set ```enabled: False``` under record, there will be no clips, and no recordings.

**Reply by blakeblackshear** [reply]
@flaektrem what are you looking at to determine that you are getting constant recording?

**Reply by flaektrem** [reply]
@blakeblackshear I was able to watch several minutes of recording from that camera even if there was no events

**Reply by blakeblackshear** [reply]
If you don't have any errors in your logs, then you may be seeing recordings saved in case there are ongoing events associated with them. The default max_seconds for an event is 5 minutes. Frigate keeps a rolling 5 minutes of recordings to make sure it doesn't delete them when an event is ongoing. It actually worked this way in 0.8.4 too, those 5 minutes just weren't visible in the UI.

**Reply by flaektrem** [reply]
@blakeblackshear  I just read this:
[https://github.com/blakeblackshear/frigate/discussions/1502#discussioncomment-1168133](url)
I think i know how it is supposed to work now. This way it works now eats disc space a lot.

So what really happens when I set this configuration:
```
   record:
      enabled: True
      retain_days: 0
      events:
         enabled: True
         retain:
            default: 5
```

Versus this:
```
   record:
      enabled: True
      retain_days: 1
      events:
         enabled: True
         retain:
            default: 5
```
Right now I have 22 minutes of constant recording, and 1 event right in the middle of that with the first config example set. 
When does it purge?

**Reply by blakeblackshear** [reply]
t should be running every minute. Try adding this to your config:
```yaml
logger:
  default: info
  logs:
    frigate.record: debug
```
