### DISCUSSION TITLE
Double-Take face notification lag of 30+ seconds

### DISCUSSION THREAD

**Discussion by warlock00** [blakeblackshear/frigate#16271] [General Support] [answered]
### Describe the problem you are having

I get a phone notification, Person detected.
  Then if its family they come inside.
  30s+ later I get another phone notification (update) saying who it is.
  Family laughs. <shame>

In looking at MQTT Explorer:
  I get frigate/reviews type: new 
    30s+ later
  I get frigate/reviews type: end - this will have updated sub_labels

I spent days trying every option I could find. I can't find a way to make this faster :(
  Initial notification is fast.
  Gemini is fast.
  double_take is taking less than 1s most of the time.

I tried several options in Home Assistant Notification automation until I realised mqtt data was slow.
I tried:
  mqtt_off_delay: 10
  best_image_timeout: 10

Any way to reduce the 30s+ delay?

### Version

0.15.0-cea210d rc2

### What browser(s) are you using?

Google Chrome 132.0.6834.160 (Official Build) (64-bit)

### Frigate config file

```yaml
version: 0.15-1

mqtt:
  enabled: true
  host: 192.168.3.218
  user: frig
  password: hidden

go2rtc:
  streams:
    driveway_camera:
      - rtsp://admin:hidden@192.168.3.122/profile2/media.smp # H.264 1920x1080 30fps 
      #- ffmpeg:camera1#video=mjpeg
    driveway_camera_mjpeg:
      - rtsp://admin:hidden@192.168.3.122/profile8/media.smp # mjpeg 800x600 1fps for HomePage

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - cat

snapshots:
  enabled: true

motion:
  enabled: true
  threshold: 50 # default 30
  lightning_threshold: 0.8
  contour_area: 30 # default 10
  mqtt_off_delay: 10 # default 30

cameras:
  driveway_camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:hidden@192.168.3.122/profile2/media.smp # H.264 1920x1080 30fps
          input_args: preset-rtsp-restream
          roles:
            - record
        #- path: rtsp://admin:hidden@192.168.3.122/profile6/media.smp # mjpeg 800x600 5fps
        - path: rtsp://admin:hidden@192.168.3.122/profile7/media.smp # H.264 1920x1080 5fps Better for Double Take
          roles:
            - detect
    detect:
      enabled: true
      #width: 800
      #height: 600
      width: 1920
      height: 1080
      fps: 5
      annotation_offset: -1100
    zones:
      driveway_zone:
        coordinates: 0,0.382,1,0.249,1,1,0,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: driveway_zone
      detections:
        required_zones: driveway_zone
    motion:
      mask: 0,0,1,0,1,0.246,0,0.379
    objects:
      filters:
        car:
          mask: 0,0.425,0.263,0.408,0.369,1,0,1
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 600 # do i need?
    best_image_timeout: 10 # default 60
    webui_url: "http://192.168.3.122"

record:
  enabled: true
  retain:
    days: 20
    mode: motion
  #preview:
  #  quality: medium
  alerts:
    retain:
      days: 40
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 40
    pre_capture: 5
    post_capture: 5

camera_groups:
  Front:
    order: 1
    icon: LuArrowUp
    cameras:
      - birdseye
      - driveway_camera

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai: # requires semantic_search
  enabled: true
  provider: gemini
  api_key: hidden
  model: gemini-1.5-flash

notifications: # browser notifications
  enabled: true
  email: hidden

logger:
  default: info # default info
  logs:
    frigate.mqtt: debug
    frigate.object_detection: debug
```

### Relevant Frigate log output

```shell
2025-02-02 17:40:42.370510293  [INFO] Preparing Frigate...
2025-02-02 17:40:42.426560852  [INFO] Starting Frigate...
2025-02-02 17:40:43.975957201  [2025-02-02 17:40:43] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-02-02 17:40:44.013425649  [2025-02-02 17:40:43] frigate.util.config            INFO    : frigate config does not need migration...
2025-02-02 17:40:44.144898286  [2025-02-02 17:40:44] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2025-02-02 17:40:44.150731363  [2025-02-02 17:40:44] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
2025-02-02 17:40:44.152631650  [2025-02-02 17:40:44] peewee_migrate.logs            INFO    : Starting migrations
2025-02-02 17:40:44.185272047  [2025-02-02 17:40:44] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-02-02 17:40:44.185395270  [2025-02-02 17:40:44] frigate.app                    INFO    : Recording process started: 497
2025-02-02 17:40:44.185397654  [2025-02-02 17:40:44] frigate.app                    INFO    : Review process started: 503
2025-02-02 17:40:44.187300339  [2025-02-02 17:40:44] frigate.app                    INFO    : go2rtc process pid: 97
2025-02-02 17:40:44.196805517  [2025-02-02 17:40:44] detector.ov                    INFO    : Starting detection process: 513
2025-02-02 17:40:44.198178144  [2025-02-02 17:40:44] frigate.app                    INFO    : Embedding process started: 515
2025-02-02 17:40:44.211714740  [2025-02-02 17:40:44] frigate.app                    INFO    : Output process started: 538
2025-02-02 17:40:44.246602542  [2025-02-02 17:40:44] frigate.app                    INFO    : Camera processor started for driveway_camera: 580
2025-02-02 17:40:44.254612160  [2025-02-02 17:40:44] frigate.app                    INFO    : Capture process started for driveway_camera: 582
2025-02-02 17:40:44.746740759  [2025-02-02 17:40:44] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-02-02 17:40:44.817064973  [2025-02-02 17:40:44] frigate.api.fastapi_app        INFO    : FastAPI started
2025-02-02 18:00:00.372305799  [2025-02-02 18:00:00] frigate.comms.dispatcher       INFO    : Setting motion threshold for driveway_camera: 50
2025-02-02 18:00:00.374541761  [2025-02-02 18:00:00] frigate.comms.dispatcher       INFO    : Setting motion contour area for driveway_camera: 30
```

### Relevant go2rtc log output

```shell
2025-02-02 17:40:42.369782272  [INFO] Preparing new go2rtc config...
2025-02-02 17:40:42.742626129  [INFO] Starting go2rtc...
2025-02-02 17:40:42.822700482  17:40:42.822 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-02-02 17:40:42.822704298  17:40:42.822 INF config path=/dev/shm/go2rtc.yaml
2025-02-02 17:40:42.822944937  17:40:42.822 INF [rtsp] listen addr=:8554
2025-02-02 17:40:42.823023959  17:40:42.822 INF [webrtc] listen addr=:8555/tcp
2025-02-02 17:40:42.823026035  17:40:42.822 INF [api] listen addr=:1984
2025-02-02 17:40:52.371022115  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:hidden@192.168.3.122/profile2/media.smp':
  Metadata:
    title           : Media Presentation
    comment         : samsung
  Duration: N/A, start: -0.412000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 30 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
  Stream #0:2: Data: none

[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":1920,"height":1080,"avg_frame_rate":"0/0"},{"codec_long_name":"PCM mu-law / G.711 mu-law","avg_frame_rate":"0/0","bit_rate":"64000"},{"avg_frame_rate":"0/0"}]}},{"return_code":1,"stderr":"","stdout":""}]
```

### Frigate stats

```json
{"cameras":{"driveway_camera":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":580,"capture_pid":582,"ffmpeg_pid":590,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"ov":{"inference_speed":7.29,"detection_start":0.0,"pid":513}},"detection_fps":0.0,"gpu_usages":{"intel-vaapi":{"gpu":"0.42%","mem":"-%"}},"cpu_usages":{"frigate.full_system":{"cpu":"2.0","mem":"18.8"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"85":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"86":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"93":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"97":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"108":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"109":{"cpu":"0.7","cpu_average":"1","mem":"0.6","cmdline":"python3 -u -m frigate"},"129":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"168":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"169":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"170":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"171":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"172":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"305":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"497":{"cpu":"0.2","cpu_average":"0","mem":"0.3","cmdline":"frigate.recording_manager"},"503":{"cpu":"0.1","cpu_average":"0","mem":"0.3","cmdline":"frigate.review_segment_manager"},"513":{"cpu":"0.0","cpu_average":"0","mem":"0.5","cmdline":"frigate.detector.ov  "},"515":{"cpu":"0.1","cpu_average":"0","mem":"1.9","cmdline":"frigate.embeddings_manager"},"538":{"cpu":"0.3","cpu_average":"0","mem":"0.3","cmdline":"frigate.output       "},"553":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"565":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"580":{"cpu":"0.6","cpu_average":"0","mem":"0.3","cmdline":"frigate.process:driveway_camera"},"582":{"cpu":"1.1","cpu_average":"1","mem":"0.3","cmdline":"frigate.capture:driveway_camera"},"590":{"cpu":"2.3","cpu_average":"2","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.3.122/profile7/media.smp -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"597":{"cpu":"1.4","cpu_average":"1","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@192.168.3.122/profile2/media.smp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/driveway_camera@%Y%m%d%H%M%S%z.mp4"},"2473":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash"},"4356":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"4440":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":1610,"version":"0.15.0-cea210d","latest_version":"0.14.1","storage":{"/media/frigate/recordings":{"total":3804512.0,"used":105386.5,"free":3696815.1,"mount_type":"btrfs"},"/media/frigate/clips":{"total":3804512.0,"used":105386.5,"free":3696815.1,"mount_type":"btrfs"},"/tmp/cache":{"total":953.7,"used":3.5,"free":950.2,"mount_type":"tmpfs"},"/dev/shm":{"total":128.0,"used":72.6,"free":55.4,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1738490854},"processes":{"recording":{"pid":497},"review_segment":{"pid":503},"go2rtc":{"pid":97},"embeddings":{"pid":515}}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always # unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2 
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Volume1/cont/frigate/config:/config
      - /Volume1/Surveillance/Frigate:/media/frigate
      - /Volume1/certs/live/hidden.duckdns.org:/etc/letsencrypt/live/frigate:ro
      - /Volume1/certs/archive/hidden.duckdns.org:/etc/letsencrypt/archive/hidden.duckdns.org:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully. 
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - 1984:1984 # go2rtc
    environment:
      FRIGATE_RTSP_PASSWORD: "hidden"
    extra_hosts:
      - "hidden.duckdns.org:192.168.3.218"
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Samsung SNV-L6083R

### Screenshots of the Frigate UI's System metrics pages

<img width="1895" alt="image" src="https://github.com/user-attachments/assets/e5094a27-5b02-4874-b112-51bb35deb89e" />

### Any other information that may be helpful

GPU Hardware
vainfo: VA-API version: 1.22 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ()
vainfo: Supported profile and entrypoints
VAProfileNone : VAEntrypointVideoProc
VAProfileNone : VAEntrypointStats
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Simple : VAEntrypointEncSlice
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointFEI
VAProfileH264Main : VAEntrypointEncSliceLP
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSlice
VAProfileH264High : VAEntrypointFEI
VAProfileH264High : VAEntrypointEncSliceLP
VAProfileVC1Simple : VAEntrypointVLD
VAProfileVC1Main : VAEntrypointVLD
VAProfileVC1Advanced : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointEncPicture
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264ConstrainedBaseline: VAEntrypointFEI
VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
VAProfileVP8Version0_3 : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointFEI
VAProfileHEVCMain : VAEntrypointEncSliceLP
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileHEVCMain10 : VAEntrypointEncSlice
VAProfileHEVCMain10 : VAEntrypointEncSliceLP
VAProfileVP9Profile0 : VAEntrypointVLD
VAProfileVP9Profile0 : VAEntrypointEncSliceLP
VAProfileVP9Profile1 : VAEntrypointVLD
VAProfileVP9Profile1 : VAEntrypointEncSliceLP
VAProfileVP9Profile2 : VAEntrypointVLD
VAProfileVP9Profile2 : VAEntrypointEncSliceLP
VAProfileVP9Profile3 : VAEntrypointVLD
VAProfileVP9Profile3 : VAEntrypointEncSliceLP
VAProfileHEVCMain12 : VAEntrypointVLD
VAProfileHEVCMain12 : VAEntrypointEncSlice
VAProfileHEVCMain422_10 : VAEntrypointVLD
VAProfileHEVCMain422_10 : VAEntrypointEncSlice
VAProfileHEVCMain422_12 : VAEntrypointVLD
VAProfileHEVCMain422_12 : VAEntrypointEncSlice
VAProfileHEVCMain444 : VAEntrypointVLD
VAProfileHEVCMain444 : VAEntrypointEncSliceLP
VAProfileHEVCMain444_10 : VAEntrypointVLD
VAProfileHEVCMain444_10 : VAEntrypointEncSliceLP
VAProfileHEVCMain444_12 : VAEntrypointVLD
VAProfileHEVCSccMain : VAEntrypointVLD
VAProfileHEVCSccMain : VAEntrypointEncSliceLP
VAProfileHEVCSccMain10 : VAEntrypointVLD
VAProfileHEVCSccMain10 : VAEntrypointEncSliceLP
VAProfileHEVCSccMain444 : VAEntrypointVLD
VAProfileHEVCSccMain444 : VAEntrypointEncSliceLP
VAProfileAV1Profile0 : VAEntrypointVLD
VAProfileHEVCSccMain444_10 : VAEntrypointVLD
VAProfileHEVCSccMain444_10 : VAEntrypointEncSliceLP
