### DISCUSSION TITLE
[Detector Support]: Updating embedded ROCm libraries

### DISCUSSION THREAD

**Discussion by WhiteWolf84** [blakeblackshear/frigate#16275] [Detector Support] [answered]
### Describe the problem you are having

Hi,

there is a way to update the ROCm libraries of the image? I've seen places where I can set the version in the docker/rocm folder but I don't know how to build the image.

There is a more simple way?

Thanks for your help.

### Version

0.15 rc2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxxxxxxxxxxxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: xxxxxxxxxxxx
tls:
  enabled: true


auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.18.0.0/16
record:
  enabled: true
  retain:
    days: 15
    mode: all
  alerts:
    retain:
      days: 30
      mode: active_objects
  detections:
    retain:
      days: 30
      mode: active_objects
go2rtc:
  streams:
    retro:
      - xxxxxxxxxxxxx
    retro_sub:
      - xxxxxxxxxxxxx
    balcone:
      - xxxxxxxxxxxxxxx
    balcone_sub:
      - xxxxxxxxxxxx
    ingresso:
      - xxxx
    ingresso_sub:
      - rxxxxxx
    laterale:
      - xxxxx
    laterale_sub:
      - xxxxxxx
cameras:
  retro:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/retro
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        # - path: rtsp://127.0.0.1:8554/retro_sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    motion:
      mask: 0,0,0,0.273,0.336,0.032,0.337,0.001
    zones:
      Giardino:
        coordinates: 
          0,0.724,0.219,0.479,0.472,0.257,0.667,0.401,0.777,0.248,0.95,0.366,0.882,0.685,0.773,0.999,0.002,1
        inertia: 3
        loitering_time: 0
        objects: person
 
    review:
      alerts:
        required_zones: Giardino
      detections:
        required_zones:
          - Giardino
 
  balcone:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/balcone
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        # - path: rtsp://127.0.0.1:8554/balcone_sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    motion:
      mask: 0.684,0.035,0.686,0.082,0.986,0.081,0.984,0.038
    zones:
      Retro:
        coordinates: 0.041,0.541,0.077,0.536,0.279,0.879,0.048,0.963
        loitering_time: 0
        objects: person
        inertia: 3
      Fronte:
        coordinates: 
          0.047,0.965,0.282,0.879,0.445,0.803,0.67,0.675,0.762,0.608,0.938,0.637,0.929,0.997,0.046,0.998
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones:
          - Retro
          - Fronte
      detections:
        required_zones:
          - Retro
          - Fronte
  ingresso:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/ingresso
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        # - path: rtsp://127.0.0.1:8554/ingresso_sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    motion:
      mask: 0.674,0.037,0.671,0.09,0.981,0.091,0.98,0.046
    zones:
      Ingresso:
        coordinates: 
          0.076,0.27,0.238,0.236,0.421,0.227,0.545,0.374,0.747,0.647,0.98,0.997,0.165,0.998,0.118,0.729,0.093,0.482
        loitering_time: 0
        inertia: 3
        objects: person
 
    review:
      alerts:
        required_zones: Ingresso
      detections:
        required_zones:
          - Ingresso
 
  laterale:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/laterale
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        # - path: rtsp://127.0.0.1:8554/laterale_sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    motion:
      mask: 0.593,0.002,0.593,0.031,0.894,0.036,0.894,0.001
    zones:
      Fronte:
        coordinates: 0.131,0.168,0.321,0.137,0.284,0.092,0.134,0.106
        loitering_time: 0
        objects: person
        inertia: 3
      Laterale:
        coordinates: 
          0.13,0.168,0.321,0.138,0.635,0.492,0.995,0.998,0.194,0.999,0.149,0.743,0.131,0.505
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - Fronte
          - Laterale
      detections:
        required_zones:
          - Fronte
          - Laterale
# detectors:
#   ov1:
#     type: openvino
#     device: CPU
#   ov2:
#     type: openvino
#     device: CPU
# model:
#   model_type: yolonas
#   width: 320 # <--- should match whatever was set in notebook
#   height: 320 # <--- should match whatever was set in notebook
#   input_tensor: nchw
#   input_pixel_format: bgr
#   path: /config/yolo_nas_s.onnx
#   labelmap_path: /labelmap/coco-80.txt

# detectors:
#   ov1:
#     type: openvino
#     device: CPU
#   ov2:
#     type: openvino
#     device: CPU
# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   path: /openvino-model/ssdlite_mobilenet_v2.xml
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detectors:
  rocm:
    type: rocm
model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

# detectors:
#   onnx:
#     type: onnx

# model:
#   model_type: yolonas
#   width: 320 # <--- should match whatever was set in notebook
#   height: 320 # <--- should match whatever was set in notebook
#   input_pixel_format: bgr
#   input_tensor: nchw
#   path: /config/yolo_nas_s.onnx
#   labelmap_path: /labelmap/coco-80.txt
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2-rocm
    shm_size: "2000mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri
      - /dev/kfd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/bruno/Documenti/frigate/config:/config
      - /home/bruno/Documenti/frigate/storage:/media/frigate
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
nothing
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

nothing
