### DISCUSSION TITLE
Is a "title bar" feasible, somewhere in the UI?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#16274] [Ask A Question] [answered]
Hello all

- Might it be useful to have a title bar or some form of free-form persistent text entry box visible somewhere within the UI? 
- Could it be done via mouse-over comment?
- Could it live in the bottom status bar?

![image](https://github.com/user-attachments/assets/eaed6c8f-84ab-489d-bfea-7cf4894aabff)

- Perhaps the text could be stripped from the config.yaml:

```
...
ui:
  title: "FRIGATE CUSTOM CONFIG with alternative go2RTC"
  time_format: 24hour

mqtt:
  enabled: false
...
```

For example, if people are running more than one Frigate Instance, or if they have competing Frigate yamls and want to keep track of which one's in use at any given time.
