### DISCUSSION TITLE
[Config Support]: Every detection is gettin label "person"

### DISCUSSION THREAD

**Discussion by bib2** [blakeblackshear/frigate#16283] [Config Support] [answered]
### Describe the problem you are having

Hi, i want to detect many things, including cats, dogs and so on. But every detection is labeld with "person". Even cats are labeld so. With over 90%...

Any idea where i can look at to find the problem?

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: false



ffmpeg:
  hwaccel_args: preset-vaapi

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 7

review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person

cameras:
  eingang_haustuer:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.xxx.xx:xxx/cam/realmonitor?channel=1&subtype=2
          # input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.xxx.xx:xxx/cam/realmonitor?channel=1&subtype=0
          roles:
            - record   
    detect:
      width: 1088
      height: 1920
      fps: 5


    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.613,0.039,0.609,0.063,0.963,0.066,0.968,0.041
    zones:
      all:
        coordinates: 0,0,0,1,1,1,1,0
        loitering_time: 0
    objects: {}



    
  sprechanlage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.xxx.xx:xxx/live/ch00_0
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    review:
      alerts:
        required_zones:
          - homezone
      detections:
        required_zones:
          - homezone
    zones:
      homezone:
        coordinates: 0.298,0.493,0.986,0.615,0.99,0.991,0.008,0.996,0.004,0.012,0.313,0.007
        loitering_time: 0
detectors:
  ov:
    type: openvino
    device: GPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


ui:
  time_format: 24hour
  strftime_fmt: '%d/%m/%Y %H:%M'

version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuCodepen
    cameras: birdseye
```

### Relevant Frigate log output

```shell
...
```

### Relevant go2rtc log output

```shell
...
```

### Operating system

Proxmox

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
proxmox helper file website - standard
```

### Object Detector

CPU (no coral)

**Comment by halabut69** [comment]
SSDLite_Mobilenet prioritises speed over accuracy. Try openvino with the YoloNAS model, to see if it is a model issue.
You can use the notebook here to download the model: https://docs.frigate.video/configuration/object_detectors/#openvino-detector
But due to errors with the download URL, you need to use a workaround to get it to download correctly - see here: https://github.com/blakeblackshear/frigate/discussions/15872

**Comment by bib2** [comment]
I don´t erxactly understand what to do...

Do i have to go to my docker container and open a cli and enter the pip install command explained in your link to #15872?

Do i have to download the yolo nas manually and put it to the openvino-folder?

**Comment by hawkeye217** [comment, marked as answer]
You need to add objects to track to the `objects` section in your config. 

```
objects:
  track:
    - person
    - car
    - ...
```

https://docs.frigate.video/configuration/objects

**Comment by bib2** [comment]
I already have this:

```
 review:
   alerts:
     labels:
       - car
       - cat
       - dog
       - person
```

Is this not necessary? Should i remove that and only put objects: into my config file?
