### DISCUSSION TITLE
[Support]: Database issue? (semantic search issues)

### DISCUSSION THREAD

**Discussion by matknowles** [blakeblackshear/frigate#16284] [General Support]
### Describe the problem you are having

Hello, I seem to be having issues with semantic search. I've pretty much left my frigate install ticking away and occaisonally checking the explore tab for things over a few weeks, but yesterday I tried searching for something (a fox) and it returned no results. Fair enough perhaps, but I then noticed that _any_ search query was returning no tracked objects found. I tried to enable reindex: true in config and restart to see if that would fix it, but it stayed stuck on starting up for over 18 hours (hangs on Starting up... Thumbnails embedded:0 Descriptions embedded:0 Tracked objects processed:0 / 384465), so I figure something's gone wrong. If I put reindex:false, I can at least get see all my objects again (335694 cars, 40498 people, 3399 waste bins, 1580 bicycles, 1535 dogs, 712 birds, etc etc...) database is 4.5GiB. I assumed at first it might just be because the database is so big, but it sticking on starting up after so long I assume something's wrong.

Was initially on 0.15b6 but have tried updating to rc2, same issue. In system metrics I can see embeddings taking up 1454.7% (otherwise CPU 9%, GPU 15%) so it seems to be doing something

### Version

0.15.0-cea210d

### Frigate config file

```yaml
N/A
```

### Relevant Frigate log output

```shell
no errors mentioned, just says 2025-02-03 08:01:43
Tag
frigate.embeddings.embeddings
Message
Indexing tracked object embeddings...
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2-rocm # Use the specific Frigate version
    shm_size: 1250mb # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # PCIe Coral
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/matthew/Frigate/Config:/config
      - /mnt/FrigateMedia:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 1984:1984
      - 8971:8971
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: password
      TZ: Europe/London # Set the timezone
      PLUS_API_KEY: key
      LIBVA_DRIVER_NAME: radeonsi
networks: {}
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

N/A
