### DISCUSSION TITLE
[Support]: detections have no clips

### DISCUSSION THREAD

**Discussion by intra-au** [blakeblackshear/frigate#16287] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

detections are saved but can't be retrieved via GET /api/events/<id>/clip.mp4 endpoint.
I've done some research and events have has_clip database field set as 0, I've manually updated has_clip to 1 and sure enough I could download clip.mp4 via the endpoint.

This only happens to event not within zones. e.g. if it happens within any zone, event is marked as has_clip=1
in my case cars on the road are saved as detections and have has_clip=0, but pedestrians that walk into a zone, e.g. driveway raise an alert and have has_clip=1.

Relevant debug log below specifically shows that has_clip supplied as False 

### Steps to reproduce

1. not sure, use the same config?
2.
3.
...

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
logger:
  # Optional: default log level (default: shown below)
  default: info

mqtt:
  enabled: true
  host: 192.168.x.x
  port: 1883
  topic_prefix: frigate
  client_id: xxx
  user: xxx
  password: xxx

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    cam_front_door:
      - rtsp://admin:xxx@192.168.x.x:554/Streaming/Channels/101 # <- stream which supports video & aac audio.
      - ffmpeg:cam_front_door#audio=opus   # <- copy of the stream which transcodes audio to opus for webrtc
    cam_front_door_sub:
      - rtsp://admin:xxx@192.168.x.x:554/Streaming/Channels/102 # <- stream which supports video & aac audio.
      - ffmpeg:cam_front_door_sub#audio=opus   # <- copy of the stream which transcodes audio to opus for webrtc
    cam_driveway:
      - rtsp://admin:xxx@192.168.x.x:554/Streaming/Channels/101 # <- stream which supports video & aac audio.
      - ffmpeg:cam_driveway#audio=opus   # <- copy of the stream which transcodes audio to opus for webrtc
    cam_driveway_sub:
      - rtsp://admin:xxx@192.168.x.x:554/Streaming/Channels/102 # <- stream which supports video & aac audio.
      - ffmpeg:cam_driveway_sub#audio=opus   # <- copy of the stream which transcodes audio to opus for webrtc

live:
  stream_name: camera_name
  height: 720
  quality: 5

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - boat

review:
  alerts:
    labels:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - boat

  detections:
    labels:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - boat

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 10
    mode: active_objects
  preview:
    quality: medium
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - boat

    retain:
      default: 10
      mode: active_objects
      objects:
        person: 30
        car: 7
        bicycle: 7
        motorcycle: 7
        bus: 7
        boat: 7

snapshots:
  enabled: true
  bounding_box: false
  crop: false
  retain:
    default: 10

cameras:
  cam_front_door: # 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam_front_door
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    motion:
      mask:
        - 0.01,0.008,0.278,0.014,0.277,0.067,0.009,0.066
        - 0.417,0.007,0.417,0.082,0.595,0.119,0.705,0.161,0.866,0.233,0.998,0.878,0.998,0
    zones:
      front_door:
        coordinates: 
          0.007,0.131,0.367,0.024,0.415,0.093,0.622,0.138,0.864,0.244,0.992,0.894,0.355,0.996,0.002,0.998
        inertia: 3
        loitering_time: 0

  cam_driveway: # 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam_driveway
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi

    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    zones:
      driveway:
        coordinates: 0.548,0.326,0.794,0.312,0.846,0.338,0.881,0.692,0.85,0.73
        loitering_time: 2
        inertia: 3
        objects:
          - person
          - car
          - bicycle
          - motorcycle
      lawn:
        coordinates: 
          0,0.449,0.245,0.386,0.588,0.341,0.873,0.712,0.708,0.78,0.715,1,0.578,1,0.547,0.996,0,0.997
        loitering_time: 1
        objects: person
        inertia: 3
      mailbox:
        coordinates: 0.447,0.235,0.574,0.23,0.574,0.339,0.45,0.359
        loitering_time: 3
        inertia: 3
        objects:
          - person
          - motorcycle
          - bicycle
    review:
      alerts:
        required_zones:
          - driveway
          - lawn
          - mailbox
    motion:
      mask:
        - 0.86,0,0.845,0.314,0.878,0.66,0.905,0.859,0.906,0.993,1,1,1,0
        - 0,0,0,0.088,0.855,0.07,0.861,0
        - 0.299,1,0.286,0.818,0.442,0.828,0.514,1
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    hostname: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "1000mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
2025-02-03 10:24:09.560389695  [2025-02-03 10:24:09] peewee                         DEBUG   : ('INSERT INTO "event" ("id", "label", "camera", "start_time", "end_time", "zones", "thumbnail", "has_clip", "has_snapshot", "retain_indefinitely",                                                                              "ratio", "model_hash", "detector_type", "model_type", "data") VALUES (?, ?, ?, ?, ?, json(?), ?, ?, ?, ?, ?, ?, ?, ?, json(?)) ON CONFLICT ("id") DO UPDATE SET "id" = ?, "label" = ?, "camera" = ?, "start_time" = ?, "end_time" = ?, "zones"                                                                              = json(?), "thumbnail" = ?, "has_clip" = ?, "has_snapshot" = ?, "model_hash" = ?, "model_type" = ?, "detector_type" = ?, "data" = json(?)', ['1738578246.158965-bqyrmb', 'car', 'cam_driveway', 1738578241.158965, 1738578254.300003, '[]', '/9jkWsxxx-snip-'  False, True, False, 1.0, '4547ad7f32a72bb36c3db0ef88a4a7f3', 'openvino', <ModelTypeEnum.ssd: -- snip --

This lines show select + error 404 from nginx
2025-02-03 10:31:02.281410411  [2025-02-03 10:31:02] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."label", "t1"."sub_label", "t1"."camera", "t1"."start_time", "t1"."end_time", "t1"."top_score", "t1"."score", "t1"."false_positive", "t1"."zones", "t1"."thumbnail", "t1"."has_clip", "t1"."has_snapshot", "t1"."region", "t1"."box", "t1"."area", "t1"."retain_indefinitely", "t1"."ratio", "t1"."plus_id", "t1"."model_hash", "t1"."detector_type", "t1"."model_type", "t1"."data" FROM "event" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?', ['1738578246.158965-bqyrmb', 1, 0])
2025-02-03 10:31:02.282329375  192.168.0.252 - - [03/Feb/2025:10:31:02 +0000] "GET /api/events/1738578246.158965-bqyrmb/clip.mp4 HTTP/1.1" 404 49 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" "192.168.xxx.xxx"
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision

### Screenshots of the Frigate UI's System metrics pages

not relevant

**Comment by hawkeye217** [comment]
This is not a bug. 

This is easier to understand in Frigate 0.15. Since you've specified a record retain mode as `active_objects` and have some `required_zones`, the `has_clip` flag will only be set for a subset of your tracked objects. 

What specifically are you trying to accomplish?

**Reply by intra-au** [reply]
I'm getting everything I need currently, e.g. keeping segments where the object was active, alerts for some areas and detections for other areas. I can see all cars and pedestrians on road within detections, however I'm unable to download clips with home assistant.

Not sure I understand it correctly, if the event (detection) has a clip, it's downloadable if I manually update database, but frigate insists that it doesn't have a clip, that smells like a bug to me :)

**Reply by hawkeye217** [reply]
As I mentioned, you have `required_zones` set. This is why `has_clip` is true only for objects in those zones.

**Reply by NickM-27** [reply]
And like Josh already said, the config has been refactored in 0.15 to make this more straightforward. It is not a bug, it is working as was expected in 0.14.

**Reply by intra-au** [reply]
I do have required_zones set, but only for the alerts. How I can keep detections as clips with my configuration?

**Reply by hawkeye217** [reply, marked as answer]
You can set some zones as required for detections.

```
    review:
      alerts:
        required_zones:
          - driveway
          - lawn
          - mailbox
      detections:
        required_zones:
          - driveway
          - lawn
          - mailbox
          - another_zone
```
