### DISCUSSION TITLE
[Support]:  Crash every few days since 0.14.0/1, power cycle required to recover

### DISCUSSION THREAD

**Discussion by JuliusFruitfly** [blakeblackshear/frigate#16288] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Since upgrade to 0.14.0/1 Frigate will crash every 3 - 5 days. Too many errors in the log for me to identify a root cause. A power cycle is required to recover as the coral TPU is eventually lost. 

Note: the camera 'frigate_hall' is the only one one on WiFi.

Help!

[ccab4aaf_frigate_2025-02-03T11-04-43.232Z.log](https://github.com/user-attachments/files/18641411/ccab4aaf_frigate_2025-02-03T11-04-43.232Z.log)

### Steps to reproduce

1.
2.
3.
...

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

all/any

### Frigate config file

```yaml
## yaml-language-server: $schema=http://hass:5000/api/config/schema.json
#
# Documentation:  https://docs.frigate.video/configuration/index
#

database:
  path: /config/frigateDb/frigate.db

mqtt:
  host: hass
  user: frigate
  password: mqpfrigate

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false
  restream: false
  mode: continuous    # or motion, objects

detect:
  enabled: true
  stationary:
    interval: 100   # nframes after object detect is re-run if no motion. 0 = default, no re-detect
    threshold: 50   # nFrames after object is treated as 'stationary'

#objects:
#  track:
#    - person
#  filters:
#    person:
#      min_area: 5000       # H*W pixels
#      max_area: 100000
record:
  enabled: true
  sync_recordings: false        # use to rebuild database from files
  retain:
    days: 20
    mode: motion    # This will retain any motion (if days>0)
  events:
    pre_capture: 5
    post_capture: 30
    retain:
      mode: motion    # This will retain the motion WHEN objects are detected
      default: 90     # days

snapshots:
  enabled: true
  clean_copy: false    # The PNG file...
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 30

timestamp_style:
  format: '%d/%m %H:%M:%S'
  position: tr

# --------------------------------------------------------------------------------

go2rtc:
  streams:
    frigate_front:
      - rtsp://user:password@192.168.100.162:88/videoSub   # H264 1280 x 720
      - ffmpeg:frigate_front#audio=aac
    frigate_hall:
      - ffmpeg:rtsp://user:password@192.168.100.161:88/videoSub#video=h264#rotate=-90

##   rtsp://user:password@192.168.100.161:88/videoMain      # H264 1920 x 1080
##   rtsp://user:password@192.168.100.161:88/videoSub       # 1280 x 720 

cameras:
  frigate_front:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.100.162:88/videoMain  # H264 1920 x 1080
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frigate_front
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
    motion:
      contour_area: 30
      mask:
        - 0,0.349,0,0,0.612,0,0.615,0.186
        - 0,0.338,0,1,0.372,1,0.274,0.741,0.304,0.7,0.123,0.315
      mqtt_off_delay: 90
      threshold: 40
      improve_contrast: 'true'
    mqtt: # snapshots sent to integration via MQTT (must be per-camera)
      enabled: true
      bounding_box: false
      crop: true
      timestamp: true
    objects:
      track:
        - person

  frigate_hall:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_hall
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record  # record lo-res videoSub stream for hall
      hwaccel_args: preset-vaapi
    motion:
      mask:
        - 0,400,0,640,32,640,32,400           # timestamp
      mqtt_off_delay: 90
    mqtt: # snapshots sent to integration via MQTT (must be per-camera)
      enabled: true
      bounding_box: false
      crop: true
      timestamp: true
    objects:
      track:
        - person

  frigate_nestcam1:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.100.165:8554/profile0
          roles:
            - record
        - path: rtsp://user:password@192.168.100.165:8554/profile1
          roles:
            - detect
      hwaccel_args: preset-vaapi
    motion:
      contour_area: 20
      mqtt_off_delay: 90
    mqtt: # snapshots sent to integration via MQTT (must be per-camera)
      enabled: true
      bounding_box: false
      crop: true
      timestamp: true

  frigate_nestcam2:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.100.166:8554/profile0
          roles:
            - record
        - path: rtsp://user:password@192.168.100.166:8554/profile1
          roles:
            - detect
      hwaccel_args: preset-vaapi
    motion:
      contour_area: 20
      mqtt_off_delay: 90
    mqtt: # snapshots sent to integration via MQTT (must be per-camera)
      enabled: true
      bounding_box: false
      crop: true
      timestamp: true

version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
?
```

### Relevant Frigate log output

```shell
attached
```

### Relevant go2rtc log output

```shell
unavailable
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Foscam

### Screenshots of the Frigate UI's System metrics pages

![sm1](https://github.com/user-attachments/assets/2d89492b-af2f-4a03-9ba9-576f03f058fe)
![sm3](https://github.com/user-attachments/assets/63e2eb5a-f93d-492c-b32e-d9601d64d6a8)
![sm2](https://github.com/user-attachments/assets/0b715ee8-c7ad-4f94-970a-016323ecc679)
