### DISCUSSION TITLE
[Detector Support]: Hailo-8L failing to load HEF file

### DISCUSSION THREAD

**Discussion by mclueppers** [blakeblackshear/frigate#16293] [Detector Support] [answered]
### Describe the problem you are having

I'm in the process of testing Frigate with Hailo-8L PCIe board attached. I'm getting errors that it's failed to initialize Hailo device: HEF can only be created from a file path (str) or a buffer (bytes)

### Version

0.15.0-rc2-h8l

### Frigate config file

```yaml
detectors:
  hailo0:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef

cameras:
  dlink932lb1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam # <----- The stream you want to use for detection
          roles:
            - detect
            - record
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -r
        - '5' # <---- adjust depending on your desired frame rate from the mjpeg image
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true

    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: ssd

version: 0.15-1

semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2-h8l
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/hailo0:/dev/hailo0
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate-nvr/config:/config
      - /opt/frigate-nvr/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "<removed>"
```

### Relevant Frigate log output

```shell
frigate  | 2025-02-03 13:45:28.465946037  [2025-02-03 13:45:28] frigate.detectors.plugins.hailo8l INFO    : Initializing Hailo device as PCIe
frigate  | 2025-02-03 13:45:28.701903063  [2025-02-03 13:45:28] frigate.app                    INFO    : Embedding process started: 402
frigate  | 2025-02-03 13:45:28.701909322  [2025-02-03 13:45:28] frigate.detectors.plugins.hailo8l INFO    : A model file already exists at /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef not downloading one.
frigate  | 2025-02-03 13:45:28.701913026  [2025-02-03 13:45:28] frigate.app                    INFO    : Output process started: 421
frigate  | 2025-02-03 13:45:28.701915693  [2025-02-03 13:45:28] frigate.app                    INFO    : Camera processor started for dlink932lb1: 436
frigate  | 2025-02-03 13:45:28.701917434  [2025-02-03 13:45:28] frigate.app                    INFO    : Capture process started for dlink932lb1: 447
frigate  | 2025-02-03 13:45:28.715322300  [2025-02-03 13:45:28] frigate.detectors.plugins.hailo8l ERROR   : Failed to initialize Hailo device: HEF can only be created from a file path (str) or a buffer (bytes)
frigate  | 2025-02-03 13:45:28.748172376  Process detector:hailo0:
frigate  | 2025-02-03 13:45:28.748177413  Traceback (most recent call last):
frigate  | 2025-02-03 13:45:28.748178673    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2025-02-03 13:45:28.748179561      self.run()
frigate  | 2025-02-03 13:45:28.748180673    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2025-02-03 13:45:28.748181506      return run(*args, **kwargs)
frigate  | 2025-02-03 13:45:28.748182635    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2025-02-03 13:45:28.748183598      self._target(*self._args, **self._kwargs)
frigate  | 2025-02-03 13:45:28.748184802    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
frigate  | 2025-02-03 13:45:28.748185950      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2025-02-03 13:45:28.748189080    File "/opt/frigate/frigate/object_detection.py", line 68, in __init__
frigate  | 2025-02-03 13:45:28.748190228      self.detect_api = create_detector(detector_config)
frigate  | 2025-02-03 13:45:28.748223932    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2025-02-03 13:45:28.748225154      return api(detector_config)
frigate  | 2025-02-03 13:45:28.748236820    File "/opt/frigate/frigate/detectors/plugins/hailo8l.py", line 74, in __init__
frigate  | 2025-02-03 13:45:28.748237802      self.hef = HEF(self.h8l_model_path)
frigate  | 2025-02-03 13:45:28.748239191    File "/usr/local/lib/python3.9/dist-packages/hailo_platform/pyhailort/pyhailort.py", line 335, in __init__
frigate  | 2025-02-03 13:45:28.748240413      raise ValueError("HEF can only be created from a file path (str) or a buffer (bytes)")
frigate  | 2025-02-03 13:45:28.748241783    File "/usr/local/lib/python3.9/dist-packages/hailo_platform/pyhailort/pyhailort.py", line 335, in __init__
frigate  | 2025-02-03 13:45:28.748243246      raise ValueError("HEF can only be created from a file path (str) or a buffer (bytes)")
frigate  | 2025-02-03 13:45:28.748255228  ValueError: HEF can only be created from a file path (str) or a buffer (bytes)
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

N/A

### Any other information that may be helpful

The app is not starting unless I remove `model.path` from the detectors section and set it into the main `model` node.
