### DISCUSSION TITLE
How do I get the tls set up for Frigate

### DISCUSSION THREAD

**Discussion by Jebarson** [blakeblackshear/frigate#16301] [Ask A Question] [answered]
I am not familiar with Linux and please guide me appropriately even if it sounds obvious to you. 

My setup runs Docker Desktop running on a Window machine. Ubuntu is the WSL OS.

I am trying to configure TLS for frigate. Based on the documentation, it seems like I should be seeing "letsencrypt" with appropriate certs set up for Frigate. However, I am not seeing one. Should I be setting up letsencrypt manually or am I missing something?

Below is how my configuration for docker compose.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:    
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: 
                - gpu
                - utility
                - compute 
                - video
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - \\wsl.localhost\Ubuntu\etc\localtime:/etc/localtime:ro
      - d:/docker/frigate/config:/config
      - d:/docker/frigate/data/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

```
