### DISCUSSION TITLE
[Camera Support]: Live view stream stops, reloads, lowers quality and has no audio

### DISCUSSION THREAD

**Discussion by 20BBrown14** [blakeblackshear/frigate#16302] [Camera Support] [answered]
### Describe the problem you are having

When I have the live view up on various devices and browsers (listed below) the live stream audio and video will pause, the video player will reload with lower quality and no audio. It happens sometimes 5 minutes after pulling up the stream sometimes 6+ hours, but always eventually. There does not seem to be any affect on recording or detection and I can always refresh the tab to get back to the usual stream. The same also happen in the Home Assistant App

**iPad** (17.7.2) using **Google Chrome** (132.0.6834.100, **Firefox** (134.1 (49636)) and **Safari** 
**Android** using **Chrome** (132.0.6834.163), **Firefox** (135.0 Build #2016070975), and **Brave** (1.74.51)

Regarding the Network question: The cameras are all POE, the host machine is wired, iPad and Android are wifi

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Listed Above

### Frigate config file

```yaml
# yaml-language-server: $schema=http://{IP}:5000/api/config/schema.json

mqtt:
  host: {IP}

auth:
  enabled: true

# logger:
  # default: debug

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  webrtc:
    candidates:
      - {IP}:8555
      - {IP}:8554
      - stun:8555
  streams:
    front_door:
      - rtsp://{FRIGATE_FRONT_DOOR_CAM_USERNAME}:{FRIGATE_FRONT_DOOR_CAM_PASSWORD}@{FRIGATE_FRONT_DOOR_CAM_IP}:554/cam/realmonitor?channel=1&subtype=0 # 0 = main, 01 = substream 
    baby_room:
      - ffmpeg:rtsp://{FRIGATE_BABY_ROOM_CAM_USERNAME}:{FRIGATE_BABY_ROOM_CAM_PASSWORD}@{FRIGATE_BABY_ROOM_CAM_IP}:554/cam/realmonitor?channel=1&subtype=0
    garage:
      - rtsp://{FRIGATE_GARAGE_CAM_USERNAME}:{FRIGATE_GARAGE_CAM_PASSWORD}@{FRIGATE_GARAGE_CAM_IP}:554/cam/realmonitor?channel=1&subtype=0

birdseye:
  enabled: true
  mode: continuous

objects:
  track:
    - person
    - cat
    - dog
    - sports ball
    - bird
    - car
    - car
    - motorcycle
    - bicycle
    - handbag
    - backpack


cameras:
  # Baby's Room
  baby_room:
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_BABY_ROOM_CAM_USERNAME}:{FRIGATE_BABY_ROOM_CAM_PASSWORD}@{FRIGATE_BABY_ROOM_CAM_IP}:554/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
            - audio
        - path: rtsp://{IP}:8554/baby_room
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: true
      min_volume: 500
      listen:
        - crying
        - crying
        - crying
        - fire_alarm
        - glass
        - chink
        - shatter
        - liquid
        - yell
        - scream
        - bark
        - speech
        - smoke_detector
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
      stationary:
        interval: 10

    record: # https://docs.frigate.video/configuration/record
      enabled: true
      retain:
        days: 90
        mode: motion
      events:
        retain:
          default: 180
          mode: active_objects
        objects:
          - person
          - cat
    snapshots:
      enabled: true
    zones:
      crib:
        coordinates: 482,148,426,376,314,348,303,263,372,139
        objects:
          - cat
      changing_table:
        coordinates: 130,97,178,214,122,291,23,165
        objects:
          - cat

    motion:
      mask:
        - 625,14,632,48,548,44,541,10

  # Garage
  garage:
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_GARAGE_CAM_USERNAME}:{FRIGATE_GARAGE_CAM_PASSWORD}@{FRIGATE_GARAGE_CAM_IP}:554/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
        - path: rtsp://{IP}:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
      stationary:
        interval: 10
    record:
      enabled: true
      retain:
        days: 90
        mode: motion
      events:
        retain:
          default: 180
          mode: active_objects
    snapshots:
      enabled: true
    motion:
      mask:
        - 638,13,635,46,442,47,437,10

  # Front doot
  front_door:
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_FRONT_DOOR_CAM_USERNAME}:{FRIGATE_FRONT_DOOR_CAM_PASSWORD}@{FRIGATE_FRONT_DOOR_CAM_IP}:554/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
        - path: rtsp://{IP}:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
      stationary:
        interval: 10
    record: # https://docs.frigate.video/configuration/record
      enabled: true
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 180
          mode: active_objects
    snapshots:
      enabled: true
    motion:
      mask:
        - 0,0.815,0.034,0.8,0.058,0.792,0.091,0.777,0.119,0.781,0.152,0.802,0.194,0.854,0.228,1,0.234,1,0,1
        - 0.25,0,0.105,0,0.128,0.158,0.45,0
        - 0,0.229,0,0,0.033,0,0.053,0.212
        - 0.966,0.025,0.981,0.092,0.859,0.092,0.848,0.021
    objects:
      filters:
        car:
          mask: 0,0,0,0.223,0.314,0.045,0.356,0.021,0.42,0
        motorcycle:
          mask:
            - 1,111,276,0,0,1,0,50
    zones:
      front_porch:
        coordinates: 425,480,157,480,131,445,260,369,184,269,364,174,550,362
        objects:
          - person
          - cat
          - dog
          - backpack
          - handbag
          - bird
      frontdoor:
        coordinates: 542,357,420,270,479,0,640,0,640,101,640,480,437,480
        objects:
          - cat
          - dog
          - person
          - handbag
          - backpack
      driveway:
        coordinates: 466,62,270,0,110,51,139,47,431,221
        objects:
          - car
          - car
          - motorcycle
          - cat
          - dog
          - person
          - bicycle
      front_yard:
        coordinates: 181,263,362,168,139,49,106,53,25,102,0,110,0,382,132,437,184,410
        objects:
          - car
          - car
          - motorcycle
          - cat
          - dog
          - person
          - sports ball
          - bird
      side_yard:
        coordinates: 257,0,473,0,464,56
        objects:
          - cat
          - dog
          - person
          - sports ball
          - bird

version: 0.14
```

### Relevant Frigate log output

```shell
2025-02-03 20:57:01.637302018  [INFO] Preparing Frigate...
2025-02-03 20:57:01.652526990  [INFO] Starting Frigate...
2025-02-03 20:57:03.628204594  [2025-02-03 20:57:03] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2025-02-03 20:57:03.628379941  [2025-02-03 20:57:03] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-02-03 20:57:03.688592451  [2025-02-03 20:57:03] frigate.util.config            INFO    : frigate config does not need migration...
2025-02-03 20:57:03.759716365  [2025-02-03 20:57:03] peewee_migrate.logs            INFO    : Starting migrations
2025-02-03 20:57:03.760903253  [2025-02-03 20:57:03] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-02-03 20:57:03.834130588  [2025-02-03 20:57:03] frigate.app                    INFO    : Recording process started: 339
2025-02-03 20:57:03.834137045  [2025-02-03 20:57:03] frigate.app                    INFO    : Recording process started: 346
2025-02-03 20:57:03.839622056  [2025-02-03 20:57:03] frigate.app                    INFO    : go2rtc process pid: 98
2025-02-03 20:57:03.896936463  [2025-02-03 20:57:03] frigate.app                    INFO    : Output process started: 370
2025-02-03 20:57:04.094970194  [2025-02-03 20:57:04] frigate.app                    INFO    : Camera processor started for baby_room: 409
2025-02-03 20:57:04.106801641  [2025-02-03 20:57:04] frigate.app                    INFO    : Camera processor started for garage: 412
2025-02-03 20:57:04.134301563  [2025-02-03 20:57:04] frigate.app                    INFO    : Camera processor started for front_door: 418
2025-02-03 20:57:04.134308842  [2025-02-03 20:57:04] frigate.app                    INFO    : Capture process started for baby_room: 429
2025-02-03 20:57:04.147004418  [2025-02-03 20:57:04] frigate.app                    INFO    : Capture process started for garage: 436
2025-02-03 20:57:04.172340440  [2025-02-03 20:57:04] frigate.app                    INFO    : Capture process started for front_door: 440
2025-02-03 20:57:04.186778092  [2025-02-03 20:57:04] frigate.app                    INFO    : Audio process started: 445
2025-02-03 20:57:06.542571466  [2025-02-03 20:57:03] detector.coral                 INFO    : Starting detection process: 368
2025-02-03 20:57:06.563653811  [2025-02-03 20:57:03] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-02-03 20:57:06.564113067  [2025-02-03 20:57:06] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Relevant go2rtc log output

```shell
2025-02-03 20:57:01.643007894  [INFO] Preparing new go2rtc config...
2025-02-03 20:57:02.124362146  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-02-03 20:57:02.181400416  [INFO] Starting go2rtc...
2025-02-03 20:57:02.346967788  20:57:02.346 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-02-03 20:57:02.347001878  20:57:02.346 INF config path=/dev/shm/go2rtc.yaml
2025-02-03 20:57:02.347819340  20:57:02.347 INF [rtsp] listen addr=:8554
2025-02-03 20:57:02.347824690  20:57:02.347 INF [api] listen addr=:1984
2025-02-03 20:57:02.348269684  20:57:02.348 INF [webrtc] listen addr=:8555
2025-02-03 20:57:11.641462481  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
I tried this command but I get `Connection refused` or `No such File or Directory`
```

### Frigate stats

```json
{"cameras":{"baby_room":{"audio_dBFS":-61.8196,"audio_rms":26.5748,"camera_fps":10.0,"capture_pid":429,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":437,"pid":409,"process_fps":10.0,"skipped_fps":0.0},"front_door":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":440,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":448,"pid":418,"process_fps":10.1,"skipped_fps":0.0},"garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":436,"detection_enabled":true,"detection_fps":0.0,"ffmpeg_pid":441,"pid":412,"process_fps":10.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"116":{"cmdline":"python3 -u -m frigate","cpu":"6.4","cpu_average":"7","mem":"4.5"},"119":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"133":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"159":{"cmdline":"nginx: worker process","cpu":"2.1","cpu_average":"1","mem":"0.1"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"160":{"cmdline":"nginx: worker process","cpu":"1.4","cpu_average":"0","mem":"0.1"},"238":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"251":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"308":{"cmdline":"bash ./run.user certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"3182":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise certsync-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"33":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"337":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.7"},"339":{"cmdline":"frigate.recording_manager","cpu":"3.7","cpu_average":"2","mem":"1.0"},"34":{"cmdline":"s6-supervise certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"346":{"cmdline":"frigate.review_segment_manager","cpu":"1.4","cpu_average":"1","mem":"0.8"},"3587":{"cmdline":"sleep 60","cpu":"0.0","cpu_average":"0","mem":"0.0"},"367":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(61)","cpu":"0.8","cpu_average":"0","mem":"0.1"},"368":{"cmdline":"frigate.detector.coral","cpu":"0.1","cpu_average":"2","mem":"0.9"},"370":{"cmdline":"frigate.output       ","cpu":"2.8","cpu_average":"3","mem":"0.8"},"379":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"384":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"389":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"394":{"cmdline":"ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"409":{"cmdline":"frigate.process:baby_room","cpu":"4.6","cpu_average":"4","mem":"1.3"},"412":{"cmdline":"frigate.process:garage","cpu":"4.5","cpu_average":"6","mem":"1.4"},"418":{"cmdline":"frigate.process:front_door","cpu":"5.1","cpu_average":"5","mem":"1.4"},"429":{"cmdline":"frigate.capture:baby_room","cpu":"2.3","cpu_average":"2","mem":"1.3"},"436":{"cmdline":"frigate.capture:garage","cpu":"2.4","cpu_average":"2","mem":"1.3"},"437":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.3:554/cam/realmonitor?channel=1&subtype=01 -r 10 -vf fps=10,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.7","cpu_average":"5","mem":"0.2"},"440":{"cmdline":"frigate.capture:front_door","cpu":"2.5","cpu_average":"2","mem":"1.3"},"441":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.4:554/cam/realmonitor?channel=1&subtype=01 -r 10 -vf fps=10,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.7","cpu_average":"5","mem":"0.2"},"445":{"cmdline":"frigate.audio_manager","cpu":"0.3","cpu_average":"0","mem":"1.3"},"448":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.2:554/cam/realmonitor?channel=1&subtype=01 -r 10 -vf fps=10,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.4","cpu_average":"6","mem":"0.2"},"45":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"450":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://{IP}:8554/baby_room -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/baby_room@%Y%m%d%H%M%S%z.mp4","cpu":"5.2","cpu_average":"5","mem":"0.2"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"465":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@10.0.0.3:554/cam/realmonitor?channel=1&subtype=0 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/f5586d52f2a7894811344ece0e220cb2","cpu":"4.6","cpu_average":"4","mem":"0.1"},"467":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://{IP}:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4","cpu":"1.8","cpu_average":"1","mem":"0.1"},"468":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -rtsp_transport tcp -timeout 5000000 -i rtsp://{IP}:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"6.5","cpu_average":"6","mem":"0.2"},"469":{"cmdline":"ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.3:554/cam/realmonitor?channel=1&subtype=01 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.0","cpu_average":"0","mem":"0.1"},"87":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"88":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"90":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"19.1","cpu_average":"17","mem":"0.2"},"frigate.full_system":{"cpu":"33.9","mem":"28.8"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":12.98,"pid":368}},"gpu_usages":{"intel-vaapi":{"gpu":"0.6%","mem":"-%"}},"processes":{"audio_detector":{"pid":445},"go2rtc":{"pid":98},"logger":{"pid":337},"recording":{"pid":339},"review_segment":{"pid":346}},"service":{"last_updated":1738638852,"latest_version":"0.14.1","storage":{"/dev/shm":{"free":252.8,"mount_type":"tmpfs","total":256.0,"used":3.2},"/media/frigate/clips":{"free":529856.0,"mount_type":"ext4","total":1320872.9,"used":723848.9},"/media/frigate/recordings":{"free":529856.0,"mount_type":"ext4","total":1320872.9,"used":723848.9},"/tmp/cache":{"free":937.4,"mount_type":"tmpfs","total":953.7,"used":16.3}},"temperatures":{},"uptime":1028,"version":"0.14.1-f4f3cfa"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW-28MM

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/3cd0a98f-771d-44e7-86dd-25fb45effeb2)
