### DISCUSSION TITLE
False positive help - hedge for a car

### DISCUSSION THREAD

**Discussion by Mwanafunzi** [blakeblackshear/frigate#16313] [Detector Support] [answered]
### Describe the problem you are having

I have a persistent problem with a hedge being detected as a car under most lighting conditions. 

I don't see an easy adjustment to help with this as the area detected is roughly car or truck sized and is exactly where I expect a real vehicle to appear. Any advice on this?

<img width="1033" alt="Screenshot 2025-02-04 at 16 43 25" src="https://github.com/user-attachments/assets/a11c39cc-368c-44d3-8cc6-28c9e89dc97e" />

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.14

cameras:
  2MainGate:
    ffmpeg:
      hwaccel_args: -hwaccel none
      inputs:
        - path: rtsp://***:***@192.168.100.31:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:***@192.168.100.31:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle

    motion:
      mask: 0.175,0.345,0.311,0.256,0.261,0,0.14,0.036
  1Road:
    ffmpeg:
      hwaccel_args: -hwaccel none
      inputs:
        - path: rtsp://***:***@192.168.100.35:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:***@192.168.100.35:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle

    zones:
      OutsideTheGate:
        coordinates: 
          0.604,0.146,0.81,0.654,0.645,0.595,0.289,0.631,0.095,0.679,0.203,0.209,0.337,0.15
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0.101,0.003,0.163,0.007,0.117,0.088,0.195,0.202,0.09,0.676,0.006,0.731,0.006,0.012
        loitering_time: 0
        inertia: 3
  3WaterTower:
    ffmpeg:
      hwaccel_args: -hwaccel none
  #    output_args:
  #      record:
  #        - -c:a
  #        - copy
      inputs:
        - path: rtsp://***:***@192.168.100.48:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:***@192.168.100.48:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    audio:
      enabled: true
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle

  4ManCave:
    ffmpeg:
      hwaccel_args: -hwaccel none
      inputs:
        - path: rtsp://***:@***@192.168.100.40:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:@***@192.168.100.40:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle



# Optional: Record configuration
# NOTE: Can be overridden at the camera level
    motion:
      threshold: 41
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0,0.245,0.103,0.3,0.133,0.509,0.133,0.717,0.116,0.782,0.083,0.851,0.059,0.863,0,0.805,0,0.714
        - 0.488,0.831,0.542,0.845,0.551,0.94,0.508,0.974,0.486,0.953,0.485,0.874
record:
  enabled: true
```

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate --restart=unless-stopped \
  --privileged --shm-size=256m \
  -v ~/frigate/config:/config \
  -v ~/frigate/media:/media/frigate \
  -v /etc/localtime:/etc/localtime:ro \
  -p 5000:5000 \
  ghcr.io/blakeblackshear/frigate:0.14.1
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker CLI

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

n/a
