### DISCUSSION TITLE
[Detector Support]: How do I configure a custom model path for coral detector?

### DISCUSSION THREAD

**Discussion by dmtroyer** [blakeblackshear/frigate#16314] [Detector Support]
### Describe the problem you are having

I am seeing conflicting documentation for setting a custom model path for a coral detector. Do I put it under detectors.coral.model.path or just model.path? Should there be an indication in the logs?

Thanks!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: /models/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    depends_on:
      - traefik
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    environment:
      - FRIGATE_RTSP_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.rule=Host(`foo.foo.com`)"
      - "traefik.http.routers.frigate.tls.certresolver=letsencrypt"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"
    networks:
      - default
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/foo/frigate/volumes/conf:/config
      - /mnt/foo/docker/frigate/volumes/media:/media/frigate
      - /mnt/foo/docker/frigate/volumes/models:/models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

n/a
