### DISCUSSION TITLE
[Support]: Alarm being triggered but can't find any correlation

### DISCUSSION THREAD

**Discussion by pbassut** [blakeblackshear/frigate#16328] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

The home assistant sensor is firing an event and triggering the alarm but when I look at frigate to see what triggered it there's nothing. It shows every other event but nothing at the time the alarm was triggered. 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/217b165b-26bb-427f-88fe-0a3f99c4a108" />
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/bcb3013c-2a17-4991-8005-5683164bb0f1" />

I'm sending myself and my wife an iOS notification with the snapshot of the detection. It works every time. Interestingly enough, this one came in without an image:
![IMG_48610A24A2EF-1](https://github.com/user-attachments/assets/fff867c3-5578-4a52-8c25-85ccb9ebe4b0)

It's 09:12 AM as I'm writing this so you can do the math for the time the notification came in.

This is not the first time this happens. I've been seeing weird behaviors after I upgraded to 0.14.1.
I'm a frigate plus user if that changes anything.

### Steps to reproduce

I'm not sure the issue is reproducible.

### Version

0.14.1

### In which browser(s) are you experiencing the issue with?

Chrome but shouldn't matter?

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate.pbassut.local:5000/api/config/schema.json

# ffmpeg:
#   hwaccel_args:
#     - -hwaccel
#     - vaapi
#     - -hwaccel_device
#     - /dev/dri/renderD128
#     - -hwaccel_output_format
#     - yuv420p

mqtt:
  host: mqtt.pbassut.local
  user: pbassut
  password: L*Q*RjQ-6


model:
  path: plus://model_id

snapshots:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  filters:
    person:
      min_score: 0.85

record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 20
      mode: motion

birdseye:
  enabled: true
  mode: continuous
  quality: 1

go2rtc:
  streams:
    fora_esquerda:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=7subtype=0#input=rtsp/udp
    fora_esquerda_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=7subtype=1#input=rtsp/udp

    fora_direita:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=8subtype=0#input=rtsp/udp
    fora_direita_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=8subtype=1#input=rtsp/udp

    frente_corredor:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=6subtype=0#input=rtsp/udp
    frente_corredor_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=6subtype=1#input=rtsp/udp

    frente:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=5subtype=0#input=rtsp/udp
    frente_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=5subtype=1#input=rtsp/udp

    garagem:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=9subtype=0#input=rtsp/udp
    garagem_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=9subtype=1#input=rtsp/udp

    area_de_servico:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=1subtype=0#input=rtsp/udp
    area_de_servico_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=1subtype=1#input=rtsp/udp

    jardim_1:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=3subtype=0#input=rtsp/udp
    jardim_1_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=3subtype=1#input=rtsp/udp

    jardim_2:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=2subtype=0#input=rtsp/udp
    jardim_2_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=2subtype=1#input=rtsp/udp

    jardim_3:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=4subtype=0#input=rtsp/udp
    jardim_3_sub:
      - rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=4subtype=1#input=rtsp/udp

    cozinha: 
      rtsp://admin:pass@10.0.0.180:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#input=rtsp/udp
    cozinha_sub: 
      rtsp://admin:pass@10.0.0.180:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#input=rtsp/udp

cameras:
############################################################################################################
  fora_esquerda:
    ui:
      order: 1
    birdseye:
      order: 1
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fora_esquerda
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=7subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fora_esquerda_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=7subtype=1
          roles:
            - detect
    motion:
      mask:
        - 960,35,960,0,793,0,792,39
    objects:
      track:
        - person
      filters:
        person:
          min_area: 1100
          max_area: 50000
          min_ratio: 0.35
          max_ratio: 0.8
    zones:
      entrada_garagem:
        coordinates: 687,480,506,300,0,306,0,480
############################################################################################################
  fora_direita:
    ui:
      order: 2
    birdseye:
      order: 2
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fora_direita
          input_args: preset-rtsp-restream
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=8subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fora_direita_sub
          input_args: preset-rtsp-restream
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=8subtype=1
          roles:
            - detect
    motion:
      mask:
        - 960,38,960,0,792,0,792,36
    objects:
      track:
        - person
      filters:
        person:
          min_area: 1300
          max_area: 50000

          min_ratio: 0.35
          max_ratio: 0.8
    zones:
      calcada:
        coordinates: 823,480,930,246,732,192,0,480
        loitering_time: 5
        filters:
          person:
            min_area: 4000
            max_area: 50000
############################################################################################################
  frente_corredor:
    ui:
      order: 3
    birdseye:
      order: 3
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frente_corredor
          input_args: preset-rtsp-restream
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=6subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frente_corredor_sub
          input_args: preset-rtsp-restream
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=6subtype=1
          roles:
            - detect
    motion:
      mask:
        - 960,33,960,0,792,0,792,35
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.2
          max_ratio: 0.8

          min_area: 1100
############################################################################################################
  frente:
    ui:
      order: 4
    birdseye:
      order: 4
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frente
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=5subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frente_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=5subtype=1
          roles:
            - detect
    # zones:
    #   entrada:
    #     coordinates: 0,121,46,117,122,143,236,74,352,79,331,240,0,240
    motion:
      mask:
        - 0.821,0.076,0.984,0.078,0.988,0.026,0.821,0.026
        - 0.725,0.129,1,0.228,1,0.347,0.724,0.233
        - 0.543,0.176,0.615,0.192,0.615,0.11,0.543,0.106
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.20
          max_ratio: 0.95

          min_area: 1100
          max_area: 60000
############################################################################################################
          mask:
            - 0.541,0.206,0.616,0.214,0.617,0.114,0.539,0.106
            - 0.721,0.242,0.723,0.117,0.998,0.197,0.998,0.368
            - 0.72,0.238,0.723,0.117,0.998,0.197,1,0.373
  garagem:
    ui:
      order: 5
    birdseye:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagem
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=9subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garagem_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=9subtype=1
          roles:
            - detect
    motion:
      mask:
        - 0.825,0,1,0,1,0.079,0.821,0.079
        - 0.629,0.878,0.611,0.749,0.704,0.741,0.688,0.879
        - 0.705,0.886,0.727,1,0.911,1,0.995,0.609,0.91,0.24,0.762,0.216,0.708,0.729
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.35
          max_ratio: 0.85

          min_area: 1100
          max_area: 60000
############################################################################################################
  area_de_servico:
    ui:
      order: 6
    birdseye:
      order: 6
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/area_de_servico
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=1subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/area_de_servico_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=1subtype=1
          roles:
            - detect
    motion:
      mask:
        - 1,0,1,0.079,0.822,0.077,0.823,0
        - 0.113,0.613,0.074,0.298,0.277,0.245,0.301,0.63
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.3
          max_ratio: 0.75

          min_area: 1100
############################################################################################################
  jardim_1:
    ui:
      order: 7
    birdseye:
      order: 7
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jardim_1
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=3subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/jardim_1_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=3subtype=1
          roles:
            - detect
    motion:
      mask:
        - 960,0,939,40,793,35,792,0
    objects:
      track:
        - person
      filters:
        person:
          max_ratio: 0.65

          min_area: 3600
          max_area: 72000
############################################################################################################
  jardim_2:
    ui:
      order: 8
    birdseye:
      order: 8
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jardim_2
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=2subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/jardim_2_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=2subtype=1
          roles:
            - detect
    # zones:
    #   area_servico:
    #     coordinates: 352,240,352,0,278,0,219,63,0,144,0,240
    motion:
      mask:
        - 960,0,960,44,793,40,793,0
        - 29,96,91,88,107,205,46,220
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.3
          max_ratio: 0.8

          min_area: 1100
          max_area: 54000
    zones:
      jardim:
        coordinates: 960,480,960,232,884,185,252,480
      jardim_meio:
        coordinates: 664,105,110,126,184,480,871,192
      jardim_area_de_servico:
        coordinates: 110,113,372,75,529,58,660,105,458,154
############################################################################################################
  jardim_3:
    ui:
      order: 9
    birdseye:
      order: 9
      width: 3840
      height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jardim_3
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=4subtype=0
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/jardim_3_sub
      # - path: rtsp://frigate:pass@10.0.0.108/cam/realmonitor?channel=4subtype=1
          roles:
            - detect
    zones:
      area_servico:
        coordinates: 352,240,352,0,278,0,219,63,0,144,0,240
    motion:
      mask:
        - 960,39,960,0,788,0,790,39
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.2
          max_ratio: 0.8

          min_area: 4000
          max_area: 40000
############################################################################################################

############################################################################################################
############################################################################################################
############################################################################################################ 
#################################### \__   __/(       )(  ___  )|\     /|###################################
####################################    ) (   | () () || (   ) || )   ( |###################################
####################################    | |   | || || || |   | || |   | |###################################
####################################    | |   | |(_)| || |   | || |   | |###################################
####################################    | |   | |   | || |   | || |   | |###################################
#################################### ___) (___| )   ( || (___) || (___) |###################################
#################################### \_______/|/     \|(_______)(_______)###################################
 ###########################################################################################################
############################################################################################################
############################################################################################################

############################################################################################################
  cozinha:
    ui:
      order: 10
    birdseye:
      order: 10
      width: 2560
      height: 1440
    ffmpeg:
      # output_args:
      #   record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

      inputs:
        - path: rtsp://127.0.0.1:8554/cozinha
      # - path: 
          # rtsp://admin:pass@10.0.0.180:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/cozinha_sub
      # - path: 
          # rtsp://admin:pass@10.0.0.180:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    zones:
      area_cozinha:
        coordinates: 189,0,640,0,640,480,0,480,0,266,195,245
      area_corredor:
        coordinates: 0,277,0,0,188,0,198,244
    motion:
      mask:
        - 619,44,604,22,445,23,445,46
    # onvif:
    #   host: 10.0.0.180
    #   port: 8000
    #   user: admin
    #   password: L2CBE555
    objects:
      track:
        - person
      filters:
        person:
          min_ratio: 0.15
          max_ratio: 0.40

          min_area: 3000
          max_area: 52000
############################################################################################################
  # cozinha_2:
  #   ffmpeg:
  #     inputs:
  #     - path: 
  #         rtsp://admin:pass@10.0.0.180:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  #       roles:
  #       - record
############################################################################################################

############################################################################################################
############################################################################################################
############################################################################################################ 
####################################_________ _______  _______ _________####################################
####################################\__   __/(  ____ \(  ____ \\__   __/####################################
####################################   ) (   | (    \/| (    \/   ) (   ####################################
####################################   | |   | (__    | (_____    | |   ####################################
####################################   | |   |  __)   (_____  )   | |   ####################################
####################################   | |   | (            ) |   | |   ####################################
####################################   | |   | (____/\/\____) |   | |   ####################################
####################################   )_(   (_______/\_______)   )_(   ####################################
############################################################################################################                                    
############################################################################################################
############################################################################################################
############################################################################################################

  # test:
  #   ffmpeg:
  #     inputs:
  #       - path: /media/frigate/recordings/2024-06-02/02/frente/09.05.mp4
  #         input_args: -re -stream_loop -1 -fflags +genpts
  #         roles:
  #           - detect
version: 0.14
camera_groups:
  Calçada:
    order: 1
    icon: LuShieldAlert
    cameras:
      - fora_direita
      - fora_esquerda
      - frente
  Fundos:
    order: 2
    icon: LuFlower2
    cameras:
      - jardim_1
      - jardim_2
      - jardim_3
  Frente:
    order: 3
    icon: LuBlinds
    cameras:
      - garagem
      - frente_corredor
      - frente
```

### docker-compose file or Docker CLI command

```yaml
I'm not using docker.
```

### Relevant Frigate log output

```shell
No logs at that time
```

### Relevant go2rtc log output

```shell
No logs at that time
```

### Operating system

Debian

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Intelbras, Imou, Hikvision

### Screenshots of the Frigate UI's System metrics pages

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/d012d105-3960-4c7e-be97-1fec27f4d818" />
