### DISCUSSION TITLE
Unable to stream WebRTC

### DISCUSSION THREAD

**Discussion by Mwanafunzi** [blakeblackshear/frigate#16336] [Config Support] [answered]
### Describe the problem you are having

I'm a bit out of my depth here. I want to make the raw footage available in a simple web display on a tablet - ultimately a grid in kiosk format.

I am connecting over tailscale.
I start docker in ' host mode'
I put this into my config file.

```
go2rtc:
  streams:
    2MainGate: rtsp://***:***@192.168.100.31:554/cam/realmonitor?channel=1&subtype=0
  webrtc:
    candidates:
      - 100.**.**.**:8555  # Frigate Server's Tailscale IP
      # need add local ip here later
      - stun:8555
```

if i go to http://100.125.82.74:1984/api/webrtc?src=2MainGate in a browser I see nothing and the browser error is "Failed to load resource: the server responded with a status of 405 (Method Not Allowed)"

```
~$ ss -tulnp | grep 8555
udp   UNCONN 0      0                                *:8555             *:*          
tcp   LISTEN 0      4096                             *:8555             *:*    

```
looks ok?

i'm not sure where to go next? Any advice appreciated.

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.14

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous

go2rtc:
  streams:
    2MainGate: rtsp://***:***@192.168.100.31:554/cam/realmonitor?channel=1&subtype=0
  webrtc:
    candidates:
      - 100.125.82.74:8555  #  Frigate Server's Tailscale IP
      # need add local ip here
      - stun:8555


cameras:
  2MainGate:
    ffmpeg:
      hwaccel_args: -hwaccel none
      inputs:
        - path: rtsp://***:***@192.168.100.31:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:***@192.168.100.31:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 960
      height: 540
      fps: 5

    objects:
      track:
        - person
        - car
        - motorcycle

    motion:
      mask: 0.175,0.345,0.311,0.256,0.261,0,0.14,0.036
  1Road:
    ffmpeg:
      hwaccel_args: -hwaccel none
      inputs:
        - path: rtsp://***:***@192.168.100.35:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:***@192.168.100.35:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle

      filters:
        car:
          mask: 0.248,0.373,0.244,0.436,0.329,0.455,0.509,0.454,0.508,0.358,0.325,0.398
        person:
          min_area: 2000  # avoid tiny people in the hedge - actually leaves

    zones:
      OutsideTheGate:
        coordinates: 
          0.604,0.146,0.81,0.654,0.645,0.595,0.289,0.631,0.095,0.679,0.203,0.209,0.337,0.15
        loitering_time: 0
        inertia: 3
      road:
        coordinates: 
          0.101,0.003,0.163,0.007,0.117,0.088,0.195,0.202,0.09,0.676,0.006,0.731,0.006,0.012
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones:
          - OutsideTheGate
          - road
      detections:
        required_zones: OutsideTheGate
  3WaterTower:
    ffmpeg:
      hwaccel_args: -hwaccel none
  #    output_args:
  #      record:
  #        - -c:a
  #        - copy
      inputs:
        - path: rtsp://***:***@192.168.100.48:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:***@192.168.100.48:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    audio:
      enabled: true
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle

  4ManCave:
    ffmpeg:
      hwaccel_args: -hwaccel none
      inputs:
        - path: rtsp://***:@***@192.168.100.40:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://***:@***@192.168.100.40:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 960
      height: 540
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle



# Optional: Record configuration
# NOTE: Can be overridden at the camera level
    motion:
      threshold: 41
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0,0.245,0.103,0.3,0.133,0.509,0.133,0.717,0.116,0.782,0.083,0.851,0.059,0.863,0,0.805,0,0.714
        - 0.488,0.831,0.542,0.845,0.551,0.94,0.508,0.974,0.486,0.953,0.485,0.874
record:
  enabled: true


camera_groups:
  BirdsEye:
    order: 1
    icon: LuActivity
    cameras: birdseye
```

### Relevant Frigate log output

```shell
nothing looking relevant
```

### Relevant go2rtc log output

```shell
docker logs frigate | grep -i "go2rtc"

s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2025-02-05 18:07:51.114618494  [INFO] Preparing new go2rtc config...
2025-02-05 18:07:51.412333782  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-02-05 18:07:51.451451431  [INFO] Starting go2rtc...
2025-02-05 18:07:51.547619902  18:07:51.547 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-02-05 18:07:51.547623540  18:07:51.547 INF config path=/dev/shm/go2rtc.yaml
2025-02-05 18:07:52.629767688  [2025-02-05 18:07:52] frigate.app                    INFO    : go2rtc process pid: 99
2025-02-05 18:08:01.106579642  [INFO] Starting go2rtc healthcheck service...

```

### Frigate stats

```json
% curl -s http://100.125.82.74:5000/api/stats | jq
{
  "cameras": {
    "1Road": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 438,
      "detection_enabled": true,
      "detection_fps": 1.3,
      "ffmpeg_pid": 5685,
      "pid": 413,
      "process_fps": 5.1,
      "skipped_fps": 0.0
    },
    "2MainGate": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 433,
      "detection_enabled": true,
      "detection_fps": 3.5,
      "ffmpeg_pid": 2080,
      "pid": 408,
      "process_fps": 4.9,
      "skipped_fps": 0.2
    },
    "3WaterTower": {
      "audio_dBFS": -73.5876,
      "audio_rms": 6.856,
      "camera_fps": 5.0,
      "capture_pid": 445,
      "detection_enabled": true,
      "detection_fps": 4.3,
      "ffmpeg_pid": 5616,
      "pid": 418,
      "process_fps": 4.6,
      "skipped_fps": 0.4
    },
    "4ManCave": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.0,
      "capture_pid": 453,
      "detection_enabled": true,
      "detection_fps": 12.0,
      "ffmpeg_pid": 462,
      "pid": 425,
      "process_fps": 5.0,
      "skipped_fps": 0.1
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "1083": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(52)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "116": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "120": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "2.3",
      "cpu_average": "2",
      "mem": "2.2"
    },
    "129": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "159": {
      "cmdline": "nginx: worker process",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "160": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "17": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "188": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "189": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "195": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "2080": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.31:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=960:540 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "4.5",
      "cpu_average": "4",
      "mem": "0.2"
    },
    "2082": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.31:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/2MainGate@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "24": {
      "cmdline": "s6-supervise certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "296": {
      "cmdline": "bash ./run.user certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise certsync-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "33": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "338": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "34": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "345": {
      "cmdline": "frigate.recording_manager",
      "cpu": "1.0",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "354": {
      "cmdline": "frigate.review_segment_manager",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.8"
    },
    "388": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(60)",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "389": {
      "cmdline": "frigate.detector.coral",
      "cpu": "36.7",
      "cpu_average": "58",
      "mem": "0.9"
    },
    "393": {
      "cmdline": "frigate.output       ",
      "cpu": "6.7",
      "cpu_average": "6",
      "mem": "0.9"
    },
    "408": {
      "cmdline": "frigate.process:2MainGate",
      "cpu": "2.8",
      "cpu_average": "4",
      "mem": "1.0"
    },
    "413": {
      "cmdline": "frigate.process:1Road",
      "cpu": "2.3",
      "cpu_average": "5",
      "mem": "1.0"
    },
    "418": {
      "cmdline": "frigate.process:3WaterTower",
      "cpu": "4.0",
      "cpu_average": "4",
      "mem": "0.9"
    },
    "425": {
      "cmdline": "frigate.process:4ManCave",
      "cpu": "6.5",
      "cpu_average": "6",
      "mem": "1.0"
    },
    "433": {
      "cmdline": "frigate.capture:2MainGate",
      "cpu": "1.0",
      "cpu_average": "1",
      "mem": "0.9"
    },
    "438": {
      "cmdline": "frigate.capture:1Road",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "445": {
      "cmdline": "frigate.capture:3WaterTower",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "45": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "453": {
      "cmdline": "frigate.capture:4ManCave",
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "0.8"
    },
    "458": {
      "cmdline": "frigate.audio_manager",
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.9"
    },
    "46": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "462": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.40:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=960:540 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "5.8",
      "cpu_average": "5",
      "mem": "0.2"
    },
    "463": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.35:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/1Road@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.4",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "482": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.40:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/4ManCave@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "484": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 960x540 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "3.6",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "489": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 960x540 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "3.8",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "494": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 960x540 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "3.9",
      "cpu_average": "3",
      "mem": "0.2"
    },
    "499": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 960x540 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "3.9",
      "cpu_average": "3",
      "mem": "0.2"
    },
    "504": {
      "cmdline": "ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "5616": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.48:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=960:540 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "5.7",
      "cpu_average": "5",
      "mem": "0.2"
    },
    "5618": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.48:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/3WaterTower@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "5619": {
      "cmdline": "ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.48:554/cam/realmonitor?channel=1&subtype=0 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "5685": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel none -user_agent FFmpeg Frigate/0.14.1-f4f3cfa -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.100.35:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=960:540 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "5.9",
      "cpu_average": "5",
      "mem": "0.2"
    },
    "6351": {
      "cmdline": "sleep 60",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "6486": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "85": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "88": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "90": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "99": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "frigate.full_system": {
      "cpu": "31.1",
      "mem": "10.0"
    }
  },
  "detection_fps": 21.1,
  "detectors": {
    "coral": {
      "detection_start": 1738780491.390523,
      "inference_speed": 27.86,
      "pid": 389
    }
  },
  "processes": {
    "audio_detector": {
      "pid": 458
    },
    "go2rtc": {
      "pid": 99
    },
    "logger": {
      "pid": 338
    },
    "recording": {
      "pid": 345
    },
    "review_segment": {
      "pid": 354
    }
  },
  "service": {
    "last_updated": 1738780491,
    "latest_version": "0.14.1",
    "storage": {
      "/dev/shm": {
        "free": 57.8,
        "mount_type": "tmpfs",
        "total": 64.0,
        "used": 6.2
      },
      "/media/frigate/clips": {
        "free": 3726.4,
        "mount_type": "ext4",
        "total": 100220.9,
        "used": 91358.5
      },
      "/media/frigate/recordings": {
        "free": 3726.4,
        "mount_type": "ext4",
        "total": 100220.9,
        "used": 91358.5
      },
      "/tmp/cache": {
        "free": 3726.4,
        "mount_type": "overlay",
        "total": 100220.9,
        "used": 91358.5
      }
    },
    "temperatures": {},
    "uptime": 1619,
    "version": "0.14.1-f4f3cfa"
  }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate --restart unless-stopped --network host \
  --device /dev/bus/usb:/dev/bus/usb \
  -v /home/stephenkemp/frigate/config:/config \
  -v /home/stephenkemp/frigate/media:/media/frigate \
  ghcr.io/blakeblackshear/frigate:stable
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1370" alt="Screenshot 2025-02-05 at 21 37 14" src="https://github.com/user-attachments/assets/cbf1a72f-aaf8-44ab-bcde-a3e536f2c56f" />

**Comment by hawkeye217** [comment]
Does `http://100.125.82.74:1984/stream.html?src=2MainGate&mode=webrtc` work?

**Reply by Mwanafunzi** [reply]
it gives no errors, no stream, just this text

webrtc/offer: streams: codecs not matched: H265, AAC => VP8, VP9, AV1, H264, OPUS, G722, PCMU, PCMA, S16B, S16L

(which reminds me, another problem is no audio!)

**Reply by NickM-27** [reply]
Try `http://100.125.82.74:1984/stream.html?video&audio&src=2MainGate&mode=webrtc`

**Reply by Mwanafunzi** [reply]
same result.
webrtc/offer: streams: codecs not matched: H265, AAC => VP8, VP9, AV1, H264, OPUS, G722, PCMU, PCMA, S16B, S16L

When I said no audio, I did not mean on the webRTC stream, because I haven't yet seen a weRTC stream :-).  I meant there's no audio on the frigate web ui or the raw recorded video.

**Reply by NickM-27** [reply]
See https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Reply by Mwanafunzi** [reply, marked as answer]
Looks like its fixed!

Thanks Hawkeye217, that error message pointed me in the right direction. I realised I need to transcode to h264. So I put this in the config
```

`go2rtc:
  streams:
    2MainGate: rtsp://*:*@192.168.100.31:554/cam/realmonitor?channel=1&subtype=0
    2MainGate_h264: ffmpeg:2MainGate#video=h264#audio=opus
  webrtc:
    listen: ":8555"
    candidates:
      - stun:stun.l.google.com:19302
      - stun:8555
      - 100.125.82.74:8555
  api:
    origins: ["*"]
    methods: ["GET", "POST", "OPTIONS"]`

```

and I can see the stream (with sound!) at
http://100.125.82.74:1984/stream.html?src=2MainGate_h264&mode=webrtc

HOWEVER. Not surprisingly, that has dramatically hit my CPU workload, I doubt if I can get it to work for all 6 camera streams on the beelink EQ14.

In another separate issue, I could not get frigate to use the GPU. Seems to be a driver/kernel version issue
