### DISCUSSION TITLE
Livestream in browser substream?

### DISCUSSION THREAD

**Discussion by ThorstenUm** [blakeblackshear/frigate#16347] [Ask A Question] [answered]
Hello everyone,

I'm mentally in the camera view, where all cameras are displayed.
Then I click on a camera and this camera is displayed in detail in the browser.
Is it possible that this live image is only displayed as a substream (detect stream)?
When I look in history, old streams are obviously shown as high quality mainstream. Isn't that the case with the live stream? Can I set somewhere so that the live view is displayed in the high-quality mainstream without affecting the recognition in the substream in the background?

My camera configuration looks like this:
```
    ffmpeg:
      hwaccel_args: auto
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.27.0.75:554/h264Preview_01_sub
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.27.0.75:554/h264Preview_01_main
          roles:
            - record
```

Greetings and have a nice day together

**Comment by hawkeye217** [comment]
You'll want to [set up go2rtc](https://docs.frigate.video/guides/configuring_go2rtc/) and just set the substream for your live view using `stream_name` directive. See the docs: https://docs.frigate.video/configuration/live/#setting-stream-for-live-ui

```
go2rtc:
  streams:
    cam_name: rtsp://....

cameras:
  cam_name:
  ....
    live:
      stream_name: cam_name
```
