### DISCUSSION TITLE
Go2rtc encoded cam goes ubavailable after days,  and solvable in frigate?

### DISCUSSION THREAD

**Discussion by borgqueenx** [blakeblackshear/frigate#16344] [Ask A Question]
To turn a camera 90 degrees, i am using a extra go2rtc config line in frigate that rotates the camera. I am then using that camera in the rest of the frigate config.
I now noted that for the third time, after days of working, the camera that is rotated shows "no frames received" and stops working. Trying to use vlc to watch the go2rtc stream also fails. However trying to watch the original non-rotated camera still works fine.
Is there perhaps a alternative to rotating?
I am using go2rtc 1.9.6.
I should note that a frigate restart solves the issue.

**Comment by hawkeye217** [comment]
In order to help we'll need to see your config and the go2rtc logs when this happens.

**Comment by borgqueenx** [comment]
here is the go2rtc config part of frigate:
```
go2rtc:
  streams:
    front-door:
      - rtsp://xxx:xxx@192.168.1.202/stream1
      - tapo://xxx@192.168.1.202
      - ffmpeg:front-door#audio=aac
    front-door-cam:
      - ffmpeg:front-door#video=h264#rotate=90
```

in the go2rtc logs (on the web page) i see nothing related to the ip address or the name of the camera when searching for it. 
But the front-door in go2rtc works fine.
front-door-cam is not working, nothing happens when i click "stream", its stuck on "loading".
its instantly fixed when i restart frigate.

**Reply by hawkeye217** [reply]
You'll want to enable go2rtc trace logs so you can discover why the rotated stream fails.

```
go2rtc:
  logs:
    exec: trace
  ...
```
