### DISCUSSION TITLE
hailort updated to 4.20

### DISCUSSION THREAD

**Discussion by clsbn** [blakeblackshear/frigate#16349] [Detector Support] [answered]
### Describe the problem you are having

The hailo driver present in the official raspberry repositories has been updated to version 4.20 while the library present in the frigate -h8l images has remained at 4.19.
In this way the container no longer starts showing a version error between the library and the driver.

### Version

frigate:df840b7-h8l

### Frigate config file

```yaml
tls:
  enabled: true

mqtt:
  enabled: true
  host: 192.168.1.12

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model_path: /config/model_cache/h8l_cache/yolov8s.hef
model:
  width: 640 ## 300
  height: 640 ## 300
  input_tensor: nhwc
  input_pixel_format: rgb ## bgr
  model_type: yolox ## null
  labelmap:
    0: person
    1: bicycle
    2: car
    3: motorcycle 
[...]
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
      #image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2-h8l
    image: ghcr.io/blakeblackshear/frigate:df840b7-h8l
    shm_size: "512MB"
    privileged: true
    devices:
      - /dev/hailo0:/dev/hailo0 # Hailo device
      - /dev/video10:/dev/video10 # Video device
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./media:/media
      - type: tmpfs # 1GB
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    ports:
      - "5000:5000" # Frigate HTTP Web UI NON AUTENTICATO
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971" # Frigate Auth Web UI
volumes:
  media:
  config:
```

### Relevant Frigate log output

```shell
frigate    | 2025-02-06 16:21:19.347197118  [2025-02-06 16:21:19] detector.hailo8l               INFO    : Starting detection process: 362
frigate    | 2025-02-06 16:21:19.348812575  [2025-02-06 16:21:19] frigate.detectors.plugins.hailo8l INFO    : Initializing Hailo device as PCIe
frigate    | 2025-02-06 16:21:19.635375523  [2025-02-06 16:21:19] frigate.app                    INFO    : Output process started: 378
frigate    | 2025-02-06 16:21:19.647323187  [HailoRT] [error] CHECK failed - Driver version (4.20.0) is different from library version (4.19.0)
frigate    | 2025-02-06 16:21:19.647505057  [HailoRT] [error] Driver version mismatch, status HAILO_INVALID_DRIVER_VERSION(76)
frigate    | 2025-02-06 16:21:19.647516298  [HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INVALID_DRIVER_VERSION(76)

[...]

frigate    | 2025-02-06 16:21:19.700141844  Process detector:hailo8l:
frigate    | 2025-02-06 16:21:19.700145955  Traceback (most recent call last):
frigate    | 2025-02-06 16:21:19.700147381    File "/usr/local/lib/python3.9/dist-packages/hailo_platform/pyhailort/pyhailort.py", line 3498, in _open_vdevice
frigate    | 2025-02-06 16:21:19.700148566      self._vdevice = _pyhailort.VDevice.create(self._params, device_ids)
frigate    | 2025-02-06 16:21:19.700149640  hailo_platform.pyhailort._pyhailort.HailoRTStatusException: 76
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

not possible because the container don't start
