### DISCUSSION TITLE
[Config Support]: incomplete list of objects in the UI - it must be another config error

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#16345] [Config Support] [answered]
### Describe the problem you are having

Hello

Throughout my config (eight cameras) I have at least these objects listed (with "cars"  added for some cameras):

```
objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder
```
but the 0.14.1-f4f3cfa UI shows these labels only:

![image](https://github.com/user-attachments/assets/caef8d79-9fc1-4afc-be52-64eefd4aebce)

and you will see that "deer" is not listed.

In contrast, my 0.15rc2 UI is complete yet  I can't spot my no-doubt-stupid error in 0.14.1 - please can you help?

(I know I read this in the discussions only the other day but ten minutes of reading through the help documentation and searching has failed to locate it - sorry)

### Version

0.14.1

### Frigate config file

```yaml
#BASELINE8_010225_0.14.1 TRUENAS low CPU burden 

objects:
  filters:
    dog:
      min_score: .8
      threshold: .9
    cat:
      min_score: .75
      threshold: .8
    fox:
      min_score: .65
      threshold: .8
    squirrel:
      min_score: .65
      threshold: .8
    bird:
      min_score: .65
      threshold: .8
    deer:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    license_plate:
      min_score: .6
    bicycle:
      min_score: .65
      threshold: .85


ui:
  time_format: 24hour
mqtt:
  enabled: false


model:
  path: plus://750ee08e1dda3669bc2c3273e6984a53  #mobiledet edgeTPU 2025.0 25/1/25
#  path: plus://e570a5fa60ccfce5aca76ad55c4ffddd  #mobiledet edgeTPU 2024.3 7/11/24
#  path: plus://98f2ff2d47bfacdd1823ef3641b716c4 #mobiledet edgeTPU 2024.3 3/11/24
#  path: plus://9b85aa0fc8a3aaa6ef8dfb8ea80a2dc9 #mobiledet edgeTPU 2024.2
#  path: plus://2cf1f99bc96475f2423babf38b7d7567 #mobiledet cpu 2024.2 


#go2rtc:
# streams:
    #reference format from NickM-27 @ https://github.com/blakeblackshear/frigate/discussions/12376 
    #              "ffmpeg:rtsp://...                                               #video=h264#audio=copy#hardware" note the quotes and hashes
#    greenhouse:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
#      - ffmpeg:greenhouse#audio=opus
#  upper_patio:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0#video=h264#audio=copy
#      - ffmpeg:upper_patio#audio=opus
#  ponds:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0#video=h264#audio=copy
#      - ffmpeg:ponds#audio=opus
#  blue_gate:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0#video=h264#audio=copy
#      - ffmpeg:blue_gate#audio=opus

#  lower_steps:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0#video=h264#audio=copy
#      - ffmpeg:lower_steps#audio=opus
#    lower_patio:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0#video=h264#audio=copy
#      - ffmpeg:lower_patio#audio=opus
#    shed:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0#video=h264#audio=copy
#      - ffmpeg:shed#audio=opus
#  drive:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0#video=h264#audio=copy
#      - ffmpeg:drive#audio=opus
#    doorbell:
#      - "ffmpeg:rtsp://admin:QXQODG@192.168.1.192:554/Streaming/Channels/101#raw -vf lenscorrection=k1=-0.450:k2=0.1"
#      - "ffmpeg:doorbell#audio=opus"

####rtsp is 30060 and webRTC is 30061 (TN Frigate app interrnals)
# webrtc:
#    candidates:
#      - 192.168.1.194:30061
#      - stun:30061


ffmpeg:
  #####you can only have one line here#####
  hwaccel_args: preset-nvidia-h264
  #hwaccel_args: preset-nvidia-hevc #gives black screens on cameras
  #hwaccel_args: preset-nvidia-cuvid #gives black screens on cameras
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

birdseye:
  enabled: true
  mode: continuous #continuous | objects | motion

# record: # <----- Enable recording # was working
#  enabled: true # was working

# added from https://fixtse.com/blog/coral-ia-frigate start#
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects
# added from https://fixtse.com/blog/coral-ia-frigate #

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true #false  #true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 768
  #height: 800
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 7
      cat: 5
      dog: 5
      bird: 1
      squirrel: 1
      fox: 5
      badger: 5
      car: 5
      deer: 7
      license_plate: 5
      bicycle: 3

  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

review:
  alerts:
    labels:
      - person
      - car
      - cat
      - dog
      - fox
      - deer
      - bicycle
  detections:
    labels:
      - person
      - car
      - cat
      - dog
      - fox
      - deer
      - bicycle

motion:
  improve_contrast: true

detect:
  width: 640
  height: 360

#record:
#  width: 1920
#  height: 1080

########################################################################################################################################################################################################################################

cameras: #########GREENHOUSE##################GREENHOUSE##################GREENHOUSE##################GREENHOUSE##################GREENHOUSE#########GREENHOUSE#########
  greenhouse:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
          roles:
            - detect


        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 1





#########UPPER_PATIO###############################################UPPER_PATIO###########################UPPER_PATIO###########################UPPER_PATIO###########################
  upper_patio: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #SD 640x360 level1 ### 130125 trying HD for det (here) and rec below as usual
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0  
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder

    zones:
      upperpatio:
        coordinates: 
          0.003,0.997,0.005,0.795,0.042,0.789,0.045,0.732,0.049,0.619,0.077,0.546,0.103,0.479,0.145,0.425,0.168,0.401,0.204,0.371,0.216,0.369,0.268,0.378,0.279,0.339,0.32,0.302,0.347,0.293,0.361,0.298,0.382,0.345,0.395,0.375,0.563,0.418,0.582,0.474,0.626,0.476,0.674,0.51,0.712,0.515,0.795,0.664,0.862,0.704,0.933,0.822,0.999,0.896,0.995,0.996
        loitering_time: 0
    motion:
      mask: 
        0.003,0.374,0.207,0.313,0.239,0.272,0.292,0.258,0.32,0.245,0.36,0.222,0.682,0.219,0.716,0.204,0.726,0.001,0.002,0.001

    review:
      alerts:
        required_zones: upperpatio
      detections: {}

#########UPPER_PATIO###############################################UPPER_PATIO###########################UPPER_PATIO###########################UPPER_PATIO###########################




  ponds: #################PONDS#######################################PONDS#########################PONDS#########################PONDS#########################PONDS#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=2&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
          roles:
            - detect


        - path: rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
          roles:
            - record
    
    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder

    birdseye:
      mode: continuous  #continuous | objects | motion
     # masks are black: they block out areas where you aren't interested in detecting things
      order: 3



  blue_gate: #########BLUE_GATE###################################################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #  input_args: preset-rtsp-restream

          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - badger # placeholder
        - car
        - license_plate
        - bicycle

    birdseye:
      mode: continuous   #continuous | objects | motion
      # masks are black: they block out areas where you aren't interested in detecting things
      order: 4

    motion:
      mask:
        - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
        - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360

    zones:
      gravel:
        coordinates: 
          411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233



  lower_steps: #########LOWER_STEPS#########LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=4&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 5


  lower_patio: #########LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 6

      # masks are black: they block out areas where you aren't interested in detecting things
    motion:
      mask:
        - 0,148,92,104,184,55,253,0,269,154,272,305,318,125,354,107,345,56,406,60,417,131,504,240,570,360,640,360,640,0,0,0
        #- 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      lower patio:
        coordinates: 
          284,360,303,183,333,157,344,139,357,118,352,99,359,74,382,73,384,110,403,128,499,246,580,360
#########LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO



  shed: #########SHED##########################SHED#########################SHED#########################SHED#########################SHED#########################SHED#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=6&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 7

#########SHED##########################SHED#########################SHED#########################SHED#########################SHED#########################SHED#########################



#########DRIVE##########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################
  drive: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record
    
    objects:
      track:
        - face
        - person
        - car
        - bicycle
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder


    zones:
      drive_gravel:
        coordinates: 
          0.256,0.37,0.355,0.375,0.344,0.548,0.693,0.536,0.991,0.866,0.999,0.991,0.207,0.995,0.2,0.595,0.082,0.522
        loitering_time: 0
    motion:
      mask: 
        0.002,0.36,0.179,0.304,0.27,0.269,0.276,0.12,0.361,0.137,0.358,0.349,0.487,0.351,0.658,0.356,0.71,0.358,0.998,0.539,0.993,0.003,0.008,0

    review:
      alerts:
        required_zones: drive_gravel
      detections:
        required_zones: drive_gravel
#########DRIVE##########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################  


#  doorbell: #####DOORBELL##########################DOORBELL##########################DOORBELL##########################DOORBELL#####################DOORBELL#####################DOORBELL#####################
#    enabled: true #remember that EZViz won't stream to more than thee (four?) destinations
#    ffmpeg:
#      inputs:
#        - path: rtsp://admin:QXQODG@192.168.1.192:554/Streaming/Channels/101 # H264 1536x1536
#          roles:
#            - detect
#      output_args:
#        detect: -vf lenscorrection=k1=-0.450:k2=0.1 -f rawvideo -pix_fmt yuv420p
#        - path: rtsp://127.0.0.1:8554/doorbell
#          roles:
#            - record
#      output_args:
#          detect: -vf lenscorrection=k1=-0.450:k2=0.1
#         
#    objects:
#      track:
#        - person
#        - cat
#        - dog
#        - bird
#        - deer
#        - fox #placeholder
#        - badger #placeholder
#    birdseye:
#      mode: continuous     #continuous | objects | motion
#        # masks are black: they block out areas where you aren't interested in detecting things
#      order: 9

# for the doorbell camera. this is what ffplay said (once I'd set the lens correction):

#$  ffplay -i rtsp://admin:QXQODG@192.168.1.192:554/Streaming/Channels/101 -vf lenscorrection=k1=-0.450:k2=0.095
#  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1536x1536, 15 fps, 15 tbr, 90k tbn
#  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp



logger:
  logs:
      #frigate.record.maintainer: debug
    frigate.object_detection: debug
      #watchdog.blue_gate: debug



version: 0.14
camera_groups:
  Woodlands:
    order: 1
    icon: LuActivitySquare
    cameras:
      - blue_gate
      - drive
      - greenhouse
      - lower_patio
      - lower_steps
      - ponds
      - shed
      - upper_patio


#-----------------------END-----------------------##-----------------------END-----------------------##-----------------------END
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
TrueNAS docker system - unknown details
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/5894777b-19cd-4fe5-a61d-d8f08ca49156)
