### DISCUSSION TITLE
Errors in system logs - arm64 - M4 Mac mini

### DISCUSSION THREAD

**Discussion by Landonthi** [blakeblackshear/frigate#16341] [General Support]
I have just setup frigate 0.15.0-rc2-standard-arm64 on my M4 Mac mini but am getting a lot of errors in the system logs. I was wondering if I could get some input on what is coming up? And maybe what I can do to fix the issues?

Thanks for any assistance you can provide.

I have uploaded my log file from about 1 hour of running.

[frigate-logs.txt](https://github.com/user-attachments/files/18680781/frigate-logs.txt)

**Comment by NickM-27** [comment]
we will have to see your config

**Reply by Landonthi** [reply]
Just posted it, but it didn't keep its formatting.

**Reply by NickM-27** [reply]
what is the docker compose?

**Reply by Landonthi** [reply]
Just posted it

**Reply by Landonthi** [reply]
> what is the docker compose?

Morning NIck, I was wondering if you had a chance to look into this a little more? I was also wondering if there is a way to support the project?

**Reply by NickM-27** [reply]
Yes, unfortunately I don't really know why these errors are occurring, seems quite odd that a cpu detector would fail.

**Reply by NickM-27** [reply]
To support the project you can check out the sponsor sidebar in the main page

**Reply by Landonthi** [reply]
> Yes, unfortunately I don't really know why these errors are occurring, seems quite odd that a cpu detector would fail.

Could this be an issue related to using docker desktop on Mac? What are you running your setup on?

**Reply by NickM-27** [reply]
I don't think so, both myself and Josh run docker desktop on Mac for developing Frigate

**Reply by Landonthi** [reply]
> I don't think so, both myself and Josh run docker desktop on Mac for developing Frigate

Hmm, could it possibly be related to low disk space? I am trying to test it on the 256gb storage model. I have been trying to get network storage configured for this setup in my compose file but am not having any luck. I was running network storage on my other system using a core i5 chip, coral and ubuntu. Can I post the issues I am having setting up my network storage or should I look for help elsewhere?

**Reply by NickM-27** [reply]
do you have go2rtc logs?

**Reply by Landonthi** [reply]
> do you have go2rtc logs?

I didn't think to save those, sorry about that. I will start it up and let it run for a while today and post the go2rtc logs in a bit.

**Reply by Landonthi** [reply]
Nick, here are log files for docker, frigate system logs and go2rtc logs. I let it run for about 40 mins. Let me know if I can help by sending you other info.

Thanks


[_frigate0150rc2_logs.txt](https://github.com/user-attachments/files/18711709/_frigate0150rc2_logs.txt)
[frigate-logs.txt](https://github.com/user-attachments/files/18711710/frigate-logs.txt)
[go2rtc-logs.txt](https://github.com/user-attachments/files/18711711/go2rtc-logs.txt)

**Reply by hawkeye217** [reply]
```
2025-02-07 19:38:29.149535542  19:38:29.149 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.2:39638->192.168.1.46:554: i/o timeout" url=rtsp://admin:Mindyd99@192.168.1.46:554
```
It looks like the network connection to the cameras is timing out. Are these wifi cameras?

**Reply by Landonthi** [reply]
> ```
> 2025-02-07 19:38:29.149535542  19:38:29.149 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.2:39638->192.168.1.46:554: i/o timeout" url=rtsp://admin:Mindyd99@192.168.1.46:554
> ```
> 
> It looks like the network connection to the cameras is timing out. Are these wifi cameras?

No these are 100% poe wired cameras. I was running the same system configuration file on an i5 system on Ubuntu for about a year and it worked pretty well, only the odd hangup where it needed a restart. But with this new M4 mini I just can't keep it running.

**Reply by hawkeye217** [reply]
You could try running the cameras with the ffmpeg module in go2rtc to see if that improves anything. For example:

```
go2rtc:
  streams:
    Driveway: ffmpeg:rtsp://######:#####@192.168.1.41:554
    Frontdoor: ffmpeg:rtsp://######:#####@192.168.1.42:554
    Side: ffmpeg:rtsp://######:#####@192.168.1.43:554
    Backyard: ffmpeg:rtsp://######:#####@192.168.1.44:554
    Kitchen: ffmpeg:rtsp://######:#####@192.168.1.45:554
    Basement: ffmpeg:rtsp://######:#####@192.168.1.46:554
    Garage: ffmpeg:rtsp://######:#####@192.168.1.47:554
```

**Reply by Landonthi** [reply]
> You could try running the cameras with the ffmpeg module in go2rtc to see if that improves anything. For example:
> 
> ```
> go2rtc:
>   streams:
>     Driveway: ffmpeg:rtsp://######:#####@192.168.1.41:554
>     Frontdoor: ffmpeg:rtsp://######:#####@192.168.1.42:554
>     Side: ffmpeg:rtsp://######:#####@192.168.1.43:554
>     Backyard: ffmpeg:rtsp://######:#####@192.168.1.44:554
>     Kitchen: ffmpeg:rtsp://######:#####@192.168.1.45:554
>     Basement: ffmpeg:rtsp://######:#####@192.168.1.46:554
>     Garage: ffmpeg:rtsp://######:#####@192.168.1.47:554
> ```

I ran it for about 30 mins with the ffmpeg update and it went sideways again, here are the logs form in Frigate. It always starts with the "b" error 

[frigate-logs.txt](https://github.com/user-attachments/files/18721859/frigate-logs.txt)

<img width="1320" alt="Screenshot 2025-02-08 at 11 35 19 AM" src="https://github.com/user-attachments/assets/a940682a-baf5-4c84-b06d-40ed8f9d4693" />

**Reply by hawkeye217** [reply]
Do you see any entries in the go2rtc log that correspond to the same or very close timestamp to those errors in the frigate log?

**Reply by Landonthi** [reply]
> Do you see any entries in the go2rtc log that correspond to the same or very close timestamp to those errors in the frigate log?

Downloaded new logs with go2rtc

[frigate-logs.txt](https://github.com/user-attachments/files/18721900/frigate-logs.txt)
[go2rtc-logs.txt](https://github.com/user-attachments/files/18721901/go2rtc-logs.txt)

**Reply by hawkeye217** [reply]
Not quite sure what the `ERROR   : b''` is, that may need some investigation. But the errors beyond that in your frigate log are because of the i/o timeout you see in your go2rtc log. 

Go2rtc just can't connect to your cameras after a certain period. 

When this happens again, you should see if you can manually access your cameras outside of the Frigate UI through VLC or another app that can play RTSP streams.  If not, then it's likely a network related issue on your end.

**Reply by Landonthi** [reply]
I tested opening the driveway camera using VLC well the errors are showing up and I was able to open a stream and watch the timestamp on the camera change.

I also decided to test out a beta version and setup Frigate (0.16.0-fa30074), I used the clone setting in docker desktop but docker would not let me deploy the container until I setup a path for tmp/cache. So I am wondering if this might be an issue with my compose file? Since I set a path for tmp/cache I have the beta version running for over an hour now, I still have a pile of the frigate.api.media  b" errors. But this is the longest it has stayed up and running, usually it makes it 25-30 mins.

Do you think it might be a tmp/cache issue? If so how should I set the path in the compose file? Or set it up in docker. Here is a screen shot of how I set it ups for now.

<img width="928" alt="Screenshot 2025-02-08 at 4 55 42 PM" src="https://github.com/user-attachments/assets/e1ffe5ca-470e-43db-b6a7-aa57188bc405" />

**Reply by hawkeye217** [reply]
On Linux, `/tmp/cache` is recommended to be a [tmpfs mount](https://docs.docker.com/engine/storage/tmpfs/). As long as your mount is on a fast drive, tmpfs isn't strictly required.

**Reply by Landonthi** [reply]
This is what I have in my compose file, I hope it's correct? The this is setup running on the Mac mini internal storage currently. If I wanted to setup the video to be stored on the NAS server does that automatically move the tmpfs to the NAS or does it stay locally stored?


- type: tmpfs # 1GB of memory
target: /tmp/cache
tmpfs:
size: 1000000000

**Reply by hawkeye217** [reply]
That configuration for `/tmp/cache` is what is recommended. Recorded video footage is what's stored in `/media/frigate`, which you have mounted separately.

**Reply by Landonthi** [reply]
Thanks for the help, hopefully I haven't been too big of a pain in the butt. Im trying to learn as I go, Im not a big linux/docker guy so this very much new to me. I will leave it like this for now and see how long it will run for and see what kind of errors I get.

**Reply by hawkeye217** [reply]
Happy to help!

**Reply by Landonthi** [reply]
Sorry, one last question for the night. Are there any hwaccel or cpu detector lines I should add in to the config file? Below is what I currently have, is that about all there is at this time ?

detectors: 
  cpu:
    type: cpu
    num_threads: 4

**Reply by hawkeye217** [reply]
If you're on a Mac Mini, that looks fine.

**Comment by Landonthi** [comment]
```
mqtt:
  host: 192.168.1.252
  user: frigate
  password: ######
  port: 1883

detectors: 
  cpu:
    type: cpu
    num_threads: 4

go2rtc:
  streams:
    Driveway: rtsp://######:#####@192.168.1.41:554
    Frontdoor: rtsp://######:#####@192.168.1.42:554
    Side: rtsp://######:#####@192.168.1.43:554
    Backyard: rtsp://######:#####@192.168.1.44:554
    Kitchen: rtsp://######:#####@192.168.1.45:554
    Basement: rtsp://######:#####@192.168.1.46:554
    Garage: rtsp://######:#####@192.168.1.47:554

cameras:
  Driveway:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 2688
      height: 1512
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
    zones:
      Driveway_pad:
        coordinates: 
          0.214,0.152,0.457,0.132,0.701,0.167,0.759,0.387,0.813,0.601,0.859,0.875,0.872,0.988,0.441,0.993,0.047,0.997,0.073,0.746,0.114,0.544,0.151,0.376
        loitering_time: 0
  Frontdoor:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Frontdoor
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1512
      height: 2688
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        car: {}
    zones:
      porch:
        coordinates: 
          0,1278,0,2688,543,2688,1006,2688,1376,2688,1520,2666,1153,1882,932,1673,891,1611,835,1573,709,1299,387,1114,305,807,254,480,0,478
    motion: {}
  Side:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 2688
      height: 1512
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
  Backyard:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1512
      height: 2866
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
  Kitchen:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 2688
      height: 1512
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
  Basement:
    ui:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Basement
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 2688
      height: 1512
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          mask:
            - 1570,530,1882,500
    motion: {}
  Garage:
    ui:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 10
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1512
      height: 2688
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
version: 0.15-1
```
