### DISCUSSION TITLE
[Support]: Storage under utilized reported incorrectly

### DISCUSSION THREAD

**Discussion by VeganBiker** [blakeblackshear/frigate#16358] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Frigate is indicating that each camera can only use 124.28GB of space to record/store video/images when I have a dedicated 4TB ssd for storage. I have 11 cameras so that would be 1367.74GB for recordings leaving 2359.62GB unusable for storage?

### Steps to reproduce

1. I just noticed this after trying to change one camera to record all the time instead of just motion

### Version

0.14.1

### In which browser(s) are you experiencing the issue with?

Librewolf 134.0.2-1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: #Host#
  user: frigate
  password: #Password#

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2
#model:
#  width: 320
#  height: 320
#  path: "/config/CodeProject.AI-Custom-IPcam-Models/TensorFlow Edge TPU Models/YOLOv8/assets/yolov8l.tflite"
cameras:
  CAM0:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM0
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM0_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #HOSTIP#
      port: 80
      user: frigate
      password: #Password#
    detect:
      enabled: true
      fps: 10
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
    motion:
      mask:
        - 0.662,0.034,0.984,0.032,0.982,0.065,0.664,0.06
        - 0.745,0.076,0.585,0.04,0.505,0.051,0.491,0.072,0.468,0.062,0.432,0.063,0.419,0.091,0.388,0.087,0.383,0.052,0.344,0.063,0.275,0.08,0.247,0.114,0.257,0.223,0.749,0.177
        - 0.188,0,0.198,0.142,0.335,0.176,0.357,0
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 10
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 10
        retain:
          default: 14
          mode: active_objects
  CAM1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    detect:
      enabled: true
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 2
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
    motion:
      mask: 0.63,0.023,0.624,0,0.963,0.001,0.962,0.026
  CAM2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.120
      port: 8899
      user: frigate
      password: #Password#
    detect:
      enabled: true
      fps: 10
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
    motion:
      mask: 0.827,0.032,0.827,0,1,0,1,0.035
  CAM3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM3
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.121
      port: 8899
      user: frigate
      password: #Password#
    detect:
      enabled: true
      fps: 10
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
    motion:
      mask: 0.827,0.031,1,0.03,1,0,0.827,0
  CAM4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM4
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.122
      port: 8899
      user: frigate
      password: #Password#
    detect:
      enabled: true
      fps: 10
    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
    motion:
      mask: 0.821,0.035,0.82,0,1,0,1,0.039
  CAM5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM5
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    detect:
      enabled: true
    motion:
      mask: 0.671,0.036,0.987,0.039,0.986,0,0.671,0
  CAM6:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM6
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM6_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.110
      port: 80
      user: frigate
      password: #Password#
    live:
      stream_name: CAM6_sub
    detect:
      enabled: true
    objects:
      filters:
        car:
          mask: 0.332,0.371,0.372,0.813,0,0.926,0,0.389,0.242,0.267
    motion:
      mask: 0.664,0.061,0.665,0.035,0.982,0.033,0.981,0.064
  CAM7:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM7
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM7_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.111
      port: 80
      user: frigate
      password: #Password#
    detect:
      enabled: true
    motion:
      mask:
        - 0.664,0.035,0.98,0.035,0.982,0.063,0.664,0.061
        - 1,0.43,0.637,0.102,0.638,0,1,0
        - 0.323,0,0,0.113,0,0
      threshold: 35
      contour_area: 16
      improve_contrast: 'true'
    objects:
      filters:
        person:
          mask:
            - 0.356,0.35,0.348,0.449,0.384,0.449,0.403,0.392,0.39,0.324
            - 0.505,0.175,0.505,0.267,0.566,0.274,0.568,0.213,0.553,0.186
  CAM8:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM8
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM8_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.114
      port: 80
      user: frigate
      password: #Password#
    detect:
      enabled: true
    motion:
      mask: 0.661,0.035,0.981,0.032,0.98,0.062,0.663,0.061
  CAM9:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM9
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM9_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.116
      port: 80
      user: frigate
      password: #Password#
    detect:
      enabled: true
    motion:
      mask: 0.664,0.033,0.982,0.033,0.981,0.065,0.664,0.062
  CAM10:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM10
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM10_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - audio
    onvif:
      host: #CAMIP#.61
      port: 80
      user: frigate
      password: #Password#
    detect:
      enabled: true

# Optional: Audio Events Configuration
# NOTE: Can be overridden at the camera level
    motion:
      mask: 0.661,0.032,0.991,0.032,0.993,0.066,0.662,0.063
      threshold: 51
      contour_area: 59
      improve_contrast: 'true'
    objects:
      filters:
        car:
          mask: 0,0,1,0,1,1,0,1
        person:
          mask: 0,0,1,0,1,1,0,1
audio:
  # Optional: Enable audio events (default: shown below)
  enabled: false
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8
# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  #width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  #height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 10
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - horse
    - cow
    - bird
    - bear


# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  #mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: false
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 7
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  # Optional: Recording Export Settings
  #export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    #timelapse_args: "-vf setpts=0.04*PTS -r 30"
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - bicycle
      - car
      - cat
      - dog
      - horse
      - cow
      - bird
      - bear
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 15
        bicycle: 5
        car: 7
        cat: 5
        dog: 5
        horse: 5
        cow: 5
        bird: 2
        bear: 5

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: false
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 15
      car: 10
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70

ffmpeg:
 # hwaccel_args: preset-intel-qsv-h265
  hwaccel_args: preset-vaapi
#  hwaccel_args:
#     -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
#  output_args:
#    detect: '-f rawvideo -pix_fmt yuv420p'
#    record: >-
#      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
#      -strftime 1 -c copy

go2rtc:
  rtsp:
    username: go2rtc
    password: #Password#
    default_query: video=h264&audio=all
  log:
    level: warn    # default level
    api: trace
    exec: warn
    ngrok: warn
    rtsp: warn
    streams: warn
    webrtc: error
  streams:
    CAM0:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.60/stream0#video=copy#audio=aac
    CAM0_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.60/stream1#video=copy#audio=aac
    CAM1:
      - ffmpeg:rtsp://admin:#Password#@#CAMIP#.104/ch01/0#video=copy
    CAM1_sub:
      - ffmpeg:rtsp://admin:#Password#@#CAMIP#.104/ch01/1#video=copy
    CAM6:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.110/stream0#video=copy#audio=aac
    CAM6_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.110/stream1#video=copy#audio=aac
    CAM7:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.111/stream0#video=copy#audio=aac
    CAM7_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.111/stream1#video=copy#audio=aac
    CAM8:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.114/stream0#video=copy#audio=aac
    CAM8_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.114/stream1#video=copy#audio=aac
    CAM9:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.116/stream0#video=copy#audio=aac
    CAM9_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.116/stream1#video=copy#audio=aac
    CAM2:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.120/channel=0_stream=0#video=h264#hardware#audio=aac
    CAM2_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.120/channel=0_stream=1#video=h264#hardware#audio=aac
    CAM3:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.121/channel=0_stream=0#video=h264#hardware#audio=aac
    CAM3_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.121/channel=0_stream=1#video=h264#hardware#audio=aac
    CAM4:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.122/channel=0_stream=0#video=h264#hardware#audio=aac
    CAM4_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.122/channel=0_stream=1#video=h264#hardware#audio=aac
#    garage_toolbench:
#      - ffmpeg:rtsp://admin:#Password#@#CAMIP#.101/channel=1_stream=0#video=h264#hardware
#    garage_toolbench_sub:
#      - ffmpeg:rtsp://admin:#Password#@#CAMIP#.101/channel=1_stream=0#video=h264#hardware
#    garage_aisle_1:
#      - ffmpeg:rtsp://admin:#Password#@#CAMIP#.102/channel=1_stream=0#video=h264#hardware
#    garage_aisle_1_sub:
#      - ffmpeg:rtsp://admin:#Password#@#CAMIP#.102/channel=1_stream=0#video=h264#hardware
    CAM5:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.103/cam/realmonitor?channel=1&subtype=0#video=copy#audio=aac
    CAM5_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.103/cam/realmonitor?channel=1&subtype=1#video=copy#audio=aac
    CAM10:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.61/stream0#video=copy#audio=aac
    CAM10_sub:
      - ffmpeg:rtsp://frigate:#Password#@#CAMIP#.61/stream1#video=copy#audio=aac
  webrtc:
    candidates:
      - 192.168.0.0/16:8555
      - 172.16.0.0/16:8555
      - 10.0.0.0/8:8555
      - stun:8555
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2gb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1
      - /dev/apex_2:/dev/apex_2
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2gb
    network_mode: host
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "1984:1984" #go2rtc
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
#    environment:
#      FRIGATE_RTSP_PASSWORD: "password"

    deploy:
      resources:
        reservations:
#          cpus: '0.25'
          memory: 8G
        limits:
#          cpus: '0.50'
          memory: 15G
#          pids: 1
```

### Relevant Frigate log output

```shell
Not sure what logs would be needed for this
```

### Relevant go2rtc log output

```shell
unrelated?
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

4k

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/5ca76687-c1ae-4bfb-8311-a1ab5a1d3e25)

### Any other information that may be helpful

This is inside a LXC with docker on proxmox.
