### DISCUSSION TITLE
[Config Support]: Hi CPU usage by FFMPEG without detect config

### DISCUSSION THREAD

**Discussion by maxx-ukoo** [blakeblackshear/frigate#16365] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I see warning Camera has high FFMPEG CPU usage without detect enabled
This config:

`
  R-CAM02:
    ffmpeg:
       inputs:
          - path:
              rtsp://view:zm_Passw0rd2@10.23.10.17:554/h264Preview_01_main
           roles:
             - record
`

produce R-CAM02 has high FFMPEG CPU usage warning:
![image](https://github.com/user-attachments/assets/c44078e0-8917-464d-a3bb-e5210fc9af01)

but this conifg:
`
  R-CAM02:
    ffmpeg:
      inputs:
        - path:
            rtsp://view:zm_Passw0rd2@10.23.10.17:554/h264Preview_01_main
          roles:
            - record
        - path:
            rtsp://view:zm_Passw0rd2@10.23.10.17:554/h264Preview_01_sub
          roles:
            - detect
`
Works without high CPU usage error. And I see it in top - no ffmpeg process with high CPU usage:

![frigate-ok](https://github.com/user-attachments/assets/08150acb-2476-43ad-8f12-9ed7450801b5)

### Steps to reproduce

1. Create config for camera with only record role (see config for  R-CAM02 in my config)
2.
3.
...

### Version

0.15.0-6b12a45

### Frigate config file

```yaml
mqtt:
  host: host

database:
  path: /opt/db/frigate.db

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 15
    mode: all
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog
    - bird
detectors:
  coral:
    type: edgetpu
    device: ''

cameras:
  8KPTZ-1:
    ffmpeg:
      inputs:
        - path: 
            rtsp://10:554/stream1?username=admin&password=
          roles:
            - detect
        - path: 
            rtsp://10:554/stream0?username=admin&password=
          roles:
            - record
    detect:
      width: 720
      height: 480
    motion:
      improve_contrast: true
    onvif:
      host: 10.
      port: 80
      user: admin
      password: ''
  8KPTZ-2:
    enabled: false
    ffmpeg:
      inputs:
        - path: 
            rtsp://10.:554/stream1?username=admin&password=
          roles:
            - detect
        - path: 
            rtsp://10.:554/stream0?username=admin&password=6
          roles:
            - record
    detect:
      width: 3840
      height: 2144
    motion:
      improve_contrast: true
    onvif:
      host: 10.
      port: 80
      user: 
      password: 
  R-CAM02:
    ffmpeg:
      inputs:
        - path:
            rtsp://user:pass@IP:554/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: false
  R-CAM03:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@IP:554/h264Preview_01_main
          roles:
            - record
    detect:
      enabled: false
  X-CAM01:
    ffmpeg:
      inputs:
        - path: 
            rtsp://10:554/user=admin_password=_channel=1_stream=1.sdp?real_stream
          roles:
            - detect
        - path: 
            rtsp://10.:554/user=admin_password=_channel=1_stream=0.sdp?real_stream
          roles:
            - record
    motion:
      improve_contrast: true
  R-PTZ-CAM04:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@IP:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://user:pass@IP:554/h264Preview_01_main
          roles:
            - record
    objects:
      filters:
        person:
          min_area: 300
    motion:
      improve_contrast: true
    onvif:
      host: 10.
      port: 8000
      user: view
      password: 
  R-PTZ-CAM05:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@IP:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://user:pass@IP:554/h264Preview_01_main
          roles:
            - record
    motion:
      improve_contrast: true
    onvif:
      host: 10.
      port: 8000
      user: view
      password: 
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    privileged: true
    container_name: frigate

    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta3
    shm_size: "768mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tb-pool/docker-opt/frigate/config.yml:/config/config.yml
      - /mnt/tb-pool/docker-opt/frigate/db:/opt/db
      - fr_cifs_mount:/media/frigate

    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:

      FRIGATE_RTSP_PASSWORD: "****************"
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink  RLC-820A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/58f22b78-f3e0-45f8-aceb-de178fe19b65)

### Any other information that may be helpful

main stream:
root@0949e19f461f:/usr/lib/ffmpeg/7.0/bin# ./ffprobe h264Preview_01_main
ffprobe version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[rtsp @ 0x563e7f8935c0] max delay reached. need to consume packet
[rtsp @ 0x563e7f8935c0] RTP: missed 4 packets
[rtsp @ 0x563e7f8935c0] max delay reached. need to consume packet
[rtsp @ 0x563e7f8935c0] RTP: missed 2 packets
[rtsp @ 0x563e7f8935c0] max delay reached. need to consume packet
[rtsp @ 0x563e7f8935c0] RTP: missed 1 packets
[rtsp @ 0x563e7f8935c0] max delay reached. need to consume packet
[rtsp @ 0x563e7f8935c0] RTP: missed 1 packets
Input #0, rtsp, from 'rtsp:///h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000125, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

substream details

root@0949e19f461f:/usr/lib/ffmpeg/7.0/bin# ./ffprobe /h264Preview_01_sub
ffprobe version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, rtsp, from 'rtsp://h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x360, 10 fps, 24.92 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
