### DISCUSSION TITLE
[Camera Support]: No Live Audio with Reolink E1Pro

### DISCUSSION THREAD

**Discussion by 7aklhz** [blakeblackshear/frigate#16362] [Camera Support] [answered]
### Describe the problem you are having

I have connected my Reolink E1Pro cameras. While I have audio on recording / playback, I cannot get audio on live view. 

I have briefly discussed this in [another ticket](https://github.com/blakeblackshear/frigate/discussions/11514) but without luck (I tested using the ffmpeg module)

Below is my conf file

Any suggestion on how to make this work ? 

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Brave  1.73.101

### Frigate config file

```yaml
mqtt:
  enabled: false
birdseye:
  enabled: true
  mode: continuous
  quality: 1
go2rtc:
  streams:
    cam1_main:
      - rtsp://abc:123@333101:554/h264Preview_01_main
      - ffmpeg:cam1#audio=copy#audio=aac#stimeout=30000000
    cam1_sub:
      - rtsp://abc:123@333101:554/h264Preview_01_sub
      - ffmpeg:cam1#audio=copy#audio=aac#stimeout=30000000
    cam2_main:
      - rtsp://abc:123@333102:554/h264Preview_01_main
      - ffmpeg:cam2#audio=copy#audio=aac#stimeout=30000000
    cam2_sub:
      - rtsp://abc:123@333102:554/h264Preview_01_sub
      - ffmpeg:cam2#audio=copy#audio=aac#stimeout=30000000
    cam3_main:
      - rtsp://abc:123@333103:554/h264Preview_01_main
      - ffmpeg:cam3#audio=copy#audio=aac#stimeout=30000000
    cam3_sub:
      - rtsp://abc:123@333103:554/h264Preview_01_sub
      - ffmpeg:cam3#audio=copy#audio=aac#stimeout=30000000
    cam4_main:
      - rtsp://abc:123@333104:554/h264Preview_01_main
      - ffmpeg:cam4#audio=copy#audio=aac#stimeout=30000000
    cam4_sub:
      - rtsp://abc:123@333104:554/h264Preview_01_sub
      - ffmpeg:cam4#audio=copy#audio=aac#stimeout=30000000
cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam1_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam1_main
    record:
      enabled: true
    detect:
      enabled: false
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam2_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam2_main
    record:
      enabled: true
    detect:
      enabled: false
  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam3_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam3_main
    record:
      enabled: true
    detect:
      enabled: false
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_main
          roles:
            - record
        #- path: rtsp://127.0.0.1:8554/cam4_sub
        #  roles:
        #    - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam4_main
    record:
      enabled: true
    detect:
      enabled: false
record:
  enabled: true
  retain:
    days: 4
    mode: all
version: 0.14
camera_groups:
  MyLayout:
    order: 1
    icon: LuShapes
    cameras:
      - cam1
      - cam2
      - cam3
      - cam4
```

### Relevant Frigate log output

```shell
N/A : no errors
```

### Relevant go2rtc log output

```shell
N/A : no errors
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://abc:123@333101:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Reolink E1Pro

### Screenshots of the Frigate UI's System metrics pages

N/A

**Comment by hawkeye217** [comment, marked as answer]
You have the wrong stream name in your go2rtc config ffmpeg lines. It needs to match the name of the stream you've defined. 

For example:

```

go2rtc:
  streams:
    cam1_main:
      - rtsp://abc:123@333101:554/h264Preview_01_main
      - ffmpeg:cam1_main#audio=copy#audio=aac#stimeout=30000000
```
