### DISCUSSION TITLE
Force manual vacuum to database

### DISCUSSION THREAD

**Discussion by dealanis** [blakeblackshear/frigate#16388] [General Support] [answered]
### Describe the problem you are having

Hi! I recently detected my database being over 9GB, I have 6 cameras and a retention of 100 days. Wanted to try manually vacuum it before losing all this historic data. Is there any way inside frigate? or a recommended command to do it directly to database. 

I activated sync_database to try and purge some data because in disk I there is 

Thanks!

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Versión 132.0.6834.160

### Frigate config file

```yaml
mqtt:
  host: xx
  user: xx
  password: xx



detectors:
  coral:
    type: edgetpu
    device: pci:0
   

cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=7&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=7&subtype=0 # <----- Update for your camera
          roles:
            - record
    #rtmp:
    #  enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
    #  filters:
        #car:
        #  mask:
        #    - 1280,720,1280,376,1005,201,424,254,369,720 #patio trasero
    #zones:
    #  patio_trasero:
    #    coordinates: 1280,720,0,720,0,281,469,224,983,184,1006,54,1280,191  
  camera_2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=8&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=8&subtype=0 # <----- Update for your camera
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    objects:
      track:
        - person
    #zones:
      #patio_trasero:
      #  coordinates: 1280,457,1280,720,1280,720,0,720,0,32,307,117,316,265
  camera_3: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    detect:
      width: 960 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
  camera_4: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=14&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=14&subtype=0 # <----- Update for your camera
          roles:
            - record

    detect:
      width: 960 #1280 # <---- update for your camera's resolution
      height: 576 #720 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
  camera_5: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=12&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=12&subtype=0 # <----- Update for your camera
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    objects:
      track:
        - person
  camera_6: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=19&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://xx@10.60.100.85:554/cam/realmonitor?channel=19&subtype=0 # <----- Update for your camera
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
motion:
  mask:
    - 1259,26,1259,74,691,75,687,21 #timestamp dahua

record:
  enabled: true
  sync_recordings: True
  events:
    retain:
      default: 100

auth:
  enabled: true

snapshots:
  enabled: true
  bounding_box: true
version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

N/A
