### DISCUSSION TITLE
[Config Support]: Recording substream

### DISCUSSION THREAD

**Discussion by jwill2385** [blakeblackshear/frigate#16397] [Config Support] [answered]
### Describe the problem you are having

Hello I am using amcrest IP cameras. These cameras have a max resolution of 5MP which creates very large files. I've reduced the quality down to 720P on the amcrest app however when i use the rtsp path on frigate the videos seem to still record in the max resolution. 

I have even tried to use the substream as well which by default is at a much lower resolution but frigate always seems to record the main stream? Is there another way to only record the substream or a lower quality?

Currently videos are saving at 2-3mb per 10 second clip. So 2 minute video exports are around 30mb which is very large

### Version

frigate:stable

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
  enabled: False #Turn off birdseye for all cameras
cameras:
   stall1:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.50.207:554/cam/realmonitor?channel=4&subtype=1
          roles: 
            - record
        - path: rtsp://admin:password@192.168.50.207:554/cam/realmonitor?channel=4&subtype=1
          roles: 
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
      retain:
        days: 7    
  stall2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.50.207:554/cam/realmonitor?channel=3&subtype=1
          roles: 
            - record
        - path: rtsp://admin:password@192.168.50.207:554/cam/realmonitor?channel=3&subtype=1
          roles: 
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
      retain:
        days: 7
  stall5:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.50.207:554/cam/realmonitor?channel=2&subtype=1
          roles: 
            - record
        - path: rtsp://admin:password@192.168.50.207:554/cam/realmonitor?channel=2&subtype=1
          roles: 
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
      retain:
        days: 7
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    # image: ghcr.io/blakeblackshear/frigate:0.12.1
    image: ghcr.io/blakeblackshear/frigate:stable #Jetson nano image jetpack 5.0+
    shm_size: "512mb" # 64mb update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/visionsense/Docker/Frigate/config:/config
      - /home/visionsense/Docker/Frigate/media:/media/frigate #TODO switch this to external HD for media storage
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      FRIGATE_RTSP_USER: "admin"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Object Detector

CPU (no coral)

### Any other information that may be helpful

I am using these cameras https://amcrest.com/4k-poe-ai-camera-panoramic-ip8m-md180e-ai.html
