### DISCUSSION TITLE
How do I correctly enable embedding/genai debugging logs for diagnostics

### DISCUSSION THREAD

**Discussion by freesamael** [blakeblackshear/frigate#16409] [Ask A Question] [answered]
I was using the latest release `ghcr.io/blakeblackshear/frigate:0.15.0` and setting up GenAI with Ollama.
To check the performance with my Ollama setup I tried to enable debug logs:

```yml
logger:
  logs:
    frigate.object_detection: debug
    frigate.embeddings: debug
    frigate.genai: debug
    detector.ov.gpu: debug
    detector.ov.cpu: debug
```

and I was expecting it would print this log in `frigate/embeddings/maintainer.py` 
```python
logger.debug(
    "Generated description for %s (%d images): %s",
    event.id,
    len(thumbnails),
    description,
)
```
and this log in `frigate/genai/__init__.py` 
```python
logger.debug(f"Sending images to genai provider with prompt: {prompt}")
```
every time I press the "Regenerate" button on Frigate UI or when a new object is detected, but it didn't.

I was also expecting it prints some warnings/errors when it exceeds the 60s limit calling Ollama but that didn't show up either. On the Ollama server logs I was observing some of these timeout cases but it didn't appear on Frigate (either with the Frigate UI log viewer or `docker log -f frigate`.
```
Feb 09 20:35:05 homelab ollama[817902]: [GIN] 2025/02/09 - 20:35:05 | 500 |          1m0s |      172.18.0.4 | POST     "/api/generate"
Feb 09 23:01:19 homelab ollama[817902]: [GIN] 2025/02/09 - 23:01:19 | 500 |          1m0s |      172.18.0.4 | POST     "/api/generate"
```

Am I doing it wrong? I've also experimented adding different logs here and there but some just don't print after Frigate is fully started (a few seconds after FastAPI started) and I was really confused. 

Here's the full configuration if it helps.
<details>
  <summary>
    Expand
  </summary>

```yml
auth:
  failed_login_rate_limit: 1/second;3/minute;10/hour
  trusted_proxies:
    - 172.18.0.0/16

tls:
  enabled: false

mqtt:
  enabled: false

telemetry:
  stats:
    network_bandwidth: true

logger:
  logs:
    frigate.object_detection: debug
    frigate.embeddings: debug
    frigate.genai: debug
    detector.ov.gpu: debug
    detector.ov.cpu: debug

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  ov.gpu:
    type: openvino
    device: GPU
  ov.cpu:
    type: openvino
    device: CPU

model:
  model_type: yolonas
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s_320.onnx
  labelmap_path: /labelmap/coco-80.txt

objects:
  track:
    - cat
    - person
  filters:
    person:
      threshold: 0.8

review:
  alerts:
    labels:
      - cat
      - person

semantic_search:
  enabled: true
  # reindex: true
  model_size: large

genai:
  enabled: true
  provider: ollama
  base_url: http://host.docker.internal:11434
  model: llava

go2rtc:
  rtsp:
    username: '{FRIGATE_GO2RTC_RTSP_USERNAME}'
    password: '{FRIGATE_GO2RTC_RTSP_PASSWORD}'
  ffmpeg:
    15fps: -r 15 -filter:v fps=15
  streams:
    tapo_balcony_lq:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@192.168.100.13:554/stream2

    tapo_balcony_portrait_lq:
      - ffmpeg:tapo_balcony_lq#video=h265#audio=aac#rotate=270#drawtext=x=5:y=10:fontsize=28:fontcolor=white#hardware=vaapi#raw=15fps

    tapo_balcony_hq:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@192.168.100.13:554/stream1

    tapo_balcony_portrait_hq:
      - ffmpeg:tapo_balcony_hq#video=h265#audio=aac#rotate=270#drawtext=x=5:y=10:fontsize=28:fontcolor=white#hardware=vaapi#raw=15fps

    tapo_bedroom_lq:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@192.168.100.12:554/stream2
      - ffmpeg:tapo_bedroom_lq#video=h265#audio=aac#hardware=vaapi

    tapo_bedroom_hq:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@192.168.100.12:554/stream1
      - ffmpeg:tapo_bedroom_hq#video=h265#audio=aac#hardware=vaapi

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    pre_capture: 60
    post_capture: 60
    retain:
      days: 180
  detections:
    pre_capture: 60
    post_capture: 60
    retain:
      days: 180

snapshots:
  enabled: true
  retain:
    default: 180

audio: # enable audio events for all camera
  enabled: true
  listen:
    - speech
    - meow
    - snoring

cameras:
  tapo_balcony:
    enabled: true
    onvif:
      host: 192.168.100.13
      port: 2020
      user: '{FRIGATE_TAPO_RTSP_USERNAME}'
      password: '{FRIGATE_TAPO_RTSP_PASSWORD}'
    detect:
      width: 720
      height: 1280
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_balcony_portrait_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/tapo_balcony_portrait_hq
          input_args: preset-rtsp-generic
          roles:
            - record
    zones:
      Balcony:
        coordinates: 0.757,1,0,1,0,0.137,0.548,0.297,0.877,0.299,0.887,0.485,0.834,0.782
        loitering_time: 0
        objects: person
    review:
      detections:
        required_zones: Balcony
      alerts:
        required_zones: Balcony
    genai:
      object_prompts:
        person: |
          Here is a series of images captured by a home security camera. The camera's viewport faces towards the exit.
          Please provide a concise description (up to 150 words) of the main person's current action. Focus on:
          - What they are carrying or handling
          - How they interact with objects or other people
          - What those actions suggest about their intent (e.g., leaving, doing laundry, returning with items)

          Do not:
          - Include any speculation or describe unseen details
          - Mention surroundings or background context.
          - Explain your reasoning or ask for more information

  tapo_bedroom:
    enabled: true
    onvif:
      host: 192.168.100.12
      port: 2020
      user: '{FRIGATE_TAPO_RTSP_USERNAME}'
      password: '{FRIGATE_TAPO_RTSP_PASSWORD}'
    detect:
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_bedroom_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/tapo_bedroom_hq
          input_args: preset-rtsp-generic
          roles:
            - record
    genai:
      object_prompts:
        person: |
          Here is a series of images captured by a fixed bedroom security camera.
          Please provide a concise description (up to 150 words) of the main person's current action or behavior. Focus on:
          - How they interact with any people, animals, or objects
          - What these actions suggest about their intent (e.g., sleeping, folding clothes, using a phone, feeding a pet)

          Do not:
          - Include any speculation or describe unseen details
          - Mention surroundings or background context.
          - Explain your reasoning or ask for more information

          Only state simple, observable facts about the person's behavior.
        cat: |
          Here is a series of images captured by a fixed bedroom security camera.
          The camera shows a cat. Please provide a concise description (up to 150 words) of the cat's current behavior. Focus on:
          - How the cat interacts with any people, animals, or objects
          - What these actions suggest about the cat's activity (e.g., seeking attention, asking for food, sleeping, playing, or hunting)

          Do not:
          - Include speculation about unseen details or surroundings
          - Describe background context or the cat's appearance
          - Explain your reasoning or ask for more information

          Only state simple, observable facts about the cat's behavior.

version: 0.15-1
```
</details>
