### DISCUSSION TITLE
How GPU from Synology ?

### DISCUSSION THREAD

**Discussion by PaulEins** [blakeblackshear/frigate#16400] [Ask A Question]
Hello,

how do I adapt this installation to my Synology 920+? I am using Docker.
I have the Eufy 220 Outdoor cam and have managed to integrate it. But the picture is slightly worse? Slightly red and less white. Why is that? Because at the same time the Synology Servilance Station also accesses it via RTPS and displays a better image.

How can I add the frames per second?
And above all, how do I activate CPU or GPU support? I seem to have to adjust it in the installation as well as in the config. But I am an amateur and have tried many things and used the internet via Google, as well as CHATGPT. 

I have this:

```
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    container_name: Frigate
    hostname: frigate
    privileged: true # selber gemacht
    restart: on-failure:5
    security_opt:
     - apparmor=unconfined
     - systempaths=unconfined
    shm_size: 512mb
    environment:
     LIBVA_DRIVER_NAME: i965
     TZ: Europe/Berlin
     FRIGATE_RTSP_PASSWORD: eiXXXXXXXXXXXXXXXXXXXM
    devices:
      - /dev/dri/renderD128 # for NAS with an Intel Hardware Accelerator
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker2/frigate/config:/config:rw
      - /volume2/docker2/frigate/media:/media/frigate:rw
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5563:5000 #Web UI Interface Port
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
```
and this:

```
mqtt:
  enabled: false

cameras:
  camFlur: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX:XXXXXXXXXXXX@192.168.3.161/live0 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
    zones:
      eins:
        coordinates: 0.081,0.022,0.173,0.455,0.414,1,0.752,0.912,0.936,0.184,0.733,0.02
        loitering_time: 0
version: 0.14
```
