### DISCUSSION TITLE
[Config Support]: Input should be a valid dictionary or instance of FrigateConfig

### DISCUSSION THREAD

**Discussion by adamjacobmuller** [blakeblackshear/frigate#16412] [Config Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Hi,

When using the helm chart with 0.15.0, I'm getting this error while frigate starts: `Input should be a valid dictionary or instance of FrigateConfig`

I'm including my configuration here, but, of note this happens even if delete my configuration from the helm chart (so let the helm chart use the default config), I still get the same error.

Same config works fine on 0.14.1

Thanks in advance,

### Steps to reproduce

install frigate with helm chart

### Version

0.15.0

### Frigate config file

```yaml
telemetry:
    stats:
      amd_gpu_stats: True
      intel_gpu_stats: False
      network_bandwidth: False

  go2rtc:
    webrtc:
      candidates:
        - 100.96.71.42:8555
    streams:
      back-doorbell:
        - "rtsp://admin:@10.0.9.47:88/videoMain"
        - "ffmpeg:back#audio=aac"
      front-doorbell:
        - "rtsp://admin:@10.0.9.38:88/videoMain"
        - "ffmpeg:front#audio=aac"
      garage:
        - "rtsp://frigate:@10.0.9.64/Preview_01_main"
      corner:
        - "rtsp://frigate:@10.0.9.216/Preview_01_main"
      front:
        - "rtsp://frigate:@10.0.9.215/Preview_01_main"

  ffmpeg:
    hwaccel_args: preset-vaapi
    output_args:
      record: preset-record-generic-audio-aac

  record:
    enabled: True
    retain:
      days: 30
      mode: all
    events:
      retain:
        default: 365
        mode: active_objects

  snapshots:
    enabled: True
    retain:
      default: 15

  audio:
    enabled: True
    listen:
      - air_brake
      - air_horn
      - aircraft
      - aircraft_engine
      - alarm
      - alarm_clock
      - ambulance
      - animal
      - arrow
      - artillery_fire
      - bang
      - bark
      - beep
      - car_alarm
      - cat
      - chainsaw
      - civil_defense_siren
      - dog
      - emergency_vehicle
      - fire
      - fire_alarm
      - fire_engine
      - firecracker
      - fireworks
      - fixed-wing_aircraft
      - foghorn
      - glass
      - helicopter
      - honk
      - ice_cream_truck
      - jackhammer
      - knock
      - lawn_mower
      - machine_gun
      - motorcycle
      - police_car
      - power_tool
      - rain
      - reversing_beeps
      - siren
      - smoke_detector
      - speech
      - train_horn
      - train_whistle
      - truck
      - vehicle
      - whimper_dog
      - whistle
      - wild_animals
      - yell

  objects:
    track:
      - person
      - bicycle
      - car
      - motorcycle
      - bus
      - boat
      - bird
      - cat
      - dog

  detectors:
    coral:
      type: edgetpu
      device: usb

  mqtt:
    enabled: True
    host: mosquitto.frigate.svc

  detect:
    stationary:
      interval: 50
      threshold: 50

  birdseye:
    restream: true

  ui:
    strftime_fmt: "%Y-%m-%d %H:%M:%S"

  cameras:
    front-doorbell:
      ffmpeg:
        inputs:
          - path: rtsp://admin:@10.0.9.38:88/videoMain
            roles:
              - record
              - audio
          - path: rtsp://admin:@10.0.9.38:88/videoSub
            roles:
              - detect
      detect:
        width: 1280
        height: 720
      motion:
        mask:
          - 475,153,180,206,184,380,483,365,659,375,602,191
          - 706,393,1212,371,1217,184,1008,111,696,228

    garage:
      webui_url: "http://10.0.9.64/"
      ffmpeg:
        inputs:
          - path: rtsp://frigate:@10.0.9.64/Preview_01_main
            roles:
              - record
              - audio
          - path: rtsp://frigate:@10.0.9.64/Preview_01_sub
            roles:
              - detect
      detect:
        width: 1536
        height: 432
      motion:
        mask:
          - 289,181,495,168,579,109,531,0,171,0,112,134

    front:
      webui_url: "http://10.0.9.215/"
      ffmpeg:
        inputs:
          - path: rtsp://frigate:@10.0.9.215/Preview_01_main
            roles:
              - record
              - audio
          - path: rtsp://frigate:@10.0.9.215/Preview_01_sub
            roles:
              - detect
      detect:
        width: 1536
        height: 432

    corner:
      webui_url: "http://10.0.9.216/"
      ffmpeg:
        inputs:
          - path: rtsp://frigate:@10.0.9.216/Preview_01_main
            roles:
              - record
              - audio
          - path: rtsp://frigate:@10.0.9.216/Preview_01_sub
            roles:
              - detect
      detect:
        width: 1536
        height: 432

    back-doorbell:
      ffmpeg:
        inputs:
          - path: rtsp://admin:@10.0.9.47:88/videoMain
            roles:
              - record
              - audio
          - path: rtsp://admin:@10.0.9.47:88/videoSub
            roles:
              - detect
      detect:
        width: 1280
        height: 720
      motion:
        mask:
          - 177,66,63,121,45,222,64,313,297,310,325,198,297,81
          - 317,260,415,340,624,345,733,267,747,30,307,80
          - 1134,0,1169,113,1193,265,1205,383,1192,493,1047,419,671,118,527,0
          - 1199,432,1189,504,1168,595,1104,720,893,720,749,694,702,536,721,380,794,226
          - 0,354,0,510,99,577,170,626,243,635,288,595,312,537,266,371,227,245,128,260,56,274,0,222
```

### Relevant Frigate log output

```shell
2025-02-09 04:32:56.785251586  [2025-02-09 04:32:56] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-02-09 04:32:56.785793286  [2025-02-09 04:32:56] frigate.util.config            ERROR   : Failed to load config at /config/config.yml
2025-02-09 04:32:56.786020484  *************************************************************
2025-02-09 04:32:56.786024185  *************************************************************
2025-02-09 04:32:56.786028027  ***    Your config file is not valid!                     ***
2025-02-09 04:32:56.786033195  ***    Please check the docs at                           ***
2025-02-09 04:32:56.786036548  ***    https://docs.frigate.video/configuration/          ***
2025-02-09 04:32:56.786040738  *************************************************************
2025-02-09 04:32:56.786045068  *************************************************************
2025-02-09 04:32:56.786083342  ***    Config Validation Errors                           ***
2025-02-09 04:32:56.786085717  *************************************************************
2025-02-09 04:32:56.786088091  : Input should be a valid dictionary or instance of FrigateConfig
2025-02-09 04:32:56.786090885  *************************************************************
2025-02-09 04:32:56.786094727  ***    End Config Validation Errors                       ***
2025-02-09 04:32:56.786098009  *************************************************************
2025-02-09 04:32:57.077739112  [INFO] Service Frigate exited with code 1 (by signal 0)
```

### Operating system

K8s

### Install method

Helm Chart

### Network connection

Wired

### Camera make and model

multiple
