### DISCUSSION TITLE
Using Coral for detection and NVIDIA for encoding and Semantic Search

### DISCUSSION THREAD

**Discussion by lordratner** [blakeblackshear/frigate#16418] [Ask A Question] [answered]
Hi,

Like the title says, I have a Coral TPU for detection (working) and NVIDIA GPU for encoding streams (also working). 

WIth the update I want to run semantic search on the GPU, however I an getting an error referencing VINO, which suggests I need to use a different build. 

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/frigate/config:/config
      - /opt/appdata/frigate/db:/db
      - /mnt/nvr/frigate-new:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "1984:1984"
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "zzzzz"
      PLUS_API_KEY: zzzzz
      TZ: "America/Chicago"
```

That's my current Docker Compose file. I don't want to use the GPU for detection (the Coral works great) but I do want to use it for Semantic Search.

Should I change the build, or is there something in the Frigate configuration I can change to enable the already-working Nvidia GPU for Semantic Search?

Thanks,
Seth
