### DISCUSSION TITLE
Licence Plate Reader (LPR) - Future Feature Request.

### DISCUSSION THREAD

**Discussion by tubalainen** [blakeblackshear/frigate#16444] [Ideas]
It would be great if there would be a future release where the licence plate would be a possible text sensor in HA.

Lets hope I can inspire someone else to fiddle with this, I have been playing around with Gen AI in 0.15.

With the introduction of the new Generative AI feature in 0.15 can be used to read the licence plate. Depending on the model it is somewhat hit and miss. Ive played around with this a bit with mixed success. I could instruct the Generative AI to be more precise in its answer and then make a text sensor myself in HA based on the Gen AI output.

What ive done is making a special prompt for `car` and `person`:
```
....
genai:
  enabled: true
  provider: gemini
  api_key: xxxxxxxxxx
#  model: gemini-1.5-pro
  model: gemini-1.5-flash

cameras:
  cam9_uppfart:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/cam9_ch1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    genai:
      use_snapshot: false
#      prompt: "Analyze the {label} in these images from the {camera} security camera at the front door. Focus on the actions and potential intent of the {label}."
      object_prompts:
        car: Analyze the car in the image. Try to read the licence plate, car make
          and model and color of the car. Also describe any persons in the picture,
          describe the persons age and gender and clothing as well as any intent.
          Don't describe stationary objects or buildings.
        person: Briefly describe what you see in this image, but only if the image
          has an animal or a person in it, from my drivewat security camera. If it
          is a person, describe the persons age and gender and clothing as well as
          any intent. Don't describe stationary objects or buildings.
      objects:
        - person
        - car
      required_zones:
        - cam9_uppfart_uppfarten
        - cam9_uppfart_grasmattan
    zones:
      cam9_uppfart_uppfarten:
        coordinates:
          0.918,0.289,0.906,0.344,0.84,0.341,0.773,0.352,0.559,0.367,0.457,0.342,0.239,0.169,0,0.343,0,1,0.835,1,0.992,0.344
        inertia: 3
        loitering_time: 0
      cam9_uppfart_vagen:
        coordinates: 0.241,0.17,0.207,0.075,0,0.187,0,0.342
        inertia: 3
        loitering_time: 0
      cam9_uppfart_juni:
        coordinates: 805,150,521,0,0,92,0,398
      cam9_uppfart_grasmattan:
        coordinates:
          0.499,0,0.47,0.332,0.555,0.348,0.62,0.183,0.762,0.162,0.81,0.202,0.814,0.313,0.843,0.337,0.907,0.342,0.917,0.28,0.892,0.263,0.916,0.188,0.725,0.054,0.7,0.06
        inertia: 3
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - license_plate
        - amazon
        - postnord
        - dog
        - cat
        - deer
        - raccoon
        - fox
        - squirrel
        - rabbit
        - package
        - robot_lawnmower
        - postnord
        - amazon
      filters:
        person:
          min_area: 10000
          threshold: 0.8
          min_score: 0.7
        cat:
          min_area: 2000
          max_area: 23000
          threshold: 0.9
          min_score: 0.7
        car:
          min_area: 60000
          max_area: 1000000
          min_score: 0.7
          threshold: 0.9
    review:
      detections: {}
      alerts:
        required_zones:
          - cam9_uppfart_grasmattan
          - cam9_uppfart_uppfarten
.....
```

It is somewhat a "Hit and miss", but it works 90% of the times. Making the licence plate searchable.... If the car isnt too dirty... hehe.
<img width="954" alt="image" src="https://github.com/user-attachments/assets/6e1e8f43-8031-4259-9162-45f4e124696f" />

I have also tried running some image analyzing models locally via ollama with mixed results. The best one for me is: llava-phi3:q4_2k. I cannot detect the car make and model as good as Google.

```
genai:
  enabled: true
  provider: ollama
  base_url: http://192.168.xxx.xxx:11434
  model: socialnetwooky/llava-phi3:q4_2k
##  model: llava-phi3:3.8b
##  model: moondream:1.8b-v2-q8_0

```
