### DISCUSSION TITLE
[HW Accel Support]: Intel-qsv or intel-vaapi is used

### DISCUSSION THREAD

**Discussion by Imwithstupid007** [blakeblackshear/frigate#16455] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I just migrated from 0.14 to 0.15. Up until 0.14 Frigate used 
`ffmpeg:
  #hwaccel_args: preset-vaapi` for HW-acceleration on my system (N305).

In several post it was advised to use `hwaccel_args: preset-intel-qsv-h264` instead for HW-acceleration in 0.15. So, I did.
But when looking at the system metrics I see in the graph that intel-qsv is used (although without activity).

![Screenshot 2025-02-10 195623](https://github.com/user-attachments/assets/3c777140-53fd-4c0c-a1b4-03d6f09824d1)

But when opening the "hardware info" it seems that Intel-Vaapi is used. Is this correct?

> {"return_code":0,"stderr":"","stdout":"vainfo: VA-API version: 1.22 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP"}

### Version

0.15

### Frigate config file

```yaml
ui:
  time_format: 24hour
  strftime_fmt: '%d/%m/%Y %H:%M:%S'

mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

#logger:
#  default: info
#  logs:
#    frigate.record: debug

birdseye:
  enabled: false
  mode: continuous

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264
  #input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  sync_recordings: false
  retain:
    days: 10
    mode: all
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10
go2rtc:
  streams:
    tuinhuiscam:
      - rtsp://rtspuser:xxxx@192.168.1.64:554/Streaming/Channels/101
    tuinhuiscam_sub:
      - rtsp://rtspuser:xxxx@192.168.1.64:554/Streaming/Channels/102
    deurbel:
      - ffmpeg:http://192.168.1.66/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=rtspuser&password=xxxx#video=copy#audio=copy#audio=opus
    deurbel_sub:
      - ffmpeg:http://192.168.1.66/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=rtspuser&password=xxxx

cameras:
  tuinhuiscam: # geen output_args: geen audio
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/tuinhuiscam?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/tuinhuiscam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0.321,0.308,0.195,0.307,0,0,0
        - 1,0,1,1,0.962,1,0.858,0
        - 0.811,0.439,0.845,0.44,0.845,0.15,0.811,0.149
        - 0,0.323,0.077,0.291,0.082,1,0,1
    zones:
      tuin:
        coordinates: 0.961,1,0.873,0.164,0.388,0.166,0,0.324,0,1
        objects: person
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: tuin
  ####################################################################
  deurbel: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/deurbel
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/deurbel_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
        - bicycle
        - motorcycle
    motion:
      mask: 0,0,1,0,1,0.413,0,0.413
    zones:
      straat:
        coordinates: 0,1,1,1,1,0.414,0,0.414
        objects:
          - person
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: straat

version: 0.15-1
camera_groups: {}
```

### docker-compose file or Docker CLI command

```yaml
---
# https://github.com/blakeblackshear/frigate
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "160mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    #  - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_TO_APPDATA}/frigate/config.yml:/config/config.yml
      - ${PATH_TO_MOVIES}/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
--
```

### Relevant go2rtc log output

```shell
--
```

### FFprobe output from your camera

```shell
--
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision, Reolink

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-02-10 200037](https://github.com/user-attachments/assets/2831bbb1-6ffd-44ef-80d1-98bb04e84ede)

### Any other information that may be helpful

![Screenshot 2025-02-10 200228](https://github.com/user-attachments/assets/eeb5cb5d-6ec3-48fc-89f3-5a875e7d614c)
