### DISCUSSION TITLE
How can I improve Frigate video retrieval performance?

### DISCUSSION THREAD

**Discussion by szaske** [blakeblackshear/frigate#16456] [Ask A Question]
I'm a long time Frigate user and love the SW.  I have 4 4K cameras, and run Frigate in a docker container on it's own server. The server is Dell Optiplex 7050 with a Intel Core i7-7700 3.60GHz, 8GB RAM and video saved to a 4TB HD.  A good friend has been pressing me to abandon Frigate and move to the Ubitquiti's NVR system. His reason for switching is the only problem I've had with Frigate, which is poor performance when attempting to watch an older video clip.  I've been trying to figure out what the problem is.  Frigate loads live video great, but when I load video from history/search it can be very hit and miss.  Sometimes it loads very quickly and many other times the video never loads. I get the progress circle spinning and I wait for 10-20 seconds or longer and either the video finally appears or it never does. I'm using the new .15 rc2 build.  How can I troubleshoot this?  Are other people seeing this?  Step 1 is to determine if my HW is the problem, or perhap I've configured Frigate incorrectly.  I've read all I can about configuring Frigate.  I have a USB Coral, and a K620 Quadro card configured for HW accellerated video encoding and my SHM is set to 900M. It seems like the issue is my HD and I'm happy to switch to a faster solution like an SSD but want to hear from you all before I invest in new HW. Do I need a new SSD? More RAM? Something else?  If you seek for a video that's 5 days ago how long does it take before that video starts to play on your system? What about a video from 2 hours ago?

**Comment by NickM-27** [comment]
Video playback is basically instant for me, regardless of if it is recent (on ssd cache pool) or older (on hdd array). You should start by showing your config and also a screenshot of the network tab in the browser tools while trying to playback so we can see which part is taking so long. 

You also should definitely not have the database on an hdd

**Reply by szaske** [reply]
Here's my Docker config...as I'm guess it's where I'd be able to configure where the database is.

```
version: "3.9"
services:
  frigate:
    container_name: frigate_nvr_15
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
               - gpu
               - utility
               - compute
               - video
    shm_size: "900m"  
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # My dri devices are weird and my Intel, which I want to share,
      #  is the card1 and renderD129. So I force an odd mapping.
      #- /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD129:/dev/dri/renderD128
      #- /dev/dri/renderD129
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storageHDD/docker-storage/frigate/config:/config
      - /storageHDD/docker-storage/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971" # Authenticated UI and API access without TLS
      - "1984:1984" # go2rtc
```
Should I move my config volume to my boot SSD? It's 500GB in size. Or should I upgrade my video drive to be SSD?  I read that SSD are not good for NVR's as they write so much, which is why I went with a standard HD that was meant for NVRs. Maybe it's good enough just moving the DB to the faster drive.
