### DISCUSSION TITLE
ffmpeg go2rtc stream no longer works on 0.15.0

### DISCUSSION THREAD

**Discussion by billy-doyle** [blakeblackshear/frigate#16454] [Ask A Question]
Just upgraded this am to 0.15.0 (was on previous minor release), my original config for the go2rtc stream was this:

```yaml
go2rtc:
  streams:
    door_cam:
      - ffmpeg:rtsp://admin:password@10.0.0.15:8554/profile0#video=h264#raw=-vf crop=1296:730:504:200
```

which no longer works and now gives "error="streams: exec: [rtsp @ 0x558b627560] Unable to open RTSP for listening\nrtsp://admin:password@10.0.0.15:8554/profile0: Cannot assign requested address\n" stream=door_cam"

The following still works 
```yaml
go2rtc:
  streams:
    door_cam:
      - rtsp://admin:password@10.0.0.15:8554/profile0
```

however since this a peephole door camera it is not cropped how I want via ffmpeg. Did see in the release notes that ffmpeg is no longer on the PATH but not sure if it related.

How to fix to get the cropped go2rtc stream back?

**Comment by hawkeye217** [comment]
What is your full go2rtc config?

**Reply by NickM-27** [reply]
we need to see docker config as well

**Reply by billy-doyle** [reply]
```yaml
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  streams:
    door_cam:
      - rtsp://admin:password@10.0.0.15:8554/profile0

cameras:
  door_cam:
    detect:
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/door_cam
          roles:
            - detect
    motion:
      mask: 
        0.367,0.191,0.498,0.107,0.607,0.139,0.709,0.243,0.75,0.412,0.734,0.667,0.694,0.772,0.61,0.891,0.482,0.901,0.389,0.849,0.327,0.757,0.303,0.623,0.293,0.514,0.303,0.37,0.341,0.278
      threshold: 15
      contour_area: 10
      improve_contrast: true
version: 0.15-1
```

running in home assistant as an addon, so docker config is just whatever is in current ver of 0.15.0 addon
