### DISCUSSION TITLE
After the last add on update in Home Assistant Frigate records the object 'car' also from outside the specified zone.

### DISCUSSION THREAD

**Discussion by XVBinh** [blakeblackshear/frigate#16458] [General Support]
### Describe the problem you are having

After the last add on update in Home Assistant Frigate records the object 'car' also from outside the specified zone. The other objects look fine, like bicycle and person

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.117   # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user           # YOUR MQTT USERNAME
  password: pw         # YOUT MQTT PASSWORD
  stats_interval: 60

##########################################################################

go2rtc:
  streams:
    reolink:
      - rtsp://user:pw@192.168.1.196:554/h264Preview_01_sub
      - ffmpeg:rtsp://user:pw@192.168.1.196:554/h264Preview_01_sub#audio=pcm#audio=volume

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=40dB"

##########################################################################

cameras:

  reolink:
    ffmpeg:
      inputs:
                    ## CHANGE RTSP USERNAME AND PASSWORD

        - path: rtsp://user:pw@192.168.1.196:554/h264Preview_01_sub
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true

    zones:
      reolink_voortuin:
        coordinates: 
          0.297,0.996,0.67,0.996,0.883,1,0.76,0.92,0.683,0.854,0.522,0.704,0.494,0.715,0.46,0.713,0.404,0.723,0.38,0.665,0.311,0.667,0.188,0.658,0.161,0.657,0.075,0.645,0.09,0.758,0.15,0.996  # WATCH MY FRIGATE VIDEO SHOWING YOU WHAT THIS IS
        objects:
          - person
          - bicycle
          - car
          - motorcycle          
          - bus


        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 499,386,569,424,615,441,717,480,800,313,800,0,404,0,407,326              # WATCH MY FRIGATE VIDEO SHOWING YOU WHAT THIS IS

      threshold: 30
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones: reolink_voortuin

objects:
  track:
    - person
    - bicycle
    - motorcycle
    - bus
    - car
  filters:
    person:
      threshold: 0.7
    car:
      threshold: 0.5

audio:
  enabled: false
  listen:
    - breaking
    - gunshot
    - crack
    - honk


detect:
  width: 800
  height: 480
  stationary:
    interval: 60
    threshold: 15


snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 7
  required_zones:
    - reolink_voortuin

record:
  enabled: true
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 2
database:
  path: /config/frigate.db
review:
  alerts:
    required_zones:
      - reolink_voortuin

version: 0.15-1
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
.
```

### Object Detector

Other

### Network connection

Wired

### Camera make and model

reolink wifi doorbell

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/bfa0c2e3-ab53-4c13-883c-c582c3af75ae)
