### DISCUSSION TITLE
genai: Extra inputs are not permitted

### DISCUSSION THREAD

**Discussion by Jleagle** [blakeblackshear/frigate#16464] [Config Support] [answered]
### Describe the problem you are having

Trying to setup genai, working before, but after copying from the docs it wont boot.

Adding the below caused this issue:
```yaml
genai:
  enabled: "True"
  provider: "gemini"
  api_key: "{FRIGATE_GENAI_KEY}"
  model: "gemini-2.0-flash"

semantic_search: # Needed for genai to work
  enabled: True
  reindex: False
  model_size: small
```

### Version

ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
# https://docs.frigate.video/configuration/index

mqtt:
  host: "192.168.0.7"

genai:
  enabled: "True"
  provider: "gemini"
  api_key: "{FRIGATE_GENAI_KEY}"
  model: "gemini-2.0-flash"

semantic_search: # Needed for genai to work
  enabled: True
  reindex: False
  model_size: small

birdseye:
  enabled: false
  mode: "motion"

ffmpeg:
  # https://docs.frigate.video/configuration/hardware_acceleration
  # https://docs.frigate.video/configuration/ffmpeg_presets/
  hwaccel_args: "preset-intel-qsv-h264"
  input_args: "preset-rtsp-restream"
  output_args:
    record: "preset-record-generic-audio-aac"

objects:
  track:
    - "person"
    - "car"

record:
  enabled: true
  events:
    retain:
      mode: "active_objects"
      objects:
        person: 7
        car: 1

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_DRIVEWAY_USERNAME}:{FRIGATE_DRIVEWAY_PASSWORD}@192.168.0.12:554/Preview_01_main"
          roles:
            - "record"
        - path: "rtsp://{FRIGATE_DRIVEWAY_USERNAME}:{FRIGATE_DRIVEWAY_PASSWORD}@192.168.0.12:554/Preview_01_sub"
          roles:
            - "detect"

detectors:
  coral:
    type: "edgetpu"
    device: "pci"
    num_threads: 2
  #  cpu:
  #    type: "cpu"
  #    num_threads: 1
```

### Relevant Frigate log output

```shell
frigate  | 2025-02-10 21:12:05.766458389  *************************************************************
frigate  | 2025-02-10 21:12:05.766461237  *************************************************************
frigate  | 2025-02-10 21:12:05.766465216  ***    Your config file is not valid!                     ***
frigate  | 2025-02-10 21:12:05.766466676  ***    Please check the docs at                           ***
frigate  | 2025-02-10 21:12:05.766467610  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2025-02-10 21:12:05.766480186  *************************************************************
frigate  | 2025-02-10 21:12:05.766480992  *************************************************************
frigate  | 2025-02-10 21:12:05.766495936  ***    Config Validation Errors                           ***
frigate  | 2025-02-10 21:12:05.766496928  *************************************************************
frigate  | 2025-02-10 21:12:05.766516633  genai: Extra inputs are not permitted
frigate  | 2025-02-10 21:12:05.766519993  semantic_search: Extra inputs are not permitted
frigate  | 2025-02-10 21:12:05.766521176  *************************************************************
frigate  | 2025-02-10 21:12:05.766524326  ***    End Config Validation Errors                       ***
frigate  | 2025-02-10 21:12:05.766525359  *************************************************************
```

### Relevant go2rtc log output

```shell
xxx
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    image: "ghcr.io/blakeblackshear/frigate:stable"
    container_name: "frigate"
    hostname: "frigate"
    restart: "unless-stopped"
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - "/dev/dri/renderD128"       # for intel hwaccel, needs to be updated for your hardware
      - "/dev/apex_0:/dev/apex_0"   # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - "${HOME}/Media/Frigate:/media/frigate"
      - "./frigate:/config"
      - "/etc/localtime:/etc/localtime:ro"
    tmpfs:
      - "/tmp/cache"
    ports:
      - "1935:1935" # RTMP feeds
      - "5000:5000" # API
    environment:
      - "FRIGATE_GENAI_KEY"
      - "FRIGATE_DRIVEWAY_USERNAME"
      - "FRIGATE_DRIVEWAY_PASSWORD"
```

### Object Detector

Coral
