### DISCUSSION TITLE
[Support]: IP camera: no frames have been received, check error logs - issue after update 2025.2.0 of HA Core

### DISCUSSION THREAD

**Discussion by XalaTheShepard** [blakeblackshear/frigate#16474] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Dear all,

I have 5 IP camera's working flawless for multiple years in my Home Assistant setup.
As from HA Core 2025.2.0 and higher, one IP camera (Dahua) freezes every 2 minutes and give the following error message: no frames have been received, check error logs .
In the issue created in Go2RTC, I received the feedback that some other brands of camera's have the same issue (e.g. Reolink).
This videostream does also freeze in the Onvif integration, but does not freeze in Onvif Device Manager nor VLC.
Please find below the error messages related to the issue:

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:149
integration: go2rtc (documentation, issues)
First occurred: 4:45:08 PM (17 occurrences)
Last logged: 4:45:08 PM

github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:129 +0x68
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 3667
github.com/pion/webrtc/v3@v3.3.5/peerconnection.go:496 +0x16f

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:186
integration: go2rtc (documentation, issues)
First occurred: 4:45:09 PM (1 occurrences)
Last logged: 4:45:09 PM

Go2rtc unexpectedly stopped, server log:

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:156
integration: go2rtc (documentation, issues)
First occurred: 4:45:09 PM (22 occurrences)
Last logged: 4:45:09 PM

github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:129 +0x68
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 3667
github.com/pion/webrtc/v3@v3.3.5/peerconnection.go:496 +0x16f

### Steps to reproduce

1. Have Frigate up and running in HA Core 2025.1.X
2. Update to HA Core 2025.2.X
3. One or multiple IP camera's freezes every 2 minutes

### Version

0.15.0

### In which browser(s) are you experiencing the issue with?

All

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.0.251
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: Citizen27022017!
  stats_interval: 60

cameras:
  #simple camera example
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.0.241/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
    detect:
      height: 720
      fps: 5

    zones:
      beyondgate:
        coordinates: 0.109,0.343,0.464,0.116,0.995,0.521,0.994,0.999,0.267,0.999
        loitering_time: 0
      frontgate:
        coordinates: 0.1,0.203,0.192,0.154,0.185,0.062,0.461,0.115,0.111,0.336
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0.086,0.057,0.099,0.201,0.192,0.155,0.183,0
        - 0.18,0,0.992,0.009,0.996,0.476,0.646,0.209,0.456,0.105,0.249,0.046,0.184,0.056
    objects:
      mask:
        - 0.087,0.056,0.101,0.205,0.194,0.161,0.182,0
        - 0.181,0.001,0.186,0.056,0.245,0.043,0.443,0.099,0.647,0.208,0.995,0.468,0.994,0.007
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.0.221:554
          roles:
            - record
            - detect
    detect:
      height: 720
      fps: 5

    zones:
      TV_cabinet:
        coordinates: 0.002,0.457,0.518,0.103,0.525,0.598,0.134,0.956
        loitering_time: 0
        inertia: 3
      Sofa:
        coordinates: 0.102,0.987,0.572,0.548,0.855,0.733,0.771,0.994
        loitering_time: 0
      Diner_table:
        coordinates: 0.521,0.099,0.984,0.155,0.881,0.733,0.569,0.541,0.53,0.58
        loitering_time: 0
  hall:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.0.204:554
          roles:
            - record
            - detect
    detect:
      height: 720
      fps: 5

    zones:
      Entryhall:
        coordinates: 0,0.172,1,0.122,1,1,0.151,1,0.082,0.633
        loitering_time: 0
        inertia: 3
  garden:
    ffmpeg:
      inputs:
        - path: 
            rtsp://*****:*****@192.168.0.11/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
    detect:
      height: 720
      fps: 5

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 5
  detections:
    retain:
      days: 5
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

objects:
  track:
    - person
    - dog
    - cat
    - car
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 0
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.8
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
HASSOS
```

### Relevant Frigate log output

```shell
Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:149
integration: go2rtc (documentation, issues)
First occurred: 4:45:08 PM (17 occurrences)
Last logged: 4:45:08 PM

github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:129 +0x68
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 3667
github.com/pion/webrtc/v3@v3.3.5/peerconnection.go:496 +0x16f

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:186
integration: go2rtc (documentation, issues)
First occurred: 4:45:09 PM (1 occurrences)
Last logged: 4:45:09 PM

Go2rtc unexpectedly stopped, server log:

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:156
integration: go2rtc (documentation, issues)
First occurred: 4:45:09 PM (22 occurrences)
Last logged: 4:45:09 PM

github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:129 +0x68
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 3667
github.com/pion/webrtc/v3@v3.3.5/peerconnection.go:496 +0x16f
```

### Relevant go2rtc log output

```shell
Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:149
integration: go2rtc (documentation, issues)
First occurred: 4:45:08 PM (17 occurrences)
Last logged: 4:45:08 PM

github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:129 +0x68
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 3667
github.com/pion/webrtc/v3@v3.3.5/peerconnection.go:496 +0x16f

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:186
integration: go2rtc (documentation, issues)
First occurred: 4:45:09 PM (1 occurrences)
Last logged: 4:45:09 PM

Go2rtc unexpectedly stopped, server log:

Logger: homeassistant.components.go2rtc.server
Source: components/go2rtc/server.py:156
integration: go2rtc (documentation, issues)
First occurred: 4:45:09 PM (22 occurrences)
Last logged: 4:45:09 PM

github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:129 +0x68
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 3667
github.com/pion/webrtc/v3@v3.3.5/peerconnection.go:496 +0x16f
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Dahua

### Screenshots of the Frigate UI's System metrics pages

![Schermafbeelding 2025-02-09 224019](https://github.com/user-attachments/assets/4f531620-19b7-4db2-b2de-a533b6c9a99a)
