### DISCUSSION TITLE
[Support]: container crash since dev build fa30074

### DISCUSSION THREAD

**Discussion by xfaustus** [blakeblackshear/frigate#16475] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Latest working dev container: dc79af2
The issue is experiencing since: fa30074

I tried to compare what is changed in the commit between builds. The most relevant changes i see is upgrade from python 3.9 to 3.11 which could lead to this issue.

How I can help trying to have more debug info and logs?

### Steps to reproduce

1. try run container fa30074
2.
3.
...

### Version

fa30074

### Frigate config file

```yaml
---
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:fa30074
# fa30074: NO 08.02
# dc79af2: OK

    shm_size: "512mb" # 160mb it's enough
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config/:rw
      - /mnt/data/frigate:/media/frigate
      - type: tmpfs # Optional:  memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1024mb
    ports:
      - "5000:5000" # frigate port
      - "8554:8554" # RTSP feeds
      - "8555:8555" # WebRTC
      - "8971:8971" # frigate with auth
      - "1984:1984" # go2rtc
    environment:
      YOLO_MODELS: ""
      PLUS_API_KEY: "*************************************"
```

### Relevant Frigate log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2025-02-11 09:20:48.680070686  [INFO] Preparing new go2rtc config...
frigate  | 2025-02-11 09:20:48.682183771  [INFO] Preparing Frigate...
frigate  | 2025-02-11 09:20:48.685747873  [INFO] Starting NGINX...
frigate  | 2025-02-11 09:20:48.694754270  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2025-02-11 09:20:48.851316499  [INFO] Starting Frigate...
frigate  | 2025-02-11 09:20:49.522890907  [INFO] Starting go2rtc...
frigate  | 2025-02-11 09:20:49.634527051  09:20:49.634 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2025-02-11 09:20:49.634551954  09:20:49.634 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2025-02-11 09:20:49.635277307  09:20:49.635 INF [api] listen addr=:1984
frigate  | 2025-02-11 09:20:49.635351214  09:20:49.635 INF [rtsp] listen addr=:8554
frigate  | 2025-02-11 09:20:49.635666783  09:20:49.635 INF [webrtc] listen addr=:8555/tcp
frigate  | 2025-02-11 09:20:50.136623233  [INFO] Service Frigate exited with code 256 (by signal 4)
```

### Relevant go2rtc log output

```shell
---
```

### Operating system

Ubuntu 22.04.5 LTS

### CPU
Intel Pentium Silver N6000

### Install method

Docker Compose

### Network connection

Wired
