### DISCUSSION TITLE
[Support]: Running Frigate without/missing storage

### DISCUSSION THREAD

**Discussion by wildchai** [blakeblackshear/frigate#16470] [General Support]
### Describe the problem you are having

Hi,
Sometimes I need to restart frigate or my server and the LXC fails to starts due to missing recording storage. My frigate storage is shared via SMB/CIF on open media vault. I understand it takes a longer time to start.

Is there a way to make frigate start even with its missing storage?

Thanks.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Version 133.0.6943.60 (Official Build) (64-bit)

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.3.205
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi

semantic_search:
  enabled: True
  reindex: False
  
go2rtc:
  streams:
    Porch:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.61:554/axis-media/media.amp?videocodec=h264
    Hall:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.65/axis-media/media.amp?videocodec=h264
    Kitchen:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.66/axis-media/media.amp?videocodec=h264
    2nd_Hall:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.99:554/axis-media/media.amp?videocodec=h264
    Backyard:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.63:554/axis-media/media.amp?videocodec=h264
    Left_Garden:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.64:554/axis-media/media.amp?videocodec=h264
    Right_Garden:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.3.62:554/axis-media/media.amp?videocodec=h264

cameras:
  ####### PORCH #######
  Porch:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    record:
      enabled: true
      retain:
        days: 14
        mode: all

    motion:
      mask:
        - 0.563,0.002,0.544,0.048,0.524,0.07,0.537,0.167,0.445,0.165,0.445,0.063,0.419,0
        - 0.851,0.005,0.966,0.002,0.967,0.047,0.85,0.048
        - 0.252,0,0.251,0.035,0.263,0.057,0.264,0.107,0.313,0.101,0.311,0.035,0.318,0.004
        - 0.687,0,0.679,0.026,0.695,0.077,0.711,0.101,0.739,0.113,0.774,0.122,0.79,0.092,0.783,0.019,0.759,0.001
    objects:
      filters:
        car:
          mask:
            - 0.551,0.033,0.698,0.07,0.721,0.126,0.599,0.159,0.504,0.128
            - 0.205,0.371,0.347,0.219,0.518,0.27,0.937,0.643,0.891,0.78,0.818,1,0.432,1
            - 0.311,0.033,0.462,0.034,0.464,0.113,0.312,0.081
      track:
        - person
        - dog
        - cat
        - car
        - motorcycle

    detect:
      width: 1280
      height: 720
      fps: 5

    zones:
      porch_entry:
        coordinates: 0.082,0.494,0.21,0.436,0.415,1,0.17,1
        loitering_time: 0
        objects:
          - person
          - dog
      porch_driveway:
        coordinates: 
          0.625,0.273,0.442,0.177,0.439,0.237,0.719,0.451,0.926,0.645,0.959,0.52,0.772,0.367
        inertia: 3
        loitering_time: 0
      porch_main:
        coordinates: 0.211,0.433,0.505,0.292,0.665,0.411,1,0.716,1,1,0.418,0.999
        loitering_time: 0
        objects:
          - dog
          - cat
          - person
      porch_garden:
        coordinates: 0.092,0.299,0.12,0.475,0.301,0.39,0.507,0.294,0.449,0.237,0.28,0.284,0.274,0.223
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones: porch_driveway

 ######### HALL #############       
  Hall:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/Hall
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - 0.304,0.051,0.303,0.011,0.001,0.011,0.001,0.054
        - 0.899,0.242,0.876,0.334,0.795,0.247,0.818,0.157
    objects:
      track:
        - person
        - dog

      mask: 0.818,0.156,0.797,0.247,0.877,0.334,0.896,0.244

    detect:
      height: 720
      width: 1280
      fps: 5

    zones:
      hall_door:
        coordinates: 0.709,0,0.686,0.186,0.736,0.225,0.762,0.023
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: hall_door

######### KITCHEN ############          
  Kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    objects:
      track:
        - person
        - dog

    detect:
      height: 720
      width: 720
      fps: 5

    zones:
      kitch_back_door:
        coordinates: 0.231,0.18,0.321,0.134,0.425,0.345,0.36,0.348
        loitering_time: 0
        objects: person
    motion:
      mask: 0.523,0.815,0.612,0.804,0.654,0.922,0.567,0.943,0.559,0.862,0.531,0.866
    review:
      alerts:
        required_zones: kitch_back_door

######### 2ND HALL ############
  2nd_Hall:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/2nd_Hall
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    detect:
      height: 1280
      width: 720
      fps: 5

    motion:
      mask: 0.002,0,0.004,0.03,1,0.034,1,0
    zones:
      upper_window:
        coordinates: 0.874,0.526,0.916,0.581,0.996,0.532,0.99,0.444
        loitering_time: 0
    review:
      alerts:
        required_zones: upper_window

####### BACKYARD #######
  Backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record

    objects:
      track:
        - person

    detect:
      height: 1280
      width: 720
      fps: 5

    motion:
      mask:
        - 0.777,0.086,0.849,0.075,0.837,0.02,1,0.074,1,0.125,1,0.235,0.76,0.147
        - 0.104,-0.001,0.104,0.016,0.224,0.016,0.218,0.001
    zones:
      back_home:
        coordinates: 
          0.229,0.025,0.373,0.042,0.43,0.18,0.505,0.427,0.638,0.766,0.72,1,0.042,1,0.028,0.434,0.105,0.144
        loitering_time: 0
        inertia: 3
      back_walk:
        coordinates: 
          0.378,0.038,0.394,0.103,0.457,0.242,0.547,0.506,0.744,1,1,1,1,0.589,0.842,0.371,0.958,0.382,0.913,0.328,0.825,0.311,0.764,0.307,0.521,0.074
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: back_walk
      detections:
        required_zones: back_home

####### Left Garden #######
  Left_Garden:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/Left_Garden
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - motorcycle
        - bicycle


      filters:
        car:
          mask: 0.119,0.15,0.322,0.147,0.335,0.193,0.119,0.195
    detect:
      width: 720
      height: 1280
      fps: 5

    motion:
      mask: 
        0.22,0.109,0.234,0.045,0.265,0.028,0.472,0.037,0.677,0.062,0.679,0.139,0.669,0.179,0.397,0.159,0.253,0.144
      threshold: 32
      contour_area: 12
      improve_contrast: 'false'
    zones:
      left_home:
        coordinates: 0.096,0.22,0.329,0.225,0.381,0.229,0.487,0.353,1,0.73,0.994,0.995,0.044,0.998
        loitering_time: 0
        objects:
          - person
          - dog
        inertia: 3
      left_neighbor:
        coordinates: 0.393,0.219,0.507,0.229,0.659,0.274,1,0.409,0.996,0.725,0.497,0.356
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: left_home

####### RIGHT Garden #######
  Right_Garden:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/Right_Garden
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog

    detect:
      width: 720
      height: 1280
      fps: 5

    motion:
      mask: 
        0.204,0,0.417,0.012,0.627,0.056,0.601,0.088,0.575,0.113,0.431,0.076,0.365,0.069,0.18,0.055



    zones:
      right_person:
        coordinates: 0.156,0.089,0.534,0.163,1,0.424,1,1,0,1,0,0.35
        loitering_time: 0
        objects: person

        inertia: 3
snapshots:
    # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
    # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
      #height: 175
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
    # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70

record:
  enabled: true
  retain:
    days: 21
    mode: motion
  alerts:
    retain:
      days: 21
      mode: motion
  detections:
    retain:
      days: 21
      mode: motion

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

version: 0.15-1
```

### Relevant Frigate log output

```shell
No errors
```

### Relevant go2rtc log output

```shell
No errors
```

### FFprobe output from your camera

```shell
No issues
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:0.15.0-rc2
    #image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    devices:
      - /dev/dri/renderD128
    shm_size: "400mb"
    volumes:
      - ./config:/config
      #- ./storage:/media/frigate
      - /cctv/cctv:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "5000:5000"
    environment:
      TZ: Asia/Kuala_Lumpur
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

AXIS Cameras
