### DISCUSSION TITLE
[Config Support]: Extra Inputs Not Supported

### DISCUSSION THREAD

**Discussion by CommittotheIndian** [blakeblackshear/frigate#16494] [Config Support] [answered]
### Describe the problem you are having

I receive the following error when adding record.alerts or record.detections in config even though the option for alerts & detections is clearly listed in the sample config.

```
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
```

```
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
record.alerts
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;retain&#39;: {&#39;days&#39;: 1, &#39;mode&#39;: &#39;active_objects&#39;}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
```

### Version

0.14

### Frigate config file

```yaml
############################################################
#############      GLOBAL    SETTINGS          #############
############################################################
version: 0.14

#############
### MQTT ####
#############
mqtt:
  enabled: true
  host: 10.10.10.10
  port: 1883
  user: REDACTED
  password: REDACTED

#################
### DETECTORS ###
#################
detectors:
  coral:
    type: edgetpu
    device: usb
  # coral1:
  #   type: edgetpu
  #   device: pci:0
  # coral2:
  #   type: edgetpu
  #   device: pci:1


###############
### REVIEWS ###
###############
review:
  alerts:
    labels:
      - car
      - person
      - bicycle
      - truck


#################
### RECORDING ###
#################
record:
  enabled: true
  retain:
    days: 0
    mode: active_objects
#   alerts:
#     retain:
#       days: 1
#       mode: active_objects
#   detections:
#     retain:
#       days: 1
#       mode: all

################
### SNAPSHOT ###
################
snapshots:
  enabled: true
  retain:
    default: 2

################
### DATABASE ###
################
database:
  path: /config/frigate.db

###############
### OBJECTS ###
###############
objects:
  track:
    - person
    - car
    - truck
    - bicycle

############################################################
#############      CAMERA    SETTINGS          #############
############################################################

go2rtc:
  streams:
    doorbell:
      - ffmpeg:http://10.200.200.158/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
      #- rtsp://10.200.200.158/Preview_01_sub
    doorbell_sub:
      - ffmpeg:http://10.200.200.158/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=BlueIris&password=REDACTED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"


###########  cAMERA  ############
cameras:

################
### DOORBELL ###
################

  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED:@REDACTED@10.200.200.158:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    motion:
      mask: 0,0,0,0.485,1,0.488,1,0
    zones:
      sidewalk:
        coordinates: 
          0.84,0.627,0.787,0.618,0.696,0.629,0.655,0.63,0.577,0.627,0.519,0.629,0.442,0.625,0.369,0.619,0.303,0.619,0.267,0.629,0.234,0.628,0.189,0.627,0.143,0.627,0.093,0.634,0.059,0.649,0.024,0.662,0.064,0.834,0.117,1,0.845,0.994
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: sidewalk

################
### DRIVEWAY ###
################

  driveway:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://REDACTED:REDACTED@10.200.200.30/H264/ch1/sub/av_stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - truck
    motion:
      mask: 
        0.05,0.347,0.111,0.298,0.2,0.214,0.255,0.241,0.321,0.233,0.353,0.226,0.38,0.182,0.616,0.218,0.592,0.265,0.935,0.369,1,0.404,1,0,0,0,0,0.29
    zones:
      just_driveway:
        coordinates: 0.595,0.23,0.391,0.516,0.22,0.391,0.265,0.33,0.362,0.227,0.385,0.2
        loitering_time: 0
        objects:
          - car
          - truck
        inertia: 3
      driveway_yard:
        coordinates: 
          0.053,0.363,0.132,0.305,0.208,0.26,0.267,0.259,0.317,0.254,0.442,0.282,0.584,0.304,0.675,0.317,0.773,0.348,0.863,0.381,0.922,0.405,0.939,0.418,1,0.544,0.996,0.995,0.777,0.996,0.812,0.801,0.392,0.518,0.203,0.376,0.098,0.438
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - just_driveway
          - driveway_yard

################
### FLAGPOLE ###
################

  flagpole:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://REDACTED:REDACTED@10.200.200.20/H264/ch1/sub/av_stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - truck
    motion:
      mask: 
        -0.001,0.577,0.271,0.344,0.391,0.265,0.443,0.265,0.496,0.273,0.735,0.344,0.752,0.387,0.791,0.415,0.809,0.414,0.861,0.34,0.947,0.354,0.966,0.182,0.883,0,0,0
    zones:
      just_driveway2:
        coordinates: 0.207,0.422,0,0.604,-0.001,0.736,0.002,0.998,0.678,0.997,0.724,0.902,0.416,0.615
        loitering_time: 0
        inertia: 3
        objects:
          - car
          - truck
      flagpole_yard:
        coordinates: 
          0.493,0.302,0.276,0.477,0.098,0.641,0.051,0.675,0.008,0.709,0.004,0.994,0.68,0.997,0.745,0.866,0.723,0.848,0.755,0.722,0.778,0.548,0.762,0.52,0.757,0.476,0.787,0.43,0.709,0.363,0.641,0.34
        loitering_time: 0
        objects: person
```

### Relevant Frigate log output

```shell
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
record.alerts
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;retain&#39;: {&#39;days&#39;: 1, &#39;mode&#39;: &#39;active_objects&#39;}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker_volumes/config:/config
      - ~/docker_volumes/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: REDACTED
```

### Object Detector

Coral
