### DISCUSSION TITLE
[Camera Support]: Google Nest

### DISCUSSION THREAD

**Discussion by Gooshy** [blakeblackshear/frigate#16493] [Camera Support]
### Describe the problem you are having

Hi,
I'm looking for options on what is the best way to integrate Google Nest cameras with Frigate.  I have previously tried using the m3u8 stream that can be found in the public share of a camera.   Using the m3u8 led to a lot of stutter, 10 frames would play very quickly then a pause and then another quick succession of frames.  

I've started looking at the go2rtc option and using the nest: integration, I've not fuly gone down the rabbit whole to get my refresh token and deviceid to make it work yet.

Whats the best approach?

### Version

0.15

### What browser(s) are you using?

Brave v1.75.175

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.147
  user: scott
  password: <PASSWORD>



detectors:
  onnx_0:
    type: onnx

objects:
  track:
    - person
    - car
    - dog
    - package

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
model:
  path: plus://<MODEL_ID>

go2rtc:
  streams:
    backgarden:
      - ffmpeg:http://192.168.1.135/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<PASSWORD>!#video=copy#audio=copy#audio=opus
    backgarden_sub:
      - ffmpeg:http://192.168.1.135/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<PASSWORD>

cameras:
  backgarden:
    ffmpeg:
      global_args: -threads 4
      inputs:
        - path: rtsp://127.0.0.1:8554/backgarden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backgarden_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - nobuffer
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    snapshots:
      enabled: true
      retain:
        default: 7
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0.232,0.06,0.008,0.417,-0.001,0.002,0.243,0.002
  frontgarden:
    ffmpeg:
      global_args: -threads 4
      inputs:
        - path: https://stream-eu1-charlie.dropcam.com:443/nexus_aac/<STREAMID>/playlist.m3u8?public=<STREAM>
          roles:
            - detect
            - record
    motion:
      mask:
        - 0.554,0.005,0.344,0.114,0.185,0.237,0,0.425,0.001,0
        - 0.874,0.464,0.878,0.635,0.998,0.449,0.996,0.26
        - 0.944,0.563,0.958,0.667,0.984,0.646,0.975,0.545
        - 0.723,0.721,0.651,0.803,0.661,0.697,0.741,0.629
    zones:
      Driveway:
        coordinates: 0.25,0.189,0.576,0.688,0.667,0.489,0.642,0.454,0.716,0.291,0.503,0.025
        loitering_time: 0
        inertia: 3
      FrontDoor:
        coordinates: 
          0.59,0.854,0.537,0.772,0.574,0.688,0.315,0.305,0.27,0.602,0.36,0.779,0.231,0.991,0.43,0.991,0.456,0.956,0.489,0.995,0.544,0.991
        loitering_time: 0
    objects:
      mask:
        - 0.886,0.479,0.885,0.616,1,0.435,0.998,0.272
        - 0.945,0.568,0.956,0.658,0.982,0.642,0.973,0.549
        - 0.741,0.628,0.663,0.704,0.648,0.8,0.72,0.723
        - 0.938,0.035,0.868,0.205,0.868,0.311,0.975,0.096
    review:
      alerts:
        required_zones:
          - Driveway
          - FrontDoor
  frontdoor:
    ffmpeg:
      global_args: -threads 4
      inputs:
        - path: https://stream-eu1-bravo.dropcam.com:443/nexus_aac/<STREAM_ID>/playlist.m3u8?public=<STREAM>
          roles:
            - detect
            - record
    motion:
      threshold: 25
      contour_area: 100
      improve_contrast: true
      mask: 
        0.461,0.531,0.547,0.452,0.6,0.422,0.6,0.349,0.547,0.333,0.506,0.323,0.507,0.182,0.481,0.18,0.492,0.329,0.466,0.265,0.46,0.333,0.395,0.27,0.359,0.306,0.344,0.361,0.339,0.402,0.365,0.45,0.418,0.512
    snapshots:
      enabled: true
      retain:
        default: 7
    zones:
      Path:
        coordinates: 
          0.511,0.603,0.531,0.629,0.398,0.698,0.397,0.802,0.296,0.804,0.322,0.991,0.783,0.995,0.744,0.932,0.828,0.871
        loitering_time: 0
        objects: person
      Driveway:
        coordinates: 0.505,0.593,0.877,0.529,0.825,0.853
        loitering_time: 0
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

Other

### Network connection

Wired

### Camera make and model

Google Nest IQ Outdoor, Google Nest Wired Doorbell

### Screenshots of the Frigate UI's System metrics pages

N/A
