### DISCUSSION TITLE
[Camera Support]: RTSP Stream has a glitch on the bottom half when streamed in frigate, but not VLC

### DISCUSSION THREAD

**Discussion by emman-plante** [blakeblackshear/frigate#16496] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When my Wyze Camera v3 is connected to Frigate Docker (unraid).

Viewing the rtsp stream on vlc shows nothing out the ordinary. through frigate I get the problem. This happens multiple time a minute, always triggering the events and detections.

I have 2 reolink cameras without this issue

in the video: Left is VLC right is frigate

https://github.com/user-attachments/assets/41ce56c2-ad19-4648-b1d1-310e00012ed8

### Steps to reproduce

1. add rstp stream to frigate

### Version

0.15.0-cea210d

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    Garage:
      - rtsp://<USER>:<PASSWORD>@192.168.2.197:8554/video1_unicast
cameras:
  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
    objects:
      track:
        - person
        - car
detectors:
  coral:
    type: edgetpu
    device: pci

objects:
  track:
    - person
    - bicycle
    - car
    - mortorcycle
    - bus
    - cat
    - dog


record:
  enabled: true
  retain:
    days: 28
    mode: all
  events:
    retain:
      default: 365
      mode: active_objects


version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant Frigate log output

```shell
Nothing specific. all mqtt logs.


This seems to happen sometimes (not at the same time as the error) which i think should be relevant:

[h264 @ 0x14b334b43580] error while decoding MB 91 63, bytestream -65
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Wyze v3

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/f565d868-2457-42d7-86ad-b729580df176)

**Comment by hawkeye217** [comment, marked as answer]
This is not a Frigate bug.

See the FAQ about streams in VLC: https://docs.frigate.video/troubleshooting/faqs/#my-rtsp-stream-works-fine-in-vlc-but-it-does-not-work-when-i-put-the-same-url-in-my-frigate-config-is-this-a-bug

The error message is typical of bad stream data from the camera. You may see improvement if you use the ffmpeg module with go2rtc:

```
go2rtc:
  streams:
    Garage:
      - ffmpeg:rtsp://<USER>:<PASSWORD>@192.168.2.197:8554/video1_unicast
```
