### DISCUSSION TITLE
[Config Support]: I can't get my frigate to detect dogs

### DISCUSSION THREAD

**Discussion by patchido** [blakeblackshear/frigate#16508] [Config Support] [answered]
### Describe the problem you are having

I configured my frigate to be able to detect dogs, but somehow it doesnt do anything.

### Version

0.15-1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.100.57
  user: ***************
  password: '**********'

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: all

review:
  detections:
    labels:
      - person
      - dog

go2rtc:
  streams:
    Timbre_sub:
      - rtsp://*************@192.168.100.89:554/h264Preview_01_sub
      - ffmpeg:rtsp://************@192.168.100.89:554/h264Preview_01_sub#audio=pcm#audio=volume
    Timbre:
      - rtsp://*************@192.168.100.89:554/h264Preview_01_main
      - ffmpeg:***************@192.168.100.89:554/h264Preview_01_main#audio=pcm#audio=volume
    Sala:
      - rtsp://*********@192.168.100.10:554/ch0
      - ffmpeg:Sala#audio=opus
    Sala_sub:
      - rtsp://**********@192.168.100.10:554/ch1
      - ffmpeg:Sala_sub#audio=opus
    Cochera:
      - rtsp://********@192.168.100.98:554/ch0
      - ffmpeg:Cochera#audio=opus
    Cochera_sub:
      - rtsp://**********@192.168.100.98:554/ch1
      - ffmpeg:Cochera_sub#audio=opus
    Sara:
      - rtsp://************@192.168.100.86:554/stream1
      - ffmpeg:Sara#audio=opus
    Sara_sub:
      - rtsp://****************@192.168.100.86:554/stream2
      - ffmpeg:Sara_sub#audio=opus
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

cameras:
  Timbre:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/Timbre
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Timbre_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true

    motion:
      mask:
        - 0,0,0,0.055,0.344,0.054,0.343,0
        - 0.566,0.001,0.597,0.384,0.684,0.498,0.818,0.476,0.947,0.309,0.998,0.224,1,0.004
      threshold: 44
      contour_area: 10
      improve_contrast: true
  Sara:
    onvif:
      host: 192.168.100.86
      port: 2020
      user: pato.llaguno
      password: Pato745477
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/Sara
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Sara_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true
    motion: {}
  Sala:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/Sala
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Sala_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.229,0.301,0.435,0.296,0.408,0.026,0.269,0.086,0.199,0.121
        - 0,0,0.195,0,0.199,0.04,0,0.099
    zones:
      Comedor:
        coordinates: 0.739,0.399,0.753,1,0.994,0.96,1,0.512,1,0,0.814,0
        loitering_time: 0
        inertia: 3
      pasillo:
        coordinates: 0.639,0.242,0.612,0.526,0.716,0.55,0.791,0.004,0.646,0.004
        loitering_time: 0
        inertia: 3
  Cochera:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/Cochera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Cochera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask: 0,0,0.194,0,0.196,0.048,0,0.047
  Pan:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://homeassistant.local:8554/pan
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://homeassistant.local:8554/pan-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true
version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
N/a
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/a
```

### Object Detector

Coral
