### DISCUSSION TITLE
[Support]: Explore page infinite loading

### DISCUSSION THREAD

**Discussion by dnestico** [blakeblackshear/frigate#16507] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I just updated to Frigate 15 and enabled semantic search and the explore page is now infinitely loading and is inaccessible.
<img width="996" alt="Screenshot 2025-02-11 at 4 43 34 PM" src="https://github.com/user-attachments/assets/781e66fb-8565-4d72-97ef-486e98ab4277" />

### Steps to reproduce

1. Update to Frigate 15
2. Enable semantic search
3. Go to explore page
...

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

Arc Browser (chromium)

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate:5000/api/config/schema

mqtt:
  enabled: true
  host: 192.168.2.176
  user: mqtt
  password: mqtt
  port: 1883
  topic_prefix: frigate
  stats_interval: 60

go2rtc:
  streams:
    porch:
      - rtsp://admin:admin@192.168.2.44/live
      - ffmpeg:porch#audio=aac#audio=opus
    driveway:
      - rtsp://admin:admin@192.168.2.30/live
      - ffmpeg:driveway#audio=aac#audio=opus
    garage:
      - rtsp://admin:admin@192.168.2.31/live
      - ffmpeg:garage#audio=aac#audio=opus
  webrtc:
    candidates:
      - 192.168.2.176:8555
      - stun:8555

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
    frigate.app: error
    frigate.edgetpu: error

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  porch:
    ffmpeg:
      inputs:
        # - path: rtsp://admin:admin@192.168.2.44/live
        - path: rtsp://127.0.0.1:8554/porch
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    motion:
      improve_contrast: 'true'
      mask:
        - 0.839,0.678,0.877,0.449,0.899,0.281,0.909,0,1,0,1,1,0.77,1
        - 0,0.261,0,0.544,0.397,0.226,0.376,0,0,0
        - 0.255,0.513,0.259,0.656,0.191,0.734,0.098,0.571,0.159,0.41
        - 0.394,0.371,0.465,0.751,0.409,0.82,0.233,0.754,0.256,0.374
        - 0.296,1,0.267,0.923,0.086,0.778,0.06,0.84,0.1,1
        - 0.569,0.589,0.49,0.572,0.439,0.622,0.41,0.783,0.486,0.824,0.533,0.821,0.597,0.748
      threshold: 35
      contour_area: 8
    zones:
      porch_deck:
        coordinates: 
          0.307,1,0.322,0.948,0.386,0.832,0.436,0.826,0.494,0.835,0.539,0.841,0.595,0.79,0.609,0.73,0.752,0.646,0.807,0.812,0.764,1,0.575,0.996
        objects:
          - person
          - dog
        filters:
          person:
            threshold: 0.80
          dog:
            threshold: 0.81
        inertia: 2
        loitering_time: 0
      porch_stairs:
        coordinates: 0.318,0.793,0.383,0.82,0.295,0.979,0.27,0.911,0.214,0.87,0.272,0.782
        objects: person
        filters:
          person:
            threshold: 0.81
        inertia: 3
        loitering_time: 0
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 10
      detections:
        retain:
          days: 2
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
      timestamp: false
      retain:
        default: 7
      required_zones:
        - porch_deck
        - porch_stairs
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true
    review:
      alerts:
        required_zones:
          - porch_deck
          - porch_stairs
  driveway:
    ffmpeg:
      inputs:
        # - path: rtsp://admin:admin@192.168.2.30/live
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        car:
          threshold: 0.79
          mask:
            - 1478,444,1621,651,1656,1080,1920,1080,1920,0,0,0,0,1080,521,1080,605,488
        person:
          mask: 0,0,0,0,1,0,1,1,0.868,1,0.684,0.413,0.305,0.419,0.268,1,0,1
          threshold: 0.80
    motion:
      mask:
        - 0.355,0,0,0,0,1,0.248,1
        - 0.24,1,0.273,0.56,0.803,0.512,0.877,1,1,1,1,0,0,0,0,1
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
    zones:
      driveway_path:
        coordinates: 904,1080,827,398,567,402,457,1080
        objects:
          - person
#          - dog
#          - cat
        filters:
          person:
            threshold: 0.81
#          dog:
#            threshold: 0.8
#          cat:
#            threshold: 0.8
      driveway_pavement:
        coordinates: 1656,1080,1660,1005,1755,997,1495,427,817,431,864,1080
        objects:
          - person
#          - dog
#          - cat
        filters:
          person:
            threshold: 0.80
#          dog:
#            threshold: 0.8
#          cat:
#            threshold: 0.8
      driveway_car:
        coordinates: 0.582,0.546,0.799,0.525,0.846,0.86,0.564,0.876
        objects: car
        filters:
          car:
            threshold: 0.7
        inertia: 3
        loitering_time: 0
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 10
      detections:
        retain:
          days: 2
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 7
      required_zones:
        - driveway_pavement
        - driveway_path
        - driveway_car
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true
    review:
      alerts:
        required_zones:
          - driveway_pavement
          - driveway_path
          - driveway_car
  garage:
    ffmpeg:
      inputs:
        # - path: rtsp://admin:admin@192.168.2.31/live
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    motion:
      improve_contrast: true
      mask:
        - 0.374,0,0.328,0.231,0.314,0.495,0.321,1,0,1,0,0
        - 0.327,0.226,0.324,0.315,0.573,0.322,0.586,0.136,0.602,0,0.374,0
        - 0,0.932,0.402,0.962,0.53,0.948,0.644,0.895,0.805,0.782,0.95,0.642,1,0.696,1,1,0,1
        - 1,0.581,1,0.68,0.951,0.63,0.882,0.695,0.747,0.4,0.59,0.159,0.602,0,1,0
    zones:
      garage_floor:
        coordinates: 
          0.33,0.94,0.545,0.926,0.773,0.788,0.699,0.599,0.592,0.331,0.334,0.331,0.326,0.569
        objects:
          - person
          - dog
        filters:
          person:
            threshold: 0.76
          dog:
            threshold: 0.79
        inertia: 2
        loitering_time: 0
      garage_car:
        coordinates: 0.641,0.482,0.706,0.688,0.352,0.719,0.347,0.479
        objects: car
        filters:
          car:
            threshold: 0.75
        inertia: 3
        loitering_time: 0
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 10
      detections:
        retain:
          days: 2
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 7
      required_zones:
        - garage_car
        - garage_floor
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true
    review:
      alerts:
        required_zones:
          - garage_car
          - garage_floor
  luna:
    ffmpeg:
      inputs:
        - path: rtsp://rtspcam:admin@192.168.2.105/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - mouse
        # - dog
      filters:
        # dog:
        #   threshold: 0.7
        mouse:
          threshold: 0.6
        person:
          threshold: 0.8
#    motion:
#      mask:
#        - 1252,720,1242,671,1100,665,1100,720
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 10
      detections:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 10
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
      timestamp: false
      retain:
        default: 7
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)

#       crop: false
#       enabled: true
version: 0.15-1
camera_groups: {}
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
none
```

### Relevant Frigate log output

```shell
Timestamp
2025-02-11 16:21:32
Tag
peewee_migrate.logs
Message
Migrate "027_create_explore_index"

-

Timestamp
2025-02-11 16:21:32
Tag
peewee_migrate.logs
Message
Done 027_create_explore_index
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

WYZE

### Screenshots of the Frigate UI's System metrics pages

<img width="943" alt="Screenshot 2025-02-11 at 4 51 26 PM" src="https://github.com/user-attachments/assets/f431a166-1941-4a50-8482-7f14794bcaa5" />

### Any other information that may be helpful

<img width="933" alt="Screenshot 2025-02-11 at 4 49 59 PM" src="https://github.com/user-attachments/assets/c6081846-a886-47ff-933c-594d004a9014" />
