### DISCUSSION TITLE
Cameras not loading and error in log

### DISCUSSION THREAD

**Discussion by sjacksonhodum** [blakeblackshear/frigate#16514] [Ask A Question]
Hello everyone. My cameras load for a super long time and sometimes dont load at all. It may have something to do with my config.yml file. Its running on a dell inspiron with 12gb of ram and shinobi ran with no issues but i wanted to try frigate. My config is below.
<img width="1491" alt="Screenshot 2025-02-11 at 6 46 18 PM" src="https://github.com/user-attachments/assets/25c64b4c-f87c-4677-9c7a-792491b13b5e" />

```
mqtt:
  enabled: False

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://Garage:1234@10.0.0.24/live
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://Driveway:1234@10.0.0.60/live
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5

  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://samm:Samwyzecam@10.0.0.16/live
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5

version: 0.15-1

```

Any help would be greatly appreciated! (sorry if i dont know much im 14 and dont know alot about this stuff)
[log.txt](https://github.com/user-attachments/files/18760477/log.txt)
