### DISCUSSION TITLE
[Support]: Gemini returned an error: 429 Resource has been exhausted (e.g. check quota).

### DISCUSSION THREAD

**Discussion by francescopeloi** [blakeblackshear/frigate#16526] [General Support]
### Describe the problem you are having

I've just enabled genai with gemini. I often get 429 from gemini, even if I enabled snapshot (I understand I should be sending only one request per video with snapshot, so limiting the traffic to gemini). I understand the free tier limit is 15 reqs/min.

On the log example I shared below, what I did: I restarted frigate, went to the explorer, chose 1 video and press regenerate, and got the 429 straightaway. There have not been other detections meanwhile and more than a minute passed from the previous one.

After I enabled genai (~2h ago), there have been ~10 video detections, but I have the description only for one of them. So the integration is working, but basically always going 429.

Tried also with gemini-1.5-flash, same behaviour.

Ideally I'd like to see all requests to gemini, I enabled `debug_save_thumbnails: true` but not sure what to check, logs are always the same with this enabled.

Am I missing something?

Thanks.

### Version

0.15

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: core-mosquitto
  user: mqtt-user
  password: redacted
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: true
  provider: gemini
  api_key: redacted
  model: gemini-2.0-flash

go2rtc:
  streams:
    garage-civico-47:
      - rtsp://admin:redacted@192.168.1.109:554/cam/realmonitor?channel=1&subtype=0
    garage-civico-47-sub:
      - rtsp://admin:redacted@192.168.1.109:554/cam/realmonitor?channel=1&subtype=1
    garage-civico-61:
      - rtsp://admin:redacted@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0
    garage-civico-61-sub:
      - rtsp://admin:redacted@192.168.1.110:554/cam/realmonitor?channel=1&subtype=1
    ingresso-civico-55:
      - rtsp://admin:redacted@192.168.1.111:554/cam/realmonitor?channel=1&subtype=0
    ingresso-civico-55-sub:
      - rtsp://admin:redacted@192.168.1.111:554/cam/realmonitor?channel=1&subtype=1
    garage-interno:
      - rtsp://admin:redacted@192.168.1.112:554/cam/realmonitor?channel=1&subtype=0
    garage-interno-sub:
      - rtsp://admin:redacted@192.168.1.112:554/cam/realmonitor?channel=1&subtype=1
    giardino:
      - rtsp://admin:redacted@192.168.1.113:554/cam/realmonitor?channel=1&subtype=0
    giardino-sub:
      - rtsp://admin:redacted@192.168.1.113:554/cam/realmonitor?channel=1&subtype=1

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:

  ingresso-civico-55:
    enabled: true
    audio:
      enabled: false
    genai:
      enabled: true
      use_snapshot: true
      debug_save_thumbnails: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ingresso-civico-55
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/ingresso-civico-55-sub
          roles:
            - detect
    live:
      stream_name: ingresso-civico-55
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    motion:
      mask:
        - 704,0,704,35,397,31,393,0
        - 0,576,189,576,0,191

  garage-civico-47:
    enabled: true
    genai:
      enabled: true
      use_snapshot: true
      debug_save_thumbnails: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-civico-47
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/garage-civico-47-sub
          roles:
            - detect
    live:
      stream_name: garage-civico-47
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    objects:
      filters:
        car:
          mask:
            - 239,97,230,0,224,0,310,0,320,127
        suitcase:
          mask:
            - 704,76,585,40,561,188,704,254
    motion:
      mask:
        - 683,530,704,576,401,576,401,538
        - 31,55,176,0,0,0,0,205

  garage-civico-61:
    enabled: true
    audio:
      enabled: false
    genai:
      enabled: true
      use_snapshot: true
      debug_save_thumbnails: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-civico-61
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/garage-civico-61-sub
          roles:
            - detect
    live:
      stream_name: garage-civico-61
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    motion:
      mask:
        - 397,0,350,57,0,118,0,0
        - 704,0,502,0,506,47,704,212
    zones:
      escluso_cancello:
        coordinates: 0,125,0,576,704,576,704,111,489,56,431,57,439,0
    objects:
      filters:
        suitcase:
          mask:
            - 223,91,293,90,291,191,236,184

  garage-interno:
    enabled: true
    genai:
      enabled: true
      use_snapshot: true
      debug_save_thumbnails: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-interno
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/garage-interno-sub
          roles:
            - detect
    live:
      stream_name: garage-interno
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    objects:
      filters:
        bicycle:
          mask: 704,248,704,146,642,45,511,83,595,296
        car:
          mask: 364,0,610,0,616,105,370,113
    motion:
      mask:
        - 704,535,704,576,403,576,405,541
        - 465,0,704,0,704,330

  giardino:
    enabled: false
    genai:
      enabled: true
      use_snapshot: true
      debug_save_thumbnails: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/giardino
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/giardino-sub
          roles:
            - detect
    live:
      stream_name: giardino
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    motion:
      mask:
        - 704,0,459,0,463,144,704,331
        - 293,0,0,0,0,32,296,39
        - 0,30,108,37,119,168,0,217
    objects:
      filters:
        suitcase:
          mask:
            - 0.099,0.705,0.25,0.526,0.379,0.595,0.247,0.795
            - 0.133,0.416,0.226,0.349,0.289,0.467,0.203,0.54
        person:
          mask: 0.211,0.534,0.142,0.42,0.226,0.358,0.281,0.475

detect:
  enabled: true
  width: 704
  height: 576
  fps: 5

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

record:
  enabled: true
  retain:
    days: 14
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - backpack
    - handbag
    - suitcase
    - knife
    - dog

version: 0.15-1

camera_groups:
  Garage:
    order: 1
    icon: LuCar
    cameras:
      - garage-civico-47
      - garage-civico-61
      - garage-interno
  Parti_comuni:
    order: 2
    icon: LuFlower2
    cameras:
      - giardino
      - ingresso-civico-55
```

### Relevant Frigate log output

```shell
2025-02-12 13:12:50.180100596  [INFO] Preparing Frigate...
2025-02-12 13:12:50.308075391  [INFO] Starting Frigate...
2025-02-12 13:12:52.770146177  [2025-02-12 14:12:52] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-02-12 13:12:52.825676493  [2025-02-12 14:12:52] frigate.util.config            INFO    : frigate config does not need migration...
2025-02-12 13:12:52.879849426  [2025-02-12 14:12:52] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
2025-02-12 13:12:52.880011813  [2025-02-12 14:12:52] frigate.app                    INFO    : Creating directory: /tmp/cache
2025-02-12 13:12:52.891496058  [2025-02-12 14:12:52] peewee_migrate.logs            INFO    : Starting migrations
2025-02-12 13:12:52.891696289  [2025-02-12 14:12:52] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-02-12 13:12:52.908174701  [2025-02-12 14:12:52] frigate.app                    INFO    : Recording process started: 354
2025-02-12 13:12:52.908592318  [2025-02-12 14:12:52] frigate.app                    INFO    : Review process started: 362
2025-02-12 13:12:52.910578781  [2025-02-12 14:12:52] frigate.app                    INFO    : go2rtc process pid: 104
2025-02-12 13:12:52.921144101  [2025-02-12 14:12:52] detector.coral                 INFO    : Starting detection process: 370
2025-02-12 13:12:55.539536262  [2025-02-12 14:12:52] frigate.app                    INFO    : Embedding process started: 372
2025-02-12 13:12:55.540155107  [2025-02-12 14:12:53] frigate.audio_manager          INFO    : Audio processor started (pid: 496)
2025-02-12 13:12:55.546917469  [2025-02-12 14:12:52] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-02-12 13:12:55.547808754  [2025-02-12 14:12:52] frigate.app                    INFO    : Output process started: 395
2025-02-12 13:12:55.547885896  [2025-02-12 14:12:55] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-02-12 13:12:55.547959743  [2025-02-12 14:12:53] frigate.app                    INFO    : Camera processor started for ingresso-civico-55: 444
2025-02-12 13:12:55.548038396  [2025-02-12 14:12:53] frigate.app                    INFO    : Camera processor started for garage-civico-47: 447
2025-02-12 13:12:55.548128130  [2025-02-12 14:12:53] frigate.app                    INFO    : Camera processor started for garage-civico-61: 455
2025-02-12 13:12:55.548180929  [2025-02-12 14:12:53] frigate.app                    INFO    : Camera processor started for garage-interno: 463
2025-02-12 13:12:55.548259101  [2025-02-12 14:12:53] frigate.app                    INFO    : Camera processor not started for disabled camera giardino
2025-02-12 13:12:55.548275161  [2025-02-12 14:12:53] frigate.app                    INFO    : Capture process started for ingresso-civico-55: 476
2025-02-12 13:12:55.548338248  [2025-02-12 14:12:53] frigate.app                    INFO    : Capture process started for garage-civico-47: 479
2025-02-12 13:12:55.548388259  [2025-02-12 14:12:53] frigate.app                    INFO    : Capture process started for garage-civico-61: 483
2025-02-12 13:12:55.548484524  [2025-02-12 14:12:53] frigate.app                    INFO    : Capture process started for garage-interno: 494
2025-02-12 13:12:55.548576719  [2025-02-12 14:12:53] frigate.app                    INFO    : Capture process not started for disabled camera giardino
2025-02-12 13:12:55.548579654  [2025-02-12 14:12:53] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-02-12 13:12:55.548592686  [2025-02-12 14:12:53] frigate.api.fastapi_app        INFO    : FastAPI started
2025-02-12 13:14:36.938131911  [2025-02-12 14:14:36] frigate.genai.gemini           WARNING : Gemini returned an error: 429 Resource has been exhausted (e.g. check quota).
```

### Relevant go2rtc log output

```shell
none
```

### Frigate stats

```json
can't reach it
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

Coral

**Comment by hawkeye217** [comment]
It doesn't look like you're missing anything.

Frigate just makes requests to your configured GenAI provider's API, so if you're exceeding their quota, you'll want to see if there is some kind of log on their end to show you the total number of requests and exactly what is failing.

**Comment by francescopeloi** [comment]
```
➜  genai-requests ls -lh
total 120K   
drwxr-xr-x    2 root     root        4.0K Feb 12 14:03 1739365415.54525-8vglws
drwxr-xr-x    2 root     root        4.0K Feb 12 14:04 1739365424.622584-3gej42
drwxr-xr-x    2 root     root        4.0K Feb 12 14:04 1739365446.464759-n6rxvb
drwxr-xr-x    2 root     root        4.0K Feb 12 14:04 1739365460.248765-4ixfpm
drwxr-xr-x    2 root     root        4.0K Feb 12 14:06 1739365579.654346-8vxwd3
drwxr-xr-x    2 root     root        4.0K Feb 12 14:06 1739365582.653568-2fmnbh
drwxr-xr-x    2 root     root        4.0K Feb 12 14:06 1739365608.709046-cxpboj
drwxr-xr-x    2 root     root        4.0K Feb 12 14:07 1739365616.115054-rxolij
drwxr-xr-x    2 root     root        4.0K Feb 12 14:07 1739365627.875538-8jve5v
drwxr-xr-x    2 root     root        4.0K Feb 12 14:08 1739365668.957951-3mosna
drwxr-xr-x    2 root     root        4.0K Feb 12 14:08 1739365671.753783-3vwfo9
drwxr-xr-x    2 root     root        4.0K Feb 12 14:08 1739365702.165351-11r604
drwxr-xr-x    2 root     root        4.0K Feb 12 14:08 1739365711.760468-0wy6ym
drwxr-xr-x    2 root     root        4.0K Feb 12 14:10 1739365806.016124-bengfp
drwxr-xr-x    2 root     root        4.0K Feb 12 14:10 1739365823.912225-1dtbpg
drwxr-xr-x    2 root     root        4.0K Feb 12 14:18 1739366278.071661-fj0apv
drwxr-xr-x    2 root     root        4.0K Feb 12 14:18 1739366300.619124-oycu8i
drwxr-xr-x    2 root     root        4.0K Feb 12 14:18 1739366314.20309-gba7t1
drwxr-xr-x    2 root     root        4.0K Feb 12 14:28 1739366903.161846-ophsh9
drwxr-xr-x    2 root     root        4.0K Feb 12 14:29 1739366911.044389-ygqmzj
drwxr-xr-x    2 root     root        4.0K Feb 12 14:29 1739366936.926097-33oqqb
drwxr-xr-x    2 root     root        4.0K Feb 12 14:35 1739367286.044343-m8n2ef
drwxr-xr-x    2 root     root        4.0K Feb 12 14:35 1739367319.635283-fw2zme
drwxr-xr-x    2 root     root        4.0K Feb 12 14:36 1739367346.117397-4z1e71
drwxr-xr-x    2 root     root        4.0K Feb 12 14:42 1739367729.656307-9uvrnp
drwxr-xr-x    2 root     root        4.0K Feb 12 14:50 1739368249.621224-061y4f
drwxr-xr-x    2 root     root        4.0K Feb 12 14:51 1739368274.189952-concjg
drwxr-xr-x    2 root     root        4.0K Feb 12 14:51 1739368275.208639-bhbz1h
drwxr-xr-x    2 root     root        4.0K Feb 12 15:13 1739369590.376157-faikx3
drwxr-xr-x    2 root     root        4.0K Feb 12 15:13 1739369599.168705-5ddp53
```

I think this (almost?) proves I am not sending them too many requests.

Also from gemini:
![image](https://github.com/user-attachments/assets/09abf43d-1fd1-47a1-8a9a-6b30b39d2503)

I don't understand :cry:

**Reply by hawkeye217** [reply]
That's pretty odd. Maybe you could reach out to Google? There's nothing Frigate can really do about it.

**Reply by francescopeloi** [reply]
I can try to reach out to them. Is the 429 log message that I see in frigate logs coming directly from gemini, or there's any mapping in between?

**Reply by hawkeye217** [reply]
That's directly from Gemini.

**Reply by francescopeloi** [reply]
As I am on the free tier, I don't have direct support capabilities, so went to their forum:

https://www.googlecloudcommunity.com/gc/AI-ML/Consistent-429-even-if-stats-says-I-am-under-quota/m-p/872001#M11678

Let's see if they answer.

**Reply by cefoster0** [reply]
watching, same issue.

**Reply by screwyforcepush** [reply]
This due to rate limiting on free tier. Retry with timeout logic would fix it.

**Reply by dbrain** [reply]
Seeing similar, seem to be under requests/min and requests/day quotas. Wondering if we're maybe hitting the "1 million TPM (tokens per minute)" limit.

I seem to be hitting the 429's over longer periods of time without an obviously successful request in between when in theory it should recover after a minute, so I'm wondering if maybe the API is throttling us for not retrying properly (hence the 503 GOAWAY we're getting). I haven't looked at the codebase, but wonder if Frigate needs to add some form of exponential backoff retry for these genai requests.

**Reply by hawkeye217** [reply]
See this comment: https://github.com/blakeblackshear/frigate/discussions/16530#discussioncomment-12176922

Several other users have reported issues with Gemini today.

**Reply by francescopeloi** [reply]
> Seeing similar, seem to be under requests/min and requests/day quotas. Wondering if we're maybe hitting the "1 million TPM (tokens per minute)" limit.

I don't think the cause is that limit either:
![Screenshot From 2025-02-13 11-19-55](https://github.com/user-attachments/assets/970d7d62-e8e0-4144-8a98-1cd76a68e2f4)

**Reply by francescopeloi** [reply]
@hawkeye217 If I do a normal prompt with a curl, gemini answers correctly. It'd be nice if we could see the exact http requests that frigate is doing, so we could try to replicate with a curl, and then maybe modify the request and see what changes. Is there any way we could see the http requests being made?

**Reply by francescopeloi** [reply]
actually, if I remember correctly what I read somewhere, you are calling gemini python library, so it'd be a matter to replicate that I guess

**Reply by hawkeye217** [reply]
> actually, if I remember correctly what I read somewhere, you are calling gemini python library, so it'd be a matter to replicate that I guess

Correct. See my comment I linked above. Frigate uses the official Google python package to connect to the Gemini API.

**Reply by lutfijw** [reply]
@hawkeye217 I have this issue also, strange. The request from Frigate always failing with out of quota issue, but I also use the  same Gemini API Key in HA and it work like a charm, no quota warning, but frigate always showing quota error.

**Reply by hawkeye217** [reply]
As I mentioned in the comment above, Frigate is just using the official Gemini API library, so this is likely an upstream issue.

**Comment by Juggler00** [comment]
Have you found a solution to this? I too am seeing Gemini error 429. I've looked in API console for Gemini and it appears I'm way below the threshold, however every request from Frigate returns the same error.

**Reply by francescopeloi** [reply]
no solution, there's this open: https://www.googlecloudcommunity.com/gc/AI-ML/Consistent-429-even-if-stats-says-I-am-under-quota/m-p/872001#M11678
Maybe do a +1 so it gets attention.

**Reply by Juggler00** [reply]
Will do… thanks!

**Comment by ElectronicBattle** [comment]
A few days ago due to this thread I reduced my Gemini demand from eight cameras on two systems and all objects to one camera, one system and one object. To start with, it seemed to make no difference but yesterday and today I see that most (perhaps 70%) images are getting an AI description.

This is hardly a scientifically based observation but, by eye, it seems to have improved so perhaps the Gemini side of things has been fixed/changed/fiddled with by Google.

**Reply by francescopeloi** [reply]
I haven't changed anything in my setup and now I am getting more descriptions, I think around the % you report. More likely google is fixing things.

**Comment by davemcphee** [comment]
Had the same issue after following the frigate steps, inc "Create API in new Project". Doing that of course creates a new project, called Gemini API. That key got the 429 errors, so I tried generating a new Gemini key in an existing, paid project - same issue.

However, then I linked my "Gemini API" project to my billing account .. and it worked? I realise this doesn't make a whole lot of sense - at this stage, I'm using a paid key created in one my existing projects. And yet, linking the Gemini API project to a billing account resolved it. 

Update: it worked .. .once. Apologies for excitedly posting a solution here.

**Reply by ElectronicBattle** [reply]
It's interesting to note, however, that in the last 20 hours I have had ten out of ten successes with Gemini populating my images, now that I am dedicating only one camera and one object to be submitted to Gemini.   My previous estimate was 70% (see earlier in this thread) so things have improved.

**Reply by ElectronicBattle** [reply]
whereas tonight I see a meagre two out of twenty (both 17 hours old) populated by AI whereas the remainder, all younger than three hours, are blank.

**Reply by ElectronicBattle** [reply]
and none since then (sixty-odd images)

**Comment by djrudolph** [comment]
When using Gemini I have one of my homes seven cameras, managed by Frigate, sending snapshots via genai.  It works for awhile, then I start to receive 429 errors followed later by the, I believe, 503 - Goaway message.   This was two zones, of four, in a not so busy driveway camera. 

Tired of dealing with this, and not finding enough actionable information,  I punted and moved over to openai, using the gpt-4o model, with zero issues.  

At this point: thinking this may be a rate limiting issue on the Google side but I won't be going back to Gemini until this endpoint is a bit more sussed out.  Using OpenAI just seems to work.

**Reply by ElectronicBattle** [reply]
This is useful to know - I have generated an API key which I can handle in my docker-compose and within the Frigate config.yaml, I have simply substituted `gpt-4o` for the model rather than the Gemini one:

```
genai:
  enabled: true
  provider: openai # was gemini
  api_key: "{FRIGATE_GENAI_API_KEY}" 
  model: gpt-4o # was gemini-2.0-flash-lite-preview-02-05 
```

and I'll see how I get on.
