### DISCUSSION TITLE
Unable to create export of one camera

### DISCUSSION THREAD

**Discussion by newness0** [blakeblackshear/frigate#16538] [General Support]
### Describe the problem you are having

Timelapse export for a camera stopped working today. Was able to export fine until yesterday and today, timelapse or regular export doesn't work. I have below error in Frigate logs

`Failed to export recording for command ffmpeg -hide_banner -an -skip_frame nokey -y -protocol_whitelist pipe,file,http,tcp -f concat -safe 0 -i /dev/stdin -c:v libx264 -preset:v ultrafast -tune:v zerolatency -vf setpts=PTS/40 -r 30 -movflags +faststart`

`[hls @ 0xaaaaf3bfd590] Skip ('#EXT-X-ALLOW-CACHE:YES')`

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Safari 18.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.55.11
  user: user-mqtt
  password: passwd


detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2


motion:
  threshold: 30
  contour_area: 15
  improve_contrast: true


auth:
  enabled: true
  reset_user_password: false


record:
  sync_recordings: true
  enabled: true
  retain:
    days: 60
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 90
      mode: all
  export:
    timelapse_args: -vf setpts=PTS/40 -r 30

snapshots:
  enabled: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 10


objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - bicycle
    - motorcycle
    - dog
    - mouse
    - cat

birdseye:
  enabled: true
  restream: true
  mode: continuous
  width: 1920
  height: 1080
  quality: 4

detect:
  width: 640
  height: 360
  enabled: true
  fps: 5
  stationary:
    interval: 150
    threshold: 20


go2rtc:
  rtsp:
    username: xx
    password: xx
  streams:

    cam1_4k:
      - rtsp://user:passwd@192.168.70.11:554/cam/realmonitor?channel=1&subtype=0
    cam1_sub:
      - rtsp://user:passwd@192.168.70.11:554/cam/realmonitor?channel=1&subtype=01

    cam2_4k:
      - rtsp://userb:passwd@192.168.65.44:554/stream1
      - ffmpeg:cam2_4k#audio=opus
    cam2_sub:
      - rtsp://userb:passwd@192.168.65.44:554/stream2
      - ffmpeg:cam2_sub#audio=opus

    cam3_4k:
      - rtsp://user:passwd@192.168.70.55:554/h264Preview_01_main
    cam3_sub:
      - rtsp://user:passwd@192.168.70.55:554/h264Preview_01_sub

    cam4_4k:
      - rtsp://usero:passwd@192.168.65.99:554/stream1
      - ffmpeg:cam4_4k#audio=aac#audio=opus
    cam4_sub:
      - rtsp://usero:passwd@192.168.65.99:554/stream2
      - ffmpeg:cam4_sub#audio=aac#audio=opus

    cam5_4k:
      - rtsp://userkid:passwd@192.168.65.55:554/stream1
      - ffmpeg:cam5_4k#audio=aac#audio=opus
    cam5_sub:
      - rtsp://userkid:passwd@192.168.65.55:554/stream2
      - ffmpeg:cam5_sub#audio=aac#audio=opus

    cam6_4k:
      - rtsp://userk:passwd@192.168.65.66:554/stream1
      - ffmpeg:cam6_4k#audio=aac#audio=opus
    cam6_sub:
      - rtsp://userk:passwd@192.168.65.66:554/stream2
      - ffmpeg:cam6_sub#audio=aac##audio=opus

    cam7_4k:
      - rtsp://user:passwd@192.168.70.44:554/cam/realmonitor?channel=1&subtype=0
    cam7_sub:
      - rtsp://user:passwd@192.168.70.44:554/cam/realmonitor?channel=1&subtype=01

    cam8_Main:
      - ffmpeg:rtsp://root:passwd@192.168.65.88:8554/unicast#video=copy#audio=copy#audio=aac

    cam9_4k:
      - rtsp://user:passwd@192.168.70.33:554/cam/realmonitor?channel=1&subtype=0
    cam9_sub:
      - rtsp://user:passwd@192.168.70.33:554/cam/realmonitor?channel=1&subtype=01

    cam10_4k:
      - rtsp://useri:passwd@192.168.65.77:554/stream1
      - ffmpeg:cam10_4k#audio=aac#audio=opus
    cam10_sub:
      - rtsp://useri:passwd@192.168.65.77:554/stream2
      - ffmpeg:cam10_sub#audio=aac#audio=opus



  webrtc:
    candidates:
      - 192.168.55.22:8555
      - stun:8555

cameras:

  cam1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam1_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam1_sub

  cam2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam2_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      stationary:
        interval: 40
        threshold: 30
    live:
      stream_name: cam2_sub

  cam3:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam3_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      stationary:
        interval: 40
        threshold: 30
    motion:
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
      mask: 0.139,0.016,0.21,0.012,0.214,0.075,0.147,0.077
    live:
      stream_name: cam3_sub

  cam4:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam4_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      stationary:
        interval: 40
        threshold: 30
    motion:
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
      mask: 0.251,0.007,0.366,0,0.367,0.061,0.266,0.073
    live:
      stream_name: cam4_sub

  cam5:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam5_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      threshold: 30
    live:
      stream_name: cam5_sub

  cam6:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam6_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam6_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      threshold: 30
      mask: 0.239,0,0.335,0.002,0.331,0.059,0.234,0.059
    live:
      stream_name: cam6_sub

  cam7:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam7_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam7_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cam7_sub

    motion:
      mask: 0.185,0.005,0.263,0.007,0.269,0.061,0.178,0.073
  cam8:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam8_Main
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: cam8_Main

  cam9:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam9_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam9_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 323,0,324,35,250,31,243,0
    live:
      stream_name: cam9_sub

  cam10:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam10_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam10_4k
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      threshold: 30
      mask: 0.236,0,0.338,0.005,0.339,0.049,0.24,0.056
    live:
      stream_name: cam10_sub


version: 0.14
camera_groups:
  Outcam:
    order: 1
    icon: LuExternalLink
    cameras:
      - cam2
      - cam3
      - cam9
      - cam7
      - cam4
  Incam:
    order: 2
    icon: LuParentheses
    cameras:
      - cam4
      - cam5
      - cam6
      - cam8
      - cam10
  Birds:
    order: 3
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
Tag
frigate.record.export
Message
Failed to export recording for command ffmpeg -hide_banner -an -skip_frame nokey -y -protocol_whitelist pipe,file,http,tcp -f concat -safe 0 -i /dev/stdin -c:v libx264 -preset:v ultrafast -tune:v zerolatency -vf setpts=PTS/40 -r 30 -movflags +faststart

Tag
frigate.record.export
Message
[hls @ 0xaaaaf3bfd590] Skip ('#EXT-X-ALLOW-CACHE:YES')
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
Main stream:

ffprobe version 4.3.7-0+deb11u1+rpt2 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt2 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://xx.65.66:554/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s




Sub Stream:
ffprobe version 4.3.7-0+deb11u1+rpt2 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt2 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://xxx.66:554/stream2':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/frig/config:/config
      - /media/frig_recs/clips:/media/frigate/clips
      - /media/frig_recs/recordings:/media/frigate/recordings
      - /mnt/frig_exports/exports:/media/frigate/exports
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxx"
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C100

### Any other information that may be helpful

I have more Tapo C100 cameras that work fine and have the exact same configuration. Issue with this particular camera started just today and was able to export just fine until today
