### DISCUSSION TITLE
[Config Support]: The video is not being displayed on the Motion Tuner, debug screen, or Home screen.

### DISCUSSION THREAD

**Discussion by hh-TDA** [blakeblackshear/frigate#16535] [Config Support] [answered]
### Describe the problem you are having

After upgrading from Frigate 0.14 to 0.15, there are no errors, but the Live view screen is completely black. Clicking on it allows me to see the live feed.

Additionally, streams are not displayed on the Debug and Motion Tuner screens.

On the home screen, the feed sometimes appears and sometimes does not, but clicking on it allows me to view the live feed.
![image](https://github.com/user-attachments/assets/5025a0cf-4437-4ebe-bb90-56f50012aa99)
![image](https://github.com/user-attachments/assets/50cb0802-f7a5-4596-8ca0-320cf8b4a3f1)

### Version

0.15.0-cea210d

### Frigate config file

```yaml
############################################
mqtt:
  host: mqtt server ip
  client_id: frigate3
  user: user
  password: password
  topic_prefix: frigate
############################################
#   
#   Optional: Authentication configuration
#   
############################################
auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false
  # Optional: Cookie to store the JWT token for native auth (default: shown below)
  # cookie_name: frigate_token
  # # Optional: Set secure flag on cookie. (default: shown below)
  # # NOTE: This should be set to True if you are using TLS
  # cookie_secure: False
  # # Optional: Session length in seconds (default: shown below)
  session_length: 300 # 5min
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  failed_login_rate_limit: 1/second;5/minute;20/hour
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000
############################################
#   birdseye設定
#   continuous:全てのカメラを常時表示
#   motion：動きがあるカメラのみ表示
############################################
birdseye:
  enabled: true
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  restream: true
  layout:
    # オプション: レイアウト計算機のスケーリング係数、範囲は1.0〜5.0 (デフォルト: 2.0)
    scaling_factor: 3.0
############################################
#   ffmpeg設定
# encode,codec
# ffprobeの設定は長めに
############################################
ffmpeg:
  # hwaccel_args: preset-nvidia-h264
  hwaccel_args: preset-nvidia
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -use_wallclock_as_timestamps 1 -threads 8 -loglevel debug -max_delay 10000
    -timeout 200000
  output_args:
    record: preset-record-generic-audio-aac
  global_args: -hide_banner -loglevel debug -analyzeduration 250M -probesize 250M
    -threads 8
############################################
# detect設定
############################################
detect:
  width: 1280
  height: 720
  fps: 5
  stationary:
    interval: 50 # interval/5fps
    threshold: 50 # threshold/5fps

############################################
#   go2rtc設定
#   FrigateはWebRTC or Media Source Extensionsを使用して
#   ストリームを再生します
############################################
go2rtc:
  streams:
  ############################################
  #   bedroom
  ############################################
    bed500:
      - rtsp://user:password@10.100.22.11:554/live/main
      - ffmpeg:bed500#video=h264#audio=aac#hardware
  webrtc:
    candidates:
      - localhost:8555
      - stun:8555

############################################
#   camera config
############################################
cameras:
  ############################################
  #   my bedroom
  ############################################
  bed500:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@localhost:8554/bed500
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@localhost:8554/bed500
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      contour_area: 100
      threshold: 80
      improve_contrast: 'true'
############################################
#   録画・イベント設定
############################################
record:
  enabled: true
  retain:
    days: 21
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    mode: all

audio:
  # Optional: Enable audio events (default: shown below)
  enabled: false
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 200
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - scream
    - yell
    - speech

############################################
#   検出に使用する検出器の設定
############################################
detectors:
  RTX2000Ada:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
############################################
#   検出モデルの設定
############################################
model:
  path: /config/model_cache/tensorrt/yolov7x-custom-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
objects:
  track:
    - person
version: 0.15-1
```

### Relevant Frigate log output

```shell
There is no error.
```

### Relevant go2rtc log output

```shell
There is no error.
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate-gpu
    build:
      context: ./Frigate
      dockerfile: Dockerfile
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 40G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # number of GPUs -> 
              capabilities: [gpu]
    #shm_size: default "64mb"  reso:1280*720　の時12.12*n(cameraの台数)+30MB で計算
    shm_size: "8gb" # update for your cameras based on calculation above 7gbから変更
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /NVR_Environment_new/Frigate/config:/config
      - /NVR_Environment_new/Frigate/trt-models:/trt-models
      - /NVR_Environment_new/Frigate/storage:/media/frigate
      - /mnt/camdisk/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 3000000000
    ports:
      - "8971:8971" # ssl port
      - "5000:5000" # non authenticated API
      - "1984:1984" # go2rtc
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: "user"
      FRIGATE_RTSP_PASSWORD: "pasuwado"
      YOLO_MODELS: yolov7x-320 # Add your models here
```

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/f0a98218-0b51-41fa-a800-4c76a391a184)

### Any other information that may be helpful

Dockerfile
```
FROM ghcr.io/blakeblackshear/frigate:0.15.0-tensorrt
COPY ./nginx.conf.d/nginx.conf /usr/local/nginx/conf/nginx.conf
COPY ./nginx.conf.d/common.conf /usr/local/nginx/conf/common.conf
COPY ./nginx.conf.d/deny.conf /usr/local/nginx/conf/deny.conf
```

**Comment by hawkeye217** [comment]
Frigate uses the stream defined by the `detect` role for the static images on the Live dashboard and for the low frame rate Motion Tuner and Debug pages. Since none of those are working, there is presumably an issue with decoding and processing those streams.

You've manually defined a lot of your ffmpeg arguments. The general recommendation is to use [ffmpeg presets](https://docs.frigate.video/configuration/ffmpeg_presets/). You may want to look at that first.

**Reply by hh-TDA** [reply]
Thank you.

I changed the `input_args` as follows, but the issue remains the same.

```
ffmpeg:
  hwaccel_args: preset-nvidia
  # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
  #   tcp -use_wallclock_as_timestamps 1 -threads 8 -loglevel debug -max_delay 10000
  #   -timeout 200000
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac
  global_args: -hide_banner -loglevel debug -analyzeduration 250M -probesize 250M
    -threads 8
```

**Reply by hawkeye217** [reply]
I'd also suggest changing your go2rtc config to provide a single transcoded stream, eg:

```
go2rtc:
  streams:
    bed500:
      - ffmpeg:rtsp://user:password@10.100.22.11:554/live/main#video=h264#audio=aac#hardware
```

**Reply by hh-TDA** [reply]
I'm sorry. I said there were no errors, but the following error appears in the Chrome developer tools.

![image](https://github.com/user-attachments/assets/ee5f93c2-0282-41e0-b230-ca885adfc5ab)

**Reply by hawkeye217** [reply]
In case `localhost` is not being resolved correctly in the container, and because you don't need authentication when connecting to restreamed urls, I'd try changing your camera urls in your config to `rtsp://127.0.0.1:8554/bed500`

**Reply by hh-TDA** [reply]
The current configuration is as follows.
```
ffmpeg:
  hwaccel_args: preset-nvidia
  # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
  #   tcp -use_wallclock_as_timestamps 1 -threads 8 -loglevel debug -max_delay 10000
  #   -timeout 200000
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac
  # global_args: -hide_banner -loglevel debug -analyzeduration 250M -probesize 250M
  #   -threads 8
 go2rtc:
　streams:
    　bed500:
        　- ffmpeg:rtsp://user:password@10.100.22.11:554/live/main#video=h264#audio=aac#hardware
cameras:
  bed500:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bed500
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bed500
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      contour_area: 100
      threshold: 80
      improve_contrast: 'true'
```
No improvements have been observed, especially regarding the issues.
The error in Chrome Developer Tools remains the same. I will search for other errors.

**Reply by hawkeye217** [reply]
If that is your _exact_ configuration, you have one too many spaces before `go2rtc:`. It should be on the same level as `ffmpeg` and `cameras`.

**Reply by hh-TDA** [reply]
Sorry, I copied and pasted the wrong thing.

**Reply by hh-TDA** [reply]
```
ffmpeg:
  hwaccel_args: preset-nvidia
  # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
  #   tcp -use_wallclock_as_timestamps 1 -threads 8 -loglevel debug -max_delay 10000
  #   -timeout 200000
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac
  # global_args: -hide_banner -loglevel debug -analyzeduration 250M -probesize 250M
  #   -threads 8

############################################
#   go2rtc設定
############################################
go2rtc:
  streams:
    bed500:
      - ffmpeg:rtsp://user:password@10.100.22.11:554/live/main#video=h264#audio=aac#hardware
  webrtc:
    candidates:
      - localhost:8555
      - stun:8555

############################################
#   camera config
############################################
cameras:
  bed500:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bed500
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bed500
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      contour_area: 100
      threshold: 80
      improve_contrast: 'true'

```
