### DISCUSSION TITLE
[Bug]: 502 from internal container NginX proxy when vod is requested for video that does not exist

### DISCUSSION THREAD

**Discussion by Rudd-O** [blakeblackshear/frigate#16534] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I go to review (in the explore tab I think) old events, and I try to pull up certain videos, I get an endless spinner on the video rectangle.

Requesting from the backend what my browser requests:

```
curl 'http://127.0.0.1:8971/vod/baby_bedroom_camera/start/1738320253.078021/end/1738320258.111851/index.m3u8' \
-H 'Host: nvr.dragonfear' \
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Accept-Language: en-US,en;q=0.5' \
-H 'Accept-Encoding: gzip, deflate, br, zstd' \
-H 'Connection: keep-alive' \
-H 'Cookie: frigate_token=<obvs not gonna put the token here>' \
-H 'Upgrade-Insecure-Requests: 1' \
-H 'Sec-Fetch-Dest: document' \
-H 'Sec-Fetch-Mode: navigate' \
-H 'Sec-Fetch-Site: none' \
-H 'Sec-Fetch-User: ?1' \
-H 'Priority: u=0, i' \
-H 'TE: trailers'
```

I get a HTTP 502 from the internal proxy.  Logs at that instant say:

```
2025-02-12 20:41:25.123512912  [2025-02-12 20:41:25] frigate.api.media              ERROR   : No recordings found for baby_bedroom_camera during the requested time range
2025-02-12 20:41:25.123822540  2025/02/12 20:41:25 [error] 153#153: *534 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 10.88.0.1, server: , request: "GET /vod/baby_bedroom_camera/start/1738320253.078021/end/1738320258.111851/index.m3u8 HTTP/1.1", host: "nvr.dragonfear"
2025-02-12 20:41:25.124370802  10.88.0.1 - - [12/Feb/2025:20:41:25 +0000] "GET /vod/baby_bedroom_camera/start/1738320253.078021/end/1738320258.111851/index.m3u8 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
```

There are two problems here:

1. 404 is a legitimate response from the internal API.  It means "that video is gone, go away".  Internal container NginX proxy *should pass through that status code and content*.
2. The frontend does not seem to handle a non-200 from the endpoint requested by it.  It should handle 404 not showing a spinner, but rather showing "this video is no longer available" or whatever error message the backend supplies (possibly translated to the user's locale).

### Steps to reproduce

See above.

### Version

0.15

### In which browser(s) are you experiencing the issue with?

Firefox.  This is a backend issue, not a browser one.

### Frigate config file

```yaml
mqtt:
{%- if mqtt %}
  enabled: true
  host: {{ mqtt["host"] | json }}
  port: 1883
  user: {{ mqtt["user"] | json }}
  password: {{ mqtt["password"] | json }}
{%- else %}
  enabled: false
{%- endif %}

tls:
  enabled: false

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  input_args: preset-rtsp-udp

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

audio:
  enabled: true
  listen:
    - scream
    - yell
    - crying
    - finger_snapping
    - lullaby

review:
  alerts:
    labels:
      - scream
      - yell
      - crying

record:
  enabled: true
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    # https://docs.frigate.video/configuration/reference/
    days: 7
    mode: all
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: high
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

cameras:
{%- for cam, creds in cameras.items() %}
  {{ cam.replace("-", "_") }}:
    enabled: true
    ffmpeg:
      inputs:
        - path:
            rtsp://{{ creds['user'] }}:{{ creds['password'] }}@{{ cam }}.dragonfear:554/stream1
          roles:
            - record
        - path:
            rtsp://{{ creds['user'] }}:{{ creds['password'] }}@{{ cam }}.dragonfear:554/stream2
          roles:
            - detect
            - audio
    # When I enable this, the entire frigate hangs and responds with HTTP 502.
    onvif:
      host: {{ cam }}.dragonfear
      port: 2020
      user: {{ creds['user'] }}
      password: {{ creds['password'] }}
{%-   if cam == "baby-bedroom-camera" %}
    zones:
      crib:
        coordinates: 0.63,0.07,0.711,0.972,0.984,0.925,0.868,0.013
        inertia: 3
        loitering_time: 0
      changer:
        coordinates: 0.524,0.777,0.395,0,0.005,0.01,0,0.833
        inertia: 3
        loitering_time: 0

    objects:
      mask:

        - 0.41,0.142,0.493,0.598,0.678,0.55,0.628,0.066
        - 0.298,0.53,0.188,0.542,0.192,0.07,0.299,0.058
{%-   endif %}
{%- endfor %}

go2rtc:
  streams:
{% for cam, creds in cameras.items() %}
    {{ cam.replace("-", "_") }}:
      - rtsp://{{ creds['user'] }}:{{ creds['password'] }}@{{ cam }}.dragonfear:554/stream1
      - ffmpeg:{{ cam.replace("-", "_") }}#audio=opus
{% endfor %}
  webrtc:
    candidates:
      - 10.250.7.20:8555

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
Just a standard podman run.
```

### Relevant Frigate log output

```shell
See above.
```

### Relevant go2rtc log output

```shell
go2rtc not involved.
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Not relevant

### Screenshots of the Frigate UI's System metrics pages

Thanks but this will not be necessary.
