### DISCUSSION TITLE
[Config Support]: After upgrade to frigate 0.15.0 my camera's are no longer loading

### DISCUSSION THREAD

**Discussion by h3llrais3r** [blakeblackshear/frigate#16531] [Config Support] [answered]
### Describe the problem you are having

Running frigate as hass addon.
I've just upgraded to the 0.15.0 version, but all my camera's which are using ffmpeg have issues due to following error:
`2025-02-12 17:13:38.118151328  18:13:38.118 WRN [rtsp] error="streams: exec: \"ffmpeg\": executable file not found in $PATH" stream=reolink_1_main`

I read the documentation that it has been removed from the path, and in most cases it should be handled automatically, but it's not.
What do I need to change to get working again?
Do I need to adapt my config and use the full path for ffmpeg?

### Version

0.15.0

### Frigate config file

```yaml
go2rtc:
  streams:
     reolink_1_main:
      - ffmpeg:https://192.168.0.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>#video=copy#audio=copy#audio=opus
     reolink_1_sub:
      - ffmpeg:https://192.168.0.154/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<user>&password=<password>
```

### Relevant Frigate log output

```shell
2025-02-12 17:19:30.391206600  18:19:30.391 WRN [rtsp] error="streams: exec: \"ffmpeg\": executable file not found in $PATH" stream=reolink_1_main
```

### Relevant go2rtc log output

```shell
error="exec: \"ffmpeg\": executable file not found in $PATH" url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.0.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password> -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral
