### DISCUSSION TITLE
[Support]: gemini was working, now it is sporadic/not working

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#16532] [General Support] [answered]
### Describe the problem you are having

Hello all

My two systems are on 0.15; my images do get descriptions added to them from time to time but it seems hit and miss.  One system gets some descriptions for some images, and the other gets some descriptions for other ones.

I was using `gemini-2.0-flash-lite-preview-02-05`  which seemed it was working but today I notice the features say this:
![image](https://github.com/user-attachments/assets/2e4d458e-ba2b-4b7e-af3a-8ea41438c3d7)
which is different, I think, from what it said a few days ago.  I chose this model due to it providing double the number of RPM compared with 1.5 (and I am running two systems here so it seemed sensible) 

By way of contrast, `gemini 1.5` says
![image](https://github.com/user-attachments/assets/21eed65b-c219-4976-9c8a-90ffaa07b201)

all of the "not supported" bits on 2.0 flash lite preview - are they what I need to get it working on Frigate? Might that explain why it is now sporadic or stopped? The last image was updated more than 4h ago.

I know I need to enable logging but that there are some problems to be ironed out and there are alternative approaches (saving thumbnails or something) which I don't know whether it's relevant or not. I have read some of the other threads in the last day or so.

### Version

0.15

### Frigate config file

```yaml
#for HPZ1G5, not TrueNAS: cameras re-ordered NO GO2RTC
version: 0.15-1-rc2


telemetry:
  # Optional: Configure system stats
  stats:
    amd_gpu_stats: false
    intel_gpu_stats: true
    network_bandwidth: true

model:
  path: plus://e570a5fa60ccfce5aca76ad55c4ffddd  #mobiledet edgeTPU 2024.3 7/11/24
#  path: plus://98f2ff2d47bfacdd1823ef3641b716c4 #mobiledet edgeTPU 2024.3 added 2320 03/11/24
#  path: plus://9b85aa0fc8a3aaa6ef8dfb8ea80a2dc9 #mobiledet edgeTPU 2024.2 added 1625 28/8/24
#  path: plus://2cf1f99bc96475f2423babf38b7d7567 #mobiledet cpu 2024.2 


genai:
  enabled: True
  provider: gemini
  api_key: "################################################"
  model: gemini-2.0-flash-lite-preview-02-05 #gemini-2.0-flash


  

ffmpeg:
  hwaccel_args:  preset-intel-qsv-h265  #preset-vaapi with the docker compose driver set to i965

#ffmpeg:
#  global_args: -hide_banner -loglevel warning -threads 2
#  hwaccel_args: preset-vaapi
#  input_args: preset-rtsp-restream


objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    fox:
      min_score: .65
      threshold: .8
    squirrel:
      min_score: .65
      threshold: .8
    bird:
      min_score: .65
      threshold: .8
    deer:
      min_score: .65
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    bicycle:
      min_score: .65
      threshold: .85

  track:
    - person
    - face
    - car
    - license_plate
    - cat
    - dog
    - fox
    - bird
    - deer
    - squirrel
    - package
    - bicycle


review:
  alerts:
    labels:
      - person
      - car
      - cat
      - dog
      - fox
      - deer
      - bicycle
  detections:
    labels:
      - person
      - car
      - cat
      - dog
      - fox
      - deer
      - bicycle

snapshots:
  enabled: true # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  clean_copy: true #false  #true # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  timestamp: false # Optional: print a timestamp on the snapshots (default: shown below)
  bounding_box: true # Optional: draw bounding box on the snapshots (default: shown below)
  crop: false # Optional: crop the snapshot (default: shown below)
  height: 768 # Optional: height to resize the snapshot to (default: original size)  #height: 800
  #required_zones: []# Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  retain: # Optional: Camera override for retention settings (default: global values)
    default: 5 # Required: Default retention days (default: shown below)
    objects: # Optional: Per object retention days
      person: 7
      cat: 7
      dog: 7
      bird: 7
      fox: 7
      badger: 7
      deer: 7
      car: 7
      licence_plate: 6
      bicycle: 7

  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

detect:
  width: 640
  height: 360
semantic_search:
  enabled: true
  reindex: true #false
  model_size: small





camera_groups:
  all:
   # order: 
    icon: LuActivitySquare
    cameras:
      - greenhouse
      - upper_patio
      - ponds
      - blue_gate
      - lower_patio
      - lower_steps
      - shed
      - drive
      
      
      
      
ui:
  time_format: 24hour


mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: pci
    detect:
      enabled: true




#stats:
#    # Enable Intel GPU stats (default: shown below)
#    intel_gpu_stats: True

record:
  enabled: true
  retain:
    days: 3
    mode: motion
#  alerts:
#    retain:
#      days: 3
#  detections:
#    retain:
#      days: 3

go2rtc:
  streams:
    #reference format from NickM-27 @ https://github.com/blakeblackshear/frigate/discussions/12376 
    #              "ffmpeg:rtsp://...                                               #video=h264#audio=copy#hardware" note the quotes and hashes
    greenhouse:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
      - ffmpeg:greenhouse#audio=opus #audio=pcmu
    upper_patio:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0#video=h264#audio=copy
      - ffmpeg:upper_patio#audio=opus #audio=pcmu 
    ponds:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0#video=h264#audio=copy
      - ffmpeg:ponds #audio=opus #audio=pcmu audio disabled, see https://github.com/blakeblackshear/frigate/discussions/15827
    blue_gate:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0#video=h264#audio=copy
      - ffmpeg:blue_gate #audio=opus #audio=pcmu audio disabled, see https://github.com/blakeblackshear/frigate/discussions/15827
    lower_patio:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0#video=h264#audio=copy
      - ffmpeg:lower_patio#audio=opus #audio=pcmu 
    lower_steps:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0#video=h264#audio=copy
      - ffmpeg:lower_steps #audio=opus #audio=pcmu  audio disabled, see https://github.com/blakeblackshear/frigate/discussions/15827
    shed:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0#video=h264#audio=copy
      - ffmpeg:shed #audio=opus #audio=pcmu audio disabled, see https://github.com/blakeblackshear/frigate/discussions/15827
    drive:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0#video=h264#audio=copy
      - ffmpeg:drive#audio=opus #audio=pcmu 
#    doorbell:
#      - "ffmpeg:rtsp://admin:QXQODG@192.168.1.192:554/Streaming/Channels/101#raw -vf lenscorrection=k1=-0.450:k2=0.1"
#      - "ffmpeg:doorbell#audio=opus"

  webrtc:
    candidates:
      - localhost:8555
      - stun:8555




cameras:

  greenhouse: #########GREENHOUSE##########################GREENHOUSE#########################GREENHOUSE#########################GREENHOUSE#########################GREENHOUSE#########################GREENHOUSE#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record
#########GREENHOUSE##########################GREENHOUSE#########################GREENHOUSE#########################GREENHOUSE#########################GREENHOUSE#########################GREENHOUSE#########################


  upper_patio: #########UPPER_PATIO###############################################UPPER_PATIO###########################UPPER_PATIO###########################UPPER_PATIO###########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #SD 640x360 level1 ### 130125 trying HD for det (here) and rec below as usual
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0 #HD level0
          roles:
            - record

    zones:
      upperpatio:
        coordinates: 
          0.003,0.997,0.005,0.795,0.042,0.789,0.045,0.732,0.049,0.619,0.077,0.546,0.103,0.479,0.145,0.425,0.168,0.401,0.204,0.371,0.216,0.369,0.268,0.378,0.279,0.339,0.32,0.302,0.347,0.293,0.361,0.298,0.382,0.345,0.395,0.375,0.563,0.418,0.582,0.474,0.626,0.476,0.674,0.51,0.712,0.515,0.795,0.664,0.862,0.704,0.933,0.822,0.999,0.896,0.995,0.996
        loitering_time: 0
    motion:
      mask: 
        0.003,0.374,0.207,0.313,0.239,0.272,0.292,0.258,0.32,0.245,0.36,0.222,0.682,0.219,0.716,0.204,0.726,0.001,0.002,0.001

    review:
      alerts:
        required_zones: upperpatio
      detections: {}

#########UPPER_PATIO###############################################UPPER_PATIO###########################UPPER_PATIO###########################UPPER_PATIO###########################

  ponds: #################PONDS#######################################PONDS#########################PONDS#########################PONDS#########################PONDS#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=2&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
          roles:
            - detect


        - path: rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
          roles:
            - record
    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox #placeholder
        - badger #placeholder
#################PONDS#######################################PONDS#########################PONDS#########################PONDS#########################PONDS#########################

  blue_gate: #########BLUE_GATE###################################################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #  input_args: preset-rtsp-restream

          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox #placehlder
        - badger # placeholder
        - car
        - license_plate



    motion:
      mask:
        - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
        - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360

    zones:
      gravel:
        coordinates: 
          411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233



    review:
      alerts:
        required_zones: gravel

#########BLUE_GATE###################################################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################


  lower_steps: #########LOWER_STEPS#########LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=4&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox #placeholder
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
    #  order: 5
#########LOWER_STEPS#########LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######

  lower_patio: #########LOWER PATIO##########################LOWER PATIO#########################LOWER PATIO#########################LOWER PATIO#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    zones:
      lower_patio_slabs:
        coordinates: 
          0.345,0.994,0.352,0.214,0.345,0.178,0.456,0.152,0.502,0.255,0.545,0.363,0.584,0.384,0.853,0.981
        loitering_time: 0
    motion:
      mask: 
        0.327,0.625,0.339,0.178,0.35,0.119,0.504,0.09,0.618,0.178,0.744,0.5,0.995,0.901,0.995,0.015,0.005,0.006,0.008,0.098,0.271,0.076,0.318,0.722
    review:
      alerts:
        required_zones: lower_patio_slabs
      detections:
        required_zones: lower_patio_slabs
#########LOWER PATIO##########################LOWER PATIO#########################LOWER PATIO#########################LOWER PATIO#########################

  shed: #########SHED##########################SHED#########################SHED#########################SHED#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=6&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record




    motion:
      mask:
        - 0.263,0.05,0.266,0,0,0,0,0.195
        - 0.7,0,0.723,0.995,0.998,0.997,1,0.001
    zones:
      shed-path:
        coordinates: 
          0.722,0.983,0.714,0.521,0.501,0.523,0.5,0.384,0.349,0.371,0.348,0.328,0.336,0.275,0.305,0.25,0.277,0.273,0.28,0.323,0.208,0.332,0.103,0.469,0.002,0.549,0.002,0.655,0.002,1
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: shed-path
      detections: {}
#########SHED##########################SHED#########################SHED#########################SHED#########################

  drive: #########DRIVE##########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    zones:
      drive_gravel:
        coordinates: 
          0.256,0.37,0.355,0.375,0.344,0.548,0.693,0.536,0.991,0.866,0.999,0.991,0.207,0.995,0.2,0.595,0.082,0.522
        loitering_time: 0
    motion:
      mask: 
        0.002,0.36,0.179,0.304,0.27,0.269,0.276,0.12,0.361,0.137,0.358,0.349,0.487,0.351,0.658,0.356,0.71,0.358,0.998,0.539,0.993,0.003,0.008,0

    review:
      alerts:
        required_zones: drive_gravel
      detections:
        required_zones: drive_gravel
#########DRIVE##########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################
```

### Relevant Frigate log output

```shell
none relevant (no mention of genAI anywhere)
```

### Relevant go2rtc log output

```shell
2025-02-12 13:49:13.587884099  created by github.com/AlexxIT/go2rtc/internal/rtsp.Init.func1 in goroutine 7
2025-02-12 13:49:13.587885643  	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:75 +0x45
2025-02-12 18:23:45.082762  2025-02-12 13:49:13.587886845
2025-02-12 13:49:13.587888151  goroutine 497278 [chan receive]:
2025-02-12 13:49:13.587896101  github.com/AlexxIT/go2rtc/pkg/core.(*Sender).worker(0xc000223620, 0xc00071a400)
2025-02-12 13:49:13.587897607  	github.com/AlexxIT/go2rtc/pkg/core/track.go:156 +0x205
2025-02-12 13:49:13.587902732  created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 497277
2025-02-12 13:49:13.587904176  	github.com/AlexxIT/go2rtc/pkg/core/track.go:117 +0x6b
2025-02-12 18:23:45.082765  2025-02-12 13:49:13.587905295
2025-02-12 13:49:13.587906550  goroutine 497316 [chan receive]:
2025-02-12 13:49:13.587912623  os/exec.(*Cmd).awaitGoroutines(0xc000feab00, 0x0)
2025-02-12 13:49:13.587913909  	os/exec/exec.go:948 +0x1fa
2025-02-12 13:49:13.587918669  os/exec.(*Cmd).Wait(0xc000feab00)
2025-02-12 13:49:13.587919975  	os/exec/exec.go:915 +0x16c
2025-02-12 13:49:13.587921427  github.com/AlexxIT/go2rtc/internal/exec.handleRTSP.func2()
2025-02-12 13:49:13.587926334  	github.com/AlexxIT/go2rtc/internal/exec/exec.go:141 +0x25
2025-02-12 13:49:13.587927824  created by github.com/AlexxIT/go2rtc/internal/exec.handleRTSP in goroutine 497044
2025-02-12 13:49:13.587932384  	github.com/AlexxIT/go2rtc/internal/exec/exec.go:140 +0x534
2025-02-12 18:23:45.082769  2025-02-12 13:49:13.587933525
2025-02-12 13:49:13.587934901  goroutine 496856 [chan receive]:
2025-02-12 13:49:13.587939850  github.com/AlexxIT/go2rtc/pkg/core.(*Sender).worker(0xc003068360, 0xc00071a2c0)
2025-02-12 13:49:13.587944872  	github.com/AlexxIT/go2rtc/pkg/core/track.go:156 +0x205
2025-02-12 13:49:13.587946514  created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 496694
2025-02-12 13:49:13.587951537  	github.com/AlexxIT/go2rtc/pkg/core/track.go:117 +0x6b
2025-02-12 18:23:45.082772  2025-02-12 13:49:13.587952714
2025-02-12 13:49:13.587954096  goroutine 497166 [chan receive]:
2025-02-12 13:49:13.587958996  github.com/AlexxIT/go2rtc/pkg/core.(*Sender).worker(0xc0002abe00, 0xc000474240)
2025-02-12 13:49:13.587960593  	github.com/AlexxIT/go2rtc/pkg/core/track.go:156 +0x205
2025-02-12 13:49:13.587965708  created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 497223
2025-02-12 13:49:13.587967296  	github.com/AlexxIT/go2rtc/pkg/core/track.go:117 +0x6b
2025-02-12 13:49:13.604795954  [INFO] The go2rtc service exited with code 2 (by signal 0)
2025-02-12 13:49:14.617811182  [INFO] Removing stale config from last run...
2025-02-12 13:49:14.621656791  [INFO] Preparing new go2rtc config...
2025-02-12 13:49:15.032965871  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-02-12 13:49:15.157222761  [INFO] Starting go2rtc...
2025-02-12 13:49:15.247770402  13:49:15.247 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-02-12 13:49:15.247772912  13:49:15.247 INF config path=/dev/shm/go2rtc.yaml
2025-02-12 13:49:15.248258065  13:49:15.248 INF [api] listen addr=:1984
2025-02-12 13:49:15.248339296  13:49:15.248 INF [rtsp] listen addr=:8554
2025-02-12 13:49:15.248580832  13:49:15.248 INF [webrtc] listen addr=:8555
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate015
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    #    deploy:
    #      # <------------- Add this section
    #      resources:
    #        reservations:
    #          devices:
    #            - driver: nvidia
    #              device_ids:
    #                - "0"
    #              count: 1
    #              capabilities:
    #                - gpu
    #
    #
    shm_size: 256mb # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      #host : container
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      #      mem_limit: 4096m # seemed to make load a bit worse
      #      cpus: "4" # seemed to make load a bit worse
      LIBVA_DRIVER_NAME: iHD #i965
      PLUS_API_KEY: ################################
networks: {}
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

na

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d54344c5-b4a1-4eb4-9340-bc1590aed2bb)
