### DISCUSSION TITLE
[Support]: Gemini returned an error: 429 Resource has been exhausted (e.g. check quota).

### DISCUSSION THREAD

**Discussion by nurtext** [blakeblackshear/frigate#16530] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Can't using Gemini GenAI API with frigate, but using the same API with the same key in Postman works fine. 

### Steps to reproduce

1. Setup Gemini according to Frigate docs
2. Setup Frigate according to Frigate docs
3. Test by moving into the camera's view :)
4. Doesn't work :(

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

doesn't matter

### Frigate config file

```yaml
auth:
  enabled: true
  reset_admin_password: false
  trusted_proxies:
    - 192.168.2.0/24

tls:
  enabled: false

mqtt:
  host: mqtt
  user: frigate
  password: "REDACTED"

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

ui:
  timezone: Europe/Berlin
  time_format: 24hour

objects:
  track:
    - car
    - cat
    - person

genai:
  enabled: true
  provider: gemini
  api_key: "REDACTED"
  model: gemini-1.5-flash

go2rtc:
  ffmpeg:
    volume: -af "volume=30dB"
  rtsp:
    username: frigate
    password: frigate
  webrtc:
    candidates:
      - 192.168.2.80:8555
      - 185.250.169.16:8555
  streams:
    childs_room_record:
      - rtsp://frigate:frigate@192.168.2.81:554/stream1
      - ffmpeg:childs_room_record#audio=aac
    childs_room_detect:
      - rtsp://frigate:frigate@192.168.2.81:554/stream2
      - ffmpeg:childs_room_detect#audio=opus

cameras:
  childs_room:
    enabled: true
    mqtt:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/childs_room_record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/childs_room_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: childs_room_record
    motion:
      mask: 0.368,0.132,0.526,0.132,0.514,0.799,0.376,0.864
    objects:
      filters:
        person:
          mask: 0.368,0.132,0.526,0.132,0.515,0.8,0.376,0.867

detect:
  width: 640
  height: 360

review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - cat
      - car

record:
  enabled: true
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7

timestamp_style:
  position: tr
  format: '%d.%m.%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  quality: 90
  retain:
    default: 0
    objects:
      car: 7
      cat: 7
      person: 7

semantic_search:
  enabled: true
  reindex: false
  model_size: small

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
not relevant
```

### Relevant Frigate log output

```shell
Gemini returned an error: 429 Resource has been exhausted (e.g. check quota).
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

TP-Link Tapo C110

### Screenshots of the Frigate UI's System metrics pages

not relevant

### Any other information that may be helpful

As described, using the Gemini API in Postman and in Google AI studio works.
