### DISCUSSION TITLE
[Bug]: Illegal instruction with 0.15

### DISCUSSION THREAD

**Discussion by a-bali** [blakeblackshear/frigate#16547] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After upgrading to 0.15, frigate startup fails with the following error. HW is Intel N3350, v0.14 worked just fine, no changes were made to the config other than the upgrade. I also tried replacing `preset-vaapi` with `preset-intel-qsv-h264/5` and downgrading to ffmpeg 5.0 as per the release notes, did not help.

```
frigate           | 2025-02-13 15:51:35.376882819  [2025-02-13 15:51:35] frigate.app                    INFO    : Output process started: 309
frigate           | 2025-02-13 15:51:35.511614969  Fatal Python error: Illegal instruction
frigate           | 2025-02-13 15:51:35.511623460
frigate           | 2025-02-13 15:51:35.511625634  Thread 0x00007faea3c516c0 (most recent call first):
frigate           | 2025-02-13 15:51:35.511658907    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate           | 2025-02-13 15:51:35.511661560    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate           | 2025-02-13 15:51:35.516697556    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate           | 2025-02-13 15:51:35.516736060    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate           | 2025-02-13 15:51:35.517975613    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate           | 2025-02-13 15:51:35.517984364
frigate           | 2025-02-13 15:51:35.517986453  Current thread 0x00007faecebb9740 (most recent call first):
frigate           | 2025-02-13 15:51:35.517995167    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 543 in compile_model
frigate           | 2025-02-13 15:51:35.517998509    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 40 in __init__
frigate           | 2025-02-13 15:51:35.518046964    File "/opt/frigate/frigate/detectors/__init__.py", line 18 in create_detector
frigate           | 2025-02-13 15:51:35.518050010    File "/opt/frigate/frigate/object_detection.py", line 68 in __init__
frigate           | 2025-02-13 15:51:35.518052865    File "/opt/frigate/frigate/object_detection.py", line 121 in run_detector
frigate           | 2025-02-13 15:51:35.518055229    File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
frigate           | 2025-02-13 15:51:35.518057190    File "/opt/frigate/frigate/util/process.py", line 41 in run_wrapper
frigate           | 2025-02-13 15:51:35.518106532    File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
frigate           | 2025-02-13 15:51:35.528088260    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
frigate           | 2025-02-13 15:51:35.529082847    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
frigate           | 2025-02-13 15:51:35.529091882    File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
frigate           | 2025-02-13 15:51:35.529094202    File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
frigate           | 2025-02-13 15:51:35.529096234    File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
frigate           | 2025-02-13 15:51:35.529098198    File "/opt/frigate/frigate/util/process.py", line 30 in start
frigate           | 2025-02-13 15:51:35.531299528    File "/opt/frigate/frigate/object_detection.py", line 204 in start_or_restart
frigate           | 2025-02-13 15:51:35.531308928    File "/opt/frigate/frigate/object_detection.py", line 172 in __init__
frigate           | 2025-02-13 15:51:35.533007612    File "/opt/frigate/frigate/app.py", line 350 in start_detectors
frigate           | 2025-02-13 15:51:35.533016588    File "/opt/frigate/frigate/app.py", line 598 in start
frigate           | 2025-02-13 15:51:35.533018811    File "/opt/frigate/frigate/__main__.py", line 60 in main
frigate           | 2025-02-13 15:51:35.533020797    File "/opt/frigate/frigate/__main__.py", line 64 in <module>
frigate           | 2025-02-13 15:51:35.533022715    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
frigate           | 2025-02-13 15:51:35.533024604    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
```

### Steps to reproduce

1. Upgrade to 0.15
2. Launch application
3. Fail :-(
...

### Version

0.15.0

### Frigate config file

```yaml
ffmpeg:
  path: "5.0"
  hwaccel_args: preset-vaapi
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac -q:a 2

[...]

detectors:
  ov:
    type: openvino
    device: AUTO
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

[...]
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    cap_add:
      - CAP_PERFMON
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config/
      - /mnt/hdd/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1935:1935"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
(see above)
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Generic IP cam

### Screenshots of the Frigate UI's System metrics pages

-

**Comment by NickM-27** [comment]
we need to see the entire config

**Comment by a-bali** [comment]
Here you go.

```
mqtt:
  enabled: true
  host: mqttgw.lan

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac -q:a 2

go2rtc:
  streams:
    street_camera:
      - rtsp://192.168.33.200:554/user=*_password=*_channel=1_stream=0.sdp?real_stream
      - ffmpeg:street_camera#audio=opus
      - ffmpeg:street_camera#audio=aac
    garden_camera:
      - rtsp://192.168.33.201:554/11
      - ffmpeg:garden_camera#audio=opus
      - ffmpeg:garden_camera#audio=aac
  webrtc:
    candidates:
      - 192.168.33.100:8555
      - 100.88.56.17:8555

cameras:
  garden_camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.33.201:554/11
          roles:
            - record
        - path: rtsp://192.168.33.201:554/12
          roles:
            - detect
    detect:
      enabled: false
      width: 800
      height: 600
    motion:
      mask:
        - 800,0,622,0,622,22,800,21,800,0
  street_camera:
    ffmpeg:
      inputs:
        - path:
            rtsp://192.168.33.200:554/user=*_password=*_channel=1_stream=0.sdp?real_stream
          roles:
            - record
        - path:
            rtsp://192.168.33.200:554/user=*_password=*_channel=1_stream=1.sdp?real_stream
          roles:
            - detect
    detect:
      width: 640
      height: 360
    zones:
      street:
        coordinates: 0,0.502,1,0.375,1,0,0,0
        inertia: 3
        loitering_time: 0
      inside:
        coordinates: 1,1,1,0.389,0,0.521,0,1
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 398,38,625,38,625,19,398,19
        - 0,62,343,39,640,56,640,0,0,0
    objects:
      filters:
        person:
          mask: 0,0,261,0,259,55,0,86
        car:
          mask: 0,0,261,0,259,55,0,86
    review:
      alerts:
        required_zones:
          - inside
    live:
      stream_name: street_camera

detectors:
  ov:
    type: openvino
    device: AUTO
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

motion:
  improve_contrast: true

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 30
    mode: all
  export:
    timelapse_args: -vf setpts=0.02*PTS -r 30

  alerts:
    retain:
      days: 365
  detections:
    retain:
      days: 365
snapshots:
  enabled: true
  quality: 95
  retain:
    default: 365

birdseye:
  enabled: true
  mode: continuous

version: 0.15-1
```
