### DISCUSSION TITLE
Is there a way to disable native frigate0.15 notifications at the camera level?

### DISCUSSION THREAD

**Discussion by Oddsodz** [blakeblackshear/frigate#16551] [Ask A Question] [answered]
Hello all.

Here is my use case.

I have 8 cameras all running wonderfully.  And I managed to work out and setup the new native push notifications to my phone (great work on that.  Wont need Home Assistant now).  

But the only thing I have failed to work out how to enable notifications for some cameras and no notifications for others.

Is this even possible as I right now?

Here is my camera config

```


cameras:
  Hallway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Hallway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Hallway
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Hallway
    record: # <----- Enable recording
      enabled: true
    genai:
      enabled: True # <- enable GenAI for your front Hallway
      use_snapshot: True
      prompt: "Describe the {label} in the sequence of images with as much detail as possible. Do not describe the background."
      objects:
        - bird
        - dog
        - cat
        - animal
        - person
    detect:
      width: 854
      height: 480
      fps: 5
```

Here is what I  feel I am missing

```
cameras:
  Hallway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Hallway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Hallway
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Hallway
    record: # <----- Enable recording
      enabled: true
    
	
	notifications:
      enabled: True # <- Oddsodz fake notifications switch
	
	
	genai:
      enabled: True # <- enable GenAI for your front Hallway
      use_snapshot: True
      prompt: "Describe the {label} in the sequence of images with as much detail as possible. Do not describe the background."
      objects:
        - bird
        - dog
        - cat
        - animal
        - person
    detect:
      width: 854
      height: 480
      fps: 5
```

Thanks for taking the time to read.

Oddsodz
