### DISCUSSION TITLE
[Config Support]: MQTT disconnected

### DISCUSSION THREAD

**Discussion by hh-TDA** [blakeblackshear/frigate#16568] [Config Support] [answered]
### Describe the problem you are having

In Frigate 0.14, it was possible to connect multiple Frigate servers to a single MQTT broker by ensuring that each client_id was unique.
From Frigate 0.15, it seems that connection is not possible unless the topic_prefix is changed.
Is this a specification change?

### Version

0.15.0-cea210d

### Frigate config file

```yaml
frigate1(192.168.1.1)
mqtt:
  host: 192.168.1.5
  client_id: frigate1
  user: mqtt-user
  password: password

frigate2(192.168.1.2)
mqtt:
  host: 192.168.1.5
  client_id: frigate2
  user: mqtt-user
  password: password
frigate3(192.168.1.3)
mqtt:
  host: 192.168.1.5
  client_id: frigate3
  user: mqtt-user
  password: password
```

### Relevant Frigate log output

```shell
error
Timestamp
2025-02-14 11:20:44
Tag
frigate.comms.mqtt
Message
MQTT disconnected
```

### Relevant go2rtc log output

```shell
nothing
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate-gpu
    build:
      context: ./Frigate
      dockerfile: Dockerfile
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 40G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # number of GPUs -> 
              capabilities: [gpu]
    #shm_size: default "64mb"  reso:1280*720　の時12.12*n(cameraの台数)+30MB で計算
    shm_size: "8gb" # update for your cameras based on calculation above 7gbから変更
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /NVR_Environment_new/Frigate/config:/config
      - /NVR_Environment_new/Frigate/trt-models:/trt-models
      - /NVR_Environment_new/Frigate/storage:/media/frigate
      - /mnt/camdisk/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 3000000000
    ports:
      - "8971:8971" # ssl port
      - "5000:5000" # non authenticated API
      - "1984:1984" # go2rtc
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: "user"
      FRIGATE_RTSP_PASSWORD: "pasuwado"
      YOLO_MODELS: yolov7x-320 # Add your models here
```

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/71287be1-38a2-4260-8d6a-9fc44756948b)
