### DISCUSSION TITLE
How do I restrict Frigate (docker) to a specific GPU renderD12x when there are multiple on the host?

### DISCUSSION THREAD

**Discussion by jonathanoliver80** [blakeblackshear/frigate#16561] [Ask A Question] [answered]
Since we need to run Frigate docker in privileged mode, all /dev/dri renderers are available to Frigate.  The code in ffmpeg_prests.py doesn't seem to allow for an override on the hardware device, it simply looks for the first renderer in the list that has some sort of acceleration:

```
        if not devices:
            return "/dev/dri/renderD128"


        if len(devices) < 2:
            self._selected_gpu = f"/dev/dri/{devices[0]}"
            return self._selected_gpu


        for device in devices:
            check = vainfo_hwaccel(device_name=device)


```

My problem is that I have a very old CPU with integrated GPU (Haswell) that doesn't support H265.  I have a very new (brand new) discrete graphics card that does support it (Intel Arc A310) and I want to use it instead.

They are listed as:
/dev/dri/renderD128
/dev/dri/renderD129

I simply want Frigate to use my D129 Intel Arc A310 GPU and I cannot find a way to do it.

Thoughts?

--------
For other docker containers (i.e., not Frigate) when I run them as non-privileged I can restrict their visibility to D128 and only pass in D129.  But I can't seem to do that when the container is run as privileged--which is a requirement for Frigate.

Here is my relevant docker compose yaml:

```
 frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD129:/dev/dri/renderD129 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/media/frigate-media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/frigate-cache
        tmpfs:
          size: 8000000000

```

And here is my Frigate ffmpeg configuration:

```
ffmpeg:
  hwaccel_args: preset-vaapi
```

I have even tried not using the preset but it STILL uses D128 despite being explict about using D129:

```
ffmpeg:
  hwaccel_args:
    - -hwaccel_flags
    - allow_profile_mismatch
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD129
    - -hwaccel_output_format
    - yuv420p
```
