### DISCUSSION TITLE
[Bug]: Infinite loading when trying to access video of event for which there is no video recording

### DISCUSSION THREAD

**Discussion by tetele** [blakeblackshear/frigate#16570] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

My Frigate setup did not include continuous recording, but only motion-based recording

```yaml
record:
  enabled: true
  retain:
    days: 1
    mode: motion
```

When creating an event in HA using [`frigate.create_event`](https://github.com/blakeblackshear/frigate-hass-integration/pull/831) with `include_recording: true`, the event did not have any associated video as there was no recording going on, as per the config.

However, in the event detail panel, the Video tab was accessible and, instead of telling me there's no available recording, it just loads forever.

![frigate infinite load](https://github.com/user-attachments/assets/f28d3231-3e1b-4a8b-9d0f-4b040237871e)

### Steps to reproduce

1. set up recoding to NOT be running constantly
2. using the API or the HA integration, create an event (with `include_recordings`) when no alerts/detections/anything else triggers recording
3. in Frigate, go to that event's details
4. notice that a Video tab is accessible. access it

Expected: a notice saying that "no video recording is available for this event" or, even better, a recording for that manually-generated event exists.
Actual: there is a loader in the tab which just spins forever

### Version

0.15.0

### Frigate config file

```yaml
mqtt:
  host: homeassistant.home
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxxxx

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true

database:
  path: /db/frigate.db

model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxx
  labelmap:
    18: other_animal # horse
    19: other_animal # sheep
    20: other_animal # cow
    21: other_animal # elephant
    22: other_animal # bear
    23: other_animal # zebra
    24: other_animal # giraffe

objects:
  filters:
    person:
      # min_area: 15000
      # max_ratio: 0.85
      min_score: 0.7
      threshold: 0.8
    car:
      min_score: 0.75
      threshold: 0.9
    cat:
      min_score: 0.8
      threshold: 0.87
    dog:
      min_score: 0.8
      threshold: 0.87
    other_animal:
      min_score: 0.8
      threshold: 0.9

semantic_search:
  enabled: True
  reindex: False

genai:
  enabled: False
  provider: openai
  api_key: "{FRIGATE_OPENAI_API_KEY}"
  model: gpt-4o

record:
  enabled: true
  
  retain:
    days: 1
    mode: all

  alerts:
    pre_capture: 10
    post_capture: 5
    retain:
      days: 30
      mode: active_objects

  detections:
    pre_capture: 10
    post_capture: 5
    retain:
      days: 10
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 7

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

timestamp_style:
  position: tl
  format: '%d.%m.%Y %H:%M:%S'

go2rtc:
  streams:
    parking:
      - rtsp://{FRIGATE_CAMERA_1}/Streaming/Channels/1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    parking_sub:
      - rtsp://{FRIGATE_CAMERA_1}/Streaming/Channels/102 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    entrance:
      - rtsp://{FRIGATE_CAMERA_2}/Streaming/Channels/1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    entrance_sub:
      - rtsp://{FRIGATE_CAMERA_2}/Streaming/Channels/102 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    backyard:
      - rtsp://{FRIGATE_CAMERA_3}/Streaming/Channels/1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    backyard_sub:
      - rtsp://{FRIGATE_CAMERA_3}/Streaming/Channels/102 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    karlas_room:
      - ffmpeg:rtsp://{FRIGATE_CAMERA_5}/Streaming/Channels/1#video=copy#audio=copy#audio=aac # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    karlas_room_sub:
      - ffmpeg:rtsp://{FRIGATE_CAMERA_5}/Streaming/Channels/102#video=copy#audio=copy#audio=aac # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    frontyard:
      - rtsp://{FRIGATE_CAMERA_6}/Streaming/Channels/1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    frontyard_sub:
      - rtsp://{FRIGATE_CAMERA_6}/Streaming/Channels/102 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
  webrtc:
    candidates:
      - 172.25.0.2:8555
      - 10.16.9.2:8555
      - stun:8555

cameras:
  parking: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/parking_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/parking
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car
        - bicycle
    zones:
      gate:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
      tudors_parking_spot:
        inertia: 5
        coordinates: xxxxxxxxxxxxxx
        objects:
          - person
          - car
          - bicycle
      katis_parking_spot:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - car
          - bicycle
    genai:
      use_snapshot: True
      # prompt: "Analyze the {label} in these images from the {camera} security camera at the front door. Focus on the actions and potential intent of the {label}."
      object_prompts:
        person: "Examine the person in these images taken from a security camera mounted 2.5 meters above a couple of parking spaces. In the lower-right corner of the image is the gate to a frontyard. Regarding the person in the image, What are they doing, and how might their actions suggest their purpose (e.g., delivering something, approaching, leaving)? Summarize their outfit."
        car: "Examine the cars in these images taken from a security camera mounted 2.5 meters above a couple of parking spaces. Describe their color. If possible, name their make and model."
      objects:
        - person
        - car

  entrance: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/entrance
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - bicycle
        - cat
        - dog
        - other_animal
    zones:
      front_entrance:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - bicycle
          - cat
          - dog
          - other_animal
      gate:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - bicycle
          - cat
          - dog
          - other_animal
      lawn:
        inertia: 10
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - bicycle
          - cat
          - dog
          - other_animal

  backyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - other_animal

  karlas_room: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/karlas_room_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
        - path: rtsp://127.0.0.1:8554/karlas_room
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: karlas-room.camera
      port: 80
      user: '{FRIGATE_KARLA_ONVIF_USERNAME}'
      password: '{FRIGATE_KARLA_ONVIF_PASSWORD}'
    audio:
      enabled: true
      listen:
        - speech
        - crying
        - yell
        - scream
        - whispering
        - snoring
    detect:
      width: 640
      height: 360
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
      filters:
        person:
          min_area: 4000
          max_ratio: 0.9
          threshold: 0.75

  frontyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: true
    snapshots:
      enabled: true
    motion:
      mask:
        - xxxxxxxxxxxxxxxx
    objects:
      track:
        - person
        - bicycle
        - cat
        - dog
        - other_animal
      filters:
        person:
          min_area: 4000
          max_ratio: 0.9
          threshold: 0.75
    zones:
      gate:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - bicycle
          - cat
          - dog
          - other_animal
      patio:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - cat
          - dog
          - other_animal
      front_entrance:
        inertia: 5
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - bicycle
          - cat
          - dog
          - other_animal
      lawn:
        inertia: 10
        coordinates: xxxxxxxxxxxxxxxx
        objects:
          - person
          - bicycle
          - cat
          - dog
          - other_animal

logger:
  logs:
    frigate.ptz.onvif: debug
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    shm_size: "224mb"
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/dev/container-apps/frigate/:/config/
      - /mnt/recordings/cameras/frigate:/media/frigate
      - /home/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1500000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      LIBVA_DRIVER_NAME: i965 # https://github.com/blakeblackshear/frigate/issues/4131#issuecomment-1286328869
      FRIGATE_RTSP_PASSWORD: "xxxxxxxxxxxxxxxxx"
      FRIGATE_OPENAI_API_KEY: "xxxxxxxxxxxxxxxxx"
      FRIGATE_CAMERA_1: "xxxxxxxxxxxxxxxxx"
      FRIGATE_CAMERA_2: "xxxxxxxxxxxxxxxxx"
      FRIGATE_CAMERA_3: "xxxxxxxxxxxxxxxxx"
      FRIGATE_CAMERA_5: "xxxxxxxxxxxxxxxxx"
      FRIGATE_CAMERA_6: "xxxxxxxxxxxxxxxxx"
      PLUS_API_KEY: "xxxxxxxxxxxxxxxxx"
      FRIGATE_KARLA_ONVIF_USERNAME: "xxxxxxxxxxxxxxxxx"
      FRIGATE_KARLA_ONVIF_PASSWORD: "xxxxxxxxxxxxxxxxx"
```

### Relevant Frigate log output

```shell
sorry, I've lost those log entries
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

not relevant

### Screenshots of the Frigate UI's System metrics pages

not relevant
