### DISCUSSION TITLE
[Detector Support]: Coral - Green boxes for person detected

### DISCUSSION THREAD

**Discussion by adi98g** [blakeblackshear/frigate#16573] [Detector Support]
### Describe the problem you are having

Hello group of nice and smart people,

At some point from blue, the bounding boxes for person became green . Nice ! After making some changes, now I don't have any more the green but is back to blue. The changes I'm saying are : rtmp enabled, and modify-in some zones (camera moved).
In my understanding, the bounding  box is green when the target meets the filter criteria (probability of detection , area )
I'm out of ideas ; Thanks for giving a hint.

### Version

0.14

### Frigate config file

```yaml
go2rtc:
  streams:
  Carport:
      - rtsp://admin:passwd@192.168.2.14:1036/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#audio=aac
    Carport-ss:
      - rtsp://admin:passwd@192.168.2.14:1036/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    rtmp:
      enabled: true  #
Carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Carport
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Carport-ss
          roles:
            - detect
    detect:
      enabled: true  # 🔴  Adaugă această linie
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.5  # Menține la 0.5-0.6 ca să elimini alarme false
          threshold: 0.6
          min_area: 1700  # Dimensiunea minimă a obiectului detectat (pixeli)
          max_area: 15500  # Dimensiunea maximă a obiectului detectat (pixeli)
        car:
          min_score: 0.5  # Menține la 0.5-0.6 ca să elimini alarme false
          threshold: 0.8
    motion:
      mask:
        - 0.449,0.15,0.449,0.189,0.569,0.183,0.574,0.106
        - 0.097,0.271,0.127,0.449,0.291,0.45,0.05,0.983,0.007,0.983,0.003,0.323
    zones:
      Lat-masini:
        coordinates:
          0.454,0.2,0.575,0.194,0.58,0.135,0.64,0.31,0.615,0.868,0.191,0.836,0.158,0.772,0.412,0.229
        loitering_time: 0
        objects: person
      Terasa-mica:
        coordinates: 0.172,0.843,0.623,0.884,0.66,0.087,0.989,0.311,0.996,0.989,0.119,0.991
        loitering_time: 0

 review:
      alerts:
        required_zones:
          - Lat-masini
          - Terasa-mica
        labels:
          - person
          - car
      detections:
        required_zones:
          - Lat-masini
          - Terasa-mica
        labels:
          - person
          - car		
		  
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb
  #cpu:
  #  type: cpu

detect:
  enabled: true  
  max_disappeared: 30

objects:
  track:
    - person
    - dog
    - cat
    - car

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30
mqtt:
  host: 192.168.1.26
  user: mqtt-user
  password: mqtt-passwd
  topic_prefix: frigate
#mqtt:
#  enabled: false

ffmpeg:
  #hwaccel_args:
  #  - -hwaccel
  #  - vaapi
  #  - -hwaccel_device
  #  - /dev/dri/renderD128
  #  - -hwaccel_output_format
  #  - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac

record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects
    objects:
      - person
      - cat
      - dog
      - car

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
```

### Relevant Frigate log output

```shell
can't find a relevant section in the logs
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/41eacae7-9f98-4ceb-89d7-54a6d4146206)

### Any other information that may be helpful

changed the filtering criteria, changed the max_disappeared: 30   to 60, 90 ...No any help.
