### DISCUSSION TITLE
Audio delay with RTMP/HTTP stream but not with RSTP

### DISCUSSION THREAD

**Discussion by katschub88** [blakeblackshear/frigate#16599] [Config Support]
### Describe the problem you are having

I set up a mini pc (AMD 5700U, 32GB ram, 4TB nvme) as frigate server at a friends house (used the same hardware and setup several times before and they all work fine) and added a Reolink Doorbell V2 (Firmware: v3.0.0.4110_2410111119).

If I use the recommended settings for Reolink Doorbells (http+flv), there is an audio dalay in the recordings.
At first it seems to be synchronous, but after 6 hours there is a delay of about 0.5 seconds.
After 24 hours there is a delay of about 1 second.
After 3 days there is a delay of about 2 seconds.
So far it stayed under 3 seconds after running for over a week.

I have tried other options (see config), including HTTPS+FLV, RTMP and RTSP.
The only stream without any audio delay is RTSP, this seems to be the most reliable variant so far.

Unfortunately the RTSP stream causes occasional errors, which result in image corruption and these errors seem to get worse over time, up to the point where you have to restart the doorbell and frigate.

I've done a lot of research, but found no solution yet. Any idea what is causing the audio delay in the recommended FLV stream and how I can fix this?
Or if not, any idea what is causing the RTSP errors and how to fix these?
Anything would be fine, if the recordings keep running stable without major image corruption.

It doesn't seem to be a server problem, as the same setup works fine in other cases.
There are plenty of ressources left and it happens with the cleaned up "record-only" config (no detection, no zones, etc.) too.

### Version

0.13, 0.14 and 0.15 (all the same behavior)

### Frigate config file

```yaml
...

ffmpeg:
  hwaccel_args: preset-vaapi  #<<<(Also tried without)

go2rtc:
  log:
    format: text
    level: "debug"
    exec: trace
  streams:
    doorbell_cam:
      - rtsp://user:password@ip/Preview_01_main
      #- "ffmpeg:rtmp://ip/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password#video=copy#audio=copy#audio=opus"
      #- rtmp://ip/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password
      #- "ffmpeg:http://ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
      #- "ffmpeg:https://ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"


cameras:
  doorbell:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy

    record:
      enabled: True
      retain:
        days: x
        mode: all
```

### Relevant Frigate log output

```shell
No log entries with the RTMP/HTTP/HTTPS streams.

Different errors with RTSP (occasionally, seem to build up over time):
- error while decoding MB x xx, bytestream -xx
- left block unavailable for requested intra mode

I can see the "error while decoding MB" errors in the recordings. They show as blurry areas at the bottom of the screen and only last a fraction of a second. Some are smaller, others larger.
The "left block" errors are more severe and last longer.
```

### Relevant go2rtc log output

```shell
No errors
```

### Operating system

Other Linux

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
Not relevant
```

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
What firmware version are you running on the doorbell?

**Comment by katschub88** [comment]
As I've said in the original post, it's currently at the latest firmware (Firmware: v3.0.0.4110_2410111119).

But I've also tried different versions. In particular:
- 4110_2410111119
- 3308_2407315182
- 3215_2401262240

Always reset the configuration to start clean.

These are the latest errors from the current RTSP stream:

2025-02-15 18:36:18.149233801  [h264 @ 0x72992811c940] left block unavailable for requested intra4x4 mode -1
2025-02-15 18:36:18.149238610  [h264 @ 0x72992811c940] error while decoding MB 0 110, bytestream 29285

(go2rtc logs show no errors at all)

The video image is damaged about 10 seconds before the logging time. It affects about 40% of the total height (from the bottom) for about 2 seconds. The audio seems completely fine, no stuttering, no missing parts.

**Reply by hawkeye217** [reply]
These errors just are indicative of bad data being sent from the camera.

**Reply by katschub88** [reply]
These are from the RTSP config. I've only added them in case they might be of interest.

The main focus is the recommended HTTP/RTMP streams, which causes audio delays as described above.
Any idea what could be causing them and how to fix this problem?

Btw, is there an option to set input_args for go2rtc?

**Reply by hawkeye217** [reply]
Have you tried using `preset-record-generic-audio-aac` for your record output args to see if that helps?

**Reply by katschub88** [reply]
No, but I can test it, but it will take some time.
Any other ideas in the meantime?

**Reply by hawkeye217** [reply]
If you search the past discussions, you'll find that this is a common issue with Reolink doorbells specifically. Here's one example that came to mind: https://github.com/blakeblackshear/frigate/discussions/9430

For some users, the RTSP stream works well. For the majority though, the HTTP stream has been the most stable, which is why it's recommended in the docs.

One user did find success using the RTSP stream outside of go2rtc this way:

```
go2rtc:
  streams:
    frontdoor_sub: 
      - "ffmpeg:http://192.168.0.zzz/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=uuuu&password=pppp"

cameras:
  frontdoor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://uuuu:pppp@192.168.0.zzz:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```

**Reply by katschub88** [reply]
I've read many of these threads and tried so many things mentioned there, this has been a problem for weeks now.
There are so many little details that might change the outcome, like 24/7 recording vs alerts only, doorbell variant and version, poe or wifi, firmware, ffmpeg version, go2rtc version, server hardware, networking, etc.

So far, the RTSP stream has the best quality, but has decoding errors.
I've noticed that the cpu usage of the Reolink Doorbell was about between 80+% with just streaming to frigate using the above config.
(Possible cause of these problems)

Anyway, I wanted to use the recommended stream, as mentioned in the frigate docs.
However, this stream introduced the audio delay. So I am looking for tweaks to fix this issue.
Or more input from people who have been using that doorbell without any issues for an extended period.

I've changed the config for testing like this yesterday:

```
go2rtc:
  streams:
    doorbell:
      - rtsp://user:password@ip:554/Preview_01_main

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: https://ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password
          input_args: preset-http-reolink
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
```


I'll have to wait until later today to get the results.
Will also try out the config you've posted and the preset-record-generic-audio-aac, although I might have already tried that before (I'm not sure).
