### DISCUSSION TITLE
[Config Support]: Zone/Loiter Recording problem

### DISCUSSION THREAD

**Discussion by jfh250** [blakeblackshear/frigate#16596] [Config Support]
### Describe the problem you are having

Hoping I can get a bit of help? New to Frigate, I’ve spent a long time reading documentation but still struggling with more than the most basic config.yml

I’m trying to take it to the next level but get problems:

**What I would like:**

I have defined 2 zones. “Driveway” and “Road”.

In the **Driveway Zone**: I want to record all **moving** people/cars, ignore shadows/trees – anything that doesn’t fit person/car to be discarded. Keep anything verified as a moving person/car for 35 days.

In the **Road Zone**: I want to record all people, **but** only record cars if are in the scene for 7+ seconds (loiter time??). I want to stop recording cars if they become stationary. The idea is to avoid recording cars passing by normally, but have some record of cars that remain longer than normal.

**What’s Actually happening:**

**All** cars passing by **(Road zone)** are being recorded as alerts in my “Review items” as well as appearing in Explore as “tracked objects”. However, the loitering for 7 seconds requirement appears to be ignored. When exploring object lifecycle there is no zone associated with the alert. **People** are being recorded (correct) but similarly not associated with the **Road** zone.

I haven’t yet had a car enter the **Driveway** zone to test. However, a **person** is correctly recorded and appearing as a “Review item” in the **Driveway** zone.

I’m in well over my head with this but hope if someone can correct what I’ve got wrong it’ll start to make more sense.
Grateful to anyone who can help.

### Version

0.15-1

### Frigate config file

```yaml
mqtt:
  enabled: false  # Disable MQTT if not using it

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@192.168.1.5:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://frigate:password@192.168.1.5:554/Streaming/Channels/101
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
    record:
      enabled: true
      retain:
        days: 35  # Keep recordings for 35 days
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 35  # Keep snapshots for 35 days
    motion:
      mask:
        - 0.268,0.047,0.268,0.082,0.334,0.082,0.334,0.039
        - 0.429,1,0.137,0.618,0.004,0.727,0.001,0.993
        - -0.001,0.354,0.08,0.251,0.136,0.237,0.144,0.038,0.132,0,-0.001,0.001
        - 1,0.182,0.665,0.074,0.394,0.066,0.157,0.086,0.147,0.005,0.996,0.001
        - 0.819,0.993,1,0.357,0.999,0.994
        - 0.242,0.188,0.233,0.215,0.35,0.238,0.426,0.242,0.429,0.205,0.328,0.184
      threshold: 35
      contour_area: 20
      improve_contrast: true
    zones:
      Driveway:
        coordinates: 
          0.313,0.988,0.916,1,0.956,0.428,0.885,0.374,0.686,0.32,0.695,0.294,0.457,0.221,0.44,0.193,0.416,0.154,0.235,0.137,0.112,0.149,0.002,0.28,0.003,0.761
        filters:
          person:
            min_area: 5000  # Adjust as needed to filter out false positives
          car:
            min_area: 8000  # Adjust as needed
      Road:
        coordinates: 
          0.974,0.355,1,0.107,0.657,0.009,0.521,0,0.15,0,0.147,0.111,0.429,0.155,0.452,0.214,0.688,0.282,0.766,0.318
        filters:
          person:
            min_area: 5000  # Adjust as needed
          car:
            min_area: 8000  # Adjust as needed
        loitering_time: 7  # Record cars only if they linger for 7 seconds or more
        inertia: 3

version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate  # Name of the running container
    image: ghcr.io/blakeblackshear/frigate:stable  # Latest stable Frigate image
    restart: unless-stopped  # Ensures Frigate restarts if it crashes or after a reboot
    shm_size: "128mb"  # Shared memory for FFmpeg (increase if video stuttering occurs)

    ports:
      - "5000:5000"  # Frigate Web UI
      - "8554:8554"  # RTSP restream (allows you to re-stream camera feeds)
      - "8555:8555/udp"  # WebRTC (for low-latency video streaming)

    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral TPU to the container
      - /dev/dri/renderD128:/dev/dri/renderD128  # Passes Intel GPU for hardware acceleration

    cap_add:
      - CAP_PERFMON  # Grants performance monitoring capability to resolve PMU error

    security_opt:
      - "seccomp=unconfined"  # Allows performance monitoring (fixes PMU error)
      - "apparmor=unconfined"  # Avoids security restrictions on GPU polling

    volumes:
      - /opt/frigate/config:/config  # Configuration files are stored here
      - /mnt/frigate/recordings:/media/frigate  # Location for recorded clips
      - /etc/localtime:/etc/localtime:ro  # Syncs time with the host
      - type: tmpfs  # Temporary RAM storage to reduce disk wear
        target: /tmp/cache
        tmpfs:
          size: 512000000  # 512MB cache (adjust as needed)

    environment:
      FRIGATE_RTSP_PASSWORD: "your_rtsp_password"  # RTSP password for secure camera streaming
      LIBVA_DRIVER_NAME: "iHD"  # Specifies Intel hardware acceleration driver
      LIBVAAPI_ENABLE: "1"  # Enables VAAPI support for video decoding
      LIBVA_TRACE: "1"  # Enables debugging logs for VAAPI if needed
```

### Object Detector

Coral
