### DISCUSSION TITLE
[Config Support]: No detections or motion on a single one of my cameras

### DISCUSSION THREAD

**Discussion by DrissiReda** [blakeblackshear/frigate#16598] [Config Support]
### Describe the problem you are having

My "backyard" camera has no detections nor motions despite things happening.
The "front" camera works as intended.
However the bandwidth consumed by "backyard" is 2.85G/hour while "front" is 1.34 G/hour.

I had same detect settings for both fps at 5 and resolution at max 2560x1440. I tried changing it by increasing fps, then decreasing resolution it changes nothing.

Any help is welcome. Even for improving something else.

### Version

0.15.0

### Frigate config file

```yaml
tls:
  enabled: false
motion:
  threshold: 200
  contour_area: 100
cameras:
  backyard:
    detect:
      fps: 10
      width: 1280
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - car
  front:
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      required_zones:
        - front_street
    detect:
      fps: 5
      height: 1440
      width: 2560
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - car
    onvif:
      host: '{FRIGATE_REO1_IP}'
      port: 8002
      user: '{FRIGATE_REO1_USER}'
      password: '{FRIGATE_REO1_PASS}'
    motion:
      mask:
        - 0.003,0.503,0.49,0.11,0.36,0,0.005,0.001
        - 0.496,0.116,0.744,0.017,0.367,0.001
        - 0.938,0.442,0.757,0.232,0.94,0.003,0.982,0.008
      threshold: 100
      contour_area: 9
      improve_contrast: true
    zones:
      front_garage:
        coordinates: 
          0.643,0.305,0.684,0.265,0.837,0.287,0.883,0.341,0.886,0.487,0.847,0.603,0.61,0.376
        loitering_time: 0
        objects: car
      front_street:
        coordinates: 0.471,0.154,0.613,0.075,0.728,0.151,0.635,0.262
        loitering_time: 0
detectors:
  coral:
    device: pci:0
    type: edgetpu
go2rtc:
  streams:
    backyard:
      - ffmpeg:http://{FRIGATE_REO1_IP}:8081/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REO1_USER}&password={FRIGATE_REO1_PASS}
    backyard_sub:
      - ffmpeg:http://{FRIGATE_REO1_IP}:8081/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_REO1_USER}&password={FRIGATE_REO1_PASS}
    front:
      - ffmpeg:http://{FRIGATE_REO1_IP}:8082/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REO1_USER}&password={FRIGATE_REO1_PASS}
    front_sub:
      - ffmpeg:http://{FRIGATE_REO1_IP}:8082/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_REO1_USER}&password={FRIGATE_REO1_PASS}

mqtt:
  host: rabbitmq.surveillance
  password: ${MQTT_PASSWORD}
  port: 1883
  user: rabbit
record:
  enabled: true
  export:
    timelapse_args: -vf setpts=0.03*PTS -r 30
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
snapshots:
  enabled: true
version: 0.15-0
semantic_search:
  enabled: true
  reindex: true
  model_size: small
```

### Relevant Frigate log output

```shell
no log related to this
```

### Relevant go2rtc log output

```shell
works as intended
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
I'm using a Kubernetes deployment.

I use mostly the CPU and have a coral TPU for classifications.
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/218b7a7e-db93-45c3-bdb5-020bace4c052)
![image](https://github.com/user-attachments/assets/5b5edaef-1265-4288-8934-a523f652e6ee)
