### DISCUSSION TITLE
[HW Accel Support]: Intel N100 CPU with Home Assistant OS 14.2

### DISCUSSION THREAD

**Discussion by kkevindev** [blakeblackshear/frigate#16609] [Hardware Acceleration Support]
### Describe the problem you are having

Just does not seem to be using the GPU on my machine. Having a high CPU % (± 20% per camera) and 0% GPU.

Also, weird thing I've noticed is that I've disabled my detect in the config but it says something about detecting started
<img width="891" alt="afbeelding" src="https://github.com/user-attachments/assets/457ce3f1-95a4-4ca1-973f-5bf9e2bf3a9a" />

### Version

0.15-1

### Frigate config file

```yaml
version: 0.15-1

go2rtc:
  streams:
    poort:
      - rtsp://admin:redacted@192.168.2.240/cam/realmonitor?channel=1&subtype=0

birdseye:
  enabled: false

ui:
  time_format: 24hour

environment_vars:
  LIBVA_DRIVER_NAME: iHD

record:
  enabled: true
  retain:
    mode: all
    days: 7

snapshots:
  enabled: false

detect:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  poort:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/poort
          roles:
            - record
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
Has some "[vf#1:0 @ 0x55ff29bf9900] Task finished with error code: -5 (Input/output error)" errors sometimes.
```

### Relevant go2rtc log output

```shell
no errors
```

### FFprobe output from your camera

```shell
-
```

### Install method

HassOS Addon

### Object Detector

Other

### Network connection

Wireless

### Camera make and model

Imou Rex 3D

### Screenshots of the Frigate UI's System metrics pages

<img width="227" alt="afbeelding" src="https://github.com/user-attachments/assets/2d2bd786-cdde-404d-8f87-d1d51219ffc2" />

<img width="1212" alt="afbeelding" src="https://github.com/user-attachments/assets/4573eaa7-afac-46b5-911c-bc736b11ba3a" />

<img width="590" alt="afbeelding" src="https://github.com/user-attachments/assets/a929eeb3-bee9-4f1a-b308-a626e5a00583" />

**Comment by hawkeye217** [comment]
Even though you have disabled detection, Frigate still needs to decode a stream for other features. See the note in the official docs about the `detect` role: https://docs.frigate.video/configuration/cameras/#setting-up-camera-inputs

> 
> If you only define one stream in your inputs and do not assign a detect role to it, Frigate will automatically assign it the detect role. Frigate will always decode a stream to support motion detection, Birdseye, the API image endpoints, and other features, even if you have disabled object detection with enabled: False in your config's detect section.
> 
> If you plan to use Frigate for recording only, it is still recommended to define a detect role for a low resolution stream to minimize resource usage from the required stream decoding.

**Reply by kkevindev** [reply]
Thanks, best thing for me to do to virtually disable it with a resolution of 1x1 for the detect role?
> define a detect role for a low resolution stream to minimize resource usage from the required stream decoding.

**Comment by NickM-27** [comment]
You should be using qsv not vaapi with this hardware. We can tell it is using the GPU though based on the errors. There is a bug with Intel GPU stats for some users.

**Reply by kkevindev** [reply]
Since I have a H265 stream from the camera I used `hwaccel_args: preset-intel-qsv-h265` (https://docs.frigate.video/configuration/hardware_acceleration#h265-streams).

But this still gives me no GPU usage:
<img width="214" alt="afbeelding" src="https://github.com/user-attachments/assets/c43e0caf-d735-4a67-9299-352194e9c7c3" />


This is a 12th gen CPU (Alder Lake-N) and based on https://docs.frigate.video/configuration/hardware_acceleration#intel-based-cpus I thought QSV was not supported. So that is why I thought I needed VAAPI.

**Reply by kkevindev** [reply]
I got some life after using the `preset-intel-qsv-h265` argument now!!

<img width="204" alt="afbeelding" src="https://github.com/user-attachments/assets/f06b8a9f-c54c-4bd4-9b59-2e50c8678c3e" />

However, why is it this low? CPU % is still high and GPU is <0.1%

**Reply by NickM-27** [reply]
Qsv is supported, just not the default but it really depends on a lot of variables. We need to see full screenshots of the system and camera stats to know what is using cpu

**Reply by kkevindev** [reply]
The ffmpeg process is still using (alot) of CPU %, see here:
<img width="664" alt="afbeelding" src="https://github.com/user-attachments/assets/82d5e328-9f46-4ae2-98ab-38ff7c86915b" />

**Reply by NickM-27** [reply]
What resolution stream is being processed?

**Reply by kkevindev** [reply]
@NickM-27 2880x1620

**Reply by NickM-27** [reply]
I'd suggest lowering the detect size then, that is a lot of detail to process without good reason. Your camera resolution and detect width / height do not need to match

**Reply by kkevindev** [reply]
@NickM-27 I have set:
```
detect:
  enabled: false

model:
  width: 1
  height: 1
```

but this does not decrease the CPU % or increase the GPU %.
