### DISCUSSION TITLE
[Support]: Is it normal for Friagte to struggle so much with tracking stationary cars that are parked next to eachother?

### DISCUSSION THREAD

**Discussion by J-Pipe** [blakeblackshear/frigate#16610] [General Support]
### Describe the problem you are having

When I have two cars parked in my driveway, with bounding boxes partially overlapping, Frigate is constantly (several times per minute) seeing and losing the cars. Even though there is little-to-no movement happening. Is there a good way to alleviate this issue, so that my "Explore" database is actually usable?

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: ...
  user: ...
  password: ...

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: ...

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-blue-iris

snapshots:
  enabled: true
  clean_copy: true
  crop: false
  required_zones:
    - driveway_car_zone
  bounding_box: true
  retain:
    default: 1

objects:
  filters:
    car:
      min_score: .8
      threshold: .85

detect:
  enabled: true
  width: 1280
  height: 720

cameras:
  driveway_cam:
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      preview:
        quality: medium
      alerts:
        retain:
          days: 2
      detections:
        retain:
          days: 1
    detect:
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - detect

    objects:
      track:
        - car
      mask:
        - 1061,0,1280,0,1280,216,1155,207,1099,191,1030,158,996,115,790,101,597,96,579,0
      filters:
        car:
          mask:
            - 0.741,0.251,0.812,0.254,0.848,0,1,0,1,0.592,0.893,0.486,0.808,0.511,0.598,0.389,0.499,0.268
            - 0.829,0,1,0,1,0.3,0.902,0.287,0.859,0.265,0.805,0.219,0.778,0.16,0.617,0.14,0.466,0.133,0.452,0
            - 0.829,0,1,0,1,0.3,0.902,0.287,0.859,0.265,0.805,0.219,0.778,0.16,0.617,0.14,0.466,0.133,0.452,0
          min_area: 0
          max_area: 350000
          #threshold: 0.55
    motion:
      mask:
        - 0.762,0.497,1,0.571,0.973,0.699,0.895,0.932,0.877,1,1,1,1,0.658,1,0,0,0,0,0.19,0.292,0.096,0.439,0.1,0.477,0.174,0.622,0.164,0.689,0.144,0.799,0.175,0.796,0.299,0.729,0.314,0.639,0.318,0.619,0.399,0.652,0.407,0.702,0.454
        - 0.298,1,0.227,0.857,0,0.829,0,1
        - 0.697,0.288,0.695,0.185,0.742,0.137,0.793,0.165,0.8,0.268,0.786,0.376,0.726,0.416,0.669,0.384,0.673,0.318
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
    mqtt:
      enabled: false
    zones:
      driveway_car_zone:
        coordinates: 
          0.099,1,0.794,1,0.921,1,0.938,0.849,0.968,0.626,0.742,0.508,0.609,0.475,0.521,0.408,0.106,0.56
        objects:
          - car
        filters:
          car:
            min_area: 40000
            max_area: 350000
            #threshold: 0.55
        inertia: 3
        loitering_time: 0
      street_car_zone:
        coordinates: 
          0.521,0.408,0.514,0.296,0.574,0.261,0.782,0.253,0.698,0.197,0.483,0.196,0.209,0.23,0,0.304,0,0.411,0.074,0.446,0.106,0.56
        objects: car
        filters:
          car:
            min_area: 5000
            max_area: 100000
        inertia: 1
        loitering_time: 0
      curb_car_zone:
        coordinates: 
          0,0.47,0.191,0.451,0.408,0.366,0.567,0.305,0.716,0.28,0.708,0.225,0.496,0.239,0.341,0.26,0.182,0.3,0,0.375
        objects:
          - car
        inertia: 30 
        max_disappeared: 200 
        loitering_time: 0
 
    review:
      alerts:
        required_zones:
          - driveway_car_zone
 
version: 0.15-1
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

<img width="901" alt="Screen Shot 2025-02-15 at 10 11 57 PM" src="https://github.com/user-attachments/assets/4e42cfbb-9670-48c3-b3a8-e17412190624" />

<img width="901" alt="Screen Shot 2025-02-15 at 10 12 14 PM" src="https://github.com/user-attachments/assets/d7a98a88-083d-4d37-810a-04cfb14344a4" />

<img width="901" alt="Screen Shot 2025-02-15 at 10 12 27 PM" src="https://github.com/user-attachments/assets/a4fe3d4d-68d3-498c-855c-a0f7f52d33ac" />

<img width="621" alt="Screen Shot 2025-02-15 at 10 46 39 PM" src="https://github.com/user-attachments/assets/ba94a61b-43a0-48e4-9b65-4cdf8c3fc62c" />

https://github.com/user-attachments/assets/a09f5b8b-8492-449b-9ae7-8fb99e041515

<img width="960" alt="Screen Shot 2025-02-15 at 10 28 45 PM" src="https://github.com/user-attachments/assets/f3f2db44-7a45-4e48-8d27-9bdae32b11d0" />
