### DISCUSSION TITLE
[Support]: Frigate Missing Config After Docker Re-pull / Update

### DISCUSSION THREAD

**Discussion by AT-StephenDetomasi** [blakeblackshear/frigate#16616] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Hi there,

I recently updated my Frigate Docker container as I was having intermittent issues with "no frames detected" across all my cameras. I did this by logging into portainer, and re-created the container and asked it to re-pull the image.

After the container is back up, all my configs are gone. No cameras, no groups, just a black screen. Surely this is not the expected behaviour? Thankfully I made a backup of setup. Below is a snippet of the stack I used for initial deployment.

I tried visiting the WebUI Settings --> Logs but none of the options under settings seem to load anymore.  Suggestions on how to resolve this issue would be appreciated.

### Steps to reproduce

1. Deploy stack in Portainer (see issue)
2. Setup a config
3. Remove and re-pull the docker container to update the container. Config will be missing.
...

### Version

0.15

### In which browser(s) are you experiencing the issue with?

Google Chrome Version 132.0.6834.197

### Frigate config file

```yaml
Missing
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: at-nvr-01 #CHANGE
    privileged: true #this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable

    shm_size: "256mb" #CHANGE for your cameras based on calculation

    devices:  
      - /dev/dri/renderD128 #CHANGE for intel hwaccel needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/frigate.yml:/config/config.yml:ro  #CHANGE to match your setup
      - /mnt/at-dh-01/:/media/frigate #CHANGE to match your setup
      - /root/frigate:/db #CHANGE to match your setup
    ports:
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXXX"  #CHANGE to whatever if using rtsp
```

### Relevant Frigate log output

```shell
Missing
```

### Relevant go2rtc log output

```shell
Missing
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/f493ef5e-3459-464a-bfed-7d9ffcdbed7e)
