### DISCUSSION TITLE
Add Audio to IP Cam[Camera Support]:

### DISCUSSION THREAD

**Discussion by vjmaz** [blakeblackshear/frigate#16622] [Camera Support]
### Describe the problem you are having

No Problem just not that good at Yaml or code in general 
 I have 2 ICSEE 360 cameras that have audio also I have hooked up one and I can get audio from app or browser on pc even with rtsp from VLC Media player ... just not sure how to add to my simple config setup team to capture at least if possible listen on live view.

I will attach my config which works well for just video and alerts notifications frigate card etc etc 
also screen shots of the vlc media for audio format even tho might be best to use aac ? 

### Version

15

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.25
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: FRIGATE_AWESOME
  password: Password
  stats_interval: 60

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1



cameras:
  office:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.2.24:554/user=banana&password=Tooh0t&channel=1&stream=0.sdp?
          roles:
            - record
        - path: rtsp://admin:@192.168.2.24:554/user=banana&password=Tooh0t&channel=1&stream=1.sdp?
          roles:
            - detect
    detect:
      width: 640
      height: 720
      fps: 12

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  detections:
    retain:
      days: 1




############################################################################################################
############################################################################################################
####  ADD Cams Above this section only do not touch the bottom version needs to be their to work !!!
############################################################################################################
version: 0.15-1
```

### Relevant Frigate log output

```shell
not sure were to get this from
```

### Relevant go2rtc log output

```shell
not sure were to get this from 
need help to setup go2rtc later anyway
```

### FFprobe output from your camera

```shell
not sure were to get this from
```

### Frigate stats

```json
not sure were to get this from
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

china 360 cam

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/5e02ab00-5002-4372-a12f-094bcc54d0cd)

### Any other information that may be helpful

j
