### DISCUSSION TITLE
Notification debugging support

### DISCUSSION THREAD

**Discussion by dskvml** [blakeblackshear/frigate#16624] [Ask A Question]
Hey,

i have Frigate v15.0 running with the native notifications enabled. This worked quite well for me, for some time, but lately the notifications started to only appear ~1min after the review alert had been created in the GUI on my Android device(battery optimization is disabled, Progressive Web App installed). 

I have a setup with Cloudflare Tunnel -> Frigate for external access and Pi-Hole -> NGINX -> Frigate for internal access, so some different applications were things could go wrong.

What would be the best way to debug when the notification is sent on its way from Frigate, to check if the delay is produced by Frigate or by any of the other steps in between?

Thanks!

**Comment by hawkeye217** [comment]
There are no debugging logs you can enable in 0.15 (though there will be in 0.16). 

You could add them to this file and drop it in your container, if you want: https://github.com/blakeblackshear/frigate/blob/master/frigate/comms/webpush.py

**Reply by dskvml** [reply]
Thanks for the hint, maybe ill try that.
Just to align the expected behaviour, when is the notification supposed to be sent? Is it as soon as the review item is created in the UI? Or is it as soon as a relevant object is entering a review zone? Or is it when the event has ended?

**Reply by NickM-27** [reply]
Notifications are sent right when the review item starts, any updates, and again when it ends

**Reply by dskvml** [reply]
Ok thanks. I think the delay I experience is coming from Frigate not starting the review item right away. Really strange behaviour:

Sometimes, everything works well and i get the notification in the moment a person enters a zone. In the Frigate Live view, a Review Item is created "Just Now".

If things go wrong (same setup, person entering a zone) the notification is delayed by a minute. In the Frigate live view, no Review item is created. After a minute, the review item pops up "1 minute ago", and the notification is received immediately. 

Any ideas how I can consistently create a "Just Now" review item and the connected notification?

(On a different note: Is it possible to group notifications (at least on Android this is a function)? This would make it easier to dismiss all notifications at once)

**Reply by dskvml** [reply]
Hey again,

did not want to open a new topic: I did some testing with Frigate 16 Beta 1 and the new button to send test notifications. I can now exclude that the delay has something to do with my cloudflare / PiHole / NGINX setup, as with the button push the notification is there immediately.

The issue described above still persists: 

0s: A person enters a zone,
<1s:  i get the red box around the camera feed in live view, the person icon appears in the top left corner (in my understanding, here the event should be created)
30s+: The Review Item is created (i get the review item above the live feed)
60s+: A notification is sent

What kind of logs would you need to help me identify where the delay is coming from? Does it make sense to post my whole config here?

Thanks for your support again!

(The question about notification grouping is also still valid ;) )

**Reply by NickM-27** [reply]
we will need to see a full copy of your config for starters

**Reply by NickM-27** [reply]
grouping of notifications is not supported by the browsers currently

**Comment by dskvml** [comment]
```
auth:
  enabled: true
  reset_admin_password: false

mqtt:
  enabled: true
  host: 192.168.1.12
  port: 1883
  topic_prefix: frigate

genai:
  enabled: false
  provider: gemini
  api_key: xxx
  model: gemini-2.0-flash

go2rtc:
  streams:


    CX810:
    
      - rtsp://xxx:yyy1@192.168.1.184:554/Preview_01_main
 




  CX810:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://xxx:yyy@192.168.1.184:554/Preview_01_main

          roles:
            - detect
            - record

    genai:
      enabled: false

    detect:
      height: 1080
      width: 1920
      fps: 5
      enabled: true
      annotation_offset: -800
    motion:
      enabled: true
      mask:
        - 0.403,0,0.595,0,0.597,0.031,0.402,0.033
        - 0.002,0.412,0,0,0.384,0,0.325,0.111,0.288,0.184,0.25,0.262,0.221,0.335,0.224,0.382,0.192,0.439,0.001,0.472
        - 0.78,0.024,0.837,0.272,0.942,0.267
        - 0.895,0.358,0.898,0.406,0.997,0.406,1,0.354
    record:
      enabled: true
      retain:
        days: 10
        mode: all

    objects:
      track:
        - person
        - car
      #  - dog
      #  - cat
      filters:
        car:
          mask: 0.185,0.496,0.245,0.485,0.249,0.569,0.191,0.563
    review:
      detections: {}
      alerts:
        required_zones:
          - Einfahrt
          - Garten
          - Hof
          - Haustuer
          - Zufahrt
    zones:
      Einfahrt:
        coordinates: 0.067,0.641,0.209,0.615,0.255,0.623,0.274,0.631,0.274,0.677,0.08,0.719
        inertia: 3
        objects: person
      Hof:
        coordinates: 
          0.019,0.733,0.276,0.68,0.275,0.548,0.329,0.557,0.421,0.54,0.567,0.552,0.593,0.54,0.597,0.697,0.98,0.851,0.96,0.999,0.033,1
        inertia: 3
        objects: person
      Garten:
        coordinates: 
          0.595,0.539,0.821,0.462,0.822,0.555,0.867,0.557,0.91,0.515,0.942,0.519,1,0.519,1,0.567,0.999,0.659,0.98,0.852,0.599,0.693
        inertia: 3
      Zufahrt:
        coordinates: 0.066,0.642,0.217,0.616,0.215,0.608,0.062,0.633
        inertia: 3
      Haustuer:
        coordinates: 
          0.196,0.616,0.2,0.625,0.215,0.643,0.248,0.582,0.248,0.547,0.229,0.575,0.202,0.602
        inertia: 1
        objects: person
    notifications:
      enabled: true
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


version: 0.16-0
notifications:
  enabled: true
  email: dskvml@mail.de
semantic_search:
  enabled: true
  reindex: false
  model_size: small

detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
classification:
  bird:
    enabled: true
```
