### DISCUSSION TITLE
[Detector Support]: Is it possible to add tracking_ID to objects in the detector module openvino?

### DISCUSSION THREAD

**Discussion by balamonica** [blakeblackshear/frigate#16625] [Detector Support]
### Describe the problem you are having

I want to save the list of detections while running openvino.py in a csv file. To avoid duplication, I want to create unique object ID for each detected objects across the frame. Is it possible to use bytetracker?

### Version

0.15

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  model_type: ssd
  input_pixel_format: bgr
  path: /models/ssdlite/ssdlite_mobilenet_v2.xml
  labelmap_path: /models/ssdlite/coco_91cl_bkgr.txt

objects:
  track:
    - person

  filters:
    person:
      min_score: 0.5
      threshold: 0.7

cameras:
  test:
    enabled: true
    ffmpeg:
      inputs:
        - path: /media/frigate/demo_long_redu_pixel.mp4
          input_args: -re -stream_loop -1
          roles:
            - detect
            - record
            - snapshots
    zones:
      full:
        coordinates: 0.011,0.016,0.991,0.013,0.991,0.986,0.007,0.977
        loitering_time: 0
        objects: person
detect:
  fps: 10
  height: 360
  width: 640
  enabled: true
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true  # Enable bounding box drawing
  crop: true          # Enable cropping of detected objects
  quality: 60
#record:
#  enabled: true

motion:
  enabled: True
  threshold: 30

version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
#version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: frigate:latest
    shm_size: "1gb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - ./models:/models:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
NA
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

NA
