### DISCUSSION TITLE
Alert one object across entire camera but another object only in specific zone on same camera

### DISCUSSION THREAD

**Discussion by mbronstein1** [blakeblackshear/frigate#16638] [Ask A Question]
I'm wondering what the best approach is for handling detecting a specific object inside of a zone ONLY but another object across the entire camera. I feel like there are some redundancies in my config, but I'm not sure what to remove or add to get the desired outcome. I think getting another eye on it would help.
```yaml
  Ext_Entry_Road:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/****
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/****
          roles:
            - record
    live:
      stream_name: ext_entry_road
    review:
      alerts:
        labels:
           - person
           - vehicle
        required_zones: &ref_3
          - entry_road
    snapshots:
      required_zones: *ref_3
    zones:
      entry_road:
        coordinates: >-
          0.32,0.264,0.001,0.354,0.001,0.843,0.378,0.742,0.994,0.982,0.999,0.579,0.727,0.354
        objects: 
          - vehicle
        inertia: 1
    objects:
      track: 
         - person
         - vehicle
```
