### DISCUSSION TITLE
[Support]: Reolink POE white doorbell 2-way audio

### DISCUSSION THREAD

**Discussion by JSa1987** [blakeblackshear/frigate#16631] [General Support] [answered]
### Describe the problem you are having

For the last couple of days I have been trying to setup the 2-way audio for a White Reolink POE Doorbell. Reading several post on troubleshooting for the same setup I have now managed to get this working when connecting to the Frigate UI via HTTPS, but I still cannot get this working in Home Assistant.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox 135.0 (50174) - On IPhone

### Frigate config file

```yaml
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - Frigate_IP:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"
  streams:
    doorbell_camera:
      - rtsp://admin:PWD@Reolik_IP:554/
      - ffmpeg:http://Reolik_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PWD#audio=opus#audio=volume
    doorbell_camera_sub:
      - rtsp://admin:PWD@Reolik_IP:554/h264Preview_01_sub
      - ffmpeg:http://Reolik_IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=PWD#audio=opus#audio=volume
cameras:
  doorbell_camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell_camera
    onvif:
      host: Reolink_IP
      port: 8000
      user: admin
      password: PWD
```

### Relevant Frigate log output

```shell
Nothing logged in the Frigate Logs
```

### Relevant go2rtc log output

```shell
2025-02-17 07:29:08.212244793  07:29:08.212 ERR [exec] error="exec: \"ffmpeg\": executable file not found in $PATH" url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://Reolink_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PWD -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -af \"volume=25dB\" -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/82249063281a4d82eb1fa3310ac206c7"
```

### FFprobe output from your camera

```shell
bash: ffprobe: command not found
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.8"
networks:
  cctvipvlan:
    external: true

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable

    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/frigate/config:/config
      - /mnt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    hostname: host.domain
    networks:
      cctvipvlan:
        ipv4_address: Frigate_IP

    dns: 1.1.1.1
    environment:
      FRIGATE_RTSP_PASSWORD: "PWD"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell PoE-W (D340P-White) - Firmware: v3.0.0.4110_2410111128

### Any other information that may be helpful

When accessing the Frigate UI via HTTPS (port 8971) the 2-way audio works well.

However, I'm unable to get this to work in Home Assistant.

If in the Frigate card I select `go2rtc: modes:` = `webrtc` then the microphone button shows up in the menu, and the audio from the microphone of the device running the Home Assistant app to the speaker of the doorbell works fine. However, the audio from the doorbell microphone to the speaker of the device running the Home Assistant app does not work. The mute/unmute button does not show up in the card even if this is enabled in the card configuration.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell_camera
    engine: frigate
    live_provider: go2rtc
    title: Dorbell
    icon: mdi:doorbell-video
    go2rtc:
      modes:
        - webrtc
```

If in the Frigate card I select `go2rtc: modes:` = `MSE` then the mute/unmute button shows up in the menu, and the audio from the microphone of the doorbell to the speaker of the device running the Home Assistant app works fine. However, the microphone button does not show up in the card even if this is enabled in the card configuration and therefore there is no audio from the microphone of the device running the Home Assistant app to the speaker of the doorbell.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell_camera
    engine: frigate
    live_provider: go2rtc
    title: Dorbell
    icon: mdi:doorbell-video
    go2rtc:
      modes:
        - mse
```

How can I get both audio streams to work at the same time from Home Assistant?

**Comment by hawkeye217** [comment]
Since this is working fine with Frigate, you'll want to post on the advanced camera card's github for support. 

https://github.com/dermotduffy/advanced-camera-card#frigate-card-conditional-example

**Comment by JSa1987** [comment, marked as answer]
I have managed to solve this. The problem was with the following part of the Frigate config:
```
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"
```

That was causing the problem discussed [here](https://github.com/blakeblackshear/frigate/discussions/14027)  (i.e. overriding the ffmpeg path with an incomplete one).

As reference below is my working configuration  for 2 way audio with the White POE Reolink Doorbell:

```
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - Frigate_IP:8555
      - stun:8555
  ffmpeg:
    volume: -af "volume=10dB"
  streams:
    doorbell_camera:
      - rtsp://admin:PWD@Doorbell_IP:554/
      - ffmpeg:http://Doorbell_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PWD#audio=opus#audio=volume
    doorbell_camera_sub:
      - rtsp://admin:PWD@Doorbell_IP:554/h264Preview_01_sub
      - ffmpeg:http://Doorbell_IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=PWD#audio=opus#audio=volume
cameras:
  doorbell_camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell_camera
    onvif:
      host: Doorbell_IP
      port: 8000
      user: admin
      password: PWD
```

Probably this can be optimized a bit (I'm not sure the `doorbell_camera_sub` stream is needed, or if the `live` and `onvif` sections for the camera are actually needed).
