### DISCUSSION TITLE
[Config Support]: Diagonal Lines & Aspect Ratios

### DISCUSSION THREAD

**Discussion by lngarrett** [blakeblackshear/frigate#16644] [Config Support]
### Describe the problem you are having

I am having an issue getting my aspect ratios to behave properly. I have a Dahua with two streams: 2688x1520 (main) and 704x480 (sub).

Given this, there are two issues I'm trying to solve for. I seem to only be able to solve for one or the other. But, I'm sure I'm missing something config wise.

* On live view, the aspect ratio of the camera view jumps between the sub-stream and mainstream. Instead, I want the sub-stream to stretch wider. This seems to maintain the integrity of objects between the two streams as the substream is anamorphic (if I'm using the correct term.)

* I can't seem to find a detect height/width that doesn't cause the diagonal line issue. I've tried 854x480 and 853x480 but neither seems to work. 

I think I'm supposed to be setting detect width/height to a standard 16:9 ratio. But, that doesn't seem to be working in this case. 

### Version

0.15

### Frigate config file

```yaml
cameras:
  parkingcam:
    enabled: true
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@parkingcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@parkingcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      # width: 854
      # height: 480
    objects:
      track:
        - person
        # - car # spams on my truck
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
    zones:
      Near_Truck:
        coordinates: 0.002,0.698,0.001,0.549,0.169,0.273,0.94,0.436,0.919,0.997,0.003,0.999
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Near_Truck
  westcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        residential sidewalk and a driveway that run along the side of two houses.
        People in this are are likely coming and going from the two houses. The camera
        is turned to an angle so up is to the right.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@westcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@westcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
        - car
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
    zones:
      Near_House:
        coordinates: 0.002,0.992,0,0,0.756,0,0.943,0.525,0.972,0.996
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: Near_House
  bporchcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        residential back yard deck. There is a garage we own off in the distance.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@bporchcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@bporchcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
  byardcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        residential backyard. To the left is a garage, to the upper right is the house.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@byardcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@byardcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
  eastcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        residential yard. Our house is to the right and the neighbor's house is to
        the left.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@eastcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@eastcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
    motion:
      mask:
        - 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
        - 0.502,0.745,0.585,0.606,0.666,0.569,0.802,0.507,0.96,0.58,0.995,0.985,0.501,0.993
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Near_House:
        coordinates: 0,0.84,0.251,0.449,0.351,0.452,0.444,0.267,0.965,0.26,0.973,0.37,0.944,0.996,0,1
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: Near_House
  neighborcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        parking lot in a walkup condo unit. Residents come and go often, but also
        thieves might come at night.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@neighborcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@neighborcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
    motion:
      mask: 0.578,0.943,0.95,0.944,0.948,0.985,0.578,0.98
    zones:
      Near_House:
        coordinates: 0.014,0.98,0.014,0.863,0.064,0.869,0.065,0.981
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Near_House
  alleynwcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        back alley behind a residential garage. We call it an alley, not a road. There
        is a garage on the left just out of view - that is our house. The other buildings
        (including the black garage) are not ours. We care very much about people
        near our garage.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@alleynwcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@alleynwcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
        - car
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
    zones:
      Near_House:
        coordinates: 0.004,0.994,0.006,0.439,0.21,0.464,0.421,0.996
        inertia: 3
        loitering_time: 0
        objects: person
      In_Alley:
        coordinates: 0.029,0.045,0.048,0.442,0.208,0.459,0.428,0.997,1,1,1,0.767,0.118,0.05
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - Near_House
          - In_Alley
  alleysecam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        back alley behind a residential garage. We call it an alley, not a road. There
        is a garage on the right just out of view - that is our house. The other buildings
        are not ours. We care very much about people near our garage.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@alleysecam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@alleysecam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      # width: 854
      # height: 480
    objects:
      track:
        - person
        - car
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
    zones:
      Near_Garage:
        coordinates: 0.343,0.999,0.821,0.363,0.994,0.404,0.903,0.996
        loitering_time: 0
        objects: person
      In_Alley:
        coordinates: 
          0,0.497,0.545,0.218,0.588,0.227,0.843,0.1,0.994,0.103,0.978,0.388,0.82,0.356,0.336,1,0,1
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones:
          - Near_Garage
          - In_Alley
  porchcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks the
        residential front yard, sidewalk, and front porch of the house. The camera
        is on the porch. Stairs lead up fron the sidewalk to the porch.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@porchcam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@porchcam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
    review:
      alerts:
        required_zones: Near_House
    zones:
      Near_House:
        coordinates: 
          0.007,0.403,0.298,0.271,0.715,0.481,0.805,0.43,0.994,0.554,0.997,0.996,0.103,0.996
        inertia: 3
        loitering_time: 0
        objects: person
  walkwaycam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        sidewalk alongside a residential garage. To the right is a gate leading to
        the alley. To the left is the backyard. The camera is turned at an angle so
        up is to the right.
    ffmpeg:
      inputs:
        # Sub-stream
        - path: 
            rtsp://user:pass@walkwaycam.domain:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path: 
            rtsp://user:pass@walkwaycam.domain:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
      width: 854
      height: 480
    objects:
      track:
        - person
    motion:
      mask: 0.596,0.94,0.968,0.941,0.966,0.982,0.596,0.977
    review:
      alerts:
        required_zones: Near_House
    zones:
      Near_House:
        coordinates: 0,0.063,0.347,0.225,0.72,0.421,0.972,0.399,0.994,0.554,0.997,0.996,0,1
        inertia: 3
        loitering_time: 0
        objects: person
  foocam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        small child's bedroom. People in the room are probably taking care of the
        kid. Kid or kids often play here
    ffmpeg:
      inputs:
        # Sub-stream
        - path: rtsp://user:pass@foocam.domain:554/stream2
          roles:
            - detect
            - audio
        # Main-stream
        - path: rtsp://user:pass@foocam.domain:554/stream1
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
    objects:
      track:
        - person
    motion:
      mask:
        - 0.601,0.677,0.706,0.348,0.849,0.375,0.844,0.746
        - 0,0,0.352,0,0.353,0.046,0,0.046
  barcam:
    enabled: true
    genai:
      prompt: Analyze the sequence of images containing the {label}. Focus on the
        likely intent or behavior of the {label} based on its actions and movement,
        rather than describing its appearance or the surroundings. Consider what the
        {label} is doing, why, and what it might do next. This camera overlooks a
        small child's bedroom. People in the room are probably taking care of the
        kid. Kid or kids often play here
    ffmpeg:
      inputs:
        # Sub-stream
        - path: rtsp://user:pass@barcam.domain:554/stream2
          roles:
            - detect
            - audio
        # Main-stream
        - path: rtsp://user:pass@barcam.domain:554/stream1
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
    objects:
      track:
        - person
    motion:
      mask: 0.84,0.27,0.567,0.266,0.593,0.568,0.934,0.563,0.977,0.418,0.877,0.189
go2rtc:
  rtsp:
    username: admin
    password: password
  streams:
    parkingcam:
      - rtsp://user:pass@parkingcam.domain:554/cam/realmonitor?channel=1&subtype=0
    westcam:
      - rtsp://user:pass@westcam.domain:554/cam/realmonitor?channel=1&subtype=0
    bporchcam:
      - rtsp://user:pass@bporchcam.domain:554/cam/realmonitor?channel=1&subtype=0
    byardcam:
      - rtsp://user:pass@byardcam.domain:554/cam/realmonitor?channel=1&subtype=0
    eastcam:
      - rtsp://user:pass@eastcam.domain:554/cam/realmonitor?channel=1&subtype=0
    neighborcam:
      - rtsp://user:pass@neighborcam.domain:554/cam/realmonitor?channel=1&subtype=0
    alleynwcam:
      - rtsp://user:pass@alleynwcam.domain:554/cam/realmonitor?channel=1&subtype=0
    alleysecam:
      - rtsp://user:pass@alleysecam.domain:554/cam/realmonitor?channel=1&subtype=0
    porchcam:
      - rtsp://user:pass@porchcam.domain:554/cam/realmonitor?channel=1&subtype=0
    walkwaycam:
      - rtsp://user:pass@walkwayam.domain:554/cam/realmonitor?channel=1&subtype=0
    foocam:
      - rtsp://user:pass@foocam.domain:554/stream1
    barcam:
      - rtsp://user:pass@barcam.domain:554/stream1

detect:
  fps: 5

ui:
  time_format: 24hour

record:
  enabled: true
  retain:
    days: 15
    mode: all
  alerts:
    retain:
      days: 40
  detections:
    retain:
      days: 40
snapshots:
  enabled: true
auth:
  enabled: false
  trusted_proxies:
    - 172.18.0.0/16

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - car
      - person
      - dog
      - cat

objects:
  track:
    - person
    - car
    - dog
    - cat

tls:
  enabled: false

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

### OV IGPU

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

mqtt:
  enabled: true
  host: foobar.domain
  user: hass
  password: password

version: 0.15-1
camera_groups:
  Grid:
    order: 2
    icon: LuBoxSelect
    cameras:
      - parkingcam
      - westcam
      - bporchcam
      - byardcam
      - eastcam
      - neighborcam
      - alleynwcam
      - alleysecam
      - porchcam
      - walkwaycam
      - foocam
      - barcam
semantic_search:
  enabled: true
  model_size: large
  reindex: false

genai:
  enabled: true
  provider: ollama
  base_url: http://foo.domain:7869
  model: llava:7b
  prompt: Analyze the {label} in these images from the {camera} security camera. Focus
    on the actions, behavior, and potential intent of the {label}, rather than just
    describing its appearance.
```

### Relevant Frigate log output

```shell
na
```

### Relevant go2rtc log output

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.15.0-tensorrt
    shm_size: "1500mb"
    environment:
      - PLUS_API_KEY=123
    devices:
      - /dev/dri:/dev/dri
    cap_add:
      - CAP_PERFMON
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/warehouse/frigate:/config
      - /data/blueiris/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
      - frigate-secure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "127.0.0.1:8971:8971"  
      - "127.0.0.1:5050:5000" # note 5050 host port 
      - "127.0.0.1:8554:8554"  
      - "127.0.0.1:8555:8555"
```

### Object Detector

OpenVino
